### ISSUE TITLE
[DataCap Application] Gemdale group

### ISSUE THREAD

**Issue by linice** [filecoin-project/filecoin-plus-large-datasets#1000]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Gemdale Group
- Website / Social Media:https://www.gemdale.com/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):200TiB
- On-chain address for first allocation:f167x5eokj2rlemqwroakbudhezeqrziorokqypua

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Gemdale  Group is one of the top 500 companies in China. Gemdale group was founded in Shenzhen, China in 1988 and listed on the Shanghai Stock Exchange (600383. SH) in 2001. After decades of exploration and practice, it has developed into a comprehensive listed company with real estate development as its main business and related diversified businesses. The business covers real estate development, commercial real estate and industrial park and town development and operation, real estate finance, smart services, sports industry operation, home decoration industry, agent construction industry, education industry, etc. The business covers more than 280 large and medium-sized cities in China and 8 different cities and regions on the East and west coasts of the United States. As of December 31, 2021, Gemdale group had a total asset of about 462.8 billion yuan and a net asset attributable to shareholders of about 63 billion yuan. It has been listed in the Forbes 2000 global enterprises and the Fortune 500 China list for many consecutive years.
```

What is the primary source of funding for this project?
```
own capital.
```

What other projects/ecosystem stakeholders is this project associated with?
```
No.
```

## Use-case details

Describe the data being stored onto Filecoin
```
Data includes group publications, slideshows, training videos/audio and business data and service logs, etc.
```

Where was the data in this dataset sourced from?
```
- Publications are public offerings.
- These slides are made by the in-house team and are mainly used for the presentation of the business.
-The video and audio are recorded by ourselves.
- Lecture materials are produced by senior members of our team.
-Business data is data that requires cold backup.
- Service logs are regular logs for web services, DB services, file services, etc.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://drive.google.com/drive/folders/1-6HDnVRbLmOGvwoXXxOSsL2lNgiJ6FQm?usp=sharing
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes. All data is public and can be retrieved by anyone on the Network.
```

What is the expected retrieval frequency for this data?
```
Multiple times per year.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
At least three years.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Asia.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Yes, I choose offline data transfer primarily.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
I would ensure if they are credible for coorperation and their ability of actual deal recieving.
```

How will you be distributing deals across storage providers?
```
We plan having 5 SPs for deals and we may distribute deals to them for different percentage.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
I have all I need to start making deals.
```

**Comment by raghavrmadya** [comment]
It is unclear from your samples what you are looking to store. Please provide accurate and proper samples

**Comment by linice** [comment]
> It is unclear from your samples what you are looking to store. Please provide accurate and proper samples

Well, the previous sample is really a bit miscellaneous.
In fact, we mainly store logs and company related videos,
We have created some new samples:
https://drive.google.com/drive/folders/1QmADfecTZbTT3Lm_uft6UKURwE9tWDa6
https://drive.google.com/drive/folders/1mBjp9SOlquQuaN7YFnfSsKz-9YUWI4Ux

thank you!

**Comment by Sunnyiscoming** [comment]
Can you explain your data composition? How many logs and company related videos are there? How many copies will you store?
What's the relationship between you and the organization?
Can you provide more detailed information about other storage providers participated in this program, such as you can list SPs you have contacted with at present?

**Comment by linice** [comment]
> Can you explain your data composition? How many logs and company related videos are there? How many copies will you store? What's the relationship between you and the organization? Can you provide more detailed information about other storage providers participated in this program, such as you can list SPs you have contacted with at present?

Hello, @Sunnyiscoming,
I am an employee of the company, responsible for technical operation and service operation and maintenance.
As a real estate group with a history of more than 20 years, the group companies and their business entities have a huge amount of data that needs to be cold backed up. The data are mainly concentrated in logs (daily office monitoring, service platform logs [Web/DB/MQ/MAIL and other services]), and publicity materials that can be published by the media,

About 1 PB of logs and company videos, and about 200 TiB of other publicity data, I plan to store 5 copies of data.

I am an employee of the company, responsible for technical operation and maintenance.

I tried to contact some storage providers near the company, including New Web Group, MK Storage and other service providers. Their nodes include but are not limited to f049911, f01101196, f01900537, f01914991, f01036920, f0392813, f0149765 and f0816168.

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 200TiB

**Client address**

>f167x5eokj2rlemqwroakbudhezeqrziorokqypua

**Comment by Sunnyiscoming** [comment]
Hey @linice , if you still want to apply for datacap, you can ask notaries to do client due diligence in slack channel. https://app.slack.com/client/TEHTVS1L6/C036JKD8NVA/thread/C03BG1MNQ4T-1673888660.823499

**Comment by linice** [comment]
> Hey @linice , if you still want to apply for datacap, you can ask notaries to do client due diligence in slack channel. https://app.slack.com/client/TEHTVS1L6/C036JKD8NVA/thread/C03BG1MNQ4T-1673888660.823499

Hi @Sunnyiscoming, I got it. Thank you!

**Comment by mjroddy** [comment]
This would be better suited towards regular deals I believe.

“Filecoin Plus is a program that aims to maximize the amount of useful storage that Filecoin can and will support.

The ultimate goal of Filecoin Plus is to accelerate the timeframe over which storage goods and services on Filecoin become more useful and attractive. The program plays an essential role in shaping the product offering on the network in collaboration with storage miners.”

**Comment by igoovo** [comment]
I received an email confirming that this is a real application.

**Comment by liyunzhi-666** [comment]
@linice Please send me a copy (patricckk886@gmail.com) and the attachment should contain the business license.
Also please state again in the issue comments the miner ID you contacted and a sample of the data.

**Comment by liyunzhi-666** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaa7od573rkcseydssho6ozz4ospyga3ujomiyqmgclkg7ncrxszu 
#### Address 
> f167x5eokj2rlemqwroakbudhezeqrziorokqypua
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1pszcrsciyixyuxxukkvtazcokexbn54amf7gvoq
#### Id
> e4922c71-2429-48fe-8750-5f33930e9446
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaa7od573rkcseydssho6ozz4ospyga3ujomiyqmgclkg7ncrxszu

**Comment by luobin544** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaqckfojzwhn4cojne2f4fafmf5zvlbhht3ahu7sfmggbruzq357q 
#### Address 
> f167x5eokj2rlemqwroakbudhezeqrziorokqypua
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1tbd632f6w62glfaf7wjpimacbnjiz26poyoes2q
#### Id
> 163b120e-7e03-4f67-a1c3-274b00cffbc1
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaqckfojzwhn4cojne2f4fafmf5zvlbhht3ahu7sfmggbruzq357q

**Comment by mikezli** [comment]
checker:manualTrigger

**Comment by mikezli** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedl5yung6ubinosnunhkelf2gqymzpyf3dwaf5gye3w4m3rmcsxy2 
#### Address 
> f167x5eokj2rlemqwroakbudhezeqrziorokqypua
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1dnb3uz7sylxk6emti3ififcvu3nlufnnsjui6ea
#### Id
> 163b120e-7e03-4f67-a1c3-274b00cffbc1
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedl5yung6ubinosnunhkelf2gqymzpyf3dwaf5gye3w4m3rmcsxy2

**Comment by mikezli** [comment]
The customer contacted me, promising to increase the retrieval rate, and promised that there would be a better distribution plan. Considering that this is the second round of packaging for the customer, I will support them temporarily and I will keep an eye on it.

**Comment by i0k24** [comment]
checker:manualTrigger

**Comment by Normalnoise** [comment]
checker:manualTrigger

**Comment by liyunzhi-666** [comment]
Why is the success rate for all searches below 1%?

**Comment by linice** [comment]
> Why is the success rate for all searches below 1%?

There is really not much data to retrieve at the moment.
The reason is that the failure is caused by the improper modification of the miner process code by the employee who performed the encapsulation operation. That it can't be retrieved.

Now, in the process of full recovery of organizational strength, searchability can be restored to a considerable state by one week at the latest.

Please wait patiently for some time, thank you for your understanding!

**Comment by liyunzhi-666** [comment]
Before solving these disputes and the success rate of retrieval, I suggest to suspend this application and contact SP to solve the problem first.

**Comment by igoovo** [comment]
checker:manualTrigger

**Comment by i0k24** [comment]
checker:manualTrigger

**Comment by linice** [comment]
> Before solving these disputes and the success rate of retrieval, I suggest to suspend this application and contact SP to solve the problem first.

I contacted SP, and they are continuing to fix the failure.
It's okay to see the effect now.

Request to continue with the packaging , thank you!

**Comment by Normalnoise** [comment]
⚠️ 81.22% of deals are for data replicated across less than 4 storage providers.

@linice can you explain this?

**Comment by linice** [comment]
> ⚠️ 81.22% of deals are for data replicated across less than 4 storage providers.
> 
> @linice can you explain this?

I have already responded to this question with SP, and they replied that this number will be reduced to the rule in the next round.
Thank you!

**Comment by Normalnoise** [comment]
Hope to follow the Fil+ rule，willing to support in the round. I will keep my eyes on the next distribution

**Comment by Normalnoise** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec7afw4lykzcpcfyksruen7vtfzluatb5j5r44xrlwvygps2iilam 
#### Address 
> f167x5eokj2rlemqwroakbudhezeqrziorokqypua
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1c5non5yf35avgcpsqvxu4yj54yyvxorwyjochqq
#### Id
> bb35ceaa-0a9c-4ee0-95ff-4018163ef700
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec7afw4lykzcpcfyksruen7vtfzluatb5j5r44xrlwvygps2iilam

**Comment by Tom-OriginStorage** [comment]
Other notaries have completed the investigation and are willing to support it

**Comment by Tom-OriginStorage** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedye4fdykas4dggcbclgfdxz5zyru35puy44tuou4iuw53vfvwyoy 
#### Address 
> f167x5eokj2rlemqwroakbudhezeqrziorokqypua
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1q6bpjlqia6iemqbrdaxr2uehrhpvoju3qh4lpga
#### Id
> bb35ceaa-0a9c-4ee0-95ff-4018163ef700
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedye4fdykas4dggcbclgfdxz5zyru35puy44tuou4iuw53vfvwyoy

**Comment by igoovo** [comment]
checker:manualTrigger

**Comment by igoovo** [comment]
⚠️ 72.41% of deals are for data replicated across less than 4 storage providers.

Please pay attention to the above tips.
Please continue to distribute storage reasonably.

**Comment by igoovo** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebfvpunuqccjlvb6l6goo4ktk65ovcy6o3mu2dwbbhl2t4243flqy 
#### Address 
> f167x5eokj2rlemqwroakbudhezeqrziorokqypua
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1shnsfayxqll77svffaxnjenms7bbbysbqcatrpy
#### Id
> 072ec61a-8160-4277-9a21-1859a701ee7f
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebfvpunuqccjlvb6l6goo4ktk65ovcy6o3mu2dwbbhl2t4243flqy

**Comment by sxxfuture-official** [comment]
@linice 
More SPs should be added, pay attention to the replica num.
Retrieval report looks good , will support and will continue to pay attention.

**Comment by sxxfuture-official** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebmrcela4l7boxjjbgtqpqjagza2g3o4loitehtwumisgmedv5fe2 
#### Address 
> f167x5eokj2rlemqwroakbudhezeqrziorokqypua
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1foiomqlmoshpuxm6aie4xysffqezkjnokgwcecq
#### Id
> 072ec61a-8160-4277-9a21-1859a701ee7f
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebmrcela4l7boxjjbgtqpqjagza2g3o4loitehtwumisgmedv5fe2

**Comment by igoovo** [comment]
checker:manualTrigger

**Comment by igoovo** [comment]
checker:manualTrigger

**Comment by igoovo** [comment]
checker:manualTrigger

**Comment by OpenGate01** [comment]
Looking forward to more copies of the same data in the next round,

**Comment by OpenGate01** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedxqkrphw3wtedhxbdcbuyu4rf7kstavcp3exzkwl2agio4yzm6ca 
#### Address 
> f167x5eokj2rlemqwroakbudhezeqrziorokqypua
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1im4hmtbfzqnx7ir74kdaiu4ynjhgqh3sdi2snla
#### Id
> 072ec61a-8160-4277-9a21-1859a701ee7f
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedxqkrphw3wtedhxbdcbuyu4rf7kstavcp3exzkwl2agio4yzm6ca

**Comment by kernelogic** [comment]
Report LGTM, also no open dispute.

**Comment by kernelogic** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacea4j4necwftinr4gonk76kmwnjqdpjowuw47dygiz3ebwtbtucjgi 
#### Address 
> f167x5eokj2rlemqwroakbudhezeqrziorokqypua
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### Id
> 072ec61a-8160-4277-9a21-1859a701ee7f
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacea4j4necwftinr4gonk76kmwnjqdpjowuw47dygiz3ebwtbtucjgi

**Comment by igoovo** [comment]
checker:manualTrigger

**Comment by nj-steve** [comment]
checker:manualTrigger

**Comment by nj-steve** [comment]
Look into The Gemdale Group, This is a respectable company and they are welcome to join filecoin data storage. 
But from the report:
Deal Data Replication
⚠️ 88.67% of deals are for data replicated across less than 4 storage providers.
Your You should send data replicated to more than 4 storage providers to conforms to fil+ rules.
Do you have any plan to solve this problem？Please show the plan to us.

**Comment by cryptowhizzard** [comment]
I am doing due diligence and would like to review this data. When i tried to download / retrieve on all your SP's the download speed is universally slow ( 1 mbit/s ). Is this some type of agreement you made?
This makes downloading nearly impossible. Reason i ask you:

Can you make piece CID baga6ea4seaqnjcqy7hmqmfrthzizlxdw4jkijrlrnnsbatsh6njksdiyj57ocni available on an URL to download somewhere so i can check what's inside and if it is consistent?


lotus state get-deal 45503401
{ 
  "Proposal": {
    "PieceCID": {
      "/": "baga6ea4seaqnjcqy7hmqmfrthzizlxdw4jkijrlrnnsbatsh6njksdiyj57ocni"
    },
    "PieceSize": 34359738368,
    "VerifiedDeal": true,
    "Client": "f02224283",
    "Provider": "f01850726",
    "Label": "bafykbzacectdd2isgsggcuxciafvc7tycytnfoew24lqn5ia5wxwbh5375ngm",
    "StartEpoch": 3039178,
    "EndEpoch": 4075978,
    "StoragePricePerEpoch": "0",
    "ProviderCollateral": "10309095591231368",
    "ClientCollateral": "0"
  },
  "State": {
    "SectorStartEpoch": 3024899,
    "LastUpdatedEpoch": -1,
    "SlashEpoch": -1,
    "VerifiedClaim": 27815830
  }
}
root@proposals:~/downloadedc

**Comment by linice** [comment]
In order to prevent hackers from attacking, some SP do use VPN, which leads to slow download speed.
There is no way to do this, you can successfully download the file, although the process is slow, please hold on patiently.
Thank you!

**Comment by linice** [comment]
"This is 88.67% of deals are for data replicated across less than 4 storage providers."

This matter has been fed back to SP, and I ask them to pay attention to it and comply with the rules.
Thank you for your suggestion!

**Comment by nj-steve** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedhpa6nm7cq3bebwswgknsfbii75mmnolo7do4ptf5mnlqck4l54s 
#### Address 
> f167x5eokj2rlemqwroakbudhezeqrziorokqypua
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1xx6555qijma7igpnjspyvdunc4vfxkawnpqy5ii
#### Id
> 9ad067fc-4ab3-4ea8-a1b3-1d295299cc5e
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedhpa6nm7cq3bebwswgknsfbii75mmnolo7do4ptf5mnlqck4l54s

**Comment by nj-steve** [comment]
@linice you should also solve problems from other notaries to get more support.

**Comment by cryptowhizzard** [comment]
> In order to prevent hackers from attacking, some SP do use VPN, which leads to slow download speed. There is no way to do this, you can successfully download the file, although the process is slow, please hold on patiently. Thank you!

I tried downloading but it keeps going timeout because of the slow speed. Please have your SP's upgrade retrieval speed so we can test what you are storing. At this moment we can't , that is against FIL+ rules.

@nj-steve 

Why do you sign while i am doing due diligence?

**Comment by nj-steve** [comment]
Hello @cryptowhizzard Thank you for reminding me. 
I didn't see you warning me of a major issue to stop sign. You all said the SP support  retrieval, and the retrieval success rate is so high, that I really thought you have checked the files before I signed. 
And I also left a message for this client, asking this client to support requests from other notaries for getting more support, because everyone has a different direction of doing due diligence.
Thanks for your hard work.

**Comment by cryptowhizzard** [comment]
> Hello @cryptowhizzard Thank you for reminding me. I didn't see you warning me of a major issue to stop sign. You all said the SP support retrieval, and the retrieval success rate is so high, that I really thought you have checked the files before I signed. And I also left a message for this client, asking this client to support requests from other notaries for getting more support, because everyone has a different direction of doing due diligence. Thanks for your hard work.

Hi @nj-steve 

The LDN application indicates that it supports public retrieval. I don't think your SP's are prepared for this so i am trying to steer you in the right direction since 18 months is a long time .. ;-)

Can you arrange this with your current SP's?

**Comment by nj-steve** [comment]
Hello @cryptowhizzard 
That is not my SP. I have left a message suggesting client contact the SP to support your work.

**Comment by ipollo00** [comment]
checker:manualTrigger

**Comment by ipollo00** [comment]
DD:
Except for the data backup issue, other parts of this application form performed well.
I checked the report from 5 days ago and compared it with today. Among them, there is a significant improvement in the data backup of three and four copies. In my judgment, this client is building trust in my mind. Willing to support.
@linice 
Also, how do you think about HTTP retrieval? When your cooperate sps will support it?

**Comment by cryptowhizzard** [comment]
Recv 8.82 GiB, Paid 0 FIL, BlocksReceived (Ongoing), 4h37m54.15s [1690024162200370517|9470170149]
Recv 8.821 GiB, Paid 0 FIL, BlocksReceived (Ongoing), 4h37m56.143s [1690024162200370517|9471218725]
Recv 8.822 GiB, Paid 0 FIL, BlocksReceived (Ongoing), 4h37m57.804s [1690024162200370517|9472267301]
Recv 8.823 GiB, Paid 0 FIL, BlocksReceived (Ongoing), 4h37m59.003s [1690024162200370517|9473315877]
Recv 8.824 GiB, Paid 0 FIL, BlocksReceived (Ongoing), 4h38m0.956s [1690024162200370517|9474364453]
Recv 8.825 GiB, Paid 0 FIL, BlocksReceived (Ongoing), 4h38m1.735s [1690024162200370517|9475413029]
Recv 8.826 GiB, Paid 0 FIL, BlocksReceived (Ongoing), 4h38m2.537s [1690024162200370517|9476461605]
Recv 8.827 GiB, Paid 0 FIL, BlocksReceived (Ongoing), 4h38m9.345s [1690024162200370517|9477510181]
Recv 8.828 GiB, Paid 0 FIL, BlocksReceived (Ongoing), 4h38m11.472s [1690024162200370517|9478558757]
Recv 8.829 GiB, Paid 0 FIL, BlocksReceived (Ongoing), 4h38m12.262s [1690024162200370517|9479607333]
Recv 8.829 GiB, Paid 0 FIL, DataTransferError (Erroring), 4h38m31.254s [1690024162200370517|9479607333]
Recv 8.829 GiB, Paid 0 FIL, BlockstoreFinalized (Errored), 4h38m31.283s [1690024162200370517|9479607333]
ERROR: Retrieval Error: error generated by data transfer: deal data transfer failed: data transfer channel 12D3KooWAhG3BRy2RhVgMbvBNyq5z61JwFYHcmEXopGm5pw54QdW-12D3KooWP9QL4z6Qsmz6A2Ufmz1oeNiqB1hCLrNjE4jDoo3LBkP9-1690024162185103051 failed to transfer data: channel 12D3KooWAhG3BRy2RhVgMbvBNyq5z61JwFYHcmEXopGm5pw54QdW-12D3KooWP9QL4z6Qsmz6A2Ufmz1oeNiqB1hCLrNjE4jDoo3LBkP9-1690024162185103051: graphsync request failed to complete: error traversing node at "Links/8/Hash/Links/848/Hash": could not load link "bafk2bzacearfmwzwutt6knjg6yfkgmxhplyg7pppc72sol4i4nn3eokspzkts": expected link (bafk2bzacearfmwzwutt6knjg6yfkgmxhplyg7pppc72sol4i4nn3eokspzkts) at path Links/8/Hash/Links/848/Hash does not match link sent by remote (bafk2bzacealsvcvjk3kjnm2xlwgbnl7nrijxbhg5sij6yrxrcjjypc4auz3q6), possible malicious responder

Can you please fix your retrieval so we can check what you are storing?

**Comment by cryptowhizzard** [comment]
@ipollo00 

Retrieval is not working for this client at the moment. It should be fixed before you sign.

**Comment by a1991car** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedtsxbho426iuqefzagujdxv5joioa7evl4v2udl4bjlry53mikty 
#### Address 
> f167x5eokj2rlemqwroakbudhezeqrziorokqypua
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1qnumecdypgrbaebtkdfjnwt5ndacadcuas3deiq
#### Id
> 12e2361e-21a6-4c6d-85be-cc22ece556a3
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedtsxbho426iuqefzagujdxv5joioa7evl4v2udl4bjlry53mikty

**Comment by linice** [comment]
I gave feedback to SP, and their reply can be retrieved and downloaded.

![57a1b1c1c59a1b5b9664d0600e49a58](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/6425979/ff5d87b1-fb90-416c-a8f0-569d60226c88)
![634726820960bbb6d2b6793405321c4](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/6425979/aa77a5a1-b043-462f-bb9d-99ab2e6149b9)

**Comment by ipollo00** [comment]
Why not?  I randomly check three nodes, and it all works. 
![21221690518095_ pic](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/116627408/6dd4d6f3-2fb0-48a3-8221-fe78ad473a10)
![21231690518102_ pic](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/116627408/c3a822c4-8da8-4c7e-a0df-206dcb86b079)
![21241690518108_ pic](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/116627408/0332b5bb-28c4-4559-a675-e82e88be30c7)

**Comment by cryptowhizzard** [comment]
@ipollo00 

did you try the whole file?

**Comment by ipollo00** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceah7xbbpadingogvgjlywak7o52aqyes6pf6whrbxw5wg6leuqoco 
#### Address 
> f167x5eokj2rlemqwroakbudhezeqrziorokqypua
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1n5wlrrhoxpkgwij25xrtt7w7g2k3fhbthmdn6ri
#### Id
> 12e2361e-21a6-4c6d-85be-cc22ece556a3
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceah7xbbpadingogvgjlywak7o52aqyes6pf6whrbxw5wg6leuqoco

**Comment by linice** [comment]
Yes, the data file can be downloaded completely.

**Comment by igoovo** [comment]
checker:manualTrigger

**Comment by Chuangshi1** [comment]
Deal Data Replication Pay attention to that.!

**Comment by Chuangshi1** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecn45ldx5we2hiry572rcko7vcl4wn6u2yi5ephrjwhtvelh5dlnm 
#### Address 
> f167x5eokj2rlemqwroakbudhezeqrziorokqypua
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1mdk7s2vntzm6hu35yuo6vjubtrpfnb2awhgvrri
#### Id
> f3446365-5b12-4b37-adc6-c899ae0e08e3
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecn45ldx5we2hiry572rcko7vcl4wn6u2yi5ephrjwhtvelh5dlnm

**Comment by a1991car** [comment]
Retrieval looks good, please improve backup data

**Comment by a1991car** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceabzqmgnb76ap5e5aeeym6c2rzrewafznpa6lbqfdchwadru3nu3o 
#### Address 
> f167x5eokj2rlemqwroakbudhezeqrziorokqypua
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1qnumecdypgrbaebtkdfjnwt5ndacadcuas3deiq
#### Id
> f3446365-5b12-4b37-adc6-c899ae0e08e3
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceabzqmgnb76ap5e5aeeym6c2rzrewafznpa6lbqfdchwadru3nu3o

**Comment by lupiruw** [comment]
checker:manualTrigger

**Comment by woshidama323** [comment]
>82.57% of deals are for data replicated across less than 4 storage providers.

May i ask what your plan about improving this warning ?

**Comment by linice** [comment]
This will do its best to ensure the balance. Thank you！

**Comment by a1991car** [comment]
The data backup looks not too good, why is this happening, how can you improve?

**Comment by linice** [comment]
On this issue, we have cooperated with 64G nodes and 32G nodes. In fact, the data are all the same, but the data formats of 64G and 32G are different.
Thank you for your concern!

**Comment by a1991car** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceapkubcjkzj3bqaqgmd2jyu7oz4nqiuruigniwjmnoj6fd4unpang 
#### Address 
> f167x5eokj2rlemqwroakbudhezeqrziorokqypua
#### Datacap Allocated
> 420.00TiB
#### Signer Address
> f1qnumecdypgrbaebtkdfjnwt5ndacadcuas3deiq
#### Id
> 10ccbd03-ca81-414b-9a06-bb50448586a9
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceapkubcjkzj3bqaqgmd2jyu7oz4nqiuruigniwjmnoj6fd4unpang

**Comment by PluskitOfficial** [comment]
> Overall HTTP retrieval success rate: 0.00%
> Overall Bitswap retrieval success rate: 0.00%
@linice Most results seem pretty good, but could you explain why these two parts have such a low success rate?

**Comment by linice** [comment]
I reported this to SP, and they replied that they would deploy HTTP's search tool in the near future.
@PluskitOfficial

**Comment by PluskitOfficial** [comment]
I'll sign this round. Hope to solve the problem next time.

**Comment by PluskitOfficial** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceciso64p5fadm2yw7cjc5mqdz7fw3rlef4n4fwd4obk5fpmyyf3qo 
#### Address 
> f167x5eokj2rlemqwroakbudhezeqrziorokqypua
#### Datacap Allocated
> 420.00TiB
#### Signer Address
> f1tgnlhtcmhwipfm7thsftxhn5k52velyjlazpvka
#### Id
> 10ccbd03-ca81-414b-9a06-bb50448586a9
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceciso64p5fadm2yw7cjc5mqdz7fw3rlef4n4fwd4obk5fpmyyf3qo
