### ISSUE TITLE
[DataCap Application] Shenzhen Bowen Big Data Technology Co., Ltd. - BWN

### ISSUE THREAD

**Issue by changelo** [filecoin-project/filecoin-plus-large-datasets#1003]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Shenzhen Bowen Big Data Technology Co., Ltd.
- Website / Social Media: www.bowenbigdata.com
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 2PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100TiB
- On-chain address for first allocation: f3rtlqil5ymgcck7itpv37cs744tpvhcpypa5mpqmcujuyb5zkmtsklohkf6llh7hrfnkz3632pycqumawbp3a

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Shenzhen Bowen Big Data Technology Co., Ltd founded in September 2021, is a professional supply block chain service provider. Engaged in software and services related to blockchain technology; Big data service; Software development; Basic software development of artificial intelligence; Data processing and storage support services; Information technology consulting services; Data processing service; Cloud computing equipment technology services; Retail of computer software, hardware and auxiliary equipment; Software sales; Cloud computing equipment sales; Sales of IoT equipment; Sales of calculator equipment; Information system integration services.
The Bowen Netdisk (BWN) is file management and sharing system base IPFS distributed storage. 

Features:
	Upload/download supports direct client transmission and download speed limit.
	The offline download of Aria2 is integrated, and multiple slave nodes can be used to share the download task.
	Online compression/decompression, multi file packaging and downloading.
	WebDAV protocol support covering all storage policies.
	Drag upload, directory upload, streaming upload processing.
	File drag management.
	Multiuser, user group.
	Create sharing links of files and directories, and set automatic expiration.
	Online preview of video, image, audio, text and office document.
```

What is the primary source of funding for this project?
```
Shenzhen Bowen Big Data Technology Co., Ltd.
```

What other projects/ecosystem stakeholders is this project associated with?
```
No.
```

## Use-case details

Describe the data being stored onto Filecoin
```
File types include text, pictures, audio, video and other types.
```

Where was the data in this dataset sourced from?
```
the all files from user's upload or download from internet.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://ipfs.io/ipfs/QmXZXavXRmgu9EryFzcBEp47DJZkGAySDQhZBAcJz8y3aV?filename=Laravel5.1_learn_test_1.zip
https://ipfs.io/ipfs/QmZQ6m2vLmzRTXFfmkrYsMQyXDCXBHQDxFiKreAkEKf58Q?filename=yele_lesson_test_01.zip
https://ipfs.io/ipfs/QmTWABFUzdQ3LhPGg3PhKD8SosTFtM2qtCGnUU9R8j8tK5?filename=test.data
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
the private files are encrypted before save to filecoin, so this is a publicly retrievable public dataset and all the files have.
```

What is the expected retrieval frequency for this data?
```
The frequency of retrieval depends on the user's needs.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
We plan to store it permanently.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Asia.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Online deal only in first phase.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We have selected more than 10 miners around us with good reputation, trustworthiness, and experience in verifying data to conduct transactions, we will cooperate for a long time with reputable miners.
```

How will you be distributing deals across storage providers?
```
Each file will be stored 2 copies on the Filecoin network, and seal them with the fast retrieval option. When a sector error is detected, the system will reseal to a new miner to ensure the safety and availability of the file.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, we have resources and funds to start making deals as soon as we receive Datacap.
Efficient and stable retrieval will make the filecoin network more perfect, looking forward to solutions from the community, thank you for the hard work of the community.
Please let us know if other information needed. Thank you!
```

**Comment by raghavrmadya** [comment]
What's the breakdown of 2 PiBs?

**Comment by changelo** [comment]
> 

The proportion of each document type is:
Video: 43.5%
Picture: 26.5%
Audio: 12%
Document: 18%

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 2PiB

**Expected weekly DataCap usage rate**

> 100TiB

**Client address**

> f3rtlqil5ymgcck7itpv37cs744tpvhcpypa5mpqmcujuyb5zkmtsklohkf6llh7hrfnkz3632pycqumawbp3a

**Comment by changelo** [comment]
Greetings! We are ready to use DataCap to make storage deals. What other materials do we need to provide? @raghavrmadya

**Comment by Sunnyiscoming** [comment]
Hey @changelo  , if you still want to apply for datacap, you can ask notaries to do client due diligence in slack channel. https://app.slack.com/client/TEHTVS1L6/C036JKD8NVA/thread/C03BG1MNQ4T-1673888660.823499

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Looking at your application i have some questions:
As you are brand new on Github and have no history of past applications it seems to me that applying for 2PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?

Can you show us visible proof of the size of your data and the storage systems you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230337462961356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!

**Comment by data-programs** [comment]
<img width="32" alt="KYC" Verified src="https://stable.filplus.storage/images/filplus-kyc-verified-badge.png"/>

This user’s identity has been verified through [filplus.storage](https://filplus.storage)
