### ISSUE TITLE
[DataCap Application] Homebloc smart  platform 

### ISSUE THREAD

**Issue by liuanxin** [filecoin-project/filecoin-plus-large-datasets#1009]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Homebloc 
- Website / Social Media: https://homebloc.io/ 
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 3PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):  200TiB
- On-chain address for first allocation: f1rf3tdlmk4x3y4dwmwb6rbxcl62rycxlfqfqgvva

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Homebloc is a smart contract platform for rental and property ownership trading. Users can generate and search for ERC 721 tokens that represent rental and property information on the platform. The system uses HOME token, an ERC 20 token, issued by the platform to reward users for contributing data and traffic to the platform. Based on the possession of the platform tokens and credit scores, established through reviews on the platform, users can be allocated a certain benefit to further raise credit scores and promote the development of platform. The role of consumers change from traditional consumers to investors of the platform.
At the same time, the company provides customers with the digital work of house design and decoration scheme. These business processes have generated a large volume of data, but the frequency of use is not high.
```

What is the primary source of funding for this project?
```
The customer pays our service fee and transaction commission.
```

What other projects/ecosystem stakeholders is this project associated with?
```
There is no other projects/ecosystem stakeholders associated with.
```

## Use-case details

Describe the data being stored onto Filecoin
```
Our business development involves a large number of 3D model datasets, including design video, customer discussion audio, visual design draft and other application scenario improvements, including video, audio, 3D models, images, etc.
```

Where was the data in this dataset sourced from?
```
Data sets mainly come from models created by employees in the business process and reference cases provided by customers.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://pan.baidu.com/s/1SL37JuR-OZNHcsMgbAdMjg?pwd=lk8m
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes, we confirm this is a public dataset that can be retrieved by anyone on the network with no specific permissions or access rights required.
```

What is the expected retrieval frequency for this data?
```
No special retrieval frequency and maybe it’s probably three times a year or more.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
Expectedly 3 years and it’s likely to be extended afterwards.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
We plans to make the deals in Asia, like: Sigapore,Vietnam or Philippines,etc.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Prefer online, if needed offline can also be considered.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
Well, we want to choose multiple miners with good size and credit in filecon's ecosystem.
```

How will you be distributing deals across storage providers?
```
We would divide the data up and send it to different miners.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, we have got some advices and resources from the community to make deals. We don’t need funding,and we need to get more weekly allocation of DC requested, About 200T per week.
```

**Comment by raghavrmadya** [comment]
Unable to access data samples are link is expired. Please update

**Comment by liuanxin** [comment]
> Unable to access data samples are link is expired. Please update

We updated the data sample link, and the new connection is (https://pan.baidu.com/s/1XP4mTiDJycibSRb_EJtM9A?pwd=1svy ), thank you!

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 3PiB

**Expected weekly DataCap usage rate**

> 200TiB

**Client address**

>f1rf3tdlmk4x3y4dwmwb6rbxcl62rycxlfqfqgvva

**Comment by Sunnyiscoming** [comment]
Hey @liuanxin , if you still want to apply for datacap, you can ask notaries to do client due diligence in slack channel. https://app.slack.com/client/TEHTVS1L6/C036JKD8NVA/thread/C03BG1MNQ4T-1673888660.823499

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Looking at your application i have some questions:
As you are brand new on Github and have no history of past applications it seems to me that applying for 3PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?

Can you show us visible proof of the size of your data and the storage systems you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230232885049356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!

**Comment by igoovo** [comment]
Look at the application list, it's quite reasonable.

**Comment by igoovo** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebk5twglxpe3yjrgpr4i2io5hzzyaljxspfrk3r6wz2m4r7hdbuwq 
#### Address 
> f1rf3tdlmk4x3y4dwmwb6rbxcl62rycxlfqfqgvva
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1shnsfayxqll77svffaxnjenms7bbbysbqcatrpy
#### Id
> 16f63477-eee8-405c-a3fd-02045ec32ef1
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebk5twglxpe3yjrgpr4i2io5hzzyaljxspfrk3r6wz2m4r7hdbuwq

**Comment by mikezli** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaigkrp6pdw44g5ny2j4qeoemyga322q6kh564jkhigy3ms6c2i4q 
#### Address 
> f1rf3tdlmk4x3y4dwmwb6rbxcl62rycxlfqfqgvva
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1dnb3uz7sylxk6emti3ififcvu3nlufnnsjui6ea
#### Id
> 16f63477-eee8-405c-a3fd-02045ec32ef1
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaigkrp6pdw44g5ny2j4qeoemyga322q6kh564jkhigy3ms6c2i4q

**Comment by igoovo** [comment]
You can use your official domain name to [filplus-app-review@fil.org](mailto:filplus-app-review@fil.org) Send email and copy to [goovolvo@gmail.com](mailto:goovolvo@gmail.com) To confirm your identity? The email name should include question ID # 1009.

Thank you!

**Comment by igoovo** [comment]
![1689649902712](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/103082537/b3c734d5-8dc2-4422-aad7-f772e48d7358)
I received an email confirming that it was sent by email under the official domain name.

**Comment by simonkim0515** [comment]
## DataCap Allocation requested

#### Multisig Notary address
> f02049625

#### Client address
> f1rf3tdlmk4x3y4dwmwb6rbxcl62rycxlfqfqgvva

#### DataCap allocation requested
> 100TiB

#### Id
> 5c6fb3b3-3f98-4676-b2dd-5aa40373c295

**Comment by kernelogic** [comment]
checker:manualTrigger

**Comment by kernelogic** [comment]
checker:manualTrigger f1rf3tdlmk4x3y4dwmwb6rbxcl62rycxlfqfqgvva

**Comment by stcouldlisa** [comment]
checker:manualTrigger

**Comment by Bitrise0111** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceduda3lmdlv2r467if5edvkpkbyxomvmlrhhdaxinpl3zychidcwe 
#### Address 
> f1rf3tdlmk4x3y4dwmwb6rbxcl62rycxlfqfqgvva
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1nknj7ayq4o43czrtdoauggtwl43fbqatmqis3yy
#### Id
> 5c6fb3b3-3f98-4676-b2dd-5aa40373c295
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceduda3lmdlv2r467if5edvkpkbyxomvmlrhhdaxinpl3zychidcwe

**Comment by SuperChaiChai** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedaorwwk3yknuw4cljzr2mhokt4povcqmigx6n3gvyz6g726je2js 
#### Address 
> f1rf3tdlmk4x3y4dwmwb6rbxcl62rycxlfqfqgvva
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f12mckci3omexgzoeosjvstcfxfe4vqw7owdia3da
#### Id
> 5c6fb3b3-3f98-4676-b2dd-5aa40373c295
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedaorwwk3yknuw4cljzr2mhokt4povcqmigx6n3gvyz6g726je2js

**Comment by Aaron01230** [comment]
checker:manualTrigger

**Comment by Aaron01230** [comment]
retrieval success rate is high and SP distribution is healthy , i will support this round

**Comment by Aaron01230** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecjxchkm4yzeovfm5he7ozgn3gmbnocckyvbiegsg763c7itmehnu 
#### Address 
> f1rf3tdlmk4x3y4dwmwb6rbxcl62rycxlfqfqgvva
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1xrnysd4gimg64d4l6qi7ulzwwq22c6vfg6lpw3i
#### Id
> 1ad78f0c-efd3-419d-8a31-79e29c013581
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecjxchkm4yzeovfm5he7ozgn3gmbnocckyvbiegsg763c7itmehnu

**Comment by YuanHeHK** [comment]
manualTrigger

**Comment by YuanHeHK** [comment]
checker:manualTrigger

**Comment by YuanHeHK** [comment]
This application CID check is very perfect, the search report in my opinion is also good, in this search query when the overall search success rate reached an average of 60%. Overall, it is very compliant with fil+ specifications.
![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/69455705/d45d3d7f-b76b-4fc3-be27-e23763d1f984)

So I'm going to support it this time. However, there are still 3 nodes with a search rate below 50%, and you should continue to improve this success rate, otherwise the back sleeve may not be supported. In addition, I have noticed that HTTP retrieval and Bitswap retrieval are also proposed to be upgraded.

**Comment by YuanHeHK** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacednakdaqkvuqd6jvduh5lrpimxz6o6wramnwlapivo23dwnmyjqvk 
#### Address 
> f1rf3tdlmk4x3y4dwmwb6rbxcl62rycxlfqfqgvva
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1fg6jkxsr3twfnyhdlatmq36xca6sshptscds7xa
#### Id
> 6375e4ed-fd29-4563-ab76-d8703ca2853b
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacednakdaqkvuqd6jvduh5lrpimxz6o6wramnwlapivo23dwnmyjqvk

**Comment by sxxfuture-official** [comment]
checker:manualTrigger

**Comment by sxxfuture-official** [comment]
Good at CID checker report and Retrieval repost , will support this round!

**Comment by sxxfuture-official** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceavanq52c3t2dyobpwyzxvwkaaorn2h4renhu77kw5h5ywo2m2v5a 
#### Address 
> f1rf3tdlmk4x3y4dwmwb6rbxcl62rycxlfqfqgvva
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1foiomqlmoshpuxm6aie4xysffqezkjnokgwcecq
#### Id
> 6375e4ed-fd29-4563-ab76-d8703ca2853b
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceavanq52c3t2dyobpwyzxvwkaaorn2h4renhu77kw5h5ywo2m2v5a

**Comment by kernelogic** [comment]
checker:manualTrigger

**Comment by kernelogic** [comment]
High retrieval success rate, CID distribution looks OK but please try store some in other continents.

**Comment by kernelogic** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecwsatczcy74mfsrzwmzhtv5yjmi7gtqmreofevy5avo6vghrraom 
#### Address 
> f1rf3tdlmk4x3y4dwmwb6rbxcl62rycxlfqfqgvva
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### Id
> 0b60d3c9-f2c2-4989-be16-978a90e59806
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecwsatczcy74mfsrzwmzhtv5yjmi7gtqmreofevy5avo6vghrraom

**Comment by liuanxin** [comment]
We are actively contacting more SP. In the next round, we will increase our cooperation with f01920887, which is a SP from Australia. In addition, we are also contacting more SPs.

**Comment by nj-steve** [comment]
When will  you cooperate with SPs from other regions?

**Comment by liuanxin** [comment]
Hello, you will see the update of the data in the next round. We have contacted the nodes in Australia and will begin to cooperate soon. 
Thank you!

**Comment by luobin544** [comment]
checker:manualTrigger

**Comment by luobin544** [comment]
Satisfied retrieval success rate, support provided in this round. Based on previous answers, we hope to see cooperation with other SPs in the next round.

**Comment by luobin544** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec3wylub4rm63msq2y66zhsprghct5tj7q4tfv4e56nojoirxw2ra 
#### Address 
> f1rf3tdlmk4x3y4dwmwb6rbxcl62rycxlfqfqgvva
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1tbd632f6w62glfaf7wjpimacbnjiz26poyoes2q
#### Id
> 0b60d3c9-f2c2-4989-be16-978a90e59806
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec3wylub4rm63msq2y66zhsprghct5tj7q4tfv4e56nojoirxw2ra

**Comment by a1991car** [comment]
checker:manualTrigger

**Comment by a1991car** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceabnt6d4dydb76q4v5bsfvasmbh5iumvuo3a5yyxbl54hffah4pvq 
#### Address 
> f1rf3tdlmk4x3y4dwmwb6rbxcl62rycxlfqfqgvva
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1qnumecdypgrbaebtkdfjnwt5ndacadcuas3deiq
#### Id
> 9bbd15b8-390a-47c3-9e47-985c46a76691
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceabnt6d4dydb76q4v5bsfvasmbh5iumvuo3a5yyxbl54hffah4pvq

**Comment by junyaoren** [comment]
Looks good to me. I can see more SPs are joining. Will support this round.

**Comment by junyaoren** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecxze2swnfslwoxctwssyftor2fxruwt7vhxnijrtphx6qfzvmu7i 
#### Address 
> f1rf3tdlmk4x3y4dwmwb6rbxcl62rycxlfqfqgvva
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1xzff5xup63o5sygr2swp4zvcajg54lotliimdty
#### Id
> 9bbd15b8-390a-47c3-9e47-985c46a76691
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecxze2swnfslwoxctwssyftor2fxruwt7vhxnijrtphx6qfzvmu7i
