### ISSUE TITLE
[DataCap Application] Fly Brain Dataset

### ISSUE THREAD

**Issue by Megan008** [filecoin-project/filecoin-plus-large-datasets#1013]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Public Data-FlyBrain
- Website / Social Media:https://registry.opendata.aws/janelia-flylight/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):3PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):100TiB
- On-chain address for first allocation:f1cf2pp6bgu6vvxfuau6bsmiibhrc7v3gvjsyseay

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
I have participated in some projects and hackathon. I have experience on it.
```

What is the primary source of funding for this project?
```
Personal income.
```

What other projects/ecosystem stakeholders is this project associated with?
```
No.
```

## Use-case details

Describe the data being stored onto Filecoin
```
It consists of fluorescence images of Drosophila melanogaster driver lines, aligned to standard templates, and stored in formats suitable for rapid searching in the cloud.
```

Where was the data in this dataset sourced from?
```
This data set is made available by Janelia's FlyLight project.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://registry.opendata.aws/janelia-flylight/
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes, it's a public dataset
```

What is the expected retrieval frequency for this data?
```
Multiple times.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
2 years.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
North america; Korea; China.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
75% data will be distributed by offline data transfer. Other data will use online transfer for distributing with storage providers who close to me.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
I would let 1 sp who used to cooperate with me for this deal. Now I'm chatting with other sps. f023495, f0508988
```

How will you be distributing deals across storage providers?
```
I have communicated with 4 sp. In first time, I will divide 1/4 data to each sp. If I find out more sp, I will decrease the percentage of deals to them --- for decentralized storage.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes.
```

**Comment by raghavrmadya** [comment]
<img width="1219" alt="Screen Shot 2022-10-07 at 8 26 39 AM" src="https://user-images.githubusercontent.com/91579519/194591221-ca9e5297-165f-4d10-8810-c486dc8497cf.png">
 The data set is already stored on slingshot and the size does not justify 5 PiBs. Closing this application now

**Comment by Megan008** [comment]
@raghavrmadya It is a public dataset so that anyone can store it not only for slingshot. The reason I apply for 5 PiB is that I want to store about 10 copies at least and prepare for more storage need in the future. And my weekly allocation request is 100TiB. I can reduce my total datacap request if 5 PiB is improper for my thought. Can you help reopen my issue and let me prepare my application again? Thank you!

**Comment by raghavrmadya** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 3PiB

**Expected weekly DataCap usage rate**

> 100TiB

**Client address**

>f1cf2pp6bgu6vvxfuau6bsmiibhrc7v3gvjsyseay

**Comment by raghavrmadya** [comment]
Can you also share how your data preparation is different than the existing data set?

**Comment by Megan008** [comment]
I have enough bandwidth and hard-disks for downloading data.

**Comment by MetaWaveInfo** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb4nfhtjp4yy7x7727zbok7byj37w622iw3smzecxbziu4jhcei64 
#### Address 
> f1cf2pp6bgu6vvxfuau6bsmiibhrc7v3gvjsyseay
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1ktlkcxnmzxcdaoqfsunrg3vocfbmgv4n3mrn74a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb4nfhtjp4yy7x7727zbok7byj37w622iw3smzecxbziu4jhcei64

**Comment by UnionLabs2020** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceav5s7orw7urk6ajd5zvisud75u7sfw6fhuyb5ddrsvxb23d36gri 
#### Address 
> f1cf2pp6bgu6vvxfuau6bsmiibhrc7v3gvjsyseay
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f17xdri3wunqgld7dm23e4f3eqsntjakwc47xjo6i
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceav5s7orw7urk6ajd5zvisud75u7sfw6fhuyb5ddrsvxb23d36gri

**Comment by BigD-Exchange** [comment]
@Megan008 Hi! Great to see you have gotten approval for DataCap and advancing the mission of preserving humanity’s most important information. If you are looking for storage providers to store these data or have any questions, please visit #bigdata-exchange on Filecoin Slack or reply here.

**Comment by swatchliu** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceatan5gyzawhvzcgyl67yzgmxwvrkp3dk5gt3x7sdyut3vykcb6p6 
#### Address 
> f1cf2pp6bgu6vvxfuau6bsmiibhrc7v3gvjsyseay
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1yh6q3nmsg7i2sys7f7dexcuajgoweudcqj2chfi
#### Id
> c1363cb1-c52b-4911-a647-0a85fc5a7881
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceatan5gyzawhvzcgyl67yzgmxwvrkp3dk5gt3x7sdyut3vykcb6p6

**Comment by Fenbushi-Filecoin** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecyuu4okgohw6foraqf2g464w4xo4grmcs44puscsxh4qa64d6x64 
#### Address 
> f1cf2pp6bgu6vvxfuau6bsmiibhrc7v3gvjsyseay
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1yqydpmqb5en262jpottko2kd65msajax7fi4rmq
#### Id
> c1363cb1-c52b-4911-a647-0a85fc5a7881
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecyuu4okgohw6foraqf2g464w4xo4grmcs44puscsxh4qa64d6x64

**Comment by MetaWaveInfo** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacea6ixuehbcds5wcj2b2izc5zbbyl5jyjok7cxbdgcxs2ilvgsbksu 
#### Address 
> f1cf2pp6bgu6vvxfuau6bsmiibhrc7v3gvjsyseay
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1ktlkcxnmzxcdaoqfsunrg3vocfbmgv4n3mrn74a
#### Id
> 7784679a-4452-4c81-962c-e455f83ff774
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacea6ixuehbcds5wcj2b2izc5zbbyl5jyjok7cxbdgcxs2ilvgsbksu

**Comment by UnionLabs2020** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecwcirkmvivbqeo3bfpdndizjtiwsud3zedc6ynktor62hyaxi7ok 
#### Address 
> f1cf2pp6bgu6vvxfuau6bsmiibhrc7v3gvjsyseay
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f17xdri3wunqgld7dm23e4f3eqsntjakwc47xjo6i
#### Id
> 7784679a-4452-4c81-962c-e455f83ff774
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecwcirkmvivbqeo3bfpdndizjtiwsud3zedc6ynktor62hyaxi7ok

**Comment by swatchliu** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceckydimni7np4c6snbn2gqagcwznbkxzwbwbdabkaedvp6523nkfo 
#### Address 
> f1cf2pp6bgu6vvxfuau6bsmiibhrc7v3gvjsyseay
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1yh6q3nmsg7i2sys7f7dexcuajgoweudcqj2chfi
#### Id
> 367492a5-0125-4f85-bc8c-37c8ace9bb41
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceckydimni7np4c6snbn2gqagcwznbkxzwbwbdabkaedvp6523nkfo

**Comment by Melody-1166** [comment]
![WechatIMG355](https://user-images.githubusercontent.com/116047447/204982037-20061df3-4822-49cb-b573-08bccd1967a8.png)

**Comment by stcouldlisa** [comment]
![WechatIMG355](https://user-images.githubusercontent.com/112812896/204982479-2e9afa43-543a-4af6-971e-6e12dd92e6ae.png)

**Comment by stcouldlisa** [comment]
@raghavrmadya It seems that there is a bug in the browser, I have observed that a lot of data is not synchronized, but in the case of this customer, it does seem to be ok,

**Comment by stcouldlisa** [comment]
![1669876790719](https://user-images.githubusercontent.com/112812896/204983282-f8590c0c-b989-4bbd-a957-ba83efbd313a.jpg)

**Comment by stcouldlisa** [comment]
It seems that there is an error in the browser, but I checked the customer's situation, and the customer is in compliance with the rules

**Comment by stcouldlisa** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedn6npsts54zfqhrkuw2xsx6n52f6jhhkjq2tkkd4zmgm2u2cz5iu 
#### Address 
> f1cf2pp6bgu6vvxfuau6bsmiibhrc7v3gvjsyseay
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1jvvltduw35u6inn5tr4nfualyd42bh3vjtylgci
#### Id
> 367492a5-0125-4f85-bc8c-37c8ace9bb41
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedn6npsts54zfqhrkuw2xsx6n52f6jhhkjq2tkkd4zmgm2u2cz5iu

**Comment by NDLABS-OFFICE** [comment]
![image](https://user-images.githubusercontent.com/104019147/206996030-c88c4b17-44d8-4644-b2ea-b910d6940c68.png)

**Comment by UnionLabs2020** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceduuctcvd2mq643qvrutnxeywwocrttwv663ov4q722zjl26mbsrg 
#### Address 
> f1cf2pp6bgu6vvxfuau6bsmiibhrc7v3gvjsyseay
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f17xdri3wunqgld7dm23e4f3eqsntjakwc47xjo6i
#### Id
> ea2cab80-b2d5-434b-a5f9-1a96b698a971
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceduuctcvd2mq643qvrutnxeywwocrttwv663ov4q722zjl26mbsrg

**Comment by MetaWaveInfo** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebziecq6632htqw4nkewbtnkw7of5bmmmhx7d3cn77rlyf7q2tlhg 
#### Address 
> f1cf2pp6bgu6vvxfuau6bsmiibhrc7v3gvjsyseay
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1ktlkcxnmzxcdaoqfsunrg3vocfbmgv4n3mrn74a
#### Id
> ea2cab80-b2d5-434b-a5f9-1a96b698a971
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebziecq6632htqw4nkewbtnkw7of5bmmmhx7d3cn77rlyf7q2tlhg

**Comment by filplus-checker** [comment]
## DataCap and CID Checker Report[^1]
 - Organization: `Public Data-FlyBrain`
 - Client: `f1cf2pp6bgu6vvxfuau6bsmiibhrc7v3gvjsyseay`
### Storage Provider Distribution
The below table shows the distribution of storage providers that have stored data for this client.

If this is the first time a provider takes verified deal, it will be marked as `new`.

For most of the datacap application, below restrictions should apply.
 - Storage provider should not exceed 25% of total datacap.
 - Storage provider should not be storing duplicate data for more than 20%.
 - Storage provider should have published its public IP address.
 - All storage providers should be located in different regions.

⚠️ [f01969789](https://filfox.info/en/address/f01969789) has sealed 46.65% of total datacap.

⚠️ 79.86% of total deal sealed by [f01969789](https://filfox.info/en/address/f01969789) are duplicate data.

⚠️ 60.84% of total deal sealed by [f01344987](https://filfox.info/en/address/f01344987) are duplicate data.

⚠️ 89.94% of total deal sealed by [f0136399](https://filfox.info/en/address/f0136399) are duplicate data.

⚠️ 46.19% of total deal sealed by [f01841131](https://filfox.info/en/address/f01841131) are duplicate data.

⚠️ 89.91% of total deal sealed by [f0229199](https://filfox.info/en/address/f0229199) are duplicate data.

⚠️ 89.75% of total deal sealed by [f0681068](https://filfox.info/en/address/f0681068) are duplicate data.

⚠️ All storage providers are located in the same region.

| Provider                                              |                           Location | Total Deals Sealed | Percentage | Unique Data | Duplicate Deals |
| :---------------------------------------------------- | ---------------------------------: | -----------------: | ---------: | ----------: | --------------: |
| [f01969789](https://filfox.info/en/address/f01969789) | Hong Kong, Central and Western, HK |         304.91 TiB |     46.65% |   61.41 TiB |          79.86% |
| [f01344987](https://filfox.info/en/address/f01344987) | Hong Kong, Central and Western, HK |         119.31 TiB |     18.25% |   46.72 TiB |          60.84% |
| [f0136399](https://filfox.info/en/address/f0136399)   | Hong Kong, Central and Western, HK |         115.50 TiB |     17.67% |   11.63 TiB |          89.94% |
| [f01841131](https://filfox.info/en/address/f01841131) | Hong Kong, Central and Western, HK |          59.06 TiB |      9.04% |   31.78 TiB |          46.19% |
| [f0229199](https://filfox.info/en/address/f0229199)   | Hong Kong, Central and Western, HK |          34.69 TiB |      5.31% |    3.50 TiB |          89.91% |
| [f0681068](https://filfox.info/en/address/f0681068)   | Hong Kong, Central and Western, HK |          20.13 TiB |      3.08% |    2.06 TiB |          89.75% |

![Provider Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/1013/1671098364009.png)
### Deal Data Replication
The below table shows how each many unique data are replicated across storage providers.
- No more than 25% of unique data are stored with less than 4 providers.

⚠️ 100.00% of deals are for data replicated across less than 4 storage providers.

| Unique Data Size | Total Deals Made | Number of Providers | Deal Percentage |
| ---------------: | ---------------: | ------------------: | --------------: |
|       132.16 TiB |       571.09 TiB |                   1 |          87.38% |
|        12.47 TiB |        82.50 TiB |                   2 |          12.62% |

![Replication Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/1013/1671098364605.png)
### Deal Data Shared with other Clients
The below table shows how many unique data are shared with other clients.
Usually different applications owns different data and should not resolve to the same CID.

⚠️ CID sharing has been observed.

| Other Client                                                                                                                                                                                                              | Application                                                                                                       | Total Deals Affected | Unique CIDs |        Verifier |
| :------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ | :---------------------------------------------------------------------------------------------------------------- | -------------------: | ----------: | --------------: |
| [f1znd7uramgqquelcgefo5xgozopd3nga73hhywpy](https://filfox.info/en/address/f1znd7uramgqquelcgefo5xgozopd3nga73hhywpy)                                                                                                     | [BotSmart ](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/373)                          |            82.94 TiB |         343 | LDN v3 multisig |
| [f1tgii4xgcp6um4n2w7eqaw6bwvnvyii2u7cjgzka](https://filfox.info/en/address/f1tgii4xgcp6um4n2w7eqaw6bwvnvyii2u7cjgzka)                                                                                                     | [Meson\.Network ](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/187)                    |            54.34 TiB |         157 | LDN v3 multisig |
| [f127l5waa4pw6k3sm4e7wxevc4fe5uz7dyt4mxa3i](https://filfox.info/en/address/f127l5waa4pw6k3sm4e7wxevc4fe5uz7dyt4mxa3i)                                                                                                     | `Pangod`                                                                                                          |            52.69 TiB |         309 | LDN v3 multisig |
| [f1quofpadzcqlonmz7v3mv7dfqvm5hdztucdsjqsy](https://filfox.info/en/address/f1quofpadzcqlonmz7v3mv7dfqvm5hdztucdsjqsy)                                                                                                     | [HENAN 863 SOFTWARE CO\., LTD](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/468)       |            47.63 TiB |         141 | LDN v3 multisig |
| [f1vbe7ze5yknpgu3orinv4zu4rkofsyqfsmpejpui](https://filfox.info/en/address/f1vbe7ze5yknpgu3orinv4zu4rkofsyqfsmpejpui)                                                                                                     | [HELIOS](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/305)                             |            46.56 TiB |         151 | LDN v3 multisig |
| [f1wr6rwwqckh6um2hynaym2t4mniev5b675kbf5ni](https://filfox.info/en/address/f1wr6rwwqckh6um2hynaym2t4mniev5b675kbf5ni)                                                                                                     | [Ctrip Global Shopping](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/303)              |            46.47 TiB |         230 | LDN v3 multisig |
| [f1ugo3abkmmb4pb2atxz5oqqgwsd27b4p6k52f2va](https://filfox.info/en/address/f1ugo3abkmmb4pb2atxz5oqqgwsd27b4p6k52f2va)                                                                                                     | [Yuepass Technology Company Limited](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/429) |            42.09 TiB |         285 | LDN v3 multisig |
| [f1bb2z36lpq3pnwiiowiraagpzqnpow4bonjacx7a](https://filfox.info/en/address/f1bb2z36lpq3pnwiiowiraagpzqnpow4bonjacx7a)                                                                                                     | [Hola Space](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/362)                         |            23.41 TiB |          75 | LDN v3 multisig |
| [f1ibuglt2lzlyf7vnmtzmuykcfgl2pn2fxym5dibi](https://filfox.info/en/address/f1ibuglt2lzlyf7vnmtzmuykcfgl2pn2fxym5dibi)                                                                                                     | [Appstest](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/346)                           |            21.88 TiB |         175 | LDN v3 multisig |
| [f1csetl7nor3qie2cehx7axf2ai3nedmowj53xwsa](https://filfox.info/en/address/f1csetl7nor3qie2cehx7axf2ai3nedmowj53xwsa)                                                                                                     | [NOAA GOES\-\-\-Piero](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1112)              |            18.81 TiB |         154 | LDN v3 multisig |
| [f1vykg3elgzoa3lpzf5xo6rbcghzr5ifat757mucq](https://filfox.info/en/address/f1vykg3elgzoa3lpzf5xo6rbcghzr5ifat757mucq)                                                                                                     | [Hailiang Mingyou Online](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/51)             |            10.81 TiB |          71 |        LDN # 51 |
| [f1a2rdwwor3kq6mv7nveuxhux7rxtj6iyjs7hfswa](https://filfox.info/en/address/f1a2rdwwor3kq6mv7nveuxhux7rxtj6iyjs7hfswa)                                                                                                     | [Worldkan](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/902)                           |             6.59 TiB |          42 | LDN v3 multisig |
| [f1rkmhotssjif6ucrosls7oewjz6pr2v2eygfjyui](https://filfox.info/en/address/f1rkmhotssjif6ucrosls7oewjz6pr2v2eygfjyui)                                                                                                     | `Weipaitang`                                                                                                      |             5.66 TiB |          34 | LDN v3 multisig |
| [f1fq6abg47ifgeee2z7q2rps3tvknoo2ztcoqy7ai](https://filfox.info/en/address/f1fq6abg47ifgeee2z7q2rps3tvknoo2ztcoqy7ai)                                                                                                     | [DaYe Art Tuition Class \(DKArt\) ](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/888)  |           864.00 GiB |           5 | LDN v3 multisig |
| [f3u3unadf654vezf62cd4jo6r7h6qpkx26g5amcdc<br/>3oe6rmpmk2nfosfd2kjkdhj4ndvr626gsm7fhpmt7<br/>gg2q](https://filfox.info/en/address/f3u3unadf654vezf62cd4jo6r7h6qpkx26g5amcdc3oe6rmpmk2nfosfd2kjkdhj4ndvr626gsm7fhpmt7gg2q) | [Runtu Information Technology](https://github.com/filecoin-project/filecoin-plus-client-onboarding/issues/1150)   |           608.00 GiB |           4 |       Steven Li |

[^1]: To manually trigger this report, add a comment with text `checker:manualTrigger`

**Comment by BDEio** [comment]
@Megan008 Hi! Great to see that you have gotten approval for DataCap!
BDE is a verified deals auction house helping you to get paid storing your valuable data with reliable storage providers. If you need any help, please get in touch.
