### ISSUE TITLE
[DataCap Application] Huochain

### ISSUE THREAD

**Issue by muxiaomu001** [filecoin-project/filecoin-plus-large-datasets#1014]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: huochain
- Website / Social Media:  www.huochain.com.cn 
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):  5 PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 200TiB
- On-chain address for first allocation: f1bp5cgtuhdb2l5z7itoxsestznvotrm2uvid37fy

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
With the vision of "digitalization of the physical industry and industrialization of digital technology", Huochain Technology creates professional services for the entire life cycle of the blockchain industry, is committed to becoming the pioneer and builder of the blockchain industry ecology, continues to promote industrial upgrading, and empowers entities economy.

As an enterprise focusing on the ecological development and construction of the blockchain industry, Huochain has successively created more than 30 fields such as carbon neutrality, digital collections, metaverse, traceability management, supply chain finance, consumption points, intellectual property, digital identity, and real estate. Core products and application scenarios. And continue to explore the application value of the blockchain, constantly explore new landing scenarios, and help the healthy and sustainable development of the overall ecology of the blockchain industry.

```

What is the primary source of funding for this project?
```
Company funds.
```

What other projects/ecosystem stakeholders is this project associated with?
```
None.
```

## Use-case details

Describe the data being stored onto Filecoin
```
Industrial blockchain data

Research report data

Education and training data

Alliance chain project data

digital collection data

Industry Summit Data
```

Where was the data in this dataset sourced from?
```
It comes from the data generated during the company's business operation, and the data generated by different business departments is different, such as research data, design data, development data, product promotion data, conference data, education and training data, etc.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://drive.google.com/drive/folders/1R_RpVYsp3Qg6ELjXupzQgLeLm6eQK83l?usp=sharing
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes, the dataset is public
```

What is the expected retrieval frequency for this data?
```
Each type of data retrieval needs may be different.About once every 6 months
```

For how long do you plan to keep this dataset stored on Filecoin?
```
At least 2 year.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
All countries
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
We plan to use offline services for data transfer.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
Based on storage provider's capacity, reputation and performance. We need long-term cooperation with storage providers that has strong comprehensive power. We have contacted some storage providers, we welcome storage providers to contact us.
```

How will you be distributing deals across storage providers?
```
We will strictly abide by the rules of FIL+ to achieve decentralized storage. We promise that there will be at least 4 SP IDs, and each SP ID will not exceed 25%.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, we are fully funded  
```

**Comment by raghavrmadya** [comment]
Need more justification and detail for the 5 PiB request

**Comment by muxiaomu001** [comment]
sir，thanks for your reply. Maybe my description is not clear enough, so I add some content.

huochain is affiliated with Huobi.  huochain consists of huochain Science and Technology Research Institute, Huochain University of Science and Technology, and Industry Empowerment Center, we are deeply in the field of digital finance. It has been cultivating for 7 years and has more than 1,500 employees around the world. 10,000-level users provide secure digital financial services


On March 13, 2020, Fire Chain Technology joined BGIN, an international blockchain non-profit organization, and became the only Chinese unit. He also includes from Georgetown University, Japan Financial Services Agency (JFAS), Stanford Blockchain Research Center, Cambridge University Emerging .Member of institutions such as the Center for Financial Research. BGIN mainly conducts related research and discussions in the field of "blockchain" governance.

We founded Huochain University of Science and Technology, which has recruited more than 1,500 students, and the online live broadcasts and events have covered more than 70,000+ people.

We have published more than 300 research papers, written and published many books, and our popular science videos have been viewed over one million.

We work with many businesses, cities, countries to provide digital solutions.

**Comment by muxiaomu001** [comment]
<img width="997" alt="WX20221024-170546@2x" src="https://user-images.githubusercontent.com/36186296/197490451-b2d4a144-4eda-472e-b5e0-70d43f3ae59b.png">

**Comment by muxiaomu001** [comment]
<img width="1008" alt="WX20221024-170608@2x" src="https://user-images.githubusercontent.com/36186296/197490536-d0c0e712-c6f0-4c9c-a778-658be842911e.png">

**Comment by muxiaomu001** [comment]
<img width="972" alt="WX20221024-170630@2x" src="https://user-images.githubusercontent.com/36186296/197490788-920b90bd-6573-412c-909e-d4d7b11c32e0.png">

**Comment by muxiaomu001** [comment]
<img width="999" alt="WX20221024-170648@2x" src="https://user-images.githubusercontent.com/36186296/197490856-2ca3b0d6-8727-4027-9a66-c2c7f2c82add.png">

**Comment by muxiaomu001** [comment]
<img width="972" alt="WX20221024-170719@2x" src="https://user-images.githubusercontent.com/36186296/197490916-11771b34-2116-47e0-b986-cd16757dee8e.png">

**Comment by muxiaomu001** [comment]
If possible, please agree to us as soon as possible.
The power of words is always limited and we would love to participate in a notary meeting to show you more about us.

**Comment by Sunnyiscoming** [comment]
Can you explain your data composition? How many copies will you store?
What's the relationship between you and the organization?
Can you provide more detailed information about other storage providers participated in this program, such as you can list SPs you have contacted with at present?

**Comment by muxiaomu001** [comment]
The data comes from our company. Our company (www.huochain.com.cn) is Huochain Technology, a subsidiary of Huobi, the world's top three exchanges. The business is very rich, and the data generated every day is also very large. We The data currently generated has exceeded 3P, and more than 15T+ data is generated every day. The data we store on the Filecoin network is mainly:
Industrial Blockchain Data
Research report data
Education and training data
Alliance chain project information
Digital Collection Data
Industry Summit Information
data case, we have shown here
https://drive.google.com/drive/folders/1R_RpVYsp3Qg6ELjXupzQgLeLm6eQK83l?usp=sharing

I am the founder of the company and we can send a business license on the mail to prove our company application.

We have reached out to many SPs across the globe:
f01391982, f01354898, f01392893, f01208189, f0875769, f01702940, f01545009, f0411786

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 200TiB

**Client address**

>f1bp5cgtuhdb2l5z7itoxsestznvotrm2uvid37fy

**Comment by Sunnyiscoming** [comment]
Hey @muxiaomu001 , if you still want to apply for datacap, you can ask notaries to do client due diligence in slack channel. https://app.slack.com/client/TEHTVS1L6/C036JKD8NVA/thread/C03BG1MNQ4T-1673888660.823499

**Comment by muxiaomu001** [comment]
@Sunnyiscoming Hi, thank you for your reminder, we just finished the Lantern Festival, we will send https://app.slack.com/client/TEHTVS1L6/C036JKD8NVA/thread/C03BG1MNQ4T-1673888660.823499 a message, hoping that an enthusiastic notary can sign for us. It would be much appreciated if you could help us.

**Comment by chongtuyun** [comment]
hey, @Sunnyiscoming , what do I need to do, we are in singapore, if you also have colleagues in singapore, glad to meet you.

**Comment by herrehesse** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Looking at your application i have some questions:
As you are brand new on Github and have no history of past applications it seems to me that applying for 5PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?

Can you show us visible proof of the size of your data and the storage systems you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230232885049356) to provide us with the necessary information to make an educated decision on your LDN request if we would like to support it.

Thanks!

**Comment by stcouldlisa** [comment]
We have contacted these SPs, f01943663, f01807707, f01984580, f01999119, they are in China and Asia respectively, we will contact more SPs, and finally choose 5 SPs for cooperation.

Considering the time and cost of data mailing, we prefer to distribute in China and Asia. Because our data is precious, we require that the cooperative SP must be retrievable.

> 亲爱的申请人，
> 
> 感谢您申请 datacap。作为 Filecoin [FIL+ 公证人](https://github.com/filecoin-project/notary-governance/tree/main/notaries)，我正在筛选您的申请并进行尽职调查。
> 
> 查看您的应用程序，我有一些问题： 由于您是 Github 上的新手并且没有过去的应用程序历史，因此在我看来申请 5PB 的数据容量很多。人们需要全面了解 Filecoin、数据打包、数据分发以及随之而来的所有要求。您是 Filecoin 领域的新手，还是您过去曾在不同的 Github 帐户名上申请过 datacap？
> 
> 您能否向我们展示您的数据大小和您拥有的存储系统的可见证据？
> 
> 作为最后一个问题，我希望您填写[此表格](https://form.jotform.com/230232885049356)以向我们提供必要的信息，以便在我们愿意支持时就您的 LDN 请求做出明智的决定。
> 
> 谢谢！
