### ISSUE TITLE
[DataCap Allocation] - Datacap Application - HashFrog 

### ISSUE THREAD

**Issue by codeb2cc** [filecoin-project/filecoin-plus-large-datasets#1015]
---
name: Large Dataset Notary application
about: Clients should use this application form to request a DataCap allocation via a LDN for a dataset
title: "Datacap Application - HashFrog "
labels: 'application, Phase: Diligence'
assignees: ''

---
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: HashFrog
- Website / Social Media: https://www.hashfrog.com/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100TiB
- On-chain address for first allocation: f3spko5rcrsz5oh5cy6rt5yvjh5hqwklpmhtonu3vaovoilu6yf6y66444l7cy3svo6pmuayyhszmooeyuxegq
- Region: Greater China Region

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
HashFrog is a cloud computing power platform. The computing power comes from tens of thousands of real mining machines. The platform cuts and allocates the computing power of the mining machines. After purchasing the computing power, users can monitor the operation of their own computing power from a third-party mining pool. Not only that, the user's income can also be directly transferred to the user's wallet through a third-party mining pool to ensure the compliance and security of assets.

As a leading blockchain company, we are very concerned about innovation in the industry, and we also hope to adjust the company's processes to practice the concept of web3. The decentralized storage field led by Filecoin is our long-term optimistic track, so we hope to store the data generated during the company's operation in this network.

Main data types: video data, log data, etc.
```

What is the primary source of funding for this project?
```
Own funds and revenue of the company.
```

What other projects/ecosystem stakeholders is this project associated with?
```
No
```

## Use-case details

Describe the data being stored onto Filecoin
```
A large number of logs generated by the company's servers and self-operated mining machines, surveillance video in the mining rigs, etc. These data does not involve the company's sensitive information.
```

Where was the data in this dataset sourced from?
```
Website / Internal system / Mining rigs
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
Masked data sample:

2022-03-18 16:15:33 [debug] Miner 0xc0010a17a0 10.227.******/HASHFROG+CA+S19PRO+105T.172x21x****** Submit share to pool [*****mao19***.hashfrog 13b8bc0102b20 07659801 6234b013 7891a723 00800000], contract id 19***, miner diff 32767.5, pool diff 32767.5, poolConn 0xc0004749c0
2022-03-18 16:15:33 [debug] Miner 0xc0010a17a0 10.227.******/HASHFROG+CA+S19PRO+105T.172x21x****** Submit share to pool [*****mao19***.hashfrog 13b8bc0102b20 077d8f01 6234b013 ad1e7140 00c00000], contract id 19***, miner diff 32767.5, pool diff 32767.5, poolConn 0xc0004749c0
2022-03-18 16:15:32 [debug] Miner 0xc0010a17a0 10.227.******/HASHFROG+CA+S19PRO+105T.172x21x****** Submit share to pool [*****mao19***.hashfrog 13b8bc0102b20 077a8301 6234b013 804e1062 00200000], contract id 19***, miner diff 32767.5, pool diff 32767.5, poolConn 0xc0004749c0
2022-03-18 16:15:32 [debug] Miner 0xc0010a17a0 10.227.******/HASHFROG+CA+S19PRO+105T.172x21x****** Submit share to pool [*****mao19***.hashfrog 13b8bc0102b20 07067d01 6234b013 d66d4d05 00000000], contract id 19***, miner diff 32767.5, pool diff 32767.5, poolConn 0xc0004749c0
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
We confirm this is a public dataset that can be retrieved by anyone on the network with no specific permissions or access rights required.
```

What is the expected retrieval frequency for this data?
```
Multiple times per year.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
At least 18 months
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
All regions.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
We will negotiate with SP, both online and offline are acceptable
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We will consider a combination of cost, service and geography, and give preference to miners of good scale and reputation.
```

How will you be distributing deals across storage providers?
```
We will store approximately 3-5 replica of data on different SPs, and we will follow the filecoin guideline to make our data more reliable and secure.
A detailed allocation plan for the SPs is in the works, we will share the details once it is ready.

```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
We have enough resources and funds to start trading. Perhaps we need more weekly allocation of DC.
```

**Comment by codeb2cc** [comment]
Any feedback?

**Comment by raghavrmadya** [comment]
Please provide proper data samples so that the community and notary can understand what exactly are you storing

**Comment by codeb2cc** [comment]
> Please provide proper data samples so that the community and notary can understand what exactly are you storing

We provide cloud mining service to our customers. We act like a mining pool or BTC node. The data sample above is the PoW workload log we recorded from miners. We're going to use FIL to store this data publicly and transparently so our customer and PoW providers can verify the PoW flow in our bussiness model and the hashrate number is correct and true.
The short version: we store programming log that need to be verified by multiple 3rd parties in a neutral and public manner. @raghavrmadya we can provide more sample but I thinks it won't make more sense if you don't look into our business.

**Comment by Sunnyiscoming** [comment]
Can you explain your data composition? How many logs and videos are there? How many copies will you store?
What's the relationship between you and the organization?
Can you provide more detailed information about other storage providers participated in this program, such as you can list SPs you have contacted with at present?

**Comment by codeb2cc** [comment]
Each log contains 2022-03-18 16:15:33 [debug] Miner 0xc0010a17a0 10.227.******/HASHFROG+CA+S19PRO+105T.172x21x****** Submit share to pool [*****mao19***.hashfrog 13b8bc0102b20 07659801 6234b013 7891a723 00800000], contract id 19***, miner diff 32767.5, pool diff 32767.5, poolConn 0xc0004749c0

**Comment by codeb2cc** [comment]
Each log contains PoW share submit datetime, bitcoin miner identity, corresponding mining pool account, block and PoW task difficulty, and some programming info. We currently produce about 8T logs daily. In our business view, there's only one copy need to be store. We're planning to let our PoW providers to use this data to verify the statistic number in our contracts.
I am the technical director of HashFrog. I can send you a email with our business domain if it's needed.
No. We haven't contact any SPs presently.

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 100TiB

**Client address**

> f3spko5rcrsz5oh5cy6rt5yvjh5hqwklpmhtonu3vaovoilu6yf6y66444l7cy3svo6pmuayyhszmooeyuxegq

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Can you show us visible proof of the size of your data and the storage systems you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230232885049356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!

**Comment by Sunnyiscoming** [comment]
It seems that the information of the customer is not the information that can be disclosed, again confirm the openness of the information1.PoW share submit datetime, bitcoin miner identity, corresponding mining pool account, block and PoW task difficulty, and some programming info.

**Comment by codeb2cc** [comment]
> It seems that the informations of customers are not the information that can be disclosed. Want to confirm the openness of the information.
> 
> > PoW share submit datetime, bitcoin miner identity, corresponding mining pool account, block and PoW task difficulty, and some programming info.

In our preliminary design, sensitive information will be encrypted and only participants with the distributed key can decrypt and verify the data.

**Comment by Normalnoise** [comment]
checker:manualTrigger

**Comment by Normalnoise** [comment]
Can you show us proof of the size of your data?
