### ISSUE TITLE
[DataCap Application] Shenzhen Yizhe Technology

### ISSUE THREAD

**Issue by zenghaiyang** [filecoin-project/filecoin-plus-large-datasets#1017]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Shenzhen Yizhe Technology Co., Ltd
- Website / Social Media: http://www.artzhe.com/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 4PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):  200TiB
- On-chain address for first allocation: f16fwmw2nw2kk5sdpq4g2etremk7mpivyv24atjfy

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Artist is a social platform for hand-painted art creation, which was established in March 2017. Users can create and upload their own works of art on the platform. Other users can search, view and collect their favorite works of art on the platform, or communicate with artists online.
```

What is the primary source of funding for this project?
```
The customer pays our service fee and transaction commission.
```

What other projects/ecosystem stakeholders is this project associated with?
```
There is no other projects/ecosystem stakeholders associated with.
```

## Use-case details

Describe the data being stored onto Filecoin
```
The data we store are mainly works of art entrepreneurs, including design drafts, oil paintings, Chinese landscape paintings, art design, etc.
```

Where was the data in this dataset sourced from?
```
It mainly comes from the creation data set of artists and users of our APP.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 

https://nftstorage.link/ipfs/bafybeigsv2znaj2hyjntj6llynqcnaf4pwi5tgzo4q5p2czykjfdq2xa7m
https://nftstorage.link/ipfs/bafybeidp5tgoihbahljns3j4yagn3hxluondsu2hvphbsbssi3ipcjn7j4
https://nftstorage.link/ipfs/bafybeiap5lubz6svtayurpd7igelvxlb24vqtns7i6fye33fexnzic7zzy
https://nftstorage.link/ipfs/bafybeidyy4nv62pzoo37zyjrnunxuu6c4jwhj4lqikfqonvaqz2k2azlte
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes, we confirm.
```

What is the expected retrieval frequency for this data?
```
Maybe twice a year or more.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
Expectedly 5 years and it’s likely to be extended afterwards.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
We plans to make the deals in Asia, like: HK,Vietnam or Philippines,etc.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Prefer online, if needed offline can also be considered.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
Well, we want to choose multiple miners with good size and credit in filecon's ecosystem.
```

How will you be distributing deals across storage providers?
```
We would divide the data up and send it to different miners.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, we have got some advices and resources from the community to make deals. We don’t need funding,and we need to get more weekly allocation of DC requested, About 150T/week.
```

**Comment by Sunnyiscoming** [comment]
https://nftstorage.link/ipfs/bafybeigsv2znaj2hyjntj6llynqcnaf4pwi5tgzo4q5p2czykjfdq2xa7m
https://nftstorage.link/ipfs/bafybeidp5tgoihbahljns3j4yagn3hxluondsu2hvphbsbssi3ipcjn7j4
https://nftstorage.link/ipfs/bafybeiap5lubz6svtayurpd7igelvxlb24vqtns7i6fye33fexnzic7zzy
https://nftstorage.link/ipfs/bafybeidyy4nv62pzoo37zyjrnunxuu6c4jwhj4lqikfqonvaqz2k2azlte
The data samples provided cannot be directly viewed after downloading. In order to facilitate the inspection by more community members, can you provide sufficient data samples separately and easier to see? How many copies will you store?

**Comment by zenghaiyang** [comment]
Well, OK.
I updated a data, see ( https://drive.google.com/drive/folders/1JjibFbfqTQsTSgD0nOI3PMpYodZ0iCzR?usp=sharing ).
In addition, I plan to save the data for five backups.
Thanks a lot.

**Comment by ipfscn** [comment]
I received your request and I checked your profile. I think you need to list at least 4 nodes, and they need to be on at least 3 different continents.
Sorry, I know it's hard, but the Filecoin network is decentralized, so I hope your storage is decentralized too.

**Comment by kernelogic** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaf73tnckhgassbax4ngpply5n663avjhn5v5ar6df2c7yreqo4h6 
#### Address 
> f16fwmw2nw2kk5sdpq4g2etremk7mpivyv24atjfy
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### Id
> 0d603dc9-6a0c-4275-900f-6f4d8d5a1f85
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaf73tnckhgassbax4ngpply5n663avjhn5v5ar6df2c7yreqo4h6

**Comment by stcouldlisa** [comment]
Please provide 4 or more sp.
Forgive me, I know it's hard, but your 4 sps need to be in at least 3 different regions.

**Comment by zenghaiyang** [comment]
> Please provide 4 or more sp. Forgive me, I know it's hard, but your 4 sps need to be in at least 3 different regions.

I contacted the miners f01850726, f01900537, f01927252, f01914991, who promised to abide by the official rules.
thank you!

**Comment by kernelogic** [comment]
I have checked the data sample in google drive and they look good. Look forward to see the first allocation result.

**Comment by herrehesse** [comment]
Agreeing with @stcouldlisa here. Are you sure that the storage providers are in different regions? Love to see some good results!

**Comment by zenghaiyang** [comment]
It has been five months, why is there still no one to support me? I needed to do something? I have answered the question you asked last time. Please support me @stcouldlisa

**Comment by OpenGate01** [comment]
Can you tell us more detailed information about the SPs? For example what specific region they are in？

**Comment by zenghaiyang** [comment]
F01926792 in Hanoi, Vietnam.
F01914123 in the UK.
F01927252 in the UK.
F01928022 in the United States

**Comment by OpenGate01** [comment]
Well, we will support this round and hope you follow the Fil+ rules strictly afterwards and we will keep an eye on this project.

**Comment by OpenGate01** [comment]
![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/117976412/00e5cfd9-5ae9-4b72-a353-89c51fd7dce5)
Sorry,I'm V4, I can't sign.

**Comment by Tom-OriginStorage** [comment]
The applicant found me to help review the signature, and saw that the rest of the notaries have done their due diligence, and currently meet the standards of OriginStorage, and are willing to support the first round, and will continue to pay attention to it later

**Comment by Tom-OriginStorage** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecrl7up2yohvvhmiiy2m5u4daw2jcpmv4sgvz43x5t26rmh4rumd6 
#### Address 
> f16fwmw2nw2kk5sdpq4g2etremk7mpivyv24atjfy
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1q6bpjlqia6iemqbrdaxr2uehrhpvoju3qh4lpga
#### Id
> 0d603dc9-6a0c-4275-900f-6f4d8d5a1f85
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecrl7up2yohvvhmiiy2m5u4daw2jcpmv4sgvz43x5t26rmh4rumd6

**Comment by stcouldlisa** [comment]
checker:manualTrigger

**Comment by stcouldlisa** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedjwmgmv4peho4efndbnjfuez7v3ng6qjsroanh672vhypp6ivprs 
#### Address 
> f16fwmw2nw2kk5sdpq4g2etremk7mpivyv24atjfy
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1jvvltduw35u6inn5tr4nfualyd42bh3vjtylgci
#### Id
> 543f32c8-2a40-4efd-a1a7-125c32ab1f0f
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedjwmgmv4peho4efndbnjfuez7v3ng6qjsroanh672vhypp6ivprs

**Comment by OpenGate01** [comment]
checker:manualTrigger

**Comment by OpenGate01** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecwjzusiddx2a4eg4ov7uonccsnqnvqgebgy2nyobvofljfjdjvn4 
#### Address 
> f16fwmw2nw2kk5sdpq4g2etremk7mpivyv24atjfy
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1im4hmtbfzqnx7ir74kdaiu4ynjhgqh3sdi2snla
#### Id
> 543f32c8-2a40-4efd-a1a7-125c32ab1f0f
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecwjzusiddx2a4eg4ov7uonccsnqnvqgebgy2nyobvofljfjdjvn4

**Comment by igoovo** [comment]
checker:manualTrigger

**Comment by igoovo** [comment]
The job seems to be in good condition.

**Comment by igoovo** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecmlus2m4k2tx3mc66k7wetnmxr24636kohh6zpqrysdt24w7juuy 
#### Address 
> f16fwmw2nw2kk5sdpq4g2etremk7mpivyv24atjfy
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1shnsfayxqll77svffaxnjenms7bbbysbqcatrpy
#### Id
> a68e3722-7e4c-4d01-bc04-6fc24f3c9323
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecmlus2m4k2tx3mc66k7wetnmxr24636kohh6zpqrysdt24w7juuy

**Comment by igoovo** [comment]
checker:manualTrigger

**Comment by igoovo** [comment]
checker:manualTrigger

**Comment by igoovo** [comment]
checker:manualTrigger

**Comment by igoovo** [comment]
checker:manualTrigger

**Comment by igoovo** [comment]
checker:manualTrigger

**Comment by igoovo** [comment]
keepalive

**Comment by igoovo** [comment]
checker:manualTrigger

**Comment by igoovo** [comment]
checker:manualTrigger

**Comment by igoovo** [comment]
checker:manualTrigger

**Comment by igoovo** [comment]
Reading the examination report is healthy and normal, and the warning suggests that attention should be paid to it.
Support this round.

**Comment by igoovo** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced3tv754zxbzqtlhuwfldarfzoxwnkf3jaqp3ql4dtj5nbeh2mu54 
#### Address 
> f16fwmw2nw2kk5sdpq4g2etremk7mpivyv24atjfy
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1shnsfayxqll77svffaxnjenms7bbbysbqcatrpy
#### Id
> a68e3722-7e4c-4d01-bc04-6fc24f3c9323
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced3tv754zxbzqtlhuwfldarfzoxwnkf3jaqp3ql4dtj5nbeh2mu54

**Comment by sxxfuture-official** [comment]
> ⚠️ 72.79% of deals are for data replicated across less than 4 storage providers.

Except for the above warnings, there are no obvious problems in other aspects. Check the replica details, and the backup number of most data is 3. I believe this warning will be lifted in the near future.
will support.

**Comment by sxxfuture-official** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb2ajyjzgifsxevmmcizhfbxi2htxxpedxyeyagzjqp76jbpbxmoi 
#### Address 
> f16fwmw2nw2kk5sdpq4g2etremk7mpivyv24atjfy
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1foiomqlmoshpuxm6aie4xysffqezkjnokgwcecq
#### Id
> a68e3722-7e4c-4d01-bc04-6fc24f3c9323
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb2ajyjzgifsxevmmcizhfbxi2htxxpedxyeyagzjqp76jbpbxmoi

**Comment by lupiruw** [comment]
keepalive

**Comment by lupiruw** [comment]
checker:manualTrigger

**Comment by Normalnoise** [comment]
checker:manualTrigger

**Comment by Normalnoise** [comment]
<img width="973" alt="image" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/102578774/4436818f-c200-4765-a9cb-be33c5876e6e">
@zenghaiyang can you explain this issue?

**Comment by zenghaiyang** [comment]
The SP I contacted ran two different sectors (32G and 64G).
SP told me about this, and they promised to continue to improve the warning message.
Thank you very much!

**Comment by Bitrise0111** [comment]
the check report shows healthy and we'd like to give support.

**Comment by Bitrise0111** [comment]
From the check bot report, it looks like data backups need to be increased, do you have a firm plan for this? How to improve it.

**Comment by zenghaiyang** [comment]
Yes, the robot does suggest that.
This is caused by several SP encapsulating different sectors, which I will ask SP to improve.
Thank you for your advice!

**Comment by Bitrise0111** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced55yqm5gkr5zl7nsofxxth7ofo5zkgzblylxcdejqwem4q4brxwi 
#### Address 
> f16fwmw2nw2kk5sdpq4g2etremk7mpivyv24atjfy
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1nknj7ayq4o43czrtdoauggtwl43fbqatmqis3yy
#### Id
> 66531e7d-1432-43f3-8a8e-279163927a38
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced55yqm5gkr5zl7nsofxxth7ofo5zkgzblylxcdejqwem4q4brxwi

**Comment by Normalnoise** [comment]
I am willing to support this round, keep watching your distribution


> The SP I contacted ran two different sectors (32G and 64G).
> SP told me about this, and they promised to continue to improve the warning message.
> Thank you very much!

**Comment by Normalnoise** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacea7o7qkvfkqa2cruppkleu5yhbunez7wugqqpohh7h3rohb7csnxq 
#### Address 
> f16fwmw2nw2kk5sdpq4g2etremk7mpivyv24atjfy
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1c5non5yf35avgcpsqvxu4yj54yyvxorwyjochqq
#### Id
> 66531e7d-1432-43f3-8a8e-279163927a38
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacea7o7qkvfkqa2cruppkleu5yhbunez7wugqqpohh7h3rohb7csnxq

**Comment by clriesco** [comment]
Removed stale label, reopened issue :)

**Comment by nj-steve** [comment]
checker:manualTrigger

**Comment by nj-steve** [comment]
Hello,the report show that warning: ⚠️ 88.09% of deals are for data replicated across less than 4 storage providers.
What is the reason and do you have any plan to fix it？

**Comment by zenghaiyang** [comment]
This is because part of the SP encapsulates the 32GB sector and part of the SP encapsulates the 64GB sector.
I will ask SP to adjust as much as possible to comply with the rules.

Thank you for your feedback!

**Comment by nj-steve** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacearenwh7pgssafii3c3qnp3lx7jtl7eu4ubuk5eb7dqk3ijnsgc3s 
#### Address 
> f16fwmw2nw2kk5sdpq4g2etremk7mpivyv24atjfy
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1xx6555qijma7igpnjspyvdunc4vfxkawnpqy5ii
#### Id
> 30b051e7-7ec8-429f-b9d2-1da274dba507
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacearenwh7pgssafii3c3qnp3lx7jtl7eu4ubuk5eb7dqk3ijnsgc3s

**Comment by nj-steve** [comment]
hope you could solve this as soon as possible.

**Comment by NiwanDao** [comment]
Hope to see more balanced data in the future.

**Comment by NiwanDao** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceatfzhq63atgwxmaq3dn5tzcc62ef6gpdkccdjnt7lyqxigkojpp2 
#### Address 
> f16fwmw2nw2kk5sdpq4g2etremk7mpivyv24atjfy
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1a2lia2cwwekeubwo4nppt4v4vebxs2frozarz3q
#### Id
> 30b051e7-7ec8-429f-b9d2-1da274dba507
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceatfzhq63atgwxmaq3dn5tzcc62ef6gpdkccdjnt7lyqxigkojpp2

**Comment by herrehesse** [comment]
@zenghaiyang As far as I can see is your distribution done by hosting services (VPN) in Europe and USA. This is making the CID tool look better than it actually is and faking location of miners.

Will do retrieval tests of your data and if not in order, will ask for a dispute & closure. Notaries also noted.
