### ISSUE TITLE
[DataCap Application] Zhejiang Geely Holding Group - <Project Name>

### ISSUE THREAD

**Issue by johnhash1992** [filecoin-project/filecoin-plus-large-datasets#1019]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Zhejiang Geely Holding Group
- Website / Social Media: http://zgh.com/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5 PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100 TiB
- On-chain address for first allocation: f1imiomfkdnrnu4g6lykbyzmepbvsnbta44jylfla
 
_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Geely Holding Group is committed to becoming a globally competitive and influential intelligent electric mobility and energy service technology company, with businesses covering automobiles and upstream and downstream industry chains, intelligent mobility services, green transportation, digital technology, etc. The group is headquartered in Hangzhou, and its subsidiaries Geely, Lynk & Co, Krypton, Geometry, Volvo, Polestar, Lotus, Yinglun Electric Vehicles, Long-range New Energy Commercial Vehicles, Radar New Energy Vehicles, Cao Cao Travel, etc. are actively participating in market competition around their respective brand positioning. The Group takes the electrification and intelligent transformation of the automobile industry as its core and builds a technology moat and strengthens the technology ecosystem in the frontier technology fields of new energy technology, shared mobility, vehicle networking, intelligent driving, and vehicle chips..
```

What is the primary source of funding for this project?
```
Own capital.
```

What other projects/ecosystem stakeholders is this project associated with?
```
None
```

## Use-case details

Describe the data being stored onto Filecoin
```
Geely automobile product introduction and review videos.
```

Where was the data in this dataset sourced from?
```
Company’s product and marketing department.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://drive.google.com/drive/folders/1Z8NVOVj_qj7-gDqrRGH4VInn8OAQxyfR?usp=sharing
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes, these are publicly available data.
```

What is the expected retrieval frequency for this data?
```
80% of our data does not need to be retrieved, and 20% has no fixed retrieval frequency, depending on the business.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
Permanent storage.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
North America.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
We plan to distribute the data to SPs via online. If there are SPs in close proximity, we will consider manual transmission.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We welcome any quality SPs but must ensure that retrieval requirements are met before distribution can take place. We will check this from time to time.
```

How will you be distributing deals across storage providers?
```
We will divide the data equally and send it to different miners.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, we are available for trading at any time.
```

**Comment by johnhash1992** [comment]
Hi,@galen-mcandrew @raghavrmadya 21 days passed, what else do I need to do?

**Comment by raghavrmadya** [comment]
You need to justify how an electric mobility and energy service technology company has 5 PiBs of data.

**Comment by johnhash1992** [comment]
Hello, @raghavrmadya 
Zhejiang Geely Holding Group (“Geely Holding” / “the Group”) was founded in 1986. In 1997, Geely Holding entered the automotive industry and has since focused our core business on the development and production of automobiles. Since 2012, Geely Holding has ranked among the Fortune Global 500 for eleven consecutive years (ranked 229th in 2022). 
Geely Holding is committed to becoming a globally competitive and influential smart electric mobility technology enterprise and energy service provider, engaged in automotive, upstream and downstream industrial chains, intelligent travel services, green transportation capacity, digital technology, etc.
We have over a hundred species models of commercial vehicles on sale, each of which we need to take high definition pictures as well as promotional videos of the vehicles and test videos of the vehicles to promote them on all major social media. 
At least 100T of data per week. Currently we have accumulated no less than 5P of data. Filecoin is the diverse storage method we expect to choose.
You can view our business description through http://zgh.com/our-business/?lang=en

**Comment by raghavrmadya** [comment]
Unblocking from the trigger as the client has been responsive and holistic in answer queries. Notaries are requested to please conduct due diligence openly as they seem fit.

**Comment by raghavrmadya** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 100TiB

**Client address**

>f1imiomfkdnrnu4g6lykbyzmepbvsnbta44jylfla

**Comment by raghavrmadya** [comment]
@johnhash1992, can you share what is your relationship with the company?

**Comment by celine3650** [comment]
@johnhash1992, would like to get a call with you and unblock the datacap application once we can validate the relationship and understand your use case.

**Comment by liyunzhi-666** [comment]
- This is a very famous car company in China.
- I've checked their data samples and it's all promotional videos about the cars they make. No issues have been found so far.

Has the client sent an email to the [filplus-app-review@fil.org](mailto:filplus-app-review@fil.org) for the simple KYB? @raghavrmadya

**Comment by raghavrmadya** [comment]
@Sunnyiscoming could you please confirm the KYB?

**Comment by johnhash1992** [comment]
Hi guys,
I'm Zhou from the Digital Technology Department of Geely Holding Group. The dataset including public video data that we are applying for this LDN application is mainly from Digital Technology Department. 
Here is a confirmation that we have sent the kYB email to the Fil+ team. 

PS.  The other application might submitted by other colleagues, which I have no idea about that.
<img width="463" alt="WechatIMG4" src="https://user-images.githubusercontent.com/114469357/203683900-65d58ffd-fa15-41bf-abdd-a50bfb782af3.png">

**Comment by Sunnyiscoming** [comment]
I will do it.



| |
***@***.***
|
|
***@***.***
|




---- Replied Message ----
| From | ***@***.***> |
| Date | 11/23/2022 15:40 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [filecoin-project/filecoin-plus-large-datasets] [DataCap Application] Zhejiang Geely Holding Group - <Project Name> (Issue #1019) |

@Sunnyiscoming could you please confirm the KYB?

**Comment by Sunnyiscoming** [comment]
@johnhash1992 It seems that you use your private email address send this email not the email address with your official domain.
Could you send an email to filplus-app-review@fil.org with your official domain in order to confirm your identity? Email name should includes the issue id #1019.

**Comment by johnhash1992** [comment]
> @johnhash1992 It seems that you use your private email address send this email not the email address with your official domain. Could you send an email to [filplus-app-review@fil.org](mailto:filplus-app-review@fil.org) with your official domain in order to confirm your identity? Email name should includes the issue id #1019. It is best to include your company's business license as well as the authorization sheet that authorizes the data to be stored on the Filecoin network and stamped with the official seal.

i I've already sent kyc email，For privacy reasons, the sensitive information in the screenshot is  @covered。@Sunnyiscoming
<img width="473" alt="image" src="https://user-images.githubusercontent.com/114469357/203883679-8ac83a72-f796-4d0c-94ac-bdd55e61c58a.png">

**Comment by NDLABS-OFFICE** [comment]
Hello @johnhash1992 , I noticed that you have done the KYB certification. Do you have any data that needs to be stored now? In addition, please explain how you searched for sp and the subsequent storage plan.

**Comment by Defil2022** [comment]
@johnhash1992 Does your dataset have been prepared yet? When will you be able to onboard your data on the network if you get the Datacap?

**Comment by johnhash1992** [comment]
Hi,@Defil2022 YES,we have prepared datasets ready to transfer data

**Comment by Defil2022** [comment]
Well, thanks for your reply. @johnhash1992 
since you have done the KYB, I'd love to see more famous enterprises join in the Filecoin network. 
will support it. and I will keep in touch about this ticket.

**Comment by Defil2022** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecmiuxusd6ahdzpju3phqf23oyo3cgjdgweq4arov4z4zppvaff2c 
#### Address 
> f1imiomfkdnrnu4g6lykbyzmepbvsnbta44jylfla
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1dnb3uz7sylxk6emti3ififcvu3nlufnnsjui6ea
#### Id
> 9e1145e7-66a5-4553-bf5b-86535474da2f
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecmiuxusd6ahdzpju3phqf23oyo3cgjdgweq4arov4z4zppvaff2c

**Comment by YuanHeHK** [comment]
Zhejiang Geely Holding Group is a very well-known car manufacturing company in China. The application applicant contacted me and showed me sample data, promising that the data was authentic and retrievable. So I will support this signing and continue to follow the app.

**Comment by YuanHeHK** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedqx3ahdsdjjk5bnwyiy7s4h2nn5uwz6pmcflhxjcxrhtviwkqmzc 
#### Address 
> f1imiomfkdnrnu4g6lykbyzmepbvsnbta44jylfla
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1fg6jkxsr3twfnyhdlatmq36xca6sshptscds7xa
#### Id
> 9e1145e7-66a5-4553-bf5b-86535474da2f
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedqx3ahdsdjjk5bnwyiy7s4h2nn5uwz6pmcflhxjcxrhtviwkqmzc

**Comment by Sunnyiscoming** [comment]
@YuanHeHK Have you do KYB for this client? Can you share some details?

**Comment by raghavrmadya** [comment]
There is an another application open. one of these is fake - https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1067

Notaries are requested to pause signing and conduct further due diligenc

**Comment by YuanHeHK** [comment]
@Sunnyiscoming @raghavrmadya I checked the domain name before I signed http://zgh.com/. I have also checked the company information corresponding to the domain name.
![1](https://user-images.githubusercontent.com/69455705/206353339-fbed8a9f-1271-4deb-969b-e8f6e7783cef.png)
![2](https://user-images.githubusercontent.com/69455705/206353348-0dcbe41f-7312-44d2-a883-fc37fd86ed36.png)

I very much hope that such influential large enterprises can enter the Filecoin storage system.
But now that #1019 and #1067 look a bit controversial, @johnhash1992 perhaps you should provide more information to illustrate it.

**Comment by NDLABS-OFFICE** [comment]
As far as I know, Geely is a large enterprise, they may be applications for different projects submitted by different organizations.
@raghavrmadya

**Comment by filplus-checker** [comment]
## DataCap and CID Checker Report[^1]
 - Organization: `Zhejiang Geely Holding Group`
 - Client: `f1imiomfkdnrnu4g6lykbyzmepbvsnbta44jylfla`
### Storage Provider Distribution
The below table shows the distribution of storage providers that have stored data for this client.

If this is the first time a provider takes verified deal, it will be marked as `new`.

For most of the datacap application, below restrictions should apply.
 - Storage provider should not exceed 25% of total datacap.
 - Storage provider should not be storing duplicate data for more than 20%.
 - Storage provider should have published its public IP address.
 - All storage providers should be located in different regions.

⚠️ [f01983523](https://filfox.info/en/address/f01983523) has sealed 62.11% of total datacap.

⚠️ 86.47% of total deal sealed by [f01983523](https://filfox.info/en/address/f01983523) are duplicate data.

⚠️ [f01983523](https://filfox.info/en/address/f01983523) has unknown IP location.

⚠️ [f01924258](https://filfox.info/en/address/f01924258) has sealed 37.89% of total datacap.

⚠️ 84.35% of total deal sealed by [f01924258](https://filfox.info/en/address/f01924258) are duplicate data.

⚠️ [f01924258](https://filfox.info/en/address/f01924258) has unknown IP location.

⚠️ All storage providers are located in the same region.

| Provider                                              | Location | Total Deals Sealed | Percentage | Unique Data | Duplicate Deals |
| :---------------------------------------------------- | -------: | -----------------: | ---------: | ----------: | --------------: |
| [f01983523](https://filfox.info/en/address/f01983523) |  Unknown |          11.78 TiB |     62.11% |    1.59 TiB |          86.47% |
| [f01924258](https://filfox.info/en/address/f01924258) |  Unknown |           7.19 TiB |     37.89% |    1.13 TiB |          84.35% |

![Provider Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/1019/1671098373587.png)
### Deal Data Replication
The below table shows how each many unique data are replicated across storage providers.
- No more than 25% of unique data are stored with less than 4 providers.

⚠️ 100.00% of deals are for data replicated across less than 4 storage providers.

| Unique Data Size | Total Deals Made | Number of Providers | Deal Percentage |
| ---------------: | ---------------: | ------------------: | --------------: |
|         2.72 TiB |        18.97 TiB |                   1 |         100.00% |

![Replication Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/1019/1671098374260.png)
### Deal Data Shared with other Clients
The below table shows how many unique data are shared with other clients.
Usually different applications owns different data and should not resolve to the same CID.

⚠️ CID sharing has been observed.

| Other Client                                                                                                          | Application       | Total Deals Affected | Unique CIDs |        Verifier |
| :-------------------------------------------------------------------------------------------------------------------- | :---------------- | -------------------: | ----------: | --------------: |
| [f1mhyxd4unemmhrw4dbhjcovivayrj3tyactezmzq](https://filfox.info/en/address/f1mhyxd4unemmhrw4dbhjcovivayrj3tyactezmzq) | `GOLDEN SECURITY` |             7.25 TiB |          40 | LDN v3 multisig |

[^1]: To manually trigger this report, add a comment with text `checker:manualTrigger`

**Comment by Sunnyiscoming** [comment]
@johnhash1992 Can you send KYB email again to [filplus-app-review@fil.org](mailto:filplus-app-review@fil.org)?

**Comment by johnhash1992** [comment]
@raghavrmadya @Sunnyiscoming ,  HI,  I send KYB email again. 
<img width="459" alt="image" src="https://user-images.githubusercontent.com/114469357/208818196-f73fd0fb-3484-47e8-9244-c89f74049b1f.png">

#1067 i guess it's a apply from another department

**Comment by raghavrmadya** [comment]
@Defil2022 @YuanHeHK , please check client's dal making behavior highlighted by CID checker bot and client is also rquested to send email from again. We can't see email in the email sent
![image](https://user-images.githubusercontent.com/91579519/209033859-c4484be7-29ef-42bb-9971-ea8c02bcd50c.png)

**Comment by cryptowhizzard** [comment]
Cid sharing with https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1019 ( Golden Security ).

Please explain.

**Comment by johnhash1992** [comment]
Hi,@cryptowhizzard 

I'm sorry to hear that.
We understand that this is because the sp we contacted was distributing the data and some of our data was distributed incorrectly due to technical issues. We will be adjusting our current collaboration for a short period of time to ensure that this issue does not occur in the next data storage.

**Comment by cryptowhizzard** [comment]
Hi @johnhash1992 

I would like you to fill out [this form](https://form.jotform.com/230232885049356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

**Comment by johnhash1992** [comment]
@cryptowhizzard  form submited

**Comment by cryptowhizzard** [comment]
Hi @johnhash1992 

Thanks for filling in.

Can you let us know who is taking care of the data packing now as you indicated that you own the data and are the customer. If you can please send me their contact info to kyc@dcent.nl

The miner distribution that you have sent us looks ok. Miners have an OK reputation.

**Comment by johnhash1992** [comment]
@cryptowhizzard  Hello sir, because our business-level regulations do not allow us to do so. Our requirements for storage service providers are also written in the cooperation agreement, so the storage service providers we contact will ensure that our data is stored in accordance with the rules. As a client, I also make the data public. Hope to get your support.

**Comment by johnhash1992** [comment]
@herrehesse Because we signed a non-disclosure agreement

**Comment by lvschouwen** [comment]
@johnhash1992 
So you confirm this LDN is not public data that cannot be retrieve and you are not able to disclose any information because of signed NDAs. 

Shall we stop this nonsense and close this LDN as we can conclude this is all bogus?

**Comment by herrehesse** [comment]
@johnhash1992 Could you please provide full disclosure of the miner ID's, the business names, and the entity responsible for the data preparation for the FIL+ program? As the community places a high value on transparency, the NDA you signed regarding the data preparation is not relevant to us.
