### ISSUE TITLE
[DataCap Application] SuperMeofficial

### ISSUE THREAD

**Issue by lea13sda** [filecoin-project/filecoin-plus-large-datasets#1020]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name:SuperMeofficial
- Website / Social Media:https://www.facebook.com/supermiiofficial
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):5 PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):100TiB
- On-chain address for first allocation:f1ed7vkc4uqrjlj4pzoo7pdytlbh6wphleptud2ji

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
MaoYoo Network focuses on the development and operation of mobile Internet applications, our mission: technology makes your life happier! The company has developed a variety of mobile phone applications and game products. Among them, the "SuperMe" App has accumulated over 15 million downloads worldwide, and "Cool Face" has more than 3 million downloads in China; its active users are all over the world, and it is a popular avatar maker app for anime fans around the world. The Maoyou team shares moving products for animation fans around the world with feelings as the original intention. Aiming to build the company into a unicorn in the development of application software in the global animation industry.
1. We have 15 million users in 147 countries around the world, DMU: 1 million+
2. We also have online storage NFT services, etc. At present, we have developed a website to help users store valid NFT original element data online, and it is currently in operation for promotion.

```

What is the primary source of funding for this project?
```
Company revenue: advertising revenue, download revenue
```

What other projects/ecosystem stakeholders is this project associated with?
```
Animation industry application software, NFT
```

## Use-case details

Describe the data being stored onto Filecoin
```
The data stored on Filecoin includes nft, pictures, and bbs, as well as videos related to us published by animation fans across the network. We all need to save it.
```

Where was the data in this dataset sourced from?
```
Our apps, forums, and company promotions
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://opensea.io/collection/richpunkclubpolygon
https://www.youtube.com/results?search_query=supermii
https://bbs.supermii.cn

```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
It is public data
```

What is the expected retrieval frequency for this data?
```
The frequency of retrieval is relatively low
```

For how long do you plan to keep this dataset stored on Filecoin?
```
We are sharing touching products for anime lovers all over the world, I hope he can keep it forever
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Currently planning to be in Singapore
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
we are distributed office, the location will not be fixed, so we will choose online transmission.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We are prefer to find suitable miners in the storage provider interface released by Filecoin. 
```

How will you be distributing deals across storage providers?
```
We plan to select four to five miners, each miner will be allocated 20%-25%.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
yes,we have enough funds to support this project. I‘d like to communicate more with filecoin community.
```

**Comment by raghavrmadya** [comment]
No official website and samples provided cannot prove the need for 5 PiBs

**Comment by raghavrmadya** [comment]
<img width="971" alt="Screen Shot 2022-10-23 at 6 11 54 AM" src="https://user-images.githubusercontent.com/91579519/197375024-f2038fed-f5f1-4015-8096-59fce5f6357a.png">

**Comment by lea13sda** [comment]
Hello, @raghavrmadya 
I have edited the official website and sample data. 
Please tell me what else I need to provide.  
What's more, do you mind reopening my application ticket? 
I would appreciate it if you could reply ASAP.

This is the official website I added:
> Website / Social Media: https://maoyoo.net/ https://www.facebook.com/supermiiofficial

Here is my added sample data:
> https://opensea.io/collection/richpunkclubpolygon
https://drive.google.com/file/d/1geZB4IbjggAOxdGnbCza7zeZvj9ggXoU/view?usp=sharing
https://drive.google.com/file/d/12en2YcROTCtw997secTmc6WUAOnAKJ7L/view?usp=sharing
https://drive.google.com/file/d/1S1eF5_En-u7nD5ZZWIYC4mQTAW2XQKIY/view?usp=sharing
https://drive.google.com/file/d/1PsVeG-kGqrtTtC0jLnNN6Q_unERGbbSK/view?usp=sharing
https://drive.google.com/file/d/137Eju72q2ebWaIHRccNyWS5oz8F4k1vT/view?usp=sharing
https://drive.google.com/file/d/1lmubHvUr8ryUzQn6NNzaAEHtdVCue1DX/view?usp=sharing
https://drive.google.com/file/d/1Wyew_MlV97ZShangYS0a2pRjDhK5ILC6/view?usp=sharing
https://drive.google.com/file/d/1jntG5mSTZguQC7SM39RT3XQcBdERs7eO/view?usp=sharing
https://drive.google.com/file/d/1qbzYao_ATmztglomwzfW_GL_AxskPgrY/view?usp=sharing
https://drive.google.com/file/d/1ekMEzHATew-diOzfatkEa9y6x7xTrUDt/view?usp=sharing
https://drive.google.com/file/d/1Gra9mU26-_CruQo7JwxAT6UvPLgWAHGZ/view?usp=sharing
https://drive.google.com/file/d/1VhhhkXTebGUI-9Ih3BA-S1ixT_pOMRTV/view?usp=sharing
https://drive.google.com/file/d/1fOdG3zEmMo7lHQUY1ZP-95-2TKydFO3Q/view?usp=sharing
 Thank you!

**Comment by NDLABS-OFFICE** [comment]
I checked the official website and it looks good.
The data samples you submitted seem to be presentation videos of some projects. The content of the videos is very interesting, and I am willing to support them.
@raghavrmadya
