### ISSUE TITLE
[DataCap Application] Resource Pro

### ISSUE THREAD

**Issue by resourcepro1** [filecoin-project/filecoin-plus-large-datasets#1021]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Resource Pro
- Website / Social Media: https://career.resourceprochina.com/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5 PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100 TiB
- On-chain address for first allocation: f12t5oquxanhtmhsywww2h27xt4qmkoi55xq2tb4i

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Founded in 2003, Resource Pro is headquartered in New York City with five 
global business centers in Qingdao, China, Huangdao, Jinan, Bangalore, India 
and Lincoln, USA to provide 24/7 business services for our clients’ operational
 needs. Through its four business modules : Strategy Consulting, Process
 Management, People Training, and Data Analytics, Resource Pro provides 
strategic services across the entire operational lifecycle with its unique 
productivity optimization platform.
```

What is the primary source of funding for this project?
```
Company profit.
```

What other projects/ecosystem stakeholders is this project associated with?
```
No.
```

## Use-case details

Describe the data being stored onto Filecoin
```
Public datasets from industry for data analyzing.
```

Where was the data in this dataset sourced from?
```
Open data collected by our company.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
Yes.
https://drive.google.com/drive/folders/19Z8OBNEYzqAHUOws6qYiCBaKx3GqJP8R?usp=sharing
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
We can confirm that, it can be viewed by anyone.
```

What is the expected retrieval frequency for this data?
```
once per year.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
We hope to permanently store the data.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Asia, America.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Both online and offline transmissions are possible.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We are looking for the suitable SPs from FIL community and evaluate the more trustworthy SPs.
```

How will you be distributing deals across storage providers?
```
We are trying to store 5 replica of data on different SPs, and follow guidelines to allocate the data to every SP, detail plan will discuss among all the SPs. 
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes.
```

**Comment by fabriziogianni7** [comment]
## Datacap Request Trigger
#### Total DataCap requested 
> 500TiB
#### Expected weekly DataCap usage rate 
> 100TiB 
#### Client address
> t1y6grz7kkjs5wyvg4mp5jqjl3unqt7t5ktqlrf2q

**Comment by Sunnyiscoming** [comment]
Can you explain your data composition? How many copies will you store?
What's the relationship between you and the organization?
Can you provide more detailed information about other storage providers participated in this program, such as you can list SPs you have contacted with at present?

**Comment by resourcepro1** [comment]
@Sunnyiscoming We have quite a lot of datasets related to our research area, we would like to store 8 copies of our current datasets. I am the software development staff of our company, SPs we have been contacted with are f032824, f01201505,
f0495421, f01385207.

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 100TiB

**Client address**

> f12t5oquxanhtmhsywww2h27xt4qmkoi55xq2tb4i

**Comment by stcouldlisa** [comment]
@resourcepro1 ，Can you email filplus-app-review@fil.org using your official domain name to confirm your identity?
Email name should contain Issue ID #1021.

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Looking at your application i have some questions:
As you are brand new on Github and have no history of past applications it seems to me that applying for 5PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?

Can you show us visible proof of the size of your data and the storage systems you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230232885049356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!

**Comment by Sunnyiscoming** [comment]
> @resourcepro1 ，Can you email [filplus-app-review@fil.org](mailto:filplus-app-review@fil.org) using your official domain name to confirm your identity? Email name should contain Issue ID #1021.

Do not receive KYC email from the client.
