### ISSUE TITLE
[DataCap Application] Teerafusion for Drust-Agee

### ISSUE THREAD

**Issue by Agee-Drust** [filecoin-project/filecoin-plus-large-datasets#1023]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Drust
- Website / Social Media:n/a
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):100TiB
- On-chain address for first allocation:f14dn4r33t7gybigxqb6g6osdn4dwrr6rb27tdo6a

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
I‘m a member in Filecoin, but I have ambitious with Filecoin and Filecoin slingshot about ensuring meaningful data is stored and retrieved from the Filecoin Network.
```

What is the primary source of funding for this project?
```
My own source.
```

What other projects/ecosystem stakeholders is this project associated with?
```
Slingshot.
```

## Use-case details

Describe the data being stored onto Filecoin
```
The Terra Basic Fusion dataset is a fused dataset of the original Level 1 radiances from the five Terra instruments. They have been fully validate to contain the original Terra instrument Level 1 data.
```

Where was the data in this dataset sourced from?
```
AWS S3 Public Bucket Containing Terra Basic Fusion Hierarchical Data Format 5 (HDF5) files.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
aws s3 ls --no-sign-request s3://terrafusiondatasampler/
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
I confirm. This is a open dataset.
```

What is the expected retrieval frequency for this data?
```
Follow LDN Application rules. 1-2 times half a year.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
More than 2 year.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
All regions, especially SPs in Asia. 
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
After CAR files are ready, I will upload it to the server for SP, or I will prepare disks. Then I will propose offline deals after they get files.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
I plan to make deals with SPs that support data retrieval and have stable sealing rate. Also, I welcome every one who are interested with this deal.
```

How will you be distributing deals across storage providers?
```
Try to make every SP under 25% of deals.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Enough.
```

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 100TiB

**Client address**

>f14dn4r33t7gybigxqb6g6osdn4dwrr6rb27tdo6a

**Comment by UnionLabs2020** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebije4x7mglhqbck44cbucyiadz36aejjwbkg7teqob5lwxxlvtuo 
#### Address 
> f14dn4r33t7gybigxqb6g6osdn4dwrr6rb27tdo6a
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f17xdri3wunqgld7dm23e4f3eqsntjakwc47xjo6i
#### Id
> 80de6a91-b05d-4cbf-b9d7-4d80f9f8a387
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebije4x7mglhqbck44cbucyiadz36aejjwbkg7teqob5lwxxlvtuo

**Comment by MetaWaveInfo** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaf2ye3mgajyspkn2wtoq2pst6pgqawu65edrfg3h4kuhv4qr3rfe 
#### Address 
> f14dn4r33t7gybigxqb6g6osdn4dwrr6rb27tdo6a
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1ktlkcxnmzxcdaoqfsunrg3vocfbmgv4n3mrn74a
#### Id
> 80de6a91-b05d-4cbf-b9d7-4d80f9f8a387
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaf2ye3mgajyspkn2wtoq2pst6pgqawu65edrfg3h4kuhv4qr3rfe

**Comment by Sunnyiscoming** [comment]
Is there any problem with using datacap?

**Comment by Aifabot-Cloud** [comment]
checker:manualTrigger

**Comment by Aifabot-Cloud** [comment]
The client followed the allocation plan as planned, good report is all dimensions. Keep it up!

**Comment by Aifabot-Cloud** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedpyaeh4pnbie5wyeypywuddnp7plqgrleypyh2inluawzunx74uu 
#### Address 
> f14dn4r33t7gybigxqb6g6osdn4dwrr6rb27tdo6a
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f174fg3bqbln3zjnkxtyf6s54txqkr7yqkj6cig7y
#### Id
> 2c4625ee-0a25-4ff4-b7a2-ac22291e3d3f
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedpyaeh4pnbie5wyeypywuddnp7plqgrleypyh2inluawzunx74uu

**Comment by TakiChain** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceahatqa3wxzceevwqbdacpjrtkfywyx5eokcg24zivkejqfxvo74c 
#### Address 
> f14dn4r33t7gybigxqb6g6osdn4dwrr6rb27tdo6a
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f15impf3j2zcaex4lhyxndxswuuhv24vzstuqtxsi
#### Id
> 2c4625ee-0a25-4ff4-b7a2-ac22291e3d3f
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceahatqa3wxzceevwqbdacpjrtkfywyx5eokcg24zivkejqfxvo74c

**Comment by Suyanj** [comment]
checker:manualTrigger

**Comment by Suyanj** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceahsdgqmmll6y3l2hjzmsfc7klnoouh2nhhhqsx4cldxcufsvbkga 
#### Address 
> f14dn4r33t7gybigxqb6g6osdn4dwrr6rb27tdo6a
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1ihv7gz3vn3xqvikpt4rwryecgisl7745lodx3yi
#### Id
> 72bd0205-b505-43ab-afda-33764f4e1359
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceahsdgqmmll6y3l2hjzmsfc7klnoouh2nhhhqsx4cldxcufsvbkga

**Comment by Suyanj** [comment]
LGTM, but should improve the Deal Data Replication in the next round.

**Comment by AthSmith** [comment]
checker:manualTrigger

**Comment by AthSmith** [comment]
CID checker ok, retrieval can be done. Willing to support!

**Comment by AthSmith** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceamsdubssiofxqpfkvpbl23bpiz5vgpnifk2jxbeax43h6i4qn2ei 
#### Address 
> f14dn4r33t7gybigxqb6g6osdn4dwrr6rb27tdo6a
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1vxbqrf7rfum3n6m5u6eb4re6xj7amvsaqnzu64y
#### Id
> 72bd0205-b505-43ab-afda-33764f4e1359
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceamsdubssiofxqpfkvpbl23bpiz5vgpnifk2jxbeax43h6i4qn2ei

**Comment by Agee-Drust** [comment]
Thanks for notaries' support.

**Comment by Agee-Drust** [comment]
Keep open!

**Comment by Agee-Drust** [comment]
Keep open!

**Comment by Agee-Drust** [comment]
Keep open!

**Comment by PluskitOfficial** [comment]
checker:manualTrigger

**Comment by PluskitOfficial** [comment]
Looks good. Willing to support.

**Comment by PluskitOfficial** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedq2cbzkxa5jbzutomms7x5k7v5cslhglrowqxk2e6zzredphhfjw 
#### Address 
> f14dn4r33t7gybigxqb6g6osdn4dwrr6rb27tdo6a
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1tgnlhtcmhwipfm7thsftxhn5k52velyjlazpvka
#### Id
> 44e1784c-3dab-4a65-93b2-35b7143810a1
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedq2cbzkxa5jbzutomms7x5k7v5cslhglrowqxk2e6zzredphhfjw

**Comment by MatrixStorage** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceahqjpjcyfzhf7ub6lyaxffdhisdlwlcmltmmuq7sbnq4lujh3m3a 
#### Address 
> f14dn4r33t7gybigxqb6g6osdn4dwrr6rb27tdo6a
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1tbxqwjxfyv7swsdin4einirlsfquv3vnmlapley
#### Id
> 44e1784c-3dab-4a65-93b2-35b7143810a1
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceahqjpjcyfzhf7ub6lyaxffdhisdlwlcmltmmuq7sbnq4lujh3m3a

**Comment by Bennyyangpu** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecv7zrjnx7422kcn65k4bw2mjf7yvqtrcee3ezgw667kmtr6vtcxy 
#### Address 
> f14dn4r33t7gybigxqb6g6osdn4dwrr6rb27tdo6a
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f174fg3bqbln3zjnkxtyf6s54txqkr7yqkj6cig7y
#### Id
> ac046d60-9d38-4f27-8b56-92f2644c05da
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecv7zrjnx7422kcn65k4bw2mjf7yvqtrcee3ezgw667kmtr6vtcxy

**Comment by Wengeding** [comment]
LGTM, willing to support!

**Comment by Wengeding** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec24abzgm2tn4npxqifolyssrn7xneqbgc2olzyigcdmfl4day2oi 
#### Address 
> f14dn4r33t7gybigxqb6g6osdn4dwrr6rb27tdo6a
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1txfsjmix4vlzido4dkildrnbw26owtlbslexmpa
#### Id
> ac046d60-9d38-4f27-8b56-92f2644c05da
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec24abzgm2tn4npxqifolyssrn7xneqbgc2olzyigcdmfl4day2oi

**Comment by kevzak** [comment]
Hello @Agee-Drust per the https://github.com/filecoin-project/notary-governance/issues/922 for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

This information will be reviewed by Fil+ Governance team to confirm validity and then the application will be allowed to move forward for additional notary review.

**Comment by Agee-Drust** [comment]
@kevzak Hi, I submitted this form just now. Please check it.

**Comment by kevzak** [comment]
f01879772 | Ronald | HongKong | 
f02368314 | Barry | Deyang, Sichuan, CN |
f01084913 | Bill | HongKong | 
f01452388 | Sheldon | Hangzhou, Zhejiang, CN | 
f0148494 | Amy | Sham Shui Po |

**Comment by herrehesse** [comment]
![Screenshot 2023-11-14 at 10 00 04](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/70132857/c443b102-e170-41ed-9bfc-02722cad6eb6)

Entity is self-dealing, SP reputation is as bad as it goes, owner wallets are the same.

Close this LDN immediately @kevzak

**Comment by Sunnyiscoming** [comment]
checker:manualTrigger

**Comment by Sunnyiscoming** [comment]
@Agee-Drust 
More sps participate in datacap storage.
Closing until all SP ID list, entity and location is provided.
