### ISSUE TITLE
[DataCap Application] Foldingathome COVID-19 Dataset

### ISSUE THREAD

**Issue by Megan008** [filecoin-project/filecoin-plus-large-datasets#1024]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Public Data-Foldingathome COVID-19
- Website / Social Media: https://registry.opendata.aws/foldingathome-covid19/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):100TiB
- On-chain address for first allocation:f1au3nipqjprr5xp2mwsarr7obvpx2dwy4is6qn4y

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
I have participated in some projects and hackathon. I have experience on it.
```

What is the primary source of funding for this project?
```
Personal income.
```

What other projects/ecosystem stakeholders is this project associated with?
```
No.
```

## Use-case details

Describe the data being stored onto Filecoin
```
[Folding@home](http://foldingathome.org/) is a massively distributed computing project that uses biomolecular simulations to investigate the [molecular origins of disease](https://foldingathome.org/diseases/) and accelerate the discovery of new therapies.
```

Where was the data in this dataset sourced from?
```
Simulations of SARS-CoV-2 and associated host proteins, with emphasis on discovering druggable cryptic pockets, documented at the [MolSSI COVID Hub](https://covid.molssi.org//simulations/#foldinghome-simulations-of-the-sars-cov-2-spike-protein-spike-spike-binding).
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://registry.opendata.aws/foldingathome-covid19/
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes, it's a public dataset.
```

What is the expected retrieval frequency for this data?
```
Multiple times.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
2 years.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
North america; Korea; China.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
75% data will be distributed by offline data transfer. Other data will use online transfer for distributing with storage providers who close to me.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
I would let 1 sp who used to cooperate with me for this deal. Now I'm chatting with other sps. f023495, f0508988
```

How will you be distributing deals across storage providers?
```
I have communicated with 4 sp. In first time, I will divide 1/4 data to each sp. If I find out more sp, I will decrease the percentage of deals to them --- for decentralized storage. 
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes.
```

**Comment by raghavrmadya** [comment]
Do you have permission from Folding@home?

**Comment by raghavrmadya** [comment]
Who are the SPs you plan to work with and what exactly is your data transfer plan? the outlined plan is really unclear

**Comment by Megan008** [comment]
@raghavrmadya Thank you for your questions.
COVID-19 is a public dataset and is not exclusive to a specific organization. So it is not necessary to have permission from folding@home in advance to download and store the dataset. It is similar to how programmers do not need to get permission from github to use their public code.
The SPs we have worked and discussed before include f01854755, f01823070 and f01878693, etc. After our application has been approved, we plan to divide data to 8-10 SPs according to BDE platform.

**Comment by raghavrmadya** [comment]
Thanks @Megan008. We have cases before where clients have needed approval of the manager for public data sets. I also see that you have many applications open. Can you share more about yourself and any organization you are representing as onboarding many PiBs of data through multiple applications requires a team effort. I'm tagging @Kernelogic as they have dealt with such challenges with clients before as it relates to public datasets

**Comment by kernelogic** [comment]
Folding@home dataset is CreativeCommons licensed so license wise it should be fine. 

It consists about 450TB of raw data from AWS S3: 
arn:aws:s3:::fah-public-data-covid19-antibodies | us-east-2 | 8.6 TiB
arn:aws:s3:::fah-public-data-covid19-cryptic-pockets | us-east-2  | 71.0 TiB
arn:aws:s3:::fah-public-data-covid19-absolute-free-energy | us-east-2 | 369.5 TiB
arn:aws:s3:::fah-public-data-covid19-moonshot-dynamics | us-east-2 | 1.8 TiB

However, I would have the following questions:
1. This dataset has been onboarded many times during Slingshot v2, it is also included in the Slingshot v3.
2. For open dataset I think it is important to provide ways to index / retrieve, not just backup. Like in Slingshot v2 we were asked to provide websites and documents about how the data can be used. Do you have any plans on this regard?
3. Download 450TB of raw data requires significant internet bandwidth, where are you located and do you have it?

**Comment by Megan008** [comment]
@raghavrmadya I'm a community member. As I mentioned before, I'm going to contact more SPs to distribute data via BDE platform next. And I also have sp that I have worked with will continue to work together, so I think we can complete it.
> @raghavrmadya Thank you for your questions. COVID-19 is a public dataset and is not exclusive to a specific organization. So it is not necessary to have permission from folding@home in advance to download and store the dataset. It is similar to how programmers do not need to get permission from github to use their public code. The SPs we have worked and discussed before include f01854755, f01823070 and f01878693, etc. After our application has been approved, we plan to divide data to 8-10 SPs according to BDE platform.

**Comment by Megan008** [comment]
@kernelogic  Thank you for your points and concern! I am currently in Singapore, but I look forward to contacting SPs around the world. I am not participating in the Slingshot, so I think I need to follow LDN's rules rather than slingshot's.

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 100TiB

**Client address**

>f1au3nipqjprr5xp2mwsarr7obvpx2dwy4is6qn4y

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 100TiB

**Client address**

>f1au3nipqjprr5xp2mwsarr7obvpx2dwy4is6qn4y

**Comment by cryptowhizzard** [comment]
#1062 
#1362

**Comment by TakiChain** [comment]
The applicant contacted me via DM and went through our due diligence. Willing to support in the first round and will keep an eye on later allocations. Looking forward to seeing your next milestone.

**Comment by TakiChain** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedq4hx2jsgyifcgazexuerxpsrkxlpvjl6f4e25667gzgaq7gexfc 
#### Address 
> f1au3nipqjprr5xp2mwsarr7obvpx2dwy4is6qn4y
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f15impf3j2zcaex4lhyxndxswuuhv24vzstuqtxsi
#### Id
> fd3d1516-a183-467e-9ad7-01964bb49b11
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedq4hx2jsgyifcgazexuerxpsrkxlpvjl6f4e25667gzgaq7gexfc

**Comment by Protocan** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecubgphhwp2m6spj7idtuvaaopy2ohlpawpkrkxpruz62lgcqxeks 
#### Address 
> f1au3nipqjprr5xp2mwsarr7obvpx2dwy4is6qn4y
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1vxbqrf7rfum3n6m5u6eb4re6xj7amvsaqnzu64y
#### Id
> fd3d1516-a183-467e-9ad7-01964bb49b11
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecubgphhwp2m6spj7idtuvaaopy2ohlpawpkrkxpruz62lgcqxeks

**Comment by BobbyChoii** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedemxymy7etyr37dk57soef4zczfyxvoqmafdthz4lvyjnjaaug76 
#### Address 
> f1au3nipqjprr5xp2mwsarr7obvpx2dwy4is6qn4y
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1irqs2gmctiv3jcdfwuch7oxvf4ixh3k4b2wc24i
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedemxymy7etyr37dk57soef4zczfyxvoqmafdthz4lvyjnjaaug76

**Comment by Casey-PG** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebluals2lpiz7lbjkcuxivocn6drljn5umrfmlzghkvqaosn6b63s 
#### Address 
> f1au3nipqjprr5xp2mwsarr7obvpx2dwy4is6qn4y
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f15impf3j2zcaex4lhyxndxswuuhv24vzstuqtxsi
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebluals2lpiz7lbjkcuxivocn6drljn5umrfmlzghkvqaosn6b63s

**Comment by Aifabot-Cloud** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedxtl7kpxvlndxflemhl2cqlgu5w3gtxjatmdtnhv7fbsl3mqdqmi 
#### Address 
> f1au3nipqjprr5xp2mwsarr7obvpx2dwy4is6qn4y
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f174fg3bqbln3zjnkxtyf6s54txqkr7yqkj6cig7y
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedxtl7kpxvlndxflemhl2cqlgu5w3gtxjatmdtnhv7fbsl3mqdqmi

**Comment by cryptowhizzard** [comment]
Reported for datacap abuse and violation of code of conduct.

@raghavrmadya @dkkapur

**Comment by Meibuy** [comment]
checker:manualTrigger

**Comment by Meibuy** [comment]
The client followed the allocation plan as planned, good report is all dimensions. Keep it up!

**Comment by Meibuy** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecmz55642hdg5pgzop7blkrc52pe3qkrp5ch2xx3sdofcl4ybwove 
#### Address 
> f1au3nipqjprr5xp2mwsarr7obvpx2dwy4is6qn4y
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1bwugfihrmn3iyunzyxst5nttql3dge4khwmurtq
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecmz55642hdg5pgzop7blkrc52pe3qkrp5ch2xx3sdofcl4ybwove

**Comment by Meibuy** [comment]
Just saw the record that the applicant has some non-compliant usage records, but not this application. I don't know what the community's opinion is on whether applicants with non-compliant usage records are allowed to apply for LDN again, I hope to have an answer soon?   

Willing to abide by the consensus opinion of the community.

**Comment by cryptowhizzard** [comment]
@Meibuy 

Yes, the opinion is that if someone harms the community that there should be due diligence done in a way that it cannot happen again.

You signed on an application that is disputed in notion. I will add this to the dispute list.

**Comment by Aifabot-Cloud** [comment]
I noticed that the applicant had a violation record before signing. However, she repeatedly assured me in DMs that it was a cooperation issue of miners. There will be no such problem in the future. I think the applicant knows enough about Filecoin as a hackathon participant, so I decided to give her a chance to prove herself again. So far, the report of this application looks healthy. 

We all know that Github is easy to sign up for, and applicants can use different accounts to apply for LDN applications. After the filplus checker went live, many applications had problems with duplicate data. I would like to know the community's views of these applications and the applicants.

**Comment by BobbyChoii** [comment]
I agree with the above points. There are no explicit rules for clients who have been in dispute before. I will abide by community feedback and official recommendations on how to handle such applications.

**Comment by cryptowhizzard** [comment]
[quote]I noticed that the applicant had a violation record before signing. However, she repeatedly assured me in DMs that it was a cooperation issue of miners. [/quote]

How? @Megan008 is a data preparer. She sends her data from her wallet to an SP as a verified deal. 
What happened is that she did not pack the dataset as she said. She packed only a few files and shared that thousands of times with the people involved in that scheme.
Miners can just accept a deal for a price. They don't have influence on what is stored on their drives so don't come here with those fairytales.

Again ... You guys decided to sign a disputed application. The rules for this are clear, you should not. Reasons why are also clear.

From my point of view the dispute is valid. Datacap should be revoked. If we were to get an upfront answer i would reconsider but we A don't get any KYC and B don't get any honest answer on what happened. Thirdly it is beyond me that we get dozens of new Github handles per day ( from the same people ) and specifically this one needs attention to continue. 

@dkkapur @raghavrmadya your call.

**Comment by Megan008** [comment]
@cryptowhizzard Sorry for raising disputes. I understand that past mistakes may have reduced my trustworthiness. I'm deeply sorry about it and i wish i can get a chance to prove that i'm fixing it. Please tell me what should I do.

**Comment by TakiChain** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebwgiuxbzfcmuga4cpudzlu5hxwgghhkbnt2a54goaulifwscryms 
#### Address 
> f1au3nipqjprr5xp2mwsarr7obvpx2dwy4is6qn4y
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f15impf3j2zcaex4lhyxndxswuuhv24vzstuqtxsi
#### Id
> dc5d06c4-9f85-4bc9-8090-0060f99e192c
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebwgiuxbzfcmuga4cpudzlu5hxwgghhkbnt2a54goaulifwscryms

**Comment by Suyanj** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebktvx7k47limisrv73ioz6c7xgkbgjyc4mxtu2wq2bth4p4a5voa 
#### Address 
> f1au3nipqjprr5xp2mwsarr7obvpx2dwy4is6qn4y
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1ihv7gz3vn3xqvikpt4rwryecgisl7745lodx3yi
#### Id
> b1b3a935-36cc-4800-90cb-7c5b98cd6d12
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebktvx7k47limisrv73ioz6c7xgkbgjyc4mxtu2wq2bth4p4a5voa

**Comment by Suyanj** [comment]
Public data with clear allocation plan, we are willing to help onboard more valuable dataset.

**Comment by Aifabot-Cloud** [comment]
Open datasets bring great value to the network. Happy to see more of them join Filecoin. Please keep the allocation in line with Filplus guidlines.

**Comment by HiFil** [comment]
checker:manualTrigger

**Comment by Wengeding** [comment]
checker:manualTrigger

**Comment by cryptowhizzard** [comment]
All these SP's are involved in CID sharing and do not support retrieval.

Akin, nothing works.

<img width="1678" alt="Scherm­afbeelding 2023-07-31 om 18 06 43" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/36404435/b63257d1-8386-436d-896d-4cd903db67ac">

**Comment by Bennyyangpu** [comment]
checker:manualTrigger

**Comment by Bennyyangpu** [comment]
According to the report, the situation in all aspects is relatively good.

**Comment by Bennyyangpu** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedv6vuvy6esbvl2qny5vwwpyzrdfuu6bfisxjb6ixhgbp46rio46c 
#### Address 
> f1au3nipqjprr5xp2mwsarr7obvpx2dwy4is6qn4y
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f174fg3bqbln3zjnkxtyf6s54txqkr7yqkj6cig7y
#### Id
> ce15296d-34d7-4f78-a693-db943fcaeec6
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedv6vuvy6esbvl2qny5vwwpyzrdfuu6bfisxjb6ixhgbp46rio46c

**Comment by BobbyChoii** [comment]
Didn't find any CID sharing as some notary mentioned from the application. Retrieval is ok according to the Retrieval Dashboard.
. Willing to give my sign and help to onboard this application.

**Comment by BobbyChoii** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacead5ev4ndiasciqqckdiwlkzz5lnkv3562sonc2rzaahiy5w4axoq 
#### Address 
> f1au3nipqjprr5xp2mwsarr7obvpx2dwy4is6qn4y
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1irqs2gmctiv3jcdfwuch7oxvf4ixh3k4b2wc24i
#### Id
> ce15296d-34d7-4f78-a693-db943fcaeec6
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacead5ev4ndiasciqqckdiwlkzz5lnkv3562sonc2rzaahiy5w4axoq

**Comment by cryptowhizzard** [comment]
This applicant has a long history of fraud and refuses to start working on the right path. Applications still not provide retrieval / data stored is not the data stored the applicant is saying.
<img width="676" alt="Scherm­afbeelding 2023-08-19 om 17 09 00" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/36404435/9994e243-06ca-40f5-a1ce-ebfdf1793a5c">

**Comment by Megan008** [comment]
![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/108327270/82c2ec50-ed1b-4192-a4c7-dc1cdc0c3e28)
@cryptowhizzard Is it mean not provide retrieval? Why did you lie through your teeth? Can you please do any check before you do anything?
@raghavrmadya @dkkapur Is it allow to dispute anyone just on his own words?

**Comment by cryptowhizzard** [comment]
> ![image](https://user-images.githubusercontent.com/108327270/262278597-82c2ec50-ed1b-4192-a4c7-dc1cdc0c3e28.png) @cryptowhizzard Is it mean not provide retrieval? Why did you lie through your teeth? Can you please do any check before you do anything? @raghavrmadya @dkkapur Is it allow to dispute anyone just on his own words?

It is public knowledge that the HTTP retrieval bot is gamed.

http://www.datasetcreators.com/downloadedcarfiles/logs/1024.log

Here you can find the log. Since you have range retrieval disabled ( Something natively enabled in boost ) it is clear you attempt to avoid that someone is retrieving the whole carfile to unpack it and do due diligence.

This is what your retrieval looks like. **_It is all junk and scam._**

![Scherm­afbeelding 2023-08-22 om 12 02 50](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/36404435/7417a09f-8d2c-4345-8f77-8be353eb623b)

**Comment by Megan008** [comment]
I will let SPs for check. 
>It is public knowledge that the HTTP retrieval bot is gamed.

This tool is from PL team, do you mean that it is useless? I think I can only trust people from official team.

**Comment by Carohere** [comment]
@cryptowhizzard Could you share the link to the file you downloaded? 
@Megan008 Retrieval bots can be largely trusted, but sometimes they are not accurate.

**Comment by raghavrmadya** [comment]
Hi, I'm following up on the dispute here - https://www.notion.so/filecoin/No-retrieval-supported-bfcfebbcbdbd475fab52cccaf83d4674?pvs=4

Client is requested to provide an update on retrievals if they are not satisfied with the evidence provided by @cryptowhizzard. 

Until then, application will remain under dispute and notaries are encourage to not sign without providing evidence of retrieval compliance

**Comment by Megan008** [comment]
@raghavrmadya First, I've proved that we support retrieval and the retrieval report can also show it.


> ![image](https://user-images.githubusercontent.com/108327270/262278597-82c2ec50-ed1b-4192-a4c7-dc1cdc0c3e28.png) @cryptowhizzard Is it mean not provide retrieval? Why did you lie through your teeth? Can you please do any check before you do anything? @raghavrmadya @dkkapur Is it allow to dispute anyone just on his own words?

Then, this is the retrieval download which is given by SPs.
![6e356c07-4dbf-40dd-ae57-](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/108327270/51e77855-d1c6-48db-b36e-62a208e3dfe5)

All thing means that we support retrieval.

**Comment by cryptowhizzard** [comment]
Dear Megan008,

As notary I am doing due diligence on your LDN. I could not get retrieval to work. Can you please upload the car file of CID baga6ea4seaqofl35yu6stkuaeo4nbpe543355wtaglyv74pfwtyx5uqhpag34ii ?

You can use our upload system at http://send.datasetcreators.com. Please select 7 days for the system to keep the file and post the link you received here so I (and other notaries) can download your content.

**Comment by Megan008** [comment]
> Dear Megan008,
> 
> As notary I am doing due diligence on your LDN. I could not get retrieval to work. Can you please upload the car file of CID baga6ea4seaqofl35yu6stkuaeo4nbpe543355wtaglyv74pfwtyx5uqhpag34ii ?
> 
> You can use our upload system at http://send.datasetcreators.com. Please select 7 days for the system to keep the file and post the link you received here so I (and other notaries) can download your content.

I can not open the link to do upload. It's better that you check my answer as below. It can give you what you want.
