### ISSUE TITLE
[DataCap Application] Shenzhen Most Profound Network Technology

### ISSUE THREAD

**Issue by yua3891** [filecoin-project/filecoin-plus-large-datasets#1025]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Shenzhen Most Profound Network Technology
- Website / Social Media: http://wechat.zskail.com/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 1PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100TiB
- On-chain address for first allocation: f1xxsgv4rojysunaqenekoogyutb54sqbbxukn77y

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Shenzhen Most Profound Network Technology Co., Ltd. was established on April 25, 2017. Based on artificial intelligence and blockchain technology, the company provides customers with trustworthy system solutions. Its main products include boring SCRM, gas industry ERP and other software products, serving thousands of small and medium-sized enterprises.
```

What is the primary source of funding for this project?
```
Own funds.
```

What other projects/ecosystem stakeholders is this project associated with?
```
No.
```

## Use-case details

Describe the data being stored onto Filecoin
```
In the past five years, the company has copyrighted the product plans, data manuscripts, 3D models, audio and video, etc. for customers.
```

Where was the data in this dataset sourced from?
```
Publicly available business data from the company.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://pan.baidu.com/s/1jQEXcm5d5X7UdScgYbu1jg?pwd=i8fq
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
We Confirm.
```

What is the expected retrieval frequency for this data?
```
About twice a year.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
about 36 months.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
All.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
The data is large and we transmit it offline.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We will find reputable SPs in the community to sealing  data.
```

How will you be distributing deals across storage providers?
```
Offline data transfer.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes and no additional support is needed. We may contact Filecoin slack if assistance is needed.
```

**Comment by raghavrmadya** [comment]
What's your relationship with the company?

**Comment by yua3891** [comment]
Hi, @raghavrmadya, I work for this company. I also pay attention to filecoin's storage technology, so I want to apply for a quota to store our data. thank you!

**Comment by Sunnyiscoming** [comment]
Can you explain your data composition? How many copies will you store?
What's the relationship between you and the organization?
Can you provide more detailed information about other storage providers participated in this program, such as you can list SPs you have contacted with at present?

**Comment by yua3891** [comment]
The data I'm going to store are product historical documents, including audio and video, product solutions, desensitized DB data, etc. I can store no more than 4 copies.
I am an engineer of the company.

We found some reputable storage providers in the slack to provide services for us. The following SPs were reported to me: f01926802, f01922865, f01803380, f01882219, f01953985, f01270767.

Thank you!

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 1PiB

**Expected weekly DataCap usage rate**

> 100TiB

**Client address**

> f1xxsgv4rojysunaqenekoogyutb54sqbbxukn77y

**Comment by newwebgroup** [comment]
Could you send an email to [filplus-app-review@fil.org](mailto:filplus-app-review@fil.org) with your official domain in order to confirm your identity?
Email name should includes the issue id https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1025.

**Comment by stcouldlisa** [comment]
Why did you apply for 5P?
How many copies do you plan to back up?
How much data do you have now?

**Comment by yua3891** [comment]
Actually, I only applied for 1PiB.
I plan to store 5 copies.
My current data volume is about 300TiB.

**Comment by yua3891** [comment]
hi, @newwebgroup, 
The email has been sent, thank you.

![11](https://user-images.githubusercontent.com/24313710/204957969-5e8638d6-145c-48ea-b1f5-30c24dbaa7c0.png)

**Comment by ipfscn** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecksur2yp37znatkfkdejpfed57idfgsra3nv4lhd3khazpqjbasm 
#### Address 
> f1xxsgv4rojysunaqenekoogyutb54sqbbxukn77y
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1j4n74chme7whbz3yls4a7ixqewb6dijypqg2a3a
#### Id
> baa84494-87a7-40a6-9f09-f86211d9d72e
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecksur2yp37znatkfkdejpfed57idfgsra3nv4lhd3khazpqjbasm

**Comment by newwebgroup** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced2jxy6szqhmfa4ii7uunvnxjx2a2rruregfah54wavu3poeoo5pk 
#### Address 
> f1xxsgv4rojysunaqenekoogyutb54sqbbxukn77y
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1e77zuityhvvw6u2t6tb5qlnsegy2s67qs4lbbbq
#### Id
> baa84494-87a7-40a6-9f09-f86211d9d72e
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced2jxy6szqhmfa4ii7uunvnxjx2a2rruregfah54wavu3poeoo5pk

**Comment by Sunnyiscoming** [comment]
checker:manualTrigger

**Comment by cryptowhizzard** [comment]
Hi,

Can you provide me with 2 more organizations here for storing the next tranche of datacap?
As far as i can see you store with one organization, that is against the rules of FIL+.

**Comment by sxxfuture-official** [comment]
![image](https://user-images.githubusercontent.com/113963951/230569117-a7b007ba-9712-4d59-97f9-a50eea4917cb.png)
deal_id from [https://filecoin.tools/f01985891](https://filecoin.tools/f01985891)

Randomly tested data retrievability, the result was OK.
The CID checker shows that the number of data replica is not enough, but considering that the current project is in the initial stage, adjustments must be made to this aspect later, support this round and I will continue to pay attention.

**Comment by sxxfuture-official** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceadxdaxyx5wvwiywyj4abpomcgborcbbutvbxpstefy4ryn7bp6fa 
#### Address 
> f1xxsgv4rojysunaqenekoogyutb54sqbbxukn77y
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1foiomqlmoshpuxm6aie4xysffqezkjnokgwcecq
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceadxdaxyx5wvwiywyj4abpomcgborcbbutvbxpstefy4ryn7bp6fa

**Comment by igoovo** [comment]
Provide initial support, please match the number of stored copies with the rules in the future.

**Comment by Normalnoise** [comment]
checker:manualTrigger

**Comment by Swift-scouts** [comment]
ok

**Comment by Sunnyiscoming** [comment]
Hello, @yua3891 per the https://github.com/filecoin-project/notary-governance/issues/922 for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

This information will be reviewed by Fil+ Governance team to confirm validity and then the application will be allowed to move forward for additional notary review.
