### ISSUE TITLE
[DataCap Application] Mikaelafashion

### ISSUE THREAD

**Issue by mikala-01** [filecoin-project/filecoin-plus-large-datasets#1027]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Mikaelafashion
- Website / Social Media: Official website: http://www.mikaelafashion.com/Tmall: https://mikaela.tmall.com/?spm=a220o.1000855.1997427721.d4918089.a6b912a9y9KL4V   Public account: MikaeLa McGilla  Video account: MikaeLa McGilla   Little Red Book: MikaeLa   Weibo: MikaeLa  Douyin: MikaeLa
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5 PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100TiB
- On-chain address for first allocation: f1jkf2e4ljhym3yaxdlq5cvqctpfsvecrklnsubjy

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Our brand name is: MikaeLa, a light luxury fashion clothing brand was established in 2018. Over 200 sales channels of franchise, direct sales and online sales, We’ve Formed a three-dimensional marketing pattern in the country. With its Headquarter located in Hangzhou, it has an office base of 6,000 square meters, as well as an independent storage center (warehouse) and production center (factory). As a professional garment enterprise integrating design,development, production, marketing, logistics and information technology, there will be about 1000sku products in two seasons every year.
```

What is the primary source of funding for this project?
```
Our current main sources of funding are three-fold:
1. Join fee from customers.
2. Direct sales.
3. Online channel sales.
```

What other projects/ecosystem stakeholders is this project associated with?
```
None
```

## Use-case details

Describe the data being stored onto Filecoin
```
The data stored on Filecoin is currently basically from the company's product and business-related materials, videos, pictures, advertisements, and resources.
```

Where was the data in this dataset sourced from?
```
Mainly from the company's product images and business-related data content
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
We have a large material library and will update many times a month. Here are some examples that our data shown on web. 
Tmall: https://mikaela.tmall.com/?spm=a220o.1000855.1997427721.d4918089.a6b912a9y9KL4V
Official website: www.mikaelafashion.com
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Confirmed
```

What is the expected retrieval frequency for this data?
```
Relatively low frequency
```

For how long do you plan to keep this dataset stored on Filecoin?
```
About 540 days
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Asia, North America
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
We currently place orders via online Deal, we can also transfer data via hard drive.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We will choose the SPs with stable operations and the SPs must have the real data storage experience. 
```

How will you be distributing deals across storage providers?
```
We plan to choose more than 10 storage providers. Each SPs will not received more than 10% of our datacap. 
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, we have enough resources to start storage now.
```

**Comment by mmmndnnd** [comment]
I add some sample data
Link: https://pan.baidu.com/s/1PrelF0iG6eRJTPDVCxt5jA
Extraction code: dkke

**Comment by Sunnyiscoming** [comment]
Can you explain your data composition? How many copies will you store?
What's the relationship between you and the organization?
Can you provide more detailed information about other storage providers participated in this program, such as you can list SPs you have contacted with at present?

**Comment by mmmndnnd** [comment]
Hi, @Sunnyiscoming 
Mikaela Fashion was established in 2018. I am an employee of Mikaela Fashion and am now in charge of Fil+ related issues. 

The data we will store on the Filecoin network, including product intro, online sales info, advertising materials and new products, will be released monthly. Those data will be in the type of video and images. Also, all datasets will be prepared in three or four copies.

Following SPs we are contacting: 
 f01854772; f01215819; f01834291; f01168661;f01834253;f01880364 ... 
We also look for SPs through slack and the web.  More SPs and I are contacting and we have to follow up on some internal processes.

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 100TiB

**Client address**

>f1jkf2e4ljhym3yaxdlq5cvqctpfsvecrklnsubjy

**Comment by Defil2022** [comment]
Basic info looks well. I'll keep an eye on this application. 
Hope this kind of company will follow the rule of allocation. Have you made deal done with your sps?

**Comment by Defil2022** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebxtiqmnqhmg4ru4tjehzw2vgauplx4lwjpzg4mulkrym7pb6nyq2 
#### Address 
> f1jkf2e4ljhym3yaxdlq5cvqctpfsvecrklnsubjy
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1dnb3uz7sylxk6emti3ififcvu3nlufnnsjui6ea
#### Id
> 6929c4d7-f0d7-4fc9-8a8f-525cf6f986f5
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebxtiqmnqhmg4ru4tjehzw2vgauplx4lwjpzg4mulkrym7pb6nyq2

**Comment by Tom-OriginStorage** [comment]
can you send email to [[filplus-app-review@fil.org]

**Comment by mikala-01** [comment]
Hello， @Tom-OriginStorage 
kyc email has been sent, please check
thank you!
![b9e2208333e2cf000b8a0ac91a532a6](https://user-images.githubusercontent.com/111743801/205604419-7241c731-59a8-4781-8a3b-ff9053c2c7a5.png)

**Comment by Tom-OriginStorage** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceactojmyi6sythl4yfedj2lakmayt3t5suffohxr5yx5pebhkppfi 
#### Address 
> f1jkf2e4ljhym3yaxdlq5cvqctpfsvecrklnsubjy
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1q6bpjlqia6iemqbrdaxr2uehrhpvoju3qh4lpga
#### Id
> 6929c4d7-f0d7-4fc9-8a8f-525cf6f986f5
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceactojmyi6sythl4yfedj2lakmayt3t5suffohxr5yx5pebhkppfi

**Comment by filplus-checker** [comment]
## DataCap and CID Checker Report[^1]
 - Organization: `Mikaelafashion`
 - Client: `f1jkf2e4ljhym3yaxdlq5cvqctpfsvecrklnsubjy`
### Storage Provider Distribution
The below table shows the distribution of storage providers that have stored data for this client.

If this is the first time a provider takes verified deal, it will be marked as `new`.

For most of the datacap application, below restrictions should apply.
 - Storage provider should not exceed 25% of total datacap.
 - Storage provider should not be storing duplicate data for more than 20%.
 - Storage provider should have published its public IP address.
 - All storage providers should be located in different regions.

⚠️ [f01740934](https://filfox.info/en/address/f01740934) has sealed 100.00% of total datacap.

⚠️ 79.37% of total deal sealed by [f01740934](https://filfox.info/en/address/f01740934) are duplicate data.

⚠️ All storage providers are located in the same region.

| Provider                                              |                    Location | Total Deals Sealed | Percentage | Unique Data | Duplicate Deals |
| :---------------------------------------------------- | --------------------------: | -----------------: | ---------: | ----------: | --------------: |
| [f01740934](https://filfox.info/en/address/f01740934) | Los Angeles, California, US |           7.88 TiB |    100.00% |    1.63 TiB |          79.37% |

![Provider Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/1027/1671098383373.png)
### Deal Data Replication
The below table shows how each many unique data are replicated across storage providers.
- No more than 25% of unique data are stored with less than 4 providers.

⚠️ 100.00% of deals are for data replicated across less than 4 storage providers.

| Unique Data Size | Total Deals Made | Number of Providers | Deal Percentage |
| ---------------: | ---------------: | ------------------: | --------------: |
|         1.63 TiB |         7.88 TiB |                   1 |         100.00% |

![Replication Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/1027/1671098384165.png)
### Deal Data Shared with other Clients
The below table shows how many unique data are shared with other clients.
Usually different applications owns different data and should not resolve to the same CID.

⚠️ CID sharing has been observed.

| Other Client                                                                                                          | Application | Total Deals Affected | Unique CIDs |        Verifier |
| :-------------------------------------------------------------------------------------------------------------------- | :---------- | -------------------: | ----------: | --------------: |
| [f1vajbbihmcqkcjlnicmjto6fflklvhoifips7uzq](https://filfox.info/en/address/f1vajbbihmcqkcjlnicmjto6fflklvhoifips7uzq) | `rctAI`     |             8.19 TiB |          40 | LDN v3 multisig |

[^1]: To manually trigger this report, add a comment with text `checker:manualTrigger`

**Comment by mikala-01** [comment]
checker: manualTrigger

**Comment by Irmagogo** [comment]
checker:manualTrigger

**Comment by Irmagogo** [comment]
‘checker:manualTrigger’

**Comment by Irmagogo** [comment]
checker:manualTrigger

**Comment by Irmagogo** [comment]
checker:manualTrigger

**Comment by filplus-checker** [comment]
## DataCap and CID Checker Report[^1]
 - Organization: `Mikaelafashion`
 - Client: `f1jkf2e4ljhym3yaxdlq5cvqctpfsvecrklnsubjy`
### Approvers
`1`Defil2022<br/>`1`Tom-OriginStorage

### Storage Provider Distribution
The below table shows the distribution of storage providers that have stored data for this client.

If this is the first time a provider takes verified deal, it will be marked as `new`.

For most of the datacap application, below restrictions should apply.
 - Storage provider should not exceed 25% of total datacap.
 - Storage provider should not be storing duplicate data for more than 20%.
 - Storage provider should have published its public IP address.
 - All storage providers should be located in different regions.

⚠️ 79.37% of total deal sealed by [f01740934](https://filfox.info/en/address/f01740934) are duplicate data.

⚠️ [f01985611](https://filfox.info/en/address/f01985611) has unknown IP location.

| Provider                                              |                                       Location | Total Deals Sealed | Percentage | Unique Data | Duplicate Deals |
| :---------------------------------------------------- | ---------------------------------------------: | -----------------: | ---------: | ----------: | --------------: |
| [f01853104](https://filfox.info/en/address/f01853104) | Los Angeles, California, US<br/>`Zenlayer Inc` |           9.16 TiB |     18.39% |    9.16 TiB |           0.00% |
| [f01890456](https://filfox.info/en/address/f01890456) | Los Angeles, California, US<br/>`Zenlayer Inc` |           9.09 TiB |     18.27% |    9.09 TiB |           0.00% |
| [f01854080](https://filfox.info/en/address/f01854080) | Los Angeles, California, US<br/>`Zenlayer Inc` |           8.94 TiB |     17.95% |    8.94 TiB |           0.00% |
| [f01740934](https://filfox.info/en/address/f01740934) | Los Angeles, California, US<br/>`Zenlayer Inc` |           7.88 TiB |     15.82% |    1.63 TiB |          79.37% |
| [f01834253](https://filfox.info/en/address/f01834253) | Los Angeles, California, US<br/>`Zenlayer Inc` |           7.84 TiB |     15.76% |    7.84 TiB |           0.00% |
| [f01985611](https://filfox.info/en/address/f01985611) |                          Unknown<br/>`Unknown` |           6.88 TiB |     13.81% |    6.88 TiB |           0.00% |

![Provider Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/1027/1672297942140.png)
### Deal Data Replication
The below table shows how each many unique data are replicated across storage providers.
- No more than 25% of unique data are stored with less than 4 providers.

⚠️ 100.00% of deals are for data replicated across less than 4 storage providers.

| Unique Data Size | Total Deals Made | Number of Providers | Deal Percentage |
| ---------------: | ---------------: | ------------------: | --------------: |
|        12.63 TiB |        18.88 TiB |                   1 |          37.92% |
|         1.63 TiB |         3.25 TiB |                   2 |           6.53% |
|         9.22 TiB |        27.66 TiB |                   3 |          55.56% |

![Replication Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/1027/1672297943871.png)
### Deal Data Shared with other Clients
The below table shows how many unique data are shared with other clients.
Usually different applications owns different data and should not resolve to the same CID.

However, this could be possible if all below clients use same software to prepare for the exact same dataset or they belong to a series of LDN applications for the same dataset.

⚠️ CID sharing has been observed.

| Other Client                                                                                                          | Application                                                                                                          | Total Deals Affected | Unique CIDs | Approvers                                                                                                                                                                                     |
| :-------------------------------------------------------------------------------------------------------------------- | :------------------------------------------------------------------------------------------------------------------- | -------------------: | ----------: | :-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| [f1ji2xty4dtg2a4pfnslltkw7pbhy76kvihizkfmq](https://filfox.info/en/address/f1ji2xty4dtg2a4pfnslltkw7pbhy76kvihizkfmq) | `Pow Power`                                                                                                          |            55.75 TiB |         215 | Unknown                                                                                                                                                                                       |
| [f1gmiepn73zoa5gz2oiqyugjmrsecwj5qxd42vmyi](https://filfox.info/en/address/f1gmiepn73zoa5gz2oiqyugjmrsecwj5qxd42vmyi) | ``                                                                                                                   |            39.13 TiB |         139 | Unknown                                                                                                                                                                                       |
| [f1vajbbihmcqkcjlnicmjto6fflklvhoifips7uzq](https://filfox.info/en/address/f1vajbbihmcqkcjlnicmjto6fflklvhoifips7uzq) | `rctAI`                                                                                                              |            19.78 TiB |         167 | Unknown                                                                                                                                                                                       |
| [f1ng6g57r4u62q67u6lm33ftijfsggyzzjzb2l4cy](https://filfox.info/en/address/f1ng6g57r4u62q67u6lm33ftijfsggyzzjzb2l4cy) | [NFTSTAR](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/960)                               |            14.06 TiB |          73 | `1`1ane-1<br/>`1`Defil2022<br/>`2`newwebgroup<br/>`1`psh0691<br/>`1`stcouldlisa<br/>`2`Tom-OriginStorage                                                                                      |
| [f1qntyafmuq5h3moldezdkpgiiycbilrsvgfvyzti](https://filfox.info/en/address/f1qntyafmuq5h3moldezdkpgiiycbilrsvgfvyzti) | [Zhonghe Mineral Processing Technology](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/371) |            10.09 TiB |          39 | `1`1ane-1<br/>`1`Defil2022<br/>`2`fireflyHZ<br/>`2`liyunzhi-666<br/>`1`NDLABS-OFFICE<br/>`1`newwebgroup<br/>`1`psh0691<br/>`1`stcouldlisa<br/>`1`szalongdzyxgs<br/>`2`Tom-OriginStorage       |
| [f1dob4zdjy6b3iinf6evbqzxf6nwgnftcksewabxq](https://filfox.info/en/address/f1dob4zdjy6b3iinf6evbqzxf6nwgnftcksewabxq) | [Dr\.ji](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/793)                                |            10.06 TiB |         175 | `1`newwebgroup<br/>`1`psh0691<br/>`1`stcouldlisa<br/>`1`YuanHeHK                                                                                                                              |
| [f1o2nxreefzqzc2mvaqneaolpdat5yk3275r6rofa](https://filfox.info/en/address/f1o2nxreefzqzc2mvaqneaolpdat5yk3275r6rofa) | [iPolloverse SG PTE\. LTD](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/767)              |             9.84 TiB |          44 | `1`1ane-1<br/>`2`Defil2022<br/>`1`fireflyHZ<br/>`1`ipfscn<br/>`1`kernelogic<br/>`1`liyunzhi-666<br/>`1`newwebgroup<br/>`2`psh0691<br/>`4`stcouldlisa<br/>`5`Tom-OriginStorage<br/>`1`YuanHeHK |
| [f1y7xmlneep3qtxcumqlmqrja3fhqdxdaxwou6mdq](https://filfox.info/en/address/f1y7xmlneep3qtxcumqlmqrja3fhqdxdaxwou6mdq) | [ND LABS](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/109)                               |             6.91 TiB |          44 | `1`cryptowhizzard<br/>`1`Fenbushi-Filecoin<br/>`1`IreneYoung<br/>`1`MegTei<br/>`1`psh0691<br/>`1`rayshitou<br/>`1`Reiers                                                                      |
| [f1u3rzf5re6nvnyjjixcmbk5tderq55vjhudmapny](https://filfox.info/en/address/f1u3rzf5re6nvnyjjixcmbk5tderq55vjhudmapny) | [ Nswap](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/882)                                |             5.97 TiB |          29 | `1`Defil2022<br/>`1`psh0691<br/>`1`Tom-OriginStorage<br/>`1`YuanHeHK                                                                                                                          |
| [f1guplg5wyjdn6bv4forsb5eu2lohexvdlttkavpq](https://filfox.info/en/address/f1guplg5wyjdn6bv4forsb5eu2lohexvdlttkavpq) | [Ipollo](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/168)                                |             4.97 TiB |          48 | `1`MegTei<br/>`1`rayshitou<br/>`1`Reiers<br/>`1`swatchliu                                                                                                                                     |
| [f1dfkdmjhuvvol6okun57mix447wdpolwcd323ktq](https://filfox.info/en/address/f1dfkdmjhuvvol6okun57mix447wdpolwcd323ktq) | [BITRISE CAPITAL FOUNDATION PTE\.LTD](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/139)   |             4.84 TiB |          42 | `1`dannyob<br/>`1`MegTei<br/>`1`rayshitou<br/>`1`swatchliu                                                                                                                                    |
| [f1sffbmjyfnz5jbsej23syerh6ubjcfmk4hd34zpi](https://filfox.info/en/address/f1sffbmjyfnz5jbsej23syerh6ubjcfmk4hd34zpi) | [Ganku Co\., Ltd\.](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1028)                    |             3.75 TiB |         119 | `1`Defil2022<br/>`1`Tom-OriginStorage                                                                                                                                                         |
| [f1mgvvj45ce5i3ikpyixtubqzcytcgmdlwgjldqri](https://filfox.info/en/address/f1mgvvj45ce5i3ikpyixtubqzcytcgmdlwgjldqri) | [Blockchain Media](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1048)                     |             3.66 TiB |         117 | `1`Defil2022<br/>`1`Joss-Hua<br/>`2`kernelogic<br/>`1`liyunzhi-666<br/>`1`NDLABS-OFFICE                                                                                                       |
| [f1df64fi3a4pmo5mxvdrz2zs7n2bfd4wnixomudcq](https://filfox.info/en/address/f1df64fi3a4pmo5mxvdrz2zs7n2bfd4wnixomudcq) | [UZERO](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/294)                                 |             3.06 TiB |          24 | `1`fireflyHZ<br/>`1`liyunzhi-666                                                                                                                                                              |
| [f1k7y7jd3ly42cg5ysty2ngc5smxmaery5mglbynq](https://filfox.info/en/address/f1k7y7jd3ly42cg5ysty2ngc5smxmaery5mglbynq) | `MikaeLa `                                                                                                           |             2.88 TiB |          27 | Unknown                                                                                                                                                                                       |
| [f13wvg4xve7nz3nev4bi2c7imod7lelstxfwwzjgi](https://filfox.info/en/address/f13wvg4xve7nz3nev4bi2c7imod7lelstxfwwzjgi) | [We Doctor](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/962)                             |             2.84 TiB |          90 | `1`Alex11801<br/>`1`Defil2022<br/>`3`kernelogic<br/>`1`liyunzhi-666<br/>`1`NDLABS-OFFICE<br/>`1`stcouldlisa                                                                                   |
| [f1raeideaex2fwvoemftky6x5jzbqdawrgeuz2mry](https://filfox.info/en/address/f1raeideaex2fwvoemftky6x5jzbqdawrgeuz2mry) | [BBNews](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/218)                                |             2.66 TiB |          23 | `1`KodaRobotDog<br/>`1`rayshitou                                                                                                                                                              |
| [f1e2emop3dpataocjw3jh4cfvqrqbp7albnip7wdq](https://filfox.info/en/address/f1e2emop3dpataocjw3jh4cfvqrqbp7albnip7wdq) | [Ganku Technology](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/219)                      |             2.59 TiB |          16 | `1`IreneYoung                                                                                                                                                                                 |
| [f1zxmwo3kwapc6axatwuia4lsowvpasco3znfbuvi](https://filfox.info/en/address/f1zxmwo3kwapc6axatwuia4lsowvpasco3znfbuvi) | Unknown                                                                                                              |             2.28 TiB |          24 | Unknown                                                                                                                                                                                       |
| [f1jlkknv6psnw4m3wxok25sy7ngzdfjjk6rucbfwy](https://filfox.info/en/address/f1jlkknv6psnw4m3wxok25sy7ngzdfjjk6rucbfwy) | [Nonabyte](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/279)                              |             1.94 TiB |          15 | `1`liyunzhi-666<br/>`1`newwebgroup                                                                                                                                                            |
| [f17d2n363326qlln4uva7ylxteamtdj3lq6wuaewi](https://filfox.info/en/address/f17d2n363326qlln4uva7ylxteamtdj3lq6wuaewi) | [Metadata Labs Inc](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/200)                     |             1.94 TiB |          25 | `1`Fenbushi-Filecoin<br/>`1`IreneYoung<br/>`1`rayshitou                                                                                                                                       |
| [f1pnsnrfp5dqfqwospzj6vis6jxhni765i37tne5q](https://filfox.info/en/address/f1pnsnrfp5dqfqwospzj6vis6jxhni765i37tne5q) | [TIMAGE](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/302)                                |             1.78 TiB |          22 | `1`fireflyHZ<br/>`1`PluskitOfficial                                                                                                                                                           |
| [f1nkh5as6inqcvcoiliumdmvai2luahw5imdqug5a](https://filfox.info/en/address/f1nkh5as6inqcvcoiliumdmvai2luahw5imdqug5a) | ``                                                                                                                   |             1.78 TiB |           9 | Unknown                                                                                                                                                                                       |
| [f1366c5an6uegsc7zhsy4csax3e5msrhie5gef7mi](https://filfox.info/en/address/f1366c5an6uegsc7zhsy4csax3e5msrhie5gef7mi) | [Jinchan Curtains Co\.,ltd](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/285)             |             1.75 TiB |          12 | `1`fireflyHZ<br/>`1`liyunzhi-666                                                                                                                                                              |
| [f16w5d2u57ndts6wcqupwwvrl7ewicrl5xnymfxui](https://filfox.info/en/address/f16w5d2u57ndts6wcqupwwvrl7ewicrl5xnymfxui) | `Maoyoo Network`                                                                                                     |             1.38 TiB |          12 | Unknown                                                                                                                                                                                       |
| [f1mhyxd4unemmhrw4dbhjcovivayrj3tyactezmzq](https://filfox.info/en/address/f1mhyxd4unemmhrw4dbhjcovivayrj3tyactezmzq) | `GOLDEN SECURITY`                                                                                                    |             1.34 TiB |           8 | Unknown                                                                                                                                                                                       |
| [f13fjnwckkgnkbpapcmnpupbdf4ohduomdso4eqga](https://filfox.info/en/address/f13fjnwckkgnkbpapcmnpupbdf4ohduomdso4eqga) | [Asia Blockchain Gaming Alliance](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/872)       |           800.00 GiB |          25 | `3`Defil2022<br/>`1`GaryGJG<br/>`2`newwebgroup<br/>`1`psh0691<br/>`2`stcouldlisa<br/>`1`Tom-OriginStorage                                                                                     |
| [f1ewwoms3aiairedun4h2uayqhlmtjsulnqy2xnrq](https://filfox.info/en/address/f1ewwoms3aiairedun4h2uayqhlmtjsulnqy2xnrq) | [AsiaBlockchain Gaming Alliance](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/179)        |           576.00 GiB |           4 | `1`dannyob<br/>`1`IreneYoung<br/>`1`MegTei<br/>`1`MRJAVAZHAO<br/>`1`rayshitou                                                                                                                 |
| [f1crhsa6czawwislz35lcwt3zke2cr2vy5rmdmt3y](https://filfox.info/en/address/f1crhsa6czawwislz35lcwt3zke2cr2vy5rmdmt3y) | ``                                                                                                                   |           576.00 GiB |           7 | Unknown                                                                                                                                                                                       |
| [f1hkvuvlwgzsgxnyet3wb4w2s3fyujvtkgeizdaey](https://filfox.info/en/address/f1hkvuvlwgzsgxnyet3wb4w2s3fyujvtkgeizdaey) | [Blue Storm Information Technology](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/323)     |           544.00 GiB |           5 | `1`1475Notary<br/>`1`Defil2022<br/>`1`liyunzhi-666<br/>`1`stcouldlisa<br/>`1`swatchliu<br/>`1`Tom-OriginStorage<br/>`1`YuanHeHK                                                               |
| [f14kei3mbjobgsfszu5cndhosuobkbbtoaikc52pq](https://filfox.info/en/address/f14kei3mbjobgsfszu5cndhosuobkbbtoaikc52pq) | [Proya](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/295)                                 |           448.00 GiB |           5 |                                                                                                                                                                                               |
| [f1fn4y2mtu7ooeuqxzczxeienm6zbnsgpf6b5ng2a](https://filfox.info/en/address/f1fn4y2mtu7ooeuqxzczxeienm6zbnsgpf6b5ng2a) | [Wel Vape](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/140)                              |           128.00 GiB |           1 | `1`fireflyHZ                                                                                                                                                                                  |
| [f1fttsmb4vjost7zod5gf4eqpd6qpzylx3i4d6s3i](https://filfox.info/en/address/f1fttsmb4vjost7zod5gf4eqpd6qpzylx3i4d6s3i) | [奕甲智能技术（上海）有限公司](https://github.com/filecoin-project/filecoin-plus-client-onboarding/issues/1961)                    |            96.00 GiB |           3 |                                                                                                                                                                                               |

[^1]: To manually trigger this report, add a comment with text `checker:manualTrigger`

**Comment by Sunnyiscoming** [comment]
No more than 25% of unique data are stored with less than 4 providers.
Can you explain about that?
