### ISSUE TITLE
[DataCap Application] Ganku Co., Ltd.

### ISSUE THREAD

**Issue by Ganku112211** [filecoin-project/filecoin-plus-large-datasets#1028]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Ganku Co., Ltd.
- Website / Social Media: https://www.ganku.net/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5 PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100TiB
- On-chain address for first allocation: f1sffbmjyfnz5jbsej23syerh6ubjcfmk4hd34zpi

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Founded in 2015, Ganku Technology has set up team in Beijing and Chengdu. We are committed to becoimg a comprehensive information security solutions provider. We provide blockchain security related business support, security analysis based on big data and other businesses. At present, we are mainly engaged in two business sectors:
1. Big data-based on-chain behavior tracking and analysis, user portrait, address marking, etc.
2. Data + AI-driven security, extract and analyze massive logs and on-chain information, summarize specific data samples and conduct machine learning training.
```

What is the primary source of funding for this project?
```
There are two main sources of funding for us:
1. Money invested by early adopters.
2. Business income of project business line
```

What other projects/ecosystem stakeholders is this project associated with?
```
Our current business line is closely related to on-chain data, and our customers also come from the blockchain industry. 
1. Regarding the server supply chain, we mainly purchase aliyun servers. 
2. As for the application party of distributed storage track, we currently have cooperation with NFT to help them review the contract code. As for the storage of metadata, we will suggest them to use decentralized services. Some customers require us to provide relevant solutions. These customers have storage requirements of NFT for music, video and pictures. 
3. As for our customers using secure data service, some on-chain data needs to be stored after processing. 

```

## Use-case details

Describe the data being stored onto Filecoin
```
The data stored on Filecoin currently consists mostly of application data and publicly available data stored by customers. 
Some of the client's project data will be used for metadata storage of images such as NFT. 
The project stores project data and training related to security AI training, including attack log raw data and processed vector data. 
```

Where was the data in this dataset sourced from?
```
Mainly from customers and application data on projects
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://github.com/vicious11/ML-for-SQL-Injection/blob/master/ML_for_SQL/data/sql_matrix.csv#/
https://pan.baidu.com/s/14nbEwY2h68Z7GqThcX6efw?pwd=1A4S
https://pan.baidu.com/s/1_paSZX6pkH4sTNw_im1khQ?pwd=1A4S 
https://pan.baidu.com/s/1RAI1fE6lakPAWOmJqjPU2w?pwd=1A4S 
Extraction code:1A4S 
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes, this is a public dataset that can be retrieved by anyone on the Network.
```

What is the expected retrieval frequency for this data?
```
There is no fixed frequency for data retrieval, it depends on the need
```

For how long do you plan to keep this dataset stored on Filecoin?
```
It also depends on the need.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
USA, Singapore
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
We support both online and offline modes.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
Our plan is to find miners who have performed well in the past to help us provide stable storage.
```

How will you be distributing deals across storage providers?
```
Proportion based on miners' repuation.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
We have enough funds to start trading.
```

**Comment by Sunnyiscoming** [comment]
https://www.ganku.net/ Website are unavailable. Please check it.
The data samples you provided are almost from chabug.org. What's the relationship between Ganku and chabug.org? Have you authorized to store the data on the Filecoin network?
Can you explain your data composition? How many copies will you store?
What's the relationship between you and the organization?
Can you provide more detailed information about other storage providers participated in this program, such as you can list SPs you have contacted with at present?

**Comment by Ganku112211** [comment]
Hello, @Sunnyiscoming Thank you very much for your feedback
1. The problem that the website is unavailable may be a network problem. Please try again. Our display is normal.
2. The data samples we provide are security-related teaching videos, and the data we will store mainly includes the following categories. Video (10%), database files (35%), security log attack files (50%), other information documents (5%)
3. We will determine the number of backups based on different data. For example, we will save 2-3 copies of logs that are more important to us. Other data may be prepared according to the number of backups of 1-2 copies.
4. I am the technical director of ganku, and I have sent KYB emails before, please confirm.
5. We have come into contact with some well-known sps in the industry, for example: f01893023/f01890456/f01773206/f01880364/f01853077

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 100TiB

**Client address**

> f1sffbmjyfnz5jbsej23syerh6ubjcfmk4hd34zpi

**Comment by Defil2022** [comment]
sample data looks good. website is fine. 
one concern is does your data can be stored in USA or other country?

**Comment by Tom-OriginStorage** [comment]
你能发邮件到[filplus-app-review@fil.org]

**Comment by Ganku112211** [comment]
Hi, @Defil2022 @Tom-OriginStorage
 Yes, we have considered this issue and are planning it. I have sent KYC email, please check it!
thanks！
![b01f337776600c221d4989a867150b7](https://user-images.githubusercontent.com/111570952/205239419-9d8b1cf3-ffd7-4465-8533-6177a13c2b9a.jpg)

**Comment by Tom-OriginStorage** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacea3j6k67xuvoewks6vu5a4cd5w65u6b6pgazbt25lyljts6mp3vte 
#### Address 
> f1sffbmjyfnz5jbsej23syerh6ubjcfmk4hd34zpi
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1q6bpjlqia6iemqbrdaxr2uehrhpvoju3qh4lpga
#### Id
> 76e298aa-a20f-4233-b6b7-d12349fb36e3
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacea3j6k67xuvoewks6vu5a4cd5w65u6b6pgazbt25lyljts6mp3vte

**Comment by Defil2022** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecxoareuot4vin2pyva5xfunwhvogwer4gl4xux44tz47bkqzhnra 
#### Address 
> f1sffbmjyfnz5jbsej23syerh6ubjcfmk4hd34zpi
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1dnb3uz7sylxk6emti3ififcvu3nlufnnsjui6ea
#### Id
> 76e298aa-a20f-4233-b6b7-d12349fb36e3
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecxoareuot4vin2pyva5xfunwhvogwer4gl4xux44tz47bkqzhnra

**Comment by Ganku112211** [comment]
checker: manualTrigger

**Comment by Ganku112211** [comment]
checker: manualTrigger

**Comment by YuanHeHK** [comment]
checker:manualTrigger

**Comment by Irmagogo** [comment]
checker:manualTrigger

**Comment by filplus-checker** [comment]
## DataCap and CID Checker Report[^1]
 - Organization: `Ganku Co., Ltd.`
 - Client: `f1sffbmjyfnz5jbsej23syerh6ubjcfmk4hd34zpi`
### Approvers
`1`Defil2022<br/>`1`Tom-OriginStorage

### Storage Provider Distribution
The below table shows the distribution of storage providers that have stored data for this client.

If this is the first time a provider takes verified deal, it will be marked as `new`.

For most of the datacap application, below restrictions should apply.
 - Storage provider should not exceed 25% of total datacap.
 - Storage provider should not be storing duplicate data for more than 20%.
 - Storage provider should have published its public IP address.
 - All storage providers should be located in different regions.

⚠️ [f01985611](https://filfox.info/en/address/f01985611) has unknown IP location.

⚠️ 43.56% of total deal sealed by [f01834291](https://filfox.info/en/address/f01834291) are duplicate data.

| Provider                                              |                                       Location | Total Deals Sealed | Percentage | Unique Data | Duplicate Deals |
| :---------------------------------------------------- | ---------------------------------------------: | -----------------: | ---------: | ----------: | --------------: |
| [f01854080](https://filfox.info/en/address/f01854080) | Los Angeles, California, US<br/>`Zenlayer Inc` |           8.44 TiB |     18.33% |    8.44 TiB |           0.00% |
| [f01853104](https://filfox.info/en/address/f01853104) | Los Angeles, California, US<br/>`Zenlayer Inc` |           8.25 TiB |     17.92% |    8.25 TiB |           0.00% |
| [f01985611](https://filfox.info/en/address/f01985611) |                          Unknown<br/>`Unknown` |           8.22 TiB |     17.85% |    8.22 TiB |           0.00% |
| [f01890456](https://filfox.info/en/address/f01890456) | Los Angeles, California, US<br/>`Zenlayer Inc` |           8.13 TiB |     17.65% |    8.13 TiB |           0.00% |
| [f01834253](https://filfox.info/en/address/f01834253) | Los Angeles, California, US<br/>`Zenlayer Inc` |           6.69 TiB |     14.53% |    6.69 TiB |           0.00% |
| [f01834291](https://filfox.info/en/address/f01834291) | Los Angeles, California, US<br/>`Zenlayer Inc` |           6.31 TiB |     13.71% |    3.56 TiB |          43.56% |

![Provider Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/1028/1672298188843.png)
### Deal Data Replication
The below table shows how each many unique data are replicated across storage providers.
- No more than 25% of unique data are stored with less than 4 providers.

⚠️ 100.00% of deals are for data replicated across less than 4 storage providers.

| Unique Data Size | Total Deals Made | Number of Providers | Deal Percentage |
| ---------------: | ---------------: | ------------------: | --------------: |
|        42.78 TiB |        45.53 TiB |                   1 |          98.91% |
|       160.00 GiB |       320.00 GiB |                   2 |           0.68% |
|        64.00 GiB |       192.00 GiB |                   3 |           0.41% |

![Replication Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/1028/1672298190361.png)
### Deal Data Shared with other Clients
The below table shows how many unique data are shared with other clients.
Usually different applications owns different data and should not resolve to the same CID.

However, this could be possible if all below clients use same software to prepare for the exact same dataset or they belong to a series of LDN applications for the same dataset.

⚠️ CID sharing has been observed.

| Other Client                                                                                                          | Application                                                                                                          | Total Deals Affected | Unique CIDs | Approvers                                                                                                                                                                                     |
| :-------------------------------------------------------------------------------------------------------------------- | :------------------------------------------------------------------------------------------------------------------- | -------------------: | ----------: | :-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| [f1ji2xty4dtg2a4pfnslltkw7pbhy76kvihizkfmq](https://filfox.info/en/address/f1ji2xty4dtg2a4pfnslltkw7pbhy76kvihizkfmq) | `Pow Power`                                                                                                          |           143.59 TiB |         552 | Unknown                                                                                                                                                                                       |
| [f1gmiepn73zoa5gz2oiqyugjmrsecwj5qxd42vmyi](https://filfox.info/en/address/f1gmiepn73zoa5gz2oiqyugjmrsecwj5qxd42vmyi) | ``                                                                                                                   |            82.72 TiB |         295 | Unknown                                                                                                                                                                                       |
| [f1qntyafmuq5h3moldezdkpgiiycbilrsvgfvyzti](https://filfox.info/en/address/f1qntyafmuq5h3moldezdkpgiiycbilrsvgfvyzti) | [Zhonghe Mineral Processing Technology](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/371) |            28.72 TiB |         102 | `1`1ane-1<br/>`1`Defil2022<br/>`2`fireflyHZ<br/>`2`liyunzhi-666<br/>`1`NDLABS-OFFICE<br/>`1`newwebgroup<br/>`1`psh0691<br/>`1`stcouldlisa<br/>`1`szalongdzyxgs<br/>`2`Tom-OriginStorage       |
| [f1ng6g57r4u62q67u6lm33ftijfsggyzzjzb2l4cy](https://filfox.info/en/address/f1ng6g57r4u62q67u6lm33ftijfsggyzzjzb2l4cy) | [NFTSTAR](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/960)                               |            27.56 TiB |         165 | `1`1ane-1<br/>`1`Defil2022<br/>`2`newwebgroup<br/>`1`psh0691<br/>`1`stcouldlisa<br/>`2`Tom-OriginStorage                                                                                      |
| [f1o2nxreefzqzc2mvaqneaolpdat5yk3275r6rofa](https://filfox.info/en/address/f1o2nxreefzqzc2mvaqneaolpdat5yk3275r6rofa) | [iPolloverse SG PTE\. LTD](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/767)              |            21.53 TiB |          98 | `1`1ane-1<br/>`2`Defil2022<br/>`1`fireflyHZ<br/>`1`ipfscn<br/>`1`kernelogic<br/>`1`liyunzhi-666<br/>`1`newwebgroup<br/>`2`psh0691<br/>`4`stcouldlisa<br/>`5`Tom-OriginStorage<br/>`1`YuanHeHK |
| [f1y7xmlneep3qtxcumqlmqrja3fhqdxdaxwou6mdq](https://filfox.info/en/address/f1y7xmlneep3qtxcumqlmqrja3fhqdxdaxwou6mdq) | [ND LABS](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/109)                               |            20.78 TiB |         135 | `1`cryptowhizzard<br/>`1`Fenbushi-Filecoin<br/>`1`IreneYoung<br/>`1`MegTei<br/>`1`psh0691<br/>`1`rayshitou<br/>`1`Reiers                                                                      |
| [f1vajbbihmcqkcjlnicmjto6fflklvhoifips7uzq](https://filfox.info/en/address/f1vajbbihmcqkcjlnicmjto6fflklvhoifips7uzq) | `rctAI`                                                                                                              |            19.94 TiB |         185 | Unknown                                                                                                                                                                                       |
| [f1u3rzf5re6nvnyjjixcmbk5tderq55vjhudmapny](https://filfox.info/en/address/f1u3rzf5re6nvnyjjixcmbk5tderq55vjhudmapny) | [ Nswap](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/882)                                |            18.09 TiB |          74 | `1`Defil2022<br/>`1`psh0691<br/>`1`Tom-OriginStorage<br/>`1`YuanHeHK                                                                                                                          |
| [f1guplg5wyjdn6bv4forsb5eu2lohexvdlttkavpq](https://filfox.info/en/address/f1guplg5wyjdn6bv4forsb5eu2lohexvdlttkavpq) | [Ipollo](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/168)                                |            14.72 TiB |         113 | `1`MegTei<br/>`1`rayshitou<br/>`1`Reiers<br/>`1`swatchliu                                                                                                                                     |
| [f13fjnwckkgnkbpapcmnpupbdf4ohduomdso4eqga](https://filfox.info/en/address/f13fjnwckkgnkbpapcmnpupbdf4ohduomdso4eqga) | [Asia Blockchain Gaming Alliance](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/872)       |             8.44 TiB |          85 | `3`Defil2022<br/>`1`GaryGJG<br/>`2`newwebgroup<br/>`1`psh0691<br/>`2`stcouldlisa<br/>`1`Tom-OriginStorage                                                                                     |
| [f1dfkdmjhuvvol6okun57mix447wdpolwcd323ktq](https://filfox.info/en/address/f1dfkdmjhuvvol6okun57mix447wdpolwcd323ktq) | [BITRISE CAPITAL FOUNDATION PTE\.LTD](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/139)   |             8.34 TiB |          69 | `1`dannyob<br/>`1`MegTei<br/>`1`rayshitou<br/>`1`swatchliu                                                                                                                                    |
| [f1jkf2e4ljhym3yaxdlq5cvqctpfsvecrklnsubjy](https://filfox.info/en/address/f1jkf2e4ljhym3yaxdlq5cvqctpfsvecrklnsubjy) | [Mikaelafashion](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1027)                       |             8.09 TiB |         119 | `1`Defil2022<br/>`1`Tom-OriginStorage                                                                                                                                                         |
| [f1k7y7jd3ly42cg5ysty2ngc5smxmaery5mglbynq](https://filfox.info/en/address/f1k7y7jd3ly42cg5ysty2ngc5smxmaery5mglbynq) | `MikaeLa `                                                                                                           |             6.50 TiB |          75 | Unknown                                                                                                                                                                                       |
| [f1df64fi3a4pmo5mxvdrz2zs7n2bfd4wnixomudcq](https://filfox.info/en/address/f1df64fi3a4pmo5mxvdrz2zs7n2bfd4wnixomudcq) | [UZERO](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/294)                                 |             6.19 TiB |          58 | `1`fireflyHZ<br/>`1`liyunzhi-666                                                                                                                                                              |
| [f17d2n363326qlln4uva7ylxteamtdj3lq6wuaewi](https://filfox.info/en/address/f17d2n363326qlln4uva7ylxteamtdj3lq6wuaewi) | [Metadata Labs Inc](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/200)                     |             5.59 TiB |          55 | `1`Fenbushi-Filecoin<br/>`1`IreneYoung<br/>`1`rayshitou                                                                                                                                       |
| [f1raeideaex2fwvoemftky6x5jzbqdawrgeuz2mry](https://filfox.info/en/address/f1raeideaex2fwvoemftky6x5jzbqdawrgeuz2mry) | [BBNews](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/218)                                |             5.03 TiB |          40 | `1`KodaRobotDog<br/>`1`rayshitou                                                                                                                                                              |
| [f1zxmwo3kwapc6axatwuia4lsowvpasco3znfbuvi](https://filfox.info/en/address/f1zxmwo3kwapc6axatwuia4lsowvpasco3znfbuvi) | Unknown                                                                                                              |             4.78 TiB |          48 | Unknown                                                                                                                                                                                       |
| [f1e2emop3dpataocjw3jh4cfvqrqbp7albnip7wdq](https://filfox.info/en/address/f1e2emop3dpataocjw3jh4cfvqrqbp7albnip7wdq) | [Ganku Technology](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/219)                      |             4.41 TiB |          29 | `1`IreneYoung                                                                                                                                                                                 |
| [f1366c5an6uegsc7zhsy4csax3e5msrhie5gef7mi](https://filfox.info/en/address/f1366c5an6uegsc7zhsy4csax3e5msrhie5gef7mi) | [Jinchan Curtains Co\.,ltd](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/285)             |             4.16 TiB |          27 | `1`fireflyHZ<br/>`1`liyunzhi-666                                                                                                                                                              |
| [f1pnsnrfp5dqfqwospzj6vis6jxhni765i37tne5q](https://filfox.info/en/address/f1pnsnrfp5dqfqwospzj6vis6jxhni765i37tne5q) | [TIMAGE](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/302)                                |             4.16 TiB |          45 | `1`fireflyHZ<br/>`1`PluskitOfficial                                                                                                                                                           |
| [f1nkh5as6inqcvcoiliumdmvai2luahw5imdqug5a](https://filfox.info/en/address/f1nkh5as6inqcvcoiliumdmvai2luahw5imdqug5a) | ``                                                                                                                   |             3.25 TiB |          16 | Unknown                                                                                                                                                                                       |
| [f1jlkknv6psnw4m3wxok25sy7ngzdfjjk6rucbfwy](https://filfox.info/en/address/f1jlkknv6psnw4m3wxok25sy7ngzdfjjk6rucbfwy) | [Nonabyte](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/279)                              |             2.88 TiB |          22 | `1`liyunzhi-666<br/>`1`newwebgroup                                                                                                                                                            |
| [f1mhyxd4unemmhrw4dbhjcovivayrj3tyactezmzq](https://filfox.info/en/address/f1mhyxd4unemmhrw4dbhjcovivayrj3tyactezmzq) | `GOLDEN SECURITY`                                                                                                    |             2.31 TiB |          12 | Unknown                                                                                                                                                                                       |
| [f1hkvuvlwgzsgxnyet3wb4w2s3fyujvtkgeizdaey](https://filfox.info/en/address/f1hkvuvlwgzsgxnyet3wb4w2s3fyujvtkgeizdaey) | [Blue Storm Information Technology](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/323)     |             2.22 TiB |          16 | `1`1475Notary<br/>`1`Defil2022<br/>`1`liyunzhi-666<br/>`1`stcouldlisa<br/>`1`swatchliu<br/>`1`Tom-OriginStorage<br/>`1`YuanHeHK                                                               |
| [f16w5d2u57ndts6wcqupwwvrl7ewicrl5xnymfxui](https://filfox.info/en/address/f16w5d2u57ndts6wcqupwwvrl7ewicrl5xnymfxui) | `Maoyoo Network`                                                                                                     |             1.91 TiB |          16 | Unknown                                                                                                                                                                                       |
| [f13wvg4xve7nz3nev4bi2c7imod7lelstxfwwzjgi](https://filfox.info/en/address/f13wvg4xve7nz3nev4bi2c7imod7lelstxfwwzjgi) | [We Doctor](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/962)                             |             1.38 TiB |          42 | `1`Alex11801<br/>`1`Defil2022<br/>`3`kernelogic<br/>`1`liyunzhi-666<br/>`1`NDLABS-OFFICE<br/>`1`stcouldlisa                                                                                   |
| [f1ewwoms3aiairedun4h2uayqhlmtjsulnqy2xnrq](https://filfox.info/en/address/f1ewwoms3aiairedun4h2uayqhlmtjsulnqy2xnrq) | [AsiaBlockchain Gaming Alliance](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/179)        |           544.00 GiB |           7 | `1`dannyob<br/>`1`IreneYoung<br/>`1`MegTei<br/>`1`MRJAVAZHAO<br/>`1`rayshitou                                                                                                                 |
| [f14kei3mbjobgsfszu5cndhosuobkbbtoaikc52pq](https://filfox.info/en/address/f14kei3mbjobgsfszu5cndhosuobkbbtoaikc52pq) | [Proya](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/295)                                 |           480.00 GiB |           8 |                                                                                                                                                                                               |
| [f1fn4y2mtu7ooeuqxzczxeienm6zbnsgpf6b5ng2a](https://filfox.info/en/address/f1fn4y2mtu7ooeuqxzczxeienm6zbnsgpf6b5ng2a) | [Wel Vape](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/140)                              |           384.00 GiB |           3 | `1`fireflyHZ                                                                                                                                                                                  |
| [f1fttsmb4vjost7zod5gf4eqpd6qpzylx3i4d6s3i](https://filfox.info/en/address/f1fttsmb4vjost7zod5gf4eqpd6qpzylx3i4d6s3i) | [奕甲智能技术（上海）有限公司](https://github.com/filecoin-project/filecoin-plus-client-onboarding/issues/1961)                    |           352.00 GiB |          11 |                                                                                                                                                                                               |
| [f1crhsa6czawwislz35lcwt3zke2cr2vy5rmdmt3y](https://filfox.info/en/address/f1crhsa6czawwislz35lcwt3zke2cr2vy5rmdmt3y) | ``                                                                                                                   |           320.00 GiB |           3 | Unknown                                                                                                                                                                                       |
| [f1dob4zdjy6b3iinf6evbqzxf6nwgnftcksewabxq](https://filfox.info/en/address/f1dob4zdjy6b3iinf6evbqzxf6nwgnftcksewabxq) | [Dr\.ji](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/793)                                |           288.00 GiB |           9 | `1`newwebgroup<br/>`1`psh0691<br/>`1`stcouldlisa<br/>`1`YuanHeHK                                                                                                                              |
| [f1mgvvj45ce5i3ikpyixtubqzcytcgmdlwgjldqri](https://filfox.info/en/address/f1mgvvj45ce5i3ikpyixtubqzcytcgmdlwgjldqri) | [Blockchain Media](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1048)                     |           160.00 GiB |           2 | `1`Defil2022<br/>`1`Joss-Hua<br/>`2`kernelogic<br/>`1`liyunzhi-666<br/>`1`NDLABS-OFFICE                                                                                                       |
| [f1fsoyq7oiwdaapagpnlncbohkrkzolxxzkex6hxq](https://filfox.info/en/address/f1fsoyq7oiwdaapagpnlncbohkrkzolxxzkex6hxq) | [SemiDrive Technology](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/911)                  |           128.00 GiB |           4 | `1`Alex11801<br/>`1`Defil2022<br/>`1`kernelogic<br/>`2`liyunzhi-666<br/>`1`NDLABS-OFFICE                                                                                                      |

[^1]: To manually trigger this report, add a comment with text `checker:manualTrigger`

**Comment by Sunnyiscoming** [comment]
Hi, please explain the abnormal information.
