### ISSUE TITLE
[DataCap Application] Fujian Zetong Construction Co., Ltd.

### ISSUE THREAD

**Issue by fujianZT** [filecoin-project/filecoin-plus-large-datasets#1031]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Fujian Zetong Construction Co., Ltd.
- Website / Social Media: www.whdfjzt.cn
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 500TiB
- On-chain address for first allocation: f1jobq5dqi4i5gnilqzwzdpngbkgeyvcrig7zs3zy

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Fujian Zetong Construction Co., Ltd., established in 2018, is a new type of construction engineering company with data-driven production. The company's main business includes engineering construction and engineering survey and so on. In order to realize the construction of informatization, our company specially set up the information technology department to realize technological change for our company's business by using big data means.
```

What is the primary source of funding for this project?
```
The project will be funded by our company.
```

What other projects/ecosystem stakeholders is this project associated with?
```
None.
```

## Use-case details

Describe the data being stored onto Filecoin
```
We have built a big data analysis system to collect the big data information of the construction engineering industry at home and abroad. Through the analysis and calculation of these data, we serve our engineering construction, engineering survey, architectural design and other businesses.
1. Engineering construction: By analyzing and comparing engineering construction links around the world, optimize the construction process, help save construction costs, and improve engineering safety.
2. Engineering survey: Based on in-depth modeling in the field of survey, realize the process and productization of survey, and improve business competitiveness

We also have a large amount of architectural model data, including downloaded material data and our open source production data.
like Building scene layer data, Georeferencing BIM data, buildings layer data.
We hope to save the collected and our own data on filecoin to help the whole construction industry to improve big data intelligence
```

Where was the data in this dataset sourced from?
```
The information technology department of the company collects the public data of the construction industry at home and abroad through the technical crawler, as well as the open data generated in the process of project analysis and calculation of our own company.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
Here is some of our design model data：
https://zetongfj.oss-cn-fuzhou.aliyuncs.com/Apartment_Building_17_3ds.zip
https://zetongfj.oss-cn-fuzhou.aliyuncs.com/Apartment_Building_6_max_vray.zip
https://zetongfj.oss-cn-fuzhou.aliyuncs.com/Architecture-Colorization.zip
https://zetongfj.oss-cn-fuzhou.aliyuncs.com/Free_Old_BuildingFBX.zip
https://zetongfj.oss-cn-fuzhou.aliyuncs.com/House_01_3Ds.zip
https://zetongfj.oss-cn-fuzhou.aliyuncs.com/Textures.rar
https://zetongfj.oss-cn-fuzhou.aliyuncs.com/Tier2.rar
https://zetongfj.oss-cn-fuzhou.aliyuncs.com/apartment_8.stl
https://zetongfj.oss-cn-fuzhou.aliyuncs.com/skyscraper-polovinko-4CAD.rar
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes, it can be accessed without any identification.
```

What is the expected retrieval frequency for this data?
```
I hope it can reach 15 times per year
```

For how long do you plan to keep this dataset stored on Filecoin?
```
We plan to store permanently on the filecoin chain.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Republic of North American, Asia
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Both online and offline transmissions are possible. If the SP requests offline transmission, we can also send by disks.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
Well, We will look for SPs through slack and through the FIL community,  we want to choose a SP with good size and credit in filecon's ecosystem.
```

How will you be distributing deals across storage providers?
```
We will follow the rules for large-datasets. And we will ensure fair distribution through limiting the amount of deals send to each miner, under 25% to per sp. These records will be made and published regularly on Github.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Sure.
```

**Comment by Sunnyiscoming** [comment]
Can you explain your data composition? How many copies will you store?
What's the relationship between you and the organization?
Can you provide more detailed information about other storage providers participated in this program, such as you can list SPs you have contacted with at present?

**Comment by fujianZT** [comment]
Hi @Sunnyiscoming  
1. The data includes the following parts: downloaded public building 3D modeling files and pictures, the 3D public building model files we generated (can be made public), public monitoring data and videos during project construction, etc.
2. We will store 10 copies
3. I am a technical staff of the company, applying for this LDN is the company action, and I will operate it
4. Here are the SPs we are currently in contact with：f03223 f0143858 f01193812 f01412203 f01699999

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 500TiB

**Client address**

> f1jobq5dqi4i5gnilqzwzdpngbkgeyvcrig7zs3zy

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Looking at your application i have some questions:
As you are brand new on Github and have no history of past applications it seems to me that applying for 5PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?

Can you show us visible proof of the size of your data and the storage systems you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230232885049356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!

**Comment by Sunnyiscoming** [comment]
Hey @fujianZT , if you still want to apply for datacap, you can ask notaries to do client due diligence in slack channel. https://app.slack.com/client/TEHTVS1L6/C036JKD8NVA/thread/C03BG1MNQ4T-1673888660.823499

**Comment by fujianZT** [comment]
> 
Sorry for the late reply.
We have a technical team, they have been researching filecoin for a long time, I believe they can handle technical issues such as packing of data, distribution of data, etc.
This is part of our filesystems that we've got ready for distribution.
<img width="764" alt="image" src="https://user-images.githubusercontent.com/114563164/222064428-f7f8ec98-c84f-40e1-90a2-439df5a46d1a.png">
<img width="759" alt="image" src="https://user-images.githubusercontent.com/114563164/222064506-d8881c13-eedb-4882-b5f2-a673605b23a3.png">

About filling out the kyc form, I'm sorry, we won't be filling out this form. Because this is a fee-charging form, we have not seen that FIL+ officially authorizes such an organization to do this. Secondly, what this organization collects is private information. In China, only government departments have this right.

If the FIL+ official has this requirement for all clients applying for LDN, and authorizes the organization, we are very willing to cooperate.

**Comment by cryptowhizzard** [comment]
Hi,

I am not aware of the limitations for KYC for China just to say who you are and what you do. I received dozens of KYC forms in last weeks.

Notary's are obliged to do due diligence. There are a few around who work on different terms but this will soon change so it has to happen eventually ;-)

**Comment by fujianZT** [comment]
> Notary's are obliged to do due diligence. There are a few around who work on different terms but this will soon change so it has to happen eventually ;-)

Ok, we've filled it out.
