### ISSUE TITLE
[DataCap Application] <Ximan> - <Media>

### ISSUE THREAD

**Issue by Finonaa** [filecoin-project/filecoin-plus-large-datasets#1032]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Ximan  Media
- Website / Social Media:http://www.cqxmcm.com/index.html
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):200TiB
- On-chain address for first allocation:f1qfczv4ybluy5agjuqodx3ebmawlczlos5bopzfa

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Chongqing Ximan Film and Television Media Co., Ltd. estabilshed in 2010 and covers five major project systems: film and television production, advertising media, technology exhibitions, brand operation, planning and planning, and provides all-round visual marketing solutions. Now it is expanding the western market with Chongqing as the center. The market business covers Yun, Gui, Sichuan, Shaanxi, Hubei, Hunan, Guangxi and other regions, serving more than 100 governments and large and medium-sized enterprises. Committed to providing comprehensive services for the city's external publicity system, and motivated to become a high-quality service provider for the city's external publicity system.
```

What is the primary source of funding for this project?
```
Company Revenue
```

What other projects/ecosystem stakeholders is this project associated with?
```
No other projects/ecosystems
```

## Use-case details

Describe the data being stored onto Filecoin
```
We want to store some film and television productions, government propaganda films, corporate propaganda films, TVC commercial films, product propaganda films, investment promotion films, micro-films, feature films, documentaries, photography, advertising, film and television media, self-media, brand planning , album design, product design, software development, technology exhibition and other data resources
```

Where was the data in this dataset sourced from?
```
The dataset is from ourself.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
[Please answer here.](http://www.cqxmcm.com/html/zuopinzhanshi/)
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes
```

What is the expected retrieval frequency for this data?
```
at least once a year
```

For how long do you plan to keep this dataset stored on Filecoin?
```
at least 3 years
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
China
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Both online and offline transfer.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
Choose a storage provider with excellent technical capabilities and an understanding of the value of the project.
```

How will you be distributing deals across storage providers?
```
The shares are distributed evenly and then adjusted according to actual performance.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes,we have enough funds.
```

**Comment by raghavrmadya** [comment]
No data samples provided. Just the website. Please open a new application with proper data samples
