### ISSUE TITLE
[DataCap Application] <Zhensulv> - <Lightshadow>

### ISSUE THREAD

**Issue by Fransiaa** [filecoin-project/filecoin-plus-large-datasets#1033]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Zhensulv
- Website / Social Media: http://www.zhensulv.com/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):100TiB
- On-chain address for first allocation: f1x6v5th3nigwwsnpbd73hohwerx6mc25og5cb37i

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```

The predecessor of Light and Shadow Media was Meitu Advertising, which was established in 2011. At first, it focused on graphic design and photography as its main business. After years of development, its business scope has continued to expand. Now it has developed into an excellent video media company in the region. Our mission Based on our own strengths, we provide customers with economical, accurate and future-oriented video advertising solutions to help customers enhance their brand influence. For this reason, we hope to serve customers more efficiently and continuously improve service levels. We attach great importance to the content-oriented trend of corporate video image display and video marketing, and our creative services and video marketing tools are all "effect-oriented". As an excellent production company in the field of video advertising, it is good at using video content to create benign communication for corporate customers, and is good at communicating with customers directly, quickly and effectively, and establishes an intimate relationship beyond ordinary cooperation.

```

What is the primary source of funding for this project?
```
It is our company revenue
```

What other projects/ecosystem stakeholders is this project associated with?
```
No associate with others
```

## Use-case details

Describe the data being stored onto Filecoin
```

Suzhou Frame Rate Culture Media Co., Ltd. was established in 2016. It is composed of Suzhou Timeline Culture Media Co., Ltd. It is a cultural enterprise with animation content creation as its core. It is formed by the core planning team, operation team, creative team and production team of former Bilibili, former MiLi Pictures, Oriental DreamWorks, Hengdian Film and Television Group. The company's main business includes original animation development, animation IP planning and operation, The whole process of 2D and 3D animation production. The company has participated in the planning, operation, creation and production of many high-end projects at home and abroad such as animation films, animation dramas, animation CG, and live shooting, providing high-quality services to customers at home and abroad, and improving the commercial value of operating projects with professional operation methods. In the original development of animation, we cooperate with upstream and downstream enterprises in the industry chain to create a closed loop of the animation industry. The company digs deep into the traditional culture of "China Five Thousand Years", passes the excellent traditional Chinese culture to children through animation, and creates the smiling faces of the next generation of human beings. We have always taken happiness, dreams and inspiration as our corporate culture.

```

Where was the data in this dataset sourced from?
```
It is meanly from ourself and our customers
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
http://www.zhensulv.com/a/chanpin/

```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
yes
```

What is the expected retrieval frequency for this data?
```
twice one year
```

For how long do you plan to keep this dataset stored on Filecoin?
```
3years
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
China
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
online transfer process
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
the povider with great sense of responsibility and excellent technical capability
```

How will you be distributing deals across storage providers?
```

I have communicated with 2 sp. In first time, I will divide 1/4 data to each sp. If I find out more sp, I will decrease the percentage of deals to them --- for decentralized storage.

```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
yes
```

**Comment by raghavrmadya** [comment]
No data samples provided

**Comment by Fransiaa** [comment]
> No data samples provided

http://www.zhensulv.com/a/chanpin/
this is the sample from our company. They are mainly pictures show on the website.if you need more i will prepare for you. Thank you！
