### ISSUE TITLE
[DataCap Application] congtu.cloud

### ISSUE THREAD

**Issue by chongtuyun** [filecoin-project/filecoin-plus-large-datasets#1034]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: congtu.cloud
- Website / Social Media: https://www.teuring.cloud/home   https://www.congtu.cloud/home
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):200TiB
- On-chain address for first allocation: f1a6lacnqztppuoptbmlirdx6j3t4yems2vvitkpq

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Founded in 2019, congtu is affiliated to congtu intelligence. It is a distributed high-performance computing network for the 5G+AIoT era. By integrating idle high-performance computing resources around the world, it provides artificial intelligence training and reasoning, cloud games, Visual rendering, blockchain, smart city, smart manufacturing and many other industries provide cost-effective, low-latency, high-density, full-coverage high-quality computing services. Serving global AI developers and various enterprises.

Congtu has more than 8,100 GPUs around the world, supports more than 16 GPU models, and has more than 100 computing nodes. The total number of users in enterprises and universities has exceeded 20,000.

congtu has reached cooperation with a number of cloud game and cloud rendering customers such as Rendering Cloud, Kingsoft Cloud, Tingyu Technology, Mushroom Yunyou and Weiling Times. At the same time, with the advantage of high cost performance, more than 500 well-known universities and scientific research institutions from around the world are using Congtu cloud network computing power for AI development and other research.
```

What is the primary source of funding for this project?
```
Our company is well funded
```

What other projects/ecosystem stakeholders is this project associated with?
```
nothing 
```

## Use-case details

Describe the data being stored onto Filecoin
```
We plan the  public data  , stored on the Filecoin network.
```

Where was the data in this dataset sourced from?
```
Sourced from our storage platform, Congtu Cloud
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://drive.google.com/drive/my-drive
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Confirm
```

What is the expected retrieval frequency for this data?
```
This is backup data, may be retrieved once a year
```

For how long do you plan to keep this dataset stored on Filecoin?
```
I would like to store more than 3 years, or longer
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Without limiting the storage area, we believe that global distribution is more in line with the characteristics of distributed storage.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Both are possible, mainly offline transmission.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We choose SPs with strong technical strength, experience in packaging DC, and understanding of retrieval.
```

How will you be distributing deals across storage providers?
```
Comply with the rules, distribute fairly, and ensure that data is stored in a decentralized and secure manner.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes,  We are prepared.
```

**Comment by raghavrmadya** [comment]
Data samples do not exist. Please provide them to proceed

**Comment by chongtuyun** [comment]
https://docs.google.com/document/d/1yQgCWDWOQwFFaGLF-gymrg0-f7foxn9I/edit
https://docs.google.com/document/d/1eY3kajnXUcEg2dPu7VRLc8RAivplcbXb/edit
https://docs.google.com/document/d/184jORyfoRkACFB642rdmhgI8cNbE0EpN/edit
sorry，sir,

**Comment by chongtuyun** [comment]
https://drive.google.com/drive/folders/14rAfgniY7LpcW4qxmz4DJPhttPJxA19O?usp=sharing

**Comment by chongtuyun** [comment]
can you agree  my request，thank you！

**Comment by Sunnyiscoming** [comment]
Any update here?

**Comment by chongtuyun** [comment]
sorry， @Sunnyiscoming ，We just saw your message now

**Comment by chongtuyun** [comment]
There are two folders in total, where scene is our test picture, which is used by our company's internal employees to test our system.

**Comment by chongtuyun** [comment]
Please check the game file and ignore the scene file, thanks

**Comment by Sunnyiscoming** [comment]
Can you explain your data composition and provide sufficient data samples separately? How many copies will you store?
What's the relationship between you and the organization?
Can you provide more detailed information about other storage providers participated in this program, such as you can list SPs you have contacted with at present?

**Comment by chongtuyun** [comment]
I am the boss of the company, I asked my colleagues to prepare relevant data. I am sorry that my subordinates also submitted the data of the cloud disk of the test system, which caused trouble to you. I am sorry, and we will resubmit a new one for you. data, please wait

**Comment by chongtuyun** [comment]
The data comes from our company's business,  games and aviation data are the main data of our company. We resubmit the data case, please check: https://drive.google.com/drive/folders/14rAfgniY7LpcW4qxmz4DJPhttPJxA19O?usp=share_link

We plan to back up 4-5 copies, contact 4-5 SP to store data for us. we have contacted these five SP:

F0119336 、 f01035680 、 f01443744 、 f01543586 、 f01407260

If you have a high-quality sp recommendation, welcome to recommend, thank you.

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 200TiB

**Client address**

> f1a6lacnqztppuoptbmlirdx6j3t4yems2vvitkpq

**Comment by Sunnyiscoming** [comment]
Hey @chongtuyun , if you still want to apply for datacap, you can ask notaries to do client due diligence in slack channel. https://app.slack.com/client/TEHTVS1L6/C036JKD8NVA/thread/C03BG1MNQ4T-1673888660.823499

**Comment by chongtuyun** [comment]
hey, @Sunnyiscoming , what do I need to do, we are in singapore, if you also have colleagues in singapore, glad to meet you.

**Comment by stcouldlisa** [comment]
@chongtuyun You need to send email to filplus-app-review@fil.org with domain email address
