### ISSUE TITLE
[DataCap Application] The three classes

### ISSUE THREAD

**Issue by yuelinglong** [filecoin-project/filecoin-plus-large-datasets#1035]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: The three classes
- Website / Social Media: https://sanjieke.cn  http://sanjieke.com  http://sanjieke.cc
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 200TiB
- On-chain address for first allocation: f142gswwplxoeq6m7cyhia3uwfucj7tfc5aeyfjia

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Founded in 2015, the three classes are China's leading digital talent strategy service providers, providing content centered online training solutions for digital talents for enterprises and individual users. Headquartered in Beijing, it has branches in Shanghai, Shenzhen and Tianjin, and a "Knowledge Management Institute" in Chengdu. It is based in Beijing and serves the whole country, and has developed into a national high-tech enterprise.
```

What is the primary source of funding for this project?
```
Own funds.
```

What other projects/ecosystem stakeholders is this project associated with?
```
No.
```

## Use-case details

Describe the data being stored onto Filecoin
```
It is mainly the public curriculum data set accumulated by the company for many years, and the audio and video of teachers' lesson preparation.
```

Where was the data in this dataset sourced from?
```
Publicly available data in the organization.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://pan.baidu.com/s/1zOCJZWS4Dh6iqitwKPmUnQ?pwd=t814
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
We Confirm.
```

What is the expected retrieval frequency for this data?
```
Multiple times/year.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
More than 3 years.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Global.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
The data is too large and can only be transmitted offline.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We find SPs in the #fil-plus community to sealing  data.
```

How will you be distributing deals across storage providers?
```
Offline data transfer.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
I don't need any help at the moment. If necessary, we will contact Filecoin slack. 
```

**Comment by raghavrmadya** [comment]
<img width="739" alt="Screen Shot 2022-10-04 at 10 22 10 PM" src="https://user-images.githubusercontent.com/91579519/193987142-03a2fc8d-4d74-4309-8d3e-3af1a9121c1b.png">

**Comment by yuelinglong** [comment]
![20221006000158](https://user-images.githubusercontent.com/16491315/194107655-ea2d3b91-0be5-47b7-a332-6e7524ae3199.png)
Well, the website can be opened normally.

**Comment by yuelinglong** [comment]
Hi, @raghavrmadya Good evening,

Well, we verified from multiple sources that the official website can be opened normally.

Please check again, thank you!

**Comment by kernelogic** [comment]
I have viewed the website and the course samples and they seem legit. However:

1. Please prove your relationship with the company.
2. Please prove your total files to store exceeds 500TiB.
3. Please tell us more about the SP IDs, locations and their operators entity.

**Comment by NDLABS-OFFICE** [comment]
Could you send an email to [filplus-app-review@fil.org](mailto:filplus-app-review@fil.org) with your official domain in order to confirm your identity? Email name should includes the issue id https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1035.

**Comment by yuelinglong** [comment]
@NDLABS-OFFICE 
Good evening,
The email has been sent. Please check it. The screenshot is as follows.
![1](https://user-images.githubusercontent.com/16491315/204844951-8a5d8a66-9745-442a-9502-73061f600298.png)

**Comment by yuelinglong** [comment]
@kernelogic 
Hello, kernelogic.
First, I have sent an email to the official mailbox to confirm;
Second, I have a screenshot of our data platform, which can prove that our data is greater than 500TiB.
Third, I found some storage providers whose SP IDs include f01915692, f01860589, f01490391, f01867658, f01914991, etc.
thanks.

<img width="1171" alt="40e745cfd31745fe3ac26693f89e213" src="https://user-images.githubusercontent.com/16491315/204846840-97695af8-08d8-4140-8d21-e10edc6c3230.png">

**Comment by NDLABS-OFFICE** [comment]
@yuelinglong thaks~ But you need to show your work email suffix to complete KYB certification.

**Comment by yuelinglong** [comment]
@NDLABS-OFFICE 
![1](https://user-images.githubusercontent.com/16491315/206450240-9982111a-7f75-482a-b9af-6e954e708175.png)

**Comment by yuelinglong** [comment]
Can someone help me, you can ask any questions, our company does have a lot of data to store on the Filecoin network.

**Comment by stcouldlisa** [comment]
Looks good, I'd like to support it ，However, please make sure you have 4 and above SP, I will strictly track

**Comment by stcouldlisa** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaup6wfkzfp5xxqqczofirsykyzh6pvgliqhocrnkajcp2u4dpi44 
#### Address 
> f142gswwplxoeq6m7cyhia3uwfucj7tfc5aeyfjia
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1jvvltduw35u6inn5tr4nfualyd42bh3vjtylgci
#### Id
> 93f18090-9436-4df5-9dc9-9637559416df
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaup6wfkzfp5xxqqczofirsykyzh6pvgliqhocrnkajcp2u4dpi44

**Comment by newwebgroup** [comment]
According to KYB, it is compliant. 

It is worth mentioning that
> I personally learned about this enterprise a few years ago, and it is quite famous in the same industry. I have bought their online courses to learn, and it is not bad.
> I am looking forward to their loading data into Filecoin, and I will keep monitoring!

**Comment by newwebgroup** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebxhbdcxzf6enqmerdscbf66goanthmpanx6xkxkweqg4h7yrodi2 
#### Address 
> f142gswwplxoeq6m7cyhia3uwfucj7tfc5aeyfjia
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1e77zuityhvvw6u2t6tb5qlnsegy2s67qs4lbbbq
#### Id
> 93f18090-9436-4df5-9dc9-9637559416df
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebxhbdcxzf6enqmerdscbf66goanthmpanx6xkxkweqg4h7yrodi2

**Comment by kernelogic** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecidjnrnzvjj6j5w6aocqqmxdci7xg5hm3xelunigppvj546s3im6 
#### Address 
> f142gswwplxoeq6m7cyhia3uwfucj7tfc5aeyfjia
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### Id
> 94cd2df2-f50d-40fd-a6f0-8d5e64d4b719
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecidjnrnzvjj6j5w6aocqqmxdci7xg5hm3xelunigppvj546s3im6

**Comment by NDLABS-OFFICE** [comment]
✔️ Storage provider distribution looks healthy.
✔️ Data replication looks healthy.
✔️ No CID sharing has been observed.
willing to support.

**Comment by NDLABS-OFFICE** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecbln32sztxvpyn2qojrpolu6n3cks6v4civgiovwwbow67xcitea 
#### Address 
> f142gswwplxoeq6m7cyhia3uwfucj7tfc5aeyfjia
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1yayfsv6whu3rheviucvventj3y6t542xfpb47ei
#### Id
> 94cd2df2-f50d-40fd-a6f0-8d5e64d4b719
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecbln32sztxvpyn2qojrpolu6n3cks6v4civgiovwwbow67xcitea

**Comment by Tom-OriginStorage** [comment]
checker:manualTrigger

**Comment by herrehesse** [comment]
@yuelinglong can you show us a proof of dataset size? 5PiB for the described data seems very high to me. Thanks for helping!

**Comment by yuelinglong** [comment]
@herrehesse 
![1](https://user-images.githubusercontent.com/16491315/212473092-7be4e969-8443-4433-a0bc-6c689bfb6986.png)

**Comment by cryptowhizzard** [comment]
I am sorry, i have tried 3 times but i am getting errors when i retrieve deals. The carfiles downloaded are unreadable.

Can you check with your SP's?

**Comment by yuelinglong** [comment]
![1](https://user-images.githubusercontent.com/16491315/223947930-ce4b59f2-23c4-476d-810d-74d50587fa66.png)
![2](https://user-images.githubusercontent.com/16491315/223947957-8b57d0fe-ecba-4c2d-8394-c297503a45a0.png)
![3](https://user-images.githubusercontent.com/16491315/223947966-5705f33f-1c31-4240-b3e0-5fe22c3f0a41.png)
![4](https://user-images.githubusercontent.com/16491315/223947978-bb8dfb2a-c2e7-4713-9675-5a8c0aa549c4.png)

**Comment by 1ane-1** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacea7o6mfxhqjz43rotjlnpeogyeb7utrpzqnzey36zz4vnxbixyagk 
#### Address 
> f142gswwplxoeq6m7cyhia3uwfucj7tfc5aeyfjia
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1mdk7s2vntzm6hu35yuo6vjubtrpfnb2awhgvrri
#### Id
> 2cf33678-cee1-4bfe-a626-016eb124e8ed
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacea7o6mfxhqjz43rotjlnpeogyeb7utrpzqnzey36zz4vnxbixyagk

**Comment by Zhangcffff** [comment]
checker:manualTrigger

**Comment by Tom-OriginStorage** [comment]
checker:manualTrigger

**Comment by Tom-OriginStorage** [comment]
<img width="1243" alt="image" src="https://user-images.githubusercontent.com/103015469/224541612-574a6f08-3d87-4e5d-a889-1a1fea92e89b.png">

**Comment by Tom-OriginStorage** [comment]
According to the robot inspection, so far the packaging complies with the rules, and the sector retrieval is also normal, willing to support

**Comment by Tom-OriginStorage** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecmj42da5bjl6zsekg5nqfwilcrdddcf7kmoxu7fe43bzq3q5piu4 
#### Address 
> f142gswwplxoeq6m7cyhia3uwfucj7tfc5aeyfjia
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1q6bpjlqia6iemqbrdaxr2uehrhpvoju3qh4lpga
#### Id
> 2cf33678-cee1-4bfe-a626-016eb124e8ed
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecmj42da5bjl6zsekg5nqfwilcrdddcf7kmoxu7fe43bzq3q5piu4

**Comment by igoovo** [comment]
checker:manualTrigger

**Comment by igoovo** [comment]
It can be retrieved normally, and seems to be OK.

![image (1)](https://user-images.githubusercontent.com/103082537/225806502-9f42ff37-01e5-47dc-b013-f121f8e0196b.png)
![image](https://user-images.githubusercontent.com/103082537/225806523-d6324c19-47bc-4f4d-94f1-260766d9c285.png)

**Comment by igoovo** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceco2q25vjr3gzu72lnevucqlvtydaezliqxdo4hapun2det2kwqy2 
#### Address 
> f142gswwplxoeq6m7cyhia3uwfucj7tfc5aeyfjia
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1shnsfayxqll77svffaxnjenms7bbbysbqcatrpy
#### Id
> 9e185039-7665-4de9-adf3-99133ad24d05
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceco2q25vjr3gzu72lnevucqlvtydaezliqxdo4hapun2det2kwqy2

**Comment by Zhangcffff** [comment]
![image](https://user-images.githubusercontent.com/96216253/225834635-e92f9b54-7ca9-48a6-8f38-865e1ff2e6b3.png)
![image](https://user-images.githubusercontent.com/96216253/225834661-a923a8d8-7b6e-4341-963f-4630cc3399b0.png)

**Comment by sxxfuture-official** [comment]
checker:manualTrigger

**Comment by sxxfuture-official** [comment]
AND most of rules of CID-Checker are compliant，but hopes solve the repetition  problem next. support this round.

**Comment by sxxfuture-official** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceacx2mr6qlo4dvtye6mketa47ywd5j42twcywc6wfyxbrfdi6lu62 
#### Address 
> f142gswwplxoeq6m7cyhia3uwfucj7tfc5aeyfjia
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1foiomqlmoshpuxm6aie4xysffqezkjnokgwcecq
#### Id
> 9e185039-7665-4de9-adf3-99133ad24d05
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceacx2mr6qlo4dvtye6mketa47ywd5j42twcywc6wfyxbrfdi6lu62

**Comment by yuelinglong** [comment]
checker:manualTrigger
