### ISSUE TITLE
[DataCap Application] Shenzhen Huaxia Landmark E-commerce Co., Ltd

### ISSUE THREAD

**Issue by maxintd** [filecoin-project/filecoin-plus-large-datasets#1036]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Shenzhen Huaxia Landmark E-commerce Co., Ltd
- Website / Social Media: https://www.dbmall.com/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 2PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100TiB
- On-chain address for first allocation: f176jxzznri6vagdje32sezuflhw57gwkstlto3wa

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Shenzhen Huaxia Landmark E-commerce Co., Ltd., founded on September 9, 2015, is located in the beautiful Nanshan District of Shenzhen. Landmark Mall is a main business of the company. The mall focuses on China's geographical indication products and aims to meet the demand for high-end food materials of China's high net worth people. "Food is the most important thing for the people and safety is the most important thing for food" - The landmark mall aims to solve the food safety problem and the pain point of the demand for high-quality food materials, so that consumers can enjoy truly safe and delicious high-quality food materials without leaving home. Landmark Mall promises to every consumer that all merchants who enter the Landmark Mall are those who have passed the quality inspection of the General Administration of Quality Supervision, Inspection and Quarantine of the People's Republic of China.

In addition to traditional online marketing, the marketing channel of Landmark Mall also makes full use of the user advantages of China Radio International and China Daily national media to build an online B2C platform for national geographical indication products.
```

What is the primary source of funding for this project?
```
Self owned profit of the platform.
```

What other projects/ecosystem stakeholders is this project associated with?
```
No.
```

## Use-case details

Describe the data being stored onto Filecoin
```
The business data accumulated in the past 7 years and the unclassified data to be stored in the future.
```

Where was the data in this dataset sourced from?
```
The data comes from the dbmall platform.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
Preparing
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes, We Confirm.
```

What is the expected retrieval frequency for this data?
```
1-3 times a year.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
40 months.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
East Asia.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Too large and we transfer it offline.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We can find reputable SPs in the community to seal data.
```

How will you be distributing deals across storage providers?
```
Offline data transfer.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
We will contact Filecoin slack if assistance is needed.
```

**Comment by raghavrmadya** [comment]
Hi @maxintd , can you please provide more information on the dataset? It is a bit unclear of what exactly you are looking to store

**Comment by raghavrmadya** [comment]
Have you been in touch with SPs already? If yes, please share their SP ID

**Comment by maxintd** [comment]
> Hi @maxintd , can you please provide more information on the dataset? It is a bit unclear of what exactly you are looking to store
Hi, @raghavrmadya,  We have prepared some data samples to store in Google Cloud Disk: 
https://drive.google.com/drive/folders/1f6JcHCp102dJhdWlgfHaY25Iuyisrhii

**Comment by maxintd** [comment]
> Have you been in touch with SPs already? If yes, please share their SP ID

We contacted nodes f0406322, f010617, f01900687, f0447183, and f01909497. We will find more high-quality nodes to store data for us. thank you!

**Comment by raghavrmadya** [comment]
Data samples shared do not reflect the 2PiB need. You mentioned you are planning to use DC for future data generated but we can only give DC to store data you have today. Please share how much data you have today (including relevant samples) as well as how many copies you plan to store

**Comment by maxintd** [comment]
Dear @raghavrmadya : 
Because the transmission to Google is slow, we only sent a few data samples.
Well, we tried ipfs and saved several samples:
https://nftstorage.link/ipfs/bafybeiez6vasqa4uowwhtcrvafyz22t6clb63m7fbov2gcyasv43sf6zmi
ipfs://bafybeidk7q2mxmbl2zqwxxn7usiwstefg72pl5hcftaf4z4ihj5keadopy

We think that the technology of ipfs/filecoin is very cool, and we are looking forward to storing data in it. On the one hand, we can reduce our storage expenses, and on the other hand, we can research new storage technologies.

In fact, after years of accumulation, our data is still quite large, as shown in the following figure:
![无标题](https://user-images.githubusercontent.com/114985029/194749869-4b0ecfd5-411c-4f10-b24a-6ee5aad3e5bf.jpg)

We originally planned to store 7 copies, requiring about 1.4PiB, but we also have some other business related data, which can be fully stored in 2PiB.

Thank you for your patient review, thank you very much!

**Comment by raghavrmadya** [comment]
What exactly do you mean by business-related data?

**Comment by maxintd** [comment]
Dear @raghavrmadya , The related data of the mall mainly refers to the video of the product offline ground marketing activities. On average, more than 20 marketing activities are promoted every year, and we will record the activity video. The video size of each activity is about 300GiB-500GiB, and the data is nearly 20TiB in recent years.

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 2PiB

**Expected weekly DataCap usage rate**

> 100TiB

**Client address**

>f176jxzznri6vagdje32sezuflhw57gwkstlto3wa

**Comment by NDLABS-OFFICE** [comment]
Please prove your relationship with the company.
Please prove your total files to store exceeds 500TiB.

**Comment by maxintd** [comment]
As for the file data I want to store, I have already given a complete reply.
Please check.

**Comment by Sunnyiscoming** [comment]
Hey @maxintd , if you still want to apply for datacap, you can ask notaries to do client due diligence in slack channel. https://app.slack.com/client/TEHTVS1L6/C036JKD8NVA/thread/C03BG1MNQ4T-1673888660.823499
