### ISSUE TITLE
[DataCap Application] <EhostICT> - <OS Packages for Server Hosting >

### ISSUE THREAD

**Issue by gustjr154** [filecoin-project/filecoin-plus-large-datasets#1040]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: EhostICT
- Website / Social Media: https://www.ehostidc.com
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100TiB
- On-chain address for first allocation: f1dj23xokyovdqnbgx3nis3ygk73szanzlwb2kduy

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
EhostIDC provides co-location (line and top-lease)·Artificial Intelligence · GPU Hosting· leased single server·server management agency·24/7/365 customer support·servers· security solutions·CDN (Contents Delivery Network) Service and software licensing. We have a main IDC in Seoul, South Korea, and have our own IDC farms in over 30 countries as providing overseas hosting services.
```

What is the primary source of funding for this project?
```
Own funds and revenue of the company.
```

What other projects/ecosystem stakeholders is this project associated with?
```
No. 
```

## Use-case details

Describe the data being stored onto Filecoin
```
We have Docker-imaged OS packages with the various versions upon client's request. 
We would provide customized services easily and directly via filecoin for our IDC services include server hosting and cloud hosting. 
and also use it for "GPU Cloud services" which is about to release as a new service.
```

Where was the data in this dataset sourced from?
```
The data/images comes from our R&D department via Docker 
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
www.ehostidc.com/upload/1w-1.mp4
www.ehostidc.com/upload/1w-2.mp4
www.ehostidc.com/upload/1w-3.mp4
www.ehostidc.com/upload/1w-4.mp4
www.ehostidc.com/upload/2w-1.mp4
www.ehostidc.com/upload/2w-2.mp4
www.ehostidc.com/upload/3w-1.mp4
www.ehostidc.com/upload/3w-2.mp4
www.ehostidc.com/upload/4w-1.mp4
www.ehostidc.com/upload/4w-2.mp4
www.ehostidc.com/upload/5w-1.mp4
www.ehostidc.com/upload/5w-2.mp4
www.ehostidc.com/upload/5w-3.mp4
www.ehostidc.com/upload/6w-1.mp4
www.ehostidc.com/upload/6w-2.mp4
www.ehostidc.com/upload/7w-1.mp4
www.ehostidc.com/upload/7w-2.mp4
www.ehostidc.com/upload/vidio traffic.mp4

```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes. 
```

What is the expected retrieval frequency for this data?
```
Mostly our employees in sales and R&D department in the beginning. Our goal is clients can access the data directly and use or edit according to their own needs. 
```

For how long do you plan to keep this dataset stored on Filecoin?
```
At least 3 years. As long as our company provide cloud services, it would be extended. 
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
The global. Mostly Asia
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Both online and offline data transfer depending on the preference of storage providers.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We will select SPs who could meet our requirements in terms of storage cost, and geographical location. Since our global customers located in Europe and Asia, probs getting one or over in Europe, two or over in Asia.
```

How will you be distributing deals across storage providers?
```
We will follow the allocation rules on this basis. each SP will be distributed deals no more than 20% of all.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes. We are ready to start making deals. 
```

**Comment by gustjr154** [comment]
@raghavrmadya Hello, RG
Can you please look it up my application? 
I'm waiting for your feedback.

**Comment by Sunnyiscoming** [comment]
It seems that you submitted the same request, #1153 .
If it is same as this one, please close it.

**Comment by gustjr154** [comment]
@Sunnyiscoming 
Just revised the data samples. Please check. 

www.ehostidc.com/upload/1w-1.mp4
www.ehostidc.com/upload/1w-2.mp4
www.ehostidc.com/upload/1w-3.mp4
www.ehostidc.com/upload/1w-4.mp4
www.ehostidc.com/upload/2w-1.mp4
www.ehostidc.com/upload/2w-2.mp4
www.ehostidc.com/upload/3w-1.mp4
www.ehostidc.com/upload/3w-2.mp4
www.ehostidc.com/upload/4w-1.mp4
www.ehostidc.com/upload/4w-2.mp4
www.ehostidc.com/upload/5w-1.mp4
www.ehostidc.com/upload/5w-2.mp4
www.ehostidc.com/upload/5w-3.mp4
www.ehostidc.com/upload/6w-1.mp4
www.ehostidc.com/upload/6w-2.mp4
www.ehostidc.com/upload/7w-1.mp4
www.ehostidc.com/upload/7w-2.mp4
www.ehostidc.com/upload/vidio traffic.mp4

**Comment by gustjr154** [comment]
@Sunnyiscoming 
Just revised the data samples. Please check as below. 


www.ehostidc.com/upload/1w-1.mp4
www.ehostidc.com/upload/1w-2.mp4
www.ehostidc.com/upload/1w-3.mp4
www.ehostidc.com/upload/1w-4.mp4
www.ehostidc.com/upload/2w-1.mp4
www.ehostidc.com/upload/2w-2.mp4
www.ehostidc.com/upload/3w-1.mp4
www.ehostidc.com/upload/3w-2.mp4
www.ehostidc.com/upload/4w-1.mp4
www.ehostidc.com/upload/4w-2.mp4
www.ehostidc.com/upload/5w-1.mp4
www.ehostidc.com/upload/5w-2.mp4
www.ehostidc.com/upload/5w-3.mp4
www.ehostidc.com/upload/6w-1.mp4
www.ehostidc.com/upload/6w-2.mp4
www.ehostidc.com/upload/7w-1.mp4
www.ehostidc.com/upload/7w-2.mp4
www.ehostidc.com/upload/vidio traffic.mp4

**Comment by gustjr154** [comment]
@simonkim0515 @Sunnyiscoming 
Hello, all 
This application is the same as #1274  
I didn't know how to close the application back time so I have posted a new one (1274) while your team has no response for a month. 
Please keep following up there. 
I'm closing this one.
