### ISSUE TITLE
[DataCap Application] PERCENT Technology Co.,ltd

### ISSUE THREAD

**Issue by tim38925** [filecoin-project/filecoin-plus-large-datasets#1041]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: PERCENT Technology Co.,ltd
- Website / Social Media: https://en.percent.cn/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100TiB
- On-chain address for first allocation: f12oilczdjigwlpbuym643hh4zuvlvldba2fw7jva

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
PERCENT Technology is dedicated to promoting social progress with data intelligence. With full-stack big data and AI products。Our Digital City project creates a "city brain" with data intelligence for all our clients all over the world, we're collecting、storing、training and providing data service to our client.
```

What is the primary source of funding for this project?
```
Own Funds
```

What other projects/ecosystem stakeholders is this project associated with?
```
Interest relationship with our end customer, and no interest related with other projects
```

## Use-case details

Describe the data being stored onto Filecoin
```
Public internet dataset
```

Where was the data in this dataset sourced from?
```
Desensitized open datasets from clients or public datasets for AI model training from public AI modeling website, such as https://www.datacastle.cn/dataset_list.html
We're sure that this data source support their data to be uploaded to Filecoin network.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
City Car Recognition Training dataset:
https://pan.baidu.com/s/1gZT04ZmFCpsLsriH3tqk5A?pwd=abrz
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes
```

What is the expected retrieval frequency for this data?
```
not much
```

For how long do you plan to keep this dataset stored on Filecoin?
```
Permanent storage or five years at least
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
US
APAC
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Online and offline
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We plan to discuss and perform due diligence with some SPs with high reputation, and hopefully could also get some reference from notaries
```

How will you be distributing deals across storage providers?
```
We will identify at least 5-10 SPs for long term partnership. Ideally, we would distribute deals evenly across the SPs.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
yes
```

**Comment by raghavrmadya** [comment]
Hi, the link you've provided says the file size is 2.3M. Can you share more information on this public dataset? Have you considered using Slingshot for this dataset?

**Comment by tim38925** [comment]
> 
Yes RG,  I shared another two datasets sample as:
https://pan.baidu.com/s/1wuOkj6E1fD5fzTURZXDEVg?pwd=fwqe  (1.87G)
https://pan.baidu.com/s/12PM08xy6uPNQ9I-gyGf6BQ?pwd=4d37 (124M)
I'm trying Slingshot, which may need some time 😁.

**Comment by tim38925** [comment]
> 

Yes RG, I shared another two datasets sample as:
https://pan.baidu.com/s/1wuOkj6E1fD5fzTURZXDEVg?pwd=fwqe (1.87G)
https://pan.baidu.com/s/12PM08xy6uPNQ9I-gyGf6BQ?pwd=4d37 (124M)
I'm trying Slingshot, which may need some time 😁.

**Comment by raghavrmadya** [comment]
Still nor able to determine the 5 PiB request. Please clarify the actual size of the data set and number of copies being stored

**Comment by tim38925** [comment]
Hi RG
Thanks for your reply.

I try to understand your concern that you don’t think our storage needs
5PiB?
Actually the samples I shared are just for reference in terms of one angle.
Our data include both private data for clients and desensitized data
cooperating with public sharing platform to the public for learning and
public use such as advertising, tech teaching course, project
introduction,etc.
You can refer to below links for the public dataset in our digital city
project which might give your more details why we need more data cap:
https://www.bilibili.com/video/BV1vz411B7WS/?spm_id_from=333.337.search-card.all.click
https://www.bilibili.com/video/BV1Nf4y1R7Ug/?spm_id_from=333.337.search-card.all.click
https://space.bilibili.com/368687062


As well, we are working with some Web3 partners in terms of Metaverse like
below link:
https://space.bilibili.com/81516606



Video fusion technology is a branch of virtual reality technology. We
believe 3D video fusion technology can create more potentials in future
city buildup and management. That is why we develop our business to fit in
today’s trend because the need for data storage is growing rapidly if we
want to really have an efficient and intelligent city.

As I said in the application, we are looking for a long-term support in
this community but respect your decision - how much I can apply for at
current stage.

Look forward to your further feedback.

Thanks.

RG ***@***.***> 于2022年11月9日周三 00:02写道：

**Comment by raghavrmadya** [comment]
As this includes private data, the information provided originally violates the rules of the LDN process. I would recommend applying for E-Fil+ pilot to onboard your dataset. You can reach out to @kevzak for further information or join the fil-plus-enterprise-wg on Filecoin slack

**Comment by tim38925** [comment]
Hi RG

Thanks for your reply.
Can I know what data sample I provided is private data as you mentioned? I
think there might be some misunderstanding in between.
Appreciate the team can communicate with more details and support since
this application has been approved months ago without any similar questions.

Look forward to your further reply.

RG ***@***.***> 于2022年11月22日周二 01:34写道：
