### ISSUE TITLE
[DataCap Application] <SYRE BLOCKCHAIN CORP.> - <SYRE >

### ISSUE THREAD

**Issue by fmwxyz** [filecoin-project/filecoin-plus-large-datasets#1043]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: SYRE BLOCKCHAIN CORP.
- Website / Social Media:www.syreblockchain.net
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):3 PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):100 TiB
- On-chain address for first allocation:f1gk6ku7nkvip3upyzdit4tznerqba2ty7a2yss6y

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
SYRE BLOCKCHAIN INC. provides computing power to cryptocurrency networks such as Bitcoin, earning fees from each computing network to secure and process transactions. The company operates five facilities in Quebec, Canada. At present, the company has more than 30 megawatts of computing power and has mined more than 10,000 bitcoins. With a strong and experienced management team and industrialized data center operator as well as some capital market professionals, the company is focused on building the infrastructure of the future by developing and hosting an ecosystem around the development of blockchain technology. Recently, SYRE BLOCKCHAIN is actively connecting with venture capital companies. Including Korelya Capital, Galaxy Digital, Macquarie Capital, etc.

```

What is the primary source of funding for this project?
```
The company has made a profit, and the main source of funds is the company's own funds
```

What other projects/ecosystem stakeholders is this project associated with?
```
No stakeholders, we are independent
```

## Use-case details

Describe the data being stored onto Filecoin
```
The data stored on Filecoin is all about monitoring data, production data, R&D data, sales data.
```

Where was the data in this dataset sourced from?
```
Mainly from the data generated during our research and development, design, transportation and sales
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
yes

https://drive.google.com/file/d/1U1ZE-DAuuJypfWMDKlSbqSabY-zUuTyq/view?usp=sharing
https://drive.google.com/file/d/1h6Q8LpfCYTUyeCoRL2cHGA-J6e6YyuX_/view?usp=sharing
https://drive.google.com/file/d/1lRQ5eCi1_74Qj-n4N8CFzihi43U_Wym2/view?usp=sharing
https://drive.google.com/file/d/1U84iXF8kqtvw0YbNQ2C9tHzfHtppPF9y/view?usp=sharing
https://drive.google.com/file/d/18FNU2FJEsACUv2mlXWsABfyjk2JZxtCK/view?usp=sharing
https://drive.google.com/file/d/1VU5TNE-5pYThLjD_tajl3eZ1AQlXFtTB/view?usp=sharing
https://drive.google.com/file/d/1tralPXCK6JVUwCn_otQNTq6ow7EgnaXy/view?usp=sharing
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Confirm
```

What is the expected retrieval frequency for this data?
```
This is our backup data, expected to be retrieved every 6-9 months
```

For how long do you plan to keep this dataset stored on Filecoin?
```
about 12 months
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
We do not limit the storage area, we welcome global Miners to store our data to achieve true distributed storage
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Online transmission is simpler and faster, so we mainly focus on online transmission, and if necessary, we will also conduct offline transmission
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We will select miners with good reputation, trustworthiness, and experience in verifying data to conduct transactions.

```

How will you be distributing deals across storage providers?
```
We will find high-quality miners through slack, GitHub and other channels, distribute to miners in an even proportion. Also, each miner won’t be allocated more than 30% of our datacap.

```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, I do
```

**Comment by Sunnyiscoming** [comment]
https://whois.whoisxmlapi.com/lookup-report/1E2N7Apw56
It seems that this website has been established for 123 day. Can you give more description about your organization?
Can you explain your data composition and provide sufficient data samples separately? How many copies will you store?
What's the relationship between you and the organization?
Can you provide more detailed information about other storage providers participated in this program, such as you can list SPs you have contacted with at present?

**Comment by fmwxyz** [comment]
Hello, our company is a web3 company focusing on BTC mining. We are headquartered in Canada and manage 5 factories with 80+ employees.
As the data sample shows you, our company's data comes from the business content of our company's daily operations, such as company video surveillance, mining video surveillance, related design documents, promotional pictures/videos, etc.
We plan to store 5 copies so that our data can be stored more securely.
I am the person in charge of our company
We are still in communication with SP. Since we are not sure about your approval time, we have not yet fully determined the SP. We have contacted 5 SPs, f01652952, f01691327, f023467, f0137489, and f02576, but we have not yet confirmed that we will reach a cooperation.

**Comment by Sunnyiscoming** [comment]
> company video surveillance, mining video surveillance, related design documents, promotional pictures/videos, etc.

Surveillance seems not be suitable for storing as public data.

**Comment by fmwxyz** [comment]
> > company video surveillance, mining video surveillance, related design documents, promotional pictures/videos, etc.
> 
> Surveillance seems not be suitable for storing as public data.
develop app source files：
https://gitee.com/syre-blockchain-corp/syre-blockchain-corp 
https://drive.google.com/drive/folders/1F9UNlnCIGHOrpTI-7T9ORb8v3eTU7oay?usp=share_link Promotional Materials

**Comment by fmwxyz** [comment]
> # Large Dataset Notary Application
> To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.
> 
> ## Core Information
> * Organization Name: SYRE BLOCKCHAIN CORP.
> * Website / Social Media:www.syreblockchain.net
> * Total amount of DataCap being requested (between 500 TiB and 5 PiB):3 PiB
> * Weekly allocation of DataCap requested (usually between 1-100TiB):100 TiB
> * On-chain address for first allocation:f1gk6ku7nkvip3upyzdit4tznerqba2ty7a2yss6y
> 
> _Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._
> 
> ## Project details
> Share a brief history of your project and organization.
> 
> ```
> SYRE BLOCKCHAIN INC. provides computing power to cryptocurrency networks such as Bitcoin, earning fees from each computing network to secure and process transactions. The company operates five facilities in Quebec, Canada. At present, the company has more than 30 megawatts of computing power and has mined more than 10,000 bitcoins. With a strong and experienced management team and industrialized data center operator as well as some capital market professionals, the company is focused on building the infrastructure of the future by developing and hosting an ecosystem around the development of blockchain technology. Recently, SYRE BLOCKCHAIN is actively connecting with venture capital companies. Including Korelya Capital, Galaxy Digital, Macquarie Capital, etc.
> ```
> 
> What is the primary source of funding for this project?
> 
> ```
> The company has made a profit, and the main source of funds is the company's own funds
> ```
> 
> What other projects/ecosystem stakeholders is this project associated with?
> 
> ```
> No stakeholders, we are independent
> ```
> 
> ## Use-case details
> Describe the data being stored onto Filecoin
> 
> ```
> The data stored on Filecoin is all about monitoring data, production data, R&D data, sales data.
> ```
> 
> Where was the data in this dataset sourced from?
> 
> ```
> Mainly from the data generated during our research and development, design, transportation and sales
> ```
> 
> Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this.
> 
> ```
> yes
> 
> https://drive.google.com/file/d/1U1ZE-DAuuJypfWMDKlSbqSabY-zUuTyq/view?usp=sharing
> https://drive.google.com/file/d/1h6Q8LpfCYTUyeCoRL2cHGA-J6e6YyuX_/view?usp=sharing
> https://drive.google.com/file/d/1lRQ5eCi1_74Qj-n4N8CFzihi43U_Wym2/view?usp=sharing
> https://drive.google.com/file/d/1U84iXF8kqtvw0YbNQ2C9tHzfHtppPF9y/view?usp=sharing
> https://drive.google.com/file/d/18FNU2FJEsACUv2mlXWsABfyjk2JZxtCK/view?usp=sharing
> https://drive.google.com/file/d/1VU5TNE-5pYThLjD_tajl3eZ1AQlXFtTB/view?usp=sharing
> https://drive.google.com/file/d/1tralPXCK6JVUwCn_otQNTq6ow7EgnaXy/view?usp=sharing
> ```
> 
> Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
> 
> ```
> Confirm
> ```
> 
> What is the expected retrieval frequency for this data?
> 
> ```
> This is our backup data, expected to be retrieved every 6-9 months
> ```
> 
> For how long do you plan to keep this dataset stored on Filecoin?
> 
> ```
> about 12 months
> ```
> 
> ## DataCap allocation plan
> In which geographies (countries, regions) do you plan on making storage deals?
> 
> ```
> We do not limit the storage area, we welcome global Miners to store our data to achieve true distributed storage
> ```
> 
> How will you be distributing your data to storage providers? Is there an offline data transfer process?
> 
> ```
> Online transmission is simpler and faster, so we mainly focus on online transmission, and if necessary, we will also conduct offline transmission
> ```
> 
> How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
> 
> ```
> We will select miners with good reputation, trustworthiness, and experience in verifying data to conduct transactions.
> ```
> 
> How will you be distributing deals across storage providers?
> 
> ```
> We will find high-quality miners through slack, GitHub and other channels, distribute to miners in an even proportion. Also, each miner won’t be allocated more than 30% of our datacap.
> ```
> 
> Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
> 
> ```
> Yes, I do
> ```

**Comment by Sunnyiscoming** [comment]
How much design documents, promotional pictures/videos, etc. here?

**Comment by fmwxyz** [comment]
> 这里有多少设计文档、宣传图片/视频等？

100t of design pictures, 400t of promotional materials, 150t of videos, about 650t of data, 5 backups

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 3PiB

**Expected weekly DataCap usage rate**

> 100TiB

**Client address**

>f1gk6ku7nkvip3upyzdit4tznerqba2ty7a2yss6y

**Comment by Tom-OriginStorage** [comment]
1：can you send email to [[filplus-app-review@fil.org]
2：Which nodes do you want to store？

**Comment by fmwxyz** [comment]
> 1：can you send email to [[[filplus-app-review@fil.org](mailto:filplus-app-review@fil.org)] 2：Which nodes do you want to store？

2:f0503420 f01566485  f01988266 f01988261

**Comment by fmwxyz** [comment]
<img width="1435" alt="image" src="https://user-images.githubusercontent.com/112076938/208023040-61433d95-add4-468e-a9ed-9456b9b2fa51.png">

**Comment by Tom-OriginStorage** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceatvvatybkdxciorq2xx2umbreay5cdrhxjrawtftcvip355p7e2e 
#### Address 
> f1gk6ku7nkvip3upyzdit4tznerqba2ty7a2yss6y
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1q6bpjlqia6iemqbrdaxr2uehrhpvoju3qh4lpga
#### Id
> 4978cddb-6aaa-4c08-86c0-4dccc2f6a26b
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceatvvatybkdxciorq2xx2umbreay5cdrhxjrawtftcvip355p7e2e

**Comment by newwebgroup** [comment]
The previous KYC information is relatively complete, and the first round of support

**Comment by newwebgroup** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacectoa4jhebumcvf3zkcfpyjov4oqsv4jk6rw2pk4h4kdnq4cyzbhe 
#### Address 
> f1gk6ku7nkvip3upyzdit4tznerqba2ty7a2yss6y
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1e77zuityhvvw6u2t6tb5qlnsegy2s67qs4lbbbq
#### Id
> 4978cddb-6aaa-4c08-86c0-4dccc2f6a26b
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacectoa4jhebumcvf3zkcfpyjov4oqsv4jk6rw2pk4h4kdnq4cyzbhe

**Comment by herrehesse** [comment]
Dear Applicant,

Due to the increased amount of erroneous/wrong Filecoin+ data recently, on behalf of the entire community, we feel compelled to go deeper into datacap requests. Hereby to ensure that the overall value of the Filecoin network and Filecoin+ program increases and is not abused.

Please answer the questions below as comprehensively as possible.

**Customer data**

- Could you demonstrate exactly how and to what extent customer contact occurred? 

We expect that for the onboarding of customers with the scale of an LDN there would have been at least multiple email and perhaps several chat conversations preceding it. A single email with an agreement does not qualify here.

- Did the customer specify the amount of data involved in this relevant correspondence?

- Why does the customer in question want to use the Filecoin+ program? 

_Should this only be soley for acquiring datacap this is of course **out of the question**. The customer must have a legitimate reason for wanting to use the Filecoin+ program which is intended as a program to store useful and public datasets on the network._ 

- Why is the customer data considered Filecoin+ eligible?

_(As an intermediate solution Filecoin offers the FIL-E program or the glif.io website for business datasets that do not meet the requirements for a Filecoin+ dataset)_


**Files and Processing**

- Could you please demonstrate to us how you envision processing and transporting the customer data in question to any location for preparation?
- Would you demonstrate to us that the customer, the preparer and the intended storage providers all have adequate bandwidth to process the set with its corresponding size?
- Would you tell us how the data set preparer takes into account the prevention of duplicates in order to prevent data cap abuse?


Hopefully you understand the caution the overall community has for onboarding the wrong data. We understand the increased need for Filecoin+, however, we must not allow the program to be misused. Everything depends on a valuable and useful network, let's do our best to make this happen. Together.

**Comment by newwebgroup** [comment]
checker:manualTrigger

**Comment by newwebgroup** [comment]
The CID Checker results look average
The distribution of SPs is not very decentralized

But because it is the second round, I am willing to support it temporarily
Please contact more SPs and list specific improvement plans;
You can use BDE, Slack, Filswan, etc

**Comment by newwebgroup** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced7l26n4ilk2lfilpx6nmmt6rxzglekkr6slb3oo4wdi3xlxfmc7k 
#### Address 
> f1gk6ku7nkvip3upyzdit4tznerqba2ty7a2yss6y
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1e77zuityhvvw6u2t6tb5qlnsegy2s67qs4lbbbq
#### Id
> 6092faa3-8cf1-4338-bfb9-5f01e619aae4
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced7l26n4ilk2lfilpx6nmmt6rxzglekkr6slb3oo4wdi3xlxfmc7k

**Comment by Joss-Hua** [comment]
The round is temporarily supported. For the next round of notaries, please check the report again to understand the rectification.

**Comment by Joss-Hua** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaskqa62knb6vlzhzhyxstl7hrvsdpatmf4a7tvk3eopsmlhv5q64 
#### Address 
> f1gk6ku7nkvip3upyzdit4tznerqba2ty7a2yss6y
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1tfg54zzscugttejv336vivknmsnzzmyudp3t7wi
#### Id
> 6092faa3-8cf1-4338-bfb9-5f01e619aae4
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaskqa62knb6vlzhzhyxstl7hrvsdpatmf4a7tvk3eopsmlhv5q64

**Comment by herrehesse** [comment]
I hereby request an immediate dispute against @newwebgroup. Fraudulent approvals without due diligence.

“ The CID Checker results look average
The distribution of SPs is not very decentralized”

Completely false.
@raghavrmadya @galen-mcandrew @Sunnyiscoming

**Comment by herrehesse** [comment]
@Joss-Hua Why did you sign the application with the CID report showing huge issues and there has been no further client due diligence? 

Love to have clear and open discussion with the client, data packer and storage providers before we continue here.

**Comment by BDEio** [comment]
@fmwxyz Hi! Congratulations on your DataCap approval！
BDE is a trusted deals auction house helping you to get paid storing your data with reliable storage providers. If you need any help, please get in touch.

**Comment by Sunnyiscoming** [comment]
@newwebgroup @Joss-Hua Can you explain about that?

**Comment by Joss-Hua** [comment]
Hi @herrehesse @Sunnyiscoming, 

There is a book in China that contains four words. Through learning them, people can communicate more effectively with each other. They are facts, opinions, positions, and beliefs. It mainly wants to express that communication should be based on "facts" and not on "opinions", because that will lead to conflicts in advance. What's more, if "position" or "belief" is different, it is bound to be a communication with gunpowder.

As one of the notaries, based on the same position as you, for improving the Fil+project and the community, my statement will not have any strange feelings.

To answer your question here, that is why I signed. When I signed the last round, I didn't think there were "huge issues" with it at that time. This is my view.

The fact is, the report shows that,
“ ✔️  Storage provider distribution looks healthy", no exception;
“ ⚠️  100.00% of deals are for data replicated across less than 3 storage providers", more SPs and more replicas are needed to improve dispersion;
“ ⚠️  CID sharing has been observed”, there are very few CID shares;
So the fact is that it has "issues". But it is not "huge". I do not recommend drawing conclusions until there is no universal standard.

Since this LDN was in its early stage, even if there were "issues", I thought it could be improved with the help of the notary, so I supported it because the notary and the governance team need to help the client, not just the trial.

Finally, add: As I said earlier, I will keep looking at this. Now another round has passed, and it has not been improved, so it will not be supported by me.

**Comment by herrehesse** [comment]
@Joss-Hua A clear NO.

There is massive abuse going on inside the program, so trust has to be earned by facts.
You state **it has "issues" but it is not "huge"** I'm sorry but that is not good enough.

Did you do retrieval tests on the stored data? Did you ask for a SP list for distribution? Did you ask for a plan forward?

Help the client ---> make them earn trust ---> then sign & support. This is the path.

**Comment by herrehesse** [comment]
There is massive abuse going on inside the program, so trust has to be earned by facts.

Help the client ---> make them earn trust ---> then sign & support. This is the path.

**Comment by Sunnyiscoming** [comment]
@fmwxyz Can you give us an explanation of the situation?
