### ISSUE TITLE
[DataCap Application] 315XY

### ISSUE THREAD

**Issue by Saeed116** [filecoin-project/filecoin-plus-large-datasets#1045]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: 315XY BuZheng Studio
- Website / Social Media: https://www.315xy.com/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):200TiB
- On-chain address for first allocation:f1jxcq5lm4du5ktt5szlc5wye4udzivaqvswhm6kq

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
The members of Studio BuZheng are a group of elites from various fields, including composers, singers, professional musicians, professional sound control technicians and experienced marketing planners, with rich experience in live show and activity planning, providing one line service from off-stage to on-stage, from hardware to program, as a long-term cooperation team for well-known enterprises.
```

What is the primary source of funding for this project?
```
It is from our company revenue.
```

What other projects/ecosystem stakeholders is this project associated with?
```
No.
```

## Use-case details

Describe the data being stored onto Filecoin
```
We have 600TiB data now. And we need 10 copies.The data we want to store are videos and images of the activities we have participated in.
```

Where was the data in this dataset sourced from?
```
It was from live shows. We recorded every show which  we participated.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
Yes, I put some data into google drive.
https://drive.google.com/drive/folders/1-TcB7lcBU_empsW_SgFWxbipuzosW3br?usp=sharing
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes, I confirm it is a public dataset.
```

What is the expected retrieval frequency for this data?
```
We may retrieve the data once half a year because we'll do a review half a year.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
3-5 years.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Now we are connecting with Sps in North America, Korea, Holland. We plan on making deals in more regions for data security.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
We will choose offline data transfer because we think it is a stable way for us to use. If it is viable, we may also choose online data transfer.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We'll ensure distributed storage so we'll choose diiferent regions to make deals.
We welcome more Sp to cooperate with us.
```

How will you be distributing deals across storage providers?
```
We will distribute no more than 30% deals to every sp.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, we've already prepared resource we need.
```

**Comment by UnionLabs2020** [comment]
Could you verify your identity by sending an email to filplus-app-review@fil.org from your official mailbox?

**Comment by Saeed116** [comment]
Ok!  ![9](https://user-images.githubusercontent.com/108274596/199179993-440defbc-ffb3-4997-be97-412d30ef945a.png)

**Comment by Sunnyiscoming** [comment]
It shows 404 when open https://drive.google.com/drive/folders/1-TcB7lcBU_empsW_SgFWxbipuzosW3br?usp=sharing

**Comment by Saeed116** [comment]
@Sunnyiscoming Thank you for your reminder! This link is now accessible.

**Comment by Saeed116** [comment]
@simonkim0515 Hi Simon, do I need to provide anything else?

**Comment by Sunnyiscoming** [comment]
Please send filplus-app-review@fil.org one more email?

**Comment by Saeed116** [comment]
@Sunnyiscoming Yes, we've resent our email to you.

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 200TiB

**Client address**

>f1jxcq5lm4du5ktt5szlc5wye4udzivaqvswhm6kq

**Comment by MetaWaveInfo** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceahcmikxs3v4xqrsylulxic6q3yfhe2kwsp7r6rr6rnsp224ngajm 
#### Address 
> f1jxcq5lm4du5ktt5szlc5wye4udzivaqvswhm6kq
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1ktlkcxnmzxcdaoqfsunrg3vocfbmgv4n3mrn74a
#### Id
> 17e75d51-145a-4260-8c5a-4438dffd3cf8
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceahcmikxs3v4xqrsylulxic6q3yfhe2kwsp7r6rr6rnsp224ngajm

**Comment by UnionLabs2020** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec5dmfd53eqjj7a4ubc4sifxpixba3urwmx7ggn2gqn7ewge7wl32 
#### Address 
> f1jxcq5lm4du5ktt5szlc5wye4udzivaqvswhm6kq
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f17xdri3wunqgld7dm23e4f3eqsntjakwc47xjo6i
#### Id
> 17e75d51-145a-4260-8c5a-4438dffd3cf8
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec5dmfd53eqjj7a4ubc4sifxpixba3urwmx7ggn2gqn7ewge7wl32

**Comment by Sunnyiscoming** [comment]
Is there any problem with using datacap?

**Comment by cryptowhizzard** [comment]
Hello,

I have tried retrieval from this data but it did not work. Any specific reason why your SP's are blocking retrieval?

When will f02019788 and f01270684 be available for retrieval according to the FIL+ rules?

**Comment by Saeed116** [comment]
![a](https://user-images.githubusercontent.com/108274596/217514386-bbf800da-418f-4047-951d-1bfe3c3bbeb1.jpg)
![b](https://user-images.githubusercontent.com/108274596/217514390-4cdabead-0173-4726-901c-81ce930a8f8e.jpg)
Hello@cryptowhizzard Have you really done it? I just tried and it's normal. Probably your local network has problems.

**Comment by cryptowhizzard** [comment]
Alright, checking again

**Comment by cryptowhizzard** [comment]
cat /var/log/syslog | grep f01935137-f01270684
Feb  8 13:35:04 proposals dealscanner-f01935137-f01270684: Recv 0 B, Paid 0 FIL, Open (New), 0s [1675842797944985733|0]
Feb  8 13:35:04 proposals dealscanner-f01935137-f01270684: Recv 0 B, Paid 0 FIL, DealProposed (WaitForAcceptance), 4ms [1675842797944985733|0]
Feb  8 13:35:06 proposals dealscanner-f01935137-f01270684: Recv 0 B, Paid 0 FIL, DealAccepted (Accepted), 1.753s [1675842797944985733|0]
Feb  8 13:35:06 proposals dealscanner-f01935137-f01270684: Recv 0 B, Paid 0 FIL, PaymentChannelSkip (Ongoing), 1.754s [1675842797944985733|0]
Feb  8 14:05:02 proposals dealscanner-f01935137-f01270684: Recv 0 B, Paid 0 FIL, Open (New), 0s [1675842797944985734|0]
Feb  8 14:05:02 proposals dealscanner-f01935137-f01270684: Recv 0 B, Paid 0 FIL, DealProposed (WaitForAcceptance), 4ms [1675842797944985734|0]
Feb  8 14:05:02 proposals dealscanner-f01935137-f01270684: Recv 0 B, Paid 0 FIL, DealAccepted (Accepted), 300ms [1675842797944985734|0]
Feb  8 14:05:02 proposals dealscanner-f01935137-f01270684: Recv 0 B, Paid 0 FIL, PaymentChannelSkip (Ongoing), 301ms [1675842797944985734|0]


Second attempt works , however it is stuck waiting now. I guess this is because your SP does not keep an unsealed copy of the sectors, right?

**Comment by lvschouwen** [comment]
@Saeed116 
And why haven't you sticked with your DataCap allocation plan?
You mentioned 3 SPs (f01199430 f0106949 f0135078) which you will work with, non of them have sealed a single bit according to the DataCap and CID Checker Report. What happend here?

You mention that no more then 30% of the deal. Why does f02019788 has 36% of the deals?

You mention to work with SPs in North America and Holland. Can you tell us which ones?

2 of the SPs/miners do not have their IP disclosed. Can you work with f02019788 & f01270684 to get this fixed?

**Comment by Saeed116** [comment]
@lvschouwen For well-known reasons, we need to eliminate SPs that do not meet the agreed rules. Even if they are in North America or Holland, all SPs that cannot be connected will be replaced. In addition, I am talking about the complete proportion, which is only the first round.

**Comment by herrehesse** [comment]
@Saeed116 You did not answer any of the questions that @lvschouwen asked.

**Comment by cryptowhizzard** [comment]
I am still looking at the same retrieval problem. It is stalled after:

Feb 21 09:47:38 proposals dealscanner-f01935137-f01270684-24279308: Recv 0 B, Paid 0 FIL, Open (New), 0s [1676890082797772171|0]
Feb 21 09:47:38 proposals dealscanner-f01935137-f01270684-24279308: Recv 0 B, Paid 0 FIL, DealProposed (WaitForAcceptance), 9ms [1676890082797772171|0]
Feb 21 09:47:39 proposals dealscanner-f01935137-f01270684-24279308: Recv 0 B, Paid 0 FIL, DealAccepted (Accepted), 331ms [1676890082797772171|0]
Feb 21 09:47:39 proposals dealscanner-f01935137-f01270684-24279308: Recv 0 B, Paid 0 FIL, PaymentChannelSkip (Ongoing), 331ms [1676890082797772171|0]

I will close this issue in my dashboard for now. When the retrieval works , please message me so i can check again.

**Comment by Protocan** [comment]
checker:manualTrigger

**Comment by Protocan** [comment]
Looks normal and acceptable, willing to support.

**Comment by Protocan** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacea5ke56zgiisgxwbodxmj3yn33lkjl5vkmfgp4ihmfkpyexpxvegy 
#### Address 
> f1jxcq5lm4du5ktt5szlc5wye4udzivaqvswhm6kq
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1vxbqrf7rfum3n6m5u6eb4re6xj7amvsaqnzu64y
#### Id
> 5073018d-5f95-40c6-8d6b-4e1ddf71b48f
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacea5ke56zgiisgxwbodxmj3yn33lkjl5vkmfgp4ihmfkpyexpxvegy

**Comment by Protocan** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebjuc5ih2vare544a6norkzpllffzauh4cyxl32laajtk2rpvydp6 
#### Address 
> f1jxcq5lm4du5ktt5szlc5wye4udzivaqvswhm6kq
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1vxbqrf7rfum3n6m5u6eb4re6xj7amvsaqnzu64y
#### Id
> 5073018d-5f95-40c6-8d6b-4e1ddf71b48f
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebjuc5ih2vare544a6norkzpllffzauh4cyxl32laajtk2rpvydp6

**Comment by BobbyChoii** [comment]
The applicant contacted me via DM and the bot check results looks good. willing to support

**Comment by BobbyChoii** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecbpnwoufuj6df5f3woupcrrsort437vcyafte4hgfp5rbr4wnl4u 
#### Address 
> f1jxcq5lm4du5ktt5szlc5wye4udzivaqvswhm6kq
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1irqs2gmctiv3jcdfwuch7oxvf4ixh3k4b2wc24i
#### Id
> 5073018d-5f95-40c6-8d6b-4e1ddf71b48f
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecbpnwoufuj6df5f3woupcrrsort437vcyafte4hgfp5rbr4wnl4u

**Comment by Aifabot-Cloud** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacealmhi6jwkhamt2g5dftxjp63buiavolmty55q2peyyfvkygur55e 
#### Address 
> f1jxcq5lm4du5ktt5szlc5wye4udzivaqvswhm6kq
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f174fg3bqbln3zjnkxtyf6s54txqkr7yqkj6cig7y
#### Id
> b0075bc1-b83d-47ee-9d71-b304f8fba0ff
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacealmhi6jwkhamt2g5dftxjp63buiavolmty55q2peyyfvkygur55e

**Comment by Aifabot-Cloud** [comment]
Good summary report and ongoing communication from the applicant. We would like to see more and more useful datasets get onboarded.

**Comment by Casey-PG** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedzkjcoby2qws5242wwkcy4w34y4zrfha6ph44udhgf7pfhdwd76o 
#### Address 
> f1jxcq5lm4du5ktt5szlc5wye4udzivaqvswhm6kq
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1d4yb3wags3mtddzesxoo63jv7dmlec3bq4yteni
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedzkjcoby2qws5242wwkcy4w34y4zrfha6ph44udhgf7pfhdwd76o

**Comment by Casey-PG** [comment]
Public data, complaint allocation plan. Willing to support.

**Comment by Ewesion** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebya7ayanbvfv5ssb7lfugmovv7bpb346gdmikxhieadkmk3xpa2g 
#### Address 
> f1jxcq5lm4du5ktt5szlc5wye4udzivaqvswhm6kq
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1ihv7gz3vn3xqvikpt4rwryecgisl7745lodx3yi
#### Id
> c5f02613-f924-40a2-8ce3-9f04d604d079
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebya7ayanbvfv5ssb7lfugmovv7bpb346gdmikxhieadkmk3xpa2g

**Comment by BobbyChoii** [comment]
checker:manualTrigger

**Comment by BobbyChoii** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedq5c3biqwp2z2ehjxhhj5kjhqh3cckz6twhz33e5biuxdvlgj3lg 
#### Address 
> f1jxcq5lm4du5ktt5szlc5wye4udzivaqvswhm6kq
#### Datacap Allocated
> 1.56PiB
#### Signer Address
> f1irqs2gmctiv3jcdfwuch7oxvf4ixh3k4b2wc24i
#### Id
> 529c8c09-e932-4160-9b84-eb766753eeed
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedq5c3biqwp2z2ehjxhhj5kjhqh3cckz6twhz33e5biuxdvlgj3lg

**Comment by Aifabot-Cloud** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedkjspkjha7y427b5o25esic6gz3i6oygk4ihvbj35oxz2sclcye2 
#### Address 
> f1jxcq5lm4du5ktt5szlc5wye4udzivaqvswhm6kq
#### Datacap Allocated
> 1.56PiB
#### Signer Address
> f174fg3bqbln3zjnkxtyf6s54txqkr7yqkj6cig7y
#### Id
> 529c8c09-e932-4160-9b84-eb766753eeed
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedkjspkjha7y427b5o25esic6gz3i6oygk4ihvbj35oxz2sclcye2

**Comment by Aifabot-Cloud** [comment]
Open datasets bring great value to the network. Happy to see more of them join Filecoin. Please keep the allocation in line with Filplus guidlines.

**Comment by Suyanj** [comment]
checker:manualTrigger

**Comment by Suyanj** [comment]
![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/107249346/29173471-a63d-47c1-a9b9-9f7471d61249)

**Comment by Suyanj** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecepaejiuaahihwauhm3mxrnvoxmy7q5rwnwtrpojbfmgcu6g3wsa 
#### Address 
> f1jxcq5lm4du5ktt5szlc5wye4udzivaqvswhm6kq
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1ihv7gz3vn3xqvikpt4rwryecgisl7745lodx3yi
#### Id
> 8c222d29-f1fc-450e-8e5e-505787ce8258
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecepaejiuaahihwauhm3mxrnvoxmy7q5rwnwtrpojbfmgcu6g3wsa

**Comment by cryptowhizzard** [comment]
http retrieval statistics are unreliable at the moment.

**Comment by cryptowhizzard** [comment]
@filplus-govteam

This application is signed with the need governance label present. Secondly no graphsync retrievals possible

**Comment by cryptowhizzard** [comment]
![Scherm­afbeelding 2023-07-31 om 08 24 34](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/36404435/38ac0b9d-0d64-40a9-a07c-cadb4735c596)

**Comment by Saeed116** [comment]
I’ve changed some words from my application last week. After that, my application was put label [governance review needed](https://github.com/filecoin-project/filecoin-plus-large-datasets/labels/governance%20review%20needed) by bot automatically. Isn't it the error of bot? Why did you think that my application has problem or can not be sign? @cryptowhizzard @filplus-govteam

**Comment by cryptowhizzard** [comment]
The reason i disputed is because the SP's you work with have been flagged overal the Fil+ system for abuse/CID sharing and non-retrievability. Both are against Fil+ rules and guidelines.

You got a notary signature where you should not have had one, reason i filed a dispute.

![Scherm­afbeelding 2023-08-03 om 13 57 13](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/36404435/d34d06b3-c709-45b9-9fa2-83012ec533f8)

**Comment by Saeed116** [comment]
@cryptowhizzard 

CID sharing is completely out of control for SPs, and it is something that belongs to DPs or Clients whose applications have problem to review.

I will take responsibility for my application and if you don't see CID Sharing in my report, please don't post misleading comments.

**Comment by cryptowhizzard** [comment]
> @cryptowhizzard
> 
> CID sharing is completely out of control for SPs, and it is something that belongs to DPs or Clients whose applications have problem to review.
> 
> I will take responsibility for my application and if you don't see CID Sharing in my report, please don't post misleading comments.

Well, if it were to be one SP i could give you credit, or perhaps 2. Not a dozen?

You are responsible for selecting SP's who support retrieval according to your declaration in the top of the LDN where you state what everyone is able to retrieve this data. These SP's do not support retrieval apart from the abuse.

**Comment by Saeed116** [comment]
![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/108274596/dcbf02f3-b0e1-4b9d-929d-c6222f5dbdd8)
@Carohere Can you please help me with the same problem as Janice? I'm the one who sent you message in slack.

**Comment by cryptowhizzard** [comment]
@Saeed116 

May i suggest that you help yourself first before asking another notary. 
Contact your SP's and make sure they enable retrieval. When that is proper your application can continue?

**Comment by Saeed116** [comment]
@cryptowhizzard 

The SPs do support retrieval.

![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/108274596/8edc2896-a7a2-4f0a-98cc-eb5f3abe9ddc)

**Comment by Carohere** [comment]
@Saeed116 If there are no problem in your application, it is no need to respond to those irrelevant. I can sign for you since your application's report seems good.

**Comment by cryptowhizzard** [comment]
Here find the log file of the retrieval attempt. After a while the retrieval stops ( aborted on the SP side ) and then restarts.
This is a typical way of circumventing the retrieval bot while still nothing can be downloaded to do due diligence on.

[1045.log.zip](https://github.com/filecoin-project/filecoin-plus-large-datasets/files/12260624/1045.log.zip)

@Carohere appreciate you won't respond, however this application is under dispute until retrieval is proper.

@Saeed116 
I am willing to revoke the dispute if you can provide me with pieceCID baga6ea4seaqira2newcpfkoqxnjfyubq6zu6jdsdk3e2zcceh4ilr27x4wciaei and make it available on a link where i can download it + unpack your data to review the content.
