### ISSUE TITLE
[DataCap Application]  - Blockchain Media

### ISSUE THREAD

**Issue by ghost** [filecoin-project/filecoin-plus-large-datasets#1046]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Blockchain Media
- Website / Social Media:https://www.youtube.com/channel/UCa1wzM7n6YNpptxR6s6xezw
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):100TiB
- On-chain address for first allocation:f1tlouhnkamaahz34f5nn4h7ptrayr46w7tjjpd7i

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
After I met blockchain in 2016, I was deeply attracted by this decentralized world At that time I hope that the development of blockchain technology can change the status quo of news, Then I created Media Blockchain in 2019 to bring cryptocurrency news in an interesting way, and have uploaded more than 5,000 videos on major media platforms. I also published the book “Several Pitfalls in BlockChain” in 2020 Media Blockchain was created to bring you the best tips, tutorials and ideas to help you learn how to become a successful investor We are here to continue to promote cryptocurrency adoption to the masses.
```

What is the primary source of funding for this project?
```
business income
```

What other projects/ecosystem stakeholders is this project associated with?
```
Nope
```

## Use-case details

Describe the data being stored onto Filecoin
```
Three main types of the content which needs to be stored
1. The videos/live tetecast I made and posted in YouTube
2. Course video (local meetings in SH/HZ, AMA)                                                                                                                                         
3. The videos in other potential platforms in China
```

Where was the data in this dataset sourced from?
```
videos/live telecast record produced by my team.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://www.youtube.com/watch?v=scYRgcJJdI4                                                                                     
https://www.youtube.com/watch?v=BCjnJCHAGQk  
https://www.youtube.com/watch?v=IRP5rs9DZCo                                                                                   
https://www.youtube.com/watch?v=ALR4DAMtUvo                                                                                
https://www.youtube.com/watch?v=rY-Di1YpKTE                                                                                    
https://www.youtube.com/watch?v=v31-IwCzyRU                                                                                  
https://www.youtube.com/watch?v=obEwnNItR-A                                                                                  
https://www.youtube.com/watch?v=u9N7zyGquro                                                                                 
https://www.youtube.com/watch?v=BxpFwBk6yCo                                                                                 
https://www.youtube.com/watch?v=Ob3fSMmNCr0
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
yes
```

What is the expected retrieval frequency for this data?
```
almost everyday
```

For how long do you plan to keep this dataset stored on Filecoin?
```
at least 5 years
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
globally
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
offline
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
Network stability and fast retrieval from SPs' support will be preferentially considered.
```

How will you be distributing deals across storage providers?
```
distribute as equally as possible
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
yes. we have prepared a fund for this project.
```

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 100TiB

**Client address**

>f1tlouhnkamaahz34f5nn4h7ptrayr46w7tjjpd7i

**Comment by Sunnyiscoming** [comment]
Hey, Blockchain Media. If you still want to apply for datacap, you can ask notaries to do client due diligence in slack channel. https://app.slack.com/client/TEHTVS1L6/C036JKD8NVA/thread/C03BG1MNQ4T-1673888660.823499
