### ISSUE TITLE
[DataCap Application] - Blockchain Media

### ISSUE THREAD

**Issue by Michaelglobalweb3** [filecoin-project/filecoin-plus-large-datasets#1048]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Blockchain Media
- Website / Social Media:https://www.youtube.com/channel/UCa1wzM7n6YNpptxR6s6xezw
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):100TiB
- On-chain address for first allocation:f1mgvvj45ce5i3ikpyixtubqzcytcgmdlwgjldqri

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
After I met blockchain in 2016, I was deeply attracted by this decentralized world At that time I hope that the development of blockchain technology can change the status quo of news, Then I created Media Blockchain in 2019 to bring cryptocurrency news in an interesting way, and have uploaded more than 5,000 videos on major media platforms. I also published the book “Several Pitfalls in BlockChain” in 2020 Media Blockchain was created to bring you the best tips, tutorials and ideas to help you learn how to become a successful investor We are here to continue to promote cryptocurrency adoption to the masses.```

What is the primary source of funding for this project?
```
business income
```

What other projects/ecosystem stakeholders is this project associated with?
```
not yet.
```

## Use-case details

Describe the data being stored onto Filecoin
```
There are three main types of the content which needs to be stored
1. The videos/live tetecast I made and posted in YouTube
2. Course video (local meetings in SH/HZ, AMA)                                                                                                                                         
3. The videos in other potential platforms in China
```

Where was the data in this dataset sourced from?
```
videos/live telecast record produced by my team.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://www.youtube.com/watch?v=scYRgcJJdI4                                                                                     
https://www.youtube.com/watch?v=BCjnJCHAGQk                                                                                 
https://www.youtube.com/watch?v=IRP5rs9DZCo                                                                                   
https://www.youtube.com/watch?v=ALR4DAMtUvo                                                                                
https://www.youtube.com/watch?v=rY-Di1YpKTE                                                                                    
https://www.youtube.com/watch?v=v31-IwCzyRU                                                                                  
https://www.youtube.com/watch?v=obEwnNItR-A                                                                                  
https://www.youtube.com/watch?v=u9N7zyGquro                                                                                 
https://www.youtube.com/watch?v=BxpFwBk6yCo                                                                                 
https://www.youtube.com/watch?v=Ob3fSMmNCr0
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
yes
```

What is the expected retrieval frequency for this data?
```
almost everyday
```

For how long do you plan to keep this dataset stored on Filecoin?
```
at least 5 years
```


## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
globally
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
offline
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
Network stability and fast retrieval from SPs' support will be preferentially considered.
```

How will you be distributing deals across storage providers?
```
distribute as equally as possible
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
yes. we have prepared a fund for this project.
```

**Comment by raghavrmadya** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 100TiB

**Client address**

>f1mgvvj45ce5i3ikpyixtubqzcytcgmdlwgjldqri

**Comment by raghavrmadya** [comment]
The applicant has confirmed relationship with the organization on slack. Safe to proceed but notaries are encouraged to do due diligence on the data set and data distribution plan.

**Comment by kernelogic** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebq5unpkvtpagrrq4bsfp6d244dsh6lcrgmhutok6eakp2nyjz6ts 
#### Address 
> f1mgvvj45ce5i3ikpyixtubqzcytcgmdlwgjldqri
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebq5unpkvtpagrrq4bsfp6d244dsh6lcrgmhutok6eakp2nyjz6ts

**Comment by liyunzhi-666** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecdtyyx6zu432cbsfzpbutbqi5amccckv66fxayyyqgdevjlghgwk 
#### Address 
> f1mgvvj45ce5i3ikpyixtubqzcytcgmdlwgjldqri
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1pszcrsciyixyuxxukkvtazcokexbn54amf7gvoq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecdtyyx6zu432cbsfzpbutbqi5amccckv66fxayyyqgdevjlghgwk

**Comment by BigD-Exchange** [comment]
@Michaelglobalweb3 Hi! Great to see you have gotten approval for DataCap and advancing the mission of preserving humanity’s most important information. If you are looking for storage providers to store these data or have any questions, please visit #bigdata-exchange on Filecoin Slack or reply here. 

We have strong demand from a diverse group of SPs, who are actively looking to onboard more data.

**Comment by kernelogic** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecwjtwou5fz4z2a63pozi27gzuimeohm7xyqul3sgcp3g3yqppjw4 
#### Address 
> f1mgvvj45ce5i3ikpyixtubqzcytcgmdlwgjldqri
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecwjtwou5fz4z2a63pozi27gzuimeohm7xyqul3sgcp3g3yqppjw4

**Comment by Joss-Hua** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacea42lomwhhkzpezecjpsmu23vshpkf6oafkevhvu47bappxcebr72 
#### Address 
> f1mgvvj45ce5i3ikpyixtubqzcytcgmdlwgjldqri
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1tfg54zzscugttejv336vivknmsnzzmyudp3t7wi
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacea42lomwhhkzpezecjpsmu23vshpkf6oafkevhvu47bappxcebr72

**Comment by NDLABS-OFFICE** [comment]
Top provider is reasonable, I would like to support.
It is recommended to find more SPs.

**Comment by NDLABS-OFFICE** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebjhgmmmoi7hk4qymja5k5zrbrod3t2ufchkemydsamfsycab4edy 
#### Address 
> f1mgvvj45ce5i3ikpyixtubqzcytcgmdlwgjldqri
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1yayfsv6whu3rheviucvventj3y6t542xfpb47ei
#### Id
> 1aba4d5b-db10-493c-8673-e0f1a0d72981
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebjhgmmmoi7hk4qymja5k5zrbrod3t2ufchkemydsamfsycab4edy

**Comment by Defil2022** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb3uy7gwxdpzekwx3cdumgkmwt32kpigcum46wgj4jtx3q6cqosvc 
#### Address 
> f1mgvvj45ce5i3ikpyixtubqzcytcgmdlwgjldqri
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1dnb3uz7sylxk6emti3ififcvu3nlufnnsjui6ea
#### Id
> 1aba4d5b-db10-493c-8673-e0f1a0d72981
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb3uy7gwxdpzekwx3cdumgkmwt32kpigcum46wgj4jtx3q6cqosvc

**Comment by filplus-checker** [comment]
## DataCap and CID Checker Report[^1]
 - Organization: `Blockchain Media`
 - Client: `f1mgvvj45ce5i3ikpyixtubqzcytcgmdlwgjldqri`
### Storage Provider Distribution
The below table shows the distribution of storage providers that have stored data for this client.

If this is the first time a provider takes verified deal, it will be marked as `new`.

For most of the datacap application, below restrictions should apply.
 - Storage provider should not exceed 25% of total datacap.
 - Storage provider should not be storing duplicate data for more than 20%.
 - Storage provider should have published its public IP address.
 - All storage providers should be located in different regions.

⚠️ [f01943959](https://filfox.info/en/address/f01943959) has sealed 29.12% of total datacap.

⚠️ 87.27% of total deal sealed by [f01943959](https://filfox.info/en/address/f01943959) are duplicate data.

⚠️ [f01943959](https://filfox.info/en/address/f01943959) has unknown IP location.

⚠️ [f01384160](https://filfox.info/en/address/f01384160) has sealed 25.67% of total datacap.

⚠️ 82.80% of total deal sealed by [f01384160](https://filfox.info/en/address/f01384160) are duplicate data.

⚠️ 86.86% of total deal sealed by [f01853077](https://filfox.info/en/address/f01853077) are duplicate data.

⚠️ 83.11% of total deal sealed by [f01834291](https://filfox.info/en/address/f01834291) are duplicate data.

⚠️ 74.28% of total deal sealed by [f01893023](https://filfox.info/en/address/f01893023) are duplicate data.

⚠️ 66.90% of total deal sealed by [f01384209](https://filfox.info/en/address/f01384209) are duplicate data.

⚠️ 62.16% of total deal sealed by [f01271208](https://filfox.info/en/address/f01271208) are duplicate data.

⚠️ 73.06% of total deal sealed by [f01215819](https://filfox.info/en/address/f01215819) are duplicate data.

| Provider                                              |                    Location | Total Deals Sealed | Percentage | Unique Data | Duplicate Deals |
| :---------------------------------------------------- | --------------------------: | -----------------: | ---------: | ----------: | --------------: |
| [f01943959](https://filfox.info/en/address/f01943959) |                     Unknown |          40.00 TiB |     29.12% |    5.09 TiB |          87.27% |
| [f01384160](https://filfox.info/en/address/f01384160) |     Shenzhen, Guangdong, CN |          35.25 TiB |     25.67% |    6.06 TiB |          82.80% |
| [f01853077](https://filfox.info/en/address/f01853077) |    Singapore, Singapore, SG |          15.94 TiB |     11.60% |    2.09 TiB |          86.86% |
| [f01834291](https://filfox.info/en/address/f01834291) | Los Angeles, California, US |          13.69 TiB |      9.97% |    2.31 TiB |          83.11% |
| [f01893023](https://filfox.info/en/address/f01893023) | Los Angeles, California, US |           9.72 TiB |      7.08% |    2.50 TiB |          74.28% |
| [f01384209](https://filfox.info/en/address/f01384209) |     Shenzhen, Guangdong, CN |           8.97 TiB |      6.53% |    2.97 TiB |          66.90% |
| [f01271208](https://filfox.info/en/address/f01271208) |     Shenzhen, Guangdong, CN |           6.94 TiB |      5.05% |    2.63 TiB |          62.16% |
| [f01215819](https://filfox.info/en/address/f01215819) |     Shenzhen, Guangdong, CN |           6.84 TiB |      4.98% |    1.84 TiB |          73.06% |

![Provider Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/1048/1671098413695.png)
### Deal Data Replication
The below table shows how each many unique data are replicated across storage providers.
- No more than 25% of unique data are stored with less than 4 providers.

⚠️ 100.00% of deals are for data replicated across less than 4 storage providers.

| Unique Data Size | Total Deals Made | Number of Providers | Deal Percentage |
| ---------------: | ---------------: | ------------------: | --------------: |
|        20.19 TiB |       123.34 TiB |                   1 |          89.81% |
|         2.66 TiB |        14.00 TiB |                   2 |          10.19% |

![Replication Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/1048/1671098414315.png)
### Deal Data Shared with other Clients
The below table shows how many unique data are shared with other clients.
Usually different applications owns different data and should not resolve to the same CID.

⚠️ CID sharing has been observed.

| Other Client                                                                                                          | Application                                                                                                        | Total Deals Affected | Unique CIDs |        Verifier |
| :-------------------------------------------------------------------------------------------------------------------- | :----------------------------------------------------------------------------------------------------------------- | -------------------: | ----------: | --------------: |
| [f1ji2xty4dtg2a4pfnslltkw7pbhy76kvihizkfmq](https://filfox.info/en/address/f1ji2xty4dtg2a4pfnslltkw7pbhy76kvihizkfmq) | `Pow Power`                                                                                                        |            31.09 TiB |         188 | LDN v3 multisig |
| [f1vajbbihmcqkcjlnicmjto6fflklvhoifips7uzq](https://filfox.info/en/address/f1vajbbihmcqkcjlnicmjto6fflklvhoifips7uzq) | `rctAI`                                                                                                            |            23.06 TiB |         148 | LDN v3 multisig |
| [f1o2nxreefzqzc2mvaqneaolpdat5yk3275r6rofa](https://filfox.info/en/address/f1o2nxreefzqzc2mvaqneaolpdat5yk3275r6rofa) | [iPolloverse SG PTE\. LTD](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/767)            |             8.72 TiB |          55 | LDN v3 multisig |
| [f1ng6g57r4u62q67u6lm33ftijfsggyzzjzb2l4cy](https://filfox.info/en/address/f1ng6g57r4u62q67u6lm33ftijfsggyzzjzb2l4cy) | [NFTSTAR](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/960)                             |             6.44 TiB |          50 | LDN v3 multisig |
| [f13fjnwckkgnkbpapcmnpupbdf4ohduomdso4eqga](https://filfox.info/en/address/f13fjnwckkgnkbpapcmnpupbdf4ohduomdso4eqga) | [Asia Blockchain Gaming Alliance](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/872)     |             4.53 TiB |          37 | LDN v3 multisig |
| [f13wvg4xve7nz3nev4bi2c7imod7lelstxfwwzjgi](https://filfox.info/en/address/f13wvg4xve7nz3nev4bi2c7imod7lelstxfwwzjgi) | [We Doctor](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/962)                           |             4.13 TiB |          32 | LDN v3 multisig |
| [f16w5d2u57ndts6wcqupwwvrl7ewicrl5xnymfxui](https://filfox.info/en/address/f16w5d2u57ndts6wcqupwwvrl7ewicrl5xnymfxui) | `Maoyoo Network`                                                                                                   |             3.09 TiB |          39 | LDN v3 multisig |
| [f1fsoyq7oiwdaapagpnlncbohkrkzolxxzkex6hxq](https://filfox.info/en/address/f1fsoyq7oiwdaapagpnlncbohkrkzolxxzkex6hxq) | [SemiDrive Technology](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/911)                |             2.63 TiB |          21 | LDN v3 multisig |
| [f1u3rzf5re6nvnyjjixcmbk5tderq55vjhudmapny](https://filfox.info/en/address/f1u3rzf5re6nvnyjjixcmbk5tderq55vjhudmapny) | [ Nswap](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/882)                              |             1.53 TiB |          13 | LDN v3 multisig |
| [f1dfkdmjhuvvol6okun57mix447wdpolwcd323ktq](https://filfox.info/en/address/f1dfkdmjhuvvol6okun57mix447wdpolwcd323ktq) | [BITRISE CAPITAL FOUNDATION PTE\.LTD](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/139) |           640.00 GiB |           3 |       LDN # 139 |
| [f1ocw63vnfpg3lkhiqxtzvzqke4d42km6ow3shkba](https://filfox.info/en/address/f1ocw63vnfpg3lkhiqxtzvzqke4d42km6ow3shkba) | `M Space`                                                                                                          |           352.00 GiB |           4 | LDN v3 multisig |
| [f1guplg5wyjdn6bv4forsb5eu2lohexvdlttkavpq](https://filfox.info/en/address/f1guplg5wyjdn6bv4forsb5eu2lohexvdlttkavpq) | [Ipollo](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/168)                              |           320.00 GiB |           1 |       LDN # 168 |
| [f1gmiepn73zoa5gz2oiqyugjmrsecwj5qxd42vmyi](https://filfox.info/en/address/f1gmiepn73zoa5gz2oiqyugjmrsecwj5qxd42vmyi) | ``                                                                                                                 |           288.00 GiB |           1 | LDN v3 multisig |
| [f1hkvuvlwgzsgxnyet3wb4w2s3fyujvtkgeizdaey](https://filfox.info/en/address/f1hkvuvlwgzsgxnyet3wb4w2s3fyujvtkgeizdaey) | [Blue Storm Information Technology](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/323)   |            32.00 GiB |           1 | LDN v3 multisig |

[^1]: To manually trigger this report, add a comment with text `checker:manualTrigger`

**Comment by Sunnyiscoming** [comment]
Hi, please explain the abnormal information.
