### ISSUE TITLE
[DataCap Application] Brazil data for Drust-Agee

### ISSUE THREAD

**Issue by Agee-Drust** [filecoin-project/filecoin-plus-large-datasets#1050]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Drust
- Website / Social Media:n/a
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):100TiB
- On-chain address for first allocation:f1xskwjewhafb6db23zrhh2uok4kxitcr47acwhgi

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
I'm a member in Filecoin, but I have ambitious with Filecoin and Filecoin slingshot about ensuring meaningful data is stored and retrieved from the Filecoin Network.
```

What is the primary source of funding for this project?
```
My own source.
```

What other projects/ecosystem stakeholders is this project associated with?
```
No
```

## Use-case details

Describe the data being stored onto Filecoin
```
Earth Observation Data Cubes for Brazil - Sentinel 2A/2B Earth Observation Data Cubes for Brazil - CBERS 4
Notifications for new EO Data Cubes Sentinel-2 scenes
Notifications for new EO Data Cubes CBERS scenes
```

Where was the data in this dataset sourced from?
```
The data is from AWS Open dataset.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://registry.opendata.aws/brazil-data-cubes/
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
I confirm. This is a open dataset.
```

What is the expected retrieval frequency for this data?
```
Follow LDN Application rules. 1-2 times half a year.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
More than 1 year.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
All regions. 
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
After CAR files are ready, I will upload it to the server for SP, or I will prepare disks. Then I will propose offline deals after they get files.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
I plan to make deals with SPs that support data retrieval and have stable sealing rate. Also, I welcome every one who are interested with this deal.
```

How will you be distributing deals across storage providers?
```
Try to make every SP under 25% of deals.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Enough.
```

**Comment by raghavrmadya** [comment]
Who are the SPs you have reached out/plan to store? Please share IDs

**Comment by Agee-Drust** [comment]
@raghavrmadya Hi, I've been in touch with SPs in USA, Korea, Sinapore, Japan. f01895783, f01917257, f01917241, f01924325

**Comment by MetaWaveInfo** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceagexonhzitgg73ciuqzjp4of4gt7gvio2d3lohml3jdqcqrzqquq 
#### Address 
> f1xskwjewhafb6db23zrhh2uok4kxitcr47acwhgi
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1ktlkcxnmzxcdaoqfsunrg3vocfbmgv4n3mrn74a
#### Id
> 4a12738c-fc7a-4535-8f1d-5b306e14966e
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceagexonhzitgg73ciuqzjp4of4gt7gvio2d3lohml3jdqcqrzqquq

**Comment by swatchliu** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec2fbuw34iqcnpziyyzz7pnx335z352ecmy6wov7mdcboaniuejsi 
#### Address 
> f1xskwjewhafb6db23zrhh2uok4kxitcr47acwhgi
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1yh6q3nmsg7i2sys7f7dexcuajgoweudcqj2chfi
#### Id
> 4a12738c-fc7a-4535-8f1d-5b306e14966e
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec2fbuw34iqcnpziyyzz7pnx335z352ecmy6wov7mdcboaniuejsi

**Comment by Sunnyiscoming** [comment]
Is there any problem with using datacap?

**Comment by Suyanj** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec4iktic2ku7ydnsabdm2j2ablw27xdwedhtlhwfmohcqitllclvo 
#### Address 
> f1xskwjewhafb6db23zrhh2uok4kxitcr47acwhgi
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1ihv7gz3vn3xqvikpt4rwryecgisl7745lodx3yi
#### Id
> feb9ecba-bcd3-4ee9-8fe4-8d2e977f0592
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec4iktic2ku7ydnsabdm2j2ablw27xdwedhtlhwfmohcqitllclvo

**Comment by Suyanj** [comment]
Public data with clear allocation plan, we are willing to help onboard more valuable dataset.

**Comment by Casey-PG** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedjb5p65vpbto7qw5l3rowmgtdzlh62arq2eajysmvlcrqnkxlbhu 
#### Address 
> f1xskwjewhafb6db23zrhh2uok4kxitcr47acwhgi
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1d4yb3wags3mtddzesxoo63jv7dmlec3bq4yteni
#### Id
> 2a68a6b8-9c73-450c-bf1d-c578651b5132
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedjb5p65vpbto7qw5l3rowmgtdzlh62arq2eajysmvlcrqnkxlbhu

**Comment by AthSmith** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebboeaphadvvlvms5s2tbgn7s6rzzguzy2xxak2bczomlgy2ndpog 
#### Address 
> f1xskwjewhafb6db23zrhh2uok4kxitcr47acwhgi
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1vxbqrf7rfum3n6m5u6eb4re6xj7amvsaqnzu64y
#### Id
> 2a68a6b8-9c73-450c-bf1d-c578651b5132
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebboeaphadvvlvms5s2tbgn7s6rzzguzy2xxak2bczomlgy2ndpog

**Comment by Meibuy** [comment]
checker:manualTrigger

**Comment by Meibuy** [comment]
![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/108273047/8b9bbb2e-fcf7-475e-bd07-d8b512ac2eac)

**Comment by Meibuy** [comment]
LGTM, should pay attention to Deal Data Replication in the next round. willing to support! @Agee-Drust

**Comment by Meibuy** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecdet7zyttjeqr6cb62tesvekit673enrtdujpzqh2s3gjao46z6k 
#### Address 
> f1xskwjewhafb6db23zrhh2uok4kxitcr47acwhgi
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1bwugfihrmn3iyunzyxst5nttql3dge4khwmurtq
#### Id
> 4208a145-2fb8-4c21-bcc0-b3197edf9379
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecdet7zyttjeqr6cb62tesvekit673enrtdujpzqh2s3gjao46z6k

**Comment by TakiChain** [comment]
It's good to see that the data is indeed improving all the time, and hope it continues to do so!

**Comment by TakiChain** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced2hsh4rddih6ecjdnyecebowegfj3g2wp3b6dm76iccibmg5oi4y 
#### Address 
> f1xskwjewhafb6db23zrhh2uok4kxitcr47acwhgi
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f15impf3j2zcaex4lhyxndxswuuhv24vzstuqtxsi
#### Id
> 4208a145-2fb8-4c21-bcc0-b3197edf9379
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced2hsh4rddih6ecjdnyecebowegfj3g2wp3b6dm76iccibmg5oi4y

**Comment by Wengeding** [comment]
checker:manualTrigger

**Comment by Wengeding** [comment]
So far the report looks good,  we'll keep tracking the datacap allocation flow.

**Comment by Wengeding** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecsa22apyycrpm2lrou2x6lhxrsu7bt2yelkkijkqj75typ53j4h6 
#### Address 
> f1xskwjewhafb6db23zrhh2uok4kxitcr47acwhgi
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1txfsjmix4vlzido4dkildrnbw26owtlbslexmpa
#### Id
> 8c974cbb-807a-4cc7-8bb3-9803d4cb46df
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecsa22apyycrpm2lrou2x6lhxrsu7bt2yelkkijkqj75typ53j4h6

**Comment by BobbyChoii** [comment]
Based on the chat history and fellow notaries' reviews, I would like to help this application moving forward as your report is normal.

**Comment by BobbyChoii** [comment]
checker:manualTrigger

**Comment by BobbyChoii** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecryiejipbnnoas5u4k5bvk7kifodv7ewmi4kcm5iveo7jt3n6w5y 
#### Address 
> f1xskwjewhafb6db23zrhh2uok4kxitcr47acwhgi
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1irqs2gmctiv3jcdfwuch7oxvf4ixh3k4b2wc24i
#### Id
> 8c974cbb-807a-4cc7-8bb3-9803d4cb46df
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecryiejipbnnoas5u4k5bvk7kifodv7ewmi4kcm5iveo7jt3n6w5y

**Comment by Agee-Drust** [comment]
Keep open!

**Comment by Agee-Drust** [comment]
Keep open!

**Comment by Casey-PG** [comment]
checker:manualTrigger

**Comment by Casey-PG** [comment]
Deal Data Replication should be improved. The other scores are accepted.

**Comment by Casey-PG** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecp7o3qm7o2snquomxjrn2bhyxmexndbe3yqzvidur4ddtyjkfcny 
#### Address 
> f1xskwjewhafb6db23zrhh2uok4kxitcr47acwhgi
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1d4yb3wags3mtddzesxoo63jv7dmlec3bq4yteni
#### Id
> 783e1e74-3405-4ba8-8f9f-3f1118d3762d
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecp7o3qm7o2snquomxjrn2bhyxmexndbe3yqzvidur4ddtyjkfcny

**Comment by AthSmith** [comment]
LGTM，willing to support

**Comment by AthSmith** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb3ipma2665qh7ebrvcprmyjly2xzzotouc4wkawz2qsnagjikzaa 
#### Address 
> f1xskwjewhafb6db23zrhh2uok4kxitcr47acwhgi
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1vxbqrf7rfum3n6m5u6eb4re6xj7amvsaqnzu64y
#### Id
> 783e1e74-3405-4ba8-8f9f-3f1118d3762d
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb3ipma2665qh7ebrvcprmyjly2xzzotouc4wkawz2qsnagjikzaa

**Comment by Bennyyangpu** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedoegrnltxfrd2cyx2dsehsenvbzpzsknkl33ogc6m4n63wy3wmn2 
#### Address 
> f1xskwjewhafb6db23zrhh2uok4kxitcr47acwhgi
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f174fg3bqbln3zjnkxtyf6s54txqkr7yqkj6cig7y
#### Id
> 783e1e74-3405-4ba8-8f9f-3f1118d3762d
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedoegrnltxfrd2cyx2dsehsenvbzpzsknkl33ogc6m4n63wy3wmn2

**Comment by PluskitOfficial** [comment]
Looks good. Willing to support.

**Comment by PluskitOfficial** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb2tjsupwf7m2hnln4usei6ptph6cotr5jiob2wdhiy57fkksq2kq 
#### Address 
> f1xskwjewhafb6db23zrhh2uok4kxitcr47acwhgi
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1tgnlhtcmhwipfm7thsftxhn5k52velyjlazpvka
#### Id
> 783e1e74-3405-4ba8-8f9f-3f1118d3762d
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb2tjsupwf7m2hnln4usei6ptph6cotr5jiob2wdhiy57fkksq2kq

**Comment by Bennyyangpu** [comment]
checker:manualTrigger

**Comment by Bennyyangpu** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedzkqfw67sjfg3ycuylgzr4qlh6x4ds63j6ww7ozdrxhglq2dxrey 
#### Address 
> f1xskwjewhafb6db23zrhh2uok4kxitcr47acwhgi
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f174fg3bqbln3zjnkxtyf6s54txqkr7yqkj6cig7y
#### Id
> 783e1e74-3405-4ba8-8f9f-3f1118d3762d
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedzkqfw67sjfg3ycuylgzr4qlh6x4ds63j6ww7ozdrxhglq2dxrey

**Comment by Sunnyiscoming** [comment]
Hello, @Agee-Drust  per the https://github.com/filecoin-project/notary-governance/issues/922 for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

This information will be reviewed by Fil+ Governance team to confirm validity and then the application will be allowed to move forward for additional notary review.

**Comment by Agee-Drust** [comment]
@Sunnyiscoming OK. I finished it.

**Comment by herrehesse** [comment]
also please add the contact information of the SP entities you are working with to store copies of the data.

**Comment by herrehesse** [comment]
checker:manualTrigger

**Comment by herrehesse** [comment]
checker:manualTrigger

**Comment by herrehesse** [comment]
![Screenshot 2023-11-29 at 09 53 06](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/70132857/dfcb0d08-d89d-43fa-8101-6ecbaf29b830)

@Agee-Drust all data has been stored in the same region, against FIL+ rules.
A lot of the datacap has gone to known abusive miners/entities.

![Screenshot 2023-11-29 at 09 54 07](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/70132857/60a0c2de-5131-4b90-a8d3-3b3cc1e6e824)

Suggest closure of this LDN @Filplus-govteam

**Comment by Agee-Drust** [comment]
@herrehesse Can you show me the rules about how to define abusive sps?

**Comment by Agee-Drust** [comment]
@Filplus-govteam Hello, the 5 sps I provided in the form are all in actual cooperation with us. It is all SPs match in your comment. And for distributed storage, we look for more sp to store our copy. I think it is under the rules. Can you please reopen my application?
