### ISSUE TITLE
[DataCap Application] Meta Blockchain

### ISSUE THREAD

**Issue by jungmin6168** [filecoin-project/filecoin-plus-large-datasets#106]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Meta Blockchain
- Website / Social Media: www.meta-blockchain.io
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5 PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100 TiB
- On-chain address for first allocation: 
f3rka2244gtwxmheadu2ao5ex3wlmktpfm4f4f3qwws3ab5bgnkywp46czwncdb4swgcfetrkaq7rrikrfmiqa

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Meta Blockchain is founded in 2018, and we have participated in first level and second level test nets too. We built a Main net and Currently owned 30 nodes. Our company is growing into a storage company based on IPFS. We build a large scale of servers and operate storage centers, and provide professional management services. We also have well-equipped IDC, and collaborate with KT which has Korea’s fastest internet backbone network. 
In addition, We are expanding our business to Metaverse, so we are planning to collaborate with Metaverse Flatform based on Game Scenario. Therefore we will create items that can trade as NFTs and store those NFTs (profile, game items, avatars, etc.) and we want to store those data in to IPFS, File Coin Storage. 

What is the primary source of funding for this project?
```
Game industry, Metaverse Flatform and NFT making company. 

What other projects/ecosystem stakeholders is this project associated with?
```
Broadcast Company, Game company, IPFS KOREA, Meta Blockchain

## Use-case details

Describe the data being stored onto Filecoin
```
Please answer here.
``` 
For NFT Storage.
We are offering storage of all NFT items of Mataverse Game(Grimm Card), which should be preserved long term on Filecoin and IPFS to ensure owners of NFTs can continually access the media their own. In the future, we might expand this to serve use cases broader than NFTs. 

Where was the data in this dataset sourced from?
```
Mostly Asia, South Korea.

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
Please answer here.
```yes
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes, it is a public data. 

What is the expected retrieval frequency for this data?
```
This data can attract people in many ways. As an entertaining contents, search frequency is expected to be high as that of TV show. Also, these data can use as essential documents in metaverse game. Then its retrieval frequency will be more higher. We want to preserve the data over a long period of time and provide it to many people. Almost as permanent archive. 

For how long do you plan to keep this dataset stored on Filecoin?
```
It's a permanent archive and we'll constantly update our data stored on Filecoin.

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Asia, mostly in South Korea. 

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
We will use online transfer. But if any kind of denial occur, we will use offline transfer. We have an offline data transfer systems too. 

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We will select miners through miners reputation systems like filrep.io. 

How will you be distributing deals across storage providers?
```
We will use online transfer. But if any kind of denial occur, we will use offline transfer.

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
We already get the fund from several companies. One metaverse game company is waiting for this deals. They have more than 100 artists and NFT items. Also, We have connection with NFT, Metaverse flatform companies (Related to K pop entertainment, Games). Also they want to start making deals as soon as possible. So, we can make a deal with those companies too.

**Comment by galen-mcandrew** [comment]
@jungmin6168 It looks like the formatting for your application may have some issues, and the bot is not correctly able to parse your replies. Can you please either edit your application comment, or submit a new one? You can see others in this repo as examples.

Additionally, please clarify the nature of the data you are sourcing. Please provide some sample data for the notaries.
