### ISSUE TITLE
[DataCap Allocation] - Web development and production

### ISSUE THREAD

**Issue by rockezweb** [filecoin-project/filecoin-plus-large-datasets#1061]
---
name: Large Dataset Notary application
about: Clients should use this application form to request a DataCap allocation via a LDN for a dataset
title: "[DataCap Application] - Web development and production"
labels: 'application, Phase: Diligence'
assignees: ''

---
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Rock's Easy Web
- Website / Social Media: https://rockezweb.com
- Region: Asia (excl. Greater China)
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 3PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100TiB
- On-chain address for first allocation: f1a3lrkppfqf6qnlxcw5acy55dwiyctxrqgw7epwy

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Founded in 2012, we provide offline classes, web development lectures, and run a YouTube channel to spread a wide range of professional knowledge.
```

What is the primary source of funding for this project?
```
The revenue of the company.
```

What other projects/ecosystem stakeholders is this project associated with?
```
No.
```

## Use-case details

Describe the data being stored onto Filecoin
```
It is a lecture training material uploaded to YouTube, and while looking for a large-capacity backup, I found out about Filecoin storage through an acquaintance and participated in it.
```

Where was the data in this dataset sourced from?
```
company.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://www.youtube.com/c/EasywebPublishing/featured
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Publicly accessible material for all to see
```

What is the expected retrieval frequency for this data?
```
At least once a day
```

For how long do you plan to keep this dataset stored on Filecoin?
```
3 to 5 years
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Available in Korea or Asia
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
It can be transmitted offline and online through an acquaintance.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
If possible, the best companies will be selected, and the old ones will be randomly selected. The search function will do it if possible.
```

How will you be distributing deals across storage providers?
```
We will not keep more than 20-30% of each storage provider's data in compliance with Filecoin rules. The search function will do it if possible.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
ready enough.
```

**Comment by rockezweb** [comment]
@raghavrmadya Is there a problem?

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 3PiB

**Expected weekly DataCap usage rate**

> 100TiB

**Client address**

>f1a3lrkppfqf6qnlxcw5acy55dwiyctxrqgw7epwy

**Comment by filplus-checker** [comment]
## DataCap and CID Checker Report[^1]
 - Organization: ``
 - Client: `f1a3lrkppfqf6qnlxcw5acy55dwiyctxrqgw7epwy`
### Storage Provider Distribution
The below table shows the distribution of storage providers that have stored data for this client.

If this is the first time a provider takes verified deal, it will be marked as `new`.

For most of the datacap application, below restrictions should apply.
 - Storage provider should not exceed 25% of total datacap.
 - Storage provider should not be storing duplicate data for more than 20%.
 - Storage provider should have published its public IP address.
 - All storage providers should be located in different regions.

⚠️ [f01925211](https://filfox.info/en/address/f01925211) has sealed 100.00% of total datacap.

⚠️ All storage providers are located in the same region.

| Provider                                              |         Location | Total Deals Sealed | Percentage | Unique Data | Duplicate Deals |
| :---------------------------------------------------- | ---------------: | -----------------: | ---------: | ----------: | --------------: |
| [f01925211](https://filfox.info/en/address/f01925211) | Busan, Busan, KR |          44.22 TiB |    100.00% |   44.22 TiB |           0.00% |

![Provider Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/1061/1671098428291.png)
### Deal Data Replication
The below table shows how each many unique data are replicated across storage providers.
- No more than 25% of unique data are stored with less than 4 providers.

⚠️ 100.00% of deals are for data replicated across less than 4 storage providers.

| Unique Data Size | Total Deals Made | Number of Providers | Deal Percentage |
| ---------------: | ---------------: | ------------------: | --------------: |
|        44.22 TiB |        44.22 TiB |                   1 |         100.00% |

![Replication Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/1061/1671098429077.png)
### Deal Data Shared with other Clients
The below table shows how many unique data are shared with other clients.
Usually different applications owns different data and should not resolve to the same CID.

✔️ No CID sharing has been observed.

[^1]: To manually trigger this report, add a comment with text `checker:manualTrigger`

**Comment by cryptowhizzard** [comment]
checker:manualTrigger

**Comment by cryptowhizzard** [comment]
@dkkapur 

Something is not right here. The checkbot above displays deals on second attempt it does not.

**Comment by cryptowhizzard** [comment]
Then -> let's try again!

**Comment by cryptowhizzard** [comment]
manualTrigger

**Comment by cryptowhizzard** [comment]
@xinaxu thanks!

@rockezweb what's on the menu today and why is this not stored (yet) according to the guidelines of Fil+?
