### ISSUE TITLE
[DataCap Application] Zoland-TV

### ISSUE THREAD

**Issue by zolandtv** [filecoin-project/filecoin-plus-large-datasets#1064]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Zoland-TV
- Website / Social Media: Websites: http://www.zolandtv.com/      http://www.zolandanimation.com/
Social Media: https://twitter.com/ZolandGroup  https://www.facebook.com/zolandanimation 
http://www.instagram.com/zolanddistribution   http://www.youtube.com/c/zolandanimation
https://www.linkedin.com/company/zolanddistribution/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5 PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100TiB
- On-chain address for first allocation: f1ka66piios6kglll2ace2amu26kxl4m4rgh5m56q

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
In 2003, ZolandTV Group realized cross domain industry upgrading and established ZhejiangZoland animation Co., Ltd. to build a pan entertainment ecosystem integrating animation creativity, animation distribution, authorized marketing, technology research and development, cultural tourism, animation performance and other industries. At present, it has become one of the largest original animation companies in China.
	Sunshine, positive energy and family happiness are the core concepts of cartoon content creation in Central South China. The company has created 22 major themes, 59 excellent animations of nearly 130000 minutes, among which the original animations "Magic Eyes", "Magic Wonderland", "Rubi" and "Zheng He's voyages to the west seas" have won more than 190 domestic and international awards, including the "five one project" award for national spiritual civilization construction, the first prize for national excellent animation, and domestic excellent animation, and have successively won more than 400 domestic and international awards TV stations and new media have been popular and distributed to 93 countries and regions around the world. The export of film, television and animation ranks first in China.
```

What is the primary source of funding for this project?
```
The business income of multiple business lines of the project.
```

What other projects/ecosystem stakeholders is this project associated with?
```
For blockchain industry, we have related with NFT project.
```

## Use-case details

Describe the data being stored onto Filecoin
```
Basically, cartoon, videos and pictures. 
```

Where was the data in this dataset sourced from?
```
Mainly from cartoon materials produced by our company
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://drive.google.com/drive/folders/1plt68NZMy2_aPgSJEuPq2n2_T-wLV4F2?usp=sharing
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
We confirm that it is perfectly public data in network. 
```

What is the expected retrieval frequency for this data?
```
There is no fixed retrieval frequency.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
we plan to store permanently. 
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
No regional restrictions
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
We have a platform for online transfer. Also, if it is needed for offline transfer, we also accept it. 
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We plan to select SP in multiple regions around us, and SP need to have a good reputation. And we will regularly track the record with SP whether they can be corrected in time. For SP with good performance, we will cooperate for a long time.
```

How will you be distributing deals across storage providers?
```
Make sure that each SP won’t be allocated more than 25% datacap of us. 
We will keep records. 
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
We have resources and funds to start making deals as soon as we receive Datacap. 
```

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 100TiB

**Client address**

>f1ka66piios6kglll2ace2amu26kxl4m4rgh5m56q

**Comment by NDLABS-OFFICE** [comment]
Hello, I am very glad to see that your application has been successfully approved. 
1、May I ask if you have ready-made data to store, how do you find the sp, and what is the follow-up packaging plan?
2、Please describe your relationship to the subject
3、Do you need assistance with data storage?

**Comment by zolandtv** [comment]
Hello, @NDLABS-OFFICE 
I am an employee of Zoland-TV, and I am mainly responsible for Fil+ related matters. With the development of our business for many years, more than 5P of data needs to be stored. We will follow up with well-known SPs on Slack's fil-deal-market channel and official website. We plan to cooperate with 10 SPs, and each SP will allocate 15% of the quota on average.

**Comment by NDLABS-OFFICE** [comment]
Thanks for the reply, please provide me with the cid after the data storage is completed: ND LABS - OFFICE(slack).
I will keep watching.

**Comment by 1ane-1** [comment]
I have verified the subject's sample data and company information, and I will continue to pay attention

**Comment by NDLABS-OFFICE** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebxmg23ouznmjonpxvj6vubbkcqpbo6la2zqgthxina5gft6gzd7a 
#### Address 
> f1ka66piios6kglll2ace2amu26kxl4m4rgh5m56q
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1yayfsv6whu3rheviucvventj3y6t542xfpb47ei
#### Id
> 2b885cd5-2101-4ca8-a2c2-5998b178a8c4
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebxmg23ouznmjonpxvj6vubbkcqpbo6la2zqgthxina5gft6gzd7a

**Comment by 1ane-1** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacea4hxxd4g4iix2u5mjg3r6cdia4wi3ep6xz25dm6oxbxrsi3ci6ve 
#### Address 
> f1ka66piios6kglll2ace2amu26kxl4m4rgh5m56q
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1mdk7s2vntzm6hu35yuo6vjubtrpfnb2awhgvrri
#### Id
> 2b885cd5-2101-4ca8-a2c2-5998b178a8c4
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacea4hxxd4g4iix2u5mjg3r6cdia4wi3ep6xz25dm6oxbxrsi3ci6ve

**Comment by NDLABS-OFFICE** [comment]
checker:manualTrigger

**Comment by herrehesse** [comment]
@zolandtv dear applicant, can you explain why the CID checker shows centralized storage of the datacap that has been given? It is against the rules of Filecoin+ and we as a community would require you to follow the rules strictly.

**Comment by NDLABS-OFFICE** [comment]
@herrehesse The customer's data wasn't completely used up, they should be in progress because I had signed before so I checked halfway through.

**Comment by herrehesse** [comment]
@NDLABS-OFFICE understood!
Looking forward to the customer showing results on their promise to:

We plan to select SP in multiple regions around us, and SP need to have a good reputation. And we will regularly track the record with SP whether they can be corrected in time. For SP with good performance, we will cooperate for a long time.

**Comment by NDLABS-OFFICE** [comment]
@herrehesse Fantastic, high-quality SP can provide customers with more stable service and guarantee, which will bring protection to FIL as the underlying infrastructure and is also conducive to the subsequent development of FIL ecology.

**Comment by herrehesse** [comment]
@zolandtv 

Can you also make sure all selected storage providers have their miners reachable?

⚠️ [f01923930](https://filfox.info/en/address/f01923930) has unknown IP location.
⚠️ [f01924189](https://filfox.info/en/address/f01924189) has unknown IP location.
⚠️ [f01924048](https://filfox.info/en/address/f01924048) has unknown IP location.

This behaviour is not allowed.

Do you need any assistance in finding storage providers on different continents and test status?

**Comment by NDLABS-OFFICE** [comment]
@herrehesse Thanks for assisting with the review, Zoland-TV
Contacted me on slack before, I have given Zoland-TV on slack
Leave a message asking for an explanation.
I will also persist the data storage situation.

**Comment by zolandtv** [comment]
Hi, @herrehesse 
Thanks for the reminder. I have contacted those SPs.
They reply that they are in the debugging stage and will get it set up ASAP. 
We have made an agreement with our SPs. They will guarantee to follow the encapsulation rules. 
Please stay tuned, thank you.

**Comment by YuanHeHK** [comment]
@zolandtv It is recommended that you add some more SPs, and if you want to get support more easily, you need to adjust the existing problems and possible optimizations. I will support you this time.

**Comment by YuanHeHK** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebflzhandkd6tywx4q3slueuewpiuacldgyzq7ryyvqttdpzp2k6w 
#### Address 
> f1ka66piios6kglll2ace2amu26kxl4m4rgh5m56q
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1fg6jkxsr3twfnyhdlatmq36xca6sshptscds7xa
#### Id
> 9b48a943-06f1-45fc-b83a-dd49d87e5ac2
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebflzhandkd6tywx4q3slueuewpiuacldgyzq7ryyvqttdpzp2k6w

**Comment by lvschouwen** [comment]
checker:manualTrigger

**Comment by lvschouwen** [comment]
@zolandtv 
(cc @YuanHeHK @NDLABS-OFFICE)
You have gone from 3 unreachable miners to 5 now, and CID sharing.
Can you please improve this situation as soon as possible? Another request for datacap should not have been approved in my opinion until this issue is resolved.

**Comment by NDLABS-OFFICE** [comment]
@lvschouwen 
Thanks for monitoring, as the client mentioned in their appeal reply they are still in the process of contacting more sp's and technical adjustments, and the client is still working on the data storage, I will continue to monitor the client's situation.

**Comment by zolandtv** [comment]
@lvschouwen 
Hello,
Thank you very much for your catch-up. and with this check tool, which is very useful for us to monitor the SP sealing situation.
We have made inquiries to these SPs. Among them, the three SPs f01923930, f01924189, and f01924048 were unable to provide stable and high-quality services, and due to their technical mistakes, data sharing occurred in our sealing process. We have decided not to do business with them anymore. In the future, our data will not be sealed on their nodes.
The feedback from the rest of the SPs is that they will make technical settings asap. After the next round of allocation, everything will return to normal.

**Comment by zolandtv** [comment]
@YuanHeHK @NDLABS-OFFICE @1ane-1 
Thanks for the support of the notarys, I will strictly supervise the subsequent data storage work of sp.

**Comment by herrehesse** [comment]
@zolandtv 

Thanks for your explanation above, looking forward to your next datacap to be stored on multiple continents and with multiple different minerID's. Show us how to meet the FIL+ rules!

**Comment by cryptowhizzard** [comment]
Sorry, but i do not agree with @herrehesse or @NDLABS-OFFICE here. I highly advise signing subsequent applications as this application has seen datasharing with [960](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/960) , a highly fraudulent LDN application.

I would like to see a review of the T&T WG team to find out who had this content first and who was first publishing the CID's to the chain. Also i would like to see a list of CID's that are stored and retrieval of the data so we can verify before we can continue.

Tagging T&T WG for review

**Comment by zolandtv** [comment]
Hi @cryptowhizzard , thanks for the reply.
We do not have data sharing with #960. As I mentioned in my appeal, our current data was shared because of a data processing issue with the sp. We have asked the sp to rectify this and we have found a new sp to work with. Please give us a chance to prove ourselves in the next round of stored data.
We will also make the CID records available for community retrieval. Thank you.

**Comment by zolandtv** [comment]
@herrehesse Thank you, we have contacted different regional sp's for data storage and you can see in the check bot if the next round can be shown.

**Comment by cryptowhizzard** [comment]
Hello @zolandtv 

I would like you to fill out [this form](https://form.jotform.com/230232885049356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Please note that i ask you to give the SP's in advance + their contact info. This is for me to check their reputation. Without that info I cannot do my due diligence.

**Comment by herrehesse** [comment]
checker:manualTrigger
