### ISSUE TITLE
[DataCap Application] <Forgame Holdings Limited> - <Cloud Gaming data storage>

### ISSUE THREAD

**Issue by NetCloud91Wan** [filecoin-project/filecoin-plus-large-datasets#1066]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Forgame Holdings Limited
- Website / Social Media:  http://www.forgame.com/
                                          https://www.jieyou.com/
                                          https://twitter.com/NETCLOUD91WAN
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):100TiB
- On-chain address for first allocation: f1ci4cisghl3tdt365axgmg4hjh2q6qm7skl6ijdy

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Founded in 2009 and listed on the Main Board of the Stock Exchange of Hong Kong on October 3, 2013, Forgame Group is a leading gaming and fintech company in China. It is now actively exploring and comprehensively upgrading its gaming business in an effort to become an influential technology company in China. 91wan, a game publishing platform run by Netcloud (Hong Kong) Technology Limited, a member of Forgame Group, has published more than 100 web-based games and attracted more than 200 million registered users. In the future, the group plans to further expand its business scope and provide users with product experiences that "technology changes their lives".
```

What is the primary source of funding for this project?
```
Own funds and revenue of the company. 
```

What other projects/ecosystem stakeholders is this project associated with?
```
None.
```

## Use-case details

Describe the data being stored onto Filecoin
```
There are two main types of data that we need to stored, 
Independent developed game pictures and videos, used to analyze game AI.
```

Where was the data in this dataset sourced from?
```
Independent development of game pictures, and training game video.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://drive.google.com/drive/folders/1WpkK0U8ppcGxGCfeQcXFVdeEILfNo3SM?usp=sharing 
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes.
```

What is the expected retrieval frequency for this data?
```
Three months to half year.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
We hope to be permanent storage.
Because we will generate a large amount of data in the process of training AI, the cost of building storage hardware according to demand is too high, so we hope to have a platform to help us store relevant data. 
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
All regions.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Both online and offline.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We need a lot of SPs to choose from. In addition, we would also like to find some reputational SPs from BigData Exchange.
```

How will you be distributing deals across storage providers?
```
We plan to distribute it equally among the different sp's.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
We have enough resources and funds to start trading. 
```

**Comment by NetCloud91Wan** [comment]
We changed applicant from Netcloud (HongKong) technology Limited to Forgame Holdings Limited. Because Netcloud is operating platform, Forgame is the parent company. Using Forgame as applicant is more clearly.

**Comment by raghavrmadya** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 100TiB

**Client address**

>f1ci4cisghl3tdt365axgmg4hjh2q6qm7skl6ijdy

**Comment by NetCloud91Wan** [comment]
@raghavrmadya Hello RG，we saw that you have replied Datacap Request Trigger 29 days ago, why didn't our bot show up? We have been waiting for a month, can you help to see if there is any solution?

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Looking at your application i have some questions:
As you are brand new on Github and have no history of past applications it seems to me that applying for 5PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?

Can you show us visible proof of the size of your data and the storage systems you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230232885049356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!

**Comment by Sunnyiscoming** [comment]
Hey, @NetCloud91Wan . If you still want to apply for datacap, you can ask more notaries to do client due diligence and approve the application in slack channel. https://app.slack.com/client/TEHTVS1L6/C036JKD8NVA/thread/C03BG1MNQ4T-1673888660.823499

**Comment by NetCloud91Wan** [comment]
> Dear applicant,
> 
> Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.
> 
> Looking at your application i have some questions: As you are brand new on Github and have no history of past applications it seems to me that applying for 5PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?
> 
> Can you show us visible proof of the size of your data and the storage systems you have there?
> 
> As last question i would like you to fill out [this form](https://form.jotform.com/230232885049356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.
> 
> Thanks!

Dear cryptowhizzard,
We have specially applied for a GitHub account for this project.
We store part of the original data on the company's server and transfer part of the data to Googledrive.
https://drive.google.com/drive/folders/1WpkK0U8ppcGxGCfeQcXFVdeEILfNo3SM?usp=sharing
Our company was established in 2009 and listed in Hong Kong Stock Exchange in 2014. we have been mainly engaged in operating web games.Right now we are training AI with lots of videos and images,so we want to store some data on filecoin platform.We want to hurry up and start uploading some data, so hopefully we can get it approved quickly
KYC we will fill, please check.
Thanks.

**Comment by NetCloud91Wan** [comment]
> Hey, @NetCloud91Wan . If you still want to apply for datacap, you can ask more notaries to do client due diligence and approve the application in slack channel. https://app.slack.com/client/TEHTVS1L6/C036JKD8NVA/thread/C03BG1MNQ4T-1673888660.823499

Thank you for your advice

**Comment by cryptowhizzard** [comment]
Hello @NetCloud91Wan 

Thanks for sending me KYC.

As you are preparing the dataset i have a few requests:

The form has an explanation of the FIL plus and asks for 4 organisations / SP's in different regions. Can you provide them to us with their contact information?

![Scherm­afbeelding 2023-02-08 om 16 29 54](https://user-images.githubusercontent.com/36404435/217574925-d3c9e941-7f75-4c08-90b0-3034e19d24e7.png)

**Comment by NetCloud91Wan** [comment]
> Hello @NetCloud91Wan
> 
> Thanks for sending me KYC.
> 
> As you are preparing the dataset i have a few requests:
> 
> The form has an explanation of the FIL plus and asks for 4 organisations / SP's in different regions. Can you provide them to us with their contact information?
> 
> ![Scherm­afbeelding 2023-02-08 om 16 29 54](https://user-images.githubusercontent.com/36404435/217574925-d3c9e941-7f75-4c08-90b0-3034e19d24e7.png)

Thank you for your reply!
Now we have found the following two SPs through slack and other channels, here is the information about them.
We will continue to look for SPs through BDE or slack etc. If the community and notaries have quality SPs to recommend, it would be great.
image.png
 
![123](https://user-images.githubusercontent.com/115387814/218031077-d5712a7f-5b68-4dd7-84d0-8d3b6ebb7034.png)

**Comment by cryptowhizzard** [comment]
lotus net connect f01870558
ERROR: getting miner info: failed to load miner actor state: actor code is not miner: account

Sp-1 is ok.

**Comment by NetCloud91Wan** [comment]
> 



> lotus net connect f01870558 ERROR: getting miner info: failed to load miner actor state: actor code is not miner: account
> 
> Sp-1 is ok.

hi，
SP-2 is f0870558, you have read it wrong and can try again

**Comment by NetCloud91Wan** [comment]
We have only been able to find the following SPs so far and we would like the community to recommend SPs to us.
![image](https://user-images.githubusercontent.com/115387814/220545487-58afa98e-8663-46dc-8618-ab5e78d5619c.png)

**Comment by NetCloud91Wan** [comment]
> > > 
> > 
> > 
> > > lotus net connect f01870558 ERROR: getting miner info: failed to load miner actor state: actor code is not miner: account
> > > Sp-1 is ok.
> > 
> > 
> > hi， SP-2 is f0870558, you have read it wrong and can try again
> 
> Sorry!
> 
> f0870558 is OK so both SP's are ok.
> 
> We need 2 more?

We have only been able to find the following SPs so far and we would like the community to recommend SPs to us.
![image](https://user-images.githubusercontent.com/115387814/220545862-32508c22-da1c-4192-82e3-e85fb1353cf6.png)

**Comment by NetCloud91Wan** [comment]
> > > 
> > 
> > 
> > > lotus net connect f01870558 ERROR: getting miner info: failed to load miner actor state: actor code is not miner: account
> > > Sp-1 is ok.
> > 
> > 
> > hi， SP-2 is f0870558, you have read it wrong and can try again
> 
> Sorry!
> 
> f0870558 is OK so both SP's are ok.
> 
> We need 2 more?

Introduced by a friend,we contacted two more SPs who were willing to help us store our dataset.
f02012032  Hong Kong
f02014107 South Korea
If you have a recommended SP, we would be happy to start contacting them as well.And you have any questions you can ask us any time.

**Comment by cryptowhizzard** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecispo5ygpcjjd2pask4wolyz6qgysxazgigcngiooxnpbg5tkqgg 
#### Address 
> f1ci4cisghl3tdt365axgmg4hjh2q6qm7skl6ijdy
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1krmypm4uoxxf3g7okrwtrahlmpcph3y7rbqqgfa
#### Id
> a8420856-f336-4f40-915b-7b4f5214cad9
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecispo5ygpcjjd2pask4wolyz6qgysxazgigcngiooxnpbg5tkqgg

**Comment by cryptowhizzard** [comment]
Looking forward to your first milestone!

**Comment by NetCloud91Wan** [comment]
> Looking forward to your first milestone!

thanks a lot

**Comment by luobin544** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedhkge2gtmimyn5enl5u3qtawzm3uz5jfvs6x3fhkll56chpny7ls 
#### Address 
> f1ci4cisghl3tdt365axgmg4hjh2q6qm7skl6ijdy
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1tbd632f6w62glfaf7wjpimacbnjiz26poyoes2q
#### Id
> a8420856-f336-4f40-915b-7b4f5214cad9
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedhkge2gtmimyn5enl5u3qtawzm3uz5jfvs6x3fhkll56chpny7ls

**Comment by luobin544** [comment]
We have seen other notaries finish kyc and are willing to support the first round

**Comment by NetCloud91Wan** [comment]
Hello @raghavrmadya @galen-mcandrew @Sunnyiscoming PL's colleagues
Thank for two notary(@cryptowhizzard @luobin544 ) have approved the issue for us, but now that we have looked at the client address there is still no credit, according to the chain we found that cryptowhizzard was signed on the v3 multi-signature address f01858410 and luobin544 was signed on the v4 multi-signature address f02049625. So now that the two notaries are approved, we are not able to get the 100T datacap.
Is there any way to solve this problem please?  Thank you！

**Comment by NetCloud91Wan** [comment]
> ## Request Proposed
> Your Datacap Allocation Request has been proposed by the Notary
> 
> #### Message sent to Filecoin Network
> > bafy2bzacedhkge2gtmimyn5enl5u3qtawzm3uz5jfvs6x3fhkll56chpny7ls
> 
> #### Address
> > f1ci4cisghl3tdt365axgmg4hjh2q6qm7skl6ijdy
> 
> #### Datacap Allocated
> > 50.00TiB
> 
> #### Signer Address
> > f1tbd632f6w62glfaf7wjpimacbnjiz26poyoes2q
> 
> #### Id
> > a8420856-f336-4f40-915b-7b4f5214cad9
> 
> #### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedhkge2gtmimyn5enl5u3qtawzm3uz5jfvs6x3fhkll56chpny7ls

Thanks a lot

**Comment by Lyu23** [comment]
> **Looks like the bot was not able to retrieve the transaction on the lotus node. Please contact governance team.** The message cid: bafy2bzacecispo5ygpcjjd2pask4wolyz6qgysxazgigcngiooxnpbg5tkqgg
> 
> ```
> Please, contact the governance team.
> ```

Hi，@cryptowhizzard 
Could you please recheck this message? Thanks

**Comment by NetCloud91Wan** [comment]
> bafy2bzacecispo5ygpcjjd2pask4wolyz6qgysxazgigcngiooxnpbg5tkqgg

Hi @cryptowhizzard ,
Could you please recheck this message,Thanks.

**Comment by caoyoungyoung** [comment]
Can you describe the data composition of 5 PiB or any  proof to show you already have 5PiB data？

**Comment by NetCloud91Wan** [comment]
> Can you describe the data composition of 5 PiB or any proof to show you already have 5PiB data？

Hi, @caoyoungyoung.
Of course. There are two main types of data, independent developed game pictures and videos, used to analyze game AI.

**Comment by caoyoungyoung** [comment]
Willing to support the first round based on the thorough investigation notaries did, we will keep eyes on your following CID report.

**Comment by coder-lb** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecqtwheskidmxtv2m7n5ibbnmrdpdtqp5mghu535hl4zauldtjoxe 
#### Address 
> f1ci4cisghl3tdt365axgmg4hjh2q6qm7skl6ijdy
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1dktm3abgn7wkpepxab4q3eaw24qktizk4esfzyy
#### Id
> a8420856-f336-4f40-915b-7b4f5214cad9
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecqtwheskidmxtv2m7n5ibbnmrdpdtqp5mghu535hl4zauldtjoxe

**Comment by NetCloud91Wan** [comment]
> ## Request Approved
> Your Datacap Allocation Request has been approved by the Notary
> 
> #### Message sent to Filecoin Network
> > bafy2bzacecqtwheskidmxtv2m7n5ibbnmrdpdtqp5mghu535hl4zauldtjoxe
> 
> #### Address
> > f1ci4cisghl3tdt365axgmg4hjh2q6qm7skl6ijdy
> 
> #### Datacap Allocated
> > 50.00TiB
> 
> #### Signer Address
> > f1dktm3abgn7wkpepxab4q3eaw24qktizk4esfzyy
> 
> #### Id
> > a8420856-f336-4f40-915b-7b4f5214cad9
> 
> #### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecqtwheskidmxtv2m7n5ibbnmrdpdtqp5mghu535hl4zauldtjoxe

Thanks a lot

**Comment by maxvint** [comment]
checker:manualTrigger

**Comment by maxvint** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebfqoiaiv2dikvwbhutakumlure3acbcm4dzgjrjmfrsdchmnjch4 
#### Address 
> f1ci4cisghl3tdt365axgmg4hjh2q6qm7skl6ijdy
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1ui5iy4mmkxjbw7752omiwp2ols2fzv4thrayagi
#### Id
> 26f0abb2-baff-40d0-bdaa-63f013a34575
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebfqoiaiv2dikvwbhutakumlure3acbcm4dzgjrjmfrsdchmnjch4

**Comment by maxvint** [comment]
Please pay attention to the retrieval problem.

**Comment by NetCloud91Wan** [comment]
checker:manualTrigger

**Comment by NetCloud91Wan** [comment]
@maxvint
Thank you, our SP is solving the retrieve function of http.

**Comment by NetCloud91Wan** [comment]
checker:manualTrigger

**Comment by NetCloud91Wan** [comment]
checker:manualTrigger

**Comment by Normalnoise** [comment]
checker:manualTrigger

**Comment by Normalnoise** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecv6vyal2f2kxeflu2efdpdnqskjcfgkhotmomppylene7sbzasac 
#### Address 
> f1ci4cisghl3tdt365axgmg4hjh2q6qm7skl6ijdy
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1c5non5yf35avgcpsqvxu4yj54yyvxorwyjochqq
#### Id
> 26f0abb2-baff-40d0-bdaa-63f013a34575
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecv6vyal2f2kxeflu2efdpdnqskjcfgkhotmomppylene7sbzasac

**Comment by zcfil** [comment]
checker:manualTrigger

**Comment by zcfil** [comment]
checker:manualTrigger

**Comment by zcfil** [comment]
Yes, it looks pretty good. This round of support, we will continue to follow up in the future

**Comment by zcfil** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebgergjvez5xqzw3wnma6yyfvbqnpdydlxrpjia26stmhoissbxo4 
#### Address 
> f1ci4cisghl3tdt365axgmg4hjh2q6qm7skl6ijdy
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1cjzbiy5xd4ehera4wmbz63pd5ku4oo7g52cldga
#### Id
> 26f0abb2-baff-40d0-bdaa-63f013a34575
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebgergjvez5xqzw3wnma6yyfvbqnpdydlxrpjia26stmhoissbxo4

**Comment by NetCloud91Wan** [comment]
@zcfil Thanks.
we'll be looking for more SPs in different places to store the data, making it more dispersed.

**Comment by NetCloud91Wan** [comment]
checker:manualTrigger

**Comment by kernelogic** [comment]
Report LGTM and the data is real.

**Comment by kernelogic** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedfz2fxnoq5xznyrd24xyof5ngkbrflv5kyktnjpskz3dk3uyrln6 
#### Address 
> f1ci4cisghl3tdt365axgmg4hjh2q6qm7skl6ijdy
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### Id
> 26f0abb2-baff-40d0-bdaa-63f013a34575
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedfz2fxnoq5xznyrd24xyof5ngkbrflv5kyktnjpskz3dk3uyrln6

**Comment by NetCloud91Wan** [comment]
@clriesco Hi notary and government team, can you open the application form for me? This could help me to continue with my previous program.

**Comment by clriesco** [comment]
Sorry, I'm not allowed to do that. Please, contact someone from the government team.

**Comment by NetCloud91Wan** [comment]
@clriesco Okay. Thank you.

**Comment by NetCloud91Wan** [comment]
@clriesco Hi, excuse me.which one of people can we call to solve this problem?

**Comment by NetCloud91Wan** [comment]
@Sunnyiscoming Hi, I'd want to ask how I can reopen this proposal. 
Thanks.

**Comment by Sunnyiscoming** [comment]
checker:manualTrigger

**Comment by Sunnyiscoming** [comment]
Best practice for storing large datasets includes ideally, storing it in 3 or more regions, with 4 or more storage provider operators or owners.You should list Miner ID, Business Entity, Location of sps you will cooperate with.
It seems that there are only no more than 2 sps participated in storing. Please ask more sps join in the datacap storage.

**Comment by NetCloud91Wan** [comment]
@Sunnyiscoming  Thank you for your help.
We are now looking for another sp for data storage.

**Comment by NetCloud91Wan** [comment]
checker:manualTrigger

**Comment by Sunnyiscoming** [comment]
Hello, @NetCloud91Wan per the https://github.com/filecoin-project/notary-governance/issues/922 for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

This information will be reviewed by Fil+ Governance team to confirm validity and then the application will be allowed to move forward for additional notary review.

**Comment by NetCloud91Wan** [comment]
@Sunnyiscoming Thanks, we've already filled out the form

**Comment by Sunnyiscoming** [comment]
Yes. Received that.

**Comment by NetCloud91Wan** [comment]
checker:manualTrigger

**Comment by herrehesse** [comment]
![Screenshot 2023-11-14 at 10 08 05](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/70132857/842dedc9-14d1-448c-8b91-20d8d80c20ae)

Fully self-dealing, close this LDN @kevzak

**Comment by NetCloud91Wan** [comment]
checker:manualTrigger

**Comment by NetCloud91Wan** [comment]
@kevzak I don't quite understand what is meant by self trading here, after hearing that PLUS is able to do storage, so far we have found 5 sp's for storage, located in Hong Kong and the US!
I also know that more sp's from different regions are needed ideally, so now we have no storage data until we find a sp from a third region, but it's true that we can't find any other sp's from other regions, so of course we are happy to give storage data to different sp's if the government team is able to provide suitable sp's

**Comment by Sunnyiscoming** [comment]
Closing until more sps join in.
