### ISSUE TITLE
[DataCap Application] Genome Ark DataSet

### ISSUE THREAD

**Issue by beck-8** [filecoin-project/filecoin-plus-large-datasets#1068]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Public Genome Ark dataset
- Website / Social Media: https://vertebrategenomesproject.org/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 200TiB
- On-chain address for first allocation: f1i64dht6jd6blfbxmt4xwss4wvf37kn7wjaxe3ui

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
I am a technologist and have participated in many tests during the early testnet of filecoin. In each network upgrade, leads the team to fight on the front line, and has a deep understanding and senior experience in the technical side of filecoin. Now come to participate in the LDN event to help filecoin store more real data and make web3 storage real.
```

What is the primary source of funding for this project?
```
Self-funded,my personal partner.
```

What other projects/ecosystem stakeholders is this project associated with?
```
No.
```

## Use-case details

Describe the data being stored onto Filecoin
```
Near error-free reference genome assemblies of extant vertebrate species, a complete list of extant vertebrate species.
```

Where was the data in this dataset sourced from?
```
https://vertebrategenomesproject.org/
the bucket is arn:aws:s3:::genomeark
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
urls:
https://genomeark.s3.us-east-1.amazonaws.com/species/Acanthisitta_chloris/bAcaChl1/genomic_data/10x/bAcaChl1_S1_L004_R1_001.fastq.gz
https://genomeark.s3.us-east-1.amazonaws.com/species/Acanthisitta_chloris/bAcaChl1/genomic_data/10x/bAcaChl1_S1_L004_R2_001.fastq.gz
https://genomeark.s3.us-east-1.amazonaws.com/species/Accipiter_gentilis/bAccGen1/assembly_cambridge/bAccGen1.alt.asm.20211029.fasta.gz
https://genomeark.s3.us-east-1.amazonaws.com/species/Accipiter_gentilis/bAccGen1/assembly_cambridge/bAccGen1.pri.asm.20211029.fasta.gz

or use bucket
arn:aws:s3:::genomeark
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes, it is AWS open dataset.
```

What is the expected retrieval frequency for this data?
```
Not very often.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
532 days
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
North america; Korea; China;Singapore.There are all other possible regions.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Storage providers that are farther away use online transfers, and those that are closer use offline transfers.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
I will combine my previous experience and look for some SPs with high reputation and stability.I have contacted some storage providers.
```

How will you be distributing deals across storage providers?
```
If they can receive my transactions, I will distribute them evenly and find as many SPs as possible to seal them, making the data more widely distributed.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
I have all I need to start making deals.
```

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 200TiB

**Client address**

>f1i64dht6jd6blfbxmt4xwss4wvf37kn7wjaxe3ui

**Comment by kernelogic** [comment]
This dataset has a non-standard usage term, need to make sure you are free to distribute it.

https://genome10k.ucsc.edu/data-use-policies/

**Comment by newwebgroup** [comment]
Hey @kernelogic 
The content looks fine,
What SPs have you found for cooperation?

**Comment by newwebgroup** [comment]
Hey @beck-8 
The content looks fine,
What SPs have you found for cooperation?

**Comment by beck-8** [comment]
> Hey @beck-8 The content looks fine, What SPs have you found for cooperation?
Hello, I plan to store to SP first (f01900525, f01155, f01971600), I am looking for more SP to store, and then continue to sync to here.

**Comment by kernelogic** [comment]
This dataset is not using the usual open source licenses. I think you need to contact them for explicit re-distribution approval.

<img width="1174" alt="image" src="https://user-images.githubusercontent.com/3711825/204965114-15c66912-3617-4458-88ad-fb2c836b9e83.png">

**Comment by beck-8** [comment]
> This dataset is not using the usual open source licenses. I think you need to contact them for explicit re-distribution approval.
> 
> <img alt="image" width="1174" src="https://user-images.githubusercontent.com/3711825/204965114-15c66912-3617-4458-88ad-fb2c836b9e83.png">

Hello, our data is all filtered data, and the rules are as follows.
![image](https://user-images.githubusercontent.com/34204218/204985002-780f504e-cfae-444d-bc76-8a3293cb4acc.png)
Relevant information is as follows
- https://genome10k.ucsc.edu/news/
- https://vertebrategenomesproject.org/accomplishmentsandpublications
- https://vertebrategenomesproject.org/news

In addition, it can be seen from the filecoin official here that this part of the data has already been stored in the network, which is no problem.
https://filecoin.io/zh-cn/blog/posts/filedrive/

**Comment by kernelogic** [comment]
I remember this dataset was indeed part of slingshot v2. Proceed.

**Comment by kernelogic** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb7tzrwap27oq5cjbk5r4jquyzkwzwrplieynjnqmevuwyvc3w2ce 
#### Address 
> f1i64dht6jd6blfbxmt4xwss4wvf37kn7wjaxe3ui
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### Id
> 21258dd7-4543-46a9-8040-bd24fc3c5c7e
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb7tzrwap27oq5cjbk5r4jquyzkwzwrplieynjnqmevuwyvc3w2ce

**Comment by newwebgroup** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedapb4zsvhp3h5ej7qqux7bih4xlm7bpevboygvh6z2jszixajsiw 
#### Address 
> f1i64dht6jd6blfbxmt4xwss4wvf37kn7wjaxe3ui
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1e77zuityhvvw6u2t6tb5qlnsegy2s67qs4lbbbq
#### Id
> 21258dd7-4543-46a9-8040-bd24fc3c5c7e
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedapb4zsvhp3h5ej7qqux7bih4xlm7bpevboygvh6z2jszixajsiw

**Comment by filplus-checker** [comment]
## DataCap and CID Checker Report[^1]
 - Organization: `Public Genome Ark dataset`
 - Client: `f1i64dht6jd6blfbxmt4xwss4wvf37kn7wjaxe3ui`
### Storage Provider Distribution
The below table shows the distribution of storage providers that have stored data for this client.

If this is the first time a provider takes verified deal, it will be marked as `new`.

For most of the datacap application, below restrictions should apply.
 - Storage provider should not exceed 25% of total datacap.
 - Storage provider should not be storing duplicate data for more than 20%.
 - Storage provider should have published its public IP address.
 - All storage providers should be located in different regions.

⚠️ [f01985775](https://filfox.info/en/address/f01985775) has sealed 100.00% of total datacap.

⚠️ All storage providers are located in the same region.

| Provider                                              |          Location | Total Deals Sealed | Percentage | Unique Data | Duplicate Deals |
| :---------------------------------------------------- | ----------------: | -----------------: | ---------: | ----------: | --------------: |
| [f01985775](https://filfox.info/en/address/f01985775) | Dallas, Texas, US |         128.00 GiB |    100.00% |  128.00 GiB |           0.00% |

![Provider Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/1068/1671098437833.png)
### Deal Data Replication
The below table shows how each many unique data are replicated across storage providers.
- No more than 25% of unique data are stored with less than 4 providers.

⚠️ 100.00% of deals are for data replicated across less than 4 storage providers.

| Unique Data Size | Total Deals Made | Number of Providers | Deal Percentage |
| ---------------: | ---------------: | ------------------: | --------------: |
|       128.00 GiB |       128.00 GiB |                   1 |         100.00% |

![Replication Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/1068/1671098438436.png)
### Deal Data Shared with other Clients
The below table shows how many unique data are shared with other clients.
Usually different applications owns different data and should not resolve to the same CID.

✔️ No CID sharing has been observed.

[^1]: To manually trigger this report, add a comment with text `checker:manualTrigger`

**Comment by psh0691** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb6rx3enhlgmo3ljlcsqno5wzj5jqowznocjt5kcmpv3xkqlwefbk 
#### Address 
> f1i64dht6jd6blfbxmt4xwss4wvf37kn7wjaxe3ui
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1qdko4jg25vo35qmyvcrw4ak4fmuu3f5rif2kc7i
#### Id
> 26dffe8a-b51a-48bc-abaa-1d8bfa2b2f66
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb6rx3enhlgmo3ljlcsqno5wzj5jqowznocjt5kcmpv3xkqlwefbk

**Comment by newwebgroup** [comment]
CID Checker looks alright.
With regard to the distribution proportion of SPs, the Client promises to make improvements, and the next round will be more decentralized

**Comment by newwebgroup** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedkrpiiji27snr7itbhgwe3s6bwrlb727pnrowuv24ettgktux274 
#### Address 
> f1i64dht6jd6blfbxmt4xwss4wvf37kn7wjaxe3ui
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1e77zuityhvvw6u2t6tb5qlnsegy2s67qs4lbbbq
#### Id
> 26dffe8a-b51a-48bc-abaa-1d8bfa2b2f66
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedkrpiiji27snr7itbhgwe3s6bwrlb727pnrowuv24ettgktux274

**Comment by 1ane-1** [comment]
Pay attention to the distribution proportion of SPs

**Comment by beck-8** [comment]
> Pay attention to the distribution proportion of SPs

Received, we are looking for more SP, and it will be more scattered later.

**Comment by 1ane-1** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced22wuhtp6zi6z33a4zoqelzvnyly7emjymnhsduxcyfrmymdywj4 
#### Address 
> f1i64dht6jd6blfbxmt4xwss4wvf37kn7wjaxe3ui
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1mdk7s2vntzm6hu35yuo6vjubtrpfnb2awhgvrri
#### Id
> f57d6f3a-3541-41b5-bf2f-4c9d17154a0f
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced22wuhtp6zi6z33a4zoqelzvnyly7emjymnhsduxcyfrmymdywj4

**Comment by xingjitansuo** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedcxad53g3zlnwlgva6neeerlnu4syxkmcflwyqab6kwbxh6ixic6 
#### Address 
> f1i64dht6jd6blfbxmt4xwss4wvf37kn7wjaxe3ui
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1a2lia2cwwekeubwo4nppt4v4vebxs2frozarz3q
#### Id
> f57d6f3a-3541-41b5-bf2f-4c9d17154a0f
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedcxad53g3zlnwlgva6neeerlnu4syxkmcflwyqab6kwbxh6ixic6

**Comment by xingjitansuo** [comment]
Since it is at the early allocation stage, I will approve this one!

**Comment by herrehesse** [comment]
@beck-8 Can you explain why all of this data is stored in the same location? This is against the rules of FIL+ and should be resolved or you can not continue. Love to look towards solutions here!

**Comment by algo-cpu** [comment]
> @beck-8 Can you explain why all of this data is stored in the same location? This is against the rules of FIL+ and should be resolved or you can not continue. Love to look towards solutions here!

**Comment by algo-cpu** [comment]
> @beck-8 Can you explain why all of this data is stored in the same location? This is against the rules of FIL+ and should be resolved or you can not continue. Love to look towards solutions here!

Hello, I'm storing one of the data backups, and later you will see that I store the data to storage providers in other regions. I haven't stored the same data in one area many times. Please check it. Thank you.

**Comment by beck-8** [comment]
> @beck-8 Can you explain why all of this data is stored in the same location? This is against the rules of FIL+ and should be resolved or you can not continue. Love to look towards solutions here!

Hello, I'm storing one of the data backups, and later you will see that I store the data to storage providers in other regions. I haven't stored the same data in one area many times. Please check it. Thank you.

**Comment by herrehesse** [comment]
@beck-8 try and be consistent in sharing deals among multiple miners in various regions. If not new trenches of datacap can not be released. It can happen once or twice, but doing a full copy and "we will sort the rest later" is not an option for this program. Can you tell us what the plan is?

**Comment by beck-8** [comment]
> @beck-8 try and be consistent in sharing deals among multiple miners in various regions. If not new trenches of datacap can not be released. It can happen once or twice, but doing a full copy and "we will sort the rest later" is not an option for this program.
> 
> Looking at the report, you have stored the same data on your own miners in the same datacenter. One copy is acceptable. Other copies must go to different entities, regions and minerID's. Can you tell us what the plan is?

Yes, my other copies will be stored in other entities, other areas, please rest assured that I will strictly follow the rules. I've posted auctions in BDE and I'll store them in more places.

**Comment by herrehesse** [comment]
Thank you for the transparency. Keep up the good work.

**Comment by newwebgroup** [comment]
checker:manualTrigger

**Comment by newwebgroup** [comment]
Client finds me through Slack
Review the above conversation records and CID Checker's conclusions, and be willing to support them.

**Comment by newwebgroup** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb3anyasnu3yms2jxrxietzvoxag4tbwpwnwy3bft2lt3mlac6mho 
#### Address 
> f1i64dht6jd6blfbxmt4xwss4wvf37kn7wjaxe3ui
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1e77zuityhvvw6u2t6tb5qlnsegy2s67qs4lbbbq
#### Id
> 536be1e8-3483-4f16-af65-14ce44b19739
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb3anyasnu3yms2jxrxietzvoxag4tbwpwnwy3bft2lt3mlac6mho

**Comment by kernelogic** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecftjlxuma2aumdgzlp44najehgzmfhxwcceueeogrlfewj6z7k2w 
#### Address 
> f1i64dht6jd6blfbxmt4xwss4wvf37kn7wjaxe3ui
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### Id
> 536be1e8-3483-4f16-af65-14ce44b19739
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecftjlxuma2aumdgzlp44najehgzmfhxwcceueeogrlfewj6z7k2w

**Comment by cryptowhizzard** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecmcn5see3khbofgzno4a4kykxsprbgsdv7sco55v4ogec3k2qc6w 
#### Address 
> f1i64dht6jd6blfbxmt4xwss4wvf37kn7wjaxe3ui
#### Datacap Allocated
> 1.56PiB
#### Signer Address
> f1krmypm4uoxxf3g7okrwtrahlmpcph3y7rbqqgfa
#### Id
> 2f54603f-015f-40a4-856a-bbbe8cb26c10
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecmcn5see3khbofgzno4a4kykxsprbgsdv7sco55v4ogec3k2qc6w

**Comment by BDEio** [comment]
@beck-8 Hi! Congratulations on your DataCap approval！
BDE is a trusted deals auction house helping you to get paid storing your data with reliable storage providers. If you need any help, please get in touch.

**Comment by beck-8** [comment]
> @beck-8 Hi! Congratulations on your DataCap approval！ BDE is a trusted deals auction house helping you to get paid storing your data with reliable storage providers. If you need any help, please get in touch.

Thank you very much. I have filled in the information on the BDE platform and is waiting for the transaction.

**Comment by kernelogic** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacea4qdnsdy6gl6qb367cvryf3uvul4xyq5appbtvvg4ssoxpcudlqu 
#### Address 
> f1i64dht6jd6blfbxmt4xwss4wvf37kn7wjaxe3ui
#### Datacap Allocated
> 1.56PiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### Id
> 2f54603f-015f-40a4-856a-bbbe8cb26c10
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacea4qdnsdy6gl6qb367cvryf3uvul4xyq5appbtvvg4ssoxpcudlqu

**Comment by Carohere** [comment]
Hi @beck-8, if I understood correctly, you/your organization is located in China and the sps engaged so far are all in US. Could you share more info about their identities/cooperation process? Just wanna make sure you’re not using vpn to relocate. 

Also, it would be really helpful if other notaries mentioned above could share how did you guys preform DD here🙏￼

**Comment by beck-8** [comment]
> Hi @beck-8, if I understood correctly, you/your organization is located in China and the sps engaged so far are all in US. Could you share more info about their identities/cooperation process? Just wanna make sure you’re not using vpn to relocate.
> 
> Also, it would be really helpful if notaries could share how did you guys preform DD here🙏￼
> 
> -Reposting from [slack](https://filecoinproject.slack.com/archives/C01DLAPKDGX/p1674300757731689?thread_ts=1674263448.065749&channel=C01DLAPKDGX&message_ts=1674300757.731689)

Already replied in slack.
https://filecoinproject.slack.com/archives/C01DLAPKDGX/p1674301371706889?thread_ts=1674263448.065749&channel=C01DLAPKDGX&message_ts=1674301371.706889

**Comment by Sunnyiscoming** [comment]
checker:manualTrigger

**Comment by Carohere** [comment]
>All storage providers should be located in different regions.

![image](https://user-images.githubusercontent.com/106579285/216569102-922d842e-1caf-4ced-8743-97f4fc131b2c.png)

![image](https://user-images.githubusercontent.com/106579285/216569163-ead2af99-e920-4037-b76a-841e4c6a9f21.png)

So far, all allocations have been made in the same city. I don't see any improvement from the last time. Please help me understand 
- your next step in onboarding sps
- the relation between you and `Flexential Colorado Corp.`
- any confirmed sps from other regions?

**Comment by beck-8** [comment]
> > All storage providers should be located in different regions.
> 
> ![image](https://user-images.githubusercontent.com/106579285/216569102-922d842e-1caf-4ced-8743-97f4fc131b2c.png)
> 
> ![image](https://user-images.githubusercontent.com/106579285/216569163-ead2af99-e920-4037-b76a-841e4c6a9f21.png)
> 
> So far, all allocations have been made in the same city. I don't see any improvement from the last time. Please help me understand
> 
> * your next step in onboarding sps
> * the relation between you and `Flexential Colorado Corp.`
> * any confirmed sps from other regions?

At present, no suitable SP has been found. A long time ago, the allocation of quotas had stalled. Please check and we will continue after we find the SP.

**Comment by Sunnyiscoming** [comment]
https://app.slack.com/client/TEHTVS1L6/C01KCAAURAN/thread/C01DLAPKDGX-1674263448.065749
This is the Slack channel for fil-deal, you can try.

**Comment by Carohere** [comment]
checker:manualTrigger

**Comment by Patapon0702** [comment]
checker:manualTrigger
