### ISSUE TITLE
-[DataCap Application]-University Aquatic Economic Animal Breeding Research Group

### ISSUE THREAD

**Issue by tangshantai** [filecoin-project/filecoin-plus-large-datasets#1071]
# Large Dataset Notary Application
To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: University Aquatic Economic Animal Breeding Research Group
- Website / Social Media: https://sea.jou.edu.cn/info/1057/1959.htm
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 400TiB
- On-chain address for first allocation: f16zvf3ecdwtgmdefpbqtzj2k7pjmjlqjft5ysphy

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
The Aquatic Economic Animal Breeding Research Group is from Jiangsu Ocean University. The research directions are: aquatic animal diseases and ecological immunity, aquatic animal nutrition and feed development. 

Facing the severe situation of frequent occurrence of marine aquatic diseases, using modern biology and immunology techniques, the effects of environmental factors and nutritional factors on the survival, growth and immunity of marine aquatic animals and their bioenergetics mechanisms were discussed. It provides new ideas for the development and utilization of marine aquaculture animals, the creation of excellent germplasm and disease control; the research ideas emphasize the interaction between the environment, pathogens and hosts, and establish an integrated disease early warning framework system.
```

What is the primary source of funding for this project?
```
Research Fund
```

What other projects/ecosystem stakeholders is this project associated with?
```
None
```

## Use-case details

Describe the data being stored onto Filecoin
```
Research material Video & Documentation
```

Where was the data in this dataset sourced from?
```
Research Group
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://github.com/tangshantai/data
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes
```

What is the expected retrieval frequency for this data?
```
5-10 times a year
```

For how long do you plan to keep this dataset stored on Filecoin?
```
540 Days
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Mainland China or Hong Kong
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Provide online download link
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We need SP to provide fast retrieval service to meet our occasional data request needs. Geographical location is also one of the influencing factors in our selection of SPs
```

How will you be distributing deals across storage providers?
```
Select multiple SPs, at least 4 SPs
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes
```

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 400TiB

**Client address**

>f16zvf3ecdwtgmdefpbqtzj2k7pjmjlqjft5ysphy

**Comment by Sunnyiscoming** [comment]
Hey, @tangshantai . If you still want to apply for datacap, you can ask more notaries to do client due diligence and approve the application in slack channel. https://app.slack.com/client/TEHTVS1L6/C036JKD8NVA/thread/C03BG1MNQ4T-1673888660.823499

**Comment by flyworker** [comment]
any SPs distribution plan?

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Can you show us visible proof of the size of your data and the storage systems you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230337462961356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!

**Comment by tangshantai** [comment]
> This application has not seen any responses in the last 10 days. This issue will be marked with Stale label and will be closed in 4 days. Comment if you want to keep this application open.

Hi,We have prepared the data file and are contacting sp to prepare encapsulation.

**Comment by tangshantai** [comment]
Hi,We have prepared the data file and are contacting sp to prepare encapsulation.

> This application has not seen any responses in the last 10 days. This issue will be marked with Stale label and will be closed in 4 days. Comment if you want to keep this application open.

**Comment by tangshantai** [comment]
Hi,We have prepared the data file and are contacting sp to prepare encapsulation.

**Comment by clriesco** [comment]
Removed stale label and reopened issue :)
