### ISSUE TITLE
[DataCap Application] zkPass  Technology

### ISSUE THREAD

**Issue by paomianonline** [filecoin-project/filecoin-plus-large-datasets#1074]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: zkPass Technology
- Website / Social Media: https://www.zkpass.org/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 2PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 200TiB
- On-chain address for first allocation: f1at62g7p7ktn2w4rmokryjzgb3lu7lap4cgiosmi

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
zkPass is a decentralized KYC solution based on MPC (Multi-Party Computation) and ZKP (Zero-Knowledge Proof), which aims to overcome the various flaws in the current KYC system, eliminate the pain points related to identity authentication, and protect user privacy while expanding KYC capabilities.

The data input of each party in the secure multi-party calculation process is independent, and no local raw data is leaked during the calculation.
The results obtained by the secure multi-party computation algorithm are consistent with the local computation results of the original plaintext data.
Multiple preset modules to meet your custom KYC needs.
```

What is the primary source of funding for this project?
```
Own funds. bigD.
```

What other projects/ecosystem stakeholders is this project associated with?
```
No.
```

## Use-case details

Describe the data being stored onto Filecoin
```
Images,Database data,Logfile,Video.
```

Where was the data in this dataset sourced from?
```
Own Servers.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://drive.google.com/drive/folders/10RTpkEyn0dkzLfJKp3EqjOG2xebX4vl3
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes.
```

What is the expected retrieval frequency for this data?
```
3 times/year.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
5 years if possible.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Give priority to Japan, South Korea and Hong Kong.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
We plan to transfer these data offline.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We're selecting the SPs with high reputation on slack.
```

How will you be distributing deals across storage providers?
```
We plan to find more than 4 SPs and distribute the transactions equally.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
We know how to contact SP, and we don't need community help for the time being.
```

**Comment by raghavrmadya** [comment]
Please send an email from the official email to filplus-app-review@fil.org

**Comment by paomianonline** [comment]
> Please send an email from the official email to [filplus-app-review@fil.org](mailto:filplus-app-review@fil.org)

The email has been sent, thank you!
![微信图片_20221025155854](https://user-images.githubusercontent.com/6744279/197717184-4a2b4635-70fa-49a2-aa44-0e5d71a10c3e.jpg)

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 2PiB

**Expected weekly DataCap usage rate**

> 200TiB

**Client address**

>f1at62g7p7ktn2w4rmokryjzgb3lu7lap4cgiosmi

**Comment by kernelogic** [comment]
@paomianonline can you give a break down of your data, proving you have over 400T raw data?

**Comment by paomianonline** [comment]
> @paomianonline can you give a break down of your data, proving you have over 400T raw data?
Web 2 data to transfer into web 3 through zkp    100 T
Project info to use potocal     20 T
Kyc info including pictures, videos  10 T
Nodes MPC computing data Storage 150T
KYC Data base     10 T
WEB 2 company kyc information    110 T

**Comment by Sunnyiscoming** [comment]
Hey, @paomianonline . If you still want to apply for datacap, you can ask more notaries to do client due diligence and approve the application in slack channel. https://app.slack.com/client/TEHTVS1L6/C036JKD8NVA/thread/C03BG1MNQ4T-1673888660.823499

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Looking at your application i have some questions:
As you are brand new on Github and have no history of past applications it seems to me that applying for 5PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?

Can you show us visible proof of the size of your data and the storage systems you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230337462961356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!

**Comment by igoovo** [comment]
Thank you for contacting me , I will support you in the first round.

**Comment by igoovo** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceane36xxconug3wtwpt6fanb36p3qwmbcwgjl3u2z32w2h26ee4to 
#### Address 
> f1at62g7p7ktn2w4rmokryjzgb3lu7lap4cgiosmi
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1shnsfayxqll77svffaxnjenms7bbbysbqcatrpy
#### Id
> 108db747-3579-48f3-9b36-bd05917e731a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceane36xxconug3wtwpt6fanb36p3qwmbcwgjl3u2z32w2h26ee4to

**Comment by igoovo** [comment]
Please list the SPs you have contacted. thanks.

**Comment by paomianonline** [comment]
> Please list the SPs you have contacted. thanks.

The sp we contacted have the following:
F01850726.
F02236965.
F02236251.
F02199138.
F01777770.
F02199166.
These SP promise efficient operation and maintenance of encapsulated data.

**Comment by nicelove666** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedgtnrpi6moepv5rnqbyjtrg3tideltpbgffmcncmfsc5lpu54ota 
#### Address 
> f1at62g7p7ktn2w4rmokryjzgb3lu7lap4cgiosmi
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1qnumecdypgrbaebtkdfjnwt5ndacadcuas3deiq
#### Id
> 108db747-3579-48f3-9b36-bd05917e731a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedgtnrpi6moepv5rnqbyjtrg3tideltpbgffmcncmfsc5lpu54ota

**Comment by kernelogic** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacectqg4i4bmuxe5inax6grzjye6kqaimmf4xtar4zngs5idmmhsrde 
#### Address 
> f1at62g7p7ktn2w4rmokryjzgb3lu7lap4cgiosmi
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### Id
> eea1c981-f4c5-45b4-a979-dc159374911a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacectqg4i4bmuxe5inax6grzjye6kqaimmf4xtar4zngs5idmmhsrde

**Comment by nj-steve** [comment]
checker:manualTrigger

**Comment by nj-steve** [comment]
The retrieval report looks fine. but the cid report shows SP is only one. Could you tell us why? and please show us what's you next plan?

**Comment by paomianonline** [comment]
Thank you for your question, it is true that the first round is only encapsulated on one node because of the small amount of data.
In the next stage, we will run the data on multiple SP, which will meet the requirements.
Thank you again for your question and support.

**Comment by nj-steve** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceag2ppkdmtigihw6nonrtctnwou7qllohathno2non442guoixxlo 
#### Address 
> f1at62g7p7ktn2w4rmokryjzgb3lu7lap4cgiosmi
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1xx6555qijma7igpnjspyvdunc4vfxkawnpqy5ii
#### Id
> eea1c981-f4c5-45b4-a979-dc159374911a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceag2ppkdmtigihw6nonrtctnwou7qllohathno2non442guoixxlo

**Comment by nj-steve** [comment]
keep eyes on this

**Comment by igoovo** [comment]
checker:manualTrigger

**Comment by Normalnoise** [comment]
checker:manualTrigger

**Comment by Normalnoise** [comment]
<img width="1033" alt="image" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/102578774/50900c38-e9cf-414b-8eb1-ecb97a9d5a42">
@paomianonline can you explain this issue?

**Comment by paomianonline** [comment]
> 
Hello, thank you for your question.
It is like this, the first 1 or 2 rounds because the quota is small, so when billing, there will be some errors, so that it is not suitable for the rules.

But we have been continuously optimizing the allocation of this data to make it more reasonable.
Thank you!

**Comment by Normalnoise** [comment]
@paomianonline You should allocate more deals to other SPs but f02236251. and duplicate data should not be more than 20% in one SP.

**Comment by Normalnoise** [comment]
I hope your next round can meet the requirements of fil+. In the round, I am willing to support it. I will see your next round check report.

**Comment by Normalnoise** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceclhaxzubu7whbojfaswpp5kukkwur565p7sandy4oteu3luri47e 
#### Address 
> f1at62g7p7ktn2w4rmokryjzgb3lu7lap4cgiosmi
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1c5non5yf35avgcpsqvxu4yj54yyvxorwyjochqq
#### Id
> 7ec808ac-a093-4501-acc6-6ee99bb56f50
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceclhaxzubu7whbojfaswpp5kukkwur565p7sandy4oteu3luri47e

**Comment by Tom-OriginStorage** [comment]
checker:manualTrigger

**Comment by Tom-OriginStorage** [comment]
Regarding the search problem of the robot, there is a notary above who has done a survey and is willing to sign this round, and continue to pay attention to it later

**Comment by Tom-OriginStorage** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaippmtq6k4trhu35h6qawrvipeylhg4fdbdyhfgu3ir52gailtyi 
#### Address 
> f1at62g7p7ktn2w4rmokryjzgb3lu7lap4cgiosmi
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1q6bpjlqia6iemqbrdaxr2uehrhpvoju3qh4lpga
#### Id
> 7ec808ac-a093-4501-acc6-6ee99bb56f50
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaippmtq6k4trhu35h6qawrvipeylhg4fdbdyhfgu3ir52gailtyi

**Comment by cryptowhizzard** [comment]
Hi,

When i try to download this data i get a lot of errors. Can you tell me why this is @paomianonline 

root@proposals:~/Dropbox/download.sh.finished# Error: Failed to retrieve content with candidate miner f02229760: data transfer failed: deal rejected: getting pieces for cid bafybeigf3gu3mfstp7nvh43cogltgyisxidhp3nd5uudowtssjcyisevv4: getting pieces containing block bafybeigf3gu3mfstp7nvh43cogltgyisxidhp3nd5uudowtssjcyisevv4: failed to lookup index for mh 1220c5d9a9b616537fdb53f3627197336112ba0677eda3ed28375a729245844895af, err: datastore: key not found

root@proposals:~/Dropbox/download.sh.finished# Error: Failed to retrieve content with candidate miner f02236251: data transfer failed: datatransfer error: data transfer channel 12D3KooWGJpT1vdLktshKZRWrA3Apw1eKBxwjPfoJF64AtEwdKrq-12D3KooWN8hnAZ1r1LFwX9LoJcDkqGeX1Zgocw2ns3yLUkxL1mdZ-1689598125436357182 failed to transfer data: channel 12D3KooWGJpT1vdLktshKZRWrA3Apw1eKBxwjPfoJF64AtEwdKrq-12D3KooWN8hnAZ1r1LFwX9LoJcDkqGeX1Zgocw2ns3yLUkxL1mdZ-1689598125436357182: graphsync request failed to complete: skip
Error: Failed to retrieve content with candidate miner f02236251: data transfer failed: datatransfer error: data transfer channel 12D3KooWGJpT1vdLktshKZRWrA3Apw1eKBxwjPfoJF64AtEwdKrq-12D3KooWN8hnAZ1r1LFwX9LoJcDkqGeX1Zgocw2ns3yLUkxL1mdZ-1689598125423742568 failed to transfer data: channel 12D3KooWGJpT1vdLktshKZRWrA3Apw1eKBxwjPfoJF64AtEwdKrq-12D3KooWN8hnAZ1r1LFwX9LoJcDkqGeX1Zgocw2ns3yLUkxL1mdZ-1689598125423742568: graphsync request failed to complete: expected link (bafybeif7jhwsqeurbfbsf6yg3y5sdicjcnc7774ediyxz3daiywzfojvqm) at path  does not match link sent by remote (bafkreiblp4de4a7wym3dma2h6fva5ch35mqqic5ym3tj2ladfbgupozlzm), possible malicious responder
Error: Failed to retrieve content with candidate miner f02236251: data transfer failed: datatransfer error: data transfer channel 12D3KooWGJpT1vdLktshKZRWrA3Apw1eKBxwjPfoJF64AtEwdKrq-12D3KooWN8hnAZ1r1LFwX9LoJcDkqGeX1Zgocw2ns3yLUkxL1mdZ-1689598125449192087 failed to transfer data: channel 12D3KooWGJpT1vdLktshKZRWrA3Apw1eKBxwjPfoJF64AtEwdKrq-12D3KooWN8hnAZ1r1LFwX9LoJcDkqGeX1Zgocw2ns3yLUkxL1mdZ-1689598125449192087: graphsync request failed to complete: expected link (bafybeif7jhwsqeurbfbsf6yg3y5sdicjcnc7774ediyxz3daiywzfojvqm) at path  does not match link sent by remote (bafkreiedckfclhdzfksk6g5amvly2qvyj4imf5l72vq2hplhabyzvtjwya), possible malicious responder

root@proposals:~/Dropbox/download.sh.finished# Error: Failed to retrieve content with candidate miner f02236251: data transfer failed: datatransfer error: data transfer channel 12D3KooWGJpT1vdLktshKZRWrA3Apw1eKBxwjPfoJF64AtEwdKrq-12D3KooWN8hnAZ1r1LFwX9LoJcDkqGeX1Zgocw2ns3yLUkxL1mdZ-1689598125445583245 failed to transfer data: channel 12D3KooWGJpT1vdLktshKZRWrA3Apw1eKBxwjPfoJF64AtEwdKrq-12D3KooWN8hnAZ1r1LFwX9LoJcDkqGeX1Zgocw2ns3yLUkxL1mdZ-1689598125445583245: graphsync request failed to complete: expected link (bafybeigh6a4hwbqd4dti5kidhc55svbzb3r7n6ivq6flutodixxfbkfkzm) at path  does not match link sent by remote (bafkreihvepgtmugdjwhhrqtkolufhkez2pa52ibfb3jgqjnljlwfy5v6t4), possible malicious responder

root@proposals:~/Dropbox/download.sh.finished# 
root@proposals:~/Dropbox/download.sh.finished# Error: Failed to retrieve content with candidate miner f02236251: data transfer failed: datatransfer error: data transfer channel 12D3KooWGJpT1vdLktshKZRWrA3Apw1eKBxwjPfoJF64AtEwdKrq-12D3KooWN8hnAZ1r1LFwX9LoJcDkqGeX1Zgocw2ns3yLUkxL1mdZ-1689598125422018757 failed to transfer data: channel 12D3KooWGJpT1vdLktshKZRWrA3Apw1eKBxwjPfoJF64AtEwdKrq-12D3KooWN8hnAZ1r1LFwX9LoJcDkqGeX1Zgocw2ns3yLUkxL1mdZ-1689598125422018757: graphsync request failed to complete: expected link (bafybeigh6a4hwbqd4dti5kidhc55svbzb3r7n6ivq6flutodixxfbkfkzm) at path  does not match link sent by remote (bafkreigt4y6kggaoqkfj5bbh25tpsavc4ekmidp3ntj4jvggzaobgngbsi), possible malicious responder

root@proposals:~/Dropbox/download.sh.finished# Error: Failed to retrieve content with candidate miner f02236251: data transfer failed: datatransfer error: data transfer channel 12D3KooWGJpT1vdLktshKZRWrA3Apw1eKBxwjPfoJF64AtEwdKrq-12D3KooWN8hnAZ1r1LFwX9LoJcDkqGeX1Zgocw2ns3yLUkxL1mdZ-1689598125465044149 failed to transfer data: channel 12D3KooWGJpT1vdLktshKZRWrA3Apw1eKBxwjPfoJF64AtEwdKrq-12D3KooWN8hnAZ1r1LFwX9LoJcDkqGeX1Zgocw2ns3yLUkxL1mdZ-1689598125465044149: graphsync request failed to complete: expected link (bafybeif7jhwsqeurbfbsf6yg3y5sdicjcnc7774ediyxz3daiywzfojvqm) at path  does not match link sent by remote (bafkreiabdlg44vunvhbai7l4re4c5jb556z6yj5ey4f5syebvgfhacexny), possible malicious responder

**Comment by paomianonline** [comment]
The errors have been fixed one after another. Thank you.
![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/6744279/a25ca883-b388-48d5-9a02-3311ef570e2b)
![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/6744279/94efc656-025e-4689-8bec-ca4b65e6d982)

**Comment by NiwanDao** [comment]
The client is exhibiting a positive attitude toward the challenging problem. I would love to support it this time.

**Comment by NiwanDao** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceccgsgbxnzequkpank62xobg6kbzw5k7ji5xj7zrbj27rsyq35vtu 
#### Address 
> f1at62g7p7ktn2w4rmokryjzgb3lu7lap4cgiosmi
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1a2lia2cwwekeubwo4nppt4v4vebxs2frozarz3q
#### Id
> a61ad691-a9fd-4d23-b7bf-5d0f13a834ce
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceccgsgbxnzequkpank62xobg6kbzw5k7ji5xj7zrbj27rsyq35vtu

**Comment by igoovo** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebqh2mvdvitxkeytaxbodrt26d5cyrqvbhlnkskdpy5b5cc6lqxr4 
#### Address 
> f1at62g7p7ktn2w4rmokryjzgb3lu7lap4cgiosmi
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1shnsfayxqll77svffaxnjenms7bbbysbqcatrpy
#### Id
> a61ad691-a9fd-4d23-b7bf-5d0f13a834ce
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebqh2mvdvitxkeytaxbodrt26d5cyrqvbhlnkskdpy5b5cc6lqxr4

**Comment by ipollo00** [comment]
checker:manualTrigger

**Comment by ipollo00** [comment]
DD:
CID checker healthy； Retrieval report LGTM. 
Since it is the second allocation, I randomly retrieve a CID through an SP. It works. 
![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/116627408/e2b847bf-a8aa-4776-9fec-8eee4ba8a222)

**Comment by ipollo00** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedcyq2kqwltlhibg5dzwxp65lzcl3eh677q26paonghaok6cq3xf2 
#### Address 
> f1at62g7p7ktn2w4rmokryjzgb3lu7lap4cgiosmi
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1n5wlrrhoxpkgwij25xrtt7w7g2k3fhbthmdn6ri
#### Id
> 770b9b4f-a983-4033-97bf-81f2851e8bf7
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedcyq2kqwltlhibg5dzwxp65lzcl3eh677q26paonghaok6cq3xf2

**Comment by Chuangshi1** [comment]
All the report looks healthy. Willing to support.

**Comment by cryptowhizzard** [comment]
Hello @paomianonline 

I have done some retrieval of your data and have made it available here for review:

I cannot match the data to the samples your provided. Can you explain?

http://datasetcreators.com/downloadedcarfiles/1074-f02247041-f02229760-46797825-baga6ea4seaqg3qthr3gxuetxw576onbw3bgd2nxmlvftwn3eedhvc5u2s3ecsfy/

![Scherm­afbeelding 2023-07-27 om 11 21 30](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/36404435/0724e446-02b8-4045-a9d6-bd46e1c1b931)

**Comment by PluskitOfficial** [comment]
checker:manualTrigger

**Comment by clriesco** [comment]
Removed stale label and reopened issue :)
