### ISSUE TITLE
[DataCap Application] Exbee - Exbee

### ISSUE THREAD

**Issue by oneforalone** [filecoin-project/filecoin-plus-large-datasets#1076]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Exbee
- Website / Social Media: https://exbee.io/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100TiB
- On-chain address for first allocation: f13lv6rz3cuhsq436xzrnitrsatgpxo7d7zawvveq

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Exbee is a marketplace for cryptocurrencies and virtual goods trading,
developed by Singapore-based BITBEE PTE. LTD. The demo video is: https://youtu.be/HJUMCcOaSKg. 
It currently supports trading of gift cards and cryptocurrencies.
The founding team is from Alibaba's core e-commerce technology team,
which has been responsible for the work related to marketing and transactions
of Tmall and Taobao, as well as user growth technology of Taote App. We have
continuous entrepreneurial experience in the blockchain/web3 field, very deep
industry knowledge in the direction of gift card trading, and have team members
who are locally responsible for market cooperation in less developed regions such
as Southeast Asia and Africa.
```

What is the primary source of funding for this project?
```
The team funding
```

What other projects/ecosystem stakeholders is this project associated with?
```
N/A
```

## Use-case details

Describe the data being stored onto Filecoin
```
Exbee platform materials such as logs, video tutorial, documents, etc.
```

Where was the data in this dataset sourced from?
```
The data produced by Exbee platform.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://drive.google.com/file/d/1HJa0GQsmepRX1fP-CQANF4Lvxx7t5Qzc/view?usp=sharing
https://drive.google.com/file/d/1QOE3s8A9_iNZJOZglGVC_NVah_j0yzf6/view?usp=sharing
https://drive.google.com/file/d/1rrZ1yF-eQvvNERgu_J19BlEdt9nP2hbs/view?usp=sharing
https://drive.google.com/file/d/1zj5U34tHUZy3b_JGjx0HMn8gmiCX6gKL/view?usp=sharing
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Confirmed - Yes.
```

What is the expected retrieval frequency for this data?
```
Every 6 months to ensure the data is available.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
More than 2 years.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
All regions, and Aisa is perefed.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
We'll generate CAR files locally, and then upload files to servers of SPs or ship with disks.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We will look for SPs through slack and filfox, also, we'll contact some SPs via wechat groups in China.
```

How will you be distributing deals across storage providers?
```
Try to make every SP under 20% of deals. And there will be at least 5 SPs.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes
```

**Comment by oneforalone** [comment]
Is there any questions about my application? Or did i missing something? @galen-mcandrew @Kevin-FF-USA @raghavrmadya

**Comment by oneforalone** [comment]
It is estimated that our data storage demand is growing rapidly. Therefore, more DataCap needs to be applied for.

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 100TiB

**Client address**

>f13lv6rz3cuhsq436xzrnitrsatgpxo7d7zawvveq

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Looking at your application i have some questions:
As you have no history of past applications it seems to me that applying for 5PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?

Can you show us visible proof of the size of your data and the storage systems you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230232885049356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!

**Comment by Sunnyiscoming** [comment]
Hey, @oneforalone . If you still want to apply for datacap, you can ask more notaries to do client due diligence and approve the application in slack channel. https://app.slack.com/client/TEHTVS1L6/C036JKD8NVA/thread/C03BG1MNQ4T-1673888660.823499

**Comment by oneforalone** [comment]
> 

Sorry for taking so long to reply, here is the answer for your question:
1. I'm quiet familiar with Filecoin, and have some experience with operating lotus.
2. No, this is the first time i applying for DC.
3. We now stores our data to our own storage servers, the data size show as below:
<img width="363" alt="image" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/41844215/ed302b51-6e51-40b8-894e-29022f8fb014">
4. I'll fill out the form as fast as i can.

Thanks.

**Comment by oneforalone** [comment]
@Sunnyiscoming @cryptowhizzard Any updates?
