### ISSUE TITLE
[DataCap Application] <Margole> - <margole>

### ISSUE THREAD

**Issue by zhongjingyun** [filecoin-project/filecoin-plus-large-datasets#1079]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: margole
- Website / Social Media: https://www.margole.com/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 4 PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 400 TiB
- On-chain address for first allocation: f1in6t6wgo3bghmqpkikeqro5golriwzgbhou3sny

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Margole forms a strong ecosystem around decentralized leveraged trading, swap, rewards, staking, and NFTs - all of which drive Margole's future growth and decentralization to provide a better experience for users.

Margole's leveraged transactions achieve fully decentralized leveraged transactions through flash loans, pledged loans, and Swap in the DeFi ecosystem. Among them, the effect of amplifying leverage is achieved through flash loans and lending platforms. In essence, the traditional DeFi lending platform becomes a money market, and you pledge your margin on the lending platform through smart contracts to achieve leverage.
```

What is the primary source of funding for this project?
```
Corporate Strategy Fund.
```

What other projects/ecosystem stakeholders is this project associated with?
```
None
```

## Use-case details

Describe the data being stored onto Filecoin
```
Log files 、Transaction records 、  NFT works 、 pictures and videos  
```

Where was the data in this dataset sourced from?
```
margole platform
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://drive.google.com/file/d/1ARdGcJtopG49zjevkYtMPfnIs_A-n_G9/view?usp=sharing
```

Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes
```

What is the expected retrieval frequency for this data?
```
1-2 times a year
```

For how long do you plan to keep this dataset stored on Filecoin?
```
540 days 
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Asia
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
We plan to use offline services .
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We will look for storage providers on Slack, but before that we will fully consider how long they have been worked in the Filecoin network to ensure that they will help us store data safely and steadily.
```

How will you be distributing deals across storage providers?
```
Allocation is based on the storage capacity of the storage providers.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, We hope to be approved as soon as possible.
```

**Comment by zhongjingyun** [comment]
My last application was flagged，This is the previous ID #518
![img_v2_a54b46d0-6e05-4cc1-bc3f-54bcad0026bh](https://user-images.githubusercontent.com/29746390/195753805-a3d0356f-f247-4ed4-b4fe-2a6497d4ade0.png)

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 4PiB

**Expected weekly DataCap usage rate**

> 400TiB

**Client address**

>f1in6t6wgo3bghmqpkikeqro5golriwzgbhou3sny

**Comment by Sunnyiscoming** [comment]
Hey, @zhongjingyun . If you still want to apply for datacap, you can ask more notaries to do client due diligence and approve the application in slack channel. https://app.slack.com/client/TEHTVS1L6/C036JKD8NVA/thread/C03BG1MNQ4T-1673888660.823499

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Can you show us visible proof of the size of your data and the storage systems you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230337462961356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!
