### ISSUE TITLE
[DataCap Application] <Formless> - <Chain game platform>

### ISSUE THREAD

**Issue by fate-7** [filecoin-project/filecoin-plus-large-datasets#1080]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name:  formless
- Website / Social Media: https://www.formless.me/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 2PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100TiB
- On-chain address for first allocation: f1ebljmrw37nj7xlewyylrxu52bql7crcbu7vvemy

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Formless adheres to the concept of creating a GameFi version of Steam, focusing on game evaluation, publicity and incubation, and a wallet system, becoming the entrance to the GameFi world.
Expand the chain game project party, classic IP, two-dimensional animation IP, traditional game chain reform, content-driven to attract users. Provide developers with full-process support from creative incubation of game projects, one-click release of game digital assets, to operation and distribution, and provide more efficient solutions for traditional game developers to embrace the metaverse world.
Formless will build around the platform and derive various GameFi peripheral services to enrich and improve the platform ecology and help the chain game ecology achieve prosperity and development.
```

What is the primary source of funding for this project?
```
ourselves
```

What other projects/ecosystem stakeholders is this project associated with?
```
No
```

## Use-case details

Describe the data being stored onto Filecoin
```
video,pictures,data,logfile
```

Where was the data in this dataset sourced from?
```
Own Servers. 
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://drive.google.com/file/d/1mYJ6tEaceeqC7eZrgamVdBMM7jdMdDHf/view?usp=sharing
https://drive.google.com/file/d/1lPMYfKineMEfVD5juseR_5f_oZKq5G1C/view?usp=sharing
https://drive.google.com/file/d/1OEexpnpLp3Q3dukDb2sFLq0LbZPXR7Cl/view?usp=sharing
https://drive.google.com/file/d/1uJQOssbEeOqOKuyTIZu1zSM4yUrMrzzc/view?usp=sharing
```

Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes.
```

What is the expected retrieval frequency for this data?
```
2-3 times a year.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
Most of data is required to stored permanently. 
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Asia.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
We plan to transfer data offline。
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We're selecting the SPs with high reputation on slack  . They have the ability to store deals at a very fast pace and a high success rate.
```

How will you be distributing deals across storage providers?
```
We plan to find more than 5 SPs and distribute the deals equally.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
We are contacting SPs and don't need community help at this time.
```

**Comment by fate-7** [comment]
My account has been flagged. This is a duplicate application. The last ID is 
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/534
[[DataCap Application] {Formless} - {Chain game platform} · Issue #534_ - github.com.pdf](https://github.com/filecoin-project/filecoin-plus-large-datasets/files/9782176/DataCap.Application.Formless.-.Chain.game.platform.Issue.534_.-.github.com.pdf)

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 2PiB

**Expected weekly DataCap usage rate**

> 100TiB

**Client address**

>f1ebljmrw37nj7xlewyylrxu52bql7crcbu7vvemy

**Comment by Tom-OriginStorage** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacede22ldsof66wou6aaa3bkjhb6n4brcec4xte5763llaqo443x73y 
#### Address 
> f1ebljmrw37nj7xlewyylrxu52bql7crcbu7vvemy
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1q6bpjlqia6iemqbrdaxr2uehrhpvoju3qh4lpga
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacede22ldsof66wou6aaa3bkjhb6n4brcec4xte5763llaqo443x73y

**Comment by BigD-Exchange** [comment]
@fate-7 Hi! Great to see you have gotten approval for DataCap. If you are looking for storage providers to store these data or have any questions, please visit #bigdata-exchange on Filecoin Slack or reply here. 

We have strong demand from a diverse group of SPs, who are actively looking to onboard more data.

**Comment by newwebgroup** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecx2l36vbpcbfnxdqkvhslh7wapfoqvkvi4quva4rsnqxp3su6uc4 
#### Address 
> f1ebljmrw37nj7xlewyylrxu52bql7crcbu7vvemy
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1e77zuityhvvw6u2t6tb5qlnsegy2s67qs4lbbbq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecx2l36vbpcbfnxdqkvhslh7wapfoqvkvi4quva4rsnqxp3su6uc4

**Comment by fireflyHZ** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecxuf4open27na3qfkjzw2tlj33kmlgmfitkgerzluofu5zkif2pa 
#### Address 
> f1ebljmrw37nj7xlewyylrxu52bql7crcbu7vvemy
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1fg6jkxsr3twfnyhdlatmq36xca6sshptscds7xa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecxuf4open27na3qfkjzw2tlj33kmlgmfitkgerzluofu5zkif2pa

**Comment by ipfscn** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceco56tamaiu2dcodxnc5flukk6f2ek22dqukbb4ianiktbphx7sua 
#### Address 
> f1ebljmrw37nj7xlewyylrxu52bql7crcbu7vvemy
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1j4n74chme7whbz3yls4a7ixqewb6dijypqg2a3a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceco56tamaiu2dcodxnc5flukk6f2ek22dqukbb4ianiktbphx7sua

**Comment by Tom-OriginStorage** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec4rerwxsvn2ecf6zdiehuh2xwyojvx5obtlpch5l2e7srpglyavq 
#### Address 
> f1ebljmrw37nj7xlewyylrxu52bql7crcbu7vvemy
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1q6bpjlqia6iemqbrdaxr2uehrhpvoju3qh4lpga
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec4rerwxsvn2ecf6zdiehuh2xwyojvx5obtlpch5l2e7srpglyavq

**Comment by newwebgroup** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceddyzoqmwmeyzoynuxaamjh5f5o3zlp52232lx5322b2j3lgpxqv2 
#### Address 
> f1ebljmrw37nj7xlewyylrxu52bql7crcbu7vvemy
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1e77zuityhvvw6u2t6tb5qlnsegy2s67qs4lbbbq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceddyzoqmwmeyzoynuxaamjh5f5o3zlp52232lx5322b2j3lgpxqv2

**Comment by Tom-OriginStorage** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceatyhbmevokjr6aknw376w44j3i6ecdastrmndvoko65zllqs3tge 
#### Address 
> f1ebljmrw37nj7xlewyylrxu52bql7crcbu7vvemy
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1q6bpjlqia6iemqbrdaxr2uehrhpvoju3qh4lpga
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceatyhbmevokjr6aknw376w44j3i6ecdastrmndvoko65zllqs3tge

**Comment by stcouldlisa** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedlj53oxdogacngo3vbxkmkikgiatzdbv5zm5fd4kkpklev35vh7s 
#### Address 
> f1ebljmrw37nj7xlewyylrxu52bql7crcbu7vvemy
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1jvvltduw35u6inn5tr4nfualyd42bh3vjtylgci
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedlj53oxdogacngo3vbxkmkikgiatzdbv5zm5fd4kkpklev35vh7s

**Comment by newwebgroup** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedwrkjtxu6qv2ltem3fjwphye4g3lihr2erdhtsri5bpesdog3zqk 
#### Address 
> f1ebljmrw37nj7xlewyylrxu52bql7crcbu7vvemy
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1e77zuityhvvw6u2t6tb5qlnsegy2s67qs4lbbbq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedwrkjtxu6qv2ltem3fjwphye4g3lihr2erdhtsri5bpesdog3zqk

**Comment by liyunzhi-666** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedxykf7mjyalrkfvjtfgswetsrdkazdamhljndezvvi3p246o3tx6 
#### Address 
> f1ebljmrw37nj7xlewyylrxu52bql7crcbu7vvemy
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1pszcrsciyixyuxxukkvtazcokexbn54amf7gvoq
#### Id
> 89a259a7-2777-4d12-8ee0-7170d72cf596
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedxykf7mjyalrkfvjtfgswetsrdkazdamhljndezvvi3p246o3tx6

**Comment by Tom-OriginStorage** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceddwrn4h5lggxhwld4capoj4dt4ymwvkqwapuhlqjttllq7jio7ps 
#### Address 
> f1ebljmrw37nj7xlewyylrxu52bql7crcbu7vvemy
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1q6bpjlqia6iemqbrdaxr2uehrhpvoju3qh4lpga
#### Id
> 89a259a7-2777-4d12-8ee0-7170d72cf596
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceddwrn4h5lggxhwld4capoj4dt4ymwvkqwapuhlqjttllq7jio7ps

**Comment by stcouldlisa** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecl3h5kpfx5f7r43d5l53svbjh33ajww467c2ebjezrpohnllso2i 
#### Address 
> f1ebljmrw37nj7xlewyylrxu52bql7crcbu7vvemy
#### Datacap Allocated
> 498.00TiB
#### Signer Address
> f1jvvltduw35u6inn5tr4nfualyd42bh3vjtylgci
#### Id
> b8c6fbb1-02a0-4aa9-8b9d-a0df2719ea4b
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecl3h5kpfx5f7r43d5l53svbjh33ajww467c2ebjezrpohnllso2i

**Comment by Tom-OriginStorage** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec3juomsecqrwlibqharxslfwglz5fwvatjxfq6u4syzwq23facbg 
#### Address 
> f1ebljmrw37nj7xlewyylrxu52bql7crcbu7vvemy
#### Datacap Allocated
> 498.00TiB
#### Signer Address
> f1q6bpjlqia6iemqbrdaxr2uehrhpvoju3qh4lpga
#### Id
> b8c6fbb1-02a0-4aa9-8b9d-a0df2719ea4b
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec3juomsecqrwlibqharxslfwglz5fwvatjxfq6u4syzwq23facbg

**Comment by ChangeHowRan** [comment]
> ## Request Approved
> Your Datacap Allocation Request has been approved by the Notary
> 
> #### Message sent to Filecoin Network
> > bafy2bzacec3juomsecqrwlibqharxslfwglz5fwvatjxfq6u4syzwq23facbg
> 
> #### Address
> > f1ebljmrw37nj7xlewyylrxu52bql7crcbu7vvemy
> 
> #### Datacap Allocated
> > 498.00TiB
> 
> #### Signer Address
> > f1q6bpjlqia6iemqbrdaxr2uehrhpvoju3qh4lpga
> 
> #### Id
> > b8c6fbb1-02a0-4aa9-8b9d-a0df2719ea4b
> 
> #### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec3juomsecqrwlibqharxslfwglz5fwvatjxfq6u4syzwq23facbg

Hello, distinguished notary, would you sign for us?https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1251

We have 150T of data. In order to ensure data security, we need 4 backups to be stored in 4 SPs. Each SP accounted for no more than 30%.

Really need your support to move on! Thanks a lot!

**Comment by filplus-checker** [comment]
## DataCap and CID Checker Report[^1]
 - Organization: ` formless`
 - Client: `f1ebljmrw37nj7xlewyylrxu52bql7crcbu7vvemy`
### Storage Provider Distribution
The below table shows the distribution of storage providers that have stored data for this client.

If this is the first time a provider takes verified deal, it will be marked as `new`.

For most of the datacap application, below restrictions should apply.
 - Storage provider should not exceed 25% of total datacap.
 - Storage provider should not be storing duplicate data for more than 20%.
 - Storage provider should have published its public IP address.
 - All storage providers should be located in different regions.

✔️ Storage provider distribution looks healthy.

| Provider                                              |                           Location | Total Deals Sealed | Percentage | Unique Data | Duplicate Deals |
| :---------------------------------------------------- | ---------------------------------: | -----------------: | ---------: | ----------: | --------------: |
| [f01938714](https://filfox.info/en/address/f01938714) |     Sham Shui Po, Sham Shui Po, HK |         312.97 TiB |     15.30% |  312.69 TiB |           0.09% |
| [f01938718](https://filfox.info/en/address/f01938718) |    Morrisville, North Carolina, US |         312.16 TiB |     15.26% |  311.81 TiB |           0.11% |
| [f01938665](https://filfox.info/en/address/f01938665) |     Sham Shui Po, Sham Shui Po, HK |         311.63 TiB |     15.23% |  311.28 TiB |           0.11% |
| [f01938721](https://filfox.info/en/address/f01938721) | Hong Kong, Central and Western, HK |         310.13 TiB |     15.16% |  309.78 TiB |           0.11% |
| [f01938717](https://filfox.info/en/address/f01938717) |           Singapore, Singapore, SG |         308.22 TiB |     15.06% |  307.88 TiB |           0.11% |
| [f01852664](https://filfox.info/en/address/f01852664) |           Singapore, Singapore, SG |         107.94 TiB |      5.28% |  107.94 TiB |           0.00% |
| [f01852677](https://filfox.info/en/address/f01852677) |    Morrisville, North Carolina, US |         101.75 TiB |      4.97% |  101.75 TiB |           0.00% |
| [f01852023](https://filfox.info/en/address/f01852023) |                   Busan, Busan, KR |          97.28 TiB |      4.75% |   97.28 TiB |           0.00% |
| [f01852325](https://filfox.info/en/address/f01852325) | Hong Kong, Central and Western, HK |          96.06 TiB |      4.69% |   96.06 TiB |           0.00% |
| [f01851482](https://filfox.info/en/address/f01851482) |                   Busan, Busan, KR |          87.94 TiB |      4.30% |   87.94 TiB |           0.00% |

![Provider Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/1080/1671098461972.png)
### Deal Data Replication
The below table shows how each many unique data are replicated across storage providers.
- No more than 25% of unique data are stored with less than 4 providers.

✔️ Data replication looks healthy.

| Unique Data Size | Total Deals Made | Number of Providers | Deal Percentage |
| ---------------: | ---------------: | ------------------: | --------------: |
|       256.00 GiB |       512.00 GiB |                   2 |           0.02% |
|         8.00 TiB |        24.00 TiB |                   3 |           1.17% |
|        70.72 TiB |       282.88 TiB |                   4 |          13.83% |
|       347.41 TiB |         1.70 PiB |                   5 |          84.98% |

![Replication Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/1080/1671098462527.png)
### Deal Data Shared with other Clients
The below table shows how many unique data are shared with other clients.
Usually different applications owns different data and should not resolve to the same CID.

✔️ No CID sharing has been observed.

[^1]: To manually trigger this report, add a comment with text `checker:manualTrigger`
