### ISSUE TITLE
[DataCap Application] <Bitwires> - <app>

### ISSUE THREAD

**Issue by LuoSir2001** [filecoin-project/filecoin-plus-large-datasets#1081]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name:  bitwires
- Website / Social Media: https://bitwires.io/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 4PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):  300TiB
- On-chain address for first allocation: f1cok6j6hpu4uk2vmntccw4svk5yzmvoc3us5mofi

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Bitwires is a blockchain and digital currency value discovery platform based on Meta-Graph Chain (Token is BKBT), which provides users with intelligent information flow of digital currency, knowledge graph, CV-Rank (Coin Volatility Rank) index and Growth Track Index helps users find value depressions, avoid investment blind spots, popularize blockchain knowledge, and promote the healthy development of blockchain ecology.
```

What is the primary source of funding for this project?
```
ourselves
```

What other projects/ecosystem stakeholders is this project associated with?
```
No
```

## Use-case details

Describe the data being stored onto Filecoin
```
video,pictures,logs
```

Where was the data in this dataset sourced from?
```
Own Servers. 
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://drive.google.com/file/d/1D_qYzYghB_TYa7Gs-NBLwgZH_6MPTWbK/view?usp=sharing
```

Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes
```

What is the expected retrieval frequency for this data?
```
at any time
```

For how long do you plan to keep this dataset stored on Filecoin?
```
1 year or more
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Singapore or Hong Kong
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Online or Offline
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We're selecting the SPs with high reputation on slack  . They have the ability to store deals at a very fast pace and a high success rate.
```

How will you be distributing deals across storage providers?
```
We plan to find more than 5 SPs and distribute the deals equally
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes. We are ready
```

**Comment by LuoSir2001** [comment]
[My account was flagged，So I tried to reapply it](url)
![Lark20221014-112105](https://user-images.githubusercontent.com/61652893/195754907-755d379e-4685-491b-8a64-a1fc6b6cd706.png)

**Comment by Sunnyiscoming** [comment]
Hey, @LuoSir2001 
If you still want to apply for datacap, you can ask more notaries to do client due diligence and approve the application in slack channel. https://app.slack.com/client/TEHTVS1L6/C036JKD8NVA/thread/C03BG1MNQ4T-1673888660.823499

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Can you show us visible proof of the size of your data and the storage systems you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230337462961356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!
