### ISSUE TITLE
[DataCap Application] Rayfore Container

### ISSUE THREAD

**Issue by lyf054** [filecoin-project/filecoin-plus-large-datasets#1083]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Rayfore Container Industry Co.,Ltd
- Website / Social Media: http://www.qdleiyue.com/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 3.5 PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100 TiB
- On-chain address for first allocation: f1uodod76kwzklp6gwhj6trz6zpm4ukovopm7tnbq

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Qingdao Rayfore Container Industry Co.,Ltd was established in 2013, which is a professional special container and container house manufacturing enterprise integrating R&D, design, production, sales and service. The company has professional special container design team, competent container room decoration team, rich production and construction experience, can provide customers with a full range of special containers, housing container solutions.
```

What is the primary source of funding for this project?
```
Company income.
```

What other projects/ecosystem stakeholders is this project associated with?
```
No.
```

## Use-case details

Describe the data being stored onto Filecoin
```
Project data, design scheme, project design drawing, 3D design rendering, relevant product image data.
```

Where was the data in this dataset sourced from?
```
From our company.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
Yes.
https://drive.google.com/drive/folders/10ePMNl1rjOw8IdNOilPmy3BUVtjHLlcu?usp=sharing
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Confirm. and we would like our design can be seen by more people.
```

What is the expected retrieval frequency for this data?
```
One to two times per year.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
At least 3 years.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Hopefully Asia region.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
The data can be transferred both online and offline depends on SP's location and online data transfer rate.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
The stability and reachability of data is important to us. Some priority parameters: location, reputation, transmission rate, retrieval rate, etc.
```

How will you be distributing deals across storage providers?
```
We are still searching for suitable SPs and we understand the community rule that not distribute more than 25% of data to single provider. 
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, we are ready.
```

**Comment by raghavrmadya** [comment]
Samples are mostly pictures. Justify the request for 3.5 PiBs

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 3.5PiB

**Expected weekly DataCap usage rate**

> 100TiB

**Client address**

> f1uodod76kwzklp6gwhj6trz6zpm4ukovopm7tnbq

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Looking at your application i have some questions:
As you are brand new on Github and have no history of past applications it seems to me that applying for 3.5PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?

Can you show us visible proof of the size of your data and the storage systems you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230232885049356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!

**Comment by Sunnyiscoming** [comment]
Can you provide more detailed informations about yourself and SPs you will cooperate with?
Could you send an email to filplus-app-review@fil.org with your official domain in order to confirm your identity? Email name should includes the issue id #1595.
