### ISSUE TITLE
[DataCap Application] - < IvyPal >

### ISSUE THREAD

**Issue by sam001nnnhotmail** [filecoin-project/filecoin-plus-large-datasets#1084]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: IvyPal
- Website / Social Media: http://ivypal.com/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):100TiB
- On-chain address for first allocation:  f15nhptyoatd36b6oa3maw53brb5amkdxjkpxt3ha

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
IvyPal is an international education brand for children under Yijia Intelligent Technology (Shanghai) Co., Ltd. Ir is 1-1 online learningand social network program, whcih provides a platform for Chinese to learnnot only language from the native English speakers but also real-life experiences.

Founded in 2012, Yijia Intelligent Technology (Shanghai) Co., Ltd. is a high-tech enterprise focusing on collaborative interactive software technology and product development. The flying broadcast collaborative learning platform built by the company uses the world's leading mobile whiteboard technology to achieve high-performance two-way synchronization of audio, video and handwriting between mobile terminals.                                                                                                               IvyPal was co-founded by a number of Silicon Valley elites, and their children also have backgrounds in prestigious American schools. Providing the best role models for children and helping them realize their dreams of a prestigious school is one of their original intentions for founding IvyPal.                                                                   

```

What is the primary source of funding for this project?
```
Own fund & company business income

```

What other projects/ecosystem stakeholders is this project associated with?
```
Nope
```

## Use-case details

Describe the data being stored onto Filecoin
```
The data we want to store on filecoin are internet dataset which can be shared with the public. They are publicly distributable teaching courses videos/live telecast.

```

Where was the data in this dataset sourced from?
```
self-produced videos by the team

```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```

All our learning and social activities are 100% online across continents. DataCap would be used to store the recorded activities.  You can check some public channels as below: - Facebook: https://www.facebook.com/public/Ivy-Pal
- Instagram: https://www.instagram.com/ivy.pal/?hl=en
- Wechat: Ivypal-cn                                                                                                                                    There are also quite a few articles regarding Ivypal if you search from Google, Baidu, and etc.         

```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes
```

What is the expected retrieval frequency for this data?
```
Frequently
```

For how long do you plan to keep this dataset stored on Filecoin?
```
We hope it's a permanent archival, and we'll constantly update our data stored on Filecoin.

```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
China and North America

```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Offline
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We need support from North America miners and Greater China miners. Currently we prefer local SP in China.If everything goes well,we will extend it to the other region for more support. 
```

How will you be distributing deals across storage providers?
```
fairly
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
yes
```

**Comment by raghavrmadya** [comment]
What's your relationship with IvyPal?

**Comment by sam001nnnhotmail** [comment]
> What's your relationship with IvyPal?

Hi RG I am the staff in Ivypal.

**Comment by sam001nnnhotmail** [comment]
Hi is there any further comment

**Comment by simonkim0515** [comment]
Please provide a breakdown of the 5 PiBs, sample of the data, and SPs you have been in touch with as well as a detailed allocation plan.

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 100TiB

**Client address**

>f15nhptyoatd36b6oa3maw53brb5amkdxjkpxt3ha

**Comment by newwebgroup** [comment]
Hey Client，
About KYC&KYB
1：Could you send an email to [filplus-app-review@fil.org](mailto:filplus-app-review@fil.org) ？

The content should include the number of the LDN application. If possible, please attach copies of the business license and other valid certificates

2：Can you provide more detailed information about other storage providers participated in this program, such as you can list SPs you have contacted with at present?
In addition, please specify your criteria for selecting SPs. I see that your retrieval frequency is frequent.If possible, please provide specific plans and what you plan to do with SPs to meet the high frequency of retrieval.

3.How large is your existing dataset? How much is the data growth per month?

In addition, I observed that your WeChat official account is very slow to update and seems very inactive. Please explain

4. Please provide more data samples to prove that you need 5PIB storage space. There is very little data on social media, which is insufficient to support such a large amount of application demand

**Comment by sam001nnnhotmail** [comment]
Hi There

Sorry for the late reply since I got covid-19 these days.
Please see the below answers to your concern.


  1.  Could you send an email to ***@***.******@***.***> ？

Have done that.

  2.  Can you provide more detailed information about other storage providers participated in this program, such as you can list SPs you have contacted with at present? In addition, please specify your criteria for selecting SPs.

I have explained some in the application. And regarding the criteria for selecting SPs due to the high frequency of retrieval, we prefer to choose the SPs with stable network first and then the speed.

  3.  How large is your existing dataset? How much is the data growth per month?

Currently it is around 3P, and monthly growth might be around 100T.

  4.  Wechat issue

I will check with tech team.


Thanks

________________________________
发件人: newwebgroup ***@***.***>
发送时间: 2022年12月12日 14:12
收件人: filecoin-project/filecoin-plus-large-datasets ***@***.***>
抄送: Sam ***@***.***>; Author ***@***.***>
主题: Re: [filecoin-project/filecoin-plus-large-datasets] [DataCap Application] - < IvyPal > (Issue #1084)


Hey Client，
About KYC&KYB
1：Could you send an email to ***@***.******@***.***> ？

The content should include the number of the LDN application. If possible, please attach copies of the business license and other valid certificates

2：Can you provide more detailed information about other storage providers participated in this program, such as you can list SPs you have contacted with at present?
In addition, please specify your criteria for selecting SPs. I see that your retrieval frequency is frequent.If possible, please provide specific plans and what you plan to do with SPs to meet the high frequency of retrieval.

3.How large is your existing dataset? How much is the data growth per month?

In addition, I observed that your WeChat official account is very slow to update and seems very inactive. Please explain

  1.  Please provide more data samples to prove that you need 5PIB storage space. There is very little data on social media, which is insufficient to support such a large amount of application demand

―

**Comment by sam001nnnhotmail** [comment]
FYI

________________________________
发件人: chen sam ***@***.***>
发送时间: 2022年12月21日 8:56
收件人: filecoin-project/filecoin-plus-large-datasets ***@***.***>; filecoin-project/filecoin-plus-large-datasets ***@***.***>
抄送: Author ***@***.***>
主题: 回复: [filecoin-project/filecoin-plus-large-datasets] [DataCap Application] - < IvyPal > (Issue #1084)


Hi There



Sorry for the late reply since I got covid-19 these days.

Please see the below answers to your concern.



  1.  Could you send an email to ***@***.******@***.***> ？

Have done that.

  2.  Can you provide more detailed information about other storage providers participated in this program, such as you can list SPs you have contacted with at present? In addition, please specify your criteria for selecting SPs.

I have explained some in the application. And regarding the criteria for selecting SPs due to the high frequency of retrieval, we prefer to choose the SPs with stable network first and then the speed.

  3.  How large is your existing dataset? How much is the data growth per month?

Currently it is around 3P, and monthly growth might be around 100T.

  4.  Wechat issue

I will check with tech team.


Thanks

________________________________
发件人: newwebgroup ***@***.***>
发送时间: 2022年12月12日 14:12
收件人: filecoin-project/filecoin-plus-large-datasets ***@***.***>
抄送: Sam ***@***.***>; Author ***@***.***>
主题: Re: [filecoin-project/filecoin-plus-large-datasets] [DataCap Application] - < IvyPal > (Issue #1084)


Hey Client，
About KYC&KYB
1：Could you send an email to ***@***.******@***.***> ？

The content should include the number of the LDN application. If possible, please attach copies of the business license and other valid certificates

2：Can you provide more detailed information about other storage providers participated in this program, such as you can list SPs you have contacted with at present?
In addition, please specify your criteria for selecting SPs. I see that your retrieval frequency is frequent.If possible, please provide specific plans and what you plan to do with SPs to meet the high frequency of retrieval.

3.How large is your existing dataset? How much is the data growth per month?

In addition, I observed that your WeChat official account is very slow to update and seems very inactive. Please explain

  1.  Please provide more data samples to prove that you need 5PIB storage space. There is very little data on social media, which is insufficient to support such a large amount of application demand

―

**Comment by sam001nnnhotmail** [comment]
FYI

[cid:dd7512d5-b721-4a35-87a4-e7c0255b6db0]

**Comment by sam001nnnhotmail** [comment]
![FB06A9F2-AD00-4FBD-8500-46D68D9E6FD0](https://user-images.githubusercontent.com/105586380/208834551-a5c64a74-aa96-4904-b9b5-74ffcd251868.jpeg)

**Comment by newwebgroup** [comment]
1. Please list the IDs of the currently confirmed SPs
And list the network bandwidth of each SPs

2.Please provide screenshots or any evidence to prove that you have a 3P dataset

**Comment by sam001nnnhotmail** [comment]
Hi There

1.We are trying to approach some SPs within top 200 on the filescan, and not had a final decision yet. If you have a good suggestion, kindly let me know.

2.FYI as partial evidence. Btw, we plan to store 2-3 copies.
![335658C5-44CF-48CF-9E92-7502DE9DE148](https://user-images.githubusercontent.com/105586380/209467863-36160a64-17d1-47b9-85b6-2b114b409dd8.jpeg)

**Comment by kernelogic** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedviv35nfnok5pgh6gguncocnzpbp6hwb7gcqfk3y77yv7ryvvlc4 
#### Address 
> f15nhptyoatd36b6oa3maw53brb5amkdxjkpxt3ha
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### Id
> 175062c6-a4ef-4e3c-9298-45506a98dd39
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedviv35nfnok5pgh6gguncocnzpbp6hwb7gcqfk3y77yv7ryvvlc4

**Comment by kernelogic** [comment]
The client has provided enough info for me to support.

**Comment by stcouldlisa** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecuu7suvpi6o6iq4ab3hz6qqtqprxn2i4gtjfkncaziveuuercg5u 
#### Address 
> f15nhptyoatd36b6oa3maw53brb5amkdxjkpxt3ha
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1jvvltduw35u6inn5tr4nfualyd42bh3vjtylgci
#### Id
> 175062c6-a4ef-4e3c-9298-45506a98dd39
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecuu7suvpi6o6iq4ab3hz6qqtqprxn2i4gtjfkncaziveuuercg5u

**Comment by stcouldlisa** [comment]
I've been following this client for a long time, and it looks pretty good,

**Comment by herrehesse** [comment]
Dear Applicant,

Due to the increased amount of erroneous/wrong Filecoin+ data recently, on behalf of the entire community, we feel compelled to go deeper into datacap requests. Hereby to ensure that the overall value of the Filecoin network and Filecoin+ program increases and is not abused.

Please answer the questions below as comprehensively as possible.

**Customer data**

- Could you demonstrate exactly how and to what extent customer contact occurred? 

We expect that for the onboarding of customers with the scale of an LDN there would have been at least multiple email and perhaps several chat conversations preceding it. A single email with an agreement does not qualify here.

- Did the customer specify the amount of data involved in this relevant correspondence?

- Why does the customer in question want to use the Filecoin+ program? 

_Should this only be soley for acquiring datacap this is of course **out of the question**. The customer must have a legitimate reason for wanting to use the Filecoin+ program which is intended as a program to store useful and public datasets on the network._ 

- Why is the customer data considered Filecoin+ eligible?

_(As an intermediate solution Filecoin offers the FIL-E program or the glif.io website for business datasets that do not meet the requirements for a Filecoin+ dataset)_


**Files and Processing**

- Could you please demonstrate to us how you envision processing and transporting the customer data in question to any location for preparation?
- Would you demonstrate to us that the customer, the preparer and the intended storage providers all have adequate bandwidth to process the set with its corresponding size?
- Would you tell us how the data set preparer takes into account the prevention of duplicates in order to prevent data cap abuse?


Hopefully you understand the caution the overall community has for onboarding the wrong data. We understand the increased need for Filecoin+, however, we must not allow the program to be misused. Everything depends on a valuable and useful network, let's do our best to make this happen. Together.

**Comment by sam001nnnhotmail** [comment]
Hi There

Welcome the concerns here.
I may not understand all of them clearly, but would like to answer them as much as I can.Hope it can be useful.
Though they are various questions,I prefer to sort them out into 2 groups ,and then I will answer them respectively and comprehensively. Thanks

Group 1:
Could you demonstrate exactly how and to what extent customer contact occurred?
Did the customer specify the amount of data involved in this relevant correspondence?
Why does the customer in question want to use the Filecoin+ program?
Why is the customer data considered Filecoin+ eligible?
Answer: 
All videos/materials are produced and owned by ourselves.
Why we choose Filecoin+. 
We ever attended another project in Filecoin and had smooth experience and great support as expected. So we decide to try Filecoin+ after evaluation - we are qualified.
    
Gourp 2:
Could you please demonstrate to us how you envision processing and transporting the customer data in question to any location for preparation?

Would you demonstrate to us that the customer, the preparer and the intended storage providers all have adequate bandwidth to process the set with its corresponding size?

Would you tell us how the data set preparer takes into account the prevention of duplicates in order to prevent data cap abuse?
Answer: 
China and North America firstly, and then depends on the resources in hand.
10G bandwidth is required.
If you mean how many copies we plan to store for the data - 3 copies

Hopefully you understand the caution the overall community has for onboarding the wrong data. We understand the increased need for Filecoin+, however, we must not allow the program to be misused. Everything depends on a valuable and useful network, let's do our best to make this happen. Together.
Response:
This is the common goal we share together.
Appreciate that.

**Comment by BDEio** [comment]
@sam001nnnhotmail Hi! Great to see that you have gotten approval for DataCap!
BDE is a verified deals auction house helping you to get paid storing your data with reliable storage providers. If you need any help, please get in touch.

**Comment by herrehesse** [comment]
@sam001nnnhotmail Thank you for your answer.

"after evaluation - we are qualified." Self produced video's by your team do not qualify for datacap. You claim to have private data and this is just not the right place for you.

Maybe you can try to store your data on Filecoin through regular deals? Can I help?

**Comment by cryptowhizzard** [comment]
Hello,

You stated "The data we want to store on filecoin are internet dataset which can be shared with the public. They are publicly distributable teaching courses videos/live telecast."

However , i see you are storing data from NFTSTAR and that application #960 is blacklisted because of CID sharing and fraudulent behaviour. Please explain what the goal is of this application and what you intend to store.

I would also like to see a list of CID of the dataset you have build so that we can see that data that you are going to distribute.

**Comment by sam001nnnhotmail** [comment]
Hey


Regarding data sharing issue you mentioned, we have checked and the main reason is when SP processes the data, there is some technical oversight in steps. For the SPs which have been checked out for some mishandling, we will not work with them anymore.
We will reach out to the qualified SPs which support public retrieval and provide CID. We will require SPs to do due diligence on multi-layers verification for further data processing.


Thanks for your timely callout.
I guarantee no data sharing anymore in future and look forward to further support from the community and you.

________________________________
发件人: CryptoWhizzard ***@***.***>
发送时间: 2023年1月13日 21:18
收件人: filecoin-project/filecoin-plus-large-datasets ***@***.***>
抄送: Sam ***@***.***>; Mention ***@***.***>
主题: Re: [filecoin-project/filecoin-plus-large-datasets] [DataCap Application] - < IvyPal > (Issue #1084)


Hello,

You stated "The data we want to store on filecoin are internet dataset which can be shared with the public. They are publicly distributable teaching courses videos/live telecast."

However , i see you are storing data from NFTSTAR and that application #960<https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/960> is blacklisted because of CID sharing and fraudulent behaviour. Please explain what the goal is of this application and what you intend to store.

I would also like to see a list of CID of the dataset you have build so that we can see that data that you are going to distribute.

―

**Comment by cryptowhizzard** [comment]
Hello @sam001nnnhotmail 

>>
I would also like to see a list of CID's of the dataset you have build so that we can see that data that you are going to distribute.
>>
