### ISSUE TITLE
[DataCap Application] <Henan Huandixu Trading Co., LTD., R & D> - <Data Backup>

### ISSUE THREAD

**Issue by zhujiaqi** [filecoin-project/filecoin-plus-large-datasets#1085]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Henan Huandixu Trading Co., LTD., R & D
- Website / Social Media: https://www.huandixu.com/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5 PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100 TiB
- On-chain address for first allocation: f1dmjsw3otkvkh6sy3hygy6ebgs43o3i74qyg52gq

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Henan Huandixu Trading Co., LTD., R & D, production and sales of all kinds of doors and Windows products, products cover the series of open doors and Windows, sliding doors and Windows, heavy folding doors, insulation broken bridge window series and other kinds, is a modern private enterprise.
```

What is the primary source of funding for this project?
```
Company.
```

What other projects/ecosystem stakeholders is this project associated with?
```
None.
```

## Use-case details

Describe the data being stored onto Filecoin
```
Design video, design pictures, design materials.
```

Where was the data in this dataset sourced from?
```
Internal and public resources.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://drive.google.com/drive/folders/15BvUVjsfPy1B0pwbV2gGU5NQdxroJz3H?usp=sharing
https://drive.google.com/drive/folders/1IDBkej46SHhWUK1jYPbLt3SiFywx3m1P?usp=sharing
https://drive.google.com/drive/folders/1RzHJhkwrrmsn1CsNPoSkgn0Q_IZWBRJQ?usp=sharing
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes.
```

What is the expected retrieval frequency for this data?
```
1-2 times a year.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
540 Days.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Hongkong/Singapore/Korea/America.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Offline transfer.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We choose SPs based on geographic location and the quality of service the SPs provide.
```

How will you be distributing deals across storage providers?
```
We have about 610t data to store 5 SPs.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes. f01938665,f01852677,f01851482,f01852325,f01938721
```

**Comment by zhujiaqi** [comment]
Hello, how is the progress of our project? Is there any problem?

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 100TiB

**Client address**

> f1dmjsw3otkvkh6sy3hygy6ebgs43o3i74qyg52gq

**Comment by ipfscn** [comment]
Can you email filplus-app-review@fil.org using your official domain name to confirm your identity?
Email name should contain Issue ID #1085.

**Comment by zhujiaqi** [comment]
@ipfscn Hi, I have sent the email. Please help confirm. Thank you!
![1671581388070](https://user-images.githubusercontent.com/1013211/208790600-4fa960e2-d555-4973-abb0-dbe4fce01729.png)

**Comment by ipfscn** [comment]
Can your sp meet your retrieval requirements
Can you list the SP you work with

**Comment by zhujiaqi** [comment]
@ipfscn  Hi,Thank you for your reply.
Yes,Sp can meet retrieval requirements.
At present, we have contacted the following sp.
f01938665,f01852677,f01851482,f01852325,f01938721

**Comment by ipfscn** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacea67vnivh3ym3x6nb3kucjbugwxusaziwvj5atud4p32r5gknnwoc 
#### Address 
> f1dmjsw3otkvkh6sy3hygy6ebgs43o3i74qyg52gq
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1j4n74chme7whbz3yls4a7ixqewb6dijypqg2a3a
#### Id
> 6a3c42f9-acb4-426a-8217-6fa473e8674c
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacea67vnivh3ym3x6nb3kucjbugwxusaziwvj5atud4p32r5gknnwoc

**Comment by Tom-OriginStorage** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedyb2jb7yvgjjpunmk4ve4curlt5s7aywkxxspgf4ihs6ghcm3ysa 
#### Address 
> f1dmjsw3otkvkh6sy3hygy6ebgs43o3i74qyg52gq
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1q6bpjlqia6iemqbrdaxr2uehrhpvoju3qh4lpga
#### Id
> 6a3c42f9-acb4-426a-8217-6fa473e8674c
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedyb2jb7yvgjjpunmk4ve4curlt5s7aywkxxspgf4ihs6ghcm3ysa

**Comment by cryptowhizzard** [comment]
Hello,

Above i see a different email address then stated on the website.

mailto:mail@huandixu.com Seems the on the website. A different one @gmail is used for KYC.

@ipfscn or @Tom-OriginStorage : did you do the KYC here or duedilligence?

Why does this data qualify for FIL+ and not FIL-E where it belongs since this is commercial data? And is 5 PB not way more then needed here for some brochures backup of a private company producing doors and windows?

**Comment by herrehesse** [comment]
@ipfscn @Tom-OriginStorage 

The described data indeed fits as company/business data., which is not suited for a LDN application for the Filecoin+ program. Please assist the applicant towards the FIL-E program.

"Design video, design pictures, design materials."

**Comment by zhujiaqi** [comment]
Hello, thank you for your reply, do you have any problems with our project? 
1.We use the administrator mailbox to send KYC emails, admin@huandixu.com.
2.When we launched the application, there was no FIL-E program.
3.After a long wait, our project has finally started. Do you want us to reapply now? This will cause us unnecessary losses if we have to wait a long time, which is the result we don't want to see. We hope to be able to continue this project, and our data has been transferred to the relevant SPs in a variety of modes, both online and offline, and has been started.
Looking forward to your reply, thank you! @cryptowhizzard @herrehesse

**Comment by herrehesse** [comment]
Best applicant,

It is great to hear how much you have already done regarding the preparation of the dataset in question. It would be an extreme shame to undo all this work so let's work together to make sure it doesn't.

Fortunately, preparation, processing and storage on the Filecoin network is separate from datacap. So you can just continue with the storage providers only now on the basis of:

1. Regular deals (1/100th lower cost compared to AWS)
2. Application for FIL-E

As stated above, the data does not meet the requirements for getting datacap from the Filecoin+ program.

Should I be able to help you further I would be happy to hear from you.

**Comment by cryptowhizzard** [comment]
@zhujiaqi 

As you can see here a @gmail address is used for KYC by you or was that a CC?

![Scherm­afbeelding 2023-01-09 om 15 44 00](https://user-images.githubusercontent.com/36404435/211334948-9181a943-04eb-40cb-8aa1-081e7d0dffbf.png)

**Comment by zhujiaqi** [comment]
> @zhujiaqi
> 
> As you can see here a @gmail address is used for KYC by you or was that a CC?
> 
> ![Scherm­afbeelding 2023-01-09 om 15 44 00](https://user-images.githubusercontent.com/36404435/211334948-9181a943-04eb-40cb-8aa1-081e7d0dffbf.png)

Cc mail is only to ensure that the mail is sent normally. There is no other intention.

**Comment by zhujiaqi** [comment]
> Best applicant,
> 
> It is great to hear how much you have already done regarding the preparation of the dataset in question. It would be an extreme shame to undo all this work so let's work together to make sure it doesn't.
> 
> Fortunately, preparation, processing and storage on the Filecoin network is separate from datacap. So you can just continue with the storage providers only now on the basis of:
> 
> 1. Regular deals (1/100th lower cost compared to AWS)
> 2. Application for FIL-E
> 
> As stated above, the data does not meet the requirements for getting datacap from the Filecoin+ program.
> 
> Should I be able to help you further I would be happy to hear from you.

I don't quite understand what I need to do to ensure the smooth progress of my project. I think I hope your help! thank you!
@herrehesse

**Comment by BDEio** [comment]
@zhujiaqi Hi! Congratulations on your DataCap approval！
BDE is a trusted deals auction house helping you to get paid storing your data with reliable storage providers. If you need any help, please get in touch.

**Comment by NDLABS-OFFICE** [comment]
The data storage situation looks good and is willing to support

**Comment by NDLABS-OFFICE** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced4zcnxijvectro4ejgrtphrechzten53ptkspuhw4bxdwfv53vcy 
#### Address 
> f1dmjsw3otkvkh6sy3hygy6ebgs43o3i74qyg52gq
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1yayfsv6whu3rheviucvventj3y6t542xfpb47ei
#### Id
> 6a25de97-9389-4fa1-a338-f5b463aea9f9
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced4zcnxijvectro4ejgrtphrechzten53ptkspuhw4bxdwfv53vcy

**Comment by stcouldlisa** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceble632libl3yga3atkix6hxzp3jtv5237y2m72h5vb4ibh7echmo 
#### Address 
> f1dmjsw3otkvkh6sy3hygy6ebgs43o3i74qyg52gq
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1jvvltduw35u6inn5tr4nfualyd42bh3vjtylgci
#### Id
> 6a25de97-9389-4fa1-a338-f5b463aea9f9
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceble632libl3yga3atkix6hxzp3jtv5237y2m72h5vb4ibh7echmo

**Comment by stcouldlisa** [comment]
I received the customer's request. This is the second round of the customer. I tend to support it. However, once I find that the customer has not complied with the rules, I will never help him again,

**Comment by newwebgroup** [comment]
checker:manualTrigger

**Comment by newwebgroup** [comment]
After checking the CID Checker report, there is no CID sharing, the SP location is very scattered, and the proportion distribution is healthy.

**Comment by newwebgroup** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceawdmwlixmpp424lj3jotyq42nrlh4uvdtkagusgvcpkrbx7yhzbw 
#### Address 
> f1dmjsw3otkvkh6sy3hygy6ebgs43o3i74qyg52gq
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1e77zuityhvvw6u2t6tb5qlnsegy2s67qs4lbbbq
#### Id
> 8c911108-7ea9-4caa-baa2-6b7436dcbf52
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceawdmwlixmpp424lj3jotyq42nrlh4uvdtkagusgvcpkrbx7yhzbw

**Comment by cryptowhizzard** [comment]
Hello 

None of the data is retrievable. This is agains FIL+ LDN rules and should have been checked first @newwebgroup 

[f0397376.log](https://github.com/filecoin-project/filecoin-plus-large-datasets/files/10418119/f0397376.log)

**Comment by newwebgroup** [comment]
@cryptowhizzard 
Sincere thanks for your flags and reminders,
I'm sorry, because I don't know the language development, so I don't have the ability to do some deeper inspections through Lotus.
I will unsign this until further improvements and explanations are made by the Client.

**Comment by zhujiaqi** [comment]
Can you tell me how to carry out this inspection? I want to try it myself, and then find the SP that serves us to solve it.

**Comment by cryptowhizzard** [comment]
Hi @zhujiaqi 

You are confusing me. If you don’t know how to retrieve your data, what is the use of doing thus exercise then?

**Comment by zhujiaqi** [comment]
Sorry, maybe my expression is not accurate, I think you have a better way to help me retrieve the data, I want to learn it to better ensure that our project goes smoothly. lotus client retrieve is the way I currently use it.
Thank you for the problem you found. We have actively contacted sp to solve it. @cryptowhizzard

**Comment by cryptowhizzard** [comment]
Hello,

"lotus client retrieve" is the same way i do it here.

Please let us know when this is resolved so i can test retrievals and we can get this application on track again in line with the FIL+ rules.

**Comment by zhujiaqi** [comment]
checker:manualTrigger

**Comment by C00kies77** [comment]
checker:manualTrigger
