### ISSUE TITLE
[DataCap Application] Curious Games Technology Co., Ltd.

### ISSUE THREAD

**Issue by curiousgamess** [filecoin-project/filecoin-plus-large-datasets#1088]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Curious Games Technology Co., Ltd.
- Website / Social Media:http://curiousgamess.com/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):500TIB
- On-chain address for first allocation: f1gqhblfupimeeasn2vuoyopfefphfw2cmmgrlwuq

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
curiousgames was founded in 2019. With nearly 100 employees, CuriousGames focuses on online game publishing and is an outstanding game publishing company in China.
The founder team of the company has cooperated with Pig Man, dragon fighter, Guobao Special attack and other well-known animation IP to produce dozens of classic mobile games, the core team has mature project operation and release experience.
The company's products cover tower defense strategy, role-playing, Roguelike cards and other types, and has successfully launched more than 10 popular products, with more than 10 million registered users worldwide.
In recent years, the overseas business has grown rapidly, covering Hong Kong, Macao and Taiwan, the Middle East, Japan, Thailand, Vietnam and other regions and countries.
```

What is the primary source of funding for this project?
```
We are fully funded
```

What other projects/ecosystem stakeholders is this project associated with?
```
No one
```

## Use-case details

Describe the data being stored onto Filecoin
```
Game promotional videos, pictures, gameplay guide videos and other relevant public data.
```

Where was the data in this dataset sourced from?
```
The data source comes from videos recorded by our in-house promotional team, as well as videos recorded by professional gamers we work with
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://drive.google.com/drive/folders/1LKYPc6obk1ov9PM8bcjcWaCkmlXo2-Y1?usp=sharing
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes.
```

What is the expected retrieval frequency for this data?
```
once every two months.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
I hope it will be preserved forever, if not, it should be preserved for at least three years.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
global.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
It can be both on-chain and off-chain, but mainly off-chain.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We will consider the stability of the nodes and the speed of accessing the network.
If SP can support fast retrieval, we will preferentially choose.
```

How will you be distributing deals across storage providers?
```
Fair distribution. We want multiple storage providers to store our data.
 
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, I do. 
```

**Comment by curiousgamess** [comment]
@raghavrmadya

**Comment by curiousgamess** [comment]
Hello, what can I do for you? Continue to wait?

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 500TiB

**Client address**

> f1gqhblfupimeeasn2vuoyopfefphfw2cmmgrlwuq

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 500TiB

**Client address**

> f1gqhblfupimeeasn2vuoyopfefphfw2cmmgrlwuq

**Comment by xiaoyuaiheshui** [comment]
1. Please show us some screenshots that can prove there is so much data.
2. Have you establish cooperation with storage providers? If yes, please list them. If not, please explain how to find them.

**Comment by curiousgamess** [comment]
https://drive.google.com/drive/folders/1LKYPc6obk1ov9PM8bcjcWaCkmlXo2-Y1?usp=sharing

**Comment by curiousgamess** [comment]
Hello, the following link is a sample of our game's promotional and teaching videos.
https://drive.google.com/drive/folders/1LKYPc6obk1ov9PM8bcjcWaCkmlXo2-Y1?usp=sharing
In addition, We have reached a cooperative relationship with some miners:
f01907578
f01153105
f01815391
We have not yet reached a cooperative relationship withstorage providers  above,  and we will cooperate with any storage providers capable of ensuring data security. Regarding how to find them,  when the LDN application is approved, we accept the invitation of any storage providers

**Comment by Tom-OriginStorage** [comment]
it looks good i will sign it

**Comment by curiousgamess** [comment]
<img width="813" alt="image" src="https://user-images.githubusercontent.com/115967403/208387375-bd89770b-b2f0-45b9-ab78-9d36f780393b.png">

**Comment by curiousgamess** [comment]
Hello, I have sent the email.
In addition, our data sample link is:
https://drive.google.com/drive/folders/1LKYPc6obk1ov9PM8bcjcWaCkmlXo2-Y1?usp=sharing
We store mostly promotional and instructional videos for the game.

**Comment by Tom-OriginStorage** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebjeknd4qjp5fxmajpmruq2c6qwvotcfvuq3eqpbm7l6p5fnsd6ss 
#### Address 
> f1gqhblfupimeeasn2vuoyopfefphfw2cmmgrlwuq
#### Datacap Allocated
> 250.00TiB
#### Signer Address
> f1q6bpjlqia6iemqbrdaxr2uehrhpvoju3qh4lpga
#### Id
> 54b6f02f-c6f8-426e-9215-c9db4b5b2868
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebjeknd4qjp5fxmajpmruq2c6qwvotcfvuq3eqpbm7l6p5fnsd6ss

**Comment by curiousgamess** [comment]
checker:manualTrigger

**Comment by curiousgamess** [comment]
checker:manualTrigger

**Comment by curiousgamess** [comment]
Because of the limited number of backups of our first batch of data, each storage provider only gets a portion of the data, and the next round will mail each other.

**Comment by NDLABS-OFFICE** [comment]
![image](https://user-images.githubusercontent.com/104019147/217139490-c83f8075-83f9-4caf-a7ea-3baff427d973.png)
![image](https://user-images.githubusercontent.com/104019147/217139573-aa4e93e0-6523-4b0b-a59d-0019848d2dae.png)
![image](https://user-images.githubusercontent.com/104019147/217139616-819d36fb-e9fa-4086-afd6-2c947acfdd5c.png)
![image](https://user-images.githubusercontent.com/104019147/217139656-cf72575e-a792-4aa6-83bb-6faec719513e.png)
![image](https://user-images.githubusercontent.com/104019147/217139701-834408b4-a3f8-4605-b3f0-0a8b2764b95e.png)
![image](https://user-images.githubusercontent.com/104019147/217139764-f601391f-9d11-40e6-8069-7a2f07a7eb01.png)

Check bot's inspection is good, and the connectivity test of the currently stored sp nodes is carried out. Currently, all nodes support retrieval, fully compliant, and willing to support.

**Comment by NDLABS-OFFICE** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecsui2o4rufg2fzepscddtudf4rwitdzu2xnagzj552d3lm4dtocc 
#### Address 
> f1gqhblfupimeeasn2vuoyopfefphfw2cmmgrlwuq
#### Datacap Allocated
> 500.00TiB
#### Signer Address
> f1yayfsv6whu3rheviucvventj3y6t542xfpb47ei
#### Id
> 59863f37-aa13-4b24-ab4f-c95ca36a2cec
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecsui2o4rufg2fzepscddtudf4rwitdzu2xnagzj552d3lm4dtocc

**Comment by YuanHeHK** [comment]
I went through the previous verification information and checked that I didn't find anything unusual. Support this app.

**Comment by YuanHeHK** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebjgkaoa5tfsopdnilvvuspp7wwkmyilmwukv735ueih2vtew2uuw 
#### Address 
> f1gqhblfupimeeasn2vuoyopfefphfw2cmmgrlwuq
#### Datacap Allocated
> 500.00TiB
#### Signer Address
> f1fg6jkxsr3twfnyhdlatmq36xca6sshptscds7xa
#### Id
> 59863f37-aa13-4b24-ab4f-c95ca36a2cec
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebjgkaoa5tfsopdnilvvuspp7wwkmyilmwukv735ueih2vtew2uuw

**Comment by cryptowhizzard** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaezaw7opr7zju5n7sbxyjqn2zp3z64vw7d6w2phbrhubvmyn2ycy 
#### Address 
> f1gqhblfupimeeasn2vuoyopfefphfw2cmmgrlwuq
#### Datacap Allocated
> 1000.00TiB
#### Signer Address
> f1krmypm4uoxxf3g7okrwtrahlmpcph3y7rbqqgfa
#### Id
> 7feb4347-6ecf-497e-8a16-371cb99fc5eb
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaezaw7opr7zju5n7sbxyjqn2zp3z64vw7d6w2phbrhubvmyn2ycy

**Comment by cryptowhizzard** [comment]
Retrieval works. I have downloaded some files. For those who want to check what i have downloaded -> 

http://www.datasetcreators.com:81/downloadedcarfiles/f01996948-f01907578-baga6ea4seaqatxxc4wti5nqtrkoicdjqtodomv3aenyqxn7fwwl4es2v3vgqwhq.car1/

Cheers.

**Comment by herrehesse** [comment]
@curiousgamess 

Please resolve distribution before further support. More regions than china only are required.
Also resolve "100.00% of deals are for data replicated across less than 3 storage providers"

Content is retrievable. That is good.

**Comment by cryptowhizzard** [comment]
Adding :

Yesterday evening i watched other video's then the link above.

http://www.datasetcreators.com/downloadedcarfiles/ldncheckedok/f01996948-f01907578-baga6ea4seaqaaq6uynxwel2ppuh5ws2nrambfojg4xgy7tjmlxwi6nrjkas5anq.car1/

**Comment by curiousgamess** [comment]
Thank you for your suggestion. In the following process, we will store the data in more regions (outside China) and continue to maintain the standard operation.

**Comment by curiousgamess** [comment]
checker:manualTrigger

**Comment by curiousgamess** [comment]
checker:manualTrigger

**Comment by curiousgamess** [comment]
checker:manualTrigger

**Comment by curiousgamess** [comment]
checker:manualTrigger

**Comment by curiousgamess** [comment]
checker:manualTrigger

**Comment by curiousgamess** [comment]
checker:manualTrigger

**Comment by xingjitansuo** [comment]
<img width="580" alt="test" src="https://user-images.githubusercontent.com/72185104/219021285-95727aa6-4d82-491d-b3a4-0a017428c880.png">
 
Reasonable distribution and retrieval supported. I am willing to approve for this tranche.

**Comment by xingjitansuo** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec65bscvoumxptm6sqr7gmg7l4gtjudggikk6rz4d2k6buqgwf73o 
#### Address 
> f1gqhblfupimeeasn2vuoyopfefphfw2cmmgrlwuq
#### Datacap Allocated
> 1000.00TiB
#### Signer Address
> f1a2lia2cwwekeubwo4nppt4v4vebxs2frozarz3q
#### Id
> 7feb4347-6ecf-497e-8a16-371cb99fc5eb
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec65bscvoumxptm6sqr7gmg7l4gtjudggikk6rz4d2k6buqgwf73o

**Comment by curiousgamess** [comment]
checker:manualTrigger

**Comment by pinwest** [comment]
@xiaoyuaiheshui @cryptowhizzard 
Deal Data Replication
⚠️ 89.44% of deals are for data replicated across less than 4 storage providers.

SP's has completely disregarded the rules of storing data with all four storage providers, and the company ceased operations in 2019, so there should not be any 5P data. 
You need to prepare for the auditor's review.

**Comment by curiousgamess** [comment]
checker:manualTrigger

**Comment by curiousgamess** [comment]
I was very shocked...
I've explained the problem of data backup above. And I always check manually. Please take a closer look.
Who are you? I notice you're a new user? I have to suspect you're messing around. I want you to see people as they really are. It's easy to make something out of nothing. I hope you're not too keen on being a clown.

**Comment by curiousgamess** [comment]
Shocked...
I've explained the problem of data backup above. And I always check manually. Please take a closer look.
Who are you? I notice you're a new user? I have to suspect you're messing around. I want you to tell everyone who you are. It's easy to make something out of nothing. I hope you're not too keen on being a clown.

**Comment by pinwest** [comment]
Your answer is very interesting, ecological development everyone has the right to regulate. There are two problems you haven't solved yet:
1. SPs are not spread across different continents. 
2. 80.07% of transactions were data replicated between fewer than 4 storage providers. 
I will follow up on this matter.

**Comment by curiousgamess** [comment]
checker:manualTrigger

**Comment by curiousgamess** [comment]
checker:manualTrigger

**Comment by curiousgamess** [comment]
checker:manualTrigger

**Comment by curiousgamess** [comment]
Hello notaries, we have always followed the FIL+ rules, but there are some situations that I must explain.

For our first batch of data, we provided the original files to the SPs to process into car files, but the resulting car files were not standardized. This is also why our 217TB of data is unique. Therefore, we processed the data ourselves from then on. However, this led to a situation in the second batch of data transmission, where an SP's car file was duplicated with the car they processed previously. As a result, 1192 duplicate orders were placed.

But we assure you that this will not happen again.

**Comment by kernelogic** [comment]
It doesn't look like this company has ceased operation.  See https://www.tianyancha.com/sicp/3391592506-ac05

![image](https://user-images.githubusercontent.com/3711825/221773339-1ae76be4-a821-4461-9a81-fb4ef2f31c7b.png)

**Comment by swatchliu** [comment]
checker:manualTrigger

**Comment by curiousgamess** [comment]
Yes, I can guarantee that.

**Comment by swatchliu** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec5douxg5lox64ndaqw6c3wzwhbz4ausbbprnalwddnun7ukrgmre 
#### Address 
> f1gqhblfupimeeasn2vuoyopfefphfw2cmmgrlwuq
#### Datacap Allocated
> 1000.00TiB
#### Signer Address
> f1yh6q3nmsg7i2sys7f7dexcuajgoweudcqj2chfi
#### Id
> 7feb4347-6ecf-497e-8a16-371cb99fc5eb
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec5douxg5lox64ndaqw6c3wzwhbz4ausbbprnalwddnun7ukrgmre

**Comment by newwebgroup** [comment]
Client found me via Slack

Trying to retrieve retrieve some of the SP's data, the network transfer was very fast. 😊

Reviewed the Github history of this LDN, KYB validation is complete.
Received verification and support from multiple notaries.

Willing to support in this round

<img width="936" alt="image" src="https://user-images.githubusercontent.com/100118145/222034773-d8413741-b9b3-4533-b4fa-09157444069e.png">
<img width="941" alt="image" src="https://user-images.githubusercontent.com/100118145/222035480-20574bcd-ce88-45db-a9dc-c203a0f721ec.png">

<img width="941" alt="image" src="https://user-images.githubusercontent.com/100118145/222035859-a1ea7e95-3963-4870-bf82-479474cd7a19.png">
<img width="941" alt="image" src="https://user-images.githubusercontent.com/100118145/222036076-c8967d70-5ce2-4c26-b8d8-25c0db3e0923.png">

**Comment by newwebgroup** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaftefpecn76ojco52paoytfvs6ej6l44n7nsg7w3cqqww3slsfjo 
#### Address 
> f1gqhblfupimeeasn2vuoyopfefphfw2cmmgrlwuq
#### Datacap Allocated
> 1000.00TiB
#### Signer Address
> f1e77zuityhvvw6u2t6tb5qlnsegy2s67qs4lbbbq
#### Id
> 7feb4347-6ecf-497e-8a16-371cb99fc5eb
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaftefpecn76ojco52paoytfvs6ej6l44n7nsg7w3cqqww3slsfjo

**Comment by newwebgroup** [comment]
I managed to retrieve a Car and was able to open it properly.
Checking the content found that it is consistent with the company the content belongs to.
The content of the Car is: demo and commentary video of the game

<img width="785" alt="image" src="https://user-images.githubusercontent.com/100118145/222040253-5857c1cd-653d-4456-88e4-eb887af79c63.png">
<img width="578" alt="image" src="https://user-images.githubusercontent.com/100118145/222040257-fabb4fa3-8906-4d9f-8733-9c947e2dcb42.png">


<img width="922" alt="image" src="https://user-images.githubusercontent.com/100118145/222040172-971a0fa5-1646-497b-b775-c0a45422d753.png">

**Comment by curiousgamess** [comment]
checker:manualTrigger

**Comment by curiousgamess** [comment]
Regarding the problem of CID sharing, it is because f02028326 took our car file and sent an order with their wallet for testing.
![2771677834663_ pic](https://user-images.githubusercontent.com/115967403/222679829-8cb7388b-dc63-4633-a292-ea63f56359e5.jpg)

**Comment by curiousgamess** [comment]
checker:manualTrigger

**Comment by curiousgamess** [comment]
checker:manualTrigger

**Comment by igoovo** [comment]
checker:manualTrigger

**Comment by laurarenpanda** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedklovbzvsfddgzjc25s2jwx65newcmsdkxqsviqveohbt4pbq2z4 
#### Address 
> f1gqhblfupimeeasn2vuoyopfefphfw2cmmgrlwuq
#### Datacap Allocated
> 1.95PiB
#### Signer Address
> f1bp3tzp536edm7dodldceekzbsx7zcy7hdfg6uzq
#### Id
> 70c5d444-3b91-4706-876b-e1df307cfb37
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedklovbzvsfddgzjc25s2jwx65newcmsdkxqsviqveohbt4pbq2z4

**Comment by newwebgroup** [comment]
checker:manualTrigger

**Comment by newwebgroup** [comment]
A search test was done on this LDN in the previous round and everything was fine.
This round, I did the retrieval test again and it also showed normal, so I am willing to choose to support it again given that it has good performance after all.
./lotus client retrieve --provider f02051391 bafybeieqiguhacfmc573edrwtdkysudeuoc2ull27j33duesgvjwx5nkxm .LDN-1088-1
<img width="1214" alt="image" src="https://user-images.githubusercontent.com/100118145/225543873-71353a18-0840-4ecd-b472-62c9d85df061.png">

**Comment by newwebgroup** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedyrcu2os7gc3gexbvf24e6jxlqhgivkoya7755xabhumcm7fbkiq 
#### Address 
> f1gqhblfupimeeasn2vuoyopfefphfw2cmmgrlwuq
#### Datacap Allocated
> 1.95PiB
#### Signer Address
> f1e77zuityhvvw6u2t6tb5qlnsegy2s67qs4lbbbq
#### Id
> 70c5d444-3b91-4706-876b-e1df307cfb37
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedyrcu2os7gc3gexbvf24e6jxlqhgivkoya7755xabhumcm7fbkiq

**Comment by curiousgamess** [comment]
checker:manualTrigger

**Comment by C00kies77** [comment]
checker:manualTrigger
