### ISSUE TITLE
[DataCap Application] - F00tage

### ISSUE THREAD

**Issue by Irenafootage** [filecoin-project/filecoin-plus-large-datasets#1089]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: F00TAGE 
- Website / Social Media: https://twitter.com/F00tageofficial                                                                                                      
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100TiB
- On-chain address for first allocation: f16efumcgpjamyhfrflxsu2brd7wrhniqwqssfpzq

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Footage was launched by a group of film-loving creators, independent filmmakers, Internet community members, and Hollywood professional production teams. Currently committed to gathering more video creators, independent filmmakers, and web3 practitioners who like movies. Together, we will explore the infinite possibilities of movies on Web3, jointly forge the new future of movies, and let more independent filmmakers be seen.
```
What is the primary source of funding for this project?
```
Own fund
```

What other projects/ecosystem stakeholders is this project associated with?
```
nope
```

## Use-case details

Describe the data being stored onto Filecoin
```
The dataset we plan to store on filecoin are some creative videos/films archive produced by video creators and independent filmmakers which can be and are supposed to be  shared with the public. Our goal is to let thousands of independent productions to shine through Web3 spirit and technology. Also, we will mint some NFT and launch it soon. 
```

Where was the data in this dataset sourced from?
```
self-produced videos/films archive
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
Currently we have a group of F00tage community builders who are video creators and independent filmmakers. You can refer to the creation from some of them who want to work with us to transfer their love and products into Web3 world. As well, If you need, we can provide our testnet with code for your reference. https://space.bilibili.com/28644104?spm_id_from=333.337.0.0 https://space.bilibili.com/37992622/?spm_id_from=333.999.0.0 https://space.bilibili.com/31071444/?spm_id_from=333.999.0.0                    
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
yes
```

What is the expected retrieval frequency for this data?
```
Frequently since we provide public service
```

For how long do you plan to keep this dataset stored on Filecoin?
```
Expectedly 3 years to see how it goes
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
North America, China
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
online and offline.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We plan to select the SPs with high reputation and rich expeirence in vidoes or film industry
```

How will you be distributing deals across storage providers?
```
at least 2 copies per client, and then distribute quota and files fairly
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
yes
```

**Comment by raghavrmadya** [comment]
No samples

**Comment by Irenafootage** [comment]
Hello RG

Actually I shared three links in that sample-required column for your reference. 
Since F00tage is open to all independent filmmakers and video creators, now we have many video KOLs with us which is convenient for you to review. 

Our testnet is in the middle of internal testing and will be open to public soon.
I can share the link and account with code with you if you can provide a private email for check.
Once it is launched, the public can see everything inside. 

Let me know your thought or share your suggestion.

Thanks a lot.

**Comment by Irenafootage** [comment]
Hi Team

I don’t understand why just closed my application directly instead of further information needed.

That is not the right way to deal with filecoin community participant.

Look forward to further communication with the team.

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 100TiB

**Client address**

> f16efumcgpjamyhfrflxsu2brd7wrhniqwqssfpzq

**Comment by kernelogic** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacea54ozyglciws6ovlsqxbehsqrysxsqrqrsisbvflfabrgsjauohk 
#### Address 
> f16efumcgpjamyhfrflxsu2brd7wrhniqwqssfpzq
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### Id
> ff118ae3-15b7-476f-a0da-befc12bc25c8
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacea54ozyglciws6ovlsqxbehsqrysxsqrqrsisbvflfabrgsjauohk

**Comment by xingjitansuo** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec4cwba64wwjjyg7jp5vru7rlskfaqrowidf6ffkns7apopqpdynu 
#### Address 
> f16efumcgpjamyhfrflxsu2brd7wrhniqwqssfpzq
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1a2lia2cwwekeubwo4nppt4v4vebxs2frozarz3q
#### Id
> ff118ae3-15b7-476f-a0da-befc12bc25c8
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec4cwba64wwjjyg7jp5vru7rlskfaqrowidf6ffkns7apopqpdynu

**Comment by BDEio** [comment]
@Irenafootage Hi! Great to see that you have gotten approval for DataCap!
BDE is a verified deals auction house helping you to get paid storing your data with reliable storage providers. If you need any help, please get in touch.

**Comment by lvschouwen** [comment]
@Irenafootage 
Can you also explain to the community why there is CID sharing going on?

**Comment by cryptowhizzard** [comment]
#1314 is also involved.
#960 is also involved.
#1173 is also involved.

**Comment by Irenafootage** [comment]
Hi CryptoWhizzard

Thanks for the reminder, and I have checked with the SPs to inspect this
outstanding issue.
Anyway, I am not a tech person who can understand how it happened though I
was told it was caused by the insufficiency of tech verification during
data processing.
But I take this as the key issue according to the project rules here.
We will not work with the previous SPs anymore and try out best to avoid
such issues in future.

Appreciate your due diligence and kind reminder.




CryptoWhizzard ***@***.***> 于2023年1月16日周一 05:49写道：

**Comment by lvschouwen** [comment]
checker:manualTrigger

**Comment by lvschouwen** [comment]
@Irenafootage 
As you can see in the report, in the 3 weeks of Chinese New Year this only became worst.
Can you please disclose contact details for you SP?

**Comment by lvschouwen** [comment]
Also tried to retrieve some deals from the miners mentioned in the report 3 weeks ago (https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1089#issuecomment-1381289228) ... those miners do no allow retrieval.

Example;
```
# lotus client retrieve --provider f01854772 mAXCg5AIgCFH58WhxjMj+XlN8L5sCaPxQd3KfOqoUMB91qcuuyCk baga6ea4seaqjx3aokfsscmv6iduv5crypmfgc7sniv2rwvv6btdhmdodfowbwiq.car
Recv 0 B, Paid 0 FIL, Open (New), 0s [1674922066658078682|0]
Recv 0 B, Paid 0 FIL, DealProposed (WaitForAcceptance), 2ms [1674922066658078682|0]
Recv 0 B, Paid 0 FIL, DealAccepted (Accepted), 158ms [1674922066658078682|0]
Recv 0 B, Paid 0 FIL, PaymentChannelSkip (Ongoing), 159ms [1674922066658078682|0]
Recv 0 B, Paid 0 FIL, ProviderCancelled (Cancelling), 177ms [1674922066658078682|0]
Recv 0 B, Paid 0 FIL, CancelComplete (Cancelled), 178ms [1674922066658078682|0]
ERROR: Retrieval Proposal Cancelled: Provider cancelled retrieval
```

**Comment by Irenafootage** [comment]
Hi Ivschouwen

Thanks for your careful inspection.
I'll talk with SPs to see what happened here.
If it did happen, we will definitely rectify & reform to further get the
support from the community and notaries.
After that, it will be welcome to further check and we will make it public
if required.

Thanks again.






lvschouwen ***@***.***> 于2023年2月1日周三 23:50写道：

**Comment by Irenafootage** [comment]
Hi herrehesse

Respectfully I'm not sure what you mean.
After the message yesterday, I checked with SPs and tried to figure out
what was going on.
Yes,the issue did happen,and thanks again for the community's check and
information.

As a customer, I will definitely work with the SPs who observe the rules.
So I will find more potential SPs to emphasize the problem avoidance in
future.



herrehesse ***@***.***> 于2023年2月2日周四 22:05写道：

**Comment by cryptowhizzard** [comment]
Hi @Irenafootage 

I think there is a problem with translation / language. That's no problem, I will try to help.

Storing data on the network of Filecoin consists of 3 things:

A: The data itself ( the dataset ).
B: The packing in carfiles with special software like Singularity of the data and the distribution.
C: Storing the received data as storage provider ( SP )

What happened here is that things went wrong in stage B.

Can you clarify what your role is here. Are you just the customer ( in A ) , or are you doing data preparation yourself and did things go wrong there ?

**Comment by Irenafootage** [comment]
Hi CryptoWhizzard

Thanks again for the patient explanation.
My role is customer here.



CryptoWhizzard ***@***.***> 于2023年2月3日周五 21:34写道：

**Comment by cryptowhizzard** [comment]
Hello @Irenafootage 

Thanks, that makes things clear.

Can you share the contact information for part -B- in the picture here? If you want you can do it by e-mail to kyc@dcent.nl.
B is the one where the non compliant packing / distribution and storage happened and we would like their contact information.

Second, you need another B to do business with in order to move on. As soon as you have found them please send their details to kyc@dcent.nl

I can recommend:

- Piknik
- Techgreedy
- Kernlogic
- Cabrina

**Comment by Irenafootage** [comment]
Hi CyptoWhizzard

Thanks for your recommendation. Can you share their contact anyway - if
they are willing to offer?

And regarding your request on the part-B information, I have a concern.
Is ***@***.*** an official email address here from Fil team? or you are
from Fil team not notary?
Sorry a bit confused.
From my POV, that is privacy so I need to ask if they accept.

Thanks for your further explanation so that I can talk with them.



CryptoWhizzard ***@***.***> 于2023年2月6日周一 18:41写道：

**Comment by herrehesse** [comment]
@Irenafootage Is ***@***.*** an official email address here from Fil team? 

No clue what you mean, but kyc@dcent.nl is the official email from a notary performing due diligence. PL has nothing to do with this email account.

**Comment by cryptowhizzard** [comment]
Hi @Irenafootage 

Let me make it clear. 

I am cryptowhizzard , I am a notary. I work for DCENT. The mailbox kyc@dcent.nl is here on my desk.
PL does not do KYC and asks the notary's to do that.

**Comment by Sunnyiscoming** [comment]
checker:manualTrigger

**Comment by Sunnyiscoming** [comment]
Hi, please explain the abnormal information.
[f01971431](https://filfox.info/en/address/f01971431) has unknown IP location.
CID sharing has been observed.
