### ISSUE TITLE
[DataCap Application] <Nanyang Technological University> - < MetaTrust >

### ISSUE THREAD

**Issue by scaNie** [filecoin-project/filecoin-plus-large-datasets#1090]
# Large Dataset Notary Application
 
To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.
 
## Core Information
- Organization Name: Nanyang Technological University
- Website / Social Media: https://www.metatrust.io/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):5 PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):100TiB
- On-chain address for first allocation:f144lfga6fmfeklx3wxxpsmv3z6hkhj4e2o65homq
 
_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._
 
## Project details
 
Share a brief history of your project and organization.
```
MetaTrust is an incubation company founded in 2022 by a research team from Nanyang Technological University
The company is committed to building a digital data platform for Web3's open source projects. The company's vision is to provide security, profiling, ranking and other services for the development team, users, exchanges and other stakeholders of the Web3 project. 
```
 
What is the primary source of funding for this project?
```
Company.
```
 
What other projects/ecosystem stakeholders is this project associated with?
```
Web3, Blockchain, DeFi, GameFi.
```
 
## Use-case details
 
Describe the data being stored onto Filecoin
```
The data will be stored on Filecoin is the full blockchain data, Web3's open source projects, and the analysis data based on these. 
Specifically, first, for the full blockchain data, we are deploying the full node of several public chains, i.e., Ethereum(ETH)、BSC(BNB)、Solana(SOL)、Dfinity(ICP),  to do some analysis including online scanning, Vulanarability analysis, Malicious transaction detection, etc, using our developed tools, like MetaScan and MetaScout. These data currently require more than 100TB of storage resources.
Second, for Web3's open source projects, we are trying to download all blockchain-related open source projects from Git project hosting platforms, such as GitHub, GitLab, Gitee, and so on. We currently have 15,000 repos of the most popular open source projects for the list of demo projects. Based on these data, we can profile these projects in terms of quality, security, degree of open source, maintainability, business risk, and development activity using our MetaScore Pipline Engines, like Metatrust Fuzzer, Analyzer,  Prover, and SCA (See our website www.metatrust.io).
In addition, with the increase in transaction volume and the vigorous growth of blockchain-related projects, the data storage resources we need will become larger and larger.
As mentioned earlier, security is a crucial guarantee in the development of Web3. The series of tools we have developed can guarantee Web3 projects in an all-round, multi-angle and practical manner.
```
 
Where was the data in this dataset sourced from?
```
Github, Gitlab, Jira, blockchain exchanges, social media platforms, etc.
```
 
Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://osspert.com/search?tab=overall_score
https://drive.google.com/drive/folders/170GzDCqLx5ZnibJvCzfHWEaotjz-AyLu?usp=sharing
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes.
```
 
What is the expected retrieval frequency for this data?
```
Frequently
```
 
For how long do you plan to keep this dataset stored on Filecoin?
```
At least 3 years.
```
 
 
## DataCap allocation plan
 
In which geographies (countries, regions) do you plan on making storage deals?
```
Singapore.
```
 
How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Prefer online, if needed offline can also be considered.
```
 
How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
The stability and reachability of data is important to us. Some priority parameters: location, reputation, transmission rate, retrieval rate, etc.
```
 
How will you be distributing deals across storage providers?
```
We will divide to each storage provider equally.
```
 
Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes.
```

**Comment by scaNie** [comment]
> 

![image](https://user-images.githubusercontent.com/94284820/196326412-ce9cc304-ec4b-4461-b951-441938d30deb.png)

**Comment by raghavrmadya** [comment]
As an incubation company, how do you have the need for 5 PiBs? The description of data outlines a lot of plans for the future but DC can only be given for what exists today

**Comment by AaronNie02** [comment]
Hi, Thank you for your question.
We are building a data center to provide data support for each application built on it. The data center includes the following types of data:
1. Mirror images of open source projects
Mirror images of open source project codes in open source communities such as github, gitlab, and gitee, which are convenient for tool scanning. We expect to download 300 million open source projects.
2. Transaction data
Basic information of the web3 project and transaction information of the token. With the continuous increase in transaction volume, huge amounts of data are bound to be generated in the future.
3. Analyze the data
Based on the above two types of data, a huge amount of data will also be obtained after scanning and analysis using various analysis engines.
Based on the above considerations, we have filled in 5 PiB in the application.
We, on the other hand, are increasing our project analytical processing capabilities in a number of ways. The goal of our data center is to support the data requirements of various applications related to open source projects and web3 projects.

**Comment by raghavrmadya** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 100TiB

**Client address**

>f144lfga6fmfeklx3wxxpsmv3z6hkhj4e2o65homq

**Comment by kernelogic** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedujucolyidgijbn4uc5pjwojg33rhexp4r5fjqqwhnwmpbdtz73w 
#### Address 
> f144lfga6fmfeklx3wxxpsmv3z6hkhj4e2o65homq
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### Id
> a5e21107-f532-4744-991c-bea00f4f59cf
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedujucolyidgijbn4uc5pjwojg33rhexp4r5fjqqwhnwmpbdtz73w

**Comment by Tom-OriginStorage** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecda2rhqafg2yfog4mdlll4dkadlqfu6n3msch33hwv6sf27ryzyc 
#### Address 
> f144lfga6fmfeklx3wxxpsmv3z6hkhj4e2o65homq
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1q6bpjlqia6iemqbrdaxr2uehrhpvoju3qh4lpga
#### Id
> a5e21107-f532-4744-991c-bea00f4f59cf
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecda2rhqafg2yfog4mdlll4dkadlqfu6n3msch33hwv6sf27ryzyc

**Comment by BigD-Exchange** [comment]
@scaNie  Hi! Great to see you have gotten approval for DataCap and advancing the mission of preserving humanity’s most important information. If you are looking for storage providers to store these data or have any questions, please visit #bigdata-exchange on Filecoin Slack or reply here. 

We have strong demand from a diverse group of SPs, who are actively looking to onboard more data.

**Comment by stcouldlisa** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedylp7oo2v7v4i53k7caxhyk24vhwa5qsbfttktth2lhwgn4gk6xm 
#### Address 
> f144lfga6fmfeklx3wxxpsmv3z6hkhj4e2o65homq
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1jvvltduw35u6inn5tr4nfualyd42bh3vjtylgci
#### Id
> cfac78f7-76eb-4665-af86-7e09cc5abb3d
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedylp7oo2v7v4i53k7caxhyk24vhwa5qsbfttktth2lhwgn4gk6xm

**Comment by NDLABS-OFFICE** [comment]
No violation found, willing to support and continue to pay attention.

**Comment by NDLABS-OFFICE** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecxik7a5q7kr2hqsisztwmqp5apz5x2m6lnz4gf6pk4hki4ukrqcs 
#### Address 
> f144lfga6fmfeklx3wxxpsmv3z6hkhj4e2o65homq
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1yayfsv6whu3rheviucvventj3y6t542xfpb47ei
#### Id
> cfac78f7-76eb-4665-af86-7e09cc5abb3d
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecxik7a5q7kr2hqsisztwmqp5apz5x2m6lnz4gf6pk4hki4ukrqcs

**Comment by YuanHeHK** [comment]
The app looks fine and I'll support this signature

**Comment by YuanHeHK** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecxkwqcyyq3lkdxgiqzujhvgvltdvfglmkd2av3sxt3dbhuqkxuxc 
#### Address 
> f144lfga6fmfeklx3wxxpsmv3z6hkhj4e2o65homq
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1fg6jkxsr3twfnyhdlatmq36xca6sshptscds7xa
#### Id
> 90f512e0-8d52-465d-b8f0-51dd2fd8249d
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecxkwqcyyq3lkdxgiqzujhvgvltdvfglmkd2av3sxt3dbhuqkxuxc

**Comment by Tom-OriginStorage** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecfmeavczo3ldboj7zgyh3nupt7v5g62hi2n76qsxm73ycoym36x2 
#### Address 
> f144lfga6fmfeklx3wxxpsmv3z6hkhj4e2o65homq
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1q6bpjlqia6iemqbrdaxr2uehrhpvoju3qh4lpga
#### Id
> 90f512e0-8d52-465d-b8f0-51dd2fd8249d
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecfmeavczo3ldboj7zgyh3nupt7v5g62hi2n76qsxm73ycoym36x2

**Comment by stcouldlisa** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceakqjlafhez2bs7kwif3t3danxgeyzpro5mhq4f6dgsxr2pqvqgqm 
#### Address 
> f144lfga6fmfeklx3wxxpsmv3z6hkhj4e2o65homq
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1jvvltduw35u6inn5tr4nfualyd42bh3vjtylgci
#### Id
> 533ecbfc-e1c8-46f5-877f-5d4ba0cde387
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceakqjlafhez2bs7kwif3t3danxgeyzpro5mhq4f6dgsxr2pqvqgqm

**Comment by newwebgroup** [comment]
Bot doesn't work
<img width="905" alt="image" src="https://user-images.githubusercontent.com/100118145/204961850-dc010dcd-f8d3-474b-b6d0-7e1104266bd5.png">


I manually used Lotus to query the encapsulation ratio, which seems to meet the requirements.
f01852325,f01968227,70.6875
f01852023,f01968227,69.59375
f01852677,f01968227,70.375
f01852664,f01968227,70.03125
f01851482,f01968227,66.1875

**Comment by newwebgroup** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb6nlevkxbx45lpxvoydktsprzuxzjmbuxwuys7q766tkkjqkphoc 
#### Address 
> f144lfga6fmfeklx3wxxpsmv3z6hkhj4e2o65homq
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1e77zuityhvvw6u2t6tb5qlnsegy2s67qs4lbbbq
#### Id
> 533ecbfc-e1c8-46f5-877f-5d4ba0cde387
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb6nlevkxbx45lpxvoydktsprzuxzjmbuxwuys7q766tkkjqkphoc

**Comment by Tom-OriginStorage** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecmrjvjgo4vsj7xeik7yytv67drpqwr4am3jdqv6bak7ykanvnpts 
#### Address 
> f144lfga6fmfeklx3wxxpsmv3z6hkhj4e2o65homq
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1q6bpjlqia6iemqbrdaxr2uehrhpvoju3qh4lpga
#### Id
> c1386ee3-0b32-4c14-9ded-6564ae5c470f
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecmrjvjgo4vsj7xeik7yytv67drpqwr4am3jdqv6bak7ykanvnpts

**Comment by NDLABS-OFFICE** [comment]
There is a problem with the bot, unable to view package records. Can only check the authenticity of the subject, no problems found, willing to support.

**Comment by NDLABS-OFFICE** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacediqx2infvc3bbb6553e7m37gnajij2swqysuwfb5obyvfwlow72a 
#### Address 
> f144lfga6fmfeklx3wxxpsmv3z6hkhj4e2o65homq
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1yayfsv6whu3rheviucvventj3y6t542xfpb47ei
#### Id
> c1386ee3-0b32-4c14-9ded-6564ae5c470f
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacediqx2infvc3bbb6553e7m37gnajij2swqysuwfb5obyvfwlow72a

**Comment by filplus-checker** [comment]
## DataCap and CID Checker Report[^1]
 - Organization: `Nanyang Technological University`
 - Client: `f144lfga6fmfeklx3wxxpsmv3z6hkhj4e2o65homq`
### Storage Provider Distribution
The below table shows the distribution of storage providers that have stored data for this client.

If this is the first time a provider takes verified deal, it will be marked as `new`.

For most of the datacap application, below restrictions should apply.
 - Storage provider should not exceed 25% of total datacap.
 - Storage provider should not be storing duplicate data for more than 20%.
 - Storage provider should have published its public IP address.
 - All storage providers should be located in different regions.

✔️ Storage provider distribution looks healthy.

| Provider                                              |                           Location | Total Deals Sealed | Percentage | Unique Data | Duplicate Deals |
| :---------------------------------------------------- | ---------------------------------: | -----------------: | ---------: | ----------: | --------------: |
| [f01852325](https://filfox.info/en/address/f01852325) | Hong Kong, Central and Western, HK |          70.72 TiB |     20.12% |   70.72 TiB |           0.00% |
| [f01852677](https://filfox.info/en/address/f01852677) |    Morrisville, North Carolina, US |          70.44 TiB |     20.04% |   70.44 TiB |           0.00% |
| [f01852023](https://filfox.info/en/address/f01852023) |                   Busan, Busan, KR |          70.22 TiB |     19.98% |   70.22 TiB |           0.00% |
| [f01851482](https://filfox.info/en/address/f01851482) |                   Busan, Busan, KR |          70.13 TiB |     19.95% |   70.13 TiB |           0.00% |
| [f01852664](https://filfox.info/en/address/f01852664) |           Singapore, Singapore, SG |          70.03 TiB |     19.92% |   70.03 TiB |           0.00% |

![Provider Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/1090/1671098486858.png)
### Deal Data Replication
The below table shows how each many unique data are replicated across storage providers.
- No more than 25% of unique data are stored with less than 4 providers.

✔️ Data replication looks healthy.

| Unique Data Size | Total Deals Made | Number of Providers | Deal Percentage |
| ---------------: | ---------------: | ------------------: | --------------: |
|        64.00 GiB |       192.00 GiB |                   3 |           0.05% |
|         2.88 TiB |        11.50 TiB |                   4 |           3.27% |
|        67.97 TiB |       339.84 TiB |                   5 |          96.68% |

![Replication Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/1090/1671098487697.png)
### Deal Data Shared with other Clients
The below table shows how many unique data are shared with other clients.
Usually different applications owns different data and should not resolve to the same CID.

✔️ No CID sharing has been observed.

[^1]: To manually trigger this report, add a comment with text `checker:manualTrigger`

**Comment by BDEio** [comment]
@scaNie Hi! Great to see that you have gotten approval for DataCap!
BDE is a verified deals auction house helping you to get paid storing your valuable data with reliable storage providers. If you need any help, please get in touch.

**Comment by cryptowhizzard** [comment]
Hello!

I see that this request has been outstanding for a bit and i am looking to get it going again.

For my reference, this miners:

<p dir="auto" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 16px; color: rgb(36, 41, 47); font-family: -apple-system, &quot;system-ui&quot;, &quot;Segoe UI&quot;, &quot;Noto Sans&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span> </span>Storage provider distribution looks healthy.</p>

Provider | Location | Total Deals Sealed | Percentage | Unique Data | Duplicate Deals
-- | -- | -- | -- | -- | --
f01852325 | Hong Kong, Central and Western, HK | 70.72 TiB | 20.12% | 70.72 TiB | 0.00%
f01852677 | Morrisville, North Carolina, US | 70.44 TiB | 20.04% | 70.44 TiB | 0.00%
f01852023 | Busan, Busan, KR | 70.22 TiB | 19.98% | 70.22 TiB | 0.00%
f01851482 | Busan, Busan, KR | 70.13 TiB | 19.95% | 70.13 TiB | 0.00%
f01852664 | Singapore, Singapore, SG | 70.03 TiB | 19.92% | 70.03 TiB | 0.00%

<br class="Apple-interchange-newline">Storage provider distribution looks healthy.

Provider	Location	Total Deals Sealed	Percentage	Unique Data	Duplicate Deals
[f01852325](https://filfox.info/en/address/f01852325)	Hong Kong, Central and Western, HK	70.72 TiB	20.12%	70.72 TiB	0.00%
[f01852677](https://filfox.info/en/address/f01852677)	Morrisville, North Carolina, US	70.44 TiB	20.04%	70.44 TiB	0.00%
[f01852023](https://filfox.info/en/address/f01852023)	Busan, Busan, KR	70.22 TiB	19.98%	70.22 TiB	0.00%
[f01851482](https://filfox.info/en/address/f01851482)	Busan, Busan, KR	70.13 TiB	19.95%	70.13 TiB	0.00%
[f01852664](https://filfox.info/en/address/f01852664)	Singapore, Singapore, SG	70.03 TiB	19.92%	70.03 TiB	0.00%

Are all owned by Chainup right? Can you confirm?

For the next round of datacap, can you provide us with SP's of other organizations to have this LDN in line with the FIL+ rules?

**Comment by C00kies77** [comment]
checker:manualTrigger

**Comment by Joss-Hua** [comment]
Currently everything is good

**Comment by Joss-Hua** [comment]
![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/75723122/09c81d0a-b33b-49b2-8ac4-d1e782e83556)
I don't know what happened

**Comment by Sunnyiscoming** [comment]
Hello, @AIGC95 per the https://github.com/filecoin-project/notary-governance/issues/922 for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

This information will be reviewed by Fil+ Governance team to confirm validity and then the application will be allowed to move forward for additional notary review.
