### ISSUE TITLE
[DataCap Application] Sinso

### ISSUE THREAD

**Issue by xingshuoyun** [filecoin-project/filecoin-plus-large-datasets#1092]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name:  Sinso
- Website / Social Media: https://www.sinso.io/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 3PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100TiB
- On-chain address for first allocation: f177s2b6rpxe4mwmvayj6tekjdzfsertii7oyg5qq

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
SINSO is a Web3.0 infrastructure builder focused on decentralized caching and FVM-based data governance. The SINSO team is composed of top technical members from all over the world. SINSO will learn from the latest achievements of the Filecoin network, expand the middle layer of Web3.0, and solve the application iteration problem caused by Filecoin's lack of a complete ecological infrastructure system.

Project core:

SINSO Getway
As an auxiliary distributed cache network based on Filecoin, SINSO Getway is built for the current usage scenarios required for gaming Fi, VR, AR, video streaming, and high-speed CDN and DAPP responses. In addition to ensuring decentralization, user data privacy and security, there is a focus on improving efficiency. The efficient data upload interface provided by SINSO makes it easy for individuals and institutions to use Filecoin's storage resources. SINSO Getway is a loading layer for Filecoin's valid data, allowing more valuable data to be stored in the Filecoin network.
SINSO Donors Network
SINSO Donors Network is a data model based on deep phenotyping model and an economic and incentive model for data transaction middleware system. It automatically matches data buyers to complete data transactions, while providing incentives for storage miners and related contributors. Its various NFT data templates for industry-wide dynamic data sets aggregate data resources, enabling users, research institutions, etc. to better utilize and realize data assets. SINSO Donors Network also enables Sinso getway to build a complete incentive model in a more flexible way of cooperation.
SINSO DataLand
As a tool for personal management of datasets, SINSO DataLand allows users to set up and plan data governance and storage state. It collects the background data stored in the SINSO ecosystem here for individuals to truly control their own data, and provides an API interface that can be easily connected to DApps. This is an entrance to the Metaverse.

SINSO DAPP Cube
is a set of middleware for industrial applications. It has built-in project components involving big data and built-in industry communication protocols. Using SINSO DApp Cube, application developers can build industry-specific Web 3.0 applications that interact with the filecoin storage network.

SINSO DAC
It is the technical framework of SINSO community autonomy. SINSO DAC aims to build a transparent and fair value system where everyone can participate and contribute. It satisfies the following characteristics of DAC: distributed and decentralized, autonomous and automated, organized and ordered, intelligent and tokenized. SINSO DAC will be built on a smart contract driven FVM sidechain.
```

What is the primary source of funding for this project?
```
Investor and product income.
```

What other projects/ecosystem stakeholders is this project associated with?
```
Our cooperation and related projects include Crust Network, Metacraft, BirdWorld, PLUG Chain, NEO Smart Economy, VISION, Poly Network, Teleport Network and some other projects.
```

## Use-case details

Describe the data being stored onto Filecoin
```
Sinso's R&D data, data provided by customers.
```

Where was the data in this dataset sourced from?
```
The data comes from the relevant data provided by the customer.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://drive.google.com/drive/folders/1knzp1mQ5VyUCdqsbVsCPHWaMdusM7ZMU?usp=sharing
https://drive.google.com/drive/folders/1DEairHxFSjhj4dAg00rmFvGGToC99uir?usp=sharing
https://drive.google.com/drive/folders/1P6sPZOPMh3EiKzpEDExqraR04Cv-8Q0W?usp=sharing
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Confirm.
```

What is the expected retrieval frequency for this data?
```
About a year or so.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
At least 36 months.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
We do not restrict any region.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Online and offline.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We will choose a highly reputable storage provider for transactions, we will understand their reliability before cooperation, whether there is hard-core hardware equipment and a professional technical team, we must ensure the security of data storage.
```

How will you be distributing deals across storage providers?
```
We will choose reputable, stable and secure storage service providers to allocate according to the rules.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, we have sufficient funds to trade, and the Filecoin Foundation will also provide us with some help.
```

**Comment by raghavrmadya** [comment]
Are you currently operational? Your samples is a presentation deck....

**Comment by xingshuoyun** [comment]
Yes, we are currently operating.
This is our testnet: https://testnet.whitelist.vip//
This is our community site: https://discord.com/invite/m8eqcHJ5ur

**Comment by xingshuoyun** [comment]
Hello, may I ask if there are any other documents our company needs to provide?

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 3PiB

**Expected weekly DataCap usage rate**

> 100TiB

**Client address**

> f177s2b6rpxe4mwmvayj6tekjdzfsertii7oyg5qq

**Comment by Tom-OriginStorage** [comment]
1：can you send email to [[[filplus-app-review@fil.org](mailto:filplus-app-review@fil.org)]
2：Can you tell which nodes should be stored？

**Comment by xingshuoyun** [comment]
1.yes
2.f01894158 f01776264 f0167254 f01776738

**Comment by xingshuoyun** [comment]
![74bf6921acd31558918018aa51bc429](https://user-images.githubusercontent.com/78671897/206175997-77208af9-9a11-49f7-8357-bc73b2b82e3a.jpg)
I have replied. Please confirm it

**Comment by Tom-OriginStorage** [comment]
It looks good. I'll sign it

**Comment by Tom-OriginStorage** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacealdh35o2zuvo77ph4b7omwg6dyn3asfb6su2xhez7dg6ztjihdmg 
#### Address 
> f177s2b6rpxe4mwmvayj6tekjdzfsertii7oyg5qq
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1q6bpjlqia6iemqbrdaxr2uehrhpvoju3qh4lpga
#### Id
> 791a675a-5a92-4eb1-815a-955edb6162ab
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacealdh35o2zuvo77ph4b7omwg6dyn3asfb6su2xhez7dg6ztjihdmg

**Comment by NDLABS-OFFICE** [comment]
Customer completes kyb and is willing to support for the first time.

**Comment by NDLABS-OFFICE** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebmxoy7ls2skzjufza346s26jzremdpxieqffykhovl34uqhij4kg 
#### Address 
> f177s2b6rpxe4mwmvayj6tekjdzfsertii7oyg5qq
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1yayfsv6whu3rheviucvventj3y6t542xfpb47ei
#### Id
> 791a675a-5a92-4eb1-815a-955edb6162ab
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebmxoy7ls2skzjufza346s26jzremdpxieqffykhovl34uqhij4kg

**Comment by aliensero** [comment]
checker:manualTrigger

**Comment by zizi-defil** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedhnlhwo2yk6b6alw3akg5wwrqw3nhob3dkkvp4wpb3x4wddyot62 
#### Address 
> f177s2b6rpxe4mwmvayj6tekjdzfsertii7oyg5qq
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1dnb3uz7sylxk6emti3ififcvu3nlufnnsjui6ea
#### Id
> 37e434b0-fb3f-4c41-b5ed-31b16adad7ae
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedhnlhwo2yk6b6alw3akg5wwrqw3nhob3dkkvp4wpb3x4wddyot62

**Comment by zizi-defil** [comment]
no CID sharing
Storage provider distribution looks healthy
so i would like to support

**Comment by newwebgroup** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacediug5egpwfrc427b4qxlv7nbfiahe5avi6aw5nzh5mz52bkijiui 
#### Address 
> f177s2b6rpxe4mwmvayj6tekjdzfsertii7oyg5qq
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1e77zuityhvvw6u2t6tb5qlnsegy2s67qs4lbbbq
#### Id
> 37e434b0-fb3f-4c41-b5ed-31b16adad7ae
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacediug5egpwfrc427b4qxlv7nbfiahe5avi6aw5nzh5mz52bkijiui

**Comment by herrehesse** [comment]
It seems (given my crowded inbox) that in the past 15 minutes @newwebgroup  has approved 10+ datacap requests.

**I wonder if this blind approval is allowed?**

Would like to see per project what due diligence you did to explain the approval @newwebgroup.

**Comment by xingshuoyun** [comment]
I guess it may be the verifier fixed time unified processing

**Comment by BDEio** [comment]
@xingshuoyun  Hi! Congratulations on your DataCap approval！
BDE is a verified deals auction house helping you to get paid storing your data with reliable storage providers. If you need any help, please get in touch.

**Comment by aliensero** [comment]
checker:manualTrigger

**Comment by xingshuoyun** [comment]
In use, do not turn off
