### ISSUE TITLE
[DataCap Allocation] - Didi Dache Date

### ISSUE THREAD

**Issue by nullpoint4290** [filecoin-project/filecoin-plus-large-datasets#1093]
---
name: Large Dataset Notary application
about: Clients should use this application form to request a DataCap allocation via a LDN for a dataset
title: "Didi Dache Date"
labels: 'application, Phase: Diligence'
assignees: ''

---
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: ttcx
- Website / Social Media: https://es.didichuxing.com/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 500TiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 20
- On-chain address for first allocation: f37707
- Region: Asia (excl. Greater China)

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Didi Travel Cooperation Company
```

What is the primary source of funding for this project?
```
Car rental company
```

What other projects/ecosystem stakeholders is this project associated with?
```
Auto sales, auto supplies, electromechanical equipment, auto parts sales, auto leasing; Technical research and development of computer software, hardware and network
```

## Use-case details

Describe the data being stored onto Filecoin
```
出行数据,车辆数据,行车记录视频
```

Where was the data in this dataset sourced from?
```
Storage Server
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https:/car888.net
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes
```

What is the expected retrieval frequency for this data?
```
Once a month
```

For how long do you plan to keep this dataset stored on Filecoin?
```
Two months
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Hong Kong
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Network transmission
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
Normal operation,Speed,Security
```

How will you be distributing deals across storage providers?
```
Issued by storage market
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
f01730206 f01730218 f0699181..Maintenance of more than 50PiB,Operation and maintenance of more than 200 servers
```

**Comment by Carohere** [comment]
[How Did Didi Run Afoul of China’s Cybersecurity Regulators? Understanding the US$1.2 Billion Fine ](https://www.china-briefing.com/news/didi-cyber-security-review-which-laws-did-didi-break/) hmmm...

**Comment by raghavrmadya** [comment]
No samples
