### ISSUE TITLE
[DataCap Application]  BitFuFu - Cloud-mining Dataset

### ISSUE THREAD

**Issue by smallbull** [filecoin-project/filecoin-plus-large-datasets#1094]
name: Large Dataset Notary application
about: Clients should use this application form to request a DataCap allocation via a LDN for a dataset
title: "BitFuFu - Cloud-mining Dataset"
labels: 'application, Phase: Diligence'
assignees: ''

# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: BitFuFu
- Website / Social Media: https://www.bitfufu.com/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5PiB 
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100TiB
- On-chain address for first allocation: f3rm7hrijz2l3qth6nihxlf2no3so55vsb2dwcplwxwm7e6szwlx3on7fjerzomdinuitldmyngwlzxtz33vnq
- Region: Asia (excl. Greater China)

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
BitFuFu is a fast-growing digital asset mining service and world-leading cloud-mining service provider. BitFuFu has been invested by, and is the only cloud-mining strategic partner of Bitmain to date, a world-leading cryptocurrency mining hardware manufacturer. 
The Company had a hosting capacity of 140 MW at the end of 2021 across its global mining facilities network and strategic partnership with Bitmain.
```

What is the primary source of funding for this project?
```
Own funds and revenue of the company.
```

What other projects/ecosystem stakeholders is this project associated with?
```
BITMAIN related companies.
```

## Use-case details

Describe the data being stored onto Filecoin
```
Promotional and training videos and documents produced during the company's business operations. A large number of logs generated by the company's servers and self-operated mining machines.These data does not involve the company's sensitive information. Total size: At least 5 PiB now
```

Where was the data in this dataset sourced from?
```
AWS Open dataset / youtube / Website / Not currently stored in a public database / public advertisement data backup in company internal storage
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://www.youtube.com/channel/UCEO7IgJoFsHPQIWRNoGmwuw
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
We confirm this is a public dataset that can be retrieved by anyone on the network with no specific permissions or access rights required.
```

What is the expected retrieval frequency for this data?
```
Multiple times per year.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
At least 18 months.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
All regions.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
We will negotiate with SP, both online and offline are acceptable
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We will consider a combination of cost, service and geography, and give preference to miners of good scale and reputation.
```

How will you be distributing deals across storage providers?
```
We will store approximately 3-5 replica of data on different SPs, and we will follow the filecoin guideline to make our data more reliable and secure.
A detailed allocation plan for the SPs is in the works, we will share the details once it is ready.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
We have enough resources and funds to start trading. Perhaps we need more weekly allocation of DC.
```

**Comment by raghavrmadya** [comment]
The sample is not enough to justify 5 PiBs. provide as much information as possible.

**Comment by smallbull** [comment]
> The sample is not enough to justify 5 PiBs. provide as much information as possible.

link: https://pan.baidu.com/s/1SFgZzYYdrUG6oACudjOzuQ 
code: 34bd

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 100TiB

**Client address**

> f3rm7hrijz2l3qth6nihxlf2no3so55vsb2dwcplwxwm7e6szwlx3on7fjerzomdinuitldmyngwlzxtz33vnq

**Comment by newwebgroup** [comment]
About KYC&KYB
1：Could you send an email to [filplus-app-review@fil.org](mailto:filplus-app-review@fil.org) ？

The content should include the number of the LDN application. If possible, please attach copies of the business license and other valid certificates

2：Can you provide more detailed information about other storage providers participated in this program, such as you can list SPs you have contacted with at present?
3.How large is your existing dataset? How much is the data growth per month?

**Comment by smallbull** [comment]
> About KYC&KYB 1：Could you send an email to [filplus-app-review@fil.org](mailto:filplus-app-review@fil.org) ？
> 
> The content should include the number of the LDN application. If possible, please attach copies of the business license and other valid certificates
> 
> 2：Can you provide more detailed information about other storage providers participated in this program, such as you can list SPs you have contacted with at present? 3.How large is your existing dataset? How much is the data growth per month?

I have sent KYC&KYB email from the company mailbox. Please check and reply, Many thanks!

**Comment by newwebgroup** [comment]
About 1，Please provide a screenshot of the email sent

About 2 ，3 ；Please reply in detail

**Comment by smallbull** [comment]
About 1，Please provide a screenshot of the email sent
<img width="1124" alt="email-screenshot" src="https://user-images.githubusercontent.com/6346086/210296451-e0f69963-66d4-4a2a-a397-bb3c72402ee0.png">

About 2 ；Please reply in detail
According to the SP resource form provided by the foundation, try to contact:
https://docs.google.com/spreadsheets/d/1rwT9ie6qlOM9hVUkYZLGej523X1pMenaVKhFuvQOiNE/edit#gid=442291216
We also have contacted SPs: f0436065  f0701089  f01016248  f0694908

About 3 ；Please reply in detail
Our existing dataset is 10PiB+. The data growth is 60~80TiB/month. These data include our daily business data and publicity data.
Here is sample data:
【超级会员V6】通过百度网盘分享的文件：bitfufu
链接:https://pan.baidu.com/s/17Rz0tP0KVZausqizdYDqjA 
提取码:9jb6
复制这段内容打开「百度网盘APP 即可获取」
https://www.bitfufu.com/
https://twitter.com/bitfufu1
https://www.youtube.com/watch?v=yiicKlsObRQ

**Comment by newwebgroup** [comment]
Because it was the first round, the Client answered my relevant questions, and the conditions for triggering signature had been met, so I chose to pass.
If anyone has more questions about the application, they can keep watching and checking.

**Comment by newwebgroup** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecx2xvzxbkxo3tusjg3qjigpoe227dd5m7h5cehf5qxkjjnozwgus 
#### Address 
> f3rm7hrijz2l3qth6nihxlf2no3so55vsb2dwcplwxwm7e6szwlx3on7fjerzomdinuitldmyngwlzxtz33vnq
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1e77zuityhvvw6u2t6tb5qlnsegy2s67qs4lbbbq
#### Id
> 8a0414b2-514c-42e0-b788-dba94b298a27
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecx2xvzxbkxo3tusjg3qjigpoe227dd5m7h5cehf5qxkjjnozwgus

**Comment by Joss-Hua** [comment]
agree with newwebgroup.

**Comment by herrehesse** [comment]
Dear Applicant,

Due to the increased amount of erroneous/wrong Filecoin+ data recently, on behalf of the entire community, we feel compelled to go deeper into datacap requests. Hereby to ensure that the overall value of the Filecoin network and Filecoin+ program increases and is not abused.

Please answer the questions below as comprehensively as possible.

**Customer data**

- Could you demonstrate exactly how and to what extent customer contact occurred? 

We expect that for the onboarding of customers with the scale of an LDN there would have been at least multiple email and perhaps several chat conversations preceding it. A single email with an agreement does not qualify here.

- Did the customer specify the amount of data involved in this relevant correspondence?

- Why does the customer in question want to use the Filecoin+ program? 

_Should this only be soley for acquiring datacap this is of course **out of the question**. The customer must have a legitimate reason for wanting to use the Filecoin+ program which is intended as a program to store useful and public datasets on the network._ 

- Why is the customer data considered Filecoin+ eligible?

_(As an intermediate solution Filecoin offers the FIL-E program or the glif.io website for business datasets that do not meet the requirements for a Filecoin+ dataset)_


**Files and Processing**

- Could you please demonstrate to us how you envision processing and transporting the customer data in question to any location for preparation?
- Would you demonstrate to us that the customer, the preparer and the intended storage providers all have adequate bandwidth to process the set with its corresponding size?
- Would you tell us how the data set preparer takes into account the prevention of duplicates in order to prevent data cap abuse?


Hopefully you understand the caution the overall community has for onboarding the wrong data. We understand the increased need for Filecoin+, however, we must not allow the program to be misused. Everything depends on a valuable and useful network, let's do our best to make this happen. Together.

**Comment by BDEio** [comment]
@smallbull Hi! Congratulations on your DataCap approval！
BDE is a trusted deals auction house helping you to get paid storing your data with reliable storage providers. If you need any help, please get in touch.

**Comment by cryptowhizzard** [comment]
Blad 6

**Comment by Normalnoise** [comment]
checker:manualTrigger

**Comment by Joss-Hua** [comment]
![image](https://user-images.githubusercontent.com/75723122/236750622-c2a3cd9a-7387-4e18-a30f-f4ac96eef785.png)
I am ready to support it, but there was an error retrieving the data. Please take a look at what happened.

**Comment by smallbull** [comment]
> ![image](https://user-images.githubusercontent.com/75723122/236750622-c2a3cd9a-7387-4e18-a30f-f4ac96eef785.png) I am ready to support it, but there was an error retrieving the data. Please take a look at what happened.

It support retrieve data. Please try again.

<img width="806" alt="image" src="https://user-images.githubusercontent.com/6346086/237007507-aca6ebbf-3010-44dc-831b-94a0fec618dd.png">
<img width="843" alt="image" src="https://user-images.githubusercontent.com/6346086/237007529-76bb5b13-ddf6-475e-b574-1d9b42baca35.png">

**Comment by Joss-Hua** [comment]
Good job. I will support it in the next round because I have already signed in the previous round.

**Comment by Fatman13** [comment]
checker:manualTrigger

**Comment by Fatman13** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebjwekknnyjzajkl5q2coh23hzizjowumqvbavtn2wtxk6qzxmu6y 
#### Address 
> f3rm7hrijz2l3qth6nihxlf2no3so55vsb2dwcplwxwm7e6szwlx3on7fjerzomdinuitldmyngwlzxtz33vnq
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1j3u7crhjzwb2cj5mq7vodlt4o66yoyci7lhcauy
#### Id
> 647d4b41-7ff6-4cf2-af74-030ec2fe8732
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebjwekknnyjzajkl5q2coh23hzizjowumqvbavtn2wtxk6qzxmu6y

**Comment by Fatman13** [comment]
Reached out by the client on Slack. CIDchecker looks good.

**Comment by igoovo** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebgompza77avdfwqsarv7chllkmqxur4e7okwqeiem7sgr3xs4x3q 
#### Address 
> f3rm7hrijz2l3qth6nihxlf2no3so55vsb2dwcplwxwm7e6szwlx3on7fjerzomdinuitldmyngwlzxtz33vnq
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1shnsfayxqll77svffaxnjenms7bbbysbqcatrpy
#### Id
> 647d4b41-7ff6-4cf2-af74-030ec2fe8732
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebgompza77avdfwqsarv7chllkmqxur4e7okwqeiem7sgr3xs4x3q
