### ISSUE TITLE
[DataCap Application] <SYNC LIVE JAPAN INC.> - <Resubmit #123>

### ISSUE THREAD

**Issue by Sunkistn** [filecoin-project/filecoin-plus-large-datasets#1095]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: SYNC LIVE JAPAN INC.
- Website / Social Media: www.synclive.co.jp
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 4.7PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100TiB
- On-chain address for first allocation: f1ju5oabz45ceog6e7k5omdj56uspv2pzgghiyzdy

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
SYNC LIVE JAPAN INC. is committed to making live entertainment business more creative, safer and more efficient performances.
In regards to the entertainment conducted in a variety of spaces, including outdoor events and amusement parks, and also in regard to sound design for cutting-edge VR or MR technology development, it is now becoming vital to not only perform sound adjustment using a DOLBY ATMOS base in order to create music that fills the entire available space, but also to link the music to video and the overall performance in complex and intricate ways in order to create a new form of entertainment.
We use AVID ProTools as our main DAW, and for sound design we mainly use Native Instruments. Our fundamental philosophy is to respond on the spot, quickly and accurately, to produce a final product perfectly in keeping with our client's desires, be that during a meeting or during rehearsals.
```

What is the primary source of funding for this project?
```
Company revenue
```

What other projects/ecosystem stakeholders is this project associated with?
```
No other projects/ecosystem stakeholders
```

## Use-case details

Describe the data being stored onto Filecoin
```
Million Song Dataset: A freely-available collection of audio features and metadata for a million contemporary popular music tracks.
Free Music Archive: Founded in 2009 by radio station WFMU, offers free access to open licensed, original music. Many curators, netlabels and independent musicians around the world contributed to FMA's success. 
MusicNet Dataset: A curated collection of labeled classical music.
```

Where was the data in this dataset sourced from?
```
http://millionsongdataset.com/
https://github.com/mdeff/fma
https://freemusicarchive.org/
https://www.kaggle.com/imsparsh/musicnet-dataset
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://freemusicarchive.org/music/fma/music-insiders-by-free-music-archive-1/music-insiders-episode-2-simon-mathewson/
https://www.kaggle.com/datasets/imsparsh/musicnet-dataset
https://freemusicarchive.org/music/Derek_Clegg/life-unfolds-10-year-anniversary-re-issue/blind/
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes, it is.
```

What is the expected retrieval frequency for this data?
```
Maybe every day
```

For how long do you plan to keep this dataset stored on Filecoin?
```
More than 2 years.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
In Asia
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
The storage providers will download the data via the network.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
Anyone interested in this project and the music industry.
```

How will you be distributing deals across storage providers?
```
According to the capacity of the storage provider, the distribution is based on the principle of equal distribution.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Have enough funds
```

**Comment by raghavrmadya** [comment]
Please provide relevant samples and exactly what you will be stored with 5 PiBs of DC. All information must be provided upfront and cannot be provided "later"

**Comment by Sunkistn** [comment]
> Please provide relevant samples and exactly what you will be stored with 5 PiBs of DC. All information must be provided upfront and cannot be provided "later"

http://millionsongdataset.com/
https://github.com/mdeff/fma
https://freemusicarchive.org/
https://www.kaggle.com/imsparsh/musicnet-dataset

’Later‘ means that new data will be added if the business grows in the future. So far, the above are all data sources

**Comment by Sunkistn** [comment]
@raghavrmadya The previous application has passed the review and has reached the third round of datacap allocation, just because the github account was flagged and resubmitted with a new account

**Comment by Sunkistn** [comment]
@galen-mcandrew @Kevin-FF-USA @raghavrmadya This is the previous application information：
![sync](https://user-images.githubusercontent.com/92632190/200984290-e05f69d2-1094-410c-8b5e-3f42b245a88a.png)
![sync2](https://user-images.githubusercontent.com/92632190/200984308-357236ed-1cc8-4d71-8a41-65770d5cf154.png)
![sync3](https://user-images.githubusercontent.com/92632190/200984331-8b679d19-175a-465d-a9b4-abf3eb7e96e0.png)

**Comment by raghavrmadya** [comment]
Why are you requesting 5 PiBs when you have already received 200TiB?

**Comment by raghavrmadya** [comment]
"’Later‘ means that new data will be added if the business grows in the future." This is not acceptable. You can only apply for the amount of DC you need today, not for future projections

**Comment by raghavrmadya** [comment]
Who are the SPs you are working with currently? Please share their SP IDs and request them to confirm by commenting on this application

**Comment by Sunkistn** [comment]
> Who are the SPs you are working with currently? Please share their SP IDs and request them to confirm by commenting on this application
@raghavrmadya 
I have updated the application form.
Storage provider information can be queried here:
I have asked them to comment here, but not all of them have Github accounts

**Comment by Sunnyiscoming** [comment]
- http://millionsongdataset.com/, the entire dataset
280 GB

- https://github.com/mdeff/fma,
917 GB

- https://freemusicarchive.org/
All songs are free, but not all of them can be used in videos, podcasts, short films or commercial projects(https://freemusicarchive.org/royalty-free-music/). Can you explain what part of the music you will store and provide proof of that, and how much data?

- https://www.kaggle.com/imsparsh/musicnet-dataset
33.46GB
![image](https://user-images.githubusercontent.com/105098820/204751280-cfc969f7-170f-4da8-8b0c-3b8aae2ed8c4.png)

If you only source your data from the above four sites, it is difficult to prove that you have 5 PB data storage needs. Hope you can give more explanation.

**Comment by Sunnyiscoming** [comment]
Any update here?

**Comment by Sunkistn** [comment]
> * http://millionsongdataset.com/, the entire dataset
>   280 GB
> * https://github.com/mdeff/fma,
>   917 GB
> * https://freemusicarchive.org/
>   All songs are free, but not all of them can be used in videos, podcasts, short films or commercial projects(https://freemusicarchive.org/royalty-free-music/). Can you explain what part of the music you will store and provide proof of that, and how much data?
> * https://www.kaggle.com/imsparsh/musicnet-dataset
>   33.46GB
>   ![image](https://user-images.githubusercontent.com/105098820/204751280-cfc969f7-170f-4da8-8b0c-3b8aae2ed8c4.png)
> 
> If you only source your data from the above four sites, it is difficult to prove that you have 5 PB data storage needs. Hope you can give more explanation.

@Sunnyiscoming We also have the following data sources:
https://registry.opendata.aws/pacific-sound/, 140TiB
https://registry.opendata.aws/elp-nouabale-landscape/, 60TiB
And we plan to store 10 copies.
sorry for the late reply.

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 100TiB

**Client address**

> f1ju5oabz45ceog6e7k5omdj56uspv2pzgghiyzdy

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 100TiB

**Client address**

> f1ju5oabz45ceog6e7k5omdj56uspv2pzgghiyzdy

**Comment by filplus-checker** [comment]
## DataCap and CID Checker Report[^1]
 - Organization: `SYNC LIVE JAPAN INC.`
 - Client: `f1ju5oabz45ceog6e7k5omdj56uspv2pzgghiyzdy`
### Storage Provider Distribution
The below table shows the distribution of storage providers that have stored data for this client.

If this is the first time a provider takes verified deal, it will be marked as `new`.

For most of the datacap application, below restrictions should apply.
 - Storage provider should not exceed 25% of total datacap.
 - Storage provider should not be storing duplicate data for more than 20%.
 - Storage provider should have published its public IP address.
 - All storage providers should be located in different regions.

⚠️ 46.17% of total deal sealed by [f01114587](https://filfox.info/en/address/f01114587) are duplicate data.

⚠️ 37.50% of total deal sealed by [f0867300](https://filfox.info/en/address/f0867300) are duplicate data.

⚠️ 37.50% of total deal sealed by [f0522948](https://filfox.info/en/address/f0522948) are duplicate data.

⚠️ 37.50% of total deal sealed by [f01227975](https://filfox.info/en/address/f01227975) are duplicate data.

⚠️ 37.50% of total deal sealed by [f01228000](https://filfox.info/en/address/f01228000) are duplicate data.

⚠️ 37.50% of total deal sealed by [f01228008](https://filfox.info/en/address/f01228008) are duplicate data.

⚠️ 45.04% of total deal sealed by [f0694908](https://filfox.info/en/address/f0694908) are duplicate data.

⚠️ [f0694908](https://filfox.info/en/address/f0694908) has unknown IP location.

⚠️ [f01075159](https://filfox.info/en/address/f01075159) has unknown IP location.

⚠️ [f0867429](https://filfox.info/en/address/f0867429) has unknown IP location.

⚠️ [f01016239](https://filfox.info/en/address/f01016239) has unknown IP location.

| Provider                                                    |                            Location | Total Deals Sealed | Percentage | Unique Data | Duplicate Deals |
| :---------------------------------------------------------- | ----------------------------------: | -----------------: | ---------: | ----------: | --------------: |
| [f01114587](https://filfox.info/en/address/f01114587)`new`  |                    Tokyo, Tokyo, JP |          57.97 TiB |     16.56% |   31.21 TiB |          46.17% |
| [f0867300](https://filfox.info/en/address/f0867300)         |                    Tokyo, Tokyo, JP |          40.00 TiB |     11.43% |   25.00 TiB |          37.50% |
| [f0522948](https://filfox.info/en/address/f0522948)         |            Singapore, Singapore, SG |          40.00 TiB |     11.43% |   25.00 TiB |          37.50% |
| [f01227975](https://filfox.info/en/address/f01227975)       |  Hong Kong, Central and Western, HK |          40.00 TiB |     11.43% |   25.00 TiB |          37.50% |
| [f01228000](https://filfox.info/en/address/f01228000)       |                    Seoul, Seoul, KR |          40.00 TiB |     11.43% |   25.00 TiB |          37.50% |
| [f01228008](https://filfox.info/en/address/f01228008)       |         Sydney, New South Wales, AU |          40.00 TiB |     11.43% |   25.00 TiB |          37.50% |
| [f0694908](https://filfox.info/en/address/f0694908)`new`    |                             Unknown |          20.47 TiB |      5.85% |   11.25 TiB |          45.04% |
| [f01075159](https://filfox.info/en/address/f01075159)`new`  |                             Unknown |          11.34 TiB |      3.24% |   11.34 TiB |           0.00% |
| [f0867429](https://filfox.info/en/address/f0867429)`new`    |                             Unknown |          10.52 TiB |      3.01% |    9.90 TiB |           5.94% |
| [f01016255](https://filfox.info/en/address/f01016255)`new`  |                 Grimstad, Agder, NO |          10.49 TiB |      3.00% |    9.90 TiB |           5.66% |
| [f01228009](https://filfox.info/en/address/f01228009)       |  Hong Kong, Central and Western, HK |          10.00 TiB |      2.86% |   10.00 TiB |           0.00% |
| [f01228065](https://filfox.info/en/address/f01228065)       |            Singapore, Singapore, SG |          10.00 TiB |      2.86% |   10.00 TiB |           0.00% |
| [f0867298](https://filfox.info/en/address/f0867298)`new`    | Dehiwala-Mount Lavinia, Western, LK |           9.90 TiB |      2.83% |    9.90 TiB |           0.00% |
| [f01016239](https://filfox.info/en/address/f01016239)`new`  |                             Unknown |           9.27 TiB |      2.65% |    9.27 TiB |           0.00% |

![Provider Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/1095/1671098503971.png)
### Deal Data Replication
The below table shows how each many unique data are replicated across storage providers.
- No more than 25% of unique data are stored with less than 4 providers.

✔️ Data replication looks healthy.

| Unique Data Size | Total Deals Made | Number of Providers | Deal Percentage |
| ---------------: | ---------------: | ------------------: | --------------: |
|        31.30 TiB |        46.82 TiB |                   1 |          13.38% |
|         1.25 TiB |         3.75 TiB |                   2 |           1.07% |
|       640.00 GiB |         2.44 TiB |                   3 |           0.70% |
|        19.27 TiB |        96.97 TiB |                   4 |          27.71% |
|        25.00 TiB |       200.00 TiB |                   5 |          57.15% |

![Replication Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/1095/1671098505264.png)
### Deal Data Shared with other Clients
The below table shows how many unique data are shared with other clients.
Usually different applications owns different data and should not resolve to the same CID.

⚠️ CID sharing has been observed.

| Other Client                                                                                                                                                                                                              | Application                                                                                                                     | Total Deals Affected | Unique CIDs |        Verifier |
| :------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ | :------------------------------------------------------------------------------------------------------------------------------ | -------------------: | ----------: | --------------: |
| [f3wgfwtrs5p6jrkwfl2mksqa2ivgbgdjjrhjbefy3<br/>n7qzvotc3y6sazmp5gfyj7um6jlgdvlbiepzawnc6<br/>wxtq](https://filfox.info/en/address/f3wgfwtrs5p6jrkwfl2mksqa2ivgbgdjjrhjbefy3n7qzvotc3y6sazmp5gfyj7um6jlgdvlbiepzawnc6wxtq) | [FileDrive Labs](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/453)                                   |           166.92 TiB |         700 | LDN v3 multisig |
| [f1pkrmygbvweykpjcut36lf7ewgqdfhjklbhvepda](https://filfox.info/en/address/f1pkrmygbvweykpjcut36lf7ewgqdfhjklbhvepda)                                                                                                     | [Protocol Labs \( project: Slingshot Evergreen \)](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/293) |           400.00 GiB |          13 |       LDN # 293 |

[^1]: To manually trigger this report, add a comment with text `checker:manualTrigger`

**Comment by Sunnyiscoming** [comment]
Hi, please explain the abnormal information.
Some Sps has unknown IP location.

**Comment by Sunkistn** [comment]
> Hi, please explain the abnormal information. Some Sps has unknown IP location.

These are SPs that I collaborated with around January 2022. However, my GitHub account was banned for a long time afterwards, which prevented me from obtaining datacap, resulting in the termination of our collaboration. There is no plan to continue working with them in the future.

**Comment by Joss-Hua** [comment]
checker:manualTrigger

**Comment by Alex11801** [comment]
@Sunkistn 

> https://filplus.info/allocation_record?client_address=f1ju5oabz45ceog6e7k5omdj56uspv2pzgghiyzdy&obj=eyJuYW1lIjoiU1lOQyBMSVZFIEpBUEFOIElOQy4iLCJpc3N1ZV9udW1iZXIiOiIxMjMifQ%3D%3D

The page cannot be found.
![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/94093479/cea7dd3c-e2ed-40f1-bef1-f8cfedea235e)

**Comment by Sunkistn** [comment]
> @Sunkistn
> 
> > https://filplus.info/allocation_record?client_address=f1ju5oabz45ceog6e7k5omdj56uspv2pzgghiyzdy&obj=eyJuYW1lIjoiU1lOQyBMSVZFIEpBUEFOIElOQy4iLCJpc3N1ZV9udW1iZXIiOiIxMjMifQ%3D%3D
> 
> The page cannot be found. ![image](https://user-images.githubusercontent.com/94093479/238519793-cea7dd3c-e2ed-40f1-bef1-f8cfedea235e.png)

@Alex11801 
This link appears to expire periodically, please check for the latest link:
https://filplus.info/allocation_record?client_address=f1ju5oabz45ceog6e7k5omdj56uspv2pzgghiyzdy&obj=%7B%22name%22%3A%22SYNC%20LIVE%20JAPAN%20INC.%22,%22issue_number%22%3A%22123%22%7D

**Comment by sgclouder** [comment]
checker:manualTrigger
