### ISSUE TITLE
[DataCap Application] MOCO

### ISSUE THREAD

**Issue by VenXXX** [filecoin-project/filecoin-plus-large-datasets#1096]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: MOCO
- Website / Social Media: http://www.mocomedia88.cn/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 1PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100TiB
- On-chain address for first allocation: f1uxduwbbtky6pij7xmoggc2kutxzbfqmc4oubbby

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Changsha Moke Culture Media Co., Ltd. is a cultural communication industry integrating graphic design, film and television advertising, and event planning. The founder of the company has several years of media planning experience. He has edited and published hundreds of fashion and creative books, which are widely accepted Readers praise. The creative director plans and shoots many corporate image films and film and television commercials for various large enterprises and institutions, and participates in the shooting of many large-scale variety shows such as Hunan Satellite TV, Golden Eagle Cartoon, Mango TV, etc., and has a good reputation in the industry.

MOCO Media has a high-level production team, and its professional business process, good after-sales service system, and efficient execution are all powerful guarantees for the best results of the products. We strive to find the creative point that best matches the corporate image and bring the biggest surprise to customers. We provide high-quality services, track the whole process, and strive for perfection to ensure that every link is perfect and perfect. At present, the company's business scope has covered many industries such as government, tourism, film and television, publishing, automobile, real estate, hotel, food, etc., and has won unanimous praise from partners.

(i) Graphic design
Cooperate with different products to provide design solutions that conform to their attributes, precise product positioning, and new packaging design, emphasizing the visual impact of the designed products when displayed in the market, bringing customers a different visual experience and attracting the target. The audience pays attention, highlights the corporate brand style and promotes the promotion of corporate image and brand.
(ii) Film and television promotional film
From a professional perspective, customize personalized film and television promotion programs for different customers, and provide audiences with a more intuitive and in-depth experience of desire from an interactive perspective.
(iii) Media Diffusion
We have mature media resources and can provide online and offline promotion programs for enterprises according to customer needs, establish a good corporate brand image publicity, improve the company's internal and external brand communication needs, and increase corporate awareness.
```

What is the primary source of funding for this project?
```
company funds
```

What other projects/ecosystem stakeholders is this project associated with?
```
No, This is our company data
```

## Use-case details

Describe the data being stored onto Filecoin
```
Video material/promotional video/picture, etc.
```

Where was the data in this dataset sourced from?
```
our company data
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://drive.google.com/file/d/1iMvPMOApYJKNRDJ4J_Rkw9czv7TeisM4/view?usp=sharing
https://drive.google.com/file/d/1wtW-p4Ajp2UtQQXfaco6tZZfiMhD_5Uy/view?usp=sharing
https://drive.google.com/file/d/1pOofh1PAD3sdEMhP1jTwP-pZF_gYDW2t/view?usp=sharing
https://drive.google.com/file/d/1WwTHZLoV63YUgTiw-Map5NROv_oD5spN/view?usp=sharing
https://drive.google.com/file/d/1GuOfswvviXDMNMzMoyFggZs1s1hSzkUQ/view?usp=sharing
https://drive.google.com/file/d/1T6g0-7sT1FBU1Xhljap2K8x3iawxDms6/view?usp=sharing
https://drive.google.com/file/d/1EwLZJ4aCxgDQhCF7830BuGtvOfKHNDjb/view?usp=sharing
```

Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes, it's all public data, it's not secret, anyone can retrieve it
```

What is the expected retrieval frequency for this data?
```
once a year, or more
```

For how long do you plan to keep this dataset stored on Filecoin?
```
540 days
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
All countries
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Use offline services for data transfer or mail data disks, depending on the requirements of the SP providing the storage
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We will take the initiative to obtain SP. We also accept SP's initiative to contact us. Our data will be stored in multiple SPs to ensure distributed storage and data security. We periodically retrieve data to ensure that it is retrievable.
```

How will you be distributing deals across storage providers?
```
At least 5 SP
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, we have the fund
```

**Comment by VenXXX** [comment]
![-DataCap-Application-MOCO-·-Issue-380-·-filecoin-project-filecoin-plus-large-datasets](https://user-images.githubusercontent.com/16303555/196369890-3f346307-22b9-4050-a47a-8629ac11953d.png)
My last application was flagged

**Comment by VenXXX** [comment]
![-DataCap-Application-MOCO-·-Issue-380-·-filecoin-project-filecoin-plus-large-datasets](https://user-images.githubusercontent.com/16303555/196369890-3f346307-22b9-4050-a47a-8629ac11953d.png)
My last application was flagged

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 1PiB

**Expected weekly DataCap usage rate**

> 100TiB

**Client address**

>f1uxduwbbtky6pij7xmoggc2kutxzbfqmc4oubbby

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 1PiB

**Expected weekly DataCap usage rate**

> 100TiB

**Client address**

>f1uxduwbbtky6pij7xmoggc2kutxzbfqmc4oubbby

**Comment by Tom-OriginStorage** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedq56yazvvgstbnag6zouhabnq7o772ipk5yxavidcoakhvhvtley 
#### Address 
> f1uxduwbbtky6pij7xmoggc2kutxzbfqmc4oubbby
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1q6bpjlqia6iemqbrdaxr2uehrhpvoju3qh4lpga
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedq56yazvvgstbnag6zouhabnq7o772ipk5yxavidcoakhvhvtley

**Comment by newwebgroup** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedkv752zlhglchvfebivek3j4zmnnw4qc6jiascnj5bich6jweitu 
#### Address 
> f1uxduwbbtky6pij7xmoggc2kutxzbfqmc4oubbby
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1e77zuityhvvw6u2t6tb5qlnsegy2s67qs4lbbbq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedkv752zlhglchvfebivek3j4zmnnw4qc6jiascnj5bich6jweitu

**Comment by BigD-Exchange** [comment]
@VenXXX Hi! Great to see you have gotten approval for DataCap. If you are looking for storage providers to store these data or have any questions, please visit #bigdata-exchange on Filecoin Slack or reply here. 

We have strong demand from a diverse group of SPs, who are actively looking to onboard more data.

**Comment by newwebgroup** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebqsncae2omok354zbt3eclh5bvhl7qigv7ut4jmfpu4tpyu3goia 
#### Address 
> f1uxduwbbtky6pij7xmoggc2kutxzbfqmc4oubbby
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1e77zuityhvvw6u2t6tb5qlnsegy2s67qs4lbbbq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebqsncae2omok354zbt3eclh5bvhl7qigv7ut4jmfpu4tpyu3goia

**Comment by fireflyHZ** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebjhemwsthe54dplmtjf2qedwfobaopfvwps4ipx36rbpjwwcol46 
#### Address 
> f1uxduwbbtky6pij7xmoggc2kutxzbfqmc4oubbby
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1fg6jkxsr3twfnyhdlatmq36xca6sshptscds7xa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebjhemwsthe54dplmtjf2qedwfobaopfvwps4ipx36rbpjwwcol46

**Comment by ipfscn** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb4ksf4qfzvz5cgxz6zb2lddatxjmvikm5fhne3e5fbf65r5y45pa 
#### Address 
> f1uxduwbbtky6pij7xmoggc2kutxzbfqmc4oubbby
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1j4n74chme7whbz3yls4a7ixqewb6dijypqg2a3a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb4ksf4qfzvz5cgxz6zb2lddatxjmvikm5fhne3e5fbf65r5y45pa

**Comment by Tom-OriginStorage** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecs4j4op6lkx3yiabrbedbh7rvvs5vp2or4tvo6dkmxrsos2wnfie 
#### Address 
> f1uxduwbbtky6pij7xmoggc2kutxzbfqmc4oubbby
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1q6bpjlqia6iemqbrdaxr2uehrhpvoju3qh4lpga
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecs4j4op6lkx3yiabrbedbh7rvvs5vp2or4tvo6dkmxrsos2wnfie

**Comment by Tom-OriginStorage** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedyfqm7ys7ln2gjnio7hldlaknmgrp3sxoxhrbhjykcaqb43w76ze 
#### Address 
> f1uxduwbbtky6pij7xmoggc2kutxzbfqmc4oubbby
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1q6bpjlqia6iemqbrdaxr2uehrhpvoju3qh4lpga
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedyfqm7ys7ln2gjnio7hldlaknmgrp3sxoxhrbhjykcaqb43w76ze

**Comment by kernelogic** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced2ippibbuqdr2t4iij7elqk7hsowbtylxr6sdm2m5hpvj2ybc3cg 
#### Address 
> f1uxduwbbtky6pij7xmoggc2kutxzbfqmc4oubbby
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced2ippibbuqdr2t4iij7elqk7hsowbtylxr6sdm2m5hpvj2ybc3cg

**Comment by liyunzhi-666** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacea7tiiqewgzqbdtphvufopuh3hoi4rqzikx6bqreiuhfifvla7h26 
#### Address 
> f1uxduwbbtky6pij7xmoggc2kutxzbfqmc4oubbby
#### Datacap Allocated
> 274.00TiB
#### Signer Address
> f1pszcrsciyixyuxxukkvtazcokexbn54amf7gvoq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacea7tiiqewgzqbdtphvufopuh3hoi4rqzikx6bqreiuhfifvla7h26

**Comment by filplus-checker** [comment]
## DataCap and CID Checker Report[^1]
 - Organization: `MOCO`
 - Client: `f1uxduwbbtky6pij7xmoggc2kutxzbfqmc4oubbby`
### Storage Provider Distribution
The below table shows the distribution of storage providers that have stored data for this client.

If this is the first time a provider takes verified deal, it will be marked as `new`.

For most of the datacap application, below restrictions should apply.
 - Storage provider should not exceed 25% of total datacap.
 - Storage provider should not be storing duplicate data for more than 20%.
 - Storage provider should have published its public IP address.
 - All storage providers should be located in different regions.

✔️ Storage provider distribution looks healthy.

| Provider                                              |                           Location | Total Deals Sealed | Percentage | Unique Data | Duplicate Deals |
| :---------------------------------------------------- | ---------------------------------: | -----------------: | ---------: | ----------: | --------------: |
| [f01938721](https://filfox.info/en/address/f01938721) | Hong Kong, Central and Western, HK |         215.69 TiB |     21.06% |  215.59 TiB |           0.04% |
| [f01938714](https://filfox.info/en/address/f01938714) |     Sham Shui Po, Sham Shui Po, HK |         207.38 TiB |     20.25% |  207.25 TiB |           0.06% |
| [f01938718](https://filfox.info/en/address/f01938718) |    Morrisville, North Carolina, US |         207.22 TiB |     20.24% |  207.09 TiB |           0.06% |
| [f01938717](https://filfox.info/en/address/f01938717) |           Singapore, Singapore, SG |         198.31 TiB |     19.37% |  198.25 TiB |           0.03% |
| [f01938665](https://filfox.info/en/address/f01938665) |     Sham Shui Po, Sham Shui Po, HK |         195.31 TiB |     19.07% |  195.19 TiB |           0.06% |
| [f01852664](https://filfox.info/en/address/f01852664) |           Singapore, Singapore, SG |          96.00 GiB |      0.01% |   96.00 GiB |           0.00% |

![Provider Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/1096/1671098517664.png)
### Deal Data Replication
The below table shows how each many unique data are replicated across storage providers.
- No more than 25% of unique data are stored with less than 4 providers.

✔️ Data replication looks healthy.

| Unique Data Size | Total Deals Made | Number of Providers | Deal Percentage |
| ---------------: | ---------------: | ------------------: | --------------: |
|       160.00 GiB |       160.00 GiB |                   1 |           0.02% |
|         2.09 TiB |         4.19 TiB |                   2 |           0.41% |
|        17.47 TiB |        52.41 TiB |                   3 |           5.12% |
|        75.47 TiB |       301.88 TiB |                   4 |          29.48% |
|       132.97 TiB |       665.38 TiB |                   5 |          64.98% |

![Replication Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/1096/1671098518379.png)
### Deal Data Shared with other Clients
The below table shows how many unique data are shared with other clients.
Usually different applications owns different data and should not resolve to the same CID.

✔️ No CID sharing has been observed.

[^1]: To manually trigger this report, add a comment with text `checker:manualTrigger`
