### ISSUE TITLE
[DataCap Application] Palliums Education - pdjedu project

### ISSUE THREAD

**Issue by joycejade0810** [filecoin-project/filecoin-plus-large-datasets#1097]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information

- Organization Name: pdjedu
- Website / Social Media: http://pdjedu.com/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 3.5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100TiB
- On-chain address for first allocation: f1wy5hcnn5vyms5s6qt7cpo5lyoubnvpnljdrvz6q

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.

```
Palliums Education was founded in May 2015., and the group is a leading education and talent service organization in China based on the concept of openness, consensus and sharing. With technology as the core driver, it provides professional level solutions and groundbreaking implementation paths to meet the huge demand for professional talents arising from China's industrial upgrading. Palliums Education was once again selected as a talent capability evaluation institution in key areas of industry and information technology by the Ministry of Industry and Information Technology in 2021, and the Welight Stars Blockchain Industry Talent Training Program was officially launched.

(i) Introducing the application of new technologies into the process of talent training.

(ii)Put the application of new technologies in industry into projects, scenarios and digitization.

(iv) Transforming the employment needs of the enterprises into a sustainable and quantifiable development process.

(v) Through the model of school-enterprise cooperation, collaborative innovation, co-construction and sharing, students can possess the scientific literacy and innovative thinking for self-growth while acquiring the ability to apply new technologies.

(vi) Let the staged and fragmented learning process be organically integrated into the digital trajectory of personal growth through blockchain, big data, AI and other technologies, and make learning a self-shaping process.

(vii) Reduce the mismatch between job demand and talent supply in the enterprise, thereby reducing the labor cost of the enterprise and the opportunity cost of talent.

(viii) Prospecting to the future, the company is committed to transforming the traditional education model and creating a new education-industry integration chain, uniting multiple parties to build an "education-industry integration economic community", embracing the future, adapting to trends, leading new trends in education with technology.
```

What is the primary source of funding for this project?

```
Company funds
```

What other projects/ecosystem stakeholders is this project associated with?

```
None
```

## Use-case details

Describe the data being stored onto Filecoin

```
Blockchain open class, programming language open class and other teaching materials videos
```

Where was the data in this dataset sourced froms

```
Company data
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 

```
http://pdjedu.com/open.html
http://pdjedu.com/video/detail_504.html
http://pdjedu.com/video/detail_626.html
http://pdjedu.com/video/detail_632.html
http://pdjedu.com/video/detail_643.html
```

Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).

```
Yes
```

What is the expected retrieval frequency for this data?

```
3-5 times a year
```

For how long do you plan to keep this dataset stored on Filecoin?

```
540 days
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?

```
Prefer Hong Kong && Singapore
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?

```
Use offline transfer or mail hard drive for data transfer.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.

```
We tend to choose SPs in Hong Kong. We will conduct spot checks on data retrieval from time to time to ensure that data can always be retrieved.
```

How will you be distributing deals across storage providers?

```
Store data in multiple SPs in a balanced manner to ensure data security.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?

```
Yes

**Comment by joycejade0810** [comment]
![-DataCap-Application-Palliums-Education-pdjedu-project-·-Issue-461-·-filecoin-project-filecoin-plus-large-datasets](https://user-images.githubusercontent.com/25027245/196389291-57585b1b-25e7-447f-9d51-b574b10afb5f.png)
My last application was flagged

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 3.5PiB

**Expected weekly DataCap usage rate**

> 100TiB

**Client address**

>f1wy5hcnn5vyms5s6qt7cpo5lyoubnvpnljdrvz6q

**Comment by Tom-OriginStorage** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedyma6spdygb6f5e4omzj6n5nm5r7tm3naqv47pon7iixp52ewnzg 
#### Address 
> f1wy5hcnn5vyms5s6qt7cpo5lyoubnvpnljdrvz6q
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1q6bpjlqia6iemqbrdaxr2uehrhpvoju3qh4lpga
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedyma6spdygb6f5e4omzj6n5nm5r7tm3naqv47pon7iixp52ewnzg

**Comment by liyunzhi-666** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebgyahflf3xvwy2xwq4cgf7l7brmyyi5c6ahycsa7slcjgmjq4sgw 
#### Address 
> f1wy5hcnn5vyms5s6qt7cpo5lyoubnvpnljdrvz6q
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1pszcrsciyixyuxxukkvtazcokexbn54amf7gvoq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebgyahflf3xvwy2xwq4cgf7l7brmyyi5c6ahycsa7slcjgmjq4sgw

**Comment by newwebgroup** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceceqovruhp5673tx2lg4efgpfftaerwawbmvytlv4sfnfq3wq2cta 
#### Address 
> f1wy5hcnn5vyms5s6qt7cpo5lyoubnvpnljdrvz6q
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1e77zuityhvvw6u2t6tb5qlnsegy2s67qs4lbbbq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceceqovruhp5673tx2lg4efgpfftaerwawbmvytlv4sfnfq3wq2cta

**Comment by newwebgroup** [comment]
**Tips**
It seems that there are some bugs. When I approve this application, the system pop-up box has two addresses.
Need to check

@raghavrmadya  @Kevin-FF-USA 
<img width="1472" alt="image" src="https://user-images.githubusercontent.com/100118145/196874701-21af6c71-75f4-43ac-91a9-293c2a808b6e.png">

**Comment by liyunzhi-666** [comment]
It seems that the two of us signed at almost the same time causing some bugs (a few seconds before and after)

**Comment by BigD-Exchange** [comment]
@joycejade0810 Hi! Great to see you have gotten approval for DataCap and advancing the mission of preserving humanity’s most important information. If you are looking for storage providers to store these data or have any questions, please visit #bigdata-exchange on Filecoin Slack or reply here.

We have strong demand from a diverse group of SPs, who are actively looking to onboard more data.

**Comment by fireflyHZ** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebdhbelsmrdkdfiyb3xeuqy7x4nmzbvy4urwuyilj3s7l34gxlmn2 
#### Address 
> f1wy5hcnn5vyms5s6qt7cpo5lyoubnvpnljdrvz6q
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1fg6jkxsr3twfnyhdlatmq36xca6sshptscds7xa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebdhbelsmrdkdfiyb3xeuqy7x4nmzbvy4urwuyilj3s7l34gxlmn2

**Comment by Tom-OriginStorage** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecksrpcze2pa5kkz2hpjwhlyo6hgvv6k57754wc7x6w4rm3xtuwe6 
#### Address 
> f1wy5hcnn5vyms5s6qt7cpo5lyoubnvpnljdrvz6q
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1q6bpjlqia6iemqbrdaxr2uehrhpvoju3qh4lpga
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecksrpcze2pa5kkz2hpjwhlyo6hgvv6k57754wc7x6w4rm3xtuwe6

**Comment by ipfscn** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecepzfyp3aguwxatzoshwvk3olsvlsks53rmsjhtrgf6wsikop5jo 
#### Address 
> f1wy5hcnn5vyms5s6qt7cpo5lyoubnvpnljdrvz6q
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1j4n74chme7whbz3yls4a7ixqewb6dijypqg2a3a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecepzfyp3aguwxatzoshwvk3olsvlsks53rmsjhtrgf6wsikop5jo

**Comment by xingjitansuo** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec6k233ag57nireiekrknsbtpnhmv6nyew34g4k3o7w2k53rx3b6w 
#### Address 
> f1wy5hcnn5vyms5s6qt7cpo5lyoubnvpnljdrvz6q
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1a2lia2cwwekeubwo4nppt4v4vebxs2frozarz3q
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec6k233ag57nireiekrknsbtpnhmv6nyew34g4k3o7w2k53rx3b6w

**Comment by Tom-OriginStorage** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecyoivn5b3vzhyxdouyq5f2kyq4w74tluqwa6awkddk2dloz3lnhe 
#### Address 
> f1wy5hcnn5vyms5s6qt7cpo5lyoubnvpnljdrvz6q
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1q6bpjlqia6iemqbrdaxr2uehrhpvoju3qh4lpga
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecyoivn5b3vzhyxdouyq5f2kyq4w74tluqwa6awkddk2dloz3lnhe

**Comment by kernelogic** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebcnnezeyquuur5r4rehp2s5nklgqxyjvvlpjpk2httywdhi7h6po 
#### Address 
> f1wy5hcnn5vyms5s6qt7cpo5lyoubnvpnljdrvz6q
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebcnnezeyquuur5r4rehp2s5nklgqxyjvvlpjpk2httywdhi7h6po

**Comment by Alex11801** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceclfobbkdvqn7qujfxnahcc4phspvti4rseljslbp3rrqkobmhlik 
#### Address 
> f1wy5hcnn5vyms5s6qt7cpo5lyoubnvpnljdrvz6q
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1hhippi64yiyhpjdtbidfyzma6irc2nuav7mrwmi
#### Id
> 75bcc41f-246a-4368-8b2f-cb8a33e8263d
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceclfobbkdvqn7qujfxnahcc4phspvti4rseljslbp3rrqkobmhlik

**Comment by Tom-OriginStorage** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec53gixvx374qewuvybrnqtvy7uirtqicxfsl44recmbso3w2gf3w 
#### Address 
> f1wy5hcnn5vyms5s6qt7cpo5lyoubnvpnljdrvz6q
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1q6bpjlqia6iemqbrdaxr2uehrhpvoju3qh4lpga
#### Id
> 75bcc41f-246a-4368-8b2f-cb8a33e8263d
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec53gixvx374qewuvybrnqtvy7uirtqicxfsl44recmbso3w2gf3w

**Comment by newwebgroup** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceba3ye7gqzxwwq3ymxj5whkw34y6vqcartbnupka4rei4p4ylb6ai 
#### Address 
> f1wy5hcnn5vyms5s6qt7cpo5lyoubnvpnljdrvz6q
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1e77zuityhvvw6u2t6tb5qlnsegy2s67qs4lbbbq
#### Id
> f95fad19-3643-4b94-82f4-d9ffb8d3108d
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceba3ye7gqzxwwq3ymxj5whkw34y6vqcartbnupka4rei4p4ylb6ai

**Comment by ipfscn** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced7aot42q4c4ebf4nd2yzgq36bty6atpy65uevenobi4pco5a3gy4 
#### Address 
> f1wy5hcnn5vyms5s6qt7cpo5lyoubnvpnljdrvz6q
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1j4n74chme7whbz3yls4a7ixqewb6dijypqg2a3a
#### Id
> f95fad19-3643-4b94-82f4-d9ffb8d3108d
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced7aot42q4c4ebf4nd2yzgq36bty6atpy65uevenobi4pco5a3gy4

**Comment by newwebgroup** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacea4o3p6fqw34ydj6iab7qktf7opdu5da4f3jwy2dvjar6zvne6xbu 
#### Address 
> f1wy5hcnn5vyms5s6qt7cpo5lyoubnvpnljdrvz6q
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1e77zuityhvvw6u2t6tb5qlnsegy2s67qs4lbbbq
#### Id
> 63c8213d-62ae-4eea-a48e-df05c0c3e3ba
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacea4o3p6fqw34ydj6iab7qktf7opdu5da4f3jwy2dvjar6zvne6xbu

**Comment by Tom-OriginStorage** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedlp5eejywky7zehtpglio2q5rmj4bskuepcjiinhi2ubu4farare 
#### Address 
> f1wy5hcnn5vyms5s6qt7cpo5lyoubnvpnljdrvz6q
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1q6bpjlqia6iemqbrdaxr2uehrhpvoju3qh4lpga
#### Id
> 63c8213d-62ae-4eea-a48e-df05c0c3e3ba
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedlp5eejywky7zehtpglio2q5rmj4bskuepcjiinhi2ubu4farare

**Comment by stcouldlisa** [comment]
This client contacted 10 SPs， it looks good

**Comment by stcouldlisa** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecoe6caok3zh73hhrkzg2lu6cxx2sfmii2y4jvhi4jaxmqwtcshig 
#### Address 
> f1wy5hcnn5vyms5s6qt7cpo5lyoubnvpnljdrvz6q
#### Datacap Allocated
> 434.00TiB
#### Signer Address
> f1jvvltduw35u6inn5tr4nfualyd42bh3vjtylgci
#### Id
> 8ccba843-7c51-4400-b744-313a55c3d014
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecoe6caok3zh73hhrkzg2lu6cxx2sfmii2y4jvhi4jaxmqwtcshig

**Comment by 1ane-1** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecnycbcxzfbtt4ls72uenpdcwy77zbgknd2etiws3l2uril7geqky 
#### Address 
> f1wy5hcnn5vyms5s6qt7cpo5lyoubnvpnljdrvz6q
#### Datacap Allocated
> 434.00TiB
#### Signer Address
> f1mdk7s2vntzm6hu35yuo6vjubtrpfnb2awhgvrri
#### Id
> 8ccba843-7c51-4400-b744-313a55c3d014
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecnycbcxzfbtt4ls72uenpdcwy77zbgknd2etiws3l2uril7geqky

**Comment by filplus-checker** [comment]
## DataCap and CID Checker Report[^1]
 - Organization: `pdjedu`
 - Client: `f1wy5hcnn5vyms5s6qt7cpo5lyoubnvpnljdrvz6q`
### Storage Provider Distribution
The below table shows the distribution of storage providers that have stored data for this client.

If this is the first time a provider takes verified deal, it will be marked as `new`.

For most of the datacap application, below restrictions should apply.
 - Storage provider should not exceed 25% of total datacap.
 - Storage provider should not be storing duplicate data for more than 20%.
 - Storage provider should have published its public IP address.
 - All storage providers should be located in different regions.

✔️ Storage provider distribution looks healthy.

| Provider                                              |                           Location | Total Deals Sealed | Percentage | Unique Data | Duplicate Deals |
| :---------------------------------------------------- | ---------------------------------: | -----------------: | ---------: | ----------: | --------------: |
| [f01938717](https://filfox.info/en/address/f01938717) |           Singapore, Singapore, SG |         351.66 TiB |     11.64% |  351.50 TiB |           0.04% |
| [f01938721](https://filfox.info/en/address/f01938721) | Hong Kong, Central and Western, HK |         343.25 TiB |     11.36% |  343.00 TiB |           0.07% |
| [f01938718](https://filfox.info/en/address/f01938718) |    Morrisville, North Carolina, US |         341.81 TiB |     11.31% |  341.69 TiB |           0.04% |
| [f01938665](https://filfox.info/en/address/f01938665) |     Sham Shui Po, Sham Shui Po, HK |         328.00 TiB |     10.86% |  327.91 TiB |           0.03% |
| [f01938714](https://filfox.info/en/address/f01938714) |     Sham Shui Po, Sham Shui Po, HK |         322.69 TiB |     10.68% |  322.50 TiB |           0.06% |
| [f01852664](https://filfox.info/en/address/f01852664) |           Singapore, Singapore, SG |         279.97 TiB |      9.27% |  279.84 TiB |           0.04% |
| [f01852325](https://filfox.info/en/address/f01852325) | Hong Kong, Central and Western, HK |         272.97 TiB |      9.04% |  272.94 TiB |           0.01% |
| [f01852677](https://filfox.info/en/address/f01852677) |    Morrisville, North Carolina, US |         267.69 TiB |      8.86% |  267.50 TiB |           0.07% |
| [f01852023](https://filfox.info/en/address/f01852023) |                   Busan, Busan, KR |         265.09 TiB |      8.78% |  265.03 TiB |           0.02% |
| [f01851482](https://filfox.info/en/address/f01851482) |                   Busan, Busan, KR |         247.78 TiB |      8.20% |  247.69 TiB |           0.04% |

![Provider Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/1097/1671098535459.png)
### Deal Data Replication
The below table shows how each many unique data are replicated across storage providers.
- No more than 25% of unique data are stored with less than 4 providers.

⚠️ 41.91% of deals are for data replicated across less than 4 storage providers.

| Unique Data Size | Total Deals Made | Number of Providers | Deal Percentage |
| ---------------: | ---------------: | ------------------: | --------------: |
|        41.69 TiB |        41.69 TiB |                   1 |           1.38% |
|       155.25 TiB |       310.50 TiB |                   2 |          10.28% |
|       304.63 TiB |       913.97 TiB |                   3 |          30.25% |
|       291.09 TiB |         1.14 PiB |                   4 |          38.55% |
|       117.34 TiB |       587.19 TiB |                   5 |          19.44% |
|       224.00 GiB |         1.59 TiB |                   6 |           0.05% |
|       128.00 GiB |         1.00 TiB |                   7 |           0.03% |
|        32.00 GiB |       288.00 GiB |                   8 |           0.01% |

![Replication Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/1097/1671098536333.png)
### Deal Data Shared with other Clients
The below table shows how many unique data are shared with other clients.
Usually different applications owns different data and should not resolve to the same CID.

✔️ No CID sharing has been observed.

[^1]: To manually trigger this report, add a comment with text `checker:manualTrigger`

**Comment by herrehesse** [comment]
Dear Applicant,

Due to the increased amount of erroneous/wrong Filecoin+ data recently, on behalf of the entire community, we feel compelled to go deeper into datacap requests. Hereby to ensure that the overall value of the Filecoin network and Filecoin+ program increases and is not abused.

Please answer the questions below as comprehensively as possible.

**Customer data**

- Could you demonstrate exactly how and to what extent customer contact occurred? 

We expect that for the onboarding of customers with the scale of an LDN there would have been at least multiple email and perhaps several chat conversations preceding it. A single email with an agreement does not qualify here.

- Did the customer specify the amount of data involved in this relevant correspondence?

- Why does the customer in question want to use the Filecoin+ program? 

_Should this only be soley for acquiring datacap this is of course **out of the question**. The customer must have a legitimate reason for wanting to use the Filecoin+ program which is intended as a program to store useful and public datasets on the network._ 

- Why is the customer data considered Filecoin+ eligible?

_(As an intermediate solution Filecoin offers the FIL-E program or the glif.io website for business datasets that do not meet the requirements for a Filecoin+ dataset)_


**Files and Processing**

- Could you please demonstrate to us how you envision processing and transporting the customer data in question to any location for preparation?
- Would you demonstrate to us that the customer, the preparer and the intended storage providers all have adequate bandwidth to process the set with its corresponding size?
- Would you tell us how the data set preparer takes into account the prevention of duplicates in order to prevent data cap abuse?


Hopefully you understand the caution the overall community has for onboarding the wrong data. We understand the increased need for Filecoin+, however, we must not allow the program to be misused. Everything depends on a valuable and useful network, let's do our best to make this happen. Together.
