### ISSUE TITLE
[DataCap Application] Quanta

### ISSUE THREAD

**Issue by Zeeker81** [filecoin-project/filecoin-plus-large-datasets#1098]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Quanta Computer
- Website / Social Media:https://www.quantacn.com/en/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):100TiB
- On-chain address for first allocation:f1txp3fckhmdliatjwyhjhswexg5sxdsjpjana72q

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Quanta has extended business to Cloud Computing, enterprise network system solutions, mobile communication technology, smart home products, automotive electronics, intelligent medical, loT, applications of AI market. Quanta has actively expanded business, created new oppotunities and intergated related resources.
```

What is the primary source of funding for this project?
```
Revenue from companies.
```

What other projects/ecosystem stakeholders is this project associated with?
```
No.
```

## Use-case details

Describe the data being stored onto Filecoin
```
We plan to store videos data shot and produced by our staff. These videos are used by companies to promote our corporate culture and enrich the promotional messages of recruitment.
```

Where was the data in this dataset sourced from?
```
It was mainly from our staff and publicity department.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://drive.google.com/file/d/1IBHSTk-DdPBhCPJD6omXYj6Rb1Xa7CnZ/view?usp=sharing
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes, the data was showed on social media for corporation propaganda.
```

What is the expected retrieval frequency for this data?
```
Once a year.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
We plan store for 2-3 years.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
We plan choosing North america; Japan; China, more countries would be chosen.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Offline transfer is the first choice. We would use some hard disks for it.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We'll have cooperation with them for deals. If the community can recommend suitable sp, we are willing to work with them.
```

How will you be distributing deals across storage providers?
```
We will strictly control the distribution ratio to ensure distributed storage. Each sp would get no more than 30% of deals.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes.
```

**Comment by raghavrmadya** [comment]
Unable to access data samples

**Comment by Zeeker81** [comment]
@raghavrmadya It's already repaired. Please access it again!

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 100TiB

**Client address**

>f1txp3fckhmdliatjwyhjhswexg5sxdsjpjana72q

**Comment by PluskitOfficial** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedzkb7ohao7khstlpwefuutbw2y3u3nvttcwbdvw4r77hv5jxlmak 
#### Address 
> f1txp3fckhmdliatjwyhjhswexg5sxdsjpjana72q
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1tgnlhtcmhwipfm7thsftxhn5k52velyjlazpvka
#### Id
> e7f6c880-4196-4b0c-9e94-58c1cf5a22f4
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedzkb7ohao7khstlpwefuutbw2y3u3nvttcwbdvw4r77hv5jxlmak

**Comment by 1475Notary** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebgntwhpaw47oaanz56ygasjz3tecxfsggfulbwjuisiengno4d2q 
#### Address 
> f1txp3fckhmdliatjwyhjhswexg5sxdsjpjana72q
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1ofq4mngy7ggcp755pfquq2gphjjnlydolf6awtq
#### Id
> e7f6c880-4196-4b0c-9e94-58c1cf5a22f4
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebgntwhpaw47oaanz56ygasjz3tecxfsggfulbwjuisiengno4d2q

**Comment by Sunnyiscoming** [comment]
Is there any problem with using datacap?

**Comment by Zeeker81** [comment]
@Sunnyiscoming Thank you for your concern, there's no problem about it.
