### ISSUE TITLE
[DataCap Application] <QIHANGLONGTU>

### ISSUE THREAD

**Issue by lj102443** [filecoin-project/filecoin-plus-large-datasets#1099]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: qihanglongtu
- Website / Social Media: http://www.qhlt.com.cn/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 200TiB
- On-chain address for first allocation: f1vgitcmjdqu2qqpduoeescdxf2qogxuxdnkj3jqi

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Beijing Qihang Longtu Education Technology Co., Ltd. is a comprehensive education technology company for U9 groups, integrating online education, face-to-face education, publishing and e-commerce. The company has well-known sub-brands such as "Qihang Education", "Cloud Education", "Cloud Publishing", etc. Its business scope covers postgraduate entrance examination, CET-4 and CET-6 examinations, computer grade examinations, accounting qualifications, practicing physicians, teacher qualifications, and professional upgrades. , Pan-knowledge learning, quality and skill improvement, etc. The company adheres to the content as the core and the user as the foundation, and develops the third-order teaching method. Adhere to independent research and development of content in teaching and publishing; adhere to the supremacy of users in service, return to the essence of education, and put people first. The company adheres to the education & Internet model, and builds an information platform to flatten high-quality educational content and make education and learning fairer and more efficient.
```

What is the primary source of funding for this project?
```
Company
```

What other projects/ecosystem stakeholders is this project associated with?
```
None
```

## Use-case details

Describe the data being stored onto Filecoin
```
Teaching live and recorded video.
```

Where was the data in this dataset sourced from?
```
Company
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://www.bilibili.com/video/BV1u5411t7qj?p=1&vd_source=e95aea4b4945b127576dda800963e138
```

Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes
```

What is the expected retrieval frequency for this data?
```
2-3 times for a year.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
At least 540 Days.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Hong Kong or North America or Singapore.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Offline transfer.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
Priority will be given to SPs with strong service and good service located in Hong Kong.
```

How will you be distributing deals across storage providers?
```
Store to 5 SPs.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes
```

**Comment by lj102443** [comment]
@galen-mcandrew @raghavrmadya @Kevin-FF-USA 
Do you have any questions about my application, please feel free to contact me if you have any questions.

**Comment by raghavrmadya** [comment]
Can you prove that the data sample is related to the mentioned organization? We don't see a connection. The video mentions sailing education group at the top left corner. Your website has no videos as well as for 5 PiBs, it's suspicious

**Comment by lj102443** [comment]
@raghavrmadya 
As seen from our official website(http://www.qihanglongtu.com/)banner page.
Qihang Longtu is a large-scale comprehensive education group focusing on domestic education.The current business involves education and training, book publishing and e-commerce and other fields.
Aiqihang Online is an online education institution under the group.It is the proposer and implementer of the concept of "precision education" in China.
Times Cloud Map is an educational book publishing institution jointly established by Qihang Longtu Group and New Oriental.Involving postgraduate entrance examination, children's education, vocational education and other fields.
As you know, we need to store high-definition historical teaching videos and course development videos recorded by our teachers, and there are new videos every year, which requires a lot of storage space,we hope to improve this phenomenon by using filecoin network storage.
The account of our video media Bilibili is "云图考研" and the link is https://search.bilibili.com/all?keyword=%E4%BA%91%E5%9B%BE%E8%80%83%E7%A0%94&from_source=webtop_search&spm_id_from=333.1007&search_source=5.You can check.

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 200TiB

**Client address**

> f1vgitcmjdqu2qqpduoeescdxf2qogxuxdnkj3jqi

**Comment by lj102443** [comment]
I have sent a confirmation email with my corporate mailbox, please check.
![qhlt](https://user-images.githubusercontent.com/53929611/204434489-9e6fb859-be53-4861-8e6b-d4e0db0a41fb.jpeg)

**Comment by Sunnyiscoming** [comment]
![image](https://user-images.githubusercontent.com/105098820/218248413-16bc2a9d-43a9-40dc-a00c-c7887756a847.png)
@lj102443 Can you check your website? It seems that it do not work.
