### ISSUE TITLE
 [DataCap Application] Chengdu Digital Media Industry Base Co., Ltd.

### ISSUE THREAD

**Issue by cdsmlhw** [filecoin-project/filecoin-plus-large-datasets#11]
# Large Client Application

To apply as a large client, please fill out the following form. 

## Core Information
- Organization Name: Chengdu Digital Media Industry Base Co., Ltd.
- Website / Social Media:www.cd-szmt.com
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 500TiB
- On-chain address for first allocation: f3xffjctbyy7zigopfa3za5ha3pvv4z3xfghlw7kwvyeuabkg4lzsgfwhnghwkvmmvi6yso6k52hq3ca6ckveq

_Please respond to the questions below in pargraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

## Project details

Describe the data being stored onto Filecoin
```
China has a long history, and all ethnic minorities have formed their own national culture and customs.
We plan to store the data of the Tibetan, Qiang and Yi nationalities culture, which includes video, audio, photos, etc. The total amount is about 500TiB.
We have been recorded their living conditions, environment and customs through long-term field trips and live-action shooting.
As three of the ethnic minorities in China, Tibetan, Qiang and Yi have produced rich and colorful ethnic characteristics and cultures in their development process, which are important parts of Chinese cultural diversity. It is of great significance to save the data of ethnic culture.

Yi nationality currently distributed in four provinces and regions, Yunnan, Sichuan, Guizhou, and Guangxi. Except a regional community gathered in Liangshan of Sichuan. The rest lived in small clusters or live together with the Han and other ethnic minorities. In the long historical development, Yi nationality has experienced a course from primitive society, slave society, limo system, tusi system, feudal domination system, landlord system, bureaucratic-capitalism system, semi-colonial and semi-feudal system. Yi nationality has produced brilliant cultural heritage, such as festivals and folk entertainment, traditional rituals and customs, traditional music and dance, beliefs and sacrificial activities, traditional costume culture, traditional arts and crafts, language and ancient books, inheritance and protection, etc.

Qiang nationality originates from the ancient Qiang nationality, an ancient ethnic nationality in western China. The ancient Qiang nationality has a wide and far-reaching influence on the development of Chinese history and the formation of the Chinese nationality.
They are mainly distributed in Sichuan Province, Maoxian County, Wenchuan County, Li County, Songpan County, Heishui County in Aba Tibetan and Qiang Autonomous Prefecture, and Beichuan Qiang Autonomous County in Mianyang City.
On May 12, 2018, an 8.0-magnitude earthquake (Wenchuan Earthquake) rocked in the Aba Tibetan and Qiang Autonomous Prefecture and surrounding areas in western Sichuan Province.
For a nationality of only about 300, 000 people, the destruction was evident. More than 20,000 people were died or missing. Qiang buildings collapsed, including blockhouses, hanging houses, and many cultural relics of the Qiang ethnic.
Lives lost, homes destroyed, and the inheritance of culture was facing severe challenges.
We have been collected and created a lot of documents and images related to the history, beliefs, customs and life of the Qiang nationality.
We hope to inherit the culture of a nationality and record the culture.

Tibetan nationality are rich in national history, folk customs and festivals, traditional clothing, characteristic food, culture and art, architecture and others.
Tibetan opera, Tibetan song and dance and Tibetan literature all have their own unique style.
The grand and magnificent Potala Palace in Lhasa is a masterpiece in the history of architecture and has been inscribed on the World Cultural Heritage List by the United Nations.
The Tibetan area is mainly divided into three parts according to different dialects, Weizang, Kangba and Amdo, each of which presents different cultural characteristics.
In terms of geographical environment, the regional culture of highland, flat land, valley and forest area are different. The Tibetan culture is mainly based on the regional culture where the Tibetan people live in compact communities, which maintains a relatively complete original state and retains a relatively complete culture.

We hope that the data of different cultural characteristics can be recorded, as well as record history, present and civilization.
```

Confirm that this is a public data set that can be retrieved by anyone on the Network
```
Yes, it is a public data. 
We are working on a website where we will publish the CID of the data to be stored. 
The public will be able to view the data through this website.
``` 

What is the expected retrieval frequency for this data?
```
This type of data is not as attractive to the general public as entertainment content, and we hope that some people or organizations who really care about national culture will pay attention to our data.So the search frequency is not expected to be as high as that of video sites.This is the reason for we choosing the Filecoin network for storage.We want to retain the data over a longer period of time and provide it to those who need it when they need it.
```

For how long do you plan to keep this dataset stored on Filecoin? Is this a permanent archival or a temporary storage deal?
```
I think it's a permanent archival, and we'll constantly update our data stored on Filecoin.
```

## Use-case details

Describe the data being stored onto Filecoin
```
These data is relate to the following categories. 
Human activities, such as the origin of ethnic minorities, legends, activities, traditional folk customs.
Music, such as the origin of an instrument, the origin of music.
History, such as language, ancient books.
Beliefs, such as religion and sacrificial activities.
And others related to ethnic minority cultures.
```

Confirm that this is a public data set that can be retrieved by anyone on the Network
```
I confirm that this is a public data set, which can be retrieved by anyone on the Network.
```

What is the expected retrieval frequency for this data?
```
It is as same as the answer above.
This type of data is not as attractive to the general public as entertainment content, and we hope that some people or organizations who really care about national culture will pay attention to our data.So the search frequency is not expected to be as high as that of video sites.This is the reason for we choosing the Filecoin network for storage.We want to retain the data over a longer period of time and provide it to those who need it when they need it.
```

For how long do you plan to keep this dataset stored on Filecoin? Is this a permanent archival or a temporary storage deal?
```
This is a permanent archival.
```

## DataCap allocation plan

In which geographies do you plan on making storage deals?
```
Given the geographical advantages and cultural backgrounds, Greater China is a priority for us. 
```

What is your expected data onboarding rate? How many deals can you make in a day, in a week? How much DataCap do you plan on using per day, per week?
```
There will be 1-5TiB deals can be made in a day, around 10-50TiB in a week. We will use DataCap around 20TiB per week in the earlier stage.
```

How do you plan on choosing the miners with whom you will be making deals?
```
We will select miners through miners reputation systems like filrep.io, or Filecoin blockchain explorers.
The main factors we considered are the following:
1.Location (Greater China is a priority for us)
2.Possess of experience in dealing with verified data.
3.Possess of more than 10 PiB Total Raw Power
```

How will you be ensuring fair distribution of storage and DataCap across miners storing data?
```
We will follow the rules for large-datasets, and we will ensure fair distribution through limiting the amount of deals send to each miner. These records will be made and published regularly on Github.
```

How will you be distributing your data to miners? Is there an offline data transfer process?
```
We will use online transfer to distribute our data at first. If there is any abnormality, we probably resort to offline transfer.
```

**Comment by swatchliu** [comment]
Traditional culture is very valuable and we should preserve it.

**Comment by MRJAVAZHAO** [comment]
I'd like to support this project.

**Comment by steven004** [comment]
This is what Filecoin network would support, for humanity information. I would support this, and hope the data can be distributed geographically.

**Comment by rayshitou** [comment]
i'm in +1

**Comment by XnMatrixSV** [comment]
We'd like to join.

**Comment by DarnellWashington** [comment]
Hi. Count me.

**Comment by neogeweb3** [comment]
Count me in

**Comment by dkkapur** [comment]
Final list of 7 notaries for this application:

1. @swatchliu - f1yh6q3nmsg7i2sys7f7dexcuajgoweudcqj2chfi
2. @MRJAVAZHAO - f14gme3f52prtyzk6pblogrdd6b6ivp4swc6qmesi
3. @steven004 - f1qoxqy3npwcvoqy7gpstm65lejcy7pkd3hqqekna
4. @rayshitou - f136bz32l2hlyad4npmfg5dngcdw3jk3tpcpoz2ja
5. @XnMatrixSV - f3rnnecpx2n5cxs5fsjrnqq32r3hacubkt45mnbywvcaskgwpfuzixdmydpcdmujwqwoe6l2oi4tzyj2zakjsq
6. @DarnellWashington - f1bjdcjxha3ldcstw5zmvkyu3r2p5x2bsm745kgsi
7. @neogeweb3 - f13k5zr6ovc2gjmg3lvd43ladbydhovpylcvbflpa

These notaries cover GCN, Asia minus GCN, NA, thereby meeting the 3 region requirement.

**Comment by dkkapur** [comment]
## Multisig Notary requested

#### Notary addresses
> f1yh6q3nmsg7i2sys7f7dexcuajgoweudcqj2chfi
> f14gme3f52prtyzk6pblogrdd6b6ivp4swc6qmesi
> f1qoxqy3npwcvoqy7gpstm65lejcy7pkd3hqqekna
> f136bz32l2hlyad4npmfg5dngcdw3jk3tpcpoz2ja
> f1yuz2twsllparyfqwslfiuxrc5wj4mfiflvnsw6a
> f1bjdcjxha3ldcstw5zmvkyu3r2p5x2bsm745kgsi
> f13k5zr6ovc2gjmg3lvd43ladbydhovpylcvbflpa

#### Total DataCap requested
> 500TiB

#### Expected weekly DataCap usage rate
> 50TiB

**Comment by XnMatrixSV** [comment]
We would like to be the lead Notary of this project.

**Comment by XnMatrixSV** [comment]
## DataCap Allocation requested
#### Multisig Notary address
> f01105948
#### Client address
> f3xffjctbyy7zigopfa3za5ha3pvv4z3xfghlw7kwvyeuabkg4lzsgfwhnghwkvmmvi6yso6k52hq3ca6ckveq
#### DataCap allocation requested
> 500TiB

**Comment by XnMatrixSV** [comment]
## DataCap Allocation requested
#### Multisig Notary address
> f01105948
#### Client address
> f3xffjctbyy7zigopfa3za5ha3pvv4z3xfghlw7kwvyeuabkg4lzsgfwhnghwkvmmvi6yso6k52hq3ca6ckveq
#### DataCap allocation requested
> 25TiB

**Comment by dkkapur** [comment]
@XnMatrixSV - the bot isn't picking this one up yet due to a config thing I need to correct! Will report back with next steps shortly.

**Comment by dkkapur** [comment]
@XnMatrixSV - https://github.com/filecoin-project/notary-governance/issues/204 actually, we are waiting on one more RKH to grant the multisig notary status on chain.

**Comment by XnMatrixSV** [comment]
Thanks,@dkkapur. Please update here when it is ready.

**Comment by cdsmlhw** [comment]
Hello, everyone.
Is there any progress on this application?

**Comment by XnMatrixSV** [comment]
@dkkapur It seems like a long time has passed. Is there any information update?

**Comment by galen-mcandrew** [comment]
Hi @cdsmlhw thanks for your patience! At this time we are seeing the large dataset notary successfully created ([f01105948](https://filplus.d.interplanetary.one/notaries?filter=f01105948))

@XnMatrixSV I think you volunteered to be lead notary here. Can you start the first allocation request and tag the other notaries? Thank you!

Total DataCap requested: 500TiB
Expected weekly DataCap usage rate: 50TiB
First Allocation: **25TiB**

**Comment by XnMatrixSV** [comment]
> ## DataCap Allocation requested
> #### Multisig Notary address
> > f01105948
> #### Client address
> > f3xffjctbyy7zigopfa3za5ha3pvv4z3xfghlw7kwvyeuabkg4lzsgfwhnghwkvmmvi6yso6k52hq3ca6ckveq
> #### DataCap allocation requested
> > 25TiB

**Comment by XnMatrixSV** [comment]
## DataCap Allocation requested
 #### Multisig Notary address
 > f01105948
#### Client address
 > f3xffjctbyy7zigopfa3za5ha3pvv4z3xfghlw7kwvyeuabkg4lzsgfwhnghwkvmmvi6yso6k52hq3ca6ckveq
 #### DataCap allocation requested
 > 25TiB

**Comment by XnMatrixSV** [comment]
## DataCap Allocation requested
#### Multisig Notary address
> f01105948
#### Client address
> f3xffjctbyy7zigopfa3za5ha3pvv4z3xfghlw7kwvyeuabkg4lzsgfwhnghwkvmmvi6yso6k52hq3ca6ckveq
#### DataCap allocation requested
> 25TiB

**Comment by galen-mcandrew** [comment]
@XnMatrixSV , @dkkapur and I were able to get the allocation request pushed through, and we're seeing it in the app at this time. Can you log in using the multisig address f01105948 and approve the allocation?

**Comment by steven004** [comment]
I do not think there is any request sent to f01105948. 
Actually, there is no single message there at this moment: 
https://filscan.io/address/general?address=f01105948

**Comment by XnMatrixSV** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecc53ct6ohj5ba65ba3l2x2mjytniynmc77upwyzzizh7uxhnqzdu 
#### Address 
> f3xffjctbyy7zigopfa3za5ha3pvv4z3xfghlw7kwvyeuabkg4lzsgfwhnghwkvmmvi6yso6k52hq3ca6ckveq
#### Datacap Allocated
> 27487790694400
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecc53ct6ohj5ba65ba3l2x2mjytniynmc77upwyzzizh7uxhnqzdu

**Comment by XnMatrixSV** [comment]
@dkkapur @galen-mcandrew @steven004 I have approved this request.

**Comment by steven004** [comment]
I approved the request: 

Message sent to Filecoin Network: 
> [bafy2bzacech4amn6rtimlvnp4u7dkluziywzh3oo7o5zysnbotho7kqxviz5i](https://filscan.io/tipset/message-detail?cid=bafy2bzacech4amn6rtimlvnp4u7dkluziywzh3oo7o5zysnbotho7kqxviz5i)

**Comment by MRJAVAZHAO** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebdfi6r4t5grlckltfhbskpvume73nxjzoch5ze5nudamigxcbtea 
#### Address 
> f3xffjctbyy7zigopfa3za5ha3pvv4z3xfghlw7kwvyeuabkg4lzsgfwhnghwkvmmvi6yso6k52hq3ca6ckveq
#### Datacap Allocated
> 27487790694400
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebdfi6r4t5grlckltfhbskpvume73nxjzoch5ze5nudamigxcbtea

**Comment by cdsmlhw** [comment]
Thank you, @galen-mcandrew @dkkapur @XnMatrixSV @steven004 @MRJAVAZHAO @swatchliu @rayshitou @DarnellWashington @neogeweb3 
Please approve our request.

**Comment by galen-mcandrew** [comment]
At this time, I'm seeing 3 approvals both in Lotus and the Filecoin Plus Registry app: XnMatrixSV, steven004, and MRJAVAZHAO.

Can we get one more approval through the app? @swatchliu @rayshitou @DarnellWashington @neogeweb3

**Comment by galen-mcandrew** [comment]
> I do not think there is any request sent to f01105948.
> Actually, there is no single message there at this moment:
> https://filscan.io/address/general?address=f01105948

@steven004 wanted to address this here to make sure we're on the same page. At this time, when a notary starts the allocation request (using the comment format in the read me for "DataCap Allocation requested") the bot should scrape the comment and adjust the labels. This starts the request process so it will show up in the Filecoin Plus Registry app, where notaries can see and sign messages using their ledger. When a notary approves through the app, it will create the message and post here, and then you should be able to see the pending transaction on-chain (to match the TxId and params).

So, there won't be any pending transactions or messages on-chain until a notary makes an approval. That's why you didn't see any pending transactions/messages two days ago.

Does that make sense and match your understanding? At this time, it looks like the app is correctly grouping the approvals, but we have had issues in the past with some notaries using the app versus others approving/proposing directly through Lotus and the TxId's not matching, causing problems with approval counts.

**Comment by neogeweb3** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecyv5iv7zdiwkskvwg45jhq6nod4x52bbudpf6qeius4bcw4d7c2g 
#### Address 
> f3xffjctbyy7zigopfa3za5ha3pvv4z3xfghlw7kwvyeuabkg4lzsgfwhnghwkvmmvi6yso6k52hq3ca6ckveq
#### Datacap Allocated
> 27487790694400
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecyv5iv7zdiwkskvwg45jhq6nod4x52bbudpf6qeius4bcw4d7c2g

**Comment by galen-mcandrew** [comment]
@cdsmlhw it looks like the allocation has gone through, and at this time address f3xffjctbyy7zigopfa3za5ha3pvv4z3xfghlw7kwvyeuabkg4lzsgfwhnghwkvmmvi6yso6k52hq3ca6ckveq has 25 TiB of DataCap!

**Comment by cdsmlhw** [comment]
@galen-mcandrew Thanks for your help.

**Comment by galen-mcandrew** [comment]
rolling to https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/48
