### ISSUE TITLE
[DataCap Application] <Organization> - <Project Name>

### ISSUE THREAD

**Issue by yy1970** [filecoin-project/filecoin-plus-large-datasets#1102]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: CIIC Education Technology (Shenzhen) Co., Ltd.
- Website / Social Media:http://vkshequn.com/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):100TiB
- On-chain address for first allocation: f1axtj4vjlsf5buf2qcn4kkqrpdcgrqk4exxxsury

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Please answer here.
```
The predecessor of CIIC Education Technology (Shenzhen) Co., Ltd. ("CIIC") was engaged in traditional corporate training, management consulting, personal growth, and spiritual training. Later, as the whole world entered the digital economy world from the Internet world, and the Internet entered Web3.0, the company also began to transform itself into a self-media platform in the digital economy world. At present, the company focuses on blockchain community operations and ETH and BTC mining, and has formed its own mining pool "V-shaped mining pool", while providing various consulting services in the industry.
What is the primary source of funding for this project?
```
Please answer here.
```
Our company has stable business, rich income and strong self-owned funds.
What other projects/ecosystem stakeholders is this project associated with?
```
Please answer here.
```
No

## Use-case details

Describe the data being stored onto Filecoin
```
Please answer here.
```
It mainly stores the videos of the company's lecturers, the videos of the management consulting site for customers, the audio, video and articles released from the media, various picture documents introducing the company's products, and data related to the production of consulting solutions for customers.
Where was the data in this dataset sourced from?
```
Please answer here.
```
From our process of providing training, consulting services, introducing products to customers, and making sales.
Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
Please answer here.
```
 https://drive.google.com/drive/folders/1gq4ET8QYwr-L1ixN6wFz-7GsrhXvTS_s?usp=sharing
https://drive.google.com/drive/folders/1fb2J233_Xz37d9UkMdz-Xizx2afj8qwC?usp=sharing
https://drive.google.com/drive/folders/1MlRgHy6YGYFD6PEo911htGSab7EFg5Lk?usp=sharing
https://drive.google.com/drive/folders/1lvbhUq5JkSy37Hc3dlrwTZ01SFlNhUzH?usp=sharing
https://drive.google.com/drive/folders/1OnCRYj_e3YG646zi7LCsVvC-YCUrGId4?usp=sharing
    
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Please answer here.
```
Yes
What is the expected retrieval frequency for this data?
```
Please answer here.
```
In general, frequent searches are not required, perhaps once every 1-2 years.
For how long do you plan to keep this dataset stored on Filecoin?
```
Please answer here.
```
For about 3year.

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Please answer here.
```
We have no restrictions on where we store, It can be used all over the world, but it may be mainly in Hong Kong and Greater China.
How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Please answer here.
```
I will distribute the data equally to each SP with no more than 5% per SP according to the FIL rules, so I will contact at least 2 SPs + 4 SPs and above.
Both on-line and off-line transfers are fine, but I think I'll decide together on off-line and SP again.

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
Please answer here.
```
Before that, we will be in slack, github, fil, etc. related files, we may even go to sp_sp, we have carried out related technology, we have good experience, technology and strength of the company. the sp.

Our requirements for retrieval are not high, and retrieval is possible, which will also become one of the conditions for us to consider sp.

How will you be distributing deals across storage providers?
```
Please answer here.
```
I will definitely abide by the rules of FIL+，to  make sure no more than 20% datacap / SP.

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Please answer here.
```
Have enough resources/funding.

**Comment by raghavrmadya** [comment]
Please answer in the fields provided as our bots will flag this as an error. Please submit a new application with the correct format
