### ISSUE TITLE
[DataCap Allocation] - Galaxy formation and cosmological evolution

### ISSUE THREAD

**Issue by StorageLabs** [filecoin-project/filecoin-plus-large-datasets#1103]
---
name: Large Dataset Notary application
about: Clients should use this application form to request a DataCap allocation via a LDN for a dataset
title: "Galaxy formation and cosmological evolution"
labels: 'application, Phase: Diligence'
assignees: ''

---
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: StorageLabs
- Website / Social Media:   Website: https://universe.storagelabs.io     Twitter：storagelabs
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100TiB
- On-chain address for first allocation: f173hsbasxc44gy3dwbuauwvhthjxtjyl6f7ozdli
- Region:  Greater China Region

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
The StorageLabs is a non-profit organization which generates mass data from experiment, observation and calculation led by our scientific research team. We carried out several international projects, like American Illustris Project, British EAGLE project, particularly ELUCID project for now. ELUCID （EXPLORING THE LOCAL UNIVERSE WITH THE RECONSTRUCTED INITIAL DENSITY FIELD） project is to reconstruct the initial linear density field from an input nonlinear density field, employing the Hamiltonian Markov Chain Monte Carlo (HMC) algorithm combined with Particle-mesh (PM) dynamics. Mass data is produced from ELUCID project with the help of computers based on physical formulas, the data mainly are the snapshots of Parameters.
```

What is the primary source of funding for this project?
```
We will fund this project with Slingshot rewards and social donations.
```

What other projects/ecosystem stakeholders is this project associated with?
```
No other stakeholders involved.
```

## Use-case details

Describe the data being stored onto Filecoin
```
The data is mainly about galaxy formation and cosmological evolution; According to cosmological modeling, we can predict how the universe looks like at different ages since the Big Bang. A lot of scientific efforts have been taken and huge datasets have been produced to describe the predicted universe at different redshifts. For now, the data is snapshot of Parameters mainly from ELUCID Project. 
```

Where was the data in this dataset sourced from?
```
Massive scientific data is generated from experiment, observation and calculation by the researchers with the help of computers.
Parts of the data is stored in centralized data center now, but most of the data is forced to be discarded due to the limit of storage capacity. So we seek to find decentralized storage provider for more space and easy access.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://universe.storagelabs.io/data/snapshot_099/
https://cpb-us-e1.wpmucdn.com/sites.northwestern.edu/dist/6/84/files/2013/12/FIREbox_z2_512_slow-ry595s.mp4
https://fire.northwestern.edu/files/2013/12/z2_512_gas_stars_fahrt1-1aks7mn.m4v?_=2
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
We confirm that the public has access to the dataset without any restriction.
```

What is the expected retrieval frequency for this data?
```
1~2 times per year.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
The dataset will be kept on Filecoin for 1-3 years as planned for now, but the duration may extend afterwards.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Greater China, but we don't rule out the possibilities of keeping it in other areas.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
We prefer to transfer the data offline considering the cost and feasibility.

```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We plan to find 5~10 SPs from Greater China, HK and North America. We will choose reputable SPs that offer fast retrieval service.

```

How will you be distributing deals across storage providers?
```
We promise to distribute the dataset equally to SPs, and no single SP will take up over 20% of the deal.

```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
We are well prepared and we will get the ball rolling upon the receival of DataCap. We would be appreciated if the community helps to clear the way ahead of us in case of any emergency.

```

**Comment by raghavrmadya** [comment]
Can you share what's your relationship with StorageLabs?

**Comment by StorageLabs** [comment]
> Can you share what's your relationship with StorageLabs?

I am the person in charge of StorageLabs and I can send you an email with the official mail(admin@storagelabs.io) to prove my identity. The StorageLabs is always dedicated to storing and sharing of scientific research data and also constructing the data storage and transmission tools accordingly

**Comment by StorageLabs** [comment]
@raghavrmadya any updates?

**Comment by raghavrmadya** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 100TiB

**Client address**

> f173hsbasxc44gy3dwbuauwvhthjxtjyl6f7ozdli

**Comment by StorageLabs** [comment]
@raghavrmadya Hi, is there anything should we do now or just waiting for signature?

**Comment by StorageLabs** [comment]
@galen-mcandrew @raghavrmadya @Kevin-FF-USA  It's been 17 days and still no notary signs our application. It would be grateful if you can spare some time and help us to get the DataCap faster. Any question, please let us know.

**Comment by kernelogic** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebvt7gnjijzqeq2vkmu4czk4opuvodo7pbixpjhve5lkr4wc2ptra 
#### Address 
> f173hsbasxc44gy3dwbuauwvhthjxtjyl6f7ozdli
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebvt7gnjijzqeq2vkmu4czk4opuvodo7pbixpjhve5lkr4wc2ptra

**Comment by StorageLabs** [comment]
Hi, notaries, who can help me approve the dataCap request here? Thank a lot.

**Comment by StorageLabs** [comment]
Hi，your kindness would be appreciated if one more sign is added, many thanks.

**Comment by StorageLabs** [comment]
@newwebgroup@MegTei@stcouldlisa @liyunzhi-666  one month has passed and we still get no dataCap, will you approve the issue ? We just need one more signing. Thanks.

**Comment by newwebgroup** [comment]
Ok, Sir, @StorageLabs 
 I will check your project and sample data.

**Comment by newwebgroup** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceahm7tq4usm2q5pin3n3q4huhsdpxvztyloadztzsrrucitnzc4l2 
#### Address 
> f173hsbasxc44gy3dwbuauwvhthjxtjyl6f7ozdli
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1e77zuityhvvw6u2t6tb5qlnsegy2s67qs4lbbbq
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceahm7tq4usm2q5pin3n3q4huhsdpxvztyloadztzsrrucitnzc4l2

**Comment by BigD-Exchange** [comment]
@StorageLabs  Hi! Great to see you have gotten approval for DataCap and advancing the mission of preserving humanity’s most important information. If you are looking for storage providers to store these data or have any questions, please visit #bigdata-exchange on Filecoin Slack or reply here. 

We have strong demand from a diverse group of SPs, who are actively looking to onboard more data.

**Comment by Sunnyiscoming** [comment]
Is there any problem with using datacap?

**Comment by StorageLabs** [comment]
please keep open

**Comment by StorageLabs** [comment]
keep open

**Comment by StorageLabs** [comment]
keep open

**Comment by StorageLabs** [comment]
re-open please @simonkim0515

**Comment by StorageLabs** [comment]
@Sunnyiscoming
