### ISSUE TITLE
[DataCap Application] Kernelogic - NREL National Solar Radiation Database

### ISSUE THREAD

**Issue by kernelogic** [filecoin-project/filecoin-plus-large-datasets#1104]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Fei Yan - Kernelogic
- Website / Social Media: https://singularity-browser.kernelogic.ca/ Slack: Fei Yan
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5 PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 750 TiB
- On-chain address for first allocation: f1vm5pdhzt5bx55xuywtqlx3j2qwllzh4mmnuel5i

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
I have participated every Slingshot phase and is probably the best performing as a "small individual client". 

Even though Slingshot v2 has ended, there are still strong demand from SPs to onboard useful data. This application is to onboard open dataset from AWS.

I will provide a nice web UI (https://github.com/tech-greedy/singularity-browser) to index all files onboarded and provide ways to retrieve.

I have successfully completed a few LDNs on other datasets and I have record to show I have been following the rules of decentralization and have zero self dealing.

https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/60
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/59
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/46
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/297
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/298
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/304
```

What is the primary source of funding for this project?
```
Self-funded, BigD exchange.
```

What other projects/ecosystem stakeholders is this project associated with?
```
enterprise-sp-wg, BigD exchange.
```

## Use-case details

Describe the data being stored onto Filecoin
```
The National Solar Radiation Database (NSRDB) is a serially complete collection of hourly and half-hourly values of 
the three most common measurements of solar radiation – global horizontal, direct normal, and diffuse horizontal 
irradiance — and meteorological data.

Total size: 340 TiB
```

Where was the data in this dataset sourced from?
```
https://nsrdb.nrel.gov/
https://registry.opendata.aws/nrel-pds-nsrdb/
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://registry.opendata.aws/nrel-pds-nsrdb/
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
AWS Open dataset. Creative Commons Attribution 3.0 United States License.
```

What is the expected retrieval frequency for this data?
```
Multiple times per year.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
18 months.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
All regions.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
I will upload my prepared CAR files to a web server and coordinate with providers to download and propose offline deals.

Maximum 3 copies per SP entity and maximum of 12 copies for every pieceCID.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
Beside the previous SPs I have worked with, I also utilize bigD exchange to further decentralize the storage

To name a few from the community that I deal with regularly: PIKNIK, Holon, CabrinaHuang, HarryM, BigBear, j1v, XinAn Xu, WillTechMusing.

From BigD exchange: Mog Li, Devin Chen, DSS Nathanial Marsh, Rabinovitch, Vin K, arockpool Tony
```

How will you be distributing deals across storage providers?
```
Evenly across all providers I propose to, if they can handle. If a miner is a notary itself, this notary will receive no more than 20% of the total granted datacap.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
I have all I need to start making deals.
```

**Comment by raghavrmadya** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 750TiB

**Client address**

>f1vm5pdhzt5bx55xuywtqlx3j2qwllzh4mmnuel5i

**Comment by NDLABS-OFFICE** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebfhr7l5zuzmx6axh4zhzj72wx6hboebvqibr4xagh4ugecrngiws 
#### Address 
> f1vm5pdhzt5bx55xuywtqlx3j2qwllzh4mmnuel5i
#### Datacap Allocated
> 256.00TiB
#### Signer Address
> f1yayfsv6whu3rheviucvventj3y6t542xfpb47ei
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebfhr7l5zuzmx6axh4zhzj72wx6hboebvqibr4xagh4ugecrngiws

**Comment by Tom-OriginStorage** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebkau22d2ondkiegz3xg7k6cnavcy4nvklj4n7x65qicpnely3pra 
#### Address 
> f1vm5pdhzt5bx55xuywtqlx3j2qwllzh4mmnuel5i
#### Datacap Allocated
> 256.00TiB
#### Signer Address
> f1q6bpjlqia6iemqbrdaxr2uehrhpvoju3qh4lpga
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebkau22d2ondkiegz3xg7k6cnavcy4nvklj4n7x65qicpnely3pra

**Comment by newwebgroup** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced5u4udpoj3dl4gplinzhinopy7kj5nwjyfk3a3e73m4xed2m5pmc 
#### Address 
> f1vm5pdhzt5bx55xuywtqlx3j2qwllzh4mmnuel5i
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f1e77zuityhvvw6u2t6tb5qlnsegy2s67qs4lbbbq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced5u4udpoj3dl4gplinzhinopy7kj5nwjyfk3a3e73m4xed2m5pmc

**Comment by Tom-OriginStorage** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced52mu5uaol3rkcrj7v6lbmanbsk5quuxtenecjnq2e65b4yg4qi6 
#### Address 
> f1vm5pdhzt5bx55xuywtqlx3j2qwllzh4mmnuel5i
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f1q6bpjlqia6iemqbrdaxr2uehrhpvoju3qh4lpga
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced52mu5uaol3rkcrj7v6lbmanbsk5quuxtenecjnq2e65b4yg4qi6

**Comment by derricktan23** [comment]
@raghavrmadya @galen-mcandrew @Kevin-FF-USA  
Can the notaries signing these two[ data requests  ](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1080) be the same ? Is this double notary signing according to the LDN Application rules? As per  https://github.com/filecoin-project/filecoin-plus-large-datasets#applying-for-a-large-datacap-allocation, **The same notary cannot sign off on immediately subsequent allocations of DataCap.**

**Comment by ipfscn** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecn76eei2te52swjrvo3zsik2xhb4jnmuxc4ov3twjewl3hvtaxwi 
#### Address 
> f1vm5pdhzt5bx55xuywtqlx3j2qwllzh4mmnuel5i
#### Datacap Allocated
> 1.00PiB
#### Signer Address
> f1j4n74chme7whbz3yls4a7ixqewb6dijypqg2a3a
#### Id
> ee5ef689-fd95-4dcb-8100-418887759f54
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecn76eei2te52swjrvo3zsik2xhb4jnmuxc4ov3twjewl3hvtaxwi

**Comment by xingjitansuo** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebgz2joxjkvgafat67gvrswhup73pa3zqjapax2nuddlsfn3sgvuc 
#### Address 
> f1vm5pdhzt5bx55xuywtqlx3j2qwllzh4mmnuel5i
#### Datacap Allocated
> 1.00PiB
#### Signer Address
> f1a2lia2cwwekeubwo4nppt4v4vebxs2frozarz3q
#### Id
> ee5ef689-fd95-4dcb-8100-418887759f54
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebgz2joxjkvgafat67gvrswhup73pa3zqjapax2nuddlsfn3sgvuc

**Comment by stcouldlisa** [comment]
looks good

**Comment by stcouldlisa** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedml36y657aqxrbbfog52b674v324fzxr374imo4pkfge76caulnq 
#### Address 
> f1vm5pdhzt5bx55xuywtqlx3j2qwllzh4mmnuel5i
#### Datacap Allocated
> 2.00PiB
#### Signer Address
> f1jvvltduw35u6inn5tr4nfualyd42bh3vjtylgci
#### Id
> 4bdac193-0635-4eab-9b21-6da3e93c56fe
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedml36y657aqxrbbfog52b674v324fzxr374imo4pkfge76caulnq

**Comment by kernelogic** [comment]
It seems bot triggered signing immediately again. Will not push to sign until use up.

**Comment by 1ane-1** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebkzkhwv5sxicxuan3rp4u2j624r4l3cnwmbjnoqrkzsvzszvveru 
#### Address 
> f1vm5pdhzt5bx55xuywtqlx3j2qwllzh4mmnuel5i
#### Datacap Allocated
> 1.25PiB
#### Signer Address
> f1mdk7s2vntzm6hu35yuo6vjubtrpfnb2awhgvrri
#### Id
> c46edacc-2253-4fbc-9ed2-951bef0fbd34
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebkzkhwv5sxicxuan3rp4u2j624r4l3cnwmbjnoqrkzsvzszvveru

**Comment by cryptowhizzard** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced543kz7boyct2gjpfrnrdxtjaephwcliuvgymhqjbmf2raqnnnuq 
#### Address 
> f1vm5pdhzt5bx55xuywtqlx3j2qwllzh4mmnuel5i
#### Datacap Allocated
> 1.25PiB
#### Signer Address
> f1krmypm4uoxxf3g7okrwtrahlmpcph3y7rbqqgfa
#### Id
> c46edacc-2253-4fbc-9ed2-951bef0fbd34
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced543kz7boyct2gjpfrnrdxtjaephwcliuvgymhqjbmf2raqnnnuq

**Comment by filplus-checker** [comment]
## DataCap and CID Checker Report[^1]
 - Organization: `Fei Yan - Kernelogic`
 - Client: `f1vm5pdhzt5bx55xuywtqlx3j2qwllzh4mmnuel5i`
### Storage Provider Distribution
The below table shows the distribution of storage providers that have stored data for this client.

If this is the first time a provider takes verified deal, it will be marked as `new`.

For most of the datacap application, below restrictions should apply.
 - Storage provider should not exceed 25% of total datacap.
 - Storage provider should not be storing duplicate data for more than 20%.
 - Storage provider should have published its public IP address.
 - All storage providers should be located in different regions.

✔️ Storage provider distribution looks healthy.

| Provider                                              |                           Location | Total Deals Sealed | Percentage | Unique Data | Duplicate Deals |
| :---------------------------------------------------- | ---------------------------------: | -----------------: | ---------: | ----------: | --------------: |
| [f01923787](https://filfox.info/en/address/f01923787) |            Shenzhen, Guangdong, CN |         347.03 TiB |     12.60% |  347.03 TiB |           0.00% |
| [f01938674](https://filfox.info/en/address/f01938674) |            Shenzhen, Guangdong, CN |         329.75 TiB |     11.97% |  329.75 TiB |           0.00% |
| [f01970716](https://filfox.info/en/address/f01970716) |            Shenzhen, Guangdong, CN |         305.94 TiB |     11.11% |  305.94 TiB |           0.00% |
| [f01927554](https://filfox.info/en/address/f01927554) |            Shenzhen, Guangdong, CN |         277.66 TiB |     10.08% |  277.66 TiB |           0.00% |
| [f01938671](https://filfox.info/en/address/f01938671) | Hong Kong, Central and Western, HK |         266.38 TiB |      9.67% |  266.38 TiB |           0.00% |
| [f01923786](https://filfox.info/en/address/f01923786) | Hong Kong, Central and Western, HK |         251.91 TiB |      9.15% |  251.91 TiB |           0.00% |
| [f01918046](https://filfox.info/en/address/f01918046) |     Kuala Lumpur, Kuala Lumpur, MY |         206.25 TiB |      7.49% |  206.25 TiB |           0.00% |
| [f01918045](https://filfox.info/en/address/f01918045) |     Kuala Lumpur, Kuala Lumpur, MY |         206.25 TiB |      7.49% |  206.25 TiB |           0.00% |
| [f01909705](https://filfox.info/en/address/f01909705) |     Kuala Lumpur, Kuala Lumpur, MY |         206.25 TiB |      7.49% |  206.25 TiB |           0.00% |
| [f01660795](https://filfox.info/en/address/f01660795) |            Shenzhen, Guangdong, CN |         201.16 TiB |      7.30% |  201.16 TiB |           0.00% |
| [f01859603](https://filfox.info/en/address/f01859603) |            Shenzhen, Guangdong, CN |         155.56 TiB |      5.65% |  155.56 TiB |           0.00% |

![Provider Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/1104/1671098560493.png)
### Deal Data Replication
The below table shows how each many unique data are replicated across storage providers.
- No more than 25% of unique data are stored with less than 4 providers.

✔️ Data replication looks healthy.

| Unique Data Size | Total Deals Made | Number of Providers | Deal Percentage |
| ---------------: | ---------------: | ------------------: | --------------: |
|        18.06 TiB |        18.06 TiB |                   1 |           0.66% |
|        33.41 TiB |        66.81 TiB |                   2 |           2.43% |
|        29.47 TiB |        88.41 TiB |                   3 |           3.21% |
|        14.72 TiB |        58.88 TiB |                   4 |           2.14% |
|        22.03 TiB |       110.16 TiB |                   5 |           4.00% |
|        20.59 TiB |       123.56 TiB |                   6 |           4.49% |
|        36.50 TiB |       255.50 TiB |                   7 |           9.28% |
|        31.16 TiB |       249.25 TiB |                   8 |           9.05% |
|        48.34 TiB |       435.09 TiB |                   9 |          15.80% |
|        73.34 TiB |       733.44 TiB |                  10 |          26.63% |
|        55.91 TiB |       614.97 TiB |                  11 |          22.33% |

![Replication Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/1104/1671098561015.png)
### Deal Data Shared with other Clients
The below table shows how many unique data are shared with other clients.
Usually different applications owns different data and should not resolve to the same CID.

✔️ No CID sharing has been observed.

[^1]: To manually trigger this report, add a comment with text `checker:manualTrigger`
