### ISSUE TITLE
[DataCap Application] Kernelogic - Hubble Space Telescope Public Data

### ISSUE THREAD

**Issue by kernelogic** [filecoin-project/filecoin-plus-large-datasets#1105]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Fei Yan - Kernelogic
- Website / Social Media: https://singularity-browser.kernelogic.ca/ Slack: Fei Yan
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5 PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 750 TiB
- On-chain address for first allocation: f1gt3lmd64eeknyuf7pkdsyzj57bxbaq4oa3lvjla

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
I have participated every Slingshot phase and is probably the best performing as a "small individual client". 

Even though Slingshot v2 has ended, there are still strong demand from SPs to onboard useful data. This application is to onboard open dataset from AWS.

I will provide a nice web UI (https://github.com/tech-greedy/singularity-browser) to index all files onboarded and provide ways to retrieve.

I have successfully completed a few LDNs on other datasets and I have record to show I have been following the rules of decentralization and have zero self dealing.

https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/60
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/59
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/46
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/297
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/298
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/304
```

What is the primary source of funding for this project?
```
Self-funded, BigD exchange.
```

What other projects/ecosystem stakeholders is this project associated with?
```
enterprise-sp-wg, BigD exchange.
```

## Use-case details

Describe the data being stored onto Filecoin
```
The Hubble Space Telescope (HST) is one of the most productive scientific instruments ever created. 
This dataset contains calibrated and raw data for all of the currently active instruments on HST: ACS, COS, STIS and WFC3.

Total size: 292.3 TiB
```

Where was the data in this dataset sourced from?
```
https://astroquery.readthedocs.io/en/latest/mast/mast.html
https://registry.opendata.aws/hst/
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://registry.opendata.aws/hst/
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
AWS Open dataset. Cited from the website:

STScI herby grants the non-exclusive, royalty free, non-transferable, worldwide right and license to use, reproduce and publicly display in all media public data from the Hubble Space Telescope.
```

What is the expected retrieval frequency for this data?
```
Multiple times per year.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
18 months.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
All regions.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
I will upload my prepared CAR files to a web server and coordinate with providers to download and propose offline deals.

Maximum 3 copies per SP entity and maximum of 12 copies for every pieceCID.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
Beside the previous SPs I have worked with, I also utilize bigD exchange to further decentralize the storage

To name a few from the community that I deal with regularly: PIKNIK, Holon, CabrinaHuang, HarryM, BigBear, j1v, XinAn Xu, WillTechMusing.

From BigD exchange: Mog Li, Devin Chen, DSS Nathanial Marsh, Rabinovitch, Vin K, arockpool Tony
```

How will you be distributing deals across storage providers?
```
Evenly across all providers I propose to, if they can handle. If a miner is a notary itself, this notary will receive no more than 20% of the total granted datacap.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
I have all I need to start making deals.
```

**Comment by raghavrmadya** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 750TiB

**Client address**

>f1gt3lmd64eeknyuf7pkdsyzj57bxbaq4oa3lvjla

**Comment by NDLABS-OFFICE** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceblhpabzzolt4p5bdevsywpyocdr6n66xo7n3cixufpt7mcml52fm 
#### Address 
> f1gt3lmd64eeknyuf7pkdsyzj57bxbaq4oa3lvjla
#### Datacap Allocated
> 256.00TiB
#### Signer Address
> f1yayfsv6whu3rheviucvventj3y6t542xfpb47ei
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceblhpabzzolt4p5bdevsywpyocdr6n66xo7n3cixufpt7mcml52fm

**Comment by filplus-checker** [comment]
## DataCap and CID Checker Report[^1]
 - Organization: `Fei Yan - Kernelogic`
 - Client: `f1gt3lmd64eeknyuf7pkdsyzj57bxbaq4oa3lvjla`
### Storage Provider Distribution
The below table shows the distribution of storage providers that have stored data for this client.

If this is the first time a provider takes verified deal, it will be marked as `new`.

For most of the datacap application, below restrictions should apply.
 - Storage provider should not exceed 25% of total datacap.
 - Storage provider should not be storing duplicate data for more than 20%.
 - Storage provider should have published its public IP address.
 - All storage providers should be located in different regions.

⚠️ [f01928097](https://filfox.info/en/address/f01928097) has sealed 100.00% of total datacap.

⚠️ All storage providers are located in the same region.

| Provider                                              |                           Location | Total Deals Sealed | Percentage | Unique Data | Duplicate Deals |
| :---------------------------------------------------- | ---------------------------------: | -----------------: | ---------: | ----------: | --------------: |
| [f01928097](https://filfox.info/en/address/f01928097) | Hong Kong, Central and Western, HK |          50.00 TiB |    100.00% |   50.00 TiB |           0.00% |

![Provider Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/1105/1671098566083.png)
### Deal Data Replication
The below table shows how each many unique data are replicated across storage providers.
- No more than 25% of unique data are stored with less than 4 providers.

⚠️ 100.00% of deals are for data replicated across less than 4 storage providers.

| Unique Data Size | Total Deals Made | Number of Providers | Deal Percentage |
| ---------------: | ---------------: | ------------------: | --------------: |
|        50.00 TiB |        50.00 TiB |                   1 |         100.00% |

![Replication Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/1105/1671098566576.png)
### Deal Data Shared with other Clients
The below table shows how many unique data are shared with other clients.
Usually different applications owns different data and should not resolve to the same CID.

✔️ No CID sharing has been observed.

[^1]: To manually trigger this report, add a comment with text `checker:manualTrigger`

**Comment by newwebgroup** [comment]
CID Checker looks good

**Comment by newwebgroup** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb33fv45lr2ydveustecptxzamn3t2v3nmtloqwyi6kmnk7mtl5ke 
#### Address 
> f1gt3lmd64eeknyuf7pkdsyzj57bxbaq4oa3lvjla
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f1e77zuityhvvw6u2t6tb5qlnsegy2s67qs4lbbbq
#### Id
> 6aac4483-6a4f-457c-ad24-4cda20961fb1
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb33fv45lr2ydveustecptxzamn3t2v3nmtloqwyi6kmnk7mtl5ke

**Comment by ipfscn** [comment]
The bot shows that this customer is very good

**Comment by ipfscn** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedwvlotififl4mpygdjkwxzbd4dsfqxsl52mkglkt4v6qwrtwv45c 
#### Address 
> f1gt3lmd64eeknyuf7pkdsyzj57bxbaq4oa3lvjla
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f1j4n74chme7whbz3yls4a7ixqewb6dijypqg2a3a
#### Id
> 6aac4483-6a4f-457c-ad24-4cda20961fb1
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedwvlotififl4mpygdjkwxzbd4dsfqxsl52mkglkt4v6qwrtwv45c

**Comment by cryptowhizzard** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaq67dzk2sakohv7rl743zeswgawseqbmn34swra7ghvjopzswcuk 
#### Address 
> f1gt3lmd64eeknyuf7pkdsyzj57bxbaq4oa3lvjla
#### Datacap Allocated
> 1.00PiB
#### Signer Address
> f1krmypm4uoxxf3g7okrwtrahlmpcph3y7rbqqgfa
#### Id
> 5acabd98-6fdc-49b3-aed4-94871573e912
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaq67dzk2sakohv7rl743zeswgawseqbmn34swra7ghvjopzswcuk

**Comment by xiaoyuaiheshui** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecjhohwachifzl3udafizae65aekhumrfsfm6336klfd2yqwpesly 
#### Address 
> f1gt3lmd64eeknyuf7pkdsyzj57bxbaq4oa3lvjla
#### Datacap Allocated
> 1.00PiB
#### Signer Address
> f122qmy25wdtt5mxd77kndiq7z5x2n3iwiuz2wdsa
#### Id
> 5acabd98-6fdc-49b3-aed4-94871573e912
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecjhohwachifzl3udafizae65aekhumrfsfm6336klfd2yqwpesly

**Comment by kernelogic** [comment]
checker:manualTrigger

**Comment by xingjitansuo** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced2gt4fdctamlbko7hllyxusb5odqt6ca7uv6rqsvwepyyuz2ddhm 
#### Address 
> f1gt3lmd64eeknyuf7pkdsyzj57bxbaq4oa3lvjla
#### Datacap Allocated
> 1.00PiB
#### Signer Address
> f1a2lia2cwwekeubwo4nppt4v4vebxs2frozarz3q
#### Id
> 5acabd98-6fdc-49b3-aed4-94871573e912
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced2gt4fdctamlbko7hllyxusb5odqt6ca7uv6rqsvwepyyuz2ddhm

**Comment by stcouldlisa** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceabtu5cakyae7xmyp4zxgf6lm5ijlocjlnhb7y4fywnhkveda76dw 
#### Address 
> f1gt3lmd64eeknyuf7pkdsyzj57bxbaq4oa3lvjla
#### Datacap Allocated
> 1.00PiB
#### Signer Address
> f1jvvltduw35u6inn5tr4nfualyd42bh3vjtylgci
#### Id
> 5acabd98-6fdc-49b3-aed4-94871573e912
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceabtu5cakyae7xmyp4zxgf6lm5ijlocjlnhb7y4fywnhkveda76dw

**Comment by stcouldlisa** [comment]
looks good

**Comment by cryptowhizzard** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceagoebegcad2smmszejudmv4yvcc6tnzckq3p4zzzdmmgdgbob7zg 
#### Address 
> f1gt3lmd64eeknyuf7pkdsyzj57bxbaq4oa3lvjla
#### Datacap Allocated
> 2.00PiB
#### Signer Address
> f1krmypm4uoxxf3g7okrwtrahlmpcph3y7rbqqgfa
#### Id
> 0e5e8c63-5659-403d-8499-24e4a5c99fe0
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceagoebegcad2smmszejudmv4yvcc6tnzckq3p4zzzdmmgdgbob7zg

**Comment by BDEio** [comment]
@kernelogic Hi! Great to see that you have gotten approval for DataCap!
BDE is a verified deals auction house helping you to get paid storing your data with reliable storage providers. If you need any help, please get in touch.

**Comment by flyworker** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecicjyqarawzipn5oo44swjdgzrgusmwdiufdu6qe5txlfo3runhg 
#### Address 
> f1gt3lmd64eeknyuf7pkdsyzj57bxbaq4oa3lvjla
#### Datacap Allocated
> 1.25PiB
#### Signer Address
> f1hlubjsdkv4wmsdadihloxgwrz3j3ernf6i3cbpy
#### Id
> 19b182f6-a519-41ac-aa0d-0b6681dd6426
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecicjyqarawzipn5oo44swjdgzrgusmwdiufdu6qe5txlfo3runhg

**Comment by Tom-OriginStorage** [comment]
<img width="966" alt="image" src="https://user-images.githubusercontent.com/103015469/218395065-6574e18d-e814-4ee4-88c5-8e63d8c0fd59.png">
The package looks all compliant, and there is no cid sharing, I checked and it is retrievable, willing to support

**Comment by Tom-OriginStorage** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedsqeaj6j3hby3f7qwyoatoibcikzkxlpzhvmhelfz5s4ndcs3d6q 
#### Address 
> f1gt3lmd64eeknyuf7pkdsyzj57bxbaq4oa3lvjla
#### Datacap Allocated
> 1.25PiB
#### Signer Address
> f1q6bpjlqia6iemqbrdaxr2uehrhpvoju3qh4lpga
#### Id
> 19b182f6-a519-41ac-aa0d-0b6681dd6426
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedsqeaj6j3hby3f7qwyoatoibcikzkxlpzhvmhelfz5s4ndcs3d6q
