### ISSUE TITLE
[DataCap Application] < MovieLife >

### ISSUE THREAD

**Issue by laff2022** [filecoin-project/filecoin-plus-large-datasets#1109]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name:  MovieLife
- Website / Social Media: https://movielife.top/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):  5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100TiB
- On-chain address for first allocation: f1lbvh2tnpjvr4b6kkmxzrybftf7k7k5426eetzji

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
MovieLife is a media video platform that provides users with services to download, watch and share video clips covering sports, daily life, news, fashion, games, and more. We are recently developing digital media, integrating blockchain technology to combine content and NFT. 
We hope to store existing data as well as new data in the future on Filecoin to reduce data storage costs and enhance the competitiveness of Movielife.
```

What is the primary source of funding for this project?
```
It's from own funds and revenue of the company.
```

What other projects/ecosystem stakeholders is this project associated with?
```
No related association
```

## Use-case details

Describe the data being stored onto Filecoin
```
It mainly contains videos and images, raw data collected and used for processing, and video clips posted to the website after secondary editing and processing.
```

Where was the data in this dataset sourced from?
```
AWS，YouTube,  Owned data
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```

https://movielife.top/download/DataSample02.zip
https://www.dropbox.com/sh/kl3hphg1y2xjv5z/AAAuAWWRBP6kDal8nN7kSLLfa?dl=0  
https://www.dropbox.com/s/naqm6b3yco89fwd/DataSample-04.zip?dl=0   
https://registry.opendata.aws/multimedia-commons/
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
yes.
```

What is the expected retrieval frequency for this data?
```
Multiple times per year
```

For how long do you plan to keep this dataset stored on Filecoin?
```
2- 4 years.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
EU / US / Australia / Asia.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
The data will be transferred both offline and online.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We already have a few providers who have been working with the project of storing and backing up the data of  videos, so we hope we can negotiate successfully and continue to cooperate.
```

How will you be distributing deals across storage providers?
```
Max 2 copy's per storage provider if stored on different miners / locations.
We plan to distribute deals to 3-5 or more miners. We also need to have multiple copies across miners.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, we have the resources.
and we have already got a file upload program which is compiled by ourself. So we can onboard our data onto filecoin on our own
```

**Comment by raghavrmadya** [comment]
It seems like it's a combination of open datasets and data generated by your organization. What's the distribution and can you provide further proof that the dropbox files are owned by your organization?

**Comment by laff2022** [comment]
@raghavrmadya Thank you for your question

MovieLife has made a Disclaimers file in Dropbox 
[ https://www.dropbox.com/s/624u4m86y7kc7fh/Disclaimers.txt?dl=0 ]

And put it in the sample data of Dropbox.
[ https://www.dropbox.com/s/79s4gw2jrrlcqgp/DataSample-04.zip?dl=0 ]
[ https://www.dropbox.com/sh/kl3hphg1y2xjv5z/AAAuAWWRBP6kDal8nN7kSLLfa?dl=0 ]

Here is the Disclaimers.
All video files in this Dropbox are original data obtained from MovieLife based on the collection of public data, and are created, edited, and produced secondarily. 
Therefore, these products are owned by MovieLife.
They are only used to apply for Large Dataset Notary ApplicationData from Filecoin.

**Comment by raghavrmadya** [comment]
Ok. What is your relationship with MovieLife?

**Comment by laff2022** [comment]
@raghavrmadya 
I am the Technical Manager of MovieLife，
responsible for daily operation of Movielife.
Email： administrators@movielife.top

**Comment by raghavrmadya** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 100TiB

**Client address**

> f1lbvh2tnpjvr4b6kkmxzrybftf7k7k5426eetzji

**Comment by laff2022** [comment]
@Carohere 
Hi man，
This is Barry, I'm the Technical Manager of MovieLife, responsible for daily operation of Movielife. Alan is my partner, investor of MovieLife. 
Thanks for your interest in our project.
MovieLife is a media platform. We have been collecting public data and doing videoclip to pick up something important from the original data. 
We are going to develop social function that  our uses can make comments on our platform like BiliBili and Youtube. 
When there are enough users, we plan to issue NFTs. We are negotiating with some artists who know nothing about blockchain to design and issue NFTs in our platform. We aim to make more and more people know about blockchian, know about NFTs.
As you know, it cost us a lot on data storage for our platform. We have tried some other solutions to optimize cost control, but there is nothing better than IPFS. This is why we applied for a substantial DataCap.
We thank you once again for your interest in this project.

**Comment by GaryGJG** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecu7tgsnv3kkdelqk4eehsfgrzlg4r3d3sv5km6qsg4q6254hhkzy 
#### Address 
> f1lbvh2tnpjvr4b6kkmxzrybftf7k7k5426eetzji
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1zffqhxwq2rrg7rtot6lmkl6hb2xyrrseawprzsq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecu7tgsnv3kkdelqk4eehsfgrzlg4r3d3sv5km6qsg4q6254hhkzy

**Comment by Carohere** [comment]
Hi @laff2022, I still don't get why would your partner have many applications and even offered to pay notaries... In my opinion, this application is quite dubious. With all due respect, I am not sure under what circumstances the notary would approve it... 
Cc: @raghavrmadya is there any better way to verify the authenticity of applications with known violations of Fil+ rules such as bribery?

**Comment by laff2022** [comment]
Hi, @Carohere. 
As an investor, Alan has the right to invest in any projects.
I honestly believe that our community is a fair and rational community. 
Now we are talking about our project here, if you have any question about our project, feel free to ask us. 
If you have some question about Alan, you can contact him via slack. I think he might be treated unfairly before. Now he has talked with RG and already got some suggestions and also understand the community guidelines. 
I reviewed a lot of applications from other applicants including those which were approved directly without any question. I believe our team is one of the applicants who has already explained the projects clearly.
If you still have some question about our project, please ask us here. Thank you.

**Comment by laff2022** [comment]
@raghavrmadya  
Hello, it has been 60 days since last allocation, we still could not begin our work. Obviously, there aren't enough notaries in Oceania area. Can you help me take a loot at it? Thank you so much.

**Comment by kevzak** [comment]
@laff2022 I might be able to help here at least help confirm KYC/KYB for your business. 

If you want to complete KYC and KYB via the E-Fil+ pilot program. Let me know. cc @raghavrmadya

**Comment by newwebgroup** [comment]
Hey @laff2022 
**About KYC&KYB**
1：Could you send an email to [filplus-app-review@fil.org](mailto:filplus-app-review@fil.org) ？

The content should include the number of the LDN application. If possible, please attach copies of the business license and other valid certificates

2：Can you provide more detailed information about other storage providers participated in this program, such as you can list SPs you have contacted with at present?
3. How large is your existing dataset? How much is the data growth per month?


**What is Fil-E?**
Fil-E is an enterprise encrypted dataset .Private data sets specially serving some enterprises.
The data stored in Filecoin through Fil-E can be set for authorized access. Only the authorized person can view the data set.

**Comment by laff2022** [comment]
@newwebgroup 
1. We've already sent email and contact RG.
2. We have already build communication with some SPs like f01681632 f0837473 f01861068. Due to delayed approval, so we can't begin our work. 
3. At present, there are already 2P existing data. And we have 800g new data everyday. We plan to build 5-10 backups

**Comment by laff2022** [comment]
![Screenshot_2023-01-03-23-23-05-856-edit_com android email](https://user-images.githubusercontent.com/112842285/210387485-deb21b1b-3651-4d6a-80d8-d534ba984ab3.jpg)

**Comment by newwebgroup** [comment]
Because it was the first round, the Client answered my relevant questions, and the conditions for triggering signature had been met, so I chose to pass.
If anyone has more questions about the application, they can keep watching and checking.

**Comment by newwebgroup** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebyitgy23yrbu3hl5isvr54tha6jsgg5ixaxjdphiwksr3ukv4ftu 
#### Address 
> f1lbvh2tnpjvr4b6kkmxzrybftf7k7k5426eetzji
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1e77zuityhvvw6u2t6tb5qlnsegy2s67qs4lbbbq
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebyitgy23yrbu3hl5isvr54tha6jsgg5ixaxjdphiwksr3ukv4ftu

**Comment by Carohere** [comment]
> ![Screenshot_2023-01-03-23-23-05-856-edit_com android email](https://user-images.githubusercontent.com/112842285/210387485-deb21b1b-3651-4d6a-80d8-d534ba984ab3.jpg)
> 
> 
This was for notary application not what you have been asked for. Please send the requested information to the plus team.
@newwebgroup,could you elaborate on the KYC/KYB details you have done for this application?

**Comment by cryptowhizzard** [comment]
@newwebgroup again , why do you willfully sign on these applications? 

How much did you get payed for this?..... The content of this is disgusting to say at least and you are willfully ignoring the community and the health of humankind over a few $$$.

<img width="1387" alt="Scherm­afbeelding 2023-01-04 om 18 00 19" src="https://user-images.githubusercontent.com/36404435/210609305-e8ed6e6a-25b9-4446-ac94-255eb43992b5.png">

**Comment by herrehesse** [comment]
@newwebgroup there are detailed rumours that you are getting paid to sign datacap. If this is true you should be removed immediately. @raghavrmadya please join the conversation here.

**Comment by newwebgroup** [comment]
Spreading rumours without conrete evidence is a personal attack and should not be tolerated in the community. @herrehesse @cryptowhizzard  @raghavrmadya 

If you are a PL assigned datacap investigator, you should get better training on community code of conduct before leaving any more comments on LDNs.

**Comment by newwebgroup** [comment]
This is our workflow for signing LDN @Carohere @raghavrmadya 
<img width="1015" alt="image" src="https://user-images.githubusercontent.com/100118145/210688183-4d626131-3ae1-4c75-87c1-ce792dadfa2a.png">

**Comment by laff2022** [comment]
@Carohere @newwebgroup 
Email sent. I confused datacap application with notary application.
![微信图片_20230105120245](https://user-images.githubusercontent.com/112842285/210700163-184db4d9-b5cf-48db-a5f2-e41eacdfdd34.jpg)

**Comment by laff2022** [comment]
@cryptowhizzard 
I can't understand what do you mean with your screenshot. It's just a film clip. Did you watch this video or just glanced at the title？ Did you watch any movies or TV Series before？ Don't you know title is to attract audiences？
Furthermore, we have adult channel. 
I suggest you that don't judge that easily before you really know details. 
The most important thing we never did any under-table dealing. It's a malignant slander to me.

**Comment by cryptowhizzard** [comment]
Yes, i watched the video’s. I recommend you do the same? There are multiple.

**Comment by herrehesse** [comment]
@newwebgroup

It is an extreme example of how not to handle your status as a notary. The workflow picture shown above shows that there is thus absolutely no due diligence done on behalf of the @newwebgroup party once an approval is already in place.

Notaries are obligated at all times to verify each other. Blindly approving sets because a notary happens to have already signed is shifting responsibility. This way we can never have a mature conversation about a fraudulent application.

It also states that you do not sign at a dubious CID checker, however there are numerous examples where you did sign this. Please explain further?

@laff2022 

Would you please fill out the above questionnaire truthfully so that we have a better understanding of exactly how your company fits within the Filecoin+ ecosystem.

I would also like to make it explicitly clear that Filecoin+ is meant for useful and public datasets, adult content via a video platform is out of the question and does not fit into the Filecoin+ program at all. Some of the images are shocking.

**Comment by laff2022** [comment]
@herrehesse 
![微信图片_20230105161003](https://user-images.githubusercontent.com/112842285/210732237-87b3e01f-cfb5-4176-92f8-f897133e8f53.jpg)

Why can you apply for so much data (30P) on your own, and on behalf of different organizations
Are you an administrator of FIL+？

https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1516
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1514
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1513
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1512
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1511

Would you please fill out the same questionnaire truthfully so that we have a better understanding of exactly how your COMPANYS fits within the Filecoin+ ecosystem.

**Comment by laff2022** [comment]
@cryptowhizzard share the link please.
I said we have adult channel.

**Comment by herrehesse** [comment]
@laff2022 

Please send the questionnaire to the above posts and i LOVE to help you. Nothing to hide from my side.

**Comment by cryptowhizzard** [comment]
@laff2022 

you have stated that your country of operation is Australia. Your disclaimer also states that you edited the video’s that are online.

i have reported it under the NOTD procedure to the appropriate authority’s including your contact details.

**Comment by cryptowhizzard** [comment]
![Uploading 6A658E0F-274B-41BB-906D-5381F2C939D1.png…]()

**Comment by laff2022** [comment]
@cryptowhizzard 
Just do it

**Comment by BDEio** [comment]
@laff2022 Hi! Congratulations on your DataCap approval！
BDE is a verified deals auction house helping you to get paid storing your data with reliable storage providers. If you need any help, please get in touch.
