### ISSUE TITLE
[DataCap Application] Uber Online Network Technology

### ISSUE THREAD

**Issue by UberOnline** [filecoin-project/filecoin-plus-large-datasets#1110]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Beijing Uber Online Network Technology Co.
- Website / Social Media:www.51vv.com
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):100Tib
- On-chain address for first allocation:f1i7h433sotvuylpmphrtcpvchcmlpd7jgkmlwpga

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Beijing Uber Online Network Technology Co., Ltd. was registered in 2008. It is a company specializing in user VV entertainment community. The company's main business is: users upload videos, and the platform publishes and disseminates various dance, music and health activity videos.
It also includes technology development, technology promotion, technology consulting, technology service, technology transfer, etc.
```

What is the primary source of funding for this project?
```
Business income.
```

What other projects/ecosystem stakeholders is this project associated with?
```
None. We are the only one that engaged in this project.
```

## Use-case details

Describe the data being stored onto Filecoin
```
Video/audio data on various topics
```

Where was the data in this dataset sourced from?
```
From users and our own collection.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://drive.google.com/drive/folders/1OHmk8aF2bhn-husmkdz-2CT8Du2YUuf9?usp=sharing
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes, we confirm that all data are public and can be retrieved by anyone on the Network.
```

What is the expected retrieval frequency for this data?
```
We expect to retrieve our data twice a year.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
Permanently.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
All regions.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
We prefer to transfer our data online and offline. But bandwidth should be an issue for us. The final decision will depend on the cost.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
Having a faster internet connection for miners would be better for us.
```

How will you be distributing deals across storage providers?
```
We’d like to distribute our data to 10-20 miners, so every miner can have a copy of our data.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, I have enough money to start the project
```

**Comment by raghavrmadya** [comment]
We’d like to distribute our data to 10-20 miners, so every miner can have a copy of our data.
- Please elaborate

**Comment by raghavrmadya** [comment]
No response. Please open a new application if you wish to continue
