### ISSUE TITLE
[DataCap Application] NOAA GOES

### ISSUE THREAD

**Issue by Pierofree** [filecoin-project/filecoin-plus-large-datasets#1112]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: NOAA GOES---Piero
- Website / Social Media: https://registry.opendata.aws/noaa-goes/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):100TiB
- On-chain address for first allocation:f1csetl7nor3qie2cehx7axf2ai3nedmowj53xwsa

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
I have participated in hackathon projects and got a very good ranking.
```

What is the primary source of funding for this project?
```
By myself.
```

What other projects/ecosystem stakeholders is this project associated with?
```
No.
```

## Use-case details

Describe the data being stored onto Filecoin
```
GOES-16 imagery and metadata; new data notifications for GOES-16, only Lambda and SQS protocols allowed; GOES-17 imagery and metadata; new data notifications for GOES-17, only Lambda and SQS protocols allowed; GOES-18 imagery and metadata; new data notifications for GOES-18, only Lambda and SQS protocols allowed.
```

Where was the data in this dataset sourced from?
```
GOES satellites (GOES-16, GOES-17, & GOES-18) provide continuous weather imagery and monitoring of meteorological and space environment data across North America.  GOES satellites provide the kind of continuous monitoring necessary for intensive data analysis.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://registry.opendata.aws/noaa-goes/
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Confirm.
```

What is the expected retrieval frequency for this data?
```
Minimally if needed.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
540 days.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Asia, North America.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Both online and offline data transfer. 
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
I will send deals to those storage providers who have ability to support retrieval and stable seal.
```

How will you be distributing deals across storage providers?
```
I will distribute under 25% deals to every storage provider.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes.
```

**Comment by raghavrmadya** [comment]
What is unique about the way you plan to prepare this Data set?

**Comment by Pierofree** [comment]
In my IDC, I've prepared 1000M network for this Dataset. For storing and sending data, I prepared 400TiB+ hard disks. I will be ready to complete the deal.

**Comment by raghavrmadya** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 100TiB

**Client address**

>f1csetl7nor3qie2cehx7axf2ai3nedmowj53xwsa

**Comment by xingjitansuo** [comment]
It is excellent to see @Pierofree apply here. 
I propose a HOLD OFF on this application before we make clear how many copies @Pierofree  plans to store, and the amount of each copy. 
I checked the size of  NOAA GOES is around 1PiB. It is far less than @Pierofree has prepared on the hard disks.  
cc @raghavrmadya

**Comment by Pierofree** [comment]
@xingjitansuo Hey, thank you for your concern! This is only part of the disks I prepared, I will continue to increase the amount of it if I need.

**Comment by MetaWaveInfo** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceadz6ny4ahqbqi52cvfxfqfvgdalnncdxe5hiqo44rnqyxrwontom 
#### Address 
> f1csetl7nor3qie2cehx7axf2ai3nedmowj53xwsa
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1ktlkcxnmzxcdaoqfsunrg3vocfbmgv4n3mrn74a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceadz6ny4ahqbqi52cvfxfqfvgdalnncdxe5hiqo44rnqyxrwontom

**Comment by UnionLabs2020** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebw43fc3plwoav2dqnqxjaf4paap5jchntc7cfre4sgupoytmjy7u 
#### Address 
> f1csetl7nor3qie2cehx7axf2ai3nedmowj53xwsa
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f17xdri3wunqgld7dm23e4f3eqsntjakwc47xjo6i
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebw43fc3plwoav2dqnqxjaf4paap5jchntc7cfre4sgupoytmjy7u

**Comment by BigD-Exchange** [comment]
@Pierofree Hi! Great to see you have gotten approval for DataCap and advancing the mission of preserving humanity’s most important information. If you are looking for storage providers to store these data or have any questions, please visit #bigdata-exchange on Filecoin Slack or reply here. 

We have strong demand from a diverse group of SPs, who are actively looking to onboard more data.

**Comment by fireflyHZ** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedqmlfdccntxhy6o6ye5wzdos32hoete52dafjdgxskowedo45sh2 
#### Address 
> f1csetl7nor3qie2cehx7axf2ai3nedmowj53xwsa
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1fg6jkxsr3twfnyhdlatmq36xca6sshptscds7xa
#### Id
> 5b603f46-142a-4f7e-b7d1-efe272fd8e57
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedqmlfdccntxhy6o6ye5wzdos32hoete52dafjdgxskowedo45sh2

**Comment by ipfscn** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebe5owdoztkonzkvwavv2ue7lczfxrapxbdogbnvx6bi5wkvhzviu 
#### Address 
> f1csetl7nor3qie2cehx7axf2ai3nedmowj53xwsa
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1j4n74chme7whbz3yls4a7ixqewb6dijypqg2a3a
#### Id
> 5b603f46-142a-4f7e-b7d1-efe272fd8e57
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebe5owdoztkonzkvwavv2ue7lczfxrapxbdogbnvx6bi5wkvhzviu

**Comment by swatchliu** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedke3h2llxkqls3sqzwvbclhcbrxxdnoenqg2vz55t4ri7xyzq5iu 
#### Address 
> f1csetl7nor3qie2cehx7axf2ai3nedmowj53xwsa
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1yh6q3nmsg7i2sys7f7dexcuajgoweudcqj2chfi
#### Id
> 8a6579d6-130e-4bce-9b38-8c3bc2f86fcb
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedke3h2llxkqls3sqzwvbclhcbrxxdnoenqg2vz55t4ri7xyzq5iu

**Comment by MetaWaveInfo** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceamh6mved2j6sgwvkewucnlam3hvvlokmvdr2v7ds3sjsfkwi274c 
#### Address 
> f1csetl7nor3qie2cehx7axf2ai3nedmowj53xwsa
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1ktlkcxnmzxcdaoqfsunrg3vocfbmgv4n3mrn74a
#### Id
> 8a6579d6-130e-4bce-9b38-8c3bc2f86fcb
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceamh6mved2j6sgwvkewucnlam3hvvlokmvdr2v7ds3sjsfkwi274c

**Comment by UnionLabs2020** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebz42jrvhkmdym4fppffvp55fixtyx7jleh7i4ho6lkqi2fah4vd6 
#### Address 
> f1csetl7nor3qie2cehx7axf2ai3nedmowj53xwsa
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f17xdri3wunqgld7dm23e4f3eqsntjakwc47xjo6i
#### Id
> af79f235-8e5b-4ba4-8f00-70e145af2773
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebz42jrvhkmdym4fppffvp55fixtyx7jleh7i4ho6lkqi2fah4vd6

**Comment by stcouldlisa** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecb7bgfbx3u4ww6zfn3unbvsyitarsyhf2at5vqd57oezsbymvxzq 
#### Address 
> f1csetl7nor3qie2cehx7axf2ai3nedmowj53xwsa
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1jvvltduw35u6inn5tr4nfualyd42bh3vjtylgci
#### Id
> af79f235-8e5b-4ba4-8f00-70e145af2773
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecb7bgfbx3u4ww6zfn3unbvsyitarsyhf2at5vqd57oezsbymvxzq

**Comment by MetaWaveInfo** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedskxq4hbwkocu52lwvthwrzatlj6g22s7h2tnofn3ostsiv5vfne 
#### Address 
> f1csetl7nor3qie2cehx7axf2ai3nedmowj53xwsa
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1ktlkcxnmzxcdaoqfsunrg3vocfbmgv4n3mrn74a
#### Id
> b1c1e7c8-a125-42e1-9422-73a313c1d925
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedskxq4hbwkocu52lwvthwrzatlj6g22s7h2tnofn3ostsiv5vfne

**Comment by filplus-checker** [comment]
## DataCap and CID Checker Report[^1]
 - Organization: `NOAA GOES---Piero`
 - Client: `f1csetl7nor3qie2cehx7axf2ai3nedmowj53xwsa`
### Storage Provider Distribution
The below table shows the distribution of storage providers that have stored data for this client.

If this is the first time a provider takes verified deal, it will be marked as `new`.

For most of the datacap application, below restrictions should apply.
 - Storage provider should not exceed 25% of total datacap.
 - Storage provider should not be storing duplicate data for more than 20%.
 - Storage provider should have published its public IP address.
 - All storage providers should be located in different regions.

⚠️ [f01344987](https://filfox.info/en/address/f01344987) has sealed 43.80% of total datacap.

⚠️ 73.95% of total deal sealed by [f01344987](https://filfox.info/en/address/f01344987) are duplicate data.

⚠️ 82.57% of total deal sealed by [f01969789](https://filfox.info/en/address/f01969789) are duplicate data.

⚠️ 89.62% of total deal sealed by [f0229199](https://filfox.info/en/address/f0229199) are duplicate data.

⚠️ 86.52% of total deal sealed by [f0681068](https://filfox.info/en/address/f0681068) are duplicate data.

⚠️ 83.76% of total deal sealed by [f01841133](https://filfox.info/en/address/f01841133) are duplicate data.

⚠️ 87.59% of total deal sealed by [f0136399](https://filfox.info/en/address/f0136399) are duplicate data.

⚠️ 79.28% of total deal sealed by [f01392600](https://filfox.info/en/address/f01392600) are duplicate data.

⚠️ 73.42% of total deal sealed by [f01841131](https://filfox.info/en/address/f01841131) are duplicate data.

| Provider                                              |                           Location | Total Deals Sealed | Percentage | Unique Data | Duplicate Deals |
| :---------------------------------------------------- | ---------------------------------: | -----------------: | ---------: | ----------: | --------------: |
| [f01344987](https://filfox.info/en/address/f01344987) | Hong Kong, Central and Western, HK |         320.28 TiB |     43.80% |   83.44 TiB |          73.95% |
| [f01969789](https://filfox.info/en/address/f01969789) | Hong Kong, Central and Western, HK |         124.28 TiB |     17.00% |   21.66 TiB |          82.57% |
| [f0229199](https://filfox.info/en/address/f0229199)   | Hong Kong, Central and Western, HK |          80.69 TiB |     11.03% |    8.38 TiB |          89.62% |
| [f0681068](https://filfox.info/en/address/f0681068)   | Hong Kong, Central and Western, HK |          64.00 TiB |      8.75% |    8.63 TiB |          86.52% |
| [f01841133](https://filfox.info/en/address/f01841133) |           Singapore, Singapore, SG |          49.06 TiB |      6.71% |    7.97 TiB |          83.76% |
| [f0136399](https://filfox.info/en/address/f0136399)   | Hong Kong, Central and Western, HK |          42.31 TiB |      5.79% |    5.25 TiB |          87.59% |
| [f01392600](https://filfox.info/en/address/f01392600) | Hong Kong, Central and Western, HK |          25.94 TiB |      3.55% |    5.38 TiB |          79.28% |
| [f01841131](https://filfox.info/en/address/f01841131) | Hong Kong, Central and Western, HK |          24.69 TiB |      3.38% |    6.56 TiB |          73.42% |

![Provider Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/1112/1671098638643.png)
### Deal Data Replication
The below table shows how each many unique data are replicated across storage providers.
- No more than 25% of unique data are stored with less than 4 providers.

⚠️ 100.00% of deals are for data replicated across less than 4 storage providers.

| Unique Data Size | Total Deals Made | Number of Providers | Deal Percentage |
| ---------------: | ---------------: | ------------------: | --------------: |
|       112.69 TiB |       580.56 TiB |                   1 |          79.39% |
|        15.41 TiB |       138.25 TiB |                   2 |          18.91% |
|         1.25 TiB |        12.44 TiB |                   3 |           1.70% |

![Replication Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/1112/1671098639191.png)
### Deal Data Shared with other Clients
The below table shows how many unique data are shared with other clients.
Usually different applications owns different data and should not resolve to the same CID.

⚠️ CID sharing has been observed.

| Other Client                                                                                                                                                                                                              | Application                                                                                                       | Total Deals Affected | Unique CIDs |        Verifier |
| :------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ | :---------------------------------------------------------------------------------------------------------------- | -------------------: | ----------: | --------------: |
| [f1znd7uramgqquelcgefo5xgozopd3nga73hhywpy](https://filfox.info/en/address/f1znd7uramgqquelcgefo5xgozopd3nga73hhywpy)                                                                                                     | [BotSmart ](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/373)                          |            76.31 TiB |         344 | LDN v3 multisig |
| [f1fq6abg47ifgeee2z7q2rps3tvknoo2ztcoqy7ai](https://filfox.info/en/address/f1fq6abg47ifgeee2z7q2rps3tvknoo2ztcoqy7ai)                                                                                                     | [DaYe Art Tuition Class \(DKArt\) ](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/888)  |            72.47 TiB |         444 | LDN v3 multisig |
| [f1quofpadzcqlonmz7v3mv7dfqvm5hdztucdsjqsy](https://filfox.info/en/address/f1quofpadzcqlonmz7v3mv7dfqvm5hdztucdsjqsy)                                                                                                     | [HENAN 863 SOFTWARE CO\., LTD](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/468)       |            64.66 TiB |         188 | LDN v3 multisig |
| [f127l5waa4pw6k3sm4e7wxevc4fe5uz7dyt4mxa3i](https://filfox.info/en/address/f127l5waa4pw6k3sm4e7wxevc4fe5uz7dyt4mxa3i)                                                                                                     | `Pangod`                                                                                                          |            60.56 TiB |         343 | LDN v3 multisig |
| [f1wr6rwwqckh6um2hynaym2t4mniev5b675kbf5ni](https://filfox.info/en/address/f1wr6rwwqckh6um2hynaym2t4mniev5b675kbf5ni)                                                                                                     | [Ctrip Global Shopping](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/303)              |            59.66 TiB |         261 | LDN v3 multisig |
| [f1ugo3abkmmb4pb2atxz5oqqgwsd27b4p6k52f2va](https://filfox.info/en/address/f1ugo3abkmmb4pb2atxz5oqqgwsd27b4p6k52f2va)                                                                                                     | [Yuepass Technology Company Limited](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/429) |            56.03 TiB |         334 | LDN v3 multisig |
| [f1bb2z36lpq3pnwiiowiraagpzqnpow4bonjacx7a](https://filfox.info/en/address/f1bb2z36lpq3pnwiiowiraagpzqnpow4bonjacx7a)                                                                                                     | [Hola Space](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/362)                         |            53.69 TiB |         172 | LDN v3 multisig |
| [f1vbe7ze5yknpgu3orinv4zu4rkofsyqfsmpejpui](https://filfox.info/en/address/f1vbe7ze5yknpgu3orinv4zu4rkofsyqfsmpejpui)                                                                                                     | [HELIOS](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/305)                             |            47.91 TiB |         147 | LDN v3 multisig |
| [f1tgii4xgcp6um4n2w7eqaw6bwvnvyii2u7cjgzka](https://filfox.info/en/address/f1tgii4xgcp6um4n2w7eqaw6bwvnvyii2u7cjgzka)                                                                                                     | [Meson\.Network ](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/187)                    |            45.31 TiB |         161 | LDN v3 multisig |
| [f1ibuglt2lzlyf7vnmtzmuykcfgl2pn2fxym5dibi](https://filfox.info/en/address/f1ibuglt2lzlyf7vnmtzmuykcfgl2pn2fxym5dibi)                                                                                                     | [Appstest](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/346)                           |            29.25 TiB |         214 | LDN v3 multisig |
| [f1cf2pp6bgu6vvxfuau6bsmiibhrc7v3gvjsyseay](https://filfox.info/en/address/f1cf2pp6bgu6vvxfuau6bsmiibhrc7v3gvjsyseay)                                                                                                     | [Public Data\-FlyBrain](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1013)             |            28.16 TiB |         154 | LDN v3 multisig |
| [f1rkmhotssjif6ucrosls7oewjz6pr2v2eygfjyui](https://filfox.info/en/address/f1rkmhotssjif6ucrosls7oewjz6pr2v2eygfjyui)                                                                                                     | `Weipaitang`                                                                                                      |            22.97 TiB |         107 | LDN v3 multisig |
| [f1a2rdwwor3kq6mv7nveuxhux7rxtj6iyjs7hfswa](https://filfox.info/en/address/f1a2rdwwor3kq6mv7nveuxhux7rxtj6iyjs7hfswa)                                                                                                     | [Worldkan](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/902)                           |            22.66 TiB |         186 | LDN v3 multisig |
| [f1vykg3elgzoa3lpzf5xo6rbcghzr5ifat757mucq](https://filfox.info/en/address/f1vykg3elgzoa3lpzf5xo6rbcghzr5ifat757mucq)                                                                                                     | [Hailiang Mingyou Online](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/51)             |            21.06 TiB |         135 |        LDN # 51 |
| [f1xwmnlen7j7qlkktm3oqggzcbrxp6cvqnkd2wipa](https://filfox.info/en/address/f1xwmnlen7j7qlkktm3oqggzcbrxp6cvqnkd2wipa)                                                                                                     | ``                                                                                                                |             1.88 TiB |           3 |       LDN # 121 |
| [f3u3unadf654vezf62cd4jo6r7h6qpkx26g5amcdc<br/>3oe6rmpmk2nfosfd2kjkdhj4ndvr626gsm7fhpmt7<br/>gg2q](https://filfox.info/en/address/f3u3unadf654vezf62cd4jo6r7h6qpkx26g5amcdc3oe6rmpmk2nfosfd2kjkdhj4ndvr626gsm7fhpmt7gg2q) | [Runtu Information Technology](https://github.com/filecoin-project/filecoin-plus-client-onboarding/issues/1150)   |             1.81 TiB |          11 |       Steven Li |

[^1]: To manually trigger this report, add a comment with text `checker:manualTrigger`

**Comment by dkkapur** [comment]
@Pierofree can you explain why there are shared CIDs across different client applications?

**Comment by Pierofree** [comment]
@dkkapur This result is also what we don't want to see. The previous non-standard operation has led to bad results. We have replaced the person in charge of SP cooperation to ensure that this situation will not continue to occur or expand. Please give us a chance to correct.
