### ISSUE TITLE
[DataCap Application] simban

### ISSUE THREAD

**Issue by kunli** [filecoin-project/filecoin-plus-large-datasets#1115]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: simban
- Website / Social Media: https://simban.io/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 200TiB
- On-chain address for first allocation: f1rtngbskg6lfpijtao6yrgteg334tv3i34swbj4i

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Simban is a new travel-style metaverse with never-before-seen integrated digital twins of real-world and fictional planets. We are the first galaxy to offer °∞travel and earn°± opportunities. Players in our hyper-realistic metaverse encounter visually stunning earth locations as well as an open virtual galaxy filled with quests and mini-games.The company is located in New York.

One of our distinguishing features is that we work with digital twins of real-world locations and virtual mythical worlds, allowing us to incorporate IRL experiences that have never been attempted before.
```

What is the primary source of funding for this project?
```
Profits from products and bigd.exchange 
```

What other projects/ecosystem stakeholders is this project associated with?
```
No.
```

## Use-case details

Describe the data being stored onto Filecoin
```
3D Models.
```

Where was the data in this dataset sourced from?
```
Our business data.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://drive.google.com/drive/folders/1iliRDp3nz-lB0lviR2coap2qC2MImkRA
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
We Confirm.
```

What is the expected retrieval frequency for this data?
```
2 times/year.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
We hope save it will be five years.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Priority storage in East Asia.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
We plan to transfer these data offline.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We're selecting the SPs with high reputation on slack.
```

How will you be distributing deals across storage providers?
```
We plan to find more than 5 SPs and distribute the transactions equally.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
We know how to contact SP, and we don't need community help for the time being.
```

**Comment by raghavrmadya** [comment]
How exactly did you acquire this data? Also, please provide data samples in a format that can be widely looked at such as video recording of your 3d models. .skp files are not the most accessible

**Comment by kunli** [comment]
These are the data of projects we developed for our clients' projects. sure, we will convert that into a easy accessible formating. once we done, I will let you know.

**Comment by Sunnyiscoming** [comment]
@kunli Any update here?

**Comment by kunli** [comment]
Hi , @Sunnyiscoming , I updated the data sample.
See  https://drive.google.com/drive/folders/1AOhXRki7bTJWFplpmOZOs-zLyYqdY_NX?usp=sharing 
, please review.

**Comment by Sunnyiscoming** [comment]
The first folder is hard to check.
The next two folders are some jpg. files related with many hotels. It seems that these data samples are not related with your business. Can you explain about that?
The established time of website is just 71 days. The social media eatablished since August 2021. These phenomena are not enough to prove that you have 5 PB data already.
What's the relationship between you and the organization?
Can you provide more detailed information about other storage providers participated in this program, such as you can list SPs you have contacted with at present?

**Comment by kunli** [comment]
Three files are related to each other. Simban's bussiness model is to build a metaverse connect the vitual with reality, so we are presenting hotels, resorts etc into metaverse so that people can precheck the place before the booking. The first file is BIM models of those hotels and resorts, the second and third files are the hotels pictures which hotel owner presented to us, so that our 3D team can build the e-hotels in the simban metaverse. 

We are not just 71days old, simban is rebranded from parallell( double LL) because there are a lot of "parallel" out there, so we decided to rebranded to simban. You can check in sibman telegram group to verify this info.

I am the one taking care of the operational side in the sibman team. Because we are building 3D models of a lot of hotels and resorts, it require large amout of storage, that's why we are appling 5PB.

I am an employee of the company. I can verify my identity by sending an email to the official via the email under the corporate domain name.

I found some reputable miners (Chain up Cloud, SXX, F3, etc.) in Filecoin related communities to provide services for me, Their SPs  are as follows: f01228108, f01895783, f01915309, f01859603, f01929565.

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 200TiB

**Client address**

> f1rtngbskg6lfpijtao6yrgteg334tv3i34swbj4i

**Comment by newwebgroup** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceahbyc7c5x3ebzvjzsw7kshxqo72fh4f5bppvqw6mfnyd5kzklki2 
#### Address 
> f1rtngbskg6lfpijtao6yrgteg334tv3i34swbj4i
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1e77zuityhvvw6u2t6tb5qlnsegy2s67qs4lbbbq
#### Id
> 65b11c60-a751-4e20-8244-ae7c5b410ce4
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceahbyc7c5x3ebzvjzsw7kshxqo72fh4f5bppvqw6mfnyd5kzklki2

**Comment by newwebgroup** [comment]
Tip
Signing error. I accidentally signed 1115 when signing Fil-E 1155.
Please note that other notaries should make a complete KYC review before signing another signature.
Many Thanks.

CC @raghavrmadya

**Comment by Sunnyiscoming** [comment]
Hi @kunli 
If you still want to apply for datacap, you can ask more notaries to do client due diligence and approve the application in slack channel. https://app.slack.com/client/TEHTVS1L6/C036JKD8NVA/thread/C03BG1MNQ4T-1673888660.823499

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Looking at your application i have some questions:
As you are brand new on Github and have no history of past applications it seems to me that applying for 5PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?

Can you show us visible proof of the size of your data and the storage systems you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230337462961356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!

**Comment by igoovo** [comment]
Are you keepalive with this Issue#1115 ? @kunli

**Comment by lupiruw** [comment]
Are you ok?

**Comment by lupiruw** [comment]
keepalive

**Comment by lupiruw** [comment]
keepalive
