### ISSUE TITLE
[DataCap Application] Kuaixue Education - Dataset2（2/3）

### ISSUE THREAD

**Issue by Acc5com** [filecoin-project/filecoin-plus-large-datasets#1117]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Shenzhen kuaixue Education Development Co., Ltd
- Website / Social Media:https://www.acc5.com/ ； Slack：Alex-Acc5
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 400TiB
- On-chain address for first allocation: f1t3buz7oqz4fktpthqe43vauhzlnuztpgm3iyhbi

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Accounting school is an online training platform under Shenzhen kuaixue Education Software Technology Co., Ltd. Founded in 2014, it is committed to providing high-quality accounting practice, tax practice, CPA, intermediate accounting, primary accounting and other training for the majority of accounting practitioners. Since its establishment, kuaixue education has a team of excellent teachers with more than 500 people, and has developed practical courses covering 150 + industries and 10000 + class hours. It is a leading online accounting practical training institution in China. Located in Shenzhen Nanshan Science and Technology Park, it is a technology and product driven innovation education training institution with more than 3million online students.
```

What is the primary source of funding for this project?
```
From ourselves.
```

What other projects/ecosystem stakeholders is this project associated with?
```
Only related to ourselves.
```

## Use-case details

Describe the data being stored onto Filecoin
```
Part of the course video of our platform.
```

Where was the data in this dataset sourced from?
```
Courses data
Real account practice: real account practice in more than 150 industries such as industry, commerce and trade, hotel and catering, construction and real estate, software, finance, import and export, administrative units, public institutions, etc;
Introduction to zero Foundation: basic accounting, financial regulations, computerization, career planning, introduction to accounting, introduction to tax law, cashier, entry, voucher binding, office software
I want to learn cashier: introduction to theory and practical operation;
Manual true account: Bookkeeping vouchers, journals, sub ledgers, general ledger, account summary, and financial statements;
Tax practice: introduction to theory, replacing business tax with value-added tax, income tax, national tax and local tax declaration, tax accounting, tax planning, export tax rebate, Golden Tax phase III, invoice management, etc;
Financial management: financial analysis, financial management, bank loans, CFO;
Professional title examination: junior accountant, intermediate accountant, certified public accountant;
Financial software: Kingdee, UFIDA, Suda, Kuai Zhang, general ledger
Excel School: Excel foundation, function formula, pivot table, accounting application, financial modeling, practical operation explanation, VBA, chart, accounting E-form, etc;
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
Yes, we have a large number of open free training courses.
In the future, after filecoin plus enterprises can open applications, we will store more paid courses on filecoin.

https://www.acc5.com/course/course_13335/learn/lesson_74929/
https://www.acc5.com/course/course_13545/learn/lesson_77063/
https://www.acc5.com/course/course_12656/learn/lesson_66671/
https://www.acc5.com/course/course_11017/learn/lesson_43899/
https://www.acc5.com/practice/course/cat_0/list-0-3-1000-0/1.html
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes, there are no restrictions. Anyone who wants to learn accounting knowledge can search it.
```

What is the expected retrieval frequency for this data?
```
At present, it is only used as a backup until our private cloud data is lost.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
We hope it will last forever.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
we hope in China, Singapore, Vietnam, Australia

SP we have worked with
--
f01128206
f01859603
f01901765
f01901351
f01917009
f01915287
f01660795
f01923786
f01923787
f01885088
f01901379
f01870888
f01412203
f01909429
f01907545
f01922865

```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
These data are currently stored in our enterprise private cloud. Because the amount of data is very huge, we hope to transmit offline.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
Because we are not miners, we only know filecoin after being introduced by friends. When we learned about fil plus, we were very happy. We carefully read the storage rules of filecoin plus.
first ，We guarantee that the distribution of content will be as decentralized as possible. It will be stored in at least 8 storage service provider nodes.
The more decentralized the data storage is, the more secure it is for our data.
secondly,
We will ask the service provider that stores the data to provide the function of rapid retrieval, and will review the work after the storage is completed.

```

How will you be distributing deals across storage providers?
```
Choose Offline transmission as far as possible.
Our enterprise private cloud should support normal users. If it is used for online transmission, it will occupy too many resources.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, we have enough money. However, we still don't know how to cut the document into a unified format according to the regulations, and we will continue to learn.
```

**Comment by Acc5com** [comment]
After the first attempt, we have saved 1/3 of our open course datasets to the Filecoin network.
We felt the help from the community and the support of the notary, and we also got to know many SPs. Thanks for everyone's help
Next, we plan to store the remaining data sets in Filecoin.

https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/512

**Comment by raghavrmadya** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 400TiB

**Client address**

>f1t3buz7oqz4fktpthqe43vauhzlnuztpgm3iyhbi

**Comment by raghavrmadya** [comment]
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/512

https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1117

Client has previously exhibited good behavior with DC and earned reputation

**Comment by newwebgroup** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebcqje63vk6ravykirtkboikywpwf36hoqewatafeuie4f5stmqii 
#### Address 
> f1t3buz7oqz4fktpthqe43vauhzlnuztpgm3iyhbi
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1e77zuityhvvw6u2t6tb5qlnsegy2s67qs4lbbbq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebcqje63vk6ravykirtkboikywpwf36hoqewatafeuie4f5stmqii

**Comment by liyunzhi-666** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebfhmwcngwspggv73psb37scg6nia2dfnbkzxuizktdvzhf34d5hq 
#### Address 
> f1t3buz7oqz4fktpthqe43vauhzlnuztpgm3iyhbi
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1pszcrsciyixyuxxukkvtazcokexbn54amf7gvoq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebfhmwcngwspggv73psb37scg6nia2dfnbkzxuizktdvzhf34d5hq

**Comment by newwebgroup** [comment]
It seems that there are some bugs here. I plan to test and sign them.

**Comment by newwebgroup** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebpmtxx5hz46i7gdxpyzlfeuywe5uoyffuc4h6cl676ccyjelcuo4 
#### Address 
> f1t3buz7oqz4fktpthqe43vauhzlnuztpgm3iyhbi
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1e77zuityhvvw6u2t6tb5qlnsegy2s67qs4lbbbq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebpmtxx5hz46i7gdxpyzlfeuywe5uoyffuc4h6cl676ccyjelcuo4

**Comment by newwebgroup** [comment]
**Sign**
This LDN application can also be signed when it is displayed on the Filplus console without Bot boot. I tried to sign it and succeeded.
Need someone to check and repair.  @fabriziogianni7

**Comment by Tom-OriginStorage** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceda4cyzhznysm4772hxxrzdnuxdoafph4a32ak7rqzwpchrml5z7s 
#### Address 
> f1t3buz7oqz4fktpthqe43vauhzlnuztpgm3iyhbi
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1q6bpjlqia6iemqbrdaxr2uehrhpvoju3qh4lpga
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceda4cyzhznysm4772hxxrzdnuxdoafph4a32ak7rqzwpchrml5z7s

**Comment by ipfscn** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecoosjrtsvcb6f7jfihjdxj5wkhitaanf43zymbrv54jyyoljc4uw 
#### Address 
> f1t3buz7oqz4fktpthqe43vauhzlnuztpgm3iyhbi
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1j4n74chme7whbz3yls4a7ixqewb6dijypqg2a3a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecoosjrtsvcb6f7jfihjdxj5wkhitaanf43zymbrv54jyyoljc4uw

**Comment by xiaoyuaiheshui** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceag6cofspkunp7omi5kdlzlg4pjdo3g5gg7p4xrk3zkr22rxjx4sk 
#### Address 
> f1t3buz7oqz4fktpthqe43vauhzlnuztpgm3iyhbi
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f122qmy25wdtt5mxd77kndiq7z5x2n3iwiuz2wdsa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceag6cofspkunp7omi5kdlzlg4pjdo3g5gg7p4xrk3zkr22rxjx4sk

**Comment by kernelogic** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecl5vefwxd4a4kl57yqaj7jbaecm2bxfdcj436u6es5bfeii64mro 
#### Address 
> f1t3buz7oqz4fktpthqe43vauhzlnuztpgm3iyhbi
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecl5vefwxd4a4kl57yqaj7jbaecm2bxfdcj436u6es5bfeii64mro

**Comment by stcouldlisa** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebqiabi3q72in3hsnm7hze3pezbtv6pul44wcinolu4nhk76mmyny 
#### Address 
> f1t3buz7oqz4fktpthqe43vauhzlnuztpgm3iyhbi
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1jvvltduw35u6inn5tr4nfualyd42bh3vjtylgci
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebqiabi3q72in3hsnm7hze3pezbtv6pul44wcinolu4nhk76mmyny

**Comment by Tom-OriginStorage** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb4cbkzyiofxboetixvdsyl4z5yx42y2pbvjysma3whm3mzf2rkh6 
#### Address 
> f1t3buz7oqz4fktpthqe43vauhzlnuztpgm3iyhbi
#### Datacap Allocated
> 1.56PiB
#### Signer Address
> f1q6bpjlqia6iemqbrdaxr2uehrhpvoju3qh4lpga
#### Id
> ce8d48b1-936a-4a3b-bc93-68b74bdbc932
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb4cbkzyiofxboetixvdsyl4z5yx42y2pbvjysma3whm3mzf2rkh6

**Comment by liyunzhi-666** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedjbgrc534vutr5l5qxln6kun7d2oym6cp5xibipl7lnotfc5k3jq 
#### Address 
> f1t3buz7oqz4fktpthqe43vauhzlnuztpgm3iyhbi
#### Datacap Allocated
> 1.56PiB
#### Signer Address
> f1pszcrsciyixyuxxukkvtazcokexbn54amf7gvoq
#### Id
> ce8d48b1-936a-4a3b-bc93-68b74bdbc932
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedjbgrc534vutr5l5qxln6kun7d2oym6cp5xibipl7lnotfc5k3jq

**Comment by Joss-Hua** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebpsfksnjf5qydemuqra5uces63foxkwrpzs3k56wyj5egqv3bdss 
#### Address 
> f1t3buz7oqz4fktpthqe43vauhzlnuztpgm3iyhbi
#### Datacap Allocated
> 1.56PiB
#### Signer Address
> f1tfg54zzscugttejv336vivknmsnzzmyudp3t7wi
#### Id
> ce8d48b1-936a-4a3b-bc93-68b74bdbc932
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebpsfksnjf5qydemuqra5uces63foxkwrpzs3k56wyj5egqv3bdss

**Comment by newwebgroup** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebfqehfxankw6ntxnfw7p3dkczijqqpzac7ukacchqembxk36aqcs 
#### Address 
> f1t3buz7oqz4fktpthqe43vauhzlnuztpgm3iyhbi
#### Datacap Allocated
> 1.56PiB
#### Signer Address
> f1e77zuityhvvw6u2t6tb5qlnsegy2s67qs4lbbbq
#### Id
> 380ef825-5eff-4f86-8324-228e2021387a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebfqehfxankw6ntxnfw7p3dkczijqqpzac7ukacchqembxk36aqcs

**Comment by filplus-checker** [comment]
## DataCap and CID Checker Report[^1]
 - Organization: `Shenzhen kuaixue Education Development Co., Ltd`
 - Client: `f1t3buz7oqz4fktpthqe43vauhzlnuztpgm3iyhbi`
### Storage Provider Distribution
The below table shows the distribution of storage providers that have stored data for this client.

If this is the first time a provider takes verified deal, it will be marked as `new`.

For most of the datacap application, below restrictions should apply.
 - Storage provider should not exceed 25% of total datacap.
 - Storage provider should not be storing duplicate data for more than 20%.
 - Storage provider should have published its public IP address.
 - All storage providers should be located in different regions.

⚠️ 66.60% of total deal sealed by [f01922893](https://filfox.info/en/address/f01922893) are duplicate data.

⚠️ 73.78% of total deal sealed by [f01922865](https://filfox.info/en/address/f01922865) are duplicate data.

⚠️ 72.99% of total deal sealed by [f01915287](https://filfox.info/en/address/f01915287) are duplicate data.

⚠️ 79.64% of total deal sealed by [f01901773](https://filfox.info/en/address/f01901773) are duplicate data.

⚠️ 68.68% of total deal sealed by [f01945688](https://filfox.info/en/address/f01945688) are duplicate data.

⚠️ 79.47% of total deal sealed by [f01970674](https://filfox.info/en/address/f01970674) are duplicate data.

⚠️ 37.24% of total deal sealed by [f01972356](https://filfox.info/en/address/f01972356) are duplicate data.

⚠️ 32.45% of total deal sealed by [f01955186](https://filfox.info/en/address/f01955186) are duplicate data.

⚠️ 64.16% of total deal sealed by [f01949183](https://filfox.info/en/address/f01949183) are duplicate data.

⚠️ 75.74% of total deal sealed by [f01970213](https://filfox.info/en/address/f01970213) are duplicate data.

⚠️ 49.33% of total deal sealed by [f01929568](https://filfox.info/en/address/f01929568) are duplicate data.

⚠️ 78.23% of total deal sealed by [f01967672](https://filfox.info/en/address/f01967672) are duplicate data.

⚠️ 20.82% of total deal sealed by [f01901351](https://filfox.info/en/address/f01901351) are duplicate data.

| Provider                                                    |                           Location | Total Deals Sealed | Percentage | Unique Data | Duplicate Deals |
| :---------------------------------------------------------- | ---------------------------------: | -----------------: | ---------: | ----------: | --------------: |
| [f01922893](https://filfox.info/en/address/f01922893)`new`  |                   Hanoi, Hanoi, VN |         860.88 TiB |     16.64% |  287.53 TiB |          66.60% |
| [f01922865](https://filfox.info/en/address/f01922865)       |  Ho Chi Minh City, Ho Chi Minh, VN |         806.28 TiB |     15.59% |  211.38 TiB |          73.78% |
| [f01915287](https://filfox.info/en/address/f01915287)       |                   Hanoi, Hanoi, VN |         788.25 TiB |     15.24% |  212.88 TiB |          72.99% |
| [f01901773](https://filfox.info/en/address/f01901773)       | Hong Kong, Central and Western, HK |         759.00 TiB |     14.67% |  154.50 TiB |          79.64% |
| [f01945688](https://filfox.info/en/address/f01945688)`new`  |                  Wuxi, Jiangsu, CN |         495.69 TiB |      9.58% |  155.25 TiB |          68.68% |
| [f01970674](https://filfox.info/en/address/f01970674)       |        Sydney, New South Wales, AU |         260.91 TiB |      5.04% |   53.56 TiB |          79.47% |
| [f01972356](https://filfox.info/en/address/f01972356)       |           Maywood Park, Oregon, US |         246.69 TiB |      4.77% |  154.81 TiB |          37.24% |
| [f01955186](https://filfox.info/en/address/f01955186)       | Hong Kong, Central and Western, HK |         229.09 TiB |      4.43% |  154.75 TiB |          32.45% |
| [f01949183](https://filfox.info/en/address/f01949183)       |           Maywood Park, Oregon, US |         174.38 TiB |      3.37% |   62.50 TiB |          64.16% |
| [f01970213](https://filfox.info/en/address/f01970213)       | Hong Kong, Central and Western, HK |         128.81 TiB |      2.49% |   31.25 TiB |          75.74% |
| [f01929568](https://filfox.info/en/address/f01929568)       |           Stockholm, Stockholm, SE |         123.16 TiB |      2.38% |   62.41 TiB |          49.33% |
| [f01870888](https://filfox.info/en/address/f01870888)       |               Chengdu, Sichuan, CN |          94.38 TiB |      1.82% |   81.88 TiB |          13.25% |
| [f01954294](https://filfox.info/en/address/f01954294)`new`  |            Shenzhen, Guangdong, CN |          79.75 TiB |      1.54% |   79.75 TiB |           0.00% |
| [f01967672](https://filfox.info/en/address/f01967672)       | Hong Kong, Central and Western, HK |          71.78 TiB |      1.39% |   15.63 TiB |          78.23% |
| [f01940076](https://filfox.info/en/address/f01940076)       | Hong Kong, Central and Western, HK |          34.97 TiB |      0.68% |   34.97 TiB |           0.00% |
| [f01901351](https://filfox.info/en/address/f01901351)       |               Chengdu, Sichuan, CN |          18.31 TiB |      0.35% |   14.50 TiB |          20.82% |

![Provider Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/1117/1671098663145.png)
### Deal Data Replication
The below table shows how each many unique data are replicated across storage providers.
- No more than 25% of unique data are stored with less than 4 providers.

⚠️ 48.45% of deals are for data replicated across less than 4 storage providers.

| Unique Data Size | Total Deals Made | Number of Providers | Deal Percentage |
| ---------------: | ---------------: | ------------------: | --------------: |
|       733.94 TiB |         1.80 PiB |                   1 |          35.60% |
|       133.50 TiB |       659.44 TiB |                   2 |          12.75% |
|       448.00 GiB |         5.09 TiB |                   3 |           0.10% |
|        35.31 TiB |       569.25 TiB |                   4 |          11.01% |
|        93.34 TiB |         1.55 PiB |                   5 |          30.72% |
|        26.22 TiB |       508.22 TiB |                   6 |           9.83% |

![Replication Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/1117/1671098663858.png)
### Deal Data Shared with other Clients
The below table shows how many unique data are shared with other clients.
Usually different applications owns different data and should not resolve to the same CID.

⚠️ CID sharing has been observed.

| Other Client                                                                                                                                                                                                              | Application                                                                                                                        | Total Deals Affected | Unique CIDs |          Verifier |
| :------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ | :--------------------------------------------------------------------------------------------------------------------------------- | -------------------: | ----------: | ----------------: |
| [f16ioghg3qy36f6572viouwv4dqow5ejpolo4kodi](https://filfox.info/en/address/f16ioghg3qy36f6572viouwv4dqow5ejpolo4kodi)                                                                                                     | [Shenzhen kuaixue Education Development Co\., Ltd](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/512)    |             5.06 PiB |      12,627 |   LDN v3 multisig |
| [f1tb2hrxk5eaeewcesnid6xmvfkklfdrxsjr5k6iy](https://filfox.info/en/address/f1tb2hrxk5eaeewcesnid6xmvfkklfdrxsjr5k6iy)                                                                                                     | [Yisainuo](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/537)                                            |           603.31 TiB |       6,770 |   LDN v3 multisig |
| [f1unz5yuxgui573lpuh2wyxpsx5ahvw5farqb7hji](https://filfox.info/en/address/f1unz5yuxgui573lpuh2wyxpsx5ahvw5farqb7hji)                                                                                                     | `AOLIGEI`                                                                                                                          |           300.22 TiB |       6,870 |   LDN v3 multisig |
| [f1axtj4vjlsf5buf2qcn4kkqrpdcgrqk4exxxsury](https://filfox.info/en/address/f1axtj4vjlsf5buf2qcn4kkqrpdcgrqk4exxxsury)                                                                                                     | [CIIC Education Technology \(Shenzhen\) Co\., Ltd\.](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1207) |           148.53 TiB |         470 |   LDN v3 multisig |
| [f3qebbkqspq4w6deouaubtngt4bmaada76uqs3omy<br/>3tki6hoeocpgxyplknev5u3oi5e7xnltobrvgxnpa<br/>3qga](https://filfox.info/en/address/f3qebbkqspq4w6deouaubtngt4bmaada76uqs3omy3tki6hoeocpgxyplknev5u3oi5e7xnltobrvgxnpa3qga) | [codex8080 \- Slingshot Restore](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/152)                      |            50.47 TiB |       1,615 |   LDN v3 multisig |
| [f126k3tkdwfaqpflgcclkiwhqxhh73ebqqazwgcoy](https://filfox.info/en/address/f126k3tkdwfaqpflgcclkiwhqxhh73ebqqazwgcoy)                                                                                                     | [New Web Group](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/356)                                       |            29.53 TiB |         943 |   LDN v3 multisig |
| [f3v7x4a2aapgx6o2r477tenoin3u5oadaeqyd7kjd<br/>sitykvf4ok7vq2utcyh34lmu5u7oybs25ff6s4dbu<br/>dpma](https://filfox.info/en/address/f3v7x4a2aapgx6o2r477tenoin3u5oadaeqyd7kjdsitykvf4ok7vq2utcyh34lmu5u7oybs25ff6s4dbudpma) | [LeoCheung \- Slingshot Restore](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/151)                      |            22.97 TiB |         735 |   LDN v3 multisig |
| [f1m6bvbcawgrxcvyk2tzayt5mplgqs255swwnw6dq](https://filfox.info/en/address/f1m6bvbcawgrxcvyk2tzayt5mplgqs255swwnw6dq)                                                                                                     | [Shanghai Tangzhi Technology Development Co\., Ltd\.](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/826) |            14.97 TiB |         468 |   LDN v3 multisig |
| [f1x7wsqpj6waymzzfqmu4hh32tyc4pbbqnpwy2ucq](https://filfox.info/en/address/f1x7wsqpj6waymzzfqmu4hh32tyc4pbbqnpwy2ucq)                                                                                                     | `Glif auto verified`                                                                                                               |            32.00 GiB |           1 | Jonathan Schwartz |
| [f15m6qoqdsh7fn7l5amegshhvwi4gl5alb2eeuz2y](https://filfox.info/en/address/f15m6qoqdsh7fn7l5amegshhvwi4gl5alb2eeuz2y)                                                                                                     | [Worldkan](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/902)                                            |            32.00 GiB |           1 |   LDN v3 multisig |

[^1]: To manually trigger this report, add a comment with text `checker:manualTrigger`

**Comment by herrehesse** [comment]
Dear Applicant,

Due to the increased amount of erroneous/wrong Filecoin+ data recently, on behalf of the entire community, we feel compelled to go deeper into datacap requests. Hereby to ensure that the overall value of the Filecoin network and Filecoin+ program increases and is not abused.

Please answer the questions below as comprehensively as possible.

**Customer data**

- Could you demonstrate exactly how and to what extent customer contact occurred? 

We expect that for the onboarding of customers with the scale of an LDN there would have been at least multiple email and perhaps several chat conversations preceding it. A single email with an agreement does not qualify here.

- Did the customer specify the amount of data involved in this relevant correspondence?

- Why does the customer in question want to use the Filecoin+ program? 

_Should this only be soley for acquiring datacap this is of course **out of the question**. The customer must have a legitimate reason for wanting to use the Filecoin+ program which is intended as a program to store useful and public datasets on the network._ 

- Why is the customer data considered Filecoin+ eligible?

_(As an intermediate solution Filecoin offers the FIL-E program or the glif.io website for business datasets that do not meet the requirements for a Filecoin+ dataset)_


**Files and Processing**

- Could you please demonstrate to us how you envision processing and transporting the customer data in question to any location for preparation?
- Would you demonstrate to us that the customer, the preparer and the intended storage providers all have adequate bandwidth to process the set with its corresponding size?
- Would you tell us how the data set preparer takes into account the prevention of duplicates in order to prevent data cap abuse?


Hopefully you understand the caution the overall community has for onboarding the wrong data. We understand the increased need for Filecoin+, however, we must not allow the program to be misused. Everything depends on a valuable and useful network, let's do our best to make this happen. Together.

**Comment by herrehesse** [comment]
@Acc5com Can you clarify why you have thousands of TiB's duplicate files across ALL miners?

⚠️ 66.60% of total deal sealed by [f01922893](https://filfox.info/en/address/f01922893) are duplicate data.
⚠️ 73.78% of total deal sealed by [f01922865](https://filfox.info/en/address/f01922865) are duplicate data.
⚠️ 72.99% of total deal sealed by [f01915287](https://filfox.info/en/address/f01915287) are duplicate data.
⚠️ 79.64% of total deal sealed by [f01901773](https://filfox.info/en/address/f01901773) are duplicate data.
⚠️ 68.68% of total deal sealed by [f01945688](https://filfox.info/en/address/f01945688) are duplicate data.
⚠️ 79.47% of total deal sealed by [f01970674](https://filfox.info/en/address/f01970674) are duplicate data.
⚠️ 37.24% of total deal sealed by [f01972356](https://filfox.info/en/address/f01972356) are duplicate data.
⚠️ 32.45% of total deal sealed by [f01955186](https://filfox.info/en/address/f01955186) are duplicate data.
⚠️ 64.16% of total deal sealed by [f01949183](https://filfox.info/en/address/f01949183) are duplicate data.
⚠️ 75.74% of total deal sealed by [f01970213](https://filfox.info/en/address/f01970213) are duplicate data.
⚠️ 49.33% of total deal sealed by [f01929568](https://filfox.info/en/address/f01929568) are duplicate data.
⚠️ 78.23% of total deal sealed by [f01967672](https://filfox.info/en/address/f01967672) are duplicate data.
⚠️ 20.82% of total deal sealed by [f01901351](https://filfox.info/en/address/f01901351) are duplicate data.

This is clearly against the rules, duplicates can happen but this is so excessive its abuse of granted datacap.
@newwebgroup @Joss-Hua Can you explain why you signed this?
