### ISSUE TITLE
[DataCap Application] <Beijing Xunhuitong Technology Co., Ltd.>

### ISSUE THREAD

**Issue by xunhuitong** [filecoin-project/filecoin-plus-large-datasets#1118]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Beijing Xunhuitong Technology Co., Ltd.
- Website / Social Media:http://www.swifton.net/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):200TiB
- On-chain address for first allocation:f1kz4ae7m3ohiu5nvyp4vwqwes7xycifmpmkoqyvy

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Beijing Xunhuitong Technology Co., Ltd. was established in Beijing, China in 2002. At the beginning of its establishment, it was an emerging value-added telecom service provider committed to telecom virtual operation, telecom value-added services and the development of telecom network equipment. It was one of the first batch of IP phone operators and Internet service providers approved by the Beijing Communications Administration. It has an independent access number of 96551 and an ISP business license, Various forms of long-distance telephone services and Internet access services are carried out in Beijing. After years of development, the company has developed from a telecommunications service provider to a comprehensive service provider providing various value-added services to domestic large financial group customers, and will further rely on channel and resource advantages in the future to form its core competitiveness in the photovoltaic industry, telecommunications value-added services, IDC operations and other aspects.
The company officially entered the photovoltaic industry in 2015, mainly selling Huawei photovoltaic inverter SUN2000 series as an agent, and customers gave us great support in business. Now the company has many partners in supply and sales, and has established strategic partnership with many enterprises in the high-tech field, laying a solid foundation for the continuous development of the enterprise. Adhering to the business purpose of "growing with customers and employees to create a first-class enterprise", the company will continue to carry forward the core values of "customer first, service oriented, pursuit of excellence, and sincere cooperation" to create greater value for customers.
```

What is the primary source of funding for this project?
```
Revenue of the company.
```

What other projects/ecosystem stakeholders is this project associated with?
```
No.
```

## Use-case details

Describe the data being stored onto Filecoin
```
Our courseware video production business.
```

Where was the data in this dataset sourced from?
```
The data comes from videos recorded by our internal team and videos recorded by the merchants we cooperate with.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://drive.google.com/drive/folders/1oSB_lDM8CWh7ympgHazwnTpzwN6D9BQU?usp=sharing
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes.
```

What is the expected retrieval frequency for this data?
```
5-8 times a year.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
At least 2 years.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
China or Asia, because I need a quick visit.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Offline transfer.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We will choose a node provider that is stable and the network can support our fast access.
```

How will you be distributing deals across storage providers?
```
Average distribution.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
We have prepared all the necessary funds.
```

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 200TiB

**Client address**

>f1kz4ae7m3ohiu5nvyp4vwqwes7xycifmpmkoqyvy

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Looking at your application i have some questions:
As you are brand new on Github and have no history of past applications it seems to me that applying for 5PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?

Can you show us visible proof of the size of your data and the storage systems you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230232885049356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!

**Comment by Sunnyiscoming** [comment]
Hi @xunhuitong 
If you still want to apply for datacap, you can ask more notaries to do client due diligence and approve the application in slack channel. https://app.slack.com/client/TEHTVS1L6/C036JKD8NVA/thread/C03BG1MNQ4T-1673888660.823499
