### ISSUE TITLE
[DataCap Application] <Meson Network>

### ISSUE THREAD

**Issue by bitruss** [filecoin-project/filecoin-plus-large-datasets#1119]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information

- Organization Name: Meson Network
- Website / Social Media: [https://meson.network/](https://meson.network/)
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100TiB
- On-chain address for first allocation: f16nefjn7qhchsgir6tnkvkzqr46atyu3p6ijyufq

*Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer.*

## Project details

Share a brief history of your project and organization.

```
Meson Network is committed to creating an efficient bandwidth marketplace on Web3, using a blockchain protocol model to replace the traditional labor-based sales models, consolidating and monetizing idle bandwidth from long-tail users at a low cost. Meson Network is the foundation of data transmission for decentralized storage, computation, and the emerging Web3 Dapp ecosystem.
```

What is the primary source of funding for this project?

```
Meson Network
```

What other projects/ecosystem stakeholders is this project associated with?

```
Meson Ecosystem: https://meson.network/ecosystem.html
```

## Use-case details

Describe the data being stored onto Filecoin

```
Mainly video, pictures and other data.
```

Where was the data in this dataset sourced from?

```
Mainly from our strategic parters.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this.

```
https://pz-rlhgrj.meson.network/ipfs/QmXoypizjW3WknFiJnKLwHCnL72vedxjQkDDP1mXWo6uco/wiki/
```

Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).

```
Yes. This is a public dataset.
```

What is the expected retrieval frequency for this data?

```
It depends on the actual needs
```

For how long do you plan to keep this dataset stored on Filecoin?

```
permanent
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?

```
All regions.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?

```
Offline data transfer over the internet, using standard HTTP or purose-made protocol like Tachyon.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.

```
Well, we want to choose a miner with good size and credit in filecon's ecosystem.
```

How will you be distributing deals across storage providers?

```
We would divide the data up and send it to different miners.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?

```
Yes，we have enough funding and resources to start making deals.
```

## Additional Information

- `martin@meson.network`
- [https://t.me/Martinicrypto](https://t.me/Martinicrypto)

**Comment by raghavrmadya** [comment]
You have previously applied, correct? Please link the previous application

**Comment by bitruss** [comment]
Due to a misunderstanding in communication, our brand was used to apply for this program. Since we find out this fake application, we contacted Deep Kapur, who helped us delete the original link and instructed us to reapply. We have working chat logs in slack and mailboxes. Thanks @raghavrmadya

**Comment by dkkapur** [comment]
@raghavrmadya confirming that the previous application was identified as incorrect, and this is the person in touch with PL/FF teams to drive onboarding from meson's side. 

@simonkim0515 can we get this one unblocked?

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 100TiB

**Client address**

>f16nefjn7qhchsgir6tnkvkzqr46atyu3p6ijyufq

**Comment by UnionLabs2020** [comment]
Could you give more evidence to prove that this dataset is generated by your system? 

https://pz-rlhgrj.meson.network/ipfs/QmXoypizjW3WknFiJnKLwHCnL72vedxjQkDDP1mXWo6uco/wiki/

**Comment by psh0691** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecfr4d5fkce5t3a4avsd7pslxh3c7xa4zmqdjdsoijvclt2p6qsa6 
#### Address 
> f16nefjn7qhchsgir6tnkvkzqr46atyu3p6ijyufq
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1qdko4jg25vo35qmyvcrw4ak4fmuu3f5rif2kc7i
#### Id
> ed79233e-549e-4299-b8cc-a54bed9d2258
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecfr4d5fkce5t3a4avsd7pslxh3c7xa4zmqdjdsoijvclt2p6qsa6

**Comment by Defil2022** [comment]
For the previous incorrect application, they got the dc?

**Comment by UnionLabs2020** [comment]
Up to now, no effective reply has been received. Propose to close the application.

**Comment by dkkapur** [comment]
@Defil2022 see - https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1119#issuecomment-1314172662

@bitruss can you please respond to @UnionLabs2020 's comment above: https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1119#issuecomment-1315253263

**Comment by bitruss** [comment]
> Could you give more evidence to prove that this dataset is generated by your system?
> 
> https://pz-rlhgrj.meson.network/ipfs/QmXoypizjW3WknFiJnKLwHCnL72vedxjQkDDP1mXWo6uco/wiki/

@UnionLabs2020 

Meson Network is committed to optimizing the speed at which the Filecoin/IPFS public gateway distributes reads. At present, the mainstream public gateways of Filecoin/IPFS are [ipfs.io](http://ipfs.io/), [cloudflare-ipfs.com](http://cloudflare-ipfs.com/), and [dweb.link](https://dweb.link/).

[ipfs.io](http://ipfs.io/) is the most frequently used gateway and the only node that can access files over 500MB, but its operating efficiency in global acceleration is not dominant. [cloudflare-ipfs.com](http://cloudflare-ipfs.com/) is relatively fast, but cannot speed up large files. dweb.link is currently the recommended gateway, but it has the same problem with [ipfs.io](http://ipfs.io/) that it is not as fast as one might expect. In view of this, Meson Network is committed to providing Filecoin/IPFS users with a secure, efficient, and usable decentralized gateway option with the help of decentralized nodes distributed around the world.

At the same time, Meson has many application partners on Web3, such as Mask Network, Rss3, Matters, OKX Chain, Cyberconnect, etc. We also provide some partners with one-click storage and distribution services on Filecoin/IPFS. The data we upload all comes from our partners.

- [Meson enhances IPFS](https://docs.meson.network/using/#example-meson-enhances-ipfs)
- [Open Grant Proposal: Meson Network #839](https://github.com/filecoin-project/devgrants/issues/839)
- [Meson Ecosystem](https://meson.network/ecosystem.html)

**Comment by Irmagogo** [comment]
Hey @bitruss 
Do you have a slack account? My slack handle is @Irma
I would like to know more about Menson Network. If you have slack, Please DM me, thank you.

**Comment by bitruss** [comment]
> Hey @bitruss Do you have a slack account? My slack handle is @irma I would like to know more about Menson Network. If you have slack, Please DM me, thank you.

@Irmagogo My college has contact you.

**Comment by psh0691** [comment]
@dkkapur 
I thought it was sufficiently verified in the previous meson LDN application (#187) and signed it at that time.
![스크린샷, 2022-12-10 00-50-03](https://user-images.githubusercontent.com/69004801/206835054-3908b81c-e2d0-42bb-9f41-2160a5a2466e.png)

In addition, the DC allocation of the previous application did not proceed until the end, so I signed for the application again.

**Comment by Chris00618** [comment]
LDN application is not suitable for such tool applications, because meson really cannot prove the ownership of these datasets.

**Comment by haihongS** [comment]
Thanks for the efforts from the PL teams and the reviewers. I am Sherlock from Meson Network, and I want to clarify here to ensure users know more details about us.

The first part is about how Meson Network works. We offer the incentive layer in the retrieval part, which means people who provide the bandwidth resources can get our token as a reward, and we can use this kind of service to be the module for the storage layer. The affection is to decouple the two layers (Storage & Retrieval). Each can focus on its own incentivizing mechanism and form different kinds of nodes (Storage needs disk capacity, Retrieval needs bandwidth).

The second part is for the Datacap application. We are delivering features that users can use Meson to upload the files into the storage layer (e.g., ipfs, FIL). The significant thing is that the [real valuable data comes from the demand side.](https://retrievalmarketssummit.super.site/) If users have a demand for the data and retrieve it frequently, it can be helpful to store them in crypto storage rather than just storing the data and claiming it's valuable. So that's why the data uploaded from Meson is beneficial for the adoption of FIL. And it also answers the questions mentioned in this issue. 

Hope we can make some efforts for the adoption.

**Comment by tbros6868** [comment]
really like your project and we would like to participate in its development.

**Comment by njts** [comment]
As a web developer, I've tested the Meson 3.0 CDN and can confirm that it works flawlessly. In my opinion, Meson Network is critical for Web 3.0 and true decentralization.

**Comment by tbros6868** [comment]
> really like your project and we would like to participate in its development.

really like your project and we would like to participate in its development.

**Comment by dinhnguyen2001** [comment]
Meson and other decentralized storages will make internet great again

**Comment by Protocan** [comment]
If the real data comes from the demand side, they should submit this application instead of Meson.  We need to review the data owner and  the real dataset here.

**Comment by haihongS** [comment]
> If the real data comes from the demand side, they should submit this application instead of Meson. We need to review the data owner and the real dataset here.

Each end-user apply a license for the Datacap (100k issues in github) or the service providers apply the license from PL and incentivise the end users (less than 100 issues). I prefer the latter one.

**Comment by cryptowhizzard** [comment]
Can someone explain what happened here?

https://github.com/filecoin-project/filecoin-plus-large-datasets/issues?q=is%3Aissue+meson

**Comment by kernelogic** [comment]
@cryptowhizzard reading through the comment log above, it seems all the previous Mason.Network LDNs involving the CID sharing were from imposters.

**Comment by bitruss** [comment]
@cryptowhizzard 

[jacintohessell@gmail.com](mailto:jacintohessell@gmail.com) submitted a Data Cap application by impersonating a member of the Meson Network team. Afterward, Meson Network reported to the Filecoin official that it was fake, and the relevant fake application (https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/187) has been sentenced.

**Comment by kernelogic** [comment]
Given the affirmation from @dkkapur above, willing to support the first round.

**Comment by kernelogic** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedvhf5s2oopgwxqkknclc5ylwxjfxpt7tn5lgmnfznvypvnwguh4m 
#### Address 
> f16nefjn7qhchsgir6tnkvkzqr46atyu3p6ijyufq
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedvhf5s2oopgwxqkknclc5ylwxjfxpt7tn5lgmnfznvypvnwguh4m

**Comment by cryptowhizzard** [comment]
checker:manualTrigger
