### ISSUE TITLE
[DataCap Application] <Hangzhou Jiama Xingle Technology Co., Ltd> - <Jiama Chat>

### ISSUE THREAD

**Issue by justmineooz** [filecoin-project/filecoin-plus-large-datasets#1120]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Jiama Xingle
- Website / Social Media: https://jiama.online
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 200TiB
- On-chain address for first allocation: f144enqwirwpkuejtualnufhzlnsehbe5qcdvkp5a

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Hangzhou Jiama Xingle Technology Co., Ltd. was born in Hangzhou, China in 2018. It is a travel scene service provider that connects all vehicles through voice social networking, provides communication methods suitable for driving scenarios, and integrates vehicle services during travel.

At present, Jiama Xingle has developed a social networking product for driving travel - Jiama Chat, it is like a "WeChat" in the car. Although it is an instant messaging tool, the usage scenarios of WeChat are mostly operated on mobile phones, and it is a kind of acquaintance socializing. But Jiama Chat is not based on the address book, and its operating scene is more focused on the driving environment.

Jiama Chat dynamically gathers users into different channels through location and driving status, and can perceive, communicate and share data with each other. For example, after driving to the same expressway, Jiama Yuchat will automatically match the same trunk driver and enter a new channel; in case of emergencies, a new channel can be automatically generated.

In terms of communication methods, Jiama Chat can speak with a touch of the screen, and adopts a conversational mode, and the received voice information can be automatically played. The "blind operation" mode is adopted to reduce the time and energy of the driver and user to focus on the screen.

Since the launch of Jiama Chat in May 2018, it has accumulated 30+ enterprise customers through self-operated and cooperative models, like FAW Jiefang and other automakers.

At present, Jiama Chat has accumulated more than 15PB images and videos, including data of specific scenarios like trucks, taxis, and online car-hailing vehicles, such as road driving records, illegal driving, lane deviation, etc.
```

What is the primary source of funding for this project?
```
Own funds and operating income.
```

What other projects/ecosystem stakeholders is this project associated with?
```
No
```

## Use-case details

Describe the data being stored onto Filecoin
```
The data stored on Filecoin is images and videos.
```

Where was the data in this dataset sourced from?
```
From Jiama Chat APP.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://drive.google.com/drive/folders/1FEvSYxXqF7qQw9-SICz-3R7cdDZXkRd9?usp=sharing
```

Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes
```

What is the expected retrieval frequency for this data?
```
About 3 times every 540 days.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
Store for at least 540 days.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
North America and Asia.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
We will distribute offline to storage providers.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We will check their overall capacity and working hours, we need a storage provider that we can work with for a long time.
```

How will you be distributing deals across storage providers?
```
We will allocate DataCap according to miner's preference, such as online transfer and offline transfer.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes，we have enough funding and resources to start making deals.
```

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 200TiB

**Client address**

> f144enqwirwpkuejtualnufhzlnsehbe5qcdvkp5a

**Comment by justmineooz** [comment]
Hi, @psh0691, sorry for the late reply.
1. The total size of the data we currently have is 15895.82TB.
<img width="1430" alt="image" src="https://user-images.githubusercontent.com/27658706/206883958-8ed266ee-2747-4189-8a09-bcc6f8ee2307.png">

2. We use Alibaba cloud OSS service keep all these data sine 2019. Maybe it is impossible to save all these data offline, as the very very expensive traffic cost. However, we have downloaded some important of all these data(about 30%) offline to local HDFS by using Alibaba cloud Datatransport service.

3. The chat data in out program is not publicly. The data we will send SPs to save are videos, pictures and tracking data collected using our Jiama Chat APP.

**Comment by psh0691** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebzmj6a5ivaxgpcpts72nuhk5yg2pk7h3se7h3p4wy7efgr3ydru4 
#### Address 
> f144enqwirwpkuejtualnufhzlnsehbe5qcdvkp5a
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1qdko4jg25vo35qmyvcrw4ak4fmuu3f5rif2kc7i
#### Id
> 687ee2e8-36af-478f-8beb-3501df568bad
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebzmj6a5ivaxgpcpts72nuhk5yg2pk7h3se7h3p4wy7efgr3ydru4

**Comment by Joss-Hua** [comment]
After preliminary check, support the first round of request.

**Comment by Joss-Hua** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebhcdmhvdmfzz4cllitaygjyhdyqnj5q52gxa4uzwku4johmd6ul4 
#### Address 
> f144enqwirwpkuejtualnufhzlnsehbe5qcdvkp5a
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1tfg54zzscugttejv336vivknmsnzzmyudp3t7wi
#### Id
> 687ee2e8-36af-478f-8beb-3501df568bad
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebhcdmhvdmfzz4cllitaygjyhdyqnj5q52gxa4uzwku4johmd6ul4

**Comment by cryptowhizzard** [comment]
Fellow notary's

All SP's are on one IP.

f02006691 -> {12D3KooWPN4arAnJp49HNGWput31hwG1v7GywW2Qc4nBcF45ABYW: [/ip4/162.219.38.93/tcp/34233]}
ERROR: failed to parse multiaddr "f02006691": must begin with /

lotus net connect f01991416                                                                                                                                                                                                                                                                                                       |
f01991416 -> {12D3KooWKhhdwS4e2KKcU1w8mmrR8QcAVvYPTNfHyLG62n3M75pc: [/ip4/162.219.38.93/tcp/34232]}
ERROR: failed to parse multiaddr "f01991416": must begin with /

lotus net connect f02012032                                                                                                                                                                                                                                                                                                       |
f02012032 -> {12D3KooWLBMSggvqs69icS3srwKpZTtaZAS484aQ2XsDchcAUwV2: [/ip4/162.219.38.93/tcp/34234]}
ERROR: failed to parse multiaddr "f02012032": must begin with /

**Comment by cryptowhizzard** [comment]
Hello @justmineooz 

I am sorry for the technical language in my post above for my fellow notary's.

For the Filecoin + program itself please note that by storing data on the Filecoin network you get 10x the power ( QAP ) of a normal sector. In return for this to be eligible for this incentive there are important rules to abide:

The data must be stored with multiple service providers. ( Not with one organization running multiple SP's but really independent organizations )
The data must be distributed over multiple regions. (Running a VPN is not allowed to fake presence in the USA for example)
The data must be retrievable by everyone in the community to check if you are really storing what you say you are storing. Running boost is highly recommended.
The data must be in line with the mission of FIL+. That means that the data must be valuable for humanity. It can be scientific or other things that people are highly interested in and is unique.
As data preparer you are allowed to store one copy yourself (if the client requests so for the sake of redundancy of the data). If you store your copy in China it means that the other organizations/SP must be outside China.

Above shows that the rules have not been followed in this LDN. Let me know if you have questions about that.
If not then i would like to create a data onboarding plan together with you to recover and get this LDN on the right track.

It consists of:

The entity that is going to do the data preparation for you, where and when. If you need recommendations i can give them to you.
The new SP's you are going to store data with and their reputation. If you need recommendations i can give them to you.
When we do checks on the data stored and how and by who.
The retrieval frequency (how often does the data needs to be retrieved and from where)

**Comment by cryptowhizzard** [comment]
Hello!

>>
Above shows that the rules have not been followed in this LDN. Let me know if you have questions about that.
If not then i would like to create a data onboarding plan together with you to recover and get this LDN on the right track.
>>

Any update here? Do you want to continue and make an onboarding plan for your data?

**Comment by justmineooz** [comment]
Hello @cryptowhizzard
I just finished my Chinese New Year holiday. I have some questions about the FIL+ rules.
> The data must be stored with multiple service providers
> The data must be distributed over multiple regions

How many regions does the data need to be distributed at least? We did not find enough SPs at first. However, we have found more SPs to store our data currently, and i believe this will never happen again in the next round.

> The data must be retrievable by everyone in the community to check if you are really storing what you say you are storing. Running boost is highly recommended.

That's because our SPs who stored our data use lotus to import storage deal, they will finish deploying and switching boost next week, the retrieval problem will be resolved.

After all these problems have been resolved, i will give an detailed onboarding plan for our data here.

Additionally,  as a Web2 company, We lack a comprehensive and complete understanding of Filecoin's storage and data distribution rules of the Filecoin + program , and we will continue to work hard to embrace web3 on the premise of complying with the rules.

**Comment by justmineooz** [comment]
Hello @cryptowhizzard 

After contacted our SPs and checked the retrieval problems, they have resolved it, and the retrieval works well currently.
Tested some deals and got the correct response:

lotus client retrieve --provider f01991416 uAXASIBdb45X2tQ7XM-FPRqXSz2Cwt8lKreF9CoKOiOxcHcZR ./uAXASIBdb45X2tQ7XM-FPRqXSz2Cwt8lKreF9CoKOiOxcHcZR.tar
```sh
Recv 0 B, Paid 0 FIL, Open (New), 0s [1673063481417153276|0]
Recv 0 B, Paid 0 FIL, DealProposed (WaitForAcceptance), 18ms [1673063481417153276|0]
Recv 0 B, Paid 0 FIL, DealAccepted (Accepted), 1m4.03s [1673063481417153276|0]
Recv 0 B, Paid 0 FIL, PaymentChannelSkip (Ongoing), 1m4.031s [1673063481417153276|0]
Recv 11.84 KiB, Paid 0 FIL, BlocksReceived (Ongoing), 1m12.761s [1673063481417153276|12127]
Recv 15.22 KiB, Paid 0 FIL, BlocksReceived (Ongoing), 1m12.772s [1673063481417153276|15587]
Recv 1.015 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 1m21.448s [1673063481417153276|1064163]
Recv 2.015 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 1m28.884s [1673063481417153276|2112739]
Recv 3.015 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 1m34.505s [1673063481417153276|3161315]
Recv 4.015 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 1m39.699s [1673063481417153276|4209891]
```

 lotus client retrieve --provider f01991416 uAXASILnw_b5KQnuw3l7CSnGXiyOjWR7KM-tfmESs8eZQkI1G ./uAXASILnw_b5KQnuw3l7CSnGXiyOjWR7KM-tfmESs8eZQkI1G.tar
```
Recv 0 B, Paid 0 FIL, Open (New), 0s [1673063481417153277|0]
Recv 0 B, Paid 0 FIL, DealProposed (WaitForAcceptance), 11ms [1673063481417153277|0]
Recv 0 B, Paid 0 FIL, DealAccepted (Accepted), 1m22.952s [1673063481417153277|0]
Recv 0 B, Paid 0 FIL, PaymentChannelSkip (Ongoing), 1m22.952s [1673063481417153277|0]
Recv 13.86 KiB, Paid 0 FIL, BlocksReceived (Ongoing), 2m3.044s [1673063481417153277|14193]
Recv 19.58 KiB, Paid 0 FIL, BlocksReceived (Ongoing), 2m3.052s [1673063481417153277|20053]
Recv 1.019 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 2m16.372s [1673063481417153277|1068629]
```

**Comment by cryptowhizzard** [comment]
Hi there,

I have retrieval working now, that is very good. However looking at the data i am wondering what you are storing and if this is okay according to the law. Since the region this data is from is not my cup of tea for rules and guidelines I am not going to sign this LDN.

Fellow notary's ._> if you want to evaluate the data please do : http://www.datasetcreators.com/downloadedcarfiles/f01941584-f02012032-22613025-baga6ea4seaqaxczirwyuj5zff4ppkgq6lqsxrlql4omh2rqnjqsp3uifoq2gkfa.car1 

I will tag this LDN for visibility with other notary's from your region to see if they can approve it.

Thanks!

**Comment by newwebgroup** [comment]
The link does not open properly @cryptowhizzard 
> http://www.datasetcreators.com/downloadedcarfiles/f01941584-f02012032-22613025-baga6ea4seaqaxczirwyuj5zff4ppkgq6lqsxrlql4omh2rqnjqsp3uifoq2gkfa.car1


<img width="674" alt="image" src="https://user-images.githubusercontent.com/100118145/219546038-79fa901c-35aa-4d1a-9bdd-b3353719b6e1.png">

**Comment by cryptowhizzard** [comment]
![Scherm­afbeelding 2023-02-17 om 11 20 19](https://user-images.githubusercontent.com/36404435/219617639-ee028832-7d3b-46c0-8ab8-aef49e2de008.png)

Are you sure?

**Comment by justmineooz** [comment]
> The link does not open properly @cryptowhizzard
> 
> > http://www.datasetcreators.com/downloadedcarfiles/f01941584-f02012032-22613025-baga6ea4seaqaxczirwyuj5zff4ppkgq6lqsxrlql4omh2rqnjqsp3uifoq2gkfa.car1
> 
> <img alt="image" width="674" src="https://user-images.githubusercontent.com/100118145/219546038-79fa901c-35aa-4d1a-9bdd-b3353719b6e1.png">

Please don not forget the "/" in the end of the url: 

http://www.datasetcreators.com/downloadedcarfiles/f01941584-f02012032-22613025-baga6ea4seaqaxczirwyuj5zff4ppkgq6lqsxrlql4omh2rqnjqsp3uifoq2gkfa.car1/

**Comment by mjroddy** [comment]
Is this suitable for FIL+

“Filecoin Plus is a program that aims to maximize the amount of useful storage that Filecoin can and will support.

The ultimate goal of Filecoin Plus is to accelerate the timeframe over which storage goods and services on Filecoin become more useful and attractive. The program plays an essential role in shaping the product offering on the network in collaboration with storage miners.”

Can you help justify this? It may be worth going through regular deals for this application.

**Comment by justmineooz** [comment]
checker:manualTrigger

**Comment by justmineooz** [comment]
@dannyob @simonkim0515 @liyunzhi-666 @Sunnyiscoming @lvschouwen @kernelogic
Dear notaries, I noticed you are very active notaries on other LDNs, could you please help us to move forward? Any question please leave a comment. Thanks a lot!

**Comment by mjroddy** [comment]
> Is this suitable for FIL+
> 
> “Filecoin Plus is a program that aims to maximize the amount of useful storage that Filecoin can and will support.
> 
> The ultimate goal of Filecoin Plus is to accelerate the timeframe over which storage goods and services on Filecoin become more useful and attractive. The program plays an essential role in shaping the product offering on the network in collaboration with storage miners.”
> 
> Can you help justify this? It may be worth going through regular deals for this application.

@justmineooz Please respond to above request - I am a notary trying to understand how this is suited to FIL+

**Comment by igoovo** [comment]
checker:manualTrigger
