### ISSUE TITLE
[DataCap Allocation] - The genetic testing data of pet-repulicate  （ 2 / 2 ）

### ISSUE THREAD

**Issue by yvonne-23MF** [filecoin-project/filecoin-plus-large-datasets#1122]
---
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Chengdu 23mofang Biotechnology Co., Ltd.
- Website / Social Media: https://www.23mofang.com/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 200TiB
- On-chain address for first allocation: f1tfxuwt2akoyizqpu64oy3k36lz77nfkfelt3tmy
- Region: Greater China Region

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Chengdu 23mofang Biotechnology Co., Ltd. was established in March 2015 to provide biogenetic testing and life data analysis services.

According to the "2018 China Genetic Testing Industry Analysis" released by a third-party data agency—Analysys International,23mofang ranked first in the consumer-grade genetic testing field.Here is the news address:https://www.jiemian.com/article/2244613.html

And in In the Forbes list of "Chinese Fifty Most Innovative Companies",23mofang was rated as the "The innovator of Gene testing",check:https://m.huanqiu.com/article/9CaKrnK9GMf。
So far, 23mofang has accumulated 6 rounds of financing from SBCVC,Hanvon technology，Matrix Partners China,CD Capital,etc.23mofang is the largest domestic consumer-based company.

Based on leading genetic research results, 23mofang owns a professional bio-testing center and uses world-leading testing equipment for sequencing, our company provides users with highly readable and usable genetic test reports. 23mofang's self-built genetic testing center has been certified by the National Health and Family Planning Commission and meets all the standards of medical and clinical trial institutions.

For better scientific research,the company also bulid cooperation with Ministry of Education Key Laboratory of Contemporary Anthropology,the Medical Heredity Research Center of Southwest hospital of AMU,Kunming institute of zoology . cas.

23mofang's  pet genetic testing uses saliva to collect  sample and provides hundreds of test items such as pedigree analysis, genetic risk, genetic traits, genetic variant carriage, nutritional needs, medication response, exercise health, skin management and more. we collect and analyze pet genetic data for diagnosing or ruling out the suspected genetic diseases, and predicting the risk of specific diseases, so we can help users to understand the ancestral origin, physical characteristics and health conditions of pets.

Our pet genetic testing helps humans understand animals better and establish a harmonious ecological environment between humans and animals, while the huge pet test analysis data also greatly promotes the development of animal medical research and animal genetic science research.

Offical Website:  https://www.23mofang.com/
Offical Wechat:   23魔方
Offical Tiktok:   @23魔方溯源故事、@23魔方寻宗
```
![image](https://user-images.githubusercontent.com/116244579/196918622-9ba7b820-f2f5-479a-9a2c-cfbcf9c61fc0.png)
![image (1)](https://user-images.githubusercontent.com/116244579/196918787-f3b51b55-74bf-4bce-8c7d-4a77b30d610d.png)
![image (2)](https://user-images.githubusercontent.com/116244579/196918822-54aa2187-acf1-4162-89f9-a2c54bebd689.png)
![image (3)](https://user-images.githubusercontent.com/116244579/196918858-7e140ebc-20a8-454a-b1a8-1325c28c5c17.png)
![e2ebaa67bb3ac873edc4120cac997b6](https://user-images.githubusercontent.com/116244579/196920637-a7272a67-f379-40cf-a952-5a75c05120e3.jpg)

What is the primary source of funding for this project?
```
The fund of data storage in this project is provided by our company.
```

What other projects/ecosystem stakeholders is this project associated with?
```
We have applied general verification datacap from notaries before, check #427、#428、#602,so we have bulid trust with Filecoin,adn we hope that we can storage our data in Filecoin steady.
```

## Use-case details

Describe the data being stored onto Filecoin
```
Animal gene test samples, analysis results and gene source data. They are all private data.
```

Where was the data in this dataset sourced from?
```
All the data from our company
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
Parameter indicators of animal data:https://1drv.ms/u/s!Ah-lIf4OzDPabwLnSRrpcnWpidw?e=S0ShEU
List of test samples:https://1drv.ms/u/s!Ah-lIf4OzDPaaoJLZKOAl_D2JTg?e=LXOkdn
Genetic test data:https://1drv.ms/u/s!Ah-lIf4OzDPaa44krWKwYX5v0bA?e=dPctKh
Test result:https://1drv.ms/u/s!Ah-lIf4OzDPabgKczD-K1wnHnh4?e=Alk3MS
Profile of test object:https://1drv.ms/u/s!Ah-lIf4OzDPacDa76kVDEICqZvk?e=bqbJ4e
Test report:https://1drv.ms/u/s!Ah-lIf4OzDPacWPsY8xcDQ8SMLg?e=JHZfPh
 https://1drv.ms/u/s!Ah-lIf4OzDPacvU_l7MwJRrZ154?e=gEaxl6
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
NO
```

What is the expected retrieval frequency for this data?
```
None
```

For how long do you plan to keep this dataset stored on Filecoin?
```
Permanently.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Global
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
online and off-line
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We currently have an established relationship with MDM, and depending on the subsequent progress of storage and the number of seal, we will continue to investigate and choose a wider range of SPs for cooperation.
We investigate SP from the following two aspects:
--Experience in storing real data
Long-term and stable storage operation and maintenance capabilities.
```

How will you be distributing deals across storage providers?
```
We provide more than 2P of pet genetic data, and copy to 5 duplicates. According to the final SP numbers,we will make a reasonable distribution plan.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, the funds for storage are ready.
```

**Comment by yvonne-23MF** [comment]
@kevzak
Hi，this is our application for FIl-E

**Comment by kevzak** [comment]
fyi above @raghavrmadya

**Comment by yvonne-23MF** [comment]
@kevzak Please help to open this issue. This is the second part of the"The genetic testing data of pet-repulicate"project. Currently, the first part (1121) is still in progress, and we will provide timely updates on the progress of this application.
@simonkim0515 Please be informed of the above situation and kindly assist in opening it.

**Comment by yvonne-23MF** [comment]
update
