### ISSUE TITLE
[DataCap Application] Digital Earth Africa GeoMAD for Drust-Agee

### ISSUE THREAD

**Issue by Agee-Drust** [filecoin-project/filecoin-plus-large-datasets#1123]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Drust
- Website / Social Media:n/a
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):100TiB
- On-chain address for first allocation:f1rzap6ssv7d7odff4azw7nky6uorn3fy7hyogbey

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
I'm a member in Filecoin, but I have ambitious with Filecoin and Filecoin slingshot about ensuring meaningful data is stored and retrieved from the Filecoin Network.
```

What is the primary source of funding for this project?
```
My own source.
```

What other projects/ecosystem stakeholders is this project associated with?
```
No
```

## Use-case details

Describe the data being stored onto Filecoin
```
Sentinel-2 GeoMAD (Annual) data
Sentinel-2 GeoMAD (Semi-Annual) data
Landsat 8 GeoMAD (Annual) data
Landsat 5 and 7 GeoMAD (Annual) data
```

Where was the data in this dataset sourced from?
```
The data is from AWS Open dataset.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://registry.opendata.aws/deafrica-geomad/
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
I confirm. This is a open dataset.
```

What is the expected retrieval frequency for this data?
```
Follow LDN Application rules. 1-2 times half a year.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
More than 1 year.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
All regions. 
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
After CAR files are ready, I will upload it to the server for SP, or I will prepare disks. Then I will propose offline deals after they get files.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
I plan to make deals with SPs that support data retrieval and have stable sealing rate.
Also, I welcome every one who are interested with this deal.
```

How will you be distributing deals across storage providers?
```
Try to make every SP under 25% of deals.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Enough.
```

**Comment by raghavrmadya** [comment]
Please share how exactly will you follow LDN rules. Who are the SPs you have been in touch with and be specific about geographic distribution

**Comment by Agee-Drust** [comment]
> Please share how exactly will you follow LDN rules. Who are the SPs you have been in touch with and be specific about geographic distribution

@raghavrmadya Hi Raghav, here is my former application and it can approve that I have been following the rules of LDN.  https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/427

This is the datacap allocation I already had.
![87](https://user-images.githubusercontent.com/106581965/197481464-56e04f90-30ac-4cf9-ab5f-86d82bc7091e.png)

I'd like to cooperate with SPs in all regions. I've been in touch with SPs in USA, Korea, Sinapore, Japan. SPs: f01895783, f01917257, f01917241, f01924325 

I will continue to follow the rules of LDN, for the purpose of distributed storage.

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 100TiB

**Client address**

>f1rzap6ssv7d7odff4azw7nky6uorn3fy7hyogbey

**Comment by PluskitOfficial** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacea3ogl5iak7pqurfldurawkwip3sidjjyr5tph2sqibarbcjhgjg2 
#### Address 
> f1rzap6ssv7d7odff4azw7nky6uorn3fy7hyogbey
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1tgnlhtcmhwipfm7thsftxhn5k52velyjlazpvka
#### Id
> 4919cc30-da9b-466a-a7b6-7103a4a5f285
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacea3ogl5iak7pqurfldurawkwip3sidjjyr5tph2sqibarbcjhgjg2

**Comment by MetaWaveInfo** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebehtvvmwyv5r5xdg6dyybjcu3stqz2et3eziqebebsjsej4kzcsa 
#### Address 
> f1rzap6ssv7d7odff4azw7nky6uorn3fy7hyogbey
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1ktlkcxnmzxcdaoqfsunrg3vocfbmgv4n3mrn74a
#### Id
> 4919cc30-da9b-466a-a7b6-7103a4a5f285
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebehtvvmwyv5r5xdg6dyybjcu3stqz2et3eziqebebsjsej4kzcsa

**Comment by Sunnyiscoming** [comment]
Is there any problem with using datacap?

**Comment by Casey-PG** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedflr5efduiqp66stfplzulczxfajejgsy7sgiuvgrubupsv2mjpk 
#### Address 
> f1rzap6ssv7d7odff4azw7nky6uorn3fy7hyogbey
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1d4yb3wags3mtddzesxoo63jv7dmlec3bq4yteni
#### Id
> 14dabb50-337b-4a27-a526-041672efeb3f
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedflr5efduiqp66stfplzulczxfajejgsy7sgiuvgrubupsv2mjpk

**Comment by Meibuy** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedlifeutzxhzqod2jxw3t43p6mxwectiiq4fydt4yobqdnyq6kqr6 
#### Address 
> f1rzap6ssv7d7odff4azw7nky6uorn3fy7hyogbey
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1bwugfihrmn3iyunzyxst5nttql3dge4khwmurtq
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedlifeutzxhzqod2jxw3t43p6mxwectiiq4fydt4yobqdnyq6kqr6

**Comment by TakiChain** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceco6xmpswz5gqtcsvd77l66bm7lx3b6gtjaglf5vupfggbzcui222 
#### Address 
> f1rzap6ssv7d7odff4azw7nky6uorn3fy7hyogbey
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f15impf3j2zcaex4lhyxndxswuuhv24vzstuqtxsi
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceco6xmpswz5gqtcsvd77l66bm7lx3b6gtjaglf5vupfggbzcui222

**Comment by Aifabot-Cloud** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecs2cekbboyva3ly27cuv7leo2gxgw563lkvrb7ksenbt43hwklj2 
#### Address 
> f1rzap6ssv7d7odff4azw7nky6uorn3fy7hyogbey
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f174fg3bqbln3zjnkxtyf6s54txqkr7yqkj6cig7y
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecs2cekbboyva3ly27cuv7leo2gxgw563lkvrb7ksenbt43hwklj2

**Comment by Casey-PG** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb6ptfjztnbdimaodbbyaawxwpmgcqjdcmfualy5t7tpsz3r3naig 
#### Address 
> f1rzap6ssv7d7odff4azw7nky6uorn3fy7hyogbey
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1d4yb3wags3mtddzesxoo63jv7dmlec3bq4yteni
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb6ptfjztnbdimaodbbyaawxwpmgcqjdcmfualy5t7tpsz3r3naig

**Comment by Sunyaoyaomk** [comment]
checker:manualTrigger

**Comment by Agee-Drust** [comment]
checker:manualTrigger

**Comment by AthSmith** [comment]
Looked into the CID report and retrieval performance, it's good to go. Kindly improve Deal Data Replication performance for the next tranche, keep eyes on it.

**Comment by AthSmith** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb4fiuxwp3bzpsnya2etvrnpfp4cj7z3dpdwxmmmg5vmxdphpvtmy 
#### Address 
> f1rzap6ssv7d7odff4azw7nky6uorn3fy7hyogbey
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1vxbqrf7rfum3n6m5u6eb4re6xj7amvsaqnzu64y
#### Id
> a9ec88d0-243b-440b-b55b-4134093002e8
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb4fiuxwp3bzpsnya2etvrnpfp4cj7z3dpdwxmmmg5vmxdphpvtmy

**Comment by BobbyChoii** [comment]
checker:manualTrigger

**Comment by BobbyChoii** [comment]
Report LGTM, willing to support!

**Comment by BobbyChoii** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceblxr2bkyjaxt2c547hr3cwalmcoeklxlxuddeohxtvflmy56bnsa 
#### Address 
> f1rzap6ssv7d7odff4azw7nky6uorn3fy7hyogbey
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f174fg3bqbln3zjnkxtyf6s54txqkr7yqkj6cig7y
#### Id
> a9ec88d0-243b-440b-b55b-4134093002e8
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceblxr2bkyjaxt2c547hr3cwalmcoeklxlxuddeohxtvflmy56bnsa

**Comment by Sunnyiscoming** [comment]
Hello, @Agee-Drust per the https://github.com/filecoin-project/notary-governance/issues/922 for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

This information will be reviewed by Fil+ Governance team to confirm validity and then the application will be allowed to move forward for additional notary review.
