### ISSUE TITLE
[DataCap Application] Guohong Information

### ISSUE THREAD

**Issue by GHinfomation** [filecoin-project/filecoin-plus-large-datasets#1125]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Shenzhen Guohong Information Technology Co.,Ltd.
- Website / Social Media: http://ghitvip.com/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 300 TiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100 TiB
- On-chain address for first allocation: f1ftviasd566ynh36tll62ddj7bsyfkcgj3bbo3ta
- Type: Custom Notary
- Identifier: E-fil

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Guohong Information was established in 2005, is an intelligent data solutions provider, 
based on App customization, data collection and transmission, cloud computing, network
security to provide a series of data-centric whole process solutions to help customers 
quickly deploy new technologies.

We have formed strategic partnerships with world-class IT technology leaders and 
companies to provide our customers with latest technology and first-class services, such
as: Oracle, IBM, EMC, vmware, Cisco, H3C, Microsoft, Intel, etc.
```

What is the primary source of funding for this project?
```
company profit
```

What other projects/ecosystem stakeholders is this project associated with?
```
None.
```

## Use-case details

Describe the data being stored onto Filecoin
```
Guohong information is a full process solution provider that provides consulting, design,
technology development, installation, deployment, and after-sales service. The data stored
on filecoin network will be mainly design solutions, development logs, maintenance tools, 
image backups and other data.
```

Where was the data in this dataset sourced from?
```
from guohong information platform.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
Yes.
https://1drv.ms/u/s!AkNgWzu4Xv4xafKrjB-DJnAzBSA?e=kDMtEx
https://1drv.ms/u/s!AkuO-ybKmae0bcXgUHSxfPEnxDU?e=ZFdxXI
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Private.
```

What is the expected retrieval frequency for this data?
```
Expected to be retrieved every 12 months.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
At least 2 years.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
We do not have preference, Maybe China, US, or Singapore.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
We plan to offline transfer of our data.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We are currently discussing capabilities and performing due diligence with serval SPs, 
we are measuring SPs in many ways including stability and locations, etc.
```

How will you be distributing deals across storage providers?
```
We'll distribute less than 25% of whole deals to each storage provider.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, we can make deals when we get datacap.
```

**Comment by kevzak** [comment]
Hello @GHinfomation since this is a private dataset, please complete the [exceptions proposal ](https://github.com/filecoin-project/notary-governance/issues/new/choose)also to provide more details about the data storage plan. Thanks

**Comment by Fenbushi-Filecoin** [comment]
KYB info looks all good from Qcc.

**Comment by Sunnyiscoming** [comment]
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).

Confirm.

@GHinfomation If this is a private dataset. Please adjust it.

**Comment by GHinfomation** [comment]
> Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
> 
> Confirm.
> 
> @GHinfomation If this is a private dataset. Please adjust it.

Yes our data is private, i have adjusted it. At beginning stage we are planning to apply for 300T DC to experience how data are stored on Filecoin network.

**Comment by kevzak** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 300TiB

**Expected weekly DataCap usage rate**

> 100TiB

**Client address**

>f1ftviasd566ynh36tll62ddj7bsyfkcgj3bbo3ta

**Comment by kevzak** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 0.3PiB

**Expected weekly DataCap usage rate**

> 100TiB

**Client address**

>f1ftviasd566ynh36tll62ddj7bsyfkcgj3bbo3ta

**Comment by kevzak** [comment]
Hello - I can confirm for the Fil+ team that @GHinfomation has completed the Client Registration and a manual Business Verification Check successfully.

Assigned notaries can proceed to review the application and the [exceptions proposal](https://github.com/filecoin-project/notary-governance/issues/789) details

**Comment by kevzak** [comment]
> Hello @stcouldlisa - @Fatman13 , please sign the datacap request

@stcloudlisa disregard, as you know, you cannot sign for your client. Thank you.

**Comment by bmcnabb25** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb22dg6bzs3u5igqxfeghggmzwbkqlgrgpc4tdzyqnbexjxeknoiu 
#### Address 
> f1ftviasd566ynh36tll62ddj7bsyfkcgj3bbo3ta
#### Datacap Allocated
> 15.00TiB
#### Signer Address
> f1jqk7xok5kautet2knhwlg74jvcfbrqlj47kbp2i
#### Id
> 239eec27-b4f2-453c-9b8c-ae825fb459ad
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb22dg6bzs3u5igqxfeghggmzwbkqlgrgpc4tdzyqnbexjxeknoiu

**Comment by bmcnabb25** [comment]
Client registration and KYB complete. Application and exceptions proposal checked out. Willing to support first tranche and monitor

**Comment by stcouldlisa** [comment]
> > 你好@stcouldlisa-@Fatman13, 请签署 datacap 请求
> 
> @stcloudlisa 无视，如您所知，您不能为您的客户签名。谢谢你。

ok，thank you

**Comment by kevzak** [comment]
@fatman13 - do you have a chance to look at this one? If not, I will assign another notary

**Comment by Fatman13** [comment]
Hello, @Kevin-FF-USA 

Sorry for the delay, email got buried due to holidays. I am contacted by @GHinfomation just now on Slack and will start DD from there.

**Comment by Fatman13** [comment]
@GHinfomation has provided their entity, distribution planning and sample data information to me on both Slack and wechat.

**Comment by Fatman13** [comment]
Hello, team, I am experiencing technical difficulty again when signing... have already tried multiple times.

![image](https://user-images.githubusercontent.com/1591330/216495877-05928b1d-bdf3-4f73-87ce-899db552d5c9.png)

![image](https://user-images.githubusercontent.com/1591330/216495958-3202a3a6-bd29-4072-a178-a8b8cf462e57.png)

**Comment by cryptowhizzard** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec7vdfc2ovaeraifn66cjxqb3fn24jxl2fzhssex4caxazlcpaw5c 
#### Address 
> f1ftviasd566ynh36tll62ddj7bsyfkcgj3bbo3ta
#### Datacap Allocated
> 15.00TiB
#### Signer Address
> f1krmypm4uoxxf3g7okrwtrahlmpcph3y7rbqqgfa
#### Id
> 239eec27-b4f2-453c-9b8c-ae825fb459ad
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec7vdfc2ovaeraifn66cjxqb3fn24jxl2fzhssex4caxazlcpaw5c

**Comment by cryptowhizzard** [comment]
Helping out a fellow notary ;-)

**Comment by kevzak** [comment]
checker:manualTrigger

**Comment by kevzak** [comment]
@GHinfomation any status on progress of onboarding? Can you comment on the CID checker information before we assign next set of notaries?

**Comment by liyunzhi-666** [comment]
checker:manualTrigger

**Comment by liyunzhi-666** [comment]
hey @GHinfomation In the subsequent distribution, can we see SP in other regions? They are currently concentrated in Thailand and mainland China.

**Comment by kevzak** [comment]
@GHinfomation awaiting any reply from you here, thanks

**Comment by newwebgroup** [comment]
No response from Client for a long time, it is recommended to close LDN temporarily first.
