### ISSUE TITLE
[DataCap Application]Jinchan Curtains Co.,ltd

### ISSUE THREAD

**Issue by gsp-hub** [filecoin-project/filecoin-plus-large-datasets#1126]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name:  Jinchan Curtains Co.,ltd
- Website / Social Media:  Website：www.jinchanwarp.com
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 4.9PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100TiB
- On-chain address for first allocation: f1366c5an6uegsc7zhsy4csax3e5msrhie5gef7mi

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Zhejiang Jinchan Fabric Co., Ltd. was established in 1988. There are more than 700 employees. We are committed to becoming an international leading home textile and home furnishing enterprise, providing customers with a full range of soft furnishing services such as design, production, installation and customization. At present, we are mainly engaged in two business segments:
1. There are more than 500 franchised stores in China.
2. Cross-border e-commerce, domestic e-commerce, live broadcast e-commerce, etc.
```

What is the primary source of funding for this project?
```
Business income from international and domestic business lines
```

What other projects/ecosystem stakeholders is this project associated with?
```
Our current business line designs 3D modeled soft furnishings for customers' homes, and stores live video and product high-definition pictures at the same time.
```

## Use-case details

Describe the data being stored onto Filecoin
```
The data stored on Filecoin is all about design, production, installation, and customization.
```

Where was the data in this dataset sourced from?
```
Mainly from our design production data and customer's installation customization data.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
 https://pan.baidu.com/s/1he89JoXNSgxFbM1faGbGGA?pwd=iu24
Extraction code: iu24 
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes, it is public data that can be retrieved by anyone.
```

What is the expected retrieval frequency for this data?
```
Few times a year.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
we want storage at least 540 days. 
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
At least two regions in North America and Asia. 
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
We mainly conduct online transmission through designated platforms, and we can also provide offline data transmission if necessary.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We will select miners with good reputation, trustworthiness, and experience in verifying data to conduct transactions.
```

How will you be distributing deals across storage providers?
```
We will distribute to high-quality storage providers in an even proportion. Also, each miner won’t be allocated more than 30% of our datacap. 
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes we have. 
```

**Comment by gsp-hub** [comment]
[Jincan-Curtains.pdf](https://github.com/filecoin-project/filecoin-plus-large-datasets/files/9835491/Jincan-Curtains.pdf)
My last application was flagged

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 4.9PiB

**Expected weekly DataCap usage rate**

> 100TiB

**Client address**

> f1366c5an6uegsc7zhsy4csax3e5msrhie5gef7mi

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 4.9PiB

**Expected weekly DataCap usage rate**

> 100TiB

**Client address**

> f1366c5an6uegsc7zhsy4csax3e5msrhie5gef7mi

**Comment by raghavrmadya** [comment]
The Trust & Transparency Working Group has assessed through its investigation that while this business is legitimate, we arer unable to determine the relationship of the applicant with the business. At this point, we request the applicant to prove the relationship as well as notaries to conduct further due diligence before signing first tranche

**Comment by gsp-hub** [comment]
Hi, @raghavrmadya  I have sent a KYC email to the official email address, please check it.
![微信图片_20221202174154](https://user-images.githubusercontent.com/71632608/205263716-6416966e-581a-4a95-8926-4ca9d5bc2df4.png)

**Comment by Defil2022** [comment]
Hello @gsp-hub 
Do you mind elaborate on why you has so much data as a curtain company?

**Comment by filplus-checker** [comment]
## DataCap and CID Checker Report[^1]
 - Organization: `Jinchan Curtains Co.,ltd`
 - Client: `f1366c5an6uegsc7zhsy4csax3e5msrhie5gef7mi`
### Storage Provider Distribution
The below table shows the distribution of storage providers that have stored data for this client.

If this is the first time a provider takes verified deal, it will be marked as `new`.

For most of the datacap application, below restrictions should apply.
 - Storage provider should not exceed 25% of total datacap.
 - Storage provider should not be storing duplicate data for more than 20%.
 - Storage provider should have published its public IP address.
 - All storage providers should be located in different regions.

⚠️ 79.62% of total deal sealed by [f01853077](https://filfox.info/en/address/f01853077) are duplicate data.

⚠️ 83.98% of total deal sealed by [f01852363](https://filfox.info/en/address/f01852363) are duplicate data.

⚠️ 76.77% of total deal sealed by [f01834253](https://filfox.info/en/address/f01834253) are duplicate data.

⚠️ 81.03% of total deal sealed by [f01384160](https://filfox.info/en/address/f01384160) are duplicate data.

⚠️ 62.30% of total deal sealed by [f01215819](https://filfox.info/en/address/f01215819) are duplicate data.

⚠️ 76.56% of total deal sealed by [f01834291](https://filfox.info/en/address/f01834291) are duplicate data.

| Provider                                              |                    Location | Total Deals Sealed | Percentage | Unique Data | Duplicate Deals |
| :---------------------------------------------------- | --------------------------: | -----------------: | ---------: | ----------: | --------------: |
| [f01853077](https://filfox.info/en/address/f01853077) |    Singapore, Singapore, SG |           9.97 TiB |     20.90% |    2.03 TiB |          79.62% |
| [f01852363](https://filfox.info/en/address/f01852363) |    Singapore, Singapore, SG |           8.00 TiB |     16.78% |    1.28 TiB |          83.98% |
| [f01834253](https://filfox.info/en/address/f01834253) | Los Angeles, California, US |           7.94 TiB |     16.64% |    1.84 TiB |          76.77% |
| [f01384160](https://filfox.info/en/address/f01384160) |     Shenzhen, Guangdong, CN |           7.91 TiB |     16.58% |    1.50 TiB |          81.03% |
| [f01215819](https://filfox.info/en/address/f01215819) |     Shenzhen, Guangdong, CN |           7.88 TiB |     16.51% |    2.97 TiB |          62.30% |
| [f01834291](https://filfox.info/en/address/f01834291) | Los Angeles, California, US |           6.00 TiB |     12.58% |    1.41 TiB |          76.56% |

![Provider Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/1126/1671098678933.png)
### Deal Data Replication
The below table shows how each many unique data are replicated across storage providers.
- No more than 25% of unique data are stored with less than 4 providers.

⚠️ 100.00% of deals are for data replicated across less than 4 storage providers.

| Unique Data Size | Total Deals Made | Number of Providers | Deal Percentage |
| ---------------: | ---------------: | ------------------: | --------------: |
|        11.03 TiB |        47.69 TiB |                   1 |         100.00% |

![Replication Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/1126/1671098679595.png)
### Deal Data Shared with other Clients
The below table shows how many unique data are shared with other clients.
Usually different applications owns different data and should not resolve to the same CID.

⚠️ CID sharing has been observed.

| Other Client                                                                                                          | Application                                                                                                        | Total Deals Affected | Unique CIDs |        Verifier |
| :-------------------------------------------------------------------------------------------------------------------- | :----------------------------------------------------------------------------------------------------------------- | -------------------: | ----------: | --------------: |
| [f1vajbbihmcqkcjlnicmjto6fflklvhoifips7uzq](https://filfox.info/en/address/f1vajbbihmcqkcjlnicmjto6fflklvhoifips7uzq) | `rctAI`                                                                                                            |            27.56 TiB |         146 | LDN v3 multisig |
| [f1ji2xty4dtg2a4pfnslltkw7pbhy76kvihizkfmq](https://filfox.info/en/address/f1ji2xty4dtg2a4pfnslltkw7pbhy76kvihizkfmq) | `Pow Power`                                                                                                        |            19.47 TiB |         107 | LDN v3 multisig |
| [f1gmiepn73zoa5gz2oiqyugjmrsecwj5qxd42vmyi](https://filfox.info/en/address/f1gmiepn73zoa5gz2oiqyugjmrsecwj5qxd42vmyi) | ``                                                                                                                 |            12.81 TiB |          70 | LDN v3 multisig |
| [f1ng6g57r4u62q67u6lm33ftijfsggyzzjzb2l4cy](https://filfox.info/en/address/f1ng6g57r4u62q67u6lm33ftijfsggyzzjzb2l4cy) | [NFTSTAR](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/960)                             |             6.63 TiB |          29 | LDN v3 multisig |
| [f1df64fi3a4pmo5mxvdrz2zs7n2bfd4wnixomudcq](https://filfox.info/en/address/f1df64fi3a4pmo5mxvdrz2zs7n2bfd4wnixomudcq) | [UZERO](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/294)                               |             5.69 TiB |          50 | LDN v3 multisig |
| [f1guplg5wyjdn6bv4forsb5eu2lohexvdlttkavpq](https://filfox.info/en/address/f1guplg5wyjdn6bv4forsb5eu2lohexvdlttkavpq) | [Ipollo](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/168)                              |             2.91 TiB |          15 |       LDN # 168 |
| [f1o2nxreefzqzc2mvaqneaolpdat5yk3275r6rofa](https://filfox.info/en/address/f1o2nxreefzqzc2mvaqneaolpdat5yk3275r6rofa) | [iPolloverse SG PTE\. LTD](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/767)            |             2.88 TiB |          10 | LDN v3 multisig |
| [f1y7xmlneep3qtxcumqlmqrja3fhqdxdaxwou6mdq](https://filfox.info/en/address/f1y7xmlneep3qtxcumqlmqrja3fhqdxdaxwou6mdq) | [ND LABS](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/109)                             |             1.41 TiB |          10 |       LDN # 109 |
| [f17d2n363326qlln4uva7ylxteamtdj3lq6wuaewi](https://filfox.info/en/address/f17d2n363326qlln4uva7ylxteamtdj3lq6wuaewi) | [Metadata Labs Inc](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/200)                   |             1.25 TiB |          10 |       LDN # 200 |
| [f1zxmwo3kwapc6axatwuia4lsowvpasco3znfbuvi](https://filfox.info/en/address/f1zxmwo3kwapc6axatwuia4lsowvpasco3znfbuvi) | Unknown                                                                                                            |           736.00 GiB |           4 |         Unknown |
| [f1dfkdmjhuvvol6okun57mix447wdpolwcd323ktq](https://filfox.info/en/address/f1dfkdmjhuvvol6okun57mix447wdpolwcd323ktq) | [BITRISE CAPITAL FOUNDATION PTE\.LTD](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/139) |           736.00 GiB |           5 |       LDN # 139 |
| [f1qpkmibcsitxtxwg6ayghxwkssoxs4bfyzwzslza](https://filfox.info/en/address/f1qpkmibcsitxtxwg6ayghxwkssoxs4bfyzwzslza) | [GAMEWAY PTE\. LTD\.](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/158)                 |           640.00 GiB |           2 |       LDN # 158 |
| [f1pnsnrfp5dqfqwospzj6vis6jxhni765i37tne5q](https://filfox.info/en/address/f1pnsnrfp5dqfqwospzj6vis6jxhni765i37tne5q) | [TIMAGE](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/302)                              |           416.00 GiB |           3 | LDN v3 multisig |
| [f1ewwoms3aiairedun4h2uayqhlmtjsulnqy2xnrq](https://filfox.info/en/address/f1ewwoms3aiairedun4h2uayqhlmtjsulnqy2xnrq) | [AsiaBlockchain Gaming Alliance](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/179)      |           352.00 GiB |           2 |       LDN # 179 |
| [f14kei3mbjobgsfszu5cndhosuobkbbtoaikc52pq](https://filfox.info/en/address/f14kei3mbjobgsfszu5cndhosuobkbbtoaikc52pq) | [Proya](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/295)                               |           256.00 GiB |           8 | LDN v3 multisig |
| [f13fjnwckkgnkbpapcmnpupbdf4ohduomdso4eqga](https://filfox.info/en/address/f13fjnwckkgnkbpapcmnpupbdf4ohduomdso4eqga) | [Asia Blockchain Gaming Alliance](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/872)     |           224.00 GiB |           1 | LDN v3 multisig |

[^1]: To manually trigger this report, add a comment with text `checker:manualTrigger`

**Comment by raghavrmadya** [comment]
Failed T&T audit
