### ISSUE TITLE
[DataCap Application] <Ji Xia Technology Hong Kong Limited> - <CoinSummer Razzil>

### ISSUE THREAD

**Issue by maxvint** [filecoin-project/filecoin-plus-large-datasets#1127]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Ji Xia Technology Hong Kong Limited
- Website / Social Media: https://razzil.coinsummer.io
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 200TiB
- On-chain address for first allocation: f1k7o76avapwoap5tce5ywbktwlgnroqktfg2sjii

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
CoinSummer Razzil is a blockchain data analysis and display platform focusing on EVM compatible chains.

We have collected the full on-chain data of Ethereum, Binance Smart Chain, Avalanche, Polygon, Arbitrum, Fantom and other Layer1 or Layer2 blockchains through full nodes RPC API, and then query from the full data , index price, marketcap, trading volume, TVL(total value locked) and other indicators, as well as the changes of these indicators, provide strong data support for investment decisions.

At present, the total on-chain data collected on the razzil platform over 12PB, of which 8PB of these data are archived compressed packages of full data, which are currently stored on AWS s3. It supports data analysis and display of more than 50 public chains and more than 800 protocols in various dimensions.
```

What is the primary source of funding for this project?
```
Own funds and revenue of the company.
```

What other projects/ecosystem stakeholders is this project associated with?
```
None
```

## Use-case details

Describe the data being stored onto Filecoin
```
The data stored on Filecoin is the full blockchain archive data as .csv and .tar format.
```

Where was the data in this dataset sourced from?
```
From the full node we maintend and the indexed data by our data platform.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://drive.google.com/drive/folders/1wZFOGzCkBSzYE4sU8A56x01zMYu6jWkk?usp=sharing
```

Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes
```

What is the expected retrieval frequency for this data?
```
3 - 5 times every 540 days.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
Store for at least 540 days.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Asia and North America.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
We will send CAR files to storage providers offline for deal making.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We will check their overall capacity and working hours, we need a storage provider that we can work with for a long time.
```

How will you be distributing deals across storage providers?
```
We will allocate DataCap according to miner's preference, such as online transfer and offline transfer.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes，we have enough funding and resources to start making deals.
```

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 200TiB

**Client address**

> f1k7o76avapwoap5tce5ywbktwlgnroqktfg2sjii

**Comment by psh0691** [comment]
I have a few questions about DC allocation.
1. Can you prove the amount of data you currently have? Example) Screenshot of data capacity
2. Are there any related SPs?
3. Did you select the Filecoin node you want to save?

**Comment by yuwenhui** [comment]
@psh0691 
1. We have about 9PiB archived of the full blockchain data stored on AWS S3 which contains most of the EVM compatible chains, this is the screenshot of AWS S3 buckets.
    <img width="1658" alt="WechatIMG423" src="https://user-images.githubusercontent.com/1715211/206112933-6aed7311-8ad4-4f0a-806f-08177d003f94.png">

2. We have contacted 4 SPs to store these data, we hope to find more.
3. We plan to store Filecoin chain data in the future, which is still under development.

**Comment by psh0691** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedujheoa2evgpaohrnrgzqbsdi52jjrmwz5uot2rhw5kfrqdgliyq 
#### Address 
> f1k7o76avapwoap5tce5ywbktwlgnroqktfg2sjii
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1qdko4jg25vo35qmyvcrw4ak4fmuu3f5rif2kc7i
#### Id
> 59b426ef-d2a9-4c68-bccd-3a8a3c31c8d5
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedujheoa2evgpaohrnrgzqbsdi52jjrmwz5uot2rhw5kfrqdgliyq

**Comment by Fenbushi-Filecoin** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaxj6moz2qab7oq25jgdpsvu6ystzya3z5kdcxk4sha2f3jda3zsk 
#### Address 
> f1k7o76avapwoap5tce5ywbktwlgnroqktfg2sjii
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1yqydpmqb5en262jpottko2kd65msajax7fi4rmq
#### Id
> 59b426ef-d2a9-4c68-bccd-3a8a3c31c8d5
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaxj6moz2qab7oq25jgdpsvu6ystzya3z5kdcxk4sha2f3jda3zsk

**Comment by yuwenhui** [comment]
checker:manualTrigger

**Comment by cryptowhizzard** [comment]
Hello @yuwenhui 

I see deals on chain, however all deals come back as slashed. Can you tell me what has been going on here?

[client-f01942130.csv](https://github.com/filecoin-project/filecoin-plus-large-datasets/files/10424151/client-f01942130.csv)

lotus state get-deal 22262474
ERROR: deal 22262474 not found - deal may not have completed sealing before deal proposal start epoch, or deal may have been slashed

For example.

**Comment by yuwenhui** [comment]
> Hello @yuwenhui
> 
> I see deals on chain, however all deals come back as slashed. Can you tell me what has been going on here?
> 
> [client-f01942130.csv](https://github.com/filecoin-project/filecoin-plus-large-datasets/files/10424151/client-f01942130.csv)
> 
> lotus state get-deal 22262474 ERROR: deal 22262474 not found - deal may not have completed sealing before deal proposal start epoch, or deal may have been slashed
> 
> For example.

Hello @cryptowhizzard
Firstly, ` lotus state get-deal 22262474 ERROR: deal 22262474 not found`, that's because the deal 22262474 did't completed sealing. You can try `lotus state get-deal 22262474` again and it will display the deal state correctly.
```
{
  "Proposal": {
    "PieceCID": {
      "/": "baga6ea4seaqco33ozurglwm3if4flyfckj4pebpbagz3djkaim7r2ejfroq5kly"
    },
    "PieceSize": 34359738368,
    "VerifiedDeal": true,
    "Client": "f01942130",
    "Provider": "f02012032",
    "Label": "uAXASIKu5te5vPh-PQEHEjLlXyaRRsg-Rq-LYzeWPFOXKjP4_",
    "StartEpoch": 2543804,
    "EndEpoch": 3582997,
    "StoragePricePerEpoch": "0",
    "ProviderCollateral": "9675929767997153",
    "ClientCollateral": "0"
  },
  "State": {
    "SectorStartEpoch": 2517743,
    "LastUpdatedEpoch": -1,
    "SlashEpoch": -1,
    "VerifiedClaim": 4744821
  }
}
```
However, there was another problem after we confirmed with the SP f02012032, the deal state is  StorageDealError, and has an the follow error:
```
error awaiting deal pre-commit: failed to set up called handler: on head changed error: called check error (h: 2516862): failed to check deal activity: failed to look up deal on chain: looking for publish deal message bafy2bzacebi44wtyxethxffuojvwfhq4fhl5cn65p6nsw5tffmoxljvxgycxw: not found
```
That's may be an unresolved bug of lotus market, our SP will use boost to import storage deals later.

**Comment by cryptowhizzard** [comment]
Hello @yuwenhui 

Boost has been around for a long time now and working perfectly. "later" is not the right word. If you want to continue with this LDN the data needs to be retrievable and you need to find SP's that are on boost currently or who are not but have good retrieval in place ( i know there are multiple )

**Comment by yuwenhui** [comment]
@cryptowhizzard Okey, "later" means we will stop sent deals to these SPs until they can be retrievable. If they could not be retrievable, I will ask you for help in finding more SPs who have good retrieval in place.

**Comment by Sunnyiscoming** [comment]
checker:manualTrigger

**Comment by herrehesse** [comment]
@yuwenhui Can you give me more information about the current SP's you are storing with? Their business name, region and city?

**Comment by Sunnyiscoming** [comment]
Hi, please explain the abnormal information.
CID sharing has been observed.

**Comment by yuwenhui** [comment]
> Hi, please explain the abnormal information. CID sharing has been observed.

Hello @Sunnyiscoming
Thanks for your check on our LDN application.

We have contacted our SP and tried to work on the issue of CID sharing you mentioned. Currently we got the feedback that they made some technical mistake when they import the deals of these two datasets. We have communicated many times with SP to check their process of deal storage. And they promise that this will not happen again. 

We also hope the community continue giving supervision and suggestions to help us store data on the Filecoin network more efficiently and smoothly.

**Comment by cryptowhizzard** [comment]
Feb 15 15:25:30 proposals dealscanner-f01942130-f02012032-22203246: Error: retrieval query for miner f02012032 failed: failed to dial 12D3KooWLBMSggvqs69icS3srwKpZTtaZAS484aQ2XsDchcAUwV2:
Feb 15 15:25:30 proposals dealscanner-f01942130-f02012032-22203246:   * [/ip4/162.219.38.94/tcp/18762] failed to negotiate stream multiplexer: EOF
Feb 15 15:25:30 proposals dealscanner-f01942130-f02012032-22289736: Error: retrieval query for miner f02012032 failed: failed to dial 12D3KooWLBMSggvqs69icS3srwKpZTtaZAS484aQ2XsDchcAUwV2:
Feb 15 15:25:30 proposals dealscanner-f01942130-f02012032-22289736:   * [/ip4/162.219.38.94/tcp/18762] failed to negotiate stream multiplexer: read tcp4 212.6.53.183:34775->162.219.38.94:18762: read: connection reset by peer
Feb 15 15:25:30 proposals dealscanner-f01942130-f02012032-22201556: Error: retrieval query for miner f02012032 failed: failed to dial 12D3KooWLBMSggvqs69icS3srwKpZTtaZAS484aQ2XsDchcAUwV2:
Feb 15 15:25:30 proposals dealscanner-f01942130-f02012032-22201556:   * [/ip4/162.219.38.94/tcp/18762] failed to negotiate stream multiplexer: read tcp4 212.6.53.183:44425->162.219.38.94:18762: read: connection reset by peer
Feb 15 15:25:30 proposals dealscanner-f01942130-f02012032: Error: retrieval query for miner f02012032 failed: failed to dial 12D3KooWLBMSggvqs69icS3srwKpZTtaZAS484aQ2XsDchcAUwV2:
Feb 15 15:25:30 proposals dealscanner-f01942130-f02012032:   * [/ip4/162.219.38.94/tcp/18762] failed to negotiate stream multiplexer: read tcp4 212.6.53.183:33321->162.219.38.94:18762: read: connection reset by peer
Feb 15 15:25:30 proposals dealscanner-f01942130-f02012032: Error: retrieval query for miner f02012032 failed: failed to dial 12D3KooWLBMSggvqs69icS3srwKpZTtaZAS484aQ2XsDchcAUwV2:
Feb 15 15:25:30 proposals dealscanner-f01942130-f02012032:   * [/ip4/162.219.38.94/tcp/18762] failed to negotiate stream multiplexer: read tcp4 212.6.53.183:41663->162.219.38.94:18762: read: connection reset by peer

The retrieval function is still not working.

https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1127#issuecomment-1429294202

**Comment by yuwenhui** [comment]
> @yuwenhui Can you give me more information about the current SP's you are storing with? Their business name, region and city?

Hello, @herrehesse Thanks for your check on my LDN application. Current SP's information as following:

f01824405  ChengDu, CN      -    RY
f01991416   HongKong, CN    -    RIKIMARU
f02012032  HongKong, CN    -    RIKIMARU
f02006691  HongKong, CN    -    NIHICHE
f02014107   Seoul, KR             -    HMT

**Comment by cryptowhizzard** [comment]
Good morning. Retrieval is still not working. Can you have this fixed please?

**Comment by yuwenhui** [comment]
> Good morning. Retrieval is still not working. Can you have this fixed please?

Hello, the retrieval problem has been fixed, now it is works well, please take a look.

**Comment by yuwenhui** [comment]
checker:manualTrigger

**Comment by data-programs** [comment]
<img width="32" alt="KYC" Verified src="https://stable.filplus.storage/images/filplus-kyc-verified-badge.png"/>

This user’s identity has been verified through [filplus.storage](https://filplus.storage)
