### ISSUE TITLE
[DataCap Application] <GANADAIO CO.,LTD> 

### ISSUE THREAD

**Issue by Ganadaioly** [filecoin-project/filecoin-plus-large-datasets#1128]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: GANADAIO CO.,LTD
- Website / Social Media: http://www.ganadaio.net/ja-JP/case
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5 PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100 TiB
- On-chain address for first allocation: f1pvqt754w3r6djygzmx4iqsiksr2p7qrvtpbpn5q

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
GANADAIO CO., LTD (hereinafter abbreviated as GND) is a comprehensive system company engaged in FinTech application and software development. Our core business is to provide complete set services of FinTech technology and application solutions and software development services to traditional enterprises around the world, and provide FinTech technology and application consulting services to governments and industry authorities. At the same time, the GND will take full advantage of the cooperation advantages of China, Japan and South Korea to form a market of high-tech products and product interoperability, thereby forming comprehensive development advantages. 

Founded in 2020 in Japan, GND established financial technology companies in Guiyang and Hainan, China, and then set up a subsidiary in Hong Kong. We work with strong companies from various industries in Japan to jointly create archetypal cases for financial technology applications. Cooperating with Japanese government agencies and leveraging the experience of cooperation with Guiyang government in China, we provide the government with typical solutions of financial technology for government, commercial and private use.

On November 29, 2018, the attention-grabbing “Golden Stone Project Japan Press Conference” was held on the 28th floor of Tokyo Garden Terrace Kiimachi at 14:30 local time. The implementation plan for the world's first culture and health industry based on blockchain technology has been officially launched. In a homely atmosphere, guests from different countries experienced the fusion scene of Eastern cultural temperament and blockchain sentiment.
```

What is the primary source of funding for this project?
```
Company revenue.
```

What other projects/ecosystem stakeholders is this project associated with?
```
No other projects.
```

## Use-case details

Describe the data being stored onto Filecoin
```
User data, advance analytics data, financial data, financial applications data, identity management data, Fintech online courses, finance, technology, blockchain education data, etc.
```

Where was the data in this dataset sourced from?
```
The data comes from the following:
1.generated during the operation of our business;
2.videos recorded by our internal team and research institutions we cooperate with;
3.Fintech webinars we were invited to;
4.public university projects related with fintech data, ML, public data
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://drive.google.com/drive/folders/1LlWZzRxToG_pUpJvJWhGB7gR9GKi7Jti?usp=sharing
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Confirmed.
```

What is the expected retrieval frequency for this data?
```
Probably twice a year, which is expected to gradually increase as we store more data on the network and get more users engaged in our project.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
We intend to store this content permanently on Filecoin so that we can accumulate our data base to develop accurate algorithms. 
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
We plan to make deals in Asia, mainly in Japan, China and Korea.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Primarily online transfer, and we’ll use offline transfer process as well is there is bandwidth limitation. We’ll focus on geographic diversity per deal (redundant storage across locations). 
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We’ll attach importance to the following factors while choosing storage providers:
reputation in the network
storage efficiency
location
transmission speed
deal success rate
nodes stability
```

How will you be distributing deals across storage providers?
```
We intend to distribute deals to more than 4 SPs and ensure that each receives less than 30% of the DataCap allocated.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes.
```

**Comment by Ganadaioly** [comment]
@raghavrmadya @simonkim0515 Hi is there any way to speed up the KYC process please? It's been a month and we haven't got reply. Thanks for your support!

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 100TiB

**Client address**

> f1pvqt754w3r6djygzmx4iqsiksr2p7qrvtpbpn5q

**Comment by Defil2022** [comment]
> User data, advance analytics data, financial data, financial applications data, identity management data, Fintech online courses, finance, technology, blockchain education data, etc.
Does the financial data can be public to everyone?

**Comment by Ganadaioly** [comment]
Hi @Defil2022 
Our financial data is public to everyone as it is the prerequisite for joining the Filecoin network. We plan to store this data permanently on Filecoin so that we can accumulate our data base to develop out algorithms and provide better products and services to our customers.

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Looking at your application i have some questions:
As you are brand new on Github and have no history of past applications it seems to me that applying for 5PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?

Can you show us visible proof of the size of your data and the storage systems you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230232885049356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!

**Comment by Ganadaioly** [comment]
@cryptowhizzard 
1. Hi we are new to the Filecoin Plus but we are aware of the development of IPFS and decentralized storage as a comprehensive system company engaged in FinTech application and software development. We provide FinTech technology and application consulting services for government, commercial and private use.

2. We have a huge data storage demand ranging from user data, advance analytics data, financial data, financial applications data, identity management data, Fintech online courses, finance, technology, blockchain education data, etc. We are using cloud storage which is normally a cost-effective choice. Uncertainties about privacy and security on the cloud are the next significant point to be made in relation to the drawbacks of cloud storage. Filecoin offers secure and cost-effective options for us as data is stored decentralized on IPFS and Filecoin.

3. Complete
If you have any further doubts, please feel free to ask. Thanks!

**Comment by cryptowhizzard** [comment]
Thanks for completing KYC.

There are 2 fields that you left open on the KYC form. I need that information before i can sign on your application.

You indicated that you are the data preparer and owner of the dataset. Can you confirm you don't have any stake in SP's you are going to send this data to? As stated in the form I am allowing 1 replica of the set to be stored on your own miners. That's the reason i ask.

Second:

As the form states _> RULES: In order to be eligible for the Filecoin+ incentive program, which provides 10x the power (QAP) for storing data on the Filecoin network, there are certain rules that must be followed:

Data must be stored with multiple independent service providers, not just one organization running multiple SPs.
Data must be distributed across multiple regions. Using a VPN to fake presence is not allowed.
Data must be publicly retrievable for verification that it is being stored as claimed. It is highly recommended to run boost.
Data must align with the mission of FIL+, meaning it must be valuable for humanity, whether scientific or unique in some other way.
Data must be open and not encrypted. If you wish to encrypt your data, consider applying for the FIL-E program instead.
Note: As a data preparer, you are allowed to store one copy yourself for redundancy at the request of the client. However, if your copy is stored in the USA, the other organizations/SPs must be outside your region. Dcent encourages applications with a minimum spread of 2 continents and 3 different organizations.

Can you provide me with the Sp's and their contact information?

Thanks!

**Comment by Sunnyiscoming** [comment]
Hi @Ganadaioly 
If you still want to apply for datacap, you can ask more notaries to do client due diligence and approve the application in slack channel. https://app.slack.com/client/TEHTVS1L6/C036JKD8NVA/thread/C03BG1MNQ4T-1673888660.823499

**Comment by Ganadaioly** [comment]
@cryptowhizzard Hi
1. I confirm we don’t have any stake in SP's we are going to send this data to.
2. We’re collecting the contact information of SPs we are going to collaborate with, which might take a few days.

Thanks!
