### ISSUE TITLE
[DataCap Application] <FavorLabs> - <FavorTube>

### ISSUE THREAD

**Issue by plotozhu** [filecoin-project/filecoin-plus-large-datasets#1129]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: FavorLabs LLC
- Website/Social Media:  https://www.favorlabs.io/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):  5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):100TiB
- On-chain address for first allocation: f1wef2oislvt4ezv6thm4rhaeo6giju52z6opsmzy

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

### FavorChain
- In past years, Favorlabs are engaged in researching and developing the fully decentralized web 3 protocol stack and brought together:  
  

  1. A decentralised high performance, low cost **blockchain**
   2. A decentralised **storage system**
   3. A decentralised **content distribution system**
   4. A decentralised **database**

And built a robust infrastructure, called FavorChain. 

### FavorTube
To prove that it can work, we built an app on top of it - **FavorTube**. The world's first fully decentralised Web3 Video Content Platform where: 
 * HD videos are retrieved and played via full P2P network in real time
 * Public protocol stacks enable processing of all economic activities on chain (incentives, etc) 
 * It’s NFT empowered to provide multiple revenue model for each stake holders
 
##### Key benefits 
* Users have full ownership of data
* It’s anti- account blocking
* Transparent and fair profit distribution
* Accessible by anyone in the world 

![ ](https://www.favorlabs.io/wp-content/uploads/2022/10/FavorTube-File-Source-182x300.png)

##### Key Business Model and Activies 
* In-app Purchase via Fiat supported
> Users subcribe to private channels using **Fiat or FavT**.

* X to Earn FavT
>  X = Create, Watch, Share, Service, Stake, Buy processed by different roles in system

* Empowered by NFT
> Creators can do Crowdfunding using NFTs
>  Profits are distributed to NFT holders.
![ ](https://www.favorlabs.io/wp-content/uploads/2022/10/FavorTube-Payment-182x300.png)

What is the primary source of funding for this project?
```
Self Funded
```

What other projects/ecosystem stakeholders is this project associated with?
```
N.A. 
```

## Use-case details

Describe the data being stored onto Filecoin

The content creators upload video files into FavorTube, and FavorTube will store them into Filecoin as backups. 
With a decentralized content distribution network, clients in FavorTube can retrieve video data to play from Filecoin Nodes by relay nodes.
All relay nodes have cache buffer and can cache relayed for a period of time, in which to provide the video file to client repeatly without retrieve from source Filecoin nodes.

![](https://www.favorlabs.io/wp-content/uploads/2022/10/system-overview-300x174.png)

Where was the data in this dataset sourced from?
```
User created and censored by DAO
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
![](https://www.favorlabs.io/wp-content/uploads/2022/10/Introductions-300x135.jpg)
 [common animated video](https://share.favorlabs.io/share/6350c7b873096be8ccf17618) 

![](https://www.favorlabs.io/wp-content/uploads/2022/10/Delphi4K-300x159.jpg)
[Delphi with in 4K ULTRA HD 60FPS by Drone ]
(https://share.favorlabs.io/share/6352403580038ae8cb85d0cc)
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes, Anyon can access the data
```

What is the expected retrieval frequency for this data?
```
First read about 5-10 times, and will be only read when the data in caches of relay nodes expired. 
```

For how long do you plan to keep this dataset stored on Filecoin?
```
Permanently
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Singapore
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Yes
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
With its bandwith, especially file transfer time.
```

How will you be distributing deals across storage providers?
```
Please answer here.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Please answer here.
```

**Comment by plotozhu** [comment]
I have correct the errors inside.

**Comment by raghavrmadya** [comment]
Parts of the application are incomplete. Please complete the application and submit again

**Comment by AidenZuk** [comment]
> Parts of the application are incomplete. Please complete the application and submit again

Hi, Thanks for your comment. It is not very clear for us. would it be possible to point out which parts should be complete?
