### ISSUE TITLE
[DataCap Application] Digital Earth Africa Water Observations from Space

### ISSUE THREAD

**Issue by Pierofree** [filecoin-project/filecoin-plus-large-datasets#1130]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Digital Earth Africa Water Observations from Space---Piero
- Website / Social Media: https://registry.opendata.aws/deafrica-wofs/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):100TiB
- On-chain address for first allocation:f1copg5qrg6js7rlz6dlvqbyqfcdgzllnt5vx5rsq

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
I have participated in hackathon projects and got a very good ranking.
```

What is the primary source of funding for this project?
```
By myself.
```

What other projects/ecosystem stakeholders is this project associated with?
```
No.
```

## Use-case details

Describe the data being stored onto Filecoin
```
Water Observations from Space (WOfS) is a service that draws on satellite imagery to provide historical surface water observations of the whole African continent, including scene-level data and annual or all time summaries.
```

Where was the data in this dataset sourced from?
```
They are generated using the WOfS classification algorithm on Landsat satellite data.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://registry.opendata.aws/deafrica-wofs/
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Confirm.
```

What is the expected retrieval frequency for this data?
```
Minimally, at least every six months.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
540 days.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Asia, North America, Europe.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Both online and offline data transfer.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
I will send deals to those storage providers who have ability to support retrieval and stable seal.
```

How will you be distributing deals across storage providers?
```
I will distribute under 25% deals to every storage provider.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes.
```

**Comment by xingjitansuo** [comment]
Thanks for applying. I have the following question :
1. How large is the dataset?  How many copies do you plan to store? 
2. Could you please elaborate more on the hackathon you participated in before to increase your credential?

**Comment by Pierofree** [comment]
@xingjitansuo Thank you for your question!

It is a large dataset which we have been working very hard to download for more than a few months, current size of the it is about 355TiB, and I plan to find 8-10 SPs to store copies.

No problem! These are the live pictures from the hackathon took by us, we are lucky and happy to get the good ranking. 
![92](https://user-images.githubusercontent.com/107857921/198256178-ff0f1fe7-443c-4b4a-bf1a-2dbda2b82bc8.png)
![89](https://user-images.githubusercontent.com/107857921/198255207-ca299661-f890-44c9-953d-b1ee89503067.png)


I'm eager to get approval from community and I am looking forward to participating in the Filecoin community. I love it!

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 100TiB

**Client address**

>f1copg5qrg6js7rlz6dlvqbyqfcdgzllnt5vx5rsq

**Comment by BlockMakeronline** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecb3bxflgw5eqkp7yzq5uxt7qvnsm2zkbwdwzhuaui3turhuthzya 
#### Address 
> f1copg5qrg6js7rlz6dlvqbyqfcdgzllnt5vx5rsq
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1o3twrcpwjtpcd4q36lpq4qmy2qfbgtyy5h6tsty
#### Id
> 82279376-4555-4dcb-94a8-cb39f3fd34f4
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecb3bxflgw5eqkp7yzq5uxt7qvnsm2zkbwdwzhuaui3turhuthzya

**Comment by BDEio** [comment]
@Pierofree Hi! Great to see that you have gotten approval for DataCap!
BDE is a verified deals auction house helping you to get paid storing your valuable data with reliable storage providers. If you need any help, we are always here for you！

**Comment by UnionLabs2020** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceakhobslv5qbpnm6vd4mpbfbxqfbmmiznbyao6li26ymsauxxyndk 
#### Address 
> f1copg5qrg6js7rlz6dlvqbyqfcdgzllnt5vx5rsq
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f17xdri3wunqgld7dm23e4f3eqsntjakwc47xjo6i
#### Id
> 7778acd2-e8a2-491e-9a29-8f2844013bc9
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceakhobslv5qbpnm6vd4mpbfbxqfbmmiznbyao6li26ymsauxxyndk

**Comment by UnionLabs2020** [comment]
Please check the connectivity of nodes @Pierofree

**Comment by cryptowhizzard** [comment]
@UnionLabs2020 

You have signed of here on an applicant who has been in very much trouble in the past. I strongly recommend that you revoke your signature immediately.

https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1338#issuecomment-1372185795

https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1112

As you can see other notary's are also in trouble over signing this.

**Comment by MetaWaveInfo** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacea4tuckesz3nmr44ncyhy7itidabc4mompnyesk76h2jwz2sizmwm 
#### Address 
> f1copg5qrg6js7rlz6dlvqbyqfcdgzllnt5vx5rsq
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1ktlkcxnmzxcdaoqfsunrg3vocfbmgv4n3mrn74a
#### Id
> 7778acd2-e8a2-491e-9a29-8f2844013bc9
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacea4tuckesz3nmr44ncyhy7itidabc4mompnyesk76h2jwz2sizmwm

**Comment by herrehesse** [comment]
Both @UnionLabs2020 and @MetaWaveInfo Signed this problematic application from a known bad actor without due diligence and should be put on "disputed" status right away. This behaviour is unacceptable.

Tagging for visibility: @simonkim0515 @galen-mcandrew @dkkapur @raghavrmadya

**Comment by raghavrmadya** [comment]
This application was flagged on the T&T WG call today. For specifics on what the flags were, please refer to the comments above as well as this recording - https://protocol.zoom.us/rec/share/ddNjjWp4rZ5LBh3UdHkneGs9R23NLv-F3nKLteIje6eWZpbA1Uy3xvsPcBoXl7z1.ukOgWhKSNiCZOvcj
Passcode: 0Kwi+cnU

**Comment by raghavrmadya** [comment]
Until the client and notaries provide a response to this flag, T&T WG recommends no further signing of this application

**Comment by UnionLabs2020** [comment]
In this case, I have tested that all nodes can be connected and retrieved, but the bot-checker is not normal, so I remind the client to keep the SPs stable.

Also, I want to remind the guys form Dcent to pay attention to your words, which may cause disputes in the community.
Strongly disagree with the definition of clients as "**bad actor**“. Even though he/she has operated irregularly before, we need to judge objectively and fairly in this case.

I suggest that other notaries can review this application and decide whether to sign it.

**Comment by UnionLabs2020** [comment]
In this case, I have tested that all nodes can be connected and retrieved, but the bot-checker is not normal, so I remind the client to keep the SPs stable.

Also, I want to remind the guys from Dcent to pay attention to your words, which may cause disputes in the community.
Strongly disagree with the definition of clients as "bad actor“. Even though he/she has operated irregularly before, we need to judge objectively and fairly in this case.

I suggest that other notaries can review this application and decide whether to sign it.

**Comment by cryptowhizzard** [comment]
@UnionLabs2020 

You signed an application for an applicant who abused the FIL+ program without the applicant or you explaining where / when and why. It is bad for Filecoin and for everyone involved.

https://github.com/filecoin-project/filecoin-plus-large-datasets/issues?q=is%3Aissue+Piero

**Comment by UnionLabs2020** [comment]
@cryptowhizzard  I think you may have misunderstood the rules of FIL+. We welcome all applicants who have bad records to correct again, not to kick them out of the Filecoin community completely. @dkkapur has stressed this point many times. I think you should also study hard. This is a web3 world with an inclusive spirit, not a courtroom.

In addition, including Dcent, Kernelogic and Filswan, these active participants have had their bad records exposed. Do they all need to be banned?

**Comment by cryptowhizzard** [comment]
> @cryptowhizzard I think you may have misunderstood the rules of FIL+. We welcome all applicants who have bad records to correct again, not to kick them out of the Filecoin community completely. @dkkapur has stressed this point many times. I think you should also study hard. This is a web3 world with an inclusive spirit, not a courtroom.
> 
> In addition, including Dcent, Kernelogic and Filswan, these active participants have had their bad records exposed. Do they all need to be banned?

Ahhh … enlightening, we are making progress here.
I am happy that we agree that this applicant has a bad record as you stated. Secondly, there has been no explanations given by the applicant what went wrong? Who was the person causing this? You signed without proper explanation and due diligence? Right??

Since you keep administrative records and have a bookkeeping plan as stated in your notary application i kindly ask you to share with us who this applicant is. Can you share before Monday? It helps the process to move faster for decision making.

Thanks!

**Comment by cryptowhizzard** [comment]
To be more specific @UnionLabs2020 

https://github.com/filecoin-project/notary-governance/issues/416

This is your commitment to the community. I would like to see 1, 2 and 3 please.

I quote:

Client Due Diligence

How will you vet the clients that are applying for DataCap? What questions will you ask to ensure your trust is placed well and that clients can properly handle the DataCap you intend to allocate to them?

There will be three stages in verification process to ensure the DataCap is used properly. Moreover, the greater the amount of DataCap requested, the more restricted the client scrutiny will be. The details are as follows:
![image](https://user-images.githubusercontent.com/68763845/155881506-8a28f618-6510-4435-8729-7c26c6005f9b.png)

[1] Details include but not limited to these:
     1. Entity Information
     - Formation documents - this includes certificates of registration/incorporation/information.
     - government-issued identification number for the entity
     2. Authorized Signatory Information
     - evidence of the authorized signatory’s authority to act on behalf of the application entity
     3. Beneficial Owners(optional)
     - If there are any 25%+ shareholders, we need a document as a capitalization table, operating agreement, or something similar to verify the ownership, and also the following information for each of them:
     - legal name;
     - date of birth;
     - street address (P.O. box number is not acceptable);

[2] Punishment actions may include disqualify the applicant certification, public its wrong actions in the community, stop further allocation forever, fine the FIL pledged by the client etc. In the extreme scenario, legal option will also be taken based on the aforementioned DataCap allocation agreement.

Question for clients:
1. Introduction of yourself/ your organization(with links)
2. Use case
3. Location
4. Max DataCap Allocation
5. Filecoin address
6. Miners you intend to allocate DataCap with allocation proportion
7. Specific requirement of miners and storage service
8. For-profit or not
What processes will you employ when granting additional DataCap to a client that has previously been verified? This includes confirming that the client is not improperly using the DataCap they were previously granted, i.e., making deals with a single SP entity.

Firstly, from the questions about use plan and further investigation, I can know some details about his allocation plans. When scoring applicants according to the above sheet, the more geographical distribution, use cases and miners assign, the higher score he will get and the more datacap clients are likely to get.  
Next, we will keep tracking clients’ information such as the DataCap distribution records, related miner addresses and storage providers, to ensure that they are consistent with their words and deeds.
Finally, a reward and punishment mechanism will be established. If someone over-allocating datacap to a single entity, I will refuse further allocation and issue a warning which will be public to the Filecoin community. On the contrary, reputable client have the opportunity to obtain more datacap.
Bookkeeping Plan

Do you plan on conducting all your allocation decisions in public (e.g. Github repo), private (e.g. over email, Telegram, etc), or both?

The record of my allocation decisions will be accessible and in public(tentatively on GitHub) to be supervised by Filecoin Community.
Where do you plan on keeping a publicly accessible record of all your allocation decisions?

All allocation decisions will be open in the following website:
https://github.com/filecoin-project/filecoin-plus-client-onboarding
https://filplus.info/#/

**Comment by UnionLabs2020** [comment]
@cryptowhizzard I think you need to explain and answer carefully how @f8-ptrk questioned you before you are qualified to attack others everywhere. Very disappointed with you guys' behavior.

![image](https://user-images.githubusercontent.com/101703888/218248340-8712e105-0ba7-4e29-9b9c-2ab90fafeb7e.png)

**Comment by UnionLabs2020** [comment]
Ok,  I will ignore them later. TKS.

**Comment by herrehesse** [comment]
@UnionLabs2020 being right in the center of everything that is happening on the FIL+ front I find it astonishing that you do not try and answer the questions of @cryptowhizzard.

I would suggest you give it a try at least.

**Comment by Casey-PG** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedzjzj726q5zyv7vkbqblvdd4vpstu2qoiz2sogkprisjwdi7khig 
#### Address 
> f1copg5qrg6js7rlz6dlvqbyqfcdgzllnt5vx5rsq
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1d4yb3wags3mtddzesxoo63jv7dmlec3bq4yteni
#### Id
> 4049501a-1d15-4de7-bfe2-87a1b302aa5d
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedzjzj726q5zyv7vkbqblvdd4vpstu2qoiz2sogkprisjwdi7khig

**Comment by BobbyChoii** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecjsoahwd3qepkkkgr3r7phovd53xcw7lntiknyqwli7xnzmkul34 
#### Address 
> f1copg5qrg6js7rlz6dlvqbyqfcdgzllnt5vx5rsq
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1irqs2gmctiv3jcdfwuch7oxvf4ixh3k4b2wc24i
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecjsoahwd3qepkkkgr3r7phovd53xcw7lntiknyqwli7xnzmkul34

**Comment by TakiChain** [comment]
The client has contacted me several times and I'll sign for this allocation. But @Pierofree  you need at minimum 4 notaries to support your application for the following rounds. Please contact other noatry in the next round.

**Comment by Suyanj** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebejkvgefuam7pvlpegwlnfzwh226lclmbgq7xvcule7bzmww6c34 
#### Address 
> f1copg5qrg6js7rlz6dlvqbyqfcdgzllnt5vx5rsq
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1ihv7gz3vn3xqvikpt4rwryecgisl7745lodx3yi
#### Id
> 4049501a-1d15-4de7-bfe2-87a1b302aa5d
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebejkvgefuam7pvlpegwlnfzwh226lclmbgq7xvcule7bzmww6c34

**Comment by Suyanj** [comment]
Open datasets bring great value to the network. Happy to see more of them join Filecoin. Please keep the allocation in line with Filplus guidlines.

**Comment by AthSmith** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecs4hhiyrgi6t3linitc7z2qoa4wh4q7dpibh226bbfnti4yad3a4 
#### Address 
> f1copg5qrg6js7rlz6dlvqbyqfcdgzllnt5vx5rsq
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1vxbqrf7rfum3n6m5u6eb4re6xj7amvsaqnzu64y
#### Id
> 8b11b132-7326-4a5a-bfc7-e20cd063b48f
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecs4hhiyrgi6t3linitc7z2qoa4wh4q7dpibh226bbfnti4yad3a4

**Comment by AthSmith** [comment]
Peformed due diligence before and the report looks good. Willing to help onboard this application again.

**Comment by Casey-PG** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedleyawjdvio6iev3qumqszzcw7m57yqpp2hm3adscxcw7s6oikwk 
#### Address 
> f1copg5qrg6js7rlz6dlvqbyqfcdgzllnt5vx5rsq
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1d4yb3wags3mtddzesxoo63jv7dmlec3bq4yteni
#### Id
> 8b11b132-7326-4a5a-bfc7-e20cd063b48f
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedleyawjdvio6iev3qumqszzcw7m57yqpp2hm3adscxcw7s6oikwk

**Comment by Casey-PG** [comment]
The client followed the allocation plan. Willing to help onboard this application again.

**Comment by BobbyChoii** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec4scwoxloxtuxf7zt5gbb25clvfggcsoifp26venspnla3st45cy 
#### Address 
> f1copg5qrg6js7rlz6dlvqbyqfcdgzllnt5vx5rsq
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1irqs2gmctiv3jcdfwuch7oxvf4ixh3k4b2wc24i
#### Id
> 86372bc3-83b1-4f8c-a696-243c1c1bf815
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec4scwoxloxtuxf7zt5gbb25clvfggcsoifp26venspnla3st45cy

**Comment by Aifabot-Cloud** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced5lgalcfglzbdguqpnrbijmeqcyk6rfowdvp2yds3l5qkebbeidg 
#### Address 
> f1copg5qrg6js7rlz6dlvqbyqfcdgzllnt5vx5rsq
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f174fg3bqbln3zjnkxtyf6s54txqkr7yqkj6cig7y
#### Id
> 86372bc3-83b1-4f8c-a696-243c1c1bf815
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced5lgalcfglzbdguqpnrbijmeqcyk6rfowdvp2yds3l5qkebbeidg

**Comment by Suyanj** [comment]
checker:manualTrigger

**Comment by Suyanj** [comment]
KYC has been done,and the report is good to me.

**Comment by Suyanj** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceai5unyzgibai7un4rx7q3kohb36fvyvwwqbsxovmzqb4ep246zdq 
#### Address 
> f1copg5qrg6js7rlz6dlvqbyqfcdgzllnt5vx5rsq
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1ihv7gz3vn3xqvikpt4rwryecgisl7745lodx3yi
#### Id
> 9ec0d637-5193-4969-aff3-9731855dbd64
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceai5unyzgibai7un4rx7q3kohb36fvyvwwqbsxovmzqb4ep246zdq

**Comment by cryptowhizzard** [comment]
![Scherm­afbeelding 2023-08-04 om 14 21 38](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/36404435/3290159b-8f6a-4918-92d4-8c38796e6712)

This application does not support proper retrieval. Nothing can be downloaded and unpacked to do due diligence on so i have no way other then to dispute.

@Pierofree 

I will revoke the dispute if you can provide me with pieceCID baga6ea4seaqjhahmqmnfbfqkz774cpba2ke3vsqgeukovtib5wvc5rs4iass6ey on a link where i can download it so i can do duediligence on your data.

**Comment by cryptowhizzard** [comment]
![Scherm­afbeelding 2023-08-04 om 14 25 13](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/36404435/09e55d01-11f2-4e1c-bb7e-8e023d912f43)

**Comment by raghavrmadya** [comment]
Remove existing DC from this LDN cc @simonkim0515

**Comment by Pierofree** [comment]
@raghavrmadya Can you please tell me why you want to remove DC from my application?

**Comment by Pierofree** [comment]
I didn't find any part of the above in which I broke any community rules.
