### ISSUE TITLE
[DataCap Application] Painite - Particle physics

### ISSUE THREAD

**Issue by Kormakornchip** [filecoin-project/filecoin-plus-large-datasets#1131]
# Large Dataset Notary Application
To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
-	Organization Name: Global Computer Systems
-	Website / Social Media: global-usa.com
-	Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5 PiB
-	Weekly allocation of DataCap requested (usually between 1-100TiB): 100 TiB
-	On-chain address for first allocation: f1kwqh6k2wmbvyyp2xykin427owqygpvqiijtskoq

## Project details
Share a brief history of your project and organization
```
Founded in 1996, we are a managed service provider. We are exploring ways to process archival data for our clients. Services we provide include backup administration, managed backups, disaster recovery, cloud migration and much more. Our company also has and continues to maintain an active R&D department. We are always testing and exploring new technologies and as such the concept of distributed storage is a very exciting new space with seemingly unlimited potential.
```

What is the primary source of funding for this project?
```
Internal
```

What other projects/ecosystem stakeholders is this project associated with?
```
None
```

## Use-case details
Describe the data being stored onto Filecoin
```
Results of high energy particle collisions. Used for the study of matter and particle physics.
```

Where was the data in this dataset sourced from?
```
Various international scientific organizations operating particle accelerators 
```

Can you share a sample of the data? A link to file would work.
```
Yes. https://drive.google.com/file/d/1rgTf2PwP3yTNfXaJwok0bjgDLNep-jUf/view?usp=sharing

```

Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
I can confirm this. This is scientific data covered by the Open Data Policy
```

What is the expected retrieval frequency for this data?
```
Every 3 months on average
```

For how long do you plan to keep this dataset stored on Filecoin?
```
18 months minimum
```

## DataCap allocation plan
In which geographies (countries, regions) do you plan on making storage deals?
```
Europe, North America, Asia
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Online and offline
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We are planning to choose reputable storage providers in the community with upstanding no-fault rates. We are open to inquiring storage providers but must understand that we would only like to store with mature storage providers. 
```

How will you be distributing deals across storage providers?
```
We plan to send deals online over the internet
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?

```
Yes we have adequate resources. Will contact community if we need more support

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 100TiB

**Client address**

> f1vqqax6gyumsttpu2htuetb7exkssupftbrg4tpi

**Comment by Kormakornchip** [comment]
Could you change the allocation address to ff1kwqh6k2wmbvyyp2xykin427owqygpvqiijtskoq ? The previously specified address was created with wallet.glif.io and is valid but there does not seem to be a way to import the address into lotus daemon. I am working with the developer to try to resolve this. I am more than happy to provide more details on the issue if that helps.

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 5PiB

**Expected weekly DataCap usage rate**
> 100TiB

**Client address**
> f1kwqh6k2wmbvyyp2xykin427owqygpvqiijtskoq

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Can you show us visible proof of the size of your data and the storage systems you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230337462961356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!
