### ISSUE TITLE
[DataCap Application] Jinhua YiBo Network Technology Co.,Ltd 

### ISSUE THREAD

**Issue by jhxhj** [filecoin-project/filecoin-plus-large-datasets#1133]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Jinhua YiBo Network Technology Co.,Ltd
- Website / Social Media: website: www.jjhgame.com  
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100TiB
- On-chain address for first allocation: f1s3vgu2mdpdonfdyiyly3jeo4qwygi3xivvc6ceq

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Jinhua YiBo Network Technology Co., Ltd. was established in December 2011. It is a national high-tech enterprise specializing in the R&D and operation of pan-entertainment game platforms. It is a leading enterprise in the “No. 1 Development Project” of digital economy in Jinhua City, Zhejiang Province, China. 

The company provides users with video entertainment, mobile and PC online games and other high-quality content, aiming to create a "one-stop online entertainment service" with entertainment, social networking and user experience as the core. 

The company has 12 departments including strategic development department, technology center, R&D center, operation center, customer service center, etc., with a total of 166 employees, including more than 80 people specializing in software R&D and operation. In addition, R&D centers have been set up in Hangzhou and Shanghai, with nearly 50 people in the two centers. 

Shanda Group (Century Huatong Group), one of the largest game companies in the domestic A-shares market, invested in the company in December 2020.

In addition, the company has also been rated as the first batch of growth-oriented cultural enterprises in Zhejiang Province and the top 100 technology enterprises in Zhejiang Province.
```

What is the primary source of funding for this project?
```
Company funding.
```

What other projects/ecosystem stakeholders is this project associated with?
```
No.
```

## Use-case details

Describe the data being stored onto Filecoin
```
Surveillance video, game data, installation package, software and App configuration and deployment documents
```

Where was the data in this dataset sourced from?
```
The data comes from:
Surveillance video of the company;
Game data produced by game users;
Installation package, sofware & App configuration and deployment documents of company products.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://pan.baidu.com/s/1RYaNbAngVqcBuV4NWlN4LA
Extraction code: a63w
```
<img width="1341" alt="image" src="https://user-images.githubusercontent.com/20355333/197473054-a5d5f9c7-f313-4c4c-b6b8-2025ee2b5300.png">

        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes. These are self-produced data by YiBo Network that opens to everyone.
```

What is the expected retrieval frequency for this data?
```
Monthly.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
At least one year.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Asia, America, Europe
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
We will distribute the data to storage providers both online and offline.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
SPs with high reputation and adjusted power will be preferentially considered. 
```

How will you be distributing deals across storage providers?
```
We will find at least 5 storage providers and distribute the deals equally.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes. We have company funding for that. 
```

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 100TiB

**Client address**

> f1s3vgu2mdpdonfdyiyly3jeo4qwygi3xivvc6ceq

**Comment by Defil2022** [comment]
> The data comes from:
Surveillance video of the company;
Game data produced by game users;
Installation package, sofware & App configuration and deployment documents of company products.

Can this kind of data be made public? @jhxhj

**Comment by jhxhj** [comment]
> > The data comes from:
> > Surveillance video of the company;
> > Game data produced by game users;
> > Installation package, sofware & App configuration and deployment documents of company products.
> 
> Can this kind of data be made public? @jhxhj

@jhxhj yes, these data can be public

**Comment by IreneYoung** [comment]
What's the relationship between you and the organization? 
And your website (http://www.jjhgame.com/) is unavailable.

**Comment by kernelogic** [comment]
Cannot access your website. Also please provide screenshot or video indicating you have the 500T data at least.

**Comment by jhxhj** [comment]
> What's the relationship between you and the organization? And your website (http://www.jjhgame.com/) is unavailable.

@IreneYoung Hi, I'm Xiang Huajian, the Technical Director of the company. Actually, the website can be accessed.
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/20355333/206656673-0bb91a3b-0cde-42b2-ba1c-9846cf5b216e.png">
<img width="1263" alt="image" src="https://user-images.githubusercontent.com/20355333/206658380-13b24a87-7bef-48ba-8f93-93e0518341d6.png">

**Comment by IreneYoung** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecwcwzmxvi5b3vhdmiutdtalitsvy7uyi4zqxuvn564vgj4btcsje 
#### Address 
> f1s3vgu2mdpdonfdyiyly3jeo4qwygi3xivvc6ceq
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1d4gmpqz3execjj2wvrxuuhvbms5mzh7t7yqrviq
#### Id
> 85b105e1-2204-462c-9d91-d41ce29f2247
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecwcwzmxvi5b3vhdmiutdtalitsvy7uyi4zqxuvn564vgj4btcsje

**Comment by flyworker** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceauc23g3kwpzvaqt5dwcrlk6dihw7dt5k2n7f3i2r7qgx4z4roshe 
#### Address 
> f1s3vgu2mdpdonfdyiyly3jeo4qwygi3xivvc6ceq
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1hlubjsdkv4wmsdadihloxgwrz3j3ernf6i3cbpy
#### Id
> 85b105e1-2204-462c-9d91-d41ce29f2247
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceauc23g3kwpzvaqt5dwcrlk6dihw7dt5k2n7f3i2r7qgx4z4roshe

**Comment by kernelogic** [comment]
I tried two retrievals, one success and one failure, given it is the first round of allocation, willing to support and see about the next round.


lotus client retrieve --maxPrice 0.01 --miner f01947280 QmVWLiVaDg9ndnzuBD8JGQpeMN1FN7yvRuc7GTYpsK3He9 /tmp/abcd
Recv 0 B, Paid 0 FIL, Open (New), 0s [1674974700925677396|0]
Recv 0 B, Paid 0 FIL, DealProposed (WaitForAcceptance), 40ms [1674974700925677396|0]
Recv 0 B, Paid 0 FIL, DealAccepted (Accepted), 311ms [1674974700925677396|0]
Recv 0 B, Paid 0 FIL, PaymentChannelSkip (Ongoing), 322ms [1674974700925677396|0]
Recv 68 B, Paid 0 FIL, BlocksReceived (Ongoing), 375ms [1674974700925677396|68]
Recv 956 B, Paid 0 FIL, BlocksReceived (Ongoing), 414ms [1674974700925677396|956]
Recv 48.94 KiB, Paid 0 FIL, BlocksReceived (Ongoing), 768ms [1674974700925677396|50119]
Recv 1.048 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 12.748s [1674974700925677396|1098709]
Recv 2.048 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 27.937s [1674974700925677396|2147299]
Recv 3.048 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 41.409s [1674974700925677396|3195889]

lotus client retrieve --maxPrice 0.01 --miner f01955030 Qmce7VovC9tdmKdYaNWMtQWy9dXTezMk29RmibPPaK6JWG /tmp/
2023-02-03T04:56:37.061Z        WARN    rpc     go-jsonrpc@v0.1.8/client.go:548 unmarshaling failed     {"message": "{\"Err\":\"exhausted 5 attempts but failed to open stream, err: failed to dial 12D3KooWKasnLcu9myNNhyJA2Qrqw514yvZE6JUQm6kNb4Stou1n:\\n  * [/ip4/117.147.188.84/tcp/11865] dial backoff\",\"Root\":null,\"Piece\":null,\"Size\":0,\"MinPrice\":\"\\u003cnil\\u003e\",\"UnsealPrice\":\"\\u003cnil\\u003e\",\"PricePerByte\":\"\\u003cnil\\u003e\",\"PaymentInterval\":0,\"PaymentIntervalIncrease\":0,\"Miner\":\"f01955030\",\"MinerPeer\":{\"Address\":\"f01955030\",\"ID\":\"12D3KooWKasnLcu9myNNhyJA2Qrqw514yvZE6JUQm6kNb4Stou1n\",\"PieceCID\":null}}"}

**Comment by kernelogic** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaetz2oqsjmllekhvizm7e54c6c6wn6mvq2cmir2xlqg4fqemoyrc 
#### Address 
> f1s3vgu2mdpdonfdyiyly3jeo4qwygi3xivvc6ceq
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### Id
> 8110a6b9-afc1-4e9a-a127-913ac9b4567c
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaetz2oqsjmllekhvizm7e54c6c6wn6mvq2cmir2xlqg4fqemoyrc

**Comment by liyunzhi-666** [comment]
checker:manualTrigger

**Comment by liyunzhi-666** [comment]
According to the CID checker:
No CID sharing.
SPs are geographically dispersed.
The number of SPs is large.
And I did some retrieval requests for SPs. It shows normal. I am willing to support this round.
![6d29543f758fcbd060640a9ba07aaa1](https://user-images.githubusercontent.com/52949274/217474013-5b3dc309-c15d-49dc-850d-811f1cef8951.png)
![90588e01e3c78435dd4037f8cb0af45](https://user-images.githubusercontent.com/52949274/217474071-6387ab1d-bb8e-4bea-91fc-3f1ee41d119b.png)
![24762100a67457adf6fb7730d08e00f](https://user-images.githubusercontent.com/52949274/217474062-e9f71382-f876-4c15-b758-dcc15c21020a.png)

**Comment by liyunzhi-666** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceagdjsmrdza2i2pl6wcqilplkn6ejppwnfdwcyssvbqmldlz46bek 
#### Address 
> f1s3vgu2mdpdonfdyiyly3jeo4qwygi3xivvc6ceq
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1pszcrsciyixyuxxukkvtazcokexbn54amf7gvoq
#### Id
> 8110a6b9-afc1-4e9a-a127-913ac9b4567c
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceagdjsmrdza2i2pl6wcqilplkn6ejppwnfdwcyssvbqmldlz46bek

**Comment by cryptowhizzard** [comment]
Hi 

> f01992623 -> Try increasing maxPrice

Any reason why you are not following the Fil+ rules with these SP's?

**Comment by Normalnoise** [comment]
checker:manualTrigger

**Comment by Normalnoise** [comment]
I retrieve the data from the random miner, it works well. cid checker is healthy.

<img width="922" alt="image" src="https://user-images.githubusercontent.com/102578774/230597802-ca0645ea-e359-47e6-94c3-0ddb1a4d1426.png">
<img width="930" alt="image" src="https://user-images.githubusercontent.com/102578774/230599685-ccedb7d3-fffc-4093-a7b7-e7d5f3977de5.png">

**Comment by Normalnoise** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedquqdbxo3cki4aowi6xsov6bwyjbhalm6qr5djweiiiuy7jfhenm 
#### Address 
> f1s3vgu2mdpdonfdyiyly3jeo4qwygi3xivvc6ceq
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1c5non5yf35avgcpsqvxu4yj54yyvxorwyjochqq
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedquqdbxo3cki4aowi6xsov6bwyjbhalm6qr5djweiiiuy7jfhenm

**Comment by nj-steve** [comment]
checker:manualTrigger

**Comment by nj-steve** [comment]
lotus client retrieve --provider f02017390 QmPYiYA4roRje6siDBvGu19pbYeSs1f93RypXzFzwFeMjG yibo.txtå
Recv 0 B, Paid 0 FIL, Open (New), 5ms [1678697507252112815|0]
Recv 0 B, Paid 0 FIL, DealProposed (WaitForAcceptance), 13ms [1678697507252112815|0]
Recv 0 B, Paid 0 FIL, DealAccepted (Accepted), 1.257s [1678697507252112815|0]
Recv 0 B, Paid 0 FIL, PaymentChannelSkip (Ongoing), 1.257s [1678697507252112815|0]
Recv 79 B, Paid 0 FIL, BlocksReceived (Ongoing), 1.28s [1678697507252112815|79]
Recv 3.483 KiB, Paid 0 FIL, BlocksReceived (Ongoing), 1.287s [1678697507252112815|3567]
Recv 23.13 KiB, Paid 0 FIL, BlocksReceived (Ongoing), 1.6s [1678697507252112815|23690]
Recv 1.023 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 7.13s [1678697507252112815|1072280]
Recv 2.023 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 9.319s [1678697507252112815|2120870]
Recv 3.023 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 11.886s [1678697507252112815|3169460]
Recv 4.023 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 14.476s [1678697507252112815|4218050]
Recv 5.023 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 16.977s [1678697507252112815|5266640]
Recv 6.023 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 19.175s [1678697507252112815|6315230]
Recv 7.023 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 21.104s [1678697507252112815|7363820]
Recv 8.023 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 23.037s [1678697507252112815|8412410]
Recv 9.023 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 24.981s [1678697507252112815|9461000]
Recv 10.02 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 26.901s [1678697507252112815|10509590]
Recv 11.02 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 28.831s [1678697507252112815|11558180]
Recv 12.02 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 31.032s [1678697507252112815|12606770]
Recv 13.02 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 33.469s [1678697507252112815|13655360]
Recv 14.02 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 35.944s [1678697507252112815|14703950]
Recv 15.02 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 38s [1678697507252112815|15752540]
Recv 16.02 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 40.36s [1678697507252112815|16801130]
Recv 17.02 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 42.413s [1678697507252112815|17849720]
Recv 18.02 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 44.054s [1678697507252112815|18898310]
Recv 19.02 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 45.772s [1678697507252112815|19946900]
Recv 20.02 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 47.06s [1678697507252112815|20995490]
Recv 21.02 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 48.422s [1678697507252112815|22044080]
Recv 22.02 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 50.133s [1678697507252112815|23092670]
Recv 23.02 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 51.629s [1678697507252112815|24141260]
Recv 24.02 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 52.745s [1678697507252112815|25189850]
Recv 25.02 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 54.104s [1678697507252112815|26238440]
Recv 26.02 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 55.775s [1678697507252112815|27287030]
Recv 27.02 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 57.965s [1678697507252112815|28335620]
Recv 28.02 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 59.764s [1678697507252112815|29384210]

the report and the retrieve look good.
