### ISSUE TITLE
[DataCap Application] FogMeta Lab - store BNB Chain snapshots

### ISSUE THREAD

**Issue by hengdingy** [filecoin-project/filecoin-plus-large-datasets#1136]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: FogMeta Lab
- Website / Social Media: https://fogmeta.com, http://rebuilder.fogmeta.com/ 
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 3 PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100 TiB
- On-chain address for first allocation: f1x4jjrsot2gevrxiqwgzgjh7kzh6c6kv3kkuyv6a

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
FogMeta Lab's research spans multiple levels from system technology, infrastructure, and middleware to services and solutions, and involves future systems, network technology and business, distributed systems and management, information management, and interactive and innovative services. Based on the views on and practices in the industry, FogMeta also solves the problem of business complexity through operations optimization and other technologies.
'filecoin-ipfs-data-rebuilder' is a project of FogMeta, a data build-and-rebuild tool between the IPFS network and the Filecoin network. Rebuilder ensures a permanent storage of at least a cold & hot backup and makes data retrievable at any time.
```

What is the primary source of funding for this project?
```
FogMeta Lab.
```

What other projects/ecosystem stakeholders is this project associated with?
```
No.
```

## Use-case details

Describe the data being stored onto Filecoin
```
Full node snapshots of the BNB chain data updated each week.
```

Where was the data in this dataset sourced from?
```
The snapshots are maintained by the BNB team and are updated about once a week. Please refer to the link here: 
https://docs.bnbchain.org/docs/validator/snapshot/
https://github.com/bnb-chain/bsc-snapshots
Moreover, we're also running BNB Chain nodes and will export a snapshot every month.  
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
geth-20221021-not-fastnode: https://pub-10cd0733ed3540f1a5bd893cdcaf4027.r2.dev/geth-20221021-not-fastnode.tar.lz4
https://docs.bnbchain.org/docs/validator/snapshot/
Latest Snapshot: https://pub-10cd0733ed3540f1a5bd893cdcaf4027.r2.dev/geth-20221021-not-fastnode.tar.lz4
2021-04-17 snapshot: https://binance-smart-chain-snapshot.s3.amazonaws.com/snap.tar.gz
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes, it's a public dataset.
```

What is the expected retrieval frequency for this data?
```
3 to 5 times a month.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
At least 500 days.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Preferably in all continents.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
The data will be sent to storage providers, and be uploaded to the web server or IPFS for storage providers to download.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We will use the FilSwan platform to distribute these data. The Market Matcher, a module of the platform, will choose the most suitable storage providers for us automatically and make sure that the data can be retrieved in the future.
```

How will you be distributing deals across storage providers?
```
We are using FilSwan client agent for batch sending deals.  https://github.com/filswan/swan-client
FilSwan has a reputation module called Swan reputation system (https://docs.filswan.com/filswan-platform/overview/reputation-system) to give storage providers scores for the data storage behavior, it based on Time-based Reachability + Regional Weighted Adjusted Power + General Deals and Verified-Storage Provider Deals

FilSwan Auction System will match the storage providers based on reputation and coditions. For the bidding policy you can find it here: https://docs.filswan.com/filswan-platform/overview/filswan-auction-system.

Some of the storage providers are as follows:
f0143858
f03624
f010088
f02301
f0187709
f01402814
f01859603
f01133080
f01858429
f01398391
f01072221
f0240185
f01390330
f01784458
f01840390
f01870135
f0520660
f01871352
f01883179
f01886797
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes. FogMeta Lab will fund the project.
```

**Comment by kernelogic** [comment]
Are you planning to store it incrementally or a complete snapshot every once a while? What's the retrieval scheme?

**Comment by hengdingy** [comment]
> Are you planning to store it incrementally or a complete snapshot every once a while? What's the retrieval scheme?

@kernelogic thanks for your question. There is a similar question with yours, we have introduced our retrieval scheme, please check [here](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1137#issuecomment-1310085569) 

We will use the [Swan Client](https://github.com/filswan/go-swan-client) to send deals. Storage providers who accepted the deals will be requested to support the fast retrieval of files. The Market Matcher based on the [Reputation System](https://console.filswan.com/#/methodology) of FilSwan can help us find suitable storage providers. Please refer to the introduction of the system [here](https://console.filswan.com/#/methodology).

**Our Retrieval Scheme**
We have designed a complete retrieval scheme for that. All the information about the snapshots will be maintained in our GitHub repository [chainsnap](https://github.com/FogMeta/chainsnap), mainly including the name of each snapshot, the download url, snapshot metadata, deal metadata, etc., and all the deal metadata will be minted into NFTs through [multichain.storage](https://www.multichain.storage). The minted NFTs can be viewed on OpenSea.

If the user wants to get the complete snapshot, the specific retrieval steps are:
- Download the deal metadata and get the storage provider IDs that store each piece;
- Obtain all pieces of the snapshot through the [lotus retrieval function](https://lotus.filecoin.io/tutorials/lotus/store-and-retrieve/retrieve-data/#send-a-retrieval-request);
- Merge all pieces to get the original snapshot
 
At present, we have completed the data storage of part of the Filecoin and Polygon snapshots. For details, please refer to the link [here](https://github.com/FogMeta/chainsnap).

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 3PiB

**Expected weekly DataCap usage rate**

> 100TiB

**Client address**

> f1x4jjrsot2gevrxiqwgzgjh7kzh6c6kv3kkuyv6a

**Comment by filplus-checker** [comment]
## DataCap and CID Checker Report[^1]
 - Organization: `FogMeta Lab`
 - Client: `f1x4jjrsot2gevrxiqwgzgjh7kzh6c6kv3kkuyv6a`
### Storage Provider Distribution
The below table shows the distribution of storage providers that have stored data for this client.

If this is the first time a provider takes verified deal, it will be marked as `new`.

For most of the datacap application, below restrictions should apply.
 - Storage provider should not exceed 25% of total datacap.
 - Storage provider should not be storing duplicate data for more than 20%.
 - Storage provider should have published its public IP address.
 - All storage providers should be located in different regions.

✔️ Storage provider distribution looks healthy.

| Provider                                              |                        Location | Total Deals Sealed | Percentage | Unique Data | Duplicate Deals |
| :---------------------------------------------------- | ------------------------------: | -----------------: | ---------: | ----------: | --------------: |
| [f0717969](https://filfox.info/en/address/f0717969)   |     Los Angeles, California, US |           3.51 TiB |      9.37% |    3.07 TiB |          12.46% |
| [f01222595](https://filfox.info/en/address/f01222595) |              Moscow, Moscow, RU |           3.45 TiB |      9.21% |    2.89 TiB |          16.29% |
| [f03624](https://filfox.info/en/address/f03624)       |           Nürnberg, Bavaria, DE |           3.23 TiB |      8.63% |    2.80 TiB |          13.53% |
| [f0187709](https://filfox.info/en/address/f0187709)   |              Moscow, Moscow, RU |           3.01 TiB |      8.02% |    2.50 TiB |          16.75% |
| [f01886797](https://filfox.info/en/address/f01886797) | Vancouver, British Columbia, CA |           2.98 TiB |      7.94% |    2.54 TiB |          14.70% |
| [f01163272](https://filfox.info/en/address/f01163272) |             Perm, Perm Krai, RU |           2.91 TiB |      7.75% |    2.38 TiB |          18.28% |
| [f01072221](https://filfox.info/en/address/f01072221) |     Los Angeles, California, US |           2.72 TiB |      7.25% |    2.25 TiB |          17.24% |
| [f01896422](https://filfox.info/en/address/f01896422) |         Fremont, California, US |           2.69 TiB |      7.17% |    2.25 TiB |          16.28% |
| [f01871352](https://filfox.info/en/address/f01871352) |                Seoul, Seoul, KR |           2.54 TiB |      6.77% |    2.23 TiB |          12.31% |
| [f010088](https://filfox.info/en/address/f010088)     |         Everett, Washington, US |           2.19 TiB |      5.84% |    2.00 TiB |           8.57% |
| [f0240456](https://filfox.info/en/address/f0240456)   |            Chengdu, Sichuan, CN |           1.85 TiB |      4.93% |    1.82 TiB |           1.69% |
| [f01402814](https://filfox.info/en/address/f01402814) |        Singapore, Singapore, SG |           1.79 TiB |      4.77% |    1.51 TiB |          15.72% |
| [f08399](https://filfox.info/en/address/f08399)       |         Seattle, Washington, US |           1.56 TiB |      4.17% |    1.34 TiB |          14.00% |
| [f01390330](https://filfox.info/en/address/f01390330) |              Xi’an, Shaanxi, CN |           1.31 TiB |      3.50% |    1.19 TiB |           9.52% |
| [f047419](https://filfox.info/en/address/f047419)     |    North Prairie, Wisconsin, US |         896.00 GiB |      2.33% |  896.00 GiB |           0.00% |
| [f0836160](https://filfox.info/en/address/f0836160)   |                Seoul, Seoul, KR |         896.00 GiB |      2.33% |  800.00 GiB |          10.71% |

![Provider Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/1136/1671098719556.png)
### Deal Data Replication
The below table shows how each many unique data are replicated across storage providers.
- No more than 25% of unique data are stored with less than 4 providers.

✔️ Data replication looks healthy.

| Unique Data Size | Total Deals Made | Number of Providers | Deal Percentage |
| ---------------: | ---------------: | ------------------: | --------------: |
|        32.00 GiB |        64.00 GiB |                   1 |           0.17% |
|       208.00 GiB |       448.00 GiB |                   2 |           1.17% |
|       612.00 GiB |         2.02 TiB |                   3 |           5.38% |
|         1.45 TiB |         6.34 TiB |                   4 |          16.92% |
|         1.59 TiB |         8.41 TiB |                   5 |          22.43% |
|       896.00 GiB |         5.63 TiB |                   6 |          15.01% |
|       224.00 GiB |         1.75 TiB |                   7 |           4.67% |
|        64.00 GiB |       512.00 GiB |                   8 |           1.33% |
|        32.00 GiB |       288.00 GiB |                   9 |           0.75% |
|        96.00 GiB |         1.56 TiB |                  12 |           4.17% |
|       224.00 GiB |         3.81 TiB |                  13 |          10.17% |
|       256.00 GiB |         4.88 TiB |                  14 |          13.01% |
|        96.00 GiB |         1.81 TiB |                  15 |           4.84% |

![Replication Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/1136/1671098720254.png)
### Deal Data Shared with other Clients
The below table shows how many unique data are shared with other clients.
Usually different applications owns different data and should not resolve to the same CID.

✔️ No CID sharing has been observed.

[^1]: To manually trigger this report, add a comment with text `checker:manualTrigger`

**Comment by cryptowhizzard** [comment]
Retrievals working superfast like a charm ;-)
Providers checked , no involvement in CID sharing and mostly with good reputation afaik.
Geo spread ++

You have my support.


<img width="1145" alt="Scherm­afbeelding 2023-01-30 om 20 56 18" src="https://user-images.githubusercontent.com/36404435/215581812-a6c32a5b-4722-414c-b36b-fa11fed84d59.png">

**Comment by cryptowhizzard** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebwlqqkdg3rff5co43pz5dbo2ynf7mbft2p5mosyxc5dmihffveia 
#### Address 
> f1x4jjrsot2gevrxiqwgzgjh7kzh6c6kv3kkuyv6a
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1krmypm4uoxxf3g7okrwtrahlmpcph3y7rbqqgfa
#### Id
> bdc7fe4f-d179-4a71-9cc6-0241cb4efa07
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebwlqqkdg3rff5co43pz5dbo2ynf7mbft2p5mosyxc5dmihffveia

**Comment by flyworker** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebeafqnpivu3mhvq7u2fsncm6nd3lustkf2fzsf5yspovw2bm243w 
#### Address 
> f1x4jjrsot2gevrxiqwgzgjh7kzh6c6kv3kkuyv6a
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1hlubjsdkv4wmsdadihloxgwrz3j3ernf6i3cbpy
#### Id
> bdc7fe4f-d179-4a71-9cc6-0241cb4efa07
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebeafqnpivu3mhvq7u2fsncm6nd3lustkf2fzsf5yspovw2bm243w

**Comment by Normalnoise** [comment]
checker:manualTrigger

**Comment by newwebgroup** [comment]
The tool took a random CID for a retrieve test, and the test result was successful
https://filecoin.tools/f01943355
./lotus client retrieve --provider f02029115 Qmbr1eSH8Uwewi1r4Mw3etNGTPkPmLe3kWueszgUr1vhnx .car
<img width="1431" alt="image" src="https://user-images.githubusercontent.com/100118145/230309321-75dfaec7-82d5-4cf8-a6ef-33158ac274f1.png">

**Comment by newwebgroup** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebpjhupkkqcq2zhr2xdrwnk3ujqswh2pony3wc3r3bmixkyrkocn6 
#### Address 
> f1x4jjrsot2gevrxiqwgzgjh7kzh6c6kv3kkuyv6a
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1e77zuityhvvw6u2t6tb5qlnsegy2s67qs4lbbbq
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebpjhupkkqcq2zhr2xdrwnk3ujqswh2pony3wc3r3bmixkyrkocn6

**Comment by zcfil** [comment]
Found only a small amount of data. Can you provide more data samples?

**Comment by zcfil** [comment]
检查器：手动触发器

**Comment by hengdingy** [comment]
> Found only a small amount of data. Can you provide more data samples?

@zcfil all data and deals have been shown here [chainsnap](https://github.com/FogMeta/chainsnap)
