### ISSUE TITLE
[DataCap Application]  FilSwan -  NFT/IPFS Storage[Stage II]

### ISSUE THREAD

**Issue by flyworker** [filecoin-project/filecoin-plus-large-datasets#1139]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name:  FilSwan
- Website / Social Media: https://www.filswan.com
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 3PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100TiB
- On-chain address for first allocation: f1j22hqwh5tijbaztl7a7plzk5q2s4cesd67nyv3a

## Project details

```
Filswan provides a decentralized edge infrastructure marketplace and software that moves data  and processing as close as necessary on Web 3.0. FilSwan NFT gate log files, artifacts, backups, container images, photos and videos on FIlecoin Network.

With Filswan NFT Gateway 
- Industry users: Industry users can migrate their NFT related data to filecoin network with our payment gateway integration so they do not need to worry about the low level coding details. e.g. we are onboarding 
 [Machine Learning data NFT project ](https://github.com/filecoin-project/devgrants/pull/263), they are machine learning company, use lots of public machine learning data for training there model like waymo auto drive data.
- Smart contract support for multi blockchain include polygon, ethereum and BSC, HackFS2021 project
- Training and onboarding developers on  Filecoin network: vArtisans https://github.com/filecoin-project/devgrants/pull/260
- Hosted Platform: For platform like Powergate and Filswan, they can easily add it as a service component integrated to their current infrastructure.

After 1.5 years running of the [previous project ](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/15 )we have accomplished 1PB storage and some of them start expire.
``` 

What is the primary source of funding for this project?
```
FilSwan own funds
```

What other projects/ecosystem stakeholders is this project associated with?
```
No
```

## Use-case details

Describe the data being stored onto Filecoin
```
 Log files, artifacts, backups, container images, photos and videos 
```

Where was the data in this dataset sourced from?
```
Users data, uploaded by the users.
```

Can you share a sample of what is in the dataset? A link to a file, an image, a table, etc., are good examples of this. 
```
https://ipfs.multichain.storage/ipfs/QmWuHREwKXLbBRV94zxmgG3qP7EADUDuyQ3jAYazC5Pd8c?filename=monkey.zip

```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes
```

What is the expected retrieval frequency for this data?
```
Weekly base.
```

For how long do you plan to keep this dataset stored on Filecoin? Will this be a permanent archival or a one-time storage deal?
```
540 days, it should be a permanent as soon as the client willing to expend it.
```

## DataCap allocation plan

In which geographies do you plan on making storage deals?
```
EU, NA,Aisa
```

What is your expected data onboarding rate? How many deals can you make in a day, in a week? How much DataCap do you plan on using per day, per week?
```
It will start from several Tb to 3PB . Wa can make 1-1000 deals in 1 day, we need about 1-30TB per day.
```

How will you be distributing your data to miners? Is there an offline data transfer process?
```
We will distributed to minerx2 using offline deals
```

How do you plan on choosing the miners with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We using filswans bid function for choosing deals, they need to submit bid in order to win the bid, , we will send to multiple miners and make the deal. We also build an api for miners to download the dataset query the dataset name, and retrieval via miner id and cid.
```

How will you be distributing data and DataCap across miners storing data?
```
We are using filSwan client agent for batch sending deals.  https://github.com/filswan/go-swan-client
```

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 3PiB

**Expected weekly DataCap usage rate**

> 100TiB

**Client address**

> f1j22hqwh5tijbaztl7a7plzk5q2s4cesd67nyv3a

**Comment by cryptowhizzard** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebn6vk5fsa5uwilzfae7v4mltwuexbea6a7hz7qwrttvby2h7gbzc 
#### Address 
> f1j22hqwh5tijbaztl7a7plzk5q2s4cesd67nyv3a
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1krmypm4uoxxf3g7okrwtrahlmpcph3y7rbqqgfa
#### Id
> 71685938-5d14-480e-bcd5-336bf3d75a8b
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebn6vk5fsa5uwilzfae7v4mltwuexbea6a7hz7qwrttvby2h7gbzc

**Comment by kernelogic** [comment]
KYC has been performed previously. Filswan is a long time community builder.

**Comment by kernelogic** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebgbml2vhfnub66ih6qfe2nxzlsneotttenxnljjfkn52b2r7rqjo 
#### Address 
> f1j22hqwh5tijbaztl7a7plzk5q2s4cesd67nyv3a
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### Id
> f0f7f3af-1814-43ec-87e0-6250bc08d12e
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebgbml2vhfnub66ih6qfe2nxzlsneotttenxnljjfkn52b2r7rqjo

**Comment by cryptowhizzard** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceck2ok5eah24wbe5ylxobyx7mnw4tmq5bundu632waiwjpl4xflee 
#### Address 
> f1j22hqwh5tijbaztl7a7plzk5q2s4cesd67nyv3a
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1krmypm4uoxxf3g7okrwtrahlmpcph3y7rbqqgfa
#### Id
> f0f7f3af-1814-43ec-87e0-6250bc08d12e
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceck2ok5eah24wbe5ylxobyx7mnw4tmq5bundu632waiwjpl4xflee

**Comment by liyunzhi-666** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceag5dzy2gme4s7zebgnffzhgenzk4ylpycgwfooev76yxc6gh3fes 
#### Address 
> f1j22hqwh5tijbaztl7a7plzk5q2s4cesd67nyv3a
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1pszcrsciyixyuxxukkvtazcokexbn54amf7gvoq
#### Id
> 916d3a41-4881-4097-bf1e-fcad40899ddb
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceag5dzy2gme4s7zebgnffzhgenzk4ylpycgwfooev76yxc6gh3fes

**Comment by filplus-checker** [comment]
## DataCap and CID Checker Report[^1]
 - Organization: ` FilSwan`
 - Client: `f1j22hqwh5tijbaztl7a7plzk5q2s4cesd67nyv3a`
### Storage Provider Distribution
The below table shows the distribution of storage providers that have stored data for this client.

If this is the first time a provider takes verified deal, it will be marked as `new`.

For most of the datacap application, below restrictions should apply.
 - Storage provider should not exceed 25% of total datacap.
 - Storage provider should not be storing duplicate data for more than 20%.
 - Storage provider should have published its public IP address.
 - All storage providers should be located in different regions.

✔️ Storage provider distribution looks healthy.

| Provider                                              |                        Location | Total Deals Sealed | Percentage | Unique Data | Duplicate Deals |
| :---------------------------------------------------- | ------------------------------: | -----------------: | ---------: | ----------: | --------------: |
| [f01947280](https://filfox.info/en/address/f01947280) |          Hangzhou, Zhejiang, CN |           7.78 TiB |     17.18% |    7.78 TiB |           0.00% |
| [f01955028](https://filfox.info/en/address/f01955028) |          Hangzhou, Zhejiang, CN |           7.78 TiB |     17.18% |    7.78 TiB |           0.00% |
| [f01955034](https://filfox.info/en/address/f01955034) |          Hangzhou, Zhejiang, CN |           6.88 TiB |     15.18% |    6.88 TiB |           0.00% |
| [f01955030](https://filfox.info/en/address/f01955030) |          Hangzhou, Zhejiang, CN |           5.16 TiB |     11.39% |    5.16 TiB |           0.00% |
| [f0717969](https://filfox.info/en/address/f0717969)   |     Los Angeles, California, US |           2.94 TiB |      6.49% |    2.94 TiB |           0.00% |
| [f010088](https://filfox.info/en/address/f010088)     |         Everett, Washington, US |           2.44 TiB |      5.38% |    2.44 TiB |           0.00% |
| [f01931631](https://filfox.info/en/address/f01931631) |         Shenzhen, Guangdong, CN |           2.38 TiB |      5.24% |    2.38 TiB |           0.00% |
| [f01886797](https://filfox.info/en/address/f01886797) | Vancouver, British Columbia, CA |           2.22 TiB |      4.90% |    2.22 TiB |           0.00% |
| [f0240456](https://filfox.info/en/address/f0240456)   |            Chengdu, Sichuan, CN |           1.31 TiB |      2.90% |    1.31 TiB |           0.00% |
| [f01862564](https://filfox.info/en/address/f01862564) |              Xi’an, Shaanxi, CN |           1.28 TiB |      2.83% |    1.28 TiB |           0.00% |
| [f01222595](https://filfox.info/en/address/f01222595) |              Moscow, Moscow, RU |         896.00 GiB |      1.93% |  896.00 GiB |           0.00% |
| [f01390330](https://filfox.info/en/address/f01390330) |              Xi’an, Shaanxi, CN |         800.00 GiB |      1.73% |  800.00 GiB |           0.00% |
| [f047419](https://filfox.info/en/address/f047419)     |    North Prairie, Wisconsin, US |         800.00 GiB |      1.73% |  800.00 GiB |           0.00% |
| [f01225882](https://filfox.info/en/address/f01225882) |   Burnaby, British Columbia, CA |         768.00 GiB |      1.66% |  768.00 GiB |           0.00% |
| [f01708981](https://filfox.info/en/address/f01708981) |         Shenzhen, Guangdong, CN |         544.00 GiB |      1.17% |  544.00 GiB |           0.00% |
| [f032824](https://filfox.info/en/address/f032824)     |               Austin, Texas, US |         480.00 GiB |      1.04% |  480.00 GiB |           0.00% |
| [f01163272](https://filfox.info/en/address/f01163272) |             Perm, Perm Krai, RU |         352.00 GiB |      0.76% |  352.00 GiB |           0.00% |
| [f01443744](https://filfox.info/en/address/f01443744) |             Leipzig, Saxony, DE |         320.00 GiB |      0.69% |  320.00 GiB |           0.00% |
| [f08399](https://filfox.info/en/address/f08399)       |         Seattle, Washington, US |         256.00 GiB |      0.55% |  256.00 GiB |           0.00% |
| [f0408717](https://filfox.info/en/address/f0408717)   |       Ansan-si, Gyeonggi-do, KR |          32.00 GiB |      0.07% |   32.00 GiB |           0.00% |

![Provider Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/1139/1671098773893.png)
### Deal Data Replication
The below table shows how each many unique data are replicated across storage providers.
- No more than 25% of unique data are stored with less than 4 providers.

⚠️ 59.70% of deals are for data replicated across less than 4 storage providers.

| Unique Data Size | Total Deals Made | Number of Providers | Deal Percentage |
| ---------------: | ---------------: | ------------------: | --------------: |
|         3.03 TiB |         3.03 TiB |                   1 |           6.69% |
|         4.31 TiB |         8.63 TiB |                   2 |          19.05% |
|         5.13 TiB |        15.38 TiB |                   3 |          33.95% |
|         4.56 TiB |        18.25 TiB |                   4 |          40.30% |

![Replication Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/1139/1671098774723.png)
### Deal Data Shared with other Clients
The below table shows how many unique data are shared with other clients.
Usually different applications owns different data and should not resolve to the same CID.

⚠️ CID sharing has been observed.

| Other Client                                                                                                          | Application                                                                                 | Total Deals Affected | Unique CIDs |        Verifier |
| :-------------------------------------------------------------------------------------------------------------------- | :------------------------------------------------------------------------------------------ | -------------------: | ----------: | --------------: |
| [f1bstbq5bi72kyovhh7zoo2f6l6uivsjz4ey5dnqq](https://filfox.info/en/address/f1bstbq5bi72kyovhh7zoo2f6l6uivsjz4ey5dnqq) | [FilSwan](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/917)      |            61.66 TiB |         520 | LDN v3 multisig |
| [f1o54sve7ede7im4caux3ug7lsyjmbue7ss3zzl6y](https://filfox.info/en/address/f1o54sve7ede7im4caux3ug7lsyjmbue7ss3zzl6y) | [FilSwan](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/278)      |            41.47 TiB |         324 | LDN v3 multisig |
| [f13zfhkvtf6mewd74jhav6iqcggwsojht73tickga](https://filfox.info/en/address/f13zfhkvtf6mewd74jhav6iqcggwsojht73tickga) | [X\-Order Lab](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/936) |             1.94 TiB |          62 | LDN v3 multisig |

[^1]: To manually trigger this report, add a comment with text `checker:manualTrigger`

**Comment by kernelogic** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceckrryejptx2wahccczoxyf4cptte7bj4nin3ohkwzizwtdjl7rau 
#### Address 
> f1j22hqwh5tijbaztl7a7plzk5q2s4cesd67nyv3a
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### Id
> 916d3a41-4881-4097-bf1e-fcad40899ddb
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceckrryejptx2wahccczoxyf4cptte7bj4nin3ohkwzizwtdjl7rau

**Comment by cryptowhizzard** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedbx3ha2u7hfoegmo6wm36zjtxuabbpl4bnkiyrhol64sf23ffxxu 
#### Address 
> f1j22hqwh5tijbaztl7a7plzk5q2s4cesd67nyv3a
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1krmypm4uoxxf3g7okrwtrahlmpcph3y7rbqqgfa
#### Id
> a2ce51f2-9f07-4990-9613-1579d4ccbca7
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedbx3ha2u7hfoegmo6wm36zjtxuabbpl4bnkiyrhol64sf23ffxxu

**Comment by kernelogic** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaxqu7cy2wk5fg5x7yst35l2biqi4odtgb6in2azd7ha4ckzgkrxi 
#### Address 
> f1j22hqwh5tijbaztl7a7plzk5q2s4cesd67nyv3a
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### Id
> a2ce51f2-9f07-4990-9613-1579d4ccbca7
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaxqu7cy2wk5fg5x7yst35l2biqi4odtgb6in2azd7ha4ckzgkrxi

**Comment by flyworker** [comment]
checker:manualTrigger

**Comment by kernelogic** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecu4q62orpzx2tclgyw77zqxww5opn5gsa2i4ay547bylgq4mhfkm 
#### Address 
> f1j22hqwh5tijbaztl7a7plzk5q2s4cesd67nyv3a
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### Id
> a2ce51f2-9f07-4990-9613-1579d4ccbca7
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecu4q62orpzx2tclgyw77zqxww5opn5gsa2i4ay547bylgq4mhfkm

**Comment by herrehesse** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacechuuf7z4aekdlgllqwehtdsbxlz6ouklzbidlfjp7hrciaxbdg2c 
#### Address 
> f1j22hqwh5tijbaztl7a7plzk5q2s4cesd67nyv3a
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1krmypm4uoxxf3g7okrwtrahlmpcph3y7rbqqgfa
#### Id
> a2ce51f2-9f07-4990-9613-1579d4ccbca7
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacechuuf7z4aekdlgllqwehtdsbxlz6ouklzbidlfjp7hrciaxbdg2c

**Comment by Sunnyiscoming** [comment]
Hi, please explain the abnormal information.
⚠️ [f01981571](https://filfox.info/en/address/f01981571) has unknown IP location.
⚠️ [f01946551](https://filfox.info/en/address/f01946551) has unknown IP location.
⚠️ 80.28% of deals are for data replicated across less than 4 storage providers.
⚠️ CID sharing has been observed.

**Comment by s0nik42** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceculvnim522vx5jf6acw6wnnozn7ad7li7t5uh3szbrbnzn3zsyxo 
#### Address 
> f1j22hqwh5tijbaztl7a7plzk5q2s4cesd67nyv3a
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1wxhnytjmklj2czezaqcfl7eb4nkgmaxysnegwii
#### Id
> 0e25ad42-330a-4b05-a2be-e4764c241af9
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceculvnim522vx5jf6acw6wnnozn7ad7li7t5uh3szbrbnzn3zsyxo

**Comment by liyunzhi-666** [comment]
checker:manualTrigger

**Comment by liyunzhi-666** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceai6a53tjnqjtmsxkmjatdtosbap3n4bdmepxx7h46diwbom4nw5a 
#### Address 
> f1j22hqwh5tijbaztl7a7plzk5q2s4cesd67nyv3a
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1pszcrsciyixyuxxukkvtazcokexbn54amf7gvoq
#### Id
> 02b9796c-051b-4794-b1de-45f74a84f313
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceai6a53tjnqjtmsxkmjatdtosbap3n4bdmepxx7h46diwbom4nw5a

**Comment by Sunnyiscoming** [comment]
Hello, @flyworker per the https://github.com/filecoin-project/notary-governance/issues/922 for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

This information will be reviewed by Fil+ Governance team to confirm validity and then the application will be allowed to move forward for additional notary review.
