### ISSUE TITLE
[DataCap Application] DongShuXiSuan - COVID19-OPEN DATASET

### ISSUE THREAD

**Issue by dsxsfz** [filecoin-project/filecoin-plus-large-datasets#1147]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Fujian DongShuXiSuan Technology Co., Ltd.
- Website / Social Media: www.ppdx.cn
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5 PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 700TiB
- On-chain address for first allocation: f1q24kye52nhw43hsnqwc7uduqy3x73bcp2hmbala

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Our company is a company specializing in providing big data and AI solutions. Our main business includes: data storage, big data analysis and calculation, AI model training.
After the start of COVID19, we spent a lot of time on this side of big data research, hoping to help patients through research.
```

What is the primary source of funding for this project?
```
This relies on the support of our shareholders and company income.
```

What other projects/ecosystem stakeholders is this project associated with?
```
None
```

## Use-case details

Describe the data being stored onto Filecoin
```
During R&D and testing, we have downloaded a large number of public data sets. We use these data for daily research and development and AI data training. We are very grateful for the great value these data bring to the company's development. We are concerned about the rapid development of the filecoin project, and technologies such as distributed storage, fvm, and data retrieval are also of great interest to the company. So we decided to store these obtained public datasets and the publicly available datasets generated by the company to the filecoin network through the fil-plus project.
```

Where was the data in this dataset sourced from?
```
Our data comes from kaggle, aws opendata, public data download platforms of major universities, as well as our daily training data, etc.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://registry.opendata.aws/foldingathome-covid19/
https://registry.opendata.aws/talend-covid19/
https://registry.opendata.aws/dnastack-covid-19-sra-data/
https://www.kaggle.com/datasets/mathurinache/mosmeddata-chest-ct-scans-with-covid19
https://www.kaggle.com/datasets/andyczhao/covidx-cxr2
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes. I confirm that this is a public dataset that can be retrieved by anyone on the Network.
```

What is the expected retrieval frequency for this data?
```
About 10 times a year.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
At least 1.5 year
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Asia, North America.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Yes. We will adopt online transmission and offline transmission.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We will look for SPs through slack and filfox, hope to choose miners with good credit. This is the character we value.
```

How will you be distributing deals across storage providers?
```
We will follow the rules for large-datasets. And we will ensure fair distribution through limiting the amount of deals send to each miner, under 25% to per sp. These records will be made and published regularly on Github.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, we have. We'd like community can support and approve our issue.
```

**Comment by dsxsfz** [comment]
@raghavrmadya Hi RG, We have open a seperate application for covid19 dataset, please help advance our issue, thank you very much

**Comment by dsxsfz** [comment]
@simonkim0515 We found our application was assigned by you,  do we need to provide more information？

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 700TiB

**Client address**

> f1q24kye52nhw43hsnqwc7uduqy3x73bcp2hmbala

**Comment by raghavrmadya** [comment]
Please note that this client had previously submitted an issue that was closed but did not disclose this information in this new application. The T&T WG is not supportive of this application - https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/996#issuecomment-1283510121
