### ISSUE TITLE
[DataCap Application] Pharos

### ISSUE THREAD

**Issue by cea1063** [filecoin-project/filecoin-plus-large-datasets#115]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Pharos Consulting
- Website / Social Media: www.pharosconsulting.co.kr
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100TiB
- On-chain address for first allocation: f3vila4wx2vahcfzui3pkq3qth6eqo5haemnullchvwljeafz35nso4tld63qtweqws4si3zahdtyh4zjmr7gq

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```

Please answer here.
```
Pharos Consulting is founded in 2018. It was established with a mission to help companies suffering from financial difficulties. In a name of the lighthouse, Pharos that lit the ocean at the first time. We have mentored numerous enterprises and corporations to earn more profit and help solve tax problems. Therefore, we have lots of education documents and lecture videos. Also, we have many peer company that is in similar situation like our company. 
However, we are expanding our business to Metaverse. So we are planning to collaborate with Metaverse Flatform and offer lecture and seminars in Metaverse world. Therefore we want to preserve our lectures and education documents in IPFS file coin storage. 

What is the primary source of funding for this project?
```
Please answer here.
```
Our clients’ company (such as Hospital, Law Firm, Pharmacy Chain, etc)

What other projects/ecosystem stakeholders is this project associated with?
```
Please answer here.
```
Hospitals, Law Firms, Education Centers, Academy

## Use-case details

Describe the data being stored onto Filecoin
```
Please answer here.
```
It is a lecture program. We have lots of lecture and education documents in IPFS file coin storage. Which should be preserved long term on Filecoin and IPFS to be utilized in many ways. Also we might expand usage cases broader than now. 

Where was the data in this dataset sourced from?
```
Please answer here.
```
Mostly Asia, South Korea.

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
Please answer here.
```
yes

https://user-images.githubusercontent.com/38237198/146495553-610e2191-88b5-4141-92b4-d9c5d3eab3aa.mp4

        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Please answer here.
```
Yes, it is a public data. 

What is the expected retrieval frequency for this data?
```
Please answer here.
```
Our data are informative and educational contents. Expected search frequency is similar to that of edu-channel show. Also these data can be used for a long time. So in the long term its retrieval frequency will be more higher. Moreover we want to preserve these data almost as a permanent archive. 

For how long do you plan to keep this dataset stored on Filecoin?
```
Please answer here.
```
Permanently, we'll constantly upload our data and store them for a long time.

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Please answer here.
```
Asia, mostly in South Korea. 

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Please answer here.
```
We are planning to use online transfer. But if the data is too big then we will use offline transfer. 

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
Please answer here.
```
We will select miners through miners reputation systems like filrep.io. 

How will you be distributing deals across storage providers?
```
Please answer here.
```
We will use both online and offline transfer.

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Please answer here.
```
We have funding from several companies. Many peer company of our company is ready to make a deals. They have thousands TiBs of lecture videos and educating programs to be stored. Also they want to start making deals as soon as possible. So hopefully we can start to put verified data rapidly.

**Comment by cea1063** [comment]
Hi Galen,
Could you update current status?

**Comment by cea1063** [comment]
Hi Galen, Sorry for late update.

I'm working on education consulting team in Pharos.

You can contact to me below e-mail address
we01@pharosconsulting.co.kr

Our website was under maintenance and you can visit now.

Please check attached sample file. 
(I clipped video file to make under 10 MB)

https://user-images.githubusercontent.com/38237198/146494923-2eccc95e-b632-4784-a297-d3ef3875757d.mp4

If you have other request, let me know.

**Comment by cea1063** [comment]
> Hi Galen, Sorry for late update.
> 
> I'm working on education consulting team in Pharos.
> 
> You can contact to me below e-mail address [we01@pharosconsulting.co.kr](mailto:we01@pharosconsulting.co.kr)
> 
> Our website was under maintenance and you can visit now.
> 
> Please check attached sample file. (I clipped video file to make under 10 MB)
> 
> If you have other request, let me know.

**Comment by cea1063** [comment]
Hi Galen,
Could you check my update?

**Comment by cea1063** [comment]
Hi Galen,
I updated my comment 3 weeks ago.
Could you share current status?
If you need other information or have request, let me know.

**Comment by dannyob** [comment]
Hi @cea1063 -- I'm the notary at the Filecoin Foundation. 5PiB is a lot of datacap to start with. You may be better off requesting a smaller one-off amount to see if the system will work well for you, and for us to be able to better ascertain whether your data is appropriate for a larger Filecoin Plus datacap allotment. Have you considered applying for a smaller one-off allocation from a single notary through this process: https://plus.fil.org/verifiers

**Comment by galen-mcandrew** [comment]
## Multisig Notary requested
#### Total DataCap requested 
> 5PiB
#### Expected weekly DataCap usage rate 
> 100TiB

**Comment by galen-mcandrew** [comment]
With the extra detail, this can pass over to the notaries. I would agree with the advice from Danny though, that you may want to first work directly with a notary for a smaller amount of DataCap.

https://plus.fil.org/verifiers

**Comment by cea1063** [comment]
> Hi @cea1063 -- I'm the notary at the Filecoin Foundation. 5PiB is a lot of datacap to start with. You may be better off requesting a smaller one-off amount to see if the system will work well for you, and for us to be able to better ascertain whether your data is appropriate for a larger Filecoin Plus datacap allotment. Have you considered applying for a smaller one-off allocation from a single notary through this process: https://plus.fil.org/verifiers

Hi Danny,
I requested 'Client Allocation Request for Pharos'. 
Unfortunately I clicked 'send request' button twice.
Could you close Issue #1366?
Please check my request. If you have other request, let me know.

**Comment by cea1063** [comment]
> With the extra detail, this can pass over to the notaries. I would agree with the advice from Danny though, that you may want to first work directly with a notary for a smaller amount of DataCap.
> 
> https://plus.fil.org/verifiers

Hi Galen,
Thanks for your support.
I would like to proceed both 'DataCap Application' and 'Client Allocation'
As Danny mentioned, I will check our system work well.

**Comment by cea1063** [comment]
@Reiers @MegTei @IreneYoung @rayshitou @TimWilliams00 @ozhtdong @Fenbushi-Filecoin @swatchliu @MRJAVAZHAO @KodaRobotDog @XnMatrixSV
Hi all,
Could you check my request to DataCap Allocation?
I'm waiting Multisig step for 2 weeks.
Please give any feedback.

**Comment by MegTei** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebuza7ezlrkfk5ft4t5jm5425xq5ccku2653zlzesvijmt3o5nns2 
#### Address 
> f3vila4wx2vahcfzui3pkq3qth6eqo5haemnullchvwljeafz35nso4tld63qtweqws4si3zahdtyh4zjmr7gq
#### Datacap Allocated
> 50TiB
#### Signer Address
> f1ystxl2ootvpirpa7ebgwl7vlhwkbx2r4zjxwe5i
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebuza7ezlrkfk5ft4t5jm5425xq5ccku2653zlzesvijmt3o5nns2

**Comment by Reiers** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceblekgmoe3htqacbu34xahp6vslkkl4c7lkehfg4amxhyhewaxyjq 
#### Address 
> f3vila4wx2vahcfzui3pkq3qth6eqo5haemnullchvwljeafz35nso4tld63qtweqws4si3zahdtyh4zjmr7gq
#### Datacap Allocated
> 50TiB
#### Signer Address
> f1oz43ckvmtxmmsfzqm6bpnemqlavz4ifyl524chq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceblekgmoe3htqacbu34xahp6vslkkl4c7lkehfg4amxhyhewaxyjq

**Comment by cea1063** [comment]
@Reiers @IreneYoung @rayshitou @TimWilliams00 @ozhtdong @Fenbushi-Filecoin @swatchliu @MRJAVAZHAO @XnMatrixSV @flyworker @IPFSUnion @bytebase @swatchliu

Hi, it's been a week, could you help my next datacap allocation?

**Comment by cea1063** [comment]
@Reiers @IreneYoung @rayshitou @TimWilliams00 @ozhtdong @Fenbushi-Filecoin @swatchliu @MRJAVAZHAO @XnMatrixSV @flyworker @IPFSUnion @bytebase @swatchliu

It's been two weeks, since the Bot request DataCap Allocation. I wonder if there is a specific reason why notaries don't respond or sign for allocation in the meantime.
I trust FileCoin, and that's why I want to put my data in these SPs and store them permanently. However, if this way of handling Datacap is delayed without prior notice and this irregularity, I think Filecoin Foundation itself will lose credibility.
I'd really appreciate it if you could tell me a reasonable reason and keep me waiting.

**Comment by Reiers** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecm7zw5jxy32njeqt5spstqukjjqobgj2dhmm72fpwddt4rsk5pai 
#### Address 
> f3vila4wx2vahcfzui3pkq3qth6eqo5haemnullchvwljeafz35nso4tld63qtweqws4si3zahdtyh4zjmr7gq
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1oz43ckvmtxmmsfzqm6bpnemqlavz4ifyl524chq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecm7zw5jxy32njeqt5spstqukjjqobgj2dhmm72fpwddt4rsk5pai

**Comment by IreneYoung** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacechc3rfjwfjufuzsbqvca6ipjuozfkmfqj35mgphbn27zsc7cmpzs 
#### Address 
> f3vila4wx2vahcfzui3pkq3qth6eqo5haemnullchvwljeafz35nso4tld63qtweqws4si3zahdtyh4zjmr7gq
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1d4gmpqz3execjj2wvrxuuhvbms5mzh7t7yqrviq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacechc3rfjwfjufuzsbqvca6ipjuozfkmfqj35mgphbn27zsc7cmpzs

**Comment by psh0691** [comment]
@cea1063

**Comment by psh0691** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceashnbzj2claojjcc22mwde25g2xxzefxzw6aalrbkmmauazryces 
#### Address 
> f3vila4wx2vahcfzui3pkq3qth6eqo5haemnullchvwljeafz35nso4tld63qtweqws4si3zahdtyh4zjmr7gq
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1qdko4jg25vo35qmyvcrw4ak4fmuu3f5rif2kc7i
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceashnbzj2claojjcc22mwde25g2xxzefxzw6aalrbkmmauazryces

**Comment by MegTei** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecjbkfvs5wp6rjemg2ewm2ydijdiv66vaeyud7yw2rj2infergjcq 
#### Address 
> f3vila4wx2vahcfzui3pkq3qth6eqo5haemnullchvwljeafz35nso4tld63qtweqws4si3zahdtyh4zjmr7gq
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1ystxl2ootvpirpa7ebgwl7vlhwkbx2r4zjxwe5i
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecjbkfvs5wp6rjemg2ewm2ydijdiv66vaeyud7yw2rj2infergjcq

**Comment by BigD-Exchange** [comment]
@cea1063 Hi! Great to see you have gotten approval for DataCap. If you are looking for storage providers to store these data or have any questions, please visit #bigdata-exchange on Filecoin Slack or reply here. 

We have strong demand from a diverse group of SPs, who are actively looking to onboard more data.

**Comment by filplus-checker** [comment]
## DataCap and CID Checker Report[^1]
 - Organization: `Pharos Consulting`
 - Client: `f3vila4wx2vahcfzui3pkq3qth6eqo5haemnullchvwljeafz35nso4tld63qtweqws4si3zahdtyh4zjmr7gq`
### Storage Provider Distribution
The below table shows the distribution of storage providers that have stored data for this client.

If this is the first time a provider takes verified deal, it will be marked as `new`.

For most of the datacap application, below restrictions should apply.
 - Storage provider should not exceed 25% of total datacap.
 - Storage provider should not be storing duplicate data for more than 20%.
 - Storage provider should have published its public IP address.
 - All storage providers should be located in different regions.

⚠️ [f01279864](https://filfox.info/en/address/f01279864) has sealed 37.22% of total datacap.

⚠️ [f01660052](https://filfox.info/en/address/f01660052) has unknown IP location.

⚠️ [f01654478](https://filfox.info/en/address/f01654478) has unknown IP location.

⚠️ [f01654220](https://filfox.info/en/address/f01654220) has unknown IP location.

⚠️ [f01690631](https://filfox.info/en/address/f01690631) has unknown IP location.

⚠️ [f01776341](https://filfox.info/en/address/f01776341) has unknown IP location.

⚠️ [f01780739](https://filfox.info/en/address/f01780739) has unknown IP location.

⚠️ [f01694564](https://filfox.info/en/address/f01694564) has unknown IP location.

⚠️ [f01652952](https://filfox.info/en/address/f01652952) has unknown IP location.

| Provider                                              |                     Location | Total Deals Sealed | Percentage | Unique Data | Duplicate Deals |
| :---------------------------------------------------- | ---------------------------: | -----------------: | ---------: | ----------: | --------------: |
| [f01279864](https://filfox.info/en/address/f01279864) | Seongnam-si, Gyeonggi-do, KR |          40.94 TiB |     37.22% |   40.94 TiB |           0.00% |
| [f01660052](https://filfox.info/en/address/f01660052) |                      Unknown |          22.84 TiB |     20.76% |   22.84 TiB |           0.00% |
| [f01472022](https://filfox.info/en/address/f01472022) |             Seoul, Seoul, KR |          18.50 TiB |     16.82% |   18.50 TiB |           0.00% |
| [f01654478](https://filfox.info/en/address/f01654478) |                      Unknown |          13.84 TiB |     12.59% |   13.84 TiB |           0.00% |
| [f01654220](https://filfox.info/en/address/f01654220) |                      Unknown |           5.06 TiB |      4.60% |    5.06 TiB |           0.00% |
| [f01690631](https://filfox.info/en/address/f01690631) |                      Unknown |           5.03 TiB |      4.57% |    5.03 TiB |           0.00% |
| [f01776341](https://filfox.info/en/address/f01776341) |                      Unknown |           1.75 TiB |      1.59% |    1.75 TiB |           0.00% |
| [f01780739](https://filfox.info/en/address/f01780739) |                      Unknown |           1.03 TiB |      0.94% |    1.03 TiB |           0.00% |
| [f01694564](https://filfox.info/en/address/f01694564) |                      Unknown |         512.00 GiB |      0.45% |  512.00 GiB |           0.00% |
| [f01652952](https://filfox.info/en/address/f01652952) |                      Unknown |         512.00 GiB |      0.45% |  512.00 GiB |           0.00% |

![Provider Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/115/1671092506088.png)
### Deal Data Replication
The below table shows how each many unique data are replicated across storage providers.
- No more than 25% of unique data are stored with less than 4 providers.

⚠️ 100.00% of deals are for data replicated across less than 4 storage providers.

| Unique Data Size | Total Deals Made | Number of Providers | Deal Percentage |
| ---------------: | ---------------: | ------------------: | --------------: |
|       104.80 TiB |       104.80 TiB |                   1 |          95.28% |
|         2.59 TiB |         5.19 TiB |                   2 |           4.72% |

![Replication Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/115/1671092506768.png)
### Deal Data Shared with other Clients
The below table shows how many unique data are shared with other clients.
Usually different applications owns different data and should not resolve to the same CID.

⚠️ CID sharing has been observed.

| Other Client                                                                                                                                                                                                              | Application                                                                                               | Total Deals Affected | Unique CIDs |  Verifier |
| :------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ | :-------------------------------------------------------------------------------------------------------- | -------------------: | ----------: | --------: |
| [f3sqnbeqqvaxyqlt56zls4viihpg5v3uykayqw5ir<br/>npbk6zbuds4dz6reeiud6eezp2dil5qbhvavbyhyd<br/>kv6a](https://filfox.info/en/address/f3sqnbeqqvaxyqlt56zls4viihpg5v3uykayqw5irnpbk6zbuds4dz6reeiud6eezp2dil5qbhvavbyhydkv6a) | [LG Whisen Dong\-an Service](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/114) |            16.59 TiB |         531 | LDN # 114 |
| [f3r5wyvf4nhgbuk72wmvheju5uhur4ifatnorqpkz<br/>ans2gwup6ehxvzmbie2mtmshdggukaxyekzmgttcq<br/>sraa](https://filfox.info/en/address/f3r5wyvf4nhgbuk72wmvheju5uhur4ifatnorqpkzans2gwup6ehxvzmbie2mtmshdggukaxyekzmgttcqsraa) | [IPFS KOREA](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/147)                 |            14.59 TiB |         467 | LDN # 147 |
| [f3sgm5o6tvtszct56ag2m7iqe5uhn4fzrf5skmjdu<br/>rmap3po2amqnqohrell6kipp74amnxn2olohgb3pd<br/>triq](https://filfox.info/en/address/f3sgm5o6tvtszct56ag2m7iqe5uhn4fzrf5skmjdurmap3po2amqnqohrell6kipp74amnxn2olohgb3pdtriq) | Unknown                                                                                                   |           256.00 GiB |           8 |   Unknown |
| [f3v7acvitagfyfhwdedorx4rv2kn7d7px2mdvg4w5<br/>btsmdkweknc6zg33mqjdoiyklaiitw7gxsw66yfzi<br/>xpwa](https://filfox.info/en/address/f3v7acvitagfyfhwdedorx4rv2kn7d7px2mdvg4w5btsmdkweknc6zg33mqjdoiyklaiitw7gxsw66yfzixpwa) | `King Enterprise`                                                                                         |           256.00 GiB |           8 |    Neo Ge |

[^1]: To manually trigger this report, add a comment with text `checker:manualTrigger`

**Comment by cea1063** [comment]
ok. I will check last comment
