### ISSUE TITLE
[DataCap Application] <Wuhan Lianlian Digital Technology Co., Ltd>< https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/100 >

### ISSUE THREAD

**Issue by AutoFeel** [filecoin-project/filecoin-plus-large-datasets#1152]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Wuhan Lianlian Digital Technology Co., Ltd
- Website / Social Media: http://www.xdlipfs.com/ 
Sina Weibo：https://weibo.com/u/7605817825?is_hot=1
WeChat official account：[https://mp.weixin.qq.com/mp/profile_ext?action=home&__biz=MzkzNTI0MTk0OQ==&scene=124#wechat_redirect](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/new?assignees=&labels=application%2C+Phase%3A+Diligence&template=datacap-application-for-large-dataset.md&title=%5BDataCap+Application%5D+%3COrganization%3E+-+%3CProject+Name%3E#wechat_redirect)
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 350TiB
- On-chain address for first allocation: f1664xafh3bzwub6gpg4beb2evkupj3u4txclko5i

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Wuhan Lianlian Digital Technology Co., Ltd., established in April 2021, is headquartered in Wuhan Optical Valley. There are more than 50 business backbones. The company has built a cloud storage service platform, created its own user community, cultivated good community consensus, and formed a good closed-loop ecology between "platform, company and user". In terms of institutional cooperation, the company has reached strategic cooperation with many local film and television companies in Wuhan to provide them with long-term distributed storage application services.
```

What is the primary source of funding for this project?
```
The project is funded by cooperative shareholders and strategic partners with sufficient reserves.
```

What other projects/ecosystem stakeholders is this project associated with?
```
Trading market.
```

## Use-case details

Describe the data being stored onto Filecoin
```
The Low Altitude Disaster Imagery (LADI) Dataset consists of human and machine annotated airborne images collected by the Civil Air Patrol in support of various disaster responses from 2015-2019. The initial release of LADI focuses on the Atlantic hurricane seasons and coastal states along the Atlantic Ocean and Gulf of Mexico. Annotations are included for major hurricanes of Harvey, Maria, and Florence. Two key distinctions are the low altitude, oblique perspective of the imagery and disaster-related features, which are rarely featured in computer vision benchmarks and datasets.
```

Where was the data in this dataset sourced from?
```
https://registry.opendata.aws/ladi/
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://github.com/LADI-Dataset/ladi-overview
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
 Creative Commons Attribution 4.0 International (CC BY 4.0)
```

What is the expected retrieval frequency for this data?
```
 Anyone interested in retrieving this data.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
Three years or more
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Of all regions, Asia is the best，Because Wuhan Lianlian has a large amount of bandwidth in Asia.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
 Online.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
Select a well funded storage provider that understands project data.
```

How will you be distributing deals across storage providers?
```
We will know whether the storage providers have relevant experience and sustainability, and reasonably allocate them to different storage providers according to the analysis.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
  We have prepared sufficient funds and resources.
```

**Comment by AutoFeel** [comment]
Hi,@Kevin-FF-USA @raghavrmadya I would like to ask why our application hasn't been updated so far? It's been 9 days since we submitted it and no robot has come to review it yet. Thank you.

**Comment by AutoFeel** [comment]
@Kevin-FF-USA @raghavrmadya
 I'm sorry to bother you again. My application has been long and I haven't received any robot updates. Can you help me with it? Thank you.

**Comment by Sunnyiscoming** [comment]
> Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
> 
>  Creative Commons Attribution 4.0 International (CC BY 4.0)

Hope you can give a clear answer about whether this is a public dataset.

What's the relationship between you and the organization?
How much original data are there? How many copies will you store?
Can you provide more detailed information about other storage providers participated in this program, such as you can list SPs you have contacted with at present?

**Comment by AutoFeel** [comment]
Hi @Sunnyiscoming 

Hope you can give a clear answer about whether this is a public dataset.
Yes, confirm it is a public dataset. Under the rule: CC BY 4.0

What's the relationship between you and the organization?
The application has been submitted before (https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/100), but the Github account has been banned. 350TiB has been consumed before, and 4.5658PiB has not been consumed.
I am an internal member of Wuhan Lianlian.
![image](https://user-images.githubusercontent.com/92368772/206385248-84497ed3-448c-46ff-9481-bbf2c152ddf5.png)

How much original data are there? How many copies will you store?
The original data is 800TiB+, and we plan to save 6-10 copies.

Can you provide more detailed information about other storage providers participated in this program, such as you can list SPs you have contacted with at present?
The miners we have worked with are as follows. At present, we are still actively contacting other miners.
![image](https://user-images.githubusercontent.com/92368772/206385282-a2d3574e-a9f9-4d3c-8495-01523e20ea30.png)

**Comment by Sunnyiscoming** [comment]
Could you send an email to filplus-app-review@fil.org with your official domain in order to confirm your identity? Email name should includes the issue id #1152.

**Comment by Sunnyiscoming** [comment]
No relative email have been received.

**Comment by AutoFeel** [comment]
Sorry, we have just sent an email, please check it, thank you.

**Comment by herrehesse** [comment]
Dear Applicant,

Due to the increased amount of erroneous/wrong Filecoin+ data recently, on behalf of the entire community, we feel compelled to go deeper into datacap requests. Hereby to ensure that the overall value of the Filecoin network and Filecoin+ program increases and is not abused.

Please answer the questions below as comprehensively as possible.

**Customer data**

- Could you demonstrate exactly how and to what extent customer contact occurred? 

We expect that for the onboarding of customers with the scale of an LDN there would have been at least multiple email and perhaps several chat conversations preceding it. A single email with an agreement does not qualify here.

- Did the customer specify the amount of data involved in this relevant correspondence?

- Why does the customer in question want to use the Filecoin+ program? 

_Should this only be soley for acquiring datacap this is of course **out of the question**. The customer must have a legitimate reason for wanting to use the Filecoin+ program which is intended as a program to store useful and public datasets on the network._ 

- Why is the customer data considered Filecoin+ eligible?

_(As an intermediate solution Filecoin offers the FIL-E program or the glif.io website for business datasets that do not meet the requirements for a Filecoin+ dataset)_


**Files and Processing**

- Could you please demonstrate to us how you envision processing and transporting the customer data in question to any location for preparation?
- Would you demonstrate to us that the customer, the preparer and the intended storage providers all have adequate bandwidth to process the set with its corresponding size?
- Would you tell us how the data set preparer takes into account the prevention of duplicates in order to prevent data cap abuse?


Hopefully you understand the caution the overall community has for onboarding the wrong data. We understand the increased need for Filecoin+, however, we must not allow the program to be misused. Everything depends on a valuable and useful network, let's do our best to make this happen. Together.

**Comment by Sunnyiscoming** [comment]
> * Wuhan Lianlian Digital Technology Co., Ltd

Received that.

**Comment by cryptowhizzard** [comment]
Hello @AutoFeel 

I tried to retrieve some of the deals that you made but all data has been slashed from your previous 350 TB of allocation?

Can you enlighten us what happened to that 350 TB of data?

**Comment by AutoFeel** [comment]
Hi @cryptowhizzard 

Because I started to understand the FIL+ project at the beginning of 2022, at that moment, I didn't have an in-depth understanding of the rules. The last project has been stagnant for nearly a year, and we haven't communicated with these SPs for a long time. I'm trying to reconnect with them these days.
For this application, we will follow the current rules and only send deals with SPs who support retrieval and have good credits in FIL+ only.

**Comment by cryptowhizzard** [comment]
Hi @AutoFeel 

Can you give us a detailed allocation plan with the SP's you want to use and how much data goes where and when?

**Comment by AutoFeel** [comment]
Hi @cryptowhizzard 

According to my understanding of FIL+ rules, we plan to find at least 10 SPs from 3-4 regions to store our data. Recently, I have been looking for LDN applicationts with high reputations in the community, and I will consider contacting these projects to see if they can recommend SPs with high service quality.

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 5PiB

**Expected weekly DataCap usage rate**
> 350TiB

**Client address**
>f1664xafh3bzwub6gpg4beb2evkupj3u4txclko5i

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 5PiB

**Expected weekly DataCap usage rate**
> 350TiB

**Client address**
> f1664xafh3bzwub6gpg4beb2evkupj3u4txclko5i

**Comment by AutoFeel** [comment]
@newwebgroup @zcfil @neogeweb3 @ipfscn @Bruce0726
Dear notaries, can you help me approve my project? Thank you so much.

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

As last question i would like you to fill out [this form](https://form.jotform.com/230337462961356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!

**Comment by AutoFeel** [comment]
@cryptowhizzard 
I have finished filling in the form, please check, thank you!

**Comment by AutoFeel** [comment]
@Joss-Hua 
We will not work with f01100139 as retrieval is not supported. We are now communicating with new SPs and confirming that the retrieval is supported，thank you!

**Comment by Joss-Hua** [comment]
Have reviewed and supports this round.

**Comment by laurarenpanda** [comment]
Didn't have any problems flagged by other notaries.
This project was submitted over six months, so I'd like to support the 1st round.
Please ensure you find qualified SPs and support data retrieval.

**Comment by Joss-Hua** [comment]
> Have reviewed and supports this round.

The second round of bot checker reports will serve as important reference.

**Comment by Joss-Hua** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced5tslcil6uezwit7uwq2mktu5pcyuogltkvsfywvltviw4wjrsd4 
#### Address 
> f1664xafh3bzwub6gpg4beb2evkupj3u4txclko5i
#### Datacap Allocated
> 175.00TiB
#### Signer Address
> f1tfg54zzscugttejv336vivknmsnzzmyudp3t7wi
#### Id
> 8783c563-7a9c-476a-bbb3-18a203fdbe4f
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced5tslcil6uezwit7uwq2mktu5pcyuogltkvsfywvltviw4wjrsd4

**Comment by laurarenpanda** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceclncqpdunutmafurxiqttkvz2ezx3wybqqzrantl3t44xjwccvny 
#### Address 
> f1664xafh3bzwub6gpg4beb2evkupj3u4txclko5i
#### Datacap Allocated
> 175.00TiB
#### Signer Address
> f1bp3tzp536edm7dodldceekzbsx7zcy7hdfg6uzq
#### Id
> 8783c563-7a9c-476a-bbb3-18a203fdbe4f
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceclncqpdunutmafurxiqttkvz2ezx3wybqqzrantl3t44xjwccvny

**Comment by AutoFeel** [comment]
Dear notaries, please take a look at my project and help me approve it, thank you very much!

**Comment by Fatman13** [comment]
checker:manualTrigger

**Comment by Fatman13** [comment]
Reached out by the client again. Wouldn't able to support due to CIDchecker report.
