### ISSUE TITLE
[DataCap Application] Wel Vape

### ISSUE THREAD

**Issue by WelVape** [filecoin-project/filecoin-plus-large-datasets#1155]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Wel Vape
- Website / Social Media: market@Wel.top  *Documentation will be sent through Email 
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):  1PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100TiB
- On-chain address for first allocation: f1i2igpiu5nlmcjbo2tyrcd5w7kdgtlgif2bb6vka
- Type: Custom Notary
- Identifier: E-fil

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Wel Vape is a Vape brand aiming to provide a healthier and more free lifestyle for smokers worldwide. Our team has over ten-year experience in consumer electronics and novel cigarette design and have won red dot design award, iF product design award, etc.. 
Wel Vape has already be an internet-famous brand among the young in Korea. In additional, we also started to actively layout the Chinese market, now we have over 1000 offline stores.
```

What is the primary source of funding for this project?
```
10 million USD from institutions such as Shunwei, Qualcomm,, Foxconn, etc..
```

What other projects/ecosystem stakeholders is this project associated with?
```
None.
```

## Use-case details

Describe the data being stored onto Filecoin
```
Development history of tobacco industry
Industry/health Knowledge Popularization
Industry/product research
Product evaluation
Experiment record
```

Where was the data in this dataset sourced from?
```
All from our company. Product department & Marketing 
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
Sample of data will be sent to Governance team and Notaries through email. 
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Not public 
```

What is the expected retrieval frequency for this data?
```
It depends. 
```

For how long do you plan to keep this dataset stored on Filecoin?
```
Permanently.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Asia&United State
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Offline transfer
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
NDLABS (Lead SP) - Singapore
Tenet - Korea
Maike Storage - Vietnam
Rongyin - USA
INTERPLANETARY STORAGE PTE. LTD. - HK
```

How will you be distributing deals across storage providers?
```
NDLABS (Lead SP)- 1X
Tenet -1X
Maike Storage - Vietnam-1X
Rongyin - 1X
INTERPLANETARY STORAGE PTE. LTD. - 1x
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes!
```

**Comment by WelVape** [comment]
Hello, @kevzak  This LDN application is for E-Fil+.

**Comment by liyunzhi-666** [comment]
hey @WelVape 
The official website mentioned in the [Exception Propasal](https://github.com/filecoin-project/notary-governance/issues/655) cannot be opened [www.wel.top](http://www.wel.top/)
cc @kevzak

**Comment by NDLABS-OFFICE** [comment]
Hi, @liyunzhi-666 
Because of the policy in mainland China now, “WelVape” are not allowed to make publicity promotions, neither the public websites nor social media. I have contacted Kevin through slack about this issue. Sorry, I forgot to put it on GitHub.
![image](https://user-images.githubusercontent.com/104019147/202651100-fc520efc-fdde-402b-8158-0bcbb9fc489d.png)

**Comment by Fatman13** [comment]
I'd like to volunteer to vet this application as a notary. What exactly are the tools that I should use to KYB this application?

**Comment by Fenbushi-Filecoin** [comment]
Can you justify why you need 5 PiB datacap? Need more details on the data.

**Comment by kevzak** [comment]
@Fatman13 - you were added to a slack group to see the Qcc report of welvape. Can you take a look there?

@NDLABS-OFFICE can you please update your application to include how much data is being onboarded for this pilot project?

**Comment by Fatman13** [comment]
> @Fatman13 - you were added to a slack group to see the Qcc report of welvape. Can you take a look there?

@kevzak I verified the information submitted in the private Slack group on [QCC](https://www.qcc.com/) and confirm that it is a legit business operating in China.

**Comment by WelVape** [comment]
Hi, @Fenbushi-Filecoin 
Sorry, I have changed the amount of data request. As KZ mentioned on E-Fil bi-weekly call, it is highly recommened for us to apply 1PiB during pilot stage.

**Comment by WelVape** [comment]
BTW, sample of data will be sent through email or duing slack by our lead SP. (cc NDLABS)

**Comment by liyunzhi-666** [comment]
I have verified the relevant information of this client in the slack group.

**Comment by Tom-OriginStorage** [comment]
Can you explain the SP area of ​​your cooperative storage?

**Comment by WelVape** [comment]
@Tom-OriginStorage  yep, I have mentioned SPs in the application form. 
![36536dfd3a9ba2c07df42bbad4ba5a2](https://user-images.githubusercontent.com/115535419/204434521-e5523c80-3b60-49ec-a319-9fa98762ab24.jpg)
Please take a look

**Comment by kevzak** [comment]
@Tom-OriginStorage and other Notaries - details of all E-Fil applications are always included in Exception proposal https://github.com/filecoin-project/notary-governance/issues/655

**Comment by stcouldlisa** [comment]
Hello, I read your information, I would like to support.
Can you provide more sample data to my mailbox, or slack (LISA).
Can you please provide the business license, thank you

**Comment by WelVape** [comment]
Hello, @stcouldlisa 
We have a slack group, I have synchronized information and materials in this group, and I will contact you in slack.
thank you!

**Comment by newwebgroup** [comment]
I verified the KYC&KYB information of the enterprise in the Slack group, which is a legal company in China.

**Comment by kevzak** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 1PiB

**Expected weekly DataCap usage rate**

> 100TiB

**Client address**

>f1i2igpiu5nlmcjbo2tyrcd5w7kdgtlgif2bb6vka

**Comment by kevzak** [comment]
Hello - I can confirm for the Fil+ team that @WelVape  has completed the Client Registration and Business Verification Check successfully. 5 Notaries reviewed the business and have shown support for the project.

Assigned notaries can proceed to review the application and the [exception proposal](https://github.com/filecoin-project/notary-governance/issues/655)

**Comment by kevzak** [comment]
It's been more than 2 business days. No review or comments from @MRJAVAZHAO @xingjitansuo. So we've assigned two additional Notaries to review. See all details above. Let me know if you have any questions.

**Comment by newwebgroup** [comment]
The preliminary audit is not bad, and I will continue to monitor.

**Comment by newwebgroup** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebemhz5t5dmmagnt2o6wso6kp3wjj2loxamtaevl4c4mpuhwsx7ca 
#### Address 
> f1i2igpiu5nlmcjbo2tyrcd5w7kdgtlgif2bb6vka
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1e77zuityhvvw6u2t6tb5qlnsegy2s67qs4lbbbq
#### Id
> f475d305-ed36-431a-bdfb-7132f58f737e
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebemhz5t5dmmagnt2o6wso6kp3wjj2loxamtaevl4c4mpuhwsx7ca

**Comment by kevzak** [comment]
@fabriziogianni7 @bmcnabb25 is having an issue signing
![Screenshot 2022-12-12 at 9 50 25 PM (1)](https://user-images.githubusercontent.com/102751751/207587483-31967795-3bd6-43d4-8579-5857ad8a00c6.png)

**Comment by fabriziogianni7** [comment]
@bmcnabb25 what version of filecoin app do you have in the ledger?

**Comment by stcouldlisa** [comment]
Looks good, I have followed them for a long time, I have completed KYB, I am willing to support them

**Comment by stcouldlisa** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecrh5fbyzhp2pvybjwtvnoxjss4jwaiqnvzddeswtjjhqksorhl7a 
#### Address 
> f1i2igpiu5nlmcjbo2tyrcd5w7kdgtlgif2bb6vka
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1jvvltduw35u6inn5tr4nfualyd42bh3vjtylgci
#### Id
> f475d305-ed36-431a-bdfb-7132f58f737e
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecrh5fbyzhp2pvybjwtvnoxjss4jwaiqnvzddeswtjjhqksorhl7a

**Comment by bmcnabb25** [comment]
@fabriziogianni7 it was v0.22.2 Just updated it to v0.22.5, so hopefully that will fix it. If I have more issues, will let you know! Thanks!

**Comment by kevzak** [comment]
Hello @WelVape can you answer some questions about your data:

How do you plan to make deals to your storage providers?

Boost Client
Lotus Client
Bidbot
Singularity
I dont know yet
Other/custom tool

How do you plan to prepare the dataset?

IPFS
lotus
singularity
graphsplit
I don't know
other/custom tool (if this, can you please add more detail?)

How will you be distributing your data to storage providers?
cloud storage (S3)

HTTP or FTP Server
IPFS
Shipping Hard Drives
Lotus Built-in data transfer
I don't know yet
others

**Comment by WelVape** [comment]
Hi, @kevzak here is my answer.

How do you plan to make deals to your storage providers?
Lotus Client

How do you plan to prepare the dataset?
lotus


How will you be distributing your data to storage providers?
cloud storage (S3)
Shipping Hard Drives

**Comment by kevzak** [comment]
@WelVape 
 just checking in on [your application](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1155). You received datacap one month ago. Do you need support with preparation and onboarding?

**Comment by Irmagogo** [comment]
Hi  @kevzak 
I'm sorry that we spent much time docking and communicating with those SPs, so the onboarding of Welvape has not started yet.
Due to the recent sealing situation check bot in the community, we found that the SP we had previously connected with and signed a cooperation agreement with was sealing unwell for their previous clients. So, we are communicating a solution to solve the problem to ensure that the sealing process of Welvape is perfect.

**Comment by cryptowhizzard** [comment]
Hello @Irmagogo 

That is totally understandable. The bar is high.

if you are looking for a SP with reputation in the USAi can recommend PikNik. It will cost you some money to get the data stored but then again, you know that things are done right and that they are behind a VPN for example.

If you want to store on the EU continent i can recommend looking at Reiers ( f022352 ) in Norway or Julien ( f010479 ) in France who is currently building out his storage capacity. Rob and ElioVP are also good candidates, you can find them on slack with ease.

Supporting decentralization is a good thing. Good luck with finding the right partners!

**Comment by NDLABS-OFFICE** [comment]
checker:manualTrigger

**Comment by kevzak** [comment]
Apologies, I posted next allocation review prompt on the[ exceptions page](https://github.com/filecoin-project/notary-governance/issues/655#issuecomment-1427956873), I meant to post it here. 

@WelVape please take a look, I think you are prompted to reply.

**Comment by cryptowhizzard** [comment]
Hello @WelVape 

Can you let me know who the SP's are where you are going to store your next round of datacap?
Can you send me the contact information of SP f02006374 to kyc@dcent.nl?

Thanks!

**Comment by PluskitOfficial** [comment]
> 75.20% of deals are for data replicated across less than 4 storage providers.

1.What's going on here?
2. Please state the form of the data you store, so that we can accurately judge whether you have such a large storage demand.
In addition, we have the same question as @cryptowhizzard, hope to receive your reply, thanks.​

**Comment by Irmagogo** [comment]
Hi there, @cryptowhizzard 
1. FYI, The upload speed of data backup is controlled by the partner SP itself, and the backed-up data has been sent to the other SPs. Each round of data onboard will have randomly different results, but the final result will be reasonable. 
2. @PluskitOfficial Do you need the contact information of the f02006374? Then please provide an email address and they will cc you.
3. f02006374 is owned by a brand new SP and is interested in accepting the deals. They contacted us through other partners. Their technology is in the initial stage of Filecoin, and some of the data is overlapped between the two LDNs due to the operation and maintenance processing of this SP. We have informed and instructed this SP on the rules and will not allow this SP to keep sealing the data until they have fully ensured that the O&M technology is mature. Appreciated it if you can understand how hard a new SP is to enter the network now. Thank you.
4. f02012175/f01971431/f01972110/f02031006/f01853077/f01878534 The above 6 SPs are expected to store the next round of dc. These SPs are located in the United States, Hong Kong, Korea and mainland China. However, since these have their own different clients, the exact amount of dc allocated each time is random. In addition, we are still in contact with other SPs in Singapore, there will be updates in the future, welcome to follow up.

**Comment by herrehesse** [comment]
@Irmagogo 

Per SP we require the:
- Business entity name
- Region
- Location

**Comment by cryptowhizzard** [comment]
> Hi there, @cryptowhizzard
> 

Hi.

> 2. @PluskitOfficial Do you need the contact information of the f02006374? Then please provide an email address and they will cc you.
> 3. f02006374 is owned by a brand new SP and is interested in accepting the deals. They contacted us through other partners. Their technology is in the initial stage of Filecoin, and some of the data is overlapped between the two LDNs due to the operation and maintenance processing of this SP. We have informed and instructed this SP on the rules and will not allow this SP to keep sealing the data until they have fully ensured that the O&M technology is mature. Appreciated it if you can understand how hard a new SP is to enter the network now. Thank you.

Brand new?

https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1084

![screemshot1](https://user-images.githubusercontent.com/36404435/218783147-c9a46c21-8ba5-477f-9bf1-dad9f6663963.png)
![screenshot2](https://user-images.githubusercontent.com/36404435/218783155-77dadb9c-6ef1-4074-a2a5-98d2222fe737.png)

**Comment by cryptowhizzard** [comment]
Doing a quick scan on these SPs does not give promising results:


f02012175 > Involved in CID sharing
f01971431 > Involved in CID sharing
f01972110 > Involved in CID sharing
f02031006 > OK
f01853077 > Involved in CID sharing
f01878534 > involved in CID sharing

@kevzak i am not comfortable on signing on this one.

**Comment by PluskitOfficial** [comment]
Based on the above results and the lack of response to our questions, I will also not sign for the time being.

**Comment by Irmagogo** [comment]
Hi all,
@kevzak An update for  SP: 
The following SPs will be added in the next round
f02031006/f02033219/f02012175

@herrehesse @PluskitOfficial  I respect your opinion but appreciate it if you could understand that the market situation is very few new SPs willing to join. The sp has invested a lot of money and time in establishing technical facilities, and it cannot prevent the SP from continuing to serve customers in the future because of a misoperation the SP. 
Also, if there is a chance, we can communicate whether you would like to provide a sealing service for WelVape.

**Comment by kevzak** [comment]
Hello @Irmagogo, sounds good. When adding/updating SPs involved,  it has become standard practice for private data applications that all SP information is included:

Business entity name
Region
Location

**Comment by Irmagogo** [comment]
@kevzak I Agree with this new rule. 
f02031006/Rolling Capital/USA
f02033219/WestWind Ltd./HK
f02012175/HeptaLabs/Korea
Please take a look. and reallocate notaries to review. Thx.

**Comment by kevzak** [comment]
@cryptowhizzard @PluskitOfficial I'll loop you back in now that SPs have been added. If you want to review again feel free. 

We'll also move forward following the updated Notary SLA https://github.com/filecoin-project/notary-governance/discussions/807 and randomly assigning:

@MRJAVAZHAO
@1475notary

Please review the application details for the Client, Data, and SPs and leave a comment. FYI, this application just updated SP details.

Please comment by Feb 27th.

If you chose not to sign, please leave a comment why so I can assign another notary if needed.

**Comment by cryptowhizzard** [comment]
Hello @kevzak

f02031006/Rolling Capital/USA is okay as SP.
f02033219/WestWind Ltd./HK is on my warning list but i am ok moving forward with this SP.

f02012175/HeptaLabs/Korea is problematic. Given that this applicant does his best and proves KYC / KYB i will be open and frank about my results. Each row in the image below where abusetype is 1 , the LDN is full of CID sharing and abuse.

Basically it means we are still short of 2 SP's with a "normal" reputation. 

<img width="1314" alt="Scherm­afbeelding 2023-02-24 om 21 37 04" src="https://user-images.githubusercontent.com/36404435/221287205-0256e442-9ea0-447e-829f-354b5d53cccb.png">

**Comment by Irmagogo** [comment]
@cryptowhizzard  Thanks for the reminder, would you like to accept an order for this LDN? If you think this is believable.

**Comment by Irmagogo** [comment]
@MRJAVAZHAO @1475Notary
Looking forward to your reply and comment. your support is appreciated. Please keep eye on the next allocation.

**Comment by MRJAVAZHAO** [comment]
Hope to know the data to be stored next. Please send data samples of these data to my email(javazhao@binghelab.cn).

**Comment by kevzak** [comment]
@MRJAVAZHAO @Irmagogo any update on data sample review?

**Comment by kevzak** [comment]
@1475Notary did not respond to request. We will move forward by randomly assigning another notary: @PluskitOfficial 

Please review and respond with a comment by March 6th. Thanks.

**Comment by MRJAVAZHAO** [comment]
@WelVape I am still waiting for the data samples. Have you sent that to my email?

**Comment by Irmagogo** [comment]
@MRJAVAZHAO hello, They tried to send the email but it shows fail many times. 
![WechatIMG177](https://user-images.githubusercontent.com/112935251/222704671-9027d02f-700c-4014-b157-90a9abafa511.png)
I'm gonna send you through my email.  Please check it. thank you.

**Comment by Irmagogo** [comment]
@MRJAVAZHAO oh, they said they send it to you successfully. 
![image](https://user-images.githubusercontent.com/112935251/222706630-6747e1e7-0d27-4bba-b5f0-62cb464d3825.png)

BTW, Does this slack account( BingHe Web 3.0 Lab) yours?  I sent the data sample through DM to this account on 2022/12/01. cause you were selected as our first-round notary. 

![屏幕快照 2023-03-03 下午7 14 42](https://user-images.githubusercontent.com/112935251/222706558-54a22c51-a888-42c5-957d-132dc4d0273d.png)

**Comment by PluskitOfficial** [comment]
> @1475Notary没有回应请求。我们将通过随机分配另一个公证人来向前推进：@PluskitOfficial
> 
> 请在3月6日之前查看并回复评论。谢谢。
@Kevin-FF-USA Hi, kevin, we reviewed it once some time ago and expressed the decision and reason of not signing it temporarily.

**Comment by kevzak** [comment]
Thank you @PluskitOfficial, I see that comment now. 

We'll wait for @MRJAVAZHAO review of data and move forward with additional notary assignment after as needed

**Comment by MRJAVAZHAO** [comment]
We have checked that. We will support it.

**Comment by MRJAVAZHAO** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedfogvneh32njyepdfzrqx6w326lhdt4ahvejiz4inere56ipkdvo 
#### Address 
> f1i2igpiu5nlmcjbo2tyrcd5w7kdgtlgif2bb6vka
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f14gme3f52prtyzk6pblogrdd6b6ivp4swc6qmesi
#### Id
> 6d427194-60b0-4774-9b3a-6f3d7eb14f91
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedfogvneh32njyepdfzrqx6w326lhdt4ahvejiz4inere56ipkdvo

**Comment by kevzak** [comment]
We'll move forward following the updated Notary SLA https://github.com/filecoin-project/notary-governance/discussions/807 and randomly assign:

@BlockMakeronline
@MatrixStorage


Please review the application details for the Client, Data, and SPs and leave a comment. FYI, this application just updated SP details.

**Comment by MatrixStorage** [comment]
I'm willing to support it.  I'll deal with it later.

**Comment by kevzak** [comment]
OK assuming @MatrixStorage will follow up. 

Let's move forward with the update notary SLA (https://github.com/filecoin-project/notary-governance/discussions/807) and assign randomly:

@Protocan

Leave a comment as needed. Please comment by March 10th. Thanks! If you are not interested in signing please also leave a comment stating why.

**Comment by MatrixStorage** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceddqgtrvodik23rbz6bjxaluf4jaieopl4yhwxk4vokjjifjp2s6m 
#### Address 
> f1i2igpiu5nlmcjbo2tyrcd5w7kdgtlgif2bb6vka
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1tbxqwjxfyv7swsdin4einirlsfquv3vnmlapley
#### Id
> 6d427194-60b0-4774-9b3a-6f3d7eb14f91
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceddqgtrvodik23rbz6bjxaluf4jaieopl4yhwxk4vokjjifjp2s6m

**Comment by kevzak** [comment]
checker:manualTrigger

**Comment by kevzak** [comment]
checker:manualTrigger

**Comment by WelVape** [comment]
Hi @Kevin Zakorchemny and all Notaries: 
I am Ruby, the person in charge of Welvape now. According to my recent observations, we found that our data is shared with other subjects. This is what I don't want to see.
According to the reply from our lead SP: Usually, they will temporarily store the data read from the hard disk on the local server, and record the data address content and data ownership label for these data through the MySQL database. Then the lead sp will distribute the data content to other sps through mysql data records. However, at the stage of labelling the data, they made some mistakes that caused the labels of different data to be mixed. They have now updated their system and this will no longer happen. Thanks for understanding.
In addition, please approve the next allocation and I will follow up on our data upload in real time to avoid repeating similar incidents. Thank you. 
| |
zfgwy79
|
|
***@***.***
|


---- Replied Message ----
| From | ***@***.***> |
| Date | 05/9/2023 21:58 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [filecoin-project/filecoin-plus-large-datasets] [DataCap Application] Wel Vape (Issue #1155) |

DataCap Allocation requested
Request number 4
Multisig Notary address

f01940930

Client address

f1i2igpiu5nlmcjbo2tyrcd5w7kdgtlgif2bb6vka

DataCap allocation requested

400TiB

Id

f66acff0-373a-40da-a2f8-1cd85f7d7fbe

**Comment by WelVape** [comment]
Hi @Kevin Zakorchemny and all Notaries: 


I am Ruby, the person in charge of Welvape now. According to my recent observations, we found that our data is shared with other subjects. This is what I don't want to see.
According to the reply from our lead SP: Usually, they will temporarily store the data read from the hard disk on the local server, and record the data address content and data ownership label for these data through the MySQL database. Then the lead sp will distribute the data content to other sps through mysql data records. However, at the stage of labelling the data, they made some mistakes that caused the labels of different data to be mixed. They have now updated their system and this will no longer happen. Thanks for understanding. 
In addition, please approve the next allocation and I will follow up on our data upload in real time to avoid repeating similar incidents. 
Thank you. 


| |
zfgwy79
|
|
***@***.***
|


---- Replied Message ----
| From | Kevin ***@***.***> |
| Date | 03/6/2023 22:06 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [filecoin-project/filecoin-plus-large-datasets] [DataCap Application] Wel Vape (Issue #1155) |

We'll move forward following the updated Notary SLA filecoin-project/notary-governance#807 and randomly assign:

@BlockMakeronline
@MatrixStorage

Please review the application details for the Client, Data, and SPs and leave a comment. FYI, this application just updated SP details.

**Comment by kevzak** [comment]
Hello @WelVape, understood. Please feel free to reach out to notaries to find needed support. [Slack link](https://filecoinproject.slack.com/archives/C03MHVAABFV/p1685110280027659?thread_ts=1685110243.399389&cid=C03MHVAABFV)

**Comment by laurarenpanda** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceas4e2i5azegp5c6y6wg37dbae5hshdq37zlsuphfn6li76rdwu62 
#### Address 
> f1i2igpiu5nlmcjbo2tyrcd5w7kdgtlgif2bb6vka
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1bp3tzp536edm7dodldceekzbsx7zcy7hdfg6uzq
#### Id
> f66acff0-373a-40da-a2f8-1cd85f7d7fbe
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceas4e2i5azegp5c6y6wg37dbae5hshdq37zlsuphfn6li76rdwu62

**Comment by Tom-OriginStorage** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedbezox4d4iairbwgqhmwvx5prbcntrzuqbnehj22m32hawvyyf5y 
#### Address 
> f1i2igpiu5nlmcjbo2tyrcd5w7kdgtlgif2bb6vka
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1q6bpjlqia6iemqbrdaxr2uehrhpvoju3qh4lpga
#### Id
> f66acff0-373a-40da-a2f8-1cd85f7d7fbe
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedbezox4d4iairbwgqhmwvx5prbcntrzuqbnehj22m32hawvyyf5y

**Comment by kevzak** [comment]
Hello @WelVape we have a new KYC ID check available on [filplus.storage](https://filplus.storage/). Please complete when you have a chance as a requirement for E-Fil+ to add additional layer of trust and to verify this GitHub account. See details: [LINK](https://medium.com/filecoin-plus/implementation-of-a-third-party-kyc-id-check-for-fil-applicants-e5e825b1484e)

**Comment by NDLABS-OFFICE** [comment]
> Hello @WelVape we have a new KYC ID check available on [filplus.storage](https://filplus.storage/). Please complete when you have a chance as a requirement for E-Fil+ to add additional layer of trust and to verify this GitHub account. See details: [LINK](https://medium.com/filecoin-plus/implementation-of-a-third-party-kyc-id-check-for-fil-applicants-e5e825b1484e)

 It looks very good.

**Comment by NDLABS-OFFICE** [comment]
It looks very good.

**Comment by Joss-Hua** [comment]
> This application has not seen any responses in the last 10 days. This issue will be marked with Stale label and will be closed in 4 days. Comment if you want to keep this application open.

Please let me know if it has been shelved and planned to be closed.

**Comment by cryptowhizzard** [comment]
Retrieval is not working @ this client.

cat 1623-f01974717-f01975316-30094233-baga6ea4seaqa7lhfosjpu7af3c4r3ob5ajphzq42qckodhbwhgmhsw4zfmvkgfa.log
ERROR: offer error: retrieval query offer errored: failed to fetch piece to retrieve from: failed to get ready(Proving) deals for retrieval QmR57Y7RoGdnfKW4AnLs6qRumqtMJgm6L8NA4FWbav5PGb

Please fix before moving on / signing.
