### ISSUE TITLE
[DataCap Application] Hitachi Systems Network Technologies

### ISSUE THREAD

**Issue by Hisysss** [filecoin-project/filecoin-plus-large-datasets#1156]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Hitachi Systems Network Technologies Pte.Ltd
- Website / Social Media: https://hitachi-systems-nt.com/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 4.5 PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100 TiB
- On-chain address for first allocation: f1ay5cv3p3uhle6akpcj3flw2kq3hidf6o2jih5yy

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Established in 2003 as I-Net Solutions and acquired by the Hitachi Group in 2015, Hitachi Systems Digital Services has transferred its business to Hitachi Systems 
Network Technologies in 2020. Headquartered in Singapore, Hitachi Systems 
Network Technologies is one of the leading information technology (IT) Service 
Providers for providing a comprehensive suite of IT solutions in consulting, 
system integration, maintenance, IT outsourcing and managed services, striving 
to be an advocate of technology innovations and to deliver the best services to all 
customers with the utmost integrity.
```

What is the primary source of funding for this project?
```
Company benefit
```

What other projects/ecosystem stakeholders is this project associated with?
```
No other stakeholders.
```

## Use-case details

Describe the data being stored onto Filecoin
```
- Firmware/image backup for all maintained devices, those are largest part of our data 
   storage. all network devices need to be prepared with different versions of firmwares, 
   systems/servers need to be prepared with most up to dated system images.
- Training materials. we are gold partener with Cisco, Huawei, Aruba, all the engineers 
   need to attend manufacturer's trainings regularly to improve skills. contents including 
   videos, demo systems, pdf, etc.
- KnowledgeBase, guide/manual for some of the devices
- Softwares, desktop/server applications for maintained devices. 
```

Where was the data in this dataset sourced from?
```
Sourced from our company own operation resources (maintenance, training, etc).
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
Sure
https://drive.google.com/drive/folders/1Aw5ZkhgiLYp8JofifCax1gFgLjT5F-4D?usp=sharing
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Confirm.
```

What is the expected retrieval frequency for this data?
```
Every 6 months.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
For 18 to 24 months.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Distance is our concern, we prefer Asia region especially SEA area.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
both online and offline are ok for us, depends on SP location.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
For safe keeping of our data, we would like to choose those with good data storage experience and stable operation providers.
```

How will you be distributing deals across storage providers?
```
Multiple replicas will be distribute to SPs, 5 copies is our plan, and 5 or more SPs will receive the data with each no more than 25%. 
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
yes, we are ready to make deals.
```

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 4.5PiB

**Expected weekly DataCap usage rate**

> 100TiB

**Client address**

> f1ay5cv3p3uhle6akpcj3flw2kq3hidf6o2jih5yy

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Looking at your application i have some questions:
As you are brand new on Github and have no history of past applications it seems to me that applying for 5PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?

Can you show us visible proof of the size of your data and the storage systems you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230232885049356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!

**Comment by Sunnyiscoming** [comment]
Hi @Hisysss 
If you still want to apply for datacap, you can ask more notaries to do client due diligence and approve the application in slack channel. https://app.slack.com/client/TEHTVS1L6/C036JKD8NVA/thread/C03BG1MNQ4T-1673888660.823499

**Comment by Hisysss** [comment]
checker:manualTrigger
