### ISSUE TITLE
[DataCap Allocation] - Blockchain media named "Coin has destiny"

### ISSUE THREAD

**Issue by R-Demon** [filecoin-project/filecoin-plus-large-datasets#1159]
---
name: Large Dataset Notary application
about: Clients should use this application form to request a DataCap allocation via a LDN for a dataset
title: "Blockchain media named "Coin has destiny""
labels: 'application, Phase: Diligence'
assignees: ''

---
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Coin has destiny
- Website / Social Media: https://www.youtube.com/channel/UCm-Z5jwhqCa3EtwDNXqMawg
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100TiB
- On-chain address for first allocation: f1diknjp6ruz5frpe2yqjdjkm2b3gqih5oe66sfwa
- Region: Greater China Region

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
I was originally an employee in the financial industry. I learned about blockchain in 2015 and was deeply attracted by its charm. But at that time, it was just a hobby.It was not until 2020 that I decided to officially resign and switch to the blockchain industry. Because at this time I have accumulated a certain amount of capital, even if I had no income at the beginning, I can still maintain my daily life. Since then, I have independently studied various blockchain projects, produced corresponding videos, and uploaded them to major social networking sites to obtain everyone's recognition and certain financial returns. With more and more videos, my own hard disk is no longer enough (so far, I have spent three 1T hard disks). Therefore, I think the real storage plan of filecoin is very useful for me, so I want to apply for some shares so that my videos can be saved for a long time.
```

What is the primary source of funding for this project?
```
My own savings and income from some platforms
```

What other projects/ecosystem stakeholders is this project associated with?
```
none
```

## Use-case details

Describe the data being stored onto Filecoin
```
The videos I made myself probably include project introduction videos, daily teaching videos and live training videos.
```

Where was the data in this dataset sourced from?
```
I usually make it myself, sometimes some friends help edit it.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://www.youtube.com/watch?v=hc_-xe8n0EQ
https://www.youtube.com/watch?v=aUawnlgIStU
https://www.youtube.com/watch?v=8NLslv_ldPA&t=1s
https://www.youtube.com/watch?v=NEajju7BVPg&t=80s
https://www.youtube.com/watch?v=nd0xP0mU3oI
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes

```

What is the expected retrieval frequency for this data?
```
Almost everyday
```

For how long do you plan to keep this dataset stored on Filecoin?
```
Of course, I hope it will be permanent, but the first stage is about three years.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Globally, of course, if possible, China takes priority.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Offline, this is the fastest.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
Network stability and fast retrieval from SPs' support will be preferentially considered.
```

How will you be distributing deals across storage providers?
```
Choose Offline transmission as far as possible.
After several years of operation, I have accumulated my fans. Most of them will watch my videos every day, so I hope this process will be as fast as possible. If it is used for online transmission, it will occupy too many resources.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Of course, I have reserved enough funds, unless your price is too outrageous. It may be helpful for the requirements of data format.
```

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 100TiB

**Client address**

> f1diknjp6ruz5frpe2yqjdjkm2b3gqih5oe66sfwa

**Comment by R-Demon** [comment]
How to get the "grant"？
I see that the current status is "Approved", but there is no following.

**Comment by R-Demon** [comment]
If there is anything else I need to do (for example, what information to fill in), please let me know.

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Looking at your application i have some questions:
As you are brand new on Github and have no history of past applications it seems to me that applying for 5PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?

Can you show us visible proof of the size of your data and the storage systems you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230232885049356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!

**Comment by Sunnyiscoming** [comment]
Hi @R-Demon 
If you still want to apply for datacap, you can ask more notaries to do client due diligence and approve the application in slack channel. https://app.slack.com/client/TEHTVS1L6/C036JKD8NVA/thread/C03BG1MNQ4T-1673888660.823499

**Comment by R-Demon** [comment]
> Hi @R-Demon If you still want to apply for datacap, you can ask more notaries to do client due diligence and approve the application in slack channel. https://app.slack.com/client/TEHTVS1L6/C036JKD8NVA/thread/C03BG1MNQ4T-1673888660.823499

Thanks you, I will try it.
