### ISSUE TITLE
[DataCap Application]stariverpan

### ISSUE THREAD

**Issue by changlizhi** [filecoin-project/filecoin-plus-large-datasets#116]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Stariver Technology Co., Ltd(四川星河飞天科技有限公司)
- Website / Social Media: https://www.stariverpan.com/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100TiB
- On-chain address for first allocation: f1wbmcknidxdfkpxdkhk6mj2otkiexyobow3pa6qq

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```

Stariver Technology Co., Ltd is a cloud disk company and is developing in web3 technology deeply. we believe that distributed store will be the most useful tech in the future!
LoogBox（“小龙云盘” in chinese）is one of our project,which is a cloud disk based on ipfs network,people can upload all files to ipfs by using this app.on the other hand ,you can research datas by cid on this app also. and you can view the datas which is opened by client.
You can download and install it by searching "小龙云盘（or LoongBox in English）" On AppStore(apple) or Samsung appstore(android) or download the pc App from our official website.

```

What is the primary source of funding for this project?
```
The company undertake this part of the spending.

```

What other projects/ecosystem stakeholders is this project associated with?
```
maybe the traditional cloud dist app like baidu cloud disk or other cloud disk.

```

## Use-case details

Describe the data being stored onto Filecoin
```

long video,short video,pictures,articles and so on.as a cloud disk you can store everything on it and the datas of you will be send to ipfs network and filecoin too.
Our data from "小龙云盘" is now pined on our own ipfs nodes and nft.storage/web3.storage.but with the data becoming larger and larger,our ipfs nodes seems too small! because the TiB level customer from video cut company is using our app to decrease their store cost.And the speed of nft.storage and web3.storage is too slow for us.so we want to apply datacap by using the filecoin network to store the cold data.

```

Where was the data in this dataset sourced from?
```
Uploaded by client from "小龙云盘".
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
You can use our own gateway below or the gateway of nft.storage gateway (bafyxxxxxx.ipfs.dweb.link) with your own cid:
(all of these data is uploaded by our app's client)
for example:
10M
https://ipfsgw.stariverpan.com/ipfs/bafybeidhnyd3z2hcmijau6gntnqbd4nzaxv5gq43bjske5f7xv5bemsnh4(JPG)
https://ipfsgw.stariverpan.com/ipfs/bafybeigicmfjsfzlputa3mffvmxjjlgyzdo7bn43lo7hcwqhivlved6jiy(zip)
https://ipfsgw.stariverpan.com/ipfs/bafybeierau2d6osa2xupxv4wfqpnmuedkk6vbthykqhwj5bcqq2bu3ljmq(mp3)

100M
https://ipfsgw.stariverpan.com/ipfs/bafybeifvtcatydzhfls622ogmkqucnjp7y5f7n243a2jq6dul65z3hroge(mp4)
https://ipfsgw.stariverpan.com/ipfs/bafybeigjtbcbtazn55rulgpj3rtzie6nl2pdghens7ig2vjwve5xc5a7zy(mp4)

1G
https://ipfsgw.stariverpan.com/ipfs/bafybeif3mnf2fqlk22dofj5yz7l3boetcvrc6jtndhwbocpoduhksxkafu(mp4)
https://ipfsgw.stariverpan.com/ipfs/bafybeibn3mdfz2sclrjlttmbskgn73irb4r3lpaksvqa7zr3g7shgimcsi(mp4)

3.4G
https://ipfsgw.stariverpan.com/ipfs/bafybeic5x7c6bv56t7kg25y57ohmm7ffnfdmleq423ln3xvh4xtll5tpjm(mp4)

```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes, we confirm that it is a public dataset.
```

What is the expected retrieval frequency for this data?
```
It's depend on the client's need,we can use LRU algorithm to distinguish and the hot data will be still on ipfs network.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
Permanent.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
China.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
we will start a lotus daemon link to our ipfs nodes  for "lotus client deal" cmd and start a timed task to exec the cmd when the LRU algorithm shows we need.
when the data become too large ,we will transfer the data offline.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
we will find the Capable miner which is stable increasing power in slingshot or who can sealing datas 20TiB per day.
```

How will you be distributing deals across storage providers?
```
we will divide the data by type and find storage providers who has the Preference of type.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
We can start immediately And if community encourage and reward some fil is much better!
```

**Comment by flyworker** [comment]
sounds interesting,
In which geographies (countries, regions) do you plan on making storage deals?
China
Any reason China only?

**Comment by changlizhi** [comment]
HI @flyworker, because our company is in china and we want stable providers in case that the providers not free for retrieve data after.If the providers are in china,we can find them for chatting,And the 5PiB datacap is so large that we maybe need to make deals offline.

**Comment by galen-mcandrew** [comment]
## Multisig Notary requested
#### Total DataCap requested 
> 5PiB
#### Expected weekly DataCap usage rate 
> 100TiB

**Comment by changlizhi** [comment]
hello @galen-mcandrew ! thanks for verifying my infos,And now,I'm finding notaries for signing it, but One notary noticed me that there is a problem which my application is not showing on [fil.plus](https://fil.plus) dashboard.It maybe need you to put it on it.thx again~!

**Comment by changlizhi** [comment]
here is his screenshot 
![image](https://user-images.githubusercontent.com/4144452/146390137-47e423a5-fd38-4458-887c-1e341f8e1abe.png)

**Comment by galen-mcandrew** [comment]
@changlizhi it is still waiting for root key holders, you will see an update in this issue (https://github.com/filecoin-project/notary-governance/issues/334) and then the bot will request your first allocation, which adjusts the labels here and it can show up in the app. Thanks for your patience!

**Comment by galen-mcandrew** [comment]
Also @changlizhi , if you have a ledger with the Filecoin app, you can also sign-in and view the pending requests same as a notary and root key holder! We are striving for transparency, so anyone can observe, but only approved addresses can take action. Hope this helps.

**Comment by changlizhi** [comment]
Get it @galen-mcandrew ,thanks! But I don't know how to get a ledger ~_~ ,I usually check the datacap in [https://verify.glif.io/](https://verify.glif.io/)

**Comment by Reiers** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceawyho3dxoqgkwygu2ytrndnfvr3hgwefcjgpliighbgt3llf2elo 
#### Address 
> f1wbmcknidxdfkpxdkhk6mj2otkiexyobow3pa6qq
#### Datacap Allocated
> 50TiB
#### Signer Address
> f1oz43ckvmtxmmsfzqm6bpnemqlavz4ifyl524chq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceawyho3dxoqgkwygu2ytrndnfvr3hgwefcjgpliighbgt3llf2elo

**Comment by galen-mcandrew** [comment]
Looks like those two notary messages went through as both proposals, so there are two pending transactions at this time. Still showing up in the app with 1 approval count, so next signature should approve one of the pending transactions.

**Comment by dannyob** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacea2mclal55vlxwuohxkn6a2cw373dlo7fjyif2x5hq57oqxiyiklu 
#### Address 
> f1wbmcknidxdfkpxdkhk6mj2otkiexyobow3pa6qq
#### Datacap Allocated
> 50TiB
#### Signer Address
> f1k6wwevxvp466ybil7y2scqlhtnrz5atjkkyvm4a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacea2mclal55vlxwuohxkn6a2cw373dlo7fjyif2x5hq57oqxiyiklu

**Comment by changlizhi** [comment]
HELLO Notaries @dannyob & @Reiers ,I've used up 80% of the first allocated datacap,Is there anything I should show here for verify?

**Comment by galen-mcandrew** [comment]
For LDN's we typically want to see top storage provider allocations at less than 35% of your overall deal-making, rather than 66.07%. A lower percentage indicates greater deal distribution, so I would also encourage you to work with some more storage providers. You can find more in deal making Slack channels, https://filrep.io/, or https://plus.fil.org/miners (just some sources, there are many ways to find storage providers!)

**Comment by changlizhi** [comment]
@galen-mcandrew yes, We realized that,The time of the notification from the bot is 7 days ago,at that time we just have found 3 storage providers and we just used up 80% of the 50TiB datacap,then we found another one and send the rest 10TiB datacap deals. the Top Provider becomes 43.88% now and there is 1TiB datacap left and the 1TiB is dealing.And we know that there is a filswan in Community now,so we will try that tool to send deals.
by the way,we applied normal datacap with `f1fd7pgiygdwnsvxqj7n3f4ixuioq5btgok25mgzi` in https://github.com/filecoin-project/filecoin-plus-client-onboarding/issues/1111 before and mixed the data deals with these wallets.
we will pay attention to the providers selections after!!

**Comment by galen-mcandrew** [comment]
Thanks for the info. At this time, your application is ready to sign and awaiting notary action. You will need two different notaries than the previous allocation signers (dannyob & Reiers)

**Comment by changlizhi** [comment]
@galen-mcandrew ok,thanks.waiting for it

**Comment by flyworker** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacea5zbihxzwa26pyhjb3rig6nqqzsrsa4klechsvd7cljtc2rxmuze 
#### Address 
> f1wbmcknidxdfkpxdkhk6mj2otkiexyobow3pa6qq
#### Datacap Allocated
> 100TiB
#### Signer Address
> f1hlubjsdkv4wmsdadihloxgwrz3j3ernf6i3cbpy
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacea5zbihxzwa26pyhjb3rig6nqqzsrsa4klechsvd7cljtc2rxmuze

**Comment by AnthnoySmith** [comment]
I just downloaded your app of ios and can upload files and images, but I found that I can't access any other people's public data. I don't think this issue meets the basic requirements of LDN.  Suggest other notaries can have a test before signing it.

**Comment by changlizhi** [comment]
HELLO @AnthnoySmith ,Publish your cid instead of just mention.And If you have deals between filecoin and IPFS,you will find that the cids of filecoin and IPFS is different,you cant search cid in our app with filecoin cid ,because we upload the data to filecoin(means cold data) but our app is based on IPFS(means hot data).If you want to verify the data of datacap, you can find  the dealid in ` https://filplus.d.interplanetary.one/clients/f01512103 ` and tell me,Then I will publish the name of that cid,so that you can retrieve it and verify that if my data is real or not.and then if you want access the data in filecoin with our app,I can give you a cid with ipfs.
If the data is not frequently requested and have dealed with filecoin datacap,We will unpin it from ipfs for more dist space,If the custom need to access again we will pin it on IPFS again,so if you cant access it ,there are 2 situations maybe:

1. the data cid is not ipfs cid
2. the data is unpined from ipfs

**Comment by IPFSUnion** [comment]
"Public" means the users don't need to know your CIDs or any other codes when they wanna download. As I understand this sort of application based on IPFS and Filecoin is for Private Data shared. It should also be encouraged. I remember there are lots of funding and incentive programs for these developers.

**Comment by changlizhi** [comment]
@IPFSUnion hi,are you @IPFSUnion2020 on slack?I'm @jim green on slack,could your account sign this issue now?

**Comment by IPFSUnion** [comment]
We can't sign yet because our address hasn't been updated by RKH now. We can give some advice for the other notaries' reference.

**Comment by s0nik42** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecjs6hvxnq37s4acxd7l7gzgilao7c543fs4bfkki26cq7gihbpkw 
#### Address 
> f1wbmcknidxdfkpxdkhk6mj2otkiexyobow3pa6qq
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1wxhnytjmklj2czezaqcfl7eb4nkgmaxysnegwii
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecjs6hvxnq37s4acxd7l7gzgilao7c543fs4bfkki26cq7gihbpkw

**Comment by changlizhi** [comment]
@s0nik42 thanks for signing for me!It's such a long term!
but @galen-mcandrew ,I checked my address on https://verify.glif.io/ and found that It's 50TiB on my address not 100TiB by singning,Is there some reason?

**Comment by changlizhi** [comment]
@galen-mcandrew ,could you please release the rest 50T datacap?I will close this issue,cause the waiting is so hard to wait.

**Comment by flyworker** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedglst3pikt6juclwd2ghdgdixifk47wc6fh7difri7nt2iflfw6y 
#### Address 
> f1wbmcknidxdfkpxdkhk6mj2otkiexyobow3pa6qq
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1hlubjsdkv4wmsdadihloxgwrz3j3ernf6i3cbpy
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedglst3pikt6juclwd2ghdgdixifk47wc6fh7difri7nt2iflfw6y

**Comment by Reiers** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacectamsjk3xemq3qrrehcblbyunzv6cgseawq6af5pggrr25xbwium 
#### Address 
> f1wbmcknidxdfkpxdkhk6mj2otkiexyobow3pa6qq
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1oz43ckvmtxmmsfzqm6bpnemqlavz4ifyl524chq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacectamsjk3xemq3qrrehcblbyunzv6cgseawq6af5pggrr25xbwium

**Comment by IreneYoung** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedwbcufxjm4rl7gg6xzhnjiwouas5lt6535q6jhfcooe6qryaxiai 
#### Address 
> f1wbmcknidxdfkpxdkhk6mj2otkiexyobow3pa6qq
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1d4gmpqz3execjj2wvrxuuhvbms5mzh7t7yqrviq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedwbcufxjm4rl7gg6xzhnjiwouas5lt6535q6jhfcooe6qryaxiai

**Comment by psh0691** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceca7axpi4kiwyq73ooy26m5gw5lau5csivij3falveyx6mdqfcbdq 
#### Address 
> f1wbmcknidxdfkpxdkhk6mj2otkiexyobow3pa6qq
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1qdko4jg25vo35qmyvcrw4ak4fmuu3f5rif2kc7i
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceca7axpi4kiwyq73ooy26m5gw5lau5csivij3falveyx6mdqfcbdq

**Comment by BigD-Exchange** [comment]
@changlizhi Hi! Great to see you have gotten approval for DataCap. If you are looking for storage providers to store these data or have any questions, please visit #bigdata-exchange on Filecoin Slack or reply here. 

We have strong demand from a diverse group of SPs, who are actively looking to onboard more data.

**Comment by liyunzhi-666** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec2gwa7lcuwnrbdgnt42ijp3td7s7lllwq5pv6npehijw6twumy2w 
#### Address 
> f1wbmcknidxdfkpxdkhk6mj2otkiexyobow3pa6qq
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1pszcrsciyixyuxxukkvtazcokexbn54amf7gvoq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec2gwa7lcuwnrbdgnt42ijp3td7s7lllwq5pv6npehijw6twumy2w

**Comment by changlizhi** [comment]
need sign

**Comment by Alex11801** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebt6slypltdonxxd72crpibpbi2kcz4ajagwcfbrx7fkvaqs2qcyk 
#### Address 
> f1wbmcknidxdfkpxdkhk6mj2otkiexyobow3pa6qq
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1hhippi64yiyhpjdtbidfyzma6irc2nuav7mrwmi
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebt6slypltdonxxd72crpibpbi2kcz4ajagwcfbrx7fkvaqs2qcyk

**Comment by changlizhi** [comment]
> @changlizhi Hi! Great to see you have gotten approval for DataCap and advancing the mission of preserving humanity’s most important information. If you are looking for storage providers to store these data or have any questions, please visit #bigdata-exchange on Filecoin Slack or reply here.
> 
> We have strong demand from a diverse group of SPs, who are actively looking to onboard more data.

Thanks @BigD-Exchange ,We Have found five sps for offline storage before,If they quit and we need to find more,We can search on slack or wechat group.

**Comment by filplus-checker** [comment]
## DataCap and CID Checker Report[^1]
 - Organization: `Stariver Technology Co., Ltd(四川星河飞天科技有限公司)`
 - Client: `f1wbmcknidxdfkpxdkhk6mj2otkiexyobow3pa6qq`
### Storage Provider Distribution
The below table shows the distribution of storage providers that have stored data for this client.

If this is the first time a provider takes verified deal, it will be marked as `new`.

For most of the datacap application, below restrictions should apply.
 - Storage provider should not exceed 25% of total datacap.
 - Storage provider should not be storing duplicate data for more than 20%.
 - Storage provider should have published its public IP address.
 - All storage providers should be located in different regions.

⚠️ [f01648376](https://filfox.info/en/address/f01648376) has sealed 68.30% of total datacap.

⚠️ [f01648376](https://filfox.info/en/address/f01648376) has unknown IP location.

⚠️ [f01128320](https://filfox.info/en/address/f01128320) has unknown IP location.

⚠️ [f01131460](https://filfox.info/en/address/f01131460) has unknown IP location.

⚠️ [f086423](https://filfox.info/en/address/f086423) has unknown IP location.

⚠️ [f0722658](https://filfox.info/en/address/f0722658) has unknown IP location.

⚠️ All storage providers are located in the same region.

| Provider                                                    | Location | Total Deals Sealed | Percentage | Unique Data | Duplicate Deals |
| :---------------------------------------------------------- | -------: | -----------------: | ---------: | ----------: | --------------: |
| [f01648376](https://filfox.info/en/address/f01648376)`new`  |  Unknown |         186.51 TiB |     68.30% |  172.43 TiB |           7.55% |
| [f01128320](https://filfox.info/en/address/f01128320)       |  Unknown |          45.51 TiB |     16.67% |   43.16 TiB |           5.17% |
| [f01131460](https://filfox.info/en/address/f01131460)       |  Unknown |          36.11 TiB |     13.22% |   35.00 TiB |           3.08% |
| [f086423](https://filfox.info/en/address/f086423)`new`      |  Unknown |           3.23 TiB |      1.18% |    3.16 TiB |           2.18% |
| [f0722658](https://filfox.info/en/address/f0722658)         |  Unknown |           1.73 TiB |      0.63% |    1.73 TiB |           0.41% |

![Provider Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/116/1671092519414.png)
### Deal Data Replication
The below table shows how each many unique data are replicated across storage providers.
- No more than 25% of unique data are stored with less than 4 providers.

⚠️ 100.00% of deals are for data replicated across less than 4 storage providers.

| Unique Data Size | Total Deals Made | Number of Providers | Deal Percentage |
| ---------------: | ---------------: | ------------------: | --------------: |
|       183.18 TiB |       196.74 TiB |                   1 |          72.04% |
|        26.74 TiB |        56.19 TiB |                   2 |          20.57% |
|         6.27 TiB |        20.16 TiB |                   3 |           7.38% |

![Replication Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/116/1671092520043.png)
### Deal Data Shared with other Clients
The below table shows how many unique data are shared with other clients.
Usually different applications owns different data and should not resolve to the same CID.

⚠️ CID sharing has been observed.

| Other Client                                                                                                                                                                                                              | Application                                                                                 | Total Deals Affected | Unique CIDs |          Verifier |
| :------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ | :------------------------------------------------------------------------------------------ | -------------------: | ----------: | ----------------: |
| [f1fd7pgiygdwnsvxqj7n3f4ixuioq5btgok25mgzi](https://filfox.info/en/address/f1fd7pgiygdwnsvxqj7n3f4ixuioq5btgok25mgzi)                                                                                                     | [四川星河飞天科技](https://github.com/filecoin-project/filecoin-plus-client-onboarding/issues/1325) |             6.27 TiB |      14,382 |         Steven Li |
| [f3wwiudiv2vjdswtc4aab5o3qs6ygeujrrixyv6a2<br/>z4o6aoma34rjayapsmwvqxxgn7aavmzomfquzwd2d<br/>n3fa](https://filfox.info/en/address/f3wwiudiv2vjdswtc4aab5o3qs6ygeujrrixyv6a2z4o6aoma34rjayapsmwvqxxgn7aavmzomfquzwd2dn3fa) | [Genesis](https://github.com/filecoin-project/filecoin-plus-client-onboarding/issues/1700)  |           767.50 GiB |         171 |         Steven Li |
| [f3ra4qdlsjp2nm5sji3p4fs2f5vnwn7yjgq43csz5<br/>low37s44lc3jyhec57kjonmfnjfrlwpx44bgwfr6h<br/>qboa](https://filfox.info/en/address/f3ra4qdlsjp2nm5sji3p4fs2f5vnwn7yjgq43csz5low37s44lc3jyhec57kjonmfnjfrlwpx44bgwfr6hqboa) | `anne`                                                                                      |             4.00 GiB |           1 |            Neo Ge |
| [f1ujcmcv4r7d2wldgsy3ckl5ko5tovyqewuwtf6gi](https://filfox.info/en/address/f1ujcmcv4r7d2wldgsy3ckl5ko5tovyqewuwtf6gi)                                                                                                     | `Glif auto verified`                                                                        |             1.50 GiB |           3 | Jonathan Schwartz |

[^1]: To manually trigger this report, add a comment with text `checker:manualTrigger`

**Comment by lvschouwen** [comment]
@changlizhi 
You are approaching the 6th allocation of datacap for this issue ... but what is going on here?
CID sharing and miners without locations?

I hope you can explain all of this before a notary signs this request.

**Comment by changlizhi** [comment]
hi @lvschouwen ,Long time to see the github.sorry for waiting!There are 20T DCs left now.
In the fifth transaction, we found two new SP to seal our data in order to meet the requirements. We hope to find some trusted SP, so all the SP's are sealed by sending data to SP through hard disk after we contact offline. However, the SP we find shields part of their public IP in order to prevent the download of too much data (it may also be caused by the detection of the detector outside China). Because we did not find enough SP
Even if we used the same allocation method when allocating different SP, there might be duplicate data when SP was sealed or some transactions did not send successfully, leading to the difference in proportion. We are contacting SP to open their public IP to extranet.
In addition, I would like to know how the detector works when detecting the proportion. If the detection still fails, we can ask SP to support your manual detection.

**Comment by cryptowhizzard** [comment]
Can i just ask....

You can't murder someone a little bit, You can't steal a little bit, You can't commit fraud a little bit and so on.

FIL+ rules => You need to take care that the data is readily retrievable and your miners need to be reachable.
Rules are rules and rules are in place for a reason. Please abide to them and message us when we can retrieve the data.

**Comment by lvschouwen** [comment]
@changlizhi 
Thanks for you reply. I have looked at your application and this was one of your answers.
![image](https://user-images.githubusercontent.com/6965171/216934550-4dc889f1-6ecc-4084-968b-b81b3d990342.png)

You agreed that ANYONE in the network can retrieve the data, which is not possible at this moment and thus you are failing to comply with FIL+ rules and the answers of your own application.

Can you please share the contact details of the SPs with MinerIDs mentioned in the report so we can work with them to retrieve the data?

**Comment by changlizhi** [comment]
@lvschouwen I see ,we will concact the SPs and ask them for confirm the lotus retrieve.
because of the chinese policy,they dont want to spread there infos up to now(the less the safe they think).

**Comment by lvschouwen** [comment]
@changlizhi 
Fine with me if they don't want to disclose information but you have applied for datacap and agreed that it would be stored under the rules of FIL+
So far you have demonstrated that the SPs you choice are not willing or able to work under the rules.

My advice; Stop the sealing immediately and use the remaining datacap you still have to proof to the community this LDN can uphold the rules of FIL+.

If not I am very afraid that after you have sealed all datacap under your last allocation, getting new datacap is going to be very difficult.

**Comment by changlizhi** [comment]
@lvschouwen OK,give me some time plz,I will concact them and make sure the data is openning for retrieval.

**Comment by changlizhi** [comment]
hi @lvschouwen ,they tried these days but not work,so they need your help,here is one of their software engerineer of sealing data @underway2014 ,maybe some configs should be changed.
@underway2014 ,look here!

**Comment by underway2014** [comment]
@changlizhi @lvschouwen Hello, we are trying to solve the problem. How do you configure miner so that it can be retrieved on the public network and display the location

**Comment by lvschouwen** [comment]
> @changlizhi @lvschouwen Hello, we are trying to solve the problem. How do you configure miner so that it can be retrieved on the public network and display the location

Hi @underway2014 
Please check https://lotus.filecoin.io/tutorials/lotus-miner/run-a-miner/#setup and then step 4 and further. Step 7 explains how you can publish your IP address to the chain so we can reach the miner.

Retrieval should automatically work, just make sure your asking price is 0 FIL.

**Comment by changlizhi** [comment]
Hi @lvschouwen ,@underway2014 had opened the port out ,and the other nodes are change to open too.
we check it with `lotus client retrieve --provider ...` command ,It worked! does it means successful?
how to report to this page like below tables or it's just ok now?

**Comment by lvschouwen** [comment]
checker:manualTrigger

**Comment by changlizhi** [comment]
checker:manualTrigger

**Comment by lvschouwen** [comment]
@changlizhi Still 4 out of 5 miners without IP / locations as you can see.

**Comment by changlizhi** [comment]
checker:manualTrigger

**Comment by herrehesse** [comment]
checker:manualTrigger

**Comment by changlizhi** [comment]
checker:manualTrigger

**Comment by changlizhi** [comment]
hi @lvschouwen ,the  f01648376 node's config is changed but step#6 returned `known`

**Comment by changlizhi** [comment]
checker:manualTrigger

**Comment by changlizhi** [comment]
checker:manualTrigger

**Comment by changlizhi** [comment]
Hi @lvschouwen ,the data is all opening now.

**Comment by cryptowhizzard** [comment]
Hi,

I am sorry but there is 1 PB stored with just one organisation. I don't have confidence that when i i sign for the next LDN tranche of 800 TB of datacap that suddenly you will follow the FIL+ rules. The risk is simply to high.

If you insist to continue your project i would like you to do KYC and make the data onboarding plan according to the rules of FIL+. [You can do so here](https://form.jotform.com/230337462961356)

When i received it and everything is ok i suggest to manually grant you 2 tranches of 50 TiB of datacap and when that is going ok, the 3rd of 200 TiB of datacap. When all this is going ok we can consider this LDN back on track and move with the next 800 TiB.
