### ISSUE TITLE
[DataCap Application]

### ISSUE THREAD

**Issue by Cloudyia** [filecoin-project/filecoin-plus-large-datasets#1160]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: DotWell
- Website / Social Media:http://www.dotwell.com/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):200TiB
- On-chain address for first allocation:f1ohytnins7faggh565z5vgstur2mnqvq3dmwwy7i

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Shenzhen DotWell Culture Communication Co., Ltd. (DotWell) is a diversified and integrated creative agency.
Services provided by Dotwell:
Live-action shooting/CG animation/KV/brand strategy/new media integrated marketing/MCN/game art & R&D/self-media business cooperation/column packaging/pan-entertainment content creation/H5/scene marketing exhibition display, etc.
```

What is the primary source of funding for this project?
```
It is mainly from our company.
```

What other projects/ecosystem stakeholders is this project associated with?
```
No other project stakenholders.
```

## Use-case details

Describe the data being stored onto Filecoin
```
Live shooting video/game video/brand video/product video/corporate video/entertainment video/plane/CG animation/KV/game art & R&D
```

Where was the data in this dataset sourced from?
```
It is from DotWell
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
(http://www.dotwell.com/work/#section2) you can watch the videos from us in the link.
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Confirmed it.
```

What is the expected retrieval frequency for this data?
```
twice a year.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
at least 3 years
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
perfer Asia
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Both online and offline transfer process are OK.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We pay attention to their work time and how much they cost.  We need comprehensive storage providers who can coorperate for a long time.
```

How will you be distributing deals across storage providers?
```
We will distribute different deals according to their distance. 
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Of course.
```

**Comment by Cloudyia** [comment]
@raghavrmadya @galen-mcandrew  sorry to bother you, Is there any update? Pls check the application~

**Comment by Cloudyia** [comment]
@raghavrmadya @galen-mcandrew Hi, Pls check it, i will answer your questions.

**Comment by raghavrmadya** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 200TiB

**Client address**

>f1ohytnins7faggh565z5vgstur2mnqvq3dmwwy7i

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 200TiB

**Client address**

> f1ohytnins7faggh565z5vgstur2mnqvq3dmwwy7i

**Comment by 1ane-1** [comment]
Can you provide more detailed information about other storage providers participated in this program, such as you can list SPs you have contacted with at present?

**Comment by Cloudyia** [comment]
> 

yes, we want to cooperate with 7 sps to be distributed storage our data. The sps are f01995046  f01789840  f01998923 f01986979  f01471028 f01975371 f01135719

**Comment by 1ane-1** [comment]
> > 
> 
> yes, we want to cooperate with 7 sps to be distributed storage our data. The sps are f01995046 f01789840 f01998923 f01986979 f01471028 f01975371 f01135719

i will follow the issue.

**Comment by 1ane-1** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebktdsplrhe5bvhzxyq762zwchxqqlgxpioixtcvj7qnfbpucazdo 
#### Address 
> f1ohytnins7faggh565z5vgstur2mnqvq3dmwwy7i
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1mdk7s2vntzm6hu35yuo6vjubtrpfnb2awhgvrri
#### Id
> 98cb92ea-54e2-42bf-8a03-020e441f9c78
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebktdsplrhe5bvhzxyq762zwchxqqlgxpioixtcvj7qnfbpucazdo

**Comment by cryptowhizzard** [comment]
Hello @Cloudyia 

I am checking on your LDN application.

It seems to me that the SP's you mention above do not exist. ( See below ).
However, it does seem that these are client wallets 

f01995046 belongs to f1zxzar2dhrytdrwepzycyo7itwq7fiuhed5ywmia _> #963 
f01789840 belongs to f1o7z3hrmxthl2yohnoabk2bmmveg6aoomatv52hq -> #1313
f01998923 belongs to f1jb32pfppwd66cctgarbjfq2bg7kvqjsxbcrreda -> #432 ( Piknik ) 
f01986979 belongs to f1m54rlpqha44mgfm3oa4nxc3exmq3k5azn7cv7fi ( Ghostbyte )
f01471028 belongs to f1r3d25hl2y7rqlsu2mgczdethy4qqjmkfdlmibfq ( FILSWAN ) / Nexrad
f01975371 belongs to f1zirctywra4s7rblvbmhzzjg6znzjqwb2luxhhlq Jiliantech
f01135719  belongs to f1sbu2duxou7f2zmykfsekmvnmarltwyvpupdxema

Can you tell me what the relationship is between your project and this clients? I would really like to know.


>>
root@proposals:~/downloadedcarfiles# lotus net connect f01995046
ERROR: getting miner info: failed to load miner actor state: actor code is not miner: account

root@proposals:~/downloadedcarfiles# lotus net connect f01789840
ERROR: getting miner info: failed to load miner actor state: actor code is not miner: account

root@proposals:~/downloadedcarfiles# lotus net connect f01998923
ERROR: getting miner info: failed to load miner actor state: actor code is not miner: account

root@proposals:~/downloadedcarfiles# lotus net connect f01986979
ERROR: getting miner info: failed to load miner actor state: actor code is not miner: account

root@proposals:~/downloadedcarfiles# lotus net connect f01471028
ERROR: getting miner info: failed to load miner actor state: actor code is not miner: account

root@proposals:~/downloadedcarfiles# lotus net connect f01975371
ERROR: getting miner info: failed to load miner actor state: actor code is not miner: account

root@proposals:~/downloadedcarfiles# lotus net connect f01135719
ERROR: getting miner info: failed to load miner actor state: actor code is not miner: account

**Comment by jamerduhgamer** [comment]
Hello @Cloudyia, why do you have 4 of PiKNiK's CIDs from our NEXRAD dataset? I don't believe we have never met before.

**Comment by Sunnyiscoming** [comment]
Any update here?

**Comment by Cloudyia** [comment]
> Any update here?

[f01016847]  US
[f01912253]  US
[f0866680]    Henan Province of China
[f0861588]    Henan Province of China
[f0101021]    Zhejiang Province of China
[f0147214]    Chengdu Province of China
[f02145020]  Guandong Province of China
Sorry for late to answer you. It is our mistake that leave the wrong SP information.we couldn't cooperate with them. It is so sorry. Now we have alreay contact these sps that would like to cooperate with us. If we can go for the next step?

**Comment by Cloudyia** [comment]
Pls check if we can going on. @Sunnyiscoming

**Comment by Sunnyiscoming** [comment]
Could you send an email to filplus-app-review@fil.org with your official domain in order to confirm your identity? Email name should includes the issue id #1160.

**Comment by Cloudyia** [comment]
@Sunnyiscoming The email has been sent. Pls check it .Thanks a lot.

**Comment by Cloudyia** [comment]
> Could you send an email to [filplus-app-review@fil.org](mailto:filplus-app-review@fil.org) with your official domain in order to confirm your identity? Email name should includes the issue id #1160.

@Sunnyiscoming  Hope you can check the email,thanks.

**Comment by Cloudyia** [comment]
@Sunnyiscoming

**Comment by cryptowhizzard** [comment]
Please check the comments of Piknik and do **not** re-open @Sunnyiscoming

**Comment by Cloudyia** [comment]
we will Keep going on.

**Comment by Cloudyia** [comment]
we hope going on.

**Comment by Cloudyia** [comment]
going on

**Comment by Cloudyia** [comment]
still no reply

**Comment by Cloudyia** [comment]
> > Could you send an email to [filplus-app-review@fil.org](mailto:filplus-app-review@fil.org) with your official domain in order to confirm your identity? Email name should includes the issue id #1160.
> 
> @Sunnyiscoming Hope you can check the email,thanks.

Hope your reply

**Comment by Cloudyia** [comment]
> > > Could you send an email to [filplus-app-review@fil.org](mailto:filplus-app-review@fil.org) with your official domain in order to confirm your identity? Email name should includes the issue id #1160.
> > 
> > 
> > @Sunnyiscoming Hope you can check the email,thanks.
> 
> Hope your reply

@Sunnyiscoming
