### ISSUE TITLE
[DataCap Application] 58.com

### ISSUE THREAD

**Issue by Aleta159** [filecoin-project/filecoin-plus-large-datasets#1161]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: 58.Com Inc.
- Website / Social Media: https://sz.58.com/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):400TiB
- On-chain address for first allocation:f17mevykuslebvw5x5j7btph4v4xhtn3igdnmwfzi

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
As a leading life service platform in China, 58's business covers various fields such as recruitment, real estate, car trading, second-hand goods trading, local life service and finance. In terms of user services, it is not only a platform for information interaction, but also a one-stop life service platform, while gradually establishing a full range of marketing solutions for merchants.
```

What is the primary source of funding for this project?
```
Our source is from our revenue.
```

What other projects/ecosystem stakeholders is this project associated with?
```
No others.
```

## Use-case details

Describe the data being stored onto Filecoin
```
In our real estate business, we have a mass of images and videos about houses introductions.
```

Where was the data in this dataset sourced from?
```
These photos were taken and produced by our employees.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
Yes, I've upload some samples.
https://drive.google.com/file/d/1M-cs32hgTPIjj1rorbXsqV_iMlRHGTWY/view?usp=sharing
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Ok, it is actually a public dataset.
```

What is the expected retrieval frequency for this data?
```
Not too often, maybe once a year.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
2 years.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Mainly Asia. We will also consider choosing other regions.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Yes, we will change data transfer process according to actual conditions-----both online and offline.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
I will choose reputable SPs for a long-term cooperation and run a check on them.
```

How will you be distributing deals across storage providers?
```
I would ensure that the data is distributed properly, under 25% to each one.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, we are well-prepared.
```

**Comment by swatchliu** [comment]
Could you send an email from your official mailbox to filplus-app-review@fil.org?

**Comment by Aleta159** [comment]
![w](https://user-images.githubusercontent.com/116624480/199210559-5d215160-e86b-4b9f-8a68-94adbbed2dfd.jpg)
@swatchliu ok!

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 400TiB

**Client address**

>f17mevykuslebvw5x5j7btph4v4xhtn3igdnmwfzi

**Comment by MatrixStorage** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebkcc2x5izvbjbwibn7rgcw5iw3qnnmtehdw3l46wjp7mdhda2qoa 
#### Address 
> f17mevykuslebvw5x5j7btph4v4xhtn3igdnmwfzi
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1tbxqwjxfyv7swsdin4einirlsfquv3vnmlapley
#### Id
> 0694ace9-4032-4e5f-b911-23a04e7f5ddd
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebkcc2x5izvbjbwibn7rgcw5iw3qnnmtehdw3l46wjp7mdhda2qoa

**Comment by PluskitOfficial** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedkzxpjl7aq7kabqnfssno6zb6kwfb6ivt6llbf2jt4mxrvbkelna 
#### Address 
> f17mevykuslebvw5x5j7btph4v4xhtn3igdnmwfzi
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1tgnlhtcmhwipfm7thsftxhn5k52velyjlazpvka
#### Id
> 0694ace9-4032-4e5f-b911-23a04e7f5ddd
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedkzxpjl7aq7kabqnfssno6zb6kwfb6ivt6llbf2jt4mxrvbkelna

**Comment by Sunnyiscoming** [comment]
Is there any problem with using datacap?

**Comment by Aleta159** [comment]
Yes

**Comment by clriesco** [comment]
Removed stale label and reopened issue :)

**Comment by Aleta159** [comment]
@clriesco Thanks!

**Comment by Aleta159** [comment]
Yes

**Comment by Aleta159** [comment]
Yes, open

**Comment by Aleta159** [comment]
Yes, need open.

**Comment by Aleta159** [comment]
Yes, need open.

**Comment by Aleta159** [comment]
Yes, need open.

**Comment by PluskitOfficial** [comment]
checker:manualTrigger

**Comment by BobbyChoii** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec2uetfuxal5vn3xfzy4qk7lz3besxylhso55z5krrng3rcqywogc 
#### Address 
> f17mevykuslebvw5x5j7btph4v4xhtn3igdnmwfzi
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1irqs2gmctiv3jcdfwuch7oxvf4ixh3k4b2wc24i
#### Id
> 4751f570-5838-47aa-9e86-63ec44c858d9
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec2uetfuxal5vn3xfzy4qk7lz3besxylhso55z5krrng3rcqywogc

**Comment by TakiChain** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb7royadkbpqeff5p2lgorae3bwubywkeq7jktxxxppmwlkxcto32 
#### Address 
> f17mevykuslebvw5x5j7btph4v4xhtn3igdnmwfzi
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f15impf3j2zcaex4lhyxndxswuuhv24vzstuqtxsi
#### Id
> 4751f570-5838-47aa-9e86-63ec44c858d9
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb7royadkbpqeff5p2lgorae3bwubywkeq7jktxxxppmwlkxcto32

**Comment by Casey-PG** [comment]
Willing to support and looking ahead to the process.

**Comment by Casey-PG** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecuifmabszipmxr4cao2ck5hwbgkjnyp6gup476ouc3npuurnrghs 
#### Address 
> f17mevykuslebvw5x5j7btph4v4xhtn3igdnmwfzi
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1d4yb3wags3mtddzesxoo63jv7dmlec3bq4yteni
#### Id
> 9c2f3020-0b3f-4c77-9bb9-78e828afc53c
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecuifmabszipmxr4cao2ck5hwbgkjnyp6gup476ouc3npuurnrghs

**Comment by PluskitOfficial** [comment]
checker:manualTrigger

**Comment by herrehesse** [comment]
![Screenshot 2023-11-14 at 10 10 21](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/70132857/56b8f798-1aaf-4f60-bf25-0aeb32a488ff)

Entity is fully self dealing under VPN as usual. Abusive notaries signing as usual.

@kevzak Close this LDN.

**Comment by Sunnyiscoming** [comment]
Hello, @Aleta159 per the https://github.com/filecoin-project/notary-governance/issues/922 for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

This information will be reviewed by Fil+ Governance team to confirm validity and then the application will be allowed to move forward for additional notary review.

**Comment by Filplus-govteam** [comment]
closing until clear list of SP entities and distribution is provided
