### ISSUE TITLE
[DataCap Application] <KUAIKAN>

### ISSUE THREAD

**Issue by wuszs** [filecoin-project/filecoin-plus-large-datasets#1162]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: kuaikan
- Website / Social Media: https://www.kuaikanmanhua.com/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 400TiB
- On-chain address for first allocation: f1slsumnbqsww6gm32afy62z2ee6dvzmjxld564ui

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Kuaikan (former name: Kuaikan Comics) is a mobile comic APP released by Kuaikan World (Beijing) Technology Co., Ltd. in 2014, providing users with high-definition full-color original comics at home and abroad to read.
On August 5, 2021, "Kuikan Comics" officially changed its name to "Kuikan", and announced the launch of a creative incentive plan. In the next three years, 1 billion yuan will be invested to support original comics, and another 1 billion yuan will be invested to join hands with partners to participate in the production of comics. . Kuaikan officially entered the global market in early 2021, and cooperated with 70 platforms around the world, covering 200 countries and regions, and currently has more than 200 million users.
```

What is the primary source of funding for this project?
```
User fees and company investment.
```

What other projects/ecosystem stakeholders is this project associated with?
```
None.
```

## Use-case details

Describe the data being stored onto Filecoin
```
Two-dimensional,TV animation (TV animation),network animation (WEB animation),theatrical animation (animation film),OVA animation/OAD animation,animation music,animation original.
```

Where was the data in this dataset sourced from?
```
Company Copyright and User Creation.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://www.kuaikanmanhua.com/
What this website presents is what we need to store.
```

Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes, we're pretty sure.
```

What is the expected retrieval frequency for this data?
```
1-2 times a year.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
Minimum 540 days.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Hong Kong.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Online download or offline mailing.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We prefer storage service providers with higher reliability.
```

How will you be distributing deals across storage providers?
```
Store to multiples SPs.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes.
```

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 400TiB

**Client address**

> f1slsumnbqsww6gm32afy62z2ee6dvzmjxld564ui

**Comment by Sunnyiscoming** [comment]
Hi @wsz-llh 
If you still want to apply for datacap, you can ask more notaries to do client due diligence and approve the application in slack channel. https://app.slack.com/client/TEHTVS1L6/C036JKD8NVA/thread/C03BG1MNQ4T-1673888660.823499

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Looking at your application i have some questions:
As you are brand new on Github and have no history of past applications it seems to me that applying for 5PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?

Can you show us visible proof of the size of your data and the storage systems you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230337462961356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!
