### ISSUE TITLE
[DataCap Allocation] - Lighthouse

### ISSUE THREAD

**Issue by nandit123** [filecoin-project/filecoin-plus-large-datasets#1163]
---
name: Large Dataset Notary application
about: Clients should use this application form to request a DataCap allocation via a LDN for a dataset
title: "Lighthouse"
labels: 'application, Phase: Diligence'
assignees: ''

---
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Lighthouse.Storage
- Website / Social Media: https://www.lighthouse.storage
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 1PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 50TiB
- On-chain address for first allocation: f1dncjh6bq7lqrkml5tkjw3kuz2fauzugxh4lkypy
- Region: Asia (excl. Greater China)

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Lighthouse provides the ability of perpetual storage on Filecoin. We started the project back in October, 2021. We have a live version of product focussed on web3 developers to easily use IPFS and Filecoin in their projects
```

What is the primary source of funding for this project?
```
Raised funds from various web3 investors like protocol labs, long hash ventures, ngc ventures, big brain holdings, fenbushi capital, etc. Went through Long hash ventures' Filecoin Frontier accelerator from Oct'21 to Jan'22
```

What other projects/ecosystem stakeholders is this project associated with?
```
Filecoin ecosystem, FVM, Optimism, Polygon, Shardeum, etc.
```

## Use-case details

Describe the data being stored onto Filecoin
```
Data will be images, videos, json, folders or other file types of various NFT, DAO and other use cases related to web3
```

Where was the data in this dataset sourced from?
```
Lighthouse users using Files Dapp, Lighthouse CLI and Lighthouse SDK.

- Files dApp - https://files.lighthouse.storage
- CLI - https://lighthouse-1.gitbook.io/lighthouse-1/cli-tool/overview
- Javascript SDK - https://lighthouse-1.gitbook.io/lighthouse-1/lighthouse-sdk/overview
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://gateway.lighthouse.storage/ipfs/QmezCAJVSBmEchhJePiXptscNsyPeBnXdyoLCYJH9yWg5g
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes
```

What is the expected retrieval frequency for this data?
```
Few times a week
```

For how long do you plan to keep this dataset stored on Filecoin?
```
We aim to store data perpetually, plan is to incentivise our clients with storage and then when the deal period ends, they clients potentially start paying for renewals
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Asia - Singapore, Korea
Europe - Great Britain, France
North America - USA, Canada

```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Online data transfer
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We will be using their past reputation, storage capacity, geo-location to determine the right storage providers for our data
```

How will you be distributing deals across storage providers?
```
Store to multiple SPs to ensure redundancy
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes we have the adequate resources and funding
```

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 1PiB

**Expected weekly DataCap usage rate**

> 50TiB

**Client address**

>f1dncjh6bq7lqrkml5tkjw3kuz2fauzugxh4lkypy

**Comment by Fenbushi-Filecoin** [comment]
Can you provide more details about the data storage plan? Thanks

**Comment by nandit123** [comment]
Hi, Lighthouse has an SDK (refer https://www.lighthouse.storage/documentation) for storage that can easily be used for devs to integrate into their backend or frontend dapps and store data on Filecoin. Users can also upload files to Lighthouse using our files dapp (https://files.lighthouse.storage). All this data is bundled together and stored on the filecoin miners.

**Comment by nandit123** [comment]
The plan is to replicate users data across multiple filecoin miners depending on the past reputation and also their geographical location to ensure that there are enough data guarantees. Miners list f01662887, f01606849, f01602479, f01681808, f01579009, etc.

**Comment by nandit123** [comment]
![Screenshot 2022-12-08 at 2 52 23 PM](https://user-images.githubusercontent.com/19206670/206408430-b6357514-1acc-43c6-b7e7-6ec3ccdfcc56.png)

**Comment by Tom-OriginStorage** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedhp3kfrlgijt4s27q6ni7vpgakvbuq43gs2qwz7ho5ij6iybxwn6 
#### Address 
> f1dncjh6bq7lqrkml5tkjw3kuz2fauzugxh4lkypy
#### Datacap Allocated
> 25.00TiB
#### Signer Address
> f1q6bpjlqia6iemqbrdaxr2uehrhpvoju3qh4lpga
#### Id
> abd215ae-5aa7-4036-9d5e-81fccf1b1d08
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedhp3kfrlgijt4s27q6ni7vpgakvbuq43gs2qwz7ho5ij6iybxwn6

**Comment by Fenbushi-Filecoin** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb4zfhahfufvvtc6xf6uiahbblio3vjwshduyyel24tswwu5dn4rg 
#### Address 
> f1dncjh6bq7lqrkml5tkjw3kuz2fauzugxh4lkypy
#### Datacap Allocated
> 25.00TiB
#### Signer Address
> f1yqydpmqb5en262jpottko2kd65msajax7fi4rmq
#### Id
> abd215ae-5aa7-4036-9d5e-81fccf1b1d08
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb4zfhahfufvvtc6xf6uiahbblio3vjwshduyyel24tswwu5dn4rg

**Comment by Sunnyiscoming** [comment]
Is there any problem with using datacap?

**Comment by Sunnyiscoming** [comment]
Hello, @nandit123 per the https://github.com/filecoin-project/notary-governance/issues/922 for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

This information will be reviewed by Fil+ Governance team to confirm validity and then the application will be allowed to move forward for additional notary review.
