### ISSUE TITLE
[DataCap Application] Changsha Yingtong Information Technology Co - opfilm

### ISSUE THREAD

**Issue by zcfil** [filecoin-project/filecoin-plus-large-datasets#1166]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Changsha Yingtong Information Technology Co., Ltd
- Website / Social Media:http://www.opfilm.cc
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):100TiB
- On-chain address for first allocation:f1rabmbft72reiqvq4wwda34gi7wpbawevjjtrg7q

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Changsha Yingtong Information Technology Co., Ltd. is a professional surgical teaching equipment manufacturer in China. With nearly 200 hospital user cases, it has become a well-known brand in the industry and the only manufacturer in the industry that develops and designs dedicated front-end host and receiving equipment for surgical teaching applications. All products have passed SGS medical safety certification and EMC electromagnetic compatibility certification.

The company leads the development of the industry with innovation, integrates advanced technologies such as intelligent imaging, media transmission, industrial control, and remote video, and has products and solutions such as digital operating rooms, surgical teaching systems, ICU medical systems, telemedicine, intelligent medicine, and big health image cloud.
```

What is the primary source of funding for this project?
```
Some clients and partners jointly contribute
```

What other projects/ecosystem stakeholders is this project associated with?
```
N.A. 
```

## Use-case details

Describe the data being stored onto Filecoin
```
Surgical videos from hospitals all over the country for academic research
```

Where was the data in this dataset sourced from?
```
These data are from hospitals, which have a large number of surgical video data to store. A large amount of such surgical video data will be generated every day, which will be provided to doctors around the world for academic research and contribute to the medical progress of all mankind
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://drive.google.com/drive/folders/1i6eATk4q3hpzCU3LqScfOpQreuM15gT6
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes, anyone can access the data
```

What is the expected retrieval frequency for this data?
```
First read about 5-10 times, and will be only read when the data in caches of relay nodes expired.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
If possible, I hope it will last forever. If not, the longer the better
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Greater China, or around the world
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
We have our own IDC machine room, which can provide network bandwidth download, or mail hard disks to storage providers
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We will take the initiative to obtain SP. We also accept SP's initiative to contact us. Our data will be stored in multiple SPs to ensure distributed storage and data security. We periodically retrieve data to ensure that it is retrievable.
```

How will you be distributing deals across storage providers?
```
At least 5 SP
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
We participate in the filecoin project from the test network, the space race and SlingShot.
We have some nodes that have been used for a long time, such as f02528(23.18PiB). We also have some nodes that have high power, such as f01756683 (12PiB), f01859603(8.6PiB), f01877184 (8.7PiB),f0723827(14.29PiB).Over the past two years, we have obtained many block rewards and resources, and we have the ability to start trading immediately after obtaining DataCap
```

**Comment by a295461148** [comment]
Dear Kevin-FF-USA @raghavrmadya : We are real big data storage providers. We have a lot of storage infrastructure, a lot of fil tokens, and a lot of data sets. But at present, we are very troubled. We have not obtained the DC. We need to spend a lot of cash to purchase the DC to participate in the infrastructure construction of filecoin. We have a headache because the applied data has not passed。
We can provide our strength: 200P storage capacity for hardware infrastructure, 600000 fil tokens, and a large amount of real data.

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 100TiB

**Client address**

>f1rabmbft72reiqvq4wwda34gi7wpbawevjjtrg7q

**Comment by Fil-ZC** [comment]
I want to say that your mechanism is not complete, how can I use the data set approved? The second round of audit card has no one to deal with it, can you help to deal with it? So many fair people are sleeping?

**Comment by kernelogic** [comment]
Could you provide some data samples and prove it is over 500T of original data?

**Comment by newwebgroup** [comment]
Hey @zcfil 
According to the data samples provided, the data should belong to “厚凯医疗”
”长沙影通信息技术有限公司“It looks like a company providing technical services.
1. Who does the Medical data belong to?
2. Have you obtained the authorization to store these medical data on Filecoin?

<img width="1274" alt="image" src="https://user-images.githubusercontent.com/100118145/206082060-24642b2d-e6f9-438f-baa3-98aa8532aeb5.png">

**Comment by zcfil** [comment]
Hi.@newwebgroup 
1.These data are recorded videos of academic research jointly conducted by major hospitals, which are open.And they are all our customers
2.They are all our customers' data, and with their consent, they are willing to back up these data to filecion for all medical practitioners to learn and contribute to medical progress around the world

**Comment by zcfil** [comment]
@kernelogic  [https://drive.google.com/file/d/1Xdz9w1rsOCpe2bDV4IsmB1c3zb34J61R/view?usp=share_link](This is a data sample)
![image](https://user-images.githubusercontent.com/45065975/206118885-b3fe2982-aa76-4c19-9c65-a013b5df8310.png)

This is the screenshot of our server data：
![16703965568140](https://user-images.githubusercontent.com/45065975/206118462-019ac4df-642a-4352-bda0-4fceb2562c4e.png)
![image](https://user-images.githubusercontent.com/45065975/206118590-ada50dc7-a690-4b56-b9d3-2e0923b551cc.png)

**Comment by kernelogic** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceafxhdyyc4ndlsjzytaovyuf6lrswvlkyvcpm4urtbpdhkxcvbtdc 
#### Address 
> f1rabmbft72reiqvq4wwda34gi7wpbawevjjtrg7q
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### Id
> 2cb0674a-2cbd-4a7f-8293-0b9a1c53eea8
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceafxhdyyc4ndlsjzytaovyuf6lrswvlkyvcpm4urtbpdhkxcvbtdc

**Comment by zcfil** [comment]
@newwebgroup Could you approve it for us? Thank you very much

**Comment by newwebgroup** [comment]
1：Could you send an email to [filplus-app-review@fil.org](mailto:filplus-app-review@fil.org) ？
2：Can you provide more detailed information about other storage providers participated in this program, such as you can list SPs you have contacted with at present?

**Comment by zcfil** [comment]
@newwebgroup We have sent some SPs we are contacting to your mailbox. If necessary, we can ask them to provide me with a private key signature to verify the authenticity

**Comment by newwebgroup** [comment]
Please provide a screenshot after sending the verification email to the governance team

**Comment by zcfil** [comment]
Hi,@newwebgroup 
This is the screenshot of the email I sent
![image](https://user-images.githubusercontent.com/45065975/206393751-208843bb-936a-4626-b412-c1ec76f28b7e.png)

**Comment by newwebgroup** [comment]
@zcfil  Hey , you need to show your work email suffix to complete KYB certification.

**Comment by ZC-FILSZ** [comment]
@newwebgroup Hi, I've cut it off
![image](https://user-images.githubusercontent.com/29709913/206658337-8c45d8a4-21b7-438e-94fe-871a0cc048fb.png)

**Comment by zcfil** [comment]
@newwebgroup Hi,I have taken a screenshot again
![image](https://user-images.githubusercontent.com/45065975/206674431-1dc31466-24c1-40a5-bc6a-0acc85d7eabe.png)

**Comment by newwebgroup** [comment]
Please use the enterprise mailbox with _opfilm.cc_ as the suffix for verification.

**Comment by newwebgroup** [comment]
Any updates? @zcfil

**Comment by zcfil** [comment]
Hi @newwebgroup, I resend the message
<img width="878" alt="16708289597939" src="https://user-images.githubusercontent.com/45065975/206983926-9a003bdc-65aa-4896-b65a-16f92733053f.png">

**Comment by newwebgroup** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedhk7zvfp5dff27cwsrbv5zjcid7q2h5equ4pw2tnvqyjadiwtkuy 
#### Address 
> f1rabmbft72reiqvq4wwda34gi7wpbawevjjtrg7q
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1e77zuityhvvw6u2t6tb5qlnsegy2s67qs4lbbbq
#### Id
> 2cb0674a-2cbd-4a7f-8293-0b9a1c53eea8
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedhk7zvfp5dff27cwsrbv5zjcid7q2h5equ4pw2tnvqyjadiwtkuy

**Comment by filplus-checker** [comment]
## DataCap and CID Checker Report[^1]
 - Organization: `Changsha Yingtong Information Technology Co., Ltd`
 - Client: `f1rabmbft72reiqvq4wwda34gi7wpbawevjjtrg7q`
### Storage Provider Distribution
The below table shows the distribution of storage providers that have stored data for this client.

If this is the first time a provider takes verified deal, it will be marked as `new`.

For most of the datacap application, below restrictions should apply.
 - Storage provider should not exceed 25% of total datacap.
 - Storage provider should not be storing duplicate data for more than 20%.
 - Storage provider should have published its public IP address.
 - All storage providers should be located in different regions.

⚠️ [f01660795](https://filfox.info/en/address/f01660795) has sealed 100.00% of total datacap.

⚠️ All storage providers are located in the same region.

| Provider                                              |                Location | Total Deals Sealed | Percentage | Unique Data | Duplicate Deals |
| :---------------------------------------------------- | ----------------------: | -----------------: | ---------: | ----------: | --------------: |
| [f01660795](https://filfox.info/en/address/f01660795) | Shenzhen, Guangdong, CN |          32.00 GiB |    100.00% |   32.00 GiB |           0.00% |

![Provider Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/1166/1671098805096.png)
### Deal Data Replication
The below table shows how each many unique data are replicated across storage providers.
- No more than 25% of unique data are stored with less than 4 providers.

⚠️ 100.00% of deals are for data replicated across less than 4 storage providers.

| Unique Data Size | Total Deals Made | Number of Providers | Deal Percentage |
| ---------------: | ---------------: | ------------------: | --------------: |
|        32.00 GiB |        32.00 GiB |                   1 |         100.00% |

![Replication Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/1166/1671098805693.png)
### Deal Data Shared with other Clients
The below table shows how many unique data are shared with other clients.
Usually different applications owns different data and should not resolve to the same CID.

✔️ No CID sharing has been observed.

[^1]: To manually trigger this report, add a comment with text `checker:manualTrigger`

**Comment by newwebgroup** [comment]
checker:manualTrigger

**Comment by zcfil** [comment]
@newwebgroup Dear notary, how do I continue to obtain DataCap?

**Comment by herrehesse** [comment]
Dear Applicant,

Due to the increased amount of erroneous/wrong Filecoin+ data recently, on behalf of the entire community, we feel compelled to go deeper into datacap requests. Hereby to ensure that the overall value of the Filecoin network and Filecoin+ program increases and is not abused.

Please answer the questions below as comprehensively as possible.

**Customer data**

- Could you demonstrate exactly how and to what extent customer contact occurred? 

We expect that for the onboarding of customers with the scale of an LDN there would have been at least multiple email and perhaps several chat conversations preceding it. A single email with an agreement does not qualify here.

- Did the customer specify the amount of data involved in this relevant correspondence?

- Why does the customer in question want to use the Filecoin+ program? 

_Should this only be soley for acquiring datacap this is of course **out of the question**. The customer must have a legitimate reason for wanting to use the Filecoin+ program which is intended as a program to store useful and public datasets on the network._ 

- Why is the customer data considered Filecoin+ eligible?

_(As an intermediate solution Filecoin offers the FIL-E program or the glif.io website for business datasets that do not meet the requirements for a Filecoin+ dataset)_


**Files and Processing**

- Could you please demonstrate to us how you envision processing and transporting the customer data in question to any location for preparation?
- Would you demonstrate to us that the customer, the preparer and the intended storage providers all have adequate bandwidth to process the set with its corresponding size?
- Would you tell us how the data set preparer takes into account the prevention of duplicates in order to prevent data cap abuse?


Hopefully you understand the caution the overall community has for onboarding the wrong data. We understand the increased need for Filecoin+, however, we must not allow the program to be misused. Everything depends on a valuable and useful network, let's do our best to make this happen. Together.

**Comment by herrehesse** [comment]
@zcfil can you explain why your website says "HELLO" in text only?

**Comment by zcfil** [comment]
@herrehesse Ouch, we replaced the official server deployment website two days ago, and did not notice this problem. We have restored it to normal. Thank you for your reminder.

**Comment by herrehesse** [comment]
@zcfil thanks for your quick answer! Can you also assist me with the above questionnaire?

**Comment by newwebgroup** [comment]
@zcfil You need to find two new notaries to sign for you to get the quota.

**Comment by cryptowhizzard** [comment]
Good morning

Pardon me for my Dutch but:

"Changsha Yingtong Information Technology Co., Ltd. is a professional surgical teaching equipment manufacturer in China."
"We also have our own miners on the filecoin network, so we are very clear about the operation mode of filecoin"

Where did we go wrong here? Are surgical teaching manufacturers also professional miners in China? Help me understand please.

**Comment by zcfil** [comment]
Hi @cryptowhizzard ，
Some of our partners are engaged in filecion storage related businesses. We listened to their suggestions before storing data in filecion

**Comment by cryptowhizzard** [comment]
Hello @zcfil 

Thanks. After translating the images above there are things more clear to me now. You are applying and the person in the hospital is your client. He is working there as i understand and you offered him to store his data on Filecoin.

From what i see above the first tranche is already allocated. The problem there is that it is not allocated according to the rules of FIL+. The SP's used are involved in LDN applications who are not compliant with the FIL+ rules. You can [check here](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/512)

>>
Since this is the 3rd allocation, the following restrictions have been relaxed:
Storage provider should not exceed 70% of total datacap.
Storage provider should not be storing duplicate data for more than 20%.
Storage provider should have published its public IP address.
**_All storage providers should be located in different regions._**
>>

Can you let us know if there is still interest from your side to get this application on the right track? It means storing with SP's with a good reputation and, since there must be diversity in region, also outside China.

**Comment by zcfil** [comment]
Hello @cryptowhizzard

**Comment by zcfil** [comment]
Hello @cryptowhizzard 

Thank you for your reply.
I'm very interested in getting this application on track,And I have contacted high-quality storage suppliers outside China, such as Japan, Hong Kong and Singapore,I believe that we can distribute reasonably according to the rule of FIL+in the future.

**Comment by cryptowhizzard** [comment]
Thanks for that.

If you can give me a list of SP’s you will use for next allocation, with good reputation then i will sign asap

**Comment by zcfil** [comment]
Due to the limited quota, I may temporarily allocate it to the following nodes

**Comment by zcfil** [comment]
Due to the limited quota, I may temporarily allocate it to the following nodes
f01938674
f01923786
f01836766
f0872282
is this OK？

**Comment by cryptowhizzard** [comment]
Hello @zcfil 

All the SP's you mention belong to one organization as far as i can see. That is not good.
Second, i am missing their contact information. Can you provide that?

I would like to see 2 independent organizations at minimum and some diversity at least. Everything is in HK/China from the SP's you gave me.

>>
f0872282 -> {12D3KooWEBLH2HU5zXHSnbTJoWPLVnzMH47gexN9XcNypUdUEhYn: [/ip4/103.201.24.105/tcp/50001]}
ERROR: failed to parse multiaddr "f0872282": must begin with /

You have new mail in /var/mail/root
root@proposals:~/api/fullauto# lotus net connect f01836766
f01836766 -> {12D3KooWFqpihaLDW5VMYCpxrg6HX7Mm9PtxFUvEJcJXzydSkiRp: [/ip4/103.44.239.188/tcp/50001]}
ERROR: failed to parse multiaddr "f01836766": must begin with /

root@proposals:~/api/fullauto# lotus net connect f01923786
f01923786 -> {12D3KooWJ9YWSrjpvSmMy7KL9NJwXgreiBBVi1KkVTBEMWmLeTCe: [/ip4/154.23.114.17/tcp/50001]}
ERROR: failed to parse multiaddr "f01923786": must begin with /

root@proposals:~/api/fullauto# lotus net connect f01938674
f01938674 -> {12D3KooWSqR5FMNJg7zJUBf56qeY6azkUqDpvsxYWp6F81EcziEm: [/ip4/183.61.189.117/tcp/50001]}
ERROR: failed to parse multiaddr "f01938674": must begin with /
>>

**Comment by zcfil** [comment]
Sorry, we are contacting organizations in Singapore. I believe we can reach cooperation soon. I can give you their contact information, but most of us use WeChat for communication. Do you need to give you WeChat.

**Comment by cryptowhizzard** [comment]
I prefer their e-mail then + wechat for their contact. As long as i can reach them to verify i am ok for now.

Btw, you are required to stay in contact with them for the deal duration period ( As long as the storage of your data goes for the retrieval period ). I would recommend not to take "just some" . There are plenty applications here on GIT who went into trouble just because of that as their SP's went "bad".

**Comment by zcfil** [comment]
Hello @cryptowhizzard

**Comment by zcfil** [comment]
Hello @cryptowhizzard 
This is our latest SP and their contact information

f01938674&f01836766 In Chinese Mainland  email:469230190@qq.com     

f01923786&f0872282 In HK email:luozhenjun@szfil.com

f01877184 In Singapore email:8954056@gamil.com

**Comment by cryptowhizzard** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced53jtrbzdsfiyml4k4f7yueyzqsauh5zwdazcuh7zaejlbuwsaii 
#### Address 
> f1rabmbft72reiqvq4wwda34gi7wpbawevjjtrg7q
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1krmypm4uoxxf3g7okrwtrahlmpcph3y7rbqqgfa
#### Id
> 755932c9-9980-4dd1-9cdf-9fd2099d0c9f
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced53jtrbzdsfiyml4k4f7yueyzqsauh5zwdazcuh7zaejlbuwsaii

**Comment by Sunnyiscoming** [comment]
Hi @wsz-llh You need one more notary approve this application. You can ask more notaries to do client due diligence and approve the application in slack channel. https://app.slack.com/client/TEHTVS1L6/C036JKD8NVA/thread/C03BG1MNQ4T-1673888660.823499

**Comment by zcfil** [comment]
@DaYouGroup Hello,I will allocate these data reasonably next time.

**Comment by Normalnoise** [comment]
checker:manualTrigger

**Comment by cryptowhizzard** [comment]
checker:manualTrigger

**Comment by data-programs** [comment]
<img width="32" alt="KYC" Verified src="https://stable.filplus.storage/images/filplus-kyc-verified-badge.png"/>

This user’s identity has been verified through [filplus.storage](https://filplus.storage)
