### ISSUE TITLE
[DataCap Application]  - <Schutten>

### ISSUE THREAD

**Issue by Kura2049** [filecoin-project/filecoin-plus-large-datasets#1169]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Schutten
- Website / Social Media:https://cn.schutten-solar.com/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):100TiB
- On-chain address for first allocation:f1hljsfuntd3epc633crzd6vxmjfya3k3yiww6wlq

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Anhui Shutten-solar Co., Ltd. is a photovoltaic module manufacturer and an expert in integrated photovoltaic solutions. We focus on the research and development, manufacturing, distribution of high-efficiency photovoltaic modules, as well as project development, EPC, operation and maintenance, project investment and financing, etc., and provide customers with comprehensive solutions for the entire life cycle of photovoltaic power plants. Since its establishment, Suneng Energy has sold more than 9GW of high-efficiency photovoltaic modules worldwide, developed and constructed more than 500MW of photovoltaic power station projects, and has business in more than 100 countries and regions around the world. with the stable expansion of business all over the world, our marketing plan to build up an international advertising and marketing system including aderstising pictures,vidoes, live stream.
```

What is the primary source of funding for this project?
```
company business income
```

What other projects/ecosystem stakeholders is this project associated with?
```
not yet
```

## Use-case details

Describe the data being stored onto Filecoin
```
The data we plan to store on filecoin are some public advertising pictures and videos talking about our products and lifestyle in offical webiste, youtube, tiktok focusing on the clients abroad to expand our business in a faster way.
```

Where was the data in this dataset sourced from?
```
pictures/vidoes shot and edited by our own team/public media
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://www.enf.com.cn/%E5%AE%89%E5%BE%BD%E6%97%AD%E8%83%BD%E7%94%B5%E5%8A%9B%E8%82%A1%E4%BB%BD%E6%9C%89%E9%99%90%E5%85%AC%E5%8F%B8 https://www.youtube.com/watch?v=EYf9cQ3t16k                          https://www.youtube.com/watch?v=7r2gz-L-tFA                                                                                     
https://www.youtube.com/watch?v=Un-vQditUu4                                                                                  
https://www.youtube.com/watch?v=n_bG_8FaKgo                                                                                                        
https://cn.schutten-solar.com/news/29.html                                                                                                                  
https://cn.schutten-solar.com/news/29.html                                                                                                                  
https://cn.schutten-solar.com/news/21.html                                                                                                                  
https://cn.schutten-solar.com/company_profile.html#w_grid-1638501031635
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
yes
```

What is the expected retrieval frequency for this data?
```
frequently
```

For how long do you plan to keep this dataset stored on Filecoin?
```
Permanent storage or five years at least
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
China,Thailand,India,Europe
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
offline
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
Currently we prefer SPs in China and prefer the SPs with rich experience to help us blend into Web3. If everything goes well, SPs in Thailand, India,Europe will be  considered.
```

How will you be distributing deals across storage providers?
```
2 copies per client and then distribute quota and files fairly
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
yes
```

**Comment by cryptowhizzard** [comment]
Hi!

The data indicated in this request is ( at most ) 10 GB. Why are you applying for a 5 PB datacap if i may ask?

**Comment by Kura2049** [comment]
> Hi!
> 
> The data indicated in this request is ( at most ) 10 GB. Why are you applying for a 5 PB datacap if i may ask?

hi there. sorry for the late reply and thanks for your question. the data sample is just for reference and check, I think. To further  move forward our global expansion in near future, we will have more and more dataset in a very fast way, as well, we may work with data provider supplier in this industry which are also interested in a creative way to store the data like products brochure, video introduction, industry research, campain, live stream. That is why we choose to give a shot here to see how traditional industry to develop in a new way.

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 100TiB

**Client address**

>f1hljsfuntd3epc633crzd6vxmjfya3k3yiww6wlq

**Comment by cryptowhizzard** [comment]
Hello,

I am familiar with the people of this solar company. They are not aware of any requests afaik.

Are you going to scrape their website without their consent here? 
Second , the size of this website is around 10 GB at max. What are you intending to do with this datacap?
