### ISSUE TITLE
[DataCap Application] TVCC

### ISSUE THREAD

**Issue by seong-k** [filecoin-project/filecoin-plus-large-datasets#117]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: TVCC
- Website / Social Media: www.tvcc.kr / https://www.youtube.com/c/TVCC-Broadcast
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 1PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 10TiB
- On-chain address for first allocation: f3tbfu6dptaui5uwdt7tlhzmovocz47z2fv34dewwhvkf6heel63zqv6ro7we5fvfzndmofel64dggk5vdr5rq

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
TVCC, founded in 2018, is a media group specialized in blockchain information, delivering the fastest and the accurate information about domestic blockchain and cryptocurrency. We are not only striving to become a mass media in the blockchain ecosystem by offering content and services such as broadcasts and interviews with specialists in the industry but also contributing to sustainable development in society. 

As mentioned before, TVCC creates the latest news specifically about the cryptocurrency and blockchain industry. So far, TVCC has made various blockchain content such as meetups, consortium, 360° VR(Virtual Reality), and sitcoms. Recently we are developing media content to introduce recent trends and issues to audiences about IPFS and Filecoin. 

TVCC is now planning to develop K-pop, XR, distributed storage solution, and Filecoin Explorer, collaborating with stakeholders related to other TVCC projects and ecosystems. All content which is produced by TVCC is being stored on Filecoin. Moreover, all processes listed so far will be created into video content for introduction to our subscribers.

```

What is the primary source of funding for this project?
```
Mainly equity, commercial advertisement etc..
```

What other projects/ecosystem stakeholders is this project associated with?
```
‘Ido Co., Ltd.’, which manages a music chart and media platform named UVP 
‘Global Cyber University, which is in charge of K-pop Academy joint operation
‘Ujoonet’, which develops distributed storage application
‘Cashierest’, one of the domestic cryptocurrency exchanges in South Korea
‘Block Data Bank’, which develops Filecoin Explorer etc.

```

## Use-case details

Describe the data being stored onto Filecoin
```
As an example, news videos, K-pop performance videos, and other cultural videos are stored onto Filecoin.
```

Where was the data in this dataset sourced from?
```
This data came from all live and VOD videos that TVCC films and produces firsthand. Also, TVCC is planning to produce performance videos as well by itself. Currently, TVCC is preparing to build an XR studio as well.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
Yes, it is sharable. Here is the link to Youtube Channel for the sample.
https://www.youtube.com/c/TVCC-Broadcast

```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes, (But for private data such as sort of kpop contents, only certain authorized people can access it.)
```

What is the expected retrieval frequency for this data?
```
It depends on the customer's situation. Some individual customers may want to share directly to a variety of devices as soon as they store it in Filecoin network, and some enterprise customers may simply want to keep it for a long time. We are implementing functions that enable both.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
We believe that for individuals, this document will be a permanent archive (but may be equal to or extended sector life at the request of the customer).
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Initially, it wants to be stored in Korea, but ultimately all over the world.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
We are based on an online deal. As confirmed, 30GB files can be saved if there is no network problem.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We are testing storage deals to various miners.
```

How will you be distributing deals across storage providers?
```
We are testing with miners who will be aggressive with various clients and looking for more miners.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
who is offering free storage deal, thus we are planning to save files on the free storage. We also found a company that already has developed a file upload solution, so we are planning to collaborate with this company as well.
```

**Comment by galen-mcandrew** [comment]
## Multisig Notary requested
#### Total DataCap requested 
> 1PiB
#### Expected weekly DataCap usage rate 
> 10TiB

**Comment by star-Kang** [comment]
Dear @galen-mcandrew ,

Hope everything is going well. We've requested large dataset recently, and received the message like this : @filecoin-plus-bot filecoin-plus-bot added status:AddedOnchain and removed status:StartSignOnchain labels 6 days ago.  After this message, the conversation between you and us was closed, but the large dataset has not been delivered yet to us.

If you already have sent to us, we are wondering if there was an error in the process of allocation. We just want to confirm that when we can receive the dataset from you. We need a dataset to initiate a work as soon as possible. If possble, can you double check please? 

Sincerely,
Seong-kyeong from TVCC

**Comment by steven004** [comment]
Let me try to allocate the 5TiB datacap. We should start this and the start number is small.

**Comment by steven004** [comment]
### Request Approved

> Your Datacap Allocation Request has been approved by the Notary

**Message sent to Filecoin Network**

> bafy2bzacec7karynx6hq4ubwuqa3pcqrd6ixzoqd22ama3hi7ptvavpkvvyfo

**Address**

> f3tbfu6dptaui5uwdt7tlhzmovocz47z2fv34dewwhvkf6heel63zqv6ro7we5fvfzndmofel64dggk5vdr5rq

**Datacap Allocated**

> 5TiB


**Signer Address**

> f1qoxqy3npwcvoqy7gpstm65lejcy7pkd3hqqekna


**You can check the status of the message here:** 
https://filscan.io/tipset/message-detail?cid=bafy2bzacec7karynx6hq4ubwuqa3pcqrd6ixzoqd22ama3hi7ptvavpkvvyfo

**Comment by seong-k** [comment]
Dear @galen-mcandrew ,

We've checked the Filcoin address whether it has an error as large-datacap-requests says like above. But it has no error and it is working as well. To solve this problem, do we need a new address to recieve large datacap? Please let us know. Otherwise, please let us know how to troubleshoot this issue.  We really appreciate your effort.

Sincerely,
TVCC

**Comment by seong-k** [comment]
Hi,

We've changed the On-chain address for first allocation by creating a new address. Hope it works. Please let us know if it still has an error to receive a Datacap. Thank you.

Regards,
TVCC

**Comment by seong-k** [comment]
Dear @steven004 

Hope everything is going well this year. We have requested a large datacap with the addresss:  f3tbfu6dptaui5uwdt7tlhzmovocz47z2fv34dewwhvkf6heel63zqv6ro7we5fvfzndmofel64dggk5vdr5rq, but we haven't received any Datacap yet. After all, we also tried creating a new address: f3vxcgzyidrdcmu4n5wod6z47hnx2cingczlzfuxhrj64ih75mg4i7faxeqomn3grablavdamihxlo4icywqva, but we haven't received yet. 

We already checked both addresses are working well now, but we cannnot find which causes this issue. We really need a Datacap to initiate our work as soon as possible. Please let us know what kind of steps we should follwo from now on. We realy appreciate your effort. 

Sincerely,
TVCC

**Comment by steven004** [comment]
@seong-k I had proposed 5TiB grant for you using this address `f3tbfu6dptaui5uwdt7tlhzmovocz47z2fv34dewwhvkf6heel63zqv6ro7we5fvfzndmofel64dggk5vdr5rq`, but it needs another notary to approve to take effect.

**Comment by Reiers** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceapquwnq6w4e4o4stny7ahwy3gphy3vm74q26q4y4z6li7etza7ig 
#### Address 
> f3tbfu6dptaui5uwdt7tlhzmovocz47z2fv34dewwhvkf6heel63zqv6ro7we5fvfzndmofel64dggk5vdr5rq
#### Datacap Allocated
> 5TiB
#### Signer Address
> f1oz43ckvmtxmmsfzqm6bpnemqlavz4ifyl524chq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceapquwnq6w4e4o4stny7ahwy3gphy3vm74q26q4y4z6li7etza7ig

**Comment by seong-k** [comment]
Hi. 
We used up all the previously allocated 5TiB Datacap. So, we would like to request an additional datacap. Good day to you, Thank you.

Regards,
TVCC

**Comment by steven004** [comment]
Hey @seong-k , there is a process to apply large dataset, please refer to https://github.com/filecoin-project/filecoin-plus-large-datasets to get details. please notice: 
> 2 notaries need to approve the next tranche of DataCap to be allocated to the client. The same notary cannot sign off on immediately subsequent allocations of DataCap, i.e., you need at minimum 4 notaries to support your application on an ongoing basis to receive multiple tranches of DataCap.

Please get some other notaries' help on this.

**Comment by seong-k** [comment]
Dear @steven004, Thank you for responding, I have a couple more questions regarding additional notaries. Does the system automatically designate additional notaries, or can we designate them? If we can designate, should we do so through plus.fil.org? I look forward to your response. Thank you.

**Comment by steven004** [comment]
> **Multisig created and sent to RKH f01598031

A multisig is created as your "notary", in which many real notaries are included. Any two of them could prove your request. Actually almost all the notaries are added as the multisig singers. 
Please check https://filscan.io/address/general?address=f01598031 to get signers' addresses;
and you can go plus.fil.org to know the signers.

**Comment by Reiers** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebjsim4t57re3q44yuzpa5mpvv7t6ho5bair4nvc3leuf6yrkw63y 
#### Address 
> f3tbfu6dptaui5uwdt7tlhzmovocz47z2fv34dewwhvkf6heel63zqv6ro7we5fvfzndmofel64dggk5vdr5rq
#### Datacap Allocated
> 10.00TiB
#### Signer Address
> f1oz43ckvmtxmmsfzqm6bpnemqlavz4ifyl524chq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebjsim4t57re3q44yuzpa5mpvv7t6ho5bair4nvc3leuf6yrkw63y

**Comment by MegTei** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacea7xfffcqenv6hdrk265gsb7vaqdiasbnppfdd4d3urc2qgf5tk6c 
#### Address 
> f3tbfu6dptaui5uwdt7tlhzmovocz47z2fv34dewwhvkf6heel63zqv6ro7we5fvfzndmofel64dggk5vdr5rq
#### Datacap Allocated
> 10.00TiB
#### Signer Address
> f1ystxl2ootvpirpa7ebgwl7vlhwkbx2r4zjxwe5i
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacea7xfffcqenv6hdrk265gsb7vaqdiasbnppfdd4d3urc2qgf5tk6c

**Comment by seong-k** [comment]
@galen-mcandrew, We used 75% of the 10 TiB of the recently allocated data cap. So, we would like to request an additional data cap. Thank you.

**Comment by seong-k** [comment]
@Reiers @MegTei We used 75% of the 10 TiB of the recently allocated data cap. So, we would like to request an additional data cap. Thank you.

**Comment by MegTei** [comment]
HI @seong-k the next round needs to be signed by two other notaries (not the same as the last round)

**Comment by seong-k** [comment]
To @IreneYoung @neogeweb3 @rayshitou @dannyob @TimWilliams00 @ozhtdong @Fenbushi-Filecoin @swatchliu @MRJAVAZHAO @KodaRobotDog @XnMatrixSV  @KodaRobotDog @flyworker @IPFSUnion @bytebase

Hi, please help me to approve next round of Datacap. Thanks!

**Comment by IreneYoung** [comment]
Hi @seong-k,  How many miners  do you currently make deal with?

**Comment by seong-k** [comment]
Hello @Irene Young, Currently, our TVCC deals with a total of 8 minor companies, including △Block data bank △Korea ipfs △FCC △Fil data △Ipfsk+ △Ipfs V △Ipfs W △Red fox. Thank you.

**Comment by IreneYoung** [comment]
OK @seong-k, I'll support it later.

**Comment by IreneYoung** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebn3qxi5nzkzw2z4dmx63e2ylzk2bcz7zgtsblng57jgqavaizxlg 
#### Address 
> f3tbfu6dptaui5uwdt7tlhzmovocz47z2fv34dewwhvkf6heel63zqv6ro7we5fvfzndmofel64dggk5vdr5rq
#### Datacap Allocated
> 20.00TiB
#### Signer Address
> f1d4gmpqz3execjj2wvrxuuhvbms5mzh7t7yqrviq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebn3qxi5nzkzw2z4dmx63e2ylzk2bcz7zgtsblng57jgqavaizxlg

**Comment by seong-k** [comment]
To @rayshitou @dannyob @TimWilliams00 @ozhtdong @Fenbushi-Filecoin @swatchliu @MRJAVAZHAO @KodaRobotDog @XnMatrixSV @KodaRobotDog @flyworker @IPFSUnion @bytebase

Hi, please help me to approve next round of Datacap. Thanks!

**Comment by dannyob** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedonpngckqt6vp6r5fjyjevvexusovv3lupjf3rl466ddnv3dfnj4 
#### Address 
> f3tbfu6dptaui5uwdt7tlhzmovocz47z2fv34dewwhvkf6heel63zqv6ro7we5fvfzndmofel64dggk5vdr5rq
#### Datacap Allocated
> 20.00TiB
#### Signer Address
> f1k6wwevxvp466ybil7y2scqlhtnrz5atjkkyvm4a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedonpngckqt6vp6r5fjyjevvexusovv3lupjf3rl466ddnv3dfnj4

**Comment by dannyob** [comment]
Hey @seong-k I've been asked to take a look at some of the applications still on the v2 multisig. Generally speaking, I don't sign a lot of Asian applications, but given the low size of this request and the importance of moving to the new multisig, I'll move this one along. Thanks for your patience.

**Comment by BigData-Exchange** [comment]
Hi @seong-k, great to see you have gotten approval for DataCap and advancing the mission of preserving humanity’s most important information. If you are looking for storage providers to store these data, please visit [BigData Exchange](bigd.exchange). We have strong demand from SPs, who are actively looking to onboard more data. 

Reply here or email us at info@bigd.exchange if you have any questions.

**Comment by psh0691** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb77stufnc3pp36gxwx2fkfagy34aaywglye6b6ifhunbqmwcny54 
#### Address 
> f3tbfu6dptaui5uwdt7tlhzmovocz47z2fv34dewwhvkf6heel63zqv6ro7we5fvfzndmofel64dggk5vdr5rq
#### Datacap Allocated
> 40.00TiB
#### Signer Address
> f1qdko4jg25vo35qmyvcrw4ak4fmuu3f5rif2kc7i
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb77stufnc3pp36gxwx2fkfagy34aaywglye6b6ifhunbqmwcny54

**Comment by Akke-1** [comment]
Hi, @seong-k  Would you like to share your rootCID with us?

**Comment by 1LISA2** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecaovtgfgt5auwf5vwfamfjsdfg4aypwgg56t7cq4cztmvdasmacu 
#### Address 
> f3tbfu6dptaui5uwdt7tlhzmovocz47z2fv34dewwhvkf6heel63zqv6ro7we5fvfzndmofel64dggk5vdr5rq
#### Datacap Allocated
> 40.00TiB
#### Signer Address
> f1jvvltduw35u6inn5tr4nfualyd42bh3vjtylgci
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecaovtgfgt5auwf5vwfamfjsdfg4aypwgg56t7cq4cztmvdasmacu

**Comment by BigD-Exchange** [comment]
@seong-k Hi! Great to see you have gotten approval for DataCap. If you are looking for storage providers to store these data or have any questions, please visit #bigdata-exchange on Filecoin Slack or reply here. 

We have strong demand from a diverse group of SPs, who are actively looking to onboard more data.

**Comment by Joss-Hua** [comment]
![image](https://user-images.githubusercontent.com/75723122/188829632-6da8cc12-c217-4b37-9c78-e60983f1e2de.png)
Too concentrated. What's the reason?

**Comment by seong-k** [comment]
> ![영상](https://user-images.githubusercontent.com/75723122/188829632-6da8cc12-c217-4b37-9c78-e60983f1e2de.png) 너무 집중. 이유가 뭐야?

There were some errors because we didn't quite understand the guidelines for the datacap. If we receive additional data caps in the future, we will implement them as indicated.

**Comment by NDLABS-OFFICE** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecoko54jmsihh5ouv4rjfa4a6ha4vo7hnbo5zh4sbydaxk65kpfbi 
#### Address 
> f3tbfu6dptaui5uwdt7tlhzmovocz47z2fv34dewwhvkf6heel63zqv6ro7we5fvfzndmofel64dggk5vdr5rq
#### Datacap Allocated
> 80.00TiB
#### Signer Address
> f1yayfsv6whu3rheviucvventj3y6t542xfpb47ei
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecoko54jmsihh5ouv4rjfa4a6ha4vo7hnbo5zh4sbydaxk65kpfbi

**Comment by ipfscn** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacechmabgfwdyti3uyma2xgi23vxotspd7pkxhsdaitre4epgpf7bkc 
#### Address 
> f3tbfu6dptaui5uwdt7tlhzmovocz47z2fv34dewwhvkf6heel63zqv6ro7we5fvfzndmofel64dggk5vdr5rq
#### Datacap Allocated
> 80.00TiB
#### Signer Address
> f1j4n74chme7whbz3yls4a7ixqewb6dijypqg2a3a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacechmabgfwdyti3uyma2xgi23vxotspd7pkxhsdaitre4epgpf7bkc

**Comment by psh0691** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebw3mnjndn27bo2765b5sr5vaktob2mzkitnuddsp2ego6otlqobg 
#### Address 
> f3tbfu6dptaui5uwdt7tlhzmovocz47z2fv34dewwhvkf6heel63zqv6ro7we5fvfzndmofel64dggk5vdr5rq
#### Datacap Allocated
> 80.00TiB
#### Signer Address
> f1qdko4jg25vo35qmyvcrw4ak4fmuu3f5rif2kc7i
#### Id
> 599203fe-f263-47e7-aac0-8349d968e4e2
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebw3mnjndn27bo2765b5sr5vaktob2mzkitnuddsp2ego6otlqobg

**Comment by Joss-Hua** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecbdo5h3iuxjxoghaq5akl5ffypd2txy6fc5apgkiek4bsfb3wrsk 
#### Address 
> f3tbfu6dptaui5uwdt7tlhzmovocz47z2fv34dewwhvkf6heel63zqv6ro7we5fvfzndmofel64dggk5vdr5rq
#### Datacap Allocated
> 80.00TiB
#### Signer Address
> f1tfg54zzscugttejv336vivknmsnzzmyudp3t7wi
#### Id
> 599203fe-f263-47e7-aac0-8349d968e4e2
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecbdo5h3iuxjxoghaq5akl5ffypd2txy6fc5apgkiek4bsfb3wrsk

**Comment by Joss-Hua** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacectdtdpwos7jzu4ead54yp7m4ouzk6p47psl5sw22jr67sc5rzg4c 
#### Address 
> f3tbfu6dptaui5uwdt7tlhzmovocz47z2fv34dewwhvkf6heel63zqv6ro7we5fvfzndmofel64dggk5vdr5rq
#### Datacap Allocated
> 80.00TiB
#### Signer Address
> f1tfg54zzscugttejv336vivknmsnzzmyudp3t7wi
#### Id
> 2abeb20f-6291-491d-a839-1d831ec70e35
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacectdtdpwos7jzu4ead54yp7m4ouzk6p47psl5sw22jr67sc5rzg4c

**Comment by psh0691** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceadmqhgztyoyyad5s223ejby4ppwx5xtkjspidmbkypfili7k7mys 
#### Address 
> f3tbfu6dptaui5uwdt7tlhzmovocz47z2fv34dewwhvkf6heel63zqv6ro7we5fvfzndmofel64dggk5vdr5rq
#### Datacap Allocated
> 80.00TiB
#### Signer Address
> f1qdko4jg25vo35qmyvcrw4ak4fmuu3f5rif2kc7i
#### Id
> d24d1472-b11b-46f8-89f1-5bc687dd30e8
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceadmqhgztyoyyad5s223ejby4ppwx5xtkjspidmbkypfili7k7mys

**Comment by filplus-checker** [comment]
## DataCap and CID Checker Report[^1]
 - Organization: `TVCC`
 - Client: `f3tbfu6dptaui5uwdt7tlhzmovocz47z2fv34dewwhvkf6heel63zqv6ro7we5fvfzndmofel64dggk5vdr5rq`
### Storage Provider Distribution
The below table shows the distribution of storage providers that have stored data for this client.

If this is the first time a provider takes verified deal, it will be marked as `new`.

For most of the datacap application, below restrictions should apply.
 - Storage provider should not exceed 25% of total datacap.
 - Storage provider should not be storing duplicate data for more than 20%.
 - Storage provider should have published its public IP address.
 - All storage providers should be located in different regions.

⚠️ [f01770778](https://filfox.info/en/address/f01770778) has unknown IP location.

⚠️ [f01900525](https://filfox.info/en/address/f01900525) has unknown IP location.

⚠️ [f01924824](https://filfox.info/en/address/f01924824) has unknown IP location.

⚠️ [f01927163](https://filfox.info/en/address/f01927163) has unknown IP location.

⚠️ [f01924891](https://filfox.info/en/address/f01924891) has unknown IP location.

⚠️ 47.51% of total deal sealed by [f01126768](https://filfox.info/en/address/f01126768) are duplicate data.

| Provider                                                    |                     Location | Total Deals Sealed | Percentage | Unique Data | Duplicate Deals |
| :---------------------------------------------------------- | ---------------------------: | -----------------: | ---------: | ----------: | --------------: |
| [f01770778](https://filfox.info/en/address/f01770778)`new`  |                      Unknown |          77.53 TiB |     24.89% |   68.69 TiB |          11.41% |
| [f01900525](https://filfox.info/en/address/f01900525)`new`  |                      Unknown |          61.78 TiB |     19.83% |   61.38 TiB |           0.66% |
| [f01115949](https://filfox.info/en/address/f01115949)       |             Seoul, Seoul, KR |          52.91 TiB |     16.98% |   52.28 TiB |           1.18% |
| [f01924824](https://filfox.info/en/address/f01924824)       |                      Unknown |          51.81 TiB |     16.63% |   51.81 TiB |           0.00% |
| [f01927163](https://filfox.info/en/address/f01927163)       |                      Unknown |          34.06 TiB |     10.93% |   34.06 TiB |           0.00% |
| [f01924891](https://filfox.info/en/address/f01924891)       |                      Unknown |          26.38 TiB |      8.47% |   26.38 TiB |           0.00% |
| [f01063173](https://filfox.info/en/address/f01063173)       | Gyeonggi-do, Gyeonggi-do, KR |         977.31 GiB |      0.31% |  921.31 GiB |           5.73% |
| [f01186444](https://filfox.info/en/address/f01186444)       | Gyeonggi-do, Gyeonggi-do, KR |         904.00 GiB |      0.28% |  894.00 GiB |           1.11% |
| [f089840](https://filfox.info/en/address/f089840)           | Gyeonggi-do, Gyeonggi-do, KR |         889.94 GiB |      0.28% |  889.69 GiB |           0.03% |
| [f0842485](https://filfox.info/en/address/f0842485)         | Gyeonggi-do, Gyeonggi-do, KR |         817.06 GiB |      0.26% |  817.06 GiB |           0.00% |
| [f0533124](https://filfox.info/en/address/f0533124)         | Gyeonggi-do, Gyeonggi-do, KR |         769.06 GiB |      0.24% |  769.06 GiB |           0.00% |
| [f0726405](https://filfox.info/en/address/f0726405)         | Gyeonggi-do, Gyeonggi-do, KR |         721.06 GiB |      0.23% |  721.06 GiB |           0.00% |
| [f0102313](https://filfox.info/en/address/f0102313)`new`    | Gyeonggi-do, Gyeonggi-do, KR |         644.06 GiB |      0.20% |  640.06 GiB |           0.62% |
| [f01126768](https://filfox.info/en/address/f01126768)       | Gyeonggi-do, Gyeonggi-do, KR |         572.50 GiB |      0.18% |  300.50 GiB |          47.51% |
| [f0149444](https://filfox.info/en/address/f0149444)         | Gyeonggi-do, Gyeonggi-do, KR |         497.00 GiB |      0.16% |  481.00 GiB |           3.22% |
| [f0399083](https://filfox.info/en/address/f0399083)         | Gyeonggi-do, Gyeonggi-do, KR |         176.00 GiB |      0.06% |  176.00 GiB |           0.00% |
| [f0215497](https://filfox.info/en/address/f0215497)         | Gyeonggi-do, Gyeonggi-do, KR |         136.00 GiB |      0.04% |  136.00 GiB |           0.00% |
| [f0142606](https://filfox.info/en/address/f0142606)`new`    | Gyeonggi-do, Gyeonggi-do, KR |         128.00 GiB |      0.04% |  128.00 GiB |           0.00% |

![Provider Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/117/1671092537160.png)
### Deal Data Replication
The below table shows how each many unique data are replicated across storage providers.
- No more than 25% of unique data are stored with less than 4 providers.

⚠️ 98.48% of deals are for data replicated across less than 4 storage providers.

| Unique Data Size | Total Deals Made | Number of Providers | Deal Percentage |
| ---------------: | ---------------: | ------------------: | --------------: |
|       295.87 TiB |       305.91 TiB |                   1 |          98.20% |
|       364.00 GiB |       920.00 GiB |                   2 |           0.29% |
|         1.00 GiB |         4.00 GiB |                   4 |           0.00% |
|        64.00 MiB |       320.00 MiB |                   5 |           0.00% |
|       128.00 GiB |       768.00 GiB |                   6 |           0.24% |
|       544.00 GiB |         3.72 TiB |                   7 |           1.19% |
|        32.00 GiB |       256.00 GiB |                   8 |           0.08% |

![Replication Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/117/1671092537798.png)
### Deal Data Shared with other Clients
The below table shows how many unique data are shared with other clients.
Usually different applications owns different data and should not resolve to the same CID.

⚠️ CID sharing has been observed.

| Other Client                                                                                                                                                                                                              | Application                                                                                              | Total Deals Affected | Unique CIDs |          Verifier |
| :------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ | :------------------------------------------------------------------------------------------------------- | -------------------: | ----------: | ----------------: |
| [f3ratr7cmhlzjodcrwa2rqb56rtvg4dkqsc2naaeo<br/>aghlqc45zoyj6gdht6653vcdnvq6omw3fgrajuq45<br/>grfa](https://filfox.info/en/address/f3ratr7cmhlzjodcrwa2rqb56rtvg4dkqsc2naaeoaghlqc45zoyj6gdht6653vcdnvq6omw3fgrajuq45grfa) | [MoneyMaker FX EA](https://github.com/filecoin-project/filecoin-plus-client-onboarding/issues/2502)      |           992.00 GiB |           6 |           Unknown |
| [f3wulqe6ljt2ymj7ih6ydllgemx5vknfevg3s4ggb<br/>ssnysi7lebsbzf3mxsrt2vsx7rxky665ncz7me5cj<br/>j7ha](https://filfox.info/en/address/f3wulqe6ljt2ymj7ih6ydllgemx5vknfevg3s4ggbssnysi7lebsbzf3mxsrt2vsx7rxky665ncz7me5cjj7ha) | [Joyful Future](https://github.com/filecoin-project/filecoin-plus-client-onboarding/issues/1233)         |           640.00 GiB |          19 |  Masaaki Nawatani |
| [f3uzdoz4kvubl3oabbtzufqaeirsqo2wbjqjerlxm<br/>3urdo4p5t3sdey756e4576veigxdg2kd7imre63yt<br/>iqbq](https://filfox.info/en/address/f3uzdoz4kvubl3oabbtzufqaeirsqo2wbjqjerlxm3urdo4p5t3sdey756e4576veigxdg2kd7imre63ytiqbq) | [Future Asset Financial](https://github.com/filecoin-project/filecoin-plus-client-onboarding/issues/705) |           360.00 GiB |          16 |             stone |
| [f3s27xfwb6pdne5qgfkdbf7ekuvpnfeo3iq2kuu6a<br/>2nixxxitsnlkmotrxtj2jtegewx6kvugo2lj4dy3p<br/>esrq](https://filfox.info/en/address/f3s27xfwb6pdne5qgfkdbf7ekuvpnfeo3iq2kuu6a2nixxxitsnlkmotrxtj2jtegewx6kvugo2lj4dy3pesrq) | `JKC Global`                                                                                             |            48.00 GiB |           2 |        Performive |
| [f3qis6dmgb3y73xycgrlkzm2iimjivyxovfizthjd<br/>t72kkvzuhfjzrj5yuaoo7d2tsczospmnotdaf35tz<br/>34uq](https://filfox.info/en/address/f3qis6dmgb3y73xycgrlkzm2iimjivyxovfizthjdt72kkvzuhfjzrj5yuaoo7d2tsczospmnotdaf35tz34uq) | `Glif auto verified`                                                                                     |            32.00 GiB |           1 | Jonathan Schwartz |
| [f3simkqmjbjnbpifr3pbtdmcfjz35sisrehkq3gcm<br/>wn7ghtussajcw6wiypzzprxdvt5pj6y2dzrxjpvn6<br/>tz2q](https://filfox.info/en/address/f3simkqmjbjnbpifr3pbtdmcfjz35sisrehkq3gcmwn7ghtussajcw6wiypzzprxdvt5pj6y2dzrxjpvn6tz2q) | [Blockchain World\(BCW\)](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/166)   |            32.00 GiB |           1 |   LDN v3 multisig |
| [f3vsofilk653op74w67zxtn4ed7dygpdyki2x5til<br/>nclmf76troni7zsag3msfv4y64qwijpkca5inx736<br/>vq4q](https://filfox.info/en/address/f3vsofilk653op74w67zxtn4ed7dygpdyki2x5tilnclmf76troni7zsag3msfv4y64qwijpkca5inx736vq4q) | [Ilshinchemical](https://github.com/filecoin-project/filecoin-plus-client-onboarding/issues/816)         |            18.00 GiB |           7 |        Steve Song |
| [f3rpablljxoko6djyzbkmtqukfa6dnrzjuzflokeu<br/>ou4x42nyrfa64e5f4isjm4yfv4mb5v6jtfqgx7hch<br/>kh4a](https://filfox.info/en/address/f3rpablljxoko6djyzbkmtqukfa6dnrzjuzflokeuou4x42nyrfa64e5f4isjm4yfv4mb5v6jtfqgx7hchkh4a) | [UJOONET](https://github.com/filecoin-project/filecoin-plus-client-onboarding/issues/868)                |            16.25 GiB |           2 |      Dr. Ann Shin |
| [f3xhkfkpiic35xrnzsyklgthys3po3c2dfidveg2s<br/>yg3kqv3lmoqmo6dadlnmoxwupyal3s6maswnhtrvg<br/>geha](https://filfox.info/en/address/f3xhkfkpiic35xrnzsyklgthys3po3c2dfidveg2syg3kqv3lmoqmo6dadlnmoxwupyal3s6maswnhtrvggeha) | [channeul](https://github.com/filecoin-project/filecoin-plus-client-onboarding/issues/655)               |            16.00 GiB |           2 |     Danny O'Brien |

[^1]: To manually trigger this report, add a comment with text `checker:manualTrigger`

**Comment by cryptowhizzard** [comment]
Hello,

There is CID sharing present in this application. As applicant you agreed to store "As an example, news videos, K-pop performance videos, and other cultural videos are stored onto Filecoin."
However i see that you share data from MoneyMake , Blockchain world and some others. 

Before we can continue with this application it is vital that we can verify what you are storing. This can be done by retrieval.
I would like to receive a list with the CID's you prepared for this dataset so we can verify the content of this data and start retrieval tests.
