### ISSUE TITLE
[DataCap Allocation] - Solisline Inc. (JAPAN)

### ISSUE THREAD

**Issue by solisline** [filecoin-project/filecoin-plus-large-datasets#1170]
---
name: Large Dataset Notary application
about: Clients should use this application form to request a DataCap allocation via a LDN for a dataset
title: "Solisline Inc. (JAPAN)"
labels: 'application, Phase: Diligence'
assignees: ''

---
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Solisline Inc.
- Website / Social Media: https://solisline.com/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 1PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100TiB
- On-chain address for first allocation: f1j6qzfozemakt2q7h5wonbvnxoidaf2nl4ne32iq
- Region: Asia (excl. Greater China)

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
2015
Started import sales and OEM manufacturing of LED lighting
2016
Telecommunications construction and SI business entry
2017
LED lighting IoT system development
2018
Started manufacture and sale of low-cost, high-quality server racks and optical fibers.
2019
Started data center service and sales
Acquisition of construction business license
2020
Rosetta agency started
Started IdeaHub agency
2021
Built Japan's first large-scale IPFS/Filecoin mining system
Developed SL-ST series face authentication base and face authentication terminal/electronic lock interlocking control box, and started sales
```

What is the primary source of funding for this project?
```
The company set up special fund for this project. 
```

What other projects/ecosystem stakeholders is this project associated with?
```
None.
```

## Use-case details

Describe the data being stored onto Filecoin
```
Business related data, such as pictures, videos, files, etc.

For LED lighting, this is the illuminance simulation data we have created for our clients.
For face recognition systems, we plan to store evaluation and simulation data.
```

Where was the data in this dataset sourced from?
```
This dataset is derived from the work of the company in conducting its business. The collection of material information is self-owned.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
Please download files on 
https://drive.google.com/file/d/18H7q72oddOPyCV_AiczV6Ngtjd-Hph02/view?usp=share_link
https://drive.google.com/file/d/15oKyC7vbUfA-Ai6M9bS9LSk32xJhUGpB/view?usp=share_link
https://drive.google.com/file/d/1acV-WBhKj8gQa1PqjXsITyvw54JOKeLW/view?usp=share_link
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes，it is.
```

What is the expected retrieval frequency for this data?
```
Approximately once per month.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
We plan to store the data for one year. If there is any update, we will store the updated data.  
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
JAPAN

f01848169
f01662849
f01184717

```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Considering upload speed, we will prioritize offline transfer process.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
The storage providers should have certain storage capability and they can provide convenient data upload service.
```

How will you be distributing deals across storage providers?
```
Average distribution.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
I have all I need to start making deals.
```

**Comment by frank-ang** [comment]
Hi @solisline! We have been in contact separately. Some feedback from me:

> Use-Case details
> Describe the data being stored onto Filecoin
>> Business related data, such as pictures, videos, files, etc.

Please be more specific. What is the business purpose of this data set? Which, or all, of the 7 SolisLine business units does this data set come from? Please expand on the use-case description. E.g. cold backup/archival, data pipeline, data producers, data consumers, what is the current storage solution, what is the current pain that Filecoin is a solution to?

> Can you share a sample of the data? 

Sample data file is too large, 447MB, my download failed. Please provide multiple links to small sized unzipped raw sampl files, < 1MB size each will be easier for a browser to render.

> What is the expected retrieval frequency for this data?
>> Multiple times per year.

Please be more specific. E.g. estimated max/min count of full or partial retrieval per week/month/year? 

> DataCap allocation plan
> In which geographies (countries, regions) do you plan on making storage deals?

Multiple countries will be better, unless you can provide very specific reasons why Japan-only. Can you share the identities of the SPs that operate the 3 miner IDs provided?

> How will you be distributing deals across storage providers?
>> We consider storing different businesses on different nodes, but we also consider backing up data. 

The point of this question is to ensure clients distribute and decentralize the storage in an even way across multiple SPs, to avoid SP concentration risk / minerID concentration risk. 
What is the policy of e.g. what is the target maximum % of storage deals to each SP? The distribution shoiuld be fairly even, e.g. if 4 SPs, each receives 25%.
Think about estimating: count of replicas, count of unique SPs providing storage, count of miner IDs by each storage provider. Typically each SP stores 1 full replica each, though you can decide a sharding strategy.

**Comment by solisline** [comment]
> Hi @solisline! We have been in contact separately. Some feedback from me:
> 
> > Use-Case details
> > Describe the data being stored onto Filecoin
> > > Business related data, such as pictures, videos, files, etc.
> 
> Please be more specific. What is the business purpose of this data set? Which, or all, of the 7 SolisLine business units does this data set come from? Please expand on the use-case description. E.g. cold backup/archival, data pipeline, data producers, data consumers, what is the current storage solution, what is the current pain that Filecoin is a solution to?
> 
> > Can you share a sample of the data?
> 
> Sample data file is too large, 447MB, my download failed. Please provide multiple links to small sized unzipped raw sampl files, < 1MB size each will be easier for a browser to render.
> 
> > What is the expected retrieval frequency for this data?
> > > Multiple times per year.
> 
> Please be more specific. E.g. estimated max/min count of full or partial retrieval per week/month/year?
> 
> > DataCap allocation plan
> > In which geographies (countries, regions) do you plan on making storage deals?
> 
> Multiple countries will be better, unless you can provide very specific reasons why Japan-only. Can you share the identities of the SPs that operate the 3 miner IDs provided?
> 
> > How will you be distributing deals across storage providers?
> > > We consider storing different businesses on different nodes, but we also consider backing up data.
> 
> The point of this question is to ensure clients distribute and decentralize the storage in an even way across multiple SPs, to avoid SP concentration risk / minerID concentration risk. What is the policy of e.g. what is the target maximum % of storage deals to each SP? The distribution shoiuld be fairly even, e.g. if 4 SPs, each receives 25%. Think about estimating: count of replicas, count of unique SPs providing storage, count of miner IDs by each storage provider. Typically each SP stores 1 full replica each, though you can decide a sharding strategy.

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 1PiB

**Expected weekly DataCap usage rate**

> 100TiB

**Client address**

> f1j6qzfozemakt2q7h5wonbvnxoidaf2nl4ne32iq

**Comment by GaryGJG** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecfu2q57qpwttcrtl2heczagpusfandkcbufexhstfs6wbjeyzlwy 
#### Address 
> f1j6qzfozemakt2q7h5wonbvnxoidaf2nl4ne32iq
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1zffqhxwq2rrg7rtot6lmkl6hb2xyrrseawprzsq
#### Id
> f8b69009-73ca-42ed-9148-17cdfd6d746e
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecfu2q57qpwttcrtl2heczagpusfandkcbufexhstfs6wbjeyzlwy

**Comment by cryptowhizzard** [comment]
checker:manualTrigger

**Comment by cryptowhizzard** [comment]
Hi @solisline 

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Can you please fill out [this form](https://form.jotform.com/230337462961356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!

**Comment by Sunnyiscoming** [comment]
Is there any problem with using datacap?
