### ISSUE TITLE
[DataCap Application] Shanghai Yancheng Internet Technology Co., Ltd - LinkFocus

### ISSUE THREAD

**Issue by millymoonyu** [filecoin-project/filecoin-plus-large-datasets#1171]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: LinkFocus
- Website / Social Media: https://linknews.cc
  - Tiktok: https://www.douyin.com/user/MS4wLjABAAAAvylqev3-VDwvecISZGe50K1ql6ZjJ1PPTh_8EN7laB8
  - Kuaishou: https://www.kuaishou.com/profile/3xbuh5dhgtv4exw
  - Weibo: https://weibo.com/7499966481
  - Twitter: https://twitter.com/lianketianxia88
  - Youtube: https://www.youtube.com/channel/UC_w-WGa7RlCbq1RUhEYhrMw
  - Wechat Official Account: Lucky-Focus
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 200TiB
- On-chain address for first allocation: f1mkrnjftesv72s2g4qehg2bjzr5nfl5pwxfbqc6y

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Shanghai Yancheng Internet Technology Co., Ltd. is a comprehensive technology company dedicated to building a new generation of Internet infrastructure through big data, artificial intelligence, blockchain and other technologies to help the development of new infrastructure; at the same time, it provides users with distributed storage solutions, Distributed computing solutions, web3.0 application development and blockchain technology services; Its brand "LinkFocus" is committed to popularizing the blockchain in the world, spreading true and comprehensive blockchain information for blockchain enthusiasts.

LinkFocus makes in-depth analysis of major events that have an impact on blockchain technology and crypto assets, and reveals the ins and outs of crypto events. With authoritative reports, data mining and analysis reports with a truly international perspective, it has become a must-read for blockchain-related senior managers. Science and technology information website to create an industry-leading blockchain information service platform.
```

What is the primary source of funding for this project?
```
Own funds and revenue of the company.
```

What other projects/ecosystem stakeholders is this project associated with?
```
None
```

## Use-case details

Describe the data being stored onto Filecoin
```
The data stored on Filecoin including articles, images, videos and raw data of videos rendering.
```

Where was the data in this dataset sourced from?
```
Our own curated and recorded videos.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://drive.google.com/drive/folders/1LFpCVy-gy76Z-KahPpM3LAVWWwCmSQKo?usp=sharing
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes
```

What is the expected retrieval frequency for this data?
```
About 5 times every 540 days.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
Store for at least 540 days.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Asia and North America.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
We will send CAR files to storage providers offline for deal making.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We will check their overall capacity and working hours, we need a storage provider that we can work with for a long time.
```

How will you be distributing deals across storage providers?
```
We will allocate DataCap according to miner's preference, such as online transfer and offline transfer.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes，we have enough funding and resources to start making deals.
```

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 200TiB

**Client address**

> f1mkrnjftesv72s2g4qehg2bjzr5nfl5pwxfbqc6y

**Comment by millymoonyu** [comment]
@cryptowhizzard I have filled out the form.

**Comment by cryptowhizzard** [comment]
Thanks !

f01195421 does not have it's IP adres set on chain and therefore is not qualified for Fil+
f01882035 is involved in abuse with the FIL+ program and therefore is not qualified for Fil+
f0123931 is ok.
f01986353 is ok.

Can you give me to other SP's with standing reputation to replace f01195421 and f01882035 please

**Comment by millymoonyu** [comment]
@cryptowhizzard  Do f02008874 and f02009668 meet the requirements?

**Comment by cryptowhizzard** [comment]
Yes , they are both ok.

Shall we start with f02008874, f02009668, f0123931, f01986353 then?

**Comment by millymoonyu** [comment]
@cryptowhizzard Yes.

**Comment by Sunnyiscoming** [comment]
Hi @millymoonyu 
Maybe you can ask more notaries to do client due diligence and approve the application in slack channel. https://app.slack.com/client/TEHTVS1L6/C036JKD8NVA/thread/C03BG1MNQ4T-1673888660.823499

**Comment by millymoonyu** [comment]
@cryptowhizzard If SPs are in accordance with the rules, can you sign for me?

**Comment by cryptowhizzard** [comment]
Hi @millymoonyu 

yes, i will put 1171 on my list to sign tonight.

**Comment by cryptowhizzard** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebeu7zxw227npn56m5qqwzg4nri3a43nj6b2kybhyylac7nvqeycm 
#### Address 
> f1mkrnjftesv72s2g4qehg2bjzr5nfl5pwxfbqc6y
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1krmypm4uoxxf3g7okrwtrahlmpcph3y7rbqqgfa
#### Id
> ad99a027-08bf-4437-bb0c-c60d3cab8b36
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebeu7zxw227npn56m5qqwzg4nri3a43nj6b2kybhyylac7nvqeycm

**Comment by millymoonyu** [comment]
Thanks a lot!

**Comment by millymoonyu** [comment]
@newwebgroup

**Comment by millymoonyu** [comment]
@s0nik42 @NDLABS-OFFICE @lvschouwen 
Hello, are you notary public I can rely on? Could you sign for me, please?

**Comment by millymoonyu** [comment]
@s0nik42 @NDLABS-OFFICE @lvschouwen
Hello, are you notaries that I can rely on? Could you sign for me, please?

**Comment by mjroddy** [comment]
Hi there.

Can you explain why you require 5 PiB it seems like a lot consider the application.

Secondly and more importantly. I'm not sure this is suited towards Filecoin+ potentially regular deals would be better suited.

“Filecoin Plus is a program that aims to maximize amount of useful storage that Filecoin can and will support.

The ultimate goal of Filecoin Plus is to accelerate the timeframe over which storage goods and services on Filecoin become more useful and attractive. The program plays an essential role in shaping the product offering on the network in collaboration with storage miners.”

From the sample data I do not see how this data would make Filecoin more attractive or useful.

**Comment by millymoonyu** [comment]
@mjroddy Hi,
I agree with some of your points. The ultimate goal of Filecoin is great.
However, the value of data is difficult to measure and varies from person to person. The videos and files we're going to store are a promotion of blockchain knowledge, as well as an introduction to FIlecoin. I think that's valuable content.
Second, each goal is not achieved with a single touch. I think Filecoin plus should probably embrace diversity of data. Only after a higher consensus can we move closer to the ultimate goal. So, I think we're also contributing to the Filecoin network by storing what we think is valuable data on the FIlecoin network. Do you agree?

**Comment by NDLABS-OFFICE** [comment]
@millymoonyu Sorry, we are still suspending signing status as of today

**Comment by millymoonyu** [comment]
@NDLABS-OFFICE Thank you for your review and support, and look forward to the follow-up work

**Comment by NDLABS-OFFICE** [comment]
@millymoonyu If the storage of data conforms to the rules of fil+, we are willing to support.

**Comment by millymoonyu** [comment]
@NDLABS-OFFICE Yes, we will abide by FIL+ rules, please supervise.

**Comment by millymoonyu** [comment]
I hope you can help me to the next milestone. I will prove it with my actions.

**Comment by NDLABS-OFFICE** [comment]
Hello @millymoonyu , according to the application criteria of ND, it is currently the first round and we cannot check the check bot. Judging from the preparation of the nodes, you are ready for data storage, and ND is willing to support you in the first round so that you can proceed to the next round. In addition, I hope you can provide me with some data samples that will be stored, so that I can do a retrieval review in the next round.

**Comment by millymoonyu** [comment]
OK!
Link：https://drive.google.com/drive/folders/1LFpCVy-gy76Z-KahPpM3LAVWWwCmSQKo?usp=sharing

**Comment by NDLABS-OFFICE** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceahtp5fm5wurucqmyvlymdis6h7qw3g2pl6zsgqrqf67srza5uuii 
#### Address 
> f1mkrnjftesv72s2g4qehg2bjzr5nfl5pwxfbqc6y
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1yayfsv6whu3rheviucvventj3y6t542xfpb47ei
#### Id
> ad99a027-08bf-4437-bb0c-c60d3cab8b36
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceahtp5fm5wurucqmyvlymdis6h7qw3g2pl6zsgqrqf67srza5uuii

**Comment by mjroddy** [comment]
> @mjroddy Hi, I agree with some of your points. The ultimate goal of Filecoin is great. However, the value of data is difficult to measure and varies from person to person. The videos and files we're going to store are a promotion of blockchain knowledge, as well as an introduction to FIlecoin. I think that's valuable content. Second, each goal is not achieved with a single touch. I think Filecoin plus should probably embrace diversity of data. Only after a higher consensus can we move closer to the ultimate goal. So, I think we're also contributing to the Filecoin network by storing what we think is valuable data on the FIlecoin network. Do you agree?

I think that it's pretty easy to argue that any piece of data is valuable. That's not the point here. It is whether it is valuable to the Filecoin ecosystem/the filecoin plus program.

I strongly recommend that this application go through normal deals. The request of 5 PiB is too large for the use case in my opinion and this dataset will not help accelerate the usefulness of Filecoin, making it more attractive for others.

@NDLABS-OFFICE please reconsider or provide a more detailed justification for this dataset.

@raghavrmadya & @dkkapur  tagging as an FYI

**Comment by millymoonyu** [comment]
> > @mjroddy Hi, I agree with some of your points. The ultimate goal of Filecoin is great. However, the value of data is difficult to measure and varies from person to person. The videos and files we're going to store are a promotion of blockchain knowledge, as well as an introduction to FIlecoin. I think that's valuable content. Second, each goal is not achieved with a single touch. I think Filecoin plus should probably embrace diversity of data. Only after a higher consensus can we move closer to the ultimate goal. So, I think we're also contributing to the Filecoin network by storing what we think is valuable data on the FIlecoin network. Do you agree?
> 
> I think that it's pretty easy to argue that any piece of data is valuable. That's not the point here. It is whether it is valuable to the Filecoin ecosystem/the filecoin plus program.
> 
> I strongly recommend that this application go through normal deals. The request of 5 PiB is too large for the use case in my opinion and this dataset will not help accelerate the usefulness of Filecoin, making it more attractive for others.
> 
> @NDLABS-OFFICE please reconsider or provide a more detailed justification for this dataset.
> 
> @raghavrmadya & @dkkapur tagging as an FYI

I'm a bit confused if you're emphasizing the value of data for Filecoin Plus. How do you define it? Does that mean you suggest and encourage everyone to be a porter of public cloud data? If everyone does that, then who will store their valuable data on Filecoin? Who will add diversity to the data on the Filecoin network? How can we increase Filecoin's influence?

Secondly, for our plan to store 10 data backups, a request for 5 Pibs is not significant, only 500 Tib, and we still need to consider data growth.

**Comment by millymoonyu** [comment]
I'm a bit confused if you're emphasizing the value of data for Filecoin Plus. How do you define it? Does that mean you suggest and encourage everyone to be a porter of public cloud data? If everyone does that, then who will store their valuable data on Filecoin? Who will add diversity to the data on the Filecoin network? How can we increase Filecoin's influence?

Secondly, for our plan to store 10 data backups, a request for 5 Pibs is not significant, only 500 Tib, and we still need to consider data growth.

**Comment by a1991car** [comment]
checker:manualTrigger

**Comment by a1991car** [comment]
![803df5a31bfe23db16377390019a692](https://user-images.githubusercontent.com/32447611/225863219-b399f7d6-58e9-4408-b90e-266e46150f77.jpg)

**Comment by a1991car** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceap4wonndzzzwwaonld46s2lz2atzgbf4h3liie42p4ochccvlp3m 
#### Address 
> f1mkrnjftesv72s2g4qehg2bjzr5nfl5pwxfbqc6y
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1qnumecdypgrbaebtkdfjnwt5ndacadcuas3deiq
#### Id
> 13e508ce-ed23-43d2-b275-ed8f8894692d
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceap4wonndzzzwwaonld46s2lz2atzgbf4h3liie42p4ochccvlp3m

**Comment by newwebgroup** [comment]
checker:manualTrigger

**Comment by newwebgroup** [comment]
https://filecoin.tools/f02048851
./lotus client retrieve --provider f02028326 bafybeicjcxysthtk2k5r6uqnwxngakinx334cfggxxt5ordzjksobp55xy .car
<img width="1116" alt="image" src="https://user-images.githubusercontent.com/100118145/230587816-dfe48df8-d44c-410f-a680-9a59466e67cd.png">

**Comment by newwebgroup** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacea7dk5qew6hs5ylha4hyui2ay45fomoe7xizqzju5jqpok6aty5wc 
#### Address 
> f1mkrnjftesv72s2g4qehg2bjzr5nfl5pwxfbqc6y
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1e77zuityhvvw6u2t6tb5qlnsegy2s67qs4lbbbq
#### Id
> 3122bc73-b67c-4d70-be68-146b58537079
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacea7dk5qew6hs5ylha4hyui2ay45fomoe7xizqzju5jqpok6aty5wc

**Comment by Tom-OriginStorage** [comment]
![image](https://user-images.githubusercontent.com/103015469/232441345-46a8038a-3186-4157-aecb-d35968b991ef.png)

**Comment by Tom-OriginStorage** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecljm4s675c22xde2gefpswcgs7pobzzsycs6tzo54xhjvapsn3by 
#### Address 
> f1mkrnjftesv72s2g4qehg2bjzr5nfl5pwxfbqc6y
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1q6bpjlqia6iemqbrdaxr2uehrhpvoju3qh4lpga
#### Id
> a893b832-551b-424c-bc18-5c3567045207
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecljm4s675c22xde2gefpswcgs7pobzzsycs6tzo54xhjvapsn3by

**Comment by 1ane-1** [comment]
manualTrigger

**Comment by 1ane-1** [comment]
checker:manualTrigger

**Comment by 1ane-1** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebvac2hna66vnn7ge3xqsthm26tqhcqioeg5evrvbrrjmtevi3wty 
#### Address 
> f1mkrnjftesv72s2g4qehg2bjzr5nfl5pwxfbqc6y
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1mdk7s2vntzm6hu35yuo6vjubtrpfnb2awhgvrri
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebvac2hna66vnn7ge3xqsthm26tqhcqioeg5evrvbrrjmtevi3wty

**Comment by 1ane-1** [comment]
No problem in the CID report.

**Comment by kernelogic** [comment]
CID report looks good, miner reachable
<img width="843" alt="image" src="https://user-images.githubusercontent.com/3711825/236139258-4a52c363-ddc6-47ec-8c6d-b86a537dfb67.png">

**Comment by kernelogic** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecvf5aikajggy4jpcwvmkzi54tjlgbetibs7u75mf3oun3u2xmczk 
#### Address 
> f1mkrnjftesv72s2g4qehg2bjzr5nfl5pwxfbqc6y
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecvf5aikajggy4jpcwvmkzi54tjlgbetibs7u75mf3oun3u2xmczk

**Comment by newwebgroup** [comment]
checker:manualTrigger

**Comment by newwebgroup** [comment]
https://filecoin.tools/f02048851

./lotus client retrieve --provider f02028326 bafybeibzmrjkb6cxb2flbwrzvrd4b2ay6ldy24yn6omzck3vp2aqoxcfqq .car
<img width="1157" alt="image" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/100118145/48f2a911-aabd-490a-ae1e-23c009a0487e">

**Comment by newwebgroup** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecssa7r5zk7flakrwxpxoj2rdt5faqccbnvyvvn2byeto553zifo6 
#### Address 
> f1mkrnjftesv72s2g4qehg2bjzr5nfl5pwxfbqc6y
#### Datacap Allocated
> 1.56PiB
#### Signer Address
> f1e77zuityhvvw6u2t6tb5qlnsegy2s67qs4lbbbq
#### Id
> da216cf5-3407-4088-a725-96d7231200b8
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecssa7r5zk7flakrwxpxoj2rdt5faqccbnvyvvn2byeto553zifo6

**Comment by Chuangshi1** [comment]
Everything goes well，this ground i will support you!

**Comment by Chuangshi1** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedr6nbn343an6rhyyzag2kltoib3jcjoebywkigcubdrfgwbg5vys 
#### Address 
> f1mkrnjftesv72s2g4qehg2bjzr5nfl5pwxfbqc6y
#### Datacap Allocated
> 1.56PiB
#### Signer Address
> f1mdk7s2vntzm6hu35yuo6vjubtrpfnb2awhgvrri
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedr6nbn343an6rhyyzag2kltoib3jcjoebywkigcubdrfgwbg5vys

**Comment by lyjmry** [comment]
checker:manualTrigger

**Comment by 1ane-1** [comment]
checker:manualTrigger

**Comment by 1ane-1** [comment]
CID Checker Report looks good.

**Comment by 1ane-1** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedvmzunbze6w46dv6spq2vtf64naki6wiv36jwc23naftb477tih4 
#### Address 
> f1mkrnjftesv72s2g4qehg2bjzr5nfl5pwxfbqc6y
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1mdk7s2vntzm6hu35yuo6vjubtrpfnb2awhgvrri
#### Id
> 2b18aee6-773a-4980-b16c-d5e7bf284c90
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedvmzunbze6w46dv6spq2vtf64naki6wiv36jwc23naftb477tih4

**Comment by cryptowhizzard** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceads2xst3swhjcusbxglwhejxzzcysx2vxsmout6rpitzymlg6bey 
#### Address 
> f1mkrnjftesv72s2g4qehg2bjzr5nfl5pwxfbqc6y
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1krmypm4uoxxf3g7okrwtrahlmpcph3y7rbqqgfa
#### Id
> 2b18aee6-773a-4980-b16c-d5e7bf284c90
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceads2xst3swhjcusbxglwhejxzzcysx2vxsmout6rpitzymlg6bey

**Comment by cryptowhizzard** [comment]
KYC was completed in early stages by this client. Retrieval is OK as wel as decentralized replication of the dataset's.

For next round i would try to evaluate and download some data.

**Comment by maxvint** [comment]
checker:manualTrigger

**Comment by Filplus-govteam** [comment]
Hello @millymoonyu per the https://github.com/filecoin-project/notary-governance/issues/922 for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

This information will be reviewed by Fil+ Governance team to confirm validity and then the application will be triggered for notary review. Let us know if you have any questions.

**Comment by millymoonyu** [comment]
I am watching this

**Comment by cryptowhizzard** [comment]
Hello,

Dispite that the graphsync retrieval looks good i get numerous errors when downloading.
Are your SP's working with custom software or with regular boost and if so, what version?

Recv 2.481 GiB, Paid 0 FIL, BlocksReceived (Ongoing), 3h16m36.842s [1690024162200370735|2664368638]
Recv 2.482 GiB, Paid 0 FIL, BlocksReceived (Ongoing), 3h16m41.575s [1690024162200370735|2665417214]
Recv 2.483 GiB, Paid 0 FIL, BlocksReceived (Ongoing), 3h16m46.164s [1690024162200370735|2666465790]
Recv 2.484 GiB, Paid 0 FIL, BlocksReceived (Ongoing), 3h16m50.802s [1690024162200370735|2667514366]
Recv 2.485 GiB, Paid 0 FIL, BlocksReceived (Ongoing), 3h16m55.433s [1690024162200370735|2668562942]
Recv 2.486 GiB, Paid 0 FIL, BlocksReceived (Ongoing), 3h17m0.046s [1690024162200370735|2669611518]
Recv 2.487 GiB, Paid 0 FIL, BlocksReceived (Ongoing), 3h17m4.791s [1690024162200370735|2670660094]
Recv 2.488 GiB, Paid 0 FIL, BlocksReceived (Ongoing), 3h17m9.379s [1690024162200370735|2671708670]
Recv 2.489 GiB, Paid 0 FIL, BlocksReceived (Ongoing), 3h17m14.129s [1690024162200370735|2672757246]
Recv 2.49 GiB, Paid 0 FIL, BlocksReceived (Ongoing), 3h17m18.726s [1690024162200370735|2673805822]
Recv 2.491 GiB, Paid 0 FIL, BlocksReceived (Ongoing), 3h17m23.534s [1690024162200370735|2674854398]
Recv 2.492 GiB, Paid 0 FIL, BlocksReceived (Ongoing), 3h17m28.039s [1690024162200370735|2675902974]
Recv 2.493 GiB, Paid 0 FIL, BlocksReceived (Ongoing), 3h17m32.611s [1690024162200370735|2676951550]
Recv 2.494 GiB, Paid 0 FIL, BlocksReceived (Ongoing), 3h17m37.145s [1690024162200370735|2678000126]
Recv 2.495 GiB, Paid 0 FIL, BlocksReceived (Ongoing), 3h17m41.827s [1690024162200370735|2679048702]
Recv 2.496 GiB, Paid 0 FIL, BlocksReceived (Ongoing), 3h17m46.454s [1690024162200370735|2680097278]
Recv 2.497 GiB, Paid 0 FIL, BlocksReceived (Ongoing), 3h17m51.068s [1690024162200370735|2681145854]
Recv 2.498 GiB, Paid 0 FIL, BlocksReceived (Ongoing), 3h17m55.644s [1690024162200370735|2682194430]
Recv 2.499 GiB, Paid 0 FIL, BlocksReceived (Ongoing), 3h18m0.346s [1690024162200370735|2683243006]
Recv 2.499 GiB, Paid 0 FIL, DataTransferError (Erroring), 7h20m49.614s [1690024162200370735|2683243006]
Recv 2.499 GiB, Paid 0 FIL, BlockstoreFinalized (Errored), 7h20m49.639s [1690024162200370735|2683243006]
ERROR: Retrieval Error: error generated by data transfer: deal data transfer failed: data transfer channel 12D3KooWAhG3BRy2RhVgMbvBNyq5z61JwFYHcmEXopGm5pw54QdW-12D3KooWD8q5LvrP7ZxiTnAeK4R7r3vq9w1j4ndbGdPJ1DVJRraU-1690024162185103296 failed to transfer data: channel 12D3KooWAhG3BRy2RhVgMbvBNyq5z61JwFYHcmEXopGm5pw54QdW-12D3KooWD8q5LvrP7ZxiTnAeK4R7r3vq9w1j4ndbGdPJ1DVJRraU-1690024162185103296: graphsync request failed to complete: error traversing node at "Links/3/Hash/Links/0/Hash/Links/961/Hash": could not load link "bafkreifnvlo6e7u43rtosqvizxkv3vhahqndwlqgbjgfwhnw3bezg5p7ja": expected link (bafybeibp5pw3nlrwcwavzcu5hmywm5hl7xkgblm75h3zplpzoqn3ydkeh4) at path  does not match link sent by remote (bafkreieagcjp62zoq4ekzpepwq6kb77uar3xbmcnyw4bwpze5prwals2u4), possible malicious responder

**Comment by millymoonyu** [comment]
> Hello,
> 
> Dispite that the graphsync retrieval looks good i get numerous errors when downloading. Are your SP's working with custom software or with regular boost and if so, what version?
> 
> Recv 2.481 GiB, Paid 0 FIL, BlocksReceived (Ongoing), 3h16m36.842s [1690024162200370735|2664368638] Recv 2.482 GiB, Paid 0 FIL, BlocksReceived (Ongoing), 3h16m41.575s [1690024162200370735|2665417214] Recv 2.483 GiB, Paid 0 FIL, BlocksReceived (Ongoing), 3h16m46.164s [1690024162200370735|2666465790] Recv 2.484 GiB, Paid 0 FIL, BlocksReceived (Ongoing), 3h16m50.802s [1690024162200370735|2667514366] Recv 2.485 GiB, Paid 0 FIL, BlocksReceived (Ongoing), 3h16m55.433s [1690024162200370735|2668562942] Recv 2.486 GiB, Paid 0 FIL, BlocksReceived (Ongoing), 3h17m0.046s [1690024162200370735|2669611518] Recv 2.487 GiB, Paid 0 FIL, BlocksReceived (Ongoing), 3h17m4.791s [1690024162200370735|2670660094] Recv 2.488 GiB, Paid 0 FIL, BlocksReceived (Ongoing), 3h17m9.379s [1690024162200370735|2671708670] Recv 2.489 GiB, Paid 0 FIL, BlocksReceived (Ongoing), 3h17m14.129s [1690024162200370735|2672757246] Recv 2.49 GiB, Paid 0 FIL, BlocksReceived (Ongoing), 3h17m18.726s [1690024162200370735|2673805822] Recv 2.491 GiB, Paid 0 FIL, BlocksReceived (Ongoing), 3h17m23.534s [1690024162200370735|2674854398] Recv 2.492 GiB, Paid 0 FIL, BlocksReceived (Ongoing), 3h17m28.039s [1690024162200370735|2675902974] Recv 2.493 GiB, Paid 0 FIL, BlocksReceived (Ongoing), 3h17m32.611s [1690024162200370735|2676951550] Recv 2.494 GiB, Paid 0 FIL, BlocksReceived (Ongoing), 3h17m37.145s [1690024162200370735|2678000126] Recv 2.495 GiB, Paid 0 FIL, BlocksReceived (Ongoing), 3h17m41.827s [1690024162200370735|2679048702] Recv 2.496 GiB, Paid 0 FIL, BlocksReceived (Ongoing), 3h17m46.454s [1690024162200370735|2680097278] Recv 2.497 GiB, Paid 0 FIL, BlocksReceived (Ongoing), 3h17m51.068s [1690024162200370735|2681145854] Recv 2.498 GiB, Paid 0 FIL, BlocksReceived (Ongoing), 3h17m55.644s [1690024162200370735|2682194430] Recv 2.499 GiB, Paid 0 FIL, BlocksReceived (Ongoing), 3h18m0.346s [1690024162200370735|2683243006] Recv 2.499 GiB, Paid 0 FIL, DataTransferError (Erroring), 7h20m49.614s [1690024162200370735|2683243006] Recv 2.499 GiB, Paid 0 FIL, BlockstoreFinalized (Errored), 7h20m49.639s [1690024162200370735|2683243006] ERROR: Retrieval Error: error generated by data transfer: deal data transfer failed: data transfer channel 12D3KooWAhG3BRy2RhVgMbvBNyq5z61JwFYHcmEXopGm5pw54QdW-12D3KooWD8q5LvrP7ZxiTnAeK4R7r3vq9w1j4ndbGdPJ1DVJRraU-1690024162185103296 failed to transfer data: channel 12D3KooWAhG3BRy2RhVgMbvBNyq5z61JwFYHcmEXopGm5pw54QdW-12D3KooWD8q5LvrP7ZxiTnAeK4R7r3vq9w1j4ndbGdPJ1DVJRraU-1690024162185103296: graphsync request failed to complete: error traversing node at "Links/3/Hash/Links/0/Hash/Links/961/Hash": could not load link "bafkreifnvlo6e7u43rtosqvizxkv3vhahqndwlqgbjgfwhnw3bezg5p7ja": expected link (bafybeibp5pw3nlrwcwavzcu5hmywm5hl7xkgblm75h3zplpzoqn3ydkeh4) at path does not match link sent by remote (bafkreieagcjp62zoq4ekzpepwq6kb77uar3xbmcnyw4bwpze5prwals2u4), possible malicious responder

Sorry for that. I got in touch with SP and made sure they turned on retrieval. This may be due to network issues. Please try again in due course

**Comment by millymoonyu** [comment]
I AM
