### ISSUE TITLE
[DataCap Application] - <2amok>

### ISSUE THREAD

**Issue by Vincent242022** [filecoin-project/filecoin-plus-large-datasets#1173]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: 2amok
- Website / Social Media:https://www.2amok.com/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):100TiB
- On-chain address for first allocation:f1px4vu4r5nvtiz6y774b7gjshmgy643jgtztw4wa

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
2amok is an exchange and learning website focusing on video materials, AE material templates, real film and television videos, LED dynamic backgrounds, dynamic visual effects and other video types. The website adheres to the long-term development strategy of "user experience", pays attention to product details and user experience, and strives to build a leading video material service exchange and learning network in China. With the rapid growth of videos storage needs, we are seeking the better way to store our vidoes and materials as long-term development strategy.These years, Web3 is growing more and more popular in China and IPFS really intrest us. 
```

What is the primary source of funding for this project?
```
business income
```

What other projects/ecosystem stakeholders is this project associated with?
```
no
```

## Use-case details

Describe the data being stored onto Filecoin
```
The data we plan to store on filecoin are public video dataset on our website.
```

Where was the data in this dataset sourced from?
```
video materials which are owned by our company.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://www.2amok.com/videoText/324806.html https://www.2amok.com/videoText/285230.html  https://www.2amok.com/videoText/453180.html  https://www.2amok.com/videoText/292816.html https://www.2amok.com/videoText/429289.html https://www.2amok.com/videoText/174277.html  https://www.2amok.com/videoText/52206.html https://www.2amok.com/videoText/53063.html  https://www.2amok.com/videoText/53098.html
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
yes
```

What is the expected retrieval frequency for this data?
```
We have had public commerical service, so it is retrieved frequently. 
```

For how long do you plan to keep this dataset stored on Filecoin?
```
at least 5 years and it can be extended afterwards.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
China
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
offline
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We plan to select the 4-5 SPs with rich experience in China first. 
```

How will you be distributing deals across storage providers?
```
at least 2 copies per client, and then distribute quota and files fairly
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
sure
```

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 100TiB

**Client address**

>f1px4vu4r5nvtiz6y774b7gjshmgy643jgtztw4wa

**Comment by xingjitansuo** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacechmxqr2cpkfrldlu7ysutkgam546jdwbz73s76234p3vitgw4u5w 
#### Address 
> f1px4vu4r5nvtiz6y774b7gjshmgy643jgtztw4wa
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1a2lia2cwwekeubwo4nppt4v4vebxs2frozarz3q
#### Id
> 0747e6a7-d0ea-4cd6-a6c1-d5b5b38034ed
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacechmxqr2cpkfrldlu7ysutkgam546jdwbz73s76234p3vitgw4u5w

**Comment by stcouldlisa** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacearxg26getlbfkrif477xdo2eeg5hdmes5xr5sfuit2wwwgf2i4sa 
#### Address 
> f1px4vu4r5nvtiz6y774b7gjshmgy643jgtztw4wa
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1jvvltduw35u6inn5tr4nfualyd42bh3vjtylgci
#### Id
> 0747e6a7-d0ea-4cd6-a6c1-d5b5b38034ed
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacearxg26getlbfkrif477xdo2eeg5hdmes5xr5sfuit2wwwgf2i4sa

**Comment by stcouldlisa** [comment]
I got a request on your slack so I signed for you, but, you need send email to filplus-app-review@fil.org using your official domain name to confirm your identity?
Email name should contain Issue ID #1173

**Comment by stcouldlisa** [comment]
In addition, you need to provide at least 4 SPs to prove that you will implement decentralized storage

**Comment by Vincent242022** [comment]
Dear Notary

1. I have sent the confirmation email to the official email per your
request.
2. Yes. We are reaching out to more than 5 SPs now and will select at least
4 to make sure the allocation is fair and even.

Thanks



LISA ***@***.***> 于2023年1月3日周二 14:21写道：

**Comment by BDEio** [comment]
@Vincent242022 Hi! Great to see that you have gotten approval for DataCap!
BDE is a verified deals auction house helping you to get paid storing your data with reliable storage providers. If you need any help, please get in touch.

**Comment by NDLABS-OFFICE** [comment]
checker:manualTrigger

**Comment by lvschouwen** [comment]
@Vincent242022 
Can you work with your SPs to make sure their miners are reachable? As you can see f01985611 is not.
Can you also explain to the community why there is CID sharing going on?

**Comment by cryptowhizzard** [comment]
Hello,

There is an outstanding question / issue with CID sharing in #1089

Can you please explain to the community why there is CID sharing going on?

Also please note that none of your content is retrievable. This is against FIL+ rules. Please contact the SP's and get this corrected asap otherwise we cannot grant and new datacap allocations.

**Comment by cryptowhizzard** [comment]
[f02005305.csv.log](https://github.com/filecoin-project/filecoin-plus-large-datasets/files/10421092/f02005305.csv.log)

**Comment by Vincent242022** [comment]
Hey



Thanks for your check on our LDN.

We have reached out to SP and tried to work on this issue of CID sharing
you mentioned.

Currently we got the feedback that they did not totally sort out the data
from different customers when they did data partitioning in the preparation
of data storage. That might be the reason why we had duplicate storage with
other customers.



Appreciate your reminder and we have communicated many times with SP to
restate our position . They promise they have rectified the process of data
preparation/processing to ensure that will not happen again.



Hope the community can continue providing supervision and suggestions, and
for any issue caused by technical part, we will improve and require our SP
to provide CID for all to check in next round.



Besides, f02005305.csv.log is not the node from our SP and we have asked SP
to provide public retrieval for the community to further supervise.



Thanks again for your timely support.



CryptoWhizzard ***@***.***> 于2023年1月16日周一 04:07写道：

**Comment by cryptowhizzard** [comment]
Hello,

Thanks for your comments.

> Currently we got the feedback that they did not totally sort out the data
from different customers when they did data partitioning in the preparation
of data storage. That might be the reason why we had duplicate storage with
other customers.

Can you tell us who you are working with and who is preparing this data for you? Working on LDN / Fil+ requires full transperancy.

It is not about the few GB of data that is duplicate. It is about the fact that the data itself is highly fraudulent.

Let us know when your SP's support full retrieval and please let us know who you are working with to pack your data so we can check and do proper KYC on the company you use for packing.

**Comment by cryptowhizzard** [comment]
Hello 

I tried retrieval again and this seems (sort of) improved. However, all SP's do not provide fast retrieval.
All data in the FIL+ program should be readily retrievable. This is not.

>>

/usr/local/bin/lotus state get-deal 21806312 
/usr/local/bin/lotus client retrieve --provider f01878534 mAXCg5AIgIBzG0Myor6K98tcZDMuSjAPjM5DbULwY+QxsZiO8o48
/usr/local/bin/lotus state get-deal 21806313 
/usr/local/bin/lotus client retrieve --provider f01878534 mAXCg5AIg0UdDb0ReVa8Bt+IepolhPWhpKX1Higq5BH1BSKIDaIE
/usr/local/bin/lotus state get-deal 21818076 
/usr/local/bin/lotus client retrieve --provider f01854080 mAXCg5AIgt9r4Bwwkgd/90CG0MIzoDhg2oJUxbFqx08KEcc47+VU
/usr/local/bin/lotus state get-deal 21818077 
/usr/local/bin/lotus client retrieve --provider f01854080 mAXCg5AIgsrmYl18cdYEYbWW0zkuqCzdvESfpZv1xQMmIaAsO0i0
/usr/local/bin/lotus state get-deal 21820415 
/usr/local/bin/lotus client retrieve --provider f01854080 mAXCg5AIge0ptJfCHIyEqu57RgbZ5+z600H6fzoH2wouMA+SafX8
/usr/local/bin/lotus state get-deal 21820416 
/usr/local/bin/lotus client retrieve --provider f01854080 mAXCg5AIgZOzfahi8RQ8jucRTCbF9k6YFk+G4+jbqG6pxnSLpobo
/usr/local/bin/lotus state get-deal 21834063 
/usr/local/bin/lotus client retrieve --provider f01985611 mAXCg5AIg7cqUy3DJSSXe87ai409ALytNh6G1D9ACc3fRGjzW84E
Recv 0 B, Paid 0 FIL, Open (New), 0s [1673908265200556116|0]
Recv 0 B, Paid 0 FIL, DealProposed (WaitForAcceptance), 12ms [1673908265200556116|0]
/usr/local/bin/lotus state get-deal 21834520 
/usr/local/bin/lotus client retrieve --provider f01985611 mAXCg5AIgJrVQbqNRuq9/LGddUWs8+nUo4cGcMmmSfiUujD+Bb+o
Recv 0 B, Paid 0 FIL, Open (New), 0s [1673908265200556117|0]
Recv 0 B, Paid 0 FIL, DealProposed (WaitForAcceptance), 12ms [1673908265200556117|0]
/usr/local/bin/lotus state get-deal 21884120 
/usr/local/bin/lotus client retrieve --provider f02000936 mAXCg5AIghEbGBE290OGAYcjiLUfIn6ViZ2o+bW2mAlslsPKKESE
Recv 0 B, Paid 0 FIL, Open (New), 0s [1673908265200556118|0]
Recv 0 B, Paid 0 FIL, DealProposed (WaitForAcceptance), 12ms [1673908265200556118|0]
/usr/local/bin/lotus state get-deal 21884824 
/usr/local/bin/lotus client retrieve --provider f02000936 mAXCg5AIgm6Ah2Gnf+CaZ0gKwiKNosDGepwlK0kqzyQTQdGfm9Rw
Recv 0 B, Paid 0 FIL, Open (New), 0s [1673908265200556119|0]
Recv 0 B, Paid 0 FIL, DealProposed (WaitForAcceptance), 12ms [1673908265200556119|0]
/usr/local/bin/lotus state get-deal 21910091 
/usr/local/bin/lotus client retrieve --provider f01854080 mAXCg5AIg6Ibm9ZcfY0tJg8+2sSVt7B8F56VmNv4UwnJMf6FKvEU
/usr/local/bin/lotus state get-deal 21910092 
/usr/local/bin/lotus client retrieve --provider f01854080 mAXCg5AIgxEORLZT7+AVh7QlUbpYuJx7rnwdugDoOp6cZ2ombmWU
/usr/local/bin/lotus state get-deal 21916437 
/usr/local/bin/lotus client retrieve --provider f02000936 mAXCg5AIgJu7id+jhDXrA46o99ZdWYT4kqACBc4f2vWiUnOID84E
Recv 0 B, Paid 0 FIL, Open (New), 0s [1673908265200556120|0]
Recv 0 B, Paid 0 FIL, DealProposed (WaitForAcceptance), 12ms [1673908265200556120|0]
/usr/local/bin/lotus state get-deal 21916461 
/usr/local/bin/lotus client retrieve --provider f01985611 mAXCg5AIgU4TaWlIynTod+FJTGQ2gps90+83Bv8DQbuYJh4ydUFI
Recv 0 B, Paid 0 FIL, Open (New), 0s [1673908265200556121|0]
Recv 0 B, Paid 0 FIL, DealProposed (WaitForAcceptance), 12ms [1673908265200556121|0]
/usr/local/bin/lotus state get-deal 22171587 
/usr/local/bin/lotus client retrieve --provider f01972110 bafykbzacebw6lg7y5fu2egklne65frtvnv6yuvth5sifkg4mrojvsuvlaen7u
/usr/local/bin/lotus state get-deal 22175071 
/usr/local/bin/lotus client retrieve --provider f01972110 bafykbzacec4v6gf7sbjlcm2rszr6mmmxkmgfv2e6bpnnye4gsp5vskcxqpeug
/usr/local/bin/lotus state get-deal 22604604 
/usr/local/bin/lotus client retrieve --provider f01972110 bafykbzaceavhwz3hrob3gl3imb32u77yfmtzjcpaijo3iw4ndhfwjkh5zi64u
/usr/local/bin/lotus state get-deal 22605487 
/usr/local/bin/lotus client retrieve --provider f01972110 bafykbzacedhaz67cmoo7cjffqwkmnoquzph2ccke3nwxbphbzxlubhbme5qa6
Recv 0 B, Paid 0 FIL, Open (New), 0s [1673908265200556122|0]
Recv 0 B, Paid 0 FIL, DealProposed (WaitForAcceptance), 12ms [1673908265200556122|0]
Recv 0 B, Paid 0 FIL, Open (New), 0s [1673908265200556123|0]
Recv 0 B, Paid 0 FIL, DealProposed (WaitForAcceptance), 16ms [1673908265200556123|0]
Recv 0 B, Paid 0 FIL, Open (New), 0s [1673908265200556124|0]
Recv 0 B, Paid 0 FIL, DealProposed (WaitForAcceptance), 12ms [1673908265200556124|0]
Recv 0 B, Paid 0 FIL, Open (New), 0s [1673908265200556125|0]
Recv 0 B, Paid 0 FIL, DealProposed (WaitForAcceptance), 16ms [1673908265200556125|0]

**Comment by cryptowhizzard** [comment]
Btw:

I did a check on the 4 SP's you work with:

f01917354	f01878534	128.1.220.178	1	8573	2679.06TB QAP 

https://github.com/filecoin-project/filecoin-plus-large-datasets/issues?q=is%3Aissue+f1o2nxreefzqzc2mvaqneaolpdat5yk3275r6rofa

All applications with CID Sharing and fake data.


f01936823	f01878534	128.1.220.178	1	1664	520.00TB QAP _ >

https://github.com/filecoin-project/filecoin-plus-large-datasets/issues?q=is%3Aissue+f13wvg4xve7nz3nev4bi2c7imod7lelstxfwwzjgi
 
f01941015	f01878534	128.1.220.178	1	565	176.56TB QAP

https://github.com/filecoin-project/filecoin-plus-large-datasets/issues?q=is%3Aissue+f1fsoyq7oiwdaapagpnlncbohkrkzolxxzkex6hxq+

f02005295	f01878534	128.1.220.178	1	252	78.75TB QAP

Sorry, i don't have the energy to check anymore.



![Scherm­afbeelding 2023-01-20 om 14 23 09](https://user-images.githubusercontent.com/36404435/213705419-e70f88f9-6235-4ee3-9fe8-4943898072df.png)
![Scherm­afbeelding 2023-01-20 om 14 23 39](https://user-images.githubusercontent.com/36404435/213705422-428dc8d3-281c-43b1-9b27-0f45be5d9644.png)
![Scherm­afbeelding 2023-01-20 om 14 24 25](https://user-images.githubusercontent.com/36404435/213705425-1409c025-9e7b-413f-a070-7d35b7393a10.png)

**Comment by cryptowhizzard** [comment]
f01917354	f01878534	128.1.220.178	1	8573	2679.06TB QAP 

https://github.com/filecoin-project/filecoin-plus-large-datasets/issues?q=is%3Aissue+f1o2nxreefzqzc2mvaqneaolpdat5yk3275r6rofa

All applications with CID Sharing and fake data.


f01936823	f01878534	128.1.220.178	1	1664	520.00TB QAP _ >

https://github.com/filecoin-project/filecoin-plus-large-datasets/issues?q=is%3Aissue+f13wvg4xve7nz3nev4bi2c7imod7lelstxfwwzjgi
 
f01941015	f01878534	128.1.220.178	1	565	176.56TB QAP

https://github.com/filecoin-project/filecoin-plus-large-datasets/issues?q=is%3Aissue+f1fsoyq7oiwdaapagpnlncbohkrkzolxxzkex6hxq+

f02005295	f01878534	128.1.220.178	1	252	78.75TB QAP


This SP (f01878534) is heavily involved in CID sharing / fraudulent storing of data.

![Scherm­afbeelding 2023-01-20 om 14 23 09](https://user-images.githubusercontent.com/36404435/213705790-2553941e-2b89-4ae3-974b-0dc82f6b6cb6.png)
![Scherm­afbeelding 2023-01-20 om 14 23 39](https://user-images.githubusercontent.com/36404435/213705796-02d1ee9a-1e0c-41e9-a912-e878705f4153.png)
![Scherm­afbeelding 2023-01-20 om 14 24 25](https://user-images.githubusercontent.com/36404435/213705800-5d230a44-c7ae-4c60-be42-5d1cebef6df2.png)

**Comment by cryptowhizzard** [comment]
<google-sheets-html-origin><style type="text/css"></style>

f01673159 | f01854080 | 128.1.207.98 | 1 | 77
-- | -- | -- | -- | --
f01889672 | f01854080 | 128.1.207.98 | 1 | 879
f01938396 | f01854080 | 128.1.207.98 | 1 | 6057
f01941015 | f01854080 | 128.1.207.98 | 1 | 2130
f01972207 | f01854080 | 128.1.207.98 | 1 | 872
f01984555 | f01854080 | 128.1.207.98 | 1 | 270
f01985575 | f01854080 | 128.1.207.98 | 1 | 290
f01994024 | f01854080 | 128.1.207.98 | 1 | 317
f02005305 | f01854080 | 128.1.207.98 | 1 | 326
f02005507 | f01854080 | 128.1.207.98 | 1 | 126

Saving some of time i see that f01854080 received the most QAP from client f01938396
![Scherm­afbeelding 2023-01-20 om 14 30 38](https://user-images.githubusercontent.com/36404435/213706399-0f92efba-66d7-4410-b194-1d66e73bf259.png)

**Comment by cryptowhizzard** [comment]
Summary

I have good reason that all SP's you provided are solely put up for datacap mining.

Let me / and the community know if you still wish to continue with this application.

**Comment by Vincent242022** [comment]
Hello CryptoWhizzard

Thankful to your detailed information and check.
Actually we cannot have an idea of the SPs' CID sharing issue and how it
happened. The only thing we can do is to stop cooperation with those
unqualified SPs and deep dive into problem inspection to avoid such things.
Since the business has to move on, we will continue contacting more SPs for
cooperation according to the rules in the community.

Sincerely appreciate your support.


CryptoWhizzard ***@***.***> 于2023年1月20日周五 21:34写道：

**Comment by lvschouwen** [comment]
@Vincent242022 
We would love to get in contact with the SP who have stored the deals so far. Can you provide us with their contact information please?

**Comment by Vincent242022** [comment]
Hi Ivschouwen

Can I know what it is for?

Thanks!


lvschouwen ***@***.***> 于2023年2月2日周四 19:20写道：

**Comment by lvschouwen** [comment]
@Vincent242022 
Because as @cryptowhizzard already pointed out, it seems the are involved in heavy CID sharing and suspicious activities on the Filecoin network. We would love to know who they are to restore trust in the community and this LDN going forward.
