### ISSUE TITLE
[DataCap Application]  - <3D Cloud Exhibition>

### ISSUE THREAD

**Issue by Camgo2020** [filecoin-project/filecoin-plus-large-datasets#1174]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: 3D Cloud Exhibition
- Website / Social Media:https://www.3dyz.com/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):100TiB
- On-chain address for first allocation:f1bast4law5qgpftqd66j7pgaxiujxopot6jxas2i

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
The 3D Cloud Exhibition (3DYZ.COM) platform focuses on 3D digitization and VR/AR all-round technical solutions. Its business covers two series of 3D scanning modeling and 3D model application, restoring real 3D space, virtual digital fantasy, and immersive roaming experience. Provide VR panorama and virtual reality solutions for digital exhibition halls, online exhibitions, smart exhibition halls, cultural expositions, factories, museums, scene-based e-commerce and other industries.
```

What is the primary source of funding for this project?
```
business income & funds
```

What other projects/ecosystem stakeholders is this project associated with?
```
nope
```

## Use-case details

Describe the data being stored onto Filecoin
```
The data we would like to store on filecoin are some VR/AR analog videos  amd 3D animation created for clients and show the technical solutions, in whcih you can simulate the reality.
```

Where was the data in this dataset sourced from?
```
produced by our tech team
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://www.3dyz.com/product/20220119173181164.html                                                                              
https://www.3dyz.com/VR/?id=1291                                                                 
https://www.3dyz.com/product/20220120144091181.html                                                                           https://www.3dyz.com/yunzhanting/
https://www.3dyz.com/product/202201191048251152.html  
https://www.3dyz.com/product/202207221810351747.html  
https://www.3dyz.com/product/202208021810481795.html  
https://www.3dyz.com/product/202205281646311588.html  
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
yes
```

What is the expected retrieval frequency for this data?
```
It is retrieved very often.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
3 to 5 years
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
China
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
offline
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
 Currently we prefer local SP in China
```

How will you be distributing deals across storage providers?
```
fairly
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
yes
```

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 100TiB

**Client address**

>f1bast4law5qgpftqd66j7pgaxiujxopot6jxas2i

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As notary i am screening your application and doing due diligence.

Looking at your application i have some questions:

As you are brand new on Github and have no history of past applications. Applying for 5PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing data and it's requirements and distribution of the data. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?

Can you provide me with some KYC details per e-mail at kyc@dcent.nl. I would like to receive an e-mail from the original domainname / contact as listed on the website that refers to this application. 
Your application is for 5PB of datacap. Can you show us some visible proof from the data size and the storage you have there?

As you can see here : https://github.com/filecoin-project/filecoin-plus-large-datasets it states:

> In order for a client and their dataset to be eligible:
> the dataset should be public, open, and mission aligned with Filecoin and Filecoin Plus. This also means that the data should be accessible to anyone > in the network, without requiring any special permissions or access requirement
> stored data should be readily retrievable on the network and this should be regularly verified (though the use of manual or automated verification > that includes retrieving data from various miners over the course of the DataCap allocation timeframe)

To make sure that you understand the rules and guidelines I would like to receive a detailed allocation plan where the amount of data and reputational SP's where you are going to store this data are included. 
For the Filecoin + program itself please note that by storing data on the Filecoin network you get 10x the power ( QAP ) of a normal sector. In return for this to be eligible for this incentive there are important rules to abide:

The data must be stored with multiple service providers. ( Not with one organization running multiple SP's but really independent organizations )
The data must be distributed over multiple regions. (Running a VPN is not allowed to fake presence in the USA for example)
The data must be retrievable by everyone in the community to check if you are really storing what you say you are storing. Running boost is highly recommended.
The data must be in line with the mission of FIL+. That means that the data must be valuable for humanity. It can be scientific or other things that people are highly interested in and is unique.
As data preparer you are allowed to store one copy yourself (if the client requests so for the sake of redundancy of the data). If you store your copy in Greater China it means that the other organizations/SP must be outside Greater China.

**Comment by Sunnyiscoming** [comment]
Hi @Camgo2020 
If you still want to apply for datacap, you can ask more notaries to do client due diligence and approve the application in slack channel. https://app.slack.com/client/TEHTVS1L6/C036JKD8NVA/thread/C03BG1MNQ4T-1673888660.823499
