### ISSUE TITLE
[DataCap Application] Doubo Live Streaming

### ISSUE THREAD

**Issue by decmob** [filecoin-project/filecoin-plus-large-datasets#1176]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Doubo
- Website / Social Media: http://doubo.tv
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5 PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100 TiB
- On-chain address for first allocation: f1cswucvq6rmuugtjrew3iqszdybn2lz55a5pkgmi

## Project details

Share a brief history of your project and organization.
```
Doubo 逗播 is founded on May, 2015. Founder team are from, SNDA, BIDU, ALIBABA. 
Doubo has got two investment, angle investment is 1Million, and Pre-A investment is 5Million. 
We have doubo.tv app, it is a mobile live platform.
And we have make VR videos too.
  

We have a legal contract with showgirl to pay for all content produced by showgirl and to acquire all rights to the content, including ownership and usage rights.


```

What is the primary source of funding for this project?
```
business revenue and founder's invest.
```

What other projects/ecosystem stakeholders is this project associated with?
```
There is no other projects/ecosystem stakeholders associated with.
```

## Use-case details

Describe the data being stored onto Filecoin
```
We live real time live content and recording content. they store in two folder. And the recording live video, video content have storage in a unique folder by UUID or unique hash value.
And we split the video to many ts files and one m3u8 file.

TS: A TS file is a type of video stream file. It's used to store our video content.
It makes use of standard MPEG compression to compress video data, mostly being used for saving streamed or broadcast video content. 

M3U8: A file with the M3U8 file extension is a UTF-8 Encoded Audio Playlist file. They are plain text files that can be used by both audio and video players to describe where media files are located.
```

Where was the data in this dataset sourced from?
```
Showgirls generate content themselves, They use mobile phone to take video, streaming their life to doubo.tv, and we served these contents.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
For samples data( maybe using VLC tool to play):  
http://pili-vod.ls.doubo.tv/fragments/z1.dl-show.148290ec1d99e/1625298073545-1625298079710.ts
http://pili-vod.ls.doubo.tv/fragments/z1.dl-show.14821af9a045c/1625155411461-1625155420214.ts
http://pili-vod.ls.doubo.tv/recordings/z1.dl-show.14f341983e85c/0_1660198771.m3u8
http://pili-vod.ls.doubo.tv/recordings/z1.dl-show.14ef7d107ac60/0_1659044672.m3u8
http://pili-vod.ls.doubo.tv/recordings/z1.dl-show.14ef345066be4/0_1658943260.m3u8
http://pili-vod.ls.doubo.tv/fragments/z1.dl-show.14828c65ab5b4/1625292759361-1625292765347.ts

```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes, we confirm this is a public dataset that can be retrieved by anyone on the network with no specific permissions or access rights required.
```

What is the expected retrieval frequency for this data?
```
No special retrieval frequency and maybe it’s probably twice a year or more.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
Expectedly 2 years and it’s likely to be extended afterwards.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
We plans to make the deals in Asia, like: Sigapore,HongKong
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
online, if needed offline can also be considered it.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
Well, we want to choose a miner with good size and credit in filecon's ecosystem.
```

How will you be distributing deals across storage providers?
```
We would divide the data up and send it to different miners with TPLabs's data distribution solutions.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, we have got some advices and resources from the community to make deals. We don’t need funding,and we need to get more weekly allocation of DC requested.
```

**Comment by decmob** [comment]
hi teams, we're updated the on-chain address for first allocation. 
Thx.

**Comment by Kevin-FF-USA** [comment]
Link to Governance Demo/Explainer video: https://drive.google.com/file/d/1KzOU4ndpfMhTLz1UKQNI-YIlXo5ofUAB/view?usp=share_link

**Comment by raghavrmadya** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 100TiB

**Client address**

> f1cswucvq6rmuugtjrew3iqszdybn2lz55a5pkgmi

**Comment by newwebgroup** [comment]
The Client contacts me through Slack
About Kyc
1：Could you send an email to [filplus-app-review@fil.org](mailto:filplus-app-review@fil.org) ？
2：Can you provide more detailed information about other storage providers participated in this program, such as you can list SPs you have contacted with at present?

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Looking at your application i have some questions:
As you are brand new on Github and have no history of past applications it seems to me that applying for 5PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?

Can you show us visible proof of the size of your data and the storage systems you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230232885049356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!

**Comment by decmob** [comment]
> Dear applicant,
> 
> Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.
> 
> Looking at your application i have some questions: As you are brand new on Github and have no history of past applications it seems to me that applying for 5PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?
> 
> Can you show us visible proof of the size of your data and the storage systems you have there?
> 
> As last question i would like you to fill out [this form](https://form.jotform.com/230232885049356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.
> 
> Thanks!

We have partners to help us deal with packing of data, distribution of data.Our partners come from many technical teams and have rich experience in car file packaging, distribution, order management, lotus or boost useing, etc.

We do not have applied for datacap in the past on different Github account names, this is my first time applying  for data cap ,but we have been involved in the Filecoin project for a long time.This is one of our stakes as follow,
https://filfox.info/zh/address/f0859013

We have doubo.tv app, which is a mobile live broadcast platform. We also participate in the production of vr video. This is our first application. But the data we produce every day is more than 10TB. Compared with the traditional public cloud storage,  1PB of data storage in cloud  is over 50 thousand dollar every year, storing it in the filecoin network can save me costs. It also guarantees the growth of my future data magnitude.
![企业微信截图_3b0197dc-89a2-48cb-948a-6bd34032380b](https://user-images.githubusercontent.com/30797094/216297780-f6518b81-419c-4797-9aaf-865bae1f89b9.png)

**Comment by cryptowhizzard** [comment]
Thanks,

But this was not what i have asked for. I asked:

>
As last question i would like you to fill out [this form](https://form.jotform.com/230232885049356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.
>

**Comment by decmob** [comment]
> Thanks,
> 
> But this was not what i have asked for. I asked:
> 
> > 
> 
> As last question i would like you to fill out [this form](https://form.jotform.com/230232885049356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.
> 
> >
@cryptowhizzard Hi, sorry about the late reply, I've read this form. But I don't really like share my personal information due to privacy reason. We might contact other notary to help through slack, also thank you for your help!
