### ISSUE TITLE
[DataCap Application]  - <YXT MUSIC LESSON>

### ISSUE THREAD

**Issue by YXTmusic** [filecoin-project/filecoin-plus-large-datasets#1184]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: YXT MUSIC LESSON
- Website / Social Media:https://yinxiaotun.com/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):100TiB
- On-chain address for first allocation:f13ygfuufickugig3o54frcmyowkgmj6zb33t3nty

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Yinxiaodou Music Lesson is an online music education platform for children under Ningbo Qiange Wanqu Technology Co., Ltd. Yinxiaodou music class takes vocal music teaching as the carrier, combines solfeggio, music appreciation, rhythm, music theory, etc., integrates diverse music knowledge content, pays attention to children's comprehensive ability development, and shapes children's future competitiveness. The Yinxiaodou music class comprehensively builds a student growth center through the form of music enlightenment AI class and live interactive class.
```

What is the primary source of funding for this project?
```
business income
```

What other projects/ecosystem stakeholders is this project associated with?
```
no
```

## Use-case details

Describe the data being stored onto Filecoin
```
The live tetecast videos & Children‘s performance videos posted and recorded on our website as well as  advertising videos on the internet which are all public
```

Where was the data in this dataset sourced from?
```
videos dataset owned by YXT Music lesson, including liveclass/performance record/advertising vidoes on the internet
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://yinxiaotun.com/liveClass 
https://yinxiaotun.com/classes                                                                                      
https://yinxiaotun.com/collections   
https://www.bilibili.com/video/BV18v411N7WN/?vd_source=1948624b755bbb0ca852ec834bd44228  https://www.bilibili.com/video/BV1hb4y1y7ib/?spm_id_from=333.788.recommend_more_video.0&vd_source=1948624b755bbb0ca852ec834bd44228 https://www.bilibili.com/video/BV1hb4y1y7ib/?spm_id_from=333.999.0.0&vd_source=1948624b755bbb0ca852ec834bd44228 https://www.bilibili.com/video/BV1q3411i7kD/?vd_source=1948624b755bbb0ca852ec834bd44228
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
yes
```

What is the expected retrieval frequency for this data?
```
frequently
```

For how long do you plan to keep this dataset stored on Filecoin?
```
5 years
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
globally
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
offline
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
Prefer to contact with local SPs in China
```

How will you be distributing deals across storage providers?
```
equally
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
yes
```

**Comment by YXTmusic** [comment]
hey Team & Galen
I have sent some signature support requests in the community on Slack.

look forward to further comments or approval.

Thanks!

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Looking at your application i have some questions:
As you are brand new on Github and have no history of past applications it seems to me that applying for 5PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?

Can you show us visible proof of the size of your data and the storage systems you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230337462961356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!

**Comment by flyworker** [comment]
This issue looks old, which oboarding technology you are going to use?
And how are you going to send to SPs?

**Comment by Sunnyiscoming** [comment]
Hi @YXTmusic 
If you still want to apply for datacap, you can ask more notaries to do client due diligence and approve the application in slack channel. https://app.slack.com/client/TEHTVS1L6/C036JKD8NVA/thread/C03BG1MNQ4T-1673888660.823499

**Comment by YXTmusic** [comment]
@Sunnyiscoming  
Sorry for the late reply.

I'll do that after I answer all the concerns from the community.

Thanks!

**Comment by YXTmusic** [comment]
@cryptowhizzard 

hello 

![image](https://user-images.githubusercontent.com/117133315/220647728-a1e56747-df13-47ab-a512-6ad6290f197a.png)

I cannot open the form anyway.

**Comment by YXTmusic** [comment]
> This issue looks old, which oboarding technology you are going to use? 
  sorry I do not understand what it means in this sentence. 
And how are you going to send to SPs?
 Currently we keep them in our own storage infra, and don't know yet how exactly to send to SPs, maybe both online and offline.
