### ISSUE TITLE
[DataCap Application] <EhostICT> - <OS Packages for GPU hosting called AIOCP>

### ISSUE THREAD

**Issue by gustjr154** [filecoin-project/filecoin-plus-large-datasets#1185]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: EhostICT
- Website / Social Media: https://www.aiocp.co.kr
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5 PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100 TiB
- On-chain address for first allocation: f1dj23xokyovdqnbgx3nis3ygk73szanzlwb2kduy

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
AIOCP is the brand name of EhostIDC’s artificial intelligence server. GPU hosting solutions for Deep Learning/ Machine Learning/ Big Data/ Autonomous Driving/ Medical Service / Education / 3D Rendering. 
EhostIDC has been providing the best IDC services to domestic and overseas users and has developed into a company capable of providing total IT services by expanding into the ICT domain.
```

What is the primary source of funding for this project?
```
Own funds and revenue of the company.
```

What other projects/ecosystem stakeholders is this project associated with?
```
No. 
```

## Use-case details

Describe the data being stored onto Filecoin
```
The images are being used on GPU servers which will be provided to our clients.
We have Docker-imaged OS packages with the various versions upon client's request. 
We will make customized packages as many as we could and store them into filecoin system for high availability.
The data samples are our marketing videos and sample design of the product. 
```

Where was the data in this dataset sourced from?
```
The data/images(docker image) come from our AIOCP R&D team. 
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://drive.google.com/file/d/13oc05GJweERWRO_VXhqHticTk_mGs5kj/view?usp=sharing
https://drive.google.com/file/d/197ZhtCDh5qyp0kCRQRIoDLpH6KeaM_YW/view?usp=sharing
https://drive.google.com/file/d/1BqJIm9B9DzrgIc7U2DS4PbPiWB4H4cLQ/view?usp=sharing
https://drive.google.com/file/d/1CqH4wWtz5KARBDcSxne54SUxrbioXxqn/view?usp=sharing
https://drive.google.com/file/d/1G1zmtfoxJ2RbYf-5XaPq4c_D-v_wZhNb/view?usp=sharing
https://drive.google.com/file/d/1GNSMx0szgjrxOKJeTBZh7_mt8xfoRqd2/view?usp=sharing
https://drive.google.com/file/d/1GjrRklEeif_VxNVrLOM8oPSPx2J1I23V/view?usp=sharing
https://drive.google.com/file/d/1P82NhTRdKql6ksDg0EvQVS2tsAPo422r/view?usp=sharing
https://drive.google.com/file/d/1Tp2KhMUU1E8YACmBVJ25lkrf1N-73Bua/view?usp=sharing
https://drive.google.com/file/d/1WS8_VsFuejVqRlT1Xyrw-q0CHFto1lUb/view?usp=sharing
https://drive.google.com/file/d/1We7XOFHjwnCdRgF-q5CLruHEwui4adJk/view?usp=sharing
https://drive.google.com/file/d/1lKkwQAgfKJu5zA9ECtxumQozZVGK-1CI/view?usp=sharing
https://drive.google.com/file/d/1pyA9aObpjugrAbjAQph_9xZLFsSqeja9/view?usp=sharing
https://drive.google.com/file/d/1pzSNn-SRTdpw4SHqEWRQUFCVdWzUHBid/view?usp=sharing
https://drive.google.com/file/d/1tY0gHY783KPW6Z5-G0Pz1mvaF0o2DmX6/view?usp=sharing
https://drive.google.com/file/d/1vL0H1soSh4TflZIQPiM1OKOpMAq-vCGj/view?usp=sharing
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
yes
```

What is the expected retrieval frequency for this data?
```
Mostly our employees in sales and R&D department in the beginning. Our goal is clients can access the data directly and use or edit according to their own needs. 
```

For how long do you plan to keep this dataset stored on Filecoin?
```
At least 3 years. As long as our company provides cloud services, it would extend. 
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
The global. Mostly Asia. 
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Both online and offline data transfer depending on the preference of storage providers.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We will select SPs who could meet our requirements in terms of storage cost, and geographical location. Since our global customers located in Europe and Asia, probs getting one or over in Europe, two or over in Asia.
```

How will you be distributing deals across storage providers?
```
We will follow the allocation rules on this basis. each SP will be distributed deals no more than 20% of all.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes. We are ready to start making deals. 
```

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 100TiB

**Client address**

> f1dj23xokyovdqnbgx3nis3ygk73szanzlwb2kduy

**Comment by Sunnyiscoming** [comment]
Same as https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1197

**Comment by simonkim0515** [comment]
Closing as this is the same as #1197
