### ISSUE TITLE
[DataCap Application] Air Liquide

### ISSUE THREAD

**Issue by Janice35** [filecoin-project/filecoin-plus-large-datasets#1192]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Air Liquide
- Website / Social Media:[https://www.airliquide.com/](https://www.airliquide.com/%EF%BF%BD)
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):200TiB
- On-chain address for first allocation: f1s5trlwomspamyukz5tv7ivq7so256sd3rhj57hq 

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
A world leader in gases, technologies and services for Industry and Health, Air Liquide is present in 75 countries with approximately 66,400 employees and serves more than 3.8 million customers and patients. Oxygen, nitrogen and hydrogen are essential small molecules for life, matter and energy. They embody Air Liquide’s scientific territory and have been at the core of the company’s activities since its creation in 1902.
```

What is the primary source of funding for this project?
```
Business revenue.
```

What other projects/ecosystem stakeholders is this project associated with?
```
No other projects.
```

## Use-case details

Describe the data being stored onto Filecoin
```
We choose videos related to our company from our channel to store in filecoin. Also, we store data on research-related chemical resources.
```

Where was the data in this dataset sourced from?
```
It comes from our Youtube channel which is made by our company.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
Yes, this is our Youtube channel.
https://www.youtube.com/user/AirLiquideCorp/shorts
Data sample:
https://drive.google.com/file/d/1UD1JcmCvWNNDhpCSeR-xyGKJK5SFx_sv/view?usp=sharing
https://drive.google.com/drive/folders/1OzN2fRs0Lcsw1WABvP-K8WmtkGk7a7NU?usp=sharing
https://drive.google.com/drive/folders/1erx58yi7nIScd-OYqVvGu2IZXpcAz9Vx?usp=sharing
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes, we confirm the data is shown to public as a promotion.
```

What is the expected retrieval frequency for this data?
```
Our expected retrieval frequency for the data is half a year.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
365 days.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
North America, Canada, Sinapore, China.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Both offline and online. We prefer to transfer data offline, and the reason is that we think this is a safer and more stable way of transferring.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We are looking for 1. reputable sp 2. experienced sp 3. sp with stable bandwidth
We will choose storage providers via slack and github. Also, we will also go to BDE platform to find sp to cooperate.
```

How will you be distributing deals across storage providers?
```
We plan choose at least 5 sps for deals, and try to make each sp have less than 20% deals.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes.
```

**Comment by MetaWaveInfo** [comment]
Can you validate your identity by sending a confirmation to filplus-app-review@fil.org?

**Comment by Janice35** [comment]
OK! I emailed to you just now.@MetaWaveInfo ![Email](https://user-images.githubusercontent.com/117071779/199470625-5262c6a8-e7f2-49b4-9c78-facb815d38f3.jpg)

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 200TiB

**Client address**

> f1s5trlwomspamyukz5tv7ivq7so256sd3rhj57hq

**Comment by MetaWaveInfo** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedpctnj25vggkwzbr7q4bwllypvgwphs7kpf5o6werfn3xwq4areo 
#### Address 
> f1s5trlwomspamyukz5tv7ivq7so256sd3rhj57hq
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1ktlkcxnmzxcdaoqfsunrg3vocfbmgv4n3mrn74a
#### Id
> 5b250bea-8576-4584-9b83-983e606069f3
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedpctnj25vggkwzbr7q4bwllypvgwphs7kpf5o6werfn3xwq4areo

**Comment by 1475Notary** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedblc6umsz6wtusx7kkq2ifmdqpgbj3jihfxhomgwymnyhipj3d6m 
#### Address 
> f1s5trlwomspamyukz5tv7ivq7so256sd3rhj57hq
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1ofq4mngy7ggcp755pfquq2gphjjnlydolf6awtq
#### Id
> 5b250bea-8576-4584-9b83-983e606069f3
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedblc6umsz6wtusx7kkq2ifmdqpgbj3jihfxhomgwymnyhipj3d6m

**Comment by Sunnyiscoming** [comment]
Is there any problem with using datacap?

**Comment by Janice35** [comment]
@Sunnyiscoming Thanks for your comment. We'll go beck to the plan.

**Comment by clriesco** [comment]
Removed stale label and reopened issue :)

**Comment by Janice35** [comment]
yes

**Comment by Janice35** [comment]
Yes!

**Comment by Janice35** [comment]
Yes!

**Comment by Janice35** [comment]
Yes!

**Comment by Janice35** [comment]
Yes!

**Comment by Janice35** [comment]
Yes, should open!

**Comment by herrehesse** [comment]
checker:manualTrigger

**Comment by Sunnyiscoming** [comment]
Hello, @Janice35 per the https://github.com/filecoin-project/notary-governance/issues/922 for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

This information will be reviewed by Fil+ Governance team to confirm validity and then the application will be allowed to move forward for additional notary review.

**Comment by Filplus-govteam** [comment]
closing until clear list of SP entities and distribution provided
