### ISSUE TITLE
[DataCap Application] <Shenzhen Meitu Media Technology Co., Ltd> 

### ISSUE THREAD

**Issue by yadielaaneveah** [filecoin-project/filecoin-plus-large-datasets#1193]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Shenzhen Meitu Media Technology Co., Ltd
- Website / Social Media: www.mitomcn.com
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):5 PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):200TiB
- On-chain address for first allocation: f1ul2nhvndar55qdqpsbjgpwsth43obz22zjgtzmq

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Meitu Media is a service provider based on overseas mainstream short video platforms,
The business is mainly to produce short videos for overseas brands and merchants for brand promotion and marketing. Different videos need to be created, so there is a large amount of video data.
```

What is the primary source of funding for this project?
```
The revenue of the company.
```

What other projects/ecosystem stakeholders is this project associated with?
```
None.
```

## Use-case details

Describe the data being stored onto Filecoin
```
There are three main parts of the content that needs to be stored
1. Overseas live video
2. TikTok content creation video
3. Video taken by e-commerce
```

Where was the data in this dataset sourced from?
```
Video produced by our company
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://drive.google.com/drive/folders/1uYYOst4J8fAesPRxy95sOmY-L_vW0zPn?usp=sharing
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes.
```

What is the expected retrieval frequency for this data?
```
once every two months.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
At least 5 years​
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Asia,China
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Offline
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
1. choose reliable and highly reputable storage suppliers​
2. Select a storage provider that can provide offline data transmission
3.If SP can support fast retrieval, we will preferentially choose
```

How will you be distributing deals across storage providers?
```
Average distribution
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Our own company has sufficient project funds
```

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 200TiB

**Client address**

> f1ul2nhvndar55qdqpsbjgpwsth43obz22zjgtzmq

**Comment by 1ane-1** [comment]
Can you proof that you have more than 400T raw data?

**Comment by Sunnyiscoming** [comment]
Hi @yadielaaneveah 
If you still want to apply for datacap, you can ask more notaries to do client due diligence and approve the application in slack channel. https://app.slack.com/client/TEHTVS1L6/C036JKD8NVA/thread/C03BG1MNQ4T-1673888660.823499
