### ISSUE TITLE
[DataCap Application] PRiMO media

### ISSUE THREAD

**Issue by Joshua-zhao** [filecoin-project/filecoin-plus-large-datasets#1194]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: PRiMO media
- Website / Social Media: https://www.primomedia.cn/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100TiB
- On-chain address for first allocation: f16o7a7abiklmmog7mgqond5xzf764gc4y7up4hdy

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.

```
PRiMO media is a marketing company established in 2014, 
located in Beijing China, provides IMC(Integrated Marketing Communication), User Operation, 
Branding, Events Marketing, Content Delivery and Visual Creativity services.

From 2014 to present, PRiMO has provided services to different comapnies in various areas 
including: BMW, BAIC Motor, Mercedes-Benz, Vokswagen, GEELY AUTO, Tencent, Huawei, Caissa, 
Alibaba Ant Financial, Alibaba Tmall, ZIROOM, Audi, Hundai, Toyota, Tiktok and so on.

```
What is the primary source of funding for this project?
```
internal fund
```

What other projects/ecosystem stakeholders is this project associated with?
```
none
```

## Use-case details

Describe the data being stored onto Filecoin
```
Aligned with the business of PRiMO media, the data to be stored onto filecoin is grouped to the following categories:
IMC(Integrated Marketing Communication)
User Operation
Branding
Events Marketing
Content Delivery 
Visual Creativity
```

Where was the data in this dataset sourced from?
```
public data backup
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
Data are mainly source material for products which can be explored via official website: https://www.primomedia.cn/
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
data are supposed to be open to public
```

What is the expected retrieval frequency for this data?
```
Static data. Retrieval once a year for internal needs
```

For how long do you plan to keep this dataset stored on Filecoin?
```
1-2 years
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Asian-pacific and America
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
supporting online and offline data transfer depending on the preference of storage providers.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
we will select SPs who could meet our requirements in terms of storage cost, storage service and geographical location.

```

How will you be distributing deals across storage providers?
```
3-5 SPs to have the data backup is our preference, and we will follow the filecoin guideline to make our data more reliable and secure.
current plan is listed below:
1 replica of data allocated to the SP located in Singapore,
1 replica of data allocated to the SP located in HK,
1 replica of data allocated to the SP located in US, which is under dicusstion;
The detailed allocation plan with more SPs is being worked on, and details will be shared here once ready.
current distribution plan is:
f01740934    Location: US
f01852363    Location: SGP
f0520660      Location: SGP
```
Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
we will reach you when needed.
```

**Comment by raghavrmadya** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 100TiB

**Client address**

>f16o7a7abiklmmog7mgqond5xzf764gc4y7up4hdy

**Comment by raghavrmadya** [comment]
The client is requested to share the screenshot of KYC email to assist in notaries' due diligence

**Comment by Joshua-zhao** [comment]
![微信图片_20221121162621](https://user-images.githubusercontent.com/22786714/203001929-1a470ded-8b43-4176-a4de-a1930041a584.jpg)

**Comment by Joshua-zhao** [comment]
> The client is requested to share the screenshot of KYC email to assist in notaries' due diligence

@raghavrmadya The snapshot of KYC email is posted

**Comment by raghavrmadya** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 100TiB

**Client address**

>f16o7a7abiklmmog7mgqond5xzf764gc4y7up4hdy

**Comment by raghavrmadya** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 100TiB

**Client address**

>f16o7a7abiklmmog7mgqond5xzf764gc4y7up4hdy

**Comment by NDLABS-OFFICE** [comment]
I noticed that this is the first round of allocation, I am willing to support and follow up in the follow-up.

**Comment by NDLABS-OFFICE** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceafuhsdru5ydbqctt536ppjp5lruij4tidte3ncxsixmgx5smyxjs 
#### Address 
> f16o7a7abiklmmog7mgqond5xzf764gc4y7up4hdy
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1yayfsv6whu3rheviucvventj3y6t542xfpb47ei
#### Id
> f18dd504-9c89-4ba0-b62f-065006b01f35
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceafuhsdru5ydbqctt536ppjp5lruij4tidte3ncxsixmgx5smyxjs

**Comment by Tom-OriginStorage** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebpw6khxzacqbhof5sgww2zoik6km4vhohqtlmqljhcxanzwaestq 
#### Address 
> f16o7a7abiklmmog7mgqond5xzf764gc4y7up4hdy
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1q6bpjlqia6iemqbrdaxr2uehrhpvoju3qh4lpga
#### Id
> f18dd504-9c89-4ba0-b62f-065006b01f35
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebpw6khxzacqbhof5sgww2zoik6km4vhohqtlmqljhcxanzwaestq

**Comment by Tom-OriginStorage** [comment]
This is the first time to sign. I will follow up on it later. If there are any problems, I will contact the owner to solve them

**Comment by filplus-checker** [comment]
## DataCap and CID Checker Report[^1]
 - Organization: `PRiMO media`
 - Client: `f16o7a7abiklmmog7mgqond5xzf764gc4y7up4hdy`
### Storage Provider Distribution
The below table shows the distribution of storage providers that have stored data for this client.

If this is the first time a provider takes verified deal, it will be marked as `new`.

For most of the datacap application, below restrictions should apply.
 - Storage provider should not exceed 25% of total datacap.
 - Storage provider should not be storing duplicate data for more than 20%.
 - Storage provider should have published its public IP address.
 - All storage providers should be located in different regions.

⚠️ [f0520660](https://filfox.info/en/address/f0520660) has sealed 100.00% of total datacap.

⚠️ [f0520660](https://filfox.info/en/address/f0520660) has unknown IP location.

⚠️ All storage providers are located in the same region.

| Provider                                            | Location | Total Deals Sealed | Percentage | Unique Data | Duplicate Deals |
| :-------------------------------------------------- | -------: | -----------------: | ---------: | ----------: | --------------: |
| [f0520660](https://filfox.info/en/address/f0520660) |  Unknown |          15.19 TiB |    100.00% |   15.19 TiB |           0.00% |

![Provider Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/1194/1671098827115.png)
### Deal Data Replication
The below table shows how each many unique data are replicated across storage providers.
- No more than 25% of unique data are stored with less than 4 providers.

⚠️ 100.00% of deals are for data replicated across less than 4 storage providers.

| Unique Data Size | Total Deals Made | Number of Providers | Deal Percentage |
| ---------------: | ---------------: | ------------------: | --------------: |
|        15.19 TiB |        15.19 TiB |                   1 |         100.00% |

![Replication Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/1194/1671098827725.png)
### Deal Data Shared with other Clients
The below table shows how many unique data are shared with other clients.
Usually different applications owns different data and should not resolve to the same CID.

✔️ No CID sharing has been observed.

[^1]: To manually trigger this report, add a comment with text `checker:manualTrigger`

**Comment by Irmagogo** [comment]
checker:manualTrigger

**Comment by cryptowhizzard** [comment]
checker:manualTrigger

**Comment by cryptowhizzard** [comment]
Hello,

It seems that this LDN is going the wrong way. According to our statistics all data is stored on a miner who is not visible on the internet / not reachable. This is against the rules of FIL+ where you have to distribute the data and the data has to be retrievable ( miner has to be online ).

Can you let us know if you wish to continue with this LDN? If so i would like you to fill out [this form](https://form.jotform.com/230232885049356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it. 

Please do mind that i need it 100% filled out, including SP Id's and their contact information to avoid that this LDN is getting further of track.

Cheers

**Comment by Sunnyiscoming** [comment]
Hi, @Joshua-zhao  please explain the abnormal information.

**Comment by Joshua-zhao** [comment]
@Sunnyiscoming @cryptowhizzard 
hi all, we will continue with this LDN for sure, and the public id problem is under fixing.
as you could see from the statistics, this LDN is just started to seal and this is the reason that the first round release quota is allocated to one SP. this is following the advise from PL consultant.
about the form, let me check if it is filled or not.
last but definitely not least, we are trying our best to resume the consumption of this LDN, but this is not just technical efforts but business issues as well, and what we need is just a little luck and patience.

**Comment by cryptowhizzard** [comment]
HI @Joshua-zhao 

Your KYC is well received.

What i meant is that i want clarity on the other SP's you want to use for the new tranche of datacap. I haven't received any, let me know when you are ready to provide the other SP's.
