### ISSUE TITLE
[DataCap Application] siyuanjiatong

### ISSUE THREAD

**Issue by metacodebean** [filecoin-project/filecoin-plus-large-datasets#1195]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: siyuanjiatong
- Website / Social Media: http://www.siyuanjt.com.cn/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 400TiB
- On-chain address for first allocation: f1fs2rynivh2jeywfkkwiasdzmjsc2cdtmu3zuzfi  

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
1. Beijing Siyuan Jiatong Technology Co., Ltd. was established in 2008. It is a gold agent certified by Cisco manufacturers, focusing on providing a full range of CISCO application solution products. At the same time, Beijing Siyuan Jiatong Technology Co., Ltd. is a professional network service company, providing computer system network construction, information technology consulting and services for enterprises and industries. The company is headquartered in Beijing and has branches in Wuhan. Beijing Siyuan Jiatong Technology Co., Ltd. has been praised for its forward-looking vision, success guarantee and professional service among its existing customers. Our customers are widely distributed in state-owned enterprises, transportation industry, education system, medical system, real estate companies and other fields.
2. The business scope of Beijing Siyuan Jiatong Technology Co., Ltd. covers a full range of services from technical consultation, solution design and implementation. With the in-depth understanding of the customer's industry and a keen grasp of customer demand changes, we can propose a targeted change plan. With the help of the professional knowledge and professional skills of Beijing Siyuan Jiatong Technology Co., Ltd. Help clients achieve a competitive advantage and improve overall performance levels. The company is committed to providing large, medium and small enterprises with: (1) Network upgrade and transformation services, including IT management consulting solutions such as consulting, design, integration, maintenance, optimization, and upgrade of network infrastructure, as well as service support such as IT operation and maintenance. (2) Application of new network technologies, including triple play (voice, data, video), network security, video surveillance, unified communications, network storage, network management and network optimization solutions and technical service support. Starting from consultation, we provide users with planning, design, sales, logistics, installation and commissioning, operation and maintenance, maintenance during the warranty period and after-warranty services.
```

What is the primary source of funding for this project?
```
Company product and service revenue.
```

What other projects/ecosystem stakeholders is this project associated with?
```
Not yet.
```

## Use-case details

Describe the data being stored onto Filecoin
```
1. Store product pictures.
2. Network device logs.
3. Monitor data.
```

Where was the data in this dataset sourced from?
```
Company.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://drive.google.com/file/d/1kp1RJDPJL2M3ytQQwFU9y1mbrddbaoty/view?usp=share_link
https://drive.google.com/file/d/1e0R7Ka76_O5yIEIXzGdqYv-yNf79j5oV/view?usp=share_link
https://drive.google.com/file/d/1egsbMSgyAxyqGVStXJTzMkRRHdWCkf_I/view?usp=share_link
https://drive.google.com/file/d/15WdJAxlwiXt7JAwKj0siUymT6MNJA7CB/view?usp=share_link
https://drive.google.com/file/d/1zNyVuQCMsl9Ap2iwYgwuJN_Vj9MEo2N1/view?usp=share_link
https://drive.google.com/file/d/1WWTwCDoXH3_PEzTFmV2IJQhDkUJnBJUv/view?usp=share_link
https://drive.google.com/file/d/1EPLLVEoK2MnS5pnqYp2gJUdJtjQqHTu5/view?usp=share_link
```

Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes
```

What is the expected retrieval frequency for this data?
```
1 time for one year.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
More than 540 Days.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Hong Kong.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Both offline mail and online download are available.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We prefer storage service providers with higher reliability.
```

How will you be distributing deals across storage providers?
```
Store to 5 SPs.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
We have funds ready for this project.
```

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 400TiB

**Client address**

> f1fs2rynivh2jeywfkkwiasdzmjsc2cdtmu3zuzfi

**Comment by metacodebean** [comment]
![image](https://user-images.githubusercontent.com/41883249/204697037-b69dd184-7171-45e5-bd63-d8f1e726cceb.png)

**Comment by 1ane-1** [comment]
Can you provide more data sample? The data sample you provided are 7 pictures.

**Comment by metacodebean** [comment]
> Can you provide more data sample? The data sample you provided are 7 pictures.

I have uploaded some videos and log files, the links are
https://drive.google.com/file/d/1tvTWJ2G68bz3qcCurBHHwKjc_LUo6CLA/view?usp=share_link
https://drive.google.com/file/d/1UYtgIU3qK9zYGBQVzhw_UWPgNfXOZTIN/view?usp=share_link
https://drive.google.com/file/d/1ClSV8M1KsJlObQ8ah0Eyn_tsNr59_ckX/view?usp=share_link
https://drive.google.com/file/d/1m-RxjCHlK_RWhMOffPVSx5OHLEAMWSqj/view?usp=share_link
https://drive.google.com/file/d/1gYRUNzepRJ4rqL47bQ1cBb63RgLDuJ_a/view?usp=share_link
https://drive.google.com/file/d/1rkxysp2pBywk2S6maur8xTrVfQ9U-eBf/view?usp=share_link

**Comment by 1ane-1** [comment]
> > Can you provide more data sample? The data sample you provided are 7 pictures.
> 
> I have uploaded some videos and log files, the links are https://drive.google.com/file/d/1tvTWJ2G68bz3qcCurBHHwKjc_LUo6CLA/view?usp=share_link https://drive.google.com/file/d/1UYtgIU3qK9zYGBQVzhw_UWPgNfXOZTIN/view?usp=share_link https://drive.google.com/file/d/1ClSV8M1KsJlObQ8ah0Eyn_tsNr59_ckX/view?usp=share_link https://drive.google.com/file/d/1m-RxjCHlK_RWhMOffPVSx5OHLEAMWSqj/view?usp=share_link https://drive.google.com/file/d/1gYRUNzepRJ4rqL47bQ1cBb63RgLDuJ_a/view?usp=share_link https://drive.google.com/file/d/1rkxysp2pBywk2S6maur8xTrVfQ9U-eBf/view?usp=share_link

Could you provide the screenshot of your total data size？The pics and videos can't proof you need 5PiB datacap.
Thanks a lot~

**Comment by metacodebean** [comment]
> > > Can you provide more data sample? The data sample you provided are 7 pictures.
> > 
> > 
> > I have uploaded some videos and log files, the links are https://drive.google.com/file/d/1tvTWJ2G68bz3qcCurBHHwKjc_LUo6CLA/view?usp=share_link https://drive.google.com/file/d/1UYtgIU3qK9zYGBQVzhw_UWPgNfXOZTIN/view?usp=share_link https://drive.google.com/file/d/1ClSV8M1KsJlObQ8ah0Eyn_tsNr59_ckX/view?usp=share_link https://drive.google.com/file/d/1m-RxjCHlK_RWhMOffPVSx5OHLEAMWSqj/view?usp=share_link https://drive.google.com/file/d/1gYRUNzepRJ4rqL47bQ1cBb63RgLDuJ_a/view?usp=share_link https://drive.google.com/file/d/1rkxysp2pBywk2S6maur8xTrVfQ9U-eBf/view?usp=share_link
> 
> Could you provide the screenshot of your total data size？The pics and videos can't proof you need 5PiB datacap. Thanks a lot~

<img width="594" alt="image" src="https://user-images.githubusercontent.com/41883249/206148862-e8640f01-b674-4a31-9183-941c985cea48.png">
This is part of our data.

**Comment by Tom-OriginStorage** [comment]
It looks good. I'll sign it

**Comment by Tom-OriginStorage** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceayi76q3lhbyafxehgq2azidpez6lzyfr3ev4gvfw5ojubdwlcgyu 
#### Address 
> f1fs2rynivh2jeywfkkwiasdzmjsc2cdtmu3zuzfi
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1q6bpjlqia6iemqbrdaxr2uehrhpvoju3qh4lpga
#### Id
> bed16d99-59aa-4138-9f5c-5279a0c2875c
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceayi76q3lhbyafxehgq2azidpez6lzyfr3ev4gvfw5ojubdwlcgyu

**Comment by xiaoyuaiheshui** [comment]
It looks good. I'll sign it

**Comment by herrehesse** [comment]
@xiaoyuaiheshui "It looks good. I'll sign it" is not due diligence. 

The above miners seem to be all from the same entity and have gotten over 300P worth of datacap. Could be highly fraudulent and should be on hold until more is known.

@metacodebean Dear Applicant,

_(Your website is not reachable, please resolve)_

Due to the increased amount of erroneous/wrong Filecoin+ data recently, on behalf of the entire community, we feel compelled to go deeper into datacap requests. Hereby to ensure that the overall value of the Filecoin network and Filecoin+ program increases and is not abused.

Please answer the questions below as comprehensively as possible.

**Customer data**

- Could you demonstrate exactly how and to what extent customer contact occurred? 

We expect that for the onboarding of customers with the scale of an LDN there would have been at least multiple email and perhaps several chat conversations preceding it. A single email with an agreement does not qualify here.

- Did the customer specify the amount of data involved in this relevant correspondence?

- Why does the customer in question want to use the Filecoin+ program? 

_Should this only be soley for acquiring datacap this is of course **out of the question**. The customer must have a legitimate reason for wanting to use the Filecoin+ program which is intended as a program to store useful and public datasets on the network._ 

- Why is the customer data considered Filecoin+ eligible?

_(As an intermediate solution Filecoin offers the FIL-E program or the glif.io website for business datasets that do not meet the requirements for a Filecoin+ dataset)_


**Files and Processing**

- Could you please demonstrate to us how you envision processing and transporting the customer data in question to any location for preparation?
- Would you demonstrate to us that the customer, the preparer and the intended storage providers all have adequate bandwidth to process the set with its corresponding size?
- Would you tell us how the data set preparer takes into account the prevention of duplicates in order to prevent data cap abuse?


Hopefully you understand the caution the overall community has for onboarding the wrong data. We understand the increased need for Filecoin+, however, we must not allow the program to be misused. Everything depends on a valuable and useful network, let's do our best to make this happen. Together.

**Comment by cryptowhizzard** [comment]
Hi there,

Doing retrieval tests failed here for these providers. None of the deals stored are retrievable and they all come back with the same error:

Example1 -> Deal ID 21623095
retrieve: offer error: retrieval query offer errored: failed to fetch piece to retrieve from: getting pieces for cid QmYXoGqwxvq3xzy8s22Bd5ySvyL85SskjBiP2YZCXzFWCp: getting pieces containing block QmYXoGqwxvq3xzy8s22Bd5ySvyL85SskjBiP2YZCXzFWCp: failed to lookup index for mh 1220976ff1281523b41a3905f17239e5151d01f392cc11ce23ce2c5023a4a64c0d01, err: datastore: key not found

Example2 -> Deal ID 21512169
retrieve: offer error: retrieval query offer errored: failed to fetch piece to retrieve from: getting pieces for cid QmVZNyBweu1iMSzkmshjJDfkNrWP6BX1vrMSpbBsk119Sj: getting pieces containing block QmVZNyBweu1iMSzkmshjJDfkNrWP6BX1vrMSpbBsk119Sj: failed to lookup index for mh 12206b448fd102baba908c3b6685d7c73e0c294dc05179f02c3ac5d5e8c7f7c1ae54, err: datastore: key not found

Example3 -> Deal ID 21528237
retrieve: offer error: retrieval query offer errored: failed to fetch piece to retrieve from: getting pieces for cid QmRppoH7UhWqTEbhkmRKNgZHUmiUtQ8VjsYWpFBXCfxvuf: getting pieces containing block QmRppoH7UhWqTEbhkmRKNgZHUmiUtQ8VjsYWpFBXCfxvuf: failed to lookup index for mh 122033cabb36381846d2620d028dbd2ee1a233a426f04450b07258a589bf4cac25ba, err: datastore: key not found

Example4 -> Deal ID 21551337
retrieve: offer error: retrieval query offer errored: failed to fetch piece to retrieve from: getting pieces for cid QmTwBSiS2Rz9wrewtNFTVcjLBMpLyHv3y1Fn1PDJhkXtUk: getting pieces containing block QmTwBSiS2Rz9wrewtNFTVcjLBMpLyHv3y1Fn1PDJhkXtUk: failed to lookup index for mh 12205322ef13da82bacf5d4a5eb684750c94051f0cc392645c91678918f0beebca15, err: datastore: key not found

Before datacap can be granted this situation must be resolved. The data stored in the FIL+ program needs to be retrievable and none of this stored data is.

I advise @metacodebean to contact his service providers and provide a solution before continuing this project.
@metacodebean please ask your SP's to switch to boost to have the data properly stored and retrievable and wait until this is done.

**Comment by cryptowhizzard** [comment]
@FroghubMan can you please cancel your proposal. We must wait until this situation is resolved.

**Comment by Sunnyiscoming** [comment]
@metacodebean Any update here?

**Comment by cryptowhizzard** [comment]
Feb 15 23:40:03 proposals dealscanner-f01987325-f01852664: Error: Failed to retrieve content with candidate miner f01852664: data transfer failed: deal errored: getting pieces for cid QmbizRacw3A9E4n7sKFbKWMXV4yV26AsMi3FBc61xxgNiP: getting pieces containing block QmbizRacw3A9E4n7sKFbKWMXV4yV26AsMi3FBc61xxgNiP: failed to lookup index for mh 1220c6e0ffeed9d3c32225e6c46d7c987fd2f03bc7f0201bf38dbe718812bd5860bc, err: datastore: key not found

**Comment by C00kies77** [comment]
checker:manualTrigger

**Comment by dongpo313** [comment]
checker:manualTrigger

**Comment by metacodebean** [comment]
Hello, we will look for reputable, technologically mature SP to continue to cooperate, thank you!

**Comment by dongpo313** [comment]
checker:manualTrigger
