### ISSUE TITLE
[DataCap Allocation] - 1 PB Allocation Request

### ISSUE THREAD

**Issue by BHK-Industry** [filecoin-project/filecoin-plus-large-datasets#1196]
---
name: Large Dataset Notary application
about: Clients should use this application form to request a DataCap allocation via a LDN for a dataset
title: "1 PB Allocation Request"
labels: 'application, Phase: Diligence'
assignees: ''

---
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: BHK Industry
- Website / Social Media: www.bhkindustry.com
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 1PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 35TiB
- On-chain address for first allocation:  f3waep5r2qf4hvfgslvvieesvsb6mocgyl3gz2c73kqu72tmqv2yhdxez436fr7v6jd6vumgsmdiywp76ivvoa
- Region: Europe

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Started Filecoin sealing in Jun. 2021
Expanding and optimising our hardware cluster 
Planning of buying more hardware and increasing sealing capacity 
```

What is the primary source of funding for this project?
```
Revenue of BHK Industry (IT Support, Programming, PC Selling) 
```

What other projects/ecosystem stakeholders is this project associated with?
```
Big Data Exchange 
Evergreen 
Moonlanding 
```

## Use-case details

Describe the data being stored onto Filecoin
```
Deals from data exchanges 
Small private deals
```

Where was the data in this dataset sourced from?
```
Deals from data exchanges, changing clients 
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
![image-4](https://user-images.githubusercontent.com/115569094/204632427-13074ce4-7dde-4c2d-88d5-750c7b007643.png)
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes, it is an encrypted 101 GB dataset. 
```

What is the expected retrieval frequency for this data?
```
6-8 months
```

For how long do you plan to keep this dataset stored on Filecoin?
```
1 year 25 weeks
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Germany, Europe 
Nevada, US
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Depends on clients requirements 
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
Daily encrypted backups using Acronis Enterprise software
```

How will you be distributing deals across storage providers?
```
We are a SP ourselves. 
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Darma Capital for collateral (50.000 FIL)
We require some help with the finalisation of the FIL+ layer from Protocol Labs. 
```

**Comment by BHK-Industry** [comment]
> Please answer all of questions on the application.

All questions have been answered.

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 1PiB

**Expected weekly DataCap usage rate**

> 35TiB

**Client address**

> f3waep5r2qf4hvfgslvvieesvsb6mocgyl3gz2c73kqu72tmqv2yhdxez436fr7v6jd6vumgsmdiywp76ivvoa

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Looking at your application i have some questions:
As you are brand new on Github and have no history of past applications it seems to me that applying for 1 PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?

Can you show us visible proof of the size of your data and the storage systems you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230232885049356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!

**Comment by BHK-Industry** [comment]
Dear Cryptowhizzard, 

Thank you for your reply. 

Please see attached our stored data. 

![Fil+ Proof of Data](https://user-images.githubusercontent.com/115569094/216838057-9d24f2de-70ce-45bf-b379-719f307c538b.png)
![Fil+ Proof of Data png_2](https://user-images.githubusercontent.com/115569094/216838058-65bba03b-f3ea-4a11-bcf5-dfac696a6212.png)

**Comment by BHK-Industry** [comment]
We visited ESPA, worked with Factor 8 Solutions and did Blockchain courses. 
[Zertifikate.pdf](https://github.com/filecoin-project/filecoin-plus-large-datasets/files/10611875/Zertifikate.pdf)

**Comment by cryptowhizzard** [comment]
Thanks, that looks good!

Can you fill in the form like i requested? I am keen to learn about the role here you want to take ( SP and DP? ) or is someone going to do the data preparation for you? 

What i would also recommend is that, since we are talking about encrypted data, we move this application towards Fil-E.

**Comment by BHK-Industry** [comment]
Excellent, I've filled out the forum. We are SP as well as DP.

**Comment by cryptowhizzard** [comment]
Ok clear.

Can you let me know how you will distribute the data? One copy you can store yourself on your own platform, who are the other 3?

**Comment by cryptowhizzard** [comment]
I will notify kevin to start the Fil-E proces

**Comment by BHK-Industry** [comment]
One copy will be stored on PikNik, the other 2 will be determined by the Big Data Exchange.

**Comment by cryptowhizzard** [comment]
I notified Fil-E to pick up from here. Looking forward to the cooperation!

**Comment by kevzak** [comment]
can we close this application and refer to the updated one [here](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1588) @BHK-Industry ? cc @simonkim0515
