### ISSUE TITLE
[DataCap Application] <Sichuan Jingzhi Education Technology Co.,Ltd.> - <Jingzhi Education>

### ISSUE THREAD

**Issue by jacktree7** [filecoin-project/filecoin-plus-large-datasets#1198]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Sichuan Jingzhi Education Technology Co.,Ltd.
- Website / Social Media:https://www.jingshengya.net/#/index
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5 PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 200 TiB
- On-chain address for first allocation:f1j2yfkrh7dsglj54eurkp2ykjqqwgzlp5jyyufki

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Jing career education system belongs to the independent brand of Sichuan Jingzhi Education Technology Co.,Ltd.We Provide online college entrance examination volunteer application, new college entrance examination subject selection, career planning, comprehensive quality assessment, strong foundation plan and other college planning services for more than 9 million college students.
Since 2016, we have provided professional services for more than 3 million candidates nationwide and become an influential career planning and volunteer application platform in the industry. After years of research and accumulation, Jing Career has covered 29 provinces and cities nationwide, with nearly 10,000 registered users.
```

What is the primary source of funding for this project?
```
Business Development and Shareholders' Own Funds.
```

What other projects/ecosystem stakeholders is this project associated with?
```
None.
```

## Use-case details

Describe the data being stored onto Filecoin
```
Mainly videos and documents,the content is mainly subject tutorial videos,career lesson plans,career classroom,etc.
```

Where was the data in this dataset sourced from?
```
Self-developed and produced mainly.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
Of course.
https://www.jingshengya.net/#/careerManagement/study-course-detail?ID=95ed7851-a8cc-48ca-dace-08d9c5e132a2
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes,I confirm that this is a public dataset that can be retrieved by anyone on the Network.
```

What is the expected retrieval frequency for this data?
```
Due to the large amount of data,it will not be retrieved often.Maybe once a year.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
At least 2 years.We will have an attempt to store for a long time.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Asian region is the main,of course,other regions are suitable is not impossible to consider.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
This depends on the location of the SP,both online and offline transfers are possible,taking into account transfer costs,efficiency,etc.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
First of all there must be a certain scale to secure the data,so we need to find some miners with scale and credit through slack and information on githu.Secondly the SP team needs to have some development capability to support subsequent file retrieval in the Filecoin network.
```

How will you be distributing deals across storage providers?
```
Spilt the data and send it to different miners according to the official filecoin rules in order to truly decentralize.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
We are ready to make deals.
```

**Comment by Kevin-FF-USA** [comment]
Link to explainer video: https://drive.google.com/file/d/1vZq3yT4g7dhVC_CYqWqNg8aC-Qg-pWYi/view?usp=share_link for Governance Meeting Demo

**Comment by jacktree7** [comment]
> Link to explainer video: https://drive.google.com/file/d/1vZq3yT4g7dhVC_CYqWqNg8aC-Qg-pWYi/view?usp=share_link for Governance Meeting Demo

Yes,Kevin,we had do that,thanks!

**Comment by jacktree7** [comment]
Hi, @raghavrmadya @Kevin-FF-USA @galen-mcandrew ,Can we get updates?Thanks!~

**Comment by jacktree7** [comment]
@simonkim0515 Hi,Simon,I see that a large number of LDNs were approved this time, some even applied later than us and did not go to the governor's meeting, and I wonder if there is anything else we can do?Thanks！～Look forward to reply～

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 200TiB

**Client address**

>f1j2yfkrh7dsglj54eurkp2ykjqqwgzlp5jyyufki

**Comment by psh0691** [comment]
I have a few questions for your DataCap approval.
1. Are there any storage providers involved?
2. Can you disclose the file coin node you want to save?

**Comment by jacktree7** [comment]
> Could you give some screenshot of you having more than 500T of raw data? Also data samples?

Thank you for your question. Please see screenshots of some of the sample data, including but not limited to course lesson plans, classroom videos, career plans, expert classes, etc. For more information, please see the official website: https://www.jingshengya.net/#/index

![01](https://user-images.githubusercontent.com/116623999/206337110-1665d2d5-f5a9-41ba-a0ae-b697800e65e7.png)
![02](https://user-images.githubusercontent.com/116623999/206337115-4cfd49f7-b17a-46c2-8512-b090692eb5b8.png)
![03](https://user-images.githubusercontent.com/116623999/206337118-047419b2-0b27-459b-a44c-c0bfa0e5cbfd.png)
![04](https://user-images.githubusercontent.com/116623999/206337123-06a9825a-f524-4d77-8bc7-78a62b0a0622.png)
![05](https://user-images.githubusercontent.com/116623999/206337127-2cccae97-72b0-4abd-9d8b-571fbb819854.png)
![06](https://user-images.githubusercontent.com/116623999/206337135-835ed80e-498c-4a6a-8e78-f9738797c956.png)

**Comment by kernelogic** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceamvapew3vja7t7ljlmxdh3imwmg2km3pe3n3jzwojnihkodt7g6e 
#### Address 
> f1j2yfkrh7dsglj54eurkp2ykjqqwgzlp5jyyufki
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### Id
> 9fcb1ad0-2f83-41c7-a3a3-327dfeb28540
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceamvapew3vja7t7ljlmxdh3imwmg2km3pe3n3jzwojnihkodt7g6e

**Comment by Fatman13** [comment]
> We are currently communicating with SPs such as Bitrise Capital, ND Labs, Guazi Dynamic, and New Web Group via slack

Hello, all. @fatman13 from Guazi Dynamic here. We atm do not have data on-boarding plans with respect to this dataset.

**Comment by Sunnyiscoming** [comment]
Is there any problem with using datacap?

**Comment by jacktree7** [comment]
Previously delayed due to personal family reasons and preparation of data, will now get back into the swing of things.

**Comment by OpenGate01** [comment]
checker:manualTrigger

**Comment by OpenGate01** [comment]
The report looks good, willing to support this round, I'll stay tuned and please follow the rules.

**Comment by OpenGate01** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebjbdw5pvc34hrqbbylwkhns4yy7as6uqncugyhnp7dtrdhmdbwym 
#### Address 
> f1j2yfkrh7dsglj54eurkp2ykjqqwgzlp5jyyufki
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1im4hmtbfzqnx7ir74kdaiu4ynjhgqh3sdi2snla
#### Id
> 23840488-0495-4a40-82a1-a89a2cf1834d
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebjbdw5pvc34hrqbbylwkhns4yy7as6uqncugyhnp7dtrdhmdbwym

**Comment by Aaron01230** [comment]
checker:manualTrigger

**Comment by Aaron01230** [comment]
The report shows that SP distribution is healthy and the retrieval success rate is high and the data replication is healthy , willing to support this round.

**Comment by Aaron01230** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecxatj73rundaqce5oljzoadd3p6ge3uy5n4mmojwywkm5vxmoilo 
#### Address 
> f1j2yfkrh7dsglj54eurkp2ykjqqwgzlp5jyyufki
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1xrnysd4gimg64d4l6qi7ulzwwq22c6vfg6lpw3i
#### Id
> 23840488-0495-4a40-82a1-a89a2cf1834d
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecxatj73rundaqce5oljzoadd3p6ge3uy5n4mmojwywkm5vxmoilo

**Comment by ipollo00** [comment]
checker:manualTrigger

**Comment by ipollo00** [comment]
Hi @jacktree7, I'm curious about why the checker report of this round is not as good as the previous report.

**Comment by jacktree7** [comment]
> 你好@jacktree7，我很好奇为什么这一轮的检查员报告不如上一次的报告。 请向我们详细展示您的计划。

The sealing speed of the SPs nodes we contacted is not the same. We will suspend the cooperation of the nodes with fast sealing later, so that those nodes with less data backup can catch up with the progress. Anyway, we'll eventually meet the rules.

**Comment by 1ane-1** [comment]
> > 你好@jacktree7，我很好奇为什么这一轮的检查员报告不如上一次的报告。 请向我们详细展示您的计划。
> 
> The sealing speed of the SPs nodes we contacted is not the same. We will suspend the cooperation of the nodes with fast sealing later, so that those nodes with less data backup can catch up with the progress. Anyway, we'll eventually meet the rules.

Hope you can do it as you say. Support this round.

**Comment by 1ane-1** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedhfaymhhuhhn7aefhqof5nnhsvfq6qs7ravbkxblzb2zt7cpnoi2 
#### Address 
> f1j2yfkrh7dsglj54eurkp2ykjqqwgzlp5jyyufki
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1mdk7s2vntzm6hu35yuo6vjubtrpfnb2awhgvrri
#### Id
> 0e3242de-c53b-44b6-9d94-d915ea305803
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedhfaymhhuhhn7aefhqof5nnhsvfq6qs7ravbkxblzb2zt7cpnoi2

**Comment by ipollo00** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacea2r4tmiqaoghxkfryvi663alzoz7pxykecd6buigeeyweu3r46ri 
#### Address 
> f1j2yfkrh7dsglj54eurkp2ykjqqwgzlp5jyyufki
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1n5wlrrhoxpkgwij25xrtt7w7g2k3fhbthmdn6ri
#### Id
> 0e3242de-c53b-44b6-9d94-d915ea305803
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacea2r4tmiqaoghxkfryvi663alzoz7pxykecd6buigeeyweu3r46ri

**Comment by clriesco** [comment]
The bot has not been active due to an API outage. It should have been resolved 4 days ago.

**Comment by jacktree7** [comment]
checker:manualTrigger

**Comment by jacktree7** [comment]
In progress

**Comment by mikezli** [comment]
checker:manualTrigger

**Comment by mikezli** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb4magrtb3ybj2mxsivwle7k37yshbcj7qmavskr2ctj2dabz2bam 
#### Address 
> f1j2yfkrh7dsglj54eurkp2ykjqqwgzlp5jyyufki
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1dnb3uz7sylxk6emti3ififcvu3nlufnnsjui6ea
#### Id
> 803cf216-39cd-4569-858d-fb94ddf3fc11
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb4magrtb3ybj2mxsivwle7k37yshbcj7qmavskr2ctj2dabz2bam

**Comment by mikezli** [comment]
The retrieval rate has improved, but data backup still needs to be improved. In the next round, f02122388 needs to reduce orders.

**Comment by woshidama323** [comment]
checker:manualTrigger

**Comment by woshidama323** [comment]
Please improve the f02122388 issue next round ,
Will support first

**Comment by woshidama323** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceasgi6hquld5wzaoh52srdtf6i7zvbfzwhd7var3m6o5kbwojtgzw 
#### Address 
> f1j2yfkrh7dsglj54eurkp2ykjqqwgzlp5jyyufki
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f12tk3adljauwnd3hjbigpfxb7b7gdlj63p6afwtq
#### Id
> 803cf216-39cd-4569-858d-fb94ddf3fc11
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceasgi6hquld5wzaoh52srdtf6i7zvbfzwhd7var3m6o5kbwojtgzw

**Comment by jacktree7** [comment]
checker:manualTrigger

**Comment by zcfil** [comment]
checker:manualTrigger

**Comment by zcfil** [comment]
Deal Data Replication
⚠️ 88.54% of deals are for data replicated across less than 4 storage providers.

This issue has been going on for several rounds, will there be any improvements in the future?

**Comment by jacktree7** [comment]
> 交易数据复制 ⚠️88.54% 的交易涉及在少于 4 个存储提供商之间复制的数据。
> 
> 这个问题已经持续了好几轮了，以后会有改进吗？

Yes, stay tuned, we'll improve later.

**Comment by zcfil** [comment]
Willing to support this round due to smaller data upfront and fixing one of the unhealthy reports, but please follow the rules and fix the other unhealthy report, will follow up with data distribution

**Comment by zcfil** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec5z6xioustthtqukgjhotyu57mbohnupsm5u2mjov45yug3vilja 
#### Address 
> f1j2yfkrh7dsglj54eurkp2ykjqqwgzlp5jyyufki
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1cjzbiy5xd4ehera4wmbz63pd5ku4oo7g52cldga
#### Id
> 718f0cdc-3555-4ce6-b212-493ba788d7a1
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec5z6xioustthtqukgjhotyu57mbohnupsm5u2mjov45yug3vilja

**Comment by NiwanDao** [comment]
Looking forward to see improvement in the next round.

**Comment by NiwanDao** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceawna44xxrvq4lr6jef7ytmypggdwkjzdjiuvtjzfnveiodkjfcny 
#### Address 
> f1j2yfkrh7dsglj54eurkp2ykjqqwgzlp5jyyufki
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1a2lia2cwwekeubwo4nppt4v4vebxs2frozarz3q
#### Id
> 718f0cdc-3555-4ce6-b212-493ba788d7a1
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceawna44xxrvq4lr6jef7ytmypggdwkjzdjiuvtjzfnveiodkjfcny

**Comment by jacktree7** [comment]
checker:manualTrigger

**Comment by Sunnyiscoming** [comment]
Hello, @jacktree7 per the https://github.com/filecoin-project/notary-governance/issues/922 for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

This information will be reviewed by Fil+ Governance team to confirm validity and then the application will be allowed to move forward for additional notary review.

**Comment by jacktree7** [comment]
checker:manualTrigger

**Comment by ipollo00** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceafhfy3vadfeygflhzb2ohj5pmu4oget5m4fjzhnk3a527uxd67bi 
#### Address 
> f1j2yfkrh7dsglj54eurkp2ykjqqwgzlp5jyyufki
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1n5wlrrhoxpkgwij25xrtt7w7g2k3fhbthmdn6ri
#### Id
> 0c82cba0-fdb9-4db0-a6e1-f282b0cfaea4
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceafhfy3vadfeygflhzb2ohj5pmu4oget5m4fjzhnk3a527uxd67bi

**Comment by jacktree7** [comment]
<img width="851" alt="image" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/116623999/d52438f8-2c71-4f14-a748-e2b73369440b">

**Comment by AlanGreaterheat** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedegfozlaykyfuy4kbdz5kzszrqzhgt4bq4tlayugmn275rba2eow 
#### Address 
> f1j2yfkrh7dsglj54eurkp2ykjqqwgzlp5jyyufki
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1pnmzlxj7cfeo2v6oj5nco46hkg2l46wj7o4xxui
#### Id
> 0c82cba0-fdb9-4db0-a6e1-f282b0cfaea4
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedegfozlaykyfuy4kbdz5kzszrqzhgt4bq4tlayugmn275rba2eow

**Comment by herrehesse** [comment]
checker:manualTrigger

**Comment by jacktree7** [comment]
checker:manualTrigger

**Comment by jacktree7** [comment]
checker:manualTrigger

**Comment by jacktree7** [comment]
The previously issued DCs have all been sealed, why didn't they trigger the next round of bot assignments, can you help with that, thanks!

@Sunnyiscoming @simonkim0515

**Comment by jacktree7** [comment]
https://github.com/keyko-io/filecoin-verifier-frontend/issues/884

The work order has been submitted, please help resolve it, thank you very much! @simonkim0515 @Sunnyiscoming

**Comment by 1ane-1** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecnupq3y7yaqfc5xl5bhlz76hdd4ykc5l54gjndqdbleta43zdxfi 
#### Address 
> f1j2yfkrh7dsglj54eurkp2ykjqqwgzlp5jyyufki
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1mdk7s2vntzm6hu35yuo6vjubtrpfnb2awhgvrri
#### Id
> f0857c87-363b-42f5-848e-1c35501b3c4d
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecnupq3y7yaqfc5xl5bhlz76hdd4ykc5l54gjndqdbleta43zdxfi

**Comment by a1991car** [comment]
checker:manualTrigger

**Comment by a1991car** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacechq6truodjz4vbbgsd7t4nbfqfvwu7brkr2qikv7nwygnmgafxl6 
#### Address 
> f1j2yfkrh7dsglj54eurkp2ykjqqwgzlp5jyyufki
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1qnumecdypgrbaebtkdfjnwt5ndacadcuas3deiq
#### Id
> f0857c87-363b-42f5-848e-1c35501b3c4d
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacechq6truodjz4vbbgsd7t4nbfqfvwu7brkr2qikv7nwygnmgafxl6

**Comment by jacktree7** [comment]
checker:manualTrigger

**Comment by NewHuoPool** [comment]
@jacktree7 can you explain this?
![2456#2](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/117884185/961c1243-0ab0-4f5b-9d8b-fa2fba78d94e)

**Comment by jacktree7** [comment]
There's still a portion of the DC that's still being sealed, and we'll spread it out in later rounds to make the report look perfect,thanks！

> @jacktree7你能解释一下吗？ ![2456#2](https://private-user-images.githubusercontent.com/117884185/289025421-961c1243-0ab0-4f5b-9d8b-fa2fba78d94e.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIwMjgxODksIm5iZiI6MTcwMjAyNzg4OSwicGF0aCI6Ii8xMTc4ODQxODUvMjg5MDI1NDIxLTk2MWMxMjQzLTBhYjAtNGY1Yi05ZDhiLWZhMmZiYTc4ZDk0ZS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwOFQwOTMxMjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MzNhMzE4NDZjNzE1ZDdiZTY4MDdmOTA2YThlYjMyMzRlODcwN2E2OGVlZmJkZmEyYjEzNzNlMmQ4ZTE1ZTE0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.DKCWsMs2wtpqjTJlGA67CYHJEP1TwB2LgOikgsZWMxs)

**Comment by Aaron01230** [comment]
according the info above, i will support this round

**Comment by Aaron01230** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecexrorojzxp2vn4gj7vekjsze6eefeh5js7q7xouhdtxcn2x63t2 
#### Address 
> f1j2yfkrh7dsglj54eurkp2ykjqqwgzlp5jyyufki
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1xrnysd4gimg64d4l6qi7ulzwwq22c6vfg6lpw3i
#### Id
> 0a60db94-85dc-4bf5-9a82-c27ba841b192
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecexrorojzxp2vn4gj7vekjsze6eefeh5js7q7xouhdtxcn2x63t2

**Comment by jacktree7** [comment]
checker:manualTrigger

**Comment by Sunnyiscoming** [comment]
Please provide ID, City, Country, Organization of each SP here.

**Comment by jacktree7** [comment]
checker:manualTrigger

**Comment by jacktree7** [comment]
Even though it's the last round, Regarding the Storage Provider Distribution tip, it is obvious to see that the percentage is decreasing.

The information is updated below:

f02363308	 Fly  Tokyo, Tokyo, JP
f02850071	Datastone  Shenzhen, Guangdong, CN
f02122388	nanhao  Shenzhen, Guangdong, CN
f02829748	xingcircle  Shenzhen, Guangdong, CN
f02830476	Xing  Shenzhen, Guangdong, CN
f02829749	xingcircle  Shenzhen, Guangdong, CN
f02182798	nanhao  Shenzhen, Guangdong, CN
f02850016	Datastone   Hong Kong, Central and Western, HK
f02830451	HK_Fil  Hong Kong, Central and Western, HK
f02820089	Xingxing  Hong Kong, Central and Western, HK
f02363306	Seven  Singapore, Singapore, SG
f02829744	HK_Fil  Hong Kong, Central and Western, HK
f02850067	Datastone  Shenzhen, Guangdong, CN
f02807399  CNCTGNet  Shenzhen, Guangdong, CN
f02363300	xingxing  Tokyo, Tokyo, JP
f02078669	HKblockchain  Los Angeles, California, US
f02182743	Air  Shenzhen, Guangdong, CN
f02182802	Henry  London, England, GB
f02850015	Datastone  Hong Kong, Central and Western, HK

Thanks！

**Comment by jacktree7** [comment]
Even though it's the last round, Regarding the Storage Provider Distribution tip, it is obvious to see that the percentage is decreasing.

The information is updated below:

f02363308 Fly Tokyo, Tokyo, JP
f02850071 Datastone Shenzhen, Guangdong, CN
f02122388 nanhao Shenzhen, Guangdong, CN
f02829748 xingcircle Shenzhen, Guangdong, CN
f02830476 Xing Shenzhen, Guangdong, CN
f02829749 xingcircle Shenzhen, Guangdong, CN
f02182798 nanhao Shenzhen, Guangdong, CN
f02850016 Datastone Hong Kong, Central and Western, HK
f02830451 HK_Fil Hong Kong, Central and Western, HK
f02820089 Xingxing Hong Kong, Central and Western, HK
f02363306 Seven Singapore, Singapore, SG
f02829744 HK_Fil Hong Kong, Central and Western, HK
f02850067 Datastone Shenzhen, Guangdong, CN
f02807399 CNCTGNet Shenzhen, Guangdong, CN
f02363300 xingxing Tokyo, Tokyo, JP
f02078669 HKblockchain Los Angeles, California, US
f02182743 Air Shenzhen, Guangdong, CN
f02182802 Henry London, England, GB
f02850015 Datastone Hong Kong, Central and Western, HK

Thanks！

**Comment by Chuangshi1** [comment]
[f02850067](https://filfox.info/en/address/f02850067): 22.71%, [f02850071](https://filfox.info/en/address/f02850071): 22.74%, [f02850015](https://filfox.info/en/address/f02850015): 22.46%, [f02850016](https://filfox.info/en/address/f02850016): 22.58%

[f02850067](https://filfox.info/en/address/f02850067): 33.24%, [f02850071](https://filfox.info/en/address/f02850071): 35.52%, [f02850015](https://filfox.info/en/address/f02850015): 36.65%, [f02850016](https://filfox.info/en/address/f02850016): 35.37%
Although it is the last time, hope you can keep the percentage  decreasing all the time. Signed.

**Comment by Chuangshi1** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedz2uvhvpskyqeortrtnpvflenhvdveuwnrkzaqso5wjsqfij2utu 
#### Address 
> f1j2yfkrh7dsglj54eurkp2ykjqqwgzlp5jyyufki
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1mdk7s2vntzm6hu35yuo6vjubtrpfnb2awhgvrri
#### Id
> ff2eed70-dea9-425f-bad4-261ad853434e
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedz2uvhvpskyqeortrtnpvflenhvdveuwnrkzaqso5wjsqfij2utu

**Comment by zcfil** [comment]
checker:manualTrigger

**Comment by mikezli** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedpoxkfqwpvz6l7molkbly27xukcq625jt466nabv73ten6payg24 
#### Address 
> f1j2yfkrh7dsglj54eurkp2ykjqqwgzlp5jyyufki
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1dnb3uz7sylxk6emti3ififcvu3nlufnnsjui6ea
#### Id
> ff2eed70-dea9-425f-bad4-261ad853434e
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedpoxkfqwpvz6l7molkbly27xukcq625jt466nabv73ten6payg24

**Comment by Sunnyiscoming** [comment]
SP List provided:
[{"providerID": "f02363308","City": " Tokyo", "Country": " JP", "SPOrg","Fly Tokyo"},
{"providerID": "f02850071","City": " Guangdong", "Country": " CN", "SPOrg","Datastone Shenzhen"},
{"providerID": "f02122388","City": " Guangdong", "Country": " CN", "SPOrg","nanhao Shenzhen"},
{"providerID": "f02829748","City": " Guangdong", "Country": " CN", "SPOrg","xingcircle Shenzhen"},
{"providerID": "f02830476","City": " Guangdong", "Country": " CN", "SPOrg","Xing Shenzhen"},
{"providerID": "f02829749","City": " Guangdong", "Country": " CN", "SPOrg","xingcircle Shenzhen"},
{"providerID": "f02182798","City": " Guangdong", "Country": " CN", "SPOrg","nanhao Shenzhen"},
{"providerID": "f02850016","City": " Central and Western", "Country": " HK", "SPOrg","Datastone Hong Kong"},
{"providerID": "f02830451","City": " Central and Western", "Country": " HK", "SPOrg","HK_Fil Hong Kong"},
{"providerID": "f02820089","City": " Central and Western", "Country": " HK", "SPOrg","Xingxing Hong Kong"},
{"providerID": "f02363306","City": " Singapore", "Country": " SG", "SPOrg","Seven Singapore"},
{"providerID": "f02829744","City": " Central and Western", "Country": " HK", "SPOrg","HK_Fil Hong Kong"},
{"providerID": "f02850067","City": " Guangdong", "Country": " CN", "SPOrg","Datastone Shenzhen"},
{"providerID": "f02807399","City": " Guangdong", "Country": " CN", "SPOrg","CNCTGNet Shenzhen"},
{"providerID": "f02363300","City": " Tokyo", "Country": " JP", "SPOrg","xingxing Tokyo"},
{"providerID": "f02078669","City": " California", "Country": " US", "SPOrg","HKblockchain Los Angeles"},
{"providerID": "f02182743","City": " Guangdong", "Country": " CN", "SPOrg","Air Shenzhen"},
{"providerID": "f02182802","City": " England", "Country": " GB", "SPOrg","Henry London"},
{"providerID": "f02850015","City": " Central and Western", "Country": " HK", "SPOrg","Datastone Hong Kong"},]

**Comment by jacktree7** [comment]
on going

**Comment by jacktree7** [comment]
checker:manualTrigger

**Comment by jacktree7** [comment]
checker:manualTrigger

**Comment by AlanGreaterheat** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceccc5cm4bt4ntogbvqixlezxzqhrjopp4bax2a2nwfsc5fbdc2sau 
#### Address 
> f1j2yfkrh7dsglj54eurkp2ykjqqwgzlp5jyyufki
#### Datacap Allocated
> 320.00TiB
#### Signer Address
> f1pnmzlxj7cfeo2v6oj5nco46hkg2l46wj7o4xxui
#### Id
> 526fa476-5619-4a42-be56-fc54f63955af
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceccc5cm4bt4ntogbvqixlezxzqhrjopp4bax2a2nwfsc5fbdc2sau
