### ISSUE TITLE
[DataCap Application]  - <F00tage>

### ISSUE THREAD

**Issue by Irenafootage** [filecoin-project/filecoin-plus-large-datasets#1199]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: F00tage
- Website / Social Media:https://twitter.com/F00tageofficial         
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):100TiB
- On-chain address for first allocation:f16efumcgpjamyhfrflxsu2brd7wrhniqwqssfpzq

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Footage was launched by a group of film-loving creators, independent filmmakers, Internet community members, and Hollywood professional production teams. Currently committed to gathering more video creators, independent filmmakers, and web3 practitioners who like movies. Together, we will explore the infinite possibilities of movies on Web3, jointly forge the new future of movies, and let more independent filmmakers be seen. 
```

What is the primary source of funding for this project?
```
own fund
```

What other projects/ecosystem stakeholders is this project associated with?
```
nope
```

## Use-case details

Describe the data being stored onto Filecoin
```
The dataset we plan to store on filecoin are some creative videos/films archive produced by video creators and independent filmmakers which can be and are supposed to be  shared with the public. Our goal is to let thousands of independent productions to shine through Web3 spirit and technology. Also, we will mint some NFT and launch it soon. 
```

Where was the data in this dataset sourced from?
```
self-produced videos/films archive by our independent film makers and vidoe creators
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://www.bilibili.com/video/BV1C44y1n7aq/?spm_id_from=333.999.0.0&vd_source=1948624b755bbb0ca852ec834bd44228               https://www.bilibili.com/video/BV1Ge4y1475S/?spm_id_from=333.1007.tianma.15-2-68.click&vd_source=1948624b755bbb0ca852ec834bd44228      
https://www.bilibili.com/video/BV1dV4y1u75N/?spm_id_from=333.999.0.0&vd_source=1948624b755bbb0ca852ec834bd44228  https://www.bilibili.com/video/BV1x64y1k7Bf/?spm_id_from=333.788.recommend_more_video.0&vd_source=1948624b755bbb0ca852ec834bd44228
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
yes
```

What is the expected retrieval frequency for this data?
```
Frequently since we provide public service
```

For how long do you plan to keep this dataset stored on Filecoin?
```
Expectedly 3 years to see how it goes
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
North America, China
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
online & offline
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We plan to select the SPs with high reputation and rich expeirence in vidoes or film industry
```

How will you be distributing deals across storage providers?
```
at least 2 copies per client, and then distribute quota and files fairly
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
yes
```

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 100TiB

**Client address**

>f16efumcgpjamyhfrflxsu2brd7wrhniqwqssfpzq

**Comment by raghavrmadya** [comment]
exact same issue exists - https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1089
