### ISSUE TITLE
[DataCap Application] NFT.Storage

### ISSUE THREAD

**Issue by jnthnvctr** [filecoin-project/filecoin-plus-large-datasets#12]
# Large Dataset Notary Application
 
## Core Information
- Organization Name: nft.storage, web3.storage - Protocol Labs
- Website / Social Media: nft.storage, web3.storage
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5PiB
- On-chain address for first allocation: f3watks6wyq5sakerofowyv7q4gwx4z6ukmfe2irh5zitspj6gpceudt3rrbvm5psofkcgoabev3s2mwtkcunq

_Please respond to the questions below in pargraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

## Project details

Share a brief history of your project and organization.
```
Protocol Labs is an open-source R&D lab. We build protocols, tools, and services to radically improve the internet. Our products serve thousands of organizations and millions of people. Protocols we’ve built to date include IPFS, Filecoin, libp2p, drand, IPLD and more. 

Our organization was founded back in 2014 - you can find more details about some of the important milestones along our history on our [website](https://protocol.ai/about/).  
```

What is the primary source of funding for this project?
```
We are developing a backend that will be used to serve two separate projects. 

The first project (nft.storage) is being funded by Protocol Labs to support the storage of what we view as a public good. Aside from the investment we’re making to operationalize the Filecoin deals, we’re also managing our own pin cluster to keep all NFT persisted on our side - and working with Pinata to store additional copies as well. 

The second project (web3.storage) is a project to enable early users of Filecoin to have a seamless user experience to develop early applications. The structure is heavily borrowed from NFT.Storage - where users can sign up via a website, download a client library, and get rolling using the service. The purpose of this project is to enable non-NFT use cases, and provide an early sandbox for developers to get started with testing (offering a capped limit of free storage, and with a verification process enabling higher limits). Protocol Labs intends to bear the IPFS costs required to deliver a strong user experience, while using Filecoin for persistence and storage. Over time, we'll be relying more heavily on Filecoin for retrievals vs. relying on IPFS (as we fully decentralize out the backend). 
```

What other projects/ecosystem stakeholders is this project associated with?
```
The NFT.storage project is being driven by Protocol Labs, but there are a number of large NFT platforms that intend to integrate this service as a component of their storage strategy (OpenSea, Rarible, Async Art, Palm) as well as platforms that intend to offer this as a free add-on service for their customers (Pinata, Fleek, Infura). 

The web3.storage project is also driven by Protocol Labs and is aimed to be one of the early starting points for developers trying to build in IPFS/Filecoin ecosystem. Primarily we believe hackathon participants will benefit the most early on (e.g. HackFS). 
```

## Use-case details

Describe the data being stored onto Filecoin
```
For NFT.Storage
We are offering free storage of all NFT on IPFS and Filecoin through https://nft.storage/. This can include various tokenized media that should be preserved long term on Filecoin and IPFS to ensure owners of NFTs can continually access the media they own. 

In the future, we might expand this to serve use cases broader than NFTs, but any changes to this plan will be added to this proposal for approval.

For Web3.Storage
We intend to offer free storage to any user with a Github or valid email signup. To start, we'll be offering a capped amount of free storage for all accounts - but enable users to request additional storage capacity (for free) by contacting us (so we can vet for abuse). We intend to mirror the same Terms of Service requirements for stored content as IPFS (and NFT.Storage). 
```

Where was the data in this dataset sourced from?
```

For NFT.Storage:
These NFTs are being sourced via three methods: 

1. Chain scraping (using theGraph to build an index of minted NFTs on the most popular blockchains)
2. Adoption of the NFT.storage library (to let developer directly integrate with our service)
3. Backend support with infrastructure providers (to enable pinning services to directly ship us content from their customers)

From these three methods, we both persist relevant CIDs in IPFS, and add the CIDs into a deal queue - which we package into 32GiB files with a self-describing index.

For web3.storage: 
These are files and requests we are pulling from early hackathon participants, and other early adopters of IPFS and Filecoin. We imagine this will likely end up being use cases that lean towards larger data volumes (as we are architecting our processes to make storing sizable chunks of data seamless) - but believe this service will be useful for any dApp developer trying to leverage decentralized storage for their use case. Equally, we believe this will become a friendly pathway for web2 developers to dip their toes into the IPFS/Filecoin ecosystems. 
```

Can you share a sample of what is in the dataset? A link to a file, an image, a table, etc., are good examples of this. 
```
For NFT.Storage
This platform serves all different kinds of media, including images, files, and videos that have been tokenized as NFTs. These are typically created by an artist, minted as NFTs, and then can be transacted. When uploaded to Filecoin, they are still owned by the individual that last purchased the token, but are accessible to anyone. 

Here are some sample CIDs of NFTs that have been stored via nft.storage: 
- https://ipfs.io/ipfs/bafybeid5jpdqzlb4tqsd6peoa7qstoxat3ovsg62wutyp4gnzqbqsggfsq
- https://ipfs.io/ipfs/bafybeihity6bx24npzvvkzopjbat25ekefjwmnshe7rvldy72dxngzf644
- https://ipfs.io/ipfs/bafybeicvcevx3ktiqjsfwnjguu4lnzejlhgb35brayuod5xdtn7demfdhe

For Web.Storage - we do not have any examples yet. 
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
For NFT.Storage
All of this data is public - NFT.storage will support a “status” API that will give both pin status (to show if the content is in IPFS) as well as the relevant deal information - such that anyone can retrieve the relevant data from a miner and store their own local copy. 

For Web3.Storage
We expect there may be a mix here - some developers will be building with public data, but its possible some users may want (for their own reasons) to encrypt their data. Given all of this content is going to be pinned on IPFS, it content will be retrievable. There will be public APIs that will allow anyone to query for a speciifc CID to get back status on the content being pinned, as well as the miners who have been contracted to store those deals.For users who request larger allocations of storage capacity, we have the ability to vet teams for abuse.

I think this is an area where we're open to feedback - our aim is to give early developers as much flexibility to use these protocols as they see fit, and given the miner selection process is decoupled from the client storage (i.e. Clients cannot directly choose which miner to store with) typical economic concerns of self-dealing are mitigated against.


```

What is the expected retrieval frequency for this data?
```
To start, we intend to persist all this data in IPFS - so the retrieval frequency out of Filecoin we expect to be minimal. Over time, our intent is to lean more heavily on fast retrieval out of Filecoin and cache content intelligently in IPFS. 

For NFT.Storage specifically: 
Part of our intended goals is to also enable teams who are not directly storing content via NFT.storage to request data out of this service, or to configure it as a fallback in the event an NFTs URL does not resolve. 
```

For how long do you plan to keep this dataset stored on Filecoin? Will this be a permanent archival or a one-time storage deal?
```
We intend to store this content permanently on Filecoin - and will be actively monitoring to ensure that the requisite number of copies remain online and that deals are appropriately renewed. 
```

## DataCap allocation plan

In which geographies do you plan on making storage deals?
```
We intend to make deals with our allocation with MinerX fellows from around the world. These deals will be split across ~30 miners - in regions spanning the globe (US, Europe, parts of Asia). 
```

What is your expected data onboarding rate? How many deals can you make in a day, in a week? How much DataCap do you plan on using per day, per week?
```
For NFT.Storage
In the first few months, we will be running our chain scraping process - which will require creating a backfill for all NFTs that have been minted to date. As that process executes, we imagine the rate of storage will be significantly higher (perhaps on the order of terabytes a day). We do not have concrete estimates of the total number of NFTs that we will be storing, but our estimate is 600TiB for Ethereum looking back historically. We expect to have a more refined forward looking estimate of the rate of increase as we see steady state adoption in the coming weeks. 

Our current estimate is that we’ll require 5TiB per week of DataCap to store newly minted NFTs from Ethereum with replication. From the 5PiB requested above, we expect 1PiB to be dedicated to supporting NFT.Storage

For Web3.Storage
We expect we're going to see a rapid number of sign ups during hackathons and pushes where there might be a large number of new developers - but we expect these users to have a low average usage - assuming the average storage lifetime amt is ~5GiB total. 

Separately, our estimates are that there will likely be a handful of power users (e.g. teams like Voodfy, we've ball parked this at 10% of our user base) who will generate large volumes of data - on the order of 10s of GiB a week. 

A rough estimate would be (8k total users by EOY  * 0.9 *5 GiB) + (8k total users by EOY* 0.1 *50GiB*4 weeks*6 months) = Total datacap used this year = (roughly) 1PiB

For a minimum of 5x replication, we'd need 5PiB.

These are aggressive goals (and walking throuhg the math is likely an over assumption), but given the allocation mechanism it would be ideal to have this amt pre-approved - and notaries to rate limit accordingly. 

Totally the request is: 
1PiB for NFT.Storage
5PiB for Web3.Storage
-> 6PiB total. -> requesting 5PiB as it is the max. 

```

How will you be distributing your data to miners? Is there an offline data transfer process?
```
We’ll be doing primarily online data transfers with miners - though we’ll be running a batching script to only trigger deals once we have full sectors. Miners are being sourced from the MinerX program - and will only receive deals if they are found to be in good standing with our client. Deals will be allocated in a round robin strategy to ensure equal distribution - with a primary focus on enabling geographic diversity per deal (redundant storage across locations). 

Note our broker backend is being used for a number of other services (including Textile, Estuary, and Discover)
```

How do you plan on choosing the miners with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
As a component of our storage strategy, we’ll be requesting fast / free retrieval which will be required in order for miners to continue to receive deals from our Client. 
```

How will you be distributing data and DataCap across miners storing data?
```
We will be rotating through the MinerX fellows to ensure roughly equal distribution to Miners who offer high quality services to our client. We intend to fully allocate DataCap per 32GiB deal we strike with a Miner. 
```

**Comment by cryptowhizzard** [comment]
Sounds good. Happy to be notary for this as soon as we are ready to go.

**Comment by jnthnvctr** [comment]
@cryptowhizzard  - please see the updates to the above issue! Note we're using hte same backend for two projects, so rather than file two different issues I've added detail on both above!

**Comment by neogeweb3** [comment]
Count me in!

**Comment by andrewxhill** [comment]
+1

**Comment by jnthnvctr** [comment]
@andrewxhill  and @neogeweb3  please note that I totally forgot about the replication factor - I've updated the issue above accordingly

**Comment by s0nik42** [comment]
Good for me too

**Comment by Reiers** [comment]
**I'm in as well +1**

**Comment by ozhtdong** [comment]
Count me in!

**Comment by steven004** [comment]
Great. Count me in.  +1

And, I'm looking forward to some methods which can also be applied to other programs to ensure that the datacap is not abused.

**Comment by Broz221** [comment]
Would like to be the notary of this project.

**Comment by rayshitou** [comment]
Nice. I'm in too

**Comment by Fenbushi-Filecoin** [comment]
I'm in +1

**Comment by swatchliu** [comment]
I'm in.

**Comment by Fatman13** [comment]
> Note our broker backend is being used for a number of other services (including Textile, Estuary, and Discover)
Is this broker backend open sourced by any chance?

**Comment by ribasushi** [comment]
@Fatman13 it is open source as virtually everything we do. However things are still shaping up: I could point you to a repository, but it is 100% unstable and being force-pushed to, so I wouldn't look just yet ( if really curious - simply look at my recent commit history 😉 )

The aggregator routine however (the one I used in [partial retrieval](https://github.com/filecoin-project/lotus/pull/6393#issue-661783290) demos ) is ready to roll: https://pkg.go.dev/github.com/filecoin-project/go-dagaggregator-unixfs

**Comment by dkkapur** [comment]
Hi folks - great to see lots of notary support for this one! Moving forward with the first 7 notaries that responded. 

1. @cryptowhizzard - f1krmypm4uoxxf3g7okrwtrahlmpcph3y7rbqqgfa
2. @neogeweb3 - f13k5zr6ovc2gjmg3lvd43ladbydhovpylcvbflpa
3. @andrewxhill - f2kb4izxsxu2jyyslzwmv2sfbrgpld56efedgru5i
4. @s0nik42 - f1wxhnytjmklj2czezaqcfl7eb4nkgmaxysnegwii
5. @Reiers - f1oz43ckvmtxmmsfzqm6bpnemqlavz4ifyl524chq
6. @ozhtdong - f1lwpw2bcv66pla3lpkcuzquw37pbx7ur4m6zvq2a
7. @steven004 - f1qoxqy3npwcvoqy7gpstm65lejcy7pkd3hqqekna

**Comment by dkkapur** [comment]
## Multisig Notary requested
 
#### Notary addresses
> f1krmypm4uoxxf3g7okrwtrahlmpcph3y7rbqqgfa
> f13k5zr6ovc2gjmg3lvd43ladbydhovpylcvbflpa
> f2kb4izxsxu2jyyslzwmv2sfbrgpld56efedgru5i
> f1wxhnytjmklj2czezaqcfl7eb4nkgmaxysnegwii
> f1oz43ckvmtxmmsfzqm6bpnemqlavz4ifyl524chq
> f1lwpw2bcv66pla3lpkcuzquw37pbx7ur4m6zvq2a
> f1qoxqy3npwcvoqy7gpstm65lejcy7pkd3hqqekna

#### Total DataCap requested
> 5PiB

#### Expected weekly DataCap usage rate
> 5TiB

**Comment by dkkapur** [comment]
https://github.com/filecoin-project/notary-governance/issues/200 - this Notary is ready to begin providing DataCap to the client (represented by @jnthnvctr). Next steps are:

- we need to confirm a lead Notary - @cryptowhizzard @neogeweb3 @andrewxhill @Reiers @s0nik42 @ozhtdong @steven004, please let us know if one of you would be willing to take this on. 
- @jnthnvctr whenever you are ready - please share a message here requesting your first DataCap allocation and the address to which you would like it received. The first DataCap request can be up to 2.5TiB for this application.

Based on this, the lead notary will paste in the following message as a comment in this Issue:

## DataCap Allocation requested
#### Multisig Notary address
> f01105790
#### Client address
> <addr2>
#### DataCap allocation requested
> <XTiB>

This will prompt the bot to show the request to the other Notaries on the multisig in the Fil+ Registry App. We need 4 Notaries to sign the request for it to go through.

**Comment by dkkapur** [comment]
## DataCap Allocation requested
#### Multisig Notary address
> f01105790
#### Client address
> f3watks6wyq5sakerofowyv7q4gwx4z6ukmfe2irh5zitspj6gpceudt3rrbvm5psofkcgoabev3s2mwtkcunq
#### DataCap allocation requested
> 2.5TiB

**Comment by neogeweb3** [comment]
I can take the lead on this.

**Comment by dkkapur** [comment]
Thank you @neogeweb3!

**Comment by neogeweb3** [comment]
Hey @jnthnvctr, when you are ready, could you confirm the address to which you'd like it received and the DataCap request amount. I am ready to kick off the 1st request.

**Comment by ribasushi** [comment]
@neogeweb3 above address is confirmed!
`f3watks6wyq5sakerofowyv7q4gwx4z6ukmfe2irh5zitspj6gpceudt3rrbvm5psofkcgoabev3s2mwtkcunq`

**Comment by neogeweb3** [comment]
> @neogeweb3 above address is confirmed!
> `f3watks6wyq5sakerofowyv7q4gwx4z6ukmfe2irh5zitspj6gpceudt3rrbvm5psofkcgoabev3s2mwtkcunq`

Thanks, @ribasushi, just want to confirm that you are requesting the full initial max of 2.5TiB as noted by @dkkapur?

**Comment by ribasushi** [comment]
@neogeweb3 yes all 2.5TiB please. This will drive both nft.storage and web3.storage ( they aggregate together via [this lib](https://pkg.go.dev/github.com/filecoin-project/go-dagaggregator-unixfs#Aggregate) ), so yeah - we will take all we can.

**Comment by neogeweb3** [comment]
## DataCap Allocation requested
#### Multisig Notary address
> f01105790
#### Client address
> f3watks6wyq5sakerofowyv7q4gwx4z6ukmfe2irh5zitspj6gpceudt3rrbvm5psofkcgoabev3s2mwtkcunq
#### DataCap allocation requested
> 2.5TiB

**Comment by dkkapur** [comment]
Just added the label manually and I now see it in the app @neogeweb3. Let me know if you can see it / can sign it?

**Comment by neogeweb3** [comment]
Thanks, @dkkapur. Now I can see it in the app but cannot sign it. 
The error is "Verification failed: Data is invalid: Unexpected method"
The console log shows: 

Inter-Regular.woff:1 Failed to load resource: the server responded with a status of 404 ()
Inter-SemiBold.woff:1 Failed to load resource: the server responded with a status of 404 ()
plus.fil.org/:1 Failed to load resource: the server responded with a status of 404 ()

Cannot convert to key Error: failed to get account actor state for f01105790: unknown actor code bafkqadtgnfwc6njpnv2wy5djonuwo
    at e.<anonymous> (index.js:91)
    at l (runtime.js:63)
    at Generator._invoke (runtime.js:294)
    at Generator.next (runtime.js:119)
    at r (asyncToGenerator.js:3)
    at c (asyncToGenerator.js:25)

Let me know if that would help @ialberquilla Thanks.

**Comment by ribasushi** [comment]
> `... unknown actor code bafkqadtgnfwc6njpnv2wy5djonuwo`

This means the app is built against an older version of lotus/zondax-tools :( From before the network upgrade a month ago. @ialberquilla @dkkapur reach me on slack if you need further help with that.

**Comment by neogeweb3** [comment]
Hey folks, it turns out the expert mode was automatically turned off when I updated my Ledger firmware to 2.0.0. After I re-enabled the expert mode, this request was successfully proposed without any problems. 

I apologize for the inconvenience, and thank you for the help! @dkkapur @ialberquilla

**Comment by cryptowhizzard** [comment]
When i am trying to approve i get :

Verification failed: fatal error calling 'Filecoin.GasEstimateMessageGas': panic in rpc method 'Filecoin.GasEstimateMessageGas': cannot marshal undefined address

**Comment by steven004** [comment]
Approved. 

Message sent:
[bafy2bzacec6lzlxbseqm4fxzof2h2np77xb6ktkhr4sruxvev3vwwmvzs4lmk](https://filscan.io/tipset/message-detail?cid=bafy2bzacec6lzlxbseqm4fxzof2h2np77xb6ktkhr4sruxvev3vwwmvzs4lmk)

**Comment by dkkapur** [comment]
@cryptowhizzard just updated the instructions here: https://github.com/filecoin-project/filecoin-plus-large-datasets/blob/main/README.md#granting-datacap-to-the-client; this flow should work hopefully!

**Comment by cryptowhizzard** [comment]
@dkkapur thanks. That helped!

Request approved.

**Comment by neogeweb3** [comment]
We are still waiting for another 2 notaries to approve this request.

**Comment by galen-mcandrew** [comment]
Seeing the proposal and 2 approvals. 

@s0nik42, @Reiers, @ozhtdong : Could we get some approval messages through the [Fil+ App ](https://plus.fil.org/app)for the pending DataCap allocation?

**Comment by dkkapur** [comment]
This looks like it went through thanks to a fourth signature today. @jnthnvctr @ribasushi you should have your first allocation of 2.5TiB ready to go

**Comment by neogeweb3** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb4lau3sjvrxwxyekl6pij6p7ap3vtuyjzluglced6axcskfdbon2 
#### Address 
> f3watks6wyq5sakerofowyv7q4gwx4z6ukmfe2irh5zitspj6gpceudt3rrbvm5psofkcgoabev3s2mwtkcunq
#### Datacap Allocated
> 2748779069440
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb4lau3sjvrxwxyekl6pij6p7ap3vtuyjzluglced6axcskfdbon2

**Comment by galen-mcandrew** [comment]
Hi @neogeweb3 , checking the dashboard and the glif site, looks like this address (f3watks6wyq5sakerofowyv7q4gwx4z6ukmfe2irh5zitspj6gpceudt3rrbvm5psofkcgoabev3s2mwtkcunq) still has 2.5 TiB of DataCap, and no verified deals yet. Looks like this may be a duplicate approval?

**Comment by neogeweb3** [comment]
Hey @galen-mcandrew, good point. I did that on purpose because the current LDN process time is quite long (more than one week) to collect all four signatures. Considering the expected weekly DataCap usage rate of this application is 5TiB, I proposed again right after the initial allocation. But given NFT.Storage hasn't used any DataCap, I would wait until @ribasushi or @jnthnvctr to notify the project progress.

**Comment by Reiers** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecspolxmjeeu5cxm4qmq6aov2qttuezrt3larmq7zb7duzebpmesi 
#### Address 
> f3watks6wyq5sakerofowyv7q4gwx4z6ukmfe2irh5zitspj6gpceudt3rrbvm5psofkcgoabev3s2mwtkcunq
#### Datacap Allocated
> 2748779069440
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecspolxmjeeu5cxm4qmq6aov2qttuezrt3larmq7zb7duzebpmesi

**Comment by galen-mcandrew** [comment]
@ribasushi & @jnthnvctr , seeing 2.5 TiB of DataCap successfully allocated to address: f3watks6wyq5sakerofowyv7q4gwx4z6ukmfe2irh5zitspj6gpceudt3rrbvm5psofkcgoabev3s2mwtkcunq

It looks like the notaries have also started proposing messages for your second allocation but we won't be able to approve that until more is sealed, so let us know if there is an issue on your side with the first DataCap allocation.

**Comment by neogeweb3** [comment]
wondering if this one is still moving

**Comment by ribasushi** [comment]
@neogeweb3 apologies, I somehow got unsubscribed from this issue.
We ran into difficulties with dealmaking and have leaned heavily on [BidBot](https://github.com/textileio/bidbot). It currently does not support delegated signing, so I can't draw on the granted datacap just yet as there is no robust mechanism to remotely sign the proposal payloads generated by bidbot. We seem to be in the latest stage of getting this running however, I will update the issue once things begin to flow!

cc @jnthnvctr

**Comment by s0nik42** [comment]
Shall we move to a bigger allocation next time ? 2.5 seems small compared to the total allocation.

**Comment by s0nik42** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacea27nvou7fgm5dg6w5nyq2y3pv3m432cezg7uk4dr3o4dgxbn7a6i 
#### Address 
> f3watks6wyq5sakerofowyv7q4gwx4z6ukmfe2irh5zitspj6gpceudt3rrbvm5psofkcgoabev3s2mwtkcunq
#### Datacap Allocated
> 2748779069440
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacea27nvou7fgm5dg6w5nyq2y3pv3m432cezg7uk4dr3o4dgxbn7a6i

**Comment by ribasushi** [comment]
@s0nik42 almost certainly yes, we'll figure it out once we get our datacap to flow. At present as-tuned we would eat about 1TiB of datacap/day.

**Comment by s0nik42** [comment]
@ribasushi I'm keeping my ledger plugged in then :p

**Comment by neogeweb3** [comment]
@ribasushi no worries, let me know if there is anything I could help with along the process.

**Comment by s0nik42** [comment]
What is the status of this request ? is it still not fully approved ?

**Comment by galen-mcandrew** [comment]
@s0nik42 , to my knowledge this second allocation has still not met threshold of 4. That said, the team is still working through some tech hurdles so they have not actually started any deals with the first allocation.

Right now, seeing 3 approvals from Neo, Reiers, and Julien. I think it would be good to go ahead and get a fourth signature, so that it clears the second allocation before we roll all the LDN's to new multisigs.

@cryptowhizzard @andrewxhill @ozhtdong @steven004 could we get one more approval here?

**Comment by steven004** [comment]
Approved.

https://filscan.io/tipset/message-detail?cid=bafy2bzacebjt2w6plpjra746wjvlbel23ya2f64jsgbnlzuo2vi3h6qrmd3e4

**Comment by cryptowhizzard** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedy2ezgiiuh4qbujlpuuvwpuznxk2xaerkoijik6t5ktdpkjwa5t6 
#### Address 
> f3watks6wyq5sakerofowyv7q4gwx4z6ukmfe2irh5zitspj6gpceudt3rrbvm5psofkcgoabev3s2mwtkcunq
#### Datacap Allocated
> 2748779069440
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedy2ezgiiuh4qbujlpuuvwpuznxk2xaerkoijik6t5ktdpkjwa5t6

**Comment by galen-mcandrew** [comment]
rolling to https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/49
