### ISSUE TITLE
[DataCap Application] MeiYa

### ISSUE THREAD

**Issue by marik336514** [filecoin-project/filecoin-plus-large-datasets#120]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name:  Singapore Mei Ya Technology PTE.LTD.  
- Website / Social Media: www.meiyauniverse.com
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100TiB
- On-chain address for first allocation: f3vn67d2ncju2iikkwp56gxkzy6fbgwa6x2rqgp5ud5nwashsvbfnqc7vcn4n24sjpfuq2qoksuw55hbvt7cgq

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.

  Singapore Meiya Technology Co., Ltd. is a high-tech enterprise applying cloud computing, big data and artificial intelligence technology to realize data asset operation. Our business covers many industries and is committed to the construction of big data industrial ecological chain. We use advanced technology to realize the whole life cycle management of data from collection, processing to application. Excellent solutions have been successfully applied to the Internet, finance, government, intelligent manufacturing and other fields.
  Meiya technology uses the existing new information infrastructure platform to provide shared resources for the establishment of smart city security management system for mobile communication, traffic monitoring, urban security video monitoring, meteorological and environmental protection monitoring (PM2.5), water quality detection, fire monitoring and early warning, so as to lay a foundation for the sharing of smart city management platform.
  Meiya technology is committed to building the ecosystem of data and application based on Internet 3 (Web3.0), and building EOT data side chain based on EOS, providing data center and data application platform for Internet and big data industry transformation from Internet plus to Internet plus. This will be a scalable, low latency, high interaction, and scalable security chain domain guardrail distributed network platform. Realize the scene display of various objects and data under the jurisdiction of government departments.

What is the primary source of funding for this project?
Our own funding.

What other projects/ecosystem stakeholders is this project associated with?
There's no other projects/ecosystem stakeholders associated with.

## Use-case details

Describe the data being stored onto Filecoin
  Dynamic loading of a variety of global general map data, special map data such as police PGIS and heaven and earth map, high-precision elevation data, various vector geographic element data (such as roads, buildings, administrative divisions and ocean boundaries), tilt photography data, UAV aerial photography data, fine building structure data.

Where was the data in this dataset sourced from?
The data comes from our front of the devices and front platform environment.

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
(https://pan.baidu.com/s/1EZklQA1ygVgvZ064nDoFmA)    Code：f8wd
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
Yes, I confirm that this is a public dataset that can be retrieved by anyone on the Network.

What is the expected retrieval frequency for this data?
It's about once a week.

For how long do you plan to keep this dataset stored on Filecoin?
At least two years.

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
Deal with Singapore and China.

How will you be distributing your data to storage providers? Is there an offline data transfer process?
We will choose online and offline transfer, it's depends on the network speed.

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
We prefer to choose the storage providers that who are stabilize and close to us.

How will you be distributing deals across storage providers?
Equal distribution.

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
We have the available resources if we get the datacap. We accept the support from the community if you can.

**Comment by galen-mcandrew** [comment]
## Multisig Notary requested
#### Total DataCap requested 
> 5PiB
#### Expected weekly DataCap usage rate 
> 100TiB

**Comment by MegTei** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceam73obqra7qmpvpdhxse5tt5qq2jnmgevegqf7u7jdvja4wk4ebs 
#### Address 
> f3vn67d2ncju2iikkwp56gxkzy6fbgwa6x2rqgp5ud5nwashsvbfnqc7vcn4n24sjpfuq2qoksuw55hbvt7cgq
#### Datacap Allocated
> 50TiB
#### Signer Address
> f1ystxl2ootvpirpa7ebgwl7vlhwkbx2r4zjxwe5i
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceam73obqra7qmpvpdhxse5tt5qq2jnmgevegqf7u7jdvja4wk4ebs

**Comment by flyworker** [comment]
I think notary should check the application before apporve
![image](https://user-images.githubusercontent.com/8363795/150722236-877622a3-0460-4305-bbf5-a4a899d4bbc6.png)

and the website is really low quality.

**Comment by MegTei** [comment]
@flyworker Yes in doing Due diligence on any app I check their credentials.  This client website looked legitimate to me 
![image](https://user-images.githubusercontent.com/80305349/150733046-0fe4eac1-299a-4fd1-a884-6333a9ea320f.png)

**Comment by marik336514** [comment]
@flyworker 链接：https://pan.baidu.com/s/1EZklQA1ygVgvZ064nDoFmA 
提取码：f8wd
I update the link

**Comment by marik336514** [comment]
We are still waiting for the review result of the notary. What can we do to speed up the process?
![055607EB](https://user-images.githubusercontent.com/94332490/153529295-992afef4-b77e-4873-8cfe-0727c1cbf76c.png)

**Comment by UnionLabs2020** [comment]
No official contact way and no company address~

**Comment by marik336514** [comment]
The address and contact information are at the bottom of our official website.

**Comment by marik336514** [comment]
> No official contact way and no company address~

The address and contact information are at the bottom of our official website.

**Comment by UnionLabs2020** [comment]
Thanks for your reply. I can hardly find any valuable content, except a lot of blanks. How could I support you？

**Comment by marik336514** [comment]
@UnionLabs2020 
Our company's main business is the deployment of video monitoring system and the cloud storage service of video data generated by monitoring. We hope to store some surveillance video data (backup data specified in the service contract) in the filecoin network, which can reduce our operating costs.

**Comment by newwebgroup** [comment]
@marik336514 
Hi  man, can you send some more data samples?
The previous link seems to have expired.



<img width="944" alt="image" src="https://user-images.githubusercontent.com/100118145/180683040-84140a91-5f42-4055-aecf-bd64cc21163e.png">

**Comment by psh0691** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaxaquw5b6ik43lbgduoyngvft25h66arfu3tq7uluzwja7pubzuq 
#### Address 
> f3vn67d2ncju2iikkwp56gxkzy6fbgwa6x2rqgp5ud5nwashsvbfnqc7vcn4n24sjpfuq2qoksuw55hbvt7cgq
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1qdko4jg25vo35qmyvcrw4ak4fmuu3f5rif2kc7i
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaxaquw5b6ik43lbgduoyngvft25h66arfu3tq7uluzwja7pubzuq

**Comment by filplus-checker** [comment]
## DataCap and CID Checker Report[^1]
 - Organization: `Glif auto verified`
 - Client: `f3vn67d2ncju2iikkwp56gxkzy6fbgwa6x2rqgp5ud5nwashsvbfnqc7vcn4n24sjpfuq2qoksuw55hbvt7cgq`
### Storage Provider Distribution
The below table shows the distribution of storage providers that have stored data for this client.

If this is the first time a provider takes verified deal, it will be marked as `new`.

For most of the datacap application, below restrictions should apply.
 - Storage provider should not exceed 25% of total datacap.
 - Storage provider should not be storing duplicate data for more than 20%.
 - Storage provider should have published its public IP address.
 - All storage providers should be located in different regions.

⚠️ [f0500003](https://filfox.info/en/address/f0500003) has sealed 100.00% of total datacap.

⚠️ [f0500003](https://filfox.info/en/address/f0500003) has unknown IP location.

⚠️ All storage providers are located in the same region.

| Provider                                                  | Location | Total Deals Sealed | Percentage | Unique Data | Duplicate Deals |
| :-------------------------------------------------------- | -------: | -----------------: | ---------: | ----------: | --------------: |
| [f0500003](https://filfox.info/en/address/f0500003)`new`  |  Unknown |          32.00 GiB |    100.00% |   32.00 GiB |           0.00% |

![Provider Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/120/1671092542631.png)
### Deal Data Replication
The below table shows how each many unique data are replicated across storage providers.
- No more than 25% of unique data are stored with less than 4 providers.

⚠️ 100.00% of deals are for data replicated across less than 4 storage providers.

| Unique Data Size | Total Deals Made | Number of Providers | Deal Percentage |
| ---------------: | ---------------: | ------------------: | --------------: |
|        32.00 GiB |        32.00 GiB |                   1 |         100.00% |

![Replication Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/120/1671092543346.png)
### Deal Data Shared with other Clients
The below table shows how many unique data are shared with other clients.
Usually different applications owns different data and should not resolve to the same CID.

✔️ No CID sharing has been observed.

[^1]: To manually trigger this report, add a comment with text `checker:manualTrigger`
