### ISSUE TITLE
[DataCap Allocation] - Landsat 9 replications

### ISSUE THREAD

**Issue by TaylorOshan** [filecoin-project/filecoin-plus-large-datasets#1200]
---
name: Large Dataset Notary application
about: Clients should use this application form to request a DataCap allocation via a LDN for a dataset
title: "Landsat 9 replications"
labels: 'application, Phase: Diligence'
assignees: ''

---
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: The EASIER Data Initiative
- Website / Social Media: easierdata.org
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 2PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 500TiB
- On-chain address for first allocation: f1uwzfw6hghqf6js4773p62onzvqnupcqdxbkhhvq
- Region: North America

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
The EASIER Data initiative kicked off late this summer and is a two year project in collaboration with the Filecoin Foundation for the Decentralized Web to build pipelines for storing and extracting geospatial data on Filecoin and IPFS. These pipelines will be prototyped and demonstrated using one year of Landsat 9 satellite data, which is estimated at about 500TB per replication. We originally opened your request here, but didn't realize that we should request the total amount for all of the replications and so we only requested 500TB instead of 2.5PB for replications.
```

What is the primary source of funding for this project?
```
Filecoin Foundation for the Decentralized Web
```

What other projects/ecosystem stakeholders is this project associated with?
```
University of Maryland, Filecoin Foundation for the Decentralized Web, Piknik, Atlas, Filecoin Green
```

## Use-case details

Describe the data being stored onto Filecoin
```
One year of landsat 9 satellite images.
```

Where was the data in this dataset sourced from?
```
Landsat 9 is a joint mission between NASA and USGS
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://www.usgs.gov/landsat-missions/landsat-9
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
The data are supported by open missions and are meant to be public
```

What is the expected retrieval frequency for this data?
```
Initially, the data will likely only be retrieved infrequently by the project team, but the hope is that with the development of the pipelines during the duration of the project, the platform will increase the number of users and the retrieval frequency.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
3-5 years
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
We plan to have one or two copies stored in North America and several additional copies stored in other regions around the globe as suggested by partner storage providers.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
We will be egress in the data from our servers to Piknik servers using S3 and Piknik has agreed to help distribute replication copies to additional storage providers.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We will be working with Piknic and the big data exchange so identify additional storage providers
```

How will you be distributing deals across storage providers?
```
We will store several copies with Piknik and distribute the remaining copies with additional storage providers
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
We anticipate being ready to start making storage deals within a week or two.
```

**Comment by TaylorOshan** [comment]
This 2PiBbrequest is associated with this earlier 500Tib request #995, which should have been 2.5PiB to account for replications.

**Comment by dannyob** [comment]
@galen-mcandrew, @Kevin-FF-USA and @raghavrmadya is there something that needs to be done to move this along? I've been in conversation with the applications and it looks good to me.

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 2PiB

**Expected weekly DataCap usage rate**

> 500TiB

**Client address**

> f1uwzfw6hghqf6js4773p62onzvqnupcqdxbkhhvq

**Comment by GaryGJG** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacea3ul77zjilcacoh6ltm6pbvsojj2apcwj5wjoz2d7zskmbsixxeu 
#### Address 
> f1uwzfw6hghqf6js4773p62onzvqnupcqdxbkhhvq
#### Datacap Allocated
> 102.39TiB
#### Signer Address
> f1zffqhxwq2rrg7rtot6lmkl6hb2xyrrseawprzsq
#### Id
> 110dba04-3a23-4fe4-a93d-60c40f9bd665
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacea3ul77zjilcacoh6ltm6pbvsojj2apcwj5wjoz2d7zskmbsixxeu

**Comment by dannyob** [comment]
Adding my approval to this.

**Comment by dannyob** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebelhalfv6srnwmagfvi6jaccuhlrnhc3f2hwbjhxokxjti6vnini 
#### Address 
> f1uwzfw6hghqf6js4773p62onzvqnupcqdxbkhhvq
#### Datacap Allocated
> 102.39TiB
#### Signer Address
> f1k6wwevxvp466ybil7y2scqlhtnrz5atjkkyvm4a
#### Id
> 110dba04-3a23-4fe4-a93d-60c40f9bd665
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebelhalfv6srnwmagfvi6jaccuhlrnhc3f2hwbjhxokxjti6vnini

**Comment by cryptowhizzard** [comment]
Hi @GaryGJG 

Can you fill out [this form](https://form.jotform.com/230337462961356) to provide us with the necessary information so i can move on and approve you for the next tranche of datacap?

**Comment by TaylorOshan** [comment]
@cryptowhizzard was that message intended for me? We have a game this year in process for this data set and should now be consuming the datacap.

**Comment by cryptowhizzard** [comment]
> @cryptowhizzard was that message intended for me? We have a game this year in process for this data set and should now be consuming the datacap.

Sorry man ... you can ignore this, my bad.

**Comment by Sunnyiscoming** [comment]
checker:manualTrigger

**Comment by Sunnyiscoming** [comment]
For most of the datacap application, below restrictions should apply.

Storage provider should not exceed 25% of total datacap.
Storage provider should not be storing duplicate data for more than 20%.
Storage provider should have published its public IP address.
All storage providers should be located in different regions.

**Comment by jamerduhgamer** [comment]
Hello all, providing this comment for full transparency here. PiKNiK started sealing first to get past the smaller datacap 50 and 100 TiB allocations.

Another replica will be going to Australia but the SP is stilling setting up to take on the data.

2 other copies have been posted to the Big Data Exchange for an SP in Asia excluding GCN and an SP in Europe so we will have more SPs onboarded once those auctions are won along with more geographic distribution as well.

**Comment by TaylorOshan** [comment]
Just wanted to loop in @dannyob for situational awareness as this moves forward. Would the next status updates/tranche of datacap be granted once we continue dealmaking or do we need to wait for that to happen before we can start dealmaking again with additional SPs and finish the first copy with Piknik?

**Comment by dannyob** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedzphtrlog6q6txhqsf5fqre6l2yll4zsidwkoocopn44xg4nm2ee 
#### Address 
> f1uwzfw6hghqf6js4773p62onzvqnupcqdxbkhhvq
#### Datacap Allocated
> 204.79TiB
#### Signer Address
> f1k6wwevxvp466ybil7y2scqlhtnrz5atjkkyvm4a
#### Id
> 671ce160-3a55-458d-9607-f987e713cf2c
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedzphtrlog6q6txhqsf5fqre6l2yll4zsidwkoocopn44xg4nm2ee

**Comment by dannyob** [comment]
Hi @TaylorOshan -  I've started another allocation request on the presumption that you'll be using this datacap with other SPs, but you'll need to encourage another notary to trust you on this. It's best to start out distributing to multiple SPs, just because notaries are less likely to sign off if it looks like a single SP is getting all the rewards.

**Comment by dannyob** [comment]
checker:manualTrigger

**Comment by TaylorOshan** [comment]
Could we please keep this application open? @jamerduhgamer was working with partner SPs to get additional copies stored and use the next tranche of datacap allocated by @dannyob more diversely.

**Comment by TaylorOshan** [comment]
Please keep open as we are trying to troubleshoot an issue.

**Comment by spaceT9** [comment]
checker:manualTrigger

**Comment by SethDocherty** [comment]
checker:manualTrigger

**Comment by jamerduhgamer** [comment]
Hi @SethDocherty, I see you checking this LDN but we have an updated one we are using here - https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/2163

**Comment by jamerduhgamer** [comment]
Oh I just saw that you have also checked that one already. Never mind :)
