### ISSUE TITLE
[DataCap Application] <CS Render> - <Render Data IPFS Project>

### ISSUE THREAD

**Issue by shliming** [filecoin-project/filecoin-plus-large-datasets#1201]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: CS Render
- Website / Social Media: http://www.csrender.com/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 4PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 400TiB
- On-chain address for first allocation:f1k4ljwusrgqbeifkily2noykutbpi3sf77wmk5pq

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
1. project: Render Data IPFS Project is our new project on that we will storage a lot of render data (such as render pictures or render videos) in Filecoin net.The render data is in our disk now，and it costs us a lot of storage space and disk.We want to storage the data to Filecoin net,we believe our Filecoin net is very security ,very efficient and very cheap.

2. organization: CS Render is a rendering service cloud platform that is developed independently. We are well known in China in 3D production, digital media, architectural design, film special effects, animation games, advertising and other industries.We are interested in filecoin, and we've been paying attention for years.In 2020, we invested in a sealing node.Now we want to seal our data to filecoin net.

What is the primary source of funding for this project?
Our own internal funds

What other projects/ecosystem stakeholders is this project associated with?
None

## Use-case details

Describe the data being stored onto Filecoin
Our render data is from 3D production, digital media, architectural design, film special effects, animation games, advertising and other industries.And the data is storaged in our disk.

Where was the data in this dataset sourced from?
1.Our own render data with intellectual property rights.
2.Our users store the render data and raw data to our service.

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
Link:https://pan.baidu.com/s/18MkMfgnrYhfpOCWkfZLMgw  password:r9y8
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
Yes,it is.All the data can be retrieved by anyone.

What is the expected retrieval frequency for this data?
On average, about 10 times a year.

For how long do you plan to keep this dataset stored on Filecoin?
At least 540 days.

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
All regions.

How will you be distributing your data to storage providers? Is there an offline data transfer process?
1.We will generate the car files,upload to our server , then the storage provider will download them or send them to storage provider.The same data,we will send storage deal to at least 4 storage providers and 3 copies for the same storage provider.
2.The offline data process will be supported.

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
First,we will choose the storage providers these we are familiar with or we have worked with or will be believed in the community.
Then,The storage providers that I send storage deals will be at 3 different regions.
And all providers must agree that they should store unsealed files and keep these data retrieved anytime.

How will you be distributing deals across storage providers?
First,we will communicate with these storage providers,talk about the ability that they handle the data.
Then,we will send storage deals based on their ability to handle data.
If the storage provider has more ability to handle data,we will send more deals to it and the data sent to it will be less than 30% of all data. 

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
Yes,we have all to start making deals. If we have any question,we will ask for help to community.

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 4PiB

**Expected weekly DataCap usage rate**

> 400TiB

**Client address**

>f1k4ljwusrgqbeifkily2noykutbpi3sf77wmk5pq

**Comment by 1ane-1** [comment]
Could you send an email to filplus-app-review@fil.org with your official domain in order to confirm your identity? 
Can you provide more detailed information about other storage providers participated in this program, such as you can list SPs you have contacted with at present?
Could you give some screenshot of you having more than 300T of raw data? Also data samples?

**Comment by shxfli** [comment]
Thanks Anne. We have sent you email just now from the email gaoyunyue@csrender.com.Please check it for us.
1.We have contacted with some SPs ,such as f0436065 ，f0701089，f01981571，f01053413 and so on.

**Comment by shxfli** [comment]
Thanks Anne. We have sent you email just now from the email gaoyunyue@csrender.com.Please check it for us.

1.We have contacted with some SPs ,such as f0436065 ，f0701089，f01981571，f01053413 and so on.

2.Below are our screenshot of our raw data.That is about 300T.
![cs rrr](https://user-images.githubusercontent.com/116863228/209920909-1bb4354b-e961-4b32-8cbc-7a236f675979.jpg)

![cs render](https://user-images.githubusercontent.com/116863228/209920979-fa71015b-eef5-47c6-8c39-ca188e5d9e02.jpg)

**Comment by 1ane-1** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebyvkvlqaebepxfndqrzjvo5xmeldwjlaaoj5moybqxhmp2266aay 
#### Address 
> f1k4ljwusrgqbeifkily2noykutbpi3sf77wmk5pq
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1mdk7s2vntzm6hu35yuo6vjubtrpfnb2awhgvrri
#### Id
> ff46732c-d0ab-4682-b803-3e3c19143bdb
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebyvkvlqaebepxfndqrzjvo5xmeldwjlaaoj5moybqxhmp2266aay

**Comment by Joss-Hua** [comment]
CC @Kevin-FF-USA @galen-mcandrew Hi guys, please leave a message here after receiving the KYC email so that the subsequent notary can continue to follow up this LDN
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1201#issuecomment-1358760849

**Comment by Joss-Hua** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebsnx3lmlrrcljiphmur33rlq3lzux2sj3njh6uhr6dooyzksi3yq 
#### Address 
> f1k4ljwusrgqbeifkily2noykutbpi3sf77wmk5pq
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1tfg54zzscugttejv336vivknmsnzzmyudp3t7wi
#### Id
> ff46732c-d0ab-4682-b803-3e3c19143bdb
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebsnx3lmlrrcljiphmur33rlq3lzux2sj3njh6uhr6dooyzksi3yq

**Comment by herrehesse** [comment]
Dear Applicant,

Due to the increased amount of erroneous/wrong Filecoin+ data recently, on behalf of the entire community, we feel compelled to go deeper into datacap requests. Hereby to ensure that the overall value of the Filecoin network and Filecoin+ program increases and is not abused.

Please answer the questions below as comprehensively as possible.

**Customer data**

- Could you demonstrate exactly how and to what extent customer contact occurred? 

We expect that for the onboarding of customers with the scale of an LDN there would have been at least multiple email and perhaps several chat conversations preceding it. A single email with an agreement does not qualify here.

- Did the customer specify the amount of data involved in this relevant correspondence?

- Why does the customer in question want to use the Filecoin+ program? 

_Should this only be soley for acquiring datacap this is of course **out of the question**. The customer must have a legitimate reason for wanting to use the Filecoin+ program which is intended as a program to store useful and public datasets on the network._ 

- Why is the customer data considered Filecoin+ eligible?

_(As an intermediate solution Filecoin offers the FIL-E program or the glif.io website for business datasets that do not meet the requirements for a Filecoin+ dataset)_


**Files and Processing**

- Could you please demonstrate to us how you envision processing and transporting the customer data in question to any location for preparation?
- Would you demonstrate to us that the customer, the preparer and the intended storage providers all have adequate bandwidth to process the set with its corresponding size?
- Would you tell us how the data set preparer takes into account the prevention of duplicates in order to prevent data cap abuse?


Hopefully you understand the caution the overall community has for onboarding the wrong data. We understand the increased need for Filecoin+, however, we must not allow the program to be misused. Everything depends on a valuable and useful network, let's do our best to make this happen. Together.

**Comment by BDEio** [comment]
@shxfli  Hi! Congratulations on your DataCap approval！
BDE is a trusted deals auction house helping you to get paid storing your data with reliable storage providers. If you need any help, please get in touch.

**Comment by cryptowhizzard** [comment]
Hello @shxfli 

Can you tell us when we can expect the first data to arrive on chain?

**Comment by shxfli** [comment]
Thanks    @cryptowhizzard 
We are preparing for the data.Maybe about half a month.

**Comment by Sunnyiscoming** [comment]
checker:manualTrigger

**Comment by nj-steve** [comment]
checker:manualTrigger

**Comment by nj-steve** [comment]
@shliming Hello，How much data have you prepared to store in the next stage?

**Comment by shliming** [comment]
@nj-steve we have prepared about 200TiB data that want to store

**Comment by Normalnoise** [comment]
checker:manualTrigger

**Comment by Normalnoise** [comment]
@shliming  cid checker has tell me your storage is healthy, but I think you need to send deals to more storage providers  in different region. If you can not contact more other region SPs, you can using [swan-provider](https://github.com/FogMeta/go-swan-provider) to find more SPs around the world. if you have some questions, you can visit the #fil-filswan channel in the slack. Based on the current situation, I am willing to support you in this round. 

it seems there are some issues. I have contacted with Philip
![image](https://user-images.githubusercontent.com/102578774/229693288-fc28d395-0f46-409e-af7d-b47edbea3fde.png)

**Comment by shliming** [comment]
@Normalnoise Thanks for your help.

**Comment by shliming** [comment]
@Sunnyiscoming Hello, please help us. If the system has  any bug that large-datacap-requests  bot cannot trigger ” DataCap Allocation requested“？So the notary cannot allocate DataCap for us.

**Comment by shliming** [comment]
@Sunnyiscoming Hello,please help us, if the system has any bug, we didn't  receive the "Datacap Request Trigger".

**Comment by zcfil** [comment]
checker:manualTrigger

**Comment by zcfil** [comment]
The data looks very healthy, this round supports it. We will continue to pay attention in the future

**Comment by zcfil** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacede2agi3kuuj7hlrwuoauw6w6rup5xivmcz2ufsc4af5oej2vx5qk 
#### Address 
> f1k4ljwusrgqbeifkily2noykutbpi3sf77wmk5pq
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1cjzbiy5xd4ehera4wmbz63pd5ku4oo7g52cldga
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacede2agi3kuuj7hlrwuoauw6w6rup5xivmcz2ufsc4af5oej2vx5qk

**Comment by zcfil** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecrgqfwadaouytkrbzd3glzrhbfgi272cqqmdk7q47zyykiedo4iq 
#### Address 
> f1k4ljwusrgqbeifkily2noykutbpi3sf77wmk5pq
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1cjzbiy5xd4ehera4wmbz63pd5ku4oo7g52cldga
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecrgqfwadaouytkrbzd3glzrhbfgi272cqqmdk7q47zyykiedo4iq

**Comment by shliming** [comment]
checker:manualTrigger

**Comment by stcouldlisa** [comment]
checker:manualTrigger

**Comment by stcouldlisa** [comment]
<img width="852" alt="WechatIMG211" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/112812896/27093526-473a-4891-999d-1525ad2187dc">

**Comment by stcouldlisa** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaqabazvtvxrr2g25gzb4gvf6mxjsjwcdbisiheal53ldojgsv4bs 
#### Address 
> f1k4ljwusrgqbeifkily2noykutbpi3sf77wmk5pq
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1jvvltduw35u6inn5tr4nfualyd42bh3vjtylgci
#### Id
> aff40f28-bcff-4c59-b539-01a0ad9e50fc
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaqabazvtvxrr2g25gzb4gvf6mxjsjwcdbisiheal53ldojgsv4bs

**Comment by shliming** [comment]
checker:manualTrigger

**Comment by shliming** [comment]
checker:manualTrigger

**Comment by shliming** [comment]
checker:manualTrigger

**Comment by nj-steve** [comment]
checker:manualTrigger

**Comment by nj-steve** [comment]
The CID checker looks good. Please contact the SPs to support more retrieval.

**Comment by shliming** [comment]
@nj-steve Thanks. I will contact some of them to open the retrieval.

**Comment by nj-steve** [comment]
The customer contacted me, promising to increase the retrieval rate, and promised that they would send to more SPs. I will support them temporarily and I will keep an eye on it.

**Comment by nj-steve** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecaqpqowffjfnbta5bhfnsodhyqteuv26kgh4dfae7zugmk2e33zw 
#### Address 
> f1k4ljwusrgqbeifkily2noykutbpi3sf77wmk5pq
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1xx6555qijma7igpnjspyvdunc4vfxkawnpqy5ii
#### Id
> c30d1aae-4a8d-4ba1-98b3-978b0f6f61c9
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecaqpqowffjfnbta5bhfnsodhyqteuv26kgh4dfae7zugmk2e33zw

**Comment by shliming** [comment]
checker:manualTrigger

**Comment by herrehesse** [comment]
checker:manualTrigger

**Comment by Fatman13** [comment]
checker:manualTrigger

**Comment by Fatman13** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebwrtc35xv7clhxqan27s4t3tyunrpvx5cp7geixy6rzuyx72sm7o 
#### Address 
> f1k4ljwusrgqbeifkily2noykutbpi3sf77wmk5pq
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1j3u7crhjzwb2cj5mq7vodlt4o66yoyci7lhcauy
#### Id
> c30d1aae-4a8d-4ba1-98b3-978b0f6f61c9
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebwrtc35xv7clhxqan27s4t3tyunrpvx5cp7geixy6rzuyx72sm7o

**Comment by Fatman13** [comment]
Reached out by the client on Slack. Retrieval is on the low end but > 1%. Walked through their plans to increase retrievability.

**Comment by shliming** [comment]
checker:manualTrigger

**Comment by shliming** [comment]
checker:manualTrigger

**Comment by shliming** [comment]
keep going

**Comment by shliming** [comment]
keep going

**Comment by shliming** [comment]
keep going

**Comment by cryptowhizzard** [comment]
ERROR: offer error: retrieval query offer errored: failed to fetch piece to retrieve from: getting pieces for cid QmTqmu6XNWT4WMexoSXVEUcZT74MNQXH285KW4J6m15Yha: getting pieces containing block QmTqmu6XNWT4WMexoSXVEUcZT74MNQXH285KW4J6m15Yha: failed to lookup index for mh 122051c06842078e997dc7cb80c2d8884dc916ff0638ef8b5620e5f6a6d7ea9fbf6d, err: datastore: key not found

**Comment by cryptowhizzard** [comment]
Dear shxfli,

As notary I am doing due diligence on your LDN. I could not get retrieval to work. Can you please upload the car file of CID baga6ea4seaqd2chrgnxc6hemhfibzjawzrcmwnay7uqiofn2xlrdpofrl7lk2aq ?

You can use our upload system at http://send.datasetcreators.com. Please select 7 days for the system to keep the file and post the link you received here so I (and other notaries) can download your content.

**Comment by shliming** [comment]
@cryptowhizzard Thanks for your work.We will find this car file and download it in our local and upload it recently.

**Comment by shliming** [comment]
The upload speed is too slow.
<img width="796" alt="图片" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/116863228/b75156e9-5b76-4906-bfda-8c35b43c515c">
I have restore the car file to original file.The content is normal.
<img width="450" alt="图片" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/116863228/92f76cc4-6497-4de3-b264-c5ba5feff52c">

**Comment by shliming** [comment]
checker:manualTrigger

**Comment by cryptowhizzard** [comment]
> The upload speed is too slow. <img alt="图片" width="796" src="https://user-images.githubusercontent.com/116863228/264005226-b75156e9-5b76-4906-bfda-8c35b43c515c.png"> I have restore the car file to original file.The content is normal. <img alt="图片" width="450" src="https://user-images.githubusercontent.com/116863228/264006511-92f76cc4-6497-4de3-b264-c5ba5feff52c.png">

Sorry but I can't take this for an answer. You manage to send out PiB's of data to SP's but are incapable of uploading a few GB?

**Comment by shliming** [comment]
Sorry, you misunderstand me. I mean this platform upload speed is slow. Data transmission, we use the server to transmit to SPs. To upload data to this platform, I can only download it to my personal computer and then upload it from my local computer. The speed from my computer with the platform is too slow. 
Please wait for a while.

**Comment by cryptowhizzard** [comment]
> Sorry, you misunderstand me. I mean this platform upload speed is slow. Data transmission, we use the server to transmit to SPs. To upload data to this platform, I can only download it to my personal computer and then upload it from my local computer. The speed from my computer with the platform is too slow. Please wait for a while.

No problem... sorry I misunderstood!

**Comment by shliming** [comment]
https://send.datasetcreators.com/download/b34ab807c04df44b/#sXaxEAh3QHBNz9JIpfvqkQ
Hello, you should unzip the file , and get a car file.

**Comment by Normalnoise** [comment]
checker:manualTrigger

**Comment by Normalnoise** [comment]
CID report shows it is healthy, willing to support this round

**Comment by Normalnoise** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebkysaq3qbiflxgilkhkjtonblph7ljeuwbtyz73avefsl7p26v6w 
#### Address 
> f1k4ljwusrgqbeifkily2noykutbpi3sf77wmk5pq
#### Datacap Allocated
> 1.56PiB
#### Signer Address
> f1c5non5yf35avgcpsqvxu4yj54yyvxorwyjochqq
#### Id
> d8e77580-fdbd-45d3-a1f1-f4540b27eae5
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebkysaq3qbiflxgilkhkjtonblph7ljeuwbtyz73avefsl7p26v6w

**Comment by cryptowhizzard** [comment]
Dear shxfli,

As notary I am doing due diligence on your LDN. I could not get retrieval to work. Can you please upload the car file of CID baga6ea4seaqmcezv2lloms62nojrghscyeljyg42cbyn6xhrihxyi654zfjruoi ?

You can use our upload system at http://send.datasetcreators.com. Please select 7 days for the system to keep the file and post the link you received here so I (and other notaries) can download your content.

**Comment by mikezli** [comment]
checker:manualTrigger

**Comment by mikezli** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaanuydnqcglbnmollsijvk6rd577wg3ecrtjk7veqacyc3mxyly2 
#### Address 
> f1k4ljwusrgqbeifkily2noykutbpi3sf77wmk5pq
#### Datacap Allocated
> 1.56PiB
#### Signer Address
> f1dnb3uz7sylxk6emti3ififcvu3nlufnnsjui6ea
#### Id
> d8e77580-fdbd-45d3-a1f1-f4540b27eae5
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaanuydnqcglbnmollsijvk6rd577wg3ecrtjk7veqacyc3mxyly2

**Comment by shliming** [comment]
<img width="910" alt="图片" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/116863228/4d1a94ae-f337-41d6-b021-6bfe0e7e1255">
hello, the car is here.

**Comment by shliming** [comment]
checker:manualTrigger

**Comment by shliming** [comment]
hello herrehesse, I will connect the SPs,if they are the real same SP.If they are I will tell it to the community , only could send deals to the only one.

**Comment by cryptowhizzard** [comment]
Dear shxfli,

As notary I am doing due diligence on your LDN. I could not get retrieval to work. Can you please upload the car file of CID baga6ea4seaqmcezv2lloms62nojrghscyeljyg42cbyn6xhrihxyi654zfjruoi ?

You can use our upload system at http://send.datasetcreators.com. Please select 7 days for the system to keep the file and post the link you received here so I (and other notaries) can download your content.

**Comment by shliming** [comment]
sorry, we also need keeping

**Comment by shliming** [comment]
keep going

**Comment by kernelogic** [comment]
checker:manualTrigger

**Comment by kernelogic** [comment]
Distribution is all over the world. Very minimal accidental CID sharing I'm gonna to let it pass.

**Comment by kernelogic** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebb3mo4e6ftkndtfib6qyw62viaogatsvrdjtu3kv47rfd2r2n4q4 
#### Address 
> f1k4ljwusrgqbeifkily2noykutbpi3sf77wmk5pq
#### Datacap Allocated
> 1.26PiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### Id
> 1ff5d6e7-d12b-481a-a425-eb0674ed6479
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebb3mo4e6ftkndtfib6qyw62viaogatsvrdjtu3kv47rfd2r2n4q4

**Comment by Tom-OriginStorage** [comment]
Very small amount of CID sharing willing to support

**Comment by Tom-OriginStorage** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecdkvsn3ecu7z5bs36jzu7mmhfd4ntypixyr55onuxpumkchxx6bg 
#### Address 
> f1k4ljwusrgqbeifkily2noykutbpi3sf77wmk5pq
#### Datacap Allocated
> 1.26PiB
#### Signer Address
> f1q6bpjlqia6iemqbrdaxr2uehrhpvoju3qh4lpga
#### Id
> 1ff5d6e7-d12b-481a-a425-eb0674ed6479
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecdkvsn3ecu7z5bs36jzu7mmhfd4ntypixyr55onuxpumkchxx6bg

**Comment by Sunnyiscoming** [comment]
Hello, @shliming  per the https://github.com/filecoin-project/notary-governance/issues/922 for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

This information will be reviewed by Fil+ Governance team to confirm validity and then the application will be allowed to move forward for additional notary review.
