### ISSUE TITLE
[DataCap Application] <Mapnova> - <Map and dashcam data>

### ISSUE THREAD

**Issue by mapnova2021** [filecoin-project/filecoin-plus-large-datasets#1202]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Mapnova
- Website / Social Media: https://www.mapnova.io/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 80TiB
- On-chain address for first allocation: f1aptusjean3tderq6ci3dey54pl7zal54wfjc65y

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
MapNova builds the world's full-coverage high definition map, we process not only data about GPS signals, road information, but also traffic lights, static objects and dynamic informations analysised from dashcam videos. we have large amount daily video data to process, and after we have processed the video, we would like to store the videos in somewhere in case one day we need to retrieve them for further analysis.

What is the primary source of funding for this project?
Ourselves.

What other projects/ecosystem stakeholders is this project associated with?
No.

## Use-case details

Describe the data being stored onto Filecoin
The lidar data and camera data.

Where was the data in this dataset sourced from?
MapNova

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
https://drive.google.com/file/d/10RFNjMkpOoS7bQIx_RzBBwvk4PtvCEGE/view
https://drive.google.com/file/d/1UgkpEazl0ASKzEYE_fMvAjUGQjxYJM6r/view
https://drive.google.com/file/d/1FUz0PZJGP19kK4FtOuByQ_7nNSfO8ZPo/view
https://drive.google.com/file/d/1ur2xq0x5pqBhA0f-hmdbqbtnIS4aak_t/view

        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
Yes, it is a public dataset.

What is the expected retrieval frequency for this data?
1-2 times per year.

For how long do you plan to keep this dataset stored on Filecoin?
3-5 years.

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
All regions.

How will you be distributing your data to storage providers? Is there an offline data transfer process?
We will negotiate with SP, both online and offline are acceptable

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
We'll choose storage providers based on the price and geography and other aspects affect the storage service. Currenct candidates are: f0809927, f090492, f091395, and we'll find more providers.

How will you be distributing deals across storage providers?
We plan to have 3 replicas and each providers can have less than 30% of the data.

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
Yes, we have enough resources and funds to start trading.

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 80TiB

**Client address**

> f1aptusjean3tderq6ci3dey54pl7zal54wfjc65y

**Comment by mapnova2021** [comment]
> ### Datacap Request Trigger
> **Total DataCap requested**
> 
> > 5PiB
> 
> **Expected weekly DataCap usage rate**
> 
> > 80TiB
> 
> **Client address**
> 
> > f1aptusjean3tderq6ci3dey54pl7zal54wfjc65y

**Comment by cryptowhizzard** [comment]
Hi there,

I have been looking at your website and your application request. It looks like a nice project. 

I tried to look at the SP's for storing your data as it has to be retrievable but it looks like none of the 3 support retrievability.

lotus net connect f0809927
f0809927 -> {12D3KooWL2vbWcJ3jhzvx2vV1r3QguenEEWy9Ggskj2eJcgtkfo8: []}
ERROR: failed to parse multiaddr "f0809927": must begin with /

lotus net connect f090492
f090492 -> {12D3KooWBoawg91CyDgPT7B29eV694ijdtYQSFUyFScD1C9sBWdj: []}
ERROR: failed to parse multiaddr "f090492": must begin with /

 lotus net connect f091395
f091395 -> {12D3KooWQfh4vzcevhacHypRcSZWt666AtTEb52nvXyWWX953vt4: []}
ERROR: failed to parse multiaddr "f091395": must begin with /

Can you tell me where these 3 SP's are located and why you have chosen them instead of SP's with reputation?

Looking at the samples you provided i see that one of them is in Mission Creek park USA. Can you tell me what i am looking at with the purple ring around it?

Thanks!

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Can you show us visible proof of the size of your data and the storage systems you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230232885049356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!

**Comment by Sunnyiscoming** [comment]
Any update here?
