### ISSUE TITLE
[DataCap Application] stariverpan.com - 小龙云盘

### ISSUE THREAD

**Issue by changlizhi** [filecoin-project/filecoin-plus-large-datasets#1203]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Stariver Technology Co., Ltd(四川星河飞天科技有限公司)
- Website / Social Media: https://www.stariverpan.com/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100TiB
- On-chain address for first allocation: f13gwxgfkgogu5wujgmuzhkjzgtt44twox4whtr3i

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```

Stariver Technology Co., Ltd is a cloud disk company and is developing in web3 technology deeply. we believe that distributed store will be the most useful tech in the future!
LoogBox（“小龙云盘” in chinese）is one of our project,which is a cloud disk based on ipfs network,people can upload all files to ipfs by using this app.on the other hand ,you can research datas by cid on this app also. and you can view the datas which is opened by client.
You can download and install it by searching "小龙云盘（or LoongBox in English）" On AppStore(apple) or Samsung appstore(android) or download the pc App from our official website.

```

What is the primary source of funding for this project?
```
The company undertake this part of the spending.

```

What other projects/ecosystem stakeholders is this project associated with?
```
maybe the traditional cloud dist app like baidu cloud disk or other cloud disk.

```

## Use-case details

Describe the data being stored onto Filecoin
```

long video,short video,pictures,articles and so on.as a cloud disk you can store everything on it and the datas of you will be send to ipfs network and filecoin too.
Our data from "小龙云盘" is now pined on our own ipfs nodes and nft.storage/web3.storage.but with the data becoming larger and larger,our ipfs nodes seems too small! because the TiB level customer from video cut company is using our app to decrease their store cost.And the speed of nft.storage and web3.storage is too slow for us.so we want to apply datacap by using the filecoin network to store the cold data.

```

Where was the data in this dataset sourced from?
```
Uploaded by client from "小龙云盘".
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
You can use our own gateway below or the gateway of nft.storage gateway (bafyxxxxxx.ipfs.dweb.link) with your own cid:
(all of these data is uploaded by our app's client)
for example:
10M
https://ipfsgw.stariverpan.com/ipfs/bafybeidhnyd3z2hcmijau6gntnqbd4nzaxv5gq43bjske5f7xv5bemsnh4(JPG)
https://ipfsgw.stariverpan.com/ipfs/bafybeigicmfjsfzlputa3mffvmxjjlgyzdo7bn43lo7hcwqhivlved6jiy(zip)
https://ipfsgw.stariverpan.com/ipfs/bafybeierau2d6osa2xupxv4wfqpnmuedkk6vbthykqhwj5bcqq2bu3ljmq(mp3)

100M
https://ipfsgw.stariverpan.com/ipfs/bafybeifvtcatydzhfls622ogmkqucnjp7y5f7n243a2jq6dul65z3hroge(mp4)
https://ipfsgw.stariverpan.com/ipfs/bafybeigjtbcbtazn55rulgpj3rtzie6nl2pdghens7ig2vjwve5xc5a7zy(mp4)

1G
https://ipfsgw.stariverpan.com/ipfs/bafybeif3mnf2fqlk22dofj5yz7l3boetcvrc6jtndhwbocpoduhksxkafu(mp4)
https://ipfsgw.stariverpan.com/ipfs/bafybeibn3mdfz2sclrjlttmbskgn73irb4r3lpaksvqa7zr3g7shgimcsi(mp4)

3.4G
https://ipfsgw.stariverpan.com/ipfs/bafybeic5x7c6bv56t7kg25y57ohmm7ffnfdmleq423ln3xvh4xtll5tpjm(mp4)

```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes, we confirm that it is a public dataset.
```

What is the expected retrieval frequency for this data?
```
It's depend on the client's need,we can use LRU algorithm to distinguish and the hot data will be still on ipfs network.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
Permanent.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
China.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
we will start a lotus daemon link to our ipfs nodes  for "lotus client deal" cmd and start a timed task to exec the cmd when the LRU algorithm shows we need.
when the data become too large ,we will transfer the data offline.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
we will find the Capable miner which is stable increasing power in slingshot or who can sealing datas 20TiB per day.
```

How will you be distributing deals across storage providers?
```
we will divide the data by type and find storage providers who has the Preference of type.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
We can start immediately And if community encourage and reward some fil is much better!
```

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 100TiB

**Client address**

> f13gwxgfkgogu5wujgmuzhkjzgtt44twox4whtr3i

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Can you show us visible proof of the size of your data and the storage systems you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230337462961356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!
