### ISSUE TITLE
[DataCap Allocation] - StarCitizen

### ISSUE THREAD

**Issue by ierud220411** [filecoin-project/filecoin-plus-large-datasets#1204]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Star  Citizen
- Website / Social Media: https://www.starcitizen.global
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 200TiB
- On-chain address for first allocation: f1jag7pvit7v6oqv2vcleke2offs4jwqjvm6vb7ei

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
StarCitizen is all about getting ordinary users to understand and participate in decentralization. To provide closer links between project parties and investors. These include decentralized multi-chain wallet, short video, live streaming, chat, task hall, conference. It allows you to have all the information in the web3 world in one app.
```

What is the primary source of funding for this project?
```
Our own funds.
```

What other projects/ecosystem stakeholders is this project associated with?
```
No
```

## Use-case details

Describe the data being stored onto Filecoin
```
The data stored in filecoin will be some video and picture data.
```

Where was the data in this dataset sourced from?
```
Short videos, live videos and NFT footage from our users.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://sss8888.s3.ap-southeast-1.amazonaws.com/android_20192_20221103_162527_769436.mp4
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Confirm.
```

What is the expected retrieval frequency for this data?
```
if need
```

For how long do you plan to keep this dataset stored on Filecoin?
```
2 years
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Asia
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Both online and offline transfer.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We have contacted some SPs,like: f01825161 f01785040 f01740679
```

How will you be distributing deals across storage providers?
```
Three to four copies will be evenly distributed among those SPs.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
We have sufficient resources and funds that can start now.
```

**Comment by kernelogic** [comment]
This is the real star citizen  https://robertsspaceindustries.com/

**Comment by ierud220411** [comment]
> This is the real star citizen https://robertsspaceindustries.com/

Maybe the names are similar, I can provide the official certificate.

**Comment by Sunnyiscoming** [comment]
https://sss8888.s3.ap-southeast-1.amazonaws.com/android_20192_20221103_162527_769436.mp4
The link of data samples is unavailable. Please check it.

The eastablished time of your website is only 30 days. Why you have 5 PB data storage requirement?

Can you give more detailed description of your organization and business?

What's the relationship between you and the organization?

**Comment by simonkim0515** [comment]
Closing due to no response. You may reapply with another application
