### ISSUE TITLE
[DataCap Application] <Long An Law Firm> - < Long An University Hall>

### ISSUE THREAD

**Issue by Swift-scouts** [filecoin-project/filecoin-plus-large-datasets#1205]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Long An Law Firm
- Website / Social Media:http://www.longanlaw.com/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):100TiB
- On-chain address for first allocation:f1u7l2fksfm6hoqcdss4yabrg2l52hx55vcnc7hiq

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Founded in 1992, Long An is one of the earliest partnership law firms in China, and was successfully restructured into a special general partnership law firm in 2017. At present, we have offices in more than 30 cities in China, including Beijing, Shanghai, Shenyang and Shenzhen, and Longan is expanding further. In order to make the new partner better serve customers, we set up video courses to help Long An'er learn legal knowledge and provide a way for the Grand Duke to learn law.
```

What is the primary source of funding for this project?
```
Ourselves.
```

What other projects/ecosystem stakeholders is this project associated with?
```
No
```

## Use-case details

Describe the data being stored onto Filecoin
```
Law teaching video
```

Where was the data in this dataset sourced from?
```
Some of them came from our staff's live recording ,as well as joint discussions with other teachers,and we also had public interest legal courses accumulated from the Internet
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
链接：https://pan.baidu.com/s/1g9vJFY1EAoyS2q3F0FHRSA 
提取码：gg58
It has 30-day access
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes
```

What is the expected retrieval frequency for this data?
```
Maybe twice a year is enough
```

For how long do you plan to keep this dataset stored on Filecoin?
```
We hope it will last a long time, in Filecoin maybe 3-5 years
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Hong Kong
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
We will negotiate with SP, both online and offline are acceptable
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We'll choose storage providers based on the price and geography and other aspects affect the storage service. Currenct candidates are: f01938665,f01859603,f01909429,f01938721,f01851482
```

How will you be distributing deals across storage providers?
```
We plan to have 5 replicas and each providers should keep more than 50%  source data.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, we have enough resources and funds to start trading.
```

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 100TiB

**Client address**

>f1u7l2fksfm6hoqcdss4yabrg2l52hx55vcnc7hiq

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 100TiB

**Client address**

> f1u7l2fksfm6hoqcdss4yabrg2l52hx55vcnc7hiq

**Comment by newwebgroup** [comment]
Hey Client，
About KYC&KYB
1：Could you send an email to filplus-app-review@fil.org ？

The content should include the number of the LDN application.

2：Can you provide more detailed information about other storage providers participated in this program, such as you can list SPs you have contacted with at present?

3.How large is your existing dataset? How much is the data growth per month?

**Comment by Swift-scouts** [comment]
<img width="812" alt="图片" src="https://user-images.githubusercontent.com/33534080/208877983-2375245f-f8a0-4353-89f3-ce21de236e90.png">
1，Email has been sent, please check
2，Currently contacted SPs are f01965334，f01966534，f01967473，f01901379，f01901765，f01907545 and son on
3，Our accumulated data is almost 2PiB, and the amount of data generated every month is about 50~100TiB.
thank you!

**Comment by newwebgroup** [comment]
Because it was the first round, the Client answered my relevant questions, and the conditions for triggering signature had been met, so I chose to pass.
If anyone has more questions about the application, they can keep watching and checking.

**Comment by newwebgroup** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceay7us6ee2hzlvxnmtfmzfuw6rqxuluzelezo2gmzydhs32kybgf4 
#### Address 
> f1u7l2fksfm6hoqcdss4yabrg2l52hx55vcnc7hiq
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1e77zuityhvvw6u2t6tb5qlnsegy2s67qs4lbbbq
#### Id
> ba1d80b8-49a6-4071-8bd8-647c15a4364f
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceay7us6ee2hzlvxnmtfmzfuw6rqxuluzelezo2gmzydhs32kybgf4

**Comment by Tom-OriginStorage** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebyyin77g2tzsx4ruugl5mubzmfegt72agacbacrlp6g4ukjla77u 
#### Address 
> f1u7l2fksfm6hoqcdss4yabrg2l52hx55vcnc7hiq
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1q6bpjlqia6iemqbrdaxr2uehrhpvoju3qh4lpga
#### Id
> ba1d80b8-49a6-4071-8bd8-647c15a4364f
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebyyin77g2tzsx4ruugl5mubzmfegt72agacbacrlp6g4ukjla77u

**Comment by herrehesse** [comment]
Dear Applicant @Swift-scouts,

Due to the increased amount of erroneous/wrong Filecoin+ data recently, on behalf of the entire community, we feel compelled to go deeper into datacap requests. Hereby to ensure that the overall value of the Filecoin network and Filecoin+ program increases and is not abused.

Please answer the questions below as comprehensively as possible.

**Customer data**

- Could you demonstrate exactly how and to what extent customer contact occurred? 

We expect that for the onboarding of customers with the scale of an LDN there would have been at least multiple email and perhaps several chat conversations preceding it. A single email with an agreement does not qualify here.

- Did the customer specify the amount of data involved in this relevant correspondence?

- Why does the customer in question want to use the Filecoin+ program? 

_Should this only be soley for acquiring datacap this is of course **out of the question**. The customer must have a legitimate reason for wanting to use the Filecoin+ program which is intended as a program to store useful and public datasets on the network._ 

- Why is the customer data considered Filecoin+ eligible?

_(As an intermediate solution Filecoin offers the FIL-E program or the glif.io website for business datasets that do not meet the requirements for a Filecoin+ dataset)_


**Files and Processing**

- Could you please demonstrate to us how you envision processing and transporting the customer data in question to any location for preparation?
- Would you demonstrate to us that the customer, the preparer and the intended storage providers all have adequate bandwidth to process the set with its corresponding size?
- Would you tell us how the data set preparer takes into account the prevention of duplicates in order to prevent data cap abuse?


Hopefully you understand the caution the overall community has for onboarding the wrong data. We understand the increased need for Filecoin+, however, we must not allow the program to be misused. Everything depends on a valuable and useful network, let's do our best to make this happen. Together.

**Comment by BDEio** [comment]
@Swift-scouts  Hi! Congratulations on your DataCap approval！
BDE is a verified deals auction house helping you to get paid storing your data with reliable storage providers. If you need any help, please get in touch.

**Comment by Swift-scouts** [comment]
We and our friends from Long 'an Law Firm prepared the data transmission plan several months ago and contacted the storage service provider in Hong Kong. The data is transferred to the storage server in Hong Kong through the network. In this way, when storing a copy of data in Hong Kong, it is more convenient to provide data transmission services to storage providers in different regions. Now 1P of data has been transferred to the storage server in Hong Kong. Hong Kong is a very powerful financial and information center with sufficient hardware and software capabilities to provide data transmission services. Filecoin+ is a very good project. Our partners are very happy to put their own teaching and popular science data on this project and lick the bricks for filecoin project. We also take data quality very seriously in filecoin+. In data transfer and download, data is de-duplicated so you don't have to worry about duplicate data.

**Comment by NDLABS-OFFICE** [comment]
Willing to support.

**Comment by NDLABS-OFFICE** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebukp2jdchfjaf4af2nz43cuyozwb2fjlzwfgglvm3iy27wp7wy56 
#### Address 
> f1u7l2fksfm6hoqcdss4yabrg2l52hx55vcnc7hiq
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1yayfsv6whu3rheviucvventj3y6t542xfpb47ei
#### Id
> 232a4d2d-3cfc-4ebb-a351-6495aea3ec92
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebukp2jdchfjaf4af2nz43cuyozwb2fjlzwfgglvm3iy27wp7wy56

**Comment by stcouldlisa** [comment]
Storage provider distribution looks healthy、 No CID sharing has been observed， I  want to support.

**Comment by stcouldlisa** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb27umesi3cuaebf7lc3mox425nvuz3mawkh2rv3brjzqupaimzzi 
#### Address 
> f1u7l2fksfm6hoqcdss4yabrg2l52hx55vcnc7hiq
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1jvvltduw35u6inn5tr4nfualyd42bh3vjtylgci
#### Id
> 232a4d2d-3cfc-4ebb-a351-6495aea3ec92
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb27umesi3cuaebf7lc3mox425nvuz3mawkh2rv3brjzqupaimzzi

**Comment by newwebgroup** [comment]
checker:manualTrigger

**Comment by cryptowhizzard** [comment]
Hello,

None of this data is available for retrieval. This is against the FIL+ / LDN rules. Please contact your SP's and make the data retrievable before we can continue allocating datacap.

>>

ERROR: offer error: retrieval query offer errored: failed to fetch piece to retrieve from: getting pieces for cid bafykbzaceb3jzijnry64dokvowigwi2f5xuvojh5dmnfd3p5uvhpwl6wjubdy: getting pieces containing block bafykbzaceb3jzijnry64dokvowigwi2f5xuvojh5dmnfd3p5uvhpwl6wjubdy: failed to lookup index for mh a0e40220769ca12d8e3dc1b95575906b2345ede95724fd1b1a51edfda54efb2fd64d023c, err: datastore: key not found

ERROR: offer error: retrieval query offer errored: failed to fetch piece to retrieve from: getting pieces for cid bafykbzacedghdivbilivdvdyndedsit2oxxrgw7gp5uaukkz4w2a66itmcrc6: getting pieces containing block bafykbzacedghdivbilivdvdyndedsit2oxxrgw7gp5uaukkz4w2a66itmcrc6: failed to lookup index for mh a0e40220cc71a2a142d151d47868c839227a75ef135be67f680a2959e5b40f791360a22f, err: datastore: key not found

ERROR: offer error: retrieval query offer errored: failed to fetch piece to retrieve from: getting pieces for cid bafykbzaceagjjjh2k6r7tj3bi32e32bf7dkvjfxc357mri57qqk3h4os5l4qu: getting pieces containing block bafykbzaceagjjjh2k6r7tj3bi32e32bf7dkvjfxc357mri57qqk3h4os5l4qu: failed to lookup index for mh a0e402200c94a4fa57a3f9a76146f44de825f8d55496e2df7ec8a3bf8415b3f1d2eaf90a, err: datastore: key not found

ERROR: offer error: retrieval query offer errored: failed to fetch piece to retrieve from: getting pieces for cid bafybeie5szlgl5joyjerpwuqb6dojicdrxruo2pra7r422ybd5q4lnrx64: getting pieces containing block bafybeie5szlgl5joyjerpwuqb6dojicdrxruo2pra7r422ybd5q4lnrx64: failed to lookup index for mh 12209d965665f52ec24917da900f86e4a0438de34769f107e3cd6b011f61c5b637f7, err: datastore: key not found

ERROR: offer error: retrieval query offer errored: failed to fetch piece to retrieve from: getting pieces for cid bafykbzaceayuu25itetqtxndp637b7kyqcwccvp357k5wsyveisy3jraw4cym: getting pieces containing block bafykbzaceayuu25itetqtxndp637b7kyqcwccvp357k5wsyveisy3jraw4cym: failed to lookup index for mh a0e40220314a6ba8992709dda37fb7f0fd5880ac2155fbefd5db4b1522258da620b70586, err: datastore: key not found

ERROR: offer error: retrieval query offer errored: failed to fetch piece to retrieve from: getting pieces for cid bafybeibouhmtaqolriep2asua33chleevguf665tzoxvn3ongmcureudve: getting pieces containing block bafybeibouhmtaqolriep2asua33chleevguf665tzoxvn3ongmcureudve: failed to lookup index for mh 12202ea1d93041cb8a08fd025406f623ac84a9a85f7bb3cbaf56edcd3305489283a9, err: datastore: key not found

ERROR: offer error: retrieval query offer errored: failed to fetch piece to retrieve from: getting pieces for cid bafykbzaceclrlluzhlnoashnedevtfow3cal5ouhdq352ywqqfbq5zwxhfycq: getting pieces containing block bafykbzaceclrlluzhlnoashnedevtfow3cal5ouhdq352ywqqfbq5zwxhfycq: failed to lookup index for mh a0e402209715ae993adae048ed20c95995d6d880beba871c37dd62d081430ee6d7397028, err: datastore: key not found

ERROR: offer error: retrieval query offer errored: failed to fetch piece to retrieve from: getting pieces for cid bafykbzacedikma7b66heawdg5epnjbk76apvbq32fcfyayxpta5re7azje6a4: getting pieces containing block bafykbzacedikma7b66heawdg5epnjbk76apvbq32fcfyayxpta5re7azje6a4: failed to lookup index for mh a0e40220d0a603e1f78e405866e91ed4855ff01f50c37a288b8062ef983b127c19493c0e, err: datastore: key not found

ERROR: offer error: retrieval query offer errored: failed to fetch piece to retrieve from: getting pieces for cid bafykbzacedikma7b66heawdg5epnjbk76apvbq32fcfyayxpta5re7azje6a4: getting pieces containing block bafykbzacedikma7b66heawdg5epnjbk76apvbq32fcfyayxpta5re7azje6a4: failed to lookup index for mh a0e40220d0a603e1f78e405866e91ed4855ff01f50c37a288b8062ef983b127c19493c0e, err: datastore: key not found

ERROR: offer error: retrieval query offer errored: failed to fetch piece to retrieve from: getting pieces for cid bafybeihm57xysyijidtldkujnbmp26dffbpqo562b6zb76gnoyyidp3r4e: getting pieces containing block bafybeihm57xysyijidtldkujnbmp26dffbpqo562b6zb76gnoyyidp3r4e: failed to lookup index for mh 1220ecefef89610940e6b1aa896858fd7865285f0777da0fb21ff8cd763081bf71e1, err: datastore: key not found

ERROR: offer error: retrieval query offer errored: failed to fetch piece to retrieve from: getting pieces for cid bafykbzacec7dfq5iz57zkfdev6b7oitpdtqm2ereq5gl37fprq5eehml7z3za: getting pieces containing block bafykbzacec7dfq5iz57zkfdev6b7oitpdtqm2ereq5gl37fprq5eehml7z3za: failed to lookup index for mh a0e40220be32c3a8cf7f951464af83f7226f1ce0cd1224874cbdfcaf8c3a421d8bfe7790, err: datastore: key not found

ERROR: offer error: retrieval query offer errored: failed to fetch piece to retrieve from: getting pieces for cid bafykbzacebmodhxys5p6xhe7ugeufasyw754ovzbxf6s2ja6gujfrn33fnoru: getting pieces containing block bafykbzacebmodhxys5p6xhe7ugeufasyw754ovzbxf6s2ja6gujfrn33fnoru: failed to lookup index for mh a0e4022058e19ef8975feb9c9fa189428258b7fbc75721b97d2d241e351258b77b2b5d1a, err: datastore: key not found

ERROR: offer error: retrieval query offer errored: failed to fetch piece to retrieve from: getting pieces for cid bafybeibggjou2afuqvtxpsat6dn3wtln7m67wvwphi74xbdzahbg5mobgy: getting pieces containing block bafybeibggjou2afuqvtxpsat6dn3wtln7m67wvwphi74xbdzahbg5mobgy: failed to lookup index for mh 122026325d4d00b4856777c813f0dbbb4d6dfb3dfb56cf3a3fcb847901c26eb1c136, err: datastore: key not found

ERROR: offer error: retrieval query offer errored: failed to fetch piece to retrieve from: getting pieces for cid bafykbzacedbwxebaxggtdlt3lvtmdsceu4xcbn4e3iyr7ffsmkenivqsm4fu6: getting pieces containing block bafykbzacedbwxebaxggtdlt3lvtmdsceu4xcbn4e3iyr7ffsmkenivqsm4fu6: failed to lookup index for mh a0e40220c36b9020b98d31ae7b5d66c1c844a72e20b784da311f94b26288d45612670b4f, err: datastore: key not found

ERROR: offer error: retrieval query offer errored: failed to fetch piece to retrieve from: getting pieces for cid bafykbzacedfdtqhbdyud6id42aibqn4yk22loferwzhwxi4ekauu37cvdoygm: getting pieces containing block bafykbzacedfdtqhbdyud6id42aibqn4yk22loferwzhwxi4ekauu37cvdoygm: failed to lookup index for mh a0e40220ca39c0e11e283f207cd01018379856b4b71491b64f6ba38450294dfc551bb066, err: datastore: key not found

ERROR: offer error: retrieval query offer errored: failed to fetch piece to retrieve from: getting pieces for cid QmNa6QwRLRUyZ3JhUcrgZh9qqJX62o5b6iCGqEDPCSvJdn: getting pieces containing block QmNa6QwRLRUyZ3JhUcrgZh9qqJX62o5b6iCGqEDPCSvJdn: failed to lookup index for mh 122003719d37c2d83d847492b38e67d2a0c25cea857c0ff2e3ae3bf6aa12b97cbef1, err: datastore: key not found

ERROR: offer error: retrieval query offer errored: failed to fetch piece to retrieve from: getting pieces for cid bafykbzacebbp2o7hx6wyqdm3l4xqia77atzr2m7fagbt7awm2hnzbzlbjm4ku: getting pieces containing block bafykbzacebbp2o7hx6wyqdm3l4xqia77atzr2m7fagbt7awm2hnzbzlbjm4ku: failed to lookup index for mh a0e4022042fd3be7bfad880d9b5f2f0403ff04f31d33e501833f82ccd1db90e5614b38aa, err: datastore: key not found

**Comment by cryptowhizzard** [comment]
checker:manualTrigger

**Comment by C00kies77** [comment]
checker:manualTrigger

**Comment by Swift-scouts** [comment]
Can you open this issue please? @Sunnyiscoming
