### ISSUE TITLE
[DataCap Application] <Guoyi Capital> - <Liandong Auto financing>

### ISSUE THREAD

**Issue by yaoyuanww** [filecoin-project/filecoin-plus-large-datasets#1206]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Guoyi Capital
- Website / Social Media: https://www.guoyihuitong.com
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 500TiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 50TiB
- On-chain address for first allocation: f1xppiiufu6rn22zi6d6gq2ivc23updomtl7ainbq

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Guoyi capital, founded in 2015, is a Fintech company focusing on providing cutting edge AI, big data and IOT technology to the auto financing industry. Underneath, Liandong Auto is a comprehensive service brand. By collecting applicant auto info, accident records, maintenance records and mileage records, combined with its own state-of-art risk control model and AI-based IOT system to keep track of the exact location of the vehicle at all time, Liandong auto has expanded into 20 provinces of China with over 70 stores, provided its auto-backed financing products to thousands of end users over the years. It has been a well-known industry leader in the auto financing industry, and formed strategic cooperation with numerous financial institutions, including Huaxia Bank, Zhongbang Bank, Sunshine Insurance Group, China United Property Insurance Company, Suning Finance, Huaan Insurance, Langfang Bank. 
Over the years, Liandong auto has stored massive amount of business-generated data including auto info (both video and pics), IOT data (RFID data) and auto maintenance video data

```

What is the primary source of funding for this project?
```
Guoyi capital 
```

What other projects/ecosystem stakeholders is this project associated with?
```
No
```

## Use-case details

Describe the data being stored onto Filecoin
```
auto info (both video and pics), IOT data (RFID data) and auto maintenance video data
```

Where was the data in this dataset sourced from?
```
our own servers
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://drive.google.com/drive/folders/1qOgVRh6NrAUFWi65bTx4oIZQhSQffj_K?usp=share_link
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes, I confirm this is a public dataset that can be retrieved by anyone on the network with no specific permissions or access rights required
```

What is the expected retrieval frequency for this data?
```
once or twice every 6 months
```

For how long do you plan to keep this dataset stored on Filecoin?
```
2 years
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Asia
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
some offline, some online, depends on the situation
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
I will find SPs who has good reputation in fast retrieval in Filecoin slack
```

How will you be distributing deals across storage providers?
```
I plan to find 4 SPs and distribute the deals equally
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, I have resources available to make deals once I receive Datacap, and no additional support needed right now.
```

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 500PiB

**Expected weekly DataCap usage rate**

> 50TiB

**Client address**

> f1sshymsne7x3cndwflpk57ozerlzkxgzv7aknadq

**Comment by yaoyuanww** [comment]
@simonkim0515 a month has passed, the status has not changed, what is next?

**Comment by yaoyuanww** [comment]
@simonkim0515 please be aware, the On-chain address for first allocation has been corrected, thanks.

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Looking at your application i have some questions:
As you are brand new on Github and have no history of past applications it seems to me that applying for 5PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?

Can you show us visible proof of the size of your data and the storage systems you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230337462961356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!
