### ISSUE TITLE
[DataCap Application] <Guangzhou Niuduxiu Information Technology Co., LTD> - < Art works & NFT>

### ISSUE THREAD

**Issue by Niuduxiu** [filecoin-project/filecoin-plus-large-datasets#1211]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Guangzhou Niuduxiu Information Technology Co., LTD
- Website / Social Media:http://www.niuduxiu.com
                                        WeChat public account：niuduxiu
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):5 PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):100 TiB
- On-chain address for first allocation:f1uc2zciu3n356g2gw36e4itdzqhx726rerpn7tua
- Region: Greater China Region

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Founded in June 2017, Niuduxiu is a platform for cultural and creative company that provides art works display and transformation for college students, young talents and students from art colleges around the world. Creative IP authorization, OEM cooperation, industry -university -research docking service company.In addition, we provide comprehensive copyright blockchain technology on all platforms, record the art works information on the chain, and achieve unable to tampered with the certificate.
```

What is the primary source of funding for this project?
```
Own funds and revenue of the company.
```

What other projects/ecosystem stakeholders is this project associated with?
```
None.
```

## Use-case details

Describe the data being stored onto Filecoin
```
There are mainly two kinds: pictures and videos, Creative by the artist.
```

Where was the data in this dataset sourced from?
```
User-generated images and videos are hosted on our platform.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://drive.google.com/drive/u/2/folders/1nNMa3ggvvgPbMFqnlnHby1dxGCuwi8ZI
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes.
```

What is the expected retrieval frequency for this data?
```
Two months or more.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
We plan to keep this dataset stored for 3-5 years in Filecoin.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
All regions.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Both online and offline.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We need a lot of SPs to choose. In addition, we would also like to find some reputable SPs from BigData Exchange.
```

How will you be distributing deals across storage providers?
```
We will distribute the dataset equally to SPs, and no SP will take up over 20% of the deals.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
We have enough resources and funds to start deals after we receive the DataCap. We would appreciate that the community can response our technical questions in time.
```

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Looking at your application i have some questions:
As you are brand new on Github and have no history of past applications it seems to me that applying for 5PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?

Can you show us visible proof of the size of your data and the storage systems you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230232885049356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Can you show us visible proof of the size of your data and the storage systems you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230232885049356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!

**Comment by Niuduxiu** [comment]
> Dear applicant,
> 
> Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.
> 
> Looking at your application i have some questions: As you are brand new on Github and have no history of past applications it seems to me that applying for 5PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?
> 
> Can you show us visible proof of the size of your data and the storage systems you have there?
> 
> As last question i would like you to fill out [this form](https://form.jotform.com/230232885049356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.
> 
> Thanks!

Hi cryptowhizzard，

First, we will fill out the KYC form for your review.

Our company's GitHub account is newly created for this project. We have learned the relevant knowledge of filecoin, and have done the relevant work of preparing data.

Our company has been committed to building an nft platform in recent years. The source of data is the original works of users, including pictures and videos. After the original works have been reviewed and approved by the China Copyright Protection Center, they will obtain an identity - digital copyright unique identifier (DCI code) and Work registration certificate (electronic version).
As requested, we uploaded some data to Google Drive, https://drive.google.com/drive/u/2/folders/1nNMa3ggvvgPbMFqnlnHby1dxGCuwi8ZI. 
For more original works, please refer to our website: http://www.niuduxiu.com/ 

If any question, please let us know, Thanks.

**Comment by Niuduxiu** [comment]
> Hello @Niuduxiu
> 
> Thanks!
> 
> As stated in the form :
> 
> What is your role in this LDN : I am the data owner and I am responsible for the LDN application's process I am the data preparer and will be responsible for preparing the dataset
> 
> SP disclosure None
> 
> Let me know when you are ready to move forward and when you have the SP's contacted to move forward and email us the SP's to [kyc@dcent.nl](mailto:kyc@dcent.nl) who comply with these rules :
> 
> RULES: In order to be eligible for the Filecoin+ incentive program, which provides 10x the power (QAP) for storing data on the Filecoin network, there are certain rules that must be followed:
> 
> Data must be stored with multiple independent service providers, not just one organization running multiple SPs. Data must be distributed across multiple regions. Using a VPN to fake presence is not allowed. Data must be publicly retrievable for verification that it is being stored as claimed. It is highly recommended to run boost. Data must align with the mission of FIL+, meaning it must be valuable for humanity, whether scientific or unique in some other way. Data must be open and not encrypted. If you wish to encrypt your data, consider applying for the FIL-E program instead. Note: As a data preparer, you are allowed to store one copy yourself for redundancy at the request of the client. However, if your copy is stored in the USA, the other organizations/SPs must be outside your region. Dcent encourages applications with a minimum spread of 2 continents and 3 different organizations.

Hello cryptowhizzard.
We have not yet found SP to be our storage provider，we will be looking for suitable SPs through slack or other.
If community and notaries have quality SP recommendations that would be great.
