### ISSUE TITLE
[DataCap Allocation] - Eystorage Large Dataset Notary Application

### ISSUE THREAD

**Issue by heroapn** [filecoin-project/filecoin-plus-large-datasets#1213]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: WenChu BlockChain
- Website / Social Media: https://www.wenchu.io/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 540TiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100TiB
- On-chain address for first allocation: f1wgijz5c25j6n4fvdwwvf3ggj4htbt7qgpj7zj6q
- Region: Greater China Region

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Eystorage means easy to store data which provides an easy-to-use storage and retrieval service platform for users and developers of distributed storage. The backend stores data based on distributed storage networks such as IPFS, GlusterFS, web3.storage, Filecoin and https://github.com/filecoin-project/devgrants/issues/430, and provides storage for developers through OpenAPI interface. The front end provides a visual interface for users to store and retrieve data.
```

What is the primary source of funding for this project?
```
Funding project of the filecoin foundation.
```

What other projects/ecosystem stakeholders is this project associated with?
```
 Filecoin foundation
```

## Use-case details

Describe the data being stored onto Filecoin
```
vps template ,iso file and machine log file.

```

Where was the data in this dataset sourced from?
```
 our cooperative partner 

```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://drive.google.com/file/d/1TI-HzvT2lx9_xEvZYI9EoBu_GeXYRTzU/view?usp=share_link
https://drive.google.com/file/d/1ZI0N9ptGMfHDFX04BPQBcvG4GA9q_Qb2/view?usp=share_link
https://drive.google.com/file/d/1fbQ2qsBnuToDRthkhaLRathQUB0HG7PS/view?usp=share_link

```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes.
```

What is the expected retrieval frequency for this data?
```
3 to 5 times a year.

```

For how long do you plan to keep this dataset stored on Filecoin?
```
permanently. 

```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
China,Asia
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
We plan to transfer data offline.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We're selecting the SPs with high reputation on slack  . They have the ability to store deals at a very fast pace and a high success rate.

```

How will you be distributing deals across storage providers?
```
We try to follow the rule about LDN. Under 25% to per sp.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes，we have enough funding and resources to start making deals.
```

**Comment by heroapn** [comment]
@galen-mcandrew @raghavrmadya @jbenet @Kevin-FF-USA  We have sent presentation video on Governance Call , when will our 540TiB datacap be approved.Thanks.

**Comment by heroapn** [comment]
Waiting day and night for team approval. @Kevin-FF-USA

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 540TiB

**Expected weekly DataCap usage rate**

> 100TiB

**Client address**

> f1wgijz5c25j6n4fvdwwvf3ggj4htbt7qgpj7zj6q

**Comment by heroapn** [comment]
Would you please tell me when will our 27TiB datacap be signed? THANKS @simonkim0515

**Comment by heroapn** [comment]
Would you please tell me when will our 27TiB datacap be signed? THANKS @simonkim0515 @Kevin-FF-USA

**Comment by psh0691** [comment]
@heroapn 
How much data do you currently have?
Are there any storage providers involved?

**Comment by psh0691** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb2oehbr7cyhodkvvyjzya4mrvblz2ybuobxcgyejxmd4fobuqdvi 
#### Address 
> f1wgijz5c25j6n4fvdwwvf3ggj4htbt7qgpj7zj6q
#### Datacap Allocated
> 27.00TiB
#### Signer Address
> f1qdko4jg25vo35qmyvcrw4ak4fmuu3f5rif2kc7i
#### Id
> 6e4d3f75-2fad-4b19-9d8a-1d23aa33d562
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb2oehbr7cyhodkvvyjzya4mrvblz2ybuobxcgyejxmd4fobuqdvi

**Comment by kernelogic** [comment]
The plan looks OK to me. Will look again at next allocation

**Comment by kernelogic** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedd2nvayxehshktgxeljmoatlnnxlsbathbihpz4kddkbftnogt4w 
#### Address 
> f1wgijz5c25j6n4fvdwwvf3ggj4htbt7qgpj7zj6q
#### Datacap Allocated
> 27.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### Id
> 6e4d3f75-2fad-4b19-9d8a-1d23aa33d562
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedd2nvayxehshktgxeljmoatlnnxlsbathbihpz4kddkbftnogt4w

**Comment by IreneYoung** [comment]
> Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this.
ISO-https://ipfs.io/ipfs/QmQLp9uKcjfFZNCATfECip2F8SY5sSB7QVMFbmHy4WwQcF
vmdk: https://ipfs.io/ipfs/QmPLtdoNmBB4ciBZLXBypNhcEAXkCij5Tyvj4jrgrCE7NQ

The data sample is unavailable.

**Comment by heroapn** [comment]
The first round of distribution has ended, and we have made rectifications for the contents of the report, as follows：
1.https://filplus.d.interplanetary.one/clients/f01986242/breakdown
![图片](https://user-images.githubusercontent.com/33470476/209607194-4dd5a560-e629-42e8-8902-1d5d0a468db1.png)
DC is evenly distributed among the 5 SPs。

2.The report shows that the address is not public, we have asked the SP to declare the address, and the SP distribution is shown in the table。
![图片](https://user-images.githubusercontent.com/33470476/209607435-b0fa46d6-3676-4be8-acf0-a8aab77a712f.png)

3.Regarding the question of the repetition rate, since it is the first distribution, we have problems in the distribution, which makes the repetition rate not meet the requirements a little bit, and we promise that such problems will not occur again in the second distribution.

**Comment by Joss-Hua** [comment]
checker:manualTrigger

**Comment by herrehesse** [comment]
Dear Applicant,

Due to the increased amount of erroneous/wrong Filecoin+ data recently, on behalf of the entire community, we feel compelled to go deeper into datacap requests. Hereby to ensure that the overall value of the Filecoin network and Filecoin+ program increases and is not abused.

Please answer the questions below as comprehensively as possible.

**Customer data**

- Could you demonstrate exactly how and to what extent customer contact occurred? 

We expect that for the onboarding of customers with the scale of an LDN there would have been at least multiple email and perhaps several chat conversations preceding it. A single email with an agreement does not qualify here.

- Did the customer specify the amount of data involved in this relevant correspondence?

- Why does the customer in question want to use the Filecoin+ program? 

_Should this only be soley for acquiring datacap this is of course **out of the question**. The customer must have a legitimate reason for wanting to use the Filecoin+ program which is intended as a program to store useful and public datasets on the network._ 

- Why is the customer data considered Filecoin+ eligible?

_(As an intermediate solution Filecoin offers the FIL-E program or the glif.io website for business datasets that do not meet the requirements for a Filecoin+ dataset)_


**Files and Processing**

- Could you please demonstrate to us how you envision processing and transporting the customer data in question to any location for preparation?
- Would you demonstrate to us that the customer, the preparer and the intended storage providers all have adequate bandwidth to process the set with its corresponding size?
- Would you tell us how the data set preparer takes into account the prevention of duplicates in order to prevent data cap abuse?


Hopefully you understand the caution the overall community has for onboarding the wrong data. We understand the increased need for Filecoin+, however, we must not allow the program to be misused. Everything depends on a valuable and useful network, let's do our best to make this happen. Together.

**Comment by herrehesse** [comment]
@heroapn please explain to me why every miner has over or near 50% duplicates?

**Comment by heroapn** [comment]
> @heroapn please explain to me why every miner has over or near 50% duplicates?

Hello, for data security, we saved 2 copies for each SP, which caused the repetition rate to fail to meet the requirements. We have realized this problem and made the repetition rate meet the requirements in the second round of allocation.

**Comment by heroapn** [comment]
> > Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this.
> > ISO-https://ipfs.io/ipfs/QmQLp9uKcjfFZNCATfECip2F8SY5sSB7QVMFbmHy4WwQcF
> > vmdk: https://ipfs.io/ipfs/QmPLtdoNmBB4ciBZLXBypNhcEAXkCij5Tyvj4jrgrCE7NQ
> 
> The data sample is unavailable.

hi,we have updated the link.

**Comment by herrehesse** [comment]
@heroapn Thank you for your response. Appreciate the clarity and good luck with the next batch!

**Comment by Joss-Hua** [comment]
The client has improved. Supports this round.

**Comment by Joss-Hua** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebmjxpcfcemssm2yablyuebpwy6qvkl2eoml2ggq7tix5c3cttvdu 
#### Address 
> f1wgijz5c25j6n4fvdwwvf3ggj4htbt7qgpj7zj6q
#### Datacap Allocated
> 108.00TiB
#### Signer Address
> f1tfg54zzscugttejv336vivknmsnzzmyudp3t7wi
#### Id
> da131fd0-c867-4ac4-878c-040b5de3d171
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebmjxpcfcemssm2yablyuebpwy6qvkl2eoml2ggq7tix5c3cttvdu

**Comment by liyunzhi-666** [comment]
I hope the client @heroapn  will make improvements in the next round.
I would like to support this round

**Comment by liyunzhi-666** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecvp65ioiwgggsaockfrbsmho7kbwvtb4b466wmy4mf764tmfbssa 
#### Address 
> f1wgijz5c25j6n4fvdwwvf3ggj4htbt7qgpj7zj6q
#### Datacap Allocated
> 108.00TiB
#### Signer Address
> f1pszcrsciyixyuxxukkvtazcokexbn54amf7gvoq
#### Id
> da131fd0-c867-4ac4-878c-040b5de3d171
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecvp65ioiwgggsaockfrbsmho7kbwvtb4b466wmy4mf764tmfbssa

**Comment by heroapn** [comment]
> I hope the client @heroapn will make improvements in the next round. I would like to support this round

Thanks for your support.

**Comment by cryptowhizzard** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceddvwhy4rhh4e2hu2z27yhulzm2tncyjm7v3dxi2xppi5a2uy4j4y 
#### Address 
> f1wgijz5c25j6n4fvdwwvf3ggj4htbt7qgpj7zj6q
#### Datacap Allocated
> 216.00TiB
#### Signer Address
> f1krmypm4uoxxf3g7okrwtrahlmpcph3y7rbqqgfa
#### Id
> 670fccdc-b0ac-4626-9ddb-e8f4dffaa793
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceddvwhy4rhh4e2hu2z27yhulzm2tncyjm7v3dxi2xppi5a2uy4j4y

**Comment by phantom-rabbit** [comment]
> 1. checker:manualTrigger

checker:manualTrigger

**Comment by heroapn** [comment]
checker:manualTrigger

**Comment by heroapn** [comment]
checker:manualTrigger

**Comment by heroapn** [comment]
checker:manualTrigger

**Comment by heroapn** [comment]
checker:manualTrigger

**Comment by heroapn** [comment]
> @heroapn dear applicant,
> 
> Looking at the CID report it seems that a lot of files are duplicated. Can you explain how this happend and how you are going to prevent this in the future from happening again?
> 
> ⚠️ 43.72% of total deal sealed by [f01915133](https://filfox.info/en/address/f01915133) are duplicate data. ⚠️ 70.35% of total deal sealed by [f01915188](https://filfox.info/en/address/f01915188) are duplicate data. ⚠️ 48.26% of total deal sealed by [f01915135](https://filfox.info/en/address/f01915135) are duplicate data. ⚠️ 23.68% of total deal sealed by [f07830](https://filfox.info/en/address/f07830) are duplicate data. ⚠️ 23.45% of total deal sealed by [f020522](https://filfox.info/en/address/f020522) are duplicate data.
Hi, the distribution of this round has not been completed yet. We have revised the distribution plan and believe that the repetition rate will meet the requirements. Thanks again for your reminder

**Comment by herrehesse** [comment]
@heroapn I completely understand, looking forward to the next CID reports.
You are talking about distribution, but I am talking about duplications. Can you or the data preparer please explain to my how so much duplicate data was stored and how to prevent this from happening in the future?

**Comment by phantom-rabbit** [comment]
manualTrigger

**Comment by phantom-rabbit** [comment]
checker:manualTrigger

**Comment by heroapn** [comment]
checker:manualTrigger

**Comment by heroapn** [comment]
checker:manualTrigger

**Comment by phantom-rabbit** [comment]
checker:manualTrigger

**Comment by BDEio** [comment]
@heroapn Hi! Congratulations on your DataCap approval！
BDE is a trusted deals auction house helping you to get paid storing your data with reliable storage providers. If you need any help, please get in touch.

**Comment by heroapn** [comment]
checker:manualTrigger

**Comment by heroapn** [comment]
checker:manualTrigger

**Comment by cryptowhizzard** [comment]
Hello @heroapn 

I have been checking to do some deal retrievals but it seems that your providers do not support them.

For example deal id 21141743 results in:
retrieve: offer error: retrieval query offer errored: failed to fetch piece to retrieve from: getting pieces for cid QmeGWs7HK3pXnsWV2DfyxiFJtUZ3Qn8qrjuG2Zcd7ua5HQ: getting pieces containing block QmeGWs7HK3pXnsWV2DfyxiFJtUZ3Qn8qrjuG2Zcd7ua5HQ: failed to lookup index for mh 1220ecabcc26413575bae99dbf654e5065caebbfbbb9096f2ce0d1485a863a61a6ef, err: datastore: key not found

Providers below give context errors and don't allow retrieval at all.
f01852677 | 8404 | context canceled
f01852023 | 8394 | context canceled

This is problematic since the deals need to be available for retrieval in the FIL+ program and this indicates that the storage is not going well. I doubt these deals will become available in the near future unless your SP's start using boost and do regular retrieval tests.

Can you please talk to the SP's you do business with and get them on the right track?

**Comment by phantom-rabbit** [comment]
checker:manualTrigger

**Comment by cryptowhizzard** [comment]
Hello,

None of the content of this LDN is retrievable. This is against the Fil+ guidelines.

Please have this resolved before we can grant any new datacap.

[client-f01986242.csv](https://github.com/filecoin-project/filecoin-plus-large-datasets/files/10421053/client-f01986242.csv)

**Comment by heroapn** [comment]
> Hello,
> 
> None of the content of this LDN is retrievable. This is against the Fil+ guidelines.
> 
> Please have this resolved before we can grant any new datacap.
> 
> [client-f01986242.csv](https://github.com/filecoin-project/filecoin-plus-large-datasets/files/10421053/client-f01986242.csv)

Hi, we will ask SP to fix this issue as soon as possible.

**Comment by heroapn** [comment]
checker:manualTrigger

**Comment by heroapn** [comment]
lotus client retrieve --provider f01915188 --from f1wgijz5c25j6n4fvdwwvf3ggj4htbt7qgpj7zj6q bafykbzacedj6k4qackk5gubjq3wz2ppwqfjxi4coacn6svx25mhlgbtlqrptw  dc.car
![图片](https://user-images.githubusercontent.com/33470476/216526385-530430a3-3ff4-45e3-92d6-8cdea75bceb5.png)
SP has fixed the retrievals  function.
SP has fixed the detection function

**Comment by cryptowhizzard** [comment]
Feb  3 12:18:03 proposals dealscanner-f01986242-f01915188: Recv 0 B, Paid 0 FIL, Open (New), 0s [1675293168511471417|0]
Feb  3 12:18:03 proposals dealscanner-f01986242-f01915188: Recv 0 B, Paid 0 FIL, DealProposed (WaitForAcceptance), 3ms [1675293168511471417|0]
Feb  3 12:18:04 proposals dealscanner-f01986242-f01915188: Recv 0 B, Paid 0 FIL, DealAccepted (Accepted), 298ms [1675293168511471417|0]
Feb  3 12:18:04 proposals dealscanner-f01986242-f01915188: Recv 0 B, Paid 0 FIL, PaymentChannelSkip (Ongoing), 299ms [1675293168511471417|0]

After this it goes stale for hours.

**Comment by heroapn** [comment]
We consulted the SP, because they did not save the unseal file, so the retrieval requires an unseal process, and involves machine performance, these factors make the retrieval time-consuming.

**Comment by cryptowhizzard** [comment]
Hi @heroapn 

I do understand. However, this is against FIL+ rules. Readily retrieval means that files must be available to be served.

I would like to request that the files will be unsealed ( everything ) and available for retrieval to enable us to do due diligence and check the data before new datacap will be signed.

**Comment by heroapn** [comment]
@cryptowhizzard Hi,SP has notified us that the retrieval function has been fixed. Please check.

**Comment by heroapn** [comment]
@cryptowhizzard If you have any questions please let me know.

**Comment by heroapn** [comment]
@cryptowhizzard hi,have you checked? Do you need any assistance?

**Comment by heroapn** [comment]
@cryptowhizzard any feedback?

**Comment by heroapn** [comment]
I post a review request on channel,if any notary have any question please let me know.

**Comment by zcfil** [comment]
clicked on the link and found that there was only a small amount of video data. Can you provide more data samples?

**Comment by heroapn** [comment]
@zcfil data samples are as below:
Centos 8.4 vmdk image:https://drive.google.com/file/d/1nXTrThLP4um3EvLqCrIZ-RT1Ve-mbjbA/view?usp=sharing
Centos 8.5 vmdk image:https://drive.google.com/file/d/1b9UQNLBA-5G0155c_Y3BsB9DeECJANxn/view?usp=sharing
Centos 9 vmdk image: https://drive.google.com/file/d/1HxkXW4ccrPzcizbpkBGMiZlJ0k9M05qg/view?usp=sharing
Centos 8.2 vmdk image: https://drive.google.com/file/d/1jXvTEakPRVKYljxnCA_gtp2e87smF6PV/view?usp=sharing
please check.

**Comment by zcfil** [comment]
checker:manualTrigger

**Comment by zcfil** [comment]
Hi @heroapn 
Thank you for providing more data and confirming that it has been approved

**Comment by zcfil** [comment]
<img width="1489" alt="273" src="https://user-images.githubusercontent.com/45065975/229704295-41134583-96c1-404a-b58e-491c7f03141b.png">
Dear @raghavrmadya @Kevin-FF-USA @galen-mcandrew 
I'm having some issues with signing, check it out.

**Comment by heroapn** [comment]
@zcfil Thank you for your diligent work. May I ask if you can sign now?

**Comment by zcfil** [comment]
I just tried, but it still doesn't work. I have already provided feedback to the community staff. Respecting Good News

**Comment by heroapn** [comment]
Ok, I will also follow up on this matter.

**Comment by heroapn** [comment]
@zcfil Hi notary, any update?

**Comment by heroapn** [comment]
@zcfil hi,any feedback?

**Comment by heroapn** [comment]
@fabriziogianni7 Could you please find out what the problem is and fix it

**Comment by heroapn** [comment]
OK,waiting for your good news.

**Comment by zcfil** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebyhvqrgjvbliz2o7z7rizoq7qt6aglh6k4ddgd46in6hmt64yo54 
#### Address 
> f1wgijz5c25j6n4fvdwwvf3ggj4htbt7qgpj7zj6q
#### Datacap Allocated
> 216.00TiB
#### Signer Address
> f1cjzbiy5xd4ehera4wmbz63pd5ku4oo7g52cldga
#### Id
> 670fccdc-b0ac-4626-9ddb-e8f4dffaa793
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebyhvqrgjvbliz2o7z7rizoq7qt6aglh6k4ddgd46in6hmt64yo54

**Comment by zcfil** [comment]
> OK,waiting for your good news.
@heroapn With the efforts of community workers, the problem has been repaired. Support this proposal

**Comment by zcfil** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaw6shfear3d5ruqcbtibopz5ado5pooorqryveoke3tsh5oow7my 
#### Address 
> f1wgijz5c25j6n4fvdwwvf3ggj4htbt7qgpj7zj6q
#### Datacap Allocated
> 216.00TiB
#### Signer Address
> f1cjzbiy5xd4ehera4wmbz63pd5ku4oo7g52cldga
#### Id
> 670fccdc-b0ac-4626-9ddb-e8f4dffaa793
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaw6shfear3d5ruqcbtibopz5ado5pooorqryveoke3tsh5oow7my

**Comment by heroapn** [comment]
Thanks for your effort to move this forward,appreciate it.

**Comment by Joss-Hua** [comment]
<img width="660" alt="image" src="https://user-images.githubusercontent.com/75723122/233815985-b54b8092-260e-4113-b43a-be11db6d83c7.png">

**Comment by Joss-Hua** [comment]
Please increase data replicas and improve dispersion

**Comment by heroapn** [comment]
OK, the distribution will be improved this round.

**Comment by laurarenpanda** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceah76jl2ruinpisttwido6hlzem6h3bmgnanu6cn2wr2osco65bz2 
#### Address 
> f1wgijz5c25j6n4fvdwwvf3ggj4htbt7qgpj7zj6q
#### Datacap Allocated
> 216.00TiB
#### Signer Address
> f1bp3tzp536edm7dodldceekzbsx7zcy7hdfg6uzq
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceah76jl2ruinpisttwido6hlzem6h3bmgnanu6cn2wr2osco65bz2

**Comment by heroapn** [comment]
checker:manualTrigger

**Comment by Fatman13** [comment]
checker:manualTrigger

**Comment by Fatman13** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceczcbfdgrvbenlcov47fvcwibbnpkrvf43nwyj65kouc26ik5gxtw 
#### Address 
> f1wgijz5c25j6n4fvdwwvf3ggj4htbt7qgpj7zj6q
#### Datacap Allocated
> 189.00TiB
#### Signer Address
> f1j3u7crhjzwb2cj5mq7vodlt4o66yoyci7lhcauy
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceczcbfdgrvbenlcov47fvcwibbnpkrvf43nwyj65kouc26ik5gxtw

**Comment by Fatman13** [comment]
Reached out by the applicant on WeChat. Met personally in fil-hk. Discussed plans on how they could improve on the CID checker warnings.

**Comment by destor2023** [comment]
checker:manualTrigger

**Comment by destor2023** [comment]
@heroapn Can you explain why CID checker showed that 38.44% of your data was stored in less than 4 copies?

**Comment by heroapn** [comment]
@destor2023 Because data is transported from one SP to another, as you can see, the number of copies is continuously increasing. I believe the percentage of warnings will also decrease in this round.

**Comment by cryptowhizzard** [comment]
Hi,

I don't want to spoil , but the SP's do not support retrieval so replication from one SP to another seems not possible. Or do you mean that you are shipping harddrives from one SP to another?

>>
 Error: Failed to retrieve content with candidate miner f07786: data transfer failed: deal errored: getting pieces for cid bafykbzacedzf36xhp35uoobqprdohwpj5mkvel7k2qame73ooyv46tiqqyjja: getting pieces containing block bafykbzacedzf36xhp35uoobqprdohwpj5mkvel7k2qame73ooyv46tiqqyjja: failed to lookup index for mh a0e40220f25dfae77efb4738307c46e3d9e9eb15522fead400c27f6e762bcf4d10861290, err: datastore: key not found
Error: Failed to retrieve content with candidate miner f020522: data transfer failed: deal errored: getting pieces for cid bafykbzacea7ydvz4jzvqpmuiq7r6vcbpaof4n4r472fo2einclvdwc2rewofw: getting pieces containing block bafykbzacea7ydvz4jzvqpmuiq7r6vcbpaof4n4r472fo2einclvdwc2rewofw: failed to lookup index for mh a0e402203f81d73c4e6b07b28887e3ea882f038bc6f23cfe8aed110d12ea3b0b51259c5b, err: datastore: key not found
>>

<img width="1107" alt="Scherm­afbeelding 2023-05-06 om 10 53 12" src="https://user-images.githubusercontent.com/36404435/236614002-d3f34b0c-6fa9-4413-8e52-b45e8dcfbd22.png">

**Comment by heroapn** [comment]
@cryptowhizzard 
 Thank you for your reminder. The retrieval function is already in communication with SPs for repair. As mentioned in the application form, data is transfer offline. If there is any latest progress, I will synchronize with you in a timely manner.

**Comment by cryptowhizzard** [comment]
@heroapn 

Will you let us know then when it is repaired? 

If you want you can make the CID's available and carfiles of the files i tried to retrieve ( see above ) with a download link. When i can verify the data and match the CID i am willing to support. Otherwise we can't do due diligence and verify what you are storing.

**Comment by heroapn** [comment]
![图片](https://user-images.githubusercontent.com/33470476/236721863-9702ab25-15b2-4234-8b28-a71dd4c11ef7.png)
@cryptowhizzard 
Hi, SP replied that the retrieval function has been repaired, I tried it and it works, please check and download the data for verification.

**Comment by heroapn** [comment]
@cryptowhizzard  Hi, have you checked and do you need any assistance?

**Comment by destor2023** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced5rdtqeenewpr7lw3a2b4aus23anr64uu67cnyza3xqkcwd3ydjm 
#### Address 
> f1wgijz5c25j6n4fvdwwvf3ggj4htbt7qgpj7zj6q
#### Datacap Allocated
> 189.00TiB
#### Signer Address
> f1yh6q3nmsg7i2sys7f7dexcuajgoweudcqj2chfi
#### Id
> 0d82f68c-2292-4e7a-94ff-6c4781ca0eb6
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced5rdtqeenewpr7lw3a2b4aus23anr64uu67cnyza3xqkcwd3ydjm
