### ISSUE TITLE
[DataCap Allocation] - Ogcloud

### ISSUE THREAD

**Issue by Frank-jinxin** [filecoin-project/filecoin-plus-large-datasets#1215]
---
name: Large Dataset Notary application
about: Clients should use this application form to request a DataCap allocation via a LDN for a dataset
title: "Ogcloud"
labels: 'application, Phase: Diligence'
assignees: ''

---
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Ogcloud
- Website / Social Media: www.ogcloud.com
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5 PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100 TiB
- On-chain address for first allocation: f1e74m7phfpdflpnoeispqwowwmvceag6wf75hdfy
- Region: Greater China Region

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
OgCloud is a cloud computing service brand independently developed by Tianyun Technology.

In 2019, Tianyun Technology made a breakthrough and proposed the "dual-engine overseas" strategy of "enterprise IT overseas matrix + cross-border overseas matrix", investing the resources and technical capabilities accumulated by international ICT for many years into the research and development of SaaS cloud platform, focusing on Pound has built a cloud computing service brand - OgCloud, and has integrated more than 30 data centers around the world, covering the United States, the United Kingdom, Japan, South Korea, Indonesia, Singapore and other countries and regions, providing services for global e-commerce, games, finance and other industries. Cost-effective SaaS cloud service is the industry's leading one-stop cloud computing service platform for enterprises to go overseas.

Since the first year of overseas social e-commerce, OgCloud has seized the cross-border e-commerce market. Its international cloud mobile phone OgPhone, global live broadcast room OgLive, cross-border cloud computer OgVPS, cross-border workbench OgDesk, global application acceleration OgIC and other popular products, It can deeply empower cross-border e-commerce customers, realize global one-click shop opening, off-site drainage, and live broadcast delivery for cross-border e-commerce, accurately deploy overseas marketing markets, and help enterprises to start their overseas business safely.

```

What is the primary source of funding for this project?
```
From the our company funds
```

What other projects/ecosystem stakeholders is this project associated with?
```
None
```

## Use-case details

Describe the data being stored onto Filecoin
```
Our customer types are rich, and the types of data that need to be stored are also comprehensive, including but not limited to: videos, documents, photos, voices...
```

Where was the data in this dataset sourced from?
```
We have more than 36 public cloud node, the access using the enterprise customers more than 50,000 in the use of our host of cloud, the cloud backup, cloud phone, studio, etc. There are produce a large number of users need to store data files.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
We are the background management, and the front display needs to go through the customer portal.
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
yes
```

What is the expected retrieval frequency for this data?
```
Mainly used for backup, check 1-2 times a month regularly
```

For how long do you plan to keep this dataset stored on Filecoin?
```
We plan to keep most of the data permanently, some data may be replaced according to demand
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
There are nodes all over the world. At present, we hope to be in Asia.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
It can be used in offline, physical transportation, Internet transmission, etc
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We have a reputable partner on Filcoin and can provide good and stable support. At the same time, we will also seek more high-quality, large-scale and high reputation partners.we will also actively use existing tools and platforms to improve participation and retrieval.
```

How will you be distributing deals across storage providers?
```
It will be divided into several parts.
1. It is carried out with large-scale cooperative objects through physical transportation.
2. Small scale storage through the Internet.
It is handled in a diversified way to ensure stability and redundancy.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
We have mastered sufficient funds and technology to achieve good operation.
```

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 100TiB

**Client address**

> f1e74m7phfpdflpnoeispqwowwmvceag6wf75hdfy

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Looking at your application i have some questions:
As you are brand new on Github and have no history of past applications it seems to me that applying for 5PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?

Can you show us visible proof of the size of your data and the storage systems you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230232885049356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!
