### ISSUE TITLE
[DataCap Application] Cloudssss

### ISSUE THREAD

**Issue by Michele37** [filecoin-project/filecoin-plus-large-datasets#1218]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Cloudssss
- Website / Social Media:https://www.cloudssss.com/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):200TiB
- On-chain address for first allocation:f1j43vxmv63ghh7g773h4fqdy3rqfymnxo22bh2ii

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
All front-line service personnel have passed the cloud practitioner examination certification of Tencent Cloud, and the technical architects have the TCP professional architect certificate issued by Tencent. We provide users with cloud consulting, architecture design, cloud migration, operation and maintenance management, cloud product development and integration services. We are honored to win the Best Expansion Award at the annual Tencent Cloud Channel Conference in 2011.
```

What is the primary source of funding for this project?
```
Business income.
```

What other projects/ecosystem stakeholders is this project associated with?
```
No.
```

## Use-case details

Describe the data being stored onto Filecoin
```
The data is videos which are from live shows.
```

Where was the data in this dataset sourced from?
```
From our live video support services. 
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
Dataset link:
https://c.gmx.com/@1162658847450465225/urj6xquqTRq-sZRPfja7uw
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes, we confirm it.
```

What is the expected retrieval frequency for this data?
```
We'll retrieve these data once a year.It is cold data.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
2 years.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
I plan choose North America, Korea, Japan.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Yes, offline transfer is our first choice. We have 600TiB relevant data to store and we  prepare about 50 hard disks for transfer.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
Github and slack can help us find more sp with reputation and enough resource. We'd like to contact sps from different regions for distributed storage.
```

How will you be distributing deals across storage providers?
```
We will distribute more deals to experienced sp while ensuring that the rules in community are followed.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes.
```

**Comment by Michele37** [comment]
![cloudsss](https://user-images.githubusercontent.com/117341628/204707068-21d5c832-db2a-484c-b041-13966fe1e0d8.png)
Hi community, I've sent the email. Can my application be approved? @raghavrmadya @simonkim0515

**Comment by Sunnyiscoming** [comment]
https://c.gmx.com/@1162658847450465225/urj6xquqTRq-sZRPfja7uw
The link of data samples you provided is not accessible. Can you check that?

**Comment by Michele37** [comment]
Hello Sunny, I have checked my link and I can open it. Can you please try it again? If you still meet some problem about this link, I'm willing to help solve it. Thank you for your notice!

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 200TiB

**Client address**

>f1j43vxmv63ghh7g773h4fqdy3rqfymnxo22bh2ii

**Comment by 1ane-1** [comment]
Can you provide more data sample ?

**Comment by Michele37** [comment]
https://c.gmx.com/@1162658847450465225/urj6xquqTRq-sZRPfja7uw
@1ane-1 Hi, I've uploaded the dataset which is 2GB. You can start viewing this sample. Thank you!

**Comment by swatchliu** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebecnzp6k5xv77owi6p267ed7qmcwlsysphzykrilatxumcmuuy3e 
#### Address 
> f1j43vxmv63ghh7g773h4fqdy3rqfymnxo22bh2ii
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1yh6q3nmsg7i2sys7f7dexcuajgoweudcqj2chfi
#### Id
> 5cb18f5e-766b-47d4-ac01-23a17d5dc4d2
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebecnzp6k5xv77owi6p267ed7qmcwlsysphzykrilatxumcmuuy3e

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Looking at your application i have some questions:
As you are brand new on Github and have no history of past applications it seems to me that applying for 5PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?

Can you show us visible proof of the size of your data and the storage systems you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230232885049356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!

**Comment by BlockMakeronline** [comment]
Where is your main operation area?
What is the composition of your data? How many copies do you plan to store?
Could you please provide the SP list?

**Comment by Michele37** [comment]
Hello @BlockMakeronline, our main operation area is Shanghai, China. Our data is videos about our live show service. 9 copies we plan to store and more than 600 TiB data we have.
Sure! But I can't list every SP to you until I identify who to work with. I will select SP cautiously and observe the rules. Please approve our application, thank you!

**Comment by BlockMakeronline** [comment]
Glad to receive your reply. 
It's a great project. I'd like to sign for you.

**Comment by BlockMakeronline** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedf4jceklyhsqjeoyicz52plfd4i5lzmtfeww7zs7sykfbueb3342 
#### Address 
> f1j43vxmv63ghh7g773h4fqdy3rqfymnxo22bh2ii
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1o3twrcpwjtpcd4q36lpq4qmy2qfbgtyy5h6tsty
#### Id
> 5cb18f5e-766b-47d4-ac01-23a17d5dc4d2
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedf4jceklyhsqjeoyicz52plfd4i5lzmtfeww7zs7sykfbueb3342

**Comment by Michele37** [comment]
Got it. Keep open.

**Comment by Michele37** [comment]
Got it. Keep open.

**Comment by clriesco** [comment]
Removed stale label and reopened issue :)

**Comment by Michele37** [comment]
Yes.
