### ISSUE TITLE
[DataCap Application] <Nantong Chunna Textile Co., Ltd> - <Resubmit #165>

### ISSUE THREAD

**Issue by Corerae** [filecoin-project/filecoin-plus-large-datasets#1219]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name:Nantong Chunna Textile Co., Ltd 
- Website / Social Media:https://mall.jd.com/index-739308.html
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):4.87PiB 
- Weekly allocation of DataCap requested (usually between 1-100TiB):500TiB
- On-chain address for first allocation: f1aqbilzkvvtggxd4kui5zamwqrdpfzilbtmg5kdi

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Nantong Chunna Textile Co., Ltd. was founded in 1998, mainly engaged in textiles, including clothes and bedding. Its brands include mankton home textile, which has developed into a home textile chain business group, mainly engaged in high-grade home textile, and most of the consumer groups are high-consumption urban people.
```

What is the primary source of funding for this project?
```
Large sales of textile goods.
```

What other projects/ecosystem stakeholders is this project associated with?
```
It has nothing to do with other projects.
```

## Use-case details

Describe the data being stored onto Filecoin
```
Mankton home textile, a subsidiary of Nantong Chunna Textile Co., Ltd., has a flagship store on JD.com, a comprehensive online shopping mall in China. Therefore, a large amount of data will be generated in the process of online store operation and sales, including commodity quotation sheet, detail page, original pictures and videos of commodities, live recording frequency of commodities when they are on the shelf, commodity evaluation, etc. The main forms of our data are pictures, texts and videos. Our data is open source and will not cause disputes. We hope to provide services and help for our data storage through Filecoin.
```

Where was the data in this dataset sourced from?
```
Publicly available data generated during brand operations and merchandise sales.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
Link：https://pan.baidu.com/s/14V2yA_XukKoG9TPlnsxK_g
Extraction code：096a
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Just open the link. There is no restriction on the use of these data.
```

What is the expected retrieval frequency for this data?
```
Anyone who is interested in our brand or products can open and view it.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
Two and a half years.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Asia.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
We will upload our data to the network server, communicate with the storage provider, download and propose offline transactions.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We are willing to cooperate with any miner with storage conditions and experience.
```

How will you be distributing deals across storage providers?
```
We will use IPFS distributed storage to fairly distribute to miners.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
We have enough funds and resources.
```

**Comment by maweis1981** [comment]
How r u, Fellow.

**Comment by Corerae** [comment]
@simonkim0515 Hello, this is my resubmitted application. The previous Github account cannot be logged in. Please help me review it again.

**Comment by Sunnyiscoming** [comment]
What's the relationship between you and the organization?

https://filplus.d.interplanetary.one/clients/f01724439/breakdown
Are these SPs you cooperated suppprtive of data retrievaling?

According to the business license published on the site you provided. The organization name is 南通竞天国际贸易有限公司, not  Nantong Chunna Textile Co., Ltd, Can you explain about that?
https://mall.jd.com/showLicence-739308.html

**Comment by Corerae** [comment]
1.I work for Nantong Chunna.
2.Yes.
3.The shareholder（LIANG CHEN） of Nantong Jingtian is the legal person of Nantong Chunna. The shareholder is the actual controller of Nantong Jingtian and Chunna.

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 4.87PiB

**Expected weekly DataCap usage rate**

> 500TiB

**Client address**

> f1aqbilzkvvtggxd4kui5zamwqrdpfzilbtmg5kdi

**Comment by newwebgroup** [comment]
About KYC&KYB
1：Could you send an email to [filplus-app-review@fil.org](mailto:filplus-app-review@fil.org) ？ 
> The content should include the number of the LDN application. If possible, please attach copies of the business license and other valid certificates

2：Can you provide more detailed information about other storage providers participated in this program, such as you can list SPs you have contacted with at present?
3.How large is your existing dataset? How much is the data growth per month?

**Comment by filplus-checker** [comment]
## DataCap and CID Checker Report[^1]
 - Organization: `Nantong Chunna Textile Co., Ltd`
 - Client: `f1aqbilzkvvtggxd4kui5zamwqrdpfzilbtmg5kdi`
### Storage Provider Distribution
The below table shows the distribution of storage providers that have stored data for this client.

If this is the first time a provider takes verified deal, it will be marked as `new`.

For most of the datacap application, below restrictions should apply.
 - Storage provider should not exceed 25% of total datacap.
 - Storage provider should not be storing duplicate data for more than 20%.
 - Storage provider should have published its public IP address.
 - All storage providers should be located in different regions.

⚠️ [f0522948](https://filfox.info/en/address/f0522948) has sealed 27.97% of total datacap.

⚠️ 39.34% of total deal sealed by [f0522948](https://filfox.info/en/address/f0522948) are duplicate data.

⚠️ 47.92% of total deal sealed by [f01100139](https://filfox.info/en/address/f01100139) are duplicate data.

⚠️ [f01100139](https://filfox.info/en/address/f01100139) has unknown IP location.

⚠️ 47.92% of total deal sealed by [f01227975](https://filfox.info/en/address/f01227975) are duplicate data.

⚠️ 47.92% of total deal sealed by [f0867300](https://filfox.info/en/address/f0867300) are duplicate data.

| Provider                                              |                           Location | Total Deals Sealed | Percentage | Unique Data | Duplicate Deals |
| :---------------------------------------------------- | ---------------------------------: | -----------------: | ---------: | ----------: | --------------: |
| [f0522948](https://filfox.info/en/address/f0522948)   |           Singapore, Singapore, SG |          34.95 TiB |     27.97% |   21.20 TiB |          39.34% |
| [f01100139](https://filfox.info/en/address/f01100139) |                            Unknown |          30.00 TiB |     24.01% |   15.63 TiB |          47.92% |
| [f01227975](https://filfox.info/en/address/f01227975) | Hong Kong, Central and Western, HK |          30.00 TiB |     24.01% |   15.63 TiB |          47.92% |
| [f0867300](https://filfox.info/en/address/f0867300)   |                   Tokyo, Tokyo, JP |          30.00 TiB |     24.01% |   15.63 TiB |          47.92% |

![Provider Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/1219/1671098882191.png)
### Deal Data Replication
The below table shows how each many unique data are replicated across storage providers.
- No more than 25% of unique data are stored with less than 4 providers.

✔️ Data replication looks healthy.

| Unique Data Size | Total Deals Made | Number of Providers | Deal Percentage |
| ---------------: | ---------------: | ------------------: | --------------: |
|         5.57 TiB |         5.57 TiB |                   1 |           4.46% |
|        15.63 TiB |       119.38 TiB |                   4 |          95.54% |

![Replication Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/1219/1671098882859.png)
### Deal Data Shared with other Clients
The below table shows how many unique data are shared with other clients.
Usually different applications owns different data and should not resolve to the same CID.

⚠️ CID sharing has been observed.

| Other Client                                                                                                                                                                                                              | Application                                                                                   | Total Deals Affected | Unique CIDs |        Verifier |
| :------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ | :-------------------------------------------------------------------------------------------- | -------------------: | ----------: | --------------: |
| [f3wgfwtrs5p6jrkwfl2mksqa2ivgbgdjjrhjbefy3<br/>n7qzvotc3y6sazmp5gfyj7um6jlgdvlbiepzawnc6<br/>wxtq](https://filfox.info/en/address/f3wgfwtrs5p6jrkwfl2mksqa2ivgbgdjjrhjbefy3n7qzvotc3y6sazmp5gfyj7um6jlgdvlbiepzawnc6wxtq) | [FileDrive Labs](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/453) |            44.58 TiB |         180 | LDN v3 multisig |

[^1]: To manually trigger this report, add a comment with text `checker:manualTrigger`

**Comment by Corerae** [comment]
@newwebgroup 
1.
YES！
2.
![纯娜](https://user-images.githubusercontent.com/93756978/208854919-4d13436b-ce02-401f-ac6b-051f131cecef.png)

We are still in contact with these miners, and are also looking for other suitable miners (using FILMine tools, etc.)

3.Our organization has home textile brands in major Chinese e-commerce platforms, and has hundreds of thousands of fans. Due to the impact of the COVID-19, the demand for online shopping has gradually increased recently, and we expect 50 TiB dataset growth every quarter. The current dataset is 500 TiB . 

PS：The time point of quota digestion was earlier than now. At that time, the requirements for duplicate data were not very clear. We will follow the current requirements of LDN project .

**Comment by herrehesse** [comment]
Dear Applicant,

Due to the increased amount of erroneous/wrong Filecoin+ data recently, on behalf of the entire community, we feel compelled to go deeper into datacap requests. Hereby to ensure that the overall value of the Filecoin network and Filecoin+ program increases and is not abused.

Please answer the questions below as comprehensively as possible.

**Customer data**

- Could you demonstrate exactly how and to what extent customer contact occurred? 

We expect that for the onboarding of customers with the scale of an LDN there would have been at least multiple email and perhaps several chat conversations preceding it. A single email with an agreement does not qualify here.

- Did the customer specify the amount of data involved in this relevant correspondence?

- Why does the customer in question want to use the Filecoin+ program? 

_Should this only be soley for acquiring datacap this is of course **out of the question**. The customer must have a legitimate reason for wanting to use the Filecoin+ program which is intended as a program to store useful and public datasets on the network._ 

- Why is the customer data considered Filecoin+ eligible?

_(As an intermediate solution Filecoin offers the FIL-E program or the glif.io website for business datasets that do not meet the requirements for a Filecoin+ dataset)_


**Files and Processing**

- Could you please demonstrate to us how you envision processing and transporting the customer data in question to any location for preparation?
- Would you demonstrate to us that the customer, the preparer and the intended storage providers all have adequate bandwidth to process the set with its corresponding size?
- Would you tell us how the data set preparer takes into account the prevention of duplicates in order to prevent data cap abuse?


Hopefully you understand the caution the overall community has for onboarding the wrong data. We understand the increased need for Filecoin+, however, we must not allow the program to be misused. Everything depends on a valuable and useful network, let's do our best to make this happen. Together.

**Comment by Joss-Hua** [comment]
checker:manualTrigger

**Comment by Joss-Hua** [comment]
CC@raghavrmadya  The Checkerbot did not give me the correct return value

**Comment by Joss-Hua** [comment]
After preliminary data check and client communication, support this round.
Follow up the commitments https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1219#issuecomment-1361009195

**Comment by Joss-Hua** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacealolmtif6i6g7m7n5b6qhqi3w43a6y5zqzb365utrjcz4g6xb5l4 
#### Address 
> f1aqbilzkvvtggxd4kui5zamwqrdpfzilbtmg5kdi
#### Datacap Allocated
> 249.34TiB
#### Signer Address
> f1tfg54zzscugttejv336vivknmsnzzmyudp3t7wi
#### Id
> 46f851a4-2d86-4b2f-ab77-336f1688ffe0
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacealolmtif6i6g7m7n5b6qhqi3w43a6y5zqzb365utrjcz4g6xb5l4

**Comment by nj-steve** [comment]
checker:manualTrigger

**Comment by Fatman13** [comment]
checker:manualTrigger

**Comment by Fatman13** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceclznuq5y4mkiqwgtxqluu35tkv4ha4i2tq7nzrev6xe22ibnkgji 
#### Address 
> f1aqbilzkvvtggxd4kui5zamwqrdpfzilbtmg5kdi
#### Datacap Allocated
> 249.34TiB
#### Signer Address
> f1j3u7crhjzwb2cj5mq7vodlt4o66yoyci7lhcauy
#### Id
> 46f851a4-2d86-4b2f-ab77-336f1688ffe0
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceclznuq5y4mkiqwgtxqluu35tkv4ha4i2tq7nzrev6xe22ibnkgji

**Comment by Fatman13** [comment]
was previously reached out by the client but at that moment was not able to login to notary dashboard after fil-hk. Now the problem is fixed by Philipe and the team. Have gone through some of the allocation plans with the client on Slack to improve the warnings prompted by CID checker.

**Comment by laurarenpanda** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceblzxbdyirj22j3mr5bwqasvmkjmwvkrbrkcmnehd2fldqezr2rsi 
#### Address 
> f1aqbilzkvvtggxd4kui5zamwqrdpfzilbtmg5kdi
#### Datacap Allocated
> 249.34TiB
#### Signer Address
> f1bp3tzp536edm7dodldceekzbsx7zcy7hdfg6uzq
#### Id
> 46f851a4-2d86-4b2f-ab77-336f1688ffe0
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceblzxbdyirj22j3mr5bwqasvmkjmwvkrbrkcmnehd2fldqezr2rsi

**Comment by Corerae** [comment]
Dear notaries! Please take a look at our application. Really need your support to keep going! Thanks!

**Comment by Fatman13** [comment]
checker:manualTrigger

**Comment by Fatman13** [comment]
Reached out by the client again. Wouldn't able to support due to CIDchecker report warnings.
