### ISSUE TITLE
[DataCap Application] - <KTalks>

### ISSUE THREAD

**Issue by James-YikeTalks** [filecoin-project/filecoin-plus-large-datasets#1222]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: KTalks
- Website / Social Media:https://www.yiketalks.com/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):100TiB
- On-chain address for first allocation:f1r7nceo5cb677fdvieg53hnagvmghz6xyneya25a

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Ktalks is a leading domestic media like TED, a global intellectual knowledge sharing platform, focusing on six innovation  categories in intelligence, genetics, business, finance, education and art that will profoundly affect future changes. field, and strive to jointly promote the future of the mind. We produce live stream, speech event, video interview with some outstanding representatives in different industries through deep conversation. 
```
What is the primary source of funding for this project?
```
own fund
```

What other projects/ecosystem stakeholders is this project associated with?
```
no
```

## Use-case details

Describe the data being stored onto Filecoin
```
videos on official social media/platform
```

Where was the data in this dataset sourced from?
```
videos produced by my team.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://www.youtube.com/channel/UC8OPzYp9d4sZBk6ElacXnKw  https://search.bilibili.com/all?keyword=%E4%B8%80%E5%88%BBtalks  https://www.bilibili.com/video/BV1rQ4y1K7zJ/?spm_id_from=333.337.search-card.all.click   https://www.bilibili.com/video/BV1jc411h761/?spm_id_from=333.337.search-card.all.click https://www.bilibili.com/video/BV1T4411y7vh/?spm_id_from=333.788.recommend_more_video.8
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
yes
```

What is the expected retrieval frequency for this data?
```
often
```

For how long do you plan to keep this dataset stored on Filecoin?
```
3-5 years
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
globally
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
offline
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
firstly consider local SPs to ensure stable network 
```

How will you be distributing deals across storage providers?
```
select 4 - 6 SPs and distribute the quota as equally as possible
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
yes
```

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 100TiB

**Client address**

>f1r7nceo5cb677fdvieg53hnagvmghz6xyneya25a

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Looking at your application i have some questions:
As you are brand new on Github and have no history of past applications it seems to me that applying for 5PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?

Can you show us visible proof of the size of your data and the storage systems you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230232885049356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!
