### ISSUE TITLE
[DataCap Application] <Arrows> - <Energy Database>

### ISSUE THREAD

**Issue by fand-ee** [filecoin-project/filecoin-plus-large-datasets#1225]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: アローズコーポレーション（Arrows Corporation）
- Website / Social Media: https://arrows-corp.co.jp/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 4.95PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 500TiB
- On-chain address for first allocation: f1qlw5qik62kvrzvpa7bsst65uobtt3jmkrh3ajsq

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
ARROWS was established in July 2006, and its main business is as follows:
・ Housing business. (sales / construction / maintenance work such as sales outsourcing, solar power generation system, storage battery system, HEMS, all-electric, EV charger, remodeling, etc.).
・ Material procurement. (solar power generation system, storage battery system, HEMS, all-electric, EV charger, etc. wholesale sales)
・ Business development. (biomass business, comprehensive sales of housing materials)
![image](https://user-images.githubusercontent.com/93598242/200982944-a635c983-231d-48cf-9bbb-c391b809ff1c.png)

```

What is the primary source of funding for this project?
```
Company's own assets.
```

What other projects/ecosystem stakeholders is this project associated with?
```
There is no others.
```

## Use-case details

Describe the data being stored onto Filecoin
```
National Solar Radiation Database (NSRDB) is a serially complete collection of hourly and half-hourly values of the three most common measurements of solar radiation – global horizontal, direct normal, and diffuse horizontal irradiance — and meteorological data. These data have been collected at a sufficient number of locations and temporal and spatial scales to accurately represent regional solar radiation climates.
```

Where was the data in this dataset sourced from?
```
AWS (https://registry.opendata.aws/nrel-pds-nsrdb/)
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://nsrdb.nrel.gov/
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
License: Creative Commons Attribution 3.0 United States License.
```

What is the expected retrieval frequency for this data?
```
Anytime.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
Over 540 days.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Mainly in Japan, other area in Asia is also acceptable.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Mainly transferred online, offline transfer can be considered if the storage provider is in Japan.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We will need reliable storage providers to ensure that our data can be stored for a long time and also can be retrieved at any time.
```

How will you be distributing deals across storage providers?
```
The amount of data allocated will be determined by the qualifications of the storage provider, such as the stability of the equipment they provide, the amount pledged, etc.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Company assets can cover all expenses.
```

PS. We have submitted this application before, but we've lost our previous GitHub account due to some problems and the application process was interrupted, so we had to resubmit the application again. We would appreciate it if you would reconsider our application.
The screenshot is a record of the last application, and the link to the previous application (which is no longer available due to account issues): https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/101

![arrows](https://user-images.githubusercontent.com/93598242/200984095-ec9686e1-bb46-4e47-9b9c-5642ef0a4532.png)
![arrows2](https://user-images.githubusercontent.com/93598242/200984105-005b3937-2940-4835-b590-c3e098cf9e5c.png)

**Comment by simonkim0515** [comment]
@fand-ee it seems that this ID was allocated 50TiB already. Can you change the total amount of DataCap being requested to 4.5PiB, however If you would like the additional 5PiB on top of the 50TiB allocated, please explain why you need the extra 5PiB.

**Comment by kernelogic** [comment]
I have done the same dataset and I will verify it after first allocation.

**Comment by kernelogic** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced5dnrwrzt57jxuxi3l2rwpozp5a2gpnsynr5dfvbzc3esxpzqtec 
#### Address 
> f1qlw5qik62kvrzvpa7bsst65uobtt3jmkrh3ajsq
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### Id
> 77941bbd-8543-4947-8558-44616c83d9a1
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced5dnrwrzt57jxuxi3l2rwpozp5a2gpnsynr5dfvbzc3esxpzqtec

**Comment by fand-ee** [comment]
@kernelogic Thanks for your support. In addition, I would like to ask why the request is 250T, but the pass is 100T. Is there a bug in the program?

**Comment by Joss-Hua** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebespf3x22vinmz6ffe272qcytgwclcdid554gvcvt6pgs3v57lsa 
#### Address 
> f1qlw5qik62kvrzvpa7bsst65uobtt3jmkrh3ajsq
#### Datacap Allocated
> 250.00TiB
#### Signer Address
> f1tfg54zzscugttejv336vivknmsnzzmyudp3t7wi
#### Id
> 77941bbd-8543-4947-8558-44616c83d9a1
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebespf3x22vinmz6ffe272qcytgwclcdid554gvcvt6pgs3v57lsa

**Comment by Joss-Hua** [comment]
I have preliminarily investigated this client in #101. 
Agreed to this allocation, and further reviewed it before the next allocation.

**Comment by Joss-Hua** [comment]
![image](https://user-images.githubusercontent.com/75723122/206132072-b64e6247-dffb-40f4-8627-6fe8818e8999.png)

anomalous, "Datacap Allocated" is inconsistent with the actual allocated quantity @galen-mcandrew @dkkapur

**Comment by psh0691** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacea7hlgj2fruotbrlcquofjhkdgrzmrphyy5vzmmcbdqj2lujtu4ig 
#### Address 
> f1qlw5qik62kvrzvpa7bsst65uobtt3jmkrh3ajsq
#### Datacap Allocated
> 250.00TiB
#### Signer Address
> f1qdko4jg25vo35qmyvcrw4ak4fmuu3f5rif2kc7i
#### Id
> 77941bbd-8543-4947-8558-44616c83d9a1
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacea7hlgj2fruotbrlcquofjhkdgrzmrphyy5vzmmcbdqj2lujtu4ig

**Comment by filplus-checker** [comment]
## DataCap and CID Checker Report[^1]
 - Organization: `アローズコーポレーション（Arrows Corporation）`
 - Client: `f1qlw5qik62kvrzvpa7bsst65uobtt3jmkrh3ajsq`
### Storage Provider Distribution
The below table shows the distribution of storage providers that have stored data for this client.

If this is the first time a provider takes verified deal, it will be marked as `new`.

For most of the datacap application, below restrictions should apply.
 - Storage provider should not exceed 25% of total datacap.
 - Storage provider should not be storing duplicate data for more than 20%.
 - Storage provider should have published its public IP address.
 - All storage providers should be located in different regions.

⚠️ [f01228089](https://filfox.info/en/address/f01228089) has sealed 30.00% of total datacap.

⚠️ 54.58% of total deal sealed by [f01228089](https://filfox.info/en/address/f01228089) are duplicate data.

⚠️ [f01228100](https://filfox.info/en/address/f01228100) has sealed 30.00% of total datacap.

⚠️ 54.58% of total deal sealed by [f01228100](https://filfox.info/en/address/f01228100) are duplicate data.

⚠️ 31.87% of total deal sealed by [f01228087](https://filfox.info/en/address/f01228087) are duplicate data.

⚠️ 31.87% of total deal sealed by [f01228105](https://filfox.info/en/address/f01228105) are duplicate data.

| Provider                                              |                           Location | Total Deals Sealed | Percentage | Unique Data | Duplicate Deals |
| :---------------------------------------------------- | ---------------------------------: | -----------------: | ---------: | ----------: | --------------: |
| [f01228089](https://filfox.info/en/address/f01228089) |       Frankfurt am Main, Hesse, DE |          15.00 TiB |     30.00% |    6.81 TiB |          54.58% |
| [f01228100](https://filfox.info/en/address/f01228100) |           San Jose, California, US |          15.00 TiB |     30.00% |    6.81 TiB |          54.58% |
| [f01228087](https://filfox.info/en/address/f01228087) |                London, England, GB |          10.00 TiB |     20.00% |    6.81 TiB |          31.87% |
| [f01228105](https://filfox.info/en/address/f01228105) | Hong Kong, Central and Western, HK |          10.00 TiB |     20.00% |    6.81 TiB |          31.87% |

![Provider Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/1225/1671098892638.png)
### Deal Data Replication
The below table shows how each many unique data are replicated across storage providers.
- No more than 25% of unique data are stored with less than 4 providers.

✔️ Data replication looks healthy.

| Unique Data Size | Total Deals Made | Number of Providers | Deal Percentage |
| ---------------: | ---------------: | ------------------: | --------------: |
|         6.81 TiB |        50.00 TiB |                   4 |         100.00% |

![Replication Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/1225/1671098893306.png)
### Deal Data Shared with other Clients
The below table shows how many unique data are shared with other clients.
Usually different applications owns different data and should not resolve to the same CID.

⚠️ CID sharing has been observed.

| Other Client                                                                                                                                                                                                              | Application                                                                                   | Total Deals Affected | Unique CIDs |        Verifier |
| :------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ | :-------------------------------------------------------------------------------------------- | -------------------: | ----------: | --------------: |
| [f3qaipvxrz2gxexc7mcvjsxifmscfiw7c7zfhrmq7<br/>6j5ee4hcbvg3gbtpea7wgz72kkjcjmwzhm5uo2onx<br/>yocq](https://filfox.info/en/address/f3qaipvxrz2gxexc7mcvjsxifmscfiw7c7zfhrmq76j5ee4hcbvg3gbtpea7wgz72kkjcjmwzhm5uo2onxyocq) | [Guazi Dynamic ](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/393) |            27.25 TiB |         218 | LDN v3 multisig |

[^1]: To manually trigger this report, add a comment with text `checker:manualTrigger`

**Comment by cryptowhizzard** [comment]
Hi @fand-ee 

I tried to retrieve some data but got stuck after this:

root@proposals:~# lotus client retrieve --provider f01228087 QmXhz91P5rJD9JBiuWp5bVwcn5m6h7vvTGigB2ARyaUmLk test.car
Recv 0 B, Paid 0 FIL, Open (New), 0s [1676445845934082940|0]
Recv 0 B, Paid 0 FIL, DealProposed (WaitForAcceptance), 3ms [1676445845934082940|0]

Is f01228087 open for retrieval?

**Comment by fand-ee** [comment]
Hi @cryptowhizzard 
f01228087 is open for retrieval. It may be slow due to network problems, please try again.

**Comment by cryptowhizzard** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedapdts7da5hj4p3mplg6ramnjwe3swb2gysdeh6adzrqiow7426m 
#### Address 
> f1qlw5qik62kvrzvpa7bsst65uobtt3jmkrh3ajsq
#### Datacap Allocated
> 500.00TiB
#### Signer Address
> f1krmypm4uoxxf3g7okrwtrahlmpcph3y7rbqqgfa
#### Id
> 1852d20c-f650-4645-99c6-66ee24fc3d04
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedapdts7da5hj4p3mplg6ramnjwe3swb2gysdeh6adzrqiow7426m

**Comment by cryptowhizzard** [comment]
@fand-ee 

Thanks, retrieval worked.

**Comment by Joss-Hua** [comment]
checker:manualTrigger

**Comment by nj-steve** [comment]
checker:manualTrigger

**Comment by fand-ee** [comment]
Hi @nj-steve 
It's possible that we used the same AWS public dataset and the same data splitting tool, which may have led to this issue occurring with a small probability. This is inevitable, but we will try to find ways to reduce the occurrence of such situations in the future.

**Comment by nj-steve** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb5jk7vyl2odcwzgtjxzgc7kmwpaew6vcefh2mtv32otvl3np7frm 
#### Address 
> f1qlw5qik62kvrzvpa7bsst65uobtt3jmkrh3ajsq
#### Datacap Allocated
> 500.00TiB
#### Signer Address
> f1xx6555qijma7igpnjspyvdunc4vfxkawnpqy5ii
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb5jk7vyl2odcwzgtjxzgc7kmwpaew6vcefh2mtv32otvl3np7frm

**Comment by herrehesse** [comment]
checker:manualTrigger

**Comment by spaceT9** [comment]
your retrieval rate is  too low and it needs to be increased.

**Comment by fand-ee** [comment]
@spaceT9 I have asked SPs to support retrieval, because the retrieval rate is a cumulative value and will gradually increase with the number of tests. We will terminate cooperation with SPs that have been unable to provide retrieval services

**Comment by fand-ee** [comment]
Waiting for signature

**Comment by cryptowhizzard** [comment]
> Waiting for signature

You should make sure your SP's enable retrieval before you get next allocation of datacap. Retrieval is mandatory according to Fil+ rules and guidelines.

**Comment by fand-ee** [comment]
......

**Comment by clriesco** [comment]
Removed stale label, reopened issue :)

**Comment by fand-ee** [comment]
Hi
