### ISSUE TITLE
[DataCap Allocation] - Application for a large datacap

### ISSUE THREAD

**Issue by teamhzipfs** [filecoin-project/filecoin-plus-large-datasets#1229]
---
name: Large Dataset Notary application
about: Clients should use this application form to request a DataCap allocation via a LDN for a dataset
title: "Application for a large datacap"
labels: 'application, Phase: Diligence'
assignees: ''

---
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Dayan Technology
- Website / Social Media: wechat: yczhang9999; telegram: Chaochao2021
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100TiB
- On-chain address for first allocation: f1o52hywcutkq6iqztmrlox24blocbjwm6ka7avey
- Region: Greater China Region

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
The project is to allow for the storage of a gaming plotform which has a very large set of data. We are looking to utilize Filecoin to help improve the efficiency bring Web3 technology to today's web2 world.
```

What is the primary source of funding for this project?
```
Investors include a gaming company and other private fund investment company.
```

What other projects/ecosystem stakeholders is this project associated with?
```
Dayan Technology is the company running the storage node.
```

## Use-case details

Describe the data being stored onto Filecoin
```
Primarily date of the gaming platform but could also include other data.
```

Where was the data in this dataset sourced from?
```
A gaming platform.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
No sample available yet.
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes
```

What is the expected retrieval frequency for this data?
```
From daily to weekly.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
The next 5 years.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Greater China.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Yes. Hard drive transfer. 
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
Yes. We will be storing with f01090983.
```

How will you be distributing deals across storage providers?
```
No.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes. As mentioned we are backed by a private fund investment company.
```

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 100TiB

**Client address**

> f1o52hywcutkq6iqztmrlox24blocbjwm6ka7avey

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Looking at your application i have some questions:
As you are brand new on Github and have no history of past applications it seems to me that applying for 5PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?

Can you show us visible proof of the size of your data and the storage systems you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230232885049356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!
