### ISSUE TITLE
[DataCap Application] <Chengdu Fengfan Technology> 

### ISSUE THREAD

**Issue by GuiPulp** [filecoin-project/filecoin-plus-large-datasets#1231]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Chengdu Fengfan Technology Co., Ltd.
- Website / Social Media: website: http://www.ffapm.net/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100TiB
- On-chain address for first allocation: f1jpvx2qvvgil7gowa5pkxjtueeau3zwkoknjwtsi

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Chengdu Fengfan Technology Co., Ltd. was established in 2015. The company was engaged in the development of application software in the early days, and successively developed the Niuniu Xiaotuan community group buying platform, the Gugubang help selling platform, etc., and later transformed into IT monitoring. The company has the industry's leading products and solutions, and provides a wealth of performance monitoring and stress testing services. Our core product is FFAPM (Fengfan Application Performance Management). We emphasize customer-centricity, take the needs and pain points of customers as the core, and provide different IT service system solutions and services for different industries in combination with the their various characteristics.
```

What is the primary source of funding for this project?
```
It comes from the company revenue. We have a budget for it.
```

What other projects/ecosystem stakeholders is this project associated with?
```
No.
```

## Use-case details

Describe the data being stored onto Filecoin
```
Product training and frontend monitoring videos, audios, and various documents
```

Where was the data in this dataset sourced from?
```
The data is produced by ourselves. It includes various kinds of training videos and audios of our products and discussions at different meetings, frontend monitoring videos, documents of our product training and company activities, and smart solutions we've designed for various application scenarios.


```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://drive.google.com/drive/folders/1Io9hqOZjGWZrOE7CezRvsPQflzudrLna?usp=share_link
https://drive.google.com/drive/folders/1zq1uIflCLGrOPKIHyJcPdyg9IOAiX8Oj?usp=sharing
```

        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes. These are public dataset produced by ourselves.
```

What is the expected retrieval frequency for this data?
```
About twice a week.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
We'd like to keep that for at least two years.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Asia, Africa, Europe, North America
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
The data will be distributed to storage providers online and offline. We have 10 Gbps of bandwidth. Storage Providers can download data from our servers or we will send the disks to them. 
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We prefer to chose storage providers with good reputation based on their adjusted power, current storage capacity, seal capabilities, enterprise-grade DCs, bandwidth, etc.
```

How will you be distributing deals across storage providers?
```
We would like to find at least 4 storage providers and distribute < 25% of the deals to each of them.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, we have enough budget for that.
```

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 100TiB

**Client address**

> f1jpvx2qvvgil7gowa5pkxjtueeau3zwkoknjwtsi

**Comment by flyworker** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedn37sakdptswnji2h64opi3jz5f7htwyfpqvgurmbg4rv44so3o6 
#### Address 
> f1jpvx2qvvgil7gowa5pkxjtueeau3zwkoknjwtsi
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1hlubjsdkv4wmsdadihloxgwrz3j3ernf6i3cbpy
#### Id
> 875f0327-143f-4818-9b80-328e3b2dc324
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedn37sakdptswnji2h64opi3jz5f7htwyfpqvgurmbg4rv44so3o6

**Comment by IreneYoung** [comment]
@GuiPulp If there're no data privacy concerns, I will support the application.

**Comment by GuiPulp** [comment]
Thanks @IreneYoung all data is owned by our company and is publicly available

**Comment by IreneYoung** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecdsi6muvl3dy7kahsuskiw3rjvla3dnj752yenv4jlv5e76lhzrg 
#### Address 
> f1jpvx2qvvgil7gowa5pkxjtueeau3zwkoknjwtsi
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1d4gmpqz3execjj2wvrxuuhvbms5mzh7t7yqrviq
#### Id
> 875f0327-143f-4818-9b80-328e3b2dc324
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecdsi6muvl3dy7kahsuskiw3rjvla3dnj752yenv4jlv5e76lhzrg

**Comment by kernelogic** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedfirb7xybca75r5gyhz6woy2cjzeiq5odys43yppbnipa6keok2i 
#### Address 
> f1jpvx2qvvgil7gowa5pkxjtueeau3zwkoknjwtsi
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### Id
> f7e5f13c-eb3d-4052-b804-2757be944117
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedfirb7xybca75r5gyhz6woy2cjzeiq5odys43yppbnipa6keok2i

**Comment by cryptowhizzard** [comment]
I did some retrieval tests and could not locate / find the data the applicant stated to store.

**Comment by flyworker** [comment]
@kernelogic's test convinced me, would like to continue sign.

**Comment by flyworker** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceai5jkkazmroo2foix7jdodvpmwccvajqw4u5cykpwhsvwgea5r2k 
#### Address 
> f1jpvx2qvvgil7gowa5pkxjtueeau3zwkoknjwtsi
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1hlubjsdkv4wmsdadihloxgwrz3j3ernf6i3cbpy
#### Id
> f7e5f13c-eb3d-4052-b804-2757be944117
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceai5jkkazmroo2foix7jdodvpmwccvajqw4u5cykpwhsvwgea5r2k

**Comment by Yvette516** [comment]
@flyworker Can you share context as to why you were comfortable signing this application? We all find that @cryptowhizzard has raised a flag after @kernelogic's simple verification. It would be much appreciated if you can give some reasonable explaination.

Also, Curious that why did you sign this application twice in a row?

**Comment by lvschouwen** [comment]
@GuiPulp 
Can you please provide me a list of files that have been encapsulated into the CAR files that went on chain?
All I can find is one file;

dc.tar.gz (in different parts)

So far I am not able to piece it together and extract it.

**Comment by flyworker** [comment]
> 

The same notary cannot sign off on immediately subsequent allocations of DataCap, i.e., you need at minimum 4 unique notaries to support your application on an ongoing basis to receive multiple tranches of DataCap.

OK,just notice this datacap has been signed by me already last time, will let other notaries sign next time, or there is a way to cancel.

**Comment by flyworker** [comment]
> @flyworker Can you share context as to why you were comfortable signing this application? We all find that @cryptowhizzard has raised a flag after @kernelogic's simple verification. It would be much appreciated if you can give some reasonable explaination.
> 
> Also, Curious that why did you sign this application twice in a row?

lotus client retrieve --provider f0187709 --pieceCid baga6ea4seaqe7diyp5vbpdukjqieupfqrgwbexyi4kh2dlcv2eihn5oqmfds6oa QmXfAfQpcaK1qW3hBYCkM8NkQfZyu4qn4sxwivc6dEob5K deal.file 
Recv 0 B, Paid 0 FIL, DealProposed (WaitForAcceptance), 26ms
Recv 0 B, Paid 0 FIL, DealAccepted (Accepted), 11.161s
Recv 0 B, Paid 0 FIL, PaymentChannelSkip (Ongoing), 11.187s
Recv 68 B, Paid 0 FIL, BlocksReceived (Ongoing), 11.24s
Recv 752 B, Paid 0 FIL, BlocksReceived (Ongoing), 11.24s
Recv 48.75 KiB, Paid 0 FIL, BlocksReceived (Ongoing), 11.24s
Recv 1.048 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 13.412s
Recv 2.048 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 15.681s
Recv 3.048 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 17.124s
Recv 4.048 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 18.563s
Recv 5.048 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 20.398s
Recv 6.048 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 22.054s
Recv 7.048 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 22.95s
Recv 8.048 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 23.788s
Recv 9.048 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 24.75s
Recv 10.05 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 25.609s
Recv 11.05 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 26.439s
Recv 12.05 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 27.409s
Recv 13.05 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 28.395s
Recv 14.05 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 29.368s
Recv 15.05 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 30.319s
Recv 16.05 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 31.264s

this is my retrieval test log

**Comment by GuiPulp** [comment]
checker:manualTrigger

**Comment by Normalnoise** [comment]
checker:manualTrigger

**Comment by Normalnoise** [comment]
checker:manualTrigger

**Comment by bq1024** [comment]
Random data retrieve looks good, SP distribution and data replication looks healthy.
```
lotus client retrieve --provider f02017390 Qme5L8EHYvLbcYks1xCdrk9ccxCXLnWri6qSCL5s3q1Psw f02017390.txt
Recv 0 B, Paid 0 FIL, Open (New), 0s [1680864601230977015|0]
Recv 0 B, Paid 0 FIL, DealProposed (WaitForAcceptance), 62ms [1680864601230977015|0]
Recv 0 B, Paid 0 FIL, DealAccepted (Accepted), 284ms [1680864601230977015|0]
Recv 0 B, Paid 0 FIL, PaymentChannelSkip (Ongoing), 304ms [1680864601230977015|0]
Recv 79 B, Paid 0 FIL, BlocksReceived (Ongoing), 422ms [1680864601230977015|79]
Recv 3.687 KiB, Paid 0 FIL, BlocksReceived (Ongoing), 422ms [1680864601230977015|3775]
Recv 6.368 KiB, Paid 0 FIL, BlocksReceived (Ongoing), 516ms [1680864601230977015|6521]
Recv 1.006 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 5.863s [1680864601230977015|1055111]
Recv 2.006 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 8.465s [1680864601230977015|2103701]
Recv 3.006 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 10.529s [1680864601230977015|3152291]
Recv 4.006 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 12.021s [1680864601230977015|4200881]
Recv 5.006 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 12.921s [1680864601230977015|5249471]
Recv 6.006 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 13.931s [1680864601230977015|6298061]
Recv 7.006 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 14.958s [1680864601230977015|7346651]
Recv 8.006 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 15.89s [1680864601230977015|8395241]
Recv 9.006 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 17.171s [1680864601230977015|9443831]
Recv 10.01 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 18.497s [1680864601230977015|10492421]
Recv 11.01 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 19.59s [1680864601230977015|11541011]
Recv 12.01 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 20.502s [1680864601230977015|12589601]
Recv 13.01 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 21.698s [1680864601230977015|13638191]
Recv 14.01 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 22.828s [1680864601230977015|14686781]
Recv 15.01 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 24.026s [1680864601230977015|15735371]
Recv 16.01 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 25.11s [1680864601230977015|16783961]
Recv 17.01 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 26.151s [1680864601230977015|17832551]
Recv 18.01 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 27.2s [1680864601230977015|18881141]
Recv 19.01 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 28.41s [1680864601230977015|19929731]
Recv 20.01 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 29.312s [1680864601230977015|20978321]
Recv 21.01 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 30.402s [1680864601230977015|22026911]
Recv 22.01 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 31.372s [1680864601230977015|23075501]
Recv 23.01 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 32.457s [1680864601230977015|24124091]
Recv 24.01 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 33.45s [1680864601230977015|25172681]
Recv 25.01 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 34.464s [1680864601230977015|26221271]
Recv 26.01 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 35.69s [1680864601230977015|27269861]
Recv 27.01 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 37.186s [1680864601230977015|28318451]
Recv 28.01 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 38.083s [1680864601230977015|29367041]
Recv 29.01 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 39.206s [1680864601230977015|30415631]
Recv 30.01 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 40.286s [1680864601230977015|31464221]
Recv 31.01 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 41.516s [1680864601230977015|32512811]
Recv 32.01 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 42.684s [1680864601230977015|33561401]
Recv 33.01 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 43.884s [1680864601230977015|34609991]
Recv 34.01 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 44.803s [1680864601230977015|35658581]
Recv 35.01 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 45.658s [1680864601230977015|36707171]
Recv 36.01 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 46.821s [1680864601230977015|37755761]
```

**Comment by bq1024** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb6spyt25dm3mtbidrhiwcohdzggna7ldo6hxery5r3fqlwphyl4g 
#### Address 
> f1jpvx2qvvgil7gowa5pkxjtueeau3zwkoknjwtsi
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1pkjtavqx4r2q2w3he3jknfc5mo2vgfimccmpnaa
#### Id
> 80033f75-b98a-4637-851a-6f174264424e
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb6spyt25dm3mtbidrhiwcohdzggna7ldo6hxery5r3fqlwphyl4g

**Comment by BobStaring** [comment]
checker:manualTrigger

**Comment by nj-steve** [comment]
checker:manualTrigger

**Comment by nj-steve** [comment]
lotus client retrieve --provider f02017390 QmPQzod2wyB1SQtGqpknu3AyjQ1gVU8fMQwPhhMU94GLQB fengfan.txt
Recv 0 B, Paid 0 FIL, Open (New), 0s [1678697507252112816|0]
Recv 0 B, Paid 0 FIL, DealProposed (WaitForAcceptance), 4ms [1678697507252112816|0]
Recv 0 B, Paid 0 FIL, DealAccepted (Accepted), 38.157s [1678697507252112816|0]
Recv 0 B, Paid 0 FIL, PaymentChannelSkip (Ongoing), 38.162s [1678697507252112816|0]
Recv 79 B, Paid 0 FIL, BlocksReceived (Ongoing), 38.17s [1678697507252112816|79]
Recv 3.483 KiB, Paid 0 FIL, BlocksReceived (Ongoing), 38.17s [1678697507252112816|3567]
Recv 42.21 KiB, Paid 0 FIL, BlocksReceived (Ongoing), 38.17s [1678697507252112816|43226]
Recv 1.041 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 41.949s [1678697507252112816|1091816]
Recv 2.041 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 55.2s [1678697507252112816|2140406]
Recv 3.041 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 58.063s [1678697507252112816|3188996]
Recv 4.041 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 1m10.619s [1678697507252112816|4237586]
Recv 5.041 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 1m14.686s [1678697507252112816|5286176]
Recv 6.041 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 1m24.005s [1678697507252112816|6334766]
Recv 7.041 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 1m26.497s [1678697507252112816|7383356]
Recv 8.041 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 1m30.16s [1678697507252112816|8431946]
Recv 9.041 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 1m33.233s [1678697507252112816|9480536]
Recv 10.04 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 1m35.924s [1678697507252112816|10529126]
Recv 11.04 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 1m38.674s [1678697507252112816|11577716]
Recv 12.04 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 1m40.331s [1678697507252112816|12626306]
Recv 13.04 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 1m45.369s [1678697507252112816|13674896]
Recv 14.04 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 1m49.25s [1678697507252112816|14723486]
Recv 15.04 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 1m52.926s [1678697507252112816|15772076]
Recv 16.04 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 1m56.582s [1678697507252112816|16820666]
Recv 17.04 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 2m0.706s [1678697507252112816|17869256]
Recv 18.04 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 2m4.162s [1678697507252112816|18917846]
Recv 19.04 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 2m6.752s [1678697507252112816|19966436]
Recv 20.04 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 2m8.404s [1678697507252112816|21015026]
Recv 21.04 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 2m11.686s [1678697507252112816|22063616]
Recv 22.04 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 2m15.844s [1678697507252112816|23112206]
Recv 23.04 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 2m18.98s [1678697507252112816|24160796]
Recv 24.04 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 2m24.796s [1678697507252112816|25209386]
Recv 25.04 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 2m29.137s [1678697507252112816|26257976]
Recv 26.04 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 2m33.426s [1678697507252112816|27306566]
Recv 27.04 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 2m37.57s [1678697507252112816|28355156]
Recv 28.04 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 2m39.545s [1678697507252112816|29403746]
Recv 29.04 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 2m44.614s [1678697507252112816|30452336]
Recv 30.04 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 2m47.096s [1678697507252112816|31500926]
Recv 31.04 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 2m50.214s [1678697507252112816|32549516]
Recv 32.04 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 2m53.33s [1678697507252112816|33598106]
Recv 33.04 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 2m54.968s [1678697507252112816|34646696]
Recv 34.04 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 2m57.832s [1678697507252112816|35695286]
Recv 35.04 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 3m0.846s [1678697507252112816|36743876]
Recv 36.04 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 3m2.777s [1678697507252112816|37792466]
Recv 37.04 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 3m4.434s [1678697507252112816|38841056]
Recv 38.04 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 3m6.146s [1678697507252112816|39889646]
Recv 39.04 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 3m8.027s [1678697507252112816|40938236]
Recv 40.04 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 3m9.691s [1678697507252112816|41986826]

The report and the retrieve look good!

**Comment by GuiPulp** [comment]
checker:manualTrigger
