### ISSUE TITLE
[DataCap Application] <Yu Quan> - <Chong Qu Hui>

### ISSUE THREAD

**Issue by cqh2022** [filecoin-project/filecoin-plus-large-datasets#1236]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Hangzhou Yu Quan Technology Co.
- Website / Social Media: http://www.jinguidna.com
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5 PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 200TiB
- On-chain address for first allocation: f1maztm327vu3w4gvum7lbmohupao6et5s6xjlr2q

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Hangzhou Yu  Quan Technology was established in 2018, facing the historical mission of building a beautiful China and the increasing public attention to nature conservation in recent years, especially the emergence of haze, water pollution and climate change and other issues related to public health, society is more concerned about environmental safety and sustainable development, and expects to actively learn related knowledge; the rich biodiversity of nature and the behavior of insects are very attractive to The rich biodiversity of nature and the behavior of insects are very attractive to urban dwellers, and the public is very willing to participate in nature education activities. For children in particular, the alienation between childhood and nature is a major dislocation. It is a new educational concept to allow children to gain a variety of experiences and learn a variety of skills in nature and to achieve an effective connection between children and nature, thus maintaining children's intellectual growth and healthy physical and mental development.
We provide one-stop nature education activities and related nature products for adults aged 30-45 and children aged 6-12 with online sharing and offline experience.
The project includes: 1) offline experience store model with cross-border cooperation; 2) brand social effect construction such as nature classroom on campus and second classroom; 3) interactive platform for nature education preferences, bringing together domestic and international high-quality nature education institutions, protected areas and related industries; 4) continuous fun science and wilderness discovery through a large number of short videos to spread nature knowledge and advocate green concepts.
```

What is the primary source of funding for this project?
```
Shareholder funds, revenue generated from the broadcast of classroom teaching videos, and revenues from convention fees and sales of peripheral products.
```

What other projects/ecosystem stakeholders is this project associated with?
```
None
```

## Use-case details

Describe the data being stored onto Filecoin
```
Authored videos or photos of the developmental changes of plants and animals throughout their life cycle.
```

Where was the data in this dataset sourced from?
```
All shot independently..
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
Of course. Please check the link: http://www.jinguidna.com
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Confirmation.
```

What is the expected retrieval frequency for this data?
```
Twice a year.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
At least 2 years.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Any region that meets the rules will do, with Asia preferred.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Both online and offline will be considered, depending on the storage provider actually.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We hope to find some miners with size and credit. We plan to make a special form for our own records.
```

How will you be distributing deals across storage providers?
```
The data is split according to filecoin rules and sent to different miners.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Everything is ready to go.
```

**Comment by cqh2022** [comment]
hi @simonkim0515 thank you for taking the time,our team's application has participated in the Governance Call see that you have approved many projects but ours has not,is there any question we need to add?
![微信图片_20221202102732](https://user-images.githubusercontent.com/116540903/205201753-0e8aaa18-8b5b-426f-a3d0-8a3602a27ab6.jpg)

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 200TiB

**Client address**

> f1maztm327vu3w4gvum7lbmohupao6et5s6xjlr2q

**Comment by psh0691** [comment]
Are there any related SPs? 
Or did you select the SPs you want to save?

**Comment by cqh2022** [comment]
> Could you give some screenshot of you having more than 500T of raw data? Also data samples?

Okay,please look at the pictures here：
<img width="1073" alt="微信图片_202212071920195" src="https://user-images.githubusercontent.com/116540903/206167173-b331a43b-7901-4125-8f26-5dc1501f8ca0.png">
 <img width="1073" alt="微信图片_202212071920196" src="https://user-images.githubusercontent.com/116540903/206167178-9a7b338a-4568-4df4-8b90-85f2b1d86e86.png">
![微信图片_2022120719102010](https://user-images.githubusercontent.com/116540903/206167181-68acdc61-77ae-4811-968c-e684f42fc703.jpg)
![微信图片_2022120719102011](https://user-images.githubusercontent.com/116540903/206167185-a74afe3b-3225-4011-97fe-cf90bad8392b.jpg)
![微信图片_2022120719102012](https://user-images.githubusercontent.com/116540903/206167189-49dd0752-a368-40a4-94bb-37411e65fcc7.jpg)
![微信图片_2022120719102013](https://user-images.githubusercontent.com/116540903/206167190-328676a0-2493-4050-af23-86a335edcf4b.jpg)
![微信图片_2022120719102014](https://user-images.githubusercontent.com/116540903/206167191-f0436b08-1db2-4077-8a18-4137e0ffa834.jpg)
![微信图片_2022120719102015](https://user-images.githubusercontent.com/116540903/206167200-be42ae5f-41cc-4383-885b-033a4e9121aa.jpg)
![微信图片_2022120719102016](https://user-images.githubusercontent.com/116540903/206167212-a90b91b7-3df6-48d5-a19a-2b37e70c47d1.jpg)
![微信图片_2022120719102017](https://user-images.githubusercontent.com/116540903/206167215-ccc8bb12-b324-4983-8d3f-f14162b1b78f.jpg)
![微信图片_2022120719102018](https://user-images.githubusercontent.com/116540903/206167218-8faf823a-f171-4ac3-b85b-69cd304ee375.jpg)
![微信图片_2022120719102019](https://user-images.githubusercontent.com/116540903/206167222-91f43345-7414-4759-8e5c-c2784c8bab52.jpg)
![微信图片_2022120719102020](https://user-images.githubusercontent.com/116540903/206167228-dd6459bc-a505-43da-827c-173e50fb2a41.jpg)
![微信图片_20221207191019](https://user-images.githubusercontent.com/116540903/206167081-51c6820f-3f4e-48b2-a36a-9f43d4e7af8b.jpg)
![微信图片_20221207191020](https://user-images.githubusercontent.com/116540903/206167092-91de528c-aa99-4740-8f9b-da9fd5cf28f1.jpg)
<img width="1073" alt="微信图片_20221207192019" src="https://user-images.githubusercontent.com/116540903/206167095-b20b1745-71dc-4d96-9e2f-f257726c233d.png">
![微信图片_202212071910191](https://user-images.githubusercontent.com/116540903/206167100-7ca63c29-b414-409b-96b1-4dd4ad0a4a7f.jpg)
![微信图片_202212071910192](https://user-images.githubusercontent.com/116540903/206167106-8786aa6f-ac17-498f-953f-a6953ce6b727.jpg)
![微信图片_202212071910201](https://user-images.githubusercontent.com/116540903/206167110-58c82dad-ea50-4fe5-9412-c96bea4c0da5.jpg)
![微信图片_202212071910202](https://user-images.githubusercontent.com/116540903/206167114-67e63ebb-6cda-4c28-a64b-8ab41def3bf9.jpg)
![微信图片_202212071910203](https://user-images.githubusercontent.com/116540903/206167116-ca864e68-2266-4150-a2ab-ab8d948a989b.jpg)
![微信图片_202212071910204](https://user-images.githubusercontent.com/116540903/206167119-ee564060-515c-4ec2-a749-085b9230df5c.jpg)
![微信图片_202212071910205](https://user-images.githubusercontent.com/116540903/206167122-0ea13147-7149-47a7-9146-16c69ae97451.jpg)
![微信图片_202212071910206](https://user-images.githubusercontent.com/116540903/206167127-59b46f0d-4e2b-4058-bdb6-e3d7c57dea56.jpg)
![微信图片_202212071910207](https://user-images.githubusercontent.com/116540903/206167130-826b8db8-a143-4e4a-8cc1-b8002d5cc814.jpg)
![微信图片_202212071910208](https://user-images.githubusercontent.com/116540903/206167133-90241eeb-f2f6-4f02-be7f-0211f970d3df.jpg)
![微信图片_202212071910209](https://user-images.githubusercontent.com/116540903/206167146-8d2fad9e-9853-4ade-b3a4-5fbcc50c137b.jpg)
<img width="1073" alt="微信图片_202212071920191" src="https://user-images.githubusercontent.com/116540903/206167149-0bac056e-4da2-4c94-ba50-5e0444a270f0.png">
<img width="1073" alt="微信图片_202212071920192" src="https://user-images.githubusercontent.com/116540903/206167154-cc7034a4-ed3f-48c7-95ca-6c82009b2fdc.png">
<img width="1073" alt="微信图片_202212071920193" src="https://user-images.githubusercontent.com/116540903/206167159-5ef3256b-97d4-4019-8ba6-a8c88167ce39.png">
<img width="1073" alt="微信图片_202212071920194" src="https://user-images.githubusercontent.com/116540903/206167164-93a53e07-a697-493d-9d56-705a9fdb2295.png">

**Comment by cqh2022** [comment]
> Are there any related SPs? Or did you select the SPs you want to save?

At present, we are communicating with Nd labs, Newwebgroup, Greaterheat and Piknik. We will strictly follow the encapsulation rules to maximize the dispersion of data encapsulation SPs.

**Comment by psh0691** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacea527legopcbcwyqlsrfwdl273vcgbvvfrt5ltcn6kzeglsv5sjjy 
#### Address 
> f1maztm327vu3w4gvum7lbmohupao6et5s6xjlr2q
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1qdko4jg25vo35qmyvcrw4ak4fmuu3f5rif2kc7i
#### Id
> 8d490b91-5dc3-4a87-9d49-289b12ad4c30
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacea527legopcbcwyqlsrfwdl273vcgbvvfrt5ltcn6kzeglsv5sjjy

**Comment by kernelogic** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaobhrp6yapzylfkaiuefqsfgi4hhjogqruuzmzqltnhj5n27ndnw 
#### Address 
> f1maztm327vu3w4gvum7lbmohupao6et5s6xjlr2q
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### Id
> 8d490b91-5dc3-4a87-9d49-289b12ad4c30
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaobhrp6yapzylfkaiuefqsfgi4hhjogqruuzmzqltnhj5n27ndnw

**Comment by cryptowhizzard** [comment]
Flagging #1230 

Can you clarify why you did not follow up on the rules of Fil+? It seems you stored all datacap on one organisation / SP, located on a VPN in the USA. Out of this 3 there are 5 other SP's on your ip on ports 6000 / 6025. See below*

Second, i cannot perform any duediligence since none of the data stored is retrievable. See below*

Until explanation is given we cannot continue with this LDN for datacap.

Thanks for your understanding.

lotus net connect f01971600
f01971600 -> {12D3KooWBNh4V7JeEvYLKvSbGeMMMFJyB3vavEyEipqNYaZh9cNS: [/ip4/128.136.157.164/tcp/8004]}
ERROR: failed to parse multiaddr "f01971600": must begin with /

lotus net connect f01992630
f01992630 -> {12D3KooWSPav6xffB6rk8KL2xuEMgtQZJKGZusfEaM8PPT7NgtMo: [/ip4/128.136.157.164/tcp/8013]}
ERROR: failed to parse multiaddr "f01992630": must begin with /

lotus net connect f033462
f033462 -> {12D3KooWMrhzqoTb6rJUYcw15qpiwKsRLEiyNCXTsWW4pLnqYmyh: [/ip4/128.136.157.164/tcp/8010]}
ERROR: failed to parse multiaddr "f033462": must begin with /

VPN data :
nmap -O 128.136.157.164
Starting Nmap 7.80 ( https://nmap.org/ ) at 2023-01-18 09:56 CET
Nmap scan report for 128.136.157.164
Host is up (0.11s latency).
Not shown: 988 filtered ports
PORT STATE SERVICE
22/tcp open ssh
80/tcp open http
113/tcp closed ident
6000/tcp open X11
6001/tcp open X11:1
6002/tcp open X11:2
6009/tcp open X11:9
6025/tcp open x11
8002/tcp open teradataordbms
8008/tcp open http
8009/tcp open ajp13
8010/tcp open xmpp

telnet 128.136.157.164 6001
Trying 128.136.157.164...
Connected to 128.136.157.164.
Escape character is '^]'.
/multistream/1.0.0
^CConnection closed by foreign host.
telnet 128.136.157.164 6002
Trying 128.136.157.164...
Connected to 128.136.157.164.
Escape character is '^]'.
/multistream/1.0.0
^CConnection closed by foreign host.
telnet 128.136.157.164 6009
Trying 128.136.157.164...
Connected to 128.136.157.164.
Escape character is '^]'.
/multistream/1.0.0
^CConnection closed by foreign host.
telnet 128.136.157.164 6025
Trying 128.136.157.164...
Connected to 128.136.157.164.
Escape character is '^]'.
/multistream/1.0.0
^CConnection closed by foreign host.

Retrieval testing:

ERROR: offer error: retrieval query offer errored: failed to fetch piece to retrieve from: getting pieces for cid bafykbzacecxdtl7ytilqjknysbfr3igfrcvezeyj3kb43fcg4gjx3roea5mj6: getting pieces containing block bafykbzacecxdtl7ytilqjknysbfr3igfrcvezeyj3kb43fcg4gjx3roea5mj6: failed to lookup index for mh a0e40220ae39aff89a1704a9b8904b1da0c588aa4c9309da83cd9446e1937dc5c407589f, err: datastore: key not found

ERROR: offer error: retrieval query offer errored: failed to fetch piece to retrieve from: getting pieces for cid bafykbzacecxdtl7ytilqjknysbfr3igfrcvezeyj3kb43fcg4gjx3roea5mj6: getting pieces containing block bafykbzacecxdtl7ytilqjknysbfr3igfrcvezeyj3kb43fcg4gjx3roea5mj6: failed to lookup index for mh a0e40220ae39aff89a1704a9b8904b1da0c588aa4c9309da83cd9446e1937dc5c407589f, err: datastore: key not found

ERROR: offer error: retrieval query offer errored: failed to fetch piece to retrieve from: getting pieces for cid bafykbzacecxdtl7ytilqjknysbfr3igfrcvezeyj3kb43fcg4gjx3roea5mj6: getting pieces containing block bafykbzacecxdtl7ytilqjknysbfr3igfrcvezeyj3kb43fcg4gjx3roea5mj6: failed to lookup index for mh a0e40220ae39aff89a1704a9b8904b1da0c588aa4c9309da83cd9446e1937dc5c407589f, err: datastore: key not found

ERROR: offer error: retrieval query offer errored: failed to fetch piece to retrieve from: getting pieces for cid bafykbzacecxdtl7ytilqjknysbfr3igfrcvezeyj3kb43fcg4gjx3roea5mj6: getting pieces containing block bafykbzacecxdtl7ytilqjknysbfr3igfrcvezeyj3kb43fcg4gjx3roea5mj6: failed to lookup index for mh a0e40220ae39aff89a1704a9b8904b1da0c588aa4c9309da83cd9446e1937dc5c407589f, err: datastore: key not found

**Comment by cqh2022** [comment]
> Flagging #1230
> 
> Same SP's , same behaviour.
> 
> Can you clarify why you did not follow up on the rules of Fil+? It seems you stored all datacap on one organisation / SP, located on a VPN in the USA. Out of this 3 there are 5 other SP's on your ip on ports 6000 / 6025. See below*
> 
> Second, i cannot perform any duediligence since none of the data stored is retrievable. See below*
> 
> Until explanation is given we cannot continue with this LDN for datacap.
> 
> Thanks for your understanding.
> 
> lotus net connect f01971600 f01971600 -> {12D3KooWBNh4V7JeEvYLKvSbGeMMMFJyB3vavEyEipqNYaZh9cNS: [/ip4/128.136.157.164/tcp/8004]} ERROR: failed to parse multiaddr "f01971600": must begin with /
> 
> lotus net connect f01992630 f01992630 -> {12D3KooWSPav6xffB6rk8KL2xuEMgtQZJKGZusfEaM8PPT7NgtMo: [/ip4/128.136.157.164/tcp/8013]} ERROR: failed to parse multiaddr "f01992630": must begin with /
> 
> lotus net connect f033462 f033462 -> {12D3KooWMrhzqoTb6rJUYcw15qpiwKsRLEiyNCXTsWW4pLnqYmyh: [/ip4/128.136.157.164/tcp/8010]} ERROR: failed to parse multiaddr "f033462": must begin with /
> 
> VPN data : nmap -O 128.136.157.164 Starting Nmap 7.80 ( https://nmap.org/ ) at 2023-01-18 09:56 CET Nmap scan report for 128.136.157.164 Host is up (0.11s latency). Not shown: 988 filtered ports PORT STATE SERVICE 22/tcp open ssh 80/tcp open http 113/tcp closed ident 6000/tcp open X11 6001/tcp open X11:1 6002/tcp open X11:2 6009/tcp open X11:9 6025/tcp open x11 8002/tcp open teradataordbms 8008/tcp open http 8009/tcp open ajp13 8010/tcp open xmpp
> 
> telnet 128.136.157.164 6001 Trying 128.136.157.164... Connected to 128.136.157.164. Escape character is '^]'. /multistream/1.0.0 ^CConnection closed by foreign host. telnet 128.136.157.164 6002 Trying 128.136.157.164... Connected to 128.136.157.164. Escape character is '^]'. /multistream/1.0.0 ^CConnection closed by foreign host. telnet 128.136.157.164 6009 Trying 128.136.157.164... Connected to 128.136.157.164. Escape character is '^]'. /multistream/1.0.0 ^CConnection closed by foreign host. telnet 128.136.157.164 6025 Trying 128.136.157.164... Connected to 128.136.157.164. Escape character is '^]'. /multistream/1.0.0 ^CConnection closed by foreign host.
> 
> Retrieval testing:
> 
> ERROR: offer error: retrieval query offer errored: failed to fetch piece to retrieve from: getting pieces for cid bafykbzacecxdtl7ytilqjknysbfr3igfrcvezeyj3kb43fcg4gjx3roea5mj6: getting pieces containing block bafykbzacecxdtl7ytilqjknysbfr3igfrcvezeyj3kb43fcg4gjx3roea5mj6: failed to lookup index for mh a0e40220ae39aff89a1704a9b8904b1da0c588aa4c9309da83cd9446e1937dc5c407589f, err: datastore: key not found
> 
> ERROR: offer error: retrieval query offer errored: failed to fetch piece to retrieve from: getting pieces for cid bafykbzacecxdtl7ytilqjknysbfr3igfrcvezeyj3kb43fcg4gjx3roea5mj6: getting pieces containing block bafykbzacecxdtl7ytilqjknysbfr3igfrcvezeyj3kb43fcg4gjx3roea5mj6: failed to lookup index for mh a0e40220ae39aff89a1704a9b8904b1da0c588aa4c9309da83cd9446e1937dc5c407589f, err: datastore: key not found
> 
> ERROR: offer error: retrieval query offer errored: failed to fetch piece to retrieve from: getting pieces for cid bafykbzacecxdtl7ytilqjknysbfr3igfrcvezeyj3kb43fcg4gjx3roea5mj6: getting pieces containing block bafykbzacecxdtl7ytilqjknysbfr3igfrcvezeyj3kb43fcg4gjx3roea5mj6: failed to lookup index for mh a0e40220ae39aff89a1704a9b8904b1da0c588aa4c9309da83cd9446e1937dc5c407589f, err: datastore: key not found
> 
> ERROR: offer error: retrieval query offer errored: failed to fetch piece to retrieve from: getting pieces for cid bafykbzacecxdtl7ytilqjknysbfr3igfrcvezeyj3kb43fcg4gjx3roea5mj6: getting pieces containing block bafykbzacecxdtl7ytilqjknysbfr3igfrcvezeyj3kb43fcg4gjx3roea5mj6: failed to lookup index for mh a0e40220ae39aff89a1704a9b8904b1da0c588aa4c9309da83cd9446e1937dc5c407589f, err: datastore: key not found


I don't have this in my database and SP just tested it and can retrieve it, please check. bafykbzacecxdtl7ytilqjknysbfr3igfrcvezeyj3kb43fcg4gjx3roea5mj6

We are now storing the first copy, subsequent copies will find more SPs in different regions, sp told me it should be used like this lotus net connect f033462 should be replaced with lotus net connect /ip4/128.136.157.164/tcp/8010/p2p/ 12D3KooWMrhzqoTb6rJUYcw15qpiwKsRLEiyNCXTsWW4pLnqYmyh

Meanwhile, we are communicating with SPs such as SXX Future Data, and we are also considering decentralization in platforms such as BDE.

**Comment by cryptowhizzard** [comment]
Hi @cqh2022 

Thanks for the message.

It seems retrieval is working now, that is great.

If you want me to sign for the next datacap tranche please provide me with a list of SP's where you are going to store the data so i can their reputation and region.

Thanks!

**Comment by cqh2022** [comment]
> Hi @cqh2022
> 
> Thanks for the message.
> 
> It seems retrieval is working now, that is great.
> 
> If you want me to sign for the next datacap tranche please provide me with a list of SP's where you are going to store the data so i can their reputation and region.
> 
> Thanks!

Sorry, reply is a little late, because I have been off recently. As mentioned earlier, we are communicating with SPs such as SXX Future Data, Greatereat, etc., and we are also contacting with the person in charge of BDE to achieve data decentralized encapsulation. We hope to get your signature support. Thank you very much.

**Comment by cryptowhizzard** [comment]
Hello,

Sounds good.

If you want me to sign for the next datacap tranche please provide me with a list of SP's where you are going to store the data so i can their reputation and region.

**Comment by cqh2022** [comment]
> Hello,
> 
> Sounds good.
> 
> If you want me to sign for the next datacap tranche please provide me with a list of SP's where you are going to store the data so i can their reputation and region.

Recently have been busy communicating SPs, the initial communication is as follows：

Greaterheat——f033462、f01985775——Dallas, USA

Cabrina——f039940——Sichuan,China

SXX Future——f01964215——Guangdong,China
SXX Future——f01986229——Hubei,China

Guazi Dynamic——f01016254、f0694916——Asia

Of course we will continue to look for more SPs.

**Comment by xingjitansuo** [comment]
![image](https://user-images.githubusercontent.com/72185104/222049077-20ff8b03-c369-45e3-8109-ccfeddcdd250.png)

Random retrieval works. I will support this tranche.

**Comment by xingjitansuo** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacead7ag6er4zrbrnbq2tmfil6cu5pwpcrzhzmkqxv2i4ggjtbbu7vg 
#### Address 
> f1maztm327vu3w4gvum7lbmohupao6et5s6xjlr2q
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1a2lia2cwwekeubwo4nppt4v4vebxs2frozarz3q
#### Id
> c3890110-6b8f-4cc6-ad0a-19e0b7420a6e
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacead7ag6er4zrbrnbq2tmfil6cu5pwpcrzhzmkqxv2i4ggjtbbu7vg

**Comment by cqh2022** [comment]
> Hello,
> 
> Sounds good.
> 
> If you want me to sign for the next datacap tranche please provide me with a list of SP's where you are going to store the data so i can their reputation and region.

Hi, cryptowhizzard, can I get your signature for support? Very much looking forward to it.

**Comment by cqh2022** [comment]
> This application has not seen any responses in the last 14 days, so for now it is being closed. Please feel free to contact the Fil+ Gov team to re-open the application if it is still being processed. Thank you!

We have been dealing with bugs and now it seems that we can. @simon @deep @kevin @rg

**Comment by cqh2022** [comment]
> This application has not seen any responses in the last 10 days. This issue will be marked with Stale label and will be closed in 4 days. Comment if you want to keep this application open.

checker:

**Comment by cqh2022** [comment]
checker:manualTrigger

**Comment by cqh2022** [comment]
Sorry for the next round of DC quota bots are not triggering, please help to turn them on manually,thanks! @simonkim0515

**Comment by NewHuoPool** [comment]
checker:manualTrigger

**Comment by cryptowhizzard** [comment]
@cqh2022 

I tested your retrieval and this is working. Also the .avi stored is ok.

@filplus-govteam can you please implement 922 on this application and bring it to the latest standard so we can move on?

**Comment by Aaron01230** [comment]
checker:manualTrigger

**Comment by Aaron01230** [comment]
The report shows that  52.21% of deals are for data replicated across less than 4 storage providers, and there are 12 nodes deal with this LDN, are you planning to improve the data replication next round ?

**Comment by cqh2022** [comment]
> The report shows that 52.21% of deals are for data replicated across less than 4 storage providers, and there are 12 nodes deal with this LDN, are you planning to improve the data replication next round ?
Yes, in the next round we will increase the proportion of data with data backup greater than 4

**Comment by Aaron01230** [comment]
OK，the report shows that the retrieval rate is very high and the number of nodes is large. Since this is the third round, I believe that the client can gradually restore the data backup to meet the standards in the follow-up. I will support this round.

**Comment by Aaron01230** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb6brwhjawyqio5hqrhzuzy2hpbr3anvaz5cijhstnsr6jakopk5c 
#### Address 
> f1maztm327vu3w4gvum7lbmohupao6et5s6xjlr2q
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1xrnysd4gimg64d4l6qi7ulzwwq22c6vfg6lpw3i
#### Id
> e82b16d9-c651-4fb3-91cb-002324976072
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb6brwhjawyqio5hqrhzuzy2hpbr3anvaz5cijhstnsr6jakopk5c

**Comment by cqh2022** [comment]
> ## Request Proposed
> 
> Your Datacap Allocation Request has been proposed by the Notary
> #### Message sent to Filecoin Network
> 
> > bafy2bzaceb6brwhjawyqio5hqrhzuzy2hpbr3anvaz5cijhstnsr6jakopk5c
> 
> #### Address
> 
> > f1maztm327vu3w4gvum7lbmohupao6et5s6xjlr2q
> 
> #### Datacap Allocated
> 
> > 400.00TiB
> 
> #### Signer Address
> 
> > f1xrnysd4gimg64d4l6qi7ulzwwq22c6vfg6lpw3i
> 
> #### Id
> 
> > e82b16d9-c651-4fb3-91cb-002324976072
> 
> #### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb6brwhjawyqio5hqrhzuzy2hpbr3anvaz5cijhstnsr6jakopk5c

checker:manualTrigger

**Comment by 1ane-1** [comment]
checker:manualTrigger

**Comment by 1ane-1** [comment]
Please solve the deal data replication problem in the next round. Support it.

**Comment by 1ane-1** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceax3uejjvb24oudlzbg26thu6iuo25z6fdmpeo4y3syw7tszbt6xi 
#### Address 
> f1maztm327vu3w4gvum7lbmohupao6et5s6xjlr2q
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1mdk7s2vntzm6hu35yuo6vjubtrpfnb2awhgvrri
#### Id
> e82b16d9-c651-4fb3-91cb-002324976072
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceax3uejjvb24oudlzbg26thu6iuo25z6fdmpeo4y3syw7tszbt6xi

**Comment by cqh2022** [comment]
checker:manualTrigger

**Comment by cqh2022** [comment]
checker:manualTrigger

**Comment by cqh2022** [comment]
checker:manualTrigger

**Comment by cqh2022** [comment]
checker:manualTrigger

**Comment by Sunnyiscoming** [comment]
Hello, @cqh2022 per the https://github.com/filecoin-project/notary-governance/issues/922 for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

This information will be reviewed by Fil+ Governance team to confirm validity and then the application will be allowed to move forward for additional notary review.

**Comment by cqh2022** [comment]
checker:manualTrigger

**Comment by cqh2022** [comment]
> Hello, @cqh2022 per the [filecoin-project/notary-governance#922](https://github.com/filecoin-project/notary-governance/issues/922) for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.
> 
> This information will be reviewed by Fil+ Governance team to confirm validity and then the application will be allowed to move forward for additional notary review.

Submitted, thank you!

**Comment by herrehesse** [comment]
checker:manualTrigger

**Comment by cqh2022** [comment]
checker:manualTrigger

**Comment by cqh2022** [comment]
checker:manualTrigger

**Comment by Filplus-govteam** [comment]
SP List provided:
f02002141 | Henry |  Seoul, South Korea | NO | /
f02229545 | Black | Los Angeles, USA | NO | /
f029585 | Lucas | | USA | NO | /
f02812307 | Alice Xu | Singapore | NO | /
f02809368 | Tom Liu | Japan | NO | /

SPs taking deals:
**f02002141** | Seoul, Seoul, KRAmazon.com, Inc. | 17.00 TiB | 2.45% | 17.00 TiB | 0.00%
f01996825 | Seoul, Seoul, KRAmazon.com, Inc. | 14.00 TiB | 2.02% | 14.00 TiB | 0.00%
**f02229545** | Los Angeles, California, USCNSERVERS LLC | 23.94 TiB | 3.45% | 23.94 TiB | 0.00%
f01988794 | Dallas, Texas, USFlexential Colorado Corp. | 40.00 TiB | 5.77% | 40.00 TiB | 0.00%
f01985745 | Dallas, Texas, USFlexential Colorado Corp. | 40.00 TiB | 5.77% | 40.00 TiB | 0.00%
f01971600 | Dallas, Texas, USFlexential Colorado Corp. | 25.00 TiB | 3.61% | 25.00 TiB | 0.00%
f01992630 | Dallas, Texas, USFlexential Colorado Corp. | 23.98 TiB | 3.46% | 23.98 TiB | 0.00%
f033462 | Dallas, Texas, USFlexential Colorado Corp. | 20.00 TiB | 2.89% | 20.00 TiB | 0.00%
**f029585** | Dallas, Texas, USFlexential Colorado Corp. | 19.55 TiB | 2.82% | 19.55 TiB | 0.00%
f02368754 | Dallas, Texas, USFlexential Colorado Corp. | 17.94 TiB | 2.59% | 17.94 TiB | 0.00%
f02227496 | Hong Kong, Central and Western, HKIPTELECOM ASIA | 23.97 TiB | 3.46% | 23.97 TiB | 0.00%
**f02812307**new | Singapore, Singapore, SGIPTELECOM Global | 120.02 TiB | 17.32% | 120.02 TiB | 0.00%
f02812314new | Los Angeles, California, USIPTELECOM Global | 119.92 TiB | 17.30% | 119.92 TiB | 0.00%
**f02809368**new | Tokyo, Tokyo, JPIPTELECOM Global | 116.83 TiB | 16.86% | 116.83 TiB | 0.00%
f02229505 | Hong Kong, Central and Western, HKIPTELECOM Global | 23.91 TiB | 3.45% | 23.91 TiB | 0.00%
f02230309 | Putra Heights, Selangor, MYTechAvenue Malaysia | 23.19 TiB | 3.35% | 23.19 TiB | 0.00%
f02233568 | Paripark, Seoul, KRThe Constant Company, LLC | 23.78 TiB | 3.43% | 23.78 TiB | 0.00%

Many SP IDs are not matching the list provided @cqh2022 - please provide updated proof of SP Entity and distribution list, closing until updated
