### ISSUE TITLE
[DataCap Application]BrotherUnion

### ISSUE THREAD

**Issue by brotherunion2008** [filecoin-project/filecoin-plus-large-datasets#1244]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: BrotherUnion
- Website / Social Media:http://www.brotherunion.jp/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):2PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):150TiB
- On-chain address for first allocation: f1itu6g25zwh4xqtaijaapsunfe5s3da37njxeo5i

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
BrotherUnion is founded in 2008. We integrates the import and export sales and leasing of electrical equipment, and currently mainly provides unmanned aerial vehicles' rental business. At the same time, we also committed to promoting the quality of the human environment and promoting the recycling of all kinds of resources.

In recent years, with the continuous improvement of technology, the use of unmanned aerial vehicles, whether for personal use or commercial use, is growing. Unmanned aerial vehiclesare mostly used in photography, agriculture and other fields. Equipped with light-rich leds, pre-programmed and controlled by computers, hundreds of unmanned aerial vehicles can be flown to depict words and patterns in the night sky, making the LED screen appear in the night sky. It will not only be presented in 2D but also in 3D. Unmanned aerial vehicles can be used in active situations, such as performing with fireworks, displaying corporate logos in the sky, etc. They can be used to perform various kinds of performances according to design ideas. However, the purchase of unmanned aerial vehicles will be a large amount of money, so we provide users with rental and other services to meet the needs of customers for the use of unmanned aerial vehicles in different scenarios.
```

What is the primary source of funding for this project?
```
Mainly from our business revenue.
```

What other projects/ecosystem stakeholders is this project associated with?
```
None
```

## Use-case details

Describe the data being stored onto Filecoin
```
The data we store mainly includes the video backup and business data of our use of unmanned aerial vehicles in recent years after desensitization.
```

Where was the data in this dataset sourced from?
```
They are generated in the process of our business.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://github.com/brotherunion2008/Sample
https://29.gigafile.nu/1121-p7f6a24fcc55ae9714fcde8eb06f853f8
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes, this is a public dataset.
```

What is the expected retrieval frequency for this data?
```
It will almost never be retrieved.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
Permanent. And we will continue to store more data as our business evolves.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
We will mainly store in Southeast Asia, including but not limited to Japan, South Korea, Hong Kong.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
We plan to send the data to the corresponding sp in batches through hard disks through offline transmission.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We will choose a provider with a long service life to provide services for us. Although we don't access it often, we want our data to be stored permanently and visible to everyone. If there are service providers that meet the above criteria, please contact us.
```

How will you be distributing deals across storage providers?
```
Follow the community allocation principle.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes
```

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 2PiB

**Expected weekly DataCap usage rate**

> 150TiB

**Client address**

> f1itu6g25zwh4xqtaijaapsunfe5s3da37njxeo5i

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Looking at your application i have some questions:
As you are brand new on Github and have no history of past applications it seems to me that applying for 2PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?

Can you show us visible proof of the size of your data and the storage systems you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230232885049356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!
