### ISSUE TITLE
[DataCap Application] <Jiuzhang Algorithm www.jiuzhang.com> - <Jiuzhang Algorithm Courses>

### ISSUE THREAD

**Issue by xtt129** [filecoin-project/filecoin-plus-large-datasets#1245]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Jiuzhang Algorithm Tech.Co.Ltd.
- Website / Social Media: www.jiuzhang.com
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 400TiB
- On-chain address for first allocation: f1dgu6pdk4ixro7scz2h5w3ndey2ojthkikwjqb6q

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
Originated from Silicon Valley and headquartered in Hangzhou, Jiuzhang Algorithm is the largest Chinese online education company in North America. It mainly provides adult online education products for IT people. Our main business is job-hunting service for international students, online programming platform and enterprise technology recruitment tools. Our mission is to help China's technology industry take off with education.

The founding team has worked in world-class companies such as Facebook and Google in Silicon Valley. The core team members are all from Peking University, Tsinghua University, Zhejiang University, Harvard, Stanford and other world-renowned universities. 90% of them are born in the 1990s, comprising a company with high quality and great development potential.

Since its establishment in 2013, Jiuzhang has helped 30,000+ job seekers to obtain high-quality job opportunities from world-renowned Internet companies such as Alibaba, Tencent, NetEase, Google, and Facebook. It has a wide range of influence in the IT job search sector in mainland China and North America, and its job search education courses are also well received by students.

What is the primary source of funding for this project?
From ourselves.

What other projects/ecosystem stakeholders is this project associated with?
None.

## Use-case details

Describe the data being stored onto Filecoin
Parts of the course videos from our platform.

Where was the data in this dataset sourced from?
Free public courses from Jiuzhang Algorithms. Through nearly 10 years of international students' algorithm and interview coaching, we have accumulated a large number of free public courses.

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
https://www.jiuzhang.com/seminar/?page=1

        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
Yes, it's public for anyone.

What is the expected retrieval frequency for this data?
1-2 times/year

For how long do you plan to keep this dataset stored on Filecoin?
3-5 years

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
Basically in United States and China

How will you be distributing your data to storage providers? Is there an offline data transfer process?
Use offline transfer by hard drives or some other ways.

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
We tend to choose SPs in China or United States.
We will conduct spot checks on data retrieval from time to time to ensure that data can always be retrieved.

How will you be distributing deals across storage providers?
Store data in multiple SPs in a balanced manner to ensure data security.

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
Yes

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 400TiB

**Client address**

> f1dgu6pdk4ixro7scz2h5w3ndey2ojthkikwjqb6q
