### ISSUE TITLE
[DataCap Application] Shanghai Rongsheng Information Network Technology Co., LTD

### ISSUE THREAD

**Issue by fairy-and-flower** [filecoin-project/filecoin-plus-large-datasets#1250]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Shanghai Rongsheng Information Network Technology Co., LTD
- Website / Social Media: https://www.ronsheng-network.com
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100TiB
- On-chain address for first allocation: f1uzzjdd5nfwlo5rz6e3owsrqsliv3w6tf25ks5hy

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Shanghai Rongsheng Network Technology Co., Ltd. is a cultural media company integrating game promotion, CG creative production and advertising. Since the company was founded in 2018, has been dedicated to promote their business, always adhere to the "customer advertising information to a global audience, to sell customer's products and services to the global market" service tenet, with the "service" to insist on this team spirit, and form a set of research, planning, cooperation, leading examining, follow-up one-stop service system. 
We have a strong design team, SEM optimization team, customer service team for your services involving data research and analysis, consulting, advertising design, marketing strategy planning. 
(i) Shanghai Rongsheng always insists on using data and results to speak. In the field of short video and social networking, Shanghai Rongsheng has obtained the official qualification partner certification of many platforms and accumulated more than 1000 successful cases. 
(ii) We provide video editing, market analysis, creative production of advertising materials, CLOAK system review and agent operation services. 
(iii) All-media traffic ecosystem, covering the whole platform of high-quality traffic resources, the exclusive core CLOAK technology, no subscriber rejection, unlimited stream, generation operation.
```

What is the primary source of funding for this project?
```
Company funds
```

What other projects/ecosystem stakeholders is this project associated with?
```
None
```

## Use-case details

Describe the data being stored onto Filecoin
```
Designer's sketches, vertical drawings, CG clips, CG semi-finished products.
```

Where was the data in this dataset sourced from?
```
Our company's data.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://drive.google.com/file/d/17V0_7kP9n0B_SAeJnif1BQAMZD_NB4lU/view?usp=share_link
https://drive.google.com/file/d/1Ln3NRl-7BaeHFkvoJlFI5ET8osZr-X8p/view?usp=share_link
https://drive.google.com/file/d/1kRWLRX0CzGsQN_LS0bfFOmpvfANTnm5O/view?usp=share_link
https://drive.google.com/file/d/1aY6ETkngcG69j2WNegWn8wjKLpKdwDgG/view?usp=share_link
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes, this is all public data, not secret, and anyone can retrieve it.
```

What is the expected retrieval frequency for this data?
```
At present, you only need to back up files to prevent file loss due to a local storage breakdown.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
We want to store it on the filecoin network all the time.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Asia and Europe.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Due to the large amount of data, we want to send data offline
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
To ensure the security of data, five or more storage providers will be selected, and the storage providers will be required to enable quick retrieval to facilitate the review of data integrity.
```

How will you be distributing deals across storage providers?
```
Try to choose offline transmission, because the data volume is large, if choose to choose online transmission will occupy a lot of resources.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, we have the funds.
```

**Comment by frank-ang** [comment]
[Company and project overview video](https://drive.google.com/file/d/1mvV9GnwLpmZRp8MayKlIm56-9oIKgSGm/view?usp=sharing) posted for Nov 15th governance call.

**Comment by raghavrmadya** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 100TiB

**Client address**

>f1uzzjdd5nfwlo5rz6e3owsrqsliv3w6tf25ks5hy

**Comment by YuanHeHK** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedturyw5xhlqawq6mdpyqrgdiy4zzntsxvj24aq7lgjoorttln7yy 
#### Address 
> f1uzzjdd5nfwlo5rz6e3owsrqsliv3w6tf25ks5hy
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1fg6jkxsr3twfnyhdlatmq36xca6sshptscds7xa
#### Id
> c1855da9-4598-43d7-9107-da931f3dcb0b
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedturyw5xhlqawq6mdpyqrgdiy4zzntsxvj24aq7lgjoorttln7yy

**Comment by YuanHeHK** [comment]
This is my first signing for this client and I promise that I will keep track of their assignments.

**Comment by xingjitansuo** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedbggvtaakjoyeai4mfqijnlmvqwbv3oq7gyqwfhjzmf2bdiz5loy 
#### Address 
> f1uzzjdd5nfwlo5rz6e3owsrqsliv3w6tf25ks5hy
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1a2lia2cwwekeubwo4nppt4v4vebxs2frozarz3q
#### Id
> c1855da9-4598-43d7-9107-da931f3dcb0b
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedbggvtaakjoyeai4mfqijnlmvqwbv3oq7gyqwfhjzmf2bdiz5loy

**Comment by BigD-Exchange** [comment]
@fairy-and-flower Hi! Great to see you have gotten approval for DataCap and advancing the mission of preserving humanity’s most important information. If you are looking for storage providers to store these data or have any questions, please visit #bigdata-exchange on Filecoin Slack or reply here. 

We have strong demand from a diverse group of SPs, who are actively looking to onboard more data.
