### ISSUE TITLE
[DataCap Allocation] - System ISO dataset Application

### ISSUE THREAD

**Issue by liuxuf4i** [filecoin-project/filecoin-plus-large-datasets#1252]
---
name: Large Dataset Notary application
about: Clients should use this application form to request a DataCap allocation via a LDN for a dataset
title: "System ISO dataset Application"
labels: 'application, Phase: Diligence'
assignees: ''

---
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Guangdong Efly Cloud Computing Co.,Ltd
- Website / Social Media: https://www.eflycloud.com/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 500TiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 80TiB
- On-chain address for first allocation: f1qgheo4ojz676oxkrot76xgygvmfof52lde4k4ea
- Region: Greater China Region

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Guangdong Efly Cloud Computing Co.,Ltd (hereinafter called Efly Cloud), founded in 2007, is the leading internet service provider, cloud computing service provider and data center operator in China. Efly Cloud is committed to provide professional Cloud Computing Service, Internet Data Center (IDC), Content Distribution Network (CDN) and related solutions to various global industries, like finance, e-commerce, mobile internet, online games, portal sites, smart city, health care, education, trade, manufacturing, etc.
```

What is the primary source of funding for this project?
```
Company account
```

What other projects/ecosystem stakeholders is this project associated with?
```
no
```

## Use-case details

Describe the data being stored onto Filecoin
```
As a cloud service provider, we often need to provide customers with images of various types and versions, including various distributions of linux windows, and need to store them uniformly. For some reasons, the public images cannot be obtained, and the filecoin network needs to be used. to store these images
```

Where was the data in this dataset sourced from?
```
From various system version providers, such as ubuntu centos, etc.

```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://mirror.xtom.com/centos/7.9.2009/isos/x86_64/CentOS-7-x86_64-Everything-2009.iso
https://ubuntu.com/download/desktop/thank-you?version=22.10&architecture=amd64
ed2k://|file|cn_windows_10_enterprise_ltsc_2019_x64_dvd_9c09ff24.iso|4478906368|E7C526499308841A4A6D116C857DB669|/
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes, we confirm that all data is public.
```

What is the expected retrieval frequency for this data?
```
Maybe once a week or longer.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
Forever, depending on service and value.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
US,  Western Europe, asia.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Online transfer and offline copy.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
It is planned to select some experienced and stable storage providers in storing verification data.
```

How will you be distributing deals across storage providers?
```
Fair distribution according to platform rules.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes，we're ready for making deals.
```

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 500PiB

**Expected weekly DataCap usage rate**

> 80TiB

**Client address**

> f1qgheo4ojz676oxkrot76xgygvmfof52lde4k4ea

**Comment by newwebgroup** [comment]
Hey Client，
About KYC&KYB
1：Could you send an email to [filplus-app-review@fil.org](mailto:filplus-app-review@fil.org) ？

The content should include the number of the LDN application. If possible, please attach copies of the business license and other valid certificates

2：Can you provide more detailed information about other storage providers participated in this program, such as you can list SPs you have contacted with at present?
In addition, please specify your criteria for selecting SPs. I see that your retrieval frequency is frequent.If possible, please provide specific plans and what you plan to do with SPs to meet the high frequency of retrieval.

3.How large is your existing dataset? How much is the data growth per month?
