### ISSUE TITLE
[DataCap Application] <Ant Cluster> - <QCCS>

### ISSUE THREAD

**Issue by AntCluster** [filecoin-project/filecoin-plus-large-datasets#1263]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Ant Cluster
- Website / Social Media: https://www.myjq-ipfs.com
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100TiB
- On-chain address for first allocation: f1t7bfgjgcbkny46a2pry4ozv7wvd6izyaa35egka

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Ant Cluster is a professional digital technology solution provider. With blockchain technology as its core, the company is deeply involved in emerging technology fields such as big data, Internet of Things, blockchain, cloud computing, artificial intelligence and meta-universe.
```

What is the primary source of funding for this project?
```
The income generated by the company's operation of its own products.
```

What other projects/ecosystem stakeholders is this project associated with?
```
Qin Chu digital collection products(QCCS) operated by the company.
```

## Use-case details

Describe the data being stored onto Filecoin
```
We will store the NFT artwork storage data in Qin Chu's data collection on Filecoin, including pictures, videos, audio, etc.
```

Where was the data in this dataset sourced from?
```
We work with museums, cultural and creative institutions and famous artists to map the data content of cultural and creative works, artworks, cultural relics derivatives, etc., and store the data on Filecoin.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://raw.githubusercontent.com/AntCluster/datasets-sample/main/1659666271699ihju1zh2v2a.png
https://raw.githubusercontent.com/AntCluster/datasets-sample/main/1659666282813716ggnzm234.jpg
https://raw.githubusercontent.com/AntCluster/datasets-sample/main/1659671934852hkj4az6c0c5.jpg
https://raw.githubusercontent.com/AntCluster/datasets-sample/main/165969447696488esr7vnj2.jpg
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes, it is public data that can be retrieved by anyone.
```

What is the expected retrieval frequency for this data?
```
Monthly.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
We want to store data for at least 3 years.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Asia
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
We conduct online transmission through the designated platform, and can also provide offline data transmission when necessary.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We will choose a storage supplier with high consideration and experience in verifying data for trading.
```

How will you be distributing deals across storage providers?
```
We will find at least 5 storage suppliers and distribute the transactions as evenly as possible.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes. Our company has its own product operating income, and we can provide enough funds for it.
```

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 100TiB

**Client address**

> f1t7bfgjgcbkny46a2pry4ozv7wvd6izyaa35egka

**Comment by 1ane-1** [comment]
Can you explain your data composition and provide sufficient data samples more than 500T separately? 
How many copies will you store?
Could you send an email to [filplus-app-review@fil.org](mailto:filplus-app-review@fil.org) with your official domain in order to confirm your identity?

**Comment by 1ane-1** [comment]
> 
Hi，maybe you can show me that your data size screenshot to proof you have lots of data and the Sps you cooperated now。

**Comment by AntCluster** [comment]
the data storage screenshot have been sent to filplus-app-review@fil.org

**Comment by 1ane-1** [comment]
> the data storage screenshot have been sent to [filplus-app-review@fil.org](mailto:filplus-app-review@fil.org)

what about SPs? Can you sent the screenshot here?

**Comment by AntCluster** [comment]
what information about the SPs should be included in the screenshot?

**Comment by 1ane-1** [comment]
> 

Data screenshot and SPs node pls make pubilc here.

**Comment by AntCluster** [comment]
We have contacted some SPS, for example: f01033096, f0730942.
![image](https://user-images.githubusercontent.com/116699195/207001893-06b43679-7f5f-4442-8e13-8269c08a3916.png)

**Comment by cryptowhizzard** [comment]
Hello @AntCluster 


I see my fellow notaries have already started on due diligence. That is great and speeds up the proces to get you going.

What is missing is a data allocation plan.

For the Filecoin + program itself please note that by storing data on the Filecoin network you get 10x the power ( QAP ) of a normal sector. In return for this to be eligible for this incentive there are important rules to abide:

The data must be stored with multiple service providers. ( Not with one organization running multiple SP's but really independent organizations )
The data must be distributed over multiple regions. (Running a VPN is not allowed to fake presence in the USA for example)
The data must be retrievable by everyone in the community to check if you are really storing what you say you are storing. Running boost is highly recommended.
The data must be in line with the mission of FIL+. That means that the data must be valuable for humanity. It can be scientific or other things that people are highly interested in and is unique.
As data preparer you are allowed to store one copy yourself (if the client requests so for the sake of redundancy of the data). If you store your copy in Greater China it means that the other organizations/SP must be outside Greater China.

Can you provide us with a list of SP's that you will work with in the first allocation and who/where they are?
With that we can check on their reputation and avoid problems in later stages.

**Comment by cryptowhizzard** [comment]
Any news here? Is there anything i can do to speed up the proces?

**Comment by stcouldlisa** [comment]
I checked your data sample, it seems that these are all pictures downloaded from the Internet, can you provide more data examples?
<img width="551" alt="WX20230220-145243@2x" src="https://user-images.githubusercontent.com/112812896/220040234-0f6ae4e9-b839-4970-a6cb-b7013c398d10.png">
<img width="892" alt="WX20230220-153038@2x" src="https://user-images.githubusercontent.com/112812896/220040421-f63b8ca1-edff-4510-81a3-b4834c15b294.png">
