### ISSUE TITLE
[DataCap Application] <Quantitative Finance, Department of Mathematics, National University of Singapore> - <quantitative finance>

### ISSUE THREAD

**Issue by NationaUniversity** [filecoin-project/filecoin-plus-large-datasets#1264]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Quantitative Finance, Department of Mathematics, National University of Singapore
- Website / Social Media: https://www.math.nus.edu.sg/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 200TiB
- On-chain address for first allocation: f1iaezpdxjmhbobtngflwhfg7eqgxfhn2vmharkwq
- Type: Custom Notary
- Identifier: E-fil

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
National University of Singapore (NUS) Quantitative Finance (MSc in Quantitative Finance, hereinafter referred to as MQF) is a taught master's program offered under the Department of Mathematics of the Faculty of Science.

The Department of Mathematics of the National University of Singapore launched the Master of Quantitative Finance program in 2009. Supported by the Department of Economics and the Department of Statistics and Data Science of the National University of Singapore, the program is an interdisciplinary course that integrates financial mathematics, quantitative finance, and financial statistics. .

In recent years, the Quantitative Finance Master's Program has kept pace with the times, and the course content has been continuously deepen. At present, emerging sciences such as artificial intelligence and big data have been expanded. Master's degree program in quantitative finance was held with the cooperation of Shanghai Jiaotong University in China in 2016, which is currently the first master's degree program in quantitative finance certified by the Ministry of Education of the People's Republic of China.
```

What is the primary source of funding for this project?
```
From within ourselves.
```

What other projects/ecosystem stakeholders is this project associated with?
```
Filecoin Foundation.
```

## Use-case details

Describe the data being stored onto Filecoin
```
The project is mainly a data set of the quantitative finance major of the Department of Mathematics, National University of Singapore, including some teaching course videos, quantitative financial data and other partial data sets.
```

Where was the data in this dataset sourced from?
```
The data types are shown as below:
1. Mathematics course videos
2. Courseware
3. Seminars
4. Quantify financial data
5. Students’ interview videos
6. Data related to students’ assignments
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
No data sample link
Has been sent to Filplus team for review.
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
The data are all internal data of the school, only allowed to be viewed by the internal staff, it needs to be encrypted and cannot be made public.
After the notary has signed the confidentiality agreement, the data can be provided to the Fil plus team and the notary for KYC/KYB review.
```

What is the expected retrieval frequency for this data?
```
Once a year​.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
At least 3-5 years.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Global.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
We will distribute offline to storage providers.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We will focus on the running time of the SP, the stability of operation status, the size of the node, and the feature of whether it supports retrieval.
We need long-term storage suppliers who can provide high-quality and secured storage service.
```

How will you be distributing deals across storage providers?
```
We plan to allocate 500T allocation data to each storage provider, and roughly plan to do 10 backups.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, we have prepared our own funds for storage.
```

**Comment by kevzak** [comment]
Hello - I can confirm for the Fil+ team that @NationaUniversity has completed the Client Registration and Business Verification Check successfully.

**Comment by kevzak** [comment]
The only thing missing is the Data Storage Plan:
- How much Data, number of copies requried
Who are SPs, IDs, locations

**Comment by JohnsonWang-sg** [comment]
all these NUS data will be in Singapore, 10 data replicas is prefered. also recommend @newwebgroup to support.

**Comment by kevzak** [comment]
Hello @NationaUniversity I am checking in to see if you need any help with your application or finding SPs to store copies. Let me know. Thank you.

**Comment by NationaUniversity** [comment]
> 你好@NationaUniversity我正在检查您是否需要有关您的应用程序的任何帮助或寻找 SP 来存储副本。让我知道。谢谢。

Current progress.
Data prep being facilitated by NewWebGroup (expected to take another 10 days)
The data will be transferred to SP by offline mail (3 days)

Dataset size.
600T, plan to make 8 copies 

SP list.
NewWebGroup: 3 - 4 SPs (Hong Kong, China, other cities in China)
SXX: 2 SPs (Hubei, China, Guangdong, China)
ORIGIN STORAGE: 2 - 3 SPs (Singapore)
SPs will be recommended by the above technical service providers.
@kevzak

**Comment by kevzak** [comment]
Thank you @NationaUniversity for the details

@newwebgroup - please work with Frank from Filecoin Foundation on the following:
- SP miner IDs will be required and should be included in the application details
- an explanation why newwebgroup has 3-4 SP ids involved, as lead SP you should be in charge of 2 copies max, please confirm. Also for Origin and SXX, max 1 copy per SP. This should all be clear upfront.
- an explanation why data is just storing in China, HK. This is OK but NU should explain why not other geo locations so notaries understand. Otherwise, please consider more geo distribution of copies.
- proof of KYB (can be a call conducted with Frank and @NationaUniversity to confirm data owner, data details, SP storage plan)

**Comment by newwebgroup** [comment]
Thanks for the heads up, I will get in touch with Frank soon. @kevzak 

-What Client is saying is that the SP will be accessed through these 3 technical operators.
I will assist Client in confirming the SP ID and SP affiliation as soon as possible.

-Agreed to store 2 copies of the LD SP as Newwebgroup

-Expect to store 4 - 5 copies in Singapore and 3 copies in China
1 copy in other regions.

**Comment by kevzak** [comment]
Hello I can confirm that @NationaUniversity passed the KYC and KYB check for the E-Fil+ pilot. 

@newwebgroup please ensure the SPs involved (miner IDs, business name, location) and distribution plan is updated in this application for notaries to assess. Once complete, let me know and I'll trigger the application for review.

**Comment by newwebgroup** [comment]
Okay, thanks.

We will finalize the confirmation by Thursday

**Comment by NationaUniversity** [comment]
> 您好，我可以确定@NationaUniversity通过了E-Fil+测试点的KYC和KYB测试。
> 
> @newwebgroup请确保本申请中浸及的SP（矿工ID、公司名称、位置）和分配计划已更新，以提供公证人评价。完成后，请告诉我，我将触摸以摸。

@kevzak

**Comment by kevzak** [comment]
Hello I can confirm that @NationaUniversity has passed the KYC/KYB check required by completing a call with Filecoin Foundation to confirm client and dataset.

**Comment by kevzak** [comment]
## Datacap Request Trigger
#### Total DataCap requested 
> 5PiB
#### Expected weekly DataCap usage rate 
> 200TiB
#### Client address
> f1iaezpdxjmhbobtngflwhfg7eqgxfhn2vmharkwq

**Comment by kevzak** [comment]
For the first allocation request: Let's move forward with the update notary SLA (https://github.com/filecoin-project/notary-governance/discussions/807) and assign randomly:

@liyunzhi-666
@Fatman13

Please review application details above and note that this applicant passed the KYC/KYB requirements for E-Fil. Please comment by April 6th. Thanks!

**Comment by liyunzhi-666** [comment]
Hey @NationaUniversity , everything looks good so far by the comments in the issues. Can you send a sample of the data to my email yz.li@m.dapponline.io? I will sign it after confirming it.

**Comment by newwebgroup** [comment]
Hi Patrick @liyunzhi-666 
We have assisted NUS in sending a sample of the data from the course video to your email address, please check it.
<img width="943" alt="image" src="https://user-images.githubusercontent.com/100118145/230038537-458fd333-ecaa-47ae-bc79-dfb089d7d0d3.png">
<img width="1145" alt="image" src="https://user-images.githubusercontent.com/100118145/230038548-6788e26e-8bf2-4c82-8277-f5595c84603c.png">

**Comment by liyunzhi-666** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedzgitksch6g54ckm3gdtpbaout6sqg457ymxommkwx44ju63fl34 
#### Address 
> f1iaezpdxjmhbobtngflwhfg7eqgxfhn2vmharkwq
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1pszcrsciyixyuxxukkvtazcokexbn54amf7gvoq
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedzgitksch6g54ckm3gdtpbaout6sqg457ymxommkwx44ju63fl34

**Comment by Fatman13** [comment]
Sorry for the late reply. Just came back from a Chinese national holiday. Could you please share some sample data and your distribution plan to yu.leng@guazi.io? Thank you!

**Comment by newwebgroup** [comment]
Hey Fatman @Fatman13 
I also sent you the data sample and copied KZ
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1264#issuecomment-1497187286

**Comment by Fatman13** [comment]
Hello, all, somehow 1264 is not showing up on my dashboard?

![image](https://user-images.githubusercontent.com/1591330/230529819-ae93dd8e-6f05-4db4-b873-3e5c127b867b.png)

**Comment by Fatman13** [comment]
Hello, team, still getting this error somehow...

![image](https://user-images.githubusercontent.com/1591330/230704306-2a04fdaa-810a-4ee9-bfae-23b9c4fe38a2.png)

**Comment by Fatman13** [comment]
After couple retires, now i am getting this...

![image](https://user-images.githubusercontent.com/1591330/230704627-3bb4c321-c9fa-439b-bade-c591e16d2902.png)

**Comment by kevzak** [comment]
@Fatman13 with signing issues, still?

For the first allocation request: Let's move forward with the update notary SLA (https://github.com/filecoin-project/notary-governance/discussions/807) and assign randomly:

@xingjitansuo
@swatchliu

Please review application details above and note that this applicant passed the KYC/KYB requirements for E-Fil. Please comment by April 12th. Thanks!

**Comment by Carohere** [comment]
![image](https://user-images.githubusercontent.com/118327353/229260009-becf814c-9d62-457e-a1f7-49b447d10392.png)
 
Hi @NationaUniversity, can you specify the ownership (business name and contacts) of these SPs? A clear sp list will better help notaries to follow up on future allocations and cut down on your waiting time for signatures next.

**Comment by xingjitansuo** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceazuddnjvpflmnzltauktkxuslbnjzzzyrastgylmdqlgjzj4isrg 
#### Address 
> f1iaezpdxjmhbobtngflwhfg7eqgxfhn2vmharkwq
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1a2lia2cwwekeubwo4nppt4v4vebxs2frozarz3q
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceazuddnjvpflmnzltauktkxuslbnjzzzyrastgylmdqlgjzj4isrg

**Comment by Joss-Hua** [comment]
Hi @NationaUniversity, could you send more samples of the data to my email (huarenbin@foxmail.com)? I would like to follow up and sign it.

**Comment by newwebgroup** [comment]
Hi @Joss-Hua 
We have assisted NUS in sending a sample of the data from the course video to your email address, please check it.

**Comment by newwebgroup** [comment]
@Carohere 
You have been contacted on Slack and content has been sent to you

**Comment by fabriziogianni7** [comment]
## DataCap Allocation requested

#### Multisig Notary address
> f01940930

#### Client address
> f1iaezpdxjmhbobtngflwhfg7eqgxfhn2vmharkwq

#### DataCap allocation requested
> 200TiB

#### Id
> 568e5b3c-01da-4e1e-87a7-4b8bb7f4140g

**Comment by fabriziogianni7** [comment]
## DataCap Allocation requested

### Request number 2
#### Multisig Notary address
> f01940930

#### Client address
> f1iaezpdxjmhbobtngflwhfg7eqgxfhn2vmharkwq

#### DataCap allocation requested
> 200TiB

#### Id
> 568e5b3c-01da-4e1e-87a7-5b8bb7f4140g

**Comment by kevzak** [comment]
checker:manualTrigger

**Comment by Joss-Hua** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacea2yos3f4xrppywxpkyygvw7wc5ik2rxbitxl56qzo2nwmfi7r3b6 
#### Address 
> f1iaezpdxjmhbobtngflwhfg7eqgxfhn2vmharkwq
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1tfg54zzscugttejv336vivknmsnzzmyudp3t7wi
#### Id
> 568e5b3c-01da-4e1e-87a7-5b8bb7f4140g
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacea2yos3f4xrppywxpkyygvw7wc5ik2rxbitxl56qzo2nwmfi7r3b6

**Comment by laurarenpanda** [comment]
checker:manualTrigger

**Comment by laurarenpanda** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecwxkpuixcfpv6yesyjt3w3p2kiqztd6zsaa47w5vvg7qk2sq7gky 
#### Address 
> f1iaezpdxjmhbobtngflwhfg7eqgxfhn2vmharkwq
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1bp3tzp536edm7dodldceekzbsx7zcy7hdfg6uzq
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecwxkpuixcfpv6yesyjt3w3p2kiqztd6zsaa47w5vvg7qk2sq7gky

**Comment by newwebgroup** [comment]
checker:manualTrigger

**Comment by Fatman13** [comment]
checker:manualTrigger

**Comment by Fatman13** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceda4gs5pwbkcxcklzan2bzlrdvj467h72eobuyvjwwvbnbqlxbzuo 
#### Address 
> f1iaezpdxjmhbobtngflwhfg7eqgxfhn2vmharkwq
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1j3u7crhjzwb2cj5mq7vodlt4o66yoyci7lhcauy
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceda4gs5pwbkcxcklzan2bzlrdvj467h72eobuyvjwwvbnbqlxbzuo

**Comment by Fatman13** [comment]
Have been reached out by the client on Slack and discussed how they can be improving on the warnings given by CID checker.

**Comment by Tom-OriginStorage** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecgj4ibatbqckhohou3rwqogyd7dzkf3rdonnonbpvgtn7ozca2cw 
#### Address 
> f1iaezpdxjmhbobtngflwhfg7eqgxfhn2vmharkwq
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1q6bpjlqia6iemqbrdaxr2uehrhpvoju3qh4lpga
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecgj4ibatbqckhohou3rwqogyd7dzkf3rdonnonbpvgtn7ozca2cw

**Comment by newwebgroup** [comment]
checker:manualTrigger

**Comment by destor2023** [comment]
@NationaUniversity  Can you explain why why 71.08% of data is stored in less than 4 sps and why 1 sp sealed more than 30% of total datacap?

**Comment by NationaUniversity** [comment]
> @NationaUniversity 你能解释为什么 71.08% 的数据存储在不到 4 个 sps 中，为什么 1 个 sps 加密了超过 30% 的总数据量吗？

Because of the small amount of DCs in the early stages
so the amount is not distributed so evenly

We have noticed this problem and
Starting with this round, it will make the Cid checher results more compliant.

and sent you a sample of NUS data via Slack

**Comment by newwebgroup** [comment]
checker:manualTrigger

**Comment by laurarenpanda** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedm75iouclbbjoem6rhbln7paqz7d74liks5pswdqx3fwjb7fflne 
#### Address 
> f1iaezpdxjmhbobtngflwhfg7eqgxfhn2vmharkwq
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1bp3tzp536edm7dodldceekzbsx7zcy7hdfg6uzq
#### Id
> not found
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedm75iouclbbjoem6rhbln7paqz7d74liks5pswdqx3fwjb7fflne

**Comment by liyunzhi-666** [comment]
checker:manualTrigger

**Comment by liyunzhi-666** [comment]
⚠️ 1 storage providers sealed more than 30% of total datacap - [f01732345](https://filfox.info/en/address/f01732345): 37.08%
⚠️ 46.32% of deals are for data replicated across less than 4 storage providers.

Please continue to reduce the percentage or add new SPs in the next round. @NationaUniversity

**Comment by newwebgroup** [comment]
checker:manualTrigger

**Comment by Joss-Hua** [comment]
So far, everything is healthy, good job

**Comment by Joss-Hua** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebdswi5j5hfzvvgqoudkyt5jeqavqs5bckzbdjrxexxyrl27oml3c 
#### Address 
> f1iaezpdxjmhbobtngflwhfg7eqgxfhn2vmharkwq
#### Datacap Allocated
> 1.56PiB
#### Signer Address
> f1tfg54zzscugttejv336vivknmsnzzmyudp3t7wi
#### Id
> d9fb3980-fde9-44bb-b17c-7fa9468dd31f
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebdswi5j5hfzvvgqoudkyt5jeqavqs5bckzbdjrxexxyrl27oml3c

**Comment by herrehesse** [comment]
@NationaUniversity I am looking at your application and will try to do retrieval & unpacking this week to make sure everyting is in order. Can you answer why your distribution is not global?

> In which geographies (countries, regions) do you plan on making storage deals?
> Global.

Looking forward to your response.

**Comment by NationaUniversity** [comment]
> @NationaUniversity我正在查看您的申请，并将尝试在本周进行检索和拆包，以确保一切都井井有条。您能回答为什么您的发行版不是全球性的吗？
> 
> > 您计划在哪些地区（国家、地区）进行存储交易？
> > 全球的。
> 
> 期待你的回复。

This dataset is a Fil-E dataset, so retrieval is not supported.
A sample of the data has been sent to you via Slack as a validation.

Since our school is located in Singapore, we would like to have more data backups stored in Singapore, which is our request.
The region other than Singapore is based on the SP we work with.
We expect all data samples to be stored within the Asian region.

**Comment by herrehesse** [comment]
@NationaUniversity Retrieval should always be supported? Encryption is allowed on FIL-E but retrieval should work.

**Comment by herrehesse** [comment]
> We expect all data samples to be stored within the Asian region.

This, is not the same as how you applied.

> In which geographies (countries, regions) do you plan on making storage deals?
> Global.

**Comment by NationaUniversity** [comment]
> @NationaUniversity应该开始最终支持检查？FIL-E允许加密，但检查应该有效。

Agree with you
1. encryption of data so that anyone can support retrieval;
2. data encryption, only Client can retrieve;

What option to choose depends on the client itself, because our content is all course and student related data, so we want just us to be able to view the data content.
That's why we chose Fil-E, This is because it considers the customer's point of view and the needs are formulated by the customer.

Also on the issue of storage area, we want to store in the Asian region, but we actually store outside of Asia as well.

**Comment by Tom-OriginStorage** [comment]
checker:manualTrigger

**Comment by Tom-OriginStorage** [comment]
Packaging is relatively healthy and willing to support

**Comment by newwebgroup** [comment]
checker:manualTrigger

**Comment by Fatman13** [comment]
checker:manualTrigger

**Comment by Fatman13** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceau7crz4embmmcsjvsbcfioh7yg7wj25gaka7gqarhssxckdp5dja 
#### Address 
> f1iaezpdxjmhbobtngflwhfg7eqgxfhn2vmharkwq
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1j3u7crhjzwb2cj5mq7vodlt4o66yoyci7lhcauy
#### Id
> db5ad96b-c872-46a3-95e8-2804c69a66de
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceau7crz4embmmcsjvsbcfioh7yg7wj25gaka7gqarhssxckdp5dja

**Comment by Fatman13** [comment]
Reached out by client on Slack. Sample data checked, CIDchecker looks okay.

**Comment by NiwanDao** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaqzjcg5shb2fyy4h3pyxfpzls4wjjl4j5k5ll6qppp375bm6yn4a 
#### Address 
> f1iaezpdxjmhbobtngflwhfg7eqgxfhn2vmharkwq
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1a2lia2cwwekeubwo4nppt4v4vebxs2frozarz3q
#### Id
> db5ad96b-c872-46a3-95e8-2804c69a66de
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaqzjcg5shb2fyy4h3pyxfpzls4wjjl4j5k5ll6qppp375bm6yn4a

**Comment by PluskitOfficial** [comment]
Everything looks well. Willing to support.

**Comment by stcouldlisa** [comment]
Looks good, willing to support

**Comment by stcouldlisa** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebbbix3gpei6r5k3xn52wzn6slmdcttpu2emjye4ikbzkqjwyjsbk 
#### Address 
> f1iaezpdxjmhbobtngflwhfg7eqgxfhn2vmharkwq
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1jvvltduw35u6inn5tr4nfualyd42bh3vjtylgci
#### Id
> 57141b7c-35f6-4923-abd2-39e8e66ae74c
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebbbix3gpei6r5k3xn52wzn6slmdcttpu2emjye4ikbzkqjwyjsbk

**Comment by stcouldlisa** [comment]
checker:manualTrigger

**Comment by stcouldlisa** [comment]
Others are very good, the retrieval report needs to be improved, I will continue to pay attention

**Comment by XnMatrixSV** [comment]
Everything looks healthy. I would like to support this. Good work!

**Comment by XnMatrixSV** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacednlta7w63dgy4aa7vk7gtmzxviywwywxasgpz2lwhjfdy7occ4wy 
#### Address 
> f1iaezpdxjmhbobtngflwhfg7eqgxfhn2vmharkwq
#### Datacap Allocated
> 322.55TiB
#### Signer Address
> f1bcvvwv3w6az7ivhdzory7anha54ocrlkxazm3yq
#### Id
> 4075c49a-4fbe-4d7d-8a44-8b8408c11b4b
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacednlta7w63dgy4aa7vk7gtmzxviywwywxasgpz2lwhjfdy7occ4wy

**Comment by herrehesse** [comment]
checker:manualTrigger

**Comment by herrehesse** [comment]
Not supportive of this datacap request for two reasons:

1. Client stated to distribute deals globally, but all SP's are using VPN services (cant track real location) and no deal has gone to Europe or USA.

2. None of the files are retrievable, while tools such as HTTP/BITSWAP-retrieval are working properly currently. 

If the two above are resolved, and I can retrieve the files, willing to support next rounds and conduct file checks.
