### ISSUE TITLE
[DataCap Allocation] - 申请 存储 重要数据 DataCap 额度

### ISSUE THREAD

**Issue by txysgit** [filecoin-project/filecoin-plus-large-datasets#1265]
---
name: Large Dataset Notary application
about: Clients should use this application form to request a DataCap allocation via a LDN for a dataset
title: "关于重要数据 DataCap 存储额度申请 About important data DataCap storage quota application"
labels: 'application, Phase: Diligence'
assignees: ''

---
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: 中康尚德健康管理（北京）有限公司 Zhongkang ShangDe Health Management (Beijing) Co., Ltd.
- Website / Social Media: tiexinyisheng.com
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 3PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100TiB
- On-chain address for first allocation: f3qzcdd33as5aenoeyqljrfj3hcek3eapee6us6ee4gczaek3bprweruvg25tczuyhp2soy4z2xugcvblalycq
- Region: Greater China Region

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
公司成立于2013年，是中国最早做互联网医疗的公司，同时也国内领先的高端医疗服务提供商；公司致力于“精准的医患撮合，构建医疗资源共享生态圈”，在国内和国际形成了完整会诊和转诊服务，在日本，美国，印度，泰国等有良好的医疗资源；公司主要业务包括医生实现及时通讯、患者管理、辅助医疗、电子病历、远程就诊、云盘储存等服务；当前主要焦距医疗数据的存储，挖掘，分析和应用，公司未的很多项目都将立足于区块链技术和医疗产品的结合创新，以应用于用户的个人健康管理、医学研究，药物研究等行业领域
Founded in 2013, the company is the earliest Internet medical company in China, and it is also a leading high-end medical service provider in China; the company is committed to "accurate doctor-patient matching and building a medical resource sharing ecosystem", forming a domestic and international network Complete consultation and referral services, with good medical resources in Japan, the United States, India, Thailand, etc.; the company's main business includes doctors' real-time communication, patient management, auxiliary medical care, electronic medical records, remote consultation, cloud storage and other services; currently The main focus is the storage, mining, analysis and application of medical data. Many of the company's future projects will be based on the combined innovation of blockchain technology and medical products to be applied to users' personal health management, medical research, drug research and other industries.

```

What is the primary source of funding for this project?
```
主要资金来源为自有资金
private capital

```

What other projects/ecosystem stakeholders is this project associated with?
```
自有资源，完全自主独立项目，暂无其他利益相关者
Self-owned resources, completely independent independent project, no other stakeholders

```

## Use-case details

Describe the data being stored onto Filecoin
```
医疗图像、医疗数据报告等各类医疗分析数据
Various medical analysis data such as medical images and medical data reports

```

Where was the data in this dataset sourced from?
```
近十年以来，大量用户在公司业务中产生的真实医疗数据
In the past ten years, real medical data generated by a large number of users in the company's business

```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
http://www.xfzyxnw.com:9000/data/skin_Images_sample.zip
数据链接只保存7天，请注意查收
The data link is only saved for 7 days. Please check
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
不是，这是我们公司的私有数据
No, this is our company's private data

```

What is the expected retrieval frequency for this data?
```
根据公司业务需要，不定时按需检索
According to the company's business needs, search on demand from time to time

```

For how long do you plan to keep this dataset stored on Filecoin?
```
540天
540 days

```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
中国
China

```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
通过服务器传输。有离线数据传输过程。
transmitted through the server. There is an offline data transfer process.

```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
我们会选择我们信任的存储提供商。因为属于私有数据，暂未打算对本公司以外的其他组织或个人开放访问权限。
We choose storage providers we trust. Because it is private data, it is not planned to open access to other organizations or individuals outside the company.

```

How will you be distributing deals across storage providers?
```
我们将首选我们信任的存储提供商
We will prefer storage providers we trust

```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
我们有充足的资源和资金支持此后的交易；同时如果可以，我们希望社区能在大量数据传输的快速方式上提供一些技术支持与建议
We have sufficient resources and funds to support future transactions; at the same time, if possible, we hope that the community can provide some technical support and suggestions on a fast way to transfer large amounts of data

```

**Comment by txysgit** [comment]
> **感谢您的请求！**
> 
> ```
> Heads up, you’re requesting more than the typical weekly onboarding rate of DataCap!
> ```
The weekly application datacap has been revised as required

**Comment by txysgit** [comment]
> **感谢您的请求！**
> 
> ```
> Heads up, you’re requesting more than the typical weekly onboarding rate of DataCap!
> ```

The weekly application datacap has been revised as required

**Comment by txysgit** [comment]
> **感谢您的请求！**
> 
> ```
> Heads up, you’re requesting more than the typical weekly onboarding rate of DataCap!
> ```

The weekly application datacap has been revised as required

**Comment by Sunnyiscoming** [comment]
> Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
> 
> 不是，这是我们公司的私有数据
> No, this is our company's private data

@kevzak Hi, Kevin. This is a E-FIL+ application.

**Comment by kevzak** [comment]
Hello @txysgit  - because you are looking to store private data, you should apply for DataCap via the E-Fil+ program https://efilplus.super.site/

Please have the data applicant complete a registration form: [LINK](https://docs.google.com/forms/d/e/1FAIpQLSeAaM0duQFDGUmQ5c7e--FVez7fXGOkLZlUPSkfpbBMfmwXsw/viewform)

**Comment by simonkim0515** [comment]
Closing due to no response. Please feel free to reapply.
