### ISSUE TITLE
[DataCap Application]Multiverse Labs

### ISSUE THREAD

**Issue by multiverse2022** [filecoin-project/filecoin-plus-large-datasets#127]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Multiverse Labs
- Website / Social Media: https://www.multiverse.ai/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100TiB
- On-chain address for first allocation: f3rwiidkpjbprpwxo54kqxisc7xxaxko4u3zlld7yj6cagzdsg4ypcdejacqzpcb7mstdq7znl2mflp2q4fyqq

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Multiverse is the first true metaverse, with a token system and novel blockchain which allows for full decentralization, commerce, and recreation. It’s an ecosystem for building new ideas into startups and projects, all interconnected by our metaverse ecosystem, A.I. algorithms, community, and economy. A true metaverse requires actual businesses and individuals to operate and earn within it; otherwise, it’s simply an amusement park. Existing approaches are either centralized (social networks), solely recreation (i.e. most people cannot earn a living within Fortnite), or limited to virtual real estate speculation. They are more akin to virtual theme parks or sandboxes with centralized control. Multiverse’s A.I. algorithms allow it to adapt, accept decentralized governance, and operate autonomously without human corruption or biases.
```

What is the primary source of funding for this project?
```
Multiverse currently has over 50 venture capital funds participating and dozens of new startups building their businesses within our ecosystem. 
```

What other projects/ecosystem stakeholders is this project associated with?
```
Multiverse has partnered with some of world’s most renowned companies and projects. For example, Multiverse announced plans to launch a Filecoin planet in the Multiverse ecosystem. This enables all planet founders in Multiverse to store and backup their data via decentralized storage. [
](https://www.multiverse.ai/news/filecoin-to-launch-distributed-storage-planet-in-multiverse-ecosystem)
```

## Use-case details

Describe the data being stored onto Filecoin
```
Neural network data for machine learning. We may start with medical images.
```

Where was the data in this dataset sourced from?
```
From publicly accessible dataset. To start with, we plan using dataset from Digital Pathology Association’s imaging repository.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://bio-atlas.psu.edu/view.php?s=1761&z=2&c=22013,10742
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
We will only use openly accessible data. 
```

What is the expected retrieval frequency for this data?
```
At present, the retrieval frequency is relatively low. Once more people choose to do machine learning using these data, the retrieval frequency will be higher.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
The plan is to do permanent storage.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
North America, Singapore, Europe or and other geographical regions satisfy our needs.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
We will distribute the data to storage providers both online and offline.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We will consider numerous factors including location, experience in dealing with data and companies’ background.
```

How will you be distributing deals across storage providers?
```
We will abide the norms of the community and distribute among the providers in a reasonable and fair manner.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, we have sufficient funds and resources
```

**Comment by Fenbushi-Filecoin** [comment]
Can you provide more details on the use-case? How is it related to the Multiverse blockchain?

**Comment by Fenbushi-Filecoin** [comment]
Can you provide more details on the use case? How is it related to the Multiverse blockchain?

**Comment by multiverse2022** [comment]
The data are used for machine learning by the projects in our Multiverse system. For example, medical/biology companies/projects partnered with us will use the annotated cancer/tumor scan image for neutral network machine learning, for the purpose of their R&D.

The machine learning process will not be happened on our blockchain. The Multiverse platform supports these projects by allowing users to stake on projects they consider promising.  Each user's stake/unstake and how much each project got staked are recorded on the Multiverse blockchain.

**Comment by multiverse2022** [comment]
> Can you provide more details on the use case? How is it related to the Multiverse blockchain?

The data are used for machine learning by the projects in our Multiverse system. For example, medical/biology companies/projects partnered with us will use the annotated cancer/tumor scan image for neutral network machine learning, for the purpose of their R&D.

The machine learning process will not be happened on our blockchain. The Multiverse platform supports these projects by allowing users to stake on projects they consider promising. Each user's stake/unstake and how much each project got staked are recorded on the Multiverse blockchain.

**Comment by Fenbushi-Filecoin** [comment]
> 

Sounds legit. Would like to be the notary for this application.

**Comment by Fenbushi-Filecoin** [comment]
> > Can you provide more details on the use case? How is it related to the Multiverse blockchain?
> 
> The data are used for machine learning by the projects in our Multiverse system. For example, medical/biology companies/projects partnered with us will use the annotated cancer/tumor scan image for neutral network machine learning, for the purpose of their R&D.
> 
> The machine learning process will not be happened on our blockchain. The Multiverse platform supports these projects by allowing users to stake on projects they consider promising. Each user's stake/unstake and how much each project got staked are recorded on the Multiverse blockchain.

Sounds legit. Would like to be the notary for this application.

**Comment by galen-mcandrew** [comment]
## Multisig Notary requested
#### Total DataCap requested 
> 5PiB
#### Expected weekly DataCap usage rate 
> 100TiB

**Comment by MRJAVAZHAO** [comment]
@multiverse2022 
Hi，Multiverse Labs.
Have You got the data usage permission from Digital Pathology Association?
Can you give us more information about Digital Pathology Association, like website, registered address, etc.

**Comment by TimWilliams00** [comment]
You‘d better get the web owners' permission before using these datasets? Including but not limited to this website：https://bio-atlas.psu.edu

**Comment by multiverse2022** [comment]
> @multiverse2022 Hi，Multiverse Labs. Have You got the data usage permission from Digital Pathology Association? Can you give us more information about Digital Pathology Association, like website, registered address, etc.

Hi MRJAVAZHAO, so Digital Pathology Association's imaging repository is basically a website with links to the imaging repository of various research institutions.[ ](https://digitalpathologyassociation.org/whole-slide-imaging-repository)

Each link will direct you to a separate institution(eg. Emory University, Penn State University, Cancer Imaging Archive). The date policy regarding if we can use it freely depends on each institution's policy. The plan is to start with those we can use freely, and there are plenty of them.[ ](https://wiki.cancerimagingarchive.net/display/Public/Data+Usage+Policies+and+Restrictions)
For example, the Caner Imaging Archive specified clearly that "most data are freely available to browse, download, and use for commercial, scientific and educational purposes".
There's also future plan to get permission from those institutions who didn't specify their policies on data usage. However, we will start with images that are said to be freely usable in their data policies, and there's plenty.

**Comment by multiverse2022** [comment]
> You‘d better get the web owners' permission before using these datasets? Including but not limited to this website：https://bio-atlas.psu.edu

Yes sir. The link I posted didn't specify their data usage policy per se, but I was posting this link for ease of access for you guys. Other image depository only have huge files to be download. 
The plan is to start with images that are obviously free to use, with specification in their websites.

**Comment by IreneYoung** [comment]
It looks good. We'd like to support the request. But it seems your company have no business related to Filecoin or IPFS before. Are you sure you can handle the Datacap allocation and storage deals with various miners properly?

**Comment by IreneYoung** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebu3fmilk7tzk5hgeevxh4tuehzqqppzozpyjfhnjtmp7vqei6366 
#### Address 
> f3rwiidkpjbprpwxo54kqxisc7xxaxko4u3zlld7yj6cagzdsg4ypcdejacqzpcb7mstdq7znl2mflp2q4fyqq
#### Datacap Allocated
> 50TiB
#### Signer Address
> f1d4gmpqz3execjj2wvrxuuhvbms5mzh7t7yqrviq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebu3fmilk7tzk5hgeevxh4tuehzqqppzozpyjfhnjtmp7vqei6366

**Comment by flyworker** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceax4eu2xsrr46fbjxchci6ep6bnpwca2pzzdkd5jfybxnpyvuoi7q 
#### Address 
> f3rwiidkpjbprpwxo54kqxisc7xxaxko4u3zlld7yj6cagzdsg4ypcdejacqzpcb7mstdq7znl2mflp2q4fyqq
#### Datacap Allocated
> 50TiB
#### Signer Address
> f1hlubjsdkv4wmsdadihloxgwrz3j3ernf6i3cbpy
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceax4eu2xsrr46fbjxchci6ep6bnpwca2pzzdkd5jfybxnpyvuoi7q

**Comment by mr-spaghetti-code** [comment]
Hi,

It looks like you received 50TiBs of DataCap to date but have spent less than 20% of it so far.

We would love to understand if there's anything holding you back. We are working hard to make the data onboarding process easier for clients like you and your feedback is very valuable. If you have a moment, please fill in this survey: https://forms.gle/s6AuTXZPZSMokscLA

If you have any feedback or would like to consult with an expert, please let me know. 

Thanks,

João Fiadeiro
Product Manager, Large Data Client Onboarding
Protocol Labs

**Comment by filplus-checker** [comment]
## DataCap and CID Checker Report[^1]
 - Organization: `Multiverse Labs`
 - Client: `f3rwiidkpjbprpwxo54kqxisc7xxaxko4u3zlld7yj6cagzdsg4ypcdejacqzpcb7mstdq7znl2mflp2q4fyqq`
### Storage Provider Distribution
The below table shows the distribution of storage providers that have stored data for this client.

If this is the first time a provider takes verified deal, it will be marked as `new`.

For most of the datacap application, below restrictions should apply.
 - Storage provider should not exceed 25% of total datacap.
 - Storage provider should not be storing duplicate data for more than 20%.
 - Storage provider should have published its public IP address.
 - All storage providers should be located in different regions.

⚠️ [f01372912](https://filfox.info/en/address/f01372912) has sealed 100.00% of total datacap.

⚠️ 50.00% of total deal sealed by [f01372912](https://filfox.info/en/address/f01372912) are duplicate data.

⚠️ All storage providers are located in the same region.

| Provider                                              |                 Location | Total Deals Sealed | Percentage | Unique Data | Duplicate Deals |
| :---------------------------------------------------- | -----------------------: | -----------------: | ---------: | ----------: | --------------: |
| [f01372912](https://filfox.info/en/address/f01372912) | Singapore, Singapore, SG |           3.13 TiB |    100.00% |    1.56 TiB |          50.00% |

![Provider Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/127/1671092550567.png)
### Deal Data Replication
The below table shows how each many unique data are replicated across storage providers.
- No more than 25% of unique data are stored with less than 4 providers.

⚠️ 100.00% of deals are for data replicated across less than 4 storage providers.

| Unique Data Size | Total Deals Made | Number of Providers | Deal Percentage |
| ---------------: | ---------------: | ------------------: | --------------: |
|         1.56 TiB |         3.13 TiB |                   1 |         100.00% |

![Replication Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/127/1671092551261.png)
### Deal Data Shared with other Clients
The below table shows how many unique data are shared with other clients.
Usually different applications owns different data and should not resolve to the same CID.

✔️ No CID sharing has been observed.

[^1]: To manually trigger this report, add a comment with text `checker:manualTrigger`
