### ISSUE TITLE
[DataCap Allocation] - Test application (please ignore)

### ISSUE THREAD

**Issue by orvn** [filecoin-project/filecoin-plus-large-datasets#1271]
---
name: Large Dataset Notary application
about: Clients should use this application form to request a DataCap allocation via a LDN for a dataset
title: "Test application (please ignore)"
labels: 'application, Phase: Diligence'
assignees: ''

---
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Filecoin
- Website / Social Media: https://filecoin.io
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 500TiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 1TiB
- On-chain address for first allocation: f123456
- Region: Europe

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
hello world
```

What is the primary source of funding for this project?
```
hello world
```

What other projects/ecosystem stakeholders is this project associated with?
```
hello world
```

## Use-case details

Describe the data being stored onto Filecoin
```
hello world
```

Where was the data in this dataset sourced from?
```
hello world
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
hello world
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
hello world
```

What is the expected retrieval frequency for this data?
```
hello world
```

For how long do you plan to keep this dataset stored on Filecoin?
```
hello world
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
xhello world
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
hello world
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
hello world
```

How will you be distributing deals across storage providers?
```
hello world
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
hello world
```

**Comment by orvn** [comment]
This was an internal test, closing the ticket

**Comment by data-programs** [comment]
<img width="32" alt="KYC" Verified src="https://stable.filplus.storage/images/filplus-kyc-verified-badge.png"/>

This user’s identity has been verified through [filplus.storage](https://filplus.storage)
