### ISSUE TITLE
[DataCap Application] <Xuewujing Education Consulting> - <Course>

### ISSUE THREAD

**Issue by schonLee** [filecoin-project/filecoin-plus-large-datasets#1272]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Xiangyang Xuewujing Education Consulting Co., Ltd.
- Website / Social Media:http://xy.xwjjyw.com/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):2PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):80TiB
- On-chain address for first allocation:f1gb6wxxjchmwfsjjvie6ldoy6ensbqr6p5b3gxty

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Xuewujing (Live&Learn) Education was established in 2014. The main business of the company is to provide various quality courses and provide students with personalized textbooks, teaching plans and courses, including eloquence, hosting, art, calligraphy, chess, puzzles, programming and art exams, etc. Wait. Committed to making every student enjoy an ideal education, helping children cross the boundaries of knowledge and ability, and helping every child grow in an all-round way. At present, it has a number of directly-operated personalized tutoring campuses in Hubei, Shanxi, Henan and other provinces, with a total area of more than 20,000 square meters.
```

What is the primary source of funding for this project?
```
Acquired by providing course services etc.
```

What other projects/ecosystem stakeholders is this project associated with?
```
NO other stakeholder. 
```

## Use-case details

Describe the data being stored onto Filecoin
```
Various types of data such as text, pictures, documents, audio, and video, which involve various types of courses, including subjects, art, and programming.
```

Where was the data in this dataset sourced from?
```
The data we want to store are all kinds of subject textbooks, teaching resources, and various teaching plans and teaching videos produced by teachers.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://www.aliyundrive.com/s/8QkmQvTf7yP/folder/636b690be3329c8d2ad1416bbe96942b5a2bceb3
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes, it is a public data.
```

What is the expected retrieval frequency for this data?
```
This data is mainly used for learning sharing and training for new recruits within the company, and the retrieval frequency is about twice a year.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
This data belongs to resource sharing data. We want to store it temporarily for two years. If it is suitable and convenient, we hope to store it permanently for a long time.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Asia.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
If it is in China, we will adopt online upload data transmission; if it is in other parts of Asia, we may change to offline method.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We plan to look for storage providers on slack, and then we could know more about their qualifications, product prices, and team size through online or offline meetings. Then we will start cooperation after confirmation.
```

How will you be distributing deals across storage providers?
```
We will first contact at least 4 storage providers for transactions to ensure distributed storage of data. In this way, the proportion of data stored by each storage provider will not exceed 25% of our total application.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
We have prepared sufficient funds for this work, and we can start storing transactions immediately after approval. The official slack channel can help us understand Filecoin better.
```

**Comment by Sunnyiscoming** [comment]
You use data of other platforms as the data samples, such as Jingtongxuetang, Kuke. Have you authorized to store these data as public data on the Filecoin network?
Can you explain your data composition and provide sufficient data samples separately? How many copies will you store?
What's the relationship between you and the organization?
Can you provide more detailed information about other storage providers participated in this program, such as you can list SPs you have contacted with at present?

**Comment by simonkim0515** [comment]
Due to no response, this application will close. The data owner may reapply.
