### ISSUE TITLE
[DataCap Application] Inlan Fashion Co., Limited

### ISSUE THREAD

**Issue by inlanfashion** [filecoin-project/filecoin-plus-large-datasets#1273]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Inlan Fashion Co., Limited
-  Website / Social Media: www.inlan-fashion.com
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):100TiB
- On-chain address for first allocation: f1zuasorixabj4k5qwt63v5kbjchqmwdl6dzgrkyq

Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer.

## Project details

Share a brief history of your project and organization.
Inlan fashion was established in 2017 We are professional jewelry manufacturer with trading department, company in Shenzhen and factory in Chang an Dongguan. For most of products from design artwork to productions we all make them in-house with good quality and time management. Our main products are women fashion jewelry which have very good reputation. The main feature of the product is to highlight the temperament and charm of mature women, of course, we also can produce men’s and children’s jewelry. The main material of our product is brass, alloy, stainless steel and so on. Our products are mainly exported to the UK, AUS, the USA and so on. The founder of the company is a normal woman. With her passion for life and analysis of market trends. She keeps creating novelty and smart products, thus realizing her own value and growing with the company to become an elegant and confident woman. The main objective of Inlan fashion is to let every consumer can find jewelry suitable for her, let the jewelry can decorate her life from each small part and enjoy her life every day.

What is the primary source of funding for this project?
From our own business.

What other projects/ecosystem stakeholders is this project associated with?
No other stakeholder.

## Use-case details

Describe the data being stored onto Filecoin
Includes fashion jewelry trends, popular jewelry images, jewelry making processes and introduce the way to match jewelry and clothing. 

Where was the data in this dataset sourced from?
We produce by ourselves.

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
http://www.inlan-fashion.com/?mod=product&col_key=product   
   
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
Sure. These data is public and it can be retrieved by anyone.

What is the expected retrieval frequency for this data?
This is just one of our redundant backups, which does not require frequent access.Maybe once a year.

For how long do you plan to keep this dataset stored on Filecoin?
We hope it's long-term.

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
We want to be able to store globally.

How will you be distributing your data to storage providers? Is there an offline data transfer process?
Both online and offline would be OK.

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
We would like to work with several reputable large-scale storage provider operations to ensure geo-distribution and reliability of storage. 

How will you be distributing deals across storage providers?
We will make a fair allocation based on the service capacity on the storage service.

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
Of course, the funds are enough and we can pay easily.

**Comment by Sunnyiscoming** [comment]
What's Chinese name of your organization?
Can you explain your data composition and provide sufficient data samples separately? How many copies will you store?
What's the relationship between you and the organization?
Can you provide more detailed information about other storage providers participated in this program, such as you can list SPs you have contacted with at present?

**Comment by inlanfashion** [comment]
The Chinese name of our organization is  怡瀾國際有限公司.
The data composition is come from our company products photos and the video of how to match our products to the dress. We can ensure to provide sufficient date samples because our main products are fashion jewelry so our factory has to development more new items in order to we can send items photos to our customers and get new inquiries  and more orders. In you need we can send them to you separately.We will store 3 to 4 copies . 
I'm a legal person.
Sorry for that we can not provide more detailed information about other storage providers participated in this program and we will try to find them from below website right now.
https://filscan.io

**Comment by inlanfashion** [comment]
> What's Chinese name of your organization? Can you explain your data composition and provide sufficient data samples separately? How many copies will you store? What's the relationship between you and the organization? Can you provide more detailed information about other storage providers participated in this program, such as you can list SPs you have contacted with at present?

The Chinese name of our organization is  怡瀾國際有限公司.
The data composition is come from our company products photos and the video of how to match our products to the dress. We can ensure to provide sufficient date samples because our main products are fashion jewelry so our factory has to development more new items in order to we can send items photos to our customers and get new inquiries  and more orders. In you need we can send them to you separately.We will store 3 to 4 copies . 
I'm a legal person.
Sorry for that we can not provide more detailed information about other storage providers participated in this program and we will try to find them from below website right now.
https://filscan.io

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 100TiB

**Client address**

> f1zuasorixabj4k5qwt63v5kbjchqmwdl6dzgrkyq

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Looking at your application i have some questions:
As you are brand new on Github and have no history of past applications it seems to me that applying for 5PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?

Can you show us visible proof of the size of your data and the storage systems you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230232885049356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!

**Comment by inlanfashion** [comment]
> Dear applicant,
> 
> Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.
> 
> Looking at your application i have some questions: As you are brand new on Github and have no history of past applications it seems to me that applying for 5PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?
> 
> Can you show us visible proof of the size of your data and the storage systems you have there?
> 
> As last question i would like you to fill out [this form](https://form.jotform.com/230232885049356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.
> 
> Thanks!

Dear Friend,

Glad to receive your above reply.

Yes, I am new on Github and I am the leader of our company. I heard Filecoin from one of our company IT engineer who came to our company last year. He is familiar with Filecoin. In order to protect the interests of company so I am applying for datacap. Our company has always used NAS for date backup which does not expand easily so he suggested me to use IPFS instead of NAS.

Our main data including the high quality photos and HD video of our products. If you need I can send some of them to you.

I know 5PB of datacap is a lot. I heard from our IT engineer for that which can store data permanent in free and we always have a lots of photos and videos of our products need to be backup so I would like to apply 5PB of datacap and hope you can distribute it to us.

By the way, I am very interesting in traveling and I also have a lots of scenery photos which can be available for public. If I feel Filecoin is really useful and I will share it to my friends or business partner to use it.

Hope everything is going well and get your good news.

Thank you!

**Comment by cryptowhizzard** [comment]
Hello!

Thanks for your reply. 

When can i expect this -> 

As last question i would like you to fill out [this form](https://form.jotform.com/230232885049356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

**Comment by inlanfashion** [comment]
> Hello!
> 
> Thanks for your reply.
> 
> When can i expect this ->
> 
> As last question i would like you to fill out [this form](https://form.jotform.com/230232885049356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Hello!

Sorry for late and I have filled out the form. Could you help me to check and advice if it is ok for you? Thank you.

**Comment by cryptowhizzard** [comment]
Hello,

That is no problem.

Whenever you are ready to provide me with the SP's, let me know so i can continue my work
