### ISSUE TITLE
[DataCap Application] <EhostICT> - <Data center level of Backup storage>

### ISSUE THREAD

**Issue by gustjr154** [filecoin-project/filecoin-plus-large-datasets#1274]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: EhostICT 
- Website / Social Media: https://www.ehostidc.com/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 2PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100TiB
- On-chain address for first allocation: f1dj23xokyovdqnbgx3nis3ygk73szanzlwb2kduy
- Type: Custom Notary
- Identifier: E-fil

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
EhostICT is running a tier-3 data center which is located in Seoul, South Korea. We have been offering IT total services such as GPU server hosting, Network, Security controller based on almost two decades’ experiences of IDC operation. We operate various scales of data centers & POPs over the world to offer global IDC services.

Our main data center’s infrastructure is tier 3 levels of high availability with 176 racks mounted 1,630 servers and equipped with three major ISP lines and China direct line with 50G port speed. Also, the operation & management team offers 24/7 monitoring service which handles the network changes, system network infra resource, security issues and backup schedule.

Currently, we have invested in IPFS infrastructure development with a full scale of its capability since we are aware of that IPFS is the representative core value to realize decentralization and distribution under Web 3.0 era. In particular, we already cooperated with the IPFS infrastructure company operating two full racks mounted on 16 servers in our own DC. The total capacity is 5Pib so far.
```
![dc1](https://user-images.githubusercontent.com/75414830/202381096-10debac0-3540-4a42-a1cc-cf5ab45a4148.JPG)
![dc2](https://user-images.githubusercontent.com/75414830/202381110-67b18469-4f34-4df8-8ad7-f6ac920e36fd.JPG)
![dc3](https://user-images.githubusercontent.com/75414830/202381121-7cfa120d-b82a-4a70-8e96-33c2bb856c2d.JPG)
![dc4](https://user-images.githubusercontent.com/75414830/202381128-bcf29d96-fed1-4e19-a884-8f0e9aeaaf15.JPG)

What is the primary source of funding for this project?
```
Own funds and revenue of the company.
```

What other projects/ecosystem stakeholders is this project associated with?
```
No. 
```

## Use-case details

Describe the data being stored onto Filecoin
```
About 100~150TB of backup data occurs everyday operating our IDC infrastructure and services. It has been stored only in the physical hard disk in our DC for years. However, we need a different level of storing method that anyone can retrieve and share under the Web 3.0 era and found out the IPFS technology would fit our needs.
Our first goal is decentralizing these petabyte levels of datasets into a filecoin system and making it contactable to anyone could retrieve.
The backup data includes, 
1) Private data from the client (confidential docs, DB backup) 
2) Public data from the client (footage, programs and files) 
3) Public data from EhostIDC (files and video for company Introduction) 

```

Where was the data in this dataset sourced from?
```
Over 80% of backup data would be the client’s services which we have been offering. It is customized total IT consulting services, including deep learning, autonomous driving, medical services, and education. 
And the remaining 20% would be a backup data comes from operating our IDC infrastructure. 
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
www.ehostidc.com/upload/1w-1.mp4
www.ehostidc.com/upload/1w-2.mp4
www.ehostidc.com/upload/1w-3.mp4
www.ehostidc.com/upload/1w-4.mp4
www.ehostidc.com/upload/2w-1.mp4
www.ehostidc.com/upload/2w-2.mp4
www.ehostidc.com/upload/3w-1.mp4
www.ehostidc.com/upload/3w-2.mp4
www.ehostidc.com/upload/4w-1.mp4
www.ehostidc.com/upload/4w-2.mp4
www.ehostidc.com/upload/5w-1.mp4
www.ehostidc.com/upload/5w-2.mp4
www.ehostidc.com/upload/5w-3.mp4
www.ehostidc.com/upload/6w-1.mp4
www.ehostidc.com/upload/6w-2.mp4
www.ehostidc.com/upload/7w-1.mp4
www.ehostidc.com/upload/7w-2.mp4
www.ehostidc.com/upload/vidio traffic.mp4
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
The current data set requires permission based access.
A final goal is our clients can retrieve and access their own data. 
```

What is the expected retrieval frequency for this data?
```
Whenever our client needs to access the data. 
```

For how long do you plan to keep this dataset stored on Filecoin?
```
At least 3 years. 
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
The global. Mostly Asia
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Both online and offline data transfer depending on the preference of storage providers.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We will select SPs who could meet our requirements in terms of storage cost, and geographical location. Since our global customers located in Europe and Asia, probs getting one or over in Europe, two or over in Asia.
```

How will you be distributing deals across storage providers?
```
We will follow the allocation rules on this basis. each SP will be distributed deals no more than 20% of all.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes. We are ready to start making deals. 
```
![ipfs](https://user-images.githubusercontent.com/75414830/202379756-6b7276dd-e21a-4f98-b237-13a9f9c8566b.JPG)
![자율주행 ㅡㅐㅕ](https://user-images.githubusercontent.com/75414830/202379766-c50b4578-28fd-4e41-8978-f71443a00119.JPG)

**Comment by Sunnyiscoming** [comment]
> Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
> 
> The current data set requires permission based access.
> A final goal is our clients can retrieve and access their own data. 

@kevzak  Hi, Kevin. This is a E-FIL+ application.

**Comment by kevzak** [comment]
Hello @gustjr154 - because you are looking to store permissioned private data, you should apply for DataCap via the E-Fil+ program https://efilplus.super.site/

Please have the data applicant complete a registration form: [LINK](https://docs.google.com/forms/d/e/1FAIpQLSeAaM0duQFDGUmQ5c7e--FVez7fXGOkLZlUPSkfpbBMfmwXsw/viewform)

**Comment by gustjr154** [comment]
@kevzak 
We have submitted the E-Fil+ program application through the link you gave us for private data storage.

Thank you.

**Comment by kevzak** [comment]
Hello - Thank you for completing Registration and Manual KYB check. I can confirm this was completed successfully.

@gustjr154  in order to proceed, please fill out the [LDN application exceptions template](https://github.com/filecoin-project/notary-governance/issues/new/choose) and include details about the data storage plan:

please include Data Storage Plan:
Size of dataset, # of copies required
Storage Providers involved: Miner Ids, Locations

**Comment by gustjr154** [comment]
Hello, @kevzak 
Just submit the template. Please look it up I will be waiting for your feedback. 
Btw, I have revised the total amount 5pib to 2pib. then eventually the Efil+ label has gone. 
Please add it again.

**Comment by kevzak** [comment]
@gustjr154 I will manage E-Fil label, thank you for note. 

I have left you feedback on your proposal. You need more SP details and you need to either pass KYB check or find 5 notaries for support: https://github.com/filecoin-project/notary-governance/issues/797#issuecomment-1355105602
