### ISSUE TITLE
[DataCap Application] <VMERA3> - <Metaverse Project> 

### ISSUE THREAD

**Issue by szcoolw** [filecoin-project/filecoin-plus-large-datasets#1279]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: VMERA3
- Website / Social Media:https://www.vmeta3.net/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):3PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):100TiB
- On-chain address for first allocation: f1qttvggw2cpaqidpg5luhqvkxu6qmm6x6rvy6zlq

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
A Metaverse in our opinion is the real world in a digital space. That's the experience we want our users to have. 

We are a Metaverse that brings together components of Web 3.0 in a highly efficient and synchronized manner such as our Vmeta3 Wallet, Layer-2 Mining, Cross-Chain NFT Marketplace, and Swap. These modules interlock with each other, forming a profitable Metaverse economy hence helping it grow and prosper. The development of each independent module will ultimately improve the growth of any business that aims to harness the Web 3.0 Technology.

We seamlessly and securely facilitate Cross-Chain transmission of informational data, NFTs, and smart contracts across other chains.

Providing a mechanism to exchange tokens between Ethereum scaling solutions and for transferring tokens over a shared layer 1 network quickly and without trust.

Enabling customers with a two-pronged token bridge for Ethereum’s layer 2 networks.

The solution aims to facilitate the rapid movement of a token between layer 2 and a scaling solution’s governance token. 

Using Key Artistic Standards and Instructions based on the Unity engine, the PBR process and emphasizing the real restoration of resources we can truly achieve the relationship between the metaverse and reality,

We understand the requirements of businesses such as virtual fashion that have rigid requirements for expressiveness.

The application of this standard can also expand the types of NFTs and promote the development of NFTs.

We have a unique set of standards that protect the IPs of artists. The original designs minted on VMeta3 Chain will be marked in encrypted files so that the chain will confirm the owner of the NFTs and protect their copyright.

In VMeta3, Digital Identities (DI) are unique online identifiers. A DI is who you are and how you represent yourself in this virtual space. Your DI will have important information about you, like your habits and skills. Having your DI removes the need for physical documentation to prove your identity in the digital world.

Our advertising solution uses blockchain data, a "Peer-to-Peer" advertising solution for sponsors to choose their audiences, and an open source report that shows the marketing expense on the exact audience, ensuring transparency and fairness between audiences and sponsors.

With our virtual fashion technology, you can try on clothes and accessories from the comfort of your own home. The VMeta3 Metaverse is improving how people shop for clothes and accessories. We're making it easier than ever to find the perfect outfit and experience what it feels like to wear them before deciding to buy.
```

What is the primary source of funding for this project?
```
Company's own funds and partners' funds.
```

What other projects/ecosystem stakeholders is this project associated with?
```
None.
```

## Use-case details

Describe the data being stored onto Filecoin
```
Videos, pictures, R&D data.
```

Where was the data in this dataset sourced from?
```
The data comes from the data provided by the company's research and development department and publicity department.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://drive.google.com/file/d/1JT_VpYAMhjQyj34T8lMxpNQz-uXuTWkN/view?usp=sharing
https://drive.google.com/file/d/1LMRfBZstqG7ligNj-VlCeFhZjiHPXj7u/view?usp=share_link
https://drive.google.com/file/d/1W5jCMe2qvnoaciZpEKmMfAhGYHVUQAkj/view?usp=share_lin
https://drive.google.com/file/d/1JWsgkTQ0N96vFKNz5D8iP5B1LQTrFNjc/view?usp=share_linkk
https://drive.google.com/drive/folders/1pS3IodBvhk019PdXGcxLfAbrd2GWWFuw?usp=share_link
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Confirm.
```

What is the expected retrieval frequency for this data?
```
About a year or so.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
At least 24 months.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Asian region.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Both online and offline transmission.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We need a storage provider that can cooperate for a long time. We will choose a reputable storage provider, check their overall capacity and working hours, screen the overall technical strength of miners, and ensure distributed storage and data security.
```

How will you be distributing deals across storage providers?
```
We will choose a stable and secure storage provider, and then allocate according to the allocation rules on this basis.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes ,we have enough funds.
```

**Comment by Tom-OriginStorage** [comment]
1：can you send email to [[[filplus-app-review@fil.org](mailto:filplus-app-review@fil.org)]
2：Can you tell which nodes should be stored？

**Comment by szcoolw** [comment]
1.yes,i can
2.f01901351 f01901351 f01901351 f01901351

**Comment by szcoolw** [comment]
![4287b4d3ed6c970b567b2e1e8f71d9b](https://user-images.githubusercontent.com/68136299/206381208-5dab0489-1c9c-496c-8808-7dbd319f2e80.jpg)
I have replied. Please confirm it.

**Comment by Tom-OriginStorage** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebnu43zenjlfb53my4prhl5t3lqdfy53kr7mu626b76pexkknqkqq 
#### Address 
> f1qttvggw2cpaqidpg5luhqvkxu6qmm6x6rvy6zlq
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1q6bpjlqia6iemqbrdaxr2uehrhpvoju3qh4lpga
#### Id
> 26655d8b-7631-4a2c-be52-9575ee639bc5
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebnu43zenjlfb53my4prhl5t3lqdfy53kr7mu626b76pexkknqkqq

**Comment by NDLABS-OFFICE** [comment]
Checked the customer subject information and data samples, willing to support and keep concerned.

**Comment by NDLABS-OFFICE** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecb6267bpkmyf6jq2o5f5iwzpd4z7dtm2m7uqs7syic5tiu7g6wse 
#### Address 
> f1qttvggw2cpaqidpg5luhqvkxu6qmm6x6rvy6zlq
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1yayfsv6whu3rheviucvventj3y6t542xfpb47ei
#### Id
> 26655d8b-7631-4a2c-be52-9575ee639bc5
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecb6267bpkmyf6jq2o5f5iwzpd4z7dtm2m7uqs7syic5tiu7g6wse

**Comment by zizi-defil** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceawvfqx5l3zyggp7mg3ewsjntw74zmt5fcvnpzcpku5zz2dckorie 
#### Address 
> f1qttvggw2cpaqidpg5luhqvkxu6qmm6x6rvy6zlq
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1dnb3uz7sylxk6emti3ififcvu3nlufnnsjui6ea
#### Id
> ea6b9deb-03fc-478b-bab7-3148c78022b4
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceawvfqx5l3zyggp7mg3ewsjntw74zmt5fcvnpzcpku5zz2dckorie

**Comment by zizi-defil** [comment]
no CID sharing
Storage provider distribution looks healthy
so i would like to support

**Comment by newwebgroup** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceahy4seeqspkfcyt7tglpqa2wr5i5srs57d2axnxcgd5luu5xecsg 
#### Address 
> f1qttvggw2cpaqidpg5luhqvkxu6qmm6x6rvy6zlq
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1e77zuityhvvw6u2t6tb5qlnsegy2s67qs4lbbbq
#### Id
> ea6b9deb-03fc-478b-bab7-3148c78022b4
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceahy4seeqspkfcyt7tglpqa2wr5i5srs57d2axnxcgd5luu5xecsg

**Comment by herrehesse** [comment]
It seems (given my crowded inbox) that in the past 15 minutes @newwebgroup  has approved 10+ datacap requests.

**I wonder if this blind approval is allowed?**

Would like to see per project what due diligence you did to explain the approval @newwebgroup.

**Comment by herrehesse** [comment]
@newwebgroup Asking a bot for numbers is not doing due diligence. Please respond to my original question.

**Comment by szcoolw** [comment]
I don't think they're online every day, just occasionally processing messages, like you.

**Comment by BDEio** [comment]
@szcoolw Hi! Congratulations on your DataCap approval！
BDE is a verified deals auction house helping you to get paid storing your data with reliable storage providers. If you need any help, please get in touch.

**Comment by herrehesse** [comment]
@szcoolw hello applicant, can you help and explain to my why your data fits the Filecoin+ program rules?

"Videos, pictures, R&D data."

**Comment by aliensero** [comment]
checker:manualTrigger

**Comment by cryptowhizzard** [comment]
Feb 13 22:00:52 proposals dealscanner-f01920820-f0153960: 2023-02-13T22:00:52.317+0100#011WARN#011rpc#011go-jsonrpc@v0.1.9/client.go:560#011unmarshaling failed#011{"message": "{\"Err\":\"exhausted 5 attempts but failed to open stream, err: failed to dial 12D3KooWRV1adkrcTeenh9pt7MxPmUBdeFWAFEA2JT4sbPipjZEM:\\n  * [/ip4/47.242.95.98/tcp/62353] dial tcp4 0.0.0.0:38697-\\u003e47.242.95.98:62353: i/o timeout\",\"Root\":null,\"Piece\":null,\"Size\":0,\"MinPrice\":\"\\u003cnil\\u003e\",\"UnsealPrice\":\"\\u003cnil\\u003e\",\"PricePerByte\":\"\\u003cnil\\u003e\",\"PaymentInterval\":0,\"PaymentIntervalIncrease\":0,\"Miner\":\"f0153960\",\"MinerPeer\":{\"Address\":\"f0153960\",\"ID\":\"12D3KooWRV1adkrcTeenh9pt7MxPmUBdeFWAFEA2JT4sbPipjZEM\",\"PieceCID\":null}}"}
Feb 13 22:00:52 proposals dealscanner-f01920820-f0153960: 2023-02-13T22:00:52.317+0100#011INFO#011retry#011retry/retry.go:17#011Retrying after error:RPC client error: unmarshaling result: failed to parse big string: '"\u003cnil\u003e"'
Feb 13 22:01:28 proposals autoretrieve:     [addressId] => f01920820
Feb 13 22:01:33 proposals autoretrieve: Working with PSP . f02001667 AND client f01920820 
Feb 13 22:02:11 proposals dealscanner-f01920820-f0153960: 2023-02-13T22:02:11.831+0100#011WARN#011rpc#011go-jsonrpc@v0.1.9/client.go:560#011unmarshaling failed#011{"message": "{\"Err\":\"exhausted 5 attempts but failed to open stream, err: failed to dial 12D3KooWRV1adkrcTeenh9pt7MxPmUBdeFWAFEA2JT4sbPipjZEM:\\n  * [/ip4/47.242.95.98/tcp/62353] dial tcp4 0.0.0.0:38697-\\u003e47.242.95.98:62353: i/o timeout\",\"Root\":null,\"Piece\":null,\"Size\":0,\"MinPrice\":\"\\u003cnil\\u003e\",\"UnsealPrice\":\"\\u003cnil\\u003e\",\"PricePerByte\":\"\\u003cnil\\u003e\",\"PaymentInterval\":0,\"PaymentIntervalIncrease\":0,\"Miner\":\"f0153960\",\"MinerPeer\":{\"Address\":\"f0153960\",\"ID\":\"12D3KooWRV1adkrcTeenh9pt7MxPmUBdeFWAFEA2JT4sbPipjZEM\",\"PieceCID\":null}}"}
Feb 13 22:02:11 proposals dealscanner-f01920820-f0153960: 2023-02-13T22:02:11.831+0100#011INFO#011retry#011retry/retry.go:17#011Retrying after error:RPC client error: unmarshaling result: failed to parse big string: '"\u003cnil\u003e"'
Feb 13 22:02:31 proposals autoretrieve:     [addressId] => f01920820
Feb 13 22:04:57 proposals dealscanner-f01920820-f0153960: 2023-02-13T22:04:57.448+0100#011WARN#011rpc#011go-jsonrpc@v0.1.9/client.go:560#011unmarshaling failed#011{"message": "{\"Err\":\"exhausted 5 attempts but failed to open stream, err: failed to dial 12D3KooWRV1adkrcTeenh9pt7MxPmUBdeFWAFEA2JT4sbPipjZEM:\\n  * [/ip4/47.242.95.98/tcp/62353] dial tcp4 0.0.0.0:38697-\\u003e47.242.95.98:62353: i/o timeout\",\"Root\":null,\"Piece\":null,\"Size\":0,\"MinPrice\":\"\\u003cnil\\u003e\",\"UnsealPrice\":\"\\u003cnil\\u003e\",\"PricePerByte\":\"\\u003cnil\\u003e\",\"PaymentInterval\":0,\"PaymentIntervalIncrease\":0,\"Miner\":\"f0153960\",\"MinerPeer\":{\"Address\":\"f0153960\",\"ID\":\"12D3KooWRV1adkrcTeenh9pt7MxPmUBdeFWAFEA2JT4sbPipjZEM\",\"PieceCID\":null}}"}
Feb 13 22:04:57 proposals dealscanner-f01920820-f0153960: 2023-02-13T22:04:57.448+0100#011INFO#011retry#011retry/retry.go:17#011Retrying after error:RPC client error: unmarshaling result: failed to parse big string: '"\u003cnil\u003e"'
Feb 13 22:06:58 proposals dealscanner-f01920820-f0153960: 2023-02-13T22:06:58.993+0100#011WARN#011rpc#011go-jsonrpc@v0.1.9/client.go:560#011unmarshaling failed#011{"message": "{\"Err\":\"exhausted 5 attempts but failed to open stream, err: failed to dial 12D3KooWRV1adkrcTeenh9pt7MxPmUBdeFWAFEA2JT4sbPipjZEM:\\n  * [/ip4/47.242.95.98/tcp/62353] dial tcp4 0.0.0.0:38697-\\u003e47.242.95.98:62353: i/o timeout\",\"Root\":null,\"Piece\":null,\"Size\":0,\"MinPrice\":\"\\u003cnil\\u003e\",\"UnsealPrice\":\"\\u003cnil\\u003e\",\"PricePerByte\":\"\\u003cnil\\u003e\",\"PaymentInterval\":0,\"PaymentIntervalIncrease\":0,\"Miner\":\"f0153960\",\"MinerPeer\":{\"Address\":\"f0153960\",\"ID\":\"12D3KooWRV1adkrcTeenh9pt7MxPmUBdeFWAFEA2JT4sbPipjZEM\",\"PieceCID\":null}}"}
Feb 13 22:06:58 proposals dealscanner-f01920820-f0153960: 2023-02-13T22:06:58.993+0100#011INFO#011retry#011retry/retry.go:17#011Retrying after error:RPC client error: unmarshaling result: failed to parse big string: '"\u003cnil\u003e"'
Feb 13 22:07:42 proposals dealscanner-f01920820-f0153960: 2023-02-13T22:07:42.665+0100#011WARN#011rpc#011go-jsonrpc@v0.1.9/client.go:560#011unmarshaling failed#011{"message": "{\"Err\":\"exhausted 5 attempts but failed to open stream, err: failed to dial 12D3KooWRV1adkrcTeenh9pt7MxPmUBdeFWAFEA2JT4sbPipjZEM:\\n  * [/ip4/47.242.95.98/tcp/62353] dial backoff\",\"Root\":null,\"Piece\":null,\"Size\":0,\"MinPrice\":\"\\u003cnil\\u003e\",\"UnsealPrice\":\"\\u003cnil\\u003e\",\"PricePerByte\":\"\\u003cnil\\u003e\",\"PaymentInterval\":0,\"PaymentIntervalIncrease\":0,\"Miner\":\"f0153960\",\"MinerPeer\":{\"Address\":\"f0153960\",\"ID\":\"12D3KooWRV1adkrcTeenh9pt7MxPmUBdeFWAFEA2JT4sbPipjZEM\",\"PieceCID\":null}}"}
Feb 13 22:07:42 proposals dealscanner-f01920820-f0153960: 2023-02-13T22:07:42.665+0100#011ERROR#011retry#011retry/retry.go:29#011Failed after 5 attempts, last error: RPC client error: unmarshaling result: failed to parse big string: '"\u003cnil\u003e"'
Feb 13 22:07:42 proposals dealscanner-f01920820-f0153960: ERROR: RPC client error: unmarshaling result: failed to parse big string: '"\u003cnil\u003e"'
Feb 13 22:07:42 proposals dealscanner-f01920820-f0153960:

**Comment by cryptowhizzard** [comment]
Seems retrievals are not working. Can you check your side please?
