### ISSUE TITLE
[DataCap Application] McKorn - Community Center

### ISSUE THREAD

**Issue by Davekorn** [filecoin-project/filecoin-plus-large-datasets#1280]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: McKorn
- Website / Social Media: http://www.mckorn.com
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):500 TiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 10 TiB
- On-chain address for first allocation: f1an2kap2rdjfifryjlfznw75z6gy45nbprzknp2i

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Aug(2018) NHBank Customer Services
Aug(2019) Hanwha Customer Services 
Mar(2020) Ministry of Labor Community Site https://www.moel.go.kr
Jan(2021) Adventist Church Community Site https://sdakorea.net
```

What is the primary source of funding for this project?
```
Our clients will be the funding source, governments, bank companies, churches, and SNS communities.
```

What other projects/ecosystem stakeholders is this project associated with?
```
This project will refer to creating other same projects more and more as many as there are more than 9,000 churches in South Korea.
```

## Use-case details

Describe the data being stored onto Filecoin
```
The majority of data being stored will be images and other media data.
```

Where was the data in this dataset sourced from?
```
The data centers of the governments and the companies and the churches that we manage.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
Yes
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes
```

What is the expected retrieval frequency for this data?
```
As it is community services, it should be available in 24 hours, but seems to be hard to predict the frequency.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
More than 5 years
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Seoul, South Korea
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Hard drivers
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
For convenience, the nearest storage providers.
```

How will you be distributing deals across storage providers?
```
Each deal is to one provider, based on my clients' location.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, finding good storage provider would help us.
```

**Comment by Davekorn** [comment]
![IMG_3340](https://user-images.githubusercontent.com/70049300/202731389-b1ca96cc-e74b-4757-b405-a21341c0d219.JPG)

**Comment by Davekorn** [comment]
the other big size movies are to be stored.

**Comment by Davekorn** [comment]
![IMG_3326](https://user-images.githubusercontent.com/70049300/202733071-9b7357d0-9442-4b23-b366-99823c57d90d.JPG)

**Comment by Sunnyiscoming** [comment]
You can save the sample data to a platform and share the link with us, like https://drive.google.com.
For example, https://drive.google.com/drive/folders/1LKYPc6obk1ov9PM8bcjcWaCkmlXo2-Y1.

**Comment by Davekorn** [comment]
https://drive.google.com/file/d/1zqPWoaG0sHoQk4yXShDDzlNdz4GuGedQ/view?usp=share_link

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 500TiB

**Expected weekly DataCap usage rate**

> 10TiB

**Client address**

> f1an2kap2rdjfifryjlfznw75z6gy45nbprzknp2i

**Comment by Davekorn** [comment]
Hi, what do these messages mean about my application? 
Approved? Then how much capacity?

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Can you show us visible proof of the size of your data and the storage systems you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230232885049356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!
