### ISSUE TITLE
[DataCap Application] Caribbean LDN-01 Seal Storage Technology

### ISSUE THREAD

**Issue by salstorage** [filecoin-project/filecoin-plus-large-datasets#1281]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Seal Storage Technology
- Website / Social Media: https://www.sealstorage.io/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 400TiB
- On-chain address for first allocation: f1bvlifue4nucdljqbcayi7i3ep535y3rackexiyy

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
NOTE: this is LDN app 1 of 2. Total data cap requested for this project is 8.4 PiB.
LDN app 2 of 2 can be found here: https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1282
Seal is collaborating with The Center for Extreme Data Management, Analysis and Visualization (CEDMAV) of the University of Utah on a pilot project to use Filecoin for data storage for a public dataset: OpenVisus datasets (they are very “sparse”, combustion, simulations, earth, satellite etc). The data sets are about 1.4 PiB. Seal and CEDMAV are also exploring specific use-cases and how the Filecoin Network can support ongoing research.

Seal is a carbon-neutral, decentralized cloud storage provider. Seal's technical leadership brings decades of experience from traditional enterprise storage companies including Seagate and Oracle, as well as world-class experience on the Filecoin Network. Today, Seal operates data centers across the US and Canada with enterprise-grade infrastructure and data policies.

```

What is the primary source of funding for this project?
```
Seal is funding the project
```

What other projects/ecosystem stakeholders is this project associated with?
```
The main stakeholder for this project is the University of Utah CEDMAV group. Our customer views decentralized data storage as an exciting platform that could yield many benefits for future large datasets.
```

## Use-case details

Describe the data being stored onto Filecoin
```
Project Caribbean consists of a 1.4 PiB verified PUBLIC data set belonging to The Center for Extreme Data Management Analysis and Visualization at the University of Utah (CEDMAV, http://cedmav.org/). The data is OpenVisus data sets (they are very “sparse”, combustion, simulations, earth, satellite etc).
```

Where was the data in this dataset sourced from?
```
The Center for Extreme Data Management, Analysis and Visualization (CEDMAV) of the University of Utah
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://drive.google.com/drive/folders/1j6p8peLJJ9tbNhF5mD3sPBUKjFrw5UUy?usp=sharing
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Confirmed - this is a public dataset
```

What is the expected retrieval frequency for this data?
```
The data will be accessed by external collaborators and Researchers.
Retrieval would be daily as and when needed, Seal Storage will keep a unsealed copy for retrieval purposes
```

For how long do you plan to keep this dataset stored on Filecoin?
```
Three year term
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
We plan to store six copies of the 1.4 PiB data set [total of 8.4 PiB] in four different cities, in three different countries and across two continents.

```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Seal Storage has dual 100 Gbps internet connections. SPs will download data from Seal. 
Seal Storage will prepare and CAR the files into 32GB chunks for distribution
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We are currently meeting and discussing capabilities with several other SPs. Due to the size of this pilot, our SPs have requested DataCap before committing to the project.
We plan to choose enterprise-grade SPs for this project and will complete our due diligence post DataCap approval.

```

How will you be distributing deals across storage providers?
```
1 copy = 1.4 PiB

DLTX 1 copy in Omaha, Nebraska, USA
Ghostbytes 1 copy in Philadelphia, USA
DSS 1 copy in Sydney, Australia
Telnyx 1 copy multiple locations USA
Seal Storage 1 copy in Las Vegas, NV USA 
Seal Storage 1 copy in Montreal, Quebec, Canada 

Seal Storage must also keep a full hot copy unsealed for our Customer. 

```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Once we receive DataCap, we will begin making deals as soon as customer data is transferred to Seal Storage November 2022
We currently have the support we need.
```

**Comment by salstorage** [comment]
The following Notaries have reviewed the 1.4PiB Data Storage Plan and support/approve project Caribbean
Data Storage Plan Link: https://docs.google.com/document/d/1J8UPM8w4wxyPNISXpI0vYpMcPv6EinpiAGm4X14E6-0/edit?usp=sharing

Notaries:
Joss Hua - Venus Team - IPFSForce - f1tfg54zzscugttejv336vivknmsnzzmyudp3t7wi
Alex Kim - Define Platform - f1hhippi64yiyhpjdtbidfyzma6irc2nuav7mrwmi
BlockMaker - f1o3twrcpwjtpcd4q36lpq4qmy2qfbgtyy5h6tsty
Claudia Richoux - Banyan - f1oc6qvenzp7wsriu7edyebb325gnaovktmujl7jq
Zhehao Chen - Fenbushi Capital - f1yqydpmqb5en262jpottko2kd65msajax7fi4rmq
Wijnand Schouten - Speedium - f1krmypm4uoxxf3g7okrwtrahlmpcph3y7rbqqgfa

**Comment by Fenbushi-Filecoin** [comment]
Confirm to support the application.

**Comment by salstorage** [comment]
Notaries that have expressed support for Proj-Caribbean, please confirm 
@wijnand Schouten
@BlockMaker
@Alex Kim (Define)
@Gary Gao-FBG
@​​Joss-Venus

**Comment by Joss-Hua** [comment]
Willing to be supportive. I have had a preliminary face-to-face visit with the applicant, the applicant has shown some relevant materials and is happy to see that these data will bring more useful data to the network.

**Comment by mjroddy** [comment]
Repeating my support as per https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1282

Overall I am supportive of this project.

Given the size it is important that we get as much 'knowledge' out of this program as possible. A case study and marketing is included. in the Data Storage Plan Link

I would like to see that findings from onboarding this client be shared with other storage providers. This would include challenges, technical and sales tooling, even a case study from the SP's perspective so that the network as a whole benefits from this project.

For Filecoin to improve all SP's must be lifted up.

**Comment by steven004** [comment]
Will to be supportive on this project.

**Comment by BlockMakeronline** [comment]
They contacted us earlier and told us much about the project. Happy to support the application.

**Comment by cryptowhizzard** [comment]
Happy to support

**Comment by raghavrmadya** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 400TiB

**Client address**

>f1bvlifue4nucdljqbcayi7i3ep535y3rackexiyy

**Comment by raghavrmadya** [comment]
All datacap will go to f1bvlifue4nucdljqbcayi7i3ep535y3rackexiyy

**Comment by Fenbushi-Filecoin** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec5wiuxl3fdku32ytttb2sxgtaukdjc6czswmxti5znbfkxjywntk 
#### Address 
> f1bvlifue4nucdljqbcayi7i3ep535y3rackexiyy
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1yqydpmqb5en262jpottko2kd65msajax7fi4rmq
#### Id
> 65b30fae-0eb2-4a3c-a8f9-a14afb3f832d
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec5wiuxl3fdku32ytttb2sxgtaukdjc6czswmxti5znbfkxjywntk

**Comment by mjroddy** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebbvmadd2v4ttmgo4qnlkxqx52h5docnacwknwqaxgtfwz3jleor4 
#### Address 
> f1bvlifue4nucdljqbcayi7i3ep535y3rackexiyy
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1ystxl2ootvpirpa7ebgwl7vlhwkbx2r4zjxwe5i
#### Id
> 65b30fae-0eb2-4a3c-a8f9-a14afb3f832d
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebbvmadd2v4ttmgo4qnlkxqx52h5docnacwknwqaxgtfwz3jleor4

**Comment by filplus-checker** [comment]
## DataCap and CID Checker Report[^1]
 - Organization: `Seal Storage Technology`
 - Client: `f1bvlifue4nucdljqbcayi7i3ep535y3rackexiyy`
### Storage Provider Distribution
The below table shows the distribution of storage providers that have stored data for this client.

If this is the first time a provider takes verified deal, it will be marked as `new`.

For most of the datacap application, below restrictions should apply.
 - Storage provider should not exceed 25% of total datacap.
 - Storage provider should not be storing duplicate data for more than 20%.
 - Storage provider should have published its public IP address.
 - All storage providers should be located in different regions.

⚠️ [f01886710](https://filfox.info/en/address/f01886710) has sealed 100.00% of total datacap.

⚠️ [f01886710](https://filfox.info/en/address/f01886710) has unknown IP location.

⚠️ All storage providers are located in the same region.

| Provider                                              | Location | Total Deals Sealed | Percentage | Unique Data | Duplicate Deals |
| :---------------------------------------------------- | -------: | -----------------: | ---------: | ----------: | --------------: |
| [f01886710](https://filfox.info/en/address/f01886710) |  Unknown |           8.00 TiB |    100.00% |    8.00 TiB |           0.00% |

![Provider Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/1281/1671098948577.png)
### Deal Data Replication
The below table shows how each many unique data are replicated across storage providers.
- No more than 25% of unique data are stored with less than 4 providers.

⚠️ 100.00% of deals are for data replicated across less than 4 storage providers.

| Unique Data Size | Total Deals Made | Number of Providers | Deal Percentage |
| ---------------: | ---------------: | ------------------: | --------------: |
|         8.00 TiB |         8.00 TiB |                   1 |         100.00% |

![Replication Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/1281/1671098949217.png)
### Deal Data Shared with other Clients
The below table shows how many unique data are shared with other clients.
Usually different applications owns different data and should not resolve to the same CID.

✔️ No CID sharing has been observed.

[^1]: To manually trigger this report, add a comment with text `checker:manualTrigger`

**Comment by salstorage** [comment]
Paging Notary to sign next DC tranche please
@Joss-Hua @steven004 @cryptowhizzard @BlockMakeronline @laudiacay @Alex11801 @GaryGJG

**Comment by salstorage** [comment]
checker:manualTrigger

**Comment by salstorage** [comment]
Paging Notary to sign next DC tranche please
@Joss-Hua @steven004 @cryptowhizzard @BlockMakeronline @laudiacay @Alex11801 @GaryGJG

**Comment by cryptowhizzard** [comment]
HI @salstorage 

I can't sign since this one is not visible on my dashboard.
I can sign on #1282  if you want?

**Comment by salstorage** [comment]
Hi @cryptowhizzard 
#1282 has already been signed, thank you.

Do you know why you cannot see this LDN on dashboard?? Please let me know if we need someone from FF to assist?

**Comment by cryptowhizzard** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced2npr2osb2rj4hwkuergzjhfjelkwbvksvttaimsgxkkf2633q3y 
#### Address 
> f1bvlifue4nucdljqbcayi7i3ep535y3rackexiyy
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1krmypm4uoxxf3g7okrwtrahlmpcph3y7rbqqgfa
#### Id
> eab8af5b-2939-4c99-982c-d8084e4dd83a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced2npr2osb2rj4hwkuergzjhfjelkwbvksvttaimsgxkkf2633q3y

**Comment by cryptowhizzard** [comment]
Proposing on basis of trust. Seal is a long term trusted participant in the ecosystem.
Did some retrieval requests and all looks ok.

**Comment by 1475Notary** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebnhis3keaz6ma624il6t7xeqyfnbkhgur35o3fatr27j2qigpvza 
#### Address 
> f1bvlifue4nucdljqbcayi7i3ep535y3rackexiyy
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1ofq4mngy7ggcp755pfquq2gphjjnlydolf6awtq
#### Id
> eab8af5b-2939-4c99-982c-d8084e4dd83a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebnhis3keaz6ma624il6t7xeqyfnbkhgur35o3fatr27j2qigpvza

**Comment by salstorage** [comment]
Please add the following Miner ID's to project:
f01838599 and f01845552?

**Comment by data-programs** [comment]
<img width="32" alt="KYC" Verified src="https://stable.filplus.storage/images/filplus-kyc-verified-badge.png"/>

This user’s identity has been verified through [filplus.storage](https://filplus.storage)

**Comment by salstorage** [comment]
Please note SP GHOSTBYTES is no longer online 
We are removing GHOSTBTYES from application (Miner ID:   f01506844)

**Comment by salstorage** [comment]
Due to removal of Ghostbytes/ Web3Cloud from application.
We are adding SP Vogo-Digital Labs located in S. Korea to store 200 TB's of Caribbean Dataset 
MINER ID's: f02202753 and f01987994

**Comment by salstorage** [comment]
Due to termination of sectors, Remove the following SP and Miner ID from application
DLTX 1 copy in Omaha, Nebraska, USA
Ghostbytes 1 copy in Philadelphia, USA
Telnyx 1 copy multiple locations USA

Adding the following SP to application
GreaterHeat Dallas US Location 
f02361686 
f02345061

**Comment by Sunnyiscoming** [comment]
Hello, @salstorage per the https://github.com/filecoin-project/notary-governance/issues/922 for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

This information will be reviewed by Fil+ Governance team to confirm validity and then the application will be allowed to move forward for additional notary review.

**Comment by salstorage** [comment]
> Hello, @salstorage per the [filecoin-project/notary-governance#922](https://github.com/filecoin-project/notary-governance/issues/922) for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.
> 
> This information will be reviewed by Fil+ Governance team to confirm validity and then the application will be allowed to move forward for additional notary review.

Completed @Sunnyiscoming

**Comment by salstorage** [comment]
Latest update on SP and distribution:

f01886690 f01886710 SEAL STORAGE TECHNOLOGY INC, Las Vegas USA
f01274011 f01746964 f01919423 f01938357 f02238775 DSS Australia 
f01923553 f01923554 f01923555 f01923556 f02181705 SEAL STORAGE TECHNOLOGY INC, Montreal Canada
f01987994 f02202753 VoGo Digital Labs, S Korea
f02229460 f02832654 Aligned USA, Mid West / Ohio, USA
f02361686 f02345061 GreaterHeat Dallas Tx USA
