### ISSUE TITLE
[DataCap Application] Caribbean LDN-02 Seal Storage Technology

### ISSUE THREAD

**Issue by salstorage** [filecoin-project/filecoin-plus-large-datasets#1282]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Seal Storage Technology
- Website / Social Media: https://www.sealstorage.io/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 3.4PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 400TiB
- On-chain address for first allocation: f1bvlifue4nucdljqbcayi7i3ep535y3rackexiyy

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
NOTE: this is LDN app 2 of 2. Total data cap requested for this project is 8.4 PiB.
LDN app 1 of 2 can be found here: https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1281
Seal is collaborating with The Center for Extreme Data Management, Analysis and Visualization (CEDMAV) of the University of Utah on a pilot project to use Filecoin for data storage for a public dataset: OpenVisus datasets (they are very “sparse”, combustion, simulations, earth, satellite etc). The data sets are about 1.4 PiB. Seal and CEDMAV are also exploring specific use-cases and how the Filecoin Network can support ongoing research.

Seal is a carbon-neutral, decentralized cloud storage provider. Seal's technical leadership brings decades of experience from traditional enterprise storage companies including Seagate and Oracle, as well as world-class experience on the Filecoin Network. Today, Seal operates data centers across the US and Canada with enterprise-grade infrastructure and data policies.

```

What is the primary source of funding for this project?
```
Seal is funding the project.
```

What other projects/ecosystem stakeholders is this project associated with?
```
The main stakeholder for this project is the University of Utah CEDMAV group. Our customer views decentralized data storage as an exciting platform that could yield many benefits for future large datasets.
```

## Use-case details

Describe the data being stored onto Filecoin
```
Project Caribbean consists of a 1.4 PiB verified PUBLIC data set belonging to The Center for Extreme Data Management Analysis and Visualization at the University of Utah (CEDMAV, http://cedmav.org/). The data is OpenVisus data sets (they are very “sparse”, combustion, simulations, earth, satellite etc).
```

Where was the data in this dataset sourced from?
```
The Center for Extreme Data Management, Analysis and Visualization (CEDMAV) of the University of Utah
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://drive.google.com/drive/folders/1j6p8peLJJ9tbNhF5mD3sPBUKjFrw5UUy?usp=sharing
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Confirmed - this is a public dataset
```

What is the expected retrieval frequency for this data?
```
The data will be accessed by external collaborators and Researchers.
Retrieval would be daily as and when needed, Seal Storage will keep a unsealed copy for retrieval purposes
```

For how long do you plan to keep this dataset stored on Filecoin?
```
Three year term
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
We plan to store six copies of the 1.4 PiB data set [total of 8.4 PiB] in four different cities, in three different countries and across two continents.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Seal Storage has dual 100 Gbps internet connections. SPs will download data from Seal.
Seal Storage will prepare and CAR the files into 32GB chunks for distribution 

```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We are currently meeting and discussing capabilities with several other SPs. Due to the size of this pilot, our SPs have requested DataCap before committing to the project.
We plan to choose enterprise-grade SPs for this project and will complete our due diligence post DataCap approval

```

How will you be distributing deals across storage providers?
```
1 copy = 1.4 PiB

DLTX 1 copy in Omaha, Nebraska, USA
Ghostbytes 1 copy in Philadelphia, USA
DSS 1 copy in Sydney, Australia
Telnyx 1 copy in USA, multiple locations
Seal Storage 1 copy in Las Vegas, NV USA 
Seal Storage 1 copy in Montreal, Quebec, Canada 

Seal Storage must also keep a full hot copy unsealed for our Customer. 
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Once we receive DataCap, we will begin making deals as soon as customer data is transferred to Seal Storage November 2022
We currently have the support we need.

```

**Comment by mjroddy** [comment]
Overall I am supportive of this project.

Given the size it is important that we get as much 'knowledge' out of this program as possible. A case study and marketing is included. in the Data Storage Plan Link

I would like to see that findings from onboarding this client be shared with other storage providers. This would include challenges, technical and sales tooling, even a case study from the SP's perspective so that the network as a whole benefits from this project.

For Filecoin to improve all SP's must be lifted up.

**Comment by Joss-Hua** [comment]
Willing to be supportive. 
Related to #1281 .

**Comment by Fenbushi-Filecoin** [comment]
Confirm to support the application.
Related to https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1281 .

**Comment by cryptowhizzard** [comment]
Happy to support

**Comment by raghavrmadya** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 3.4PiB

**Expected weekly DataCap usage rate**

> 400TiB

**Client address**

>f1bvlifue4nucdljqbcayi7i3ep535y3rackexiyy

**Comment by GaryGJG** [comment]
Support.
Related to https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1281 .

**Comment by cryptowhizzard** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecymsciep47chlii4ofw43b4egpjwhr2elxlg7aoxuygyywtakhhu 
#### Address 
> f1bvlifue4nucdljqbcayi7i3ep535y3rackexiyy
#### Datacap Allocated
> 174.07TiB
#### Signer Address
> f1krmypm4uoxxf3g7okrwtrahlmpcph3y7rbqqgfa
#### Id
> defbebec-8c39-4265-b914-4735be0e3825
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecymsciep47chlii4ofw43b4egpjwhr2elxlg7aoxuygyywtakhhu

**Comment by Alex11801** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedc7aeowiqj5pvi4qr4wyyjjck4ylsj3nf5aoryhcw3z462ij634c 
#### Address 
> f1bvlifue4nucdljqbcayi7i3ep535y3rackexiyy
#### Datacap Allocated
> 174.07TiB
#### Signer Address
> f1hhippi64yiyhpjdtbidfyzma6irc2nuav7mrwmi
#### Id
> defbebec-8c39-4265-b914-4735be0e3825
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedc7aeowiqj5pvi4qr4wyyjjck4ylsj3nf5aoryhcw3z462ij634c

**Comment by steven004** [comment]
Support.
Related to https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1281 .

**Comment by filplus-checker** [comment]
## DataCap and CID Checker Report[^1]
 - Organization: `Seal Storage Technology`
 - Client: `f1bvlifue4nucdljqbcayi7i3ep535y3rackexiyy`
### Storage Provider Distribution
The below table shows the distribution of storage providers that have stored data for this client.

If this is the first time a provider takes verified deal, it will be marked as `new`.

For most of the datacap application, below restrictions should apply.
 - Storage provider should not exceed 25% of total datacap.
 - Storage provider should not be storing duplicate data for more than 20%.
 - Storage provider should have published its public IP address.
 - All storage providers should be located in different regions.

⚠️ [f01886710](https://filfox.info/en/address/f01886710) has sealed 100.00% of total datacap.

⚠️ [f01886710](https://filfox.info/en/address/f01886710) has unknown IP location.

⚠️ All storage providers are located in the same region.

| Provider                                              | Location | Total Deals Sealed | Percentage | Unique Data | Duplicate Deals |
| :---------------------------------------------------- | -------: | -----------------: | ---------: | ----------: | --------------: |
| [f01886710](https://filfox.info/en/address/f01886710) |  Unknown |           8.00 TiB |    100.00% |    8.00 TiB |           0.00% |

![Provider Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/1282/1671098953938.png)
### Deal Data Replication
The below table shows how each many unique data are replicated across storage providers.
- No more than 25% of unique data are stored with less than 4 providers.

⚠️ 100.00% of deals are for data replicated across less than 4 storage providers.

| Unique Data Size | Total Deals Made | Number of Providers | Deal Percentage |
| ---------------: | ---------------: | ------------------: | --------------: |
|         8.00 TiB |         8.00 TiB |                   1 |         100.00% |

![Replication Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/1282/1671098954573.png)
### Deal Data Shared with other Clients
The below table shows how many unique data are shared with other clients.
Usually different applications owns different data and should not resolve to the same CID.

✔️ No CID sharing has been observed.

[^1]: To manually trigger this report, add a comment with text `checker:manualTrigger`

**Comment by salstorage** [comment]
checker:manualTrigger

**Comment by salstorage** [comment]
checker:manualTrigger

**Comment by salstorage** [comment]
checker:manualTrigger [↩](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1282#user-content-fnref-1-26d57c501ebc5780d12c253f49b2e38b)

**Comment by salstorage** [comment]
checker:manualTrigger

**Comment by salstorage** [comment]
checker:manualTrigger

**Comment by salstorage** [comment]
Paging Notary to sign next DC tranche please
@Joss-Hua @steven004 @Fenbushi-Filecoin  @BlockMakeronline @laudiacay @GaryGJG @mjroddy

**Comment by Fenbushi-Filecoin** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebwem5zc3gw2umbdwcurqesagvxdpffep257ncsos33wvp2maaycq 
#### Address 
> f1bvlifue4nucdljqbcayi7i3ep535y3rackexiyy
#### Datacap Allocated
> 348.15TiB
#### Signer Address
> f1yqydpmqb5en262jpottko2kd65msajax7fi4rmq
#### Id
> c7507b50-3c5e-4c05-860f-10ac96c68ea5
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebwem5zc3gw2umbdwcurqesagvxdpffep257ncsos33wvp2maaycq

**Comment by mjroddy** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedhn4juywefrjykkjjbfoxg4bx44jjv3dwd3ftbm2a4rwgvmzq4ge 
#### Address 
> f1bvlifue4nucdljqbcayi7i3ep535y3rackexiyy
#### Datacap Allocated
> 348.15TiB
#### Signer Address
> f1ystxl2ootvpirpa7ebgwl7vlhwkbx2r4zjxwe5i
#### Id
> c7507b50-3c5e-4c05-860f-10ac96c68ea5
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedhn4juywefrjykkjjbfoxg4bx44jjv3dwd3ftbm2a4rwgvmzq4ge

**Comment by Joss-Hua** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacechgltv3wcdipaximvogusaclvejn5gldh6pkwj7yxudjiyzw2lha 
#### Address 
> f1bvlifue4nucdljqbcayi7i3ep535y3rackexiyy
#### Datacap Allocated
> 348.15TiB
#### Signer Address
> f1tfg54zzscugttejv336vivknmsnzzmyudp3t7wi
#### Id
> c7507b50-3c5e-4c05-860f-10ac96c68ea5
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacechgltv3wcdipaximvogusaclvejn5gldh6pkwj7yxudjiyzw2lha

**Comment by Alex11801** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacealc5eyilq4eenbswigz2jjz4nlv2nbeh4iwaj7woiolp6dghws34 
#### Address 
> f1bvlifue4nucdljqbcayi7i3ep535y3rackexiyy
#### Datacap Allocated
> 348.15TiB
#### Signer Address
> f1hhippi64yiyhpjdtbidfyzma6irc2nuav7mrwmi
#### Id
> c7507b50-3c5e-4c05-860f-10ac96c68ea5
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacealc5eyilq4eenbswigz2jjz4nlv2nbeh4iwaj7woiolp6dghws34

**Comment by cryptowhizzard** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecppm6ta5dzeo7ehifq4uwt6thnt4hdtrsfajffuztopqcbjmsqac 
#### Address 
> f1bvlifue4nucdljqbcayi7i3ep535y3rackexiyy
#### Datacap Allocated
> 348.15TiB
#### Signer Address
> f1krmypm4uoxxf3g7okrwtrahlmpcph3y7rbqqgfa
#### Id
> c7507b50-3c5e-4c05-860f-10ac96c68ea5
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecppm6ta5dzeo7ehifq4uwt6thnt4hdtrsfajffuztopqcbjmsqac

**Comment by kernelogic** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedf4cgebojinwslcg4ooz4tv6tk6iksppjhyindvvcp4nvaccon42 
#### Address 
> f1bvlifue4nucdljqbcayi7i3ep535y3rackexiyy
#### Datacap Allocated
> 348.15TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### Id
> c7507b50-3c5e-4c05-860f-10ac96c68ea5
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedf4cgebojinwslcg4ooz4tv6tk6iksppjhyindvvcp4nvaccon42

**Comment by salstorage** [comment]
Please add the following Miner ID's to project:
f01838599 and f01845552?

**Comment by salstorage** [comment]
Please add the following SP ID to application.

SP's are for Distributed Storage Solutions

f01274011
f01746964

**Comment by salstorage** [comment]
Paging notaries to approve the next tranche please

@Alex11801 @cryptowhizzard @Joss-Hua @steven004  @BlockMakeronline @laudiacay @GaryGJG

**Comment by Fenbushi-Filecoin** [comment]
checker:manualTrigger

**Comment by laudiacay** [comment]
@Fenbushi-Filecoin can I approve the next tranche with these replication rates/do you know where I can look at the rules for this?

**Comment by laudiacay** [comment]
slash @Kevin-FF-USA

**Comment by mjroddy** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebuuiyftkadcvv3ltoir7mvja3h7v4dbdjkvbqjlhppo6zpvs76q2 
#### Address 
> f1bvlifue4nucdljqbcayi7i3ep535y3rackexiyy
#### Datacap Allocated
> 1.56PiB
#### Signer Address
> f1ystxl2ootvpirpa7ebgwl7vlhwkbx2r4zjxwe5i
#### Id
> 76b26b3e-c255-41fc-b2d2-7bea28b23bb5
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebuuiyftkadcvv3ltoir7mvja3h7v4dbdjkvbqjlhppo6zpvs76q2

**Comment by data-programs** [comment]
<img width="32" alt="KYC" Verified src="https://stable.filplus.storage/images/filplus-kyc-verified-badge.png"/>

This user’s identity has been verified through [filplus.storage](https://filplus.storage)

**Comment by salstorage** [comment]
Please note GHOSTBYTES is no longer online 
We are removing GHOSTBTYES from application (Miner ID:   f01506844)

**Comment by salstorage** [comment]
Paging notaries to approve the next tranche please
@Fenbushi-Filecoin @Joss-Hua @steven004 @BlockMakeronline @laudiacay @GaryGJG @Alex11801

**Comment by neogeweb3** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec6zsykebikze4744qgxsr23r5w4bqpesgjyoeepxj3z4r7ti33to 
#### Address 
> f1bvlifue4nucdljqbcayi7i3ep535y3rackexiyy
#### Datacap Allocated
> 1.56PiB
#### Signer Address
> f13k5zr6ovc2gjmg3lvd43ladbydhovpylcvbflpa
#### Id
> 76b26b3e-c255-41fc-b2d2-7bea28b23bb5
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec6zsykebikze4744qgxsr23r5w4bqpesgjyoeepxj3z4r7ti33to

**Comment by C00kies77** [comment]
checker:manualTrigger

**Comment by salstorage** [comment]
Due to removal of Ghostbytes/ Web3Cloud from application.
We are adding SP Vogo-Digital Labs located in S. Korea to store 200 TB's of Caribbean Dataset 
MINER ID's: f02202753 and f01987994

**Comment by Fenbushi-Filecoin** [comment]
> @Fenbushi-Filecoin can I approve the next tranche with these replication rates/do you know where I can look at the rules for this?

Sorry for missing your message @laudiacay . I think there is no clear rule for this. Case by case.

**Comment by salstorage** [comment]
Due to termination of sectors, Remove the following SP and Miner ID from application
DLTX 1 copy in Omaha, Nebraska, USA
Ghostbytes 1 copy in Philadelphia, USA
Telnyx 1 copy multiple locations USA

Adding the following SP to application
GreaterHeat Dallas US Location 
f02361686 
f02345061

**Comment by salstorage** [comment]
f01886690 f01886710 SEAL STORAGE TECHNOLOGY INC, Las Vegas USA
f01274011 f01746964 f01919423 f01938357 f02238775 DSS Australia
f01923553 f01923554 f01923555 f01923556 f02181705 SEAL STORAGE TECHNOLOGY INC, Montreal Canada
f01987994 f02202753 VoGo Digital Labs, S Korea
f02229460 f02832654 Aligned USA, Mid West / Ohio, USA
f02361686 f02345061 GreaterHeat Dallas Tx USA
