### ISSUE TITLE
[DataCap Application] LHL Design Office - Project image

### ISSUE THREAD

**Issue by darleenchan123** [filecoin-project/filecoin-plus-large-datasets#1287]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Beijing LHL Design Office Co., Ltd.
- Website / Social Media: http://www.lhlsq.com/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):2PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):80TiB
- On-chain address for first allocation:f1lirkrd3nuzavjkkhfkz57jgkbpd5bzmtqk3u7uq

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
![image](https://user-images.githubusercontent.com/118407958/202629365-3ee4e8f8-1c11-43fb-b169-640639d126eb.png)
```
LHL Design Office was founded in 2016, focusing on high-end residential space and commercial space research and design, is an interior design office with design as the main, construction as the auxiliary.With a unique modular management model, the company adheres to the business philosophy of providing high-quality full-case design for a small number of customers, and always adheres to the personalized service of non-batch "one-to-three" advanced private customization. Excellent, try our best to meet the personalized service of customers.
```

What is the primary source of funding for this project?
```
Income from business operations.
```

What other projects/ecosystem stakeholders is this project associated with?
```
NO other stakeholder. We will seek out other Filecoin ecosystem providers if needed.
```

## Use-case details

Describe the data being stored onto Filecoin
![image](https://user-images.githubusercontent.com/118407958/202629428-3943b65d-fbe1-466f-8aa6-8b5fb8845561.png)
```
Each of our works is presented through long-term design accumulation and understanding of space and lifestyle. Hundreds of design tasks have been completed so far. This time, we will store the past excellent design products on the chain for public display and long-term storage.
```

Where was the data in this dataset sourced from?
```
Relevant image data after the project design is completed.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://www.lhlsq.com/944.html
https://www.lhlsq.com/770.html
https://www.lhlsq.com/788.html
https://www.lhlsq.com/812.html
https://www.lhlsq.com/752.html
https://www.lhlsq.com/740.html
https://www.lhlsq.com/725.html
https://www.lhlsq.com/709.html
The above are some links, details can be seen on the official website.
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes, it is a public data.
```

What is the expected retrieval frequency for this data?
```
This data is mainly used for design research and is open to download all over the world, but the retrieval frequency is not expected to be too high, because the use of this type of data requires professional analysis capabilities for data in this segment, and the estimated download frequency is about 50 times a year .
```

For how long do you plan to keep this dataset stored on Filecoin?
```
This data has long-term scientific research value, and we will permanently store this data.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
GCR
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Depending on the geographical location of the storage provider, there are mainly two methods: online and offline. Online, we upload the data to the server of the cloud storage provider and send the download link to the other party. Offline, we will mail the physical storage device by express.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
The plan will be evenly allocated to each storage provider, but the actual implementation process may be adjusted according to considerations such as transmission rate, storage cost, and operation and maintenance capabilities.
```

How will you be distributing deals across storage providers?
```
According to the transmission cost with the storage provider is a factor to consider the data volume allocation, low-cost data transfer and high reliability of the storage service provider will obtain a larger proportion of data volume. But we will always insist on decentralized storage, which is a safe way.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
We have already prepared sufficient funds for this work and will start storing transactions as soon as they are approved.
```

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 2PiB

**Expected weekly DataCap usage rate**

> 80TiB

**Client address**

>f1lirkrd3nuzavjkkhfkz57jgkbpd5bzmtqk3u7uq

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Looking at your application i have some questions:
As you are brand new on Github and have no history of past applications it seems to me that applying for 2PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?

Your application is for 5PB of datacap. Can you show us visible proof of the size of your data and the storage systems you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230232885049356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!
