### ISSUE TITLE
[DataCap Application] EMPIAR

### ISSUE THREAD

**Issue by fscann** [filecoin-project/filecoin-plus-large-datasets#1288]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: EMPIAR Public dataset
- Website / Social Media: https://www.ebi.ac.uk/empiar
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100TiB
- On-chain address for first allocation: f1pyshx7hnvpamnc3dfecex7grwjqv5lroi45wbyi

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
I have participated in Space Race and serval hackathon projects. I would like to involve in to FIL+ to gain knowledge as a data preparer, deal with SP and client retrieval, what's more, to store human's most important data permanently. 
 this public dataset size is 2pb, i would like to store 2 copies, in order to achieve that goal, i have 2 isp links with 3000Mbps + 5000Mbps and sufficient 16T hard disks. 
```

What is the primary source of funding for this project?
```
Self-funded
```

What other projects/ecosystem stakeholders is this project associated with?
```
No.
```

## Use-case details

Describe the data being stored onto Filecoin
```
EMPIAR, the Electron Micronscopy Public Image Archive, is a public resource for raw image underpinning 3D cryo-EM maps and tomograms. EMPIAR also accomodates 3D datasets obtained with volume EM techniques and soft and hard X-ray tomography. The purpose of EMPIAR is to provide easy access to state-of-the-art data to facilitate methods development, validation and re-use, e.g, for Machine Learning applications. EMPIAR data is also used for training and teaching purposes and as part of community challenges.
```

Where was the data in this dataset sourced from?
```
EMPIAR
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
Yes
https://www.ebi.ac.uk/empiar 
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Confirm. All data archived in EMPIAR can be re-used freely without any conditions or restrictions ("CC0" license model).
```

What is the expected retrieval frequency for this data?
```
Once per year.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
At least 3 years.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Welcome storage providers from all regions.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
I have prepared enough storage for offine transfer among China. However we are able to provide online transfer with total of 8000Mbps bandwidth for the rest of the world. 
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
Getting in touch with serval asia nodes f01421513, f01096124, f01430671, f01449814, what's more, SPs from community members, big-d exchange, slack that shows ability are welcomed to cooperate with me.
```

How will you be distributing deals across storage providers?
```
I will obey the FIL+ allocation rules for single node not store for more than 25%.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, i am ready.
```

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Looking at your application i have some questions:
It seems to me that applying for 5PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?

Can you show us visible proof of the size of your data and the storage systems you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230232885049356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!

**Comment by fscann** [comment]
Happy to answer your questions.
This site https ://www.ebi.ac.uk/empiar  has 2.26PiB of raw data
Our company is Mkccstorage, website: https://maike.mkccstorage.com/
Thank you for your attention to us and hope to get your support.

**Comment by cryptowhizzard** [comment]
Hi @fscann 

Thanks for your reply but you did not answer my questions, neither did you fill in the form to enable me to do my work.
Let me know when you are ready to continue.

**Comment by fscann** [comment]
@cryptowhizzard , we're happy to answer your questions, please support us.

https://www.ebi.ac.uk/empiar is a public data. As of 2023-02-15, EMPIAR contains 1198 entries and occupies 2.56PB of storage space. We plan to store the data on this website to the Filecoin network superior.

We are v4 notaries, #665 fully demonstrates that we are equipped enough to download empiar data to the Filecoin network, if you are interested in us, you are welcome to check #665.

We look forward to your support!

**Comment by cryptowhizzard** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebyzjj6bkwijy5dni3pcmusr2d4prxagcctvh6xvs2e6z4sba6erg 
#### Address 
> f1pyshx7hnvpamnc3dfecex7grwjqv5lroi45wbyi
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1krmypm4uoxxf3g7okrwtrahlmpcph3y7rbqqgfa
#### Id
> ada0f8df-9999-43d9-91e9-14e1ec16cf79
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebyzjj6bkwijy5dni3pcmusr2d4prxagcctvh6xvs2e6z4sba6erg
