### ISSUE TITLE
[DataCap Application] <Hainan Zhi Le Shengye Technology Co., Ltd> - <leshua app>

### ISSUE THREAD

**Issue by metacodebean** [filecoin-project/filecoin-plus-large-datasets#1289]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Hainan Zhi Le Shengye Technology Co., Ltd.
- Website / Social Media: [https://leshua](https://leshua.info/).[info/](https://leshua.info/)
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 400TiB
- On-chain address for first allocation: f1xqb3hq2ffrngx66ggeh33a4ablylk7saancd2nq

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer.*

## Project details

Share a brief history of your project and organization.
```
1. Established in September 2020, Hainan Zhi Le Shengye Technology Co., Ltd. is a technology startup company specializing in the research and development and operation of web3.0 technology. The team of the company is committed to the research, development and construction of decentralized network and economic model. The vision of the company is to make an important contribution to the landing of web3.0 applications. At present, the company has developed the world's first blockchain short video platform (leshua), which links users around the world with video, provides copyright protection on the chain for video original authors, owns users' personal creation data, and provides reliable bridges and ties for creators to trade their original works. Leshua app has been in operation for two years, and 380000 users have created and edited 1.5 million small videos, taking up storage space 200TiB. The number of leshua users and works will grow at an annual rate of 500%.

2. Leshua is the world's first blockchain short video platform, which links users around the world with video, and combines short video with blockchain technology with the direct value exchange of creators, viewers, advertisers and auditors as the main principle to realize property rights linking, rights confirmation, trading, authorization and other business applications, to create a video platform that can make money by brushing video in fragmented time.
```

<img width="1530" alt="image" src="https://user-images.githubusercontent.com/41883249/202679810-182dd4f7-8f51-4e1c-b97d-42678e94d791.png">

<img width="1543" alt="image" src="https://user-images.githubusercontent.com/41883249/202679871-64fa5dfd-7059-4705-add1-c24df472ff2f.png">

<img width="1593" alt="image" src="https://user-images.githubusercontent.com/41883249/202679913-aae10b25-5d73-4026-9f6f-accedbdaac1b.png">

<img width="1525" alt="image" src="https://user-images.githubusercontent.com/41883249/202679948-4c749bf5-4926-4d46-b736-4eae81567fb5.png">

<img width="1603" alt="image" src="https://user-images.githubusercontent.com/41883249/202680020-15383963-fca4-491b-8ec3-cce82369f4c0.png">

<img width="1469" alt="image" src="https://user-images.githubusercontent.com/41883249/202680051-01f4e851-6ca7-42e7-8165-2dc2f1cb6985.png">

<img width="1465" alt="image" src="https://user-images.githubusercontent.com/41883249/202680090-892bc4da-7fd4-4dac-a2ca-7561480adfca.png">

<img width="1511" alt="image" src="https://user-images.githubusercontent.com/41883249/202680327-124ce4d0-64cb-4839-8bf9-35a6613d6592.png">

<img width="1554" alt="image" src="https://user-images.githubusercontent.com/41883249/202680355-3dc3f251-abd7-48e4-a37b-3f2bf6731dce.png">

What is the primary source of funding for this project?
```
    Company product and service revenue.
```

What other projects/ecosystem stakeholders is this project associated with?
```
Not yet.
```

## Use-case details

Describe the data being stored onto Filecoin
```
1. A large number of user's video works.
2. Store product pictures.
3. Network device logs.
4. Monitor data.
```
Where was the data in this dataset sourced from?
```
Company and users.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this.
```
    https://img.leshuapro.com/video_50/100343d8-18489845f2d.mp4
    https://img.leshuapro.com/video_50/1123768b-18489b335e2.mp4
    https://img.leshuapro.com/video_50/125cbfe1-18489d79540.mp4
    https://img.leshuapro.com/video_50/13055d04-18489d61f23.mp4
    https://img.leshuapro.com/video_50/1412c6c1-18489570435.mp4
    https://img.leshuapro.com/video_50/14b96f6-18489d8739d.mp4
    https://img.leshuapro.com/video_50/169482d3-1848980f8c8.mp4
    https://img.leshuapro.com/video_50/1a7ba868-18489821d06.mp4
    https://img.leshuapro.com/video_50/1b959395-1848a0aa5da.mp4
    https://img.leshuapro.com/video_50/1b9a9028-18489969f2d.mp4
    https://img.leshuapro.com/video_50/1ca054a3-18489ad3d37.mp4
    https://img.leshuapro.com/video_50/1d6bce7-18489d6a1fd.mp4
    https://img.leshuapro.com/video_50/2156a2e4-184895afb5e.mp4
    https://img.leshuapro.com/video_50/24c62402-18489874eb0.mp4
    https://img.leshuapro.com/video_50/27f99717-18489d2723f.mp4
    https://img.leshuapro.com/video_50/28825393-184897fdc8c.mp4
    https://img.leshuapro.com/video_50/288bdef7-18489cd47d7.mp4
    https://img.leshuapro.com/video_50/29e57bf0-184897ef4b8.mp4
    https://img.leshuapro.com/video_50/2c863817-184890a0f71.mp4
    https://img.leshuapro.com/video_50/2e987b49-18489b20e65.mp4
    https://img.leshuapro.com/video_50/2fba4405-1848a07a60c.mp4
    https://img.leshuapro.com/video_50/314783fc-18489cd3cb3.mp4
    https://img.leshuapro.com/video_50/31ac064e-18489d7338e.mp4
    https://img.leshuapro.com/video_50/33f77b36-18488e9da7d.mp4
    https://img.leshuapro.com/video_50/34cff753-1848946837e.mp4
    https://img.leshuapro.com/video_50/35950b87-18489aa2d5c.mp4
    https://img.leshuapro.com/video_50/384dbbf6-1848a0994e5.mp4
    https://img.leshuapro.com/video_50/3b633e5c-18489d6d415.mp4
    https://img.leshuapro.com/video_50/3d1ed2ee-1848a025481.mp4
    https://img.leshuapro.com/video_50/3f39c210-18489b532d9.mp4
    https://img.leshuapro.com/video_50/3ff0c695-18489b00e0e.mp4
    https://img.leshuapro.com/video_50/4683b9d-184895a04b9.mp4
    https://img.leshuapro.com/video_50/4cefb10e-18489d4941b.mp4
    https://img.leshuapro.com/video_50/4d3052b-18489d491d3.mp4
    https://img.leshuapro.com/video_50/4e6430b3-1848957e533.mp4
    https://img.leshuapro.com/video_50/4f0cf57c-18489367f57.mp4
    https://img.leshuapro.com/video_50/553249d7-18489b456da.mp4
    https://img.leshuapro.com/video_50/555b4579-184897df6dc.mp4
    https://img.leshuapro.com/video_50/56167fe6-1848982faa2.mp4
    https://img.leshuapro.com/video_50/597dbbb3-184897e90b8.mp4
    https://img.leshuapro.com/video_50/5edbba-18489d7edd4.mp4
    https://img.leshuapro.com/video_50/6321eda3-18489d8ec28.mp4
    https://img.leshuapro.com/video_50/63558263-1848963bcf3.mp4
    https://img.leshuapro.com/video_50/6e6ec29-184893fccdf.mp4
    https://img.leshuapro.com/video_50/911230f-18489648bf0.mp4
    https://img.leshuapro.com/video_50/951fd2d-18489a7f0fc.mp4
    https://img.leshuapro.com/video_50/983e763-18489ced684.mp4
    https://img.leshuapro.com/video_50/e9b25b-18489d598bd.mp4
    https://img.leshuapro.com/video_50/eb66417-18489e139dd.mp4
    https://img.leshuapro.com/video_50/f8caf50-184897b4259.mp4

```
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes, we're pretty sure.
```

What is the expected retrieval frequency for this data?
```
1-2 times a year.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
Minimum 540 days.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?

    Hong Kong.

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Online download or offline mailing.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We prefer storage service providers with higher reliability.
```

How will you be distributing deals across storage providers?
```
Store to multiples SPs.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes.
```

**Comment by metacodebean** [comment]
Hello, dear official reviewer, I found that all the applications that were applied later than ours have been approved. Why have we not been approved yet? is there any problem after us? Look forward to reply, thank you!

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 400TiB

**Client address**

> f1xqb3hq2ffrngx66ggeh33a4ablylk7saancd2nq

**Comment by Tom-OriginStorage** [comment]
1：can you send email to [[filplus-app-review@fil.org]
2：Can you tell which nodes should be stored？

**Comment by metacodebean** [comment]
> 1：can you send email to [[[filplus-app-review@fil.org](mailto:filplus-app-review@fil.org)] 2：Can you tell which nodes should be stored？
My reply:
1: Email has been sent
<img width="643" alt="image" src="https://user-images.githubusercontent.com/41883249/207498173-3dc12727-ba34-45b2-8f8e-4aff50ca8193.png">
2: The  nodes should be stored:  f01319803.   f01123400

**Comment by metacodebean** [comment]
1: Email has been sent
![image](https://user-images.githubusercontent.com/41883249/207544903-860e44b0-cf2f-4b28-95e3-83957084ab70.png)

2: The nodes should be stored: 
f01319803  
f01123400
f01991310

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Looking at your application i have some questions:
As you are brand new on Github and have no history of past applications it seems to me that applying for 5PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?

Can you show us visible proof of the size of your data and the storage systems you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230337462961356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!

**Comment by cryptowhizzard** [comment]
#1350
