### ISSUE TITLE
[DataCap Application] IPFS SUNGNAM

### ISSUE THREAD

**Issue by minigoju** [filecoin-project/filecoin-plus-large-datasets#129]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: IPFS Sungnam
- Website / Social Media: https://cafe.naver.com/ipfssungnam
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5 PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100TiB
- On-chain address for first allocation: f3td4j3qzhaxrrpqfywpezyck4cnxva62k44hagdncwmwttb5tjp4tzkicf4nurg4vvtoevmrovrc6t2bjwldq

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
IPFS Sungnam was established in June 2020 with a capital of $1,000,000. It is a technology-driven company leading the Korean distributed storage market by focusing on blockchain and IPFS technology R&D, supercomputing server R&D, distributed storage construction, distributed cloud storage platform development, and supercomputer server import & export. Our node is currently being operated by SK & LG IDC. We are establishing IPFS-specialized research institutes with large Korean companies. We are discussing to collaborate with government agencies and service platforms in various industries. The aim of distributed storage service of IPFS is to provide a safe and affordable storage service that anyone can participate in in various fields in Korea.
```

What is the primary source of funding for this project?
```
Actually We are planning to expand our business to METAVERSE GAME, so I think there gonna be huge amount of data to be stored permanently. 
```

What other projects/ecosystem stakeholders is this project associated with?
```
There is no other projects/ecosystem stakeholders associated with.
```

## Use-case details

Describe the data being stored onto Filecoin
```
We need to store docs, photos, videos, information data, game data, and product information in our distributed storage.
```

Where was the data in this dataset sourced from?
```
Sources are from the various industry platforms we will cooperate with in the future.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
(https://user-images.githubusercontent.com/91580013/143798140-df866547-64e9-4411-8c8d-8fb6b74e39ac.jpeg)
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes, all data stored in the cloud storage of IPFS Sungnam is open to the public. Anyone can access.
```

What is the expected retrieval frequency for this data?
```
This type of data search frequency is expected to be not so high, but we have to store these data for a long time. This is the reason why we chose the Filecoin network for storage. We want to retain the data for a long period of time and provide them to those who need, whenever they require.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
permanently.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
In the Republic of Korea.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Our Miners are not big enough to store all of data. so I will distribute my data according to fil-reputation site. We do have an offline data transfer process.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
This should include a plan to ensure the We have our own massive storage inside SK & LG IDC in Korea. We will store data from various industry platforms in our distributed cloud storage, and all users using the platform will be able to freely store and retrieve their data.
```

How will you be distributing deals across storage providers?
```
Since our IDC cannot store all data from all platforms, we will distribute the deal to trusted storage providers that run nodes stably.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes we have enough resources and funds to start trading as soon as we receive DataCap. Now, We are discussing collaboration with many companies in Korea, and as soon as DataCap is secured, collaboration can proceed quickly. There is nothing the community can do to help our business in Korea right now. But as the size of the Korean market grows, we will need support, and then we will ask for it.
```

**Comment by galen-mcandrew** [comment]
Resubmission from #107.

The provided website appears to be a forum, and the sample data does not seem to match the described content. Can you please provide some more details about this project and the data?

**Comment by minigoju** [comment]
@galen-mcandrew Most of our data is video data, and it is difficult to upload because the capacity is too large.
I'm going to upload some captured files. 
![image](https://user-images.githubusercontent.com/96175055/146854244-dba2f8d0-c77f-484a-b532-47c67afa31b3.png)

**Comment by minigoju** [comment]
@galen-mcandrew It has been 4 weeks since I applied. We are affiliated with various game companies in Seongnam, Silicon Valley of Korea, and have a lot of data related to games. Please process it quickly.
