### ISSUE TITLE
[DataCap Application] <Memolabs>-<centralized information>

### ISSUE THREAD

**Issue by zhoukailun** [filecoin-project/filecoin-plus-large-datasets#1290]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Memolabs
- Website / Social Media:https://www.memolabs.org/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):3PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):100TiB
- On-chain address for first allocation: f17u7iepqbrxbgedcgu4sgq5znwwiwhaakl55vcoa

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Memoriae: An efficient, safe and reliable large-scale decentralized data storage system builds decentralized storage services around the blockchain.

Traditional data center-based centralized storage systems will face challenges from cost performance, security Unprecedented challenges with reliability.

Memoriae is a decentralized cloud storage system designed to meet the above challenges and meet the data storage needs of future Internet applications. Memoriae is built on the blockchain, organizes and manages a huge number of idle edge storage devices scattered around the world, and forms a hierarchical low-cost, high-security, high-reliability single storage system to serve global users household.

The core construction idea of Memoriae is to store only the most critical information in the blockchain to make full use of its high security, high availability, and high reliability features; at the same time, store other data in cheap edge storage devices, In order to avoid the blockchain with low performance and low scalability becoming the bottleneck of the system.

Besides, we propose an exhaustive technical framework to mitigate the security and reliability risks introduced by untrusted and unreliable edge storage devices. Finally, we also discuss Some details about running Memoriae.

We will use availability and storage time usage as indicators to measure the service quality of Memoriae. Specifically, users pay service fees based on service availability and storage time and usage, and service providers (edge storage device providers) distribute revenue based on availability and storage time and usage.

Regarding the storage data of edge devices, Memoriae adopts Proof of Reliability based on Proof of Storage and Proof of Space & Time to evaluate the reliability and time usage of data storage, thereby improving the credibility of the system .

At the same time, these verifications are consensused through random beacons and BFT protocols to avoid manipulation and single point of failure. The consensus mechanism is completed in an off-chain manner, thereby avoiding the burden of transactions other than storage on the blockchain.
```

What is the primary source of funding for this project?
```
Our own funds and funds provided by investors, partners.
```

What other projects/ecosystem stakeholders is this project associated with?
```
Our associated projects include DHVC, HASHLEY, SNZ, COMMANDO, HASHGLOBAL, METIS, HARMONGY, CHAIN CAPITAL, MSQ, ETHEREUN, My Token, etc. These are our partners.
```

## Use-case details

Describe the data being stored onto Filecoin
```
Images, metadata, video, audio, user-provided files.
```

Where was the data in this dataset sourced from?
```
Company.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://drive.google.com/drive/folders/1g9sb3kIpCZDRpO5eo4BFnQSvHSn5BYvg?usp=share_link
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Confirm.
```

What is the expected retrieval frequency for this data?
```
1-2 times a year.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
At least 36 months.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Asian.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Both online and offline transmission.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We choose storage providers with a good reputation and knowledge of the project.
```

How will you be distributing deals across storage providers?
```
The data we allocate depends on the quality and availability of their nodes and teams, ideally we allocate transactions based on their business needs.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, once we receive the DataCap we have enough funds to trade and we can easily disburse funds.
```

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 3PiB

**Expected weekly DataCap usage rate**

> 100TiB

**Client address**

>f17u7iepqbrxbgedcgu4sgq5znwwiwhaakl55vcoa

**Comment by NDLABS-OFFICE** [comment]
Can you please send an email from your official business account to [filplus-app-review@fil.org](mailto:filplus-app-review@fil.org)?

**Comment by zhoukailun** [comment]
Hi, I have sent the email. Please help confirm. Thank you! 
![EmailScreenshot](https://user-images.githubusercontent.com/35447302/207036161-0433424e-7d0b-425c-b518-e41f273de95d.png)

**Comment by NDLABS-OFFICE** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebxduhmbubmpq7wmrkvibsiabjsqrfeax6l3yjwtyf4oidi2ct2aa 
#### Address 
> f17u7iepqbrxbgedcgu4sgq5znwwiwhaakl55vcoa
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1yayfsv6whu3rheviucvventj3y6t542xfpb47ei
#### Id
> dbfae83d-3306-43ea-925a-f96b8c89d47f
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebxduhmbubmpq7wmrkvibsiabjsqrfeax6l3yjwtyf4oidi2ct2aa

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Looking at your application i have some questions:
As you are brand new on Github and have no history of past applications it seems to me that applying for 3PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?

Can you show us visible proof of the size of your data and the storage systems you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230232885049356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!
