### ISSUE TITLE
[DataCap Application] Beijing Kundou Technology Co., Ltd - mubu

### ISSUE THREAD

**Issue by KD-spring** [filecoin-project/filecoin-plus-large-datasets#1291]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name:Beijing Kundou Technology Co., Ltd
- Website / Social Media:https://mubu.com/about     https://mubu.com/home
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):1 PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):35TiB
- On-chain address for first allocation:f1ocso2nbparbf732c5btuco7kguy2erchnsoatlq

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Beijing Kundou Technology Co., Ltd., established in December 2015, is a humanities technology company. Kundou Technology chose to start from a SaaS efficiency tool manufacturer, and tried to focus on thinking, helping outstanding talents to put their thinking to the ground, optimizing their working mode and improving their working efficiency. The contribution of outstanding talents is the main driving force of social progress, making talents more efficient and making society better! 
Mubu is the first product of Kundou Technology, and its main orientation is to solve the efficiency problems of efficient people in the workplace or life, organize notes, create independently and manage tasks. After more than one year's development and improvement, the mubu web version was launched in May 2016, the desktop version was launched on December 1, and the mobile version was launched on March 24. Multi-platform synchronization provides excellent services for users' work and life. 
```

What is the primary source of funding for this project?
```
If users need to use more functions and solve the photo limit, they need to recharge to upgrade to advanced accounts, and the main funds are obtained from users' recharge and purchase functions. 
```

What other projects/ecosystem stakeholders is this project associated with?
```
NO. 
```

## Use-case details

Describe the data being stored onto Filecoin
```
The data we need to store is the mind maps created, uploaded and published by users on the mubu app and the text exported in various formats. We need to store all kinds of data such as words and images in the text.
```

Where was the data in this dataset sourced from?
```
The data comes from mind maps created and published by users on the mubu app, texts and pictures exported in various formats, and various texts and pictures published by authoritative media forwarded by the authority in the mubu community.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://mubu.com/explore/2GcHPcWOE7?
https://mubu.com/explore/2G9cAlpoU06
https://mubu.com/explore/62ZJAUEqxII
https://mubu.com/explore/5qOEfgaTF1l
https://mubu.com/explore/59WdaO_JsWe
```

Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes, it is a public data.
```

What is the expected retrieval frequency for this data?
```
The data is used for text publishing and personal writing, and is expected to be downloaded about twice a year. 
```
For how long do you plan to keep this dataset stored on Filecoin?
```
The data is used for text publishing and personal writing, and is expected to be downloaded about twice a year.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Asian region
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
If in China, we will choose online transmission, Offline data will be stored on servers in China.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We will choose storage providers with extensive experience.
```

How will you be distributing deals across storage providers?
```
We'll give the storage providers an even distribution ratio.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
We have our own product revenue, so we can afford to fund it, and the slack community is a great inspiration for us.
```

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Looking at your application i have some questions:
As you are brand new on Github and have no history of past applications it seems to me that applying for 1PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?

Can you show us visible proof of the size of your data and the storage systems you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230232885049356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!
