### ISSUE TITLE
[DataCap Application] Timedoor Internet Co., Ltd - timedoor academy

### ISSUE THREAD

**Issue by OTLENS** [filecoin-project/filecoin-plus-large-datasets#1292]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Timedoor Internet Co., Ltd
- Website / Social Media:https://jp.timedoor.net/        https://timedooracademy.com/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):2 PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):60 TiB
- On-chain address for first allocation:f1tnx4mva5zte72vjhlztyxokhcvw3eyjlbf5oddi

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Timedoor is a Japanese-funded Internet company dedicated to providing the best IT services to global customers. It was established in Bali, Indonesia in 2014 and has branches in Indonesia, Jakarta, Bali and Japan. The company's business includes web design, application development, online advertising, programming schools and so on. With about 150 employees, we are committed to creating the best service people need by putting the best technology into every job.
```

What is the primary source of funding for this project?
```
The main funding comes from designing pages for customers, earning revenue from applications, and the cost of purchasing coding and design class by customers.
```

What other projects/ecosystem stakeholders is this project associated with?
```
NO other stakeholder. 
```

## Use-case details

Describe the data being stored onto Filecoin
```
The stored data comes from programming teaching courses, teaching materials and online learning tasks that students need to complete offered by Timedoor for customers. These include all kinds of learning programming, teaching video, teaching audio, audio text, video text and other resources purchased by users, which involve all kinds of data such as text, pictures, audio and video to be stored.
```

Where was the data in this dataset sourced from?
```
The teachers team of Doortime recorded their own images and audio related to teaching courses and teaching materials.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://www.youtube.com/watch?v=QaVfzHPp8XU
https://www.youtube.com/watch?v=CRK6scu0AgI
https://www.youtube.com/watch?v=J1EmZbBG5wI
https://www.youtube.com/watch?v=Y2qipistBe4
https://www.youtube.com/watch?v=eGI9lJ-RXlw
```

Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes, it is a public data.
```

What is the expected retrieval frequency for this data?
```
Since this data is open to the world and used for programming teaching, it is estimated that the download frequency will be about four times a year. 
```
For how long do you plan to keep this dataset stored on Filecoin?
```
We expect to store the data for one year, and we will decide whether to continue to store the data on filecoin according to the quality of this service and the development of our company.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Asian region
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
We will choose online transmission, and offline data will be searched for local storage vendors and stored on local servers.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We will choose storage providers with high transmission speed, excellent equipment quality and rich experience.
```

How will you be distributing deals across storage providers?
```
We will decide according to the qualifications of storage providers, such as the quality of equipment they provide and the quantity of pledges.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Company assets cover all costs, and the slack community is a great inspiration.
```

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Looking at your application i have some questions:
As you are brand new on Github and have no history of past applications it seems to me that applying for 2PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?

Can you show us visible proof of the size of your data and the storage systems you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230337462961356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!
