### ISSUE TITLE
[DataCap Application] Changsha JIDU Information Tec

### ISSUE THREAD

**Issue by jiduxx** [filecoin-project/filecoin-plus-large-datasets#1294]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Changsha Jidu Information Technology Co., Ltd.
- Website / Social Media: https://www.0731i.com/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):1.85PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 50TiB
- On-chain address for first allocation: f1z64mkxtv7g3n27yyvo3p3ywkuafoaskraus47na

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Changsha JIDU Information Technology was established in 2010, from providing basic website construction services for enterprises to mobile Internet as the main battlefield. The company has established a business closed loop based on traffic, products and operations. Based on Internet platforms such as Baidu, wechat, Douyin and Taobao, the company provides novels, comics, e-commerce, mini programs, evaluation and other services. With millions of fans, the company takes creating user value as its core concept and provides users with more healthy, positive and valuable Internet products. Extreme Information has a very young and combative team. All the middle and senior management have grown up step by step from the grassroots, and their performance is excellent. Everyone has the business incubation experience from 0 to 1, the common understanding of corporate culture, good management, multi-department collaboration, so that both new and old employees can continue to grow in the company. Accurately find their own position, and play their own value. From 2010 to now, the company team has been growing, gradually forming a complete and mature business model.
```

What is the primary source of funding for this project?
```
By providing website construction services, product services and internet operations.
```

What other projects/ecosystem stakeholders is this project associated with?
```
None.
```

## Use-case details

Describe the data being stored onto Filecoin
```
Text, pictures and other data needed to build the website; There are novels, comics, e-commerce, small programs, evaluation and other Internet product data.
```

Where was the data in this dataset sourced from?
```
It comes partly from the large amount of data generated in business processes and partly from shared data packets provided by customers.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://pan.baidu.com/s/1Kwt4zzZ4Gz76Kp2WkI5RgQ
https://www.aliyundrive.com/s/z2MDfkD6A8s/folder/6371257a4d99bd3fbe504e4e9e2a5d143a4967e1
https://www.51zxw.net/Show.aspx?cid=337&id=18082
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes, it is public data.
```

What is the expected retrieval frequency for this data?
```
The data is a backup for the long-term development of the enterprise, and the retrieval frequency is about five times a year.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
The backup data needs to be stored perpetually.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
No restrictions in region.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
It could be transmitted both online or offline.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We will actively engage with the storage provider community. In addition, we will determine the correct data storage provider based on their past reputation, storage capacity, and geographic location.
```

How will you be distributing deals across storage providers?
```
We will contact multiple storage providers to implement the principle of distributed storage.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
We have a good understanding of the market and we have enough capital to prepare for it. We hope that the community and storage providers can provide technical support and guarantee for us.
```

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 1.85PiB

**Expected weekly DataCap usage rate**

> 50TiB

**Client address**

> f1z64mkxtv7g3n27yyvo3p3ywkuafoaskraus47na

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Looking at your application i have some questions:
As you are brand new on Github and have no history of past applications it seems to me that applying for 1.85PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?

Can you show us visible proof of the size of your data and the storage systems you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230232885049356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!
