### ISSUE TITLE
[DataCap Application] <Tianjin Hong-En Perfect Future Education Technology Co., Ltd> - <Educational application>

### ISSUE THREAD

**Issue by Hongen1** [filecoin-project/filecoin-plus-large-datasets#1295]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Tianjin Hong En Perfect Future Education Technology Co., Ltd（天津洪恩完美未来教育科技有限公司）
- Website / Social Media:  https://www.ihuman.com、https://v.douyin.com/rHqpbHC/、https://weibo.com/u/5930816252
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 2PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 75TiB
- On-chain address for first allocation: f3q7632xjpmgzpi6y6627tecyemdi3trlbbzpnomnmafo3vw2lrvtylecjtadvpiyc6imovmivbogwj4nybila

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Hong En is a leading technology puzzle product enterprise in China established in 2016. The company is committed to making it easier for parents to raise children and happier for their children to grow up. Benefiting from more than 20 years' experience in parent-child industry, excellent original content, advanced scientific and technological innovation and deep accumulation of cutting-edge R&D strength, Hong En provides parents with efficient parent-child companionship resources and stimulates children's natural curiosity and desire for exploration through unique and interesting interactive product experience. Cultivate children's language ability, logic ability, reading ability and creativity, as well as their natural interest in Chinese traditional culture.

With the unique and advanced technical strength accumulated in 3D engine, AI/AR interaction and big data analysis of children's behavior and psychology, Hong En will continue to provide parents in China and all over the world with efficient, relaxed and high-quality parenting experience with high-quality scientific and technological educational products, and start a fruitful and fun growth journey for children.
```

What is the primary source of funding for this project?
```
If users need to unlock more educational resources and study packages, users need to choose to recharge monthly cards, annual cards or purchase permanent packages independently, and the main funds are obtained from users' recharge and purchase functions.
```

What other projects/ecosystem stakeholders is this project associated with?
```
NO other.
```

## Use-case details

Describe the data being stored onto Filecoin
```
The data we need to store are the educational resource data of our platform, courseware animation data such as audio and video, and learning homework data generated by users. We need to store all kinds of data such as text, image, audio and video in educational resources.
```

Where was the data in this dataset sourced from?
```
The stored data comes from the teaching videos, pictures and texts on each app and the data generated when users use the app, such as homework and tasks.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://www.bing.com/videos/search?q=%e6%b4%aa%e6%81%a9%e8%af%86%e5%ad%97&qpvt=%e6%b4%aa%e6%81%a9%e8%af%86%e5%ad%97&FORM=VDRE
https://www.ihuman.com/shizi/
https://www.ihuman.com/math/
https://www.ihuman.com/english/
https://www.ihuman.com/pinyin/
https://www.ihuman.com/book/
https://www.ihuman.com/story/
https://www.ihuman.com/baike/
https://www.ihuman.com/reading/
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes, it is a public data.
```

What is the expected retrieval frequency for this data?
```
This data is used by users to learn after downloading, and the expected retrieval frequency is 5 times a year.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
We expect to store it for one year first, and then we need to observe the storage effect before making a decision.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Asian region.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
If in China, we will choose online transmission, Offline data will be stored on servers in China.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We will choose experienced and reliable storage providers.
```

How will you be distributing deals across storage providers?
```
We'll give the storage providers an even distribution ratio.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
We have our own product revenue, so we can afford to fund it, and the slack community is a great inspiration for us.
```

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 2PiB

**Expected weekly DataCap usage rate**

> 75TiB

**Client address**

> f3q7632xjpmgzpi6y6627tecyemdi3trlbbzpnomnmafo3vw2lrvtylecjtadvpiyc6imovmivbogwj4nybila
