### ISSUE TITLE
[DataCap Application] <Times Architectural Design> - <Design Cases>

### ISSUE THREAD

**Issue by timesdesign** [filecoin-project/filecoin-plus-large-datasets#1297]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Qingdao Times Architectural Design Co., Ltd. 
- Website / Social Media: http://www.qdsct.com/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 2PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 80TiB
- On-chain address for first allocation: f122wmm4xuiy6a3t5c4mg7kwt2jg5gb3re667aunq

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Qingdao Times Architectural Design Co., Ltd. was established in July 1985. For more than 30 years, it has always been adhering to the concept of the times of "seeking innovation, refinement, and truth-seeking", focusing on management internally, building an image externally, starting from changing mechanisms, improving quality, and improving services, reforming with determination, pioneering and enterprising, and improving the management level of the enterprise. , Design capabilities and service quality have been rapidly improved, and it has become the main force in Shandong's architectural design market. It is an architectural design and engineering company, mainly engaged in the integrated design of architecture, interior and landscape planning of high-star business hotels, resort hotels, commercial complexes, characteristic commercial streets and other commercial real estate.
![image](https://user-images.githubusercontent.com/118799981/203251806-fa718c87-a6b0-438b-8115-d99348598a60.png)
```

What is the primary source of funding for this project?
```
Investment and benefits from projects.
```

What other projects/ecosystem stakeholders is this project associated with?
```
None.
```

## Use-case details

Describe the data being stored onto Filecoin
```
It is mainly the case sharing designed by the company and the picture data of the company's project case analysis.
```

Where was the data in this dataset sourced from?
```
The works designed by the company and the classic design concepts and design cases collected by the company.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
http://www.qdsct.com/anli.aspx
https://docs.google.com/document/d/1tZG6SFJpjWDCmq82pfXB6m9ndf_MRMglqJxOHpmezmI/edit?usp=share_link
https://docs.google.com/document/d/1K5hmpUHmfKnf4NJk0ACykH7gmZXZd15PrFbMg-GU-xA/edit?usp=sharing
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes, it is.
```

What is the expected retrieval frequency for this data?
```
Maybe 1~5 times per year.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
We hope to store on Filecoin for long.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Anywhere in the world is ok, but in Asia is better.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Maybe we will choose offline data transmission, but we will compare various methods to choose the most economical and convenient method.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
The conditions for us to choose a storage provider are: a good reputation (confirmed through the official website or social media account); mature scale; stable and reliable equipment; able to support retrieval.
```

How will you be distributing deals across storage providers?
```
We will store data on multiple storage providers.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, we have enough funding for this. If we have some problems during this process, we will seek help from notaries and officials.
```

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 2PiB

**Expected weekly DataCap usage rate**

> 80TiB

**Client address**

> f122wmm4xuiy6a3t5c4mg7kwt2jg5gb3re667aunq

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Looking at your application i have some questions:
As you are brand new on Github and have no history of past applications it seems to me that applying for 2PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?

Can you show us visible proof of the size of your data and the storage systems you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230232885049356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!
