### ISSUE TITLE
[DataCap Application] Shenzhen Derier Technology Co., Ltd.

### ISSUE THREAD

**Issue by Melody-1166** [filecoin-project/filecoin-plus-large-datasets#1299]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Shenzhen Derier Technology Co., Ltd.
- Website / Social Media: https://www.Derier.com.cn/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5 PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100TiB
- On-chain address for first allocation: f156pj6fm7ndebnrfkgbrk4r6aycbmm5xjo4ioccy 

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
 Shenzhen DERIER Technology Co., Ltd. was established in 2001. We cooperate with internationally renowned jewelry masters such as Evert de Graeve, Pascal Sert, and Lars Heinz. It is a global jewelry high-end brand focusing on jewelry research and development, design, production and sales. 1000+ people, 30+ stores. Since 2010, DERIER has been included in the "Top 500 Most Valuable Brands" released by the World Brand Lab for three consecutive years, with a brand value of 2.362 billion.
In 2002, DERIER became a member of the standing director unit of China Gemstone Association;
In March 2004, DERIER won the honorary title of "Famous Brand in China's Jewelry Industry" issued by the State Administration for Industry and Commerce and China Gemstone Association.
In May 2004, 30 outstanding managers including brand founder Liu Xudong and Li Zekai won the "World Manager Achievement Award Future Leader", becoming the only one in the industry to receive this honor;
In 2005, DERIER became the only designated jeweler for the New Silk Road Model Contest; currently, DERIER has opened high-end stores in 31 cities in China, including Hangzhou, Ningbo, Chengdu, Chongqing, Wuhan, Shanghai, and Lanzhou, serving millions of people.
In 2006, Liu Xudong, chairman of the group, was elected as the vice president of the Sichuan International Chamber of Commerce. In 2007, he became the vice president of the Sichuan Jewelry Association. In 2008, he became the vice president of the Chengdu Jewelry Chamber of Commerce.
In 2009, the DERIER jewelry business team was invited to participate in the Basel International Jewelry Show
In 2010, the jewelry business team of DERIER was invited as the VIP guest of Japan's largest Tokyo International Jewelry Show to participate in the exhibition and as the ribbon-cutting guest.
In 2011, DERIER jewelry was awarded the 500 most valuable brands in China, with a brand value of 1.925 billion
In 2011, the DERIER jewelry business team went to Las Vegas, USA to participate in the International Jewelry Exhibition
In 2012, the DERIER jewelry business team participated in the Gold Jewelry Exhibition in Vicenza, Italy
In 2012, DERIER jewelry was awarded the 500 most valuable brands in China, with a brand value of 2.362 billion
In 2014, we established DERIER COLLEGE, focusing on cultivating and exporting jewelry industry talents for the world.
In 2015, DERIER Jewelry won the honorary title of "Excellent Enterprise in China's Jewelry and Jade Jewelry Industry in 2015".
In 2015, the DERIER jewelry business team went to Las Vegas, USA to participate in the International Jewelry Exhibition
In 2017, ABAS awarded DERIER the honor of "Top Ten Leading Brands in China (Industry)"
In 2018, we were invited to participate in the Munich Jewelry Show in Germany
In 2020, Liu Xudong, chairman of the group, was re-elected as the "Executive Director" of China Jewelry and Jade Jewelry Industry Association
In 2022, it will become the vice-chairman unit of Guangdong Jewelry Chamber of Commerce, and Liu Xudong, chairman of the group, will be elected as the vice-chairman of Shenzhen Jewelry Chamber of Commerce

As a well-known jewelry brand in the world, our jewelry has cooperated with many stars, such as. Wu Jinyan endorsed our "Bright Love" series. Wang Likun endorsed our "Bright Love X Ray" series, Chen Qiaoen endorsed our "Bright Love X Ray" series, Guo Caijie endorsed our "Star Series", DERIER has sponsored the movie "Follow Your Heart" and the TV series "The Time of You and Me"。
```

What is the primary source of funding for this project?
```
Our company has a long history, profitable, is the enterprise's own funds.
```

What other projects/ecosystem stakeholders is this project associated with?
```
We are completely independent
```

## Use-case details

Describe the data being stored onto Filecoin
```
As a world-renowned jewelry brand established for more than 20 years, we have many precious design manuscripts, jewelry production, transportation, maintenance, sales and other data. At the same time, we also have a lot of data about jewelry publicity, promotion, explanation, etc. We established the DERIER Business School, and we have accumulated a lot of jewelry courseware, and we also hope to store this part of the data on the Filecoin network.

Therefore, these data are roughly:

Promotional pictures and live videos of DERIER jewelry products
Promotional pictures, videos, customer pre-sales and after-sales data of DERIER physical store
DERIER enterprise data, for example, DERIER's PPT, promotional articles, videos, team building content
DERIER designer's precious design draft, factory production environment, pictures
Honors received by DERIER, for example, DERIER has continuously won the award of 500 most valuable brands for many years
Pictures and videos of celebrities and models shooting, promoting and endorsement for DERIER
Data on events organized and attended by DERIER
Derier Business School courseware data
DERIER sponsored the movie "Like a Shadow" and the TV series "My Time with You", and the data in this part is very huge. dates.
```

Where was the data in this dataset sourced from?
```
The data stored on the Filecoin network comes from DERIER companies, such as DERIER stores, DERIER factories, DERIER operations department and brand department, DERIER business school, TV plays and movies sponsored by DERIER，etc.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
Yes, I'd love to share with you:

1. Promotional pictures and videos of DERIER jewelry products:
https://drive.google.com/drive/folders/1jk1ymtNcYRhwRK-_yKe67j1f1Bw13T2o
https://drive.google.com/drive/folders/1BMVSL0iOseVxbzUDEUT6zW2Z2_3q_Zhi
https://drive.google.com/drive/folders/1NsPWVUdtTEHyP1-iErS0DzWDNvjOGoJz

2. Honors received by DERIER: https://drive.google.com/drive/folders/1iwZmLFcD8nCqazwHGfWuI59x3KFr0oOq

3. DERIER designer's design draft and production pictures:
https://drive.google.com/drive/folders/1qtHHl4ffvMKxEGymFMO4fbHCbnFJ3gjn

3. Celebrities and models endorse DERIER:
https://drive.google.com/drive/folders/16Xq2stfWDQgmJaQpP0w8iidNW6MDLNUP
https://drive.google.com/drive/folders/1kAcDT0X_sDFneEnzuU4XLyjtUX9aI31B

5. Propaganda articles of DERIER:
https://drive.google.com/drive/folders/1qD1CLfvUz6huXXNL_kGwHk56VPHwHw4K

6. Data from DERIER Business School:
https://drive.google.com/drive/folders/1iRLzp8rmXIUyM4eUvyyG0ZKkgksnLa-R?usp=sharing

7. Real picture of DERIER store:
https://drive.google.com/drive/folders/1OLaC7-d4gTRyLe4Do2mbZwlrMBbW8wmV

8. Activities held by DERIER:
https://drive.google.com/drive/folders/1F6PpaeEwrmLzQGTTEMW3LKPfb0oep14m

9、TV plays and movies sponsored by DERIER:
https://drive.google.com/drive/folders/1o0HX9uZOD1wRYaVOvHumBs0KWlXbjKJK
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Confirm
```

What is the expected retrieval frequency for this data?
```
What is stored on the Filecoin network is the data of our spare parts, which is expected to be surveyed 1-2 times a year
```

For how long do you plan to keep this dataset stored on Filecoin?
```
We hope that the Filecoin network will store data for us, and we hope that the data can be stored for a long time, and we plan to store it for 2-3 years.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
We do not limit the storage area, it can be in Singapore, Portugal, Hong Kong, Vietnam, and even more other areas.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Over the past 20 years, we have accumulated a lot of data, which is very large, and we prefer to transmit it offline.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We will select storage providers based on their capabilities, reputation, integrity, and response speed. We will contact storage providers on websites such as filfox, slack, and filplus, and score them. We will select storage providers ranked by scores.

At the same time, we will also understand the retrievable capabilities of storage providers to ensure that they can provide retrieval when we need retrievable.
```

How will you be distributing deals across storage providers?
```
We will contact more than 10 storage providers, and finally select 4-6 storage providers for cooperation.

We will transfer the data to storage providers through the hard disk, and we will abide by the rules of FIL Plus, and the storage ratio of each storage provider will not exceed 25%.

We plan to make 3-5 backups of our data to ensure that the data can be better stored.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, our money and resources are abundant.
```

**Comment by Melody-1166** [comment]
Hello, we have sent two emails to your mailbox (because the memory of a single email is limited, so we only sent two), which contain our business license and more content, please check it, and Please pass our application early, thank you.

**Comment by Melody-1166** [comment]
<img width="1122" alt="6e406219-ced0-4304-9b40-ffd984cc9734" src="https://user-images.githubusercontent.com/116047447/203285568-2561a034-ff61-4b2f-a39b-27986b7f8453.png">

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 100TiB

**Client address**

> f156pj6fm7ndebnrfkgbrk4r6aycbmm5xjo4ioccy

**Comment by sowhat99** [comment]
@stouldlisa
As a jewelry company with a history of more than 20 years, we integrate R&D, design, production, sales and after-sales. The company's data is huge. Our current data exceeds 3P and increases at a rate of 100T+every year. We plan to store five copies of 1P data backups on the Filecoin network. In the future, we are willing to store more data on the Filecoin network. Please check our example data:
https://drive.google.com/drive/folders/1jk1ymtNcYRhwRK-_yKe67j1f1Bw13T2o
https://drive.google.com/drive/folders/1BMVSL0iOseVxbzUDEUT6zW2Z2_3q_Zhi
https://drive.google.com/drive/folders/1NsPWVUdtTEHyP1-iErS0DzWDNvjOGoJz
https://drive.google.com/drive/folders/1iwZmLFcD8nCqazwHGfWuI59x3KFr0oOq
https://drive.google.com/drive/folders/1qtHHl4ffvMKxEGymFMO4fbHCbnFJ3gjn
https://drive.google.com/drive/folders/16Xq2stfWDQgmJaQpP0w8iidNW6MDLNUP
https://drive.google.com/drive/folders/1kAcDT0X_sDFneEnzuU4XLyjtUX9aI31B
https://drive.google.com/drive/folders/1OLaC7-d4gTRyLe4Do2mbZwlrMBbW8wmV
https://drive.google.com/drive/folders/1F6PpaeEwrmLzQGTTEMW3LKPfb0oep14m
https://drive.google.com/drive/folders/1o0HX9uZOD1wRYaVOvHumBs0KWlXbjKJK

**Comment by Melody-1166** [comment]
@newwebgroup 
Thank you for your question. Both derer.com and derer.com.cn are our company's mailboxes. Now we use derer.com.cn to filplus-app-review@fil.org An email was also sent to confirm that our company is applying for FIL+.

In addition, we added the email of derier.com as the official email to https://www.derier.com.cn/ , please check.
![1299官网添加邮箱的截图](https://user-images.githubusercontent.com/116047447/204961512-dd72d549-02ba-494f-bf0d-0b101fcf7750.png)

![e4897f2e4e28246aeedb69fc86fc38d](https://user-images.githubusercontent.com/116047447/204961580-fd637c9c-53bb-47df-8613-adc0852b168f.png)

**Comment by Melody-1166** [comment]
@newwebgroup 
Thank you for your question. Both derer.com and derer.com.cn are our company's mailboxes. Now we use derer.com.cn to filplus-app-review@fil.org An email was also sent to confirm that our company is applying for FIL+.

In addition, we added the email of derier.com as the official email to https://www.derier.com.cn/ , please check.
![1299官网添加邮箱的截图](https://user-images.githubusercontent.com/116047447/204963313-146a4c80-4651-4773-8c03-a283679c5942.png)
![1299邮件已发送截图](https://user-images.githubusercontent.com/116047447/204963329-8fcc4252-7876-48bc-b9ab-60cf217830bf.png)

**Comment by Melody-1166** [comment]
@stouldlisa
As a jewelry company with a history of more than 20 years, we integrate R&D, design, production, sales and after-sales. The company's data is huge. Our current data exceeds 3P and increases at a rate of 100T+every year. We plan to store five copies of 1P data backups on the Filecoin network. In the future, we are willing to store more data on the Filecoin network. Please check our example data:
https://drive.google.com/drive/folders/1jk1ymtNcYRhwRK-_yKe67j1f1Bw13T2o
https://drive.google.com/drive/folders/1BMVSL0iOseVxbzUDEUT6zW2Z2_3q_Zhi
https://drive.google.com/drive/folders/1NsPWVUdtTEHyP1-iErS0DzWDNvjOGoJz
https://drive.google.com/drive/folders/1iwZmLFcD8nCqazwHGfWuI59x3KFr0oOq
https://drive.google.com/drive/folders/1qtHHl4ffvMKxEGymFMO4fbHCbnFJ3gjn
https://drive.google.com/drive/folders/16Xq2stfWDQgmJaQpP0w8iidNW6MDLNUP
https://drive.google.com/drive/folders/1kAcDT0X_sDFneEnzuU4XLyjtUX9aI31B
https://drive.google.com/drive/folders/1OLaC7-d4gTRyLe4Do2mbZwlrMBbW8wmV
https://drive.google.com/drive/folders/1F6PpaeEwrmLzQGTTEMW3LKPfb0oep14m
https://drive.google.com/drive/folders/1o0HX9uZOD1wRYaVOvHumBs0KWlXbjKJK

**Comment by stcouldlisa** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecj27boyjpin4bmuqlernetbwaxvgswlyspk2j2wa2cqcxjvtypja 
#### Address 
> f156pj6fm7ndebnrfkgbrk4r6aycbmm5xjo4ioccy
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1jvvltduw35u6inn5tr4nfualyd42bh3vjtylgci
#### Id
> 94c81203-1e92-47c3-868d-8b9ad198cdcb
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecj27boyjpin4bmuqlernetbwaxvgswlyspk2j2wa2cqcxjvtypja

**Comment by swatchliu** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb6qiz5ryevapxlc4ecita7kkbo3trnfssdwa6ma3isiywrglxrpi 
#### Address 
> f156pj6fm7ndebnrfkgbrk4r6aycbmm5xjo4ioccy
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1yh6q3nmsg7i2sys7f7dexcuajgoweudcqj2chfi
#### Id
> 94c81203-1e92-47c3-868d-8b9ad198cdcb
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb6qiz5ryevapxlc4ecita7kkbo3trnfssdwa6ma3isiywrglxrpi

**Comment by ChangeHowRan** [comment]
> ## Request Proposed
> Your Datacap Allocation Request has been proposed by the Notary
> 
> #### Message sent to Filecoin Network
> > bafy2bzacecj27boyjpin4bmuqlernetbwaxvgswlyspk2j2wa2cqcxjvtypja
> 
> #### Address
> > f156pj6fm7ndebnrfkgbrk4r6aycbmm5xjo4ioccy
> 
> #### Datacap Allocated
> > 50.00TiB
> 
> #### Signer Address
> > f1jvvltduw35u6inn5tr4nfualyd42bh3vjtylgci
> 
> #### Id
> > 94c81203-1e92-47c3-868d-8b9ad198cdcb
> 
> #### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecj27boyjpin4bmuqlernetbwaxvgswlyspk2j2wa2cqcxjvtypja

Hello, LISA, distinguished notary, would you sign for us?

We have 150T of data. In order to ensure data security, we need 4 backups to be stored in 4 SPs. Each SP accounted for no more than 30%.

https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1251

Really need your support to move on! Thanks a lot!

**Comment by ChangeHowRan** [comment]
> Why did you apply for 5P? How many copies do you plan to back up? How much data do you have now?

Hello, LISA, distinguished notary, would you sign for us?https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1251

We have 150T of data. In order to ensure data security, we need 4 backups to be stored in 4 SPs. Each SP accounted for no more than 30%.

Really need your support to move on! Thanks a lot!

**Comment by ChangeHowRan** [comment]
> ## Request Approved
> Your Datacap Allocation Request has been approved by the Notary
> 
> #### Message sent to Filecoin Network
> > bafy2bzaceb6qiz5ryevapxlc4ecita7kkbo3trnfssdwa6ma3isiywrglxrpi
> 
> #### Address
> > f156pj6fm7ndebnrfkgbrk4r6aycbmm5xjo4ioccy
> 
> #### Datacap Allocated
> > 50.00TiB
> 
> #### Signer Address
> > f1yh6q3nmsg7i2sys7f7dexcuajgoweudcqj2chfi
> 
> #### Id
> > 94c81203-1e92-47c3-868d-8b9ad198cdcb
> 
> #### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb6qiz5ryevapxlc4ecita7kkbo3trnfssdwa6ma3isiywrglxrpi

Hello, distinguished notary, would you sign for us?https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1251

We have 150T of data. In order to ensure data security, we need 4 backups to be stored in 4 SPs. Each SP accounted for no more than 30%.

Really need your support to move on! Thanks a lot!

**Comment by herrehesse** [comment]
Dear Applicant,

Due to the increased amount of erroneous/wrong Filecoin+ data recently, on behalf of the entire community, we feel compelled to go deeper into datacap requests. Hereby to ensure that the overall value of the Filecoin network and Filecoin+ program increases and is not abused.

Please answer the questions below as comprehensively as possible.

**Customer data**

- Could you demonstrate exactly how and to what extent customer contact occurred? 

We expect that for the onboarding of customers with the scale of an LDN there would have been at least multiple email and perhaps several chat conversations preceding it. A single email with an agreement does not qualify here.

- Did the customer specify the amount of data involved in this relevant correspondence?

- Why does the customer in question want to use the Filecoin+ program? 

_Should this only be soley for acquiring datacap this is of course **out of the question**. The customer must have a legitimate reason for wanting to use the Filecoin+ program which is intended as a program to store useful and public datasets on the network._ 

- Why is the customer data considered Filecoin+ eligible?

_(As an intermediate solution Filecoin offers the FIL-E program or the glif.io website for business datasets that do not meet the requirements for a Filecoin+ dataset)_


**Files and Processing**

- Could you please demonstrate to us how you envision processing and transporting the customer data in question to any location for preparation?
- Would you demonstrate to us that the customer, the preparer and the intended storage providers all have adequate bandwidth to process the set with its corresponding size?
- Would you tell us how the data set preparer takes into account the prevention of duplicates in order to prevent data cap abuse?


Hopefully you understand the caution the overall community has for onboarding the wrong data. We understand the increased need for Filecoin+, however, we must not allow the program to be misused. Everything depends on a valuable and useful network, let's do our best to make this happen. Together.

**Comment by BDEio** [comment]
@Melody-1166 Hi! Great to see that you have gotten approval for DataCap!
BDE is a verified deals auction house helping you to get paid storing your valuable data with reliable storage providers. If you need any help, we are always here for you！

**Comment by Melody-1166** [comment]
> Dear Applicant,
> 
> Due to the increased amount of erroneous/wrong Filecoin+ data recently, on behalf of the entire community, we feel compelled to go deeper into datacap requests. Hereby to ensure that the overall value of the Filecoin network and Filecoin+ program increases and is not abused.
> 
> Please answer the questions below as comprehensively as possible.
> 
> **Customer data**
> 
> * Could you demonstrate exactly how and to what extent customer contact occurred?
> 
> We expect that for the onboarding of customers with the scale of an LDN there would have been at least multiple email and perhaps several chat conversations preceding it. A single email with an agreement does not qualify here.
> 
> * Did the customer specify the amount of data involved in this relevant correspondence?
> * Why does the customer in question want to use the Filecoin+ program?
> 
> _Should this only be soley for acquiring datacap this is of course **out of the question**. The customer must have a legitimate reason for wanting to use the Filecoin+ program which is intended as a program to store useful and public datasets on the network._
> 
> * Why is the customer data considered Filecoin+ eligible?
> 
> _(As an intermediate solution Filecoin offers the FIL-E program or the glif.io website for business datasets that do not meet the requirements for a Filecoin+ dataset)_
> 
> **Files and Processing**
> 
> * Could you please demonstrate to us how you envision processing and transporting the customer data in question to any location for preparation?
> * Would you demonstrate to us that the customer, the preparer and the intended storage providers all have adequate bandwidth to process the set with its corresponding size?
> * Would you tell us how the data set preparer takes into account the prevention of duplicates in order to prevent data cap abuse?
> 
> Hopefully you understand the caution the overall community has for onboarding the wrong data. We understand the increased need for Filecoin+, however, we must not allow the program to be misused. Everything depends on a valuable and useful network, let's do our best to make this happen. Together.



> 
I am the owner of Derier, a top 500 jewelry supplier in the world.

Our company was established in 2001, and our own data exceeds 3P, including some public data and some very important private data. We plan to experience the storage of Filecoin through FIL+ first, and then store the data of our precious jewelry design files in E-fil.

We have provided a lot of information, please check:

1. Promotional pictures and videos of DERIER jewelry products:
https://drive.google.com/drive/folders/1jk1ymtNcYRhwRK-_yKe67j1f1Bw13T2o
https://drive.google.com/drive/folders/1BMVSL0iOseVxbzUDEUT6zW2Z2_3q_Zhi
https://drive.google.com/drive/folders/1NsPWVUdtTEHyP1-iErS0DzWDNvjOGoJz

2. Honors received by DERIER: https://drive.google.com/drive/folders/1iwZmLFcD8nCqazwHGfWuI59x3KFr0oOq

3. DERIER designer's design draft and production pictures:
https://drive.google.com/drive/folders/1qtHHl4ffvMKxEGymFMO4fbHCbnFJ3gjn

3. Celebrities and models endorse DERIER:
https://drive.google.com/drive/folders/16Xq2stfWDQgmJaQpP0w8iidNW6MDLNUP
https://drive.google.com/drive/folders/1kAcDT0X_sDFneEnzuU4XLyjtUX9aI31B

5. Propaganda articles of DERIER:
https://drive.google.com/drive/folders/1qD1CLfvUz6huXXNL_kGwHk56VPHwHw4K

6. Data from DERIER Business School:
https://drive.google.com/drive/folders/1iRLzp8rmXIUyM4eUvyyG0ZKkgksnLa-R?usp=sharing

7. Real picture of DERIER store:
https://drive.google.com/drive/folders/1OLaC7-d4gTRyLe4Do2mbZwlrMBbW8wmV

8. Activities held by DERIER:
https://drive.google.com/drive/folders/1F6PpaeEwrmLzQGTTEMW3LKPfb0oep14m

9、TV plays and movies sponsored by DERIER:
https://drive.google.com/drive/folders/1o0HX9uZOD1wRYaVOvHumBs0KWlXbjKJK

We have cooperated with many top designers in the world, and they are distributed in the United States, Canada and other places.

We are planning to participate in notary conferences where we would like to present us to you.

**Comment by herrehesse** [comment]
@Melody-1166 Very awesome! Love to assist you with the onboarding. Can you try and answer the remainder of the questions asked in the above post?

**Comment by Melody-1166** [comment]
> @Melody-1166 Very awesome! Love to assist you with the onboarding. Can you try and answer the remainder of the questions asked in the above post?

Thank you for your endorsement, we plan to answer all questions at the notary meeting, and we anticipate participating in the next notary meeting.

**Comment by cryptowhizzard** [comment]
Hi @Melody-1166 

Can you please fill out [this form](https://form.jotform.com/230232885049356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!

**Comment by Melody-1166** [comment]
> Hi @Melody-1166
> 
> Can you please fill out [this form](https://form.jotform.com/230232885049356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.
> 
> Thanks!

We are trying to find a sp, because of the rules of three continents, our communication with overseas sp is not smooth, so it may take some time, if I find a sp, I am filling out your form, is that ok?

**Comment by cryptowhizzard** [comment]
> > Hi @Melody-1166
> > Can you please fill out [this form](https://form.jotform.com/230232885049356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.
> > Thanks!
> 
> We are trying to find a sp, because of the rules of three continents, our communication with overseas sp is not smooth, so it may take some time, if I find a sp, I am filling out your form, is that ok?

ofc!
