### ISSUE TITLE
[DataCap Application] <Tianjin Huibur Technology Co., Ltd> 

### ISSUE THREAD

**Issue by janeehur** [filecoin-project/filecoin-plus-large-datasets#1301]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Tianjin Huibur Technology Co., Ltd
- Website / Social Media:Website:http://www.huibur.com/  wechat: HUIBUR 科技
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):2.3PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):100TiB
- On-chain address for first allocation:f1raieov7hveqsbeyuznsnah4kv6iyxt3yjph7lbi

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Please answer here.
1.The core team of Huibo started in 2016, and Tianjin Huibo Technology Co., Ltd. was established in January 2019. Huibo is committed to solutions for the industrial Internet of Things and the localization of military industry. From the data collection of the underlying equipment to the analysis of the upper-level data, as well as the management and control platforms such as WMS and MES, it helps the comprehensive upgrade of industrial intelligent manufacturing, and realizes production line monitoring and production management.
2.China's military industry reforms, and equipment is fully localized. Huibo Technology has seized the development opportunities brought by national strategies such as "military-civilian integration" and "Made in China 2025", and has comprehensively explored localized operating systems, databases, etc., and has been fully and successfully implemented.

What is the primary source of funding for this project?
```
Please answer here.
Business and investment income and APP income

What other projects/ecosystem stakeholders is this project associated with?
```
Please answer here.
NO other stakeholder. 

## Use-case details

Describe the data being stored onto Filecoin
```
Please answer here.
A large amount of product information of the company and its customers and a large amount of information in the collection process need to be stored, as well as a large amount of service design data and a large amount of data generated by the company's APP and platform background.

Where was the data in this dataset sourced from?
```
Please answer here.
The company's product collection, APP and platform background.

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
Please answer here.
https://drive.google.com/drive/folders/1h9rT_ttMpDjkd_YQGweaBzSLPivMmb6l
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Please answer here.
Yes, it is a public data.

What is the expected retrieval frequency for this data?
```
Please answer here.
Involving a lot of product information, in order to innovate more products, the download frequency is expected to be about four times a year.

For how long do you plan to keep this dataset stored on Filecoin?
```
Please answer here.
We expect to store for 1 year, as the product information is constantly updated.

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Please answer here.
Currently in China, if the company conducts business overseas, it will consider overseas storage.

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Please answer here.
Equal distribution for easy communication.
If within China, we will choose to transmit online, and offline data will be stored on servers in China.

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
Please answer here.
We will choose the most experienced SP in China
[f0433542][f01841826][f01592495]

How will you be distributing deals across storage providers?
```
Please answer here.
According to the degree of importance, it is divided into product business, platform backend and APP backend.

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Please answer here.
The company has very large partners and investors in China, and we have sufficient financial support. We can follow Twitter information at any time, and recently plan to enter SLACK to study.

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 2.3PiB

**Expected weekly DataCap usage rate**

> 100TiB

**Client address**

>f1raieov7hveqsbeyuznsnah4kv6iyxt3yjph7lbi

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Looking at your application i have some questions:
As you are brand new on Github and have no history of past applications it seems to me that applying for 5PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?

Can you show us visible proof of the size of your data and the storage systems you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230337462961356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!
