### ISSUE TITLE
[DataCap Application] <Shanghai Boohee technology co., ltd> - <Boohee>

### ISSUE THREAD

**Issue by Boohee111** [filecoin-project/filecoin-plus-large-datasets#1303]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Shanghai Boohee technology co., ltd（上海薄荷健康科技股份有限公司）
- Website / Social Media: http://www.boohee.com 、 https://v.douyin.com/rXJ9Bq9/ 、 https://weibo.com/1822042062 、https://space.bilibili.com/19729246、 https://www.xiaohongshu.com/user/profile/59e9963382ec397c771ccfd1?xhsshare=CopyLink&appuid=59e9963382ec397c771ccfd1&apptime=1574732748、
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 3PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100TiB
- On-chain address for first allocation: f14dnxy5vh3hvxzsxiczsvca6lkvuokakju5bdz6a

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Shanghai Boohee Health Technology Co., Ltd. (hereinafter referred to as "Boohee Technology") is a mobile Internet company focusing on health, and our vision is to "make people healthy, beautiful and happy". Boohee app and Boohee.com have over 10 million users, and have achieved good results in health and bodybuilding applications in app store and Android markets. Our main products: Boohee app is the most popular weight loss and fitness app in China. http://www.boohee.com/app/ Boohee Technology not only provides users with healthy lifestyle and upward community atmosphere through app, but also provides users with its own brand of high-quality health food-Boohee Light Truck Series. The number of users exceeds 10 million, and the daily activity exceeds 1 million.
```

What is the primary source of funding for this project?
```
According to the health pressure of users at different stages of their lives, multi-category packaged foods are developed to meet the daily needs of consumers and promote their consumption.
Provide health nutrition management payment functions, including food nutrition, calorie inquiry, customized recipes, diet analysis, photo identification of food calories, healthy community and online stores, etc.
Provide intelligent services and more consumption privileges for member users, including personal customized health programs, nutrition analysis, AI nutritionists, exclusive customized foods for members, etc., and enjoy a healthy life lightly.
```

What other projects/ecosystem stakeholders is this project associated with?
```
NO other.
```

## Use-case details

Describe the data being stored onto Filecoin
```
**Rich food data:** Boohee Health has an Internet food database established for more than 10 years-Mint Food Database, which contains 7 kinds of nutrients, more than 40 kinds of nutrition data and 500,000 pieces of food data to be stored.
**User data accumulation:** Boohee itself has 60 million registered users. The health data and eating habits entered by users every day will become the basis for the research and development of mint products. Users' search results will also become an important reference for research and development.
**Health Science Popularization Content:** Boohee also distributes original health content on major We Media platforms such as Vibrato, Weibo and WeChat, attracting the attention of nearly 10 million fans in the form of health KOL and creative videos. These pictures, texts, audio and video data are very large.
```

Where was the data in this dataset sourced from?
```
This data set comes from food data, user data accumulation and health science popularization content, mainly audio and video, pictures and texts, and data generated by users using app.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://www.bilibili.com/video/BV1264y1u7HT/?vd_source=d02ca08201fc6684f684836596f4ef89
https://www.bilibili.com/video/BV1v5411t7uW/?vd_source=d02ca08201fc6684f684836596f4ef89
https://www.bilibili.com/video/BV1Ak4y1R7PB/?vd_source=d02ca08201fc6684f684836596f4ef89
https://www.bilibili.com/video/BV1E64y1T71L/?vd_source=d02ca08201fc6684f684836596f4ef89
 https://v.douyin.com/rXeH66u/ 
https://v.douyin.com/rXe5ojm/ 
https://v.douyin.com/rXemVLb/ 
https://www.xiaohongshu.com/discovery/item/636dfa09000000001f02090c
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes, it is a public data.
```

What is the expected retrieval frequency for this data?
```
This data is used by users to learn after downloading, and the expected retrieval frequency is 5 times a year.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
We expect to store it for one year first, and then we need to observe the storage effect before making a decision.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Asian region.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
If in China, we will choose online transmission, Offline data will be stored on servers in China.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We will choose experienced and reliable storage providers.
```

How will you be distributing deals across storage providers?
```
We'll give the storage providers an even distribution ratio.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
We have our own product revenue, so we can afford to fund it, and the slack community is a great inspiration for us.
```

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 3PiB

**Expected weekly DataCap usage rate**

> 100TiB

**Client address**

> f14dnxy5vh3hvxzsxiczsvca6lkvuokakju5bdz6a

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Looking at your application i have some questions:
As you are brand new on Github and have no history of past applications it seems to me that applying for 3PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?

Can you show us visible proof of the size of your data and the storage systems you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230232885049356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!
