### ISSUE TITLE
[DataCap Application] Migu Culture

### ISSUE THREAD

**Issue by Cayden51** [filecoin-project/filecoin-plus-large-datasets#1305]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Migu Culture Technology Co., Ltd
- Website / Social Media:www.migu.cn
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):400TiB
- On-chain address for first allocation:f1utaos4kjh4lbywmvgrfy3nx5ts3c7dxq3nmvwua

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Migu Culture Technology Co., Ltd. ("Migu Company" for short) is an integrated professional subsidiary company established by China Mobile for the mobile Internet field and responsible for the provision, operation and service of products in the digital content field. It is a music, video, and reading subsidiary of China Mobile. The only operating entity in the digital business segment of, games and animation, with five subsidiaries of Migu Music, Migu Video, Migu Digital Media, Migu Interactive Entertainment, and Migu Animation. At present, Migu has become a leading domestic immersive platform for all-scenario brands, gathering more than 35 million+ songs, 4.6 million videos, 600,000+ books, 1100+ games, and 750,000 episodes of animated cartoons. Facing the future, Migu will vigorously explore the "Internet + digital content" operation innovation, combine content incubation and channel cooperation, focus on cross-domain IP operations, and actively create new media integration, digital content aggregation, copyright transactions, and content entrepreneurship innovation. The big platform is dedicated to bringing changes in the entertainment lifestyle for users.
```

What is the primary source of funding for this project?
```
Company income.
```

What other projects/ecosystem stakeholders is this project associated with?
```
No.
```

## Use-case details

Describe the data being stored onto Filecoin
```
Videos(films/live shows), audios and pics.
```

Where was the data in this dataset sourced from?
```
It comes from materials provided by our company. We have a large number of videos and audios in stock.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
Yes. I can show you the sample.
https://1drv.ms/u/s!AqytNS2M9IaDaj2dtV80OnNNLWE?e=aJQVgv
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes, all the data will be posted on the website.
```

What is the expected retrieval frequency for this data?
```
We plan to check the network 2 times per month.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
We expect to be a permanent archival.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
We welcome any region to accept our deal.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Yes. We'll use offline data transmission to make the data transfer more secure and stable.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We plan to select some miners who provide services reliably and stably.
```

How will you be distributing deals across storage providers?
```
We will try to distribute it equally across the sps. We also decide how much to distribute based on the actual capacity of the sps.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
We hope the community will approve our application.
```

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 400TiB

**Client address**

>f1utaos4kjh4lbywmvgrfy3nx5ts3c7dxq3nmvwua

**Comment by 1475Notary** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceazq3d3omqncyl45azuuuye44wsxoeqwetcrjbwqapp25i4iu5ega 
#### Address 
> f1utaos4kjh4lbywmvgrfy3nx5ts3c7dxq3nmvwua
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1ofq4mngy7ggcp755pfquq2gphjjnlydolf6awtq
#### Id
> 8483477a-8004-4ecc-adea-7bb933533382
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceazq3d3omqncyl45azuuuye44wsxoeqwetcrjbwqapp25i4iu5ega

**Comment by swatchliu** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebkuanq7jhsovcf4jgg7hmenbfujxlc6l2oj2qihl54ov3aynp6fk 
#### Address 
> f1utaos4kjh4lbywmvgrfy3nx5ts3c7dxq3nmvwua
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1yh6q3nmsg7i2sys7f7dexcuajgoweudcqj2chfi
#### Id
> 8483477a-8004-4ecc-adea-7bb933533382
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebkuanq7jhsovcf4jgg7hmenbfujxlc6l2oj2qihl54ov3aynp6fk

**Comment by Casey-PG** [comment]
Deal Data Replication needs to be improved in the next round.

**Comment by Suyanj** [comment]
Good to me,willing to sign.

**Comment by Suyanj** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebqpxqctooy2obmtbhnxj6p46zocptw3lcacquijxgtslrlgw6hhi 
#### Address 
> f1utaos4kjh4lbywmvgrfy3nx5ts3c7dxq3nmvwua
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1ihv7gz3vn3xqvikpt4rwryecgisl7745lodx3yi
#### Id
> 5980f537-0d51-470d-83ff-6b06342917e2
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebqpxqctooy2obmtbhnxj6p46zocptw3lcacquijxgtslrlgw6hhi
