### ISSUE TITLE
[DataCap Allocation] - SiGe-Technology

### ISSUE THREAD

**Issue by SiGe-Technology** [filecoin-project/filecoin-plus-large-datasets#1306]
---
name: Large Dataset Notary application
about: Clients should use this application form to request a DataCap allocation via a LDN for a dataset
title: "SiGe-Technology"
labels: 'application, Phase: Diligence'
assignees: ''

---
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: SiGe Technology
- Website / Social Media: http://www.sigezn.com/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100TiB
- On-chain address for first allocation: f1kh7vqg4dcdtkwugc5wgd4vuitixiy7e6ugnalmy
- Region: Greater China Region

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Guangzhou SiGe Intelligent Technology Co., Ltd, founded in 2014 and headquartered in Guangzhou, is a leading provider of "intelligent manufacturing, intelligent factory" solutions in China.
SiGe Intelligent insists on the concept of "innovation, win-win", constantly innovating product solutions, providing customers with high-quality products and services, creating value for customers and realizing the value of SiGe.
SiGe is a hardware and software research and development company, and has accumulated rich experience in research and development over the years.
We are committed to industrial interconnection, digital factory and intelligent logistics field.At present, we have independent intellectual property rights of industrial object linkage products and automated logistics AGV series products, which provide powerful and innovative product support for the digital transformation implementation of well-known domestic enterprises such as GAC, Great Wall Motor and Dongfeng Liuzhou Automobile.
In addition, we also have experience in the development of medical device controllers, and have a cooperative R&D agreement with Mojo Biotech (Shanghai) for single cell analyzers.

```

What is the primary source of funding for this project?
```
For now, as a service provider, our main revenue comes from service fees and a small portion from financing.
```

What other projects/ecosystem stakeholders is this project associated with?
```
There is no other projects/ecosystem stakeholders associated with.
```

## Use-case details

Describe the data being stored onto Filecoin
```
The data is mainly composed of pictures and videos. Since Siegel is a hardware and software R&D company and solution provider, our video and picture content is made up of two parts: 3D modeling solution and real-life shooting of the solution implementation effect. As a service provider, we need to use monitors to store a large amount of automated real-time video data for backend personnel to operate and maintain. As an R&D company, we need to create a large number of 3D modeling solutions.
```

Where was the data in this dataset sourced from?
```
The material in 3d modeling comes from the production of employees, while the real-time video comes from our company's backend server.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
Pic：https://pan.baidu.com/s/1IR2yxl2HepIWUmtbF-XVag?pwd=ex2s 

Video：https://pan.baidu.com/s/1rUD6dNeEJeVPnQLX4Y7iuw?pwd=dlje 
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes.
All of these data are owned by Sige, some of which are publicly available, while the rest of the data are in ready to public status.
```

What is the expected retrieval frequency for this data?
```
Twice a year or more.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
5 years at least.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Asia.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
We prefer online, if needed offline can also be considered.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We plan to select around 10 the SPs who with high reputation and would cooperate for a long time with.
```

How will you be distributing deals across storage providers?
```
At the first, we will distribute the data equally among the ten storage providers, and then adjust the data distribution according to their strengths.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, we already had some ressources to start making deals as soon as we receive DataCap. And we don't need funding from community, we need to get more weekly allocation of DC requested.
```

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 100TiB

**Client address**

> f1kh7vqg4dcdtkwugc5wgd4vuitixiy7e6ugnalmy

**Comment by 1ane-1** [comment]
Here are your data samples, can you provide more about it to proof that you need 5PiB Datacap?
![image](https://user-images.githubusercontent.com/91301211/206126917-0307f972-0850-4f77-8ded-fce46ead07ec.png)
![image](https://user-images.githubusercontent.com/91301211/206126953-567cf604-e7a4-4161-850d-a20ce3379c66.png)

**Comment by newwebgroup** [comment]
Any updates?

About KYC&KYB
1：Could you send an email to [filplus-app-review@fil.org](mailto:filplus-app-review@fil.org) ？

The content should include the number of the LDN application. If possible, please attach copies of the business license and other valid certificates

2：Can you provide more detailed information about other storage providers participated in this program, such as you can list SPs you have contacted with at present?
3. How large is your existing dataset? How much is the data growth per month?

**Comment by SiGe-Technology** [comment]
> Here are your data samples, can you provide more about it to proof that you need 5PiB Datacap?
> ![image](https://user-images.githubusercontent.com/91301211/206126917-0307f972-0850-4f77-8ded-fce46ead07ec.png)
> ![image](https://user-images.githubusercontent.com/91301211/206126953-567cf604-e7a4-4161-850d-a20ce3379c66.png)



> Here are your data samples, can you provide more about it to proof that you need 5PiB Datacap?
> ![image](https://user-images.githubusercontent.com/91301211/206126917-0307f972-0850-4f77-8ded-fce46ead07ec.png)
> ![image](https://user-images.githubusercontent.com/91301211/206126953-567cf604-e7a4-4161-850d-a20ce3379c66.png)



> Here are your data samples, can you provide more about it to proof that you need 5PiB Datacap?
> ![image](https://user-images.githubusercontent.com/91301211/206126917-0307f972-0850-4f77-8ded-fce46ead07ec.png)
> ![image](https://user-images.githubusercontent.com/91301211/206126953-567cf604-e7a4-4161-850d-a20ce3379c66.png)

Hi,
Thanks for you point out this. And here are some pics that shows our data we store on the server, the videos in the netbook are just a few samples that we take out to show. After all, these large volumes of data are also more difficult to store on the web.
![4B604E5D-3B53-490A-8D87-7DDC697ACCB6](https://user-images.githubusercontent.com/116698391/207530292-567bbd17-c972-418d-824e-0bbaed5f5bfe.png)
![4C837BE0-F6C2-4E78-BDDD-C316C24B7AAA](https://user-images.githubusercontent.com/116698391/207530299-fe1d373f-08f3-4492-8092-328e58b931ce.png)

**Comment by SiGe-Technology** [comment]
> Any updates?
> 
> About KYC&KYB 1：Could you send an email to [filplus-app-review@fil.org](mailto:filplus-app-review@fil.org) ？
> 
> The content should include the number of the LDN application. If possible, please attach copies of the business license and other valid certificates
> 
> 2：Can you provide more detailed information about other storage providers participated in this program, such as you can list SPs you have contacted with at present? 3. How large is your existing dataset? How much is the data growth per month?

Hi,
We apologize for not updating the new data news recently, our colleague has Covid infection and has a high fever for several days. Thx for your understanding!

1. We’ve just sent the email with business license and our application number.

2. Our initial plan is to find ten sps and distribute the acquired data evenly, after which the planned distribution of DCs will be in accordance with the differences in packaging speed and size of each sp to make certain changes. 
We are now more sure to cooperate with the following nodes: 
f0432773 
f01170291 
f01032989
f01213126
f01384113
f01270657
f01198966
and our company had cooperation with Interstellar
 Storage (Shenzhen), and will also continue to communicate with them in this regard

3. As the picture in the reply above shows, our company's database storage is about to reach the PB level. And we receive a lot of video data every day, so the data will grow around 30T to 50T every month.

**Comment by SiGe-Technology** [comment]
![image](https://user-images.githubusercontent.com/116698391/208813662-c0b28f6e-ea25-444e-9c10-71e3903c30fe.png)

**Comment by 1ane-1** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceba6vyco2xbumrdovtxuw4xt6crrsfdjghaif5ji4tmu7yfsamste 
#### Address 
> f1kh7vqg4dcdtkwugc5wgd4vuitixiy7e6ugnalmy
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1mdk7s2vntzm6hu35yuo6vjubtrpfnb2awhgvrri
#### Id
> df8e0066-162e-48ab-9689-0bfdd98d8368
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceba6vyco2xbumrdovtxuw4xt6crrsfdjghaif5ji4tmu7yfsamste

**Comment by newwebgroup** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacea3i5kkcfpccornowp5g7akhig2v7d45t7yce5vvxahwcoje5p3ti 
#### Address 
> f1kh7vqg4dcdtkwugc5wgd4vuitixiy7e6ugnalmy
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1e77zuityhvvw6u2t6tb5qlnsegy2s67qs4lbbbq
#### Id
> df8e0066-162e-48ab-9689-0bfdd98d8368
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacea3i5kkcfpccornowp5g7akhig2v7d45t7yce5vvxahwcoje5p3ti

**Comment by cryptowhizzard** [comment]
Hi,

From here -> https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1306#issuecomment-1350523023

It indicates you need 22 TB of datacap to store this photo's. When you replicate those to 10 providers it gives 220 TiB of needed datacap.

@newwebgroup why did you approve this request to be 5 PiB that is around 20 times the amount of data this client needs?

**Comment by SiGe-Technology** [comment]
> Hi,
> 
> From here -> [#1306 (comment)](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1306#issuecomment-1350523023)
> 
> It indicates you need 22 TB of datacap to store this photo's. When you replicate those to 10 providers it gives 220 TiB of needed datacap.
> 
> @newwebgroup why did you approve this request to be 5 PiB that is around 20 times the amount of data this client needs? @1ane-1 same question?

Hello, thank you very much for your question.
Regarding the above 22T storage image, this image just shows the data stored on one of our servers. Since our company needs to record a lot of videos and pictures every day and this amount will continue to grow afterwards, our company now has almost ten storage servers. This is the reason why we need such a large storage capacity of 5 PiB.

**Comment by SiGe-Technology** [comment]
Hello [cryptowhizzard](https://github.com/cryptowhizzard), thank you very much for your question.
Regarding the above 22T storage image, this image just shows the data stored on one of our servers. Since our company needs to record a lot of videos and pictures every day and this amount will continue to grow afterwards, our company now has almost ten storage servers. This is the reason why we need such a large storage capacity of 5 PiB.

**Comment by herrehesse** [comment]
Dear Applicant,

Due to the increased amount of erroneous/wrong Filecoin+ data recently, on behalf of the entire community, we feel compelled to go deeper into datacap requests. Hereby to ensure that the overall value of the Filecoin network and Filecoin+ program increases and is not abused.

Please answer the questions below as comprehensively as possible.

**Customer data**

- Could you demonstrate exactly how and to what extent customer contact occurred? 

We expect that for the onboarding of customers with the scale of an LDN there would have been at least multiple email and perhaps several chat conversations preceding it. A single email with an agreement does not qualify here.

- Did the customer specify the amount of data involved in this relevant correspondence?

- Why does the customer in question want to use the Filecoin+ program? 

_Should this only be soley for acquiring datacap this is of course **out of the question**. The customer must have a legitimate reason for wanting to use the Filecoin+ program which is intended as a program to store useful and public datasets on the network._ 

- Why is the customer data considered Filecoin+ eligible?

_(As an intermediate solution Filecoin offers the FIL-E program or the glif.io website for business datasets that do not meet the requirements for a Filecoin+ dataset)_


**Files and Processing**

- Could you please demonstrate to us how you envision processing and transporting the customer data in question to any location for preparation?
- Would you demonstrate to us that the customer, the preparer and the intended storage providers all have adequate bandwidth to process the set with its corresponding size?
- Would you tell us how the data set preparer takes into account the prevention of duplicates in order to prevent data cap abuse?


Hopefully you understand the caution the overall community has for onboarding the wrong data. We understand the increased need for Filecoin+, however, we must not allow the program to be misused. Everything depends on a valuable and useful network, let's do our best to make this happen. Together.

**Comment by SiGe-Technology** [comment]
> Dear Applicant,
> 
> Due to the increased amount of erroneous/wrong Filecoin+ data recently, on behalf of the entire community, we feel compelled to go deeper into datacap requests. Hereby to ensure that the overall value of the Filecoin network and Filecoin+ program increases and is not abused.
> 
> Please answer the questions below as comprehensively as possible.
> 
> **Customer data**
> 
> * Could you demonstrate exactly how and to what extent customer contact occurred?
> 
> We expect that for the onboarding of customers with the scale of an LDN there would have been at least multiple email and perhaps several chat conversations preceding it. A single email with an agreement does not qualify here.
> 
> * Did the customer specify the amount of data involved in this relevant correspondence?
> * Why does the customer in question want to use the Filecoin+ program?
> 
> _Should this only be soley for acquiring datacap this is of course **out of the question**. The customer must have a legitimate reason for wanting to use the Filecoin+ program which is intended as a program to store useful and public datasets on the network._
> 
> * Why is the customer data considered Filecoin+ eligible?
> 
> _(As an intermediate solution Filecoin offers the FIL-E program or the glif.io website for business datasets that do not meet the requirements for a Filecoin+ dataset)_
> 
> **Files and Processing**
> 
> * Could you please demonstrate to us how you envision processing and transporting the customer data in question to any location for preparation?
> * Would you demonstrate to us that the customer, the preparer and the intended storage providers all have adequate bandwidth to process the set with its corresponding size?
> * Would you tell us how the data set preparer takes into account the prevention of duplicates in order to prevent data cap abuse?
> 
> Hopefully you understand the caution the overall community has for onboarding the wrong data. We understand the increased need for Filecoin+, however, we must not allow the program to be misused. Everything depends on a valuable and useful network, let's do our best to make this happen. Together.

Hi, @[herrehesse](https://github.com/herrehesse) sorry for reply this so late. 
We totaly understand that your consideratin of erroneous/wrong Filecoin+ data in the community, and we are glad to answer your question.

As the applicant, I am the customer. With this in mind, I will answer all questions in two parts, Customer data and Files and Processing, according to our situation.

**Customer data**

The SPs in the marketplace approached us saying to go to storage in a safer and cheaper way. So we're making a line of credit application. After that we started to learn about the FIL+ program and its very high security. Our company's development direction is also web3, and we know the value and necessity of data.

We as a customer don't care what way we do the application. Our paths are guided by the SPs that find us.
Our business has been in operation for ten years. There is definitely more valuable data in ten years than what I've shown, and I'm sure you can understand the volume of data that an R&D and service business can generate in ten years.

As the data owner, we can ensure that the data is publicly available. Data that is not publicly retrievable we do not have in our storage plan.
Nodes like the ones I mentioned earlier at https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1306#issuecomment-1350593419 are ones we are trying to actively engage with, and while we can't guarantee that we would work together, but we guarantee that we will follow the rules of fil+ and find 4+ SPs to work with.

**Files and Processing**

Like I said before, our business has been in operation for ten years. The volume of valuable data is also very substantial. And, we serve dozens of large, well-known companies. We have archived the publicly available data generated in the past for local download. The backed up data would sent to different SPs in the form of hard disks (these costs are borne by the SPs). Other transfer methods will be improvised.

The choice of we seletc SPs will of course also take into account their situation such as size and the speed of allocate data.
The data we currently have ready is backed up according to the SPs in different regions. The number of backups is controlled by our company as the client and will not exceed ten.

Really appreciate your due diligence, and this brings us greater confidence in the transparency and security of the program.

**Comment by kevzak** [comment]
@herrehesse based on the application information, this is a public data application.

E-Fil+ is a program for Private Data owners. Please let me know if you need more background before promoting the program incorrectly. Thank you.

**Comment by Irmagogo** [comment]
checker:manualTrigger

**Comment by cryptowhizzard** [comment]
Good morning,

It seems we can stop this before we even started. CID sharing observed with some fraudulent applications.
Nothing of the data is retrievable.

ERROR: offer error: retrieval query offer errored: failed to fetch piece to retrieve from: getting pieces for cid bafykbzaceawo2eq2dwcamgrmzo54u3o3law3k23rtalbiuicgdtsut275bqtu: getting pieces containing block bafykbzaceawo2eq2dwcamgrmzo54u3o3law3k23rtalbiuicgdtsut275bqtu: failed to lookup index for mh a0e402202ced121a1d84061a2ccbbbca6ddb582db56b71981614510230e72a4f5fe8613a, err: datastore: key not found

ERROR: offer error: retrieval query offer errored: failed to fetch piece to retrieve from: getting pieces for cid bafykbzaceawo2eq2dwcamgrmzo54u3o3law3k23rtalbiuicgdtsut275bqtu: getting pieces containing block bafykbzaceawo2eq2dwcamgrmzo54u3o3law3k23rtalbiuicgdtsut275bqtu: failed to lookup index for mh a0e402202ced121a1d84061a2ccbbbca6ddb582db56b71981614510230e72a4f5fe8613a, err: datastore: key not found

ERROR: offer error: retrieval query offer errored: failed to fetch piece to retrieve from: getting pieces for cid bafykbzacedayasv72h4nh3jjm5p633v2gshnwamvjuhcuhosygigo2o2ut4hw: getting pieces containing block bafykbzacedayasv72h4nh3jjm5p633v2gshnwamvjuhcuhosygigo2o2ut4hw: failed to lookup index for mh a0e40220c1804abfd1f8d3ed29675fedeeba348edb01954d0e2a1dd2c1906769daa4f87b, err: datastore: key not found

ERROR: offer error: retrieval query offer errored: failed to fetch piece to retrieve from: getting pieces for cid bafykbzacecqfsh2nac5pbcnskiarzma2rseajtopqm76f47i3hd2mubenqwu6: getting pieces containing block bafykbzacecqfsh2nac5pbcnskiarzma2rseajtopqm76f47i3hd2mubenqwu6: failed to lookup index for mh a0e40220a0591f4d00baf089b252011cb01a8c8804cdcf833fe2f3e8d9c7a650246c2d4f, err: datastore: key not found

ERROR: offer error: retrieval query offer errored: failed to fetch piece to retrieve from: getting pieces for cid bafykbzaceb4nbitgt6ujnhnlq5qe74ihd52szsc3i2zeyaztlmrfhvgzvhyfe: getting pieces containing block bafykbzaceb4nbitgt6ujnhnlq5qe74ihd52szsc3i2zeyaztlmrfhvgzvhyfe: failed to lookup index for mh a0e4022078d0a2669fa8969dab87604ff1071f752cc85b46b24c03335b2253d4d9a9f052, err: datastore: key not found

ERROR: offer error: retrieval query offer errored: failed to fetch piece to retrieve from: getting pieces for cid bafykbzacec4onybu7pwgxmznwdzrgfrhjhds5bmhautim4pxsw2t4txzaqozk: getting pieces containing block bafykbzacec4onybu7pwgxmznwdzrgfrhjhds5bmhautim4pxsw2t4txzaqozk: failed to lookup index for mh a0e40220b8e6e034fbec6bb32db0f313162749c72e858705268671f795b53e4ef9041d95, err: datastore: key not found

ERROR: offer error: retrieval query offer errored: failed to fetch piece to retrieve from: getting pieces for cid bafykbzacec3sl7szfvoyvhl3b2e6ot36m24lodrpddrg4xt7ri57u2g2x2f2k: getting pieces containing block bafykbzacec3sl7szfvoyvhl3b2e6ot36m24lodrpddrg4xt7ri57u2g2x2f2k: failed to lookup index for mh a0e40220b725fe592d5d8a9d7b0e89e74f7e66b8b70e2f18e26e5e7f8a3bfa68dabe8ba5, err: datastore: key not found

ERROR: offer error: retrieval query offer errored: failed to fetch piece to retrieve from: getting pieces for cid bafykbzacec3sl7szfvoyvhl3b2e6ot36m24lodrpddrg4xt7ri57u2g2x2f2k: getting pieces containing block bafykbzacec3sl7szfvoyvhl3b2e6ot36m24lodrpddrg4xt7ri57u2g2x2f2k: failed to lookup index for mh a0e40220b725fe592d5d8a9d7b0e89e74f7e66b8b70e2f18e26e5e7f8a3bfa68dabe8ba5, err: datastore: key not found
