### ISSUE TITLE
[DataCap Application]  ZKLink

### ISSUE THREAD

**Issue by ZKLink2022** [filecoin-project/filecoin-plus-large-datasets#1307]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: ZKLink
- Website / Social Media: Website: https://zk.link/ Twitter：https://twitter.com/zkLinkorg Discord:https://discord.com/invite/9GCwxN7xaJ Telegram：https://t.me/zkLinkorg
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5 PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100TiB
- On-chain address for first allocation: f1j33ixbfuht4xszjgxdg4uti3vhmv6ntsmlmfnqy
_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
zkLink is an ultra secure, chain-to-chain interoperability protocol powered by zero-knowledge technology. As a ”connector” among diverse ecosystems, zkLink cooperates with various public chains and Layer2 protocols to provide a more convenient and secure chain-to-chain trading environment, contributing to a more accessible and efficient DeFi ecosystem for everyone. Furthermore, we are engaging in NFT marketplace. And we have built a platform for cross-chain transactions and already have nearly 100 thousands fans in social media and community. Our blog publishes news about blockchain and followers are allowed to post their content in free. We serve not only individuals, but also toB. 
```

What is the primary source of funding for this project?
```
Shareholder’s investment
```

What other projects/ecosystem stakeholders is this project associated with?
```
We are cooperate with various public chains and Layer2 protocols
```

## Use-case details

Describe the data being stored onto Filecoin
```
Blockchain news, videos and docs. Transaction data, social media information
```

Where was the data in this dataset sourced from?
```
Huge amount of images, videos and docs from blog.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://drive.google.com/file/d/1FxhPW2ye1_-gx5wkYZ9Zj0aOGC2PqZ_V/view?usp=share_link
https://drive.google.com/file/d/1oit2oySVOfYOODhN33VfLODUPbnajQr_/view?usp=share_link
https://drive.google.com/file/d/1MDtNnYnqZtfvoqmcBejLzA_WygS3vgsm/view?usp=share_link
https://drive.google.com/file/d/1-0EpcRcyt34ZGFVx47u_akILIT9cQd52/view?usp=share_link
https://drive.google.com/file/d/1QYEP9zvB79KQoaR_76QfVIjtzxG_2s_-/view?usp=share_link
https://drive.google.com/file/d/1uqwju1tqYvLmdUHTENHX4ia7oYjK1prN/view?usp=share_link
https://drive.google.com/file/d/12g0hvHTTew8i1IYxIpII3hK41GulEgMk/view?usp=share_link
https://drive.google.com/file/d/1CDD75auJp5ogOMflUuOgKaCwNXRCufTK/view?usp=share_link
https://drive.google.com/file/d/1N5ZgIgJJ4GYFp3OQ-wHP78J6Pge-5z7V/view?usp=share_link
https://drive.google.com/file/d/1qsfeOSa12XiTucGxmAg_YvCqeu6rddxw/view?usp=share_link
https://drive.google.com/file/d/1SE5SZDLn0KtDA6aZqbXn1mwSCDsFjrHW/view?usp=share_link
https://drive.google.com/file/d/1p_xSA4Do9P-WnH-SYlOuY742YCI8k5I2/view?usp=share_link
https://drive.google.com/file/d/1SHk22Ecy1N08jjXCxHRX672OTDKEd3Rz/view?usp=share_link
https://drive.google.com/file/d/1XfZqn_fnhsWZwGJUr2swhM9zmbyalqkW/view?usp=share_link
https://drive.google.com/file/d/1sw6sYTL0fcofz8hVHY53sv-mfmZBpmEA/view?usp=share_link
https://drive.google.com/file/d/1b4yyng3nY6pLmveHwabj5ihrWEJlAD-p/view?usp=share_link
https://drive.google.com/file/d/1lkYYVF7kTBKyF-pppoNkDIzNDZWk2jj1/view?usp=share_link
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes, of course. 
```

What is the expected retrieval frequency for this data?
```
No exactly frequency.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
It is useful for us. So is better to store permanently.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Any acceptable regions.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Online transfer is better.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
Base on provider’s capacity, reputation and performance. 
```

How will you be distributing deals across storage providers?
```
It mainly depends on storage provider’s willing.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
We have enough funding to support this project. 
Also, Filecoin is the platform that we are looking for. maybe we can have further cooperation in the future. 
```

**Comment by ZKLink2022** [comment]
Hello, @raghavrmadya @Kevin-FF-USA  @galen-mcandrew 
Since our previous application account was flagged and the previous multisig address was not f01858410, we created a new issue here and replaced the new f1 address.

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 100TiB

**Client address**

> f1i2igpiu5nlmcjbo2tyrcd5w7kdgtlgif2bb6vka

**Comment by Defil2022** [comment]
@ZKLink2022 Have you sent KYC email to confirm your identity?

**Comment by ZKLink2022** [comment]
hello, @Defil2022 @galen-mcandrew @raghavrmadya  @Kevin-FF-USA 
I have sent kyc mail, please check it
thanks！
![1bf04868e37af90acc0afe173ede35f](https://user-images.githubusercontent.com/116628409/208051199-a245faef-547f-4344-9086-a1e550fcfbc7.jpg)

**Comment by ipfscn** [comment]
the previous account was flagged, it shows that the customer's KYB has been carefully screened, and I am willing to support them

**Comment by liyunzhi-666** [comment]
hey @ZKLink2022 
Can you provide more detailed information about other storage providers participated in this program, such as you can list SPs you have contacted with at present?

**Comment by ZKLink2022** [comment]
Hey @liyunzhi-666   Thanks for you ask. 
We have contacted following sps: 
f01773206, f01880364, f01850141, f01384160, f01834253, f01853077,f01890456, etc.

**Comment by ZKLink2022** [comment]
Also @simonkim0515 Do you mind check it out what's the meaning of our form's label?

**Comment by cryptowhizzard** [comment]
Hi @ZKLink2022 

The reason for doing the form / KYC is that we screen for the SP's if they have a standing reputation.

f01773206 involved in abuse / CID sharing
f01880364 involved in abuse / CID sharing 
f01850141 OK
f01384160 involved in abuse / CID sharing
f01834253 involved in abuse / CID sharing 
f01853077 involved in abuse / CID sharing 
f01890456 involved in abuse  /CID sharing 

With these SP's i will not sign a DC requests. I recommend searching SP's with a good reputation.

**Comment by ZKLink2022** [comment]
@CryptoWhizzard 

Hello sorry for the late reply. 
Thanks for your reminder, We will still search for SP with a good reputation. Please follow up on our data onboarding status. Appreciate it if you could feedback after the first allocation. Those miners we've contacted before we have made an agreement. It's unrealistic for us to default now.. However, we will keep our eyes on the storage process and make sure there will no wrong things happen. Thank you.


| |
wcogz60
|
|
***@***.***
|
---- Replied Message ----
| From | ***@***.***> |
| Date | 2/14/2023 18:35 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [filecoin-project/filecoin-plus-large-datasets] [DataCap Application] ZKLink (Issue #1307) |

Hi @ZKLink2022

The reason for doing the form / KYC is that we screen for the SP's if they have a standing reputation.

f01773206 involved in abuse / CID sharing
f01880364 involved in abuse / CID sharing
f01850141 OK
f01384160 involved in abuse / CID sharing
f01834253 involved in abuse / CID sharing
f01853077 involved in abuse / CID sharing
f01890456 involved in abuse /CID sharing

With these SP's i will not sign a DC requests. I recommend searching SP's with a good reputation.

**Comment by Zhangcffff** [comment]
Found another interesting thing~
Hopefully you can look for some reputable SP's, as @cryptowhizzard said.
Also, hope you can provide some samples that will be stored for my next round of review.
I'd love to help you out if I can!

**Comment by ZKLink2022** [comment]
@Zhangcffff First of all, thank you for your attention, and I appreciate your willingness to support me.
Each notary should have his own criteria for judging. I can say that any SP is not trusted by me, but it doesn't mean that as long as one person says it's bad, it's really bad. What do you think?
Is there a leader among the notaries?
I said that we will arrange special personnel to follow up the packaging situation in real time. As a client, I have tried my best. Hope you understand.
In addition, "reputable" sp we are communicating with: f01896036/f02013434/f01479781/f01543586. Don't know if you think these can be trusted? However, since we are communicating now, it will take time to send the data to these sps, so they may not be able to provide services in early rounds of allocation.
In addition, please see the sample data here: 
https://drive.google.com/file/d/12g0hvHTTew8i1IYxIpII3hK41GulEgMk/view?usp=share_link
https://drive.google.com/file/d/1CDD75auJp5ogOMflUuOgKaCwNXRCufTK/view?usp=share_link
https://drive.google.com/file/d/1N5ZgIgJJ4GYFp3OQ-wHP78J6Pge-5z7V/view?usp=share_link
https://drive.google.com/file/d/1qsfeOSa12XiTucGxmAg_YvCqeu6rddxw/view?usp=share_link
https://drive.google.com/file/d/1SE5SZDLn0KtDA6aZqbXn1mwSCDsFjrHW/view?usp=share_link
https://drive.google.com/file/d/1p_xSA4Do9P-WnH-SYlOuY742YCI8k5I2/view?usp=share_link
https://drive.google.com/file/d/1SHk22Ecy1N08jjXCxHRX672OTDKEd3Rz/view?usp=share_link
Thank you.

**Comment by Zhangcffff** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedzow72z427fxutl2ymfbwyzkxwkqu5fiuq2dgcrx2yzpnfj2yjpo 
#### Address 
> f1i2igpiu5nlmcjbo2tyrcd5w7kdgtlgif2bb6vka
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f122qmy25wdtt5mxd77kndiq7z5x2n3iwiuz2wdsa
#### Id
> 64293946-38d5-4ca2-a166-a8fac6680da5
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedzow72z427fxutl2ymfbwyzkxwkqu5fiuq2dgcrx2yzpnfj2yjpo

**Comment by Tom-OriginStorage** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecfeywpxfrl5t4rujljoenwkbijornktlxts62kmt6sfqojjp7obg 
#### Address 
> f1i2igpiu5nlmcjbo2tyrcd5w7kdgtlgif2bb6vka
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1q6bpjlqia6iemqbrdaxr2uehrhpvoju3qh4lpga
#### Id
> 64293946-38d5-4ca2-a166-a8fac6680da5
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecfeywpxfrl5t4rujljoenwkbijornktlxts62kmt6sfqojjp7obg

**Comment by ZKLink2022** [comment]
@Simon Kim Hi 

The address f1i2igpiu5nlmcjbo2tyrcd5w7kdgtlgif2bb6vka does not belong to us. May I ask if you triggered the wrong address?
My address should be f1j33ixbfuht4xszjgxdg4uti3vhmv6ntsmlmfnqy


| |
wcogz60
|
|
***@***.***
|
---- Replied Message ----
| From | Simon ***@***.***> |
| Date | 11/30/2022 00:50 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [filecoin-project/filecoin-plus-large-datasets] [DataCap Application] ZKLink (Issue #1307) |

Datacap Request Trigger

Total DataCap requested

5PiB

Expected weekly DataCap usage rate

100TiB

Client address

f1i2igpiu5nlmcjbo2tyrcd5w7kdgtlgif2bb6vka

**Comment by ZKLink2022** [comment]
Hi  @Simon Kim 
The address f1i2igpiu5nlmcjbo2tyrcd5w7kdgtlgif2bb6vka does not belong to us. May I ask if you triggered the wrong address?
My address should be f1j33ixbfuht4xszjgxdg4uti3vhmv6ntsmlmfnqy
