### ISSUE TITLE
[DataCap Application] Qianyuan Yunshuo Technology (Shenzhen) Co., Ltd.

### ISSUE THREAD

**Issue by uicn1iu1** [filecoin-project/filecoin-plus-large-datasets#1308]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Qianyuan Yunshuo Technology (Shenzhen) Co., Ltd.
- Website / Social Media:www.ipfsqy.com
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):4PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):100TiB
- On-chain address for first allocation:f1dcjn2qk4jsnjfdaavsdle5ydkufuxws767zarfi

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Qianyuan Yunshuo Technology (Shenzhen) Co., Ltd. is a comprehensive service provider based on distributed storage software research and development and QianYuan cloud technology as the core, dedicated to providing users with big data storage business, BaaS solutions and technical services. It provides stable, efficient, intelligent and controllable distributed storage product lines and solutions around big data storage technology, and can provide innovative and efficient storage and blockchain solutions for users' big data storage. We can provide innovative and efficient storage solutions for users' big data storage and overall solutions for blockchain technology applications.
```

What is the primary source of funding for this project?
```
Own enterprise funds.
```

What other projects/ecosystem stakeholders is this project associated with?
```
No
```

## Use-case details

Describe the data being stored onto Filecoin
```
We store data generated by our company on the Filecoin network:
The company's precious data: the company's patents, the company's PPT
The company's business data: product introductions, promotional posters, presentation videos, the content of the company's participation in industry conferences, and the content of receiving customers
Other data: IDC computer room operation/maintenance, content purchased by the company, etc.

```

Where was the data in this dataset sourced from?
```
From our company and the business that our company conducts.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
(https://drive.google.com/drive/folders/1ols3j3pk4-dKj6Wvo0YtylbCvZG30sDx?usp=share_link)
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes，We confirm
```

What is the expected retrieval frequency for this data?
```
Frequent searches are not required, about 1-2 times a year.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
Most of data is required to stored permanently，We will store for 2-3 years.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
As long as the data can be stored securely, we do not limit the area where it is stored.
However, no matter which region is stored, we hope that SP can cover the postage, and it is best if it can also cover the cost of the hard disk.

```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
We plan to transfer data offline 
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We are selecting SPs with high reputation on slack and filfox who have the ability to store transactions very fast and with a high success rate.
When we choose an SP, we will consider their area, whether they can be retrieved, and how many backups they intend to make. We think it is more appropriate to do 3-5 backups.

```

How will you be distributing deals across storage providers?
```
We plan to find more than 5 SPs and distribute the deals equally.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
We are ready for the funds. In the future, if I have any questions, I will seek the help of officials and other technicians through slack .
```

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 4PiB

**Expected weekly DataCap usage rate**

> 100TiB

**Client address**

>f1dcjn2qk4jsnjfdaavsdle5ydkufuxws767zarfi

**Comment by uicn1iu1** [comment]
https://drive.google.com/drive/folders/1utPKmjeTPQwYP7_48AW9DLEcmF3bwaTY，This is part of our node monitoring, operations and maintenance logs

**Comment by stcouldlisa** [comment]
Can you email filplus-app-review@fil.org using your official domain name to confirm your identity?
Email name should contain Issue ID #1308

**Comment by stcouldlisa** [comment]
Which SPs have you contacted，do you need support from the community

**Comment by uicn1iu1** [comment]
![1670828559647](https://user-images.githubusercontent.com/99867495/206981755-303687b8-fcb3-4ccf-ab5a-8acc4c418e6f.jpg)

**Comment by uicn1iu1** [comment]
@stcouldlisa Thank you for your question, I am the person in charge of qianyuan Yunshuo, I just sent an email, please check.
We contacted many SPs on slack and filgram. In addition, we checked the qualifications of  SPs on filrep. We contacted more than 30 SPs, and after screening, we left 6 SPs. At the same time, we are still Find more premium SP:
f0119336
f01694564
f01482290
f0723722
f0840770
f01602479

**Comment by stcouldlisa** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec2xhcf4ldbrt2p4qoqnfkabpphh5tu5wmchnmy5xjztwmo4xam42 
#### Address 
> f1dcjn2qk4jsnjfdaavsdle5ydkufuxws767zarfi
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1jvvltduw35u6inn5tr4nfualyd42bh3vjtylgci
#### Id
> def706b5-cc87-4dea-93ba-f701f170f298
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec2xhcf4ldbrt2p4qoqnfkabpphh5tu5wmchnmy5xjztwmo4xam42

**Comment by Tom-OriginStorage** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaj6dbxj7nbvxp3eoltlzu73ghadkghcirixgrdhflmq3evdbsyps 
#### Address 
> f1dcjn2qk4jsnjfdaavsdle5ydkufuxws767zarfi
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1q6bpjlqia6iemqbrdaxr2uehrhpvoju3qh4lpga
#### Id
> def706b5-cc87-4dea-93ba-f701f170f298
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaj6dbxj7nbvxp3eoltlzu73ghadkghcirixgrdhflmq3evdbsyps

**Comment by stcouldlisa** [comment]
According to the feedback from the community, the sp you provided does not support retrieval, please provide the SP again.

The SP you finally cooperate with must support retrieval, otherwise it will be difficult for you to regain trust.

**Comment by psh0691** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebzy2il5gkg2ojir3u66c4voqw5c4b67ak4tan7f5hj4ohnpm3xjq 
#### Address 
> f1dcjn2qk4jsnjfdaavsdle5ydkufuxws767zarfi
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1qdko4jg25vo35qmyvcrw4ak4fmuu3f5rif2kc7i
#### Id
> f7726a82-c5c3-45f9-96a0-396f46ef277e
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebzy2il5gkg2ojir3u66c4voqw5c4b67ak4tan7f5hj4ohnpm3xjq

**Comment by kernelogic** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedqp6nexcfx5mvkdknscl4d2otkmu5wcddnh27rn3wdeq3u2kxols 
#### Address 
> f1dcjn2qk4jsnjfdaavsdle5ydkufuxws767zarfi
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### Id
> f7726a82-c5c3-45f9-96a0-396f46ef277e
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedqp6nexcfx5mvkdknscl4d2otkmu5wcddnh27rn3wdeq3u2kxols

**Comment by kernelogic** [comment]
I was able to retrieve a good chunk of the data in a reasonable speed. Will provide the full retrieval cmd later.

<img width="727" alt="image" src="https://user-images.githubusercontent.com/3711825/219311838-53c0e262-1e9f-4d16-a335-1f7f9785779f.png">

**Comment by psh0691** [comment]
file:///root/%EC%82%AC%EC%A7%84/img_4659.jpg

**Comment by psh0691** [comment]
![img_4659](https://user-images.githubusercontent.com/69004801/219317125-2d82c26d-c9a8-46f8-806c-75ced29b5640.jpg)

**Comment by kernelogic** [comment]
To continue the above DD, I was able to finish retrieve the whole sector and extract out a few MP4 videos. They seems inline with what's being described to store.

<img width="1031" alt="image" src="https://user-images.githubusercontent.com/3711825/219528618-dbc2e5c7-9b05-46e3-b1c7-edb7795e2701.png">


<img width="769" alt="image" src="https://user-images.githubusercontent.com/3711825/219528389-fc1db1af-101a-43b6-988f-6204fe6c4dcd.png">
<img width="1454" alt="image" src="https://user-images.githubusercontent.com/3711825/219528505-991191c9-4a54-47d4-ac20-ad7763b5497f.png">

**Comment by cryptowhizzard** [comment]
Hi,

I would like to sign but it seems these are only 2 organisations ( at most ).


![Scherm­afbeelding 2023-02-17 om 11 56 37](https://user-images.githubusercontent.com/36404435/219629297-6313c2ab-e261-4f83-8958-fcc45a03a108.png)


@uicn1iu1 can you perform KYC and data onboard plan please [here](https://form.jotform.com/230337462961356)

I would like to know where you are going to store the next trance of data.

**Comment by uicn1iu1** [comment]
It's a great honor, thank you pay attention us.

We plan to store data in three continents or even four continents. Next, our sp may be Chinese sp or American sp, or both will be added.

Please help us, we will not disappoint your trust, in the next round, you will be able to see sp from more regions

**Comment by cryptowhizzard** [comment]
> It's a great honor, thank you pay attention us.
> 
> We plan to store data in three continents or even four continents. Next, our sp may be Chinese sp or American sp, or both will be added.
> 
> Please help us, we will not disappoint your trust, in the next round, you will be able to see sp from more regions

It is a great honor to meet you to, however please fill out the KYC form and provide me with the SP's where you are going to store the next tranche of data.

**Comment by uicn1iu1** [comment]
Here we finally found the new sp, they are f01900687 and they are in the US.

I filled out your form, we will continue to contact more sp, please support us!

**Comment by cryptowhizzard** [comment]
Hi @uicn1iu1 

I am supporting you. If i would not be supportive i would not help you in the right direction!

I received your KYC data. f01900687 looks OK. There is still missing one organization, but i am willing to propose to give you a second chance.

**Comment by cryptowhizzard** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced3omjcermv74x3bcad7yl2iw5bxq2llaor7lsgmba5r2zicfzjya 
#### Address 
> f1dcjn2qk4jsnjfdaavsdle5ydkufuxws767zarfi
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1krmypm4uoxxf3g7okrwtrahlmpcph3y7rbqqgfa
#### Id
> 0ca07647-99ac-45e4-9628-857bf59849dc
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced3omjcermv74x3bcad7yl2iw5bxq2llaor7lsgmba5r2zicfzjya

**Comment by uicn1iu1** [comment]
Thank you for everyone's help, there is still one signature left, please help me from the enthusiastic notary, thank you!

**Comment by liyunzhi-666** [comment]
checker:manualTrigger

**Comment by liyunzhi-666** [comment]
It looks like the CID checker is fine and retrievable for me.
![6a7e3cda28fa9ab51eef8ec140e1286](https://user-images.githubusercontent.com/52949274/220541937-7a1afa96-2811-4da2-a5b0-1e19641f524e.png)
![de074afa7cbe2d80e2f1873e1a638d9](https://user-images.githubusercontent.com/52949274/220541961-2147b0b9-4413-41f5-a8d0-d461c656f000.png)

**Comment by liyunzhi-666** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced42sojifxkrlz54caohewv3f2rphts66hssifmpdpt2wsbdfa7ky 
#### Address 
> f1dcjn2qk4jsnjfdaavsdle5ydkufuxws767zarfi
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1pszcrsciyixyuxxukkvtazcokexbn54amf7gvoq
#### Id
> 0ca07647-99ac-45e4-9628-857bf59849dc
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced42sojifxkrlz54caohewv3f2rphts66hssifmpdpt2wsbdfa7ky

**Comment by kernelogic** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb4duq2yqj3iaebprmxpgtcsufxpmiq7nryzpiu3wk5jfxsrt7vmu 
#### Address 
> f1dcjn2qk4jsnjfdaavsdle5ydkufuxws767zarfi
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### Id
> 0ca07647-99ac-45e4-9628-857bf59849dc
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb4duq2yqj3iaebprmxpgtcsufxpmiq7nryzpiu3wk5jfxsrt7vmu

**Comment by NDLABS-OFFICE** [comment]
checker:manualTrigger

**Comment by NDLABS-OFFICE** [comment]
According to the review standard of ND, we are willing to carry out this round of support for you. The reason is that the status of the check bot is good, and we have tested the connectivity of the nodes to work normally.
The sp that provides storage is distributed in different places, and the backup is also good.

**Comment by NDLABS-OFFICE** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecovxdn7k2scpt5mmutjuzny5xi3uvas2f66mkmelzoh5kmdp62qw 
#### Address 
> f1dcjn2qk4jsnjfdaavsdle5ydkufuxws767zarfi
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1yayfsv6whu3rheviucvventj3y6t542xfpb47ei
#### Id
> 0ca07647-99ac-45e4-9628-857bf59849dc
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecovxdn7k2scpt5mmutjuzny5xi3uvas2f66mkmelzoh5kmdp62qw

**Comment by Joss-Hua** [comment]
![image](https://user-images.githubusercontent.com/75723122/223640975-ba2cb6ae-284b-415a-87f2-38803fd12a64.png)
<img width="978" alt="image" src="https://user-images.githubusercontent.com/75723122/223641598-8d9877d7-9140-4788-9b0e-3682a755cc62.png">

**Comment by Joss-Hua** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecplgfdcfwemrwnmmlsmlsfo7iwequyjgbhzc4rdyzsorxl3yzhqi 
#### Address 
> f1dcjn2qk4jsnjfdaavsdle5ydkufuxws767zarfi
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1tfg54zzscugttejv336vivknmsnzzmyudp3t7wi
#### Id
> 4691f53e-9818-4052-96a4-08b81afbff77
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecplgfdcfwemrwnmmlsmlsfo7iwequyjgbhzc4rdyzsorxl3yzhqi

**Comment by yuelinglong** [comment]
checker:manualTrigger

**Comment by uicn1iu1** [comment]
Since 410 has no DC, we are resting these days.
The cid incident in 1719 has nothing to do with us. Please be wise, rational, and fact-respecting notaries, officials, and community members to help us.

**Comment by psh0691** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceciyi2tn2rgwfnd63q3zrsifovwo2r5l7zy3grph7uael7gq7g67y 
#### Address 
> f1dcjn2qk4jsnjfdaavsdle5ydkufuxws767zarfi
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1qdko4jg25vo35qmyvcrw4ak4fmuu3f5rif2kc7i
#### Id
> d7ceea3b-eb53-4263-b28a-a087d679440f
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceciyi2tn2rgwfnd63q3zrsifovwo2r5l7zy3grph7uael7gq7g67y

**Comment by psh0691** [comment]
<img width="830" alt="WX20230317-135052@2x" src="https://user-images.githubusercontent.com/69004801/225823799-95d7f211-95d0-40e1-b8c3-f7ebd0fcf618.png">

**Comment by 1ane-1** [comment]
randomly retrieve check
![lQLPJx2kq-ovUWDNAhjNBFCwx7cCDfEidKEEDSTr2IAVAA_1104_536](https://user-images.githubusercontent.com/91301211/225823510-d3e64017-e809-419e-8d22-bdd518b80ea5.png)

**Comment by 1ane-1** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedximirru5epijuvco6rlqekh7rkkytgdkvqbf6b5oombx6vddcis 
#### Address 
> f1dcjn2qk4jsnjfdaavsdle5ydkufuxws767zarfi
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1mdk7s2vntzm6hu35yuo6vjubtrpfnb2awhgvrri
#### Id
> d7ceea3b-eb53-4263-b28a-a087d679440f
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedximirru5epijuvco6rlqekh7rkkytgdkvqbf6b5oombx6vddcis

**Comment by xiaoyuaiheshui** [comment]
checker:manualTrigger

**Comment by xiaoyuaiheshui** [comment]
The report does not look very healthy, CID sharing?

**Comment by uicn1iu1** [comment]
Hello, thank you for your attention to us, and the cid of 1719 is the fault of 1719 and sp. It happened during the period when v3 410 had no quota. We did not do anything, and the cid appeared.

The cid of 516 is only 1t. We are investigating the reason. If it is our reason, we can accept the termination of the sector.

**Comment by xiaoyuaiheshui** [comment]
I accept your explanation, and I will focus on CID sharing in the future

**Comment by xiaoyuaiheshui** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaacgrglvndb6kfmg4x42qaujdjth3ajjxwuei7hup74oahvxrt4s 
#### Address 
> f1dcjn2qk4jsnjfdaavsdle5ydkufuxws767zarfi
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f122qmy25wdtt5mxd77kndiq7z5x2n3iwiuz2wdsa
#### Id
> d7ceea3b-eb53-4263-b28a-a087d679440f
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaacgrglvndb6kfmg4x42qaujdjth3ajjxwuei7hup74oahvxrt4s

**Comment by newwebgroup** [comment]
1.CID sharing problem Need to continue to follow up the processing, although only 1T, but please check what is the cause of the Sharing

2. Since there is a CID sharing situation, we randomly select multiple SP's CIDs to check.
Multiple CIDs were randomly selected for retrieval testing through the Filecoin CID Checker website, and the test results showed that they all support retrieval.
https://filecoin.tools/f01992879

./lotus client retrieve --provider f02001485 bafykbzacedl4qqdz2gk5ueczocx75wrehofg7qjfbqj6yfiff564k7einy4ss .car
<img width="1263" alt="image" src="https://user-images.githubusercontent.com/100118145/226183738-212c8a71-4b91-4e71-8860-52a349742cda.png">


./lotus client retrieve --provider f01989013 uAXASIGGgcZba8Qn5r2pwJ1m1ezRaoM83ZAkzsuVl6NwFe3IQ .car
<img width="1242" alt="image" src="https://user-images.githubusercontent.com/100118145/226183747-08b236b7-b4e6-48a9-8203-f5e0c930f775.png">
<img width="1242" alt="image" src="https://user-images.githubusercontent.com/100118145/226184374-c51c570f-c51e-4015-b049-6863dece47d1.png">

./lotus client retrieve --provider f02062851 bafybeih3hvnqi5s6yeyzr6jksxtg5nyx4t6x2xdiz5wrczssrc6wzzhcre .car
<img width="1186" alt="image" src="https://user-images.githubusercontent.com/100118145/226185163-17bf8dbc-994a-4306-acf0-c107bc65997e.png">

**Comment by newwebgroup** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb6dsndlptphn4nxhrrdmo5thsmhblm6rvcf4thkwkj3z2amisepm 
#### Address 
> f1dcjn2qk4jsnjfdaavsdle5ydkufuxws767zarfi
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1e77zuityhvvw6u2t6tb5qlnsegy2s67qs4lbbbq
#### Id
> d7ceea3b-eb53-4263-b28a-a087d679440f
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb6dsndlptphn4nxhrrdmo5thsmhblm6rvcf4thkwkj3z2amisepm

**Comment by newwebgroup** [comment]
@uicn1iu1 CID Sharing is further expanded, please explain the exact reason!

⚠️ CID sharing has been observed. (Top 3) 

13.61 TiB - [f142gswwplxoeq6m7cyhia3uwfucj7tfc5aeyfjia](https://filfox.info/en/address/f142gswwplxoeq6m7cyhia3uwfucj7tfc5aeyfjia) - https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1035

**Comment by xiaoyuaiheshui** [comment]
@uicn1iu1  Please pause distribution first to identify CID sharing issues
