### ISSUE TITLE
[DataCap Application] FC Ventures

### ISSUE THREAD

**Issue by sugelandui** [filecoin-project/filecoin-plus-large-datasets#1310]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: FC Ventures
- Website / Social Media: https://fc-venture.com
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 200TiB
- On-chain address for first allocation: f14kdcmjvvg2ocuyaoggigo7q25hogj3mfyuu6mwi

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
FC Ventures helps blockchain projects with Asia community operation, brand upgrade, Asia media PR, services. We focus on blockchain infrastructure, financial technology and enterprise technology companies, and look to engage in a strategic relationship that may include joint product development, FC Ventures invests significant time and resources in our portfolio companies, providing relationships, and strategic network to accelerate value creation.provide diversified technical support services for different startup needs, including: Technical auditing, code analyzation, and decentralized derivative develop (game, fintech, wallet etc.) Startup comes with the idea, but also need other explored technical solutions to extend their business model.
FC Ventures builds community in several countries around Asia Publish related articles or news on top blockchain media Manage Professional meet up in numerous cities which highly developed in crypto Design related product for projects in order to create the culture of brand. Crypto market is totally different with traditional market; it is growing rapidly and changing significantly. FC Ventures always provide comments, give out best reliable suggestions for develop Crypto business, attract new comers and bring some ideas to negotiate with exchanges Also, provide crypto market or technical education for traditional company.
```

What is the primary source of funding for this project?
```
Company funds
```

What other projects/ecosystem stakeholders is this project associated with?
```
No.
```

## Use-case details

Describe the data being stored onto Filecoin
```
Business data of the invested subsidiaries, including educational videos, teaching materials, technical materials, public audit documents, etc
```

Where was the data in this dataset sourced from?
```
Our company's data.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://pan.baidu.com/s/1bLLJyjI53y1xiOk98OxZjA?pwd=7msy
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes, this is all public data, not secret, and anyone can retrieve it.
```

What is the expected retrieval frequency for this data?
```
3 times/year.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
We want to store it on the filecoin network all the time.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Priority storage in Europe.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Due to the large amount of data, we want to send data offline.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
To ensure the security of data, five storage providers will be selected, and the storage providers will be required to enable quick retrieval to facilitate the review of data integrity.
```

How will you be distributing deals across storage providers?
```
We plan to find more than 5 SPs and distribute the transactions equally.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, We have the funds. We know how to contact SP, and we don't need community help for the time being.
```

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Looking at your application i have some questions:
As you are brand new on Github and have no history of past applications it seems to me that applying for 5PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?

Can you show us visible proof of the size of your data and the storage systems you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230232885049356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!

**Comment by igoovo** [comment]
Thank you for contacting me.
I do the necessary due diligence and need you to support my work.
You can use your official domain name to [filplus-app-review@fil.org](mailto:filplus-app-review@fil.org) Send email and copy to [goovolvo@gmail.com](mailto:goovolvo@gmail.com) To confirm your identity? The email name should include question ID # 1310

Thanks!

**Comment by cryptowhizzard** [comment]
@igoovo 

New issues need to go through PL for verification.

------------

Per the https://github.com/filecoin-project/notary-governance/issues/922 for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

This information will be reviewed by Fil+ Governance team to confirm validity and then the application will be approved for notary review. Let us know if you have any questions.

**Comment by igoovo** [comment]
Ok, I will feed back the information to the customer and ask them to fill out the form.
Thank you for @cryptowhizzard !

**Comment by lupiruw** [comment]
ok?

**Comment by lupiruw** [comment]
ready
