### ISSUE TITLE
[DataCap Application] <Shenzhen Nanshan District Mali Quankai Technology Studio> - <Mali Quankai>

### ISSUE THREAD

**Issue by Maliquankai** [filecoin-project/filecoin-plus-large-datasets#1311]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Shenzhen Nanshan District Mali Quankai Technology Studio
- Website / Social Media: https://www.maliquankai.com/、Wechat Official account：force_code 
![image](https://user-images.githubusercontent.com/118967722/203737952-573d314b-3c95-4fa9-a2cb-265d409b4c32.png)
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 3PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 200TiB
- On-chain address for first allocation: f1ngbguhgklkpu3rggb4k3eqqflvx6e2oitqbbmei

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Mali Quankai Technology Studio in Nanshan District, Shenzhen pushes articles related to development, design and products from time to time, as well as works of independent developers, discussing technology, design, products, operation and everything about independent developers. At present, 11 apps have been developed. Its Code Force Full University Hall is a learning website for independent developers, including App courses, design courses and back-end courses.
```

What is the primary source of funding for this project?
```
The apps under the platform are all membership-based, and the main funds come from users rushing to members.
```

What other projects/ecosystem stakeholders is this project associated with?
```
NO other.
```

## Use-case details

Describe the data being stored onto Filecoin
```
**Rich resource pool data:** The company platform itself has rich resource pool for developers to use, with more than 20 resource types, including illustration materials, open source projects, tools, designs, courses and other material data.
**User data accumulation:** Data generated by users using the platform, such as engineering documents, graphic materials, audio and video, and personal works materials.
**Product app data:** There are 11 apps under the company, and there will be more in the future. The data generated by apps need to be stored.
```

Where was the data in this dataset sourced from?
```
This data set comes from the platform resource library, user usage data, user work data and data generated by its app, mainly audio and video, graphic data.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://design.maliquankai.com/
https://maliquankai.com/categories/%E8%AE%BE%E8%AE%A1%E8%B5%84%E6%BA%90/
https://maliquankai.com/categories/%E5%BC%80%E6%BA%90%E9%A1%B9%E7%9B%AE/
https://maliquankai.com/categories/%E5%B7%A5%E5%85%B7%E8%B5%84%E6%BA%90/
https://maliquankai.com/categories/%E4%B8%AA%E4%BA%BA%E4%BD%9C%E5%93%81/
https://maliquankai.com/categories/%E7%A8%8B%E5%BA%8F%E5%91%98%E8%81%8A%E8%AE%BE%E8%AE%A1/
https://maliquankai.com/categories/%E9%9A%8F%E7%AC%94/
https://maliquankai.com/categories/%E4%BC%98%E6%83%A0%E7%A6%8F%E5%88%A9/
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes, it is a public data.
```

What is the expected retrieval frequency for this data?
```
This data is used by users to learn after downloading, and the expected retrieval frequency is 3 times a year.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
We expect to store it for one year first, and then we need to observe the storage effect before making a decision.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Asian region.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
If in China, we will choose online transmission, Offline data will be stored on servers in China.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We will choose experienced and reliable storage providers.
```

How will you be distributing deals across storage providers?
```
We'll give the storage providers an even distribution ratio.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
We have our own product revenue, so we can afford to fund it, and the slack community is a great inspiration for us.
```

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 3PiB

**Expected weekly DataCap usage rate**

> 200TiB

**Client address**

> f1ngbguhgklkpu3rggb4k3eqqflvx6e2oitqbbmei
