### ISSUE TITLE
[DataCap Application] <Sichuan Fanmei Zhifei Tech> 

### ISSUE THREAD

**Issue by fanmei11** [filecoin-project/filecoin-plus-large-datasets#1312]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Sichuan FanMei Zhifei Technology Co., Ltd.
- Website / Social Media: http://www.scfmzf.cn/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):3.5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):200TiB
- On-chain address for first allocation: f3uixirlsuq3b2fiacjy3kvycfq4s35vkptln73ayfjd6iy5dq7bu2bcfiid4j4ofgdugcw7powf63df3b5rfa

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Sichuan Fanmei Zhifei Technology Co., Ltd. is an emerging technology company dedicated to UAV industry application services such as UAV driver license training, power grid inspection, formation flight performance, and event operation. Fanmei Zhifei has a professional UAV service team, including UAV driving instructors, power grid inspection pilots, and power grid data analysts, all of whom have obtained the civil unmanned pilot uniform issued by the Flight Standards Department of the Civil Aviation Administration of China. Aircraft system pilot license, and have excellent professional skills and rich project experience in their respective segments. Fanmei Zhifei is deeply involved in the field of drone related industries. It has education and training divisions, power grid divisions, formation divisions, and study tour divisions, which undertake drone driving training, power grid inspections, and drone formations respectively. Performance and aviation science education for young people, UAV competition operation and other businesses.
```

What is the primary source of funding for this project?
```
Benefits from projects.
```

What other projects/ecosystem stakeholders is this project associated with?
```
None.
```

## Use-case details

Describe the data being stored onto Filecoin
```
Pictures, videos and texts.
```

Where was the data in this dataset sourced from?
```
It comes from a large amount of video and photo data left by our business such as every flight show and competition, power inspection, etc., as well as a large amount of teaching and popular science data generated by our UAV Education and Training Division.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
UAV flight data: https://v.douyin.com/rVYobx3/
Power inspection data: http://www.scfmzf.cn/Power-inspection.html
Flight training data: http://www.scfmzf.cn/Training-registration.html
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes, it's public.
```

What is the expected retrieval frequency for this data?
```
We don't have specific retrieval requirements, it's just a long-term backup of company information. But maybe there will be one or two times a year.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
Long time storage.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Asia or some other regions.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
We hope to transmit online.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We plan to find as many reliable storage providers as possible through channels such as notary or slack. The storage provider must provide us with evidence to prove that he has stable and reliable equipment and operation and maintenance capabilities to ensure reliable storage of data.
```

How will you be distributing deals across storage providers?
```
We will first contact at least five storage providers, and then each will not allocate more than 20% of the total.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
We have prepared sufficient funds to start.
```

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 3.5PiB

**Expected weekly DataCap usage rate**

> 200TiB

**Client address**

> f3uixirlsuq3b2fiacjy3kvycfq4s35vkptln73ayfjd6iy5dq7bu2bcfiid4j4ofgdugcw7powf63df3b5rfa

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Looking at your application i have some questions:
As you are brand new on Github and have no history of past applications it seems to me that applying for 5PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?

Can you show us visible proof of the size of your data and the storage systems you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230337462961356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!
