### ISSUE TITLE
[DataCap Application] silu - Online education

### ISSUE THREAD

**Issue by 2748198** [filecoin-project/filecoin-plus-large-datasets#1313]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Hangzhou silu Technology Co., Ltd
- Website / Social Media: http://www.metayhc.com/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100TiB
- On-chain address for first allocation:  f1o7z3hrmxthl2yohnoabk2bmmveg6aoomatv52hq

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Under the normalization of epidemic situation, the field of remote office and online teaching has become a normal gradually. Many colleges and universities have gradually increased their efforts to establish their own open online teaching. This has brought two demands, the first one is the teaching platform facing the public network, which provides distance education services for students, teachers and adult educators. The second one is the copyright demand of teaching videos, which requires that teaching videos can be stored in block chains, so that teaching videos can be traced back and copyright can be traced.

Hangzhou silu Technology Co., Ltd. focuses on the research of resource media design and distributed storage of network teaching platform. It is currently doing remote video teaching services in Zhejiang Media University, Gannan Medical College, Zhejiang Shuren University, Shandong University of Finance and Economics, Zhejiang University of Mechatronics and other colleges. On the one hand, this project requires a lot of data storage services. Generally, a university produces data between 5-10 PiB a year, which requires a lot of data storage. On the other hand, we also look at filecoin's role in data security. Now the first phase of the project has come online, we have made a unified teaching platform to provide daily live teaching and course on demand services for schools.
```

What is the primary source of funding for this project?
```
This project mainly comes from two sources, one is provided by universities and our company in the near future, the other is from the use of paid services by students and educatees.
Subsequently, we will provide copyright registration services for these instructional videos.
```

What other projects/ecosystem stakeholders is this project associated with?
```
The project is related to the systems of adult education, remote tutoring and classroom assessment that our company intends to set up. Adult education projects can also serve as windows for social adult continuing education, and can use the resources of colleges and universities to carry out continuing education, the income comes from the course fees; Remote tutoring system can realize the interaction between teachers and students in remote teaching, remote tutoring students'homework, answering questions for students, and asking questions to teachers. Classroom assessment system is used for teaching evaluation among departments in charge of teaching, students and different educational institutions to promote teaching reform and mutual promotion of teaching and learning.
There are about 3,000 general higher education institutions in China, 15,000 vocational education institutions, and more than 500 million educatees (including school-age students, adult re-educators, autonomous learners and on-the-job trainers). This will be a huge market space.
The usage data, log data, teaching data, review data of these systems are very valuable archive data. On the one hand, this kind of data has a large amount of information and a large storage space requirement. More importantly, it puts forward a very high requirement for data storage security. Obviously filecoin thinks it's a very appropriate platform.
```

## Use-case details

Describe the data being stored onto Filecoin
```
There are mainly unstructured data such as video, audio and picture classes related to classroom teaching and structured table file data.
The usage data, log data, teaching data, and comment data of these systems are very precious archive data. On the one hand, this type of data has a large amount of information and a large demand for storage space, and more importantly, it puts forward very high requirements for data storage security. Obviously filecoin we think is a very suitable platform.
```

Where was the data in this dataset sourced from?
```
We offer online education services that include elementary, middle, high school, and university related courses. For example, courses such as mathematics, nature, science experiments, etc.
These data are recordings of excellent classroom lessons, voices, handout documents, and student interaction logs that have been saved from our daily classes.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
http://www.metayhc.com/ppt/show-91.html
http://www.metayhc.com/ppt/show-125.html
http://www.metayhc.com/ppt/show-203.html
http://www.metayhc.com/ppt/show-194.html
http://www.metayhc.com/ppt/show-195.html
http://www.metayhc.com/ppt/show-196.html
http://www.metayhc.com/ppt/show-199.html
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes. We confirm that these courses are public data.
```

What is the expected retrieval frequency for this data?
```
Our open source course data is backed up, and the retrieval frequency is retrieved according to customer needs
```

For how long do you plan to keep this dataset stored on Filecoin?
```
Hope that long-term storage, especially some file data, can be best stored permanently.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Mainly in China, Hong Kong, Macao and Taiwan, and foreign customers.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Offline orders are dominant
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We plan to select multiple storage vendors to store a single piece of data, while opening it up for other retrieval.
The detailed rules are as follows:
1 Has a wealth of filecoin storage experience, and can promise long-term storage.
2 Select at least 2 different regions with at least 4 or more SPs
3 The amount given to each SP does not exceed 25%
```

How will you be distributing deals across storage providers?
```
In the early stage, fair distribution transactions are conducted according to platform rules, and in the later stage, they are distributed according to storage provider services.
We plan to select 8 to 10 SP to distribute orders to them on average, and then evaluate and select 5 to 6 excellent SPs based on packaging efficiency, retrieval efficiency, and service quality, and send more orders to them later
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, we can make deals once we get datacap.  We have a technical team to track community dynamics enough to support making deals.
```

**Comment by 2748198** [comment]
@raghavrmadya This application is associated #301.  
Due to the change of company personnel, the GitHub account that applied for #301 was not available, so we changed the GitHub account and reapplied.

[LDN 301](https://drive.google.com/file/d/1oZSmEllz2LOLSwZLNnj-ZAwa1CZixl2c/view)

**Comment by 2748198** [comment]
@raghavrmadya @Kevin-FF-USA Request a review of our app, thank you very much!
 If you have any questions about the app, I'm always available.

**Comment by raghavrmadya** [comment]
Hi, can you add more information on your application such as screenshots from previous app, the previous client address (if you are using a different one now), as well as how much DC you have already received. Also include SPs you worked with before. 

All this information will help notaries to move quicker and for you to gain trust

**Comment by 2748198** [comment]
@raghavrmadya Thank you for your reply. 
My previous application only completed the RKH and did not get the DC credit.
![ldn-301](https://user-images.githubusercontent.com/69459803/204427910-e7bb0d13-4b75-4f8d-afd7-62251fa771da.png)

**Comment by 2748198** [comment]
Please take the time to check out our application as well, thank you very much!

**Comment by 2748198** [comment]
Hi @simonkim0515 , Please take the time to check out our application as well, thank you very much!

**Comment by Defil2022** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceambspt4ebvkoqqztfrtjkxpdnmo3o6lq2ml6rjzkk2psjdauwf3m 
#### Address 
> f1o7z3hrmxthl2yohnoabk2bmmveg6aoomatv52hq
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1dnb3uz7sylxk6emti3ififcvu3nlufnnsjui6ea
#### Id
> 0efe4bba-df0b-4761-885d-acd732dbe513
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceambspt4ebvkoqqztfrtjkxpdnmo3o6lq2ml6rjzkk2psjdauwf3m

**Comment by 2748198** [comment]
@Defil2022  Thanks to your support and signature, we have found SPs through the community and everything is ready. Just like in our allocation plan, our first phase of DC will be allocated to at least 4 SPs. And the quota will not exceed 25% of the current quota.

**Comment by kernelogic** [comment]
LGTM, KYC done previously, willing to support.

**Comment by newwebgroup** [comment]
Reviewed the comments of other notaries in history and checked the distribution of SPs. It looks good at first.

<img width="552" alt="image" src="https://user-images.githubusercontent.com/100118145/206960431-a6a7c594-9d6d-453c-9d98-0e64dd380e8d.png">

**Comment by newwebgroup** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceau2eh52b2efpp7k3bfwdlbexcp56hr4seyf57ibo27ajf2nl2i6y 
#### Address 
> f1o7z3hrmxthl2yohnoabk2bmmveg6aoomatv52hq
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1e77zuityhvvw6u2t6tb5qlnsegy2s67qs4lbbbq
#### Id
> 26154b0c-1749-48b4-9411-a47512a1ee53
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceau2eh52b2efpp7k3bfwdlbexcp56hr4seyf57ibo27ajf2nl2i6y

**Comment by stcouldlisa** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceclnbruhtqw24wnfl5nffcxcj27v75ehpdeqkjlkjq6qhgpymhubo 
#### Address 
> f1o7z3hrmxthl2yohnoabk2bmmveg6aoomatv52hq
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1jvvltduw35u6inn5tr4nfualyd42bh3vjtylgci
#### Id
> 26154b0c-1749-48b4-9411-a47512a1ee53
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceclnbruhtqw24wnfl5nffcxcj27v75ehpdeqkjlkjq6qhgpymhubo

**Comment by stcouldlisa** [comment]
look good，

**Comment by Tom-OriginStorage** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceareanrqtkhkox2roq4izxt6iz6yfgvpc2aj3lirmd5odi5oqlamc 
#### Address 
> f1o7z3hrmxthl2yohnoabk2bmmveg6aoomatv52hq
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1q6bpjlqia6iemqbrdaxr2uehrhpvoju3qh4lpga
#### Id
> 6b6c6353-d48e-4357-9b89-923d62942aca
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceareanrqtkhkox2roq4izxt6iz6yfgvpc2aj3lirmd5odi5oqlamc

**Comment by YuanHeHK** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceas63atgh6524vclpiduml2xjjv4my6boaam2jdiyafawbdp2kctk 
#### Address 
> f1o7z3hrmxthl2yohnoabk2bmmveg6aoomatv52hq
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1fg6jkxsr3twfnyhdlatmq36xca6sshptscds7xa
#### Id
> 6b6c6353-d48e-4357-9b89-923d62942aca
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceas63atgh6524vclpiduml2xjjv4my6boaam2jdiyafawbdp2kctk

**Comment by filplus-checker** [comment]
## DataCap and CID Checker Report[^1]
 - Organization: `Hangzhou silu Technology Co., Ltd`
 - Client: `f1o7z3hrmxthl2yohnoabk2bmmveg6aoomatv52hq`
### Storage Provider Distribution
The below table shows the distribution of storage providers that have stored data for this client.

If this is the first time a provider takes verified deal, it will be marked as `new`.

For most of the datacap application, below restrictions should apply.
 - Storage provider should not exceed 25% of total datacap.
 - Storage provider should not be storing duplicate data for more than 20%.
 - Storage provider should have published its public IP address.
 - All storage providers should be located in different regions.

✔️ Storage provider distribution looks healthy.

| Provider                                              |                    Location | Total Deals Sealed | Percentage | Unique Data | Duplicate Deals |
| :---------------------------------------------------- | --------------------------: | -----------------: | ---------: | ----------: | --------------: |
| [f01949065](https://filfox.info/en/address/f01949065) | Los Angeles, California, US |          27.31 TiB |     22.55% |   27.31 TiB |           0.00% |
| [f021695](https://filfox.info/en/address/f021695)     |            Osaka, Ōsaka, JP |          24.08 TiB |     19.88% |   24.08 TiB |           0.00% |
| [f01955058](https://filfox.info/en/address/f01955058) | Los Angeles, California, US |          23.81 TiB |     19.66% |   23.81 TiB |           0.00% |
| [f01941229](https://filfox.info/en/address/f01941229) |            Osaka, Ōsaka, JP |          21.48 TiB |     17.74% |   21.48 TiB |           0.00% |
| [f01908646](https://filfox.info/en/address/f01908646) | Los Angeles, California, US |          12.33 TiB |     10.18% |   12.33 TiB |           0.00% |
| [f01908695](https://filfox.info/en/address/f01908695) |            Osaka, Ōsaka, JP |          12.08 TiB |      9.97% |   12.08 TiB |           0.00% |

![Provider Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/1313/1671098987038.png)
### Deal Data Replication
The below table shows how each many unique data are replicated across storage providers.
- No more than 25% of unique data are stored with less than 4 providers.

✔️ Data replication looks healthy.

| Unique Data Size | Total Deals Made | Number of Providers | Deal Percentage |
| ---------------: | ---------------: | ------------------: | --------------: |
|         2.34 TiB |         2.34 TiB |                   1 |           1.94% |
|         2.86 TiB |         5.72 TiB |                   2 |           4.72% |
|         1.97 TiB |         5.91 TiB |                   3 |           4.88% |
|         7.50 TiB |        30.00 TiB |                   4 |          24.77% |
|         2.09 TiB |        10.47 TiB |                   5 |           8.65% |
|        11.11 TiB |        66.66 TiB |                   6 |          55.05% |

![Replication Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/1313/1671098987583.png)
### Deal Data Shared with other Clients
The below table shows how many unique data are shared with other clients.
Usually different applications owns different data and should not resolve to the same CID.

✔️ No CID sharing has been observed.

[^1]: To manually trigger this report, add a comment with text `checker:manualTrigger`

**Comment by fireflyHZ** [comment]
checker:manualTrigger

**Comment by Tom-OriginStorage** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceafptrog4r7qps3ckmtj2gbngxqabgm2ac254ggbny6g2qlfmkids 
#### Address 
> f1o7z3hrmxthl2yohnoabk2bmmveg6aoomatv52hq
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1q6bpjlqia6iemqbrdaxr2uehrhpvoju3qh4lpga
#### Id
> b6de334d-80da-4b2b-aee9-e3eb0996a70a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceafptrog4r7qps3ckmtj2gbngxqabgm2ac254ggbny6g2qlfmkids

**Comment by fireflyHZ** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec6ohr6ckaatsiwif2h2me3r5hrg4zf7juwsab2235yl5tt3yjwj6 
#### Address 
> f1o7z3hrmxthl2yohnoabk2bmmveg6aoomatv52hq
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1fg6jkxsr3twfnyhdlatmq36xca6sshptscds7xa
#### Id
> b6de334d-80da-4b2b-aee9-e3eb0996a70a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec6ohr6ckaatsiwif2h2me3r5hrg4zf7juwsab2235yl5tt3yjwj6

**Comment by kernelogic** [comment]
checker result looks very good.

**Comment by newwebgroup** [comment]
checker Looks like everything's okay

**Comment by kernelogic** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceabi3536smkqewg33cpyuuefu25rfc2ubkrktkd4h2uwxv6szrevk 
#### Address 
> f1o7z3hrmxthl2yohnoabk2bmmveg6aoomatv52hq
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### Id
> 43830788-bbeb-489d-ad75-7a16ccd245e9
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceabi3536smkqewg33cpyuuefu25rfc2ubkrktkd4h2uwxv6szrevk

**Comment by newwebgroup** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced26bcuqewqmg4dvp3m6bzy6vc6faslweixexzj237zevy3n6hzsg 
#### Address 
> f1o7z3hrmxthl2yohnoabk2bmmveg6aoomatv52hq
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1e77zuityhvvw6u2t6tb5qlnsegy2s67qs4lbbbq
#### Id
> 43830788-bbeb-489d-ad75-7a16ccd245e9
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced26bcuqewqmg4dvp3m6bzy6vc6faslweixexzj237zevy3n6hzsg

**Comment by newwebgroup** [comment]
Tip
There are some errors. After the normal signing, the DC quota has not arrived.
Filplus background shows that it can be signed again, and will sign again to see whether it is normal.

**Comment by newwebgroup** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceah6v6mnvcsa5bhbymebgwuvxsrcwhul3k7j3qwjbqg67f6unevne 
#### Address 
> f1o7z3hrmxthl2yohnoabk2bmmveg6aoomatv52hq
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1e77zuityhvvw6u2t6tb5qlnsegy2s67qs4lbbbq
#### Id
> 43830788-bbeb-489d-ad75-7a16ccd245e9
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceah6v6mnvcsa5bhbymebgwuvxsrcwhul3k7j3qwjbqg67f6unevne

**Comment by newwebgroup** [comment]
After a second query, it is found that the DC quota has been received, and the last Proposal will be withdrawn
<img width="785" alt="image" src="https://user-images.githubusercontent.com/100118145/210305154-5eff94d4-c86d-4f30-878b-609954825a73.png">

**Comment by herrehesse** [comment]
Dear Applicant,

Due to the increased amount of erroneous/wrong Filecoin+ data recently, on behalf of the entire community, we feel compelled to go deeper into datacap requests. Hereby to ensure that the overall value of the Filecoin network and Filecoin+ program increases and is not abused.

Please answer the questions below as comprehensively as possible.

**Customer data**

- Could you demonstrate exactly how and to what extent customer contact occurred? 

We expect that for the onboarding of customers with the scale of an LDN there would have been at least multiple email and perhaps several chat conversations preceding it. A single email with an agreement does not qualify here.

- Did the customer specify the amount of data involved in this relevant correspondence?

- Why does the customer in question want to use the Filecoin+ program? 

_Should this only be soley for acquiring datacap this is of course **out of the question**. The customer must have a legitimate reason for wanting to use the Filecoin+ program which is intended as a program to store useful and public datasets on the network._ 

- Why is the customer data considered Filecoin+ eligible?

_(As an intermediate solution Filecoin offers the FIL-E program or the glif.io website for business datasets that do not meet the requirements for a Filecoin+ dataset)_


**Files and Processing**

- Could you please demonstrate to us how you envision processing and transporting the customer data in question to any location for preparation?
- Would you demonstrate to us that the customer, the preparer and the intended storage providers all have adequate bandwidth to process the set with its corresponding size?
- Would you tell us how the data set preparer takes into account the prevention of duplicates in order to prevent data cap abuse?


Hopefully you understand the caution the overall community has for onboarding the wrong data. We understand the increased need for Filecoin+, however, we must not allow the program to be misused. Everything depends on a valuable and useful network, let's do our best to make this happen. Together.

**Comment by BDEio** [comment]
@2748198 Hi! Great to see that you have gotten approval for DataCap!
BDE is a verified deals auction house helping you to get paid storing your data with reliable storage providers. If you need any help, please get in touch.

**Comment by cryptowhizzard** [comment]
Same as #1349 

No retrieval supported.

**Comment by 2748198** [comment]
Hi @herrehesse , sorry for taking so long to respond to your questions.

**Comment by 2748198** [comment]
Hello @herrehesse , sorry for taking so long to respond to your questions.

**Customer data**

- Could you demonstrate exactly how and to what extent customer contact occurred?
Hangzhou Silu Information Co., Ltd. focuses on the research of resource media design and distributed storage of online teaching platform.
Under the normalization of the epidemic, remote work and online teaching have gradually become a norm, and many colleges and universities have gradually increased their efforts to establish their own online open teaching. This brings two demands, the first aspect: a teaching platform for the public network to provide distance teaching services for students, teachers, and adult educators, and the second aspect, the copyright and storage of teaching videos.

- Did the customer specify the amount of data involved in this relevant correspondence?
We are currently doing remote video teaching services of Zhejiang University of Media and Communication, Gannan Medical College, Zhejiang Shuren University, Shandong University of Finance and Economics, Zhejiang Institute of Mechanical and Electrical Engineering, on the one hand, the project requires a large number of data storage services, generally a college produces data between 1-2P a year, and the storage demand for data is very large; The other party
We also fancy Filecoin's role in data security. Now that the first phase of the project has been launched, we have made a unified teaching platform to provide schools with daily teaching live broadcast and on-demand courses.

- Why does the customer in question want to use the Filecoin+ program?
This data will be used less frequently over time, especially after the epidemic is over, but we cannot discard this data, and choosing Filecoin storage is a very good storage solution from the perspective of the cost of our storage.

- Why is the customer data considered Filecoin+ eligible?
Because FileCoin's vision and reliable storage are a good fit for our open class dataset.

**Files and Processing**

- Could you please demonstrate to us how you envision processing and transporting the customer data in question to any location for preparation?
On our side, we package the data into a car file by using the tools provided by SP and mail it to SPs via physical hard disk.
- Would you demonstrate to us that the customer, the preparer and the intended storage providers all have adequate bandwidth to process the set with its corresponding size?
We send the data to the partner SP before retrieving and bandwidth requirements. If something goes wrong here, we will terminate the delivery order to them and ask them to resolve the problem.
- Would you tell us how the data set preparer takes into account the prevention of duplicates in order to prevent data cap abuse?
The data source is controlled and processed by ourselves, and we can guarantee this

@cryptowhizzard 
I will also try to retrieve it and if there is a problem I will ask SPs to fix this.

**Comment by herrehesse** [comment]
@2748198 Thank you for your in depth answer. Here are follow-up questions.

1. "Filecoin storage" is not the same as "Filecoin+ datacap". You can facilitate and help this business on filecoin without the use of datacap. Datacap (FIL+ is a commodity for valuable datasets to be stored on Filecoin. The blockchain can facility storage for you without the need of this program at all. So, your response does not really answer my question.

2. "Because FileCoin's vision and reliable storage are a good fit for our open class dataset." also not an answer to my question.

3. You state that you are packing yourself, which is awesome. But you are completely new to Filecoin's GitHub and Slack and you request the highest amount available of 5PiB. Even the best Filecoin businesses with huge dedicated teams are having issues with these amounts. It is simply too much for an account with zero reputation.

Adding, I would like to get a view on your selected SP's and their business names and regions. So we can see their reputation, IP and if the distribution is in order.

**Comment by nj-steve** [comment]
checker:manualTrigger
