### ISSUE TITLE
[DataCap Application] SuperMeofficial

### ISSUE THREAD

**Issue by lea13sda** [filecoin-project/filecoin-plus-large-datasets#1314]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: SuperMeofficial
- Website / Social Media: https://maoyoo.net/    https://www.facebook.com/supermiiofficial
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5 PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100TiB
- On-chain address for first allocation: f1ed7vkc4uqrjlj4pzoo7pdytlbh6wphleptud2ji

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
MaoYoo Network focuses on the development and operation of mobile Internet applications, our mission: technology makes your life happier! The company has developed a variety of mobile phone applications and game products. Among them, the "SuperMe" App has accumulated over 15 million downloads worldwide, and "Cool Face" has more than 3 million downloads in China; its active users are all over the world, and it is a popular avatar maker app for anime fans around the world. The Maoyou team shares moving products for animation fans around the world with feelings as the original intention. Aiming to build the company into a unicorn in the development of application software in the global animation industry.
1. We have 15 million users in 147 countries around the world, DMU: 1 million+
2. We also have online storage NFT services, etc. At present, we have developed a website to help users store valid NFT original element data online, and it is currently in operation for promotion.
```

What is the primary source of funding for this project?
```
Company revenue: advertising revenue, download revenue
```

What other projects/ecosystem stakeholders is this project associated with?
```
Animation industry application software, NFT
```

## Use-case details

Describe the data being stored onto Filecoin
```
The data stored on Filecoin includes nft, pictures, and bbs, as well as videos related to us published by animation fans across the network. We all need to save it.
```

Where was the data in this dataset sourced from?
```
Our apps, forums, and company promotions
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://opensea.io/collection/richpunkclubpolygon
https://drive.google.com/file/d/1geZB4IbjggAOxdGnbCza7zeZvj9ggXoU/view?usp=sharing
https://drive.google.com/file/d/12en2YcROTCtw997secTmc6WUAOnAKJ7L/view?usp=sharing
https://drive.google.com/file/d/1S1eF5_En-u7nD5ZZWIYC4mQTAW2XQKIY/view?usp=sharing
https://drive.google.com/file/d/1PsVeG-kGqrtTtC0jLnNN6Q_unERGbbSK/view?usp=sharing
https://drive.google.com/file/d/137Eju72q2ebWaIHRccNyWS5oz8F4k1vT/view?usp=sharing
https://drive.google.com/file/d/1lmubHvUr8ryUzQn6NNzaAEHtdVCue1DX/view?usp=sharing
https://drive.google.com/file/d/1Wyew_MlV97ZShangYS0a2pRjDhK5ILC6/view?usp=sharing
https://drive.google.com/file/d/1jntG5mSTZguQC7SM39RT3XQcBdERs7eO/view?usp=sharing
https://drive.google.com/file/d/1qbzYao_ATmztglomwzfW_GL_AxskPgrY/view?usp=sharing
https://drive.google.com/file/d/1ekMEzHATew-diOzfatkEa9y6x7xTrUDt/view?usp=sharing
https://drive.google.com/file/d/1Gra9mU26-_CruQo7JwxAT6UvPLgWAHGZ/view?usp=sharing
https://drive.google.com/file/d/1VhhhkXTebGUI-9Ih3BA-S1ixT_pOMRTV/view?usp=sharing
https://drive.google.com/file/d/1fOdG3zEmMo7lHQUY1ZP-95-2TKydFO3Q/view?usp=sharing
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
It is public data
```

What is the expected retrieval frequency for this data?
```
The frequency of retrieval is relatively low
```

For how long do you plan to keep this dataset stored on Filecoin?
```
We are sharing touching products for anime lovers all over the world, I hope he can keep it forever
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Currently planning to be in Singapore
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
we are distributed office, the location will not be fixed, so we will choose online transmission.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We are prefer to find suitable miners in the storage provider interface released by Filecoin. 
```

How will you be distributing deals across storage providers?
```
We plan to select four to five miners, each miner will be allocated 20%-25%.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
yes,we have enough funds to support this project. I‘d like to communicate more with filecoin community.
```

**Comment by lea13sda** [comment]
@raghavrmadya @galen-mcandrew @Kevin-FF-USA 
We have done KYC certification, our previous application page was closed, this is a new issue I created, please review and tell me what else I need to add? thank you!
<img width="680" alt="fc480d71f947f0d937a72a30418a0d0" src="https://user-images.githubusercontent.com/111737415/203914396-c4637c33-6bfb-4563-a0a6-78ffb4c8c8fd.png">

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 100TiB

**Client address**

> f1ed7vkc4uqrjlj4pzoo7pdytlbh6wphleptud2ji

**Comment by Defil2022** [comment]
Hi @lea13sda 
Have you contact with your SPs? and list their ID as much as you can please. 
How many data that you have prepared until now? 
Are you able to upload ASAP?

**Comment by lea13sda** [comment]
Hello, @Defil2022 
So far we have prepared no less than 5P data, which can be uploaded at any time.
The sp we plan to communicate with: f01384209｜f01890456｜f01831983｜f01853077

**Comment by lvschouwen** [comment]
@lea13sda 
Can you work with your SPs to make sure their miners are reachable? As you can see [f01985611](https://filfox.info/en/address/f01985611) and [f01971431](https://filfox.info/en/address/f01971431) are not.
Can you also explain to the community why there is CID sharing going on?

**Comment by cryptowhizzard** [comment]
#1089 is also involved.
#960 is also involved.
#1173 is also involved.
