### ISSUE TITLE
[DataCap Application] <QYER（Beijing）Company Limited> - <QYER>

### ISSUE THREAD

**Issue by QYTX123** [filecoin-project/filecoin-plus-large-datasets#1316]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: QYER（Beijing）Company Limited（北京穷游天下科技发展有限公司）
- Website / Social Media: - https://www.qyer.com/、Wechat Official account：穷游网
![image](https://user-images.githubusercontent.com/119022732/203897852-b18ee178-6346-4642-9f07-7706023f00fc.png)
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 2.6PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 160TiB
- On-chain address for first allocation:  f15arlxjklruhhwz6ulqdnbowwc2uyp632jaum4mi

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Established in 2004 in the dormitory for international students in Europe, Qiongyou.com is the largest outbound travel community in China, providing users with original and practical outbound travel guides and travel strategies, travel areas and question-and-answer exchange platforms, as well as visas, insurance, air tickets, hotel reservations, car rentals, etc. The service aim of poor travel is to "make it easier for Chinese people to travel abroad and help everyone get a better travel and life experience". In 2006, the European Forum for Poor Travel was officially renamed as Poor Travel, and joined the self-help travel sections of other continents. The service aim of poor travel is "to make it easier for Chinese people to travel abroad and help them get better travel and life experience.
```

What is the primary source of funding for this project?
```
The main funds come from users booking hotels in official website, purchasing air ticket insurance, visa processing, purchasing goods, etc.
```

What other projects/ecosystem stakeholders is this project associated with?
```
NO other. 
```

## Use-case details

Describe the data being stored onto Filecoin
```
**Product app data:** The company has three travel apps, including travel strategies, popular videos, hotel information and other data.
**User data accumulation:** Data generated by users using the platform, such as user browsing travel strategies, forum posting, hotel reservation information and other data.
**Official website data:** Official website collects rich global travel strategies, global hotel information, global wonderful travel videos, visa and car rental information and other data.
```

Where was the data in this dataset sourced from?
```
This data set comes from user usage data, official website data and data generated by its app, mainly audio and video, graphic information data.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://www.qyer.com/video/
https://bbs.qyer.com/
https://ask.qyer.com/
https://biu.qyer.com/
https://guide.qyer.com/
https://z.qyer.com/
https://hotel.qyer.com/
https://bbs.qyer.com/forum-2-1.html
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes, it is a public data.
```

What is the expected retrieval frequency for this data?
```
This data is used by users after downloading, and the expected retrieval frequency is once a year.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
We expect to store it for one year first, and then we need to observe the storage effect before making a decision.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Asian region.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
If in China, we will choose online transmission, Offline data will be stored on servers in China.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We will choose experienced and reliable storage providers.
```

How will you be distributing deals across storage providers?
```
We'll give the storage providers an even distribution ratio.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
We have our own product revenue, so we can afford to fund it, and the slack community is a great inspiration for us.
```

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 2.6PiB

**Expected weekly DataCap usage rate**

> 160TiB

**Client address**

> f15arlxjklruhhwz6ulqdnbowwc2uyp632jaum4mi

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Looking at your application i have some questions:
As you are brand new on Github and have no history of past applications it seems to me that applying for 2.6PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?

Can you show us visible proof of the size of your data and the storage systems you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230232885049356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!
