### ISSUE TITLE
[DataCap Application] <Shenzhen Rootsense Company Limited> 

### ISSUE THREAD

**Issue by watermelon2022033** [filecoin-project/filecoin-plus-large-datasets#1317]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Shenzhen Rootsense Company Limited
- Website / Social Media:- website：http://www.rootsense.cn/default.htm weibo:ROOTSENSE根元
Douyin :唯美精选品
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):2PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):120TiB
- On-chain address for first allocation:f1tleykllqe73tduzhj5cayxamfoorx55ezj3xb3y

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
Shenzhen Rootsense Co., Ltd. was established on April 28, 2014. The company's business scope includes: technical consultation, technical services, technology development, and technology transfer in the field of environmental protection technology; mechanical and electrical products, electronic components, electronic products, household appliances and accessories, building waterproof materials, Wujinjiaodian, daily necessities, crafts Sales of gifts, building and decoration materials, sanitary ware, flowers and seedlings, labor protection products; cleaning services, household services, and import and export of goods and technologies.

What is the primary source of funding for this project?
product sales

What other projects/ecosystem stakeholders is this project associated with?
NO other stakeholder. 

## Use-case details

Describe the data being stored onto Filecoin
Rootsense has Rootsense Home APP and Shoe Control APP, and each has its own flagship store and a large number of e-commerce partners on Tmall, Taobao, and Jingdong. Own your own products and check the quality control yourself. Through the video promotion of major platforms, it is associated with the company's business, generating a large amount of videos and background data, including product videos, live videos and e-commerce platform data. The background data generated by the APP will pave the way for the company's business, so that the company can better serve each customer and create better products.

Where was the data in this dataset sourced from?
A large number of videos generated by the promotion of the company's products, as well as promotional videos created by bloggers on various social platforms, product design data and e-commerce background data.

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
https://www.douyin.com/video/7058476960212782375
https://www.bilibili.com/video/BV1Cq4y1H7BH?vd_source=9fb10707865e2d7092a18304bf88bfd9
https://www.bilibili.com/video/BV16U4y1G7DS?vd_source=9fb10707865e2d7092a18304bf88bfd9
https://www.1688.com/chanpin/-B1F9CFE420D2ECCEB6.html
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
Yes, it is a public data.

What is the expected retrieval frequency for this data?
There are a large number of material videos, which are expected to be twice a year for more effective product promotion in the future.

For how long do you plan to keep this dataset stored on Filecoin?
We expect to store for 2 years.

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
Most are in China, with a tiny fraction of export data stored overseas.

How will you be distributing your data to storage providers? Is there an offline data transfer process?
Equal distribution for easy communication.
Yes.

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
[f01909311][f01271385][f01833148][f01223318]

We will choose SPs that have already cooperated.
How will you be distributing deals across storage providers?
Divided into video, product and background data.

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
With enough capital, the company has its own business income.
We have learned web3 before.

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 2PiB

**Expected weekly DataCap usage rate**

> 120TiB

**Client address**

>f1tleykllqe73tduzhj5cayxamfoorx55ezj3xb3y

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Looking at your application i have some questions:
As you are brand new on Github and have no history of past applications it seems to me that applying for 5PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?

Can you show us visible proof of the size of your data and the storage systems you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230337462961356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!
