### ISSUE TITLE
[DataCap Application] Super Accurate Vision Technology

### ISSUE THREAD

**Issue by szwin** [filecoin-project/filecoin-plus-large-datasets#1320]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Shenzhen Chaozhun Vision Technology Co., Ltd.
- Website / Social Media: [www.super-accurate.com](http://www.super-accurate.com/)
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 2.5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 180TiB
- On-chain address for first allocation: f3u3fitrgaxw2fpdo632mvwkeklnlipyxfrmlhqoxe6uajlwl4wuhuqos4keoweikauejrmlucnco37sdutaoa

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Shenzhen Chaozhun Vision Technology Co., Ltd. was established in 2017. It is a leading comprehensive service provider and a national high-tech enterprise specializing in the R&D, design, manufacturing and sales of 3D machine vision systems in China. The products cover 3D image sensors, algorithms, software and overall solutions, which are widely used.
2017: Insist on taking scientific and technological innovation as the guide and taking advanced manufacturing as the foundation
2018: Complete the development of 3D positioning and guiding vision system
2019: Mass production of 3D intelligent welding vision guidance system, won the national high-tech enterprise
2020 to now: reached cooperation with many large-scale construction, automobile and other enterprises, and the business volume has increased significantly
```
![image](https://user-images.githubusercontent.com/119086251/204066919-03ed85db-98e7-4ce8-9428-e375626eeaff.png)

What is the primary source of funding for this project?
```
Company.
```

What other projects/ecosystem stakeholders is this project associated with?
```
None.
```

## Use-case details

Describe the data being stored onto Filecoin
```
Mainly are pictures and videos.
```

Where was the data in this dataset sourced from?
```
Case videos of the company's products operating in different industries, media videos produced by the company's publicity and promotion department, and promotional and explanatory pictures of different products.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://docs.google.com/document/d/1jzC6EKeI7V6Kr2MGa5E_nfvCeqwqm_oyzw7riuQVWz4/edit?usp=sharing
https://v.douyin.com/rXdapAq/
http://www.super-accurate.com/video
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes. It is a public dataset.
```

What is the expected retrieval frequency for this data?
```
Maybe 5 or more times a year.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
For one year or more. It depends on the situation of storage.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Asia, in China or Singapore.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
We will choose the most convenient and economic means.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We will contact storage providers in Asia to investigate storage qualifications and service quality through a combination of online and offline methods to ensure that data can be stored and retrieved normally.
```

How will you be distributing deals across storage providers?
```
We will contact many storage providers at home and abroad to ensure the distributed storage of data.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, we have.
```

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 2.5PiB

**Expected weekly DataCap usage rate**

> 180TiB

**Client address**

> f3u3fitrgaxw2fpdo632mvwkeklnlipyxfrmlhqoxe6uajlwl4wuhuqos4keoweikauejrmlucnco37sdutaoa

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Looking at your application i have some questions:
As you are brand new on Github and have no history of past applications it seems to me that applying for 5PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?

Can you show us visible proof of the size of your data and the storage systems you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230337462961356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!
