### ISSUE TITLE
[DataCap Application] < Guangzhou Moreless Network Technology Co., Ltd > - < Tide >

### ISSUE THREAD

**Issue by Moreless000** [filecoin-project/filecoin-plus-large-datasets#1321]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Guangzhou Moreless Network Technology Co., Ltd（广州多少网络科技有限公司）
- Website / Social Media: - https://moreless.io/ Wechat Official account：潮汐App 
![screenshot-20221128-103818](https://user-images.githubusercontent.com/119029773/204180040-669eb055-d3ef-4375-9cae-afc6efb86e17.png)

- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 3.8PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 180TiB
- On-chain address for first allocation: f1vped3tnyqdswqxvhhjmmrbbpnnui6vqdps6e2uq

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Moreless is a technology company focusing on spiritual upgrading and physical and mental health. We devote our love and efforts to create lifestyle products and brands that make life healthier and happier for users all over the world. The main product is sleep app-Tide. This product is dedicated to creating an inspiration space for urban young people to return to their hearts, advocating the brand concept of sleeping naturally and living awake, and providing one-stop physical and mental health solutions such as immersive, interesting, professional and effective sleep, meditation, concentration and relaxation, so as to help people sleep better and have less anxiety.

```

What is the primary source of funding for this project?
```
The main funds come from users using payment functions, such as rushing members, buying sleep audio and white noise.
```

What other projects/ecosystem stakeholders is this project associated with?
```
NO other. 
```

## Use-case details

Describe the data being stored onto Filecoin
```
**Product app data:** The company's Tide app has built-in plug-ins, sound scenes, meditation exercises and daily inspiration motto data, including a large number of audio, video and graphic data.
**User data accumulation:** Data generated by users using the platform, such as white noise, video, copy and other data downloaded by users.
```

Where was the data in this dataset sourced from?
```
This data set comes from user usage data, data generated by user download and data generated by its app, mainly audio, video and graphic data.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://tide.fm/sounds/
https://tide.fm/meditation/
https://video.weibo.com/show?fid=1034:4836817363730557
https://video.weibo.com/show?fid=1034:4835095669047309
https://www.woshipm.com/evaluating/4238931.html
https://www.instagram.com/p/B_P7CAzjTlp/?utm_source=ig_web_copy_link
https://www.instagram.com/p/B5Fr6R-nyTK/?utm_source=ig_web_copy_link
https://www.instagram.com/p/B2vO4hzHrZ0/?utm_source=ig_web_copy_link
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes, it is a public data.
```

What is the expected retrieval frequency for this data?
```
This data is used by users to learn after downloading, and the expected retrieval frequency is 1 times a year.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
We expect to store it for one year first, and then we need to observe the storage effect before making a decision.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Asian region.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
If in China, we will choose online transmission, Offline data will be stored on servers in China.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We will choose experienced and reliable storage providers.
```

How will you be distributing deals across storage providers?
```
We'll give the storage providers an even distribution ratio.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
We have our own product revenue, so we can afford to fund it, and the slack community is a great inspiration for us.
```

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 3.8PiB

**Expected weekly DataCap usage rate**

> 180TiB

**Client address**

> f1vped3tnyqdswqxvhhjmmrbbpnnui6vqdps6e2uq

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Looking at your application i have some questions:
As you are brand new on Github and have no history of past applications it seems to me that applying for 3.8PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?

Can you show us visible proof of the size of your data and the storage systems you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230232885049356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!
