### ISSUE TITLE
[DataCap Application] <iNFT> 

### ISSUE THREAD

**Issue by wangkai88** [filecoin-project/filecoin-plus-large-datasets#1322]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: iNFT
- Website / Social Media: https://inft.io/  Twitter：https://twitter.com/iNFT_io  Telegram：https://t.me/iNFTglobal
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100TiB
- On-chain address for first allocation: f147zdeyrtzh4nvm3svhoxxdybj2osd4r3pr5hzbq

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
iNFT is a leading global NFT asset trading platform. It is founded in September 2020, the first version went live in November 2020, supporting Non-Fungible Token trading of Ethereum's ERC721 and ERC1155 asset protocols.
iNFT is committed to creating a safe, efficient, fair and low-cost NFT asset issuance and trading platform; Provide users with convenient NFT minting, trading, mining and other DeFi functions, and provide an editorial minting, distribution, fundraising and trading platform for publishers and NFT authors.
At the same time, in order to allow more NFT enthusiasts to enjoy the financial dividends brought by DeFi, iNFT trading platform will support the NFT assets of BSC, HECO, EOS, Boca, Wave Field, HPB and other mainstream public chains, and provide more tools to assist ecological development, forming the aggregation of NFT assets.
The platform will also strengthen the business cooperation of NFT projects, and bring some popular NFT asset transactions to the iNFT platform through trade mining, fee reduction and other ways. For example, NBATopshot, ZED.run, Axie, cryptopunk, decenntraland, somnium space and other projects have their own user traffic, so as to achieve a series of NFT assets for the platform drainage effect.

```

What is the primary source of funding for this project?
```
Revenue of the Company
```

What other projects/ecosystem stakeholders is this project associated with?
```
No
```

## Use-case details

Describe the data being stored onto Filecoin
```
iNFT data mainly includes the following types:
(1) NFT trading platform core data backup image, generally 24 times a day backup, the current core data image about 10G; (10G*24*days)
(2) The increasing NFT resources of the platform
(3) User data, NFT transaction data, etc.
```

Where was the data in this dataset sourced from?
```
Thae dataset is from iNFT platform, including NFT resource, database backup, and NFT transaction history, etc. 
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://drive.google.com/drive/folders/16XckRdPaB_4T8V4pviyw26b3pH6nUgzN
https://drive.google.com/drive/folders/1zypO-rct4rLYd3f2L8yzz8ZYPk0656il
https://drive.google.com/drive/folders/1kKmXx4lLPpgfKm27DUqcnakStRCqj1Ta
https://drive.google.com/drive/folders/1MIN2ZbKw9BtLSwSSAfWIBJz2E3zY-jf2?usp=sharing
https://docs.google.com/spreadsheets/d/1eiYL2SUk8uqhqkfmWfK4K5KFeR0cE7NtHbZU5BCH9Cc/edit?usp=sharing
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes, it is public dataset, everyone can retrieve them.
```

What is the expected retrieval frequency for this data?
```
Once a month
```

For how long do you plan to keep this dataset stored on Filecoin?
```
At least two years.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Asia, EU, North America, and America.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
We will send offline deals to storage providers. The dataset will be uploaded to the our server, storage providers can directly download them
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We will select the storage providers according to their reputation, adjusted power, storage space and computational efficiency and so on. To ensure the data is retrievable, fast retrieval will be required for the storage providers, and the storage providers must be reachable during the storage period.  
```

How will you be distributing deals across storage providers?
```
we will send the deals to the five different storage providers, and no more than 25 percent of the dataset will be sent to a single storage provider.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Our company will support it. We will send deals according to the official lite node "FULLNODE_API_INFO=wss://api.chain.love lotus daemon --lite"
```

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 100TiB

**Client address**

> f147zdeyrtzh4nvm3svhoxxdybj2osd4r3pr5hzbq

**Comment by flyworker** [comment]
The application looks interesting to me.
FiLSwan wants to support NFT storage use case.
@wangkai88  Maybe you can use Multichain.storage as a technology solution.
If you have questions please come to us.
You can find us on #fil-filswan channel.

**Comment by flyworker** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebhvr7xr4siytj6hoflrctrltrobuc2xjr4si7ud3wbczc5pcwbxi 
#### Address 
> f147zdeyrtzh4nvm3svhoxxdybj2osd4r3pr5hzbq
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1hlubjsdkv4wmsdadihloxgwrz3j3ernf6i3cbpy
#### Id
> 7a31cf09-b007-4347-b30a-44a61a45cfbb
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebhvr7xr4siytj6hoflrctrltrobuc2xjr4si7ud3wbczc5pcwbxi

**Comment by cryptowhizzard** [comment]
Hi,

@flyworker , can we have a list of SP's where this data is stored for the first tranche and their contact info? This helps keeping the application on track.

Do you want us to perform KYC or have you done that already?

**Comment by flyworker** [comment]
@cryptowhizzard  they confirmed will send though swan client with the bidding engine, but you can double KYC them.

**Comment by cryptowhizzard** [comment]
@flyworker 

Thanks. I will put this on my list to sign as soon as the problems are cleared with the bot.

**Comment by wangkai88** [comment]
Yes, thanks supports from the filswan teams @flyworker ,  we have seen that swan-client is a good onboarding tool. @cryptowhizzard

**Comment by cryptowhizzard** [comment]
I am not sure if the bot problems are cleared but i will put an alarm on my phone to sign tonight

**Comment by cryptowhizzard** [comment]
Hi,

Sorry for my error, but reading up i noticed we did not have KYC done. Can you please fill out my KYC form?
After i received it i will sign asap.

https://form.jotform.com/230337462961356

**Comment by wangkai88** [comment]
@cryptowhizzard I have filled out the KYC form, please check it

**Comment by cryptowhizzard** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacediev7bad4qhlgpbuzpf7cacevdsjphjxmbcmavpw2qf5ksefz5e6 
#### Address 
> f147zdeyrtzh4nvm3svhoxxdybj2osd4r3pr5hzbq
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1krmypm4uoxxf3g7okrwtrahlmpcph3y7rbqqgfa
#### Id
> 7a31cf09-b007-4347-b30a-44a61a45cfbb
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacediev7bad4qhlgpbuzpf7cacevdsjphjxmbcmavpw2qf5ksefz5e6

**Comment by Sunnyiscoming** [comment]
Hello, @wangkai88 per the https://github.com/filecoin-project/notary-governance/issues/922 for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

This information will be reviewed by Fil+ Governance team to confirm validity and then the application will be allowed to move forward for additional notary review.
