### ISSUE TITLE
[DataCap Allocation] - Enterprise Video Data Storage Project

### ISSUE THREAD

**Issue by vaelephant** [filecoin-project/filecoin-plus-large-datasets#1324]
---
name: Large Dataset Notary application
about: Clients should use this application form to request a DataCap allocation via a LDN for a dataset
title: "Enterprise Video Data Storage Project"
labels: 'application, Phase: Diligence'
assignees: ''

---
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Beijing Tianxin Boyi Technology Development Co., Ltd.
- Website / Social Media: https://mbd.baidu.com/ma/s/Qa1zFnhM
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 800TiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100TiB
- On-chain address for first allocation: f1y6hlcjweffnnjkmhetjzlhvw3x6j3fnyex3xcba
- Region: Greater China Region

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Founded in 2011, the company is a service provider focusing on corporate customer loyalty and satisfaction. Based on blockchain technology and product innovation, it is widely used in industrial finance, digital government affairs, digital assets, traceability, supply chain management and other industries, and continues to provide industry-level solutions and products. With multi-centered trust as the core, it is committed to creating A new generation of value circulation network.

```

What is the primary source of funding for this project?
```
private capital

```

What other projects/ecosystem stakeholders is this project associated with?
```
Self-owned resources, independent independent projects

```

## Use-case details

Describe the data being stored onto Filecoin
```
Enterprise video data

```

Where was the data in this dataset sourced from?
```
Corporate business services and product videos

```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
http://207.148.96.245:9000/data/Enterprise%20work%20action%20record.mp4
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Access to this data requires specific permissions or access rights

```

What is the expected retrieval frequency for this data?
```
Retrieve every day

```

For how long do you plan to keep this dataset stored on Filecoin?
```
540 days

```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
China

```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Send to the storage provider through offline data transmission

```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
Find affordable storage providers at https://plus.fil.org/


```

How will you be distributing deals across storage providers?
```
According to the quotation and service decision of the storage provider, it is expected to choose 1 or 2 companies

```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Funding is sufficient. Hope the community can provide storage technical support and suggestions

```

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 800TiB

**Expected weekly DataCap usage rate**

> 100TiB

**Client address**

> f1y6hlcjweffnnjkmhetjzlhvw3x6j3fnyex3xcba

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Looking at your application i have some questions:
As you are brand new on Github and have no history of past applications it seems to me that applying for 800TB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?

Can you show us visible proof of the size of your data and the storage systems you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230232885049356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!
