### ISSUE TITLE
[DataCap Application] <Beijing Xiachufang Technology Co., Ltd> - <Xiachufang>

### ISSUE THREAD

**Issue by Xiachufang9** [filecoin-project/filecoin-plus-large-datasets#1327]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Beijing Xiachufang Technology Co., Ltd（北京下厨房科技有限公司）
- Website / Social Media: https://www.xiachufang.com/ 、 https://weibo.com/xiachufang?sudaref=www.xiachufang.com、https://twitter.com/xiachufang
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 2.8PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 180 TiB
- On-chain address for first allocation: f1k26ft36jiaieksem2pzztsqlcn2r3sjehrg7eyi

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Under the kitchen food recipe network advocates cooking at home, healthy lifestyle, provides copyrighted practical recipe practices and diet knowledge, and provides a platform for chefs and food lovers to record and share.
```

What is the primary source of funding for this project?
```
The main funds come from users' purchase of cooking courses and daily shopping in official website and its app.
```

What other projects/ecosystem stakeholders is this project associated with?
```
NO other. 
```

## Use-case details

Describe the data being stored onto Filecoin
```
Product app data: The kitchen under the company's app contains a variety of posts, rookie recipes, the best of the month, previous headlines, etc., mainly graphic and video data.
User data accumulation: Data generated by users using the platform, such as users browsing recipes, watching learning videos and other data.
Official website data: Official website collects a wealth of recipe data, with more than 1,000 kinds of dishes, mainly graphic and video data.
User work data: Users publish their cooking experience on the platform and share the dishes they learn to cook, mainly including graphic and video data.
```

Where was the data in this dataset sourced from?
```
This data set comes from user usage data, official website data, recipe data generated by its app, cooking course data, mainly audio and video, graphic information data.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://www.xiachufang.com/category/40076/
https://www.xiachufang.com/explore/rising/
https://www.xiachufang.com/explore/head/
https://www.xiachufang.com/explore/monthhonor/ 
https://www.xiachufang.com/explore/menu/pop/
https://www.xiachufang.com/category/1136/
https://www.xiachufang.com/category/674/
https://www.xiachufang.com/recipe/103478616/
https://www.xiachufang.com/activity/site/?order=pop
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes, it is a public data.
```

What is the expected retrieval frequency for this data?
```
This data is used by users after downloading, and the expected retrieval frequency is once a year.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
We expect to store it for one year first, and then we need to observe the storage effect before making a decision.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Asian region.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
If in China, we will choose online transmission, Offline data will be stored on servers in China.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We will choose experienced and reliable storage providers.
```

How will you be distributing deals across storage providers?
```
We'll give the storage providers an even distribution ratio.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
We have our own product revenue, so we can afford to fund it, and the slack community is a great inspiration for us.
```

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 2.8PiB

**Expected weekly DataCap usage rate**

> 180TiB

**Client address**

> f1k26ft36jiaieksem2pzztsqlcn2r3sjehrg7eyi
