### ISSUE TITLE
[DataCap Application] <Guangzhou Uju Info Tech Company Limited> - <Uju Media>

### ISSUE THREAD

**Issue by dogwangwang520** [filecoin-project/filecoin-plus-large-datasets#1328]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Guangzhou Uju Info Tech Company Limited-Uju Media
- Website / Social Media:Website:https://www.ujumedia.com/ Wechat 优矩互动
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):2.3PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):140TiB
- On-chain address for first allocation:f1udbtkeylnckym4us2dowp2fwcf6d5dixmooqldq

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Please answer here.
Uju Media is a market leader specializing in online short video marketing solutions in China. The company spans search, information flow, and short video media, and is committed to the short video ecosystem, serving the entire marketing chain of more than a thousand large domestic customers; it has the ability to produce over 10,000 short videos per month, and has a production capacity in Beijing, Shanghai and Guangzhou. , Chongqing has built a short video shooting base.
The company's self-developed technical system, the Optimum Engine, empowers customers on the operation and creation side. The company is committed to the continuous improvement of the marketing efficiency and effect of our customers through technology and products.

What is the primary source of funding for this project?
```
Please answer here.
Business and short video and advertising revenue

What other projects/ecosystem stakeholders is this project associated with?
```
Please answer here.
NO other stakeholder. 

## Use-case details

Describe the data being stored onto Filecoin
```
Please answer here.
The second largest online marketing service provider in total bills generated by online short video advertising in 2020.
The self-developed technology product Optimum Engine was successfully developed and launched, generating a large amount of background data.
The monthly output of short videos exceeds 10,000, and there is a large amount of video data.

Where was the data in this dataset sourced from?
```
Please answer here.
Huge short video shooting tidbits and feature videos

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
Please answer here.
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Please answer here.
https://www.douyin.com/user/MS4wLjABAAAA3PY6N6XUXH7qHH2VrXI1JnOBjthriZJ1lsx9Vb0p-c8?modal_id=7018493986037828901&relation=0&vid=7034818141435874567
 https://v.douyin.com/rbNMnRo/
https://www.douyin.com/user/MS4wLjABAAAA0LFCGNMxreUtEkWiVE2oLdt4XQEmD3-8d2r-_Ga5QqY?modal_id=6847798730406530318

What is the expected retrieval frequency for this data?
```
Please answer here.
Involving a large amount of video material, customers may have demand, and the download frequency is expected to be about four times a year.

For how long do you plan to keep this dataset stored on Filecoin?
```
Please answer here.
We expect to store for 2 years

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Please answer here.
In China

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Please answer here.
Equal distribution for easy communication.
Yes

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
Please answer here.
f01452360, f01805813, f0689215
choose the most experienced SP in China

How will you be distributing deals across storage providers?
```
Please answer here.
Video data divided into different sections is provided to SP

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Please answer here.
The company's business is doing very well. There are more than 10,000 video promotions every month, and the business is guaranteed. Companies are very interested in FIL.

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 2.3PiB

**Expected weekly DataCap usage rate**

> 140TiB

**Client address**

>f1udbtkeylnckym4us2dowp2fwcf6d5dixmooqldq

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Looking at your application i have some questions:
As you are brand new on Github and have no history of past applications it seems to me that applying for 2.3PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?

Can you show us visible proof of the size of your data and the storage systems you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230232885049356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!
