### ISSUE TITLE
[DataCap Application] <Yingke> - <Smart elevator system>

### ISSUE THREAD

**Issue by mirsea888** [filecoin-project/filecoin-plus-large-datasets#1330]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Zhejiang Yingke Technology (Group) Co., Ltd
- Website / Social Media:http://www.y-five.cn/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):3PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):100TiB
- On-chain address for first allocation:f16wxlzjjz3fxkkuifum2kw7nnp5artwczfciy6ry

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Zhejiang Yingke Technology (Group) Co., Ltd. was established in 2019, has been committed to the research and development and application of "Internet of Things" technology in the elevator industry, has a number of independent core technologies and patents, obtained the national intelligent elevator system safety evaluation certification, is a new research and development institution, elevator safety science popularization base. Yingke IoT has an elevator industry college and an elevator Internet of Things test base.

Yingke IoT actively responds to the call of the country, practices the reform of on-demand maintenance, and strives to create a smart service system for the elevator aftermarket with "Internet of Things" as the core and "digital maintenance + insurance" as one, which is the pioneer of the new model of on-demand maintenance of elevators and the leader of comprehensive solutions for the elevator aftermarket
```

What is the primary source of funding for this project?
```
We sell software services and hardware equipment for a profit
```

What other projects/ecosystem stakeholders is this project associated with?
```
NO.
```

## Use-case details

Describe the data being stored onto Filecoin
```
Our data sources include sample videos, pictures and animations that we have recorded ourselves. In addition, there are sample data provided by customers, as well as more sample data obtained during the actual operation of our project
```

Where was the data in this dataset sourced from?
```
Our data sources include sample videos, pictures and animations that we have recorded ourselves. In addition, there are sample data provided by customers, as well as more sample data obtained during the actual operation of our project
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://drive.google.com/file/d/19toYdrBYWMx80RIN7Kisr5lWXtcdLxyl/view?usp=share_link
https://drive.google.com/file/d/1QsGXqfm25LdAJ5sn35vRQ3Byx6tRJlrx/view?usp=share_link
https://drive.google.com/file/d/1ADZkIC8QoVFUD3O5IUiKh1Z6Ss1dCCv6/view?usp=share_link
https://drive.google.com/file/d/19bUNwDlzw8-w9ORySlfQUOYpJx1nzHWr/view?usp=share_link
https://drive.google.com/file/d/15U4N1apTwmFPnhqJ_IfVQt14JDBIl6AK/view?usp=share_link
https://drive.google.com/file/d/1RruY1ZrQ4ZEkjPF7ZZ0x5q6K8FgvF8oo/view?usp=share_link
https://drive.google.com/file/d/1gAEihhBNKYSNzehvgq1w2vr4Tq8GJwg_/view?usp=share_link
https://drive.google.com/file/d/1P-SY00XCvBu-v7q2ix3QBQxQPXfoNeIi/view?usp=share_link
https://drive.google.com/file/d/1UfanhqHJ1tcUgtZGiV_8BIVb85pGYeCA/view?usp=share_link
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes. We confirm that these courses are public data.
```

What is the expected retrieval frequency for this data?
```
Our open source course data is backed up, and the retrieval frequency is retrieved according to customer needs
```

For how long do you plan to keep this dataset stored on Filecoin?
```
3 years at least.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Mainly in China, Hong Kong, Macao and Taiwan, and foreign customers.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Online transfer or distribute offline to storage providers.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We plan to select multiple storage vendors to store a single piece of data, while opening it up for other retrieval.
The detailed rules are as follows:
1 Has a wealth of filecoin storage experience, and can promise long-term storage.
2 Select at least 2 different regions with at least 4 or more SPs
3 The amount given to each SP does not exceed 25%
```

How will you be distributing deals across storage providers?
```
Less than 25% of total data will be stored in each SP.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes! We have enough funds to support this project.
```

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 3PiB

**Expected weekly DataCap usage rate**

> 100TiB

**Client address**

>f16wxlzjjz3fxkkuifum2kw7nnp5artwczfciy6ry

**Comment by liyunzhi-666** [comment]
hey @mirsea888 
- I checked your data samples and they are all monitoring screenshots. Are you going to store these video screenshots on the Filecoin network?
- How many SPs have you found now? Can you list their IDs?

**Comment by mirsea888** [comment]
Hi @liyunzhi-666
1 Thank you for your attention, our sample data is not only these screenshot data, but also some video data, only these are currently shown, and we will sort out more sample data later to show it.
2 We plan to look for 10 or more SPs. We have already found 6 in talks about storage. They are from 3 different regions and all have experience with DC storage, and I have also tried retrieving their orders and they all look good.
f01908695/f01955058/f01949065/f021695/f01908646/f01941229/
Hope you can review our app and give you some support, thank you very much!

**Comment by liyunzhi-666** [comment]
thanks @mirsea888 
Could you send an email to filplus-app-review@fil.org with your official domain in order to confirm your identity? Email name should includes the issue id.
cc @Sunnyiscoming please help me confirm

**Comment by mirsea888** [comment]
@liyunzhi-666 @Sunnyiscoming I had sent email to filplus-app-review@fil.org . Please check, Thank you!
![2022-12-07 13-39-23](https://user-images.githubusercontent.com/62424416/206098263-b7aea777-2730-4841-9e55-111656e6c3ef.png)

**Comment by liyunzhi-666** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebohzmlmptdpdrzivyxbexd6ziqji2nitd3bprt63baoaq7gsgdcc 
#### Address 
> f16wxlzjjz3fxkkuifum2kw7nnp5artwczfciy6ry
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1pszcrsciyixyuxxukkvtazcokexbn54amf7gvoq
#### Id
> bec950a0-018b-4187-8926-e68e00155196
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebohzmlmptdpdrzivyxbexd6ziqji2nitd3bprt63baoaq7gsgdcc

**Comment by YuanHeHK** [comment]
The information provided so currently appears to be fine, the first signature gives support, and later if there is a problem, it will not be supported.

**Comment by YuanHeHK** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedbbzzykx7jti4evcjup647nobl5l5o3l37h624akhk2z2adfv7bm 
#### Address 
> f16wxlzjjz3fxkkuifum2kw7nnp5artwczfciy6ry
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1fg6jkxsr3twfnyhdlatmq36xca6sshptscds7xa
#### Id
> bec950a0-018b-4187-8926-e68e00155196
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedbbzzykx7jti4evcjup647nobl5l5o3l37h624akhk2z2adfv7bm

**Comment by kernelogic** [comment]
checker result looks very good.

**Comment by kernelogic** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebu6th5uzzsnngxjoefqoipse5sfsvhf7vole2m22usyk4cmknyf4 
#### Address 
> f16wxlzjjz3fxkkuifum2kw7nnp5artwczfciy6ry
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### Id
> 16c95815-2047-48e9-8a5e-8d7aa9e76f44
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebu6th5uzzsnngxjoefqoipse5sfsvhf7vole2m22usyk4cmknyf4

**Comment by NDLABS-OFFICE** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebdvowynuvc2blrxf6poh2zwqpzmrbdp3ntgu723bsmiyndxdnlpg 
#### Address 
> f16wxlzjjz3fxkkuifum2kw7nnp5artwczfciy6ry
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1yayfsv6whu3rheviucvventj3y6t542xfpb47ei
#### Id
> 16c95815-2047-48e9-8a5e-8d7aa9e76f44
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebdvowynuvc2blrxf6poh2zwqpzmrbdp3ntgu723bsmiyndxdnlpg

**Comment by BDEio** [comment]
@mirsea888 Hi! Great to see that you have gotten approval for DataCap!
BDE is a verified deals auction house helping you to get paid storing your data with reliable storage providers. If you need any help, please get in touch.

**Comment by YuanHeHK** [comment]
checker:manualTrigger

**Comment by lvschouwen** [comment]
Hi @mirsea888 

You DataCap and CID report looks very healthy.
In your application you stated "Yes. We confirm that these courses are public data." and "We plan to select multiple storage vendors to store a single piece of data, while opening it up for other retrieval." so I tried downloading it from the SPs listed above, but none of the miners are reachable. Can you please contact the SP or give me contact details so I can retry the data and enjoy the content!

```
# lotus net connect f01908646
f01908646 -> {12D3KooWDr4AEQMuVqdhGFnC48vM1Vap5paan1yqsvpaF12yWwrf: [/ip4/74.211.110.65/tcp/59111]}
# telnet 74.211.110.65 59111
Trying 74.211.110.65...
Connected to 74.211.110.65.
Escape character is '^]'.
Connection closed by foreign host.

# lotus net connect f01908695
f01908695 -> {12D3KooWNCSRj6bx4yhfzaJZyx8Pj9jnj9FwResNZHMkRCp9SDwJ: [/ip4/212.50.250.232/tcp/59218]}
# telnet 212.50.250.232 59218
Trying 212.50.250.232...
Connected to 212.50.250.232.
Escape character is '^]'.
Connection closed by foreign host.

# lotus net connect f01941229
f01941229 -> {12D3KooWF7jrudF7k2tibthXrC2cyFrAMThm4qLbU4PRMFkj13JC: [/ip4/212.50.245.224/tcp/59112]}
# telnet 212.50.245.224
Trying 212.50.245.224...
telnet: Unable to connect to remote host: No route to host

# lotus net connect f01949065
f01949065 -> {12D3KooWDViFSHfrvC3usC8Nio9bJ6WbmrvoCgGiwDFw5ZCU7USE: [/ip4/173.242.116.70/tcp/59065]}
# telnet 173.242.116.70 59065
Trying 173.242.116.70...
telnet: Unable to connect to remote host: Connection refused

# lotus net connect f021695
f021695 -> {12D3KooWFbwEyLfARnZRR26DPJXw1v5tMQW63q2ybMVK8f4Tj69J: [/ip4/212.50.250.232/tcp/59204]}
# telnet 212.50.250.232 59204
Trying 212.50.250.232...
Connected to 212.50.250.232.
Escape character is '^]'.
Connection closed by foreign host.

# lotus net connect f01955058
f01955058 -> {12D3KooWRRsKt3q9XmisHgaxgv2uRnLnFRjbktCrMbLqzAxbiTob: [/ip4/173.242.116.70/tcp/55058]}
# telnet 173.242.116.70 55058
Trying 173.242.116.70...
telnet: Unable to connect to remote host: Connection refused
```

**Comment by mirsea888** [comment]
@lvschouwen Thanks for the reminder, I have received this issue and I will contact these SPs to ask them to fix it.

**Comment by Sunnyiscoming** [comment]
Hello, @mirsea888 per the https://github.com/filecoin-project/notary-governance/issues/922 for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

This information will be reviewed by Fil+ Governance team to confirm validity and then the application will be allowed to move forward for additional notary review.
