### ISSUE TITLE
[DataCap Allocation] - MoneyMaker FX EA

### ISSUE THREAD

**Issue by moneymakerfxea** [filecoin-project/filecoin-plus-large-datasets#1334]
---
name: Large Dataset Notary application
about: Clients should use this application form to request a DataCap allocation via a LDN for a dataset
title: "MoneyMaker FX EA"
labels: 'application, Phase: Diligence'
assignees: ''

---
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: MoneyMaker FX EA
- Website / Social Media: https://mmfx.vvip-members.com/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 300TiB
- On-chain address for first allocation: f3ratr7cmhlzjodcrwa2rqb56rtvg4dkqsc2naaeoaghlqc45zoyj6gdht6653vcdnvq6omw3fgrajuq45grfa
- Region: North America

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
We are a company that provides forex trading automation system service. 

The website address is below.
https://mmfx.vvip-members.com/
```

What is the primary source of funding for this project?
```
funds from the company's investors and Service usage fees for service users
```

What other projects/ecosystem stakeholders is this project associated with?
```
Forex trading investors
```

## Use-case details

Describe the data being stored onto Filecoin
```
We will store forex quote data from the past to the present and future.
And, we will save the transaction history of our forex trading automation
system.
Tick data, 1 minute data, 10 minutes data, 15 minutes data, 30 minutes
data, 1 hour data, 4 hours data, 8 hours data, 24 hours data, week data,
month data, year data, IMAGE FILES, VIDEO FILES, etc..
We are going to store very large amounts of data.
See attached sample data.
```

Where was the data in this dataset sourced from?
```
forex price history data : from forex market
Trading Hisoty / Videos/ Images : We made
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://www.youtube.com/channel/UCKabpz_S-WAIxtdLuNurDIA/shorts
https://www.youtube.com/channel/UCKabpz_S-WAIxtdLuNurDIA/videos
https://www.youtube.com/channel/UCKabpz_S-WAIxtdLuNurDIA/streams
https://www.youtube.com/channel/UCKabpz_S-WAIxtdLuNurDIA
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes Right
```

What is the expected retrieval frequency for this data?
```
2~3 times/year
```

For how long do you plan to keep this dataset stored on Filecoin?
```
4~5 years
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
North America and Asia
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
The total amount of data to be saved is about 5~7 PB. So, We are going to send our mass storage to the storage provider. (offline)
Some data will also be transferred online.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We plan to select a few reliable SPs for stable storage and retrieval of data.
```

How will you be distributing deals across storage providers?
```
We plan to select and distribute 5-6 SPs.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
There are sufficient funds, and no extra support is required.
```

**Comment by moneymakerfxea** [comment]
We do not know the details of the technical aspects of FILECOIN.
We have already provided data samples and more.
filecoin-project/filecoin-plus-client-onboarding#2502
<https://github.com/filecoin-project/filecoin-plus-client-onboarding/issues/2502>

We have our own IDC, and we already have complete backups of the data we
need.

A few months ago, officials from the FILECOIN PROVIDER vendor
association(?) contacted us saying they wanted to keep our data in
FILECOIN, so we decided to do so.

However, the application process is too complex and cumbersome.
Since we have already perfectly backed up our important data, there is no
need to store it in FILECOIN.
We no longer want to waste time on unnecessary tasks.

You may terminate the application process.
Thanks. Regards.


2022년 12월 7일 (수) 오전 11:45, Sunnyiscoming ***@***.***>님이 작성:

**Comment by Sunnyiscoming** [comment]
OK.
