### ISSUE TITLE
[DataCap Application] NOAA GEFS

### ISSUE THREAD

**Issue by Pierofree** [filecoin-project/filecoin-plus-large-datasets#1338]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: NOAA GEFS---Piero
- Website / Social Media: https://registry.opendata.aws/noaa-gefs/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 200TiB
- On-chain address for first allocation:f1p643cvpsvgy3zvwgjuij3kijdsb2umodvnrpgey

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
I have participated in hackathon projects and got a very good ranking.
```

What is the primary source of funding for this project?
```
By myself.
```

What other projects/ecosystem stakeholders is this project associated with?
```
No.
```

## Use-case details

Describe the data being stored onto Filecoin
```
The data contains the ensemble forecast data organized by day. The files are in GRIB2 format.
```

Where was the data in this dataset sourced from?
```
It is from Global Ensemble Forecast System (GEFS), previously known as the GFS Global ENSemble (GENS), which is a weather forecast model made up of 21 separate forecasts, or ensemble members. The National Centers for Environmental Prediction (NCEP) started the GEFS to address the nature of uncertainty in weather observations, which are used to initialize weather forecast models.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://registry.opendata.aws/noaa-gefs/
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Confirm.
```

What is the expected retrieval frequency for this data?
```
Minimally, at least every three months.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
540 days.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Asia, North America.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Both online and offline data transfer.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
I will send deals to those storage providers who have ability to support retrieval and stable seal.
```

How will you be distributing deals across storage providers?
```
I will distribute under 25% deals to every storage provider.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes.
```

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 200TiB

**Client address**

>f1p643cvpsvgy3zvwgjuij3kijdsb2umodvnrpgey

**Comment by cryptowhizzard** [comment]
Given the tracking history i recommend not signing this application.

https://github.com/filecoin-project/filecoin-plus-large-datasets/issues?q=is%3Aissue+Piero

![Scherm­afbeelding 2023-01-05 om 13 59 47](https://user-images.githubusercontent.com/36404435/210785655-5781549e-42a3-4f30-ab37-58ec41c536f3.png)

**Comment by lvschouwen** [comment]
@Pierofree 
You state that you have selected 3 SPs 
`Selected SPs: f01040469, f0838873, f0142637 `

The first has no IP listed on chain
`lotus net connect f01040469
f01040469 -> {12D3KooWQqYCoH9pbYw6qPMYYN9Tumx96EyrWqvmjdubWsPTM3Zf: []}`

The second is not reachable
`tus net connect f0838873
f0838873 -> {12D3KooWRmHEDgxXcFL5bDyEF793GEpU6kHjR1ohH5xKkRafPFif: [/ip4/83.229.35.241/tcp/54640]}
telnet 83.229.35.241 54640
Trying 83.229.35.241...
^C`

The third same problem
`lotus net connect f0142637
f0142637 -> {12D3KooWMsPmAA65yHAHgbxgh7CPkEctJHZMeM3rAvoW8CZKxtpG: [/ip4/110.186.65.5/tcp/23458]}
telnet 110.186.65.5 23458
Trying 110.186.65.5...
telnet: Unable to connect to remote host: Connection refused`

Please let us know why this is.

**Comment by cryptowhizzard** [comment]
Why should i do this? This is up to you.

If you can include my questions in it that would be welcome.

From there on, if you want I will forward it to our notary governance team for review and advice / guidance.

**Comment by BobbyChoii** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedfp6nejedogjr3w64wf6qiqbs4bxlyvvd2i3mg52ehyi3h45sn4i 
#### Address 
> f1p643cvpsvgy3zvwgjuij3kijdsb2umodvnrpgey
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1irqs2gmctiv3jcdfwuch7oxvf4ixh3k4b2wc24i
#### Id
> 7b06cf42-8963-42e8-ab12-427b0748c7c7
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedfp6nejedogjr3w64wf6qiqbs4bxlyvvd2i3mg52ehyi3h45sn4i

**Comment by TakiChain** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebwd7iqw3g35aepz76dzwpuixiufehv7asjyei7rak4grhbshu5dg 
#### Address 
> f1p643cvpsvgy3zvwgjuij3kijdsb2umodvnrpgey
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f15impf3j2zcaex4lhyxndxswuuhv24vzstuqtxsi
#### Id
> 7b06cf42-8963-42e8-ab12-427b0748c7c7
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebwd7iqw3g35aepz76dzwpuixiufehv7asjyei7rak4grhbshu5dg

**Comment by Protocan** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacednld5ofxta22os5gawe6dqbnil62jbimrgyu43gktlhmjpmdry3q 
#### Address 
> f1p643cvpsvgy3zvwgjuij3kijdsb2umodvnrpgey
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1vxbqrf7rfum3n6m5u6eb4re6xj7amvsaqnzu64y
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacednld5ofxta22os5gawe6dqbnil62jbimrgyu43gktlhmjpmdry3q

**Comment by Meibuy** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceanaxzgcvipkfdljpgzfz67plkgtjrizs6txf5smt6ry7mufvbtz4 
#### Address 
> f1p643cvpsvgy3zvwgjuij3kijdsb2umodvnrpgey
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1bwugfihrmn3iyunzyxst5nttql3dge4khwmurtq
#### Id
> 1bc6339f-ba1b-4bda-8104-961eae07dba3
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceanaxzgcvipkfdljpgzfz67plkgtjrizs6txf5smt6ry7mufvbtz4

**Comment by Meibuy** [comment]
Good summary report and ongoing communication from the applicant. We would like to see more and more useful datasets get onboarded.

**Comment by BobbyChoii** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedii7hmfndnub6lbmixh3u234meysfyserippti2papqaaizfgeea 
#### Address 
> f1p643cvpsvgy3zvwgjuij3kijdsb2umodvnrpgey
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1irqs2gmctiv3jcdfwuch7oxvf4ixh3k4b2wc24i
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedii7hmfndnub6lbmixh3u234meysfyserippti2papqaaizfgeea

**Comment by BobbyChoii** [comment]
There're lots of inputs from many notaries and reasonable responses from the applicant. I'm willing to give my sign and help to onboard this application.

**Comment by Pierofree** [comment]
checker:manualTrigger

**Comment by cryptowhizzard** [comment]
Hello @Pierofree 

It seems that you are still not following the FIl+ rules and guidelines, despite you have been given a second and third chance by the community. Nothing of the data is retrievable of the things that you are storing and most of your SP's have been flagged in applications #1556 #1557 #1558 #1559 for rampant abuse and CID sharing.

Can you enlighten us what the reason is this time that things went so wrong?

![Scherm­afbeelding 2023-08-03 om 13 38 16](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/36404435/530ef229-7b74-4206-85f5-30517282ed94)

**Comment by Pierofree** [comment]
Hello @cryptowhizzard 
If there is any abuse of these SPs working with me in my application, feel free to mark it here.
If there is abuse between these Sps and other client, please leave here to go to their applications and remind them.
Thank you

**Comment by cryptowhizzard** [comment]
> Hello @cryptowhizzard
> If there is any abuse of these SPs working with me in my application, feel free to mark it here.
> If there is abuse between these Sps and other client, please leave here to go to their applications and remind them.
> Thank you

Very intelligent. So you mean that the SP enables retrieval on your applications but disabled them on yours? 

That’s good stuff!

**Comment by Pierofree** [comment]
1. We can only be responsible for matters under our control;
2. Please do not ask for what are not related to us.
Please respect each other. Thank you.

**Comment by cryptowhizzard** [comment]
> * We can only be responsible for matters under our control;
> * Please do not ask for what are not related to us.
>   Please respect each other. Thank you.

Do these support retrieval now or don’t they?
Who are they?

**Comment by Pierofree** [comment]
You can check it on the retrieval report. Thank you.

**Comment by cryptowhizzard** [comment]
This applicant has a long fraudulent history and is still not working with SP's who support retrieval / on the right track.

<img width="713" alt="Scherm­afbeelding 2023-08-19 om 17 04 57" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/36404435/7beeb934-ad77-4359-86d9-2feb68b293b6">

**Comment by Pierofree** [comment]
checker:manualTrigger

**Comment by Pierofree** [comment]
> This applicant has a long fraudulent history and is still not working with SP's who support retrieval / on the right track.
> 
> <img alt="Scherm­afbeelding 2023-08-19 om 17 04 57" width="713" src="https://user-images.githubusercontent.com/36404435/261804979-7beeb934-ad77-4359-86d9-2feb68b293b6.png">

@cryptowhizzard Please apologize to me for your rude behavior.

**Comment by cryptowhizzard** [comment]
> > This applicant has a long fraudulent history and is still not working with SP's who support retrieval / on the right track.
> > <img alt="Scherm­afbeelding 2023-08-19 om 17 04 57" width="713" src="https://user-images.githubusercontent.com/36404435/261804979-7beeb934-ad77-4359-86d9-2feb68b293b6.png">
> 
> @cryptowhizzard Please apologize to me for your rude behavior.

Lol

![Scherm­afbeelding 2023-08-28 om 11 48 37](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/36404435/5beaedfd-4d06-49f4-b603-a041a33b353d)

http://www.datasetcreators.com/downloadedcarfiles/httpretrievals/1338-f01980913-f02184300-51485029-baga6ea4seaqazgjok36tbzuqgz3rnls65gsgpefsujqjbxqrfbalbgdmfdkvspq

You should apologize to the community for storing crap data, again and again.

**Comment by Pierofree** [comment]
@cryptowhizzard What is it? It isn't what we stored. You should apologize to me, again and again.

**Comment by cryptowhizzard** [comment]
Read the manual. Please do not tag me until you know the meaning of immutability, Filecoin , data preparer and service provider.

**Comment by raghavrmadya** [comment]
Hi, I'm following up based on the dispute submitted here - https://www.notion.so/filecoin/No-retrieval-supported-09b72f2153df46b9b1a7a0e1fa4a32f2?pvs=4

@Pierofree , if you are not satisfied with the evidence shared by @cryptowhizzard , kindly share evidence of data stored. I would also like to flag that the Deal Data Replication is concerning. 

Until the dispute is resolved, notaries are encouraged to not sign further.

**Comment by Pierofree** [comment]
@raghavrmadya Yes, I'm not satisfied with that notary's evidence. What his picture shown is not a normal car file. My answer is different with him. The truth is that he displayed wrong result and thought that is my car file. I'm not responsible for his mistakes.

This dispute should be removed from my application.

**Comment by cryptowhizzard** [comment]
Dear Pierofree,

As notary I am doing due diligence on your LDN. I could not get retrieval to work. Can you please upload the car file of CID baga6ea4seaqe3hi47tyd3jkfehf7h4uel756nbsmdtlgryhfreruhfgdzqyikai ?

You can use our upload system at http://send.datasetcreators.com. Please select 7 days for the system to keep the file and post the link you received here so I (and other notaries) can download your content.

**Comment by cryptowhizzard** [comment]
"This dispute should be removed from my application."

Prove me wrong and upload the data so we can check it.

**Comment by Pierofree** [comment]
Actually I have proved that we stored is normal car file, not the same as yours.

**Comment by Sunnyiscoming** [comment]
Hello, @Pierofree per the https://github.com/filecoin-project/notary-governance/issues/922 for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

This information will be reviewed by Fil+ Governance team to confirm validity and then the application will be allowed to move forward for additional notary review.
