### ISSUE TITLE
Xiamen Minkuang Survey & Mapping Institute 

### ISSUE THREAD

**Issue by minkuangcehui** [filecoin-project/filecoin-plus-large-datasets#1339]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Xiamen Minkuang Survey & Mapping Institute 
- Website / Social Media:http://www.xmmkchy.com/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):3 PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):100TiB
- On-chain address for first allocation:f1jp5lf5ysd27zykkmgpu3ejqxbndr3k4qfb5mxny

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Xiamen Minkuang Survey & Mapping Institute is a professional team that has transformed from geological surveying and surveying to market surveying and technical services for land resources. It is affiliated to the Fujian West Fujian Geological Brigade. Aerial photography, land resources technology, land planning, agricultural engineering design services as the main business of professional teams.
  Over the years, it has always adhered to the service tenet of "quality first, reputation first"; the first company involved in real estate surveying and mapping in Xiamen, the first to develop 3D laser scanning measurement technology in Fujian, and many surveying and mapping projects have won provincial and ministerial excellent engineering awards; In the field of national economic construction, it provides high-quality services and is highly praised by users.
```

What is the primary source of funding for this project?
```
From our corporate shareholders.
```

What other projects/ecosystem stakeholders is this project associated with?
```
No.
```

## Use-case details

Describe the data being stored onto Filecoin
```
Inspection and measurement videos, photos
A large number of promotional video materials
```

Where was the data in this dataset sourced from?
```
Inspection and measurement video, the photos are from the actual measurement records
A large number of promotional videos come from partner promotional video materials
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://drive.google.com/drive/folders/1x9sU974qBymj9LJJr8HeGWrDzxxB48Ni?usp=sharing
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes, Confirm 
It is a public data. 
```

What is the expected retrieval frequency for this data?
```
Once a year.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
I think it's a permanent archival, and we'll constantly update our data stored on Filecoin.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Europe, United States, Australia or any other SPs that are interested.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
offline.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We will  find SPs on Filecoin slack, and Filgram.
And storage providers who are willing to make deals with us are welcome.
```

How will you be distributing deals across storage providers?
```
Hosting files online where storage providers can download them.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Sure, we have. 
```

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 3PiB

**Expected weekly DataCap usage rate**

> 100TiB

**Client address**

>f1jp5lf5ysd27zykkmgpu3ejqxbndr3k4qfb5mxny

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

As last question i would like you to fill out [this form](https://form.jotform.com/230337462961356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!
