### ISSUE TITLE
[DataCap Application] <LEMURIA>

### ISSUE THREAD

**Issue by pengt325** [filecoin-project/filecoin-plus-large-datasets#1342]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: LEMURIA
- Website / Social Media:https://www.miracles.games 
Discord：https://discord.gg/EnsvSAVZCv 
Twitter：https://twitter.com/0xMiracleGame
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):5 PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):100TiB
- On-chain address for first allocation:f16vgwhyalvquucsfojgveavpkbydoab4zvi6osya

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
In January 2017, Jinke Culture and Outfit7 reached a strategic cooperation, including film,television, animation, games, cultural entertainment
consumption and theme parks. At the same time, Jinke Culture has won the Outfit7 "Talking Family"
Licensing of series IP, including game development, game distribution, advertising, derivative development and sales, video content production, etc.
"My Tom Cat", "My Angela", "My Hank Dog" and "Tom Cat Parkour" ,four games as a series of TOM CAT entertainment game, have shown active data and large downloads. The key role is to grasp the scale of the players and different characteristics to promote the advertisement and perfect the game, as well as additional IP production. 
Four casual games of the Mu Mao IP series. Since going live, active data and downloads have performed well, so it is necessary to pass
By understanding the overall core player size of the four games, the size of derived players, and the characteristics of different types of players to help the game
The development of the game and the post-marketing promotion work, as well as the production of extended content related to IP derivatives.

What is the primary source of funding for this project?
```
We currently have two main sources of funding
1. Own funds;
2. Business Income.

What other projects/ecosystem stakeholders is this project associated with?
```
A. As for the platform users, we mainly have an interest relationship with the users who use the platform to trade NFT.
B. As for artists and brands, we currently work with well-known NFT creative artists and brands to help them publish NFT works on our platform.
C. As for advertisers, we will cooperate with different advertisers to make them launch and publicize on the platform.

## Use-case details

Describe the data being stored onto Filecoin
```
The data stored on Filecoin is currently basically the data of MU applications.

Where was the data in this dataset sourced from?
```
Mainly from Tom cat, MU games and other projects.

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://www.mediafire.com/view/oxnhnw8el3wneik/NFT_girl.jfif/file
[https://www.mediafire.com/file/nu2o7v3cv5bpndi/NFT_boy.webp/file](https://www.mediafire.com/view/oxnhnw8el3wneik/NFT_girl.jfif/file)
[https://www.mediafire.com/view/4wi828ugfy27vfv/NFT_chicken.jfif/file](https://www.mediafire.com/view/oxnhnw8el3wneik/NFT_girl.jfif/file)
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Currently the data we stored is based on publicly available data from applications or clients, so we make sure that this is a publicly retrievable public dataset.

What is the expected retrieval frequency for this data?
```
We basically do not need to search, sometimes it is up to clients for special condition.

For how long do you plan to keep this dataset stored on Filecoin?
```
The data we stored on Filecoin is subject to application needs and business needs, and we plan to store data for 540 days now. 


## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Asia, Europe, North America

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Mostly we will distribute to miners online. If there are some special circumstances, we would use offline methods.

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
The miners we choose shale have a good reputation record. Meanwhile we will do a regular tracking of miners. For those miners who have a good performance ,we will cooperate with them for a long time.

How will you be distributing deals across storage providers?
```
We plan to distribute evenly to miners, each miner will be allocated as 20% of our dataCap

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
We have sufficient resources and funds that can start now.

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 100TiB

**Client address**

>f16vgwhyalvquucsfojgveavpkbydoab4zvi6osya

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Looking at your application i have some questions:
As you are brand new on Github and have no history of past applications it seems to me that applying for 5PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?

Can you show us visible proof of the size of your data and the storage systems you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230232885049356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!
