### ISSUE TITLE
[DataCap Application] <BEIJING Testor Technology Co., Ltd.> - <Emergency earthquake command and rescue>

### ISSUE THREAD

**Issue by choclate879** [filecoin-project/filecoin-plus-large-datasets#1343]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: BEIJING Testor Technology Co., Ltd.
- Website / Social Media:https://www.testor.com.cn/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):200TiB
- On-chain address for first allocation:f16tmjsviuhzdyxnowcpfrwz7iamzcmerlilm4mky

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Beijing Testor Technology Co., Ltd., founded in 2003, is a leading provider of solutions for the communication network, smart emergency and industrial Internet industries in China. We are committed to providing government and enterprise customers with advanced and reliable products and solutions, deeply understanding customer application scenarios, helping customers tap the value of data, realizing the transformation from owning data to owning capabilities, and making customers' businesses safe, efficient Rich.
```

What is the primary source of funding for this project?
```
Project Income
```

What other projects/ecosystem stakeholders is this project associated with?
```
None
```

## Use-case details

Describe the data being stored onto Filecoin
```
The data are mainly satellite remote sensing image data and monitoring data
```

Where was the data in this dataset sourced from?
```
Data generated by the Company in conducting its business.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
Link：https://pan.baidu.com/s/1ZiFIcgx9Rh079V2qS-Oa8A 
Extraction code：v7jh 
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes,it is
```

What is the expected retrieval frequency for this data?
```
No frequent retrieval is required. 1-2 times a year
```

For how long do you plan to keep this dataset stored on Filecoin?
```
5 years
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
China
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Depending on the location of the storage provider, both online and offline modes are used.Online, we upload data to the cloud storage provider's server and send download URL to each other. Offline, we will send physical storage devices by express.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
In order to ensure data security, we will select 3 or more storage providers and require storage providers to be able to quickly retrieve
```

How will you be distributing deals across storage providers?
```
We will distribute them equally to the high-quality storage providers that pass our audit.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
The company will have a special fund to pay all expenses.
```

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 200TiB

**Client address**

>f16tmjsviuhzdyxnowcpfrwz7iamzcmerlilm4mky

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Looking at your application i have some questions:
As you are brand new on Github and have no history of past applications it seems to me that applying for 5PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?

Your application is for 5PB of datacap. Can you show us visible proof of the size of your data and the storage systems you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230232885049356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!
