### ISSUE TITLE
[DataCap Application] <Daxiancloud> - <Daxiancloud>

### ISSUE THREAD

**Issue by caokun8341** [filecoin-project/filecoin-plus-large-datasets#1346]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: daxiancloud
- Website / Social Media: https://daxiancloud.com/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 400TiB
- On-chain address for first allocation: f15vyr6e7wuizomrsxbregxwuxmvwrrccjdkkamza

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Beijing Daxian Technology Co., Ltd. is a professional intelligent sales service SaaS provider. "Daxian Cloud" is an industry-oriented intelligent sales and customer acquisition Saas platform, dedicated to helping enterprises tap the procurement opportunities and channel resources of major customers in the industry, and empowering enterprises through big data and AI technology. The founder, Qu Wei, graduated from Wuhan University and received an EMBA from Tsinghua SEM. He is a big data expert and the founder of the original Redmai Software. In 2015, he was successfully acquired by the listed company Beyondsoft. In the past 13 years, he has been deeply cultivating enterprise-level data applications and focusing on mining the value of big data.

Beijing Daxian Technology Co., Ltd. has established a professional team. The core members of the team have worked for well-known domestic companies such as Sina Weibo, Kuaishou, AVIC International, and China Digital. The team members have decades of SaaS-related working background and have With strong big data analysis ability and rich experience in project management, he is an expert in product, technology, data and sales industries. Daxian focuses on in-depth mining of customer acquisition data resources in subdivided industries, and has a comprehensive layout in industries such as education, medical care, finance, energy, transportation, and government, helping companies find accurate customers and core channels, understand market conditions, and rationally allocate sales resources.
```

What is the primary source of funding for this project?
```
Company Product Earnings and Investments.
```

What other projects/ecosystem stakeholders is this project associated with?
```
None.
```

## Use-case details

Describe the data being stored onto Filecoin

```
1.Industry-wide big data and processed cached data。
2.saas system data.
```

Where was the data in this dataset sourced from?
```
Big data generated and analyzed by the company's internal saas system.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://drive.google.com/file/d/1ttQR_yncsh4t8_l78lW1IFr17alQPa26/view?usp=share_link
https://drive.google.com/file/d/1zeF6-e0xa6z67yGbWj-vGLuVgpz7dwE0/view?usp=share_link
https://drive.google.com/file/d/14LklZq_xOFoVMQ3lVEkCbZaQ2PZKNYzj/view?usp=share_link
https://drive.google.com/file/d/19PMYebIruqmir6Wo8DFFLS3u_6SOQ4h1/view?usp=share_link
https://drive.google.com/file/d/1l3aALJ7cmQeOMD_1J72U3vkbhhmdsFi5/view?usp=share_link
https://drive.google.com/file/d/1qEZS2ngSpRRZu-SvNQXe5I-Ma0Jbj3QI/view?usp=share_link
```

Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes, we're pretty sure.
```

What is the expected retrieval frequency for this data?
```
1-2 times a year.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
Minimum 540 days.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Hong Kong or America.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Online download or offline mailing.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We prefer storage service providers with higher reliability.
```

How will you be distributing deals across storage providers?
```
Store to multiples SPs.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes.
```

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 400TiB

**Client address**

> f15vyr6e7wuizomrsxbregxwuxmvwrrccjdkkamza

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Looking at your application i have some questions:
As you are brand new on Github and have no history of past applications it seems to me that applying for 5PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?

Can you show us visible proof of the size of your data and the storage systems you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230337462961356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!

**Comment by caokun8341** [comment]
> Dear applicant,
> 
> Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.
> 
> Looking at your application i have some questions: As you are brand new on Github and have no history of past applications it seems to me that applying for 5PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?
> 
> Can you show us visible proof of the size of your data and the storage systems you have there?
> 
> As last question i would like you to fill out [this form](https://form.jotform.com/230337462961356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.
> 
> Thanks!

@cryptowhizzard Hello, We have submitted the KYC information of LDN, thank you!
<img width="768" alt="image" src="https://user-images.githubusercontent.com/34340092/221742562-26f0597f-c74b-455b-b744-b8514f50be3a.png">

**Comment by caokun8341** [comment]
@cryptowhizzard Hello, could you sign for us, please? Thank you!

**Comment by cryptowhizzard** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebfqkndlqimt4dcn2pzlauxrqrzc3uzlfcxenqgiujeenc4c3p2h2 
#### Address 
> f15vyr6e7wuizomrsxbregxwuxmvwrrccjdkkamza
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1krmypm4uoxxf3g7okrwtrahlmpcph3y7rbqqgfa
#### Id
> 00b21649-cb07-4ca4-b61c-0801bc6ce35f
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebfqkndlqimt4dcn2pzlauxrqrzc3uzlfcxenqgiujeenc4c3p2h2

**Comment by cryptowhizzard** [comment]
Well received. Looking forward to your first milestone!

**Comment by metacodebean** [comment]
checker:manualTrigger

**Comment by luobin544** [comment]
checker:manualTrigger

**Comment by luobin544** [comment]
![15521686108329_ pic](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/4277341/17c4f1ff-4e68-4773-b6f1-f005e7bf5996)

**Comment by luobin544** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceborsjdwitoy2m7looz6x4q5sunun3lpjzyqjpgtileuij4v5llki 
#### Address 
> f15vyr6e7wuizomrsxbregxwuxmvwrrccjdkkamza
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1tbd632f6w62glfaf7wjpimacbnjiz26poyoes2q
#### Id
> 03e0434a-54ac-4bea-a6f8-cc81deb821a1
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceborsjdwitoy2m7looz6x4q5sunun3lpjzyqjpgtileuij4v5llki

**Comment by SuperChaiChai** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebaatbknc4auamcctbumv3smgbntqsm44oodbkxerwnwefblpugcg 
#### Address 
> f15vyr6e7wuizomrsxbregxwuxmvwrrccjdkkamza
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f12mckci3omexgzoeosjvstcfxfe4vqw7owdia3da
#### Id
> 03e0434a-54ac-4bea-a6f8-cc81deb821a1
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebaatbknc4auamcctbumv3smgbntqsm44oodbkxerwnwefblpugcg

**Comment by SuperChaiChai** [comment]
More SPs need to be added
If you need help contacting SP, you can contact me

**Comment by dongpo313** [comment]
checker:manualTrigger

**Comment by dongpo313** [comment]
checker:manualTrigger

**Comment by dongpo313** [comment]
checker:manualTrigger

**Comment by dongpo313** [comment]
checker:manualTrigger

**Comment by dongpo313** [comment]
checker:manualTrigger

**Comment by dongpo313** [comment]
checker:manualTrigger

**Comment by caokun8341** [comment]
We are still using this Ldn, please do not close it, thank you

**Comment by mingyang313** [comment]
checker:manualTrigger

**Comment by caokun8341** [comment]
We are still using this Ldn, please do not close it, thank you

**Comment by caokun8341** [comment]
We are still using this Ldn, please do not close it, thank you

**Comment by caokun8341** [comment]
We are still using this Ldn, please do not close it, thank you

**Comment by caokun8341** [comment]
We have found the right SP, and we will start storing project data soon.

**Comment by lingsucheng** [comment]
checker:manualTrigger

**Comment by caokun8341** [comment]
We have found the right SP, and we will start storing project data soon.

**Comment by mingyang313** [comment]
checker:manualTrigger

**Comment by cryptowhizzard** [comment]
![Scherm­afbeelding 2023-09-05 om 14 31 20](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/36404435/b367d6fa-541b-462e-9ab1-0b18d1942e3b)

Only 2 of the 4 miners you work with are online :(

**Comment by caokun8341** [comment]
> ![Scherm­afbeelding 2023-09-05 om 14 31 20](https://user-images.githubusercontent.com/36404435/265698240-b367d6fa-541b-462e-9ab1-0b18d1942e3b.png)
> 
> Only 2 of the 4 miners you work with are online :(

hello @cryptowhizzard We are contacting sp for processing, it will take some time, thank you.

**Comment by mingyang313** [comment]
checker:manualTrigger

**Comment by cryptowhizzard** [comment]
Still no change here. Only one SP is open for connection.

<img width="1273" alt="Scherm­afbeelding 2023-09-12 om 09 11 19" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/36404435/2747b6be-eec6-4b9f-9737-ed068b46113b">

**Comment by caokun8341** [comment]
Our ldn is still in use, please do not close it.We are looking for SPs of high quality.

**Comment by Tom-OriginStorage** [comment]
The package is basically healthy, and there are a few CID sharing applicants who say they will pay attention to it in the future,

**Comment by Tom-OriginStorage** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecrybts4kgi5ln3vbk2zzjiygdprc4t7hwmrz2pmnb2yf2j5b2q6w 
#### Address 
> f15vyr6e7wuizomrsxbregxwuxmvwrrccjdkkamza
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1q6bpjlqia6iemqbrdaxr2uehrhpvoju3qh4lpga
#### Id
> 1b2777c0-503f-4936-b7ff-189b4d8c26d4
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecrybts4kgi5ln3vbk2zzjiygdprc4t7hwmrz2pmnb2yf2j5b2q6w

**Comment by caokun8341** [comment]
Our ldn is still in use, please do not close it.Thanks.

**Comment by caokun8341** [comment]
Regarding the connection, I have already contacted the service provider to address the issue. However, considering the availability, I have also reached out to a new service provider.

**Comment by mingyang313** [comment]
checker:manualTrigger

**Comment by mingyang313** [comment]
checker:manualTrigger

**Comment by luobin544** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebde7s7bx5t36gacmdz2mpyh6vegb2vqre6ki7l5kh2qarsid2xzg 
#### Address 
> f15vyr6e7wuizomrsxbregxwuxmvwrrccjdkkamza
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1tbd632f6w62glfaf7wjpimacbnjiz26poyoes2q
#### Id
> 1b2777c0-503f-4936-b7ff-189b4d8c26d4
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebde7s7bx5t36gacmdz2mpyh6vegb2vqre6ki7l5kh2qarsid2xzg

**Comment by Sunnyiscoming** [comment]
Hello, @caokun8341 per the https://github.com/filecoin-project/notary-governance/issues/922 for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

This information will be reviewed by Fil+ Governance team to confirm validity and then the application will be allowed to move forward for additional notary review.

**Comment by caokun8341** [comment]
> > Dear applicant,
> > Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.
> > Looking at your application i have some questions: As you are brand new on Github and have no history of past applications it seems to me that applying for 5PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?
> > Can you show us visible proof of the size of your data and the storage systems you have there?
> > As last question i would like you to fill out [this form](https://form.jotform.com/230337462961356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.
> > Thanks!
> 
> @cryptowhizzard Hello, We have submitted the KYC information of LDN, thank you! <img alt="image" width="768" src="https://user-images.githubusercontent.com/34340092/221742562-26f0597f-c74b-455b-b744-b8514f50be3a.png">

Hello @Sunnyiscoming The kyc form has been completed before. Kyc has been completed before the table.

**Comment by caokun8341** [comment]
Hello @Sunnyiscoming The kyc form has been completed.

> Hello, @caokun8341 per the [filecoin-project/notary-governance#922](https://github.com/filecoin-project/notary-governance/issues/922) for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.
> 
> This information will be reviewed by Fil+ Governance team to confirm validity and then the application will be allowed to move forward for additional notary review.

**Comment by mingyang313** [comment]
checker:manualTrigger

**Comment by mikezli** [comment]
Can you explain the emergence of CID?

**Comment by caokun8341** [comment]
> Can you explain the emergence of CID?
Hello @mikezli We have the same SP client as them. During the data preparation process, the SP client got confused about some things. We have now terminated our collaboration with this SP. Please continue to monitor the situation.

**Comment by caokun8341** [comment]
> Can you explain the emergence of CID?

Hello @mikezli We have the same SP client as them. During the data preparation process, the SP client got confused about some things. We have now terminated our collaboration with this SP. Please continue to monitor the situation.

**Comment by mikezli** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecsllusrxd6tsmye32twzrc6tf4bignwrb6b3awhsz2rjnpputl4i 
#### Address 
> f15vyr6e7wuizomrsxbregxwuxmvwrrccjdkkamza
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1dnb3uz7sylxk6emti3ififcvu3nlufnnsjui6ea
#### Id
> 1b2777c0-503f-4936-b7ff-189b4d8c26d4
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecsllusrxd6tsmye32twzrc6tf4bignwrb6b3awhsz2rjnpputl4i

**Comment by sxxfuture-official** [comment]
checker:manualTrigger

**Comment by sxxfuture-official** [comment]
> > Can you explain the emergence of CID?
> 
> Hello @mikezli We have the same SP client as them. During the data preparation process, the SP client got confused about some things. We have now terminated our collaboration with this SP. Please continue to monitor the situation.

In view of this, hope that the CID non-sharing principle will be followed in the next.

**Comment by sxxfuture-official** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacea5t2ou2ulzjih3u6hih2coevg535ci4cibh6noj53izwknfbdkzw 
#### Address 
> f15vyr6e7wuizomrsxbregxwuxmvwrrccjdkkamza
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1foiomqlmoshpuxm6aie4xysffqezkjnokgwcecq
#### Id
> 1b2777c0-503f-4936-b7ff-189b4d8c26d4
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacea5t2ou2ulzjih3u6hih2coevg535ci4cibh6noj53izwknfbdkzw

**Comment by ipollo00** [comment]
checker:manualTrigger

**Comment by 1ane-1** [comment]
Hope you can improve your  retrieval rate. And the CID sharing problem explained before, i will keep following it.

**Comment by ipollo00** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecw62aqsflxxyukq4nqwvnghhxlz4sj75tc3iiahgsrokjskddom2 
#### Address 
> f15vyr6e7wuizomrsxbregxwuxmvwrrccjdkkamza
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1n5wlrrhoxpkgwij25xrtt7w7g2k3fhbthmdn6ri
#### Id
> 1b2777c0-503f-4936-b7ff-189b4d8c26d4
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecw62aqsflxxyukq4nqwvnghhxlz4sj75tc3iiahgsrokjskddom2

**Comment by caokun8341** [comment]
The following is a list of SPs we want to work with：
f02831201  Juwu Mine Guangzhou, Guangdong
f02831202 Juwu Mine Guangzhou, Guangdong
f02824533 Coffee Cloud HK
 f02837094 Coffee Cloud HK
f02833198 Coffee Cloud HK
f02824140 cylinder Ningxia
f02816081 KRAL Singapore
f02816095 KRAL Singapore
f02829200 applecould   jiangxi

**Comment by 87103978** [comment]
checker:manualTrigger

**Comment by herrehesse** [comment]
@caokun8341 

f02831201 Juwu Mine Guangzhou, Guangdong
f02831202 Juwu Mine Guangzhou, Guangdong
f02824533 Coffee Cloud HK
f02837094 Coffee Cloud HK
f02833198 Coffee Cloud HK
f02824140 cylinder Ningxia
f02816081 KRAL Singapore
f02816095 KRAL Singapore
f02829200 applecould jiangxi


These are all the same entity and the same datacenter using VPN. Why are you trying to abuse FIL+?

**Comment by 87103978** [comment]
At least three different regions, with at least four SPs, is my understanding not comprehensive?

**Comment by caokun8341** [comment]
After receiving your message, we immediately contacted SP,SP and firmly told us that they did not use VPN, the addresses were all real, and we verified by technical means that SP was not lying. If SP does use VPN, we will no longer work with them. So, if you think they used VPN, please list the detailed evidence.

**Comment by a1991car** [comment]
checker:manualTrigger

**Comment by nj-steve** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedb7allw3zshnryle646rjkg5kw2zigfhea4qlaekjorwszcmu2e6 
#### Address 
> f15vyr6e7wuizomrsxbregxwuxmvwrrccjdkkamza
#### Datacap Allocated
> 1.56PiB
#### Signer Address
> f1xx6555qijma7igpnjspyvdunc4vfxkawnpqy5ii
#### Id
> b360d338-49c5-4d63-b20e-c0691ed0d26a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedb7allw3zshnryle646rjkg5kw2zigfhea4qlaekjorwszcmu2e6

**Comment by a1991car** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebgnvn3dadyuumf2tjt45d75b6kfnfidx2q5mit2sdwdnqjqsyhpm 
#### Address 
> f15vyr6e7wuizomrsxbregxwuxmvwrrccjdkkamza
#### Datacap Allocated
> 1.56PiB
#### Signer Address
> f1qnumecdypgrbaebtkdfjnwt5ndacadcuas3deiq
#### Id
> b360d338-49c5-4d63-b20e-c0691ed0d26a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebgnvn3dadyuumf2tjt45d75b6kfnfidx2q5mit2sdwdnqjqsyhpm

**Comment by a1991car** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced775gdis2alwhjs7ju44m3sgvbr4vg4ide324svdxq6q3uz7mlys 
#### Address 
> f15vyr6e7wuizomrsxbregxwuxmvwrrccjdkkamza
#### Datacap Allocated
> 1.56PiB
#### Signer Address
> f1qnumecdypgrbaebtkdfjnwt5ndacadcuas3deiq
#### Id
> b360d338-49c5-4d63-b20e-c0691ed0d26a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced775gdis2alwhjs7ju44m3sgvbr4vg4ide324svdxq6q3uz7mlys

**Comment by Sunnyiscoming** [comment]
Hello, @caokun8341 per the https://github.com/filecoin-project/notary-governance/issues/922 for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

This information will be reviewed by Fil+ Governance team to confirm validity and then the application will be allowed to move forward for additional notary review.

**Comment by woshidama323** [comment]
checker:manualTrigger

**Comment by woshidama323** [comment]
Looks healthy and CID sharing issue has been explained 
Will support

**Comment by Filplus-govteam** [comment]
checker:manualTrigger

**Comment by Filplus-govteam** [comment]
SPs taking deals:
2812781 | Hanoi, Hanoi, VN365 Online technology joint stock company | 6.81 TiB | 0.50% | 6.81 TiB | 0.00%
f01302188 | Zhengzhou, Henan, CNCHINA UNICOM China169 Backbone | 196.97 TiB | 14.42% | 191.41 TiB | 2.82%
f02824140 | Shenzhen, Guangdong, CNCHINA UNICOM China169 Backbone | 40.59 TiB | 2.97% | 40.59 TiB | 0.00%
f02190189 | Hangzhou, Zhejiang, CNCHINANET-BACKBONE | 124.53 TiB | 9.12% | 124.13 TiB | 0.33%
f0155829 | Hangzhou, Zhejiang, CNCHINANET-BACKBONE | 114.28 TiB | 8.37% | 114.19 TiB | 0.08%
f02086562new | Wuhan, Hubei, CNCHINANET-BACKBONE | 109.13 TiB | 7.99% | 106.22 TiB | 2.66%
f02831201 | Shenzhen, Guangdong, CNCHINANET-BACKBONE | 63.84 TiB | 4.67% | 63.84 TiB | 0.00%
f02831202 | Shenzhen, Guangdong, CNCHINANET-BACKBONE | 63.63 TiB | 4.66% | 63.63 TiB | 0.00%
f02829200 | Nanchang, Jiangxi, CNCHINANET-BACKBONE | 34.38 TiB | 2.52% | 34.38 TiB | 0.00%
f02833198 | Hong Kong, Central and Western, HKHK Broadband Network Ltd. | 46.53 TiB | 3.41% | 46.50 TiB | 0.07%
f02824533 | Hong Kong, Central and Western, HKHK Broadband Network Ltd. | 35.44 TiB | 2.59% | 35.44 TiB | 0.00%
f02837094 | Hong Kong, Central and Western, HKHK Broadband Network Ltd. | 31.06 TiB | 2.27% | 31.06 TiB | 0.00%
f02811783 | London, England, GBHydra Communications Ltd | 71.97 TiB | 5.27% | 70.94 TiB | 1.43%
f02813403 | London, England, GBHydra Communications Ltd | 68.34 TiB | 5.00% | 67.63 TiB | 1.05%
f02828509 | Seoul, Seoul, KRKIDC Limited | 75.22 TiB | 5.51% | 74.19 TiB | 1.37%
f02824257 | Singapore, Singapore, SGOVH SAS | 80.31 TiB | 5.88% | 79.22 TiB | 1.36%
f02825197 | Manila, Metro Manila, PHZenlayer Inc | 75.22 TiB | 5.51% | 74.28 TiB | 1.25%
f02814393 | Los Angeles, California, USZenlayer Inc | 66.34 TiB | 4.86% | 65.66 TiB | 1.04%
f02816081 | Singapore, Singapore, SGZenlayer Inc | 34.31 TiB | 2.51% | 34.31 TiB | 0.00%
f02816095 | Singapore, Singapore, SGZenlayer Inc | 27.25 TiB | 1.99% | 27.25 TiB | 0.00%

**Comment by mingyang313** [comment]
checker:manualTrigger

**Comment by caokun8341** [comment]
Hello @Sunnyiscoming @kevzak The following figure lists the information of all the sps we have worked with. I hope you can open the ldn. Thank you very much!
![1346](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/34340092/ea37ef4c-24e4-4949-baf1-8568371acd75)

**Comment by caokun8341** [comment]
Hello @Sunnyiscoming @kevzak The following figure lists the information of all the sps we have worked with. I hope you can open the ldn. Thank you very much!
1346

**Comment by caokun8341** [comment]
Hello @Sunnyiscoming @kevzak The following figure lists the information of all the sps we have worked with. I hope you can open the ldn. Thank you very much!
![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/34340092/be75b5cc-1c7b-437b-a9e5-c5285782caaa)

**Comment by Filplus-govteam** [comment]
@caokun8341 please provide proof of SP entity and distributed locations. A list of IDs and locations doesn't validate your application is meeting the Fil+ guidelines.

**Comment by caokun8341** [comment]
Many service providers are contacted through WeChat. How can I present evidence? If needed, I can provide screenshots of the conversations. Here are the most recent service providers contacted through WeChat.

f02831201 Juwu Mine Guangdong
f02837094 Coffee Could HK
f02816081 KRAL Singapore
f02824157 Shenzhen  ZhongChuangYun
