### ISSUE TITLE
[DataCap Application] <huataibaoan> - <huataibaoan>

### ISSUE THREAD

**Issue by summerxue1992** [filecoin-project/filecoin-plus-large-datasets#1347]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: huataibaoan
- Website / Social Media: http://www.huataibaoan.com/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 400TiB
- On-chain address for first allocation: f1vjj7xunph27t6bsqnlzgelutlijspuwn5y7x3ey

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Beijing Huatai Yongan Security Service Co., Ltd. was established in 2004 with a registered capital of 100 million yuan. It is a member of the China Security Association and a director unit of the Beijing Security Association. Mainly engaged in security security, technical defense, civil air defense, safety inspection, safety assessment and other businesses. It is the Central Government Procurement Center and the designated procurement unit of the Beijing Municipal Government. Security service enterprise level two qualification. The company is located at No. 88, Gonghuacheng Street, Shahe Town, Changping District, Beijing. Now it has more than 3,500 square meters of independent office space and a professional security training base. The company's middle-level and above management personnel are all cadres above the regiment level who have been transferred from the army and armed police, and 95% of them have a college degree or above. There are more than 8,000 professional security guards, 15 branches, 3 offices, and more than 100 service customers, providing various security services such as security, civil air defense, technical defense, guards, parking lot management, and order maintenance for customer units all over the country .
```

What is the primary source of funding for this project?
```
Company labor income.
```

What other projects/ecosystem stakeholders is this project associated with?
```
None.
```

## Use-case details

Describe the data being stored onto Filecoin

```
1. Training video.
2. Walkthrough video.
```

Where was the data in this dataset sourced from?
```
Generated within the company.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://drive.google.com/file/d/1D1lS-C_ApZJfWchMQTzSpJoxwIh1Q7w-/view?usp=share_link
https://drive.google.com/file/d/1LiPIfNTyercWoN55VmNYKar00E-HAtGY/view?usp=share_link
https://drive.google.com/file/d/1krsJl1jrCKlPlXcaZnAA2l0HXM3a3Jxk/view?usp=share_link
Link: https://pan.baidu.com/s/1OL2cjug9s7nLiDAgabMUOw?pwd=j5kv Extraction code: j5kv
```

Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes, we're pretty sure.
```

What is the expected retrieval frequency for this data?
```
1-2 times a year.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
Minimum 540 days.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Hong Kong or America.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Online download or offline mailing.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We prefer storage service providers with higher reliability.
```

How will you be distributing deals across storage providers?
```
Store to multiples SPs.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes.
```

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 400TiB

**Client address**

> f1vjj7xunph27t6bsqnlzgelutlijspuwn5y7x3ey

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Looking at your application i have some questions:
As you are brand new on Github and have no history of past applications it seems to me that applying for 5PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?

Can you show us visible proof of the size of your data and the storage systems you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230337462961356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!

**Comment by summerxue1992** [comment]
@cryptowhizzard  I have completed the kyc, please can not sign for me, thank you！

**Comment by summerxue1992** [comment]
@cryptowhizzard   Hello, I have completed kyc, could you sign for me,？ thank you!

**Comment by summerxue1992** [comment]
I'm looking for sp

**Comment by summerxue1992** [comment]
I will finish the remaining work in the near future, please don't close it yet.

**Comment by summerxue1992** [comment]
I just remembered

**Comment by summerxue1992** [comment]
@cryptowhizzard Oops, my previous address is lost, I need to change the address, f1vjj7xunph27t6bsqnlzgelutlijspuwn5y7x3ey, the mobile phone where this address is located is lost.

**Comment by zcfil** [comment]
Can you explain the source of your data? How many copies will you store?

**Comment by summerxue1992** [comment]
Our data is some video files etc. that record the company.
2 to 3 copies may be saved, and some important data may be more.

**Comment by zcfil** [comment]
Please list the SPs you are pre-collaborating with and the regions.
