### ISSUE TITLE
[DataCap Application] <Beijing Lingyun Space Technology Co., Ltd.> - <spatialinfo>

### ISSUE THREAD

**Issue by caokun8341** [filecoin-project/filecoin-plus-large-datasets#1348]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Beijing Lingyun Space Technology Co., Ltd.
- Website / Social Media: https://www.spatialinfo.cn/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 400TiB
- On-chain address for first allocation: f1fd56n6yko244o3eduavmpju5jgc3rm3jmnmabei

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Beijing Lingyun Space Technology Co., Ltd. is a spatio-temporal data analysis and decision support service company. It is deeply involved in the automatic analysis of spatio-temporal data, data mining and technical research on cloud services. "Software" provides overall solutions for customers in industries such as natural resources, water conservancy and water affairs, agriculture and rural areas, ecological environment, emergency management, urban and rural construction, national defense and military industry, and helps customers promote scientific decision-making and efficient service. Our goal is to build a spatio-temporal data center about the earth and create an understandable digital earth.
```

What is the primary source of funding for this project?
```
company income.
```

What other projects/ecosystem stakeholders is this project associated with?
```
None.
```

## Use-case details

Describe the data being stored onto Filecoin

```
Data such as design schemes, security assessment content, software development logs, publicly available software codes, after-sales maintenance records, and user data.
```

Where was the data in this dataset sourced from?
```
Data generated by the company when conducting business.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://pan.baidu.com/s/1JRc6IEJsybm5xVNOJDVIRw 

verification code: rp2g
```

Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes, we're pretty sure.
```

What is the expected retrieval frequency for this data?
```
3-5 times a year.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
Minimum 540 days.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Hong Kong.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Online download or offline mailing.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We prefer storage service providers with higher reliability.
```

How will you be distributing deals across storage providers?
```
Store to multiples SPs.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes.
```

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Looking at your application i have some questions:
As you are brand new on Github and have no history of past applications it seems to me that applying for 5PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?

Can you show us visible proof of the size of your data and the storage systems you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230232885049356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!

**Comment by Joss-Hua** [comment]
Can you send confirmation email to **filplus-app-review@fil.org** using the email address of your company domain?
@Sunnyiscoming please help verify and confirm.

**Comment by caokun8341** [comment]
> Can you send confirmation email to **[filplus-app-review@fil.org](mailto:filplus-app-review@fil.org)** using the email address of your company domain? @Sunnyiscoming please help verify and confirm.

![image](https://user-images.githubusercontent.com/34340092/219255959-bb7ec6c5-db46-4f34-9f5e-ed369331013b.png)

**Comment by caokun8341** [comment]
> Baidu cloud disk link of data sample is invalid now.

hello,has been reset to be permanently accessible.
链接：https://pan.baidu.com/s/14Fp6xzsts8UULeS3cJzKxw
提取码：fifx
数据永久网盘链接。

**Comment by herrehesse** [comment]
@caokun8341 Not supportive of an application with only storage in Hong Kong.

**Comment by caokun8341** [comment]
> @caokun8341 Not supportive of an application with only storage in Hong Kong.

@herrehesse hello
clear. So we are looking for sps in different places, at least 3.

**Comment by Joss-Hua** [comment]
Agree with what @herrehesse said, but I think that on the premise that the client knows the rules, we need to see the results of the first report before making a judgment.

"Check is friendly to good people and cruel to bad people"

Leave a pair of eyes here.

**Comment by Joss-Hua** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacear2jnbaqptab35whipj72q7fzj3x5pw2ixrpp3jxoc2yh53vzhly 
#### Address 
> f1fd56n6yko244o3eduavmpju5jgc3rm3jmnmabei
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1tfg54zzscugttejv336vivknmsnzzmyudp3t7wi
#### Id
> 1c5be2d2-2d56-47d6-bb7e-6e39fbc5f953
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacear2jnbaqptab35whipj72q7fzj3x5pw2ixrpp3jxoc2yh53vzhly

**Comment by Tom-OriginStorage** [comment]
Kyc has been completed. I am willing to support it. Please start as soon as possible

**Comment by Tom-OriginStorage** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec4tqrlhbndwf2hq5k3s535eo7pf5vwd24q43hib3qs7vvyu4deio 
#### Address 
> f1fd56n6yko244o3eduavmpju5jgc3rm3jmnmabei
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1q6bpjlqia6iemqbrdaxr2uehrhpvoju3qh4lpga
#### Id
> 1c5be2d2-2d56-47d6-bb7e-6e39fbc5f953
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec4tqrlhbndwf2hq5k3s535eo7pf5vwd24q43hib3qs7vvyu4deio

**Comment by a1991car** [comment]
Looks like the same company applied twice with different F1 addresses

**Comment by caokun8341** [comment]
> Looks like the same company applied twice with different F1 addresses

@a1991car Hello,yes, 1315 is an application put forward by another colleague in my company. Later, this colleague left and is no longer responsible for such business. 1315 of ldn is no longer used by our company and will not apply for notary signature again. Thank you!

**Comment by dongpo313** [comment]
checker:manualTrigger

**Comment by dongpo313** [comment]
checker:manualTrigger

**Comment by dongpo313** [comment]
checker:manualTrigger

**Comment by caokun8341** [comment]
@cryptowhizzard 
Could you please kinldy check my LDN and approve or leave some comment if you need?
Many thanks!

**Comment by cryptowhizzard** [comment]
checker:manualTrigger

**Comment by cryptowhizzard** [comment]
Hello @caokun8341 

I have reviewed your LDN per your request, but we cannot proceed.

1: None of your data is retrievable as it stands. This is against Fil+ rules and guidelines.
2: You have not performed KYC which is mandatory.
3: You have stored everything with one miner @sxx-future
<img width="1705" alt="Scherm­afbeelding 2023-07-22 om 11 50 22" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/36404435/ec1fd866-104b-43af-a1c1-9135edbfbe7b">

**Comment by caokun8341** [comment]
@cryptowhizzard

**Comment by caokun8341** [comment]
<img width="900" alt="image" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/34340092/c431dea3-714d-4383-98c5-3542fe559a3f">

**Comment by caokun8341** [comment]
@cryptowhizzard 
Kyc has been completed, we have contacted sp to deal with the retrieval problem, more sp will be added later, if you have sp, you can also introduce to us, thank you very much.

**Comment by caokun8341** [comment]
Hello @cryptowhizzard 
1:We have contacted sp to deal with the retrieval problem, more sp will be added later, if you have sp, you can also introduce to us, thank you very much.
2: Kyc has been completed

**Comment by xinaxu** [comment]
I'm not supporting this LDN since the reports have multiple flags on deal distribution and retrieval.

**Comment by mingyang313** [comment]
checker:manualTrigger

**Comment by dongpo313** [comment]
checker:manualTrigger

**Comment by dongpo313** [comment]
checker:manualTrigger

**Comment by dongpo313** [comment]
checker:manualTrigger

**Comment by dongpo313** [comment]
checker:manualTrigger

**Comment by dongpo313** [comment]
checker:manualTrigger

**Comment by dongpo313** [comment]
checker:manualTrigger

**Comment by mingyang313** [comment]
checker:manualTrigger

**Comment by mingyang313** [comment]
checker:manualTrigger

**Comment by Filplus-govteam** [comment]
Hello @caokun8341  per the new guidelines https://github.com/filecoin-project/notary-governance/issues/922 for Open Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

This information will be reviewed by Fil+ Governance team to confirm validity toward the Fil+ guideline of a distributed storage plan and SPs posted in the comments here. Let us know if you have any questions.

**Comment by caokun8341** [comment]
@Filplus-govteam Hello,Our KYC has been done and finished. Thank you.

**Comment by mingyang313** [comment]
checker:manualTrigger

**Comment by cryptowhizzard** [comment]
<img width="683" alt="Scherm­afbeelding 2023-08-19 om 16 59 34" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/36404435/073fb8ec-d7ba-45c4-9925-00d80dd4b7c5">

Dispute made.

This application does not support retrieval and should be closed.

**Comment by mingyang313** [comment]
checker:manualTrigger

**Comment by caokun8341** [comment]
The data that can be retrieved already increasing. SP is repairing the data, please do not close it, thank you!

**Comment by caokun8341** [comment]
checker:manualTrigger

**Comment by caokun8341** [comment]
We have contacted sp, as it is the weekend, so we have to wait until Monday to go to work to deal with the search problem, please do not close this application, thank you!

**Comment by 87103978** [comment]
checker:manualTrigger

**Comment by caokun8341** [comment]
checker:manualTrigger

**Comment by chenhanweiharry** [comment]
checker:manualTrigger

**Comment by cryptowhizzard** [comment]
> <img alt="Scherm­afbeelding 2023-08-19 om 16 59 34" width="683" src="https://user-images.githubusercontent.com/36404435/261804698-073fb8ec-d7ba-45c4-9925-00d80dd4b7c5.png">
> Dispute made.
> 
> This application does not support retrieval and should be closed.

Secondly, it is 100% selfdealing.

**Comment by caokun8341** [comment]
> > <img alt="Scherm­afbeelding 2023-08-19 om 16 59 34" width="683" src="https://user-images.githubusercontent.com/36404435/261804698-073fb8ec-d7ba-45c4-9925-00d80dd4b7c5.png">
> > Dispute made.
> > This application does not support retrieval and should be closed.
> 
> Secondly, it is 100% selfdealing.

Hello @cryptowhizzard Sp is repairing the data. It will take some time. Please don't close it. Thank you.

**Comment by mingyang313** [comment]
checker:manualTrigger

**Comment by mingyang313** [comment]
checker:manualTrigger

**Comment by mingyang313** [comment]
checker:manualTrigger

**Comment by mingyang313** [comment]
checker:manualTrigger

**Comment by lingsucheng** [comment]
checker:manualTrigger

**Comment by caokun8341** [comment]
checker:manualTrigger

**Comment by lingsucheng** [comment]
checker:manualTrigger

**Comment by lingsucheng** [comment]
checker:manualTrigger

**Comment by cryptowhizzard** [comment]
Question:

I see you have stored with only one organisation until now and that retrievability is very bad. According to my records these are SXX-Future data miners. Is that correct?

@Filplus-govteam can you please implement 922 here. I would like to know the storage plan and why this retrieval is problematic.

**Comment by raghavrmadya** [comment]
The report is extremely concerning and client has provided no update. Application is being closed to prevent potential abuse of DC and request for DC if received any
<img width="698" alt="Screenshot 2023-09-04 at 9 30 12 AM" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/91579519/7bbce36f-8d59-45f8-932d-081937cf23c9">

Check dispute here - https://www.notion.so/filecoin/No-retrieval-in-application-198a61b3bea544019aa0d44751622a81?pvs=4

**Comment by caokun8341** [comment]
> The report is extremely concerning and client has provided no update. Application is being closed to prevent potential abuse of DC and request for DC if received any <img alt="Screenshot 2023-09-04 at 9 30 12 AM" width="698" src="https://user-images.githubusercontent.com/91579519/265510171-7bbce36f-8d59-45f8-932d-081937cf23c9.png">
> 
> Check dispute here - https://www.notion.so/filecoin/No-retrieval-in-application-198a61b3bea544019aa0d44751622a81?pvs=4

hello @raghavrmadya 
You can see an improvement in the retrieval success rate, and we have added SP to meet the demands of FIL+."

**Comment by mingyang313** [comment]
checker:manualTrigger

**Comment by caokun8341** [comment]
Hello @kevzak, please help me to repoen it，thx.

**Comment by mingyang313** [comment]
checker:manualTrigger
