### ISSUE TITLE
[DataCap Application] <YueYuan> - <Smart Voice>

### ISSUE THREAD

**Issue by PipengWang** [filecoin-project/filecoin-plus-large-datasets#1349]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Hangzhou Yueyuan Technology Co., Ltd
- Website / Social Media: http://www.xinsway.cn/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100TiB
- On-chain address for first allocation:  f166erfrtv2iggppt4mmr7rykcxrz5pkzrcv5a7ry

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Hangzhou Yueyuan Technology Co., Ltd. (hereinafter referred to as Yueyuan Technology), founded in August 2019, is a professional technology company focusing on intelligent operation related products and services, focusing on speech recognition, semantic understanding, speech synthesis and data mining and other fields, combined with the team's Internet operation experience, with the S2B2C model, to provide intelligent marketing operation SaaS platform, empowering the intelligent transformation and performance improvement of enterprises.
Yueyuan Technology and Beijing Forestry University jointly promote in-depth cooperation between industry, education and research in the field of artificial intelligence, and are members of the strategic alliance of technological innovation in the artificial intelligence industry.
Yueyuan Technology has complete patents and copyrights for TTS, ASR, NLP and other related technologies and products independently developed, and continues to develop and optimize speech synthesis, speech recognition, semantic understanding and other related technologies
```

What is the primary source of funding for this project?
```
Our software and services generate profits
```

What other projects/ecosystem stakeholders is this project associated with?
```
No.
```

## Use-case details

Describe the data being stored onto Filecoin
```
Our sample data is mainly pronunciation in various Chinese dialects, as well as situational dialogue training texts, etc
```

Where was the data in this dataset sourced from?
```
1 Industry case material accumulation 
2 Cooperate with customer needs to provide
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://drive.google.com/file/d/1Cv4TzqZPp2iuxPKPvo_izgtOM5tUe1fm/view?usp=share_link
https://drive.google.com/file/d/1vUr6ZmU76gtggieVKQw7nf1FXd8kxyOP/view?usp=share_link
https://drive.google.com/file/d/1jpTE7Jz_Zil-253jB1A5-qxPxv7sG58E/view?usp=share_link
https://drive.google.com/file/d/1fNvrytcWHtKcshNa-_u8ujPMYKzNrpAR/view?usp=share_link
https://drive.google.com/file/d/1Uk2Xdt5BmzBpgyEZFmbMGZIuj8U0xf1z/view?usp=share_link
https://drive.google.com/file/d/1QKrgYN4lqsMr_JB6QWIgqAo9EqQfxgQs/view?usp=share_link

```
        
Confirm that th is is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes, the confirmations are all public data.
```

What is the expected retrieval frequency for this data?
```
Semi-annually
```

For how long do you plan to keep this dataset stored on Filecoin?
```
5 years
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
China
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Mainly offline
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We will choose large miners and reputable miners
```

How will you be distributing deals across storage providers?
```
We have about 1.2P of data on it, will be ready to make 5 copies, choose about 10 storage providers
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, we have negotiated some miners and have already made some preliminary cooperation agreements, and we will start encapsulating once we get the quota.
```

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 100TiB

**Client address**

> f166erfrtv2iggppt4mmr7rykcxrz5pkzrcv5a7ry

**Comment by YuanHeHK** [comment]
Hi，@PipengWang

**Comment by YuanHeHK** [comment]
Hi @PipengWang 

- Please explain your relationship with this business？
- Please describe the data in detail, including but not limited to the total data volume, number of replicas, allocation plan and possibly node list.
- Could you send an email to [filplus-app-review@fil.org](mailto:filplus-app-review@fil.org) with your official domain in order to confirm your identity? Email name should includes the issue id.

**Comment by PipengWang** [comment]
@YuanHeHK 
- My name is Changlin Zhao. I am the business matchmaker of Yueyuan Technology Co., Ltd.
- We are an intelligent speech recognition company, our business includes speech recognition and intelligent situational dialogue business, such as intelligent customer service and so on.
The data we plan to store on Filecoin is mainly some of our voices for training, including dialect data, contextual dialogue data, etc. Because of China's relatively large territory, we have collected language sets of 10 major dialects, and there are dozens of sub-categories of variable language sets under each category. The amount of data is about 1.3P data source.
We plan to divide these data into 4~5 copies and mainly store them in 6 to 10 SPs, in this process we will try multiple SPs, and follow up the storage quality provided to select the best SPs.
- Finally I have sent a confirmation email. Please check， @YuanHeHK  @Sunnyiscoming  Thank you very much!


![image](https://user-images.githubusercontent.com/50102737/206137756-33f12d44-621c-4861-95ad-32f28d99faa2.png)

**Comment by liyunzhi-666** [comment]
hey @PipengWang 
Can you provide more detailed information about other storage providers participated in this program? Such as SP ID and geographic location.

**Comment by PipengWang** [comment]
hey @liyunzhi-666 ,Sorry for taking so long to reply. We plan to look for about 10 SPs, and currently we are dealing with 5 as follows：
![image](https://user-images.githubusercontent.com/50102737/207223280-2d588ae2-abb8-4a98-b26d-27016882fdd7.png)

**Comment by liyunzhi-666** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebe7iu6k2jaujv24a5rhnewmv7jpz6iq4rkcvn7hd2cy64p7g2qkm 
#### Address 
> f166erfrtv2iggppt4mmr7rykcxrz5pkzrcv5a7ry
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1pszcrsciyixyuxxukkvtazcokexbn54amf7gvoq
#### Id
> f3b8cd53-72c8-4d52-a599-c9daaf0edadd
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebe7iu6k2jaujv24a5rhnewmv7jpz6iq4rkcvn7hd2cy64p7g2qkm

**Comment by YuanHeHK** [comment]
The information provided so currently appears to be fine, the first signature gives support, and later if there is a problem, it will not be supported.

**Comment by YuanHeHK** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec7uyoyazxmklvirvuk5gasgbsnklp3drfofagobnq66ko5ywhdqk 
#### Address 
> f166erfrtv2iggppt4mmr7rykcxrz5pkzrcv5a7ry
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1fg6jkxsr3twfnyhdlatmq36xca6sshptscds7xa
#### Id
> f3b8cd53-72c8-4d52-a599-c9daaf0edadd
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec7uyoyazxmklvirvuk5gasgbsnklp3drfofagobnq66ko5ywhdqk

**Comment by kernelogic** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceclipbcmgti73go3npo36jda4wjskud3zt62ejbqxjrzyywlmki56 
#### Address 
> f166erfrtv2iggppt4mmr7rykcxrz5pkzrcv5a7ry
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### Id
> 9ee93a68-16e9-4b1e-b7c8-bdd16a953160
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceclipbcmgti73go3npo36jda4wjskud3zt62ejbqxjrzyywlmki56

**Comment by kernelogic** [comment]
CID Checker looks alright, willing to support

**Comment by Tom-OriginStorage** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedujwxe6wyzeb7spzrjg6bdjdptysa6k2l2uen7lt4647p7wgrgcg 
#### Address 
> f166erfrtv2iggppt4mmr7rykcxrz5pkzrcv5a7ry
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1q6bpjlqia6iemqbrdaxr2uehrhpvoju3qh4lpga
#### Id
> 9ee93a68-16e9-4b1e-b7c8-bdd16a953160
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedujwxe6wyzeb7spzrjg6bdjdptysa6k2l2uen7lt4647p7wgrgcg

**Comment by Tom-OriginStorage** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceck6hbcavlen2gwx3fvs5ptawkp3io7l45px6wkozxhstkcyseage 
#### Address 
> f166erfrtv2iggppt4mmr7rykcxrz5pkzrcv5a7ry
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1q6bpjlqia6iemqbrdaxr2uehrhpvoju3qh4lpga
#### Id
> c56103e4-ad15-4bf7-b036-e54b415384d0
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceck6hbcavlen2gwx3fvs5ptawkp3io7l45px6wkozxhstkcyseage

**Comment by fireflyHZ** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedt22nafugwjxcw7e5eel2vsh6o6w44z77ojza3b2qcithhilbyuc 
#### Address 
> f166erfrtv2iggppt4mmr7rykcxrz5pkzrcv5a7ry
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1fg6jkxsr3twfnyhdlatmq36xca6sshptscds7xa
#### Id
> c56103e4-ad15-4bf7-b036-e54b415384d0
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedt22nafugwjxcw7e5eel2vsh6o6w44z77ojza3b2qcithhilbyuc

**Comment by YuanHeHK** [comment]
checker:manualTrigger

**Comment by Irmagogo** [comment]
checker:manualTrigger

**Comment by NDLABS-OFFICE** [comment]
checker:manualTrigger

**Comment by kernelogic** [comment]
checker result looks very good.

**Comment by kernelogic** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecfps27rsuf33bfiyuwi2ind2araoplvvl7d5ovd3vvfokz7y5sr6 
#### Address 
> f166erfrtv2iggppt4mmr7rykcxrz5pkzrcv5a7ry
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### Id
> c67c26db-f8a9-4da9-bde9-8c0ec1341829
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecfps27rsuf33bfiyuwi2ind2araoplvvl7d5ovd3vvfokz7y5sr6

**Comment by newwebgroup** [comment]
Looks normal

**Comment by newwebgroup** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebtkpprza35h6gy2zxfbuzrdyctayz6v7lsv3d75flptln6ilcll4 
#### Address 
> f166erfrtv2iggppt4mmr7rykcxrz5pkzrcv5a7ry
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1e77zuityhvvw6u2t6tb5qlnsegy2s67qs4lbbbq
#### Id
> c67c26db-f8a9-4da9-bde9-8c0ec1341829
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebtkpprza35h6gy2zxfbuzrdyctayz6v7lsv3d75flptln6ilcll4

**Comment by cryptowhizzard** [comment]
Hello,

None of these miners are supporting retrieval of deals and none of this miners are reachable at all for retrieval.

*This is against the FIL+ rules and guidelines and be fixed before next allocation of datacaps can proceed*

>>>>>

lotus net connect f01908646
f01908646 -> {12D3KooWDr4AEQMuVqdhGFnC48vM1Vap5paan1yqsvpaF12yWwrf: [/ip4/74.211.110.65/tcp/59111]}
ERROR: failed to parse multiaddr "f01908646": must begin with /


root@proposals:~# telnet 74.211.110.65 59111
Trying 74.211.110.65...
Connected to 74.211.110.65.
Escape character is '^]'.
Connection closed by foreign host.

lotus net connect f01949065
f01949065 -> {12D3KooWDViFSHfrvC3usC8Nio9bJ6WbmrvoCgGiwDFw5ZCU7USE: [/ip4/173.242.116.70/tcp/59065]}
ERROR: failed to parse multiaddr "f01949065": must begin with /

root@proposals:~# telnet 173.242.116.70 59065
Trying 173.242.116.70...
telnet: Unable to connect to remote host: Connection refused


lotus net connect f01908695
f01908695 -> {12D3KooWNCSRj6bx4yhfzaJZyx8Pj9jnj9FwResNZHMkRCp9SDwJ: [/ip4/212.50.250.232/tcp/59218]}
ERROR: failed to parse multiaddr "f01908695": must begin with /

root@proposals:~# telnet 212.50.250.232 59218
Trying 212.50.250.232...
Connected to 212.50.250.232.
Escape character is '^]'.
Connection closed by foreign host.

lotus net connect f01941229
f01941229 -> {12D3KooWF7jrudF7k2tibthXrC2cyFrAMThm4qLbU4PRMFkj13JC: [/ip4/212.50.245.224/tcp/59112]}
ERROR: failed to parse multiaddr "f01941229": must begin with /

root@proposals:~# telnet 212.50.245.224 59112
Trying 212.50.245.224...
Connected to 212.50.245.224.
Escape character is '^]'.
Connection closed by foreign host.


lotus net connect f021695
f021695 -> {12D3KooWFbwEyLfARnZRR26DPJXw1v5tMQW63q2ybMVK8f4Tj69J: [/ip4/212.50.250.232/tcp/59204]}
ERROR: failed to parse multiaddr "f021695": must begin with /

root@proposals:~# telnet 212.50.250.232 59204
Trying 212.50.250.232...
Connected to 212.50.250.232.
Escape character is '^]'.
Connection closed by foreign host.

lotus net connect f01955058
f01955058 -> {12D3KooWRRsKt3q9XmisHgaxgv2uRnLnFRjbktCrMbLqzAxbiTob: [/ip4/173.242.116.70/tcp/55058]}
ERROR: failed to parse multiaddr "f01955058": must begin with /

root@proposals:~# telnet 173.242.116.70 55058
Trying 173.242.116.70...
telnet: Unable to connect to remote host: Connection refused

**Comment by BDEio** [comment]
@PipengWang Hi! Great to see that you have gotten approval for DataCap!
BDE is a verified deals auction house helping you to get paid storing your data with reliable storage providers. If you need any help, please get in touch.

**Comment by cryptowhizzard** [comment]
checker:manualTrigger

**Comment by cryptowhizzard** [comment]
checker:manualTrigger

**Comment by cryptowhizzard** [comment]
Hello!

None of your miners support retrieval, everything is firewalled.
Please take note on the rules of FIL+ . Clients must be able to connect to download the data.
