### ISSUE TITLE
[DataCap Application] <Cayman Atomic Fund Co., Ltd.> - <Atoshi>

### ISSUE THREAD

**Issue by 87103978** [filecoin-project/filecoin-plus-large-datasets#1357]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Cayman Atomic Fund Co., Ltd.
- Website / Social Media: https://atoshi.org/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 400TiB
- On-chain address for first allocation: f1bwcd4g2ygy4wgryeeils42jjpdf2dpbbvi37gfq

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer.*

## Project details

Share a brief history of your project and organization.
```
1. Atomic Fund Co., Ltd. (Atoshi Foundation) was established in May 2018, using block chain to achieve value transfer, using block chain to achieve landing application of electronic mall. Atomic chain Mall, the main atoshi brand goods, the main B2C e-commerce, brand e-commerce. And do diversion services for the world's mainstream e-commerce.

2. At present, the main project is ATOSHI. With blockchain to enable social e-commerce, APP starts more than 9.6 million times a day, Mall makes more than 40000 daily payments, and its daily active users peak more than one million; Mall has the following characteristics: cooperate with Taobao Tmall, JD.com, pinduoduo, and Amazon,Shopee,eBay in the future, our users will enjoy certain discounts when they go to the above malls through our APP, and can also get atomic coins. We will also get a rebate from the above platform. At present, we have more than 10 million registered users. On average, after each customer spends on the above platform, if we get a rebate of 1 yuan, that is more than 10 million daily income. Can also start a business at home: by sharing APP, turn idle time into productivity; as long as you work hard, your monthly income may exceed 10,000 yuan! Buyers buy products free of charge, currency appreciation potential is unlimited, from simple consumers to potential moneymakers, encourage consumption to boost GDP. We have a variety of games for our users' leisure and entertainment, including idioms, chess and other educational and learning games. Users can get atomic coins by playing games. At present, we have more than 10 million registered users. If 1% of people can contribute 10 yuan a day, the income will reach more than 1 million a day, and this income will be even higher in the future.
```
![image](https://user-images.githubusercontent.com/72076505/205005619-cbe3aa52-9bb8-4d6f-bec4-370910981014.png)
![image](https://user-images.githubusercontent.com/72076505/205005670-7b430873-51ef-485a-af43-24c37ac7edd6.png)
![image](https://user-images.githubusercontent.com/72076505/205005696-f36ee43a-88af-4d37-8af9-df87a9bff4c8.png)
![image](https://user-images.githubusercontent.com/72076505/205005748-05482624-28db-4ea7-8bb0-a600cd8d9fff.png)
![image](https://user-images.githubusercontent.com/72076505/205005780-0420ddfc-afdd-4406-87d7-853fb1f5513b.png)
![image](https://user-images.githubusercontent.com/72076505/205005804-21ba741f-3896-47b1-8817-f4de87b76ad1.png)
![image](https://user-images.githubusercontent.com/72076505/205005836-d105705d-21f1-44a5-b3a2-eb1ec571c0b3.png)
![image](https://user-images.githubusercontent.com/72076505/205005869-7f99e4f8-6a5f-4e2f-ba09-934bc99fba1d.png)
![image](https://user-images.githubusercontent.com/72076505/205005890-2b0d272f-73d9-4665-bdff-d3849333ed1c.png)

What is the primary source of funding for this project?
```
COperating income of electronic mall
```

What other projects/ecosystem stakeholders is this project associated with?
```
Not yet.
```

## Use-case details

Describe the data being stored onto Filecoin
```
1. Corporate promotional video.
2. Store product pictures and video.
```
Where was the data in this dataset sourced from?
```
Company and users.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this.
```
https://drive.google.com/file/d/15bn7BfG8vv4DEqTIp3dXD_ys8TCQDw4c/view?usp=share_link
https://drive.google.com/file/d/1xhZgSucBzaoqfs5g5RX1LhgAGmpvf_-A/view?usp=share_link
https://drive.google.com/file/d/16Af6k6FOQEmCAiW_Ax2qXT7E6WMn97hW/view?usp=share_link
https://drive.google.com/file/d/1VoNeP7gLbVSp30s2weZWG81Uo-0FGXGP/view?usp=share_link
https://drive.google.com/file/d/1dW9brB_tmpdInItsYhE5qJW-Fvs2afsM/view?usp=share_link
https://drive.google.com/file/d/1K2G20pQ7KURClB6FcmX8B8dxsQKnPP80/view?usp=share_link
https://drive.google.com/file/d/1veP8Utsqd4znacihVFa-9267_YMPO54x/view?usp=share_link
https://drive.google.com/file/d/1ubJF0CIcqkjeoin_RB9cTksWyWR7o17l/view?usp=share_link
https://drive.google.com/file/d/1Zl-KZyuMxs7kpvOrhDnjpoMYaOnExrxu/view?usp=share_link
https://drive.google.com/file/d/152uRUqPhA7v8S0xmaTjNGxXSlSGzbZn8/view?usp=share_link
https://drive.google.com/file/d/1ioj7d9PRrWaqA28zTC3DqMTUDlNd341u/view?usp=share_link
https://drive.google.com/file/d/1EtYdJDv_rGVFpFIMjSX2fiRUJb8J2kca/view?usp=share_link
https://drive.google.com/file/d/1T9BlJkZJLO5exQNrSsmF1qfl-kFpeFDq/view?usp=share_link
https://drive.google.com/file/d/1beIWb-Kg_NSvJ6C8a27aFSjK_pGeFZhf/view?usp=share_link
https://drive.google.com/file/d/1FGYV45D8jccmKHGybjE_T72uLbkaGkQ1/view?usp=share_link
https://drive.google.com/file/d/1B9BsoczbJ8dg02GKh3Ygza31U8JY3D-f/view?usp=share_link
https://drive.google.com/file/d/1D0c_9pWC0Gr7EnNfTdIeqe8PicnxfZlO/view?usp=share_link
https://drive.google.com/file/d/15EMaC8gwttoFrZ9YxAgjzIrvt0ZZCNkt/view?usp=share_link



```
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes, we're pretty sure.
```

What is the expected retrieval frequency for this data?
```
1-2 times a year.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
Minimum 540 days.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?

    Hong Kong.

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Online download or offline mailing.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We prefer storage service providers with higher reliability.
```

How will you be distributing deals across storage providers?
```
Store to multiples SPs.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes.
```

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 400TiB

**Client address**

> f1bwcd4g2ygy4wgryeeils42jjpdf2dpbbvi37gfq

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Looking at your application i have some questions:
As you are brand new on Github and have no history of past applications it seems to me that applying for 5PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?

Can you show us visible proof of the size of your data and the storage systems you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230232885049356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!

**Comment by cryptowhizzard** [comment]
Hello,

Thank you for your the help.

The only thing that is missing are the SP's you will use for the first datacap allocation plus their contact information in order to verify that they are legit and of good reputation. Can you give them to us?

And the acknowledgement that you understand this rules. Please acknowledge below that you understand them.

>>
RULES: In order to be eligible for the Filecoin+ incentive program, which provides 10x the power (QAP) for storing data on the Filecoin network, there are certain rules that must be followed:

Data must be stored with multiple independent service providers, not just one organization running multiple SPs.
Data must be distributed across multiple regions. Using a VPN to fake presence is not allowed.
Data must be publicly retrievable for verification that it is being stored as claimed. It is highly recommended to run boost.
Data must align with the mission of FIL+, meaning it must be valuable for humanity, whether scientific or unique in some other way.
Data must be open and not encrypted. If you wish to encrypt your data, consider applying for the FIL-E program instead.
Note: As a data preparer, you are allowed to store one copy yourself for redundancy at the request of the client. However, if your copy is stored in the USA, the other organizations/SPs must be outside your region. Dcent encourages applications with a minimum spread of 2 continents and 3 different organizations.
>>

**Comment by 87103978** [comment]
> Dear applicant,
> 
> Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.
> 
> Looking at your application i have some questions: As you are brand new on Github and have no history of past applications it seems to me that applying for 5PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?
> 
> Can you show us visible proof of the size of your data and the storage systems you have there?
> 
> As last question i would like you to fill out [this form](https://form.jotform.com/230232885049356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.
> 
> Thanks!

Hello, I have worked in the field of filecoin and have been following this project for more than 2 years. I have applied for datacap with my github account in the past, and I have another github account.

Data size display:
![image](https://user-images.githubusercontent.com/72076505/215689822-93f54f80-2f3c-4e70-9982-5085b8114f8e.png)

**Comment by cryptowhizzard** [comment]
hello @87103978 

>>
As last question i would like you to fill out [this form](https://form.jotform.com/230232885049356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.
>>

?

**Comment by cryptowhizzard** [comment]
Hello!

Thanks for completing KYC.

There are 2 fields that you left open on the KYC form. I need that information before i can sign on your application.

You indicated that you are the data preparer and owner of the dataset. Can you confirm you don't have any stake in SP's you are going to send this data to? As stated in the form I am allowing 1 replica of the set to be stored on your own miners. That's the reason i ask.

Second:

As the form states _> RULES: In order to be eligible for the Filecoin+ incentive program, which provides 10x the power (QAP) for storing data on the Filecoin network, there are certain rules that must be followed:

Data must be stored with multiple independent service providers, not just one organization running multiple SPs.
Data must be distributed across multiple regions. Using a VPN to fake presence is not allowed.
Data must be publicly retrievable for verification that it is being stored as claimed. It is highly recommended to run boost.
Data must align with the mission of FIL+, meaning it must be valuable for humanity, whether scientific or unique in some other way.
Data must be open and not encrypted. If you wish to encrypt your data, consider applying for the FIL-E program instead.
Note: As a data preparer, you are allowed to store one copy yourself for redundancy at the request of the client. However, if your copy is stored in the USA, the other organizations/SPs must be outside your region. Dcent encourages applications with a minimum spread of 2 continents and 3 different organizations.

Can you provide me with the Sp's and their contact information?

Thanks!

**Comment by 87103978** [comment]
@cryptowhizzard Hello, could you sign for us, please? Thank you!

**Comment by cryptowhizzard** [comment]
Hi @87103978 

No, i won't sign unless i have the SP's known where you are going to store your first allocation and those SP's are with good reputation.

**Comment by metacodebean** [comment]
We are looking for SP, after finding a suitable SP, we will use this ldn, apply to open, thank you!

**Comment by 87103978** [comment]
@Sunnyiscoming We will continue to use this LDN. I'm very sorry. Please open it for us. Thank you.

**Comment by 87103978** [comment]
Hello @Fil+ Gov team, We will continue to use this LDN,Please open it for us. Thank you.

**Comment by 87103978** [comment]
@Sunnyiscoming Thanks a lot

**Comment by psh0691** [comment]
@87103978 Did you find a storage provider to store your data?

**Comment by Filplus-govteam** [comment]
Hello @87103978 per the new guidelines https://github.com/filecoin-project/notary-governance/issues/922 for Open Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

This information will be reviewed by Fil+ Governance team to confirm validity toward the Fil+ guideline of a distributed storage plan and SPs posted in the comments here. Let us know if you have any questions.

**Comment by MRJAVAZHAO** [comment]
According to the rules of the community, you need to clarify the sp information.

**Comment by 87103978** [comment]
@psh0691 Hello,The following SP node numbers we found to store our data are the following 4: 
f01992563
f01996719
f01996817
f01319803

**Comment by 87103978** [comment]
@MRJAVAZHAO Hello, The following SP node numbers we found to store our data are the following 4:
f01992563
f01996719
f01996817
f01319803

**Comment by 87103978** [comment]
@Filplus-govteam KYC completed. Thank you.
<img width="772" alt="image" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/72076505/c61a8511-318a-4a13-ba73-09942b65234e">

**Comment by psh0691** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedf24mtvgkfa2fqvemuuknx3cc4lketw4vdb632gch3lmy2e22apc 
#### Address 
> f1bwcd4g2ygy4wgryeeils42jjpdf2dpbbvi37gfq
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1qdko4jg25vo35qmyvcrw4ak4fmuu3f5rif2kc7i
#### Id
> a93bc0c5-575f-45de-885c-b4553f53ef18
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedf24mtvgkfa2fqvemuuknx3cc4lketw4vdb632gch3lmy2e22apc

**Comment by cryptowhizzard** [comment]
<img width="698" alt="Scherm­afbeelding 2023-08-19 om 16 49 11" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/36404435/2220b5e1-6bec-4a2d-805e-1c75be7f83ad">

The providers you intend to work with do not support retrieval. See issue 1350

This goes for f01992563, f01996719 and f01996817

https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1350

**Comment by cryptowhizzard** [comment]
@psh0691 

Why are you signing on this?

**Comment by 87103978** [comment]
Hello  @cryptowhizzard， We have contacted SPs to turn on the retrieval function, you can check it, thank you!

**Comment by cryptowhizzard** [comment]
Hi @87103978 

Again: These SP's don't support retrieval.

**Comment by 87103978** [comment]
Hello @cryptowhizzard 
Please try to check these SPs again , thank you!

**Comment by zcfil** [comment]
checker:manualTrigger

**Comment by Sunnyiscoming** [comment]
f01992563 CN
f01996719 SA
f01996817 HK
f01319803 CN
f01992032 CN

**Comment by cryptowhizzard** [comment]
<img width="523" alt="Scherm­afbeelding 2023-08-25 om 22 27 48" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/36404435/8a1ee617-0a75-484d-9797-d931c6eb6662">

f01319803 is still not ok because it has no IP set on chain.

All the remaining SP's are **_not_** eligible for FIL+ and flagged in #1350. They abort retrieval requests when attempts are made.

**Comment by 87103978** [comment]
> <img alt="Scherm­afbeelding 2023-08-25 om 22 27 48" width="523" src="https://user-images.githubusercontent.com/36404435/263385379-8a1ee617-0a75-484d-9797-d931c6eb6662.png">
> f01319803 is still not ok because it has no IP set on chain.
> 
> All the remaining SP's are **_not_** eligible for FIL+ and flagged in #1350. They abort retrieval requests when attempts are made.

Hello, @cryptowhizzard  we have decided to change the SP,f01319803 to f01302188, please check, thank you

**Comment by cryptowhizzard** [comment]
f01319803 does not have it's IP set on chain and is not eligible for Fil+
f01302188 has been storing data in #1365 where it has been storing crap data.

Sorry.

**Comment by raghavrmadya** [comment]
https://www.notion.so/filecoin/Signing-without-retrieval-9cee5be9c8e044079c83de02ec2c8d9d?pvs=4

Flags by the notary has been ignored and the client has addressed the concerns in the dispute. As a result, this application is being closed based on the above evidence and being flagged for DC removal. The client is welcome to apply again by completing ALL fields in the LDN.

**Comment by 87103978** [comment]
Hello @cryptowhizzard @raghavrmadya 

> f01319803 does not have it's IP set on chain and is not eligible for Fil+ f01302188 has been storing data in #1365 where it has been storing crap data.
> 
> Sorry.


> https://www.notion.so/filecoin/Signing-without-retrieval-9cee5be9c8e044079c83de02ec2c8d9d?pvs=4
> 
> Flags by the notary has been ignored and the client has addressed the concerns in the dispute. As a result, this application is being closed based on the above evidence and being flagged for DC removal. The client is welcome to apply again by completing ALL fields in the LDN.

![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/72076505/fe8a0414-a915-4f81-a0dc-486a6a39d6e3)


First of all, I don't agree with this conclusion, or it may be that I made a mistake when submitting KYC, we do not want to work with SP's who do not support retrieval.
Second, we have nothing to do with # 1365. If f01302188 encapsulates junk data, we will not cooperate with it.
We are working on real data, and strive to support the data cap project and the construction and development of filecoin ecology.
I hope the manager can help us reopen our ldn, we are real data, knowledge has not yet begun to encapsulate, we are looking for enough SPs to cooperate, the reply message here may be a bit untimely, thank you!

**Comment by 87103978** [comment]
@Sunnyiscoming Hello, can you open this LDN for us? now that we have contacted the reliable and high-quality SP, we need to store our valid data immediately. thanks.

**Comment by 87103978** [comment]
Hello @kevzak can you open this LDN for us? now that we have contacted the reliable and high-quality SP, we need to store our valid data immediately. thanks.

**Comment by herrehesse** [comment]
checker:manualTrigger
