### ISSUE TITLE
[DataCap Application] <BEIJING DataColour Co., Ltd.> - <Audio Visualization Project>

### ISSUE THREAD

**Issue by baibailee12** [filecoin-project/filecoin-plus-large-datasets#1358]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: BEIJING DataColour Co., Ltd.
- Website / Social Media:http://www.datacolour.cn/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):200TiB
- On-chain address for first allocation:f1tjseop7cfi2re4gtvrd2vdjn7vmiyiezzisbenq

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
We support multi-dimensional business scenario analysis of enterprises, provide fast delivery business strategy analysis capabilities, and unify the comprehensive display and linkage of various business data of enterprises. In this project, we present audio as visual graphs and curves for users to use
```

What is the primary source of funding for this project?
```
Project Income
```

What other projects/ecosystem stakeholders is this project associated with?
```
None
```

## Use-case details

Describe the data being stored onto Filecoin
```
The data are Audio data
```

Where was the data in this dataset sourced from?
```
Data generated by the Company in conducting its business.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
Link：https://www.aliyundrive.com/s/xApdhPp4uCV 
Extraction code：none
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes,it is
```

What is the expected retrieval frequency for this data?
```
No frequent retrieval is required. 1 times a year
```

For how long do you plan to keep this dataset stored on Filecoin?
```
3 years
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
ALL REGIONS
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
We store the data on the data server
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
In order to ensure data security, we will select 2 storage providers and require storage providers to be able to quickly retrieve
```

How will you be distributing deals across storage providers?
```
We will distribute them equally to the high-quality storage providers that pass our audit.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
The company will pay all expenses.
```

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 200TiB

**Client address**

>f1tjseop7cfi2re4gtvrd2vdjn7vmiyiezzisbenq

**Comment by xingjitansuo** [comment]
Hi, Thanks for applying. Access to the sample data is expired. Can you please update the latest access code? 
<img width="397" alt="截屏2023-03-18 下午10 36 25" src="https://user-images.githubusercontent.com/72185104/226112705-66d27d00-b584-4773-a6fb-9da04d2e8f6b.png">

**Comment by NewHuoPool** [comment]
In the storage plan you mentioned that you will choose two storage providers, I want to confirm whether this means that you will choose two upfront or only two for the whole storage, if there are only two storage providers for the whole process, it may not be consistent with the fil+ rule.

**Comment by baibailee12** [comment]
Sorry, I am re-uploading the data samples and will make them available for your inspection tomorrow.

**Comment by baibailee12** [comment]
https://cowtransfer.com/s/f91dee4a76ba4c 点击链接查看 [ Common Voice Corpus 2 zh-CN .tar ] ，或访问奶牛快传 cowtransfer.com 输入传输口令 ibawb6 查看；
 
 Here is the sample data, please check@xingjitansuo @NewHuoPool 
In addition, after our preliminary screening and communication, we will probably reach cooperation with the following SP
f01927554
f01923787
f01923786
f01859603
f01938671
f01900537
f01914991 
f01932183

**Comment by NewHuoPool** [comment]
Each node displays normally.
![265b71c362cce92101167edc1100bb1](https://user-images.githubusercontent.com/117884185/227408604-7d61f1e4-7fb7-42b2-8f4a-5fdc5056f748.jpg)
We'll support this round.

**Comment by NewHuoPool** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecknft4agvzxsecvhu2gfrbwhutt6lh7rwfooa7ju6u7pqlqybljs 
#### Address 
> f1tjseop7cfi2re4gtvrd2vdjn7vmiyiezzisbenq
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f16karfxq7lxdy7izqrzrk75jf3not34k6sg6zvcy
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecknft4agvzxsecvhu2gfrbwhutt6lh7rwfooa7ju6u7pqlqybljs

**Comment by xingjitansuo** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebho65s45k2ymacye4pit5bxtu2ac32aoxuebuu4cqn2fcens4k6y 
#### Address 
> f1tjseop7cfi2re4gtvrd2vdjn7vmiyiezzisbenq
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1a2lia2cwwekeubwo4nppt4v4vebxs2frozarz3q
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebho65s45k2ymacye4pit5bxtu2ac32aoxuebuu4cqn2fcens4k6y

**Comment by SuperChaiChai** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced42auxuba7r4enlzxhfhft4hedfin65qk3vle5rwvunrlwnu7ssi 
#### Address 
> f1tjseop7cfi2re4gtvrd2vdjn7vmiyiezzisbenq
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f12mckci3omexgzoeosjvstcfxfe4vqw7owdia3da
#### Id
> c7bc0efb-fed7-4220-93f1-a78b6c82a2f6
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced42auxuba7r4enlzxhfhft4hedfin65qk3vle5rwvunrlwnu7ssi

**Comment by SuperChaiChai** [comment]
> ## Request Proposed
> Your Datacap Allocation Request has been proposed by the Notary
> 
> #### Message sent to Filecoin Network
> > bafy2bzaced42auxuba7r4enlzxhfhft4hedfin65qk3vle5rwvunrlwnu7ssi
> 
> #### Address
> > f1tjseop7cfi2re4gtvrd2vdjn7vmiyiezzisbenq
> 
> #### Datacap Allocated
> > 200.00TiB
> 
> #### Signer Address
> > f12mckci3omexgzoeosjvstcfxfe4vqw7owdia3da
> 
> #### Id
> > c7bc0efb-fed7-4220-93f1-a78b6c82a2f6
> 
> #### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced42auxuba7r4enlzxhfhft4hedfin65qk3vle5rwvunrlwnu7ssi

<img width="1034" alt="image" src="https://user-images.githubusercontent.com/42091141/227899898-ab6d67da-96f1-46ba-a65d-a10837bbf7a8.png">

**Comment by SuperChaiChai** [comment]
<img width="1029" alt="image" src="https://user-images.githubusercontent.com/42091141/227900852-fe390237-444a-4a35-bdcd-ebf71558ab52.png">

**Comment by METAVERSEDATAMINING** [comment]
Retrieval normal.
I noted that the distribution of SP is too concentrated.   Unless there is a reasonable reason, please follow the rules of "fil+" and distribute it in at least 3 regions.
As it is the beginning of the allocation, I will sign this round.
<img width="1120" alt="20230328111352" src="https://user-images.githubusercontent.com/111408360/228118499-42a5880f-a09c-4b8a-9857-193696d34503.png">

**Comment by METAVERSEDATAMINING** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedpvm4xj4ihgruyazoqbv2wok37sdqvenj5glkepj7ubvl5enb5we 
#### Address 
> f1tjseop7cfi2re4gtvrd2vdjn7vmiyiezzisbenq
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f17idrnfnxl2mbgcgr57a6z2c6lj2qx56gvm3336i
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedpvm4xj4ihgruyazoqbv2wok37sdqvenj5glkepj7ubvl5enb5we

**Comment by NDLABS-OFFICE** [comment]
checker:manualTrigger

**Comment by NDLABS-OFFICE** [comment]
Check bot is functioning properly, and the CID retrieval test is complete. We hope to connect more high-quality SPs in the subsequent storage.

**Comment by NDLABS-OFFICE** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacear5gmlxlu6iftbpeuvpoubkqnigkqb5m362x5nyohqszm6wjm6xw 
#### Address 
> f1tjseop7cfi2re4gtvrd2vdjn7vmiyiezzisbenq
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1yayfsv6whu3rheviucvventj3y6t542xfpb47ei
#### Id
> be8330be-98f5-4871-bdfa-da3af192b478
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacear5gmlxlu6iftbpeuvpoubkqnigkqb5m362x5nyohqszm6wjm6xw

**Comment by igoovo** [comment]
Everything seems normal

**Comment by igoovo** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaudkqd2hzuz447hpf5jxfqqet337eqrla3xdozcetk5hjrinzan2 
#### Address 
> f1tjseop7cfi2re4gtvrd2vdjn7vmiyiezzisbenq
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1shnsfayxqll77svffaxnjenms7bbbysbqcatrpy
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaudkqd2hzuz447hpf5jxfqqet337eqrla3xdozcetk5hjrinzan2

**Comment by sxxfuture-official** [comment]
![image](https://user-images.githubusercontent.com/113963951/229287595-a9561900-52bd-491f-9aed-d7750c4c870b.png)
![image](https://user-images.githubusercontent.com/113963951/229287626-5a2808c1-6517-49e9-969c-700c0868dbc0.png)

**Comment by sxxfuture-official** [comment]
filplus-check shows everything OK, and test retrieve complete.

**Comment by sxxfuture-official** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacearc3o5o5njf3nvip26sjytzcotzxl3ikcrjpbci5k5b2tazqr56s 
#### Address 
> f1tjseop7cfi2re4gtvrd2vdjn7vmiyiezzisbenq
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1foiomqlmoshpuxm6aie4xysffqezkjnokgwcecq
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacearc3o5o5njf3nvip26sjytzcotzxl3ikcrjpbci5k5b2tazqr56s

**Comment by newwebgroup** [comment]
https://filecoin.tools/f02090474
<img width="1291" alt="image" src="https://user-images.githubusercontent.com/100118145/229295227-2eb40aff-6fdc-47e3-9887-9cfd76f394b0.png">

**Comment by newwebgroup** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedwjebc3o65pvn5gxkdpu43daj3jd243nevzebxq5bml6ehkseepq 
#### Address 
> f1tjseop7cfi2re4gtvrd2vdjn7vmiyiezzisbenq
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1e77zuityhvvw6u2t6tb5qlnsegy2s67qs4lbbbq
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedwjebc3o65pvn5gxkdpu43daj3jd243nevzebxq5bml6ehkseepq

**Comment by stcouldlisa** [comment]
<img width="884" alt="WX20230405-213929@2x" src="https://user-images.githubusercontent.com/112812896/230097951-a48e3359-9e16-4d47-9deb-4944ec117963.png">

**Comment by stcouldlisa** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedj4rsyl6i5igjjn7fvqwsxd72tavnalwxtpshtinf4jzwgktbmba 
#### Address 
> f1tjseop7cfi2re4gtvrd2vdjn7vmiyiezzisbenq
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1jvvltduw35u6inn5tr4nfualyd42bh3vjtylgci
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedj4rsyl6i5igjjn7fvqwsxd72tavnalwxtpshtinf4jzwgktbmba

**Comment by stcouldlisa** [comment]
<img width="884" alt="WX20230405-213929@2x" src="https://user-images.githubusercontent.com/112812896/230105195-1a095b23-3b42-4b69-b9b7-b8463c467abf.png">

**Comment by bq1024** [comment]
The checker report looks good, however, almost all the deals were sent to SPs located in Asia, while you plan on making storage deals in ALL REGIONS. Can you distribute deals to other regions?

**Comment by bq1024** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecwzzo3jvnrmmm36mpq2okgwopobpswfkdhzt2y6ijevezgafhfec 
#### Address 
> f1tjseop7cfi2re4gtvrd2vdjn7vmiyiezzisbenq
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1pkjtavqx4r2q2w3he3jknfc5mo2vgfimccmpnaa
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecwzzo3jvnrmmm36mpq2okgwopobpswfkdhzt2y6ijevezgafhfec

**Comment by newwebgroup** [comment]
The CID Checker report looks normal
CID random check by tool
Retrieval result is successful
https://filecoin.tools/f02090474
<img width="1144" alt="image" src="https://user-images.githubusercontent.com/100118145/230750496-e2f1096f-08bb-4681-a846-7227ab0ca1eb.png">

**Comment by newwebgroup** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceamdnwn6vpjptbl6d6het262esleiptakoqehdrupvl536n3qeucm 
#### Address 
> f1tjseop7cfi2re4gtvrd2vdjn7vmiyiezzisbenq
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1e77zuityhvvw6u2t6tb5qlnsegy2s67qs4lbbbq
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceamdnwn6vpjptbl6d6het262esleiptakoqehdrupvl536n3qeucm

**Comment by Tom-OriginStorage** [comment]
Encapsulation is very healthy according to robot report, willing to support

**Comment by Tom-OriginStorage** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecgp6r64is4myd3nfuqpebylxsra46yb7f6ebo6623kfugl5geqcc 
#### Address 
> f1tjseop7cfi2re4gtvrd2vdjn7vmiyiezzisbenq
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1q6bpjlqia6iemqbrdaxr2uehrhpvoju3qh4lpga
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecgp6r64is4myd3nfuqpebylxsra46yb7f6ebo6623kfugl5geqcc

**Comment by baibailee12** [comment]
checker:manualTrigger

**Comment by baibailee12** [comment]
CID sharing has been observed. (Top 3)
Because of scripting issues, 25 Car's were sent in error.
The problem was detected during the order import phase
Stopped immediately at that time, these 25 orders had expired.
The PC1 PC2... phase did not continue and did not cause any bad effects

**Comment by zcfil** [comment]
checker:manualTrigger

**Comment by zcfil** [comment]
The data sampling sample is normal, and this round of audit has been passed.
![image](https://user-images.githubusercontent.com/45065975/233921869-0132e372-2946-4aed-8d0c-79710726c887.png)
![image](https://user-images.githubusercontent.com/45065975/233922273-6bc14097-b997-453d-8f3b-ed4504ea05c5.png)

**Comment by laurarenpanda** [comment]
> CID sharing has been observed. (Top 3) Because of scripting issues, 25 Car's were sent in error. The problem was detected during the order import phase Stopped immediately at that time, these 25 orders had expired. The PC1 PC2... phase did not continue and did not cause any bad effects

More about CID sharing, I have getton the following info from this Client via WeChat:

**f01919426 -  17 sectors：**
- https://filfox.info/en/message/bafy2bzacea7vds5hgbls6cgtqwjircpzcenanxbdnz5f5f2sw5gc5ab72v5jc
- https://filfox.info/en/message/bafy2bzacedj4wdqvpclfittsjbeptrcjmzcefg25xeuht34itvmdmzn4jfcfg
- https://filfox.info/en/message/bafy2bzacebxjksn4ieimcfjlhqyxuwoxoi54jk2fo3bupmdhw56zayscwu3si

**f02002918 - 8 sectors：**
https://filfox.info/en/message/bafy2bzacebxfpbs5ki5awsehvx6dqhijwdy74547c3e6c6ongs5cxqdrtqsag

It is acceptable on my side. However, please avoid the same error again.
Willing to support this round.

**Comment by laurarenpanda** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceactr5v3xznk6fszxmuqaig5r4cfaql5u6zrb6nnpfzwcmr4pvzwu 
#### Address 
> f1tjseop7cfi2re4gtvrd2vdjn7vmiyiezzisbenq
#### Datacap Allocated
> 1.56PiB
#### Signer Address
> f1bp3tzp536edm7dodldceekzbsx7zcy7hdfg6uzq
#### Id
> 9161013f-a905-4f06-9c36-785299978ddf
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceactr5v3xznk6fszxmuqaig5r4cfaql5u6zrb6nnpfzwcmr4pvzwu

**Comment by kernelogic** [comment]
Stats look OK.

**Comment by kernelogic** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced7ilarjlr5nnsehi5sj4jfq4zpjv5zf3zfhm5bvgqae3u65tkma4 
#### Address 
> f1tjseop7cfi2re4gtvrd2vdjn7vmiyiezzisbenq
#### Datacap Allocated
> 1.19PiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### Id
> not found
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced7ilarjlr5nnsehi5sj4jfq4zpjv5zf3zfhm5bvgqae3u65tkma4

**Comment by luobin544** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec3dzm43gdmieykoqfyzwbl4545o3476ncj6bpkmjhnoi5o7zozwq 
#### Address 
> f1tjseop7cfi2re4gtvrd2vdjn7vmiyiezzisbenq
#### Datacap Allocated
> 1.19PiB
#### Signer Address
> f1tbd632f6w62glfaf7wjpimacbnjiz26poyoes2q
#### Id
> not found
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec3dzm43gdmieykoqfyzwbl4545o3476ncj6bpkmjhnoi5o7zozwq
