### ISSUE TITLE
[DataCap Application] Kernelogic Slingshot Restore Program

### ISSUE THREAD

**Issue by kernelogic** [filecoin-project/filecoin-plus-large-datasets#136]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Kernelogic - Fei Yan - Slingshot Restore
- Website / Social Media: http://slingshot.kernelogic.ca/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 2PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 500TiB
- On-chain address for first allocation: f15djc5avdxihguvpmtej24rzbvnnqvzurxe55kja

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
I have participated every Slingshot phase and is probably the best performing as a "small individual miner". 

I am known for always storing data with many different community miners in different countries.
```

What is the primary source of funding for this project?
```
Prior slingshot rewards
```

What other projects/ecosystem stakeholders is this project associated with?
```
Slingshot restore program.
https://docs.google.com/forms/d/e/1FAIpQLScqM-UfmoAzC0jRrNhM0BUT2QuVotVqm_T7hTSHPmvaQZZTYg/viewform
```

## Use-case details

Describe the data being stored onto Filecoin
```
Any public dataset slingshot restore program committee assigns to me.

They will most likely come from this list https://github.com/filecoin-project/slingshot/blob/master/datasets.md
```

Where was the data in this dataset sourced from?
```
A variety sources, AWS, Azure, GCP, bittorrent and others.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://3kricegenome.s3.amazonaws.com/9311/IRIS_313-15896.realigned.bam
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes it is on the list of slingshot approved dataset.
```

What is the expected retrieval frequency for this data?
```
I am expecting some retrievals during prize judging period, as well as anyone interested in downloading this dataset.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
500 days according to program rules.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
5 continents according to program rules.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Yes I will upload my prepared CAR files to a web server and coordinate with miners to download and propose offline deals.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
Program committee will assign SPs to me.
```

How will you be distributing deals across storage providers?
```
Program committee will assign SPs to me.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes can start asap. I will need notaries to approve this quickly because the program is on a tight schedule.
```

**Comment by galen-mcandrew** [comment]
Getting a number of these projects, slightly editing the application titles for more distinction and clarity

**Comment by galen-mcandrew** [comment]
## Multisig Notary requested
#### Total DataCap requested 
> 2PiB
#### Expected weekly DataCap usage rate 
> 500TiB

**Comment by flyworker** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaosqnitau2t5s4iyzedlvtz6zzdkktljdxcjj3z2tjpg4wr4i4w6 
#### Address 
> f15djc5avdxihguvpmtej24rzbvnnqvzurxe55kja
#### Datacap Allocated
> 102TiB
#### Signer Address
> f1hlubjsdkv4wmsdadihloxgwrz3j3ernf6i3cbpy
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaosqnitau2t5s4iyzedlvtz6zzdkktljdxcjj3z2tjpg4wr4i4w6

**Comment by neogeweb3** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacealv4vqt7wtngnf5kthqvaech6zgm5omql7zrivxrx5tkbver6tbm 
#### Address 
> f15djc5avdxihguvpmtej24rzbvnnqvzurxe55kja
#### Datacap Allocated
> 102TiB
#### Signer Address
> f13k5zr6ovc2gjmg3lvd43ladbydhovpylcvbflpa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacealv4vqt7wtngnf5kthqvaech6zgm5omql7zrivxrx5tkbver6tbm

**Comment by flyworker** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacealbakjyjz56sibvo57ueupd2vvf35lkwsovrmpmj3x2qwt4bublw 
#### Address 
> f15djc5avdxihguvpmtej24rzbvnnqvzurxe55kja
#### Datacap Allocated
> 204TiB
#### Signer Address
> f1hlubjsdkv4wmsdadihloxgwrz3j3ernf6i3cbpy
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacealbakjyjz56sibvo57ueupd2vvf35lkwsovrmpmj3x2qwt4bublw

**Comment by swatchliu** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceamz7smnr7pgzq2n55m2kfejurkbrdjnayvf7zukgfgxfkxdiimpg 
#### Address 
> f15djc5avdxihguvpmtej24rzbvnnqvzurxe55kja
#### Datacap Allocated
> 204TiB
#### Signer Address
> f1yh6q3nmsg7i2sys7f7dexcuajgoweudcqj2chfi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceamz7smnr7pgzq2n55m2kfejurkbrdjnayvf7zukgfgxfkxdiimpg

**Comment by MegTei** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecp6gsssfqhfgab23tjjx7jvglskmp2whbfllypptxgetnzv3gmeo 
#### Address 
> f15djc5avdxihguvpmtej24rzbvnnqvzurxe55kja
#### Datacap Allocated
> 409.60TiB
#### Signer Address
> f1ystxl2ootvpirpa7ebgwl7vlhwkbx2r4zjxwe5i
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecp6gsssfqhfgab23tjjx7jvglskmp2whbfllypptxgetnzv3gmeo

**Comment by IreneYoung** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecxd5cxzhto43rlwus4gueejse534p2iaw4uajnjdjkzzzhreccxi 
#### Address 
> f15djc5avdxihguvpmtej24rzbvnnqvzurxe55kja
#### Datacap Allocated
> 409.60TiB
#### Signer Address
> f1d4gmpqz3execjj2wvrxuuhvbms5mzh7t7yqrviq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecxd5cxzhto43rlwus4gueejse534p2iaw4uajnjdjkzzzhreccxi

**Comment by Reiers** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb3x6e2ix3yova4jnwn2v36gxghs2hv5qghee7rirrlquqvxc2mgs 
#### Address 
> f15djc5avdxihguvpmtej24rzbvnnqvzurxe55kja
#### Datacap Allocated
> 819.20TiB
#### Signer Address
> f1oz43ckvmtxmmsfzqm6bpnemqlavz4ifyl524chq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb3x6e2ix3yova4jnwn2v36gxghs2hv5qghee7rirrlquqvxc2mgs

**Comment by dannyob** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceby3cgznzl5qycvfncvzdccp3n7635qf7jwmvemgcf6fyioxmke4e 
#### Address 
> f15djc5avdxihguvpmtej24rzbvnnqvzurxe55kja
#### Datacap Allocated
> 819.20TiB
#### Signer Address
> f1k6wwevxvp466ybil7y2scqlhtnrz5atjkkyvm4a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceby3cgznzl5qycvfncvzdccp3n7635qf7jwmvemgcf6fyioxmke4e

**Comment by kernelogic** [comment]
Thank you @Reiers and @dannyob for approving this!

**Comment by cryptowhizzard** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecifde567xq7hb7ase6dbuurmsgmsarsv2yx4i4i43asph3h3qmkc 
#### Address 
> f15djc5avdxihguvpmtej24rzbvnnqvzurxe55kja
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f1krmypm4uoxxf3g7okrwtrahlmpcph3y7rbqqgfa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecifde567xq7hb7ase6dbuurmsgmsarsv2yx4i4i43asph3h3qmkc

**Comment by Reiers** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceajfpb47wskmeagmqtuwobbwybn2kfxvrnsxt6n4xizod7flxsho4 
#### Address 
> f15djc5avdxihguvpmtej24rzbvnnqvzurxe55kja
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f1oz43ckvmtxmmsfzqm6bpnemqlavz4ifyl524chq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceajfpb47wskmeagmqtuwobbwybn2kfxvrnsxt6n4xizod7flxsho4

**Comment by kernelogic** [comment]
@fabriziogianni7 @simonkim0515 the last allocation approval did not work. Shows "ExitCode": 17.

https://filfox.info/en/message/bafy2bzaceajfpb47wskmeagmqtuwobbwybn2kfxvrnsxt6n4xizod7flxsho4

**Comment by fabriziogianni7** [comment]
@simonkim0515 @panges2

**Comment by kernelogic** [comment]
Is it because of this? But why it is zero though?
<img width="1316" alt="image" src="https://user-images.githubusercontent.com/3711825/200732354-d9e97e13-defb-4a0b-9ce0-845368ffc81c.png">

**Comment by cryptowhizzard** [comment]
Don't know what is going here but i get a message on the website that there is already a pending proposal for this one and i should contact the governance team when i am trying to approve this one.

**Comment by kernelogic** [comment]
Hey @cryptowhizzard thanks for checking it out. This one indeed having issue now and @fabriziogianni7 is looking into it.

**Comment by filplus-checker** [comment]
## DataCap and CID Checker Report[^1]
 - Organization: `Kernelogic - Fei Yan - Slingshot Restore`
 - Client: `f15djc5avdxihguvpmtej24rzbvnnqvzurxe55kja`
### Storage Provider Distribution
The below table shows the distribution of storage providers that have stored data for this client.

If this is the first time a provider takes verified deal, it will be marked as `new`.

For most of the datacap application, below restrictions should apply.
 - Storage provider should not exceed 25% of total datacap.
 - Storage provider should not be storing duplicate data for more than 20%.
 - Storage provider should have published its public IP address.
 - All storage providers should be located in different regions.

⚠️ [f01660837](https://filfox.info/en/address/f01660837) has unknown IP location.

| Provider                                                    |                               Location | Total Deals Sealed | Percentage | Unique Data | Duplicate Deals |
| :---------------------------------------------------------- | -------------------------------------: | -----------------: | ---------: | ----------: | --------------: |
| [f01660837](https://filfox.info/en/address/f01660837)       |                                Unknown |         113.42 TiB |      7.40% |  113.42 TiB |           0.00% |
| [f01926635](https://filfox.info/en/address/f01926635)       |     Hong Kong, Central and Western, HK |         111.24 TiB |      7.26% |  111.24 TiB |           0.00% |
| [f01885088](https://filfox.info/en/address/f01885088)       |     Hong Kong, Central and Western, HK |         111.23 TiB |      7.26% |  111.23 TiB |           0.00% |
| [f01933917](https://filfox.info/en/address/f01933917)       |     Hong Kong, Central and Western, HK |         111.20 TiB |      7.26% |  111.20 TiB |           0.00% |
| [f01732188](https://filfox.info/en/address/f01732188)       |                  Chicago, Illinois, US |          95.92 TiB |      6.26% |   95.92 TiB |           0.00% |
| [f066596](https://filfox.info/en/address/f066596)           |              San Diego, California, US |          91.25 TiB |      5.96% |   91.25 TiB |           0.00% |
| [f01702940](https://filfox.info/en/address/f01702940)       |                      Dallas, Texas, US |          82.44 TiB |      5.38% |   82.44 TiB |           0.00% |
| [f0143858](https://filfox.info/en/address/f0143858)         |                Clifton, New Jersey, US |          80.05 TiB |      5.23% |   80.05 TiB |           0.00% |
| [f010617](https://filfox.info/en/address/f010617)           |           Surrey, British Columbia, CA |          68.86 TiB |      4.50% |   66.52 TiB |           3.40% |
| [f01208189](https://filfox.info/en/address/f01208189)       |            Sydney, New South Wales, AU |          68.78 TiB |      4.49% |   59.50 TiB |          13.49% |
| [f01345523](https://filfox.info/en/address/f01345523)       |                Antwerpen, Flanders, BE |          57.72 TiB |      3.77% |   57.72 TiB |           0.00% |
| [f01392893](https://filfox.info/en/address/f01392893)       |           Amsterdam, North Holland, NL |          56.41 TiB |      3.68% |   56.41 TiB |           0.00% |
| [f01909705](https://filfox.info/en/address/f01909705)       |         Kuala Lumpur, Kuala Lumpur, MY |          42.19 TiB |      2.75% |   42.19 TiB |           0.00% |
| [f01918045](https://filfox.info/en/address/f01918045)       |         Kuala Lumpur, Kuala Lumpur, MY |          42.19 TiB |      2.75% |   42.19 TiB |           0.00% |
| [f01851482](https://filfox.info/en/address/f01851482)       |                       Busan, Busan, KR |          37.03 TiB |      2.42% |   37.03 TiB |           0.00% |
| [f01402814](https://filfox.info/en/address/f01402814)       |               Singapore, Singapore, SG |          37.03 TiB |      2.42% |   37.03 TiB |           0.00% |
| [f01119939](https://filfox.info/en/address/f01119939)       |                      Dallas, Texas, US |          36.94 TiB |      2.41% |   36.94 TiB |           0.00% |
| [f01864434](https://filfox.info/en/address/f01864434)       |            Sydney, New South Wales, AU |          36.03 TiB |      2.35% |   36.03 TiB |           0.00% |
| [f01208632](https://filfox.info/en/address/f01208632)`new`  |            Sydney, New South Wales, AU |          35.94 TiB |      2.35% |   35.94 TiB |           0.00% |
| [f0240185](https://filfox.info/en/address/f0240185)         |                Clifton, New Jersey, US |          34.81 TiB |      2.27% |   34.81 TiB |           0.00% |
| [f02301](https://filfox.info/en/address/f02301)             |               San Jose, California, US |          34.44 TiB |      2.25% |   34.44 TiB |           0.00% |
| [f03223](https://filfox.info/en/address/f03223)             |               San Jose, California, US |          30.19 TiB |      1.97% |   30.19 TiB |           0.00% |
| [f01652333](https://filfox.info/en/address/f01652333)       |              Sunnyvale, California, US |          24.70 TiB |      1.61% |   24.70 TiB |           0.00% |
| [f08403](https://filfox.info/en/address/f08403)             |      Bourton on the Water, England, GB |          24.38 TiB |      1.59% |   24.38 TiB |           0.00% |
| [f09848](https://filfox.info/en/address/f09848)             | Rancho Santa Margarita, California, US |          24.03 TiB |      1.57% |   24.03 TiB |           0.00% |
| [f01918046](https://filfox.info/en/address/f01918046)       |         Kuala Lumpur, Kuala Lumpur, MY |          23.44 TiB |      1.53% |   23.44 TiB |           0.00% |
| [f01111110](https://filfox.info/en/address/f01111110)       |                    Văn Điển, Hanoi, VN |           9.84 TiB |      0.64% |    9.84 TiB |           0.00% |
| [f01558688](https://filfox.info/en/address/f01558688)       |                   Toronto, Ontario, CA |           8.69 TiB |      0.57% |    8.69 TiB |           0.00% |
| [f01821041](https://filfox.info/en/address/f01821041)       |        Vancouver, British Columbia, CA |           1.53 TiB |      0.10% |    1.53 TiB |           0.00% |

![Provider Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/136/1671092583320.png)
### Deal Data Replication
The below table shows how each many unique data are replicated across storage providers.
- No more than 25% of unique data are stored with less than 4 providers.

⚠️ 28.94% of deals are for data replicated across less than 4 storage providers.

| Unique Data Size | Total Deals Made | Number of Providers | Deal Percentage |
| ---------------: | ---------------: | ------------------: | --------------: |
|         1.69 TiB |         1.69 TiB |                   1 |           0.11% |
|        18.81 TiB |        37.63 TiB |                   2 |           2.46% |
|       134.65 TiB |       403.95 TiB |                   3 |          26.37% |
|       448.00 GiB |         1.75 TiB |                   4 |           0.11% |
|        21.77 TiB |       109.27 TiB |                   5 |           7.13% |
|        27.34 TiB |       168.51 TiB |                   6 |          11.00% |
|        58.50 TiB |       414.28 TiB |                   7 |          27.04% |
|        21.69 TiB |       175.28 TiB |                   8 |          11.44% |
|        21.59 TiB |       194.53 TiB |                   9 |          12.70% |
|         2.47 TiB |        24.69 TiB |                  10 |           1.61% |
|        32.00 GiB |       352.00 GiB |                  11 |           0.02% |

![Replication Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/136/1671092586810.png)
### Deal Data Shared with other Clients
The below table shows how many unique data are shared with other clients.
Usually different applications owns different data and should not resolve to the same CID.

⚠️ CID sharing has been observed.

| Other Client                                                                                                                                                                                                              | Application                                                                                                                     | Total Deals Affected | Unique CIDs |        Verifier |
| :------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ | :------------------------------------------------------------------------------------------------------------------------------ | -------------------: | ----------: | --------------: |
| [f1j6pwjnuo5a6s4ou7emsx6jymam5nu4es7ogf7tq](https://filfox.info/en/address/f1j6pwjnuo5a6s4ou7emsx6jymam5nu4es7ogf7tq)                                                                                                     | [Fei Yan \- Kernelogic](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/304)                            |           453.09 TiB |       1,350 |       LDN # 304 |
| [f3wkoaov5p4ghrjtfk4lcwtloc3mr3vunxk37mkfm<br/>h4lwiqj5thj7wddjgvzaqz5eqdzgvbfrhgqhrvxzr<br/>mxva](https://filfox.info/en/address/f3wkoaov5p4ghrjtfk4lcwtloc3mr3vunxk37mkfmh4lwiqj5thj7wddjgvzaqz5eqdzgvbfrhgqhrvxzrmxva) | [Fei Yan \- Kernelogic](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/60)                             |           385.34 TiB |       2,155 |        LDN # 60 |
| [f3xbtxeptbmiuevsbjnnsntx6p37a7q6lbw4x7gdk<br/>dkiih2ha4qlymoayd2xwk2mpgbwdvgievlje7eivh<br/>3e3q](https://filfox.info/en/address/f3xbtxeptbmiuevsbjnnsntx6p37a7q6lbw4x7gdkdkiih2ha4qlymoayd2xwk2mpgbwdvgievlje7eivh3e3q) | [Fei Yan \- Kernelogic](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/59)                             |           340.80 TiB |       1,387 |        LDN # 59 |
| [f1pkrmygbvweykpjcut36lf7ewgqdfhjklbhvepda](https://filfox.info/en/address/f1pkrmygbvweykpjcut36lf7ewgqdfhjklbhvepda)                                                                                                     | [Protocol Labs \( project: Slingshot Evergreen \)](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/293) |           228.80 TiB |       3,082 |       LDN # 293 |
| [f1ufbhme24mzlo3mtzx3hkhte3xndpinq7xycezxi](https://filfox.info/en/address/f1ufbhme24mzlo3mtzx3hkhte3xndpinq7xycezxi)                                                                                                     | [HarryM \- Slingshot Restore](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/172)                      |            67.19 TiB |         794 |       LDN # 172 |
| [f1euejrtpg5vphqzydzleld2vgxfkhbrueiomz54y](https://filfox.info/en/address/f1euejrtpg5vphqzydzleld2vgxfkhbrueiomz54y)                                                                                                     | [Fei Yan \- Kernelogic](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/457)                            |            13.88 TiB |          54 | LDN v3 multisig |

[^1]: To manually trigger this report, add a comment with text `checker:manualTrigger`

**Comment by kernelogic** [comment]
Closing this one as the remaining DC cannot be signed and cannot be fixed by team.
