### ISSUE TITLE
[DataCap Application] GAMEWAY

### ISSUE THREAD

**Issue by xiand791** [filecoin-project/filecoin-plus-large-datasets#1360]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: GAMEWAY PTE. LTD.
- Website / Social Media: https://twitter.com/GameWayFun
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5 PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100TiB
- On-chain address for first allocation: f1lieed5tmnf6veepapaknygtz3fjpnv5n6tre3jy

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
The name of our organization is: GAMEWAY PTE. LTD. Since its establishment in 2021, we have established several teams in Singapore and Hangzhou, China, with a total number of about 20 people.
We are a vertical portal for blockchain games. We set up columns for games, KOL, and provide game information, strategy, data analysis and other services for chain game players. Besides, by linking game project parties, KOL, game guilds and players to build a chain game content ecology jointly and create an interactive position for chain game players. 
Through this platform to create a global chain game community - GameWay DAO.
```

What is the primary source of funding for this project?
```
There are three main sources of our current funding:
1. Early investors invest funds.
2. Fees for AMA activities of chain games, game announcements and media cooperation
3. Membership fee
```

What other projects/ecosystem stakeholders is this project associated with?
```
Our current business is closely related to the server supply chain and the application side on the decentralized storage. In addition, it is related to our storage service customers.
1. Regarding the server supply chain, we mainly have related cooperation with Alibaba Cloud
2. Regarding the application side of the decentralized storage, we currently have official website content data, Gamefi and other data 
3. Regarding our software service customers, their own data will be stored on our platform
```

## Use-case details

Describe the data being stored onto Filecoin
```
For now, basically are Gamefi and NFT related pictures, audios and docs.
```

Where was the data in this dataset sourced from?
```
Mainly from data stored when publishing content, Gamefi and minted NFT videos.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://drive.google.com/file/d/1f2XetSE3S239S__3G3qqudcSQXdkVX9A/view?usp=share_link
https://drive.google.com/file/d/1oQgkMAjgB8XE3qgZ12_Ummg5rDbHd4HE/view?usp=share_link
https://drive.google.com/file/d/1HNMsmFxbdwNyxUIrFLKBGrUx5CpwoFCe/view?usp=share_link
https://drive.google.com/file/d/1yYBIrmAkiJBBm5hSUQTboMDRJBEwHIV0/view?usp=share_link
https://drive.google.com/file/d/1nd7EARH9SrxEfdsYyycGsrob7tVS0vU9/view?usp=share_link
https://drive.google.com/file/d/1740Ur-hMKd3jsE8-XDgEs4IHqYUEmmGk/view?usp=share_link
https://drive.google.com/file/d/1HXMfxvXy-6-Q_JdCAaEJ6lEX_GOw6rZo/view?usp=share_link
https://drive.google.com/file/d/17-2B-2C-H4NqBov9m8VyLWn5WI-xXNWJ/view?usp=share_link
https://drive.google.com/file/d/1nWIRk6dbcQYlnTJCiUlr8zJAxC19ku_o/view?usp=share_link
https://drive.google.com/file/d/1eN6me-ZQRRHFrqWpWx380YHVVLEbuOso/view?usp=share_link
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
We confirm that the data we stored are all open source. 
```

What is the expected retrieval frequency for this data?
```
There is no fixed retrieval frequency fro this data, it base on customers willing. 
```

For how long do you plan to keep this dataset stored on Filecoin?
```
Most of data is required to stored permanently. 
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Currently planning in Singapore and some English-speaking countries.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
We currently distribute it manually.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We plan to develop a related automation way as soon as possible. For now, we do it by hand selection.
```

How will you be distributing deals across storage providers?
```
At present, we are mainly based on the personal wishes of the storage providers, and we will designate relevant standards for practice in the future.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, we have.
```

**Comment by liyunzhi-666** [comment]
hey @xiand791 , I've looked at the data samples and it looks good so far.

- Could you send an email to filplus-app-review@fil.org with your official domain in order to confirm your identity? Email name should includes the issue id. cc @Sunnyiscoming 
- Can you provide more detailed information about other storage providers participated in this program, such as you can list SPs you have contacted with at present?

**Comment by xiand791** [comment]
Hello: @liyunzhi-666 @@Sunnyiscoming
I have sent a KYC email, please check it.
We are currently looking at the following SPs:
f01854080; f01715155; f01168661; f01834253;
<img width="1045" alt="1" src="https://user-images.githubusercontent.com/116630087/207534561-8eee15e5-f446-49e3-aeff-1fd5aff24795.png">

**Comment by stcouldlisa** [comment]
what is your relationship with the company
How many copies do you plan to back up
Do you understand the rules of FIL+?
Can you promise that you will abide by the FIL+ rules, and each SP will not store more than 30%

**Comment by liyunzhi-666** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecqamr475j7zsq2u6nqrdbjyd2dj5nw3dkyixlclzt4yv3n7vnlkq 
#### Address 
> f1lieed5tmnf6veepapaknygtz3fjpnv5n6tre3jy
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1pszcrsciyixyuxxukkvtazcokexbn54amf7gvoq
#### Id
> b052ce82-34f8-4ff3-892f-3e6721929005
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecqamr475j7zsq2u6nqrdbjyd2dj5nw3dkyixlclzt4yv3n7vnlkq

**Comment by psh0691** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebjfovabct7g2ofwovecdhdnojcyb7hb2cb6mggdz4fs2txrh7bmc 
#### Address 
> f1lieed5tmnf6veepapaknygtz3fjpnv5n6tre3jy
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1qdko4jg25vo35qmyvcrw4ak4fmuu3f5rif2kc7i
#### Id
> b052ce82-34f8-4ff3-892f-3e6721929005
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebjfovabct7g2ofwovecdhdnojcyb7hb2cb6mggdz4fs2txrh7bmc

**Comment by Irmagogo** [comment]
checker:manualTrigger

**Comment by cryptowhizzard** [comment]
Hello,

This application has CID sharing with other applications. This means that you have not prepared "For now, basically are Gamefi and NFT related pictures, audios and docs." as you stated but just downloaded random data and made deals with this.

This is fraudulent and cannot be tolerated.
