### ISSUE TITLE
[DataCap Application] <XIAN SHIRUHUITU Technology Co., Ltd.> - <Robot learning & AI project>

### ISSUE THREAD

**Issue by xingyanfang87** [filecoin-project/filecoin-plus-large-datasets#1361]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: XIAN SHIRUHUITU Co., Ltd.
- Website / Social Media:https://v7.cn/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):3.5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):100TiB
- On-chain address for first allocation:f1o2grp6uhxvgngixohsukthvypqb5qs42o6tsabq

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Quickly extract and construct data association from multiple heterogeneous data such as documents, pictures, audio and video, spatio-temporal data, and accelerate the landing of data intelligent applications with AI capabilities
```

What is the primary source of funding for this project?
```
Project Income
```

What other projects/ecosystem stakeholders is this project associated with?
```
None
```

## Use-case details

Describe the data being stored onto Filecoin
```
We need a lot of input data for robots to learn, and then intelligently output document data and chart data for users to use
```

Where was the data in this dataset sourced from?
```
Data generated by the Company in conducting its business.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
Link：https://pan.baidu.com/wap/init?surl=69-0CMY40Bsuzo7PDJD5mw 
Extraction code：69qs
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes,it is
```

What is the expected retrieval frequency for this data?
```
No frequent retrieval is required. 1-2 times a year
```

For how long do you plan to keep this dataset stored on Filecoin?
```
2 years
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
China
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
We store the data on the storage device
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
we select 2 storage providers and require storage providers to be able to quickly retrieve
```

How will you be distributing deals across storage providers?
```
We will distribute them equally to the high-quality storage providers that pass our audit.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
The company will pay all expenses.
```

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 3.5PiB

**Expected weekly DataCap usage rate**

> 100TiB

**Client address**

>f1o2grp6uhxvgngixohsukthvypqb5qs42o6tsabq

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Looking at your application i have some questions:
As you are brand new on Github and have no history of past applications it seems to me that applying for 5PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?

Can you show us visible proof of the size of your data and the storage systems you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230337462961356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!
