### ISSUE TITLE
[DataCap Application] <SINOSOFT>

### ISSUE THREAD

**Issue by co1sinl** [filecoin-project/filecoin-plus-large-datasets#1366]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: sinosoft
- Website / Social Media: https://sinosoft.com.cn/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 400TiB
- On-chain address for first allocation: f1upfcp5lia6rfrbdljm2ppzcwvmllev3bbqfmgly

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Zhongke Soft Technology Co., Ltd. was established in 1996. In October 2000, it was reorganized into a joint stock company with the approval of the State Economic and Trade Commission, the Ministry of Finance and the Chinese Academy of Sciences. Relying on the strong talent advantages and leading scientific research achievements of the Chinese Academy of Sciences, Zhongkesoft Technology has been active in the forefront of China's industry information construction for more than 20 years. It is a large-scale professional high-tech enterprise engaged in computer software research and development, application and service. The company takes the development of industry application software as the core, and its business covers application software, support software, system integration and other application levels, and can provide customers with large-scale industry application solutions.
```

What is the primary source of funding for this project?
```
Company income and investment.
```

What other projects/ecosystem stakeholders is this project associated with?
```
None.
```

## Use-case details

Describe the data being stored onto Filecoin

```
1. Teaching recording video
2. software data
3. Exhibition video
```

Where was the data in this dataset sourced from?
```
business generation
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://drive.google.com/file/d/1ryXijSlahRUr_vxY-Pz0pcv8FUVzmdGI/view?usp=share_link
https://drive.google.com/file/d/1gq7A-yoxu-id_dOcVuG8YYXR9OkLxG1b/view?usp=share_link
```

Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes, we're pretty sure.
```

What is the expected retrieval frequency for this data?
```
1-3 times a year.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
At least 540 days.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Hong Kong or America.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Online download or offline mailing.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We prefer storage service providers with higher reliability.
```

How will you be distributing deals across storage providers?
```
Store to multiples SPs.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes.
```

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 400TiB

**Client address**

> f1upfcp5lia6rfrbdljm2ppzcwvmllev3bbqfmgly

**Comment by co1sinl** [comment]
We are contacting sp and will start packaging shortly.

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Looking at your application i have some questions:
As you are brand new on Github and have no history of past applications it seems to me that applying for 5PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?

Can you show us visible proof of the size of your data and the storage systems you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230337462961356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!

**Comment by co1sinl** [comment]
We are contacting sp, when everything is ready, we will start packaging.

**Comment by co1sinl** [comment]
@cryptowhizzard 
![56361677601425_ pic](https://user-images.githubusercontent.com/101273629/221915538-9ebcfcbc-f101-42c4-85a0-41cac1c674ce.jpg)
I have recently contacted sp, ready to package, I have submitted the relevant information, please sign for me, thank you.

**Comment by co1sinl** [comment]
@xinaxu  
![56571677682393_ pic](https://user-images.githubusercontent.com/101273629/222176973-0e7dd57f-b49b-4b96-a13b-6891fcd6e237.jpg)
This is the first batch of data directory tables that we plan to store on the filecoin network, mainly our software course videos, and we will organize more data to be stored on the filecoin network in the future, thank you.

**Comment by co1sinl** [comment]
@xinaxu 
![56811677683477_ pic](https://user-images.githubusercontent.com/101273629/222180664-b50d064b-fd4d-4384-b1ad-5da31d3abf12.jpg)
This is the first batch of data directory tables that we plan to store on the filecoin network, mainly our software course videos, and we will organize more data to be stored on the filecoin network in the future, thank you.

**Comment by co1sinl** [comment]
@cryptowhizzard 
hello, is there any problem with kyc? If not, can you sign it for me, thank you.

**Comment by co1sinl** [comment]
@cryptowhizzard 
hello, is there any problem with kyc? If not, can you sign it for me, thank you.

**Comment by cryptowhizzard** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced5zj7vtv2dghiiu2pkudtaeofzmdyvc2hdxb7pvqkaamvpjelcdi 
#### Address 
> f1upfcp5lia6rfrbdljm2ppzcwvmllev3bbqfmgly
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1krmypm4uoxxf3g7okrwtrahlmpcph3y7rbqqgfa
#### Id
> bab175c7-f5ed-4c65-a59c-1b736195216e
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced5zj7vtv2dghiiu2pkudtaeofzmdyvc2hdxb7pvqkaamvpjelcdi

**Comment by cryptowhizzard** [comment]
Hi!

Looking forward to your first milestone!

**Comment by luobin544** [comment]
checker:manualTrigger

**Comment by luobin544** [comment]
![10131682654358_ pic](https://user-images.githubusercontent.com/4277341/235050999-5143c64e-97b1-4077-9c2a-ede8b968a1a5.jpg)

**Comment by luobin544** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb3g7orpbkpmzrs6iih7vzixeyir4eaahgcfpjvp53z5qzwu3hp3y 
#### Address 
> f1upfcp5lia6rfrbdljm2ppzcwvmllev3bbqfmgly
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1tbd632f6w62glfaf7wjpimacbnjiz26poyoes2q
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb3g7orpbkpmzrs6iih7vzixeyir4eaahgcfpjvp53z5qzwu3hp3y

**Comment by SuperChaiChai** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecnc7o35e34x5gq47kgx4w7anf32aboigxkuq3nbhmq2optxwoayy 
#### Address 
> f1upfcp5lia6rfrbdljm2ppzcwvmllev3bbqfmgly
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f12mckci3omexgzoeosjvstcfxfe4vqw7owdia3da
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecnc7o35e34x5gq47kgx4w7anf32aboigxkuq3nbhmq2optxwoayy

**Comment by SuperChaiChai** [comment]
You need to add more SPs. If you need help, please feel free to contact me

**Comment by dongpo313** [comment]
checker:manualTrigger

**Comment by dongpo313** [comment]
checker:manualTrigger

**Comment by dongpo313** [comment]
checker:manualTrigger

**Comment by xinaxu** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb5kjspgajmj4d4luz5lxafihgw34kgehxqqmsm6ezep4iwb6nd7o 
#### Address 
> f1upfcp5lia6rfrbdljm2ppzcwvmllev3bbqfmgly
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1k3ysofkrrmqcot6fkx4wnezpczlltpirmrpsgui
#### Id
> 4b53babb-bfe6-41ad-9e33-ebf94cfc48dc
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb5kjspgajmj4d4luz5lxafihgw34kgehxqqmsm6ezep4iwb6nd7o

**Comment by Tom-OriginStorage** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedghdti2joed57hhxzialbuparpydtoniix6lgxbuqf6z3a6vtldc 
#### Address 
> f1upfcp5lia6rfrbdljm2ppzcwvmllev3bbqfmgly
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1q6bpjlqia6iemqbrdaxr2uehrhpvoju3qh4lpga
#### Id
> 4b53babb-bfe6-41ad-9e33-ebf94cfc48dc
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedghdti2joed57hhxzialbuparpydtoniix6lgxbuqf6z3a6vtldc

**Comment by dongpo313** [comment]
checker:manualTrigger

**Comment by dongpo313** [comment]
checker:manualTrigger

**Comment by dongpo313** [comment]
checker:manualTrigger

**Comment by dongpo313** [comment]
checker:manualTrigger

**Comment by dongpo313** [comment]
checker:manualTrigger

**Comment by mingyang313** [comment]
checker:manualTrigger

**Comment by psh0691** [comment]
checker:manualTrigger

**Comment by psh0691** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec4cgmpngmqedilzefo4ragzomjrdfgshav3jibgd2ejxyl7g2nas 
#### Address 
> f1upfcp5lia6rfrbdljm2ppzcwvmllev3bbqfmgly
#### Datacap Allocated
> 1.56PiB
#### Signer Address
> f1qdko4jg25vo35qmyvcrw4ak4fmuu3f5rif2kc7i
#### Id
> 43ed5909-03a3-4e81-ac9f-3525d2821529
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec4cgmpngmqedilzefo4ragzomjrdfgshav3jibgd2ejxyl7g2nas

**Comment by BDE-io** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb6m6zy5snnyzhhc52yuv2rwtk5i3r6sckcuigk3onp2zmvkdnpl2 
#### Address 
> f1upfcp5lia6rfrbdljm2ppzcwvmllev3bbqfmgly
#### Datacap Allocated
> 1.56PiB
#### Signer Address
> f1dvvrjur7tstos2paxdsvdpljqx53c74wsp5cl4q
#### Id
> 43ed5909-03a3-4e81-ac9f-3525d2821529
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb6m6zy5snnyzhhc52yuv2rwtk5i3r6sckcuigk3onp2zmvkdnpl2

**Comment by BDE-io** [comment]
i signed and approved this application because 

a. storage replication is distributed and i know that there's data prep work being done by data client and sent to a SP that (from my understanding) has no direct relationship with the data client 
b. there's some retrieval

@co1sinl - going forward, it will be helpful if the data can be distributed across more regions. thank  you!

**Comment by dongpo313** [comment]
checker:manualTrigger

**Comment by Sunnyiscoming** [comment]
⚠️ [f01697248](https://filfox.info/en/address/f01697248) has sealed 54.33% of total datacap.
Please explain about it.
f0155829 Whether this sp provide data retrieval?

**Comment by co1sinl** [comment]
Regarding the retrieval issue, we have already contacted SP to handle it. SP, f01697248, has completed downloading the data first, while the other SPs are catching up.

**Comment by cryptowhizzard** [comment]
Hello,

All attempts to receive data from you resulted in:

ERROR: offer error: retrieval query offer errored: failed to fetch piece to retrieve from: getting pieces for cid bafykbzacedzcit4kd54e23vq3e2p35vvnmatlbcpjkcsnm23kcfcre5ol5f6c: getting pieces containing block bafykbzacedzcit4kd54e23vq3e2p35vvnmatlbcpjkcsnm23kcfcre5ol5f6c: failed to lookup index for mh a0e40220f2244f8a1f784d6eb0d934fdf6b56b0135844f4a8526b35b508a2893ae5f4be1, err: datastore: key not found

**Comment by cryptowhizzard** [comment]
Dear co1sinl,

As notary I am doing due diligence on your LDN. I could not get retrieval to work. Can you please upload the car file of CID baga6ea4seaqfj27uo2jntacco3bcp5f4wnuuknqr274icbmx4zrjimf65jgy6bi ?

You can use our upload system at http://send.datasetcreators.com. Please select 7 days for the system to keep the file and post the link you received here so I (and other notaries) can download your content.

**Comment by hyunmoon** [comment]
It looks like `baga6ea4seaqfj27uo2jntacco3bcp5f4wnuuknqr274icbmx4zrjimf65jgy6bi` has not been announced properly as I can not search it on cid.contact.

I just ran `boostd index announce-all` and I'm checking if it makes any changes.
I check find `baga6ea4seaqfj27uo2jntacco3bcp5f4wnuuknqr274icbmx4zrjimf65jgy6bi` in my boost databsse fine so I think I can get this issue resolved soon.

**Comment by hyunmoon** [comment]
I can see `baga6ea4seaqfj27uo2jntacco3bcp5f4wnuuknqr274icbmx4zrjimf65jgy6bi` in my boost db but it seems to have not been annoucned properly as I can't search it on cid.contact.
I just ran `boostd index announce-all` and I'm trying to find what else I can do to fix the problem.

**Comment by hyunmoon** [comment]
It appears I'm affected by this issue here: [https://boost.filecoin.io/v/v1/troubleshooting#fix-retrievals-with-error-failed-to-lookup-index-for-mh](url)

**Comment by hyunmoon** [comment]
![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/2242149/214428a0-5b59-40ab-b99a-e4f859d9b890)

I can confirm that this works:
`boost retrieve -p f01697248 -o file.car bafykbzaceboe5vho6bybcpz5joxy3meta5syhxvntzvlnzapx3bvfj6sfy4sq`

**Comment by hyunmoon** [comment]
If retrieval by PieceCID is supposed to work, then it's failing because I'm dealing with this issue:
https://boost.filecoin.io/v/v1/troubleshooting#fix-retrievals-with-error-failed-to-lookup-index-for-mh

**Comment by Sunnyiscoming** [comment]
> the other SPs are catching up.

Please list a specific plan for the next step.

**Comment by co1sinl** [comment]
The three new service providers will complete the downloads and start packaging next week. All the remaining quotas in the final round will be allocated to them to meet FIL+'s data distribution requirements.

**Comment by co1sinl** [comment]
it's in use.

**Comment by mingyang313** [comment]
checker:manualTrigger

**Comment by co1sinl** [comment]
Regarding CID sharing, we can see that we have a common service provider (SP) client. The SP made some mistakes while preparing the data, but luckily, we discovered and resolved them promptly as the project just started. The sharing did not continue to increase. 
Regarding data distribution, the three new SPs we introduced have already finished downloading the data,They will begin packaging it today. All remaining quotas will be allocated to them.

**Comment by cryptowhizzard** [comment]
Hi,

I see that one SP received more then 60% of the total granted datacap.
Can you explain?

<img width="1266" alt="Scherm­afbeelding 2023-09-12 om 09 15 40" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/36404435/50d6f530-08c5-4177-970f-07237a2ae08f">

**Comment by co1sinl** [comment]
f01697248 had completed the data downloading firstly.
rencently,the three new SPs we introduced had already finished  the data downloading,They will begin sealing it this week. All remaining quotas will be allocated to them.

**Comment by co1sinl** [comment]
it works.

**Comment by co1sinl** [comment]
it works.

**Comment by Tom-OriginStorage** [comment]
Overall relatively healthy and willing to support

**Comment by Tom-OriginStorage** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedl734appl3wxqjzxxhuh2bxh4eeopu3ueyxqkrw7htqedpsxok7q 
#### Address 
> f1upfcp5lia6rfrbdljm2ppzcwvmllev3bbqfmgly
#### Datacap Allocated
> 1.56PiB
#### Signer Address
> f1q6bpjlqia6iemqbrdaxr2uehrhpvoju3qh4lpga
#### Id
> 4ff481bc-18c3-49b6-ae12-6608d88bb469
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedl734appl3wxqjzxxhuh2bxh4eeopu3ueyxqkrw7htqedpsxok7q

**Comment by SuperChaiChai** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceahowlbjm4pu2okrp477q3qsta6u73n5avqk7veuvtjlnz5vwdhle 
#### Address 
> f1upfcp5lia6rfrbdljm2ppzcwvmllev3bbqfmgly
#### Datacap Allocated
> 1.56PiB
#### Signer Address
> f12mckci3omexgzoeosjvstcfxfe4vqw7owdia3da
#### Id
> 4ff481bc-18c3-49b6-ae12-6608d88bb469
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceahowlbjm4pu2okrp477q3qsta6u73n5avqk7veuvtjlnz5vwdhle

**Comment by co1sinl** [comment]
checker:manualTrigger

**Comment by luobin544** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedwa6ywz36emvylahcwelumgb5bzsdetgm4pchq456c7nkvplxhlm 
#### Address 
> f1upfcp5lia6rfrbdljm2ppzcwvmllev3bbqfmgly
#### Datacap Allocated
> 725.11TiB
#### Signer Address
> f1tbd632f6w62glfaf7wjpimacbnjiz26poyoes2q
#### Id
> 3d22630b-8d17-45b3-828f-b0f7e6a06c31
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedwa6ywz36emvylahcwelumgb5bzsdetgm4pchq456c7nkvplxhlm

**Comment by 1ane-1** [comment]
Slack contact me and it has been explained before about the report. Support for this round and always supervise you.

**Comment by 1ane-1** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacediendatwpqfs4h222ctmgp5odgetq7ztsyoh64xoh6gcez4ytwtm 
#### Address 
> f1upfcp5lia6rfrbdljm2ppzcwvmllev3bbqfmgly
#### Datacap Allocated
> 725.11TiB
#### Signer Address
> f1mdk7s2vntzm6hu35yuo6vjubtrpfnb2awhgvrri
#### Id
> 3d22630b-8d17-45b3-828f-b0f7e6a06c31
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacediendatwpqfs4h222ctmgp5odgetq7ztsyoh64xoh6gcez4ytwtm

**Comment by Sunnyiscoming** [comment]
Hello, @co1sinl per the https://github.com/filecoin-project/notary-governance/issues/922 for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

This information will be reviewed by Fil+ Governance team to confirm validity and then the application will be allowed to move forward for additional notary review.
