### ISSUE TITLE
[DataCap Application] < Chengdu Qingting Precision Health Management Co., Ltd  > - <Medical, health, pension, etc.>

### ISSUE THREAD

**Issue by hxcstar** [filecoin-project/filecoin-plus-large-datasets#1371]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Chengdu Qingting Precision Health Management Co., Ltd 
- Website / Social Media:http://qingtingjk.com/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):3PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):100TiB
- On-chain address for first allocation: f1bh7mz3awixqm3hx4hotp2qvs7xo54lacougghli

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Chengdu Qingting Precision Health Management Co., Ltd. (hereinafter referred to as "Qingting Health") is jointly established by Sino-American Xaar Biotechnology (Guangdong) Co., Ltd., Zhuhai Hengqin Ruiherui Financial Leasing Co., Ltd., Chengdu Huarinke Biotechnology Co., Ltd. and other health enterprises. Its group company has 23 years of precipitation in the precision medicine industry, with 3 cell laboratories, 6 regional treatment centers, and more than 50 medical, health, pension and other institutions in China, and its business involves all over the country; The core technology system is the cutting-edge life science system at home and abroad, focusing on cell therapy, gene therapy and microecological therapy; At present, it has 108 patents, and the expert team involves a number of related fields, and has more than 20 research projects in cooperative institutions.


In 2019, Qingting Health began to get involved in the fields of health real estate and rural revitalization, and successively cooperated with Greenland Group and Longji Group to build two projects in Chengdu: Qingting International Precision Wellness Center and Qingting Wuxiang Precision Medical Hotel. The project integrates regenerative medicine, functional medicine, energy medicine, natural medicine, traditional Chinese medicine, Taoist medicine, gongfa and other technical systems, and is currently a sample project of medical tourism, health care, ecological healing, pastoral healing, healing hotel, and rural revitalization in southwest China.
```

What is the primary source of funding for this project?
```
Our own funds and those of our partners.
```

What other projects/ecosystem stakeholders is this project associated with?
```
None.
```

## Use-case details

Describe the data being stored onto Filecoin
```
Our business development will involve the use of a large number of data sets, which are mainly used for the storage of medical, health, and elderly care data. The data includes: video, image, audio, text, etc.
```

Where was the data in this dataset sourced from?
```
The data comes from the company.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://drive.google.com/drive/folders/17pN7HT93bp9FVFfBMw-ypT6znXF2U7sk?usp=share_link
https://drive.google.com/file/d/1POL4hh4u92_5LhGSonN_RYuwAVOeKu24/view?usp=share_link
https://drive.google.com/file/d/1CHKLP9zeCovyCiT-rTIDeaTJc-tKLk6J/view?usp=share_link
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Confirm.
```

What is the expected retrieval frequency for this data?
```
2-3 times a quarter.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
At least 32 months.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
We do not limit any region.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
online and offline.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We will choose storage providers with high reputation and strong confidentiality for transactions. Before we cooperate, we will understand their scale, whether they are reliable, whether they have hard-core hardware equipment and professional technical teams. The security of data storage is very important.
```

How will you be distributing deals across storage providers?
```
We will select large-scale, reputable, stable and secure storage service providers according to the rules and distribute them in proportion.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, we have enough funds to trade and we can easily cover these fees.
```

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 3PiB

**Expected weekly DataCap usage rate**

> 100TiB

**Client address**

> f1f1bh7mz3awixqm3hx4hotp2qvs7xo54lacougghli

**Comment by NDLABS-OFFICE** [comment]
can you send email to [[filplus-app-review@fil.org](mailto:filplus-app-review@fil.org)]

**Comment by hxcstar** [comment]
I have replied. Please confirm it
![qt](https://user-images.githubusercontent.com/28218867/206654391-19febc36-8434-4f24-a3f2-187dee014378.png)

**Comment by hxcstar** [comment]
My client address to submit error, error address: f1f1bh7mz3awixqm3hx4hotp2qvs7xo54lacougghli, changed to the correct address: f1bh7mz3awixqm3hx4hotp2qvs7xo54lacougghli. Please recheck it for me

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Looking at your application i have some questions:
As you are brand new on Github and have no history of past applications it seems to me that applying for 5PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?

Can you show us visible proof of the size of your data and the storage systems you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230337462961356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!

**Comment by hxcstar** [comment]
> # Large Dataset Notary Application
> To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.
> 
> ## Core Information
> * Organization Name: Chengdu Qingting Precision Health Management Co., Ltd
> * Website / Social Media:http://qingtingjk.com/
> * Total amount of DataCap being requested (between 500 TiB and 5 PiB):3PiB
> * Weekly allocation of DataCap requested (usually between 1-100TiB):100TiB
> * On-chain address for first allocation: f1bh7mz3awixqm3hx4hotp2qvs7xo54lacougghli
> 
> _Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._
> 
> ## Project details
> Share a brief history of your project and organization.
> 
> ```
> Chengdu Qingting Precision Health Management Co., Ltd. (hereinafter referred to as "Qingting Health") is jointly established by Sino-American Xaar Biotechnology (Guangdong) Co., Ltd., Zhuhai Hengqin Ruiherui Financial Leasing Co., Ltd., Chengdu Huarinke Biotechnology Co., Ltd. and other health enterprises. Its group company has 23 years of precipitation in the precision medicine industry, with 3 cell laboratories, 6 regional treatment centers, and more than 50 medical, health, pension and other institutions in China, and its business involves all over the country; The core technology system is the cutting-edge life science system at home and abroad, focusing on cell therapy, gene therapy and microecological therapy; At present, it has 108 patents, and the expert team involves a number of related fields, and has more than 20 research projects in cooperative institutions.
> 
> 
> In 2019, Qingting Health began to get involved in the fields of health real estate and rural revitalization, and successively cooperated with Greenland Group and Longji Group to build two projects in Chengdu: Qingting International Precision Wellness Center and Qingting Wuxiang Precision Medical Hotel. The project integrates regenerative medicine, functional medicine, energy medicine, natural medicine, traditional Chinese medicine, Taoist medicine, gongfa and other technical systems, and is currently a sample project of medical tourism, health care, ecological healing, pastoral healing, healing hotel, and rural revitalization in southwest China.
> ```
> 
> What is the primary source of funding for this project?
> 
> ```
> Our own funds and those of our partners.
> ```
> 
> What other projects/ecosystem stakeholders is this project associated with?
> 
> ```
> None.
> ```
> 
> ## Use-case details
> Describe the data being stored onto Filecoin
> 
> ```
> Our business development will involve the use of a large number of data sets, which are mainly used for the storage of medical, health, and elderly care data. The data includes: video, image, audio, text, etc.
> ```
> 
> Where was the data in this dataset sourced from?
> 
> ```
> The data comes from the company.
> ```
> 
> Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this.
> 
> ```
> https://drive.google.com/drive/folders/17pN7HT93bp9FVFfBMw-ypT6znXF2U7sk?usp=share_link
> https://drive.google.com/file/d/1POL4hh4u92_5LhGSonN_RYuwAVOeKu24/view?usp=share_link
> https://drive.google.com/file/d/1CHKLP9zeCovyCiT-rTIDeaTJc-tKLk6J/view?usp=share_link
> ```
> 
> Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
> 
> ```
> Confirm.
> ```
> 
> What is the expected retrieval frequency for this data?
> 
> ```
> 2-3 times a quarter.
> ```
> 
> For how long do you plan to keep this dataset stored on Filecoin?
> 
> ```
> At least 32 months.
> ```
> 
> ## DataCap allocation plan
> In which geographies (countries, regions) do you plan on making storage deals?
> 
> ```
> We do not limit any region.
> ```
> 
> How will you be distributing your data to storage providers? Is there an offline data transfer process?
> 
> ```
> online and offline.
> ```
> 
> How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
> 
> ```
> We will choose storage providers with high reputation and strong confidentiality for transactions. Before we cooperate, we will understand their scale, whether they are reliable, whether they have hard-core hardware equipment and professional technical teams. The security of data storage is very important.
> ```
> 
> How will you be distributing deals across storage providers?
> 
> ```
> We will select large-scale, reputable, stable and secure storage service providers according to the rules and distribute them in proportion.
> ```
> 
> Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
> 
> ```
> Yes, we have enough funds to trade and we can easily cover these fees.
> ```
