### ISSUE TITLE
[DataCap Application] Song An Group 

### ISSUE THREAD

**Issue by ANDoooL** [filecoin-project/filecoin-plus-large-datasets#1388]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Song An Group 
- Website / Social Media: www.songangroup.com
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 4.5 PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100 TiB
- On-chain address for first allocation: f12vgjkxwyr2efu5loua6b2lojveoymcofgbndlxa

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Shenzhen Song An Group PTE Ltd. was founded in 2008, with a registered capital of 52.8 million yuan, headquartered in the center of Longgang District, Shenzhen City, Guangdong Province, the company's purpose is "digital intelligence empowerment - to build a smart city ecological rainforest", layout industry ecology, build business map, and serve the development of the city.
For more than ten years, Songan Industrial Group has been based on service foundation, seeking development by technology, seeking leap by innovation, and continuously cultivating "new species" of wisdom industry of the group, gradually forming a multi-business sequence with city wisdom housekeeper, information technology and security service as the main body, forming a more complete set of city housekeeping service, emergency linkage command, security The company has formed a one-stop and full-chain urban service system, including urban butler service, emergency linkage command, security training, and comprehensive solutions for smart cities. At the same time, on the basis of deep plowing the market in Shenzhen and Hunan and helping to build a wisdom demonstration city, we have been expanding our business blueprint, and our service scope has been expanded from Shenzhen to the Greater Bay Area, Yangtze River Economic Belt and other regions, with more than 20 branches and 7 subsidiaries, with a workforce of over 5,000 people and a team of 100 management cadres and professional technical teams selected and cultivated, and now the group company is serving and operating nearly 300 projects.

```

What is the primary source of funding for this project?
```
Self-funding
```

What other projects/ecosystem stakeholders is this project associated with?
```
No
```

## Use-case details

Describe the data being stored onto Filecoin
```
Mostly are our drone videos
```

Where was the data in this dataset sourced from?
```
Self produced.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
Yes.
https://1drv.ms/u/s!At3d4pe1hAcAatHrtcB9jZ94tBA?e=cbM7Q9
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Confirm.
```

What is the expected retrieval frequency for this data?
```
once per year.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
At least 3 years.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Preferablely China and Asia area.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
We have prepared enough storage for offline transfer among China. However we are able to provide online transfer link for the rest of the world.  
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We are actively looking for SPs in Slack Filecoin channel.
```

How will you be distributing deals across storage providers?
```
We will obey the FIL+ allocation rules.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes.
```

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 4.5PiB

**Expected weekly DataCap usage rate**

> 100TiB

**Client address**

> f12vgjkxwyr2efu5loua6b2lojveoymcofgbndlxa

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Looking at your application i have some questions:
As you are brand new on Github and have no history of past applications it seems to me that applying for 5PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?

Can you show us visible proof of the size of your data and the storage systems you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230337462961356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!

**Comment by cryptowhizzard** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecldsl2cgldzvwr5h6sxiei4j6eymzqgfd2gslosxovc6meyehzsa 
#### Address 
> f12vgjkxwyr2efu5loua6b2lojveoymcofgbndlxa
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1krmypm4uoxxf3g7okrwtrahlmpcph3y7rbqqgfa
#### Id
> 20bdb7e4-bb10-4eb6-a0a6-aa127d8650c5
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecldsl2cgldzvwr5h6sxiei4j6eymzqgfd2gslosxovc6meyehzsa
