### ISSUE TITLE
[DataCap Application] VMware - Open Source Data Preservation (Salt and Idem)

### ISSUE THREAD

**Issue by alexpeay** [filecoin-project/filecoin-plus-large-datasets#1390]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: VMware (Salt and Idem Open Source Project Maintainers)
- Website / Social Media: https://twitter.com/Salt_Project_OS
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 2 PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 50 TiB
- On-chain address for first allocation: f3vcwv646rqlwp5izprt3sflwmfbbkxxroglaswjp2jhhel6gbj3lko3frjag3c2zpfqhtwubik3jdridhcqoq

## Project details

Share a brief history of your project and organization.
```
VMware has a number of open source projects, mostly through acquisition. This project is an attempt to ensure consistency and perseverance of these open source projects regardless of the commercial direction of the company. Projects like Salt have been providing for the infrastructure needs for 10s of thousands of clients for over a decade. This includes many not for profit and government agencies like JPL and NASA. This project will create an archive of the pipeline data, documentation, and enablement from previous versions of Salt and Idem initially to allow for a long lasting archive that can be access for groups that may be on older, no longer supported versions of the software. If this is successful it could expand to other VMware open source projects.

```

What is the primary source of funding for this project?
```
This project is being funded by VMware as a validation project to see if providing replicas for this data on Filecoin is a viable option. This is being driven by the Salt and Idem Open Source teams.

```

What other projects/ecosystem stakeholders is this project associated with?
```
none
```

## Use-case details

Describe the data being stored onto Filecoin
```
It takes a variety of different sets of data to properly run an open source project. We have found that through transitions within commercial organizations things can become lost either due to acquisition or simply employee turn over. This project would serve as an archive that the community (and entire internet) would have access to, allowing for retrieval of specific data around architecutre, marketing, enablement, code and pipeline data. Ensuring that regardless of who the maintainers of the project are the assets that make the project consumable are always available to those who use the project for infrastructure management. 
```

Where was the data in this dataset sourced from?
```
Various code repositories, pipelines, marketing repositories, and documentation archives:
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://github.com/saltstack/salt
https://docs.saltproject.io/en/latest/topics/releases/3005.1.html
https://gitlab.com/vmware/idem
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes, these data sets are public
```

What is the expected retrieval frequency for this data?
```
Yearly
```

For how long do you plan to keep this dataset stored on Filecoin?
```
3 + years
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
North America
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
HTTP or FTP Server
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We are currently discussing capabilities and performing due diligence with several SPs. We chose these based on their current storage capacity, compute capabilities, enterprise-grade DCs and bandwidth and their familiarity and passion for open source software.

```

How will you be distributing deals across storage providers?
```
Boost Client
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes
```

**Comment by Sunnyiscoming** [comment]
What's the relationship between you and the organization? Why didn't you use an github handle of SaltStack to apply?
Can you provide more detailed information about other storage providers participated in this program, such as you can list SPs you have contacted with at present?

**Comment by alexpeay** [comment]
I was the head of Product for Salt Project prior to SaltStack being acquired by VMware. Upon acquisition the SaltStack emails were removed. Since this work is more on behalf of the community I used my personal email rather than my VMware email. While my initial focus will be the Salt and Idem projects which came to VMware as part of the VMware acquisition of SaltStack, if successful this can expand to other Open Source communities that are being potentially disrupted through acquisitions (which for now includes all Open projects within VMware as Broadcom finalizes their acquisition of VMware).

We have started having discussions with BigDataExchange to understand how we can use that platform to get additional Storage Providers engaged. Additionally we met yesterday with Porter Stowell to gain some insights on the SP community within the US. 

The first SP that we will work with to prove the flow of this data for the first replica is a new SP named Moria Data who we have a relationship with through the Salt community. Moria has available capacity and a 10 GPS connection and can start working with the first replica immediately.

**Comment by alexpeay** [comment]
@simonkim0515 and @Sunnyiscoming I am not sure what needs to happen next for this to be signed. I would like to start in full force on this project in the new year. 

Is the next step on me or is it something else in the process I am waiting on? Looking at the documentation and some other applications it looks like the next step is a notary proposal but I don't see how I trigger that. Any help would be appreciated.

Thanks,
Alex

**Comment by jamerduhgamer** [comment]
@simonkim0515, I would like to support @alexpeay's application here as they are an ESPA participant from Cohort 5 and will be working with PiKNiK on this dataset.

**Comment by cryptowhizzard** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebimjzesgbm7o6vxs5qqcrhjv4pv3paddfpiovixjactogq6fwgju 
#### Address 
> f3vcwv646rqlwp5izprt3sflwmfbbkxxroglaswjp2jhhel6gbj3lko3frjag3c2zpfqhtwubik3jdridhcqoq
#### Datacap Allocated
> 25.00TiB
#### Signer Address
> f1krmypm4uoxxf3g7okrwtrahlmpcph3y7rbqqgfa
#### Id
> 851baad9-d617-4d26-b80c-7e995f2d1b4b
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebimjzesgbm7o6vxs5qqcrhjv4pv3paddfpiovixjactogq6fwgju
