### ISSUE TITLE
[DataCap Application] Xi'an Qinchu Technology Co., Ltd.

### ISSUE THREAD

**Issue by tuo1niao** [filecoin-project/filecoin-plus-large-datasets#1392]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Xi'an Qinchu Technology Co., Ltd.
- Website / Social Media:http://qinlianyun.com/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):100TiB
- On-chain address for first allocation:f1twzys26cthye7xdpaipqyaksqzw46bv22u6iami

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Xi'an Qinchu Technology Co., Ltd. is the chairman unit of the Xi'an Blockchain Technology Application Association, featuring blockchain technology, providing industry + blockchain comprehensive solutions, and innovative Web 3.0 Internet products. Founded in 2015, the company focuses on cloud computing, big data, Internet of Things, blockchain, artificial intelligence and other technology research and development, focusing on important fields such as "government affairs, education, justice, people's livelihood, medical care, and finance", relying on strong technical research and development capabilities , Rich experience in blockchain underlying technology and application research and development, through value Internet infrastructure such as "independent and controllable blockchain basic service platform" and "Qin Chuyun distributed storage system", serve the government, empower enterprises, and provide high-quality and efficient Product integration comprehensive solutions and Web3.0 new form Internet products.
```

What is the primary source of funding for this project?
```
We are rich and resourceful
```

What other projects/ecosystem stakeholders is this project associated with?
```
No.
```

## Use-case details

Describe the data being stored onto Filecoin
```
The data mainly includes design schemes, picture materials, 3D materials, software development logs, user data and other data.
```

Where was the data in this dataset sourced from?
```
It comes from the plans, logs and business data generated by the Qin Chu Data Storage platform when designing plans and maintaining operations for customers.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
Link: https://pan.baidu.com/s/14DbtkamiLFfRPhxuxT5btA
Extraction code: 1we4 
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes.
```

What is the expected retrieval frequency for this data?
```
We plan about 4 times a year.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
3 years
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Any region is fine
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Both online and offline transfers are possible
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We plan to choose some reliable, qualified and stable storage providers
```

How will you be distributing deals across storage providers?
```
We also decide how much to allocate based on the actual capacity of the sps. but we'll try to evenly distribute
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Have enough resources.
```

**Comment by Sunnyiscoming** [comment]
The data samples you provided seems to contain data from the user, such as pictures. Have you authorized to store these data as public data on Filecoin network? Please provide related materials to prove that.
Can you explain your data composition and provide sufficient data samples separately? How many copies will you store?
What's the relationship between you and the organization?
Can you provide more detailed information about other storage providers participated in this program, such as you can list SPs you have contacted with at present?
Whether the sps you choose can support data retrieval?

**Comment by Sunnyiscoming** [comment]
Close for no reply.
