### ISSUE TITLE
[DataCap Application] <Education> 

### ISSUE THREAD

**Issue by stakecom** [filecoin-project/filecoin-plus-large-datasets#1394]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Beijing Xuechuan Technology Co.,Ltd.
- Website / Social Media: https://www.bjxctec.com/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):100TiB
- On-chain address for first allocation:f1m2ocyzqqpb2b7t7vfkrclpwfenswjjoxkl4fe7a

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
The advantages of Xuechuan Technology in communication, resources, platforms, and technologies are different from and superior to other market-oriented enterprises. The company has more than 20 software copyrights, and mainly provides "Smart Education (Campus) 2.0 Cloud Platform", "Online Education Cloud platform", "big data platform", "after-school 3:30 education service platform" and other software and hardware supporting services, providing Xuechuan technology integration solutions for the development of high-quality education, and also laying the foundation for the development of smart education construction business A solid foundation, among them, the "Xuechuan Smart Education Cloud Platform" with comprehensive functions, easy to learn and practical, strong integration, and down-to-earth; Products such as the "light school" that makes teaching easier and the "smart electronic student ID card" that replaces smartphones have been promoted and used in educational institutions and schools across the country, and have received good results. Standardized management is an important support for improving the high-quality development of educational institutions. Its smart education platform has been listed by the Ministry of Education as "National Basic Education Informatization Application Areas and Typical Demonstration Cases of School Promotion".
```

What is the primary source of funding for this project?
```
Company revenues.
```

What other projects/ecosystem stakeholders is this project associated with?
```
None.
```

## Use-case details

Describe the data being stored onto Filecoin
```
Project operation data of different online education platforms. Including but not limited to user information,video, audio, models, data analysis, algorithms, etc.
```

Where was the data in this dataset sourced from?
```
Our own background data and original content.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://drive.google.com/file/d/1lEpMp3fM7YFHNj_QZK-eOcjoex80udFc/view?usp=share_link
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes, this is a public dataset that can be retrieved by anyone on the Network.
```

What is the expected retrieval frequency for this data?
```
There is no fixed retrieval frequency.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
2 years at least.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Greater China
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
We will choose online transmission. 
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
Firstly he must have a certain scale to ensure data security, and secondly his team needs to have some development capabilities to support subsequent file retrieval in the Filecoin network.
```

How will you be distributing deals across storage providers?
```
We will talk to different miners and of course compare the prices of services between them, and these factors will also determine the distribution ratio between real data and DataCap.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, We have enough funds. 
```

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 100TiB

**Client address**

>f1m2ocyzqqpb2b7t7vfkrclpwfenswjjoxkl4fe7a

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Looking at your application i have some questions:
It seems to me that applying for 5PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Do you have experience in this field?

Can you show us visible proof of the size of your data and the storage systems you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230232885049356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!
