### ISSUE TITLE
[DataCap Application] Haicheng Jiayu Network Culture Media Co., LTD

### ISSUE THREAD

**Issue by qin-superman** [filecoin-project/filecoin-plus-large-datasets#1395]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Haicheng Jiayu Network Culture Media Co., LTD
- Website / Social Media: https://www.hcjiayu.com
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100TiB
- On-chain address for first allocation: f166zg64m7574czxy2cf2klerizdmailya73qgj5q

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Haicheng Jiayu Network Culture Media Co., Ltd. is a live broadcast operation, network delivery, artist management as one of the cultural media company.

It is committed to building a new retail platform of live streaming and short video integrating people, goods and field. Its main business is live streaming operation and short video e-commerce operation, and it is dedicated to building supply chain and team service for e-commerce experts.

Fully open including live broadcasting ability, interactive ability, selection ability as well as live broadcasting content, one-click synchronization including almost all live broadcasting solutions.
```

What is the primary source of funding for this project?
```
The company's live broadcast income, sales income and artist income
```

What other projects/ecosystem stakeholders is this project associated with?
```
None
```

## Use-case details

Describe the data being stored onto Filecoin
```
Live video playback of games, live video playback of goods, singing chat playback video and so on
```

Where was the data in this dataset sourced from?
```
The live recording videos of the company's entertainers and anchors are currently stored in private cloud, but the maintenance and machine costs are very expensive.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://drive.google.com/file/d/1I4kS0_5jmpSbBwncoZhHz36Xuj-Wb9iD/view?usp=share_link
https://drive.google.com/file/d/17SOWkfOvZK0e081SexwLcdZXee9d0nYh/view?usp=share_link
https://drive.google.com/file/d/1qDOn4ETv3EZW0rcr_tSRPfg7fAhO-3-g/view?usp=share_link
https://drive.google.com/file/d/1xW2waGHdk-ZV-9sv1-Wbpr9Siz4sJxMA/view?usp=share_link
https://drive.google.com/file/d/1bLlxCEHm4qYQtZcDdrHGDlJmMjlt3gQK/view?usp=share_link
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes, this is all public data, not secret, and anyone can retrieve it
```

What is the expected retrieval frequency for this data?
```
About once or twice a year, every year at the annual meeting and the anniversary of the founding of the company we review these historical live videos with all our artists.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
Permanent storage.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Asia and Europe.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Because of the large amount of data, online transmission will take a long time and a large bandwidth, so we plan to use offline mail disk.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
Separate data as far as possible and store it evenly in multiple storage providers to ensure data security. In addition, the storage provider must enable the retrieval function. After the storage is completed, we will conduct a data retrieval immediately. In the future, there will be two data download requirements every year.
```

How will you be distributing deals across storage providers?
```
Data is evenly stored across multiple storage providers to ensure data security.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, there is enough money. We will separate some of our funding from the existing private cloud, and the company will also fund the storage conversion project.
```

**Comment by Sunnyiscoming** [comment]
Can you explain your data composition and provide sufficient data samples separately? How many copies will you store?
What's the relationship between you and the organization?
Can you provide more detailed information about other storage providers participated in this program, such as you can list SPs you have contacted with at present?
Whether the sps you choose can support data retrieval?

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 100TiB

**Client address**

> f166zg64m7574czxy2cf2klerizdmailya73qgj5q

**Comment by kernelogic** [comment]
Willing to support

**Comment by kernelogic** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceabka5sqhjvq5j4k3v2p4zy5oez4aiatvcz567hqn6ytyrvv7cezm 
#### Address 
> f166zg64m7574czxy2cf2klerizdmailya73qgj5q
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### Id
> d8e607c6-2b10-476c-a80b-dac2710c3764
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceabka5sqhjvq5j4k3v2p4zy5oez4aiatvcz567hqn6ytyrvv7cezm

**Comment by newwebgroup** [comment]
It has been verified by the FF department and is willing to support it.

**Comment by newwebgroup** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceayuuovwhvuhgkytuhxso4mbjkcdxphowholf35qgyd3hoeeyv7mo 
#### Address 
> f166zg64m7574czxy2cf2klerizdmailya73qgj5q
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1e77zuityhvvw6u2t6tb5qlnsegy2s67qs4lbbbq
#### Id
> d8e607c6-2b10-476c-a80b-dac2710c3764
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceayuuovwhvuhgkytuhxso4mbjkcdxphowholf35qgyd3hoeeyv7mo

**Comment by Sunnyiscoming** [comment]
Could you send an email to filplus-app-review@fil.org with your official domain in order to confirm your identity? Email name should includes the issue id #1395.

**Comment by cryptowhizzard** [comment]
checker:manualTrigger
