### ISSUE TITLE
[DataCap Application] <digital visual products> 

### ISSUE THREAD

**Issue by yangaoquan** [filecoin-project/filecoin-plus-large-datasets#1396]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Beijing Wankutianxia Shuzi Technology Co., Ltd.
- Website / Social Media:http://naughtyworld.com.cn/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):100TiB
- On-chain address for first allocation:f1pbeylugzylqgoc3m6xsmt3ebalklenc3uaouenq

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Founded in 2014, the company has always been committed to digital technology. It is an excellent supplier of digital visual products. It is a comprehensive service enterprise with digital visual technology as its core and creative cultural industry as its background. It continues to provide customers with excellent digital products and services. Services, enterprises focus on VR/AR virtual reality and augmented reality technology application development, visual creativity, 3D interactive system, high-end customization, software development and other business content.
```

What is the primary source of funding for this project?
```
Company revenues.
```

What other projects/ecosystem stakeholders is this project associated with?
```
No.
```

## Use-case details

Describe the data being stored onto Filecoin
```
Construction frameworks for different systems and projects, a large amount of test data and others: pictures, videos, database, texture, 3D model, transactions, shader, audio.
```

Where was the data in this dataset sourced from?
```
Shareholder
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://drive.google.com/file/d/1s9bu_GEee5V09XW2lDRIQ1rySH1DkU1L/view?usp=share_link
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes, We confirm that this is a publicly searchable public dataset. 
```

What is the expected retrieval frequency for this data?
```
This type of data search frequency is expected to be not so high, but we have to store these data for a long time. This is the reason why we chose the Filecoin network for storage. We want to retain the data for a long period of time and provide them to those who need, whenever they require.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
Permanently.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
China.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Online transmission. 
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
Choose a miner with good size and credit.
```

How will you be distributing deals across storage providers?
```
Send it to the different miners according to the offcial Filecoin rules.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, We have enough funds to support this project.
```

**Comment by Sunnyiscoming** [comment]
> Where was the data in this dataset sourced from?
> Shareholder

According to the data samples you provided, it seems that the data came from the Virtual Simulation Experiment Teaching Center of Kongtian Electronic Information of BUAA, 北航空天电子信息虚拟仿真实验教学中心.
But the shareholder is Liyan, not Kongtian Electronic Information of BUAA. Can you explain about that? Have you authorized to store these data as public data on Filecoin network? Please provide related materials to prove that.
Can you explain your data composition and provide sufficient data samples separately? How many copies will you store?
What's the relationship between you and the organization?
Can you provide more detailed information about other storage providers participated in this program, such as you can list SPs you have contacted with at present?
Whether the sps you choose can support data retrieval?

**Comment by simonkim0515** [comment]
Will be closing due to no response. You may reapply with a new application.
