### ISSUE TITLE
[DataCap Application] SHANGHAI UTAG Co., Ltd.

### ISSUE THREAD

**Issue by Z216y** [filecoin-project/filecoin-plus-large-datasets#1399]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: SHANGHAI UTAG Co., Ltd.
- Website / Social Media: www.utag.cn
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100TiB
- On-chain address for first allocation: f1gdesul7rjuv5uyxanyhtphz6n2vee7igdyax7ia

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
UTAG is a data-driven technology company focusing on software development and intelligent data, which also specialized on AI, manufacturing, Enterprise and other industries, with excellent technology research and development capabilities and customer service awareness, based on the Yangtze River Delta.

What is the primary source of funding for this project?
Company income.

What other projects/ecosystem stakeholders is this project associated with?
No.

## Use-case details

Describe the data being stored onto Filecoin
We store data generated by our company on the Filecoin such as software development logs, webpage design schemes, 
software copyright application certificates, etc.

Where was the data in this dataset sourced from?
Data generated by the company when conducting business.

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
https://pan.baidu.com/s/1OpGH0G7sQ2V9ySc4ujyT9w?pwd=hskp 
extraction code: hskp
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
Yes，We confirm.

What is the expected retrieval frequency for this data?
Once a year.

For how long do you plan to keep this dataset stored on Filecoin?
2-3 years or more.

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
Hong Kong, Singapore and Japan.

How will you be distributing your data to storage providers? Is there an offline data transfer process?
Online & offline.

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
We'll choosing the storage providers who would like to storage public data on slack and telegram.

How will you be distributing deals across storage providers?
Data is evenly stored across multiple storage providers to ensure data security, none of them will exceed 20% of  the total.

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
Yes,  we have enough funds.

**Comment by Sunnyiscoming** [comment]
Can you explain your data composition and provide sufficient data samples separately? How many copies will you store?
What's the relationship between you and the organization?
Can you provide more detailed information about other storage providers participated in this program, such as you can list SPs you have contacted with at present?
Whether the sps you choose can support data retrieval?

**Comment by Z216y** [comment]
> Can you explain your data composition and provide sufficient data samples separately? How many copies will you store? What's the relationship between you and the organization? Can you provide more detailed information about other storage providers participated in this program, such as you can list SPs you have contacted with at present? Whether the sps you choose can support data retrieval?

Hello Sunny, Our data composition comprises of data generated in the course of website design and software development. Please check this link for data samples, https://pan.baidu.com/s/1OpGH0G7sQ2V9ySc4ujyT9w?pwd=hskp 
 I am  G.M. of UTAG company and so far SPs we contacted are f0432329,  f0130791, f095334, f01610285. We would like to store 5 copies of our total data.
Hope can get back from you soon.

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 100TiB

**Client address**

> f1gdesul7rjuv5uyxanyhtphz6n2vee7igdyax7ia

**Comment by MetaWaveInfo** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec5j4p4a6ypnw6x5r54rpf6z7x6dymnulmrypszs52spd7bdkjslq 
#### Address 
> f1gdesul7rjuv5uyxanyhtphz6n2vee7igdyax7ia
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1ktlkcxnmzxcdaoqfsunrg3vocfbmgv4n3mrn74a
#### Id
> 726bdd75-0523-48b8-b5f5-9e9578e74dcb
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec5j4p4a6ypnw6x5r54rpf6z7x6dymnulmrypszs52spd7bdkjslq

**Comment by UnionLabs2020** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced3rfuisxusd3uovz4rxeq2zgldirrdagb7vgekuygj2xlszxie6y 
#### Address 
> f1gdesul7rjuv5uyxanyhtphz6n2vee7igdyax7ia
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f17xdri3wunqgld7dm23e4f3eqsntjakwc47xjo6i
#### Id
> 726bdd75-0523-48b8-b5f5-9e9578e74dcb
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced3rfuisxusd3uovz4rxeq2zgldirrdagb7vgekuygj2xlszxie6y

**Comment by Sunnyiscoming** [comment]
f0432329, f0130791, f01610285
They don't disclose the IP. Please check them.

**Comment by cryptowhizzard** [comment]
checker:manualTrigger

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Looking at your application i have some questions:
As you are brand new on Github and have no history of past applications it seems to me that applying for 5PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?

Can you show us visible proof of the size of your data and the storage systems you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230337462961356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!

**Comment by Aaronn85** [comment]
checker:manualTrigger
