### ISSUE TITLE
[DataCap Application] Protocol Labs Dealbot Project

### ISSUE THREAD

**Issue by mgoelzer** [filecoin-project/filecoin-plus-large-datasets#14]
# Large Dataset Notary Application

To apply as a large client, please fill out the following form. 

## Core Information
- Organization Name:  Dealbot - Protocol Labs
- Website / Social Media:  https://protocol.ai/ 
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):  1 PiB
- On-chain address for first allocation:  f1wdxdpqh3hirrhp353i4o6ld7bsw6evh3v7i5jtq

_Please respond to the questions below in pargraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

## Project details

Share a brief history of your project and organization.
```
Protocol Labs has recently developed an open source deal bot (https://github.com/filecoin-project/dealbot) for testing miners on the Filecoin network. The purpose of the bot is to make random, unpredictable deals with all miners on the network and measure whether they successfully completed the full Filecoin lifecycle:  (1) a successful storage deal, (2) a delay period during which the data is not lost, and then (3) a successful retrieval of the stored data.  We call each of these tests a “deal attempt.”

All data attempt results are published as a hash-linked IPLD data structure, such that anyone can read the data. A GraphQL query interface is also exposed to query the data. One example use of such data is a reputation service that reads the public dealbot data, computes a deal success/failure ratio for each miner, and publishes a ranking of miners based on that ratio.

As the project begins testing miners, we don't yet have a good sense of success rates, so will use non-valuable data (random bits). There are approximately 2,460 miners on the network at the time of this writing[1], and we would like to perform 32 GiB storage deal attempts with each miner twice per month. If each deal attempt that fails will be retried up to one additional time, this effort will require between 154 and 308 TB of datacap per month.
 
[1] filfox.info miner count as of Sunday, June 13, 2021.
```

What is the primary source of funding for this project?
```
Protocol Labs is funding this testing using its own internal funds. PL's motivation for funding this is that we believe that increasing the transparency surrounding which miners do and do not accept online deals, it will be easier for storage clients to find a reliable miner to store data with. This creates financial incentives for miners that are well aligned with those of storage clients.
```

What other projects/ecosystem stakeholders is this project associated with?
```
The dealbot is a standalone project meant to provide public data on miner past performance.
```

## Use-case details

Describe the data being stored onto Filecoin
```
The dealbot generates random bits for each storage deal attempt, and this is the data being stored. Random data has the desirable property that it is statistically indistinguishable from encrypted real data, making it more difficult for miners to distinguish between a dealbot test and a “real” storage client.

How does this benefit the Filecoin network?  The broader context of this project is that we would like to make the Filecoin network a better experience for clients storing real data.  One challenge that clients face is finding a miner that accepts online deals. While miner reputation services already exist, none that we know of base their reputation scores on actual deal attempts.  They can rank miners based on latency, uptime and other factors, but cannot factor into those rankings the ability to successfully store and retrieve real data -- the characteristic a user most cares about!  The cost of each reputation service doing these tests would be prohibitive, but is more tolerable when the results gleaned can be shared across the entire community.  It is our expectation and hope that results gathered by the dealbot will be used by multiple competing reputation services, all of which have equal access to the dealbot results dataset.

Couldn’t the same rankings be created using vanilla (non-datacap) storage deals? Most real world demand for Filecoin is being served through Fil+ with clients making verified deals with DataCap.We also see a pattern emerging in which end users do not interact with tools like Lotus directly.  Instead, end users interact with higher level services, and those services pack data into 32 GiB sectors and make verified storage deals for that batch of data.  Since we would like to test the conditions that we expect most users to encounter in the real world, testing should focus on 32 GiB pre-packed, verified storage deals with retrievals occurring at random points during the deal lifetime. This will also help reputation systems calculate the most accurate deal success likelihood that clients will be exposed to on the Network for specific miners.

At the top of this issue we did not indicate a single wallet to receive this datacap, and would like to explain why here.  Instead of receiving the entire datacap allocation in a single wallet, we would prefer to receive a stream of new allocations to newly generated wallets every 24-36 hours, each allocation containing just that few hours’ worth of datacap.  We believe this will make it more difficult for unscrupulous miners to gain advantage with higher apparent dealbot success rate by correctly guessing which incoming online deals are deal attempts from the bot.

(An ideal workflow for us would be an automated way to request a small chunk of datacap (like 5 TB) from a multisig wallet that normally allocates 5 TB chunks for non-dealbot purposes.  We would then burn up that 5 TB over the course of, say, the next 24 hours, and then come back for a new allocation.)

Tracing back the datacap flow is not the only challenge needed for the bots to “blend in with the crowd”.  However, we have solutions in place to prevent bots from having easily identified IP addresses, geographies, libp2p peer ids, and other types of machine fingerprints.  We also fund bot testing wallets (needed for gas and deals) in a manner that makes them difficult to distinguish from normal wallets.  We do not want to detail every infrastructural detection countermeasure designed into the system for opsec reasons.

```

Where was the data in this dataset sourced from?
```
/dev/urandom or similar RNG
```

Can you share a sample of what is in the dataset? A link to a file, an image, a table, etc., are good examples of this. 
```
Not applicable. The data is random bits.
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Each deal attempt record will report a miner id and CID where the random data was stored.  The dealbot itself will retrieve these after a period of time to test retrieval on that miner.  Anyone else can also retrieve these CIDs.
```

What is the expected retrieval frequency for this data?
```
We expect to test each miner on the network 1-2 times per month. After each successful storage deal, we will make some number of retrieval attempts between 1 and 10 over the lifetime of the deal to make sure it is still retrievable for the full deal duration. These are the only retrievals expected initially.
```

For how long do you plan to keep this dataset stored on Filecoin? Will this be a permanent archival or a one-time storage deal?
```
Each chunk of random data is a one-time storage deal and once its deal lifetime has expired, that exact data will not be stored again. However, the dealbot testing project itself is an ongoing effort that we expect to continue indefinitely.
```

## DataCap allocation plan

In which geographies do you plan on making storage deals?
```
All regions.
```

What is your expected data onboarding rate? How many deals can you make in a day, in a week? How much DataCap do you plan on using per day, per week?
```
Because we are storing random data using a scalable, multi-cloud compute cluster that has nodes all over the world, there is no scale-up delay. Instead, we think in terms of evenly spreading each month’s deal attempts over that month. Suppose we were to have 250 TB worth of intended storage deal attempts in a given 28-day month. This would work out to 250/28 = ~9 TB of data stored on Filecoin per day or ~36 TB per week.
```

How will you be distributing your data to miners? Is there an offline data transfer process?
```
We will attempt to store test data on each miner that has been active on-chain in the previous 30-days.  The dealbot tests only online deals.
```

How do you plan on choosing the miners with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
Our goal is to test every miner that has been active on-chain in the preceding 30 days. Our bot will also test retrievability of the data at multiple time intervals.
```

How will you be distributing data and DataCap across miners storing data?
```
We will be sending the same amount of datacap data (to within a randomness bound that helps the bot evade detection) to each miner tested each month.
```

**Comment by mgoelzer** [comment]
@dkkapur

**Comment by Broz221** [comment]
Count me in.

**Comment by swatchliu** [comment]
Bytebase will support it!

**Comment by ozhtdong** [comment]
Would like to be the notary of this project.

**Comment by MegTei** [comment]
Happy to support

**Comment by dannyob** [comment]
Filecoin Foundation approves of this experiment.

**Comment by galen-mcandrew** [comment]
Looks like we are at 5 notaries, need 2 more.

**Comment by MegTei** [comment]
Count me in

**Comment by neogeweb3** [comment]
Count me in.

**Comment by andrewxhill** [comment]
yep, in!

**Comment by steven004** [comment]
Count me in

**Comment by dkkapur** [comment]
Final list of 7 notaries for this application (from the first 7 who responded - thank you to @steven004 as well):

1. @Broz221 - f13vzzb65gr7pjmb2vsfq666epq6lhdbanc4vfopq
2. @swatchliu - f1yh6q3nmsg7i2sys7f7dexcuajgoweudcqj2chfi
3. @ozhtdong - f1lwpw2bcv66pla3lpkcuzquw37pbx7ur4m6zvq2a
4. @MegTei - f1ystxl2ootvpirpa7ebgwl7vlhwkbx2r4zjxwe5i
5. @dannyob - f1k6wwevxvp466ybil7y2scqlhtnrz5atjkkyvm4a
6. @neogeweb3 - f13k5zr6ovc2gjmg3lvd43ladbydhovpylcvbflpa
7. @andrewxhill - f2kb4izxsxu2jyyslzwmv2sfbrgpld56efedgru5i

These notaries cover GCN, NA, EU, Oceania, thereby meeting the 3 region requirement.

**Comment by dkkapur** [comment]
## Multisig Notary requested 
 
#### Notary addresses
> f13vzzb65gr7pjmb2vsfq666epq6lhdbanc4vfopq
> f1yh6q3nmsg7i2sys7f7dexcuajgoweudcqj2chfi
> f1lwpw2bcv66pla3lpkcuzquw37pbx7ur4m6zvq2a
> f1ystxl2ootvpirpa7ebgwl7vlhwkbx2r4zjxwe5i
> f1k6wwevxvp466ybil7y2scqlhtnrz5atjkkyvm4a
> f13k5zr6ovc2gjmg3lvd43ladbydhovpylcvbflpa
> f2kb4izxsxu2jyyslzwmv2sfbrgpld56efedgru5i

#### Total DataCap requested
> 1PiB

#### Expected weekly DataCap usage rate
> 50TiB

**Comment by galen-mcandrew** [comment]
@mgoelzer this LDN app cleared the root key holders! 

Kicking off the first allocation request. Can we get 4 approvals from notaries?
@Broz221 @swatchliu @ozhtdong @MegTei @dannyob @neogeweb3 @andrewxhill

**Comment by galen-mcandrew** [comment]
@mgoelzer & @dkkapur what client address would you like to use for the first allocation?

**Comment by dkkapur** [comment]
`f1wdxdpqh3hirrhp353i4o6ld7bsw6evh3v7i5jtq` thanks!

**Comment by galen-mcandrew** [comment]
## DataCap Allocation requested

#### Multisig Notary address
> f01240081

#### Client address
> f1wdxdpqh3hirrhp353i4o6ld7bsw6evh3v7i5jtq

#### DataCap allocation requested
> 25TiB

**Comment by galen-mcandrew** [comment]
@Broz221 @swatchliu @ozhtdong @MegTei @dannyob @neogeweb3 @andrewxhill

Ready to sign!

**Comment by swatchliu** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec4dvh3kttb3chbcawz432u6svcgi3le3muw3ffwubzshuti723oa 
#### Address 
> f1wdxdpqh3hirrhp353i4o6ld7bsw6evh3v7i5jtq
#### Datacap Allocated
> 27487790694400
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec4dvh3kttb3chbcawz432u6svcgi3le3muw3ffwubzshuti723oa

**Comment by neogeweb3** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceatqpf6oqsvdsugfm46pg6b6kyivnlupjrjl6dzplhqyro7pr7bjy 
#### Address 
> f1wdxdpqh3hirrhp353i4o6ld7bsw6evh3v7i5jtq
#### Datacap Allocated
> 27487790694400
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceatqpf6oqsvdsugfm46pg6b6kyivnlupjrjl6dzplhqyro7pr7bjy

**Comment by MegTei** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebocqoimj2jc3wmj4piokuburbq6zwomigxnwhauevdz47hwpuku4 
#### Address 
> f1wdxdpqh3hirrhp353i4o6ld7bsw6evh3v7i5jtq
#### Datacap Allocated
> 27487790694400
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebocqoimj2jc3wmj4piokuburbq6zwomigxnwhauevdz47hwpuku4

**Comment by dannyob** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecvpbrzynoxgw2pcujb7bbfpnk2hqgk27lbz3tp4jvcou5cpzowpw 
#### Address 
> f1wdxdpqh3hirrhp353i4o6ld7bsw6evh3v7i5jtq
#### Datacap Allocated
> 27487790694400
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecvpbrzynoxgw2pcujb7bbfpnk2hqgk27lbz3tp4jvcou5cpzowpw

**Comment by galen-mcandrew** [comment]
Thanks notaries!

@dkkapur at this time, seeing 25 TiB at f1wdxdpqh3hirrhp353i4o6ld7bsw6evh3v7i5jtq

Happy dealbotting!

**Comment by galen-mcandrew** [comment]
rolling to https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/50
