### ISSUE TITLE
[DataCap Application] <BBNEWS> 

### ISSUE THREAD

**Issue by zjgxj34** [filecoin-project/filecoin-plus-large-datasets#1400]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: BBNews
- Website / Social Media: Twitter：BitalkNews
Website：www.bitalk.com/index
TG: t.me/bitalknews
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 4.9 PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100 TiB
- On-chain address for first allocation: f1t7z6akmsguxaerhoeab3mqil2nwqlkzuewu2noi

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
BBNews is a professional blockchain content platform, covering business sectors such as blockchain information, online and offline activities, etc. We are committed to becoming a high-quality disseminator and information aggregator in the blockchain industry. At present, we are mainly engaged in two business segments:
1. Media business. At present, we have successfully operated nearly 10 IPs such as Beep Big Coffee Show, Beep Round Table Party, Trendy, New Currency Express, Little Turtle China Bank, and New Mining Forces. There are 50+ industry media in matrix-style publicity, which can provide Personalized planning of activities, writing in-depth manuscripts, and media publicity and other services.
2. Investment business. At present, we are working on the layout of investment business. Through the team's market research, we have selected high-quality potential projects. In the future, we will also carry out deeper investment research work.
```

What is the primary source of funding for this project?
```
Operation income from media business and investment.
```

What other projects/ecosystem stakeholders is this project associated with?
```
Our business is a blockchain content platform, so we have researched projects related to the blockchain industry.
```

## Use-case details

Describe the data being stored onto Filecoin
```
The data stored on Filecoin are basically original articles, other high-quality articles, and investment research graphics and videos.
```

Where was the data in this dataset sourced from?
```
Our team’s creation and other platforms
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://m.bitalk.com/video/detail/681063671027339264
https://m.bitalk.com/video/detail/456042955027910656
https://m.bitalk.com/video/detail/636854967206023168
https://m.bitalk.com/video/detail/438648187406913536
https://m.bitalk.com/video/detail/521933817485856768
https://m.bitalk.com/video/detail/487815246195593216
https://m.bitalk.com/video/detail/451194829125324800
https://m.bitalk.com/video/detail/617238824510164992
https://m.bitalk.com/video/detail/469680472159555584
https://m.bitalk.com/video/detail/482085114730385408
https://m.bitalk.com/news/detail/522298554446909440
https://m.bitalk.com/news/detail/520828184187506688
https://m.bitalk.com/news/detail/691529324729339904
https://m.bitalk.com/news/detail/691523642122702848
https://m.bitalk.com/news/detail/691878751901978624
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes, we confirm 
```

What is the expected retrieval frequency for this data?
```
Maybe high, maybe low
```

For how long do you plan to keep this dataset stored on Filecoin?
```
We are eager to find a suitable platform to store for a longer period of time. So, I think we will store for at least ten years on filecoin.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Asia， Europe
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
We will send data to miners online
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We will observe the miner's data through the block explorer to filter the miners that are suitable for us
```

How will you be distributing deals across storage providers?
```
We will not store more than 20% of the data in each miner
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, we have the resources and funds to start trading
```

**Comment by Sunnyiscoming** [comment]
How about the previous application you applied before? 
What's the relationship between you and the organization?
Can you provide more detailed information about other storage providers participated in this program, such as you can list SPs you have contacted with at present?
Whether the sps you choose can support data retrieval?

**Comment by zjgxj34** [comment]
Hello @Sunnyiscoming 
We successfully applied for 5P before, but because the GitHub account is restricted, now we create new Issues.
I am an employee of BBNEWS, specializing in filplus business. We plan to contact high-quality and compliant SPs through the official website and slack.
Here are the SPs we have contacted so far:
f01740934｜f01854772｜f01384209｜f01893023｜f01137150
Thanks!

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 4.9PiB

**Expected weekly DataCap usage rate**

> 100TiB

**Client address**

> f1t7z6akmsguxaerhoeab3mqil2nwqlkzuewu2noi

**Comment by ipfscn** [comment]
Can you email filplus-app-review@fil.org using your official domain name to confirm your identity?
Email name should contain Issue ID #1400.

**Comment by psh0691** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceadhxzhfmxe34wjmap34ncf5fs5iwxcexrr4zhfratdu72w3sjnfs 
#### Address 
> f1t7z6akmsguxaerhoeab3mqil2nwqlkzuewu2noi
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1qdko4jg25vo35qmyvcrw4ak4fmuu3f5rif2kc7i
#### Id
> 59104750-1508-4407-abf4-180b596d547f
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceadhxzhfmxe34wjmap34ncf5fs5iwxcexrr4zhfratdu72w3sjnfs

**Comment by cryptowhizzard** [comment]
Hello @zjgxj34,

I have questions about your previous application. That one was involved in heavy CID sharing.
CID sharing means that you stored data from other persons / dataset's while you applied to store other data ( as in topic ).

Investigating this is a very time consuming matter. I need to check each CID by hand and check who brought it on chain first to see if that was by you or someone else. And further down the line i must try to retrieve the data.

To conclude: Are you sure you want to proceed with this application? If CID has been taking place and you did not store the data as indicated in your first application the chances are slim that you will get datacap in the future for this one.

![Scherm­afbeelding 2023-01-20 om 15 22 50](https://user-images.githubusercontent.com/36404435/213721840-40be9b94-9cf5-43d2-b94b-2a1e734ae5f7.png)

**Comment by cryptowhizzard** [comment]
@psh0691 can you please cancel your propose message?

This should not be signed.
