### ISSUE TITLE
[DataCap Application] Bakon Electronic Technology

### ISSUE THREAD

**Issue by GzyyzG** [filecoin-project/filecoin-plus-large-datasets#1401]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Shenzhen Bakon Electronic Technology 
- Website / Social Media: www.bakon.cn
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5 PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100 TiB
- On-chain address for first allocation: f1cnzivxxexinqoyfkbku6tbbjnwyazrtwrxtq2ny

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Shenzhen Bakon Electronic Technology CO., LTD was established in 1998, we are devoted to the research and development, production and sales of rework soldering tools, intelligent brushless electric screwdriver and related electronic instruments and testing instruments. Bakon is a well-known service provider of electronic tools’ R&D, manufacturing and service, as well as electrostatic prevention and control service provider in domestic. All products are independently developed by Bakon, includes the solution of electrostatic prevention and control, automated lean production scheme, lead-free soldering and rework station, purify auxiliary equipment, hardware hand tools, production industrial tools and repair market. Only create more value for you. 
```

What is the primary source of funding for this project?
```
Company profit
```

What other projects/ecosystem stakeholders is this project associated with?
```
None.
```

## Use-case details

Describe the data being stored onto Filecoin
```
Promotion videos, design data, documents archives.
```

Where was the data in this dataset sourced from?
```
From our company.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
Yes.
https://1drv.ms/u/s!AhDXHQshpkiQasIGdwesxfxLI7o?e=5Q4b5I
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Confirm.
```

What is the expected retrieval frequency for this data?
```
Every half a year.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
At least 3 years.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Asia & GCR.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
combine online & offline transfer depend on location.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We will choose storage providers with high reputation and strong confidentiality for transactions. Before we cooperate, we will understand their scale, whether they are reliable, whether they have hard-core hardware equipment and professional technical teams. The security of data storage is very important.
```

How will you be distributing deals across storage providers?
```
We will select large-scale, reputable, stable and secure storage service providers according to the rules and distribute them in proportion.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes we are ready and we will pay all expenses.
```

**Comment by Sunnyiscoming** [comment]
Can you explain your data composition and provide sufficient data samples separately? How many copies will you store?
What's the relationship between you and the organization?
Can you provide more detailed information about other storage providers participated in this program, such as you can list SPs you have contacted with at present?
Whether the sps you choose can support data retrieval?

**Comment by GzyyzG** [comment]
> Can you explain your data composition and provide sufficient data samples separately? How many copies will you store? What's the relationship between you and the organization? Can you provide more detailed information about other storage providers participated in this program, such as you can list SPs you have contacted with at present? Whether the sps you choose can support data retrieval?

Hi @Sunnyiscoming ，the samples in shared link are updated agin, we would like to store advertising videos, design pics and design drawings for roughly 8 to 10 copies.
I am the R&D staff of our company. Listed below are the SPs contacted at present:
f0108672, f043929, f01927554(retrieval), f01672960, f082635.

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 100TiB

**Client address**

> f1cnzivxxexinqoyfkbku6tbbjnwyazrtwrxtq2ny

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Looking at your application i have some questions:
As you are brand new on Github and have no history of past applications it seems to me that applying for 5PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?

Can you show us visible proof of the size of your data and the storage systems you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230337462961356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!
