### ISSUE TITLE
[DataCap Application] <Weishi>

### ISSUE THREAD

**Issue by ikingqu** [filecoin-project/filecoin-plus-large-datasets#1402]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Beijing Weishiyuanjing Technology Co.,Ltd.
- Website / Social Media::http://www.vsoutlook.com/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):100TiB
- On-chain address for first allocation:f1tpx6k76ktk5owetoa2gj3uevxrjafedrr6lsnfi

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
The company was founded by senior experts from broadcast television, digital media, and Internet industries. We are committed to combining cutting-edge IT technology with media business applications, helping media industry customers to establish a modern media production environment, providing IP-based, ultra-high-definition video and audio system consulting and construction services, mainly serving China Central Radio and Television, Beijing TV, Tencent and other domestic first-line radio and television media, as well as major overseas national television stations.
```

What is the primary source of funding for this project?
```
Company revenues.
```

What other projects/ecosystem stakeholders is this project associated with?
```
There is no other projects/ecosystem stakeholders associated with.
```

## Use-case details

Describe the data being stored onto Filecoin
```
Design framework of publicly available audio-visual system, VR/AR project data, ultra-high-definition video resources, integrated media project operation data,  etc.
```

Where was the data in this dataset sourced from?
```
Project operation data and original content.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://drive.google.com/file/d/1nGRoUoJ1suPgsXv3CISvVC5-S2ZHPmxW/view?usp=share_link
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes, We confirm that the data we stored are all open source. 
```

What is the expected retrieval frequency for this data?
```
There is no fixed retrieval frequency for this data.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
3 years at least.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
We tend to choose China.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
We will choose online transmission. 
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We are testing storage deals to various miners.
```

How will you be distributing deals across storage providers?
```
We are testing with miners who will be aggressive with various clients and looking for more miners.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes,we have.
```

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 100TiB

**Client address**

>f1tpx6k76ktk5owetoa2gj3uevxrjafedrr6lsnfi

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 100TiB

**Client address**

>f1tpx6k76ktk5owetoa2gj3uevxrjafedrr6lsnfi

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 100TiB

**Client address**

>f1tpx6k76ktk5owetoa2gj3uevxrjafedrr6lsnfi

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Looking at your application i have some questions:
As you are brand new on Github and have no history of past applications it seems to me that applying for 5PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?

Can you show us visible proof of the size of your data and the storage systems you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230232885049356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!
