### ISSUE TITLE
[DataCap Application] <HaiShi Technology Co., Ltd.> - <Community security monitoring project>

### ISSUE THREAD

**Issue by 1351311** [filecoin-project/filecoin-plus-large-datasets#1403]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: HaiShi Technology Co., Ltd.
- Website / Social Media:http://www.hisw.cn/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):200TiB
- On-chain address for first allocation:f1aavji5y2g3hv73wldvry23tlta6zoq3m3pggyta

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
We have mature AI technology strength, and uses advanced technologies such as deep learning, machine learning, big data mining to serve the development of AI solutions and software in various industries. This project records monitoring data in the community, and records and identifies vehicle scratches in the community
```

What is the primary source of funding for this project?
```
Project Income
```

What other projects/ecosystem stakeholders is this project associated with?
```
None
```

## Use-case details

Describe the data being stored onto Filecoin
```
We need to store a large amount of monitoring data
```

Where was the data in this dataset sourced from?
```
From our monitoring recorder
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
Link：https://pan.baidu.com/share/init?surl=wEcLFyu62uZuAOsBWCgfzw 
Extraction code：n596
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes,it is
```

What is the expected retrieval frequency for this data?
```
No frequent retrieval is required. 1 times a year
```

For how long do you plan to keep this dataset stored on Filecoin?
```
3 years
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
China
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
We need to store the data on a stable storage device so that it can be viewed at any time and used by robots for learning and recognition
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
Stable
```

How will you be distributing deals across storage providers?
```
The industry's advanced disaster recovery storage.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
We will pay all expenses.
```

**Comment by Sunnyiscoming** [comment]
Can you explain your data composition and provide sufficient data samples separately? How many copies will you store?
What's the relationship between you and the organization?
Can you provide more detailed information about other storage providers participated in this program, such as you can list SPs you have contacted with at present?
Whether the sps you choose can support data retrieval?

**Comment by Sunnyiscoming** [comment]
Any update here?

**Comment by Sunnyiscoming** [comment]
Close for no reply.
