### ISSUE TITLE
Hangzhou Seoul Education Training Co., Ltd - Du immortality[1/3]

### ISSUE THREAD

**Issue by language970** [filecoin-project/filecoin-plus-large-datasets#1404]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Hangzhou Seoul Education Training Co., Ltd
- Website / Social Media:http://www.shoueredu.com/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):100TiB
- On-chain address for first allocation:f13dwvmc6st6ulv4elm5gamo3xrybgp4hdqmdziei

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Seoul Education was invested by Hujiang and established in Hangzhou in October 2005.
The language training courses cover ten languages, including South Korea, Japan, Germany, France and Spain. Its brands integrate basic language teaching, exam oriented intensive training and overseas learning services, and provide personalized training programs to meet the students' learning needs, such as examinations, employment, interests and overseas learning.

Initiate the "3O" teaching service system, offline, online and open, break the traditional teaching mode, make up for the lack of online learning, and provide effective guidance from four aspects of listening, speaking, reading and writing, so as to fully integrate offline teaching and online learning. The educational mission of Seoul Education is to "open up the" ecological road of learning "of small language" O2O "and provide high-quality resources and services to students.
```

What is the primary source of funding for this project?
```
Some clients and partners jointly contribute.
```

What other projects/ecosystem stakeholders is this project associated with?
```
N.A. 
```

## Use-case details

Describe the data being stored onto Filecoin
```
Teaching videos from training institutions all over the country for joint learning.
```

Where was the data in this dataset sourced from?
```
These data are from the public course recording screen and online teaching recording screen. A large amount of such teaching video data will be generated every day, it will be provided to educators and students around the world to learn and make contributions to the progress of all mankind.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://drive.google.com/drive/folders/19NFPbpKVP88PpU2NTM2xXs72LxVdKqPc
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes, anyone can access the data.
```

What is the expected retrieval frequency for this data?
```
First read about 5-10 times, and will be only read when the data in caches of relay nodes expired.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
540 days or more.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Greater China, or around the world.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
We have our own IDC machine room, which can provide network bandwidth download, or mail hard disks to storage providers.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We will take the initiative to obtain SP. We also accept SP's initiative to contact us. Our data will be stored in multiple SPs to ensure distributed storage and data security. We periodically retrieve data to ensure that it is retrievable.
```

How will you be distributing deals across storage providers?
```
At least 6 SP.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, our money and resources are abundant.
```

**Comment by ZC-FILSZ** [comment]
Hi, @simonkim0515 
I've closed the other two

**Comment by Normalnoise** [comment]
@ZC-FILSZ  Do you have how much data? can you show me a dataset size proof?

**Comment by ZC-FILSZ** [comment]
@Normalnoise hello,I currently have 252T of teaching data, and about 500T are still in other campuses. This is a screenshot of the data size of my campus
![image](https://user-images.githubusercontent.com/29709913/228297185-1164ae92-1c48-47a5-b641-fc22cf4d8398.png)

**Comment by Normalnoise** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceanybmtqzx7vwh6cuam3hbt7bcra33hstpiwdy4t7qzcipraxulpc 
#### Address 
> f13dwvmc6st6ulv4elm5gamo3xrybgp4hdqmdziei
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1c5non5yf35avgcpsqvxu4yj54yyvxorwyjochqq
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceanybmtqzx7vwh6cuam3hbt7bcra33hstpiwdy4t7qzcipraxulpc

**Comment by newwebgroup** [comment]
Since the initial amount is relatively small, we are willing to make support in the first round and hope to see compliance performance.

**Comment by newwebgroup** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedwtf4qrwn2vhh2bapggr4uhacxtlxda2jhzesenrvhgxpoahonzg 
#### Address 
> f13dwvmc6st6ulv4elm5gamo3xrybgp4hdqmdziei
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1e77zuityhvvw6u2t6tb5qlnsegy2s67qs4lbbbq
#### Id
> 781303d0-96b6-4d3b-af17-ff68266ee964
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedwtf4qrwn2vhh2bapggr4uhacxtlxda2jhzesenrvhgxpoahonzg

**Comment by igoovo** [comment]
checker:manualTrigger

**Comment by igoovo** [comment]
![WechatIMG3](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/103082537/fab135f9-9c57-4602-99f0-f7ae74a97bb8)

**Comment by igoovo** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedqkjy2epjg7ezc27pesz6ibs4s245a562kt6igmytgr22dr54jas 
#### Address 
> f13dwvmc6st6ulv4elm5gamo3xrybgp4hdqmdziei
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1shnsfayxqll77svffaxnjenms7bbbysbqcatrpy
#### Id
> not found
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedqkjy2epjg7ezc27pesz6ibs4s245a562kt6igmytgr22dr54jas

**Comment by zcfil** [comment]
checker:manualTrigger

**Comment by zcfil** [comment]
Data allocation looks very healthy, but data is only stored in SPs from two cities. Do you have any more SPs from other cities?

**Comment by language970** [comment]
@zcfil Hi,Due to the limited amount of data in the first round, it is not easy to allocate. Later, I have planned to store the data in Singapore and the United States.
The cooperative SPs are as follows：
f01877184  Singapore 
f02062851  The United States.

**Comment by zcfil** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced2ollfm6ife7rmvtbwk6dzrzavxwdt74c7u3s6g3hvlnpvyhlplg 
#### Address 
> f13dwvmc6st6ulv4elm5gamo3xrybgp4hdqmdziei
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1cjzbiy5xd4ehera4wmbz63pd5ku4oo7g52cldga
#### Id
> 32f2789d-0354-4be7-86cf-76ca53232440
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced2ollfm6ife7rmvtbwk6dzrzavxwdt74c7u3s6g3hvlnpvyhlplg

**Comment by zcfil** [comment]
checker:manualTrigger

**Comment by 1ane-1** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebx6bw2gmwikrp3mzjxll5tmzeia6ex2azcxstlkbjntjycosglqs 
#### Address 
> f13dwvmc6st6ulv4elm5gamo3xrybgp4hdqmdziei
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1mdk7s2vntzm6hu35yuo6vjubtrpfnb2awhgvrri
#### Id
> 7ee29926-38ba-478d-94b8-06e5285dbf90
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebx6bw2gmwikrp3mzjxll5tmzeia6ex2azcxstlkbjntjycosglqs

**Comment by SuperChaiChai** [comment]
<img width="761" alt="image" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/42091141/7c6c460a-bb88-42e5-a69f-8822275e0ed8">

**Comment by SuperChaiChai** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedkjobc24sdjuvcdt4buuspu23k3i27curvncn6wh2b63gtzolruw 
#### Address 
> f13dwvmc6st6ulv4elm5gamo3xrybgp4hdqmdziei
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f12mckci3omexgzoeosjvstcfxfe4vqw7owdia3da
#### Id
> 7ee29926-38ba-478d-94b8-06e5285dbf90
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedkjobc24sdjuvcdt4buuspu23k3i27curvncn6wh2b63gtzolruw

**Comment by woshidama323** [comment]
checker:manualTrigger

**Comment by cryptowhizzard** [comment]
@language970 

Why are you sending all your data to one entity?

![Scherm­afbeelding 2023-07-26 om 09 23 03](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/36404435/f47e720a-e09c-43ed-8af7-20f40120eacc)
