### ISSUE TITLE
[DataCap Application] CTGH

### ISSUE THREAD

**Issue by Javaris33** [filecoin-project/filecoin-plus-large-datasets#1414]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: China Tourism Group Hotel
- Website / Social Media:https://www.ctg.cn/en/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):200TiB
- On-chain address for first allocation:f13yt2tdceufa4moywlszvxxstzcyc6pl2a2kqwvi

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
China Tourism Group Hotel Holding Co., Ltd., abbreviated as "CTG Hotel", is running three hotel brands, namely Grand Metropark, Kew Green and Traveler Inn The company operates nearly 200 hotels around the world with more than 51,000 guest rooms, covering more than 60 cities in Mainland China, such as Beijing, Shanghai, Nanjing, Hangzhou, Suzhou, Chongqing and Shenzhen, as well as 42 hotels in London, Leeds, Birmingham, Lincoln, Portsmouth, Brighton, etc. in the UK.
```

What is the primary source of funding for this project?
```
From company's income.
```

What other projects/ecosystem stakeholders is this project associated with?
```
No.
```

## Use-case details

Describe the data being stored onto Filecoin
```
We are here to save the pictures and videos for the hotel promotion show.
```

Where was the data in this dataset sourced from?
```
These data was created by our company.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
Yes, here it is.
https://c.gmx.com/@1162701252321085957/PJCEV7PHTjqW__uTWbFdXg
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes.
```

What is the expected retrieval frequency for this data?    
```
We'll do the retrieve once a year. 
```

For how long do you plan to keep this dataset stored on Filecoin?
```
At least 2 years for it.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
We plan making deals mainly in Asia. Also considering other regions.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
We would use both online and offline transfer. Small-capacity data will transfer onilne.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We would find some storage providers through slack. The purpose of applying for datacap is to hope that more storage providers can finish our deals.
```

How will you be distributing deals across storage providers?
```
We try to give less than 20% deals for every storage provider. Then we'll continue looking for more sps.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes. If we have a good experience in filecoin, we hope to introduce more companies in our group or some companies in the same industry to participate together.
```

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 200TiB

**Client address**

>f13yt2tdceufa4moywlszvxxstzcyc6pl2a2kqwvi

**Comment by swatchliu** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedwpe6henfj5rbuv7kuspwfvi75pvn6oo3kxuzkbwem2hg7ohxxki 
#### Address 
> f13yt2tdceufa4moywlszvxxstzcyc6pl2a2kqwvi
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1yh6q3nmsg7i2sys7f7dexcuajgoweudcqj2chfi
#### Id
> a7f4bba7-6a0c-43ef-bd9d-b0b307e7b788
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedwpe6henfj5rbuv7kuspwfvi75pvn6oo3kxuzkbwem2hg7ohxxki

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Looking at your application i have some questions:
As you are brand new on Github and have no history of past applications it seems to me that applying for 5PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?

Can you show us visible proof of the size of your data and the storage systems you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230232885049356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!

**Comment by 1475Notary** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaijevexbdpe2srgavzfz6fjcfmuvolsm5ggysvmtcvqlvz5w32ke 
#### Address 
> f13yt2tdceufa4moywlszvxxstzcyc6pl2a2kqwvi
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1ofq4mngy7ggcp755pfquq2gphjjnlydolf6awtq
#### Id
> a7f4bba7-6a0c-43ef-bd9d-b0b307e7b788
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaijevexbdpe2srgavzfz6fjcfmuvolsm5ggysvmtcvqlvz5w32ke

**Comment by clriesco** [comment]
Removed stale label and reopened issue :)

**Comment by Javaris33** [comment]
Keep open please

**Comment by Javaris33** [comment]
Yes, keep open.

**Comment by Javaris33** [comment]
Yes, keep open.

**Comment by Javaris33** [comment]
Yes, in process.

**Comment by Javaris33** [comment]
Yes, in process.

**Comment by Javaris33** [comment]
Yes, please

**Comment by Sunnyiscoming** [comment]
Hello, @Javaris33 per the https://github.com/filecoin-project/notary-governance/issues/922 for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

This information will be reviewed by Fil+ Governance team to confirm validity and then the application will be allowed to move forward for additional notary review.

**Comment by Filplus-govteam** [comment]
Closing until SP list is provided
