### ISSUE TITLE
[DataCap Application] Fujian ZhanXun Geographic Information Co., Ltd 

### ISSUE THREAD

**Issue by mutablepunk** [filecoin-project/filecoin-plus-large-datasets#1419]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Fujian ZhanXun Geographic Information Co., Ltd
- Website / Social Media: www.zhanxun.site
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 2 PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100 Tib
- On-chain address for first allocation: f1jqrcpugschakigqqvivbk3mfr6hx6jkf42kyqya

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Fujian ZhanXun Geographic Information Co., Ltd , founded in May 2014. The company provides services such as thematic map production and H5 application system development, and is committed to the investment development and application promotion of geographic information applications. The company has successively provided services such as information collection, application development and platform release for provincial-level units such as the Provincial Investigation Bureau、Provincial Safety Administration、Provincial Publicity Department and Provincial Tourism Bureau. At the same time, it also provides information development services for mass merchants and various enterprises. So far, it has served nearly 50 scenic spots and more than 200 enterprises in the province, and accumulated a large number of application data such as tourist attractions, special food, cultural exhibition halls, etc.
```

What is the primary source of funding for this project?
```
Company revenue
```

What other projects/ecosystem stakeholders is this project associated with?
```
None
```

## Use-case details

Describe the data being stored onto Filecoin
```
This data includes geographic imagery data and panoramas. We has served nearly 50 scenic spots and more than 200 enterprises in the province, and accumulated a large number of application data such as tourist attractions, special food, cultural exhibition halls, etc. 
```

Where was the data in this dataset sourced from?
```
From the geographic data in our project
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://drive.google.com/drive/folders/1RjLa99z8qSFRvLxHMEdIgpiKINbyYhjg?usp=sharing
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes, Confirm.
```

What is the expected retrieval frequency for this data?
```
1-2 times a year
```

For how long do you plan to keep this dataset stored on Filecoin?
```
Three years or more 
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Greater China，Asia.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
offline.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We will refer to their storage efficiency and overall capacity, then choose reliable and experienced storage providers
```

How will you be distributing deals across storage providers?
```
According to the rules of the fil-plus community, we will evenly distribute them to high-quality storage providers.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, we have sufficient funds.
```

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 2PiB

**Expected weekly DataCap usage rate**

> 100TiB

**Client address**

> f1jqrcpugschakigqqvivbk3mfr6hx6jkf42kyqya

**Comment by xiaoyuaiheshui** [comment]
1.can you send email to [filplus-app-review@fil.org]；
2.Have you establish cooperation with storage providers? If yes, please list them. If not, please explain how to find them.

**Comment by mutablepunk** [comment]
1. Yes, I already sent email.
2. Yes, we have. Here are their nodes: f0216849, f01949260 and f01907578

<img width="651" alt="Screen Shot 2022-12-20 at 14 22 19" src="https://user-images.githubusercontent.com/113664386/208600454-590a8bf6-0cd0-4c52-ad08-388a59575b94.png">

**Comment by xiaoyuaiheshui** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedqsgjr33ph4huw3kr4gyfyfffuwassjqc2l25drjw2rd2habydna 
#### Address 
> f1jqrcpugschakigqqvivbk3mfr6hx6jkf42kyqya
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f122qmy25wdtt5mxd77kndiq7z5x2n3iwiuz2wdsa
#### Id
> 5d356a10-1e4a-4c92-b776-d3468688e436
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedqsgjr33ph4huw3kr4gyfyfffuwassjqc2l25drjw2rd2habydna

**Comment by kernelogic** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacechoo4a2cd2ifhporpcnxbhxya2bhegmkczsqlcwk56w2evrr6psu 
#### Address 
> f1jqrcpugschakigqqvivbk3mfr6hx6jkf42kyqya
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### Id
> 5d356a10-1e4a-4c92-b776-d3468688e436
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacechoo4a2cd2ifhporpcnxbhxya2bhegmkczsqlcwk56w2evrr6psu

**Comment by kernelogic** [comment]
First allocation, looking forward to next milestone

**Comment by Sunnyiscoming** [comment]
![image](https://user-images.githubusercontent.com/105098820/212877920-6a1e9a6a-8b4e-491a-8020-2910c7248e65.png)
The email address for sending KYB emails is not an authorized email address. 
Could you send an email to filplus-app-review@fil.org with your official domain in order to confirm your identity? Email name should includes the issue id #1419.

**Comment by mutablepunk** [comment]
Sorry, the email address used to send the email before was wrong, the new email has been sent, please see the screenshot.

![WechatIMG30](https://user-images.githubusercontent.com/113664386/215312286-fec6c8d8-093d-40bb-ae30-94caa5eed024.png)

Also the email address previously used on the company's official website has been discontinued and has now been updated to a new email address

<img width="1166" alt="Screenshot 2023-01-28 at 12 12 45" src="https://user-images.githubusercontent.com/113664386/215312300-0636f79a-8822-4ace-822c-e0cde5038473.png">

**Comment by herrehesse** [comment]
@mutablepunk First allocation does not seem regionally spread out. I want a clear plan of distribution and a list of SP's and business names before moving forward with the next trench.

**Comment by cryptowhizzard** [comment]
Trying to retrieve the data what's in here. Will report back shortly.

**Comment by mutablepunk** [comment]
checker:manualTrigger

**Comment by mutablepunk** [comment]
@herrehesse @cryptowhizzard  The encapsulation speed of some SP is relatively slow, and now they are all on the chain. Can you support me?

**Comment by cryptowhizzard** [comment]
Hi @mutablepunk

Thanks for your message. The SP's that stored your data don't see to support retrieval. I will attempt a second try over the weekend to see if i can retrieve your data. Retrievability is a key component of the FIL+ rules to enable me to check what the data is that is stored.

Thanks for your understanding.

**Comment by mutablepunk** [comment]
> 
@cryptowhizzard  There is one SP that does not support retrieval, and other SPs support retrieval. We have informed SP by email that we need to open the online retrieval mode. Can you sign for me before that? I will solve this problem in the second round.

**Comment by C00kies77** [comment]
@mutablepunk We recommend not signing anything before retrievals on all SP's are working properly. As soon as you can show us proper results we will take another look at your application

Thanks for your understanding.

**Comment by mutablepunk** [comment]
@cryptowhizzard @C00kies77   The SP f054420 cannot be retrieved. SP is also trying to solve the problem. I will not send a new order to this SP until the problem is solved. Can you help me enter the second round first. Until it solves the retrieval problem, I will issue it again.

**Comment by mutablepunk** [comment]
F054420 email replies can already support retrieval. Can you help me enter the second round? @cryptowhizzard

**Comment by mutablepunk** [comment]
![图片](https://user-images.githubusercontent.com/113664386/218678042-c3084c91-c3e5-4fa7-930c-fdb22105f642.png)

**Comment by cryptowhizzard** [comment]
Hi,

I checked on f054420 but they are listed in our system as abusive SP connected to abuse LDN's.
I have it in my system under #1214 , the owner of that ticket deleted it.

Tbh, i would like you to replace this SP for another one. I will test retrievals on the others.

**Comment by cryptowhizzard** [comment]
Feb 14 10:55:03 proposals dealscanner-f01997810-f060754: ERROR: failed to find offer satisfying maxPrice: 0 FIL. Try increasing maxPrice
Feb 14 10:55:03 proposals dealscanner-f01997810-f060754: 
Feb 14 10:55:03 proposals dealscanner-f01997810-f054420: ERROR: failed to find offer satisfying maxPrice: 0 FIL. Try increasing maxPrice

Btw ... the issue is still not fixed.

**Comment by mutablepunk** [comment]
> Feb 14 10:55:03 proposals dealscanner-f01997810-f060754: ERROR: failed to find offer satisfying maxPrice: 0 FIL. Try increasing maxPrice Feb 14 10:55:03 proposals dealscanner-f01997810-f060754: Feb 14 10:55:03 proposals dealscanner-f01997810-f054420: ERROR: failed to find offer satisfying maxPrice: 0 FIL. Try increasing maxPrice
> 
> Btw ... the issue is still not fixed. The price above is 0.1 . Retrieval should be free according to the FIL+ rules!

@cryptowhizzard   I have helped SP solve this problem.

**Comment by mutablepunk** [comment]
> Hi,
> 
> I checked on f054420 but they are listed in our system as abusive SP connected to abuse LDN's. I have it in my system under #1214 , the owner of that ticket deleted it.
> 
> Tbh, i would like you to replace this SP for another one. I will test retrievals on the others.

We had in-depth exchanges before reaching cooperation with the SP. If we can't store the data according to the Fil+rule, we will stop distributing the data at any time. There is still a retrieval problem in the early stage. SP has fixed this problem yesterday. If there are other problems in the future, we will terminate the cooperation with this SP at any time

**Comment by mutablepunk** [comment]
@herrehesse @cryptowhizzard   Hello, what can I do for you? Continue to wait?

**Comment by herrehesse** [comment]
I would like to see a list of SP's and their business names and regions. And why are you only storing in "Asia", if you can reach HK, SG and JP from your location you can also distribute to EU and USA.

**Comment by mutablepunk** [comment]
@herrehesse At present, the partners are mainly in Asia.
We are also looking for suitable SP in the United States and Europe

**Comment by herrehesse** [comment]
@mutablepunk Love to assist you in that process, let me know if you need any assistance. Love to support if you can distribute your dataset better.

**Comment by mutablepunk** [comment]
Will do! We will abide by the rules of FIl+ and try to distribute data in regions other than Asia.

**Comment by mutablepunk** [comment]
@herrehesse   Thanks, glad to have your help!
I will choose more regions to distribute my data at a later stage!
Can you help me pass this round?

**Comment by herrehesse** [comment]
Nope, first an SP list with more regions, then we can (if the retrieval is OK) help you sign this next round!

**Comment by mutablepunk** [comment]
f01949260  Fuzhou
f01949267  Fuzhou
f02016677  HK
f060754    HK
f01907578  PuTian
f0123931   Fuzhou
f01807707  ShenZhen
Frankfurt  confirming
@herrehesse  Here is our SP list for the second round
There is also a partner of Frankfurt who is communicating. If appropriate, he will start Boost!

**Comment by herrehesse** [comment]
Awesome! What are their business names? Locations are noted.

**Comment by mutablepunk** [comment]
@herrehesse 
f01949260 Fuzhoushuidiwangluo  Technology Co. Ltd
f01949267 Fuzhoushuidiwangluo  Technology Co. Ltd
f02016677 Personal
f060754  Shenzhenshuidixinxijishu Technology Co. Ltd
f01907578 Personal
f0123931 Fuzhou Blue Coast Network Technology Co. LTD
f01807707 ShenzhenXingyuecunchu Technology Co. Ltd

**Comment by herrehesse** [comment]
@mutablepunk Thank you for being transparent. Will put the data inside our database and discuss with @cryptowhizzard about next steps. If all is in order love to sign your application.

**Comment by cryptowhizzard** [comment]
Hi @mutablepunk 

Thanks for this. Based on above information you are almost good to go.
I only have a problem with SP f01807707. It is in a subnet where much abuse has been going on.

Can we agree that you will not use that SP and onboard with the others? If so, i am ok to sign.

**Comment by mutablepunk** [comment]
@cryptowhizzard 
Thank you for your reminding and suggestion. I agree with your suggestion and terminate the cooperation with the SP

**Comment by cryptowhizzard** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacectqeicwbzvr6uuu6ryta2yf4pfageqs6ml4sonb2t36ytx35erxo 
#### Address 
> f1jqrcpugschakigqqvivbk3mfr6hx6jkf42kyqya
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1krmypm4uoxxf3g7okrwtrahlmpcph3y7rbqqgfa
#### Id
> 0be0d103-a186-4baf-8d11-ed25f82b4a78
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacectqeicwbzvr6uuu6ryta2yf4pfageqs6ml4sonb2t36ytx35erxo

**Comment by YuanHeHK** [comment]
The previous information is disclosed completely, and I tried to retrieve it without problems, I will support it。
![mmexport1676953549316](https://user-images.githubusercontent.com/69455705/220247591-2dc7ab15-994a-4f12-b0fa-d5bbb1b67f77.png)
![mmexport1676953551489](https://user-images.githubusercontent.com/69455705/220247598-87b92aed-0d5e-4fb1-b2e0-57ecfab3ed80.png)

**Comment by YuanHeHK** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceau4pr5dwxz775hz77xvmzaa4m5o3zozzkvpl76sqryciqd4n3lpa 
#### Address 
> f1jqrcpugschakigqqvivbk3mfr6hx6jkf42kyqya
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1fg6jkxsr3twfnyhdlatmq36xca6sshptscds7xa
#### Id
> 0be0d103-a186-4baf-8d11-ed25f82b4a78
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceau4pr5dwxz775hz77xvmzaa4m5o3zozzkvpl76sqryciqd4n3lpa

**Comment by mutablepunk** [comment]
checker:manualTrigger

**Comment by mutablepunk** [comment]
checker:manualTrigger

**Comment by Tom-OriginStorage** [comment]
checker:manualTrigger

**Comment by Tom-OriginStorage** [comment]
![image](https://user-images.githubusercontent.com/103015469/221737529-b4386752-efc9-44fb-aa16-ef12d14be486.png)

**Comment by Tom-OriginStorage** [comment]
The bot shows that the packaging is more in line with the rules. There is no CID sharing, and the retrieval is performed randomly. It can be downloaded normally and meets the OriginStorage signature standard. We are willing to support it

**Comment by Tom-OriginStorage** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebzasmqqtncllh5iktwmagmmo77xuxvgjzxii4c2gfqgjrsu42oxo 
#### Address 
> f1jqrcpugschakigqqvivbk3mfr6hx6jkf42kyqya
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1q6bpjlqia6iemqbrdaxr2uehrhpvoju3qh4lpga
#### Id
> 0be0d103-a186-4baf-8d11-ed25f82b4a78
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebzasmqqtncllh5iktwmagmmo77xuxvgjzxii4c2gfqgjrsu42oxo

**Comment by kernelogic** [comment]
After reviewing the bot report, I have come to the same conclusion as @Tom-OriginStorage . Willing to support.

**Comment by kernelogic** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacea7gczf562jpm3mzyvaymjreqfa34q7pwnbzjkabdlyvj4cz3s63u 
#### Address 
> f1jqrcpugschakigqqvivbk3mfr6hx6jkf42kyqya
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### Id
> aeb81f52-1795-40fa-b00a-70f32553b007
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacea7gczf562jpm3mzyvaymjreqfa34q7pwnbzjkabdlyvj4cz3s63u

**Comment by mutablepunk** [comment]
checker:manualTrigger

**Comment by mutablepunk** [comment]
@xiaoyuaiheshui  @newwebgroup   Dear Notary, can you help me to get to the next round?

**Comment by xiaoyuaiheshui** [comment]
checker:manualTrigger

**Comment by xiaoyuaiheshui** [comment]
![image](https://user-images.githubusercontent.com/43629914/223049581-a514179f-fcf9-49f2-aeb5-b0efd2c5ace7.png)
Received your request again. From the above report, the data distribution is healthy and supports retrieval. I would like to support again.

**Comment by cryptowhizzard** [comment]
> ![image](https://user-images.githubusercontent.com/43629914/223049581-a514179f-fcf9-49f2-aeb5-b0efd2c5ace7.png) Received your request again. From the above report, the data distribution is healthy and supports retrieval. I would like to support again.

Likewise. Checked retrieval, all looks good.

**Comment by cryptowhizzard** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec7etbcxzti6cfpsi4uzj6yrkp66hyo746fmosegvyypcu4kxingu 
#### Address 
> f1jqrcpugschakigqqvivbk3mfr6hx6jkf42kyqya
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1krmypm4uoxxf3g7okrwtrahlmpcph3y7rbqqgfa
#### Id
> d995bc20-0e05-4842-b02c-d1e031983459
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec7etbcxzti6cfpsi4uzj6yrkp66hyo746fmosegvyypcu4kxingu

**Comment by xiaoyuaiheshui** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced3axsbwjbzqlucbs5s7lfcuxvnui6xxxvxnfh4t7gaqc2qdw7ylq 
#### Address 
> f1jqrcpugschakigqqvivbk3mfr6hx6jkf42kyqya
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f122qmy25wdtt5mxd77kndiq7z5x2n3iwiuz2wdsa
#### Id
> d995bc20-0e05-4842-b02c-d1e031983459
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced3axsbwjbzqlucbs5s7lfcuxvnui6xxxvxnfh4t7gaqc2qdw7ylq

**Comment by Joss-Hua** [comment]
![image](https://user-images.githubusercontent.com/75723122/223636123-438520e8-ac7c-4e10-b827-5fc94a3c7e89.png)
 the data distribution is healthy and supports retrieval. Cool.

**Comment by Joss-Hua** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceacghyjo6qd2robh4cc35ekqo5iwdfl3fv32fmqzkomvdjqlwggie 
#### Address 
> f1jqrcpugschakigqqvivbk3mfr6hx6jkf42kyqya
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1tfg54zzscugttejv336vivknmsnzzmyudp3t7wi
#### Id
> a49e7298-4e0a-4596-8994-53a611971cd1
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceacghyjo6qd2robh4cc35ekqo5iwdfl3fv32fmqzkomvdjqlwggie

**Comment by newwebgroup** [comment]
checker:manualTrigger

**Comment by newwebgroup** [comment]
CID Checker reports compliance, data support retrieval

<img width="1109" alt="image" src="https://user-images.githubusercontent.com/100118145/223999209-651c26e5-2490-4732-916d-55de0295ee53.png">

**Comment by newwebgroup** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb6fd2wnqhwg7kpbrefutzjue6wgemspewirr7n4lbfqgr7xxywga 
#### Address 
> f1jqrcpugschakigqqvivbk3mfr6hx6jkf42kyqya
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1e77zuityhvvw6u2t6tb5qlnsegy2s67qs4lbbbq
#### Id
> a49e7298-4e0a-4596-8994-53a611971cd1
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb6fd2wnqhwg7kpbrefutzjue6wgemspewirr7n4lbfqgr7xxywga

**Comment by wozhishilaonanhai** [comment]
checker:manualTrigger

**Comment by 1ane-1** [comment]
Report is ok. Everthing goes well.

**Comment by 1ane-1** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebjnuybrz7bwxzdlb63p4wd24lupsibnofyohokajfgg4ta4yjtni 
#### Address 
> f1jqrcpugschakigqqvivbk3mfr6hx6jkf42kyqya
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1mdk7s2vntzm6hu35yuo6vjubtrpfnb2awhgvrri
#### Id
> b3b41112-7c6e-4302-9353-0eb95dd616eb
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebjnuybrz7bwxzdlb63p4wd24lupsibnofyohokajfgg4ta4yjtni

**Comment by mikezli** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecvu33bk246isem7pj2ywhvvhn2tnf6gjnrv4dp2d5x5t77oexrec 
#### Address 
> f1jqrcpugschakigqqvivbk3mfr6hx6jkf42kyqya
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1dnb3uz7sylxk6emti3ififcvu3nlufnnsjui6ea
#### Id
> b3b41112-7c6e-4302-9353-0eb95dd616eb
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecvu33bk246isem7pj2ywhvvhn2tnf6gjnrv4dp2d5x5t77oexrec
