### ISSUE TITLE
[DataCap Application] <DeSci Labs> - <General Index>

### ISSUE THREAD

**Issue by ewvanwinkle** [filecoin-project/filecoin-plus-large-datasets#1424]
### Data Owner Name

DeSci Labs

### Data Owner Country/Region

Switzerland

### Data Owner Industry

Other

### Website

https://www.desci.com/

### Social Media

```text
https://twitter.com/DeSciLabs and https://www.youtube.com/channel/UCzVdQSku9md4WxruSIKdnZw
```

### Total amount of DataCap being requested

500TiB

### Weekly allocation of DataCap requested

100TiB

### On-chain address for first allocation

f1v56ou42aazt5xywckezi6txqzy63qokkzpcvpby

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
The General Index is an index to scientific journals. It consists of a listing of n-grams, from unigrams to five-grams, extracted from 107 million journal articles. Access to the full corpus of scholarly journals is an essential facility to the practice of science in our modern world. The General Index is an invaluable utility for researchers who wish to search for articles about plants, chemicals, genes, proteins, materials, geographical locations, and other entities of interest. The General Index allows scholars and students all over the world to perform specialized and customized searches within the scope of their disciplines and research over the full corpus.

DeSci Labs was started in 2021 with the goal of building technologies for open and reproducible science. We strive to bring simplicity, radical accessibility, and higher efficiency to scientific publishing and funding. We are scientists and engineers building tools to make knowledge more accessible and verifiable. We envision a scientific record without data silos, content drift, paywalls, and proprietary analytics. We build technologies for open and reproducible science. We strive to bring simplicity, radical accessibility, and higher efficiency to scientific publishing and funding.
```

### Is this project associated with other projects/ecosystem stakeholders?

Yes

### If answered yes, what are the other projects/ecosystem stakeholders

```text
DeSci Foundation
```

### Describe the data being stored onto Filecoin

```text
The General Index consists of 3 tables derived from 107,233,728 journal articles. A table of n-grams, ranging from unigrams to 5-grams, is extracted using SpaCy. Each  of the 355,279,820,087 rows of the n-gram table consists of an n-gram coupled with a journal article id. A second table is constructed using Yake and consists of 19,740,906,314 rows, each with a keywords and an article id. A third table associates an article id with metadata. 

The metadata, readme, and sample files are available on this item in the data downloads area.
The README.txt file contains more information.
The corpus of articles has been split into 16 slices. We keep the keywords and n-grams files, one for each of the 16 slices, in separate items. We do this to avoid overloading the servers. Be careful, these files are big and inflate greatly upon unzipping.
The keywords are located here: [ 0 : 1 : 2 : 3 : 4 : 5 : 6 : 7 : 8 : 9 : a : b : c : d : e : f ]
The n-grams are located here: [ 0 : 1 : 2 : 3 : 4 : 5 : 6 : 7 : 8 : 9 : a : b : c : d : e : f ]
You can see all the items at this URL: https://archive.org/search.php?query=%22general%20index%22%20AND%20collection%3Amulticasting
Public Resource has also made available The TDM Today Show and an early release of The Florilegium: A Special Index to Plants. A previous article about our work in this area appeared in Nature. The General Index was also the subject of a more recent article in Nature. There is also a Special Index to Species available.
```

### Where was the data currently stored in this dataset sourced from

Other

### If you answered "Other" in the previous question, enter the details here

Internet Archives

### How do you plan to prepare the dataset

I don't know yet

### Please share a sample of the data

```text
https://ia802307.us.archive.org/18/items/GeneralIndex/data/
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [ ] I confirm

### What is the expected retrieval frequency for this data

Monthly

### For how long do you plan to keep this dataset stored on Filecoin

1 to 1.5 years

### In which geographies do you plan on making storage deals

Asia other than Greater China, North America, Europe, Australia (continent)

### How will you be distributing your data to storage providers

I don't know yet

### How do you plan to choose storage providers

Slack, Partners

### How do you plan to make deals to your storage providers

I don't know yet

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
What's the relationship between you and the organization?
Could you send an email to filplus-app-review@fil.org with your official domain in order to confirm your identity? Email name should includes the issue id #1424.

**Comment by Sunnyiscoming** [comment]
Any update here?

**Comment by Sunnyiscoming** [comment]
Close for no reply.
