### ISSUE TITLE
[DataCap Allocation] - Nongshangtong-Agricultural Products Trading Information Service Project

### ISSUE THREAD

**Issue by NongShangTong** [filecoin-project/filecoin-plus-large-datasets#1426]
---
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Chengdu Nongshangtong Network Technology Group Co. LTD
- Website / Social Media: https://www.nst168.com/ 
- Region: Greater China Region
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 200TiB
- On-chain address for first allocation: f1kpiaodl3zfqqdd3kzmyrivo6deub7o2wmxsu3fi

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Chengdu Nongshangtong Network Technology Group Co. LTD was established in 2015, which is an innovative agricultural Internet enterprise jointly initiated by senior commodity trading market professionals, Internet experts and agricultural entrepreneurs, with the participation of a Hong Kong listed company and a registered capital of 50 million RMB. It mainly operates two platforms: agricultural products trading information service and online auction. In 2022, awarded the title of "National High-tech Enterprise" .

By building an information service platform for agricultural products trading, the company solves the problems of industrial pain caused by asymmetrical and untimely agricultural information in China, such as blindly following the trend of farming, imbalance of regional supply and demand, and large price fluctuations. In addition, through the standardization of special agricultural products, the traditional agricultural products trading market is comprehensively upgraded by means of "auction" and "order" trading, which solves the problems of long trading links and high circulation costs of agricultural products and makes up for the problems of packaging, promotion, logistics, etc. in the sales of agricultural products (B2C) on mainstream e-commerce platforms. ) of packaging, promotion, logistics and other high cost deficiencies.

The auction center is a new trading model with the online and offline auction platform independently developed by Farmers Business as the main operation carrier, which can sell agricultural products with local characteristics at a higher price to increase farmers' income, at a more standardized price to meet the government's supervision of the market, and at a more professional price to increase product awareness through auction. It can sort out clearer product values for farmers of origin, help local governments achieve precise poverty alleviation, and provide help for local agricultural industry upgrading.

Through a variety of effective measures to achieve the goal of seasonal profitability, such as direct propaganda to farmers in advance, positive report propaganda of online auction mode in advance, vigorous development of scattered wholesale vendors from offline, introduction of 10,000-ton bulk commodity buyers, opening online auction live with goods and propaganda, and reasonable joint local e-commerce team with resources.

Now the Group also has business segments around agriculture upstream, midstream and downstream, such as fruit chain, agricultural materials sales, whole vehicle trade and financial services.

Since the outbreak of the Covid-19 epidemic in 2020, our model has provided more farmers with a better way to introduce and sell their agricultural products, solving their difficulties of not being able to conduct business normally because of the epidemic. Hundreds of thousands of farmers have been greatly helped as a result. We are happy to continue to provide more and more farmers, especially those in poor areas, with more convenient and less expensive services.
```
WeChat
![农商通](https://user-images.githubusercontent.com/119988652/206078500-f817348e-5392-4dd9-9c40-def464c9c987.jpg)
![农商通服务号](https://user-images.githubusercontent.com/119988652/206078580-7348f302-6db3-47be-9b18-32692ead03fa.jpg)
Links to social media reports：
https://www.36kr.com/p/1721946292225
https://www.sohu.com/a/319645517_717450
https://new.qq.com/rain/a/20211101A037XN00
http://www.agri.cn/zx/xxlb/xj/202007/t20200715_7457262.htm
http://news.ts.cn/system/2020/06/16/036317621.shtml
https://www.ts.cn/xwzx/dzxw/202203/t20220328_5724509.shtml
http://3g.k.sohu.com/t/n465073147
http://www.fujianfood.net/ShowNews/Newsdetail/16085.html
https://c.m.163.com/news/a/FI06698Q0512JAEJ.html

What is the primary source of funding for this project?
```
Business Development  earnings and Shareholders' Own Funds.
```

What other projects/ecosystem stakeholders is this project associated with?
```
None.
```

## Use-case details

Describe the data being stored onto Filecoin
```
The data content is agricultural products information, categories are: pictures, videos and text information description.Since the company has been operating for 7 years, there are more than 4 million B-side users in the reserve agriculture, more than 100,000 certified stores, and more than 5,000 pieces of supply information daily. The supply information includes photos, videos and text descriptions taken by farmers on agricultural products.
The data volume is more than 1p and is planned to be stored in 5 copies.
```

Where was the data in this dataset sourced from?
```
The data is copyrighted by Chengdu Nongshangtong Network Technology Group Co. LTD 
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
Agricultural Supply Information: https://1drv.ms/u/s!AgPkq2rHCOqUihfus6D-UWYA4WUg?e=xemYz4
Agricultural Related Information Promotion Articles: https://1drv.ms/u/s!AgPkq2rHCOqUgjXhtDuJdhfrYsWG?e=bYciv5
E-commerce training for agricultural products from poor areas: https://1drv.ms/u/s!AgPkq2rHCOqUihzm_sp9o23haOrA?e=R7cM3z
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes,I confirm that this is a public dataset that can be retrieved by anyone on the Network.
```

What is the expected retrieval frequency for this data?
```
Due to the large amount of data,it will not be retrieved often.Maybe once a year.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
Permanently.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Asia.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Use offline transmission (including hard disk copy) to transmit data.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We have contacted a number of SPs via slack to get basic information through online meetings, and after preliminary judgment, we will conduct field visits to SPs, and will select professional, mature and trustworthy SPs, including the examination of whether they have real data storage experience, long-term storage operation and maintenance capabilities and data retrievability and other capabilities.

Currently we have contacted the following SPs and they applied for the following nodes for us，f01986300，f01986311，f01986314，f01986317.
```

How will you be distributing deals across storage providers?
```
First we will contact multiple storage providers to ensure distributed storage of data, with each storage provider storing no more than 25% of our total data.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
The funds for storage are ready.
```

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> PiB

**Expected weekly DataCap usage rate**

> TiB

**Client address**

>
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 200TiB

**Client address**

> f1kpiaodl3zfqqdd3kzmyrivo6deub7o2wmxsu3fi

**Comment by herrehesse** [comment]
Dear Applicant,

Due to the increased amount of erroneous/wrong Filecoin+ data recently, on behalf of the entire community, we feel compelled to go deeper into datacap requests. Hereby to ensure that the overall value of the Filecoin network and Filecoin+ program increases and is not abused.

Please answer the questions below as comprehensively as possible.

**Customer data**

- Could you demonstrate exactly how and to what extent customer contact occurred? 

We expect that for the onboarding of customers with the scale of an LDN there would have been at least multiple email and perhaps several chat conversations preceding it. A single email with an agreement does not qualify here.

- Did the customer specify the amount of data involved in this relevant correspondence?

- Why does the customer in question want to use the Filecoin+ program? 

_Should this only be soley for acquiring datacap this is of course **out of the question**. The customer must have a legitimate reason for wanting to use the Filecoin+ program which is intended as a program to store useful and public datasets on the network._ 

- Why is the customer data considered Filecoin+ eligible?

_(As an intermediate solution Filecoin offers the FIL-E program or the glif.io website for business datasets that do not meet the requirements for a Filecoin+ dataset)_


**Files and Processing**

- Could you please demonstrate to us how you envision processing and transporting the customer data in question to any location for preparation?
- Would you demonstrate to us that the customer, the preparer and the intended storage providers all have adequate bandwidth to process the set with its corresponding size?
- Would you tell us how the data set preparer takes into account the prevention of duplicates in order to prevent data cap abuse?


Hopefully you understand the caution the overall community has for onboarding the wrong data. We understand the increased need for Filecoin+, however, we must not allow the program to be misused. Everything depends on a valuable and useful network, let's do our best to make this happen. Together.

**Comment by NongShangTong** [comment]
@cryptowhizzard  Thanks for your review,  I saw that this form needs to be filled out with SP, I am now looking for definitive SP, I will perfect this form when I find it, thank you!

**Comment by bella000000** [comment]
Hi, @cryptowhizzard , this is part of our company's data, as data is generated continuously and this is not the most recent.
Our storage provider has not been finalized yet.
We will cooperate with fil+ notaries to do due diligence while we contact storage providers.
![visible proof](https://user-images.githubusercontent.com/110386295/222070782-124081d1-bba3-4497-a7b8-fc462e930d55.png)

**Comment by NongShangTong** [comment]
Hi, @cryptowhizzard , this is part of our company's data, as data is generated continuously and this is not the most recent.
Our storage provider has not been finalized yet. We will cooperate with fil+ notaries to do due diligence while we contact storage providers.
![visible proof](https://user-images.githubusercontent.com/119988652/222073484-6d9303ac-92f5-4a9d-a189-6e3906644dfc.png)

**Comment by sxxfuture-official** [comment]
Thanks for your application ~
Hope you can answer the following two questions for me:
- send a confirmation email to [filplus-app-review@fil.org](mailto:filplus-app-review@fil.org) （also send to [kyc@sxxfture.com](mailto:kyc@sxxfture.com)）using the email address of your domain '@nst168.com'.
- Please disclose your next sealing plan, such as SPs and their distribution areas.

**Comment by NongShangTong** [comment]
@sxxfuture-official Hi, we have sent a confirmation email.
![d9101f57750dc822e89b83ef1c07be1](https://user-images.githubusercontent.com/119988652/226539600-f8ad56ed-a5aa-4ce2-8ce3-f24de9553442.png)
Here are our sps and their distribution areas，f01986300 AU
f01986311 HK
f01986314 HK
f01986317 SGP

**Comment by sxxfuture-official** [comment]
![image](https://user-images.githubusercontent.com/113963951/226540314-51b248dc-8380-4692-b8cb-39f2b4183350.png)

Received kyc mail and checked OK.
Based on disclosed plans, I will support this round

**Comment by sxxfuture-official** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceczi2zbapcwlyypitlsim3yhhdprdqjjssjlkmpgvm5rfahmxhi2i 
#### Address 
> f1kpiaodl3zfqqdd3kzmyrivo6deub7o2wmxsu3fi
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1foiomqlmoshpuxm6aie4xysffqezkjnokgwcecq
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceczi2zbapcwlyypitlsim3yhhdprdqjjssjlkmpgvm5rfahmxhi2i

**Comment by NongShangTong** [comment]
> **We have found some problems in the information provided in the Approved Comment. We could not find **Id** field in the information provided
> 
> ```
> Please, take a look at the comment and edit the body of the comment providing all the required information.
> ```

Is this a bug? Please help me. @galen-mcandrew @simonkim0515

**Comment by OpenGate01** [comment]
At present, as the first round, I would like to support you. Please abide by all the rules.

**Comment by OpenGate01** [comment]
> > **We have found some problems in the information provided in the Approved Comment. We could not find **Id** field in the information provided
> > ```
> > Please, take a look at the comment and edit the body of the comment providing all the required information.
> > ```
> 
> Is this a bug? Please help me. @galen-mcandrew @simonkim0515

I can't find this application, may need to wait for this to be resolved.

**Comment by NongShangTong** [comment]
@fabriziogianni7 Hi, I contacted notaries to sign for us, but they don't see this item number in the backend, can you help me with this?
