### ISSUE TITLE
[DataCap Application] Tianjin Zhihui Marine Tech - Marine Exploration Data

### ISSUE THREAD

**Issue by UriahSee** [filecoin-project/filecoin-plus-large-datasets#1432]
### Data Owner Name

Tianjin Zhihui Marine Technology Co., Ltd

### Data Owner Country/Region

China

### Data Owner Industry

Environment

### Website

www.tjzhocean.com

### Social Media

```text
www.tjzhocean.com
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

400TiB

### On-chain address for first allocation

f1xd4hex5q44mkddd2n3wr23jmbv7qyzqdcsyetea

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Established in Tianjin Airport Economic Zone, Tianjin Zhihui ocean is mainly engaged in the sales, maintenance, leasing and technical services of hardware and software such as marine surveying and mapping equipment, intelligent unmanned platform and underwater engineering. At present, it has reached cooperation with many well-known enterprises such as Kongsberg, Applanix, Norbit, sonardyne, sontek, tritech, valeport and AML.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
Tianjin Zhihui has its own production and Research Center, which does research and development work such as marine exploration, UAV river survey, and mapping equipment. 
Data, which we plan to store on Filecoin, is come from our R&D Center without copyright issues, with the data format of docs, pictures, and videos.
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### How do you plan to prepare the dataset

IPFS, lotus, singularity, graphsplit

### Please share a sample of the data

```text
https://pan.baidu.com/s/11UWlgPnWsknM3sKYKlZWHA  Extraction code： arni
https://pan.baidu.com/s/10sU5bqRNqjewvo1C7LuYMA   Extraction code：qgpa
https://pan.baidu.com/s/1dlzg9wnlfinuaUIKOityOw   Extraction code：goch
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Monthly

### For how long do you plan to keep this dataset stored on Filecoin

More than 3 years

### In which geographies do you plan on making storage deals

Asia other than Greater China, North America, Europe

### How will you be distributing your data to storage providers

Cloud storage (i.e. S3), HTTP or FTP server, IPFS

### How do you plan to choose storage providers

Slack, Filmine, Big data exchange, Partners

### If you already have a list of storage providers to work with, fill out their names and provider IDs below

```text
Still in communicating with qualified SPs.
```

### How do you plan to make deals to your storage providers

Lotus client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
Any update here?

**Comment by UriahSee** [comment]
> https://filplus.d.interplanetary.one/clients?filter=f1xd4hex5q44mkddd2n3wr23jmbv7qyzqdcsyetea The address is used to apply before. Can you explain about that?
> 
> ![image](https://user-images.githubusercontent.com/105098820/207371616-1c6acd4e-4960-4077-99e5-f547a11938f2.png) Data samples you provided are not available. Please check it.

Hi @Sunnyiscoming.
This project is the resubmit of LDN #126. The previous account has been flagged and blocked, so we submit it again.

For this project, we plan to store following datasets:
- [Pacific Ocean Sound Recordings](https://registry.opendata.aws/pacific-sound/)
- [NOAA Operational Forecast System (OFS)](https://registry.opendata.aws/noaa-ofs/)
- [Sea Around Us Global Fisheries Catch Data](https://registry.opendata.aws/sau-global-fisheries-catch-data/)
-[ Sea Surface Temperature Daily Analysis](https://registry.opendata.aws/surftemp-sst/)
- [Sentinel-3](https://registry.opendata.aws/sentinel-3/)
- [NOAA Wave Ensemble Reforecast](https://registry.opendata.aws/noaa-wave-ensemble-reforecast/)
- [NOAA Global Extratropical Surge and Tide Operational Forecast System](https://registry.opendata.aws/noaa-gestofs/)
- [NOAA National Bathymetric Source Data](https://registry.opendata.aws/noaa-bathymetry/)
- [NOAA S-102 Bathymetric Surface Data](https://registry.opendata.aws/noaa-s102/)
- [NOAA Unified Forecast System (UFS) Marine Reanalysis: 1979-2019](https://registry.opendata.aws/noaa-ufs-marinereanalysis/)
- [Orcasound - bioacoustic data for marine conservation](https://registry.opendata.aws/orcasound/)

More than 400+TIB in total. And we plan to store at least 10 copies on the Filecoin network, supporting data retrieval as well.

**Comment by Sunnyiscoming** [comment]
Could you send an email to filplus-app-review@fil.org with your official domain in order to confirm your identity? Email name should includes the issue id #1432
.

**Comment by Sunnyiscoming** [comment]
No email received.

**Comment by herrehesse** [comment]
Dear Applicant,

Due to the increased amount of erroneous/wrong Filecoin+ data recently, on behalf of the entire community, we feel compelled to go deeper into datacap requests. Hereby to ensure that the overall value of the Filecoin network and Filecoin+ program increases and is not abused.

Please answer the questions below as comprehensively as possible.

**Customer data**

- Could you demonstrate exactly how and to what extent customer contact occurred? 

We expect that for the onboarding of customers with the scale of an LDN there would have been at least multiple email and perhaps several chat conversations preceding it. A single email with an agreement does not qualify here.

- Did the customer specify the amount of data involved in this relevant correspondence?

- Why does the customer in question want to use the Filecoin+ program? 

_Should this only be soley for acquiring datacap this is of course **out of the question**. The customer must have a legitimate reason for wanting to use the Filecoin+ program which is intended as a program to store useful and public datasets on the network._ 

- Why is the customer data considered Filecoin+ eligible?

_(As an intermediate solution Filecoin offers the FIL-E program or the glif.io website for business datasets that do not meet the requirements for a Filecoin+ dataset)_


**Files and Processing**

- Could you please demonstrate to us how you envision processing and transporting the customer data in question to any location for preparation?
- Would you demonstrate to us that the customer, the preparer and the intended storage providers all have adequate bandwidth to process the set with its corresponding size?
- Would you tell us how the data set preparer takes into account the prevention of duplicates in order to prevent data cap abuse?


Hopefully you understand the caution the overall community has for onboarding the wrong data. We understand the increased need for Filecoin+, however, we must not allow the program to be misused. Everything depends on a valuable and useful network, let's do our best to make this happen. Together.

**Comment by cryptowhizzard** [comment]
Hi @Sunnyiscoming 

Can you confirm you received a mail from this applicant?

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

As last question i would like you to fill out [this form](https://form.jotform.com/230337462961356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!

**Comment by UriahSee** [comment]
> Dear applicant,
> 
> Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.
> 
> As last question i would like you to fill out [this form](https://form.jotform.com/230337462961356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.
> 
> Thanks!

Thank you for reviewing our application. I found that in the form(https://form.jotform.com/230337462961356) we have to fil out 4 SPs' information which we cant confirm yet. But we have been reaching out to different SPs  in different regions recently and we are very close to get the SPs  to store our data. Once we get confirmation from the SPs I will comment here. Please kindly approve our LDN application. Thank you!

**Comment by UriahSee** [comment]
> Dear applicant,
> 
> Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.
> 
> As last question i would like you to fill out [this form](https://form.jotform.com/230337462961356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.
> 
> Thanks!

Hi@cryptowhizzard ,
Thank you for reviewing our application. I found that in the form(https://form.jotform.com/230337462961356) we have to fil out 4 SPs' information which we cant confirm yet. But we have been reaching out to different SPs in different regions recently and we are very close to get the SPs to store our data. Once we get confirmation from the SPs I will comment here. Please kindly approve our LDN application. Thank you!

**Comment by Normalnoise** [comment]
@UriahSee How much data do you have downloaded? Do you have contact any SPs to store you data?

**Comment by Joss-Hua** [comment]
The client contacted me on Slack, and in simple terms, I believe it is possible to start the first step and keep further review for the second round.

**Comment by Joss-Hua** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacednyhhq2mijaqvtclpavrpr347oi2a7u33a33a52oqjzvd5djkepe 
#### Address 
> f1xd4hex5q44mkddd2n3wr23jmbv7qyzqdcsyetea
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1tfg54zzscugttejv336vivknmsnzzmyudp3t7wi
#### Id
> 2bc3d6ca-bda4-494d-872c-9e6b45d146cb
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacednyhhq2mijaqvtclpavrpr347oi2a7u33a33a52oqjzvd5djkepe

**Comment by Aaron01230** [comment]
The link of [LDN#126](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1432) has become 404, we are not sure whether KYC has been completed. can you provide a screenshot of the email sent?

**Comment by Normalnoise** [comment]
> 

for the first round, I am willing to support it

**Comment by Normalnoise** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecoicuhiqjnr4toaqcj4lvg3ic2qqkkv24o4j3trfgwmm5vfaalt2 
#### Address 
> f1xd4hex5q44mkddd2n3wr23jmbv7qyzqdcsyetea
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1c5non5yf35avgcpsqvxu4yj54yyvxorwyjochqq
#### Id
> 2bc3d6ca-bda4-494d-872c-9e6b45d146cb
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecoicuhiqjnr4toaqcj4lvg3ic2qqkkv24o4j3trfgwmm5vfaalt2

**Comment by UriahSee** [comment]
@Aaron01230 Thanks for the comment. We have finished KYC before.As mentioned above:
The previous account has been flagged and blocked so we have to submit it here again.Please see the screenshot of previous allocation of #126 below:
![126 DataCap Allocation](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/95369907/02d48358-5cb0-4325-8aa1-a7da95c209ff)

**Comment by UriahSee** [comment]
Thank you for your support! @Joss-Hua @Normalnoise

**Comment by Fatman13** [comment]
checker:manualTrigger
