### ISSUE TITLE
[DataCap Application] SHINEWAY

### ISSUE THREAD

**Issue by wesllej** [filecoin-project/filecoin-plus-large-datasets#1434]
### Data Owner Name

SHINEWAY

### Data Owner Country/Region

China

### Data Owner Industry

Construction, Property & Real Estate

### Website

www.shineway-st.com

### Social Media

```text
www.shineway-st.com
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

450TiB

### On-chain address for first allocation

f1smgxi4zoaj6oc2cq57g2f6w2ympmhddgwb3ezjq

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Xianwei Intelligent Technology (Suzhou) Co., Ltd., located in Suzhou Industrial Park, is a high-tech enterprise specializing in the R & D and sales of smart construction sites, smart communities and smart park products.


At present, the company focuses on the development of smart site business, combines Internet of things technology, big data technology and electronic communication technology, develops special smart equipment for the construction industry and develops smart site big data platform. The company also studies video AI and data analysis algorithms, provides reliable technical support for safe and civilized construction, and realizes environmental protection and intelligent management of construction sites.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
Text, pictures and video data such as construction personnel management module, hoisting machinery visual management module, safety early warning module, safety hazard recording and processing module, on-site video monitoring module, intelligent behavior analysis module, etc. These data are open source and we believe they can be safely stored in Filecoin.
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### How do you plan to prepare the dataset

IPFS, lotus

### Please share a sample of the data

```text
link:https://pan.baidu.com/s/1AYzYjM9Sfq9lHhpc5cPlSQ 
password:329f
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Monthly

### For how long do you plan to keep this dataset stored on Filecoin

More than 3 years

### In which geographies do you plan on making storage deals

Asia other than Greater China, North America, Europe

### How will you be distributing your data to storage providers

Cloud storage (i.e. S3), HTTP or FTP server, IPFS, Lotus built-in data transfer

### How do you plan to choose storage providers

Slack, Filmine

### How do you plan to make deals to your storage providers

Lotus client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
Can you explain your data composition and provide sufficient data samples separately? How many copies will you store?
What's the relationship between you and the organization?
Can you provide more detailed information about other storage providers participated in this program, such as you can list SPs you have contacted with at present?
Whether the sps you choose can support data retrieval?

**Comment by Sunnyiscoming** [comment]
Any update here?

**Comment by wesllej** [comment]
@Sunnyiscoming  Hi,please check out.
Can you explain your data composition and provide sufficient data samples separately? How many copies will you store?
Data Composition:
Data generated from our business: could be public without copyright issues.
Public datasets
Data sample:
Link: https://pan.baidu.com/s/15A1cbYrv4PsDUygzNQHJkw
Code: 6fph 
We plan to store 6-10 copies onto Filecoin

What's the relationship between you and the organization?
I'm the staff of Xianwei Intelligent Technology (Suzhou) Co., Ltd, and I am also responsible for this program.
A verification email will send to filplus-app-review@fil.org. Please check it later.

Can you provide more detailed information about other storage providers participated in this program, such as you can list SPs you have contacted with at present?
We are still trying to contact more SPs according to this list (https://docs.google.com/spreadsheets/d/1rwT9ie6qlOM9hVUkYZLGej523X1pMenaVKhFuvQOiNE/edit#gid=442291216).
Furthermore, we also have a plan to:
Use Filmine to find SPs with storage deal experience.
Or consider publishing part of DataCap onto BigDataExchange

Whether the sps you choose can support data retrieval?
Yes, supporting data retrieval is one of the necessary conditions that we use to choose SPs to work together.

**Comment by Sunnyiscoming** [comment]
Can you take a screenshot of your mailing page and provide your business license to filplus-app-review@fil.org? I can't confirm the sender's email address.

**Comment by herrehesse** [comment]
Dear Applicant,

Due to the increased amount of erroneous/wrong Filecoin+ data recently, on behalf of the entire community, we feel compelled to go deeper into datacap requests. Hereby to ensure that the overall value of the Filecoin network and Filecoin+ program increases and is not abused.

Please answer the questions below as comprehensively as possible.

**Customer data**

- Could you demonstrate exactly how and to what extent customer contact occurred? 

We expect that for the onboarding of customers with the scale of an LDN there would have been at least multiple email and perhaps several chat conversations preceding it. A single email with an agreement does not qualify here.

- Did the customer specify the amount of data involved in this relevant correspondence?

- Why does the customer in question want to use the Filecoin+ program? 

_Should this only be soley for acquiring datacap this is of course **out of the question**. The customer must have a legitimate reason for wanting to use the Filecoin+ program which is intended as a program to store useful and public datasets on the network._ 

- Why is the customer data considered Filecoin+ eligible?

_(As an intermediate solution Filecoin offers the FIL-E program or the glif.io website for business datasets that do not meet the requirements for a Filecoin+ dataset)_


**Files and Processing**

- Could you please demonstrate to us how you envision processing and transporting the customer data in question to any location for preparation?
- Would you demonstrate to us that the customer, the preparer and the intended storage providers all have adequate bandwidth to process the set with its corresponding size?
- Would you tell us how the data set preparer takes into account the prevention of duplicates in order to prevent data cap abuse?


Hopefully you understand the caution the overall community has for onboarding the wrong data. We understand the increased need for Filecoin+, however, we must not allow the program to be misused. Everything depends on a valuable and useful network, let's do our best to make this happen. Together.

**Comment by wesllej** [comment]
@Sunnyiscoming Hi, we just returned from vacation. We will send a screenshot of our mailing page and provide the business license to the above email as soon as possible. Thanks.

**Comment by wesllej** [comment]
@Sunnyiscoming Hi, we have sent an email to the above email address. The sender's email address is the contact email displayed on our official website http://www.shineway-st.com/. Thanks.

**Comment by cryptowhizzard** [comment]
@wesllej can you be so kind to answer the questions of @herrehesse

**Comment by simonkim0515** [comment]
## Datacap Request Trigger

#### Total DataCap requested 
> 5PiB

#### Expected weekly DataCap usage rate 
> 450TiB 

#### Client address
> f1smgxi4zoaj6oc2cq57g2f6w2ympmhddgwb3ezjq

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Looking at your application i have some questions:
As you are brand new on Github and have no history of past applications it seems to me that applying for 5PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?

Can you show us visible proof of the size of your data and the storage systems you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230232885049356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!

**Comment by wesllej** [comment]
Hello.

We have been aware of the Filecoin network since last year. At present, we have a preliminary understanding of Filecoin. Our technique team also has the knowledge of packing of data, distribution of data and all it's requirements coming with it. If there are any problems with this process, we will also seek help from members of the community in a timely manner.

Regarding the visible proof of the size of our data and the storage systems we have, we store a large amount of data in IDC, which can be seen by the following figure.

![Shineway IDC Storage State](https://user-images.githubusercontent.com/95494662/216248923-0c84f001-3d0f-4936-a33f-3ce009980bde.png)

**Comment by herrehesse** [comment]
@wesllej that picture could be just Filecoin SP's storage. It does not proof anything. I can make the same picture a hundred times inside our datacenter, without any client data on it.

**Comment by wesllej** [comment]
After the first batch of DC is allocated, we will complete the storage. If in doubt, you can retrieve the data we store. This can allow you to verify that the data we actually store and the data mentioned in the application are consistent and true. Thanks.

**Comment by cryptowhizzard** [comment]
Again:

Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Looking at your application i have some questions:
As you are brand new on Github and have no history of past applications it seems to me that applying for 5PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?

Can you show us visible proof of the size of your data and the storage systems you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230232885049356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!

**Comment by nj-steve** [comment]
@wesllej Hello, how much data do you prepare for store?Please show more detail for the data! And where is this data now? Have you contacted to the storage providers？

**Comment by nj-steve** [comment]
@wesllej Hello, how much data do you prepare for store?Please show more detail for the data! And where is this data now? Have you contacted to the storage providers？

**Comment by wesllej** [comment]
Hi, @nj-steve currently we have about 400TiB data ready for store and the data is currently in our IDC. We have actively contacted with several storage providers through Slack and Filmine, but since the application has not been very smooth, we are currently in agreement with a few of them. Thanks.

**Comment by wesllej** [comment]
After several weeks of hard work, we actively contacted several storage providers and reached agreement with several of them. Has any notary paid attention to our application? We'd love to hear back!

**Comment by Fatman13** [comment]
checker:manualTrigger

**Comment by Fatman13** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacea3a3wsbvtkgvqd4o2kqy4ettg4cq33hglgm5plpjemldx46xs4ce 
#### Address 
> f1smgxi4zoaj6oc2cq57g2f6w2ympmhddgwb3ezjq
#### Datacap Allocated
> 225.00TiB
#### Signer Address
> f1j3u7crhjzwb2cj5mq7vodlt4o66yoyci7lhcauy
#### Id
> 385656b8-89b8-4ab2-bdea-e68628a4a570
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacea3a3wsbvtkgvqd4o2kqy4ettg4cq33hglgm5plpjemldx46xs4ce

**Comment by Fatman13** [comment]
Reached out by the client on Slack. Application looks okay for now. Will see how the 1st allocation goes.

**Comment by wesllej** [comment]
Has any notary paid attention to our application?  We need another notary to review our application, and we would be glad to provide feedback and answers.

**Comment by wesllej** [comment]
Dear notaries! Please take a look at our application, we need another notary to sign this application for us. Really need your support to keep going! Thanks!

**Comment by wesllej** [comment]
Dear notaries! We also need some notaries for the second part on this application, please take a look.Thanks!

**Comment by wesllej** [comment]
Has any notary paid attention to our application? We need another notary to review our application! Thanks!!

**Comment by wesllej** [comment]
We are still actively looking for notaries, and hope that more notaries will pay attention to our application. Thanks.

**Comment by wesllej** [comment]
Dear notaries! We also need some notaries for the second part on this application, please take a look.Thanks!

**Comment by clriesco** [comment]
Removed stale label and reopened issue :)

**Comment by wesllej** [comment]
Has any notary paid attention to our application? We need another notary to review our application, and we would be glad to provide feedback and answers.

**Comment by wesllej** [comment]
still in in progress and reopen the application :)
