### ISSUE TITLE
[DataCap Application] <Shenzhen Weite Network Culture Co., Ltd.> - <video archive>

### ISSUE THREAD

**Issue by hhhhxiao** [filecoin-project/filecoin-plus-large-datasets#1436]
### Data Owner Name

Shenzhen Weite Network Culture Co., Ltd.

### Data Owner Country/Region

China

### Data Owner Industry

Information, Media & Telecommunications

### Website

http://www.oktrust.com.cn/

### Social Media

```text
http://www.oktrust.com.cn/
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

300TiB

### On-chain address for first allocation

f16xlgzogkkd5qm44uftfprkvh44gu4ruo7dmngca

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Shenzhen Weite Network Culture Co., Ltd. was established in 2017. We have been engaged in e-commerce, live broadcast, short video shooting, corporate promotional videos and other businesses.
We are a comprehensive advertising communication agency with creative images as the core and all-media "one-stop" communication as the channel. The integrated brand communication work we are engaged in covers creative film and television production, corporate brand building, new media interactive marketing, etc.
Video: As a professional commercial video production and dissemination agency, Witt Media always takes the maximization of brand communication as the basis of creation. It has industry-leading directors and production team resources. Foreign large and medium-sized enterprises have provided hundreds of excellent film and television works.
Brand: From communication strategy to advertisement creation and placement, Weite Media provides customers with one-stop full-service services. With accurate consumer insight, strategic thinking, creative expression and integrated communication capabilities, we will create more prominent business value and social influence for customers in the all-media era.
New Media: Weite Media focuses on the most advanced new media marketing model in the "Internet +" era, integrates interactive media, advertising creativity and innovative technology, and provides the most complete innovative marketing services in the industry with rigorous execution and a professional attitude . Connect customers, brands, products, users, and society, and create new brand experiences through communication in the interactive field.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
We have a lot of live, e-commerce videos that need to be archived。
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### How do you plan to prepare the dataset

lotus

### Please share a sample of the data

```text
https://drive.google.com/file/d/1XAqPnIuVMC8tisHbDmcZgVsnHltJfObl/view?usp=share_link
https://drive.google.com/file/d/15A9rGG0mUr3DTUD8TWg7nVuZErdRCGcv/view?usp=share_link
https://drive.google.com/file/d/1AW4BXp_uc0ZdhbKXYxzE_F3acesZaA_4/view?usp=share_link
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

More than 3 years

### In which geographies do you plan on making storage deals

Greater China

### How will you be distributing your data to storage providers

Shipping hard drives

### How do you plan to choose storage providers

Slack

### How do you plan to make deals to your storage providers

Boost client, Lotus client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
Data samples you provided is from https://space.bilibili.com/515848288?spm_id_from=333.337.0.0. What's the relationship between the bilibili channel and the organization? Can you provide relative materials?
The website is recorded by 成都西维数码科技有限公司. Can you explain about that?
Can you explain your data composition and provide sufficient data samples separately? How many copies will you store?
What's the relationship between you and the organization?
Can you provide more detailed information about other storage providers participated in this program, such as you can list SPs you have contacted with at present?
Whether the sps you choose can support data retrieval?

**Comment by Sunnyiscoming** [comment]
Could you send an email to filplus-app-review@fil.org with your official domain in order to confirm your identity? Email name should includes the issue id #1436.

**Comment by simonkim0515** [comment]
## Datacap Request Trigger

#### Total DataCap requested 
> 5PiB

#### Expected weekly DataCap usage rate 
> 300TiB 

#### Client address
> f16xlgzogkkd5qm44uftfprkvh44gu4ruo7dmngca

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Looking at your application i have some questions:
As you are brand new on Github and have no history of past applications it seems to me that applying for 5PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?

Can you show us visible proof of the size of your data and the storage systems you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230337462961356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!

**Comment by cryptowhizzard** [comment]
Thanks

Will you fill out the form?

**Comment by cryptowhizzard** [comment]
Hi @hhhhxiao 

Thanks for the help and the form. Well received.

I take it that you are making preparations and are building the dataset. Good to hear!

Let me know when you have SP's where you want to store the data. I will screen them for you to make sure they have not been involved in FIL+ abuse. You can mail their info to kyc@dcent.nl

Thanks!

**Comment by NDLABS-OFFICE** [comment]
Please explain your current data details, overall data volume, weekly storage volume, etc. and provide relevant evidence

**Comment by NDLABS-OFFICE** [comment]
@hhhhxiao Ok, I'll do the first round of support to help you get started with storage

**Comment by NDLABS-OFFICE** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedhq5bfhln3vmkjx7rv2s6p5g5c7qteynbdco52cozrfwquvpdwto 
#### Address 
> f16xlgzogkkd5qm44uftfprkvh44gu4ruo7dmngca
#### Datacap Allocated
> 150.00TiB
#### Signer Address
> f1yayfsv6whu3rheviucvventj3y6t542xfpb47ei
#### Id
> bedc95da-280c-4249-8b08-41d47191ac7e
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedhq5bfhln3vmkjx7rv2s6p5g5c7qteynbdco52cozrfwquvpdwto

**Comment by newwebgroup** [comment]
Agree with ND and have checked GIthub's history and would be willing to make an endorsement in the first round.
I will keep an eye on the follow-up to check if SP supports the retrieval and to see if the content matches the description.

**Comment by newwebgroup** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecmjusbi6oxaowvh2seoknawv3oxbtwte3m2jt6q6xfljppv2yiqu 
#### Address 
> f16xlgzogkkd5qm44uftfprkvh44gu4ruo7dmngca
#### Datacap Allocated
> 150.00TiB
#### Signer Address
> f1e77zuityhvvw6u2t6tb5qlnsegy2s67qs4lbbbq
#### Id
> bedc95da-280c-4249-8b08-41d47191ac7e
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecmjusbi6oxaowvh2seoknawv3oxbtwte3m2jt6q6xfljppv2yiqu

**Comment by stcouldlisa** [comment]
It seems that the data of one node is relatively concentrated, which does not meet the requirements. Do you have any improvement measures for this?

**Comment by mikezli** [comment]
checker:manualTrigger

**Comment by mikezli** [comment]
Good check, willing to support this round,

**Comment by mikezli** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceabptuvyfqxxjxr4tyfr26dumazyfuwvvcsgrteeqlp2nw7e7x542 
#### Address 
> f16xlgzogkkd5qm44uftfprkvh44gu4ruo7dmngca
#### Datacap Allocated
> 300.00TiB
#### Signer Address
> f1dnb3uz7sylxk6emti3ififcvu3nlufnnsjui6ea
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceabptuvyfqxxjxr4tyfr26dumazyfuwvvcsgrteeqlp2nw7e7x542

**Comment by sxxfuture-official** [comment]
checker:manualTrigger

**Comment by sxxfuture-official** [comment]
@hhhhxiao 
Most of the results displayed by the CID Checker Report are satisfactory, except that the number of replicas of the data is insufficient, and more SPs need to be added to store copies of the data. 
But considering that the project has just gone through the second round, I hope this problem can be solved in the future.

The results of the retrieval test are as follows, deal_id from [https://datacapstats.io/clients/f02060232?page=567](https://datacapstats.io/clients/f02060232?page=567)

![image](https://user-images.githubusercontent.com/113963951/235062933-e3d0f5cc-7056-4d55-9c15-2a629b52d2e2.png)

**Comment by sxxfuture-official** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedlkj7zbvmntgsgbwnc7taw6suozzhyl57wg7yrmukck36ubm3cam 
#### Address 
> f16xlgzogkkd5qm44uftfprkvh44gu4ruo7dmngca
#### Datacap Allocated
> 600.00TiB
#### Signer Address
> f1foiomqlmoshpuxm6aie4xysffqezkjnokgwcecq
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedlkj7zbvmntgsgbwnc7taw6suozzhyl57wg7yrmukck36ubm3cam

**Comment by woshidama323** [comment]
checker:manualTrigger

**Comment by woshidama323** [comment]
![image](https://user-images.githubusercontent.com/11014169/235065638-5fa5bc94-ef5e-488d-869d-4a281d03e037.png)

Hope you will fix this next round

**Comment by woshidama323** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebzgqvryntn4r6k2ufyf26a7vrq6cr6jhxbaxovq5toautqep357y 
#### Address 
> f16xlgzogkkd5qm44uftfprkvh44gu4ruo7dmngca
#### Datacap Allocated
> 600.00TiB
#### Signer Address
> f12tk3adljauwnd3hjbigpfxb7b7gdlj63p6afwtq
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebzgqvryntn4r6k2ufyf26a7vrq6cr6jhxbaxovq5toautqep357y

**Comment by cryptowhizzard** [comment]
Good morning,

It seems your SP's do not support retrieval of data. This is against FIL+ rules and guidelines.

 ./f02060232.sh
Error: retrieval query for miner f02121645 failed: failed to dial 12D3KooWCK6NUYAEYrdpfH1ENc7XiFKX7qQ1RYphgLdWgYsa7Njs:
  * [/ip4/103.141.225.6/tcp/12359] dial tcp4 103.141.225.6:12359: connect: connection refused
  * [/ip4/10.72.88.82/tcp/12359] dial tcp4 0.0.0.0:38749->10.72.88.82:12359: i/o timeout
Error: retrieval query for miner f02121645 failed: failed to dial 12D3KooWCK6NUYAEYrdpfH1ENc7XiFKX7qQ1RYphgLdWgYsa7Njs:
  * [/ip4/103.141.225.6/tcp/12359] dial tcp4 103.141.225.6:12359: connect: connection refused
  * [/ip4/10.72.88.82/tcp/12359] dial tcp4 0.0.0.0:43483->10.72.88.82:12359: i/o timeout
  * 
<img width="1114" alt="Scherm­afbeelding 2023-05-06 om 11 04 45" src="https://user-images.githubusercontent.com/36404435/236614588-672be340-ffe9-496d-a163-dc39c5011496.png">

**Comment by zcfil** [comment]
checker:manualTrigger

**Comment by zcfil** [comment]
The report shows that the data distribution is relatively concentrated. What is the reason for this and how to avoid it in the future?

**Comment by maxvint** [comment]
checker:manualTrigger

**Comment by zcfil** [comment]
![企业微信截图_16833645891375](https://user-images.githubusercontent.com/45065975/236634476-d651fcf5-e435-4414-8570-77994ef996c2.png)

**Comment by zcfil** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebk376wtgg3qzmaegsjkhj7ue3dcmyvq72myykeiermk2vodijglg 
#### Address 
> f16xlgzogkkd5qm44uftfprkvh44gu4ruo7dmngca
#### Datacap Allocated
> 1.17PiB
#### Signer Address
> f1cjzbiy5xd4ehera4wmbz63pd5ku4oo7g52cldga
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebk376wtgg3qzmaegsjkhj7ue3dcmyvq72myykeiermk2vodijglg

**Comment by Joyologist** [comment]
![0254d1e70c4085006ee89c8109e123c](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/115516926/1b4a9145-0423-481a-b1f0-4a1650a26a2a)

**Comment by Joyologist** [comment]
Retrieval looks ok, willing to support this round

**Comment by Joyologist** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceavcynpcdwubmbq6a5kuuwmuj7rs2lhns3csnfevwcw4vcpdkhmhw 
#### Address 
> f16xlgzogkkd5qm44uftfprkvh44gu4ruo7dmngca
#### Datacap Allocated
> 1.17PiB
#### Signer Address
> f1txboxiscdm4f3okffyjmbilmwjtbisrbee72j6q
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceavcynpcdwubmbq6a5kuuwmuj7rs2lhns3csnfevwcw4vcpdkhmhw

**Comment by lyjmry** [comment]
checker:manualTrigger

**Comment by cryptowhizzard** [comment]
![Scherm­afbeelding 2023-08-21 om 14 00 18](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/36404435/61f69b51-7a80-4a01-b825-cd474dd288eb)

Only 3 of your SP's are online at the moment. Why?

**Comment by cryptowhizzard** [comment]
You have only 3 Sp's left , only 42% of your data is retrievable at maximum. :(

Let me know who you consider for replacement. I hope SP's with reputation this time?

**Comment by cryptowhizzard** [comment]
I downloaded the data and made it available here:

http://www.datasetcreators.com/downloadedcarfiles/1436-f02060232-f01261113-50835053-baga6ea4seaqac2kioha5z47g6mwii4dvep3qhzqwrdizmq4siq52qcgoqed2aaq

The data does not match the data applicant indicated he is storing.

![Scherm­afbeelding 2023-09-05 om 14 28 17](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/36404435/f21695ba-28e7-4f9d-9e92-48cfc2a3d111)

**Comment by Sunnyiscoming** [comment]
Hello, @hhhhxiao per the https://github.com/filecoin-project/notary-governance/issues/922 for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

This information will be reviewed by Fil+ Governance team to confirm validity and then the application will be allowed to move forward for additional notary review.

**Comment by Filplus-govteam** [comment]
SP list provided
 f0130556 | Lanhe | CN | no | no
f02051716 | US | no | no
f02040772 | HB | UK | no | no
f02320270 | R1 | US | no | no

**Comment by Filplus-govteam** [comment]
checker:manualTrigger

**Comment by Filplus-govteam** [comment]
SPs taking deals:
130556 | Guangzhou, Guangdong, CNChina Mobile communications corporation | 145.06 TiB | 6.81% | 144.97 TiB | 0.06%
f02226869 | Nanchang, Jiangxi, CNCHINA UNICOM China169 Backbone | 463.34 TiB | 21.74% | 463.34 TiB | 0.00%
f01261113 | Shenzhen, Guangdong, CNCHINANET-BACKBONE | 451.22 TiB | 21.18% | 438.78 TiB | 2.76%
f02059207 | Shenzhen, Guangdong, CNCHINANET-BACKBONE | 126.03 TiB | 5.91% | 126.03 TiB | 0.00%
f01261218 | Shenzhen, Guangdong, CNCHINANET-BACKBONE | 50.28 TiB | 2.36% | 50.28 TiB | 0.00%
f02121645 | Hanoi, Hanoi, VNDREAM POWER TECHNOLOGY LIMITED | 370.69 TiB | 17.40% | 370.69 TiB | 0.00%
f02329561new | Hong Kong, Central and Western, HKDREAM POWER TECHNOLOGY LIMITED | 303.00 TiB | 14.22% | 303.00 TiB | 0.00%
f02051716new | Seattle, Washington, USGTHost | 116.13 TiB | 5.45% | 116.13 TiB | 0.00%
f02040772new | London, England, GBGTHost | 105.06 TiB | 4.93% | 105.06 TiB | 0.00%

SPs don't match list provided. Closing until a clear list of SP entities and distribution is provided
