### ISSUE TITLE
[DataCap Application] Protocol Labs - Filecoin Archive via Perpetual storage smart contract

### ISSUE THREAD

**Issue by jennijuju** [filecoin-project/filecoin-plus-large-datasets#1437]
### Data Owner Name

Filecoin Chain

### Data Owner Country/Region

Canada

### Data Owner Industry

Web3 / Crypto

### Website

https://protocol.ai/

### Social Media

```text
https://twitter.com/Filecoin
```

### Total amount of DataCap being requested

500TiB

### Weekly allocation of DataCap requested

10TiB

### On-chain address for first allocation

TBD

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
[Protocol labs](https://protocol.ai/work/) is an open-source R&D lab, Filecoin project is created by PL.
Lotus & CryptoNetLab are two teams at Protocol Labs that research, design and develop the filecoin protocol.

We started [FilFil project](https://www.notion.so/pl-strflt/FilFil-PeSto-and-Filecoin-Archive-3413707b05b848f6ae5161975aa8f757) that will store archives Filecoin chain messages on Filecoin’s perpetual storage(PeSto) network from genesis and onward.
```

### Is this project associated with other projects/ecosystem stakeholders?

Yes

### If answered yes, what are the other projects/ecosystem stakeholders

```text
Filecoin Foundation, we believe the archival service  shall be governed by FF for public goods.
```

### Describe the data being stored onto Filecoin

```text
Filecoin chain
```

### Where was the data currently stored in this dataset sourced from

Other

### If you answered "Other" in the previous question, enter the details here

filecoin full archival node operators' storage  

### How do you plan to prepare the dataset

lotus

### Please share a sample of the data

```text
devnet example


{
  "Version": 0,
  "To": "t1r4lhrgb2gup6ifgveng7ifapmfsgmbd72ns3dwq",
  "From": "t3vh4uhxybsksxj5ritkq5mo3wdifwdctma3kro4h7yf3xjx7itcbwurveczuvwufxlkinw7bjzv5n2xcjhdzq",
  "Nonce": 2,
  "Value": "100000000000000000000",
  "GasLimit": 2981727,
  "GasFeeCap": "19299170",
  "GasPremium": "101152",
  "Method": 0,
  "Params": null,
  "CID": {
    "/": "bafy2bzaceaeczozmlnsq3a7ikjfudbd6fzvttvsiydrelmc4orkbp2t7bhxxc"
  }
}
{
  "Version": 0,
  "To": "t3wx3bjiwqz2w7jpgkwisxhvhsy6xl6be7wesihcmyptvjue7rolubqitpi6as4ud5ilg5plvb4m7ci5jtgrjq",
  "From": "t3vh4uhxybsksxj5ritkq5mo3wdifwdctma3kro4h7yf3xjx7itcbwurveczuvwufxlkinw7bjzv5n2xcjhdzq",
  "Nonce": 1,
  "Value": "1000000000000000000000",
  "GasLimit": 587210,
  "GasFeeCap": "37529580",
  "GasPremium": "100502",
  "Method": 0,
  "Params": null,
  "CID": {
    "/": "bafy2bzaceabvre2fabdzlg2laeuqonq3dajcbdfu3ijq4327dr7bpibafq4zi"
  }
}
{
  "Version": 0,
  "To": "t01000",
  "From": "t3vh4uhxybsksxj5ritkq5mo3wdifwdctma3kro4h7yf3xjx7itcbwurveczuvwufxlkinw7bjzv5n2xcjhdzq",
  "Nonce": 0,
  "Value": "0",
  "GasLimit": 3645720,
  "GasFeeCap": "1054396240",
  "GasPremium": "99365",
  "Method": 4,
  "Params": "gVgmACQIARIgLuy2nusFckXgzH5oIdhNhAcbE56j2vQdPYkWI7t7bu8=",
  "CID": {
    "/": "bafy2bzacedjzl3xzaoqxcwuj6gz66xwvl7qlpp77ki6z5b4ixoerkrr72zjjk"
  }
}
```
```


### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### If you chose not to confirm, what was the reason

_No response_

### What is the expected retrieval frequency for this data

Daily

### For how long do you plan to keep this dataset stored on Filecoin

Permanently

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, Africa, North America, South America, Europe, Australia (continent), Antarctica

### How will you be distributing your data to storage providers

Others

### How do you plan to choose storage providers

Others

### If you answered "Others" in the previous question, what is the tool or platform you plan to use

SPs will get the data from their lotus chain datastore directly

### If you already have a list of storage providers to work with, fill out their names and provider IDs below

```text
any SP may claim the data bounty from the smart contract
```

### How do you plan to make deals to your storage providers

Others/custom tool

### If you answered "Others/custom tool" in the previous question, enter the details here

SP can claim the data bounty from the smart contract and use lotus or boost to publish the deal 

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by jennijuju** [comment]
We likely will start running the service on mainnet in mid-late q1/2023. However, given this might be one of the first applications that will be applying datacap to a smart contract,  id like to get the datacap application started early so that the governance process can go through in time.

**Comment by jennijuju** [comment]
@galen-mcandrew @raghavrmadya  - the address for the contract will be `f4` or `f2` later on, what's the path for adding that?

**Comment by momack2** [comment]
@dkkapur we need this fixed ASAP so that smart contracts can start applying for FIL+ datacap ex for DataDAOs that want to steward and preserve public-good datasets.
