### ISSUE TITLE
[DataCap Application] <EMA> - <Resource Management Storage>

### ISSUE THREAD

**Issue by jihan233** [filecoin-project/filecoin-plus-large-datasets#1439]
### Data Owner Name

E Management Agency LLC

### Data Owner Country/Region

US

### Data Owner Industry

Arts & Recreation

### Website

https://emanagementagency.com/

### Social Media

```text
yini@emanagementagency.com
```

### Total amount of DataCap being requested

2PiB

### Weekly allocation of DataCap requested

100TiB

### On-chain address for first allocation

f1l4meydrcyme2yjcozs5q4ez6n5krl7dy4uwjtyq

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
EMA, a data-intelligent onlyfans management agency, has partnered with Creators to provide them with a full service package, including a complete onboarding process, tools, a dedicated team and dedicated management supervision to achieve their goals.
We are the same strategist, industry management expert and consulting firm, all three in one. We very much need a data storage platform, create a data storage set, store the data of each member, convenient for us to find and add storage.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### If answered yes, what are the other projects/ecosystem stakeholders

```text
Having no other projects/ecosystem stakeholders
```

### Describe the data being stored onto Filecoin

```text
Our data source has two parts;
Part 1: The main storage company's management platform logs,
The second part; Mainly store members' growth videos and account promotion logs
There are other bits of data that need to be stored
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### How do you plan to prepare the dataset

IPFS, lotus, singularity, graphsplit

### Please share a sample of the data

```text
https://emanagementagency.com/onlyfans-management-case-study-s/
https://emanagementagency.com/onlyfans-news-tips/
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Daily

### For how long do you plan to keep this dataset stored on Filecoin

Permanently

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, Africa, North America, South America, Europe, Australia (continent), Antarctica

### How will you be distributing your data to storage providers

Cloud storage (i.e. S3), HTTP or FTP server, IPFS

### How do you plan to choose storage providers

Slack, Filmine, Big data exchange, Partners

### If you already have a list of storage providers to work with, fill out their names and provider IDs below

```text
There are currently no cooperating storage providers
```

### How do you plan to make deals to your storage providers

Boost client, Lotus client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
Can you explain your data composition and provide sufficient data samples separately? How many copies will you store?
What's the relationship between you and the organization?

**Comment by jihan233** [comment]
Data Owner Name
E Management Agency LLC
I am an operation and maintenance technician in the company

Our data are mainly management data, growth videos of cooperative artists and account promotion logs. We have our own platform to facilitate communication with customers until the final transaction, which generates a large number of data sources

https://emanagementagency.com/wp-content/uploads/2021/10/Urez_iphone-w-screenshot-1066x2048-1.png
https://emanagementagency-com.translate.goog/?_x_tr_sl=en&_x_tr_tl=us_EN&_x_tr_hl=zh-CN&_x_tr_pto=sc

I need to store important parts and then make a plan

**Comment by Sunnyiscoming** [comment]
More data samples needed.

**Comment by jihan233** [comment]
链接: https://pan.baidu.com/s/1N9lmnWWuIc0mytMeVLTVPQ?pwd=4p6p 提取码: 4p6p 
https://connect.livechatinc.com/api/v1/script/f14e48cc-53fc-4844-b933-2fcfea78e601
链接: https://pan.baidu.com/s/1PRUZl_HLeQX98iIwmInLIA?pwd=usy9 提取码: usy9

**Comment by herrehesse** [comment]
Dear Applicant,

Due to the increased amount of erroneous/wrong Filecoin+ data recently, on behalf of the entire community, we feel compelled to go deeper into datacap requests. Hereby to ensure that the overall value of the Filecoin network and Filecoin+ program increases and is not abused.

Please answer the questions below as comprehensively as possible.

**Customer data**

- Could you demonstrate exactly how and to what extent customer contact occurred? 

We expect that for the onboarding of customers with the scale of an LDN there would have been at least multiple email and perhaps several chat conversations preceding it. A single email with an agreement does not qualify here.

- Did the customer specify the amount of data involved in this relevant correspondence?

- Why does the customer in question want to use the Filecoin+ program? 

_Should this only be soley for acquiring datacap this is of course **out of the question**. The customer must have a legitimate reason for wanting to use the Filecoin+ program which is intended as a program to store useful and public datasets on the network._ 

- Why is the customer data considered Filecoin+ eligible?

_(As an intermediate solution Filecoin offers the FIL-E program or the glif.io website for business datasets that do not meet the requirements for a Filecoin+ dataset)_


**Files and Processing**

- Could you please demonstrate to us how you envision processing and transporting the customer data in question to any location for preparation?
- Would you demonstrate to us that the customer, the preparer and the intended storage providers all have adequate bandwidth to process the set with its corresponding size?
- Would you tell us how the data set preparer takes into account the prevention of duplicates in order to prevent data cap abuse?


Hopefully you understand the caution the overall community has for onboarding the wrong data. We understand the increased need for Filecoin+, however, we must not allow the program to be misused. Everything depends on a valuable and useful network, let's do our best to make this happen. Together.

**Comment by jihan233** [comment]
Dear notary，
I quite understand the changes that have been made to ensure that the overall value of the Filecoin network and Filecoin+ project increases and is not abused due to the recent increase in the amount of incorrect/incorrect Filecoin+ data. We will also actively cooperate with community, and strictly complete.

Could you demonstrate exactly how and to what extent customer contact occurred?
We have a Dedicated account manager, Media assistants, social media management of existing accounts, daily reddit promotions, personal messaging management, paid promotion network and GG, PPV + Tip sales and upselling management
There are regular websites, and customers can find us according to the chat portal of the website. We have customer service staff specially for this area, so as to further explore the potential of business cooperation.

Did the customer specify the amount of data involved in this relevant correspondence?
Yes, under the premise of ensuring the security of private data, we upload and store part of our data and create multiple copies.

Why does the customer in question want to use the Filecoin+ program?
Filecoin+ program was chosen, be due toinnovative community platform, and storage activity and standardized community management. We believe in Filecoin growth potential.

Why is the customer data considered Filecoin+ eligible?
Most of our data will be stored directly on Filecoin, the customer data involved will be encrypted, and we want to create multiple copies to prevent data clutter and loss

Could you please demonstrate to us how you envision processing and transporting the customer data in question to any location for preparation?
First of all, our data is currently stored on the hard disk of the server and will be backed up to mobile HDD, cloud disk and local on a regular basis. We will evaluate the uploading of data and upload it under the premise of reducing cost and time

Would you demonstrate to us that the customer, the preparer and the intended storage providers all have adequate bandwidth to process the set with its corresponding size?
We have servers in both the machine room and the cloud. The bandwidth of the machine room is 8G, and the bandwidth of the cloud is 4G, both of which are public IP. We are currently contacting multiple sps, and the premise of contacting these sps is to choose according to the storage of sps and the region where our server is located. Reduce network impact.

Would you tell us how the data set preparer takes into account the prevention of duplicates in order to prevent data cap abuse?
First of all, our data is not duplicated, and there are enough data sources. We have also made a plan for data uploading. Because our data has multiple file directories, we will carry out data uploading one after another and make corresponding records. We also conduct data screening to ensure the uniqueness of data upload and avoid data upload duplication

These are my answers to the above questions.Please look it up and check，Thanks！

**Comment by herrehesse** [comment]
Dear applicant @jihan233,

Your data is business data management for adult content. Not suitable for the Filecoin+ program.

<img width="1728" alt="Screenshot 2023-01-09 at 09 39 52" src="https://user-images.githubusercontent.com/70132857/211268307-64d2e275-ecd6-4ae0-b928-02f5a8a88094.png">

I would recommend you to use regular storage deals and pay the storage provider you want to make use of per GiB.
If you want to fully encrypt the data, you might be able to work with FIL-E. But I am not sure they allow adult content.

@raghavrmadya @Sunnyiscoming @galen-mcandrew

**Comment by jihan233** [comment]
Dear @herrehesse 
Thank you for your reply, and I would like to try again. There are many types of our data, which in my opinion are the storage of data files, and filecoin just happens to be the storage project, and the data we upload is also packaged. I believe that filecoin storage is also diversified, which can accommodate many impossibilities. Please correct me if anything is wrong. Thank you very much

**Comment by herrehesse** [comment]
@jihan233 You are completely correct here! We both believe Filecoin is an awesome way to store your business data. The only issue here is that your application does not fit the Filecoin+ program rules, therefore I would like to help you onboard your data trough one of the following ways:

1. Application at FIL-E
2. Regular storage deals (1/100th price of AWS)

This way you can make use of all the awesome futures that Filecoin has to offer. Let me know if you need assistance.

To clarify, you are doing nothing wrong and we love to onboard you! Just not through the program of Filecoin+.

**Comment by simonkim0515** [comment]
## Datacap Request Trigger

#### Total DataCap requested 
> 2PiB

#### Expected weekly DataCap usage rate 
> 100TiB 

#### Client address
> f1l4meydrcyme2yjcozs5q4ez6n5krl7dy4uwjtyq

**Comment by jihan233** [comment]
亲爱的公证人，
感谢您的回复，对你的提问我将做出以下回答，还请查阅
对于filecoin我确实是新手，对部分的操作流程可能还不是很熟悉，但是我相信filecoin社区的人会帮助我进行更深入的了解，我也正在积极的学习当中
![image](https://user-images.githubusercontent.com/77474253/215679596-6f442465-70e3-4ede-bbe6-6f8125b4c91c.png)
![image](https://user-images.githubusercontent.com/77474253/215941760-e14a9e7a-05ab-41a1-843b-ee426f2133de.png)

**Comment by lvschouwen** [comment]
“the customer data involved will be encrypted”
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1439#issuecomment-1375073487

This data should not be on FIL+ but maybe on FIL-E (tagging @Kevin-FF-USA).

**Comment by lvschouwen** [comment]
Should have been @kevzak not @Kevin-FF-USA (Sorry)
