### ISSUE TITLE
[DataCap Application] Telnyx - Nanopore Reference Human Genome

### ISSUE THREAD

**Issue by bmcnabb25** [filecoin-project/filecoin-plus-large-datasets#1441]
### Data Owner Name

Telnyx

### Data Owner Country/Region

United States

### Data Owner Industry

Information, Media & Telecommunications

### Website

https://telnyx.com/

### Social Media

```text
https://www.linkedin.com/company/telnyx/mycompany/verification/
https://twitter.com/telnyx
https://www.facebook.com/Telnyx/
```

### Total amount of DataCap being requested

300TiB

### Weekly allocation of DataCap requested

50TiB

### On-chain address for first allocation

f1m2trtgqqcfvsurukeiaq25cxsrycqphi2i5nrui

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Telnyx is a global Telecom company founded back in 2009. However, we are now aiming higher with the vision to democratize infrastructure, enabling and accelerating new economies by making Edge Connectivity easily accessibly. We believe that Filecoin will be an integral part of achieving this vision.

We started participating in the Filecoin ecosystem earlier this year, after attending the ESPA conference in February 2022.

We currently have 6 miners located in cities across the US (f01847751, f01872811, f01882569, f01889910, f01909616, f01917539), with 2 more miners expected to be up and running in the near future

We are FIL+ notaries (https://github.com/filecoin-project/notary-governance/issues/470) and are part of the #fil-plus-enterprise-wg

We just launched a new S3 Compatible API that stores and retrieves data from Filecoin. Currently only stores unverified data on our own miners, but hoping to expand its capabilities to include FIL+ data and other miners in the future. (https://telnyx.com/products/storage)

We are hoping to continue growing our involvement in the network and community over the coming weeks, months, and years.
```

### Is this project associated with other projects/ecosystem stakeholders?

Yes

### If answered yes, what are the other projects/ecosystem stakeholders

```text
Tinfra
```

### Describe the data being stored onto Filecoin

```text
From this page: https://aws.amazon.com/marketplace/pp/prodview-wc5a46r7xvxqi?sr=0-49&ref_=beagle&applicationId=AWSMPContessa

Description: This dataset includes the sequencing and assembly of a reference standard human genome (GM12878) using the MinION nanopore sequencing instrument with the R9.4 1D chemistry.

Size of dataset: 51.2 TiB (issue the command `aws s3 ls --no-sign-request s3://nanopore-human-wgs/ --summarize --human-readable` in the CLI to verify for yourself!)

We plan on making 5 copies of the dataset and distributing it globally by using BigDateExchange.
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### How do you plan to prepare the dataset

lotus

### Please share a sample of the data

```text
Source: https://aws.amazon.com/marketplace/pp/prodview-wc5a46r7xvxqi?sr=0-49&ref_=beagle&applicationId=AWSMPContessa

All data is open and publicly available. Instructions on how to access the data for a sample are listed under the resources page. 

Or you can go directly to this link https://nanopore-human-wgs.s3.amazonaws.com/index.html
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Sporadic

### For how long do you plan to keep this dataset stored on Filecoin

1 to 1.5 years

### In which geographies do you plan on making storage deals

Asia other than Greater China, North America, Europe, Australia (continent)

### How will you be distributing your data to storage providers

Cloud storage (i.e. S3)

### How do you plan to choose storage providers

Big data exchange

### How do you plan to make deals to your storage providers

Boost client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
Will you only store data on your own nodes?

**Comment by bmcnabb25** [comment]
Will not be storing any copies on our own nodes.

Planning on listing on BDE once approved, no SP's identified at the moment

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 300TiB

**Expected weekly DataCap usage rate**

> 50TiB

**Client address**

> f1m2trtgqqcfvsurukeiaq25cxsrycqphi2i5nrui

**Comment by cryptowhizzard** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebb7agmmcwzfrbesuj6q2mqbgnqnizi36ebungpz4q7ngdqjdkiuk 
#### Address 
> f1m2trtgqqcfvsurukeiaq25cxsrycqphi2i5nrui
#### Datacap Allocated
> 15.00TiB
#### Signer Address
> f1krmypm4uoxxf3g7okrwtrahlmpcph3y7rbqqgfa
#### Id
> a3335e0f-6a5e-459f-9732-9c83f636aa86
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebb7agmmcwzfrbesuj6q2mqbgnqnizi36ebungpz4q7ngdqjdkiuk

**Comment by bmcnabb25** [comment]
@galen-mcandrew you can close this datacap request
