### ISSUE TITLE
[DataCap Application] <Venus Team > - <DealAccelerator V2>

### ISSUE THREAD

**Issue by Joss-Hua** [filecoin-project/filecoin-plus-large-datasets#1444]
### Data Owner Name

Venus team

### Data Owner Country/Region

Hong Kong

### Data Owner Industry

Life Science / Healthcare

### Website

https://venushub.io

### Social Media

```text
https://twitter.com/venus_filecoin
https://www.youtube.com/@venus_filecoin
http://filecoinproject.slack.com/archives/CEHHJ
http://filecoinvenus.medium.com
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

200TiB

### On-chain address for first allocation

f1ymfz2mqdrkrdpjmrwh4qaqtuknfpsq3lp3r3auq

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
The team: Venus team

Venus team leads the development and practice of Filecoin Venus, established in 2020, Shanghai, China. Now we have decades of members from all over the world focusing on code dev and community.

Through the core dev and ecological activities and programs, we hope (and already) to have more storage service providers, users, and enthusiasts join Filecoin or provide more contributions after joining Filecoin.


The project: Venus Deal Accelerator (https://venushub.io/accelerator/)

Venus is committed to offer a fully functional deal-making experience for both storage clients and storage providers on the scale. As the Filecoin network grows and the community strives towards a more storage deal weighted growth than committed capacity growth, the Venus community takes on the challenge to help shape this vision with the Venus Deal Accelerator program.

The goal of the Venus Deal Accelerator program is to distribute as much storage deals as it can to the broader storage provider community with focuses on seamlessly bridging the sealing experience that storage providers are already familiar with to the Filecoin deal taking experience. Venus Deal Accelerator program will be responsible for applying large datacap with approved open datasets from fil-plus program and distribute storage deals to its participants running Venus storage systems.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
The data being stored onto Filecoin is from publicly available datasets in various academic disciplines, including humanity, nature science, formal science, medical science, life science, etc.
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### How do you plan to prepare the dataset

graphsplit

### Please share a sample of the data

```text
https://registry.opendata.aws/pacific-sound/
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Monthly

### For how long do you plan to keep this dataset stored on Filecoin

1 to 1.5 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, Europe

### How will you be distributing your data to storage providers

Cloud storage (i.e. S3), HTTP or FTP server, Shipping hard drives

### How do you plan to choose storage providers

Slack, Big data exchange, Others

### If you answered "Others" in the previous question, what is the tool or platform you plan to use

We define VenusHub as a platform for community projects. The Deal Accelerator mentioned here is one of them. The Deal Accelerator is aimed at the storage providers of real data storage. We complete the SP screening through they' application and screening rules, and they come from the Filecoin community, so they have no interest relationship.

### If you already have a list of storage providers to work with, fill out their names and provider IDs below

```text
Such as f01934215, f01045812, f01285787, f01874063, and more.

We will focus on more new SPs (miners) and hope that more miners will real data provide storage for the client.
```

### How do you plan to make deals to your storage providers

Others/custom tool

### If you answered "Others/custom tool" in the previous question, enter the details here

venus-market. By the way, the support of venus-market for real data storage is very mature.

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/345
Datacap to be granted to reach the total amount requested by the client (5 PiB)
2.16PiB
Why you submit another application about the same dataset? Can you explain about that?

https://filplus.d.interplanetary.one/clients/f01379794/breakdown
Whether the sps you choose can support data retrieval?
Can you provide some retrieval samples?

**Comment by Joss-Hua** [comment]
Because someone has been downloading my data through my data sample link in the last 24 hours and it is still in progress, I have updated the sample link now.

**Comment by Joss-Hua** [comment]
Hi, @Sunnyiscoming @simonkim0515  Please check again. Any suggestions or questions?

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 200TiB

**Client address**

>f1ymfz2mqdrkrdpjmrwh4qaqtuknfpsq3lp3r3auq

**Comment by kernelogic** [comment]
Long time community participant, willing to support.

**Comment by kernelogic** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceagvugebhn4nrp4ryp2oeyrhpp3awktlyoik2xbswwk5u3mfdvxjy 
#### Address 
> f1ymfz2mqdrkrdpjmrwh4qaqtuknfpsq3lp3r3auq
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### Id
> c4151066-abd3-4b95-81af-1761a86361d5
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceagvugebhn4nrp4ryp2oeyrhpp3awktlyoik2xbswwk5u3mfdvxjy

**Comment by cryptowhizzard** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedfax3dp6madyw672lqrfb2nbqhpsmsaqa3xtd3qr2gsnysab2r5e 
#### Address 
> f1ymfz2mqdrkrdpjmrwh4qaqtuknfpsq3lp3r3auq
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1krmypm4uoxxf3g7okrwtrahlmpcph3y7rbqqgfa
#### Id
> c4151066-abd3-4b95-81af-1761a86361d5
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedfax3dp6madyw672lqrfb2nbqhpsmsaqa3xtd3qr2gsnysab2r5e

**Comment by kernelogic** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacealp7motsxut5lycxksw45kteu6zkrg25txyjnv33wxeui6upkp5c 
#### Address 
> f1ymfz2mqdrkrdpjmrwh4qaqtuknfpsq3lp3r3auq
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### Id
> c4151066-abd3-4b95-81af-1761a86361d5
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacealp7motsxut5lycxksw45kteu6zkrg25txyjnv33wxeui6upkp5c

**Comment by stcouldlisa** [comment]
I researched the project well enough ，it feels good，

**Comment by stcouldlisa** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebvvkehiym2e5dmoptu7vuia6vyoyqz5agkkixnjnejgfqrunuqyo 
#### Address 
> f1ymfz2mqdrkrdpjmrwh4qaqtuknfpsq3lp3r3auq
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1jvvltduw35u6inn5tr4nfualyd42bh3vjtylgci
#### Id
> c4151066-abd3-4b95-81af-1761a86361d5
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebvvkehiym2e5dmoptu7vuia6vyoyqz5agkkixnjnejgfqrunuqyo

**Comment by BDEio** [comment]
@Joss-Hua Hi! Congratulations on your DataCap approval！
BDE is a trusted deals auction house helping you to get paid storing your data with reliable storage providers. If you need any help, please get in touch.

**Comment by Joss-Hua** [comment]
checker:manualTrigger

**Comment by kernelogic** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedaes4gexhxodewsk4djl6zp2w2m2ludzahjs7ebeed3mufkgbvc6 
#### Address 
> f1ymfz2mqdrkrdpjmrwh4qaqtuknfpsq3lp3r3auq
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### Id
> f306e47c-69ac-4980-b2d6-4844f04579d3
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedaes4gexhxodewsk4djl6zp2w2m2ludzahjs7ebeed3mufkgbvc6

**Comment by xingjitansuo** [comment]
checker:manualTrigger

**Comment by xiaoyuaiheshui** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceclgiaavn64766eobu6dkgtab343rqtd4lo4yy6zu6pl2ytcv42ra 
#### Address 
> f1ymfz2mqdrkrdpjmrwh4qaqtuknfpsq3lp3r3auq
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f122qmy25wdtt5mxd77kndiq7z5x2n3iwiuz2wdsa
#### Id
> f306e47c-69ac-4980-b2d6-4844f04579d3
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceclgiaavn64766eobu6dkgtab343rqtd4lo4yy6zu6pl2ytcv42ra

**Comment by xingjitansuo** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecm4zo2ajli6sgwfcpvpyke4l6sv3jowhtyvb6n5b3wkajjtdzs6i 
#### Address 
> f1ymfz2mqdrkrdpjmrwh4qaqtuknfpsq3lp3r3auq
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1a2lia2cwwekeubwo4nppt4v4vebxs2frozarz3q
#### Id
> 91ee5b3b-5d77-4765-9ad7-23b405cc55b8
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecm4zo2ajli6sgwfcpvpyke4l6sv3jowhtyvb6n5b3wkajjtdzs6i

**Comment by Meibuy** [comment]
checker:manualTrigger

**Comment by s0nik42** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaz4sfkpba3x36n2vslw4ph7mtnvqdxv7kluomwl25qx626mk5y2o 
#### Address 
> f1ymfz2mqdrkrdpjmrwh4qaqtuknfpsq3lp3r3auq
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1wxhnytjmklj2czezaqcfl7eb4nkgmaxysnegwii
#### Id
> 91ee5b3b-5d77-4765-9ad7-23b405cc55b8
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaz4sfkpba3x36n2vslw4ph7mtnvqdxv7kluomwl25qx626mk5y2o

**Comment by NDLABS-OFFICE** [comment]
checker:manualTrigger

**Comment by Joss-Hua** [comment]
This LDN inherits the report of #345. If the notaries, the governance team or the community members have questions about this, please move to [#345](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/345#issuecomment-1377458238) to check the historical information, and also welcome to contact me, hoping not to misunderstand. Peace and love.

**Comment by kernelogic** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedtyyy3k5jfzwis567chg6gdbcw6pleypeiar4tmq6ov4gaetwrmq 
#### Address 
> f1ymfz2mqdrkrdpjmrwh4qaqtuknfpsq3lp3r3auq
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### Id
> b7efe5a9-f8e5-4180-a803-fc4e43755b10
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedtyyy3k5jfzwis567chg6gdbcw6pleypeiar4tmq6ov4gaetwrmq

**Comment by flyworker** [comment]
would like to support the community data alocation

**Comment by flyworker** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecq7lekdk7qu5s5wanq36yaexcmou7ieiol33imivrtlcozqwmfhk 
#### Address 
> f1ymfz2mqdrkrdpjmrwh4qaqtuknfpsq3lp3r3auq
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1hlubjsdkv4wmsdadihloxgwrz3j3ernf6i3cbpy
#### Id
> b7efe5a9-f8e5-4180-a803-fc4e43755b10
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecq7lekdk7qu5s5wanq36yaexcmou7ieiol33imivrtlcozqwmfhk

**Comment by NDLABS-OFFICE** [comment]
<img width="631" alt="image" src="https://user-images.githubusercontent.com/104019147/218385431-b98618f4-0b97-4eab-bb62-b337150bd07d.png">
A random sample of data was retrieved and the test was successful.

**Comment by 1ane-1** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec3vjuri3lvzga5uwsmzuwcef34m7u3b3zfpnwnrzj4cint4pgl5i 
#### Address 
> f1ymfz2mqdrkrdpjmrwh4qaqtuknfpsq3lp3r3auq
#### Datacap Allocated
> 1.56PiB
#### Signer Address
> f1mdk7s2vntzm6hu35yuo6vjubtrpfnb2awhgvrri
#### Id
> 77ea1ce2-6147-4537-8708-babf56ce4449
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec3vjuri3lvzga5uwsmzuwcef34m7u3b3zfpnwnrzj4cint4pgl5i

**Comment by Joss-Hua** [comment]
thank you all for your support.
![image](https://user-images.githubusercontent.com/75723122/224870407-b288f79d-9ec1-4a3d-9850-a43536812378.png)
and looking forward to the final signature.

**Comment by laurarenpanda** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceblthvgveqa2pk3sa6rcskcwkzodao3gohjq26rapzfc23e7f6vtu 
#### Address 
> f1ymfz2mqdrkrdpjmrwh4qaqtuknfpsq3lp3r3auq
#### Datacap Allocated
> 1.56PiB
#### Signer Address
> f1bp3tzp536edm7dodldceekzbsx7zcy7hdfg6uzq
#### Id
> 806385d9-f04e-451e-8c0b-729463d26f05
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceblthvgveqa2pk3sa6rcskcwkzodao3gohjq26rapzfc23e7f6vtu

**Comment by laurarenpanda** [comment]
Wiling to support this round!

**Comment by kernelogic** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecjjr7d4paf6mcvma4rol3rj4tthv3crcsagzu32eos4fauijylae 
#### Address 
> f1ymfz2mqdrkrdpjmrwh4qaqtuknfpsq3lp3r3auq
#### Datacap Allocated
> 1.56PiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### Id
> 806385d9-f04e-451e-8c0b-729463d26f05
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecjjr7d4paf6mcvma4rol3rj4tthv3crcsagzu32eos4fauijylae

**Comment by sxxfuture-official** [comment]
> This LDN inherits the report of https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/345. If the notaries, the governance team or the community members have questions about this, please move to https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/345#issuecomment-1377458238 to check the historical information, and also welcome to contact me, hoping not to misunderstand. Peace and love.

Most of the problems can be explained based on the appeal notes and I will support this round. But please follow up to solve the problem of unknown IP and duplication.

**Comment by sxxfuture-official** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaws5kcwk2i3uvnsbg273iblk6jsjckuilqx2hcja7sgfgrczbmyg 
#### Address 
> f1ymfz2mqdrkrdpjmrwh4qaqtuknfpsq3lp3r3auq
#### Datacap Allocated
> 425.11TiB
#### Signer Address
> f1foiomqlmoshpuxm6aie4xysffqezkjnokgwcecq
#### Id
> 3e82f4c4-4109-4141-8b01-2a10c105100b
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaws5kcwk2i3uvnsbg273iblk6jsjckuilqx2hcja7sgfgrczbmyg

**Comment by kernelogic** [comment]
Bot result looks good. Venus team will continue have my support.

**Comment by xingjitansuo** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebkpmyvaovbvt5efqf4ot34so2enhao3zj5boywhziehjovuawqku 
#### Address 
> f1ymfz2mqdrkrdpjmrwh4qaqtuknfpsq3lp3r3auq
#### Datacap Allocated
> 425.11TiB
#### Signer Address
> f1a2lia2cwwekeubwo4nppt4v4vebxs2frozarz3q
#### Id
> 3e82f4c4-4109-4141-8b01-2a10c105100b
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebkpmyvaovbvt5efqf4ot34so2enhao3zj5boywhziehjovuawqku

**Comment by Joss-Hua** [comment]
DD

**Comment by kevzak** [comment]
checker:manualTrigger

**Comment by data-programs** [comment]
<img width="32" alt="KYC" Verified src="https://stable.filplus.storage/images/filplus-kyc-verified-badge.png"/>

This user’s identity has been verified through [filplus.storage](https://filplus.storage)

**Comment by Sunnyiscoming** [comment]
Close for total datacap reached.
