### ISSUE TITLE
[DataCap Application] dropcool Slingshot Restore Program

### ISSUE THREAD

**Issue by dropcool** [filecoin-project/filecoin-plus-large-datasets#145]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: dropcool - Slingshot Restore
- Website / Social Media:https://github.com/DropCool
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 1PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 500 TiB
- On-chain address for first allocation: f3rwypb3nhyzkslf6eb2qoiaqdwvaedcawxiav4hmhi4cp4w7ptjua42knqoddbl5uabcrtzgq7jajvjroz54a

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
1. Acting as clients - we have been participating Slingshot competition since 2.3,2.5
2. Acting as small Miner
```

What is the primary source of funding for this project?
```
Own money
```

What other projects/ecosystem stakeholders is this project associated with?
```
Slingshot restore program
https://filecoinproject.slack.com/archives/C01AK1J7TF1/p1639607995023000
```

## Use-case details

Describe the data being stored onto Filecoin
```
Those will be the dataset assigned by Protocol Lab as part of the repair and recovery effort for lost deals due to storage outages.
```

Where was the data in this dataset sourced from?
```
Those are public dataset that was used in previous Slingshot rounds.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
The dataset will be from one of those in this table. The actual content will be known once Protocol Lab has the assignment.
https://github.com/filecoin-project/slingshot/blob/master/datasets.md
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
This is confirmed as the Protocol Lab will only assign the deals to qualified storage providers and the data will not be compressed or encrypted.
```

What is the expected retrieval frequency for this data?
```
A few times per year depending on the roadmap of Slingshot competition and following applications.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
500 to 540 days.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Mainly in Hong Kong, China
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
The deal will be made offline only. There will be 5 assigned storage providers according to Slingshot restore program.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
Protocol Lab will assign storage provider for this project. 5 storage providers will be assigned for each project.
```

How will you be distributing deals across storage providers?
```
Every storage provider will have same amount of deals to accept and seal.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes. I am familiar with the deal making process. It will start once the Slingshot restore program starts.
```

**Comment by galen-mcandrew** [comment]
Minor edit to application title and parent comment, for distinction and clarity

**Comment by galen-mcandrew** [comment]
## Multisig Notary requested
#### Total DataCap requested 
> 1PiB
#### Expected weekly DataCap usage rate 
> 500TiB

**Comment by flyworker** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec2tqncln2uhsrsvrbdgfvrozc7nldab6och53sewhlovsu5dnqdw 
#### Address 
> f3rwypb3nhyzkslf6eb2qoiaqdwvaedcawxiav4hmhi4cp4w7ptjua42knqoddbl5uabcrtzgq7jajvjroz54a
#### Datacap Allocated
> 51TiB
#### Signer Address
> f1hlubjsdkv4wmsdadihloxgwrz3j3ernf6i3cbpy
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec2tqncln2uhsrsvrbdgfvrozc7nldab6och53sewhlovsu5dnqdw

**Comment by neogeweb3** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceatft5h23ofi2zwxeyyd5tvqa5skm3dtmorjsi6pdlx3t4fpe4t2w 
#### Address 
> f3rwypb3nhyzkslf6eb2qoiaqdwvaedcawxiav4hmhi4cp4w7ptjua42knqoddbl5uabcrtzgq7jajvjroz54a
#### Datacap Allocated
> 51TiB
#### Signer Address
> f13k5zr6ovc2gjmg3lvd43ladbydhovpylcvbflpa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceatft5h23ofi2zwxeyyd5tvqa5skm3dtmorjsi6pdlx3t4fpe4t2w

**Comment by DropCool** [comment]
@neogeweb3 @galen-mcandrew @flyworker @dkkapur  I am sorry to tell you. Just now, the company leaders decided not to participate in Slingshot Repair program. but I have applied for some datacap, and the company leaders think that in order to avoid being wasted, it will be used to slingshot 2.7 and later phases.

**Comment by jamerduhgamer** [comment]
Hi @dropcool, I don't think you should be applying for datacap in this application for other programs. You should be submitting new LDNs for future programs as needed.

Also, this ticket has been idle since December 23, 2021. Can we close this one out?

**Comment by flyworker** [comment]
I agree it should be closed.

**Comment by dannyob** [comment]
@galen-mcandrew @raghavrmadya can we close this one out?

**Comment by IreneYoung** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecqqzmuwwwp5tmycqcwrbgut3obztja3paisg3so3wy2avjlup6am 
#### Address 
> f3rwypb3nhyzkslf6eb2qoiaqdwvaedcawxiav4hmhi4cp4w7ptjua42knqoddbl5uabcrtzgq7jajvjroz54a
#### Datacap Allocated
> 102.39TiB
#### Signer Address
> f1d4gmpqz3execjj2wvrxuuhvbms5mzh7t7yqrviq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecqqzmuwwwp5tmycqcwrbgut3obztja3paisg3so3wy2avjlup6am

**Comment by flyworker** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebxuhoa74dxoamiiruvyw6l6l6ytz7vxn7mpdjqgtfqugbgc5uo46 
#### Address 
> f3rwypb3nhyzkslf6eb2qoiaqdwvaedcawxiav4hmhi4cp4w7ptjua42knqoddbl5uabcrtzgq7jajvjroz54a
#### Datacap Allocated
> 102.39TiB
#### Signer Address
> f1hlubjsdkv4wmsdadihloxgwrz3j3ernf6i3cbpy
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebxuhoa74dxoamiiruvyw6l6l6ytz7vxn7mpdjqgtfqugbgc5uo46

**Comment by filplus-checker** [comment]
## DataCap and CID Checker Report[^1]
 - Organization: `dropcool - Slingshot Restore`
 - Client: `f3rwypb3nhyzkslf6eb2qoiaqdwvaedcawxiav4hmhi4cp4w7ptjua42knqoddbl5uabcrtzgq7jajvjroz54a`
### Storage Provider Distribution
The below table shows the distribution of storage providers that have stored data for this client.

If this is the first time a provider takes verified deal, it will be marked as `new`.

For most of the datacap application, below restrictions should apply.
 - Storage provider should not exceed 25% of total datacap.
 - Storage provider should not be storing duplicate data for more than 20%.
 - Storage provider should have published its public IP address.
 - All storage providers should be located in different regions.

⚠️ [f01901773](https://filfox.info/en/address/f01901773) has sealed 63.15% of total datacap.

⚠️ [f01878201](https://filfox.info/en/address/f01878201) has sealed 33.35% of total datacap.

⚠️ 74.91% of total deal sealed by [f01878201](https://filfox.info/en/address/f01878201) are duplicate data.

| Provider                                              |                           Location | Total Deals Sealed | Percentage | Unique Data | Duplicate Deals |
| :---------------------------------------------------- | ---------------------------------: | -----------------: | ---------: | ----------: | --------------: |
| [f01901773](https://filfox.info/en/address/f01901773) | Hong Kong, Central and Western, HK |         100.00 TiB |     63.15% |   93.53 TiB |           6.47% |
| [f01878201](https://filfox.info/en/address/f01878201) |             Hangzhou, Zhejiang, CN |          52.81 TiB |     33.35% |   13.25 TiB |          74.91% |
| [f03624](https://filfox.info/en/address/f03624)       |              Nürnberg, Bavaria, DE |           5.00 TiB |      3.16% |    5.00 TiB |           0.00% |
| [f01862564](https://filfox.info/en/address/f01862564) |                 Xi’an, Shaanxi, CN |         512.00 GiB |      0.32% |  448.00 GiB |          12.50% |
| [f01955030](https://filfox.info/en/address/f01955030) |             Hangzhou, Zhejiang, CN |          32.00 GiB |      0.02% |   32.00 GiB |           0.00% |

![Provider Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/145/1671092621552.png)
### Deal Data Replication
The below table shows how each many unique data are replicated across storage providers.
- No more than 25% of unique data are stored with less than 4 providers.

⚠️ 100.00% of deals are for data replicated across less than 4 storage providers.

| Unique Data Size | Total Deals Made | Number of Providers | Deal Percentage |
| ---------------: | ---------------: | ------------------: | --------------: |
|       111.38 TiB |       157.41 TiB |                   1 |          99.41% |
|       448.00 GiB |       960.00 GiB |                   2 |           0.59% |

![Replication Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/145/1671092622252.png)
### Deal Data Shared with other Clients
The below table shows how many unique data are shared with other clients.
Usually different applications owns different data and should not resolve to the same CID.

⚠️ CID sharing has been observed.

| Other Client                                                                                                                                                                                                              | Application                                                                                                   | Total Deals Affected | Unique CIDs |        Verifier |
| :------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ | :------------------------------------------------------------------------------------------------------------ | -------------------: | ----------: | --------------: |
| [f13d6zt424jkp55u7kp67azotkzadtlokwnz2ntxa](https://filfox.info/en/address/f13d6zt424jkp55u7kp67azotkzadtlokwnz2ntxa)                                                                                                     | [ FilSwan \- Slingshot Restore](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/157)  |           506.94 TiB |       2,960 | LDN v3 multisig |
| [f1bstbq5bi72kyovhh7zoo2f6l6uivsjz4ey5dnqq](https://filfox.info/en/address/f1bstbq5bi72kyovhh7zoo2f6l6uivsjz4ey5dnqq)                                                                                                     | [FilSwan](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/917)                        |           241.50 TiB |       2,355 | LDN v3 multisig |
| [f1o54sve7ede7im4caux3ug7lsyjmbue7ss3zzl6y](https://filfox.info/en/address/f1o54sve7ede7im4caux3ug7lsyjmbue7ss3zzl6y)                                                                                                     | [FilSwan](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/278)                        |           218.41 TiB |       2,710 | LDN v3 multisig |
| [f3v7x4a2aapgx6o2r477tenoin3u5oadaeqyd7kjd<br/>sitykvf4ok7vq2utcyh34lmu5u7oybs25ff6s4dbu<br/>dpma](https://filfox.info/en/address/f3v7x4a2aapgx6o2r477tenoin3u5oadaeqyd7kjdsitykvf4ok7vq2utcyh34lmu5u7oybs25ff6s4dbudpma) | [LeoCheung \- Slingshot Restore](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/151) |            71.00 TiB |         584 | LDN v3 multisig |
| [f3qebbkqspq4w6deouaubtngt4bmaada76uqs3omy<br/>3tki6hoeocpgxyplknev5u3oi5e7xnltobrvgxnpa<br/>3qga](https://filfox.info/en/address/f3qebbkqspq4w6deouaubtngt4bmaada76uqs3omy3tki6hoeocpgxyplknev5u3oi5e7xnltobrvgxnpa3qga) | [codex8080 \- Slingshot Restore](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/152) |            64.53 TiB |         424 | LDN v3 multisig |
| [f1toz5izxdse43peqyd7zktmyqilvhf6u72z74gfq](https://filfox.info/en/address/f1toz5izxdse43peqyd7zktmyqilvhf6u72z74gfq)                                                                                                     | [Starboard Networks](https://github.com/filecoin-project/filecoin-plus-client-onboarding/issues/1855)         |            32.75 TiB |         424 |       Steven Li |
| [f14r2jybmccwiu6hze4fu55jyhclktvwacec56hea](https://filfox.info/en/address/f14r2jybmccwiu6hze4fu55jyhclktvwacec56hea)                                                                                                     | [ FilSwan](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/15)                        |            30.09 TiB |         808 | LDN v3 multisig |
| [f1r3d25hl2y7rqlsu2mgczdethy4qqjmkfdlmibfq](https://filfox.info/en/address/f1r3d25hl2y7rqlsu2mgczdethy4qqjmkfdlmibfq)                                                                                                     | [ NEXRAD \- FilSwan](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/80)              |             1.22 TiB |          29 | LDN v3 multisig |
| [f13zfhkvtf6mewd74jhav6iqcggwsojht73tickga](https://filfox.info/en/address/f13zfhkvtf6mewd74jhav6iqcggwsojht73tickga)                                                                                                     | [X\-Order Lab](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/936)                   |             1.06 TiB |          33 | LDN v3 multisig |

[^1]: To manually trigger this report, add a comment with text `checker:manualTrigger`
