### ISSUE TITLE
[DataCap Application] Dukesoft / Slingshot Restore

### ISSUE THREAD

**Issue by RobQuistNL** [filecoin-project/filecoin-plus-large-datasets#146]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information 
- Organization Name: Dukesoft - Slingshot Restore
- Website / Social Media: Dukesoft.nl
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 1 PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 500 TiB
- On-chain address for first allocation: f3w436qzcbnzpngwwkslethcbsnt7rjdslf25mk7ufoo27gmf4uxt3pa3yn5zilzaqwqduew7pqmu5v2nypuiq

## Project details

Share a brief history of your project and organization.
```
Repairing the lost slingshot data
```

What is the primary source of funding for this project?
```
My own time.
```

What other projects/ecosystem stakeholders is this project associated with?
```
None
```

## Use-case details

Describe the data being stored onto Filecoin
```
Trying to get petabytes of data back online :) the missing slingshot data
```

Where was the data in this dataset sourced from?
```
Slingshot datasets
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
I don't know which sets I'm going to get yet
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes
```

What is the expected retrieval frequency for this data?
```
No idea
```

For how long do you plan to keep this dataset stored on Filecoin?
```
500 days
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Probably worldwide, depends on the miners that I'm going to get assigned to
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Most likely physical hard drives because internet is too slow
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
They will be assigned to me
```

How will you be distributing deals across storage providers?
```
1 deal to each of the 5 miners I'm being assigned to
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
yes
```

**Comment by cryptowhizzard** [comment]
I am in favor of supporting this as @RobQuistNL is participating in the slingshot repair program.

**Comment by galen-mcandrew** [comment]
## Multisig Notary requested
#### Total DataCap requested 
> 1PiB
#### Expected weekly DataCap usage rate 
> 500TiB

**Comment by neogeweb3** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecmwqoovgfz7ks22xxll44cogjlxaoxl62qstfap6bjlbr5erok6a 
#### Address 
> f3w436qzcbnzpngwwkslethcbsnt7rjdslf25mk7ufoo27gmf4uxt3pa3yn5zilzaqwqduew7pqmu5v2nypuiq
#### Datacap Allocated
> 51TiB
#### Signer Address
> f13k5zr6ovc2gjmg3lvd43ladbydhovpylcvbflpa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecmwqoovgfz7ks22xxll44cogjlxaoxl62qstfap6bjlbr5erok6a

**Comment by Fenbushi-Filecoin** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedhwrnz67rkluvcy6eb5k3b6ndabzph5f6x7t6z26seifkqigjqhs 
#### Address 
> f3w436qzcbnzpngwwkslethcbsnt7rjdslf25mk7ufoo27gmf4uxt3pa3yn5zilzaqwqduew7pqmu5v2nypuiq
#### Datacap Allocated
> 51TiB
#### Signer Address
> f1yqydpmqb5en262jpottko2kd65msajax7fi4rmq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedhwrnz67rkluvcy6eb5k3b6ndabzph5f6x7t6z26seifkqigjqhs

**Comment by cryptowhizzard** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebaw3d27np4jbaka6o3egedbqjucqaqw4dqk5dbfoesjukqwym6r2 
#### Address 
> f3w436qzcbnzpngwwkslethcbsnt7rjdslf25mk7ufoo27gmf4uxt3pa3yn5zilzaqwqduew7pqmu5v2nypuiq
#### Datacap Allocated
> 102TiB
#### Signer Address
> f1krmypm4uoxxf3g7okrwtrahlmpcph3y7rbqqgfa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebaw3d27np4jbaka6o3egedbqjucqaqw4dqk5dbfoesjukqwym6r2

**Comment by swatchliu** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebwyipu2gdu5mtazd44xwc2ro32cwswdzs6sm3yziiht4pp2i5362 
#### Address 
> f3w436qzcbnzpngwwkslethcbsnt7rjdslf25mk7ufoo27gmf4uxt3pa3yn5zilzaqwqduew7pqmu5v2nypuiq
#### Datacap Allocated
> 102TiB
#### Signer Address
> f1yh6q3nmsg7i2sys7f7dexcuajgoweudcqj2chfi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebwyipu2gdu5mtazd44xwc2ro32cwswdzs6sm3yziiht4pp2i5362

**Comment by Reiers** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec3ucb7j3us5c5a2b7qa7xyhbksjolngiwaw2qt3jfogwmqknr5ly 
#### Address 
> f3w436qzcbnzpngwwkslethcbsnt7rjdslf25mk7ufoo27gmf4uxt3pa3yn5zilzaqwqduew7pqmu5v2nypuiq
#### Datacap Allocated
> 204TiB
#### Signer Address
> f1oz43ckvmtxmmsfzqm6bpnemqlavz4ifyl524chq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec3ucb7j3us5c5a2b7qa7xyhbksjolngiwaw2qt3jfogwmqknr5ly

**Comment by cryptowhizzard** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebiapvr5bye7hpxf2khx5xsgl64l3h3jrwr3644hjfqyddzojdl7k 
#### Address 
> f3w436qzcbnzpngwwkslethcbsnt7rjdslf25mk7ufoo27gmf4uxt3pa3yn5zilzaqwqduew7pqmu5v2nypuiq
#### Datacap Allocated
> 204TiB
#### Signer Address
> f1krmypm4uoxxf3g7okrwtrahlmpcph3y7rbqqgfa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebiapvr5bye7hpxf2khx5xsgl64l3h3jrwr3644hjfqyddzojdl7k

**Comment by flyworker** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebxvj3dokp7txwaus6nly6gkuqapqpfrbk35utfjl2p45m77kflrs 
#### Address 
> f3w436qzcbnzpngwwkslethcbsnt7rjdslf25mk7ufoo27gmf4uxt3pa3yn5zilzaqwqduew7pqmu5v2nypuiq
#### Datacap Allocated
> 204TiB
#### Signer Address
> f1hlubjsdkv4wmsdadihloxgwrz3j3ernf6i3cbpy
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebxvj3dokp7txwaus6nly6gkuqapqpfrbk35utfjl2p45m77kflrs

**Comment by RobQuistNL** [comment]
67 TiB left

**Comment by MegTei** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedl6525gflsznj4owc2dntmpmydxolzoy7ghbvdq4itx4wk2a4zag 
#### Address 
> f3w436qzcbnzpngwwkslethcbsnt7rjdslf25mk7ufoo27gmf4uxt3pa3yn5zilzaqwqduew7pqmu5v2nypuiq
#### Datacap Allocated
> 409.60TiB
#### Signer Address
> f1ystxl2ootvpirpa7ebgwl7vlhwkbx2r4zjxwe5i
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedl6525gflsznj4owc2dntmpmydxolzoy7ghbvdq4itx4wk2a4zag

**Comment by flyworker** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebunroidqytzmb5m7sndibp5ad5f7ewtikraydaijlkuq6tny7cxc 
#### Address 
> f3w436qzcbnzpngwwkslethcbsnt7rjdslf25mk7ufoo27gmf4uxt3pa3yn5zilzaqwqduew7pqmu5v2nypuiq
#### Datacap Allocated
> 409.60TiB
#### Signer Address
> f1hlubjsdkv4wmsdadihloxgwrz3j3ernf6i3cbpy
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebunroidqytzmb5m7sndibp5ad5f7ewtikraydaijlkuq6tny7cxc

**Comment by RobQuistNL** [comment]
Out of datacap again

**Comment by IreneYoung** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebsldouiskjxwcqc4mv7s32nj764nxj4wiwf2mxzk6siyzxxvn2zy 
#### Address 
> f3w436qzcbnzpngwwkslethcbsnt7rjdslf25mk7ufoo27gmf4uxt3pa3yn5zilzaqwqduew7pqmu5v2nypuiq
#### Datacap Allocated
> 463.00TiB
#### Signer Address
> f1d4gmpqz3execjj2wvrxuuhvbms5mzh7t7yqrviq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebsldouiskjxwcqc4mv7s32nj764nxj4wiwf2mxzk6siyzxxvn2zy

**Comment by cryptowhizzard** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecibn6mun2dxcjff47yf377upvllk3iciovqubeqmbedyhil2ywso 
#### Address 
> f3w436qzcbnzpngwwkslethcbsnt7rjdslf25mk7ufoo27gmf4uxt3pa3yn5zilzaqwqduew7pqmu5v2nypuiq
#### Datacap Allocated
> 463.00TiB
#### Signer Address
> f1krmypm4uoxxf3g7okrwtrahlmpcph3y7rbqqgfa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecibn6mun2dxcjff47yf377upvllk3iciovqubeqmbedyhil2ywso

**Comment by RobQuistNL** [comment]
I opened the next one for the next (and final) bunch of deals: https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/262

**Comment by TimWilliams00** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecox226nxlohmlqsxwp4xcyz3m2urtjy5kg2jixosrnmtvk26bkog 
#### Address 
> f3w436qzcbnzpngwwkslethcbsnt7rjdslf25mk7ufoo27gmf4uxt3pa3yn5zilzaqwqduew7pqmu5v2nypuiq
#### Datacap Allocated
> 53.40TiB
#### Signer Address
> f1fkxkfxgopjf3ufnfg5i3m6qlwf73kp4w5zz7nnq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecox226nxlohmlqsxwp4xcyz3m2urtjy5kg2jixosrnmtvk26bkog

**Comment by MegTei** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecaccnpezldif7lqjvmc2gpf6fekydinx46jm7q46z7wvnukrlzsy 
#### Address 
> f3w436qzcbnzpngwwkslethcbsnt7rjdslf25mk7ufoo27gmf4uxt3pa3yn5zilzaqwqduew7pqmu5v2nypuiq
#### Datacap Allocated
> 53.40TiB
#### Signer Address
> f1ystxl2ootvpirpa7ebgwl7vlhwkbx2r4zjxwe5i
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecaccnpezldif7lqjvmc2gpf6fekydinx46jm7q46z7wvnukrlzsy

**Comment by RobQuistNL** [comment]
Yes, but it should continue here: https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/262

I need moarrr :)

**Comment by filplus-checker** [comment]
## DataCap and CID Checker Report[^1]
 - Organization: `Dukesoft - Slingshot Restore`
 - Client: `f3w436qzcbnzpngwwkslethcbsnt7rjdslf25mk7ufoo27gmf4uxt3pa3yn5zilzaqwqduew7pqmu5v2nypuiq`
### Storage Provider Distribution
The below table shows the distribution of storage providers that have stored data for this client.

If this is the first time a provider takes verified deal, it will be marked as `new`.

For most of the datacap application, below restrictions should apply.
 - Storage provider should not exceed 25% of total datacap.
 - Storage provider should not be storing duplicate data for more than 20%.
 - Storage provider should have published its public IP address.
 - All storage providers should be located in different regions.

⚠️ [f01660837](https://filfox.info/en/address/f01660837) has unknown IP location.

| Provider                                                    |                         Location | Total Deals Sealed | Percentage | Unique Data | Duplicate Deals |
| :---------------------------------------------------------- | -------------------------------: | -----------------: | ---------: | ----------: | --------------: |
| [f01345523](https://filfox.info/en/address/f01345523)       |          Antwerpen, Flanders, BE |         370.84 TiB |     23.57% |  370.46 TiB |           0.10% |
| [f01392893](https://filfox.info/en/address/f01392893)       |     Amsterdam, North Holland, NL |         369.45 TiB |     23.48% |  369.29 TiB |           0.04% |
| [f01702940](https://filfox.info/en/address/f01702940)       |                Dallas, Texas, US |         194.38 TiB |     12.35% |  194.31 TiB |           0.03% |
| [f01752548](https://filfox.info/en/address/f01752548)`new`  |          Seattle, Washington, US |         188.35 TiB |     11.97% |  188.35 TiB |           0.00% |
| [f01652333](https://filfox.info/en/address/f01652333)       |        Sunnyvale, California, US |         175.60 TiB |     11.16% |  175.60 TiB |           0.00% |
| [f01558688](https://filfox.info/en/address/f01558688)       |             Toronto, Ontario, CA |         119.17 TiB |      7.57% |  119.17 TiB |           0.00% |
| [f0838923](https://filfox.info/en/address/f0838923)         |          Seattle, Washington, US |          78.21 TiB |      4.97% |   78.21 TiB |           0.00% |
| [f01611097](https://filfox.info/en/address/f01611097)       |     San Clemente, California, US |          36.16 TiB |      2.30% |   36.16 TiB |           0.00% |
| [f01775922](https://filfox.info/en/address/f01775922)       |            Ashburn, Virginia, US |          20.03 TiB |      1.27% |   20.03 TiB |           0.00% |
| [f01208862](https://filfox.info/en/address/f01208862)       | Heerhugowaard, North Holland, NL |          11.73 TiB |      0.75% |   11.73 TiB |           0.00% |
| [f01786387](https://filfox.info/en/address/f01786387)       | Heerhugowaard, North Holland, NL |           7.73 TiB |      0.49% |    7.73 TiB |           0.00% |
| [f01847751](https://filfox.info/en/address/f01847751)`new`  |             Denver, Colorado, US |           1.56 TiB |      0.10% |    1.56 TiB |           0.00% |
| [f01240](https://filfox.info/en/address/f01240)             | Heerhugowaard, North Holland, NL |          32.00 GiB |      0.00% |   32.00 GiB |           0.00% |
| [f01660837](https://filfox.info/en/address/f01660837)       |                          Unknown |          16.00 GiB |      0.00% |   16.00 GiB |           0.00% |

![Provider Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/146/1671092639008.png)
### Deal Data Replication
The below table shows how each many unique data are replicated across storage providers.
- No more than 25% of unique data are stored with less than 4 providers.

✔️ Data replication looks healthy.

| Unique Data Size | Total Deals Made | Number of Providers | Deal Percentage |
| ---------------: | ---------------: | ------------------: | --------------: |
|        32.00 GiB |        32.00 GiB |                   1 |           0.00% |
|         1.63 TiB |         3.25 TiB |                   2 |           0.21% |
|        77.58 TiB |       233.20 TiB |                   3 |          14.82% |
|       144.10 TiB |       576.40 TiB |                   4 |          36.64% |
|       141.01 TiB |       705.16 TiB |                   5 |          44.82% |
|         9.20 TiB |        55.22 TiB |                   6 |           3.51% |

![Replication Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/146/1671092639839.png)
### Deal Data Shared with other Clients
The below table shows how many unique data are shared with other clients.
Usually different applications owns different data and should not resolve to the same CID.

✔️ No CID sharing has been observed.

[^1]: To manually trigger this report, add a comment with text `checker:manualTrigger`

**Comment by fabriziogianni7** [comment]
> @fabriziogianni7 @huseyincansoylu allocation #6 did not hit, https://filfox.info/en/message/bafy2bzacecaccnpezldif7lqjvmc2gpf6fekydinx46jm7q46z7wvnukrlzsy see exitCode != 0. Notary on chain still has 53.40 TiB of DataCap, but tooling thinks its finished. I think this preceded the exitCode checks we added, may need to be manually fixed?

@dkkapur is the transaction still pending on the node? if so, we can re-paste that comment
