### ISSUE TITLE
Shenzhen Dongyu Clothing Technology Co., Ltd

### ISSUE THREAD

**Issue by sowhat99** [filecoin-project/filecoin-plus-large-datasets#1466]
### Data Owner Name

Shenzhen Dongyu Clothing Technology Co., Ltd

### Data Owner Country/Region

China

### Data Owner Industry

Other

### Website

http://www.dongyufashion.com/

### Social Media

```text
RED: https://www.xiaohongshu.com/user/profile/5e2504830000000001006568?xhsshare=CopyLink&appuid=5fb0152e00000000010098cd&apptime=1671163397

Douyin：https://v.douyin.com/harLEeo/
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

200TiB

### On-chain address for first allocation

f1hyif7spofkgpgfwk6y4neqmej6u3mdod6zrimba

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Shenzhen Dongyu Clothing Technology Co., Ltd. was founded in 2000, the company has 205 employees, we are a collection of clothing design, production, sales, marketing management, as well as software research and development and sales as one of the modern enterprises. Its brands include: MAPLE AROMA, a mature high-end women's wear brand, and GIGLIO COUTURE.
As a senior clothing brand with a long history, our company integrates design, production, research and development, manufacturing and sales, and has signed a long-term strategic cooperation agreement with a top big data software research and development company in the UK. We are committed to the research and development of intelligent aesthetics big data acquisition/matching software system, and cooperate in the research and development of C2C2M industrial chain integration platform. Enhance the competitiveness of the company in the whole field of clothing industry. At present, we have set up 22 stores in 11 cities in China, serving nearly 100,000 + customers.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
As a clothing brand with a history of 22 years, our company is committed to providing clothing solutions for women and becoming a trusted partner of customers. During the growth of this company, we have private banking activities, private clothing customization services, clothing model display pictures, store member VIP and other picture data, and hope to store this part of data on the Filecoin network.

Therefore, these data are roughly:
Photos of Dongyu Private Bank and Local Chamber of Commerce activities
Dongyu private clothing customization service picture
Dongyu ready-to-wear model display pictures
Dongyu store member VIP activity picture
Pictures of Dongyu clothing conference
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### How do you plan to prepare the dataset

lotus

### Please share a sample of the data

```text
Private Banking and Local Chamber of Commerce Activities:
https://drive.google.com/drive/folders/1trEFXRrEzOnzp_XXoKoRh1U2IeeisqoB?usp=share_link
https://drive.google.com/drive/folders/1m1Xd3FGk9PLt7FXAMpb1QiOjGzCVeCqR?usp=share_link
https://drive.google.com/drive/folders/1uEzDyFu9lrYF42BXkbGxn15taRP62vuj?usp=share_link
https://drive.google.com/drive/folders/1YHG1gG4g3rBvG4gFN3Yw69hqD6kvAO0j?usp=share_link
Personal clothing customization service:
https://drive.google.com/drive/folders/1dNWB84UA67CqIByEzsebCu7PlFcU1VKh?usp=share_link
Ready-to-wear model display picture:
https://drive.google.com/drive/folders/12uZ1obmPK9ceSUYJjljpQnaymdrgaXHm?usp=share_link
Store member VIP activities:
https://drive.google.com/drive/folders/10MypffNalz5Dtx0o0Nj2hvidV0cPirnh?usp=share_link
Clothing launch:
https://drive.google.com/drive/folders/1y_4k9BkGKZ2gzVZNUZpmeyAfjZwputWE?usp=share_link
Store background music:
https://drive.google.com/drive/folders/1RR19Nl7EpAAWmj0w3hSSTEDYVV1j-Hsl?usp=share_link
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Sporadic

### For how long do you plan to keep this dataset stored on Filecoin

2 to 3 years

### In which geographies do you plan on making storage deals

Greater China, North America

### How will you be distributing your data to storage providers

Shipping hard drives, Lotus built-in data transfer

### How do you plan to choose storage providers

Slack, Filmine

### If you already have a list of storage providers to work with, fill out their names and provider IDs below

```text
f0119336、f01035680、f0673990、 f0707721, f01537511
```

### How do you plan to make deals to your storage providers

Boost client, Lotus client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
Most data samples you provided were created a long time ago.
![image](https://user-images.githubusercontent.com/105098820/208407673-19a96e57-c503-4981-8cec-5db6da23b433.png)
![image](https://user-images.githubusercontent.com/105098820/208407802-3066bbba-1cd2-4b1d-aad4-3fb79b07f4ab.png)
Are you storing all the historical data? Or can you provide some updated data samples?
How much data do you have? 
What's the relationship between you and the organization?
Whether the sps you choose can support data retrieval?

**Comment by sowhat99** [comment]
Thank you for your attention
I am an executive of our company, my contact information has been left on our company website
As a company established for more than 20 years, we have more data than most companies. According to incomplete statistics, our total data exceeds 1.3PiB.
We are actively contacting more SPs. In the end, the SPs we cooperate with will definitely meet our enterprise's retrieval.
In addition, we provide more data cases, including our participation in fashion week data, store data, video, designer clothing data, etc.:

Clothing Conference
https://drive.google.com/drive/folders/1GbNxk6DD_Z0xvEjs28plB9l7yKes1ct9?usp=share_link
giancarlo mossi -designer
https://drive.google.com/drive/folders/16iHt_hRjP4Ak3tm7HMPki681lVjZrtPT?usp=share_link
Product pictures
https://drive.google.com/drive/folders/1Ocq4se5pRGjH1wU1RUa6Ge7KJANi0LNr?usp=share_link
store
https://drive.google.com/drive/folders/1OJQClsBdQRTuT8hFA6pO0mYH1W2NWjR7?usp=share_link
video
https://drive.google.com/drive/folders/1QdZrrKNf0jr8khiwF2RfGnHPR8lKE-Ky?usp=share_link

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 200TiB

**Client address**

> f1hyif7spofkgpgfwk6y4neqmej6u3mdod6zrimba

**Comment by herrehesse** [comment]
Dear Applicant,

Due to the increased amount of erroneous/wrong Filecoin+ data recently, on behalf of the entire community, we feel compelled to go deeper into datacap requests. Hereby to ensure that the overall value of the Filecoin network and Filecoin+ program increases and is not abused.

Please answer the questions below as comprehensively as possible.

**Customer data**

- Could you demonstrate exactly how and to what extent customer contact occurred? 

We expect that for the onboarding of customers with the scale of an LDN there would have been at least multiple email and perhaps several chat conversations preceding it. A single email with an agreement does not qualify here.

- Did the customer specify the amount of data involved in this relevant correspondence?

- Why does the customer in question want to use the Filecoin+ program? 

_Should this only be soley for acquiring datacap this is of course **out of the question**. The customer must have a legitimate reason for wanting to use the Filecoin+ program which is intended as a program to store useful and public datasets on the network._ 

- Why is the customer data considered Filecoin+ eligible?

_(As an intermediate solution Filecoin offers the FIL-E program or the glif.io website for business datasets that do not meet the requirements for a Filecoin+ dataset)_


**Files and Processing**

- Could you please demonstrate to us how you envision processing and transporting the customer data in question to any location for preparation?
- Would you demonstrate to us that the customer, the preparer and the intended storage providers all have adequate bandwidth to process the set with its corresponding size?
- Would you tell us how the data set preparer takes into account the prevention of duplicates in order to prevent data cap abuse?


Hopefully you understand the caution the overall community has for onboarding the wrong data. We understand the increased need for Filecoin+, however, we must not allow the program to be misused. Everything depends on a valuable and useful network, let's do our best to make this happen. Together.

**Comment by sowhat99** [comment]
> 亲爱的申请人，
> 
> 由于最近错误/错误的 Filecoin+ 数据数量增加，我们代表整个社区感到有必要更深入地研究数据上限请求。特此确保 Filecoin 网络和 Filecoin+ 程序的整体价值增加和不被滥用。
> 
> 请尽可能全面地回答以下问题。
> 
> **客户资料**
> 
> * 您能否确切地说明如何以及在多大程度上发生了客户联系？
> 
> 我们预计，对于 LDN 规模的客户入职，至少会有多封电子邮件，之前可能还会有几次聊天对话。带有协议的单个电子邮件不符合此处的条件。
> 
> * 客户是否指定了此相关通信中涉及的数据量？
> * 为什么有问题的客户想要使用 Filecoin+ 程序？
> 
> _如果这只是为了获取 datacap 这当然是不可能**的**。客户必须有正当理由想要使用 Filecoin+ 程序，该程序旨在用作在网络上存储有用和公共数据集的程序。_
> 
> * 为什么客户数据被认为 Filecoin+ 符合条件？
> 
> _（作为中间解决方案，Filecoin 为不满足 Filecoin+ 数据集要求的业务数据集提供 FIL-E 程序或 glif.io 网站）_
> 
> **文件和处理**
> 
> * 您能否向我们展示您设想如何处理相关客户数据并将其传输到任何位置进行准备？
> * 你能向我们证明客户、准备者和预期的存储提供商都有足够的带宽来处理相应大小的集合吗？
> * 您能否告诉我们数据集准备者如何考虑防止重复以防止滥用数据上限？
> 
> 希望您了解整个社区对载入错误数据的谨慎态度。我们理解对 Filecoin+ 的需求增加，但是，我们绝不能允许该程序被滥用。一切都取决于有价值和有用的网络，让我们尽最大努力实现这一目标。一起。

Shenzhen Dongyu Clothing Technology Co., Ltd. was founded in 2000, the company has 205 employees, we are a collection of clothing design, production, sales, marketing management, as well as software research and development and sales as one of the modern enterprises. Its brands include: MAPLE AROMA, a mature high-end women's wear brand, and GIGLIO COUTURE. As a senior clothing brand with a long history, we have set up 22 stores in 11 cities in China, serving nearly 100,000 + customers.

We have provided a lot of data cases, which record the activities we held, the styles of our clothing, the environment of our stores, etc. We also have a lot of data that will be stored on the Filecoin network in the future.

![1466](https://user-images.githubusercontent.com/117882503/217745010-a75fef35-d386-40a8-951a-dc9aa7a9116a.png)

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Looking at your application i have some questions:
As you are brand new on Github and have no history of past applications it seems to me that applying for 5PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?

Can you show us visible proof of the size of your data and the storage systems you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230337462961356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!

**Comment by sowhat99** [comment]
Hello, is there any information I need to provide to get to the next round? Could you sign for me, please?

**Comment by sowhat99** [comment]
![109721676274693_ pic](https://user-images.githubusercontent.com/117882503/218402174-a34e013a-c380-476b-ab58-bcf21d7de79e.jpg)

**Comment by sowhat99** [comment]
Recently, I have downloaded data that was originally stored on aws to local hard drive storage. Below is a screenshot of some of the data.
![109721676274693_ pic](https://user-images.githubusercontent.com/117882503/218404198-eb11d1b5-2d42-4df6-a47d-7a0e764ba065.jpg)

**Comment by sowhat99** [comment]
@cryptowhizzard

**Comment by sowhat99** [comment]
@cryptowhizzard @herrehesse

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

As last question i would like you to fill out [this form](https://form.jotform.com/230337462961356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!

**Comment by sowhat99** [comment]
It has been sent!
![5801676348474_ pic](https://user-images.githubusercontent.com/117882503/218638745-652e7b9b-08d1-4136-aea4-0f694ad24454.jpg)

**Comment by cryptowhizzard** [comment]
Hello,

Thanks!

Upon checking i found that your miners do not qualify for Fil+. The miners are not reachable on the internet and are not open for retrieval.

Do you prefer other's or is this something that is going to be fixed?

Last -> there is one SP missing. You have 2 personals and only one is allowed ( unless you distribute the set 50% / 50 % on these personal ones ) however then you still miss on nr. 4

**Comment by sowhat99** [comment]
@cryptowhizzard  Hello, thank you for your review. Which SP does not comply with fil+ rules?

**Comment by sowhat99** [comment]
Retrieval is necessary, no doubt about it. I will contact SP to solve this problem.

**Comment by sowhat99** [comment]
Perhaps you would like to help me start the first phase of the process? When the process starts, you'll have a better idea of whether I really follow the rules and not be a fraud.

**Comment by xiaoyuaiheshui** [comment]
@cryptowhizzard  How can I access this KYC questionnaire?  
Can you provide the SP you contacted again? So that I can make a survey.
I checked your reply above, which seems to be all right.
If possible, I would like to try the first allocation

**Comment by cryptowhizzard** [comment]
Hi @xiaoyuaiheshui 

![afbeelding1](https://user-images.githubusercontent.com/36404435/219007202-f7c3a5df-2995-419b-a121-312f41b46f2d.png)

Happy to help here. These are the SP's provided to me.

I did not contact the SP's ... My reply above states the SP's were not reachable and therefore not qualify.

For the KYC and personal data i recommend that you contact @sowhat99 .

**Comment by xiaoyuaiheshui** [comment]
> Hi @xiaoyuaiheshui
> 
> ![afbeelding1](https://user-images.githubusercontent.com/36404435/219007202-f7c3a5df-2995-419b-a121-312f41b46f2d.png)
> 
> Happy to help here. These are the SP's provided to me.
> 
> I did not contact the SP's ... My reply above states the SP's were not reachable and therefore not qualify.
> 
> For the KYC and personal data i recommend that you contact @sowhat99 .

thank you.

**Comment by xiaoyuaiheshui** [comment]
@sowhat99  The SPs you choose don't seem to be very good. Can you first let them prove that they can provide retrieval capability, or find a more suitable SP.

**Comment by sowhat99** [comment]
@xiaoyuaiheshui Thank you for your participation!
Can you tell me which SP has bad behavior? I will make adjustments in time.

**Comment by xiaoyuaiheshui** [comment]
F0870354 cannot support retrieval
F0515360 and f01710095 have no data, but they have not received data, if they can prove themselves.

**Comment by sowhat99** [comment]
@cryptowhizzard @xiaoyuaiheshui  Thanks for reminding！

I have contacted and solved it. Now f0870354 supports retrieval.

f0515360 and f01710095 will also be available today.

**Comment by sowhat99** [comment]
There is a slight problem. I will replace f01710095 with f01986353.

**Comment by xiaoyuaiheshui** [comment]
It looks good. I will sign it. First allocation, look forward to the next milestone!

**Comment by xiaoyuaiheshui** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecmqwvu424ap6jgdofvk3l4ovjvnxhuh3xqco6gkuuujgilnfg7ks 
#### Address 
> f1hyif7spofkgpgfwk6y4neqmej6u3mdod6zrimba
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f122qmy25wdtt5mxd77kndiq7z5x2n3iwiuz2wdsa
#### Id
> 9b2864bc-604c-46b3-8abe-649fa15556c9
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecmqwvu424ap6jgdofvk3l4ovjvnxhuh3xqco6gkuuujgilnfg7ks

**Comment by sowhat99** [comment]
@cryptowhizzard Hello, can you sign for me?

**Comment by cryptowhizzard** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceclusz76rwcpcfbbcmmbr4lcjlihpl5pudsyesmjxfmhklaltszpk 
#### Address 
> f1hyif7spofkgpgfwk6y4neqmej6u3mdod6zrimba
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1krmypm4uoxxf3g7okrwtrahlmpcph3y7rbqqgfa
#### Id
> 9b2864bc-604c-46b3-8abe-649fa15556c9
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceclusz76rwcpcfbbcmmbr4lcjlihpl5pudsyesmjxfmhklaltszpk

**Comment by cryptowhizzard** [comment]
Happy to help. Looking forward to the next milestone!

**Comment by a1991car** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec6kvqdfif66pmb62gzp7cdb6z5kryyu3phhutjgm2q7soe3272ws 
#### Address 
> f1hyif7spofkgpgfwk6y4neqmej6u3mdod6zrimba
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1qnumecdypgrbaebtkdfjnwt5ndacadcuas3deiq
#### Id
> b63e0a69-23f7-4236-9303-de297557939c
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec6kvqdfif66pmb62gzp7cdb6z5kryyu3phhutjgm2q7soe3272ws

**Comment by a1991car** [comment]
![微信图片_20230403175221](https://user-images.githubusercontent.com/32447611/229475720-1859709f-c70b-4360-bd93-b3ab47ace83d.jpg)

**Comment by kernelogic** [comment]
SP is reachable for retrieval. I noticed the distribution ratio is a little low. Client has informed me about plan to increase distribution on later phases. Willing to support.

<img width="828" alt="image" src="https://user-images.githubusercontent.com/3711825/230299437-7752bd6b-b777-4598-97de-bb2b63f8e095.png">

**Comment by kernelogic** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebonhl6wj427j5tgb5ws4vsksx22gx2etgbg76cqydvrxnjpn6nls 
#### Address 
> f1hyif7spofkgpgfwk6y4neqmej6u3mdod6zrimba
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebonhl6wj427j5tgb5ws4vsksx22gx2etgbg76cqydvrxnjpn6nls

**Comment by Chuangshi1** [comment]
checker:manualTrigger

**Comment by Chuangshi1** [comment]
CID report looks good, i will support you.

**Comment by Chuangshi1** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebio2kmvyigspv2czncpp2736t4k6ysw2srue5mtxpltdcdjqesyw 
#### Address 
> f1hyif7spofkgpgfwk6y4neqmej6u3mdod6zrimba
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1mdk7s2vntzm6hu35yuo6vjubtrpfnb2awhgvrri
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebio2kmvyigspv2czncpp2736t4k6ysw2srue5mtxpltdcdjqesyw

**Comment by luobin544** [comment]
![10431685165435_ pic](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/4277341/0edcdd67-a332-44cf-b2e0-9fe7aec2d598)

**Comment by 1ane-1** [comment]
checker:manualTrigger

**Comment by luobin544** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedij7avcahc33c43e4fkspbvnqad6kxxvsidywp6uhmuvulbgaata 
#### Address 
> f1hyif7spofkgpgfwk6y4neqmej6u3mdod6zrimba
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1tbd632f6w62glfaf7wjpimacbnjiz26poyoes2q
#### Id
> 13ac7fa1-9881-47c8-a76b-70af2b2b3a78
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedij7avcahc33c43e4fkspbvnqad6kxxvsidywp6uhmuvulbgaata

**Comment by 1ane-1** [comment]
![07cd4a5762543627c9184d8cc47bdbb](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/91301211/5060fd64-927e-4390-b4d4-3f6a8fead75e)

**Comment by 1ane-1** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb7r6utyghlojb3dtzx5ys2hugb47yu4ulj2kewvd5topgwzcel5y 
#### Address 
> f1hyif7spofkgpgfwk6y4neqmej6u3mdod6zrimba
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1mdk7s2vntzm6hu35yuo6vjubtrpfnb2awhgvrri
#### Id
> 13ac7fa1-9881-47c8-a76b-70af2b2b3a78
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb7r6utyghlojb3dtzx5ys2hugb47yu4ulj2kewvd5topgwzcel5y

**Comment by NiwanDao** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebwkorws3x5kcj2iqxfivjcwzbaxpc5jb5k7zkldcxbugjv4os4yq 
#### Address 
> f1hyif7spofkgpgfwk6y4neqmej6u3mdod6zrimba
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1a2lia2cwwekeubwo4nppt4v4vebxs2frozarz3q
#### Id
> 13ac7fa1-9881-47c8-a76b-70af2b2b3a78
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebwkorws3x5kcj2iqxfivjcwzbaxpc5jb5k7zkldcxbugjv4os4yq

**Comment by kevzak** [comment]
checker:manualTrigger

**Comment by 1ane-1** [comment]
checker:manualTrigger

**Comment by 1ane-1** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedjw4dbznuucgeasw6u4sf4cwu4e3ppalwmhlm3np3wqgtnfro2ge 
#### Address 
> f1hyif7spofkgpgfwk6y4neqmej6u3mdod6zrimba
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1mdk7s2vntzm6hu35yuo6vjubtrpfnb2awhgvrri
#### Id
> 228cb5b7-cbe9-4357-b39a-9be08d54b3cc
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedjw4dbznuucgeasw6u4sf4cwu4e3ppalwmhlm3np3wqgtnfro2ge

**Comment by ipollo00** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb64kk63vhzqu5o7extafka6rtgjwrvlgwrziwoia6qln4jtgbtas 
#### Address 
> f1hyif7spofkgpgfwk6y4neqmej6u3mdod6zrimba
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1n5wlrrhoxpkgwij25xrtt7w7g2k3fhbthmdn6ri
#### Id
> 228cb5b7-cbe9-4357-b39a-9be08d54b3cc
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb64kk63vhzqu5o7extafka6rtgjwrvlgwrziwoia6qln4jtgbtas

**Comment by cryptowhizzard** [comment]
checker:manualTrigger

**Comment by Bitengine-reeta** [comment]
checker:manualTrigger

**Comment by Bitengine-reeta** [comment]
everything looks well, will support!

**Comment by Bitengine-reeta** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebfwxjhooka7xa2dejljs5j63s3v35b246d3xxpqhqdfds2y6fqrm 
#### Address 
> f1hyif7spofkgpgfwk6y4neqmej6u3mdod6zrimba
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1jyvhxp4kmwreo22ke4itspraznpudw3uqaink5i
#### Id
> 8247e6b5-49ab-4362-8c46-cc66471ec7f2
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebfwxjhooka7xa2dejljs5j63s3v35b246d3xxpqhqdfds2y6fqrm

**Comment by cryptowhizzard** [comment]
Hi There,

I want to dispute this application.

The applicant is not storing the data he indicated.

http://www.datasetcreators.com/downloadedcarfiles/f02041769-f01153105-33184475-baga6ea4seaqgk3kw2jypvjsor5wfiwmjehdtejkzuweplqc5ua7vwumfoni6mda.car/

I unpacked baga6ea4seaqgk3kw2jypvjsor5wfiwmjehdtejkzuweplqc5ua7vwumfoni6mda and made it available for review.

**Comment by cryptowhizzard** [comment]
@Bitengine-reeta please revoke your signature.

**Comment by herrehesse** [comment]
@Bitengine-reeta I am opening a dispute against your signature.

**Comment by cryptowhizzard** [comment]
Really?

http://www.datasetcreators.com/downloadedcarfiles/f02041769-f01153105-33184475-baga6ea4seaqgk3kw2jypvjsor5wfiwmjehdtejkzuweplqc5ua7vwumfoni6mda.car/ca322cfd-5560-4b89-a333-1b071ef6a0e9.mp4

**Comment by sowhat99** [comment]
But you can't negate my need for data storage! If the data processor does evil, but you directly believe that I have stored fake data. How can I protect my rights?

**Comment by lyjmry** [comment]
checker:manualTrigger

**Comment by sowhat99** [comment]
I'm sorry for storing wrong data. I have communicated with the technical staff and will carefully classify the data. Guaranteed storage of enlisted data. 
Dear notary, please continue to monitor.

**Comment by raghavrmadya** [comment]
@sowhat99 , you cannot just be sorry. This is an absolute violation of the program rules. All allocations must be paused and DC should be removed.

**Comment by raghavrmadya** [comment]
@simonkim0515

**Comment by sowhat99** [comment]
@raghavrmadya 1 out of 8 files is irrelevant data and I explained why above. If it has to be cancelled. fine.
