### ISSUE TITLE
[DataCap Application] TIMAGE

### ISSUE THREAD

**Issue by data-programs** [filecoin-project/filecoin-plus-large-datasets#1468]
### Data Owner Name
TIMAGE

### Data Owner Country/Region
China

### Data Owner Industry
Other

### Website
[http://www.caitangtimage.com/](http://www.caitangtimage.com/)

### Github Handle
@Shepherd-7

### Social Media
https://mp.weixin.qq.com/mp/profile_ext?action=home&__biz=MzIyMjgwNzk5NQ==&scene=124#wechat_redirect    https://v.douyin.com/LoFq6TD/ (Wechat  Tiktok)

### Total amount of DataCap being requested
5 PiB

### Weekly allocation of DataCap requested
100 TiB

### On-chain address for first allocation
f1pnsnrfp5dqfqwospzj6vis6jxhni765i37tne5q

### Custom multisig
No

### Share a brief history of your project and organization
TIMAGE was founded in 2014 by Mr. Tang Yi, a Chinese celebrity makeup artist. Based on Chinese aesthetics, combined with international makeup trends,  focuses on expressing the smart beauty of Chinese women, creating practical and artistic makeup products.

### Is this project associated with other projects/ecosystem stakeholders?
Yes

### If answered yes, what are the other projects/ecosystem stakeholders
Internet online sales channels.

### Describe the data being stored onto Filecoin
The data stored in Filcoin are all publicly available data from our online channels, advertisements, videos, live broadcasts, customer orders, etc

### Where was the data currently stored in this dataset sourced from
Google Cloud

### If you answered "Other" in the previous question, enter the details here
Mainly from our e-commerce online platform, and  advertising video for product promotion.

### How do you plan to prepare the dataset
others/custom tool

### If you answered "other/custom tool" in the previous question, enter the details here
Tools from the Storage providers

### Please share a sample of the data
https://drive.google.com/file/d/1XHBqkbhm_NwgMy-cjhC91QIk1XPRF4PR/view?usp=sharing
https://drive.google.com/file/d/1GP6vyWfgxplgSJYeonc9SsphfQOLHrz_/view?usp=sharing

### Confirm that this is a public dataset that can be retrieved by anyone on the Network
Yes

### What is the expected retrieval frequency for this data
Yearly

### For how long do you plan to keep this dataset stored on Filecoin
Permanently

### In which geographies do you plan on making storage deals
Asia other than Greater China

### How will you be distributing your data to storage providers
Cloud storage (i.e. S3)

### How do you plan to choose SP
Slack

### If you already have a list of storage providers to work with, fill out their names and provider IDs below
f01834291  f01137150  f01271208 f01852363

### How do you plan to make deals to your storage providers
Others/custom tool

### If you answered "Others/custom tool" in the previous question, enter the details here
Tools from the Storage providers

### Can you confirm that you will follow the Fil+ guideline
Yes

**Comment by Sunnyiscoming** [comment]
https://filplus.d.interplanetary.one/clients?filter=f1pnsnrfp5dqfqwospzj6vis6jxhni765i37tne5q%09
Whether the sps you choose can support data retrieval?
How much data do you have? How many copies will you store?
What's the relationship between you and the organization?

**Comment by Shepherd-7** [comment]
Hello, @Sunnyiscoming 
I am in charge of the fil+ LDN application for "TIMAGE". I have sent KCY email, please check it. We have communicated with selected sps to support data retrieval. "TIMAGE" currently has 3P data, and plans to back up 2-3 copies of data

**Comment by Shepherd-7** [comment]
Because our page was restricted by github, I now create new Issues.

**Comment by Sunnyiscoming** [comment]
Why you use another github handle to answer this question?
If the applicant is not from TIMEGE, please open another application.

**Comment by Shepherd-7** [comment]
> Why you use another github handle to answer this question? If the applicant is not from TIMEGE, please open another application.

Hi @Sunnyiscoming 
 For I applied through this(https://filplus.storage/apply), that's why it shows “data-programs ”. I have confirmed that it was  TIMEGE itself to apply for it and sent the kyc e-mail.

**Comment by Sunnyiscoming** [comment]
Please resend email again. I can not find it in my mailbox.

**Comment by Shepherd-7** [comment]
Hi @Sunnyiscoming  The e-mail has sent to you, please check it. 
![cab6d66d2e456c5d6aa4e75cb588aff](https://user-images.githubusercontent.com/103163034/211476609-2cee232a-54dd-4b30-982e-1bcd6d46a0ef.jpg)

**Comment by cryptowhizzard** [comment]
This address has been involved in fraud.

https://github.com/filecoin-project/filecoin-plus-large-datasets/issues?q=is%3Aissue+f1pnsnrfp5dqfqwospzj6vis6jxhni765i37tne5q

For example:

https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1360

Has been sharing fake data among multiple LDN's .

![Scherm­afbeelding 2023-01-10 om 08 48 43](https://user-images.githubusercontent.com/36404435/211492155-da9bd6d5-8b74-4e56-8733-5ab6dae1c988.png)

No need to get this passed to RKH.

**Comment by simonkim0515** [comment]
## Datacap Request Trigger

#### Total DataCap requested 
> 5PiB

#### Expected weekly DataCap usage rate 
> 100TiB 

#### Client address
> f1pnsnrfp5dqfqwospzj6vis6jxhni765i37tne5q
