### ISSUE TITLE
[DataCap Application] IPFS KOREA

### ISSUE THREAD

**Issue by Metaipfs** [filecoin-project/filecoin-plus-large-datasets#147]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: IPFS KOREA
- Website / Social Media: www.ipfskor.com
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100TiB
- On-chain address for first allocation: f3r5wyvf4nhgbuk72wmvheju5uhur4ifatnorqpkzans2gwup6ehxvzmbie2mtmshdggukaxyekzmgttcqsraa

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
IPFS Korea is founded in 2018, and we have participated in first level and second level test nets too. We built a Main net and Currently owned 27 nodes. Our company is growing into a storage company based on IPFS. We build a large scale of servers and operate storage centers, and provide professional management services. We will stand at the forefront of the fourth industry and try to fulfill our responsibilities and roles to secure Korea's data sovereignty. But we are focusing on high speed sealing. so we are not planning to make storage provider for datacap. 
Moreover, We are expanding our business to NFT, so we will create NFTs and store NFTs (related to K pop, Art, Music, etc.) and we want to store those data in to File Coin Storage. 
```

What is the primary source of funding for this project?
```
NFT Market, Kpop industry, and NFT making company.
```
What other projects/ecosystem stakeholders is this project associated with?
```
Kpop, NFT, Galleries, IPFS KOREA
```

## Use-case details

Describe the data being stored onto Filecoin
```
For NFT.Storage
We are offering storage of all NFT artwork of NFT Market, which should be preserved long term on Filecoin and IPFS to ensure owners of NFTs can continually access the media they own. In the future, we might expand this to serve use cases broader than NFTs (Related to IP, K-pop, etc)
```
Where was the data in this dataset sourced from?
```
South Korea
```
Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
ok! 
![image](https://user-images.githubusercontent.com/96154919/146582061-616b8eb4-6787-4d5a-b453-07050c6469d1.png)
```        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
yes, it is a public data
```
What is the expected retrieval frequency for this data?
```
This type of data is attractive to the general public as aesthetic and entertaining content. So the search frequency is expected to be as high as that of gallery and museum sites. This is the reason why we chose the Filecoin network for storage. We want to retain the data over a longer period of time and provide it to those who need it when they need it.
```
For how long do you plan to keep this dataset stored on Filecoin?
```
I think it's a permanent archive and we'll constantly update our data stored on Filecoin.
```
## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
All around Asia, but mostly in South Korea. 
```
How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
We will use online transfer to distribute our data at first. If there is any abnormality, we probably resort to offline transfer. We do have an offline data transfer system.
```
How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We will select miners through miners reputation systems like filrep.io, or Filecoin blockchain explorers. 
```
How will you be distributing deals across storage providers?
```
As we have a large amount of data, I think we better use offline transfer. but we do know both way so we can use both on-line and off-line transfer. 
```
Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Currently, One NFT market company is waiting for this deals. They have more than 250 artists and NFT artworks. Also, We have connection with NFT, Metaverse flatform companies (Related to K pop entertainment, Games). Also they want to start making deals as soon as possible. So, we can make a deal with those companies too.  
```

**Comment by Metaipfs** [comment]
I already granted DataCap(FYI issue #69), but because of Github account problem. I newly uploaded same application, with a new account.  
Hopefully I could get Datacap ASAP.. I really need second allocation, because I already made a contract with NFT companies. 

@galen-mcandrew 
@dkkapur 
@MegTei

**Comment by dkkapur** [comment]
Hi folks - just wanted to flag that @Metaipfs was in touch with the ecosystem team in Asia and confirmed the following details:
- deal making has already started, https://filplus.d.interplanetary.one/clients/f01404557
- initial DataCap application was approved, but GitHub issue was lost when account was blocked, so this is an attempt to get a new LDN up and running
- data onboarding work with NFT projects is already underway, but is blocked given no DataCap availability

@Metaipfs - I see that the first round of DataCap was used in about ~2157 deals. Can you share more about how you are selecting your Storage Providers, since right now your top allocation is >30% to one miner ID, which is higher than what Fil+ typically supports (at most 20% to one ID, ideally closer to 5%)? 

Separately, @galen-mcandrew @fabriziogianni7 @ialberquilla - might be an opportunity to explore porting existing LDNs to new GitHub Issues rather than having to create a new one.

**Comment by Metaipfs** [comment]
@dkkapur 
At first time, we were not sure about the way we put real data in to miners. So we kept send data to same miners. From that we made stable program to allocate data into other miners. We selected miners located in korea, has good and high reputation through filrep.io.  I didn't know that our company should distribute datacap to more various miners. I will tell tech team to distribute DC to more diverse miners. 

Our Standard in selecting miners 
Location : Asia / Especially in Korea (available to make offline deal)
Reputation : according to filrep.io, higher than 90

**Comment by Metaipfs** [comment]
![image](https://user-images.githubusercontent.com/96154919/147216771-63250f00-ff99-40c3-93c2-74ba9c0b1db3.png)

**Comment by KwrayFF** [comment]
## Multisig Notary requested
#### Total DataCap requested 
> 5PiB
#### Expected weekly DataCap usage rate 
> 100TiB

**Comment by Reiers** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebqnyejgfgrju7sobrnjojdujj5ent75rwa6neeocda2if55s772e 
#### Address 
> f3r5wyvf4nhgbuk72wmvheju5uhur4ifatnorqpkzans2gwup6ehxvzmbie2mtmshdggukaxyekzmgttcqsraa
#### Datacap Allocated
> 50TiB
#### Signer Address
> f1oz43ckvmtxmmsfzqm6bpnemqlavz4ifyl524chq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebqnyejgfgrju7sobrnjojdujj5ent75rwa6neeocda2if55s772e

**Comment by Metaipfs** [comment]
So, do I need one more notary to sign for allocation?

**Comment by Metaipfs** [comment]
@dkkapur 
@galen-mcandrew  
I promote  this application to Slack #fil-plus channel several times. But still I need one more notary to sign for this. 
Is there any other way to get one more sign?

**Comment by MegTei** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebdspmv2zfejsm4gmwqnshlzxlbq63p2nllxucfthyus55fa3llzs 
#### Address 
> f3r5wyvf4nhgbuk72wmvheju5uhur4ifatnorqpkzans2gwup6ehxvzmbie2mtmshdggukaxyekzmgttcqsraa
#### Datacap Allocated
> 50TiB
#### Signer Address
> f1ystxl2ootvpirpa7ebgwl7vlhwkbx2r4zjxwe5i
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebdspmv2zfejsm4gmwqnshlzxlbq63p2nllxucfthyus55fa3llzs

**Comment by MegTei** [comment]
@Metaipfs Should be sorted for you now

**Comment by KoreaHerald** [comment]
@MegTei  Thank you 🙏

**Comment by Metaipfs** [comment]
Thank you for allocation. Btw I've used up over 80% of allocated datacap, so can I request for next datacap allocation? (100TiB)

**Comment by Metaipfs** [comment]
@Reiers @MegTei  @Kevin-FF-USA 
@IreneYoung @rayshitou @dannyob @TimWilliams00 @ozhtdong @Fenbushi-Filecoin @swatchliu @XnMatrixSV 
Could you help me with datacap allocation?

**Comment by IreneYoung** [comment]
Hello can I understand that you will making storage deals for some NFT NFT Markets, Kpop industry, and NFT making companies as a Filecoin storage intermediary. For now, the DataCap you requested is mainly for the data storage of other entities, rather than your organization, for example, the NFT market https://www.parula.io/. Is that right?

If so, regarding the data you intend to store, we need to confirm with you about the original source of those data, and do you have any proof of the ownership or any authorization? Thanks.

**Comment by Metaipfs** [comment]
Yes, that's right. 
We store nft markets and kpop industry related data. 
For this part, our company have signed contract with each company, and I can show you the contract, which is in Korean. If you want me to send you a translation, I'll do that. 
But since korean new years day is began. Everyone doesn't go to work until next week. 
I'll get the data on that part as soon as possible and post it into comment.

**Comment by IreneYoung** [comment]
> @IreneYoung Yes, that's right. We store nft markets and kpop industry related data. For this part, our company have signed contract with each company, and I can show you the contract, which is in Korean. If you want me to send you a translation, I'll do that. But since korean new years day is began. Everyone doesn't go to work until next week. I'll get the data on that part as soon as possible and post it into comment.

Yes, it would be great if you can show us the signed contract, even in Korean is OK.

**Comment by Metaipfs** [comment]
[data_contract.pdf](https://github.com/filecoin-project/filecoin-plus-large-datasets/files/8020296/data_contract.pdf)
This is one of our signed contract. :) we have used same form of contract for each company.

**Comment by IreneYoung** [comment]
> @IreneYoung [data_contract.pdf](https://github.com/filecoin-project/filecoin-plus-large-datasets/files/8020296/data_contract.pdf) This is one of our signed contract. :) we have used same form of contract for each company.

Gotcha! Thanks for cooperation!

**Comment by Metaipfs** [comment]
@IreneYoung
Thank you, hope you can allocate Datacap for our company now :)

**Comment by IreneYoung** [comment]
Hey @Metaipfs - Surely I’d love to support but now the status label is showing in a “verifying” stage. When it get “readyToSign”, then I will sign for you with pleasure.

I learned from the document that: (1) the right holder licensed your company IPFS Korea the relevant copyrights in accordance with [Article 2] of the agreement which shall go into force from October 14, 2021 to 540 days thereafter. (2) It is restricted to grant the right to a third party with the exception of Protocol Labs and Filecoin Foundation. 

For that matter, as storage providers are individuals or entities which not part of Protocol Labs or Filecoin Foundation, I'm not sure whether the SPs you making deals with are supposed to shall get the rights granted by the right holders to process and store the data?

I don’t know much about the legitimacy issue. Hence, I suggest you interpret the data contract into English and share it here with governance team and other notaries. Specifically, the parts in great need of the English translation are: [Article 2], [Artical 4 - (3)],  [Article 12]

Looking forward to your reply. Thanks very much!

**Comment by Metaipfs** [comment]
@galen-mcandrew Could you  check this application's status label please? It needs to be labelled to “readyToSign”

**Comment by Metaipfs** [comment]
@IreneYoung 
Okay Thank you :) 
Will post you English translation of : [Article 2], [Artical 4 - (3)], [Article 12]
[Translation of Articles.pdf](https://github.com/filecoin-project/filecoin-plus-large-datasets/files/8030955/Translation.of.Articles.pdf)

At this moment (Oct, 2021)  we didn't think SPs are not part of Protocol Labs or Filecoin Foundation. But it is right that in legitimacy issue it can be a problem. However we didn't have specific Article that allows SPs to also have right for those data. 
But fortunatley our clients were aware of this point, and didn't thought of this issue as a problem. So we made Appendix #1 and going to recieve official sign for that. Will post you that appendix too. (I think appendix will be able to posted tomorrow.)

**Comment by Metaipfs** [comment]
> ## Stats for DataCap Allocation
> #### Multisig Notary address
> > f01646655
> 
> #### Client address
> > f3r5wyvf4nhgbuk72wmvheju5uhur4ifatnorqpkzans2gwup6ehxvzmbie2mtmshdggukaxyekzmgttcqsraa
> 
> #### Last two approvers
> > **MegTei** & **Reiers**
> 
> #### DataCap allocation requested
> > 100TiB
> 
> #### **[Stats](https://filplus.d.interplanetary.one/clients?filter=f01404557)**
> Number of deals	Number of storage providers	Previous DC Allocated	Top provider	Remaining DC
> 727	17	50TiB	17.12	9.0TiB

**Comment by Metaipfs** [comment]
@IreneYoung 
[scanned_appendix.pdf](https://github.com/filecoin-project/filecoin-plus-large-datasets/files/8037188/scanned_appendix.pdf)

here's one of signed Appendix :)

**Comment by IreneYoung** [comment]
Great job! I went through the contract and the appendix. I'm OK with this issue. @galen-mcandrew @Kevin-FF-USA

**Comment by galen-mcandrew** [comment]
Looks like the parent comment was edited, which then changes the labels. @fabriziogianni7 , can you help us look into the [logs](https://plus.fil.org/logs) here? Seeing some errors when trying to sign, and now SA bot looks like it's hitting an error.

Checking lotus for f01646655, not seeing any transactions, which matches that there were no signatures from the SA post 21 days ago. 

I can manually change label to readyToSign, but let's also investigate what the SA bot is encountering.

**Comment by Metaipfs** [comment]
Thank you 😀 @galen-mcandrew 
@IreneYoung  now status has changed!

**Comment by IreneYoung** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced7gj2ar4g3t2ilfpl72je2cwkqpgnaa7bivx7nj67scclp5h7y74 
#### Address 
> f3r5wyvf4nhgbuk72wmvheju5uhur4ifatnorqpkzans2gwup6ehxvzmbie2mtmshdggukaxyekzmgttcqsraa
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1d4gmpqz3execjj2wvrxuuhvbms5mzh7t7yqrviq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced7gj2ar4g3t2ilfpl72je2cwkqpgnaa7bivx7nj67scclp5h7y74

**Comment by Reiers** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebs7pwwiuqbupo7oeyrsd3cdrm4i553clbnymvo2fp4wgxebuz5he 
#### Address 
> f3r5wyvf4nhgbuk72wmvheju5uhur4ifatnorqpkzans2gwup6ehxvzmbie2mtmshdggukaxyekzmgttcqsraa
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1oz43ckvmtxmmsfzqm6bpnemqlavz4ifyl524chq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebs7pwwiuqbupo7oeyrsd3cdrm4i553clbnymvo2fp4wgxebuz5he

**Comment by MegTei** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedhlqwc7wcxtyxm7nuvwly2uwc3ca2yhnetl4ytbfauhevtlufiks 
#### Address 
> f3r5wyvf4nhgbuk72wmvheju5uhur4ifatnorqpkzans2gwup6ehxvzmbie2mtmshdggukaxyekzmgttcqsraa
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1ystxl2ootvpirpa7ebgwl7vlhwkbx2r4zjxwe5i
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedhlqwc7wcxtyxm7nuvwly2uwc3ca2yhnetl4ytbfauhevtlufiks

**Comment by IreneYoung** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedj34rcxgxlfhwfepyss2gyfqffw2zpkod4zdgkcxrvaodir44sgg 
#### Address 
> f3r5wyvf4nhgbuk72wmvheju5uhur4ifatnorqpkzans2gwup6ehxvzmbie2mtmshdggukaxyekzmgttcqsraa
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1d4gmpqz3execjj2wvrxuuhvbms5mzh7t7yqrviq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedj34rcxgxlfhwfepyss2gyfqffw2zpkod4zdgkcxrvaodir44sgg

**Comment by Metaipfs** [comment]
@Eric @TimWilliams @DarnellWashington @FenbushiCapital @WijnandSchouten @XnMatrix @DannyO'brien @JulianNOEL @IreneYoung @EmmaRussell @Holon Innovations 
Hope life is treating you well! Can I please be updated with the issue of further datacap allocation? I've been waiting patiently up until this point and I'd like to know what's holding on your end. Thank you so much.

**Comment by filplus-checker** [comment]
## DataCap and CID Checker Report[^1]
 - Organization: `IPFS KOREA`
 - Client: `f3r5wyvf4nhgbuk72wmvheju5uhur4ifatnorqpkzans2gwup6ehxvzmbie2mtmshdggukaxyekzmgttcqsraa`
### Storage Provider Distribution
The below table shows the distribution of storage providers that have stored data for this client.

If this is the first time a provider takes verified deal, it will be marked as `new`.

For most of the datacap application, below restrictions should apply.
 - Storage provider should not exceed 25% of total datacap.
 - Storage provider should not be storing duplicate data for more than 20%.
 - Storage provider should have published its public IP address.
 - All storage providers should be located in different regions.

⚠️ [f01690631](https://filfox.info/en/address/f01690631) has unknown IP location.

⚠️ [f01660052](https://filfox.info/en/address/f01660052) has unknown IP location.

⚠️ [f01136592](https://filfox.info/en/address/f01136592) has unknown IP location.

⚠️ [f01654478](https://filfox.info/en/address/f01654478) has unknown IP location.

⚠️ [f01654220](https://filfox.info/en/address/f01654220) has unknown IP location.

⚠️ 62.13% of total deal sealed by [f01472022](https://filfox.info/en/address/f01472022) are duplicate data.

⚠️ 66.14% of total deal sealed by [f01516894](https://filfox.info/en/address/f01516894) are duplicate data.

⚠️ [f01516894](https://filfox.info/en/address/f01516894) has unknown IP location.

⚠️ 92.26% of total deal sealed by [f01279864](https://filfox.info/en/address/f01279864) are duplicate data.

⚠️ 96.94% of total deal sealed by [f0165375](https://filfox.info/en/address/f0165375) are duplicate data.

⚠️ [f062318](https://filfox.info/en/address/f062318) has unknown IP location.

⚠️ [f01776341](https://filfox.info/en/address/f01776341) has unknown IP location.

⚠️ 96.67% of total deal sealed by [f0482619](https://filfox.info/en/address/f0482619) are duplicate data.

⚠️ [f0482619](https://filfox.info/en/address/f0482619) has unknown IP location.

⚠️ 94.69% of total deal sealed by [f01474735](https://filfox.info/en/address/f01474735) are duplicate data.

⚠️ [f01474735](https://filfox.info/en/address/f01474735) has unknown IP location.

⚠️ [f01694564](https://filfox.info/en/address/f01694564) has unknown IP location.

⚠️ [f01690643](https://filfox.info/en/address/f01690643) has unknown IP location.

⚠️ [f01780739](https://filfox.info/en/address/f01780739) has unknown IP location.

⚠️ [f01690781](https://filfox.info/en/address/f01690781) has unknown IP location.

⚠️ [f0752695](https://filfox.info/en/address/f0752695) has unknown IP location.

⚠️ 36.36% of total deal sealed by [f0157564](https://filfox.info/en/address/f0157564) are duplicate data.

⚠️ [f0157564](https://filfox.info/en/address/f0157564) has unknown IP location.

| Provider                                                    |                     Location | Total Deals Sealed | Percentage | Unique Data | Duplicate Deals |
| :---------------------------------------------------------- | ---------------------------: | -----------------: | ---------: | ----------: | --------------: |
| [f01690631](https://filfox.info/en/address/f01690631)`new`  |                      Unknown |          26.63 TiB |     22.16% |   26.63 TiB |           0.00% |
| [f01660052](https://filfox.info/en/address/f01660052)`new`  |                      Unknown |          20.75 TiB |     17.27% |   20.75 TiB |           0.00% |
| [f01136592](https://filfox.info/en/address/f01136592)`new`  |                      Unknown |          16.69 TiB |     13.89% |   15.64 TiB |           6.27% |
| [f01654478](https://filfox.info/en/address/f01654478)       |                      Unknown |          13.78 TiB |     11.47% |   13.78 TiB |           0.00% |
| [f01654220](https://filfox.info/en/address/f01654220)       |                      Unknown |          11.53 TiB |      9.60% |   11.53 TiB |           0.00% |
| [f01472022](https://filfox.info/en/address/f01472022)`new`  |             Seoul, Seoul, KR |           8.33 TiB |      6.93% |    3.15 TiB |          62.13% |
| [f01516894](https://filfox.info/en/address/f01516894)`new`  |                      Unknown |           8.15 TiB |      6.78% |    2.76 TiB |          66.14% |
| [f01279864](https://filfox.info/en/address/f01279864)`new`  | Seongnam-si, Gyeonggi-do, KR |           6.56 TiB |      5.46% |  520.31 GiB |          92.26% |
| [f0165375](https://filfox.info/en/address/f0165375)`new`    | Seongnam-si, Gyeonggi-do, KR |           1.79 TiB |      1.49% |   56.00 GiB |          96.94% |
| [f062318](https://filfox.info/en/address/f062318)`new`      |                      Unknown |           1.19 TiB |      0.99% |    1.19 TiB |           0.00% |
| [f01776341](https://filfox.info/en/address/f01776341)`new`  |                      Unknown |         960.00 GiB |      0.78% |  960.00 GiB |           0.00% |
| [f0482619](https://filfox.info/en/address/f0482619)         |                      Unknown |         960.00 GiB |      0.78% |   32.00 GiB |          96.67% |
| [f01474735](https://filfox.info/en/address/f01474735)`new`  |                      Unknown |         904.00 GiB |      0.73% |   48.00 GiB |          94.69% |
| [f01694564](https://filfox.info/en/address/f01694564)`new`  |                      Unknown |         512.00 GiB |      0.42% |  512.00 GiB |           0.00% |
| [f01690643](https://filfox.info/en/address/f01690643)`new`  |                      Unknown |         480.00 GiB |      0.39% |  480.00 GiB |           0.00% |
| [f01780739](https://filfox.info/en/address/f01780739)`new`  |                      Unknown |         448.00 GiB |      0.36% |  448.00 GiB |           0.00% |
| [f01690781](https://filfox.info/en/address/f01690781)`new`  |                      Unknown |         224.00 GiB |      0.18% |  224.00 GiB |           0.00% |
| [f0752695](https://filfox.info/en/address/f0752695)`new`    |                      Unknown |         224.00 GiB |      0.18% |  224.00 GiB |           0.00% |
| [f0157564](https://filfox.info/en/address/f0157564)`new`    |                      Unknown |         176.00 GiB |      0.14% |  112.00 GiB |          36.36% |

![Provider Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/147/1671092655898.png)
### Deal Data Replication
The below table shows how each many unique data are replicated across storage providers.
- No more than 25% of unique data are stored with less than 4 providers.

⚠️ 84.85% of deals are for data replicated across less than 4 storage providers.

| Unique Data Size | Total Deals Made | Number of Providers | Deal Percentage |
| ---------------: | ---------------: | ------------------: | --------------: |
|        96.75 TiB |        97.12 TiB |                   1 |          80.82% |
|       904.00 GiB |         3.92 TiB |                   2 |           3.26% |
|        48.00 GiB |       944.00 GiB |                   3 |           0.77% |
|         8.00 GiB |       256.00 GiB |                   4 |           0.21% |
|         8.00 GiB |         3.83 TiB |                   5 |           3.19% |
|        40.00 GiB |        14.13 TiB |                   6 |          11.75% |

![Replication Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/147/1671092656363.png)
### Deal Data Shared with other Clients
The below table shows how many unique data are shared with other clients.
Usually different applications owns different data and should not resolve to the same CID.

⚠️ CID sharing has been observed.

| Other Client                                                                                                                                                                                                              | Application                                                                                               | Total Deals Affected | Unique CIDs |          Verifier |
| :------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ | :-------------------------------------------------------------------------------------------------------- | -------------------: | ----------: | ----------------: |
| [f3sqnbeqqvaxyqlt56zls4viihpg5v3uykayqw5ir<br/>npbk6zbuds4dz6reeiud6eezp2dil5qbhvavbyhyd<br/>kv6a](https://filfox.info/en/address/f3sqnbeqqvaxyqlt56zls4viihpg5v3uykayqw5irnpbk6zbuds4dz6reeiud6eezp2dil5qbhvavbyhydkv6a) | [LG Whisen Dong\-an Service](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/114) |            62.16 TiB |       1,018 |         LDN # 114 |
| [f3vila4wx2vahcfzui3pkq3qth6eqo5haemnullch<br/>vwljeafz35nso4tld63qtweqws4si3zahdtyh4zjm<br/>r7gq](https://filfox.info/en/address/f3vila4wx2vahcfzui3pkq3qth6eqo5haemnullchvwljeafz35nso4tld63qtweqws4si3zahdtyh4zjmr7gq) | [Pharos Consulting](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/115)          |            15.69 TiB |         467 |   LDN v3 multisig |
| [f3sgm5o6tvtszct56ag2m7iqe5uhn4fzrf5skmjdu<br/>rmap3po2amqnqohrell6kipp74amnxn2olohgb3pd<br/>triq](https://filfox.info/en/address/f3sgm5o6tvtszct56ag2m7iqe5uhn4fzrf5skmjdurmap3po2amqnqohrell6kipp74amnxn2olohgb3pdtriq) | Unknown                                                                                                   |           672.00 GiB |          21 |           Unknown |
| [f3vfqb7comvrd36wk745dpy42xmnbiqghl3ndexis<br/>dejma53tkegrqmrtun5uw3yyiove7iql6zmcr44w7<br/>z3ha](https://filfox.info/en/address/f3vfqb7comvrd36wk745dpy42xmnbiqghl3ndexisdejma53tkegrqmrtun5uw3yyiove7iql6zmcr44w7z3ha) | `Glif auto verified`                                                                                      |            64.00 GiB |           1 | Jonathan Schwartz |
| [f3v7acvitagfyfhwdedorx4rv2kn7d7px2mdvg4w5<br/>btsmdkweknc6zg33mqjdoiyklaiitw7gxsw66yfzi<br/>xpwa](https://filfox.info/en/address/f3v7acvitagfyfhwdedorx4rv2kn7d7px2mdvg4w5btsmdkweknc6zg33mqjdoiyklaiitw7gxsw66yfzixpwa) | `King Enterprise`                                                                                         |            32.00 GiB |           1 |            Neo Ge |
| [f3rxmx43tn5sfocd7pdyqhfrotfema2jwfe3nh4ht<br/>i2m4jtqwz7w3rwf2xofh262iwgiihhi2lgiiqx5fn<br/>zchq](https://filfox.info/en/address/f3rxmx43tn5sfocd7pdyqhfrotfema2jwfe3nh4hti2m4jtqwz7w3rwf2xofh262iwgiihhi2lgiiqx5fnzchq) | Unknown                                                                                                   |            20.00 GiB |           1 |           Unknown |
| [f3uarqwxptcskoyjwaf5dykmrjswjecyjlkadtcgo<br/>3tos6z3fwkl5fnrke7lb6koezazmqns7ji2azrubt<br/>73fa](https://filfox.info/en/address/f3uarqwxptcskoyjwaf5dykmrjswjecyjlkadtcgo3tos6z3fwkl5fnrke7lb6koezazmqns7ji2azrubt73fa) | Unknown                                                                                                   |           706.00 MiB |           3 |           Unknown |
| [f1sm4vru5k3jnbg4me7ymo2r2zc3fqc2pu57tuijq](https://filfox.info/en/address/f1sm4vru5k3jnbg4me7ymo2r2zc3fqc2pu57tuijq)                                                                                                     | `Glif auto verified`                                                                                      |             6.00 MiB |           1 | Jonathan Schwartz |

[^1]: To manually trigger this report, add a comment with text `checker:manualTrigger`

**Comment by aliensero** [comment]
checker:manualTrigger
