### ISSUE TITLE
Shenzhen Qiancheng Shangpin Jewelry Co., LTD

### ISSUE THREAD

**Issue by mike202223** [filecoin-project/filecoin-plus-large-datasets#1470]
### Data Owner Name

Shenzhen Qiancheng Shangpin Jewelry Co., LTD

### Data Owner Country/Region

China

### Data Owner Industry

Other

### Website

www.gocoring.com

### Social Media

```text
https://weibo.com/u/6393801150
http://xhslink.com/XFQWWl
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

200TiB

### On-chain address for first allocation

f172ifpx4b2ivjc3mov3busnuzyhqgedqlfqetzfq

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
The GOCO brand was born in 2017. GOCO has opened physical stores in Ningbo, Wuhan, and Yinchuan. It adheres to the brand proposition of "permanent engraving of promises—exclusive and unique GOCO diamond rings." It draws inspiration from European culture and combines the results of intensive research on aesthetic design and modern craftsmanship. Constantly create an elegant yet fashionable style in the field of jewelry, and devote ourselves to providing high-quality products and services for more noble, elegant, light and familiar consumers with a better life. Through personalized jewelry, convey the attitude towards life that is expressed with heart and experienced with love .
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
Design drafts of GOCO brand designers, pictures and videos of GOCO jewelry; Photos and videos of GOCO's events,
GOCO promotional materials, GOCO customer maintenance data, etc.
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### How do you plan to prepare the dataset

IPFS, singularity, graphsplit

### Please share a sample of the data

```text
A1 Video
https://drive.google.com/drive/folders/1a2Zd_wLDIC1EaZYXNQjijyn-PTJMBD19?usp=sharing
B1 picture
https://drive.google.com/drive/folders/16ewGDths3dj8nFjJVefE7KiGJ4lGBI6P?usp=share_link
C1 written words
https://drive.google.com/drive/folders/1OY6-WG8fxl-GT7fPyg2VTnI4YHWrnmZs?usp=share_link
D Shop Picture
https://drive.google.com/drive/folders/1acH28igQMqhRmO93VwqZ1b9ixLjyMBPj?usp=share_link
E design
https://drive.google.com/drive/folders/18ARgdEeH9m_oDkKwGi4YjgfbqTcvx3i_?usp=share_link
F Activities
https://drive.google.com/drive/folders/1ItLtOgCSjeBEjS_68rhbFJI2Rp3C3MyX?usp=share_link
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

1.5 to 2 years

### In which geographies do you plan on making storage deals

Asia other than Greater China, North America, Europe

### How will you be distributing your data to storage providers

HTTP or FTP server, Shipping hard drives

### How do you plan to choose storage providers

Slack, Filmine, Big data exchange

### If you already have a list of storage providers to work with, fill out their names and provider IDs below

```text
f01497836
f01672748
f01474838
f0838684
f0707721
f0838852
```

### How do you plan to make deals to your storage providers

Boost client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 200TiB

**Client address**

> f172ifpx4b2ivjc3mov3busnuzyhqgedqlfqetzfq

**Comment by mike202223** [comment]
Hello, I'm sorry for the long delay. Do I need to provide more information to get the support of notaries?

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Looking at your application i have some questions:
As you are brand new on Github and have no history of past applications it seems to me that applying for 5PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?

Can you show us visible proof of the size of your data and the storage systems you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230337462961356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!

**Comment by xiaoyuaiheshui** [comment]
1. Can you answer the question mentioned above by @cryptowhizzard ：Can you show us visible proof of the size of your data and the storage systems you have there?
2. I don't agree with the novice problem mentioned by @cryptowhizzard . Filecoin also needs a lot of fresh blood. If you have any data packaging or distribution problems, I'm happy to help you.
3. Could you send an email to filplus-app-review@fil.org with your official domain in order to confirm your identity? Email name should includes the issue id #1470

**Comment by mike202223** [comment]
About the data:
![109731676274694_ pic](https://user-images.githubusercontent.com/116071203/218652510-081411aa-115d-41c0-8136-9fb0926448ae.jpg)
The confirmation email has been sent:
![801676354354_ pic](https://user-images.githubusercontent.com/116071203/218652546-f049556c-05ca-4454-967a-57b0e579c82f.jpg)

**Comment by xiaoyuaiheshui** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacea376mithmp2mivaatbft435tyo7rv4lu5x6rp5sfv6wazpedk5ou 
#### Address 
> f172ifpx4b2ivjc3mov3busnuzyhqgedqlfqetzfq
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f122qmy25wdtt5mxd77kndiq7z5x2n3iwiuz2wdsa
#### Id
> b1bd89a8-8f5a-40c4-96cf-4559fb04ea35
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacea376mithmp2mivaatbft435tyo7rv4lu5x6rp5sfv6wazpedk5ou

**Comment by stcouldlisa** [comment]
I received your request, but I hope you can provide more than 4 sp first.

**Comment by mike202223** [comment]
@stcouldlisa At present, we have reached preliminary cooperation with the following SP: f01153105, f01660795, f01907578, f01161245

**Comment by herrehesse** [comment]
@mike202223 Thank you for letting us know which SP's. Now i'd like to know the following about each:

**City, Business name and region.**

Thank you.

**Comment by mike202223** [comment]
@herrehesse Can I count on your support? I would really appreciate it!

**Comment by herrehesse** [comment]
Thank you @mike202223 for this. I have a lot of questions about the validity of your data, about the replications and about the entity doing the packing/distribution. But, willing to support a first round to prove yourself as a good actor.

Did you fill in the KYC from @cryptowhizzard ? If yes, then we can try a first allocation.

**Comment by mike202223** [comment]
@herrehesse  I've forgotten. But I will submit the form again if you want.

**Comment by mike202223** [comment]
Finish

**Comment by cryptowhizzard** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecf6tt3ojplqfcguinojjjebzvlaoiza6uawbtov7dsichl2sixvy 
#### Address 
> f172ifpx4b2ivjc3mov3busnuzyhqgedqlfqetzfq
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1krmypm4uoxxf3g7okrwtrahlmpcph3y7rbqqgfa
#### Id
> b1bd89a8-8f5a-40c4-96cf-4559fb04ea35
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecf6tt3ojplqfcguinojjjebzvlaoiza6uawbtov7dsichl2sixvy

**Comment by mike202223** [comment]
@cryptowhizzard @herrehesse @xiaoyuaiheshui Thanks for your support!

**Comment by mike202223** [comment]
checker:manualTrigger

**Comment by kernelogic** [comment]
Retrieval successful, distribution looks healthy.
<img width="988" alt="image" src="https://user-images.githubusercontent.com/3711825/225219881-89d29b24-0a74-4459-9004-e80a25de117c.png">

**Comment by kernelogic** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceacd7iuw2v2wousn72btxunjvx2tau4w6h4hifwz3cjkt23eckbs4 
#### Address 
> f172ifpx4b2ivjc3mov3busnuzyhqgedqlfqetzfq
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### Id
> 97b00598-3dfa-4e4c-9851-fe502f1d4d21
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceacd7iuw2v2wousn72btxunjvx2tau4w6h4hifwz3cjkt23eckbs4

**Comment by laurarenpanda** [comment]
checker:manualTrigger

**Comment by laurarenpanda** [comment]
The checker report looks great!
Willing to support this round.
Hope to see more SPs in different regions join in.

**Comment by laurarenpanda** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec3y7sy2kt7h4zhx43mpkvywxsxkoylure3bolm24nlzrl6nbu7wo 
#### Address 
> f172ifpx4b2ivjc3mov3busnuzyhqgedqlfqetzfq
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1bp3tzp536edm7dodldceekzbsx7zcy7hdfg6uzq
#### Id
> 97b00598-3dfa-4e4c-9851-fe502f1d4d21
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec3y7sy2kt7h4zhx43mpkvywxsxkoylure3bolm24nlzrl6nbu7wo

**Comment by a1991car** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedcdfx3bd7u2ctv2xrgirjgi4ohflgfo5cbkiphumtrj45pso46bg 
#### Address 
> f172ifpx4b2ivjc3mov3busnuzyhqgedqlfqetzfq
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1qnumecdypgrbaebtkdfjnwt5ndacadcuas3deiq
#### Id
> 33e7c5e8-c0b4-4114-a8c5-89833d213773
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedcdfx3bd7u2ctv2xrgirjgi4ohflgfo5cbkiphumtrj45pso46bg

**Comment by a1991car** [comment]
![微信图片_20230317173719](https://user-images.githubusercontent.com/32447611/225869226-69289561-d25a-4f0b-8f5d-552bccd6faa0.jpg)

**Comment by Tom-OriginStorage** [comment]
checker:manualTrigger

**Comment by Tom-OriginStorage** [comment]
<img width="1094" alt="image" src="https://user-images.githubusercontent.com/103015469/226262401-641931d4-0314-466a-affb-6684155d2bb9.png">

**Comment by Tom-OriginStorage** [comment]
View the packaging report, which is relatively healthy. After inspection, the data can be retrieved normally. Willing to support this round

**Comment by Tom-OriginStorage** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebyybgdsggxtbefqf6veuthwr2utjaqlz6muixbkttzxtpr77eu62 
#### Address 
> f172ifpx4b2ivjc3mov3busnuzyhqgedqlfqetzfq
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1q6bpjlqia6iemqbrdaxr2uehrhpvoju3qh4lpga
#### Id
> 33e7c5e8-c0b4-4114-a8c5-89833d213773
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebyybgdsggxtbefqf6veuthwr2utjaqlz6muixbkttzxtpr77eu62

**Comment by mike202223** [comment]
checker:manualTrigger

**Comment by kernelogic** [comment]
I have performed DD before and this time around the CID report looks good too.

**Comment by kernelogic** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceceavftkghvarb63lq3tylhttfhkiu3grwwgxemsivt5dyg6a2x2o 
#### Address 
> f172ifpx4b2ivjc3mov3busnuzyhqgedqlfqetzfq
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceceavftkghvarb63lq3tylhttfhkiu3grwwgxemsivt5dyg6a2x2o

**Comment by Fatman13** [comment]
checker:manualTrigger

**Comment by maxvint** [comment]
<img width="1216" alt="image" src="https://user-images.githubusercontent.com/1715211/229025616-0fd872c8-7f1f-4ffc-90b7-8e7dddb3c19c.png">
<img width="1208" alt="image" src="https://user-images.githubusercontent.com/1715211/229025631-acceb3a1-9677-4220-988f-758cee037f6b.png">

Cool, data distribution and retrieval looks good, willing to support.

**Comment by maxvint** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebxnh57li5fq6h22hkig2p27g3ozrtldvatdcbxvbrer6v4totmqi 
#### Address 
> f172ifpx4b2ivjc3mov3busnuzyhqgedqlfqetzfq
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1ui5iy4mmkxjbw7752omiwp2ols2fzv4thrayagi
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebxnh57li5fq6h22hkig2p27g3ozrtldvatdcbxvbrer6v4totmqi

**Comment by 1ane-1** [comment]
checker:manualTrigger

**Comment by 1ane-1** [comment]
![b4d953ee746072af53899963ccc6830a](https://user-images.githubusercontent.com/91301211/236104289-002bdbf7-7a32-4734-8221-962bff62543e.png)

**Comment by 1ane-1** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecd5nzwcme6xnohu4o24fjn4o62h4m6e5wp7pirzv5o3yblncnke2 
#### Address 
> f172ifpx4b2ivjc3mov3busnuzyhqgedqlfqetzfq
#### Datacap Allocated
> 1.56PiB
#### Signer Address
> f1mdk7s2vntzm6hu35yuo6vjubtrpfnb2awhgvrri
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecd5nzwcme6xnohu4o24fjn4o62h4m6e5wp7pirzv5o3yblncnke2

**Comment by NDLABS-OFFICE** [comment]
The check bot displays well, and the node supports retrieval and is willing to support

**Comment by NDLABS-OFFICE** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb6dxlrtyv3d34wqmturvrg7qro2dikwcfq55bamgf2uimscifmsm 
#### Address 
> f172ifpx4b2ivjc3mov3busnuzyhqgedqlfqetzfq
#### Datacap Allocated
> 1.56PiB
#### Signer Address
> f1yayfsv6whu3rheviucvventj3y6t542xfpb47ei
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb6dxlrtyv3d34wqmturvrg7qro2dikwcfq55bamgf2uimscifmsm

**Comment by maxvint** [comment]
checker:manualTrigger

**Comment by igoovo** [comment]
checker:manualTrigger

**Comment by igoovo** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedoiiw42r5tgwr5m5khmy7exhnk6whelwhjqigc6gvkane3yxstao 
#### Address 
> f172ifpx4b2ivjc3mov3busnuzyhqgedqlfqetzfq
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1shnsfayxqll77svffaxnjenms7bbbysbqcatrpy
#### Id
> 013189c4-5107-4bbd-a54c-92ee7d7f7d04
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedoiiw42r5tgwr5m5khmy7exhnk6whelwhjqigc6gvkane3yxstao

**Comment by igoovo** [comment]
All the indicators look normal, and I support this round.

**Comment by 1ane-1** [comment]
From the report, it looks everything good. Support !

**Comment by 1ane-1** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceducxzryblxyte2zwgz2cbd6vnlmi5mxmopg7rx62oetecrcre5ti 
#### Address 
> f172ifpx4b2ivjc3mov3busnuzyhqgedqlfqetzfq
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1mdk7s2vntzm6hu35yuo6vjubtrpfnb2awhgvrri
#### Id
> 013189c4-5107-4bbd-a54c-92ee7d7f7d04
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceducxzryblxyte2zwgz2cbd6vnlmi5mxmopg7rx62oetecrcre5ti

**Comment by clriesco** [comment]
Removed stale label and reopened issue :)
