### ISSUE TITLE
Shenzhen Rule Culture and Sports Communication Co., LTD

### ISSUE THREAD

**Issue by persia2022** [filecoin-project/filecoin-plus-large-datasets#1471]
### Data Owner Name

Shenzhen Rule Culture and Sports Communication Co., LTD

### Data Owner Country/Region

China

### Data Owner Industry

Information, Media & Telecommunications

### Website

www.worlddiamond.com.cn

### Social Media

```text
Here are some of our co-artists
RED:
https://www.xiaohongshu.com/user/profile/54e555882e1d933298d00c7a?xhsshare=CopyLink&appuid=5fb0152e00000000010098cd&apptime=1671183378
https://www.xiaohongshu.com/user/profile/5984d3d850c4b429c5466a76?xhsshare=CopyLink&appuid=5fb0152e00000000010098cd&apptime=1671183428
Sina weibo:
https://weibo.com/u/1957529242
Douyin:
https://v.douyin.com/han2qc1/
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

200TiB

### On-chain address for first allocation

f1hrhqirk3x2zraemn2d5tes26qywb5craycw3aly

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Shenzhen Ruyue Culture and Sports Communication Co., Ltd. was established in 2017. It is a large-scale performance, performance promotion, artist brokerage, film and television post-production, and event planning cultural company. The company has many star resources in the domestic performing arts circle, and has established good cooperative relations with well-known performing arts companies and star agents in Hong Kong, Beijing, Guangdong and other places. It can independently undertake various large-scale star concerts, cultural and art festivals and other activities.
The company has an elite team with strong professional planning, design and execution capabilities. Relying on its own unique advantages in the fierce market competition, it is unique in the same industry and is well received by the industry and customers! Over the years, we have established good cooperative relations with well-known brand companies in various industries. The company adheres to the business philosophy of "achieve the future with heart, realize dreams beyond" and vigorously promote differentiated services with innovation, high efficiency, high quality and high price, and strive to achieve the goal of win-win with customers and growth with the market.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
The company has a large number of star resources in the domestic entertainment industry, and has established a good cooperative relationship with well-known performing arts companies and star agents in Hong Kong, Beijing, Guangdong and other places The data of our company is very rich. The stored data comes from the data generated by our company and the cooperative artists, such as concerts, performances, TV series, pictures and videos, etc.
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### How do you plan to prepare the dataset

IPFS, singularity

### Please share a sample of the data

```text
A Concert related pictures
https://drive.google.com/drive/folders/1vf83LW3LXxPHah-oCBbQ58wOCyXn_rie?usp=share_link
B Contract
https://drive.google.com/drive/folders/1sUuKKFf_uptPrhre_Ex-ShfCmKPc7Z59?usp=share_link
C Credentials
https://drive.google.com/drive/folders/1pC9pEL6WsAvIFjyVaIC1RgNsChg3BF4m?usp=share_link
D movie demo
https://drive.google.com/drive/folders/1MtB1tIMk23zlAEh_zWTU6laW2lQBbIg6?usp=share_link
E Promotional video
https://drive.google.com/drive/folders/1USE4ejl6S-AUl55oCNZXZvXPmL9tMSpL?usp=share_link
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

1.5 to 2 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, South America

### How will you be distributing your data to storage providers

IPFS, Shipping hard drives

### How do you plan to choose storage providers

Slack, Filmine

### If you already have a list of storage providers to work with, fill out their names and provider IDs below

```text
f01394448
f01412953
f01474838
f02576
f01165468
```

### How do you plan to make deals to your storage providers

Boost client, Singularity

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 200TiB

**Client address**

> f1hrhqirk3x2zraemn2d5tes26qywb5craycw3aly

**Comment by herrehesse** [comment]
Dear Applicant,

Due to the increased amount of erroneous/wrong Filecoin+ data recently, on behalf of the entire community, we feel compelled to go deeper into datacap requests. Hereby to ensure that the overall value of the Filecoin network and Filecoin+ program increases and is not abused.

Please answer the questions below as comprehensively as possible.

**Customer data**

- Could you demonstrate exactly how and to what extent customer contact occurred? 

We expect that for the onboarding of customers with the scale of an LDN there would have been at least multiple email and perhaps several chat conversations preceding it. A single email with an agreement does not qualify here.

- Did the customer specify the amount of data involved in this relevant correspondence?

- Why does the customer in question want to use the Filecoin+ program? 

_Should this only be soley for acquiring datacap this is of course **out of the question**. The customer must have a legitimate reason for wanting to use the Filecoin+ program which is intended as a program to store useful and public datasets on the network._ 

- Why is the customer data considered Filecoin+ eligible?

_(As an intermediate solution Filecoin offers the FIL-E program or the glif.io website for business datasets that do not meet the requirements for a Filecoin+ dataset)_


**Files and Processing**

- Could you please demonstrate to us how you envision processing and transporting the customer data in question to any location for preparation?
- Would you demonstrate to us that the customer, the preparer and the intended storage providers all have adequate bandwidth to process the set with its corresponding size?
- Would you tell us how the data set preparer takes into account the prevention of duplicates in order to prevent data cap abuse?


Hopefully you understand the caution the overall community has for onboarding the wrong data. We understand the increased need for Filecoin+, however, we must not allow the program to be misused. Everything depends on a valuable and useful network, let's do our best to make this happen. Together.

**Comment by persia2022** [comment]
> 亲爱的申请人，
> 
> 由于最近错误/错误的 Filecoin+ 数据数量增加，我们代表整个社区感到有必要更深入地研究数据上限请求。特此确保 Filecoin 网络和 Filecoin+ 程序的整体价值增加和不被滥用。
> 
> 请尽可能全面地回答以下问题。
> 
> **客户资料**
> 
> * 您能否确切地说明如何以及在多大程度上发生了客户联系？
> 
> 我们预计，对于 LDN 规模的客户入职，至少会有多封电子邮件，之前可能还会有几次聊天对话。带有协议的单个电子邮件不符合此处的条件。
> 
> * 客户是否指定了此相关通信中涉及的数据量？
> * 为什么有问题的客户想要使用 Filecoin+ 程序？
> 
> _如果这只是为了获取 datacap 这当然是不可能**的**。客户必须有正当理由想要使用 Filecoin+ 程序，该程序旨在用作在网络上存储有用和公共数据集的程序。_
> 
> * 为什么客户数据被认为 Filecoin+ 符合条件？
> 
> _（作为中间解决方案，Filecoin 为不满足 Filecoin+ 数据集要求的业务数据集提供 FIL-E 程序或 glif.io 网站）_
> 
> **文件和处理**
> 
> * 您能否向我们展示您设想如何处理相关客户数据并将其传输到任何位置进行准备？
> * 你能向我们证明客户、准备者和预期的存储提供商都有足够的带宽来处理相应大小的集合吗？
> * 您能否告诉我们数据集准备者如何考虑防止重复以防止滥用数据上限？
> 
> 希望您了解整个社区对载入错误数据的谨慎态度。我们理解对 Filecoin+ 的需求增加，但是，我们绝不能允许该程序被滥用。一切都取决于有价值和有用的网络，让我们尽最大努力实现这一目标。一起。

Our company is Shenzhen Rule Culture and Sports Communication Co., LTD, our official website is http://www.worlddiamond.com.cn/, our contact email is liuwenjing@worlddiamond.com.cn.
This GitHub (persia2022) is our company's GitHub.

We emailed filplus-app-review@fil.org.

**Comment by persia2022** [comment]
> > 亲爱的申请人，
> > filecoin+ filecoin+数据增加增加，我们我们增加整个社区有必要更深入深入深入地地研究研究研究研究数据上限上限上限请求请求。。。特特特确保确保确保确保确保网络网络网络网络网络
> > 请尽可能地回答以下问题。
> > **客户资料**
> > 
> > * 您能不能确定地说明如何以及在多大程度上建立了客户联系？
> > 
> > 我们预估，对于LDN规范的客户入职，至少会有很多封电子邮件，之前可能还会有几次聊天对话。带有协议的单个电子邮件的不符合此时。
> > 
> > * 客户是否指定了此相关通信中浸及的数据量？
> > * 为什么有问题的客户想要使用Filecoin+程序？
> > 
> > _如果这只是为了获取datacap这当然是不可能**的**。客户必须有正当理由想使用Filecoin+程序，该程序早在使用在网络上存储有用和公共数据库。_
> > 
> > * 为什么客户数据被认为是Filecoin+符合条？
> > 
> > _（作为中间解决方案，Filecoin 为不满足 Filecoin+数据集需要的业务数据集提供FIL-E程序或glif.io网站）_
> > **文件和处理**
> > 
> > * 您能不能向我们展示您的设计如何处理相关客户数据并将其传输到任何位置进行准备？
> > * 你能向我们证明客户、准备者和预期的库存供应商提供足够的带宽来处理相对应大的小的集合吗？
> > * 您能不能告诉我们数据集准备者如何考虑防范重新恢复以防范溢出使用数据绑定？
> > 
> > Filecoin+ filecoin+ filecoin+的的需求增加增加增加了解了解了解了解对载入数据数据增加增加增加增加，但是，但是我们增加的，我们我们我们我们我们我们我们，我们我们我们我们我们我们我们我们我们我们了解了解了解对对对对对对对对对对对对对对这一目标。一开始。
> 
> 我公司是深圳市路尔文体传播有限公司，我们的官方网站是http://www.worlddiamond.com.cn/，我们的联系邮箱是[liuwenjing@worlddiamond.com.cn](mailto:liuwenjing@worlddiamond.com.cn)。 这个GitHub（persia2022）是我们公司的GitHub。
> 
> 我们通过电子邮件发送给[filplus-app-review@fil.org](mailto:filplus-app-review@fil.org)。
![1471邮件截图](https://user-images.githubusercontent.com/115997428/216507051-9f9281ca-5880-4ec8-afe1-aec9dcff38e7.jpg)

**Comment by persia2022** [comment]
![216507051-9f9281ca-5880-4ec8-afe1-aec9dcff38e7](https://user-images.githubusercontent.com/115997428/218407922-a1d35dad-1a19-4e75-8164-8e589377bd38.jpeg)

**Comment by herrehesse** [comment]
@persia2022 Before we continue, can you answer the above questions?

**Comment by persia2022** [comment]
@herrehesse Can you help me? There's been no answer here for a long time.

**Comment by herrehesse** [comment]
@persia2022 love to assist! But please try and answer this before we can move: https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1471#issuecomment-1371155141

**Comment by persia2022** [comment]
@herrehesse  I have heard about fil+ abuse in the community. For me, I will be an honest fil+ customer. The data I store is real and has real value. I benefit from being able to store my data on the filecoin network. I promise that I will strictly abide by fil+ rules. About data processing: I will finish the data processing on my own local server, and then send the completed data to SP by off-line mode (hard disk transportation). This process has no bandwidth requirement. We can also ensure that the data is not misused.

**Comment by herrehesse** [comment]
@persia2022 What are the business names and locations of the SP's you want to store with?

**Comment by persia2022** [comment]
ID | 公司名称 | 地点
-- | -- | --
f0827006 | Frog Cloud Storage Technology Co. LTD | Japan/Tokyo
f01847516 | Henan Luoyunshu Technology Co., LTD | China/HongKong
f01708981 | Shenzhen derier Technology Co. LTD | China/Shenzhen
f01076644 | Personal | China/Fujian

**Comment by persia2022** [comment]
ID | 公司名称 | 地点
-- | -- | --
f0827006 | Frog Cloud Storage Technology Co. LTD | Japan/Tokyo
f01847516 | Henan Luoyunshu Technology Co., LTD | China/Inner Mongolia
f01708981 | Shenzhen derier Technology Co. LTD | China/Shenzhen
f01076644 | Personal | China/Fujian

**Comment by cryptowhizzard** [comment]
Dear @persia2022 ,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Can you fill out [this form](https://form.jotform.com/230337462961356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it. We have the miners already. I checked them and they are ok.

Thanks!

**Comment by persia2022** [comment]
@cryptowhizzard I have finished the form.

**Comment by cryptowhizzard** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebxy3ugsevytbr47wktmrgblcoqsi34x6qpb7fkex5qktyrltuu4a 
#### Address 
> f1hrhqirk3x2zraemn2d5tes26qywb5craycw3aly
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1krmypm4uoxxf3g7okrwtrahlmpcph3y7rbqqgfa
#### Id
> 128e2571-b508-4b27-bcff-49b8f61f1134
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebxy3ugsevytbr47wktmrgblcoqsi34x6qpb7fkex5qktyrltuu4a

**Comment by stcouldlisa** [comment]
> @herrehesse I have heard about fil+ abuse in the community. For me, I will be an honest fil+ customer. The data I store is real and has real value. I benefit from being able to store my data on the filecoin network. I promise that I will strictly abide by fil+ rules. About data processing: I will finish the data processing on my own local server, and then send the completed data to SP by off-line mode (hard disk transportation). This process has no bandwidth requirement. We can also ensure that the data is not misused.

Your answer is very sincere, I am willing to try to believe you, this is the first time I support you, I will continue to pay attention

**Comment by stcouldlisa** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebcljlkozlw74p5ig76txhclx44d4s4wgtvmibdl7gvahce4qputy 
#### Address 
> f1hrhqirk3x2zraemn2d5tes26qywb5craycw3aly
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1jvvltduw35u6inn5tr4nfualyd42bh3vjtylgci
#### Id
> 128e2571-b508-4b27-bcff-49b8f61f1134
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebcljlkozlw74p5ig76txhclx44d4s4wgtvmibdl7gvahce4qputy

**Comment by kernelogic** [comment]
![WX20230302-192018@2x](https://user-images.githubusercontent.com/3711825/222623124-d08ae5f9-57dd-4389-99de-26d260b3c1d3.png)
Testing retrieval

**Comment by kernelogic** [comment]
![WX20230302-204321@2x](https://user-images.githubusercontent.com/3711825/222633270-24c601c8-c1cb-4444-a107-709c9b9e3f3b.png)

**Comment by kernelogic** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebkdmjejcscvwru2euxxsb4zfpnfqfktu3bo5dsrg3ozhsa3pfqg4 
#### Address 
> f1hrhqirk3x2zraemn2d5tes26qywb5craycw3aly
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### Id
> b32f1c44-e64f-4d35-9db3-25204efa916b
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebkdmjejcscvwru2euxxsb4zfpnfqfktu3bo5dsrg3ozhsa3pfqg4

**Comment by xiaoyuaiheshui** [comment]
![image](https://user-images.githubusercontent.com/43629914/222655544-d75bc6e7-778e-4a9c-94eb-ce3edac9f6c1.png)
I looked up the conversation above and checked the bot's report. The file distribution is all healthy.
Also retrieved files, very fast!
I would like to support this round!

**Comment by xiaoyuaiheshui** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedjd2lfug6n7gnolo2rp6xfha4she5kzmipzav34cgjljt6e4pire 
#### Address 
> f1hrhqirk3x2zraemn2d5tes26qywb5craycw3aly
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f122qmy25wdtt5mxd77kndiq7z5x2n3iwiuz2wdsa
#### Id
> b32f1c44-e64f-4d35-9db3-25204efa916b
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedjd2lfug6n7gnolo2rp6xfha4she5kzmipzav34cgjljt6e4pire

**Comment by mikezli** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedizcmgevzqeqz4gf6i7t5wvkcb7met4peimn4umz7t4owtrwh7l4 
#### Address 
> f1hrhqirk3x2zraemn2d5tes26qywb5craycw3aly
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1dnb3uz7sylxk6emti3ififcvu3nlufnnsjui6ea
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedizcmgevzqeqz4gf6i7t5wvkcb7met4peimn4umz7t4owtrwh7l4

**Comment by xiaoyuaiheshui** [comment]
checker:manualTrigger

**Comment by luobin544** [comment]
![image](https://user-images.githubusercontent.com/4277341/228205914-b7dfe94a-b438-4ae5-8d6d-698bb4203c56.png)

**Comment by Tom-OriginStorage** [comment]
checker:manualTrigger

**Comment by Tom-OriginStorage** [comment]
<img width="1180" alt="image" src="https://user-images.githubusercontent.com/103015469/228420643-e6ca1f4e-dba6-4cd0-a626-a6568ffad389.png">

**Comment by Tom-OriginStorage** [comment]
Packaging is relatively healthy, willing to support

**Comment by 1ane-1** [comment]
![6deb37f5575602818f0a0b2afd68b077](https://user-images.githubusercontent.com/91301211/228438129-e15be2fd-7125-4a10-8054-57f9513ee1e3.png)
![684f0d682141efb8a37523ba2e4bfff2](https://user-images.githubusercontent.com/91301211/228438154-c7ed36ba-6915-4b35-b4d9-078c9c0f6ec0.png)

**Comment by 1ane-1** [comment]
It is ok for me to support it.

**Comment by 1ane-1** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecpdbthx2agqchayz4hilgayyhrlendzxiwothj43zxzizlywmc4g 
#### Address 
> f1hrhqirk3x2zraemn2d5tes26qywb5craycw3aly
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1mdk7s2vntzm6hu35yuo6vjubtrpfnb2awhgvrri
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecpdbthx2agqchayz4hilgayyhrlendzxiwothj43zxzizlywmc4g

**Comment by kernelogic** [comment]
Have performed DD before and this time the CID report looks good.

**Comment by kernelogic** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebfpknmoxgd2xhc2ujsejirst5dnumu2fiwf7yguk4l55aobmcxeg 
#### Address 
> f1hrhqirk3x2zraemn2d5tes26qywb5craycw3aly
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebfpknmoxgd2xhc2ujsejirst5dnumu2fiwf7yguk4l55aobmcxeg

**Comment by cryptomandy** [comment]
checker:manualTrigger

**Comment by cryptomandy** [comment]
Cool, data distribution looks very good, and check all the boxes, retrieval also works very well, willing to support.

<img width="1379" alt="image" src="https://user-images.githubusercontent.com/9623093/232352175-970a972b-7762-4af9-a423-43b2b43863fd.png">

<img width="1305" alt="image" src="https://user-images.githubusercontent.com/9623093/232352198-e9446693-0cb1-4984-b722-a3ca75c9ee91.png">

**Comment by maxvint** [comment]
checker:manualTrigger

**Comment by maxvint** [comment]
Cool, data distribution looks very good, and check all the boxes, retrieval also works very well, willing to support.

<img width="1343" alt="image" src="https://user-images.githubusercontent.com/1715211/232352549-700f69f0-9ea6-431f-90df-4901ad834e19.png">

<img width="1287" alt="image" src="https://user-images.githubusercontent.com/1715211/232352582-d401208b-bd41-41a6-83ec-7589ab965095.png">

**Comment by maxvint** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaqg5st353atvvkc2jocdp3ydexwvn6sa4snrt6bsszq7xhzt73j2 
#### Address 
> f1hrhqirk3x2zraemn2d5tes26qywb5craycw3aly
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1ui5iy4mmkxjbw7752omiwp2ols2fzv4thrayagi
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaqg5st353atvvkc2jocdp3ydexwvn6sa4snrt6bsszq7xhzt73j2

**Comment by 1ane-1** [comment]
![lQLPJw0WbS_1DdrNAXXNBH2wQmbti9DVwF0ETa4KfIDSAA_1149_373](https://user-images.githubusercontent.com/91301211/236613884-6177e535-151c-4b0f-a0f6-d8e796d40486.png)

**Comment by 1ane-1** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceamhazlhip53jludacvf62kqokzotnhkbqvgy5f2xd5owu7fpjuqw 
#### Address 
> f1hrhqirk3x2zraemn2d5tes26qywb5craycw3aly
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1mdk7s2vntzm6hu35yuo6vjubtrpfnb2awhgvrri
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceamhazlhip53jludacvf62kqokzotnhkbqvgy5f2xd5owu7fpjuqw

**Comment by cryptowhizzard** [comment]
@1ane-1 

I am having difficulty downloading from this SP's. It seems to work at your end.

Can you please provide me with the car file you downloaded above , i want to check the content / data and verify the CID.

Thanks!

**Comment by NDLABS-OFFICE** [comment]
checker:manualTrigger

**Comment by NDLABS-OFFICE** [comment]
check bot shows good and willing to support.

**Comment by NDLABS-OFFICE** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced36rkbu66byjdjjyb462omhnkzasuym6kq6siltpwk7vcoor7ury 
#### Address 
> f1hrhqirk3x2zraemn2d5tes26qywb5craycw3aly
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1yayfsv6whu3rheviucvventj3y6t542xfpb47ei
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced36rkbu66byjdjjyb462omhnkzasuym6kq6siltpwk7vcoor7ury

**Comment by cryptowhizzard** [comment]
@NDLABS-OFFICE 

I indicated that there are SP's not supporting retrieval and was in the proces of doing due diligence. Why did you approve?
Not supporting retrieval is against the FIL+ guidelines and rules.

https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1471#issuecomment-1537094970

**Comment by NDLABS-OFFICE** [comment]
@cryptowhizzard 
Because I checked their check bot, it was a good project, and I did a spot check on the connectivity of the nodes and they were all connected properly. If you have records that are not retrievable you can leave a comment.

**Comment by cryptowhizzard** [comment]
@NDLABS-OFFICE 

I do have records that retrieval is not working properly, reason i asked @1ane-1 for the file she retrieved.

**Comment by persia2022** [comment]
Hi @cryptowhizzard,Thank you for your attention. May I know which SP does not support retrieval, I checked all SPs and they all support.

**Comment by cryptowhizzard** [comment]
@persia2022 

f01098810 for example and f02063867

I am trying to fetch baga6ea4seaqbj65aumtrx2dx7kwwjjb3yvoz33qkdkoc44mfnrkahxy7p4g3spa / bafybeib24m4hmnht6ihs5mu7uzugxl5n6ead4la7ujhjrnhfgvwb64ngcm

Can you send me the car file or make it available to download so i can check your data?

Thanks!

**Comment by amiable169** [comment]
checker:manualTrigger

**Comment by Chuangshi1** [comment]
From the total CID report，it performs great. But i will keep following you. Hope you always obey the rule.

**Comment by Chuangshi1** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebmfv5lni3dkvqpo2xfv54s54a7j5rvmofztjdwymr6ek3i2yfwmy 
#### Address 
> f1hrhqirk3x2zraemn2d5tes26qywb5craycw3aly
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1mdk7s2vntzm6hu35yuo6vjubtrpfnb2awhgvrri
#### Id
> 7c36623a-111f-42d0-b93c-947a94543d83
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebmfv5lni3dkvqpo2xfv54s54a7j5rvmofztjdwymr6ek3i2yfwmy

**Comment by NiwanDao** [comment]
checker:manualTrigger

**Comment by NiwanDao** [comment]
LGTM

**Comment by NiwanDao** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaget6deflek74iouc4nd2su5r7zqhsjisskae4yin62oj5loilxg 
#### Address 
> f1hrhqirk3x2zraemn2d5tes26qywb5craycw3aly
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1a2lia2cwwekeubwo4nppt4v4vebxs2frozarz3q
#### Id
> 7c36623a-111f-42d0-b93c-947a94543d83
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaget6deflek74iouc4nd2su5r7zqhsjisskae4yin62oj5loilxg

**Comment by cryptowhizzard** [comment]
I am trying to retrieve data here but i am getting errors:

 Error: Failed to retrieve content with candidate miner f01811024: data transfer failed: deal rejected: getting pieces for cid bafybeihvqfejnh6jf277viu72kdu7bldyny6sfsf2234idkzm52hgtdf4i: getting pieces containing block bafybeihvqfejnh6jf277viu72kdu7bldyny6sfsf2234idkzm52hgtdf4i: failed to lookup index for mh 1220f58148969fc92ebffaa29fd2874f8563c371e91645d6b7c40d596774734c65e2, err: datastore: key not found
Error: Failed to retrieve content with candidate miner f02235221: data transfer failed: deal rejected: there is no unsealed piece containing payload cid bafybeicsgi5dxfhmryxpg6slyzu3cki7g4znllsjfjucdar6lbk73sztde

As this affects to of the 4 SP's you use i urgently request to fix this.

**Comment by cryptowhizzard** [comment]
I managed to download some of your data and i have put it online for review.

http://www.datasetcreators.com/downloadedcarfiles/bafybeibobjpdkeumn7yrvudr57libilw6z4gn4dprp2xbr5pvk32z2v2aa/

From what i can see the quality of this data is extremely low. MP4 video's of 15 seconds inflated to 1 GB size or even more with the sole purpose to get datacap. This data is not valuable to the Filecoin network and i won't sign on this application.

Link with the data:
http://www.datasetcreators.com/downloadedcarfiles/bafybeibobjpdkeumn7yrvudr57libilw6z4gn4dprp2xbr5pvk32z2v2aa/
