### ISSUE TITLE
[DataCap Application] Focus Media

### ISSUE THREAD

**Issue by Kaylee92** [filecoin-project/filecoin-plus-large-datasets#1472]
### Data Owner Name

FocusMedia

### Data Owner Country/Region

China

### Data Owner Industry

Information, Media & Telecommunications

### Website

www.focusmedia.cn

### Social Media

```text
Wechat:fenzhongzhuanxiang
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

200TiB

### On-chain address for first allocation

f1yegk5pcziznjqueg2vmja4hnwdyxysmclpl65oq

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Focus Media is the largest offline advertising solution provider in China. Our goal is to be the partner of choice for the national leading brands by helping them connect with consumers and embrace data across a host of multi-platform inner-building channels.

Founded in 2003 as a pioneer of inner-building advertising company globally, Focus Media is China’s largest elevator and cinema media group. Its IPO in 2005 on NASDAQ was the first among Chinese advertising company. In 2007, it was included in the NASDAQ 100 Index. In 2015, Focus Media returned to the China A-share market.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
Our data is mainly media images and videos shown in the elevator.
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### How do you plan to prepare the dataset

lotus

### Please share a sample of the data

```text
I have put the data sample in this link. https://c.gmx.com/@1162714025528661586/1lXCx0ejQqK2fqy2ZRsKTg
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Sporadic

### For how long do you plan to keep this dataset stored on Filecoin

2 to 3 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, Europe

### How will you be distributing your data to storage providers

Shipping hard drives

### How do you plan to choose storage providers

Slack, Big data exchange

### If you already have a list of storage providers to work with, fill out their names and provider IDs below

```text
Now we have no identified SPs.
```

### How do you plan to make deals to your storage providers

Boost client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 200TiB

**Client address**

> f1yegk5pcziznjqueg2vmja4hnwdyxysmclpl65oq

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Looking at your application i have some questions:
As you are brand new on Github and have no history of past applications it seems to me that applying for 5PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?

Can you show us visible proof of the size of your data and the storage systems you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230232885049356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!

**Comment by stcouldlisa** [comment]
This company is a very large company in China, and it can even be said to be the top three advertising companies.

Are you an employee of this company, or the boss?

Can you store data on the filecoin network on behalf of your company?

**Comment by Kaylee92** [comment]
@stcouldlisa Hello, I am Jessie who is in charge of the marketing department of our company. We want to store the public and available data about advertisement in filecoin, and after that we will contact SPs through the BDE platform and hope to get your support from the community! Thank you.

**Comment by cryptowhizzard** [comment]
> Dear applicant,
> 
> Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.
> 
> Looking at your application i have some questions: As you are brand new on Github and have no history of past applications it seems to me that applying for 5PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?
> 
> Can you show us visible proof of the size of your data and the storage systems you have there?
> 
> As last question i would like you to fill out [this form](https://form.jotform.com/230232885049356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.
> 
> Thanks!

Reminder

**Comment by 1475Notary** [comment]
Thank you for your clarification. Please pay attention to the rules before making deals with SPs.

**Comment by 1475Notary** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaywrtv6wmroezicz4ppqtjb3jvifgwpmnwlrfgf4msruxly4w364 
#### Address 
> f1yegk5pcziznjqueg2vmja4hnwdyxysmclpl65oq
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1ofq4mngy7ggcp755pfquq2gphjjnlydolf6awtq
#### Id
> 5b7873fd-6769-4c92-99a8-9ce836b62fd7
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaywrtv6wmroezicz4ppqtjb3jvifgwpmnwlrfgf4msruxly4w364

**Comment by cryptowhizzard** [comment]
Proposed without KYC. Tagging

**Comment by Aifabot-Cloud** [comment]
The applicant contacted me via DM and went through our due diligence. We are willing to support in the first round and will keep an eye on later allocations. Looking forward to seeing your next milestone.

**Comment by Aifabot-Cloud** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecfk3ndxsnkc7l7ki67ylwi6mep4xrf2che4pyvbpamgjo6wp4qza 
#### Address 
> f1yegk5pcziznjqueg2vmja4hnwdyxysmclpl65oq
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f174fg3bqbln3zjnkxtyf6s54txqkr7yqkj6cig7y
#### Id
> 5b7873fd-6769-4c92-99a8-9ce836b62fd7
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecfk3ndxsnkc7l7ki67ylwi6mep4xrf2che4pyvbpamgjo6wp4qza

**Comment by RawTechVentures** [comment]
Since this is currently the first round of applications, there are no bot check results available for review. We believe this application meets the Fil+ criteria based on the applicant's description and the distribution plan.

**Comment by RawTechVentures** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceboyxwp4exqeeih757y2wopqmel27ea5vi5iegqqsrfr3jpmyzmwg 
#### Address 
> f1yegk5pcziznjqueg2vmja4hnwdyxysmclpl65oq
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1txfsjmix4vlzido4dkildrnbw26owtlbslexmpa
#### Id
> 5b7873fd-6769-4c92-99a8-9ce836b62fd7
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceboyxwp4exqeeih757y2wopqmel27ea5vi5iegqqsrfr3jpmyzmwg

**Comment by Meibuy** [comment]
Reviewed the report, and wish you cound find more sps(>3) in the next round.

**Comment by Meibuy** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebgh7godnxscyjh42ciqzekzop7tx74fhkwmtsp5kw2vtue4uysma 
#### Address 
> f1yegk5pcziznjqueg2vmja4hnwdyxysmclpl65oq
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1bwugfihrmn3iyunzyxst5nttql3dge4khwmurtq
#### Id
> 9fda2e11-60d8-4b8e-88f6-da35c1ed06ee
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebgh7godnxscyjh42ciqzekzop7tx74fhkwmtsp5kw2vtue4uysma

**Comment by cryptowhizzard** [comment]
checker:manualTrigger

**Comment by BobbyChoii** [comment]
Everything looks healthy, Deal Data Replication should be improved in the next round.

**Comment by BobbyChoii** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebylkkxpedwkhxlurqedif4mlvpk6m7s53mla6ewt62lfzw3gueb4 
#### Address 
> f1yegk5pcziznjqueg2vmja4hnwdyxysmclpl65oq
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1irqs2gmctiv3jcdfwuch7oxvf4ixh3k4b2wc24i
#### Id
> 9fda2e11-60d8-4b8e-88f6-da35c1ed06ee
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebylkkxpedwkhxlurqedif4mlvpk6m7s53mla6ewt62lfzw3gueb4

**Comment by clriesco** [comment]
Removed stale label and reopened issue :)

**Comment by TobyShea** [comment]
need update

**Comment by Kaylee92** [comment]
Not from our application. Wrong comment. 
> ![Scherm­afbeelding 2023-08-31 om 15 15 36](https://user-images.githubusercontent.com/36404435/264656129-b7f61bea-2f55-4528-8dc3-4b77ece5f524.png)
> 
> Hello,
> 
> I see you have been very creative and artistic to compile this beautifull data. However it is not the data you promised to store ;-)
> 
> I have made it ( Deal ID 42174172 ) available after i retrieved it from you on link:
> 
> http://www.datasetcreators.com/downloadedcarfiles/httpretrievals/1472-f02007260-f02207907-42174172-baga6ea4seaqkgjiy5i56rck2kqib5cgn77zx56ljcbdpx7mam45o4mymgqq7gjy
>

**Comment by cryptowhizzard** [comment]
Hello

Deal ID 42174172 is made from your wallet and this is the content per above.

**Comment by Kaylee92** [comment]
> Hello
> 
> Deal ID 42174172 is made from your wallet and this is the content per above.

Hello, but your result is wrong, maybe your program has some problem.

**Comment by Casey-PG** [comment]
checker:manualTrigger

**Comment by Casey-PG** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebw5jxf7t2ixhqdib62d4sbzx6qu4rulbebikuuqt33xl3dh7z7qg 
#### Address 
> f1yegk5pcziznjqueg2vmja4hnwdyxysmclpl65oq
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1d4yb3wags3mtddzesxoo63jv7dmlec3bq4yteni
#### Id
> 06ec04c0-e6e4-47b4-b725-968a26ba9724
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebw5jxf7t2ixhqdib62d4sbzx6qu4rulbebikuuqt33xl3dh7z7qg

**Comment by BobbyChoii** [comment]
Report looks healthy,willing to support!

**Comment by BobbyChoii** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebwzuqdjxuf6kk2raqlm5uio2wyi4zs7zhral5pg2xruo5pphozsw 
#### Address 
> f1yegk5pcziznjqueg2vmja4hnwdyxysmclpl65oq
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1irqs2gmctiv3jcdfwuch7oxvf4ixh3k4b2wc24i
#### Id
> 06ec04c0-e6e4-47b4-b725-968a26ba9724
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebwzuqdjxuf6kk2raqlm5uio2wyi4zs7zhral5pg2xruo5pphozsw

**Comment by herrehesse** [comment]
![Screenshot 2023-11-14 at 10 42 24](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/70132857/2060ab25-de2f-48df-befb-44e19a0c299f)

100% self-dealing, abusive notaries signing again, this story is getting pathetic.

**Comment by Sunnyiscoming** [comment]
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1472#issuecomment-1790739237
@Kaylee92 Hi, please notice this message.

**Comment by Filplus-govteam** [comment]
closing until SP entity and distribution list provided
