### ISSUE TITLE
[DataCap Application] Protocol Labs - Project Bacalhau

### ISSUE THREAD

**Issue by aronchick** [filecoin-project/filecoin-plus-large-datasets#1474]
### Data Owner Name

Bacalhau Project

### Data Owner Country/Region

United States

### Data Owner Industry

Information, Media & Telecommunications

### Website

https://bacalhau.org

### Social Media

```text
https://twitter.com/bacalhauproject
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

1PiB

### On-chain address for first allocation

f3wxle2afa4ov3zh6blop43oppmoz3o5wbxuch3rbhguqlsbzlnpapu64b3lhmts2ha5hn6holobzffnj6y24a 

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
We are the Bacalhau Project - an effort to bring Compute over Data. We will be passing through FIL+ information from the dataset being run to the resulting data set.

We started in February of 2022, and are currently funded as a Protocol Labs project.
```

### Is this project associated with other projects/ecosystem stakeholders?

Yes

### If answered yes, what are the other projects/ecosystem stakeholders

```text
Protocol Labs
The Compute over Data working group (cod.cloud)
```

### Describe the data being stored onto Filecoin

```text
We will be taking FIL+ (only) data and running a processing job on it. Users will evaluate if the data continues to be valuable and, if so, will propose it as being a derivative FIL+ dataset.
```

### Where was the data currently stored in this dataset sourced from

Other

### If you answered "Other" in the previous question, enter the details here

```text
Users will source all datasets as FIL+ already hosted on Filecoin
```

### How do you plan to prepare the dataset

IPFS, lotus

### Please share a sample of the data

```text
https://slingshot.filecoin.io/
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Monthly

### For how long do you plan to keep this dataset stored on Filecoin

Permanently

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, Africa, North America, South America, Europe, Australia (continent), Antarctica

### How will you be distributing your data to storage providers

Cloud storage (i.e. S3), HTTP or FTP server, IPFS

### How do you plan to choose storage providers

Slack, Filmine, Big data exchange, Partners, Others

### If you answered "Others" in the previous question, what is the tool or platform you plan to use

```text
Likely the people running the compute job will get "first bid" on storing the data. After that, it will be open to the community.
```

### How do you plan to make deals to your storage providers

Boost client, Lotus client, Others/custom tool

### If you answered "Others/custom tool" in the previous question, enter the details here

```text
Spade
```

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 1PiB

**Client address**

> f3wxle2afa4ov3zh6blop43oppmoz3o5wbxuch3rbhguqlsbzlnpapu64b3lhmts2ha5hn6holobzffnj6y24a

**Comment by cryptowhizzard** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb3qfi7ybbln5l7j7dmlj3rfshzmogyu42z73mimdt6kkuyiufv6y 
#### Address 
> f3wxle2afa4ov3zh6blop43oppmoz3o5wbxuch3rbhguqlsbzlnpapu64b3lhmts2ha5hn6holobzffnj6y24a
#### Datacap Allocated
> 256.00TiB
#### Signer Address
> f1krmypm4uoxxf3g7okrwtrahlmpcph3y7rbqqgfa
#### Id
> 6ff074fc-57bd-436a-9e5b-aaaed1360cff
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb3qfi7ybbln5l7j7dmlj3rfshzmogyu42z73mimdt6kkuyiufv6y

**Comment by psh0691** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedqvlhltbatq6fyll4kbgi4hvgefhncxetp7q53jmhlxyzeotwupo 
#### Address 
> f3wxle2afa4ov3zh6blop43oppmoz3o5wbxuch3rbhguqlsbzlnpapu64b3lhmts2ha5hn6holobzffnj6y24a
#### Datacap Allocated
> 256.00TiB
#### Signer Address
> f1qdko4jg25vo35qmyvcrw4ak4fmuu3f5rif2kc7i
#### Id
> 6ff074fc-57bd-436a-9e5b-aaaed1360cff
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedqvlhltbatq6fyll4kbgi4hvgefhncxetp7q53jmhlxyzeotwupo

**Comment by cryptowhizzard** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacea5v7h43aapwzmhbhn4ocua5xoivw5zs7rvssuhmdmmxp53yfbgba 
#### Address 
> f3wxle2afa4ov3zh6blop43oppmoz3o5wbxuch3rbhguqlsbzlnpapu64b3lhmts2ha5hn6holobzffnj6y24a
#### Datacap Allocated
> 256.00TiB
#### Signer Address
> f1krmypm4uoxxf3g7okrwtrahlmpcph3y7rbqqgfa
#### Id
> 6ff074fc-57bd-436a-9e5b-aaaed1360cff
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacea5v7h43aapwzmhbhn4ocua5xoivw5zs7rvssuhmdmmxp53yfbgba

**Comment by MetaWaveInfo** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceamuoha754erdhxuopj5rfbyv5kltljigq626ovjumw42c2vxfkiq 
#### Address 
> f3wxle2afa4ov3zh6blop43oppmoz3o5wbxuch3rbhguqlsbzlnpapu64b3lhmts2ha5hn6holobzffnj6y24a
#### Datacap Allocated
> 256.00TiB
#### Signer Address
> f1ktlkcxnmzxcdaoqfsunrg3vocfbmgv4n3mrn74a
#### Id
> 6ff074fc-57bd-436a-9e5b-aaaed1360cff
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceamuoha754erdhxuopj5rfbyv5kltljigq626ovjumw42c2vxfkiq

**Comment by cryptowhizzard** [comment]
@raghavrmadya @dkkapur 

I still have this application on my dash while there is no outstanding bot requests afaik.

Should we sign on this one?

![Scherm­afbeelding 2023-01-24 om 15 12 37](https://user-images.githubusercontent.com/36404435/214317124-28c80538-2322-4ab2-b67c-2be712a553dc.png)

**Comment by swatchliu** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced66ueez7rcmeuopu4237x4fgdbkqeaovqtk7y2z4nm4bw5virakq 
#### Address 
> f3wxle2afa4ov3zh6blop43oppmoz3o5wbxuch3rbhguqlsbzlnpapu64b3lhmts2ha5hn6holobzffnj6y24a
#### Datacap Allocated
> 256.00TiB
#### Signer Address
> f1yh6q3nmsg7i2sys7f7dexcuajgoweudcqj2chfi
#### Id
> 6ff074fc-57bd-436a-9e5b-aaaed1360cff
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced66ueez7rcmeuopu4237x4fgdbkqeaovqtk7y2z4nm4bw5virakq

**Comment by dkkapur** [comment]
<img width="628" alt="Screen Shot 2023-02-01 at 12 46 53 AM" src="https://user-images.githubusercontent.com/2343218/215994337-88f63cee-3d45-4f89-a194-489ed352266a.png">

@cryptowhizzard no, looks like labels needed patching / automation did not go through. @panges2 can we double click into this and see what went wrong / address with patch if needed?

**Comment by cryptowhizzard** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceayhvmn5wvlfrdsfiz7cdroy55mk3jhby37jhvjyyvxc3q64ysc2w 
#### Address 
> f3wxle2afa4ov3zh6blop43oppmoz3o5wbxuch3rbhguqlsbzlnpapu64b3lhmts2ha5hn6holobzffnj6y24a
#### Datacap Allocated
> 256.00TiB
#### Signer Address
> f1krmypm4uoxxf3g7okrwtrahlmpcph3y7rbqqgfa
#### Id
> 6ff074fc-57bd-436a-9e5b-aaaed1360cff
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceayhvmn5wvlfrdsfiz7cdroy55mk3jhby37jhvjyyvxc3q64ysc2w
