### ISSUE TITLE
[DataCap Application] Tiansheng Jiahe Media

### ISSUE THREAD

**Issue by grasshopperr** [filecoin-project/filecoin-plus-large-datasets#1479]
### Data Owner Name

Tiansheng Jiahe Media

### Data Owner Country/Region

China

### Data Owner Industry

Information, Media & Telecommunications

### Website

tsjh.tv

### Social Media

```text
NA
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

200TiB

### On-chain address for first allocation

f1f4akaolaexljchsrul4el5ewt6bdnzafr7hysfq

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Founded in Shenzhen and radiating from the Pearl River Delta, Tiansheng Jiahe has joined hands with high-quality performing arts resources across the country to lead the development of the children's art industry and make effective innovations for the children's art education. In recent years, Tiansheng Jiahe has focused on the development strategy of "giving children a confident stage", and has helped children grow up one after another in the field of children's programs with the corporate vision of "confidence and happiness". In 2018, the company released a series of original music videos for children called "Tiansheng Children's Voice", which was well received by parents and industry professionals.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
Activities recordings
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### How do you plan to prepare the dataset

lotus

### Please share a sample of the data

```text
Yes.
https://1drv.ms/u/s!AmTdIiRgJH4bajEpdV1W6Vs9f1Q?e=DRqGmz
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

More than 3 years

### In which geographies do you plan on making storage deals

Greater China

### How will you be distributing your data to storage providers

Shipping hard drives

### How do you plan to choose storage providers

Slack, Partners

### How do you plan to make deals to your storage providers

Boost client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
How much data do you have? How many copies will you store?
What's the relationship between you and the organization?

**Comment by grasshopperr** [comment]
> How much data do you have? How many copies will you store? What's the relationship between you and the organization?

I am the company owner, we saved quite a lot of video recordings these years, so we are looking for some place that can safely save those copies, we have more than 1 Pib of video data and we would like to make 5 copies.

**Comment by herrehesse** [comment]
Dear Applicant,

Due to the increased amount of erroneous/wrong Filecoin+ data recently, on behalf of the entire community, we feel compelled to go deeper into datacap requests. Hereby to ensure that the overall value of the Filecoin network and Filecoin+ program increases and is not abused.

Please answer the questions below as comprehensively as possible.

**Customer data**

- Could you demonstrate exactly how and to what extent customer contact occurred? 

We expect that for the onboarding of customers with the scale of an LDN there would have been at least multiple email and perhaps several chat conversations preceding it. A single email with an agreement does not qualify here.

- Did the customer specify the amount of data involved in this relevant correspondence?

- Why does the customer in question want to use the Filecoin+ program? 

_Should this only be soley for acquiring datacap this is of course **out of the question**. The customer must have a legitimate reason for wanting to use the Filecoin+ program which is intended as a program to store useful and public datasets on the network._ 

- Why is the customer data considered Filecoin+ eligible?

_(As an intermediate solution Filecoin offers the FIL-E program or the glif.io website for business datasets that do not meet the requirements for a Filecoin+ dataset)_


**Files and Processing**

- Could you please demonstrate to us how you envision processing and transporting the customer data in question to any location for preparation?
- Would you demonstrate to us that the customer, the preparer and the intended storage providers all have adequate bandwidth to process the set with its corresponding size?
- Would you tell us how the data set preparer takes into account the prevention of duplicates in order to prevent data cap abuse?


Hopefully you understand the caution the overall community has for onboarding the wrong data. We understand the increased need for Filecoin+, however, we must not allow the program to be misused. Everything depends on a valuable and useful network, let's do our best to make this happen. Together.

**Comment by simonkim0515** [comment]
## Datacap Request Trigger

#### Total DataCap requested 
> 5PiB

#### Expected weekly DataCap usage rate 
> 200TiB 

#### Client address
> f1f4akaolaexljchsrul4el5ewt6bdnzafr7hysfq

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Looking at your application i have some questions:
As you are brand new on Github and have no history of past applications it seems to me that applying for 5PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?

Can you show us visible proof of the size of your data and the storage systems you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230337462961356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!

**Comment by stcouldlisa** [comment]
Looks good, you have provided 15 videos, many of them save children. Filecoin is public, do you have their consent to store data on the filecoin network

**Comment by grasshopperr** [comment]
The confirmation email with our domain address have been sent to filplus team, email title is '#1475 Banma App', kindly help to review.

**Comment by grasshopperr** [comment]
The confirmation email with our domain address have been sent to filplus team, email title is '[DataCap Application]Tiansheng JIahe Media#1479 ', kindly help to review.

**Comment by grasshopperr** [comment]
It's been a long time since we;ve applied & sent email, hope someone can help to process further, thanks!
![_20230419184433](https://user-images.githubusercontent.com/115762541/233051955-31cc4523-be09-42b4-9d4e-b670326e91fe.jpg)

**Comment by mikezli** [comment]
Please list the SP you work with and tell us your backup plan.

**Comment by grasshopperr** [comment]
Sure, We contacted these sps, we plan to cooperate with some of them, we want to back up 6-8 copies, thank you for your question.
f01900537
f01289300
f01914991
f0478837
f01807707
f01915309
f02001485
f02036170
f01111113

**Comment by mikezli** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebkuzkgpix4k43l4xvxovrmmbujwweqkwt2a6qa2ddhv3ttdljxoe 
#### Address 
> f1f4akaolaexljchsrul4el5ewt6bdnzafr7hysfq
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1dnb3uz7sylxk6emti3ififcvu3nlufnnsjui6ea
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebkuzkgpix4k43l4xvxovrmmbujwweqkwt2a6qa2ddhv3ttdljxoe

**Comment by grasshopperr** [comment]
Sure.
1. Yes, our data are public.
2. Kindly refer to sample link, we have provided quite large number of sample data.
Thanks!

**Comment by sxxfuture-official** [comment]
checker:manualTrigger

**Comment by sxxfuture-official** [comment]
According to the results of the CID Checker Report, based on the fact that this project is in its infancy, there are still some adjustments that need to be made
 - Need to add more SPs from other regions, such as US, Europe, Southeast Asia, etc.
 - Need to increase the number of data copies and store the copies in different regions

I will support this round, but hopefully the two above can be adjusted soon.

**Comment by sxxfuture-official** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedgtsgj55kukw5yoqd6aolczuv2q3ys6auddpz7yvlacnk7idlmn2 
#### Address 
> f1f4akaolaexljchsrul4el5ewt6bdnzafr7hysfq
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1foiomqlmoshpuxm6aie4xysffqezkjnokgwcecq
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedgtsgj55kukw5yoqd6aolczuv2q3ys6auddpz7yvlacnk7idlmn2

**Comment by zcfil** [comment]
checker:manualTrigger

**Comment by zcfil** [comment]
Hi  grasshopperr The inspection report is very healthy, but SP is too concentrated in Zhanjiang. Can we contact SP from other cities in the future?

**Comment by grasshopperr** [comment]
Sure, that's we are are planning, and this situation won't happen in later rounds. we will distribute sps on 3 different continetns evenly.
Thanks a lot for your support.

**Comment by zcfil** [comment]
We have passed this review and will continue to pay attention to this proposal

**Comment by zcfil** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedav6hm4stj7zlzqd5acqjcybvf5ovtpeii5rzq5ucyhz54vyseiy 
#### Address 
> f1f4akaolaexljchsrul4el5ewt6bdnzafr7hysfq
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1cjzbiy5xd4ehera4wmbz63pd5ku4oo7g52cldga
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedav6hm4stj7zlzqd5acqjcybvf5ovtpeii5rzq5ucyhz54vyseiy

**Comment by igoovo** [comment]
checker:manualTrigger

**Comment by igoovo** [comment]
https://filecoin.tools/f091987

![WechatIMG13](https://user-images.githubusercontent.com/103082537/236965256-77ea39df-8977-4681-b31b-1176cc8a0152.jpeg)

**Comment by igoovo** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebs3kgwak7aqguvtdwr6fpi3az5yuy3f3x4y6qdgv5ajrqxj7xv4a 
#### Address 
> f1f4akaolaexljchsrul4el5ewt6bdnzafr7hysfq
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1shnsfayxqll77svffaxnjenms7bbbysbqcatrpy
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebs3kgwak7aqguvtdwr6fpi3az5yuy3f3x4y6qdgv5ajrqxj7xv4a

**Comment by Joyologist** [comment]
![47ca40a3029ee9f815a17d671113730](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/115516926/d0ac90e0-58e4-4ac6-9c1e-b9af22e5a721)

**Comment by Joyologist** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebcxpln5nadyo5xwxiy624qryhzjd5lkmyyfv3w7d5cm4jjmnbzvq 
#### Address 
> f1f4akaolaexljchsrul4el5ewt6bdnzafr7hysfq
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1txboxiscdm4f3okffyjmbilmwjtbisrbee72j6q
#### Id
> 096292c4-08a3-49fb-8a19-fb003dad78b8
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebcxpln5nadyo5xwxiy624qryhzjd5lkmyyfv3w7d5cm4jjmnbzvq

**Comment by liyunzhi-666** [comment]
checker:manualTrigger

**Comment by Tom-OriginStorage** [comment]
I hope the distribution of nodes will be more evenly distributed next time

**Comment by Tom-OriginStorage** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaor6hzkayf6dnexnwbugkdteib67c5io3tm4ggfg3dzroljl3opy 
#### Address 
> f1f4akaolaexljchsrul4el5ewt6bdnzafr7hysfq
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1q6bpjlqia6iemqbrdaxr2uehrhpvoju3qh4lpga
#### Id
> not found
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaor6hzkayf6dnexnwbugkdteib67c5io3tm4ggfg3dzroljl3opy

**Comment by nj-steve** [comment]
everything  looks good!
![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/15796059/fdc68743-f215-4c72-9b33-c0d19a99e43b)

**Comment by igoovo** [comment]
checker:manualTrigger

**Comment by OpenGate01** [comment]
Hope to continue to follow the fil+ rule encapsulation afterwards.

**Comment by OpenGate01** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceayy62qpndcnnfg6rl3tc7i3w3kqo464axodhwcgmx25o245uuy2s 
#### Address 
> f1f4akaolaexljchsrul4el5ewt6bdnzafr7hysfq
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1im4hmtbfzqnx7ir74kdaiu4ynjhgqh3sdi2snla
#### Id
> 60e8657e-c05e-4ac0-a3c2-963e2e7a9754
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceayy62qpndcnnfg6rl3tc7i3w3kqo464axodhwcgmx25o245uuy2s

**Comment by newwebgroup** [comment]
**The retrieval success rate looks low and needs to be adjusted by contacting SP, please improve it as soon as possible.
Retrieval Statistics**
> Overall Graphsync retrieval success rate: ⚠️  **11.06%** ⚠️
> Overall HTTP retrieval success rate: 0.00%
> Overall Bitswap retrieval success rate: 0.00%

**Unevenly dispersed replicas of data, requiring more SP to store replicas**
> Deal Data Replication
> ⚠️ 74.99% of deals are for data replicated across less than 4 storage providers.
> <img width="1094" alt="image" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/100118145/1d1effbd-ca37-4296-982d-c4b79dbe427d">
>

**Comment by newwebgroup** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceckegx5ajmsrxirin54fvbhktbrlj6knqjmnhwjsnvzv4fahdbgje 
#### Address 
> f1f4akaolaexljchsrul4el5ewt6bdnzafr7hysfq
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1e77zuityhvvw6u2t6tb5qlnsegy2s67qs4lbbbq
#### Id
> 60e8657e-c05e-4ac0-a3c2-963e2e7a9754
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceckegx5ajmsrxirin54fvbhktbrlj6knqjmnhwjsnvzv4fahdbgje

**Comment by a1991car** [comment]
checker:manualTrigger
