### ISSUE TITLE
Speedium | Dcent - Galaxy Evolution Explorer Satellite dataset - Part 2/3

### ISSUE THREAD

**Issue by cryptowhizzard** [filecoin-project/filecoin-plus-large-datasets#1482]
### Data Owner Name

NASA

### Data Owner Country/Region

United States

### Data Owner Industry

Environment

### Website

https://www.jpl.nasa.gov/missions/galaxy-evolution-explorer-galex

### Social Media

```text
https://www.jpl.nasa.gov/missions/galaxy-evolution-explorer-galex
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

500TiB

### On-chain address for first allocation

f1kyaa43uqypbcsv5isyd4xw7lvgjcumfzqsxag7y

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Speedium / Dcent has been engaged in the Filecoin space since 2020. We have successfully stored more than 15 differerent datasets with 20+ different miners.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
The Galaxy Evolution Explorer Satellite (GALEX) was a NASA mission led by the California Institute of Technology, whose primary goal was to investigates how star formation in galaxies evolved from the early Universe up to the present. GALEX used microchannel plate detectors to obtain direct images in the near-UV (NUV) and far-UV (FUV), and a grism to disperse light for low resolution spectroscopy. More information about GALEX is available at MAST

This project is a followup of #487. 487 has been granted 4 PB of datacap but given that we need around 800 TiB of datacap per replica we are at 50%.
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### How do you plan to prepare the dataset

others/custom tool

### If you answered "other/custom tool" in the previous question, enter the details here

```text
Singularity for the building of the data. Replication we do with our custom software written by ourselves.
```

### Please share a sample of the data

```text
https://www.jpl.nasa.gov/missions/galaxy-evolution-explorer-galex
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

1.5 to 2 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, Europe, Australia (continent)

### How will you be distributing your data to storage providers

HTTP or FTP server, IPFS

### How do you plan to choose storage providers

Big data exchange, Partners

### If you already have a list of storage providers to work with, fill out their names and provider IDs below

| MinerID | City | Continent | Business/Entity |
| --- | --- | --- | --- |
| `f01944347` | Oregon | USA | Jenny, Dabai |
| `f01952350` | Oregon | USA | Jenny, Dabai |
| `f01972364` | Oregon | USA | Jenny, Dabai |
| `f01972376` | Oregon | USA | Jenny, Dabai |
| `f02000937` | Chengdu | CN | MTY |
| `f01915033` | Chengdu | CN | MTY |
| `f01901765` | Hangzhou | CN | MTY |
| `f01953985` | Shenzhen | CN | MTY |
| `f0120****` | Melbourne | AU | HOLON |
| `f0115****` | Melbourne | AU | HOLON |
| `f01199430` | Heerhugowaard | EU | DCENT |
| `f01786387` | Heerhugowaard | EU | DCENT |
| `f01201327` | Heerhugowaard | EU | DCENT |
| `f01937642` | Heerhugowaard | EU | DCENT |
| `f0198****` | Dallas | USA | GREATERHEAT |
| `f0188****` | Singapore | AS | GREATERHEAT |
| `f01091851` | Omaha | USA | DLTx |
| `f01736668` | Omaha | USA | DLTx |
| `f01820744` | Omaha | USA | DLTx |
| `f0855584` | Omaha | USA | DLTx |
| `f01794610` | Omaha | USA | DLTx |
| `f01838599` | Kansas City | USA | DLTx |
| `f01845552` | Kansas City | USA | DLTx |
| `f01885088` | Hong Kong | AS | Hong Kong Morpho Technology Limited |
| `f01926635` | Hong Kong | AS | Hong Kong Morpho Technology Limited |
| `f01933917` | Hong Kong | AS | Hong Kong Morpho Technology Limited |
| `f01989888` | Hong Kong | AS | Hong Kong Morpho Technology Limited |

### How do you plan to make deals to your storage providers

Boost client, Lotus client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Kevin-FF-USA** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5 PiB

**Expected weekly DataCap usage rate**

> 500 TiB

**Client address**

> f1kyaa43uqypbcsv5isyd4xw7lvgjcumfzqsxag7y

**Comment by 8hfq** [comment]
You as a notary, I suspect you have violated the rules
You disclosed your node holdings in the notary application, f01199430 , f01720359
https://github.com/filecoin-project/notary-governance/issues/678
So you apply for a DC as an sp ,and issue a DC to yourself, which is a serious violation of the community protocol
and you have a lot of duplicate data, please explain it. 
As a notary, you are suspected of being involved in insider trading.

**Comment by herrehesse** [comment]
@8hfq Can I point out a clear error on your side here?
There has never been a violation here as @cryptowhizzard has never signed one of his own requests.

Storing one copy of the client's data is officially accepted by the community as a standard. No violations here.

Can you show me more proof of insider trading suspicion?

**Comment by 8hfq** [comment]
Under Fil+ it is allowed to store one copy yourself.
You have multiple nodes storing multiple copies. 
According to your statement, if I have 10 nodes, can I store 10 copies by myself. 
This is completely insider trading, the notary is to guarantee the fair certification of sc, not to seek benefits for himself
More importantly, as a notary, you apply for DC and sell it for profit. Please explain this problem.

**Comment by cryptowhizzard** [comment]
> You have multiple nodes storing multiple copies. 

This is an accusation and this is where you go wrong because it is simply not true. If we store one copy and distribute that over 2 nodes each node get's 50% of that one copy.

Prove it?

**Comment by 8hfq** [comment]
⚠️ 50.12% of total deal sealed by [f01199430](https://filfox.info/en/address/f01199430) are duplicate data.
⚠️ 41.66% of total deal sealed by [f01720359](https://filfox.info/en/address/f01720359) are duplicate data.
Obviously your own nodes have a lot of duplicate data, please explain why only your own nodes have a lot of duplicate data.
More importantly, as a notary, you apply for DC and sell it for profit. Please explain this problem.

**Comment by 8hfq** [comment]
You are a notary yourself, you apply for a DC, and you store it as an SP, is this reasonable?
As an open source community, if the notaries themselves violate the established agreement, then I don't know what you are doing

**Comment by cryptowhizzard** [comment]
Again , you are making accusations. Prove them?

The rule is that one can store 25% of an LDN ( one copy ) on it's own nodes.
The second rule is that a notary should not sign his own datacap request.

If you want additions or other rules you are welcome to submit a proposal on github to change the rules.

Meanwhile i have not broken any rules , will not ever , and you can't prove your accusations so this discussion is closed.

**Comment by 8hfq** [comment]
The notary sells dc, does it violate the rules?
Raghav Rmadya has clearly stated that it is forbidden to sell dc for profit

**Comment by 8hfq** [comment]
You are now the notary and the dc applicant. When I raise a question, you should show evidence and prove that you have not violated the regulations. Obviously, you are now looking at the current evidence and turning a blind eye, and selling dc privately, involving insider trading. I suggest the official review of your notary qualifications

**Comment by 8hfq** [comment]
As mentioned above, you have admitted that you sell dc data to sp.And now you are both a referee, an athlete and a medallist, as if you are blind to the rules.
https://github.com/filecoin-project/notary-governance/tree/main/notaries
No Self Dealing: To prevent conflicts of interest, Notaries should not allocate DataCap to Clients over which they control the private keys, or to a Client who intends to specifically spend the allocated DataCap with an address affiliated with the Notary. When in doubt, Notaries should bias towards transparency (i.e. public disclosure) or to getting a different Notary to handle the individual request.
[f01199430](https://filfox.info/en/address/f01199430)
[f01720359](https://filfox.info/en/address/f01720359)
[f01786387](https://filfox.info/en/address/f01786387)
[f01771403](https://filfox.info/en/address/f01771403)
[f01937642](https://filfox.info/en/address/f01937642)
These are all under your control, sp.Do you need more evidence? besides, I treat everyone equally. As a lotus developer, I love the community more than anyone else.
Instead, you blindly trust some people, especially some people.There is no due diligence for every applicant at all.

**Comment by cryptowhizzard** [comment]
It states i should not allocate or sign 
I have not signed any of the datacap request that i have applied for myself.

Again a lot of bla bla, no proof.

**Comment by herrehesse** [comment]
@8hfq lets try and keep this discussion mature please. Do not personally attack anyone. Even though I understand the stakes are high and some people become emotional. 

Not all of the datasets requested are stored (25%) on owned miners, this is not set in stone during the application phase. That is why commented "no comment".

As @cryptowhizzard stated multiple times, it is illegal to sign your own datacap request and you are right to attack a notary on this point! But, as far as I can see @cryptowhizzard never signed his own datacap request and is therefore in the right.

"you are so arrogant" please keep it non-personal @8hfq Daniel.

As far as I can see a lot of allegations but zero proof, can we go back to fighting fraud please?

**Comment by cryptowhizzard** [comment]
I do my duedilligence for every application i sign, thats the reason you are here right?

but again, if you have proof u did something wrong then file a dispute with the governance team. I do the same thing, no worries.

same goes for the current rules. If you don’t like them, feel free to propose a change request.

and for my arrogance, perhaps you are right. That’s because i am jus honest and tell you just the way it is.

**Comment by kernelogic** [comment]
Filecoin is a very small community, constructive community members are scarce and often wear many hats. Members are already proactively avoiding conflict of interest as much as possible. 

But personal attacks and threats should absolutely not be tolerated, please refer to community code of conduct about how to give advice.

**Comment by xinaxu** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebuh2jkhulwejdwrfve5abu3opau7inhkj3be64jiso5wkytb3ypk 
#### Address 
> f1kyaa43uqypbcsv5isyd4xw7lvgjcumfzqsxag7y
#### Datacap Allocated
> 1.95PiB
#### Signer Address
> f1k3ysofkrrmqcot6fkx4wnezpczlltpirmrpsgui
#### Id
> 333cac20-560d-4e64-80fd-9bb92fc5723f
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebuh2jkhulwejdwrfve5abu3opau7inhkj3be64jiso5wkytb3ypk

**Comment by xingjitansuo** [comment]
@cryptowhizzard Can you please explain the heavy duplication within one SP?

**Comment by cryptowhizzard** [comment]
Hi Cabrina,

Thanks for the notice. We have been sending deals to the lotus-markets miners in the past and those led to timeouts ( redeal ) on our api. With boost it is impossible to send deals multiple times, we are enforcing this now to prevent these issues so the duplicates should not grow in the next tranches.

Secondly , the FIL+ site ( https://filplus.d.interplanetary.one/notaries?showInactive=true ) had an outage for a while past weeks. There are post on slack about this. I am checking automated &  based on their data what deals are existing on chain and who are not. Everything that is not on chain after 14 days get's wiped in our database and resend.

Since the site was up but now showing new deals , my script wiped deals and started resending. That was unfortunate and caused duplicates. When i discovered it I halted the cleaning script and i am running it by hand now ( after verification that the data i am receiving is correct ).

**Comment by xingjitansuo** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec37c7aylaipfw5ypt7uyryxi4c7cifj66ervpsdx6tcu3gp3zwqg 
#### Address 
> f1kyaa43uqypbcsv5isyd4xw7lvgjcumfzqsxag7y
#### Datacap Allocated
> 1.34PiB
#### Signer Address
> f1a2lia2cwwekeubwo4nppt4v4vebxs2frozarz3q
#### Id
> 75ab1a84-4250-4154-8435-ab271b8b0d45
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec37c7aylaipfw5ypt7uyryxi4c7cifj66ervpsdx6tcu3gp3zwqg

**Comment by Yvette516** [comment]
> Hi Cabrina,
> 
> Thanks for the notice. We have been sending deals to the lotus-markets miners in the past and those led to timeouts ( redeal ) on our api. With boost it is impossible to send deals multiple times, we are enforcing this now to prevent these issues so the duplicates should not grow in the next tranches.
> 
> Secondly , the FIL+ site ( https://filplus.d.interplanetary.one/notaries?showInactive=true ) had an outage for a while past weeks. There are post on slack about this. I am checking automated & based on their data what deals are existing on chain and who are not. Everything that is not on chain after 14 days get's wiped in our database and resend.
> 
> Since the site was up but now showing new deals , my script wiped deals and started resending. That was unfortunate and caused duplicates. When i discovered it I halted the cleaning script and i am running it by hand now ( after verification that the data i am receiving is correct ).

![image](https://user-images.githubusercontent.com/106008819/226876227-d2d8a0e8-f2c5-4eb6-9e60-ef66e4cc3a17.png)

<img width="763" alt="WeChatWorkScreenshot_d4f47017-98b5-4733-86f2-6846893825b3" src="https://user-images.githubusercontent.com/106008819/226876370-3f296600-4288-46f5-8799-35f58ad24a02.png">

If that's the case, can you help me understand why piece CID - baga6ea4seaqfferi4pvcishqlhqwi43zzvutal6d2zsy3zzzh43sqhtzpqa56oy was stored 10682 times in f01199430?

**Comment by cryptowhizzard** [comment]
> > Hi Cabrina,
> > Thanks for the notice. We have been sending deals to the lotus-markets miners in the past and those led to timeouts ( redeal ) on our api. With boost it is impossible to send deals multiple times, we are enforcing this now to prevent these issues so the duplicates should not grow in the next tranches.
> > Secondly , the FIL+ site ( https://filplus.d.interplanetary.one/notaries?showInactive=true ) had an outage for a while past weeks. There are post on slack about this. I am checking automated & based on their data what deals are existing on chain and who are not. Everything that is not on chain after 14 days get's wiped in our database and resend.
> > Since the site was up but now showing new deals , my script wiped deals and started resending. That was unfortunate and caused duplicates. When i discovered it I halted the cleaning script and i am running it by hand now ( after verification that the data i am receiving is correct ).
> 
> ![image](https://user-images.githubusercontent.com/106008819/226876227-d2d8a0e8-f2c5-4eb6-9e60-ef66e4cc3a17.png)
> 
> <img alt="WeChatWorkScreenshot_d4f47017-98b5-4733-86f2-6846893825b3" width="763" src="https://user-images.githubusercontent.com/106008819/226876370-3f296600-4288-46f5-8799-35f58ad24a02.png">
> 
> If that's the case, can you help me understand why piece CID - baga6ea4seaqfferi4pvcishqlhqwi43zzvutal6d2zsy3zzzh43sqhtzpqa56oy was stored 10682 times in f01199430?

Hi,

I checked my database but Galex has only 3960 deals to f01199430 . It is in no way a match to the numbers you are reporting here. 

Secondly , there was a bug in Singularity as already stated here. It let to duplication of CID's on our side, but that has already been solved. ( https://github.com/tech-greedy/singularity/issues/172 ) . 

As we are now on Boost with all machines duplicate's are near impossible. Boost refuses when the same ID sent twice i believe. If this is not the case I will create a PR for it to make this a configuration option as this might be a very handy feature request to avoid duplication. As stated i am on leave until May 8 due family issues. If you need more information please ping on slack.

<img width="1247" alt="Scherm­afbeelding 2023-04-27 om 14 38 40" src="https://user-images.githubusercontent.com/36404435/234865819-54377033-3c7c-4f52-861d-ba1a58d1abda.png">

**Comment by cryptowhizzard** [comment]
Btw, the Mysql learned that indeed there was duplication due the singularity bug. The max is 16 times for certain CID's. Nowhere near the 10K you mention.

<img width="920" alt="Scherm­afbeelding 2023-04-27 om 14 51 10" src="https://user-images.githubusercontent.com/36404435/234867378-bb2f85d7-1714-4d85-b216-a95540c83c4f.png">

**Comment by Chuangshi1** [comment]
checker:manualTrigger

**Comment by Yvette516** [comment]
The TerminateSectors messages tell a lot. I'm very impressed that you tried hard to fix the problem. But the application still doesn't meet Fil+ rule, why do so many nodes have more than 20% duplicate data?

**Comment by Yvette516** [comment]
checker:manualTrigger

**Comment by data-programs** [comment]
<img width="32" alt="KYC" Verified src="https://stable.filplus.storage/images/filplus-kyc-verified-badge.png"/>

This user’s identity has been verified through [filplus.storage](https://filplus.storage)
