### ISSUE TITLE
[DataCap Application] <Himawari-8/-9>

### ISSUE THREAD

**Issue by algo-cpu** [filecoin-project/filecoin-plus-large-datasets#1484]
### Data Owner Name

Meteorological Satellite Center of JMA

### Data Owner Country/Region

Japan

### Data Owner Industry

Utilities

### Website

https://www.data.jma.go.jp/mscweb/en/himawari89/cloud_service/cloud_service.html

### Social Media

```text
https://www.data.jma.go.jp/mscweb/en/general/contact.html
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

200TiB

### On-chain address for first allocation

f1rrdumkod5xqzup2znqxc2htvtiv3rqv47ctzywa

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
The Himawari-8/-9 satellite’s provision of plentiful image data is an essential meteorological service. To distribute the enormous volumes of Himawari-8/-9 imagery, JMA established an Internet cloud service called HimawariCloud for National Meteorological and Hydrological Services (NMHSs) in the East Asia/Western Pacific regions and elsewhere.
I am an early filecoin participant and have a deep understanding of ecology and technology. Because this Himawari-8/-9 project cannot persist data, I thought of filecoin, so that data that is beneficial to the world can be stored in web3 more persistently.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
Himawari Standard Data are used to create all products related to Himawari-8/-9 as master data from all 16 bands with the finest spatial resolution. True-color images composed of data from three visible bands are provided in Portable Network Graphics (PNG) format. In addition, images of target areas in Network Common Data Form (NetCDF) are also created and distributed. In November 2015, JMA began to distribute HRIT data (same as the ones disseminated via HimawariCast).

Full-Disk Himawari Standard Data and HRIT data are separately created for each band and divided into 10 segments from north to south so that NMHSs can select only the files necessary for their operations.
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### How do you plan to prepare the dataset

singularity

### Please share a sample of the data

```text
https://noaa-himawari8.s3.us-east-1.amazonaws.com/AHI-L1b-FLDK/2015/07/07/0200/HS_H08_20150707_0200_B03_FLDK_R05_S0101.DAT.bz2
https://noaa-himawari8.s3.us-east-1.amazonaws.com/AHI-L1b-Japan/2019/10/04/1620/HS_H08_20191004_1620_B01_JP04_R10_S0101.DAT.bz2
https://noaa-himawari8.s3.us-east-1.amazonaws.com/AHI-L1b-Japan/AHI-L2-FLDK-Clouds/2019/12/10/1500/Himawari8_AHI_FLDK_2019344_1500_00_CLOUD_PHASE_EN.nc
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

Permanently

### In which geographies do you plan on making storage deals

Asia other than Greater China, North America, South America, Europe

### How will you be distributing your data to storage providers

HTTP or FTP server, Shipping hard drives

### How do you plan to choose storage providers

Slack, Big data exchange, Partners

### How do you plan to make deals to your storage providers

Boost client, Singularity

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
Please provide the material to prove that this is an open dataset.

**Comment by beck-8** [comment]
> Please provide the material to prove that this is an open dataset.

Hello, I learned this data from the data set that sealingshot v3 plans to store.

**Comment by algo-cpu** [comment]
> Please provide the material to prove that this is an open dataset.
Hello, I saw this dataset from the dataset that slingshot v3 is preparing to store.
But you reminded me, I just went to read the data set usage rules, and now there are no clear public rules, so I will close this issuse.
