### ISSUE TITLE
[DataCap Allocation] - cloud native

### ISSUE THREAD

**Issue by hail100** [filecoin-project/filecoin-plus-large-datasets#1485]
---
name: Large Dataset Notary application
about: Clients should use this application form to request a DataCap allocation via a LDN for a dataset
title: "cloud native"
labels: 'application, Phase: Diligence'
assignees: ''

---
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Shanghai Lingmi Information Technology Co., Ltd.
- Website / Social Media: https://opsmind.com/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100TiB
- On-chain address for first allocation: f1ewvlonhvzu2d377z3dvzo5wk4dh3rkccp6j234q
- Region: Asia (excl. Greater China)

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
       OpsMind (Shanghai Lingmi Information Technology Co., Ltd.), founded in 2017, is an open operation and maintenance capability building platform-as-a-service provider for the cloud-native era. Adhering to the corporate mission of ‘making IT information technology popular’ and the core values of ‘customer success, seeking truth from facts, long-termism, and first innovation’, OpsMind is committed to empowering enterprises to transform IT operation and maintenance into SRE with an operation and maintenance self-service platform and improving the penetration rate of business self-service and accelerate the process of enterprise digital transformation.
	With the advent of the cloud-native era, we firmly believe that IT operation and maintenance has transformed from the manager of the infrastructure to a part of the infrastructure. By using OpsMind, the enterprise IT operation and maintenance team can quickly and cost-effectively build personalized and customized self-service solutions that meet business needs. The service platform enables internal and external personnel of the company to complete query retrieval, observation analysis and operation control of operation and maintenance objects from a business perspective.
	We are a professional ITSM technology service provider, providing solutions such as full-stack monitoring and alarming, resource configuration management, multi-cloud management platform, automated operation platform, and release process management. Most importantly, we also provide a low-code secondary development platform for the above solutions, making the construction and changes of solutions more flexible and agile.
	The OpsMind R&D service center is located in Shanghai. The core team comes from well-known technology companies such as Qiniuyun, UCloud, Baidu, and Byte. Rich insights and practical experience, corporate customers widely cover media entertainment, corporate services, retail distribution, financial technology and other industries.
```

What is the primary source of funding for this project?
```
corporate income
```

What other projects/ecosystem stakeholders is this project associated with?
```
None.
```

## Use-case details

Describe the data being stored onto Filecoin
```
We need to store a large number of surveillance video files, database data and various business information to meet customer business monitoring, real-time alarm and so on.
```

Where was the data in this dataset sourced from?
```
These data come from the company's business development, and a large amount of video surveillance data will be generated every day, which will provide business security for customers in various industries.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://drive.google.com/drive/folders/1spEV-g75BmkSIapXOVf9e3UKkzThOqeM?usp=share_link
https://drive.google.com/drive/folders/1jGQDW8G0ViAFscYC2OSoMOBnOvE7xjeR?usp=share_link
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Confirm
```

What is the expected retrieval frequency for this data?
```
No need frequent, 1-2 times a day
```

For how long do you plan to keep this dataset stored on Filecoin?
```
2 year
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
all regions
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
We have our own IDC room, can open the external network for customers downloading.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We will choose a storage provider with high reputation and strong transaction confidentiality. Before we cooperate with them, we should know the size of their business, reliability, whether they have core hardware and professional technical team. Because we know the confidentiality of the data is very important
```

How will you be distributing deals across storage providers?
```
We will distribute equally to high-quality storage providers
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
When we get our datacap, we make the transaction immediately. And there is enough money to pay for it.
```

**Comment by Sunnyiscoming** [comment]
surveillance video files are not suitable as public data stores.
Can you explain your data composition? How many copies will you store?
What's the relationship between you and the organization?
Can you provide more detailed information about other storage providers participated in this program, such as you can list SPs you have contacted with at present? Whether the sps you choose can support data retrieval?

**Comment by ruiyaningAI** [comment]
@Sunnyiscoming 
Hello, Sunny iscoming. We have re-updated the public data. The original surveillance video is required for our business operation and maintenance IDC. We will monitor some risk factors of IDC through intelligent algorithms, and some surveillance videos have been removed;
I am the project manager of the company, mainly responsible for the company's project development and implementation. Most of our data is generated by business development, including but not limited to cloud resource monitoring data, operation and maintenance object observation and analysis data, operation and maintenance object operation audit and cloud resources data such as cost analysis. At present, there are some SP service providers connected. f01949018, f01947280;

**Comment by hail100** [comment]
@Sunnyiscoming 
Hello, Sunny iscoming. We have re-updated the public data. The original surveillance video is required for our business operation and maintenance IDC. We will monitor some risk factors of IDC through intelligent algorithms, and some surveillance videos have been removed;
I am the project manager of the company, mainly responsible for the company's project development and implementation. Most of our data is generated by business development, including but not limited to cloud resource monitoring data, operation and maintenance object observation and analysis data, operation and maintenance object operation audit and cloud resources data such as cost analysis. At present, there are some SP service providers connected. f01949018, f01947280;

**Comment by herrehesse** [comment]
Dear Applicant,

Due to the increased amount of erroneous/wrong Filecoin+ data recently, on behalf of the entire community, we feel compelled to go deeper into datacap requests. Hereby to ensure that the overall value of the Filecoin network and Filecoin+ program increases and is not abused.

Please answer the questions below as comprehensively as possible.

**Customer data**

- Could you demonstrate exactly how and to what extent customer contact occurred? 

We expect that for the onboarding of customers with the scale of an LDN there would have been at least multiple email and perhaps several chat conversations preceding it. A single email with an agreement does not qualify here.

- Did the customer specify the amount of data involved in this relevant correspondence?

- Why does the customer in question want to use the Filecoin+ program? 

_Should this only be soley for acquiring datacap this is of course **out of the question**. The customer must have a legitimate reason for wanting to use the Filecoin+ program which is intended as a program to store useful and public datasets on the network._ 

- Why is the customer data considered Filecoin+ eligible?

_(As an intermediate solution Filecoin offers the FIL-E program or the glif.io website for business datasets that do not meet the requirements for a Filecoin+ dataset)_


**Files and Processing**

- Could you please demonstrate to us how you envision processing and transporting the customer data in question to any location for preparation?
- Would you demonstrate to us that the customer, the preparer and the intended storage providers all have adequate bandwidth to process the set with its corresponding size?
- Would you tell us how the data set preparer takes into account the prevention of duplicates in order to prevent data cap abuse?


Hopefully you understand the caution the overall community has for onboarding the wrong data. We understand the increased need for Filecoin+, however, we must not allow the program to be misused. Everything depends on a valuable and useful network, let's do our best to make this happen. Together.

**Comment by simonkim0515** [comment]
## Datacap Request Trigger

#### Total DataCap requested 
> 5PiB

#### Expected weekly DataCap usage rate 
> 100TiB 

#### Client address
> f1ewvlonhvzu2d377z3dvzo5wk4dh3rkccp6j234q

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Looking at your application i have some questions:
As you are brand new on Github and have no history of past applications it seems to me that applying for 5PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?

Can you show us visible proof of the size of your data and the storage systems you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230337462961356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!

**Comment by hail100** [comment]
@cryptowhizzard 
hi，Completed the form

**Comment by cryptowhizzard** [comment]
Seems we have not received anything. Can you retry please?

**Comment by hail100** [comment]
@cryptowhizzard 
Hello, I have conducted another handover here, and I have worked hard to check it
![image](https://user-images.githubusercontent.com/7278395/226504194-9306e00f-fa99-432a-ae07-42e377d41a9c.png)

**Comment by hail100** [comment]
@cryptowhizzard 
Hello, haven't received it yet?

**Comment by hail100** [comment]
@fabriziogianni7 
Hello, can you verify it?

**Comment by hail100** [comment]
ok

**Comment by 1ane-1** [comment]
Can you provide more detailed information about other storage providers participated in this program, such as you can list SPs you have contacted with at present? And how many copies do you want to store?

**Comment by hail100** [comment]
Hello, the relevant sps are f02094335, f02029743, f02114868, f02199393, f02121645.store 3-5 servings

**Comment by hail100** [comment]
@1ane-1 
Hello, the relevant sps are f02094335, f02029743, f02114868, f02199393, f02121645.store 3-5 servings

**Comment by 1ane-1** [comment]
> @1ane-1 Hello, the relevant sps are f02094335, f02029743, f02114868, f02199393, f02121645.store 3-5 servings

Thanks, for the first round, i am willing to support you. Hope you can obey the fil+ rules.

**Comment by 1ane-1** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaain37fmmxz6p2almxye5kdxvlyvuk2xoxpfsckxvrq6htsrkcmi 
#### Address 
> f1ewvlonhvzu2d377z3dvzo5wk4dh3rkccp6j234q
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1mdk7s2vntzm6hu35yuo6vjubtrpfnb2awhgvrri
#### Id
> 1d1cbac5-bb29-42be-b902-838323a079a4
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaain37fmmxz6p2almxye5kdxvlyvuk2xoxpfsckxvrq6htsrkcmi

**Comment by sxxfuture-official** [comment]
The SPs provided are all reachable. In the first round, I will support and continue to pay attention.

**Comment by sxxfuture-official** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb6lv4upvnumid5mzeqlwii6pbepit66mcj6j4de34zfa42oquxqo 
#### Address 
> f1ewvlonhvzu2d377z3dvzo5wk4dh3rkccp6j234q
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1foiomqlmoshpuxm6aie4xysffqezkjnokgwcecq
#### Id
> 1d1cbac5-bb29-42be-b902-838323a079a4
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb6lv4upvnumid5mzeqlwii6pbepit66mcj6j4de34zfa42oquxqo

**Comment by Chuangshi1** [comment]
checker:manualTrigger

**Comment by Chuangshi1** [comment]
Pls check your report.

**Comment by cryptowhizzard** [comment]
> ## Request Approved
> Your Datacap Allocation Request has been approved by the Notary
> 
> #### Message sent to Filecoin Network
> > bafy2bzaceb6lv4upvnumid5mzeqlwii6pbepit66mcj6j4de34zfa42oquxqo
> 
> #### Address
> > f1ewvlonhvzu2d377z3dvzo5wk4dh3rkccp6j234q
> 
> #### Datacap Allocated
> > 50.00TiB
> 
> #### Signer Address
> > f1foiomqlmoshpuxm6aie4xysffqezkjnokgwcecq
> 
> #### Id
> > 1d1cbac5-bb29-42be-b902-838323a079a4
> 
> #### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb6lv4upvnumid5mzeqlwii6pbepit66mcj6j4de34z

> The SPs provided are all reachable. In the first round, I will support and continue to pay attention.

🥳🥳🥳🥳🥳🥳🥳🥳🥳🥳🥳🥳🤣

**Comment by cryptowhizzard** [comment]
> The SPs provided are all reachable. In the first round, I will support and continue to pay attention.

🥳🥳🥳🥳🥳🥳🥳🥳🥳🥳

**Comment by xiaoyuaiheshui** [comment]
checker:manualTrigger

**Comment by hail100** [comment]
checker:manualTrigger

**Comment by hail100** [comment]
checker:manualTrigger

**Comment by twosson** [comment]
checker:manualTrigger

**Comment by twosson** [comment]
checker:manualTrigger

**Comment by twosson** [comment]
checker:manualTrigger

**Comment by hail100** [comment]
checker:manualTrigger

**Comment by hail100** [comment]
The CID sharing issue was caused by the SP test during their initial storage/code optimization. This problem has been discussed with the SP, and it will not occur again in the future.

**Comment by SuperChaiChai** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedhkjnmhkpu6cn5twhlrk2sw2fmr3ierl72hoeiirid4qqhmj5yhu 
#### Address 
> f1ewvlonhvzu2d377z3dvzo5wk4dh3rkccp6j234q
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f12mckci3omexgzoeosjvstcfxfe4vqw7owdia3da
#### Id
> 81ffda26-146d-4631-a418-8d2d2e004f2d
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedhkjnmhkpu6cn5twhlrk2sw2fmr3ierl72hoeiirid4qqhmj5yhu

**Comment by nj-steve** [comment]
checker:manualTrigger

**Comment by nj-steve** [comment]
<img width="1261" alt="image" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/15796059/69afd84d-e467-4bc3-8cbd-d9b94b728cd9">
everything looks good.willing to support.
the shared cid has been explained with testing and only a 32G sector, I choose to believe.

**Comment by nj-steve** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceayewwi6fa2wv5lhrj2ayt3h5ael63byge5bv7jifipxr4amgom3u 
#### Address 
> f1ewvlonhvzu2d377z3dvzo5wk4dh3rkccp6j234q
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1xx6555qijma7igpnjspyvdunc4vfxkawnpqy5ii
#### Id
> 81ffda26-146d-4631-a418-8d2d2e004f2d
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceayewwi6fa2wv5lhrj2ayt3h5ael63byge5bv7jifipxr4amgom3u

**Comment by 1ane-1** [comment]
checker:manualTrigger

**Comment by ipollo00** [comment]
> <img alt="image" width="1261" src="https://user-images.githubusercontent.com/15796059/259920469-69afd84d-e467-4bc3-8cbd-d9b94b728cd9.png"> everything looks good.willing to support. the shared cid has been explained with testing and only a 32G sector, I choose to believe.

DD: That‘s reasonable. 

The retrieval rate is increasing. No other question.

**Comment by ipollo00** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceczcs4fggilbr7mvcd6pim2aojpnglgmdnhdg5jc5eainyzgyamew 
#### Address 
> f1ewvlonhvzu2d377z3dvzo5wk4dh3rkccp6j234q
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1n5wlrrhoxpkgwij25xrtt7w7g2k3fhbthmdn6ri
#### Id
> f740e61c-475f-4e35-9a92-5402a85dd6c5
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceczcs4fggilbr7mvcd6pim2aojpnglgmdnhdg5jc5eainyzgyamew

**Comment by Chuangshi1** [comment]
Looks good, hope to improve retrieval rate gradually!

**Comment by Chuangshi1** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebucsdqoegfmnzd2zmispkvhds57tjdnlhfd7zpgu6q4ckcinungm 
#### Address 
> f1ewvlonhvzu2d377z3dvzo5wk4dh3rkccp6j234q
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1mdk7s2vntzm6hu35yuo6vjubtrpfnb2awhgvrri
#### Id
> f740e61c-475f-4e35-9a92-5402a85dd6c5
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebucsdqoegfmnzd2zmispkvhds57tjdnlhfd7zpgu6q4ckcinungm

**Comment by cryptowhizzard** [comment]
I don't see where this improvement is coming from tbh.

Recv 0 B, Paid 0 FIL, Open (New), 1ms [1692105002195743737|0]
Recv 0 B, Paid 0 FIL, DealProposed (WaitForAcceptance), 13ms [1692105002195743737|0]
Recv 0 B, Paid 0 FIL, DealRejected (RetryLegacy), 610ms [1692105002195743737|0]
Recv 0 B, Paid 0 FIL, DealProposed (WaitForAcceptanceLegacy), 633ms [1692105002195743737|0]
Recv 0 B, Paid 0 FIL, Open (New), 0s [1692105002195743738|0]
Recv 0 B, Paid 0 FIL, DealProposed (WaitForAcceptance), 24ms [1692105002195743738|0]
Recv 0 B, Paid 0 FIL, DealRejected (Rejecting), 1.223s [1692105002195743737|0]
Recv 0 B, Paid 0 FIL, BlockstoreFinalized (Rejected), 1.241s [1692105002195743737|0]
ERROR: Retrieval Proposal Rejected: deal rejected: there is no unsealed piece containing payload cid bafybeibezwkhiwuunxjku7uzjbm75hmgkve2zzo4nkettcbg72olqkno7a

Recv 0 B, Paid 0 FIL, DealRejected (RetryLegacy), 598ms [1692105002195743738|0]
Recv 0 B, Paid 0 FIL, DealProposed (WaitForAcceptanceLegacy), 610ms [1692105002195743738|0]
Recv 0 B, Paid 0 FIL, DealRejected (Rejecting), 2.681s [1692105002195743738|0]
Recv 0 B, Paid 0 FIL, BlockstoreFinalized (Rejected), 2.687s [1692105002195743738|0]
ERROR: Retrieval Proposal Rejected: deal rejected: there is no unsealed piece containing payload cid bafybeibezwkhiwuunxjku7uzjbm75hmgkve2zzo4nkettcbg72olqkno7a

Retrievals over http are in Kbit/s.

![Scherm­afbeelding 2023-08-15 om 15 14 42](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/36404435/2b70abf2-6349-494f-8f21-09412c236f98)

**Comment by cryptowhizzard** [comment]
![Scherm­afbeelding 2023-08-15 om 15 19 09](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/36404435/1f326c46-da18-4812-893d-4d2e64ac5110)

Since range headers are also disabled I submitted a dispute.

@hail100 please enable range headers again ( it is default enabled in Boost ) to make sure when a timeout occurs the download can restart where it left of. Also provide readily retrieval ( minimum speed in Mbit/s , not 56K6 modem speed please ).

**Comment by jinyexon** [comment]
checker:manualTrigger

**Comment by hail100** [comment]
checker:manualTrigger

**Comment by lyjmry** [comment]
checker:manualTrigger

**Comment by hail100** [comment]
We are already working on fixing the issue with this retrieval. The report from the robot has indicated the problem, and it seems that the rules do not explicitly require enforcing the activation of range headers. What do we need to do to proceed?

**Comment by jinyexon** [comment]
checker:manualTrigger

**Comment by cryptowhizzard** [comment]
> We are already working on fixing the issue with this retrieval. The report from the robot has indicated the problem, and it seems that the rules do not explicitly require enforcing the activation of range headers. What do we need to do to proceed?

Good working retrieval. 

Stop gaming , play by the rules.

**Comment by jinyexon** [comment]
checker:manualTrigger

**Comment by jinyexon** [comment]
checker:manualTrigger

**Comment by Filplus-govteam** [comment]
Hello @hail100  per the new guidelines https://github.com/filecoin-project/notary-governance/issues/922 for Open Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

This information will be reviewed by Fil+ Governance team to confirm validity toward the Fil+ guideline of a distributed storage plan and SPs posted in the comments here. Let us know if you have any questions.

**Comment by jinyexon** [comment]
checker:manualTrigger

**Comment by cryptowhizzard** [comment]
Very cool surveillance data

I managed to get a partial file from you. It can be downloaded here:

http://www.datasetcreators.com/1485-f01999075-f02098006-50578232-baga6ea4seaqo2jhxkpdb4ucuhdemer5z3gqeh3o7ltousuhs3jipxlpawnyagga

Question ... Why are you storing junk data and scamming the community?

<img width="851" alt="Scherm­afbeelding 2023-08-23 om 19 50 52" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/36404435/71894c31-210c-4ac1-a88e-a98d3b6ceded">

**Comment by raghavrmadya** [comment]
Retrieval sampling evidence by notary shows discrepancy in data stored and no response to address the [dispute](https://www.notion.so/filecoin/SP-s-are-not-proving-readily-retrieval-12cda563f2a444ac856adbce7adaefbe?pvs=4) 

Flagging for DC removal and proceeding with closure
