### ISSUE TITLE
[DataCap Application] WEI Tianmu lake

### ISSUE THREAD

**Issue by wulumuqird** [filecoin-project/filecoin-plus-large-datasets#1494]
### Data Owner Name

WEI Tianmu lake

### Data Owner Country/Region

China

### Data Owner Industry

Construction, Property & Real Estate

### Website

http://weiretreat.com/

### Social Media

```text
https://weibo.com/u/6268042078?from=page_100505_profile&wvr=6&mod=like
```

### Total amount of DataCap being requested

4PiB

### Weekly allocation of DataCap requested

150TiB

### On-chain address for first allocation

f1ixhebrcng2k4vfbd6bcbt5djiquvmonx44sbvwa

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
WEI Retreat Tianmu Lake is located on the shores of Tianmu Lake, known as the "Pearl of the South", at the junction of Jiangsu, Zhejiang and Anhui.
It is a high-end resort hotel under WEI, a new luxury hotel brand in China. The overall architectural style has a strong classical oriental flavor, with more than 30 simple and elegant rooms and suites, which can enjoy the best view.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
Promotional materials/construction data/ hotel images
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### How do you plan to prepare the dataset

lotus

### Please share a sample of the data

```text
https://1drv.ms/u/s!AhE5Jd-aoIroaYqY-FR3EAKOq-E?e=HioFuV
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Sporadic

### For how long do you plan to keep this dataset stored on Filecoin

2 to 3 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China

### How will you be distributing your data to storage providers

HTTP or FTP server, Shipping hard drives

### How do you plan to choose storage providers

I don't know yet

### How do you plan to make deals to your storage providers

Boost client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
Please provide enough detailed data sources to prove that you have 4PB data. Can you explain your data composition? How many copies will you store?
What's the relationship between you and the organization? 
Can you provide more detailed information about other storage providers participated in this program, such as you can list SPs you have contacted with at present? Whether the sps you choose can support data retrieval?

**Comment by simonkim0515** [comment]
## Datacap Request Trigger

#### Total DataCap requested 
> 4PiB

#### Expected weekly DataCap usage rate 
> 150TiB 

#### Client address
> f1ixhebrcng2k4vfbd6bcbt5djiquvmonx44sbvwa

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Looking at your application i have some questions:
As you are brand new on Github and have no history of past applications it seems to me that applying for 5PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?

Can you show us visible proof of the size of your data and the storage systems you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230337462961356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!
