### ISSUE TITLE
[DataCap Application] Shenzhen Liberty City Culture Media Co., Ltd.

### ISSUE THREAD

**Issue by 001can** [filecoin-project/filecoin-plus-large-datasets#1495]
### Data Owner Name

Shenzhen Liberty City Culture Media Co., Ltd.

### Data Owner Country/Region

China

### Data Owner Industry

Information, Media & Telecommunications

### Website

http://www.whballoon.com/

### Social Media

```text
http://www.whballoon.com/
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

500TiB

### On-chain address for first allocation

f1mrqexd4z6oxrvzeuthlf4n2jf6m64abonhhchya

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Liberty City Culture Media Co., Ltd. is a cultural product provider with market insight as the starting point, value communication as the core, and unique creativity as the main competitiveness.
Focusing on video shooting and production, it covers brand commercials, product commercials, corporate promotional videos and other types.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
Various types of original materials such as brand commercials, product commercials, corporate promotional videos, etc.
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### How do you plan to prepare the dataset

IPFS, lotus

### Please share a sample of the data

```text
https://www.aliyundrive.com/s/SnnuBDbrnYA
https://www.aliyundrive.com/s/9UD9jQN56c9
https://www.aliyundrive.com/s/T2xdLn9NsK5
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

More than 3 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China

### How will you be distributing your data to storage providers

HTTP or FTP server, Shipping hard drives

### How do you plan to choose storage providers

Slack

### How do you plan to make deals to your storage providers

Lotus client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
How much data do you have? How many copies will you store?
What's the relationship between you and the organization?

**Comment by herrehesse** [comment]
Dear Applicant,

Due to the increased amount of erroneous/wrong Filecoin+ data recently, on behalf of the entire community, we feel compelled to go deeper into datacap requests. Hereby to ensure that the overall value of the Filecoin network and Filecoin+ program increases and is not abused.

Please answer the questions below as comprehensively as possible.

**Customer data**

- Could you demonstrate exactly how and to what extent customer contact occurred? 

We expect that for the onboarding of customers with the scale of an LDN there would have been at least multiple email and perhaps several chat conversations preceding it. A single email with an agreement does not qualify here.

- Did the customer specify the amount of data involved in this relevant correspondence?

- Why does the customer in question want to use the Filecoin+ program? 

_Should this only be soley for acquiring datacap this is of course **out of the question**. The customer must have a legitimate reason for wanting to use the Filecoin+ program which is intended as a program to store useful and public datasets on the network._ 

- Why is the customer data considered Filecoin+ eligible?

_(As an intermediate solution Filecoin offers the FIL-E program or the glif.io website for business datasets that do not meet the requirements for a Filecoin+ dataset)_


**Files and Processing**

- Could you please demonstrate to us how you envision processing and transporting the customer data in question to any location for preparation?
- Would you demonstrate to us that the customer, the preparer and the intended storage providers all have adequate bandwidth to process the set with its corresponding size?
- Would you tell us how the data set preparer takes into account the prevention of duplicates in order to prevent data cap abuse?


Hopefully you understand the caution the overall community has for onboarding the wrong data. We understand the increased need for Filecoin+, however, we must not allow the program to be misused. Everything depends on a valuable and useful network, let's do our best to make this happen. Together.

**Comment by cryptowhizzard** [comment]
Hello @001can 

Are you a direct employee of Shenzhen Liberty City Culture Media Co., Ltd. because you state that you are responsible for the technical architecture of the company?

Does Shenzhen Liberty City Culture Media Co., Ltd. have enough resources to pack all the data into distributable files to make storage deals with and what software tools is Shenzhen Liberty City Culture Media Co., Ltd. going to use for this?
In what timeframe do you want to distribute all the data and how?

Does Shenzhen Liberty City Culture Media Co., Ltd. have it's own Filecoin nodes / hardware operational and if so can you tell us what it consists of?

**Comment by herrehesse** [comment]
@001can You describe the content as:

"Various types of original materials such as brand commercials, product commercials, corporate promotional videos, etc."

These types of request should be done through FIL-E.
Filecoin+ LDN is not the right place.

**Comment by cryptowhizzard** [comment]
> > Looking at the internet archive i located your website [www.whballoon.com](http://www.whballoon.com) 3 times. Between 2018 and 2021 it looked like this:
> > ![Scherm­afbeelding 2023-01-05 om 14 58 48](https://user-images.githubusercontent.com/36404435/210797360-7e17354e-fafb-4c8d-97ff-078177a9c125.png) ![Scherm­afbeelding 2023-01-05 om 14 59 17](https://user-images.githubusercontent.com/36404435/210797365-e5784e31-e047-4046-a7e6-d8a3ca43ae94.png)
> 
> What website was built before this domain name has nothing to do with us. We created the website in the first half of 2022.

This is not how it works. When you are the new owner of this website the who-is record in the domain registry is updated accordingly to the new owner. This record has not been updated since 2015.

https://who.is/whois/whballoon.com

LTD company’s are from the United Kingdom. LCC’s are from China. I highly doubt this request is legitimate.

**Comment by lvschouwen** [comment]
@001can 
All 3 links provided as sample data cannot be opened without a account and hence the data cannot be verified.
Can you provide use with links that can publicly opened?

**Comment by hyunmoon** [comment]
Nope. This kind of dataset should be stored as unverified deals.

**Comment by herrehesse** [comment]
Agreed with @hyunmoon here.

**Comment by herrehesse** [comment]
@001can Regular deals on the Filecoin network, most storage providers take them for about 1/100th of the price of AWS right now.

**Comment by herrehesse** [comment]
Ofcourse friend, here you go: https://filecoin.io/blog/posts/how-storage-and-retrieval-deals-work-on-filecoin/
Come back to me when you have follow-up questions.

**Comment by hyunmoon** [comment]
https://filplus.storage/faq

**Comment by herrehesse** [comment]
Filecoin+ is meant for datasets that are public, open, and mission aligned with Filecoin's "Storing humanities most important information". 

Filecoin itself can be used to store all types of data, but you won't get datacap for these files.

**Comment by hyunmoon** [comment]
Simply put, what we're saying is you should pay the storage providers directly to get your data stored just as you would do with any traditional cloud storage providers.
Because verified deals provide x10 quality adjusted power, verified deals are accepted for free (or at a premium) by the storgae providers.
The x10 quality adjusted power is given as a reward for dataset that will incrase the value of the filecoin network.
Your dataset is not considered one of those that's why your dataset should be stored as unverified (or regular) deals.

**Comment by herrehesse** [comment]
@001can This is indeed our opinion too.

**Comment by hyunmoon** [comment]
Well, lucky for them and unlucky for you.
It is up to the elected notaries to judege if your dataset applies to FIL+.
Because some people got away with the rule doesn't mean everyone should be free from the rule.
https://github.com/filecoin-project/notary-governance/tree/main/notaries

**Comment by herrehesse** [comment]
@001can It is a three-part dilemma. 

On the one hand, a lot of data needs to be put on Filecoin to show the world how useful we are. The more the better.

On the other hand, there is extremely much data that has absolutely no value and can be easily uploaded or faked. 
_( I have seen many spoofed / empty sectors - referring to 15P raw from slingshot)_

And lastly, many users want to abuse the Filecoin+ program because of the data cap and the rewards involved.

**Comment by lvschouwen** [comment]
@001can 
You seem to be more interested in fighting @herrehesse then fixing your application and providing the community with sample data that can be checked.
I therefor advice all notaries to not sign this application as is until this is fixed and this childish trowing mud stops.

**Comment by cryptowhizzard** [comment]
> I read https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0003.md https://github.com/filecoin-project/notary-governance/tree/main/notaries https://github.com/filecoin-project/filecoin-plus-large-datasets, the vision for filecoin+ is described as "the dataset should be public, open, and mission aligned with Filecoin and Filecoin Plus . This also means that the data should be accessible to anyone in the network, without requiring any special permissions or access requirement stored data should be readily retrievable on the network and this should be regularly verified (though the use of manual or automated verification that includes retrieving data from various miners over the course of the DataCap allocation timeframe";
> 
> and such "Notary Sets Use Cases Support (1) or more the following, which can be linked to in a separate doc: Professional Services (Hosting Reseller, Long-term Backups, Data Warehousing) Developer Tools (Package Managers, Automatic Notaries, Web2 to Web3 integrations) Decentralized Applications User Content (Personal Storage) Public or Open Data (Scientific datasets, research data, government or historical Media & Entertainment (Videos, photos, NFTs)"; and "The ultimate goal of Filecoin Plus is to accelerate the proliferation of products and compliant use cases on Filecoin with both geographic and use case diversity. Filecoin Plus provides the framework and incentive for business development to happen on Filecoin. After all, adoption is more than just technology. Client needs and legitimate use cases will shape the goods and services produced on Filecoin.”
> 
> What's wrong with our data?

You are confusing notary use cases ( a usecase the notary specialises in and given in his specific application to become a notary ) and the fil+ program. Notary’s also help with Fil-E .. this is where these fields of experise come in handy for a customer to select a notary for his business case.

**Comment by simonkim0515** [comment]
## Datacap Request Trigger

#### Total DataCap requested 
> 5PiB

#### Expected weekly DataCap usage rate 
> 500TiB 

#### Client address
> f1mrqexd4z6oxrvzeuthlf4n2jf6m64abonhhchya

**Comment by zcfil** [comment]
After reading history, I have some questions：
1. Can I show more data？
2. Is your data publicly available？

**Comment by zcfil** [comment]
@001can  I clicked on the link and found that there was only a small amount of video data. Can you provide more data samples?

**Comment by zcfil** [comment]
Hi @001can 
 I looked at the new data sample.

How will you allocate this data, which cities do you plan to store data in, and which data storage vendors do you currently have with you.

I look forward to hearing from you.

**Comment by a1991car** [comment]
Can you email filplus-app-review@fil.org using your official domain name to confirm your identity?Email name should contain Issue ID #1495.

**Comment by a1991car** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecm4nu3bs3ivh7gdy7h57phm237xfq2u5ypb7jhfasa22hqxbvqhg 
#### Address 
> f1mrqexd4z6oxrvzeuthlf4n2jf6m64abonhhchya
#### Datacap Allocated
> 250.00TiB
#### Signer Address
> f1qnumecdypgrbaebtkdfjnwt5ndacadcuas3deiq
#### Id
> 503b4627-102e-4591-a204-4c44a0ed4c5a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecm4nu3bs3ivh7gdy7h57phm237xfq2u5ypb7jhfasa22hqxbvqhg

**Comment by zcfil** [comment]
@galen-mcandrew @raghavrmadya @Kevin-FF-USA Because my hardware wallet has not been updated to the multi signature address f02049625 for a long time, my signature using the lotus command did not trigger the following robot message reply. I mentioned it to RG before, but it still hasn't been resolved. I'm confused

### Request Approve
Your Datacap Allocation Request has been proposed by the Notary

**Message sent to Filecoin Network**
> bafy2bzacealntbwrtsd2vvcuwlhiz7cg4jyx2azn2hz3smdsdcrmppdz2o73s

**Address**
> f1mrqexd4z6oxrvzeuthlf4n2jf6m64abonhhchya

**Datacap Allocated**
> 250.00TiB

**Signer Address**
> f17xummecmkqgjhm4fesktesaieumn7ugarwucwty

**Id**
> none

**You can check the status of the message here:** https://filfox.info/en/message/bafy2bzacedxw2yhr2yk4ocd2g57n3kas2w4urvamac3kpjetc7qzvynmyefrq

**Comment by maxvint** [comment]
checker:manualTrigger

**Comment by woshidama323** [comment]
checker:manualTrigger

**Comment by woshidama323** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedwdemoqbj5nmgfq4ta4u6zwoshqcrw6vszzvzghljkmxrpgf4glm 
#### Address 
> f1mrqexd4z6oxrvzeuthlf4n2jf6m64abonhhchya
#### Datacap Allocated
> 250.00TiB
#### Signer Address
> f12tk3adljauwnd3hjbigpfxb7b7gdlj63p6afwtq
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedwdemoqbj5nmgfq4ta4u6zwoshqcrw6vszzvzghljkmxrpgf4glm

**Comment by maxvint** [comment]
Data distribution looks good, and check all the boxes, retrieval also works very well, willing to support.

<img width="921" alt="image" src="https://user-images.githubusercontent.com/1715211/233524423-7e831138-8c11-4a4f-900d-bea19b406108.png">

<img width="876" alt="image" src="https://user-images.githubusercontent.com/1715211/233525890-874413c3-2542-4d0c-99cf-3f2c8b5f2eb2.png">

<img width="877" alt="image" src="https://user-images.githubusercontent.com/1715211/233526488-b2d5b7e9-bdb1-40ce-b487-c8bf4c8de360.png">

**Comment by maxvint** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec3fmp63bxgncp5te3ebqrt2odaoxrh7j23hoocfgbe4vozl7eje6 
#### Address 
> f1mrqexd4z6oxrvzeuthlf4n2jf6m64abonhhchya
#### Datacap Allocated
> 250.00TiB
#### Signer Address
> f1ui5iy4mmkxjbw7752omiwp2ols2fzv4thrayagi
#### Id
> 503b4627-102e-4591-a204-4c44a0ed4c5a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec3fmp63bxgncp5te3ebqrt2odaoxrh7j23hoocfgbe4vozl7eje6

**Comment by sxxfuture-official** [comment]
checker:manualTrigger

**Comment by sxxfuture-official** [comment]
CID-Checker shows everything well
and the data retrieve testing result as follows:
![image](https://user-images.githubusercontent.com/113963951/237035100-4b20a10e-d68d-450f-aeed-61042bc651b9.png)
![image](https://user-images.githubusercontent.com/113963951/237039427-48365326-06dc-417b-b10a-4a468382911f.png)

@001can  Next round sealing, you should add more SPs into this project, 3 SP will not enougth .

**Comment by sxxfuture-official** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedmhkmlebrdwk54vzrctmhivizfsfzvbh4dhbifnnrvil6qwu2vno 
#### Address 
> f1mrqexd4z6oxrvzeuthlf4n2jf6m64abonhhchya
#### Datacap Allocated
> 1000.00TiB
#### Signer Address
> f1foiomqlmoshpuxm6aie4xysffqezkjnokgwcecq
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedmhkmlebrdwk54vzrctmhivizfsfzvbh4dhbifnnrvil6qwu2vno

**Comment by newwebgroup** [comment]
checker:manualTrigger

**Comment by newwebgroup** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb3riuhaky4qq265iuwx5kn5yjs4d7qnjfhp7ms36j5ujp5is3okq 
#### Address 
> f1mrqexd4z6oxrvzeuthlf4n2jf6m64abonhhchya
#### Datacap Allocated
> 1000.00TiB
#### Signer Address
> f1e77zuityhvvw6u2t6tb5qlnsegy2s67qs4lbbbq
#### Id
> 81c43253-575d-4262-b6b7-c1aef75c7744
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb3riuhaky4qq265iuwx5kn5yjs4d7qnjfhp7ms36j5ujp5is3okq

**Comment by cryptowhizzard** [comment]
Hello,

It seems that some of your SP's went offline. Can you bring them online again to enable retrieval?

cat 1495-f02100670-f01738789-43761618-baga6ea4seaqdi5dywmr2wrsieo3ywsy2eqf4o46zqzbuifnyas7d4fn3mqmmafy.log
2023-07-26T22:53:49.472+0200	WARN	rpc	go-jsonrpc@v0.3.1/client.go:615	unmarshaling failed	{"message": "{\"Err\":\"exhausted 5 attempts but failed to open stream, err: failed to dial 12D3KooWHPD3nMavfuVZsn7de9FNBGCfottBQLFMEqpJxoewTScq:\\n  * [/ip4/160.86.241.170/tcp/18140] dial tcp4 160.86.241.170:18140: connect: connection refused\",\"Root\":null,\"Piece\":null,\"Size\":0,\"MinPrice\":\"\\u003cnil\\u003e\",\"UnsealPrice\":\"\\u003cnil\\u003e\",\"PricePerByte\":\"\\u003cnil\\u003e\",\"PaymentInterval\":0,\"PaymentIntervalIncrease\":0,\"Miner\":\"f01738789\",\"MinerPeer\":{\"Address\":\"f01738789\",\"ID\":\"12D3KooWHPD3nMavfuVZsn7de9FNBGCfottBQLFMEqpJxoewTScq\",\"PieceCID\":null}}"}
2023-07-26T22:53:49.473+0200	INFO	retry	retry/retry.go:17	Retrying after error:RPC client error: unmarshaling result: failed to parse big string: '"\u003cnil\u003e"'
2023-07-26T22:55:57.625+0200	WARN	rpc	go-jsonrpc@v0.3.1/client.go:615	unmarshaling failed	{"message": "{\"Err\":\"exhausted 5 attempts but failed to open stream, err: failed to dial 12D3KooWHPD3nMavfuVZsn7de9FNBGCfottBQLFMEqpJxoewTScq:\\n  * [/ip4/160.86.241.170/tcp/18140] dial tcp4 160.86.241.170:18140: connect: connection refused\",\"Root\":null,\"Piece\":null,\"Size\":0,\"MinPrice\":\"\\u003cnil\\u003e\",\"UnsealPrice\":\"\\u003cnil\\u003e\",\"PricePerByte\":\"\\u003cnil\\u003e\",\"PaymentInterval\":0,\"PaymentIntervalIncrease\":0,\"Miner\":\"f01738789\",\"MinerPeer\":{\"Address\":\"f01738789\",\"ID\":\"12D3KooWHPD3nMavfuVZsn7de9FNBGCfottBQLFMEqpJxoewTScq\",\"PieceCID\":null}}"}
2023-07-26T22:55:57.626+0200	INFO	retry	retry/retry.go:17	Retrying after error:RPC client error: unmarshaling result: failed to parse big string: '"\u003cnil\u003e"'
2023-07-26T22:58:06.147+0200	WARN	rpc	go-jsonrpc@v0.3.1/client.go:615	unmarshaling failed	{"message": "{\"Err\":\"exhausted 5 attempts but failed to open stream, err: failed to dial 12D3KooWHPD3nMavfuVZsn7de9FNBGCfottBQLFMEqpJxoewTScq:\\n  * [/ip4/160.86.241.170/tcp/18140] dial tcp4 160.86.241.170:18140: connect: connection refused\",\"Root\":null,\"Piece\":null,\"Size\":0,\"MinPrice\":\"\\u003cnil\\u003e\",\"UnsealPrice\":\"\\u003cnil\\u003e\",\"PricePerByte\":\"\\u003cnil\\u003e\",\"PaymentInterval\":0,\"PaymentIntervalIncrease\":0,\"Miner\":\"f01738789\",\"MinerPeer\":{\"Address\":\"f01738789\",\"ID\":\"12D3KooWHPD3nMavfuVZsn7de9FNBGCfottBQLFMEqpJxoewTScq\",\"PieceCID\":null}}"}
2023-07-26T22:58:06.147+0200	INFO	retry	retry/retry.go:17	Retrying after error:RPC client error: unmarshaling result: failed to parse big string: '"\u003cnil\u003e"'
2023-07-26T23:00:30.827+0200	WARN	rpc	go-jsonrpc@v0.3.1/client.go:615	unmarshaling failed	{"message": "{\"Err\":\"exhausted 5 attempts but failed to open stream, err: failed to dial 12D3KooWHPD3nMavfuVZsn7de9FNBGCfottBQLFMEqpJxoewTScq:\\n  * [/ip4/160.86.241.170/tcp/18140] dial tcp4 160.86.241.170:18140: connect: connection refused\",\"Root\":null,\"Piece\":null,\"Size\":0,\"MinPrice\":\"\\u003cnil\\u003e\",\"UnsealPrice\":\"\\u003cnil\\u003e\",\"PricePerByte\":\"\\u003cnil\\u003e\",\"PaymentInterval\":0,\"PaymentIntervalIncrease\":0,\"Miner\":\"f01738789\",\"MinerPeer\":{\"Address\":\"f01738789\",\"ID\":\"12D3KooWHPD3nMavfuVZsn7de9FNBGCfottBQLFMEqpJxoewTScq\",\"PieceCID\":null}}"}
2023-07-26T23:00:30.828+0200	INFO	retry	retry/retry.go:17	Retrying after error:RPC client error: unmarshaling result: failed to parse big string: '"\u003cnil\u003e"'
2023-07-26T23:02:25.962+0200	WARN	rpc	go-jsonrpc@v0.3.1/client.go:615	unmarshaling failed	{"message": "{\"Err\":\"exhausted 5 attempts but failed to open stream, err: failed to dial 12D3KooWHPD3nMavfuVZsn7de9FNBGCfottBQLFMEqpJxoewTScq:\\n  * [/ip4/160.86.241.170/tcp/18140] dial tcp4 160.86.241.170:18140: connect: connection refused\",\"Root\":null,\"Piece\":null,\"Size\":0,\"MinPrice\":\"\\u003cnil\\u003e\",\"UnsealPrice\":\"\\u003cnil\\u003e\",\"PricePerByte\":\"\\u003cnil\\u003e\",\"PaymentInterval\":0,\"PaymentIntervalIncrease\":0,\"Miner\":\"f01738789\",\"MinerPeer\":{\"Address\":\"f01738789\",\"ID\":\"12D3KooWHPD3nMavfuVZsn7de9FNBGCfottBQLFMEqpJxoewTScq\",\"PieceCID\":null}}"}
2023-07-26T23:02:25.962+0200	ERROR	retry	retry/retry.go:29	Failed after 5 attempts, last error: RPC client error: unmarshaling result: failed to parse big string: '"\u003cnil\u003e"'
ERROR: RPC client error: unmarshaling result: failed to parse big string: '"\u003cnil\u003e"'

![Scherm­afbeelding 2023-07-28 om 14 41 32](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/36404435/c6821099-4556-4a96-a6d5-ac5e0f623658)

**Comment by ipollo00** [comment]
Since the last tranche now is 3 months ago, even though the report has a warning on data replication, the number of backups has significantly increased, which is acceptable to me.
However, Strongly suggest your sps can widely accept HTTP retrieval. I will keep following up on this form.

**Comment by ipollo00** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced5jp7mp7jotbh7i4u4yandfvokwoissu4k6haveqxe74msmy6pac 
#### Address 
> f1mrqexd4z6oxrvzeuthlf4n2jf6m64abonhhchya
#### Datacap Allocated
> 1.95PiB
#### Signer Address
> f1n5wlrrhoxpkgwij25xrtt7w7g2k3fhbthmdn6ri
#### Id
> dfa8fc7e-d016-40d7-a2b0-b263f1d6788a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced5jp7mp7jotbh7i4u4yandfvokwoissu4k6haveqxe74msmy6pac

**Comment by METAVERSEDATAMINING** [comment]
Data can be retrieved.
<img width="714" alt="11" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/111408360/169d8a6c-9118-4990-b9b8-1015fdb8c325">

>56.02% of deals are for data replicated across less than 4 storage providers.

@001can This round of data backup needs to be significantly improved.I'll sign this round

**Comment by METAVERSEDATAMINING** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecuxpmepoq46u477wghckku726wim6ulwzjhlcv3mhxd4ijd77t5a 
#### Address 
> f1mrqexd4z6oxrvzeuthlf4n2jf6m64abonhhchya
#### Datacap Allocated
> 1.95PiB
#### Signer Address
> f17idrnfnxl2mbgcgr57a6z2c6lj2qx56gvm3336i
#### Id
> dfa8fc7e-d016-40d7-a2b0-b263f1d6788a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecuxpmepoq46u477wghckku726wim6ulwzjhlcv3mhxd4ijd77t5a

**Comment by cryptowhizzard** [comment]
I have downloaded some of the data available and unpacked here:

http://www.datasetcreators.com/downloadedcarfiles/1495-f02100670-f01261218-49563095-baga6ea4seaqhx2aqnrlpuchiz3xsqjhhjcvpzbhvw7rpqgpph5u2a4gkuisrmay

Seems to me you are not storing the data that you were telling us you were going to store.

![Scherm­afbeelding 2023-08-21 om 14 08 37](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/36404435/613df9fc-56ae-4e12-9783-672ce13f5bff)

**Comment by Carohere** [comment]
@001can  Could you confirm this file?  http://www.datasetcreators.com/downloadedcarfiles/1495-f02100670-f01261218-49563095-baga6ea4seaqhx2aqnrlpuchiz3xsqjhhjcvpzbhvw7rpqgpph5u2a4gkuisrmay

**Comment by raghavrmadya** [comment]
https://www.notion.so/filecoin/Applicant-not-storing-the-data-promised-4defffb5a564422494af9f68463e8a57?pvs=4

**Comment by raghavrmadya** [comment]
As client has confirmed non-compliance with the Fil+ guidelines, all DC must be removed from this client's wallet. 

The involved SP IDs have been blacklisted as client has flagged negligent behavior on the part of the SPs.
