### ISSUE TITLE
[DataCap Application] Chengyou Tech

### ISSUE THREAD

**Issue by Xavierr4** [filecoin-project/filecoin-plus-large-datasets#1498]
### Data Owner Name

Chengyou Tech

### Data Owner Country/Region

China

### Data Owner Industry

IT & Technology Services

### Website

www.qiangdi.net

### Social Media

```text
www.qiangdi.net
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

200TiB

### On-chain address for first allocation

f1oajib3g6npbw6jl4rqrhq5sr5i4kmxrdtjmjx6a

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Our company is mainly engaged in software technology outsourcing services, big data technology services, AI and mobile application development, enterprise intellectual property services, digital processing of confidential files and other businesses.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
We have accumulated a large number of product images and video resources in our business of outsourcing technical services and online shopping mall business. To store this data more securely, we choose to store it in filecoin.
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### How do you plan to prepare the dataset

lotus

### Please share a sample of the data

```text
Dataset:
https://1drv.ms/u/s!AhJEdfyS4P8macyIUOoZ_LbQBAY?e=noYXAz
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Sporadic

### For how long do you plan to keep this dataset stored on Filecoin

2 to 3 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, Europe, North America

### How will you be distributing your data to storage providers

Shipping hard drives

### How do you plan to choose storage providers

Slack, Big data exchange

### How do you plan to make deals to your storage providers

I don't know yet

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
There are very few goods on your online shopping mall, so it is difficult to judge the amount of data you have based on the data samples you provide. 
Can you explain your data composition and provide sufficient data samples separately? How many copies will you store?
What's the relationship between you and the organization? 
Can you provide more detailed information about other storage providers participated in this program, such as you can list SPs you have contacted with at present? Whether the sps you choose can support data retrieval?

**Comment by Xavierr4** [comment]
Hello @Sunnyiscoming In fact, in addition to the videos and images shown on the website, there is a lot of data that needs to be stored that is not displayed. Some of these data is content that has been displayed in the past, and some will be displayed on the website in the future. The data is mainly divided into pictures of product information, advertisement videos, etc. I have grouped and uploaded these data samples by product brand, which you can view through this link. I'm an employee of Chengyou. We plan store 10 copies for business. https://1drv.ms/u/s!AhJEdfyS4P8macyIUOoZ_LbQBAY?e=noYXAz
We are actively contacting more eligible sps!

**Comment by herrehesse** [comment]
Dear Applicant,

Due to the increased amount of erroneous/wrong Filecoin+ data recently, on behalf of the entire community, we feel compelled to go deeper into datacap requests. Hereby to ensure that the overall value of the Filecoin network and Filecoin+ program increases and is not abused.

Please answer the questions below as comprehensively as possible.

**Customer data**

- Could you demonstrate exactly how and to what extent customer contact occurred? 

We expect that for the onboarding of customers with the scale of an LDN there would have been at least multiple email and perhaps several chat conversations preceding it. A single email with an agreement does not qualify here.

- Did the customer specify the amount of data involved in this relevant correspondence?

- Why does the customer in question want to use the Filecoin+ program? 

_Should this only be soley for acquiring datacap this is of course **out of the question**. The customer must have a legitimate reason for wanting to use the Filecoin+ program which is intended as a program to store useful and public datasets on the network._ 

- Why is the customer data considered Filecoin+ eligible?

_(As an intermediate solution Filecoin offers the FIL-E program or the glif.io website for business datasets that do not meet the requirements for a Filecoin+ dataset)_


**Files and Processing**

- Could you please demonstrate to us how you envision processing and transporting the customer data in question to any location for preparation?
- Would you demonstrate to us that the customer, the preparer and the intended storage providers all have adequate bandwidth to process the set with its corresponding size?
- Would you tell us how the data set preparer takes into account the prevention of duplicates in order to prevent data cap abuse?


Hopefully you understand the caution the overall community has for onboarding the wrong data. We understand the increased need for Filecoin+, however, we must not allow the program to be misused. Everything depends on a valuable and useful network, let's do our best to make this happen. Together.

**Comment by simonkim0515** [comment]
## Datacap Request Trigger

#### Total DataCap requested 
> 5PiB

#### Expected weekly DataCap usage rate 
> 200TiB 

#### Client address
> f1oajib3g6npbw6jl4rqrhq5sr5i4kmxrdtjmjx6a

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Looking at your application i have some questions:
As you are brand new on Github and have no history of past applications it seems to me that applying for 5PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?

Can you show us visible proof of the size of your data and the storage systems you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230232885049356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!

**Comment by swatchliu** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaqmf6wakznsxzqeeqboo4k2zuyac5hyj2unecfqkxb2kk6b6zgju 
#### Address 
> f1oajib3g6npbw6jl4rqrhq5sr5i4kmxrdtjmjx6a
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1yh6q3nmsg7i2sys7f7dexcuajgoweudcqj2chfi
#### Id
> d3066cd4-206e-4346-9466-87c6f193779b
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaqmf6wakznsxzqeeqboo4k2zuyac5hyj2unecfqkxb2kk6b6zgju

**Comment by BlockMakeronline** [comment]
You said you accumulated a large number of product images and video resources in our business of outsourcing technical services and online shopping mall business.  Do you have sufficient intellectual property rights over these data?
We also want to know the SPs list, could you provide it?

**Comment by BlockMakeronline** [comment]
OK, I'd like to sign.
However, it is recommended that SPs be confirmed ASAP and stored data according to community rules.

**Comment by BlockMakeronline** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebhk6rjjpgr7yhgdxrxwv7xlnamacfy22ntowubh64xkx64vv22le 
#### Address 
> f1oajib3g6npbw6jl4rqrhq5sr5i4kmxrdtjmjx6a
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1o3twrcpwjtpcd4q36lpq4qmy2qfbgtyy5h6tsty
#### Id
> d3066cd4-206e-4346-9466-87c6f193779b
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebhk6rjjpgr7yhgdxrxwv7xlnamacfy22ntowubh64xkx64vv22le

**Comment by fabriziogianni7** [comment]
## DataCap Allocation requested

#### Multisig Notary address
> f01858410

#### Client address
> f1oajib3g6npbw6jl4rqrhq5sr5i4kmxrdtjmjx6a

#### DataCap allocation requested
> 200TiB

#### Id
> d3066fr4-212e-4446-9466-67c7f193779h

**Comment by UnionLabs2020** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceds7cfzaofisnqfo32t2ocd4qxpg2sn4qhbbcaedik226itkek4d4 
#### Address 
> f1oajib3g6npbw6jl4rqrhq5sr5i4kmxrdtjmjx6a
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f17xdri3wunqgld7dm23e4f3eqsntjakwc47xjo6i
#### Id
> d3066fr4-212e-4446-9466-67c7f193779h
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceds7cfzaofisnqfo32t2ocd4qxpg2sn4qhbbcaedik226itkek4d4

**Comment by kevzak** [comment]
checker:manualTrigger

**Comment by TakiChain** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebk572ctag7mk2yl5pk6esahp5jozblqnv3ssa2ykjkdzssk3xdqq 
#### Address 
> f1oajib3g6npbw6jl4rqrhq5sr5i4kmxrdtjmjx6a
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f15impf3j2zcaex4lhyxndxswuuhv24vzstuqtxsi
#### Id
> 0f0b430e-4471-4386-9c30-683d562d38e9
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebk572ctag7mk2yl5pk6esahp5jozblqnv3ssa2ykjkdzssk3xdqq

**Comment by Casey-PG** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb63uqdq4jwhrzplfhmmric6awhk2fbuwfma25k7edl4nezwqrpu4 
#### Address 
> f1oajib3g6npbw6jl4rqrhq5sr5i4kmxrdtjmjx6a
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1d4yb3wags3mtddzesxoo63jv7dmlec3bq4yteni
#### Id
> 0f0b430e-4471-4386-9c30-683d562d38e9
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb63uqdq4jwhrzplfhmmric6awhk2fbuwfma25k7edl4nezwqrpu4

**Comment by Xavierr4** [comment]
checker:manualTrigger

**Comment by Xavierr4** [comment]
![122](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/120177081/aa05c2cd-1cf4-4b71-b791-3d0f7def062f)

Our SPs are supporting retrieval. Do the Checker Report need some time to update?

**Comment by xmcai2016** [comment]
The report needs a few days to show the increase in scores because it takes the average of retrieval data in the past few months since Retrieval Bot was launched. We are working on a self-serving portal to let you monitor real-time retrieval data. Stay tuned for updates on the release of the monitor dashboard.

**Comment by Suyanj** [comment]
Confirmed that retrieval is OK, willing to support.

**Comment by Suyanj** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecjyp6vyyvbacckzslgwosp6rwhqfigjhygpteqhbfqswsioyikse 
#### Address 
> f1oajib3g6npbw6jl4rqrhq5sr5i4kmxrdtjmjx6a
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1ihv7gz3vn3xqvikpt4rwryecgisl7745lodx3yi
#### Id
> fda55d68-fa87-4594-9901-6bf11ec41fd9
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecjyp6vyyvbacckzslgwosp6rwhqfigjhygpteqhbfqswsioyikse

**Comment by Filplus-govteam** [comment]
Hello @Xavierr4 per the https://github.com/filecoin-project/notary-governance/issues/922 for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

This information will be reviewed by Fil+ Governance team to confirm validity and then the application will be approved for notary review. Let us know if you have any questions.

**Comment by C00kies77** [comment]
checker:manualTrigger

**Comment by BobbyChoii** [comment]
I choose to trust this applicants, but the next round of retrieval data reports should be ready for an update.

**Comment by BobbyChoii** [comment]
I choose to trust this applicant, but the next round of retrieval data reports should be ready for an update. 
Don't disappoint me. Good luck!

**Comment by BobbyChoii** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecckbtqiulebxt2qgs7a3hfwfolubxuox3tu5s2tktpusakpiiepm 
#### Address 
> f1oajib3g6npbw6jl4rqrhq5sr5i4kmxrdtjmjx6a
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1irqs2gmctiv3jcdfwuch7oxvf4ixh3k4b2wc24i
#### Id
> fda55d68-fa87-4594-9901-6bf11ec41fd9
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecckbtqiulebxt2qgs7a3hfwfolubxuox3tu5s2tktpusakpiiepm

**Comment by herrehesse** [comment]
@BobbyChoii - You are signing while this application is under dispute.

@raghavrmadya @Kevin-FF-USA @dkkapur, I urge you to take immediate action to close and remove this content. This behavior is precisely what we are fighting against here - collusion and a complete disregard for rules. Please address this promptly.

**Comment by hyunmoon** [comment]
wow

**Comment by BobbyChoii** [comment]
No, it's not in the dispute form till now:
https://filecoin.notion.site/T-T-Dispute-Tracker-d28b93677cb544b48e77b585856601cf

**Comment by herrehesse** [comment]
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1498#issuecomment-1648350383

**Comment by Xavierr4** [comment]
Yes. keep open

**Comment by cryptowhizzard** [comment]
This application has issues. 

![Scherm­afbeelding 2023-08-16 om 14 10 38](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/36404435/03a98998-4f27-4f04-8c67-2245a34d172b)

**Comment by Filplus-govteam** [comment]
Hello @Xavierr4  per the new guidelines https://github.com/filecoin-project/notary-governance/issues/922 for Open Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

This information will be reviewed by Fil+ Governance team to confirm validity toward the Fil+ guideline of a distributed storage plan and SPs posted in the comments here. Let us know if you have any questions.

**Comment by Xavierr4** [comment]
Keep open please.

**Comment by Xavierr4** [comment]
Keep open please.

**Comment by Xavierr4** [comment]
@Filplus-govteam ok. I have finished the form.

**Comment by Sunnyiscoming** [comment]
The form has been completed.

**Comment by Casey-PG** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedr7c57tvpftvi7r3cjn3yxs5vhc43s4fqtwg6qpbg3rq75mqjcuk 
#### Address 
> f1oajib3g6npbw6jl4rqrhq5sr5i4kmxrdtjmjx6a
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1d4yb3wags3mtddzesxoo63jv7dmlec3bq4yteni
#### Id
> fa95f927-66f6-49df-ad4d-61f8b96baa6c
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedr7c57tvpftvi7r3cjn3yxs5vhc43s4fqtwg6qpbg3rq75mqjcuk

**Comment by Casey-PG** [comment]
After communicating with the applicant, I'm willing to support the round to observe the follow-up process.

**Comment by AthSmith** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedyeyvze5wzzenp6zmsh5t2dbrdg6gggt4i456dzakaaouccu7lcu 
#### Address 
> f1oajib3g6npbw6jl4rqrhq5sr5i4kmxrdtjmjx6a
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1vxbqrf7rfum3n6m5u6eb4re6xj7amvsaqnzu64y
#### Id
> fa95f927-66f6-49df-ad4d-61f8b96baa6c
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedyeyvze5wzzenp6zmsh5t2dbrdg6gggt4i456dzakaaouccu7lcu

**Comment by Xavierr4** [comment]
Yes
