### ISSUE TITLE
[DataCap Application]  <High energy accelerator research organization> - <J-PARC>

### ISSUE THREAD

**Issue by aslinkipfs** [filecoin-project/filecoin-plus-large-datasets#1505]
### Data Owner Name

High energy accelerator research organization

### Data Owner Country/Region

Japan

### Data Owner Industry

Other

### Website

https://www2.kek.jp/imss/msl/

### Social Media

```text
https://www2.kek.jp/imss/msl/
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

100TiB

### On-chain address for first allocation

f12rjkjli6axzysgvilyh5cmsmyzox3atgt7mufsa

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
April 1978
The Meson Science Experimental Facility was born as an auxiliary facility of the School of Science, University of Tokyo. It is allowed to establish experimental facilities in booster utilization facilities of high-energy physics laboratories and promote scientific research on the use of pulsed mesons and mesons.
July 1980
Generation using large superconducting solenoids μ The sub beam channel starts to operate. Successfully produced the first in the world μ The sub beam acts as a pulse beam.
November 1981
A comprehensive experiment based on experimental suggestions was started. Hold an international seminar on "Meson Basic Science Research" to deepen international exchanges.
April 1983
Yamada Conference "The Third International Conference on Meson Spin Rotation" was held in Xiatian City, Shizuoka County.
September 1986
The First International Conference on Meson Catalysts Nuclear Fusion (co sponsored with RIKEN) was held in Honxiang Campus of Tokyo University.
April 1988
The meson science experimental facility was reorganized into a meson science research center.
September 1988
With the support of specific research "meson science", we introduced and completed the μ Sub bundle channel.
April 1989
The two-year plan of special facility funds for "meson experiment device" was approved, and the construction of ultra slow meson experiment device was started.
July 1994
As a laser ionization method, it successfully produced the world's first super slow μ Subbundles.
September 1995
The "External Evaluation Committee" of the Meson Science Research Center was convened.
April 1996
The 7th Muon Spin Rotation, Relaxation and Resolution International Conference (co hosted with RIKEN) was held in Sunlight City, Yumu County.
April 1997
The Institute of High Energy Physics, the Institute of Atomic Energy of the University of Tokyo, and the Meson Science Research Center of the School of Science of the University of Tokyo were merged and reorganized to establish a research institute for high-energy accelerators. The joint use of university experiments began at the Institute of Materials and Structures Science and the Meson Science Research Facility.
November 2001
It was decided to jointly implement the high intensity proton accelerator project with the Japan Atomic Energy Research Institute. As part of the first phase plan, μ The construction budget of the meson science experiment facility was partially approved, and the construction of the facility began in Donghai Village.
April 2004
It was renamed as Muon Science Research Facility due to its reorganization as an inter university research institute company.
June 2004
The "External Evaluation Committee" of Muon Scientific Research Institute was held.
March 2006
The operation of the booster facility (Tsukuba campus) is completed.
April 2006
The overseas facility meson experiment promotion project (experiment for common use by universities) was launched.
July 2008
The 11th Muon Spin Rotation, Relaxation, and Resolution International Academic Conference（ μ SR2008) was held in Tsukuba (co sponsored by RIKEN Nishina Center and JAERI Advanced Science Research Center).
September 2008
The first meson beam was successfully extracted at J-PARC MUSE (Meson Science Experiment Facility).
December 2008
The joint use experiment with the university started at J-PARC MUSE (18 kW operation).
March 2009
The project of promoting meson experiment in overseas facilities was completed.
November 2009
Achieved the world's highest intensity pulse in J-PARC MUSE (120 kW operation) μ Subbundles.
November 2012
J-PARC MUSE achieves the world's highest 2500000 per pulse μ Sub strength (used to generate μ The proton beam intensity is 212 kW).
```

### Is this project associated with other projects/ecosystem stakeholders?

Yes

### Describe the data being stored onto Filecoin

```text
Interschool experiments are fully funded by the government, and in principle all payable results are eventually made available to the public. This principle also applies to experimental data.
j-parc collects and records the experimental experimental data collected and recorded in the Release Material Material Life Facility (Muse). But but for the sake of priority priority priority priority priority priority right will be limited to the person in charge of the experiment, and password protection is set for each experiment number. (Experimental data of one full year after acquisition will be made public automatically.)
```

### Where was the data currently stored in this dataset sourced from

Other

### How do you plan to prepare the dataset

IPFS, lotus

### Please share a sample of the data

```text
https://www2.kek.jp/imss/msl/user-info/DATA_download/KEK_data_zips/msr1_zip/1981.zip
https://www2.kek.jp/imss/msl/user-info/DATA_download/KEK_data_zips/msr3_zip/1981.zip
https://www2.kek.jp/imss/msl/user-info/DATA_download/KEK_data_zips/msr4_zip/1998.zip
https://www2.kek.jp/imss/msl/user-info/DATA_download/KEK_data_zips/msr5.zip
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Weekly

### For how long do you plan to keep this dataset stored on Filecoin

More than 3 years

### In which geographies do you plan on making storage deals

Asia other than Greater China

### How will you be distributing your data to storage providers

Cloud storage (i.e. S3), IPFS, Lotus built-in data transfer

### How do you plan to choose storage providers

Slack, Big data exchange, Partners

### How do you plan to make deals to your storage providers

Lotus client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
How much data do you have? How many copies will you store?
What's the relationship between you and the organization?
Whether the sps you choose can support data retrieval?

**Comment by simonkim0515** [comment]
## Datacap Request Trigger

#### Total DataCap requested 
> 5PiB

#### Expected weekly DataCap usage rate 
> 100TiB 

#### Client address
> f12rjkjli6axzysgvilyh5cmsmyzox3atgt7mufsa

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As notary i am screening your application and doing due diligence.

Looking at your application i have some questions:

As you are brand new on Github and have no history of past applications. Applying for 5PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing data and it's requirements and distribution of the data. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?

Can you provide me with some KYC details per e-mail at kyc@dcent.nl. I would like to receive an e-mail from the original domainname / contact as listed on the website that refers to this application. 
Your application is for 5PB of datacap. Can you show us some visible proof from the data size and the storage you have there?

Can you provide us with a distribution plan supposably that you would be granted datacap to store?

As you can see here : https://github.com/filecoin-project/filecoin-plus-large-datasets it states:

> In order for a client and their dataset to be eligible:
> the dataset should be public, open, and mission aligned with Filecoin and Filecoin Plus. This also means that the data should be accessible to anyone > in the network, without requiring any special permissions or access requirement
> stored data should be readily retrievable on the network and this should be regularly verified (though the use of manual or automated verification > that includes retrieving data from various miners over the course of the DataCap allocation timeframe)

To make sure that you understand the rules and guidelines I would like to receive a detailed allocation plan where the amount of data and reputational SP's where you are going to store this data are included.

**Comment by aslinkipfs** [comment]
> ## Datacap Request Trigger
> #### Total DataCap requested
> > 5PiB
> 
> #### Expected weekly DataCap usage rate
> > 100TiB
> 
> #### Client address
> > f12rjkjli6axzysgvilyh5cmsmyzox3atgt7mufsa



> How much data do you have? How many copies will you store? What's the relationship between you and the organization? Whether the sps you choose can support data retrieval?

We are have a professional team working on HPC Solution.
And we are also high level Channel Partner(VAP) of Hardware Vender Huawei and XFusion。
We developed Filecoin Hardware solution by useing software defined storage product(Oceanstor 9000 and Pacific 9540) from Huawei and Server from Huawei（Taishan200） and Xfusion（2288H V5/V6）since 2020.
We are the first local team who provide Filecoin Hardware solution and operation and maintenance service in Japan。
And support our customer the first node（over 7PiB）in Japan at the head of 2021。
We have already support our customer buliding 8nodes ，total physical capacity over 62PB
total effective capacity over 40PiB.

Because We have a professional team working on HPC solution, so We keep in touch with
KEK , the High Energy Accelerator Research Organization(https://www.kek.jp/en/about-en/what-en/) for a long time.
They have about 100PB storage(HDD+Tape) for storing and analysis data from high-energy particle beams and synchrotron light sources.
This research help us human to advance our understanding of the universe that surrounds us, its mechanisms and their control.And Makoto Kobayashi Professor Emeritus of KEK was awarded a 2008 Nobel Prize for Physics for the theory to explain the origin of the broken symmetry which predicts the existence of at least three families of quarks in nature.
Because KEK have too much data from super machine like SuperKEKB and ILC , and budget is limited，thats the reason they mix used HDD storage and Tape together，and dont backup data.
We plan to actual cost reduction by using Filecoin+ to store some of data not only for backup but also useing some free sealing machine resource (P1nodes multi-core + P2/P3 nodes High performance GPU) to do some new research just like use AI to analysis the old data agian，try to get some new discovery. And there are a lot of earthquake around KEK location，earthquake in 2011 was a hard lesson,and nobody want experience again.So we also plan to store data to Filecoin nodes located at Tokyo,Osaka,Okinawa to protect data from earthquake,because

Because the data is so important，We plan to run it in 2 stages.And we need Filecoin+ support us to achieve stage1 asap.

Stage 1
KEK will provide about 4PiB data which could be published，these data from high-energy particle beams and synchrotron light sources of CERN，and KEK keep a copy offsite.
The same data can be download from http://opendata.cern.ch/
sample : http://opendata.cern.ch/record/363

We will store theres data to Filecoin nodes and provide to some researchers from KEK and some Phds postgraduates from universities
data access and free sealing server multi-core and High performance GPU resource for research just like using AI to analysis old data again to get new discovers，training AI Algorithms for improving analysis efficiency about new data.

We plan 4-6 copys for the data, and owner of these node already agree to join this project.
And We will use different nodes to support access from different area of researchers or students of university.

Kanto Tohoku Hokkaido Area
f01623525 7.36PiB
f01357002 7.27PiB
f01126799 7.37PiB
f0155983 7.36PiB sealing again 2023 1H

f01184717 1.24PiB
f01662849 1.13PiB

f01715688 4.18PiB

Kyushu area
f01848169 4.51PiB

Osaka area
f01738789 709TiB

Stage 2
KEK will provide over 20PiB data ，these data from high-energy particle beams and synchrotron light sources(like SuperKEKB and ILC).
First of all store data as backup,then analysis the data by using the free multi-core and High performance GPU resource from sealing servers.
