### ISSUE TITLE
[DataCap Application] <NHPソリューション株式会社> - <Project Name>

### ISSUE THREAD

**Issue by lbj2004032** [filecoin-project/filecoin-plus-large-datasets#1506]
### Data Owner Name

NHPソリューション株式会社

### Data Owner Country/Region

Afghanistan

### Data Owner Industry

Other

### Website

https://nhp-gp.com/

### Social Media

```text
Obtain equipment use rights from sponsoring companies and research institutes, and conduct secondary analysis and exploration of past accelerator data based on data mining and AI technology
```

### Total amount of DataCap being requested

4PiB

### Weekly allocation of DataCap requested

50TiB

### On-chain address for first allocation

f1x3ylumun2gnvkbhcxcyi2qtqj4vm5uqy5vt4yqi

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
We are have a professional team working on HPC Solution.
And we are also high level Channel Partner(VAP) of Hardware Vender Huawei and XFusion。
We developed Filecoin Hardware solution by useing software defined storage product(Oceanstor 9000 and Pacific 9540) from Huawei and Server from Huawei（Taishan200） and Xfusion（2288H V5/V6）since 2020.
We are the first local team who provide Filecoin Hardware solution and operation and maintenance service in Japan。
And support our customer the first node（over 7PiB）in Japan at the head of 2021。
We have already support our customer buliding 8nodes ，total physical capacity over 62PB
total effective capacity over 40PiB.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
Data generated by the Institute's research
Gene collision related data
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### How do you plan to prepare the dataset

lotus

### Please share a sample of the data

```text
http://124.219.161.88:22180/#s/8mvyG_uQ

http://124.219.161.88:22180/#s/8mvyG_uQ

http://124.219.161.88:22180/#s/8mvyG_uQ
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Weekly

### For how long do you plan to keep this dataset stored on Filecoin

More than 3 years

### In which geographies do you plan on making storage deals

Asia other than Greater China

### How will you be distributing your data to storage providers

IPFS, Lotus built-in data transfer

### How do you plan to choose storage providers

Partners

### How do you plan to make deals to your storage providers

Lotus client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As notary i am screening your application and doing due diligence.

Looking at your application i have some questions:

As you are brand new on Github and have no history of past applications. Applying for 4PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing data and it's requirements and distribution of the data. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?

Can you provide me with some KYC details per e-mail at kyc@dcent.nl. I would like to receive an e-mail from the original domain name / contact as listed on the website that refers to this application. 
Your application is for 4PB of datacap. Can you show us some visible proof from the data size and the storage you have there?

Can you provide us with a distribution plan supposably that you would be granted datacap to store?

As you can see here : https://github.com/filecoin-project/filecoin-plus-large-datasets it states:

> In order for a client and their dataset to be eligible:
> the dataset should be public, open, and mission aligned with Filecoin and Filecoin Plus. This also means that the data should be accessible to anyone > in the network, without requiring any special permissions or access requirement
> stored data should be readily retrievable on the network and this should be regularly verified (though the use of manual or automated verification > that includes retrieving data from various miners over the course of the DataCap allocation timeframe)

To make sure that you understand the rules and guidelines I would like to receive a detailed allocation plan where the amount of data and reputational SP's where you are going to store this data are included. 

As last question i would like to know the relationship between Genome collision data and your company. The data you are going to store must be in line with the mission of FIL+ ( Store humanity's most valuable data 0 ). You mentioned a general phrase with "storing the data of the institute" but i would like you to be more specific here.

**Comment by lbj2004032** [comment]
We are have a professional team working on HPC Solution.
And we are also high level Channel Partner(VAP) of Hardware Vender Huawei and XFusion。
We developed Filecoin Hardware solution by useing software defined storage product(Oceanstor 9000 and Pacific 9540) from Huawei and Server from Huawei（Taishan200） and Xfusion（2288H V5/V6）since 2020.
We are the first local team who provide Filecoin Hardware solution and operation and maintenance service in Japan。
And support our customer the first node（over 7PiB）in Japan at the head of 2021。
We have already support our customer buliding 8nodes ，total physical capacity over 62PB
total effective capacity over 40PiB.

Because We have a professional team working on HPC solution, so We keep in touch with
KEK , the High Energy Accelerator Research Organization(https://www.kek.jp/en/about-en/what-en/) for a long time.
They have about 100PB storage(HDD+Tape) for storing and analysis data from high-energy particle beams and synchrotron light sources.
This research help us human to advance our understanding of the universe that surrounds us, its mechanisms and their control.And Makoto Kobayashi Professor Emeritus of KEK was awarded a 2008 Nobel Prize for Physics for the theory to explain the origin of the broken symmetry which predicts the existence of at least three families of quarks in nature.
Because KEK have too much data from super machine like SuperKEKB and ILC , and budget is limited，thats the reason they mix used HDD storage and Tape together，and dont backup data.
We plan to actual cost reduction by using Filecoin+ to store some of data not only for backup but also useing some free sealing machine resource (P1nodes multi-core + P2/P3 nodes High performance GPU) to do some new research just like use AI to analysis the old data agian，try to get some new discovery. And there are a lot of earthquake around KEK location，earthquake in 2011 was a hard lesson,and nobody want experience again.So we also plan to store data to Filecoin nodes located at Tokyo,Osaka,Okinawa to protect data from earthquake,because

Because the data is so important，We plan to run it in 2 stages.And we need Filecoin+ support us to achieve stage1 asap.

Stage 1
KEK will provide about 4PiB data which could be published，these data from high-energy particle beams and synchrotron light sources of CERN，and KEK keep a copy offsite.
The same data can be download from http://opendata.cern.ch/
sample : http://opendata.cern.ch/record/363

We will store theres data to Filecoin nodes and provide to some researchers from KEK and some Phds postgraduates from universities
data access and free sealing server multi-core and High performance GPU resource for research just like using AI to analysis old data again to get new discovers，training AI Algorithms for improving analysis efficiency about new data.

We plan 4-6 copys for the data, and owner of these node already agree to join this project.
And We will use different nodes to support access from different area of researchers or students of university.

Kanto Tohoku Hokkaido Area
f01623525 7.36PiB
f01357002 7.27PiB
f01126799 7.37PiB
f0155983 7.36PiB sealing again 2023 1H

f01184717 1.24PiB
f01662849 1.13PiB

f01715688 4.18PiB

Kyushu area
f01848169 4.51PiB

Osaka area
f01738789 709TiB

Stage 2
KEK will provide over 20PiB data ，these data from high-energy particle beams and synchrotron light sources(like SuperKEKB and ILC).
First of all store data as backup,then analysis the data by using the free multi-core and High performance GPU resource from sealing servers.

**Comment by lbj2004032** [comment]
> We are have a professional team working on HPC Solution. And we are also high level Channel Partner(VAP) of Hardware Vender Huawei and XFusion。 We developed Filecoin Hardware solution by useing software defined storage product(Oceanstor 9000 and Pacific 9540) from Huawei and Server from Huawei（Taishan200） and Xfusion（2288H V5/V6）since 2020. We are the first local team who provide Filecoin Hardware solution and operation and maintenance service in Japan。 And support our customer the first node（over 7PiB）in Japan at the head of 2021。 We have already support our customer buliding 8nodes ，total physical capacity over 62PB total effective capacity over 40PiB.
> 
> Because We have a professional team working on HPC solution, so We keep in touch with KEK , the High Energy Accelerator Research Organization(https://www.kek.jp/en/about-en/what-en/) for a long time. They have about 100PB storage(HDD+Tape) for storing and analysis data from high-energy particle beams and synchrotron light sources. This research help us human to advance our understanding of the universe that surrounds us, its mechanisms and their control.And Makoto Kobayashi Professor Emeritus of KEK was awarded a 2008 Nobel Prize for Physics for the theory to explain the origin of the broken symmetry which predicts the existence of at least three families of quarks in nature. Because KEK have too much data from super machine like SuperKEKB and ILC , and budget is limited，thats the reason they mix used HDD storage and Tape together，and dont backup data. We plan to actual cost reduction by using Filecoin+ to store some of data not only for backup but also useing some free sealing machine resource (P1nodes multi-core + P2/P3 nodes High performance GPU) to do some new research just like use AI to analysis the old data agian，try to get some new discovery. And there are a lot of earthquake around KEK location，earthquake in 2011 was a hard lesson,and nobody want experience again.So we also plan to store data to Filecoin nodes located at Tokyo,Osaka,Okinawa to protect data from earthquake,because
> 
> Because the data is so important，We plan to run it in 2 stages.And we need Filecoin+ support us to achieve stage1 asap.
> 
> Stage 1 KEK will provide about 4PiB data which could be published，these data from high-energy particle beams and synchrotron light sources of CERN，and KEK keep a copy offsite. The same data can be download from http://opendata.cern.ch/ sample : http://opendata.cern.ch/record/363
> 
> We will store theres data to Filecoin nodes and provide to some researchers from KEK and some Phds postgraduates from universities data access and free sealing server multi-core and High performance GPU resource for research just like using AI to analysis old data again to get new discovers，training AI Algorithms for improving analysis efficiency about new data.
> 
> We plan 4-6 copys for the data, and owner of these node already agree to join this project. And We will use different nodes to support access from different area of researchers or students of university.
> 
> Kanto Tohoku Hokkaido Area f01623525 7.36PiB f01357002 7.27PiB f01126799 7.37PiB f0155983 7.36PiB sealing again 2023 1H
> 
> f01184717 1.24PiB f01662849 1.13PiB
> 
> f01715688 4.18PiB
> 
> Kyushu area f01848169 4.51PiB
> 
> Osaka area f01738789 709TiB
> 
> Stage 2 KEK will provide over 20PiB data ，these data from high-energy particle beams and synchrotron light sources(like SuperKEKB and ILC). First of all store data as backup,then analysis the data by using the free multi-core and High performance GPU resource from sealing servers.

We are have a professional team working on HPC Solution.
And we are also high level Channel Partner(VAP) of Hardware Vender Huawei and XFusion。
We developed Filecoin Hardware solution by useing software defined storage product(Oceanstor 9000 and Pacific 9540) from Huawei and Server from Huawei（Taishan200） and Xfusion（2288H V5/V6）since 2020.
We are the first local team who provide Filecoin Hardware solution and operation and maintenance service in Japan。
And support our customer the first node（over 7PiB）in Japan at the head of 2021。
We have already support our customer buliding 8nodes ，total physical capacity over 62PB
total effective capacity over 40PiB.

Because We have a professional team working on HPC solution, so We keep in touch with
KEK , the High Energy Accelerator Research Organization(https://www.kek.jp/en/about-en/what-en/) for a long time.
They have about 100PB storage(HDD+Tape) for storing and analysis data from high-energy particle beams and synchrotron light sources.
This research help us human to advance our understanding of the universe that surrounds us, its mechanisms and their control.And Makoto Kobayashi Professor Emeritus of KEK was awarded a 2008 Nobel Prize for Physics for the theory to explain the origin of the broken symmetry which predicts the existence of at least three families of quarks in nature.
Because KEK have too much data from super machine like SuperKEKB and ILC , and budget is limited，thats the reason they mix used HDD storage and Tape together，and dont backup data.
We plan to actual cost reduction by using Filecoin+ to store some of data not only for backup but also useing some free sealing machine resource (P1nodes multi-core + P2/P3 nodes High performance GPU) to do some new research just like use AI to analysis the old data agian，try to get some new discovery. And there are a lot of earthquake around KEK location，earthquake in 2011 was a hard lesson,and nobody want experience again.So we also plan to store data to Filecoin nodes located at Tokyo,Osaka,Okinawa to protect data from earthquake,because

Because the data is so important，We plan to run it in 2 stages.And we need Filecoin+ support us to achieve stage1 asap.

Stage 1
KEK will provide about 4PiB data which could be published，these data from high-energy particle beams and synchrotron light sources of CERN，and KEK keep a copy offsite.
The same data can be download from http://opendata.cern.ch/
sample : http://opendata.cern.ch/record/363

We will store theres data to Filecoin nodes and provide to some researchers from KEK and some Phds postgraduates from universities
data access and free sealing server multi-core and High performance GPU resource for research just like using AI to analysis old data again to get new discovers，training AI Algorithms for improving analysis efficiency about new data.

We plan 4-6 copys for the data, and owner of these node already agree to join this project.
And We will use different nodes to support access from different area of researchers or students of university.

Kanto Tohoku Hokkaido Area
f01623525 7.36PiB
f01357002 7.27PiB
f01126799 7.37PiB
f0155983 7.36PiB sealing again 2023 1H

f01184717 1.24PiB
f01662849 1.13PiB

f01715688 4.18PiB

Kyushu area
f01848169 4.51PiB

Osaka area
f01738789 709TiB

Stage 2
KEK will provide over 20PiB data ，these data from high-energy particle beams and synchrotron light sources(like SuperKEKB and ILC).
First of all store data as backup,then analysis the data by using the free multi-core and High performance GPU resource from sealing servers.

**Comment by lbj2004032** [comment]
> Dear applicant,
> 
> Thank you for applying for datacap. As notary i am screening your application and doing due diligence.
> 
> Looking at your application i have some questions:
> 
> As you are brand new on Github and have no history of past applications. Applying for 4PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing data and it's requirements and distribution of the data. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?
> 
> Can you provide me with some KYC details per e-mail at [kyc@dcent.nl](mailto:kyc@dcent.nl). I would like to receive an e-mail from the original domain name / contact as listed on the website that refers to this application. Your application is for 4PB of datacap. Can you show us some visible proof from the data size and the storage you have there?
> 
> Can you provide us with a distribution plan supposably that you would be granted datacap to store?
> 
> As you can see here : https://github.com/filecoin-project/filecoin-plus-large-datasets it states:
> 
> > In order for a client and their dataset to be eligible:
> > the dataset should be public, open, and mission aligned with Filecoin and Filecoin Plus. This also means that the data should be accessible to anyone > in the network, without requiring any special permissions or access requirement
> > stored data should be readily retrievable on the network and this should be regularly verified (though the use of manual or automated verification > that includes retrieving data from various miners over the course of the DataCap allocation timeframe)
> 
> To make sure that you understand the rules and guidelines I would like to receive a detailed allocation plan where the amount of data and reputational SP's where you are going to store this data are included.
> 
> As last question i would like to know the relationship between Genome collision data and your company. The data you are going to store must be in line with the mission of FIL+ ( Store humanity's most valuable data 0 ). You mentioned a general phrase with "storing the data of the institute" but i would like you to be more specific here.

We are have a professional team working on HPC Solution.
And we are also high level Channel Partner(VAP) of Hardware Vender Huawei and XFusion。
We developed Filecoin Hardware solution by useing software defined storage product(Oceanstor 9000 and Pacific 9540) from Huawei and Server from Huawei（Taishan200） and Xfusion（2288H V5/V6）since 2020.
We are the first local team who provide Filecoin Hardware solution and operation and maintenance service in Japan。
And support our customer the first node（over 7PiB）in Japan at the head of 2021。
We have already support our customer buliding 8nodes ，total physical capacity over 62PB
total effective capacity over 40PiB.

Because We have a professional team working on HPC solution, so We keep in touch with
KEK , the High Energy Accelerator Research Organization(https://www.kek.jp/en/about-en/what-en/) for a long time.
They have about 100PB storage(HDD+Tape) for storing and analysis data from high-energy particle beams and synchrotron light sources.
This research help us human to advance our understanding of the universe that surrounds us, its mechanisms and their control.And Makoto Kobayashi Professor Emeritus of KEK was awarded a 2008 Nobel Prize for Physics for the theory to explain the origin of the broken symmetry which predicts the existence of at least three families of quarks in nature.
Because KEK have too much data from super machine like SuperKEKB and ILC , and budget is limited，thats the reason they mix used HDD storage and Tape together，and dont backup data.
We plan to actual cost reduction by using Filecoin+ to store some of data not only for backup but also useing some free sealing machine resource (P1nodes multi-core + P2/P3 nodes High performance GPU) to do some new research just like use AI to analysis the old data agian，try to get some new discovery. And there are a lot of earthquake around KEK location，earthquake in 2011 was a hard lesson,and nobody want experience again.So we also plan to store data to Filecoin nodes located at Tokyo,Osaka,Okinawa to protect data from earthquake,because

Because the data is so important，We plan to run it in 2 stages.And we need Filecoin+ support us to achieve stage1 asap.

Stage 1
KEK will provide about 4PiB data which could be published，these data from high-energy particle beams and synchrotron light sources of CERN，and KEK keep a copy offsite.
The same data can be download from http://opendata.cern.ch/
sample : http://opendata.cern.ch/record/363

We will store theres data to Filecoin nodes and provide to some researchers from KEK and some Phds postgraduates from universities
data access and free sealing server multi-core and High performance GPU resource for research just like using AI to analysis old data again to get new discovers，training AI Algorithms for improving analysis efficiency about new data.

We plan 4-6 copys for the data, and owner of these node already agree to join this project.
And We will use different nodes to support access from different area of researchers or students of university.

Kanto Tohoku Hokkaido Area
f01623525 7.36PiB
f01357002 7.27PiB
f01126799 7.37PiB
f0155983 7.36PiB sealing again 2023 1H

f01184717 1.24PiB
f01662849 1.13PiB

f01715688 4.18PiB

Kyushu area
f01848169 4.51PiB

Osaka area
f01738789 709TiB

Stage 2
KEK will provide over 20PiB data ，these data from high-energy particle beams and synchrotron light sources(like SuperKEKB and ILC).
First of all store data as backup,then analysis the data by using the free multi-core and High performance GPU resource from sealing servers.
