### ISSUE TITLE
[DataCap Application] <NOAA Climate Forecast System>

### ISSUE THREAD

**Issue by algo-cpu** [filecoin-project/filecoin-plus-large-datasets#1509]
### Data Owner Name

National Oceanic and Atmospheric Administration

### Data Owner Country/Region

United States

### Data Owner Industry

Utilities

### Website

https://cfs.ncep.noaa.gov/

### Social Media

```text
https://twitter.com/NOAANCEI
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

200TiB

### On-chain address for first allocation

f1rrdumkod5xqzup2znqxc2htvtiv3rqv47ctzywa

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
The Climate Forecast System (CFS) is a model representing the global interaction between Earth's oceans, land, and atmosphere. Produced by several dozen scientists under guidance from the National Centers for Environmental Prediction (NCEP), this model offers hourly data with a horizontal resolution down to one-half of a degree (approximately 56 km) around Earth for many variables. CFS uses the latest scientific approaches for taking in, or assimilating, observations from data sources including surface observations, upper air balloon observations, aircraft observations, and satellite observations.
Our goal is to make the data that is beneficial to the long history of human beings durable.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
The CFS was developed at the Environmental Modeling Center at NCEP. It is a fully coupled model representing the interaction between the Earth's atmosphere, oceans, land and seaice.
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### How do you plan to prepare the dataset

lotus, singularity

### Please share a sample of the data

```text
https://noaa-cfs-pds.s3.us-east-1.amazonaws.com/cfs.20190128/00/6hrly_grib_01/flxf2019062006.01.2019012800.grb2
https://noaa-cfs-pds.s3.us-east-1.amazonaws.com/cfs.20220723/06/6hrly_grib_01/ipvf2022111418.01.2022072306.grb2
https://noaa-cfs-pds.s3.us-east-1.amazonaws.com/cfs.20220723/06/6hrly_grib_01/sigf2022072306.01.2022072306
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

More than 3 years

### In which geographies do you plan on making storage deals

Asia other than Greater China, North America, South America, Europe

### How will you be distributing your data to storage providers

HTTP or FTP server, IPFS

### How do you plan to choose storage providers

Slack, Big data exchange

### How do you plan to make deals to your storage providers

Boost client, Singularity

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
Please verify that this is a public data set that can be stored on the filecoin network.
Could you introduce yourself?

**Comment by algo-cpu** [comment]
> Please verify that this is a public data set that can be stored on the filecoin network.
> Could you introduce yourself?
https://aws.amazon.com/marketplace/pp/prodview-oa2b3wsl2l5gy?qid=1672749280939&sr=0-1&ref_=srh_res_product_title
![57D61B41-F6CA-4C6A-9463-3F036158CC27](https://user-images.githubusercontent.com/76160255/210358549-5ec88873-01ae-477f-923f-50a90e57f0b8.jpeg)

I am an individual worker. I have participated in the testing of the network since the test network. I have been involved until now. I have a deep understanding of filecoin.after that, nv18/fvm/saturn will continue to participate in the test.
If you have any questions, please continue to contact me. Thank you.

**Comment by simonkim0515** [comment]
## Datacap Request Trigger

#### Total DataCap requested 
> 5PiB

#### Expected weekly DataCap usage rate 
> 200TiB 

#### Client address
> f1rrdumkod5xqzup2znqxc2htvtiv3rqv47ctzywa

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

I would like you to fill out [this form](https://form.jotform.com/230232885049356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!

**Comment by algo-cpu** [comment]
> Dear applicant,
> 
> Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.
> 
> I would like you to fill out [this form](https://form.jotform.com/230232885049356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.
> 
> Thanks!

Hello notary
Thanks for your review, after receiving your reply, I saw that this form needs to be filled out with SP, I am now looking for definitive SP, I will perfect this form when I find it, thank you.
