### ISSUE TITLE
[DataCap Application]LeoCheung - Slingshot Restore Program

### ISSUE THREAD

**Issue by LeoZCH** [filecoin-project/filecoin-plus-large-datasets#151]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: LeoCheung - Slingshot Restore
- Website / Social Media: https://github.com/LeoZCH
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 500TiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 200TiB
- On-chain address for first allocation: f3v7x4a2aapgx6o2r477tenoin3u5oadaeqyd7kjdsitykvf4ok7vq2utcyh34lmu5u7oybs25ff6s4dbudpma

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
this DataCap is for **Slingshot Restore Program**, it is hosted by the Slingshot teams. you can see the detail as follows:

https://docs.google.com/document/d/1ZH4URWaNYtlddZwZMyqcSnc3GRsR3zCqnW0RfkkNlr8/edit# 
https://docs.google.com/document/d/1sGLkw321Fl09jvAr80kFY2FcQWa1H-dYpowXFRWo-OM/edit 

https://docs.google.com/spreadsheets/d/1UYmVtwtJUIAwlogZmLSZB_nZxWrVlID6ryfqrB0jBjw/edit#gid=1779251844 
https://docs.google.com/spreadsheets/d/1Skga2Yn0BD7CDgT1WQmKtPJ3nxhQ4QWd45e78Y42Wjc/edit#gid=0 
```

What is the primary source of funding for this project?
```
PL & Slingshot teams, and my teams support this project.
```

What other projects/ecosystem stakeholders is this project associated with?
```
No
```

## Use-case details

Describe the data being stored onto Filecoin
```
I have submitted the application as a client, and I has been assigned the dataset "
common-crawl - april 2021(https://commoncrawl.org/2021/04/april-2021-crawl-archive-now-available/)"

Dataset Description：
The data was crawled April 10 – 23 and contains 3.1 billion web pages or 320 TiB of uncompressed content. It includes page captures of 1.35 billion new URLs, not visited in any of our prior crawls.
```

Where was the data in this dataset sourced from?
```
These dataset is public, I can download them directly.
```
<img width="786" alt="image" src="https://user-images.githubusercontent.com/72675907/146637764-b6f44d73-df37-4843-8aa2-750efb9417fb.png">

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
Yes, I can supply some url of dataset:

https://commoncrawl.s3.amazonaws.com/cc-index/collections/CC-MAIN-2021-17/indexes/cdx-00000.gz
https://commoncrawl.s3.amazonaws.com/cc-index/collections/CC-MAIN-2021-17/indexes/cdx-00001.gz
https://commoncrawl.s3.amazonaws.com/cc-index/collections/CC-MAIN-2021-17/indexes/cdx-00002.gz
https://commoncrawl.s3.amazonaws.com/cc-index/collections/CC-MAIN-2021-17/indexes/cdx-00003.gz
https://commoncrawl.s3.amazonaws.com/cc-index/collections/CC-MAIN-2021-17/indexes/cdx-00004.gz
https://commoncrawl.s3.amazonaws.com/cc-index/collections/CC-MAIN-2021-17/indexes/cdx-00005.gz
https://commoncrawl.s3.amazonaws.com/cc-index/collections/CC-MAIN-2021-17/indexes/cdx-00006.gz
https://commoncrawl.s3.amazonaws.com/cc-index/collections/CC-MAIN-2021-17/indexes/cdx-00007.gz
https://commoncrawl.s3.amazonaws.com/cc-index/collections/CC-MAIN-2021-17/indexes/cdx-00008.gz
https://commoncrawl.s3.amazonaws.com/cc-index/collections/CC-MAIN-2021-17/indexes/cdx-00009.gz
https://commoncrawl.s3.amazonaws.com/cc-index/collections/CC-MAIN-2021-17/indexes/cdx-00010.gz
https://commoncrawl.s3.amazonaws.com/cc-index/collections/CC-MAIN-2021-17/indexes/cdx-00011.gz
https://commoncrawl.s3.amazonaws.com/cc-index/collections/CC-MAIN-2021-17/indexes/cdx-00012.gz
https://commoncrawl.s3.amazonaws.com/cc-index/collections/CC-MAIN-2021-17/indexes/cdx-00013.gz
https://commoncrawl.s3.amazonaws.com/cc-index/collections/CC-MAIN-2021-17/indexes/cdx-00014.gz
https://commoncrawl.s3.amazonaws.com/cc-index/collections/CC-MAIN-2021-17/indexes/cdx-00015.gz
https://commoncrawl.s3.amazonaws.com/cc-index/collections/CC-MAIN-2021-17/indexes/cdx-00016.gz
https://commoncrawl.s3.amazonaws.com/cc-index/collections/CC-MAIN-2021-17/indexes/cdx-00017.gz
https://commoncrawl.s3.amazonaws.com/cc-index/collections/CC-MAIN-2021-17/indexes/cdx-00018.gz
https://commoncrawl.s3.amazonaws.com/cc-index/collections/CC-MAIN-2021-17/indexes/cdx-00019.gz
https://commoncrawl.s3.amazonaws.com/cc-index/collections/CC-MAIN-2021-17/indexes/cdx-00020.gz
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes, I have confirmed it.
```

What is the expected retrieval frequency for this data?
```
Anytime.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
More than 500 days
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
HongKong, China
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
I will store every file to at least 3 storage providers, the offline data process will be supported.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
The three storage providers will locate different regions, and their power must more than 3PiB. And providers must agree that they should store unsealed files and keep these data retrieved all the time.
```

How will you be distributing deals across storage providers?
```
I have two rules for distributing deals. First, every storage provider will get one data-deal at least.  Second, the more power  storage provider has, the more deals will be assigned. 
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, I have contact two providers, who are. willing to accept my verified deals as a low price. And the data download process has started. After the data is processed, we can start send deals to them.    
```

**Comment by galen-mcandrew** [comment]
## Multisig Notary requested
#### Total DataCap requested 
> 500TiB
#### Expected weekly DataCap usage rate 
> 200TiB

**Comment by neogeweb3** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceblsg5xdxntxw52dpzo3jk2zvmvfs4fccozmshu4qy5mnpys33ojq 
#### Address 
> f3v7x4a2aapgx6o2r477tenoin3u5oadaeqyd7kjdsitykvf4ok7vq2utcyh34lmu5u7oybs25ff6s4dbudpma
#### Datacap Allocated
> 25TiB
#### Signer Address
> f13k5zr6ovc2gjmg3lvd43ladbydhovpylcvbflpa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceblsg5xdxntxw52dpzo3jk2zvmvfs4fccozmshu4qy5mnpys33ojq

**Comment by IreneYoung** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebywusu7te5gqgcq367apd4i4shfw7jrspg3amrcbayqj6m4k34jg 
#### Address 
> f3v7x4a2aapgx6o2r477tenoin3u5oadaeqyd7kjdsitykvf4ok7vq2utcyh34lmu5u7oybs25ff6s4dbudpma
#### Datacap Allocated
> 25TiB
#### Signer Address
> f1d4gmpqz3execjj2wvrxuuhvbms5mzh7t7yqrviq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebywusu7te5gqgcq367apd4i4shfw7jrspg3amrcbayqj6m4k34jg

**Comment by mr-spaghetti-code** [comment]
Hi,

It looks like you received 55TiBs of DataCap to date but have spent less than 20% of it so far.

We would love to understand if there's anything holding you back. We are working hard to make the data onboarding process easier for clients like you and your feedback is very valuable. If you have a moment, please fill in this survey: https://forms.gle/s6AuTXZPZSMokscLA

If you have any feedback or would like to consult with an expert, please let me know. 

Thanks,

João Fiadeiro
Product Manager, Large Data Client Onboarding
Protocol Labs

**Comment by Joss-Hua** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceclk743rxjnt7qurj7kfl264c4ubitu5kwsg26ozp6fkr7zoyoezm 
#### Address 
> f3v7x4a2aapgx6o2r477tenoin3u5oadaeqyd7kjdsitykvf4ok7vq2utcyh34lmu5u7oybs25ff6s4dbudpma
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1tfg54zzscugttejv336vivknmsnzzmyudp3t7wi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceclk743rxjnt7qurj7kfl264c4ubitu5kwsg26ozp6fkr7zoyoezm

**Comment by MetaWaveInfo** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceapetwmnwzafa5tltsiyucwviy6ctql6m3hgs5bx5wdbvakzeup3o 
#### Address 
> f3v7x4a2aapgx6o2r477tenoin3u5oadaeqyd7kjdsitykvf4ok7vq2utcyh34lmu5u7oybs25ff6s4dbudpma
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1ktlkcxnmzxcdaoqfsunrg3vocfbmgv4n3mrn74a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceapetwmnwzafa5tltsiyucwviy6ctql6m3hgs5bx5wdbvakzeup3o

**Comment by BigD-Exchange** [comment]
@LeoZCH Hi! Great to see you have gotten approval for DataCap. If you are looking for more storage providers to store these data or have any questions, please visit #bigdata-exchange on Filecoin Slack or reply here. 

We have strong demand from a diverse group of SPs, who are actively looking to onboard more data.

**Comment by LeoZCH** [comment]
Dear every notary, @Joss-Hua @MetaWaveInfo @mr-spaghetti-code 
I am so sorry to say  I lost my private key because of myself, so please do not grant more DataCap to that address, Can I change the address to `f1cbomoyigc2a2b2wbwmlfbfptqg5vin35gpyhvxq`

**Comment by LeoZCH** [comment]
> @LeoZCH Hi! Great to see you have gotten approval for DataCap. If you are looking for more storage providers to store these data or have any questions, please visit #bigdata-exchange on Filecoin Slack or reply here.
> 
> We have strong demand from a diverse group of SPs, who are actively looking to onboard more data.

thanks @BigD-Exchange , but I lost my private key, I need notaries help me solve this issue

**Comment by jamerduhgamer** [comment]
Hi @LeoZCH, I don't think the notaries will be able to help you with this. This may have to be taken up with @galen-mcandrew.

**Comment by psh0691** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb4ehk3hz4b5fmumf7m5w3rteedefzhek2r2qgacfukotjrku4awk 
#### Address 
> f3v7x4a2aapgx6o2r477tenoin3u5oadaeqyd7kjdsitykvf4ok7vq2utcyh34lmu5u7oybs25ff6s4dbudpma
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1qdko4jg25vo35qmyvcrw4ak4fmuu3f5rif2kc7i
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb4ehk3hz4b5fmumf7m5w3rteedefzhek2r2qgacfukotjrku4awk

**Comment by LeoZCH** [comment]
@psh0691 thanks for your propose dc request, I get the address again.

@neogeweb3 @MetaWaveInfo @Joss-Hua can you help me sign the request again?

**Comment by liyunzhi-666** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedzgdxzdrvpnw5czz6xjji7xmpditzmhmvvue3y2et4wxsf3y4vhg 
#### Address 
> f3v7x4a2aapgx6o2r477tenoin3u5oadaeqyd7kjdsitykvf4ok7vq2utcyh34lmu5u7oybs25ff6s4dbudpma
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1pszcrsciyixyuxxukkvtazcokexbn54amf7gvoq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedzgdxzdrvpnw5czz6xjji7xmpditzmhmvvue3y2et4wxsf3y4vhg

**Comment by filplus-checker** [comment]
## DataCap and CID Checker Report[^1]
 - Organization: `LeoCheung - Slingshot Restore`
 - Client: `f3v7x4a2aapgx6o2r477tenoin3u5oadaeqyd7kjdsitykvf4ok7vq2utcyh34lmu5u7oybs25ff6s4dbudpma`
### Storage Provider Distribution
The below table shows the distribution of storage providers that have stored data for this client.

If this is the first time a provider takes verified deal, it will be marked as `new`.

For most of the datacap application, below restrictions should apply.
 - Storage provider should not exceed 25% of total datacap.
 - Storage provider should not be storing duplicate data for more than 20%.
 - Storage provider should have published its public IP address.
 - All storage providers should be located in different regions.

⚠️ [f01878201](https://filfox.info/en/address/f01878201) has sealed 29.49% of total datacap.

⚠️ 70.96% of total deal sealed by [f01878201](https://filfox.info/en/address/f01878201) are duplicate data.

⚠️ 80.02% of total deal sealed by [f03624](https://filfox.info/en/address/f03624) are duplicate data.

⚠️ [f01919426](https://filfox.info/en/address/f01919426) has unknown IP location.

⚠️ 32.57% of total deal sealed by [f066596](https://filfox.info/en/address/f066596) are duplicate data.

⚠️ 27.51% of total deal sealed by [f0165400](https://filfox.info/en/address/f0165400) are duplicate data.

⚠️ 46.90% of total deal sealed by [f01652333](https://filfox.info/en/address/f01652333) are duplicate data.

⚠️ 22.75% of total deal sealed by [f0694396](https://filfox.info/en/address/f0694396) are duplicate data.

⚠️ 42.95% of total deal sealed by [f01157271](https://filfox.info/en/address/f01157271) are duplicate data.

⚠️ 25.00% of total deal sealed by [f0157535](https://filfox.info/en/address/f0157535) are duplicate data.

⚠️ 33.33% of total deal sealed by [f01947280](https://filfox.info/en/address/f01947280) are duplicate data.

⚠️ [f01981571](https://filfox.info/en/address/f01981571) has unknown IP location.

⚠️ 34.31% of total deal sealed by [f01131460](https://filfox.info/en/address/f01131460) are duplicate data.

⚠️ [f01131460](https://filfox.info/en/address/f01131460) has unknown IP location.

⚠️ [f01922624](https://filfox.info/en/address/f01922624) has unknown IP location.

⚠️ 50.00% of total deal sealed by [f01419959](https://filfox.info/en/address/f01419959) are duplicate data.

⚠️ 50.00% of total deal sealed by [f0240456](https://filfox.info/en/address/f0240456) are duplicate data.

| Provider                                                    |                           Location | Total Deals Sealed | Percentage | Unique Data | Duplicate Deals |
| :---------------------------------------------------------- | ---------------------------------: | -----------------: | ---------: | ----------: | --------------: |
| [f01878201](https://filfox.info/en/address/f01878201)       |             Hangzhou, Zhejiang, CN |          45.63 TiB |     29.49% |   13.25 TiB |          70.96% |
| [f01940076](https://filfox.info/en/address/f01940076)`new`  | Hong Kong, Central and Western, HK |          29.50 TiB |     19.07% |   29.50 TiB |           0.00% |
| [f03624](https://filfox.info/en/address/f03624)             |              Nürnberg, Bavaria, DE |          25.03 TiB |     16.18% |    5.00 TiB |          80.02% |
| [f01901773](https://filfox.info/en/address/f01901773)       | Hong Kong, Central and Western, HK |          22.97 TiB |     14.85% |   22.97 TiB |           0.00% |
| [f01890287](https://filfox.info/en/address/f01890287)       |             Shanghai, Shanghai, CN |          15.34 TiB |      9.92% |   15.34 TiB |           0.00% |
| [f01919426](https://filfox.info/en/address/f01919426)       |                            Unknown |           6.72 TiB |      4.34% |    6.72 TiB |           0.00% |
| [f066596](https://filfox.info/en/address/f066596)           |          San Diego, California, US |           1.61 TiB |      1.04% |    1.08 TiB |          32.57% |
| [f0165400](https://filfox.info/en/address/f0165400)         |               Montréal, Quebec, CA |           1.55 TiB |      1.01% |    1.13 TiB |          27.51% |
| [f01652333](https://filfox.info/en/address/f01652333)       |          Sunnyvale, California, US |         969.00 GiB |      0.61% |  514.50 GiB |          46.90% |
| [f01091840](https://filfox.info/en/address/f01091840)       |               Montréal, Quebec, CA |         915.00 GiB |      0.58% |  867.00 GiB |           5.25% |
| [f0447183](https://filfox.info/en/address/f0447183)         |          Indianapolis, Indiana, US |         648.00 GiB |      0.41% |  528.00 GiB |          18.52% |
| [f01558688](https://filfox.info/en/address/f01558688)       |               Toronto, Ontario, CA |         522.31 GiB |      0.33% |  448.19 GiB |          14.19% |
| [f0694396](https://filfox.info/en/address/f0694396)         |            Birmingham, England, GB |         510.00 GiB |      0.32% |  394.00 GiB |          22.75% |
| [f019551](https://filfox.info/en/address/f019551)           |            Birmingham, England, GB |         436.00 GiB |      0.28% |  376.00 GiB |          13.76% |
| [f01606849](https://filfox.info/en/address/f01606849)       |               Montréal, Quebec, CA |         432.00 GiB |      0.27% |  432.00 GiB |           0.00% |
| [f02301](https://filfox.info/en/address/f02301)             |           San Jose, California, US |         278.00 GiB |      0.18% |  252.00 GiB |           9.35% |
| [f01157271](https://filfox.info/en/address/f01157271)       |        Sydney, New South Wales, AU |         227.00 GiB |      0.14% |  129.50 GiB |          42.95% |
| [f01602479](https://filfox.info/en/address/f01602479)       |              Longueuil, Quebec, CA |         224.00 GiB |      0.14% |  216.00 GiB |           3.57% |
| [f0678914](https://filfox.info/en/address/f0678914)         |          San Diego, California, US |         192.31 GiB |      0.12% |  156.19 GiB |          18.78% |
| [f0157535](https://filfox.info/en/address/f0157535)         |               Montréal, Quebec, CA |         144.00 GiB |      0.09% |  108.00 GiB |          25.00% |
| [f0240185](https://filfox.info/en/address/f0240185)         |            Clifton, New Jersey, US |         143.00 GiB |      0.09% |  135.00 GiB |           5.59% |
| [f0143858](https://filfox.info/en/address/f0143858)         |            Clifton, New Jersey, US |         100.00 GiB |      0.06% |  100.00 GiB |           0.00% |
| [f01947280](https://filfox.info/en/address/f01947280)`new`  |             Hangzhou, Zhejiang, CN |          96.00 GiB |      0.06% |   64.00 GiB |          33.33% |
| [f01981571](https://filfox.info/en/address/f01981571)       |                            Unknown |          96.00 GiB |      0.06% |   96.00 GiB |           0.00% |
| [f079426](https://filfox.info/en/address/f079426)`new`      |           Singapore, Singapore, SG |          96.00 GiB |      0.06% |   96.00 GiB |           0.00% |
| [f01131460](https://filfox.info/en/address/f01131460)       |                            Unknown |          51.00 GiB |      0.03% |   33.50 GiB |          34.31% |
| [f014768](https://filfox.info/en/address/f014768)           |           Singapore, Singapore, SG |          40.00 GiB |      0.03% |   40.00 GiB |           0.00% |
| [f01163272](https://filfox.info/en/address/f01163272)       |                Perm, Perm Krai, RU |          36.00 GiB |      0.02% |   36.00 GiB |           0.00% |
| [f0187709](https://filfox.info/en/address/f0187709)         |                 Moscow, Moscow, RU |          32.00 GiB |      0.02% |   32.00 GiB |           0.00% |
| [f01862564](https://filfox.info/en/address/f01862564)`new`  |                 Xi’an, Shaanxi, CN |          32.00 GiB |      0.02% |   32.00 GiB |           0.00% |
| [f01922624](https://filfox.info/en/address/f01922624)`new`  |                            Unknown |          32.00 GiB |      0.02% |   32.00 GiB |           0.00% |
| [f01072221](https://filfox.info/en/address/f01072221)       |        Los Angeles, California, US |          32.00 GiB |      0.02% |   32.00 GiB |           0.00% |
| [f0697249](https://filfox.info/en/address/f0697249)         |               Beijing, Beijing, CN |          32.00 GiB |      0.02% |   32.00 GiB |           0.00% |
| [f01053413](https://filfox.info/en/address/f01053413)       | Hong Kong, Central and Western, HK |          32.00 GiB |      0.02% |   32.00 GiB |           0.00% |
| [f08399](https://filfox.info/en/address/f08399)             |            Seattle, Washington, US |          32.00 GiB |      0.02% |   32.00 GiB |           0.00% |
| [f097777](https://filfox.info/en/address/f097777)           |                Kivertsi, Volyn, UA |          32.00 GiB |      0.02% |   32.00 GiB |           0.00% |
| [f010088](https://filfox.info/en/address/f010088)           |            Everett, Washington, US |          32.00 GiB |      0.02% |   32.00 GiB |           0.00% |
| [f0731235](https://filfox.info/en/address/f0731235)`new`    |                  Odesa, Odessa, UA |          16.00 GiB |      0.01% |   16.00 GiB |           0.00% |
| [f01641612](https://filfox.info/en/address/f01641612)       |               Montréal, Quebec, CA |          16.00 GiB |      0.01% |   16.00 GiB |           0.00% |
| [f01419959](https://filfox.info/en/address/f01419959)       |          San Diego, California, US |           8.00 GiB |      0.01% |    4.00 GiB |          50.00% |
| [f01199442](https://filfox.info/en/address/f01199442)       |   Heerhugowaard, North Holland, NL |           4.00 GiB |      0.00% |    4.00 GiB |           0.00% |
| [f0240456](https://filfox.info/en/address/f0240456)         |               Chengdu, Sichuan, CN |           2.00 GiB |      0.00% |    1.00 GiB |          50.00% |

![Provider Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/151/1671092694972.png)
### Deal Data Replication
The below table shows how each many unique data are replicated across storage providers.
- No more than 25% of unique data are stored with less than 4 providers.

⚠️ 96.56% of deals are for data replicated across less than 4 storage providers.

| Unique Data Size | Total Deals Made | Number of Providers | Deal Percentage |
| ---------------: | ---------------: | ------------------: | --------------: |
|        73.68 TiB |       126.27 TiB |                   1 |          81.63% |
|         9.79 TiB |        20.00 TiB |                   2 |          12.93% |
|       928.50 GiB |         3.11 TiB |                   3 |           2.01% |
|       287.00 GiB |         1.27 TiB |                   4 |           0.82% |
|       112.00 GiB |       614.00 GiB |                   5 |           0.39% |
|        68.00 GiB |       456.00 GiB |                   6 |           0.29% |
|        92.00 GiB |       856.00 GiB |                   7 |           0.54% |
|        88.00 GiB |         1.08 TiB |                   8 |           0.70% |
|        56.00 GiB |       688.00 GiB |                   9 |           0.43% |
|        32.00 GiB |       368.00 GiB |                  10 |           0.23% |
|         4.00 GiB |        60.00 GiB |                  12 |           0.04% |

![Replication Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/151/1671092695649.png)
### Deal Data Shared with other Clients
The below table shows how many unique data are shared with other clients.
Usually different applications owns different data and should not resolve to the same CID.

⚠️ CID sharing has been observed.

| Other Client                                                                                                                                                                                                              | Application                                                                                                                      | Total Deals Affected | Unique CIDs |        Verifier |
| :------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ | :------------------------------------------------------------------------------------------------------------------------------- | -------------------: | ----------: | --------------: |
| [f126k3tkdwfaqpflgcclkiwhqxhh73ebqqazwgcoy](https://filfox.info/en/address/f126k3tkdwfaqpflgcclkiwhqxhh73ebqqazwgcoy)                                                                                                     | [New Web Group](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/356)                                     |           522.72 TiB |       1,342 | LDN v3 multisig |
| [f16ioghg3qy36f6572viouwv4dqow5ejpolo4kodi](https://filfox.info/en/address/f16ioghg3qy36f6572viouwv4dqow5ejpolo4kodi)                                                                                                     | [Shenzhen kuaixue Education Development Co\., Ltd](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/512)  |           513.31 TiB |         735 | LDN v3 multisig |
| [f1t3buz7oqz4fktpthqe43vauhzlnuztpgm3iyhbi](https://filfox.info/en/address/f1t3buz7oqz4fktpthqe43vauhzlnuztpgm3iyhbi)                                                                                                     | [Shenzhen kuaixue Education Development Co\., Ltd](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1363) |           425.56 TiB |         735 | LDN v3 multisig |
| [f1tb2hrxk5eaeewcesnid6xmvfkklfdrxsjr5k6iy](https://filfox.info/en/address/f1tb2hrxk5eaeewcesnid6xmvfkklfdrxsjr5k6iy)                                                                                                     | [Yisainuo](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/537)                                          |            73.09 TiB |         735 | LDN v3 multisig |
| [f3qebbkqspq4w6deouaubtngt4bmaada76uqs3omy<br/>3tki6hoeocpgxyplknev5u3oi5e7xnltobrvgxnpa<br/>3qga](https://filfox.info/en/address/f3qebbkqspq4w6deouaubtngt4bmaada76uqs3omy3tki6hoeocpgxyplknev5u3oi5e7xnltobrvgxnpa3qga) | [codex8080 \- Slingshot Restore](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/152)                    |            64.53 TiB |         424 | LDN v3 multisig |
| [f3rwypb3nhyzkslf6eb2qoiaqdwvaedcawxiav4hm<br/>hi4cp4w7ptjua42knqoddbl5uabcrtzgq7jajvjro<br/>z54a](https://filfox.info/en/address/f3rwypb3nhyzkslf6eb2qoiaqdwvaedcawxiav4hmhi4cp4w7ptjua42knqoddbl5uabcrtzgq7jajvjroz54a) | [dropcool \- Slingshot Restore](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/145)                     |            58.41 TiB |         584 | LDN v3 multisig |
| [f1o54sve7ede7im4caux3ug7lsyjmbue7ss3zzl6y](https://filfox.info/en/address/f1o54sve7ede7im4caux3ug7lsyjmbue7ss3zzl6y)                                                                                                     | [FilSwan](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/278)                                           |            46.94 TiB |         168 | LDN v3 multisig |
| [f1toz5izxdse43peqyd7zktmyqilvhf6u72z74gfq](https://filfox.info/en/address/f1toz5izxdse43peqyd7zktmyqilvhf6u72z74gfq)                                                                                                     | [Starboard Networks](https://github.com/filecoin-project/filecoin-plus-client-onboarding/issues/1855)                            |            32.75 TiB |         424 |       Steven Li |
| [f1unz5yuxgui573lpuh2wyxpsx5ahvw5farqb7hji](https://filfox.info/en/address/f1unz5yuxgui573lpuh2wyxpsx5ahvw5farqb7hji)                                                                                                     | `AOLIGEI`                                                                                                                        |            23.44 TiB |         723 | LDN v3 multisig |
| [f1bstbq5bi72kyovhh7zoo2f6l6uivsjz4ey5dnqq](https://filfox.info/en/address/f1bstbq5bi72kyovhh7zoo2f6l6uivsjz4ey5dnqq)                                                                                                     | [FilSwan](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/917)                                           |             8.47 TiB |         103 | LDN v3 multisig |
| [f14r2jybmccwiu6hze4fu55jyhclktvwacec56hea](https://filfox.info/en/address/f14r2jybmccwiu6hze4fu55jyhclktvwacec56hea)                                                                                                     | [ FilSwan](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/15)                                           |             4.16 TiB |          85 | LDN v3 multisig |
| [f1pkrmygbvweykpjcut36lf7ewgqdfhjklbhvepda](https://filfox.info/en/address/f1pkrmygbvweykpjcut36lf7ewgqdfhjklbhvepda)                                                                                                     | [Protocol Labs \( project: Slingshot Evergreen \)](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/293)  |             1.83 TiB |         120 |       LDN # 293 |
| [f13zfhkvtf6mewd74jhav6iqcggwsojht73tickga](https://filfox.info/en/address/f13zfhkvtf6mewd74jhav6iqcggwsojht73tickga)                                                                                                     | [X\-Order Lab](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/936)                                      |             1.06 TiB |          33 | LDN v3 multisig |
| [f1r3d25hl2y7rqlsu2mgczdethy4qqjmkfdlmibfq](https://filfox.info/en/address/f1r3d25hl2y7rqlsu2mgczdethy4qqjmkfdlmibfq)                                                                                                     | [ NEXRAD \- FilSwan](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/80)                                 |           896.00 GiB |          28 | LDN v3 multisig |
| [f13d6zt424jkp55u7kp67azotkzadtlokwnz2ntxa](https://filfox.info/en/address/f13d6zt424jkp55u7kp67azotkzadtlokwnz2ntxa)                                                                                                     | [ FilSwan \- Slingshot Restore](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/157)                     |           736.00 GiB |          23 | LDN v3 multisig |
| [f3qohcweogfkczlkpjzdzpgsu2x6dsypyckfkjo6f<br/>onecyybxqjffjq6cujcqmt4hf2zlb4jm2ojwock47<br/>bsca](https://filfox.info/en/address/f3qohcweogfkczlkpjzdzpgsu2x6dsypyckfkjo6fonecyybxqjffjq6cujcqmt4hf2zlb4jm2ojwock47bsca) | Unknown                                                                                                                          |            64.00 GiB |           1 |         Unknown |
| [f3vtrnj3jlbsdw3u4jtnjf7v5gy7hwjyuaeuzj7ai<br/>mudpwwuhsg654ytd5344rfi2gwam5jrceb7munoak<br/>nh6q](https://filfox.info/en/address/f3vtrnj3jlbsdw3u4jtnjf7v5gy7hwjyuaeuzj7aimudpwwuhsg654ytd5344rfi2gwam5jrceb7munoaknh6q) | [IPFSPower \- Slingshot Restore](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/154)                    |            32.00 GiB |           1 |       LDN # 154 |

[^1]: To manually trigger this report, add a comment with text `checker:manualTrigger`

**Comment by Sunnyiscoming** [comment]
Hi, @LeoZCH  please explain the abnormal information.

⚠️ [f01878201](https://filfox.info/en/address/f01878201) has sealed 29.49% of total datacap.

⚠️ 70.96% of total deal sealed by [f01878201](https://filfox.info/en/address/f01878201) are duplicate data.

⚠️ 80.02% of total deal sealed by [f03624](https://filfox.info/en/address/f03624) are duplicate data.

⚠️ [f01919426](https://filfox.info/en/address/f01919426) has unknown IP location.

⚠️ 32.57% of total deal sealed by [f066596](https://filfox.info/en/address/f066596) are duplicate data.

⚠️ 27.51% of total deal sealed by [f0165400](https://filfox.info/en/address/f0165400) are duplicate data.

⚠️ 46.90% of total deal sealed by [f01652333](https://filfox.info/en/address/f01652333) are duplicate data.

⚠️ 22.75% of total deal sealed by [f0694396](https://filfox.info/en/address/f0694396) are duplicate data.

⚠️ 42.95% of total deal sealed by [f01157271](https://filfox.info/en/address/f01157271) are duplicate data.

⚠️ 25.00% of total deal sealed by [f0157535](https://filfox.info/en/address/f0157535) are duplicate data.

⚠️ 33.33% of total deal sealed by [f01947280](https://filfox.info/en/address/f01947280) are duplicate data.

⚠️ [f01981571](https://filfox.info/en/address/f01981571) has unknown IP location.

⚠️ 34.31% of total deal sealed by [f01131460](https://filfox.info/en/address/f01131460) are duplicate data.

⚠️ [f01131460](https://filfox.info/en/address/f01131460) has unknown IP location.

⚠️ [f01922624](https://filfox.info/en/address/f01922624) has unknown IP location.

⚠️ 50.00% of total deal sealed by [f01419959](https://filfox.info/en/address/f01419959) are duplicate data.

⚠️ 50.00% of total deal sealed by [f0240456](https://filfox.info/en/address/f0240456) are duplicate data.

⚠️ CID sharing has been observed.

**Comment by Sunnyiscoming** [comment]
Close for no reply. You can reopen it anytime.
