### ISSUE TITLE
[DataCap Application] Change Media

### ISSUE THREAD

**Issue by sfe01** [filecoin-project/filecoin-plus-large-datasets#1510]
### Data Owner Name

Change Media

### Data Owner Country/Region

China

### Data Owner Industry

Information, Media & Telecommunications

### Website

http://1000-x.cn/

### Social Media

```text
https://www.tvcbook.com/u/M5f252862d584b.html
https://space.bilibili.com/650473466
```

### Total amount of DataCap being requested

4PiB

### Weekly allocation of DataCap requested

100TiB

### On-chain address for first allocation

f12jdj24swgj5ccytwxq7vkqo4jsfhpwfy4rvdapa

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Change Media is a brand integrated marketing and communication service company oriented to "creative marketing + efficient communication", providing brand planning, full network marketing, new media operation, video production, media communication and other integrated marketing services for enterprises. With our professional team, strong strength, rich media resources, and project experience accumulated in serving different industries, we provide enterprises with a full chain of integrated marketing services to shape a high-quality brand image and enhance brand value.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
Media contents created by us.
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### How do you plan to prepare the dataset

lotus

### Please share a sample of the data

```text
https://www.tvcbook.com/video/957101.html
https://www.tvcbook.com/video/957097.html
https://www.bilibili.com/video/BV1EK411n793/?spm_id_from=333.999.0.0&vd_source=95344eff1314639246a4c1cc8aec93ce
https://www.bilibili.com/video/BV1mk4y1m7ku/?spm_id_from=333.999.0.0&vd_source=95344eff1314639246a4c1cc8aec93ce
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Sporadic

### For how long do you plan to keep this dataset stored on Filecoin

More than 3 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, South America, Europe, Australia (continent)

### How will you be distributing your data to storage providers

HTTP or FTP server

### How do you plan to choose storage providers

I don't know yet

### How do you plan to make deals to your storage providers

Boost client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by simonkim0515** [comment]
## Datacap Request Trigger

#### Total DataCap requested 
> 4PiB

#### Expected weekly DataCap usage rate 
> 100TiB 

#### Client address
> f12jdj24swgj5ccytwxq7vkqo4jsfhpwfy4rvdapa

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As notary i am screening your application and doing due diligence.

Looking at your application i have some questions:

As you are brand new on Github and have no history of past applications. Applying for 4PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing data and it's requirements and distribution of the data. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?

Can you provide me with some KYC details per e-mail at kyc@dcent.nl. I would like to receive an e-mail from the original domainname / contact as listed on the website that refers to this application. 
Your application is for 4PB of datacap. Can you show us some visible proof from the data size and the storage you have there?

Can you provide us with a distribution plan supposably that you would be granted datacap to store?

As you can see here : https://github.com/filecoin-project/filecoin-plus-large-datasets it states:

> In order for a client and their dataset to be eligible:
> the dataset should be public, open, and mission aligned with Filecoin and Filecoin Plus. This also means that the data should be accessible to anyone > in the network, without requiring any special permissions or access requirement
> stored data should be readily retrievable on the network and this should be regularly verified (though the use of manual or automated verification > that includes retrieving data from various miners over the course of the DataCap allocation timeframe)

To make sure that you understand the rules and guidelines I would like to receive a detailed allocation plan where the amount of data and reputational SP's where you are going to store this data are included. 

As last question you mentioned you want to store media content. Is this content copyright protected and can you show us that you have permission to store it?

**Comment by cryptowhizzard** [comment]
@sfe01 

Any news here?
