### ISSUE TITLE
[DataCap Allocation] - Medical platform

### ISSUE THREAD

**Issue by Netonline2016** [filecoin-project/filecoin-plus-large-datasets#1517]
---
name: Large Dataset Notary application
about: Clients should use this application form to request a DataCap allocation via a LDN for a dataset
title: "Medical platform"
labels: 'application, Phase: Diligence'
assignees: ''

---
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Chengdu Jiutian Zhixin Technology Co., Ltd.
- Website / Social Media: http://www.jtzxsoft.cn/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100TiB
- On-chain address for first allocation: f1zwqkfljcsal74irleiia2yqeq6qcdfngqpfxpyy
- Region: Asia (excl. Greater China)

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Chengdu Jiutian Zhixin Technology Co., Ltd. is led by experts who have been engaged in medical informatization for more than 20 years. The company is located in Zhaoxin Center, Wuhou District, Chengdu. It is mainly engaged in software research and development based on medical care and centered on personal health. Provide professional solutions for smart hospitals, Internet hospitals, medical community construction, medical big data construction, etc.
The company adheres to the corporate tenet of "Let everyone obtain better health", and actively develops a new generation of "Cloud HIS" products with the product concept of "Technology creates more convenient health services". The large product line has formed a strategic layout of "one body with two wings" to provide users with high-quality products and drive the development of smart medical care. We implant the concept of convenience into every detail in the process of product design and research and development, and carry out convenience to the end. Based on cloud computing + AI + 5G technology, we are committed to gradually transitioning system applications from mouse operation mode to natural operation mode (touch, face, voice, gesture, awareness, etc.), and in-depth research and development of more convenient operation methods, so that Apps are available everywhere.
What we do is not just providing software and services for medical care, but long-term cooperation with hospitals. We hope that the new generation of "cloud HIS" products can become a tool and means of hospital modern management and create better benefits for hospitals. We will also continue to launch more practical and convenient products to make medical services within easy reach.
```

What is the primary source of funding for this project?
```
corporate income
```

What other projects/ecosystem stakeholders is this project associated with?
```
None
```

## Use-case details

Describe the data being stored onto Filecoin
```
We need to store a large amount of interactive information between various departments in the hospital, and collaborative information between hospitals. And clinical data management information that meets the requirements of the standard
```

Where was the data in this dataset sourced from?
```
These data come from the company's business development, and the hospital will generate a large amount of data application and processing information every day, as well as information related to medical equipment and operation manuals
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://drive.google.com/drive/folders/1055321TwwSUwPWPccNA-NrDKcFFrDGj1
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Confirm
```

What is the expected retrieval frequency for this data?
```
1-2 times a day
```

For how long do you plan to keep this dataset stored on Filecoin?
```
3 year
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
all regions
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
We have our own IDC computer room to build cloud services. If customers need data, we can provide external networks for customers to download or access
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
Because the confidentiality of data is very important, we will know the size of the storage provider's team, reputation, and whether it has hard-core hardware equipment and a professional technical team before choosing a storage provider
```

How will you be distributing deals across storage providers?
```
We will distribute equally to high-quality storage providers
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
When we get our datacap, we make the transaction immediately. And there is enough money to pay for it.
```

**Comment by herrehesse** [comment]
Dear Applicant,

Due to the increased amount of erroneous/wrong Filecoin+ data recently, on behalf of the entire community, we feel compelled to go deeper into datacap requests. Hereby to ensure that the overall value of the Filecoin network and Filecoin+ program increases and is not abused.

Please answer the questions below as comprehensively as possible.

**Customer data**

- Could you demonstrate exactly how and to what extent customer contact occurred? 

We expect that for the onboarding of customers with the scale of an LDN there would have been at least multiple email and perhaps several chat conversations preceding it. A single email with an agreement does not qualify here.

- Did the customer specify the amount of data involved in this relevant correspondence?

- Why does the customer in question want to use the Filecoin+ program? 

_Should this only be soley for acquiring datacap this is of course **out of the question**. The customer must have a legitimate reason for wanting to use the Filecoin+ program which is intended as a program to store useful and public datasets on the network._ 

- Why is the customer data considered Filecoin+ eligible?

_(As an intermediate solution Filecoin offers the FIL-E program or the glif.io website for business datasets that do not meet the requirements for a Filecoin+ dataset)_


**Files and Processing**

- Could you please demonstrate to us how you envision processing and transporting the customer data in question to any location for preparation?
- Would you demonstrate to us that the customer, the preparer and the intended storage providers all have adequate bandwidth to process the set with its corresponding size?
- Would you tell us how the data set preparer takes into account the prevention of duplicates in order to prevent data cap abuse?


Hopefully you understand the caution the overall community has for onboarding the wrong data. We understand the increased need for Filecoin+, however, we must not allow the program to be misused. Everything depends on a valuable and useful network, let's do our best to make this happen. Together.

**Comment by Netonline2016** [comment]
@herrehesse 
Hello, herrehesse. Regarding the above questions, we made the following responses
1.Could you demonstrate exactly how and to what extent customer contact occurred?
We hold online or offline meetings with customers every month to communicate the amount of data storage generated each month and which data will be stored in Filecoin+

2.Did the customer specify the amount of data involved in this relevant correspondence?
yes

3.Why does the customer in question want to use the Filecoin+ program?
Customers want to share new products, new functions, and new technologies of the medical platform to Filecoin+, so that more medical industries can communicate, so as to promote the improvement of the current difficulties in medical treatment for patients and chaotic hospital management.

4.Why is the customer data considered Filecoin+ eligible?
These data are precious materials output during customer business development and project research and development. Sharing to Filecoin+ is to let more people in the same industry know about us, so as to help progress together.

5.Could you please demonstrate to us how you envision processing and transporting the customer data in question to any location for preparation?
We have temporarily communicated with a storage provider f01926777, who promised that all storage devices will be stored in IDC and have a bandwidth of no less than 500M

6.Would you demonstrate to us that the customer, the preparer and the intended storage providers all have adequate bandwidth to process the set with its corresponding size?
This is our IDC bandwidth speed test
![20230105114735](https://user-images.githubusercontent.com/18053719/210698622-1b238d84-5af5-4dc0-b238-90d296cd0e15.png)


7.Would you tell us how the data set preparer takes into account the prevention of duplicates in order to prevent data cap abuse?
Before uploading data, we will use our self-made program to filter the uploaded data, remove duplicate data, and then manually filter out invalid data to ensure that the uploaded data is valid and meaningful.

**Comment by Sunnyiscoming** [comment]
How much data do you have? How many copies will you store?
What's the relationship between you and the organization?
Whether the sps you choose can support data retrieval?

**Comment by cryptowhizzard** [comment]
Hello,

I see that the retrieval frequency for this data is 1 or 2 times a day, i think this would be a challenge on the short term. The only way to do this is to use Boost and this is not an "entry level" assignment that is easy to acomplish.

However, i will ask some people from your region to join this chat who are respectable SP's and data preparers to see if they can make this a working project.

On a side note .... The data you have should really belong in Fil-E and not in Fil+ as it is not public data. Medical records should be kept private and encrypted.

**Comment by simonkim0515** [comment]
## Datacap Request Trigger

#### Total DataCap requested 
> 5PiB

#### Expected weekly DataCap usage rate 
> 100TiB 

#### Client address
> f1zwqkfljcsal74irleiia2yqeq6qcdfngqpfxpyy

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As notary i am screening your application and doing due diligence.

Looking at your application i have some questions:

As you are brand new on Github and have no history of past applications. Applying for 5PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing data and it's requirements and distribution of the data. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?

Can you provide me with some KYC details per e-mail at kyc@dcent.nl. I would like to receive an e-mail from the original domainname / contact as listed on the website that refers to this application. 
Your application is for 5PB of datacap. Can you show us some visible proof from the data size and the storage you have there?

Can you provide us with a distribution plan supposably that you would be granted datacap to store?

As you can see here : https://github.com/filecoin-project/filecoin-plus-large-datasets it states:

> In order for a client and their dataset to be eligible:
> the dataset should be public, open, and mission aligned with Filecoin and Filecoin Plus. This also means that the data should be accessible to anyone > in the network, without requiring any special permissions or access requirement
> stored data should be readily retrievable on the network and this should be regularly verified (though the use of manual or automated verification > that includes retrieving data from various miners over the course of the DataCap allocation timeframe)

To make sure that you understand the rules and guidelines I would like to receive a detailed allocation plan where the amount of data and reputational SP's where you are going to store this data are included. 

As last question i have some questions about the data itself. Your description is a little vague. The data to be stored should be in line with the mission of FIL+. That means it should be valuable for humanity. Can you be more specific about the data itself and how it can be valuable for humanity? Operational guides for equipment are mostly copyright protected, can you show us that you are authorized to store this copyrighted data?

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Looking at your application i have some questions:
As you are brand new on Github and have no history of past applications it seems to me that applying for 5PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?

Can you show us visible proof of the size of your data and the storage systems you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230232885049356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!

**Comment by Netonline2016** [comment]
@cryptowhizzard 
Hello, this is the storage system we use, which stores the amount of data generated by the organization's business.
![47845f7ab57931c97f1871cbde393c0](https://user-images.githubusercontent.com/18053719/215646947-a8e87f02-e897-4819-8b09-24768e2f6964.png)

**Comment by cryptowhizzard** [comment]
>>
As last question i would like you to fill out [this form](https://form.jotform.com/230232885049356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.
>>

?

**Comment by Netonline2016** [comment]
@cryptowhizzard 
Hello,completed the form.

**Comment by cryptowhizzard** [comment]
Hi @Netonline2016 

Thanks. It is well received.

You provided me with only one SP id where you are going to store data. I need a minimum of 4. 
What i need is the 4 SP id' s and their contact information. If you prefer you can provide the SP ID's in here, and the contact information by e-mail to kyc@dcent.nl. 

Cheers.

**Comment by Netonline2016** [comment]
@cryptowhizzard 
Hello, I have sent the email to the designated email address using kcolle69@163com

**Comment by cryptowhizzard** [comment]
Hi

The SP's you provided are not qualified for FIL+ . They don't have their IP address published on chain and are not open for retrieval.

Please please please ... just read the rules. If you have questions or need help ask on slack.

RULES: In order to be eligible for the Filecoin+ incentive program, which provides 10x the power (QAP) for storing data on the Filecoin network, there are certain rules that must be followed:

Data must be stored with multiple independent service providers, not just one organization running multiple SPs.
Data must be distributed across multiple regions. Using a VPN to fake presence is not allowed.
Data must be publicly retrievable for verification that it is being stored as claimed. It is highly recommended to run boost.
Data must align with the mission of FIL+, meaning it must be valuable for humanity, whether scientific or unique in some other way.
Data must be open and not encrypted. If you wish to encrypt your data, consider applying for the FIL-E program instead.
Note: As a data preparer, you are allowed to store one copy yourself for redundancy at the request of the client. However, if your copy is stored in the USA, the other organizations/SPs must be outside your region. Dcent encourages applications with a minimum spread of 2 continents and 3 different organizations.

**Comment by Netonline2016** [comment]
@cryptowhizzard 
Hello, very sorry that the sp information was provided incorrectly. It has been re-sent through the kcolle69@163com email address. The newly sent sp has the detection function.

**Comment by cryptowhizzard** [comment]
Hi,

I have not received any e-mail from kcolle69@163com . Please send the SP's to kyc@dcent.nl

**Comment by Netonline2016** [comment]
@cryptowhizzard 
![image](https://user-images.githubusercontent.com/18053719/217133509-bea58b6a-06eb-4f61-9e00-a87e3609d4b8.png)
Hello, I sent it again here, thank you for checking it

**Comment by cryptowhizzard** [comment]
Hello,

Thanks. F02017390 does not qualify and has been involved in non-compliant storage of FIL+ data. 
The other 3 ( f01955028,f01955030,f01955034) are all in CN , Zhejiang , Hangzhou.

Let me state the FIL+ rules again:

RULES: In order to be eligible for the Filecoin+ incentive program, which provides 10x the power (QAP) for storing data on the Filecoin network, there are certain rules that must be followed:

Data must be stored with multiple independent service providers, not just one organization running multiple SPs.
**Data must be distributed across multiple regions.** 
Data must be publicly retrievable for verification that it is being stored as claimed. It is highly recommended to run boost.
Data must align with the mission of FIL+, meaning it must be valuable for humanity, whether scientific or unique in some other way.
Data must be open and not encrypted. If you wish to encrypt your data, consider applying for the FIL-E program instead.
Note: As a data preparer, you are allowed to store one copy yourself for redundancy at the request of the client. However, if your copy is stored in the USA, the other organizations/SPs must be outside your region. Dcent encourages applications with a minimum spread of 2 continents and 3 different organizations.

**Comment by Netonline2016** [comment]
@cryptowhizzard 
I am so sorry，The sp information has been carefully sent to the designated mailbox kyc@dcent.nl as required

**Comment by cryptowhizzard** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecvuw25zsezvh2gt4glzq2xnmd3z7gbbkgibdrp6ljdu237ubqy5o 
#### Address 
> f1zwqkfljcsal74irleiia2yqeq6qcdfngqpfxpyy
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1krmypm4uoxxf3g7okrwtrahlmpcph3y7rbqqgfa
#### Id
> ebb9f6e7-d14e-41c5-ab07-4165622d9257
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecvuw25zsezvh2gt4glzq2xnmd3z7gbbkgibdrp6ljdu237ubqy5o

**Comment by cryptowhizzard** [comment]
Thanks, well received.

Looking forward to your first milestone!

**Comment by Netonline2016** [comment]
@cryptowhizzard 
Thank you！

**Comment by GaryGJG** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebprzwmxaixrzdigoohrrujhohjsgqjbxh646lrjn5obqyndtmpck 
#### Address 
> f1zwqkfljcsal74irleiia2yqeq6qcdfngqpfxpyy
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1zffqhxwq2rrg7rtot6lmkl6hb2xyrrseawprzsq
#### Id
> ebb9f6e7-d14e-41c5-ab07-4165622d9257
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebprzwmxaixrzdigoohrrujhohjsgqjbxh646lrjn5obqyndtmpck

**Comment by spaceT9** [comment]
checker:manualTrigger

**Comment by spaceT9** [comment]
checker:manualTrigger

**Comment by Netonline2016** [comment]
Hello, the existing quota has been used up, please allocate the rest

**Comment by cryptowhizzard** [comment]
checker:manualTrigger

**Comment by jinyexon** [comment]
checker:manualTrigger

**Comment by hail100** [comment]
@cryptowhizzard 
Hello, can you help me? The quota is gone.

**Comment by Netonline2016** [comment]
@cryptowhizzard 
Hello, can you help me? The quota is gone.

**Comment by Netonline2016** [comment]
@Sunnyiscoming 
Hello, can you help me? The quota is gone.

**Comment by Netonline2016** [comment]
@Sunnyiscoming 
Hello, can you help me? The quota is gone. The robot did not skip to the next round.

**Comment by zcfil** [comment]
checker:manualTrigger

**Comment by zcfil** [comment]
@Netonline2016 CID sharing has been observed, What caused it?

**Comment by Netonline2016** [comment]
@zcfil 
Hello, our first allocation was completed by inviting the technical assistance of a third-party company, and it may have been confused due to mistakes during the operation at that time. We found out later and corrected the behavior quickly. In the future, we will strictly abide by the fil+ rules.

**Comment by zcfil** [comment]
Okay, we must control the duplication of CID, pass this round of audit, and continuously observe the data status in the future

**Comment by zcfil** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb3hbjzjyl4eaco77bmnp5ynyfu3wvlxpqsgh2yzxabuxreseyzs6 
#### Address 
> f1zwqkfljcsal74irleiia2yqeq6qcdfngqpfxpyy
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1cjzbiy5xd4ehera4wmbz63pd5ku4oo7g52cldga
#### Id
> 9105a64f-3a6d-4acd-a3fb-e1d122e31571
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb3hbjzjyl4eaco77bmnp5ynyfu3wvlxpqsgh2yzxabuxreseyzs6

**Comment by cryptowhizzard** [comment]
Hello @Netonline2016 

As this upcoming allocation is relatively small i won't dispute , but it seems that retrieval is not yet as it should be, especially with SP f02233608

Please do regular checks to make sure you are able to retrieve the data needed for proper due diligence.

Cheers!

cat 1517-f02002405-f02233608-46446961-baga6ea4seaqicpcdjhsor7yv5fnb4ao4tyny7kmhrqm3h3gj774gwdgfwwsrgfq.log
2023-07-27T03:24:11.010+0200	WARN	rpc	go-jsonrpc@v0.3.1/client.go:615	unmarshaling failed	{"message": "{\"Err\":\"exhausted 5 attempts but failed to open stream, err: protocols not supported: [/fil/retrieval/qry/1.0.0]\",\"Root\":null,\"Piece\":null,\"Size\":0,\"MinPrice\":\"\\u003cnil\\u003e\",\"UnsealPrice\":\"\\u003cnil\\u003e\",\"PricePerByte\":\"\\u003cnil\\u003e\",\"PaymentInterval\":0,\"PaymentIntervalIncrease\":0,\"Miner\":\"f02233608\",\"MinerPeer\":{\"Address\":\"f02233608\",\"ID\":\"12D3KooWDJ6hxpTidDnxnHu9Efz8kYHn7brFgd82bvJYmpowMLNx\",\"PieceCID\":null}}"}
2023-07-27T03:24:11.010+0200	INFO	retry	retry/retry.go:17	Retrying after error:RPC client error: unmarshaling result: failed to parse big string: '"\u003cnil\u003e"'
2023-07-27T03:25:00.819+0200	WARN	rpc	go-jsonrpc@v0.3.1/client.go:615	unmarshaling failed	{"message": "{\"Err\":\"exhausted 5 attempts but failed to open stream, err: protocols not supported: [/fil/retrieval/qry/1.0.0]\",\"Root\":null,\"Piece\":null,\"Size\":0,\"MinPrice\":\"\\u003cnil\\u003e\",\"UnsealPrice\":\"\\u003cnil\\u003e\",\"PricePerByte\":\"\\u003cnil\\u003e\",\"PaymentInterval\":0,\"PaymentIntervalIncrease\":0,\"Miner\":\"f02233608\",\"MinerPeer\":{\"Address\":\"f02233608\",\"ID\":\"12D3KooWDJ6hxpTidDnxnHu9Efz8kYHn7brFgd82bvJYmpowMLNx\",\"PieceCID\":null}}"}
2023-07-27T03:25:00.819+0200	INFO	retry	retry/retry.go:17	Retrying after error:RPC client error: unmarshaling result: failed to parse big string: '"\u003cnil\u003e"'
2023-07-27T03:26:20.772+0200	WARN	rpc	go-jsonrpc@v0.3.1/client.go:615	unmarshaling failed	{"message": "{\"Err\":\"exhausted 5 attempts but failed to open stream, err: protocols not supported: [/fil/retrieval/qry/1.0.0]\",\"Root\":null,\"Piece\":null,\"Size\":0,\"MinPrice\":\"\\u003cnil\\u003e\",\"UnsealPrice\":\"\\u003cnil\\u003e\",\"PricePerByte\":\"\\u003cnil\\u003e\",\"PaymentInterval\":0,\"PaymentIntervalIncrease\":0,\"Miner\":\"f02233608\",\"MinerPeer\":{\"Address\":\"f02233608\",\"ID\":\"12D3KooWDJ6hxpTidDnxnHu9Efz8kYHn7brFgd82bvJYmpowMLNx\",\"PieceCID\":null}}"}
2023-07-27T03:26:20.773+0200	INFO	retry	retry/retry.go:17	Retrying after error:RPC client error: unmarshaling result: failed to parse big string: '"\u003cnil\u003e"'
2023-07-27T03:28:12.434+0200	WARN	rpc	go-jsonrpc@v0.3.1/client.go:615	unmarshaling failed	{"message": "{\"Err\":\"exhausted 5 attempts but failed to open stream, err: protocols not supported: [/fil/retrieval/qry/1.0.0]\",\"Root\":null,\"Piece\":null,\"Size\":0,\"MinPrice\":\"\\u003cnil\\u003e\",\"UnsealPrice\":\"\\u003cnil\\u003e\",\"PricePerByte\":\"\\u003cnil\\u003e\",\"PaymentInterval\":0,\"PaymentIntervalIncrease\":0,\"Miner\":\"f02233608\",\"MinerPeer\":{\"Address\":\"f02233608\",\"ID\":\"12D3KooWDJ6hxpTidDnxnHu9Efz8kYHn7brFgd82bvJYmpowMLNx\",\"PieceCID\":null}}"}
2023-07-27T03:28:12.435+0200	INFO	retry	retry/retry.go:17	Retrying after error:RPC client error: unmarshaling result: failed to parse big string: '"\u003cnil\u003e"'
2023-07-27T03:28:56.199+0200	WARN	rpc	go-jsonrpc@v0.3.1/client.go:615	unmarshaling failed	{"message": "{\"Err\":\"exhausted 5 attempts but failed to open stream, err: protocols not supported: [/fil/retrieval/qry/1.0.0]\",\"Root\":null,\"Piece\":null,\"Size\":0,\"MinPrice\":\"\\u003cnil\\u003e\",\"UnsealPrice\":\"\\u003cnil\\u003e\",\"PricePerByte\":\"\\u003cnil\\u003e\",\"PaymentInterval\":0,\"PaymentIntervalIncrease\":0,\"Miner\":\"f02233608\",\"MinerPeer\":{\"Address\":\"f02233608\",\"ID\":\"12D3KooWDJ6hxpTidDnxnHu9Efz8kYHn7brFgd82bvJYmpowMLNx\",\"PieceCID\":null}}"}
2023-07-27T03:28:56.199+0200	ERROR	retry	retry/retry.go:29	Failed after 5 attempts, last error: RPC client error: unmarshaling result: failed to parse big string: '"\u003cnil\u003e"'
ERROR: RPC client error: unmarshaling result: failed to parse big string: '"\u003cnil\u003e"'

**Comment by MRJAVAZHAO** [comment]
If you can come up with a plan for improving data retriecal, we'd like to sign it.

**Comment by Netonline2016** [comment]
@MRJAVAZHAO 
Hi, thanks for the reminder. We are also in the process of continuous improvement. The reason for the low number of retrievals is that our sps are still in storage, and the rest of the retrieved data are distributed and stored in these sps. Once all stores are complete, retrieval will resume normally.

**Comment by Netonline2016** [comment]
checker:manualTrigger

**Comment by Netonline2016** [comment]
checker:manualTrigger

**Comment by lyjmry** [comment]
checker:manualTrigger

**Comment by jinyexon** [comment]
checker:manualTrigger

**Comment by cryptowhizzard** [comment]
![Scherm­afbeelding 2023-08-21 om 13 43 18](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/36404435/4d4a98d9-157e-4b9e-b35b-66d2466d84b9)
![Scherm­afbeelding 2023-08-21 om 13 43 10](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/36404435/a0d8ca06-a694-476d-baab-783db6206807)

**Comment by jinyexon** [comment]
checker:manualTrigger

**Comment by jinyexon** [comment]
checker:manualTrigger

**Comment by Carohere** [comment]
> ![Scherm­afbeelding 2023-08-21 om 13 43 18](https://user-images.githubusercontent.com/36404435/262012814-4d4a98d9-157e-4b9e-b35b-66d2466d84b9.png) ![Scherm­afbeelding 2023-08-21 om 13 43 10](https://user-images.githubusercontent.com/36404435/262012835-a0d8ca06-a694-476d-baab-783db6206807.png)


@Netonline2016  Could you get your SPs to fix these errors this week?

**Comment by jinyexon** [comment]
checker:manualTrigger

**Comment by cryptowhizzard** [comment]
<img width="1352" alt="Scherm­afbeelding 2023-08-23 om 19 57 08" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/36404435/89c8327d-a4f6-4f83-bbca-1fef46ac9cda">

I have never been able to get a retrieval from you. What is wrong here with this provider?

**Comment by raghavrmadya** [comment]
@Netonline2016, kindly respond to the dispute here - https://www.notion.so/filecoin/Retrieval-not-working-368cfeece1a44048b2deb0d16cc9539d?pvs=4

No response within 2 weeks will result in closure of application and removal of existing DC
