### ISSUE TITLE
[DataCap Application] <Organization> - <Project Name>

### ISSUE THREAD

**Issue by zlkg1688** [filecoin-project/filecoin-plus-large-datasets#1518]
### Data Owner Name

www.zjhl-sz.com

### Data Owner Country/Region

China

### Data Owner Industry

Web3 / Crypto

### Website

www.zjhl-sz.com

### Social Media

```text
www.zjhl-sz.com
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

100TiB

### On-chain address for first allocation

f1dcazydkog4o3gwlgprwrzrk6ognbsien2ye63fa

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Shenzhen ZhongJinHuLian Technology Co., Ltd. is located in 3001 Ludan Building, No. 1011 Binhe Road, Ludan Village Community, Guiyuan Street, Luohu District, Shenzhen, with a registered capital of 100 million yuan and was established on April 12, 2021.     At present, the company's main business scope is general business items, including:
technology development,
Data processing service;
Technical development of computer software;
technology consulting and technology services of the Internet;     Mobile Internet APP technology development,
Media technology，
technical consulting and technical services;
Technical development of computer software;
technology services and technology transfer of computer technology;     Research and development of network technology;
R&D and sales of new materials and communication products
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
The data stored on Filecoin is all about production data, R&D data, sales data.
```

### Where was the data currently stored in this dataset sourced from

Other

### If you answered "Other" in the previous question, enter the details here

```text
Mainly from the data generated during our research and development, design, transportation and sales
```

### Please share a sample of the data

```text
https://drive.google.com/drive/folders/1AJMSXjkGwQycvZk3-N8BetkdtN_ubBXs?usp=sharing
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Sporadic

### For how long do you plan to keep this dataset stored on Filecoin

Less than 1 year

### In which geographies do you plan on making storage deals

Greater China

### How will you be distributing your data to storage providers

HTTP or FTP server, I don't know yet

### How do you plan to choose storage providers

Big data exchange, Partners, I don't know yet

### How do you plan to make deals to your storage providers

Boost client, Lotus client, Bidbot

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by herrehesse** [comment]
Dear Applicant,

Due to the increased amount of erroneous/wrong Filecoin+ data recently, on behalf of the entire community, we feel compelled to go deeper into datacap requests. Hereby to ensure that the overall value of the Filecoin network and Filecoin+ program increases and is not abused.

Please answer the questions below as comprehensively as possible.

**Customer data**

- Could you demonstrate exactly how and to what extent customer contact occurred? 

We expect that for the onboarding of customers with the scale of an LDN there would have been at least multiple email and perhaps several chat conversations preceding it. A single email with an agreement does not qualify here.

- Did the customer specify the amount of data involved in this relevant correspondence?

- Why does the customer in question want to use the Filecoin+ program? 

_Should this only be soley for acquiring datacap this is of course **out of the question**. The customer must have a legitimate reason for wanting to use the Filecoin+ program which is intended as a program to store useful and public datasets on the network._ 

- Why is the customer data considered Filecoin+ eligible?

_(As an intermediate solution Filecoin offers the FIL-E program or the glif.io website for business datasets that do not meet the requirements for a Filecoin+ dataset)_


**Files and Processing**

- Could you please demonstrate to us how you envision processing and transporting the customer data in question to any location for preparation?
- Would you demonstrate to us that the customer, the preparer and the intended storage providers all have adequate bandwidth to process the set with its corresponding size?
- Would you tell us how the data set preparer takes into account the prevention of duplicates in order to prevent data cap abuse?


Hopefully you understand the caution the overall community has for onboarding the wrong data. We understand the increased need for Filecoin+, however, we must not allow the program to be misused. Everything depends on a valuable and useful network, let's do our best to make this happen. Together.

**Comment by zlkg1688** [comment]
Could you demonstrate exactly how and to what extent customer contact occurred?
>Our company has a large number of stable customer resources and needs to process and connect with a large amount of data.    Before that, we have maintained good communication with our customers.

We expect that for the onboarding of customers with the scale of an LDN there would have been at least multiple email and perhaps several chat conversations preceding it.                        A single email with an agreement does not qualify here.
>zhongjinhulian@zjhl-sz.com

Did the customer specify the amount of data involved in this relevant correspondence?
>yes

Why does the customer in question want to use the Filecoin+ program?
>Most importantly, information can be stored securely using the program.                     Don't worry about outages of central storage.

Should this only be soley for acquiring datacap this is of course out of the question.                        The customer must have a legitimate reason for wanting to use the Filecoin+ program which is intended as a program to store useful and public datasets on the network.
>yes，Our company has been in the data storage industry for more than a decade, and there is an urgent need for a new, more secure way to store data.

Why is the customer data considered Filecoin+ eligible?
>Storage, more secure and reliable was our priority, and obviously, it met our expectations.

(As an intermediate solution Filecoin offers the FIL-E program or the glif.                       io website for business datasets that do not meet the requirements for a Filecoin+ dataset)

Files and Processing

Could you please demonstrate to us how you envision processing and transporting the customer data in question to any location for preparation?
>We will go offline, using hard drives to copy the data and then store the data

Would you demonstrate to us that the customer, the preparer and the intended storage providers all have adequate bandwidth to process the set with its corresponding size?
>We'll mail it offline.

Would you tell us how the data set preparer takes into account the prevention of duplicates in order to prevent data cap abuse?
>We will be through the form of a contract, a strong binding of business practices

Hopefully you understand the caution the overall community has for onboarding the wrong data.                        We understand the increased need for Filecoin+, however, we must not allow the program to be misused.                        Everything depends on a valuable and useful network, let's do our best to make this happen.                        Together.
>Yes, we have worked together to improve the filcoin+ ecosystem.

**Comment by Sunnyiscoming** [comment]
Can you explain your data composition? How many copies will you store?
What's the relationship between you and the organization?

**Comment by zlkg1688** [comment]
Software development related source code, documents, design data, the company's computer room surveillance video data. There is the operation of e-commerce product information, as well as product-related video information.
For the sake of security, some important data & file data need to be double backed up.
I am in charge of database maintenance and management in the company

**Comment by herrehesse** [comment]
@zlkg1688 Thank you for your detailed answers.

Why does the customer in question want to use the Filecoin+ program?
**Most importantly, information can be stored securely using the program. Don't worry about outages of central storage.**

Should this only be soley for acquiring datacap this is of course out of the question. The customer must have a legitimate reason for wanting to use the Filecoin+ program which is intended as a program to store useful and public datasets on the network.
**Yes, our company has been in the data storage industry for more than a decade, and there is an urgent need for a new, more secure way to store data.**

The above answers do NOT make your data eligible for the Filecoin+ program. You should take a look at regular deals and pay for the storage or try a FIL-E application with @kevzak .

**Comment by kevzak** [comment]
@herrehesse based on the application information, this is a public data application. 

E-Fil+ is a program for Private Data owners. Please let me know if you need more background before promoting the program incorrectly. Thank you.

**Comment by herrehesse** [comment]
Hi @kevzak,

Thanks for your response, to my understanding the E in E-FIL (FIL-E) stood for "enterprise" and thus the business applications of datacap. In case I have misunderstood this my apologies for the miscommunication.

I remain of the opinion that many of these applications are out of place when applying for datacap and should be prepared to store their business data with relevant storage providers for a fee. The gift of "datacap" should not be given at will to people who simply ask for it. The relevant data should at least contribute to a more valuable network, not solely for miners to grow with a multiplier.

**Comment by simonkim0515** [comment]
## Datacap Request Trigger

#### Total DataCap requested 
> 5PiB

#### Expected weekly DataCap usage rate 
> 100TiB 

#### Client address
> f1dcazydkog4o3gwlgprwrzrk6ognbsien2ye63fa

**Comment by zhangyiqiangwork** [comment]
Hi @filplus-checker-app 
This is a new application address.

**Comment by stcouldlisa** [comment]
This customer didn't even modify the title, and many contents in the article were not answered, and the application form looked like a draft.
