### ISSUE TITLE
[DataCap Application] - <baoya Fund>

### ISSUE THREAD

**Issue by sanxunl** [filecoin-project/filecoin-plus-large-datasets#1519]
### Data Owner Name

Xi'an baoya Fund Management Partnership (Limited Partnership)

### Data Owner Country/Region

China

### Data Owner Industry

Financial Services

### Website

https://gs.amac.org.cn/amac-infodisc/res/pof/manager/1812271707108231.html

### Social Media

```text
none
```

### Total amount of DataCap being requested

1PiB

### Weekly allocation of DataCap requested

100TiB

### On-chain address for first allocation

f3wg6mwnxzzh72icaxhnur5wyxliz5smdtahoiitnsw75cv2eirr5elyxnmj6abipfobagz7vqan3qtwjhtiea

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
The company is a professional investment institution for securities fund enterprises registered in the Chinese industry, with the registration number: P1070648. The company was established in November 2018, and its core members are from a group of senior personnel in investment, banking, finance and taxation, computer, etc（https://gs.amac.org.cn/amac-infodisc/res/pof/manager/1812271707108231.html）.As of August 2022, the company manages the Baoya Quantitative series of securities investment fund products. The management scale is nearly 50 million. Companies adhering to the concept of multi-strategy investment, in the continuous scientific investment, value discovery and other gradually formed characteristics and steady development.
```

### Is this project associated with other projects/ecosystem stakeholders?

Yes

### If answered yes, what are the other projects/ecosystem stakeholders

```text
Fund companies have cooperated with sp to store data in the traditional way for retrieval applications, which can be used for fund companies' quantitative strategies and research
```

### Describe the data being stored onto Filecoin

```text
Stock trading and quantitative investment backtest analysis system related business data
```

### Where was the data currently stored in this dataset sourced from

Other

### If you answered "Other" in the previous question, enter the details here

```text
Sources are mainly provided by financial terminal platforms and related industry institutions
```

### How do you plan to prepare the dataset

lotus

### Please share a sample of the data

```text
https://github.com/filecoin-project/filecoin-plus-client-onboarding/files/9798985/Fund.data1.pdf
https://github.com/filecoin-project/filecoin-plus-client-onboarding/files/9798988/Fund.data2.pdf
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Daily

### For how long do you plan to keep this dataset stored on Filecoin

More than 3 years

### In which geographies do you plan on making storage deals

Greater China

### How will you be distributing your data to storage providers

HTTP or FTP server, IPFS, Shipping hard drives, Lotus built-in data transfer

### How do you plan to choose storage providers

Slack, Filmine, Big data exchange, Partners

### How do you plan to make deals to your storage providers

Boost client, Lotus client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1086
Why you open this new application for the same project?

**Comment by simonkim0515** [comment]
## Datacap Request Trigger

#### Total DataCap requested 
> 1PiB

#### Expected weekly DataCap usage rate 
> 100TiB 

#### Client address
> f3wg6mwnxzzh72icaxhnur5wyxliz5smdtahoiitnsw75cv2eirr5elyxnmj6abipfobagz7vqan3qtwjhtiea

**Comment by cryptowhizzard** [comment]
#1086 

No responses here. I guess it is better to close them.

The data does not look genuine to me ( See translated PDF to english ) . These are fake funds.


[Fund.data2.pdf](https://github.com/filecoin-project/filecoin-plus-large-datasets/files/10426147/Fund.data2.pdf)
[Fund.data1.pdf](https://github.com/filecoin-project/filecoin-plus-large-datasets/files/10426148/Fund.data1.pdf)

[translate_Fund.data1.pdf](https://github.com/filecoin-project/filecoin-plus-large-datasets/files/10426146/translate_Fund.data1.pdf)
