### ISSUE TITLE
[DataCap Application] codex8080 Slingshot Restore Program

### ISSUE THREAD

**Issue by codex8080** [filecoin-project/filecoin-plus-large-datasets#152]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: codex8080 - Slingshot Restore
- Website / Social Media: https://gitee.com/codex8080
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):500 TiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 200 TiB
- On-chain address for first allocation: f3qebbkqspq4w6deouaubtngt4bmaada76uqs3omy3tki6hoeocpgxyplknev5u3oi5e7xnltobrvgxnpa3qga

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
this DataCap is for **Slingshot Restore Program**, and the detail is follows:

https://docs.google.com/document/d/1ZH4URWaNYtlddZwZMyqcSnc3GRsR3zCqnW0RfkkNlr8/edit# 
https://docs.google.com/document/d/1sGLkw321Fl09jvAr80kFY2FcQWa1H-dYpowXFRWo-OM/edit 

https://docs.google.com/spreadsheets/d/1UYmVtwtJUIAwlogZmLSZB_nZxWrVlID6ryfqrB0jBjw/edit#gid=1779251844 
https://docs.google.com/spreadsheets/d/1Skga2Yn0BD7CDgT1WQmKtPJ3nxhQ4QWd45e78Y42Wjc/edit#gid=0
```
![image](https://user-images.githubusercontent.com/3350961/146706480-41c09719-4d48-4d5d-a928-80ddc9b1500e.png)
![image](https://user-images.githubusercontent.com/3350961/146706545-f1700de2-bd87-4511-947d-e01cdc283763.png)
![image](https://user-images.githubusercontent.com/3350961/146706586-f123e473-e4c3-4788-b8d1-ab87b62240f1.png)

What is the primary source of funding for this project?
```
From the slingshot team and my team.
```

What other projects/ecosystem stakeholders is this project associated with?
```
No
```

## Use-case details

Describe the data being stored onto Filecoin
```
I have participated in the Slingshot Restoreis Project：

https://docs.google.com/spreadsheets/d/1UYmVtwtJUIAwlogZmLSZB_nZxWrVlID6ryfqrB0jBjw/edit#gid=1779251844

```
![image](https://user-images.githubusercontent.com/3350961/146706307-eb276efe-4860-4424-8d77-0c6f0b655f4a.png)

![image](https://user-images.githubusercontent.com/3350961/146706235-f0adb69e-6928-49f6-8625-c9d811791286.png)

![image](https://user-images.githubusercontent.com/3350961/146706365-319c410e-d7f4-4dd5-b17f-9ba42db887f4.png)

Where was the data in this dataset sourced from?
```
The data comes from the slingshot team assigned to me by the project：

https://docs.google.com/spreadsheets/d/1UYmVtwtJUIAwlogZmLSZB_nZxWrVlID6ryfqrB0jBjw/edit#gid=1203385488

https://commoncrawl.org/2021/10/september-2021-crawl-archive-now-available/

These dataset is public, everyone can download them directly.

```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://commoncrawl.s3.amazonaws.com/crawl-data/CC-MAIN-2021-39/segments/1631780053493.41/warc/CC-MAIN-20210916094919-20210916124919-00000.warc.gz
https://commoncrawl.s3.amazonaws.com/crawl-data/CC-MAIN-2021-39/segments/1631780053493.41/warc/CC-MAIN-20210916094919-20210916124919-00001.warc.gz
https://commoncrawl.s3.amazonaws.com/crawl-data/CC-MAIN-2021-39/segments/1631780053493.41/warc/CC-MAIN-20210916094919-20210916124919-00002.warc.gz
https://commoncrawl.s3.amazonaws.com/crawl-data/CC-MAIN-2021-39/segments/1631780053493.41/warc/CC-MAIN-20210916094919-20210916124919-00003.warc.gz
https://commoncrawl.s3.amazonaws.com/crawl-data/CC-MAIN-2021-39/segments/1631780053493.41/warc/CC-MAIN-20210916094919-20210916124919-00004.warc.gz
https://commoncrawl.s3.amazonaws.com/crawl-data/CC-MAIN-2021-39/segments/1631780053493.41/warc/CC-MAIN-20210916094919-20210916124919-00005.warc.gz
https://commoncrawl.s3.amazonaws.com/crawl-data/CC-MAIN-2021-39/segments/1631780053493.41/warc/CC-MAIN-20210916094919-20210916124919-00006.warc.gz
https://commoncrawl.s3.amazonaws.com/crawl-data/CC-MAIN-2021-39/segments/1631780053493.41/warc/CC-MAIN-20210916094919-20210916124919-00007.warc.gz
https://commoncrawl.s3.amazonaws.com/crawl-data/CC-MAIN-2021-39/segments/1631780053493.41/warc/CC-MAIN-20210916094919-20210916124919-00008.warc.gz
https://commoncrawl.s3.amazonaws.com/crawl-data/CC-MAIN-2021-39/segments/1631780053493.41/warc/CC-MAIN-20210916094919-20210916124919-00009.warc.gz
https://commoncrawl.s3.amazonaws.com/crawl-data/CC-MAIN-2021-39/segments/1631780053493.41/warc/CC-MAIN-20210916094919-20210916124919-00010.warc.gz
https://commoncrawl.s3.amazonaws.com/crawl-data/CC-MAIN-2021-39/segments/1631780053493.41/warc/CC-MAIN-20210916094919-20210916124919-00011.warc.gz

```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes.
```

What is the expected retrieval frequency for this data?
```
Anytime.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
More than 500 days
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
 China
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
I will store every file to at least 4 storage providers, the offline data process will be supported.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
The three storage providers will locate different regions, and their power must more than 5PiB. And providers must agree that they should store unsealed files and keep these data retrieved all the time.
```

How will you be distributing deals across storage providers?
```
One storage provider will get one data-deal at least.  And the more power  storage provider has, the more deals will be assigned. 
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, I have contact some providers. And the data download has been downloaded. 
```

**Comment by galen-mcandrew** [comment]
## Multisig Notary requested
#### Total DataCap requested 
> 500TiB
#### Expected weekly DataCap usage rate 
> 200TiB

**Comment by flyworker** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceasd5srg76wqn5cc5mz6hskygshnkv5nqcmxr2v3trmemflwx3mw4 
#### Address 
> f3qebbkqspq4w6deouaubtngt4bmaada76uqs3omy3tki6hoeocpgxyplknev5u3oi5e7xnltobrvgxnpa3qga
#### Datacap Allocated
> 25TiB
#### Signer Address
> f1hlubjsdkv4wmsdadihloxgwrz3j3ernf6i3cbpy
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceasd5srg76wqn5cc5mz6hskygshnkv5nqcmxr2v3trmemflwx3mw4

**Comment by neogeweb3** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceal7opo2ihiedvzcw7sfv33ajye4knoso753alxj6nax6l6djir3o 
#### Address 
> f3qebbkqspq4w6deouaubtngt4bmaada76uqs3omy3tki6hoeocpgxyplknev5u3oi5e7xnltobrvgxnpa3qga
#### Datacap Allocated
> 25TiB
#### Signer Address
> f13k5zr6ovc2gjmg3lvd43ladbydhovpylcvbflpa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceal7opo2ihiedvzcw7sfv33ajye4knoso753alxj6nax6l6djir3o

**Comment by fabriziogianni7** [comment]
@galen-mcandrew @codex8080 after checking the transaction, the allocation went through. removing error label and adding granted

**Comment by cryptowhizzard** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacea6ncrg7d2x6jywxw3hwn4c2hyagdaj2uuqaqffoaeos7qkhmmuak 
#### Address 
> f3qebbkqspq4w6deouaubtngt4bmaada76uqs3omy3tki6hoeocpgxyplknev5u3oi5e7xnltobrvgxnpa3qga
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1krmypm4uoxxf3g7okrwtrahlmpcph3y7rbqqgfa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacea6ncrg7d2x6jywxw3hwn4c2hyagdaj2uuqaqffoaeos7qkhmmuak

**Comment by liyunzhi-666** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebcwrp53hgjz5tnshd6rmxffywgpniiie5o6zk4j57msacqtgeub2 
#### Address 
> f3qebbkqspq4w6deouaubtngt4bmaada76uqs3omy3tki6hoeocpgxyplknev5u3oi5e7xnltobrvgxnpa3qga
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1pszcrsciyixyuxxukkvtazcokexbn54amf7gvoq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebcwrp53hgjz5tnshd6rmxffywgpniiie5o6zk4j57msacqtgeub2

**Comment by IreneYoung** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceduoy4b7z62jypekbnh6h3dgf6573txxd4nkfg7haonr3ta47ljos 
#### Address 
> f3qebbkqspq4w6deouaubtngt4bmaada76uqs3omy3tki6hoeocpgxyplknev5u3oi5e7xnltobrvgxnpa3qga
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1d4gmpqz3execjj2wvrxuuhvbms5mzh7t7yqrviq
#### Id
> c4a550d7-f3a8-4462-8409-67e3e9a9702d
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceduoy4b7z62jypekbnh6h3dgf6573txxd4nkfg7haonr3ta47ljos

**Comment by filplus-checker** [comment]
## DataCap and CID Checker Report[^1]
 - Organization: `codex8080 - Slingshot Restore`
 - Client: `f3qebbkqspq4w6deouaubtngt4bmaada76uqs3omy3tki6hoeocpgxyplknev5u3oi5e7xnltobrvgxnpa3qga`
### Storage Provider Distribution
The below table shows the distribution of storage providers that have stored data for this client.

If this is the first time a provider takes verified deal, it will be marked as `new`.

For most of the datacap application, below restrictions should apply.
 - Storage provider should not exceed 25% of total datacap.
 - Storage provider should not be storing duplicate data for more than 20%.
 - Storage provider should have published its public IP address.
 - All storage providers should be located in different regions.

⚠️ [f01878201](https://filfox.info/en/address/f01878201) has sealed 56.11% of total datacap.

⚠️ 79.47% of total deal sealed by [f01878201](https://filfox.info/en/address/f01878201) are duplicate data.

⚠️ [f01901773](https://filfox.info/en/address/f01901773) has sealed 43.89% of total datacap.

| Provider                                              |                           Location | Total Deals Sealed | Percentage | Unique Data | Duplicate Deals |
| :---------------------------------------------------- | ---------------------------------: | -----------------: | ---------: | ----------: | --------------: |
| [f01878201](https://filfox.info/en/address/f01878201) |             Hangzhou, Zhejiang, CN |          64.53 TiB |     56.11% |   13.25 TiB |          79.47% |
| [f01901773](https://filfox.info/en/address/f01901773) | Hong Kong, Central and Western, HK |          50.47 TiB |     43.89% |   50.47 TiB |           0.00% |

![Provider Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/152/1671092700777.png)
### Deal Data Replication
The below table shows how each many unique data are replicated across storage providers.
- No more than 25% of unique data are stored with less than 4 providers.

⚠️ 100.00% of deals are for data replicated across less than 4 storage providers.

| Unique Data Size | Total Deals Made | Number of Providers | Deal Percentage |
| ---------------: | ---------------: | ------------------: | --------------: |
|        63.72 TiB |       115.00 TiB |                   1 |         100.00% |

![Replication Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/152/1671092701474.png)
### Deal Data Shared with other Clients
The below table shows how many unique data are shared with other clients.
Usually different applications owns different data and should not resolve to the same CID.

⚠️ CID sharing has been observed.

| Other Client                                                                                                                                                                                                              | Application                                                                                                                      | Total Deals Affected | Unique CIDs |        Verifier |
| :------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ | :------------------------------------------------------------------------------------------------------------------------------- | -------------------: | ----------: | --------------: |
| [f16ioghg3qy36f6572viouwv4dqow5ejpolo4kodi](https://filfox.info/en/address/f16ioghg3qy36f6572viouwv4dqow5ejpolo4kodi)                                                                                                     | [Shenzhen kuaixue Education Development Co\., Ltd](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/512)  |             1.16 PiB |       1,615 | LDN v3 multisig |
| [f1t3buz7oqz4fktpthqe43vauhzlnuztpgm3iyhbi](https://filfox.info/en/address/f1t3buz7oqz4fktpthqe43vauhzlnuztpgm3iyhbi)                                                                                                     | [Shenzhen kuaixue Education Development Co\., Ltd](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1363) |           861.88 TiB |       1,615 | LDN v3 multisig |
| [f1tb2hrxk5eaeewcesnid6xmvfkklfdrxsjr5k6iy](https://filfox.info/en/address/f1tb2hrxk5eaeewcesnid6xmvfkklfdrxsjr5k6iy)                                                                                                     | [Yisainuo](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/537)                                          |           146.53 TiB |       1,612 | LDN v3 multisig |
| [f1unz5yuxgui573lpuh2wyxpsx5ahvw5farqb7hji](https://filfox.info/en/address/f1unz5yuxgui573lpuh2wyxpsx5ahvw5farqb7hji)                                                                                                     | `AOLIGEI`                                                                                                                        |            75.72 TiB |       1,371 | LDN v3 multisig |
| [f3rwypb3nhyzkslf6eb2qoiaqdwvaedcawxiav4hm<br/>hi4cp4w7ptjua42knqoddbl5uabcrtzgq7jajvjro<br/>z54a](https://filfox.info/en/address/f3rwypb3nhyzkslf6eb2qoiaqdwvaedcawxiav4hmhi4cp4w7ptjua42knqoddbl5uabcrtzgq7jajvjroz54a) | [dropcool \- Slingshot Restore](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/145)                     |            52.81 TiB |         424 | LDN v3 multisig |
| [f3v7x4a2aapgx6o2r477tenoin3u5oadaeqyd7kjd<br/>sitykvf4ok7vq2utcyh34lmu5u7oybs25ff6s4dbu<br/>dpma](https://filfox.info/en/address/f3v7x4a2aapgx6o2r477tenoin3u5oadaeqyd7kjdsitykvf4ok7vq2utcyh34lmu5u7oybs25ff6s4dbudpma) | [LeoCheung \- Slingshot Restore](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/151)                    |            45.63 TiB |         424 | LDN v3 multisig |
| [f1toz5izxdse43peqyd7zktmyqilvhf6u72z74gfq](https://filfox.info/en/address/f1toz5izxdse43peqyd7zktmyqilvhf6u72z74gfq)                                                                                                     | [Starboard Networks](https://github.com/filecoin-project/filecoin-plus-client-onboarding/issues/1855)                            |            32.75 TiB |         424 |       Steven Li |
| [f126k3tkdwfaqpflgcclkiwhqxhh73ebqqazwgcoy](https://filfox.info/en/address/f126k3tkdwfaqpflgcclkiwhqxhh73ebqqazwgcoy)                                                                                                     | [New Web Group](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/356)                                     |             3.19 TiB |         101 | LDN v3 multisig |

[^1]: To manually trigger this report, add a comment with text `checker:manualTrigger`
