### ISSUE TITLE
[DataCap Application] 1W3

### ISSUE THREAD

**Issue by data-programs** [filecoin-project/filecoin-plus-large-datasets#1527]
### Data Owner Name
1W3

### Data Owner Country/Region
India

### Data Owner Industry
Web3 / Crypto

### Website
[https://1W3.io](https://1W3.io)

### Github Handle
@1W3io

### Social Media
@1W3io (Twitter)

### Total amount of DataCap being requested
112 TiB

### Weekly allocation of DataCap requested
10 GiB

### On-chain address for first allocation
f1atl736o7c777afsxuhodip232tgwio6be3jdywy

### Custom multisig
No

### Share a brief history of your project and organization
1w3 is a  no-code website builder where users can create professional-grade web3sites with ease. With our predefined web templates and components users can drag-and-drop interface, can easily add and arrange elements like text, images, and videos, as well as customize the layout and design of their website.
The team behind 1W3 is the same team that built w3layouts.com. We have a decade of experience in web templates and designs. W3layouts has more than 4000 templates. W3layouts have 1 million signed-up users with 17 million downloads and more than 80k website live. We are trying the bring all this experience into the web3site builder.

### Is this project associated with other projects/ecosystem stakeholders?
No

### Describe the data being stored onto Filecoin
We will be storing the websites of users into IPFS where the CID will be updated to ENS and web3 domains to make the websites live.

### Where was the data currently stored in this dataset sourced from
My own storage infra

### How do you plan to prepare the dataset
IPFS

### Please share a sample of the data
https://bafybeieyojyhh67uztpcvhygaupassq2a3aczo5mnhcr7de2s7tr4ghwqa.ipfs.w3s.link

http://k51qzi5uqu5dhki443fx2mpjxfuzx58rn00qthda1hyvp2l5mok9sbwctivo9e.ipns.w3s.link
https://bafybeid7wexpekm5yuwcd5665ilnteac7zcir57zpp6phezbgjnveeotxy.ipfs.w3s.link
https://bafybeifox5yj4zrvv3wcjq72kokenpu44zepu2gpssmwru5w3fsi2sisra.ipfs.w3s.link

https://bafybeiekbwpcs4vbukfjtrvcoakpolnwvfbaqt6luz5xnhjpav6lzf3bxq.ipfs.w3s.link
https://bafybeieuc7ysgzagvdqo6rzufsbieodrpti2etqcmshlcqrzmrz4fuycaq.ipfs.w3s.link
https://bafybeidqnywftfotxmjqn7ntm43eizvkfjgba3adt2jrbmjkacvq2tzrvi.ipfs.w3s.link

### Confirm that this is a public dataset that can be retrieved by anyone on the Network
Yes

### What is the expected retrieval frequency for this data
Daily

### For how long do you plan to keep this dataset stored on Filecoin
Permanently

### In which geographies do you plan on making storage deals
South America

### How will you be distributing your data to storage providers
IPFS

### How do you plan to choose SP
I don't know yet

### How do you plan to make deals to your storage providers
I don't know yet

### Can you confirm that you will follow the Fil+ guideline
Yes

**Comment by herrehesse** [comment]
@data-programs The application looks great,  your website is also very clear. Is there anything you need assistance with?

**Comment by Sunnyiscoming** [comment]
What's the relationship between you and the organization? 
Please provide documents to prove that the team behind 1W3 is the same team that built w3layouts.com.

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As notary i am screening your application and doing due diligence.

Looking at your application i have some questions:

As you are brand new on Github and have no history of past applications. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?

Can you provide me with some KYC details per e-mail at kyc@dcent.nl. I would like to receive an e-mail from the original domainname / contact as listed on the website that refers to this application. 
Can you show us some visible proof from the data size and the storage you have there?

Can you provide us with a distribution plan supposably that you would be granted datacap to store?

As you can see here : https://github.com/filecoin-project/filecoin-plus-large-datasets it states:

> In order for a client and their dataset to be eligible:
> the dataset should be public, open, and mission aligned with Filecoin and Filecoin Plus. This also means that the data should be accessible to anyone > in the network, without requiring any special permissions or access requirement
> stored data should be readily retrievable on the network and this should be regularly verified (though the use of manual or automated verification > that includes retrieving data from various miners over the course of the DataCap allocation timeframe)

To make sure that you understand the rules and guidelines I would like to receive a detailed allocation plan where the amount of data and reputational SP's where you are going to store this data are included.

**Comment by simonkim0515** [comment]
## Datacap Request Trigger

#### Total DataCap requested 
> 112TiB

#### Expected weekly DataCap usage rate 
> 10GiB 

#### Client address
> f1atl736o7c777afsxuhodip232tgwio6be3jdywy
