### ISSUE TITLE
[DataCap Application] Derek- Mooc

### ISSUE THREAD

**Issue by hanyan007** [filecoin-project/filecoin-plus-large-datasets#1541]
### Data Owner Name

Derek（Hangzhou）Cultural Institutions

### Data Owner Country/Region

China

### Data Owner Industry

Information, Media & Telecommunications

### Website

http://www.dlk.asia

### Social Media

```text
www.dlk.asia
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

300TiB

### On-chain address for first allocation

f1qavvbrfn2q3l4eyb73ku5xjgy3x2lettilsjlzq

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Ltd. was established in 2013, is a film and television culture communication team dedicated to brand strategy services, new media development and operation, film and television filming and production and live streaming pushing services on various platforms.

Our business undertakes services related to video production, such as shooting and production of high-quality courses in colleges and universities, image promotion films, personalized movie business cards, large outdoor performances, product shooting and production, short video shooting and production, VR panoramic shooting and production, video ringtone shooting and production, live streaming and other services related to video production on various platforms.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
High school class shooting production, image film, personalized film business card, large
outdoor performance activities, product shooting, short video shooting, VR panoramic shooting, video ringtone shooting, live streaming on various platforms.
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### Please share a sample of the data

```text
ok, http://www.dlk.asia/#/
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [ ] I confirm

### What is the expected retrieval frequency for this data

Sporadic

### For how long do you plan to keep this dataset stored on Filecoin

Permanently

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America

### How will you be distributing your data to storage providers

HTTP or FTP server

### How do you plan to choose storage providers

Slack, Partners

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by herrehesse** [comment]
Dear @hanyan007 applicant,

Thank you for applying for an LDN on the Filecoin+ program.
Taking a deeper dive into your application I can see that you describe your content as:

"High school class shooting production, image film, personalized film business card, large
outdoor performance activities, product shooting, short video shooting, VR panoramic shooting, video ringtone shooting, live streaming on various platforms."

This kind of business data does not fit into the Filecoin+ program and therefore I can not support your application.
You can take a look at the FIL-E program for business content, do you need any help with that?

@raghavrmadya @Sunnyiscoming

**Comment by cryptowhizzard** [comment]
Good morning,

I was checking about this.

Can you give evidence about the size of the data you are going to store and samples? How big is the dataset you have there? What is it stored on?

Is all this data available to the public world wide? What is the value to the Filecoin network of this data?

The website voor this company is just 2 weeks old. What happened in the past 10 years here?

![Scherm­afbeelding 2023-01-09 om 10 05 17](https://user-images.githubusercontent.com/36404435/211272723-38e2be72-bfb0-4964-8d98-a707c46e6cdb.png)

**Comment by hanyan007** [comment]
> Dear @hanyan007 applicant,
> 
> Thank you for applying for an LDN on the Filecoin+ program. Taking a deeper dive into your application I can see that you describe your content as:
> 
> "High school class shooting production, image film, personalized film business card, large outdoor performance activities, product shooting, short video shooting, VR panoramic shooting, video ringtone shooting, live streaming on various platforms."
> 
> This kind of business data does not fit into the Filecoin+ program and therefore I can not support your application. You can take a look at the FIL-E program for business content, do you need any help with that?
> 
> @raghavrmadya @Sunnyiscoming

@herrehesse @raghavrmadya @Sunnyiscoming 

Hi, thank you for asking. The data we plan to store are mainly video teaching and skill training. Please check the sample: http://www.dlk.asia/media/train.6cefcca6.mp4 、 http://www.dlk.asia/media/eda.15225f17.mp4 According to the official requirements, the real data is required to be public and searchable without privacy. It is the data that can be accessed by anyone without legal dispute. I think our data meets the requirements. We have data storage requirements. If there is any information that needs further communication, please let us know. Thank you.

**Comment by cryptowhizzard** [comment]
Hello,

Can you please answer my question?

> The website voor this company is just 2 weeks old. What happened in the past 10 years here?

**Comment by hanyan007** [comment]
> Good morning,
> 
> I was checking about this.
> 
> Can you give evidence about the size of the data you are going to store and samples? How big is the dataset you have there? What is it stored on?
> 
> Is all this data available to the public world wide? What is the value to the Filecoin network of this data?
> 
> The website voor this company is just 2 weeks old. What happened in the past 10 years here?
> 
> ![Scherm­afbeelding 2023-01-09 om 10 05 17](https://user-images.githubusercontent.com/36404435/211272723-38e2be72-bfb0-4964-8d98-a707c46e6cdb.png)



>

**Comment by hanyan007** [comment]
> Hello,
> 
> Can you please answer my question?
> 
> > The website for this company is just 2 weeks old. What happened in the past 10 years here?

Good morning, I am very modest to reply so late. I have prepared some materials to explain what we have done in the past ten years.
Since the establishment of the company in 2013, we have positioned ourselves as a new type of startup company. We have been committed to business development for 10 years, shooting a lot of videos and accumulating a lot of video data, but we have been neglecting website construction.
![20](https://user-images.githubusercontent.com/14324188/211703151-80cea647-519d-463d-ad7a-006f4c09a5eb.png)
![21](https://user-images.githubusercontent.com/14324188/211703182-98d7a54f-f618-4831-bc83-9bcd0219be53.png)
![22](https://user-images.githubusercontent.com/14324188/211703207-bbc5d13c-f919-40cd-a489-2658fc8c9b53.png)
![23](https://user-images.githubusercontent.com/14324188/211703227-96a3d9e5-8d61-4911-a2c3-479b9b08052c.png)
![24](https://user-images.githubusercontent.com/14324188/211703234-693acb49-20a9-423e-9c15-0280be8fb56e.png)
![25](https://user-images.githubusercontent.com/14324188/211703248-d14cded7-966f-4954-8446-94056d54164e.png)
![26](https://user-images.githubusercontent.com/14324188/211703253-8f633b24-80ba-42f9-b0c3-fcf1822ddeca.png)
![27](https://user-images.githubusercontent.com/14324188/211703262-fbcb6923-5b2b-4597-b877-01f39e084b9e.png)
![28](https://user-images.githubusercontent.com/14324188/211703282-525acb9c-df1e-4cb3-8749-d1d0b621f7b4.png)
![29](https://user-images.githubusercontent.com/14324188/211703296-2bef8766-c6a6-4fe2-83fa-f469d5fb5f81.png)
![30](https://user-images.githubusercontent.com/14324188/211703309-ad870917-ba7f-4e48-b49c-9fb053d405c2.png)
![31](https://user-images.githubusercontent.com/14324188/211703320-4245bfc9-ef63-4397-8a4d-060a30d22284.png)
![32](https://user-images.githubusercontent.com/14324188/211703331-76dd1086-fbd5-4d67-9ca2-5dd19ffdd6af.png)
![33](https://user-images.githubusercontent.com/14324188/211703333-44bd71d1-3363-44c2-abc6-9cd56e879110.png)
![34](https://user-images.githubusercontent.com/14324188/211703340-afc69c4d-76c9-4723-81c4-b293736e83c7.png)
![35](https://user-image
![1](https://user-images.githubusercontent.com/14324188/211703373-c958b269-638d-431c-b3a1-878559742534.png)
s.githubusercontent.com/14324188/211703348-af43322b-13d7-4739-a20c-2c93b82631f7.png)
![1-1](https://user-images.githubusercontent.com/14324188/211703381-9cf2b64c-9b7d-4020-9849-e08dbe56e373.png)
![11](https://user-images.githubusercontent.com/14324188/211703394-129a7f6b-8194-4ed9-90ef-8aa9976bee10.png)
![12](https://user-images.githubusercontent.com/14324188/211703398-40f860d8-abca-47b4-8362-1c298b51a56f.png)
![8](https://user-images.githubusercontent.com/14324188/211703407-c60f5269-99c8-4a13-9875-01f1ece3c35c.png)
The above is the business accumulation of our company in the past 10 years. Our company has a wide influence in the industry and the customer group is relatively stable.
At the same time, we have uploaded cooperation agreements with important partners for nearly 10 years, and these customers still maintain long-term cooperation with us, which is also the source of so much data we have.
<img width="568" alt="1673403944408(1)" src="https://user-images.githubusercontent.com/14324188/211703606-f2376613-9183-4ada-bded-7cbb19e22266.png">
![扫描 2](https://user-images.githubusercontent.com/14324188/211703640-544ffd9e-a74a-453b-9be9-ff32608bce48.jpeg)
![扫描 3](https://user-images.githubusercontent.com/14324188/211703648-6e13d4c8-5090-4e21-a0c8-975f1b5cda81.jpeg)
![扫描](https://user-images.githubusercontent.com/14324188/211703674-a3b245cf-8b37-41af-839a-e2f9ba8fc04f.jpeg)
![扫描 1](https://user-images.githubusercontent.com/14324188/211703685-3e99537a-4578-406c-afd7-ccc2e9ee1207.jpeg)
![扫描](https://user-images.githubusercontent.com/14324188/211703738-f33d0f89-5aba-48c2-88ee-b4c3d37a3723.jpeg)
![扫描 1](https://user-images.githubusercontent.com/14324188/211703747-04071895-1db5-4366-a4a6-f779d229b65f.jpeg)
![扫描](https://user-images.githubusercontent.com/14324188/211703775-c26c4906-4a6d-45bb-a0ac-f85607340114.jpeg)
![扫描 1](https://user-images.githubusercontent.com/14324188/211703783-0435f201-eac0-4b77-9e8f-7f438e58b8cb.jpeg)
![扫描](https://user-images.githubusercontent.com/14324188/211703815-44279b8f-2fab-4959-b1d8-3245b5413f12.jpeg)
![扫描 1](https://user-images.githubusercontent.com/14324188/211703822-7bd17b64-a927-4079-a129-309690e988bd.jpeg)
![扫
![扫描](https://user-images.githubusercontent.com/14324188/211703893-42778793-9e33-4724-b364-bb549921e8c3.jpeg)
描](https://user-images.githubusercontent.com/14324188/211703850-469b048f-e90b-48ad-8a69-4df114b21edc.jpeg)
![扫描 1](https://user-images.githubusercontent.com/14324188/211703867-f0760a56-38bf-4b46-b341-908378829cb7.jpeg)
![扫描 1](https://user-images.githubusercontent.com/14324188/211703924-bb3249b5-e41e-46fa-b157-2229435323d1.jpeg)
![扫描 2](https://user-images.githubusercontent.com/14324188/211703953-2ca6a029-6ff7-4c55-ae2d-420a6c4121a7.jpeg)
![扫描 3](https://user-images.githubusercontent.com/14324188/211703990-942bbac0-f6b7-4ef5-87db-4ac87d0bfc6b.jpeg)
![扫描 4](https://user-images.githubusercontent.com/14324188/211704002-accdf9fe-6835-4e6c-b450-2db4ba75405b.jpeg)
![扫描](https://user-images.githubusercontent.com/14324188/211704031-28a5296b-dd87-486c-be09-990de215bece.jpeg)
![扫描 1](https://user-images.githubusercontent.com/14324188/211704046-5ecafaf1-5103-4706-9b3f-f82c87a642f3.jpeg)
![杭州阿优合作合同2020年](https://user-images.githubusercontent.com/14324188/211704071-7009dc97-794d-47a8-ad85-2da0abc19b83.jpeg)
![杭州阿优合作合同2020年 1](https://user-images.githubusercontent.com/14324188/211704081-a55b7cda-60ca-4127-b9c2-dd346b50d7c0.jpeg)
![扫描](https://user-images.githubusercontent.com/14324188/211704120-a30e2094-fcc3-4b25-b5ca-ebc375e07e5a.jpeg)
![扫描 4](https://user-images.githubusercontent.com/14324188/211704130-7295ab30-3867-4336-afb2-bb400634109a.jpeg)
With the help of this opportunity of filecoin, we also happen to carry out standardization transformation. The website construction is only the first step. We will also operate social media such as WeChat official account and Tiktok. Thank you!

**Comment by hanyan007** [comment]
> Good morning,
> 
> I was checking about this.
> 
> Can you give evidence about the size of the data you are going to store and samples? How big is the dataset you have there? What is it stored on?
> 
> Is all this data available to the public world wide? What is the value to the Filecoin network of this data?
> 
> The website voor this company is just 2 weeks old. What happened in the past 10 years here?
> 
> ![Scherm­afbeelding 2023-01-09 om 10 05 17](https://user-images.githubusercontent.com/36404435/211272723-38e2be72-bfb0-4964-8d98-a707c46e6cdb.png)
Good morning, I am very modest to reply so late. I have prepared some materials to explain what we have done in the past ten years.
Since the establishment of the company in 2013, we have positioned ourselves as a new type of startup company. We have been committed to business development for 10 years, shooting a lot of videos and accumulating a lot of video data, but we have been neglecting website construction. The above is the business accumulation of our company in the past 10 years. Our company has a wide influence in the industry and the customer group is relatively stable. At the same time, we have uploaded cooperation agreements with important partners for nearly 10 years, and these customers still maintain long-term cooperation with us, which is also the source of so much data we have. With the help of this opportunity of filecoin, we also happen to carry out standardization transformation. The website construction is only the first step. We will also operate social media such as WeChat official account and Tiktok.Thank you!

**Comment by herrehesse** [comment]
Hello @hanyan007 

The provided materials als not suited for the Filecoin+ program. Please ask @kevzak for an FIL-E application.

"High school class shooting production, image film, personalized film business card, large
outdoor performance activities, product shooting, short video shooting, VR panoramic shooting, video ringtone shooting, live streaming on various platforms."

**Comment by kevzak** [comment]
Hello - E-Fil+ is a pilot program to onboard private, encrypted datasets. @hanyan007 see more info here if that is something you'd be interested in pursuing: https://efilplus.super.site/

**Comment by cryptowhizzard** [comment]
Website / company not reachable.

I recommend on closing this application. There is no base for trust this way.

![Scherm­afbeelding 2023-01-16 om 15 10 14](https://user-images.githubusercontent.com/36404435/212697639-57a4a8e6-7ac9-4ecb-85ce-1fcd446a6122.png)

![Scherm­afbeelding 2023-01-16 om 15 10 50](https://user-images.githubusercontent.com/36404435/212697800-fb76d21b-760c-4da1-8573-7c5377bd5e5c.png)

**Comment by hanyan007** [comment]
> Website / company not reachable.
> 
> I recommend on closing this application. There is no base for trust this way.
> 
> ![Scherm­afbeelding 2023-01-16 om 15 10 14](https://user-images.githubusercontent.com/36404435/212697639-57a4a8e6-7ac9-4ecb-85ce-1fcd446a6122.png)
> 
> ![Scherm­afbeelding 2023-01-16 om 15 10 50](https://user-images.githubusercontent.com/36404435/212697800-fb76d21b-760c-4da1-8573-7c5377bd5e5c.png)

Hello, the website has been repaired. Because our company is a video shooting company and has fixed customers offline, our dependence on the company's website is not high, and our company is also unable to support full-time IT engineers. Therefore, our website is built on the company's internal server by our colleagues who know a little about the network. In China, the bandwidth of fixed public IP is 10 times the price difference of non-fixed IP bandwidth, Then we borrowed the fixed IP of other companies through FRP, and just in the middle of January, 2/3 of the company's people got sick leave from COVID-19, which led to no maintenance of our servers. After finding this problem, we have migrated the server to the leased cloud server.

**Comment by hanyan007** [comment]
@Sunnyiscoming Hello, because we did not maintain the website well during the epidemic, the project was closed. The details have been explained above. Please help us open this project, thank you!

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 5PiB

**Expected weekly DataCap usage rate**
> 300TiB

**Client address**
>f1qavvbrfn2q3l4eyb73ku5xjgy3x2lettilsjlzq

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 5PiB

**Expected weekly DataCap usage rate**
> 300TiB

**Client address**
>f1qavvbrfn2q3l4eyb73ku5xjgy3x2lettilsjlzq

**Comment by kernelogic** [comment]
From reading the above history and talked to the client, it appears the course data is not private or encrypted. Given that this application is reopened, willing to support and see the distribution result.

**Comment by kernelogic** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceddblesbko54o3sz4eiz7tubv55hxj3zzs3av7dn3ys7l65dhre4s 
#### Address 
> f1qavvbrfn2q3l4eyb73ku5xjgy3x2lettilsjlzq
#### Datacap Allocated
> 150.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### Id
> 1004ae53-32ba-4855-81e5-33b2953a6909
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceddblesbko54o3sz4eiz7tubv55hxj3zzs3av7dn3ys7l65dhre4s

**Comment by TimGuo7** [comment]
Willing to support those data to be stored to support the educational purpose

**Comment by TimGuo7** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceabmfqfqmih4b2dlkhtujfg32nkgligoct2tnesjgz3tievtazdlo 
#### Address 
> f1qavvbrfn2q3l4eyb73ku5xjgy3x2lettilsjlzq
#### Datacap Allocated
> 150.00TiB
#### Signer Address
> f1yslbnnqzrjlyuxsmyxfbqcc7xthcavgpripjevi
#### Id
> 1004ae53-32ba-4855-81e5-33b2953a6909
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceabmfqfqmih4b2dlkhtujfg32nkgligoct2tnesjgz3tievtazdlo

**Comment by hanyan007** [comment]
We have been preparing the data for quite some time, and we are now ready to do a big job! @simonkim0515
