### ISSUE TITLE
[DataCap Application] web3eye.io

### ISSUE THREAD

**Issue by data-programs** [filecoin-project/filecoin-plus-large-datasets#1542]
### Data Owner Name
web3eye.io

### Data Owner Country/Region
Hong Kong

### Data Owner Industry
Web3 / Crypto

### Website
[https://web3eye.io](https://web3eye.io)

### Github Handle
@kikakkz

### Social Media
@web3_eye (@web_eye)

### Total amount of DataCap being requested
1.07 PiB

### Weekly allocation of DataCap requested
50 TiB

### On-chain address for first allocation
f1pvixpahnuxfjp73ojo43oax5asoopobyqu4hmea

### Custom multisig
No

### Share a brief history of your project and organization
Web3Eye is aimed to build a cross chain indexer for onchain content, including NFTs, articles, videos, etc.

### Is this project associated with other projects/ecosystem stakeholders?
Yes

### If answered yes, what are the other projects/ecosystem stakeholders
FIL-Peggy

### Describe the data being stored onto Filecoin
Backup data of indexer snapshot

### Where was the data currently stored in this dataset sourced from
My own storage infra

### How do you plan to prepare the dataset
others/custom tool

### If you answered "other/custom tool" in the previous question, enter the details here
https://github.com/tech-greedy/singularity.git

### Please share a sample of the data
web3eye.io is in development and we already finish indexer part. we can provide sample at Q2, 2023

### Confirm that this is a public dataset that can be retrieved by anyone on the Network
Yes

### What is the expected retrieval frequency for this data
Weekly

### For how long do you plan to keep this dataset stored on Filecoin
More than 3 years

### In which geographies do you plan on making storage deals
Asia other than Greater China

### How will you be distributing your data to storage providers
Shipping hard drives

### How do you plan to choose SP
Partners

### How do you plan to make deals to your storage providers
Boost client

### Can you confirm that you will follow the Fil+ guideline
Yes

**Comment by herrehesse** [comment]
Dear Applicant,

_(Your website is not reachable, please resolve)_

Due to the increased amount of erroneous/wrong Filecoin+ data recently, on behalf of the entire community, we feel compelled to go deeper into datacap requests. Hereby to ensure that the overall value of the Filecoin network and Filecoin+ program increases and is not abused.

Please answer the questions below as comprehensively as possible.

**Customer data**

- Could you demonstrate exactly how and to what extent customer contact occurred? 

We expect that for the onboarding of customers with the scale of an LDN there would have been at least multiple email and perhaps several chat conversations preceding it. A single email with an agreement does not qualify here.

- Did the customer specify the amount of data involved in this relevant correspondence?

- Why does the customer in question want to use the Filecoin+ program? 

_Should this only be soley for acquiring datacap this is of course **out of the question**. The customer must have a legitimate reason for wanting to use the Filecoin+ program which is intended as a program to store useful and public datasets on the network._ 

- Why is the customer data considered Filecoin+ eligible?

_(As an intermediate solution Filecoin offers the FIL-E program or the glif.io website for business datasets that do not meet the requirements for a Filecoin+ dataset)_


**Files and Processing**

- Could you please demonstrate to us how you envision processing and transporting the customer data in question to any location for preparation?
- Would you demonstrate to us that the customer, the preparer and the intended storage providers all have adequate bandwidth to process the set with its corresponding size?
- Would you tell us how the data set preparer takes into account the prevention of duplicates in order to prevent data cap abuse?


Hopefully you understand the caution the overall community has for onboarding the wrong data. We understand the increased need for Filecoin+, however, we must not allow the program to be misused. Everything depends on a valuable and useful network, let's do our best to make this happen. Together.

**Comment by lvschouwen** [comment]
@data-programs 
As already stated your website is currently offline.
You state the sample data of this dataset will be on your website, so until its reachable we cannot verify anything.

On the question "How do you plan to prepare the dataset" you have specified Other and the answered Singularity, while that is a option on the list. I find this strange.

Do you have a list of storage providers who you will work with in this dataset?

**Comment by simonkim0515** [comment]
## Datacap Request Trigger

#### Total DataCap requested 
> 1.07PiB

#### Expected weekly DataCap usage rate 
> 50TiB 

#### Client address
> f1pvixpahnuxfjp73ojo43oax5asoopobyqu4hmea

**Comment by cryptowhizzard** [comment]
Website offline. Recommend closing.

**Comment by kikakkz** [comment]
> Website offline. Recommend closing.

not offline. we're developing it, and will be online soon. we have a lot storage space requirement for our indexer snapshot.

**Comment by cryptowhizzard** [comment]
Can you update us when you are ready to proceed then and when the website is in good shape?

**Comment by kikakkz** [comment]
not accurate but we will have a test version for open access at about 2/10. for first release version should be about end of Feb.

**Comment by cryptowhizzard** [comment]
Ok, then we can put this on hold until 10 februari 2023. Let us know when you are ready.

**Comment by kikakkz** [comment]
> Ok, then we can put this on hold until 10 februari 2023. Let us know when you are ready.

@cryptowhizzard https://hk-testing.web3eye.io/ we have a test site here. it's not full function but it can show something we're trying to build.

**Comment by cryptowhizzard** [comment]
Ok, thanks for sharing!

Please fill out [this form](https://form.jotform.com/230337462961356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

**Comment by cryptowhizzard** [comment]
Hi @kikakkz 

Well received. Upon checking i noticed that SP f07824 has a bad reputation. Can you replace it with another SP please?

**Comment by cryptowhizzard** [comment]
Yes please

**Comment by kikakkz** [comment]
@cryptowhizzard please replase f07824 to f023152

**Comment by cryptowhizzard** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecz7z4pq75nentvmowhruvdplviatupbojeykr7sfe7onwhxfuflg 
#### Address 
> f1pvixpahnuxfjp73ojo43oax5asoopobyqu4hmea
#### Datacap Allocated
> 25.00TiB
#### Signer Address
> f1krmypm4uoxxf3g7okrwtrahlmpcph3y7rbqqgfa
#### Id
> 26558ef3-fc88-4448-b6e4-dcb1e17f3078
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecz7z4pq75nentvmowhruvdplviatupbojeykr7sfe7onwhxfuflg

**Comment by kikakkz** [comment]
@simonkim0515 @Kevin-FF-USA @galen-mcandrew @raghavrmadya hi guys, we plan to launch our cross chain indexer soon, and want to store indexer snapshot to Filecoin storage. could you please help to approve this application ?

**Comment by Joss-Hua** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebi7rvdfidkalottu6rb4clsainisyi7vuywpg6zzudt3iti4qpeo 
#### Address 
> f1pvixpahnuxfjp73ojo43oax5asoopobyqu4hmea
#### Datacap Allocated
> 25.00TiB
#### Signer Address
> f1tfg54zzscugttejv336vivknmsnzzmyudp3t7wi
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebi7rvdfidkalottu6rb4clsainisyi7vuywpg6zzudt3iti4qpeo

**Comment by kikakkz** [comment]
Dear Notaries, please take a look at our LDN. Welcome to leave your comments inside and let me know if there is any quesiton.

**Comment by kikakkz** [comment]
https://testnet.web3eye.io/  we have a test site version here. indexer service for ethereum and solana is ready. currently we're development snapshot and backup service of the content.

**Comment by GaryGJG** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacea7syp2hgyvlg7xlweqpzvwfvnsofxebrbz2sphzpnouhfwakfwwq 
#### Address 
> f1pvixpahnuxfjp73ojo43oax5asoopobyqu4hmea
#### Datacap Allocated
> 25.00TiB
#### Signer Address
> f1zffqhxwq2rrg7rtot6lmkl6hb2xyrrseawprzsq
#### Id
> 26558ef3-fc88-4448-b6e4-dcb1e17f3078
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacea7syp2hgyvlg7xlweqpzvwfvnsofxebrbz2sphzpnouhfwakfwwq

**Comment by kikakkz** [comment]
@GaryGJG thanks man. we're developing our web3eye NFT survivor for coming HackFS, with that we can snapshort the cross chain content and store to Filecoin storage provider~

**Comment by kikakkz** [comment]
@GaryGJG before we don't note the execute result of the message seems not success. could you please help to sign again ?
![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/13128505/b83ab4d6-901f-4813-984d-c171402f86dc)

**Comment by GaryGJG** [comment]
Hi @kikakkz I can't find your request in my filplus portal to sign now .. who can help on this ??

**Comment by cryptowhizzard** [comment]
checker:manualTrigger

**Comment by kikakkz** [comment]
> now

@Kevin-FF-USA @galen-mcandrew @raghavrmadya could you please help ?

**Comment by kikakkz** [comment]
@Kevin-FF-USA @galen-mcandrew @raghavrmadya hi, any update of that ?

**Comment by kikakkz** [comment]
@Kevin-FF-USA @raghavrmadya @galen-mcandrew hi, could you please help to solve that ? we'll generate our first production dataset soon. do we need to create a new one ?

**Comment by kikakkz** [comment]
@Kevin-FF-USA @raghavrmadya @galen-mcandrew hi, could you please help to solve that ? we'll generate our first production dataset soon. do we need to create a new one ?

**Comment by kikakkz** [comment]
> This application has not seen any responses in the last 10 days. This issue will be marked with Stale label and will be closed in 4 days. Comment if you want to keep this application open.

we need someone help to solve the failed sign.

**Comment by kikakkz** [comment]
@Kevin-FF-USA @raghavrmadya @galen-mcandrew hi, could you please help to solve that ? we'll generate our first production dataset soon. do we need to create a new one ?

**Comment by kikakkz** [comment]
This application has not seen any responses in the last 10 days. This issue will be marked with Stale label and will be closed in 4 days. Comment if you want to keep this application open.

**Comment by kikakkz** [comment]
@Kevin-FF-USA @raghavrmadya @galen-mcandrew hi, could you please help to solve that ? we'll generate our first production dataset soon. do we need to create a new one ?

**Comment by kikakkz** [comment]
@Kevin-FF-USA @raghavrmadya @galen-mcandrew hi, could you please help to solve that ? we'll generate our first production dataset soon. do we need to create a new one ?

**Comment by kikakkz** [comment]
@Kevin-FF-USA @raghavrmadya @galen-mcandrew hi, could you please help to solve that ? we'll generate our first production dataset soon. do we need to create a new one ?

**Comment by kikakkz** [comment]
@Kevin-FF-USA @raghavrmadya @galen-mcandrew hi, could you please help to solve that ? we'll generate our first production dataset soon. do we need to create a new one ?

**Comment by kikakkz** [comment]
@Kevin-FF-USA @raghavrmadya @galen-mcandrew hi, could you please help to solve that ? we'll generate our first production dataset soon. do we need to create a new one ?

**Comment by kikakkz** [comment]
@Kevin-FF-USA @raghavrmadya @galen-mcandrew hi, could you please help to solve that ? do we need to create a new one ?

**Comment by kikakkz** [comment]
@Kevin-FF-USA @raghavrmadya @galen-mcandrew hi, could you please help to solve that ? do we need to create a new one ?

**Comment by Sunnyiscoming** [comment]
Hello, @kikakkz per the https://github.com/filecoin-project/notary-governance/issues/922 for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

This information will be reviewed by Fil+ Governance team to confirm validity and then the application will be allowed to move forward for additional notary review.

**Comment by kikakkz** [comment]
![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/13128505/276c2251-b257-4e89-82c5-06c3006f2cb0)

**Comment by Filplus-govteam** [comment]
SP List provided:
 f0111584 | Entropy Pool | Singapore | No | N/A
f01970622 |Crypto More | Hongkong | No | Zhao KK
f01713152 | Entropy Pool | Singapore | No | N/A
f01970630 | Crypto More | Hongkong | No | Zhao KK
f0111499 | Yiqifei | Chengdu, China | No | guikai

**Comment by Filplus-govteam** [comment]
checker:manualTrigger

**Comment by herrehesse** [comment]
checker:manualTrigger

**Comment by kikakkz** [comment]
hey, any one can help to process our application ?

**Comment by Sunnyiscoming** [comment]
SP List provided:
[{"providerID":"f0111584","City":"XYZ","Country":"Singapore","SPOrg","EntropyPool"},
{"providerID":"f01970622","City":"Hongkong","Country":"CN","SPOrg","CryptoMore"},
{"providerID":"f01713152","City":"XYZ","Country":"Singapore","SPOrg","EntropyPool"},
{"providerID":"f01970630","City":"Hongkong","Country":"CN","SPOrg","CryptoMore"},
{"providerID":"f0111499","City":"Chengdu","Country":"CN","SPOrg","Yiqifei"},]

**Comment by kikakkz** [comment]
hey, any one can help to process our application ?

**Comment by kikakkz** [comment]
hey, any one can help to process our application ?

**Comment by kikakkz** [comment]
hey, any one can help to process our application ?
