### ISSUE TITLE
[DataCap Application] Speedium - 1000 Genomes Phase 3 Reanalysis with DRAGEN 3.5 and 3.7 [Part 2 / 3]

### ISSUE THREAD

**Issue by cryptowhizzard** [filecoin-project/filecoin-plus-large-datasets#1549]
### Data Owner Name

International Genome (EMBL-EBI)

### Data Owner Country/Region

United Kingdom

### Data Owner Industry

Life Science / Healthcare

### Website

https://www.internationalgenome.org/category/phase-3/ & https://www.ebi.ac.uk/

### Social Media

```text
https://www.facebook.com/EMBLEBI/
https://github.com/topics/1000genomes
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

500TiB

### On-chain address for first allocation

f1klrehuwhzfw6boiiywdi7pikztsob4kkieivcwq

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Since its launch, the Filecoin network has become an important player in the decentralised storage space, offering a secure and transparent alternative to traditional data storage solutions.

We as Speedium / DCENT have been engaged with storing real and valuable datasets on the Filecoin network since Slingshot 2.6 and have been actively developing tools to improve the process. We are always on the lookout for new and useful client data to onboard.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
This dataset contains alignment files and short nucleotide, copy number, repeat expansion (STR) and structural variant call files from the 1000 Genomes Project Phase 3 dataset (n=3202) using Illumina DRAGEN v3.5.7b and v3.7.6 software.
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### How do you plan to prepare the dataset

IPFS, lotus, singularity, graphsplit

### Please share a sample of the data

```text
https://registry.opendata.aws/ilmn-dragen-1kgp/
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

1.5 to 2 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, South America, Europe, Australia (continent)

### How will you be distributing your data to storage providers

HTTP or FTP server, IPFS, Shipping hard drives, Lotus built-in data transfer

### How do you plan to choose storage providers

Slack, Big data exchange, Partners

### If you already have a list of storage providers to work with, fill out their names and provider IDs below

| MinerID | City | Continent | Business/Entity |
| --- | --- | --- | --- |
| `f01944347` | Oregon | USA | Jenny, Dabai |
| `f01952350` | Oregon | USA | Jenny, Dabai |
| `f01972364` | Oregon | USA | Jenny, Dabai |
| `f01972376` | Oregon | USA | Jenny, Dabai |
| `f02000937` | Chengdu | CN | MTY |
| `f01915033` | Chengdu | CN | MTY |
| `f01901765` | Hangzhou | CN | MTY |
| `f01953985` | Shenzhen | CN | MTY |
| `f0120****` | Melbourne | AU | HOLON |
| `f0115****` | Melbourne | AU | HOLON |
| `f01199430` | Heerhugowaard | EU | DCENT |
| `f01786387` | Heerhugowaard | EU | DCENT |
| `f01201327` | Heerhugowaard | EU | DCENT |
| `f01937642` | Heerhugowaard | EU | DCENT |
| `f0198****` | Dallas | USA | GREATERHEAT |
| `f0188****` | Singapore | AS | GREATERHEAT |
| `f01091851` | Omaha | USA | DLTx |
| `f01736668` | Omaha | USA | DLTx |
| `f01820744` | Omaha | USA | DLTx |
| `f0855584` | Omaha | USA | DLTx |
| `f01794610` | Omaha | USA | DLTx |
| `f01838599` | Kansas City | USA | DLTx |
| `f01845552` | Kansas City | USA | DLTx |
| `f01885088` | Hong Kong | AS | Hong Kong Morpho Technology Limited |
| `f01926635` | Hong Kong | AS | Hong Kong Morpho Technology Limited |
| `f01933917` | Hong Kong | AS | Hong Kong Morpho Technology Limited |
| `f01989888` | Hong Kong | AS | Hong Kong Morpho Technology Limited |

### How do you plan to make deals to your storage providers

Boost client, Lotus client, Singularity

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by cryptowhizzard** [comment]
(Proposal #1516 is broken this is a re-apply of that request)

**Comment by simonkim0515** [comment]
## Datacap Request Trigger

#### Total DataCap requested 
> 5PiB

#### Expected weekly DataCap usage rate 
> 500TiB 

#### Client address
> f1klrehuwhzfw6boiiywdi7pikztsob4kkieivcwq

**Comment by herrehesse** [comment]
Kindly requesting the assistance of a Notary in signing the next tranche of the datacap. @kernelogic @s0nik42 @steven004 @GaryGJG @mjroddy @xinaxu @xingjitansuo

(previous allocation can be found here including the CID report: #485 )

**Comment by kernelogic** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceblrm4zm6nhpdforbfipux4aabmgixclhagziwnu2ybt7dtnxgysk 
#### Address 
> f1klrehuwhzfw6boiiywdi7pikztsob4kkieivcwq
#### Datacap Allocated
> 250.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceblrm4zm6nhpdforbfipux4aabmgixclhagziwnu2ybt7dtnxgysk

**Comment by xingjitansuo** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebfookq5rkcar4jysgvp3urlpg7tlpu3v2eaz54kz5ksprwqm22zm 
#### Address 
> f1klrehuwhzfw6boiiywdi7pikztsob4kkieivcwq
#### Datacap Allocated
> 250.00TiB
#### Signer Address
> f1a2lia2cwwekeubwo4nppt4v4vebxs2frozarz3q
#### Id
> 1658b1f4-3f3f-4567-9598-b89f1dbe1cd4
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebfookq5rkcar4jysgvp3urlpg7tlpu3v2eaz54kz5ksprwqm22zm

**Comment by psh0691** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecto5263hbf4z5ihz4yukp4vwdeodwyoi4fsigiyapdnzq2rpw5qw 
#### Address 
> f1klrehuwhzfw6boiiywdi7pikztsob4kkieivcwq
#### Datacap Allocated
> 250.00TiB
#### Signer Address
> f1qdko4jg25vo35qmyvcrw4ak4fmuu3f5rif2kc7i
#### Id
> 1658b1f4-3f3f-4567-9598-b89f1dbe1cd4
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecto5263hbf4z5ihz4yukp4vwdeodwyoi4fsigiyapdnzq2rpw5qw

**Comment by psh0691** [comment]
DC is not assigned, so it has been signed again.

**Comment by s0nik42** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced7qevy5tov2ymcaxbvtga4mx7q6brzruotepcjd73xt2o6p4vlye 
#### Address 
> f1klrehuwhzfw6boiiywdi7pikztsob4kkieivcwq
#### Datacap Allocated
> 250.00TiB
#### Signer Address
> f1wxhnytjmklj2czezaqcfl7eb4nkgmaxysnegwii
#### Id
> 1658b1f4-3f3f-4567-9598-b89f1dbe1cd4
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced7qevy5tov2ymcaxbvtga4mx7q6brzruotepcjd73xt2o6p4vlye

**Comment by galen-mcandrew** [comment]
Trying to understand the evidence that the previous allocation didn't go through. @psh0691 can you explain why a new proposal was made?

I suspect any problems being encountered here have to do with reusing the client address. The SA bot looks at remaining DataCap and then determines when it is ready to launch the subsequent allocation request. If multiple applications are pointing to the same client address, the bot will not know when it's ready for more DataCap, and will get confused about where to make a new allocation request.

**Comment by galen-mcandrew** [comment]
Message 22zm landed 2023-01-30, and shows as 250TiB on interplanetary at height 2558834 - https://filfox.info/en/message/bafy2bzacebfookq5rkcar4jysgvp3urlpg7tlpu3v2eaz54kz5ksprwqm22zm

Message vlye landed 2023-02-02, and shows 250TiB as well at height 2567404 - https://filfox.info/en/message/bafy2bzaced7qevy5tov2ymcaxbvtga4mx7q6brzruotepcjd73xt2o6p4vlye

https://filplus.d.interplanetary.one/clients?filter=f1klrehuwhzfw6boiiywdi7pikztsob4kkieivcwq

**Comment by galen-mcandrew** [comment]
On chain as of 2-2 9:30am pacific, client f1klrehuwhzfw6boiiywdi7pikztsob4kkieivcwq has 318TiB, which also seems to support two 250TiB allocations.

**Comment by Wednesdaysof** [comment]
CID sharing has been observed. 
Why did you sign it?
@xinaxu

**Comment by cryptowhizzard** [comment]
![Schermafbeelding 2023-02-07 om 09 27 58](https://user-images.githubusercontent.com/36404435/217191843-ed7cde07-6ade-43a3-a240-6a9894d16be6.png)

**Comment by Wednesdaysof** [comment]
The new account  does not affect the fact that this project has shared cid.

**Comment by cryptowhizzard** [comment]
CID sharing is our own application. Follow the hyperlink.

**Comment by mjroddy** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecwoujeiqiplve2hft4fx7gzincs2e4tkv6wopidmzmrs4av7g6s2 
#### Address 
> f1klrehuwhzfw6boiiywdi7pikztsob4kkieivcwq
#### Datacap Allocated
> 500.00TiB
#### Signer Address
> f1ystxl2ootvpirpa7ebgwl7vlhwkbx2r4zjxwe5i
#### Id
> 87c24778-9603-45e5-8842-6b453b88fc7a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecwoujeiqiplve2hft4fx7gzincs2e4tkv6wopidmzmrs4av7g6s2

**Comment by herrehesse** [comment]
@Wednesdaysof What are you doing here with a throwaway account?
This application is the example for 99% of the community:

- Valuable research data proposed by the PL team
- Reachable miners (9/10) 
- Retrievable sectors (fast 9/10)
- Distribution perfectly across continents
- Distribution perfectly across 8+ different companies (not 1 SP using VPN)
- All data is close to perfectly spread among SP's
- Full transparency on all businesses we cooperate with

Again, this is an example for everyone to use. Do not try and be a fool in here.

**Comment by Wednesdaysof** [comment]
lotus client retrieve --provider f02012223 baga6ea4seaqc7jkfypvhk3rl7mj6xs7ojeitnbeh3wzx2bbtnteftt3ur77sgpy test.file
ERROR: offer error: retrieval query offer errored: failed to fetch piece to retrieve from: getting pieces for cid baga6ea4seaqc7jkfypvhk3rl7mj6xs7ojeitnbeh3wzx2bbtnteftt3ur77sgpy: getting pieces containing block baga6ea4seaqc7jkfypvhk3rl7mj6xs7ojeitnbeh3wzx2bbtnteftt3ur77sgpy: failed to lookup index for mh 9220202fa545c3ea756e2bfb13ebcbee4911368487ddb37d04336cc859cf748fff233f, err: datastore: key not found

@mjroddy  @xinaxu Retrieval failure！

**Comment by herrehesse** [comment]
@Wednesdaysof My friend, you should download the BAFY not the BAGA. Try again :)

**Comment by Wednesdaysof** [comment]
![图片](https://user-images.githubusercontent.com/124664479/217223419-130b1d8a-1c3d-4fd5-80c5-c811becfc1d5.png)

Why are these two values the same?
Piece CID  &  Payload CID

lotus client retrieve --provider f02012223 --pieceCid baga6ea4seaqc7jkfypvhk3rl7mj6xs7ojeitnbeh3wzx2bbtnteftt3ur77sgpy baga6ea4seaqc7jkfypvhk3rl7mj6xs7ojeitnbeh3wzx2bbtnteftt3ur77sgpy test.file
ERROR: offer error: retrieval query offer errored: failed to fetch piece to retrieve from: getting pieces for cid baga6ea4seaqc7jkfypvhk3rl7mj6xs7ojeitnbeh3wzx2bbtnteftt3ur77sgpy: getting pieces containing block baga6ea4seaqc7jkfypvhk3rl7mj6xs7ojeitnbeh3wzx2bbtnteftt3ur77sgpy: failed to lookup index for mh 9220202fa545c3ea756e2bfb13ebcbee4911368487ddb37d04336cc859cf748fff233f, err: datastore: key not found

**Comment by herrehesse** [comment]
@Wednesdaysof  Thank you for showing us a failed retrieval. Tagging the corresponding SP below here for full transparency. Will update you below when the deal(s) from this SP are retrievable again.

@Igor Please check minerID f02012223

**Comment by fillove** [comment]
mark:

unable to retrieve

They shouldn't keep getting DC @raghavrmadya @simonkim0515 @Kevin-FF-USA

**Comment by cryptowhizzard** [comment]
> ![图片](https://user-images.githubusercontent.com/124664479/217223419-130b1d8a-1c3d-4fd5-80c5-c811becfc1d5.png)
> 
> Why are these two values the same? Piece CID & Payload CID
> 
> lotus client retrieve --provider f02012223 --pieceCid baga6ea4seaqc7jkfypvhk3rl7mj6xs7ojeitnbeh3wzx2bbtnteftt3ur77sgpy baga6ea4seaqc7jkfypvhk3rl7mj6xs7ojeitnbeh3wzx2bbtnteftt3ur77sgpy test.file ERROR: offer error: retrieval query offer errored: failed to fetch piece to retrieve from: getting pieces for cid baga6ea4seaqc7jkfypvhk3rl7mj6xs7ojeitnbeh3wzx2bbtnteftt3ur77sgpy: getting pieces containing block baga6ea4seaqc7jkfypvhk3rl7mj6xs7ojeitnbeh3wzx2bbtnteftt3ur77sgpy: failed to lookup index for mh 9220202fa545c3ea756e2bfb13ebcbee4911368487ddb37d04336cc859cf748fff233f, err: datastore: key not found

If you look to your picture you can see the deal starts at 17 februari 2023. It is still in the proces of sealing, reason why you can't retrieve it until the SP finishes his/her sealing task.

**Comment by mrworkdev** [comment]
Hello.
We are doing deals from 1000Gnomes_Dragen on f02012223 and f02012227 miners (1.19.0 Lotus + 1.5.1_rc5 Boost).
Currently expiriecing issues with retrievals. Fixing in progress. Report back when we will fix it completely.

**Comment by xingjitansuo** [comment]
checker:manualTrigger

**Comment by xingjitansuo** [comment]
![image](https://user-images.githubusercontent.com/72185104/218462002-4479b5e7-0f30-48eb-8fae-b48296f18522.png)

<img width="379" alt="截屏2023-02-13 下午8 42 56" src="https://user-images.githubusercontent.com/72185104/218462345-9b0c62f9-be69-4b24-adb0-f473e03e8544.png">

I tried to test the retrieval for deal 23987803 and it failed.  The payload CID does not seem right. Can you show me a right way to retrieve?

**Comment by lvschouwen** [comment]
@xingjitansuo 
The SPs and ourself are aware of this issue.
As you notice the Piece CID and Payload CID are the same.
This dataset was prepared with a old version of Singularity where it packed the files as such.

If the SP is running Boost (which they are) the deal becomes unretrievable because Boost is unable to locate it.

We are working on a bug report to submit to the Lotus and Boost teams to address this issue.

**Comment by psh0691** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedba52hhhux4ckhnis7w43t3zs4oxwee3i3gvfwrr3wo4pvkh4ols 
#### Address 
> f1klrehuwhzfw6boiiywdi7pikztsob4kkieivcwq
#### Datacap Allocated
> 1000.00TiB
#### Signer Address
> f1qdko4jg25vo35qmyvcrw4ak4fmuu3f5rif2kc7i
#### Id
> 01ede35c-f4df-4a0f-bfbc-cb47cf58c3ab
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedba52hhhux4ckhnis7w43t3zs4oxwee3i3gvfwrr3wo4pvkh4ols

**Comment by kernelogic** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecfhbnwn7g4ajehoj265zc6gvo7mmnacdkaegdfrcrtp5oyh33jvy 
#### Address 
> f1klrehuwhzfw6boiiywdi7pikztsob4kkieivcwq
#### Datacap Allocated
> 1000.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### Id
> 01ede35c-f4df-4a0f-bfbc-cb47cf58c3ab
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecfhbnwn7g4ajehoj265zc6gvo7mmnacdkaegdfrcrtp5oyh33jvy

**Comment by mjroddy** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaxn4ebypk3umdot6zu6zubzmahwi3czfleikqk7hz762uqtyvbqo 
#### Address 
> f1klrehuwhzfw6boiiywdi7pikztsob4kkieivcwq
#### Datacap Allocated
> 1000.00TiB
#### Signer Address
> f1ystxl2ootvpirpa7ebgwl7vlhwkbx2r4zjxwe5i
#### Id
> 01ede35c-f4df-4a0f-bfbc-cb47cf58c3ab
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaxn4ebypk3umdot6zu6zubzmahwi3czfleikqk7hz762uqtyvbqo

**Comment by liyunzhi-666** [comment]
checker:manualTrigger

**Comment by liyunzhi-666** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecuanlgdkgxknausu2jrg2jrxaatgyuszjxtx47wesslyw7hdo3pg 
#### Address 
> f1klrehuwhzfw6boiiywdi7pikztsob4kkieivcwq
#### Datacap Allocated
> 1000.00TiB
#### Signer Address
> f1pszcrsciyixyuxxukkvtazcokexbn54amf7gvoq
#### Id
> 01ede35c-f4df-4a0f-bfbc-cb47cf58c3ab
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecuanlgdkgxknausu2jrg2jrxaatgyuszjxtx47wesslyw7hdo3pg

**Comment by simonkim0515** [comment]
## DataCap Allocation requested

#### Multisig Notary address
> f02049625

#### Client address
> f1klrehuwhzfw6boiiywdi7pikztsob4kkieivcwq

#### DataCap allocation requested
> 2000TiB

#### Id
> dac4fe66-d84e-454c-9d45-232ae75730fo

**Comment by liyunzhi-666** [comment]
checker:manualTrigger

**Comment by Fatman13** [comment]
checker:manualTrigger

**Comment by Fatman13** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaurhmrqv7w6c4dt2zn6sxfk4odoxu6sgq7gjr4rnuxvpsigy5al6 
#### Address 
> f1klrehuwhzfw6boiiywdi7pikztsob4kkieivcwq
#### Datacap Allocated
> 1.95PiB
#### Signer Address
> f1j3u7crhjzwb2cj5mq7vodlt4o66yoyci7lhcauy
#### Id
> dac4fe66-d84e-454c-9d45-232ae75730fo
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaurhmrqv7w6c4dt2zn6sxfk4odoxu6sgq7gjr4rnuxvpsigy5al6

**Comment by Fatman13** [comment]
Reached out by the client on Slack. CIDcheker looks good.

**Comment by liyunzhi-666** [comment]
I did a random retrieval https://filecoin.tools/f01981059
![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/52949274/fabb5a3e-e892-4445-8b00-9aff5221a7cc)
About CID sharing, @herrehesse  has explained to me in slack. I will support this round.

**Comment by liyunzhi-666** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec35vjyqvgob42e36q5iizk7fkn7nliuxv54sbv74kjbp2eblpch2 
#### Address 
> f1klrehuwhzfw6boiiywdi7pikztsob4kkieivcwq
#### Datacap Allocated
> 1.95PiB
#### Signer Address
> f1pszcrsciyixyuxxukkvtazcokexbn54amf7gvoq
#### Id
> dac4fe66-d84e-454c-9d45-232ae75730fo
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec35vjyqvgob42e36q5iizk7fkn7nliuxv54sbv74kjbp2eblpch2

**Comment by herrehesse** [comment]
![Screenshot 2023-05-31 at 10 06 09](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/70132857/8851808b-ecd4-47b5-8d38-7b2d7709af7e)

Might the Faucet be empty @Fatman13 @liyunzhi-666 ?

**Comment by simonkim0515** [comment]
## DataCap Allocation requested

#### Multisig Notary address
> f02049625

#### Client address
> f1klrehuwhzfw6boiiywdi7pikztsob4kkieivcwq

#### DataCap allocation requested
> 1950TiB

#### Id
> dac4fe66-d84e-454c-9d45-232ae75730fq

**Comment by s0nik42** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebjt23ccgbofztbsql3milpbtljrsvan66kb4o7cw3onqk3grlbae 
#### Address 
> f1klrehuwhzfw6boiiywdi7pikztsob4kkieivcwq
#### Datacap Allocated
> 1.90PiB
#### Signer Address
> f1wxhnytjmklj2czezaqcfl7eb4nkgmaxysnegwii
#### Id
> dac4fe66-d84e-454c-9d45-232ae75730fq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebjt23ccgbofztbsql3milpbtljrsvan66kb4o7cw3onqk3grlbae

**Comment by mjroddy** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecmlcgu6xhlpzsrfimtjftkacote2jfxx7pb2l3ppvgixwiwonciq 
#### Address 
> f1klrehuwhzfw6boiiywdi7pikztsob4kkieivcwq
#### Datacap Allocated
> 1.90PiB
#### Signer Address
> f1ystxl2ootvpirpa7ebgwl7vlhwkbx2r4zjxwe5i
#### Id
> dac4fe66-d84e-454c-9d45-232ae75730fq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecmlcgu6xhlpzsrfimtjftkacote2jfxx7pb2l3ppvgixwiwonciq

**Comment by fdate11** [comment]
checker:manualTrigger

**Comment by liyunzhi-666** [comment]
checker:manualTrigger

**Comment by liyunzhi-666** [comment]
Why is the success rate for all searches below 1%?

**Comment by cryptowhizzard** [comment]
@liyunzhi-666 I've contacted the retrieval bot team directly last week and hope to have a call with them soon. All our miners currently have the following settings:

RETRIEVAL DEALS PER HOUR: 5000
MAX BANDWIDTH: 100Mbps
Accept storage deals from unknown clients: YES
SIMULTANEOUS RETRIEVALS: 5
SIMULTANEOUS REQUESTS PER PEER ID: 5

HTTP Retrieval enabled: No Limits (currently)
BITSWAP Retrieval enabled: (Limits above)
GRAPHSYNC Retrieval enabled: (Limits above)

**We still reach a 0% retrievability. Which is odd.**

We need to determine whether the problems lie within our systems or need to be resolved on your end. We should also draft a "recommended settings" doc for storage providers in need of assistance with retrievals. Urgent action is required to rectify the situation promptly. @simonkim0515 @dkkapur @raghavrmadya

**Comment by liyunzhi-666** [comment]
Before solving these disputes and the success rate of retrieval, I suggest to suspend this application and contact SP to solve the problem first.

**Comment by BlockMakeronline** [comment]
checker:manualTrigger

**Comment by data-programs** [comment]
<img width="32" alt="KYC" Verified src="https://stable.filplus.storage/images/filplus-kyc-verified-badge.png"/>

This user’s identity has been verified through [filplus.storage](https://filplus.storage)
