### ISSUE TITLE
[DataCap Application] Speedium - Distributed Archives Neurophysiology Data Integration (DANDI) [2 / 3]

### ISSUE THREAD

**Issue by cryptowhizzard** [filecoin-project/filecoin-plus-large-datasets#1550]
### Data Owner Name

Massachusetts Institute Of Technology

### Data Owner Country/Region

United States

### Data Owner Industry

Life Science / Healthcare

### Website

https://www.dandiarchive.org/

### Social Media

```text
https://github.com/dandi
https://twitter.com/dandiarchive
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

500TiB

### On-chain address for first allocation

f1xlnnzzl2d73amahvsu5uyfwdascodwtw6lopw5y

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Since its launch, the Filecoin network has become an important player in the decentralised storage space, offering a secure and transparent alternative to traditional data storage solutions.

We as Speedium / DCENT have been engaged with storing real and valuable datasets on the Filecoin network since Slingshot 2.6 and have been actively developing tools to improve the process. We are always on the lookout for new and useful client data to onboard.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
DANDI is a public archive of neurophysiology datasets, including raw and processed data, and associated software containers. Datasets are shared according to a Creative Commons CC0 or CC-BY licenses. The data archive provides a broad range of cellular neurophysiology data. This includes electrode and optical recordings, and associated imaging data using a set of community standards: NWB:N - NWB:Neurophysiology, BIDS - Brain Imaging Data Structure, and NIDM - Neuro Imaging Data Model.
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### How do you plan to prepare the dataset

IPFS, lotus, singularity, graphsplit

### Please share a sample of the data

```text
https://registry.opendata.aws/dandiarchive/
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

1.5 to 2 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, South America, Europe, Australia (continent)

### How will you be distributing your data to storage providers

HTTP or FTP server, IPFS, Shipping hard drives, Lotus built-in data transfer

### How do you plan to choose storage providers

Slack, Big data exchange, Partners

### If you already have a list of storage providers to work with, fill out their names and provider IDs below

| MinerID | City | Continent | Business/Entity |
| --- | --- | --- | --- |
| `f01944347` | Oregon | USA | Jenny, Dabai |
| `f01952350` | Oregon | USA | Jenny, Dabai |
| `f01972364` | Oregon | USA | Jenny, Dabai |
| `f01972376` | Oregon | USA | Jenny, Dabai |
| `f02000937` | Chengdu | CN | MTY |
| `f01915033` | Chengdu | CN | MTY |
| `f01901765` | Hangzhou | CN | MTY |
| `f01953985` | Shenzhen | CN | MTY |
| `f0120****` | Melbourne | AU | HOLON |
| `f0115****` | Melbourne | AU | HOLON |
| `f01199430` | Heerhugowaard | EU | DCENT |
| `f01786387` | Heerhugowaard | EU | DCENT |
| `f01201327` | Heerhugowaard | EU | DCENT |
| `f01937642` | Heerhugowaard | EU | DCENT |
| `f0198****` | Dallas | USA | GREATERHEAT |
| `f0188****` | Singapore | AS | GREATERHEAT |
| `f01091851` | Omaha | USA | DLTx |
| `f01736668` | Omaha | USA | DLTx |
| `f01820744` | Omaha | USA | DLTx |
| `f0855584` | Omaha | USA | DLTx |
| `f01794610` | Omaha | USA | DLTx |
| `f01838599` | Kansas City | USA | DLTx |
| `f01845552` | Kansas City | USA | DLTx |
| `f01885088` | Hong Kong | AS | Hong Kong Morpho Technology Limited |
| `f01926635` | Hong Kong | AS | Hong Kong Morpho Technology Limited |
| `f01933917` | Hong Kong | AS | Hong Kong Morpho Technology Limited |
| `f01989888` | Hong Kong | AS | Hong Kong Morpho Technology Limited |

### How do you plan to make deals to your storage providers

Boost client, Lotus client, Singularity

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by cryptowhizzard** [comment]
(Proposal https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1515 is broken this is a re-apply of that request)

**Comment by simonkim0515** [comment]
## Datacap Request Trigger

#### Total DataCap requested 
> 5PiB

#### Expected weekly DataCap usage rate 
> 500TiB 

#### Client address
> f1xlnnzzl2d73amahvsu5uyfwdascodwtw6lopw5y

**Comment by psh0691** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced5epxnhr32iv4gwnmuzofm4npemtwxajrw7vhn7n5wbxophxuux4 
#### Address 
> f1xlnnzzl2d73amahvsu5uyfwdascodwtw6lopw5y
#### Datacap Allocated
> 250.00TiB
#### Signer Address
> f1qdko4jg25vo35qmyvcrw4ak4fmuu3f5rif2kc7i
#### Id
> 3aa4ed69-6283-4994-9a0c-0479b37b2165
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced5epxnhr32iv4gwnmuzofm4npemtwxajrw7vhn7n5wbxophxuux4

**Comment by s0nik42** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacea7qzawlemr5vompuwtimpykwabjwnv65q5ve4t4hghe6fcn57t7w 
#### Address 
> f1xlnnzzl2d73amahvsu5uyfwdascodwtw6lopw5y
#### Datacap Allocated
> 250.00TiB
#### Signer Address
> f1wxhnytjmklj2czezaqcfl7eb4nkgmaxysnegwii
#### Id
> 3aa4ed69-6283-4994-9a0c-0479b37b2165
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacea7qzawlemr5vompuwtimpykwabjwnv65q5ve4t4hghe6fcn57t7w

**Comment by filplusapp** [comment]
checker:manualTrigger

**Comment by filplusapp** [comment]
![image](https://user-images.githubusercontent.com/124670203/217228701-90da6775-df5e-4362-bf91-1ad6dff68b83.png)

**Comment by cryptowhizzard** [comment]
> ![image](https://user-images.githubusercontent.com/124670203/217228701-90da6775-df5e-4362-bf91-1ad6dff68b83.png)

This one is correct. I will contact this SP and get this fixed.

**Comment by psh0691** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb5qtfmjnkj5pnytqz72ymxdpvwtmd4lnwdkxv2xywm34tmwa25hk 
#### Address 
> f1xlnnzzl2d73amahvsu5uyfwdascodwtw6lopw5y
#### Datacap Allocated
> 1000.00TiB
#### Signer Address
> f1qdko4jg25vo35qmyvcrw4ak4fmuu3f5rif2kc7i
#### Id
> 25d1635d-fec4-4097-9ead-eb2d27b31fee
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb5qtfmjnkj5pnytqz72ymxdpvwtmd4lnwdkxv2xywm34tmwa25hk

**Comment by mjroddy** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceclfhcrb5kjlyijwgwzexx4w7yq3dioqwb2ugrlgaz6ozlmllxf4o 
#### Address 
> f1xlnnzzl2d73amahvsu5uyfwdascodwtw6lopw5y
#### Datacap Allocated
> 1000.00TiB
#### Signer Address
> f1ystxl2ootvpirpa7ebgwl7vlhwkbx2r4zjxwe5i
#### Id
> 25d1635d-fec4-4097-9ead-eb2d27b31fee
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceclfhcrb5kjlyijwgwzexx4w7yq3dioqwb2ugrlgaz6ozlmllxf4o

**Comment by kernelogic** [comment]
Distribution looks health.

**Comment by kernelogic** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecxejxzojebce3opaxfdsl6atwmq26rpoplasmvz5opmbtcve4poy 
#### Address 
> f1xlnnzzl2d73amahvsu5uyfwdascodwtw6lopw5y
#### Datacap Allocated
> 1.95PiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### Id
> 99ad4d1d-f2b6-4347-aea7-7bd97d03b1db
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecxejxzojebce3opaxfdsl6atwmq26rpoplasmvz5opmbtcve4poy

**Comment by flyworker** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceckkj4jmocpiup3lowu57crqfodrus7jo6ljdhjbutt42rx5wzz76 
#### Address 
> f1xlnnzzl2d73amahvsu5uyfwdascodwtw6lopw5y
#### Datacap Allocated
> 1.95PiB
#### Signer Address
> f1hlubjsdkv4wmsdadihloxgwrz3j3ernf6i3cbpy
#### Id
> 99ad4d1d-f2b6-4347-aea7-7bd97d03b1db
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceckkj4jmocpiup3lowu57crqfodrus7jo6ljdhjbutt42rx5wzz76

**Comment by kernelogic** [comment]
Seems the SSA bot requested another top up right away after the previous one approved.

**Comment by data-programs** [comment]
<img width="32" alt="KYC" Verified src="https://stable.filplus.storage/images/filplus-kyc-verified-badge.png"/>

This user’s identity has been verified through [filplus.storage](https://filplus.storage)
