### ISSUE TITLE
[DataCap Application] Speedium - Next Generation Weather Radar (NEXRAD V2) [Part 2/5]

### ISSUE THREAD

**Issue by cryptowhizzard** [filecoin-project/filecoin-plus-large-datasets#1552]
### Data Owner Name

National Weather Service (NWS)

### Data Owner Country/Region

United States

### Data Owner Industry

Environment

### Website

https://www.ncei.noaa.gov/products/radar/next-generation-weather-radar

### Social Media

```text
https://www.facebook.com/NEXRADROC/
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

500TiB

### On-chain address for first allocation

f1xafi3wsh7q553efnumhgeomathrehwwd2mye7oy

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Since its launch, the Filecoin network has become an important player in the decentralised storage space, offering a secure and transparent alternative to traditional data storage solutions.

We as Speedium / DCENT have been engaged with storing real and valuable datasets on the Filecoin network since Slingshot 2.6 and have been actively developing tools to improve the process. We are always on the lookout for new and useful client data to onboard.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
The [Next Generation Weather Radar](https://www.ncdc.noaa.gov/data-access/radar-data/nexrad) (NEXRAD) is a network of 160 high-resolution Doppler radar sites that detects precipitation and atmospheric movement and disseminates data in approximately 5 minute intervals from each site.
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### How do you plan to prepare the dataset

IPFS, lotus, singularity, graphsplit

### Please share a sample of the data

```text
https://www.ncei.noaa.gov/products/radar-data/nexrad
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

1.5 to 2 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, South America, Europe, Australia (continent)

### How will you be distributing your data to storage providers

HTTP or FTP server, IPFS, Shipping hard drives, Lotus built-in data transfer

### How do you plan to choose storage providers

Slack, Big data exchange, Partners

### If you already have a list of storage providers to work with, fill out their names and provider IDs below

| MinerID | City | Continent | Business/Entity |
| --- | --- | --- | --- |
| `f01944347` | Oregon | USA | Jenny, Dabai |
| `f01952350` | Oregon | USA | Jenny, Dabai |
| `f01972364` | Oregon | USA | Jenny, Dabai |
| `f01972376` | Oregon | USA | Jenny, Dabai |
| `f0120****` | Melbourne | AU | HOLON |
| `f0115****` | Melbourne | AU | HOLON |
| `f01199430` | Heerhugowaard | EU | DCENT |
| `f01786387` | Heerhugowaard | EU | DCENT |
| `f01201327` | Heerhugowaard | EU | DCENT |
| `f01937642` | Heerhugowaard | EU | DCENT |
| `f0198****` | Dallas | USA | GREATERHEAT |
| `f0188****` | Singapore | AS | GREATERHEAT |
| `f01091851` | Omaha | USA | DLTx |
| `f01736668` | Omaha | USA | DLTx |
| `f01820744` | Omaha | USA | DLTx |
| `f0855584` | Omaha | USA | DLTx |
| `f01794610` | Omaha | USA | DLTx |
| `f01838599` | Kansas City | USA | DLTx |
| `f01845552` | Kansas City | USA | DLTx |

### How do you plan to make deals to your storage providers

Boost client, Lotus client, Singularity

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by cryptowhizzard** [comment]
(Proposal https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1513 is broken this is a re-apply of that request)

**Comment by simonkim0515** [comment]
## Datacap Request Trigger

#### Total DataCap requested 
> 5PiB

#### Expected weekly DataCap usage rate 
> 500TiB 

#### Client address
> f1xafi3wsh7q553efnumhgeomathrehwwd2mye7oy

**Comment by mjroddy** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedxd2pagnjsgcgt3cbi4pznc5eatnqxjrd6ittd4w74eq42khf7vu 
#### Address 
> f1xafi3wsh7q553efnumhgeomathrehwwd2mye7oy
#### Datacap Allocated
> 2.00PiB
#### Signer Address
> f1ystxl2ootvpirpa7ebgwl7vlhwkbx2r4zjxwe5i
#### Id
> 94bbc852-85c5-47e6-bfb5-07c6b29528a5
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedxd2pagnjsgcgt3cbi4pznc5eatnqxjrd6ittd4w74eq42khf7vu

**Comment by cryptowhizzard** [comment]
@001can

Stop gaslighting. https://filecoinproject.slack.com/archives/C01DLAPKDGX/p1673518708336059

**Comment by filplusapp** [comment]
lotus client retrieve --provider f01967501 --pieceCid baga6ea4seaqbfovm7x6k62orbgfv2nwfbndlsveetyozky23hfuxhgpqjznnyey uAYHiA5IgIBK6rP38r2nRCYtdNsULRrlUhJ4dlWNbOWlzmfBOWtwT test.file
ERROR: offer error: retrieval query offer errored: failed to fetch piece to retrieve from: getting pieces for cid baga6ea4seaqbfovm7x6k62orbgfv2nwfbndlsveetyozky23hfuxhgpqjznnyey: getting pieces containing block baga6ea4seaqbfovm7x6k62orbgfv2nwfbndlsveetyozky23hfuxhgpqjznnyey: failed to lookup index for mh 92202012baacfdfcaf69d1098b5d36c50b46b954849e1d95635b39697399f04e5adc13, err: datastore: key not found

**Comment by flyworker** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec54b44u2ou2biz7hgklxlcgqapugujkzxxc5qpvdoyvdb2ljqe7i 
#### Address 
> f1xafi3wsh7q553efnumhgeomathrehwwd2mye7oy
#### Datacap Allocated
> 1000.00TiB
#### Signer Address
> f1hlubjsdkv4wmsdadihloxgwrz3j3ernf6i3cbpy
#### Id
> c9fedff8-e143-47a4-aba1-b1b49bbb1b31
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec54b44u2ou2biz7hgklxlcgqapugujkzxxc5qpvdoyvdb2ljqe7i

**Comment by psh0691** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecpy3f52konagn2aevtmputt4fm3oso5objuehiabpfwb3xwzgy5w 
#### Address 
> f1xafi3wsh7q553efnumhgeomathrehwwd2mye7oy
#### Datacap Allocated
> 1000.00TiB
#### Signer Address
> f1qdko4jg25vo35qmyvcrw4ak4fmuu3f5rif2kc7i
#### Id
> c9fedff8-e143-47a4-aba1-b1b49bbb1b31
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecpy3f52konagn2aevtmputt4fm3oso5objuehiabpfwb3xwzgy5w

**Comment by s0nik42** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecrofjdyihenjfls6fxpozjnaz7s6wjhwxmd7ci3sahj7mqlg5um4 
#### Address 
> f1xafi3wsh7q553efnumhgeomathrehwwd2mye7oy
#### Datacap Allocated
> 1.95PiB
#### Signer Address
> f1wxhnytjmklj2czezaqcfl7eb4nkgmaxysnegwii
#### Id
> 0771cb69-ef42-42e5-989a-54e813018179
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecrofjdyihenjfls6fxpozjnaz7s6wjhwxmd7ci3sahj7mqlg5um4

**Comment by NDLABS-OFFICE** [comment]
7 storage providers sealed too much duplicate data - [f01208803](https://filfox.info/en/address/f01208803): 26.75%, [f01157271](https://filfox.info/en/address/f01157271): 28.09%, [f01208154](https://filfox.info/en/address/f01208154): 24.14%, [f01208632](https://filfox.info/en/address/f01208632): 27.18%, [f01208189](https://filfox.info/en/address/f01208189): 50.24%, [f01156835](https://filfox.info/en/address/f01156835): 24.42%, [f01208042](https://filfox.info/en/address/f01208042): 34.04%

[f01208189](https://filfox.info/en/address/f01208189): 50.24%
this ratio is too high,I want to know what causes.

**Comment by herrehesse** [comment]
@NDLABS-OFFICE there was a bug in our API with HOLON. We found this bug when the first CID checker was released, fixed it, and it never happens again since.

You can see this on the previous application. Explained with the timeline added.

**Comment by NDLABS-OFFICE** [comment]
checker:manualTrigger

**Comment by NDLABS-OFFICE** [comment]
@herrehesse It's acceptable to have a technical issue, we'd like to support it and hope to see it fixed. If this problem persists we will no longer support. Hope community members are more inclusive.

**Comment by NDLABS-OFFICE** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaxlminjjuvaxz64sqmzfp4abzhswt4bys23ayn5d3t5ygemggqa2 
#### Address 
> f1xafi3wsh7q553efnumhgeomathrehwwd2mye7oy
#### Datacap Allocated
> 1.34PiB
#### Signer Address
> f1yayfsv6whu3rheviucvventj3y6t542xfpb47ei
#### Id
> 4d3f2901-7a2d-42eb-b001-56b805185a09
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaxlminjjuvaxz64sqmzfp4abzhswt4bys23ayn5d3t5ygemggqa2

**Comment by xingjitansuo** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceceocuz35wjaa5zwc7zjfnc32fik446spwebccrovvat6hchodmkw 
#### Address 
> f1xafi3wsh7q553efnumhgeomathrehwwd2mye7oy
#### Datacap Allocated
> 1.34PiB
#### Signer Address
> f1a2lia2cwwekeubwo4nppt4v4vebxs2frozarz3q
#### Id
> 4d3f2901-7a2d-42eb-b001-56b805185a09
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceceocuz35wjaa5zwc7zjfnc32fik446spwebccrovvat6hchodmkw

**Comment by C00kies77** [comment]
checker:manualTrigger

**Comment by data-programs** [comment]
<img width="32" alt="KYC" Verified src="https://stable.filplus.storage/images/filplus-kyc-verified-badge.png"/>

This user’s identity has been verified through [filplus.storage](https://filplus.storage)
