### ISSUE TITLE
Speedium | Dcent - Galaxy Evolution Explorer Satellite dataset - Part 3/3

### ISSUE THREAD

**Issue by cryptowhizzard** [filecoin-project/filecoin-plus-large-datasets#1555]
### Data Owner Name

NASA

### Data Owner Country/Region

United States

### Data Owner Industry

Environment

### Website

https://www.jpl.nasa.gov/missions/galaxy-evolution-explorer-galex

### Social Media

```text
https://www.jpl.nasa.gov/missions/galaxy-evolution-explorer-galex
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

500TiB

### On-chain address for first allocation

f1kyaa43uqypbcsv5isyd4xw7lvgjcumfzqsxag7y

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Since its launch, the Filecoin network has become an important player in the decentralised storage space, offering a secure and transparent alternative to traditional data storage solutions.

We as Speedium / DCENT have been engaged with storing real and valuable datasets on the Filecoin network since Slingshot 2.6 and have been actively developing tools to improve the process. We are always on the lookout for new and useful client data to onboard.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
The Galaxy Evolution Explorer Satellite (GALEX) was a NASA mission led by the California Institute of Technology, whose primary goal was to investigates how star formation in galaxies evolved from the early Universe up to the present. GALEX used microchannel plate detectors to obtain direct images in the near-UV (NUV) and far-UV (FUV), and a grism to disperse light for low resolution spectroscopy. More information about GALEX is available at MAST

This project is a followup of #487. 487 has been granted 4 PB of datacap but given that we need around 800 TiB of datacap per replica we are at 50%.
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### How do you plan to prepare the dataset

IPFS, lotus, singularity, graphsplit

### Please share a sample of the data

```text
https://www.jpl.nasa.gov/missions/galaxy-evolution-explorer-galex
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

1.5 to 2 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, South America, Europe, Australia (continent)

### How will you be distributing your data to storage providers

HTTP or FTP server, IPFS, Shipping hard drives, Lotus built-in data transfer

### How do you plan to choose storage providers

Slack, Big data exchange, Partners

### If you already have a list of storage providers to work with, fill out their names and provider IDs below

| MinerID | City | Continent | Business/Entity |
| --- | --- | --- | --- |
| `f01944347` | Oregon | USA | Jenny, Dabai |
| `f01952350` | Oregon | USA | Jenny, Dabai |
| `f01972364` | Oregon | USA | Jenny, Dabai |
| `f01972376` | Oregon | USA | Jenny, Dabai |
| `f02000937` | Chengdu | CN | MTY |
| `f01915033` | Chengdu | CN | MTY |
| `f01901765` | Hangzhou | CN | MTY |
| `f01953985` | Shenzhen | CN | MTY |
| `f0120****` | Melbourne | AU | HOLON |
| `f0115****` | Melbourne | AU | HOLON |
| `f01199430` | Heerhugowaard | EU | DCENT |
| `f01786387` | Heerhugowaard | EU | DCENT |
| `f01201327` | Heerhugowaard | EU | DCENT |
| `f01937642` | Heerhugowaard | EU | DCENT |
| `f0198****` | Dallas | USA | GREATERHEAT |
| `f0188****` | Singapore | AS | GREATERHEAT |
| `f01091851` | Omaha | USA | DLTx |
| `f01736668` | Omaha | USA | DLTx |
| `f01820744` | Omaha | USA | DLTx |
| `f0855584` | Omaha | USA | DLTx |
| `f01794610` | Omaha | USA | DLTx |
| `f01838599` | Kansas City | USA | DLTx |
| `f01845552` | Kansas City | USA | DLTx |
| `f01885088` | Hong Kong | AS | Hong Kong Morpho Technology Limited |
| `f01926635` | Hong Kong | AS | Hong Kong Morpho Technology Limited |
| `f01933917` | Hong Kong | AS | Hong Kong Morpho Technology Limited |
| `f01989888` | Hong Kong | AS | Hong Kong Morpho Technology Limited |

### How do you plan to make deals to your storage providers

Boost client, Lotus client, Singularity

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by simonkim0515** [comment]
## Datacap Request Trigger

#### Total DataCap requested 
> 5PiB

#### Expected weekly DataCap usage rate 
> 500TiB 

#### Client address
> f1kyaa43uqypbcsv5isyd4xw7lvgjcumfzqsxag7y

**Comment by mjroddy** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec5vdqxhm7d5nyngjqcy3iyudms25y5ekm7e2gvjkcjjog3p4dwqg 
#### Address 
> f1kyaa43uqypbcsv5isyd4xw7lvgjcumfzqsxag7y
#### Datacap Allocated
> 250.00TiB
#### Signer Address
> f1ystxl2ootvpirpa7ebgwl7vlhwkbx2r4zjxwe5i
#### Id
> e29f9f49-300c-480e-a37d-5d7d325cbfa2
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec5vdqxhm7d5nyngjqcy3iyudms25y5ekm7e2gvjkcjjog3p4dwqg

**Comment by kernelogic** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedir4wepesekcm726k5ex6sdurnmycs6kfkoivpe32eo6zt3s3aua 
#### Address 
> f1kyaa43uqypbcsv5isyd4xw7lvgjcumfzqsxag7y
#### Datacap Allocated
> 250.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### Id
> e29f9f49-300c-480e-a37d-5d7d325cbfa2
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedir4wepesekcm726k5ex6sdurnmycs6kfkoivpe32eo6zt3s3aua

**Comment by mjroddy** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb2b3dnsa5m7aagr2dgtw64qwia27cg3iiazua7rdni7ky2olrmt2 
#### Address 
> f1kyaa43uqypbcsv5isyd4xw7lvgjcumfzqsxag7y
#### Datacap Allocated
> 500.00TiB
#### Signer Address
> f1ystxl2ootvpirpa7ebgwl7vlhwkbx2r4zjxwe5i
#### Id
> 4dae2fb2-ee7e-4a07-a78d-089338bb7844
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb2b3dnsa5m7aagr2dgtw64qwia27cg3iiazua7rdni7ky2olrmt2

**Comment by xingjitansuo** [comment]
Greeting!  The geographic distribution of Data looks good to me. Can you share your plan on the number of duplicates and the size in Datacap of a single copy?

**Comment by herrehesse** [comment]
Hello @xingjitansuo ! Thank you for your question.

Initially we have stored a bunch of CID duplicates due to bugs in singularity (#487). This has now been resolved by PL and our database has been purged of any duplicate CID records. 

The plan is to distribute 10 to 12 full copies of the dataset, which comprises 500 TiB of carfiles. To store all of these files, approximately 900 TiB of datacap is needed per copy. 

The total datacap required for 12 copies is 10.8 PiB, with the third tranche serving as a backup for any errors or duplicates and for the possibility of an SP slashing sectors. It should be noted that any unused datacap will not be refunded to our wallet. Measures will be taken to ensure that all copies are stored on-chain and the datacap from the third tranche will be reclaimed upon completion if not used.

Let me know if I can answer some more questions! Here to help.

**Comment by kernelogic** [comment]
@herrehesse you can use `lotus filplus remove-expired-allocations` command to recover DC caused by expiration (slashed I'm not sure).

**Comment by kernelogic** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaqujljuzezaq5kjm7tw47tftpxkpfyir6txsnhb3xllchzoocrrc 
#### Address 
> f1kyaa43uqypbcsv5isyd4xw7lvgjcumfzqsxag7y
#### Datacap Allocated
> 1000.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### Id
> ed574fb9-8130-4fdf-83a5-8687e45b9595
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaqujljuzezaq5kjm7tw47tftpxkpfyir6txsnhb3xllchzoocrrc

**Comment by mjroddy** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacea3d4iybdstghk4vs6ttbppv3fckfaskz663nljjsw5c3f6pmnaka 
#### Address 
> f1kyaa43uqypbcsv5isyd4xw7lvgjcumfzqsxag7y
#### Datacap Allocated
> 1000.00TiB
#### Signer Address
> f1ystxl2ootvpirpa7ebgwl7vlhwkbx2r4zjxwe5i
#### Id
> ed574fb9-8130-4fdf-83a5-8687e45b9595
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacea3d4iybdstghk4vs6ttbppv3fckfaskz663nljjsw5c3f6pmnaka

**Comment by herrehesse** [comment]
Kindly requesting the assistance of a Notary in signing the next tranche of the datacap. @kernelogic @s0nik42 @steven004 @GaryGJG @mjroddy @xinaxu @xingjitansuo

**Comment by kernelogic** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedryv57boabih6pmz4tgcycqrr6o7vmririmmr4czgewzqngfob5u 
#### Address 
> f1kyaa43uqypbcsv5isyd4xw7lvgjcumfzqsxag7y
#### Datacap Allocated
> 1.95PiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedryv57boabih6pmz4tgcycqrr6o7vmririmmr4czgewzqngfob5u

**Comment by mjroddy** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced3yb3a7caodeyrhhybcnhag6bppp63uivoxf7cw3rxnymn4hvf3y 
#### Address 
> f1kyaa43uqypbcsv5isyd4xw7lvgjcumfzqsxag7y
#### Datacap Allocated
> 1.95PiB
#### Signer Address
> f1ystxl2ootvpirpa7ebgwl7vlhwkbx2r4zjxwe5i
#### Id
> 3bf7d37c-3877-4107-a6be-883d4c7f40df
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced3yb3a7caodeyrhhybcnhag6bppp63uivoxf7cw3rxnymn4hvf3y

**Comment by xingjitansuo** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedc4s7stelgdv4zin7jipr7tn7oanrmakdvjrxtu4codkogzsbhv2 
#### Address 
> f1kyaa43uqypbcsv5isyd4xw7lvgjcumfzqsxag7y
#### Datacap Allocated
> 1.34PiB
#### Signer Address
> f1a2lia2cwwekeubwo4nppt4v4vebxs2frozarz3q
#### Id
> 679a25cf-f96e-463d-b6a5-1c762000be62
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedc4s7stelgdv4zin7jipr7tn7oanrmakdvjrxtu4codkogzsbhv2

**Comment by kernelogic** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceavwkqw6xjmarsyn7dkbb6atofpqbxjkwksrsq3v2gsc3zap7utn2 
#### Address 
> f1kyaa43uqypbcsv5isyd4xw7lvgjcumfzqsxag7y
#### Datacap Allocated
> 1.34PiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### Id
> 679a25cf-f96e-463d-b6a5-1c762000be62
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceavwkqw6xjmarsyn7dkbb6atofpqbxjkwksrsq3v2gsc3zap7utn2

**Comment by chenfan76673** [comment]
checker:manualTrigger

**Comment by Wednesdaysof** [comment]
![图片](https://user-images.githubusercontent.com/124664479/217231545-de938803-3d99-416d-b366-036c8783b785.png)

![图片](https://user-images.githubusercontent.com/124664479/217232047-d6ea00bf-ef7f-40f2-8ad1-e4bc96f90b9e.png)

lotus client retrieve --provider f01989888 --pieceCid baga6ea4seaqk7hjam27qux6dnynxseyqidjzkp2iuirsi2bwvj6sfdt4s26mika baga6ea4seaqk7hjam27qux6dnynxseyqidjzkp2iuirsi2bwvj6sfdt4s26mika test.file
ERROR: offer error: retrieval query offer errored: failed to fetch piece to retrieve from: getting pieces for cid baga6ea4seaqk7hjam27qux6dnynxseyqidjzkp2iuirsi2bwvj6sfdt4s26mika: getting pieces containing block baga6ea4seaqk7hjam27qux6dnynxseyqidjzkp2iuirsi2bwvj6sfdt4s26mika: failed to lookup index for mh 922020af9d2066bf0a5fc36e1b79131040d3953f48a223246836aa7d228e7c96bcc428, err: datastore: key not found

**Comment by herrehesse** [comment]
@Wednesdaysof Thank you for showing us a failed retrieval. Tagging the corresponding SP below here for full transparency. Will update you below when the deal(s) from this SP are retrievable again.

@Feellin Please check minerID f01989888

**Comment by herrehesse** [comment]
@xinaxu should be in order now. Will ask @lvschouwen and @cryptowhizzard to double check on Monday morning and show you the results.

Enjoy your weekend.

**Comment by Joss-Hua** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedvkzpjcpoywrcxem5bw4gxdxezqdkcj4nc5us4tpteymzflmlss4 
#### Address 
> f1kyaa43uqypbcsv5isyd4xw7lvgjcumfzqsxag7y
#### Datacap Allocated
> 1.03TiB
#### Signer Address
> f1tfg54zzscugttejv336vivknmsnzzmyudp3t7wi
#### Id
> 0cc99c66-3fe2-49e5-8a29-f2cd0c4183d9
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedvkzpjcpoywrcxem5bw4gxdxezqdkcj4nc5us4tpteymzflmlss4

**Comment by psh0691** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecgtet2honrqucdhp7inabcl64dz3tbonaed7zfo7jrdyow5bmqxg 
#### Address 
> f1kyaa43uqypbcsv5isyd4xw7lvgjcumfzqsxag7y
#### Datacap Allocated
> 1.03TiB
#### Signer Address
> f1qdko4jg25vo35qmyvcrw4ak4fmuu3f5rif2kc7i
#### Id
> 0cc99c66-3fe2-49e5-8a29-f2cd0c4183d9
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecgtet2honrqucdhp7inabcl64dz3tbonaed7zfo7jrdyow5bmqxg

**Comment by data-programs** [comment]
<img width="32" alt="KYC" Verified src="https://stable.filplus.storage/images/filplus-kyc-verified-badge.png"/>

This user’s identity has been verified through [filplus.storage](https://filplus.storage)
