### ISSUE TITLE
[DataCap Application] <Swift Data> - <NFT chain data storage>

### ISSUE THREAD

**Issue by Garyweiou** [filecoin-project/filecoin-plus-large-datasets#1560]
### Data Owner Name

Swift Data

### Data Owner Country/Region

Singapore

### Data Owner Industry

Web3 / Crypto

### Website

http://nft.swiftnftmarket.io/

### Social Media

```text
twitter: @SwiftDataLab
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

500TiB

### On-chain address for first allocation

f1fmcgclzh7m7pmi3i7qgz3ujpsv5ml5uhhpjeogy

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Swift Data is committed to constructing infrastructure for web3 enterprise-grade data and AI. Swift AI zero-code service, Swift dashboard data visualization tool and big data warehouse based on databend are preliminarily built for the time being. By means of this platform, the developers and data analysts can access block chain data using SQL command. AI applications that are based on block chain data can be quickly built by adopting AI zero-code service. Based on this system, we have completed the data management and graphical display of the Flow chain and also finished the construction of Ethereum and polygon chain data warehouses.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
The dataset is mainly NFT-related on-chain data and pics/videos/texts obtained from social media or 3rd party website. Data is presented on our website and produced constantly, see more details directly from the website.
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### How do you plan to prepare the dataset

lotus

### Please share a sample of the data

```text
http://nft.swiftnftmarket.io/
http://assets.swiftnftmarket.io/
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Sporadic

### For how long do you plan to keep this dataset stored on Filecoin

2 to 3 years

### In which geographies do you plan on making storage deals

Greater China

### How will you be distributing your data to storage providers

Shipping hard drives

### How do you plan to choose storage providers

Partners

### If you already have a list of storage providers to work with, fill out their names and provider IDs below

```text
we don't have any for now.
```

### How do you plan to make deals to your storage providers

Boost client, Lotus client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
The website you shared is not available. Please check it.
Estimated domain age: 89 day(s)

**Comment by Garyweiou** [comment]
The website is accessible now, please try again. The website is down because new features are integrated. Thanks for your understanding.

**Comment by cryptowhizzard** [comment]
Can we receive some CID’s from the carfiles build for verification? 

You are referring to third party websites. Can you tell me which ones?

Are you applying for Swiftlab and is Swiftlab your company?

**Comment by Garyweiou** [comment]
> Can we receive some CID’s from the carfiles build for verification?
> Please check those CIDs below for verification:
bafykbzacecg3d7udidhmedsdowf3voshrrae3n4wobx3tff6vkxatzdywzf34
bafykbzacecioh37hxslhalrijrddlh3ujv4gnb2tsro5ldo3iki2ji2ul5w44
bafykbzaceashizoqf7m5hwx3gd3273i52wxyzz2o6b77er7jypbgpwemlbyby
bafykbzaceb5y5qzglavoqb63j4r57ajqpfwipe4xqietk4g5m2b4vt5fbpxlu
bafykbzaced4vnm7iac5frt7nqjbidu524k7ctsz7wqscfp7awe2a6e3e6q6xc
bafykbzacec3w2weiyhkqf77tpmemqpufguccphps33dkcawi4tz6ib5rb6xgi
bafykbzacedgxpzlqbjqlny5c67da2qiasafvw5i7g2ffbotiffm2vpz57qj3o
bafykbzacedxnkdoxu6qybb65oqzisryf7clpwap7lf22ixb7mfapocw3fozh2
bafykbzaceawrgqql52dzsbyq2h24w3z43to3xhj4yh7l3ojh3q6umgan3vdso
bafykbzaceddalwa3uds5a24cp2eplsabtv54skp3jnodkhhgb7ffat3aap7mm

> You are referring to third party websites. Can you tell me which ones?
>  http://nft.swiftnftmarket.io/ & http://assets.swiftnftmarket.io/， I mean those two websites as @Sunnyiscoming mentioned
> Are you applying for Swiftlab and is Swiftlab your company?
 I am applying on behalf of SwiftData which is a R&D branch of Data ABC Co., Ltd.

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As notary i am screening your application and doing due diligence.

Looking at your application i have some questions:

As you are brand new on Github and have no history of past applications. Applying for 5PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing data and it's requirements and distribution of the data. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?

Can you provide me with some KYC details per e-mail at kyc@dcent.nl. I would like to receive an e-mail from the original domainname / contact as listed on the website that refers to this application. 
Your application is for 5PB of datacap. Can you show us some visible proof from the data size and the storage you have there?

Can you provide us with a distribution plan supposably that you would be granted datacap to store?

As you can see here : https://github.com/filecoin-project/filecoin-plus-large-datasets it states:

> In order for a client and their dataset to be eligible:
> the dataset should be public, open, and mission aligned with Filecoin and Filecoin Plus. This also means that the data should be accessible to anyone > in the network, without requiring any special permissions or access requirement
> stored data should be readily retrievable on the network and this should be regularly verified (though the use of manual or automated verification > that includes retrieving data from various miners over the course of the DataCap allocation timeframe)

To make sure that you understand the rules and guidelines I would like to receive a detailed allocation plan where the amount of data and reputational SP's where you are going to store this data are included. 

Ps.
Just a few comments:

![Scherm­afbeelding 2023-01-16 om 15 22 28](https://user-images.githubusercontent.com/36404435/212700255-4c0bae96-2fb4-4f40-ad37-13af538dc542.png)
![Scherm­afbeelding 2023-01-16 om 15 21 14](https://user-images.githubusercontent.com/36404435/212700257-a11942f1-82f1-4086-b76c-0487999e7bb5.png)

**Comment by simonkim0515** [comment]
## Datacap Request Trigger

#### Total DataCap requested 
> 5PiB

#### Expected weekly DataCap usage rate 
> 500TiB 

#### Client address
> f1fmcgclzh7m7pmi3i7qgz3ujpsv5ml5uhhpjeogy

**Comment by Garyweiou** [comment]
Hi @cryptowhizzard 
1.	This is the first time to apply for dataCap, but we are not green hands in the Filecoin community. We followed Filecoin network all the way since 2020. We participated in Slingshot competition, we run nodes f01137656 & f01139232, that shows we are well equipped with sufficient knowledge about Filecoin Ecosystem.
2.	The email including kyc info and contact info were sent to you, please check.
3.	Regarding the data size proof, we provide you a screenshot of our current hot data storage status, and we have 1P cold data that does not show on this screenshot. Currently we are supporting more chains, that means the data size will increase sharply, it is expected 1t data will be generated per day in the future.
4.	As for the distribution plan, I will find 5~10 SPs in greater China to store our data, we are going to find some reputational SPs who offering fast retrieval service, we are going to select quality SPs offering competitive price and good sealing speed. Besides, we are 100% sure that our data is publicly accessible.
5.	The websites work normally, you can try again now.

Any question, please let me know.
![data size](https://user-images.githubusercontent.com/122604633/213361612-022dbb52-9fd0-4200-b1f1-3d31e8d4d1b7.png)

**Comment by Carohere** [comment]
>As for the distribution plan, I will find 5~10 SPs in greater China to store our data,

@Garyweiou, do you plan to store the data in only one region?

Also, 500TiB weekly allocation is way above the community-suggested value. Given this's your first formal application, the community has no way to track your previous performance, i suggest you reduce it to 100 or less. Please see [guideline](https://filecoinproject.slack.com/archives/C01DLAPKDGX/p1661450182420319 ) here.

**Comment by cryptowhizzard** [comment]
Hello fellow notary's

Let me comment that i am still in the proces of KYC with this client. The only thing i received up till now is a link to a certificate to a company in the Virgin islands and i am awaiting more information.

@Garyweiou 
For the Filecoin + program itself please note that by storing data on the Filecoin network you get 10x the power ( QAP ) of a normal sector. In return for this to be eligible for this incentive there are important rules to abide:

The data must be stored with multiple service providers. ( Not with one organization running multiple SP's but really independent organizations )
The data must be distributed over multiple regions. (Running a VPN is not allowed to fake presence in the USA for example)
The data must be retrievable by everyone in the community to check if you are really storing what you say you are storing. Running boost is highly recommended.
The data must be in line with the mission of FIL+. That means that the data must be valuable for humanity. It can be scientific or other things that people are highly interested in and is unique.
As data preparer you are allowed to store one copy yourself (if the client requests so for the sake of redundancy of the data). If you store your copy in China it means that the other organizations/SP must be outside China.

Commenting back on your answer above , " I will find 5~10 SPs in greater China to store our data," -> this is not the right way to go. I would like to create a data onboarding plan together with you to get you going.

It consists of:
The entity that is going to do the data preparation for you, where and when. If you need recommendations i can give them to you.
The SP's you are going to store data with and their reputation. If you need recommendations i can give them to you.
When we do checks on the data stored and how and by who.
The retrieval frequency (how often does the data needs to be retrieved and from where)

But first i am awaiting the answers of the e-mail for KYC that was sent to you.

**Comment by Garyweiou** [comment]
@Carohere @cryptowhizzard 
Hi , sorry for the delay, we were on holiday these days. 
1. we are going to store our data in America, greater China and HK after adjustment, and no single SP will take over 20% of the deal.  we have participated in Slingshot before, so we are not new in the ecosystem. We agree to reduce the weekly allocation to 100TiB, you can keep monitoring our storage status after we get the first tranche.
2.   for more KYC info, we just replied by email and hope we can have a quick phone call to ensure no private info disclosed publicly.  Looking forward to your call.

**Comment by cryptowhizzard** [comment]
Hi @Garyweiou 

As notary i am obliged to keep a record for administration. Phone calls are not helpful for documentation in this matter.

With the e-mail going back and forward i am confident that i am speaking to the right person, that's ok now.
The only matter outstanding is that i need a list of SP's where you are going to store your first tranche of datacap and their contact info.

If you want you can provide the list of SP id's here and their name / contact informnation by e-mail. 

Cheers

**Comment by Garyweiou** [comment]
@cryptowhizzard 
Hi,  we have contacted a few SPs in HK and America, but it may take some time to finalize the SP list for the first tranche. Because we are still waiting for dataCap, it is hard to reach an agreement because of uncertain dataCap size and granting time.
Please have confidence that  we will strictly abide by the relevant guidelines and ensure the SPs selected conduct operations under relevant rules. You can keep monitoring the storage status afterwards.

**Comment by cryptowhizzard** [comment]
Hi @Garyweiou 

I am sorry but i cannot help you with that. If you want me to sign i need these provided.

Have you tried on slack to find SP's in the deals channel?

**Comment by Garyweiou** [comment]
f02028779 is finalized, more SPs still on the way. We will keep updating.

**Comment by Garyweiou** [comment]
@cryptowhizzard Any udpate？ We are  trying to contact more SPs, it may take some time. Is it possible to sign this application?  With the dataCap settled down,  so we can  finalize the deal details with more SPs faster. You can keep tracking our records for avoiding potential risk.

**Comment by cryptowhizzard** [comment]
Hi,

I am sorry but i cannot help you with that. If you want me to sign i need these provided.

**Comment by Garyweiou** [comment]
Hi @cryptowhizzard  Finally, we worked out the SP list for the first tranche, pLease have a look. Would you kindly sign for us now? Many thanks !
f01518369
f01483143
f02028779
f01106668
f01991416

**Comment by herrehesse** [comment]
@Garyweiou What region are they in (non VPN) and what business entity owns them?

**Comment by Garyweiou** [comment]
Hi @cryptowhizzard @herrehesse 
f01518369  USA
f01483143  HK
f02028779  HK
f01106668  HK
f01991416  HK

The location of each SP is provided, but for the sake of privacy, the SPs don’t want to disclose their personal information. And we totally understand their intent to protect privacy and that’s why people like us came to the decentralized world like Filecoin.  Every community member came here trying to make a contribution to the ecosystem, I think we should respect their privacy, rather than force them to expose personal data. That may drive them away from the Filecoin network. In this way, it may harm the growth of entire Ecosystem. That’s not what we want, right?
We understand your position, and if you still have any doubt about this LDN, you can keep tracking on our distribution status, the statistics /CID report will say everything.

**Comment by cryptowhizzard** [comment]
Hi @Garyweiou 

f01991416 is an SP who has stored data from LDN's with FIL+ abuse. I will not sign when you want to use that SP.
f01518369 is already known to us and is ok to store data with.

As you can see in my form we encourage applications who are at least on 2 continents and have 3 organizations.
If you can suggest another way to show me that there are at least 2 organizations involved in HK and that those do not connect to the one in the USA , i will reconsider.

**Comment by Garyweiou** [comment]
hi @cryptowhizzard 
Thanks for your kind warning that f01991416 has a Fil+ abuse issue, we highly respect your determination to perform great due diligence for the benefits of Fil+ program. So we decided to remove f01991416 from the SP list, we promise we will abide by Fil+ guidelines that data owner should engage at least 4 SPs and no single SP ID should receive >30% of a client's allocated DataCap. 

Besides, we followed your rules that SPs must be located in 2 continents and 3 organizations. After double-check, we assure you that those SPs in HK are at different IP addresses, obviously they belong to different organizations. Regarding to the SP f01518369 in the US，it is known to you guys like you mentioned above. Let’s do the calculation, 3 HK-based organizations plus one in the US equals 4 organizations, Asia and North America = 2 continents. That’s perfectly matching the rules! 

Finally, we just a data owner who tries to preserve the data on Filecoin. We provide everything we can as you request from the very beginning, SPs refuse to expose too much information and this is beyond our control. Hopefully please have confidence in us and we can not assume someone evil before knowing each other. Please give us an opportunity to prove that we are trustworthy participants. 

Thanks!
![微信图片_20230217113829](https://user-images.githubusercontent.com/122604633/219543831-f9eeeff3-ad1e-486e-be3c-d1e7f2e75517.png)

**Comment by Garyweiou** [comment]
Hi @cryptowhizzard，Happy weekend！ Any feedback？

**Comment by cryptowhizzard** [comment]
Hi @Garyweiou 

We spoke about this in our team meeting this morning and decided we are not comfortable moving forward with this without KYC. This means you have to wait for feedback from other notary's to see if they are willing to move forward or have solutions.

**Comment by Garyweiou** [comment]
Hi @cryptowhizzard Thanks anyway. I think we provided sufficient KYC info back and forth between you and me, I made clear explanation with every details and also proof of identity, datasize and also SP list (see snapshot or above comments). I am really sorry for  this dilemma facing us. 

@liyunzhi-666 @Carohere @kernelogic @Fatman13 @simonkim0515 @Sunnyiscoming  @lvschouwen @kernelogic Hi notaries, can you please review our application and support us? Any question, please leave a comment.

![5c51684277181797e8d5873a3d1492a](https://user-images.githubusercontent.com/122604633/220282375-3b7ed797-fa07-4370-86ed-6436510e1371.png)

**Comment by Carohere** [comment]
Hi @Garyweiou, I'm not able to sign any app atm. Post in #fil-plus-application-review or reach out to R3 notaries directly would help!

**Comment by Garyweiou** [comment]
> Hi @Garyweiou, I'm not able to sign any app atm. Post in #fil-plus-application-review or reach out to R3 notaries directly would help!

Thanks! @Carohere

**Comment by Garyweiou** [comment]
@dannyob @simonkim0515  @liyunzhi-666  @Sunnyiscoming @lvschouwen @kernelogic 
Dear notaries,  I noticed you are very active notaries on other LDNs, can you please help us to move forward? any questiion, please leave a comment.  Thanks!

**Comment by cryptowhizzard** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceadyayhi7okawpm4thzzxapx47eepbgqtzziguzoyc6eissisfh6a 
#### Address 
> f1fmcgclzh7m7pmi3i7qgz3ujpsv5ml5uhhpjeogy
#### Datacap Allocated
> 250.00TiB
#### Signer Address
> f1krmypm4uoxxf3g7okrwtrahlmpcph3y7rbqqgfa
#### Id
> 383313b2-77a3-49d6-8ba4-fcb5c5d7cc58
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceadyayhi7okawpm4thzzxapx47eepbgqtzziguzoyc6eissisfh6a

**Comment by cryptowhizzard** [comment]
Hi @Garyweiou 

Here you go. Looking forward to your first milestone!

**Comment by Garyweiou** [comment]
@cryptowhizzard 
Thank you for your support, we will follow our plan.

@dannyob @simonkim0515 @liyunzhi-666 @Sunnyiscoming @lvschouwen @kernelogic @flyworker Dear notaries, cryptowhizzard has signed and one more sign is needed to get started, can you please help us here?

**Comment by kernelogic** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedpawjy3qs46fw2kwfgzl754naqznv6nvh2avhahbegyqe54hvgxy 
#### Address 
> f1fmcgclzh7m7pmi3i7qgz3ujpsv5ml5uhhpjeogy
#### Datacap Allocated
> 250.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### Id
> 383313b2-77a3-49d6-8ba4-fcb5c5d7cc58
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedpawjy3qs46fw2kwfgzl754naqznv6nvh2avhahbegyqe54hvgxy

**Comment by kernelogic** [comment]
Based on the comprehensive / responsive client communication, willing to support for round one.

**Comment by Garyweiou** [comment]
@kernelogic Thanks for your support, we are very excited to get started. Cheers!

**Comment by Garyweiou** [comment]
stay open plz

**Comment by Garyweiou** [comment]
stay open plz

**Comment by Garyweiou** [comment]
stay open plz

**Comment by Garyweiou** [comment]
please re-open !

**Comment by Garyweiou** [comment]
@simonkim0515
