### ISSUE TITLE
[DataCap Application] Cabrina- nanopore-reference-human-genome

### ISSUE THREAD

**Issue by NiwanDao** [filecoin-project/filecoin-plus-large-datasets#1564]
### Data Owner Name

Nanopore Whole Genome Sequencing Consortium

### Data Owner Country/Region

United States

### Data Owner Industry

Life Science / Healthcare

### Website

https://github.com/nanopore-wgs-consortium/NA12878

### Social Media

```text
https://dstorage.cabrina.xyz/
```

### Total amount of DataCap being requested

3PiB

### Weekly allocation of DataCap requested

500TiB

### On-chain address for first allocation

f1ndp7rsl4nvzgtxti4uuoyhvzms6bhulionxekpi

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
- I am an active participant in Slingshot and Slingshot Restore. This experience has gained me a lot of knowledge as a data preparer, deal SP, and retrieval client. 
- I have established a relationship with other community members along the way and have successfully sent deals with over 60 SPs worldwide. 
- With the surge of requests from other SPs on deal-making and the value of storing humanity’s most important data permanently, I decided to bring more value data to the network.
- I will track deals and provide retrieval access through https://dstorage.cabrina.xyz/.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
- This dataset includes the sequencing and assembly of a reference standard human genome (GM12878) using the MinION nanopore sequencing instrument with the R9.4 1D chemistry.
- I finished the CAR generation with a total number of 7753.
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### How do you plan to prepare the dataset

singularity

### Please share a sample of the data

```text
https://nanopore-human-wgs.s3.amazonaws.com/index.html
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Sporadic

### For how long do you plan to keep this dataset stored on Filecoin

1 to 1.5 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America

### How will you be distributing your data to storage providers

HTTP or FTP server, Shipping hard drives

### How do you plan to choose storage providers

Slack, Big data exchange, Partners

### If you already have a list of storage providers to work with, fill out their names and provider IDs below

```text
I work with SP including but not limited to FL cloud, GreaterHeat, HarryM-Filet,Chenxi,Andriy.I will continue look for new SP from the offline community and online BDE platform. 
The partner I previously worked with are listed in https://dstorage.cabrina.xyz/sp/
```

### How do you plan to make deals to your storage providers

Singularity

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Carohere** [comment]
@xingjitansuo, can you share the data size and your allocation plan? Also, 500TiB weekly allocation is way above the community-suggested value , any particular reason you are applying so?

**Comment by simonkim0515** [comment]
## Datacap Request Trigger

#### Total DataCap requested 
> 3PiB

#### Expected weekly DataCap usage rate 
> 500TiB 

#### Client address
> f1ndp7rsl4nvzgtxti4uuoyhvzms6bhulionxekpi

**Comment by xingjitansuo** [comment]
As the application indicated, I have generated 7753 files in total, which is around 250T per copy and I plan to send 10 - 12 replicas. Most of the SPs I tend to work with have a daily capacity of at least 100T. 500T weekly allocation is a conservative ad fair prediction.

**Comment by cryptowhizzard** [comment]
Hello @xingjitansuo 

Given your track record i will sign this application. Thank you for bringing your contribution to filecoin.

**Comment by cryptowhizzard** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceavqojpxw54a44mhb7iyhh2xle27tq72plwk2atiuwi6otqduerus 
#### Address 
> f1ndp7rsl4nvzgtxti4uuoyhvzms6bhulionxekpi
#### Datacap Allocated
> 153.59TiB
#### Signer Address
> f1krmypm4uoxxf3g7okrwtrahlmpcph3y7rbqqgfa
#### Id
> a04daae9-242d-476c-8902-b14527efad8a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceavqojpxw54a44mhb7iyhh2xle27tq72plwk2atiuwi6otqduerus

**Comment by Carohere** [comment]
@xingjitansuo ACK. How many SPs are confirmed now? To help me better follow up on this application, could you share their nodes, geographical locations, etc.?

**Comment by xingjitansuo** [comment]
Currently, 4 different organizations operating in the U.S. and China are confirmed for now as indicated in the application. SP ID has not been finalized yet from the SP side. You may get more ideas soon.

**Comment by Carohere** [comment]
Noted. Good luck finding 6+ SPs. Looking forward to seeing the checker report!

**Comment by mjroddy** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacea4jd2ye5e3wqkjk2svyha362jpkukg6mwlaun5fju4hmxr2bavfk 
#### Address 
> f1ndp7rsl4nvzgtxti4uuoyhvzms6bhulionxekpi
#### Datacap Allocated
> 153.59TiB
#### Signer Address
> f1ystxl2ootvpirpa7ebgwl7vlhwkbx2r4zjxwe5i
#### Id
> a04daae9-242d-476c-8902-b14527efad8a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacea4jd2ye5e3wqkjk2svyha362jpkukg6mwlaun5fju4hmxr2bavfk

**Comment by dongpo313** [comment]
checker:manualTrigger

**Comment by xingjitansuo** [comment]
checker:manualTrigger

**Comment by xingjitansuo** [comment]
checker:manualTrigger

**Comment by xingjitansuo** [comment]
The single copy is at around 250T.  Since this is the first allocation and some SP starts earlier than others, we will likely see more distributed allocation in the next round.

**Comment by kernelogic** [comment]
Based on the explanation and track record of @xingjitansuo ,willing to support.

**Comment by kernelogic** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebsz2vrupfmmlhtl4usrnuxef7ffxlmogudqd7dvoob5h5cqmaqdo 
#### Address 
> f1ndp7rsl4nvzgtxti4uuoyhvzms6bhulionxekpi
#### Datacap Allocated
> 307.19TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### Id
> 85cc4369-dd2a-4bc9-a4c2-3286807d5347
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebsz2vrupfmmlhtl4usrnuxef7ffxlmogudqd7dvoob5h5cqmaqdo

**Comment by Joss-Hua** [comment]
![Uploading image.png…]()

**Comment by Joss-Hua** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacea55ulq4d2taqunt37s7a7rgr7bgcyewrjjczi2xavg4ghab2mnww 
#### Address 
> f1ndp7rsl4nvzgtxti4uuoyhvzms6bhulionxekpi
#### Datacap Allocated
> 307.19TiB
#### Signer Address
> f1tfg54zzscugttejv336vivknmsnzzmyudp3t7wi
#### Id
> 85cc4369-dd2a-4bc9-a4c2-3286807d5347
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacea55ulq4d2taqunt37s7a7rgr7bgcyewrjjczi2xavg4ghab2mnww

**Comment by xingjitansuo** [comment]
As the distribution process is still in its early stages, it is hard that the majority of deals are being stored over 4 times. However, it is expected that data replication for deals will improve in the next tranche.

**Comment by stcouldlisa** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecvupguilrmbjm24apxcnyfyx4lvvgl4e7wgl6h7swxfmfm7rkuxy 
#### Address 
> f1ndp7rsl4nvzgtxti4uuoyhvzms6bhulionxekpi
#### Datacap Allocated
> 614.39TiB
#### Signer Address
> f1jvvltduw35u6inn5tr4nfualyd42bh3vjtylgci
#### Id
> 7ae4f71f-7975-4fed-8aa7-eb216f031d45
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecvupguilrmbjm24apxcnyfyx4lvvgl4e7wgl6h7swxfmfm7rkuxy

**Comment by stcouldlisa** [comment]
![WechatIMG175](https://user-images.githubusercontent.com/112812896/226505834-6fb3bdd6-2d7e-466e-b1c9-35bc9705e3cf.jpeg)

**Comment by METAVERSEDATAMINING** [comment]
Random retrieval  is Normal 
Expect to improve replica storage in the next round.
<img width="778" alt="00" src="https://user-images.githubusercontent.com/111408360/228730617-e15bca38-4f01-4caf-a199-daf0eb6db8f2.png">

**Comment by xingjitansuo** [comment]
checker:manualTrigger

**Comment by newwebgroup** [comment]
<img width="1235" alt="image" src="https://user-images.githubusercontent.com/100118145/229297888-ef568add-6f81-40c6-bf56-63aede1aacd4.png">

**Comment by newwebgroup** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb4po7ry2docugb737sle6hjncbpzacxectuee2pukghxkx6npc3m 
#### Address 
> f1ndp7rsl4nvzgtxti4uuoyhvzms6bhulionxekpi
#### Datacap Allocated
> 1.20PiB
#### Signer Address
> f1e77zuityhvvw6u2t6tb5qlnsegy2s67qs4lbbbq
#### Id
> 720e2e06-0934-41da-8a9e-95930a062031
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb4po7ry2docugb737sle6hjncbpzacxectuee2pukghxkx6npc3m

**Comment by xiaoyuaiheshui** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecagjsbntl22h4owmbup5rqrx26qemiabrucoesep6squvwzj2r4c 
#### Address 
> f1ndp7rsl4nvzgtxti4uuoyhvzms6bhulionxekpi
#### Datacap Allocated
> 1.20PiB
#### Signer Address
> f122qmy25wdtt5mxd77kndiq7z5x2n3iwiuz2wdsa
#### Id
> 720e2e06-0934-41da-8a9e-95930a062031
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecagjsbntl22h4owmbup5rqrx26qemiabrucoesep6squvwzj2r4c

**Comment by NiwanDao** [comment]
checker:manualTrigger

**Comment by NiwanDao** [comment]
checker:manualTrigger

**Comment by NiwanDao** [comment]
checker:manualTrigger

**Comment by NiwanDao** [comment]
checker:manualTrigger

**Comment by kernelogic** [comment]
Report LGTM, reputable long term open dataset client

**Comment by kernelogic** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceahaev4st7u4uvzfsloavzdd4vzbbxqtbrz4rofowujrehfkp2jls 
#### Address 
> f1ndp7rsl4nvzgtxti4uuoyhvzms6bhulionxekpi
#### Datacap Allocated
> 1.95PiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### Id
> c803cad1-ea88-48c9-aa2e-e6b78f7eedab
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceahaev4st7u4uvzfsloavzdd4vzbbxqtbrz4rofowujrehfkp2jls

**Comment by cryptowhizzard** [comment]
KYC Done / OK
Retrieval OK
Report OK

LGTM

**Comment by cryptowhizzard** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaj2nzj4yllwiqu7u2xy6ye7q5tyedxwqeqcdtlbmyy5uv76nk2za 
#### Address 
> f1ndp7rsl4nvzgtxti4uuoyhvzms6bhulionxekpi
#### Datacap Allocated
> 1.95PiB
#### Signer Address
> f1krmypm4uoxxf3g7okrwtrahlmpcph3y7rbqqgfa
#### Id
> c803cad1-ea88-48c9-aa2e-e6b78f7eedab
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaj2nzj4yllwiqu7u2xy6ye7q5tyedxwqeqcdtlbmyy5uv76nk2za

**Comment by NiwanDao** [comment]
WIP

**Comment by clriesco** [comment]
Removed stale label and reopened issue :)

**Comment by NiwanDao** [comment]
WIP

**Comment by NiwanDao** [comment]
WIP
