### ISSUE TITLE
[DataCap Application] FilSwan Slingshot Restore Program- Fly Brain Anatomy

### ISSUE THREAD

**Issue by flyworker** [filecoin-project/filecoin-plus-large-datasets#157]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name:  FilSwan - Slingshot Restore
- Website / Social Media: https://www.filswan.com
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 1 PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100TiB
- On-chain address for first allocation: f13d6zt424jkp55u7kp67azotkzadtlokwnz2ntxa 

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
This is a project for the Slingshot Restore Program, the program is for fix 10PB storage within 100 days. FilSwan is a leading web3 and computing provider in the filecoin ecosystem player. We would like to working as a client for this project.
```

What is the primary source of funding for this project?
```
Self funded by each node
```

What other projects/ecosystem stakeholders is this project associated with?
```
No
```

## Use-case details

Describe the data being stored onto Filecoin
```
Previous work of dataset can be found here: https://console.filswan.com/#/dataset

```

Where was the data in this dataset sourced from?
```
This dataset, made available by Janelia's FlyLight project, consists of fluorescence images of Drosophila melanogaster driver lines, aligned to standard templates, and stored in formats suitable for rapid searching in the cloud. https://registry.opendata.aws/janelia-flylight/
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
Please answer here.
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
https://open.quiltdata.com/b/janelia-flylight-imagery/tree/Annotator%20Gen1%20MCFO/R10A09/R10A09-20170217_21_E4-f-20x-brain-GAL4-JRC2018_Unisex_20x_HR-CDM_2.png
```

What is the expected retrieval frequency for this data?
```
Monthly
```

For how long do you plan to keep this dataset stored on Filecoin?
```
540 days
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
3 countries with 5 nodes
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
though Filswan IPFS gateway
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
Please answer here.
```

How will you be distributing deals across storage providers?
```
Please answer here.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, we have the fund, and community has the collateral.
```

**Comment by galen-mcandrew** [comment]
## Multisig Notary requested
#### Total DataCap requested 
> 1PiB
#### Expected weekly DataCap usage rate 
> 100TiB

**Comment by IreneYoung** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceapqrtotai6h3adxmsgipa3qtigwbulphxneojagejsrpq66olfbm 
#### Address 
> f13d6zt424jkp55u7kp67azotkzadtlokwnz2ntxa
#### Datacap Allocated
> 45TiB
#### Signer Address
> f1d4gmpqz3execjj2wvrxuuhvbms5mzh7t7yqrviq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceapqrtotai6h3adxmsgipa3qtigwbulphxneojagejsrpq66olfbm

**Comment by MegTei** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedpnnfdk5ypnxy56v4zmednjjunmqgetbbrzbnsxnbv2to4fp4tsu 
#### Address 
> f13d6zt424jkp55u7kp67azotkzadtlokwnz2ntxa
#### Datacap Allocated
> 45TiB
#### Signer Address
> f1ystxl2ootvpirpa7ebgwl7vlhwkbx2r4zjxwe5i
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedpnnfdk5ypnxy56v4zmednjjunmqgetbbrzbnsxnbv2to4fp4tsu

**Comment by cryptowhizzard** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacectzs7h7wtup6r6r36q4fkkw2xuw6oteh4ybkc7e7okqoitcenzje 
#### Address 
> f13d6zt424jkp55u7kp67azotkzadtlokwnz2ntxa
#### Datacap Allocated
> 90TiB
#### Signer Address
> f1krmypm4uoxxf3g7okrwtrahlmpcph3y7rbqqgfa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacectzs7h7wtup6r6r36q4fkkw2xuw6oteh4ybkc7e7okqoitcenzje

**Comment by Reiers** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebx5lmggcfhbm5nvzsbrrf57igkejnzjohexazqopmokz5rzup4hi 
#### Address 
> f13d6zt424jkp55u7kp67azotkzadtlokwnz2ntxa
#### Datacap Allocated
> 90TiB
#### Signer Address
> f1oz43ckvmtxmmsfzqm6bpnemqlavz4ifyl524chq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebx5lmggcfhbm5nvzsbrrf57igkejnzjohexazqopmokz5rzup4hi

**Comment by dannyob** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb37nb2jmc57kipqpr6q3abkpf7v54imtnqtcyjlg5vmvpxphl43e 
#### Address 
> f13d6zt424jkp55u7kp67azotkzadtlokwnz2ntxa
#### Datacap Allocated
> 90TiB
#### Signer Address
> f1k6wwevxvp466ybil7y2scqlhtnrz5atjkkyvm4a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb37nb2jmc57kipqpr6q3abkpf7v54imtnqtcyjlg5vmvpxphl43e

**Comment by swatchliu** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceakyc7ekihkcpjmvqq4sqvpm54uurtfkvhmtdrzljftaija3tuxza 
#### Address 
> f13d6zt424jkp55u7kp67azotkzadtlokwnz2ntxa
#### Datacap Allocated
> 200TiB
#### Signer Address
> f1yh6q3nmsg7i2sys7f7dexcuajgoweudcqj2chfi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceakyc7ekihkcpjmvqq4sqvpm54uurtfkvhmtdrzljftaija3tuxza

**Comment by MegTei** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb26z3y4eur47gaujbs3bp5lpdb73emastfkb5l6jdtnreebke73g 
#### Address 
> f13d6zt424jkp55u7kp67azotkzadtlokwnz2ntxa
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1ystxl2ootvpirpa7ebgwl7vlhwkbx2r4zjxwe5i
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb26z3y4eur47gaujbs3bp5lpdb73emastfkb5l6jdtnreebke73g

**Comment by cryptowhizzard** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceadepzx7rujuxre4u2s66prffrmxaqhtm27qumiqxaqwtyccckgto 
#### Address 
> f13d6zt424jkp55u7kp67azotkzadtlokwnz2ntxa
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1krmypm4uoxxf3g7okrwtrahlmpcph3y7rbqqgfa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceadepzx7rujuxre4u2s66prffrmxaqhtm27qumiqxaqwtyccckgto

**Comment by dkkapur** [comment]
@fabriziogianni7 @huseyincansoylu allocation should be correct actually, there are 599 TiB left on this notary address on chain. 

@flyworker is this one still relevant?

**Comment by flyworker** [comment]
Ah, so this is an error of the system, if we can fix the error, we can close the 366 to use this datacap first.

**Comment by dkkapur** [comment]
I'm changing the request to 399 TiB for now. Looks like there's a miscalculation on the bot. This should be ready for signature now @flyworker if you'd like to get folks to look at it.

**Comment by dkkapur** [comment]
![image](https://user-images.githubusercontent.com/2343218/173986001-688be66f-9ed6-456f-928f-1892b68bc8d2.png)

**Comment by cryptowhizzard** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceawrrhnwhzeoog5cdqfjeofhtkfyl42piiyztlntieuczjd4iifeo 
#### Address 
> f13d6zt424jkp55u7kp67azotkzadtlokwnz2ntxa
#### Datacap Allocated
> 399.00TiB
#### Signer Address
> f1krmypm4uoxxf3g7okrwtrahlmpcph3y7rbqqgfa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceawrrhnwhzeoog5cdqfjeofhtkfyl42piiyztlntieuczjd4iifeo

**Comment by IreneYoung** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaug7u4yz25uf6cdwk2yllypz2jr542gihkr6wpesc3yp4uap3nsi 
#### Address 
> f13d6zt424jkp55u7kp67azotkzadtlokwnz2ntxa
#### Datacap Allocated
> 399.00TiB
#### Signer Address
> f1d4gmpqz3execjj2wvrxuuhvbms5mzh7t7yqrviq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaug7u4yz25uf6cdwk2yllypz2jr542gihkr6wpesc3yp4uap3nsi

**Comment by psh0691** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceatrnynsqzey5vpjiojt4x4nz7w5ph5od6oqtr2xgpsl4emfr7p7m 
#### Address 
> f13d6zt424jkp55u7kp67azotkzadtlokwnz2ntxa
#### Datacap Allocated
> 199.00TiB
#### Signer Address
> f1qdko4jg25vo35qmyvcrw4ak4fmuu3f5rif2kc7i
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceatrnynsqzey5vpjiojt4x4nz7w5ph5od6oqtr2xgpsl4emfr7p7m

**Comment by kernelogic** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedy5i3kkh42dg2ljjhgryeck3hqzxjxzivnf4nc63cmsb3yvue6i4 
#### Address 
> f13d6zt424jkp55u7kp67azotkzadtlokwnz2ntxa
#### Datacap Allocated
> 199.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedy5i3kkh42dg2ljjhgryeck3hqzxjxzivnf4nc63cmsb3yvue6i4

**Comment by kernelogic** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaywzvvkcr2yqy5l2thhtw6ph25srhuxdq35ofjzhb5l2j5v6zxgy 
#### Address 
> f13d6zt424jkp55u7kp67azotkzadtlokwnz2ntxa
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaywzvvkcr2yqy5l2thhtw6ph25srhuxdq35ofjzhb5l2j5v6zxgy

**Comment by s0nik42** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebj5s3m6w2ix5rnjzwo45tu6f5dhtq4r5ke74sfwfin5vdhasqu4q 
#### Address 
> f13d6zt424jkp55u7kp67azotkzadtlokwnz2ntxa
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1wxhnytjmklj2czezaqcfl7eb4nkgmaxysnegwii
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebj5s3m6w2ix5rnjzwo45tu6f5dhtq4r5ke74sfwfin5vdhasqu4q

**Comment by filplus-checker** [comment]
## DataCap and CID Checker Report[^1]
 - Organization: ` FilSwan - Slingshot Restore`
 - Client: `f13d6zt424jkp55u7kp67azotkzadtlokwnz2ntxa`
### Storage Provider Distribution
The below table shows the distribution of storage providers that have stored data for this client.

If this is the first time a provider takes verified deal, it will be marked as `new`.

For most of the datacap application, below restrictions should apply.
 - Storage provider should not exceed 25% of total datacap.
 - Storage provider should not be storing duplicate data for more than 20%.
 - Storage provider should have published its public IP address.
 - All storage providers should be located in different regions.

⚠️ 34.45% of total deal sealed by [f01947280](https://filfox.info/en/address/f01947280) are duplicate data.

⚠️ 36.99% of total deal sealed by [f01955028](https://filfox.info/en/address/f01955028) are duplicate data.

⚠️ 22.34% of total deal sealed by [f01955030](https://filfox.info/en/address/f01955030) are duplicate data.

⚠️ 48.17% of total deal sealed by [f01876488](https://filfox.info/en/address/f01876488) are duplicate data.

⚠️ 49.94% of total deal sealed by [f01911369](https://filfox.info/en/address/f01911369) are duplicate data.

⚠️ [f01911369](https://filfox.info/en/address/f01911369) has unknown IP location.

⚠️ 27.87% of total deal sealed by [f01146045](https://filfox.info/en/address/f01146045) are duplicate data.

⚠️ [f0145874](https://filfox.info/en/address/f0145874) has unknown IP location.

⚠️ [f01801932](https://filfox.info/en/address/f01801932) has unknown IP location.

| Provider                                                    |                          Location | Total Deals Sealed | Percentage | Unique Data | Duplicate Deals |
| :---------------------------------------------------------- | --------------------------------: | -----------------: | ---------: | ----------: | --------------: |
| [f01786736](https://filfox.info/en/address/f01786736)`new`  |         Saint-Gabriel, Quebec, CA |         304.70 TiB |     16.77% |  274.00 TiB |          10.08% |
| [f01947280](https://filfox.info/en/address/f01947280)       |            Hangzhou, Zhejiang, CN |         181.13 TiB |      9.97% |  118.72 TiB |          34.45% |
| [f01938223](https://filfox.info/en/address/f01938223)       |              Montréal, Quebec, CA |         179.55 TiB |      9.88% |  147.05 TiB |          18.10% |
| [f01955028](https://filfox.info/en/address/f01955028)       |            Hangzhou, Zhejiang, CN |         155.09 TiB |      8.54% |   97.72 TiB |          36.99% |
| [f01955030](https://filfox.info/en/address/f01955030)       |            Hangzhou, Zhejiang, CN |         115.28 TiB |      6.35% |   89.53 TiB |          22.34% |
| [f02401](https://filfox.info/en/address/f02401)             |       Raleigh, North Carolina, US |         106.31 TiB |      5.85% |  106.28 TiB |           0.03% |
| [f01691553](https://filfox.info/en/address/f01691553)`new`  |              Montréal, Quebec, CA |          89.64 TiB |      4.93% |   89.48 TiB |           0.17% |
| [f01955034](https://filfox.info/en/address/f01955034)       |            Hangzhou, Zhejiang, CN |          63.34 TiB |      3.49% |   63.34 TiB |           0.00% |
| [f01876488](https://filfox.info/en/address/f01876488)       | Ho Chi Minh City, Ho Chi Minh, VN |          52.94 TiB |      2.91% |   27.44 TiB |          48.17% |
| [f01911369](https://filfox.info/en/address/f01911369)`new`  |                           Unknown |          50.34 TiB |      2.77% |   25.20 TiB |          49.94% |
| [f01641612](https://filfox.info/en/address/f01641612)       |              Montréal, Quebec, CA |          49.95 TiB |      2.75% |   41.89 TiB |          16.14% |
| [f01276](https://filfox.info/en/address/f01276)             |              Montréal, Quebec, CA |          47.88 TiB |      2.64% |   47.26 TiB |           1.31% |
| [f01207045](https://filfox.info/en/address/f01207045)       |  Heerhugowaard, North Holland, NL |          45.97 TiB |      2.53% |   45.97 TiB |           0.00% |
| [f0447183](https://filfox.info/en/address/f0447183)         |         Indianapolis, Indiana, US |          44.19 TiB |      2.43% |   44.16 TiB |           0.07% |
| [f01146045](https://filfox.info/en/address/f01146045)       |          Singapore, Singapore, SG |          32.97 TiB |      1.81% |   23.78 TiB |          27.87% |
| [f03624](https://filfox.info/en/address/f03624)`new`        |             Nürnberg, Bavaria, DE |          29.42 TiB |      1.62% |   28.52 TiB |           3.08% |
| [f0157535](https://filfox.info/en/address/f0157535)         |              Montréal, Quebec, CA |          29.06 TiB |      1.60% |   28.56 TiB |           1.72% |
| [f01662887](https://filfox.info/en/address/f01662887)       |          Singapore, Singapore, SG |          28.13 TiB |      1.55% |   24.03 TiB |          14.56% |
| [f01859603](https://filfox.info/en/address/f01859603)       |           Shenzhen, Guangdong, CN |          25.97 TiB |      1.43% |   21.06 TiB |          18.89% |
| [f0165400](https://filfox.info/en/address/f0165400)         |              Montréal, Quebec, CA |          19.45 TiB |      1.07% |   19.45 TiB |           0.00% |
| [f0240456](https://filfox.info/en/address/f0240456)         |              Chengdu, Sichuan, CN |          14.91 TiB |      0.82% |   14.91 TiB |           0.00% |
| [f01392893](https://filfox.info/en/address/f01392893)       |      Amsterdam, North Holland, NL |          13.94 TiB |      0.77% |   13.94 TiB |           0.00% |
| [f01713152](https://filfox.info/en/address/f01713152)       |              Jakarta, Jakarta, ID |          12.69 TiB |      0.70% |   12.69 TiB |           0.00% |
| [f0145874](https://filfox.info/en/address/f0145874)         |                           Unknown |          10.28 TiB |      0.57% |   10.28 TiB |           0.00% |
| [f01345523](https://filfox.info/en/address/f01345523)       |           Antwerpen, Flanders, BE |           7.72 TiB |      0.42% |    7.72 TiB |           0.00% |
| [f01072221](https://filfox.info/en/address/f01072221)       |       Los Angeles, California, US |           6.84 TiB |      0.38% |    6.53 TiB |           4.57% |
| [f0187709](https://filfox.info/en/address/f0187709)         |                Moscow, Moscow, RU |           6.72 TiB |      0.37% |    6.72 TiB |           0.00% |
| [f01402814](https://filfox.info/en/address/f01402814)       |          Singapore, Singapore, SG |           6.67 TiB |      0.37% |    6.67 TiB |           0.00% |
| [f019104](https://filfox.info/en/address/f019104)           |              Montréal, Quebec, CA |           6.48 TiB |      0.36% |    6.48 TiB |           0.00% |
| [f02301](https://filfox.info/en/address/f02301)             |          San Jose, California, US |           6.23 TiB |      0.34% |    6.23 TiB |           0.00% |
| [f03223](https://filfox.info/en/address/f03223)             |          San Jose, California, US |           6.22 TiB |      0.34% |    6.22 TiB |           0.00% |
| [f0143858](https://filfox.info/en/address/f0143858)         |           Clifton, New Jersey, US |           6.09 TiB |      0.34% |    6.09 TiB |           0.00% |
| [f097777](https://filfox.info/en/address/f097777)           |               Kivertsi, Volyn, UA |           5.98 TiB |      0.33% |    5.98 TiB |           0.00% |
| [f0240185](https://filfox.info/en/address/f0240185)         |           Clifton, New Jersey, US |           5.95 TiB |      0.33% |    5.95 TiB |           0.00% |
| [f0773157](https://filfox.info/en/address/f0773157)         |           Fremont, California, US |           5.81 TiB |      0.32% |    5.50 TiB |           5.38% |
| [f03488](https://filfox.info/en/address/f03488)             |                  Seoul, Seoul, KR |           5.73 TiB |      0.32% |    5.73 TiB |           0.00% |
| [f01163272](https://filfox.info/en/address/f01163272)       |               Perm, Perm Krai, RU |           5.69 TiB |      0.31% |    5.69 TiB |           0.00% |
| [f030379](https://filfox.info/en/address/f030379)           |                  Seoul, Seoul, KR |           5.64 TiB |      0.31% |    5.52 TiB |           2.22% |
| [f033356](https://filfox.info/en/address/f033356)           |                  Seoul, Seoul, KR |           4.09 TiB |      0.23% |    4.09 TiB |           0.00% |
| [f0440429](https://filfox.info/en/address/f0440429)         |                  Seoul, Seoul, KR |           3.45 TiB |      0.19% |    3.45 TiB |           0.00% |
| [f010088](https://filfox.info/en/address/f010088)           |           Everett, Washington, US |           3.44 TiB |      0.19% |    3.44 TiB |           0.00% |
| [f01806491](https://filfox.info/en/address/f01806491)`new`  |                  Seoul, Seoul, KR |           3.31 TiB |      0.18% |    3.22 TiB |           2.83% |
| [f01398391](https://filfox.info/en/address/f01398391)       |              Chengdu, Sichuan, CN |           2.59 TiB |      0.14% |    2.59 TiB |           0.00% |
| [f024184](https://filfox.info/en/address/f024184)           |                  Seoul, Seoul, KR |           2.56 TiB |      0.14% |    2.56 TiB |           0.00% |
| [f01222595](https://filfox.info/en/address/f01222595)       |                Moscow, Moscow, RU |           2.13 TiB |      0.12% |    2.13 TiB |           0.00% |
| [f01051301](https://filfox.info/en/address/f01051301)       |              Daejeon, Daejeon, KR |           2.13 TiB |      0.12% |    2.13 TiB |           0.00% |
| [f01466075](https://filfox.info/en/address/f01466075)       |                  Seoul, Seoul, KR |         896.00 GiB |      0.05% |  896.00 GiB |           0.00% |
| [f01790264](https://filfox.info/en/address/f01790264)       |                  Seoul, Seoul, KR |         448.00 GiB |      0.02% |  448.00 GiB |           0.00% |
| [f01764587](https://filfox.info/en/address/f01764587)       |                  Seoul, Seoul, KR |         416.00 GiB |      0.02% |  416.00 GiB |           0.00% |
| [f01801932](https://filfox.info/en/address/f01801932)       |                           Unknown |         224.00 GiB |      0.01% |  224.00 GiB |           0.00% |
| [f01390330](https://filfox.info/en/address/f01390330)`new`  |                Xi’an, Shaanxi, CN |         160.00 GiB |      0.01% |  160.00 GiB |           0.00% |

![Provider Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/157/1671092755467.png)
### Deal Data Replication
The below table shows how each many unique data are replicated across storage providers.
- No more than 25% of unique data are stored with less than 4 providers.

⚠️ 39.80% of deals are for data replicated across less than 4 storage providers.

| Unique Data Size | Total Deals Made | Number of Providers | Deal Percentage |
| ---------------: | ---------------: | ------------------: | --------------: |
|       228.36 TiB |       282.72 TiB |                   1 |          15.56% |
|        80.88 TiB |       171.83 TiB |                   2 |           9.46% |
|        69.91 TiB |       268.56 TiB |                   3 |          14.78% |
|        68.00 TiB |       325.22 TiB |                   4 |          17.90% |
|        38.50 TiB |       228.44 TiB |                   5 |          12.57% |
|        28.75 TiB |       211.81 TiB |                   6 |          11.66% |
|        13.78 TiB |       116.97 TiB |                   7 |           6.44% |
|         1.53 TiB |        13.03 TiB |                   8 |           0.72% |
|         1.09 TiB |        10.50 TiB |                   9 |           0.58% |
|         1.73 TiB |        19.23 TiB |                  10 |           1.06% |
|         2.38 TiB |        28.41 TiB |                  11 |           1.56% |
|         3.34 TiB |        43.97 TiB |                  12 |           2.42% |
|         3.16 TiB |        44.19 TiB |                  13 |           2.43% |
|         1.38 TiB |        20.81 TiB |                  14 |           1.15% |
|       960.00 GiB |        15.19 TiB |                  15 |           0.84% |
|       768.00 GiB |        13.03 TiB |                  16 |           0.72% |
|       160.00 GiB |         2.81 TiB |                  17 |           0.15% |

![Replication Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/157/1671092758092.png)
### Deal Data Shared with other Clients
The below table shows how many unique data are shared with other clients.
Usually different applications owns different data and should not resolve to the same CID.

⚠️ CID sharing has been observed.

| Other Client                                                                                                                                                                                                              | Application                                                                                                                     | Total Deals Affected | Unique CIDs |        Verifier |
| :------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ | :------------------------------------------------------------------------------------------------------------------------------ | -------------------: | ----------: | --------------: |
| [f1o54sve7ede7im4caux3ug7lsyjmbue7ss3zzl6y](https://filfox.info/en/address/f1o54sve7ede7im4caux3ug7lsyjmbue7ss3zzl6y)                                                                                                     | [FilSwan](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/278)                                          |           744.03 TiB |       7,433 | LDN v3 multisig |
| [f1bstbq5bi72kyovhh7zoo2f6l6uivsjz4ey5dnqq](https://filfox.info/en/address/f1bstbq5bi72kyovhh7zoo2f6l6uivsjz4ey5dnqq)                                                                                                     | [FilSwan](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/917)                                          |           494.52 TiB |       5,572 | LDN v3 multisig |
| [f1r3d25hl2y7rqlsu2mgczdethy4qqjmkfdlmibfq](https://filfox.info/en/address/f1r3d25hl2y7rqlsu2mgczdethy4qqjmkfdlmibfq)                                                                                                     | [ NEXRAD \- FilSwan](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/80)                                |           424.42 TiB |       2,000 | LDN v3 multisig |
| [f14r2jybmccwiu6hze4fu55jyhclktvwacec56hea](https://filfox.info/en/address/f14r2jybmccwiu6hze4fu55jyhclktvwacec56hea)                                                                                                     | [ FilSwan](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/15)                                          |           412.85 TiB |       7,808 | LDN v3 multisig |
| [f1pkrmygbvweykpjcut36lf7ewgqdfhjklbhvepda](https://filfox.info/en/address/f1pkrmygbvweykpjcut36lf7ewgqdfhjklbhvepda)                                                                                                     | [Protocol Labs \( project: Slingshot Evergreen \)](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/293) |           297.36 TiB |       3,110 |       LDN # 293 |
| [f3rwypb3nhyzkslf6eb2qoiaqdwvaedcawxiav4hm<br/>hi4cp4w7ptjua42knqoddbl5uabcrtzgq7jajvjro<br/>z54a](https://filfox.info/en/address/f3rwypb3nhyzkslf6eb2qoiaqdwvaedcawxiav4hmhi4cp4w7ptjua42knqoddbl5uabcrtzgq7jajvjroz54a) | [dropcool \- Slingshot Restore](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/145)                    |            99.13 TiB |       2,960 | LDN v3 multisig |
| [f1eto4dfafkoeukxenoc7vzexrvf6i4yqvhszrq2y](https://filfox.info/en/address/f1eto4dfafkoeukxenoc7vzexrvf6i4yqvhszrq2y)                                                                                                     | [ Haoqian Mx](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/308)                                      |            10.25 TiB |          63 | LDN v3 multisig |
| [f1a5z2ulumzvqogr2hui6o5vsbzzebcvc5mm3aqei](https://filfox.info/en/address/f1a5z2ulumzvqogr2hui6o5vsbzzebcvc5mm3aqei)                                                                                                     | Unknown                                                                                                                         |             6.25 TiB |          40 |         Unknown |
| [f3v7x4a2aapgx6o2r477tenoin3u5oadaeqyd7kjd<br/>sitykvf4ok7vq2utcyh34lmu5u7oybs25ff6s4dbu<br/>dpma](https://filfox.info/en/address/f3v7x4a2aapgx6o2r477tenoin3u5oadaeqyd7kjdsitykvf4ok7vq2utcyh34lmu5u7oybs25ff6s4dbudpma) | [LeoCheung \- Slingshot Restore](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/151)                   |             3.59 TiB |          23 | LDN v3 multisig |
| [f13zfhkvtf6mewd74jhav6iqcggwsojht73tickga](https://filfox.info/en/address/f13zfhkvtf6mewd74jhav6iqcggwsojht73tickga)                                                                                                     | [X\-Order Lab](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/936)                                     |           192.00 GiB |           6 | LDN v3 multisig |
| [f3vmnxpsmdb5vdv6n7srtpqb4hdtd3ui2xntkk7ca<br/>tzhg3r6kkok433ijtatqwtymt27unojrfas7sa4dz<br/>6htq](https://filfox.info/en/address/f3vmnxpsmdb5vdv6n7srtpqb4hdtd3ui2xntkk7catzhg3r6kkok433ijtatqwtymt27unojrfas7sa4dz6htq) | Unknown                                                                                                                         |            64.00 GiB |           1 |         Unknown |

[^1]: To manually trigger this report, add a comment with text `checker:manualTrigger`
