### ISSUE TITLE
[DataCap Application] Usertoken

### ISSUE THREAD

**Issue by usertoken** [filecoin-project/filecoin-plus-large-datasets#1571]
### Data Owner Name
Usertoken

### Data Owner Country/Region
United States

### Data Owner Industry
Information, Media & Telecommunications

### Website
[https://www.usertoken.com](https://www.usertoken.com)

### Social Media
@usertoken (Twitter)

### Total amount of DataCap being requested
5 PiB

### Weekly allocation of DataCap requested
500 TiB

### On-chain address for first allocation
f13zuz7qgorjo6gd5krecsysagvidfjan4rgtijy

### Custom multisig
No

### Share a brief history of your project and organization
preserve and provide public access to raw data for Artificial Intelligence and deep learning training using in-house and crowdsource datasets

### Is this project associated with other projects/ecosystem stakeholders?
No

### Describe the data being stored onto Filecoin
datasets consists of video, audio, and images used for training A.I.

### Where was the data currently stored in this dataset sourced from
My own storage infra

### How do you plan to prepare the dataset
IPFS

### If you answered "other/custom tool" in the previous question, enter the details here
IPFS, lotus, singularity, graphsplit

### Please share a sample of the data
https://github.com/usertoken/ai-datasets/bolt-multi-size-detection.mp4
https://github.com/usertoken/ai-datasets/driver-action-recognition.mp4
https://github.com/usertoken/ai-datasets/fruit-and-vegetable-detection.mp4

### Confirm that this is a public dataset that can be retrieved by anyone on the Network
Yes

### What is the expected retrieval frequency for this data
Weekly

### For how long do you plan to keep this dataset stored on Filecoin
2 to 3 years

### In which geographies do you plan on making storage deals
North America

### How will you be distributing your data to storage providers
Cloud storage (i.e. S3)

### How do you plan to choose SP
Slack

### If you answered "Others" in the previous question, what is the tool or platform you plan to use
Slack, Big data exchange, Partners,Filmine

### How do you plan to make deals to your storage providers
Boost client

### If you answered "Others/custom tool" in the previous question, enter the details here
Boost client, Lotus client, Singularity

### Can you confirm that you will follow the Fil+ guideline
Yes

**Comment by lvschouwen** [comment]
@usertoken 
Thanks for you datacap request and welcome to the Filecoin network.
The sample data you provide is a clone of the https://github.com/intel-iot-devkit/sample-videos repo.
Can you provide sample data of what you plan to store on Filecoin?

**Comment by lvschouwen** [comment]
Also you website seems to be broken on many points.
Last but not least you state that you plan to make storage deals in North America only.
Is there a reason to limit your reach to North America only? Why not spread the data over the globe?

**Comment by usertoken** [comment]
- We are crowdsourcing public assets for our data as we migrate our data pipeline to IPFS.   - We are currently working on migrating our internal datasets from r2 and s3 into the public domain according to licensing constraints.
- We are working on a login process for our website that would allow public and private access without registration.  Login is currently disabled. 
- We initially target North America and would open up access to other geolocation as we scale.

Thank you for the feedback and let us know if you have any other questions.

**Comment by Sunnyiscoming** [comment]
![image](https://user-images.githubusercontent.com/105098820/215397736-d94334ea-494b-49de-b597-55964901f9d0.png)
All the links of data samples are unavailable, please check them.

**Comment by usertoken** [comment]
Please check these dataset samples:

- https://pub-1271127aa1404ba3bd1e199833b19a73.r2.dev/drone-pedestrian-3.mp4
- https://pub-1271127aa1404ba3bd1e199833b19a73.r2.dev/drone-rotate-right-360.mp4
- https://pub-1271127aa1404ba3bd1e199833b19a73.r2.dev/drone-bridge-view.mp4
- https://pub-1271127aa1404ba3bd1e199833b19a73.r2.dev/drone-rotate-right-360.mp4

We are releasing our R2 datasets.

**Comment by Sunnyiscoming** [comment]
Can you provide more data samples to prove that you have 5 PB already?
Can you provide more detailed informations about yourself and SPs you will cooperate with?

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Looking at your application i have some questions:
As you are brand new on Github and have no history of past applications it seems to me that applying for 5PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?

Can you show us visible proof of the size of your data and the storage systems you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230337462961356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!

**Comment by simonkim0515** [comment]
## Datacap Request Trigger

#### Total DataCap requested 
> 5PiB

#### Expected weekly DataCap usage rate 
> 500TiB 

#### Client address
> f13zuz7qgorjo6gd5krecsysagvidfjan4rgtijy
