### ISSUE TITLE
[DataCap Application] Hubble Space Telescope Public Data

### ISSUE THREAD

**Issue by StoweRudge** [filecoin-project/filecoin-plus-large-datasets#1573]
### Data Owner Name

Space Telescope Science Institute

### Data Owner Country/Region

United States

### Data Owner Industry

Environment

### Website

https://astroquery.readthedocs.io/en/latest/mast/mast.html#module-astroquery.mast

### Social Media

```text
archive@stsci.edu
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

400TiB

### On-chain address for first allocation

f1tbgm7baejvc5hmzbbeqnuhe7yq6s4e3dwrlacii

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
I am a participant who follows the filecoin community. I want to get involved in filecoin deeply by storing useful public datasets first.

The Space Telescope Science Institute (STScI) is operated by the Association of Universities for Research in Astronomy (AURA) with the goal of helping humanity explore the universe with advanced space telescopes and ever-growing data archives.
```

### Is this project associated with other projects/ecosystem stakeholders?

Yes

### Describe the data being stored onto Filecoin

```text
The Hubble Space Telescope (HST) is one of the most productive scientific instruments ever created. This dataset contains calibrated and raw data for all of the currently active instruments on HST: ACS, COS, STIS and WFC3.
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### How do you plan to prepare the dataset

lotus

### Please share a sample of the data

```text
https://registry.opendata.aws/hst/
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Sporadic

### For how long do you plan to keep this dataset stored on Filecoin

2 to 3 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, South America, Europe, Australia (continent)

### How will you be distributing your data to storage providers

Cloud storage (i.e. S3), HTTP or FTP server, IPFS, Shipping hard drives

### How do you plan to choose storage providers

Slack, Big data exchange

### How do you plan to make deals to your storage providers

Lotus client, Singularity

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Looking at your application i have some questions:
As you are brand new on Github and have no history of past applications it seems to me that applying for 5PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?

Can you show us visible proof of the size of your data and the storage systems you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230232885049356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!

**Comment by herrehesse** [comment]
@StoweRudge Awesome application, looking forward to your KYC form!

**Comment by Sunnyiscoming** [comment]
Can you provide more detailed information about Sps you will cooperate with?

**Comment by caoyoungyoung** [comment]
you answered 'yes', so have to list all the stakeholders associated with
[
![22](https://user-images.githubusercontent.com/113870610/216266284-a6fe9fd5-88c5-4a42-b86e-8df3d9c6b758.png)
](url)

**Comment by StoweRudge** [comment]
@caoyoungyoung That was a mistake, and I've fixed it. Thanks!

**Comment by simonkim0515** [comment]
## Datacap Request Trigger

#### Total DataCap requested 
> 5PiB

#### Expected weekly DataCap usage rate 
> 400TiB 

#### Client address
> f1tbgm7baejvc5hmzbbeqnuhe7yq6s4e3dwrlacii

**Comment by Casey-PG** [comment]
willing to support in the 1st round.

**Comment by Casey-PG** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecxzlqsralxu75os7bbvjxsdbfbxeqzv2k7enedqnthef5t3c22ha 
#### Address 
> f1tbgm7baejvc5hmzbbeqnuhe7yq6s4e3dwrlacii
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1d4yb3wags3mtddzesxoo63jv7dmlec3bq4yteni
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecxzlqsralxu75os7bbvjxsdbfbxeqzv2k7enedqnthef5t3c22ha

**Comment by Suyanj** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceapw5w67tqlhxhqogvkdxjgppwad2ndqkhvz2zzhatztudfqyfku2 
#### Address 
> f1tbgm7baejvc5hmzbbeqnuhe7yq6s4e3dwrlacii
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1ihv7gz3vn3xqvikpt4rwryecgisl7745lodx3yi
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceapw5w67tqlhxhqogvkdxjgppwad2ndqkhvz2zzhatztudfqyfku2

**Comment by AthSmith** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceagbvprrie5ywaodxpwahqsomej7xfbrbbpo6jacx7mm7inn6fj3s 
#### Address 
> f1tbgm7baejvc5hmzbbeqnuhe7yq6s4e3dwrlacii
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1vxbqrf7rfum3n6m5u6eb4re6xj7amvsaqnzu64y
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceagbvprrie5ywaodxpwahqsomej7xfbrbbpo6jacx7mm7inn6fj3s

**Comment by BobbyChoii** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedetvl4ynecgba276y2lzfue7dksqoxnltrjbcbvkh42jkq5uv7dy 
#### Address 
> f1tbgm7baejvc5hmzbbeqnuhe7yq6s4e3dwrlacii
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1irqs2gmctiv3jcdfwuch7oxvf4ixh3k4b2wc24i
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedetvl4ynecgba276y2lzfue7dksqoxnltrjbcbvkh42jkq5uv7dy

**Comment by TakiChain** [comment]
checker:manualTrigger

**Comment by TakiChain** [comment]
Report is good，ongoing communication from the client.

**Comment by TakiChain** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebe7nfcppun3q7obqk3zovl7djxe37v3mml4qi5miflcdt5slxad2 
#### Address 
> f1tbgm7baejvc5hmzbbeqnuhe7yq6s4e3dwrlacii
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f15impf3j2zcaex4lhyxndxswuuhv24vzstuqtxsi
#### Id
> 38faf2a6-33ac-4168-b3c0-b6a01fa6ccb8
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebe7nfcppun3q7obqk3zovl7djxe37v3mml4qi5miflcdt5slxad2

**Comment by Aifabot-Cloud** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedfgvy5sph5qhvmvdwxsmy6w5atxtzlyrrzzdh7t2rhpg2nx2ydnk 
#### Address 
> f1tbgm7baejvc5hmzbbeqnuhe7yq6s4e3dwrlacii
#### Datacap Allocated
> 1.56PiB
#### Signer Address
> f174fg3bqbln3zjnkxtyf6s54txqkr7yqkj6cig7y
#### Id
> cf7b4506-bfc2-436f-bee8-1170c0cdf941
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedfgvy5sph5qhvmvdwxsmy6w5atxtzlyrrzzdh7t2rhpg2nx2ydnk

**Comment by AthSmith** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedccluqqqa3duc3fxxr3pqh6ygw7bczsi43dmrv5e34kxukznb6ay 
#### Address 
> f1tbgm7baejvc5hmzbbeqnuhe7yq6s4e3dwrlacii
#### Datacap Allocated
> 1.56PiB
#### Signer Address
> f1vxbqrf7rfum3n6m5u6eb4re6xj7amvsaqnzu64y
#### Id
> cf7b4506-bfc2-436f-bee8-1170c0cdf941
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedccluqqqa3duc3fxxr3pqh6ygw7bczsi43dmrv5e34kxukznb6ay

**Comment by AthSmith** [comment]
Public data with clear allocation plan, we are willing to help onboard more valuable dataset.

**Comment by spaceT9** [comment]
checker:manualTrigger

**Comment by spaceT9** [comment]
Increase retrieval rate before next tranche please

**Comment by StoweRudge** [comment]
checker:manualTrigger

**Comment by StoweRudge** [comment]
@spaceT9 ok! We are paying time on updating.

**Comment by TakiChain** [comment]
Glad to see the improvement in your reporting, keep up the good work.

**Comment by TakiChain** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceacvd4wpn7cjoyuqhcb67yh4bghrh6ccfafyy3nr3b75mcynlfck4 
#### Address 
> f1tbgm7baejvc5hmzbbeqnuhe7yq6s4e3dwrlacii
#### Datacap Allocated
> 1.56PiB
#### Signer Address
> f15impf3j2zcaex4lhyxndxswuuhv24vzstuqtxsi
#### Id
> 13e0a7c6-08cf-4b02-a1d1-2cdcfda91f2d
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceacvd4wpn7cjoyuqhcb67yh4bghrh6ccfafyy3nr3b75mcynlfck4

**Comment by Meibuy** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedqtio4eosty42fhm5dfwtfzaz73rwypx5jurvgbq7fgcgmmnuqss 
#### Address 
> f1tbgm7baejvc5hmzbbeqnuhe7yq6s4e3dwrlacii
#### Datacap Allocated
> 1.56PiB
#### Signer Address
> f1bwugfihrmn3iyunzyxst5nttql3dge4khwmurtq
#### Id
> 13e0a7c6-08cf-4b02-a1d1-2cdcfda91f2d
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedqtio4eosty42fhm5dfwtfzaz73rwypx5jurvgbq7fgcgmmnuqss

**Comment by Bennyyangpu** [comment]
checker:manualTrigger

**Comment by Bennyyangpu** [comment]
We're willing to help support the application. Please follow the plan you have shared. @StoweRudge  
"Deal Data Replication" is not good as we expect.

**Comment by Bennyyangpu** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceajinrz3ysh665h5pgl5jswmrmck3qm2h766ahc75zobfui4365bq 
#### Address 
> f1tbgm7baejvc5hmzbbeqnuhe7yq6s4e3dwrlacii
#### Datacap Allocated
> 725.11TiB
#### Signer Address
> f174fg3bqbln3zjnkxtyf6s54txqkr7yqkj6cig7y
#### Id
> 313e2594-72dc-4015-8879-bf3ebe06b801
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceajinrz3ysh665h5pgl5jswmrmck3qm2h766ahc75zobfui4365bq

**Comment by cryptowhizzard** [comment]
![Scherm­afbeelding 2023-09-05 om 14 57 25](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/36404435/1ecf9a53-914f-4e9a-a096-ecb63f689b83)

Please read above and please remove your signature @Bennyyangpu 

![Scherm­afbeelding 2023-09-05 om 14 57 47](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/36404435/39181af8-25df-48f9-be0c-68e6f18f53ec)

**Comment by Bennyyangpu** [comment]
@cryptowhizzard Thanks for your tip, I hadn't noticed that the applicant hadn't completed the form.

@StoweRudge If you need to continue, please do it asap.

**Comment by StoweRudge** [comment]
![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/122515345/a0bad205-5d6c-4ace-9b52-6921c7b6aa02)
@Bennyyangpu Thank you for your reminder! We have done it.

**Comment by StoweRudge** [comment]
Yes

**Comment by StoweRudge** [comment]
Yes, keep open.

**Comment by StoweRudge** [comment]
Yes, keep open.

**Comment by kevzak** [comment]
checker:manualTrigger

**Comment by kevzak** [comment]
f01808139 | Hong Kong, Central and Western, HKANLIAN NETWORK TECHNOLOGY CO., LIMITED | 649.50 TiB | 12.88% | 649.50 TiB | 0.00%
f02368321new | Hong Kong, Central and Western, HKANLIAN NETWORK TECHNOLOGY CO., LIMITED | 183.88 TiB | 3.65% | 183.88 TiB | 0.00%
f0420161 | Toronto, Ontario, CABeanfield Technologies Inc. | 740.50 TiB | 14.68% | 740.50 TiB | 0.00%
f02128256 | Toronto, Ontario, CABeanfield Technologies Inc. | 257.88 TiB | 5.11% | 257.88 TiB | 0.00%
f01878693 | Jiangyin, Jiangsu, CNChina Mobile communications corporation | 298.00 TiB | 5.91% | 298.00 TiB | 0.00%
f01955030 | Shanghai, Shanghai, CNChina Mobile communications corporation | 45.00 TiB | 0.89% | 45.00 TiB | 0.00%
f01882035 | Chengdu, Sichuan, CNChina Mobile Communications Group Co., Ltd. | 87.97 TiB | 1.74% | 87.97 TiB | 0.00%
f02232088 | Chengdu, Sichuan, CNCHINA UNICOM China169 Backbone | 287.97 TiB | 5.71% | 287.97 TiB | 0.00%
f02232007 | Chengdu, Sichuan, CNCHINA UNICOM China169 Backbone | 287.66 TiB | 5.70% | 287.66 TiB | 0.00%
f02181152 | Chengdu, Sichuan, CNCHINA UNICOM China169 Backbone | 200.69 TiB | 3.98% | 200.69 TiB | 0.00%
f02114994 | Chengdu, Sichuan, CNCHINA UNICOM China169 Backbone | 114.06 TiB | 2.26% | 114.06 TiB | 0.00%
f02114868 | Chengdu, Sichuan, CNCHINA UNICOM China169 Backbone | 112.91 TiB | 2.24% | 112.91 TiB | 0.00%
f02233608 | Chengdu, Sichuan, CNCHINA UNICOM China169 Backbone | 110.00 TiB | 2.18% | 110.00 TiB | 0.00%
f01955034 | Hangzhou, Zhejiang, CNCHINA UNICOM China169 Backbone | 40.00 TiB | 0.79% | 40.00 TiB | 0.00%
f01084913 | Hong Kong, Central and Western, HKChina Unicom Global | 198.63 TiB | 3.94% | 198.63 TiB | 0.00%
f02816097 | Shenzhen, Guangdong, CNCHINANET-BACKBONE | 187.72 TiB | 3.72% | 187.72 TiB | 0.00%
f02369788 | Shenzhen, Guangdong, CNCHINANET-BACKBONE | 168.94 TiB | 3.35% | 168.94 TiB | 0.00%
f02200400new | Shenzhen, Guangdong, CNCHINANET-BACKBONE | 149.13 TiB | 2.96% | 149.13 TiB | 0.00%
f01452388 | Hangzhou, Zhejiang, CNCHINANET-BACKBONE | 71.06 TiB | 1.41% | 71.06 TiB | 0.00%
f02362189 | Hong Kong, Central and Western, HKHK Cable TV Ltd | 220.13 TiB | 4.36% | 220.13 TiB | 0.00%
f02368314new | Deyang, Sichuan, CNSichuan Chuanxn IDC | 153.88 TiB | 3.05% | 153.88 TiB | 0.00%
f02363999 | Singapore, Singapore, SGStarHub Ltd | 291.94 TiB | 5.79% | 291.94 TiB | 0.00%
f02222222 | Singapore, Singapore, SGTencent Building, Kejizhongyi Avenue | 186.75 TiB | 3.70% | 186.75 TiB | 0.00%

SPs provided
No entity or contact info
f01808139
f0420161
f02363999
f02114994
f01955034

**Comment by kevzak** [comment]
3 SPs IDs match. Closing until more information provided
