### ISSUE TITLE
[DataCap Application] Apus Network [1/2]

### ISSUE THREAD

**Issue by freecodewu** [filecoin-project/filecoin-plus-large-datasets#1574]
### Data Owner Name

Apus Network

### Data Owner Country/Region

China

### Data Owner Industry

Web3 / Crypto

### Website

https://apus.network/

### Social Media

```text
Twitter: https://twitter.com/apus_network
Telegram: https://t.me/+AWdHtLSl2m4yM2I1
Media report about Apus Network: https://news.pedaily.cn/202205/493211.shtml
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

500TiB

### On-chain address for first allocation

f1jr3yfd367csao6k3x27643pnxxrz5cf6l7julmq

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Apus Network is a Web3 Infra for decentralized edge network data transmission. We cooperate closely with Filecoin. Apus Network is operated and run by PPIO's oversea business team. Tik Tok and Kuaishou are our customers, and iQiyi and Bilibili use our overseas nodes.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
The data we'd like to store includes: 
1) historical versions of our clients' app packages that are public to all (800 TiB)
2) log files of our nodes (200TiB)
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### How do you plan to prepare the dataset

lotus, singularity, others/custom tool

### If you answered "other/custom tool" in the previous question, enter the details here

```text
https://github.com/filswan/go-swan-client#Graphsplit
```

### Please share a sample of the data

```text
App package samples:
https://s3.ap-southeast-1.amazonaws.com/apusnetwork.test/3310931.apk
https://s3.ap-southeast-1.amazonaws.com/apusnetwork.test/3334275.apk
https://s3.ap-southeast-1.amazonaws.com/apusnetwork.test/3334315.apk
https://s3.ap-southeast-1.amazonaws.com/apusnetwork.test/3334492.apk
https://s3.ap-southeast-1.amazonaws.com/apusnetwork.test/3334951.apk

Log file samples:
https://s3.ap-southeast-1.amazonaws.com/apusnetwork.test/HJSC01173.xlsx
https://s3.ap-southeast-1.amazonaws.com/apusnetwork.test/HJSC02540.xlsx
https://s3.ap-southeast-1.amazonaws.com/apusnetwork.test/HJSC02875.xlsx
https://s3.ap-southeast-1.amazonaws.com/apusnetwork.test/HJSC03011.xlsx
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Monthly

### For how long do you plan to keep this dataset stored on Filecoin

2 to 3 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, Africa, North America

### How will you be distributing your data to storage providers

Cloud storage (i.e. S3), HTTP or FTP server, Shipping hard drives

### How do you plan to choose storage providers

Slack, Partners, Others

### If you answered "Others" in the previous question, what is the tool or platform you plan to use

```text
We'd like to use the FilSwan platform (https://filswan.com/) to find suitable storage providers.
```

### If you already have a list of storage providers to work with, fill out their names and provider IDs below

```text
Some storage providers from the FilSwan platform are:
f010088
f02301
f08399
f047419
f0187709
f01163272
f01402814
f0240185
f0143858
f0408717
f01225882
f0717969
f01211558
f03223
f01801091
f0240456
f032824
f01931631
f01907556
f01877184
f02003005
```

### How do you plan to make deals to your storage providers

Boost client, Lotus client, Others/custom tool

### If you answered "Others/custom tool" in the previous question, enter the details here

```text
We'd also like to use Swan Client to send our deals. Please refer to: https://github.com/filswan/go-swan-client#16-Create-A-Task
```

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
How many nodes do you have? It seems that the log file for each node contains about 1 MB data.

**Comment by freecodewu** [comment]
> How many nodes do you have? It seems that the log file for each node contains about 1 MB data.

@Sunnyiscoming We possess 5000+ nodes in China and 300+ in abroad. And the number of clients we serve reached 70 million per day (https://www.ppio.cn/). As of now, we already have about 200TiB of log files in total. Apus Network is operated and run by PPIO's oversea business team. Tik Tok and Kuaishou are our customers, and iQiyi and Bilibili use our overseas nodes.

**Comment by Sunnyiscoming** [comment]
Could you send an email to filplus-app-review@fil.org with your official domain in order to confirm your identity? Email name should includes the issue id #1574.

**Comment by freecodewu** [comment]
> Could you send an email to [filplus-app-review@fil.org](mailto:filplus-app-review@fil.org) with your official domain in order to confirm your identity? Email name should includes the issue id #1574. Hope to receive emails from the following organizations. https://apus.network/ https://www.ppio.cn/

@Sunnyiscoming Sent already. Please check. 
![image](https://user-images.githubusercontent.com/96016540/218377571-91aaf552-2630-4b84-bae8-bc4a1b027d45.png)

![image](https://user-images.githubusercontent.com/96016540/218377514-5a4c5472-0f39-4a88-b846-d2ed5d393dd5.png)

**Comment by simonkim0515** [comment]
## Datacap Request Trigger

#### Total DataCap requested 
> 5PiB

#### Expected weekly DataCap usage rate 
> 500TiB 

#### Client address
> f1jr3yfd367csao6k3x27643pnxxrz5cf6l7julmq

**Comment by kernelogic** [comment]
Same with cryptowhizzard, need to see proof of data.

**Comment by freecodewu** [comment]
> Dear applicant,
> 
> Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.
> 
> Can you show us visible proof of the size of your data and the storage systems you have there?
> 
> As last question i would like you to fill out [this form](https://form.jotform.com/230337462961356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.
> 
> Thanks!

@cryptowhizzard @kernelogic 

![image](https://user-images.githubusercontent.com/96016540/218954045-05fce95f-ea07-4634-aa91-a208685f2931.png)

Here is the data size proof. And we have already filled out the form. Please check.

**Comment by cryptowhizzard** [comment]
I received the KYC documents. Miners are from the FILswan plaform. 

I am ok with signing this for first round.

**Comment by cryptowhizzard** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedfn3d4lr3irntrslihkyaarwakboihbglwgcl5ehfgkzkyugjaj4 
#### Address 
> f1jr3yfd367csao6k3x27643pnxxrz5cf6l7julmq
#### Datacap Allocated
> 250.00TiB
#### Signer Address
> f1krmypm4uoxxf3g7okrwtrahlmpcph3y7rbqqgfa
#### Id
> 27c3e700-c51f-4a08-a152-33b8b12f9ca6
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedfn3d4lr3irntrslihkyaarwakboihbglwgcl5ehfgkzkyugjaj4

**Comment by kernelogic** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb4wqnckla2nayx4tgypsnzaoc7texqzcdpoarmi37fpud7pu7exg 
#### Address 
> f1jr3yfd367csao6k3x27643pnxxrz5cf6l7julmq
#### Datacap Allocated
> 250.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### Id
> 27c3e700-c51f-4a08-a152-33b8b12f9ca6
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb4wqnckla2nayx4tgypsnzaoc7texqzcdpoarmi37fpud7pu7exg

**Comment by Sunnyiscoming** [comment]
Hello, @freecodewu per the https://github.com/filecoin-project/notary-governance/issues/922 for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

This information will be reviewed by Fil+ Governance team to confirm validity and then the application will be allowed to move forward for additional notary review.
