### ISSUE TITLE
[DataCap Application] Protocol Labs - Evergreen (re-applying)

### ISSUE THREAD

**Issue by dkkapur** [filecoin-project/filecoin-plus-large-datasets#1576]
### Data Owner Name

Various open data sources (labs, research, etc.), primarily on Web2 cloud open data registries

### Data Owner Country/Region

United States

### Data Owner Industry

Not-for-Profit

### Website

https://evergreen.filecoin.io/ 

### Social Media

```text
https://protocol.ai/, https://slingshot.filecoin.io/, https://v2.slingshot.filecoin.io/,, https://evergreen.filecoin.io/
```

### Total amount of DataCap being requested

3PiB

### Weekly allocation of DataCap requested

1PiB

### On-chain address for first allocation

f1pkrmygbvweykpjcut36lf7ewgqdfhjklbhvepda

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Slingshot is a community competition for storage clients and developers that rewards the storage of real, valuable, and usable data on the Filecoin network. Slingshot v2 kicked off at the end of 2020, through which ~35 PiB of 61+ public open datasets have been onboarded to the Filecoin network. The Slingshot competition has effectively served as one of the largest data onboarding funnels in the Filecoin network, and has resulted in several learnings around deal making at scale, retrievals, data indexing and documentation of onboarded data. 

Protocol Labs has supported the Slingshot competition and will be the primary owner of the Slingshot Evergreen engine. Protocol Labs is an OSS R&D Lab, and was founded in 2014. Software developed by PL includes IPFS, Filecoin (lotus implementation), libp2p, drand, IPLD and more.
```

### Is this project associated with other projects/ecosystem stakeholders?

Yes

### If answered yes, what are the other projects/ecosystem stakeholders

```text
PL will be funding the development and operations of the Slingshot Evergreen engine.

This project is primarily associated with participants of the Slingshot community, and those with a vested interested in permanent archival of data on Filecoin (which could include key Filecoin stakeholders like developers of implementations, those working on the FVM, the Filecoin Foundation, and Storage Provider entities). Additionally, in some cases, owners of Slingshot datasets that we’ve collaborated with will also benefit from a permanent mirror of their datasets on the decentralized web.
```

### Describe the data being stored onto Filecoin

```text
Each of the Slingshot datasets come from reputable organizations where the licensing allows for public storage of the data. The full list of datasets that are eligible for Slingshot can be found [here](https://github.com/filecoin-project/slingshot/blob/master/datasets.md). The [Slingshot Data Explorer](https://slingshot.filecoin.io/explore) also has a list of datasets stored in the past.
```

### Where was the data currently stored in this dataset sourced from

Other

### If you answered "Other" in the previous question, enter the details here

```text
For long term archival through Evergreen - the data will be sourced from the Filecoin network. SPs interested in serving this data are expected to run retrievals to obtain pieces that can be re-stored in the future.

The original data was sourced directly from the organizations that own it or mirrors they support, which are linked to [here](https://github.com/filecoin-project/slingshot/blob/master/datasets.md).
```

### How do you plan to prepare the dataset

others/custom tool

### If you answered "other/custom tool" in the previous question, enter the details here

```text
It is technically up to the original Slingshot client representatives that prepared the data / current CIDs. Solutions typically included custom built libraries, open source libraries in the ecosystem, and other tooling like FileDrive.
```

### Please share a sample of the data

```text
Yes - here are some examples of datasets onboarded through Slingshot:
 Million Song Dataset    - http://millionsongdataset.com/
Boxy Vehicles Dataset - https://boxy-dataset.com/boxy/, https://github.com/karstenBehrendt/boxy 
Foldingathome COVID-19 Dataset - https://registry.opendata.aws/foldingathome-covid19/ 


The [Slingshot Data Explorer](https://slingshot.filecoin.io/explore) has a list of all the stored data along with the SPs that onboarded it, which can be used to source the data from Filecoin network directly.
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Weekly

### For how long do you plan to keep this dataset stored on Filecoin

Permanently

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, Africa, North America, South America, Europe, Australia (continent), Antarctica

### How will you be distributing your data to storage providers

HTTP or FTP server, Lotus built-in data transfer

### How do you plan to choose storage providers

Others

### If you answered "Others" in the previous question, what is the tool or platform you plan to use

```text
We plan for SPs interested in participating to fill out the [onboarding form](https://docs.google.com/forms/d/e/1FAIpQLSe5bpkD5RJeHGMNx3CpkV3a6UA2i7aroNE5DlGUdQF0mQU8DQ/viewform?usp=sf_link) in order to be eligible to receive deals from the Evergreen engine. This includes checking for location, miner IDs, and confirms their ability to service retrievals as required by the program. 

The Evergreen engine will plan to distribute up to 10 replicas for each piece of data that is expiring in deals made through Slingshot v2 (in the following 60d at any given point in time), with the following distribution requirements for replicas:
No more than one replica per city / datacenter
No more than two replicas per country
At least one replica in three different continents

The goal is to distribute these replicas both geographically and across SP organizations to increase the availability of the data in different regions, and improve long–term availability. 

Over time, the retrieval sampling we do will also be made available through the Filecoin Reputation System, and retrieval success rate will be used as a measure of reliable performance to enable future dealmaking from the Evergreen engine. SPs that do not serve retrievals as required by the program will not be eligible for future deals.
```

### How do you plan to make deals to your storage providers

Others/custom tool

### If you answered "Others/custom tool" in the previous question, enter the details here

```text
The Evergreen engine will be available as an API for registered SPs to reach out to, to request deal proposals for eligible piece CIDs that they would like to store a replica of. The goal is to distribute replicas across SP operators and regions, using the following heuristics:
Max 1 replica per datacenter/city
Max 2 replicas per Storage Provider organization
Max 2 replicas per country
Min 3 continents
```

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by dkkapur** [comment]
@ribasushi opening this one up instead of https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/293

**Comment by simonkim0515** [comment]
## Datacap Request Trigger

#### Total DataCap requested 
> 3PiB

#### Expected weekly DataCap usage rate 
> 1PiB 

#### Client address
> f1pkrmygbvweykpjcut36lf7ewgqdfhjklbhvepda

**Comment by dkkapur** [comment]
checker:manualTrigger

**Comment by dkkapur** [comment]
@s0nik42 @cryptowhizzard - new request, refiled the LDN app. can you give this one a shot if you have a chance? thank you.

**Comment by cryptowhizzard** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecdbl5rwvkbhxv7eajtbh6356r6h7ggl6dlaewsueu6rmntjsj342 
#### Address 
> f1pkrmygbvweykpjcut36lf7ewgqdfhjklbhvepda
#### Datacap Allocated
> 153.59TiB
#### Signer Address
> f1krmypm4uoxxf3g7okrwtrahlmpcph3y7rbqqgfa
#### Id
> cde022d1-d6b0-406c-913d-e05383706a1d
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecdbl5rwvkbhxv7eajtbh6356r6h7ggl6dlaewsueu6rmntjsj342

**Comment by kernelogic** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecabopme5dhtlwi6jmx3gci76vaskmxhrs5naldqfqlqlzu4hw3gg 
#### Address 
> f1pkrmygbvweykpjcut36lf7ewgqdfhjklbhvepda
#### Datacap Allocated
> 153.59TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### Id
> cde022d1-d6b0-406c-913d-e05383706a1d
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecabopme5dhtlwi6jmx3gci76vaskmxhrs5naldqfqlqlzu4hw3gg

**Comment by filplusapp** [comment]
checker:manualTrigger

**Comment by filplusapp** [comment]
results are crazy!!!

lotus client retrieve --provider f01853438 --pieceCid baga6ea4seaqlqo7mb4cwifhqzwmgu3g6cq2hbetknud6wmz26i5jxtcl4cch2li uAXCg5AIgT-Up8ecCOchoOB8F3ZJ9HGHZtikqV_qP8wKG1Pw3KhQ test.file
ERROR: offer error: retrieval query offer errored: failed to fetch piece to retrieve from: getting pieces for cid bafykbzacebh6kkpr44bdtsdihapqlxmspuogdwnwfevfp6up6mbinvh4g4vbi: getting pieces containing block bafykbzacebh6kkpr44bdtsdihapqlxmspuogdwnwfevfp6up6mbinvh4g4vbi: failed to lookup index for mh a0e402204fe529f1e70239c868381f05dd927d1c61d9b6292a57fa8ff30286d4fc372a14, err: datastore: key not found

lotus client retrieve --provider f01853438 --pieceCid baga6ea4seaqnmaptffjzsyw2hvuf7fklf4cgsihxaxjwq6fg6vq4dl7q2civqcq QmUH6qUAGMyd7MEkjbyUNipmeJ5k6GpKrjtzqDNqZXyPys test.file
ERROR: offer error: retrieval query offer errored: failed to fetch piece to retrieve from: getting pieces for cid QmUH6qUAGMyd7MEkjbyUNipmeJ5k6GpKrjtzqDNqZXyPys: getting pieces containing block QmUH6qUAGMyd7MEkjbyUNipmeJ5k6GpKrjtzqDNqZXyPys: failed to lookup index for mh 1220583d5713c8da598b352a943c58bf15ec5df2b94c72f01ce003aa95ef7816331a, err: datastore: key not found

**Comment by cryptowhizzard** [comment]
> results are crazy!!!
> 
> lotus client retrieve --provider f01853438 --pieceCid baga6ea4seaqlqo7mb4cwifhqzwmgu3g6cq2hbetknud6wmz26i5jxtcl4cch2li uAXCg5AIgT-Up8ecCOchoOB8F3ZJ9HGHZtikqV_qP8wKG1Pw3KhQ test.file ERROR: offer error: retrieval query offer errored: failed to fetch piece to retrieve from: getting pieces for cid bafykbzacebh6kkpr44bdtsdihapqlxmspuogdwnwfevfp6up6mbinvh4g4vbi: getting pieces containing block bafykbzacebh6kkpr44bdtsdihapqlxmspuogdwnwfevfp6up6mbinvh4g4vbi: failed to lookup index for mh a0e402204fe529f1e70239c868381f05dd927d1c61d9b6292a57fa8ff30286d4fc372a14, err: datastore: key not found
> 
> lotus client retrieve --provider f01853438 --pieceCid baga6ea4seaqnmaptffjzsyw2hvuf7fklf4cgsihxaxjwq6fg6vq4dl7q2civqcq QmUH6qUAGMyd7MEkjbyUNipmeJ5k6GpKrjtzqDNqZXyPys test.file ERROR: offer error: retrieval query offer errored: failed to fetch piece to retrieve from: getting pieces for cid QmUH6qUAGMyd7MEkjbyUNipmeJ5k6GpKrjtzqDNqZXyPys: getting pieces containing block QmUH6qUAGMyd7MEkjbyUNipmeJ5k6GpKrjtzqDNqZXyPys: failed to lookup index for mh 1220583d5713c8da598b352a943c58bf15ec5df2b94c72f01ce003aa95ef7816331a, err: datastore: key not found

Perhaps you should try a Nintendo instead of a computer, it will greatly improve your mission for throwing m00t in the community.

Anyway, the deals you refer to are just appearing on chain and need some days to get sealed. Secondly you are bashing the Evergreen project of protocol labs itself.

**Comment by underway2014** [comment]
checker:manualTrigger

**Comment by underway2014** [comment]
checker:manualTrigger

**Comment by Joss-Hua** [comment]
checker:manualTrigger
