### ISSUE TITLE
[DataCap Application] <RongYIn Open Data Project 1>

### ISSUE THREAD

**Issue by datalove2** [filecoin-project/filecoin-plus-large-datasets#1579]
### Data Owner Name

RongYIn Open Data Project 1

### Data Owner Country/Region

China

### Data Owner Industry

IT & Technology Services

### Website

https://www.qcc.com/firm/3380acbb3101bd58394d1ba4be51e877.html

### Social Media

```text
https://www.qcc.com/firm/3380acbb3101bd58394d1ba4be51e877.html
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

500TiB

### On-chain address for first allocation

f1es3jnh7ivhvc32s23mro7wuktehjkxlc7yjac6a

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
RongYin was established in 2019 in HK. We were provided with a storage capacity in total of 100PiB. Now, we are planning to engage in onboard humanity data which is useful for the network. <RongYin Open Data Project> estimated onboard 10PiB storage capacity to the network, which is about 1.5P raw data.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
We are going to onboard open data of agriculture from AWS. 
Agriculture datasets covers 86 matching datasets. In total about 5PiB. 
Including USGS Landsat, NOAA, ESA WorldCover, Digital Earth Africa, Rice Genomes Project, SILO Climate data and so on.
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### How do you plan to prepare the dataset

IPFS, lotus, singularity, graphsplit

### Please share a sample of the data

```text
https://registry.opendata.aws/deafrica-geomad/
https://registry.opendata.aws/deafrica-wofs/
https://registry.opendata.aws/afsis/
https://registry.opendata.aws/3kricegenome/
https://registry.opendata.aws/isdasoil/
https://registry.opendata.aws/noaa-goes
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

1.5 to 2 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, South America, Europe, Australia (continent)

### How will you be distributing your data to storage providers

HTTP or FTP server, IPFS, Shipping hard drives, Lotus built-in data transfer

### How do you plan to choose storage providers

Slack, Big data exchange, Partners

### If you already have a list of storage providers to work with, fill out their names and provider IDs below

```text
In communicating
```

### How do you plan to make deals to your storage providers

Boost client, Lotus client, Singularity

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by lvschouwen** [comment]
Yesterday this same application was filed under #1577 and #1578 by Github user ledecaevi.
Both applications are deleted.
@datalove2, can you please explain what the relation is here?

![image](https://user-images.githubusercontent.com/6965171/216308684-7bcca977-447b-49aa-8848-6626cdf25aaa.png)

**Comment by datalove2** [comment]
Hi there,
The Github handle" ledecaevi" is also one of mine. I resubmitted an
application because " ledecaevi"  was flagged as "participate in the mining
project" by Github Team. I have appealed to the GitHub Team for the
specific reason.

lvschouwen ***@***.***> 於 2023年2月2日 星期四寫道：

**Comment by Sunnyiscoming** [comment]
Data samples you provided are mentioned in the following applications. How many duplicates are there?
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1123
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1130
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/3
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/46
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/136
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1112
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1488
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1489
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1490
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1491

**Comment by datalove2** [comment]
@Sunnyiscoming Thank you for your reminder. This is a matter worth
discussing. The <RongYin Open Data Project> is planned to bring valuable
open datasets to the network based on our storage capabilities. We
carefully selected these datasets as our first phase plan and submitted the
application after the preliminary preparations were mostly completed.
After my confirmation, there was no clear requirement for the network to
backup these AWS datasets stored. I'm also curious about this requirement
and it would be great if you could provide any suggestions.

Sunnyiscoming ***@***.***> 於 2023年2月5日 星期日寫道：

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Can you show us visible proof of the size of your data and the storage systems you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230337462961356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!

**Comment by simonkim0515** [comment]
## Datacap Request Trigger

#### Total DataCap requested 
> 5PiB

#### Expected weekly DataCap usage rate 
> 500TiB 

#### Client address
> f1es3jnh7ivhvc32s23mro7wuktehjkxlc7yjac6a

**Comment by herrehesse** [comment]
Dear Filecoin+ Github applicant,

We have noticed that some of you are submitting merged datacap requests for datasets that are already (partly) on the chain. While we appreciate your enthusiasm to contribute to the Filecoin network, we want to remind you that this behaviour may not be beneficial to the network in the long run. In fact, this behaviour has been questioned and discussed in issue https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/832 on the Filecoin notary-governance Github repository.

We encourage you to review the discussions in issue https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/832. It's important to ensure that your datacap requests are valid, necessary, and add value to the network. By doing so, you can help to maintain the integrity and sustainability of the Filecoin network.

You can find the link to issue https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/832 here: https://github.com/filecoin-project/notary-governance/issues/832

Thank you for your understanding and cooperation.

**Comment by kernelogic** [comment]
@datalove2 although there is no rule against merged datasets currently, but how do you plan to make the data available for public to use? Do you have your own website to perform indexing of these different datasets?

**Comment by datalove2** [comment]
@herrehesse Thanks for the reminder.
@kernelogic Thanks for the review. First of all, all the data we store will
be retrievable, and we have optimized the efficiency of data retrieval to
support fast retrieval. If you'd like to support us, you can review the
data after data has been uploaded.

Fei Yan ***@***.***> 於 2023年2月28日 星期二寫道：

**Comment by kernelogic** [comment]
For example, if I want to retrieve 3kricegenome, how do I know which CIDs belong to this dataset? Will you provide a list?

**Comment by datalove2** [comment]
@kernelogic
We will record the data with tags to distinguish different project data. In
addition we will also provide a list of CIDs.

Fei Yan ***@***.***> 於 2023年2月28日 星期二寫道：

**Comment by kernelogic** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceael6yjkgibwgsm2hwlz3gnsvhtsezype7ylslfjlkcacx5a7bcsw 
#### Address 
> f1es3jnh7ivhvc32s23mro7wuktehjkxlc7yjac6a
#### Datacap Allocated
> 250.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### Id
> e01dc661-fcec-415b-b14b-58818b8665d0
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceael6yjkgibwgsm2hwlz3gnsvhtsezype7ylslfjlkcacx5a7bcsw

**Comment by Tom-OriginStorage** [comment]
Which SPs have you contacted? Please list them and their distribution areas

**Comment by datalove2** [comment]
@Tom-OriginStorage，
Hi there, Here are some SPs we found, and the number of SPs will be
increased with more allocation.
f01896036 US; f02037700 KR; f02047841 CN; f02024315 Thailand; f01834253 US;
f01853077 SG...

Tom-OriginStorage ***@***.***> 於 2023年2月28日 星期二寫道：

**Comment by Tom-OriginStorage** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaf2mpdp3zv7uncrbbcyzeru2had2wniqzilqx6zisnqx3f36v3jk 
#### Address 
> f1es3jnh7ivhvc32s23mro7wuktehjkxlc7yjac6a
#### Datacap Allocated
> 250.00TiB
#### Signer Address
> f1q6bpjlqia6iemqbrdaxr2uehrhpvoju3qh4lpga
#### Id
> e01dc661-fcec-415b-b14b-58818b8665d0
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaf2mpdp3zv7uncrbbcyzeru2had2wniqzilqx6zisnqx3f36v3jk

**Comment by laurarenpanda** [comment]
> **Since this is the 3rd allocation, the following restrictions have been relaxed:**
> - No more than 70% of unique data are stored with less than 3 providers.
> 
> ✔️ Data replication looks healthy.
> 
> | Unique Data Size | Total Deals Made | Number of Providers | Deal Percentage |
> | ---------------: | ---------------: | ------------------: | --------------: |
> |       229.19 TiB |       229.19 TiB |                   1 |          59.03% |
> |        15.81 TiB |        31.63 TiB |                   2 |           8.14% |
> |        21.75 TiB |        65.25 TiB |                   3 |          16.80% |
> |         9.97 TiB |        39.88 TiB |                   4 |          10.27% |
> |         4.47 TiB |        22.34 TiB |                   5 |           5.75% |
> 
> <img src="https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/1579/1679647450344.png"/>

The unbalanced data distribution is acceptable in the first three rounds.
But I personally recommend paying more attention to the Checker report, and please try to find more SPs in different locations.
Would like to know more about your future plan.

**Comment by flyworker** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebrz6472agrs3d322nqlf6w7bqh2z7vgnv6cfjb2du2rqwosaw7qq 
#### Address 
> f1es3jnh7ivhvc32s23mro7wuktehjkxlc7yjac6a
#### Datacap Allocated
> 500.00TiB
#### Signer Address
> f1hlubjsdkv4wmsdadihloxgwrz3j3ernf6i3cbpy
#### Id
> 1f5ba341-65a7-4e76-b991-1fd7d40f28a1
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebrz6472agrs3d322nqlf6w7bqh2z7vgnv6cfjb2du2rqwosaw7qq

**Comment by luobin544** [comment]
checker:manualTrigger

**Comment by luobin544** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec74oqfsmtv6yj44inhoiispkdgnredmpvyue2aaemntyj4dnjxfc 
#### Address 
> f1es3jnh7ivhvc32s23mro7wuktehjkxlc7yjac6a
#### Datacap Allocated
> 500.00TiB
#### Signer Address
> f1tbd632f6w62glfaf7wjpimacbnjiz26poyoes2q
#### Id
> 1f5ba341-65a7-4e76-b991-1fd7d40f28a1
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec74oqfsmtv6yj44inhoiispkdgnredmpvyue2aaemntyj4dnjxfc

**Comment by xingjitansuo** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebe6gs2acrss4ihre4h3u3quklf2powvthwynrc3kgm5o6jlj2hbc 
#### Address 
> f1es3jnh7ivhvc32s23mro7wuktehjkxlc7yjac6a
#### Datacap Allocated
> 1.95PiB
#### Signer Address
> f1a2lia2cwwekeubwo4nppt4v4vebxs2frozarz3q
#### Id
> 1348b904-e877-4545-a29f-b477b4b6cb58
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebe6gs2acrss4ihre4h3u3quklf2powvthwynrc3kgm5o6jlj2hbc

**Comment by sxxfuture-official** [comment]
checker:manualTrigger

**Comment by sxxfuture-official** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecnjuzoovihnkkq7yauyfm5ll7tt7xc67zazcojnr4p5axwbg3x7o 
#### Address 
> f1es3jnh7ivhvc32s23mro7wuktehjkxlc7yjac6a
#### Datacap Allocated
> 1.95PiB
#### Signer Address
> f1foiomqlmoshpuxm6aie4xysffqezkjnokgwcecq
#### Id
> 1348b904-e877-4545-a29f-b477b4b6cb58
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecnjuzoovihnkkq7yauyfm5ll7tt7xc67zazcojnr4p5axwbg3x7o

**Comment by zcfil** [comment]
checker:manualTrigger

**Comment by mikezli** [comment]
lotus client retrieve --provider f01854080 --pieceCid baga6ea4seaqggenwkzclg2dtnp6jijwicbqi4llt4aslo75kuhstoizfh3j6mcq       bafykbzacebmkzuqtlib52xe5mvojlqzmb3ovjjztjncrzqez33qqutpuntwq4 ~/
![ca6e22a29657696312b707c39ef5b01](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/118169683/14ddabe1-9c3d-4dea-aead-0ff2cbf41b44)
The customer contacted me and explained to me the reasons for CID sharing and retrieval. I am willing to support customers in this round for the time being, and I will keep paying attention.

**Comment by mikezli** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedv3ap5kvtpkb62icr4q7vswvfljeyc66serjksqhk6xtwdmmowpw 
#### Address 
> f1es3jnh7ivhvc32s23mro7wuktehjkxlc7yjac6a
#### Datacap Allocated
> 1.95PiB
#### Signer Address
> f1dnb3uz7sylxk6emti3ififcvu3nlufnnsjui6ea
#### Id
> 1348b904-e877-4545-a29f-b477b4b6cb58
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedv3ap5kvtpkb62icr4q7vswvfljeyc66serjksqhk6xtwdmmowpw
