### ISSUE TITLE
[DataCap Application] <RongYIn Open Data Project 2> 

### ISSUE THREAD

**Issue by datalove2** [filecoin-project/filecoin-plus-large-datasets#1580]
### Data Owner Name

RongYIn Open Data Project 2

### Data Owner Country/Region

China

### Data Owner Industry

IT & Technology Services

### Website

https://www.qcc.com/firm/3380acbb3101bd58394d1ba4be51e877.html

### Social Media

```text
https://www.qcc.com/firm/3380acbb3101bd58394d1ba4be51e877.html
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

500TiB

### On-chain address for first allocation

f13prg74xg56peezyogauhkbomx4x4jzajyczh34q

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
RongYin was established in 2019 in HK. We were provided with a storage capacity in total of 100PiB. Now, we are planning to engage in onboard humanity data which is useful for the network. <RongYin Open Data Project> estimated onboard 10PiB storage capacity to the network, which is about 1.5P raw data.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
We are going to onboard open data of agriculture from AWS. 
Agriculture datasets covers 86 matching datasets. In total about 5PiB. 
Including USGS Landsat, NOAA, ESA WorldCover, Digital Earth Africa, Rice Genomes Project, SILO Climate data and so on.
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### How do you plan to prepare the dataset

IPFS, lotus, singularity, graphsplit

### Please share a sample of the data

```text
https://registry.opendata.aws/deafrica-geomad/
https://registry.opendata.aws/deafrica-wofs/
https://registry.opendata.aws/afsis/
https://registry.opendata.aws/3kricegenome/
https://registry.opendata.aws/isdasoil/
https://registry.opendata.aws/noaa-goes
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

1.5 to 2 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, South America, Europe, Australia (continent)

### How will you be distributing your data to storage providers

HTTP or FTP server, IPFS, Shipping hard drives, Lotus built-in data transfer

### How do you plan to choose storage providers

Slack, Big data exchange, Partners

### If you already have a list of storage providers to work with, fill out their names and provider IDs below

```text
In communicating
```

### How do you plan to make deals to your storage providers

Boost client, Lotus client, Singularity

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by simonkim0515** [comment]
## Datacap Request Trigger

#### Total DataCap requested 
> 5PiB

#### Expected weekly DataCap usage rate 
> 500TiB 

#### Client address
> f13prg74xg56peezyogauhkbomx4x4jzajyczh34q

**Comment by herrehesse** [comment]
Dear Filecoin+ Github applicant,

We have noticed that some of you are submitting merged datacap requests for datasets that are already (partly) on the chain. While we appreciate your enthusiasm to contribute to the Filecoin network, we want to remind you that this behaviour may not be beneficial to the network in the long run. In fact, this behaviour has been questioned and discussed in issue https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/832 on the Filecoin notary-governance Github repository.

We encourage you to review the discussions in issue https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/832. It's important to ensure that your datacap requests are valid, necessary, and add value to the network. By doing so, you can help to maintain the integrity and sustainability of the Filecoin network.

You can find the link to issue https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/832 here: https://github.com/filecoin-project/notary-governance/issues/832

Thank you for your understanding and cooperation.

**Comment by kernelogic** [comment]
DD performed in https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1579#issuecomment-1447513010

**Comment by kernelogic** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced7sjtrppbl2m6q2nbuwgo26te5w5xy6p2a4xjwj6jv2idgbysddo 
#### Address 
> f13prg74xg56peezyogauhkbomx4x4jzajyczh34q
#### Datacap Allocated
> 250.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### Id
> 89596cc0-2f7b-45a3-8c94-9a43c5e36f32
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced7sjtrppbl2m6q2nbuwgo26te5w5xy6p2a4xjwj6jv2idgbysddo

**Comment by Tom-OriginStorage** [comment]
DD performed in 1579

**Comment by Tom-OriginStorage** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced7uezpfnwidokiednbr3e7xke636k4rt6sf2zlnnozgsq7bg75d6 
#### Address 
> f13prg74xg56peezyogauhkbomx4x4jzajyczh34q
#### Datacap Allocated
> 250.00TiB
#### Signer Address
> f1q6bpjlqia6iemqbrdaxr2uehrhpvoju3qh4lpga
#### Id
> 89596cc0-2f7b-45a3-8c94-9a43c5e36f32
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced7uezpfnwidokiednbr3e7xke636k4rt6sf2zlnnozgsq7bg75d6

**Comment by flyworker** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaw6ggcdzmzovyrvt4xdsqckqukqgncocfuozuhim4coa7npljuzy 
#### Address 
> f13prg74xg56peezyogauhkbomx4x4jzajyczh34q
#### Datacap Allocated
> 500.00TiB
#### Signer Address
> f1hlubjsdkv4wmsdadihloxgwrz3j3ernf6i3cbpy
#### Id
> f2e2b36d-f439-41a2-a3dc-f48a5391dc50
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaw6ggcdzmzovyrvt4xdsqckqukqgncocfuozuhim4coa7npljuzy

**Comment by luobin544** [comment]
checker:manualTrigger

**Comment by luobin544** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceboesruocj6gmy7cuab5q37hde3t66orpsds3qjqddmitk6opdksg 
#### Address 
> f13prg74xg56peezyogauhkbomx4x4jzajyczh34q
#### Datacap Allocated
> 500.00TiB
#### Signer Address
> f1tbd632f6w62glfaf7wjpimacbnjiz26poyoes2q
#### Id
> f2e2b36d-f439-41a2-a3dc-f48a5391dc50
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceboesruocj6gmy7cuab5q37hde3t66orpsds3qjqddmitk6opdksg

**Comment by NDLABS-OFFICE** [comment]
checker:manualTrigger

**Comment by fireflyHZ** [comment]
Select a miner retrieval query and it looks fine.
<img width="1044" alt="mmexport1681899093202" src="https://user-images.githubusercontent.com/100905326/233044520-dbdc113f-b240-45df-adb6-5010bf61d62c.png">

**Comment by fireflyHZ** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceamrj3ekoxn2yvkcpu6lhp2gsjezggnjfq6ylkourp7kh2ikyammy 
#### Address 
> f13prg74xg56peezyogauhkbomx4x4jzajyczh34q
#### Datacap Allocated
> 1000.00TiB
#### Signer Address
> f1fg6jkxsr3twfnyhdlatmq36xca6sshptscds7xa
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceamrj3ekoxn2yvkcpu6lhp2gsjezggnjfq6ylkourp7kh2ikyammy

**Comment by kernelogic** [comment]
DD performed perviously. CID checker result looks good.

**Comment by kernelogic** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedfcotmmkfanb5e4abuxf55ojclzcrilt5favjya62zmvgrnycoq6 
#### Address 
> f13prg74xg56peezyogauhkbomx4x4jzajyczh34q
#### Datacap Allocated
> 1000.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedfcotmmkfanb5e4abuxf55ojclzcrilt5favjya62zmvgrnycoq6

**Comment by 1ane-1** [comment]
checker:manualTrigger

**Comment by 1ane-1** [comment]
@datalove2 Pay attention:No more than 30% of unique data are stored with less than 4 providers.
Please explain CID sharing problem.

**Comment by 1ane-1** [comment]
<img width="990" alt="38be716bd3e58a8f672f396050a1908" src="https://user-images.githubusercontent.com/91301211/236109324-782c4793-d4d0-42ff-a017-39ac15d47b12.png">
<img width="1107" alt="76565983e6101af09dcf54d2819893c" src="https://user-images.githubusercontent.com/91301211/236109341-a4581233-f6d3-4766-a9c0-301136d2282b.png">

**Comment by datalove2** [comment]
Thanks for asking the question.

“During our regular check, there was some CID sharing between some LDNs
that we are not aware of. We have located the mistaken SPs
(f02000936&f02006374) requiring them to stop data onboarding and hopefully
give the solution for this mistake they made. until then, we will not send
deals to them.
We and ND are cooperative sps, because the same problem caused some LDNs to
have data sharing records, but this problem has been found and resolved,
but the shared data still has records.
we are always monitoring the data for issues. Hope we can get your support!

In addition, the problem of data backup is because the progress of each sp
is different, and it will eventually comply with the rules of the
governance team.

Anne ***@***.***> 於 2023年5月4日 週四 上午11:44寫道：

**Comment by 1ane-1** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaf7ilv7kvnqynbikrn2hxj4rimjiahhiuowri2kn3swfzppngvc6 
#### Address 
> f13prg74xg56peezyogauhkbomx4x4jzajyczh34q
#### Datacap Allocated
> 1.95PiB
#### Signer Address
> f1mdk7s2vntzm6hu35yuo6vjubtrpfnb2awhgvrri
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaf7ilv7kvnqynbikrn2hxj4rimjiahhiuowri2kn3swfzppngvc6

**Comment by xingjitansuo** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacechj3y3ykkoqhs2dloylepacwkw5j2kzctppf2pxvcjyk44ra3js6 
#### Address 
> f13prg74xg56peezyogauhkbomx4x4jzajyczh34q
#### Datacap Allocated
> 1.95PiB
#### Signer Address
> f1a2lia2cwwekeubwo4nppt4v4vebxs2frozarz3q
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacechj3y3ykkoqhs2dloylepacwkw5j2kzctppf2pxvcjyk44ra3js6

**Comment by sxxfuture-official** [comment]
checker:manualTrigger

**Comment by sxxfuture-official** [comment]
Refer to my reply in #1579

**Comment by sxxfuture-official** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceam5qlyopto5dwj4uyf75uovvlcgp4dbbmvfyxu4swv5q2nzmuzys 
#### Address 
> f13prg74xg56peezyogauhkbomx4x4jzajyczh34q
#### Datacap Allocated
> 1.34PiB
#### Signer Address
> f1foiomqlmoshpuxm6aie4xysffqezkjnokgwcecq
#### Id
> d7fd1696-2ea6-4def-b780-40ebf1a2d17e
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceam5qlyopto5dwj4uyf75uovvlcgp4dbbmvfyxu4swv5q2nzmuzys

**Comment by zcfil** [comment]
checker:manualTrigger

**Comment by mikezli** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebqkn3e2y5v2j3halwts42zyxedtt75ehqle7gds643g4pc2ubvvi 
#### Address 
> f13prg74xg56peezyogauhkbomx4x4jzajyczh34q
#### Datacap Allocated
> 1.34PiB
#### Signer Address
> f1dnb3uz7sylxk6emti3ififcvu3nlufnnsjui6ea
#### Id
> d7fd1696-2ea6-4def-b780-40ebf1a2d17e
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebqkn3e2y5v2j3halwts42zyxedtt75ehqle7gds643g4pc2ubvvi
