### ISSUE TITLE
[DataCap Application] Shenzhen Bowen Big Data Technology Co., Ltd. - BWN

### ISSUE THREAD

**Issue by changelo** [filecoin-project/filecoin-plus-large-datasets#1582]
### Data Owner Name

Shenzhen Bowen Big Data Technology Co., Ltd

### Data Owner Country/Region

China

### Data Owner Industry

IT & Technology Services

### Website

http://www.bowenbigdata.com/

### Social Media

```text
http://www.bowenbigdata.com/
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

500TiB

### On-chain address for first allocation

f3rtlqil5ymgcck7itpv37cs744tpvhcpypa5mpqmcujuyb5zkmtsklohkf6llh7hrfnkz3632pycqumawbp3a

### Custom multisig

- [x] Use Custom Multisig

### Identifier

efil

### Share a brief history of your project and organization

```text
Shenzhen Bowen Big Data Technology Co., Ltd founded in September 2021, is a professional supply block chain service provider. Engaged in software and services related to blockchain technology; Big data service; Software development; Basic software development of artificial intelligence; Data processing and storage support services; Information technology consulting services; Data processing service; Cloud computing equipment technology services; Retail of computer software, hardware and auxiliary equipment; Software sales; Cloud computing equipment sales; Sales of IoT equipment; Sales of calculator equipment; Information system integration services.
The Bowen Netdisk (BWN) is file management and sharing system base IPFS distributed storage. 

Features:
	Upload/download supports direct client transmission and download speed limit.
	The offline download of Aria2 is integrated, and multiple slave nodes can be used to share the download task.
	Online compression/decompression, multi file packaging and downloading.
	WebDAV protocol support covering all storage policies.
	Drag upload, directory upload, streaming upload processing.
	File drag management.
	Multiuser, user group.
	Create sharing links of files and directories, and set automatic expiration.
	Online preview of video, image, audio, text and office document.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
File types include text, pictures, audio, video and other types.
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### How do you plan to prepare the dataset

graphsplit

### Please share a sample of the data

```text
Yes - here some examples of datasets onboarded through http://disk.bowenbigdata.com
http://disk.bowenbigdata.com/s/rEH0
http://disk.bowenbigdata.com/s/x9T4
http://disk.bowenbigdata.com/s/wRSz
http://disk.bowenbigdata.com/s/y7Uz
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [ ] I confirm

### If you chose not to confirm, what was the reason

```text
The dataset contains two parts, one is private and encrypted, and the other is public, both of which can provide retrieval, and the public dataset can be retrieved by anyone on the Network.
```

### What is the expected retrieval frequency for this data

Daily

### For how long do you plan to keep this dataset stored on Filecoin

Permanently

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China

### How will you be distributing your data to storage providers

HTTP or FTP server

### How do you plan to choose storage providers

Partners

### If you already have a list of storage providers to work with, fill out their names and provider IDs below

```text

| Miner ID | Business Name | Location | Copies |
| f0427989 | Qingdao Pangu Kaiyuan Electronic Technology Development Co., Ltd  | China/Qingdao | 1 |
| f01123232 | Shenzhen Bowen Big Data Technology Co., Ltd | China/Shenzhen | 1 |
| f01302086 | Xi'an Taidi Electromechanical Engineering Co., Ltd | China/Shenzhen | 1|
| f01076644 | Jiangsu Shuozhen Cloud Network Technology Co., Ltd | China/Jiangsu | 1|
```

### How do you plan to make deals to your storage providers

Lotus client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Can you show us visible proof of the size of your data and the storage systems you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230232885049356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!

**Comment by herrehesse** [comment]
@changelo Can you please try to describe your project with a title as requested:

**Organization & Project Name** _(you can edit this above the application)_

**Comment by Sunnyiscoming** [comment]
> the private files are encrypted before save to filecoin

Does the data to be stored contain encrypted data?

Can you provide more data samples to prove that you have 5 PB data? How many copies you will store?
Could you send an email to filplus-app-review@fil.org with your official domain in order to confirm your identity? Email name should includes the issue id #1582.

**Comment by changelo** [comment]
The KYC form to be provided has filled in the necessary information.

**Comment by herrehesse** [comment]
@changelo Hello applicant, can you provide me with a list of business names and location of the SP's you provided for our due diligence?

_f01396338,f01302086,f01076644,f0222811,f0427989_

**Comment by changelo** [comment]
f01396338 does not participate in storage temporarily. We are also looking for other SPs willing to cooperate in Slack, Big data exchange.
| ID | Business Name | Location |
| --- | --- | --- |
| f0427989 | Qingdao Pangu Kaiyuan Electronic Technology Development Co., Ltd | China/Qingdao |
| f01123232 | Shenzhen Bowen Big Data Technology Co., Ltd | China/Hongkong |
| f01302086 | Xi'an Taidi Electromechanical Engineering Co., Ltd | China/Xian |
| f01076644 | Jiangsu Shuozhen Cloud Network Technology Co., Ltd | China/Jiangsu |

**Comment by kevzak** [comment]
> The KYC form to be provided has filled in the necessary information.

Yes, I can confirm that Shenzhen Bowen Big Data has completed a full Client Registration (KYC) and Business verification (KYB) check via the synaps.io product.

**Comment by kevzak** [comment]
> @herrehesse Dear Notary,
> 
> f01396338 does not participate in storage temporarily. We are also looking for other SPs willing to cooperate in Slack, Big data exchange.
> 
> ID	Business Name	Location
> f0427989	Qingdao Pangu Kaiyuan Electronic Technology Development Co., Ltd	China/Qingdao
> f01123232	Shenzhen Bowen Big Data Technology Co., Ltd	China/Hongkong
> f01302086	Xi'an Taidi Electromechanical Engineering Co., Ltd	China/Xian
> f01076644	Jiangsu Shuozhen Cloud Network Technology Co., Ltd	China/Jiangsu

@changelo here is [a list of E-Fil working group SPs.](https://docs.google.com/spreadsheets/d/1rwT9ie6qlOM9hVUkYZLGej523X1pMenaVKhFuvQOiNE/edit#gid=442291216) Feel free to reach them in Slack

**Comment by changelo** [comment]
> > the private files are encrypted before save to filecoin
> 
> Does the data to be stored contain encrypted data?
> 
> Can you provide more data samples to prove that you have 5 PB data? How many copies you will store? Could you send an email to [filplus-app-review@fil.org](mailto:filplus-app-review@fil.org) with your official domain in order to confirm your identity? Email name should includes the issue id #1582.

Hi [Sunnyiscoming](https://github.com/Sunnyiscoming), Thanks for your review! The email with our official domain was sent.

**Comment by changelo** [comment]
@kevzak 
Dear notary,

Thanks for your advice! 
Is my application still in progress? 
We are ready with the storage plan, please trigger notaries to review. Thanks!

**Comment by kevzak** [comment]
> > > the private files are encrypted before save to filecoin
> > 
> > 
> > Does the data to be stored contain encrypted data?
> > Can you provide more data samples to prove that you have 5 PB data? How many copies you will store? Could you send an email to [filplus-app-review@fil.org](mailto:filplus-app-review@fil.org) with your official domain in order to confirm your identity? Email name should includes the issue id #1582.
> 
> Hi [Sunnyiscoming](https://github.com/Sunnyiscoming), Thanks for your review! The email with our official domain was sent.

@Sunnyiscoming did they email you? Can you forward to me? @changelo I was waiting for a representative from Big Bowen Data to email me. Please confirm, thanks

**Comment by changelo** [comment]
Hi notaries!

@Sunnyiscoming  Could you confirm that email was sent?

@kevzak Need me to send that email to you again?

**Comment by kevzak** [comment]
yes please reply to my email @changelo

**Comment by changelo** [comment]
@kevzak Could you provider your email addresss? Thanks.

**Comment by kevzak** [comment]
I emailed the business contact, Evelan, they should check there. @changelo

**Comment by changelo** [comment]
Thanks for your supports! Business contact, Evelan will reply the email as soon as possible. @kevzak

**Comment by changelo** [comment]
Hi @Carohere 

I would like to provide the proof on the size of dataset. On the websit through the following link [http://disk.bowenbigdata.com/share](url), you can see the detailed dataset information.

The number of copies we plan to store is 3-4. Thank you!

**Comment by Carohere** [comment]
Appreciate the details. Given all miners are in one region, it doesn't fit the scope of decentralized allocation. I won't be able to sign this application.

**Comment by kevzak** [comment]
@Carohere - just an FYI for you, the https://github.com/filecoin-project/notary-governance/discussions/583#discussioncomment-5165924 is in regards to greater than 5PiB requests (which we will pilot soon). It was not directly for this application, although it doesn't hurt.

**Comment by kevzak** [comment]
Regarding miners in one region. I will reshare the [best practice guidelines](https://github.com/filecoin-project/filecoin-plus-large-datasets): 
_Best practice for storing large datasets includes ideally, storing it in 3 or more regions, with 4 or more storage provider operators or owners, and having at least 5 replicas of the dataset. No more than one replica should be stored with one SP ID, and if the data cannot leave a particular geographic boundary, then it is expected that replication will still happen across different locations (cities, datacenters, etc.). Each storage provider should not exceed 30% of the total datacap that the client was allocated and the storage provider should have published its public IP address. If you cannot follow these practices due to policy or any other issues, you may explain your case in the application and provide to the community what method you can do instead. These are recommendations and not strict rules that every client must follow_.

@changelo you technically do not need to store outside of China as stated above, however if you chose not to store elsewhere, please state why, and then also please confirm the locations you have listed are spread. I believe this will help in notary support.. If you which to spread distribution and need help finding SPs in other regions we can help.

**Comment by changelo** [comment]
| ID | Datacenter Location |
| --- | --- |
| f0427989 | China/Qingdao |
| f01123232 | China/Shenzhen |
| f01302086 | China/Shenzhen |
| f01076644 | China/Jiangsu |

@kevzak  It should be noted that the public IP address of f01123232 belongs to Hong Kong, but the datacenter is located in Shenzhen. At present, we are discussing cooperation with a storage provider in Chongqing. In this case, there will be more than 4 storage providers in different cities (data centers)

**Comment by changelo** [comment]
Hi @kevzak Due to geographical constraints, if the storage provider is located in other regions outside of China, it can only transfer 1728GB of data per day based on the bandwidth transmission rate of 20MB/s. It will take about 4 months to transfer 200TB of data. In this way, it is too inefficient, and it also needs to pay a high bandwidth fee. If storage providers are all in China, dataset can be copied to hard disks offline and then mail them to storage providers, which is more efficient. Therefore, storage providers we are looking for are located in China as far as possible.

**Comment by laurarenpanda** [comment]
Since this is an E-FIL+ program, the data owner's needs should be given priority.
So I can support this program even if all data will be stored only inside China, which could also be easier for data transmission like @changelo mentioned.

And I have a little bit confused about the following:
> Confirm that this is a public dataset that can be retrieved by anyone on the Network
> If you chose not to confirm, what was the reason
> the private files are encrypted before save to filecoin, so this is a publicly retrievable public dataset and all the files have.

In case of any misunderstanding, please make it clear.
Is this program an E-FIL+ program for encrypted private data from Shenzhen Bowen Big Data Technology Co., Ltd, which also require public retrieval provided by SPs to meet daily retrieval needs?

**Comment by changelo** [comment]
@laurarenpanda 
Sorry about that the answer to the previous question was not explained clearly.
The dataset contains two parts, one is private and encrypted, and the other is public, both of which need to provide retrieval.

**Comment by Joss-Hua** [comment]
oh, sorry, I'm just picked up this email carefully in my mailbox recycle bin. I missed it.
Thank @kevzak and @derricktan23 for their work. I'll waiting for the next assignment.

**Comment by Tom-OriginStorage** [comment]
@changelo 
Hi there!  I was wondering, have you applied for datacap in Filecoin space for either EFIL+ or Fil+, before using different Github account names, or is this your first time? 
I noticed that in a previous link you applied for 2 PiB. 
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1003

Could you tell me more about why you need 5 PiB this time and maybe share some details about the amount of data you have? Thanks!

**Comment by derricktan23** [comment]
@changelo Hi there! I was wondering, have you applied for datacap in Filecoin space for either EFIL+ or Fil+, before using different Github account names, or is this your first time?

I noticed that in a previous link you applied for 2 PiB.

[[#1003](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1003)](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1003)

Could you tell me more about why the application will need 5 PiB this time and maybe share some details about the amount of data you have? Thanks!

**Comment by changelo** [comment]
@derricktan23 Yes, this is our first application for datacap in Filecoin space for E-FIL+.

I clarified why I would move the application to E-FIL+ in a previous link.

https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1003#issuecomment-1445570877

We currently have far more data sets than at that time, and we expect more data sets to be stored in Filecoin Space Currently, the number of data sets that can be stored has exceeded 1 PB. According to the estimation of at least 4 copies, it can be considered reasonable to apply for 5 PB.


> Hi @Carohere
> 
> I'm willing to provide the proof on the size of dataset. On the websit through the following link [http://disk.bowenbigdata.com/share](url), you can see the detailed dataset information.
> 
> The number of copies we plan to store in the initial stage is 3-4. Thank you!

**Comment by derricktan23** [comment]
> @herrehesse Dear Notary,
> 
> f01396338 does not participate in storage temporarily. We are also looking for other SPs willing to cooperate in Slack, Big data exchange.
> 
> ID	Business Name	Location
> f0427989	Qingdao Pangu Kaiyuan Electronic Technology Development Co., Ltd	China/Qingdao
> f01123232	Shenzhen Bowen Big Data Technology Co., Ltd	China/Hongkong
> f01302086	Xi'an Taidi Electromechanical Engineering Co., Ltd	China/Xian
> f01076644	Jiangsu Shuozhen Cloud Network Technology Co., Ltd	China/Jiangsu

hi @changelo 

You listed these five SPs, provider IDs in your application. 
f01396338,f01302086,f01076644,f0222811,f0427989

may i check is f0222811 , f0222811 are still supporting your application? If so, please update the application with the number of copies with clear recipients of each copy (miner ID, business, location). 

May I check on your sealing capacity/ efficiency of sealing large datasets, TiBs per day?

**Comment by derricktan23** [comment]
> 

Thank you for the update. It's great to hear that the application has been updated with new content. It looks good. 

1. How do you explain how relevant customer data will be processed and transferred anywhere for preparation?
2. Can you prove that your customer, your preparer , and your intended SPs all have sufficient bandwidth to handle the right data size set?
3.Would you  explain how data set preparer handle prevention of duplication to prevent data cap abuse?

**Comment by changelo** [comment]
> > 
> 
> @changelo Thank you for the update. It's great to hear that the application has been updated with new content. It looks good.
> 
> 1. How do you explain how relevant customer data will be processed and transferred anywhere for preparation?
> 2. Can you prove that your customer, your preparer , and your intended SPs all have sufficient bandwidth to handle the right data size set?
> 3. Would you  explain how data set preparer handle prevention of duplication to prevent data cap abuse?

Hi @derricktan23 
Thank you for your patient and support. 

1. A: We use Graphsplit to segment data sets to generate car formatted files, which are copied in batches to hard disks, and sent by mail to storage providers.

2. A: Based on the above processing methods, online transmission of large data sets will be avoided. Due to the majority of cold data, our requirements for data retrieval frequency are not high. After reasonable estimation, we have confirmed with storage providers that the bandwidth of 100M-200M can already meet our business needs.

3. A: Together with storage providers, we have developed a dataset management system that manages the backup of datasets and the distribution of offline deal sealing tasks. The distributed and successfully sealed data contains the hash, file name, and unique identity of the storage provider, which will be recorded by the system to match the number of data copies and prevent data duplication and abuse of DataCap.

**Comment by laurarenpanda** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacea3bzdxeg3qj3v3stalkpuvtm2ur7ck4gdhs2fy6ogrudf5vfreng 
#### Address 
> f3rtlqil5ymgcck7itpv37cs744tpvhcpypa5mpqmcujuyb5zkmtsklohkf6llh7hrfnkz3632pycqumawbp3a
#### Datacap Allocated
> 500.00TiB
#### Signer Address
> f1bp3tzp536edm7dodldceekzbsx7zcy7hdfg6uzq
#### Id
> 2fdc99e4-b855-40eb-b074-713261540dc3
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacea3bzdxeg3qj3v3stalkpuvtm2ur7ck4gdhs2fy6ogrudf5vfreng

**Comment by changelo** [comment]
@Kevin-FF-USA  @derricktan23 @Joss-Hua @cryptowhizzard  @Sunnyiscoming 
Dear notaries,

Thank you for your due diligence, prudent review, and patient guidance in contributing to the development of the community.

Are there any honorable Notaries who can sign this for us? Really need your support to move on. Thanks a lot!

**Comment by kevzak** [comment]
Haven't heard back either way from @derricktan23 

Let's move forward with the update notary SLA (https://github.com/filecoin-project/notary-governance/discussions/807) and assign randomly:

@Aifabot-Cloud
@ewesion

Please review application details above and note that this applicant passed the KYC/KYB requirements for E-Fil. Please comment by March 28th. Thanks!

**Comment by Ewesion** [comment]
checker:manualTrigger

**Comment by PluskitOfficial** [comment]
No problem be found at present. We are willing to support and approve later today. 
Please strictly abide by the community rules. We will continue to pay attention to the project.

**Comment by changelo** [comment]
> No problem be found at present. We are willing to support and approve later today. Please strictly abide by the community rules. We will continue to pay attention to the project.

Hi @PluskitOfficial,

Thank you for taking the valuable time to review my application. We promise to strictly abide by community rules and are very willing to accept the supervision of notaries. Please spare some time to sign for us so that the application can move forward. This is extremely important for us and our business partners. To take a crucial step forward, we look forward to being able to store data on the Filecoin chain. Thanks!

**Comment by PluskitOfficial** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebppep46netzzvxr3iloy6kx5z7l6y2xaklmt4wuv3k4rt3qvzl54 
#### Address 
> f3rtlqil5ymgcck7itpv37cs744tpvhcpypa5mpqmcujuyb5zkmtsklohkf6llh7hrfnkz3632pycqumawbp3a
#### Datacap Allocated
> 500.00TiB
#### Signer Address
> f1tgnlhtcmhwipfm7thsftxhn5k52velyjlazpvka
#### Id
> 2fdc99e4-b855-40eb-b074-713261540dc3
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebppep46netzzvxr3iloy6kx5z7l6y2xaklmt4wuv3k4rt3qvzl54

**Comment by changelo** [comment]
@all

Prudent, patient, and impartial notaries, we are grateful for your enthusiastic support and guidance. We will follow the community agreement to carry out our project. We hope to receive your support in the future review. Thank you again!

**Comment by liyunzhi-666** [comment]
I had some problems with the signing. @kevzak 
<img width="1357" alt="image" src="https://user-images.githubusercontent.com/52949274/229986112-dd016fea-86bf-4b85-b437-86dfcd023aab.png">

**Comment by fabriziogianni7** [comment]
@huseyincansoylu another case oh double proposal here. Can you have a look?

**Comment by changelo** [comment]
checker:manualTrigger

**Comment by changelo** [comment]
checker:manualTrigger

**Comment by changelo** [comment]
checker:manualTrigger

**Comment by changelo** [comment]
@kevzak 
Dear Notary,
Could you please help approve the next round of DC quotas? Thank you!

**Comment by kevzak** [comment]
> @kevzak Dear Notary, Could you please help approve the next round of DC quotas? Thank you!

Feel free to reach out to E_Fil WG notaries directly @changelo. They are tagged here: https://filecoinproject.slack.com/archives/C03MHVAABFV/p1685732868607249?thread_ts=1685732855.714369&cid=C03MHVAABFV

**Comment by changelo** [comment]
Thank you for your help and timely feedback @kevzak.

**Comment by liyunzhi-666** [comment]
checker:manualTrigger

**Comment by liyunzhi-666** [comment]
The CID checker looks healthy. I will support this round.

**Comment by liyunzhi-666** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceckdlprtkcube6w34m3dgi7im6owpq6vd4lsxayyh7h7giq4bxaiq 
#### Address 
> f3rtlqil5ymgcck7itpv37cs744tpvhcpypa5mpqmcujuyb5zkmtsklohkf6llh7hrfnkz3632pycqumawbp3a
#### Datacap Allocated
> 1000.00TiB
#### Signer Address
> f1pszcrsciyixyuxxukkvtazcokexbn54amf7gvoq
#### Id
> 8e0d1cab-653f-46d8-a9e0-e38919be0def
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceckdlprtkcube6w34m3dgi7im6owpq6vd4lsxayyh7h7giq4bxaiq

**Comment by Casey-PG** [comment]
checker:manualTrigger

**Comment by Casey-PG** [comment]
Hi @changelo, 

We would like to help your application move forward. However, the retrieval success rate is very low, can you help me understand why?

**Comment by changelo** [comment]
Dear notary @Casey-PG ,

Thanks for your review. We found that many retrievals on the boost backend page failed due to timeout, rather than being unable to retrieve. We personally verified the above searches and the results were successful.

![boost_list_printscreen](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/40971829/0299ced6-bb26-4aaf-b729-f3dffd23b5ec)
![boost_detail_printscreen](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/40971829/e2179b2e-502e-4dd6-93e6-7c6581fe582e)

**Comment by changelo** [comment]
Hi @Casey-PG, If you need any further information from us, please feel free to let us know. Thank you.

**Comment by Casey-PG** [comment]
Thanks for providing more information. The official statistics of the search bot have not been introduced yet. We cannot interpret whether the results of your application meet the reasonable zone. We will follow the progress of the retrieval robot and offer our suggestions in a timely manner.

Thanks for your patience,
PangodGroup Team

**Comment by changelo** [comment]
Hi @Casey-PG ,

We have had effective discussions with the leader of this retrieval statistics project regarding the issue of retrieval timeout. 
[https://filecoinproject.slack.com/archives/C01DLAPKDGX/p1686674436156599?thread_ts=1686247698.699859&cid=C01DLAPKDGX](url)

Can we verify the retrievability of the dataset using the previous manual retrieval method before making changes to the timeout time of the official automatic retrieval robot.  Thanks for your responsible review.

**Comment by changelo** [comment]
Hi @Casey-PG, @kevzak 

There has been new progress in the discussion of the official statistical report given by the retrieval robot, and the project leader has provided reasonable explanations and meaningful suggestions for the situation we are currently facing.

[https://filecoinproject.slack.com/archives/C01DLAPKDGX/p1687321398181439?thread_ts=1686247698.699859&cid=C01DLAPKDGX](https://filecoinproject.slack.com/archives/C01DLAPKDGX/p1687321398181439?thread_ts=1686247698.699859&cid=C01DLAPKDGX)

Although our application is for E-FIL, we guarantee that the retrieval of the dataset can be successful, even if the response time may be longer than the current retrieval robot setting.

We need the support of Notaries to keep the application forward. Thank you.

**Comment by cryptowhizzard** [comment]
Why is your response time slow on a retrieval request if I may ask?

**Comment by kevzak** [comment]
Hi I’m trying to better understand @Casey-PG @cryptowhizzard is there a reason you are challenging retrievals on a private dataset? 

It does not follow the same guidelines as open public. 

Is it just to confirm the data can be retrieved?

**Comment by kevzak** [comment]
@changelo we have a new KYC ID check available on [filplus.storage](https://filplus.storage/). Please complete when you have a chance as a requirement for E-Fil+ to add additional layer of trust and to verify this GitHub account. See details: [LINK](https://medium.com/filecoin-plus/implementation-of-a-third-party-kyc-id-check-for-fil-applicants-e5e825b1484e)

**Comment by data-programs** [comment]
<img width="32" alt="KYC" Verified src="https://stable.filplus.storage/images/filplus-kyc-verified-badge.png"/>

This user’s identity has been verified through [filplus.storage](https://filplus.storage)

**Comment by changelo** [comment]
Hi @kevzak, I have completed the new KYC ID check.

**Comment by Carohere** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebqbvimraskeblwdp4m7ui5odndl52xlwhhz6kjr7iadhofypr36m 
#### Address 
> f3rtlqil5ymgcck7itpv37cs744tpvhcpypa5mpqmcujuyb5zkmtsklohkf6llh7hrfnkz3632pycqumawbp3a
#### Datacap Allocated
> 1000.00TiB
#### Signer Address
> f1pynuve3pi2fwvhlkco6dl3ipspkgzmb25syv5ca
#### Id
> 8e0d1cab-653f-46d8-a9e0-e38919be0def
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebqbvimraskeblwdp4m7ui5odndl52xlwhhz6kjr7iadhofypr36m

**Comment by Carohere** [comment]
Approving this application for the following reasons: 
- the client has provided the sp and allocation details
- both retrieval and CID reports meet the expectations of the E-FIL+ program
- the client has been actively engaging and providing the newest updates to community members on slack and github

**Comment by C00kies77** [comment]
checker:manualTrigger

**Comment by changelo** [comment]
> This application has not seen any responses in the last 10 days. This issue will be marked with Stale label and will be closed in 4 days. Comment if you want to keep this application open.

The sealing of the data is still ongoing

**Comment by changelo** [comment]
The sealing of the data is still ongoing

**Comment by clriesco** [comment]
Removed stale label and reopened issue :)

**Comment by changelo** [comment]
checker:manualTrigger

**Comment by changelo** [comment]
checker:manualTrigge

**Comment by changelo** [comment]
checker:manualTrigger

**Comment by Sunnyiscoming** [comment]
Hello, @changelo per the https://github.com/filecoin-project/notary-governance/issues/922 for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

This information will be reviewed by Fil+ Governance team to confirm validity and then the application will be allowed to move forward for additional notary review.
