### ISSUE TITLE
[DataCap Application] FilSwan -  Fly Brain Anatomy v2

### ISSUE THREAD

**Issue by flyworker** [filecoin-project/filecoin-plus-large-datasets#1583]
### Data Owner Name

Janelia Research Campus

### Data Owner Country/Region

United States

### Data Owner Industry

Life Science / Healthcare

### Website

https://open.quiltdata.com/b/janelia-flylight-imagery

### Social Media

```text
Contact
flylight@janelia.hhmi.org
```

### Total amount of DataCap being requested

2PiB

### Weekly allocation of DataCap requested

200TiB

### On-chain address for first allocation

f1cmmxerf4fdybqoad6voojos5sxeaekwsxlzacma

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Filswan provides a decentralized edge infrastructure marketplace and software that moves data storage and analysis as close as necessary on Web 3.0.

This is a project for the Slingshot Restore Program, the program is for fixing 10PB storage within 100 days. FilSwan is a leading web3 and computing provider in the filecoin ecosystem player. We would like to work as a client for this project.

The first allocation is in https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/157 back to Dec 21, 2021. After 1.5 years, most sectors start expiring, so we decide to start v2.

The previous work can be found here: https://console.filswan.com/#/dataset
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
Description

This data set, made available by Janelia's FlyLight project, consists of fluorescence images of Drosophila melanogaster driver lines, aligned to standard templates, and stored in formats suitable for rapid searching in the cloud. Additional data will be added as it is published.
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### How do you plan to prepare the dataset

others/custom tool

### If you answered "other/custom tool" in the previous question, enter the details here

```text
Swan Client
```

### Please share a sample of the data

```text
https://open.quiltdata.com/b/janelia-flylight-imagery/tree/Annotator%20Gen1%20MCFO/R10A09/R10A09-20170217_21_E4-f-20x-brain-GAL4-JRC2018_Unisex_20x_HR-CDM_2.png
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Monthly

### For how long do you plan to keep this dataset stored on Filecoin

1.5 to 2 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America

### How will you be distributing your data to storage providers

HTTP or FTP server, IPFS

### How do you plan to choose storage providers

Others

### If you answered "Others" in the previous question, what is the tool or platform you plan to use

```text
Swan Provider
```

### How do you plan to make deals to your storage providers

Others/custom tool

### If you answered "Others/custom tool" in the previous question, enter the details here

```text
Swan client
```

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
Is this issue the continuation of https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/157?

**Comment by flyworker** [comment]
> Is this issue the continuation of #157?
yes

**Comment by Sunnyiscoming** [comment]
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/157#issuecomment-1352719907
@flyworker Could you explain the abnormal information of https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/157.

**Comment by flyworker** [comment]
@Sunnyiscoming  I did not notice that there are CID issues on the previous allocation,the dataset have been put on the sending engine for 2 years, I need to do an internal check to see if it contains bugs.

Will come back one we have a conclusion about it.
Close the application for now.
