### ISSUE TITLE
[DataCap Application] NREL National Solar Radiation Database

### ISSUE THREAD

**Issue by Lennon00** [filecoin-project/filecoin-plus-large-datasets#1584]
### Data Owner Name

National Renewable Energy Laboratory

### Data Owner Country/Region

United States

### Data Owner Industry

Environment

### Website

https://nsrdb.nrel.gov/

### Social Media

```text
https://twitter.com/nrel/
https://www.facebook.com/nationalrenewableenergylab
https://www.youtube.com/user/NRELPR
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

400TiB

### On-chain address for first allocation

f1kmjnrme567khnfq5fhuz34bzklpxdt6ry3glgeq

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
At the National Renewable Energy Laboratory (NREL), they focus on creative answers to today's energy challenges. From breakthroughs in fundamental science to new clean technologies to integrated energy systems that power our lives, NREL researchers are transforming the way the nation and the world use energy.
We are participants in filecoin community and I want to make filecoin network better by storing public data that is good for humanity.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
The National Solar Radiation Database (NSRDB) is a serially complete collection of hourly and half-hourly values of the three most common measurements of solar radiation – global horizontal, direct normal, and diffuse horizontal irradiance — and meteorological data. These data have been collected at a sufficient number of locations and temporal and spatial scales to accurately represent regional solar radiation climates.
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### How do you plan to prepare the dataset

lotus, singularity

### Please share a sample of the data

```text
https://registry.opendata.aws/nrel-pds-nsrdb/
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

1.5 to 2 years

### In which geographies do you plan on making storage deals

Asia other than Greater China, North America, Europe

### How will you be distributing your data to storage providers

IPFS, Shipping hard drives

### How do you plan to choose storage providers

Slack, Big data exchange

### How do you plan to make deals to your storage providers

Boost client, Lotus client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Looking at your application i have some questions:
As you are brand new on Github and have no history of past applications it seems to me that applying for 5PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?

Can you show us visible proof of the size of your data and the storage systems you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230337462961356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!

**Comment by Sunnyiscoming** [comment]
Can you provide more detailed informations about SPs you will cooperate with?

**Comment by simonkim0515** [comment]
## Datacap Request Trigger

#### Total DataCap requested 
> 5PiB

#### Expected weekly DataCap usage rate 
> 400TiB 

#### Client address
> f1kmjnrme567khnfq5fhuz34bzklpxdt6ry3glgeq

**Comment by Lennon00** [comment]
@Sunnyiscoming I have contacted with some SPs, but we are just at the first step of communication. I will add more information in the future and do some distribute under the community rules.

**Comment by BlockMakeronline** [comment]
@Lennon00 
I'm the notary from Blockmaker.
I want to know how many backups you want to store. Are you ready if you get Datacap?

**Comment by cryptowhizzard** [comment]
Dear applicant / @Lennon00 

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Looking at your application i have some questions:
As you are brand new on Github and have no history of past applications it seems to me that applying for 5PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?

Can you show us visible proof of the size of your data and the storage systems you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230337462961356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!

**Comment by Lennon00** [comment]
@BlockMakeronline Hello notary, I plan store 10 backups for this application. Yes, we are ready to start deals after we get Datacap.    Look forward to your approval!

**Comment by Lennon00** [comment]
@cryptowhizzard Thank you for your comments. For privacy, I am worried to fill out the form. Thank again.

**Comment by BlockMakeronline** [comment]
I will approve it and track the process.

**Comment by BlockMakeronline** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebzvo22uyowobc6sea5n2vorzpp3dvesj5c556dxh3g2y6tef32j2 
#### Address 
> f1kmjnrme567khnfq5fhuz34bzklpxdt6ry3glgeq
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1o3twrcpwjtpcd4q36lpq4qmy2qfbgtyy5h6tsty
#### Id
> 6c68e1bd-63a0-4829-b62a-c5dba0a63227
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebzvo22uyowobc6sea5n2vorzpp3dvesj5c556dxh3g2y6tef32j2

**Comment by MatrixStorage** [comment]
Your project is good, but I would like to ask if your SPs is ready?  Would you like to show us?  If you can show it to us, I can also provide a signature for your project.In addition, I hope that even if you do get Datacap, you will be able to store it in accordance with community regulations to avoid confusing your future applications.

**Comment by Lennon00** [comment]
@MatrixStorage Welcome! We are now looking for SP. I will add more information in the future and do some distribute under the community rules! Welcome to your attention!

**Comment by MatrixStorage** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedwdwymruw753n6jigg7lzw2bwoy4hthm642bw7624lsmeghwp3yy 
#### Address 
> f1kmjnrme567khnfq5fhuz34bzklpxdt6ry3glgeq
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1tbxqwjxfyv7swsdin4einirlsfquv3vnmlapley
#### Id
> 6c68e1bd-63a0-4829-b62a-c5dba0a63227
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedwdwymruw753n6jigg7lzw2bwoy4hthm642bw7624lsmeghwp3yy

**Comment by panges2** [comment]
Hey @MatrixStorage @BlockMakeronline Can you please resign the application. Your last one returned error code 16 meaning the multisig was empty when you tried. I deleted it so you guys can try again

**Comment by BlockMakeronline** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecqvwcgu7wyzicbueogfiny3ze5hzpxjp42lrvij5niqothprbyji 
#### Address 
> f1kmjnrme567khnfq5fhuz34bzklpxdt6ry3glgeq
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1o3twrcpwjtpcd4q36lpq4qmy2qfbgtyy5h6tsty
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecqvwcgu7wyzicbueogfiny3ze5hzpxjp42lrvij5niqothprbyji

**Comment by MatrixStorage** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedte2ovc4lvxslgooyu67okjqri4t5623mcbwt44nswle2yi2ctrs 
#### Address 
> f1kmjnrme567khnfq5fhuz34bzklpxdt6ry3glgeq
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1tbxqwjxfyv7swsdin4einirlsfquv3vnmlapley
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedte2ovc4lvxslgooyu67okjqri4t5623mcbwt44nswle2yi2ctrs

**Comment by BobbyChoii** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecflilqo7e5wmzqty7wtneiwv2qlfyw3mc3hv42dfn5fzwozfk562 
#### Address 
> f1kmjnrme567khnfq5fhuz34bzklpxdt6ry3glgeq
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1irqs2gmctiv3jcdfwuch7oxvf4ixh3k4b2wc24i
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecflilqo7e5wmzqty7wtneiwv2qlfyw3mc3hv42dfn5fzwozfk562

**Comment by Aifabot-Cloud** [comment]
checker:manualTrigger

**Comment by Aifabot-Cloud** [comment]
Please keep your request in accordance with the principles of the program and in line with their allocation strategy. We will check the following updates.

**Comment by Aifabot-Cloud** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb4foh5xiluisds7rvsp4ykt3ouhk55oa42zkdga4i3w4hcgt6sso 
#### Address 
> f1kmjnrme567khnfq5fhuz34bzklpxdt6ry3glgeq
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f174fg3bqbln3zjnkxtyf6s54txqkr7yqkj6cig7y
#### Id
> ec99cd1d-d012-47f7-a24d-7013c49cb8df
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb4foh5xiluisds7rvsp4ykt3ouhk55oa42zkdga4i3w4hcgt6sso

**Comment by Casey-PG** [comment]
Glad to support this application in this round.

**Comment by Casey-PG** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedtwd7syfdfe3wkygjqfa7a4tr7j3ihxrzwxq6jwfw2geiwbpffsk 
#### Address 
> f1kmjnrme567khnfq5fhuz34bzklpxdt6ry3glgeq
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1d4yb3wags3mtddzesxoo63jv7dmlec3bq4yteni
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedtwd7syfdfe3wkygjqfa7a4tr7j3ihxrzwxq6jwfw2geiwbpffsk

**Comment by BobbyChoii** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecpof2mbbn5vcyw2ple6nk3xaahjcxxjouh5itg7mld5tfewktany 
#### Address 
> f1kmjnrme567khnfq5fhuz34bzklpxdt6ry3glgeq
#### Datacap Allocated
> 1.56PiB
#### Signer Address
> f1irqs2gmctiv3jcdfwuch7oxvf4ixh3k4b2wc24i
#### Id
> 2a97c592-2e84-4827-b5c4-edeec7110951
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecpof2mbbn5vcyw2ple6nk3xaahjcxxjouh5itg7mld5tfewktany

**Comment by C00kies77** [comment]
checker:manualTrigger

**Comment by cryptowhizzard** [comment]
checker:manualTrigger

**Comment by Lennon00** [comment]
Got it.

**Comment by Wengeding** [comment]
LGTM, looking forward to seeing your improvement about your Deal Data Replication.

**Comment by Wengeding** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedfjqh3m7k6tjh3r5jhe7drmc2tl4ctjjtua7xghb2ox4ny6gvezw 
#### Address 
> f1kmjnrme567khnfq5fhuz34bzklpxdt6ry3glgeq
#### Datacap Allocated
> 1.56PiB
#### Signer Address
> f1txfsjmix4vlzido4dkildrnbw26owtlbslexmpa
#### Id
> f1b457e2-ed79-4d0f-9b3d-27381ec63f1b
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedfjqh3m7k6tjh3r5jhe7drmc2tl4ctjjtua7xghb2ox4ny6gvezw

**Comment by AthSmith** [comment]
Overall HTTP retrieval success rate: 7.67%,  willing to sign.

**Comment by AthSmith** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecfgyofqvuu34xt4afhvu34trwt7nn3dmc2uymt2lmgjtqzbk2yfu 
#### Address 
> f1kmjnrme567khnfq5fhuz34bzklpxdt6ry3glgeq
#### Datacap Allocated
> 1.56PiB
#### Signer Address
> f1vxbqrf7rfum3n6m5u6eb4re6xj7amvsaqnzu64y
#### Id
> f1b457e2-ed79-4d0f-9b3d-27381ec63f1b
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecfgyofqvuu34xt4afhvu34trwt7nn3dmc2uymt2lmgjtqzbk2yfu

**Comment by herrehesse** [comment]
@Wengeding & @AthSmith known abusive notaries signing of an LDN where selfdealing is clearly visible on the CID report. Can we please remove/hold the DC from closed applications asap and remove notaries from multisig?

@Filplus-govteam @Kevin-FF-USA @raghavrmadya

**Comment by cryptowhizzard** [comment]
This client is actively stalling http retrievals and blocked http ranged requests with a reverse proxy to prevent it's data being investigated.

It works as follows:

One set's a bandwidth limit with NGINX on the HTTP retrieval. After a random certain amount the limit is set to zero. This makes the transfer timeout. Because range retrieval is disabled in NGINX one cannot pick up where he left and needs to start all over again. 

Log can be found at http://datasetcreators.com/downloadedcarfiles/logs/1584.log

**Comment by Filplus-govteam** [comment]
Hello @Lennon00 per the new guidelines https://github.com/filecoin-project/notary-governance/issues/922 for Open Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

This information will be reviewed by Fil+ Governance team to confirm validity toward the Fil+ guideline of a distributed storage plan and SPs posted in the comments here. Let us know if you have any questions.
