### ISSUE TITLE
[DataCap Application] <Rotation Technology> - <Video Resources>

### ISSUE THREAD

**Issue by minecryptoHub** [filecoin-project/filecoin-plus-large-datasets#1585]
### Data Owner Name

Fujian Rotation Technology Co., Ltd.

### Data Owner Country/Region

China

### Data Owner Industry

Other

### Website

https://www.minecrypto.cn/

### Social Media

```text
https://www.minecrypto.cn/
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

500TiB

### On-chain address for first allocation

f14t46qjo5n3zso6yeguqrtpfpyjqqzkahlsrdehq

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Our team was established in May 2021 and currently has 50 employees. The company mainly operates video content creation platform, content promotion and distribution service, content distribution service, AI intelligent advertising service, and is committed to providing users with simple, fast, efficient, and high-value open content platform.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
Every day, our team members will re-create video resources, so we need a lot of storage space to store video data, which is a very large data set. For example, food videos, scenery videos, funny videos, game videos, draft video files being created, short video files already created, etc. These stored files are original and have no copyright issues. So we need a lot of storage space.
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### How do you plan to prepare the dataset

IPFS

### Please share a sample of the data

```text
[https ://drive.google.com/drive/folders/1HwpY7tefOqExT-YIOmJWolH4vaZ8K_wy?usp=sharing](https://drive.google.com/drive/folders/1HwpY7tefOqExT-YIOmJWolH4vaZ8K_wy?usp=sharing)
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

More than 3 years

### In which geographies do you plan on making storage deals

Greater China

### How will you be distributing your data to storage providers

Shipping hard drives

### How do you plan to choose storage providers

Big data exchange

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Looking at your application i have some questions:
As you are brand new on Github and have no history of past applications it seems to me that applying for 5PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?

Can you show us visible proof of the size of your data and the storage systems you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230337462961356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!

**Comment by Sunnyiscoming** [comment]
![image](https://user-images.githubusercontent.com/105098820/216999803-ea3f8f8b-5f89-473a-80dc-8089e70cdad3.png)
Is your data authorized to be stored? Such as the data samples you provided.
https://aiqicha.baidu.com/company_detail_94615966776023 Is this a link to your company information?
Can you provide more detailed informations about SPs you will cooperate with?

**Comment by caoyoungyoung** [comment]
The videos on your websites can not be displayed. And are those videos are public accessible? Are those videos original?

**Comment by herrehesse** [comment]
@minecryptoHub I do not support this application and its value. Adding: all your video files are copyrighted movie files. https://drive.google.com/drive/folders/1gZBNiViJtwH2taFqLNZHNCJ6UO7l-zKP?usp=sharing

**Comment by minecryptoHub** [comment]
@Sunnyiscoming @herrehesse  I'm terribly sorry. It's my fault. My last application was unexpectedly closed due to a late response, and this is a new one. The old application is #1429.
As for the issue of video copyright, it is my careless consideration. I do not intend to store it as public data. So we decided not to store film and television resources, but to store the original videos that we shot ourselves, which are free from copyright issues. I have made some modifications in this application. Due to my mistake, the wrong address was filled in for the data sample. The new sample address is: https://drive.google.com/drive/folders/1HwpY7tefOqExT-YIOmJWolH4vaZ8K_wy?usp=sharing

**Comment by minecryptoHub** [comment]
@Sunnyiscoming yes , https://aiqicha.baidu.com/company_detail_94615966776023 is link to my company information

**Comment by minecryptoHub** [comment]
@caoyoungyoung Yes, the data is publicly accessible and original

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.


Can you show us visible proof of the size of your data and the storage systems you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230337462961356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!

**Comment by herrehesse** [comment]
@minecryptoHub Can we support you by finding willing SP's to store your data? We would require to have a list with business names and location before granting any datacap.

If things stay limited would support a first trench for the applicant to show their good intentions.

**Comment by simonkim0515** [comment]
## Datacap Request Trigger

#### Total DataCap requested 
> 5PiB

#### Expected weekly DataCap usage rate 
> 500TiB 

#### Client address
> f14t46qjo5n3zso6yeguqrtpfpyjqqzkahlsrdehq

**Comment by minecryptoHub** [comment]
@herrehesse Hello, I have been looking for SP that can help me store data. At present, the SP that has reached cooperation includes:
China/HongKong: f02009671,
Singapore: f02008841,
Korea/Seoul: f02012674,
China/Shenzhen: f01708981

**Comment by cryptowhizzard** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaokvy2dprm2efqbp5o5h2eon7hwww4krsoxchkgzq6gh6ktqxkhs 
#### Address 
> f14t46qjo5n3zso6yeguqrtpfpyjqqzkahlsrdehq
#### Datacap Allocated
> 250.00TiB
#### Signer Address
> f1krmypm4uoxxf3g7okrwtrahlmpcph3y7rbqqgfa
#### Id
> 9adf3d3c-7a61-417f-af37-63e308ceff35
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaokvy2dprm2efqbp5o5h2eon7hwww4krsoxchkgzq6gh6ktqxkhs

**Comment by yuwenhui** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedvd2jo5z3crcrdrfzoif64ruyffcy7zgzmtzxe33alcwbtvgcv56 
#### Address 
> f14t46qjo5n3zso6yeguqrtpfpyjqqzkahlsrdehq
#### Datacap Allocated
> 250.00TiB
#### Signer Address
> f1ui5iy4mmkxjbw7752omiwp2ols2fzv4thrayagi
#### Id
> 9adf3d3c-7a61-417f-af37-63e308ceff35
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedvd2jo5z3crcrdrfzoif64ruyffcy7zgzmtzxe33alcwbtvgcv56

**Comment by NDLABS-OFFICE** [comment]
The check bot has verified that everything is in good condition, and I have tested the connectivity of all nodes, which are all functional. I am willing to provide support.

**Comment by NDLABS-OFFICE** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaojgyndkmogvbsun3hiu65yxr25twiunmqcvowtrwiqto7n5emzy 
#### Address 
> f14t46qjo5n3zso6yeguqrtpfpyjqqzkahlsrdehq
#### Datacap Allocated
> 500.00TiB
#### Signer Address
> f1yayfsv6whu3rheviucvventj3y6t542xfpb47ei
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaojgyndkmogvbsun3hiu65yxr25twiunmqcvowtrwiqto7n5emzy

**Comment by newwebgroup** [comment]
checker:manualTrigger

**Comment by newwebgroup** [comment]
https://filecoin.tools/f02084354

./lotus client retrieve --provider f02085743 bafybeidbwtklugjmwgjbui4yka6txmfe4ydmsicfmiy2xoxljlyteobal4 .car
<img width="1235" alt="image" src="https://user-images.githubusercontent.com/100118145/230586326-6794b45c-f9ec-4fb2-9aae-40464fbab433.png">

**Comment by newwebgroup** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebmt6635g2yachxhv7yynit5vrfplcs7jkqfjmes5mkwdroy3ddaw 
#### Address 
> f14t46qjo5n3zso6yeguqrtpfpyjqqzkahlsrdehq
#### Datacap Allocated
> 1000.00TiB
#### Signer Address
> f1e77zuityhvvw6u2t6tb5qlnsegy2s67qs4lbbbq
#### Id
> cb842584-dd48-4311-9bd4-564ee50167e4
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebmt6635g2yachxhv7yynit5vrfplcs7jkqfjmes5mkwdroy3ddaw

**Comment by Fatman13** [comment]
checker:manualTrigger

**Comment by 1ane-1** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecixgsfvafukdwg2cn7v32qz5gguz7zpzrhbc2cpqvoydgd4qkmii 
#### Address 
> f14t46qjo5n3zso6yeguqrtpfpyjqqzkahlsrdehq
#### Datacap Allocated
> 1000.00TiB
#### Signer Address
> f1mdk7s2vntzm6hu35yuo6vjubtrpfnb2awhgvrri
#### Id
> a0edd024-d8bf-4a0c-8d23-5518ac293d1a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecixgsfvafukdwg2cn7v32qz5gguz7zpzrhbc2cpqvoydgd4qkmii

**Comment by Tom-OriginStorage** [comment]
![image](https://user-images.githubusercontent.com/103015469/232437216-de3c4872-e472-499a-a22c-4c320194467b.png)

**Comment by Tom-OriginStorage** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedrza3uldwitessgylwfsoosgs2tr533kebvv5thfu6foxqvo635s 
#### Address 
> f14t46qjo5n3zso6yeguqrtpfpyjqqzkahlsrdehq
#### Datacap Allocated
> 1.95PiB
#### Signer Address
> f1q6bpjlqia6iemqbrdaxr2uehrhpvoju3qh4lpga
#### Id
> 561a80cc-7b0a-4af0-91b2-acb44e09e1a5
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedrza3uldwitessgylwfsoosgs2tr533kebvv5thfu6foxqvo635s

**Comment by stcouldlisa** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebmlkb7skchvxokmmjrqp52l62lhaps6dzoohtx276ikdu3xslvag 
#### Address 
> f14t46qjo5n3zso6yeguqrtpfpyjqqzkahlsrdehq
#### Datacap Allocated
> 1.95PiB
#### Signer Address
> f1jvvltduw35u6inn5tr4nfualyd42bh3vjtylgci
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebmlkb7skchvxokmmjrqp52l62lhaps6dzoohtx276ikdu3xslvag

**Comment by stcouldlisa** [comment]
lotus client retrieve --provider f02085743 bafybeifrp3nh3doiilr4kpaj6o4lrag65an4up6ogwgkmm6tdtvkh27uuy ~/output-file

**Comment by stcouldlisa** [comment]
<img width="893" alt="WX20230418-113253@2x" src="https://user-images.githubusercontent.com/112812896/232664274-e3317e49-f367-4477-b9ef-fa97344485e6.png">

**Comment by herrehesse** [comment]
checker:manualTrigger

**Comment by spaceT9** [comment]
checker:manualTrigger
