### ISSUE TITLE
Client Allocation Request for: Impossible Cloud

### ISSUE THREAD

**Issue by Whiterabbit5264** [filecoin-project/filecoin-plus-large-datasets#1586]
# Client Allocation Questions

## Core Information
- Name: Impossible Cloud
- Website / Social Media: [impossiblecloud.com](impossiblecloud.com), (https://www.linkedin.com/company/impossiblecloud/, LinkedIn)
- Region: Europe
- DataCap Requested: 519 GiB
- Addresses to be Notarized: f1ikkftumztbq6uzr2zmguwodzstbtr6jihcoiedy
- Notary Requested: Deon Erda

**Comment by timelytree** [comment]
Hi @Whiterabbit5264, the form at https://filplus.storage now correctly submits application requests of <100TiB to the [correct repo](https://github.com/filecoin-project/filecoin-plus-client-onboarding). You can fill it out again 🙂

**Comment by Whiterabbit5264** [comment]
No longer needed, thanks 👍
