### ISSUE TITLE
[DataCap Application] World Bank - Light Every Night (Public Dataset)

### ISSUE THREAD

**Issue by Conor-xin** [filecoin-project/filecoin-plus-large-datasets#1587]
### Data Owner Name

World Bank Group

### Data Owner Country/Region

United States

### Data Owner Industry

Life Science / Healthcare

### Website

https://www.worldbank.org/en/home

### Social Media

```text
https://twitter.com/worldbank
https://www.flickr.com/photos/worldbank
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

500TiB

### On-chain address for first allocation

f16jegeis3yc3hyt7c5lza3ifzss2ofop7bz35bvi

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
This is a very rewarding dataset. World Bank Group is a unique global partnership: five institutions working for sustainable solutions that reduce poverty and build shared prosperity in developing countries.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
Light Every Night - World Bank Nighttime Light Data – provides open access to all nightly imagery and data from the Visible Infrared Imaging Radiometer Suite Day-Night Band (VIIRS DNB) from 2012-2020 and the Defense Meteorological Satellite Program Operational Linescan System (DMSP-OLS) from 1992-2013.The data is published and openly available under the terms of the World Bank’s open data license.
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### How do you plan to prepare the dataset

IPFS, lotus, singularity

### Please share a sample of the data

```text
https://registry.opendata.aws/wb-light-every-night/
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Sporadic

### For how long do you plan to keep this dataset stored on Filecoin

1.5 to 2 years

### In which geographies do you plan on making storage deals

North America, Europe

### How will you be distributing your data to storage providers

HTTP or FTP server, IPFS, Shipping hard drives

### How do you plan to choose storage providers

Big data exchange

### How do you plan to make deals to your storage providers

Lotus client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
Data samples you provided are mentioned in the following applications. How many duplicates are there?
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/840
Can you provide more detailed informations about yourself and SPs you will cooperate with?

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Looking at your application i have some questions:
As you are brand new on Github and have no history of past applications it seems to me that applying for 5PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?

Can you show us visible proof of the size of your data and the storage systems you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230337462961356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!

**Comment by Conor-xin** [comment]
@Sunnyiscoming This is a public dataset on aws. We plan to store 10 duplicates and prepare for some unknown situations. We are in the process of communicating with sps, but hopefully our datacap will be approved soon.

**Comment by simonkim0515** [comment]
## Datacap Request Trigger

#### Total DataCap requested 
> 5PiB

#### Expected weekly DataCap usage rate 
> 500TiB 

#### Client address
> f16jegeis3yc3hyt7c5lza3ifzss2ofop7bz35bvi

**Comment by MatrixStorage** [comment]
Looks good, have you found suitable SPs in the past few days?

**Comment by Conor-xin** [comment]
@MatrixStorage Yes, it's taken me a long time to prepare the CAR file. I contacted some SP via slack, and as soon as the CAR file is ready, I will list them here. Thanks for your attention.

**Comment by MatrixStorage** [comment]
I am willing to support you, but please store the data in a correct way in the future. We will also check regularly or ask you to provide data retrieval.

**Comment by MatrixStorage** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedgdzr5xzgfiixudsxvbr3s3pqupryws75n4tksa3e4w7722ceysq 
#### Address 
> f16jegeis3yc3hyt7c5lza3ifzss2ofop7bz35bvi
#### Datacap Allocated
> 250.00TiB
#### Signer Address
> f1tbxqwjxfyv7swsdin4einirlsfquv3vnmlapley
#### Id
> 001a8b25-b39d-4d35-bf61-934330fbf712
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedgdzr5xzgfiixudsxvbr3s3pqupryws75n4tksa3e4w7722ceysq

**Comment by PluskitOfficial** [comment]
Seems no further problems at the moment. I'd like to support the project.

**Comment by PluskitOfficial** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec42jff3lc4pdq5tq2fn2tabewdohcnwhrti66mht5ktujy4kqnbq 
#### Address 
> f16jegeis3yc3hyt7c5lza3ifzss2ofop7bz35bvi
#### Datacap Allocated
> 250.00TiB
#### Signer Address
> f1tgnlhtcmhwipfm7thsftxhn5k52velyjlazpvka
#### Id
> 001a8b25-b39d-4d35-bf61-934330fbf712
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec42jff3lc4pdq5tq2fn2tabewdohcnwhrti66mht5ktujy4kqnbq

**Comment by Meibuy** [comment]
@Conor-xin ,please contact f02055555 and make sure why it can't show the  IP location. You can consider giving them up if they don't cooperate.

**Comment by BobbyChoii** [comment]
The applicant may not be able to meet the guideline in the first few rounds. I will check future reports and also leave reviews .

**Comment by UnionLabs2020** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaft4f7vvnd2g5727hmsupfh67u535u4jf3oxolxlu4r7co4ys6sa 
#### Address 
> f16jegeis3yc3hyt7c5lza3ifzss2ofop7bz35bvi
#### Datacap Allocated
> 500.00TiB
#### Signer Address
> f17xdri3wunqgld7dm23e4f3eqsntjakwc47xjo6i
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaft4f7vvnd2g5727hmsupfh67u535u4jf3oxolxlu4r7co4ys6sa

**Comment by UnionLabs2020** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced6ee5iyq4e6shfg2bzishyh77utvy6bdfxo6m5brnevdxek4fy5s 
#### Address 
> f16jegeis3yc3hyt7c5lza3ifzss2ofop7bz35bvi
#### Datacap Allocated
> 500.00TiB
#### Signer Address
> f17xdri3wunqgld7dm23e4f3eqsntjakwc47xjo6i
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced6ee5iyq4e6shfg2bzishyh77utvy6bdfxo6m5brnevdxek4fy5s

**Comment by destor2023** [comment]
checker:manualTrigger

**Comment by destor2023** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacea2go2jeoajdgoiw4xxikgg7rf3e7v2gxlv75kraosja2naikecym 
#### Address 
> f16jegeis3yc3hyt7c5lza3ifzss2ofop7bz35bvi
#### Datacap Allocated
> 500.00TiB
#### Signer Address
> f1yh6q3nmsg7i2sys7f7dexcuajgoweudcqj2chfi
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacea2go2jeoajdgoiw4xxikgg7rf3e7v2gxlv75kraosja2naikecym

**Comment by destor2023** [comment]
Report looks healthy, please keep up the great work.

**Comment by Meibuy** [comment]
checker:manualTrigger

**Comment by Conor-xin** [comment]
Thank you

**Comment by cryptowhizzard** [comment]
checker:manualTrigger

**Comment by cryptowhizzard** [comment]
Hello,

I see you are working solely with SP's who have been tagged for CID/ Sharing and not support retrieval.

Can you clarify please.

![Scherm­afbeelding 2023-07-31 om 08 44 02](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/36404435/3e6d7dae-3c50-41f8-9d0c-6cd8e2572790)

**Comment by Casey-PG** [comment]
checker:manualTrigger

**Comment by Conor-xin** [comment]
![258732418-6167dc49-d760-42d4-9146-58d175486e8c](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/122514421/ed01371b-cb8a-4013-aa6c-27f4c536d898)
We've already begun replacing the sp. We won't work with sp's who didn't support retrieval in the past anymore. Please give us a chance for participation.

**Comment by Suyanj** [comment]
checker:manualTrigger

**Comment by Suyanj** [comment]
Seems the retrieval success rate is improving, keep up!
Also, I don't care about the history of the SPs you work with, but please be careful to follow the rules in their work with you.

**Comment by Filplus-govteam** [comment]
Hello @Conor-xin per the new guidelines https://github.com/filecoin-project/notary-governance/issues/922 for Open Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

This information will be reviewed by Fil+ Governance team to confirm validity toward the Fil+ guideline of a distributed storage plan and SPs posted in the comments here. Let us know if you have any questions.

**Comment by Conor-xin** [comment]
@Filplus-govteam OK.   Keep Open

**Comment by Conor-xin** [comment]
Keep Open please.

**Comment by Conor-xin** [comment]
Please keep open

**Comment by AthSmith** [comment]
checker:manualTrigger
