### ISSUE TITLE
[DataCap Application] BHK Industry GmbH

### ISSUE THREAD

**Issue by BHK-Industry** [filecoin-project/filecoin-plus-large-datasets#1588]
### Data Owner Name
BHK Industry GmbH

### Data Owner Country/Region
Germany

### Data Owner Industry
IT & Technology Services

### Website
[https://www.bhkindustry.com](https://www.bhkindustry.com)
[https://www.bhkcloud.com](https://www.bhkcloud.com)

### Social Media
@BHKCloud_io (Twitter)
@BHK-Industry (GitHub)

### Total amount of DataCap being requested
5 PiB

### Weekly allocation of DataCap requested
1 PiB

### On-chain address for first allocation
f3waep5r2qf4hvfgslvvieesvsb6mocgyl3gz2c73kqu72tmqv2yhdxez436fr7v6jd6vumgsmdiywp76ivvoa

### Custom multisig
Yes

### Identifier
E-Fil

### Share a brief history of your project and organization
Encrypted Client Data 
Own IT Cloud Storage Solution

### Is this project associated with other projects/ecosystem stakeholders?
No

### Describe the data being stored onto Filecoin
Encrypted Client Data in 101 GB chunks 

### Where was the data currently stored in this dataset sourced from
My own storage infrastructure 

### How do you plan to prepare the dataset
lotus
singularity 
Support from Decent with CAR files and transfer

### Please share a sample of the data
(https://bhkindustry-my.sharepoint.com/:f:/p/ceo/Esjg1dZzFfRJh4nYLT2HDswB_dT5SMiSgAgUDQvzjqR-KQ?e=37b5I1)

### Confirm that this is a public dataset that can be retrieved by anyone on the Network
No

### If you chose not to confirm, what was the reason

Client data
### What is the expected retrieval frequency for this data
6-8 months 

### For how long do you plan to keep this dataset stored on Filecoin
1 to 1.5 years

### In which geographies do you plan on making storage deals
Europe

### How will you be distributing your data to storage providers
Lotus built-in data transfer

### How do you plan to choose SP
Big data exchange

### If you already have a list of storage providers to work with, fill out their names and provider IDs below
Livspect, Inc, f0104671, Tokyo, Japan, 10 TiB
WillTechMusing, f08399, South Korea, 10 TiB

### How do you plan to make deals to your storage providers
Boost client

### Can you confirm that you will follow the Fil+ guideline
Yes

**Comment by Sunnyiscoming** [comment]
Hi @kevzak
This is a Fil-E project.

**Comment by kevzak** [comment]
Hi @BHK-Industry - please reply to the email I sent to confirm client registration KYC. 

You have already passed the Diro KYB, thank you for completing.

Also, looking at your application you will need to list SPs involved and the storage plan in this private dataset project. SP miner IDs, locations, number of copies each. If you need help finding SPs, let us know.

**Comment by kevzak** [comment]
Here is [a list of E-Fil working group SPs.](https://docs.google.com/spreadsheets/d/1rwT9ie6qlOM9hVUkYZLGej523X1pMenaVKhFuvQOiNE/edit#gid=442291216) Feel free to reach them in Slack 

You can also check for SPs in slack:
#fil-deal-market
#global-storage-provider-community

Once you are ready with the storage plan, let me know and I will trigger notaries to review.

**Comment by cbtan21** [comment]
@kevzak Hi Kevin, @BHK-Industry has found a SP to store his data on [BDE](https://www.bigdataexchange.io/detail/20230223307098). May you kickstart his review process? Let me know how I can help. Happy to onboard more data into our ecosystem.

**Comment by kevzak** [comment]
> @kevzak Hi Kevin, @BHK-Industry has found a SP to store his data on [BDE](https://www.bigdataexchange.io/detail/20230223307098). May you kickstart his review process? Let me know how I can help. Happy to onboard more data into our ecosystem.

@cbtan21 - sounds good. The next step is for @BHK-Industry and/or the lead SP selected from BDE to update the application above to include Data and SP details:
How big is dataset?
How many copies?
How many locations?

For each SP, include details: miner ID, business, location

For private datasets, notaries expect full disclosure of the storage plan.

**Comment by BHK-Industry** [comment]
Dataset size 10 TiB
Number of copies: 1
Location: BHK Industry's data is located in Europe

**Comment by kevzak** [comment]
@BHK-Industry I'll refer you to guidelines for Fil+: https://github.com/filecoin-project/filecoin-plus-large-datasets

**Comment by BHK-Industry** [comment]
Thanks @kevzak! I've edited the comment according to the guidelines.

**Comment by kevzak** [comment]
> Thanks @kevzak! I've edited the comment according to the guidelines.

More recommendations for you @BHK-Industry: 
1) You'll need to share the SP miner ID, business name, location
2) You'll also be asked to find more SPs before notaries will sign off. 

Here is an example from another project: https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1212#issuecomment-1380778468

If you need help finding qualified SPs, there are multiple resources:
- [LINK](https://docs.google.com/spreadsheets/d/1rwT9ie6qlOM9hVUkYZLGej523X1pMenaVKhFuvQOiNE/edit#gid=442291216) to E-Fil+ SP WG members
- Slack #global-storage-provider-community
- Slack #fil-deal-market

**Comment by BHK-Industry** [comment]
@kevzak Should I looking for SPs for the total 1 PiB dataset or 10 TiB chunckwise?

**Comment by BHK-Industry** [comment]
I see, thank you. I was just wondering, because SPs did not bid on BDE for the remaining copies. I thought the dataset of 10 TB might be too small for them.

**Comment by kevzak** [comment]
Yes, that is very likely not worth it.

**Comment by kevzak** [comment]
Let us know if you need help @BHK-Industry we can setup a call or slack discussion with PL support team.

**Comment by BHK-Industry** [comment]
@kevzak Yes, we need some help with data transfer to the SPs. I would be happy if you could setup a call.

**Comment by BHK-Industry** [comment]
@kevzak We are working with Dcent to transfer the data as fast as possible. The only missing requirement for the application is to find 5-6 SPs for the dataset, right? Thanks!

**Comment by BHK-Industry** [comment]
> This application has not seen any responses in the last 10 days. This issue will be marked with Stale label and will be closed in 4 days. Comment if you want to keep this application open.

We want to keep the application open.

**Comment by BHK-Industry** [comment]
We would like to keep the application open, Hidde is on holiday. > Comment

**Comment by clriesco** [comment]
Removed stale label and reopened issue :)
