### ISSUE TITLE
[DataCap Application] BHK Industry GmbH

### ISSUE THREAD

**Issue by BHK-Industry** [filecoin-project/filecoin-plus-large-datasets#1589]
### Data Owner Name
BHK Industry GmbH

### Data Owner Country/Region
Germany

### Data Owner Industry
IT & Technology Services

### Website
[https://www.bhkindustry.com](https://www.bhkindustry.com)

### Social Media
@BHK-Industry (--)

### Total amount of DataCap being requested
1 PiB

### Weekly allocation of DataCap requested
10 TiB

### On-chain address for first allocation
f3waep5r2qf4hvfgslvvieesvsb6mocgyl3gz2c73kqu72tmqv2yhdxez436fr7v6jd6vumgsmdiywp76ivvoa

### Custom multisig
No

### Share a brief history of your project and organization
Encrypted Client Data 
Own IT Cloud Storage Solution

### Is this project associated with other projects/ecosystem stakeholders?
No

### Describe the data being stored onto Filecoin
Encrypted Client Data in 101 GB chunks 

### Where was the data currently stored in this dataset sourced from
My own storage infra

### How do you plan to prepare the dataset
lotus

### Please share a sample of the data
--

### Confirm that this is a public dataset that can be retrieved by anyone on the Network
No

### What is the expected retrieval frequency for this data
Daily

### For how long do you plan to keep this dataset stored on Filecoin
1 to 1.5 years

### In which geographies do you plan on making storage deals
Europe

### How will you be distributing your data to storage providers
Lotus built-in data transfer

### How do you plan to choose SP
Big data exchange

### How do you plan to make deals to your storage providers
Boost client

### Can you confirm that you will follow the Fil+ guideline
Yes

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Can you show us visible proof of the size of your data and the storage systems you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230337462961356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!

**Comment by BHK-Industry** [comment]
Hi cryptowhizzard

@Kevin-FF-USA is onboarding us to File-E. Thank you!

https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1196

**Comment by lvschouwen** [comment]
@BHK-Industry 
So this issue can be closed then? 😄

**Comment by BHK-Industry** [comment]
@lvschouwen Yes, thank you!
