### ISSUE TITLE
[DataCap Application] Impossible Cloud GmbH - Own disaster recovery

### ISSUE THREAD

**Issue by Whiterabbit5264** [filecoin-project/filecoin-plus-large-datasets#1590]
### Data Owner Name

Impossible Cloud GmbH

### Data Owner Country/Region

Germany

### Data Owner Industry

IT & Technology Services

### Website

impossiblecloud.com

### Social Media

```text
LinkedIn: https://www.linkedin.com/company/impossiblecloud/mycompany/
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

150TiB

### On-chain address for first allocation

f1ikkftumztbq6uzr2zmguwodzstbtr6jihcoiedy

### Custom multisig

- [x] Use Custom Multisig

### Identifier

E-fil

### Share a brief history of your project and organization

```text
We provide an enterprise-grade, S3-compatible object storage.
We intend to use Filecoin as part of our disaster recovery strategy.
```

### Is this project associated with other projects/ecosystem stakeholders?

Yes

### If answered yes, what are the other projects/ecosystem stakeholders

```text
Protocol Labs is one of our key investors.
```

### Describe the data being stored onto Filecoin

```text
Encrypted snapshot data from our customers.
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### How do you plan to prepare the dataset

IPFS, lotus, I don't know yet

### Please share a sample of the data

```text
After an NDA, we can share sanitized samples.
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [ ] I confirm

### If you chose not to confirm, what was the reason

```text
This is customer data, i.e., this should not be retrieved by anyone but us.
```

### What is the expected retrieval frequency for this data

Sporadic

### For how long do you plan to keep this dataset stored on Filecoin

More than 3 years

### In which geographies do you plan on making storage deals

North America, Europe

### How will you be distributing your data to storage providers

IPFS, Lotus built-in data transfer, I don't know yet

### How do you plan to choose storage providers

Slack

### If you already have a list of storage providers to work with, fill out their names and provider IDs below

```text
Orange County, CA: CES Group Inc. (f01611097)
Boston, MA: Nebula Block (f02401)
Minneapolis, MN: Dukesoft (f01392893)
Dallas, TX: GreaterHeat (f01877571)
```

### How do you plan to make deals to your storage providers

Lotus client, I don't know yet

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Whiterabbit5264** [comment]
Please see our main engineer's Github as well (@jkoelker). 

Going forward we would like to use Multisig as well.

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Looking at your application i have some questions:
As you are brand new on Github and have no history of past applications it seems to me that applying for 5PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?

Can you show us visible proof of the size of your data and the storage systems you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230337462961356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!

**Comment by lvschouwen** [comment]
@kevzak 
This one is for FIL-E

**Comment by Whiterabbit5264** [comment]
Hi Cryptowhizzard, 
Thanks for the quick response. 

For clarity and as mentioned by @lvschouwen, we also registered for E-Fil - I believe @kevzak is already taking a look at that. 

Following my thoughts on your questions:
- Re Github, please review (one of) my colleague's profile: @jkoelker.
- Re size of data, yes we can. I suggest we get in touch for an NDA.
- Re form, filled it out as requested.

Let me know in case of open questions at any time. 
Many thanks

**Comment by kevzak** [comment]
Hello - A note for notaries: I can confirm that @Whiterabbit5264 and Impossible Cloud have completed a full KYC Registration and KYB check via Diro.io

**Comment by kevzak** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 150TiB

**Client address**

>f1ikkftumztbq6uzr2zmguwodzstbtr6jihcoiedy

**Comment by Whiterabbit5264** [comment]
Hi all, 
To add information on the above application - we aim to store 25% of the data at a given SP. 
As Filecoin recommends to store 3 copies of data, we are thinking about involving 12 nodes / SPs.
Do not hesitate to reach out in case of any open questions

**Comment by kevzak** [comment]
## Datacap Request Trigger
#### Total DataCap requested 
> 5PiB
#### Expected weekly DataCap usage rate 
> 150TiB
#### Client address
> f1ikkftumztbq6uzr2zmguwodzstbtr6jihcoiedy

**Comment by kevzak** [comment]
1st allocation assignment: Let's move forward with the updated E-Fil notary SLA (https://github.com/filecoin-project/notary-governance/discussions/807) and assign randomly:

@derricktan23
@liyunzhi-666
@Fatman13

Please note: this comment completed the required E-Fil+ [KYC/KYB ](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1590#issuecomment-1431038609)
Please review the application and leave a comment for or against the plan by Feb 17th.

**Comment by liyunzhi-666** [comment]
It's great to see customers completing KYC/KYB through the tool.
Since it is the first round, there are not many restrictions. You mentioned that you will be looking for 12 SPs, can you share their geographic location and ID in the comments? @Whiterabbit5264

**Comment by Fatman13** [comment]
Hello, efil+ applicant, 

I see three SP you listed... 

> CES Group Inc. (f01611097)
> Nebula Block (f02401)
> Dukesoft (f01392893)

None of them has registered their multiaddress on-chain. How do you plan on retrieving data with them?

> How do you plan to prepare the dataset
> How will you be distributing your data to storage providers
> How do you plan to make deals to your storage providers

For all the above questions you answered with "you don't know". How do you plan to acquire relevant technical know-how to execute your storage plan?

> Where was the data currently stored in this dataset sourced from
> My Own Storage Infra

What are the exact kind of data you mean by "storage infra"? Can you please share some sample data?

**Comment by derricktan23** [comment]
Hi @Whiterabbit5264

I have few questions :
a. Requesting 5 PB of datacap is an important request. Can you provide reasons why you may need such large capacity?
b. Are you new to the Filecoin ecosystem, have you ever applied for datacap with another GitHub account name?

**Comment by Whiterabbit5264** [comment]
_Responding individually:_
Hi @liyunzhi-666, we will only be storing in the US. 
Our first 4 SPs are CES Group Inc. (f01611097), Nebula Block (f02401), Dukesoft (f01392893), GreaterHeat (f01877571) and we are currently seeking more SPs on the market.

**Comment by Whiterabbit5264** [comment]
Hi @Fatman13, 
Re retrieval and technical know-how, happy to loop in my colleague Jason on this @jkoelker.
We have our own storage infrastructure at a data center and plan to use filecoin in our disaster recovery strategy. 
Happy to share sample data once we set up an NDA

**Comment by Whiterabbit5264** [comment]
Hi @derricktan23,
As mentioned above, we have our own storage infrastructure and plan to use filecoin as a disaster recovery strategy - hence the large amount. Happy to share sample data once we set up an NDA

**Comment by jkoelker** [comment]
We're still figuring alot of the nuts and bolts of the implementation, but the high level technical is:

* We will maintain a private IPFS cluster that is peered to the SPs
* At the TBD backup interval, we will encrypt the data and load it into our IPFS cluster via a UnixFS DAG to provide a lookup tree (TBD if we will use kubo for this step or manually create the DAG in our code)
*  Snapshot the DAG head into a CAR file(s)
* Make the storage deal through Lotus with the CID of the CAR
* SP will pull from the IPFS peer

Retreival will be the same but in reverse, making the deal then pulling from the IPFS peer (although some SPs have also offered other transport options, TBD if we'd use those or not).

Re the size of the request, due to it being a component of a disaster recovery strategy, we will employ a rotation akin to GFS rotation (the exact scheme is till TBD) via storage deal length, and renewal of deals for specific archives to achieve our disaster recovery goals.

**Comment by Whiterabbit5264** [comment]
Thanks @jkoelker for the explanation. 
One additional note - aside from the automatic mechanism, we never applied for Fil+.

**Comment by liyunzhi-666** [comment]
> _Responding individually:_ Hi @liyunzhi-666, we will only be storing in the US. Our first 4 SPs are CES Group Inc. (f01611097), Nebula Block (f02401), Dukesoft (f01392893), GreaterHeat (f01877571) and we are currently seeking more SPs on the market.

In FiL+, the client will be asked to store the data in different regions. I would like to know if it is against E-FiL+ rules for customers to store only in the same region. @kevzak

**Comment by kevzak** [comment]
Hello @liyunzhi-666 : E-Fil+ follows the same guidelines as Fil+ 

Guidelines from https://github.com/filecoin-project/filecoin-plus-large-datasets

_Best practice for storing large datasets includes ideally, storing it in 3 or more regions, with 4 or more storage provider operators or owners, and having at least 5 replicas of the dataset. No more than one replica should be stored with one SP ID, and if the data cannot leave a particular geographic boundary, then it is expected that replication will still happen across different locations (cities, datacenters, etc.). If you cannot follow these practices due to policy or any other issues, you may explain your case in the application and provide to the community what method you can do instead. These are recommendations and not strict rules that every client must follow._

**Comment by liyunzhi-666** [comment]
thanks Kevin.
hey @Whiterabbit5264  I suggest you make changes and follow the rules.Guidelines from https://github.com/filecoin-project/filecoin-plus-large-datasets
In summary, I will not be signing this round until the client finds the right SPs.
cc @kevzak

**Comment by Whiterabbit5264** [comment]
Hi @liyunzhi-666, thank you very much for your feedback. 
Could you provide some additional explanation on your decision? 
If I understand correctly, we are precisely following the recommendation (at least 4 different SPs and storing across multiple locations). 
The choice to go with 12 different SPs is an additional security measure we want to put in place - i.e., is our voluntary choice to increase the number of fail-safes in addition to the above recommendation.

**Comment by cryptowhizzard** [comment]
I think there is a misunderstanding here. Dukesoft is not in the US , it is in EU. @liyunzhi-666 thinks you intend to store your whole allocation in the US , but i think that what you mean to say is that you will start in the US but that you will spread the first allocation over the 4 sp's you mentioned?

**Comment by kevzak** [comment]
If this is the case, this is a good point @cryptowhizzard. We can avoid future confusion by adding a requirement to the application labels above of: 

 | SP ID | SP org | SP region |

@Whiterabbit5264 if you could update your application above with this info? Location is key. Thanks for pushing through with these requests of the pilot.

@simonkim0515 cc'ing you for feedback to application.

**Comment by Fatman13** [comment]
> We're still figuring alot of the nuts and bolts of the implementation

We should expect that this efil+ will be distributing fairly slowly for the first couple month right?

> Happy to share sample data once we set up an NDA

Can you please share it with either yu.leng@guazi.io or @Fatman13 on filecoin Slack?

Other than the above I'd happy to approve the first round of this application.

**Comment by derricktan23** [comment]
@Whiterabbit5264 
1. I noticed that the application only lists three SPS instead of four, and it seems that GreaterHeat (f01877571) is missing.

 2. As per kevzak's suggestion, an update your application with more region information,This could help us better understand how the pilot is performing in different regions and make any necessary adjustments.

3.  Would it be possible for you to share the sample data with @derrick [OriginStorage] on the Filecoin Slack? 
 I am happy to sign any necessary NDA to ensure the confidentiality of the data.

**Comment by Whiterabbit5264** [comment]
Hi all, 
Thanks for the feedback - following all requests and thoughts:
- Data generation: First few weeks will be less busy, i.e., thorough testing needs to be done. if all goes well, Q2 will pick up significantly. 
- Data sharing: Reached out to derrick offline (slack) for NDA and data sharing
- SPs and their region: Added GreaterHeat and all respective locations

**Comment by Fatman13** [comment]
> Data sharing: Reached out to derrick offline (slack) for NDA and data sharing

+1 here too.

**Comment by kevzak** [comment]
> Hi all, Thanks for the feedback - following my comments on the above requests:
> 
> * Data generation: First few weeks will be less busy, i.e., thorough testing needs to be done. If all goes well, Q2 will pick up significantly.
> * Data sharing: Reached out to derrick offline (slack) for NDA and data sharing
> * SPs and their region: Added GreaterHeat and all respective locations

Lets us know @derricktan23 after review. Thanks

**Comment by Fatman13** [comment]
@kevzak Only one notary is needed to check the data? I have requested for a check too.

**Comment by Tom-OriginStorage** [comment]
there may be some delay in the process, filled up the NDA , but havent gotten back from Whiterabbit5264. 
@Fatman13  yes, perhaps you may followup with the checking of data, if only one notary is needed. Thanks.

**Comment by Whiterabbit5264** [comment]
Thanks for checking in everyone. 
We experience a minor delay in the process as @jkoelker is traveling at the moment. 
We will get back to you @derricktan23 early next week. 
If you want to get a look at the data as well @Fatman13 - happy to provide it to you when you send me your email address for the NDA

**Comment by kevzak** [comment]
> @kevzak Only one notary is needed to check the data? I have requested for a check too.

There are two required signatures @Fatman13 . I viewed [this request](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1590#issuecomment-1434412808) under your comment and thought you had triggered the proposal. My mistake.

Everything seems good - you and Derrick are waiting for review.

**Comment by kevzak** [comment]
Two additional comments: @Tom-OriginStorage I'm curious is there a reason you are involved? You are not an E-Fil+ Notary

Also, I do not know why this [2nd request was triggered](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1590#issuecomment-1434412808). Need to follow up with @fabriziogianni7 @panges2

**Comment by Fatman13** [comment]
> If you want to get a look at the data as well @Fatman13 - happy to provide it to you when you send me your email address for the NDA

It's yu.leng@guazi.io. Thank you!

**Comment by derricktan23** [comment]
> Two additional comments: @Tom-OriginStorage I'm curious is there a reason you are directly involved? Supporting Derrick? You can comment, but you are not an E-Fil+ Notary
yes Kevin, yes, he's supporting, understood the point that he's not an E-Fil+ Notary. Thanks.

**Comment by kevzak** [comment]
Any update on data checks here @Whiterabbit5264 ? Let me know if you need some support.

**Comment by Whiterabbit5264** [comment]
Thanks @kevzak for checking in. 
We sent the data to both @derricktan23 and @Fatman13. Since then I am waiting on an update from their side.

**Comment by jkoelker** [comment]
> Sorry for the late reply. I might be ill-equipped with knowledge to check data on AWS given the technical instructions. Hope other notary could cover the technical data checking.

Hi @Fatman13 the file is about 20GiB in size, if you have a GPG key I can encrypt it and send you a link to it on another platform, just let me know how you would like for me to transfer the file to you.

**Comment by Fatman13** [comment]
I think I understand GPG is a quite popular choice (also used by Github), but I am not familiar with how to use it to encrypt properly. Maybe efil+ program could instrument some kind of data checking framework between notary and client?

**Comment by kevzak** [comment]
Let's move forward with the update notary SLA (https://github.com/filecoin-project/notary-governance/discussions/807) and assign randomly:

@cryptowizzard
@xingjitansuo

The applicant is willing to send data samples, please reach out and leave a comment as needed. Please comment by March 14th. Thanks!

**Comment by Whiterabbit5264** [comment]
Thanks @kevzak for pushing this forward. 
Pleasure to e-meet @cryptowhizzard and @xingjitansuo. 
So far I have not heard anything, so feel free to reach out on slack or mail for any questions.

**Comment by kevzak** [comment]
No word from @cryptowhizzard @xingjitansuo. Let's move forward with the update notary SLA (https://github.com/filecoin-project/notary-governance/discussions/807) and assign randomly:

@swatchliu
@blockmakeronline

This is an initial allocation review. The applicant is willing to send data samples, please reach out and leave a comment as needed. Please comment by March 17th. Thanks!

**Comment by cryptowhizzard** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaarsrga6bu5fz6k4sltabvtvdiiivqbwle5zmxii3upd3i4la2me 
#### Address 
> f1ikkftumztbq6uzr2zmguwodzstbtr6jihcoiedy
#### Datacap Allocated
> 150.00TiB
#### Signer Address
> f1krmypm4uoxxf3g7okrwtrahlmpcph3y7rbqqgfa
#### Id
> b7ee8332-5323-46a5-9977-e5c6e64805a1
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaarsrga6bu5fz6k4sltabvtvdiiivqbwle5zmxii3upd3i4la2me

**Comment by BlockMakeronline** [comment]
@kevzak There was a problem with the approval. Please allow more notaries to join before the problem are fixed.

**Comment by Whiterabbit5264** [comment]
Thanks for the response @BlockMakeronline - what was the problem?

**Comment by kevzak** [comment]
@BlockMakeronline we will have to wait until your issue is fixed, @panges2 knows about it. Also no word from @swatchliu

Let's move forward with the update notary SLA (https://github.com/filecoin-project/notary-governance/discussions/807) and assign randomly:
@aifabot-cloud
@laurarenpanda

Please review the application details for the Client, Data, and SPs and leave a comment. Please comment by March 21st. Thanks!

**Comment by Aifabot-Cloud** [comment]
@Whiterabbit5264 how did the first round of 150 TiB distribution go? It's a bit odd that there're no records. BTW, the second allocation has already been proposed. I don't think @cryptowhizzard should be signing on this one.
cc'ing @kevzak

**Comment by Whiterabbit5264** [comment]
Thanks @Aifabot-Cloud. According to verify.glif.io, we have not received the allocation yet 

![image](https://user-images.githubusercontent.com/122367932/226606883-d96d3608-b582-4a3f-b0be-b7131c503fa5.png)

**Comment by kevzak** [comment]
> @Whiterabbit5264 how did the first round of 150 TiB distribution go? It's a bit odd that there're no records. BTW, the second allocation has already been proposed. I don't think @cryptowhizzard should be signing on this one. cc'ing @kevzak

@Aifabot-Cloud this is a first allocation request. They haven't received datacap. The goal if for notaries to review the application for dataset being stored and storage plan. Also as part of E-Fil+ @Whiterabbit5264 has passed KYC/KYB so please keep that in mind.

**Comment by laurarenpanda** [comment]
- Different locations in the USA: okay with this geographical distribution
- SPs list: 4 SPs from different organizations
- KYC/KYB passed
- Data sample checked by other notaries

As this is the first round, I'd like to support this project and monitor its actual deal flow.

**Comment by Aifabot-Cloud** [comment]
> > @Whiterabbit5264 how did the first round of 150 TiB distribution go? It's a bit odd that there're no records. BTW, the second allocation has already been proposed. I don't think @cryptowhizzard should be signing on this one. cc'ing @kevzak
> 
> @Aifabot-Cloud this is a first allocation request. They haven't received datacap yet. Each application requires two notaries to sign.
> 
> The goal here is for notaries to review the application for dataset being stored and storage plan. Also as part of E-Fil+ @Whiterabbit5264 has passed KYC/KYB so please keep that in mind.
> 
> Also, @cryptowhizzard was assigned initially and is eligible to sign.

I saw the second round request was triggered that's why I was asking. 

Regarding the notary I mentioned - the signature was given after you announced moving on to the next two notaries. From my understanding, if the notary does not sign within the expected time then the round they are assigned to sign off on is over. Otherwise, it will affect the workflow of the next round of notaries. 

I would like things to get clearly outlined, so we can save a lot of time in communication.

**Comment by kevzak** [comment]
Hello @Aifabot-Cloud 

Yes, the second round notification is an issue with the bot. Apologies for any confusion.

Regarding the notary that signed, he was out of office for a personal matter, he slacked me directly, and said he would sign when he got back so I allowed.  We are following an SLA for this pilot but obviously things come up as all of the notaries are volunteering their time and energy here and have other obligations, so I am open to understanding here. In fact, perhaps we'll find after the pilot that 72 hours is not enough turn around time because of these factors.

**Comment by kevzak** [comment]
> * Different locations in the USA: okay with this geographical distribution
> * SPs list: 4 SPs from different organizations
> * KYC/KYB passed
> * Data sample checked by other notaries
> 
> As this is the first round, I'd like to support this project and monitor its actual deal flow.

@laurarenpanda does that mean you are signing here?

**Comment by laurarenpanda** [comment]
> > * Different locations in the USA: okay with this geographical distribution
> 
> > * SPs list: 4 SPs from different organizations
> 
> > * KYC/KYB passed
> 
> > * Data sample checked by other notaries
> 
> > 
> 
> > As this is the first round, I'd like to support this project and monitor its actual deal flow.
> 
> 
> 
> @laurarenpanda does that mean you are signing here? 

@kevzak Yes, I'll sign this project. 
A few hours later. Wouldn't be too long.

**Comment by laurarenpanda** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedtixmwopg53noayaqyas2gvivqdw43j2jxqoogui7eb6nm6rb4xe 
#### Address 
> f1ikkftumztbq6uzr2zmguwodzstbtr6jihcoiedy
#### Datacap Allocated
> 150.00TiB
#### Signer Address
> f1bp3tzp536edm7dodldceekzbsx7zcy7hdfg6uzq
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedtixmwopg53noayaqyas2gvivqdw43j2jxqoogui7eb6nm6rb4xe

**Comment by laurarenpanda** [comment]
Emmm...
Something has gone wrong with the SSA Bot.
Waiting for fixing and would like to sign it again.

**Comment by kevzak** [comment]
> Emmm... Something has gone wrong with the SSA Bot. Waiting for fixing and would like to sign it again.

Should be good @laurarenpanda thanks. @Whiterabbit5264 let us know if you did not receive DataCap here.

**Comment by Whiterabbit5264** [comment]
Apologies, we are still working on the S3-API in the background. 
This is **slightly** more complicated than envisioned. 
Anyhow, to keep up with our application, we will upload data in the upcoming days

**Comment by Whiterabbit5264** [comment]
Yes, please keep open

**Comment by clriesco** [comment]
Removed stale label and reopened issue :)
