### ISSUE TITLE
Client Allocation Request for: PiKNiK

### ISSUE THREAD

**Issue by scharfstein** [filecoin-project/filecoin-plus-large-datasets#1591]
# Client Allocation Questions

## Core Information
- Name: PiKNiK
- Website / Social Media: [https://www.piknik.com/](https://www.piknik.com/), (@piknikcompany, LinkedIn)
- Region: North America
- DataCap Requested: 730 GiB
- Addresses to be Notarized: f1pakqdbs44c4vue4o527gzwckzn2orczq4d6e2ty
- Notary Requested: Xinan Xu

**Comment by scharfstein** [comment]
@raghavrmadya @simonkim0515 I just completed the form at https://filplus.storage/
 for this request and it ended up in the wrong place on Github. Pls advise on what I should do.

**Comment by flyworker** [comment]
you can close the issue.

**Comment by timelytree** [comment]
Hi everyone, the form at https://filplus.storage now correctly submits application requests of <100TiB to the [correct repo](https://github.com/filecoin-project/filecoin-plus-client-onboarding) 🙂
