### ISSUE TITLE
[DataCap Application] ] Cabrina-HRRR Open Dataset <2/7> 

### ISSUE THREAD

**Issue by NiwanDao** [filecoin-project/filecoin-plus-large-datasets#1592]
### Data Owner Name

Cabrina

### Data Owner Country/Region

China

### Data Owner Industry

Life Science / Healthcare

### Website

 https://dstorage.cabrina.xyz/

### Social Media

```text
https://dstorage.cabrina.xyz/
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

800TiB

### On-chain address for first allocation

f1vjjczm7nqvfkkpbponvvmk4mqdrf7z4e52eil6y

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
- I am an active participant in Slingshot and Slingshot Restore. This experience has gained me a lot of knowledge as a data preparer, deal SP, and retrieval client. I fully understand and obey the rule of FIL+. 
- I have established a relationship with other community members along the way and have successfully sent deals with over 60 SPs worldwide.
- With the surge of requests from other SPs on deal-making and the value of storing humanity’s most important data permanently, I decided to bring HRRR datasets to the network.
- I will track deals and provide retrieval access through https://dstorage.cabrina.xyz/.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
> The High-Resolution Rapid Refresh (HRRR) is sourced by Global System Laboratory from National Oceanic && Atmospheric Administration. It is a NOAA real-time 3-km resolution, hourly updated, cloud-resolving, convection-allowing atmospheric model, initialized by 3km grids with 3km radar assimilation. Radar data is assimilated in the HRRR every 15 min over a 1-h period adding further detail to that provided by the hourly data assimilation from the 13km radar-enhanced Rapid Refresh. 
> HRRR dataset stored on AWS is the archive since 2014 with a total size of 2PiB and 38526457 Object.
> I plan to send 10x copies, each for 2PiB raw data. Since there is a conversion rate between the raw data size and Datacap consumption size, each copy would require around 3.5PiB Datacap, with a total amount of  35PiB Datacap.
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### How do you plan to prepare the dataset

graphsplit

### Please share a sample of the data

```text
https://registry.opendata.aws/noaa-hrrr-pds/
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Sporadic

### For how long do you plan to keep this dataset stored on Filecoin

1.5 to 2 years

### In which geographies do you plan on making storage deals

Greater China, North America, Australia (continent)

### How will you be distributing your data to storage providers

HTTP or FTP server, Shipping hard drives

### How do you plan to choose storage providers

Slack, Big data exchange, Partners

### If you already have a list of storage providers to work with, fill out their names and provider IDs below

```text
I work with SP including but not limited to FL cloud, GreaterHeat, Filet, Chenxi,Dong.I will continue look for new SP from the offline community and online BDE platform. 
The partner I previously worked with are listed in https://dstorage.cabrina.xyz/sp/
```

### How do you plan to make deals to your storage providers

Boost client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by flyworker** [comment]
https://dstorage.cabrina.xyz/ is not accessible, can you please check your website?
<img width="1382" alt="image" src="https://user-images.githubusercontent.com/8363795/218086616-be7cfeee-0283-4743-9d11-91cd86867a77.png">

**Comment by xingjitansuo** [comment]
@flyworker Thanks for checking and pointing out the issue. The website is up again.

**Comment by simonkim0515** [comment]
## Datacap Request Trigger

#### Total DataCap requested 
> 5PiB

#### Expected weekly DataCap usage rate 
> 800TiB 

#### Client address
> f1vjjczm7nqvfkkpbponvvmk4mqdrf7z4e52eil6y

**Comment by kernelogic** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacear2ina6yd4j7hgtsvbv3l3ack6pmoaaj7uty5az45lq2wkl76ufi 
#### Address 
> f1vjjczm7nqvfkkpbponvvmk4mqdrf7z4e52eil6y
#### Datacap Allocated
> 256.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### Id
> 3005f8b7-0451-446d-95a6-824abbefa8a2
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacear2ina6yd4j7hgtsvbv3l3ack6pmoaaj7uty5az45lq2wkl76ufi

**Comment by cryptowhizzard** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedqxpxybugssirevfnwkmcx4aan34jlgk5eebukam5khjjg3epjlw 
#### Address 
> f1vjjczm7nqvfkkpbponvvmk4mqdrf7z4e52eil6y
#### Datacap Allocated
> 256.00TiB
#### Signer Address
> f1krmypm4uoxxf3g7okrwtrahlmpcph3y7rbqqgfa
#### Id
> 3005f8b7-0451-446d-95a6-824abbefa8a2
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedqxpxybugssirevfnwkmcx4aan34jlgk5eebukam5khjjg3epjlw

**Comment by woshidama323** [comment]
checker:manualTrigger

**Comment by woshidama323** [comment]
Hi @xingjitansuo  
Suggest you should adjust the proposal strategy to fix this warning at the next round
 "87.36% of deals are for data replicated across less than 3 storage providers"

**Comment by newwebgroup** [comment]
checker:manualTrigger

**Comment by flyworker** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb6b7nlstnmzznlochx7tp3a2zal36khzwycoo5f3x7gz6ryyczja 
#### Address 
> f1vjjczm7nqvfkkpbponvvmk4mqdrf7z4e52eil6y
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f1hlubjsdkv4wmsdadihloxgwrz3j3ernf6i3cbpy
#### Id
> 0d6f3a5b-d366-4765-a7ec-310556f91909
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb6b7nlstnmzznlochx7tp3a2zal36khzwycoo5f3x7gz6ryyczja

**Comment by xingjitansuo** [comment]
Thanks for asking and the answer is definitely Yes. > I see the Deal Data Replication slightly improved but still very high
> 
> 
> 
> 
> 
> ⚠️ 85.59% of deals are for data replicated across less than 3 storage providers.
> 
> 
> 
> @xingjitansuo  will you do more work to improve it?

**Comment by igoovo** [comment]
![1679129249834](https://user-images.githubusercontent.com/103082537/226095532-fac14bce-13ad-4d77-9c76-35f0db96b9fd.jpg)


![1679129373384](https://user-images.githubusercontent.com/103082537/226095543-43cde014-2d2a-4d7b-9f7d-8f1f0bbddc0f.jpg)

**Comment by igoovo** [comment]
Can be retrieved, everything looks normal, supported

**Comment by igoovo** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced2ffrtlfnfbtah2e4pswi2fjhvr25245jrzgtquebif6vdpu6ca6 
#### Address 
> f1vjjczm7nqvfkkpbponvvmk4mqdrf7z4e52eil6y
#### Datacap Allocated
> 1.00PiB
#### Signer Address
> f1shnsfayxqll77svffaxnjenms7bbbysbqcatrpy
#### Id
> 25902f65-b1d1-4949-9286-0b218c5d4b63
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced2ffrtlfnfbtah2e4pswi2fjhvr25245jrzgtquebif6vdpu6ca6

**Comment by kernelogic** [comment]
CID checker result looks good across all the applications in the same series.

**Comment by OpenGate01** [comment]
checker:manualTrigger

**Comment by OpenGate01** [comment]
⚠️ 65.63% of deals are for data replicated across less than 4 storage providers.Will you do more work to improve it?

**Comment by xingjitansuo** [comment]
@OpenGate01 Thanks for asking. It will improve in the next tranche.

**Comment by OpenGate01** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebe5feel35vvy65znfvy6uflijwvdf5nvsqkgnxprclnrbebk2zsq 
#### Address 
> f1vjjczm7nqvfkkpbponvvmk4mqdrf7z4e52eil6y
#### Datacap Allocated
> 2.00PiB
#### Signer Address
> f1im4hmtbfzqnx7ir74kdaiu4ynjhgqh3sdi2snla
#### Id
> d2137099-b34f-48ce-9b95-aa02c09c4cf7
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebe5feel35vvy65znfvy6uflijwvdf5nvsqkgnxprclnrbebk2zsq

**Comment by kernelogic** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedbw6bmoccd7dkyo5tb56zs2i5gfzyfo67qoibxcsmqn252tovq2u 
#### Address 
> f1vjjczm7nqvfkkpbponvvmk4mqdrf7z4e52eil6y
#### Datacap Allocated
> 2.00PiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedbw6bmoccd7dkyo5tb56zs2i5gfzyfo67qoibxcsmqn252tovq2u

**Comment by NiwanDao** [comment]
checker:manualTrigger

**Comment by NiwanDao** [comment]
Clarification: f0142637 Deals duplication was due to a technical bug in the internal distribution system that happened in April. It has been fixed.

**Comment by 1ane-1** [comment]
[f02031063](https://filfox.info/en/address/f02031063) check its problem and repair it. This round will support you.

**Comment by Chuangshi1** [comment]
[f02031063](https://filfox.info/en/address/f02031063) check its problem and repair it. This round will support you.

**Comment by Chuangshi1** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceczrwq3de4d6afk3m5qznm7wtt74ie4wj4y2xmzs3u2itt63qme64 
#### Address 
> f1vjjczm7nqvfkkpbponvvmk4mqdrf7z4e52eil6y
#### Datacap Allocated
> 1.25PiB
#### Signer Address
> f1mdk7s2vntzm6hu35yuo6vjubtrpfnb2awhgvrri
#### Id
> 01a6ff5c-c13f-4ab0-b1ca-0e9b18f93003
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceczrwq3de4d6afk3m5qznm7wtt74ie4wj4y2xmzs3u2itt63qme64

**Comment by NiwanDao** [comment]
WIP

**Comment by NiwanDao** [comment]
WIP

**Comment by clriesco** [comment]
Removed stale label and reopened issue :)

**Comment by NiwanDao** [comment]
WIP

**Comment by NiwanDao** [comment]
WIP
