### ISSUE TITLE
[DataCap Application] Hepta - OpenNeuro

### ISSUE THREAD

**Issue by yhkp** [filecoin-project/filecoin-plus-large-datasets#1594]

**Comment by herrehesse** [comment]
Hello @yhkp !

Can you show me a list of the 20 SP's you contacted? Love to see who they are and where you want to store this valuable dataset. Will do further due diligence after the list. Please fill in like this:

| MinerID | Region | Continent | Business Entity Name |
| --- | --- | --- | --- |

**Comment by caoyoungyoung** [comment]
Can you provide more KYB info to prove your identity?

**Comment by herrehesse** [comment]
@yhkp Can you please help and answer my above question! Love to continue with the due diligence.

**Comment by simonkim0515** [comment]
## Datacap Request Trigger

#### Total DataCap requested 
> 5PiB

#### Expected weekly DataCap usage rate 
> 500TiB 

#### Client address
> f1es3jnh7ivhvc32s23mro7wuktehjkxlc7yjac6a

**Comment by yhkp** [comment]
Hello @herrehesse, Here are some SPs we are and will connecting with. including the region here. We are looking for and communicating with SPs through email/GitHub/Slack/offline. Whether they can store our data is based on their infrastructure or collateral or technical suit with us. lmk if you have any other concern. Thx.
f01225882 US
f01959735 US 
f01854080 US
f01543586 HK
f02033219 HK
f01985611 US
f01579009  KR
f01386984 CN
f01690643  KR
f02012175 KR
f01402814 HK
f01893023 US

**Comment by yhkp** [comment]
> Can you provide more KYB info to prove your identity?

@caoyoungyoung sure will do. 
This is my business license. Is there anything else needed?
<img width="678" alt="image" src="https://user-images.githubusercontent.com/121103586/220321595-f3b4abd5-29eb-4efb-9441-de141072ade6.png">

**Comment by yhkp** [comment]
FYI, welcome community members (SPs) connect with me if you are willing to cooperate with us in storing OpenNeuro Open Data.

**Comment by kernelogic** [comment]
First time seeing this dataset, checked license and it's open. Willing to support.

**Comment by kernelogic** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacea5fhca7gmgmlh6rwbdqlzrqsv3c34xfe26wio3qwnzb4gbouploc 
#### Address 
> f1es3jnh7ivhvc32s23mro7wuktehjkxlc7yjac6a
#### Datacap Allocated
> 250.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### Id
> f2371eca-b76a-4df1-9d90-378c71488e7e
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacea5fhca7gmgmlh6rwbdqlzrqsv3c34xfe26wio3qwnzb4gbouploc

**Comment by YuanHeHK** [comment]
I looked at this open source data and it looks pretty good. And I also randomly checked whether the three previously announced SPS support the search service. At the moment, they all seem to be FIL+ compliant. I will support you this time.
```
$./bin/lotus client query-ask f01225882
Ask: f01225882
Price per GiB: 0 FIL
Verified Price per GiB: 0 FIL
Max Piece size: 32 GiB
Min Piece size: 8 GiB
$./bin/lotus net connect f01225882
f01225882 -> {12D3KooWJFeoBixrAFY7tHs4PqriJktAhea12zfmGA9tcaBQ9p7p: [/ip4/135.84.176.14/tcp/23891]}
ERROR: failed to parse multiaddr "f01225882": must begin with /

$./bin/lotus net connect f01386984
f01386984 -> {12D3KooWHwhTmqq3eGnGkqSc75iiGDfH7RCsCPnuzbQqmUBTS549: [/ip4/112.132.159.12/tcp/48080]}
ERROR: failed to parse multiaddr "f01386984": must begin with /

$./bin/lotus client query-ask f01386984
Ask: f01386984
Price per GiB: 0.0000000005 FIL
Verified Price per GiB: 0.00000000005 FIL
Max Piece size: 32 GiB
Min Piece size: 256 B

$./bin/lotus net connect f01893023
f01893023 -> {12D3KooWLzGJ3Kei7AQRhUbLszVtJe7KwenWebFBoiSsy6eRWSmu: [/ip4/65.255.35.236/tcp/23456]}
ERROR: failed to parse multiaddr "f01893023": must begin with /

$./bin/lotus client query-ask f01893023
Ask: f01893023
Price per GiB: 0.0000000005 FIL
Verified Price per GiB: 0.00000000005 FIL
Max Piece size: 32 GiB
Min Piece size: 256 B

```

**Comment by YuanHeHK** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced2a44iq4eudk2sdkzspkkkpe2pguswfwtvqta5dq4iqpxjfmysx4 
#### Address 
> f1es3jnh7ivhvc32s23mro7wuktehjkxlc7yjac6a
#### Datacap Allocated
> 250.00TiB
#### Signer Address
> f1fg6jkxsr3twfnyhdlatmq36xca6sshptscds7xa
#### Id
> f2371eca-b76a-4df1-9d90-378c71488e7e
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced2a44iq4eudk2sdkzspkkkpe2pguswfwtvqta5dq4iqpxjfmysx4

**Comment by yhkp** [comment]
FYI, Because we didn't understand the application rules, we filled in the wrong f1 address in our application form. We will close this application and resubmit an application with the new f1 address.
