### ISSUE TITLE
[DataCap Application] FrogHub Public Buckets

### ISSUE THREAD

**Issue by FroghubMan** [filecoin-project/filecoin-plus-large-datasets#1597]
### Data Owner Name

FrogHub

### Data Owner Country/Region

China

### Data Owner Industry

Web3 / Crypto

### Website

https://dash.froghub.io/

### Social Media

```text
-website:https://froghub.io/files.html
-GitHub: https://github.com/orgs/froghub-io
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

350TiB

### On-chain address for first allocation

f1622ljfj6wczt4ge2aerxtcwxo3o72ozbsjyimdq

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
FrogHub files is a platform that will provide users with free storage, allowing users to enjoy free storage at the same time. Facilitating the Filecoin network to store more and more valuable public data sets.

About the FrogHub data set

FrogHub files is a user-oriented cloud storage platform. Any user with data storage needs can use the platform tools free of charge.

The Filecoin Network provides reliable, secure, and affordable decentralized storage, and FrogHub files wants to make it easy for users to store their data in the filecoin network.

Attracting traditional cloud and object-based storage users to the Filecoin network and benefiting from it is a challenge. FrogHub, as developers in the Felicoin ecosystem, needs to face this challenge together. We've been building useful tools to make it easier for users to store data on the Filecoin network.

Froghub files integrates a set of tools, including storage bucket, custom gateway, data encryption service KMS, static web deployment (under development), open API, to provide storage services compatible with cloud storage and object storage, providing better user experience and attracting more users.

About FrogHub

FrogHub has always defined itself as a tool developer and infrastructure builder in the Filecoin ecosystem. In 2019, we started to focus on technical solutions and development based on the IPFS protocol and Filecoin network. We have been working hard to become a qualified builder in the filecoin ecosystem.

Our team is a very pure development team, more than 90% of which are developers, more than half of whom have more than 5 years of development experience in communication, Internet, blockchain and other industries. We hope that we can gain users' recognition by exporting useful tools and platforms.

In order to contribute to the filecoin community, we have developed the open source sector repair tool Filecoin-Sealer-Recover and the nft free authoring platform NFT-Creator.
In addition, we plan to provide a sector browser for the community in 2023 and build the liquidity pledge platform STFIL on FVM.

See the links below for details.
- making: https://github.com/orgs/froghub-io
```

### Is this project associated with other projects/ecosystem stakeholders?

Yes

### If answered yes, what are the other projects/ecosystem stakeholders

```text
All data will be stored on the Filecoin network through the Filecoin Plus project. Therefore, the main ecosystem stakeholders are IPFS and Filecoin.
```

### Describe the data being stored onto Filecoin

```text
At the moment. The data stored through FrogHub files are mostly NFT and raw materials created by NFT creators, including pictures, GIFs, short videos, etc. The main source of this data is the NFT-Creator (we have completed the integration). Some users directly use FrogHub files to store data. They usually upload files directly (users already know that it is stored as public files) or use platform kms service for encrypted storage. Some users also access the service through open API. Data types are mainly pictures, short videos, pdf and large files.
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### Please share a sample of the data

```text
https://storage.froghub.io/team-1582303692638388224-default/WechatIMG483.jpeg
https://storage.froghub.io/nft-art-oldman2-my-nft-project/generate_image/assets/1.png
https://storage.froghub.io/nft-art-oldman2-my-nft-project/generate_image/assets/2.png
https://storage.froghub.io/nft-art-oldman2-my-nft-project/generate_image/assets/3.png
https://storage.froghub.io/nft-art-oldman2-my-nft-project/generate_image/assets/4.png
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

1.5 to 2 years

### In which geographies do you plan on making storage deals

Greater China

### How will you be distributing your data to storage providers

Shipping hard drives

### How do you plan to choose storage providers

Big data exchange

### How do you plan to make deals to your storage providers

Boost client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by herrehesse** [comment]
@FroghubMan Hello there, thank you for your application. As notary i am screening your application and doing due diligence.

Looking at your application i have some questions:

Applying for 5PB of datacap is a lot, the examples you provided would not require the amount of storage you are requesting. One needs comprehensive knowledge of Filecoin, packing data and it's requirements and distribution of the data. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?

Can you provide me with some KYC details per e-mail at [kyc@dcent.nl](mailto:kyc@dcent.nl). I would like to receive an e-mail from the original domainname / contact as listed on the website that refers to this application.
Can you show us some visible proof from the data size and the storage you have there?

Can you provide us with a distribution plan supposably that you would be granted datacap to store?

As you can see here : https://github.com/filecoin-project/filecoin-plus-large-datasets it states:

To make sure that you understand the rules and guidelines I would like to receive a detailed allocation plan where the amount of data and reputational SP's with business names and locations are stated.

Thank you.

**Comment by Sunnyiscoming** [comment]
Can you provide more data samples to prove that you have 5 PB already?
Can you provide more detailed informations about yourself and SPs you will cooperate with?

**Comment by FroghubMan** [comment]
@Sunnyiscoming Hello, I'm glad to have your attention.
We already have about 500 Tibs of raw data, of which more than 80% (about 400 TiBs) is unencrypted public data. We plan to store 6-10 copies of these data in SP in different parts of the world. And we take into account the growth of the data. So we applied for 5Pib

**Comment by FroghubMan** [comment]
At present, we have reached preliminary cooperation intention with some SP, for example: f01153105 f0827006 f01847516 f01708981 f01660795 f02016677. We are also looking for SP support from other regions.

**Comment by caoyoungyoung** [comment]
The data sample you provided only 5 pics, can you provide more proof to show you have sufficent data like you said above, mayby snapshot or link

**Comment by simonkim0515** [comment]
## Datacap Request Trigger

#### Total DataCap requested 
> 5PiB

#### Expected weekly DataCap usage rate 
> 350TiB 

#### Client address
> f1622ljfj6wczt4ge2aerxtcwxo3o72ozbsjyimdq

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

As last question i would like you to fill out [this form](https://form.jotform.com/230337462961356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!

**Comment by FroghubMan** [comment]
@caoyoungyoung This is a screenshot of some of the data
![109751676346737_ pic](https://user-images.githubusercontent.com/88960777/218635199-66c92120-3c4a-4025-9a60-30924ee139bf.jpg)

**Comment by FroghubMan** [comment]
@cryptowhizzard I have filled out the kyc form.If  need more information, please leave a message.

**Comment by FroghubMan** [comment]
@cryptowhizzard 
Thanks for the reminder. I will no longer cooperate with f01939377.

f0844271 hasn't really participated in FIl+ yet, SP promised us that it will open retrievals after storing real data. I think any Fil+ newbie should be given a chance.

Finally, there are other customers who want to participate in Fil+ and play by the rules. They're willing to create new nodes to store data for me. I hope you'll keep watching.

**Comment by FroghubMan** [comment]
@caoyoungyoung @herrehesse @cryptowhizzard Can I get your support? I would really appreciate it!

**Comment by FroghubMan** [comment]
@cryptowhizzard  
Added SP: f01302188
I have communicated with SP (f0844271) and they will start boost tomorrow

**Comment by cryptowhizzard** [comment]
Cool.

I will propose for approval in a second.

To be 100% clear ... f01302188, f0844271 ( They will set IP and enable tmrw ) , f02008876 and f02013352 will be used for sealing the first allocation

Good to see you starting and welcome to Filecoin!

**Comment by cryptowhizzard** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedqcut2is7kiy2ltogirizxzf4jrizdwdsbqmsifjkh7ziuef6spa 
#### Address 
> f1622ljfj6wczt4ge2aerxtcwxo3o72ozbsjyimdq
#### Datacap Allocated
> 175.00TiB
#### Signer Address
> f1krmypm4uoxxf3g7okrwtrahlmpcph3y7rbqqgfa
#### Id
> 769c61d0-c1f6-47a1-9adc-fdc7c92486c8
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedqcut2is7kiy2ltogirizxzf4jrizdwdsbqmsifjkh7ziuef6spa

**Comment by FroghubMan** [comment]
Cool ! Thanks！

**Comment by kernelogic** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced3kc7tmyimmn54opu2y5yani2z5slzzipummw4m5wh36fogcs3uq 
#### Address 
> f1622ljfj6wczt4ge2aerxtcwxo3o72ozbsjyimdq
#### Datacap Allocated
> 175.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### Id
> 769c61d0-c1f6-47a1-9adc-fdc7c92486c8
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced3kc7tmyimmn54opu2y5yani2z5slzzipummw4m5wh36fogcs3uq

**Comment by kernelogic** [comment]
FrogHub has reached out to me to prove this is the real account. They are dev grant recipient building in the community. Willing to support.

**Comment by FroghubMan** [comment]
@kernelogic @cryptowhizzard  thank you for your support!

**Comment by Carohere** [comment]
checker:manualTrigger

**Comment by Chuangshi1** [comment]
checker:manualTrigger

**Comment by Chuangshi1** [comment]
![6458719137b5c1d402d5f8b5df48c27a](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/112937825/ab8fa001-b321-46c4-939f-31539eb34745)

**Comment by Chuangshi1** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebgyoml3rc7x2zm3uh5htmpt6fqsbns5ytrt6iiczuwc4gxstc7lu 
#### Address 
> f1622ljfj6wczt4ge2aerxtcwxo3o72ozbsjyimdq
#### Datacap Allocated
> 350.00TiB
#### Signer Address
> f1mdk7s2vntzm6hu35yuo6vjubtrpfnb2awhgvrri
#### Id
> b2a41bf1-0a9e-4ed5-b521-5551354e02d8
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebgyoml3rc7x2zm3uh5htmpt6fqsbns5ytrt6iiczuwc4gxstc7lu

**Comment by luobin544** [comment]
![img_v2_337f564b-ddfd-41b1-9d30-f8fcc9704c8h](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/4277341/618a66db-ba0e-4031-9ad7-b8cc14588b02)

**Comment by luobin544** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedwp3yym5dvpdfeb3sbezwyc4wuqhshidlr54iydeylib7zrvbdwy 
#### Address 
> f1622ljfj6wczt4ge2aerxtcwxo3o72ozbsjyimdq
#### Datacap Allocated
> 350.00TiB
#### Signer Address
> f1tbd632f6w62glfaf7wjpimacbnjiz26poyoes2q
#### Id
> b2a41bf1-0a9e-4ed5-b521-5551354e02d8
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedwp3yym5dvpdfeb3sbezwyc4wuqhshidlr54iydeylib7zrvbdwy

**Comment by 1ane-1** [comment]
checker:manualTrigger

**Comment by 1ane-1** [comment]
![11f1ed73bb74c44c658324c21317989](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/91301211/962dc077-2cc8-4f7c-9290-ae7f2279fe86)

**Comment by 1ane-1** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceciwizxg6zl7ltfaywvtl7i66rm7hfhzkkaivb7urohdoynvyoa3i 
#### Address 
> f1622ljfj6wczt4ge2aerxtcwxo3o72ozbsjyimdq
#### Datacap Allocated
> 1.36PiB
#### Signer Address
> f1mdk7s2vntzm6hu35yuo6vjubtrpfnb2awhgvrri
#### Id
> cd0737b7-4243-47ca-a059-779ba46275a0
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceciwizxg6zl7ltfaywvtl7i66rm7hfhzkkaivb7urohdoynvyoa3i

**Comment by SuperChaiChai** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaxxjmsj5xd6zm5cty4tgwcru2m35723eujwbpatmlmq33ixek7jw 
#### Address 
> f1622ljfj6wczt4ge2aerxtcwxo3o72ozbsjyimdq
#### Datacap Allocated
> 1.36PiB
#### Signer Address
> f12mckci3omexgzoeosjvstcfxfe4vqw7owdia3da
#### Id
> cd0737b7-4243-47ca-a059-779ba46275a0
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaxxjmsj5xd6zm5cty4tgwcru2m35723eujwbpatmlmq33ixek7jw

**Comment by herrehesse** [comment]
checker:manualTrigger

**Comment by Bitrise0111** [comment]
The check report shows health

**Comment by Bitrise0111** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced3rbbxzm3axzzyoagjenglwa3wdnj4j35k2p2j2swuuhgj5kadfq 
#### Address 
> f1622ljfj6wczt4ge2aerxtcwxo3o72ozbsjyimdq
#### Datacap Allocated
> 2.73PiB
#### Signer Address
> f1nknj7ayq4o43czrtdoauggtwl43fbqatmqis3yy
#### Id
> bcd0f6f7-6e0e-4d88-9ffa-5f871dca6d73
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced3rbbxzm3axzzyoagjenglwa3wdnj4j35k2p2j2swuuhgj5kadfq

**Comment by mikezli** [comment]
![b8e6742156bff88c346e5a4f9f7219f](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/118169683/9746adf3-5567-4c41-9c53-550cbbd7a9ee)
Customers contact me, I am willing to support this round temporarily, will keep an eye on

**Comment by mikezli** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebolmcid6ooeftq4ha4b22xlarqazkzjmfmo7vpyhttpk53mgc2ja 
#### Address 
> f1622ljfj6wczt4ge2aerxtcwxo3o72ozbsjyimdq
#### Datacap Allocated
> 2.73PiB
#### Signer Address
> f1dnb3uz7sylxk6emti3ififcvu3nlufnnsjui6ea
#### Id
> bcd0f6f7-6e0e-4d88-9ffa-5f871dca6d73
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebolmcid6ooeftq4ha4b22xlarqazkzjmfmo7vpyhttpk53mgc2ja

**Comment by kevzak** [comment]
checker:manualTrigger

**Comment by 1ane-1** [comment]
checker:manualTrigger

**Comment by 1ane-1** [comment]
CID Checker Report looks healthy. Support this round.

**Comment by 1ane-1** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceclndemccjxo5mrxqzhehijvtzyixaaucducrqf7g2kjuwoxp6m6u 
#### Address 
> f1622ljfj6wczt4ge2aerxtcwxo3o72ozbsjyimdq
#### Datacap Allocated
> 406.80TiB
#### Signer Address
> f1mdk7s2vntzm6hu35yuo6vjubtrpfnb2awhgvrri
#### Id
> afc0d872-7a27-4d7b-96ec-2b8ca8fcef89
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceclndemccjxo5mrxqzhehijvtzyixaaucducrqf7g2kjuwoxp6m6u

**Comment by nj-steve** [comment]
checker:manualTrigger

**Comment by nj-steve** [comment]
see this issue in community , the cid and retrieval reports look fine. 
execute a random retrieval. 
<img width="804" alt="image" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/15796059/1587e1b7-6df3-4a85-83dd-f83ecc02e28d">

**Comment by nj-steve** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedkuyy36mte3ttwanh7evnvhcvtikkz6vfa3xekgt5g5lg4mm5ub4 
#### Address 
> f1622ljfj6wczt4ge2aerxtcwxo3o72ozbsjyimdq
#### Datacap Allocated
> 406.80TiB
#### Signer Address
> f1xx6555qijma7igpnjspyvdunc4vfxkawnpqy5ii
#### Id
> afc0d872-7a27-4d7b-96ec-2b8ca8fcef89
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedkuyy36mte3ttwanh7evnvhcvtikkz6vfa3xekgt5g5lg4mm5ub4
