### ISSUE TITLE
[DataCap Application] Amazonia EO satellite

### ISSUE THREAD

**Issue by RamonPedroo** [filecoin-project/filecoin-plus-large-datasets#1599]
### Data Owner Name

AMS Kepler

### Data Owner Country/Region

Brazil

### Data Owner Industry

Information, Media & Telecommunications

### Website

https://www.amskepler.com/

### Social Media

```text
https://twitter.com/amskepler
https://www.youtube.com/amskepler
https://www.pinterest.jp/amskepler/
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

500TiB

### On-chain address for first allocation

f1m6trho4k23hkaizdwthyy2rsvkbtwxemas7i6na

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
AMS Kepler is a Brazilian company with deep knowledge in the  development of software for Remote Sensing earth stations with a strong presence in the areas of Digital Cartography, Space Engineering, Geoprocessing, Digital Image Processing, Remote Sensing and Information Technology.
The company operates as a service provider, integrating imaging technologies and Geographic Information Systems with the best Software Engineering practices, using its high technical and operational standards.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
Imagery acquired by Amazonia-1 satellite. The image files are recorded and processed by Instituto Nacional de Pesquisas Espaciais (INPE) and are converted to Cloud Optimized Geotiff format in order to optimize its use for cloud based applications.
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### How do you plan to prepare the dataset

lotus

### Please share a sample of the data

```text
https://registry.opendata.aws/amazonia/
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Sporadic

### For how long do you plan to keep this dataset stored on Filecoin

1 to 1.5 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, South America

### How will you be distributing your data to storage providers

HTTP or FTP server, IPFS, Shipping hard drives

### How do you plan to choose storage providers

Slack, I don't know yet

### How do you plan to make deals to your storage providers

Lotus client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by herrehesse** [comment]
@RamonPedroo Thank you for applying for a datacap for storing scientific data, really great to see.
Can you provide me with a SP list and company names/region on which you want to store the data? Also, why are you not storing in EU?

Thanks for your assistance.

**Comment by lvschouwen** [comment]
@RamonPedroo 
Why do you request a 5 PiB allocation for a set that is only 4 TiB big?

`
lucas@toolbox:~$ aws s3 ls --no-sign-request s3://amazonia-pds/ --recursive --human-readable --summarize
Total Objects: 33292
   Total Size: 4.0 TiB

lucas@toolbox:~$ aws s3 ls --no-sign-request s3://amazonia-meta-pds/ --recursive --human-readable --summarize
Total Objects: 5548
   Total Size: 10.8 GiB
`

![image](https://user-images.githubusercontent.com/6965171/218080511-bcf4d8c5-775f-4179-ac83-e5578239c086.png)

**Comment by RamonPedroo** [comment]
@lvschouwen Ohhhh that's a mistake. I'll check it again. Graças
