### ISSUE TITLE
[DataCap Application] UJOONET, Inc.

### ISSUE THREAD

**Issue by jhkim1412** [filecoin-project/filecoin-plus-large-datasets#16]
# Large Dataset Client Application

To apply for a DataCap allocation for your dataset, please fill out the following information.

## Core Information
- Organization Name: UJOONET, Inc
- Website / Social Media: http://mylinkplus.io
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 1 PiB
- On-chain address for first allocation: f3rpablljxoko6djyzbkmtqukfa6dnrzjuzflokeuou4x42nyrfa64e5f4isjm4yfv4mb5v6jtfqgx7hchkh4a

_Please respond to the questions below in pargraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

## Project details

Share a brief history of your project and organization.
```
UJOONET was created to advance the IPFS and Filecoin ecosystem. We have been trying to create an easy and fast way for our existing customers to store their data in FILECOIN Miner.

UJOONET has created a way to automatically save data with FILECOIN miners on behalf of clients, and that is mylinkplus. Clients can also search by clicking the button on the website.

In addition, stored data can be shared with other devices or people using links created by mylinkplus. While the data is stored on the filecoin network, a separate link is created to eliminate any delays in the use of the customer, so that the customer does not feel any delay during the transaction.
(Alternatively, a faster retrieval method may allow for faster retrieval.)

UJOONET applies for DATACAP to store data of various customers.
Clients can be divided into personal (no ID or password required) and corporate customers, and corporate customers may require a login process to manage separate folders.
```

What is the primary source of funding for this project?
```
There are mainly equity, bonds, credit, bank loans, etc
```

What other projects/ecosystem stakeholders is this project associated with?
```
Institutional investors, private investors and entertainment companies as well as the Filecoin network.
```

## Use-case details

Describe the data being stored onto Filecoin
```
Access mylinkplus.io from the Chrome browser on your computer or smartphone to upload files and perform "CID 파일코인 저장(Save CID File Coin)".
```

Where was the data in this dataset sourced from?
```
Mainly by user’s data (individual image, video and files and entertainment contents data, business data)
```

Can you share a sample of what is in the dataset? A link to a file, an image, a table, etc., are good examples of this. 
```
Video of a family performance on a smartphone. Below is url generated by mylinkplus.
https://www.mylinkplus.io/dn/GpVhnpcsn
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes, (But For corporate data, only certain authorized people can access it.)
```

What is the expected retrieval frequency for this data?
```
It depends on the customer's situation. Some individual customers may want to share directly to a variety of devices as soon as they store it in Filecoin network, and some enterprise customers may simply want to keep it for a long time. We are implementing functions that enable both.
```

For how long do you plan to keep this dataset stored on Filecoin? Will this be a permanent archival or a one-time storage deal?
```
We believe that for individuals, this document will be a permanent archive (but may be equal to or extended sector life at the request of the customer).
```

## DataCap allocation plan

In which geographies do you plan on making storage deals?
```
Initially, it wants to be stored in Korea, but ultimately all over the world.
```

What is your expected data onboarding rate? How many deals can you make in a day, in a week? How much DataCap do you plan on using per day, per week?
```
It may depend on how quickly the service spreads, but initially we expect 10 TiB per week.
```

How will you be distributing your data to miners? Is there an offline data transfer process?
```
We are based on an online deal. As confirmed, 30GB files can be saved if there is no network problem.
```

How do you plan on choosing the miners with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We are testing storage deals to various miners.
```

How will you be distributing data and DataCap across miners storing data?
```
We are testing with miners who will be aggressive with various clients and looking for more miners.
```

**Comment by dannyob** [comment]
Assuming our Chinese notaries verify and approve this, Filecoin Foundation will also approve.

**Comment by dkkapur** [comment]
@jhkim1412 - thanks for submitting your application for a large DataCap allocation to the Fil+ Notaries! As the Notaries and the Fil+ community carries out the due diligence process on your application - we'd love to invite you to participate in the Fil+ Community Governance Call. We're inviting clients applying for large amounts of DataCap to come present and field questions during the second half of each community call to help enable the process. The next set of calls are actually today - Tues Aug 31 at 3pm and 11pm UTC, information to participate can be found here: https://github.com/filecoin-project/notary-governance/issues/221. Looking forward to seeing you there or perhaps at the next one on Sept 14!

**Comment by jhkim1412** [comment]
Sorry, I have an important appointment today, so I will attend the next event, September 14th.

**Comment by jhkim1412** [comment]
Our system is not ready yet, so I will apply again after the next upgrade is complete. Let's close this issue.

**Comment by ozzi0221** [comment]
About The APP is not related with our project at all.
