### ISSUE TITLE
[DataCap Application] Outercore - Delta Instance One

### ISSUE THREAD

**Issue by jimmylee** [filecoin-project/filecoin-plus-large-datasets#1601]
### Data Owner Name

Outercore - Network Growth - Engineering

### Data Owner Country/Region

United States

### Data Owner Industry

Other

### Website

https://fw.services

### Social Media

```text
https://twitter.com/OutercoreEng
https://twitter.com/Estuary_Tech
```

### Total amount of DataCap being requested

2PiB

### Weekly allocation of DataCap requested

500TiB

### On-chain address for first allocation

f14wtf7z3k3rx4wtb5s24lwafxkfyuyeewyybz7vi

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Root website: https://fw.services
Project website: https://delta.store

We are the Engineering team at Protocol Labs ➝ Outercore ➝ Engineering/Network Growth. Our goal is develop tooling for entire Filecoin Ecosystem to use to onboard data to the Filecoin Network.

Our mission


We want an internet where resources are owned & shared by everyone. Everyone shares consensus over a distributed ledger. Data storage is verifiably stored for the end-user, and more fault tolerant. There is no central authority of control and no single point of failure. And the security promise only improves as the network continues to grow. Just imagine all of the certifications that can be automatically generated for end users by a new network like this. This is how you achieve storage as a human right for anyone in the world.

We're going to prove that we can get here by building the tools that can support onboarding 10 PiBs a day of data to the Filecoin Network. But we're also not going to forget about retrievability and helping the Filecoin Network actually become usable.
```

Delta

```
Our solution to archival and cold storage use cases.

Use ∆ Delta to upload all of your useful public data to Filecoin storage providers. Delta is a straight-forward Filecoin storage deal making tool that manages deals, and does not do anything else. It is purely for the function of helping Storage Providers fill capacity either through online or offline methods. It is written in Go and designed to be paired well with bare-metal infrastructure.
```

On March 27th, 2023 we'll open source the tool for everyone.
```


### Is this project associated with other projects/ecosystem stakeholders?

Yes

### If answered yes, what are the other projects/ecosystem stakeholders

```text
Protocol Labs -> Outercore -> Network Growth
```

### Describe the data being stored onto Filecoin

```text
A useful datasets that have been listed by the Network Growth team has tracked in their client tracker.

We also have our own PM going after clients such as the Cancer Imaging Archive, University Data, Climate Data, AI Data, Healthcare data, and so much more.
```

### Where was the data currently stored in this dataset sourced from

Other

### If you answered "Other" in the previous question, enter the details here

```text
Differs from client to client

* University hard drives
* Backup services
* Cloud
```

### How do you plan to prepare the dataset

others/custom tool

### If you answered "other/custom tool" in the previous question, enter the details here

```text
Our new tool Delta, which we plan to release to the whole ecosystem.

Learn more at https://delta.store
```

### Please share a sample of the data

```text
I have no examples, we'll be working through Network Growth's client list of Petabyte scale users.
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [ ] I confirm

### If you chose not to confirm, what was the reason

```text
Delta is not focused on retrieval, its focused on storage onboarding. We are going to help all SPs onboard all of their data.
```

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

More than 3 years

### In which geographies do you plan on making storage deals

North America

### How will you be distributing your data to storage providers

Others

### How do you plan to choose storage providers

Others

### If you answered "Others" in the previous question, what is the tool or platform you plan to use

```text
We will be developing our tool Delta

Learn more at https://delta.store
```

### If you already have a list of storage providers to work with, fill out their names and provider IDs below

```text
We have developed our own list at https://data.storage.market but we will work with everyone/anyone. We actively work with storage providers and we have a storage provider on our team.

93 of them that we plan to start with, obviously we'll work with more.

➝ https://data.storage.market/api/providers/f0840770
➝ https://data.storage.market/api/providers/f01624021
➝ https://data.storage.market/api/providers/f01806491
➝ https://data.storage.market/api/providers/f08399
➝ https://data.storage.market/api/providers/f01790264
➝ https://data.storage.market/api/providers/f0875769
➝ https://data.storage.market/api/providers/f01035680
➝ https://data.storage.market/api/providers/f033356
➝ https://data.storage.market/api/providers/f01683871
➝ https://data.storage.market/api/providers/f03488
➝ https://data.storage.market/api/providers/f030379
➝ https://data.storage.market/api/providers/f01466075
➝ https://data.storage.market/api/providers/f02301
➝ https://data.storage.market/api/providers/f010479
➝ https://data.storage.market/api/providers/f010088
➝ https://data.storage.market/api/providers/f0773157
➝ https://data.storage.market/api/providers/f0717969
➝ https://data.storage.market/api/providers/f0461791
➝ https://data.storage.market/api/providers/f01746964
➝ https://data.storage.market/api/providers/f01059489
➝ https://data.storage.market/api/providers/f023467
➝ https://data.storage.market/api/providers/f01392893
➝ https://data.storage.market/api/providers/f01736668
➝ https://data.storage.market/api/providers/f022352
➝ https://data.storage.market/api/providers/f01199430
➝ https://data.storage.market/api/providers/f09848
➝ https://data.storage.market/api/providers/f01222595
➝ https://data.storage.market/api/providers/f01794610
➝ https://data.storage.market/api/providers/f01443744
➝ https://data.storage.market/api/providers/f01199442
➝ https://data.storage.market/api/providers/f02401
➝ https://data.storage.market/api/providers/f01402814
➝ https://data.storage.market/api/providers/f0104671
➝ https://data.storage.market/api/providers/f01207045
➝ https://data.storage.market/api/providers/f0406703
➝ https://data.storage.market/api/providers/f01175097
➝ https://data.storage.market/api/providers/f010446
➝ https://data.storage.market/api/providers/f0724219
➝ https://data.storage.market/api/providers/f022142
➝ https://data.storage.market/api/providers/f058369
➝ https://data.storage.market/api/providers/f01201327
➝ https://data.storage.market/api/providers/f0406322
➝ https://data.storage.market/api/providers/f01278
➝ https://data.storage.market/api/providers/f0187709
➝ https://data.storage.market/api/providers/f01045784
➝ https://data.storage.market/api/providers/f0706693
➝ https://data.storage.market/api/providers/f024184
➝ https://data.storage.market/api/providers/f01385207
➝ https://data.storage.market/api/providers/f01652333
➝ https://data.storage.market/api/providers/f01319368
➝ https://data.storage.market/api/providers/f0214334
➝ https://data.storage.market/api/providers/f082635
➝ https://data.storage.market/api/providers/f0836160
➝ https://data.storage.market/api/providers/f0135078
➝ https://data.storage.market/api/providers/f039940
➝ https://data.storage.market/api/providers/f0408717
➝ https://data.storage.market/api/providers/f01345523
➝ https://data.storage.market/api/providers/f01108096
➝ https://data.storage.market/api/providers/f01611097
➝ https://data.storage.market/api/providers/f01208862
➝ https://data.storage.market/api/providers/f01662356
➝ https://data.storage.market/api/providers/f01423116
➝ https://data.storage.market/api/providers/f017665
➝ https://data.storage.market/api/providers/f01666984
➝ https://data.storage.market/api/providers/f0440429
➝ https://data.storage.market/api/providers/f01028552
➝ https://data.storage.market/api/providers/f0707721
➝ https://data.storage.market/api/providers/f099608
➝ https://data.storage.market/api/providers/f0142637
➝ https://data.storage.market/api/providers/f01127678
➝ https://data.storage.market/api/providers/f0501283
➝ https://data.storage.market/api/providers/f01133080
➝ https://data.storage.market/api/providers/f0127896
➝ https://data.storage.market/api/providers/f010617
➝ https://data.storage.market/api/providers/f097777
➝ https://data.storage.market/api/providers/f01367109
➝ https://data.storage.market/api/providers/f01225882
➝ https://data.storage.market/api/providers/f023971
➝ https://data.storage.market/api/providers/f0466405
➝ https://data.storage.market/api/providers/f01310564
➝ https://data.storage.market/api/providers/f02620
➝ https://data.storage.market/api/providers/f02576
➝ https://data.storage.market/api/providers/f01764587
➝ https://data.storage.market/api/providers/f019551
➝ https://data.storage.market/api/providers/f034258
➝ https://data.storage.market/api/providers/f0240185
➝ https://data.storage.market/api/providers/f01619524
➝ https://data.storage.market/api/providers/f01096124
➝ https://data.storage.market/api/providers/f01163272
➝ https://data.storage.market/api/providers/f01337533
➝ https://data.storage.market/api/providers/f01091851
➝ https://data.storage.market/api/providers/f01784458
➝ https://data.storage.market/api/providers/f08403
```

### How do you plan to make deals to your storage providers

Others/custom tool

### If you answered "Others/custom tool" in the previous question, enter the details here

```text
Our new tool Delta, which we plan to release to the whole ecosystem.

Learn more at https://delta.store
```

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 2PiB

**Expected weekly DataCap usage rate**
> 500TiB

**Client address**
>f14wtf7z3k3rx4wtb5s24lwafxkfyuyeewyybz7vi

**Comment by simonkim0515** [comment]
## Datacap Request Trigger

#### Total DataCap requested 
> 2PiB

#### Expected weekly DataCap usage rate 
> 500TiB 

#### Client address
> f14wtf7z3k3rx4wtb5s24lwafxkfyuyeewyybz7vi

**Comment by liyunzhi-666** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecp7qwyc3l4iyjyc33qgbjjtixtmvr6o7q533qw3xnvc4tcsbpuko 
#### Address 
> f14wtf7z3k3rx4wtb5s24lwafxkfyuyeewyybz7vi
#### Datacap Allocated
> 102.39TiB
#### Signer Address
> f1pszcrsciyixyuxxukkvtazcokexbn54amf7gvoq
#### Id
> b2d533df-0cc6-4ec8-8293-546ca8dc4ffe
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecp7qwyc3l4iyjyc33qgbjjtixtmvr6o7q533qw3xnvc4tcsbpuko

**Comment by liyunzhi-666** [comment]
[Same reason](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1602#issuecomment-1428951352). I am willing to support.

**Comment by kernelogic** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebxuvt2kf54r7lwpc46ujjthzhiobvvmeostetplkzmqwlj76twou 
#### Address 
> f14wtf7z3k3rx4wtb5s24lwafxkfyuyeewyybz7vi
#### Datacap Allocated
> 102.39TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### Id
> b2d533df-0cc6-4ec8-8293-546ca8dc4ffe
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebxuvt2kf54r7lwpc46ujjthzhiobvvmeostetplkzmqwlj76twou

**Comment by dannyob** [comment]
Hey @jimmylee one observation from previous experience -- if fw.services is expecting to onload data rapidly, you may want to pre-arrange with a group of four notaries per application, so you have folks on hand if you need to keep the rhythm of renewals. I'm happy to be one of the notaries for one or two of the instances.

**Comment by jimmylee** [comment]
Thank you for the advice! I think thats a smart move even if we expect other people to run our tooling. Really appreciate you @dannyob

**Comment by spaceT9** [comment]
checker:manualTrigger

**Comment by Joss-Hua** [comment]
checker:manualTrigger

**Comment by psh0691** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceasoj7qtp3q6v3t4awjv4iljm5v5qa4iurr5tq7zq7okeg4i4hxzc 
#### Address 
> f14wtf7z3k3rx4wtb5s24lwafxkfyuyeewyybz7vi
#### Datacap Allocated
> 204.79TiB
#### Signer Address
> f1qdko4jg25vo35qmyvcrw4ak4fmuu3f5rif2kc7i
#### Id
> c4645ca0-b2dd-40ab-8ff6-f2de28445b36
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceasoj7qtp3q6v3t4awjv4iljm5v5qa4iurr5tq7zq7okeg4i4hxzc

**Comment by psh0691** [comment]
We look forward to the changed search status, distribution, duplicate status, and CID sharing status in the next round.

**Comment by nj-steve** [comment]
@jimmylee You should send  deals to more SPs, you can contact other SPs on slack.

**Comment by schreck23** [comment]
@dannyob anyway you could bless this for us?

**Comment by kernelogic** [comment]
Got the clarification from RG existing merged dataset can continue to perform. However, anyone from Delta team can explain to me what are these duplicate data?

⚠️ 3 storage providers sealed too much duplicate data - [f0104671](https://filfox.info/en/address/f0104671): 49.95%, [f033356](https://filfox.info/en/address/f033356): 21.43%, [f03488](https://filfox.info/en/address/f03488): 33.33%

**Comment by kernelogic** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced4wmv6fyf4hamg3bzhljm2hwibge5hjlwqt5ymdxnjfyckfg4bdy 
#### Address 
> f14wtf7z3k3rx4wtb5s24lwafxkfyuyeewyybz7vi
#### Datacap Allocated
> 204.79TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### Id
> c4645ca0-b2dd-40ab-8ff6-f2de28445b36
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced4wmv6fyf4hamg3bzhljm2hwibge5hjlwqt5ymdxnjfyckfg4bdy

**Comment by kernelogic** [comment]
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1854#issuecomment-1612381964
