### ISSUE TITLE
[DataCap Application] Nebula Block - Cell Painting Gallery[1/2]

### ISSUE THREAD

**Issue by bq1024** [filecoin-project/filecoin-plus-large-datasets#1604]
### Data Owner Name
Nebula Block

### Data Owner Country/Region
Canada

### Data Owner Industry
Web3 / Crypto

### Website
[https://www.nebulablock.com/](https://www.nebulablock.com/)

### Social Media
https://twitter.com/nbfsdata  (Twitter)

### Total amount of DataCap being requested
5 PiB

### Weekly allocation of DataCap requested
500 TiB

### On-chain address for first allocation
f1albgsgb7uy3mrnq3hz7ehkwoxzxcryl7hqjok4y

### Custom multisig
No

### Share a brief history of your project and organization
As a data center services provider and blockchain practitioner, Nebula Block is one of the earliest participants in the Filecoin ecosystem in North America and has been contributing to the Filecoin network and ecosystem since 2020. We were selected as minerX fellow, participated in early-stage testing, participated in slingshot v2 and v3, helped improve louts, and support ecosystem projects like Filmine, Estuary, and FilSwan. Nebula Block is also in charge of this dataset storage and deal preparation in slingshot v3.

Currently, Nebula block is one of the biggest web3 hosting providers in North America, which works with 4 data centers across the world, and hosts more than 3000 servers with 700 PiB storage.

Nebula Block is seeking to onboard data to meet the high demand of FIL+ for itself and its partners.

### Is this project associated with other projects/ecosystem stakeholders?
No

### Describe the data being stored onto Filecoin
The Cell Painting Gallery is a collection of image datasets created using the Cell Painting assay. The images of cells are captured by microscopy imaging, and reveal the response of various labeled cell components to whatever treatments are tested, which can include genetic perturbations, chemicals or drugs, or different cell types.

### Where was the data currently stored in this dataset sourced from
AWS Cloud

### How do you plan to prepare the dataset
others/custom tool

### If you answered "other/custom tool" in the previous question, enter the details here
We will use multiple tools to prepare the dataset, such as singularity and go-swan-client. https://github.com/filswan/go-swan-client

### Please share a sample of the data
https://cellpainting-gallery.s3.amazonaws.com/index.html

### Confirm that this is a public dataset that can be retrieved by anyone on the Network
Yes

### What is the expected retrieval frequency for this data
Monthly

### For how long do you plan to keep this dataset stored on Filecoin
2 to 3 years

### In which geographies do you plan on making storage deals
Greater China, Asia other than Greater China, Africa, North America, South America, Europe, Australia (continent), Antarctica

### How will you be distributing your data to storage providers
HTTP or FTP server, IPFS

### How do you plan to choose SP
Other

### If you answered "Others" in the previous question, what is the tool or platform you plan to use
We will create auto-bid tasks on the FilSwan platform, and the platform will help up find suitable storage providers based on its reputation system (https://docs.filswan.com/filswan-platform/overview/reputation-system)

### If you already have a list of storage providers to work with, fill out their names and provider IDs below
Some storage providers registered on the FilSwan platform and accepting auto-bid deals are as follows:
f03624
f010088
f02301
f08399
f0187709
f01163272
f01402814
f0240185
f0143858
f01390330
f01225882
f0717969
f03223
f01862564
f01946551
f01877184
f02012951

### How do you plan to make deals to your storage providers
Others/custom tool

### If you answered "Others/custom tool" in the previous question, enter the details here
We will use go-swan-client to make deals. https://github.com/filswan/go-swan-client

### Can you confirm that you will follow the Fil+ guideline
Yes

**Comment by herrehesse** [comment]
@bq1024 How large is the amazon bucket?

**Comment by simonkim0515** [comment]
## Datacap Request Trigger

#### Total DataCap requested 
> 5PiB

#### Expected weekly DataCap usage rate 
> 500TiB 

#### Client address
> f1albgsgb7uy3mrnq3hz7ehkwoxzxcryl7hqjok4y

**Comment by bq1024** [comment]
> @bq1024 How large is the amazon bucket?

@simonkim0515 We are recalculating the size of the bucket, will get back to you once done. Thanks!

**Comment by caoyoungyoung** [comment]
checker:manualTrigger

**Comment by bq1024** [comment]
> @bq1024 How large is the amazon bucket?

Total Objects: 251439753
   Total Size: 575.2 TiB
We plan to distribute 10 copies to SPs.

**Comment by flyworker** [comment]
> 

@bq1024  just for your information, from recently community's querying if you send through swan engine, I suggest you send more than 10 copies to ensure you have enough redundant.

**Comment by bq1024** [comment]
> > 
> 
> @bq1024 just for your information, from recently community's querying if you send through swan engine, I suggest you send more than 10 copies to ensure you have enough redundant for retrieval.

Got it, thank you @flyworker

**Comment by kernelogic** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceamluttucd2o5soxfrv226npot5jmdup4ttlbfoqki666i4y5hnpi 
#### Address 
> f1albgsgb7uy3mrnq3hz7ehkwoxzxcryl7hqjok4y
#### Datacap Allocated
> 250.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### Id
> 6868eaef-4245-46a7-81be-cc8e981216b1
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceamluttucd2o5soxfrv226npot5jmdup4ttlbfoqki666i4y5hnpi

**Comment by kernelogic** [comment]
At today's governance meeting Charles has clarified the relationships among filswan, nebula etc. willing to support.

**Comment by cryptowhizzard** [comment]
> At today's governance meeting Charles has clarified the relationships among filswan, nebula etc. willing to support.

Likewise.

**Comment by cryptowhizzard** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacealx6eaallfbddhz7zli2hl7e3twhzuv2qkxm6nk7sj4yvp5on5bc 
#### Address 
> f1albgsgb7uy3mrnq3hz7ehkwoxzxcryl7hqjok4y
#### Datacap Allocated
> 250.00TiB
#### Signer Address
> f1krmypm4uoxxf3g7okrwtrahlmpcph3y7rbqqgfa
#### Id
> 6868eaef-4245-46a7-81be-cc8e981216b1
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacealx6eaallfbddhz7zli2hl7e3twhzuv2qkxm6nk7sj4yvp5on5bc

**Comment by Sunnyiscoming** [comment]
checker:manualTrigger

**Comment by Normalnoise** [comment]
checker:manualTrigger

**Comment by liyunzhi-666** [comment]
checker:manualTrigger

**Comment by liyunzhi-666** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceafmvtf4tpwykvkyhnhfksmedu536cxdwsckmkmqhs6b4ssagpg5y 
#### Address 
> f1albgsgb7uy3mrnq3hz7ehkwoxzxcryl7hqjok4y
#### Datacap Allocated
> 500.00TiB
#### Signer Address
> f1pszcrsciyixyuxxukkvtazcokexbn54amf7gvoq
#### Id
> 95c51f29-d95a-43cc-99dc-923ba353cadc
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceafmvtf4tpwykvkyhnhfksmedu536cxdwsckmkmqhs6b4ssagpg5y

**Comment by igoovo** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceblg7klhba2ftqa5jssfretofcb6ky45ifjfgfyszjzmfijm7j67i 
#### Address 
> f1albgsgb7uy3mrnq3hz7ehkwoxzxcryl7hqjok4y
#### Datacap Allocated
> 500.00TiB
#### Signer Address
> f1shnsfayxqll77svffaxnjenms7bbbysbqcatrpy
#### Id
> 6c1bfda2-141d-407d-9ecf-f6e9d3ea066e
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceblg7klhba2ftqa5jssfretofcb6ky45ifjfgfyszjzmfijm7j67i

**Comment by igoovo** [comment]
<img width="1023" alt="截屏2023-04-08 00 05 59" src="https://user-images.githubusercontent.com/103082537/230642011-f80abda7-1343-464b-a99a-6deb09056d69.png">

<img width="1055" alt="截屏2023-04-08 00 10 54" src="https://user-images.githubusercontent.com/103082537/230642024-3f5129dc-a3f3-4cca-be64-f1744c9742f2.png">

**Comment by bq1024** [comment]
We'd like to keep this application open as we are currently working on onboarding more SPs to the project

**Comment by claydrone** [comment]
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1604

**Comment by clriesco** [comment]
Removed stale label and reopened issue :)

**Comment by bq1024** [comment]
checker:manualTrigger

**Comment by bq1024** [comment]
Onboarding more SPs to the project.

**Comment by flyworker** [comment]
checker:manualTrigger

**Comment by flyworker** [comment]
checker:manualTrigger

**Comment by flyworker** [comment]
checker:manualTrigger

**Comment by bq1024** [comment]
checker:manualTrigger

**Comment by bq1024** [comment]
checker:manualTrigger

**Comment by Sunnyiscoming** [comment]
Hello, @bq1024 per the https://github.com/filecoin-project/notary-governance/issues/922 for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

This information will be reviewed by Fil+ Governance team to confirm validity and then the application will be allowed to move forward for additional notary review.

**Comment by herrehesse** [comment]
checker:manualTrigger

**Comment by herrehesse** [comment]
![Screenshot 2023-11-14 at 09 34 15](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/70132857/98048aa0-1258-4600-8a2d-dbd1dfaf81c2)

Happy to see 1/100 applications that are following the rules. Thank you.

**Comment by bq1024** [comment]
checker:manualTrigger

**Comment by herrehesse** [comment]
checker:manualTrigger

**Comment by Sunnyiscoming** [comment]
Please provide ID, City, Country, Organization of each SP here.

**Comment by Normalnoise** [comment]
> Please provide ID, City, Country, Organization of each SP here.

Hi @Sunnyiscoming, please refer to https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1529#issuecomment-1824761572

**Comment by bq1024** [comment]
> Please provide ID, City, Country, Organization of each SP here.

Hi @Sunnyiscoming please refer to https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1529#issuecomment-1824761572
