### ISSUE TITLE
[DataCap Application] Nebula Block - Cell Painting Gallery[2/2]

### ISSUE THREAD

**Issue by bq1024** [filecoin-project/filecoin-plus-large-datasets#1605]
### Data Owner Name
Nebula Block - Cell Painting Gallery[2/2]

### Data Owner Country/Region
Canada

### Data Owner Industry
Web3 / Crypto

### Website
[https://www.nebulablock.com/](https://www.nebulablock.com/)

### Social Media
https://twitter.com/nbfsdata  (Twitter)

### Total amount of DataCap being requested
5 PiB

### Weekly allocation of DataCap requested
500 TiB

### On-chain address for first allocation
f1nuohujbh4radxhpo53qk3izzsqfusyn6j2mardq

### Custom multisig
No

### Share a brief history of your project and organization
As a data center services provider and blockchain practitioner, Nebula Block is one of the earliest participants in the Filecoin ecosystem in North America and has been contributing to the Filecoin network and ecosystem since 2020. We were selected as minerX fellow, participated in early-stage testing, participated in slingshot v2 and v3, helped improve louts, and support ecosystem projects like Filmine, Estuary, and FilSwan. Nebula Block is also in charge of this dataset storage and deal preparation in slingshot v3.

Currently, Nebula block is one of the biggest web3 hosting providers in North America, which works with 4 data centers across the world, and hosts more than 3000 servers with 700 PiB storage.

Nebula Block is seeking to onboard data to meet the high demand of FIL+ for itself and its partners.

### Is this project associated with other projects/ecosystem stakeholders?
No

### Describe the data being stored onto Filecoin
The Cell Painting Gallery is a collection of image datasets created using the Cell Painting assay. The images of cells are captured by microscopy imaging, and reveal the response of various labeled cell components to whatever treatments are tested, which can include genetic perturbations, chemicals or drugs, or different cell types.

### Where was the data currently stored in this dataset sourced from
AWS Cloud

### How do you plan to prepare the dataset
others/custom tool

### If you answered "other/custom tool" in the previous question, enter the details here
We will use multiple tools to prepare the dataset, such as singularity and go-swan-client. https://github.com/filswan/go-swan-client

### Please share a sample of the data
https://cellpainting-gallery.s3.amazonaws.com/index.html

### Confirm that this is a public dataset that can be retrieved by anyone on the Network
Yes

### What is the expected retrieval frequency for this data
Monthly

### For how long do you plan to keep this dataset stored on Filecoin
2 to 3 years

### In which geographies do you plan on making storage deals
Greater China, Asia other than Greater China, Africa, North America, South America, Europe, Australia (continent), Antarctica

### How will you be distributing your data to storage providers
HTTP or FTP server, IPFS

### How do you plan to choose SP
Other

### If you answered "Others" in the previous question, what is the tool or platform you plan to use
We will create auto-bid tasks on the FilSwan platform, and the platform will help up find suitable storage providers based on its reputation system (https://docs.filswan.com/filswan-platform/overview/reputation-system)

### If you already have a list of storage providers to work with, fill out their names and provider IDs below
Some storage providers registered on the FilSwan platform and accepting auto-bid deals are as follows:
f03624
f010088
f02301
f08399
f0187709
f01163272
f01402814
f0240185
f0143858
f01390330
f01225882
f0717969
f03223
f01862564
f01946551
f01877184
f02012951

### How do you plan to make deals to your storage providers
Others/custom tool

### If you answered "Others/custom tool" in the previous question, enter the details here
We will use go-swan-client to make deals. https://github.com/filswan/go-swan-client

### Can you confirm that you will follow the Fil+ guideline
Yes

**Comment by simonkim0515** [comment]
## Datacap Request Trigger

#### Total DataCap requested 
> 5PiB

#### Expected weekly DataCap usage rate 
> 500TiB 

#### Client address
> f1nuohujbh4radxhpo53qk3izzsqfusyn6j2mardq

**Comment by cryptowhizzard** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedhr2hpmcw3immwxtid73kgjlotjg522zsfzuduhbyr72xbu4kejw 
#### Address 
> f1nuohujbh4radxhpo53qk3izzsqfusyn6j2mardq
#### Datacap Allocated
> 250.00TiB
#### Signer Address
> f1krmypm4uoxxf3g7okrwtrahlmpcph3y7rbqqgfa
#### Id
> a5a74d3a-07cf-44a1-8744-6ed7a40021c8
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedhr2hpmcw3immwxtid73kgjlotjg522zsfzuduhbyr72xbu4kejw

**Comment by NDLABS-OFFICE** [comment]
The check bot audit was carried out in 1604, the nodes are abundant and geographically dispersed, and fully comply with the ND signature standard. In addition, the retrieval test of the node was carried out, and the random inspection was normal.

**Comment by NDLABS-OFFICE** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec5vfbnsoal572knevmdvkisolpkgyvyvluqwafo4dokyqgi4s66e 
#### Address 
> f1nuohujbh4radxhpo53qk3izzsqfusyn6j2mardq
#### Datacap Allocated
> 250.00TiB
#### Signer Address
> f1yayfsv6whu3rheviucvventj3y6t542xfpb47ei
#### Id
> a5a74d3a-07cf-44a1-8744-6ed7a40021c8
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec5vfbnsoal572knevmdvkisolpkgyvyvluqwafo4dokyqgi4s66e

**Comment by zcfil** [comment]
checker:manualTrigger

**Comment by spaceT9** [comment]
Given the good performance of first round, CID history is very healthy, I will sign the second tranche. Keep the good work!

**Comment by Joss-Hua** [comment]
checker:manualTrigger

**Comment by ipollo00** [comment]
@bq1024 hey, are you still requiring datacap? 
seems some sps you work with are not as planned. Do you mind disclose here?

**Comment by bq1024** [comment]
> @bq1024 hey, are you still requiring datacap? seems some sps you work with are not as planned. Do you mind disclose here?

Yes, we still require datacap, all the deals were distributed via the Filswan platform, please see https://app.slack.com/huddle/TEHTVS1L6/C04LBAMBDPD
And we are actively working on onboarding more SPs to the Filswan platform

**Comment by ipollo00** [comment]
checker:manualTrigger

**Comment by ipollo00** [comment]
Gotcha. It's okay. No reason not to support it.

**Comment by ipollo00** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebjec4yualori3yidvmrffhl4pwzqubxywywhcbjiad3mdu5clde2 
#### Address 
> f1nuohujbh4radxhpo53qk3izzsqfusyn6j2mardq
#### Datacap Allocated
> 500.00TiB
#### Signer Address
> f1n5wlrrhoxpkgwij25xrtt7w7g2k3fhbthmdn6ri
#### Id
> bbb7274c-7c18-4cc9-93d4-4936fd0072d4
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebjec4yualori3yidvmrffhl4pwzqubxywywhcbjiad3mdu5clde2

**Comment by bq1024** [comment]
We'd like to keep this application open as we are currently working on onboarding more SPs to the project

**Comment by bq1024** [comment]
checker:manualTrigger

**Comment by clriesco** [comment]
Removed stale label and reopened issue :)

**Comment by bq1024** [comment]
checker:manualTrigger

**Comment by bq1024** [comment]
Onboarding more SPs to the project.

**Comment by Normalnoise** [comment]
checker:manualTrigger

**Comment by Sunnyiscoming** [comment]
Hello, per the https://github.com/filecoin-project/notary-governance/issues/922 for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

This information will be reviewed by Fil+ Governance team to confirm validity and then the application will be allowed to move forward for additional notary review.
