### ISSUE TITLE
[DataCap Application] <Dwart> - <Dewei Art Education>

### ISSUE THREAD

**Issue by james0012022** [filecoin-project/filecoin-plus-large-datasets#1606]
### Data Owner Name

Dewei Art

### Data Owner Country/Region

China

### Data Owner Industry

Education & Training

### Website

http://www.deweiart.com/

### Social Media

```text
https://space.bilibili.com/587927837/
https://www.xiaohongshu.com/user/profile/5ce00a6f0000000005020264?xhsshare=CopyLink&appuid=5db980920000000001009152&apptime=1676266482
douyin:dwart021
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

200TiB

### On-chain address for first allocation

f1eoynacq7iojj4tnhfcptfrvotn4oiyl24catdei

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Dewei Art is an art company focusing on art education and creation. The aim is to motivate art enthusiast to learn and enjoy art world through our artists' professional and flexible education and influence, and also connect with all the excellent artists to create more modern artistic works.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
art education lessons
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### How do you plan to prepare the dataset

IPFS, lotus

### Please share a sample of the data

```text
https://www.xiaohongshu.com/user/profile/5ce00a6f0000000005020264?xhsshare=CopyLink&appuid=5db980920000000001009152&apptime=1676266482
https://space.bilibili.com/587927837/
Douyin:dwart021
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [ ] I confirm

### What is the expected retrieval frequency for this data

Daily

### For how long do you plan to keep this dataset stored on Filecoin

Permanently

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, Europe

### How will you be distributing your data to storage providers

HTTP or FTP server, IPFS, Shipping hard drives, Lotus built-in data transfer

### How do you plan to choose storage providers

Slack, Partners, I don't know yet

### How do you plan to make deals to your storage providers

Boost client, Lotus client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Looking at your application i have some questions:
As you are brand new on Github and have no history of past applications it seems to me that applying for 5PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?

Can you show us visible proof of the size of your data and the storage systems you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230337462961356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!

**Comment by james0012022** [comment]
@cryptowhizzard 

Hello There
Thanks for your due diligence.

To answer your questions as below:
Yes, I am new here. Is it not allowed for a new customer??
And I think the application form is very detailed and I have answered it, could you kindly tell me what else I need to speicially know? 

Currently we have more than 500GB dataset, and I can show you one of them which is part of 2022.
![Dwart](https://user-images.githubusercontent.com/105343308/218485343-c91de049-673f-40cf-bcc1-1a92bbc99f9a.png)

On the platforms I listed in the application, it is just part of our videos for this project, but you can refer to the latest update and information.

at last, I tried to fill the form above, but some information stopped me and made me think what is it for?
Does this form just for notaries' educated decision making not official KYC/KYB? 
![image](https://user-images.githubusercontent.com/105343308/218488117-94fe84a5-4320-475c-ab98-e803dbc747ed.png)

Sorry still looking for some nice SPs and struggling for the final decision.
But even if I have chosen the partners, I think it is optional, right?
I read some rules in the community and try to figure out what is good for me and this project.

Hope above information can help you better understand my project and position.
And welcome for more questions.

**Comment by cryptowhizzard** [comment]
Hi @james0012022 

Thanks for your response.

Applicant asks me to sign off on an application where we enter an agreement where I put my signature on.
Part of that agreement is that one understands the rules of FIL+ and that the storage is going according to the rules and guidelines.

Thanks for your understanding.

**Comment by simonkim0515** [comment]
## Datacap Request Trigger

#### Total DataCap requested 
> 5PiB

#### Expected weekly DataCap usage rate 
> 200TiB 

#### Client address
> f1eoynacq7iojj4tnhfcptfrvotn4oiyl24catdei

**Comment by Sunnyiscoming** [comment]
Could you send an email to [filplus-app-review@fil.org](mailto:filplus-app-review@fil.org) with your official domain in order to confirm your identity? Email name should includes the issue id https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1606.

**Comment by james0012022** [comment]
@Sunnyiscoming  hi, Sunny pls. check the mail box and you can also refer to below screenshot.
![kyc email](https://user-images.githubusercontent.com/105343308/218757441-186e85ff-eb93-4e9d-9d98-1344582e3fb9.jpg)

**Comment by james0012022** [comment]
@cryptowhizzard 

Hi thanks for your support.
I have done the kyc process per official request.

In terms of your suggestion, I might talk about it with my team. If we need your support, we will abide by your rules.

Anyway appreciate your quick reply on my application.

**Comment by james0012022** [comment]
@Sunnyiscoming 

Hi Sunny 
Are there any other issues I need to clarify for further step?

Thanks

**Comment by Sunnyiscoming** [comment]
Not yet.
But this trigger do not make bot(Large datacap requests) create DataCap Allocation requested directly. @simonkim0515

**Comment by Sunnyiscoming** [comment]
Not yet.

**Comment by herrehesse** [comment]
@james0012022 once you have found your SP's please post their information. Looking forward to it!

**Comment by simonkim0515** [comment]
## Datacap Request Trigger

#### Total DataCap requested 
> 5PiB

#### Expected weekly DataCap usage rate 
> 200TiB 

#### Client address
> f1eoynacq7iojj4tnhfcptfrvotn4oiyl24catdei

**Comment by simonkim0515** [comment]
## Datacap Request Trigger

#### Total DataCap requested 
> 5PiB

#### Expected weekly DataCap usage rate 
> 200TiB 

#### Client address
> f1eoynacq7iojj4tnhfcptfrvotn4oiyl24catdei

**Comment by cryptowhizzard** [comment]
> @cryptowhizzard
> 
> Hi thanks for your support. I have done the kyc process per official request.
> 
> In terms of your suggestion, I might talk about it with my team. If we need your support, we will abide by your rules.
> 
> Anyway appreciate your quick reply on my application.

To avoid confusion here for other notary's :

I / We have not received KYC details from this applicant. The only thing this applicant has done is send an e-mail as per above, however this not KYC and has gone wrong in the past many many times.

@james0012022 is you want my support then please perform [this KYC](https://form.jotform.com/230337462961356) and fill in the SP's / onboarding plan.

**Comment by james0012022** [comment]
Hey Community & Notaries

I put SP-IDs here for your kind reference and support:

f02031006  -   US
f02033219  -   HK​
f01392893  -   China
f02012175  - Korea
f010479  -  China

**Comment by james0012022** [comment]
@cryptowhizzard 

Thanks for your reminder.
I prefer to put it here for everyone's check and support.

official domain email KYC + SP information

More details can be referred in my LDN application. 

Thanks

**Comment by cryptowhizzard** [comment]
Hi @james0012022 

Protocol labs or the e-mail you refer to above is notKYC. Notary's are obliged to do their own KYC and all notary's know this.
Secondly , one can easily fake the e-mail sender and there is no back / forth communication on these e-mails so let's not pretend that you did KYC ;-)

Anyway , i did check on your miners. Let me know if you need anything more.

> f02031006 > reputation OK.
> f02033219 > reputation OK.
> f01392893 > reputation OK.
> f02012175 > reputation not OK, involved in Abuse / CID sharing.
> f010479 > reputation OK.

**Comment by james0012022** [comment]
@cryptowhizzard 

hey Sir
Even if you are a notary, I ask you please to watch out your word here - pretend.
If you think fil team's official email KYC is not effective, please name it in the community, but not too aggressive here.
@Sunnyiscoming @raghavrmadya 

the words from a notary really make me really confused.

Btw, if it is fine with notaries or fil team, I can have back/forth communication with offiical domain email.

@cryptowhizzard 
Regarding your check on SP reputation, appreciate your due diligence and I will check on it.

**Comment by james0012022** [comment]
Btw, I totally understand rules here and respect all notaries' due diligence. 
We will absolutely process data within rules.
Welcome the community's inspection and support, we will make the improvement according to your suggestion.

Thanks in advance.

**Comment by cryptowhizzard** [comment]
> @cryptowhizzard
> 
> hey Sir Even if you are a notary, I ask you please to watch out your word here - pretend. If you think fil team's official email KYC is not effective, please name it in the community, but not too aggressive here. @Sunnyiscoming @raghavrmadya

Well, i just want to clarify. You said you had performed KYC , but in reality you have not. I want to avoid confusion that other notary's think KYC had been performed.

> 
> the words from a notary really make me really confused.
> 
> Btw, if it is fine with notaries or fil team, I can have back/forth communication with offiical domain email.
> 
> @cryptowhizzard Regarding your check on SP reputation, appreciate your due diligence and I will check on it.

**Comment by james0012022** [comment]
@cryptowhizzard 

Thank you, Sir. Appreciate the clarification - I mentioned official domain email KYC/I have done the kyc process per official request - first time to know they are not KYC.
I think that might be some misunderstanding as well.
From your side, your KYC rules or process will support you to approve my LDN, and other notaries' KYC(may differ in format/content) will help community to know this application well and let them support my LDN if they accept.

Honestly, not very familiar with all detailed rules in the community, but I try to catch up with key information and answer all reasonable questions.

Thanks.

**Comment by james0012022** [comment]
@cryptowhizzard 

Hey Sir, do you have any other questions? is your due diligence finished currently so that I can move forward?

Thanks

**Comment by james0012022** [comment]
@cryptowhizzard
Hey, Sir

If no further questions for current stage, I will move forward by asking for more support in the community.
Thanks.

**Comment by cryptowhizzard** [comment]
Hello @james0012022 

https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1606#issuecomment-1427635339

Please see my post with request to fill out the form so I can do proper KYC.

**Comment by james0012022** [comment]
@cryptowhizzard 

Thank you, Sir.
Regarding this request, I also express my concern and provide my solution - back/forth communication in email if needed.

Some information like address of an applicant seems to be kinda of privacy and like what you concerned about regarding offical domain email KYC, it is easy to be faked.
I have provided all necessary information here.

Anyway thanks for your suggestion.
I will move forward with the community's support.

**Comment by james0012022** [comment]
@Sunnylscoming 

Hi Sunny

I was aware of this issue and already appreciate @cryptowhizzard notification in a timely manner - that is also where the power of community comes from. Thanks again.

With the inspection from the community, the applicant can have improvement and learn more about the project step by step but not just stop here instead.

Thanks.

**Comment by james0012022** [comment]
@Sunnylscoming 

just checked #960  you mentioned. Sorry I have no idea about this.
As a client, my duty is to provide data and select SPs per suggestion from the community, right? 

After the checker as above, I will not work with this SP obviously, but I got another 4 clean SPs. is it not enough for 1st round?

direct me if I missed anything from the project rules.

much appreciated.

**Comment by james0012022** [comment]
@Sunnylscoming 

Hey sunny，we plan to store 8-10 copies for current dataset in hand, which is almost 60T for differrent lessons we filmed for our online platform and other video materials we might not put on the platform but need storage. Besides, we take into account the growth of the data with the increasing business in near future. 
Can you suggest how much we are supposed to apply for? If you need any further information,kindly let me know.

**Comment by james0012022** [comment]
@Sunnyiscoming 

Hi Sunny 
Any further comments or suggestoin?

Thanks

**Comment by Sunnyiscoming** [comment]
@Sunnyiscoming It's me.
@SunnyIscoming I don't know who is him?

**Comment by Sunnyiscoming** [comment]
@james0012022 I have received your KYC email.

**Comment by Sunnyiscoming** [comment]
![image](https://user-images.githubusercontent.com/105098820/222869715-7cb48d5a-c95b-4d2b-9ae1-80287e8f160f.png)

**Comment by james0012022** [comment]
@Sunnyiscoming 

Hey Sunny
Thanks for your reminder!

I'll keep this in mind to avoid any other misunderstanding again.

**Comment by Alex11801** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecpnue2pqwxz3abmz46mdejt6kjvlezer3ajnw5t2s7q7iosgshno 
#### Address 
> f1eoynacq7iojj4tnhfcptfrvotn4oiyl24catdei
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1hhippi64yiyhpjdtbidfyzma6irc2nuav7mrwmi
#### Id
> 4b8276eb-f19d-4666-a340-30a413477511
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecpnue2pqwxz3abmz46mdejt6kjvlezer3ajnw5t2s7q7iosgshno

**Comment by TrueBlood1** [comment]
@Alex11801 Dwart has no previous application and falls in the new client category. Why didn't you perform any due diligence as stated in the [notary application](https://github.com/filecoin-project/notary-governance/issues/657)? 


<html>
<body>


Stage | New Client/small DataCap request | Repeat Client/large DataCap request
-- | -- | --
Before the allocation | 1. Ask for some details about his organization and use plan2. Verify the submitted information3. Score them according to our score sheet | 1. Learn about his DataCap usage2. Collect details[1]about his organization and use plan.3. Detailed review of related information4. Score them according to our score sheet


</body>
</html>

**Comment by james0012022** [comment]
@trueblood1

hey there
I have to jump in here to further clarify.
I believe I have answered all detailed questions and accepted the nice suggestions in above.
I threw my LDN to review channel for many times but no one paid attention except for the faked sunny.

I went to fil team like sunny, RG for support and also went to many notaries in slack for further support.

I appreicate Alex's support!

I have to say, this community is bit disappointing.

just always judging without their own due diligence.

**Comment by james0012022** [comment]
@Sunnyiscoming  Thanks for your support.
@raghavrmadya I appreicate your response in slack, but really need support here. I don't understand, no one cares about the real request in review channel  but cares about other things less important(at least for me) - it might be the reason why no notary wants to give me feedback and so inactive. 

@Alex11801 Thanks for your support. If needed, you can provide the screenshot of our conversation in slack.

**Comment by TrueBlood1** [comment]
@Alex11801 understand but none of what you said is relevant. This is the notary's duty and has nothing to do with the client. Notary set out kyc and due diligence process they will undertake. That said, signings without any explanation are unacceptable.

**Comment by james0012022** [comment]
@TrueBlood1 
sorry, I am client, and I knowhow it happend.
Before faked sunny was regconized, Alex refused me in Slack after detailed review.
It was me who did the due diligence here for the community for such funny things.

Again,it was me who asked many notaries again (not only Alex) for kind reveiw because @Sunnyiscoming showed up with her support in my LDN.

**Comment by TrueBlood1** [comment]
> Lack of diligence from notaries: Of all the recent conversations and arguments of potential bad acting, this is one that the Filecoin Plus program may have the most opportunity to address and correct. **Each notary is required to submit their own set of guidelines, policies, and procedures for how they will perform diligence and award DataCap. What we are seeing in some cases is a total lack of diligence on large dataset applications, with subsequent allocations happening possibly just because “someone else already signed once.”** The policy has always been: ask a client to provide qualitative up-front evidence to justify they are real, have valid data, and can be trusted to engage in good deal-making; then perform subsequent quantitative analysis on their on-chain deal-making data. The governance team has prioritized tooling to make this process easier, simpler, and more consistent for the notaries to perform their stated duties. It is not the role of the governance team to perform diligence on clients or storage providers. We intend to continue prioritizing this, and look forward to hearing suggestions on additional services or tools that can be built, whether it is by us or by the community.

@Alex11801 please see https://github.com/filecoin-project/notary-governance/issues/819

**Comment by james0012022** [comment]
![image](https://user-images.githubusercontent.com/105343308/223400927-b5413235-6750-495f-9f60-054d2cbd2116.png)

**Comment by TrueBlood1** [comment]
> Again,it was me who asked many notaries again (not only Alex) for kind reveiw

What I'm asking is public feedback from notary which has zero business to do with you from the client side. Don't take it wrong.

**Comment by TrueBlood1** [comment]
https://github.com/james0012022 so?

**Comment by james0012022** [comment]
@TrueBlood1 
Yes, actually it is not my business.
but I appreciate the only notary who responded to my request in the past days.
I don't use Github - not tech person, but as client, I care about what happened to the progress of the LDN.

I am always active and care about what really happended here - by talking with the team, sending message to the notaries though there is no response :)


@raghavrmadya 
things continue like this, no more reasonably active support - that is only my concern.

**Comment by TrueBlood1** [comment]
> Alex refused me in Slack after detailed review. It was me who did the due diligence here for the community for such funny things.
> 
> Again,it was me who asked many notaries again (not only Alex) for kind reveiw because @Sunnyiscoming showed up with her support in my LDN.

Sunny is a member of T&T working group lead, she does routinely check on lots of applications. If the regular check can sway the judgment of the notary, I am even more skeptical of Define's qualifications as a notary.

**Comment by TrueBlood1** [comment]
> @raghavrmadya
> things continue like this, no more reasonably active support - that is only my concern.

No proper DD done means no support. Why, how, and since when was it considered "reasonable" for a notary to sign without saying anything? @raghavrmadya will  there be any approach of T&T WG on this?

**Comment by james0012022** [comment]
This is really weird.
I dont udnerstand because I am really new here.

below is my concern. 

@raghavrmadya @Sunnyiscoming 
I input so much information in application and also answered questions here, and I chose to disclose some information in this thread but not in someone's KYC form(that can also be faked because no one else can see what is inside for a notary to check) - I have talked about this with GR at the very beginning of this LDN.
My purpose is to let all notaries who enter in and want to support my LDN see it without repeated questions - efficient. 

I am not sure if a notary MUST say something to "show" their due diligence in this LDN - not reasonable from normal logic though - if yes, it is the rules,the conversation in slack can not be counted in? - if not, clearly let me know. I will know how to communicate with future notaries.

**Comment by TrueBlood1** [comment]
> > Lack of diligence from notaries: Of all the recent conversations and arguments of potential bad acting, this is one that the Filecoin Plus program may have the most opportunity to address and correct. **Each notary is required to submit their own set of guidelines, policies, and procedures for how they will perform diligence and award DataCap. What we are seeing in some cases is a total lack of diligence on large dataset applications, with subsequent allocations happening possibly just because “someone else already signed once.”** The policy has always been: ask a client to provide qualitative up-front evidence to justify they are real, have valid data, and can be trusted to engage in good deal-making; then perform subsequent quantitative analysis on their on-chain deal-making data. The governance team has prioritized tooling to make this process easier, simpler, and more consistent for the notaries to perform their stated duties. It is not the role of the governance team to perform diligence on clients or storage providers. We intend to continue prioritizing this, and look forward to hearing suggestions on additional services or tools that can be built, whether it is by us or by the community.
> 
> @Alex11801 please see [filecoin-project/notary-governance#819](https://github.com/filecoin-project/notary-governance/issues/819)

Again, you can find all your answers here. Please read.

**Comment by james0012022** [comment]
@TrueBlood1 

Thanks for your docs. 
From my unsderstanding, if the information is not full or meet the requirements from some notaries,they will ask for more details. 

Not repeat questions already in applicaiton or this thread - a notary is full time? - sorry i really don't know. 
If the answer is yes, I feel disappointed with the efficiencey here but I respect.

I will know how to communicate in future and thanks for all your information.

**Comment by james0012022** [comment]
A kind reminder:
To all the notaries who entered this LDN and might be willing to support, please ask questions or share your suggestions here.

Thanks for your notice!

**Comment by Alex11801** [comment]
> @Alex11801 Dwart has no previous application and falls in the new client category. Why didn't you perform any due diligence as stated in the [notary application](https://github.com/filecoin-project/notary-governance/issues/657)?
> 
> Stage	New Client/small DataCap request	Repeat Client/large DataCap request
> Before the allocation	1. Ask for some details about his organization and use plan2. Verify the submitted information3. Score them according to our score sheet	1. Learn about his DataCap usage2. Collect details[1]about his organization and use plan.3. Detailed review of related information4. Score them according to our score sheet

@TrueBlood1 Thank you for your feedback. To clarify things here, James have talked to me a lot in slack. I've been keeping an eye on this LDN for quite a period of time. And also I have asked my questions on slack. I signed because I have seen a sincere attitude and very detailed information about the project. As for KYC, @Sunnylscoming have provided a screenshot of the KYC email which is quite straightforward. I don't think there's any point of repetitive work. Anyway, thank you for your kindly reminder.

**Comment by james0012022** [comment]
sigh....still no one

**Comment by TrueBlood1** [comment]
> Currently we have more than 500GB dataset, and I can show you one of them which is part of 2022.
> ![Dwart](https://user-images.githubusercontent.com/105343308/218485343-c91de049-673f-40cf-bcc1-1a92bbc99f9a.png)

> > @Alex11801 Dwart has no previous application and falls in the new client category. Why didn't you perform any due diligence as stated in the [notary application](https://github.com/filecoin-project/notary-governance/issues/657)?
> > Stage	New Client/small DataCap request	Repeat Client/large DataCap request
> > Before the allocation	1. Ask for some details about his organization and use plan2. Verify the submitted information3. Score them according to our score sheet	1. Learn about his DataCap usage2. Collect details[1]about his organization and use plan.3. Detailed review of related information4. Score them according to our score sheet
>
> @TrueBlood1 Thank you for your feedback. To clarify things here, James have talked to me a lot in slack. I've been keeping an eye on this LDN for quite a period of time. And also I have asked my questions on slack. I signed because I have seen a sincere attitude and very detailed information about the project. As for KYC, @Sunnylscoming have provided a screenshot of the KYC email which is quite straightforward. I don't think there's any point of repetitive work. Anyway, thank you for your kindly reminder.

@Alex11801 data size must have been included in the detailed infos. I'm curious what their answer was.

**Comment by TrueBlood1** [comment]
> > Alex refused me in Slack after detailed review. It was me who did the due diligence here for the community for such funny things.
> > Again,it was me who asked many notaries again (not only Alex) for kind reveiw because @Sunnyiscoming showed up with her support in my LDN.
> 
> Sunny is a member of T&T working group lead, she does routinely check on lots of applications. If the regular check can sway the judgment of the notary, I am even more skeptical of Define's qualifications as a notary.

Again, the email posted by Sunny means KYC **NOT** due diligence. 

>[1] Details include but not limited to:
     1. Entity Information
     - Formation documents - this includes certificates of registration/incorporation/information.
     - government-issued identification number for the entity
     2. Authorized Signatory Information
     - evidence of the authorized signatory’s authority to act on behalf of the application entity
     3. Beneficial Owners(optional)
     - If there are any 25%+ shareholders, we need a document as a capitalization table, operating agreement, or something similar to verify the ownership, and also the following information for each of them:
     - legal name;
     - date of birth;
     - street address (P.O. box number is not acceptable);
>[2] Punishments may include disqualifying the applicant certification, publicizing wrong actions in the community, stopping further allocation forever and fining the Filecoin pledged by the client etc. In the extreme scenario, legal options will also be taken basing on the aforementioned DataCap allocation agreement.
>Question for clients:
>1. Introduction of yourself/ your organization(with links)
>2. Use case
>3. Location
>4. Max DataCap Allocation
>5. Filecoin address
>6. Miners you intend to allocate DataCap with allocation proportion
>7. Specific requirement of miners and storage service
>8. For-profit or not

All these above are diligence (which I happen to find in your notary application 😅). It's not the governance team's role to perform DD on clients. I sincerely hope that you do understand the difference. My question stays the same. cc @raghavrmadya

**Comment by james0012022** [comment]
> @Sunnylscoming
> 
> Hey sunny，we plan to store 8-10 copies for current dataset in hand, which is almost 60T for differrent lessons we filmed for our online platform and other video materials we might not put on the platform but need storage. Besides, we take into account the growth of the data with the increasing business in near future. Can you suggest how much we are supposed to apply for? If you need any further information,kindly let me know.

@NDLABS-OFFICE 

Hey there!
Thanks for your attention and due diligence here.

Though it was faked sunny, you can still refer to my answers for some details and some of them might be a big updated as below.

Our team checked the current data:

![1](https://user-images.githubusercontent.com/105343308/224033324-c9cb98fb-f3d6-4f2a-8a2e-23c290631262.png)
![2](https://user-images.githubusercontent.com/105343308/224033332-231b2941-f70f-4780-bd15-f0b08f080774.png)
![3](https://user-images.githubusercontent.com/105343308/224033337-e2b30d82-e032-4088-959d-01b63bb9aee5.png)

Since there is so many stories(weird and apprecaited) here, I do hope dear notary can instruct me  if I miss anything here or some rules I failed to catch up with.

Thanks!

**Comment by cryptowhizzard** [comment]
|| Since there is so many stories(weird and apprecaited) here, I do hope dear notary can instruct me if I miss anything here or some rules I failed to catch up with.

Nr1. Datacap is a gift, not a right.

**Comment by james0012022** [comment]
@cryptowhizzard 

sorry, I don't understand....
I applyied and surely I know it's optional(gift you mean?).

I am not asking for a MUST, I am trying to answer all reasonable questions and seek the support from the community.

and faked sunny issue is definitely WEIRD!!!

**Comment by james0012022** [comment]
@Chris00618 

could you kindly check the context above? the word faked is very resonable.
If you are not happy with that, it is none of my business.
I have patience but I still have the right to ask for support from the community.

Much appriecated.

**Comment by Chris00618** [comment]
![image](https://user-images.githubusercontent.com/105741726/224090882-c88a21e3-2b53-4612-afaa-2a36622a43dc.png)

**Comment by james0012022** [comment]
@Chris00618 
thanks for the doc.
btw, the team has blocked that sunny.

If all members just let the misleading activity happen, sad.
Again, fake is neutral for me, it is a fact, not the words above like "fraud, cheat ,liar".

this is my logic.
If you continue to insist, I will shut up.

btw again, I always show my respectful attitudes to everyone, but i have the right to question.
I believe here it is the free community to share opinions.

Thank you.

**Comment by TrueBlood1** [comment]
As long as some notary have a simple check, everyone would find that lots of violations of f02012175 are related to the applications of ND group members, and have resulted in a large number of unacceptable CID sharings, including: ND Labs, ipollo, Nswap, Bitrise, NFTSTAR、Pow Power, Dr. Ji,  Blockchain Media, BBNews, Proya, and so on.

Highly recommended that other neutral notaries can help to review this application.

**Comment by james0012022** [comment]
thanks for @TrueBlood1 's reminder.
As I read some dispute over CID sharing issue in the past days, I see it is aligned to move on with improvement from my understanding.
Anyway, inspection is welcome and as a client I will work only with the qualifed SPs.

**Comment by james0012022** [comment]
@NDLABS-OFFICE 

Thanks for the response and support.

**Comment by NDLABS-OFFICE** [comment]
@TrueBlood1 Galen McAndrew said a long time ago that the content of github's trumpet speech can be ignored. If you represent any organization, please indicate your identity.

**Comment by NDLABS-OFFICE** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecomnctkqtfxgi2hwcrfcialtlkms7nscvqtk6ouzudgu7fgv2c64 
#### Address 
> f1eoynacq7iojj4tnhfcptfrvotn4oiyl24catdei
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1yayfsv6whu3rheviucvventj3y6t542xfpb47ei
#### Id
> 4b8276eb-f19d-4666-a340-30a413477511
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecomnctkqtfxgi2hwcrfcialtlkms7nscvqtk6ouzudgu7fgv2c64

**Comment by TrueBlood1** [comment]
> Hi @james0012022
> 
> Protocol labs or the e-mail you refer to above is notKYC. Notary's are obliged to do their own KYC and all notary's know this. Secondly , one can easily fake the e-mail sender and there is no back / forth communication on these e-mails so let's not pretend that you did KYC ;-)
> 
> Anyway , i did check on your miners. Let me know if you need anything more.
> 
> > f02031006 > reputation OK.
> > f02033219 > reputation OK.
> > f01392893 > reputation OK.
> > f02012175 > reputation not OK, involved in Abuse / CID sharing.
> > f010479 > reputation OK.

@james0012022 f02012175 has a bad record as has been pointed out many times. What is the reason you have to work with this sp? 

@NDLABS-OFFICE no idea what a trumpet speech is but as a community member, I have every single right to ask questions, and more importantly, I'll be around to make sure no more ND group-like cases happen ;)

**Comment by james0012022** [comment]
@TrueBlood1 
I have no idea where to check SP reputation....could you kindly indicate?
please do not assume eveyrone is so familiar with the whole community and everything.
We need instruction and support.

Even for some outstanding issue in the community, I was reminded by some kind notaries in Slack and went to check.
So I read the alignment in community, all are committed to build up a better coummnity here and move on with respectful inspection and nice support.

f02012175 was pointed out and I also immediately stopped cooperation with this SP by responding here,  which does not mean my LDN is stopped.

I even saw some CID sharing invloved LDN can be accepted because they explained it and accepted the coummunity's support.
Again, welcome your questions as long as my LDN is going on.

As a client, I do not want to see any improper direction against any notary inside.

Thanks

**Comment by NDLABS-OFFICE** [comment]
@TrueBlood1 Questions can be asked at a notary meeting.

**Comment by TrueBlood1** [comment]
> f02012175 was pointed out and I also immediately stopped cooperation with this SP by responding here, which does not mean my LDN is stopped.

Nowhere to find the response you are talking about and no sober notary would approve 5PiB to a 500GiB dataset. Datacap is a gift, not a right. All you need to do is to provide the exact data size to move your application forward. You're not the only one waiting so stop complaining and do what you need to do. 

@NDLABS-OFFICE I don't need you to tell me what to do.

**Comment by TrueBlood1** [comment]
@panges2 not sure if you went through all comments. This client requested 5PB with a 500GB dataset which should not be approved whatsoever.

**Comment by james0012022** [comment]
> 

thanks for the clarification.
@NDLABS-OFFICE  appreciate if you can approve again.

Thanks.

**Comment by NDLABS-OFFICE** [comment]
> 嘿， @NDLABS-OFFICE我删除了您的 datacap 提案，因为已经存在一个提案，所以它导致了错误。您能否再次尝试批准数据上限分配？

I need to resubmit my signature, and I hope LDN can seek quality SPs for data storage, and ND will continue to follow up on the LDN.

**Comment by NDLABS-OFFICE** [comment]
@TrueBlood1 Please review the history of github,thanks

**Comment by TrueBlood1** [comment]
I don't see anything in the ticket. Please walk me through.

**Comment by herrehesse** [comment]
checker:manualTrigger

**Comment by james0012022** [comment]
hello all here
There is some issue happening here ,and I am waiting for the team's response to fix it.

let's keep patience and share the useful comments. Thanks

**Comment by james0012022** [comment]
hello Welcome any question from the community.

**Comment by herrehesse** [comment]
checker:manualTrigger

**Comment by james0012022** [comment]
I have created a new one due to some tech issue.
you can refer to below link:
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/2086

not sure if it is proper to close this one.
