### ISSUE TITLE
[DataCap Application] <OriginStorage> - <Central Weather Bureau OpenData 01>

### ISSUE THREAD

**Issue by Origin-Storage** [filecoin-project/filecoin-plus-large-datasets#1607]
### Data Owner Name

NOAA Rapid Refresh (RAP)

### Data Owner Country/Region

United States

### Data Owner Industry

Life Science / Healthcare

### Website

https://www.nco.ncep.noaa.gov/pmb/products/rap/ 
https://registry.opendata.aws/noaa-rap 

### Social Media

```text
slack: OriginStorage
email product@ipfsorigin.com
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

400TiB

### On-chain address for first allocation

f1xipwsuwwdvbdb5j76l2mzxta3g7ofms7rzjqwzq

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
The Rapid Refresh (RAP) is a NOAA/NCEP operational weather prediction system comprised primarily of a numerical forecast model and analysis/assimilation system to initialize that model. It covers North America and is run with a horizontal resolution of 13 km and 50 vertical layers. The RAP was developed to serve users needing frequently updated short-range weather forecasts, including those in the US aviation community and US severe weather forecasting community. The model is run for every hour of the day; it is integrated to 51 hours for the 03/09/15/21 UTC cycles and to 21 hours for every other cycle. The RAP uses the ARW core of the WRF model and the Gridpoint Statistical Interpolation (GSI) analysis - the analysis is aided with the assimilation of cloud and hydrometeor data to provide more skill in short-range cloud and precipitation forecasts.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
aws s3 ls --no-sign-request s3://noaa-rap-pds/
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### How do you plan to prepare the dataset

lotus

### Please share a sample of the data

```text
aws s3 ls --no-sign-request s3://noaa-rap-pds/
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

More than 3 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, Europe

### How will you be distributing your data to storage providers

Cloud storage (i.e. S3), HTTP or FTP server

### How do you plan to choose storage providers

Slack, Big data exchange, Partners

### How do you plan to make deals to your storage providers

Lotus client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by caoyoungyoung** [comment]
1. Can you share more details about  your organization?  can you provide proof to prove your identify？
2. Where does the data come from? 
3. Central Weather Bureau looks like a government body. Is it sensitive or publiclly accessible?

**Comment by lvschouwen** [comment]
@Origin-Storage 

```
lucas@toolbox:~$ aws s3 ls --no-sign-request s3://cwbopendata/ --recursive --human-readable --summarize
Total Objects: 1210
   Total Size: 25.8 GiB
```

You want 5PiB for a 25.8GiB dataset?
Please explain ...

**Comment by herrehesse** [comment]
@Origin-Storage Looking at the past history associated with your account, would suggest not to do any further applications.

**Comment by lvschouwen** [comment]
@Origin-Storage 
Care to share a update in this LDN in regards to my question yesterday? https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1607#issuecomment-1427540014

If you cannot answer it and cannot tell the community why you need a 5PiB allocation for 25GiB of files may I suggest you close this request to prevent pollution on the dashboard?

**Comment by Sunnyiscoming** [comment]
Any update here?
