### ISSUE TITLE
[DataCap Application] <NOAA GEFS Public dataset>--Part 1

### ISSUE THREAD

**Issue by MiaAus** [filecoin-project/filecoin-plus-large-datasets#1608]
### Data Owner Name

National Oceanic and Atmospheric Administration

### Data Owner Country/Region

United States

### Data Owner Industry

Environment

### Website

https://registry.opendata.aws/noaa-gefs/

### Social Media

```text
Website: https://www.noaa.gov/
Twitter: https://twitter.com/NOAA
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

500TiB

### On-chain address for first allocation

f1epywjw5mm4bihvttndrb35dymznxqpkevbnv36q

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
NOAA is an agency that enriches life through science. Their reach goes from the surface of the sun to the depths of the ocean floor as we work to keep the public informed of the changing environment around them.
```

### Is this project associated with other projects/ecosystem stakeholders?

Yes

### Describe the data being stored onto Filecoin

```text
The Global Ensemble Forecast System (GEFS), previously known as the GFS Global ENSemble (GENS), is a weather forecast model made up of 21 separate forecasts, or ensemble members. The National Centers for Environmental Prediction (NCEP) started the GEFS to address the nature of uncertainty in weather observations, which is used to initialize weather forecast models. The GEFS attempts to quantify the amount of uncertainty in a forecast by generating an ensemble of multiple forecasts, each minutely different, or perturbed, from the original observations. With global coverage, GEFS is produced four times a day with weather forecasts going out to 16 days.
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### How do you plan to prepare the dataset

lotus

### Please share a sample of the data

```text
https://registry.opendata.aws/noaa-gefs/
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

1.5 to 2 years

### In which geographies do you plan on making storage deals

Asia other than Greater China, North America, Europe

### How will you be distributing your data to storage providers

Shipping hard drives

### How do you plan to choose storage providers

Slack

### How do you plan to make deals to your storage providers

Lotus client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Looking at your application i have some questions:
As you are brand new on Github and have no history of past applications it seems to me that applying for 5PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?

Can you show us visible proof of the size of your data and the storage systems you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230337462961356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!

**Comment by simonkim0515** [comment]
## Datacap Request Trigger

#### Total DataCap requested 
> 5PiB

#### Expected weekly DataCap usage rate 
> 500TiB 

#### Client address
> f1epywjw5mm4bihvttndrb35dymznxqpkevbnv36q

**Comment by simonkim0515** [comment]
## Datacap Request Trigger

#### Total DataCap requested 
> 5PiB

#### Expected weekly DataCap usage rate 
> 500TiB 

#### Client address
> f1epywjw5mm4bihvttndrb35dymznxqpkevbnv36q

**Comment by Sunnyiscoming** [comment]
Please provide more information about Sps you will cooperate with.

**Comment by lvschouwen** [comment]
@MiaAus 
So what makes this LDN different then #1483 and #1338 ?

**Comment by MiaAus** [comment]
@Sunnyiscoming Hi, I'm looking for suitable Sps to work with. Before we receive the datacap and start using it, we will have everything ready.

**Comment by MiaAus** [comment]
@lvschouwen Totally different.

**Comment by herrehesse** [comment]
@MiaAus It is completely the same. Please explain yourself.

**Comment by Casey-PG** [comment]
Since this is currently the first round of applications, there are no bot check results available for review. We believe this application meets the Fil+ criteria based on the applicant's description and the distribution plan.

**Comment by Casey-PG** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceby5hx6qboi7ak5fyup4thzxril5to26botb4v27z4aem4or3dbhc 
#### Address 
> f1epywjw5mm4bihvttndrb35dymznxqpkevbnv36q
#### Datacap Allocated
> 250.00TiB
#### Signer Address
> f1d4yb3wags3mtddzesxoo63jv7dmlec3bq4yteni
#### Id
> 796c4ebb-31a8-47da-9426-30912cd2e42e
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceby5hx6qboi7ak5fyup4thzxril5to26botb4v27z4aem4or3dbhc

**Comment by Ewesion** [comment]
KYC is ok, willing to support.

**Comment by Ewesion** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebxvlqehzl6i6ni3i25iejlgck5ejnfa6zgsiav7fhxg5lskjfxus 
#### Address 
> f1epywjw5mm4bihvttndrb35dymznxqpkevbnv36q
#### Datacap Allocated
> 250.00TiB
#### Signer Address
> f1ihv7gz3vn3xqvikpt4rwryecgisl7745lodx3yi
#### Id
> 796c4ebb-31a8-47da-9426-30912cd2e42e
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebxvlqehzl6i6ni3i25iejlgck5ejnfa6zgsiav7fhxg5lskjfxus

**Comment by BobbyChoii** [comment]
Based on the datacap and cid checks, the application meets the expected community requirements.

**Comment by BobbyChoii** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceceozux6xibrbgf276ibhevuvg6yi4wwsd7bexhc7c7jxkhi6otgw 
#### Address 
> f1epywjw5mm4bihvttndrb35dymznxqpkevbnv36q
#### Datacap Allocated
> 500.00TiB
#### Signer Address
> f1irqs2gmctiv3jcdfwuch7oxvf4ixh3k4b2wc24i
#### Id
> 813b7519-02da-407d-8dfd-38b7dbcba101
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceceozux6xibrbgf276ibhevuvg6yi4wwsd7bexhc7c7jxkhi6otgw

**Comment by Aifabot-Cloud** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecderlpeqdkm76ckgizaxpraqzemzl732jk2wahlwregk3lve4qre 
#### Address 
> f1epywjw5mm4bihvttndrb35dymznxqpkevbnv36q
#### Datacap Allocated
> 500.00TiB
#### Signer Address
> f174fg3bqbln3zjnkxtyf6s54txqkr7yqkj6cig7y
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecderlpeqdkm76ckgizaxpraqzemzl732jk2wahlwregk3lve4qre

**Comment by Aifabot-Cloud** [comment]
Good summary report and ongoing communication from the applicant. We would like to see more and more useful datasets get onboarded.

**Comment by Casey-PG** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceclb2mt677fql7ed532kljtyq3v7pqzgut7pkgogqhsxyibsbqfro 
#### Address 
> f1epywjw5mm4bihvttndrb35dymznxqpkevbnv36q
#### Datacap Allocated
> 1000.00TiB
#### Signer Address
> f1d4yb3wags3mtddzesxoo63jv7dmlec3bq4yteni
#### Id
> 85b143f7-4fff-4b52-9bd7-f63d36bf83de
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceclb2mt677fql7ed532kljtyq3v7pqzgut7pkgogqhsxyibsbqfro

**Comment by Meibuy** [comment]
Public data, complaint allocation plan. Willing to support.

**Comment by Meibuy** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceccjjynx2qu3jawf3vqvcnwwhapzor3adtanhyluliivylubd2ho2 
#### Address 
> f1epywjw5mm4bihvttndrb35dymznxqpkevbnv36q
#### Datacap Allocated
> 1000.00TiB
#### Signer Address
> f1bwugfihrmn3iyunzyxst5nttql3dge4khwmurtq
#### Id
> 85b143f7-4fff-4b52-9bd7-f63d36bf83de
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceccjjynx2qu3jawf3vqvcnwwhapzor3adtanhyluliivylubd2ho2

**Comment by Aifabot-Cloud** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecsqzfdhgk5ithwnyeiyb5z4rjxtyndrban5jqosmxgph2uzlnqug 
#### Address 
> f1epywjw5mm4bihvttndrb35dymznxqpkevbnv36q
#### Datacap Allocated
> 1.95PiB
#### Signer Address
> f174fg3bqbln3zjnkxtyf6s54txqkr7yqkj6cig7y
#### Id
> ec72e23d-fb45-4ac7-b93f-d92b92ab0e9a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecsqzfdhgk5ithwnyeiyb5z4rjxtyndrban5jqosmxgph2uzlnqug

**Comment by BobbyChoii** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceca67o5l7im6o4pftn6wscry7bjwai7q46vvrvtql74lbcdsfxp5c 
#### Address 
> f1epywjw5mm4bihvttndrb35dymznxqpkevbnv36q
#### Datacap Allocated
> 1.95PiB
#### Signer Address
> f1irqs2gmctiv3jcdfwuch7oxvf4ixh3k4b2wc24i
#### Id
> ec72e23d-fb45-4ac7-b93f-d92b92ab0e9a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceca67o5l7im6o4pftn6wscry7bjwai7q46vvrvtql74lbcdsfxp5c

**Comment by BobbyChoii** [comment]
Public data with clear allocation plan, we are willing to help onboard more valuable dataset.

**Comment by MiaAus** [comment]
ok!

**Comment by cryptowhizzard** [comment]
Hello,

I see that you are working solely with providers who do not support retrieval and/or have been flagged for CID sharing and abuse.

Can you clarify please.

![Scherm­afbeelding 2023-07-31 om 08 41 31](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/36404435/1471b565-2728-4bc8-96b5-724eff3ceb4e)

**Comment by MiaAus** [comment]
checker:manualTrigger

**Comment by MiaAus** [comment]
checker:manualTrigger

**Comment by cryptowhizzard** [comment]
<img width="568" alt="Scherm­afbeelding 2023-08-25 om 22 42 17" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/36404435/78aa3ce0-e516-4862-a59b-87a8784aba62">

http://www.datasetcreators.com/downloadedcarfiles/httpretrieval/1608-f02036989-f02365890-51878136-baga6ea4seaqjbqzsxw42t4c7kfangatuvbfq5e5ypxavxxegxhtzvdyuy33voiy

You are storing garbage data.

<img width="661" alt="Scherm­afbeelding 2023-08-25 om 22 43 19" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/36404435/0214a9ff-0a51-4bfb-b6b4-0e708beece1a">

**Comment by cryptowhizzard** [comment]
Datacap remove request made:

https://github.com/filecoin-project/notary-governance/issues/973

**Comment by MiaAus** [comment]
@cryptowhizzard I have communicated with SPs about what you showed. They think your download is in error. This result you showed is not from our application. You should remove my application from dispute form!

**Comment by MiaAus** [comment]
My application is at a normal progress, can notaries help sign it?

**Comment by TakiChain** [comment]
checker:manualTrigger

**Comment by raghavrmadya** [comment]
Hi, I'm following up regarding the [dispute](https://www.notion.so/filecoin/Storing-garbage-data-102cf79fa1c548aba055de0f55844a5e?pvs=4) submitted. 

It seems like the client is not satisfied with the evidence provided by the notary. As such, the client must provide evidence of retrieval sample to proceed. Additionally, it is important to note that Deal Data Replication is concerning. 

Notaries are encouraged to not sign without resolving the concerns above.

**Comment by MiaAus** [comment]
The evidence is clear enough.

![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/125250897/e242886d-4ead-4d08-94b9-ff1c193302ec)

**Comment by MiaAus** [comment]
@cryptowhizzard We support retrieval so that you can try to download what you need directly.

**Comment by cryptowhizzard** [comment]
@MiaAus 

Please cooperate per what @raghavrmadya mentioned to get your dispute removed and provide us with the data to do due diligence.

**Comment by MiaAus** [comment]
Hi. Actually it's better for you to download it by yourself. The SPs are supporting retrieval.

> @MiaAus
> 
> Please cooperate per what @raghavrmadya mentioned to get your dispute removed and provide us with the data to do due diligence.

**Comment by MiaAus** [comment]
keep open

**Comment by MiaAus** [comment]
keep open

**Comment by MiaAus** [comment]
Yes

**Comment by Sunnyiscoming** [comment]
Hello, @MiaAus per the https://github.com/filecoin-project/notary-governance/issues/922 for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

This information will be reviewed by Fil+ Governance team to confirm validity and then the application will be allowed to move forward for additional notary review.

**Comment by Sunnyiscoming** [comment]
@MiaAus Hi, please notice this message.
