### ISSUE TITLE
[DataCap Application]About The APP

### ISSUE THREAD

**Issue by nnrecive** [filecoin-project/filecoin-plus-large-datasets#161]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name:  About The Block
- Website / Social Media: www.ata.company
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 1PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 20TiB
- On-chain address for first allocation: f3w37mbq6zs5ntivs35unaxzg67m27zkpawjsiohbtdcpb36cyerlggfhrcxfwsopoktkeseb7ucb5tlcmtitq

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.

>> ATA(About The App) company has a Battleground game team, and plans to save game videos in the ipfs method and upload them to the video platform for use.
    In addition, we are developing a game application and will convert game data into a safe blockchain method.

What is the primary source of funding for this project?

>>There are mainly bonds, credit, bank loans, etc

What other projects/ecosystem stakeholders is this project associated with?

>> Institutional investors, private investors and entertainment companies as well as the Filecoin network.

## Use-case details

Describe the data being stored onto Filecoin

>> Battleground game video and application storage data.

Where was the data in this dataset sourced from?

>> Mainly by user’s data (individual image, video and files and entertainment contents data, business data)

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 

>> https://www.youtube.com/channel/UCPj1NAtVcT-G-jg7MtDDGuA
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).

>> Yes

What is the expected retrieval frequency for this data?

>> It depends on the situation, but it will allow people interested in Battleground to be exposed to the video platform when searching, and will be used as ipfs when loading game data when developing App games.

For how long do you plan to keep this dataset stored on Filecoin?

>>We believe that for individuals, this document will be a permanent archive

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?

>>  Initially, it wants to be stored in Korea, but ultimately all over the world.

How will you be distributing your data to storage providers? Is there an offline data transfer process?

>> It may depend on how quickly the service spreads, but initially we expect 10 TiB per week.

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.

>> We are based on an online deal. As confirmed, 30GB files can be saved if there is no network problem

How will you be distributing deals across storage providers?

>> We are testing storage deals to various miners

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?

>>We are testing with miners who will be aggressive with various clients and looking for more miners.

**Comment by galen-mcandrew** [comment]
Website appears to be built by UJOONET. Is this related to #16 & https://github.com/filecoin-project/filecoin-plus-client-onboarding/issues/553 

Is this the same project?

That client received 3 TiB from direct notary activity, and appears to have made deals with 12 storage providers, with top allocation of 18%. https://filplus.d.interplanetary.one/clients?filter=f3rpablljxoko6djyzbkmtqukfa6dnrzjuzflokeuou4x42nyrfa64e5f4isjm4yfv4mb5v6jtfqgx7hchkh4a

**Comment by galen-mcandrew** [comment]
## Multisig Notary requested
#### Total DataCap requested 
> 1PiB
#### Expected weekly DataCap usage rate 
> 20TiB

**Comment by nnrecive** [comment]
I'm sorry.
It's not related to UJOONET.
Chohee's website is https://www.youtube.com/c/ATB%EC%96%B4%EB%B0%94%EC%9B%83%EB%8D%94%EB%B8%94%EB%A1%9D%EB%8F%88%EB%B2%8C%EA%B1%B8%EB%8F%88%EB%B2%84%EB%82%A8.

It is a project to have https://namu.wiki/w/ATA%20Esports e-sports Team and to store and operate Battleground game videos and application data.

**Comment by nnrecive** [comment]
Hello
It was a project that had nothing to do with MyLink.
I'm sorry for making you confused by my mistake.
I'll organize the contents and re-apply.
I'm sorry.
