### ISSUE TITLE
[DataCap Application] 1000 Genomes Phase 3

### ISSUE THREAD

**Issue by Yazidys** [filecoin-project/filecoin-plus-large-datasets#1610]
### Data Owner Name

International Genome (EMBL-EBI)

### Data Owner Country/Region

United Kingdom

### Data Owner Industry

Life Science / Healthcare

### Website

https://www.internationalgenome.org/category/phase-3/

### Social Media

```text
https://www.ebi.ac.uk/
https://www.facebook.com/illuminainc
https://www.instagram.com/illuminainc/
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

500TiB

### On-chain address for first allocation

f153qu3d3bv2a2imsaicqc37un7krbba7btx73pwq

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
At Illumina, our goal is to apply innovative technologies to the analysis of genetic variation and function, making studies possible that were not even imaginable just a few years ago. It is mission critical for us to deliver innovative, flexible, and scalable solutions to meet the needs of our customers. As a global company that places high value on collaborative interactions, rapid delivery of solutions, and providing the highest level of quality, we strive to meet this challenge.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
This dataset contains alignment files and short nucleotide, copy number, repeat expansion (STR) and structural variant call files from the 1000 Genomes Project Phase 3 dataset (n=3202) using Illumina DRAGEN v3.5.7b and v3.7.6 software.
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### How do you plan to prepare the dataset

lotus

### Please share a sample of the data

```text
https://registry.opendata.aws/ilmn-dragen-1kgp/
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

1.5 to 2 years

### In which geographies do you plan on making storage deals

Asia other than Greater China, North America, South America, Europe

### How will you be distributing your data to storage providers

Cloud storage (i.e. S3), HTTP or FTP server, Shipping hard drives

### How do you plan to choose storage providers

Big data exchange

### How do you plan to make deals to your storage providers

Boost client, Lotus client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by lvschouwen** [comment]
@Yazidys 
So what makes this LDN different then #1549 and #485 ?

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 5PiB

**Expected weekly DataCap usage rate**
> 500TiB

**Client address**
>f153qu3d3bv2a2imsaicqc37un7krbba7btx73pwq

**Comment by Yazidys** [comment]
@lvschouwen My application is indeed different with these application. We just chose the same public dataset to store.

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

As last question i would like you to fill out [this form](https://form.jotform.com/230337462961356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!

**Comment by lvschouwen** [comment]
> @lvschouwen My application is indeed different with these application. We just chose the same public dataset to store.

To what point?
This public dataset is already stored on Filecoin in countless replica's all over the world.
What would the point be storing the same dataset once again on Filecoin?

**Comment by herrehesse** [comment]
@Yazidys 

Please note that we cannot support your request to store the same dataset on Filecoin again, as it has already been stored 10 or more times on chain. The purpose of the datacap from the Filecoin+ program is to enhance the value of the Filecoin network, and duplicating data multiple times does not contribute to that goal.

While you are entitled to store your data on Filecoin, we encourage you to find a dataset that has not been stored on chain multiple times. Therefore, we cannot provide support for storing this dataset since it has already been stored multiple times.

Thank you for your understanding.

**Comment by swatchliu** [comment]
We can Support your request.

**Comment by swatchliu** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedzrsj2bfjorrtz7po7psfpmptl7xztvaeje3kro4ayhdwahfe3bu 
#### Address 
> f153qu3d3bv2a2imsaicqc37un7krbba7btx73pwq
#### Datacap Allocated
> 250.00TiB
#### Signer Address
> f1yh6q3nmsg7i2sys7f7dexcuajgoweudcqj2chfi
#### Id
> 329c7b75-671b-47ba-b793-122ade7c4edf
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedzrsj2bfjorrtz7po7psfpmptl7xztvaeje3kro4ayhdwahfe3bu

**Comment by lvschouwen** [comment]
> We can Support your request.

How ... ?

**Comment by herrehesse** [comment]
Tagging for visibility: @Sunnyiscoming @raghavrmadya @dkkapur @galen-mcandrew @cryptowhizzard 

The notary above @swatchliu will be added to our list of notaries who are on dispute. We can not tolerate this behaviour any longer. https://github.com/filecoin-project/notary-governance/issues/826

Revoke your signature immediately @swatchliu.

**Comment by swatchliu** [comment]
> > We can Support your request.
> 
> How ... ?
Every notary has an independent view, this is an open web3 community, not yours.  IMO, it's  a very normal application and does not violate any rules.  Please leave voluntarily for any unreasonable behavior that interferes with my signature.

@Yazidys ,please find another notary to sign.  If some guys make trouble again, you can complain about them on salck.

**Comment by swatchliu** [comment]
@lvschouwen  Every notary has an independent view, this is an open web3 community, not yours. IMO, it's a very normal application and does not violate any rules. Please leave voluntarily for any unreasonable behavior that interferes with my signature.

@Yazidys ,please find another notary to sign. If some guys make trouble again, you can complain about them on salck.

**Comment by lvschouwen** [comment]
@swatchliu I can choice where to reply to or not.
I do not need your opinion.

**Comment by lvschouwen** [comment]
@raghavrmadya 
I feel that as a community member I can ask questions to notaries.
I must admit that I feel attacked by @swatchliu comment to "leave voluntarily". This feels like a threat and therefor I am tagging you to make this known.

**Comment by dkkapur** [comment]
hey folks - just wanted to chime in with my 2c.

@Yazidys -
> First, it is public data on AWS. Everyone has right to store it.

This is accurate and I agree. Given that it is an open dataset that happens to already have some replicas on the network, it would be great for you to also explain what you are doing in data processing / what makes the replicas you bring useful to the network. The questions from @lvschouwen on asking what makes yours different is a fair one. Let's answer it using objective truths -> you may be processing the data differently, you may be picking SPs differently, etc. 

@swatchliu @lvschouwen - request for you guys to step back a little bit. There's a lot of tension here that we can probably make better progress without. Both of you are right - it is fair for anyone to ask questions of clients and notaries, but it is also fair for a notary to make an independent decision. They went through an application process to earn exactly this right. 

If there's significant disagreement with how a notary is operating and a desire to identify a systematic pattern, calling it out as a dispute as @herrehesse mentioned is the right next step (but also, statements like "Revoke your signature immediately" is not going to get us very far in a small community).

**Comment by herrehesse** [comment]
@dkkapur agreeing with you mostly, the issue is if we accept this behaviour the end is not "near" but already upon us. Tighten the ropes and make sure that what gets through is appropriate, if not then improve tooling to automate this process.

Letting things pass because of "inclusivity" in stead of "truths" is not a good move in my opinion.

We need more and better rules, this is getting out of control.

**Comment by lvschouwen** [comment]
> @swatchliu @lvschouwen - request for you guys to step back a little bit. There's a lot of tension here that we can probably make better progress without. Both of you are right - it is fair for anyone to ask questions of clients and notaries, but it is also fair for a notary to make an independent decision. They went through an application process to earn exactly this right.

Thank you for this reply.
I totally agree that every notary has earned the right.
However I do think that if community members have outstanding questions in regards to a LDN a notary cannot simply sign with "We can Support your request".

My "How" was a bit Dutch maybe, and @herrehesse he reply was more the reply I should have given to @swatchliu. And for this I apologize.

Now that this LDN has a Request Proposed lets wait for a second notary to sign and for the applicant to seal the data to Filecoin. After the 1st or 2nd trench we can make up the bill.

**Comment by dkkapur** [comment]
@herrehesse agree with what you're pushing for here 100% and a few of us are working on proposals towards this every day. Would love to hear other ideas too if anyone has any. 
> Tighten the ropes and make sure that what gets through is appropriate, if not then improve tooling to automate this process.

Separately, as someone that also works in onboarding open datasets to the network -> they are definitely a bit of a shortcut to earning QAP / getting to auction on BDE. However, we should be holding those applying for DataCap to a higher standard. I look forward to hearing more from this applicant and seeing notaries in the future continue to work towards a higher bar.

**Comment by cryptowhizzard** [comment]
> hey folks - just wanted to chime in with my 2c.
> 
> @Yazidys -
> 
> > First, it is public data on AWS. Everyone has right to store it.
> 
> This is accurate and I agree. Given that it is an open dataset that happens to already have some replicas on the network, it would be great for you to also explain what you are doing in data processing / what makes the replicas you bring useful to the network. The questions from @lvschouwen on asking what makes yours different feels a fair one. Let's answer it using objective truths -> you may be processing the data differently, you may be picking SPs differently, etc.
> 
> @swatchliu @lvschouwen - request for you guys to step back a little bit. There's a lot of tension here that we can probably make better progress without. Both of you are right - it is fair for anyone to ask questions of clients and notaries, but it is also fair for a notary to make an independent decision. 

I want to add another angle of view here. But before i do so, i would kindly ask that if people want to respond to it, then please open another issue in the notary governance repo or do it on slack. This topic is for the applicant , about the applicant and his/her plan to onboard data to the network and we should focus on topic.

First : Filecoin and its's notary''s (We) have done KYC since the beginning. I remember doing zooms with Philip Bernard and other notary's to verify who we talk to, who we are and what we do. This is nothing abnormal and protects the FIL+ program from abuse. The issue here at hand is that this KYC or whatever introduction has not been performed in any way. 
Second : I have spoken to Eric many times and have had no notion about him opposing on matters like KYC in the governance calls of project beacon for example.

Therefore @dkkapur and @raghavrmadya  I would like you to push for the urgent protection of the notaries of Filecoin, where if someone gives them an order to do something that is not beneficial to Filecoin and it's community, those involved must know that the outcome will not beneficial on the medium and long term.

Having said this, i will now focus on getting this LDN on track.

**Comment by cryptowhizzard** [comment]
Hi @Yazidys 

First, apologies for above. Filecoin has a dynamic community with lot's of opinions. Let's get your LDN on track asap.
As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence / KYC.

Can you please fill out [this form](https://form.jotform.com/230337462961356) to provide me with the necessary information to make a educated decision on your LDN request? It's a simple KYC to know who you are and what your role is in this LDN and to make the first steps  towards the data onboarding plan.

Thanks!

**Comment by Yazidys** [comment]
Yes, thanks @dkkapur for the mediation. More thanks to @swatchliu for your support and @cryptowhizzard for the great work. 
To be precise, I'm a data prepare and I don't run nodes. I come from an educational research institution in Guangzhou, China, and had the opportunity to come across Filecoin in the hope of getting some profit. I met Jack from BDE in the community and learned that they could help me find SPs I could work with, so I spent almost a month downloading data and processing it as requested.

I'm not aware of an upper limit for data copies. I learned from BDE side that the real data storage of Filecoin is still very early, more data preparers are welcome to help SP to improve their efficiency.

In addition, this is something I do in my spare time, outside of my work. Please understand that I cannot cooperate with the collection of private information such as phone number, form that charges me and so on. 
@dkkapur hope this is enough to continue my application and please let me know if anything is needed.

**Comment by cryptowhizzard** [comment]
> Yes, thanks @dkkapur for the mediation. More thanks to @swatchliu for your support and @cryptowhizzard for the great work. To be precise, I'm a data prepare and I don't run nodes. I come from an educational research institution in Guangzhou, China, and had the opportunity to come across Filecoin in the hope of getting some profit. I met Jack from BDE in the community and learned that they could help me find SPs I could work with, so I spent almost a month downloading data and processing it as requested.
> 
> I'm not aware of an upper limit for data copies. I learned from BDE side that the real data storage of Filecoin is still very early, more data preparers are welcome to help SP to improve their efficiency.
> 
> In addition, this is something I do in my spare time, outside of my work. Please understand that I cannot cooperate with the collection of private information such as phone number, form that charges me and so on. @dkkapur hope this is enough to continue my application and please let me know if anything is needed.

Hi,

_For the record:_
We do not / will not charge you. We have never charged anyone until now and we bear the costs of Veriff  to do KYC until now. I appreciate your opinion but i cannot put a signature on a data preparation / onboard plan from someone i don't know and where the data will be onboarded.

Secondly, I / We know there is abuse going on in the system. I appreciate you look for profit and SP's as we all have to make a living. Storing the data with an SP involved in abuse is a short term goal as your datacap will be slashed in the near future and your LDN blocked.
The work i do is screening the SP's you intend to work with for the first and second tranche. This is a help and security for you and beneficial for all of us. There are many participants moving on the right track since, hence from China.

In case you might change your opinion, you know where to find me/us. ;-)

**Comment by Yazidys** [comment]
@Yazidys Thank you for the concern! :-) We will contact SPs who are up to standard of Fil+ community.

**Comment by Protocan** [comment]
Looks normal and willing to support.

**Comment by Protocan** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebpbbujzithpmg3brhaxjrebzmr2r6x4m6cetlzdyawsysvoywsko 
#### Address 
> f153qu3d3bv2a2imsaicqc37un7krbba7btx73pwq
#### Datacap Allocated
> 500.00TiB
#### Signer Address
> f1vxbqrf7rfum3n6m5u6eb4re6xj7amvsaqnzu64y
#### Id
> 4d0ee270-477b-4d00-b771-b19e5124e8d0
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebpbbujzithpmg3brhaxjrebzmr2r6x4m6cetlzdyawsysvoywsko

**Comment by OlivierMolenkamp** [comment]
Checker report looks fine.  Retrieval can be done. Willing to suport!

**Comment by OlivierMolenkamp** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb3s7wpla4i3azfchpwji5ii2oysvlnaraa66fmc666ofrm5dma5s 
#### Address 
> f153qu3d3bv2a2imsaicqc37un7krbba7btx73pwq
#### Datacap Allocated
> 500.00TiB
#### Signer Address
> f1fl5gjqv3xknuhka273jrsrkzqcumrp6idrnvgyi
#### Id
> 4d0ee270-477b-4d00-b771-b19e5124e8d0
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb3s7wpla4i3azfchpwji5ii2oysvlnaraa66fmc666ofrm5dma5s

**Comment by Aifabot-Cloud** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceayaxzdfkhrtdfb2w5oqx5xhezsjiuov52dswpznqwr3oyvem6n3k 
#### Address 
> f153qu3d3bv2a2imsaicqc37un7krbba7btx73pwq
#### Datacap Allocated
> 1000.00TiB
#### Signer Address
> f174fg3bqbln3zjnkxtyf6s54txqkr7yqkj6cig7y
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceayaxzdfkhrtdfb2w5oqx5xhezsjiuov52dswpznqwr3oyvem6n3k

**Comment by Aifabot-Cloud** [comment]
I have reviewed the application, it meets my stated diligence process, and I will support.

**Comment by Meibuy** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceasz6mlz6jdevoovbyf7aj2thuccvwotszylz6n666izg434mzzms 
#### Address 
> f153qu3d3bv2a2imsaicqc37un7krbba7btx73pwq
#### Datacap Allocated
> 1000.00TiB
#### Signer Address
> f1bwugfihrmn3iyunzyxst5nttql3dge4khwmurtq
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceasz6mlz6jdevoovbyf7aj2thuccvwotszylz6n666izg434mzzms

**Comment by Meibuy** [comment]
The client contacted me by slack and shared the storage plan. I'd like to see more public data joining the network!

**Comment by spaceT9** [comment]
checker:manualTrigger

**Comment by Yazidys** [comment]
checker:manualTrigger

**Comment by Yazidys** [comment]
@spaceT9 OK. We're working on it.

**Comment by cryptowhizzard** [comment]
Seems like all the SP's you have been working with have been flagged for Abuse/Cid sharing and non-retrievability against rules and guidelines of Fil+.

Can you explain?

![Scherm­afbeelding 2023-08-03 om 13 42 34](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/36404435/928b65d5-e8e6-408f-8af7-79ffb8cc53df)
