### ISSUE TITLE
[DataCap Application] <FogMeta Lab> - <NOAA National Blend of Models>[2/2]

### ISSUE THREAD

**Issue by hengdingy** [filecoin-project/filecoin-plus-large-datasets#1612]
### Data Owner Name

FogMeta Lab

### Data Owner Country/Region

China

### Data Owner Industry

Web3 / Crypto

### Website

https://fogmeta.com

### Social Media

```text
Twitter: https://twitter.com/FogMeta
GitHub: https://github.com/FogMeta
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

1PiB

### On-chain address for first allocation

f1hx6abbmocragaffomthxant4i6qjm7rx2skm5hq

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
FogMeta Lab's research spans multiple levels from system technology, infrastructure, and middleware to services and solutions, and involves future systems, network technology and business, distributed systems and management, information management, and interactive and innovative services. Based on the views on and practices in the industry, FogMeta also solves the problem of business complexity through operations optimization and other technologies.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
"The National Blend of Models (NBM) is a nationally consistent and skillful suite of calibrated forecast guidance based on a blend of both NWS and non-NWS numerical weather prediction model data and post-processed model guidance. The goal of the NBM is to create a highly accurate, skillful and consistent starting point for the gridded forecast."

Source:https://registry.opendata.aws/noaa-nbm/
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### How do you plan to prepare the dataset

IPFS, lotus, graphsplit, others/custom tool

### Please share a sample of the data

```text
s3://noaa-nbm-pds/ （424T）
s3://noaa-nbm-grib2-pds/（545.2T）
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Monthly

### For how long do you plan to keep this dataset stored on Filecoin

2 to 3 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, Africa, North America, South America, Europe, Australia (continent), Antarctica

### How will you be distributing your data to storage providers

Cloud storage (i.e. S3), HTTP or FTP server, IPFS, Shipping hard drives, Others

### How do you plan to choose storage providers

Slack, Partners, Others

### If you answered "Others" in the previous question, what is the tool or platform you plan to use

```text
We'd also like to use FilSwan platform (https://filswan.com/) to choose storage providers who meet our requirements.
```

### If you already have a list of storage providers to work with, fill out their names and provider IDs below

```text
The storage providers we'd like to work with are presented below. Some of them are from the FilSwan platform.
f03624
f010088
f02301
f08399
f02401
f0187709
f01163272
f01402814
f01072221
f0240185
f0143858
f01390330
f01225882
f0717969
f03223
f01395673
f01786736
f0836160
f032824
f01443744
f01871352
f01907556
f01946551
f02012951
f01970630
```

### How do you plan to make deals to your storage providers

Boost client, Lotus client, Others/custom tool

### If you answered "Others/custom tool" in the previous question, enter the details here

```text
https://github.com/filswan/go-swan-client
```

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
See questions in #1611

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

As last question i would like you to fill out [this form](https://form.jotform.com/230337462961356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!

**Comment by hengdingy** [comment]
> Dear applicant,
> 
> Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.
> 
> As last question i would like you to fill out [this form](https://form.jotform.com/230337462961356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.
> 
> Thanks!

https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1611#issuecomment-1432423697

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 5PiB

**Expected weekly DataCap usage rate**
> 1PiB

**Client address**
>f1hx6abbmocragaffomthxant4i6qjm7rx2skm5hq

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 5PiB

**Expected weekly DataCap usage rate**
> 1PiB

**Client address**
>f1hx6abbmocragaffomthxant4i6qjm7rx2skm5hq

**Comment by kernelogic** [comment]
Willing to support open dataset from well recognized community entitiy.

**Comment by kernelogic** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec2cjfkh662yfpxb3ikcpoqjbkbebkvxnnvrnci5mu4meeoihi4gc 
#### Address 
> f1hx6abbmocragaffomthxant4i6qjm7rx2skm5hq
#### Datacap Allocated
> 256.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### Id
> c5d4a576-dea9-4e39-aba6-d8636b9a2120
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec2cjfkh662yfpxb3ikcpoqjbkbebkvxnnvrnci5mu4meeoihi4gc

**Comment by cryptowhizzard** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceavufqqmzso37skubvvlwo3r4jioti4g2todoiwyfduyjmkxyomfi 
#### Address 
> f1hx6abbmocragaffomthxant4i6qjm7rx2skm5hq
#### Datacap Allocated
> 256.00TiB
#### Signer Address
> f1krmypm4uoxxf3g7okrwtrahlmpcph3y7rbqqgfa
#### Id
> c5d4a576-dea9-4e39-aba6-d8636b9a2120
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceavufqqmzso37skubvvlwo3r4jioti4g2todoiwyfduyjmkxyomfi

**Comment by cryptowhizzard** [comment]
KYC / Data onboarding plan done. Ready to start!

Looking forward to the first milestone!

**Comment by hengdingy** [comment]
checker:manualTrigger

**Comment by hengdingy** [comment]
checker:manualTrigger

**Comment by zcfil** [comment]
checker:manualTrigger

**Comment by zcfil** [comment]
checker:manualTrigger

**Comment by zcfil** [comment]
The data allocation looks very healthy, and the retrieval is normal. I support this round.
![8ae945e3c0e4c8812a46f01407b0274](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/45065975/2e1bc1c9-8ed1-44a5-bc0c-b2a1b7988a31)

**Comment by zcfil** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecrgqtrnzt7o5ijnvnxghdpq5rjjkjamt6ewkmvtpyfqnntf23yri 
#### Address 
> f1hx6abbmocragaffomthxant4i6qjm7rx2skm5hq
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f1cjzbiy5xd4ehera4wmbz63pd5ku4oo7g52cldga
#### Id
> f06495ba-f0fc-43e4-80f0-3b44f4691582
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecrgqtrnzt7o5ijnvnxghdpq5rjjkjamt6ewkmvtpyfqnntf23yri

**Comment by nj-steve** [comment]
checker:manualTrigger

**Comment by nj-steve** [comment]
The report looks good, everything looks healthy.
<img width="1092" alt="1612" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/15796059/417809de-fe11-4d24-96d4-d1d8c1648ff6">

**Comment by nj-steve** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacea73amds6tbhgotfqox5py3i7xizy3qd4cbbbaknurx6kpnlwgtiy 
#### Address 
> f1hx6abbmocragaffomthxant4i6qjm7rx2skm5hq
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f1xx6555qijma7igpnjspyvdunc4vfxkawnpqy5ii
#### Id
> f06495ba-f0fc-43e4-80f0-3b44f4691582
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacea73amds6tbhgotfqox5py3i7xizy3qd4cbbbaknurx6kpnlwgtiy

**Comment by cryptowhizzard** [comment]
checker:manualTrigger

**Comment by Normalnoise** [comment]
checker:manualTrigger

**Comment by kernelogic** [comment]
Report LGTM. There is a open auditing regarding FogMeta however it's only regarding [1733-1742](https://github.com/filecoin-project/notary-governance/issues/897#issuecomment-1618972092). Therefore I am going to support this round.

**Comment by kernelogic** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebq27qsmjkaub22fr33mw7vd3nsyrsp4wqdvqkvcctg6skt2eepqy 
#### Address 
> f1hx6abbmocragaffomthxant4i6qjm7rx2skm5hq
#### Datacap Allocated
> 1.00PiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### Id
> fa775f55-847f-4bff-944d-243738ed7611
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebq27qsmjkaub22fr33mw7vd3nsyrsp4wqdvqkvcctg6skt2eepqy

**Comment by igoovo** [comment]
checker:manualTrigger

**Comment by igoovo** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacea2sktzpbsszbt62ylnmb2mmcfjdwsggpchmj3jtujwrjacd6ycvk 
#### Address 
> f1hx6abbmocragaffomthxant4i6qjm7rx2skm5hq
#### Datacap Allocated
> 1.00PiB
#### Signer Address
> f1shnsfayxqll77svffaxnjenms7bbbysbqcatrpy
#### Id
> fa775f55-847f-4bff-944d-243738ed7611
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacea2sktzpbsszbt62ylnmb2mmcfjdwsggpchmj3jtujwrjacd6ycvk

**Comment by hengdingy** [comment]
checker:manualTrigger

**Comment by Sunnyiscoming** [comment]
Hello, @hengdingy per the https://github.com/filecoin-project/notary-governance/issues/922 for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

This information will be reviewed by Fil+ Governance team to confirm validity and then the application will be allowed to move forward for additional notary review.
