### ISSUE TITLE
[DataCap Application] <FogMeta Lab> - <Distributed Archives for Neurophysiology Data Integration>[1/2]

### ISSUE THREAD

**Issue by hengdingy** [filecoin-project/filecoin-plus-large-datasets#1614]
### Data Owner Name

FogMeta Lab

### Data Owner Country/Region

China

### Data Owner Industry

Web3 / Crypto

### Website

https://fogmeta.com

### Social Media

```text
Twitter: https://twitter.com/FogMeta
GitHub: https://github.com/FogMeta
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

1PiB

### On-chain address for first allocation

f1fh6xy4jjndwjgaey3hoyjsps34hj6de3rvjg27i

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
FogMeta Lab's research spans multiple levels from system technology, infrastructure, and middleware to services and solutions, and involves future systems, network technology and business, distributed systems and management, information management, and interactive and innovative services. Based on the views on and practices in the industry, FogMeta also solves the problem of business complexity through operations optimization and other technologies.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
"DANDI is a public archive of neurophysiology datasets, including raw and processed data, and associated software containers. Datasets are shared according to a Creative Commons CC0 or CC-BY licenses. The data archive provides a broad range of cellular neurophysiology data. This includes electrode and optical recordings, and associated imaging data using a set of community standards: NWB:N - NWB:Neurophysiology, BIDS - Brain Imaging Data Structure, and NIDM - Neuro Imaging Data Model. Development of DANDI is supported by the National Institute of Mental Health."

Distributed Archives for Neurophysiology Data Integration (DANDI) was accessed on Feb 15,2023 from https://registry.opendata.aws/dandiarchive.
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### How do you plan to prepare the dataset

IPFS, graphsplit, others/custom tool

### If you answered "other/custom tool" in the previous question, enter the details here

```text
We'd like to use the Swan Client (https://github.com/filswan/go-swan-client#Graphsplit) to prepare the dataset.
```

### Please share a sample of the data

```text
s3://dandiarchive/ (599T)

More:
https://dandiarchive.org/dandiset
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Monthly

### For how long do you plan to keep this dataset stored on Filecoin

2 to 3 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, Africa, North America, South America, Europe, Australia (continent), Antarctica

### How will you be distributing your data to storage providers

Cloud storage (i.e. S3), HTTP or FTP server, IPFS, Shipping hard drives, Others

### How do you plan to choose storage providers

Slack, Partners, Others

### If you answered "Others" in the previous question, what is the tool or platform you plan to use

```text
We'd like to use the FilSwan platform (https://filswan.com/) to choose storage providers who meet our requirements.
```

### If you already have a list of storage providers to work with, fill out their names and provider IDs below

```text
The storage providers we'd like to work with are presented below. Some of them are from the FilSwan platform.
f01955033
f02029115
f03624
f010088
f02301
f08399
f02401
f01955030
f0187709
f01163272
f01402814
f01072221
f0240185
f0143858
f01390330
f01225882
f0717969
f03223
f01395673
f01786736
f0836160
f032824
f01443744
f01871352
f01907556
f01955028
f01947280
f01946551
f02012951
f01970630
```

### How do you plan to make deals to your storage providers

Boost client, Lotus client, Others/custom tool

### If you answered "Others/custom tool" in the previous question, enter the details here

```text
Swan Client tool
https://github.com/filswan/go-swan-client
```

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by flyworker** [comment]
As the current design of FilSwan platform, not every node is guaranteed of retrieval, you need to be aware of this and make more copies.

FilSwan may give nodes higher score with good retrieval performance test.

**Comment by Sunnyiscoming** [comment]
> If you already have a list of storage providers to work with, fill out their names and provider IDs below
> The storage providers we'd like to work with are presented below. Some of them are from the FilSwan platform.
> f01955033
> f02029115
> f03624
> f010088
> f02301
> f08399
> f02401
> f01955030
> f0187709
> f01163272
> f01402814
> f01072221
> f0240185
> f0143858
> f01390330
> f01225882
> f0717969
> f03223
> f01395673
> f01786736
> f0836160
> f032824
> f01443744
> f01871352
> f01907556
> f01955028
> f01947280
> f01946551
> f02012951
> f01970630

Are all of them supportive of data retrieval?

**Comment by herrehesse** [comment]
@hengdingy Is this application similar to #1550 & #486 ? If they are similar I do not see a reason to store this dataset with another X amount of copies with datacap.

**Comment by hengdingy** [comment]
> > If you already have a list of storage providers to work with, fill out their names and provider IDs below
> > The storage providers we'd like to work with are presented below. Some of them are from the FilSwan platform.
> > f01955033
> > f02029115
> > f03624
> > f010088
> > f02301
> > f08399
> > f02401
> > f01955030
> > f0187709
> > f01163272
> > f01402814
> > f01072221
> > f0240185
> > f0143858
> > f01390330
> > f01225882
> > f0717969
> > f03223
> > f01395673
> > f01786736
> > f0836160
> > f032824
> > f01443744
> > f01871352
> > f01907556
> > f01955028
> > f01947280
> > f01946551
> > f02012951
> > f01970630
> 
> Are all of them supportive of data retrieval?

@Sunnyiscoming 
As @flyworker said, FilSwan cannot guarantee that every storage provider supports retrieval. But we will definitely choose those with higher scores.

**Comment by herrehesse** [comment]
@hengdingy Can you respond to the above question, thank you.

**Comment by flyworker** [comment]
> 

FiLSwan just update the score measurement, but I suggest you add some other SPs you feel confident.

**Comment by hengdingy** [comment]
> @hengdingy Is this application similar to #1550 & #486 ? If they are similar I do not see a reason to store this dataset with another X amount of copies with datacap.

Thanks @herrehesse, we have noticed that **New datasets deposited every month**, so We think new dataset and more copies need to be stored to the Filecoin network.  Hope @herrehesse can support us. and as @flyworker said, we will store the data to some confident SPs(high score in the Filswan platform and have contacted) to guarantee the Retrievable.
<img width="1195" alt="image" src="https://user-images.githubusercontent.com/107467232/219708942-cf2780b7-cea2-4695-931e-21821290968b.png">

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 5PiB

**Expected weekly DataCap usage rate**
> 1PiB

**Client address**
>f1fh6xy4jjndwjgaey3hoyjsps34hj6de3rvjg27i

**Comment by kernelogic** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceczmvzkqkdm6dn34l4f5fm6b52qw3gbctv2ao7mdrg3xijvtnvkdi 
#### Address 
> f1fh6xy4jjndwjgaey3hoyjsps34hj6de3rvjg27i
#### Datacap Allocated
> 256.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### Id
> 1d97f587-db7c-420e-bd8e-11f39c4ed760
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceczmvzkqkdm6dn34l4f5fm6b52qw3gbctv2ao7mdrg3xijvtnvkdi

**Comment by cryptowhizzard** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecgnk7qlcnu5pwlx73jcqoed2invmnyqo2g6w7p7bvdgre3bpegw2 
#### Address 
> f1fh6xy4jjndwjgaey3hoyjsps34hj6de3rvjg27i
#### Datacap Allocated
> 256.00TiB
#### Signer Address
> f1krmypm4uoxxf3g7okrwtrahlmpcph3y7rbqqgfa
#### Id
> 1d97f587-db7c-420e-bd8e-11f39c4ed760
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecgnk7qlcnu5pwlx73jcqoed2invmnyqo2g6w7p7bvdgre3bpegw2

**Comment by herrehesse** [comment]
Dear Filecoin+ Github applicant,

We have noticed that some of you are submitting merged datacap requests for datasets that are already (partly) on the chain. While we appreciate your enthusiasm to contribute to the Filecoin network, we want to remind you that this behaviour may not be beneficial to the network in the long run. In fact, this behaviour has been questioned and discussed in issue https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/832 on the Filecoin notary-governance Github repository.

We encourage you to review the discussions in issue https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/832. It's important to ensure that your datacap requests are valid, necessary, and add value to the network. By doing so, you can help to maintain the integrity and sustainability of the Filecoin network.

You can find the link to issue https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/832 here: https://github.com/filecoin-project/notary-governance/issues/832

Thank you for your understanding and cooperation.

**Comment by Normalnoise** [comment]
checker:manualTrigger

**Comment by Normalnoise** [comment]
checker:manualTrigger

**Comment by zcfil** [comment]
checker:manualTrigger

**Comment by nj-steve** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceblrypux5kzghb2sqs4x3cellq6kcoieimsoyyrbgxpqvfsuw6fak 
#### Address 
> f1fh6xy4jjndwjgaey3hoyjsps34hj6de3rvjg27i
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f1xx6555qijma7igpnjspyvdunc4vfxkawnpqy5ii
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceblrypux5kzghb2sqs4x3cellq6kcoieimsoyyrbgxpqvfsuw6fak

**Comment by igoovo** [comment]
checker:manualTrigger

**Comment by igoovo** [comment]
![WechatIMG1](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/103082537/f7b339ba-a160-4677-9f44-9be314628cee)

![WechatIMG2](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/103082537/3ffac800-194e-4e9b-98d5-f3b3660e9503)

**Comment by hengdingy** [comment]
checker:manualTrigger

**Comment by hengdingy** [comment]
checker:manualTrigger
