### ISSUE TITLE
[DataCap Application] BigDataBeast - Storing /dev/urandom

### ISSUE THREAD

**Issue by ghost** [filecoin-project/filecoin-plus-large-datasets#1621]
### Data Owner Name

Nobody is the owner of this data

### Data Owner Country/Region

Holy See (Vatican City State)

### Data Owner Industry

Other

### Website

https://en.wikipedia.org/wiki//dev/random

### Social Media

```text
n/a
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

100TiB

### On-chain address for first allocation

f1aawstijtepfw6u25anfk6rh5a6sdkgt5zuxdgwy

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
This project is to store parts of /dev/urandom on Filecoin.
We believe that Filecoin and FIL+ is the ideal method of storing this data.

/dev/urandom is completely random and to store 5PiB of this random data on the chain is clearly invaluable.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
We will prepare 33000 files of 17GiB (the ideal size to fill a 32GiB sector) with /dev/urandom
We have asked ChatGPT how to create the files and this was the result

#!/bin/bash

for i in {1..33000}
do
  # Generate a random filename with 8 random characters
  filename=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 8 | head -n 1)

  # Create the file with random data
  dd if=/dev/urandom of="$filename" bs=1G count=17

  echo "Created file $filename"
done
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### How do you plan to prepare the dataset

singularity

### Please share a sample of the data

```text
Well that is going to be hard, because every time the sample will be different.
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Sporadic

### For how long do you plan to keep this dataset stored on Filecoin

Permanently

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, Europe

### How will you be distributing your data to storage providers

HTTP or FTP server

### How do you plan to choose storage providers

Slack, Big data exchange

### How do you plan to make deals to your storage providers

Boost client, Lotus client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
Are you storing these files just to get Datacap? It's hard to tell if the data is valid and authorized.

**Comment by Sunnyiscoming** [comment]
Any update here?
