### ISSUE TITLE
[DataCap Application] Chengdu Katy Business Service Co. , Ltd

### ISSUE THREAD

**Issue by chengdukaty** [filecoin-project/filecoin-plus-large-datasets#1628]
### Data Owner Name

Chengdu Katy Business Service Co. , Ltd.

### Data Owner Country/Region

China

### Data Owner Industry

Information, Media & Telecommunications

### Website

kelpservice.com

### Social Media

```text
none
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

200TiB

### On-chain address for first allocation

f1x42jxzwbpbgpqdkfbglgzm5bl24u6wxckdkkh4y

### Custom multisig

- [x] Use Custom Multisig

### Identifier

E-Fil

### Share a brief history of your project and organization

```text
Katy Business Service was established in 2014, as a company dedicated to providing comprehensive one-stop cultural communication for various enterprises and institutions, adhering to the business philosophy of "Beginning with goodness, aesthetics, creativity and creation", we are committed to providing customized and diversified integrated marketing communication services, forming an industrial service system that integrates PR communication and event planning.

Our team integrates planning, shooting and promotion, we have served hundreds of companies and hundreds of thousands of people, and accumulated a large number of cases and data.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
The data stored on the filecoin network originates from our company. Over the 10 years of our existence, we have accumulated a large amount of data, mainly campaign data and filming data, as we plan programs and provide filming and distribution for our clients.
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### How do you plan to prepare the dataset

lotus, singularity, graphsplit

### Please share a sample of the data

```text
A Module resource
https://drive.google.com/drive/folders/1xngHf3Mo8tmN7vf523xfgapYL2gEZopH?usp=share_link
B Activity Planning （The vineyard）
https://drive.google.com/drive/folders/1VEL0yjbZRjILEgHeNkPPUYGPNamMu-TM?usp=share_link
C Activity Planning (Panda Cup)
https://drive.google.com/drive/folders/147k_-vFmBDpCkrDknk07BOSRN2_e1hjm?usp=share_link
D Activity Planning（Fang Cao Primary School）
https://drive.google.com/drive/folders/1h15vAzuOA1p8M9RTwmw6SW1dMPsRtf-7?usp=share_link
E Activity Planning （Chivalry Cup）
https://drive.google.com/drive/folders/1crSdejw0kh-Uf_elZq9xTmzeYzCya8D0?usp=share_link
F photograph Videograph
https://drive.google.com/drive/folders/1xO3Jx4saA16ZIwnMbFjOGLhymVb7E-RP?usp=share_link
G Activity Planning （Digital Parking）
https://drive.google.com/drive/folders/15InetFVTGFH27SmPDWbq7Dpqn7-8mUAq?usp=share_link
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

1 to 1.5 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America

### How will you be distributing your data to storage providers

Shipping hard drives, Lotus built-in data transfer

### How do you plan to choose storage providers

Slack, Filmine, Big data exchange

### How do you plan to make deals to your storage providers

Boost client, Lotus client, Singularity

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Looking at your application i have some questions:
As you are brand new on Github and have no history of past applications it seems to me that applying for 5PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?

Can you show us visible proof of the size of your data and the storage systems you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230337462961356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!

**Comment by Sunnyiscoming** [comment]
The data samples you provided contains too many personal photos. It's hard to say whether it is authorized to store them as public data. Can you provide more materials to prove that.
Can you provide detailed information about Sps you will cooperate with?

**Comment by caoyoungyoung** [comment]
The sample includes a lot personal photos of children. Did you have the permission from their parents to store those pics? It is more like a E-fil+ project

**Comment by cryptowhizzard** [comment]
> The sample includes a lot personal photos of children. Did you have the permission from their parents to store those pics? It is more like a E-fil+ project

agree

**Comment by chengdukaty** [comment]
> 该样本包括很多儿童的个人照片。你有没有得到他们父母的许可来存储这些照片？它更像是一个E-fil+项目

As an event planning and photography company, every time we hold an event or undertake a customer's shooting plan, we will record wonderful moments, and these records are usually presented in the form of photos.

I think this is the problem with all photography companies, we have a lot of clients, our cameras and computer memory are full.

However, out of responsibility to customers, especially many customers who have signed annual cooperation agreements, we cannot delete these pictures.

We hope to have a good enough platform to help us store data, and we think filecoin is a good enough platform.

What is the E-fil+ project you mentioned? Can you help us? I would be very grateful if someone could tell me

**Comment by caoyoungyoung** [comment]
Hi 
E-Fil+ is to preserve private/encrpted data, that's the main difference.  You can find more details in https://efilplus.super.site/

**Comment by Sunnyiscoming** [comment]
Hi @kevzak , there is a fil+ project.

**Comment by kevzak** [comment]
> Hi E-Fil+ is to preserve private/encrpted data, that's the main difference. You can find more details in https://efilplus.super.site/

Please let me know if you have any questions on the E-Fil+ Process @chengdukaty
