### ISSUE TITLE
[DataCap Application] Taiwan University

### ISSUE THREAD

**Issue by KizenYang** [filecoin-project/filecoin-plus-large-datasets#1629]
### Data Owner Name
Taiwan University

### Data Owner Country/Region
Taiwan, Province of China

### Data Owner Industry
Construction, Property & Real Estate

### Website
[https://www.ntu.edu.tw/](https://www.ntu.edu.tw/)

### Social Media
https://www.facebook.com/iloventu (https://twitter.com/univkyoto)

### Total amount of DataCap being requested
1 PiB

### Weekly allocation of DataCap requested
32 TiB

### On-chain address for first allocation
f3r7kqm3jylrbrynnxt4qrng6muvou5pkrkhnezikmeaiynj63tfpwumkgbcwa53f4e2e574xk7ea6vrz46fua

### Custom multisig
No

### Share a brief history of your project and organization
none

### Is this project associated with other projects/ecosystem stakeholders?
No

### Describe the data being stored onto Filecoin
none

### Where was the data currently stored in this dataset sourced from
My own storage infra

### How do you plan to prepare the dataset
lotus

### Please share a sample of the data
none

### Confirm that this is a public dataset that can be retrieved by anyone on the Network
No

### What is the expected retrieval frequency for this data
Monthly

### For how long do you plan to keep this dataset stored on Filecoin
2 to 3 years

### In which geographies do you plan on making storage deals
Greater China

### How will you be distributing your data to storage providers
Lotus built-in data transfer

### How do you plan to choose SP
Slack

### How do you plan to make deals to your storage providers
Lotus client

### Can you confirm that you will follow the Fil+ guideline
Yes

**Comment by KizenYang** [comment]
Please ignore, I reapply

**Comment by sklay** [comment]
Please ignore, I reapply

**Comment by sklay** [comment]
Please ignore, I reapply

**Comment by sklay** [comment]
> **Thanks for your request!** Everything looks **good**. 👌
> 
> A Governance Team member will review the information provided and contact you back pretty soon.

Please ignore, I reapply
