### ISSUE TITLE
[DataCap Application]Talken

### ISSUE THREAD

**Issue by XixiTalken** [filecoin-project/filecoin-plus-large-datasets#163]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Talken.io
- Website / Social Media: https://talken.io/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):100TiB
- On-chain address for first allocation: f1smkg3penf4nrooa6tmzxphfrlt5c567gfa5azka

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Talken is a multi-chain decentralized NFT wallet with the largest community. It facilitates all social interaction, engagement and transaction for creators and users with digital assets like NFTs, and real assets on the blockchain. Talken NFT Suite offers a suite of products for every stage of lifecycle of NFTs: 1) simple NFT minting tool provided to creators for super easy NFT minting procedures, and artists can drop & auction on multichain to engage more users; 2) It provides seamless browsing for supported chain or DApps, users will have an ultra-convenient and secure multi-chain NFT wallet; 3) It is also an interoperable NFT marketplace for all participants in the digital world where they can buy & trade NFTs securely and immutably in the mobile payment & crypto payment enabled multi-chain NFT marketplace. Ultimately, Talken will serve as a multi-functional trading platform for creators and users to define how to engage with each other and build communities in the digital world. 
```

What is the primary source of funding for this project?
```
The seed round of funding involved Honest Venture and BDC Labs in. 
```

What other projects/ecosystem stakeholders is this project associated with?
```
After acquiring CoinManager in 2019, we have established cooperative relations with Huobi HECO, Binance Smart Chain, and Klaytn successively. Now we have completed a round of private placement financing, which was invested by Kryptos Research, Pharos Capital, Tachyon Partners, Alphabit, BabySwap and other institutions. Check the details here: https://talken.io/#partners
```

## Use-case details

Describe the data being stored onto Filecoin
```
The wallet supports seamless browsing for multi-chain, therefore it’s significant to transfer the datas of the assets and NFT to a decentralized storage network which can guarantee its interoperability and security. In addition, only by means of the decentralized storage network like Filecoin or Arweave , users can identify whether the NFT metadata is valid or not.
```

Where was the data in this dataset sourced from?
```
The data mainly comes from Dapp browser and NFT marketplace on Talken.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://image.toast.com/aaaaave/pd/cu/mp_lB2mIsau/F02R1QKRH2R.png
https://nftbe.talken.io/talkenNft/QmT8wnWAeGENBTMiZJ1SE5BJc9H3EBRw9v8WM65eFrKLUt.png
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes, we confirm this is a public dataset that can be retrieved by anyone on the network with no specific permissions or access rights required.
```

What is the expected retrieval frequency for this data?
```
There is no demand for frequent retrieval and it’s probably once a year.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
Expectedly 3 years and it’s likely to be extended afterwards.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
We plan to make deals in Korea, Singapore or China if possible.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
The data are expectedly distributed online to storage providers. We have no offline transfer process yet.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We get some advice from the storage provider community and get some tries with different providers. And we hope some skilled storage providers could contact us by email: xixi@talken.io
```

How will you be distributing deals across storage providers?
```
We plan to distribute deals to 3 providers at least.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes we have got some advice and resources from the community to make deals. We don’t need funding. But if there is some funding support from Filecoin, that would be great. Thank you. 
```

**Comment by KwrayFF** [comment]
HI @XixiTalken !
Thanks for applying. I'm with the Filecoin Foundation and here to review this application for accuracy and authenticity. Have a few questions to help get this processed for you.

Can you please provide additional contact information from associates within your company? 
-  Ideally some of the Github handles from 'The Team' website (https://talken.io/static/introPage/index.html?osType=null&isMobile=false&isBrowserKorean=false#mm5). 
- Email addresses from the company directory.

**Comment by XixiTalken** [comment]
> HI @XixiTalken ! Thanks for applying. I'm with the Filecoin Foundation and here to review this application for accuracy and authenticity. Have a few questions to help get this processed for you.
> 
> Can you please provide additional contact information from associates within your company?
> 
> * Ideally some of the Github handles from 'The Team' website (https://talken.io/static/introPage/index.html?osType=null&isMobile=false&isBrowserKorean=false#mm5).
> * Email addresses from the company directory.

Hi @KwrayFF , thanks for your reply. Here is the information for your reference.

- Github Handle from the Team: 
[](https://github.com/hwnahm )
[](https://github.com/woojae-cho)

- Company email address:  
xixi@talken.io 
km.kim@talken.io

**Comment by XixiTalken** [comment]
> HI @XixiTalken ! Thanks for applying. I'm with the Filecoin Foundation and here to review this application for accuracy and authenticity. Have a few questions to help get this processed for you.
> 
> Can you please provide additional contact information from associates within your company?
> 
> * Ideally some of the Github handles from 'The Team' website (https://talken.io/static/introPage/index.html?osType=null&isMobile=false&isBrowserKorean=false#mm5).
> * Email addresses from the company directory.

Hi @KwrayFF , thanks for your reply. Here is the information for your reference.

- Github Handle from the Team: 
https://github.com/hwnahm 
https://github.com/woojae-cho

- Company email address:  
xixi@talken.io 
km.kim@talken.io

**Comment by galen-mcandrew** [comment]
## Multisig Notary requested
#### Total DataCap requested 
> 5PiB
#### Expected weekly DataCap usage rate 
> 100TiB

**Comment by XixiTalken** [comment]
Hi, @KwrayFF , @galen-mcandrew , given that there have been no updates in our application since 6 days ago, could you please give us some tips on what to do next?

**Comment by MegTei** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceafgk46xdkbyzgs5b7upi7qbw5f7z7iljp4dvwysddqfqa4wkew4o 
#### Address 
> f1smkg3penf4nrooa6tmzxphfrlt5c567gfa5azka
#### Datacap Allocated
> 50TiB
#### Signer Address
> f1ystxl2ootvpirpa7ebgwl7vlhwkbx2r4zjxwe5i
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceafgk46xdkbyzgs5b7upi7qbw5f7z7iljp4dvwysddqfqa4wkew4o

**Comment by Reiers** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaq7gitkua3asqycvef2nh6uibl5nbj6ksnbjy5wuamarg7h4nxea 
#### Address 
> f1smkg3penf4nrooa6tmzxphfrlt5c567gfa5azka
#### Datacap Allocated
> 50TiB
#### Signer Address
> f1oz43ckvmtxmmsfzqm6bpnemqlavz4ifyl524chq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaq7gitkua3asqycvef2nh6uibl5nbj6ksnbjy5wuamarg7h4nxea

**Comment by mr-spaghetti-code** [comment]
Hi,

It looks like you received 50TiBs of DataCap to date but have spent less than 20% of it so far.

We would love to understand if there's anything holding you back. We are working hard to make the data onboarding process easier for clients like you and your feedback is very valuable. If you have a moment, please fill in this survey: https://forms.gle/s6AuTXZPZSMokscLA

If you have any feedback or would like to consult with an expert, please let me know. 

Thanks,

João Fiadeiro
Product Manager, Large Data Client Onboarding
Protocol Labs

**Comment by XixiTalken** [comment]
Hi @mr-spaghetti-code , I have completed the survey. We did have some problems in the data onboarding process, we're just still looking for storage providers so far. 
We'll contact you if we have any issues, thanks for your concern!

**Comment by ClarkYin5566** [comment]
Hi @XixiTalken , I am also applying for datacap but still waiting for review. I would like to discuss with you how to proceed and how to promote the development of real data. If possible, please leave your email or contact me: mr.clark.yin@gmail.com

**Comment by XixiTalken** [comment]
Hi @ClarkYin5566, we'd love to discuss about the process. We're also trying to proceed the DataCap allocation now. Contact me xixi@talken.io.

**Comment by IreneYoung** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaxlhbc3dw77w4pmka265abbrlcjorlblh5ylxuxmj7kusrpq7j7y 
#### Address 
> f1smkg3penf4nrooa6tmzxphfrlt5c567gfa5azka
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1d4gmpqz3execjj2wvrxuuhvbms5mzh7t7yqrviq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaxlhbc3dw77w4pmka265abbrlcjorlblh5ylxuxmj7kusrpq7j7y

**Comment by psh0691** [comment]
I'm Sounghwan Park, a notary in Korea.
I have a question before approval.

1. In the application, you said you would store data in Korea, Singapore, and China, but all four storage providers selected are Canada. Is there a reason?
2. You applied for 5 PiB, how much data do you have now? 
 - There are many difficulties in transferring 5PiB online, where is the data retention location?

**Comment by BigD-Exchange** [comment]
@XixiTalken Hi! Great to see you have gotten approval for DataCap. If you are looking for storage providers to store these data, please visit #bigdata-exchange on Filecoin Slack or reply here.

**Comment by IreneYoung** [comment]
@psh0691 We made storage deals with those Canadian SPs which were recommended by community. It’s not easy to find the right SPs, as you know. If you have Korean SPs resources, please help us. 
At present, the small amount of data is transmitted online. We also support offline transfer If there is any SP in South Korea or other Asian areas. 
Thanks for your help!

**Comment by XixiTalken** [comment]
@BigD-Exchange We have entered the #bigdata-exchange channel in Filecoin Slack, and will look for partners in the channel if needed in the future. Thanks!

**Comment by psh0691** [comment]
> @psh0691저도 공증인이며 이제 Talken이 데이터를 Filecoin에 등록하는 것을 돕습니다. 우리는 커뮤니티에서 추천한 캐나다 SP와 스토리지 거래를 했습니다. 아시다시피 SP를 찾는 것은 쉽지 않습니다. 한국 SP 리소스가 있으면 알려주십시오. 현재 소량의 데이터가 온라인으로 전송됩니다. 한국이나 다른 아시아 지역에 SP가 있다면 Talken도 오프라인 전송을 지원해야 한다고 생각합니다. 당신의 도움을 주셔서 감사합니다!

Thank you.
I will also support and cooperate as much as I can.

**Comment by IreneYoung** [comment]
@psh0691  that would be really great!

**Comment by filplus-checker** [comment]
## DataCap and CID Checker Report[^1]
 - Organization: `Talken.io`
 - Client: `f1smkg3penf4nrooa6tmzxphfrlt5c567gfa5azka`
### Storage Provider Distribution
The below table shows the distribution of storage providers that have stored data for this client.

If this is the first time a provider takes verified deal, it will be marked as `new`.

For most of the datacap application, below restrictions should apply.
 - Storage provider should not exceed 25% of total datacap.
 - Storage provider should not be storing duplicate data for more than 20%.
 - Storage provider should have published its public IP address.
 - All storage providers should be located in different regions.

⚠️ [f01641612](https://filfox.info/en/address/f01641612) has sealed 39.34% of total datacap.

⚠️ [f01602479](https://filfox.info/en/address/f01602479) has sealed 30.20% of total datacap.

⚠️ 40.48% of total deal sealed by [f01666984](https://filfox.info/en/address/f01666984) are duplicate data.

⚠️ 45.34% of total deal sealed by [f01833576](https://filfox.info/en/address/f01833576) are duplicate data.

| Provider                                                    |              Location | Total Deals Sealed | Percentage | Unique Data | Duplicate Deals |
| :---------------------------------------------------------- | --------------------: | -----------------: | ---------: | ----------: | --------------: |
| [f01641612](https://filfox.info/en/address/f01641612)       |  Montréal, Quebec, CA |          18.69 TiB |     39.34% |   18.63 TiB |           0.33% |
| [f01602479](https://filfox.info/en/address/f01602479)       | Longueuil, Quebec, CA |          14.34 TiB |     30.20% |   14.34 TiB |           0.00% |
| [f01666984](https://filfox.info/en/address/f01666984)       |    Dorval, Quebec, CA |           6.56 TiB |     13.82% |    3.91 TiB |          40.48% |
| [f01833576](https://filfox.info/en/address/f01833576)`new`  |  Montréal, Quebec, CA |           5.03 TiB |     10.59% |    2.75 TiB |          45.34% |
| [f01606849](https://filfox.info/en/address/f01606849)       |  Montréal, Quebec, CA |           2.88 TiB |      6.05% |    2.88 TiB |           0.00% |

![Provider Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/163/1671093361169.png)
### Deal Data Replication
The below table shows how each many unique data are replicated across storage providers.
- No more than 25% of unique data are stored with less than 4 providers.

⚠️ 78.55% of deals are for data replicated across less than 4 storage providers.

| Unique Data Size | Total Deals Made | Number of Providers | Deal Percentage |
| ---------------: | ---------------: | ------------------: | --------------: |
|         1.88 TiB |         1.88 TiB |                   1 |           3.95% |
|        11.50 TiB |        23.00 TiB |                   2 |          48.42% |
|         3.44 TiB |        12.44 TiB |                   3 |          26.18% |
|         1.75 TiB |         9.81 TiB |                   4 |          20.66% |
|        64.00 GiB |       384.00 GiB |                   5 |           0.79% |

![Replication Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/163/1671093361872.png)
### Deal Data Shared with other Clients
The below table shows how many unique data are shared with other clients.
Usually different applications owns different data and should not resolve to the same CID.

✔️ No CID sharing has been observed.

[^1]: To manually trigger this report, add a comment with text `checker:manualTrigger`

**Comment by mmfxea** [comment]
checker:manualTrigger

**Comment by futuremaster777** [comment]
checker:manualTrigger

**Comment by cryptowhizzard** [comment]
I am not sure what the status is now of this application. 

@XixiTalken can you enlighten us how this went between august and now and what the future plan is?
