### ISSUE TITLE
[DataCap Application] Sentinel-1 SLC dataset for Germany I

### ISSUE THREAD

**Issue by CarelScholtens** [filecoin-project/filecoin-plus-large-datasets#1630]
### Data Owner Name

LiveEO

### Data Owner Country/Region

Germany

### Data Owner Industry

Environment

### Website

https://www.live-eo.com/

### Social Media

```text
Twitter---https://twitter.com/liveeo_space
Linkedin---https://www.linkedin.com/company/liveeo/
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

500TiB

### On-chain address for first allocation

f1jvyqf7n3eywv7en3fcczsnfodiz6cn6p27hupca

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
LiveEO was born from the idea that satellite data, a vast and almost untapped resource, has enormous potential to transform our lives, and the world around us, for the better. Sven and Daniel, two NewSpace enthusiasts with a keen interest in A.I., founded LiveEO in 2018 with a simple vision: to apply this incredible trove of data about our planet to improve the way we do business, and live our lives.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
The Sentinel1 Single Look Complex (SLC) unzipped dataset contains Synthetic Aperture Radar (SAR) data from the European Space Agency’s Sentinel-1 mission.SAR imagery gets recorded regardless of weather conditions and daylight, which makes it ideally suited for monitoring land-use changes, surface deformations, land applications, oil spills, sea-ice, natural hazards, and for emergency response. This dataset is retrieved from Alaska Satellite Facility (ASF) and consists of all Sentinel1-SLC imagery from the beginning (2014) to present.
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### How do you plan to prepare the dataset

IPFS, lotus, singularity, graphsplit

### Please share a sample of the data

```text
https://registry.opendata.aws/sentinel1-slc/
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

1.5 to 2 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, South America, Europe, Australia (continent)

### How will you be distributing your data to storage providers

HTTP or FTP server, IPFS, Shipping hard drives, Lotus built-in data transfer

### How do you plan to choose storage providers

Slack, Big data exchange

### How do you plan to make deals to your storage providers

Boost client, Lotus client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Looking at your application i have some questions:
As you are brand new on Github and have no history of past applications it seems to me that applying for 5PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?

Can you show us visible proof of the size of your data and the storage systems you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230337462961356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!

**Comment by stcouldlisa** [comment]
1. 10PiB seems a lot, how do you prove that you have 10PiB of data.

2. Can you use the domain name mailbox to send an email to prove your identity?

**Comment by Sunnyiscoming** [comment]
Could you send an email to filplus-app-review@fil.org with your official domain in order to confirm your identity? Email name should includes the issue id #1630.

**Comment by herrehesse** [comment]
@CarelScholtens Greetings, it appears that this dataset have been previously stored multiple times and is currently present on the chain (slingshot 2.6/2.7/2.8/restore). Therefore, I'm uncertain why it would qualify for a datacap request once more.

I'm not in favor of creating numerous unnecessary copies of identical sets, as it wouldn't serve any practical purpose and would waste storage capacity.

**Comment by CarelScholtens** [comment]
@stcouldlisa What I want to say is that the dataset is about 1.1PiB, and I plan to store 10 duplicates in total. That's the reason why I apply for the amount. @Sunnyiscoming I'm an individual sp and I come to apply datacap for this meaningful dataset. @herrehesse Sure this appears in slingshot? I don't know much about it actually. I chose to store this dataset because I found it truly useful and I managed to download it. I just want to do some contribution to filecoin.

**Comment by cryptowhizzard** [comment]
Hi @CarelScholtens 

When can you fill in the questionaire?

**Comment by Sunnyiscoming** [comment]
Can you provide more detailed informations about SPs you will cooperate with?

**Comment by CarelScholtens** [comment]
@Sunnyiscoming Okay. I can give it after the nodes be created. The SPs are still in the final round of finalization. Thanks
@cryptowhizzard Hi, I've already reply to Fil+ officer.

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 5PiB

**Expected weekly DataCap usage rate**
> 500TiB

**Client address**
>f1jvyqf7n3eywv7en3fcczsnfodiz6cn6p27hupca

**Comment by 1475Notary** [comment]
> @stcouldlisa What I want to say is that the dataset is about 1.1PiB, and I plan to store 10 duplicates in total. That's the reason why I apply for the amount. @Sunnyiscoming I'm an individual sp and I come to apply datacap for this meaningful dataset. @herrehesse Sure this appears in slingshot? I don't know much about it actually. I chose to store this dataset because I found it truly useful and I managed to download it. I just want to do some contribution to filecoin.

Thank you for your clarification. Please make the deals according to the rule of fil+.

**Comment by 1475Notary** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebaxg2k5akcsuckyaktmikpy5bpo3xkml6cv2xpsflgnhrawuev4y 
#### Address 
> f1jvyqf7n3eywv7en3fcczsnfodiz6cn6p27hupca
#### Datacap Allocated
> 250.00TiB
#### Signer Address
> f1ofq4mngy7ggcp755pfquq2gphjjnlydolf6awtq
#### Id
> be166733-b3a4-4bab-8b5a-1e0b544d2504
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebaxg2k5akcsuckyaktmikpy5bpo3xkml6cv2xpsflgnhrawuev4y

**Comment by cryptowhizzard** [comment]
Proposed without KYC. Tagging.

**Comment by TrueBlood1** [comment]
checker:manualTrigger

**Comment by MarshLin88** [comment]
checker:manualTrigger

**Comment by Aaronn85** [comment]
checker:manualTrigger

**Comment by CarelScholtens** [comment]
@simonkim0515 Can you please reopen my application? I'm going to send more data to SPs. In order for the next step of the process to work properly, please help us reopen the application first. Thank you very much!

**Comment by Sunnyiscoming** [comment]
- Best practice for storing large datasets includes ideally, storing it in 3 or more regions, with 4 or more storage provider operators or owners.You should list Miner ID, Business Entity, Location of sps you will cooperate with.

**Comment by Filplus-govteam** [comment]
Hello @CarelScholtens  per the new guidelines https://github.com/filecoin-project/notary-governance/issues/922 for Open Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

This information will be reviewed by Fil+ Governance team to confirm validity toward the Fil+ guideline of a distributed storage plan and SPs posted in the comments here. Let us know if you have any questions.

**Comment by CarelScholtens** [comment]
@Filplus-govteam Ok. I've finished it.

**Comment by Sunnyiscoming** [comment]
f02169597 CN
f02259811 CN
f01392600 CN
f01860256 HK
f01106276 CN

**Comment by cryptowhizzard** [comment]
<img width="555" alt="Scherm­afbeelding 2023-08-27 om 20 40 04" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/36404435/9ac2a7f1-b2bd-43ec-aadd-aabcb1768ad4">

Why are you storing garbage data @CarelScholtens ?

https://www.datasetcreators.com/downloadedcarfiles/httpretrievals/1630-f02044678-f02244750-46888968-baga6ea4seaqd2npt4xv3krni7fysdxri5sart5wujnjk74klxbowcbzifiraebi

DealID 46888968

Visible with command hexdump -C 1630-f02044678-f02244750-46888968-baga6ea4seaqd2npt4xv3krni7fysdxri5sart5wujnjk74klxbowcbzifiraebi | more

<img width="668" alt="Scherm­afbeelding 2023-08-27 om 20 42 09" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/36404435/8a0381b0-e6fc-478b-bccd-e3583ecdae98">

**Comment by raghavrmadya** [comment]
Client is requested to address the [dispute](https://www.notion.so/filecoin/Applicant-storing-garbage-data-fe27267d5ba049cfb556dc5909bc5dd0?pvs=4) at their earliest convenience to prevent closure and removal of DC

**Comment by CarelScholtens** [comment]
After confirmed with SPs, I can ensure that this is not the data what we stored or what I transfer to SPs. I think it is a groundless allegations and it should be removed.

Evidence: This is the download result which I use @cryptowhizzard 's command to do. Different with his.

![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/122512300/541ebf3e-3684-4f0b-975c-3c15adea9d33)

**Comment by cryptowhizzard** [comment]
Dear CarelScholtens,

As notary I am doing due diligence on your LDN. I could not get retrieval to work. Can you please upload the car file of CID baga6ea4seaqd2npt4xv3krni7fysdxri5sart5wujnjk74klxbowcbzifiraebi ?

You can use our upload system at http://send.datasetcreators.com. Please select 7 days for the system to keep the file and post the link you received here so I (and other notaries) can download your content.

**Comment by CarelScholtens** [comment]
We support retrieval. If you want to do some check, please download by yourself. I don't want to do something repetitive and pointless.

**Comment by CarelScholtens** [comment]
Yes.

**Comment by CarelScholtens** [comment]
Yes.
