### ISSUE TITLE
[DataCap Application] Sentinel-1 SLC dataset for Germany II

### ISSUE THREAD

**Issue by CarelScholtens** [filecoin-project/filecoin-plus-large-datasets#1631]
### Data Owner Name

LiveEO

### Data Owner Country/Region

Germany

### Data Owner Industry

Environment

### Website

https://www.live-eo.com/

### Social Media

```text
Twitter---https://twitter.com/liveeo_space
Linkedin---https://www.linkedin.com/company/liveeo/
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

500TiB

### On-chain address for first allocation

f1mifv4bn6tsg6js7l4742nccbo5pdtdpgm2p6d5a

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
LiveEO was born from the idea that satellite data, a vast and almost untapped resource, has enormous potential to transform our lives, and the world around us, for the better. Sven and Daniel, two NewSpace enthusiasts with a keen interest in A.I., founded LiveEO in 2018 with a simple vision: to apply this incredible trove of data about our planet to improve the way we do business, and live our lives.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
The Sentinel1 Single Look Complex (SLC) unzipped dataset contains Synthetic Aperture Radar (SAR) data from the European Space Agency’s Sentinel-1 mission.SAR imagery gets recorded regardless of weather conditions and daylight, which makes it ideally suited for monitoring land-use changes, surface deformations, land applications, oil spills, sea-ice, natural hazards, and for emergency response. This dataset is retrieved from Alaska Satellite Facility (ASF) and consists of all Sentinel1-SLC imagery from the beginning (2014) to present.
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### How do you plan to prepare the dataset

IPFS, lotus, singularity, graphsplit

### Please share a sample of the data

```text
https://registry.opendata.aws/sentinel1-slc/
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

1.5 to 2 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, South America, Europe, Australia (continent)

### How will you be distributing your data to storage providers

HTTP or FTP server, IPFS, Shipping hard drives, Lotus built-in data transfer

### How do you plan to choose storage providers

Slack, Big data exchange

### How do you plan to make deals to your storage providers

Boost client, Lotus client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Looking at your application i have some questions:
As you are brand new on Github and have no history of past applications it seems to me that applying for 5PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?

Can you show us visible proof of the size of your data and the storage systems you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230337462961356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!

**Comment by Sunnyiscoming** [comment]
See questions in #1630

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 5PiB

**Expected weekly DataCap usage rate**
> 500TiB

**Client address**
>f1mifv4bn6tsg6js7l4742nccbo5pdtdpgm2p6d5a

**Comment by 1475Notary** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebx5l34wkaii6wjwkkyyu2pzqvmk7pndqloyumod6fmuhm2abhpk6 
#### Address 
> f1mifv4bn6tsg6js7l4742nccbo5pdtdpgm2p6d5a
#### Datacap Allocated
> 250.00TiB
#### Signer Address
> f1ofq4mngy7ggcp755pfquq2gphjjnlydolf6awtq
#### Id
> 05c1876e-bff8-49ed-bef6-6d41f1aaeccf
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebx5l34wkaii6wjwkkyyu2pzqvmk7pndqloyumod6fmuhm2abhpk6

**Comment by cryptowhizzard** [comment]
Proposed without KYC. Tagging.

**Comment by Joss-Hua** [comment]
checker:manualTrigger

**Comment by CarelScholtens** [comment]
Thanks for the tip.

**Comment by cryptowhizzard** [comment]
checker:manualTrigger

**Comment by CarelScholtens** [comment]
Thanks for the tip.

**Comment by Filplus-govteam** [comment]
Hello @CarelScholtens  per the new guidelines https://github.com/filecoin-project/notary-governance/issues/922 for Open Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

This information will be reviewed by Fil+ Governance team to confirm validity toward the Fil+ guideline of a distributed storage plan and SPs posted in the comments here. Let us know if you have any questions.

**Comment by CarelScholtens** [comment]
@Filplus-govteam Ok. I've finished it.

**Comment by cryptowhizzard** [comment]
![Scherm­afbeelding 2023-08-25 om 15 33 00](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/36404435/8d5e58af-f244-4672-95d6-7581b0d7d1e2)

This application should be closed. The data has been sent to one SP and that SP has closed retrievals.

![Scherm­afbeelding 2023-08-25 om 15 34 26](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/36404435/4eb5df9f-bf34-4b95-9652-60cec1aa5699)

**Comment by cryptowhizzard** [comment]
https://github.com/filecoin-project/notary-governance/issues/971

**Comment by CarelScholtens** [comment]
![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/122512300/6e0e79d9-a885-48fe-86fb-1ad2d38fee3f)

We have got a total of 250T DC and successfully distributed 18T to one SP. from the report, we can see that this SP has no problem with the retrieval as below. Of course, we are still looking for more suitable SPs for cooperation.

![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/122512300/8adb7174-5a7e-4807-accc-977eb09dea80)

**Comment by CarelScholtens** [comment]
As we all know, the discussion that DC from the closed applications with low onboarding rate may be removed is still ongoing: 
https://github.com/filecoin-project/notary-governance/issues/967 
We all know this proposal is currently highly controversial and a lot of people are against it.

So why would you feel comfortable being impatient to submit such a proposal at the present time?  @cryptowhizzard 
https://github.com/filecoin-project/notary-governance/issues/971

**Comment by raghavrmadya** [comment]
@CarelScholtens The [dispute](https://www.notion.so/filecoin/No-retrieval-2cf3763ff1e147a38504d6b9b7a1fa9f?pvs=4) is not about your low onboarding rate but about retrievals. You confirmed that in the LDN above. Kindly address this community concern before proceeding. 

Notaries are encouraged to not sign until dispute is resolved.

**Comment by CarelScholtens** [comment]
Hello @raghavrmadya 
>You confirmed that in the LDN above.

As you said, I have confirmed retrieval in the LDN above. I don't think there's any more evidence I need to provide here. No unresolved points here.

**Comment by cryptowhizzard** [comment]
Dear CarelScholtens,

As notary I am doing due diligence on your LDN. I could not get retrieval to work. Can you please upload the car file of CID baga6ea4seaqpm64up5iw3iiti2jy7jdu3bwfzvgomsgkk5iv7tbsar5dr3mnmnq ?

You can use our upload system at http://send.datasetcreators.com. Please select 7 days for the system to keep the file and post the link you received here so I (and other notaries) can download your content.

**Comment by CarelScholtens** [comment]
Yes.

**Comment by CarelScholtens** [comment]
Yes.
