### ISSUE TITLE
[DataCap Application] Pride Group Dubai - HPA

### ISSUE THREAD

**Issue by manojkumardevisetty** [filecoin-project/filecoin-plus-large-datasets#1632]
### Data Owner Name

 Phil Culliton 

### Data Owner Country/Region

United States

### Data Owner Industry

Life Science / Healthcare

### Website

None

### Social Media

```text
https://www.kaggle.com/philculliton
```

### Total amount of DataCap being requested

1PiB

### Weekly allocation of DataCap requested

50TiB

### On-chain address for first allocation

f3wh7ffch5kcmbgwvcp7f5t5nu4ffoq4zrbtupvyrklbizyg3kbjsxeg5p7h34wrm7cucvymwdyw3oonldn6ka

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
We are base din Dubai "pride Group" we are in to storage provider services along with that financial services acts like VC in many projects(involved in gold,petrol,software,crypto, medical 
products, etc)
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
Science and medial records related documents and images
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### How do you plan to prepare the dataset

singularity

### Please share a sample of the data

```text
https://www.kaggle.com/datasets/philculliton/hpa-challenge-2021-extra-train-images
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Daily

### For how long do you plan to keep this dataset stored on Filecoin

1.5 to 2 years

### In which geographies do you plan on making storage deals

Asia other than Greater China, North America

### How will you be distributing your data to storage providers

Lotus built-in data transfer

### How do you plan to choose storage providers

Slack

### How do you plan to make deals to your storage providers

Boost client, Singularity

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
Can you provide more detailed informations about SPs you will cooperate with?
Could you send an email to filplus-app-review@fil.org with your official domain in order to confirm your identity? Email name should includes the issue id #1632.

**Comment by manojkumardevisetty** [comment]
sure ill do send from official mail id

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

As last question i would like you to fill out [this form](https://form.jotform.com/230337462961356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!

**Comment by manojkumardevisetty** [comment]
@

> Dear applicant,
> 
> Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.
> 
> As last question i would like you to fill out [this form](https://form.jotform.com/230337462961356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.
> 
> Thanks!

Form filled thanks

**Comment by manojkumardevisetty** [comment]
> Can you provide more detailed informations about SPs you will cooperate with? Could you send an email to [filplus-app-review@fil.org](mailto:filplus-app-review@fil.org) with your official domain in order to confirm your identity? Email name should includes the issue id #1632.

email id: manoj@prideholding.com

**Comment by manojkumardevisetty** [comment]
yea just sent

**Comment by cryptowhizzard** [comment]
Hi there,

Thanks for sending the KYC. It is well received.
The Sp's included in this application are involved in CID sharing and FIL+ abuse. That is a bit unfortunate.

My (personal) guideline is that i won't sign of on new applications when i see a data preparation plan with at least some SP's with standing reputation.

You indicated that you are a data preparer. Can you give me some insight in what went wrong the last times and how you plan to keep on the right track in the future? I am willing to give you a chance when you are willing to be open on what happened?

![Scherm­afbeelding 2023-02-21 om 13 34 04](https://user-images.githubusercontent.com/36404435/220346234-2d43a61f-492d-465c-bfa4-894f203f37c5.png)

**Comment by manojkumardevisetty** [comment]
Hey I appreciate what you are doing but most of the deals we are getting for estuary and FilSwan it is actively serviced till the data. 
Since where I have asked for one of the sp having a good relation ship where this make you satisfied to work this sp f01959735 North America.
Till the data I haven't done anything wrong to be open. If you see some deals went wrong from yesterday it was Delta deals engine for testing where we have taken even 10% of the deals sent. 

I request you give a change for new application like us, where we make thing better and much better in coming days. I assure that we didn't do anything wrong. Or knowingly

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 1PiB

**Expected weekly DataCap usage rate**
> 50TiB

**Client address**
>f3wh7ffch5kcmbgwvcp7f5t5nu4ffoq4zrbtupvyrklbizyg3kbjsxeg5p7h34wrm7cucvymwdyw3oonldn6ka

**Comment by manojkumardevisetty** [comment]
We are happy to answer the questions if you need more information and get approved

**Comment by cryptowhizzard** [comment]
@Sunnyiscoming 

Applications above #1620 are not in my dashboard to propose / sign. Please kindly check.

**Comment by simonkim0515** [comment]
## Datacap Request Trigger

#### Total DataCap requested 
> 1PiB

#### Expected weekly DataCap usage rate 
> 50TiB 

#### Client address
> f3wh7ffch5kcmbgwvcp7f5t5nu4ffoq4zrbtupvyrklbizyg3kbjsxeg5p7h34wrm7cucvymwdyw3oonldn6ka

**Comment by cryptowhizzard** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedv7fhsv6uaehs4wem65n7iqoovjnnnb64b4mlixqnv7zpbcovts4 
#### Address 
> f3wh7ffch5kcmbgwvcp7f5t5nu4ffoq4zrbtupvyrklbizyg3kbjsxeg5p7h34wrm7cucvymwdyw3oonldn6ka
#### Datacap Allocated
> 25.00TiB
#### Signer Address
> f1krmypm4uoxxf3g7okrwtrahlmpcph3y7rbqqgfa
#### Id
> c107c276-9829-4faa-a0be-4bff86b51cca
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedv7fhsv6uaehs4wem65n7iqoovjnnnb64b4mlixqnv7zpbcovts4

**Comment by daniel2022nnn** [comment]
just curious how it passed KYC and CID sharing issue as above.
I even do not understand what @manojkumardevisetty  was talking about since it seems to be all translation with slight errors here. 

@cryptowhizzard can you explain more to the community why you proposed?
CID sharing issue can be fixed only by saying to give them one more chance without any detail?

**Comment by cryptowhizzard** [comment]
> just curious how it passed KYC and CID sharing issue as above. I even do not understand what @manojkumardevisetty was talking about since it seems to be all translation with slight errors here.
> 
> @cryptowhizzard can you explain more to the community why you proposed? CID sharing issue can be fixed only by saying to give them one more chance without any detail?

Sure.

First the client came with SP's who were involved in CID sharing. The client indicated to move to FilSwan with other SP's and f01959735. From there the risk got lowered and i figured since i have KYC done that the risk was acceptable for 25 TB.

**Comment by manojkumardevisetty** [comment]
Thanks for allowing me

**Comment by GaryGJG** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecmbptsoamivmutqk6dn6ky7hz7ne6wswcq5a5qba3d67he3s2i6q 
#### Address 
> f3wh7ffch5kcmbgwvcp7f5t5nu4ffoq4zrbtupvyrklbizyg3kbjsxeg5p7h34wrm7cucvymwdyw3oonldn6ka
#### Datacap Allocated
> 25.00TiB
#### Signer Address
> f1zffqhxwq2rrg7rtot6lmkl6hb2xyrrseawprzsq
#### Id
> c107c276-9829-4faa-a0be-4bff86b51cca
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecmbptsoamivmutqk6dn6ky7hz7ne6wswcq5a5qba3d67he3s2i6q
