### ISSUE TITLE
[DataCap Application] DongShuXiSuan - COVID19-OPEN DATASET

### ISSUE THREAD

**Issue by dsxsfz** [filecoin-project/filecoin-plus-large-datasets#1633]
### Data Owner Name

Fujian DongShuXiSuan Technology Co., Ltd.

### Data Owner Country/Region

China

### Data Owner Industry

Life Science / Healthcare

### Website

www.ppdx.cn

### Social Media

```text
www.ppdx.cn
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

700TiB

### On-chain address for first allocation

f1q24kye52nhw43hsnqwc7uduqy3x73bcp2hmbala

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Our company is a company specializing in providing big data and AI solutions. Our main business includes: data storage, big data analysis and calculation, AI model training.
After the start of COVID19, we spent a lot of time on this side of big data research, hoping to help patients through research.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
During R&D and testing, we have downloaded a large number of public data sets. We use these data for daily research and development and AI data training. We are very grateful for the great value these data bring to the company's development. We are concerned about the rapid development of the filecoin project, and technologies such as distributed storage, fvm, and data retrieval are also of great interest to the company. So we decided to store these obtained public datasets and the publicly available datasets generated by the company to the filecoin network through the fil-plus project.
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### How do you plan to prepare the dataset

singularity, graphsplit

### Please share a sample of the data

```text
https://registry.opendata.aws/foldingathome-covid19/
https://registry.opendata.aws/talend-covid19/
https://registry.opendata.aws/dnastack-covid-19-sra-data/
https://www.kaggle.com/datasets/mathurinache/mosmeddata-chest-ct-scans-with-covid19
https://www.kaggle.com/datasets/andyczhao/covidx-cxr2
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Monthly

### For how long do you plan to keep this dataset stored on Filecoin

1.5 to 2 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, South America

### How will you be distributing your data to storage providers

HTTP or FTP server, Shipping hard drives

### How do you plan to choose storage providers

Slack, Partners

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by dsxsfz** [comment]
We have applied before, but RG asked us to open a seperate application, and then said the second time that we were rejected because we did not disclose the first application. Now disclose this information here：https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/996 https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1147

**Comment by herrehesse** [comment]
@dsxsfz Greetings, it appears that several of these datasets have been previously stored multiple times and are currently present on the chain (_slingshot 2.6/2.7/2.8/restore_). Therefore, I'm uncertain why they would qualify for a datacap request once more.

I'm not in favor of creating numerous unnecessary copies of identical sets, as it wouldn't serve any practical purpose and would waste storage capacity.

**Comment by Sunnyiscoming** [comment]
@dsxsfz  Can you email filplus-app-review@fil.org using your official domain name to confirm your identity? Email name should contain Issue ID #1633.

**Comment by herrehesse** [comment]
Dear Filecoin+ Github applicant,

We have noticed that some of you are submitting merged datacap requests for datasets that are already (partly) on the chain. While we appreciate your enthusiasm to contribute to the Filecoin network, we want to remind you that this behaviour may not be beneficial to the network in the long run. In fact, this behaviour has been questioned and discussed in issue #832 on the Filecoin notary-governance Github repository.

We encourage you to review the discussions in issue #832. It's important to ensure that your datacap requests are valid, necessary, and add value to the network. By doing so, you can help to maintain the integrity and sustainability of the Filecoin network.

You can find the link to issue #832 here: [filecoin-project/notary-governance#832](https://github.com/filecoin-project/notary-governance/issues/832)

Thank you for your understanding and cooperation.

**Comment by Sunnyiscoming** [comment]
Any update here?

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 5PiB

**Expected weekly DataCap usage rate**
> 700TiB

**Client address**
>f1q24kye52nhw43hsnqwc7uduqy3x73bcp2hmbala

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 5PiB

**Expected weekly DataCap usage rate**
> 700TiB

**Client address**
>f1q24kye52nhw43hsnqwc7uduqy3x73bcp2hmbala

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

As last question i would like you to fill out [this form](https://form.jotform.com/230337462961356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!

**Comment by dsxsfz** [comment]
> Dear applicant,
> 
> Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.
> 
> As last question i would like you to fill out [this form](https://form.jotform.com/230337462961356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.
> 
> Thanks!

@cryptowhizzard OK, we have completed the form
