### ISSUE TITLE
[DataCap Application] HIRLAM Weather Model

### ISSUE THREAD

**Issue by Bobonl** [filecoin-project/filecoin-plus-large-datasets#1634]
### Data Owner Name

Finnish Meteorological Institute

### Data Owner Country/Region

Finland

### Data Owner Industry

Environment

### Website

https://en.ilmatieteenlaitos.fi/

### Social Media

```text
T: https://twitter.com/meteorologit
Ins: https://www.instagram.com/ilmatieteenlaitos/
F: https://www.facebook.com/fmibeta/
Y: https://www.youtube.com/user/ilmatieteenlaitos
L: https://www.linkedin.com/company/finnish-meteorological-institute
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

500TiB

### On-chain address for first allocation

f1ugrcmyl55wm67t4fd53yhv3tbbfb5pnem6cem5a

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
The Finnish Meteorological Institute makes observations and research on the atmosphere, the near space and the seas. It also provides services on weather, sea, air quality, climate and near space for the needs of public safety, business life and citizens. The Finnish Meteorological Institute is an administrative branch of the Ministry of Transport and Communications.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
HIRLAM (High Resolution Limited Area Model) is an operational synoptic and mesoscale weather prediction model managed by the Finnish Meteorological Institute.
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### How do you plan to prepare the dataset

IPFS, lotus

### Please share a sample of the data

```text
https://registry.opendata.aws/hirlam/
s3://fmi-opendata-rcrhirlam-surface-grib/2017/04/07/06/numerical-hirlam74-forecast-LowCloudCover-20170407T060000Z.grb2.658B4BD6
s3://fmi-opendata-rcrhirlam-surface-grib/2017/04/07/12/numerical-hirlam74-forecast-LowCloudCover-20170407T120000Z.grb2.E45B2AF8
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

1 to 1.5 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, South America, Europe

### How will you be distributing your data to storage providers

HTTP or FTP server, Shipping hard drives

### How do you plan to choose storage providers

Slack, Big data exchange

### How do you plan to make deals to your storage providers

Lotus client, I don't know yet

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Looking at your application i have some questions:
As you are brand new on Github and have no history of past applications it seems to me that applying for 5PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?

Can you show us visible proof of the size of your data and the storage systems you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230337462961356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!

**Comment by Sunnyiscoming** [comment]
Can you share a brief history of your organization and sps you will cooperate with?

**Comment by Bobonl** [comment]
@cryptowhizzard Hello. I've read your form. But for privacy reasons, I do not want to share my personal information. 
@Sunnyiscoming Hello, I plan to contact 4 SPs at the first step. It is in process and I'm waiting for the final result.

**Comment by TrueWarriors8** [comment]
That's no problem at all. Metawave or Bytebase can sign your application for a few Fil per TiB. Just send them a message on Slack and it will be settled in no time.

**Comment by Sunnyiscoming** [comment]
Can you introduce your organization? Look forward the list of Sps you will cooperate with.

**Comment by Bobonl** [comment]
@Sunnyiscoming Ok! And we are a team for data preparing, not an organization.

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 5PiB

**Expected weekly DataCap usage rate**
> 500TiB

**Client address**
>f1ugrcmyl55wm67t4fd53yhv3tbbfb5pnem6cem5a

**Comment by Aifabot-Cloud** [comment]
Please find more good SPs ASAP. Looking forward to the results of the first CID report.

**Comment by Aifabot-Cloud** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacea7uxvchhcywp32dkbz4is2m3pgi236tcl2wu6mjwmmuz2jsyawjc 
#### Address 
> f1ugrcmyl55wm67t4fd53yhv3tbbfb5pnem6cem5a
#### Datacap Allocated
> 250.00TiB
#### Signer Address
> f174fg3bqbln3zjnkxtyf6s54txqkr7yqkj6cig7y
#### Id
> e7100dbf-4cc1-426f-8652-7cdf99336ae2
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacea7uxvchhcywp32dkbz4is2m3pgi236tcl2wu6mjwmmuz2jsyawjc

**Comment by TakiChain** [comment]
DP is a hard work. Many people have tried before, but it is difficult to persist. Hope you can keep doing it under the community rules.

**Comment by TakiChain** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecv4zj4bwz4e567exinibudbivazigespqa5tawkmgkqsg43cyioq 
#### Address 
> f1ugrcmyl55wm67t4fd53yhv3tbbfb5pnem6cem5a
#### Datacap Allocated
> 250.00TiB
#### Signer Address
> f15impf3j2zcaex4lhyxndxswuuhv24vzstuqtxsi
#### Id
> e7100dbf-4cc1-426f-8652-7cdf99336ae2
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecv4zj4bwz4e567exinibudbivazigespqa5tawkmgkqsg43cyioq

**Comment by BobbyChoii** [comment]
In light of the applicant's long history of engagement and response record, this is the kind of consistent DD response attitude that file plus requires. Thank you for integrating more trustworthy data into the network and please continue to follow fileplus' guidelines.

**Comment by Casey-PG** [comment]
> @filplus-checker-app I have contacted sp about this problem. They said that they‘ve confused the data. I‘ve already asked them not to have a similar problem again.

I can support this round and will check your following updates.

**Comment by Casey-PG** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacececwvzmi4ac3vkxkaaau2hmcpqbohoo5jg7gtwotxjgrtdnm5en2 
#### Address 
> f1ugrcmyl55wm67t4fd53yhv3tbbfb5pnem6cem5a
#### Datacap Allocated
> 500.00TiB
#### Signer Address
> f1d4yb3wags3mtddzesxoo63jv7dmlec3bq4yteni
#### Id
> fcb202f9-fa69-48d3-a52d-49ed1b22412a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacececwvzmi4ac3vkxkaaau2hmcpqbohoo5jg7gtwotxjgrtdnm5en2

**Comment by Meibuy** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacea4mwuhbb7imob3ll7wevmythwfosje3jibt4ejoyyeq7zcvkutq4 
#### Address 
> f1ugrcmyl55wm67t4fd53yhv3tbbfb5pnem6cem5a
#### Datacap Allocated
> 500.00TiB
#### Signer Address
> f1bwugfihrmn3iyunzyxst5nttql3dge4khwmurtq
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacea4mwuhbb7imob3ll7wevmythwfosje3jibt4ejoyyeq7zcvkutq4

**Comment by Casey-PG** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb7ra7wslzdusl6g2irptldvxp2gzddjcppbmqmypirpif66oo75g 
#### Address 
> f1ugrcmyl55wm67t4fd53yhv3tbbfb5pnem6cem5a
#### Datacap Allocated
> 1.95PiB
#### Signer Address
> f1d4yb3wags3mtddzesxoo63jv7dmlec3bq4yteni
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb7ra7wslzdusl6g2irptldvxp2gzddjcppbmqmypirpif66oo75g

**Comment by BobbyChoii** [comment]
Open datasets bring great value to the network. Happy to see more of them join Filecoin. Please keep the allocation in line with Filplus guidlines.

**Comment by BobbyChoii** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebyoah62j3bngjyba2b25b5dvlynkxap5zegt6y53nmqy2edtpobm 
#### Address 
> f1ugrcmyl55wm67t4fd53yhv3tbbfb5pnem6cem5a
#### Datacap Allocated
> 1.95PiB
#### Signer Address
> f1irqs2gmctiv3jcdfwuch7oxvf4ixh3k4b2wc24i
#### Id
> 7741b968-3a7a-4afd-b451-d5636e666c9d
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebyoah62j3bngjyba2b25b5dvlynkxap5zegt6y53nmqy2edtpobm

**Comment by Bobonl** [comment]
Yes please.

**Comment by cryptowhizzard** [comment]
Hello,

I see you have been working with SP's who don't provide retrieval ( Against Fil+ Rules ) and / or CID sharing.

Can you clarify?

![Scherm­afbeelding 2023-07-31 om 08 39 00](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/36404435/2e73d454-5b3f-440a-941b-2230be0e1ba8)

**Comment by Bobonl** [comment]
checker:manualTrigger

**Comment by herrehesse** [comment]
@Filplus-govteam @Kevin-FF-USA @raghavrmadya

Application is abusive, and randomly growing with over 7PiB QaP this week. Can we please remove/hold the DC from closed applications asap?

**Comment by cryptowhizzard** [comment]
This client is actively stalling http retrievals and blocked http ranged requests with a reverse proxy to prevent it's data being investigated.

It works as follows:

One set's a bandwidth limit with NGINX on the HTTP retrieval. After a random certain amount the limit is set to zero. This makes the transfer timeout. Because range retrieval is disabled in NGINX one cannot pick up where he left and needs to start all over again. 

Log can be found at http://datasetcreators.com/downloadedcarfiles/logs/1634.log

**Comment by Filplus-govteam** [comment]
Hello @Bobonl per the new guidelines https://github.com/filecoin-project/notary-governance/issues/922 for Open Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

This information will be reviewed by Fil+ Governance team to confirm validity toward the Fil+ guideline of a distributed storage plan and SPs posted in the comments here. Let us know if you have any questions.

**Comment by Bobonl** [comment]
@herrehesse You can't say something that has no basis.
@cryptowhizzard We have contacted with SPs. They don't use NGINX. Maybe it's your fault for not making it work. You can try it again. The speed of download seems slow but it didn't break community rules.

**Comment by cryptowhizzard** [comment]
![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/36404435/9a86e25e-17ed-42a8-9f0f-31774a37bb33)

@Bobonl I provided proof in the log above.
I tested retrievals from all over the globe and have asked multiple sources to try, even people working with PL.

**Comment by Bobonl** [comment]
@cryptowhizzard The log can not show any problem. It may This should be due to your network settings. The SPs didn't against the rules. Why did you put the application into dispute? Is the form so cheap to submit? Please provide proof, not irrelevant logs.

**Comment by Carohere** [comment]
Is there any other clearer abusing evidence of this?  I don't see the relationship between using NGINX and log files.

**Comment by cryptowhizzard** [comment]
@Carohere 

Boost supports range retrievals. This means that when a transfer time-out occurs the transfer can restart where it left off.

Here this is disabled. The only way to do that is with NGINX. When you look at the log you see it restarting again at 0 ....

No-one will be able to download a file here.

**Comment by raghavrmadya** [comment]
Client has not responded to the concern and [dispute](https://www.notion.so/filecoin/No-retrieval-possible-424b231976aa4172ab815d3b76072658?pvs=4) for over 2 weeks. As such, application is being closed and being flagged for DC removal. 

Client is welcome to apply again.

**Comment by Bobonl** [comment]
@raghavrmadya Hello sir, I have answered his questions about retrieval in the past. 

> @herrehesse You can't say something that has no basis. @cryptowhizzard We have contacted with SPs. They don't use NGINX. Maybe it's your fault for not making it work. You can try it again. The speed of download seems slow but it didn't break community rules.


> @cryptowhizzard The log can not show any problem. It may This should be due to your network settings. The SPs didn't against the rules. Why did you put the application into dispute? Is the form so cheap to submit? Please provide proof, not irrelevant logs.


Also, the report can also confirm that we support retrieval.
![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/122778978/a9ac0d42-d491-4580-af31-7a6ac9ddae5b)

Can you reopen my application?
