### ISSUE TITLE
[DataCap Application] DeYun - PrivacyDaos

### ISSUE THREAD

**Issue by privacydaos** [filecoin-project/filecoin-plus-large-datasets#1635]
### Data Owner Name

Deyun Technology

### Data Owner Country/Region

China

### Data Owner Industry

IT & Technology Services

### Website

https://privacydaos.xyz

### Social Media

```text
none.
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

500TiB

### On-chain address for first allocation

f1hp4wduk3engadojmhpp77vjmepjn6brzew3z56q

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Guizhou Deyun Technology Co., Ltd. independently developed PrivacyDaos, an enterprise-level open source privacy computing platform product. The core members are all from well-known companies such as Baidu, Ali, ByteDance, and Huawei.

Deyun Technology's privacy computing products have cooperated in many fields such as finance, operators, government affairs, industrial Internet of Things, and medical care, and have signed strategic cooperation with many well-known companies. It provides data fusion services based on privacy and security for many enterprises and individuals, and has been highly recognized and praised by customers.

PrivacyDaos is a distributed privacy computing platform independently developed by Deyun Technology based on technologies such as multi-party secure computing, federated learning, homomorphic encryption, and trusted computing. The platform covers privacy intersection, joint modeling, joint statistics, anonymous query, data resource management, algorithm container management, heterogeneous platform interconnection, etc., based on self-developed and open privacy computing framework, to create compatible performance for all business scenarios , security, and efficient privacy computing platform.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
PrivacyDaos is a privacy computing platform, and partners can conduct dietary calculations through private node deployment. The platform will generate a large number of desensitization calculation results, model results and other files, these files are generated by the platform's comprehensive calculations, and there is no copyright dispute.
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### How do you plan to prepare the dataset

I don't know yet

### Please share a sample of the data

```text
https://drive.google.com/drive/folders/1vA-1zH_5hBt0ld1-OSwtBmuDKiceYojg?usp=share_link
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Weekly

### For how long do you plan to keep this dataset stored on Filecoin

More than 3 years

### In which geographies do you plan on making storage deals

Greater China

### How will you be distributing your data to storage providers

HTTP or FTP server

### How do you plan to choose storage providers

I don't know yet

### How do you plan to make deals to your storage providers

I don't know yet

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Looking at your application i have some questions:
As you are brand new on Github and have no history of past applications it seems to me that applying for 5PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?

Can you show us visible proof of the size of your data and the storage systems you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230337462961356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!

**Comment by Sunnyiscoming** [comment]
https://whois.whoisxmlapi.com/lookup-report/gz5xj1rARw
Estimated domain age: 387 day(s)
The data samples you provided are difficult to prove that you have 5 PB data. Can you give more materials to prove that?

**Comment by privacydaos** [comment]
> Dear applicant,
> 
> Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.
> 
> Looking at your application i have some questions: As you are brand new on Github and have no history of past applications it seems to me that applying for 5PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?
> 
> Can you show us visible proof of the size of your data and the storage systems you have there?
> 
> As last question i would like you to fill out [this form](https://form.jotform.com/230337462961356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.
> 
> Thanks!

Hello @cryptowhizzard 
This is our first application for DataCap, but in fact, we have just learned about Filecoin, we knowing that Filecoin can safely and cheaply store data, which is very suitable for our storage needs. Regarding the problem of network failure when accessing Github in China, we use private deployment of Gitlab as the code hub management instead of GitHub. In order to apply for the application of Filecoin, we specially registered a GitHub account. We have filled out the KYC form, thank you again for your attention and questions. Considering the growth of data, I hope you can give us reasonable guidance, and we will actively cooperate with the adjustment. We provide some snapshots about our data:
https://drive.google.com/drive/folders/1VfDvppXIwPGhmLpP5ON1LPbHNHGA61ld?usp=share_link

**Comment by privacydaos** [comment]
> We provide some snapshots about our data:
> https://drive.google.com/drive/folders/1VfDvppXIwPGhmLpP5ON1LPbHNHGA61ld?usp=share_link

Hello @Sunnyiscoming.
We provide some snapshots about our data:
https://drive.google.com/drive/folders/1VfDvppXIwPGhmLpP5ON1LPbHNHGA61ld?usp=share_link

**Comment by privacydaos** [comment]
> https://whois.whoisxmlapi.com/lookup-report/gz5xj1rARw Estimated domain age: 387 day(s) The data samples you provided are difficult to prove that you have 5 PB data. Can you give more materials to prove that?

Hello @Sunnyiscoming.
We provide some snapshots about our data:
https://drive.google.com/drive/folders/1VfDvppXIwPGhmLpP5ON1LPbHNHGA61ld?usp=share_link

**Comment by Sunnyiscoming** [comment]
I don't think that the snapshots you provided prove that you have 5 PB data already. Instead, I want to know more about the origination of your data and data types, etc. Hope you can provide more evidence to make me feel good about this dataset.

**Comment by privacydaos** [comment]
> I don't think that the snapshots you provided prove that you have 5 PB data already. Instead, I want to know more about the origination of your data and data types, etc. Hope you can provide more evidence to make me feel good about this dataset.

Hello @Sunnyiscoming .
The snapshot screenshot is only one of the internal NAS data of our company. Currently, our total data contains several hundred TB of original data. Now the company has independently developed an enterprise-level open source privacy computing platform product, and the data will grow and continue to increase.The 5PB maybe not be enough to include the use of duplicates.
The data sources and types you are concerned about have been stated in the description of the application, which mainly include the results of users' privacy calculation in the application and the original data of automatic desensitization.
With filecoin's massive distributed storage. We hope to help our projects continue to get better. Later, we need to prepare for the real data upload of filecoin. If there is no problem with our project, please reply whether our application can be approved. Thanks!

**Comment by Sunnyiscoming** [comment]
Maybe you can provide more data samples to prove the amount of data you already have.
I want to confirm whether the data, the results of users' privacy calculation in the application and the original data of automatic desensitization, you will store is public.

**Comment by cryptowhizzard** [comment]
> Dear applicant,
> 
> Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.
> 
> Looking at your application i have some questions: As you are brand new on Github and have no history of past applications it seems to me that applying for 5PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?
> 
> Can you show us visible proof of the size of your data and the storage systems you have there?
> 
> As last question i would like you to fill out [this form](https://form.jotform.com/230337462961356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.
> 
> Thanks!

Reminder.

**Comment by privacydaos** [comment]
> > Dear applicant,
> > Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.
> > Looking at your application i have some questions: As you are brand new on Github and have no history of past applications it seems to me that applying for 5PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?
> > Can you show us visible proof of the size of your data and the storage systems you have there?
> > As last question i would like you to fill out [this form](https://form.jotform.com/230337462961356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.
> > Thanks!
> 
> Reminder.

We had filled the KYC Form at 02-28-2023 and got the email response.

**Comment by privacydaos** [comment]
> Maybe you can provide more data samples to prove the amount of data you already have. I want to confirm whether the data, the results of users' privacy calculation in the application and the original data of automatic desensitization, you will store is public.

We need to promise whether to allow the data to be disclosed when the customer uploads the data, so only the data that the customer allows and agrees to be disclosed, not all the original data is made public. In addition, we provide some new data samples as requested, please refer to: https://drive.google.com/drive/folders/1OTaGgmlN_6Ti_Qs26NWxwuxiwE16sVn5?usp=share_link

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 5PiB

**Expected weekly DataCap usage rate**
> 500TiB

**Client address**
>f1hp4wduk3engadojmhpp77vjmepjn6brzew3z56q

**Comment by cryptowhizzard** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecxe5n3cy6zukzktso4ep7ttkmvvdz427d6aocp2b7swwslpucepc 
#### Address 
> f1hp4wduk3engadojmhpp77vjmepjn6brzew3z56q
#### Datacap Allocated
> 250.00TiB
#### Signer Address
> f1krmypm4uoxxf3g7okrwtrahlmpcph3y7rbqqgfa
#### Id
> 013ea635-7f5a-4213-9967-454d15d279bb
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecxe5n3cy6zukzktso4ep7ttkmvvdz427d6aocp2b7swwslpucepc

**Comment by TimGuo7** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedkvtrxlw3fsx7kyo4k5szxp3zigppu6d5fajv3dzk4ykhpogbrqq 
#### Address 
> f1hp4wduk3engadojmhpp77vjmepjn6brzew3z56q
#### Datacap Allocated
> 250.00TiB
#### Signer Address
> f1yslbnnqzrjlyuxsmyxfbqcc7xthcavgpripjevi
#### Id
> 013ea635-7f5a-4213-9967-454d15d279bb
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedkvtrxlw3fsx7kyo4k5szxp3zigppu6d5fajv3dzk4ykhpogbrqq
