### ISSUE TITLE
[DataCap Application] Shenzhen Max Overseas Consulting Co., Ltd.

### ISSUE THREAD

**Issue by AAAqukuailian** [filecoin-project/filecoin-plus-large-datasets#1636]
### Data Owner Name

Shenzhen Max Overseas Consulting Co., Ltd.

### Data Owner Country/Region

China

### Data Owner Industry

Education & Training

### Website

https://www.eb3usa.com/

### Social Media

```text
Official website：https://www.eb3usa.com/company/
douyin：https://www.douyin.com/user/MS4wLjABAAAArLBXI-97-OxiLGS7TaJjt1T1FE96toice4TqfDVxjpM
```

### Total amount of DataCap being requested

100TiB

### Weekly allocation of DataCap requested

1PiB

### On-chain address for first allocation

f1s5escnvn66bjaptmuqfvzznlc5yo5umtchgce5a

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Shenzhen Max Going Abroad Consulting Co., Ltd. originated from a well-known immigration law firm in North America.
Gathering global experts with decades of experience in the field of immigration, it is a trustworthy professional brand in the field of immigration, with business in North America, Europe, Oceania, Asia and other overseas places. Since its establishment, it has provided thousands of customers from all over the world with one-stop solutions for children's overseas education, global asset allocation and identity planning. We adhere to the international service concept, based on authority and professionalism, and proceed from the interests of customers, tailor the comprehensive configuration of overseas identity, assets and education for each customer, serve the Chinese elite with heart, and help the world citizens in the new era to live their favorite life Own
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
The storage is mainly to help the flow of people and wealth, so that people all over the world can live the life they yearn for, and live their favorite videos, articles and pictures. With identity planning and comprehensive services, it helps 1,000 customers realize their life dreams every year.
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### How do you plan to prepare the dataset

IPFS, singularity

### Please share a sample of the data

```text
Link：https://pan.baidu.com/s/1vqfnoeTaz918XxtghL5HXg 
Extraction code：d60u
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Sporadic

### For how long do you plan to keep this dataset stored on Filecoin

Permanently

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, Africa, North America, South America, Europe, Australia (continent), Antarctica

### How will you be distributing your data to storage providers

HTTP or FTP server, IPFS

### How do you plan to choose storage providers

Filmine, Big data exchange

### How do you plan to make deals to your storage providers

Boost client, Singularity

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by herrehesse** [comment]
@AAAqukuailian you are storing in Antarctica?

**Comment by TrueWarriors8** [comment]
"The storage is mainly to help the flow of people and wealth, so that people all over the world can live the life they yearn for, and live their favorite videos, articles and pictures. With identity planning and comprehensive services, it helps 1,000 customers realize their life dreams every year."

非常支持這個應用程序。 100%契合FIL+的使命，讓財富只屬於中國精英。這個數據是中國的，你能把整個5PB都存到你自己的礦機上嗎？

**Comment by Sunnyiscoming** [comment]
> The storage is mainly to help the flow of people and wealth, so that people all over the world can live the life they yearn for, and live their favorite videos, articles and pictures. With identity planning and comprehensive services, it helps 1,000 customers realize their life dreams every year.

I still do not know the data type and data source you want to store. Can you give more detailed description about data? Please provide more data samples to prove that you have 5 PB data? How many copies you will store?
Data samples you provided include short videos. Can you provide some materials to prove that these videos are from your organization or authorized to store as public data on Filecoin network.
Could you send an email to filplus-app-review@fil.org with your official domain in order to confirm your identity? Email name should includes the issue id #1636.

**Comment by Sunnyiscoming** [comment]
Any update here?

**Comment by Sunnyiscoming** [comment]
You can reopen it if you want to continue.
