### ISSUE TITLE
[DataCap Application] oxyak

### ISSUE THREAD

**Issue by kylyhorton** [filecoin-project/filecoin-plus-large-datasets#164]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: oxyak
- Website / Social Media: https://www.oxyak.com
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 2PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 200 TiB
- On-chain address for first allocation: f1bmkq2l6zhjk6l236m2qoscoucitzfqlimnboixi

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Oxyak is a technology-oriented service company,our main business is to provide professional software development for enterprise clients to help them complete their digital transformation. 
Our services can be mainly grouped into three main categories.
1、Enterprise digital capacity building
2、Construction of asset-light software services
3、Building intelligent enterprise software services
We have a solid understanding of data and both the dilemmas and opportunities in business operations. In the process of continuous practice, we find the IT solutions that will help businesses to grow sustainably. Taking business at the core and customer experience at the root, we give life to enterprise and intelligence to data.
To date, we have provided services to nearly 500+ local and multinational companies.
In the digital era, digital transformation of enterprises is an inevitable result as well as an important weapon for enterprises to establish differentiated competitiveness.

```

What is the primary source of funding for this project?
```
The main funding for this program comes from the company's R&D funds, and every year we invest in technology development, which is unavoidable in order to maintain a continuous technological lead.
```

What other projects/ecosystem stakeholders is this project associated with?
```
None.
```

## Use-case details

Describe the data being stored onto Filecoin
```
The data being stored is the live e-commerce video from the customer and is analyzed by our system.Then make a backup in the Filecoin network.
```

Where was the data in this dataset sourced from?
```
The data being stored is the live e-commerce video from the customer and is analyzed by our system.Then make a backup in the Filecoin network.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
We have packaged and uploaded a small portion of the video to Github, which can be viewed at the following link
Link：https://github.com/yuntaozhu/Filecoin-Data-Sample
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
On this point, we have confirmed with our client that the data is primarily advertising content for the sale of goods and can be made public, but the ultimate ownership of the data remains unchanged.
```

What is the expected retrieval frequency for this data?
```
May retrieve these data 2 to 3 times a year.

```

For how long do you plan to keep this dataset stored on Filecoin?
```
It will be a permanent archival. 
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
The first choice is still Greater China, both in terms of trust and data transfer costs.
Of course, given the unique situation in China, we may also consider regions other than the mainland, but the feasibility and cost of transferring data across countries through the Filecoin network is not quite clear at this point.
In the short term, we still choose the Greater China.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
We might try to use offline transactions, but in the long term we would like these steps to be done online through the system.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We will examine the miner's overall situation, the area where it is located, the grade of the server room, the performance of the hardware, the technical strength and other dimensions.
```

How will you be distributing deals across storage providers?
```
When we get DataCap,  we would keep the ratio of 1:1 to allocate DataCap and data. 

```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
We will do it by ourselves.
```

**Comment by flyworker** [comment]
Warning: Potential Security Risk Ahead

Firefox detected an issue and did not continue to www.oxyak.com. The website is either misconfigured or your computer clock is set to the wrong time.

It’s likely the website’s certificate is expired, which prevents Firefox from connecting securely. If you visit this site, attackers could try to steal information like your passwords, emails, or credit card details.

What can you do about it?

The issue is most likely with the website, and there is nothing you can do to resolve it. You can notify the website’s administrator about the problem.

Learn more…

**Comment by KwrayFF** [comment]
Hi @kylyhorton 
Sending a friendly follow up.  Do you have additional information or have you addressed the Potential Security Risk associated with the site?

**Comment by kylyhorton** [comment]
This should be the site's certificate expired, this is a site for display, will not cause security problems.

**Comment by galen-mcandrew** [comment]
Looks like website may still need some updating. @kylyhorton 
![Screen Shot 2022-01-03 at 10 21 03 AM](https://user-images.githubusercontent.com/85587348/147965518-645ef9af-0d2a-4280-9b49-0a53f4909ce3.png)

**Comment by dannyob** [comment]
Yep, it's totally down now.

**Comment by dkkapur** [comment]
Closing this application out for now. @kylyhorton please re-open if still relevant.
