### ISSUE TITLE
[DataCap Application] < Chengdu Qingting Precision Health Management Co., Ltd > - <Medical, health, pension, etc.>

### ISSUE THREAD

**Issue by hxcstar** [filecoin-project/filecoin-plus-large-datasets#1645]
### Data Owner Name

Chengdu Qingting Precision Health Management Co., Ltd 

### Data Owner Country/Region

China

### Data Owner Industry

Life Science / Healthcare

### Website

http://qingtingjk.com/

### Social Media

```text
email: zhaoxinghai@qingtingjk.com
```

### Total amount of DataCap being requested

3PiB

### Weekly allocation of DataCap requested

100TiB

### On-chain address for first allocation

f1bh7mz3awixqm3hx4hotp2qvs7xo54lacougghli

### Custom multisig

- [x] Use Custom Multisig

### Share a brief history of your project and organization

```text
Chengdu Qingting Precision Health Management Co., Ltd. (hereinafter referred to as "Qingting Health") is jointly established by Sino-American Xaar Biotechnology (Guangdong) Co., Ltd., Zhuhai Hengqin Ruiherui Financial Leasing Co., Ltd., Chengdu Huarinke Biotechnology Co., Ltd. and other health enterprises. Its group company has 23 years of precipitation in the precision medicine industry, with 3 cell laboratories, 6 regional treatment centers, and more than 50 medical, health, pension and other institutions in China, and its business involves all over the country; The core technology system is the cutting-edge life science system at home and abroad, focusing on cell therapy, gene therapy and microecological therapy; At present, it has 108 patents, and the expert team involves a number of related fields, and has more than 20 research projects in cooperative institutions.


In 2019, Qingting Health began to get involved in the fields of health real estate and rural revitalization, and successively cooperated with Greenland Group and Longji Group to build two projects in Chengdu: Qingting International Precision Wellness Center and Qingting Wuxiang Precision Medical Hotel. The project integrates regenerative medicine, functional medicine, energy medicine, natural medicine, traditional Chinese medicine, Taoist medicine, gongfa and other technical systems, and is currently a sample project of medical tourism, health care, ecological healing, pastoral healing, healing hotel, and rural revitalization in southwest China.
```

### Is this project associated with other projects/ecosystem stakeholders?

Yes

### Describe the data being stored onto Filecoin

```text
Our business development will involve the use of a large number of data sets, which are mainly used for the storage of medical, health, and elderly care data. The data includes: video, image, audio, text, etc.
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### How do you plan to prepare the dataset

I don't know yet

### Please share a sample of the data

```text
http://qingtingjk.com/?about_18/
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Daily

### For how long do you plan to keep this dataset stored on Filecoin

2 to 3 years

### In which geographies do you plan on making storage deals

Greater China

### How will you be distributing your data to storage providers

Shipping hard drives

### How do you plan to choose storage providers

Slack, Partners

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
Any update here?

**Comment by Sunnyiscoming** [comment]
Close for no reply.
