### ISSUE TITLE
[DataCap Application] BotSmart  - Public Opinion Analyzing

### ISSUE THREAD

**Issue by felixeager** [filecoin-project/filecoin-plus-large-datasets#1646]
### Data Owner Name

BotSmart

### Data Owner Country/Region

China

### Data Owner Industry

IT & Technology Services

### Website

http://yuqing.botsmart.cn/

### Social Media

```text
http://yuqing.botsmart.cn/
```

### Total amount of DataCap being requested

3PiB

### Weekly allocation of DataCap requested

50TiB

### On-chain address for first allocation

f12obur3kvse4c6allrsenuv22heumiri6bd3tp7i

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Botsmart Company integrates the powerful functions of public opinion monitoring, analysis, early warning and reporting, and provides a new generation of cloud service system with deep integration of big data technology and analysis business.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
We store relevant data processed by the company's technology on the Filecoin network:
1.Analyzing sample data.
2.Data analysis intermediate results data.
3.Result data processed by the company, such as data analysis report.
4.Some texts, pictures, and video data of news.
5.System and middleware image backup
```

### Where was the data currently stored in this dataset sourced from

Other

### If you answered "Other" in the previous question, enter the details here

```text
From our company and the business that our company conducts.
```

### How do you plan to prepare the dataset

I don't know yet

### Please share a sample of the data

```text
https://drive.google.com/file/d/1FkXvyOrR1-KxOFgT_NjPnWywUaRatMvu/view?usp=share_link
https://drive.google.com/file/d/1if6C1XfTrYTc4zMoZsmc-J3dzumpZde5/view?usp=share_link
https://drive.google.com/file/d/1n7TgAxF9rIGto8JySLh5WbrBMTZe2mOx/view?usp=share_link
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Monthly

### For how long do you plan to keep this dataset stored on Filecoin

1.5 to 2 years

### In which geographies do you plan on making storage deals

Asia other than Greater China

### How will you be distributing your data to storage providers

Shipping hard drives, Lotus built-in data transfer

### How do you plan to choose storage providers

Slack

### How do you plan to make deals to your storage providers

I don't know yet

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by herrehesse** [comment]
@felixeager Could you clarify the reason for exclusively choosing to store data in "Asia, excluding Greater China"? It is not advisable to limit storage to a particular region, as it is recommended to distribute data globally. Utilizing the same bandwidth to send data to storage providers in Europe or the United States, in addition to Asia, would be more beneficial.

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Looking at your application i have some questions:
As you are brand new on Github and have no history of past applications it seems to me that applying for 5PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?

Can you show us visible proof of the size of your data and the storage systems you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230337462961356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!

**Comment by felixeager** [comment]
> @felixeager Could you clarify the reason for exclusively choosing to store data in "Asia, excluding Greater China"? It is not advisable to limit storage to a particular region, as it is recommended to distribute data globally. Utilizing the same bandwidth to send data to storage providers in Europe or the United States, in addition to Asia, would be more beneficial.

sorry, I misunderstood the question and thought only one region could be selected. To correct, i want to store my data as a backup , so here i should choose all geographies.

**Comment by felixeager** [comment]
> Dear applicant,
> 
> Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.
> 
> Looking at your application i have some questions: As you are brand new on Github and have no history of past applications it seems to me that applying for 5PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?
> 
> Can you show us visible proof of the size of your data and the storage systems you have there?
> 
> As last question i would like you to fill out [this form](https://form.jotform.com/230337462961356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.
> 
> Thanks!



> brand new in the Filecoin space

Yes, i am  brand new in the Filecoin space. i will fill out the form and  show visible proof of the size of my data later

**Comment by felixeager** [comment]
> Dear applicant,
> 
> Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.
> 
> Looking at your application i have some questions: As you are brand new on Github and have no history of past applications it seems to me that applying for 5PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?
> 
> Can you show us visible proof of the size of your data and the storage systems you have there?
> 
> As last question i would like you to fill out [this form](https://form.jotform.com/230337462961356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.
> 
> Thanks!

Yes, i am brand new in the Filecoin space. i will fill out the form and show visible proof of the size of my data later

**Comment by cryptowhizzard** [comment]
Thanks! Form is well received. I am waiting for the SP list to sign of.

**Comment by Meibuy** [comment]
@felixeager Thanks for your application. As a part of KYC process, could you introduce yourself and your job in botsmart?
BTW, Can you email to filplus-app-review@fil.org using your official domain name to confirm your identity?

**Comment by Sunnyiscoming** [comment]
Any update here?

**Comment by Sunnyiscoming** [comment]
Any update here?

**Comment by Sunnyiscoming** [comment]
Close for no reply.

**Comment by Sunnyiscoming** [comment]
Close for no reply.
