### ISSUE TITLE
[DataCap Application] Instructional videos and materials

### ISSUE THREAD

**Issue by mingzhonglv** [filecoin-project/filecoin-plus-large-datasets#1647]
### Data Owner Name

Fuzhou MZL Network Technology Co., LTD

### Data Owner Country/Region

China

### Data Owner Industry

Education & Training

### Website

https://www.wangkewang.com/

### Social Media

```text
https://www.wangkewang.com/
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

500TiB

### On-chain address for first allocation

f17kj3z6j6nff7susxtdc6o3cb2eastdnzlfszwua

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Our company was founded in 2019. We have been committed to providing users with rich teaching resources. Resources on the website include: entrepreneurship teaching, sideline creativity, primary and secondary school tutoring videos, skills teaching videos, tutorial PDFS. Through the combination of videos and teaching documents, we hope that most users can quickly master the skills or knowledge they want to learn.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
The data is mainly videos and pdf files on our website. Most of this data is currently stored on local hard drives, with some stored on platforms such as Baidu's web disk. We want to store this data on Filecoin.
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### How do you plan to prepare the dataset

lotus

### Please share a sample of the data

```text
link: https://pan.baidu.com/s/14nzx-syMoTkC8UeOjS-e5Q?pwd=gd3n code: gd3n
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

More than 3 years

### In which geographies do you plan on making storage deals

Greater China

### How will you be distributing your data to storage providers

Shipping hard drives

### How do you plan to choose storage providers

Slack, Big data exchange

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Looking at your application i have some questions:
As you are brand new on Github and have no history of past applications it seems to me that applying for 5PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?

Can you show us visible proof of the size of your data and the storage systems you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230337462961356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!

**Comment by Sunnyiscoming** [comment]
1. The main content of the website is online courses in primary and secondary schools, but the data samples you provided seem to be different. Can you explain the source of these data?
2. Are all your website resources open? https://www.wangkewang.com/mfwk?price_type=1
3. Can you email [filplus-app-review@fil.org](mailto:filplus-app-review@fil.org) using your official domain name to confirm your identity? Email name should contain Issue ID https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1647.

**Comment by Sunnyiscoming** [comment]
Any update here?

**Comment by Sunnyiscoming** [comment]
You can reopen it if you want to continue.

**Comment by mingzhonglv** [comment]
@Sunnyiscoming Sorry for the long delay.How to reopen it .
About the questions above:
1:I have multiple video resource sites if need the same type of video material as in the application.

> 链接：https://pan.baidu.com/s/1bJPqkwgNR6JN_5KWJzA_Wg?pwd=unz9 
提取码：unz9 

> 链接：https://pan.baidu.com/s/1fQYu2eE81SjjpJaW_Qcmlw?pwd=xqh0 
提取码：xqh0 

> 链接：https://pan.baidu.com/s/1h3HnD2vYfvq-T7LQkw2Nsg?pwd=i4bl 
提取码：i4bl 

2.website resources is open.
3.Sure, I will send a message to [filplus-app-review@fil.org](mailto:filplus-app-review@fil.org) to confirm.

**Comment by mingzhonglv** [comment]
@cryptowhizzard ok ,I will finish, but now I am wondering how to reopen it
