### ISSUE TITLE
[DataCap Application]  raid.xyz - raid

### ISSUE THREAD

**Issue by 0xtaosu** [filecoin-project/filecoin-plus-large-datasets#1656]
### Data Owner Name

raid.xyz

### Data Owner Country/Region

United States

### Data Owner Industry

Web3 / Crypto

### Website

https://www.raid.xyz/explore

### Social Media

```text
Twitter: https://twitter.com/raidxyz
```

### Total amount of DataCap being requested

1PiB

### Weekly allocation of DataCap requested

50TiB

### On-chain address for first allocation

f1zqzieiwqkxaaz53bsrqzkakin7g34k23vrz3ryq

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
raid.xyz is A destination to showcase community passion, A place for web3 collectors and artists to connect, A gallery to capture web3 moments.
```

### Is this project associated with other projects/ecosystem stakeholders?

Yes

### If answered yes, what are the other projects/ecosystem stakeholders

```text
Powered by CreatorDAO (@creatordaocc). Since early 2022, the team has been working to help creators to navigate web3, as well as bridging web2 & web3 through activities such as commissions, educations, IRL events.
```

### Describe the data being stored onto Filecoin

```text
The work generate by the web3 artist, such as images, videos, models，animation etc.

Videos and photos of offline events.

Project commercials and posters.
```

### Where was the data currently stored in this dataset sourced from

Other

### If you answered "Other" in the previous question, enter the details here

```text
supabase and S3
```

### How do you plan to prepare the dataset

lotus

### Please share a sample of the data

```text
https://drive.google.com/drive/folders/1eC9Yy9d5WUtDDnj1UcmBGG-wngKtWV1I?usp=share_link
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Sporadic

### For how long do you plan to keep this dataset stored on Filecoin

1.5 to 2 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, Africa, North America, South America, Europe, Australia (continent), Antarctica

### How will you be distributing your data to storage providers

Cloud storage (i.e. S3), HTTP or FTP server, IPFS, Shipping hard drives, Lotus built-in data transfer

### How do you plan to choose storage providers

Slack

### How do you plan to make deals to your storage providers

Boost client, Lotus client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by herrehesse** [comment]
Hello @0xtaosu thanks for your application! Are you planning on storing data in Antarctica? Please let me know which SP's you are planning on storing with, love to help you if you need assistance!

Also, your demo data showed marketing content for Redbull-Racing, I do not believe this is with their consent?

Love to chat!

<img width="1267" alt="Screenshot 2023-02-22 at 13 42 31" src="https://user-images.githubusercontent.com/70132857/220622801-76036c83-fb14-41c5-9182-9dad28e5977f.png">

**Comment by 0xtaosu** [comment]
> Hello @0xtaosu thanks for your application! Are you planning on storing data in Antarctica? Please let me know which SP's you are planning on storing with, love to help you if you need assistance!
> 
> Also, your demo data showed marketing content for Redbull-Racing, I do not believe this is with their consent?
> 
> Love to chat!
> 
> <img alt="Screenshot 2023-02-22 at 13 42 31" width="1267" src="https://user-images.githubusercontent.com/70132857/220622801-76036c83-fb14-41c5-9182-9dad28e5977f.png">

The works of raid.xyz are all created by web3 artists. As a decentralized platform, we have no way of knowing whether the elements used in their works with consent. In addition, as far as I know, Filcoin is also a decentralized storage network. Does the content of each file stored in the fil plus project have to be checked for copyright? What is your checking mechanism?

**Comment by 0xtaosu** [comment]
Dear notary, we are new to filplus, what should be the next step, can you help me? @herrehesse

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 1PiB

**Expected weekly DataCap usage rate**
> 50TiB

**Client address**
>f1zqzieiwqkxaaz53bsrqzkakin7g34k23vrz3ryq

**Comment by 0xtaosu** [comment]
Dear Notaries, can anyone sign for my LDN?

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Looking at your application i have some questions:
As you are brand new on Github and have no history of past applications it seems to me that applying for 1PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?

Can you show us visible proof of the size of your data and the storage systems you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230337462961356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!

**Comment by cryptowhizzard** [comment]
Hi @0xtaosu 

Thanks for submitting KYC. I can sign your LDN when you give us the SP's where you are going to store the data.
Please let me know when you are ready.

**Comment by 0xtaosu** [comment]
Yes, we are applying for Fil+ LDN for the first time, and I have submitted the KYC form. Here is a screenshot of our data stored on Amazon S3:
![image](https://user-images.githubusercontent.com/17952537/223049109-1f67e2cb-2dca-400d-bcdc-9ca6c416c9c7.png)
![image](https://user-images.githubusercontent.com/17952537/223049144-2fa2b837-84e3-4869-8822-fc944b9fc8e8.png)

**Comment by 0xtaosu** [comment]
I had found several SPs who are willing to store our data  , here are their node IDs:
f02047255
f02009668
f02008883
and I want two notaries to sign for this LDN, thank you @cryptowhizzard

**Comment by cryptowhizzard** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebp6fwtwpdw64a5sjx3koacwe4bpsjr62zk6n5usealobtoeowcgu 
#### Address 
> f1zqzieiwqkxaaz53bsrqzkakin7g34k23vrz3ryq
#### Datacap Allocated
> 25.00TiB
#### Signer Address
> f1krmypm4uoxxf3g7okrwtrahlmpcph3y7rbqqgfa
#### Id
> f578a9b0-5ed0-42de-a35d-ad694ff007d2
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebp6fwtwpdw64a5sjx3koacwe4bpsjr62zk6n5usealobtoeowcgu

**Comment by woshidama323** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced2vqbq773exok2wwhgsfs3xdiu3oaq5f3juaoui3xxskssr3jbwk 
#### Address 
> f1zqzieiwqkxaaz53bsrqzkakin7g34k23vrz3ryq
#### Datacap Allocated
> 25.00TiB
#### Signer Address
> f12tk3adljauwnd3hjbigpfxb7b7gdlj63p6afwtq
#### Id
> f578a9b0-5ed0-42de-a35d-ad694ff007d2
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced2vqbq773exok2wwhgsfs3xdiu3oaq5f3juaoui3xxskssr3jbwk

**Comment by GaryGJG** [comment]
checker:manualTrigger

**Comment by GaryGJG** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecsilw5ne2ksmpsx2gglqsizuparfqm2nxyowmb6bzhzlawtltlvy 
#### Address 
> f1zqzieiwqkxaaz53bsrqzkakin7g34k23vrz3ryq
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1zffqhxwq2rrg7rtot6lmkl6hb2xyrrseawprzsq
#### Id
> 44668690-dd09-4560-a4a2-bda7ac79c55c
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecsilw5ne2ksmpsx2gglqsizuparfqm2nxyowmb6bzhzlawtltlvy

**Comment by herrehesse** [comment]
checker:manualTrigger

**Comment by Aaron01230** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebw63uy3bv6w7ob6owkd4ao3b2lqanpxyniync4d4ukfkxv7bleay 
#### Address 
> f1zqzieiwqkxaaz53bsrqzkakin7g34k23vrz3ryq
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1xrnysd4gimg64d4l6qi7ulzwwq22c6vfg6lpw3i
#### Id
> 44668690-dd09-4560-a4a2-bda7ac79c55c
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebw63uy3bv6w7ob6owkd4ao3b2lqanpxyniync4d4ukfkxv7bleay

**Comment by spaceT9** [comment]
checker:manualTrigger

**Comment by spaceT9** [comment]
The history looks good overall, hope you can increase the number of providers and retrieval rate. I will keep eyes on your performance.

**Comment by spaceT9** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecxiosqshpqq3bq5blnkfbf6nggr3nvuudbs4vwcxtrepd25n6xji 
#### Address 
> f1zqzieiwqkxaaz53bsrqzkakin7g34k23vrz3ryq
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1dktm3abgn7wkpepxab4q3eaw24qktizk4esfzyy
#### Id
> 8bddd4c2-c4e8-4906-ae2e-707971d0977c
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecxiosqshpqq3bq5blnkfbf6nggr3nvuudbs4vwcxtrepd25n6xji

**Comment by Patapon0702** [comment]
checker:manualTrigger

**Comment by Patapon0702** [comment]
report looks good. will support this round

**Comment by Patapon0702** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecbdrags7rewuwlrvqoh5veduw5jatvmtih6umu7vfxsgx5clqeew 
#### Address 
> f1zqzieiwqkxaaz53bsrqzkakin7g34k23vrz3ryq
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1ho2liobpznr7llma6xcl7jtififsfvhdnudn4yy
#### Id
> 8bddd4c2-c4e8-4906-ae2e-707971d0977c
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecbdrags7rewuwlrvqoh5veduw5jatvmtih6umu7vfxsgx5clqeew

**Comment by herrehesse** [comment]
![Screenshot 2023-07-21 at 12 03 01](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/70132857/36390f4d-b725-43cc-80e3-4986364e2602)
![Screenshot 2023-07-21 at 12 04 31](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/70132857/f2d0cf52-23e2-42e4-8d93-5f43b2788868)


@Patapon0702 More than 50% of the application has been sealed by the same entity. Nodes are not distributed but use VPN for location spoofing. Why are you claiming "report looks good. will support this round" ?

@Filplus-govteam

**Comment by Patapon0702** [comment]
@herrehesse 
I reviewed your proposal https://github.com/filecoin-project/notary-governance/issues/917. There is still no conclusion formed.

**Comment by fanjingar** [comment]
checker:manualTrigger

**Comment by Aaron01230** [comment]
checker:manualTrigger

**Comment by Aaron01230** [comment]
checker:manualTrigger

**Comment by zcfil** [comment]
checker:manualTrigger

**Comment by zcfil** [comment]
It seems that your data is too centralized.

**Comment by zcfil** [comment]
Please enable retrieval.

**Comment by cryptowhizzard** [comment]
![Scherm­afbeelding 2023-08-31 om 14 32 27](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/36404435/095d04e2-8e87-4e79-b0b3-2c78f17f884d)

Only one of the SP's has graphsync retrieval enabled. The rest is closed. :(
