### ISSUE TITLE
[DataCap Application] Speedium | Dcent - NOAA Joint Polar Satellite System (JPSS) Part 1 - 25

### ISSUE THREAD

**Issue by cryptowhizzard** [filecoin-project/filecoin-plus-large-datasets#1657]
### Data Owner Name

NOAA

### Data Owner Country/Region

United States

### Data Owner Industry

Life Science / Healthcare

### Website

https://www.nesdis.noaa.gov/about/our-offices/joint-polar-satellite-system-jpss-program-office

### Social Media

```text
https://www.nesdis.noaa.gov/about/our-offices/joint-polar-satellite-system-jpss-program-office
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

250TiB

### On-chain address for first allocation

f1fcd6rkacbgdqdtct3zi2q3nsbuxvqf6lyiugyji

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Since its launch, the Filecoin network has become an important player in the decentralised storage space, offering a secure and transparent alternative to traditional data storage solutions.

We as Speedium / DCENT have been engaged with storing real and valuable datasets on the Filecoin network since Slingshot and have been actively developing tools to improve the process. We are always on the lookout for new and useful client data to onboard.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
The Joint Polar Satellite System (JPSS) is the nation’s advanced series of polar-orbiting environmental satellites. Considered the backbone of the global observing system, JPSS satellites circle Earth from pole to pole and cross the equator 14 times daily—providing full global coverage twice a day.
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### How do you plan to prepare the dataset

singularity, others/custom tool

### If you answered "other/custom tool" in the previous question, enter the details here

```text
Inhouse tooling
```

### Please share a sample of the data

```text
https://www.nesdis.noaa.gov/about/our-offices/joint-polar-satellite-system-jpss-program-office
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

Permanently

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, Europe, Australia (continent)

### How will you be distributing your data to storage providers

HTTP or FTP server

### How do you plan to choose storage providers

Slack, Filmine, Big data exchange, Partners

### If you answered "Others" in the previous question, what is the tool or platform you plan to use

```text
Inhouse tooling
```

### If you already have a list of storage providers to work with, fill out their names and provider IDs below

```text
| MinerID | City | Continent | Business/Entity |
| --- | --- | --- | --- |
| `f01944347` | Oregon | USA | Jenny, Dabai |
| `f01952350` | Oregon | USA | Jenny, Dabai |
| `f01972364` | Oregon | USA | Jenny, Dabai |
| `f01972376` | Oregon | USA | Jenny, Dabai |
| `f02000937` | Chengdu | CN | MTY |
| `f01915033` | Chengdu | CN | MTY |
| `f01901765` | Hangzhou | CN | MTY |
| `f01953985` | Shenzhen | CN | MTY |
| `f0120****` | Melbourne | AU | HOLON |
| `f0115****` | Melbourne | AU | HOLON |
| `f01199430` | Heerhugowaard | EU | DCENT |
| `f01786387` | Heerhugowaard | EU | DCENT |
| `f01201327` | Heerhugowaard | EU | DCENT |
| `f01937642` | Heerhugowaard | EU | DCENT |
| `f0198****` | Dallas | USA | GREATERHEAT |
| `f0188****` | Singapore | AS | GREATERHEAT |
| `f01091851` | Omaha | USA | DLTx |
| `f01736668` | Omaha | USA | DLTx |
| `f01820744` | Omaha | USA | DLTx |
| `f0855584` | Omaha | USA | DLTx |
| `f01794610` | Omaha | USA | DLTx |
| `f01838599` | Kansas City | USA | DLTx |
| `f01845552` | Kansas City | USA | DLTx |
| `f01885088` | Hong Kong | AS | Hong Kong Morpho Technology Limited |
| `f01926635` | Hong Kong | AS | Hong Kong Morpho Technology Limited |
| `f01933917` | Hong Kong | AS | Hong Kong Morpho Technology Limited |
| `f01989888` | Hong Kong | AS | Hong Kong Morpho Technology Limited |
```

### How do you plan to make deals to your storage providers

Boost client, Others/custom tool

### If you answered "Others/custom tool" in the previous question, enter the details here

```text
Inhouse tooling
```

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 5PiB

**Expected weekly DataCap usage rate**
> 250TiB

**Client address**
>f1fcd6rkacbgdqdtct3zi2q3nsbuxvqf6lyiugyji

**Comment by caoyoungyoung** [comment]
checker:manualTrigger

**Comment by spaceT9** [comment]
checker:manualTrigger

**Comment by data-programs** [comment]
<img width="32" alt="KYC" Verified src="https://stable.filplus.storage/images/filplus-kyc-verified-badge.png"/>

This user’s identity has been verified through [filplus.storage](https://filplus.storage)
