### ISSUE TITLE
[DataCap Application] Blockchain World (BCW)

### ISSUE THREAD

**Issue by psh0691** [filecoin-project/filecoin-plus-large-datasets#166]
# Large Dataset Notary Application
To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.
## Core Information
- Organization Name: Blockchain World(BCW)
- Website / Social Media: http://bcwnews.com/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 1PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100TiB
- On-chain address for first allocation:  f3simkqmjbjnbpifr3pbtdmcfjz35sisrehkq3gcmwn7ghtussajcw6wiypzzprxdvt5pj6y2dzrxjpvn6tz2q

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details
Share a brief history of your project and organization.
```
-History.
Planning to launch a blockchain-related media in November 2019.
Registration of periodicals in Seoul in October 2020 (서울 아53341)
Registered as an Internet newspaper publisher in October 2020.
Establishing a website for Blockchain World News in November 2020.
Corporate registration in May 2021 (Blockchain World)

-BCW is
It is a medium that focuses on covering and reporting the news of the blockchain industry, which will be at the center of the future core value of the fourth industry.
It contributes to the development of the blockchain industry and leads innovation in related economies and finance.
It is a medium that drives the direction of change of the times by incorporating the value of innovation based on new industries into free and responsible media.
```

What is the primary source of funding for this project?
```
The company undertake this part of the spending.
The main source of income is news subscription and advertising.
```

What other projects/ecosystem stakeholders is this project associated with?
```
We provide various media such as videos, cartoons, photos, and related materials so that news subscribers can make correct judgments.
We plan to distribute IPFS/Filecoin materials suitable for the Web 3.0 era through the IPFS Today channel we are preparing in the future.
```
## Use-case details
Describe the data being stored onto Filecoin
```
We will upload videos, cartoons, photos, events, Lecture on blockchain and planned serials as news that we cover and produce.
```

Where was the data in this dataset sourced from?
```
Republic of Korea.
```
Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
- Video : https://blog.naver.com/bcwnews/222602753035
- Catoon : http://bcwnews.com/6169
- Planning series : http://bcwnews.com/1032
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes, Public data
```

What is the expected retrieval frequency for this data?
```
It currently has more than 5,000 members.
I subscribe to a lot of news that is an issue, and in particular, video and blockchain serial cartoons are popular.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
I want to permanently store all the data produced by BCW.
```

## DataCap allocation plan
In which geographies (countries, regions) do you plan on making storage deals?
```
Republic of Korea, Asia
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
It is possible online and offline if you are a Korean storage provider.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
There are two to three storage providers connected to the partner company. And storage providers want to attract data.
```

How will you be distributing deals across storage providers?
```
Both online and offline transmissions are possible.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Partner storage providers are already ready. Once the data cap is approved, it plans to save it as File Plus as soon as possible.
```

**Comment by psh0691** [comment]
@KwrayFF I forgot to write the title. Thank you for filling it out instead.

**Comment by psh0691** [comment]
Title, Thanks you!

**Comment by psh0691** [comment]
...

**Comment by galen-mcandrew** [comment]
## Multisig Notary requested
#### Total DataCap requested 
> 1PiB
#### Expected weekly DataCap usage rate 
> 100TiB

**Comment by galen-mcandrew** [comment]
Looks like bot is not picking up to start first allocation, so I'll do it manually.

> Total DataCap requested
> 1PiB
> 
> Expected weekly DataCap usage rate
> 100TiB

First allocation: lesser of 5% of total DataCap requested or 50% of weekly allocation rate

5% of 1PiB = 6.4TiB

**Comment by psh0691** [comment]
@galen-mcandrew

**Comment by Reiers** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebw3fkci4hzxi4bsugub2oikldwg2jsm2bvofavjcepqlstqvoz54 
#### Address 
> f3simkqmjbjnbpifr3pbtdmcfjz35sisrehkq3gcmwn7ghtussajcw6wiypzzprxdvt5pj6y2dzrxjpvn6tz2q
#### Datacap Allocated
> 50TiB
#### Signer Address
> f1oz43ckvmtxmmsfzqm6bpnemqlavz4ifyl524chq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebw3fkci4hzxi4bsugub2oikldwg2jsm2bvofavjcepqlstqvoz54

**Comment by MegTei** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebmf3tg46cagp3bpakmiatfgnysbgq3e46pq4uhzlbvvh4giwbnoq 
#### Address 
> f3simkqmjbjnbpifr3pbtdmcfjz35sisrehkq3gcmwn7ghtussajcw6wiypzzprxdvt5pj6y2dzrxjpvn6tz2q
#### Datacap Allocated
> 50TiB
#### Signer Address
> f1ystxl2ootvpirpa7ebgwl7vlhwkbx2r4zjxwe5i
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebmf3tg46cagp3bpakmiatfgnysbgq3e46pq4uhzlbvvh4giwbnoq

**Comment by mr-spaghetti-code** [comment]
Hi,

It looks like you received 50TiBs of DataCap to date but have spent less than 20% of it so far.

We would love to understand if there's anything holding you back. We are working hard to make the data onboarding process easier for clients like you and your feedback is very valuable. If you have a moment, please fill in this survey: https://forms.gle/s6AuTXZPZSMokscLA

If you have any feedback or would like to consult with an expert, please let me know. 

Thanks,

João Fiadeiro
Product Manager, Large Data Client Onboarding
Protocol Labs

**Comment by ClarkYin5566** [comment]
Hi @psh0691 , I am also applying for datacap but still waiting for review. I would like to discuss with you how to proceed and how to promote the development of real data. If possible, please leave your email or contact me: mr.clark.yin@gmail.com

**Comment by 1LISA2** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceavha53qaqrfj3okmlavoitwz2djwdkrmadnhizlgn5inas22yols 
#### Address 
> f3simkqmjbjnbpifr3pbtdmcfjz35sisrehkq3gcmwn7ghtussajcw6wiypzzprxdvt5pj6y2dzrxjpvn6tz2q
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1jvvltduw35u6inn5tr4nfualyd42bh3vjtylgci
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceavha53qaqrfj3okmlavoitwz2djwdkrmadnhizlgn5inas22yols

**Comment by liyunzhi-666** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceagjzmgultrjtib4lf4ruzoqy7a5icc4rrytll34qonkgapvbt6lw 
#### Address 
> f3simkqmjbjnbpifr3pbtdmcfjz35sisrehkq3gcmwn7ghtussajcw6wiypzzprxdvt5pj6y2dzrxjpvn6tz2q
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1pszcrsciyixyuxxukkvtazcokexbn54amf7gvoq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceagjzmgultrjtib4lf4ruzoqy7a5icc4rrytll34qonkgapvbt6lw

**Comment by psh0691** [comment]
@liyunzhi-666 Thank you. 
Have a good day.

**Comment by BigD-Exchange** [comment]
@psh0691 Hi! Great to see you have gotten approval for DataCap and advancing the mission of preserving humanity’s most important information. If you are looking for storage providers to store these data or have any questions, please visit #bigdata-exchange on Filecoin Slack or reply here. 

We have strong demand from a diverse group of SPs, who are actively looking to onboard more data.

**Comment by Alex11801** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebl4st42m7ssgh7jnke3bohm3skwuswmzy3keg5iev4dakhoe3vz4 
#### Address 
> f3simkqmjbjnbpifr3pbtdmcfjz35sisrehkq3gcmwn7ghtussajcw6wiypzzprxdvt5pj6y2dzrxjpvn6tz2q
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1hhippi64yiyhpjdtbidfyzma6irc2nuav7mrwmi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebl4st42m7ssgh7jnke3bohm3skwuswmzy3keg5iev4dakhoe3vz4

**Comment by Reiers** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebga2g23bxsa4n6ehgzai6f6ccbbjorqep2xukca46ahnhcru24po 
#### Address 
> f3simkqmjbjnbpifr3pbtdmcfjz35sisrehkq3gcmwn7ghtussajcw6wiypzzprxdvt5pj6y2dzrxjpvn6tz2q
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1oz43ckvmtxmmsfzqm6bpnemqlavz4ifyl524chq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebga2g23bxsa4n6ehgzai6f6ccbbjorqep2xukca46ahnhcru24po

**Comment by psh0691** [comment]
@Alex11801 @Reiers Thank you for your approval.

**Comment by stcouldlisa** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceach77nmpbc6c7o6broijp6y2iek4pbqeqdewewm6gdvmemgxfwu4 
#### Address 
> f3simkqmjbjnbpifr3pbtdmcfjz35sisrehkq3gcmwn7ghtussajcw6wiypzzprxdvt5pj6y2dzrxjpvn6tz2q
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1jvvltduw35u6inn5tr4nfualyd42bh3vjtylgci
#### Id
> 07007e27-77f4-4713-8754-dd26ff58bd2f
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceach77nmpbc6c7o6broijp6y2iek4pbqeqdewewm6gdvmemgxfwu4

**Comment by NDLABS-OFFICE** [comment]
Reviewed the customer information, communicated with the customer about the storage situation, willing to support and follow up.

**Comment by NDLABS-OFFICE** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecoayfiewciq5qrqv3pvnfyyi6qmqumso7cakqjw7qq3socw33lf2 
#### Address 
> f3simkqmjbjnbpifr3pbtdmcfjz35sisrehkq3gcmwn7ghtussajcw6wiypzzprxdvt5pj6y2dzrxjpvn6tz2q
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1yayfsv6whu3rheviucvventj3y6t542xfpb47ei
#### Id
> 07007e27-77f4-4713-8754-dd26ff58bd2f
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecoayfiewciq5qrqv3pvnfyyi6qmqumso7cakqjw7qq3socw33lf2

**Comment by filplus-checker** [comment]
## DataCap and CID Checker Report[^1]
 - Organization: `Blockchain World(BCW)`
 - Client: `f3simkqmjbjnbpifr3pbtdmcfjz35sisrehkq3gcmwn7ghtussajcw6wiypzzprxdvt5pj6y2dzrxjpvn6tz2q`
### Storage Provider Distribution
The below table shows the distribution of storage providers that have stored data for this client.

If this is the first time a provider takes verified deal, it will be marked as `new`.

For most of the datacap application, below restrictions should apply.
 - Storage provider should not exceed 25% of total datacap.
 - Storage provider should not be storing duplicate data for more than 20%.
 - Storage provider should have published its public IP address.
 - All storage providers should be located in different regions.

⚠️ [f0521569](https://filfox.info/en/address/f0521569) has sealed 59.98% of total datacap.

⚠️ 32.88% of total deal sealed by [f0521569](https://filfox.info/en/address/f0521569) are duplicate data.

| Provider                                                    |                     Location | Total Deals Sealed | Percentage | Unique Data | Duplicate Deals |
| :---------------------------------------------------------- | ---------------------------: | -----------------: | ---------: | ----------: | --------------: |
| [f0521569](https://filfox.info/en/address/f0521569)`new`    |             Seoul, Seoul, KR |         191.77 TiB |     59.98% |  128.71 TiB |          32.88% |
| [f01624021](https://filfox.info/en/address/f01624021)       |             Seoul, Seoul, KR |          66.11 TiB |     20.68% |   60.97 TiB |           7.78% |
| [f01918123](https://filfox.info/en/address/f01918123)`new`  |             Seoul, Seoul, KR |          58.82 TiB |     18.40% |   50.47 TiB |          14.19% |
| [f0399083](https://filfox.info/en/address/f0399083)         | Gyeonggi-do, Gyeonggi-do, KR |           2.12 TiB |      0.66% |    2.05 TiB |           3.38% |
| [f096173](https://filfox.info/en/address/f096173)           | Gwangmyeong, Gyeonggi-do, KR |         652.00 GiB |      0.20% |  648.00 GiB |           0.61% |
| [f01126768](https://filfox.info/en/address/f01126768)       | Gyeonggi-do, Gyeonggi-do, KR |         165.75 GiB |      0.05% |  165.25 GiB |           0.30% |
| [f0149444](https://filfox.info/en/address/f0149444)         | Gyeonggi-do, Gyeonggi-do, KR |          96.00 GiB |      0.03% |   96.00 GiB |           0.00% |

![Provider Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/166/1671093377593.png)
### Deal Data Replication
The below table shows how each many unique data are replicated across storage providers.
- No more than 25% of unique data are stored with less than 4 providers.

⚠️ 100.00% of deals are for data replicated across less than 4 storage providers.

| Unique Data Size | Total Deals Made | Number of Providers | Deal Percentage |
| ---------------: | ---------------: | ------------------: | --------------: |
|        58.08 TiB |        72.97 TiB |                   1 |          22.83% |
|        83.90 TiB |       227.03 TiB |                   2 |          71.01% |
|         5.73 TiB |        19.70 TiB |                   3 |           6.16% |

![Replication Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/166/1671093378667.png)
### Deal Data Shared with other Clients
The below table shows how many unique data are shared with other clients.
Usually different applications owns different data and should not resolve to the same CID.

⚠️ CID sharing has been observed.

| Other Client                                                                                                                                                                                                              | Application                                                                                                                   | Total Deals Affected | Unique CIDs |          Verifier |
| :------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ | :---------------------------------------------------------------------------------------------------------------------------- | -------------------: | ----------: | ----------------: |
| [f1lzkycqjpx4nmvznhxkl5fd7rct26tpo56qx2ura](https://filfox.info/en/address/f1lzkycqjpx4nmvznhxkl5fd7rct26tpo56qx2ura)                                                                                                     | [KIM JIN HYUK Gongzakso\(meaning: Production\)](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1038) |           131.71 TiB |       2,621 |   LDN v3 multisig |
| [f3q3vwkcuufnuzslkzjtr3uzhtpbxonvl4oifs5ut<br/>sb2zdyqnr7rn6ptdh2h3hfry642gefonnfamw2x4c<br/>5q4q](https://filfox.info/en/address/f3q3vwkcuufnuzslkzjtr3uzhtpbxonvl4oifs5utsb2zdyqnr7rn6ptdh2h3hfry642gefonnfamw2x4c5q4q) | Unknown                                                                                                                       |             2.06 TiB |           1 |           Unknown |
| [f3uizzqt4occf4sf6ne7pvjqorfh2anb4sys7kzrx<br/>fpw77rgpfqjkdquat2m662rnmfitrfaoqzf6nfp77<br/>oqua](https://filfox.info/en/address/f3uizzqt4occf4sf6ne7pvjqorfh2anb4sys7kzrxfpw77rgpfqjkdquat2m662rnmfitrfaoqzf6nfp77oqua) | Unknown                                                                                                                       |           448.00 GiB |          14 |           Unknown |
| [f3s27xfwb6pdne5qgfkdbf7ekuvpnfeo3iq2kuu6a<br/>2nixxxitsnlkmotrxtj2jtegewx6kvugo2lj4dy3p<br/>esrq](https://filfox.info/en/address/f3s27xfwb6pdne5qgfkdbf7ekuvpnfeo3iq2kuu6a2nixxxitsnlkmotrxtj2jtegewx6kvugo2lj4dy3pesrq) | `JKC Global`                                                                                                                  |           384.00 GiB |          12 |        Performive |
| [f3ri7eoqdpai2eor65k3nbzbalseph2sq3ytl4awt<br/>ocwib5twl2qdqapssehkmpqli2hib5hzkjqktmg5h<br/>md3a](https://filfox.info/en/address/f3ri7eoqdpai2eor65k3nbzbalseph2sq3ytl4awtocwib5twl2qdqapssehkmpqli2hib5hzkjqktmg5hmd3a) | `Yehyun`                                                                                                                      |           232.00 GiB |           8 |        Steve Song |
| [f3tfs6seggoe75xpj3a4buavcjttx4rs6jgeusbmj<br/>zzklra6l2j3oqpk3tpgbfsocl63en5r7uiqrsdufb<br/>6jlq](https://filfox.info/en/address/f3tfs6seggoe75xpj3a4buavcjttx4rs6jgeusbmjzzklra6l2j3oqpk3tpgbfsocl63en5r7uiqrsdufb6jlq) | [Cleancap](https://github.com/filecoin-project/filecoin-plus-client-onboarding/issues/784)                                    |            96.00 GiB |           1 |             stone |
| [f3tbfu6dptaui5uwdt7tlhzmovocz47z2fv34deww<br/>hvkf6heel63zqv6ro7we5fvfzndmofel64dggk5vd<br/>r5rq](https://filfox.info/en/address/f3tbfu6dptaui5uwdt7tlhzmovocz47z2fv34dewwhvkf6heel63zqv6ro7we5fvfzndmofel64dggk5vdr5rq) | [TVCC](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/117)                                           |            64.00 GiB |           1 |   LDN v3 multisig |
| [f3rpablljxoko6djyzbkmtqukfa6dnrzjuzflokeu<br/>ou4x42nyrfa64e5f4isjm4yfv4mb5v6jtfqgx7hch<br/>kh4a](https://filfox.info/en/address/f3rpablljxoko6djyzbkmtqukfa6dnrzjuzflokeuou4x42nyrfa64e5f4isjm4yfv4mb5v6jtfqgx7hchkh4a) | [UJOONET](https://github.com/filecoin-project/filecoin-plus-client-onboarding/issues/868)                                     |            64.00 GiB |           2 |      Dr. Ann Shin |
| [f3qis6dmgb3y73xycgrlkzm2iimjivyxovfizthjd<br/>t72kkvzuhfjzrj5yuaoo7d2tsczospmnotdaf35tz<br/>34uq](https://filfox.info/en/address/f3qis6dmgb3y73xycgrlkzm2iimjivyxovfizthjdt72kkvzuhfjzrj5yuaoo7d2tsczospmnotdaf35tz34uq) | `Glif auto verified`                                                                                                          |            32.00 GiB |           1 | Jonathan Schwartz |
| [f3uytte2nvfzcow3lmiowu7owpnhlbmknlpmtddcv<br/>g2hjyiktrfg3ol3m7oy2mugbucnmkyos3a5pj4k2h<br/>idua](https://filfox.info/en/address/f3uytte2nvfzcow3lmiowu7owpnhlbmknlpmtddcvg2hjyiktrfg3ol3m7oy2mugbucnmkyos3a5pj4k2hidua) | Unknown                                                                                                                       |            32.00 GiB |           1 |           Unknown |
| [f3u5l74k5b3kh4drszygkaowx7rx3fv4pcqh7c7yn<br/>2k6xgvtdcb344v3cyfvzssropkqr7bqxnkyuhyqmo<br/>ez6q](https://filfox.info/en/address/f3u5l74k5b3kh4drszygkaowx7rx3fv4pcqh7c7yn2k6xgvtdcb344v3cyfvzssropkqr7bqxnkyuhyqmoez6q) | `Glif auto verified`                                                                                                          |            28.00 GiB |           6 | Jonathan Schwartz |

[^1]: To manually trigger this report, add a comment with text `checker:manualTrigger`

**Comment by data-programs** [comment]
<img width="32" alt="KYC" Verified src="https://stable.filplus.storage/images/filplus-kyc-verified-badge.png"/>

This user’s identity has been verified through [filplus.storage](https://filplus.storage)
