### ISSUE TITLE
[DataCap Application] <OriginStorage> <NOAA Geostationary Operational Environmental Satellites (GOES) 16, 17 & 18> - (1/3)

### ISSUE THREAD

**Issue by Tom-OriginStorage** [filecoin-project/filecoin-plus-large-datasets#1660]
### Data Owner Name

National Oceanic and Atmospheric Administration

### Data Owner Country/Region

United States

### Data Owner Industry

Life Science / Healthcare

### Website

https://registry.opendata.aws/noaa-goes .

### Social Media

```text
https://github.com/awslabs/open-data-docs/tree/main/docs/noaa/noaa-goes16
https://registry.opendata.aws/noaa-goes .
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

450TiB

### On-chain address for first allocation

f1gdxwhlgds3padyhj7rptu3ujxalu4ejc6tyv5xi

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
NEW GOES-18 Data!!! GOES-18 is now provisional and data has began streaming. Data files will be available between Provisional and the Operational Declaration of the satellite, however, data will have the caveat GOES-18 Preliminary, Non-Operational Data. The exception is during the interleave period when ABI Radiances and Cloud and Moisture Imagery data will be shared operationally via the NOAA Open Data Dissemination Program. GOES satellites (GOES-16, GOES-17, & GOES-18) provide continuous weather imagery and monitoring of meteorological and space environment data across North America. GOES satellites provide the kind of continuous monitoring necessary for intensive data analysis. They hover continuously over one position on the surface. The satellites orbit high enough to allow for a full-disc view of the Earth. Because they stay above a fixed spot on the surface, they provide a constant vigil for the atmospheric "triggers" for severe weather conditions such as tornadoes, flash floods, hailstorms, and hurricanes. When these conditions develop, the GOES satellites are able to monitor storm development and track their movements. SUVI products available in both NetCDF and FITS.
```

### Is this project associated with other projects/ecosystem stakeholders?

Yes

### Describe the data being stored onto Filecoin

```text
NEW GOES-18 Data!!! GOES-18 is now provisional and data has began streaming. Data files will be available between Provisional and the Operational Declaration of the satellite, however, data will have the caveat GOES-18 Preliminary, Non-Operational Data. The exception is during the interleave period when ABI Radiances and Cloud and Moisture Imagery data will be shared operationally via the NOAA Open Data Dissemination Program. GOES satellites (GOES-16, GOES-17, & GOES-18) provide continuous weather imagery and monitoring of meteorological and space environment data across North America. GOES satellites provide the kind of continuous monitoring necessary for intensive data analysis. They hover continuously over one position on the surface. The satellites orbit high enough to allow for a full-disc view of the Earth. Because they stay above a fixed spot on the surface, they provide a constant vigil for the atmospheric "triggers" for severe weather conditions such as tornadoes, flash floods, hailstorms, and hurricanes. When these conditions develop, the GOES satellites are able to monitor storm development and track their movements. SUVI products available in both NetCDF and FITS.
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### Please share a sample of the data

```text
2023-01-10 23:46:16    4.7 MiB SUVI-L1b-He303/2023/010/15/OR_SUVI-L1b-He303_G17_s20230101545352_e20230101545362_c20230101545546.fits
2023-01-10 23:46:15    4.8 MiB SUVI-L1b-He303/2023/010/15/OR_SUVI-L1b-He303_G17_s20230101545352_e20230101545362_c20230101545546.nc
2023-01-10 23:46:16    4.7 MiB SUVI-L1b-He303/2023/010/15/OR_SUVI-L1b-He303_G17_s20230101545443_e20230101545443_c20230101546044.fits
2023-01-10 23:46:15    4.8 MiB SUVI-L1b-He303/2023/010/15/OR_SUVI-L1b-He303_G17_s20230101545443_e20230101545443_c20230101546044.nc
2023-01-10 23:47:41    4.7 MiB SUVI-L1b-He303/2023/010/15/OR_SUVI-L1b-He303_G17_s20230101547043_e20230101547043_c20230101547247.fits
2023-01-10 23:47:42    4.8 MiB SUVI-L1b-He303/2023/010/15/OR_SUVI-L1b-He303_G17_s20230101547043_e20230101547043_c20230101547247.nc
2021-09-28 03:48:15   31.6 KiB index.html
Total Objects: 237687110
Total Size: 780.1 TiB
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

1.5 to 2 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, South America

### How will you be distributing your data to storage providers

Cloud storage (i.e. S3), HTTP or FTP server

### How do you plan to choose storage providers

Slack, Big data exchange

### How do you plan to make deals to your storage providers

Boost client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
@Tom-OriginStorage It seems that you have submitted 5 applications.
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1661
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1662
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1664
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1681

Can you introduce your organization and Sps you will cooperate with.

**Comment by Tom-OriginStorage** [comment]
hi  @Sunnyiscoming  I'm glad to receive your reply
OriginStorage as a distributed storage and blockchain practitioner, we started the research and application of IPFS in 2018 and caught up with Filecoin again in 2019. After closely studying the Filecoin white paper and related technologies, we believe it was the only business scenario that could be landed since the development of blockchain technology. ORIGIN storage was finally set up, and lots of human and material resources were invested into Filecoin during the continuous operation.

1. In 2018,  some of our codes were merged. For example: 
https://github.com/btfslib/go-libp2p-quic-transport/commit/944de2ea4fec3bbab65d9d36577b7128142b361a

2. We went through all the test networks of Filecoin (T02417 is still active in the main network: https://filfox.info/en/address/f02417):
Testnet1: T017267
Testnet2: T01030
Spacerace: T02417, T017273

3. Co-developed a decentralized netdisk with Blockcasting Cloud in slingshot. (Slingshot registration ID: 676715867) (https://github.com/litianc/slingshot/blob/master/participants/BlockcastingCloud.md) 

4. After continuous investment and efforts, the company has become an essential contributor to the Filecoin network, with a total of 600P+ computing power. We also have an integrated Filecoin storage solution covering IDC server room, hardware, and software. To improve data encapsulation and storage efficiency, we conduct deep optimization in the modules of encapsulation efficiency, scheduling, space-time proof, cluster architecture, etc.

5. We strive to promote the development of IPFS and Filecoin by establishing partnerships with several web 2.0 industry giants and facilitating the storage of valid data in Filecoin.

**Comment by Tom-OriginStorage** [comment]
1. Participated in the entire process of Filecoin's test net/space race/mainnet development(https://filfox.info/en/address/f02417)

2. Started in 2019, actively promoted IPFS and Filecoin technology. In October 2020, while many miners did not understand the protocol lab, we wrote many articles to explain the Filecoin economic model and spoke in public to support PL.

3. We developed the decentralized network disk in Slingshot (ID: 676715867) together with Blockcasting Cloud. 
(https://github.com/litianc/slingshot/blob/master/participants/BlockcastingCloud.md)

4. We continuously participate in the development of Filecoin, issue reporting, and code contribution.
(https://github.com/filecoin-project/lotus/issues/7833.
https://github.com/filecoin-project/lotus/pull/6635)

5. We became Venus Master to participate in the construction of the community and make contributions: slack: cryptostack-zou (https://filecoinproject.slack.com/archives/CEHHJNJS3/p1635833794026900)

6. Become the leading SP of Solana Lab to store blockchain snapshot data in Filecoin.

7. Become an early builder member of fvm.

8. Actively participate in the construction of the filecoin community and contribute to the command line HD wallet: https://github.com/llifezou/fil-wallet

**Comment by Tom-OriginStorage** [comment]
We keep working on Filecoin, and our colleague has proposed several issues and pr involved in the development of Filecoin.
https://github.com/filecoin-project/lotus/pull/6635
https://github.com/filecoin-project/lotus/pull/7844
https://github.com/filecoin-project/lotus/pull/7512
https://github.com/filecoin-project/lotus/pull/8208
https://github.com/filecoin-project/lotus/issues/7132
https://github.com/filecoin-project/lotus/issues/6669

**Comment by Tom-OriginStorage** [comment]
@Sunnyiscoming 
We have communicated and confirmed the SPs for cooperation. They are mainly located in Southeast Asia, Greater China and North America. At present, we are sure to use
f01914268
f01896036
f02024315
f02013434
f02044834

At present, we are still talking about the remaining SPs. We expect that more than 20 SPs will join in total;

According to the demand, we have applied for 25PiB in total this time. We have made the preliminary preparations. We hope we can get your support. Thank you

**Comment by Sunnyiscoming** [comment]
Total Size: 780.1 TiB
You have submitted 3 applications for 15 PB Datacap. How many copies you want to store?

**Comment by Tom-OriginStorage** [comment]
> Total Size: 780.1 TiB You have submitted 3 applications for 15 PB Datacap. How many copies you want to store?

We are ready to store to 10 SPs, which have been communicated and confirmed, and the node ID is still being prepared. Because the CAR file is larger than 0.5 times the sector size and smaller than the sector size, the 780T is estimated to need nearly 15P of storage space. Because the final actual size is uncertain, I only submitted 2 applications for the time being（#1681）, totaling 10P. After the 10P is used, I will decide whether to apply for the final 5P according to the situation. Thank you

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 5PiB

**Expected weekly DataCap usage rate**
> 400TiB

**Client address**
>f1gdxwhlgds3padyhj7rptu3ujxalu4ejc6tyv5xi

**Comment by Bitrise0111** [comment]
@Tom-OriginStorage  
I have looked through the explanation, it makes sense. also your account is an active member of the Network, KYC process can be skipped.
One more question: Will you provide us with a list of CIDs after data be uploaded on the network for these four LDNs so that we can verify the data?

> > Total Size: 780.1 TiB You have submitted 3 applications for 15 PB Datacap. How many copies you want to store?
> 
> We are ready to store to 10 SPs, which have been communicated and confirmed, and the node ID is still being prepared. Because the CAR file is larger than 0.5 times the sector size and smaller than the sector size, the 780T is estimated to need nearly 15P of storage space. Because the final actual size is uncertain, I only submitted 2 applications for the time being（#1681）, totaling 10P. After the 10P is used, I will decide whether to apply for the final 5P according to the situation. Thank you

**Comment by Tom-OriginStorage** [comment]
> @Tom-OriginStorage I have looked through the explanation, it makes sense. also your account is an active member of the Network, KYC process can be skipped. One more question: Will you provide us with a list of CIDs after data be uploaded on the network for these four LDNs so that we can verify the data?
> 
> > > Total Size: 780.1 TiB You have submitted 3 applications for 15 PB Datacap. How many copies you want to store?
> > 
> > 
> > We are ready to store to 10 SPs, which have been communicated and confirmed, and the node ID is still being prepared. Because the CAR file is larger than 0.5 times the sector size and smaller than the sector size, the 780T is estimated to need nearly 15P of storage space. Because the final actual size is uncertain, I only submitted 2 applications for the time being（#1681）, totaling 10P. After the 10P is used, I will decide whether to apply for the final 5P according to the situation. Thank you

Yes, this is no problem. Thank you, notary

**Comment by Bitrise0111** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecpvwk23zl3rn2yo5ng4bbvi4k5bzvmy4vs3nzyzn772gdp7vzasq 
#### Address 
> f1gdxwhlgds3padyhj7rptu3ujxalu4ejc6tyv5xi
#### Datacap Allocated
> 225.00TiB
#### Signer Address
> f1nknj7ayq4o43czrtdoauggtwl43fbqatmqis3yy
#### Id
> c93750b0-cf73-45dc-ad33-cc1b2ad0b00b
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecpvwk23zl3rn2yo5ng4bbvi4k5bzvmy4vs3nzyzn772gdp7vzasq

**Comment by graceonline9** [comment]
It seems that the applicant is a notary. In order to avoid private dealings.
@Tom-OriginStorage Can you explain which organizations these sps belong to? Can you support retrieval?
![image](https://user-images.githubusercontent.com/87518670/223610723-8a42c8fe-c0c2-42f6-970c-935749a858c8.png)
The same sps combination appears in several other applications
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1650
It is suspected that these sp's belong to one organization.
@cryptowhizzard Can you check this one?

**Comment by Tom-OriginStorage** [comment]
Hello, @graceonline9 ,OriginStorgae is a notary. OriginStorgae is not only a notary, but also a SP. For details, please refer to the information I posted above. Is there any problem with the agreement of SPs? What is your source of guesswork, and what institutional organization do you belong to? Don’t use the trumpet to make trouble here, if you have any questions, you can find me on slack, or you can communicate at the notary meeting or T&T meeting

**Comment by newwebgroup** [comment]
I see that you plan to store publicly available large data sets, please answer these questions for me
1.How will you get the data from the data source?
2.How much bandwidth resources do you have?
3.How do you plan to transfer the data to the partner SPs?

**Comment by Tom-OriginStorage** [comment]
1: I will download data from AWS, which is currently being downloaded
2: My bandwidth is 5Gbps+,
3: I will provide the CAR file to other SP downloads by letting customers download
thank you

**Comment by newwebgroup** [comment]
We are willing to support in the first round and would like to see CID Checker results that meet the requirements.

**Comment by newwebgroup** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacect66j5d3le3zhwumeayez4od2r2if4zld4q77rfkc23yp634epos 
#### Address 
> f1gdxwhlgds3padyhj7rptu3ujxalu4ejc6tyv5xi
#### Datacap Allocated
> 225.00TiB
#### Signer Address
> f1e77zuityhvvw6u2t6tb5qlnsegy2s67qs4lbbbq
#### Id
> c93750b0-cf73-45dc-ad33-cc1b2ad0b00b
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacect66j5d3le3zhwumeayez4od2r2if4zld4q77rfkc23yp634epos

**Comment by a1991car** [comment]
Looks ok, retrieval works,

**Comment by a1991car** [comment]
![微信图片_20230410123932](https://user-images.githubusercontent.com/32447611/230827263-23190512-ad59-4ab0-8a0a-4246fa612e43.jpg)

**Comment by a1991car** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebor3zyszdsstmzziww3b4e5mpjo3ep7ma3taumqcfplbhkkioefa 
#### Address 
> f1gdxwhlgds3padyhj7rptu3ujxalu4ejc6tyv5xi
#### Datacap Allocated
> 450.00TiB
#### Signer Address
> f1qnumecdypgrbaebtkdfjnwt5ndacadcuas3deiq
#### Id
> d734deed-78c4-47f3-affd-fe338b01e6e2
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebor3zyszdsstmzziww3b4e5mpjo3ep7ma3taumqcfplbhkkioefa

**Comment by sxxfuture-official** [comment]
checker:manualTrigger

**Comment by sxxfuture-official** [comment]
CID-Checker Report shows that everything in line with the FIL+ rules, I will support this round if retrieve test OK.
But as a notory I suggest adding nodes in such as Europe, the United States, and Australia to the project. After all, it seems that all SPs are currently concentrated in East Asia and Southeast Asia.

**Comment by igoovo** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacearcmzx4ztmy4zw363fbe5zptdtxy2srkkbyoor72y7k566dy6zj2 
#### Address 
> f1gdxwhlgds3padyhj7rptu3ujxalu4ejc6tyv5xi
#### Datacap Allocated
> 450.00TiB
#### Signer Address
> f1shnsfayxqll77svffaxnjenms7bbbysbqcatrpy
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacearcmzx4ztmy4zw363fbe5zptdtxy2srkkbyoor72y7k566dy6zj2

**Comment by a1991car** [comment]
checker:manualTrigger

**Comment by stcouldlisa** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebdktny5yikkop4acoldq47zqh2ys4ro3z54s3lr5rxfbsip4cryo 
#### Address 
> f1gdxwhlgds3padyhj7rptu3ujxalu4ejc6tyv5xi
#### Datacap Allocated
> 900.00TiB
#### Signer Address
> f1jvvltduw35u6inn5tr4nfualyd42bh3vjtylgci
#### Id
> d1c5ae5e-e6f4-4672-ac99-2b90a1cccf20
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebdktny5yikkop4acoldq47zqh2ys4ro3z54s3lr5rxfbsip4cryo

**Comment by laurarenpanda** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceajjwhfladdllxtl2apq5ociyz6uerjwt4s3ap52e3s5cl7gda6gy 
#### Address 
> f1gdxwhlgds3padyhj7rptu3ujxalu4ejc6tyv5xi
#### Datacap Allocated
> 900.00TiB
#### Signer Address
> f1bp3tzp536edm7dodldceekzbsx7zcy7hdfg6uzq
#### Id
> d1c5ae5e-e6f4-4672-ac99-2b90a1cccf20
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceajjwhfladdllxtl2apq5ociyz6uerjwt4s3ap52e3s5cl7gda6gy

**Comment by 1ane-1** [comment]
checker:manualTrigger

**Comment by 1ane-1** [comment]
![6dea62142485f8821b68c643c3c4169](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/91301211/78ea64ec-34cf-4673-bce5-4239f32c6b0b)

**Comment by 1ane-1** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedi6lfwkwv5edepgugdcl7ylj5txqtqawg3i6un4cu5aj33qwfypi 
#### Address 
> f1gdxwhlgds3padyhj7rptu3ujxalu4ejc6tyv5xi
#### Datacap Allocated
> 1.75PiB
#### Signer Address
> f1mdk7s2vntzm6hu35yuo6vjubtrpfnb2awhgvrri
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedi6lfwkwv5edepgugdcl7ylj5txqtqawg3i6un4cu5aj33qwfypi

**Comment by newwebgroup** [comment]
Checking the Github history and the CID Checker report, everything is fine.
> https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1660#issuecomment-1554065344

And I selected a few CIDs randomly through CID Tool for retrieval test, and it worked.

https://filecoin.tools/f02063337

<img width="1181" alt="image" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/100118145/2b469957-5357-4789-9503-86a10de16e19">

<img width="1186" alt="image" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/100118145/407f2fd8-4b15-43ef-847c-6e45fe7a8048">
<img width="1055" alt="image" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/100118145/8d767f92-f578-4187-ada5-dfa1030ef0b5">

**Comment by newwebgroup** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceau3rsoyidblzfm2kgqroq5qtxyu2ifqtpfmbz5oyhddy6nfvptly 
#### Address 
> f1gdxwhlgds3padyhj7rptu3ujxalu4ejc6tyv5xi
#### Datacap Allocated
> 1.75PiB
#### Signer Address
> f1e77zuityhvvw6u2t6tb5qlnsegy2s67qs4lbbbq
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceau3rsoyidblzfm2kgqroq5qtxyu2ifqtpfmbz5oyhddy6nfvptly

**Comment by herrehesse** [comment]
checker:manualTrigger

**Comment by Tom-OriginStorage** [comment]
checker:manualTrigger

**Comment by Tom-OriginStorage** [comment]
checker:manualTrigger

**Comment by SuperChaiChai** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebmg6tn4gwtds4c6tjk443myandofib7mtqcy7hncl34djamuazcc 
#### Address 
> f1gdxwhlgds3padyhj7rptu3ujxalu4ejc6tyv5xi
#### Datacap Allocated
> 1.71PiB
#### Signer Address
> f12mckci3omexgzoeosjvstcfxfe4vqw7owdia3da
#### Id
> 80a3cc5d-e3a7-40f2-a196-a7a942ae441a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebmg6tn4gwtds4c6tjk443myandofib7mtqcy7hncl34djamuazcc

**Comment by luobin544** [comment]
checker:manualTrigger

**Comment by luobin544** [comment]
Check for excellent success rates and provide support

**Comment by luobin544** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedillw7jmypszcsg4vd2trbpme2xeh2f5wvnkisd2l3efntl6tjpy 
#### Address 
> f1gdxwhlgds3padyhj7rptu3ujxalu4ejc6tyv5xi
#### Datacap Allocated
> 1.71PiB
#### Signer Address
> f1tbd632f6w62glfaf7wjpimacbnjiz26poyoes2q
#### Id
> 80a3cc5d-e3a7-40f2-a196-a7a942ae441a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedillw7jmypszcsg4vd2trbpme2xeh2f5wvnkisd2l3efntl6tjpy

**Comment by Wengeding** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceddyi5xxhcocifqbdc636hq7rpgr32mkur4exwlddszdyo7y2rx5s 
#### Address 
> f1gdxwhlgds3padyhj7rptu3ujxalu4ejc6tyv5xi
#### Datacap Allocated
> 1.96TiB
#### Signer Address
> f1txfsjmix4vlzido4dkildrnbw26owtlbslexmpa
#### Id
> 805e0c88-0f44-4f9f-a741-733bffd0eb58
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceddyi5xxhcocifqbdc636hq7rpgr32mkur4exwlddszdyo7y2rx5s

**Comment by NDLABS-Leo** [comment]
checker:manualTrigger
