### ISSUE TITLE
[DataCap Application] Speedium | Dcent - Epoch of Reionization Dataset 1 - 2

### ISSUE THREAD

**Issue by cryptowhizzard** [filecoin-project/filecoin-plus-large-datasets#1663]
### Data Owner Name

University of washington Radio Cosmology Group

### Data Owner Country/Region

United States

### Data Owner Industry

Life Science / Healthcare

### Website

http://danielcjacobs.com/research/epoch-of-reionization-aws-public-dataset/

### Social Media

```text
http://danielcjacobs.com/research/epoch-of-reionization-aws-public-dataset/
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

200TiB

### On-chain address for first allocation

f14mebbhgsdsd5rq7wrsjkb63segrxpgv33px6gsi

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Since its launch, the Filecoin network has become an important player in the decentralised storage space, offering a secure and transparent alternative to traditional data storage solutions.

We as Speedium / DCENT have been engaged with storing real and valuable datasets on the Filecoin network since Slingshot and have been actively developing tools to improve the process. We are always on the lookout for new and useful client data to onboard.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
The data are from observations with the Murchison Widefield Array (MWA) which is a Square Kilometer Array (SKA) precursor in Western Australia. This particular dataset is from the Epoch of Reionization project which is a key science driver of the SKA. Nearly 2PB of such observations have been recorded to date, this is a small subset of that which has been exported from the MWA data archive in Perth and made available to the public on AWS. The data were taken to detect signatures of the first stars and galaxies forming and the effect of these early stars and galaxies on the evolution of the universe.
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### How do you plan to prepare the dataset

singularity, others/custom tool

### If you answered "other/custom tool" in the previous question, enter the details here

```text
Inhouse tooling
```

### Please share a sample of the data

```text
https://registry.opendata.aws/epoch-of-reionization/
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

Permanently

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, Europe, Australia (continent)

### How will you be distributing your data to storage providers

HTTP or FTP server

### How do you plan to choose storage providers

Slack, Filmine, Big data exchange, Partners

### If you already have a list of storage providers to work with, fill out their names and provider IDs below

```text
| MinerID | City | Continent | Business/Entity |
| --- | --- | --- | --- |
| `f01944347` | Oregon | USA | Jenny, Dabai |
| `f01952350` | Oregon | USA | Jenny, Dabai |
| `f01972364` | Oregon | USA | Jenny, Dabai |
| `f01972376` | Oregon | USA | Jenny, Dabai |
| `f02000937` | Chengdu | CN | MTY |
| `f01915033` | Chengdu | CN | MTY |
| `f01901765` | Hangzhou | CN | MTY |
| `f01953985` | Shenzhen | CN | MTY |
| `f0120****` | Melbourne | AU | HOLON |
| `f0115****` | Melbourne | AU | HOLON |
| `f01199430` | Heerhugowaard | EU | DCENT |
| `f01786387` | Heerhugowaard | EU | DCENT |
| `f01201327` | Heerhugowaard | EU | DCENT |
| `f01937642` | Heerhugowaard | EU | DCENT |
| `f0198****` | Dallas | USA | GREATERHEAT |
| `f0188****` | Singapore | AS | GREATERHEAT |
| `f01091851` | Omaha | USA | DLTx |
| `f01736668` | Omaha | USA | DLTx |
| `f01820744` | Omaha | USA | DLTx |
| `f0855584` | Omaha | USA | DLTx |
| `f01794610` | Omaha | USA | DLTx |
| `f01838599` | Kansas City | USA | DLTx |
| `f01845552` | Kansas City | USA | DLTx |
| `f01885088` | Hong Kong | AS | Hong Kong Morpho Technology Limited |
| `f01926635` | Hong Kong | AS | Hong Kong Morpho Technology Limited |
| `f01933917` | Hong Kong | AS | Hong Kong Morpho Technology Limited |
| `f01989888` | Hong Kong | AS | Hong Kong Morpho Technology Limited |
```

### How do you plan to make deals to your storage providers

Boost client, Others/custom tool

### If you answered "Others/custom tool" in the previous question, enter the details here

```text
Inhouse tooling
```

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 5PiB

**Expected weekly DataCap usage rate**
> 200TiB

**Client address**
>f14mebbhgsdsd5rq7wrsjkb63segrxpgv33px6gsi

**Comment by spaceT9** [comment]
cryptowhizzard is a very reputaional notary, with the exhaustive distribution plan, I am willing to support the first round.

**Comment by spaceT9** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced27nijh2u2w5y6teqlp3mu4o4soxsbrpcny6fwtbrqvlqamti444 
#### Address 
> f14mebbhgsdsd5rq7wrsjkb63segrxpgv33px6gsi
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1dktm3abgn7wkpepxab4q3eaw24qktizk4esfzyy
#### Id
> ad8e1239-1cdb-48cb-9b64-59733cac9061
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced27nijh2u2w5y6teqlp3mu4o4soxsbrpcny6fwtbrqvlqamti444

**Comment by data-programs** [comment]
<img width="32" alt="KYC" Verified src="https://stable.filplus.storage/images/filplus-kyc-verified-badge.png"/>

This user’s identity has been verified through [filplus.storage](https://filplus.storage)
