### ISSUE TITLE
[DataCap Application] Speedium | Dcent - NOAA Water-Column Sonar Data Archive 1 - 2

### ISSUE THREAD

**Issue by cryptowhizzard** [filecoin-project/filecoin-plus-large-datasets#1665]
### Data Owner Name

NOAA

### Data Owner Country/Region

United States

### Data Owner Industry

Life Science / Healthcare

### Website

https://cires.gitbook.io/ncei-wcsd-archive/

### Social Media

```text
https://cires.gitbook.io/ncei-wcsd-archive/
https://registry.opendata.aws/ncei-wcsd-archive/
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

200TiB

### On-chain address for first allocation

f1x4nvcin6x5m7dooqmrqvnbynoxkujm6k7bemvya

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Since its launch, the Filecoin network has become an important player in the decentralised storage space, offering a secure and transparent alternative to traditional data storage solutions.

We as Speedium / DCENT have been engaged with storing real and valuable datasets on the Filecoin network since Slingshot and have been actively developing tools to improve the process. We are always on the lookout for new and useful client data to onboard.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
Water-column sonar data archived at the NOAA National Centers for Environmental Information.
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### How do you plan to prepare the dataset

singularity, others/custom tool

### If you answered "other/custom tool" in the previous question, enter the details here

```text
Inhouse tooling
```

### Please share a sample of the data

```text
https://registry.opendata.aws/ncei-wcsd-archive/
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

Permanently

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, Europe, Australia (continent)

### How will you be distributing your data to storage providers

HTTP or FTP server

### How do you plan to choose storage providers

Slack, Filmine, Big data exchange, Partners

### If you already have a list of storage providers to work with, fill out their names and provider IDs below

```text
| MinerID | City | Continent | Business/Entity |
| --- | --- | --- | --- |
| `f01944347` | Oregon | USA | Jenny, Dabai |
| `f01952350` | Oregon | USA | Jenny, Dabai |
| `f01972364` | Oregon | USA | Jenny, Dabai |
| `f01972376` | Oregon | USA | Jenny, Dabai |
| `f02000937` | Chengdu | CN | MTY |
| `f01915033` | Chengdu | CN | MTY |
| `f01901765` | Hangzhou | CN | MTY |
| `f01953985` | Shenzhen | CN | MTY |
| `f0120****` | Melbourne | AU | HOLON |
| `f0115****` | Melbourne | AU | HOLON |
| `f01199430` | Heerhugowaard | EU | DCENT |
| `f01786387` | Heerhugowaard | EU | DCENT |
| `f01201327` | Heerhugowaard | EU | DCENT |
| `f01937642` | Heerhugowaard | EU | DCENT |
| `f0198****` | Dallas | USA | GREATERHEAT |
| `f0188****` | Singapore | AS | GREATERHEAT |
| `f01091851` | Omaha | USA | DLTx |
| `f01736668` | Omaha | USA | DLTx |
| `f01820744` | Omaha | USA | DLTx |
| `f0855584` | Omaha | USA | DLTx |
| `f01794610` | Omaha | USA | DLTx |
| `f01838599` | Kansas City | USA | DLTx |
| `f01845552` | Kansas City | USA | DLTx |
| `f01885088` | Hong Kong | AS | Hong Kong Morpho Technology Limited |
| `f01926635` | Hong Kong | AS | Hong Kong Morpho Technology Limited |
| `f01933917` | Hong Kong | AS | Hong Kong Morpho Technology Limited |
| `f01989888` | Hong Kong | AS | Hong Kong Morpho Technology Limited |
```

### How do you plan to make deals to your storage providers

Boost client, Others/custom tool

### If you answered "Others/custom tool" in the previous question, enter the details here

```text
Inhouse tooling
```

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
It seems that the information of 4 nodes have been hided. Can you make an explaination? 
| `f0120****` | Melbourne | AU | HOLON |
| `f0115****` | Melbourne | AU | HOLON |
| `f0198****` | Dallas | USA | GREATERHEAT |
| `f0188****` | Singapore | AS | GREATERHEAT |

**Comment by herrehesse** [comment]
Dear @Sunnyiscoming,

I would like to clarify that there has been no attempt to conceal any information regarding Speedium/Dcent's applications. The asterisks indicate that multiple miners in the same range belong to the same entity. This is a deliberate measure to simplify the presentation of information and avoid a lengthy list of over 100 miners in our proposal.

I invite you to take a look at our other applications and their corresponding CID reports. This will allow you to see the different ranges and the businesses operating as storage providers in each range. If you have any questions or require further clarification, please do not hesitate to reach out.

Sincerely, team DCENT

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 5PiB

**Expected weekly DataCap usage rate**
> 200TiB

**Client address**
>f1x4nvcin6x5m7dooqmrqvnbynoxkujm6k7bemvya

**Comment by TimGuo7** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacednv62oind6k3irmmqarpsmdgiiajzhkptterhfts7aiqdoe4ur7u 
#### Address 
> f1x4nvcin6x5m7dooqmrqvnbynoxkujm6k7bemvya
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1yslbnnqzrjlyuxsmyxfbqcc7xthcavgpripjevi
#### Id
> b3c9b938-0225-4792-93bf-4b522530a776
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacednv62oind6k3irmmqarpsmdgiiajzhkptterhfts7aiqdoe4ur7u

**Comment by psh0691** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceak22uwbvnzwfbybzhsriqm3kwfprhwwjmoxfesljijorp7xv2i5a 
#### Address 
> f1x4nvcin6x5m7dooqmrqvnbynoxkujm6k7bemvya
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1qdko4jg25vo35qmyvcrw4ak4fmuu3f5rif2kc7i
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceak22uwbvnzwfbybzhsriqm3kwfprhwwjmoxfesljijorp7xv2i5a
