### ISSUE TITLE
[DataCap Application] Speedium | Dcent - Allen Institute for Neural Dynamics - Mouse Neuroanatomy and Physiology Data 1 - 25

### ISSUE THREAD

**Issue by cryptowhizzard** [filecoin-project/filecoin-plus-large-datasets#1666]
### Data Owner Name

Allen Institute for Neural Dynamics (AIND)

### Data Owner Country/Region

United States

### Data Owner Industry

Life Science / Healthcare

### Website

https://registry.opendata.aws/allen-nd-open-data/

### Social Media

```text
https://registry.opendata.aws/allen-nd-open-data/
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

250TiB

### On-chain address for first allocation

f1p7drde4z46rt2vntxpfknpoyfswkoyhju67vsti

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Since its launch, the Filecoin network has become an important player in the decentralised storage space, offering a secure and transparent alternative to traditional data storage solutions.

We as Speedium / DCENT have been engaged with storing real and valuable datasets on the Filecoin network since Slingshot and have been actively developing tools to improve the process. We are always on the lookout for new and useful client data to onboard.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
The Allen Institute for Neural Dynamics (AIND) is committed to FAIR, Open, and Reproducible science. We therefore share all of the raw and derived data we collect publicly with rich metadata, including preliminary data collected during methods development, as near to the time of collection as possible.
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### How do you plan to prepare the dataset

singularity, others/custom tool

### If you answered "other/custom tool" in the previous question, enter the details here

```text
Inhouse tooling
```

### Please share a sample of the data

```text
https://registry.opendata.aws/allen-nd-open-data/
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Sporadic

### For how long do you plan to keep this dataset stored on Filecoin

Permanently

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, Europe, Australia (continent)

### How will you be distributing your data to storage providers

HTTP or FTP server

### How do you plan to choose storage providers

Slack, Filmine, Big data exchange, Partners

### If you answered "Others" in the previous question, what is the tool or platform you plan to use

```text
Inhouse
```

### If you already have a list of storage providers to work with, fill out their names and provider IDs below

```text
| MinerID | City | Continent | Business/Entity |
| --- | --- | --- | --- |
| `f01944347` | Oregon | USA | Jenny, Dabai |
| `f01952350` | Oregon | USA | Jenny, Dabai |
| `f01972364` | Oregon | USA | Jenny, Dabai |
| `f01972376` | Oregon | USA | Jenny, Dabai |
| `f02000937` | Chengdu | CN | MTY |
| `f01915033` | Chengdu | CN | MTY |
| `f01901765` | Hangzhou | CN | MTY |
| `f01953985` | Shenzhen | CN | MTY |
| `f0120****` | Melbourne | AU | HOLON |
| `f0115****` | Melbourne | AU | HOLON |
| `f01199430` | Heerhugowaard | EU | DCENT |
| `f01786387` | Heerhugowaard | EU | DCENT |
| `f01201327` | Heerhugowaard | EU | DCENT |
| `f01937642` | Heerhugowaard | EU | DCENT |
| `f0198****` | Dallas | USA | GREATERHEAT |
| `f0188****` | Singapore | AS | GREATERHEAT |
| `f01091851` | Omaha | USA | DLTx |
| `f01736668` | Omaha | USA | DLTx |
| `f01820744` | Omaha | USA | DLTx |
| `f0855584` | Omaha | USA | DLTx |
| `f01794610` | Omaha | USA | DLTx |
| `f01838599` | Kansas City | USA | DLTx |
| `f01845552` | Kansas City | USA | DLTx |
| `f01885088` | Hong Kong | AS | Hong Kong Morpho Technology Limited |
| `f01926635` | Hong Kong | AS | Hong Kong Morpho Technology Limited |
| `f01933917` | Hong Kong | AS | Hong Kong Morpho Technology Limited |
| `f01989888` | Hong Kong | AS | Hong Kong Morpho Technology Limited |
```

### How do you plan to make deals to your storage providers

Boost client, Others/custom tool

### If you answered "Others/custom tool" in the previous question, enter the details here

```text
Inhouse tooling
```

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by xingjitansuo** [comment]
Do we allow client to store on his own node?

**Comment by lvschouwen** [comment]
> Do we allow client to store on his own node?

Yes.

**Comment by kernelogic** [comment]
@lvschouwen source?

**Comment by simonkim0515** [comment]
Just to be clear here there are no set rules about client’s storing their own dataset. The LDN applications are reviewed case by case by the notaries. Our ask is that you are transparent about the data you are trying to onboard. For more information about best practices to follow please visit the filecoin-plus-large-datasets repo.    

https://github.com/filecoin-project/filecoin-plus-large-datasets

We agree that due to the situations with the community, we can work on publishing this better. If you would like to continue this discussion, please visit this discussion post. 

https://github.com/filecoin-project/notary-governance/discussions/834

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 5PiB

**Expected weekly DataCap usage rate**
> 250TiB

**Client address**
>f1p7drde4z46rt2vntxpfknpoyfswkoyhju67vsti

**Comment by data-programs** [comment]
<img width="32" alt="KYC" Verified src="https://stable.filplus.storage/images/filplus-kyc-verified-badge.png"/>

This user’s identity has been verified through [filplus.storage](https://filplus.storage)
