### ISSUE TITLE
[DataCap Application] Seal Storage Technology - Slingshot Restore Program

### ISSUE THREAD

**Issue by scharfstein** [filecoin-project/filecoin-plus-large-datasets#167]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Seal Storage Technology
- Website / Social Media: https://www.sealstorage.io/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 2 PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 500 TiB
- On-chain address for first allocation: f3xgmtwepzgkb45jf6tkfrcezybhwupmg7jl6p6plslced7ufww3b2k4e6bcp3toajv43acdknxkc7xqs7scsq

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Seal recently joined the Slingshot Restore Program as a client and storage provider. We are excited to be a part of the program and wanted to be proactive about DataCap.

Seal is a carbon-neutral, decentralized cloud storage provider. Seal's technical leadership brings decades of experience from traditional enterprise storage companies including Seagate and Oracle, as well as world-class experience on the Filecoin Network. Today, Seal operates data centers across the US and Canada with enterprise-grade infrastructure and data policies.

```

What is the primary source of funding for this project?
```
We are self-funded.
```

What other projects/ecosystem stakeholders is this project associated with?
```
We understand the Slingshot has other projects with Filecoin Foundation / PL.
```

## Use-case details

Describe the data being stored onto Filecoin
```
Data associated with the Slingshot Restore Program that is eligible for Filecoin plus.
```

Where was the data in this dataset sourced from?
```
The Slingshot Restore Program will provide these details.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
Please see Protocol Labs.
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Defer to Slingshot about this.
```

What is the expected retrieval frequency for this data?
```
Unknown at this time.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
500 days as requested by PL
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
US, Canada, Netherlands, Belgium, France
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Seal Storage has dual 100 Gbps internet connections. DSPs will download data from Seal. We can do offline data transfers, if required.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We are currently meeting and discussing capabilities with several other DSPs and has chosen a geographically-diverse group of DSPs with excellent track records in the Filecoin Ecosystem and Space Race.
```

How will you be distributing deals across storage providers?
```
Round robin.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, we have resources and funding.

Nothing at this time. We will make requests as needed. 
```

**Comment by galen-mcandrew** [comment]
## Multisig Notary requested
#### Total DataCap requested 
> 2PiB
#### Expected weekly DataCap usage rate 
> 100TiB

**Comment by scharfstein** [comment]
> ## Multisig Notary requested
> #### Total DataCap requested
> > 2PiB
> 
> #### Expected weekly DataCap usage rate
> > 100TiB

Good day. We reviewed our data storage plan and request a weekly usage rate of 500 TiB. 

All 5 SPs plan to seal data in parallel.

**Comment by scharfstein** [comment]
Data set update - Seal was assigned data set 4:

common-crawl - april 2021	common-crawl - april 2021	100.0 TiB

**Comment by dkkapur** [comment]
@scharfstein - `On-chain address for first allocation: f01558688` still requires a client address. Holding this from proceeding with RKH until we get this corrected. Please update us as soon as possible. Thank you!

**Comment by scharfstein** [comment]
> @scharfstein - `On-chain address for first allocation: f01558688` still requires a client address. Holding this from proceeding with RKH until we get this corrected. Please update us as soon as possible. Thank you!

Sorry for the delay ... here it is:

f3xgmtwepzgkb45jf6tkfrcezybhwupmg7jl6p6plslced7ufww3b2k4e6bcp3toajv43acdknxkc7xqs7scsq

and Happy New Year!

**Comment by swatchliu** [comment]
Happy to support if you need.

**Comment by galen-mcandrew** [comment]
Looks like bot is not picking up to start first allocation, so I'll do it manually.

> Total DataCap requested
> 2PiB
> 
> Expected weekly DataCap usage rate
> 100TiB

First allocation: lesser of 5% of total DataCap requested or 50% of weekly allocation rate

5% of 2PiB = 12.8TiB

**Comment by galen-mcandrew** [comment]
## DataCap Allocation requested

#### Multisig Notary address
> f01645641

#### Client address
> f3xgmtwepzgkb45jf6tkfrcezybhwupmg7jl6p6plslced7ufww3b2k4e6bcp3toajv43acdknxkc7xqs7scsq

#### DataCap allocation requested
> 12.8TiB

**Comment by dkkapur** [comment]
@swatchliu this should show up in the app now for signature. Thanks!

**Comment by flyworker** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedxmacfwhm3nz2jxrnzk2vzqktfju3cdvakekdjr4qa6r5axp6dpq 
#### Address 
> f3xgmtwepzgkb45jf6tkfrcezybhwupmg7jl6p6plslced7ufww3b2k4e6bcp3toajv43acdknxkc7xqs7scsq
#### Datacap Allocated
> 50TiB
#### Signer Address
> f1hlubjsdkv4wmsdadihloxgwrz3j3ernf6i3cbpy
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedxmacfwhm3nz2jxrnzk2vzqktfju3cdvakekdjr4qa6r5axp6dpq

**Comment by dannyob** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecdbpm3jjhqua7pbtorib4dexha5pehwzhfwrtdzek6lyynw7bhya 
#### Address 
> f3xgmtwepzgkb45jf6tkfrcezybhwupmg7jl6p6plslced7ufww3b2k4e6bcp3toajv43acdknxkc7xqs7scsq
#### Datacap Allocated
> 50TiB
#### Signer Address
> f1k6wwevxvp466ybil7y2scqlhtnrz5atjkkyvm4a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecdbpm3jjhqua7pbtorib4dexha5pehwzhfwrtdzek6lyynw7bhya

**Comment by galen-mcandrew** [comment]
hmmm looks like this hit an error, so now there are two pending transactions for 50TiB. Adjusting labels, let's see if @dannyob can try to sign again as an approval for txID 0.

**Comment by dannyob** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedcwhowqnz434wbeq3fm3p7iitqdlhciakitdbo7csyp2sk5z4msy 
#### Address 
> f3xgmtwepzgkb45jf6tkfrcezybhwupmg7jl6p6plslced7ufww3b2k4e6bcp3toajv43acdknxkc7xqs7scsq
#### Datacap Allocated
> 50TiB
#### Signer Address
> f1k6wwevxvp466ybil7y2scqlhtnrz5atjkkyvm4a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedcwhowqnz434wbeq3fm3p7iitqdlhciakitdbo7csyp2sk5z4msy

**Comment by galen-mcandrew** [comment]
@scharfstein  txID 0 is now approved, so client can start sealing deals. There's still another pending transaction for 50TiB, so for the next allocation we can either require one more signature to clear the 50 (which will require some label adjustment), or we let the subsequent allocation bot run with would propose another allocation for higher rate of DataCap and require two signatures.

**Comment by scharfstein** [comment]
> @scharfstein txID 0 is now approved, so client can start sealing deals. There's still another pending transaction for 50TiB, so for the next allocation we can either require one more signature to clear the 50 (which will require some label adjustment), or we let the subsequent allocation bot run with would propose another allocation for higher rate of DataCap and require two signatures.

Thanks Galen ... Please let me know if this is something that requires Seal's input.

**Comment by scharfstein** [comment]
> > @scharfstein txID 0 is now approved, so client can start sealing deals. There's still another pending transaction for 50TiB, so for the next allocation we can either require one more signature to clear the 50 (which will require some label adjustment), or we let the subsequent allocation bot run with would propose another allocation for higher rate of DataCap and require two signatures.
> 
> Thanks @galen-mcandrew ... Please let me know if this is something that requires Seal's input.

@galen-mcandrew ... I received a response from our CTO about this: We prefer 2 signatures. How soon they can get the request made?

**Comment by galen-mcandrew** [comment]
Sorry for confusion here, the first transaction is clear. Client address `f3xgmtwepzgkb45jf6tkfrcezybhwupmg7jl6p6plslced7ufww3b2k4e6bcp3toajv43acdknxkc7xqs7scsq` has 50TiB of DataCap at this time. There is a second pending transaction for another 50TiB (this happened because of an issue with the labels, which led to the second notary action causing a new transaction proposal rather than approving the existing proposal).

You can see this by checking the messages to the large dataset notary multisig `f01645641` https://filfox.info/en/address/f01645641 - back to back proposals, then an approval.

So right now client can start making deals. Once 75% of existing DataCap has been allocated, the subsequent allocation bot will kick off the next allocation. At that time: we could either: get a notary to approve the pending [txID1](https://filfox.info/en/message/bafy2bzacecdbpm3jjhqua7pbtorib4dexha5pehwzhfwrtdzek6lyynw7bhya) for 50TiB **OR** start a new allocation request for 100TiB (per the calculation plan) which would require two notary signatures (a proposal for txID2 and then an approval). 

The only action needed right now: start making deals and sealing the allocated 50TiB of DataCap.
