### ISSUE TITLE
[DataCap Application] <Sparklink Protocol> - <Sparklink Protocol>

### ISSUE THREAD

**Issue by Erreth-Akbe** [filecoin-project/filecoin-plus-large-datasets#1671]
### Data Owner Name

Sparklink protocol

### Data Owner Country/Region

United States

### Data Owner Industry

Information, Media & Telecommunications

### Website

Sparklink.io

### Social Media

```text
https://twitter.com/SparkLink_io

https://discord.gg/3EV9V7Tenb

https://medium.com/@SparkLink_Protocol
```

### Total amount of DataCap being requested

2PiB

### Weekly allocation of DataCap requested

50TiB

### On-chain address for first allocation

f1hjiip3jr6u4a5wgrktfyvgtqrmf3xyxbhpcvbki

### Custom multisig

- [ ] Use Custom Multisig

### Identifier

None

### Share a brief history of your project and organization

```text
SparkLink protocol is a unique decentralized protocol for NFT content creation and sharing. Based on web3.0 concepts, everyone can create their own NFT works through SparkLink and set their own sales and distribution fees. Any sale or dissemination of NFT after it is generated will generate revenue for the owner or node user. SparkLink provides users with a new decentralized way to distribute NFT and spread content，we have developed a new extension protocol ERC-721S, based on the current NFT protocol ERC-721. We have added the scarcity and irreplaceable value of NFT to the sharing incentive property of a larger content layer, allowing the content of all formats to split indefinitely and reap benefits through NFT.
```

### Is this project associated with other projects/ecosystem stakeholders?

Yes

### If answered yes, what are the other projects/ecosystem stakeholders

```text
The project is deployed on Binance Smart Chain and polygon
```

### Describe the data being stored onto Filecoin

```text
Pictures, music, and media materials
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### If you answered "Other" in the previous question, enter the details here

```text
Pinata
```

### How do you plan to prepare the dataset

IPFS

### If you answered "other/custom tool" in the previous question, enter the details here

```text
null
```

### Please share a sample of the data

```text
we have tens of thousands of pages of files on pinata server, including pictures, videos, and audio, here are some sample files（some files that have been asymmetrically encrypted）：
https://i.328888.xyz/2023/02/23/xB5EF.png
sparklink.mypinata.cloud
https://sparklink.mypinata.cloud/ipfs/QmSnBxzqunw9xWBHGmV7Mkoq2dBrGWxgcFhKzyYg355Kbb?_gl=1*13a4ura*_ga*MTY4NDI2MzAxOC4xNjczMDIxNzcx*_ga_5RMPXG14TE*MTY3NzEyNjk2Ny4yLjEuMTY3NzEyNzk4MC42MC4wLjA.
https://sparklink.mypinata.cloud/ipfs/QmTQhGVnL8bSrZNVg5ZqgSN3YXW5bHRrs8PCi8xZGpWCCx?_gl=1*13a4ura*_ga*MTY4NDI2MzAxOC4xNjczMDIxNzcx*_ga_5RMPXG14TE*MTY3NzEyNjk2Ny4yLjEuMTY3NzEyNzk4MC42MC4wLjA.
https://sparklink.mypinata.cloud/ipfs/QmTpKk6sijZUBraQgkRP9xdr2qd5MwXGTZFbNBM6SbrLpp?_gl=1*13a4ura*_ga*MTY4NDI2MzAxOC4xNjczMDIxNzcx*_ga_5RMPXG14TE*MTY3NzEyNjk2Ny4yLjEuMTY3NzEyNzk4MC42MC4wLjA.
https://sparklink.mypinata.cloud/ipfs/QmeSGXg2WeaAcQ9J1ttWL7r1AoJWHt2TZPeiZCMw7LXSFh?_gl=1*1r47vai*_ga*MTY4NDI2MzAxOC4xNjczMDIxNzcx*_ga_5RMPXG14TE*MTY3NzEyNjk2Ny4yLjEuMTY3NzEyODA0NS42MC4wLjA.
https://sparklink.mypinata.cloud/ipfs/QmaH7o9RQxA1wUs283bFn1hxXzA7WKwSeAoDbFo8oSRP7b?_gl=1*1r47vai*_ga*MTY4NDI2MzAxOC4xNjczMDIxNzcx*_ga_5RMPXG14TE*MTY3NzEyNjk2Ny4yLjEuMTY3NzEyODA0NS42MC4wLjA.
https://sparklink.mypinata.cloud/ipfs/QmfFgPHGFThrp9TaFi7Hy4afdamY2vv8iAaZypHDLFmo5G?_gl=1*1r47vai*_ga*MTY4NDI2MzAxOC4xNjczMDIxNzcx*_ga_5RMPXG14TE*MTY3NzEyNjk2Ny4yLjEuMTY3NzEyODA0NS42MC4wLjA.
https://sparklink.mypinata.cloud/ipfs/Qma3Lo8apbvN2A4cvGyJZC2aFdU2svEyqtabTnM1sHGWkJ?_gl=1*1r47vai*_ga*MTY4NDI2MzAxOC4xNjczMDIxNzcx*_ga_5RMPXG14TE*MTY3NzEyNjk2Ny4yLjEuMTY3NzEyODA0NS42MC4wLjA.
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [ ] I confirm

### If you chose not to confirm, what was the reason

```text
The Dapp has a unlock function, in this function, partial files can only be seen through “pay to unlock”. Files are encrypted using asymmetric encryption， just only the file which selected this function, this is an important feature of the product.
```

### What is the expected retrieval frequency for this data

Weekly

### For how long do you plan to keep this dataset stored on Filecoin

More than 3 years

### In which geographies do you plan on making storage deals

Asia other than Greater China, Africa, North America, South America, Europe, Australia (continent), Antarctica

### How will you be distributing your data to storage providers

HTTP or FTP server

### How do you plan to choose storage providers

Slack, Big data exchange

### If you answered "Others" in the previous question, what is the tool or platform you plan to use

```text
No response
```

### If you already have a list of storage providers to work with, fill out their names and provider IDs below

```text
No response
```

### How do you plan to make deals to your storage providers

Boost client, Lotus client, Singularity

### If you answered "Others/custom tool" in the previous question, enter the details here

```text
No response
```

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Looking at your application i have some questions:
Can you show us visible proof of the size of your data and the storage systems you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230337462961356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!

**Comment by Erreth-Akbe** [comment]
We have completed the documentation, the proof about the size of the stored data, and since we used pinata's service before, all we have are the CIDs of these files, and I can list them below, along with the pinata debit records.
![cdcf84134ca50ff4b5af13dabb6324b](https://user-images.githubusercontent.com/43749085/221485656-61de13b5-9185-4104-a7ea-91936b434c0e.png)
QmSnBxzqunw9xWBHGmV7Mkoq2dBrGWxgcFhKzyYg355Kbb
QmTQhGVnL8bSrZNVg5ZqgSN3YXW5bHRrs8PCi8xZGpWCCx
QmURYSDPFYpE7ABK4zhWw2YNtwrtvtxK9zzWQ8roScTuE5
QmWWJHVM26pa7mWwYckNzrPAVbZbD3cZwXJZfKcRKc1XZv
QmeSGXg2WeaAcQ9J1ttWL7r1AoJWHt2TZPeiZCMw7LXSFh
If you need the complete CID of all our files we can crawl and export them, but a large part of the files are AES symmetric encrypted

**Comment by cryptowhizzard** [comment]
Good morning.

Thanks for sending me the data and KYC.

I am missing the data onboarding plan ( Sp's you are going to use ). Please let me know when you are ready so i can check them followed by a propose when they are ok.

**Comment by Sunnyiscoming** [comment]
I think maybe the dataset you want to store is more suitable for applying for E-Fil+. 
@kevzak Hope you can give him a hand.

**Comment by Erreth-Akbe** [comment]
Sorry I didn't explain clearly, to be precise only part of the file is AES encrypted, in our DAPP, the generated json when uploading these are certainly not encrypted, and then there will be a file attached to the json, it can choose whether aes encrypted, we now only about 1/4 of the NFT works choose to encrypt the release.

**Comment by Erreth-Akbe** [comment]
And the data we store is the user's data, in fact, the data that is accessed at high frequencies. For example, if a user stores an encrypted file, our server will detect whether another user has purchased this one user's NFT, and if so, we will distribute a decryption key to him. So it's actually high frequency access.

**Comment by Sunnyiscoming** [comment]
But Large dataset is open for totally public data without any encrypted file. Can you tell me how much totally public data do you have?

**Comment by Sunnyiscoming** [comment]
Any update here?

**Comment by Erreth-Akbe** [comment]
Now we choose the filplus service only to store public data, because it is more cost-effective than indirectly using ipfs in pinata. The storage space is determined according to the number of times the user uses it. Calculated according to the average number of times of use, it will take about 50T per week.  And we only store unencrypted data in this part of the space.

**Comment by Erreth-Akbe** [comment]
If you want to see more proofs, you can also search for our contract address on any NFT platform to see the NFT data generated by users.  We have user records on BSC, ETH, POLYGON.

**Comment by Sunnyiscoming** [comment]
Large dataset applications are open to existing public datasets. Can you tell me how much data you already have?

**Comment by Erreth-Akbe** [comment]
We are currently using the pinata service to indirectly store hundreds of T data and are adding more data every day.

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 2PiB

**Expected weekly DataCap usage rate**
> 50TiB

**Client address**
>f1hjiip3jr6u4a5wgrktfyvgtqrmf3xyxbhpcvbki

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 2PiB

**Expected weekly DataCap usage rate**
> 50TiB

**Client address**
>f1hjiip3jr6u4a5wgrktfyvgtqrmf3xyxbhpcvbki

**Comment by simonkim0515** [comment]
## Datacap Request Trigger

#### Total DataCap requested 
> 2PiB

#### Expected weekly DataCap usage rate 
> 50TiB 

#### Client address
> f1hjiip3jr6u4a5wgrktfyvgtqrmf3xyxbhpcvbki

**Comment by Erreth-Akbe** [comment]
Thank you！

**Comment by cryptowhizzard** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedo5tllfhtmt2iwl7tz3fzd5m2ialyp5kdmfoxo3i6t76jja4pv7k 
#### Address 
> f1hjiip3jr6u4a5wgrktfyvgtqrmf3xyxbhpcvbki
#### Datacap Allocated
> 25.00TiB
#### Signer Address
> f1krmypm4uoxxf3g7okrwtrahlmpcph3y7rbqqgfa
#### Id
> 38510d49-3f75-4e53-ac9d-872ab134efbf
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedo5tllfhtmt2iwl7tz3fzd5m2ialyp5kdmfoxo3i6t76jja4pv7k

**Comment by sxxfuture-official** [comment]
Thanks for your application ~
As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.
Hope you can answer the following two questions :
- send a confirmation email to [filplus-app-review@fil.org](mailto:filplus-app-review@fil.org) （also send to [kyc@sxxfuture.com](mailto:kyc@sxxfuture.com)）using the email address of your domain '@sparklink.io', the mail content should contains the current LDN handle.
- Please disclose your next sealing plan, such as SPs and their distribution areas.

**Comment by Erreth-Akbe** [comment]
> 
Sorry we don't have a mail service set up for this domain, what should I do in this case, can I use the official contract deployment wallet address for signature verification? Or provide some other information, for example, you can see that the owner of the official github org is my github account.

**Comment by Erreth-Akbe** [comment]
f02009673 
f02008876 
f02008883 
f02012674 

The sealing plan is in Asia minus GCR and Greater China SPs.

**Comment by sxxfuture-official** [comment]
>We have replied to your Twitter account through our official account for verification, please confirm： 
  https://twitter.com/sxxfuture/status/1638450562126729219
 Received your sealing plan, bug twitter reply not found yet. 
 Or you can use the official twitter @@SparkLink_io to post a kyc message, and I will sign it for you this round.

**Comment by sxxfuture-official** [comment]
![img_v2_c4678303-3f40-462a-a225-9556565185bg](https://user-images.githubusercontent.com/113963951/227418764-0fbfb3d1-6670-4d64-b9b4-1e7e65880b7d.jpg)

OK, i found it

**Comment by sxxfuture-official** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceapyp7xkaeunbgg3flazepnh54ozxzlommsaapoyjyrve7ichwcpa 
#### Address 
> f1hjiip3jr6u4a5wgrktfyvgtqrmf3xyxbhpcvbki
#### Datacap Allocated
> 25.00TiB
#### Signer Address
> f1foiomqlmoshpuxm6aie4xysffqezkjnokgwcecq
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceapyp7xkaeunbgg3flazepnh54ozxzlommsaapoyjyrve7ichwcpa

**Comment by herrehesse** [comment]
checker:manualTrigger

**Comment by spaceT9** [comment]
checker:manualTrigger

**Comment by spaceT9** [comment]
retrieval rate too low, need to be improved

**Comment by Aaron01230** [comment]
checker:manualTrigger

**Comment by Aaron01230** [comment]
checker:manualTrigger

**Comment by a1991car** [comment]
checker:manualTrigger

**Comment by a1991car** [comment]
Retrieving backups doesn't look great and needs to be improved, but the retrieval rate is improving, which is an improvement. Considering this is only the second round, and the first round is only 25T, I support it for now

**Comment by a1991car** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecena3rjzw2nqhmi6fwr5rabi4zr4lbu2bl52idh4zbtkdbt2znx4 
#### Address 
> f1hjiip3jr6u4a5wgrktfyvgtqrmf3xyxbhpcvbki
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1qnumecdypgrbaebtkdfjnwt5ndacadcuas3deiq
#### Id
> 0e78dad5-d61d-428b-8397-37757d499f9e
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecena3rjzw2nqhmi6fwr5rabi4zr4lbu2bl52idh4zbtkdbt2znx4

**Comment by Aaron01230** [comment]
<img width="1259" alt="image" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/107668727/3ae60dc2-a076-4a5a-bb85-288de9b5042e">

Retrieval rate is improving, from here(https://datacapstats.io/clients/f02031033/breakdown) the data distribution statistics shown in the report are not accurate, I will support this round

**Comment by Aaron01230** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceave2kqxsz2mx7gqdlpcktkr7pdzmfooy7frlmgwb6e24ek4obwag 
#### Address 
> f1hjiip3jr6u4a5wgrktfyvgtqrmf3xyxbhpcvbki
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1xrnysd4gimg64d4l6qi7ulzwwq22c6vfg6lpw3i
#### Id
> 0e78dad5-d61d-428b-8397-37757d499f9e
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceave2kqxsz2mx7gqdlpcktkr7pdzmfooy7frlmgwb6e24ek4obwag

**Comment by NewHuoPool** [comment]
checker:manualTrigger

**Comment by NewHuoPool** [comment]
With a smaller allocation of the first round, it's understandable that these problems were reported. I will keep an eye on it as the community rules are followed in the later rounds.

**Comment by stcouldlisa** [comment]
checker:manualTrigger

**Comment by kernelogic** [comment]
Seems the client is responsive on the questions other notaries have raised. And the report looks OK for early stages.

**Comment by kernelogic** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedtkc4pqkrbhqgaqrc4oyhbadqnoyjp5getozv5nbapv5ai7iwmq2 
#### Address 
> f1hjiip3jr6u4a5wgrktfyvgtqrmf3xyxbhpcvbki
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### Id
> d0e28f65-ca40-4826-997d-eba4200e6ff8
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedtkc4pqkrbhqgaqrc4oyhbadqnoyjp5getozv5nbapv5ai7iwmq2

**Comment by 1ane-1** [comment]
checker:manualTrigger

**Comment by 1ane-1** [comment]
Hope you can  improve the retrieval success ratio and resolve the deal data dupilication! Support for this round.

**Comment by 1ane-1** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebxl3cus5724jc557i6tyruu7ncaosdeoiclsdycifhxow2z6bpfy 
#### Address 
> f1hjiip3jr6u4a5wgrktfyvgtqrmf3xyxbhpcvbki
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1mdk7s2vntzm6hu35yuo6vjubtrpfnb2awhgvrri
#### Id
> d0e28f65-ca40-4826-997d-eba4200e6ff8
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebxl3cus5724jc557i6tyruu7ncaosdeoiclsdycifhxow2z6bpfy

**Comment by igoovo** [comment]
checker:manualTrigger

**Comment by igoovo** [comment]
The searchability is still very good, and we hope to deploy the http retrieval tool later.
I will give my support in this round, but the relevant warnings should be taken seriously.

**Comment by igoovo** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceatf7ths4bygarovkithbqq5o6dniowxmqgupaczabbm6gbxwsstq 
#### Address 
> f1hjiip3jr6u4a5wgrktfyvgtqrmf3xyxbhpcvbki
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1shnsfayxqll77svffaxnjenms7bbbysbqcatrpy
#### Id
> 98c77fd0-f74d-402c-8814-7f3df3641236
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceatf7ths4bygarovkithbqq5o6dniowxmqgupaczabbm6gbxwsstq

**Comment by psh0691** [comment]
![스크린샷 2023-07-31 11-44-24](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/69004801/0733821c-ca0c-4544-b7b8-5e62b179dbf5)

**Comment by psh0691** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceadshhdytaw5sxhbvkkz7brytkte4faegekh6wjhg77o6uesgdjrg 
#### Address 
> f1hjiip3jr6u4a5wgrktfyvgtqrmf3xyxbhpcvbki
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1qdko4jg25vo35qmyvcrw4ak4fmuu3f5rif2kc7i
#### Id
> 98c77fd0-f74d-402c-8814-7f3df3641236
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceadshhdytaw5sxhbvkkz7brytkte4faegekh6wjhg77o6uesgdjrg

**Comment by kernelogic** [comment]
checker:manualTrigger

**Comment by kernelogic** [comment]
High retrieval success rate, CID distribution also look good.

**Comment by kernelogic** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced3yr5jk3terxzuxc567dds62n2inc65fsagav65gihhbrztn42fw 
#### Address 
> f1hjiip3jr6u4a5wgrktfyvgtqrmf3xyxbhpcvbki
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### Id
> 53fcfc0b-b321-43eb-9a45-7bb8c124c2e7
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced3yr5jk3terxzuxc567dds62n2inc65fsagav65gihhbrztn42fw

**Comment by ipfscn** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb3tpcxdn4kuq3ja4ftn6stqqkxeatnvtjknlvqb4x6vgncpagjca 
#### Address 
> f1hjiip3jr6u4a5wgrktfyvgtqrmf3xyxbhpcvbki
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1j4n74chme7whbz3yls4a7ixqewb6dijypqg2a3a
#### Id
> 53fcfc0b-b321-43eb-9a45-7bb8c124c2e7
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb3tpcxdn4kuq3ja4ftn6stqqkxeatnvtjknlvqb4x6vgncpagjca

**Comment by woshidama323** [comment]
checker:manualTrigger

**Comment by woshidama323** [comment]
Retrieval success rate looks good, CID distribution looks good
and also report LGTM
Will support

**Comment by woshidama323** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebgtk7yw63hxoybjmcxsonxqxvznhihj26na3mdqbbl4qdvckgkzm 
#### Address 
> f1hjiip3jr6u4a5wgrktfyvgtqrmf3xyxbhpcvbki
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f12tk3adljauwnd3hjbigpfxb7b7gdlj63p6afwtq
#### Id
> 732d236a-2f51-4166-9264-572c18699e79
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebgtk7yw63hxoybjmcxsonxqxvznhihj26na3mdqbbl4qdvckgkzm

**Comment by zcfil** [comment]
checker:manualTrigger

**Comment by zcfil** [comment]
The report is very healthy, this round of support! Continue to maintain

**Comment by zcfil** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebh3fs55sztmgijejevjfrrpkquuitfygxti4pfnw7woatnsgjzpu 
#### Address 
> f1hjiip3jr6u4a5wgrktfyvgtqrmf3xyxbhpcvbki
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1cjzbiy5xd4ehera4wmbz63pd5ku4oo7g52cldga
#### Id
> 732d236a-2f51-4166-9264-572c18699e79
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebh3fs55sztmgijejevjfrrpkquuitfygxti4pfnw7woatnsgjzpu

**Comment by Aaron01230** [comment]
checker:manualTrigger

**Comment by SuperChaiChai** [comment]
checker:manualTrigger

**Comment by SuperChaiChai** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedhc6ah3cm6lzqxbm4v5l6uhacwbfboms3kksywzzs3t6yjxyll4u 
#### Address 
> f1hjiip3jr6u4a5wgrktfyvgtqrmf3xyxbhpcvbki
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f12mckci3omexgzoeosjvstcfxfe4vqw7owdia3da
#### Id
> 994bab80-6492-4fb7-90c2-102f40e71089
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedhc6ah3cm6lzqxbm4v5l6uhacwbfboms3kksywzzs3t6yjxyll4u

**Comment by a1991car** [comment]
checker:manualTrigger

**Comment by a1991car** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecpohhjqjg564pxf4yzltl4dfqi7jxmtzn4plwvbgt3drfxbdpzqg 
#### Address 
> f1hjiip3jr6u4a5wgrktfyvgtqrmf3xyxbhpcvbki
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1qnumecdypgrbaebtkdfjnwt5ndacadcuas3deiq
#### Id
> 994bab80-6492-4fb7-90c2-102f40e71089
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecpohhjqjg564pxf4yzltl4dfqi7jxmtzn4plwvbgt3drfxbdpzqg

**Comment by AlanGreaterheat** [comment]
checker:manualTrigger

**Comment by AlanGreaterheat** [comment]
Please note the dispersion！

**Comment by AlanGreaterheat** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebq7ty4egfmmfjnyco7ayy5sbte6qtri3pm2nt3f77lw6v246w6h2 
#### Address 
> f1hjiip3jr6u4a5wgrktfyvgtqrmf3xyxbhpcvbki
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1pnmzlxj7cfeo2v6oj5nco46hkg2l46wj7o4xxui
#### Id
> 6a8a467d-0ddc-47c0-a989-b617558b3adc
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebq7ty4egfmmfjnyco7ayy5sbte6qtri3pm2nt3f77lw6v246w6h2

**Comment by spaceT9** [comment]
please be noted that Storage provider should not be storing duplicate data for more than 20%.

**Comment by nj-steve** [comment]
checker:manualTrigger

**Comment by nj-steve** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecmmvjychg727fti2gzi53vyzukbeelciyksbhjqd242dw7offilg 
#### Address 
> f1hjiip3jr6u4a5wgrktfyvgtqrmf3xyxbhpcvbki
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1xx6555qijma7igpnjspyvdunc4vfxkawnpqy5ii
#### Id
> 6a8a467d-0ddc-47c0-a989-b617558b3adc
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecmmvjychg727fti2gzi53vyzukbeelciyksbhjqd242dw7offilg

**Comment by cryptowhizzard** [comment]
Dear Erreth-Akbe,

As notary I am doing due diligence on your LDN. I could not get retrieval to work. Can you please upload the car file of CID baga6ea4seaqosyc7yhrcngdhympljl4d7xuy4uwpb4ceghvehkeejrl4o6rmuea ?

You can use our upload system at http://send.datasetcreators.com. Please select 7 days for the system to keep the file and post the link you received here so I (and other notaries) can download your content.

**Comment by Aaron01230** [comment]
checker:manualTrigger

**Comment by cryptowhizzard** [comment]
![Scherm­afbeelding 2023-09-15 om 14 20 40](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/36404435/1396cfa1-fc26-473c-82f3-7acc4f8dade2)

Please note , many providers are offline in this LDN. @Erreth-Akbe please contact them and have them bring their SP's online again for retrieval.

**Comment by cryptowhizzard** [comment]
> Dear Erreth-Akbe,
> 
> As notary I am doing due diligence on your LDN. I could not get retrieval to work. Can you please upload the car file of CID baga6ea4seaqosyc7yhrcngdhympljl4d7xuy4uwpb4ceghvehkeejrl4o6rmuea ?
> 
> You can use our upload system at http://send.datasetcreators.com. Please select 7 days for the system to keep the file and post the link you received here so I (and other notaries) can download your content.

Reminder!

**Comment by Sunnyiscoming** [comment]
Hello, @Erreth-Akbe  per the https://github.com/filecoin-project/notary-governance/issues/922 for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

This information will be reviewed by Fil+ Governance team to confirm validity and then the application will be allowed to move forward for additional notary review.
