### ISSUE TITLE
[DataCap Application] <Makeshop> - <Online mall Product Reference> 

### ISSUE THREAD

**Issue by makeshop102** [filecoin-project/filecoin-plus-large-datasets#1673]
### Data Owner Name

Makeshop

### Data Owner Country/Region

Korea, Republic of

### Data Owner Industry

IT & Technology Services

### Website

https://makeshop.co.kr/

### Social Media

```text
http://blog.naver.com/NBlogTop.naver?isHttpsRedirect=true&blogId=mbreed
```

### Total amount of DataCap being requested

3PiB

### Weekly allocation of DataCap requested

200TiB

### On-chain address for first allocation

f1xgnvm2pkwsw6tmj2vh5dkrsmnq2r7bm5s5cr7ui

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Makeshop provides the solution of building a online shopping mall to support starts-up and small enterprises. We are leading the No. 1 shopping mall solution since 2007 in South Korea. 
MakeShop make customer easy to manage their client and provide ideal method to grow sales, and support mobile shopping mall tool too. Technically it’s all-in-one solution for building online shopping mall.  
In addition, MakeShop, a government-recognized as information protection leader, provides a stable solution and server environment so that you can only focus on shopping mall operations without worrying about hacking or external attacks.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
The pictures, videos from global magazines like vogue, marie claire, eile, and etc., 
As one of the shopping mall management methods in the Retail Field, we make a the product detail page by referring to a video or model pictures of global magazines.
The dataset should be shared and stored by both our product managers and our customers who operate their own online shopping malls. 
So, we want to decentralize these references including images and video so that we all can easily retrieve.
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### Please share a sample of the data

```text
https://drive.google.com/drive/folders/11s06RHE2CRDanKZaA12aghTwm6DlcPgK?usp=sharing
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Weekly

### For how long do you plan to keep this dataset stored on Filecoin

2 to 3 years

### In which geographies do you plan on making storage deals

Asia other than Greater China, North America, Europe

### How will you be distributing your data to storage providers

HTTP or FTP server, IPFS

### How do you plan to choose storage providers

Slack, Filmine

### How do you plan to make deals to your storage providers

Boost client, Lotus client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Looking at your application i have some questions:
As you are brand new on Github and have no history of past applications it seems to me that applying for 3PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?

Can you show us visible proof of the size of your data and the storage systems you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230337462961356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!

**Comment by cryptowhizzard** [comment]
Thanks!

Well received and ok. When the datacap is triggered by PL i will propropose.

**Comment by Sunnyiscoming** [comment]
The pictures, videos from global magazines like vogue, marie claire, eile, and etc., 
I want to know whether these data are authorized to store as public data on Filecoin network?

**Comment by makeshop102** [comment]
@Sunnyiscoming 
I mentioned global magazines to make you understand my project. 
We refer not only these magazines, also various open resources of fashion related contents. 
The data are only references, not for commercial purposes.

**Comment by Sunnyiscoming** [comment]
Could you send an email to filplus-app-review@fil.org with your official domain in order to confirm your identity? Email name should includes the issue id #1673.

**Comment by makeshop102** [comment]
@Sunnyiscoming Our company uses Gmail as our business account. Just sent the mail though.

**Comment by cryptowhizzard** [comment]
@Sunnyiscoming 

Can you prompt RKH to trigger here please? We performed KYC + data onboarding plan. I would like to propose.

**Comment by Sunnyiscoming** [comment]
![image](https://user-images.githubusercontent.com/105098820/222951642-40443d03-afef-4b3d-b593-713e282f3617.png)
Maybe gmail is not ok. Because your organization has published email on the website.

**Comment by Sunnyiscoming** [comment]
Any update here?

**Comment by Sunnyiscoming** [comment]
@makeshop102 Any feedback?

**Comment by Sunnyiscoming** [comment]
You can reopen it when you want to apply again.
