### ISSUE TITLE
[DataCap Application] Genome Ark

### ISSUE THREAD

**Issue by Micaucas** [filecoin-project/filecoin-plus-large-datasets#1678]
### Data Owner Name

Genome 10K Community of Scientists

### Data Owner Country/Region

United States

### Data Owner Industry

Life Science / Healthcare

### Website

https://genome10k.ucsc.edu/

### Social Media

```text
Twitter: https://twitter.com/genome10k
Facebook: https://www.facebook.com/genome10k/
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

400TiB

### On-chain address for first allocation

f1pt35xbg63qo4kwomz6monedjst2yqd5pdfw4lpa

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
The Genome 10K Organization is a community of scientists dedicated to the preservation and understanding of genetic diversity in the animal species on our planet. We organize and facilitate projects, such as the Bat 1K, the Bird 10K, and our flagship, the Vertebrate Genomes Project, to sequence the genomes from as many animals as possible, while partnering with sister projects such as the Earth Biogenome Project, the Insect 5K (i5K), and the GIGA – Global Invertebrate Genomics Alliance. Our goal is to assemble a genomic zoo that will live forever as a basis for the science and preservation of life.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
The Genome Ark hosts genomic information for the Vertebrate Genomes Project (VGP) and other related projects. The VGP is an international collaboration that aims to generate complete and near error-free reference genomes for all extant vertebrate species. These genomes will be used to address fundamental questions in biology and disease, to identify species most genetically at risk for extinction, and to preserve genetic information of life.
Total: 583.8TiB
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### How do you plan to prepare the dataset

lotus, I don't know yet

### Please share a sample of the data

```text
https://registry.opendata.aws/genomeark/
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Sporadic

### For how long do you plan to keep this dataset stored on Filecoin

More than 3 years

### In which geographies do you plan on making storage deals

Asia other than Greater China, North America, Europe

### How will you be distributing your data to storage providers

HTTP or FTP server, IPFS, Shipping hard drives, I don't know yet

### How do you plan to choose storage providers

Slack, Filmine, Big data exchange, I don't know yet

### How do you plan to make deals to your storage providers

Boost client, Lotus client, I don't know yet

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by sklay** [comment]
ok

**Comment by sklay** [comment]
> Thanks

Thanks

**Comment by sklay** [comment]
> > Thanks
> 
> Thanks

Thanks

**Comment by sklay** [comment]
> > > Thanks
> > 
> > 
> > Thanks
> 
> Thanks

1441546860

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Looking at your application i have some questions:
As you are brand new on Github and have no history of past applications it seems to me that applying for 5PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?

Can you show us visible proof of the size of your data and the storage systems you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230337462961356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!

**Comment by Sunnyiscoming** [comment]
Could you send an email to filplus-app-review@fil.org with your official domain in order to confirm your identity? Email name should includes the issue id #1678.

**Comment by Micaucas** [comment]
@cryptowhizzard Hello, since I haven't contacted the sp, I can't fill out the form yet. Thank you!

**Comment by Micaucas** [comment]
@Sunnyiscoming Hello, I'm an individual sp. And I will continue to participate in the test of FVM.

**Comment by Sunnyiscoming** [comment]
> Weekly allocation of DataCap requested
> 400TiB

Can you give more detailed plan about sps you will cooperate with?

**Comment by Micaucas** [comment]
@Sunnyiscoming OK. I'm contacting several SPs for this dataset storing. Our communication is in process.

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 5PiB

**Expected weekly DataCap usage rate**
> 400TiB

**Client address**
>f1pt35xbg63qo4kwomz6monedjst2yqd5pdfw4lpa

**Comment by PangodGroup** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebnvxxdlguynp3zap4hs37lqkimo7zdxu5hynmkb3rly4kdehry5c 
#### Address 
> f1pt35xbg63qo4kwomz6monedjst2yqd5pdfw4lpa
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1d4yb3wags3mtddzesxoo63jv7dmlec3bq4yteni
#### Id
> 1ed641a8-a926-43cc-a525-3ee23cb7b6e2
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebnvxxdlguynp3zap4hs37lqkimo7zdxu5hynmkb3rly4kdehry5c

**Comment by Meibuy** [comment]
![1678941743161](https://user-images.githubusercontent.com/108273047/225516381-87069a47-4e0b-4936-b01a-1251b8fa6741.png)

Based on the datacap and cid checks, the application meets the expected community requirements. I hope you can reach the decentralization goal as soon as possible. If you have trouble finding sp, try slack channel such as fil-deal-market or filmine platform.

**Comment by Protocan** [comment]
Looks normal and acceptable, willing to support.

**Comment by Protocan** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedgxdv7um7tr54mg5ct47xeevi7fizfp7nr225iadrzweimuo2m5m 
#### Address 
> f1pt35xbg63qo4kwomz6monedjst2yqd5pdfw4lpa
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1vxbqrf7rfum3n6m5u6eb4re6xj7amvsaqnzu64y
#### Id
> 136c6a59-2c29-45f8-98f8-9d5321d6969c
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedgxdv7um7tr54mg5ct47xeevi7fizfp7nr225iadrzweimuo2m5m

**Comment by Meibuy** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaiwpvsaqv6go6rfcxfkv47wsf65onqnkpeaglu5tbsqm7lm5si76 
#### Address 
> f1pt35xbg63qo4kwomz6monedjst2yqd5pdfw4lpa
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1bwugfihrmn3iyunzyxst5nttql3dge4khwmurtq
#### Id
> 136c6a59-2c29-45f8-98f8-9d5321d6969c
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaiwpvsaqv6go6rfcxfkv47wsf65onqnkpeaglu5tbsqm7lm5si76

**Comment by TakiChain** [comment]
CID checker and Retrieval can be done. Willing to suport!

**Comment by TakiChain** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced23w2uuo5ska7oklpbttclfdvkab5xewtcpuntok2my5vgmrnn3u 
#### Address 
> f1pt35xbg63qo4kwomz6monedjst2yqd5pdfw4lpa
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f15impf3j2zcaex4lhyxndxswuuhv24vzstuqtxsi
#### Id
> 7f6391fd-ad19-46ca-8fcd-9a638533d79d
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced23w2uuo5ska7oklpbttclfdvkab5xewtcpuntok2my5vgmrnn3u

**Comment by Meibuy** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecbztqkdxbredg5nvqidrmxmugnpns2aa7ymppmg7htjl4k7sce34 
#### Address 
> f1pt35xbg63qo4kwomz6monedjst2yqd5pdfw4lpa
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1bwugfihrmn3iyunzyxst5nttql3dge4khwmurtq
#### Id
> 7f6391fd-ad19-46ca-8fcd-9a638533d79d
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecbztqkdxbredg5nvqidrmxmugnpns2aa7ymppmg7htjl4k7sce34

**Comment by Suyanj** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebfqz2bj4vw2zotbvw6lashefhy7lhll5ewl3fjia7mzbwscwspfs 
#### Address 
> f1pt35xbg63qo4kwomz6monedjst2yqd5pdfw4lpa
#### Datacap Allocated
> 1.56PiB
#### Signer Address
> f1ihv7gz3vn3xqvikpt4rwryecgisl7745lodx3yi
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebfqz2bj4vw2zotbvw6lashefhy7lhll5ewl3fjia7mzbwscwspfs

**Comment by TakiChain** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebesmbxwiigob6b7yx5tvwow3lyanzx5zefc53elaispnxi27mcks 
#### Address 
> f1pt35xbg63qo4kwomz6monedjst2yqd5pdfw4lpa
#### Datacap Allocated
> 1.56PiB
#### Signer Address
> f15impf3j2zcaex4lhyxndxswuuhv24vzstuqtxsi
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebesmbxwiigob6b7yx5tvwow3lyanzx5zefc53elaispnxi27mcks

**Comment by kevzak** [comment]
checker:manualTrigger

**Comment by spaceT9** [comment]
rerieval rate too low to sign

**Comment by spaceT9** [comment]
checker:manualTrigger

**Comment by Micaucas** [comment]
checker:manualTrigger

**Comment by Bennyyangpu** [comment]
checker:manualTrigger

**Comment by Bennyyangpu** [comment]
![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/107031628/9d5905cf-f79b-4578-9ee2-115aff87860d)
 LGTM, willing to support.

**Comment by Bennyyangpu** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec7235prf57tno5wmbaqkssailj34sxc24tv6eg43hnzrbjcmv2wy 
#### Address 
> f1pt35xbg63qo4kwomz6monedjst2yqd5pdfw4lpa
#### Datacap Allocated
> 1.56PiB
#### Signer Address
> f174fg3bqbln3zjnkxtyf6s54txqkr7yqkj6cig7y
#### Id
> 76f3a889-adee-432e-bb27-c4fdcdd1b769
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec7235prf57tno5wmbaqkssailj34sxc24tv6eg43hnzrbjcmv2wy

**Comment by Meibuy** [comment]
Basically acceptable, but need to improve Deal Data Replication in the next round.

**Comment by Meibuy** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecfydrjk2pql2hg3hksdgnreqqsrb3ftcbbrdxlvxr3c3wl7quf5m 
#### Address 
> f1pt35xbg63qo4kwomz6monedjst2yqd5pdfw4lpa
#### Datacap Allocated
> 1.56PiB
#### Signer Address
> f1bwugfihrmn3iyunzyxst5nttql3dge4khwmurtq
#### Id
> 76f3a889-adee-432e-bb27-c4fdcdd1b769
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecfydrjk2pql2hg3hksdgnreqqsrb3ftcbbrdxlvxr3c3wl7quf5m

**Comment by clriesco** [comment]
Removed stale label and reopened issue :)

**Comment by cryptowhizzard** [comment]
Dear Micaucas,

As notary I am doing due diligence on your LDN. I could not get retrieval to work. Can you please upload the car file of CID baga6ea4seaqfzwbbsishtsobdiuzr46s5kjqp4oyknrfj4sivbb5ttenq5eqwmy ?

You can use our upload system at http://send.datasetcreators.com. Please select 7 days for the system to keep the file and post the link you received here so I (and other notaries) can download your content.

**Comment by Micaucas** [comment]
Yes

**Comment by Micaucas** [comment]
Thanks for the comment.

**Comment by Micaucas** [comment]
Yes of course!

**Comment by Micaucas** [comment]
Yes of course!

**Comment by Micaucas** [comment]
Thanks for the comment.

**Comment by herrehesse** [comment]
checker:manualTrigger

**Comment by herrehesse** [comment]
All storage in same region, most with VPN, highly likely self-dealing.

Requesting closure.

**Comment by Micaucas** [comment]
No VPN. All of the SPs are different.

**Comment by Sunnyiscoming** [comment]
Hello, @Micaucas per the https://github.com/filecoin-project/notary-governance/issues/922 for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

This information will be reviewed by Fil+ Governance team to confirm validity and then the application will be allowed to move forward for additional notary review.

**Comment by herrehesse** [comment]
checker:manualTrigger

**Comment by herrehesse** [comment]
<img width="1495" alt="Screenshot 2023-11-29 at 09 27 15" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/70132857/2bdc96a2-0dd0-4249-bd67-511665fb5d76">

![Screenshot 2023-11-29 at 09 27 32](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/70132857/f60a0a38-c998-4528-996d-d0d6c33f60e3)

Most of the above miners are flagged on MASSIVE amounts of abuse on flagged LDN's. We can and should not support these entities with datacap and growth. Also self-dealing, lying about entity and names and have the same funding wallets.

@Filplus-govteam Close this asap.

![Screenshot 2023-11-29 at 09 29 28](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/70132857/82f19ca1-5220-43cd-84a2-eca145030e0f)

**Comment by Filplus-govteam** [comment]
Closing until clear list of SP entities and distributed location is provided.
