### ISSUE TITLE
[DataCap Application] ZINC Database Project 1

### ISSUE THREAD

**Issue by WisseHeyne** [filecoin-project/filecoin-plus-large-datasets#1680]
### Data Owner Name

John Irwin---Irwin Lab @USCF

### Data Owner Country/Region

United States

### Data Owner Industry

Life Science / Healthcare

### Website

https://registry.opendata.aws/zinc15/

### Social Media

```text
https://irwinlab.compbio.ucsf.edu/
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

400TiB

### On-chain address for first allocation

f1anpyrkoyzqxsv3glkjsvdnyiols7p4cajtwax7a

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Irwin Lab develops software tools and databases to help discover small molecules for biology. They use their own software and databases for their own research, which helps focus our attention on making the tools pragmatic.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
3D models for molecular docking screens. ZINC is provided by the Irwin and Shoichet Laboratories in the Department of Pharmaceutical Chemistry at the University of California, San Francisco (UCSF).
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### How do you plan to prepare the dataset

lotus, singularity

### Please share a sample of the data

```text
https://registry.opendata.aws/zinc15/
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

2 to 3 years

### In which geographies do you plan on making storage deals

Asia other than Greater China, North America, South America, Europe

### How will you be distributing your data to storage providers

HTTP or FTP server, Shipping hard drives

### How do you plan to choose storage providers

Slack, Filmine, Big data exchange

### How do you plan to make deals to your storage providers

Boost client, Lotus client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by lvschouwen** [comment]
Hi @WisseHeyne 

This dataset is close to 1 PiB big
```
lucas@toolbox:~$ aws s3 ls --no-sign-request s3://zinc3d --recursive --human-readable --summarize
Total Objects: 5432244
   Total Size: 924.5 TiB
```

How many times do you plan to store this set?

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Looking at your application i have some questions:
As you are brand new on Github and have no history of past applications it seems to me that applying for 5PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?

Can you show us visible proof of the size of your data and the storage systems you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230337462961356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!

**Comment by kernelogic** [comment]
@WisseHeyne this dataset has license issue. You cannot re-distribute it without owner's permission. I have tried it and couldn't get the permission. Unless you have obtained permission?

**Comment by kernelogic** [comment]
See here https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/842#issuecomment-1246059638

**Comment by WisseHeyne** [comment]
@kernelogic Thank you! I don't know about it before I downloaded the dataset. Closing this as I did not get the author's approval to redistribute.
