### ISSUE TITLE
[DataCap Application] <OriginStorage> <NOAA Geostationary Operational Environmental Satellites (GOES) 16, 17 & 18> - (2/3) 

### ISSUE THREAD

**Issue by Tom-OriginStorage** [filecoin-project/filecoin-plus-large-datasets#1681]
### Data Owner Name

National Oceanic and Atmospheric Administration

### Data Owner Country/Region

United States

### Data Owner Industry

Life Science / Healthcare

### Website

https://registry.opendata.aws/noaa-goes .

### Social Media

```text
https://github.com/awslabs/open-data-docs/tree/main/docs/noaa/noaa-goes16
https://registry.opendata.aws/noaa-goes .
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

400TiB

### On-chain address for first allocation

f1nqngcxaslai77fbzxpk2n2ggnltuk7uktgk7cei

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
NEW GOES-18 Data!!! GOES-18 is now provisional and data has began streaming. Data files will be available between Provisional and the Operational Declaration of the satellite, however, data will have the caveat GOES-18 Preliminary, Non-Operational Data. The exception is during the interleave period when ABI Radiances and Cloud and Moisture Imagery data will be shared operationally via the NOAA Open Data Dissemination Program. GOES satellites (GOES-16, GOES-17, & GOES-18) provide continuous weather imagery and monitoring of meteorological and space environment data across North America. GOES satellites provide the kind of continuous monitoring necessary for intensive data analysis. They hover continuously over one position on the surface. The satellites orbit high enough to allow for a full-disc view of the Earth. Because they stay above a fixed spot on the surface, they provide a constant vigil for the atmospheric "triggers" for severe weather conditions such as tornadoes, flash floods, hailstorms, and hurricanes. When these conditions develop, the GOES satellites are able to monitor storm development and track their movements. SUVI products available in both NetCDF and FITS.
```

### Is this project associated with other projects/ecosystem stakeholders?

Yes

### Describe the data being stored onto Filecoin

```text
NEW GOES-18 Data!!! GOES-18 is now provisional and data has began streaming. Data files will be available between Provisional and the Operational Declaration of the satellite, however, data will have the caveat GOES-18 Preliminary, Non-Operational Data. The exception is during the interleave period when ABI Radiances and Cloud and Moisture Imagery data will be shared operationally via the NOAA Open Data Dissemination Program. GOES satellites (GOES-16, GOES-17, & GOES-18) provide continuous weather imagery and monitoring of meteorological and space environment data across North America. GOES satellites provide the kind of continuous monitoring necessary for intensive data analysis. They hover continuously over one position on the surface. The satellites orbit high enough to allow for a full-disc view of the Earth. Because they stay above a fixed spot on the surface, they provide a constant vigil for the atmospheric "triggers" for severe weather conditions such as tornadoes, flash floods, hailstorms, and hurricanes. When these conditions develop, the GOES satellites are able to monitor storm development and track their movements. SUVI products available in both NetCDF and FITS.
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### How do you plan to prepare the dataset

lotus

### Please share a sample of the data

```text
2023-01-10 23:46:16    4.7 MiB SUVI-L1b-He303/2023/010/15/OR_SUVI-L1b-He303_G17_s20230101545352_e20230101545362_c20230101545546.fits
2023-01-10 23:46:15    4.8 MiB SUVI-L1b-He303/2023/010/15/OR_SUVI-L1b-He303_G17_s20230101545352_e20230101545362_c20230101545546.nc
2023-01-10 23:46:16    4.7 MiB SUVI-L1b-He303/2023/010/15/OR_SUVI-L1b-He303_G17_s20230101545443_e20230101545443_c20230101546044.fits
2023-01-10 23:46:15    4.8 MiB SUVI-L1b-He303/2023/010/15/OR_SUVI-L1b-He303_G17_s20230101545443_e20230101545443_c20230101546044.nc
2023-01-10 23:47:41    4.7 MiB SUVI-L1b-He303/2023/010/15/OR_SUVI-L1b-He303_G17_s20230101547043_e20230101547043_c20230101547247.fits
2023-01-10 23:47:42    4.8 MiB SUVI-L1b-He303/2023/010/15/OR_SUVI-L1b-He303_G17_s20230101547043_e20230101547043_c20230101547247.nc
2021-09-28 03:48:15   31.6 KiB index.html
Total Objects: 237687110
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

1.5 to 2 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, South America

### How will you be distributing your data to storage providers

Cloud storage (i.e. S3)

### How do you plan to choose storage providers

Slack, Big data exchange

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 5PiB

**Expected weekly DataCap usage rate**
> 400TiB

**Client address**
>f1nqngcxaslai77fbzxpk2n2ggnltuk7uktgk7cei

**Comment by Bitrise0111** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceai25j7mglcymebnid6fewpytvsdkjmfpniam4szr5mwl2wacmaa2 
#### Address 
> f1nqngcxaslai77fbzxpk2n2ggnltuk7uktgk7cei
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1nknj7ayq4o43czrtdoauggtwl43fbqatmqis3yy
#### Id
> fd1f15c2-859a-4ac3-9700-8e8d89602b42
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceai25j7mglcymebnid6fewpytvsdkjmfpniam4szr5mwl2wacmaa2

**Comment by 1ane-1** [comment]
Can you provide more detailed information about other storage providers participated in this program, such as you can list SPs you have contacted with at present?

**Comment by Tom-OriginStorage** [comment]
Hello, notary , the SP we are currently contacting is as follows
f01914268
f02006841
f01896036
f02024315
f02013434
f02029895
f02030031
f01170282
f02044834
f02041085
f02050599
f02046736
f02056391
f02048990
f02042992
f02055638
Thank you, I hope you can sign for me

**Comment by 1ane-1** [comment]
> Hello, notary , the SP we are currently contacting is as follows f01914268 f02006841 f01896036 f02024315 f02013434 f02029895 f02030031 f01170282 f02044834 f02041085 f02050599 f02046736 f02056391 f02048990 f02042992 f02055638 Thank you, I hope you can sign for me

For the first round, i will support you and follow you in next steps.

**Comment by 1ane-1** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaiqkpd2ibwr5rxuswghcysvwbbfi3h2xmwvlhjfc4plpxbncr6zu 
#### Address 
> f1nqngcxaslai77fbzxpk2n2ggnltuk7uktgk7cei
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1mdk7s2vntzm6hu35yuo6vjubtrpfnb2awhgvrri
#### Id
> fd1f15c2-859a-4ac3-9700-8e8d89602b42
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaiqkpd2ibwr5rxuswghcysvwbbfi3h2xmwvlhjfc4plpxbncr6zu

**Comment by SuperChaiChai** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacearkjev3jbol3gg2zk5nl6exkyfltky3zjdeobvpr2gmksmpzc2h4 
#### Address 
> f1nqngcxaslai77fbzxpk2n2ggnltuk7uktgk7cei
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f12mckci3omexgzoeosjvstcfxfe4vqw7owdia3da
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacearkjev3jbol3gg2zk5nl6exkyfltky3zjdeobvpr2gmksmpzc2h4

**Comment by SuperChaiChai** [comment]
![img_v2_dad976a9-0e9b-415e-ba49-bae12163ac2h](https://user-images.githubusercontent.com/42091141/230860527-e44c220e-3312-45a1-bf20-abcf9773502e.jpg)
The data retrieval is normal this time, and I am willing to support it.

**Comment by luobin544** [comment]
<img width="500" alt="WeChat4c5ce6c58fe89affdcc400b90940d38f" src="https://user-images.githubusercontent.com/4277341/230866609-2a98ab94-f9de-4090-843b-187789012b48.png">

**Comment by luobin544** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedon6euwnygdqy37siglx2jpzqcm3wfrisirphtwjaoe2va3qils4 
#### Address 
> f1nqngcxaslai77fbzxpk2n2ggnltuk7uktgk7cei
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1tbd632f6w62glfaf7wjpimacbnjiz26poyoes2q
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedon6euwnygdqy37siglx2jpzqcm3wfrisirphtwjaoe2va3qils4

**Comment by METAVERSEDATAMINING** [comment]
So far everything is in order, support this round

**Comment by METAVERSEDATAMINING** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec4zto4i5hj7xfselljn5pq3onj5kw4ltm3w6a35kgv6xr43eavie 
#### Address 
> f1nqngcxaslai77fbzxpk2n2ggnltuk7uktgk7cei
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f17idrnfnxl2mbgcgr57a6z2c6lj2qx56gvm3336i
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec4zto4i5hj7xfselljn5pq3onj5kw4ltm3w6a35kgv6xr43eavie

**Comment by stcouldlisa** [comment]
lotus client retrieve --provider f02064089 QmR5ZmwiVsNKoN4krdex9EXktQNJtKQGNbVG8xLzuHj3qa QmR5ZmwiVsNKoN4krdex9EXktQNJtKQGNbVG8xLzuHj3qa.car
![WechatIMG3237](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/112812896/84092152-c8d2-4a6d-bb8b-daf917ff3b57)

**Comment by stcouldlisa** [comment]
checker:manualTrigger

**Comment by stcouldlisa** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacediwon5pdrjannv2tu3qojsaqilsep3ylalpaah2mbbec27raoqwk 
#### Address 
> f1nqngcxaslai77fbzxpk2n2ggnltuk7uktgk7cei
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1jvvltduw35u6inn5tr4nfualyd42bh3vjtylgci
#### Id
> bb99b790-3a34-4ad3-a323-8cee294dc53c
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacediwon5pdrjannv2tu3qojsaqilsep3ylalpaah2mbbec27raoqwk

**Comment by newwebgroup** [comment]
checker:manualTrigger

**Comment by NDLABS-OFFICE** [comment]
check bot is very healthy, according to ND audit mark willing to support

**Comment by NDLABS-OFFICE** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceddw3djtj2lzy2spf7otl3zznvwlsoielqhzqve65g7crbcmupudc 
#### Address 
> f1nqngcxaslai77fbzxpk2n2ggnltuk7uktgk7cei
#### Datacap Allocated
> 1.56PiB
#### Signer Address
> f1yayfsv6whu3rheviucvventj3y6t542xfpb47ei
#### Id
> 0742a948-1e63-4ee0-8955-f8665cb98f8e
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceddw3djtj2lzy2spf7otl3zznvwlsoielqhzqve65g7crbcmupudc

**Comment by newwebgroup** [comment]
**Willing to support**
1. are publicly available large data sets;
2. checked Client's Github, not a new account;
3. checked the history of this LDN, obtained multiple notaries for review and support;
4. the CID Checker report is compliant;
5. performed a retrieval test with CID and it was successful

<img width="1374" alt="image" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/100118145/0410d528-5206-4257-9f30-622dbb121617">

**Comment by newwebgroup** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecodxt6oz2ln3qvl53tx3bkpbg3ydx2hb6adhgh37ahlkncf4hzje 
#### Address 
> f1nqngcxaslai77fbzxpk2n2ggnltuk7uktgk7cei
#### Datacap Allocated
> 1.56PiB
#### Signer Address
> f1e77zuityhvvw6u2t6tb5qlnsegy2s67qs4lbbbq
#### Id
> 0742a948-1e63-4ee0-8955-f8665cb98f8e
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecodxt6oz2ln3qvl53tx3bkpbg3ydx2hb6adhgh37ahlkncf4hzje

**Comment by Tom-OriginStorage** [comment]
It's in progress

**Comment by nj-steve** [comment]
checker:manualTrigger

**Comment by nj-steve** [comment]
checker:manualTrigger

**Comment by laurarenpanda** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceathy27h4x3udnlgjhkz4waarjog6xnomk7ot2jrxtx6wqr5uxajo 
#### Address 
> f1nqngcxaslai77fbzxpk2n2ggnltuk7uktgk7cei
#### Datacap Allocated
> 1.56PiB
#### Signer Address
> f1bp3tzp536edm7dodldceekzbsx7zcy7hdfg6uzq
#### Id
> 36ccf0a8-ed67-4d83-9c8f-448b2a06a2ab
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceathy27h4x3udnlgjhkz4waarjog6xnomk7ot2jrxtx6wqr5uxajo

**Comment by nj-steve** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebiseklvqs6thf5xznjkfy4y3cvua7xpjzen3o7xnkyopcss3av56 
#### Address 
> f1nqngcxaslai77fbzxpk2n2ggnltuk7uktgk7cei
#### Datacap Allocated
> 1.56PiB
#### Signer Address
> f1xx6555qijma7igpnjspyvdunc4vfxkawnpqy5ii
#### Id
> 36ccf0a8-ed67-4d83-9c8f-448b2a06a2ab
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebiseklvqs6thf5xznjkfy4y3cvua7xpjzen3o7xnkyopcss3av56

**Comment by Joss-Hua** [comment]
checker:manualTrigger

**Comment by Joss-Hua** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceahrrnu64bydkbcdlhqoolxjvcywi3c2cvzrzfa37bsl2ttmyfjrc 
#### Address 
> f1nqngcxaslai77fbzxpk2n2ggnltuk7uktgk7cei
#### Datacap Allocated
> 1.56PiB
#### Signer Address
> f1tfg54zzscugttejv336vivknmsnzzmyudp3t7wi
#### Id
> fa8cb529-0bb7-4691-a002-613a0da57928
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceahrrnu64bydkbcdlhqoolxjvcywi3c2cvzrzfa37bsl2ttmyfjrc

**Comment by laurarenpanda** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced2auxabu2htkqr6wu2j55ez25v2apljq6xajpfhfgrw4fkonw4wc 
#### Address 
> f1nqngcxaslai77fbzxpk2n2ggnltuk7uktgk7cei
#### Datacap Allocated
> 1.56PiB
#### Signer Address
> f1bp3tzp536edm7dodldceekzbsx7zcy7hdfg6uzq
#### Id
> fa8cb529-0bb7-4691-a002-613a0da57928
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced2auxabu2htkqr6wu2j55ez25v2apljq6xajpfhfgrw4fkonw4wc

**Comment by Tom-OriginStorage** [comment]
In progress, thank you

**Comment by Tom-OriginStorage** [comment]
It's a work in progress, call the bot to see its latest progress

**Comment by Tom-OriginStorage** [comment]
It's a work in progress, call the bot to see its latest progress

**Comment by Tom-OriginStorage** [comment]
It's a work in progress, call the bot to see its latest progress

**Comment by Tom-OriginStorage** [comment]
It's a work in progress, call the bot to see its latest progress

**Comment by Tom-OriginStorage** [comment]
It's a work in progress, call the bot to see its latest progress
