### ISSUE TITLE
[DataCap Application] Kernelogic - End of Term Web Archive Dataset (1/2)

### ISSUE THREAD

**Issue by kernelogic** [filecoin-project/filecoin-plus-large-datasets#1683]
### Data Owner Name

End of Term Web Archive

### Data Owner Country/Region

United States

### Data Owner Industry

Government

### Website

https://registry.opendata.aws/eot-web-archive/

### Social Media

```text
N/A
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

1PiB

### On-chain address for first allocation

f16xgxvxqh4uly64npes2deyyt43mfynaaemrtkfq

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
I have participated every Slingshot phase and is probably the best performing as a "small individual client". 

Even though Slingshot v2 has ended, there are still strong demand from SPs to onboard useful data. This application is to onboard open dataset from AWS.

I have a web UI (https://singularity-browser.kernelogic.ca/) to index all files onboarded and provide ways to retrieve.

I have successfully completed a few LDNs on other datasets and I have record to show I have been following the rules of decentralization and have zero self dealing.

Some of the recent LDNs I completed:
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1108
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1107
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1106
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1104
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/983
```

### Is this project associated with other projects/ecosystem stakeholders?

Yes

### If answered yes, what are the other projects/ecosystem stakeholders

```text
Storage working groups, BigD exchange, singularity deal making tool.
```

### Describe the data being stored onto Filecoin

```text
Disclaimer: 
Due to un-answered issues around whether combined requests or duplicate requests can be used to apply LDN. This is a series of recent new open datasets never applied by anybody (aka calling dibs).

Description: 
The End of Term Web Archive (EOT) captures and saves U.S. Government websites at the end of presidential administrations. The EOT has thus far preserved websites from administration changes in 2008, 2012, 2016, and 2020. Data from these web crawls have been made openly available in several formats in this dataset.

Size:
Total files 1873606
Total size 580.1 TiB
s3://eotarchive
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### How do you plan to prepare the dataset

singularity

### Please share a sample of the data

```text
https://registry.opendata.aws/eot-web-archive/
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Sporadic

### For how long do you plan to keep this dataset stored on Filecoin

1 to 1.5 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, Europe

### How will you be distributing your data to storage providers

HTTP or FTP server

### How do you plan to choose storage providers

Slack, Big data exchange, Partners

### If you already have a list of storage providers to work with, fill out their names and provider IDs below

```text
PIKNIK f01904630,f01873432
GreaterHeat f01971600,f01992630
HarryM-Filet f02301,f03223,f0240185
BEWELL TECHNOLOGIES LIMITED f01944744,f01943663,f01928097
And others from BigDExchange
```

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 5PiB

**Expected weekly DataCap usage rate**
> 1PiB

**Client address**
>f16xgxvxqh4uly64npes2deyyt43mfynaaemrtkfq

**Comment by Tom-OriginStorage** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaduyzzpbg3rblw23rkcppfzxrhk7mu3wszck53vttxl4fi7rgp4o 
#### Address 
> f16xgxvxqh4uly64npes2deyyt43mfynaaemrtkfq
#### Datacap Allocated
> 256.00TiB
#### Signer Address
> f1q6bpjlqia6iemqbrdaxr2uehrhpvoju3qh4lpga
#### Id
> 3c60b1f7-397d-498c-be10-61c99a75b05f
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaduyzzpbg3rblw23rkcppfzxrhk7mu3wszck53vttxl4fi7rgp4o

**Comment by xiaoyuaiheshui** [comment]
First assigned, Kernelogic's project was as compliant as ever. I am willing to support and look forward to the next milestone!

**Comment by xiaoyuaiheshui** [comment]
First assignment
Kernelogic project is as compliant as ever. I am willing to support and look forward to the next milestone!

**Comment by xiaoyuaiheshui** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceabif4d2e4hgxfvp4ae5ucgdr3slazk7w7pn4rl7oxcwfu4334av4 
#### Address 
> f16xgxvxqh4uly64npes2deyyt43mfynaaemrtkfq
#### Datacap Allocated
> 256.00TiB
#### Signer Address
> f122qmy25wdtt5mxd77kndiq7z5x2n3iwiuz2wdsa
#### Id
> 3c60b1f7-397d-498c-be10-61c99a75b05f
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceabif4d2e4hgxfvp4ae5ucgdr3slazk7w7pn4rl7oxcwfu4334av4

**Comment by kernelogic** [comment]
keepalive

**Comment by kernelogic** [comment]
I need to keep this open.

**Comment by kernelogic** [comment]
Need to keep this open. Still onboarding slowly.

**Comment by kernelogic** [comment]
I am still working on it. Started sending out deals this week.

**Comment by kernelogic** [comment]
I am still working on it. I sent out some deals already but just need a bit more distribution to trigger next tranche.

**Comment by kernelogic** [comment]
checker:manualTrigger f16xgxvxqh4uly64npes2deyyt43mfynaaemrtkfq f1ezp4w6l2y2oz2nmy4sdegnmxcrphab2jlt5hbla

**Comment by a1991car** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced7mlnwfftkuvb5bpc27emjw34f2lzve65amej32522ag557dyl4c 
#### Address 
> f16xgxvxqh4uly64npes2deyyt43mfynaaemrtkfq
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f1qnumecdypgrbaebtkdfjnwt5ndacadcuas3deiq
#### Id
> 7124a59c-195f-4d54-b804-648185997276
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced7mlnwfftkuvb5bpc27emjw34f2lzve65amej32522ag557dyl4c

**Comment by sxxfuture-official** [comment]
LGTM

**Comment by sxxfuture-official** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebjuqsnntkehjonuqup7y4depg4ednhvozcilh4552voopofpdfec 
#### Address 
> f16xgxvxqh4uly64npes2deyyt43mfynaaemrtkfq
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f1foiomqlmoshpuxm6aie4xysffqezkjnokgwcecq
#### Id
> 7124a59c-195f-4d54-b804-648185997276
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebjuqsnntkehjonuqup7y4depg4ednhvozcilh4552voopofpdfec

**Comment by kernelogic** [comment]
Still onboarding in this series.

**Comment by SuperChaiChai** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceahi7czu5rrppbkfyqipwaigfi4274p6q4b4jxq6krf63rpfrjohu 
#### Address 
> f16xgxvxqh4uly64npes2deyyt43mfynaaemrtkfq
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f12mckci3omexgzoeosjvstcfxfe4vqw7owdia3da
#### Id
> 7124a59c-195f-4d54-b804-648185997276
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceahi7czu5rrppbkfyqipwaigfi4274p6q4b4jxq6krf63rpfrjohu

**Comment by laurarenpanda** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebo4567nb5orbncxrw7r3cy3lzzeyy3x2hhrdn36e5jljxa6zcqfm 
#### Address 
> f16xgxvxqh4uly64npes2deyyt43mfynaaemrtkfq
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f1bp3tzp536edm7dodldceekzbsx7zcy7hdfg6uzq
#### Id
> 7124a59c-195f-4d54-b804-648185997276
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebo4567nb5orbncxrw7r3cy3lzzeyy3x2hhrdn36e5jljxa6zcqfm

**Comment by kernelogic** [comment]
need to keep open, still onboarding.

**Comment by kevzak** [comment]
checker:manualTrigger

**Comment by kevzak** [comment]
@kernelogic looks like 2 SPs and 1 is storing 60+%. Who are distributed SPs involved. please provide Entity and IDs.

**Comment by kernelogic** [comment]
checker:manualTrigger f16xgxvxqh4uly64npes2deyyt43mfynaaemrtkfq  f1ezp4w6l2y2oz2nmy4sdegnmxcrphab2jlt5hbla

**Comment by kernelogic** [comment]
@kevzak please look at the combined CID report above since it's 2 in 1 series.

The onboarding entities or alliances are DSPA (The ones in Dallas), Chris (The ones in Hong Kong) and Sageone (data transfer in progress).

**Comment by Sunnyiscoming** [comment]
Hello, @kernelogic per the https://github.com/filecoin-project/notary-governance/issues/922 for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

This information will be reviewed by Fil+ Governance team to confirm validity and then the application will be allowed to move forward for additional notary review.

**Comment by kernelogic** [comment]
Hi @Sunnyiscoming form submitted. What's next? Can notaries proceed to sign now? If not, when can I expect a response?

**Comment by AlanGreaterheat** [comment]
checker:manualTrigger

**Comment by AlanGreaterheat** [comment]
checker:manualTrigger f16xgxvxqh4uly64npes2deyyt43mfynaaemrtkfq f1ezp4w6l2y2oz2nmy4sdegnmxcrphab2jlt5hbla

**Comment by AlanGreaterheat** [comment]
Client is well known and has completed KYC form. Willing to support this round.

**Comment by AlanGreaterheat** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec7umxtmxb4wwfi5szensq72nfuv3djzue4m4bzkizaam6bjzgiyg 
#### Address 
> f16xgxvxqh4uly64npes2deyyt43mfynaaemrtkfq
#### Datacap Allocated
> 1.00PiB
#### Signer Address
> f1pnmzlxj7cfeo2v6oj5nco46hkg2l46wj7o4xxui
#### Id
> 37f3b264-7558-4a02-8ce8-94295913b4e4
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec7umxtmxb4wwfi5szensq72nfuv3djzue4m4bzkizaam6bjzgiyg

**Comment by luobin544** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebryddggpsfcuvluahhm42fdyri4mt3lrhbwe4wbk3t6yyjwp5zno 
#### Address 
> f16xgxvxqh4uly64npes2deyyt43mfynaaemrtkfq
#### Datacap Allocated
> 1.00PiB
#### Signer Address
> f1tbd632f6w62glfaf7wjpimacbnjiz26poyoes2q
#### Id
> 37f3b264-7558-4a02-8ce8-94295913b4e4
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebryddggpsfcuvluahhm42fdyri4mt3lrhbwe4wbk3t6yyjwp5zno

**Comment by nj-steve** [comment]
checker:manualTrigger

**Comment by nj-steve** [comment]
Because at first，more replication is coming soon.

**Comment by nj-steve** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceadvnmijiyganxgaeteixfiqg6diwwnd2o2tgjzpbrety2xffcbmw 
#### Address 
> f16xgxvxqh4uly64npes2deyyt43mfynaaemrtkfq
#### Datacap Allocated
> 1.00PiB
#### Signer Address
> f1xx6555qijma7igpnjspyvdunc4vfxkawnpqy5ii
#### Id
> 37f3b264-7558-4a02-8ce8-94295913b4e4
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceadvnmijiyganxgaeteixfiqg6diwwnd2o2tgjzpbrety2xffcbmw

**Comment by kernelogic** [comment]
Keep it open

**Comment by kernelogic** [comment]
checker:manualTrigger f16xgxvxqh4uly64npes2deyyt43mfynaaemrtkfq f1ezp4w6l2y2oz2nmy4sdegnmxcrphab2jlt5hbla

**Comment by Normalnoise** [comment]
the report seems healthy, willing to support next round

**Comment by Normalnoise** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceakso62gentj66u62skmuermcb6qhj56crcdytz5hs3al3kx2db6g 
#### Address 
> f16xgxvxqh4uly64npes2deyyt43mfynaaemrtkfq
#### Datacap Allocated
> 1.00PiB
#### Signer Address
> f1c5non5yf35avgcpsqvxu4yj54yyvxorwyjochqq
#### Id
> 37f3b264-7558-4a02-8ce8-94295913b4e4
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceakso62gentj66u62skmuermcb6qhj56crcdytz5hs3al3kx2db6g

**Comment by kernelogic** [comment]
keepalive

**Comment by Sunnyiscoming** [comment]
If you already have a list of storage providers to work with, fill out their names and provider IDs below
PIKNIK f01904630,f01873432
GreaterHeat f01971600,f01992630
HarryM-Filet f02301,f03223,f0240185
BEWELL TECHNOLOGIES LIMITED f01944744,f01943663,f01928097
And others from BigDExchange
--------------------------
Please provide ID, City, Country, Organization of each SP here.

**Comment by kernelogic** [comment]
I need to keep it open

**Comment by kernelogic** [comment]
keepalive

**Comment by kernelogic** [comment]
keepalive

**Comment by kernelogic** [comment]
keepalive

**Comment by kernelogic** [comment]
keepalive

**Comment by kernelogic** [comment]
I need to keep this open.
