### ISSUE TITLE
[DataCap Application] Kernelogic - Cell Painting Gallery (1/2)

### ISSUE THREAD

**Issue by kernelogic** [filecoin-project/filecoin-plus-large-datasets#1685]
### Data Owner Name

Broad Institute

### Data Owner Country/Region

United Kingdom

### Data Owner Industry

Life Science / Healthcare

### Website

https://registry.opendata.aws/cellpainting-gallery/

### Social Media

```text
N/A
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

1PiB

### On-chain address for first allocation

f1l72kz4c5rqqcukgm4yl4ydlrnbwd2wy7a7oqqua

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
I have participated every Slingshot phase and is probably the best performing as a "small individual client". 

Even though Slingshot v2 has ended, there are still strong demand from SPs to onboard useful data. This application is to onboard open dataset from AWS.

I have a web UI (https://singularity-browser.kernelogic.ca/) to index all files onboarded and provide ways to retrieve.

I have successfully completed a few LDNs on other datasets and I have record to show I have been following the rules of decentralization and have zero self dealing.

Some of the recent LDNs I completed:
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1108
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1107
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1106
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1104
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/983
```

### Is this project associated with other projects/ecosystem stakeholders?

Yes

### If answered yes, what are the other projects/ecosystem stakeholders

```text
Storage working groups, BigD exchange, singularity deal making tool.
```

### Describe the data being stored onto Filecoin

```text
Disclaimer: 
Due to un-answered issues around whether combined requests or duplicate requests can be used to apply LDN. This is a series of recent new open datasets never applied by anybody (aka calling dibs).

Description: 
The Cell Painting Gallery is a collection of image datasets created using the Cell Painting assay. The images of cells are captured by microscopy imaging, and reveal the response of various labeled cell components to whatever treatments are tested, which can include genetic perturbations, chemicals or drugs, or different cell types. 

Size:
Total files 251683704
Total size 582.1 TiB
s3://cellpainting-gallery
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### How do you plan to prepare the dataset

singularity

### Please share a sample of the data

```text
https://registry.opendata.aws/cellpainting-gallery/
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Sporadic

### For how long do you plan to keep this dataset stored on Filecoin

Less than 1 year

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, Europe, Australia (continent)

### How will you be distributing your data to storage providers

HTTP or FTP server

### How do you plan to choose storage providers

Slack, Big data exchange, Partners

### If you already have a list of storage providers to work with, fill out their names and provider IDs below

```text
PIKNIK f01904630,f01873432
GreaterHeat f01971600,f01992630
HarryM-Filet f02301,f03223,f0240185
BEWELL TECHNOLOGIES LIMITED f01944744,f01943663,f01928097
And others from BigDExchange
```

### How do you plan to make deals to your storage providers

Singularity

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 5PiB

**Expected weekly DataCap usage rate**
> 1PiB

**Client address**
>f1l72kz4c5rqqcukgm4yl4ydlrnbwd2wy7a7oqqua

**Comment by newwebgroup** [comment]
KYB is complete and Client has had a lot of prior experience loading publicly available large datasets into Filecoin via Fil+ and is in good standing.
First round willing to support

**Comment by newwebgroup** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedqbo6ca5kvgx4tirdkddkx4fdi22og2zn6ov56bxkrdnghc45pe6 
#### Address 
> f1l72kz4c5rqqcukgm4yl4ydlrnbwd2wy7a7oqqua
#### Datacap Allocated
> 256.00TiB
#### Signer Address
> f1e77zuityhvvw6u2t6tb5qlnsegy2s67qs4lbbbq
#### Id
> 68b57f7f-d608-49cc-be26-2b8a9242b50f
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedqbo6ca5kvgx4tirdkddkx4fdi22og2zn6ov56bxkrdnghc45pe6

**Comment by herrehesse** [comment]
Fei is a respected and known entity, willing to support first round and see the results.

**Comment by herrehesse** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacea7wmpgtjnhszahvwqpsajdgfxgcsau2c7jgmj7ceiby3vtaobbzo 
#### Address 
> f1l72kz4c5rqqcukgm4yl4ydlrnbwd2wy7a7oqqua
#### Datacap Allocated
> 256.00TiB
#### Signer Address
> f1krmypm4uoxxf3g7okrwtrahlmpcph3y7rbqqgfa
#### Id
> 68b57f7f-d608-49cc-be26-2b8a9242b50f
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacea7wmpgtjnhszahvwqpsajdgfxgcsau2c7jgmj7ceiby3vtaobbzo

**Comment by kernelogic** [comment]
checker:manualTrigger

**Comment by a1991car** [comment]
checker:manualTrigger

**Comment by a1991car** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceajhoivsctk23ksjs5udfcon54nai43dz6ipt62v73hqkr3c7weqq 
#### Address 
> f1l72kz4c5rqqcukgm4yl4ydlrnbwd2wy7a7oqqua
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f1qnumecdypgrbaebtkdfjnwt5ndacadcuas3deiq
#### Id
> not found
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceajhoivsctk23ksjs5udfcon54nai43dz6ipt62v73hqkr3c7weqq

**Comment by newwebgroup** [comment]
checker:manualTrigger

**Comment by laurarenpanda** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedvvkux5ves3rzsz3keswr2s53imrwlywn5lt3nihkuld27jyhf2w 
#### Address 
> f1l72kz4c5rqqcukgm4yl4ydlrnbwd2wy7a7oqqua
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f1bp3tzp536edm7dodldceekzbsx7zcy7hdfg6uzq
#### Id
> not found
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedvvkux5ves3rzsz3keswr2s53imrwlywn5lt3nihkuld27jyhf2w

**Comment by kernelogic** [comment]
checker:manualTrigger f1l72kz4c5rqqcukgm4yl4ydlrnbwd2wy7a7oqqua f1gjimknqxeipu3xacx5bnbldsbwzlgvtf562pnay

**Comment by sxxfuture-official** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb7oxhvbow7symhat7nkg45cmsa3aqxa7um3qlnrnr4jc5zg2btm2 
#### Address 
> f1l72kz4c5rqqcukgm4yl4ydlrnbwd2wy7a7oqqua
#### Datacap Allocated
> 1.00PiB
#### Signer Address
> f1foiomqlmoshpuxm6aie4xysffqezkjnokgwcecq
#### Id
> 152641d9-8b1d-49af-8530-3b2aa1565b2c
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb7oxhvbow7symhat7nkg45cmsa3aqxa7um3qlnrnr4jc5zg2btm2

**Comment by laurarenpanda** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecmn3qhlekp3iksp4bgzxiymrbxejjgiqr5unrl5npdtt36mhwrgi 
#### Address 
> f1l72kz4c5rqqcukgm4yl4ydlrnbwd2wy7a7oqqua
#### Datacap Allocated
> 1.00PiB
#### Signer Address
> f1bp3tzp536edm7dodldceekzbsx7zcy7hdfg6uzq
#### Id
> 152641d9-8b1d-49af-8530-3b2aa1565b2c
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecmn3qhlekp3iksp4bgzxiymrbxejjgiqr5unrl5npdtt36mhwrgi

**Comment by Aaronn85** [comment]
checker:manualTrigger

**Comment by kernelogic** [comment]
Keep alive

**Comment by kernelogic** [comment]
checker:manualTrigger f1l72kz4c5rqqcukgm4yl4ydlrnbwd2wy7a7oqqua f1gjimknqxeipu3xacx5bnbldsbwzlgvtf562pnay

**Comment by 1ane-1** [comment]
Support!

**Comment by 1ane-1** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb5fabpoihhkgrk2fdfjf6e3o6e7u2ybwe55jtvab652vczphxy6c 
#### Address 
> f1l72kz4c5rqqcukgm4yl4ydlrnbwd2wy7a7oqqua
#### Datacap Allocated
> 2.00PiB
#### Signer Address
> f1mdk7s2vntzm6hu35yuo6vjubtrpfnb2awhgvrri
#### Id
> 636dee30-4597-4084-90ce-7b900d3a6604
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb5fabpoihhkgrk2fdfjf6e3o6e7u2ybwe55jtvab652vczphxy6c

**Comment by spaceT9** [comment]
checker:manualTrigger

**Comment by kernelogic** [comment]
checker:manualTrigger f1l72kz4c5rqqcukgm4yl4ydlrnbwd2wy7a7oqqua f1gjimknqxeipu3xacx5bnbldsbwzlgvtf562pnay

**Comment by a1991car** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedxzgkxoidv424kb5rkblpd6sxfdj3zx27p2ni3og56txzfegmfc2 
#### Address 
> f1l72kz4c5rqqcukgm4yl4ydlrnbwd2wy7a7oqqua
#### Datacap Allocated
> 2.00PiB
#### Signer Address
> f1qnumecdypgrbaebtkdfjnwt5ndacadcuas3deiq
#### Id
> 636dee30-4597-4084-90ce-7b900d3a6604
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedxzgkxoidv424kb5rkblpd6sxfdj3zx27p2ni3og56txzfegmfc2

**Comment by Sunnyiscoming** [comment]
Hello, @kernelogic per the https://github.com/filecoin-project/notary-governance/issues/922 for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

This information will be reviewed by Fil+ Governance team to confirm validity and then the application will be allowed to move forward for additional notary review.
