### ISSUE TITLE
[DataCap Application] Kernelogic - Cell Painting Gallery (2/2)

### ISSUE THREAD

**Issue by kernelogic** [filecoin-project/filecoin-plus-large-datasets#1686]
### Data Owner Name

Broad Institute

### Data Owner Country/Region

United Kingdom

### Data Owner Industry

Life Science / Healthcare

### Website

https://registry.opendata.aws/cellpainting-gallery/

### Social Media

```text
N/A
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

1PiB

### On-chain address for first allocation

f1gjimknqxeipu3xacx5bnbldsbwzlgvtf562pnay

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
I have participated every Slingshot phase and is probably the best performing as a "small individual client". 

Even though Slingshot v2 has ended, there are still strong demand from SPs to onboard useful data. This application is to onboard open dataset from AWS.

I have a web UI (https://singularity-browser.kernelogic.ca/) to index all files onboarded and provide ways to retrieve.

I have successfully completed a few LDNs on other datasets and I have record to show I have been following the rules of decentralization and have zero self dealing.

Some of the recent LDNs I completed:
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1108
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1107
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1106
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1104
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/983
```

### Is this project associated with other projects/ecosystem stakeholders?

Yes

### If answered yes, what are the other projects/ecosystem stakeholders

```text
Storage working groups, BigD exchange, singularity deal making tool.
```

### Describe the data being stored onto Filecoin

```text
Disclaimer: 
Due to un-answered issues around whether combined requests or duplicate requests can be used to apply LDN. This is a series of recent new open datasets never applied by anybody (aka calling dibs).

Description: 
The Cell Painting Gallery is a collection of image datasets created using the Cell Painting assay. The images of cells are captured by microscopy imaging, and reveal the response of various labeled cell components to whatever treatments are tested, which can include genetic perturbations, chemicals or drugs, or different cell types. 

Size:
Total files 251683704
Total size 582.1 TiB
s3://cellpainting-gallery
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### How do you plan to prepare the dataset

singularity

### Please share a sample of the data

```text
https://registry.opendata.aws/cellpainting-gallery/
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Sporadic

### For how long do you plan to keep this dataset stored on Filecoin

1 to 1.5 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, Europe, Australia (continent)

### How will you be distributing your data to storage providers

HTTP or FTP server

### How do you plan to choose storage providers

Slack, Big data exchange, Partners

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 5PiB

**Expected weekly DataCap usage rate**
> 1PiB

**Client address**
>f1gjimknqxeipu3xacx5bnbldsbwzlgvtf562pnay

**Comment by newwebgroup** [comment]
KYB is complete and Client has had a lot of prior experience loading publicly available large datasets into Filecoin via Fil+ and is in good standing.
First round willing to support

**Comment by Tom-OriginStorage** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebybuccnpq3pbnliktyzfpqgnmjn6l5jqqkagh5sfnvkdbwbcs3cg 
#### Address 
> f1gjimknqxeipu3xacx5bnbldsbwzlgvtf562pnay
#### Datacap Allocated
> 256.00TiB
#### Signer Address
> f1q6bpjlqia6iemqbrdaxr2uehrhpvoju3qh4lpga
#### Id
> d479973c-ab9e-432f-9f50-38196283e314
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebybuccnpq3pbnliktyzfpqgnmjn6l5jqqkagh5sfnvkdbwbcs3cg

**Comment by newwebgroup** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedsxuk3zs3f7pa2wsc7tebxqpobujxb2wk6mvprcjwmyf4uc4mgwi 
#### Address 
> f1gjimknqxeipu3xacx5bnbldsbwzlgvtf562pnay
#### Datacap Allocated
> 256.00TiB
#### Signer Address
> f1e77zuityhvvw6u2t6tb5qlnsegy2s67qs4lbbbq
#### Id
> d479973c-ab9e-432f-9f50-38196283e314
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedsxuk3zs3f7pa2wsc7tebxqpobujxb2wk6mvprcjwmyf4uc4mgwi

**Comment by kernelogic** [comment]
checker:manualTrigger

**Comment by spaceT9** [comment]
checker:manualTrigger

**Comment by spaceT9** [comment]
Can you solve the CID sharing issue? what's your plan?

**Comment by kernelogic** [comment]
CID Sharing comes from the same series of same dataset (from me). Therefore it is expected.

**Comment by sxxfuture-official** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedffg5iu656jlisiuj4rhvkcdkeuwiomwtoi65ahamcspcpaq74b6 
#### Address 
> f1gjimknqxeipu3xacx5bnbldsbwzlgvtf562pnay
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f1foiomqlmoshpuxm6aie4xysffqezkjnokgwcecq
#### Id
> 9cc2a35f-0a33-4505-9a22-bdfac006290c
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedffg5iu656jlisiuj4rhvkcdkeuwiomwtoi65ahamcspcpaq74b6

**Comment by sxxfuture-official** [comment]
The merged CID Report is here
[https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1685#issuecomment-1586566868](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1685#issuecomment-1586566868)

**Comment by laurarenpanda** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec7wthr2rdkw2mvswviht63yanafjtu5b4vabyrple6kxfe7gr2ko 
#### Address 
> f1gjimknqxeipu3xacx5bnbldsbwzlgvtf562pnay
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f1bp3tzp536edm7dodldceekzbsx7zcy7hdfg6uzq
#### Id
> 9cc2a35f-0a33-4505-9a22-bdfac006290c
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec7wthr2rdkw2mvswviht63yanafjtu5b4vabyrple6kxfe7gr2ko

**Comment by spaceT9** [comment]
checker:manualTrigger

**Comment by kernelogic** [comment]
checker:manualTrigger f1l72kz4c5rqqcukgm4yl4ydlrnbwd2wy7a7oqqua f1gjimknqxeipu3xacx5bnbldsbwzlgvtf562pnay

**Comment by igoovo** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceczov2k6e3sosmtjml7xncyk7vwbqztdrokem4xj6r2whm2in56fc 
#### Address 
> f1gjimknqxeipu3xacx5bnbldsbwzlgvtf562pnay
#### Datacap Allocated
> 1.00PiB
#### Signer Address
> f1shnsfayxqll77svffaxnjenms7bbbysbqcatrpy
#### Id
> a91979ff-dea3-4394-8a41-0f6df901115d
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceczov2k6e3sosmtjml7xncyk7vwbqztdrokem4xj6r2whm2in56fc

**Comment by SuperChaiChai** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebkpa7drcb2uha3ibkvtts32yj2git2mqgndhbracepb5i3axrfz2 
#### Address 
> f1gjimknqxeipu3xacx5bnbldsbwzlgvtf562pnay
#### Datacap Allocated
> 1.00PiB
#### Signer Address
> f12mckci3omexgzoeosjvstcfxfe4vqw7owdia3da
#### Id
> a91979ff-dea3-4394-8a41-0f6df901115d
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebkpa7drcb2uha3ibkvtts32yj2git2mqgndhbracepb5i3axrfz2

**Comment by kernelogic** [comment]
I need to keep this open.

**Comment by kernelogic** [comment]
Keep alive

**Comment by clriesco** [comment]
Removed stale label and reopened issue :)

**Comment by kernelogic** [comment]
I am still onboarding it and the SP is about to start.

**Comment by kernelogic** [comment]
Waiting for SP to get Fil funding.

**Comment by kernelogic** [comment]
Still onboarding in this series.

**Comment by kernelogic** [comment]
Still onboarding in this series.

**Comment by kernelogic** [comment]
keepalive

**Comment by kernelogic** [comment]
keepalive
