### ISSUE TITLE
[DataCap Application] Kernelogic - ASTER L1T Cloud-Optimized GeoTIFFs

### ISSUE THREAD

**Issue by kernelogic** [filecoin-project/filecoin-plus-large-datasets#1687]
### Data Owner Name

Descartes Labs

### Data Owner Country/Region

United States

### Data Owner Industry

Life Science / Healthcare

### Website

https://registry.opendata.aws/aster-l1t/

### Social Media

```text
N/A
```

### Total amount of DataCap being requested

3PiB

### Weekly allocation of DataCap requested

1PiB

### On-chain address for first allocation

f1fuo45n56dhesso2nyjwjumkxnvehgigrkgrprgq

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
I have participated every Slingshot phase and is probably the best performing as a "small individual client". 

Even though Slingshot v2 has ended, there are still strong demand from SPs to onboard useful data. This application is to onboard open dataset from AWS.

I have a web UI (https://singularity-browser.kernelogic.ca/) to index all files onboarded and provide ways to retrieve.

I have successfully completed a few LDNs on other datasets and I have record to show I have been following the rules of decentralization and have zero self dealing.

Some of the recent LDNs I completed:
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1108
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1107
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1106
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1104
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/983
```

### Is this project associated with other projects/ecosystem stakeholders?

Yes

### If answered yes, what are the other projects/ecosystem stakeholders

```text
Storage working groups, BigD exchange, singularity deal making tool.
```

### Describe the data being stored onto Filecoin

```text
Disclaimer: 
Due to un-answered issues around whether combined requests or duplicate requests can be used to apply LDN. This is a series of recent new open datasets never applied by anybody (aka calling dibs).

Description: 
The Advanced Spaceborne Thermal Emission and Reflection Radiometer (ASTER) Level 1 Precision Terrain Corrected Registered At-Sensor Radiance (AST_L1T) data contains calibrated at-sensor radiance, which corresponds with the ASTER Level 1B (AST_L1B), that has been geometrically corrected, and rotated to a north-up UTM projection.

Size:
Total files 17023534
Total size 165.7 TiB
s3://aster-l1t
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### How do you plan to prepare the dataset

singularity

### Please share a sample of the data

```text
https://registry.opendata.aws/aster-l1t/
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [ ] I confirm

### What is the expected retrieval frequency for this data

Sporadic

### For how long do you plan to keep this dataset stored on Filecoin

1 to 1.5 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, Europe, Australia (continent)

### How will you be distributing your data to storage providers

HTTP or FTP server

### How do you plan to choose storage providers

Slack, Big data exchange, Partners

### How do you plan to make deals to your storage providers

Singularity

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 3PiB

**Expected weekly DataCap usage rate**
> 1PiB

**Client address**
>f1fuo45n56dhesso2nyjwjumkxnvehgigrkgrprgq

**Comment by newwebgroup** [comment]
KYB is complete and Client has had a lot of prior experience loading publicly available large datasets into Filecoin via Fil+ and is in good standing.
First round willing to support

**Comment by newwebgroup** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceag44oet3wz6fss4a2bgbnxusogu2vhzyple6tbiblvl4lyiddxze 
#### Address 
> f1fuo45n56dhesso2nyjwjumkxnvehgigrkgrprgq
#### Datacap Allocated
> 153.59TiB
#### Signer Address
> f1e77zuityhvvw6u2t6tb5qlnsegy2s67qs4lbbbq
#### Id
> cab78a19-e86c-47c1-a08e-c20e74b287c1
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceag44oet3wz6fss4a2bgbnxusogu2vhzyple6tbiblvl4lyiddxze

**Comment by C00kies77** [comment]
@kernelogic Looking forward to the results of the first CiD report.

**Comment by herrehesse** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedfieljmzpguxxhcprd65cjpn3nom7nwyqd6znvbhqrndg6gq6r7w 
#### Address 
> f1fuo45n56dhesso2nyjwjumkxnvehgigrkgrprgq
#### Datacap Allocated
> 153.59TiB
#### Signer Address
> f1krmypm4uoxxf3g7okrwtrahlmpcph3y7rbqqgfa
#### Id
> cab78a19-e86c-47c1-a08e-c20e74b287c1
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedfieljmzpguxxhcprd65cjpn3nom7nwyqd6znvbhqrndg6gq6r7w

**Comment by kernelogic** [comment]
keepalive

**Comment by kernelogic** [comment]
Not enough demand to onboarding this dataset. Closing it for now.
