### ISSUE TITLE
[DataCap Application] FileDrive Labs - Smithsonian Open Access

### ISSUE THREAD

**Issue by laurarenpanda** [filecoin-project/filecoin-plus-large-datasets#1688]
### Data Owner Name

FileDrive Labs

### Data Owner Country/Region

China

### Data Owner Industry

Life Science / Healthcare

### Website

https://filedrive.io/

### Social Media

```text
Twitter: https://twitter.com/FileDrive1
Medium: https://medium.com/@FileDrive1
WeChat Offical Account: FileDrive
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

500TiB

### On-chain address for first allocation

f1udumyw3yjzxuu5co4rateaq6czubrwbyy2t4jiq

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
FileDrive Datasets Landing Plan is a project for onboarding more valuable public datasets onto the Filecoin network. Through several phases, we plan to bring 10 PiB data and promote 100 PiB storage power growth to Filecoin. 


About FileDrive Datasets

FileDrive Datasets is a platform to effectively connect the huge storage market that Filecoin has built with publishers of public datasets.
The Filecoin network provides reliable, secure, and affordable decentralized storage services, and FileDrive Labs wants to deliver these benefits to end-users by building a public dataset platform.
It is challenging to attract traditional Cloud Storage and Object-base Storage users to the Filecoin network and benefit from it. Developers in the Felicoin ecosystem, such as FileDrive Labs, need to face this challenge together.
As a member of the Filecoin ecosystem, FileDrive Labs has been insisting on developing useful tools to make it easier for users to store their data onto the Filecoin network. 

FileDrive Datasets has integrated a group of tools to provide storage service with the compatibility of both Cloud Storage and Object-base Storage and better user experience to attract more users.
Projects(ongoing) behind:
- Go-Graphsplit: https://github.com/filedrive-team/go-graphsplit
- DS-Cluster: https://github.com/filedrive-team/go-ds-cluster
- Filejoy: https://github.com/filedrive-team/filejoy

Article about FileDrive Datasets on Filecoin Blog:
- Large Datasets: FileDrive: https://filecoin.io/blog/posts/large-datasets-filedrive/



About FileDrive Labs

FileDrive Labs has always defined ourselves as tool developers and infrastructure builders in the Filecoin ecosystem. From 2019, we continuously focus on technical solutions and development based on IPFS protocol and the Filecoin network and do our best to contribute to the community.
Over 80% of our team are qualified engineers, and half of them have more than 10-year development experience in multiple industries, including Communication, the Internet, and blockchain.
Since 2020, we have participated in Slingshot Competition, become one of the top teams, and stored over 5 PiB useful data from public datasets to the Filecoin network.
To contribute to the Filecoin Community, we developed an open-source data prep tool Graphsplit, FIL+ project dashboard filplus.info and storage provider discovery platform filfind,info.
Besides, we have also hold weekly online virtual events named FileDrive Meetup from March 2022, which aims to provide a platform for community members to grasp the latest trends of the Filecoin network and our work and research.

Please check the following links for more details.
- GitHub: https://github.com/filedrive-team
- Twitter: https://twitter.com/FileDrive1
- Eventbrite: https://www.eventbrite.hk/o/filedrive-labs-42456337463
- YouTube Channel: https://www.youtube.com/channel/UCxcZC1dtBUlQvZY7DX13W1w
- Medium: https://medium.com/@FileDrive1
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
Smithsonian Open Access
- The Smithsonian’s mission is the "increase and diffusion of knowledge" and has been collecting since 1846. The Smithsonian, through its efforts to digitize its multidisciplinary collections, has created millions of digital assets and related metadata describing the collection objects. On February 25th, 2020, the Smithsonian released over 2.8 million CC0 interdisciplinary 2-D and 3-D images, related metadata, and additionally, research data from researches across the Smithsonian. The 2.8 million "open access" collections are a subset of the Smithsonian’s 155 million objects, 2.1 million library volumes and 156,000 cubic feet of archival collections held in 19 museums, 9 research centers, libraries, archives and the National Zoo. Digitization of collections is ongoing.
- https://registry.opendata.aws/smithsonian-open-access/
- License: CC0
- Size: 621.2 TiB
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### How do you plan to prepare the dataset

IPFS, lotus, graphsplit

### Please share a sample of the data

```text
Original Source:
https://registry.opendata.aws/smithsonian-open-access/
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Weekly

### For how long do you plan to keep this dataset stored on Filecoin

2 to 3 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, Europe, Australia (continent)

### How will you be distributing your data to storage providers

IPFS, Shipping hard drives, Lotus built-in data transfer

### How do you plan to choose storage providers

Slack, Filmine

### If you already have a list of storage providers to work with, fill out their names and provider IDs below

```text
Please check the Checker Reports of our previous LDN applications:
- https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1266
```

### How do you plan to make deals to your storage providers

Lotus client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
You mentioned this dataset in 8 applications. How much data of this dataset has been stored? How many copies?
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1266
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1267
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1268

Because there is no consensus in whether the client should submit one by one, 5 applications have not been updated.
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1623
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1624
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1625
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1626
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1627

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 5PiB

**Expected weekly DataCap usage rate**
> 500TiB

**Client address**
>f1udumyw3yjzxuu5co4rateaq6czubrwbyy2t4jiq

**Comment by Fatman13** [comment]
check:trigger

**Comment by Fatman13** [comment]
checker:manualTrigger

**Comment by laurarenpanda** [comment]
@Fatman13 
Please check for the historical deal report:
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1266#issuecomment-1441136766

**Comment by Fatman13** [comment]
What was the reason for CID sharing again? I remember seeing you explaining it somewhere but couldn't find it.

**Comment by laurarenpanda** [comment]
> What was the reason for CID sharing again? I remember seeing you explaining it somewhere but couldn't find it.

The same public datasets with the same preprocessing tool, like Go-Graphsplit, could lead to that result.

**Comment by liyunzhi-666** [comment]
Through disclosure records and comment history,I would like to support this round.

**Comment by liyunzhi-666** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebb56cfyjxmba45m6dseb2zyo3zfk2rwnxl22wrwxvfoqj63jhceu 
#### Address 
> f1udumyw3yjzxuu5co4rateaq6czubrwbyy2t4jiq
#### Datacap Allocated
> 250.00TiB
#### Signer Address
> f1pszcrsciyixyuxxukkvtazcokexbn54amf7gvoq
#### Id
> e30a5bb4-9378-4b93-a10a-d992b77021bb
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebb56cfyjxmba45m6dseb2zyo3zfk2rwnxl22wrwxvfoqj63jhceu

**Comment by dongpo313** [comment]
checker:manualTrigger

**Comment by Fatman13** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecygocguw6vntkb47v5prag5hjfnfzohhhggdyah4k56tpx77qvfe 
#### Address 
> f1udumyw3yjzxuu5co4rateaq6czubrwbyy2t4jiq
#### Datacap Allocated
> 500.00TiB
#### Signer Address
> f1j3u7crhjzwb2cj5mq7vodlt4o66yoyci7lhcauy
#### Id
> ef70eb16-cee2-455a-9804-3451cfe85e1e
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecygocguw6vntkb47v5prag5hjfnfzohhhggdyah4k56tpx77qvfe

**Comment by Fatman13** [comment]
Reached out by client on Slack. CID checker and everything else looks good.

**Comment by kernelogic** [comment]
In support too

**Comment by NDLABS-OFFICE** [comment]
checker:manualTrigger

**Comment by kernelogic** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebphzcbtq3lmodbijwhohgezhxbstao6imhnxpido2nuqzklxufrk 
#### Address 
> f1udumyw3yjzxuu5co4rateaq6czubrwbyy2t4jiq
#### Datacap Allocated
> 500.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### Id
> ef70eb16-cee2-455a-9804-3451cfe85e1e
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebphzcbtq3lmodbijwhohgezhxbstao6imhnxpido2nuqzklxufrk

**Comment by laurarenpanda** [comment]
checker:manualTrigger

**Comment by woshidama323** [comment]
checker:manualTrigger

**Comment by herrehesse** [comment]
checker:manualTrigger

**Comment by laurarenpanda** [comment]
checker:manualTrigger

**Comment by nj-steve** [comment]
the retrieval rate increase so fine.

**Comment by nj-steve** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecoc6ktpvzamn24ymqxdtyo5igdyxizdy72alzkugvko5o4kaqh5u 
#### Address 
> f1udumyw3yjzxuu5co4rateaq6czubrwbyy2t4jiq
#### Datacap Allocated
> 1000.00TiB
#### Signer Address
> f1xx6555qijma7igpnjspyvdunc4vfxkawnpqy5ii
#### Id
> 03f55812-bf25-4ee7-b7ba-36b69fe0d709
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecoc6ktpvzamn24ymqxdtyo5igdyxizdy72alzkugvko5o4kaqh5u

**Comment by a1991car** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb7qbwl3tbnc47zrst4x2o5kusm7awq7wkbnjbt6zb7c3otjtk5ay 
#### Address 
> f1udumyw3yjzxuu5co4rateaq6czubrwbyy2t4jiq
#### Datacap Allocated
> 1000.00TiB
#### Signer Address
> f1qnumecdypgrbaebtkdfjnwt5ndacadcuas3deiq
#### Id
> 03f55812-bf25-4ee7-b7ba-36b69fe0d709
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb7qbwl3tbnc47zrst4x2o5kusm7awq7wkbnjbt6zb7c3otjtk5ay

**Comment by Aaronn85** [comment]
checker:manualTrigger

**Comment by herrehesse** [comment]
checker:manualTrigger

**Comment by laurarenpanda** [comment]
Please keep this application open.

**Comment by laurarenpanda** [comment]
checker:manualTrigger

**Comment by data-programs** [comment]
<img width="32" alt="KYC" Verified src="https://stable.filplus.storage/images/filplus-kyc-verified-badge.png"/>

This user’s identity has been verified through [filplus.storage](https://filplus.storage)

**Comment by woshidama323** [comment]
checker:manualTrigger

**Comment by woshidama323** [comment]
LGTM about the result of report and retrieval success rate is also good 
Will support

**Comment by woshidama323** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedtnrey7xkq7oocbuazptx77q2yf6s74c5py4thvmed6g5q3rlypk 
#### Address 
> f1udumyw3yjzxuu5co4rateaq6czubrwbyy2t4jiq
#### Datacap Allocated
> 1.95PiB
#### Signer Address
> f12tk3adljauwnd3hjbigpfxb7b7gdlj63p6afwtq
#### Id
> c2acc050-7a11-4ca7-bcd7-840e8c5a2608
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedtnrey7xkq7oocbuazptx77q2yf6s74c5py4thvmed6g5q3rlypk

**Comment by Joss-Hua** [comment]
checker:manualTrigger

**Comment by Joss-Hua** [comment]
everything be okay

**Comment by Joss-Hua** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebpatu7ub5njme6bnisxuy4pfeixc7iolcj6xpls2h5z27ydpbr34 
#### Address 
> f1udumyw3yjzxuu5co4rateaq6czubrwbyy2t4jiq
#### Datacap Allocated
> 1.95PiB
#### Signer Address
> f1tfg54zzscugttejv336vivknmsnzzmyudp3t7wi
#### Id
> c2acc050-7a11-4ca7-bcd7-840e8c5a2608
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebpatu7ub5njme6bnisxuy4pfeixc7iolcj6xpls2h5z27ydpbr34

**Comment by laurarenpanda** [comment]
Please keep this application open.

**Comment by laurarenpanda** [comment]
Please keep this application open.

**Comment by laurarenpanda** [comment]
Please keep this application open.

**Comment by laurarenpanda** [comment]
Please keep this application open.

**Comment by laurarenpanda** [comment]
Please keep this application open.

**Comment by laurarenpanda** [comment]
checker:manualTrigger

**Comment by kernelogic** [comment]
CID report looks great, evenly distributed.

**Comment by kernelogic** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceankqsdslcoomv2cc4n3u6wmpxaigmjno2abkzbfobampornb6ptm 
#### Address 
> f1udumyw3yjzxuu5co4rateaq6czubrwbyy2t4jiq
#### Datacap Allocated
> 1.34PiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### Id
> 9979cccd-ca13-44fd-a86d-b99df9dcf47f
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceankqsdslcoomv2cc4n3u6wmpxaigmjno2abkzbfobampornb6ptm

**Comment by NiwanDao** [comment]
LGTM

**Comment by NiwanDao** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb34hstss2l3s4tc42kseh6mufxfm7x6ilput2xeswq2ezjyzhbvy 
#### Address 
> f1udumyw3yjzxuu5co4rateaq6czubrwbyy2t4jiq
#### Datacap Allocated
> 1.34PiB
#### Signer Address
> f1a2lia2cwwekeubwo4nppt4v4vebxs2frozarz3q
#### Id
> 9979cccd-ca13-44fd-a86d-b99df9dcf47f
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb34hstss2l3s4tc42kseh6mufxfm7x6ilput2xeswq2ezjyzhbvy

**Comment by herrehesse** [comment]
checker:manualTrigger

**Comment by herrehesse** [comment]
![Screenshot 2023-11-14 at 10 49 22](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/70132857/edd2f6ca-f0bc-4b2c-90b0-c5a00035ba1e)

Entity uses VPN to falsely distribute, its fake. Not happy seeing some trustworthy notaries sign this. @laurarenpanda you should take responsibility for you actions.

Close this LDN immediately @kevzak

**Comment by herrehesse** [comment]
![Screenshot 2023-11-14 at 10 50 50](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/70132857/4677363c-0746-4e52-a03e-be99404e9e74)

**Comment by Sunnyiscoming** [comment]
Hello, @laurarenpanda per the https://github.com/filecoin-project/notary-governance/issues/922 for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

This information will be reviewed by Fil+ Governance team to confirm validity and then the application will be allowed to move forward for additional notary review.

**Comment by ymhaihao** [comment]
| Provider  |                            Location | SP Entity or Personal |
| :-------- | ----------------------------------: | --------------------: |
| f02816095 |   Singapore |              KRAL |
| f02816081|   Singapore |              KRAL |
| f02829200 |  JiangXi|              applecould |
| f02833198 |    HK |              CoffeeCould |
| f02824533 |    HK |              CoffeeCould |
| f02837094 |    HK |              CoffeeCould |
| f02841613 |    HK |              CoffeeCould |
| f02824157 |   Shenzhen |             ZhongChuangYun |
| f02824140 |   Shenzhen |             ZhongChuangYun |
|f02829749 |    GuangDong|              Calculus |

**Comment by laurarenpanda** [comment]
Completed the form, Please take a look.

**Comment by Sunnyiscoming** [comment]
Please provide ID, City, Country, Organization of each SP here.

**Comment by laurarenpanda** [comment]
Please check SP List:
[{"providerID":"f02003888","City":"Singapore","Country":"Singapore","SPOrg","Force"},
{"providerID":"f02002888","City":"Tokyo","Country":"JAPAN","SPOrg","XYZ"},
{"providerID":"f02003866","City":"Singapore","Country":"Singapore","SPOrg","Oasis Global"},
{"providerID":"f01114587","City":"Tokyo","Country":"JAPAN","SPOrg","XYZ"},
{"providerID":"f0522948","City":"Singapore","Country":"Singapore","SPOrg","KY Tech"},
{"providerID":"f0867300","City":"Tokyo","Country":"JAPAN","SPOrg","IE Cloud"},
{"providerID":"f01228000","City":"Seoul","Country":"KR","SPOrg","KAK Dynamics"},
{"providerID":"f01228008","City":"Sydney","Country":"AU","SPOrg","BV Capital"},
{"providerID":"f02104858","City":"Hong Kong","Country":"HK","SPOrg","Nest Inew Limited"},
{"providerID":"f02006999","City":"Hong Kong","Country":"HK","SPOrg","Kun Yao"},
{"providerID":"f02003555","City":"Dallas","Country":"US","SPOrg","XYZ"},
{"providerID":"f02003333","City":"Dallas","Country":"US","SPOrg","XYZ"},
{"providerID":"f02002688","City":"Plano","Country":"US","SPOrg","XYZ"},
{"providerID":"f034548","City":"Plano","Country":"US","SPOrg","XYZ"},]

**Comment by laurarenpanda** [comment]
Please keep this application open.

**Comment by 1ane-1** [comment]
checker:manualTrigger

**Comment by 1ane-1** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebd5o4jtqxq6u5tutj6zvw56qw4ynam4owx6o7zolt2agcyhydk2u 
#### Address 
> f1udumyw3yjzxuu5co4rateaq6czubrwbyy2t4jiq
#### Datacap Allocated
> 1.34PiB
#### Signer Address
> f1mdk7s2vntzm6hu35yuo6vjubtrpfnb2awhgvrri
#### Id
> 9979cccd-ca13-44fd-a86d-b99df9dcf47f
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebd5o4jtqxq6u5tutj6zvw56qw4ynam4owx6o7zolt2agcyhydk2u

**Comment by mikezli** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebfs4wwr6u3asy3kfadibtr4nyux6lkaqrn7qa2zacegaddtugu5k 
#### Address 
> f1udumyw3yjzxuu5co4rateaq6czubrwbyy2t4jiq
#### Datacap Allocated
> 1.34PiB
#### Signer Address
> f1dnb3uz7sylxk6emti3ififcvu3nlufnnsjui6ea
#### Id
> 9979cccd-ca13-44fd-a86d-b99df9dcf47f
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebfs4wwr6u3asy3kfadibtr4nyux6lkaqrn7qa2zacegaddtugu5k

**Comment by laurarenpanda** [comment]
Please keep this open.

**Comment by laurarenpanda** [comment]
Please keep this application open.

**Comment by laurarenpanda** [comment]
Please keep this application open.

**Comment by laurarenpanda** [comment]
Please keep this application open.

**Comment by laurarenpanda** [comment]
Please keep this application open.
