### ISSUE TITLE
[DataCap Application] NOAA North American Mesoscale Forecast System

### ISSUE THREAD

**Issue by WisseHeyne** [filecoin-project/filecoin-plus-large-datasets#1689]
### Data Owner Name

NOAA

### Data Owner Country/Region

United States

### Data Owner Industry

Environment

### Website

https://www.noaa.gov/

### Social Media

```text
Twitter: https://twitter.com/NOAA
Facenook: https://www.facebook.com/NOAA
Ins: https://www.instagram.com/noaa/
Youtube: https://www.youtube.com/usnoaagov
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

400TiB

### On-chain address for first allocation

f1anpyrkoyzqxsv3glkjsvdnyiols7p4cajtwax7a

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
NOAA is an agency that enriches life through science. Their reach goes from the surface of the sun to the depths of the ocean floor as we work to keep the public informed of the changing environment around them.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
The North American Mesoscale Forecast System (NAM) is one of the National Centers For Environmental Prediction’s (NCEP) major models for producing weather forecasts. NAM generates multiple grids (or domains) of weather forecasts over the North American continent at various horizontal resolutions. Each grid contains data for dozens of weather parameters, including temperature, precipitation, lightning, and turbulent kinetic energy. NAM uses additional numerical weather models to generate high-resolution forecasts over fixed regions, and occasionally to follow significant weather events like hurricanes.
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### How do you plan to prepare the dataset

lotus, singularity

### Please share a sample of the data

```text
https://registry.opendata.aws/noaa-nam/
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Sporadic

### For how long do you plan to keep this dataset stored on Filecoin

2 to 3 years

### In which geographies do you plan on making storage deals

Asia other than Greater China, North America, South America, Europe

### How will you be distributing your data to storage providers

HTTP or FTP server, IPFS, Shipping hard drives

### How do you plan to choose storage providers

Slack, Filmine, Big data exchange, Partners

### How do you plan to make deals to your storage providers

Boost client, Lotus client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by lvschouwen** [comment]
Hi @WisseHeyne 

```
lucas@toolbox:~$ aws s3 ls --no-sign-request s3://noaa-nam-pds --recursive --human-readable --summarize
Total Objects: 11179028
   Total Size: 289.4 TiB
```

You are requesting 5 PiB datacap, so that means 17 copies roughly.
Can you share you storage plan?

**Comment by WisseHeyne** [comment]
@lvschouwen Our plan is preparing to store 12 copies in total. We'll provide maximum 2 copies to per SP entity and maximum of 12 copies for every pieceCID. Considering car padding, we requested 5 PiB datacap.

**Comment by Sunnyiscoming** [comment]
12 copies maybe too much. Can you tell me why you want to do this?
Can you introduce your organizaion? Please share more detailed information about sps you will cooperate with.

**Comment by WisseHeyne** [comment]
@Sunnyiscoming It is just a plan, we plan to store 12 copies at most. We'd like to let the meaningful data be stored distributedly in various places.

**Comment by Sunnyiscoming** [comment]
We prefer one application for one dataset. So I advice you reduce the amount of datacap requested.

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.


Can you fill out [this form](https://form.jotform.com/230337462961356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 5PiB

**Expected weekly DataCap usage rate**
> 400TiB

**Client address**
>f1anpyrkoyzqxsv3glkjsvdnyiols7p4cajtwax7a

**Comment by BobbyChoii** [comment]
Everything looks trusted and willing to support!  Enjoy your sealing!

**Comment by BobbyChoii** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceacl7epbvlmuebmdzwacn66qmq7w5glw6rbdnwnrhxezionwgc7x6 
#### Address 
> f1anpyrkoyzqxsv3glkjsvdnyiols7p4cajtwax7a
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1irqs2gmctiv3jcdfwuch7oxvf4ixh3k4b2wc24i
#### Id
> c5172b0a-1586-47f4-be7b-55b994b1894b
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceacl7epbvlmuebmdzwacn66qmq7w5glw6rbdnwnrhxezionwgc7x6

**Comment by OlivierMolenkamp** [comment]
DM received from the applicant and will keep an eye on your sps distribution. Thank you!

**Comment by OlivierMolenkamp** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebqablj2ak5cu7b2vs2xtcbe4ufosbsfdqzmhoahkyea3cosjdvns 
#### Address 
> f1anpyrkoyzqxsv3glkjsvdnyiols7p4cajtwax7a
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1fl5gjqv3xknuhka273jrsrkzqcumrp6idrnvgyi
#### Id
> c5172b0a-1586-47f4-be7b-55b994b1894b
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebqablj2ak5cu7b2vs2xtcbe4ufosbsfdqzmhoahkyea3cosjdvns

**Comment by cryptowhizzard** [comment]
Tagging here as no due diligence has been done.

@OlivierMolenkamp @BobbyChoii  please read [the governance team statement here](https://github.com/filecoin-project/notary-governance/issues/819)

[The policy has always been: ask a client to provide qualitative up-front evidence to justify they are real, have valid data, and can be trusted to engage in good deal-making; then perform subsequent quantitative analysis on their on-chain deal-making data.]

**Comment by RawTechVentures** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecsp7yqtghr46exgbmysr67hucczdvlomfshzxlmoewvksvq2t5lm 
#### Address 
> f1anpyrkoyzqxsv3glkjsvdnyiols7p4cajtwax7a
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1txfsjmix4vlzido4dkildrnbw26owtlbslexmpa
#### Id
> 3558d7c6-696c-4fed-8927-d5c4211bb039
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecsp7yqtghr46exgbmysr67hucczdvlomfshzxlmoewvksvq2t5lm

**Comment by Meibuy** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedndv65qgguizltmaoculseljuyuzsyjk5cw34qwiyofiuupf3sfi 
#### Address 
> f1anpyrkoyzqxsv3glkjsvdnyiols7p4cajtwax7a
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1bwugfihrmn3iyunzyxst5nttql3dge4khwmurtq
#### Id
> 3558d7c6-696c-4fed-8927-d5c4211bb039
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedndv65qgguizltmaoculseljuyuzsyjk5cw34qwiyofiuupf3sfi

**Comment by Meibuy** [comment]
checker:manualTrigger

**Comment by cryptowhizzard** [comment]
checker:manualTrigger

**Comment by cryptowhizzard** [comment]
checker:manualTrigger

**Comment by cryptowhizzard** [comment]
checker:manualTrigger

**Comment by cryptowhizzard** [comment]
checker:manualTrigger

**Comment by galen-mcandrew** [comment]
Curious why the SA bot is triggering, this address: f1anpyrkoyzqxsv3glkjsvdnyiols7p4cajtwax7a still has 600TiB of DataCap from the first 2 allocations (200+400) and no deal making behavior yet.

**Comment by spaceT9** [comment]
checker:manualTrigger

**Comment by spaceT9** [comment]
The CID report needs to be improved before next tranche

**Comment by spaceT9** [comment]
checker:manualTrigger

**Comment by Aaronn85** [comment]
checker:manualTrigger

**Comment by MarshLin88** [comment]
checker:manualTrigger

**Comment by WisseHeyne** [comment]
We are ready to restart our data transfer and more SPs are ready for storing. Can anyone help reopen the application?

**Comment by cryptowhizzard** [comment]
checker:manualTrigger

**Comment by Sunnyiscoming** [comment]
> This client is actively stalling http retrievals and blocked http ranged requests with a reverse proxy to prevent it's data being investigated.
> 
> It works as follows:
> 
> One set's a bandwidth limit with NGINX on the HTTP retrieval. After a random certain amount the limit is set to zero. This makes the transfer timeout. Because range retrieval is disabled in NGINX one cannot pick up where he left and needs to start all over again.
> 
> Log can be found at http://datasetcreators.com/downloadedcarfiles/logs/1689.log

Please explain about that.

**Comment by Filplus-govteam** [comment]
Hello @WisseHeyne per the new guidelines https://github.com/filecoin-project/notary-governance/issues/922 for Open Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

This information will be reviewed by Fil+ Governance team to confirm validity toward the Fil+ guideline of a distributed storage plan and SPs posted in the comments here. Let us know if you have any questions.

**Comment by WisseHeyne** [comment]
Hello @Sunnyiscoming , @cryptowhizzard 's words are wrong. I've asked SPs and they never use bandwidth limit with NGINX.

**Comment by WisseHeyne** [comment]
@Filplus-govteam done

**Comment by Sunnyiscoming** [comment]
f02207907 US 
f02218611 US
f02244750 GB 
f01232837 CN
f0146875 CN

**Comment by cryptowhizzard** [comment]
![Scherm­afbeelding 2023-08-25 om 16 17 06](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/36404435/f0e1208b-53c5-4ce7-808a-7531f70b1d0a)

Http://www.datasetcreators.com/downloadedcarfiles/httpretrievals/1689-f02057490-f02244750-46952876-baga6ea4seaqeu5jiheu4nvxesppyv24plbrr6bwu33w76ileoegpn2fjeafg2ja

Seems you are storing garbage data. From the part i could retrieve this is what your data looks like.

Application should be closed, datacap removed.

**Comment by cryptowhizzard** [comment]
![Scherm­afbeelding 2023-08-25 om 16 18 55](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/36404435/34a0dcee-0e99-4a3e-92ac-7b1925bfe95a)

**Comment by cryptowhizzard** [comment]
https://github.com/filecoin-project/notary-governance/issues/972

**Comment by WisseHeyne** [comment]
Absolutely gaslighting! 
This link is not available at all, I wonder where this guy came up with the so-called evidence.

> 
> [Http://www.datasetcreators.com/downloadedcarfiles/httpretrievals/1689-f02057490-f02244750-46952876-baga6ea4seaqeu5jiheu4nvxesppyv24plbrr6bwu33w76ileoegpn2fjeafg2ja](Http://www.datasetcreators.com/downloadedcarfiles/httpretrievals/1689-f02057490-f02244750-46952876-baga6ea4seaqeu5jiheu4nvxesppyv24plbrr6bwu33w76ileoegpn2fjeafg2ja)

**Comment by cryptowhizzard** [comment]
http://www.datasetcreators.com/downloadedcarfiles/httpretrievals/1689-f02057490-f02244750-46952876-baga6ea4seaqeu5jiheu4nvxesppyv24plbrr6bwu33w76ileoegpn2fjeafg2ja

link works here. Just copy / paste it in your browser.

For the rest I won't waste my time on you anymore.

**Comment by WisseHeyne** [comment]
@cryptowhizzard It is your duty as a notary to answer clients’ questions. Instead of only questioning everyone else.

**Comment by cryptowhizzard** [comment]
> @cryptowhizzard It is your duty as a notary to answer clients’ questions. Instead of only questioning everyone else.

I am sorry, but you are level kindergarten to me. I know you stole the candy, we all know, but you are in denial and you will stay in denial. Been there, done that.

It is 100% clear that you stored garbage. Sorry if you can't handle that.

**Comment by WisseHeyne** [comment]
But you are wrong. All you provided is not belong to my application. Just want you to check it again.

> > @cryptowhizzard It is your duty as a notary to answer clients’ questions. Instead of only questioning everyone else.
> 
> I am sorry, but you are level kindergarten to me. I know you stole the candy, we all know, but you are in denial and you will stay in denial. Been there, done that.
> 
> It is 100% clear that you stored garbage. Sorry if you can't handle that.

**Comment by Meibuy** [comment]
checker:manualTrigger

**Comment by WisseHeyne** [comment]
Yes open

**Comment by WisseHeyne** [comment]
Keep open.

**Comment by WisseHeyne** [comment]
Yes open

**Comment by kevzak** [comment]
SPs provided upfront
f02207907 | Tim | / | / | NewYork, US | no | tim
f02218611 | Dave | / | / | Virginia, US | no | Dave
f02244750 | Charlie | / | / | England, GB | no | Charlie
f01232837 | HaiGuo | | / | CN | no | /
f0146875 | Bob Lin | / | / | CN | no | Bob

**Comment by WisseHeyne** [comment]
@kevzak Hello Kevin, actually there's no VPN here. Next we will contact more sp's to participate in the storage, as the amount of data will increase thereafter.

**Comment by herrehesse** [comment]
![Screenshot 2023-11-14 at 10 47 42](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/70132857/35e4d490-8a1b-4456-ad9d-a85cc4a22ec8)

Why are you lying against the governance team about VPN use?
Close this LDN @kevzak

**Comment by Filplus-govteam** [comment]
checker:manualTrigger

**Comment by Filplus-govteam** [comment]
@WisseHeyne SP entity names and proof of location are needed here. Closing until updated
