### ISSUE TITLE
[DataCap Application] <Hepta> - <opendatalab>

### ISSUE THREAD

**Issue by yhkp** [filecoin-project/filecoin-plus-large-datasets#1693]
### Data Owner Name

Hepta

### Data Owner Country/Region

Korea, Republic of

### Data Owner Industry

Education & Training

### Website

https://opendatalab.org.cn/home

### Social Media

```text
N/A
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

500TiB

### On-chain address for first allocation

f1fi32zvoljht7ekcepglk7hleg2d3trf7wd7zvdi

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Hepta Labs joined Filecoin as an SP starting in 2021. In order to comply with Filecoin's plan to store the most important data of humanity, we transformed our business. We have gone through the preparatory phase and contacted nearly 20 SPs. Most expressed willingness to collaborate on our important data storage plan.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
Dataset content includes: automatic driving, openmmlab, classic benchmark, smart remote sensing, smart medical care, virtual reality, multimodality, openxdlab, smart education raw data and trained data sets will be backed up to 10 copies.
The types of data sets include: text, image, video, audio, etc.
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### How do you plan to prepare the dataset

IPFS, lotus, singularity

### Please share a sample of the data

```text
https://drive.google.com/file/d/1iiHAbqgDlveO3i9TfcZoJwDcpClZM1fB/view?usp=share_link
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

1.5 to 2 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, Europe

### How will you be distributing your data to storage providers

HTTP or FTP server, IPFS, Shipping hard drives, Lotus built-in data transfer

### How do you plan to choose storage providers

Slack, Partners

### If you already have a list of storage providers to work with, fill out their names and provider IDs below

```text
f01225882 US
f01959735 US
f01854080 US
f01543586 HK
f02033219 HK
f01985611 US
f01579009 KR
f01386984 CN
f01690643 KR
f02012175 KR
f01402814 HK
f01893023 US
```

### How do you plan to make deals to your storage providers

Boost client, Lotus client, Singularity

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by yhkp** [comment]
![](https://user-images.githubusercontent.com/121103586/220321595-f3b4abd5-29eb-4efb-9441-de141072ade6.png)

**Comment by Sunnyiscoming** [comment]
Where is your organization? China or Korea?
https://whois.whoisxmlapi.com/lookup-report/MK54nYeMRo
Domain's registrant
Name: 上海人工智能创新中心
Email: pjpublic@pjlab.org.cn

Waht's the relationship between you and the organization?

Can you provide more data samples? I try to download data samples you provided. But I can't open it.

**Comment by yhkp** [comment]
Hi, @Sunnyiscoming thank you for your prompt reply.
This website is a public dataset website, not our official website.
We will download the dataset from this website and store it in the Filecoin network.

We are a storage provider in the Korea, so I guess we don't need an official website. The business license that can verify my identity is already in the previous comment.

LMK if there is anything you confused.

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Can you fill out [this form](https://form.jotform.com/230337462961356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 5PiB

**Expected weekly DataCap usage rate**
> 500TiB

**Client address**
>f1fi32zvoljht7ekcepglk7hleg2d3trf7wd7zvdi

**Comment by SuperChaiChai** [comment]
See that the applicant has uploaded KYC certification

After sealing, a CID list can be shared for retrieval ？

**Comment by yhkp** [comment]
> See that the applicant has uploaded KYC certification
> 
> After sealing, a CID list can be shared for retrieval ？

@SuperChaiChai yes, it is our business license. Thanks for you attention.
Of course, we will make sure the data can be retrieved and SPs are reachable.

**Comment by Bitrise0111** [comment]
@yhkp Enough info for me. KYC done and SPs are reachable. 
Looking forward to see the CID checker. Willing to support for the first allocation.

**Comment by Bitrise0111** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecrh5ku6b35xqqjkoc5rrgwe2dpf66a4f5ofbpnjqpjbths6vydoi 
#### Address 
> f1fi32zvoljht7ekcepglk7hleg2d3trf7wd7zvdi
#### Datacap Allocated
> 250.00TiB
#### Signer Address
> f1nknj7ayq4o43czrtdoauggtwl43fbqatmqis3yy
#### Id
> 6483e815-f5af-4926-a3ce-5f4352ebd263
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecrh5ku6b35xqqjkoc5rrgwe2dpf66a4f5ofbpnjqpjbths6vydoi

**Comment by sxxfuture-official** [comment]
checker:manualTrigger

**Comment by fireflyHZ** [comment]
checker:manualTrigger

**Comment by sxxfuture-official** [comment]
checker:manualTrigger f1diyfoa4c3zy7goknerc4q7ogrq24xlzhoddiqbi f1fdall2v6xxtwgohunsybv7kypwoywuzftni5v4q f1d2op7ndmbevlthyonqntkxsg4a47qgliztvhj4i

**Comment by fireflyHZ** [comment]
Hi @yhkp, I read the report of the detection robot, I have a few questions for you to answer: Your app shared some data with several other apps reported before, can you explain why? In addition, the report shows that your data shows that the stored copies are not enough, and it is recommended that you store more copies.

**Comment by yhkp** [comment]
Hi there, really appreciate your follow-up.  @fireflyHZ 
As the lead SP of our project, I feel sorry for this issue. We are cooperating with other SPs to ensure the data is stored in various regions.  One of the sp has made some mistakes in daily operation, the Same as the other SP disclosed. I have talked with them, and I can assure you this mistake will not happen again. 
Besides, for the data replicates, different SPs with different upload speeds. However, it will be normal in the end. 
Looking forward your support!

**Comment by fireflyHZ** [comment]
@yhkp  Thank you for the quick reply. I tried spot-checking an SP check and it looks good. I will support you this time.

**Comment by fireflyHZ** [comment]
<img width="961" alt="mmexport1683281460186" src="https://user-images.githubusercontent.com/100905326/236431475-d81e631b-1c63-4799-aeb4-ef4486ed09f4.png">

**Comment by fireflyHZ** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceay2qvefwbtv4tmsfyicofkndx27ylbl65v4bkaq7ycfnqambm2rc 
#### Address 
> f1fi32zvoljht7ekcepglk7hleg2d3trf7wd7zvdi
#### Datacap Allocated
> 500.00TiB
#### Signer Address
> f1fg6jkxsr3twfnyhdlatmq36xca6sshptscds7xa
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceay2qvefwbtv4tmsfyicofkndx27ylbl65v4bkaq7ycfnqambm2rc

**Comment by zcfil** [comment]
checker:manualTrigger

**Comment by zcfil** [comment]
The report shows a small number of CID duplicates, which cannot appear according to the fil plus criterion. How is this caused? How to handle the centralized storage of LDN data in the later stage

**Comment by Joyologist** [comment]
This round is willing to support, the follow-up will continue to pay attention to the data situation

**Comment by Joyologist** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacediz5pw3t2dcafalixdkghtl5wtejxloulvdq6dldgiobfzrg6w7w 
#### Address 
> f1fi32zvoljht7ekcepglk7hleg2d3trf7wd7zvdi
#### Datacap Allocated
> 500.00TiB
#### Signer Address
> f1txboxiscdm4f3okffyjmbilmwjtbisrbee72j6q
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacediz5pw3t2dcafalixdkghtl5wtejxloulvdq6dldgiobfzrg6w7w

**Comment by yhkp** [comment]
Hey @zcfil 
Thanks for your attention. I really understand your concern. 
Please see the comment I reply yesterday. 


> Hi there, really appreciate your follow-up. @fireflyHZ
> As the lead SP of our project, I feel sorry for this issue. We are cooperating with other SPs to ensure the data is stored in various regions. One of the sp has made some mistakes in daily operation, the Same as the other SP disclosed. I have talked with them, and I can assure you this mistake will not happen again.
> Besides, for the data replicates, different SPs with different upload speeds. However, it will be normal in the end.
> Looking forward your support!

We will pay more attention to the storage provider we cooperate with.

**Comment by kernelogic** [comment]
checker:manualTrigger

**Comment by kernelogic** [comment]
CID report looks good. CID sharing is minimal and explained above.

**Comment by kernelogic** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecjndp5wcuo3so64mexcer6znt7lap7vi62yx3eez4v2igji2vw7k 
#### Address 
> f1fi32zvoljht7ekcepglk7hleg2d3trf7wd7zvdi
#### Datacap Allocated
> 1000.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### Id
> 390a288c-1c74-436d-881f-47a39f618bb3
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecjndp5wcuo3so64mexcer6znt7lap7vi62yx3eez4v2igji2vw7k

**Comment by laurarenpanda** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceapdd6n5k3rcueem3dkxgnl4gz56mhysjwvktqf477f4cscaxugd6 
#### Address 
> f1fi32zvoljht7ekcepglk7hleg2d3trf7wd7zvdi
#### Datacap Allocated
> 1000.00TiB
#### Signer Address
> f1bp3tzp536edm7dodldceekzbsx7zcy7hdfg6uzq
#### Id
> 390a288c-1c74-436d-881f-47a39f618bb3
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceapdd6n5k3rcueem3dkxgnl4gz56mhysjwvktqf477f4cscaxugd6

**Comment by yhkp** [comment]
Hi all notaries, 
I'm looking forward to your support. 
Issues in the checker have been fixed.  
There may be no retrieval rate since we haven't onboarded data a few months ago. 
Q from another application disclose here: 
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1731#issuecomment-1630318110

**Comment by herrehesse** [comment]
Retrieval Statistics
⚠️ All retrieval success ratios are below 1%.

Requesting notaries not to sign.

**Comment by yhkp** [comment]
Hi @cryptowhizzard 
Thanks for your attention. 
However, How can I improve the retrieval rate if notaries do not sign?
I already said that we haven't sent deals since a few months ago.  It should be restarted now, provided that notaries sign this round for us.

**Comment by yhkp** [comment]
checker:manualTrigger

**Comment by yhkp** [comment]
checker:manualTrigger

**Comment by cryptowhizzard** [comment]
I guess this won't end well. The SP's used are not OK. Everything is red is involved in CID sharing fairly recent and does not have retrieval enabled.

![Scherm­afbeelding 2023-08-01 om 08 54 07](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/36404435/ce4e447d-9a53-45c3-88a0-2213fa53c234)

**Comment by cryptowhizzard** [comment]
Tried again, it seems that there is some movement. I have been able to download something but it is not readable. All other methods of retrieval failed until now.

**Comment by cryptowhizzard** [comment]
See : http://datasetcreators.com/downloadedcarfiles/httpretrievals/1693-f02057953-f01834253-44634310-baga6ea4seaqn5jcteneyr62pm2nvgpztgbpg6gahia7ob3biwxk7nwozzybqaeq/
