### ISSUE TITLE
[DataCap Application] Huachu Cloud Storage Technology Co., LTD

### ISSUE THREAD

**Issue by licornduan** [filecoin-project/filecoin-plus-large-datasets#1699]
### Data Owner Name

Huachu Cloud Storage Technology Co., LTD

### Data Owner Country/Region

China

### Data Owner Industry

IT & Technology Services

### Website

pan.ipfshuzy.com

### Social Media

```text
www.ipfshczy.com
```

### Total amount of DataCap being requested

1PiB

### Weekly allocation of DataCap requested

10TiB

### On-chain address for first allocation

f1lzseynoswqw5zahhpkmrbymu5pm54wyklgaixsq

### Custom multisig

- [x] Use Custom Multisig

### Identifier

E-fil

### Share a brief history of your project and organization

```text
Founded in February 2014, Huachu Zhiyun (Beijing) Technology Service Co., Ltd. is headquartered in Zhongguancun Science and Technology Innovation Park (No. 38 Zhongguancun Street), Beijing, Capital of China. Provide reliable cloud disk services for web3 media and online education groups

huachu enterprise cloud disk  is one of several products of huachu cloud storage.  huachu provides our users with an unlimited number of file sharing services, which are mainly used for enterprise/individual collaborative work scenarios.
```

### Is this project associated with other projects/ecosystem stakeholders?

Yes

### Describe the data being stored onto Filecoin

```text
In huachu enterprise cloud disk, customers will create a large amount of content information in pdf/word, xmind/visio, videos, recording, whiteboard pictures, work and life photos, etc. 
huachu should help customers store these original content. We expect a huge amount of storage demand in the future, so we have been looking for safe, reliable and affordable storage service providers. 
IPFS & Filecoin is our best choice now.
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### If you answered "other/custom tool" in the previous question, enter the details here

```text
online & off-line.
```

### Please share a sample of the data

```text
lotus client retrieve --provider  f0508892 bafyreihjakbu5zefc23gsd6swhavmnop424pf4z2hgrde4gqd5y3yhyj34 ./file.pan

lotus client retrieve --provider f0508892  bafykbzacecxrfwk5q2n5qu3qnnnop23m6tiito7jat3kafdme4xl7mjaehd3w ./file2.pan
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [ ] I confirm

### What is the expected retrieval frequency for this data

Weekly

### For how long do you plan to keep this dataset stored on Filecoin

1 to 1.5 years

### In which geographies do you plan on making storage deals

Greater China

### How will you be distributing your data to storage providers

HTTP or FTP server

### How do you plan to choose storage providers

Partners

### If you already have a list of storage providers to work with, fill out their names and provider IDs below

```text
owner f081988
partner 
f023219
f0500878
f20489
f0157265
```

### How do you plan to make deals to your storage providers

Boost client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
Can you confirm that customers' data can be public. Are you authorized to store these data as public data on Filecoin network?
Please provide more data samples to prove that you have 5 PB data already.

**Comment by licornduan** [comment]
It can be confirmed that the customer's data is stored in encrypted mode and then uploaded to our node by boots client for encapsulation storage. I can ask the customer to upload more encrypted sample data to our test node for your audit

**Comment by licornduan** [comment]
bafykbzacecdukvv2mj3bvuapkbe3kkgz6xkoxt6at7hkt2g4t5mauvx4ku73a
bafykbzaceadina37okk52fff2362naku7liofvkfrxjc3uxmslwydqnxw4wbs
bafykbzacecdmcyqjcmm3qncz7lowksflw6szbst2hj4lezygghgerhd5kfdr2
bafykbzacebi65ufibhae3bphrrggyd4s3xk6wh4raqdohkckh35vl77do3pmc
bafykbzacecxrfwk5q2n5qu3qnnnop23m6tiito7jat3kafdme4xl7mjaehd3w
bafykbzacedzq662xbwoxt2ljbl5dsec22osyazepptcq4dajm3z67szutzlpa
bafykbzacecxrfwk5q2n5qu3qnnnop23m6tiito7jat3kafdme4xl7mjaehd3w
bafykbzacebxhqrjjyo2ygynpmk23xyoicevwqlbyptlwwt4djb62ghxqnubgq
bafykbzacebtbox64phdhthmw3vws4cdzenmsujqvdpaobcui4k3zsb22eaunu

CID above all is the history of the test sample data 

The data that needs to be stored has been authorized for public storage, and the data that needs to be encrypted is encrypted by the customer and then stored.

**Comment by cryptowhizzard** [comment]
Greetings!

Encrypted data should go to Fil-E

Please contact @kevzak

**Comment by kevzak** [comment]
@licornduan please see https://efilplus.super.site/ for more details, let me know if you have any questions.

**Comment by licornduan** [comment]
Encryption and public data will be separated, existing applications will be used for common business data storage, and application quota applications will be reduced.

@cryptowhizzard

I will contact him to do encryption business and apply for a new issue
@kevzak
