### ISSUE TITLE
[DataCap Application] NOAA CFS

### ISSUE THREAD

**Issue by Lunaluca** [filecoin-project/filecoin-plus-large-datasets#1700]
### Data Owner Name

National Oceanic and Atmospheric Administration

### Data Owner Country/Region

United States

### Data Owner Industry

Life Science / Healthcare

### Website

https://cfs.ncep.noaa.gov/

### Social Media

```text
https://twitter.com/NOAANCEI
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

400TiB

### On-chain address for first allocation

f1phb4y4oxfxmk5uyyqntoo2dbaqwjsszgn6h3rxi

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
The Climate Forecast System (CFS) is a model representing the global interaction between Earth's oceans, land, and atmosphere. Produced by several dozen scientists under guidance from the National Centers for Environmental Prediction (NCEP), this model offers hourly data with a horizontal resolution down to one-half of a degree (approximately 56 km) around Earth for many variables. CFS uses the latest scientific approaches for taking in, or assimilating, observations from data sources including surface observations, upper air balloon observations, aircraft observations, and satellite observations.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
Climate Forecast System (CFS) Model Data. The CFS was developed at the Environmental Modeling Center at NCEP. It is a fully coupled model representing the interaction between the Earth's atmosphere, oceans, land and seaice. https://registry.opendata.aws/noaa-cfs/
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### How do you plan to prepare the dataset

IPFS, lotus

### Please share a sample of the data

```text
s3://noaa-cfs-pds/cfs.20181031/00/6hrly_grib_01/pgbf2019042918.01.2018103100.grb2
s3://noaa-cfs-pds/cfs.20181031/00/6hrly_grib_04/flxf2019011518.04.2018103100.grb2.fdb5958a
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

1.5 to 2 years

### In which geographies do you plan on making storage deals

Asia other than Greater China, North America, South America, Europe

### How will you be distributing your data to storage providers

HTTP or FTP server, IPFS, Shipping hard drives

### How do you plan to choose storage providers

Slack, Big data exchange

### How do you plan to make deals to your storage providers

Boost client, Lotus client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
Please share a brief history of your project and organization. That means give more description about your organization.
Please provide more detailed information about sps you will coopeate with? Whether they can support data retrival?

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Looking at your application i have some questions:
As you are brand new on Github and have no history of past applications it seems to me that applying for 5PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?

Can you show us visible proof of the size of your data and the storage systems you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230337462961356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 5PiB

**Expected weekly DataCap usage rate**
> 400TiB

**Client address**
>f1phb4y4oxfxmk5uyyqntoo2dbaqwjsszgn6h3rxi

**Comment by TakiChain** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecue35nauifqdi5bc2zg4ts5fgdl4maaaz6l2bjhpnmr5v6lac3vq 
#### Address 
> f1phb4y4oxfxmk5uyyqntoo2dbaqwjsszgn6h3rxi
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f15impf3j2zcaex4lhyxndxswuuhv24vzstuqtxsi
#### Id
> 29c5bcaa-308f-4bca-bdea-88dd5200abde
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecue35nauifqdi5bc2zg4ts5fgdl4maaaz6l2bjhpnmr5v6lac3vq

**Comment by Protocan** [comment]
checker:manualTrigger

**Comment by Protocan** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb26g4besisb7nfzr5twkknkfv6pnln4gozoynyeq54tfjc3rugpg 
#### Address 
> f1phb4y4oxfxmk5uyyqntoo2dbaqwjsszgn6h3rxi
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1vxbqrf7rfum3n6m5u6eb4re6xj7amvsaqnzu64y
#### Id
> e378b488-8cc4-487b-b62b-b74cf46f5222
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb26g4besisb7nfzr5twkknkfv6pnln4gozoynyeq54tfjc3rugpg

**Comment by Meibuy** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecigwxetqqsvgxmt4zweac54gsoegiwxhg4xzvcty6valht7l3kca 
#### Address 
> f1phb4y4oxfxmk5uyyqntoo2dbaqwjsszgn6h3rxi
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1bwugfihrmn3iyunzyxst5nttql3dge4khwmurtq
#### Id
> e378b488-8cc4-487b-b62b-b74cf46f5222
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecigwxetqqsvgxmt4zweac54gsoegiwxhg4xzvcty6valht7l3kca

**Comment by TakiChain** [comment]
CID checker report is OK. Willing to suport!

**Comment by TakiChain** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecacg3ajftfmwdavrhpmepl6m5mn2x4is7m6rphtaxbentt5n3ed2 
#### Address 
> f1phb4y4oxfxmk5uyyqntoo2dbaqwjsszgn6h3rxi
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f15impf3j2zcaex4lhyxndxswuuhv24vzstuqtxsi
#### Id
> ab89bbb9-4b55-4900-a658-5fde97a98110
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecacg3ajftfmwdavrhpmepl6m5mn2x4is7m6rphtaxbentt5n3ed2

**Comment by Aifabot-Cloud** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceal5bndhanq55gufzwtv54vupknmgstx3d2s4gp5qbhavzxvus2xy 
#### Address 
> f1phb4y4oxfxmk5uyyqntoo2dbaqwjsszgn6h3rxi
#### Datacap Allocated
> 1.56PiB
#### Signer Address
> f174fg3bqbln3zjnkxtyf6s54txqkr7yqkj6cig7y
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceal5bndhanq55gufzwtv54vupknmgstx3d2s4gp5qbhavzxvus2xy

**Comment by cryptowhizzard** [comment]
Hello,

None of the data in this application is retrievable, this is against rules and guidelines of FIL+.
Secondly there is no Geographic distribution. "In which geographies do you plan on making storage deals
Asia other than Greater China, North America, South America, Europe"

Why did you sign on this @Aifabot-Cloud 

@Lunaluca , why are you using SP's who do not allow retrieval of data and why are you not following on the geographic distribution rules?

**Comment by Meibuy** [comment]
checker:manualTrigger

**Comment by Meibuy** [comment]
@Lunaluca  You need to improve this indicator of "Deal Data Replication" according to the rules of the community.

**Comment by cryptowhizzard** [comment]
@Meibuy and make the data retrievable according to the rules of Fil+

**Comment by BobbyChoii** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebhn6esu2rseg6obt5cflclaolj5c5srp5mloh2j647svgtkb4iae 
#### Address 
> f1phb4y4oxfxmk5uyyqntoo2dbaqwjsszgn6h3rxi
#### Datacap Allocated
> 1.56PiB
#### Signer Address
> f1irqs2gmctiv3jcdfwuch7oxvf4ixh3k4b2wc24i
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebhn6esu2rseg6obt5cflclaolj5c5srp5mloh2j647svgtkb4iae

**Comment by kevzak** [comment]
checker:manualTrigger

**Comment by Suyanj** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb7itia7lvocty6dubdr5dpbirvomex5tvtxu4hqgxk4hw67a6c6w 
#### Address 
> f1phb4y4oxfxmk5uyyqntoo2dbaqwjsszgn6h3rxi
#### Datacap Allocated
> 1.56PiB
#### Signer Address
> f1ihv7gz3vn3xqvikpt4rwryecgisl7745lodx3yi
#### Id
> 051ab7d7-bb6f-40dd-9169-fcdd5cd54eea
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb7itia7lvocty6dubdr5dpbirvomex5tvtxu4hqgxk4hw67a6c6w

**Comment by Casey-PG** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacede325d4cm7farv3becc7vjpzik2cvqk74kp2shrtb3sb4eoymkb4 
#### Address 
> f1phb4y4oxfxmk5uyyqntoo2dbaqwjsszgn6h3rxi
#### Datacap Allocated
> 1.56PiB
#### Signer Address
> f1d4yb3wags3mtddzesxoo63jv7dmlec3bq4yteni
#### Id
> 051ab7d7-bb6f-40dd-9169-fcdd5cd54eea
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacede325d4cm7farv3becc7vjpzik2cvqk74kp2shrtb3sb4eoymkb4

**Comment by Casey-PG** [comment]
Have received DM from this applicant and verified data samples, allocation plan. Would like to offer support for this round.

**Comment by Lunaluca** [comment]
ok, I want to keep it open

**Comment by Lunaluca** [comment]
ok, I want to keep it open

**Comment by clriesco** [comment]
Removed stale label and reopened issue :)

**Comment by Lunaluca** [comment]
@clriesco thank you :)

**Comment by Lunaluca** [comment]
ok. keep it open

**Comment by Lunaluca** [comment]
ok. keep it open

**Comment by Lunaluca** [comment]
ok. keep it open

**Comment by Bennyyangpu** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced3rqu45ozbjnrxcpcgsp55gxsnopgstqcjdug6cmin34wjtv5aok 
#### Address 
> f1phb4y4oxfxmk5uyyqntoo2dbaqwjsszgn6h3rxi
#### Datacap Allocated
> 525.11TiB
#### Signer Address
> f174fg3bqbln3zjnkxtyf6s54txqkr7yqkj6cig7y
#### Id
> cc76d1e2-7af8-4b49-9232-e5fe99eb51c4
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced3rqu45ozbjnrxcpcgsp55gxsnopgstqcjdug6cmin34wjtv5aok

**Comment by Wengeding** [comment]
LGTM, willing to support!

**Comment by Wengeding** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced22hv2tn4auwbm3c7pi66dxaxct5msq6ysyevfjlifrg23yubgpm 
#### Address 
> f1phb4y4oxfxmk5uyyqntoo2dbaqwjsszgn6h3rxi
#### Datacap Allocated
> 525.11TiB
#### Signer Address
> f1txfsjmix4vlzido4dkildrnbw26owtlbslexmpa
#### Id
> cc76d1e2-7af8-4b49-9232-e5fe99eb51c4
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced22hv2tn4auwbm3c7pi66dxaxct5msq6ysyevfjlifrg23yubgpm

**Comment by Sunnyiscoming** [comment]
Close for total datacap reached.
