### ISSUE TITLE
[DataCap Application]  Wuhan Jiusi Chuang Technology Co., Ltd.

### ISSUE THREAD

**Issue by sichaungjiu** [filecoin-project/filecoin-plus-large-datasets#1704]
### Data Owner Name

Wuhan Jiusi Chuang Technology Co., Ltd.

### Data Owner Country/Region

China

### Data Owner Industry

Web3 / Crypto

### Website

http://s04152.top/

### Social Media

```text
Official website:  http://s04152.top/
Projects we operate:
https://weibo.com/u/5696707241
https://weibo.com/u/7675236358
jinsecaijing column:
IOSG
DAOSquare
WCMD
```

### Total amount of DataCap being requested

3PiB

### Weekly allocation of DataCap requested

400TiB

### On-chain address for first allocation

f1szqeu5umnvjjner3bdim6axhp57clfhenlkyp3q

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Wuhan Jiusi Chuang Technology Co., Ltd. is a one-stop comprehensive blockchain project incubation landing marketing planning service brand, providing white paper writing, poster design, video production, all-media publicity, community operation/live broadcast for enterprises and individuals , Soft article/project evaluation writing, event planning, high-end interviews, foreign media publishing and other all-round support, and strive to build the largest blockchain project incubation and landing service platform in the country and even in the world.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
The data stored on the Filecoin network are precious materials such as copywriting, pictures, and videos output by our company employees when undertaking brand design and project marketing of major projects
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### How do you plan to prepare the dataset

IPFS, lotus, singularity

### Please share a sample of the data

```text
https://drive.google.com/drive/folders/1vJkFTTG3Qu9P1lfvNOWc7SB_vctTNtvd?usp=share_link
https://drive.google.com/drive/folders/1DTh0Hz1UPmrgyECN5IDi-lbW8uwm91Kr?usp=share_link
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Monthly

### For how long do you plan to keep this dataset stored on Filecoin

1.5 to 2 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, Africa, North America, South America, Europe

### How will you be distributing your data to storage providers

IPFS, Shipping hard drives, Lotus built-in data transfer

### How do you plan to choose storage providers

Slack, Filmine, Big data exchange

### How do you plan to make deals to your storage providers

Boost client, Lotus client, Singularity

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by sichaungjiu** [comment]
Last year, our application passed #1473, but our GitHub is gone, please help us， thank you!

**Comment by Sunnyiscoming** [comment]
There are more than 400 videos on the webaite. And it stopped updating since 2019.
I try to open them, but I failed. Please check it.
Media error: Format(s) not supported or source(s) not found
https://hx24-media.huoxing24.com/video/news/2019/08/30/20190830102126044376.mp4

The content of data samples you provided is not closely related with the content published on the website. Can you explain about that?

**Comment by sichaungjiu** [comment]
> 网站上有 400 多个视频。并且从2019年开始就停止更新了。 我尝试打开它们，但我失败了。请检查一下。 媒体错误：不支持格式或找不到来源 https://hx24-media.huoxing24.com/video/news/2019/08/30/20190830102126044376.mp4
> 
> 您提供的数据样本内容与本网站发布的内容没有密切关系。你能解释一下吗？

Yes, due to the adjustment of the company's policy, our platform did not update the video later, for three reasons:
1. In 2019, more and more people began to make videos. The fierce competition reduced our advantages in making videos, and the effect of videos on fan growth was weakened. Therefore, after September 2019, we decided to give up making videos.
2. As you can see, we have 480 videos and countless articles on the website, which take up space. In order to save storage costs, we paused video updates and deleted some videos.
3. Our platform has a total of 30,278 categories, about 29,520 of which are articles and newsletters. We hope to store all the content on the filecoin network.

**Comment by stcouldlisa** [comment]
<img width="933" alt="WX20230303-163914@2x" src="https://user-images.githubusercontent.com/112812896/222677336-4a526bfa-914d-4e44-ad42-385d79daee05.png">

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Looking at your application i have some questions:
As you are brand new on Github and have no history of past applications it seems to me that applying for 3PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?

Can you show us visible proof of the size of your data and the storage systems you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230337462961356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 3PiB

**Expected weekly DataCap usage rate**
> 400TiB

**Client address**
>f1szqeu5umnvjjner3bdim6axhp57clfhenlkyp3q

**Comment by TimGuo7** [comment]
<img width="496" alt="image" src="https://user-images.githubusercontent.com/94029052/224656524-f1e13cb2-0a57-4eca-ab90-cac20de0f840.png">
I have issue to access your website, anything wrong with it? 
and from above conversation, can you explain a bit more about why these data are valuable to the public to store into the Filecoin network, thanks.

**Comment by sichaungjiu** [comment]
Dear TimGuo7，after multiple confirmations by me and my colleagues, the website can be opened. It may be that you have turned on the vpn, or other reasons. Please try again, thank you!
<img width="989" alt="WX20230314-190457@2x" src="https://user-images.githubusercontent.com/126668912/224982582-f88bd09a-0e1e-4a93-b2a4-2e290908530e.png">
We are a web3 project, and we believe that there are three data types suitable for filecoin:
1. Web3 data
2. web2 and other traditional Internet data
3. Open data.
In general, web3 has a stronger overall acceptance and learning ability, and is more suitable for the filecoin network. Thank you for your question and hope to get your support.It makes me very sad that we don't have someone supporting us .Hope to get your enthusiastic help.

**Comment by cryptowhizzard** [comment]
> Dear applicant,
> 
> Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.
> 
> Looking at your application i have some questions: As you are brand new on Github and have no history of past applications it seems to me that applying for 3PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?
> 
> Can you show us visible proof of the size of your data and the storage systems you have there?
> 
> As last question i would like you to fill out [this form](https://form.jotform.com/230337462961356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.
> 
> Thanks!

Reminder!

**Comment by TimGuo7** [comment]
@cryptowhizzard this form is great, I am just wondering if you can share the info to the rest of notaries, maybe can share it here in the github?
 Have a list of these questions right out in this thread, it could be super helpful for the rest of notaries and save time for duplicated questions.

**Comment by sichaungjiu** [comment]
We filled out the form, @cryptowhizzard  @TimGuo7  can you help me?  We have applied for a long time。

**Comment by Fatman13** [comment]
checker:manualTrigger

**Comment by Fatman13** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceappooosifm5j2jol5pyrmnwwqoh42cp6ldeiiaasan44p4dx4lwo 
#### Address 
> f1szqeu5umnvjjner3bdim6axhp57clfhenlkyp3q
#### Datacap Allocated
> 153.59TiB
#### Signer Address
> f1j3u7crhjzwb2cj5mq7vodlt4o66yoyci7lhcauy
#### Id
> 1473f8fa-5231-492e-801c-bd1545191ea2
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceappooosifm5j2jol5pyrmnwwqoh42cp6ldeiiaasan44p4dx4lwo

**Comment by Fatman13** [comment]
I have been reached by this applicant on Slack and willing to support its first allocation.

**Comment by METAVERSEDATAMINING** [comment]
Hello,applicant
--What is your relationship with the organization, and do you have a way to prove it?
--Can you provide more detailed information about storage providers participated in this program, such as SP id ，region，etc.

**Comment by alllikes** [comment]
Hi, you can see our website, the cover of the poster on the website has a contact email address, we use the email sent from the contact email address on the poster, if necessary, this can fully prove our identity, even, you can specify any article (as long as the article fits the style of our website), we can publish it to the website today.

sp, we filled out the cryptowhizzard form yesterday, and it has been disclosed. Now, I will disclose our sps on github again: f01932183, f0198905, f02036170, f01900537, f01914991

**Comment by sichaungjiu** [comment]
1. Cooperative sps: f01932183, f0198905, f02036170, f01900537, f01914991

2. You can see our website. The cover of the poster on the website has a contact email address. We use the email sent from the contact email address on the poster, which can fully prove our identity.

3. Please help us

**Comment by METAVERSEDATAMINING** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebppqblx2uzcihff5v4wnvrqav6mpwx2gbbo5orxcdd5qnrxbpoaq 
#### Address 
> f1szqeu5umnvjjner3bdim6axhp57clfhenlkyp3q
#### Datacap Allocated
> 153.59TiB
#### Signer Address
> f17idrnfnxl2mbgcgr57a6z2c6lj2qx56gvm3336i
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebppqblx2uzcihff5v4wnvrqav6mpwx2gbbo5orxcdd5qnrxbpoaq

**Comment by newwebgroup** [comment]
checker:manualTrigger

**Comment by igoovo** [comment]
Can be retrieved normally and supported.

![WechatIMG104](https://user-images.githubusercontent.com/103082537/227703199-3475c0eb-adc2-4c43-82a6-8707d28e0112.jpeg)

![WechatIMG105](https://user-images.githubusercontent.com/103082537/227703209-cea63e21-bfaa-4dc8-977c-96099e2d2ae1.jpeg)

**Comment by igoovo** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedur3akqamevrcn7vw7bfg7ydpfz35tqfkyq3wm7dle5uez37jvke 
#### Address 
> f1szqeu5umnvjjner3bdim6axhp57clfhenlkyp3q
#### Datacap Allocated
> 307.19TiB
#### Signer Address
> f1shnsfayxqll77svffaxnjenms7bbbysbqcatrpy
#### Id
> c74f7797-2a52-4ccd-a0cd-afb5d04498a6
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedur3akqamevrcn7vw7bfg7ydpfz35tqfkyq3wm7dle5uez37jvke

**Comment by newwebgroup** [comment]
<img width="1144" alt="image" src="https://user-images.githubusercontent.com/100118145/227723878-6dc9c531-922c-4805-ba8c-3d00e36a9019.png">

https://filecoin.tools/f02085468

**Comment by newwebgroup** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec74utbwlznvywigz3nrp7kxbkiux2jdsl3bv537qqsauwpbcdz6g 
#### Address 
> f1szqeu5umnvjjner3bdim6axhp57clfhenlkyp3q
#### Datacap Allocated
> 307.19TiB
#### Signer Address
> f1e77zuityhvvw6u2t6tb5qlnsegy2s67qs4lbbbq
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec74utbwlznvywigz3nrp7kxbkiux2jdsl3bv537qqsauwpbcdz6g

**Comment by sxxfuture-official** [comment]
Check retrieve for deals : 
![image](https://user-images.githubusercontent.com/113963951/227829688-a4673a09-923e-4f8e-ae32-2551c337b9b5.png)

Result : 
![image](https://user-images.githubusercontent.com/113963951/227829763-6518b378-d88e-4dea-ba4c-a720a3895c94.png)

**Comment by sxxfuture-official** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacearynul3asfnx5blwva6iw22g4huv2sx5p6pnar4snq66cgpmxfjo 
#### Address 
> f1szqeu5umnvjjner3bdim6axhp57clfhenlkyp3q
#### Datacap Allocated
> 614.39TiB
#### Signer Address
> f1foiomqlmoshpuxm6aie4xysffqezkjnokgwcecq
#### Id
> 970cc172-eae9-4510-b773-fdbfe069175b
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacearynul3asfnx5blwva6iw22g4huv2sx5p6pnar4snq66cgpmxfjo

**Comment by laurarenpanda** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceddg7bissdbybqzgs7mdbsxoi4nxmw6hotqypw6swav4y327jdvfu 
#### Address 
> f1szqeu5umnvjjner3bdim6axhp57clfhenlkyp3q
#### Datacap Allocated
> 614.39TiB
#### Signer Address
> f1bp3tzp536edm7dodldceekzbsx7zcy7hdfg6uzq
#### Id
> 970cc172-eae9-4510-b773-fdbfe069175b
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceddg7bissdbybqzgs7mdbsxoi4nxmw6hotqypw6swav4y327jdvfu

**Comment by stcouldlisa** [comment]
checker:manualTrigger

**Comment by newwebgroup** [comment]
https://filecoin.tools/f02085468
<img width="1347" alt="image" src="https://user-images.githubusercontent.com/100118145/228500588-a433e604-a8ee-4bae-8468-f711afbf2b97.png">

**Comment by newwebgroup** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceahgelwyxpy6k4ccdo6zhq4hxdyb5klijjmhnj3sjj3clhhv5nrhi 
#### Address 
> f1szqeu5umnvjjner3bdim6axhp57clfhenlkyp3q
#### Datacap Allocated
> 1.20PiB
#### Signer Address
> f1e77zuityhvvw6u2t6tb5qlnsegy2s67qs4lbbbq
#### Id
> 9f13c368-17c1-4cf4-917f-dad154e13e69
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceahgelwyxpy6k4ccdo6zhq4hxdyb5klijjmhnj3sjj3clhhv5nrhi

**Comment by NDLABS-OFFICE** [comment]
<img width="886" alt="image" src="https://user-images.githubusercontent.com/104019147/228726170-f0520a65-f026-4730-a957-fd5bdab886c3.png">
check bot shows good, and check survey is successful, willing to support.

**Comment by NDLABS-OFFICE** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebcwduauzjvd2vjyfgntodn3r7fzpmkn7huoiec2l22mno66ufsh2 
#### Address 
> f1szqeu5umnvjjner3bdim6axhp57clfhenlkyp3q
#### Datacap Allocated
> 1.20PiB
#### Signer Address
> f1yayfsv6whu3rheviucvventj3y6t542xfpb47ei
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebcwduauzjvd2vjyfgntodn3r7fzpmkn7huoiec2l22mno66ufsh2

**Comment by a1991car** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebor6whqpwwi24ljurrxbntlejd5in5he4y6y4sqwls5scb6kotmi 
#### Address 
> f1szqeu5umnvjjner3bdim6axhp57clfhenlkyp3q
#### Datacap Allocated
> 768.02TiB
#### Signer Address
> f1qnumecdypgrbaebtkdfjnwt5ndacadcuas3deiq
#### Id
> 68948089-e96a-45c4-b34c-3f0a7941eb52
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebor6whqpwwi24ljurrxbntlejd5in5he4y6y4sqwls5scb6kotmi

**Comment by SuperChaiChai** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecfvpmhl3yghc7wgxwogc6jfrdhnbje7imsiq25mnoqk2vocnbp3m 
#### Address 
> f1szqeu5umnvjjner3bdim6axhp57clfhenlkyp3q
#### Datacap Allocated
> 768.02TiB
#### Signer Address
> f12mckci3omexgzoeosjvstcfxfe4vqw7owdia3da
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecfvpmhl3yghc7wgxwogc6jfrdhnbje7imsiq25mnoqk2vocnbp3m

**Comment by SuperChaiChai** [comment]
<img width="860" alt="image" src="https://user-images.githubusercontent.com/42091141/229676121-7e639e62-4395-4d6b-aef3-24c9438f053f.png">
