### ISSUE TITLE
Changsha Anze Intelligent Technology Co., Ltd

### ISSUE THREAD

**Issue by jekc2008** [filecoin-project/filecoin-plus-large-datasets#1705]
### Data Owner Name

anzev

### Data Owner Country/Region

China

### Data Owner Industry

IT & Technology Services

### Website

www.anzev.cn

### Social Media

```text
www.anzev.cn
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

100TiB

### On-chain address for first allocation

f1fth5mfxdcs6hwgpchy3fmoxsz5u6muvjlzcsygq

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
ANZEV CMS is a new core, and always advocates open source sharing, free enterprise information technology management system, including ERP, official website, applet

APP, IDC and IPFS decentralized storage are a set of efficient, simple and powerful ANZEV CMS source code that can be used for free and commercial use, and can meet various enterprise application networks

The needs of station development and construction. Solve the problems faced by the enterprise's online system, use system, operation and maintenance system, analysis system, and all information system-related data, software, and hardware

Difficulties and difficulties.

Our company has a group of research and refining teams focusing on JAVA, C #, DB, Linux, GO, RUST, network, etc., and has been engaged in the research of relevant disciplines for more than 10 years,

The main R&D center is located in Shenzhen, and the core members have the backbones of traditional industries and large companies, such as onet, ZTE, huawei, Mindray, APPO, etc.

We have an elite team with strong professional planning, design and execution capabilities, and will be committed to providing the best computer-related services for developers and enterprises

Develop and build solutions to enable enterprises to research their own products with more energy and assets. With its unique advantages in the fierce market competition, it stands alone in the same industry

Unique, highly praised by the industry and customers! Over the years, we have established good cooperative relations with well-known enterprises and companies in various industries. The company adheres to the principle of "achieving the future with heart,

The business philosophy of "beyond dreams, reputation first, and service foremost", vigorously promote innovative, efficient, high-quality, open-source, customized differentiated services, and strive to achieve customer cooperation

The goal of win-win for customers and market growth.

Our advantages:

1. Proficient in production, manufacturing, chain, real estate, distribution system analysis and research

We have the most representative products, including product analysis, design, development, testing, online, operation and maintenance solutions and successful cases

2. Service first

Solve customer problems, answer customer problems and avoid customer problems

3. Leading technology

Business continuity continued to be stable, 99.9% throughout the year

Business problem solving ability, 99.9%

Leading in processing business efficiency

4. Save time and effort

Reliable enterprise, conscientious enterprise, high-quality enterprise and ten-year quality
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
All kinds of open source system software demand analysis documents, product design, UI design, code writing, operation and maintenance documents, revision records and other software research in the early stage and online bug repair in the later stage, generate all data!
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### How do you plan to prepare the dataset

IPFS, lotus, singularity, graphsplit

### Please share a sample of the data

```text
product design 
https://drive.google.com/drive/folders/1_wvwvy6wxXQMNm_-Of535V3KgCekpdeM?usp=sharing
IDC 
https://drive.google.com/drive/folders/1swkHu7efwvRD05a30yw0dK8C6f42Uato?usp=sharing
image 
https://drive.google.com/drive/folders/1Ohw1boNjut7jNKM3N-W2Si4bQl8XK21Z?usp=sharing
Web development 
https://drive.google.com/drive/folders/1hiG_8jYG--QlXBlBnCgE5ty7k9N7KtlF?usp=sharing
APP development  
https://drive.google.com/drive/folders/1nfdCCMVVXLD2Uc4g5V808K0rojzuBaj7?usp=sharing
ERP development  
https://drive.google.com/drive/folders/1C88-2uxcyAuJL2myGHZ78wyjsBoK1kPJ?usp=sharing
FIL project   
https://drive.google.com/drive/folders/1FF9GCKbAxnTpGXkRVbtFlweGGQIxZU6t?usp=sharing
PS design 
https://drive.google.com/drive/folders/1DlIGbe6D3CjZIRuzoOKbrPrlqurmIw0N?usp=sharing
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

More than 3 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, Africa, North America, South America

### How will you be distributing your data to storage providers

Cloud storage (i.e. S3), HTTP or FTP server, IPFS, Shipping hard drives, Lotus built-in data transfer

### How do you plan to choose storage providers

Slack, Partners

### How do you plan to make deals to your storage providers

Boost client, Lotus client, Singularity

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
Data samples you provided contains data from different industry, like IT, diamond, real estate, etc.
Can you explain about the origin of these data?

There are some problems on your website. Can you explain about that?
![image](https://user-images.githubusercontent.com/105098820/222438411-aafc375c-271d-4a8e-83e8-bc792aa7db41.png) 
![image](https://user-images.githubusercontent.com/105098820/222438204-e488ebe9-3bb1-4e13-890c-da690686cf4b.png)

**Comment by jekc2008** [comment]
We provide services for all walks of life, including computer product demand analysis for customers,

Product design, system development, system operation, system operation and maintenance, our open source standard body

Department, from the beginning of demand to the launch of the system, all processes involved can be openly studied and discussed

Documents and data are convenient for the improvement and reference of the system.

We commit to open source standard framework, protect customer core data and core system, and let customers

Users spend less money, use better systems, and have their own source code,

You can modify and expand without restrictions.

**Comment by jekc2008** [comment]
![image](https://user-images.githubusercontent.com/95200129/222629947-88df91c4-80e4-493d-ad7a-ea12d4641ee8.png)
![image](https://user-images.githubusercontent.com/95200129/222630090-3f37c469-5808-463e-ac5d-c13326508a7a.png)

**Comment by jekc2008** [comment]
![image](https://user-images.githubusercontent.com/95200129/222630267-e35e0c85-91c3-4437-a7f2-460fd444d53c.png)

**Comment by jekc2008** [comment]
![image](https://user-images.githubusercontent.com/95200129/222630478-99e88951-d5e8-49b1-92fc-f59cd1111f52.png)

**Comment by jekc2008** [comment]
We have many open source codes and related documents in the industry, but these are just a few

**Comment by jekc2008** [comment]
Including transacted, not transacted, publicly available and non-public!

**Comment by jekc2008** [comment]
![image](https://user-images.githubusercontent.com/95200129/222674755-e8cfe262-dd07-4089-b345-1ee6e7a8d914.png)

**Comment by jekc2008** [comment]
![JW` C7B3W%{WQQ`{0RH{ABI](https://user-images.githubusercontent.com/95200129/222675297-322df8f6-d331-4889-bffa-afc771bb62a2.png)

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Can you show us visible proof of the size of your data and the storage systems you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230337462961356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 5PiB

**Expected weekly DataCap usage rate**
> 100TiB

**Client address**
>f1fth5mfxdcs6hwgpchy3fmoxsz5u6muvjlzcsygq

**Comment by jekc2008** [comment]
![image](https://user-images.githubusercontent.com/95200129/223604846-cf8f6e0f-f1e2-4580-a2cb-3962ad01f475.png)

**Comment by jekc2008** [comment]
Data case address, only individual demonstration, large data, sub-project, system, module
https://drive.google.com/drive/folders/1BlmfFXC6y3fCv4QYlTeAQXsP-0rDiKFE?usp=sharing
![image](https://user-images.githubusercontent.com/95200129/223605285-922b1ea8-a2ca-4c6f-b0cc-11799fbc0024.png)

**Comment by jekc2008** [comment]
![image](https://user-images.githubusercontent.com/95200129/223605442-5bd60b7c-ec58-4634-a5b6-b5d90336da8b.png)

**Comment by jekc2008** [comment]
Daily department, individual, company and technical data files
![image](https://user-images.githubusercontent.com/95200129/223605785-d930347e-2344-4ac4-91ff-1e57469b0e1d.png)

**Comment by jekc2008** [comment]
Our own IDC, enterprise application
![image](https://user-images.githubusercontent.com/95200129/223605899-b7c70977-6533-474b-8dc1-fd021b06a0c2.png)

**Comment by TimGuo7** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebwg4gf7oerskiovngcyjsifqsrl2ej2kxuwaqnqvbopujuiylkuq 
#### Address 
> f1fth5mfxdcs6hwgpchy3fmoxsz5u6muvjlzcsygq
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1yslbnnqzrjlyuxsmyxfbqcc7xthcavgpripjevi
#### Id
> 1a7c6f98-9ac5-430c-8d96-0903c2a1b596
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebwg4gf7oerskiovngcyjsifqsrl2ej2kxuwaqnqvbopujuiylkuq

**Comment by liyunzhi-666** [comment]
Based on the content in the application and the comments in the issue, I am willing to support the first round and will continue to monitor the allocation of customers.

**Comment by liyunzhi-666** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedip25cvy6nxinmy6jba2dm6pcs3bm4evwrxl7x2tea4mjyhb5mwk 
#### Address 
> f1fth5mfxdcs6hwgpchy3fmoxsz5u6muvjlzcsygq
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1pszcrsciyixyuxxukkvtazcokexbn54amf7gvoq
#### Id
> 1a7c6f98-9ac5-430c-8d96-0903c2a1b596
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedip25cvy6nxinmy6jba2dm6pcs3bm4evwrxl7x2tea4mjyhb5mwk

**Comment by jekc2008** [comment]
@simonkim0515 I haven't been paying attention to this, can you help me reopen it?

**Comment by simonkim0515** [comment]
@jekc2008 not a problem, please provide an update for community members and notaries on the status of your onboarding project. Thank you

**Comment by jekc2008** [comment]
Dear community members and notaries,
Previously delayed in storing data because it was in the process of organizing the data, it has now started and is looking for cooperative SPs one after another,Currently we work with the following SPs
f02215422  HK
f01836766  GZ,CN
f01877184  Singapore
f02062851  Californial,US

**Comment by Filplus-govteam** [comment]
ok @simonkim0515

**Comment by Filplus-govteam** [comment]
Let's see the SPs listed vs used 

Hello @jekc2008  Per the https://github.com/filecoin-project/notary-governance/issues/922 for Open, Public Dataset applicants, SP information will be reviewed by Fil+ Governance team to confirm validity and then the application will open for notary review. Let us know if you have any questions.

**Comment by jekc2008** [comment]
@Filplus-govteam  Hello, is there any progress here?
