### ISSUE TITLE
 Cabrina-HRRR Open Dataset <5/7>

### ISSUE THREAD

**Issue by NiwanDao** [filecoin-project/filecoin-plus-large-datasets#1709]
### Data Owner Name

Cabrina

### Data Owner Country/Region

United States

### Data Owner Industry

Life Science / Healthcare

### Website

https://dstorage.cabrina.xyz/

### Social Media

```text
https://dstorage.cabrina.xyz/
```

### Total amount of DataCap being requested

4PiB

### Weekly allocation of DataCap requested

800TiB

### On-chain address for first allocation

f1xyrlpfri2eiqgrubksca7djswzprlxfd3jxelqa

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
- I am an active participant in Slingshot and Slingshot Restore. This experience has gained me a lot of knowledge as a data preparer, deal SP, and retrieval client. 
- I have established a relationship with other community members along the way and have successfully sent deals with over 60 SPs worldwide.
- With the surge of requests from other SPs on deal-making and the value of storing humanity’s most important data permanently, I decided to bring HRRR datasets to the network.
- I will track deals and provide retrieval access through https://dstorage.cabrina.xyz/.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
> The High-Resolution Rapid Refresh (HRRR) is sourced by Global System Laboratory from National Oceanic && Atmospheric Administration. It is a NOAA real-time 3-km resolution, hourly updated, cloud-resolving, convection-allowing atmospheric model, initialized by 3km grids with 3km radar assimilation. Radar data is assimilated in the HRRR every 15 min over a 1-h period adding further detail to that provided by the hourly data assimilation from the 13km radar-enhanced Rapid Refresh. 
> HRRR dataset stored on AWS is the archive since 2014 with a total size of 2PiB and 38526457 Object.
> I plan to send 10x copies, each for 2PiB raw data. Since there is a conversion rate between the raw data size and Datacap consumption size, each copy would require around 3.5PiB Datacap, with a total amount of  35PiB Datacap.
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### How do you plan to prepare the dataset

graphsplit

### Please share a sample of the data

```text
https://registry.opendata.aws/noaa-hrrr-pds/
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Sporadic

### For how long do you plan to keep this dataset stored on Filecoin

1 to 1.5 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America

### How will you be distributing your data to storage providers

HTTP or FTP server, Shipping hard drives

### How do you plan to choose storage providers

Slack, Big data exchange, Partners

### If you already have a list of storage providers to work with, fill out their names and provider IDs below

```text
I work with SP including but not limited to FL cloud, GreaterHeat, Filet, Chenxi,Dong.I will continue look for new SP from the offline community and online BDE platform. 
The partner I previously worked with are listed in https://dstorage.cabrina.xyz/sp/
```

### How do you plan to make deals to your storage providers

Boost client, Lotus client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by xingjitansuo** [comment]
I filed a request allocation https://github.com/filecoin-project/notary-governance/issues/840 on different LDN shares the same address. The solution for now is closing the old one and open a new one with a different client address. See previous allocation on #https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1144 .

Since I have used 1PiB on previous address, I applied 4PiB this time.

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 4PiB

**Expected weekly DataCap usage rate**
> 800TiB

**Client address**
>f1xyrlpfri2eiqgrubksca7djswzprlxfd3jxelqa

**Comment by cryptowhizzard** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebggjnwnk7mvifhg77ybq5wexyfhfwhp7uovjax5xzkgigz3p6nas 
#### Address 
> f1xyrlpfri2eiqgrubksca7djswzprlxfd3jxelqa
#### Datacap Allocated
> 204.79TiB
#### Signer Address
> f1krmypm4uoxxf3g7okrwtrahlmpcph3y7rbqqgfa
#### Id
> 15f5ff17-3c0d-4b5b-8801-83a5d3549c5c
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebggjnwnk7mvifhg77ybq5wexyfhfwhp7uovjax5xzkgigz3p6nas

**Comment by xingjitansuo** [comment]
<img width="648" alt="截屏2023-04-01 下午3 46 38" src="https://user-images.githubusercontent.com/72185104/229273073-8e136335-df3f-4978-89a5-5f276c74ea5a.png">
f0203106 declared the IP address.

**Comment by newwebgroup** [comment]
<img width="1186" alt="image" src="https://user-images.githubusercontent.com/100118145/229298132-4debad42-ca6a-4bd5-9127-85d465b93ae2.png">

**Comment by newwebgroup** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceby5sxfzd23yfviqdeybb25wiafdgcni2db4feklmbqq4pg7hqvvs 
#### Address 
> f1xyrlpfri2eiqgrubksca7djswzprlxfd3jxelqa
#### Datacap Allocated
> 409.59TiB
#### Signer Address
> f1e77zuityhvvw6u2t6tb5qlnsegy2s67qs4lbbbq
#### Id
> b4616e7c-338a-4e9c-8edd-699de221ad7b
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceby5sxfzd23yfviqdeybb25wiafdgcni2db4feklmbqq4pg7hqvvs

**Comment by stcouldlisa** [comment]
<img width="935" alt="WechatIMG235" src="https://user-images.githubusercontent.com/112812896/229339781-12a9fa9a-3a61-43f3-81b6-b3394ce99764.png">

**Comment by stcouldlisa** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedti6whx4c4u2sysixgmrree4eowtqevgftlzo5drkvgmfzh37sks 
#### Address 
> f1xyrlpfri2eiqgrubksca7djswzprlxfd3jxelqa
#### Datacap Allocated
> 409.59TiB
#### Signer Address
> f1jvvltduw35u6inn5tr4nfualyd42bh3vjtylgci
#### Id
> b4616e7c-338a-4e9c-8edd-699de221ad7b
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedti6whx4c4u2sysixgmrree4eowtqevgftlzo5drkvgmfzh37sks

**Comment by caoyoungyoung** [comment]
checker:manualTrigger

**Comment by caoyoungyoung** [comment]
The CID report looks not good, any explanation before next tranche?
