### ISSUE TITLE
[DataCap Application] CabrinaHuang - Slingshot Restore Program

### ISSUE THREAD

**Issue by xingjitansuo** [filecoin-project/filecoin-plus-large-datasets#171]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
-Organization Name: CabrinaHuang-Slingshot Restore Program
-Website / Social Media: https://gnomad.broadinstitute.org/
-Total amount of DataCap being requested (between 500 TiB and 5 PiB): 500TiB
-Weekly allocation of DataCap requested (usually between 1-100TiB): 200TiB
-On-chain address for first allocation: f1lnecek42mynnu5ph7ucoikald2gucl6jty2ivty

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
The requested DataCap is for Slingshot Restore Program  hosted by the Slingshot teams as shown in 
Restore Program Description: https://docs.google.com/document/d/1sGLkw321Fl09jvAr80kFY2FcQWa1H-dYpowXFRWo-OM/edit?usp=sharing.
I participated as the client shown on https://docs.google.com/spreadsheets/d/1UYmVtwtJUIAwlogZmLSZB_nZxWrVlID6ryfqrB0jBjw/edit#gid=1779251844 
```

What is the primary source of funding for this project?
```
Slingshot Reward 

```

What other projects/ecosystem stakeholders is this project associated with?
```
n/a
```

## Use-case details

Describe the data being stored onto Filecoin
```
The Genome Aggregation Database (gnomAD), is a coalition of investigators seeking to aggregate and harmonize exome and genome sequencing data from a variety of large-scale sequencing projects, and to make summary data available for the wider scientific community.  
This was previously onboarded in Slingshot by others.
 
```

Where was the data in this dataset sourced from?
```
Pubic Datasets at https://gnomad.broadinstitute.org/downloads

```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
Please check at https://gnomad.broadinstitute.org/downloads
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
yes
```

What is the expected retrieval frequency for this data?
```
It depends on the Slingshot competition, probably few times per year.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
At least 500 days,

```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Most likely Asia,EU, NA. 

```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
I will distribute the data to 5 different SPs offline.

```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
Will end up with SP listed in https://docs.google.com/spreadsheets/d/1Skga2Yn0BD7CDgT1WQmKtPJ3nxhQ4QWd45e78Y42Wjc/edit#gid=0

```

How will you be distributing deals across storage providers?
```
Depends on SP's bandwidth. The plan is to distribute equally. 
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
yes
```

**Comment by galen-mcandrew** [comment]
## Multisig Notary requested
#### Total DataCap requested 
> 500TiB
#### Expected weekly DataCap usage rate 
> 200TiB

**Comment by flyworker** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedzci3gq2ii5jxqhwmgvlrryzr2dw2o3g64bnrrqhqrzswblgrdle 
#### Address 
> f1lnecek42mynnu5ph7ucoikald2gucl6jty2ivty
#### Datacap Allocated
> 25TiB
#### Signer Address
> f1hlubjsdkv4wmsdadihloxgwrz3j3ernf6i3cbpy
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedzci3gq2ii5jxqhwmgvlrryzr2dw2o3g64bnrrqhqrzswblgrdle

**Comment by neogeweb3** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecgeetvu6hqckug4hqyawupt7xc3xk4pe4ra2wpg57xgn2nylwpie 
#### Address 
> f1lnecek42mynnu5ph7ucoikald2gucl6jty2ivty
#### Datacap Allocated
> 25TiB
#### Signer Address
> f13k5zr6ovc2gjmg3lvd43ladbydhovpylcvbflpa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecgeetvu6hqckug4hqyawupt7xc3xk4pe4ra2wpg57xgn2nylwpie

**Comment by xingjitansuo** [comment]
Does anyone know why the status of ticket is "Error" ?

**Comment by dkkapur** [comment]
Looks like the allocation went through correctly. Address shows 25TiB of DataCap available.

Adjusting labels.

**Comment by xingjitansuo** [comment]
@dkkapur Thanks, but seems like 25Tib is not enough for me even for the first week. Could you please share me a reference on how the 25Tib is decided for this LDN, also what would be the process for next Datacap request ?

**Comment by galen-mcandrew** [comment]
@xingjitansuo At this time, all LDN's follow an allocation calculation plan, which is in the readme here on GitHub:

> First allocation: lesser of 5% of total DataCap requested or 50% of weekly allocation rate
Second allocation: lesser of 10% of total DataCap requested or 100% of weekly allocation rate
Third allocation onwards: lesser of 20% of total DataCap request or 200% of weekly allocation rate

Each allocation requires two signatures from the notaries on the multisig. Once you have used 75% of the previous allocation, a subsequent allocation bot will automatically kick off the next request for notaries to approve. Hope this helps clarify!

**Comment by xingjitansuo** [comment]
@galen-mcandrew 
Current available datacap is less than 75% (6.25Tib). Please help me to grant 100% of weekly allocation rate (200Tib) for the second round.

**Comment by galen-mcandrew** [comment]
> Second allocation: lesser of 10% of total DataCap requested or 100% of weekly allocation rate

Total requested is 500TiB, so 10% would be 50TiB, which is lower than 100% of weekly (200TiB)

**Comment by xingjitansuo** [comment]
> > Second allocation: lesser of 10% of total DataCap requested or 100% of weekly allocation rate
> 
> Total requested is 500TiB, so 10% would be 50TiB, which is lower than 100% of weekly (200TiB)

oh.. the text is a little bit confusing by the first look. I thought is either less than 10% of total DataCap or 100% of weekly allocation rate, and the bot has the option to take whichever is greater ...      Could you please help me on approving the request or at least recommend some other notaries approving this ?  really appreciated ...

**Comment by galen-mcandrew** [comment]
I understand, it can be confusing. It chooses the lesser option between the two. Looks like flyworker and neogeweb3 signed the first allocation, so you will need two different notaries. We had our notary governance call today and encouraged notaries to check for these large dataset requests. You can also post in Slack, direct message, or tag other notaries here.

**Comment by xingjitansuo** [comment]
For second round notaries, can I choose either flyworker or neogeweb3 ? or completely different notaries ? Also, what is the choosing rule for notaries on third rounds and onwards ?

**Comment by xingjitansuo** [comment]
@Fenbushi-Filecoin   @MegTei    @ozhtdong  @IreneYoung  @cryptowhizzard 
I noticed you are active recently.  Can you please help me on this? Thanks

**Comment by cryptowhizzard** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedkrcf4yow6qgsukqro7ks7lpzftwtgde2yb7zsafvlbo6cgzwlww 
#### Address 
> f1lnecek42mynnu5ph7ucoikald2gucl6jty2ivty
#### Datacap Allocated
> 50TiB
#### Signer Address
> f1krmypm4uoxxf3g7okrwtrahlmpcph3y7rbqqgfa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedkrcf4yow6qgsukqro7ks7lpzftwtgde2yb7zsafvlbo6cgzwlww

**Comment by flyworker** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaktoanqpt6aymj33j6v3ij7amhmkygh6xtyh7ywt4fsuhttpvor4 
#### Address 
> f1lnecek42mynnu5ph7ucoikald2gucl6jty2ivty
#### Datacap Allocated
> 50TiB
#### Signer Address
> f1hlubjsdkv4wmsdadihloxgwrz3j3ernf6i3cbpy
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaktoanqpt6aymj33j6v3ij7amhmkygh6xtyh7ywt4fsuhttpvor4

**Comment by galen-mcandrew** [comment]
> For second round notaries, can I choose either flyworker or neogeweb3 ? or completely different notaries ? Also, what is the choosing rule for notaries on third rounds and onwards ?

Ideally, you would have two net new notaries for the subsequent allocation. (Flyworker is just really motivated in helping improve the process and the Slingshot Restore program, which we appreciate 😅 ). For the third allocation, you could cycle back through to notaries from the first. Really we just don't want the same notary signing each _subsequent_ allocation. Every other allocation/alternating is the preferred.

**Comment by xingjitansuo** [comment]
@Reiers  @MegTei @neogeweb3 
can you please help me to sign this round? It is very urgent !!!

**Comment by flyworker** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb2irpbnpueryqoqj52h67buwl4524jfl5gsikewdthf3uenuqh3k 
#### Address 
> f1lnecek42mynnu5ph7ucoikald2gucl6jty2ivty
#### Datacap Allocated
> 100TiB
#### Signer Address
> f1hlubjsdkv4wmsdadihloxgwrz3j3ernf6i3cbpy
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb2irpbnpueryqoqj52h67buwl4524jfl5gsikewdthf3uenuqh3k

**Comment by cryptowhizzard** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecxq3xhxgqu7aju6q5crf4zg6ff7meu26jteg2kf3sucslqih2lg6 
#### Address 
> f1lnecek42mynnu5ph7ucoikald2gucl6jty2ivty
#### Datacap Allocated
> 100TiB
#### Signer Address
> f1krmypm4uoxxf3g7okrwtrahlmpcph3y7rbqqgfa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecxq3xhxgqu7aju6q5crf4zg6ff7meu26jteg2kf3sucslqih2lg6

**Comment by xingjitansuo** [comment]
@galen-mcandrew  @dkkapur 
Is there any way I can top up Total amount of requested DataCap from 500TiB to 700TiB ?
The rule for Slingshot- Restore client is to store the same files to SP located in 2 continents, 3 countries, and 5 cities. However, I accidentally send out 5 replicas to the the SP located in 1 continents and that apparently violates the rule, so I need to request more datacap to correct the error, and also count that potential mistake in future as to increase the total amount of Datacap.

**Comment by xingjitansuo** [comment]
@galen-mcandrew 
allocation bot was not triggered even I used up 75% of previous round, can you please help here?

**Comment by galen-mcandrew** [comment]
@xingjitansuo checking the [logs](https://plus.fil.org/logs) for this issue, when the bot checked at 2/2 9:38am the client address was still within the margins for DataCap usage, so it did not start the subsequent allocation request. Once the threshold was reached, the bot kicked off the next request for 200TiB (40% of total - 500TiB). 

It sounds like you are also requesting an increase to this total request, is that correct?

**Comment by xingjitansuo** [comment]
@galen-mcandrew 
Correct. I want to increase the total amount of datacap.

**Comment by neogeweb3** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecvixh2p5o2ongkq5qsrjnf3qmjfd7rkjmyg3ijh3xtbpwbmfpquy 
#### Address 
> f1lnecek42mynnu5ph7ucoikald2gucl6jty2ivty
#### Datacap Allocated
> 200TiB
#### Signer Address
> f13k5zr6ovc2gjmg3lvd43ladbydhovpylcvbflpa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecvixh2p5o2ongkq5qsrjnf3qmjfd7rkjmyg3ijh3xtbpwbmfpquy

**Comment by swatchliu** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedrbxznvamqakvhr7e63egudjxlk6wlpoiye7ghmjhddrlwt34sxw 
#### Address 
> f1lnecek42mynnu5ph7ucoikald2gucl6jty2ivty
#### Datacap Allocated
> 200TiB
#### Signer Address
> f1yh6q3nmsg7i2sys7f7dexcuajgoweudcqj2chfi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedrbxznvamqakvhr7e63egudjxlk6wlpoiye7ghmjhddrlwt34sxw

**Comment by MegTei** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedfuqxih3z52xm4zfpzapu3o7y7cwuspbqpqpmrlotnjnndmti2cg 
#### Address 
> f1lnecek42mynnu5ph7ucoikald2gucl6jty2ivty
#### Datacap Allocated
> 125.00TiB
#### Signer Address
> f1ystxl2ootvpirpa7ebgwl7vlhwkbx2r4zjxwe5i
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedfuqxih3z52xm4zfpzapu3o7y7cwuspbqpqpmrlotnjnndmti2cg

**Comment by cryptowhizzard** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecaxv2edznuxrwog5moi6wtzmnfrossyas2s4tewfj5dsz44bp5cg 
#### Address 
> f1lnecek42mynnu5ph7ucoikald2gucl6jty2ivty
#### Datacap Allocated
> 125.00TiB
#### Signer Address
> f1krmypm4uoxxf3g7okrwtrahlmpcph3y7rbqqgfa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecaxv2edznuxrwog5moi6wtzmnfrossyas2s4tewfj5dsz44bp5cg

**Comment by dkkapur** [comment]
Closing this one out since all the DataCap was allocated!

**Comment by filplus-checker** [comment]
## DataCap and CID Checker Report[^1]
 - Organization: ``
 - Client: `f1lnecek42mynnu5ph7ucoikald2gucl6jty2ivty`
### Storage Provider Distribution
The below table shows the distribution of storage providers that have stored data for this client.

If this is the first time a provider takes verified deal, it will be marked as `new`.

For most of the datacap application, below restrictions should apply.
 - Storage provider should not exceed 25% of total datacap.
 - Storage provider should not be storing duplicate data for more than 20%.
 - Storage provider should have published its public IP address.
 - All storage providers should be located in different regions.

⚠️ [f020378](https://filfox.info/en/address/f020378) has unknown IP location.

| Provider                                                    |                          Location | Total Deals Sealed | Percentage | Unique Data | Duplicate Deals |
| :---------------------------------------------------------- | --------------------------------: | -----------------: | ---------: | ----------: | --------------: |
| [f01652333](https://filfox.info/en/address/f01652333)`new`  |         Sunnyvale, California, US |          94.63 TiB |     19.14% |   94.63 TiB |           0.00% |
| [f066596](https://filfox.info/en/address/f066596)           |         San Diego, California, US |          55.03 TiB |     11.13% |   55.03 TiB |           0.00% |
| [f01392893](https://filfox.info/en/address/f01392893)       |      Amsterdam, North Holland, NL |          45.19 TiB |      9.14% |   43.24 TiB |           4.32% |
| [f01702940](https://filfox.info/en/address/f01702940)       |                 Dallas, Texas, US |          39.93 TiB |      8.08% |   39.93 TiB |           0.00% |
| [f01385207](https://filfox.info/en/address/f01385207)       |             Lincoln, Nebraska, US |          39.18 TiB |      7.92% |   39.18 TiB |           0.00% |
| [f097777](https://filfox.info/en/address/f097777)           |               Kivertsi, Volyn, UA |          38.03 TiB |      7.69% |   38.00 TiB |           0.08% |
| [f01157288](https://filfox.info/en/address/f01157288)`new`  |       Sydney, New South Wales, AU |          31.44 TiB |      6.36% |   31.44 TiB |           0.00% |
| [f01558688](https://filfox.info/en/address/f01558688)       |              Toronto, Ontario, CA |          26.98 TiB |      5.46% |   25.64 TiB |           4.98% |
| [f01863339](https://filfox.info/en/address/f01863339)       |            Shanghai, Shanghai, CN |          21.13 TiB |      4.27% |   21.13 TiB |           0.00% |
| [f08403](https://filfox.info/en/address/f08403)             | Bourton on the Water, England, GB |          17.75 TiB |      3.59% |   17.75 TiB |           0.00% |
| [f01611097](https://filfox.info/en/address/f01611097)       |      San Clemente, California, US |          16.81 TiB |      3.40% |   16.25 TiB |           3.35% |
| [f01163272](https://filfox.info/en/address/f01163272)       |               Perm, Perm Krai, RU |          16.69 TiB |      3.38% |   16.69 TiB |           0.00% |
| [f020378](https://filfox.info/en/address/f020378)           |                           Unknown |          15.26 TiB |      3.09% |   14.94 TiB |           2.05% |
| [f08399](https://filfox.info/en/address/f08399)             |           Seattle, Washington, US |          11.20 TiB |      2.27% |   11.20 TiB |           0.00% |
| [f010617](https://filfox.info/en/address/f010617)           |      Surrey, British Columbia, CA |          10.77 TiB |      2.18% |   10.77 TiB |           0.00% |
| [f01208189](https://filfox.info/en/address/f01208189)       |       Sydney, New South Wales, AU |           7.66 TiB |      1.55% |    7.66 TiB |           0.00% |
| [f014768](https://filfox.info/en/address/f014768)           |          Singapore, Singapore, SG |           6.09 TiB |      1.23% |    6.09 TiB |           0.00% |
| [f01662887](https://filfox.info/en/address/f01662887)       |          Singapore, Singapore, SG |         384.00 GiB |      0.08% |  384.00 GiB |           0.00% |
| [f01345523](https://filfox.info/en/address/f01345523)       |           Antwerpen, Flanders, BE |         256.00 GiB |      0.05% |  256.00 GiB |           0.00% |

![Provider Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/171/1671093404399.png)
### Deal Data Replication
The below table shows how each many unique data are replicated across storage providers.
- No more than 25% of unique data are stored with less than 4 providers.

✔️ Data replication looks healthy.

| Unique Data Size | Total Deals Made | Number of Providers | Deal Percentage |
| ---------------: | ---------------: | ------------------: | --------------: |
|        21.32 TiB |        21.32 TiB |                   1 |           4.31% |
|       832.00 GiB |         1.63 TiB |                   2 |           0.33% |
|        15.04 TiB |        45.30 TiB |                   3 |           9.16% |
|        40.20 TiB |       161.69 TiB |                   4 |          32.70% |
|        51.93 TiB |       262.77 TiB |                   5 |          53.15% |
|       288.00 GiB |         1.69 TiB |                   6 |           0.34% |

![Replication Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/171/1671093405172.png)
### Deal Data Shared with other Clients
The below table shows how many unique data are shared with other clients.
Usually different applications owns different data and should not resolve to the same CID.

⚠️ CID sharing has been observed.

| Other Client                                                                                                          | Application                                                                                                                     | Total Deals Affected | Unique CIDs |    Verifier |
| :-------------------------------------------------------------------------------------------------------------------- | :------------------------------------------------------------------------------------------------------------------------------ | -------------------: | ----------: | ----------: |
| [f1zil5gn6fgelxw5lb7sbv22eayfltg7eohcrqpni](https://filfox.info/en/address/f1zil5gn6fgelxw5lb7sbv22eayfltg7eohcrqpni) | [CabrinaHuang\-Xingjitansuo](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/232)                       |           754.03 TiB |         676 |   LDN # 232 |
| [f1c2nxtixkivuzmmezwawg4nwzoknvd7hto37cy4q](https://filfox.info/en/address/f1c2nxtixkivuzmmezwawg4nwzoknvd7hto37cy4q) | [CabrinaHuang\-Slingshot Restore Program](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/249)          |            95.22 TiB |       2,390 |   LDN # 249 |
| [f1pkrmygbvweykpjcut36lf7ewgqdfhjklbhvepda](https://filfox.info/en/address/f1pkrmygbvweykpjcut36lf7ewgqdfhjklbhvepda) | [Protocol Labs \( project: Slingshot Evergreen \)](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/293) |             3.19 TiB |         100 |   LDN # 293 |
| [f12m4wzu4ynkpilkh5bv4zaadigmr6hml4zg46dhq](https://filfox.info/en/address/f12m4wzu4ynkpilkh5bv4zaadigmr6hml4zg46dhq) | [Chengdu Sinso Technology Co\., Ltd\.](https://github.com/filecoin-project/filecoin-plus-client-onboarding/issues/485)          |            32.00 GiB |           1 | Zhehao Chen |

[^1]: To manually trigger this report, add a comment with text `checker:manualTrigger`
