### ISSUE TITLE
[DataCap Application] FileGuard - Autonomous Driving Open Datasets Archive

### ISSUE THREAD

**Issue by cryptomandy** [filecoin-project/filecoin-plus-large-datasets#1711]
### Data Owner Name

FileGuard

### Data Owner Country/Region

China

### Data Owner Industry

Web3 / Crypto

### Website

https://fileguard.io

### Social Media

```text
N/A
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

500TiB

### On-chain address for first allocation

f1o27reuxezrfhymyt2jbmuxabf3xupkrkzvhfu5i

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
As a machine learning & deep learning training data provider, FileGuard provide a complete data solution of "software + hardware", Help algorithm companies collect and check data. A complete set of solutions for cleaning, desensitization, labeling, storing, transfer, etc. FileGuard have served more than 30 artificial intelligence enterprise customers since 2018, suce as Face++, SenseTime, JD finance and so on, providing customers with more than 20 million image annotation data, and about 200,000 crowdsourcers working on the FileGuard platform.

As a platform all in Web3, We have been engaged with storing real and valuable machine learning & deep learning datasets on the Filecoin network. We focus on the three areas of artificial intelligence: computer vision(CV), natural language processing(NLP) and speech processing. We believe that the Web3 way of storing these valuable data, such as autonomous driving, cancer, disease, geographic, agriculture, speech, and NLP data, will bring huge changes.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
This application including 4 AWS open dataset focus on autonomous driving:

1. Boreas Autonomous Driving Dataset
LINK: https://registry.opendata.aws/boreas/
This autonomous driving dataset includes data from a 128-beam Velodyne Alpha-Prime lidar, a 5MP Blackfly camera, a 360-degree Navtech radar, and post-processed Applanix POS LV GNSS data.

2. A2D2: Audi Autonomous Driving Dataset
LINK: https://registry.opendata.aws/aev-a2d2/
An open multi-sensor dataset for autonomous driving research. This dataset comprises semantically segmented images, semantic point clouds, and 3D bounding boxes.

3. KITTI Vision Benchmark Suite
https://registry.opendata.aws/kitti/
Dataset and benchmarks for computer vision research in the context of autonomous driving. The dataset has been recorded in and around the city of Karlsruhe, Germany using the mobile platform AnnieWay (VW station wagon) which has been equipped with several RGB and monochrome cameras, a Velodyne HDL 64 laser scanner as well as an accurate RTK corrected GPS/IMU localization unit.

4. Ford Multi-AV Seasonal Dataset
LINK: https://registry.opendata.aws/ford-multi-av-seasonal/
This research presents a challenging multi-agent seasonal dataset collected by a fleet of Ford autonomous vehicles at different days and times during 2017-18.
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### How do you plan to prepare the dataset

lotus, singularity, graphsplit

### Please share a sample of the data

```text
https://registry.opendata.aws/boreas/
https://registry.opendata.aws/aev-a2d2/
https://registry.opendata.aws/ford-multi-av-seasonal/
https://registry.opendata.aws/kitti/
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

2 to 3 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, Europe

### How will you be distributing your data to storage providers

Cloud storage (i.e. S3), HTTP or FTP server

### How do you plan to choose storage providers

Slack, Partners

### If you already have a list of storage providers to work with, fill out their names and provider IDs below

```text
| MinerID   | City       | Continent | Business/Entity |
| --------- | ---------- | --------- | -------- |
| f01824405 | ChengDu    | CN        | RY       |
| f01991416 | HongKong   | CN        | RIKIMARU |
| f02012032 | HongKong   | CN        | RIKIMARU |
| f02006691 | HongKong   | CN        | NIHICHE  |
| f02027952 | London     | UK        | Mochi    |
| f02014107 | Seoul      | KR        | HMT      |
| f02028326 | California | USA       | Fyii     |
```

### How do you plan to make deals to your storage providers

Boost client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.


Can you fill out [this form](https://form.jotform.com/230337462961356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!

**Comment by cryptomandy** [comment]
> Dear applicant,
> 
> Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.
> 
> Can you fill out [this form](https://form.jotform.com/230337462961356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.
> 
> Thanks!

Hello @cryptowhizzard, the KYC form has submitted.

Thanks!

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 5PiB

**Expected weekly DataCap usage rate**
> 500TiB

**Client address**
>f1o27reuxezrfhymyt2jbmuxabf3xupkrkzvhfu5i

**Comment by cryptowhizzard** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceahxk6w3zdk2lo5g3cbc4hashktwct5bcquewzfgqy6jlghrtr2by 
#### Address 
> f1o27reuxezrfhymyt2jbmuxabf3xupkrkzvhfu5i
#### Datacap Allocated
> 250.00TiB
#### Signer Address
> f1krmypm4uoxxf3g7okrwtrahlmpcph3y7rbqqgfa
#### Id
> 50a7b2ce-56c2-451c-9fd1-f06335df5424
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceahxk6w3zdk2lo5g3cbc4hashktwct5bcquewzfgqy6jlghrtr2by

**Comment by kernelogic** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb4louds7ap2biuhdnu2k5i3aoiffebft6awr4o3hxuhdim4ldjgk 
#### Address 
> f1o27reuxezrfhymyt2jbmuxabf3xupkrkzvhfu5i
#### Datacap Allocated
> 250.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### Id
> 50a7b2ce-56c2-451c-9fd1-f06335df5424
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb4louds7ap2biuhdnu2k5i3aoiffebft6awr4o3hxuhdim4ldjgk

**Comment by cryptomandy** [comment]
checker:manualTrigger

**Comment by cryptomandy** [comment]
checker:manualTrigger

**Comment by Normalnoise** [comment]
checker:manualTrigger

**Comment by Normalnoise** [comment]
@cryptomandy cid checker has tell me your storage is healthy, but I think you need to send deals to more storage providers  and more region SPs.If you can not contact other region SPs, you can using [swan-provider](https://github.com/FogMeta/go-swan-provider) to find more SPs around the world. if you have some questions, you can visit the #fil-filswan channel in the slack. Based on the current situation, I am willing to support you in this round

**Comment by Fatman13** [comment]
checker:manualTrigger

**Comment by Fatman13** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceda325ikqvujytptq3kfgofxkfatnzdepa5zcz2tmvq4r5ijueepo 
#### Address 
> f1o27reuxezrfhymyt2jbmuxabf3xupkrkzvhfu5i
#### Datacap Allocated
> 500.00TiB
#### Signer Address
> f1j3u7crhjzwb2cj5mq7vodlt4o66yoyci7lhcauy
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceda325ikqvujytptq3kfgofxkfatnzdepa5zcz2tmvq4r5ijueepo

**Comment by Fatman13** [comment]
I have been reached by the applicant on Slack and this LDN check all the boxes. Will support.

**Comment by Normalnoise** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedwwru6svbccnd24gd3bnv5ufd6upumdilgegvibeeahroobrjjws 
#### Address 
> f1o27reuxezrfhymyt2jbmuxabf3xupkrkzvhfu5i
#### Datacap Allocated
> 500.00TiB
#### Signer Address
> f1c5non5yf35avgcpsqvxu4yj54yyvxorwyjochqq
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedwwru6svbccnd24gd3bnv5ufd6upumdilgegvibeeahroobrjjws

**Comment by cryptomandy** [comment]
checker:manualTrigger

**Comment by cryptomandy** [comment]
checker:manualTrigger

**Comment by cryptomandy** [comment]
checker:manualTrigger

**Comment by cryptomandy** [comment]
checker:manualTrigger

**Comment by cryptomandy** [comment]
checker:manualTrigger

**Comment by cryptomandy** [comment]
checker:manualTrigger

**Comment by sxxfuture-official** [comment]
checker:manualTrigger

**Comment by sxxfuture-official** [comment]
CID checker shows everything healthy, and retrieve test result as follows:
![image](https://user-images.githubusercontent.com/113963951/236364894-55e763b8-78ab-45e8-81c7-c74a879ea35a.png)

deal_id from [https://filecoin.tools/f02060396](https://filecoin.tools/f02060396)

**Comment by sxxfuture-official** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedqhxgofahbglbga7hdonzwoquktaw7q3w4y2wo2q4xmubiigl2xa 
#### Address 
> f1o27reuxezrfhymyt2jbmuxabf3xupkrkzvhfu5i
#### Datacap Allocated
> 1000.00TiB
#### Signer Address
> f1foiomqlmoshpuxm6aie4xysffqezkjnokgwcecq
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedqhxgofahbglbga7hdonzwoquktaw7q3w4y2wo2q4xmubiigl2xa

**Comment by cryptomandy** [comment]
checker:manualTrigger

**Comment by cryptomandy** [comment]
checker:manualTrigger

**Comment by cryptomandy** [comment]
checker:manualTrigger

**Comment by cryptomandy** [comment]
checker:manualTrigger

**Comment by cryptomandy** [comment]
checker:manualTrigger

**Comment by spaceT9** [comment]
checker:manualTrigger

**Comment by spaceT9** [comment]
Cid report of last round looks healthy, signing the next tranche based on good record. Please continue to improve in the future.

**Comment by spaceT9** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceap7dvpajm33cvbvyic7yoo26rpbxciu6fgofiswc33ix2q33gjds 
#### Address 
> f1o27reuxezrfhymyt2jbmuxabf3xupkrkzvhfu5i
#### Datacap Allocated
> 1.95PiB
#### Signer Address
> f1dktm3abgn7wkpepxab4q3eaw24qktizk4esfzyy
#### Id
> 520073e4-0058-415f-81f6-07781965f9ef
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceap7dvpajm33cvbvyic7yoo26rpbxciu6fgofiswc33ix2q33gjds

**Comment by Bitrise0111** [comment]
the check report shows healthy.

**Comment by Bitrise0111** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb4rgtkcaokkxumigsi5bfp7fzo7gvprlojiif5qi52mnuit72l66 
#### Address 
> f1o27reuxezrfhymyt2jbmuxabf3xupkrkzvhfu5i
#### Datacap Allocated
> 1.95PiB
#### Signer Address
> f1nknj7ayq4o43czrtdoauggtwl43fbqatmqis3yy
#### Id
> 520073e4-0058-415f-81f6-07781965f9ef
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb4rgtkcaokkxumigsi5bfp7fzo7gvprlojiif5qi52mnuit72l66

**Comment by cryptomandy** [comment]
checker:manualTrigger

**Comment by cryptomandy** [comment]
checker:manualTrigger

**Comment by cryptomandy** [comment]
checker:manualTrigger

**Comment by cryptowhizzard** [comment]
Hi,

It seems you are SP's are not proving readily retrieval ( Storing the unsealed sectors ).
This is against Fil+ rules and guidelines.

When is this going to be prepared and when can we download some of your data?

Recv 0 B, Paid 0 FIL, DealRejected (Rejecting), 868ms [1688983676511280994|0]
Recv 0 B, Paid 0 FIL, BlockstoreFinalized (Rejected), 871ms [1688983676511280994|0]
ERROR: Retrieval Proposal Rejected: deal rejected: there is no unsealed piece containing payload cid bafybeichrtnx4adpynbvrsiiqdntqkwedpdmix422nun7nnhdy2cmo4p7m

Recv 0 B, Paid 0 FIL, DealRejected (Rejecting), 872ms [1688983676511280995|0]
Recv 0 B, Paid 0 FIL, DealRejected (Rejecting), 871ms [1688983676511280996|0]
Recv 0 B, Paid 0 FIL, BlockstoreFinalized (Rejected), 874ms [1688983676511280996|0]
ERROR: Retrieval Proposal Rejected: deal rejected: there is no unsealed piece containing payload cid bafybeiag4l6rwqnt6etaometwb7llruhofegtjtip2jwp6lixhkfjnxp64

Recv 0 B, Paid 0 FIL, BlockstoreFinalized (Rejected), 881ms [1688983676511280995|0]
ERROR: Retrieval Proposal Rejected: deal rejected: there is no unsealed piece containing payload cid bafybeighjrrohtfrb2bean2c5zvbilr7n7lhpop5gwcxwhhhefvtuevdc4

Recv 0 B, Paid 0 FIL, DealRejected (Rejecting), 882ms [1688983676511280997|0]
Recv 0 B, Paid 0 FIL, DealRejected (Rejecting), 880ms [1688983676511280998|0]
Recv 0 B, Paid 0 FIL, BlockstoreFinalized (Rejected), 887ms [1688983676511280997|0]
ERROR: Retrieval Proposal Rejected: deal rejected: there is no unsealed piece containing payload cid bafybeighjrrohtfrb2bean2c5zvbilr7n7lhpop5gwcxwhhhefvtuevdc4

Recv 0 B, Paid 0 FIL, DealRejected (Rejecting), 883ms [1688983676511280999|0]
Recv 0 B, Paid 0 FIL, BlockstoreFinalized (Rejected), 888ms [1688983676511280998|0]
ERROR: Retrieval Proposal Rejected: deal rejected: there is no unsealed piece containing payload cid bafybeifiv5db3vqtfqq4mmi7z3ehv3yfwocebvjw6hcxeplg2scbtjqv7u

Recv 0 B, Paid 0 FIL, DealRejected (Rejecting), 885ms [1688983676511281000|0]
Recv 0 B, Paid 0 FIL, BlockstoreFinalized (Rejected), 891ms [1688983676511280999|0]
ERROR: Retrieval Proposal Rejected: deal rejected: there is no unsealed piece containing payload cid bafybeieogzruwkjflis2yjufqpjwopzgg35ghb2eqhjk7leci5cux5epim

Recv 0 B, Paid 0 FIL, DealRejected (Rejecting), 888ms [1688983676511281001|0]
Recv 0 B, Paid 0 FIL, BlockstoreFinalized (Rejected), 893ms [1688983676511281000|0]
ERROR: Retrieval Proposal Rejected: deal rejected: there is no unsealed piece containing payload cid bafybeighjrrohtfrb2bean2c5zvbilr7n7lhpop5gwcxwhhhefvtuevdc4

Recv 0 B, Paid 0 FIL, DealRejected (Rejecting), 892ms [1688983676511281002|0]
Recv 0 B, Paid 0 FIL, BlockstoreFinalized (Rejected), 896ms [1688983676511281001|0]
ERROR: Retrieval Proposal Rejected: deal rejected: there is no unsealed piece containing payload cid bafybeichrtnx4adpynbvrsiiqdntqkwedpdmix422nun7nnhdy2cmo4p7m

Recv 0 B, Paid 0 FIL, DealRejected (Rejecting), 894ms [1688983676511281003|0]
Recv 0 B, Paid 0 FIL, BlockstoreFinalized (Rejected), 899ms [1688983676511281002|0]
ERROR: Retrieval Proposal Rejected: deal rejected: there is no unsealed piece containing payload cid bafybeighjrrohtfrb2bean2c5zvbilr7n7lhpop5gwcxwhhhefvtuevdc4

Recv 0 B, Paid 0 FIL, DealRejected (Rejecting), 898ms [1688983676511281004|0]
Recv 0 B, Paid 0 FIL, BlockstoreFinalized (Rejected), 902ms [1688983676511281003|0]
ERROR: Retrieval Proposal Rejected: deal rejected: there is no unsealed piece containing payload cid bafybeie7ghkynzfkahk2y6a536u4cscbzatsg66z5amaimctiy3dvoxamm

Recv 0 B, Paid 0 FIL, DealRejected (Rejecting), 900ms [1688983676511281005|0]
Recv 0 B, Paid 0 FIL, BlockstoreFinalized (Rejected), 905ms [1688983676511281004|0]
ERROR: Retrieval Proposal Rejected: deal rejected: there is no unsealed piece containing payload cid bafybeifiv5db3vqtfqq4mmi7z3ehv3yfwocebvjw6hcxeplg2scbtjqv7u

Recv 0 B, Paid 0 FIL, DealRejected (Rejecting), 903ms [1688983676511281006|0]
Recv 0 B, Paid 0 FIL, BlockstoreFinalized (Rejected), 907ms [1688983676511281005|0]
ERROR: Retrieval Proposal Rejected: deal rejected: there is no unsealed piece containing payload cid bafybeifiv5db3vqtfqq4mmi7z3ehv3yfwocebvjw6hcxeplg2scbtjqv7u

Recv 0 B, Paid 0 FIL, DealRejected (Rejecting), 903ms [1688983676511281008|0]
Recv 0 B, Paid 0 FIL, BlockstoreFinalized (Rejected), 909ms [1688983676511281006|0]
ERROR: Retrieval Proposal Rejected: deal rejected: there is no unsealed piece containing payload cid bafybeichrtnx4adpynbvrsiiqdntqkwedpdmix422nun7nnhdy2cmo4p7m

Recv 0 B, Paid 0 FIL, DealRejected (Rejecting), 906ms [1688983676511281009|0]
Recv 0 B, Paid 0 FIL, BlockstoreFinalized (Rejected), 910ms [1688983676511281008|0]
ERROR: Retrieval Proposal Rejected: deal rejected: there is no unsealed piece containing payload cid bafybeiag4l6rwqnt6etaometwb7llruhofegtjtip2jwp6lixhkfjnxp64

Recv 0 B, Paid 0 FIL, DealRejected (Rejecting), 914ms [1688983676511281007|0]
Recv 0 B, Paid 0 FIL, BlockstoreFinalized (Rejected), 912ms [1688983676511281009|0]
ERROR: Retrieval Proposal Rejected: deal rejected: there is no unsealed piece containing payload cid bafybeie7ghkynzfkahk2y6a536u4cscbzatsg66z5amaimctiy3dvoxamm

Recv 0 B, Paid 0 FIL, BlockstoreFinalized (Rejected), 918ms [1688983676511281007|0]
ERROR: Retrieval Proposal Rejected: deal rejected: there is no unsealed piece containing payload cid bafybeichrtnx4adpynbvrsiiqdntqkwedpdmix422nun7nnhdy2cmo4p7m

**Comment by cryptomandy** [comment]
Hi, We also found this problem and have contacted our SP, they did not turn on the option to store unsealed when configuring miner, now it is turned on, and the retrieval will return to normal soon.

**Comment by cryptomandy** [comment]
checker:manualTrigger

**Comment by cryptomandy** [comment]
checker:manualTrigger

**Comment by cryptomandy** [comment]
checker:manualTrigger

**Comment by cryptomandy** [comment]
checker:manualTrigger

**Comment by cryptowhizzard** [comment]
@cryptomandy 

It seems that you are mostly working with SP's who have been flagged for CID sharing. Can you explain why?

![Scherm­afbeelding 2023-07-28 om 14 36 02](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/36404435/27e54e40-b348-42a4-bd2e-2096f4c177c3)

**Comment by cryptomandy** [comment]
@cryptowhizzard Hello, Sir

This is a lingering issue originating from the Notary V3.1. When SPs first engaged with Filecoin Plus, due to some client partnerships, it resulted in a CID sharing (about 11T). Since then, they have been diligently improving their data storage processes and enhancing their understanding of the FIL+ rules. Every subsequent action has adhered strictly to the official FIL+ guidelines.

Just as the FIL+ community governance continues to upgrade and improve, so do the clients and SPs. They are persistently refining their understanding of the FIL+ regulations and tirelessly optimizing their operations. 

Let's be clear, this process is akin to the relentless drive of progress itself. It is imperative to understand that as the FIL+ community governance rules continue to evolve, the commitment of both clients and SPs to learn, adapt, and improve never wavers. So, any suggestion of misconduct is baseless and should be confronted with this context. All participants and builders are working towards a common goal: to advance in compliance with the rules and enhance the ecosystem as a whole.

**Comment by cryptowhizzard** [comment]
Hi @cryptomandy 

Thanks for your answer. These “red” SP’s are from LDN’s in the 650 range. It is a while back indeed and things might have changed. Do these SP’s support proper retrieval now?

**Comment by cryptomandy** [comment]
checker:manualTrigger

**Comment by cryptomandy** [comment]
checker:manualTrigger

**Comment by cryptowhizzard** [comment]
Dear cryptomandy,

As notary I am doing due diligence on your LDN. I could not get retrieval to work. Can you please upload the car file of CID baga6ea4seaqliqbco6fukvma7geqemh3wtwmvfwhyio4mrluu5ctnwqvr3iqway ?

You can use our upload system at http://send.datasetcreators.com. Please select 7 days for the system to keep the file and post the link you received here so I (and other notaries) can download your content.

**Comment by cryptomandy** [comment]
checker:manualTrigger

**Comment by cryptowhizzard** [comment]
Retrieved some data from this LDN:

http://www.datasetcreators.com/downloadedcarfiles/1711-f02060396-f02093396-48104605-baga6ea4seaqksyh6pvqbfpoy32oqtgpsvge5nm7csspddjw37zxwpqblkazj2ay

To me this data looks ok.

**Comment by cryptomandy** [comment]
checker:manualTrigger

**Comment by cryptomandy** [comment]
checker:manualTrigger

**Comment by Sunnyiscoming** [comment]
Hello, @cryptomandy per the https://github.com/filecoin-project/notary-governance/issues/922 for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

This information will be reviewed by Fil+ Governance team to confirm validity and then the application will be allowed to move forward for additional notary review.
