### ISSUE TITLE
[DataCap Application] NOAA UFS Subseasonal to Seasonal Prototypes

### ISSUE THREAD

**Issue by RamonPedroo** [filecoin-project/filecoin-plus-large-datasets#1713]
### Data Owner Name

NOAA

### Data Owner Country/Region

United States

### Data Owner Industry

Environment

### Website

https://www.noaa.gov/

### Social Media

```text
https://twitter.com/NOAA
https://www.facebook.com/NOAA
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

400TiB

### On-chain address for first allocation

f1m6trho4k23hkaizdwthyy2rsvkbtwxemas7i6na

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
NOAA is an agency that enriches life through science. Their reach goes from the surface of the sun to the depths of the ocean floor as we work to keep the public informed of the changing environment around them.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
The Unified Forecast System Subseasonal to Seasonal prototypes consist of reforecast data from the UFS atmosphere-ocean coupled model experimental prototype version 5, 6, 7, and 8 produced by the Medium Range and Subseasonal to Seasonal Application team of the UFS-R2O project. The UFS prototypes are the first dataset released to the broader weather community for analysis and feedback as part of the development of the next generation operational numerical weather prediction system from NWS. The datasets includes all the major weather variables for atmosphere, land, ocean, sea ice, and ocean waves.
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### How do you plan to prepare the dataset

lotus

### Please share a sample of the data

```text
https://registry.opendata.aws/noaa-ufs-s2s/
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Sporadic

### For how long do you plan to keep this dataset stored on Filecoin

1.5 to 2 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, South America

### How will you be distributing your data to storage providers

HTTP or FTP server, IPFS, Shipping hard drives

### How do you plan to choose storage providers

Slack, I don't know yet

### How do you plan to make deals to your storage providers

Lotus client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Looking at your application i have some questions:
As you are brand new on Github and have no history of past applications it seems to me that applying for 5PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?

Can you show us visible proof of the size of your data and the storage systems you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230337462961356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 5PiB

**Expected weekly DataCap usage rate**
> 400TiB

**Client address**
>f1m6trho4k23hkaizdwthyy2rsvkbtwxemas7i6na

**Comment by BobbyChoii** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaopyuwsihe7owpp56bbfftwzj2qlnrwdswtev2byzre65xywadkc 
#### Address 
> f1m6trho4k23hkaizdwthyy2rsvkbtwxemas7i6na
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1irqs2gmctiv3jcdfwuch7oxvf4ixh3k4b2wc24i
#### Id
> d39c6d7b-c877-4d0f-9c2d-808c7bc97954
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaopyuwsihe7owpp56bbfftwzj2qlnrwdswtev2byzre65xywadkc

**Comment by Protocan** [comment]
checker:manualTrigger

**Comment by Protocan** [comment]
Looks normal and acceptable, willing to support.

**Comment by Protocan** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacea55kdvjakvms3rav5eioqlyhxjxxk2ohwsyirtd532vawpylhz7u 
#### Address 
> f1m6trho4k23hkaizdwthyy2rsvkbtwxemas7i6na
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1vxbqrf7rfum3n6m5u6eb4re6xj7amvsaqnzu64y
#### Id
> 96c90e5e-8bab-4558-a292-2e9353970711
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacea55kdvjakvms3rav5eioqlyhxjxxk2ohwsyirtd532vawpylhz7u

**Comment by TakiChain** [comment]
This score of Deal Data Replication can still be improved. Hope to see better results in the next round.

**Comment by TakiChain** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec6fb5lh5su6v3nnhwcdp2sk6ot7g3sihlsgfnsdtstmij7o5a4nc 
#### Address 
> f1m6trho4k23hkaizdwthyy2rsvkbtwxemas7i6na
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f15impf3j2zcaex4lhyxndxswuuhv24vzstuqtxsi
#### Id
> 96c90e5e-8bab-4558-a292-2e9353970711
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec6fb5lh5su6v3nnhwcdp2sk6ot7g3sihlsgfnsdtstmij7o5a4nc

**Comment by Aifabot-Cloud** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebjgxoxhj2q746igwwkglexunzadf5wpygcoq3mi5pbhcvnkhi3w4 
#### Address 
> f1m6trho4k23hkaizdwthyy2rsvkbtwxemas7i6na
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f174fg3bqbln3zjnkxtyf6s54txqkr7yqkj6cig7y
#### Id
> 4fea93fe-bea0-418d-a19c-3a909f1b0172
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebjgxoxhj2q746igwwkglexunzadf5wpygcoq3mi5pbhcvnkhi3w4

**Comment by Casey-PG** [comment]
Good summary report and ongoing communication from the applicant. willing to support!

**Comment by Casey-PG** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacea5jgjd55lnghmvyt43mcnnlojopth742w7crnfeyvmse52oebfyq 
#### Address 
> f1m6trho4k23hkaizdwthyy2rsvkbtwxemas7i6na
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1d4yb3wags3mtddzesxoo63jv7dmlec3bq4yteni
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacea5jgjd55lnghmvyt43mcnnlojopth742w7crnfeyvmse52oebfyq

**Comment by TakiChain** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceawzgebdoy6njj56afyz7orpd5x3t4p47voqacegtrblrec4hhl44 
#### Address 
> f1m6trho4k23hkaizdwthyy2rsvkbtwxemas7i6na
#### Datacap Allocated
> 1.56PiB
#### Signer Address
> f15impf3j2zcaex4lhyxndxswuuhv24vzstuqtxsi
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceawzgebdoy6njj56afyz7orpd5x3t4p47voqacegtrblrec4hhl44

**Comment by BobbyChoii** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebxuoseitlqz7fvdmhiok7dxhydxof4jtss7y4neb7u32zw5nzjr6 
#### Address 
> f1m6trho4k23hkaizdwthyy2rsvkbtwxemas7i6na
#### Datacap Allocated
> 1.56PiB
#### Signer Address
> f1irqs2gmctiv3jcdfwuch7oxvf4ixh3k4b2wc24i
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebxuoseitlqz7fvdmhiok7dxhydxof4jtss7y4neb7u32zw5nzjr6

**Comment by RamonPedroo** [comment]
Yes.

**Comment by cryptowhizzard** [comment]
checker:manualTrigger

**Comment by cryptowhizzard** [comment]
checker:manualTrigger

**Comment by cryptowhizzard** [comment]
Greetings @RamonPedroo 

It seems you are working with SP's who have retrieval disabled and/or are flagged for CID sharing.
Can you tell us why?

![Scherm­afbeelding 2023-08-01 om 09 27 39](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/36404435/1a04d119-a15b-44b2-8027-5a862d9504a6)

**Comment by Bennyyangpu** [comment]
checker:manualTrigger

**Comment by Bennyyangpu** [comment]
Tthe number of SPs and the retrieval rate are relatively good. willing to support.
![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/107031628/51542d79-14c8-4a2e-8bd4-26d949030529)

**Comment by Bennyyangpu** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceanaobbtntxspzhkzpy7qaimqn6qtwy574wcadmjhmucfslr7o254 
#### Address 
> f1m6trho4k23hkaizdwthyy2rsvkbtwxemas7i6na
#### Datacap Allocated
> 1.56PiB
#### Signer Address
> f174fg3bqbln3zjnkxtyf6s54txqkr7yqkj6cig7y
#### Id
> b7fac522-2098-4fe2-8e68-fcf0eaa8418c
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceanaobbtntxspzhkzpy7qaimqn6qtwy574wcadmjhmucfslr7o254

**Comment by Suyanj** [comment]
Judging from previous communication and the updated report, I am willing to support.

**Comment by Suyanj** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacectg5l4l7opqd3e3uipb4ucbye3q63woaw7xu44bkyt3rohkcl64g 
#### Address 
> f1m6trho4k23hkaizdwthyy2rsvkbtwxemas7i6na
#### Datacap Allocated
> 1.56PiB
#### Signer Address
> f1ihv7gz3vn3xqvikpt4rwryecgisl7745lodx3yi
#### Id
> b7fac522-2098-4fe2-8e68-fcf0eaa8418c
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacectg5l4l7opqd3e3uipb4ucbye3q63woaw7xu44bkyt3rohkcl64g

**Comment by RamonPedroo** [comment]
Thanks for notaries‘ support. We support retrieval and we will work under rules.

**Comment by RamonPedroo** [comment]
> Greetings @RamonPedroo
> 
> It seems you are working with SP's who have retrieval disabled and/or are flagged for CID sharing. Can you tell us why?
> 
> ![Scherm­afbeelding 2023-08-01 om 09 27 39](https://user-images.githubusercontent.com/36404435/257437969-1a04d119-a15b-44b2-8027-5a862d9504a6.png)

It's not related to my application. My application doesn't have the problem. You can check the report from my application.

**Comment by clriesco** [comment]
Removed stale label and reopened issue :)

**Comment by cryptowhizzard** [comment]
![Scherm­afbeelding 2023-08-31 om 15 47 48](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/36404435/f50e58d2-0d30-434a-9a44-1ddc33bb32fb)

Cheers,

I took the liberty to download some of your data.

This is : http://www.datasetcreators.com/downloadedcarfiles/httpretrievals/1713-f02035501-f02245898-48711885-baga6ea4seaqht3ek6y6inwpqiihxkpefe5ex55bn46ackfdlhcwofpsyi3ttimy

Deal ID 48711885

This garbage is not the data you promised us to store. 

![Scherm­afbeelding 2023-08-31 om 15 48 54](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/36404435/7478690f-bf66-4c71-893e-f064b48e4fcd)

**Comment by raghavrmadya** [comment]
Following up regarding the dispute here - https://www.notion.so/filecoin/Applicant-storing-garbage-data-aaac422a11f649168a576f4c9d3d8979?pvs=4

Does the client have anything to add?

**Comment by RamonPedroo** [comment]
@raghavrmadya 
There's been lots of reaction on slack that this guy's attacking many normal applicants with perjury, haven't you heard it?  Once we've exposed his poor lies, he'll use new tactics to continue gaslighting you.

I've blacklisted them. That's what i want to add.

**Comment by RamonPedroo** [comment]
Please open it.
