### ISSUE TITLE
[DataCap Application] FileGuard - Open Satellite Datasets for Machine Learning

### ISSUE THREAD

**Issue by cryptomandy** [filecoin-project/filecoin-plus-large-datasets#1714]
### Data Owner Name

FileGuard

### Data Owner Country/Region

China

### Data Owner Industry

Web3 / Crypto

### Website

https://fileguard.io

### Social Media

```text
N/A
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

500TiB

### On-chain address for first allocation

f1mmkk7e65572oobb35v2afhbbsntd5n6thexiwwy

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
As a machine learning & deep learning training data provider, FileGuard provide a complete data solution of "software + hardware", Help algorithm companies collect and check data. A complete set of solutions for cleaning, desensitization, labeling, storing, transfer, etc. FileGuard have served more than 30 artificial intelligence enterprise customers since 2018, suce as Face++, SenseTime, JD finance and so on, providing customers with more than 20 million image annotation data, and about 200,000 crowdsourcers working on the FileGuard platform.

As a platform all in Web3, We have been engaged with storing real and valuable machine learning & deep learning datasets on the Filecoin network. We focus on the three areas of artificial intelligence: computer vision(CV), natural language processing(NLP) and speech processing. We believe that the Web3 way of storing these valuable data, such as autonomous driving, cancer, disease, geographic, agriculture, speech, and NLP data, will bring huge changes.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
This application including 4 AWS open satellite dataset for Machine learning:

1. RarePlanes
https://registry.opendata.aws/rareplanes/
RarePlanes is a unique open-source machine learning dataset from CosmiQ Works and AI.Reverie that incorporates both real and synthetically generated satellite imagery.

2. NASA Prediction of Worldwide Energy Resources (POWER)
https://registry.opendata.aws/nasa-power/
NASA's goal in Earth science is to observe, understand, and model the Earth system to discover how it is changing, to better predict change, and to understand the consequences for life on Earth. The Applied Sciences Program serves NASA and Society by expanding and accelerating the realization of societal and economic benefits from Earth science, information, and technology research and development.

3. Mars Spectrometry 2: Gas Chromatography for the Sample Analysis at Mars Data (SAM) Instrument
https://registry.opendata.aws/nasa-gcms/
NASA missions like the Curiosity and Perseverance rovers carry a rich array of instruments suited to collect data and build evidence towards answering if Mars ever had livable environmental conditions. These rovers can collect rock and soil samples and can take measurements that can be used to determine their chemical makeup.

4. Mars Spectrometry: Detect Evidence for Past Habitability
https://registry.opendata.aws/nasa-ega/
This project aimed at building a model to automatically analyze evolved gas analysis mass spectrometry (EGA-MS) data collected for Mars exploration in order to help the scientists in their analysis of understanding the past habitability of Mars.
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### How do you plan to prepare the dataset

lotus, singularity

### Please share a sample of the data

```text
s3://rareplanes-public/
s3://power-analysis-ready-datastore/
s3://gcms-samdata-mlchallenge/
s3://egams-samdata-mlchallenge/
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

1 to 1.5 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, Europe

### How will you be distributing your data to storage providers

Cloud storage (i.e. S3), HTTP or FTP server, Shipping hard drives

### How do you plan to choose storage providers

Slack, Partners

### If you already have a list of storage providers to work with, fill out their names and provider IDs below

```text
| MinerID   | City       | Continent | Business/Entity |
| --------- | ---------- | --------- | -------- |
| f01824405 | ChengDu    | CN        | RY       |
| f01991416 | HongKong   | CN        | RIKIMARU |
| f02012032 | HongKong   | CN        | RIKIMARU |
| f02006691 | HongKong   | CN        | NIHICHE  |
| f02027952 | London     | UK        | Mochi    |
| f02014107 | Seoul      | KR        | HMT      |
| f02028326 | California | USA       | Fyii     |
```

### How do you plan to make deals to your storage providers

Boost client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.


Can you fill out [this form](https://form.jotform.com/230337462961356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!

**Comment by cryptomandy** [comment]
@cryptowhizzard Hello, the KYC form has submitted.

Thanks!

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 5PiB

**Expected weekly DataCap usage rate**
> 500TiB

**Client address**
>f1mmkk7e65572oobb35v2afhbbsntd5n6thexiwwy

**Comment by cryptowhizzard** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebho4nmotqp3zmgq456vme6fgoz6ge74s462ypymtqxqwlgqzyuue 
#### Address 
> f1mmkk7e65572oobb35v2afhbbsntd5n6thexiwwy
#### Datacap Allocated
> 250.00TiB
#### Signer Address
> f1krmypm4uoxxf3g7okrwtrahlmpcph3y7rbqqgfa
#### Id
> 3e640deb-f2c4-40fa-a9e5-6de1b2fab771
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebho4nmotqp3zmgq456vme6fgoz6ge74s462ypymtqxqwlgqzyuue

**Comment by jomozz** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceamvhfi3csi22y6aunqlox3gg6lt6xnjq2moxx3mkwgmjebp65g5s 
#### Address 
> f1mmkk7e65572oobb35v2afhbbsntd5n6thexiwwy
#### Datacap Allocated
> 250.00TiB
#### Signer Address
> f1qpdwt2f2fse74nl5wi27uk5jcyqqqyil47yqt7i
#### Id
> 3e640deb-f2c4-40fa-a9e5-6de1b2fab771
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceamvhfi3csi22y6aunqlox3gg6lt6xnjq2moxx3mkwgmjebp65g5s

**Comment by jomozz** [comment]
check and happy to support

**Comment by cryptomandy** [comment]
checker:manualTrigger

**Comment by cryptomandy** [comment]
checker:manualTrigger

**Comment by cryptomandy** [comment]
checker:manualTrigger

**Comment by cryptomandy** [comment]
checker:manualTrigger

**Comment by Bitrise0111** [comment]
the report show healthy

**Comment by Bitrise0111** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecja2bwz7y7w6r4rtjjo3pjurbs5ne7svynd4jdiwln2vjshsc2ua 
#### Address 
> f1mmkk7e65572oobb35v2afhbbsntd5n6thexiwwy
#### Datacap Allocated
> 500.00TiB
#### Signer Address
> f1nknj7ayq4o43czrtdoauggtwl43fbqatmqis3yy
#### Id
> 1fa628a5-f6e0-453e-808a-a05e4810fca1
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecja2bwz7y7w6r4rtjjo3pjurbs5ne7svynd4jdiwln2vjshsc2ua

**Comment by Bitengine-reeta** [comment]
checker:manualTrigger

**Comment by Bitengine-reeta** [comment]
Both CID Checker report and Retrieval report show a good result, I will support

**Comment by cryptomandy** [comment]
checker:manualTrigger

**Comment by cryptomandy** [comment]
checker:manualTrigger

**Comment by cryptomandy** [comment]
checker:manualTrigger

**Comment by cryptomandy** [comment]
checker:manualTrigger

**Comment by cryptomandy** [comment]
checker:manualTrigger

**Comment by cryptowhizzard** [comment]
Dear cryptomandy,

As notary I am doing due diligence on your LDN. I could not get retrieval to work. Can you please upload the car file of CID baga6ea4seaqcosxcjnfknypqk52g5jd3j22tepo7bps7xkhz7y2xjv646rn6ieq ?

You can use our upload system at http://send.datasetcreators.com. Please select 7 days for the system to keep the file and post the link you received here so I (and other notaries) can download your content.

**Comment by cryptomandy** [comment]
checker:manualTrigger

**Comment by cryptomandy** [comment]
Sure, uploading...

**Comment by cryptomandy** [comment]
checker:manualTrigger

**Comment by cryptomandy** [comment]
checker:manualTrigger

**Comment by cryptomandy** [comment]
checker:manualTrigger

**Comment by cryptomandy** [comment]
checker:manualTrigger

**Comment by Sunnyiscoming** [comment]
Hello, per the https://github.com/filecoin-project/notary-governance/issues/922 for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

This information will be reviewed by Fil+ Governance team to confirm validity and then the application will be allowed to move forward for additional notary review.

**Comment by cryptomandy** [comment]
> Hello, per the [filecoin-project/notary-governance#922](https://github.com/filecoin-project/notary-governance/issues/922) for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.
> 
> This information will be reviewed by Fil+ Governance team to confirm validity and then the application will be allowed to move forward for additional notary review.

Okey, sorry for late reply.
