### ISSUE TITLE
[DataCap Application] FileGuard - Allen Institute for Artificial Intelligence

### ISSUE THREAD

**Issue by cryptomandy** [filecoin-project/filecoin-plus-large-datasets#1715]
### Data Owner Name

FileGuard

### Data Owner Country/Region

China

### Data Owner Industry

Web3 / Crypto

### Website

https://fileguard.io

### Social Media

```text
N/A
```

### Total amount of DataCap being requested

3PiB

### Weekly allocation of DataCap requested

600TiB

### On-chain address for first allocation

f1hvne4mfs2fzvltranvdw6nfddvmtiofhw37bxsi

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
As a machine learning & deep learning training data provider, FileGuard provide a complete data solution of "software + hardware", Help algorithm companies collect and check data. A complete set of solutions for cleaning, desensitization, labeling, storing, transfer, etc. FileGuard have served more than 30 artificial intelligence enterprise customers since 2018, suce as Face++, SenseTime, JD finance and so on, providing customers with more than 20 million image annotation data, and about 200,000 crowdsourcers working on the FileGuard platform.

As a platform all in Web3, We have been engaged with storing real and valuable machine learning & deep learning datasets on the Filecoin network. We focus on the three areas of artificial intelligence: computer vision(CV), natural language processing(NLP) and speech processing. We believe that the Web3 way of storing these valuable data, such as autonomous driving, cancer, disease, geographic, agriculture, speech, and NLP data, will bring huge changes.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
The data being stored onto Filecoin including 12 AWS open dataset by Allen Institute:

1. AI2 Diagram Dataset (AI2D)
LINK: https://registry.opendata.aws/allenai-diagrams/
4,817 illustrative diagrams for research on diagram understanding and associated question answering.

2. Discrete Reasoning Over the content of Paragraphs (DROP)
LINK: https://registry.opendata.aws/allenai-drop/
The DROP dataset contains 96k Question and Answer pairs (QAs) over 6.7K paragraphs, split between train (77k QAs), development (9.5k QAs) and a hidden test partition (9.5k QAs).

3. Quoref
LINK: https://registry.opendata.aws/allenai-quoref/
24K Question/Answer (QA) pairs over 4.7K paragraphs, split between train (19K QAs), development (2.4K QAs) and a hidden test partition (2.5K QAs).

4. Reasoning Over Paragraph Effects in Situations (ROPES)
LINK: https://registry.opendata.aws/allenai-ropes/
14k QA pairs over 1.7K paragraphs, split between train (10k QAs), development (1.6k QAs) and a hidden test partition (1.7k QAs).

5. AI2 Meaningful Citations Data Set
LINK: https://registry.opendata.aws/allenai-meaningful-citations/
630 paper annotations

6. AI2 Reasoning Challenge (ARC) 2018
LINK: https://registry.opendata.aws/allenai-arc/
7,787 multiple choice science questions and associated corpora

7. Aristo Mini Corpus
LINK: https://registry.opendata.aws/allenai-aristo-mini/
1,197,377 science-relevant sentences

8. AI2 TabMCQ: Multiple Choice Questions aligned with the Aristo Tablestore
LINK: https://registry.opendata.aws/allenai-tablestore-questions/
9092 crowd-sourced science questions and 68 tables of curated facts

9. AI2 Tablestore (November 2015 Snapshot)
LINK: https://registry.opendata.aws/allenai-tablestore/
68 tables of curated facts

10. Aristo Tuple KB
LINK: https://registry.opendata.aws/allenai-tuple-kb/
294,000 science-relevant tuples

11. Textbook Question Answering (TQA)
LINK: https://registry.opendata.aws/allenai-tqa/
1,076 textbook lessons, 26,260 questions, 6229 images

12. ZEST: ZEroShot learning from Task descriptions
LINK: https://registry.opendata.aws/allenai-zest/
ZEST is a benchmark for zero-shot generalization to unseen NLP tasks, with 25K labeled instances across 1,251 different tasks.
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### How do you plan to prepare the dataset

lotus, singularity

### Please share a sample of the data

```text
s3://ai2-public-datasets/
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

1.5 to 2 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, Europe

### How will you be distributing your data to storage providers

Cloud storage (i.e. S3), HTTP or FTP server, Shipping hard drives

### How do you plan to choose storage providers

Slack, Partners

### If you already have a list of storage providers to work with, fill out their names and provider IDs below

```text
| MinerID   | City       | Continent | Business/Entity |
| --------- | ---------- | --------- | -------- |
| f01824405 | ChengDu    | CN        | RY       |
| f01991416 | HongKong   | CN        | RIKIMARU |
| f02012032 | HongKong   | CN        | RIKIMARU |
| f02006691 | HongKong   | CN        | NIHICHE  |
| f02027952 | London     | UK        | Mochi    |
| f02014107 | Seoul      | KR        | HMT      |
| f02028326 | California | USA       | Fyii     |
```

### How do you plan to make deals to your storage providers

Boost client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by cryptomandy** [comment]
@cryptowhizzard Hello, the KYC form has submitted.

Thanks!

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 3PiB

**Expected weekly DataCap usage rate**
> 600TiB

**Client address**
>f1hvne4mfs2fzvltranvdw6nfddvmtiofhw37bxsi

**Comment by cryptowhizzard** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecg6kmriu7z2a3thipwipmua6vctiz3oe3qor7uhqayijuxh65cvw 
#### Address 
> f1hvne4mfs2fzvltranvdw6nfddvmtiofhw37bxsi
#### Datacap Allocated
> 153.59TiB
#### Signer Address
> f1krmypm4uoxxf3g7okrwtrahlmpcph3y7rbqqgfa
#### Id
> 03d8f759-3553-4103-a4af-d516b144c8cb
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecg6kmriu7z2a3thipwipmua6vctiz3oe3qor7uhqayijuxh65cvw

**Comment by cryptomandy** [comment]
checker:manualTrigger

**Comment by ipollo00** [comment]
checker:manualTrigger

**Comment by ipollo00** [comment]
Do you still wanna keep this application since this was opened three months ago?

**Comment by cryptomandy** [comment]
checker:manualTrigger

**Comment by cryptomandy** [comment]
checker:manualTrigger

**Comment by cryptomandy** [comment]
checker:manualTrigger

**Comment by cryptomandy** [comment]
checker:manualTrigger

**Comment by zcfil** [comment]
checker:manualTrigger

**Comment by cryptomandy** [comment]
checker:manualTrigger

**Comment by cryptomandy** [comment]
checker:manualTrigger

**Comment by cryptomandy** [comment]
checker:manualTrigger

**Comment by cryptomandy** [comment]
checker:manualTrigger
