### ISSUE TITLE
[DataCap Application] FileDrive Labs - REMA

### ISSUE THREAD

**Issue by laurarenpanda** [filecoin-project/filecoin-plus-large-datasets#1716]
### Data Owner Name

FileDrive Labs

### Data Owner Country/Region

China

### Data Owner Industry

Life Science / Healthcare

### Website

https://filedrive.io/

### Social Media

```text
Twitter: https://twitter.com/FileDrive1
Medium: https://medium.com/@FileDrive1
WeChat Offical Account: FileDrive
```

### Total amount of DataCap being requested

3PiB

### Weekly allocation of DataCap requested

500TiB

### On-chain address for first allocation

f1azwcm4mf3auvdu2gzromb2utb5hmqqift3wguei

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
FileDrive Datasets Landing Plan is a project for onboarding more valuable public datasets onto the Filecoin network. Through several phases, we plan to bring 10 PiB data and promote 100 PiB storage power growth to Filecoin. 


About FileDrive Datasets

FileDrive Datasets is a platform to effectively connect the huge storage market that Filecoin has built with publishers of public datasets.
The Filecoin network provides reliable, secure, and affordable decentralized storage services, and FileDrive Labs wants to deliver these benefits to end-users by building a public dataset platform.
It is challenging to attract traditional Cloud Storage and Object-base Storage users to the Filecoin network and benefit from it. Developers in the Felicoin ecosystem, such as FileDrive Labs, need to face this challenge together.
As a member of the Filecoin ecosystem, FileDrive Labs has been insisting on developing useful tools to make it easier for users to store their data onto the Filecoin network. 

FileDrive Datasets has integrated a group of tools to provide storage service with the compatibility of both Cloud Storage and Object-base Storage and better user experience to attract more users.
Projects(ongoing) behind:
- Go-Graphsplit: https://github.com/filedrive-team/go-graphsplit
- DS-Cluster: https://github.com/filedrive-team/go-ds-cluster
- Filejoy: https://github.com/filedrive-team/filejoy

Article about FileDrive Datasets on Filecoin Blog:
- Large Datasets: FileDrive: https://filecoin.io/blog/posts/large-datasets-filedrive/



About FileDrive Labs

FileDrive Labs has always defined ourselves as tool developers and infrastructure builders in the Filecoin ecosystem. From 2019, we continuously focus on technical solutions and development based on IPFS protocol and the Filecoin network and do our best to contribute to the community.
Over 80% of our team are qualified engineers, and half of them have more than 10-year development experience in multiple industries, including Communication, the Internet, and blockchain.
Since 2020, we have participated in Slingshot Competition, become one of the top teams, and stored over 5 PiB useful data from public datasets to the Filecoin network.
To contribute to the Filecoin Community, we developed an open-source data prep tool Graphsplit, FIL+ project dashboard filplus.info and storage provider discovery platform filfind,info.
Besides, we have also hold weekly online virtual events named FileDrive Meetup from March 2022, which aims to provide a platform for community members to grasp the latest trends of the Filecoin network and our work and research.

Please check the following links for more details.
- GitHub: https://github.com/filedrive-team
- Twitter: https://twitter.com/FileDrive1
- Eventbrite: https://www.eventbrite.hk/o/filedrive-labs-42456337463
- YouTube Channel: https://www.youtube.com/channel/UCxcZC1dtBUlQvZY7DX13W1w
- Medium: https://medium.com/@FileDrive1
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
Reference Elevation Model of Antarctica (REMA)
- The Reference Elevation Model of Antarctica - 2m GSD Digital Elevation Models (DEMs) and mosaics from 2009 to the present. The REMA project seeks to fill the need for high-resolution time-series elevation data in the Antarctic. The time-dependent nature of the strip DEM files allows users to perform change detection analysis and to compare observations of topography data acquired in different seasons or years. The mosaic DEM tiles are assembled from multiple strip DEMs with the intention of providing a more consistent and comprehensive product over large areas. REMA data is constructed from in-track and cross-track high-resolution (~0.5 meter) imagery acquired by the Maxar constellation of optical imaging satellites.
- https://registry.opendata.aws/pgc-rema/
- License: Creative Commons Attribution 4.0 International (CC BY 4.0)
- Size: 313.5 TiB
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### How do you plan to prepare the dataset

IPFS, lotus, graphsplit

### Please share a sample of the data

```text
Original Source:
https://registry.opendata.aws/pgc-rema/
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Weekly

### For how long do you plan to keep this dataset stored on Filecoin

2 to 3 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, Europe, Australia (continent)

### How will you be distributing your data to storage providers

HTTP or FTP server, IPFS, Shipping hard drives

### How do you plan to choose storage providers

Slack, Filmine

### If you already have a list of storage providers to work with, fill out their names and provider IDs below

```text
Please check the Checker Reports of our previous LDN applications:
- https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1266
```

### How do you plan to make deals to your storage providers

Lotus client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 3PiB

**Expected weekly DataCap usage rate**
> 500TiB

**Client address**
>f1azwcm4mf3auvdu2gzromb2utb5hmqqift3wguei

**Comment by s0nik42** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb26itecd5lgm2svsskyun6qsvrtx6eojfw2bhenczuiqzzdocrwa 
#### Address 
> f1azwcm4mf3auvdu2gzromb2utb5hmqqift3wguei
#### Datacap Allocated
> 153.59TiB
#### Signer Address
> f1wxhnytjmklj2czezaqcfl7eb4nkgmaxysnegwii
#### Id
> 87af38bc-bd9f-4a38-9e68-7543295ecedc
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb26itecd5lgm2svsskyun6qsvrtx6eojfw2bhenczuiqzzdocrwa

**Comment by laurarenpanda** [comment]
We are working on this application with our new piece-store solution, so it's slightly slower than our previous plan.
Its estimated start time will be June.

**Comment by laurarenpanda** [comment]
Still in preparation.

**Comment by laurarenpanda** [comment]
This project will start within the next week.

**Comment by ipollo00** [comment]
Are you ready to start over?

**Comment by cryptowhizzard** [comment]
@laurarenpanda 

why can’t we retrieve this data?

**Comment by laurarenpanda** [comment]
> @laurarenpanda
> 
> why can’t we retrieve this data?

Hi, @cryptowhizzard.
I have individually reached out to the storage providers involved in this project, discussing the retrieval rate and recommending that they prioritize support for HTTP.
In addition, we tested the retrieval of data from them using our bot stationed in Japan. I believe the Retrieval report will be improved with time flows.


provider_id | date | client | http_retrievals | http_retrieval_success | avg_ttfb_ms | avg_speed_bps
-- | -- | -- | -- | -- | -- | --
f01984576 | 2023/7/13 | f02061508 | 10 | 10 | 690.8087012 | 1150456.304
f01984586 | 2023/7/13 | f02061508 | 3 | 3 | 705.6112527 | 978482.0394
f01984593 | 2023/7/13 | f02061508 | 6 | 6 | 1274.067929 | 406185.4607

In order to adhere more closely to FIL+ regulations, my team is currently developing a monitoring system to track the retrieval rate of all LDNs.

**Comment by laurarenpanda** [comment]
checker:manualTrigger

**Comment by nj-steve** [comment]
checker:manualTrigger

**Comment by nj-steve** [comment]
The client contacted me in the community and I communicated with her that they will send to more SPs in the next round.

**Comment by nj-steve** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedu4a5htzhilwvjn4amwxj3wbity7m4zvpuclfo4g37o76srwewq4 
#### Address 
> f1azwcm4mf3auvdu2gzromb2utb5hmqqift3wguei
#### Datacap Allocated
> 500.00TiB
#### Signer Address
> f1xx6555qijma7igpnjspyvdunc4vfxkawnpqy5ii
#### Id
> 3488788e-bd18-4a9f-97e0-67e03b982967
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedu4a5htzhilwvjn4amwxj3wbity7m4zvpuclfo4g37o76srwewq4

**Comment by a1991car** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedzpyjtdrnfib62xdqmandpniyhfimwv573kry7zj4ajkatal54pc 
#### Address 
> f1azwcm4mf3auvdu2gzromb2utb5hmqqift3wguei
#### Datacap Allocated
> 500.00TiB
#### Signer Address
> f1qnumecdypgrbaebtkdfjnwt5ndacadcuas3deiq
#### Id
> 3488788e-bd18-4a9f-97e0-67e03b982967
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedzpyjtdrnfib62xdqmandpniyhfimwv573kry7zj4ajkatal54pc

**Comment by herrehesse** [comment]
checker:manualTrigger

**Comment by laurarenpanda** [comment]
Please keep this application open.

**Comment by PluskitOfficial** [comment]
checker:manualTrigger

**Comment by PluskitOfficial** [comment]
@laurarenpanda Could you please specify the location of relevant SPs?  Besides, do your data support retrieval? Please provide evidence.

**Comment by laurarenpanda** [comment]
> @laurarenpanda Could you please specify the location of relevant SPs? Besides, do your data support retrieval? Please provide evidence.

Hi, @PluskitOfficial.
Thanks so much for asking!
We're working on an update of our auto-deal system with the assistance of SPs of this LDN.
Once it is complete, the retrieval function will go back to work.

**Comment by PluskitOfficial** [comment]
@laurarenpandaOK, Please let me know if there's any progress.

**Comment by laurarenpanda** [comment]
checker:manualTrigger

**Comment by zcfil** [comment]
checker:manualTrigger

**Comment by data-programs** [comment]
<img width="32" alt="KYC" Verified src="https://stable.filplus.storage/images/filplus-kyc-verified-badge.png"/>

This user’s identity has been verified through [filplus.storage](https://filplus.storage)

**Comment by woshidama323** [comment]
checker:manualTrigger

**Comment by woshidama323** [comment]
The result of the report looks healthy and the retrieval success rate also looks good
Will support this application

**Comment by woshidama323** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacea2iit4snvinmybsuilkjpi7hxosfznyuljc5v2fco5x7vwbe4rdo 
#### Address 
> f1azwcm4mf3auvdu2gzromb2utb5hmqqift3wguei
#### Datacap Allocated
> 1000.00TiB
#### Signer Address
> f12tk3adljauwnd3hjbigpfxb7b7gdlj63p6afwtq
#### Id
> c2f1e92d-5cf4-4c30-ab49-4f87e1a7a212
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacea2iit4snvinmybsuilkjpi7hxosfznyuljc5v2fco5x7vwbe4rdo

**Comment by Joss-Hua** [comment]
checker:manualTrigger

**Comment by Joss-Hua** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecamrtsduxp2kjkphxr3xlsjd23annidza7ex3iukttch5557vnbk 
#### Address 
> f1azwcm4mf3auvdu2gzromb2utb5hmqqift3wguei
#### Datacap Allocated
> 1000.00TiB
#### Signer Address
> f1tfg54zzscugttejv336vivknmsnzzmyudp3t7wi
#### Id
> c2f1e92d-5cf4-4c30-ab49-4f87e1a7a212
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecamrtsduxp2kjkphxr3xlsjd23annidza7ex3iukttch5557vnbk

**Comment by laurarenpanda** [comment]
Please keep this application open.

**Comment by laurarenpanda** [comment]
Please keep this application open.

**Comment by laurarenpanda** [comment]
Please keep this application open.

**Comment by laurarenpanda** [comment]
Please keep this application open.

**Comment by laurarenpanda** [comment]
Please keep this application open.

**Comment by laurarenpanda** [comment]
checker:manualTrigger

**Comment by laurarenpanda** [comment]
checker:manualTrigger

**Comment by sxxfuture-official** [comment]
Reports looks good !

**Comment by sxxfuture-official** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecgvlygix6ekegsf65hbosxznknl454vkdd5rjidy6d3iv63yzxuc 
#### Address 
> f1azwcm4mf3auvdu2gzromb2utb5hmqqift3wguei
#### Datacap Allocated
> 1.38PiB
#### Signer Address
> f1foiomqlmoshpuxm6aie4xysffqezkjnokgwcecq
#### Id
> 97c71e98-c822-4667-b6cb-21449a15eb43
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecgvlygix6ekegsf65hbosxznknl454vkdd5rjidy6d3iv63yzxuc

**Comment by ipollo00** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceau4sjlb5dulspsf3janh2dpf43dkhabbqql7rclff5s6z4vz77ze 
#### Address 
> f1azwcm4mf3auvdu2gzromb2utb5hmqqift3wguei
#### Datacap Allocated
> 1.38PiB
#### Signer Address
> f1n5wlrrhoxpkgwij25xrtt7w7g2k3fhbthmdn6ri
#### Id
> 97c71e98-c822-4667-b6cb-21449a15eb43
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceau4sjlb5dulspsf3janh2dpf43dkhabbqql7rclff5s6z4vz77ze

**Comment by PluskitOfficial** [comment]
checker:manualTrigger

**Comment by PluskitOfficial** [comment]
Looks  good. Willing to sign this round.

**Comment by PluskitOfficial** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedkghart7kankmyblivy6mnohbsve3qzehlxabtys3vyir6gqkcm6 
#### Address 
> f1azwcm4mf3auvdu2gzromb2utb5hmqqift3wguei
#### Datacap Allocated
> 1.38PiB
#### Signer Address
> f1tgnlhtcmhwipfm7thsftxhn5k52velyjlazpvka
#### Id
> 347df491-390b-4b14-8032-ed180c85b953
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedkghart7kankmyblivy6mnohbsve3qzehlxabtys3vyir6gqkcm6

**Comment by herrehesse** [comment]
checker:manualTrigger

**Comment by herrehesse** [comment]
![Screenshot 2023-11-14 at 11 18 40](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/70132857/e33c4f8c-08ec-4e78-96b4-f18f791313dd)

Again @laurarenpanda - 50% of deals go to the same entity - selfdealing. Explain?

**Comment by sxxfuture-official** [comment]
checker:manualTrigger

**Comment by laurarenpanda** [comment]
> ![Screenshot 2023-11-14 at 11 18 40](https://user-images.githubusercontent.com/70132857/282742091-e33c4f8c-08ec-4e78-96b4-f18f791313dd.png)
> 
> Again @laurarenpanda - 50% of deals go to the same entity - selfdealing. Explain?

Not the same entity. Alibaba is one of the top IDC and network Operator.

**Comment by sxxfuture-official** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedxsvhwf2iikjefft7p7tetfb2pncbvtfaxoszs3h6nau6ptqbsik 
#### Address 
> f1azwcm4mf3auvdu2gzromb2utb5hmqqift3wguei
#### Datacap Allocated
> 1.38PiB
#### Signer Address
> f1foiomqlmoshpuxm6aie4xysffqezkjnokgwcecq
#### Id
> 347df491-390b-4b14-8032-ed180c85b953
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedxsvhwf2iikjefft7p7tetfb2pncbvtfaxoszs3h6nau6ptqbsik

**Comment by Sunnyiscoming** [comment]
Hello, per the https://github.com/filecoin-project/notary-governance/issues/922 for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

This information will be reviewed by Fil+ Governance team to confirm validity and then the application will be allowed to move forward for additional notary review.
Please provide ID, City, Country, Organization of each SP here.

**Comment by laurarenpanda** [comment]
Please keep this application open.

**Comment by Joss-Hua** [comment]
checker:manualTrigger

**Comment by Joss-Hua** [comment]
LGTM

**Comment by Joss-Hua** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebncyghcc6chukzyqmblx7tvstqgwlsj4z4z66t4cq5fpvlixntui 
#### Address 
> f1azwcm4mf3auvdu2gzromb2utb5hmqqift3wguei
#### Datacap Allocated
> 1.38PiB
#### Signer Address
> f1tfg54zzscugttejv336vivknmsnzzmyudp3t7wi
#### Id
> 347df491-390b-4b14-8032-ed180c85b953
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebncyghcc6chukzyqmblx7tvstqgwlsj4z4z66t4cq5fpvlixntui

**Comment by psh0691** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceckv35gfkearpsjzausf2uzydei3e2sjagoqms5pyyji75tfr5d7o 
#### Address 
> f1azwcm4mf3auvdu2gzromb2utb5hmqqift3wguei
#### Datacap Allocated
> 1.38PiB
#### Signer Address
> f1qdko4jg25vo35qmyvcrw4ak4fmuu3f5rif2kc7i
#### Id
> 347df491-390b-4b14-8032-ed180c85b953
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceckv35gfkearpsjzausf2uzydei3e2sjagoqms5pyyji75tfr5d7o

**Comment by laurarenpanda** [comment]
Keep open.

**Comment by laurarenpanda** [comment]
Please keep this application open.

**Comment by laurarenpanda** [comment]
Please keep this application open.

**Comment by laurarenpanda** [comment]
Please keep this application open.
