### ISSUE TITLE
[DataCap Application]  Guangzhou All Architectural Design Co., Ltd.

### ISSUE THREAD

**Issue by allgood6** [filecoin-project/filecoin-plus-large-datasets#1717]
### Data Owner Name

Guangzhou All Architectural Design Co., Ltd.

### Data Owner Country/Region

China

### Data Owner Industry

Resources, Agriculture & Fisheries

### Website

http://www.a-ll.cn/

### Social Media

```text
http://www.a-ll.cn/
```

### Total amount of DataCap being requested

3PiB

### Weekly allocation of DataCap requested

300TiB

### On-chain address for first allocation

f1h7fzawspx7pdxasqim4okbb67lmjg7jmoor67ma

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
All Architecture is an open experimenter of space.

We are an independent design team established in Guangzhou, China. The three partners graduated from Berlage College in the Netherlands. We were officially established in 2015, but since 2012, we have been in the field of design and research of architecture and cities.

We currently have 36 employees in the company, 17 of whom are designers, and we have undertaken many designs from all over the world, such as a hotel with an area of ​​three kilometers in Italy, a sports park in the north of Songshan Lake in Dongguan, China, and an office in Foshan, China renovation, office space renovation in Guangzhou, China, etc.

Whether it is an office space of 3,000 square meters or a corner of an urban village of 30 square meters, we will go to the site to conduct project research, take pictures and videos, measure the project, communicate customer needs, plan setting and post-construction, etc. These data are very large, but also very important, and we want to store the data on the Filecoin network.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
Whether it is a 3,000-square-meter office space or a 30-square-meter urban village, we will go to the site to conduct project research, take pictures and videos, measure the project, communicate customer needs, plan setting, and post-construction.

The data we want to store is:
1. Design draft (before a real design plan is determined, at least 10 drafts need to be designed back and forth)
2. Project information (address, floor area, renovation needs, budgeted cost)
3. Pictures and videos before construction
4. Pictures and videos after the construction is completed
As designers, we store a lot of data, and we hope to reduce the storage burden for us by storing publicly available data on the filecoin network. Thank you Filecoin Network!
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### How do you plan to prepare the dataset

IPFS, lotus, singularity

### Please share a sample of the data

```text
We provide about 5G data cases.This is a greenway project we did for Chengdu, China.

Link: https://pan.baidu.com/s/1-cDn173CpF8wIIqfCK38Og
Extraction code: mpvh
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

2 to 3 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, Europe

### How will you be distributing your data to storage providers

HTTP or FTP server, IPFS, Lotus built-in data transfer

### How do you plan to choose storage providers

Slack, Filmine, Big data exchange

### How do you plan to make deals to your storage providers

Boost client, Lotus client, Singularity

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by alllikes** [comment]
I forgot the login password of 1717's GitHub account, so I can't log in, so I can only re-register and submit#1719。I can prove my identity by any ways

**Comment by Sunnyiscoming** [comment]
@allgood6 If @alllikes is not your partner. You can reopen this one.
