### ISSUE TITLE
[DataCap Application] FileGuard - Open Agriculture Datasets for Machine Learning

### ISSUE THREAD

**Issue by cryptomandy** [filecoin-project/filecoin-plus-large-datasets#1718]
### Data Owner Name

FileGuard

### Data Owner Country/Region

China

### Data Owner Industry

Web3 / Crypto

### Website

https://fileguard.io

### Social Media

```text
N/A
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

800TiB

### On-chain address for first allocation

f1yl62r3kxonvnwwnwz6cx5boq2hddmwrcaqou42q

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
As a machine learning & deep learning training data provider, FileGuard provide a complete data solution of "software + hardware", Help algorithm companies collect and check data. A complete set of solutions for cleaning, desensitization, labeling, storing, transfer, etc. FileGuard have served more than 30 artificial intelligence enterprise customers since 2018, suce as Face++, SenseTime, JD finance and so on, providing customers with more than 20 million image annotation data, and about 200,000 crowdsourcers working on the FileGuard platform.

As a platform all in Web3, We have been engaged with storing real and valuable machine learning & deep learning datasets on the Filecoin network. We focus on the three areas of artificial intelligence: computer vision(CV), natural language processing(NLP) and speech processing. We believe that the Web3 way of storing these valuable data, such as autonomous driving, cancer, disease, geographic, agriculture, speech, and NLP data, will bring huge changes.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
The data being stored onto Filecoin including 7 AWS open agriculture datasets for machine learning:

1. NASA Prediction of Worldwide Energy Resources (POWER)
- LINK: https://registry.opendata.aws/nasa-power/
NASA's goal in Earth science is to observe, understand, and model the Earth system to discover how it is changing, to better predict change, and to understand the consequences for life on Earth. The Applied Sciences Program serves NASA and Society by expanding and accelerating the realization of societal and economic benefits from Earth science, information, and technology research and development.

2. ESA WorldCover
- LINK: https://registry.opendata.aws/esa-worldcover-vito/
The European Space Agency (ESA) WorldCover product provides global land cover maps for 2020 & 2021 at 10 m resolution based on Copernicus Sentinel-1 and Sentinel-2 data.

3. Sentinel-2 L2A 120m Mosaic
- LINK: https://registry.opendata.aws/sentinel-s2-l2a-mosaic-120/
Sentinel-2 L2A 120m mosaic is a derived product, which contains best pixel values for 10-daily periods, modelled by removing the cloudy pixels and then performing interpolation among remaining values. As there are some parts of the world, which have lengthy cloudy periods, clouds might be remaining in some parts.

4. iSDAsoil
- LINK: https://registry.opendata.aws/isdasoil/
iSDAsoil is a resource containing soil property predictions for the entire African continent, generated using machine learning. Maps for over 20 different soil properties have been created at 2 different depths (0-20 and 20-50cm).

5. Africa Soil Information Service (AfSIS) Soil Chemistry
- LINK: https://registry.opendata.aws/afsis/
This dataset contains soil infrared spectral data and paired soil property reference measurements for georeferenced soil samples that were collected through the Africa Soil Information Service (AfSIS) project, which lasted from 2009 through 2018.

6. AgricultureVision
- LINK: https://registry.opendata.aws/intelinair_agriculture_vision/
Agriculture-Vision aims to be a publicly available large-scale aerial agricultural image dataset that is high-resolution, multi-band, and with multiple types of patterns annotated by agronomy experts. The original dataset affiliated with the 2020 CVPR paper includes 94,986 512x512images sampled from 3,432 farmlands with nine types of annotations: double plant, drydown, endrow, nutrient deficiency, planter skip, storm damage, water, waterway and weed cluster.

7. Longitudinal Nutrient Deficiency
- LINK: https://registry.opendata.aws/intelinair_longitudinal_nutrient_deficiency/
Dataset associated with the 2021 AAAI Paper- Detection and Prediction of Nutrient Deficiency Stress using Longitudinal Aerial Imagery. The dataset contains 3 image sequences of aerial imagery from 386 farm parcels which have been annotated for nutrient deficiency stress.
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### How do you plan to prepare the dataset

lotus, singularity

### Please share a sample of the data

```text
s3://power-analysis-ready-datastore/
s3://esa-worldcover/
s3://sentinel-s2-l2a-mosaic-120/
s3://isdasoil/
s3://afsis/
s3://intelinair-data-releases/agriculture-vision/cvpr_paper_2020/
s3://intelinair-data-releases/longitudinal-nutrient-deficiency/
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

1 to 1.5 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, Europe

### How will you be distributing your data to storage providers

Cloud storage (i.e. S3), HTTP or FTP server, Shipping hard drives

### How do you plan to choose storage providers

Slack, Partners

### If you already have a list of storage providers to work with, fill out their names and provider IDs below

```text
| MinerID   | City       | Continent | Business/Entity |
| --------- | ---------- | --------- | --------------- |
| f01824405 | ChengDu    | CN        | RY              |
| f01991416 | HongKong   | CN        | RIKIMARU        |
| f02012032 | HongKong   | CN        | RIKIMARU        |
| f02006691 | HongKong   | CN        | NIHICHE         |
| f02027952 | London     | UK        | Mochi           |
| f02014107 | Seoul      | KR        | HMT             |
| f02028326 | California | USA       | Fyii            |
| f01518369 | California | USA       | Megalayer       |
| f01889668 | California | USA       |                 |
```

### How do you plan to make deals to your storage providers

Boost client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Can you fill out [this form](https://form.jotform.com/230337462961356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!

**Comment by cryptomandy** [comment]
@cryptowhizzard Hello, the KYC form has been submitted.

Thanks!

**Comment by cryptowhizzard** [comment]
Hi @cryptomandy 

KYC is well received. I am waiting for the datacap trigger and will propose / sign.

Thanks! looking forward to your first milestone!

Ps... same goes for #1715 #1714 #1712 and #1711.

**Comment by cryptomandy** [comment]
Hello @Sunnyiscoming 
The KYC has done, could you please approve this application, and #1711, #1712, #1714, #1715.

Thanks!

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 5PiB

**Expected weekly DataCap usage rate**
> 800TiB

**Client address**
>f1yl62r3kxonvnwwnwz6cx5boq2hddmwrcaqou42q

**Comment by cryptomandy** [comment]
Hello @cryptowhizzard  The datacap has triggered, could you please sign the first round? 
And for #1711, #1712, #1714, #1715.

Thanks a lot!

**Comment by cryptowhizzard** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebhpa5gjqcfru6c33jqzdlkvqlskib2xfk76e3ctrt3rlp5763hzm 
#### Address 
> f1yl62r3kxonvnwwnwz6cx5boq2hddmwrcaqou42q
#### Datacap Allocated
> 256.00TiB
#### Signer Address
> f1krmypm4uoxxf3g7okrwtrahlmpcph3y7rbqqgfa
#### Id
> 01eef23b-0e29-4c1b-8784-326f63163b0b
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebhpa5gjqcfru6c33jqzdlkvqlskib2xfk76e3ctrt3rlp5763hzm

**Comment by cryptomandy** [comment]
@kernelogic  @xinaxu @psh0691 @Joss-Hua
Dear notaries, I noticed you are very active notaries on other LDNs, could you please help us to move forward? Any question please leave a comment. Thanks a lot!

**Comment by cryptomandy** [comment]
checker:manualTrigger

**Comment by cryptomandy** [comment]
checker:manualTrigger

**Comment by cryptomandy** [comment]
checker:manualTrigger

**Comment by ipfscn** [comment]
As a first round, temporary support, I will confirm SP IDs and locations match your plan
、confirm data is retrievable and data sample matches said datasets

**Comment by ipfscn** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecqcjverebu76zfondnkazua4fiktw4k3zwu7iybrqeu3237aswyo 
#### Address 
> f1yl62r3kxonvnwwnwz6cx5boq2hddmwrcaqou42q
#### Datacap Allocated
> 256.00TiB
#### Signer Address
> f1j4n74chme7whbz3yls4a7ixqewb6dijypqg2a3a
#### Id
> 01eef23b-0e29-4c1b-8784-326f63163b0b
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecqcjverebu76zfondnkazua4fiktw4k3zwu7iybrqeu3237aswyo

**Comment by cryptomandy** [comment]
checker:manualTrigger

**Comment by cryptowhizzard** [comment]
Dear cryptomandy,

As notary I am doing due diligence on your LDN. I could not get retrieval to work. Can you please upload the car file of CID  ?

You can use our upload system at http://send.datasetcreators.com. Please select 7 days for the system to keep the file and post the link you received here so I (and other notaries) can download your content.

**Comment by cryptomandy** [comment]
Sure, uploading...

**Comment by cryptomandy** [comment]
checker:manualTrigger

**Comment by cryptomandy** [comment]
checker:manualTrigger
