### ISSUE TITLE
[DataCap Application] Guangzhou All Architectural Design Co., Ltd

### ISSUE THREAD

**Issue by alllikes** [filecoin-project/filecoin-plus-large-datasets#1719]
### Data Owner Name

Guangzhou All Architectural Design Co., Ltd.

### Data Owner Country/Region

China

### Data Owner Industry

Resources, Agriculture & Fisheries

### Website

http://www.a-ll.cn/

### Social Media

```text
http://www.a-ll.cn/
```

### Total amount of DataCap being requested

3PiB

### Weekly allocation of DataCap requested

300TiB

### On-chain address for first allocation

f1h7fzawspx7pdxasqim4okbb67lmjg7jmoor67ma

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
All Architecture is an open experimenter of space.

We are an independent design team established in Guangzhou, China. The three partners graduated from Berlage College in the Netherlands. We were officially established in 2015, but since 2012, we have been in the field of design and research of architecture and cities.

We currently have 36 employees in the company, 17 of whom are designers, and we have undertaken many designs from all over the world, such as a hotel with an area of ​​three kilometers in Italy, a sports park in the north of Songshan Lake in Dongguan, China, and an office in Foshan, China renovation, office space renovation in Guangzhou, China, etc.

Whether it is an office space of 3,000 square meters or a corner of an urban village of 30 square meters, we will go to the site to conduct project research, take pictures and videos, measure the project, communicate customer needs, plan setting and post-construction, etc. These data are very large, but also very important, and we want to store the data on the Filecoin network.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
Whether it is a 3,000-square-meter office space or a 30-square-meter urban village, we will go to the site to conduct project research, take pictures and videos, measure the project, communicate customer needs, plan setting, and post-construction.

The data we want to store is:
1. Design draft (before a real design plan is determined, at least 10 drafts need to be designed back and forth)
2. Project information (address, floor area, renovation needs, budgeted cost)
3. Pictures and videos before construction
4. Pictures and videos after the construction is completed
As designers, we store a lot of data, and we hope to reduce the storage burden for us by storing publicly available data on the filecoin network. Thank you Filecoin Network!
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### How do you plan to prepare the dataset

IPFS, lotus, singularity

### Please share a sample of the data

```text
We provide about 5G data cases.This is a greenway project we did for Chengdu, China.

Link: https://pan.baidu.com/s/1-cDn173CpF8wIIqfCK38Og
Extraction code: mpvh
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

2 to 3 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, Europe

### How will you be distributing your data to storage providers

HTTP or FTP server, IPFS, Lotus built-in data transfer

### How do you plan to choose storage providers

Slack, Filmine, Big data exchange

### How do you plan to make deals to your storage providers

Boost client, Lotus client, Singularity

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by alllikes** [comment]
#1717 
Sorry, after I just submitted the application, I found that I forgot my GitHub login password, so I can only re-register a GitHub and submit again.  Please help me refuse or close 1717. I can prove my identity by any ways, such as sending emails or issuing a business license.  Thank you for your understanding!

**Comment by alllikes** [comment]
I forgot the login password of 1717's GitHub account, so I can't log in, so I can only re-register and submit。I can prove my identity by any ways

**Comment by Carohere** [comment]
>The data we want to store is:
>1. Design draft (before a real design plan is determined, at least 10 drafts need to be designed back and forth)
>2. Project information (address, floor area, renovation needs, budgeted cost)
>3. Pictures and videos before construction
>4. Pictures and videos after the construction is completed

Can you elaborate on the data size and the number of copies you plan to store?

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Looking at your application i have some questions:
As you are brand new on Github and have no history of past applications it seems to me that applying for 3PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?

Can you show us visible proof of the size of your data and the storage systems you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230337462961356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!

**Comment by Carohere** [comment]
@alllikes copy volume sounds good, appreciate the details. I'm also wondering if there are any confirmed service providers at the moment and has your organization participated in FIL+ projects before.

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 3PiB

**Expected weekly DataCap usage rate**
> 300TiB

**Client address**
>f1h7fzawspx7pdxasqim4okbb67lmjg7jmoor67ma

**Comment by alllikes** [comment]
> @alllikes copy volume sounds good, appreciate the details. I'm also wondering if there are any confirmed service providers at the moment and has your organization participated in FIL+ projects before.

Sorry for the late reply, we have contacted 6 SPs , currently, we are contacting more SPs to finalize the cooperation SP. The founders of our company all have a background of studying abroad. They learned about crypto and filecoin very early, and they own 5 cryptocurrencies on OKX.

**Comment by alllikes** [comment]
If possible, we hope to get your help, please tell me what I need to do?

**Comment by stcouldlisa** [comment]
I think you need to send email to filplus-app-review@fil.org with domain mailbox, ID should contain 1719

**Comment by alllikes** [comment]
I sent an email with a domain name mailbox, please help us, We will remember your kind support，thank you
<img width="619" alt="WX20230314-171535@2x" src="https://user-images.githubusercontent.com/126857864/224979212-7b975ba9-90f8-473b-872d-c30ffd640ea6.png">

**Comment by igoovo** [comment]
If you want to get support, you need to list a minimum of 4 SPs .

**Comment by alllikes** [comment]
Thanks for everyone's questions, we have just confirmed our final cooperation SP, please extend your kind olive branch and help us:
f01927554
f01927252
f01989013
f01928022
f01859603
f01938671

**Comment by stcouldlisa** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedt3xql6ksrkjsheqfcabwglvhgaq3emzxzriyqsod3qgv2bq7t74 
#### Address 
> f1h7fzawspx7pdxasqim4okbb67lmjg7jmoor67ma
#### Datacap Allocated
> 150.00TiB
#### Signer Address
> f1jvvltduw35u6inn5tr4nfualyd42bh3vjtylgci
#### Id
> 27221725-af57-4c41-95a4-e069ebc9e3a9
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedt3xql6ksrkjsheqfcabwglvhgaq3emzxzriyqsod3qgv2bq7t74

**Comment by igoovo** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecanlzdodfvpnnqbpr55fr7xlwewpzkss3jzxabg7b5cuc453bmnm 
#### Address 
> f1h7fzawspx7pdxasqim4okbb67lmjg7jmoor67ma
#### Datacap Allocated
> 150.00TiB
#### Signer Address
> f1shnsfayxqll77svffaxnjenms7bbbysbqcatrpy
#### Id
> 27221725-af57-4c41-95a4-e069ebc9e3a9
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecanlzdodfvpnnqbpr55fr7xlwewpzkss3jzxabg7b5cuc453bmnm

**Comment by sxxfuture-official** [comment]
@alllikes 
Can you explain the problem of CID sharing, although it doesn't seem like much, but I want to understand the reason~

**Comment by alllikes** [comment]
I am very sorry.The reason for the shared transaction error is that the SP was accepting data loads from multiple Clients and this morning they sent me the wrong table for the Car CID and I didn't do enough checking and my script executed it directly, thus causing the error.

We have promptly notified the SP to suspend loading data into Filecoin.
We are very sorry for this situation.

The filecoin community is tolerant, please forgive me for being lazy this time, and I will check with my eyes open in the future.Even, I will ask the sp not to cooperate with multiple LDNs at the same time, so as to prevent this kind of behavior from happening.

Please don't give us a death sentence, it wasn't our fault, our opportunities didn't come easy and we are so grateful.

**Comment by sxxfuture-official** [comment]
![image](https://user-images.githubusercontent.com/113963951/225561343-e03364d5-d10e-4d7c-907f-6a2434a804ad.png)
![image](https://user-images.githubusercontent.com/113963951/225561849-48c42994-58bf-4b22-a44a-bbda21828e07.png)
The retrieval test results look good, and the CID Sharing problem hopes to be resolved as soon as possible

**Comment by sxxfuture-official** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacea2pwiwejbargzvpx6jlzpvugcc2sda4oupdwvjjwq6f4kct2dg6o 
#### Address 
> f1h7fzawspx7pdxasqim4okbb67lmjg7jmoor67ma
#### Datacap Allocated
> 300.00TiB
#### Signer Address
> f1foiomqlmoshpuxm6aie4xysffqezkjnokgwcecq
#### Id
> 8f4b2d32-7ba9-4367-8f7c-5d393f64bd68
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacea2pwiwejbargzvpx6jlzpvugcc2sda4oupdwvjjwq6f4kct2dg6o

**Comment by alllikes** [comment]
Dear community members, normally, the CID table is kept and released by us, but considering that the data may be damaged or lost during transportation, for the sake of insurance, we will choose to let the SP, after receiving the data, Export a CID form to us, and then we compare the form provided by the SP with our form, and then issue the bill.
But this time, when the SP exported the CID, it exported the wrong order, and I didn't choose to check with our correct CID table, so I directly executed it with the script. So it leads to sharing. I implore you to tolerate and understand us.

**Comment by Carohere** [comment]
Still don't get the logic behind it. @herrehesse can you take a look here?

**Comment by alllikes** [comment]
We have Datacap and Data CID ➡️ We transmit data to SP ➡️ After SP receives the data ➡️ We use Boost to issue bills and start loading data into Filecoin


But because our transmission method is carried out offline, there is a risk of hard disk damage, so we changed the process to

We have Datacap and Data CID ➡️ We transmit data to SP ➡️ After SP receives the data, it exports all Data CID ➡️ SP sends us the table of Data CID ➡️ We proofread the table provided by SP with the table we own ➡️ Record supplement Send the missing CID file, and use the overlapping CID as the basis for issuing the bill

But in this process, two people made mistakes
First, when the SP exported the Data CID, it exported the wrong CID table
Secondly, when we were doing data proofreading, we did not proofread, resulting in the wrong CID being executed.

**Comment by alllikes** [comment]
I don't know how you feel about it, but it's true. If possible, I would like to be treated with trust and kindness.Everyone makes mistakes, and we want to have the opportunity to correct them.

**Comment by lvschouwen** [comment]
> I don't know how you feel about it, but it's true. If possible, I would like to be treated with trust and kindness.Everyone makes mistakes, and we want to have the opportunity to correct them.

Then ask the SP to terminate the 2.41TiB of sectors.

**Comment by alllikes** [comment]
> > 我不知道你怎么想的，但这是真的。如果可能的话，我希望得到信任和善意的对待。每个人都会犯错误，我们希望有机会改正错误。
> 
> 如果您想更正此问题……请要求 SP 终止 2.41TiB 扇区。

I agree with you that each of us needs to be responsible for our own mistakes even if it is just an accident, I am communicating with sp right now,

**Comment by alllikes** [comment]
Sorry, SP's technology is unwilling to go to Remove DC, because it involves the approval of many investors.
Sorry, I didn't strive for a good result.
I still hope that the community will give us another chance to correct, because if we are liars, we will not choose to cheat in the first round.
We hope to get another round to prove ourselves

**Comment by alllikes** [comment]
I want to fight for tolerance, but if you don't trust me, I can accept the result.

**Comment by lvschouwen** [comment]
> Sorry, SP's technology is unwilling to go to Remove DC, because it involves the approval of many investors. Sorry, I didn't strive for a good result. I still hope that the community will give us another chance to correct, because if we are liars, we will not choose to cheat in the first round. We hope to get another round to prove ourselves

Are you willing to stop co-operation with the SP who did the sharing and find a new SP before you be granted the next cap?

**Comment by alllikes** [comment]
I can make a promise that we will strengthen the checking and management process to ensure that mistakes will not be made again.

About not cooperating with sp, I am communicating with sp, it is not an easy decision, because sp did not do evil, they are not bad. Of course, someone must pays for the mistake.

I respect the filecoin community. If you suggest that I do not cooperate with these sps, I will also apply to the company and contact new sps.

Trust is hard, but we still want to do something to regain it.

**Comment by alllikes** [comment]
Everyone is busy now, if anyone notices us and is willing to believe that the cid of only 2.4T is indeed a mistake, please help us. I am still working overtime in the company, waiting for the community's reply. If someone is willing to help us, we would like to explain this mistake at the next notary meeting.

**Comment by Tom-OriginStorage** [comment]
checker:manualTrigger

**Comment by Tom-OriginStorage** [comment]
Looking at the packaging report, it was found that some CIDs were shared, while the rest were relatively healthy. The customer explained that they were caused by incorrect operations, and will continue to pay attention later. If shared CIDs increase, further communication will be conducted with the customer. Random selection of sectors for retrieval is normal. I am willing to support this round

**Comment by Tom-OriginStorage** [comment]
<img width="932" alt="image" src="https://user-images.githubusercontent.com/103015469/226165716-738dae7d-ecc3-4662-85ca-da968f6b595b.png">

**Comment by Tom-OriginStorage** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecce2rsjb4hjthuvf3hrrboarzbcdmepspfwzymehy324qcpem5n6 
#### Address 
> f1h7fzawspx7pdxasqim4okbb67lmjg7jmoor67ma
#### Datacap Allocated
> 300.00TiB
#### Signer Address
> f1q6bpjlqia6iemqbrdaxr2uehrhpvoju3qh4lpga
#### Id
> 8f4b2d32-7ba9-4367-8f7c-5d393f64bd68
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecce2rsjb4hjthuvf3hrrboarzbcdmepspfwzymehy324qcpem5n6

**Comment by laurarenpanda** [comment]
> 68.26% of deals are for data replicated across less than 4 storage providers.

This is a common issue when SPs have different sealing speeds. Hope this data item can be improved in the next batch.
Your explanation of CID sharing is kindly logical on my side. However, if this similar situation happens again, it will be hard for me to support this project.

**Comment by laurarenpanda** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaul6qkvdx4kwuoxt5nux4ybmcqhi2eizmvur6vq3kh6v3gas3ygu 
#### Address 
> f1h7fzawspx7pdxasqim4okbb67lmjg7jmoor67ma
#### Datacap Allocated
> 600.00TiB
#### Signer Address
> f1bp3tzp536edm7dodldceekzbsx7zcy7hdfg6uzq
#### Id
> 3708fa31-079e-43da-b22e-96281d3a1ae1
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaul6qkvdx4kwuoxt5nux4ybmcqhi2eizmvur6vq3kh6v3gas3ygu

**Comment by OpenGate01** [comment]
The client explained that the CID sharing situation was the result of a mistake. As community members, we choose to forgive mistakes, but not condone intentional mistakes, so we chose to support this round and keep an eye on this application.

**Comment by OpenGate01** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecelzk6ree4qsyxh3mfv4nqf4ixsxyu2rrhfynydgub7jhwexswws 
#### Address 
> f1h7fzawspx7pdxasqim4okbb67lmjg7jmoor67ma
#### Datacap Allocated
> 600.00TiB
#### Signer Address
> f1im4hmtbfzqnx7ir74kdaiu4ynjhgqh3sdi2snla
#### Id
> 3708fa31-079e-43da-b22e-96281d3a1ae1
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecelzk6ree4qsyxh3mfv4nqf4ixsxyu2rrhfynydgub7jhwexswws

**Comment by stcouldlisa** [comment]
checker:manualTrigger

**Comment by stcouldlisa** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedkomk57wqg3326tnly5z6brbiogck7wxfpuhici4mwa6yxncpbzs 
#### Address 
> f1h7fzawspx7pdxasqim4okbb67lmjg7jmoor67ma
#### Datacap Allocated
> 1.17PiB
#### Signer Address
> f1jvvltduw35u6inn5tr4nfualyd42bh3vjtylgci
#### Id
> 63f55bcf-4ba3-4a5d-8ab1-5027a0656e31
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedkomk57wqg3326tnly5z6brbiogck7wxfpuhici4mwa6yxncpbzs

**Comment by woshidama323** [comment]
> Looking at the packaging report, it was found that some CIDs were shared, while the rest were relatively healthy. The customer explained that they were caused by incorrect operations, and will continue to pay attention later. If shared CIDs increase, further communication will be conducted with the customer. Random selection of sectors for retrieval is normal. I am willing to support this round

As you have explained the reason of these  Warning  about "Deal Data Replication" and "Deal Data Shared with other Clients"
Wish you Could fix those warnings at the next round
I will help to approve this.

**Comment by woshidama323** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceavdtja4vnheuvb4onbiq7ar5pdfve3nsvma56elrdzxfigmbjbie 
#### Address 
> f1h7fzawspx7pdxasqim4okbb67lmjg7jmoor67ma
#### Datacap Allocated
> 1.17PiB
#### Signer Address
> f12tk3adljauwnd3hjbigpfxb7b7gdlj63p6afwtq
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceavdtja4vnheuvb4onbiq7ar5pdfve3nsvma56elrdzxfigmbjbie

**Comment by Joss-Hua** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedm7iulcub7mjcvvcx6afx3y5rsx4p7gd7m4zrtxsq474le7tzaay 
#### Address 
> f1h7fzawspx7pdxasqim4okbb67lmjg7jmoor67ma
#### Datacap Allocated
> 823.92TiB
#### Signer Address
> f1tfg54zzscugttejv336vivknmsnzzmyudp3t7wi
#### Id
> bd444203-174f-4283-aaa8-513c53398f5f
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedm7iulcub7mjcvvcx6afx3y5rsx4p7gd7m4zrtxsq474le7tzaay

**Comment by METAVERSEDATAMINING** [comment]
Data retrieval feedback, everything is normal.Support this round.

**Comment by METAVERSEDATAMINING** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecgkulc4eogjtpbhnsq2imhi46aopedxz7sykpq7kg4cegujj6jp2 
#### Address 
> f1h7fzawspx7pdxasqim4okbb67lmjg7jmoor67ma
#### Datacap Allocated
> 823.92TiB
#### Signer Address
> f17idrnfnxl2mbgcgr57a6z2c6lj2qx56gvm3336i
#### Id
> bd444203-174f-4283-aaa8-513c53398f5f
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecgkulc4eogjtpbhnsq2imhi46aopedxz7sykpq7kg4cegujj6jp2

**Comment by C00kies77** [comment]
checker:manualTrigger
