### ISSUE TITLE
[DataCap Application] HarryMa - Slingshot Restore Program 

### ISSUE THREAD

**Issue by woshidama323** [filecoin-project/filecoin-plus-large-datasets#172]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: HarryM - Slingshot Restore
- Website / Social Media: https://www.topblocks.io/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 500 TiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 500 TiB
- On-chain address for first allocation: f1ufbhme24mzlo3mtzx3hkhte3xndpinq7xycezxi

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
this DataCap is for **Slingshot Restore Program**, and the detail is follows:

https://docs.google.com/document/d/1ZH4URWaNYtlddZwZMyqcSnc3GRsR3zCqnW0RfkkNlr8/edit# 
https://docs.google.com/document/d/1sGLkw321Fl09jvAr80kFY2FcQWa1H-dYpowXFRWo-OM/edit 

https://docs.google.com/spreadsheets/d/1UYmVtwtJUIAwlogZmLSZB_nZxWrVlID6ryfqrB0jBjw/edit#gid=1779251844 
https://docs.google.com/spreadsheets/d/1Skga2Yn0BD7CDgT1WQmKtPJ3nxhQ4QWd45e78Y42Wjc/edit#gid=0



```
![image](https://user-images.githubusercontent.com/11014169/147347087-8db2ea23-2916-4243-9da6-954d93fffbbf.png)

![image](https://user-images.githubusercontent.com/11014169/147347131-79397168-8eb6-4014-abbc-5a70878f9d7c.png)

![image](https://user-images.githubusercontent.com/11014169/147347220-ebfb7009-2463-4bd1-87e8-80b20b4a101d.png)

What is the primary source of funding for this project?
```
From the slingshot team and my team.
```

What other projects/ecosystem stakeholders is this project associated with?
```
No
```

## Use-case details

Describe the data being stored onto Filecoin
```
Have participated in the Slingshot Restore project an planed to finish DataSet repairing task
```
![image](https://user-images.githubusercontent.com/11014169/147347520-6a791c2e-9126-48c3-b18e-a6eec092c1da.png)

![image](https://user-images.githubusercontent.com/11014169/147347485-5d004871-fba4-4083-a7e3-259c8374c738.png)

![image](https://user-images.githubusercontent.com/11014169/147347602-375a1589-fc29-4270-8d39-c5cd2ffb2dcf.png)

Where was the data in this dataset sourced from?
```
The data comes from the slingshot team assigned to me by the project: 
These dataset comes from https://hub.docker.com/search?type=image

Details info could be reviewed from above info
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://hub.docker.com/search?type=image&category=storage
https://hub.docker.com/search?type=image&category=monitoring
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes
```

What is the expected retrieval frequency for this data?
```
Anytime.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
More than 500 days
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
San Francisco Bay Area
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
I will store every file to at least 4 storage providers, the offline data process will be supported.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
The three storage providers will locate different regions, and their power must be more than 5PiB. And providers must agree that they should store unsealed files and keep these data retrieved all the time.
```

How will you be distributing deals across storage providers?
```
One storage provider will get one data-deal at least.  And the more power storage provider has, the more deals will be assigned. 
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, I have contacted some providers. And the data download has been downloaded. 

```

**Comment by galen-mcandrew** [comment]
## Multisig Notary requested
#### Total DataCap requested 
> 500TiB
#### Expected weekly DataCap usage rate 
> 500TiB

**Comment by flyworker** [comment]
i cannot find this case in https://plus.fil.org/app

**Comment by flyworker** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedpfqaavd3ukhkgcx2yveciwjgdnvxku5zdbeg4znssgphzwhoqns 
#### Address 
> f1ufbhme24mzlo3mtzx3hkhte3xndpinq7xycezxi
#### Datacap Allocated
> 25TiB
#### Signer Address
> f1hlubjsdkv4wmsdadihloxgwrz3j3ernf6i3cbpy
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedpfqaavd3ukhkgcx2yveciwjgdnvxku5zdbeg4znssgphzwhoqns

**Comment by MegTei** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced2zn5ywg7uzdr6744tscimdj56rogmm6gc2rie72yx2qvyi5wexe 
#### Address 
> f1ufbhme24mzlo3mtzx3hkhte3xndpinq7xycezxi
#### Datacap Allocated
> 25TiB
#### Signer Address
> f1ystxl2ootvpirpa7ebgwl7vlhwkbx2r4zjxwe5i
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced2zn5ywg7uzdr6744tscimdj56rogmm6gc2rie72yx2qvyi5wexe

**Comment by dannyob** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec2xz2pq6lpjmfn6emysmh34ns6gjidvjsadperslvu4xmwzghyt6 
#### Address 
> f1ufbhme24mzlo3mtzx3hkhte3xndpinq7xycezxi
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1k6wwevxvp466ybil7y2scqlhtnrz5atjkkyvm4a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec2xz2pq6lpjmfn6emysmh34ns6gjidvjsadperslvu4xmwzghyt6

**Comment by MegTei** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebnhymfgcqoscmwbbtopqdg4ctefiw5cltxy4yh53vyhhtj24qlhw 
#### Address 
> f1ufbhme24mzlo3mtzx3hkhte3xndpinq7xycezxi
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1ystxl2ootvpirpa7ebgwl7vlhwkbx2r4zjxwe5i
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebnhymfgcqoscmwbbtopqdg4ctefiw5cltxy4yh53vyhhtj24qlhw

**Comment by dkkapur** [comment]
@woshidama323 - what deals are you making at this point in time? Restore ops are mostly on pause, I was under the impression you were not participating? Why does your top provider have 99+% of deals allocated to it?

**Comment by woshidama323** [comment]
Well, You know, As slingshot 2.8 gets stuck for a long time and my SPs has been unable to get enough verified deals from any other clients to feed their expected growth rate. Just found that this client has only 25TiB DC, Maybe it can be used . Therefore we have been using this dc to store additional copies of the slingshot restore data. 

https://registry.opendata.aws/giab/

Actually, we only want to use 25TiB to let SP could increase its power in a short time and SP could have time to wait for slingshot2.8, I think it's not too much, But not sure why Datacap is still allocated with 50TiB?

As not know any announcement about the restore program , I think this dataset could be stored to sp as many people still did not finish them to 5 replicas finally?

Please let me know if I can still send them to SP? If not I will stop it and apologize for this ops?

We hope to hear about the program's future plan to re-evaluate again.

**Comment by dkkapur** [comment]
@woshidama323 data through Fil+ should be distributed to multiple SPs. the goals are to build constructs that result in clients being successful in storing data that is highly available and retrievable long term. just storing all the deals with a single SP to accelerate growth is not in line with the principles of the program. do you intend to make deals with other SP organizations as well?

**Comment by woshidama323** [comment]
Yes, Of course, But could you help to share what's the plan about restore project in the future? 
Maybe I have missed any latest news about restore project.
Actually, we have many SPs cooperating well in the past and I think they always need deals for increasing their power.
It's not hard for me to send deals for them as long as I have dataset and enough Datacap.

**Comment by dannyob** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec36xp3qkbnb57vvot6jkjygazusdodvn53z3godiqa6hy7z2h22y 
#### Address 
> f1ufbhme24mzlo3mtzx3hkhte3xndpinq7xycezxi
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1k6wwevxvp466ybil7y2scqlhtnrz5atjkkyvm4a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec36xp3qkbnb57vvot6jkjygazusdodvn53z3godiqa6hy7z2h22y

**Comment by MegTei** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb46u7hmotqlvjnnsngyr5c4bwqrqtypbgegqjk3nak6hiezyyeni 
#### Address 
> f1ufbhme24mzlo3mtzx3hkhte3xndpinq7xycezxi
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1ystxl2ootvpirpa7ebgwl7vlhwkbx2r4zjxwe5i
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb46u7hmotqlvjnnsngyr5c4bwqrqtypbgegqjk3nak6hiezyyeni

**Comment by dannyob** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceczota4i3z7n5s2e5kwawxczcd62yhk4aa6ec367cerynbfgaf2k2 
#### Address 
> f1ufbhme24mzlo3mtzx3hkhte3xndpinq7xycezxi
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1k6wwevxvp466ybil7y2scqlhtnrz5atjkkyvm4a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceczota4i3z7n5s2e5kwawxczcd62yhk4aa6ec367cerynbfgaf2k2

**Comment by dkkapur** [comment]
@woshidama323 as far as I know https://docs.google.com/spreadsheets/d/1UYmVtwtJUIAwlogZmLSZB_nZxWrVlID6ryfqrB0jBjw/edit#gid=1779251844 you are not on the list of clients correct? Moving this one to needsDiligence till we can align on your participation here. Can you ping me in Slack?

**Comment by woshidama323** [comment]
Hi @dkkapur  Have ping you on slack yesterday
Looking forward to your reply.

**Comment by woshidama323** [comment]
@dkkapur Could you please help to check msg on slack when you are free?

**Comment by filplus-checker** [comment]
## DataCap and CID Checker Report[^1]
 - Organization: `HarryM - Slingshot Restore`
 - Client: `f1ufbhme24mzlo3mtzx3hkhte3xndpinq7xycezxi`
### Storage Provider Distribution
The below table shows the distribution of storage providers that have stored data for this client.

If this is the first time a provider takes verified deal, it will be marked as `new`.

For most of the datacap application, below restrictions should apply.
 - Storage provider should not exceed 25% of total datacap.
 - Storage provider should not be storing duplicate data for more than 20%.
 - Storage provider should have published its public IP address.
 - All storage providers should be located in different regions.

⚠️ [f03223](https://filfox.info/en/address/f03223) has sealed 27.31% of total datacap.

⚠️ 27.60% of total deal sealed by [f03223](https://filfox.info/en/address/f03223) are duplicate data.

⚠️ [f02301](https://filfox.info/en/address/f02301) has sealed 26.07% of total datacap.

⚠️ 24.49% of total deal sealed by [f02301](https://filfox.info/en/address/f02301) are duplicate data.

| Provider                                            |                 Location | Total Deals Sealed | Percentage | Unique Data | Duplicate Deals |
| :-------------------------------------------------- | -----------------------: | -----------------: | ---------: | ----------: | --------------: |
| [f03223](https://filfox.info/en/address/f03223)     | San Jose, California, US |          20.72 TiB |     27.31% |   15.00 TiB |          27.60% |
| [f02301](https://filfox.info/en/address/f02301)     | San Jose, California, US |          19.78 TiB |     26.07% |   14.94 TiB |          24.49% |
| [f0143858](https://filfox.info/en/address/f0143858) |  Clifton, New Jersey, US |          18.34 TiB |     24.18% |   15.03 TiB |          18.06% |
| [f0240185](https://filfox.info/en/address/f0240185) |  Clifton, New Jersey, US |          17.03 TiB |     22.45% |   15.00 TiB |          11.93% |

![Provider Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/172/1671093413022.png)
### Deal Data Replication
The below table shows how each many unique data are replicated across storage providers.
- No more than 25% of unique data are stored with less than 4 providers.

✔️ Data replication looks healthy.

| Unique Data Size | Total Deals Made | Number of Providers | Deal Percentage |
| ---------------: | ---------------: | ------------------: | --------------: |
|       288.00 GiB |       864.00 GiB |                   3 |           1.11% |
|        14.78 TiB |        75.03 TiB |                   4 |          98.89% |

![Replication Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/172/1671093413585.png)
### Deal Data Shared with other Clients
The below table shows how many unique data are shared with other clients.
Usually different applications owns different data and should not resolve to the same CID.

⚠️ CID sharing has been observed.

| Other Client                                                                                                          | Application                                                                                                               | Total Deals Affected | Unique CIDs |  Verifier |
| :-------------------------------------------------------------------------------------------------------------------- | :------------------------------------------------------------------------------------------------------------------------ | -------------------: | ----------: | --------: |
| [f1j6pwjnuo5a6s4ou7emsx6jymam5nu4es7ogf7tq](https://filfox.info/en/address/f1j6pwjnuo5a6s4ou7emsx6jymam5nu4es7ogf7tq) | [Fei Yan \- Kernelogic](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/304)                      |           304.50 TiB |         782 | LDN # 304 |
| [f15djc5avdxihguvpmtej24rzbvnnqvzurxe55kja](https://filfox.info/en/address/f15djc5avdxihguvpmtej24rzbvnnqvzurxe55kja) | [Kernelogic \- Fei Yan \- Slingshot Restore](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/136) |           188.94 TiB |         794 | LDN # 136 |
| [f1efk7kg5hgmd2r6yr4kyro24pou5hd64ua7x2iii](https://filfox.info/en/address/f1efk7kg5hgmd2r6yr4kyro24pou5hd64ua7x2iii) | [Fei Yan \- Kernelogic](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/298)                      |            27.59 TiB |         125 | LDN # 298 |

[^1]: To manually trigger this report, add a comment with text `checker:manualTrigger`

**Comment by MetaWaveInfo** [comment]
manualTrigger

**Comment by MetaWaveInfo** [comment]
checker:manualTrigger
