### ISSUE TITLE
[DataCap Application] 12Ships - Slingshot Restore Program

### ISSUE THREAD

**Issue by IreneYoung** [filecoin-project/filecoin-plus-large-datasets#173]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name:  12Ships Foundation
- Website / Social Media: https://www.12ships.com/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 2PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 200TiB
- On-chain address for first allocation: f15dyustlxyzv2qspxbepijxxnz6d74vn2ckqlq5i

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
This is a project for the Slingshot Restore Program to restore ~12.5PiB of Slingshot data on Filecoin as quickly as possible. The DataCap is for **Slingshot Restore Program** and 12Ships has been assigned restore data working as a client in this program. Find the detail here: Slingshot Restore - Client Assignments
(https://docs.google.com/spreadsheets/d/1UYmVtwtJUIAwlogZmLSZB_nZxWrVlID6ryfqrB0jBjw/edit?usp=sharing)

```

What is the primary source of funding for this project?
```
My team
```

What other projects/ecosystem stakeholders is this project associated with?
```
None
```

## Use-case details

Describe the data being stored onto Filecoin
```
Slingshot Restore data. 
See more details here: https://docs.google.com/document/d/1sGLkw321Fl09jvAr80kFY2FcQWa1H-dYpowXFRWo-OM/edit?usp=sharing
```

Where was the data in this dataset sourced from?
```
Assigned by Slingshot team. 
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://github.com/filecoin-project/slingshot/blob/master/datasets.md
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Confirmed
```

What is the expected retrieval frequency for this data?
```
Anytime as required
```

For how long do you plan to keep this dataset stored on Filecoin?
```
At least 500 days
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
I will pick 5 SPs across 3 countries
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
I will distribute the data to 5 SPs across 3 countries as required. Online or offline data transfer are both acceptable.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
I will store replicas of my assigned data with a set of storage providers that Slingshot team assigns to me.
```

How will you be distributing deals across storage providers?
```
Online or offline data transfer are both acceptable. It depends on the SP's ability to process the data.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes I have some resources. I will ask for support from Slingshot team if I need later.
```

**Comment by KwrayFF** [comment]
## Multisig Notary requested
#### Total DataCap requested 
> 2PiB
#### Expected weekly DataCap usage rate 
> 200TiB

**Comment by flyworker** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacede3xnpgowp2mtwo43fjobnh4eq6fmmsdthkoqow7t7g4iuo4fy4s 
#### Address 
> f15dyustlxyzv2qspxbepijxxnz6d74vn2ckqlq5i
#### Datacap Allocated
> 100TiB
#### Signer Address
> f1hlubjsdkv4wmsdadihloxgwrz3j3ernf6i3cbpy
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacede3xnpgowp2mtwo43fjobnh4eq6fmmsdthkoqow7t7g4iuo4fy4s

**Comment by MegTei** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb4jtefoihhqwkuy6edfkspmowwrgsk3ctrqxeqih2mhoqpercmuc 
#### Address 
> f15dyustlxyzv2qspxbepijxxnz6d74vn2ckqlq5i
#### Datacap Allocated
> 100TiB
#### Signer Address
> f1ystxl2ootvpirpa7ebgwl7vlhwkbx2r4zjxwe5i
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb4jtefoihhqwkuy6edfkspmowwrgsk3ctrqxeqih2mhoqpercmuc

**Comment by liyunzhi-666** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceajsuz225q7exy2fu6tmiv6t7l43qn3c7jz3ccipvqrufhcv5zpny 
#### Address 
> f15dyustlxyzv2qspxbepijxxnz6d74vn2ckqlq5i
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1pszcrsciyixyuxxukkvtazcokexbn54amf7gvoq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceajsuz225q7exy2fu6tmiv6t7l43qn3c7jz3ccipvqrufhcv5zpny

**Comment by newwebgroup** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecc2xonl7yzrhuydtctgnbcqk3autwr34ehk4rvhfr2e2tfgz7ldw 
#### Address 
> f15dyustlxyzv2qspxbepijxxnz6d74vn2ckqlq5i
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1e77zuityhvvw6u2t6tb5qlnsegy2s67qs4lbbbq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecc2xonl7yzrhuydtctgnbcqk3autwr34ehk4rvhfr2e2tfgz7ldw

**Comment by BigD-Exchange** [comment]
@IreneYoung Hi! Great to see you have gotten approval for DataCap. If you are looking for storage providers to store these data or have any questions, please visit #bigdata-exchange on Filecoin Slack or reply here. 

We have strong demand from a diverse group of SPs, who are actively looking to onboard more data.

**Comment by filplus-checker** [comment]
## DataCap and CID Checker Report[^1]
 - Organization: ` 12Ships Foundation`
 - Client: `f15dyustlxyzv2qspxbepijxxnz6d74vn2ckqlq5i`
### Storage Provider Distribution
The below table shows the distribution of storage providers that have stored data for this client.

If this is the first time a provider takes verified deal, it will be marked as `new`.

For most of the datacap application, below restrictions should apply.
 - Storage provider should not exceed 25% of total datacap.
 - Storage provider should not be storing duplicate data for more than 20%.
 - Storage provider should have published its public IP address.
 - All storage providers should be located in different regions.

⚠️ [f01652333](https://filfox.info/en/address/f01652333) has sealed 54.08% of total datacap.

⚠️ 33.60% of total deal sealed by [f01652333](https://filfox.info/en/address/f01652333) are duplicate data.

⚠️ [f01264125](https://filfox.info/en/address/f01264125) has sealed 45.92% of total datacap.

| Provider                                              |                  Location | Total Deals Sealed | Percentage | Unique Data | Duplicate Deals |
| :---------------------------------------------------- | ------------------------: | -----------------: | ---------: | ----------: | --------------: |
| [f01652333](https://filfox.info/en/address/f01652333) | Sunnyvale, California, US |          44.20 TiB |     54.08% |   29.35 TiB |          33.60% |
| [f01264125](https://filfox.info/en/address/f01264125) |      Montréal, Quebec, CA |          37.53 TiB |     45.92% |   37.44 TiB |           0.25% |

![Provider Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/173/1671093419280.png)
### Deal Data Replication
The below table shows how each many unique data are replicated across storage providers.
- No more than 25% of unique data are stored with less than 4 providers.

⚠️ 100.00% of deals are for data replicated across less than 4 storage providers.

| Unique Data Size | Total Deals Made | Number of Providers | Deal Percentage |
| ---------------: | ---------------: | ------------------: | --------------: |
|        66.79 TiB |        81.73 TiB |                   1 |         100.00% |

![Replication Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/173/1671093420095.png)
### Deal Data Shared with other Clients
The below table shows how many unique data are shared with other clients.
Usually different applications owns different data and should not resolve to the same CID.

✔️ No CID sharing has been observed.

[^1]: To manually trigger this report, add a comment with text `checker:manualTrigger`
