### ISSUE TITLE
[DataCap Application] <Webjangee Co., Ltd.> - <Nemostory>

### ISSUE THREAD

**Issue by webjangee** [filecoin-project/filecoin-plus-large-datasets#1730]
### Data Owner Name

Webjangee Co., Ltd.

### Data Owner Country/Region

Korea, Republic of

### Data Owner Industry

IT & Technology Services

### Website

https://nemostory.net

### Social Media

```text
https://www.youtube.com/@namroki
https://www.youtube.com/@user-wb7wn4zt6b
```

### Total amount of DataCap being requested

1PiB

### Weekly allocation of DataCap requested

10TiB

### On-chain address for first allocation

f3wh5rfqafqp46a26cw7n76bszwxpammwonavamj4pqp3vytk6bktu27o4o2izbih37ttd3mpetyodovrfpopq

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
* webjangee.com
webjangee.com is a business platform with experts with professional knowledge and experience in various fields such as web development, design, and marketing. It provides a business platform where web developers, designers, planners, and marketers can freely share information and share opinions. In addition, experts in each field directly share their experiences and know-how and suggest solutions to various problems.
Unlike the existing web development, design, and marketing businesses, webjangee.com provides an environment where beginners as well as experts can easily participate.
Through this site, we will share our professional knowledge and experience, and become a business platform that grows together in the web-related field.

* nemostory.net
nemostory.net is a web service that provides review videos and text contents on health, humanities, coffee, music, etc. It provides information on various genres of health, humanities, books, etc., and you can see detailed information and evaluations for each content. In addition, it provides a function for users to leave their own evaluation of the content.
nemostory.net also provides information about new brands and event information. This ensures that users are always informed about new brands.
Through this site, users can share knowledge and experiences, and experience new brands.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
Review videos and text contents such as health, humanities, coffee, music, etc. created in the nemostory.net project
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### How do you plan to prepare the dataset

lotus

### Please share a sample of the data

```text
https://nemostory.net/bbs/group.php?gr_id=health
https://www.youtube.com/@namroki/videos
https://www.youtube.com/@user-wb7wn4zt6b/videos
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

More than 3 years

### In which geographies do you plan on making storage deals

Asia other than Greater China, North America, Europe, Australia (continent)

### How will you be distributing your data to storage providers

Lotus built-in data transfer

### How do you plan to choose storage providers

Slack, Filmine

### How do you plan to make deals to your storage providers

Lotus client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
Could you send an email to filplus-app-review@fil.org with your official domain in order to confirm your identity? Email name should includes the issue id #1730.

**Comment by webjangee** [comment]
We have sent an email to the email address requested.

**Comment by Sunnyiscoming** [comment]
No email received. Can you provide screenshot?

**Comment by webjangee** [comment]
Email sending screenshot
<img width="808" alt="2023-03-09 13 11 03" src="https://user-images.githubusercontent.com/126127939/223907167-064038d6-af6d-4b4a-a1b5-d4c464b6d378.png">

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Looking at your application i have some questions:
As you are brand new on Github and have no history of past applications it seems to me that applying for 1PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?

Can you show us visible proof of the size of your data and the storage systems you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230337462961356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!

**Comment by webjangee** [comment]
Dear,
We will answer your questions.

* One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it
→ There are developers around us who will control the data related to Filecoin. (The developer is the developer who suggested to us how to use Filecoin.)

* Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?
→ We are new to Filecoin. (The developer mentioned above will help us with Filecoin development knowledge.)

* Can you show us visible proof of the size of your data and the storage systems you have there?
→ Most of the data we plan to store in Filecoin are the original and edited files of the video on the project page link and YouTube link listed on the application page.

* i would like you to fill out this form to provide us with the necessary information
→ Before filling out the form in the link you requested, I have a question.
   - Is KYC verification of the requested link required in order to apply for DataCap?
   - Curious about the above, We looked at the contents of other data cap application pages, and found that some applicants were requested for KYC and some applicants were not requested for KYC. We are curious about what criteria are you requesting for KYC verification?

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 1PiB

**Expected weekly DataCap usage rate**
> 10TiB

**Client address**
>f3wh5rfqafqp46a26cw7n76bszwxpammwonavamj4pqp3vytk6bktu27o4o2izbih37ttd3mpetyodovrfpopq

**Comment by cryptowhizzard** [comment]
|| Is KYC verification of the requested link required in order to apply for DataCap?
Curious about the above, We looked at the contents of other data cap application pages, and found that some applicants were requested for KYC and some applicants were not requested for KYC. We are curious about what criteria are you requesting for KYC verification?

Yes , KYC is mandatory. It will be implemented on short notice in the new onboarding system but for now notary's have to do that themselves.

**Comment by kevzak** [comment]
@webjangee what is the status of this application?

**Comment by kevzak** [comment]
is this public open dataset or your company data?
