### ISSUE TITLE
[DataCap Application] <Hepta> - <OpenNeuro>

### ISSUE THREAD

**Issue by yhkp** [filecoin-project/filecoin-plus-large-datasets#1731]
### Data Owner Name

Hepta

### Data Owner Country/Region

Korea, Republic of

### Data Owner Industry

Life Science / Healthcare

### Website

https://openneuro.org

### Social Media

```text
N/A
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

500TiB

### On-chain address for first allocation

f1opjqkoajys7fr4yajwcpj2bhuf4akh4s4ppdjwq

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Hepta Labs joined Filecoin as an SP starting in 2021. In order to comply with Filecoin's plan to store the most important data of humanity, we transformed our business. We have gone through the preparatory phase and contacted nearly 20 SPs. Most expressed willingness to collaborate on our important data storage plan.
I decided to bring OpenNeuro's public datasets to the network. OpenNeuro is a free and open platform for validating and sharing BIDS-compliant MRI, PET, MEG, EEG, and iEEG data.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
OpenNeuro is a free and open platform for validating and sharing BIDS-compliant MRI, PET, MEG, EEG, and iEEG data. Those four types data in total of 795 public datasets. All those data will be backup for 10x to different SPs.
```

### Where was the data currently stored in this dataset sourced from

Other

### If you answered "Other" in the previous question, enter the details here

```text
OpenNeuro
```

### How do you plan to prepare the dataset

IPFS, lotus, singularity

### Please share a sample of the data

```text
https://openneuro.org/datasets/ds004466/versions/1.0.0
https://openneuro.org/datasets/ds004299/versions/1.0.0
https://openneuro.org/datasets/ds002898/versions/1.3.1
https://openneuro.org/datasets/ds004078/versions/1.0.4
https://openneuro.org/datasets/ds004356/versions/1.0.0
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

1.5 to 2 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, Europe

### How will you be distributing your data to storage providers

Cloud storage (i.e. S3), HTTP or FTP server, IPFS, Shipping hard drives, Lotus built-in data transfer

### How do you plan to choose storage providers

Slack, Partners

### If you already have a list of storage providers to work with, fill out their names and provider IDs below

```text
f01225882 US
f01959735 US
f01854080 US
f01543586 HK
f02033219 HK
f01985611 US
f01579009 KR
f01386984 CN
f01690643 KR
f02012175 KR
f01402814 HK
f01893023 US
```

### How do you plan to make deals to your storage providers

Boost client, Lotus client, Singularity

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by yhkp** [comment]
![1](https://user-images.githubusercontent.com/121103586/223041702-afb2c86f-fffe-4fc7-93f4-99e67de2cd29.jpeg)
Here is the business license.

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 5PiB

**Expected weekly DataCap usage rate**
> 500TiB

**Client address**
>f1opjqkoajys7fr4yajwcpj2bhuf4akh4s4ppdjwq

**Comment by SuperChaiChai** [comment]
Associate in # 1693

I will pay attention to the future retrieval.

**Comment by SuperChaiChai** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebeac3u5joupll6sufapltr6tfnymkkgxj67xuwxue7sam3urdcu2 
#### Address 
> f1opjqkoajys7fr4yajwcpj2bhuf4akh4s4ppdjwq
#### Datacap Allocated
> 250.00TiB
#### Signer Address
> f12mckci3omexgzoeosjvstcfxfe4vqw7owdia3da
#### Id
> 7200acca-7d85-4def-b157-b3cfa46bbcde
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebeac3u5joupll6sufapltr6tfnymkkgxj67xuwxue7sam3urdcu2

**Comment by Bitrise0111** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebrv2f5nivpb7cfspn2rnbxlrfh2nokjvm4hwmps2k6z3bhbftjd6 
#### Address 
> f1opjqkoajys7fr4yajwcpj2bhuf4akh4s4ppdjwq
#### Datacap Allocated
> 250.00TiB
#### Signer Address
> f1nknj7ayq4o43czrtdoauggtwl43fbqatmqis3yy
#### Id
> 7200acca-7d85-4def-b157-b3cfa46bbcde
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebrv2f5nivpb7cfspn2rnbxlrfh2nokjvm4hwmps2k6z3bhbftjd6

**Comment by fireflyHZ** [comment]
checker:manualTrigger

**Comment by fireflyHZ** [comment]
@yhkp  same question as #1693

**Comment by yhkp** [comment]
Hi there, really appreciate your follow-up. @fireflyHZ
As the lead SP of our project, I feel sorry for this issue. We are cooperating with other SPs to ensure the data is stored in various regions. One of the sp has made some mistakes in daily operation, the Same as the other SP disclosed. I have talked with them, and I can assure you this mistake will not happen again.
Besides, for the data replicates, different SPs with different upload speeds. However, it will be normal in the end.
Looking forward your support!

**Comment by fireflyHZ** [comment]
Same as #1693 ,support this time.

**Comment by fireflyHZ** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaazx2zdsn2utihnxbfrjmvs2kk7t2a3kzlypubgh2gkkxjyk2cwi 
#### Address 
> f1opjqkoajys7fr4yajwcpj2bhuf4akh4s4ppdjwq
#### Datacap Allocated
> 500.00TiB
#### Signer Address
> f1fg6jkxsr3twfnyhdlatmq36xca6sshptscds7xa
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaazx2zdsn2utihnxbfrjmvs2kk7t2a3kzlypubgh2gkkxjyk2cwi

**Comment by sxxfuture-official** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceas3qrqpcbdvwvs6bmy3l2avgo6nu2ccknoaagdv24nn2nmzm72ke 
#### Address 
> f1opjqkoajys7fr4yajwcpj2bhuf4akh4s4ppdjwq
#### Datacap Allocated
> 500.00TiB
#### Signer Address
> f1foiomqlmoshpuxm6aie4xysffqezkjnokgwcecq
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceas3qrqpcbdvwvs6bmy3l2avgo6nu2ccknoaagdv24nn2nmzm72ke

**Comment by kernelogic** [comment]
checker:manualTrigger

**Comment by kernelogic** [comment]
CID report looks good. CID sharing is minimal and explained above.

**Comment by kernelogic** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedmescot4msha7cuqbmgrdevmuibsoa5biyn5yj5prdq6lal5diuo 
#### Address 
> f1opjqkoajys7fr4yajwcpj2bhuf4akh4s4ppdjwq
#### Datacap Allocated
> 1000.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### Id
> 3e0a758b-f234-41c0-82d4-9f7303ffbb3e
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedmescot4msha7cuqbmgrdevmuibsoa5biyn5yj5prdq6lal5diuo

**Comment by laurarenpanda** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedqbn2a2asiv4rwl6yzufaesijyl45qipc7wyuqvxof2xwucpjdlu 
#### Address 
> f1opjqkoajys7fr4yajwcpj2bhuf4akh4s4ppdjwq
#### Datacap Allocated
> 1000.00TiB
#### Signer Address
> f1bp3tzp536edm7dodldceekzbsx7zcy7hdfg6uzq
#### Id
> 3e0a758b-f234-41c0-82d4-9f7303ffbb3e
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedqbn2a2asiv4rwl6yzufaesijyl45qipc7wyuqvxof2xwucpjdlu

**Comment by kevzak** [comment]
checker:manualTrigger

**Comment by kevzak** [comment]
checker:manualTrigger

**Comment by kevzak** [comment]
Hi @yhkp you are lead SP, correct? Where are you located? Can you explain data storage report? 74% with one SP in USA. Is that VPN? What is plan to spread more geographically?

**Comment by kevzak** [comment]
Also we have a new, optional KYC ID check available on [filplus.storage](https://filplus.storage/). If you want to add addtional layer of trust you can complete ID check. [LINK](https://medium.com/filecoin-plus/implementation-of-a-third-party-kyc-id-check-for-fil-applicants-e5e825b1484e)

**Comment by yhkp** [comment]
checker:manualTrigger

**Comment by yhkp** [comment]
checker:manualTrigger

**Comment by spaceT9** [comment]
checker:manualTrigger

**Comment by spaceT9** [comment]
Please increase the retrieval rate before next tranche. And also increase the number of copy to make it more decentralized.

**Comment by clriesco** [comment]
Removed stale label and reopened issue :)
