### ISSUE TITLE
[DataCap Application] <Paris Spring wedding dress image>

### ISSUE THREAD

**Issue by Paris-Spring** [filecoin-project/filecoin-plus-large-datasets#1732]
### Data Owner Name

Paris Spring wedding dress image

### Data Owner Country/Region

China

### Data Owner Industry

Other

### Website

http://www.blct.vip/

### Social Media

```text
Douyin(Tik Tok) ID:29382995094
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

300TiB

### On-chain address for first allocation

f153ggxyuwhmlyteki2j3zn4fxkz3ypebsdt5tpga

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
1. Paris Spring Imaging Group has been established since 2007, has gone through 16 years of spring and autumn, and has become a leading brand in Hubei - Supervalu wedding photography industry. Adhere to the "will tell the story of the wedding photos" as the shooting concept, for four consecutive years to obtain the scale, reputation, reputation, professionalism, the most beautiful photography brand title of Supervalu. The industry inside and outside the cooperation of technical experts, technical staff experience of more than 10 years, shooting footprints across the country.
2, in order to combine market demand, our store in 2016, the launch of a new children's theme photography brand love you baby children photography. The largest local children's photography business, covering an area of 600 square meters, dedicated to baby photography services, the first to start the theme photo shooting and theme creation, the first to launch a combination of dynamic and static photography services for infants and toddlers, the first full live-action shooting, the first to launch a newborn baby hospital field shooting children's photography agency, the existing membership has reached more than 10,000 people.

3.2022 brand upgrade, now has three local directly managed stores. The area of 1300 square meters, providing wedding photography, children photography, wedding, family portraits, parent-child photography, pregnant mother photography, location photography, advertising photography, large events on-site photography and videography and children's magazine cover shooting services.

4、4. Corporate Honors
In 2014, we won the second prize of the group in the second "Winning Action".
In 2016, the introduction of the Shanghai International Photography Exhibition "children shooting theme"
In 2016, Paris Spring Wedding Gallery signed a contract with [Jingzhou Orange Film Base].
In 2017 Paris Spring Wedding Pavilion signed a contract [Wuhan Lavender Manor] location
2020 Paris Spring Wedding Pavilion signed a [global travel shooting] platform
2022 Establishment of wedding planning consultant, wedding dress rental and sale, site decoration, wedding car rental, etc.
In 2022, after 6 years of love you baby brand upgrade again, directly operated 3 stores. New independent constant temperature studio, independent constant temperature makeup room.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
The data stored on Filecoin includes the following: wedding video, wedding documentary photos, personal portraits, family photos, children's photos, interior and exterior wedding photos
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### How do you plan to prepare the dataset

lotus

### Please share a sample of the data

```text
https://drive.google.com/drive/folders/1z43kSUtnSe3YAZhl7EnYUrZMxqK1EzEd
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [x] I confirm

### What is the expected retrieval frequency for this data

Sporadic

### For how long do you plan to keep this dataset stored on Filecoin

More than 3 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, Europe

### How will you be distributing your data to storage providers

HTTP or FTP server, Shipping hard drives

### How do you plan to choose storage providers

Slack, Big data exchange, Partners

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
The applied dataset contains many portraits. Do you have any authorization file for storing as public data?

**Comment by Paris-Spring** [comment]
> 应用的数据集包含许多人像。您是否有存储为公共数据的授权文件？



> The applied dataset contains many portraits. Do you have any authorization file for storing as public data?

Hello, the data we store is with the consent of the customer (a beautiful moment that the customer agrees to leave in the store for display) and is not for profit.

**Comment by Sunnyiscoming** [comment]
Every country has portrait protection laws, so more materials are required for such sensitive data.

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 5PiB

**Expected weekly DataCap usage rate**
> 300TiB

**Client address**
>f153ggxyuwhmlyteki2j3zn4fxkz3ypebsdt5tpga

**Comment by Sunnyiscoming** [comment]
Please confirm whether there is any problem of data usage right before approval.

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Looking at your application i have some questions:
As you are brand new on Github and have no history of past applications it seems to me that applying for 5PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?

Can you show us visible proof of the size of your data and the storage systems you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230337462961356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!

**Comment by Paris-Spring** [comment]
Thank you for your question. Please check the screenshot of our data. Thank you

![WechatIMG186](https://user-images.githubusercontent.com/126555613/224968415-e4001a98-cf6c-479b-ac77-7fe4c22764fb.png)
![WechatIMG187](https://user-images.githubusercontent.com/126555613/224968424-3b9dfe71-5c2a-48ea-b7a4-9150a9e28754.png)
![WechatIMG188](https://user-images.githubusercontent.com/126555613/224968431-556e35de-0249-4008-8081-c7e19713e7b9.png)
![WechatIMG189](https://user-images.githubusercontent.com/126555613/224968440-b5d619a5-8fd3-4f6d-a860-fb7e6af0d41a.jpeg)
![WechatIMG190](https://user-images.githubusercontent.com/126555613/224968458-50a6024f-c992-49b3-8578-8721d0500170.jpeg)
![WechatIMG191](https://user-images.githubusercontent.com/126555613/224968464-a1a52324-67f6-43a2-afa7-dec98f7878b5.jpeg)
![WechatIMG192](https://user-images.githubusercontent.com/126555613/224968469-84572997-e0bb-4aa9-aa97-b56b4b2b9b6f.jpeg)

**Comment by Paris-Spring** [comment]
> Dear applicant,
> 
> Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.
> 
> Looking at your application i have some questions: As you are brand new on Github and have no history of past applications it seems to me that applying for 5PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?
> 
> Can you show us visible proof of the size of your data and the storage systems you have there?
> 
> As last question i would like you to fill out [this form](https://form.jotform.com/230337462961356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.
> 
> Thanks!

Thank you for your question. Please check the screenshot of our data. Thank you
![WechatIMG192](https://user-images.githubusercontent.com/126555613/224970826-1c08deeb-eb54-4e3a-a446-7c4c20c5e9c3.jpeg)
![WechatIMG186](https://user-images.githubusercontent.com/126555613/224970837-a099a6d8-bd2d-4d85-bd10-d277024c9d64.png)
![WechatIMG187](https://user-images.githubusercontent.com/126555613/224970856-4ccced5a-ee70-447a-a096-8d6c75e17df3.png)
![WechatIMG188](https://user-images.githubusercontent.com/126555613/224970869-a523b0df-f59c-44af-995b-2829e7b7e667.png)
![WechatIMG189](https://user-images.githubusercontent.com/126555613/224970885-f3360da7-4753-475d-a8d8-9208f9718fa6.jpeg)
![WechatIMG190](https://user-images.githubusercontent.com/126555613/224970903-27f158f6-8cd4-4e36-bb28-17e0dc9393d0.jpeg)
![WechatIMG191 下午6 13 12](https://user-images.githubusercontent.com/126555613/224970915-6248ae59-93be-4cc5-83ee-92f1bcc54ba4.jpeg)

**Comment by cryptowhizzard** [comment]
> Dear applicant,
> 
> Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.
> 
> Looking at your application i have some questions: As you are brand new on Github and have no history of past applications it seems to me that applying for 5PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?
> 
> Can you show us visible proof of the size of your data and the storage systems you have there?
> 
> As last question i would like you to fill out [this form](https://form.jotform.com/230337462961356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.
> 
> Thanks!

Reminder

**Comment by Paris-Spring** [comment]
> > Dear applicant,
> > Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.
> > Looking at your application i have some questions: As you are brand new on Github and have no history of past applications it seems to me that applying for 5PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?
> > Can you show us visible proof of the size of your data and the storage systems you have there?
> > As last question i would like you to fill out [this form](https://form.jotform.com/230337462961356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.
> > Thanks!
> 
> Reminder

We are currently in contact with the following SPs communication information, of course, we will continue to communicate with more SPs:

Greaterheat——f01985775、f01988794——Dallas, USA

SXX Future——f01986229——Hubei,China
SXX Future——f01964215——Guangdong,China

Cabrina——f039940——Sichuan,China

We will also continue to hang orders on the BDE to diversify the SPs. But recently the platform is being adjusted. @cryptowhizzard

**Comment by cryptowhizzard** [comment]
@Paris-Spring 

https://github.com/filecoin-project/notary-governance/issues/833

KYC is mandatory. Please fill out the form.

**Comment by Paris-Spring** [comment]
> @Paris-Spring
> 
> notary-governance/issues/833
> 
> KYC is mandatory. Please fill out the form.

Hi The KYC form has been submitted

**Comment by Paris-Spring** [comment]
@cryptowhizzard 
Our KYC has been submitted. Could you please support our application.

**Comment by liyunzhi-666** [comment]
Could you send an email to filplus-app-review@fil.org with your official domain in order to confirm your identity? Email name should includes the issue id.
It is best to include your company's business license.

**Comment by Paris-Spring** [comment]
> Could you send an email to [filplus-app-review@fil.org](mailto:filplus-app-review@fil.org) with your official domain in order to confirm your identity? Email name should includes the issue id. It is best to include your company's business license.

Hello, I have already sent an email regarding identity verification.

**Comment by Paris-Spring** [comment]
> > Could you send an email to [filplus-app-review@fil.org](mailto:filplus-app-review@fil.org) with your official domain in order to confirm your identity? Email name should includes the issue id. It is best to include your company's business license.
> 
> Hello, I have already sent an email regarding identity verification.

![image](https://user-images.githubusercontent.com/126555613/226862140-df15fbb5-e0d5-49d1-b0be-c809c5bfb230.png)

Hello, this is a screenshot of the email.

**Comment by liyunzhi-666** [comment]
Based on the comments in the issue and the communication from the client, I am willing to support the first round and continuously monitor the subsequent allocation.

**Comment by liyunzhi-666** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecq2c2ntopc34tczi4dm4snsef6uy7tvofph5ceuzmvozqoaw6n3q 
#### Address 
> f153ggxyuwhmlyteki2j3zn4fxkz3ypebsdt5tpga
#### Datacap Allocated
> 150.00TiB
#### Signer Address
> f1pszcrsciyixyuxxukkvtazcokexbn54amf7gvoq
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecq2c2ntopc34tczi4dm4snsef6uy7tvofph5ceuzmvozqoaw6n3q

**Comment by zcfil** [comment]
After reading history, I have some questions：

Can you show more data？
Is your data publicly available？

**Comment by cryptowhizzard** [comment]
> > @Paris-Spring
> > notary-governance/issues/833
> > KYC is mandatory. Please fill out the form.
> 
> Hi The KYC form has been submitted

We did not receive your reply. Can you re-submit please. I will track it and put it in my agenda for monday.

**Comment by Normalnoise** [comment]
@Paris-Spring how much dataset have you prepared? can you provide the dat size proof?

**Comment by Paris-Spring** [comment]
> 

Hello, thank you for your question and sorry for replying only now.
We have more than at least 1PiB or more datasets and new data will be generated continuously. I replied to the data sample in the previous comment and the link to the Google Cloud Drive for the data sample is also above, so you can check it out sometime, thanks.

**Comment by Normalnoise** [comment]
I am willing to support you in this round

**Comment by kevzak** [comment]
hello @Paris-Spring we have a new, optional KYC ID check available on [filplus.storage](https://filplus.storage/). If you want to add addtional layer of trust you can complete ID check. See details: [LINK](https://medium.com/filecoin-plus/implementation-of-a-third-party-kyc-id-check-for-fil-applicants-e5e825b1484e)

**Comment by kevzak** [comment]
@Paris-Spring is this application still active?
You are lead DataOwner or SP? Where are you located?
Who is preparing the Data?
Where did you find SPs for the project?

**Comment by Paris-Spring** [comment]
1. My application is still in progress, but previously a signature bug prevented another notary from signing, the issue is now resolved and we will move forward. Screenshots are below:

![20230727-145935](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/126555613/a79ee780-83df-4306-8c87-c51bc04cef49)

3.We are the data owner and the location is in China.

4. we found the SPs through slack, and github.

**Comment by Paris-Spring** [comment]
@kevzak

**Comment by Paris-Spring** [comment]
checker:manualTrigger

**Comment by NiwanDao** [comment]
checker:manualTrigger

**Comment by NewHuoPool** [comment]
Are all the collaborating SPs finalized?

**Comment by zcfil** [comment]
Please list the SPs you are pre-collaborating with and the regions.

**Comment by Paris-Spring** [comment]
Hello, the current communication SPs are as follows, we are looking for more SPs to cooperate, thank you for your attention!

f0861588  USA
f02212982  shenzhen,China
f02105377  Hong Kong
f01986229  Hubei,China

**Comment by zcfil** [comment]
f01986229 seems to have failed query ask. Are you sure these nodes all support retrieval?

**Comment by cryptowhizzard** [comment]
According to the retrieval bot only f0861588 supports retrieval.

![Scherm­afbeelding 2023-09-05 om 14 33 44](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/36404435/bed4d9df-7711-40e7-bc20-464d4f35498e)
![Scherm­afbeelding 2023-09-05 om 14 33 27](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/36404435/3870f1a2-6722-4f43-811c-06f7aa8d5de1)
![Scherm­afbeelding 2023-09-05 om 14 33 09](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/36404435/bc44f810-86ee-4a2f-b54c-41b09ca6c954)

**Comment by Paris-Spring** [comment]
checker:manualTrigger

**Comment by cryptowhizzard** [comment]
> We asked SPs, and SPs feedback told us retrieval was possible, and we're matching up with more SPs, but of course we can't rule out the fact that the first round of encapsulation ended up with other SPs.
> 
> f0861588 USA (support for retrieval) f02105377 Hong Kong (support search) f01986229 Hubei, China (can retrieve, but unstable, often timeout) f0861589 USA (support search)

So, you are saying that the retrieval bot made by protocol labs is wrong?

https://retrievalbot-dashboard.vercel.app/

Of course you can't rule out that planes fall out of the sky and the moon goes in the wrong direction tomorrow, however let's keep things clear and tidy in here please. Before starting here either have the retrieval bot show decent results or select others and provide use with their details please.

<img width="1564" alt="Scherm­afbeelding 2023-09-17 om 17 51 39" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/36404435/5690d599-3c48-4b04-9d2d-0be5821a5d9c">
<img width="1529" alt="Scherm­afbeelding 2023-09-17 om 17 51 27" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/36404435/b1531cb6-0fb7-4d43-b462-7d243fb1335a">
<img width="1575" alt="Scherm­afbeelding 2023-09-17 om 17 51 14" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/36404435/a7d672cd-5585-4719-9c1c-73554049eae3">
<img width="1445" alt="Scherm­afbeelding 2023-09-17 om 17 50 55" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/36404435/927dd6e4-3543-401c-bfc1-e16d439dfb24">

**Comment by Paris-Spring** [comment]
Please check your browser screenshot. See below for details:

<img width="1438" alt="66438422609fccf6420406932c51b50" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/126555613/646bebf2-809f-4278-98dd-1f77127fa618">
<img width="1439" alt="133352ef14f66b6e7f1ce74080bf61b" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/126555613/3209efec-fdf2-424b-bef0-21e2fe395f84">
![03bbdc97f84032dd37e6a2d80846c1b](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/126555613/03b9e604-8953-4b51-ae70-10d32bfe2af2)

We are also in further communication with the new SP f02812314 (USA).

**Comment by Paris-Spring** [comment]
![1234565](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/126555613/c2f1b71f-689d-43a7-ac88-4dd24e5a717e)

**Comment by Paris-Spring** [comment]
Ongoing！

**Comment by Paris-Spring** [comment]
checker:manualTrigger

**Comment by Paris-Spring** [comment]
checker:manualTrigger

**Comment by Paris-Spring** [comment]
checker:manualTrigger

**Comment by Paris-Spring** [comment]
checker:manualTrigger

**Comment by Paris-Spring** [comment]
checker:manualTrigger

**Comment by web3woker0001** [comment]
checker:manualTrigger

**Comment by woshidama323** [comment]
Will support this first stage of LDN 
Good Luck

**Comment by woshidama323** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb5vitaobnje6lly6zbmbhqdm46hxjtzykn5iupnflux7gzhy4z7q 
#### Address 
> f153ggxyuwhmlyteki2j3zn4fxkz3ypebsdt5tpga
#### Datacap Allocated
> 150.00TiB
#### Signer Address
> f12tk3adljauwnd3hjbigpfxb7b7gdlj63p6afwtq
#### Id
> 3f2de135-fc50-4763-8896-391f75d64498
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb5vitaobnje6lly6zbmbhqdm46hxjtzykn5iupnflux7gzhy4z7q

**Comment by Paris-Spring** [comment]
checker:manualTrigger

**Comment by Paris-Spring** [comment]
Before sealing, the SPs information is updated again to comply with the rules:

f02814767 XHS 1504068285@qq.com South Korea
f02815448 bluesky danacheng2021@gmail.com USA
f02815438 MaiJie nibuil0730@163.com India

**Comment by herrehesse** [comment]
checker:manualTrigger

**Comment by Filplus-govteam** [comment]
closing until clear SP entity and distribution are provided

**Comment by Paris-Spring** [comment]
> Hello, @Paris-Spring per the [filecoin-project/notary-governance#922](https://github.com/filecoin-project/notary-governance/issues/922) for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.
> 
> This information will be reviewed by Fil+ Governance team to confirm validity and then the application will be allowed to move forward for additional notary review.

Hello,@Sunnyiscoming      a reply has been submitted.

**Comment by Filplus-govteam** [comment]
checker:manualTrigger

**Comment by Paris-Spring** [comment]
Hello, @Sunnyiscoming 
have you received the "https://form.jotform.com/231862753015656" form information we submitted?

**Comment by Filplus-govteam** [comment]
SPs provided
SP 1	f02309112	Eighteen	Kudian Tec	Changsha, Hunan, CN	NO	@Eighteen
SP 2	f01964215	Jintao	SXX Future	Shenzhen, CN	NO	@Jintao-Sxxfutre
SP 3	f01986236	Caicai	ChenXing	Los Angeles, US	NO	@caicai
SP 4	f01876488	Alex	          BitEngine	Singapore, SG	NO	@BGalex
SP 5	f02129771	Eighteen		Kudian Tec	Changsha, Hunan, CN	NO	@Eighteen


This is the list @Paris-Spring ?

**Comment by Filplus-govteam** [comment]
checker:manualTrigger

**Comment by Paris-Spring** [comment]
No, the latest SP list we provide is this:
f02814767 XHS 1504068285@qq.com South Korea

f02815448 bluesky danacheng2021@gmail.com USA

f02815438 MaiJie nibuil0730@163.com India

f02814775 Derek Cui zdderek@qq.com Haarlem, North Holland, NL

f02815451 HZZC nibuil0730@163.com Canada

@Filplus-govteam

**Comment by Filplus-govteam** [comment]
emails sent

**Comment by Filplus-govteam** [comment]
@Paris-Spring we've not received emails or proof of location distribution. 

We ask that you collect the necessary entity and location information from your SPs and send to filplus.govteam@gmail.com

**Comment by Paris-Spring** [comment]
Hello，@Filplus-govteam 
SPs told me that the email has been sent, please check it, thanks. I hope to restart LDN soon.

**Comment by Filplus-govteam** [comment]
We replied to SPs asking for more proof. Name, location on a bill for example. Not just an email reply.

Awaiting reply
