### ISSUE TITLE
[DataCap Application]Shenyang Hesiding Education Technology Co., Ltd

### ISSUE THREAD

**Issue by pandola0908** [filecoin-project/filecoin-plus-large-datasets#174]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Shenyang Hesiding Education Technology Co., Ltd
- Website / Social Media:https://mp.weixin.qq.com/mp/homepage?__biz=Mzg2MTUzMzczNQ==&hid=3&sn=d78e3d777d
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 200TiB
- On-chain address for first allocation: f1um6fija6du5sovbmko4uqfuj6dtbzmmpoqwl24i

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Founded in 2014, Hesiding brand has always been committed to providing more convenient and efficient integrated family and school education support for middle school students and primary school students. With the business philosophy of "focusing on supporting and worthy of trust", Hesiding brand has provided educational solutions for countless families. A multi-faceted growth exploration curriculum system has been exported to 51 school districts across the country, so that children not only have a thinking mode of in-depth exploration of knowledge, but also improve the quality of comprehensive application of knowledge.

After six years of development and accumulation, Hesiding brand has been deeply involved in the field of supporting education in China, and innovatively combines quality education with after-school accompanying learning.It also absorbed excellent educational talents, formed a strong faculty team , and developed an industry featuring leading exclusive teaching materials and a scientific and characteristic curriculum system.
```

What is the primary source of funding for this project?
```
Income from teaching programs and investment from investors.
```

What other projects/ecosystem stakeholders is this project associated with?
```
No.
```

## Use-case details

Describe the data being stored onto Filecoin
```
Shenyang Hesiding Education Technology Co., Ltd generates a large amount of data including poster materials, event materials and video materials in the process of preparing for enrollment promotion, event planning, online or offline teaching and many other work contents.These data are open source and will not cause disputes.The data is mainly in the form of text, video and pictures. We believe and hope that these data can be safely stored in Filecoin.
```

Where was the data in this dataset sourced from?
```
Publicly available and searchable data generated by the company during activities and teaching.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
Link：https://pan.baidu.com/s/1kJCch3fbYWgNg15QAibWRA 
Extraction code：D95T
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Open the link and you can see that there is no specific permission.
```

What is the expected retrieval frequency for this data?
```
Anyone interested can view it.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
Three and a half years.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Asia.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Online or Offline deal are OK.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
Any miner who wants to do distributed storage can.
```

How will you be distributing deals across storage providers?
```
Equally distributed.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
There are sufficient resources and funds.
```

**Comment by dkkapur** [comment]
@pandola0908 for your DataCap allocation plan, can you add a few more details on this? 

- do you have specific countries in which you want to ensure replicas of the data are available?
- do you have a target number of storage providers in mind already? 
- how do you plan on finding storage providers?

**Comment by IPFSUnion** [comment]
Could you share your public website and the link of your dataset which we can download freely?

**Comment by pandola0908** [comment]
> Could you share your public website and the link of your dataset which we can download freely?
@IPFSUnion 
Of course, there is our link above:Link：
https://pan.baidu.com/s/1kJCch3fbYWgNg15QAibWRA 
Extraction code：D95T
And you can download freely.

**Comment by galen-mcandrew** [comment]
Hello! Looks like this link may have expired for the sample data. Can you please provide an updated link?

**Comment by dkkapur** [comment]
@pandola0908 closing this one out for now since we didn't get a response to the sample sharing request! please feel free to re-open this if it is still relevant and you can share updated information. thank you!
