### ISSUE TITLE
[DataCap Application] Huachu Cloud Storage Technology Co., LTD

### ISSUE THREAD

**Issue by licornduan** [filecoin-project/filecoin-plus-large-datasets#1745]
### Data Owner Name

Huachu Cloud Storage Technology Co., LTD

### Data Owner Country/Region

China

### Data Owner Industry

IT & Technology Services

### Website

pan.ipfshuzy.com

### Social Media

```text
www.ipfshczy.com
```

### Total amount of DataCap being requested

1PiB

### Weekly allocation of DataCap requested

10TiB

### On-chain address for first allocation

f1lzseynoswqw5zahhpkmrbymu5pm54wyklgaixsq

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Founded in February 2014, Huachu Zhiyun (Beijing) Technology Service Co., Ltd. is headquartered in Zhongguancun Science and Technology Innovation Park (No. 38 Zhongguancun Street), Beijing, Capital of China. Provide reliable cloud disk services for web3 media and online education groups

huachu enterprise cloud disk  is one of several products of huachu cloud storage.  huachu provides our users with an unlimited number of file sharing services, which are mainly used for enterprise/individual collaborative work scenarios.
```

### Is this project associated with other projects/ecosystem stakeholders?

Yes

### Describe the data being stored onto Filecoin

```text
In huachu enterprise cloud disk, customers will create a large amount of content information in pdf/word, xmind/visio, videos, recording, whiteboard pictures, work and life photos, etc. 
huachu should help customers store these original content. We expect a huge amount of storage demand in the future, so we have been looking for safe, reliable and affordable storage service providers. 
IPFS & Filecoin is our best choice now.
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### If you answered "other/custom tool" in the previous question, enter the details here

```text
online & off-line.
```

### Please share a sample of the data

```text
lotus client retrieve --provider  f0508892 bafyreihjakbu5zefc23gsd6swhavmnop424pf4z2hgrde4gqd5y3yhyj34 ./file.pan

lotus client retrieve --provider f0508892  bafykbzacecxrfwk5q2n5qu3qnnnop23m6tiito7jat3kafdme4xl7mjaehd3w ./file2.pan
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [ ] I confirm

### What is the expected retrieval frequency for this data

Weekly

### For how long do you plan to keep this dataset stored on Filecoin

1 to 1.5 years

### In which geographies do you plan on making storage deals

Greater China

### How will you be distributing your data to storage providers

HTTP or FTP server

### How do you plan to choose storage providers

Partners

### If you already have a list of storage providers to work with, fill out their names and provider IDs below

```text
owner f081988
partner 
f023219
f0500878
f20489
f0157265
```

### How do you plan to make deals to your storage providers

Boost client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
@licornduan Can you provide more data samples?
Could you send an email to filplus-app-review@fil.org with your official domain in order to confirm your identity? Email name should includes the issue id #1745.

**Comment by caoyoungyoung** [comment]
the website is unavailable, please double-check

**Comment by licornduan** [comment]
bafykbzacecdukvv2mj3bvuapkbe3kkgz6xkoxt6at7hkt2g4t5mauvx4ku73a
bafykbzaceadina37okk52fff2362naku7liofvkfrxjc3uxmslwydqnxw4wbs
bafykbzacecdmcyqjcmm3qncz7lowksflw6szbst2hj4lezygghgerhd5kfdr2
bafykbzacebi65ufibhae3bphrrggyd4s3xk6wh4raqdohkckh35vl77do3pmc
bafykbzacecxrfwk5q2n5qu3qnnnop23m6tiito7jat3kafdme4xl7mjaehd3w
bafykbzacedzq662xbwoxt2ljbl5dsec22osyazepptcq4dajm3z67szutzlpa
bafykbzacecxrfwk5q2n5qu3qnnnop23m6tiito7jat3kafdme4xl7mjaehd3w
bafykbzacebxhqrjjyo2ygynpmk23xyoicevwqlbyptlwwt4djb62ghxqnubgq
bafykbzacebtbox64phdhthmw3vws4cdzenmsujqvdpaobcui4k3zsb22eaunu


I have sent an email to your designated mailbox, please check it.@Sunnyiscoming 

The domain name provided is accessible, but I'm not sure if it's internationally accessible. You can access the SP I provided and the partner nodes I will cooperate with, and you can also get the data.  @caoyoungyoung

**Comment by caoyoungyoung** [comment]
![image](https://user-images.githubusercontent.com/113870610/224239204-d895b5a3-4ab3-4ade-8b51-1cbdcdb2a48f.png)
How come the kyc website shows the company is deregistered?

**Comment by licornduan** [comment]
Fil's continued downturn led to the bankruptcy of the main body. In order to guarantee the rights and interests of the original platform users, the platform data hosting and migration, the original investors are also trying to restore the recovery of the entity, all the technical architecture implementation is based on IPFS storage framework.

**Comment by licornduan** [comment]
@caoyoungyoung

**Comment by Sunnyiscoming** [comment]
Without the subject, data ownership is no longer in the enterprise. It is recommended to close this application.

**Comment by licornduan** [comment]
Wait until the client has dealt with the main issue
