### ISSUE TITLE
Dcent - Help Ukraine miners part 3

### ISSUE THREAD

**Issue by cryptowhizzard** [filecoin-project/filecoin-plus-large-datasets#1746]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Dcent network
- Website / Social Media: www.dcent.nl
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5 PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 300 TiB
- On-chain address for first allocation: f15cps7yo2x4fosvp45opfihk3a4wg2qukmwyet7a

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Speedium / Dcent has engaged in Slingshot starting 2.6. We have successfully stored more than 15 different datasets with 20+ different miners.
```

What is the primary source of funding for this project?
```
Company account
```

What other projects/ecosystem stakeholders is this project associated with?
```
None.
```

## Use-case details

Describe the data being stored onto Filecoin
```
We have been contacted by miners from Ukraine to help them make a backup of their data in case anything happens given the situation in their country. The data will consists of sectors of the miners involved. The batch will be 500 TB we intend and we intend to spread it over 4 to 6 SP's.

This issue is a followup to issue #348. 

Set 1 contais 400 TB of sectors and cache data. We have packed it and uploaded it. In the mean time we received another 400 TiB of data for this LDN.

```
Where was the data in this dataset sourced from?
```
The miners uploaded it towards us.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
Yes, but we prefer to keep that private until uploaded for security reasons.
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes.
```

What is the expected retrieval frequency for this data?
```
Just a few times for checking but we hope that it won't be necessary  offcourse.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
18 months or longer
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
EU / China / US / Australia.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
The data will be transferred both offline and online.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We have a few providers who have been working with us during Slingshot Restore program and we'd like to continue working with them for ongoing Slingshot competition.
```

How will you be distributing deals across storage providers?
```
Max 2 copy's per storage provider if stored on different miners / locations.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, we have the resources.
```

**Comment by simonkim0515** [comment]
## Datacap Request Trigger

#### Total DataCap requested 
> 5PiB

#### Expected weekly DataCap usage rate 
> 300TiB 

#### Client address
> f15cps7yo2x4fosvp45opfihk3a4wg2qukmwyet7a

**Comment by s0nik42** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceciucwf7cvozvphfm7fvehgvsougs5k2bnkbcw3ex3mehu37jf3i6 
#### Address 
> f15cps7yo2x4fosvp45opfihk3a4wg2qukmwyet7a
#### Datacap Allocated
> 150.00TiB
#### Signer Address
> f1wxhnytjmklj2czezaqcfl7eb4nkgmaxysnegwii
#### Id
> 3ec06ea0-dd5e-4aec-8432-c3d62ad1d7b5
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceciucwf7cvozvphfm7fvehgvsougs5k2bnkbcw3ex3mehu37jf3i6

**Comment by kernelogic** [comment]
Continuation from old series. Willing to support.

**Comment by kernelogic** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebaawl7tmmdb5uqmbstwpnp42x7kui3fm2whygfkebscaz6nkfous 
#### Address 
> f15cps7yo2x4fosvp45opfihk3a4wg2qukmwyet7a
#### Datacap Allocated
> 150.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### Id
> 3ec06ea0-dd5e-4aec-8432-c3d62ad1d7b5
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebaawl7tmmdb5uqmbstwpnp42x7kui3fm2whygfkebscaz6nkfous

**Comment by daniel2022nnn** [comment]
a LDN with no sample can pass the review becasue it is dcent?

@kernelogic @s0nik42 

and  CID sharing? @cryptowhizzard can you explain?

**Comment by psh0691** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedspl3dhc6mixsm2d35ugur2ji5ksrrqp72dt2hqzja3qveuhzvty 
#### Address 
> f15cps7yo2x4fosvp45opfihk3a4wg2qukmwyet7a
#### Datacap Allocated
> 300.00TiB
#### Signer Address
> f1qdko4jg25vo35qmyvcrw4ak4fmuu3f5rif2kc7i
#### Id
> d7340be2-3ca3-4e72-b479-690185742562
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedspl3dhc6mixsm2d35ugur2ji5ksrrqp72dt2hqzja3qveuhzvty

**Comment by flyworker** [comment]
refer to https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/540 for sign

**Comment by flyworker** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedrjoxkqaxbn7257mbn5gq6joov4gl6cnzk25ly4rjokjrhm7zlm2 
#### Address 
> f15cps7yo2x4fosvp45opfihk3a4wg2qukmwyet7a
#### Datacap Allocated
> 300.00TiB
#### Signer Address
> f1hlubjsdkv4wmsdadihloxgwrz3j3ernf6i3cbpy
#### Id
> d7340be2-3ca3-4e72-b479-690185742562
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedrjoxkqaxbn7257mbn5gq6joov4gl6cnzk25ly4rjokjrhm7zlm2

**Comment by kevzak** [comment]
checker:manualTrigger

**Comment by data-programs** [comment]
<img width="32" alt="KYC" Verified src="https://stable.filplus.storage/images/filplus-kyc-verified-badge.png"/>

This user’s identity has been verified through [filplus.storage](https://filplus.storage)
