### ISSUE TITLE
[DataCap Application] Transiting Exoplanet Survey Satellite (TESS)

### ISSUE THREAD

**Issue by avavanDam** [filecoin-project/filecoin-plus-large-datasets#1747]
### Data Owner Name

Space Telescope Science Institute

### Data Owner Country/Region

United States

### Data Owner Industry

Environment

### Website

https://www.stsci.edu/

### Social Media

```text
https://www.facebook.com/stsci/
https://twitter.com/spacetelescope
https://registry.opendata.aws/collab/stsci/
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

400TiB

### On-chain address for first allocation

f1eotkofs3ywuqskq5un67hgnpyoznvlvhcqomukq

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Established in 1981, STSCI has helped guide the most famous observatory in history, the Hubble Space Telescope. Since its launch in 1990, we have performed the science operations for Hubble. We also lead the science and mission operations for the James Webb Space Telescope (JWST), which launched on December 25, 2021. We will perform parts of the science operations for the Nancy Grace Roman Space Telescope, in formulation for launch in late 2026, and we are partners on several other NASA missions. Our staff conducts world-class scientific research; our Barbara A. Mikulski Archive for Space Telescopes (MAST) curates and disseminates data from over 20 astronomical missions; and we bring science to the world through internationally recognized news, education, and public outreach programs. We value our diverse workforce and civility in the workplace, and seek to be an example for others to follow.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
The Transiting Exoplanet Survey Satellite (TESS) is a multi-year survey that will discover exoplanets in orbit around bright stars across the entire sky using high-precision photometry. The survey will also enable a wide variety of stellar astrophysics, solar system science, and extragalactic variability studies.
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### How do you plan to prepare the dataset

lotus, singularity

### Please share a sample of the data

```text
https://registry.opendata.aws/tess/
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

1.5 to 2 years

### In which geographies do you plan on making storage deals

Asia other than Greater China, North America, Europe

### How will you be distributing your data to storage providers

HTTP or FTP server, Shipping hard drives

### How do you plan to choose storage providers

Slack, Filmine, Big data exchange

### How do you plan to make deals to your storage providers

Boost client, Lotus client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 5PiB

**Expected weekly DataCap usage rate**
> 400TiB

**Client address**
>f1eotkofs3ywuqskq5un67hgnpyoznvlvhcqomukq

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Looking at your application i have some questions:
As you are brand new on Github and have no history of past applications it seems to me that applying for 5PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?

Can you show us visible proof of the size of your data and the storage systems you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230337462961356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!

**Comment by TimGuo7** [comment]
check and happy to support

**Comment by TimGuo7** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaxx5uxbn45jtztdnm2daon3y4deglodeuzlvlwmw5kfjligkjk4q 
#### Address 
> f1eotkofs3ywuqskq5un67hgnpyoznvlvhcqomukq
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1yslbnnqzrjlyuxsmyxfbqcc7xthcavgpripjevi
#### Id
> 552d4f58-9bdf-475e-a8e0-7c603fabb517
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaxx5uxbn45jtztdnm2daon3y4deglodeuzlvlwmw5kfjligkjk4q

**Comment by liyunzhi-666** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedbyykh6icqmzti7ahhfkvletfbmgwszff7ekojlpojhsxx5f6u56 
#### Address 
> f1eotkofs3ywuqskq5un67hgnpyoznvlvhcqomukq
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1pszcrsciyixyuxxukkvtazcokexbn54amf7gvoq
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedbyykh6icqmzti7ahhfkvletfbmgwszff7ekojlpojhsxx5f6u56

**Comment by liyunzhi-666** [comment]
I checked the data sample and customer information. Willing to support the first round and monitor the subsequent distribution.

**Comment by kevzak** [comment]
checker:manualTrigger

**Comment by kevzak** [comment]
checker:manualTrigger

**Comment by avavanDam** [comment]
Got it!

**Comment by avavanDam** [comment]
yes!

**Comment by avavanDam** [comment]
SPs are ready to storing.

**Comment by cryptowhizzard** [comment]
Dear ava0021,

As notary I am doing due diligence on your LDN. I could not get retrieval to work. Can you please upload the car file of CID  ?

You can use our upload system at http://send.datasetcreators.com. Please select 7 days for the system to keep the file and post the link you received here so I (and other notaries) can download your content.

**Comment by avavanDam** [comment]
Maybe you should check your network and try to download it again. Because I don't know what's your program's problem about it.

**Comment by avavanDam** [comment]
Yes please

**Comment by avavanDam** [comment]
Keep open.

**Comment by avavanDam** [comment]
Keep open.

**Comment by avavanDam** [comment]
Yes please

**Comment by avavanDam** [comment]
Yes please

**Comment by BobbyChoii** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecnr2v3k24s4qrqvmexgfhi25km6jvxd2niv6opiqttk6qcwqibxg 
#### Address 
> f1eotkofs3ywuqskq5un67hgnpyoznvlvhcqomukq
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1irqs2gmctiv3jcdfwuch7oxvf4ixh3k4b2wc24i
#### Id
> 30493ac6-35d7-40a0-878d-2729c3eaaef2
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecnr2v3k24s4qrqvmexgfhi25km6jvxd2niv6opiqttk6qcwqibxg

**Comment by Suyanj** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecfj2w6bqxuzrbsrdxv6nqjatbuizo7njbsphfu3fgnifbynjghwi 
#### Address 
> f1eotkofs3ywuqskq5un67hgnpyoznvlvhcqomukq
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1ihv7gz3vn3xqvikpt4rwryecgisl7745lodx3yi
#### Id
> 30493ac6-35d7-40a0-878d-2729c3eaaef2
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecfj2w6bqxuzrbsrdxv6nqjatbuizo7njbsphfu3fgnifbynjghwi

**Comment by avavanDam** [comment]
@Sunnyiscoming I have submitted the form.

**Comment by Filplus-govteam** [comment]
checker:manualTrigger

**Comment by Filplus-govteam** [comment]
f01844232 |  individual | Dallas, Texas, US | no | Lukas
f02368321 |  Carl | Singapore | no | carl
f01844999 | individual | Ashburn, US | no | tony
f02368314 | personal sp | Deyang, Sichuan, CN | no | Barry
f0117211 |  Emma | Guiyang, Guizhou | no | Emma

SP taking deals

f01844232 | Dallas, Texas, USHawk Host Inc. | 108.00 TiB | 68.35% | 108.00 TiB | 0.00%
f01844999 | Dulles Town Center, Virginia, USSpeedyPage Ltd | 50.00 TiB | 31.65% | 50.00 TiB | 0.00%

@avavanDam SPs in Dallas and Virginia should be able to provide clear SP entity and location proof. Closing until updated
