### ISSUE TITLE
[DataCap Application]Jaggy Sharp IT solutions

### ISSUE THREAD

**Issue by amaryisharono** [filecoin-project/filecoin-plus-large-datasets#175]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Jaggy Inc.
- Website / Social Media:https://www.jaggy.com/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 2PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):150TiB
- On-chain address for first allocation:f1bpncrva3scb63ege4w56w3udl35nt7ikhq2snwy

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Jaggy is a successor of Qualia Design, a graphic design and new media company established in 1996. In April 1999, Jaggy Inc. was formed to establish a new thriving entity focusing on enterprise Information Technology services while maintaining the creative aspect from the Qualia heritage.
The following project "Documax" - a prototype of one of the first Web-based Document Management and Photo Storage systems was considered at the time a cutting-edge, and Jaggy's team found the sharp "jaggery" solution symbolized the company's product. A new company branding took place the following year taking the "jaggy" look into a more stylized form.
Fast forward to today and technology is more central to Jaggy's business than ever before as it builds on the foundation of the digital era to create the information age. Innovation - the combination of technical know-how with commercial acumen - becomes even more crucial in a competitive world.
```

What is the primary source of funding for this project?
```
Shareholders and Technology Partners.
```

What other projects/ecosystem stakeholders is this project associated with?
```
No other projects/ecosystem stakeholders.
```

## Use-case details

Describe the data being stored onto Filecoin
```
Cases of services.
```

Where was the data in this dataset sourced from?
```
The data comes from our public information.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
Yes. You can look at this example. 
![image](https://user-images.githubusercontent.com/96288354/147462066-c1699610-d191-4e50-a73e-e921dc8393fd.png)
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes, we confirm. This is a public dataset.
```

What is the expected retrieval frequency for this data?
```
It will depends on clients' need.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
If all goes well, we'll make it a permanent archival.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
We plan on making storage deals in North America and China.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Yes. We will use offline transmission.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We want to choose miners who can ensure the stability and security of data transmission.
```

How will you be distributing deals across storage providers?
```
Try to make sure they are allocated according to ability.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes. We are preparing to make deals as soon as possible. We don't have other support for the time being
```

**Comment by dkkapur** [comment]
@amaryisharono can you expand on what exactly is being stored? 
I see a `Cases of services.` mentioned above and the image is very helpful, but just looks like what type of services Jaggy offers. Is the intent to store backup/archival data of all Jaggy's past services offered to clients? How does this add up to a requirement of 2PiB?

**Comment by amaryisharono** [comment]
Sorry for the late reply, Deep! @dkkapur 
Yes, we want to backup/archival data of all Jaggy's past services offered to clients, you can see our IT outsourcing page, Most of our DBAs have over 15 years of experience. Our Oracle, SQL Server, MySQL, and DB2Database Administration experts have the real-world experience and technical knowledge to proactively and securely manage clients' business-critical Databases. We also provide backup service to our clients. Please refer https://www.jaggy.com/content/storage-backup for more detail. To be honest, this is our test for keeping data in Filecoin, hope this program can reduce our cost of storage and connect more SPs for us.

**Comment by amaryisharono** [comment]
Thank you for your support!

**Comment by galen-mcandrew** [comment]
## Multisig Notary requested
#### Total DataCap requested 
> 2PiB
#### Expected weekly DataCap usage rate 
> 150TiB

**Comment by amaryisharono** [comment]
Hello! I'm waiting for my datacap. But it seems that my issue is forgot by the bot. Can you help me? @dkkapur @galen-mcandrew

**Comment by amaryisharono** [comment]
My issue is still no any progress now. Is it time to let notaries sign my issue? @galen-mcandrew @KwrayFF

**Comment by Fenbushi-Filecoin** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceayucdqlelx2oftoeyqrufswik4rxdj2m7ytlyecu6jlwpt545d5q 
#### Address 
> f1bpncrva3scb63ege4w56w3udl35nt7ikhq2snwy
#### Datacap Allocated
> 75TiB
#### Signer Address
> f1yqydpmqb5en262jpottko2kd65msajax7fi4rmq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceayucdqlelx2oftoeyqrufswik4rxdj2m7ytlyecu6jlwpt545d5q

**Comment by Reiers** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecbowc5m37cigbqw2y73sdei3qkl7awdawaiwtyk24v4am53txurk 
#### Address 
> f1bpncrva3scb63ege4w56w3udl35nt7ikhq2snwy
#### Datacap Allocated
> 75TiB
#### Signer Address
> f1oz43ckvmtxmmsfzqm6bpnemqlavz4ifyl524chq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecbowc5m37cigbqw2y73sdei3qkl7awdawaiwtyk24v4am53txurk

**Comment by ozhtdong** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacearxpfxydpenh4hznhu73ivpiianpduzsqnwa5druczdb3y2swyn6 
#### Address 
> f1bpncrva3scb63ege4w56w3udl35nt7ikhq2snwy
#### Datacap Allocated
> 150TiB
#### Signer Address
> f1lwpw2bcv66pla3lpkcuzquw37pbx7ur4m6zvq2a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacearxpfxydpenh4hznhu73ivpiianpduzsqnwa5druczdb3y2swyn6

**Comment by XnMatrixSV** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceahfuorycbwb553apc64ar6grjnnbh7f66vdh7qkditru5okwuc6w 
#### Address 
> f1bpncrva3scb63ege4w56w3udl35nt7ikhq2snwy
#### Datacap Allocated
> 150TiB
#### Signer Address
> f1yuz2twsllparyfqwslfiuxrc5wj4mfiflvnsw6a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceahfuorycbwb553apc64ar6grjnnbh7f66vdh7qkditru5okwuc6w

**Comment by XnMatrixSV** [comment]
Please make sure the data is open to the public. Relevant data may be sampled in the next approval.

**Comment by amaryisharono** [comment]
Sure. We will use public data.

**Comment by rayshitou** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebpte2j5zfsy4cikrmucpfeksfh6u3noguekquhgszw7pnnwmg7fe 
#### Address 
> f1bpncrva3scb63ege4w56w3udl35nt7ikhq2snwy
#### Datacap Allocated
> 300.00TiB
#### Signer Address
> f136bz32l2hlyad4npmfg5dngcdw3jk3tpcpoz2ja
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebpte2j5zfsy4cikrmucpfeksfh6u3noguekquhgszw7pnnwmg7fe

**Comment by MRJAVAZHAO** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaojn2cr65g4y2nc2s7goatmghcr3bq5sudpx63oeyr56uce4axmi 
#### Address 
> f1bpncrva3scb63ege4w56w3udl35nt7ikhq2snwy
#### Datacap Allocated
> 300.00TiB
#### Signer Address
> f14gme3f52prtyzk6pblogrdd6b6ivp4swc6qmesi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaojn2cr65g4y2nc2s7goatmghcr3bq5sudpx63oeyr56uce4axmi

**Comment by Reiers** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceae5jf3gafniayqbd6ctival6ircenaf32ec4hf4bwhoof2qmtoac 
#### Address 
> f1bpncrva3scb63ege4w56w3udl35nt7ikhq2snwy
#### Datacap Allocated
> 600.00TiB
#### Signer Address
> f1oz43ckvmtxmmsfzqm6bpnemqlavz4ifyl524chq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceae5jf3gafniayqbd6ctival6ircenaf32ec4hf4bwhoof2qmtoac

**Comment by KodaRobotDog** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebkzm7dsjslit7c4w7ag2zizqmnsc47skodryshj66kadeksto2lw 
#### Address 
> f1bpncrva3scb63ege4w56w3udl35nt7ikhq2snwy
#### Datacap Allocated
> 600.00TiB
#### Signer Address
> f1jyalts5uhtmp5sbbssse23toshvsqbbtjgukm5a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebkzm7dsjslit7c4w7ag2zizqmnsc47skodryshj66kadeksto2lw

**Comment by rayshitou** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedoshtuhcl3iq446udfrubjhqs7e6zmv7mwqgsbfmtjibnskpx2my 
#### Address 
> f1bpncrva3scb63ege4w56w3udl35nt7ikhq2snwy
#### Datacap Allocated
> 923.00TiB
#### Signer Address
> f136bz32l2hlyad4npmfg5dngcdw3jk3tpcpoz2ja
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedoshtuhcl3iq446udfrubjhqs7e6zmv7mwqgsbfmtjibnskpx2my

**Comment by XnMatrixSV** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecc2qjjfxrngn6pwzgqev7vjz745rpusznjogxm5yezkvhgs26drs 
#### Address 
> f1bpncrva3scb63ege4w56w3udl35nt7ikhq2snwy
#### Datacap Allocated
> 923.00TiB
#### Signer Address
> f1yuz2twsllparyfqwslfiuxrc5wj4mfiflvnsw6a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecc2qjjfxrngn6pwzgqev7vjz745rpusznjogxm5yezkvhgs26drs

**Comment by dkkapur** [comment]
All DataCap allocated 🎉!
