### ISSUE TITLE
[DataCap Application] StoneMoonGalaxy - <USGS-Environmental Monitoring Dataset> [ 2/6]

### ISSUE THREAD

**Issue by StoneMoonGalaxy** [filecoin-project/filecoin-plus-large-datasets#1756]
### Data Owner Name

USGS

### Data Owner Country/Region

United States

### Data Owner Industry

Environment

### Website

https://earthexplorer.usgs.gov/;https://glovis.usgs.gov/

### Social Media

```text
https://twitter.com/StoneMoonGalaxy
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

450TiB

### On-chain address for first allocation

f1a6trohs22mcmyqdtixy5jjah4kxslisk6hvd3fi

### Custom multisig

- [ ] Use Custom Multisig

### Identifier

none

### Share a brief history of your project and organization

```text
Stone Moon is a platform that provides storage solutions. Focus on Filecoin storage and FVM smart contract application development.
Since relaunching the project in Australia, we have integrated a large number of storage providers and infrastructure service providers in order to help build the Filecoin eco-network and promote the storage and retrieval of real data, as well as to meet the hot market demand and bring more decentralized storage enthusiasts into the network, for which we will work tirelessly to find new and useful data to bring into the network. To this end, we will work tirelessly to find new and useful data and bring it to the network.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### If answered yes, what are the other projects/ecosystem stakeholders

```text
none
```

### Describe the data being stored onto Filecoin

```text
The dataset is from a collection of public data provided by the U.S. Geological Survey (USGS), including geological, environmental, and especially natural disaster data. Each collection contains a different type of data. Include:

Landsat: This dataset includes high-resolution satellite imagery of the Earth's surface, collected by the Landsat program. It covers over 40 years of imagery, and is useful for studying changes in land use, natural disasters, and more.

3D Elevation Program (3DEP): This dataset provides high-resolution elevation data for the entire United States, including both bare earth and surface features such as vegetation and buildings.

Sentinel-2 series：The USGS manages and distributes data from the Sentinel-2 mission through its EarthExplorer and GloVis portals, providing free access to images for researchers, scientists and the public. It is also incorporated into the Landsat Archives of the United States Geological Survey, and both data sets are used for a variety of applications, such as land use and land cover mapping, environmental monitoring, and natural resource management.
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### How do you plan to prepare the dataset

others/custom tool

### If you answered "other/custom tool" in the previous question, enter the details here

```text
Self-developed packing tool
```

### Please share a sample of the data

```text
Landsat:
s3://usgs-landsat/collection02/
s3://deafrica-landsat/
s3://astrogeo-ard/mars/mo/themis/controlled_mosaics/
s3://astrogeo-ard/jupiter/europa/galileo_voyager/usgs_controlled_mosaics/
s3://astrogeo-ard/jupiter/europa/galileo_voyager/usgs_controlled_observations/
s3://usgs-lidar-uscities/
USGS 3DEP
s3://usgs-lidar-public/
Sentinel-2
s3://sentinel-s2-l1c/
s3://sentinel-cogs/
s3://esa-worldcover/
s3://deafrica-services/gm_s2_annual/
s3://deafrica-sentinel-2/
s3://deafrica-services/crop_mask/
s3://bdc-sentinel-2/
s3://io-10m-annual-lulc/
s3://sentinel-s2-l2a-mosaic-120/
s3://radiant-mlhub/c2smsfloods/
s3://sentinel-products-ca-mirror/
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### If you chose not to confirm, what was the reason

```text
none
```

### What is the expected retrieval frequency for this data

Sporadic

### For how long do you plan to keep this dataset stored on Filecoin

1.5 to 2 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, Europe, Australia (continent)

### How will you be distributing your data to storage providers

Cloud storage (i.e. S3), HTTP or FTP server, Shipping hard drives, Others

### How do you plan to choose storage providers

Slack, Partners, Others

### If you answered "Others" in the previous question, what is the tool or platform you plan to use

```text
none
```

### If you already have a list of storage providers to work with, fill out their names and provider IDs below

```text
| MinerID | org | region |
| --- | --- | --- |
| f02058976 | Open Gate | AU |
| f0442671 | Open Gate | AU |
| f0515461 | Friday engine inc. | US |
| f0818235 | xu xiong | CN |
| f0443184 | WITMIND SYSTEM TECHNOLOGY LIMITED | HK |
| f02003553 | WITMIND SYSTEM TECHNOLOGY LIMITED | HK |
```

### How do you plan to make deals to your storage providers

Lotus client

### If you answered "Others/custom tool" in the previous question, enter the details here

```text
none
```

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 5PiB

**Expected weekly DataCap usage rate**
> 450TiB

**Client address**
>f1a6trohs22mcmyqdtixy5jjah4kxslisk6hvd3fi

**Comment by sxxfuture-official** [comment]
Public dataset, and first round, detailed disclosure of SPs and their Regions
Willing to support

**Comment by sxxfuture-official** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec7tb7pof4hp4lfwga26zij4neuip73a654z6xl5rc7jsjzadgegy 
#### Address 
> f1a6trohs22mcmyqdtixy5jjah4kxslisk6hvd3fi
#### Datacap Allocated
> 225.00TiB
#### Signer Address
> f1foiomqlmoshpuxm6aie4xysffqezkjnokgwcecq
#### Id
> 4dd502cc-2276-48f0-83a6-2b209d6b63de
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec7tb7pof4hp4lfwga26zij4neuip73a654z6xl5rc7jsjzadgegy

**Comment by newwebgroup** [comment]
It's great to see big public datasets being loaded into Filecoin
1. What is the download bandwidth of your network?
2. What is the upload bandwidth of your network?
3. How long do you expect to complete the storage plan for this dataset? 
4. What tools do you plan to use to prepare the Car?

**Comment by StoneMoonGalaxy** [comment]
@newwebgroup thanks for  your asking.
We use peer bandwidth, which is 30 GB
The sps we contacted started storage gradually, the specific storage time depends on their encapsulating, and in the process of data transfer, we use hard disk, so the overall project can take several months.

**Comment by newwebgroup** [comment]
Will support in the first round, looking forward to a good performance

**Comment by newwebgroup** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaaf3iphv4b2inqyz6mzlccgdljvidryhx6l6oqgeqgscdcqqxdpi 
#### Address 
> f1a6trohs22mcmyqdtixy5jjah4kxslisk6hvd3fi
#### Datacap Allocated
> 225.00TiB
#### Signer Address
> f1e77zuityhvvw6u2t6tb5qlnsegy2s67qs4lbbbq
#### Id
> 4dd502cc-2276-48f0-83a6-2b209d6b63de
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaaf3iphv4b2inqyz6mzlccgdljvidryhx6l6oqgeqgscdcqqxdpi

**Comment by StoneMoonGalaxy** [comment]
checker:manualTrigger

**Comment by a1991car** [comment]
<img width="848" alt="WechatIMG370" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/32447611/11573063-3482-4015-9d54-177363cd8088">

**Comment by a1991car** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedbqxzxyv4hurq7i4blt5yz3gju3eazjodp4lsea77nz7c2oyngns 
#### Address 
> f1a6trohs22mcmyqdtixy5jjah4kxslisk6hvd3fi
#### Datacap Allocated
> 450.00TiB
#### Signer Address
> f1qnumecdypgrbaebtkdfjnwt5ndacadcuas3deiq
#### Id
> 08b38e23-fa04-4dfd-88e5-4501080c9dd5
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedbqxzxyv4hurq7i4blt5yz3gju3eazjodp4lsea77nz7c2oyngns

**Comment by Tom-OriginStorage** [comment]
checker:manualTrigger

**Comment by Tom-OriginStorage** [comment]
<img width="741" alt="image" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/103015469/c06b2158-e38b-473b-90f4-a70fbeed3621">

**Comment by Tom-OriginStorage** [comment]
Currently in compliance with the rules, additional nodes need to be added in the future, willing to support this round

**Comment by Tom-OriginStorage** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacednwzuwwftecnv536umx22h4zv2ej7zsmfcc7h4sly6etf7oxigeq 
#### Address 
> f1a6trohs22mcmyqdtixy5jjah4kxslisk6hvd3fi
#### Datacap Allocated
> 450.00TiB
#### Signer Address
> f1q6bpjlqia6iemqbrdaxr2uehrhpvoju3qh4lpga
#### Id
> 08b38e23-fa04-4dfd-88e5-4501080c9dd5
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacednwzuwwftecnv536umx22h4zv2ej7zsmfcc7h4sly6etf7oxigeq

**Comment by StoneMoonGalaxy** [comment]
checker:manualTrigger

**Comment by StoneMoonGalaxy** [comment]
Bot malfunction, the second batch of shares did not arrive.

<img width="429" alt="053" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/114480622/4a40f65e-c757-4021-a929-54f170c88fd1">

**Comment by DirectionTechnology** [comment]
The retrieval process is functioning normally.(filecoin.tools/f02032453)

......client retrieve --provider f02032453 uAXCg5AIg38LrF2KxdzEwulEstQqQlDFIPL0sAafiWSbxQh0rJ3U 37512787.car 
Recv 0 B,Paid 0 FIL,Open (New), 0s [1682577152054488760|0]
Recv 0 B,Paid 0 FIL,DealProposed (WaitForAcceptance), 3ms [1682577152054488760|0]
Recv 0 B,Paid 0 FIL,DealAccepted (Accepted), 452ms [1682577152054488760|0]

**Comment by DirectionTechnology** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecwqe4rex73jeqt4crzeeybqt3yggzsn7m6kl66bzogxmsmwwwr5k 
#### Address 
> f1a6trohs22mcmyqdtixy5jjah4kxslisk6hvd3fi
#### Datacap Allocated
> 450.00TiB
#### Signer Address
> f1inkdoatsbfumdvpctxbgcatscewr3rus5pxmsgi
#### Id
> a3476dcc-2bd6-4738-b6b7-0bba2d193dd6
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecwqe4rex73jeqt4crzeeybqt3yggzsn7m6kl66bzogxmsmwwwr5k

**Comment by spaceT9** [comment]
checker:manualTrigger

**Comment by StoneMoonGalaxy** [comment]
checker:manualTrigger

**Comment by StoneMoonGalaxy** [comment]
Preparing data...

**Comment by kevzak** [comment]
checker:manualTrigger

**Comment by kevzak** [comment]
Hello @StoneMoonGalaxy same questions as previous application [LINK](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1755#issuecomment-1618576566)

**Comment by StoneMoonGalaxy** [comment]
Already [responded](https://github.com/filecoin-project/notary-governance/issues/923#issuecomment-1639506829)

**Comment by StoneMoonGalaxy** [comment]
FYR[ LINK](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1755#issuecomment-1668833570)

**Comment by StoneMoonGalaxy** [comment]
WIP

**Comment by StoneMoonGalaxy** [comment]
WIP

**Comment by StoneMoonGalaxy** [comment]
WIP

**Comment by StoneMoonGalaxy** [comment]
WIP

**Comment by StoneMoonGalaxy** [comment]
WIP

**Comment by StoneMoonGalaxy** [comment]
WIP

**Comment by StoneMoonGalaxy** [comment]
Please keep it open.

**Comment by StoneMoonGalaxy** [comment]
Please keep it open.

**Comment by StoneMoonGalaxy** [comment]
WIP

**Comment by StoneMoonGalaxy** [comment]
WIP

**Comment by Sunnyiscoming** [comment]
Hello, @StoneMoonGalaxy per the https://github.com/filecoin-project/notary-governance/issues/922 for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

This information will be reviewed by Fil+ Governance team to confirm validity and then the application will be allowed to move forward for additional notary review.

**Comment by Filplus-govteam** [comment]
checker:manualTrigger

**Comment by Filplus-govteam** [comment]
closing until clear SP entity and distribution list is provided

**Comment by StoneMoonGalaxy** [comment]
Updated:

![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/114480622/4cd43d6c-e132-4766-87dc-e66040f9df3e)
