### ISSUE TITLE
[DataCap Application] StoneMoonGalaxy - <USGS-Environmental Monitoring Dataset> [3 /6]

### ISSUE THREAD

**Issue by StoneMoonGalaxy** [filecoin-project/filecoin-plus-large-datasets#1757]
### Data Owner Name

USGS

### Data Owner Country/Region

United States

### Data Owner Industry

Environment

### Website

https://earthexplorer.usgs.gov/ ; https://glovis.usgs.gov/

### Social Media

```text
https://twitter.com/StoneMoonGalaxy
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

450TiB

### On-chain address for first allocation

f1w6iqew74agqasewqandzefwe62hyjy7ikndchzi

### Custom multisig

- [ ] Use Custom Multisig

### Identifier

none

### Share a brief history of your project and organization

```text
Stone Moon is a platform that provides storage solutions. Focus on Filecoin storage and FVM smart contract application development.
Since relaunching the project in Australia, we have integrated a large number of storage providers and infrastructure service providers in order to help build the Filecoin eco-network and promote the storage and retrieval of real data, as well as to meet the hot market demand and bring more decentralized storage enthusiasts into the network, for which we will work tirelessly to find new and useful data to bring into the network. To this end, we will work tirelessly to find new and useful data and bring it to the network.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### If answered yes, what are the other projects/ecosystem stakeholders

```text
none
```

### Describe the data being stored onto Filecoin

```text
The dataset is from a collection of public data provided by the U.S. Geological Survey (USGS), including geological, environmental, and especially natural disaster data. Each collection contains a different type of data. Include:

Landsat: This dataset includes high-resolution satellite imagery of the Earth's surface, collected by the Landsat program. It covers over 40 years of imagery, and is useful for studying changes in land use, natural disasters, and more.

3D Elevation Program (3DEP): This dataset provides high-resolution elevation data for the entire United States, including both bare earth and surface features such as vegetation and buildings.

Sentinel-2 series：The USGS manages and distributes data from the Sentinel-2 mission through its EarthExplorer and GloVis portals, providing free access to images for researchers, scientists and the public. It is also incorporated into the Landsat Archives of the United States Geological Survey, and both data sets are used for a variety of applications, such as land use and land cover mapping, environmental monitoring, and natural resource management.
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### How do you plan to prepare the dataset

others/custom tool

### If you answered "other/custom tool" in the previous question, enter the details here

```text
Self-developed packing tool
```

### Please share a sample of the data

```text
Landsat:
s3://usgs-landsat/collection02/
s3://deafrica-landsat/
s3://astrogeo-ard/mars/mo/themis/controlled_mosaics/
s3://astrogeo-ard/jupiter/europa/galileo_voyager/usgs_controlled_mosaics/
s3://astrogeo-ard/jupiter/europa/galileo_voyager/usgs_controlled_observations/
s3://usgs-lidar-uscities/
USGS 3DEP
s3://usgs-lidar-public/
Sentinel-2
s3://sentinel-s2-l1c/
s3://sentinel-cogs/
s3://esa-worldcover/
s3://deafrica-services/gm_s2_annual/
s3://deafrica-sentinel-2/
s3://deafrica-services/crop_mask/
s3://bdc-sentinel-2/
s3://io-10m-annual-lulc/
s3://sentinel-s2-l2a-mosaic-120/
s3://radiant-mlhub/c2smsfloods/
s3://sentinel-products-ca-mirror/
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### If you chose not to confirm, what was the reason

```text
none
```

### What is the expected retrieval frequency for this data

Sporadic

### For how long do you plan to keep this dataset stored on Filecoin

1.5 to 2 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, Europe, Australia (continent)

### How will you be distributing your data to storage providers

Cloud storage (i.e. S3), HTTP or FTP server, Shipping hard drives, Others

### How do you plan to choose storage providers

Slack, Partners, Others

### If you answered "Others" in the previous question, what is the tool or platform you plan to use

```text
none
```

### If you already have a list of storage providers to work with, fill out their names and provider IDs below

```text
| MinerID | org | region |
| --- | --- | --- |
| f02058976 | Open Gate | AU |
| f0442671 | Open Gate | AU |
| f0515461 | Friday engine inc. | US |
| f0818235 | xu xiong | CN |
| f0443184 | WITMIND SYSTEM TECHNOLOGY LIMITED | HK |
| f02003553 | WITMIND SYSTEM TECHNOLOGY LIMITED | HK |
```

### How do you plan to make deals to your storage providers

Lotus client

### If you answered "Others/custom tool" in the previous question, enter the details here

```text
none
```

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 5PiB

**Expected weekly DataCap usage rate**
> 450TiB

**Client address**
>f1w6iqew74agqasewqandzefwe62hyjy7ikndchzi

**Comment by newwebgroup** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaso7b2cfivqjnozvnzkions3wvouzobymavcd2xfxtd4yktwa24u 
#### Address 
> f1w6iqew74agqasewqandzefwe62hyjy7ikndchzi
#### Datacap Allocated
> 225.00TiB
#### Signer Address
> f1e77zuityhvvw6u2t6tb5qlnsegy2s67qs4lbbbq
#### Id
> ffc08d8e-7f4d-40b2-bae3-8a41068214f9
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaso7b2cfivqjnozvnzkions3wvouzobymavcd2xfxtd4yktwa24u

**Comment by Tom-OriginStorage** [comment]
Public dataset, confirmed by other notaries, willing to support the first round

**Comment by Tom-OriginStorage** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedybagbnnzoxbloxepof2p5rzowcmlrsgtdurudb2d63dtbsfiqko 
#### Address 
> f1w6iqew74agqasewqandzefwe62hyjy7ikndchzi
#### Datacap Allocated
> 225.00TiB
#### Signer Address
> f1q6bpjlqia6iemqbrdaxr2uehrhpvoju3qh4lpga
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedybagbnnzoxbloxepof2p5rzowcmlrsgtdurudb2d63dtbsfiqko

**Comment by StoneMoonGalaxy** [comment]
checker:manualTrigger

**Comment by StoneMoonGalaxy** [comment]
The packaging is in progress and there is a delay in the report.

**Comment by StoneMoonGalaxy** [comment]
checker:manualTrigger

**Comment by a1991car** [comment]
<img width="884" alt="1757IMG372" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/32447611/c34c8148-f3f3-46e5-a847-9d5590f1291b">

**Comment by a1991car** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebladatjxvii2236on7or2pe2q475jifztbhbhmsuau5v3aowjlps 
#### Address 
> f1w6iqew74agqasewqandzefwe62hyjy7ikndchzi
#### Datacap Allocated
> 450.00TiB
#### Signer Address
> f1qnumecdypgrbaebtkdfjnwt5ndacadcuas3deiq
#### Id
> 51c51087-a19b-4849-b60b-4c33674b13d8
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebladatjxvii2236on7or2pe2q475jifztbhbhmsuau5v3aowjlps

**Comment by StoneMoonGalaxy** [comment]
Everything is normal.

**Comment by StoneMoonGalaxy** [comment]
Preparing data...

**Comment by StoneMoonGalaxy** [comment]
Preparing data...

**Comment by kevzak** [comment]
Hello @StoneMoonGalaxy same questions as previous application https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1755#issuecomment-1618576566

**Comment by StoneMoonGalaxy** [comment]
Already [responded](https://github.com/filecoin-project/notary-governance/issues/923#issuecomment-1639506829)

**Comment by StoneMoonGalaxy** [comment]
FYR[ LINK](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1755#issuecomment-1668833570)

**Comment by StoneMoonGalaxy** [comment]
WIP

**Comment by StoneMoonGalaxy** [comment]
WIP

**Comment by StoneMoonGalaxy** [comment]
checker:manualTrigger

**Comment by StoneMoonGalaxy** [comment]
WIP

**Comment by StoneMoonGalaxy** [comment]
WIP

**Comment by StoneMoonGalaxy** [comment]
Please keep it open.

**Comment by StoneMoonGalaxy** [comment]
Please keep it open.

**Comment by StoneMoonGalaxy** [comment]
WIP

**Comment by StoneMoonGalaxy** [comment]
WIP

**Comment by Filplus-govteam** [comment]
closing until clear SP entity and distribution list is provided

**Comment by StoneMoonGalaxy** [comment]
Updated
![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/114480622/26df21cc-67c1-483e-b426-5eb4db98dc1e)
