### ISSUE TITLE
[DataCap Application] Aether - Aether Metaverse

### ISSUE THREAD

**Issue by drwynn** [filecoin-project/filecoin-plus-large-datasets#1767]
### Data Owner Name

www.aether.place

### Data Owner Country/Region

United States

### Data Owner Industry

Web3 / Crypto

### Website

https://www.aether.place/

### Social Media

```text
https://twitter.com/TheAether_io
https://discord.com/invite/JqVbvfwmre
```

### Total amount of DataCap being requested

3PiB

### Weekly allocation of DataCap requested

300TiB

### On-chain address for first allocation

f1ml4u3hlf53zvq6yuvageowz57lrxgeol24k7ubq

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
The Aether metaverse is a decentralized, open metasomatic virtual world built using blockchain technology, where users can build, trade, interact socially, and generate economic revenue. Each user is given free access to celestial space, where they are given a unique virtual ID. In Aether, players can Play, Create, Own, Govern, Social, earn.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
1.The metadata and media data of nft which is owned by the Aether
2.Middleware used by the project 
3.Model files for metaverse space
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### How do you plan to prepare the dataset

IPFS, lotus, singularity, graphsplit

### Please share a sample of the data

```text
https://gateway.pinata.cloud/ipfs/QmYJt8kP6enkabgJM37ZAKae4wAVvJRxFNFK126MkuMakY/?_gl=1*1qyi6n4*_ga*OTQ0ODM2Mzk5LjE2NjcyNjc5ODE.*_ga_5RMPXG14TE*MTY3ODQxNTc5My41LjEuMTY3ODQxNTgwNi40Ny4wLjA.

https://gateway.pinata.cloud/ipfs/Qmdiuw24MBpTvTpXSbuzaPdvyacyvpdQ3znyzNeF6JWMzH/?_gl=1*1wbb4kv*_ga*OTQ0ODM2Mzk5LjE2NjcyNjc5ODE.*_ga_5RMPXG14TE*MTY3ODQxNTc5My41LjEuMTY3ODQxNTgwNi40Ny4wLjA.

https://drive.google.com/file/d/17g8lh-PGSBmUi965wFFoHYgkDya0PPkX/view?usp=share_link

https://drive.google.com/file/d/1a4nDAbTv3BjaYUxxqpBe5KJ-peVFOWx6/view?usp=share_link

https://drive.google.com/file/d/16tvZuE-mAEXBUGn-Zbbso057LlNqPh3D/view?usp=share_link
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [x] I confirm

### What is the expected retrieval frequency for this data

Sporadic

### For how long do you plan to keep this dataset stored on Filecoin

1 to 1.5 years

### In which geographies do you plan on making storage deals

Asia other than Greater China, Africa, North America, South America, Europe, Australia (continent), Antarctica

### How will you be distributing your data to storage providers

Cloud storage (i.e. S3), HTTP or FTP server, IPFS, Lotus built-in data transfer

### How do you plan to choose storage providers

Slack, Filmine, Big data exchange, Partners

### How do you plan to make deals to your storage providers

Boost client, Lotus client, Bidbot, Singularity

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 3PiB

**Expected weekly DataCap usage rate**
> 300TiB

**Client address**
>f1ml4u3hlf53zvq6yuvageowz57lrxgeol24k7ubq

**Comment by Aaron01230** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin FIL+ notary i am screening your application and conducting due diligence.

Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?

Anther question i would like you to fill out this form (https://form.jotform.com/230730730268452) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Looking at your application i have some questions:
As you are brand new on Github and have no history of past applications it seems to me that applying for 3PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?

Can you show us visible proof of the size of your data and the storage systems you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230337462961356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!

**Comment by drwynn** [comment]
> Dear applicant,
> 
> Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.
> 
> Looking at your application i have some questions: As you are brand new on Github and have no history of past applications it seems to me that applying for 3PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?
> 
> Can you show us visible proof of the size of your data and the storage systems you have there?
> 
> As last question i would like you to fill out [this form](https://form.jotform.com/230337462961356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.
> 
> Thanks!

This is our first application for FIL+ LDN, we have already made sufficient relevant knowledge reserves, and we will fully abide by all the rules of FIL+.

Here is a screenshot of some of our data volumes:
<img width="535" alt="image" src="https://user-images.githubusercontent.com/115347122/226258857-a67bc458-a748-4999-94dc-8b858eac5f25.png">

I will fill out the KYC form later ,thank you for your support ! @cryptowhizzard

**Comment by drwynn** [comment]
> Dear applicant,
> 
> Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.
> 
> Looking at your application i have some questions: As you are brand new on Github and have no history of past applications it seems to me that applying for 3PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?
> 
> Can you show us visible proof of the size of your data and the storage systems you have there?
> 
> As last question i would like you to fill out [this form](https://form.jotform.com/230337462961356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.
> 
> Thanks!

Dear cryptowhizzard,
I had submit the KYC form,  can you sign for me now?

**Comment by stcouldlisa** [comment]
To get support, you first need to verify your identity by sending an email to filplus-app-review@fil.org using a domain email address.

Second, you also need to list the sps you work with.

**Comment by drwynn** [comment]
> To get support, you first need to verify your identity by sending an email to [filplus-app-review@fil.org](mailto:filplus-app-review@fil.org) using a domain email address.
> 
> Second, you also need to list the sps you work with.

<img width="1128" alt="image" src="https://user-images.githubusercontent.com/115347122/227911639-9d7fe288-062f-4d39-b693-28d4e50222f3.png">

I have sent the validation email with email address aether@aether.place.

**Comment by drwynn** [comment]
> To get support, you first need to verify your identity by sending an email to [filplus-app-review@fil.org](mailto:filplus-app-review@fil.org) using a domain email address.
> 
> Second, you also need to list the sps you work with.

Thank you , we have contacted several SPs, there are
f02013352 located in East Asia,
f01932183 located in US,
f02009671 Greater China.
We will find more SPs to coperate with.

**Comment by stcouldlisa** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecihivolzaacd5lexwzjruvpli5ovxcmxg2annu6ejnewcavgnyei 
#### Address 
> f1ml4u3hlf53zvq6yuvageowz57lrxgeol24k7ubq
#### Datacap Allocated
> 150.00TiB
#### Signer Address
> f1jvvltduw35u6inn5tr4nfualyd42bh3vjtylgci
#### Id
> fa75b3a7-39d9-4fba-a512-23a008ddadfe
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecihivolzaacd5lexwzjruvpli5ovxcmxg2annu6ejnewcavgnyei

**Comment by Aaron01230** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceawvlmg6xd5ftz6gxoc2zi65xakahpz44nqrc7ixnnmroahy7pwmm 
#### Address 
> f1ml4u3hlf53zvq6yuvageowz57lrxgeol24k7ubq
#### Datacap Allocated
> 150.00TiB
#### Signer Address
> f1xrnysd4gimg64d4l6qi7ulzwwq22c6vfg6lpw3i
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceawvlmg6xd5ftz6gxoc2zi65xakahpz44nqrc7ixnnmroahy7pwmm

**Comment by herrehesse** [comment]
checker:manualTrigger

**Comment by Aaron01230** [comment]
checker:manualTrigger

**Comment by Aaron01230** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacea2s2jjy5bfljzlaobup4cnz7lbpeph3j7ah5zwgypmgekkzzi3q2 
#### Address 
> f1ml4u3hlf53zvq6yuvageowz57lrxgeol24k7ubq
#### Datacap Allocated
> 300.00TiB
#### Signer Address
> f1xrnysd4gimg64d4l6qi7ulzwwq22c6vfg6lpw3i
#### Id
> 2fdda5a9-05ff-4f3f-87ff-682fae35cd6b
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacea2s2jjy5bfljzlaobup4cnz7lbpeph3j7ah5zwgypmgekkzzi3q2

**Comment by zcfil** [comment]
checker:manualTrigger

**Comment by zcfil** [comment]
checker:manualTrigger

**Comment by zcfil** [comment]
checker:manualTrigger

**Comment by zcfil** [comment]
@Kevin-FF-USA checker LDN lose

**Comment by zcfil** [comment]
checker:manualTrigger

**Comment by drwynn** [comment]
Our LDN first issued bills and imports. Because the gas of the entire network is too high, the progress of SP sealing is delayed. The sealing can be completed in about 3 days, and the retrieval rate will increase. At that time, we will re-trigger the retrieval report. Thanks to the community for their focusing, we promise, we are all retrievable

And there was also a problem with the boot robot yesterday, the report information could not be displayed in time. In the case that the new round of quota has been triggered, I contacted the notary and asked them to sign it first.

**Comment by nicelove666** [comment]
checker:manualTrigger

**Comment by igoovo** [comment]
checker:manualTrigger

**Comment by igoovo** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedpul35cgufa2qptl7k4tdextikl3ifqu5quakcvwazgpts34kqls 
#### Address 
> f1ml4u3hlf53zvq6yuvageowz57lrxgeol24k7ubq
#### Datacap Allocated
> 600.00TiB
#### Signer Address
> f1shnsfayxqll77svffaxnjenms7bbbysbqcatrpy
#### Id
> be671f28-b2d4-4dee-a797-c0bce34d13e6
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedpul35cgufa2qptl7k4tdextikl3ifqu5quakcvwazgpts34kqls

**Comment by igoovo** [comment]
⚠️ 100.00% of deals are for data replicated across less than 4 storage providers.

Early in the mission, it can be supported.
The above concerns should be addressed in the follow-up.

**Comment by woshidama323** [comment]
It shows that you already have 3 SP for this application and 
I think it is easy for you to fix this. "100.00% of deals are for data replicated across less than 4 storage providers." issue
Please fix the ASAP 
Will support this first

**Comment by woshidama323** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec6qd4uppcjz4wlji2swljjmiygazmhaq3cwu5fso52gfr6hqjeog 
#### Address 
> f1ml4u3hlf53zvq6yuvageowz57lrxgeol24k7ubq
#### Datacap Allocated
> 600.00TiB
#### Signer Address
> f12tk3adljauwnd3hjbigpfxb7b7gdlj63p6afwtq
#### Id
> be671f28-b2d4-4dee-a797-c0bce34d13e6
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec6qd4uppcjz4wlji2swljjmiygazmhaq3cwu5fso52gfr6hqjeog

**Comment by Patapon0702** [comment]
checker:manualTrigger

**Comment by kevzak** [comment]
You mentioned you are working with:
f02013352 located in East Asia,
f01932183 located in US,
f02009671 Greater China,
f01923786 Greater China

I do not see any of those miner IDs in the [CID report](https://github.com/data-preservation-programs/filplus-checker-assets/blob/main/filecoin-project/filecoin-plus-large-datasets/issues/1767/1688264587206.md). I see one miner in China and one in Singapore.

Can you explain the SP entities you are working with? Do you plan to work with more?

**Comment by kevzak** [comment]
Also we have a new, optional KYC ID check available on [filplus.storage](https://filplus.storage/). If you want to add additional layer of trust you can complete an ID check and verify this GitHub account. See details: [LINK](https://medium.com/filecoin-plus/implementation-of-a-third-party-kyc-id-check-for-fil-applicants-e5e825b1484e)

**Comment by drwynn** [comment]
> Hello @drwynn I have a few questions for you: Are you the Data Owner here? Did you also prepare the data? How did you prepare the data? You didn't check the box if this data is public (and retrievable). Can you confirm?

yes, I am the owner of the data, we have prepared the data, we downloaded the data from our  server, collect it in the disk, and then send it to the cooperative SP. In addition, I forgot to check the box , and i confirm the data is public.

**Comment by drwynn** [comment]
> You mentioned you are working with: f02013352 located in East Asia, f01932183 located in US, f02009671 Greater China, f01923786 Greater China
> 
> I do not see any of those miner IDs in the [CID report](https://github.com/data-preservation-programs/filplus-checker-assets/blob/main/filecoin-project/filecoin-plus-large-datasets/issues/1767/1688264587206.md). I see one miner in China and one in Singapore.
> 
> Can you explain the SP entities you are working with? Do you plan to work with more?



> You mentioned you are working with: f02013352 located in East Asia, f01932183 located in US, f02009671 Greater China, f01923786 Greater China
> 
> I do not see any of those miner IDs in the [CID report](https://github.com/data-preservation-programs/filplus-checker-assets/blob/main/filecoin-project/filecoin-plus-large-datasets/issues/1767/1688264587206.md). I see one miner in China and one in Singapore.
> 
> Can you explain the SP entities you are working with? Do you plan to work with more?

We planned to cooperate with these SPs a few months ago, but then their sealing tasks is over recently, so we found new SPs to store our data. Yes, we are going to find more SP to cooperate with

**Comment by a1991car** [comment]
checker:manualTrigger

**Comment by cryptowhizzard** [comment]
Everything sealed with one organisation, 100% selfdealing.

<img width="1616" alt="Scherm­afbeelding 2023-07-07 om 17 14 16" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/36404435/fbf97a56-babc-404d-a170-96d0a7d6623a">

**Comment by drwynn** [comment]
> Everything sealed with one organisation, 100% selfdealing.
> 
> <img alt="Scherm­afbeelding 2023-07-07 om 17 14 16" width="1616" src="https://user-images.githubusercontent.com/36404435/251784833-fbf97a56-babc-404d-a170-96d0a7d6623a.png">

Thanks for your attention, next round we will look for more SPs to package. In addition, i think the 4 SPs you mentioned do not belong to the same organization. After IP analysis, they belong to at least 2 organizations. I don't understand what you mean by ipfsfy.com? I can't open this website and I can't even ping this domain name.

<img width="1098" alt="image" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/115347122/1489b682-2243-4108-bb28-614dda5a4cf9">
<img width="1086" alt="image" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/115347122/fe452278-8b3f-4d20-a149-550f4500fe1c">

**Comment by cryptowhizzard** [comment]
Uhm…. As data preparer you know the entities you do business with right?

**Comment by drwynn** [comment]
I think this is a problem with the Filecoin DC system. Does Filecoin require each node to perform real-name authentication? For a client applying for LDN for the first time, it is difficult to identify whether multiple nodes belong to an organization. From which dimensions can we judge whether the SP we contact belongs to an organization? Can you give me some guidance?

**Comment by cryptowhizzard** [comment]
I don’t think there is a problem.
When you applied for datacap you indicated that you read the rules and guidelines. They are all here:

https://github.com/filecoin-project/filecoin-plus-large-datasets

It is also not difficult as data preparer to ask your SP’s who they are. You decide where you will store the data so you are the one who know the identity of the SP’s you do business with.

Tell me, why not seal one replica yourself and find 3 organisations for the other replica’s. Why is it that it needs to be put to the maximum violating rules?

**Comment by drwynn** [comment]
checker:manualTrigger

**Comment by drwynn** [comment]
We have cooperated with 10 SPs, and data transmission takes time, some are sent by copying the hard disk, and some need to be transmitted over the network, so the speed is relatively slow, but we have cooperated with 10 SPs, we respect you, and hope you also respect the facts. 
https://datacapstats.io/clients/f02105063/breakdown
Because the gas is too high, some SP sealing are relatively slow, resulting in an unbalanced quota distribution.

**Comment by a1991car** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaptvv234komkjqumop4imsaw7xbygu26vzdc3ur2qf4dr745jeme 
#### Address 
> f1ml4u3hlf53zvq6yuvageowz57lrxgeol24k7ubq
#### Datacap Allocated
> 1.17PiB
#### Signer Address
> f1qnumecdypgrbaebtkdfjnwt5ndacadcuas3deiq
#### Id
> f67f990a-2fc9-4d9b-9c97-380d86369834
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaptvv234komkjqumop4imsaw7xbygu26vzdc3ur2qf4dr745jeme

**Comment by a1991car** [comment]
Reason for signing:

First, it is shown here that indeed 10 SPs have cooperated. So the allegation of self-dealing fails.
<img width="1233" alt="WX20230708-115043@2x" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/32447611/8e12464c-f611-48da-ab53-d3b1aa136376">

Second, the bot tell  SPs are distributed in different regions. 
<img width="1006" alt="WX20230708-115211@2x" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/32447611/da207e46-9420-4e27-b2d9-0336fc823a3c">

I keep an eye on specific trends

**Comment by Chuangshi1** [comment]
The customer contacted me and promised to improve. Considering that the customer cooperated with 10 sps and the data delay, I decided to support this round and continue to observe its performance. If the client does not improve, I will unsign and will not sign this LDN in the future.

**Comment by Chuangshi1** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecfbaaxwovdsebywcnp3zw4lnif7pycgejc54ret3ltkzj6lbjnkm 
#### Address 
> f1ml4u3hlf53zvq6yuvageowz57lrxgeol24k7ubq
#### Datacap Allocated
> 1.17PiB
#### Signer Address
> f1mdk7s2vntzm6hu35yuo6vjubtrpfnb2awhgvrri
#### Id
> f67f990a-2fc9-4d9b-9c97-380d86369834
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecfbaaxwovdsebywcnp3zw4lnif7pycgejc54ret3ltkzj6lbjnkm

**Comment by fdate11** [comment]
checker:manualTrigger

**Comment by drwynn** [comment]
Dear officials, respected notaries, and community members, thank you for your attention and help. We have already responded to the sudden accusation. If your doubts have not been fully resolved, I will reply in more detail below.

1. Regarding the use of ipfsfy.com pointed out by community members, we have already responded in detail. This website cannot be opened. So far, we still don’t know what this website does. However, we can be 100% sure, and it is currently displayed on the check The nodes of are affiliated to three companies.

f02217442, f02217602: Shenzhen God operator cloud storage company
f01435542: Tao Taoyun
f02101475: Lemon computing power

As for why the three nodes all display "ipfsfy.com", in order to answer this question, please allow me to "make a metaphor".

For example, 5,000 companies around the world choose to store their data in AWS. This only shows that the price, brand promotion, and service of AWS are very good, not that all of these 5,000 companies belong to one group.

2. We have indeed cooperated with 10 SPS. If you really think that some of the SPs we cooperate with do not comply with the FIL+ policy, we can not cooperate with these SPs.  why would we can to do this? Because we want to prove that we are not "self-dealing".

3. Language is sometimes very pale, especially in front of actions. So, let's calm down and wait for 3 days to see the latest results.

**Comment by psh0691** [comment]
checker:manualTrigger

**Comment by psh0691** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedcimhvr2ajrpmrea4tmprvej3bsngh37qtiknoh342veb6lzj5gg 
#### Address 
> f1ml4u3hlf53zvq6yuvageowz57lrxgeol24k7ubq
#### Datacap Allocated
> 1.17PiB
#### Signer Address
> f1qdko4jg25vo35qmyvcrw4ak4fmuu3f5rif2kc7i
#### Id
> f67f990a-2fc9-4d9b-9c97-380d86369834
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedcimhvr2ajrpmrea4tmprvej3bsngh37qtiknoh342veb6lzj5gg

**Comment by NDLABS-Leo** [comment]
According to the current community consensus retrieval rates greater than 1% are considered credible, this report has a retrieval rate greater than 20%, and the data storage is adjusting for the better from past reports. So willing to consider it a credible customer.

**Comment by NDLABS-Leo** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedxmh4ejn3tlx3256rjxhvafymsrkjzdyogl5bpe57kd3yylrlj36 
#### Address 
> f1ml4u3hlf53zvq6yuvageowz57lrxgeol24k7ubq
#### Datacap Allocated
> 1.17PiB
#### Signer Address
> f1yayfsv6whu3rheviucvventj3y6t542xfpb47ei
#### Id
> f67f990a-2fc9-4d9b-9c97-380d86369834
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedxmh4ejn3tlx3256rjxhvafymsrkjzdyogl5bpe57kd3yylrlj36

**Comment by Filplus-govteam** [comment]
checker:manualTrigger

**Comment by Aaron01230** [comment]
checker:manualTrigger

**Comment by Filplus-govteam** [comment]
Hello @drwynn per the https://github.com/filecoin-project/notary-governance/issues/922 for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

This information will be reviewed by Fil+ Governance team to confirm validity and then the application will be approved for future notary review. Let us know if you have any questions.
