### ISSUE TITLE
[DataCap Application] VIDTOO TECHNOLOGY (HONGKONG) CO., LIMITED 

### ISSUE THREAD

**Issue by IzzyLay** [filecoin-project/filecoin-plus-large-datasets#178]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: VIDTOO TECHNOLOGY (HONGKONG) CO., LIMITED 
- Website / Social Media: Twitter：@VIDTOO Tech
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5 PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100TiB
- On-chain address for first allocation: f1ize4dtdnqy3tgykhmuhbzcozip6f4epffy6qlrq

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
VIDTOO is a Fabless integrated circuit chip design company and product solution provider. VIDTOO is committed to the development of high computing power, high bandwidth, decentralized product application chips and solutions.
VIDTOO has been authorized to use a number of international patents, covering China, Taiwan, Europe, the United States and other regions. Our team has successfully taped out more than 30 projects, and the FAB process covers TSMC, SMIC, UMC2, and GSMC.
It was the world's first fully-fitting ultra-high-definition autostereoscopy in mass production. Our technology and products represented the highest level in the same field in the world at that time.
```

What is the primary source of funding for this project?
```
Revenue from the company’s business
```

What other projects/ecosystem stakeholders is this project associated with?
```
3D industry chain such as 3D shooting, intelligent image processing, 3D modeling, etc.
```

## Use-case details

Describe the data being stored onto Filecoin
```
 The images, materials, videos, and pictures we process are all publicly available
```

Where was the data in this dataset sourced from?
```
The company’s public database. And the public media content of the business output
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://drive.google.com/file/d/1tXRJJQ7pc7-7bWneOlSGb9oB-M7F8x40/view?usp=sharing
https://drive.google.com/file/d/1VpoVqeIcF0dhI39Wj0DjPcAnyzXT-cZn/view?usp=sharing
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
The data we store here is publicly accessible
```

What is the expected retrieval frequency for this data?
```
Not sure if there is a fixed retrieval frequency
```

For how long do you plan to keep this dataset stored on Filecoin?
```
According to our needs, we hope to store it for as long as possible
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Hong Kong, Singapore，US
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Not sure yet, I prefer to transfer online
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We will select high-quality miners for trading.
```

How will you be distributing deals across storage providers?
```
Strive for equal distribution, good miners may have priority
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
YES,we do. 
Hope we cooperate happily
```

**Comment by KwrayFF** [comment]
Hi @IzzyLay 

Thanks for applying. I'm with the Filecoin Foundation and here to review this application for accuracy and authenticity. Have a few questions to help get this processed for you.

I'd like to find out more about the legitimate work you are doing, but not seeing much in terms of reference this request. Can you please share
1. Working company website 
2. Social Media Presence links (if available)
3. Someone from your company with a Github handle older than 7 days.

Thank you

**Comment by dkkapur** [comment]
Closing this one out for inactivity. @IzzyLay please re-open if still relevant.

**Comment by IzzyLay** [comment]
@Kevin-FF-USA  @dkkapur   Sorry for replying late! Here it is  Website：http://ndlabs.web.97jindianzi.com/vip_ndlabs.html         Twitter：VIDTOO Tech，@Jennife11718359

**Comment by IzzyLay** [comment]
@dkkapur @Kevin-FF-USA What can we do to push the progress?

**Comment by IzzyLay** [comment]
Hi, @dkkapur @Kevin-FF-USA, any update?
