### ISSUE TITLE
[DataCap Application] FileGuard - Common Voice Datasets

### ISSUE THREAD

**Issue by cryptomandy** [filecoin-project/filecoin-plus-large-datasets#1780]
### Data Owner Name

Mozilla

### Data Owner Country/Region

United States

### Data Owner Industry

IT & Technology Services

### Website

https://commonvoice.mozilla.org/

### Social Media

```text
N/A
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

600TiB

### On-chain address for first allocation

f1odf5h4nrd3dscjyh5xn6uycmgnjiwzmyxg72mfa

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
As a machine learning & deep learning training data provider, FileGuard provide a complete data solution of "software + hardware", Help algorithm companies collect and check data. A complete set of solutions for cleaning, desensitization, labeling, storing, transfer, etc. FileGuard have served more than 30 artificial intelligence enterprise customers since 2018, suce as Face++, SenseTime, JD finance and so on, providing customers with more than 20 million image annotation data, and about 200,000 crowdsourcers working on the FileGuard platform.

As a platform all in Web3, We have been engaged with storing real and valuable machine learning & deep learning datasets on the Filecoin network. We focus on the three areas of artificial intelligence: computer vision(CV), natural language processing(NLP) and speech processing. We believe that the Web3 way of storing these valuable data, such as autonomous driving, cancer, disease, geographic, agriculture, speech, and NLP data, will bring huge changes.

We will continue to explore more high-quality datasets to serve our customers. In the fields of atmospheric research, energy research, and celestial body research, machine learning & deep learning will also play an increasingly important role.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
Mozilla Common Voice is an open source, multi-language dataset of voices that anyone can use to train speech-enabled applications, powered by the voices of volunteer contributors around the world. People who want to build voice applications can use the dataset to train machine learning models.

At present, most voice datasets are owned by companies, which stifles innovation. Voice datasets also underrepresent: non-English speakers, people of colour, disabled people, women and LGBTQIA+ people. This means that voice-enabled technology doesn’t work at all for many languages, and where it does work, it may not perform equally well for everyone. We want to change that by mobilising people everywhere to share their voice.

We believe that large, publicly available voice datasets will foster innovation and healthy commercial competition in machine-learning based speech technology. Common Voice’s multi-language dataset is already the largest publicly available voice dataset of its kind.

The dataset currently consists of 17,127 validated hours in 104 languages. Each entry in the dataset consists of a unique MP3 and corresponding text file. Many of the 26,119 recorded hours in the dataset also include demographic metadata like age, sex, and accent that can help train the accuracy of speech recognition engines.
```

### Where was the data currently stored in this dataset sourced from

Other

### If you answered "Other" in the previous question, enter the details here

```text
https://commonvoice.mozilla.org
```

### How do you plan to prepare the dataset

singularity, graphsplit

### Please share a sample of the data

```text
https://commonvoice.mozilla.org/en/datasets
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

1.5 to 2 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, Europe

### How will you be distributing your data to storage providers

Cloud storage (i.e. S3), HTTP or FTP server

### How do you plan to choose storage providers

Slack, Partners

### If you already have a list of storage providers to work with, fill out their names and provider IDs below

```text
| MinerID   | City       | Continent | Business/Entity |
| --------- | ---------- | --------- | --------- |
| f01824405 | ChengDu    | CN        | RY        |
| f01991416 | HongKong   | CN        | RIKIMARU  |
| f02012032 | HongKong   | CN        | RIKIMARU  |
| f02006691 | HongKong   | CN        | NIHICHE   |
| f02014107 | Seoul      | KR        | HMT       |
| f02027952 | London     | UK        | Mochi     |
| f02028326 | California | USA       | Fyii      |
| f01518369 | California | USA       | Megalayer |
| f01889668 | California | USA       |           |
```

### How do you plan to make deals to your storage providers

Boost client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 5PiB

**Expected weekly DataCap usage rate**
> 600TiB

**Client address**
>f1odf5h4nrd3dscjyh5xn6uycmgnjiwzmyxg72mfa

**Comment by cryptomandy** [comment]
@raghavrmadya @Kevin-FF-USA @Sunnyiscoming Hello, Sir, it seems that the bot gave incorrect labels and status, could you please help me to repair it? Thanks a lot.

**Comment by woshidama323** [comment]
checker:manualTrigger

**Comment by igoovo** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebac6cwt7psv7odtnnfwohzz455z6ptxct77wtjmsxroz5w46fgya 
#### Address 
> f1odf5h4nrd3dscjyh5xn6uycmgnjiwzmyxg72mfa
#### Datacap Allocated
> 256.00TiB
#### Signer Address
> f1shnsfayxqll77svffaxnjenms7bbbysbqcatrpy
#### Id
> 709da67b-597e-451b-a55c-a609635a2cb5
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebac6cwt7psv7odtnnfwohzz455z6ptxct77wtjmsxroz5w46fgya

**Comment by igoovo** [comment]
First round support.

**Comment by cryptomandy** [comment]
checker:manualTrigger

**Comment by spaceT9** [comment]
checker:manualTrigger

**Comment by cryptomandy** [comment]
checker:manualTrigger

**Comment by kevzak** [comment]
checker:manualTrigger

**Comment by kevzak** [comment]
@cryptomandy hello - what is the status of this application. You received DataCap 3 months ago.

Looks like you haven't used any.

**Comment by kevzak** [comment]
Also we have a new, optional KYC ID check available on [filplus.storage](https://filplus.storage/). If you want to add additional layer of trust you can complete an ID check and verify this GitHub account. See details: [LINK](https://medium.com/filecoin-plus/implementation-of-a-third-party-kyc-id-check-for-fil-applicants-e5e825b1484e)

**Comment by cryptomandy** [comment]
> @cryptomandy hello - what is the status of this application? You received DataCap 3 months ago. Looks like you haven't used any.
> 
> What is your role with this dataset? Are you preparing the data? If yes, how are you preparing the dataset and sending?
> 
> How did you find SP entities mentioned above?

@kevzak Hello,  Thanks for your attention.

Yes, we are preparing the data using singularity. We haven't started this dataset for so long, that's because we need to download a lot of small mp3 files, and the download process is very very slow, but we have completed most of the work now, and the dataset is expected to be started in the next 1 or 2 weeks.

We found these SPs from Slack and our partners.

**Comment by cryptomandy** [comment]
checker:manualTrigger

**Comment by cryptomandy** [comment]
checker:manualTrigger

**Comment by cryptomandy** [comment]
checker:manualTrigger

**Comment by cryptomandy** [comment]
checker:manualTrigger

**Comment by cryptomandy** [comment]
checker:manualTrigger

**Comment by cryptomandy** [comment]
checker:manualTrigger

**Comment by cryptomandy** [comment]
checker:manualTrigger

**Comment by cryptomandy** [comment]
checker:manualTrigger

**Comment by cryptomandy** [comment]
checker:manualTrigger
