### ISSUE TITLE
[DataCap Application] <Beijing Hatd Academy of Traditional Chinese Medicine> - <Healthy classroom>

### ISSUE THREAD

**Issue by licornduan** [filecoin-project/filecoin-plus-large-datasets#1794]
### Data Owner Name

Beijing Hatd Academy of Traditional Chinese Medicine

### Data Owner Country/Region

China

### Data Owner Industry

Information, Media & Telecommunications

### Website

http://www.beijingfude.com/

### Social Media

```text
Beijing Hatde Academy of Traditional Chinese Medicine was officially established in 2016 and is located in Beijing. The institute is committed to training more professionals with professional health care skills to serve the society, so that they can apply what they have learned. It has built a one-stop technical training service system to provide them with more business and employment opportunities. Mr. Zhang Qiao, the director of the research Institute, has developed a series of pure manipulation of health conditioning technology over the years, and trained a large number of professional health conditioning technology talents, which spread throughout the country in large, medium and small cities and regions, helping hundreds of thousands of people to relieve physical and mental pain every year.
```

### Total amount of DataCap being requested

500TiB

### Weekly allocation of DataCap requested

10TiB

### On-chain address for first allocation

f12mhwvszjzpgu7bya5fjjtlnsnzfdgy7oamccncy

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Beijing Hatde Academy of Traditional Chinese Medicine was officially established in 2016 and is located in Beijing. The institute is committed to training more professionals with professional health care skills to serve the society, so that they can apply what they have learned. It has built a one-stop technical training service system to provide them with more business and employment opportunities. Mr. Zhang Qiao, the director of the research Institute, has developed a series of pure manipulation of health conditioning technology over the years, and trained a large number of professional health conditioning technology talents, which spread throughout the country in large, medium and small cities and regions, helping hundreds of thousands of people to relieve physical and mental pain every year.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
online &  offline
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### How do you plan to prepare the dataset

lotus

### Please share a sample of the data

```text
bafykbzacediffodt6kwrxzwaj5oy5nou46hj6k5a65m7wzg4jpvvqnt52zjcm
bafykbzaceagzzloxpytf7eas7dj4muj5sp4io3b2juvw25g3p2cdejdnak644
bafykbzaceaf647ol4muhvq4sgrqkvji46nrmef5rmqdqvqxmibgxicg6pyewi
bafykbzacecrydujskay4lenkuiyvlgukyjq4jpo4mgwnwz6ckuevi7t6s2rwe
bafykbzaceazgw6xbiq7lagjrmy5nwchjbvb5firrh2eclbfm6gvfva5qit6o4
bafykbzaceaxr42tlgiai77kogu7ucooibfm4a4vf6tjvgfycssjdazyaguzgc


All mp4 format
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Weekly

### For how long do you plan to keep this dataset stored on Filecoin

Less than 1 year

### In which geographies do you plan on making storage deals

Greater China

### How will you be distributing your data to storage providers

HTTP or FTP server, IPFS, Lotus built-in data transfer

### How do you plan to choose storage providers

Partners

### How do you plan to make deals to your storage providers

Boost client, Lotus client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
Describe the data being stored onto Filecoin
online &  offline

Can you describe the data you will store, such as data type, data source, etc.

**Comment by licornduan** [comment]
It mainly uses video data, including teaching videos of doctors, on-site video collection data (service quality and improvement), activity communication, etc

**Comment by licornduan** [comment]
@Sunnyiscoming

**Comment by Sunnyiscoming** [comment]
Can you provide more data samples to prove that you have 500 TB data already?

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Looking at your application i have some questions:
As you are brand new on Github and have no history of past applications it seems to me that applying for 500 TB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?

Can you show us visible proof of the size of your data and the storage systems you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230337462961356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Looking at your application i have some questions:
As you are brand new on Github and have no history of past applications it seems to me that applying for 5PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?

Can you show us visible proof of the size of your data and the storage systems you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230337462961356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!

**Comment by licornduan** [comment]
Data Root CID

bafyaa6qsgafcmalqudsaeienxzt36yiwzofdgtmpilrvtexbztibafbqsa2bodhnft7g7zp42ajaagelucbyabasgafcmalqudsaeigkcmympkwta4h4veies3kq2mg5ytiot7j77oe5uzawvztcpd776ajaaggh66wpkaykcqeaegea4cu7kbzaqcaibaaeecaobkpvam

bafyaa6qsgafcmalqudsaeihlmzfkpsnuai6txljjxzerpz7p42v5kgkdnnv6yncznobuppetvqjaagelucbyabasgafcmalqudsaeicmornhra4desubecxd6hpkxxp7xbvkrynchukknwoeddyg7rtlzijaaghlvhwiwaqkcqeaegea2dviwbraqcaibaaeecanb2ulai

bafyaa6qsgafcmalqudsaeiewfsmrksjxuevaal7s47ktxmw4bo3pxcbsmam2j7xm26psylhodejaagelucbyabasgafcmalqudsaeig2zcyqfblcjfdu37kuclkd7j6ed5ufbdb3xhziyacjwz2olibuaqjaagghy6x7kaykcqeaegeawcwpkbzaqcaibaaeecalblhvam

bafyaa6qsgafcmalqudsaeigc3zyhswdh2z734q7hqfey5vqmbucpxgjt2g7df5lwdj7nq6m24ijaagelucbyabasgafcmalqudsaeicfnqy2lukc3q6obmajpfwtp54aez22phblbnfipldovsp5ausp2yjaagety777iaykcqeaegeawd6pibzaqcaibaaeecalb7huam

bafyaa6asgafcmalqudsaeibm5plz2ihhfhoutbqp2d34p727wd2ocgrwlzglob26s7z5a2omeyjaagelucbyabasf4fcmalqudsaeiauk3sga7stlf3o7nv4qc4i76bruvstq72qilcuro5ag46obqmhb4jaagfj7tveucqtbabbrj575lfaiieaqcaiabbau676usq

bafykbzacecgchvdrnjkzlcb4cjoomtlg7wn5jclvuma4njaxsi5h2ahdt4z4s

bafyaa6qsgafcmalqudsaeiewfsmrksjxuevaal7s47ktxmw4bo3pxcbsmam2j7xm26psylhodejaagelucbyabasgafcmalqudsaeig2zcyqfblcjfdu37kuclkd7j6ed5ufbdb3xhziyacjwz2olibuaqjaagghy6x7kaykcqeaegeawcwpkbzaqcaibaaeecalblhvam

bafyaa6qsgafcmalqudsaeigc3zyhswdh2z734q7hqfey5vqmbucpxgjt2g7df5lwdj7nq6m24ijaagelucbyabasgafcmalqudsaeicfnqy2lukc3q6obmajpfwtp54aez22phblbnfipldovsp5ausp2yjaagety777iaykcqeaegeawd6pibzaqcaibaaeecalb7huam

bafyaa6qsgafcmalqudsaeihlmzfkpsnuai6txljjxzerpz7p42v5kgkdnnv6yncznobuppetvqjaagelucbyabasgafcmalqudsaeicmornhra4desubecxd6hpkxxp7xbvkrynchukknwoeddyg7rtlzijaaghlvhwiwaqkcqeaegea2dviwbraqcaibaaeecanb2ulai

bafyaa6asgafcmalqudsaeifcllfcbqzf54fhiip3u74e5fs6kkmtuqo5f4m3kbcxr4sflw2foijaagelucbyabasf4fcmalqudsaeifuhgtlyam5fn73c3pvbovlao7yitvuzdd4ykf6ouk4ctufkwrpoejaagfcy6fcycqtbabbrbfdrkwaiieaqcaiabbaqsryula

bafyaa6asgafcmalqudsaeig2qxy3rvxl5c22sb45eymiztua7xf3nc6vcqxfugk3bhz3lxj7wijaagelucbyabasf4fcmalqudsaeicjbybyjjzlzd57axsexpr5fmmckkkw63o6zazw5vruisearirthyjaagedqx5eecqtbabbrqoo7hbaiieaqcaiabbayhhpsqq

bafyaa6asgafcmalqudsaeiazq726sjg7fxlrjqrehbs6d3qucloqycuk4enq6sqbhclzczu5qijaagelucbyabasf4fcmalqudsaeihqidr5hozeshrlhcjoypjzxheti4km7whztpytjnw3vfw6ezp64ijaaghzypzgycqtbabbrj7l6hwaiieaqcaiabbau7v7c3a

lotus client import
lotus client deal


@Sunnyiscoming
@cryptowhizzard


Sorry, I leaked node information in the last two days due to my application, so the test node of SP was flooded by non-DC orders. Please check the CID information and I will try my best to ensure that it is available.

Version upgrade causes me to submit several failed boost client

**Comment by Sunnyiscoming** [comment]
Can you provide files of data samples directly?

**Comment by licornduan** [comment]
链接: https://pan.baidu.com/s/1oUy1BxZFW7TBhboLi2nMXQ 提取码: 8j1a 复制这段内容后打开百度网盘手机App，操作更方便哦 
--来自百度网盘超级会员v1的分享

@Sunnyiscoming

**Comment by licornduan** [comment]
Can someone handle my request?

@cryptowhizzard @galen-mcandrew @raghavrmadya @Kevin-FF-USA

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 500TiB

**Expected weekly DataCap usage rate**
> 10TiB

**Client address**
>f12mhwvszjzpgu7bya5fjjtlnsnzfdgy7oamccncy

**Comment by licornduan** [comment]
<img width="644" alt="image" src="https://user-images.githubusercontent.com/19664671/226789915-6c1b751a-64a8-4ae1-9e45-2af2bb981e7c.png">

Need to wait for how long?

@cryptowhizzard @galen-mcandrew @raghavrmadya @Kevin-FF-USA

**Comment by jomozz** [comment]
> 链接: https://pan.baidu.com/s/1oUy1BxZFW7TBhboLi2nMXQ 提取码: 8j1a 复制这段内容后打开百度网盘手机App，操作更方便哦 --来自百度网盘超级会员v1的分享
> 
> @Sunnyiscoming

@licornduan The link has expired, can you repost it? If we pass the inspection, we will support.

**Comment by scdpnh** [comment]
Thank you very much for your support. I thank you for your support on behalf of our customers

https://drive.google.com/drive/folders/1hZLHW7gGHRNVbcoNr4TxJjaQ4Zu1T1UB?usp=sharing

@jomozz

**Comment by licornduan** [comment]
https://drive.google.com/drive/folders/1hZLHW7gGHRNVbcoNr4TxJjaQ4Zu1T1UB?usp=share_link


@jomozz

**Comment by jomozz** [comment]
> https://drive.google.com/drive/folders/1hZLHW7gGHRNVbcoNr4TxJjaQ4Zu1T1UB?usp=share_link
> 
> @jomozz

@licornduan Any update? I requested permission to access, but was never granted.

**Comment by licornduan** [comment]
https://drive.google.com/drive/folders/1hZLHW7gGHRNVbcoNr4TxJjaQ4Zu1T1UB?usp=sharing
Sorry, it's my problem, didn't say share Settings for anyone.

@jomozz

**Comment by licornduan** [comment]
checker:manualTrigger

**Comment by licornduan** [comment]
checker:manualTrigger f1sm4vru5k3jnbg4me7ymo2r2zc3fqc2pu57tuijq   f3r5wyvf4nhgbuk72wmvheju5uhur4ifatnorqpkzans2gwup6ehxvzmbie2mtmshdggukaxyekzmgttcqsraa

**Comment by licornduan** [comment]
checker:manualTrigger  f12mhwvszjzpgu7bya5fjjtlnsnzfdgy7oamccncy

**Comment by licornduan** [comment]
@jomozz @Sunnyiscoming 


What causes the second case?


⚠️ CID sharing has been observed. (Top 3)

6.00 MiB - [f1sm4vru5k3jnbg4me7ymo2r2zc3fqc2pu57tuijq](https://filfox.info/en/address/f1sm4vru5k3jnbg4me7ymo2r2zc3fqc2pu57tuijq) - Glif auto verified
2.00 MiB - f3r5wyvf4nhgbuk72wmvheju5uhur4ifatnorqpkz
ans2gwup6ehxvzmbie2mtmshdggukaxyekzmgttcq
sraa - https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/147

**Comment by licornduan** [comment]
@jomozz 

Dear notary, CID sharing occurs after I self-check the submitted data order. How can I locate the shared CID and clean it?

**Comment by licornduan** [comment]
checker:manualTrigger f12mhwvszjzpgu7bya5fjjtlnsnzfdgy7oamccncy

**Comment by licornduan** [comment]
checker:manualTrigger f12mhwvszjzpgu7bya5fjjtlnsnzfdgy7oamccncy

**Comment by licornduan** [comment]
checker:manualTrigger f12mhwvszjzpgu7bya5fjjtlnsnzfdgy7oamccncy

**Comment by licornduan** [comment]
checker:manualTrigger  f3rtnwp4ojvpchhexk7i2d5jeytgsellsaeu2a3nf
zyms7oplmfvxeaunbdr7eskxkk3eyggm265kg2h4o
ibuq

**Comment by licornduan** [comment]
checker:manualTrigger f3rtnwp4ojvpchhexk7i2d5jeytgsellsaeu2a3nfzyms7oplmfvxeaunbdr7eskxkk3eyggm265kg2h4oibuq

**Comment by licornduan** [comment]
checker:manualTrigger f12mhwvszjzpgu7bya5fjjtlnsnzfdgy7oamccncy

**Comment by licornduan** [comment]
@jomozz 

f3 adds f3rtnwp4ojvpchhexk7i2d5jeytgsellsaeu2a3nfzyms7oplmfvxeaunbdr7eskxkk3eyggm265kg2h4oibuq

This address is our test address.

The data sample is encapsulated by the test node for submission review. In order to find out the problem of CID shared by the other two addresses, we specially encapsulated the sample data in one node submission.

**Comment by licornduan** [comment]
@Sunnyiscoming 

Is there a notary public who can help me? Are there tools available to troubleshoot problems? Or do you have to figure it out?

**Comment by licornduan** [comment]
For the duplicate data submitted by the customer, we have done MD5 check. The duplicate orders will be skipped and the problem points will be checked manually for manual processing.

**Comment by licornduan** [comment]
@cryptowhizzard 


Dear notary, can you help me？

**Comment by licornduan** [comment]
checker:manualTrigger

**Comment by licornduan** [comment]
checker:manualTrigger

**Comment by licornduan** [comment]
checker:manualTrigger

**Comment by licornduan** [comment]
checker:manualTrigger

**Comment by licornduan** [comment]
checker:manualTrigger

**Comment by licornduan** [comment]
@cryptowhizzard 

https://filfox.info/zh/message/bafy2bzacebhadnihitquzgbnkocwalv7rqdyu2o7h3qkt6prstngyxz3a6zoc

The sample sector of data used by the test address expired

**Comment by licornduan** [comment]
checker:manualTrigger

**Comment by licornduan** [comment]
All the data are given by the customer. The problems of 2mb and 6mb May be caused by md5 checksum failure. As for the newly generated 184mb, we have to find a problem by encapsulating the historical sample of the test node to the specified node.

**Comment by licornduan** [comment]
checker:manualTrigger

**Comment by licornduan** [comment]
checker:manualTrigger

**Comment by licornduan** [comment]
checker:manualTrigger

**Comment by licornduan** [comment]
@Sunnyiscoming 


Can someone help me？

**Comment by caoyoungyoung** [comment]
CID report need to be improved before next tranche approval

**Comment by licornduan** [comment]
@caoyoungyoung 

Thank you for your reply. I know it needs to be improved. The first thing that needs to be improved is that I no longer have datacap quota. Second improvement: what about the issue of shared CID?

**Comment by licornduan** [comment]
checker:manualTrigger

**Comment by licornduan** [comment]
@caoyoungyoung 

I have finished the sector in the test address, but the CID report does not change, do I need to delete the physical files in this sector?

**Comment by zcfil** [comment]
checker:manualTrigger

**Comment by licornduan** [comment]
checker:manualTrigger

**Comment by licornduan** [comment]
@zcfil help me.

**Comment by licornduan** [comment]
@Sunnyiscoming 

Can you give a reply to the notary for processing?

For example, notary can continue to operate

**Comment by licornduan** [comment]
@Sunnyiscoming 

Hello, there is no notary to help me solve the problems in the data encapsulation process, and the notary is reluctant to sign an application that violates the rules, even if it is only 2mb.

Can the check tool output the CID value of the shared data? Let me check the contents of this CID file.

**Comment by licornduan** [comment]
Q1:
184.00 MiB - f3rtnwp4ojvpchhexk7i2d5jeytgsellsaeu2a3nfzyms7oplmfvxeaunbdr7eskxkk3eyggm265kg2h4oibuq - Glif auto verified
A1:Own test address, encapsulated data has been terminated.

Q2:
6.00 MiB - [f1sm4vru5k3jnbg4me7ymo2r2zc3fqc2pu57tuijq]
2.00 MiB - f3r5wyvf4nhgbuk72wmvheju5uhur4ifatnorqpkzans2gwup6ehxvzmbie2mtmshdggukaxyekzmgttcqsraa

A2:
Is not my customer address，The inspector is required to provide a data cid or a piece cid

Q3:

⚠️ 100.00% of deals are for data replicated across less than 4 storage providers.

A3:

It takes some datacap to fix this problem.

**Comment by licornduan** [comment]
@cryptowhizzard @zcfil 

Dear Notary, please help me move my project forward

**Comment by cryptowhizzard** [comment]
Good morning,

I have been investigating f0509062. It has it location set in France on Amazon AWS.
I investigate because the rest of your SP's are all in China / HK. I have reason to believe that this SP is also in China and the AWS is solely for VPN purpose to hide it's location. The reason is below.

I can't sign a further allocation since this is against FIL+ rules and guidelines.

I have basically 3 questions:

1:) Who is the owner of f0509062
2:) Why did they choose to work this way.
3:) Are you still interested in moving this forward where this means you need to geographically distribute to SP's who have their physical locaion outside China / HK.

-----------------------------------

Digging a bit in their blockchain behaviour i noticed this message from f0509062:
https://filfox.info/en/message/bafy2bzacecso4pqhcgqg7ustckx7s2ey7cxe5xynjj36l4rvt2h5kubt3niec

Converting this base 64 (0x04b2ece98606092c) according to https://github.com/multiformats/multiaddr/blob/master/protocols.csv gives:

04 = TCP
b2 = 178
ec = 236
e9 = 233
86 = 134
06: tcp (protocol code)
092c = 2348

Conclusion, the past address was IP4 178.236.233.134 , port 2348

looking this up in the RIPE database it gives:
inetnum:        178.236.233.0 - 178.236.233.255
netname:        Agotoz_HK_Limited
country:        DE
admin-c:        LDC282-RIPE
tech-c:         LDC282-RIPE
status:         ASSIGNED PA
mnt-by:         SC-INNOVATION-MNT
mnt-by:         hk-larus-1-mnt
mnt-by:         OH-MNT
created:        2017-11-07T12:01:01Z
last-modified:  2021-01-28T10:06:34Z
source:         RIPE

role:           Larus DB contacts
address:        Flat A3,11/F,TML Tower, No.3 Hoi Shing Road,Tsuen Wan, HKSAR
admin-c:        DH6786-RIPE
nic-hdl:        LDC282-RIPE
mnt-by:         hk-larus-1-mnt
created:        2017-08-28T04:04:01Z
last-modified:  2023-05-30T03:20:29Z
source:         RIPE # Filtered

**Comment by licornduan** [comment]
Ok, I'll contact the SP service provider and ask him to reply as soon as possible.

@cryptowhizzard

**Comment by licornduan** [comment]
@cryptowhizzard 


The reply from SP service provider is: our business needs, SP opened an international dedicated line to provide data retrieval needs, due to the problem of the network provider, which can not be recovered at present, providing Amazon's ECS host deployment boost node to provide retrieval services.

Do solutions or temporary solutions using international lines comply with the rules?

**Comment by licornduan** [comment]
@cryptowhizzard


I contacted my service provider to get me a new sp node, or a reliable European node.

**Comment by cryptowhizzard** [comment]
I suggest to take this application under umbrella of Notary governance #922 to see how / we can proceed forward.

**Comment by Filplus-govteam** [comment]
Hello @licornduan  Per the https://github.com/filecoin-project/notary-governance/issues/922 for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

This information will be reviewed by Fil+ Governance team to confirm validity and then the application will open for notary review. Let us know if you have any questions.

**Comment by licornduan** [comment]
@cryptowhizzard @Filplus-govteam 

Thank you very much for the notary's help. I am communicating with the technical support.

**Comment by zcfil** [comment]
Hi @licornduan 
Firstly, the number of copies you store is too small, at least greater than 4. Secondly, what is the issue with your CID share?

**Comment by licornduan** [comment]
@zcfil 

SP is easier to find,
CID shared data can not be found which CID overlaps with others, this is more troublesome, do you have a query channel?

**Comment by licornduan** [comment]
@zcfil 

Dear notary, has my application been closed?
