### ISSUE TITLE
[DataCap Application] Fuzhou FrogHub Technology Co. , Ltd.

### ISSUE THREAD

**Issue by FroghubMan** [filecoin-project/filecoin-plus-large-datasets#1796]
### Data Owner Name
Fuzhou FrogHub Technology Co. , Ltd.

### Data Owner Country/Region
China

### Data Owner Industry
Web3 / Crypto

### Website
[https://froghub.io/](https://froghub.io/)

### Social Media
@froghub_io (Twitter)

### Total amount of DataCap being requested
5 PiB

### Weekly allocation of DataCap requested
500 TiB

### On-chain address for first allocation
f1lugk5dlpx23vexq7lounl3gglyprskc67n3722q

### Custom multisig
- [X] Use Custom Multisig

### Identifier
efil

### Share a brief history of your project and organization
FrogHubweb3web3web2web3 20web3.0

https://www.froghub.io/
Githubhttps://github.com/froghub-io

FrogFile  BucketsKey Management Service(KMS)IPFS Gateway

### Is this project associated with other projects/ecosystem stakeholders?
No

### Describe the data being stored onto Filecoin
private data

### Where was the data currently stored in this dataset sourced from
My own storage infra

### How do you plan to prepare the dataset
IPFS

### Please share a sample of the data
This is private data that belongs to the user.

### Confirm that this is a public dataset that can be retrieved by anyone on the Network
No

### If you chose not to confirm, what was the reason
This is private data that belongs to the user.

### What is the expected retrieval frequency for this data
Monthly

### For how long do you plan to keep this dataset stored on Filecoin
More than 3 years

### In which geographies do you plan on making storage deals
Greater China

### How will you be distributing your data to storage providers
Shipping hard drives

### How do you plan to choose SP
Slack

### How do you plan to make deals to your storage providers
Singularity

### Can you confirm that you will follow the Fil+ guideline
Yes

**Comment by caoyoungyoung** [comment]
private data should be E-Fil+ project @kevzak

**Comment by kevzak** [comment]
@FroghubMan this application needs more specific SP details to move forward. 

Here is an example of what detail is expected for a private dataset application: https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1679#issuecomment-1480729063

**Comment by FroghubMan** [comment]
Hi @kevzak ,Sps are folowing:
f02051391	/	China/HongKong	/	RuiShicheng Technology
f01153105	/	Japan/Tokyo		/	MineWorld Technology
f01949267	/	China/Fuzhou	/	Dinosaur-world Technology
f01708981	/	China/ShenZhen 	/	RuiShicheng Technology
1Pib datacap already. Plan to store 5-8 copies, and I will leave messages when there are new SPs.

**Comment by kevzak** [comment]
I can confirm that @FroghubMan has successfully completed the KYC/KYB check via Synaps third party. Let's trigger the application for notary review.

**Comment by kevzak** [comment]
## Datacap Request Trigger
#### Total DataCap requested 
> 5PiB
#### Expected weekly DataCap usage rate 
> 500TiB
#### Client address
> f1lugk5dlpx23vexq7lounl3gglyprskc67n3722q

**Comment by kevzak** [comment]
## Datacap Request Trigger
#### Total DataCap requested 
> 5PiB
#### Expected weekly DataCap usage rate 
> 500TiB
#### Client address
>f1lugk5dlpx23vexq7lounl3gglyprskc67n3722q

**Comment by kevzak** [comment]
No work back from @PluskitOfficial 

Let's move forward with the update notary SLA (https://github.com/filecoin-project/notary-governance/discussions/807) and assign randomly:

@carohere
@joss-hua

Please review application details above and note that this applicant passed the KYC/KYB requirements for E-Fil via Synaps.io product. Please comment by April 6th. Thanks!

**Comment by Joss-Hua** [comment]
Unable to confirm possession of the 1PiB data set, please provide as many details as possible on the dataset and its size. any proof.

**Comment by FroghubMan** [comment]
Hi @Joss-Hua, thanks for reviewing.
I took random screenshots of two user datalists from the storage server; hope they serve as proof.
![111211680778719_ pic](https://user-images.githubusercontent.com/88960777/230359008-dd8ab69d-6e83-40b4-b847-b93f65252d26.jpg)
![111221680778719_ pic](https://user-images.githubusercontent.com/88960777/230359029-ea7f4e0a-38ad-40ef-b54c-c77f02b9646e.jpg)

**Comment by Carohere** [comment]
> There are many types of data, including NFT, pictures, files, videos and other resources. This data is undoubtedly the user's.
At present, the data is stored in our hard disk, and there are already nearly 1Pib of user private data. 

To better verify the data size, @FroghubMan can you provide
- a more thorough list of what your organization plans to store, including the exact size of all kinds of data
- proof of 1PiB data hard drive, such as the screenshots you shared above, etc.

**Comment by FroghubMan** [comment]
![113341680862137_ pic](https://user-images.githubusercontent.com/88960777/230590819-7f9beccc-a45b-4b87-a8e3-44f0060e1c1b.jpg)

**Comment by FroghubMan** [comment]
Is that so? @Joss-Hua @Carohere

**Comment by Joss-Hua** [comment]
I can 'propose', but I would like to see an double check at the 'approve' notary. Additionally, I will monitor the development of this project and wish you good luck.

**Comment by Joss-Hua** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb7gqzgw327zga7q52hxlp36q3p5ascuxslkxayc6grq55kmvbjci 
#### Address 
> f1lugk5dlpx23vexq7lounl3gglyprskc67n3722q
#### Datacap Allocated
> 250.00TiB
#### Signer Address
> f1tfg54zzscugttejv336vivknmsnzzmyudp3t7wi
#### Id
> c74a4c01-2a98-4402-84ec-3e1f1d928e3f
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb7gqzgw327zga7q52hxlp36q3p5ascuxslkxayc6grq55kmvbjci

**Comment by Carohere** [comment]
![image](https://user-images.githubusercontent.com/106579285/230838057-02952823-8e29-4d5a-ab62-ef64de6d822c.png)
>Hi @kevzak ,Sps are folowing:
f02051391 / China/HongKong / RuiShicheng Technology
f01153105 / Japan/Tokyo / MineWorld Technology
f01949267 / China/Fuzhou / Dinosaur-world Technology
f01708981 / China/ShenZhen / RuiShicheng Technology
1Pib datacap already. Plan to store 5-8 copies, and I will leave messages when there are new SPs.

FrogHub listed f01153105 in its notary application as token proof. However, here it belongs to “MineWorld Technology”. I don't have enough confidence to sign this app. cc @kevzak

**Comment by kevzak** [comment]
Thanks @Carohere 

@FroghubMan please explain who are MineWorld technology and why they are listed both as an SP for this DataCap application and also on your [Notary application](https://github.com/filecoin-project/notary-governance/issues/640) as one of your Miner IDs?

**Comment by kevzak** [comment]
Notaries please do not sign until we get further explanation, thanks

**Comment by FroghubMan** [comment]
Hi @kevzak , Sorry for the late reply. I just finished Filecoin HK and got back to work. We maintain f01153105 with owner rights. So, f01153105 can't store data for it?

**Comment by FroghubMan** [comment]
In different applications, the information I submit is true and you can trust it.

**Comment by kevzak** [comment]
> Notaries please do not sign until we get further explanation, thanks

Notaries, @FroghubMan replied. Please feel free to engage.

**Comment by Carohere** [comment]
> We maintain the node and have access to it, but the assets of the node is owned by MineWorld. We are partners. In different applications, the information I submit is true and you can trust it.

@FroghubMan it's hard to believe so without any proof. Can you share Mineworld Tecnology's company website, business license or any sort of legal documents?

**Comment by FroghubMan** [comment]
![B7CE83A3-FA46-4957-89C1-626F35D513C8](https://user-images.githubusercontent.com/88960777/232936914-937f4e97-72aa-480f-88c6-639273581192.jpeg)

**Comment by FroghubMan** [comment]
@Carohere Thank you for being responsible 👍!  But we have no reason to cheat for this.  I don't seem to get any benefit 🤣🤣🤣.  If you think this node is not suitable, I can plan to use other sp’s nodes

**Comment by FroghubMan** [comment]
@Carohere This is sensitive information, please check quickly, I will delete it

**Comment by liyunzhi-666** [comment]
Hey @FroghubMan , I checked your application, can you send a sample of the data to my email [yz.li@m.dapponline.io](mailto:yz.li@m.dapponline.io)?

**Comment by FroghubMan** [comment]
> Hey @FroghubMan , I checked your application, can you send a sample of the data to my email [yz.li@m.dapponline.io](mailto:yz.li@m.dapponline.io)?

Hi @liyunzhi-666, These are private data

**Comment by kevzak** [comment]
@Carohere @liyunzhi-666 any feedback from you here?

**Comment by liyunzhi-666** [comment]
> @Carohere @liyunzhi-666 any feedback from you here?

If I cannot confirm the content of the data, then it will be difficult for me to support the application.

**Comment by Carohere** [comment]
I'm not confident enough to sign this application. Looking forward to hearing other notaries' review.

**Comment by kevzak** [comment]
@FroghubMan I'll ask you to complete the [E-Fil+ Registration Form](https://form.jotform.com/231003748181651) that includes proof of Dataset size and Dataset sample.

**Comment by FroghubMan** [comment]
Hi @kevzak ,Hope you have a good day. 
Can I follow up on FIL+'s private data storage. In the previous application process, the entire process was very inefficient, is there any update?

**Comment by kevzak** [comment]
@FroghubMan - https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1796#issuecomment-1532981755

**Comment by FroghubMan** [comment]
> @FroghubMan I'll ask you to complete the [E-Fil+ Registration Form](https://form.jotform.com/231003748181651) that includes proof of Dataset size and Dataset sample.

Hi @kevzak , I have completed the E-FIL+ Registration Form.Pleace check it for me. Thank you!

**Comment by FroghubMan** [comment]
> @FroghubMan you still need to pay for your KYB service. Please contact synaps administration

Will do!

**Comment by kevzak** [comment]
> > @FroghubMan I'll ask you to complete the [E-Fil+ Registration Form](https://form.jotform.com/231003748181651) that includes proof of Dataset size and Dataset sample.
> 
> Hi @kevzak , I have completed the E-FIL+ Registration Form.Pleace check it for me. Thank you!

Confirmed. KYC, KYB complete.

**Comment by liyunzhi-666** [comment]
I will sign it later.

**Comment by FroghubMan** [comment]
> I will sign it later.But I still have some questions about the sample data.

I'd be happy to answer your questions.
As a cloud storage service provider, we are just a data preparer. User data is encrypted, including videos, pictures, documents, etc.

**Comment by FroghubMan** [comment]
> > > @FroghubMan I'll ask you to complete the [E-Fil+ Registration Form](https://form.jotform.com/231003748181651) that includes proof of Dataset size and Dataset sample.
> > 
> > 
> > Hi @kevzak , I have completed the E-FIL+ Registration Form.Pleace check it for me. Thank you!
> 
> Confirmed. One last request, this is newer. We ask all E-Fil applicants to complete 3rd party KYC check. https://filplus.storage/kyc

I have completed the KYC of synaps, do I still need to complete togggle again? You know, it's a very tedious and long job..

**Comment by Filplus-govteam** [comment]
@FroghubMan its clear that you are the data preparer/cloud service provider for your clients. But what data from the clients is being stored? You do not have to show encrypted data, but you at least need to confirm the nature of the data.

**Comment by Filplus-govteam** [comment]
Confirming SPs provided via E-Fil Reg form:
f01811024  chimsen   HongKong
f02085722  chimsen   Jiangmen
f0827006  Frog Storage Tokyo
f02227726   Three Clouds HongKong
f02223012  Personal Heibei

**Comment by FroghubMan** [comment]
Sure. It includes videos, pictures, documents and  other software packages, etc.

**Comment by FroghubMan** [comment]
![F5F98B13-A469-4572-9AA6-CCD1A4F2F749](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/88960777/45949422-28bd-403d-b6f9-c3d84b21afa7)

**Comment by liyunzhi-666** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedq44occgv74dgg4gtcflp7poaphekqnbhubfvxgbmd6fafguxd46 
#### Address 
> f1lugk5dlpx23vexq7lounl3gglyprskc67n3722q
#### Datacap Allocated
> 250.00TiB
#### Signer Address
> f1pszcrsciyixyuxxukkvtazcokexbn54amf7gvoq
#### Id
> c74a4c01-2a98-4402-84ec-3e1f1d928e3f
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedq44occgv74dgg4gtcflp7poaphekqnbhubfvxgbmd6fafguxd46

**Comment by FroghubMan** [comment]
thank you!

**Comment by FroghubMan** [comment]
We're preparing dataset.

**Comment by FroghubMan** [comment]
We're preparing dataset.

**Comment by 1ane-1** [comment]
checker:manualTrigger

**Comment by xiaoyuaiheshui** [comment]
checker:manualTrigger

**Comment by xiaoyuaiheshui** [comment]
checker:manualTrigger

**Comment by FroghubMan** [comment]
We're preparing data

**Comment by FroghubMan** [comment]
Some SPs are still preparing machines and will have more than 4 nodes in the next round.

**Comment by 1ane-1** [comment]
> Some SPs are still preparing machines and will have more than 4 nodes in the next round.

Could you please share the 4 nodes and more nodes you will add in the next round. Hope you can do it as you say.

**Comment by FroghubMan** [comment]
f02806528 f02364899 f02806931 f02519021 f02195966 f02311133

**Comment by Chuangshi1** [comment]
[Support for this round and wish you can ](checker:manualTrigger)

**Comment by Chuangshi1** [comment]
checker:manualTrigger

**Comment by Chuangshi1** [comment]
According to your nodes that you added, support for this round and keep eyes on you.

**Comment by Chuangshi1** [comment]
> f02806528 f02364899 f02806931 f02519021 f02195966 f02311133

According to your nodes that you added, support for this round and keep eyes on you.

**Comment by FroghubMan** [comment]
We're preparing data

**Comment by FroghubMan** [comment]
We're preparing data

**Comment by Joss-Hua** [comment]
checker:manualTrigger

**Comment by FroghubMan** [comment]
stay active

**Comment by FroghubMan** [comment]
stay active

**Comment by NiwanDao** [comment]
Please be aware of the distribution of the next tranche.

**Comment by NiwanDao** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedtkyv2nvmtwlupsevfyazugdwjnk3vn5vp7t6ytic4s4xgh6sxv2 
#### Address 
> f1lugk5dlpx23vexq7lounl3gglyprskc67n3722q
#### Datacap Allocated
> 500.00TiB
#### Signer Address
> f1a2lia2cwwekeubwo4nppt4v4vebxs2frozarz3q
#### Id
> 5fe2f577-3b42-4c42-a82b-f990aceed79e
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedtkyv2nvmtwlupsevfyazugdwjnk3vn5vp7t6ytic4s4xgh6sxv2

**Comment by Tom-OriginStorage** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedm6nofymcdljfgnrdm2exrt45jkac4iljhwps55ktrzr5y25alc4 
#### Address 
> f1lugk5dlpx23vexq7lounl3gglyprskc67n3722q
#### Datacap Allocated
> 500.00TiB
#### Signer Address
> f1q6bpjlqia6iemqbrdaxr2uehrhpvoju3qh4lpga
#### Id
> 5fe2f577-3b42-4c42-a82b-f990aceed79e
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedm6nofymcdljfgnrdm2exrt45jkac4iljhwps55ktrzr5y25alc4

**Comment by laurarenpanda** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceasyeovywrx77tiglvucbru4d76b75q6bmk6t47gcytr7tkvkfi3s 
#### Address 
> f1lugk5dlpx23vexq7lounl3gglyprskc67n3722q
#### Datacap Allocated
> 500.00TiB
#### Signer Address
> f1bp3tzp536edm7dodldceekzbsx7zcy7hdfg6uzq
#### Id
> bd2ac8ee-891c-419a-9a5f-ee48386dd6b1
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceasyeovywrx77tiglvucbru4d76b75q6bmk6t47gcytr7tkvkfi3s

**Comment by stcouldlisa** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedo3xxtxefog4hdqihxnu5o4cq4lxzvu45b5pjirzh46mrru42gze 
#### Address 
> f1lugk5dlpx23vexq7lounl3gglyprskc67n3722q
#### Datacap Allocated
> 500.00TiB
#### Signer Address
> f1jvvltduw35u6inn5tr4nfualyd42bh3vjtylgci
#### Id
> bd2ac8ee-891c-419a-9a5f-ee48386dd6b1
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedo3xxtxefog4hdqihxnu5o4cq4lxzvu45b5pjirzh46mrru42gze

**Comment by FroghubMan** [comment]
active

**Comment by Tom-OriginStorage** [comment]
checker:manualTrigger

**Comment by FroghubMan** [comment]
keep
