### ISSUE TITLE
[DataCap Application] <Fenglerui> - <CloudStorage>

### ISSUE THREAD

**Issue by fengwygit** [filecoin-project/filecoin-plus-large-datasets#1797]
### Data Owner Name

Fenglerui（Shanghai）Information Technology Co., Ltd.

### Data Owner Country/Region

China

### Data Owner Industry

IT & Technology Services

### Website

http://www.fenglerui.com

### Social Media

```text
http://www.fenglerui.com
http://bittongjian.com
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

1PiB

### On-chain address for first allocation

f1fipwe3asirtxfhrp6efxgpspjmh7nowsxtdglhq

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Founded in 2021, Fenglerui (Shanghai) Information Technology Co., Ltd. was co-founded by technical and management experts from Oracle, SAP, BOSCH, etc., aiming to provide digital implementation and safe, scalable, Private, reliable and low-cost storage solutions.
We provide digital transformation solutions for SMEs, unify logistics, information flow and capital flow, help enterprises simplify operations, improve decision-making and gain a competitive advantage in the market.
We have served hundreds of game streamers and drivers.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
There are three main types of data
1.Game&streaming, about 180TiB, gameplayers who want to record and platform want to verify their streamers' working hours.
2.Footage video, about 30TiB. This data is from open source footage websites. Customers store these materials to avoid unavailability if the websites are out of service
3.Dashcam Video, about 252TiB. This data comes from individual drivers, truck drivers, and small and medium-sized fleets to ensure a more accurate grasp of the situation of drivers and vehicles
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### How do you plan to prepare the dataset

lotus, singularity, graphsplit, others/custom tool

### If you answered "other/custom tool" in the previous question, enter the details here

```text
We might use an open source tool which is the Swan Client tool (https://github.com/filswan/go-swan-client) to prepare the dataset.
```

### Please share a sample of the data

```text
https://drive.google.com/drive/folders/1w016ULZr4u0qqYlNAJH2kLUQfbQO3YYj?usp=sharing
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Monthly

### For how long do you plan to keep this dataset stored on Filecoin

2 to 3 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, Africa, North America, South America, Europe, Australia (continent)

### How will you be distributing your data to storage providers

HTTP or FTP server, Shipping hard drives

### How do you plan to choose storage providers

Slack, Others

### If you answered "Others" in the previous question, what is the tool or platform you plan to use

```text
We might use FilSwan platform (https://filswan.com/) helping us to find storage providers who located all over the world.
```

### If you already have a list of storage providers to work with, fill out their names and provider IDs below

```text
their names and provider IDs below
We find some storage providers from FilSwan platform, the list is as below.
f02301
f02401
f03223
f03624
f08399
f010088
f032824
f0143858
f0187709
f0240185
f0717969
f0836160
f01955033
f02029115
f01955030
f01163272
f01402814
f01390330
f01225882
f01395673
f01072221
f01443744
f01786736
f01871352
f01907556
f01946551
f01947280
f01955028
f01970630
f02012951
```

### How do you plan to make deals to your storage providers

Boost client, Lotus client, Others/custom tool

### If you answered "Others/custom tool" in the previous question, enter the details here

```text
We found open source tool, which is Swan Client tool
https://github.com/filswan/go-swan-client on https://dataonboarding.filecoin.io/
```

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by fengwygit** [comment]
> https://whois.whoisxmlapi.com/lookup-report/ax5D37bj26 Parsed domain name: fenglerui.com Domain name extension: .com Estimated domain age: 5 day(s) Contact email: [54e1be65-efa3-4edd-a162-a579c1651f05@identity-protect.org](mailto:54e1be65-efa3-4edd-a162-a579c1651f05@identity-protect.org) Created date: March 8, 2023 13:38:19 UTC Updated date: March 8, 2023 13:49:07 UTC
> 
> Can you explain the estimated domain age is just 5 days?

In the past, we mainly undertook the related business of shareholders and used http://bittongjian.com/ to carry out business. Recently, our business has stabilized at a certain level and has grown steadily, so we have registered a new domain name and merged the previous website into the same brand. That's why we disclosed 2 domain names.

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Looking at your application i have some questions:
As you are brand new on Github and have no history of past applications it seems to me that applying for 5PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?

Can you show us visible proof of the size of your data and the storage systems you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230337462961356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!

**Comment by Sunnyiscoming** [comment]
Could you send an email to filplus-app-review@fil.org with your official domain in order to confirm your identity? Email name should includes the issue id #1797.

**Comment by fengwygit** [comment]
This is our first time to apply for datacap, there’no other GitHub account names.

> Dear applicant,
> 
> Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.
> 
> Looking at your application i have some questions: As you are brand new on Github and have no history of past applications it seems to me that applying for 5PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?
> 
> Can you show us visible proof of the size of your data and the storage systems you have there?
> 
> As last question i would like you to fill out [this form](https://form.jotform.com/230337462961356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.
> 
> Thanks!

This is our first time to apply for datacap, there’s no other Github account names.

Currently, our data is as below:

![fenglerui_20230315215026](https://user-images.githubusercontent.com/43399272/225329456-ba622adc-ac76-4dfd-8131-53954ad13c9c.jpg)

We have submitted the KYC form @cryptowhizzard

**Comment by fengwygit** [comment]
> Could you send an email to [filplus-app-review@fil.org](mailto:filplus-app-review@fil.org) with your official domain in order to confirm your identity? Email name should includes the issue id #1797.

Ok, please confirm that the email has been sent

![image](https://user-images.githubusercontent.com/43399272/225620123-cec3f2b4-101a-4aed-8309-1bd89366fcb3.png)

**Comment by Sunnyiscoming** [comment]
Please provide your official email address here.

**Comment by fengwygit** [comment]
> Please provide your official email address here.

ok，our official email address is：contact@fenglerui.com

**Comment by Sunnyiscoming** [comment]
![image](https://user-images.githubusercontent.com/105098820/226593070-09b19257-a0d3-43dc-b21f-19e3ef1a517b.png)
I did second confirmation because I can not see your email address from your mail.

**Comment by fengwygit** [comment]
> Fenglerui（Shanghai）Information Technology Co., Ltd.

Hi sunny, The email has been replied and a confirmation email has been received. Please confirm, thank you
Our email address: contact@fenglerui.com  @Sunnyiscoming 
![1679399010036](https://user-images.githubusercontent.com/43399272/226597037-d04feec0-47fe-416e-a2cf-be62e55259ac.png)
![1679399255160](https://user-images.githubusercontent.com/43399272/226597185-3a144fc9-13a8-4475-b8fa-74c152110dfd.png)

![1679399385424](https://user-images.githubusercontent.com/43399272/226597654-e202ed1a-1fac-43d1-b899-589e5aa2daec.png)

**Comment by Normalnoise** [comment]
@fengwygit I see that you are preparing to use the swan-client for data preparation. Could you share your experience using it? Can you confirm that this data is publicly accessible to everyone?

**Comment by nj-steve** [comment]
@fengwygit Hello guys ,how did you find the storage providers you listed? What is your relationship with them?

**Comment by fengwygit** [comment]
> @fengwygit I see that you are preparing to use the swan-client for data preparation. Could you share your experience using it? Can you confirm that this data is publicly accessible to everyone?

We only tested a few times before this application, and we will ask FilSwan to help with this.
Yes, our data is legal and publicly accessible to everyone


> @fengwygit I see that you are preparing to use the swan-client for data preparation. Could you share your experience using it? Can you confirm that this data is publicly accessible to everyone?

We only tested a few times before this application, and we will ask FilSwan to help with this.
Yes, our data is legal and publicly accessible to everyone. @Normalnoise

**Comment by fengwygit** [comment]
> @fengwygit Hello guys ,how did you find the storage providers you listed? What is your relationship with them?

We found the storage providers on FilSwan platform, we don’t have relationship with them @nj-steve

**Comment by Normalnoise** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceakza3ubiznqld5tqmtn3i2su5rqurt6mi4bwdfg3zqmmhzfereku 
#### Address 
> f1fipwe3asirtxfhrp6efxgpspjmh7nowsxtdglhq
#### Datacap Allocated
> 256.00TiB
#### Signer Address
> f1c5non5yf35avgcpsqvxu4yj54yyvxorwyjochqq
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceakza3ubiznqld5tqmtn3i2su5rqurt6mi4bwdfg3zqmmhzfereku

**Comment by Sunnyiscoming** [comment]
Hello, @fengwygit per the https://github.com/filecoin-project/notary-governance/issues/922 for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

This information will be reviewed by Fil+ Governance team to confirm validity and then the application will be allowed to move forward for additional notary review.
