### ISSUE TITLE
[DataCap Application]slingshot restore program

### ISSUE THREAD

**Issue by HowDeep123** [filecoin-project/filecoin-plus-large-datasets#180]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: KarenudxPhillipsr
- Website / Social Media: https://github.com/filecoin-project/slingshot/blob/master/datasets.md
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 2PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 400TiB
- On-chain address for first allocation:f1na3gu2v2rlznyw7yrqo7hlq6gz7zumsgpqir7xy

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
This is for Slingshot restore program. We have been assigned restore data as client.
```

What is the primary source of funding for this project?
```
From rewards of slingshot.
```

What other projects/ecosystem stakeholders is this project associated with?
```
No.
```

## Use-case details

Describe the data being stored onto Filecoin
```
Those will be the dataset assigned by Protocol Lab as part of the repair and recovery effort for lost deals due to storage outages.
```

Where was the data in this dataset sourced from?
```
Public dataset.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
The dataset are from one of those in this table. 
https://github.com/filecoin-project/slingshot/blob/master/datasets.md
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Confirm.
```

What is the expected retrieval frequency for this data?
```
It depends on the actual need.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
More than 2 years.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Mainly Asia.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
At least 5 storage providers. We will supported the offline data process.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
Protocol Lab will assign storage provider for this project. 
```

How will you be distributing deals across storage providers?
```
Due to their ability to allocate.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, we have resources.
```

**Comment by dkkapur** [comment]
@HowDeep123 - this dataset is assigned to @flyworker and his team for Slingshot Restore. https://docs.google.com/spreadsheets/d/1UYmVtwtJUIAwlogZmLSZB_nZxWrVlID6ryfqrB0jBjw/edit?usp=sharing has the list of selected clients and their datasets. Are you working with him?

**Comment by flyworker** [comment]
I don't think we are working with him

**Comment by HowDeep123** [comment]
Hi I'm KarenudxPhillipsr. I'm in the list. Sorry I’ve made a mistake about the issue. My datasets are genome-in-a-bottle, cancer-cell-line-encyclopedia-ccle and encyclopedia-of-dna-elements.

**Comment by HowDeep123** [comment]
Hi I'm KarenudxPhillipsr. I'm in the list. My datasets are genome-in-a-bottle, cancer-cell-line-encyclopedia-ccle and encyclopedia-of-dna-elements.
