### ISSUE TITLE
[DataCap Application] <FogMeta Lab> - <Community Earth System Model v2 ARISE (CESM2 ARISE)>[2/2]

### ISSUE THREAD

**Issue by hengdingy** [filecoin-project/filecoin-plus-large-datasets#1805]
### Data Owner Name

FogMeta Lab

### Data Owner Country/Region

China

### Data Owner Industry

Web3 / Crypto

### Website

https://fogmeta.com

### Social Media

```text
Twitter: https://twitter.com/FogMeta 
GitHub: https://github.com/FogMeta
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

1PiB

### On-chain address for first allocation

f1wxjurlords6b4jrxg26tiedcisekfjctbethh7y

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
FogMeta Lab's research spans multiple levels from system technology, infrastructure, and middleware to services and solutions, and involves future systems, network technology and business, distributed systems and management, information management, and interactive and innovative services. Based on the views on and practices in the industry, FogMeta also solves the problem of business complexity through operations optimization and other technologies.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
These are data from ARISE-SAI Experiments with CESM2.(https://github.com/NCAR/CESM2-ARISE) ARISE-SAI stands for Assessing Responses and Impacts of Solar climate intervention on the Earth system with Stratospheric Aerosol Injection 

“The primary goal of the Community Earth System Model (CESM) project is to develop a state-of-the-art climate model and to use it to perform the best possible science to understand climate variability and global change.”

Source: 
https://registry.opendata.aws/ncar-cesm2-arise/
https://www.cesm.ucar.edu/community-projects/arise-sai
https://www.cesm.ucar.edu/about
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### How do you plan to prepare the dataset

IPFS, lotus, graphsplit, others/custom tool

### If you answered "other/custom tool" in the previous question, enter the details here

```text
We'd also like to use the Swan Client tool (https://github.com/filswan/go-swan-client#Graphsplit) to prepare the dataset.
```

### Please share a sample of the data

```text
s3://ncar-cesm2-arise/(427.5 TiB)
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Monthly

### For how long do you plan to keep this dataset stored on Filecoin

2 to 3 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, Africa, North America, South America, Europe, Australia (continent), Antarctica

### How will you be distributing your data to storage providers

Cloud storage (i.e. S3), HTTP or FTP server, IPFS, Shipping hard drives

### How do you plan to choose storage providers

Slack, Partners, Others

### If you answered "Others" in the previous question, what is the tool or platform you plan to use

```text
We'd also like to use FilSwan platform (https://filswan.com/) to choose storage providers who meet our requirements.
```

### If you already have a list of storage providers to work with, fill out their names and provider IDs below

```text
The storage providers we'd like to work with are presented below. Some of them are from the FilSwan platform.
f01955033
f02029115
f03624
f010088
f02301
f08399
f02401
f01955030
f0187709
f01163272
f01402814
f01390330
f01225882
f0717969
f03223
f01395673
f01072221
f0143858
f01786736
f0836160
f032824
f01443744
f01871352
f01907556
f01955028
f01947280
f01946551
f02012951
f01970630
f0240185
```

### How do you plan to make deals to your storage providers

Boost client, Lotus client, Others/custom tool

### If you answered "Others/custom tool" in the previous question, enter the details here

```text
Swan Client tool
https://github.com/filswan/go-swan-client
```

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 5PiB

**Expected weekly DataCap usage rate**
> 1PiB

**Client address**
>f1wxjurlords6b4jrxg26tiedcisekfjctbethh7y

**Comment by hengdingy** [comment]
> See questions in #1804

Thanks @Sunnyiscoming review, I have comment there. https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1804#issuecomment-1474861366

**Comment by zcfil** [comment]
I see you only have over 400T of display data, how do you allocate this data?

**Comment by hengdingy** [comment]
@zcfil we will store the data 15 copies to different region SPs. dataset will be split to 16GiB piece, required 32GiB datacap, `400TiB/16*32*15/1024=11.7PiB` datacap is needed. 

All data piece will be sent to SPs according to the filswan platform. swan-client is a great onboarding tool. The piece will be downloaded to SP.

**Comment by Normalnoise** [comment]
checker:manualTrigger

**Comment by zcfil** [comment]
checker:manualTrigger

**Comment by Normalnoise** [comment]
checker:manualTrigger

**Comment by hengdingy** [comment]
checker:manualTrigger
