### ISSUE TITLE
[DataCap Application] <Van Gogh Impression Original Art Gallery>

### ISSUE THREAD

**Issue by hongshan-xu** [filecoin-project/filecoin-plus-large-datasets#1806]
### Data Owner Name

Van Gogh Impression Original Art Gallery

### Data Owner Country/Region

China

### Data Owner Industry

Other

### Website

http://www.fangaoyx.com

### Social Media

```text
http://www.fangaoyx.com
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

300TiB

### On-chain address for first allocation

f1zkgx3igrmczror3zuvvp5bohpbeli6coyns5lba

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Beilun Van Gogh Impression Original Art is located at No. 336-342, Mingzhou Road, Beilun District, Ningbo, officially established in 2002 and has 21 years of industry history up to now.

At the beginning of the company's establishment, we have clearly planned out the four business philosophy of "sincerity, happiness, fashion and quality", which has been welcomed by many customers in Beilun and has received unanimous praise and recognition. "Unlimited creativity, love in Van Gogh" is the vision and purpose of "Van Gogh Impression Original Art".

The company is mainly engaged in all kinds of high-quality photography, such as: art portrait shooting, cultural activities shooting, public welfare activities shooting, wedding ceremony shooting, event shooting and other related services.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
The data we need to store on the Filecoin network is mainly a number of domestic and international special high-definition photos and videos that can be shared publicly to international friends,  For example, regional photography, cultural activities, food sharing, flora and fauna, wedding ceremony, etc.
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### How do you plan to prepare the dataset

IPFS, lotus, others/custom tool

### Please share a sample of the data

```text
https://drive.google.com/drive/folders/1ZjOnELqRJZJzss2j-WZ7jsHDqKKv2DRY
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Sporadic

### For how long do you plan to keep this dataset stored on Filecoin

More than 3 years

### In which geographies do you plan on making storage deals

Greater China, North America, South America, Europe, Australia (continent)

### How will you be distributing your data to storage providers

HTTP or FTP server, IPFS, Shipping hard drives

### How do you plan to choose storage providers

Slack, Big data exchange, Partners, Others

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Looking at your application i have some questions:
As you are brand new on Github and have no history of past applications it seems to me that applying for 5PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?

Can you show us visible proof of the size of your data and the storage systems you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230337462961356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!

**Comment by Sunnyiscoming** [comment]
![image](https://user-images.githubusercontent.com/105098820/225331429-daf7fcf1-26c9-4548-a4be-753260c18c5d.png)
There are some error on the website.
The website has established for just 15 days. https://whois.whoisxmlapi.com/lookup-report/1pRK66BDkw
Can you explain about that?
Please provide Chinese name of your organization?

**Comment by hongshan-xu** [comment]
> ![image](https://user-images.githubusercontent.com/105098820/225331429-daf7fcf1-26c9-4548-a4be-753260c18c5d.png) There are some error on the website. The website has established for just 15 days. https://whois.whoisxmlapi.com/lookup-report/1pRK66BDkw Can you explain about that? Please provide Chinese name of your organization?

Hello, we are a physical store offline in Beilun District, Ningbo, business is mainly offline customers, before also had their own official website: www.fgyx.net, but due to exposure and use rate are extremely low, so give up, but recently because of business needs and redo a, so it looks relatively new, there are still some places need to improve;.
We are registered in the business license name: Ningbo City, Beilun District, the new United States Van Gogh impression photography store, display store name: Beilun Van Gogh impression of the original art, the following is our physical store display:
![WechatIMG205](https://user-images.githubusercontent.com/53814949/225512766-b9708d7d-c0c2-4f56-8c62-1cc7418fd170.png)
![WechatIMG206](https://user-images.githubusercontent.com/53814949/225512776-56150630-e7bd-4bea-b4bc-aa23090ce558.png)
![WechatIMG207](https://user-images.githubusercontent.com/53814949/225512784-ebdcba42-f347-4b4e-bd41-765e00961c89.png)
![WechatIMG208](https://user-images.githubusercontent.com/53814949/225512786-db4c005d-6854-4355-ad7f-f94c42205fb8.png)
![WechatIMG209](https://user-images.githubusercontent.com/53814949/225512788-7b4ad557-e61f-4d92-a687-a0ddd17477ba.png)

**Comment by Sunnyiscoming** [comment]
It seems that your business is biased towards wedding dresses. Can you explain about the source of the data samples and more data you will store?

**Comment by hongshan-xu** [comment]
> It seems that your business is biased towards wedding dresses. Can you explain about the source of the data samples and more data you will store?

Hello, our main business is really based on wedding photography, but our business is diversified, now using Filecoin network is more to store some of our unique characteristics of some regional elements pictures, videos, such as with local characteristics of architecture, scenery, food culture, all kinds of characteristics of animals and plants, etc. These elements are open and shared for other local organizations to see, and need to be stored and passed on for a long time. Thank you.

**Comment by Sunnyiscoming** [comment]
Where these data from?

**Comment by hongshan-xu** [comment]
> Where these data from?

Hello, our store has been in operation for over 20 years. The data we need to store consists of two parts: a portion of it is accumulated by ourselves over the years, and a large portion of it is wonderful materials sent by many photography enthusiast friends. As we originally planned to create an exhibition website featuring regional characteristics, the website will showcase photos and videos of local cultures, customs, food and crafts from China and other countries. We will also continuously invite photography enthusiasts from all over the world to share their own records of such materials with us. Of course, all of these can be shared publicly.

**Comment by Normalnoise** [comment]
@hongshan-xu how much dataset have you prepared? can you provide the dat size proof?

**Comment by hongshan-xu** [comment]
> @hongshan-xu how much dataset have you prepared? can you provide the dat size proof?

Hello, we currently have over 500TiB+ of data, part of which we have accumulated over the years, and a significant portion comes from many photography enthusiasts who have sent us fantastic materials. Our initial plan is to create a regional-themed exhibition website that showcases photos and videos of local cultures, customs, food, and handicrafts from China and other countries. We will also continuously invite photography enthusiasts from around the world to share their own records of these materials. The sample information of the data can be found in Google Drive. Thank you.

**Comment by Normalnoise** [comment]
please provide the data size proof, such as a screenshot in your system. @hongshan-xu

**Comment by hongshan-xu** [comment]
> please provide the data size proof, such as a screenshot in your system. @hongshan-xu


Here are some sample data.
![20230605-111206](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/53814949/0bf689e9-b58f-4bb5-8c1f-40c5fe563847)
![20230605-111214](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/53814949/893e059b-a829-4e2c-a37a-0b88c1754c1a)
![20230605-111227](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/53814949/dec9
![20230605-111234](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/53814949/5450fa7a-0448-4583-b53f-52a0cb7cc542)
2bef-6228-4990-904f-52ffaffe8659)
![20230605-111241](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/53814949/14595978-3160-4de1-b5fd-2671c7bb7edc)

**Comment by Normalnoise** [comment]
willing to support in the current round.

**Comment by Normalnoise** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceddpmkag2rqh4qnukpxkwhjyltlimpf5kaeydmidsy4scwz7qno5y 
#### Address 
> f1zkgx3igrmczror3zuvvp5bohpbeli6coyns5lba
#### Datacap Allocated
> 150.00TiB
#### Signer Address
> f1c5non5yf35avgcpsqvxu4yj54yyvxorwyjochqq
#### Id
> 523e4204-62d2-4983-b857-bdf2ded2dcbf
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceddpmkag2rqh4qnukpxkwhjyltlimpf5kaeydmidsy4scwz7qno5y

**Comment by ipollo00** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedxbmqpku4ehssda5wwatsi7kmypglphfpmwjordishfl3njfmjia 
#### Address 
> f1zkgx3igrmczror3zuvvp5bohpbeli6coyns5lba
#### Datacap Allocated
> 150.00TiB
#### Signer Address
> f1n5wlrrhoxpkgwij25xrtt7w7g2k3fhbthmdn6ri
#### Id
> 523e4204-62d2-4983-b857-bdf2ded2dcbf
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedxbmqpku4ehssda5wwatsi7kmypglphfpmwjordishfl3njfmjia

**Comment by ipollo00** [comment]
Let's check it out the sealing process.

**Comment by hongshan-xu** [comment]
checker:manualTrigger

**Comment by hongshan-xu** [comment]
checker:manualTrigger

**Comment by hongshan-xu** [comment]
@simonkim0515 
when we were planning to initiate the sealing process, we found that LDN was closed. We had just obtained signatures from notaries last month. Now, we will proceed with the sealing in the coming week.

**Comment by Sunnyiscoming** [comment]
- Have sp prepared enough token for sector pledge?
- Best practice for storing large datasets includes ideally, storing it in 3 or more regions, with 4 or more storage provider operators or owners.You should list Miner ID, Business Entity, Location of sps you will cooperate with.
- Per the https://github.com/filecoin-project/notary-governance/issues/922 for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

This information will be reviewed by Fil+ Governance team to confirm validity and then the application will be triggered for notary review. Let us know if you have any questions.

**Comment by kernelogic** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceakdvcrxvnjmf2o6rcyhev6llmapdvz25kxo42cnbsnnilg6eco4i 
#### Address 
> f1zkgx3igrmczror3zuvvp5bohpbeli6coyns5lba
#### Datacap Allocated
> 300.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### Id
> 589c5844-1e57-4379-b751-9332f0fe6315
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceakdvcrxvnjmf2o6rcyhev6llmapdvz25kxo42cnbsnnilg6eco4i

**Comment by NiwanDao** [comment]
Everything looks good. I will support.

**Comment by NiwanDao** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceagkmeaj5qukzttrfxc57o3tishwrfydpjwf5jv355whw5fv47wwo 
#### Address 
> f1zkgx3igrmczror3zuvvp5bohpbeli6coyns5lba
#### Datacap Allocated
> 300.00TiB
#### Signer Address
> f1a2lia2cwwekeubwo4nppt4v4vebxs2frozarz3q
#### Id
> 589c5844-1e57-4379-b751-9332f0fe6315
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceagkmeaj5qukzttrfxc57o3tishwrfydpjwf5jv355whw5fv47wwo

**Comment by cryptowhizzard** [comment]
Hello,

I tested retrieval. The downloads can be found here:

http://datasetcreators.com/downloadedcarfiles/1806-f02223047-f02233568-50213304-baga6ea4seaqiyuoehunuul2dqm27rsgvogcmocg7v7yifysieax6phtt4hyfsaa/

@hongshan-xu what type of files are these ? I want to view the data but it seems these are not pictures / png / jpeg files?

**Comment by hongshan-xu** [comment]
@cryptowhizzard Hello, we queried our own database and did not find this data. We are inquiring about the reason. Thanks!

**Comment by Carohere** [comment]
_"The data we need to store on the Filecoin network is mainly a number of domestic and international special high-definition photos and videos that can be shared publicly to international friends,  For example, regional photography, cultural activities, food sharing, flora and fauna, wedding ceremony, etc."_

![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/106579285/6afb1306-9a16-47e8-9bb8-2f7d4d8d3153)
![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/106579285/552d39e8-f175-44e4-8f23-6a65d95e3095)

The above words and data sample is so different from what you store in the network, By downloading your data looks quite different from your description.

![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/106579285/6a0ea984-9b2b-44c7-b614-1f06434419d0)

No file name extensions mean the computer can not open it and this doesn't match with your data sample.

I'd like to pause this LDN until the client @hongshan-xu makes a clear explanation to the community. @raghavrmadya

**Comment by Filplus-govteam** [comment]
Hello @hongshan-xu  Per the https://github.com/filecoin-project/notary-governance/issues/922 for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

This information will be reviewed by Fil+ Governance team to confirm validity and then the application will open for notary review. Let us know if you have any questions.

**Comment by hongshan-xu** [comment]
checker:manualTrigger

**Comment by hongshan-xu** [comment]
In progress

**Comment by hongshan-xu** [comment]
checker:manualTrigger

**Comment by mikezli** [comment]
checker:manualTrigger

**Comment by mikezli** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceboizbgvzlrpumyimsvk474bdflvwbsih2jkwsab55rzsp54bpqhu 
#### Address 
> f1zkgx3igrmczror3zuvvp5bohpbeli6coyns5lba
#### Datacap Allocated
> 600.00TiB
#### Signer Address
> f1dnb3uz7sylxk6emti3ififcvu3nlufnnsjui6ea
#### Id
> e167ef3e-b848-4d4e-ae1f-1a8112239994
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceboizbgvzlrpumyimsvk474bdflvwbsih2jkwsab55rzsp54bpqhu

**Comment by Aaron01230** [comment]
checker:manualTrigger

**Comment by Aaron01230** [comment]
checker:manualTrigger

**Comment by cryptowhizzard** [comment]
> Hello,
> 
> I tested retrieval. The downloads can be found here:
> 
> http://datasetcreators.com/downloadedcarfiles/1806-f02223047-f02233568-50213304-baga6ea4seaqiyuoehunuul2dqm27rsgvogcmocg7v7yifysieax6phtt4hyfsaa/
> 
> @hongshan-xu what type of files are these ? I want to view the data but it seems these are not pictures / png / jpeg files?

@mikezli 

You proposed on an applicant who is storing different data then what's indicated in the LDN against FIL+ rules and guidelines.

![Scherm­afbeelding 2023-09-18 om 14 15 56](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/36404435/aefdab5a-46a4-447b-b82f-1729926f7ef8)

**Comment by hongshan-xu** [comment]
checker:manualTrigger

**Comment by hongshan-xu** [comment]
checker:manualTrigger
