### ISSUE TITLE
[DataCap Application] <Lenstune> - <lenstune.xyz>

### ISSUE THREAD

**Issue by lenstunexyz** [filecoin-project/filecoin-plus-large-datasets#1808]
### Data Owner Name

lenstune.xyz

### Data Owner Country/Region

United States

### Data Owner Industry

Web3 / Crypto

### Website

https://lenstune.xyz/

### Social Media

```text
https://twitter.com/Web3Tunes
```

### Total amount of DataCap being requested

3PiB

### Weekly allocation of DataCap requested

300TiB

### On-chain address for first allocation

f167bkokwxoyqqklcj5mnngobxylmyqucryxcqn3y 

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
LensTunes is a decentralized music sharing and trading platform combined with social features that built on top of Lens and CyberConnect.Users can share their original audio and mint their works into NFT here.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
User's audio work.
User's NFT data.
User's social relationship data.
Project promotional video.
```

### Where was the data currently stored in this dataset sourced from

Other

### If you answered "Other" in the previous question, enter the details here

```text
Pinata
```

### How do you plan to prepare the dataset

IPFS, lotus, singularity, graphsplit

### Please share a sample of the data

```text
https://emerald-big-hedgehog-331.mypinata.cloud/ipfs/QmSNn7ypTtdnxH4oXsFSvookD79vjGmCVPjA3cPWcNCSAx

https://emerald-big-hedgehog-331.mypinata.cloud/ipfs/QmTggHUtUM14o35Z4sKpg8KMwVt8c9hu5EiD2aT4bu4wTU

https://emerald-big-hedgehog-331.mypinata.cloud/ipfs/QmY8bPfPoDCQWKE8tKVPi5Du1FM2GhY8w4nyjMReWnXXrQ

https://emerald-big-hedgehog-331.mypinata.cloud/ipfs/QmPskhfRxTDxJAiLYv61aLbHXJqibb4QNYRK2XMUERGTbx

https://emerald-big-hedgehog-331.mypinata.cloud/ipfs/QmPTSoUpGVkYt9A2BKuCSCZNtBm5bs5CZNQGjFNUbWxuJX

https://emerald-big-hedgehog-331.mypinata.cloud/ipfs/QmXoVxban6hZuveUU5hi8Z81cL7Ho6KYpDd5rb5CboZ1w1

https://emerald-big-hedgehog-331.mypinata.cloud/ipfs/Qmb7ppJADcLnRjtrHtLx6M5kAbz1JBmzxuYkZgBV2JBSQn
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

1.5 to 2 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, Africa, North America, South America, Europe, Australia (continent), Antarctica

### How will you be distributing your data to storage providers

Cloud storage (i.e. S3), HTTP or FTP server, IPFS, Lotus built-in data transfer

### How do you plan to choose storage providers

Slack, Filmine, Big data exchange, Partners

### How do you plan to make deals to your storage providers

Boost client, Lotus client, Bidbot, Singularity

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Looking at your application i have some questions:
As you are brand new on Github and have no history of past applications it seems to me that applying for 3PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?

Can you show us visible proof of the size of your data and the storage systems you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230337462961356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!

**Comment by Sunnyiscoming** [comment]
How much data do you have? It seems that there are just some test things on the website.
![image](https://user-images.githubusercontent.com/105098820/225328685-dde8bae4-7add-4dc5-ac15-93ac65d530cf.png)

**Comment by Sunnyiscoming** [comment]
Any update here?

**Comment by Sunnyiscoming** [comment]
Close for no reply. You can reopen this if you want to continue.

**Comment by lenstunexyz** [comment]
@Sunnyiscoming @Kevin-FF-USA pls open this issue, thanks

**Comment by lenstunexyz** [comment]
> How much data do you have? It seems that there are just some test things on the website. ![image](https://user-images.githubusercontent.com/105098820/225328685-dde8bae4-7add-4dc5-ac15-93ac65d530cf.png)

what you saw is the testnet website, the mainnet website is : https://lenstube.xyz/
