### ISSUE TITLE
[DataCap Application] Public Blockchain Datasets (Tech Greedy)

### ISSUE THREAD

**Issue by xinaxu** [filecoin-project/filecoin-plus-large-datasets#181]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: TechGreedy
- Website / Social Media: https://www.techgreedy.net
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 1PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 200 TiB
- On-chain address for first allocation: f1quvbybolurp6d4xzthieupygtco6mcakwflzwya

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Our company has engaged in Slingshot starting 2.1. We have successfully stored more than 30 differerent datasets with 20+ different miners.
```

What is the primary source of funding for this project?
```
Company account.
```

What other projects/ecosystem stakeholders is this project associated with?
```
Slingshot competition hosted by Protocol Lab
```

## Use-case details

Describe the data being stored onto Filecoin
```
The dataset we are storing in this project is Public Blockchain Datasets
https://github.com/blockchain-etl/public-datasets
It contains blockchain transactions for various different crypto currnecy projects such as Bitcoin, Ethereum, Polygon, etc.
```

Where was the data in this dataset sourced from?
```
The data is hosted on Google Big Table and can be exported into consumable format, such as csv, json, avro, etc.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://console.cloud.google.com/bigquery?page=table&t=transactions&d=crypto_bitcoin&p=bigquery-public-data&project=tidal-velocity-175320
Please click Preview to look at the data
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes, the dataset is part of Google's open dataset commitment and can be retrieved by anyone.
```

What is the expected retrieval frequency for this data?
```
A few times per year.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
540 days.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Canada, US and EU
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
We will ship hard drives to US and Canada storage providers. For EU providers, we will distribute the data via CDN.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We have a few providers who have been working with us during Slingshot Restore program and we'd like to continue working with them for ongoing Slingshot competition - https://docs.google.com/spreadsheets/d/1Skga2Yn0BD7CDgT1WQmKtPJ3nxhQ4QWd45e78Y42Wjc/edit#gid=0
```

How will you be distributing deals across storage providers?
```
One copy of data for each storage provider.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
We will start in 1-2 weeks once datacap is granted
```

**Comment by galen-mcandrew** [comment]
@xinaxu Can you clarify the difference between this application and #182 ? Are they both for Slingshot competition?

**Comment by xinaxu** [comment]
@galen-mcandrew That's correct. They are both for Slingshot competition, however for different dataset. Per Slingshot rule, each project needs to have different client address to differentiate.

**Comment by Schwartz10** [comment]
Cool idea! Just wanted to point out the similarities here between this application and the [Glif chainstate preservation project](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/193) application.

There are a couple key differences though:

- We plan to back up raw blockchain data, whereas bigquery data may be preprocessed in some way?
- We plan to back up the data in perpetuity
- The preservation project is not a part of slingshot
- We plan to continuously scrape all public blockchain data moving forward (not _just_ backward looking).

**Comment by xinaxu** [comment]
Thanks @Schwartz10 for pointing out the difference

- Yes, the bigquery data here is preprocessed and fits into table structure, which is useful for database import. One advantage is that any query for the bigquery table can be used for this set of data
- We plan for 1.5 years for now. The Filecoin protocol may evolve significantly in 1.5 years and we will evaluate then.
- This project is part of slingshot and has obligation to store data across 4+ storage providers, have complete indexing of the data as well as has website and UI setup to instruct end user how to use the data.
- The google's big query is also updated every week for the latest chain data.

**Comment by xinaxu** [comment]
@galen-mcandrew Could you take a look at this one? Is there any concern? Anything I can do to fascilitate the grant?

**Comment by galen-mcandrew** [comment]
## Multisig Notary requested
#### Total DataCap requested 
> 1PiB
#### Expected weekly DataCap usage rate 
> 200TiB

**Comment by Reiers** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebxooklpg3a5obe5x2qewb6l4qswfk7drgnv7ylmxq3fxnfl4vzn6 
#### Address 
> f1quvbybolurp6d4xzthieupygtco6mcakwflzwya
#### Datacap Allocated
> 51.20TiB
#### Signer Address
> f1oz43ckvmtxmmsfzqm6bpnemqlavz4ifyl524chq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebxooklpg3a5obe5x2qewb6l4qswfk7drgnv7ylmxq3fxnfl4vzn6

**Comment by MegTei** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebseblx3snbarjpsdc23bsyub4swwfjxgjdeqc4pdop2cdvnjunai 
#### Address 
> f1quvbybolurp6d4xzthieupygtco6mcakwflzwya
#### Datacap Allocated
> 51.20TiB
#### Signer Address
> f1ystxl2ootvpirpa7ebgwl7vlhwkbx2r4zjxwe5i
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebseblx3snbarjpsdc23bsyub4swwfjxgjdeqc4pdop2cdvnjunai

**Comment by TimWilliams00** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebyyl2vk4skelxhinuq6hjsdsibqsbiiorowrseidibnijt6vgh22 
#### Address 
> f1quvbybolurp6d4xzthieupygtco6mcakwflzwya
#### Datacap Allocated
> 51.20TiB
#### Signer Address
> f1fkxkfxgopjf3ufnfg5i3m6qlwf73kp4w5zz7nnq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebyyl2vk4skelxhinuq6hjsdsibqsbiiorowrseidibnijt6vgh22

**Comment by Reiers** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacectqphzaf7n4mt2to67cgq3klc7uaaei5bjjkha6lgificknpz6f4 
#### Address 
> f1quvbybolurp6d4xzthieupygtco6mcakwflzwya
#### Datacap Allocated
> 102.40TiB
#### Signer Address
> f1oz43ckvmtxmmsfzqm6bpnemqlavz4ifyl524chq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacectqphzaf7n4mt2to67cgq3klc7uaaei5bjjkha6lgificknpz6f4

**Comment by dannyob** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebwzi5mjdkav6247opqjhid5q53s3xc24zu3eyco6aahpvpw5ckdk 
#### Address 
> f1quvbybolurp6d4xzthieupygtco6mcakwflzwya
#### Datacap Allocated
> 102.40TiB
#### Signer Address
> f1k6wwevxvp466ybil7y2scqlhtnrz5atjkkyvm4a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebwzi5mjdkav6247opqjhid5q53s3xc24zu3eyco6aahpvpw5ckdk

**Comment by JimChao1** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedx2axr6nwnaz3rmaila5wklfyuroh3n4tcxm4fjqhpaqhnbc5i64 
#### Address 
> f1quvbybolurp6d4xzthieupygtco6mcakwflzwya
#### Datacap Allocated
> 204.80TiB
#### Signer Address
> f1hlubjsdkv4wmsdadihloxgwrz3j3ernf6i3cbpy
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedx2axr6nwnaz3rmaila5wklfyuroh3n4tcxm4fjqhpaqhnbc5i64

**Comment by cryptowhizzard** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebyaqfxra4qsfu3qu3u4ea7nxib4sl3j6fwpeum4ijlziuyauvbza 
#### Address 
> f1quvbybolurp6d4xzthieupygtco6mcakwflzwya
#### Datacap Allocated
> 204.80TiB
#### Signer Address
> f1krmypm4uoxxf3g7okrwtrahlmpcph3y7rbqqgfa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebyaqfxra4qsfu3qu3u4ea7nxib4sl3j6fwpeum4ijlziuyauvbza

**Comment by flyworker** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedjdn2hinfgrmht22w3z2sehy4vsilt2hcadiyfz2ots45qmtslta 
#### Address 
> f1quvbybolurp6d4xzthieupygtco6mcakwflzwya
#### Datacap Allocated
> 409.59TiB
#### Signer Address
> f1hlubjsdkv4wmsdadihloxgwrz3j3ernf6i3cbpy
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedjdn2hinfgrmht22w3z2sehy4vsilt2hcadiyfz2ots45qmtslta

**Comment by Fenbushi-Filecoin** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebhvoqjjemgcgchacls65zpiu4kbcm5mzuwb6zhncey6mawijcpa4 
#### Address 
> f1quvbybolurp6d4xzthieupygtco6mcakwflzwya
#### Datacap Allocated
> 409.59TiB
#### Signer Address
> f1yqydpmqb5en262jpottko2kd65msajax7fi4rmq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebhvoqjjemgcgchacls65zpiu4kbcm5mzuwb6zhncey6mawijcpa4

**Comment by xinaxu** [comment]
@MegTei wonder if you can help approve this last round?

**Comment by MegTei** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb2bpjejhlbhwemwzhb5u3axs3pqwyh7qrdiqhfgqqzw7enievrvy 
#### Address 
> f1quvbybolurp6d4xzthieupygtco6mcakwflzwya
#### Datacap Allocated
> 204.81TiB
#### Signer Address
> f1ystxl2ootvpirpa7ebgwl7vlhwkbx2r4zjxwe5i
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb2bpjejhlbhwemwzhb5u3axs3pqwyh7qrdiqhfgqqzw7enievrvy

**Comment by flyworker** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedp3wrhtfppb3xysbva6uctm5wbzzovrl2diy7yhsxy7zqyzbdlmm 
#### Address 
> f1quvbybolurp6d4xzthieupygtco6mcakwflzwya
#### Datacap Allocated
> 204.81TiB
#### Signer Address
> f1hlubjsdkv4wmsdadihloxgwrz3j3ernf6i3cbpy
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedp3wrhtfppb3xysbva6uctm5wbzzovrl2diy7yhsxy7zqyzbdlmm

**Comment by cryptowhizzard** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebbu54724zil5fcep6wmcnugpn6ykjzsxbh6pxrimsur2u7l37m5w 
#### Address 
> f1quvbybolurp6d4xzthieupygtco6mcakwflzwya
#### Datacap Allocated
> 3.00B
#### Signer Address
> f1krmypm4uoxxf3g7okrwtrahlmpcph3y7rbqqgfa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebbu54724zil5fcep6wmcnugpn6ykjzsxbh6pxrimsur2u7l37m5w

**Comment by filplus-checker** [comment]
## DataCap and CID Checker Report[^1]
 - Organization: `TechGreedy`
 - Client: `f1quvbybolurp6d4xzthieupygtco6mcakwflzwya`
### Storage Provider Distribution
The below table shows the distribution of storage providers that have stored data for this client.

If this is the first time a provider takes verified deal, it will be marked as `new`.

For most of the datacap application, below restrictions should apply.
 - Storage provider should not exceed 25% of total datacap.
 - Storage provider should not be storing duplicate data for more than 20%.
 - Storage provider should have published its public IP address.
 - All storage providers should be located in different regions.

✔️ Storage provider distribution looks healthy.

| Provider                                              |                     Location | Total Deals Sealed | Percentage | Unique Data | Duplicate Deals |
| :---------------------------------------------------- | ---------------------------: | -----------------: | ---------: | ----------: | --------------: |
| [f01652333](https://filfox.info/en/address/f01652333) |    Sunnyvale, California, US |         181.56 TiB |     17.81% |  177.22 TiB |           2.39% |
| [f01732189](https://filfox.info/en/address/f01732189) |    San Diego, California, US |         174.97 TiB |     17.17% |  174.97 TiB |           0.00% |
| [f01392893](https://filfox.info/en/address/f01392893) | Amsterdam, North Holland, NL |         173.34 TiB |     17.01% |  173.34 TiB |           0.00% |
| [f01702940](https://filfox.info/en/address/f01702940) |            Dallas, Texas, US |         131.39 TiB |     12.89% |  130.02 TiB |           1.05% |
| [f01345523](https://filfox.info/en/address/f01345523) |      Antwerpen, Flanders, BE |         100.23 TiB |      9.83% |  100.20 TiB |           0.03% |
| [f01752548](https://filfox.info/en/address/f01752548) |      Seattle, Washington, US |          62.98 TiB |      6.18% |   62.33 TiB |           1.04% |
| [f01794835](https://filfox.info/en/address/f01794835) |         Chengdu, Sichuan, CN |          54.70 TiB |      5.37% |   47.39 TiB |          13.37% |
| [f01823264](https://filfox.info/en/address/f01823264) |         Chengdu, Sichuan, CN |          54.16 TiB |      5.31% |   52.84 TiB |           2.42% |
| [f01775922](https://filfox.info/en/address/f01775922) |        Ashburn, Virginia, US |          35.72 TiB |      3.50% |   35.72 TiB |           0.00% |
| [f01611097](https://filfox.info/en/address/f01611097) | San Clemente, California, US |          27.00 TiB |      2.65% |   27.00 TiB |           0.00% |
| [f039940](https://filfox.info/en/address/f039940)     |         Chengdu, Sichuan, CN |          21.53 TiB |      2.11% |   21.03 TiB |           2.32% |
| [f01732188](https://filfox.info/en/address/f01732188) |        Chicago, Illinois, US |           1.44 TiB |      0.14% |    1.44 TiB |           0.00% |
| [f034258](https://filfox.info/en/address/f034258)     |         Chengdu, Sichuan, CN |         224.00 GiB |      0.02% |  224.00 GiB |           0.00% |

![Provider Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/181/1671093442187.png)
### Deal Data Replication
The below table shows how each many unique data are replicated across storage providers.
- No more than 25% of unique data are stored with less than 4 providers.

✔️ Data replication looks healthy.

| Unique Data Size | Total Deals Made | Number of Providers | Deal Percentage |
| ---------------: | ---------------: | ------------------: | --------------: |
|        16.00 GiB |        16.00 GiB |                   1 |           0.00% |
|       528.00 GiB |         1.03 TiB |                   2 |           0.10% |
|        30.34 TiB |        91.16 TiB |                   3 |           8.94% |
|        24.22 TiB |        97.69 TiB |                   4 |           9.58% |
|        20.67 TiB |       103.80 TiB |                   5 |          10.18% |
|        39.75 TiB |       240.13 TiB |                   6 |          23.56% |
|        40.94 TiB |       293.38 TiB |                   7 |          28.78% |
|        12.66 TiB |       103.50 TiB |                   8 |          10.15% |
|         5.84 TiB |        53.53 TiB |                   9 |           5.25% |
|         3.25 TiB |        35.03 TiB |                  10 |           3.44% |

![Replication Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/181/1671093442817.png)
### Deal Data Shared with other Clients
The below table shows how many unique data are shared with other clients.
Usually different applications owns different data and should not resolve to the same CID.

⚠️ CID sharing has been observed.

| Other Client                                                                                                          | Application                                                                                                                     | Total Deals Affected | Unique CIDs |  Verifier |
| :-------------------------------------------------------------------------------------------------------------------- | :------------------------------------------------------------------------------------------------------------------------------ | -------------------: | ----------: | --------: |
| [f1pkrmygbvweykpjcut36lf7ewgqdfhjklbhvepda](https://filfox.info/en/address/f1pkrmygbvweykpjcut36lf7ewgqdfhjklbhvepda) | [Protocol Labs \( project: Slingshot Evergreen \)](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/293) |           142.33 TiB |       1,522 | LDN # 293 |

[^1]: To manually trigger this report, add a comment with text `checker:manualTrigger`
