### ISSUE TITLE
[DataCap Application] Academics Torrents[1/2]

### ISSUE THREAD

**Issue by Tylertest8** [filecoin-project/filecoin-plus-large-datasets#1810]
### Data Owner Name

Academics Torrents

### Data Owner Country/Region

United States

### Data Owner Industry

IT & Technology Services

### Website

https://academictorrents.com/

### Social Media

```text
https://academictorrents.com/
Twitter: @academictorrent
Facebook: AcademicTorrents
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

200TiB

### On-chain address for first allocation

f1i7jr7ye3qgjiw6rjy33guf5ny3s7ircrn26hjfq

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Academics Torrents was established to meet the demands of science in the age of big data. It utilizes a scalable BitTorrent platform that distributes the burden of hosting data, eliminating the risk of data loss due to the rise and fall of dataset hosting providers. Researchers are empowered to replicate data they are working with and share large datasets without incurring the high costs usually associated with commercial providers.

Academic Torrents is a product of the Institute for Reproducible Research (a U.S. 501(c)3 nonprofit).
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
Academics Torrents was established to meet the demands of science in the age of big data. It utilizes a scalable BitTorrent platform that distributes the burden of hosting data, eliminating the risk of data loss due to the rise and fall of dataset hosting providers. Researchers are empowered to replicate data they are working with and share large datasets without incurring the high costs usually associated with commercial providers.
```

### Where was the data currently stored in this dataset sourced from

Other

### If you answered "Other" in the previous question, enter the details here

```text
BitTorrent
```

### How do you plan to prepare the dataset

singularity

### Please share a sample of the data

```text
https://academictorrents.com/
Making over 127.15TB of research data available!

https://academictorrents.com/browse.php?sort_field=size&sort_dir=DESC
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

1.5 to 2 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, Europe

### How will you be distributing your data to storage providers

Cloud storage (i.e. S3), HTTP or FTP server, IPFS, Shipping hard drives

### How do you plan to choose storage providers

Slack, Big data exchange, Partners, Others

### How do you plan to make deals to your storage providers

Boost client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Looking at your application i have some questions:
As you are brand new on Github and have no history of past applications it seems to me that applying for 5PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?

Can you show us visible proof of the size of your data and the storage systems you have there?

The dataset itself is 127.5 TB. If you store 6 replica's then you need around 1 PB of datacap. What do you intend to do with the other 4 PB?

As last question i would like you to fill out [this form](https://form.jotform.com/230337462961356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!

**Comment by Sunnyiscoming** [comment]
Could you send an email to filplus-app-review@fil.org with your official domain in order to confirm your identity? Email name should includes the issue id #1810.

**Comment by Tylertest8** [comment]
@cryptowhizzard 
Hello notary,
Thanks for your comment, I will try to answer your questions above
1. I may be new to applying for LDN, but  I have already participated in the construction of the filecoin network ecology in the early days
for example: <[https://github.com/filecoin-project/lotus/issues/1027>](https://github.com/filecoin-project/lotus/issues/1027%3E) 
In addition, we have done a complete test on data packaging and data distribution
2. I have prepared several servers for processing CAR files, and we are currently downloading these public data from the network
3. The current dataset is 127.15TB, and it is planned to store 10 copies. It is estimated that it will take about 2-3PB for storage, and the dataset is currently collecting more research data, so we have made some redundant applications.
4. I am currently in communication with SP, and I will announce the next progress in time

Thanks!

**Comment by Sunnyiscoming** [comment]
Received email from google email address. It is not ok to verify your identity.

**Comment by kenny688** [comment]
@Sunnyiscoming sorry！How should I do it? What kind of identity should I have to store data in the filecoin network?

**Comment by Sunnyiscoming** [comment]
> Share a brief history of your project and organization
> Academics Torrents was established to meet the demands of science in the age of big data. It utilizes a scalable BitTorrent platform that distributes the burden of hosting data, eliminating the risk of data loss due to the rise and fall of dataset hosting providers. Researchers are empowered to replicate data they are working with and share large datasets without incurring the high costs usually associated with commercial providers.
> 
> Academic Torrents is a product of the Institute for Reproducible Research (a U.S. 501(c)3 nonprofit).

These words let me think you are employee of this organization. If you are not, please tell me who you are or which organization you are working for?

**Comment by kenny688** [comment]
@Sunnyiscoming sorry ，i let you misunderstand me

I am a blockchain enthusiast and technical developer. Since 2020, I have been participating in the Filecoin test network and space race with a team, providing technical support for other Storage Providers (SPs). You can see my previous contributions in [issues/1027](https://github.com/filecoin-project/lotus/issues/1027) on GitHub. Based on the blockchain DAO concept, we currently have four developers who share the same passion for blockchain projects and are conducting research and development on storage and retrieval projects.

To comply with Filecoin's plan to store the most important human data, I am willing to provide a public dataset as effective data storage. I will strictly adhere to the effective data rules set by the community to ensure fair distribution among Storage Providers (SPs).

**Comment by Sunnyiscoming** [comment]
Please share more detailed information about sps you will cooperate with.

**Comment by kenny688** [comment]
> Please share more detailed information about sps you will cooperate with.

@Sunnyiscoming 
I plan to store data in China, China Hong Kong, Europe, and the United States. I have listed some storage providers (SPs) that I hope to collaborate with, and we will also look for high-quality SPs to collaborate with on the Filecoin reputation system and filswan platform. If there is confirmed SP information, it will be announced in a timely manner.

f01702940 US
f01035680 US
f02058037 Hong Kong

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 5PiB

**Expected weekly DataCap usage rate**
> 200TiB

**Client address**
>f1i7jr7ye3qgjiw6rjy33guf5ny3s7ircrn26hjfq

**Comment by kenny688** [comment]
@Sunnyiscoming What should I do next, can help me store data.

**Comment by swatchliu** [comment]
checker:manualTrigger

**Comment by swatchliu** [comment]
Hi @kenny688 , It looks like your website isn't working right now, could you please check with your IT man to make sure it's transparent & trustworthy so all community members can clearly know your project.

If so, I am willing to support it.

Thank you. 
![image](https://user-images.githubusercontent.com/46444977/230811850-c702ab9b-0300-446c-b862-2c28bb1ea4ac.png)

**Comment by kenny688** [comment]
@swatchliu 
Hello, there may be other problems that prevent you from accessing, I confirm that it is currently working normally

![image](https://user-images.githubusercontent.com/70317712/230814346-7fce7eaa-a5b5-427c-8337-37c7833acb66.png)

**Comment by swatchliu** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced4fflt5q5qjyomeol3hjajmsqlozqptpsjwd5r2uwsoz4g2rckqg 
#### Address 
> f1i7jr7ye3qgjiw6rjy33guf5ny3s7ircrn26hjfq
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1yh6q3nmsg7i2sys7f7dexcuajgoweudcqj2chfi
#### Id
> 97755e48-86c7-48a8-b29e-1a44c2479d29
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced4fflt5q5qjyomeol3hjajmsqlozqptpsjwd5r2uwsoz4g2rckqg

**Comment by jomozz** [comment]
How many copies do you plan in this LDN?

**Comment by jomozz** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceabddtx2pzawvmyoyeuc7vmrxqm2u6gmr5rgmkj5rw2iw6b6b3miu 
#### Address 
> f1i7jr7ye3qgjiw6rjy33guf5ny3s7ircrn26hjfq
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1qpdwt2f2fse74nl5wi27uk5jcyqqqyil47yqt7i
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceabddtx2pzawvmyoyeuc7vmrxqm2u6gmr5rgmkj5rw2iw6b6b3miu
