### ISSUE TITLE
[DataCap Application] Academics Torrents[2/2] 

### ISSUE THREAD

**Issue by Tylertest8** [filecoin-project/filecoin-plus-large-datasets#1811]
### Data Owner Name

Academics Torrents

### Data Owner Country/Region

United States

### Data Owner Industry

IT & Technology Services

### Website

https://academictorrents.com/

### Social Media

```text
https://academictorrents.com/
Twitter: @academictorrent
Facebook: AcademicTorrents
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

200TiB

### On-chain address for first allocation

f1i7jr7ye3qgjiw6rjy33guf5ny3s7ircrn26hjfq

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Academics Torrents was established to meet the demands of science in the age of big data. It utilizes a scalable BitTorrent platform that distributes the burden of hosting data, eliminating the risk of data loss due to the rise and fall of dataset hosting providers. Researchers are empowered to replicate data they are working with and share large datasets without incurring the high costs usually associated with commercial providers.

Academic Torrents is a product of the Institute for Reproducible Research (a U.S. 501(c)3 nonprofit).
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
Academics Torrents was established to meet the demands of science in the age of big data. It utilizes a scalable BitTorrent platform that distributes the burden of hosting data, eliminating the risk of data loss due to the rise and fall of dataset hosting providers. Researchers are empowered to replicate data they are working with and share large datasets without incurring the high costs usually associated with commercial providers.
```

### Where was the data currently stored in this dataset sourced from

Other

### If you answered "Other" in the previous question, enter the details here

```text
BitTorrent
```

### How do you plan to prepare the dataset

singularity

### Please share a sample of the data

```text
https://academictorrents.com/
Making over 127.15TB of research data available!

https://academictorrents.com/browse.php?sort_field=size&sort_dir=DESC
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

1.5 to 2 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, Europe

### How will you be distributing your data to storage providers

Cloud storage (i.e. S3), HTTP or FTP server, Shipping hard drives

### How do you plan to choose storage providers

Slack, Big data exchange, Partners

### How do you plan to make deals to your storage providers

Boost client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Looking at your application i have some questions:
As you are brand new on Github and have no history of past applications it seems to me that applying for 5PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?

Can you show us visible proof of the size of your data and the storage systems you have there?

The dataset itself is 127.5 TB. If you store 6 replica's then you need around 1 PB of datacap. What do you intend to do with the other 4 PB?

As last question i would like you to fill out [this form](https://form.jotform.com/230337462961356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!

**Comment by Sunnyiscoming** [comment]
See questions in #1810 .

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 5PiB

**Expected weekly DataCap usage rate**
> 200TiB

**Client address**
>f1i7jr7ye3qgjiw6rjy33guf5ny3s7ircrn26hjfq
