### ISSUE TITLE
[DataCap Application] Profero, Inc.

### ISSUE THREAD

**Issue by jamerduhgamer** [filecoin-project/filecoin-plus-large-datasets#1813]
### Data Owner Name
Profero, Inc.

### Data Owner Country/Region
United States

### Data Owner Industry
Information, Media & Telecommunications

### Website
[N/A - In Progress](N/A - In Progress)

### Social Media
N/A - In Progress (N/A)

### Total amount of DataCap being requested
3 PiB

### Weekly allocation of DataCap requested
100 TiB

### On-chain address for first allocation
f1af2ta5ltzw7bge7qkbzmjfkjks2a6oubgox26rq

### Data Type of Application
Private Commercial/Enterprise

### Custom multisig
- [x] Use Custom Multisig

### Identifier
efil

### Share a brief history of your project and organization
Profero is a start up sister company, via common ownership, to ALT Systems.  ALT Systems is a technical solution provider to the Media and Entertainment market and has extensive contacts with studios and post facilities throughout the industry.  Profero intends to leverage the ALT Systems relationships and provide alternative storage solutions for archival and DR requirements.

### Is this project associated with other projects/ecosystem stakeholders?
Yes

### If answered yes, what are the other projects/ecosystem stakeholders
PiKNiK is submitting this application on behalf of Profero's client who was a previous ESPA participant.

### Describe the data being stored onto Filecoin
Film and video projects generated by the major studios.

### Where was the data currently stored in this dataset sourced from
My own storage infra

### How do you plan to prepare the dataset
others/custom tool

### If you answered "other/custom tool" in the previous question, enter the details here
Data will be prepped using PiKNiK's Basket application.

### Please share a sample of the data
Sample will be attached soon.

### Confirm that this is a public dataset that can be retrieved by anyone on the Network
No

### If you chose not to confirm, what was the reason
ALT Systems / Profero will encrypt the data.  No GDPR compliance required, but could affect available sites for replicas.

### What is the expected retrieval frequency for this data
Yearly

### For how long do you plan to keep this dataset stored on Filecoin
2 to 3 years

### In which geographies do you plan on making storage deals
North America

### How will you be distributing your data to storage providers
HTTP or FTP server

### How do you plan to choose SP
Partners

### If you already have a list of storage providers to work with, fill out their names and provider IDs below
PiKNiK (United States) - 2 copies
Profero (United States) - 1 copy
Seal Storage (Canada) - 1 copy
TBD (Europe) - 1 copy
TBD (Europe) - 1 copy

### How do you plan to make deals to your storage providers
Boost client

### Can you confirm that you will follow the Fil+ guideline
Yes

**Comment by Sunnyiscoming** [comment]
Waiting for website, data samples, and more informations.

**Comment by Sunnyiscoming** [comment]
Any update here?

**Comment by jamerduhgamer** [comment]
Hi @Sunnyiscoming, the client will not have a social media site but am working on getting a sample of the data attached to the LDN. What more information is needed besides these two points?

**Comment by kevzak** [comment]
@jamerduhgamer any update here? Need anything else?

**Comment by jamerduhgamer** [comment]
Hello @kevzak, I heard that the sample data is no longer needed for this. Can we get this application re-opened? Profero client is currently going through the KYB and KYC process and will include that information here when they complete the process.

**Comment by jamerduhgamer** [comment]
Hi Kevin, I will complete this but I am assuming Profero will need to complete it as well?

**Comment by kevzak** [comment]
Hi @jamerduhgamer - KYC is for the applicant, it does not have to be for the data owner in this case. The data owner completes the KYB check.

**Comment by jamerduhgamer** [comment]
Hi @kevzak, I have completed the KYC check!

**Comment by kevzak** [comment]
## Datacap Request Trigger
#### Total DataCap requested 
> 3PiB
#### Expected weekly DataCap usage rate 
> 100TiB
#### Client address
> f1af2ta5ltzw7bge7qkbzmjfkjks2a6oubgox26rq

**Comment by kevzak** [comment]
I can confirm this client has completed KYC and KYB per E-Fil+ Guidelines. Open for notary review.

**Comment by mjroddy** [comment]
looks ok to me!  pushing through

**Comment by Fenbushi-Filecoin** [comment]
Can you provide IDs for the SPs?

**Comment by jamerduhgamer** [comment]
Hi @Fenbushi-Filecoin, we have the following IDs for the following locations:
1. f01884351 - United States, Dallas
2. TBD - United States, San Diego
3. f02016938 - United States, Las Vegas
4. We also have an SP in Canada, Montreal that is still in the planning stage.

**Comment by liyunzhi-666** [comment]
Does this application not support other people's retrieve? Or support specified clients retrieval? @jamerduhgamer

**Comment by Fenbushi-Filecoin** [comment]
We can sign the application for the first tranche. Please get the miner ID for the Canada and Europe SPs before the next datacap tranche.

**Comment by jamerduhgamer** [comment]
Hi @liyunzhi-666, the SPs associated with the application will support retrievals but the data will be encrypted.

Hi @Fenbushi-Filecoin, noted and will try to find a Canadian and European SPs to take on some copies!

**Comment by liyunzhi-666** [comment]
I would support the first round and look forward to seeing more SP IDs.

**Comment by liyunzhi-666** [comment]
I am having some problems with signing. Who do I contact to resolve them? @kevzak 
![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/52949274/0197bf91-504a-43e9-87c5-02778d18d3b7)

**Comment by liyunzhi-666** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebgdcwupzvkzzy6ppwyzshricapdeituog5mvs2nyang6zecpn22a 
#### Address 
> f1af2ta5ltzw7bge7qkbzmjfkjks2a6oubgox26rq
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1pszcrsciyixyuxxukkvtazcokexbn54amf7gvoq
#### Id
> 691e6f79-c895-4bb5-acf4-a7b8e7cdfd67
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebgdcwupzvkzzy6ppwyzshricapdeituog5mvs2nyang6zecpn22a

**Comment by liyunzhi-666** [comment]
I have not made any changes. I tried to sign #1813 after signing another LDN and it worked ........ But yesterday it didn't work no matter what I tried, it was weird. 
cc @kevzak  @panges2 
I have the same notary address for both V3 and V4. @jamerduhgamer

**Comment by Fenbushi-Filecoin** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceddq2vbkjbcz4z2s6qi2dzfjnfcfnq22icevj3rwcbphdu2chhg2s 
#### Address 
> f1af2ta5ltzw7bge7qkbzmjfkjks2a6oubgox26rq
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1yqydpmqb5en262jpottko2kd65msajax7fi4rmq
#### Id
> 691e6f79-c895-4bb5-acf4-a7b8e7cdfd67
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceddq2vbkjbcz4z2s6qi2dzfjnfcfnq22icevj3rwcbphdu2chhg2s

**Comment by PluskitOfficial** [comment]
checker:manualTrigger

**Comment by jamerduhgamer** [comment]
f01884351 has stopped sealing and we are working on on-boarding another SP to store a replica.

**Comment by data-programs** [comment]
<img width="32" alt="KYC" Verified src="https://stable.filplus.storage/images/filplus-kyc-verified-badge.png"/>

This user’s identity has been verified through [filplus.storage](https://filplus.storage)

**Comment by spaceT9** [comment]
Please increase  the number of SPs, and share the SP relevant info before next tranche

**Comment by clriesco** [comment]
Removed stale label and reopened issue :)
