### ISSUE TITLE
[DataCap Application] NOAA Geostationary Operational Environmental Satellites (GOES) 16 <1/2>

### ISSUE THREAD

**Issue by VincentShii** [filecoin-project/filecoin-plus-large-datasets#1818]
### Data Owner Name

The National Oceanic and Atmospheric Administration

### Data Owner Country/Region

United States

### Data Owner Industry

Environment

### Website

https://github.com/awslabs/open-data-docs/tree/main/docs/noaa/noaa-goes16

### Social Media

```text
https://www.noaa.gov/
https://twitter.com/NOAA
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

1PiB

### On-chain address for first allocation

f17uxxk6ibo4h44yohxj6oappy4on2maygafqp2zi

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
organization: Yuga was founded in 2019 with core members mainly from Microsoft, AWS and other major leading organizations. Till now we have about 20 employees in Shanghai office. We've been dedicated to building and optimizing industry-leading order encapsulation components for three years, enabling rapid processing and encapsulation of real data, and continuously empowering storage providers and data content providers.

Project: NOAA is an agency that enriches life through science. Our agency holds key leadership roles in shaping international ocean, fisheries, climate, space and weather policies.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
GOES satellites provide continuous weather imagery and monitoring of meteorological and space environment data across North America.
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### How do you plan to prepare the dataset

lotus

### Please share a sample of the data

```text
https://registry.opendata.aws/noaa-goes/
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

1.5 to 2 years

### In which geographies do you plan on making storage deals

Asia other than Greater China, North America, South America, Europe

### How will you be distributing your data to storage providers

Shipping hard drives, Lotus built-in data transfer

### How do you plan to choose storage providers

Slack, Filmine, Big data exchange, Partners

### How do you plan to make deals to your storage providers

Lotus client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 5PiB

**Expected weekly DataCap usage rate**
> 1PiB

**Client address**
>f17uxxk6ibo4h44yohxj6oappy4on2maygafqp2zi

**Comment by Casey-PG** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebb6jdfr2mwaefx4giamb6o72a3jxus3mvr2ms7675g2jxtkgltuq 
#### Address 
> f17uxxk6ibo4h44yohxj6oappy4on2maygafqp2zi
#### Datacap Allocated
> 256.00TiB
#### Signer Address
> f1d4yb3wags3mtddzesxoo63jv7dmlec3bq4yteni
#### Id
> e1a97e22-6cee-4436-b5aa-3edd8d01b75f
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebb6jdfr2mwaefx4giamb6o72a3jxus3mvr2ms7675g2jxtkgltuq

**Comment by TakiChain** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced6fmfnyoyyfzk2ntsidhhkhb66jurjkaldxdb44pqmjrpdhxsxne 
#### Address 
> f17uxxk6ibo4h44yohxj6oappy4on2maygafqp2zi
#### Datacap Allocated
> 1.00PiB
#### Signer Address
> f15impf3j2zcaex4lhyxndxswuuhv24vzstuqtxsi
#### Id
> 3127dc4b-91f3-4311-a562-fcfa0f5bf9b1
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced6fmfnyoyyfzk2ntsidhhkhb66jurjkaldxdb44pqmjrpdhxsxne

**Comment by Casey-PG** [comment]
The applicant shared the enough information with us by slack.  Willing to sign for this round.

**Comment by Casey-PG** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceck22dfw4da4ov2umunhk7lsathkoifoxn3yonij5qognau4x7jce 
#### Address 
> f17uxxk6ibo4h44yohxj6oappy4on2maygafqp2zi
#### Datacap Allocated
> 1.00PiB
#### Signer Address
> f1d4yb3wags3mtddzesxoo63jv7dmlec3bq4yteni
#### Id
> 3127dc4b-91f3-4311-a562-fcfa0f5bf9b1
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceck22dfw4da4ov2umunhk7lsathkoifoxn3yonij5qognau4x7jce

**Comment by Meibuy** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacea73spwgfoph2jaws2qk3hkwmt2fq6dndlmbgj5g5t6ndr3tpodbc 
#### Address 
> f17uxxk6ibo4h44yohxj6oappy4on2maygafqp2zi
#### Datacap Allocated
> 2.00PiB
#### Signer Address
> f1bwugfihrmn3iyunzyxst5nttql3dge4khwmurtq
#### Id
> 665ee6bc-d89e-4e9f-83a3-3cee41f7313b
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacea73spwgfoph2jaws2qk3hkwmt2fq6dndlmbgj5g5t6ndr3tpodbc

**Comment by Suyanj** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedc53jsdzhwcrtxcqgsahzsuzyxgl27vvgz5j6zgp7pogvcvlemsa 
#### Address 
> f17uxxk6ibo4h44yohxj6oappy4on2maygafqp2zi
#### Datacap Allocated
> 2.00PiB
#### Signer Address
> f1ihv7gz3vn3xqvikpt4rwryecgisl7745lodx3yi
#### Id
> 665ee6bc-d89e-4e9f-83a3-3cee41f7313b
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedc53jsdzhwcrtxcqgsahzsuzyxgl27vvgz5j6zgp7pogvcvlemsa

**Comment by Casey-PG** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebznmh3nwdp7cvuukmxqqgt34e5xz2ql377qne7imik5e2ahqwprm 
#### Address 
> f17uxxk6ibo4h44yohxj6oappy4on2maygafqp2zi
#### Datacap Allocated
> 1.50PiB
#### Signer Address
> f1d4yb3wags3mtddzesxoo63jv7dmlec3bq4yteni
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebznmh3nwdp7cvuukmxqqgt34e5xz2ql377qne7imik5e2ahqwprm

**Comment by Aifabot-Cloud** [comment]
The client followed the allocation plan as planned, good report is all dimensions. Keep it up!

**Comment by Aifabot-Cloud** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebfvwfgmpfms2jihcmy3jg6h4jbshmvpapmf4gp2c7lltoemnwlvw 
#### Address 
> f17uxxk6ibo4h44yohxj6oappy4on2maygafqp2zi
#### Datacap Allocated
> 1.50PiB
#### Signer Address
> f174fg3bqbln3zjnkxtyf6s54txqkr7yqkj6cig7y
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebfvwfgmpfms2jihcmy3jg6h4jbshmvpapmf4gp2c7lltoemnwlvw

**Comment by zcfil** [comment]
checker:manualTrigger

**Comment by VincentShii** [comment]
Keep it open!

**Comment by VincentShii** [comment]
keep open

**Comment by Sunnyiscoming** [comment]
Hello, @VincentShii  per the https://github.com/filecoin-project/notary-governance/issues/922 for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

This information will be reviewed by Fil+ Governance team to confirm validity and then the application will be allowed to move forward for additional notary review.
