### ISSUE TITLE
[DataCap Application] NOAA Geostationary Operational Environmental Satellites (GOES) 16 <2/2>

### ISSUE THREAD

**Issue by VincentShii** [filecoin-project/filecoin-plus-large-datasets#1819]
### Data Owner Name

The National Oceanic and Atmospheric Administration

### Data Owner Country/Region

United States

### Data Owner Industry

Environment

### Website

https://github.com/awslabs/open-data-docs/tree/main/docs/noaa/noaa-goes16

### Social Media

```text
https://www.noaa.gov/
https://twitter.com/NOAA
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

1PiB

### On-chain address for first allocation

f1ikatcd4hcoazfew4hqthdqahgc2vcvinbw45xby

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
organization: Yuga was founded in 2019 with core members mainly from Microsoft, AWS and other major leading organizations. Till now we have about 20 employees in Shanghai office. We've been dedicated to building and optimizing industry-leading order encapsulation components for three years, enabling rapid processing and encapsulation of real data, and continuously empowering storage providers and data content providers.

Project: NOAA is an agency that enriches life through science. Our agency holds key leadership roles in shaping international ocean, fisheries, climate, space and weather policies.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
GOES satellites provide continuous weather imagery and monitoring of meteorological and space environment data across North America.
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### How do you plan to prepare the dataset

lotus

### Please share a sample of the data

```text
https://registry.opendata.aws/noaa-goes/
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

1.5 to 2 years

### In which geographies do you plan on making storage deals

Asia other than Greater China, North America, South America, Europe

### How will you be distributing your data to storage providers

Shipping hard drives, Lotus built-in data transfer

### How do you plan to choose storage providers

Slack, Filmine, Big data exchange, Partners

### How do you plan to make deals to your storage providers

Lotus client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 5PiB

**Expected weekly DataCap usage rate**
> 1PiB

**Client address**
>f1ikatcd4hcoazfew4hqthdqahgc2vcvinbw45xby

**Comment by TimGuo7** [comment]
happy to support after the identity of applicants and sample of data.

**Comment by Casey-PG** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb6kf2pbgf53kyjxmclaqom4y3m5vcqz2y2uhm72iz6kc5tp4o5lc 
#### Address 
> f1ikatcd4hcoazfew4hqthdqahgc2vcvinbw45xby
#### Datacap Allocated
> 256.00TiB
#### Signer Address
> f1d4yb3wags3mtddzesxoo63jv7dmlec3bq4yteni
#### Id
> b5e789fd-7deb-4b0c-8689-e28bfbbcc9c5
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb6kf2pbgf53kyjxmclaqom4y3m5vcqz2y2uhm72iz6kc5tp4o5lc

**Comment by TakiChain** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceddzjzppcg6owgyye3lmjhcilulyewb67fwonfy7ljmd5536sx6yq 
#### Address 
> f1ikatcd4hcoazfew4hqthdqahgc2vcvinbw45xby
#### Datacap Allocated
> 256.00TiB
#### Signer Address
> f15impf3j2zcaex4lhyxndxswuuhv24vzstuqtxsi
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceddzjzppcg6owgyye3lmjhcilulyewb67fwonfy7ljmd5536sx6yq

**Comment by BobbyChoii** [comment]
I checked the information applicant shared and so far everything is in line with filplus program rules. Willing to give my signature in the this round.

**Comment by Meibuy** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacea7eoorybenhfeu7txuh4we5gvtkosxor4udywy45qwcfu5hzsuko 
#### Address 
> f1ikatcd4hcoazfew4hqthdqahgc2vcvinbw45xby
#### Datacap Allocated
> 1.00PiB
#### Signer Address
> f1bwugfihrmn3iyunzyxst5nttql3dge4khwmurtq
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacea7eoorybenhfeu7txuh4we5gvtkosxor4udywy45qwcfu5hzsuko

**Comment by Casey-PG** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecn7tezzydymkupzscmrlfnptwfvnfthtg5lkyyuhfy6hryl5uehc 
#### Address 
> f1ikatcd4hcoazfew4hqthdqahgc2vcvinbw45xby
#### Datacap Allocated
> 2.00PiB
#### Signer Address
> f1d4yb3wags3mtddzesxoo63jv7dmlec3bq4yteni
#### Id
> ae1ee03b-4a58-4ee5-b63f-55c38a2abc0a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecn7tezzydymkupzscmrlfnptwfvnfthtg5lkyyuhfy6hryl5uehc

**Comment by BobbyChoii** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacea6xglzkgqdlr4peov2xi3yxpu4ntrcaitu25a2kdwusqk7fajqca 
#### Address 
> f1ikatcd4hcoazfew4hqthdqahgc2vcvinbw45xby
#### Datacap Allocated
> 2.00PiB
#### Signer Address
> f1irqs2gmctiv3jcdfwuch7oxvf4ixh3k4b2wc24i
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacea6xglzkgqdlr4peov2xi3yxpu4ntrcaitu25a2kdwusqk7fajqca

**Comment by BobbyChoii** [comment]
> I checked the information applicant shared and so far everything is in line with filplus program rules. Willing to give my signature in the this round.

Sorry for the late signing.

**Comment by Aifabot-Cloud** [comment]
checker:manualTrigger

**Comment by Aifabot-Cloud** [comment]
I did Q&A with this client, dataset is authentic and allocation plan is reasonable. Willing to sign for this round!

**Comment by Aifabot-Cloud** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceazp57qlmcbdxqhuyphmjtac3byyrjfd477w7nwtupadxsua55c2o 
#### Address 
> f1ikatcd4hcoazfew4hqthdqahgc2vcvinbw45xby
#### Datacap Allocated
> 1.50PiB
#### Signer Address
> f174fg3bqbln3zjnkxtyf6s54txqkr7yqkj6cig7y
#### Id
> cdc7bd41-2f0f-4606-8778-92a0baf92c5b
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceazp57qlmcbdxqhuyphmjtac3byyrjfd477w7nwtupadxsua55c2o

**Comment by TakiChain** [comment]
No duplicate data or cid sharing observered. I'll give my support for this round.

**Comment by TakiChain** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceclb22ql7zcmnevqvaey4mrgt52y3buij4mn3f4hollbt7psiancu 
#### Address 
> f1ikatcd4hcoazfew4hqthdqahgc2vcvinbw45xby
#### Datacap Allocated
> 1.50PiB
#### Signer Address
> f15impf3j2zcaex4lhyxndxswuuhv24vzstuqtxsi
#### Id
> cdc7bd41-2f0f-4606-8778-92a0baf92c5b
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceclb22ql7zcmnevqvaey4mrgt52y3buij4mn3f4hollbt7psiancu

**Comment by VincentShii** [comment]
Keep it open!

**Comment by VincentShii** [comment]
keep open

**Comment by VincentShii** [comment]
keep open
