### ISSUE TITLE
[DataCap Application] GHTorrent (Tech Greedy)

### ISSUE THREAD

**Issue by xinaxu** [filecoin-project/filecoin-plus-large-datasets#182]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: TechGreedy
- Website / Social Media: https://www.techgreedy.net
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 500 TiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100 TiB
- On-chain address for first allocation: f1uhc5v6w4fkxu6qnecyjkwkcscfuz55mirzosbfq

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Our company has engaged in Slingshot starting 2.1. We have successfully stored more than 30 differerent datasets with 20+ different miners.
```

What is the primary source of funding for this project?
```
Company account.
```

What other projects/ecosystem stakeholders is this project associated with?
```
Slingshot competition hosted by Protocol Lab
```

## Use-case details

Describe the data being stored onto Filecoin
```
The dataset we are storing in this project is GHTorrent
https://ghtorrent.org/
It is an effort to create a scalable, queriable, offline mirror of data offered through the Github REST API.
```

Where was the data in this dataset sourced from?
```
The data is hosted on ghtorrent website and can be downloaded directly by anyone
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
Below is part of commits.csv
12057,"da960ff54f45808c22cf3e207c2032aa2d383929",1217,1217,688,"2012-07-24 00:42:07"
12058,"46d57fcc169644ee772a86afd33f956f5d7f0581",5046,5046,575,"2012-03-11 21:29:42"
12059,"ae64f1c3da47300b65a020649069efa230ce6731",1217,1217,688,"2012-07-02 19:58:16"
12060,"ac3387b9e95cea0caa74fcc7907c4fdf0161fabb",5046,5046,575,"2012-03-10 23:21:37"
12061,"cc4226588f50d4290012a6462a760eee3d85e845",1118,1118,688,"2012-07-02 15:58:45"
12062,"55af0e29bedb446603764985c1a1515bfbad4fb8",5046,5046,575,"2012-03-10 23:10:12"
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes, the dataset can be downloaded via official website by anyone
```

What is the expected retrieval frequency for this data?
```
A few times per year.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
540 days.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Canada, US and EU
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
We will ship hard drives to US and Canada storage providers. For EU providers, we will distribute the data via CDN.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We have a few providers who have been working with us during Slingshot Restore program and we'd like to continue working with them for ongoing Slingshot competition - https://docs.google.com/spreadsheets/d/1Skga2Yn0BD7CDgT1WQmKtPJ3nxhQ4QWd45e78Y42Wjc/edit#gid=0
```

How will you be distributing deals across storage providers?
```
One copy of data for each storage provider.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
We will start in 1-2 weeks once datacap is granted
```

**Comment by galen-mcandrew** [comment]
@xinaxu Can you clarify the difference between this application and #181  ? Are they both for Slingshot competition?

**Comment by xinaxu** [comment]
@galen-mcandrew That's correct. They are both for Slingshot competition, however for different dataset. Per Slingshot rule, each project needs to have different client address to differentiate.

**Comment by xinaxu** [comment]
@galen-mcandrew  Could you take a look at this one? Is there any concern? Anything I can do to fascilitate the grant?

**Comment by galen-mcandrew** [comment]
## Multisig Notary requested
#### Total DataCap requested 
> 500TiB
#### Expected weekly DataCap usage rate 
> 100TiB

**Comment by Fenbushi-Filecoin** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb7dg4xqzbqbr6uq47tdhmzesfryxzqachm7t3rljr7llafhld576 
#### Address 
> f1uhc5v6w4fkxu6qnecyjkwkcscfuz55mirzosbfq
#### Datacap Allocated
> 25.00TiB
#### Signer Address
> f1yqydpmqb5en262jpottko2kd65msajax7fi4rmq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb7dg4xqzbqbr6uq47tdhmzesfryxzqachm7t3rljr7llafhld576

**Comment by Reiers** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaqtdatol445iakjy3uaetc3cifzs7y4txj5eoqxkn4eznphldjwa 
#### Address 
> f1uhc5v6w4fkxu6qnecyjkwkcscfuz55mirzosbfq
#### Datacap Allocated
> 25.00TiB
#### Signer Address
> f1oz43ckvmtxmmsfzqm6bpnemqlavz4ifyl524chq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaqtdatol445iakjy3uaetc3cifzs7y4txj5eoqxkn4eznphldjwa

**Comment by dkkapur** [comment]
Identified an edge case here where the subsequent allocation bot was not triggered since DataCap usage went from < 75% to 100% in between the daily checks. cc @fabriziogianni7 to fix as discussed on Mar 17/18. 

In the meantime, going to manually trigger the next allocation.

**Comment by dkkapur** [comment]
## DataCap Allocation requested

#### Multisig Notary address
> f01726220

#### Client address
> f1uhc5v6w4fkxu6qnecyjkwkcscfuz55mirzosbfq

#### DataCap allocation requested
> 50TiB

**Comment by xinaxu** [comment]
Thanks @dkkapur

**Comment by JimChao1** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceca3ecv4pmfi4vq6b3yxxoyxmlgbuv2xuxwft3p56q2slyyezewdu 
#### Address 
> f1uhc5v6w4fkxu6qnecyjkwkcscfuz55mirzosbfq
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1hlubjsdkv4wmsdadihloxgwrz3j3ernf6i3cbpy
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceca3ecv4pmfi4vq6b3yxxoyxmlgbuv2xuxwft3p56q2slyyezewdu

**Comment by cryptowhizzard** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebtixpm3kic4qpuve6wgaqgbrfyljdhdvsyxjmfqya4kerx5zms7e 
#### Address 
> f1uhc5v6w4fkxu6qnecyjkwkcscfuz55mirzosbfq
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1krmypm4uoxxf3g7okrwtrahlmpcph3y7rbqqgfa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebtixpm3kic4qpuve6wgaqgbrfyljdhdvsyxjmfqya4kerx5zms7e

**Comment by liuziba** [comment]
@dkkapur @fabriziogianni7 The datacap is used up and the allocation bot isn't triggered yet. Would you please take a look and help me manually trigger it? Thanks!

**Comment by xinaxu** [comment]
Current datacap allocation statistics:
| Storage Provider | Number of deals |
| -- | -- |
| f01345523 | 691 |
| f01392893 | 1244 |
| f01732188| 465 |

The datacap for the first 2 rounds are quite small and runs out too soon hence some of the storage providers do not have a chance to get started before the datacap runs out. More storage providers are expected to join in next rounds.

**Comment by JimChao1** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebca4tnlx4pypvta72wxcgg4mef6ioahrcnsrm3cegvvypcwvxhn2 
#### Address 
> f1uhc5v6w4fkxu6qnecyjkwkcscfuz55mirzosbfq
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1hlubjsdkv4wmsdadihloxgwrz3j3ernf6i3cbpy
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebca4tnlx4pypvta72wxcgg4mef6ioahrcnsrm3cegvvypcwvxhn2

**Comment by Fenbushi-Filecoin** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceavrrix7gmikzcajc2xtvyqafiuz3zzfxjuen2uj6tc5bthdlgnfk 
#### Address 
> f1uhc5v6w4fkxu6qnecyjkwkcscfuz55mirzosbfq
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1yqydpmqb5en262jpottko2kd65msajax7fi4rmq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceavrrix7gmikzcajc2xtvyqafiuz3zzfxjuen2uj6tc5bthdlgnfk

**Comment by MegTei** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceadnmauf6cuh6fbnjuzgvuyjzmuw7vyf6pw4mw5v46yssdtu7p75e 
#### Address 
> f1uhc5v6w4fkxu6qnecyjkwkcscfuz55mirzosbfq
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1ystxl2ootvpirpa7ebgwl7vlhwkbx2r4zjxwe5i
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceadnmauf6cuh6fbnjuzgvuyjzmuw7vyf6pw4mw5v46yssdtu7p75e

**Comment by Reiers** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb7tw7hhimhramwt7com6oi74r6kgzwy34zxt5wjq4kutwblej3j2 
#### Address 
> f1uhc5v6w4fkxu6qnecyjkwkcscfuz55mirzosbfq
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1oz43ckvmtxmmsfzqm6bpnemqlavz4ifyl524chq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb7tw7hhimhramwt7com6oi74r6kgzwy34zxt5wjq4kutwblej3j2

**Comment by Fenbushi-Filecoin** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedytxbn4vhkrppz52kac6rz5bapl7irjku2v7xtynuscnce5d6u6a 
#### Address 
> f1uhc5v6w4fkxu6qnecyjkwkcscfuz55mirzosbfq
#### Datacap Allocated
> 125.00TiB
#### Signer Address
> f1yqydpmqb5en262jpottko2kd65msajax7fi4rmq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedytxbn4vhkrppz52kac6rz5bapl7irjku2v7xtynuscnce5d6u6a

**Comment by cryptowhizzard** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceahizp3ay6z4vkwbr3a6id772iyzco5s7yig6cnsycqw6nbrtvcge 
#### Address 
> f1uhc5v6w4fkxu6qnecyjkwkcscfuz55mirzosbfq
#### Datacap Allocated
> 125.00TiB
#### Signer Address
> f1krmypm4uoxxf3g7okrwtrahlmpcph3y7rbqqgfa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceahizp3ay6z4vkwbr3a6id772iyzco5s7yig6cnsycqw6nbrtvcge
