### ISSUE TITLE
[DataCap Application] <WeDAO> - <WeDAO IPFS Store Project>

### ISSUE THREAD

**Issue by snarkzk** [filecoin-project/filecoin-plus-large-datasets#1820]
### Data Owner Name

WeDAO

### Data Owner Country/Region

China

### Data Owner Industry

Web3 / Crypto

### Website

https://wedao.live/

### Social Media

```text
https://wedao.live/
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

600TiB

### On-chain address for first allocation

f1zi6orkyfjiq27iiubwag6vf4qbr3gszs3zwu2qi

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
WEDAO is a decentralized autonomous organization focusing on Web3 construction.WEDAO support Web3 node construction and truly usable Web3 products.WEDAO participants in ecological construction Filecoin,Arweave,Aleo. We are the indispensable marketplace for the Web3 world.We will design a new social product about Live-To-Earn of Web3.We've been paying attention for years.In 2021, we invested in a sealing node.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
The 1000 Genomes Project is an international collaboration which has established the most detailed catalogue of human genetic variation, including SNPs, structural variants, and their haplotype context. There were a total of 3202 individuals sequenced as part of Phase 3 of this project. The high coverage samples were processed using the Illumina DRAGEN v3.5.7b pipeline and are available at s3://1000genomes-dragen/. This dataset contains the VCFs transformed to Parquet/ORC in 3 different schemas - partitioned by samples, partitioned by chromosome and a nested data format.
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### How do you plan to prepare the dataset

lotus, graphsplit, others/custom tool

### If you answered "other/custom tool" in the previous question, enter the details here

```text
We will also use the Swan Client tool (https://github.com/filswan/go-swan-client#Graphsplit) to prepare the dataset.
```

### Please share a sample of the data

```text
s3://1000genomes-dragen
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Monthly

### For how long do you plan to keep this dataset stored on Filecoin

2 to 3 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, South America, Europe

### How will you be distributing your data to storage providers

HTTP or FTP server, IPFS, Shipping hard drives, Others

### How do you plan to choose storage providers

Slack, Partners

### If you already have a list of storage providers to work with, fill out their names and provider IDs below

```text
f0867300
f01981571
f02029115
f0522948
f01228008
f01975316
f01348489
f01975326
f01053413
f01975326
f01947280
f01975338
```

### How do you plan to make deals to your storage providers

Boost client, Lotus client, Others/custom tool

### If you answered "Others/custom tool" in the previous question, enter the details here

```text
Swan Client tool
https://github.com/filswan/go-swan-client
```

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by snarkzk** [comment]
@Sunnyiscoming Hello，this dataset is about 354.3 TiB and have 641687 files. And we will store 8-10 copies with the help of different providers.Thanks.

**Comment by nj-steve** [comment]
@snarkzk Hello , please tell us how much data you have downloaded? And what's your download speed？

**Comment by snarkzk** [comment]
Thanks steve @nj-steve, we have download 60 TiB data,and our speed is about 70TiB/week.

**Comment by Sunnyiscoming** [comment]
![image](https://user-images.githubusercontent.com/105098820/226152302-b4084a97-fea7-4214-8e39-d96c5382b6cf.png)
The website is not available.

**Comment by snarkzk** [comment]
@Sunnyiscoming Sorry, our platform was upgraded this weekend and it is back to normal now.

**Comment by Sunnyiscoming** [comment]
![image](https://user-images.githubusercontent.com/105098820/226596789-87380262-c46c-40ca-9c4e-f1ec48d9ff05.png)
No

**Comment by Sunnyiscoming** [comment]
Could you send an email to filplus-app-review@fil.org with your official domain in order to confirm your identity? Email name should includes the issue id #1820.

**Comment by snarkzk** [comment]
@Sunnyiscoming We have sent email to confirm our identity with the email address of admin@wedao.live. Please check it out.
Thanks.

**Comment by nj-steve** [comment]
@snarkzk the platform is normal recently, please make it stability.

**Comment by nj-steve** [comment]
@snarkzk the platform is normal recently, please make sure the stability.

**Comment by Joss-Hua** [comment]
Who are the SPs you have been in touch with?

**Comment by laurarenpanda** [comment]
Everything looks great.

Would you please provide more details about your distribution plan and how you plan to transfer data to SPs in different locations? And how many copies do you aim to store in the network?

Also, like to know the location of the following SPs, as you mentioned:

> f0867300
> f01981571
> f02029115
> f0522948
> f01228008
> f01975316
> f01348489
> f01975326
> f01053413
> f01975326
> f01947280
> f01975338

**Comment by Joss-Hua** [comment]
The same question.

**Comment by snarkzk** [comment]
@Joss-Hua @laurarenpanda 
We have contacted the SPs with slack or our partners or in the community.And we choose the storage providers these  have been trusted by the community and partners.As I said above we will send 8-10 copies to different SPs.The storage providers that I send storage deals will be at 3 different regions.And all providers must agree that they should store unsealed files and keep these data retrieved anytime.
Thanks.

**Comment by Joss-Hua** [comment]
leave eyes here

**Comment by laurarenpanda** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecsjdbbtzplknraszsgyapsmfo5v535waiqbzp32pzk5wwwh726b6 
#### Address 
> f1zi6orkyfjiq27iiubwag6vf4qbr3gszs3zwu2qi
#### Datacap Allocated
> 256.00TiB
#### Signer Address
> f1bp3tzp536edm7dodldceekzbsx7zcy7hdfg6uzq
#### Id
> 20c9d763-b356-461e-894f-d2526f5e42c1
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecsjdbbtzplknraszsgyapsmfo5v535waiqbzp32pzk5wwwh726b6

**Comment by snarkzk** [comment]
checker:manualTrigger

**Comment by Normalnoise** [comment]
checker:manualTrigger

**Comment by Normalnoise** [comment]
<img width="623" alt="image" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/102578774/a92ff3a1-4364-4db8-a6ef-e9559b74e127">
<img width="630" alt="image" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/102578774/e2f195dc-f60c-4b9c-ad80-12655f32b53b">
 
retrieval is available, but you should distribute the data to more storage providers.

**Comment by Normalnoise** [comment]
In this round, willing to support

**Comment by snarkzk** [comment]
ok, thanks @Normalnoise we will send to more sps

**Comment by Normalnoise** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceboceh3n7tav47hzo5fnkcgcizkgxd7lyz4mnmdygijjstzbfmvdi 
#### Address 
> f1zi6orkyfjiq27iiubwag6vf4qbr3gszs3zwu2qi
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f1c5non5yf35avgcpsqvxu4yj54yyvxorwyjochqq
#### Id
> not found
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceboceh3n7tav47hzo5fnkcgcizkgxd7lyz4mnmdygijjstzbfmvdi

**Comment by Fatman13** [comment]
checker:manualTrigger

**Comment by Fatman13** [comment]
Reached out by the client on Slack. Everything checks out.

**Comment by shliming** [comment]
checker:manualTrigger

**Comment by shliming** [comment]
checker:manualTrigger

**Comment by snarkzk** [comment]
checker:manualTrigger

**Comment by snarkzk** [comment]
checker:manualTrigger

**Comment by snarkzk** [comment]
checker:manualTrigger

**Comment by snarkzk** [comment]
checker:manualTrigger

**Comment by kernelogic** [comment]
CID report LGTM

**Comment by kernelogic** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebtzoaas7eptoi3fedmx7ssshv6vqkrkcj7dhvf2q5avgc5eflotm 
#### Address 
> f1zi6orkyfjiq27iiubwag6vf4qbr3gszs3zwu2qi
#### Datacap Allocated
> 1.00PiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### Id
> 518610a1-4a27-4341-a5c6-b6aa3d2b83fd
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebtzoaas7eptoi3fedmx7ssshv6vqkrkcj7dhvf2q5avgc5eflotm

**Comment by mikezli** [comment]
<img width="901" alt="cc66ab48f0ee90a259548394821b0b4" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/118169683/e59de390-10d0-48a7-8cc1-6baad53a923c">

**Comment by mikezli** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec6y7kbmnk42ejxqx7eeiy4thx4rkeusjyfaz2w77u76rez3uzbcy 
#### Address 
> f1zi6orkyfjiq27iiubwag6vf4qbr3gszs3zwu2qi
#### Datacap Allocated
> 1.00PiB
#### Signer Address
> f1dnb3uz7sylxk6emti3ififcvu3nlufnnsjui6ea
#### Id
> 518610a1-4a27-4341-a5c6-b6aa3d2b83fd
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec6y7kbmnk42ejxqx7eeiy4thx4rkeusjyfaz2w77u76rez3uzbcy

**Comment by snarkzk** [comment]
checker:manualTrigger

**Comment by Joss-Hua** [comment]
checker:manualTrigger

**Comment by snarkzk** [comment]
checker:manualTrigger

**Comment by snarkzk** [comment]
checker:manualTrigger

**Comment by snarkzk** [comment]
checker:manualTrigger

**Comment by snarkzk** [comment]
checker:manualTrigger

**Comment by snarkzk** [comment]
checker:manualTrigger

**Comment by snarkzk** [comment]
checker:manualTrigger

**Comment by snarkzk** [comment]
checker:manualTrigger

**Comment by 1ane-1** [comment]
checker:manualTrigger

**Comment by 1ane-1** [comment]
From this round, report looks all healthy, but hope you can improve your  retrieval rate. This round i will support you.

**Comment by 1ane-1** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced4mjufqnqfzy4iq5w4jgshdyhwpvc2lumkeg66oll4vvbavdmtie 
#### Address 
> f1zi6orkyfjiq27iiubwag6vf4qbr3gszs3zwu2qi
#### Datacap Allocated
> 2.00PiB
#### Signer Address
> f1mdk7s2vntzm6hu35yuo6vjubtrpfnb2awhgvrri
#### Id
> 4dde59fc-77de-4f55-ba96-3acdf5b1ff29
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced4mjufqnqfzy4iq5w4jgshdyhwpvc2lumkeg66oll4vvbavdmtie

**Comment by igoovo** [comment]
Everything is reported to be normal, but please increase the searchable rate.

**Comment by igoovo** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebyjrjdwwro6gelbjwm5s4qg3xg3f7krjpwt4rvv6cwk2qmj4wns6 
#### Address 
> f1zi6orkyfjiq27iiubwag6vf4qbr3gszs3zwu2qi
#### Datacap Allocated
> 2.00PiB
#### Signer Address
> f1shnsfayxqll77svffaxnjenms7bbbysbqcatrpy
#### Id
> 4dde59fc-77de-4f55-ba96-3acdf5b1ff29
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebyjrjdwwro6gelbjwm5s4qg3xg3f7krjpwt4rvv6cwk2qmj4wns6

**Comment by snarkzk** [comment]
checker:manualTrigger

**Comment by snarkzk** [comment]
checker:manualTrigger

**Comment by sxxfuture-official** [comment]
checker:manualTrigger

**Comment by sxxfuture-official** [comment]
This project looks healthy in all respects, and I will support this round.

**Comment by sxxfuture-official** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecoodmtqgbchmai72urblpdizjnhvuba2nub6jfx4ygrmo6s5faqs 
#### Address 
> f1zi6orkyfjiq27iiubwag6vf4qbr3gszs3zwu2qi
#### Datacap Allocated
> 1.25PiB
#### Signer Address
> f1foiomqlmoshpuxm6aie4xysffqezkjnokgwcecq
#### Id
> e01a50e6-b897-442f-8a97-814a8c9c3794
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecoodmtqgbchmai72urblpdizjnhvuba2nub6jfx4ygrmo6s5faqs

**Comment by nj-steve** [comment]
the cid report looks good.and even though the retrieval rate is not very high, all SPs support retrieval.

**Comment by nj-steve** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecvc7h6r5tmitatplrot6w4bex4b5hwih5ijegu23lfm2jekmgtvu 
#### Address 
> f1zi6orkyfjiq27iiubwag6vf4qbr3gszs3zwu2qi
#### Datacap Allocated
> 1.25PiB
#### Signer Address
> f1xx6555qijma7igpnjspyvdunc4vfxkawnpqy5ii
#### Id
> e01a50e6-b897-442f-8a97-814a8c9c3794
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecvc7h6r5tmitatplrot6w4bex4b5hwih5ijegu23lfm2jekmgtvu

**Comment by herrehesse** [comment]
@snarkzk why did you close the application minutes after a 1.25P signature?

@raghavrmadya @kevzak

**Comment by snarkzk** [comment]
@herrehesse Sorry, I don't know the closing rules, please tell me what are the closing rules？I'll follow it later.
