### ISSUE TITLE
[DataCap Application]  MongoStorage - SlingShot Allocated Datasets

### ISSUE THREAD

**Issue by amughal** [filecoin-project/filecoin-plus-large-datasets#1821]
### Data Owner Name

Common Crawl

### Data Owner Country/Region

United States

### Data Owner Industry

Other

### Website

https://commoncrawl.org

### Social Media

```text
None.
```

### Total amount of DataCap being requested

4PiB

### Weekly allocation of DataCap requested

50TiB

### On-chain address for first allocation

f1tefalattwqvw22kstrryh7yoh2blexkl3gs32py

### Data Type of Application

Slingshot

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
MongoStorage is an emerging FileCoin Service Provider. Based in Southern California, USA, and working through a plan, soon to be ESPA certified provider. The founders have vast experience in networks and systems, and have gone through multiple sessions at ESPA trainings organized by PikNik in Vegas.
```

### Is this project associated with other projects/ecosystem stakeholders?

Yes

### If answered yes, what are the other projects/ecosystem stakeholders

```text
MongoStorage is participant in the Slingshot V3, both as SP and DataPrep.
```

### Describe the data being stored onto Filecoin

```text
The Common Crawl project is a corpus of web crawl data composed of over 50 billion web pages. This is the crawl archive for October 2020. The data was crawled between October 19th and November 1st and contains 2.71 billion web pages or 280 TiB of uncompressed content.
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### How do you plan to prepare the dataset

singularity

### Please share a sample of the data

```text
My slingshot dataset allocation:
https://commoncrawl.org/2020/12/nov-dec-2020-crawl-archive-now-available/
https://commoncrawl.org/2020/10/september-2020-crawl-archive-now-available/
https://commoncrawl.org/2020/11/october-2020-crawl-archive-now-available/

slug noaa-global-surface-summary-of-day
slug noaa-national-bathymetric-source-data
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Daily

### For how long do you plan to keep this dataset stored on Filecoin

Less than 1 year

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, Africa, North America, South America, Europe, Australia (continent)

### How will you be distributing your data to storage providers

HTTP or FTP server, IPFS

### How do you plan to choose storage providers

Slack, Big data exchange, Partners

### How do you plan to make deals to your storage providers

Boost client, Lotus client, Singularity

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 4PiB

**Expected weekly DataCap usage rate**
> 50TiB

**Client address**
>f1tefalattwqvw22kstrryh7yoh2blexkl3gs32py

**Comment by amughal** [comment]
Hello @Sunnyiscoming . Is it possible to change the client address to following:

f1rzmkv7i5xni36fq2lvmpdemlqsqfd6nds6matia

Thanks

**Comment by TimGuo7** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedeekzcrv7xbfgjtdfggciqhpa7ulx54v33rcycun3unc6akhcphc 
#### Address 
> f1tefalattwqvw22kstrryh7yoh2blexkl3gs32py
#### Datacap Allocated
> 25.00TiB
#### Signer Address
> f1yslbnnqzrjlyuxsmyxfbqcc7xthcavgpripjevi
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedeekzcrv7xbfgjtdfggciqhpa7ulx54v33rcycun3unc6akhcphc

**Comment by TimGuo7** [comment]
> 

something wrong here, even with the id attached it seems still have this error as id field cannot be found.

**Comment by Sunnyiscoming** [comment]
checker:manualTrigger

**Comment by data-programs** [comment]
<img width="32" alt="KYC" Verified src="https://stable.filplus.storage/images/filplus-kyc-verified-badge.png"/>

This user’s identity has been verified through [filplus.storage](https://filplus.storage)
