### ISSUE TITLE
[DataCap Application]  Lifestyle Metaverse vmeta3

### ISSUE THREAD

**Issue by fdate11** [filecoin-project/filecoin-plus-large-datasets#1822]
### Data Owner Name

vmeta3

### Data Owner Country/Region

China

### Data Owner Industry

Web3 / Crypto

### Website

https://vmeta3.com/

### Social Media

```text
https://twitter.com/Vmeta3Official
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

500TiB

### On-chain address for first allocation

f1pdkgvlokrswpehupn4nokf4aspp3q4erytbt4ri

### Data Type of Application

Public, Open Commercial/Enterprise

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
A Metaverse in our opinion is the real world in a digital space. That's the experience we want our users to have. 

We are a Metaverse that brings together components of Web 3.0 in a highly efficient and synchronized manner such as our Vmeta3 Wallet, Layer-2 Mining, Cross-Chain NFT Marketplace, and Swap. These modules interlock with each other, forming a profitable Metaverse economy hence helping it grow and prosper. The development of each independent module will ultimately improve the growth of any business that aims to harness the Web 3.0 Technology.

We seamlessly and securely facilitate Cross-Chain transmission of informational data, NFTs, and smart contracts across other chains.

Providing a mechanism to exchange tokens between Ethereum scaling solutions and for transferring tokens over a shared layer 1 network quickly and without trust.

Enabling customers with a two-pronged token bridge for Ethereum’s layer 2 networks.

The solution aims to facilitate the rapid movement of a token between layer 2 and a scaling solution’s governance token. 

Using Key Artistic Standards and Instructions based on the Unity engine, the PBR process and emphasizing the real restoration of resources we can truly achieve the relationship between the metaverse and reality,

We understand the requirements of businesses such as virtual fashion that have rigid requirements for expressiveness.

The application of this standard can also expand the types of NFTs and promote the development of NFTs.

We have a unique set of standards that protect the IPs of artists. The original designs minted on VMeta3 Chain will be marked in encrypted files so that the chain will confirm the owner of the NFTs and protect their copyright.

In VMeta3, Digital Identities (DI) are unique online identifiers. A DI is who you are and how you represent yourself in this virtual space. Your DI will have important information about you, like your habits and skills. Having your DI removes the need for physical documentation to prove your identity in the digital world.

Our advertising solution uses blockchain data, a "Peer-to-Peer" advertising solution for sponsors to choose their audiences, and an open source report that shows the marketing expense on the exact audience, ensuring transparency and fairness between audiences and sponsors.

With our virtual fashion technology, you can try on clothes and accessories from the comfort of your own home. The VMeta3 Metaverse is improving how people shop for clothes and accessories. We're making it easier than ever to find the perfect outfit and experience what it feels like to wear them before deciding to buy.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
The data comes from the data provided by the company's research and development department and publicity department.
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### How do you plan to prepare the dataset

IPFS, lotus, singularity

### Please share a sample of the data

```text
https://drive.google.com/file/d/1JT_VpYAMhjQyj34T8lMxpNQz-uXuTWkN/view?usp=sharing
https://drive.google.com/file/d/1LMRfBZstqG7ligNj-VlCeFhZjiHPXj7u/view?usp=share_link
https://drive.google.com/file/d/1W5jCMe2qvnoaciZpEKmMfAhGYHVUQAkj/view?usp=share_lin
https://drive.google.com/file/d/1JWsgkTQ0N96vFKNz5D8iP5B1LQTrFNjc/view?usp=share_linkk
https://drive.google.com/drive/folders/1pS3IodBvhk019PdXGcxLfAbrd2GWWFuw?usp=share_link
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

1.5 to 2 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, Europe

### How will you be distributing your data to storage providers

HTTP or FTP server, IPFS, Shipping hard drives

### How do you plan to choose storage providers

Slack, Filmine

### How do you plan to make deals to your storage providers

Boost client, Lotus client, Singularity

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
Can you provide more data samples or more informations to prove that you have 5 PB data already?
Please list sps you will cooperate with.

**Comment by nj-steve** [comment]
@fdate11 Can you list the providers that you contact with?

**Comment by fdate11** [comment]
You can see on our twitter that we are a metaverse social product based on web3, we have combined NFT, gamefil, defil and other elements, we have obtained many famous investments, and posted many of us on twitter Building a metaverse social video. I believe you and I both know that web3 videos occupy 10 times or even 100 times the space of web2 because of different high-definition, different interactivity, and different usage scenarios. I directly provided the video link on our twitter. It is not easy to make a video, because we need to ensure that every character in the video is original, so we have produced a lot of elements, our total data must exceed 600T, and a lot of new data is added every day :

https://twitter.com/i/status/1616037432977424389
https://twitter.com/i/status/1604037451067977728
https://twitter.com/i/status/1606992951678480384
https://twitter.com/i/status/1557006615207116802
https://drive.google.com/drive/folders/1S2nA5KBqeg3H1E9V3PM9-Jw5dl9r4BGu

We contacted many sps: f01900687, f02048990, f01990772, f02042992, f01932183, f0198905, f02036170, f01111113.The launch of FEVM has made us re-acquainted with Filecoin, hoping to have more opportunities for cooperation.

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 5PiB

**Expected weekly DataCap usage rate**
> 500TiB

**Client address**
>f1pdkgvlokrswpehupn4nokf4aspp3q4erytbt4ri

**Comment by a1991car** [comment]
Can you email filplus-app-review@fil.org using your official domain name to confirm your identity?
Email name should contain Issue ID #1822

**Comment by fdate11** [comment]
![WechatIMG768](https://user-images.githubusercontent.com/116624756/227776991-a8f80c1a-0c72-496e-832d-cad7d08efa66.jpeg)

**Comment by Bitrise0111** [comment]
Hi  @fdate11 
The data that you described is being stored on Filecoin including the company's research. Will you confirm your data are publicly retrievable? 
what's more, which regions are your storage providers in?

**Comment by fdate11** [comment]
Sorry for keeping you waiting, today, the SP we cooperate with is basically confirmed, so I will immediately reply to your answer as soon as possible:
1. Our data is determined to be public and retrievable,
2. My storage providers are in China, Hong Kong, North America, Europe, and Japan. They are:

f01923786

f02079257

f01971675

f01234567

f01932183

**Comment by Bitrise0111** [comment]
Looking for the first round of checker report.

**Comment by stcouldlisa** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceckyy334lrsfobaiosvzo4wjbp6lhdma64fxmpicilsjdgq7tgnpw 
#### Address 
> f1pdkgvlokrswpehupn4nokf4aspp3q4erytbt4ri
#### Datacap Allocated
> 250.00TiB
#### Signer Address
> f1jvvltduw35u6inn5tr4nfualyd42bh3vjtylgci
#### Id
> 274366f5-ff72-46ff-803a-b24ec87696bb
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceckyy334lrsfobaiosvzo4wjbp6lhdma64fxmpicilsjdgq7tgnpw

**Comment by fabriziogianni7** [comment]
## DataCap Allocation requested

#### Multisig Notary address
> f02049625

#### Client address
> f1pdkgvlokrswpehupn4nokf4aspp3q4erytbt4ri

#### DataCap allocation requested
> 500TiB

#### Id
> 124366f5-hf72-56ff-813a-b24ec81236sc

**Comment by fabriziogianni7** [comment]
## DataCap Allocation requested

#### Multisig Notary address
> f02049625

#### Client address
> f1pdkgvlokrswpehupn4nokf4aspp3q4erytbt4ri

#### DataCap allocation requested
> 500TiB

#### Id
> 124366f5-gg72-46ff-813a-c44ec87496rt

**Comment by igoovo** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb7znzft34if5p3nhxekjdoptozxfq5kkqqy5rm5expl6d3kwkmwi 
#### Address 
> f1pdkgvlokrswpehupn4nokf4aspp3q4erytbt4ri
#### Datacap Allocated
> 500.00TiB
#### Signer Address
> f1shnsfayxqll77svffaxnjenms7bbbysbqcatrpy
#### Id
> 124366f5-gg72-46ff-813a-c44ec87496rt
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb7znzft34if5p3nhxekjdoptozxfq5kkqqy5rm5expl6d3kwkmwi

**Comment by zcfil** [comment]
After reading history, I have some questions：

Can you show more data？
Is your data publicly available？

**Comment by fdate11** [comment]
Hello, we have provided more data display, thank you for your attention, https://twitter.com/i/status/1616037432977424389
https://twitter.com/i/status/1604037451067977728
https://twitter.com/i/status/1606992951678480384
https://twitter.com/i/status/1557006615207116802
https://drive.google.com/drive/folders/1S2nA5KBqeg3H1E9V3PM9-Jw5dl9r4BGu

All our data is public, we hope more people can see our project, thank you.

**Comment by zcfil** [comment]
### Request Approve
Your Datacap Allocation Request has been proposed by the Notary

**Message sent to Filecoin Network**
> bafy2bzacedwirhzsmyflkkebcewzxuwts735g4ldz6wuvxll7rqiy6m6pgf2q

**Address**
> f1pdkgvlokrswpehupn4nokf4aspp3q4erytbt4ri

**Datacap Allocated**
> 500.00TiB

**Signer Address**
> f17xummecmkqgjhm4fesktesaieumn7ugarwucwty

**Id**
> d5b65eb7-9310-4391-9fd7-eaadb9dc1f68

**You can check the status of the message here:** https://filfox.info/en/message/bafy2bzacedwirhzsmyflkkebcewzxuwts735g4ldz6wuvxll7rqiy6m6pgf2q

**Comment by luobin544** [comment]
![10011681179516_ pic](https://user-images.githubusercontent.com/4277341/231038828-9ec1b528-15e7-47df-ae9b-5c624f1d0835.jpg)

**Comment by stcouldlisa** [comment]
It seems that the data of one node is relatively concentrated, which does not meet the requirements. Do you have any improvement measures for this?

**Comment by fdate11** [comment]
Sorry, this is caused by the misunderstanding of our employees: we mistakenly thought that as long as the total amount of a single sp is not greater than 5PiB/4=1.25PiB, we found that it turns out that it is the proportion of sp in each round Cannot exceed 25%, not a percentage of the total quota.
It will definitely be improved in the next round, please give us your support!

**Comment by fireflyHZ** [comment]
Yes, the 25% limit cannot be exceeded in each round until the full package is completed. Spot check retrieved two SP searches with no exceptions.

![截图 2023-04-12 16-47-58](https://user-images.githubusercontent.com/100905326/231404423-7092b0e8-49f5-4df0-a715-922e69e76076.png)

**Comment by fireflyHZ** [comment]
### **Request Proposed**
Your Datacap Allocation Request has been proposed by the Notary

Message sent to Filecoin Network
bafy2bzacedxyolng6flkxmws5kaq4edoo3pseqrfics3kp6jjqyqgfe6zc36c

Address
f1pdkgvlokrswpehupn4nokf4aspp3q4erytbt4ri

Datacap Allocated
1000.00TiB

### **Signer Address**
f1fg6jkxsr3twfnyhdlatmq36xca6sshptscds7xa

Id
124366f5-gg72-46ff-813a-c44ec87496rt

You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedxyolng6flkxmws5kaq4edoo3pseqrfics3kp6jjqyqgfe6zc36c###

**Comment by fabriziogianni7** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedxyolng6flkxmws5kaq4edoo3pseqrfics3kp6jjqyqgfe6zc36c 
#### Address 
> f1pdkgvlokrswpehupn4nokf4aspp3q4erytbt4ri
#### Datacap Allocated
> 500.00TiB
#### Signer Address
> f1fg6jkxsr3twfnyhdlatmq36xca6sshptscds7xa
#### Id
> c53f7601-52c1-4533-95d6-2a67ba3d3aec
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedxyolng6flkxmws5kaq4edoo3pseqrfics3kp6jjqyqgfe6zc36c

**Comment by psh0691** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceddgysn75udwbdz5s75kixzr3b6akenlz6d4x7qcx6mmi2q26hyic 
#### Address 
> f1pdkgvlokrswpehupn4nokf4aspp3q4erytbt4ri
#### Datacap Allocated
> 1.00PiB
#### Signer Address
> f1qdko4jg25vo35qmyvcrw4ak4fmuu3f5rif2kc7i
#### Id
> c53f7601-52c1-4533-95d6-2a67ba3d3aec
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceddgysn75udwbdz5s75kixzr3b6akenlz6d4x7qcx6mmi2q26hyic

**Comment by psh0691** [comment]
![WechatIMG241](https://user-images.githubusercontent.com/69004801/231476720-2b11acb5-bbf8-46eb-a6dd-8e77be9b8072.jpeg)

**Comment by stcouldlisa** [comment]
checker:manualTrigger

**Comment by maxvint** [comment]
checker:manualTrigger

**Comment by bq1024** [comment]
I tried to retrieve a file but was stuck here, can you take a look? The deal ID is 33052139

<img width="829" alt="Screen Shot 2023-04-18 at 3 28 52 PM" src="https://user-images.githubusercontent.com/78975968/232885224-5fd88f14-5d3c-4204-86ec-1c634cd0b463.png">

**Comment by fdate11** [comment]
Dear notary, I am very glad to see that you pointed out our problem. All of our sp have stored unsealed files, which can be retrieved. Regarding your problem, our operation and maintenance personnel will check again and find that it is not possible to connect to the internal net, we're actively working on it. Please check other sp, the retrieval of other sp is very normal.

**Comment by fdate11** [comment]
<img width="885" alt="WX20230419-112710@2x" src="https://user-images.githubusercontent.com/116624756/232959572-25a68388-a9f3-44b6-be26-474e57f58823.png">

**Comment by fdate11** [comment]
<img width="885" alt="WX20230419-112710@2x" src="https://user-images.githubusercontent.com/116624756/232959842-742bc03b-3733-4fa9-98d6-4d6c7f08c709.png">

**Comment by bq1024** [comment]
> I tried to retrieve a file but was stuck here, can you take a look? The deal ID is 33052139
> 
> <img alt="Screen Shot 2023-04-18 at 3 28 52 PM" width="829" src="https://user-images.githubusercontent.com/78975968/232885224-5fd88f14-5d3c-4204-86ec-1c634cd0b463.png">

I tried again and it worked. It was slow due to sp's geo location. The checker report looks fine, willing to support.
<img width="672" alt="Screen Shot 2023-04-18 at 3 50 27 PM" src="https://user-images.githubusercontent.com/78975968/232959071-5b6095f8-c5dc-4be8-9922-f3d25e68c7f2.png">

**Comment by bq1024** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebbeqjow56kh73ysoogx2smdqcuwtzngavg3tajlq44jnk5of6bxi 
#### Address 
> f1pdkgvlokrswpehupn4nokf4aspp3q4erytbt4ri
#### Datacap Allocated
> 1000.00TiB
#### Signer Address
> f1pkjtavqx4r2q2w3he3jknfc5mo2vgfimccmpnaa
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebbeqjow56kh73ysoogx2smdqcuwtzngavg3tajlq44jnk5of6bxi

**Comment by SuperChaiChai** [comment]
<img width="887" alt="image" src="https://user-images.githubusercontent.com/42091141/232963900-644eeef4-8eb6-412d-9ae3-de841d011896.png">

**Comment by SuperChaiChai** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceczyz2ptoriljsnw44fn7u3gzcl2fl5uugt5rbygqhapirbgz5rai 
#### Address 
> f1pdkgvlokrswpehupn4nokf4aspp3q4erytbt4ri
#### Datacap Allocated
> 1000.00TiB
#### Signer Address
> f12mckci3omexgzoeosjvstcfxfe4vqw7owdia3da
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceczyz2ptoriljsnw44fn7u3gzcl2fl5uugt5rbygqhapirbgz5rai

**Comment by stcouldlisa** [comment]
checker:manualTrigger

**Comment by luobin544** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedmok6ows72znxodp4bz6umgx5eu3rmaejidyiax5byr2n5bepwd6 
#### Address 
> f1pdkgvlokrswpehupn4nokf4aspp3q4erytbt4ri
#### Datacap Allocated
> 2.29PiB
#### Signer Address
> f1tbd632f6w62glfaf7wjpimacbnjiz26poyoes2q
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedmok6ows72znxodp4bz6umgx5eu3rmaejidyiax5byr2n5bepwd6

**Comment by Aaron01230** [comment]
We check the full report and the data distribution is healthy and can be retrieved. so we support this round.
<img width="1194" alt="image" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/107668727/2add9dd1-ee7a-4884-bc7c-fbe9ec14995c">

**Comment by Aaron01230** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecrsv6bkd7hnowdtchis2ngrr6hzgwp7etqhm35cqqml2dxojqvk4 
#### Address 
> f1pdkgvlokrswpehupn4nokf4aspp3q4erytbt4ri
#### Datacap Allocated
> 2.29PiB
#### Signer Address
> f1xrnysd4gimg64d4l6qi7ulzwwq22c6vfg6lpw3i
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecrsv6bkd7hnowdtchis2ngrr6hzgwp7etqhm35cqqml2dxojqvk4
