### ISSUE TITLE
[DataCap Application] https://www.cdstm.cn/

### ISSUE THREAD

**Issue by lyjmry** [filecoin-project/filecoin-plus-large-datasets#1824]
### Data Owner Name
中国数字科技馆

### Data Owner Country/Region
China

### Data Owner Industry
Education & Training

### Website
[https://www.cdstm.cn/](https://www.cdstm.cn/)

### Social Media
wechat:cdstm2013 

### Total amount of DataCap being requested
5 PiB

### Weekly allocation of DataCap requested
500 TiB

### On-chain address for first allocation
f1devrnw74736ha43ofk77zzzkgyuce4f22mq535y

### Data Type of Application
Public, Open Dataset (Research/Non-Profit)

### Custom multisig
No

### Share a brief history of your project and organization
The China Digital Science and Technology Museum is a national public welfare science popularization service platform based on Internet communication jointly built by the China Association for Science and Technology, the Ministry of Education and the Chinese Academy of Sciences. The China Digital Science and Technology Museum aims to stimulate public interest in science and improve public scientific quality. It aims to build an online science popularization park for the entire public, especially for young people. On the platform of the China Digital Science and Technology Museum, the public can increase scientific knowledge, experience scientific processes, stimulate creative inspiration, understand technological trends, and share rich popular science resources.

### Is this project associated with other projects/ecosystem stakeholders?
No

### Describe the data being stored onto Filecoin
The data are public welfare education books, videos, pictures, etc. developed and supported by China's national public welfare institutions

### Where was the data currently stored in this dataset sourced from
My own storage infra

### How do you plan to prepare the dataset
lotus

### Please share a sample of the data
https://drive.google.com/drive/folders/1GMr6l1EKzpOnFDoD1r0mNozg_M7ZDfYK

### Confirm that this is a public dataset that can be retrieved by anyone on the Network
Yes

### What is the expected retrieval frequency for this data
Yearly

### For how long do you plan to keep this dataset stored on Filecoin
Permanently

### In which geographies do you plan on making storage deals
Greater China

### How will you be distributing your data to storage providers
HTTP or FTP server

### How do you plan to choose SP
I don't know yet

### If you already have a list of storage providers to work with, fill out their names and provider IDs below
NA

### How do you plan to make deals to your storage providers
Lotus client

### Can you confirm that you will follow the Fil+ guideline
Yes

**Comment by Sunnyiscoming** [comment]
![image](https://user-images.githubusercontent.com/105098820/225939058-1b9a2177-c18d-454c-ad6f-3113e538f95f.png)
No rights to check data samples.
Could you send an email to filplus-app-review@fil.org with your official domain in order to confirm your identity? Email name should includes the issue id #1824.

**Comment by lyjmry** [comment]
> ilplus-app-review@fil.org

https://drive.google.com/drive/folders/1GMr6l1EKzpOnFDoD1r0mNozg_M7ZDfYK?usp=share_link

**Comment by nj-steve** [comment]
@lyjmry Hello，Can you  list SPs you have contacted with at present?

**Comment by lyjmry** [comment]
> @lyjmry Hello，Can you list SPs you have contacted with at present?

f02056275  HongKong
f02061213  HEILONGJIANG CHIA

**Comment by Sunnyiscoming** [comment]
No email received.

**Comment by Sunnyiscoming** [comment]
Any update here?

**Comment by lyjmry** [comment]
I've notified them, but they seem to have a problem

**Comment by Sunnyiscoming** [comment]
I have received an email from 163 email address. You can send your business license to verify your identity.

**Comment by lyjmry** [comment]
Hello, there is no business license, because it is a public institution.

**Comment by lyjmry** [comment]
> I have received an email from 163 email address. You can send your business license to verify your identity.

hello, please pay attention to @163's email

**Comment by Sunnyiscoming** [comment]
I have not received that. Please check it again.

**Comment by Sunnyiscoming** [comment]
It will be closed if no reply in 3 days.

**Comment by data-programs** [comment]
<img width="32" alt="KYC" Verified src="https://stable.filplus.storage/images/filplus-kyc-verified-badge.png"/>

This user’s identity has been verified through [filplus.storage](https://filplus.storage)
