### ISSUE TITLE
[DataCap Application] <CS Render> - <CS Opendata Store>

### ISSUE THREAD

**Issue by shliming** [filecoin-project/filecoin-plus-large-datasets#1825]
### Data Owner Name

CS Render

### Data Owner Country/Region

China

### Data Owner Industry

IT & Technology Services

### Website

http://www.csrender.com/

### Social Media

```text
1.http://www.csrender.com/
2.WeChat Official Account（微信公众号）：CSRender云渲染
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

500TiB

### On-chain address for first allocation

f1tkizizsc37mz525q2rbgxdq7bhb2skj65ccusda

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
CS Render is a rendering service cloud platform that is developed independently. We are well known in China in 3D production, digital media, architectural design, film special effects, animation games, advertising and other industries.We are interested in filecoin, and we've been paying attention for years.In 2020, we invested in a sealing node.Now we want to store some opendata of 2D or 3D to filecoin net to promote ecological development .
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
The Smithsonian’s mission is the "increase and diffusion of knowledge" and has been collecting since 1846. The Smithsonian, through its efforts to digitize its multidisciplinary collections, has created millions of digital assets and related metadata describing the collection objects. On February 25th, 2020, the Smithsonian released over 2.8 million CC0 interdisciplinary 2-D and 3-D images, related metadata, and additionally, research data from researches across the Smithsonian. The 2.8 million "open access" collections are a subset of the Smithsonian’s 155 million objects, 2.1 million library volumes and 156,000 cubic feet of archival collections held in 19 museums, 9 research centers, libraries, archives and the National Zoo. Digitization of collections is ongoing.
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### How do you plan to prepare the dataset

lotus, graphsplit, others/custom tool

### If you answered "other/custom tool" in the previous question, enter the details here

```text
The other tool is the Swan Client tool (https://github.com/filswan/go-swan-client#Graphsplit) to prepare the dataset.
```

### Please share a sample of the data

```text
s3://smithsonian-open-access/
all data is about 451.4TiB
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Monthly

### For how long do you plan to keep this dataset stored on Filecoin

2 to 3 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, South America, Europe, Australia (continent)

### How will you be distributing your data to storage providers

HTTP or FTP server, IPFS, Shipping hard drives, Others

### How do you plan to choose storage providers

Slack, Partners

### If you already have a list of storage providers to work with, fill out their names and provider IDs below

```text
f0839509
f0867300
f01348489
f0522948
f01228008
f01053413
f01975316
f01975326
f01390330
f01975336
f01402814
f01225882
f01975338
```

### How do you plan to make deals to your storage providers

Boost client, Lotus client, Others/custom tool

### If you answered "Others/custom tool" in the previous question, enter the details here

```text
The othser tool is Swan Client tool
https://github.com/filswan/go-swan-client
```

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by nj-steve** [comment]
@shliming Hello , please tell us why do you want to store these data? how much data you have downloaded? And what's your download speed？

**Comment by shliming** [comment]
@nj-steve 
1.We are very interested in these data ,and we want share these data in filecoin net. the Smithsonian released over 2.8 million CC0 interdisciplinary 2-D and 3-D images, related metadata.
2.We've been downloading data for the last two weeks，and the download speed is about 60TiB per week.

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 5PiB

**Expected weekly DataCap usage rate**
> 500TiB

**Client address**
>f1tkizizsc37mz525q2rbgxdq7bhb2skj65ccusda

**Comment by nj-steve** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceddfbvhbrtgi3tw3qaf3w3oahfhqvyk6bqq55qm6opclyv452mrxu 
#### Address 
> f1tkizizsc37mz525q2rbgxdq7bhb2skj65ccusda
#### Datacap Allocated
> 250.00TiB
#### Signer Address
> f1xx6555qijma7igpnjspyvdunc4vfxkawnpqy5ii
#### Id
> 5e5b0faf-2134-46d4-b7f6-877541993cef
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceddfbvhbrtgi3tw3qaf3w3oahfhqvyk6bqq55qm6opclyv452mrxu

**Comment by bq1024** [comment]
Hi @shliming, how many copies will you distribute to the storage providers? How did you find the storage providers you listed? How do you plan to send deals to these storage providers?

**Comment by shliming** [comment]
@bq1024

**Comment by shliming** [comment]
Thanks @bq1024
1.We will store 8-10 copies with different SPs.
2.We find the SPs with slack or our partners or in the community.We will choose the storage providers these we are familiar with or we have worked with or will be believed in the community.
3.The storage providers that I send storage deals will be at 3 different regions.And all providers must agree that they should store unsealed files and keep these data retrieved anytime.

**Comment by bq1024** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedhgsqjmfqnb5tqh6ex4pzjotiombpsgonuy4uo6isrg2aatx4r76 
#### Address 
> f1tkizizsc37mz525q2rbgxdq7bhb2skj65ccusda
#### Datacap Allocated
> 250.00TiB
#### Signer Address
> f1pkjtavqx4r2q2w3he3jknfc5mo2vgfimccmpnaa
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedhgsqjmfqnb5tqh6ex4pzjotiombpsgonuy4uo6isrg2aatx4r76

**Comment by shliming** [comment]
checker:manualTrigger

**Comment by shliming** [comment]
checker:manualTrigger

**Comment by shliming** [comment]
checker:manualTrigger

**Comment by shliming** [comment]
checker:manualTrigger

**Comment by raghavrmadya** [comment]
Pause allocations. This applications severely lacks notary DD @nj-steve @bq1024 , what gives you confidence this client is real?

**Comment by nj-steve** [comment]
Hello @raghavrmadya thanks for your question. The client contacted me from community slack. I thought the client was KYC certified, so it was triggered to ready to sign.

**Comment by nj-steve** [comment]
Hello @shliming Can you send your business license to filplus-app-review@fil.org?

**Comment by shliming** [comment]
@bq1024 @raghavrmadya @nj-steve Hello notaries ，we send the email by gaoyunyue@csrender.com again.
please check it for me. 
Thanks.

**Comment by herrehesse** [comment]
checker:manualTrigger

**Comment by shliming** [comment]
@Sunnyiscoming hello, please help me to check the email about the information of our company.

**Comment by shliming** [comment]
@Sunnyiscoming hello, please help us to change the label,we have already done the kyc by email.

**Comment by shliming** [comment]
keep

**Comment by shliming** [comment]
keep

**Comment by shliming** [comment]
need keeping

**Comment by shliming** [comment]
need keeping

**Comment by shliming** [comment]
hello , this client need keeping

**Comment by shliming** [comment]
keep

**Comment by shliming** [comment]
keep

**Comment by shliming** [comment]
checker:manualTrigger

**Comment by woshidama323** [comment]
LGTM Will support

![data](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/11014169/fe729863-6439-4bb9-b363-4cbd8e781178)

**Comment by woshidama323** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceanipcb5gwr7voqpbuanwbdrivm2beavnmpyumwrdba74gss27rje 
#### Address 
> f1tkizizsc37mz525q2rbgxdq7bhb2skj65ccusda
#### Datacap Allocated
> 500.00TiB
#### Signer Address
> f12tk3adljauwnd3hjbigpfxb7b7gdlj63p6afwtq
#### Id
> ad1be8d5-1120-4dbd-b93a-e2d036c49d41
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceanipcb5gwr7voqpbuanwbdrivm2beavnmpyumwrdba74gss27rje

**Comment by Sunnyiscoming** [comment]
Hello, @shliming per the https://github.com/filecoin-project/notary-governance/issues/922 for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

This information will be reviewed by Fil+ Governance team to confirm validity and then the application will be allowed to move forward for additional notary review.

**Comment by shliming** [comment]
checker:manualTrigger

**Comment by shliming** [comment]
@Sunnyiscoming Thanks, we'll fill in the form as soon as possible

**Comment by shliming** [comment]
@Sunnyiscoming hello, we have submitted the registration form, please check it.

**Comment by shliming** [comment]
checker:manualTrigger

**Comment by Filplus-govteam** [comment]
no form submitted, closing until clear SP list is provided showing entity and location

**Comment by shliming** [comment]
Hello @Filplus-govteam we submitted the registration form again, please check it.
<img width="737" alt="图片" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/116863228/447ee1b7-2ce1-4e78-b374-285469cd9818">
Because this registration form can only be filled with 7 SPs, and the other SP's infomation is below：

| SP ID          | Organization |  City           |   Country |
| ------         | ------            | ------         | ------     | 
| f02826888 | chimsen       |Toronto      | Canada |

@Sunnyiscoming @kevzak @Filplus-govteam 
Please help us to reopen it. Thanks！

**Comment by Filplus-govteam** [comment]
SPs provided
f02132642 | laura  QC.sg | Singapore | 
f02827777 | lisj | l chimsen | India | 
f02372022 | William | IPFSUP | Japan | 
f02825666 | AntWu |  MiningIn | Korea | 
f02806894 | lisj |chimsen | Korea | 
f02836485 | Likui |  StorageTrust | China | 
f02229545 | Allen |  WanghuiNet | US |
f02826888 | chimsen | Toronto | Canada

**Comment by Filplus-govteam** [comment]
SPs taking deals showing under VPN:
f02372022 | Ōi, Saitama, JPThe Constant Company, LLC | 49.50 TiB | 12.34% | 49.50 TiB | 0.00%
f02826888 | Toronto, Ontario, CAThe Constant Company, LLC | 49.50 TiB | 12.34% | 49.50 TiB | 0.00%
f02827777new | Mumbai, Maharashtra, INThe Constant Company, LLC | 40.20 TiB | 10.02% | 40.20 TiB | 0.00%
f02806894 | Paripark, Seoul, KRThe Constant Company, LLC | 23.92 TiB | 5.96% | 23.92 TiB | 0.00%

please provide proof of location of these SPs and email to filplus.govteam@gmail.com

**Comment by shliming** [comment]
checker:manualTrigger

**Comment by shliming** [comment]
checker:manualTrigger

**Comment by shliming** [comment]
checker:manualTrigger
