### ISSUE TITLE
[DataCap Application] < Edwardext> - <Mouse Brain Dataset>

### ISSUE THREAD

**Issue by edwardext** [filecoin-project/filecoin-plus-large-datasets#1827]
### Data Owner Name

IBL/Allen/Janelia 

### Data Owner Country/Region

United States

### Data Owner Industry

Life Science / Healthcare

### Website

https://alleninstitute.org ;https://www.janelia.org/ ;https://www.internationalbrainlab.com/

### Social Media

```text
https://twitter.com/AllenInstitute；
https://twitter.com/IntlBrainLab
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

400TiB

### On-chain address for first allocation

f16hot3sxrgnfmqluqzx7kq76xo7juyknrrubdp3y

### Data Type of Application

None

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
I am a researcher and developer in blockchain technology.        
In 2020, I participated in the Filecoin Space Race as a member of the technical support team, providing technical assistance to other service providers (SPs).       
I am deeply interested in Filecoin's complex storage system and have a deep understanding of mining technology, as well as extensive industry experience.        
Through system optimization, hardware matching optimization, and process optimization, I have developed a mining system based on Lotus that is suitable for large-scale production.
I have a team of three developers in China, and we are currently developing an ecosystem application based on FVM.
Based on my recognition of Filecoin's valid data, I would like to provide the public dataset as valid data storage and recommend it to SPs that I know or work with.
I will supervise and guide my collaborating SPs to strictly follow the valid data  encapsulating rules established by the community.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
This is a dataset about the mouse brain.  
The data of mouse brain helps researchers to better understand brain function and mechanisms, identify potential drug targets, and design new therapies for brain diseases.  This has significant implications for the fields of neuroscience and medicine.
The data owners are  the following institutions:
Allen Institute
Janelia Research Campus
International Brain Laboratory
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### How do you plan to prepare the dataset

others/custom tool

### If you answered "other/custom tool" in the previous question, enter the details here

```text
Self-developed packing tool
```

### Please share a sample of the data

```text
https://registry.opendata.aws/
s3://allen-mouse-brain-atlas/
s3://ibl-brain-wide-map-public/  
s3://janelia-mouselight-imagery/
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Sporadic

### For how long do you plan to keep this dataset stored on Filecoin

1 to 1.5 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, South America, Europe, Australia (continent)

### How will you be distributing your data to storage providers

HTTP or FTP server, Shipping hard drives, Others

### How do you plan to choose storage providers

Partners, Others

### If you already have a list of storage providers to work with, fill out their names and provider IDs below

```text
If I determine the storage provider, I will update it intime.
```

### How do you plan to make deals to your storage providers

Lotus client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 5PiB

**Expected weekly DataCap usage rate**
> 400TiB

**Client address**
>f16hot3sxrgnfmqluqzx7kq76xo7juyknrrubdp3y

**Comment by Sunnyiscoming** [comment]
Whether this dataset is public?

**Comment by edwardext** [comment]
Hi  @Sunnyiscoming,thank you for your review.
  
  > Whether this dataset is public?
  
Yes, this is a public dataset compiled from AWS. The significance of submitting this comprehensive dataset is to enable faster and more centralized searching of basic data for mouse brain research in the future.
At the same time, under the premise of decentralized storage, I want to focus on storing the data in Asia and Greater China, in order to improve the retrieval efficiency of scientific research data in this region.
The overall allocation plan is as follows:
European 2 copies
Americas 2 copies
Oceania 2 copies
Greater China 2 copies
Asia minus GCR   2 copies

**Comment by NewHuoPool** [comment]
Can you provide more detailed information about storage providers participated in this program, such as you can list SPs you have contacted with at present?

**Comment by edwardext** [comment]
@NewHuoPool  thanks for asking.
The SPs that will participate in the collaboration are as follows,
f01980952	CN
f01943941	CN
f0150816	        CN
f02031264	SGP
f02052244	US
f02052252	US

**Comment by NewHuoPool** [comment]
Ok, I will support this round and hope you follow the rules in the future. I will keep an eye on the check report.

**Comment by DirectionTechnology** [comment]
Hello,applicant
We are very concerned about the retrievability of data, which is also the meaning of fil+. 
You have provided a collection of three datasets. I would like to know how to accurately retrieve the specified dataset.

**Comment by edwardext** [comment]
@DirectionTechnology thanks for your DD
This data collection will be stored in a categorized manner, marked according to the type of dataset, and associated CIDs recorded. Queries can be made based on the corresponding CID list, and all information is publicly available.

**Comment by edwardext** [comment]
checker:manualTrigger

**Comment by Tom-OriginStorage** [comment]
According to the robot report, there are only two nodes at present, can you briefly explain the follow-up packaging plan

**Comment by Tom-OriginStorage** [comment]
Okay, I will continue to follow up in the future

**Comment by Tom-OriginStorage** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceal26xwvxvbb53axrhg2itw3wfcgdnd4gjwe72ri777pmwhps4jw4 
#### Address 
> f16hot3sxrgnfmqluqzx7kq76xo7juyknrrubdp3y
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1q6bpjlqia6iemqbrdaxr2uehrhpvoju3qh4lpga
#### Id
> 9b53fa06-57cf-449d-9627-15d900ff5fa0
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceal26xwvxvbb53axrhg2itw3wfcgdnd4gjwe72ri777pmwhps4jw4

**Comment by NiwanDao** [comment]
![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/72185104/80beccc0-7317-4f96-830e-5bbbe21cbd68)
I will support this tranche

**Comment by NiwanDao** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecdb2prlnlajbx2lwvnegzmnruyx5xiydxopzsewi6cu4ynu6qji2 
#### Address 
> f16hot3sxrgnfmqluqzx7kq76xo7juyknrrubdp3y
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1a2lia2cwwekeubwo4nppt4v4vebxs2frozarz3q
#### Id
> 9b53fa06-57cf-449d-9627-15d900ff5fa0
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecdb2prlnlajbx2lwvnegzmnruyx5xiydxopzsewi6cu4ynu6qji2

**Comment by Dave-lgtm** [comment]
checker:manualTrigger

**Comment by cryptowhizzard** [comment]
> Hi @Sunnyiscoming,thank you for your review.
> 
> > Whether this dataset is public?
> 
> Yes, this is a public dataset compiled from AWS. The significance of submitting this comprehensive dataset is to enable faster and more centralized searching of basic data for mouse brain research in the future. At the same time, under the premise of decentralized storage, I want to focus on storing the data in Asia and Greater China, in order to improve the retrieval efficiency of scientific research data in this region. The overall allocation plan is as follows: European 2 copies Americas 2 copies Oceania 2 copies Greater China 2 copies Asia minus GCR 2 copies

How did this go?

**Comment by edwardext** [comment]
checker:manualTrigger

**Comment by edwardext** [comment]
SP has the right to choose what kind of service provider to use as long as the SP meets our storage conditions.
Our selection of SPs is primarily based on Fil+ rules:
--Data retrievability
--Selection of storage providers distributed in different regions
--Storage according to our specified data requirements, including DC allocation, CAR file allocation, replica storage, etc.
Currently, every SP we work with has gone through a long period of adjustment (such as package progress and data allocation requirements), which undoubtedly comes at a cost of sacrificing a lot (especially time costs). Despite this, we are still constantly communicating and optimizing.

**Comment by edwardext** [comment]
checker:manualTrigger

**Comment by edwardext** [comment]
Things are progressing as planned

**Comment by edwardext** [comment]
We are communicating with new SPs

**Comment by edwardext** [comment]
Communicating with new SPs

**Comment by edwardext** [comment]
Update

**Comment by edwardext** [comment]
Ongoing

**Comment by edwardext** [comment]
Ongoing

**Comment by edwardext** [comment]
Ongoing

**Comment by edwardext** [comment]
Ongoing

**Comment by cryptowhizzard** [comment]
Dear edwardext,

As notary I am doing due diligence on your LDN. I could not get retrieval to work. Can you please upload the car file of CID baga6ea4seaqpgcjy3ehwgbnbgx5pkoeoqwvfasqd3i2ei4zwr5wvdkbx2aomsji ?

You can use our upload system at http://send.datasetcreators.com. Please select 7 days for the system to keep the file and post the link you received here so I (and other notaries) can download your content.

**Comment by edwardext** [comment]
Message received, will handle promptly

**Comment by edwardext** [comment]
thanks for your reminding , please keep it open

**Comment by edwardext** [comment]
Ongoing

**Comment by edwardext** [comment]
Ongoing

**Comment by edwardext** [comment]
please keep it open

**Comment by edwardext** [comment]
Ongoing

**Comment by edwardext** [comment]
Ongoing

**Comment by edwardext** [comment]
Ongoing

**Comment by Sunnyiscoming** [comment]
Hello, @edwardext per the https://github.com/filecoin-project/notary-governance/issues/922 for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

This information will be reviewed by Fil+ Governance team to confirm validity and then the application will be allowed to move forward for additional notary review.

**Comment by edwardext** [comment]
The form has been submitted

**Comment by sxxfuture-official** [comment]
@edwardext 
can you explain this？
![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/113963951/2895cc67-4b92-4f5c-bdfa-dfdfa7f89011)

**Comment by a1991car** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecnoxi23e2shnvgtz6y5rp5wlnlhba5xgwga4ezedeyvcpjbzs524 
#### Address 
> f16hot3sxrgnfmqluqzx7kq76xo7juyknrrubdp3y
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1qnumecdypgrbaebtkdfjnwt5ndacadcuas3deiq
#### Id
> 2a08d4f6-1b2b-4e9d-9be1-1b8a68815545
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecnoxi23e2shnvgtz6y5rp5wlnlhba5xgwga4ezedeyvcpjbzs524

**Comment by sxxfuture-official** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedygxamx4myzr2znimqmfdmtcui6mkvt2ddudmn43ac7gkbyfrzva 
#### Address 
> f16hot3sxrgnfmqluqzx7kq76xo7juyknrrubdp3y
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1foiomqlmoshpuxm6aie4xysffqezkjnokgwcecq
#### Id
> 2a08d4f6-1b2b-4e9d-9be1-1b8a68815545
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedygxamx4myzr2znimqmfdmtcui6mkvt2ddudmn43ac7gkbyfrzva

**Comment by herrehesse** [comment]
checker:manualTrigger

**Comment by herrehesse** [comment]
![Screenshot 2023-11-29 at 09 19 16](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/70132857/a6bc1a98-2fdd-4888-bd71-d6038ba11176)

Fully self-dealing with fake VPN locations. @sxxfuture-official why are you signing on abuse?

@Filplus-govteam close this LDN.

**Comment by Filplus-govteam** [comment]
SPs taking deals
f02031264 | Singapore, Singapore, SGAmazon.com, Inc. | 100.00 TiB | 49.98% | 100.00 TiB | 0.00%
f02048808 | São Paulo, São Paulo, BRAmazon.com, Inc. | 26.38 TiB | 13.18% | 26.31 TiB | 0.24%
f02052252 | Boardman, Oregon, USAmazon.com, Inc. | 26.06 TiB | 13.03% | 26.00 TiB | 0.24%
f02032453 | Abu Dhabi, Abu Dhabi, AEAmazon.com, Inc. | 25.94 TiB | 12.96% | 25.94 TiB | 0.00%
f02058976 | Sydney, New South Wales, AUAmazon.com, Inc. | 21.69 TiB | 10.84% | 21.69 TiB | 0.00%

SPs listed
SP 1	f02048808	Andrew	BR	y	n/a
SP 2	f02032453	Nathaniel		AE	y	Nathaniel
SP 3	f02052252	Erick	US	y	eric
SP 4	f02031264	oliver lu	SGP	y	oliver
SP 5	f02058976	LEO		AU	y	LEO

Oliver email doesn't exist.

**Comment by edwardext** [comment]
> SPs listed SP 1 f02048808 Andrew BR y n/a SP 2 f02032453 Nathaniel AE y Nathaniel SP 3 f02052252 Erick US y eric SP 4 f02031264 oliver lu SGP y oliver SP 5 f02058976 LEO AU y LEO
> Oliver email doesn't exist.

The info. has been submitted through the table.

**Comment by herrehesse** [comment]
Merged set, VPN abuse, fake distribution, fake miners, fake businesses. Guys? Close?

**Comment by Filplus-govteam** [comment]
Closing until clear SP entity and location information is provided for SPs taking deals.

Gather information from SPs and send all information to filplus.govteam@gmail.com
