### ISSUE TITLE
[DataCap Allocation] - kuoye (Shanghai) Data Technology Co., LTD

### ISSUE THREAD

**Issue by Kuoyeshuju** [filecoin-project/filecoin-plus-large-datasets#1830]
---
name: Large Dataset Notary application
about: Clients should use this application form to request a DataCap allocation via a LDN for a dataset
title: "[DataCap Application] - kuoye (Shanghai) Data Technology Co., LTD"
labels: 'application, Phase: Diligence'
assignees: ''

---
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: kuoye (Shanghai) Data Technology Co., LTD
- Website / Social Media: Website http://kuoyeshuju.com/    Social Media Wechat:Shanghai kuoye data 
- Region: Greater China Region
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100TiB
- On-chain address for first allocation: f1klzdf2ksdfqe7gaz6hrvobsr7xjyplyzi5o4vmy

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Engaged in data science and technology, computer information technology, intelligent technology, Internet technology in the field of technology development, technical consultation, technical services, technology transfer, computer data processing, computer information system integration, security engineering, computer services, computer software development, cloud software services, cloud platform services, computer, software and auxiliary equipment, communication equipment, intelligent equipment wholesale, retail, telecommunications business.
```

What is the primary source of funding for this project?
```
Financing
```

What other projects/ecosystem stakeholders is this project associated with?
```
no
```

## Use-case details

Describe the data being stored onto Filecoin
```
We store data for IDC server room operation records and IDC server room maintenance records, etc. Our company's products - business scope includes data technology, computer information technology, intelligent technology, technology development in the field of Internet, technical consultation, technical services, technology transfer, computer data processing, computer information system integration, security engineering, computer services, computer software development, cloud software services, cloud platform services, computers, software and auxiliary equipment, communications equipment, intelligent equipment Wholesale, retail, telecommunications business. 
```

Where was the data in this dataset sourced from?
```
My Own Storage Infra.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
![微信图片_20230309133430](https://user-images.githubusercontent.com/127381690/226300506-400196be-a19c-43c2-ac70-093617f70de2.jpg)
![微信图片_20230309133611](https://user-images.githubusercontent.com/127381690/226300512-3aecd325-a2da-44af-8886-e9dc84989238.jpg)
![微信图片_20230309133615](https://user-images.githubusercontent.com/127381690/226300516-41106bf9-ed84-4c6a-b437-a864e0997f28.jpg)
![微信图片_20230309133619](https://user-images.githubusercontent.com/127381690/226300523-973a5425-6b5c-4085-b573-13d4c3b503e1.jpg)
![微信图片_20230309133623](https://user-images.githubusercontent.com/127381690/226300530-c6d918df-5fa0-4c1a-b7aa-cb304afb61f4.jpg)
![微信图片_20230309133628](https://user-images.githubusercontent.com/127381690/226300533-d208cfd0-6da9-4cfa-9109-3b6e9b422c12.jpg)
![微信图片_20230309133423](https://user-images.githubusercontent.com/127381690/226300493-6b855c33-a658-4386-9151-1aecc75cbdf0.jpg)
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
 I confirm.
```

What is the expected retrieval frequency for this data?
```
Yearly.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
1 to 1.5 years.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Greater China，Asia，United State.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
HTTP or FTP server, Shipping hard drives.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
I'm still looking for it. I'll use slack and post it to the issue when I find it.
```

How will you be distributing deals across storage providers?
```
HTTP or FTP server, Shipping hard drives.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
yes.
```

**Comment by Kuoyeshuju** [comment]
> 名称： 大型数据集公证申请 关于： 客户应使用此申请表通过 LDN 请求数据集标题的 DataCap 分配：“[DataCap 应用程序] - 国业（上海）数据科技有限公司”标签：“应用程序，阶段：勤勉”受让人：“”
> 
> # 大数据集公证应用
> 要申请DataCap将您的数据集载入Filecoin，请填写以下内容。
> 
> ## 核心信息
> * 机构名称：国业（上海）数据科技有限公司
> * 网站/社交媒体：网站 http://kuoyeshuju.com/ 社交媒体 微信：上海国业数据
> * 地区： 大中华区
> * 请求的数据上限总量（介于 500 TiB 和 5 PiB 之间）：5PiB
> * 每周请求的数据上限分配（通常在 1-100TiB 之间）：100TiB
> * 用于首次分配的链上地址：f1klzdf2ksdfqe7gaz6hrvobsr7xjyplyzi5o4vmy
> 
> _请回答以下问题，将“请在此处回答”的文字改为。在答案中包含尽可能多的细节。_
> 
> ## 项目详情
> 分享您的项目和组织的简史。
> 
> ```
> Engaged in data science and technology, computer information technology, intelligent technology, Internet technology in the field of technology development, technical consultation, technical services, technology transfer, computer data processing, computer information system integration, security engineering, computer services, computer software development, cloud software services, cloud platform services, computer, software and auxiliary equipment, communication equipment, intelligent equipment wholesale, retail, telecommunications business.
> ```
> 
> 该项目的主要资金来源是什么？
> 
> ```
> Financing
> ```
> 
> 该项目与哪些其他项目/生态系统利益相关者相关联？
> 
> ```
> no
> ```
> 
> ## 用例详细信息
> 描述存储在Filecoin上的数据
> 
> ```
> We store data for IDC server room operation records and IDC server room maintenance records, etc. Our company's products - business scope includes data technology, computer information technology, intelligent technology, technology development in the field of Internet, technical consultation, technical services, technology transfer, computer data processing, computer information system integration, security engineering, computer services, computer software development, cloud software services, cloud platform services, computers, software and auxiliary equipment, communications equipment, intelligent equipment Wholesale, retail, telecommunications business. 
> ```
> 
> 此数据集中的数据来自何处？
> 
> ```
> My Own Storage Infra.
> ```
> 
> 你能分享一个数据样本吗？指向文件、图像、表格等的链接是执行此操作的好方法。
> 
> ```
> .
> ```
> 
> 确认这是网络上任何人都可以检索的公共数据集（即，查看数据不需要特定权限或访问权限）。
> 
> ```
>  I confirm.
> ```
> 
> What is the expected retrieval frequency for this data?
> 
> ```
> Yearly.
> ```
> 
> For how long do you plan to keep this dataset stored on Filecoin?
> 
> ```
> 1 to 1.5 years.
> ```
> 
> ## DataCap allocation plan
> In which geographies (countries, regions) do you plan on making storage deals?
> 
> ```
> Greater China.
> ```
> 
> How will you be distributing your data to storage providers? Is there an offline data transfer process?
> 
> ```
> HTTP or FTP server, Shipping hard drives.
> ```
> 
> How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
> 
> ```
> slack.
> ```
> 
> How will you be distributing deals across storage providers?
> 
> ```
> HTTP or FTP server, Shipping hard drives.
> ```
> 
> Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
> 
> ```
> yes.
> ```

**Comment by Kuoyeshuju** [comment]
![微信图片_20230309133423](https://user-images.githubusercontent.com/127381690/226298177-03817d87-ae4e-46c0-8b3f-0a6cf8d732fc.jpg)
![微信图片_20230309133430](https://user-images.githubusercontent.com/127381690/226298186-dc702cfc-08bc-4291-a58e-a495591bab47.jpg)
![微信图片_20230309133611](https://user-images.githubusercontent.com/127381690/226298194-07b506a5-fc1a-431a-86c9-15a408dec5bf.jpg)
![微信图片_20230309133615](https://user-images.githubusercontent.com/127381690/226298203-01938106-6d8a-41ea-9496-085c08eae289.jpg)
![微信图片_20230309133619](https://user-images.githubusercontent.com/127381690/226298208-dfd3a945-9b1e-426d-a4e6-8227db2675a8.jpg)
![微信图片_20230309133623](https://user-images.githubusercontent.com/127381690/226298218-57cd5b36-12af-4bc1-9bf1-c97d9861a05f.jpg)
![微信图片_20230309133628](https://user-images.githubusercontent.com/127381690/226298246-4c804bae-9a61-4b63-8876-0a45098b1792.jpg)

**Comment by Sunnyiscoming** [comment]
Can you provide more data samples to prove that you have 5 PB data already?

**Comment by Kuoyeshuju** [comment]
> Can you provide more data samples to prove that you have 5 PB data already?

![A](https://user-images.githubusercontent.com/127381690/227093266-68258eca-4676-45f9-97e5-92a8c9d38f18.png)

**Comment by Sunnyiscoming** [comment]
You have just provided 7 pictures. So maybe you can provide more data samples rather than screenshot to make others believe that you have 5 PB data.

**Comment by Kuoyeshuju** [comment]
> You have just provided 7 pictures. So maybe you can provide more data samples rather than screenshot to make others believe that you have 5 PB data.

Link: https://pan.baidu.com/s/1yNlx_FTgV2FXUE2HKOCoGg
Extraction code: ru6a
The company data is a lot, put some simple reference

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 5PiB

**Expected weekly DataCap usage rate**
> 100TiB

**Client address**
>f1klzdf2ksdfqe7gaz6hrvobsr7xjyplyzi5o4vmy

**Comment by zcfil** [comment]
Can you email filplus-app-review@fil.org using your official domain name to confirm your identity? Email name should contain Issue ID #1830.

**Comment by Kuoyeshuju** [comment]
> ID #1830.

Yes, of course. It has been sent

**Comment by zcfil** [comment]
<img width="1094" alt="b0acf27a7b48160eeec382481f2f4ec" src="https://user-images.githubusercontent.com/45065975/230318714-7a6450a7-b038-45dd-a478-a1e565bbcbac.png">
@raghavrmadya Signature error reported, requesting assistance
```
Verification failed: message execution failed: exit 18, reason: messagefailed with backtrace:00: f02049625 (method 2) -- f02016627 is not a signer (18)
(RetCode=18)
```

**Comment by Kuoyeshuju** [comment]
Can anyone update it for me

**Comment by zcfil** [comment]
Retrying or the same error, we need to wait for community workers to fix it
<img width="1561" alt="111" src="https://user-images.githubusercontent.com/45065975/230898333-a653b290-8ecb-4c3c-9962-97dc5fa77dba.png">

**Comment by GaryGJG** [comment]
Let me try for the sign..

**Comment by GaryGJG** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceailifuf3e7ajgiptm3ny4fc2bn4odcxsjw2bjr74z2emqqvngbb4 
#### Address 
> f1klzdf2ksdfqe7gaz6hrvobsr7xjyplyzi5o4vmy
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1zffqhxwq2rrg7rtot6lmkl6hb2xyrrseawprzsq
#### Id
> f8e9ee96-1691-4f99-a575-7825a0231ae5
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceailifuf3e7ajgiptm3ny4fc2bn4odcxsjw2bjr74z2emqqvngbb4
