### ISSUE TITLE
[DataCap Application] Instructional videos and materials 

### ISSUE THREAD

**Issue by mingzhonglv** [filecoin-project/filecoin-plus-large-datasets#1831]
### Data Owner Name

Fuzhou MZL Network Technology Co., LTD

### Data Owner Country/Region

China

### Data Owner Industry

Education & Training

### Website

https://www.wangkewang.com/

### Social Media

```text
https://www.wangkewang.com/
https://www.36171.com/
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

500TiB

### On-chain address for first allocation

f17kj3z6j6nff7susxtdc6o3cb2eastdnzlfszwua

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Our company was founded in 2019. We have been committed to providing users with rich teaching resources. Resources on the website include: entrepreneurship teaching, sideline creativity, primary and secondary school tutoring videos, skills teaching videos, tutorial PDFS. Through the combination of videos and teaching documents, we hope that most users can quickly master the skills or knowledge they want to learn.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
The data is mainly videos and pdf files on our website. Most of this data is currently stored on local hard drives, with some stored on platforms such as Baidu's web disk. We want to store this data on Filecoin.
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### How do you plan to prepare the dataset

lotus

### Please share a sample of the data

```text
链接：https://pan.baidu.com/s/1bJPqkwgNR6JN_5KWJzA_Wg?pwd=unz9
提取码：unz9

链接：https://pan.baidu.com/s/1fQYu2eE81SjjpJaW_Qcmlw?pwd=xqh0
提取码：xqh0

链接：https://pan.baidu.com/s/1h3HnD2vYfvq-T7LQkw2Nsg?pwd=i4bl
提取码：i4bl
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [ ] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

More than 3 years

### In which geographies do you plan on making storage deals

Greater China

### How will you be distributing your data to storage providers

Shipping hard drives

### How do you plan to choose storage providers

Slack, Big data exchange, Partners

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by mingzhonglv** [comment]
link to #1647

**Comment by Sunnyiscoming** [comment]
Can you email [filplus-app-review@fil.org](mailto:filplus-app-review@fil.org) using your official domain name(wangkewang.com) to confirm your identity?

**Comment by mingzhonglv** [comment]
Hi @Sunnyiscoming , Our team uses @36171.com mailbox. The website of wangkewang.com also displays the contact email address. Can I use this email address to send mail?
<img width="636" alt="WeChat9f37ca2ec16b5547d72d86a80b01b5cf" src="https://user-images.githubusercontent.com/126055036/226603928-e1470d62-b75e-4307-a3d2-dc47bace8a50.png">

**Comment by mingzhonglv** [comment]
COOL! Thank you!

**Comment by mingzhonglv** [comment]
@cryptowhizzard Hi dear Notary. I have already submitted the kyc form.

**Comment by cryptowhizzard** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebreue3kqamnjd5bkvt6o6iwgqe4krjt2dwc4pwri2oulhyqpzxuw 
#### Address 
> f17kj3z6j6nff7susxtdc6o3cb2eastdnzlfszwua
#### Datacap Allocated
> 250.00TiB
#### Signer Address
> f1krmypm4uoxxf3g7okrwtrahlmpcph3y7rbqqgfa
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebreue3kqamnjd5bkvt6o6iwgqe4krjt2dwc4pwri2oulhyqpzxuw

**Comment by mingzhonglv** [comment]
@cryptowhizzard  Thanks!

**Comment by liyunzhi-666** [comment]
Hi @mingzhonglv I am glad to see your application, please answer the following questions
Can you explain your data composition and provide sufficient data samples separately? How many copies will you store?
What's the relationship between you and the organization?
Can you provide more detailed information about other storage providers participated in this program, such as you can list SPs you have contacted with at present?
Whether the sps you choose can support data retrieval?

**Comment by mingzhonglv** [comment]
Hi @liyunzhi-666 , Thank you for your attention!
The data is mainly video, and there are also a small number of words and pdf. All kinds of teaching materials. We plan to store 5-8 copies.
I am a member of the company and can provide proof of this by sending an email if necessary.
The SPs I have contacted so far are as follows (they will support data retrieval, we reached an agreement):

- f02028138/Thailand/Krabi
- f02028326/America/Atlanta
- f01811024/China/HongKong
- f02085743/China/HongKong

data samples:
`链接：https://pan.baidu.com/s/1bJPqkwgNR6JN_5KWJzA_Wg?pwd=unz9
提取码：unz9

链接：https://pan.baidu.com/s/1fQYu2eE81SjjpJaW_Qcmlw?pwd=xqh0
提取码：xqh0

链接：https://pan.baidu.com/s/1h3HnD2vYfvq-T7LQkw2Nsg?pwd=i4bl
提取码：i4bl`

**Comment by liyunzhi-666** [comment]
I checked the legitimacy of the company through [QCC](https://www.qcc.com/firm/1e98ab817ba50642f6eadf15a0ea5bd4.html) and also checked the data samples. I am willing to support the first round and keep an eye on the subsequent allocation.

**Comment by mingzhonglv** [comment]
Thanks!

**Comment by liyunzhi-666** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebsb7kklf46h52elaud7neg6jx3q36ucgywh5hjr3fozfnlrnfege 
#### Address 
> f17kj3z6j6nff7susxtdc6o3cb2eastdnzlfszwua
#### Datacap Allocated
> 250.00TiB
#### Signer Address
> f1pszcrsciyixyuxxukkvtazcokexbn54amf7gvoq
#### Id
> db7e12a4-185b-4f67-8405-e8c6401c15a1
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebsb7kklf46h52elaud7neg6jx3q36ucgywh5hjr3fozfnlrnfege

**Comment by 1ane-1** [comment]
checker:manualTrigger

**Comment by 1ane-1** [comment]
Please check your CID sharing problem.

**Comment by liyunzhi-666** [comment]
hey @mingzhonglv , please explain the CID sharing situation in your application within two business days. Otherwise I will recommend T&T WG to close your application.

**Comment by liyunzhi-666** [comment]
Time has passed and still no feedback from the client @mingzhonglv . Recommend T&T WG Gov to intervene.
I propose to close the application and remove the remaining Datacap.
cc @raghavrmadya @simonkim0515

**Comment by raghavrmadya** [comment]
On the recommendation of T&T WG, we are closing this application based on the discussion above and request DC removal
