### ISSUE TITLE
[DataCap Application] Finnish Meteorological Institute Weather Radar Data

### ISSUE THREAD

**Issue by AgeeWeb3** [filecoin-project/filecoin-plus-large-datasets#1832]
### Data Owner Name

Finnish Meteorological Institute

### Data Owner Country/Region

Finland

### Data Owner Industry

Environment

### Website

https://en.ilmatieteenlaitos.fi/open-data-on-aws-s3

### Social Media

```text
https://twitter.com/meteorologit
https://www.linkedin.com/company/finnish-meteorological-institute
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

400TiB

### On-chain address for first allocation

f1vpsnv6aqsytsvztc6p22mr5yoxkwdylh27yboca

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
The Finnish Meteorological Institute makes observations and research on the atmosphere, the near space and the seas. It also provides services on weather, sea, air quality, climate and near space for the needs of public safety, business life and citizens. The Finnish Meteorological Institute is an administrative branch of the Ministry of Transport and Communications.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
The up-to-date weather radar from the FMI radar network is available as Open Data. The data contain both single radar data along with composites over Finland in GeoTIFF and HDF5-formats.
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### How do you plan to prepare the dataset

lotus, singularity

### Please share a sample of the data

```text
https://registry.opendata.aws/hirlam/
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Sporadic

### For how long do you plan to keep this dataset stored on Filecoin

1 to 1.5 years

### In which geographies do you plan on making storage deals

Asia other than Greater China, North America, South America, Europe

### How will you be distributing your data to storage providers

HTTP or FTP server, Shipping hard drives, Lotus built-in data transfer

### How do you plan to choose storage providers

Slack, Filmine, Big data exchange

### How do you plan to make deals to your storage providers

Lotus client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 5PiB

**Expected weekly DataCap usage rate**
> 400TiB

**Client address**
>f1vpsnv6aqsytsvztc6p22mr5yoxkwdylh27yboca

**Comment by Aaron01230** [comment]
Your LDN data seems  make sense, we can support you.
As a notary, we need to do some research, please answer me a few questions.
1. Please provide proof of your existing data capacity.
2. Please use the ilmatieteenlaitos.fi domain mailbox to send an email containing the number #1832 to filplus-app-review@fil.org 
3. Please fill out this form(https://form.jotform.com/230730730268452) to list the SPs id you will cooperate with and provide us with the necessary information. 
Thanks

**Comment by TakiChain** [comment]
There's no reference from the checker report for the first round. Based on the distribution plan and communication, we will sign for the first round and follow up on the after process.

**Comment by TakiChain** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceanatvijqvuyelgrzaowr2ntyqwvhjaqwhnjbl3olnh2hawu5u4fo 
#### Address 
> f1vpsnv6aqsytsvztc6p22mr5yoxkwdylh27yboca
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f15impf3j2zcaex4lhyxndxswuuhv24vzstuqtxsi
#### Id
> 9e96aa69-e419-474e-b74b-4c9484a71d14
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceanatvijqvuyelgrzaowr2ntyqwvhjaqwhnjbl3olnh2hawu5u4fo

**Comment by Aifabot-Cloud** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedpf74ggsgogl5tpfuhjxivulvkfpq5uxmf7l2lskv26thhju3rum 
#### Address 
> f1vpsnv6aqsytsvztc6p22mr5yoxkwdylh27yboca
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f174fg3bqbln3zjnkxtyf6s54txqkr7yqkj6cig7y
#### Id
> 9e96aa69-e419-474e-b74b-4c9484a71d14
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedpf74ggsgogl5tpfuhjxivulvkfpq5uxmf7l2lskv26thhju3rum

**Comment by BobbyChoii** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebqpfxcztiz4btpn2hi4wfw46cqlskdlsjqc2ffvrp7jgxnsltuxw 
#### Address 
> f1vpsnv6aqsytsvztc6p22mr5yoxkwdylh27yboca
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1irqs2gmctiv3jcdfwuch7oxvf4ixh3k4b2wc24i
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebqpfxcztiz4btpn2hi4wfw46cqlskdlsjqc2ffvrp7jgxnsltuxw

**Comment by TakiChain** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebg7jkbyusny2himxsanrloebuatns2j7vjc4q7banhz6ykrbpf34 
#### Address 
> f1vpsnv6aqsytsvztc6p22mr5yoxkwdylh27yboca
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f15impf3j2zcaex4lhyxndxswuuhv24vzstuqtxsi
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebg7jkbyusny2himxsanrloebuatns2j7vjc4q7banhz6ykrbpf34

**Comment by Meibuy** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedw6msliqu6lmqbqjffcqcmjrhok5mdwhwde4me45g2wgi7pndrcs 
#### Address 
> f1vpsnv6aqsytsvztc6p22mr5yoxkwdylh27yboca
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1bwugfihrmn3iyunzyxst5nttql3dge4khwmurtq
#### Id
> 82321325-8aa9-4989-a2c3-adc79e394b80
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedw6msliqu6lmqbqjffcqcmjrhok5mdwhwde4me45g2wgi7pndrcs

**Comment by TakiChain** [comment]
Good summary report and ongoing communication from the applicant. There're lots of inputs from many notaries and reasonable responses from the applicant. I'm willing to give my sign and help to onboard this application.

**Comment by TakiChain** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecf37yxj2zwr3wj4ehnai6tr4qxdrvkirsx3cvpnwryy5v7dzcd4o 
#### Address 
> f1vpsnv6aqsytsvztc6p22mr5yoxkwdylh27yboca
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f15impf3j2zcaex4lhyxndxswuuhv24vzstuqtxsi
#### Id
> 618537c3-58a5-4105-9983-b5ede45c1a32
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecf37yxj2zwr3wj4ehnai6tr4qxdrvkirsx3cvpnwryy5v7dzcd4o

**Comment by Aifabot-Cloud** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecfxo6b2ntdvwz6a6gia7cgsx6fnrdhyzkzr2dhdtdtz27ehedavm 
#### Address 
> f1vpsnv6aqsytsvztc6p22mr5yoxkwdylh27yboca
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f174fg3bqbln3zjnkxtyf6s54txqkr7yqkj6cig7y
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecfxo6b2ntdvwz6a6gia7cgsx6fnrdhyzkzr2dhdtdtz27ehedavm

**Comment by Casey-PG** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceamhimjectrvxziy2lsdcuuuigcqpnelxify7xps7tq6vtbkrymns 
#### Address 
> f1vpsnv6aqsytsvztc6p22mr5yoxkwdylh27yboca
#### Datacap Allocated
> 1.56PiB
#### Signer Address
> f1d4yb3wags3mtddzesxoo63jv7dmlec3bq4yteni
#### Id
> 46247987-0da3-4a5d-a730-1573a82a91a9
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceamhimjectrvxziy2lsdcuuuigcqpnelxify7xps7tq6vtbkrymns

**Comment by Suyanj** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedxy4jbtrwyid3c4y4guozxga6tdbcrny4f4ufrckgd3mch3lx2h4 
#### Address 
> f1vpsnv6aqsytsvztc6p22mr5yoxkwdylh27yboca
#### Datacap Allocated
> 1.56PiB
#### Signer Address
> f1ihv7gz3vn3xqvikpt4rwryecgisl7745lodx3yi
#### Id
> 46247987-0da3-4a5d-a730-1573a82a91a9
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedxy4jbtrwyid3c4y4guozxga6tdbcrny4f4ufrckgd3mch3lx2h4

**Comment by Suyanj** [comment]
Open datasets bring great value to the network. Happy to see more of them join Filecoin. Please keep the allocation in line with Filplus guidlines.

**Comment by kevzak** [comment]
checker:manualTrigger

**Comment by Filplus-govteam** [comment]
Hello @AgeeWeb3  per the https://github.com/filecoin-project/notary-governance/issues/922 for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

This information will be reviewed by Fil+ Governance team to confirm validity and then the application will be triggered for notary review. Let us know if you have any questions.

**Comment by AgeeWeb3** [comment]
checker:manualTrigger

**Comment by AgeeWeb3** [comment]
@Filplus-govteam Already finished the form.

**Comment by Filplus-govteam** [comment]
Thank you @AgeeWeb3 for submitting the SP Entity info:

f02232088 no entity Sichuan
f02252118 Worldcamp HK
f02245898 no entity HK
f02244985 no entity HK
f02232007 no entity Sichuan

**Comment by Filplus-govteam** [comment]
why are you choosing to use SP who will not serve retrievals? This is not meeting the Fil+ guidelines

Also 38.95% of deals are for data replicated across less than 4 storage providers. 

FYI Notaries

**Comment by Stanton15** [comment]
checker:manualTrigger

**Comment by AgeeWeb3** [comment]
@Filplus-govteam The sps are all supporting retrieval.


![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/122510851/7bf5b1e0-f8bb-4b6a-885e-2902a156317f)
![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/122510851/e18c413c-b5c8-426b-a00a-7c3c1be60c7e)
![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/122510851/845c7eea-c61e-4ba5-bd8e-196dd5afb7f5)
![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/122510851/7acf8a29-3e59-44bd-bd0d-fea284900fae)
![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/122510851/164bb969-3da2-41e1-9e93-36817e71cb8b)

About Deal Data Replication, it just because we've got a little amount of datacap and it is hard to transfer to more sps. Then we'll improve about this to make it much more distributed.

**Comment by AthSmith** [comment]
Frankly, need to pay attention to Deal Data Replication and looking forward to seeing your improvement.

**Comment by AthSmith** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceax3lqhdq4f2vgchtlf6fbrnkeznvwpcifo4fhe6qu7m6s4zk6ocm 
#### Address 
> f1vpsnv6aqsytsvztc6p22mr5yoxkwdylh27yboca
#### Datacap Allocated
> 122.55TiB
#### Signer Address
> f1vxbqrf7rfum3n6m5u6eb4re6xj7amvsaqnzu64y
#### Id
> 9361a354-713b-4654-bdeb-8c7f9a597278
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceax3lqhdq4f2vgchtlf6fbrnkeznvwpcifo4fhe6qu7m6s4zk6ocm

**Comment by AgeeWeb3** [comment]
@athsmith Thank you for your support. We will improve it.
