### ISSUE TITLE
[DataCap Application] <lnjoying> - <lnjoying Aws Dataset>

### ISSUE THREAD

**Issue by ElioLam** [filecoin-project/filecoin-plus-large-datasets#1834]
### Data Owner Name

lnjoying

### Data Owner Country/Region

China

### Data Owner Industry

IT & Technology Services

### Website

http://www.lnjoying.com/

### Social Media

```text
1.http://www.lnjoying.com/lists/65.html
2.微信公众号：秒如科技
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

500TiB

### On-chain address for first allocation

f1fqcvp53xdph7ruo2bckz4ytv25ygjwhwccm4bvi

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Lnjoying Technology is a company that created in 2019.We're backed by TusStar,Fangxin Capital,GL Ventures and so on.Lnjoying Technology is committed to becoming a world-class edge cloud service provider.
We are interested in filecoin, and we've been paying attention for years.In the last few years, we invested in many FILs.Now we want to join the filecoin ecosystem to store some open data.Then we will store our own open data to the filecoin net.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
1.This dataset captures Sunflower's genetic diversity originating from thousands of wild, cultivated, and landrace sunflower individuals distributed across North America.
2.The 3000 Rice Genome Project is an international effort to sequence the genomes of 3,024 rice varieties from 89 countries.
3.The National Ocean Service (NOS)  has been developing and implementing hydrodynamic model-based Operational Forecast Systems.
4.The NOAA National Water Model Retrospective dataset contains input and output from multi-decade CONUS retrospective simulations. These simulations used meteorological input fields from meteorological retrospective datasets. The output frequency and fields available in this historical NWM dataset differ from those contained in the real-time operational NWM forecast model.
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### How do you plan to prepare the dataset

lotus, graphsplit, others/custom tool

### If you answered "other/custom tool" in the previous question, enter the details here

```text
Swan Client tool (https://github.com/filswan/go-swan-client#Graphsplit) to prepare the dataset.
```

### Please share a sample of the data

```text
1.s3://ubc-sunflower-genome/   (67.2TiB)
2.s3://3kricegenome/   (96.6TiB)
3.s3://noaa-ofs-pds/   (101.0TiB)
4.s3://noaa-nwm-retrospective-2-1-zarr-pds/  (132TiB)
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Monthly

### For how long do you plan to keep this dataset stored on Filecoin

2 to 3 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, South America, Europe

### How will you be distributing your data to storage providers

HTTP or FTP server, IPFS, Shipping hard drives, Others

### How do you plan to choose storage providers

Slack, Partners

### If you already have a list of storage providers to work with, fill out their names and provider IDs below

```text
f01789666
f0134516
f0118330
f0839509
f0867300
f01395673
f01072221
f0143858
f01786736
f01348489
f0522948
f01228008
f01053413
f01975316
f01975326
f01390330
```

### How do you plan to make deals to your storage providers

Boost client, Lotus client, Others/custom tool

### If you answered "Others/custom tool" in the previous question, enter the details here

```text
Swan Client tool：
https://github.com/filswan/go-swan-client
```

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by ElioLam** [comment]
@Normalnoise 
1.We have researched and are familiar with the swan tool command.Such as use "swan-client generate-car graphsplit car" to generate car and use "swan-client task" to make deals.
2.One of our client wants to use some of that data.Also we want to join the ipfs ecology and test the filecoin network performance.In the fulture we will store some our data in the network.

**Comment by Sunnyiscoming** [comment]
Could you send an email to filplus-app-review@fil.org with your official domain in order to confirm your identity? Email name should includes the issue id #1834.

**Comment by ElioLam** [comment]
@Sunnyiscoming

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 5PiB

**Expected weekly DataCap usage rate**
> 500TiB

**Client address**
>f1fqcvp53xdph7ruo2bckz4ytv25ygjwhwccm4bvi

**Comment by Normalnoise** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebcuni7ux6vlrhuj3habmovys2e3tjntwncd4kzceperxdowrhgp4 
#### Address 
> f1fqcvp53xdph7ruo2bckz4ytv25ygjwhwccm4bvi
#### Datacap Allocated
> 250.00TiB
#### Signer Address
> f1c5non5yf35avgcpsqvxu4yj54yyvxorwyjochqq
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebcuni7ux6vlrhuj3habmovys2e3tjntwncd4kzceperxdowrhgp4

**Comment by nj-steve** [comment]
@ElioLam What's your plan that you will send deals to these storage providers?

**Comment by ElioLam** [comment]
@nj-steve hi nj-steve, We will send 8 copies to different sp. We send storage transactions to storage providers in 3 different regions

**Comment by nj-steve** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceagablkvk6apzt4u2246stkplkl5bwffmdrhwfqcfi6k2qgxfda2w 
#### Address 
> f1fqcvp53xdph7ruo2bckz4ytv25ygjwhwccm4bvi
#### Datacap Allocated
> 250.00TiB
#### Signer Address
> f1xx6555qijma7igpnjspyvdunc4vfxkawnpqy5ii
#### Id
> 04ea581e-bb43-492d-8f35-1644ef763392
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceagablkvk6apzt4u2246stkplkl5bwffmdrhwfqcfi6k2qgxfda2w

**Comment by ElioLam** [comment]
checker:manualTrigger

**Comment by nj-steve** [comment]
Hi, when will you use this client for storing the data?

**Comment by ElioLam** [comment]
@nj-steve We are preparing the data and expect to start using it in two weeks，thankyou

**Comment by ElioLam** [comment]
checker:manualTrigger

**Comment by ElioLam** [comment]
checker:manualTrigger

**Comment by ElioLam** [comment]
checker:manualTrigger

**Comment by ElioLam** [comment]
checker:manualTrigger

**Comment by ElioLam** [comment]
checker:manualTrigger

**Comment by ElioLam** [comment]
checker:manualTrigger

**Comment by ElioLam** [comment]
checker:manualTrigger

**Comment by ElioLam** [comment]
checker:manualTrigger

**Comment by Joss-Hua** [comment]
Base the report, considering that the number of SPs and replicas can continue to increase, while other aspects are healthy, this round of allocation is supported.

**Comment by a1991car** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacectw3olkkiuq3nnayytkkreakh23k3w224o6pq6s7r45w4odipbri 
#### Address 
> f1fqcvp53xdph7ruo2bckz4ytv25ygjwhwccm4bvi
#### Datacap Allocated
> 500.00TiB
#### Signer Address
> f1qnumecdypgrbaebtkdfjnwt5ndacadcuas3deiq
#### Id
> 747088bf-2b35-4007-9875-1775fe878d9a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacectw3olkkiuq3nnayytkkreakh23k3w224o6pq6s7r45w4odipbri

**Comment by a1991car** [comment]
Temporarily supported, please improve the retrieval success rate

**Comment by ElioLam** [comment]
checker:manualTrigger

**Comment by ElioLam** [comment]
@a1991car Thank you for your support. From the data, our retrieval rate is steadily improving

**Comment by ElioLam** [comment]
checker:manualTrigger

**Comment by ElioLam** [comment]
checker:manualTrigger

**Comment by ElioLam** [comment]
checker:manualTrigger

**Comment by ElioLam** [comment]
checker:manualTrigger

**Comment by ElioLam** [comment]
checker:manualTrigger

**Comment by ElioLam** [comment]
checker:manualTrigger

**Comment by ElioLam** [comment]
checker:manualTrigger

**Comment by Tom-OriginStorage** [comment]
checker:manualTrigger

**Comment by Tom-OriginStorage** [comment]
The inspection report shows that they are relatively healthy and willing to support this round

**Comment by Tom-OriginStorage** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacea43frv4zeovn6jvpqvwwppnp7hiztfjq2muhx64rb6vt45hyuhxa 
#### Address 
> f1fqcvp53xdph7ruo2bckz4ytv25ygjwhwccm4bvi
#### Datacap Allocated
> 1000.00TiB
#### Signer Address
> f1q6bpjlqia6iemqbrdaxr2uehrhpvoju3qh4lpga
#### Id
> cfae7cdf-9a8b-41a6-8f30-b6303a03b09d
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacea43frv4zeovn6jvpqvwwppnp7hiztfjq2muhx64rb6vt45hyuhxa

**Comment by 1ane-1** [comment]
The report shows everything goes well.

**Comment by 1ane-1** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceajvemnucw2hsocciwn4g322tsoizvfee3wpajplefgr3iega6xc2 
#### Address 
> f1fqcvp53xdph7ruo2bckz4ytv25ygjwhwccm4bvi
#### Datacap Allocated
> 1000.00TiB
#### Signer Address
> f1mdk7s2vntzm6hu35yuo6vjubtrpfnb2awhgvrri
#### Id
> cfae7cdf-9a8b-41a6-8f30-b6303a03b09d
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceajvemnucw2hsocciwn4g322tsoizvfee3wpajplefgr3iega6xc2

**Comment by ElioLam** [comment]
checker:manualTrigger

**Comment by ElioLam** [comment]
keep going

**Comment by Bitrise0111** [comment]
Check report shows healthy and we'd like to support.

**Comment by Bitrise0111** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebttlz5thiycjqgk4y7gyrvipyef5ct5fpop5mai46b42vytsmsmi 
#### Address 
> f1fqcvp53xdph7ruo2bckz4ytv25ygjwhwccm4bvi
#### Datacap Allocated
> 1.95PiB
#### Signer Address
> f1nknj7ayq4o43czrtdoauggtwl43fbqatmqis3yy
#### Id
> d3d4d1b1-189e-406c-86fa-c20504cbe1b1
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebttlz5thiycjqgk4y7gyrvipyef5ct5fpop5mai46b42vytsmsmi

**Comment by NiwanDao** [comment]
checker:manualTrigger

**Comment by NiwanDao** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced53g5kq7xhoz4xfcj3r4fa4heilel2hujac4yv3bxdk4la6cfcb4 
#### Address 
> f1fqcvp53xdph7ruo2bckz4ytv25ygjwhwccm4bvi
#### Datacap Allocated
> 1.95PiB
#### Signer Address
> f1a2lia2cwwekeubwo4nppt4v4vebxs2frozarz3q
#### Id
> d3d4d1b1-189e-406c-86fa-c20504cbe1b1
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced53g5kq7xhoz4xfcj3r4fa4heilel2hujac4yv3bxdk4la6cfcb4

**Comment by ElioLam** [comment]
checker:manualTrigger

**Comment by ElioLam** [comment]
checker:manualTrigger

**Comment by nj-steve** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedloy6wnab4idoselmnjakbdrvrxaf5g54vlke7p2uc4bdhhqniu6 
#### Address 
> f1fqcvp53xdph7ruo2bckz4ytv25ygjwhwccm4bvi
#### Datacap Allocated
> 1.95PiB
#### Signer Address
> f1xx6555qijma7igpnjspyvdunc4vfxkawnpqy5ii
#### Id
> d3d4d1b1-189e-406c-86fa-c20504cbe1b1
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedloy6wnab4idoselmnjakbdrvrxaf5g54vlke7p2uc4bdhhqniu6

**Comment by zcfil** [comment]
checker:manualTrigger

**Comment by zcfil** [comment]
There are several SPs with 0 retrieval rate, please contact to fix this issue
![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/45065975/01a37cc7-eb1a-49fa-8a0e-37e0cf84b89c)

**Comment by zcfil** [comment]
![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/45065975/e8004ebd-37b5-40fc-829c-f21ced3c93a3)

Robot reports normal and checked multiple sp's, all support retrieval, willing to support this round

**Comment by zcfil** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceahje652pawv2vybt52ldxsqezehf3uw4n6bfquldg7crh3s3ja4u 
#### Address 
> f1fqcvp53xdph7ruo2bckz4ytv25ygjwhwccm4bvi
#### Datacap Allocated
> 1.95PiB
#### Signer Address
> f1cjzbiy5xd4ehera4wmbz63pd5ku4oo7g52cldga
#### Id
> d3d4d1b1-189e-406c-86fa-c20504cbe1b1
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceahje652pawv2vybt52ldxsqezehf3uw4n6bfquldg7crh3s3ja4u

**Comment by ElioLam** [comment]
continue

**Comment by Sunnyiscoming** [comment]
Close for total datacap reached.
