### ISSUE TITLE
[DataCap Application] <BossDB Open Neuroimagery Datasets><1/2>

### ISSUE THREAD

**Issue by caoxinhe0108** [filecoin-project/filecoin-plus-large-datasets#1835]
### Data Owner Name

Johns Hopkins University Applied Physics Laboratory

### Data Owner Country/Region

United States

### Data Owner Industry

Life Science / Healthcare

### Website

https://registry.opendata.aws/bossdb

### Social Media

```text
https://registry.opendata.aws/bossdb
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

600TiB

### On-chain address for first allocation

f1fji3yg3t5xyhuzhq34yl7kihbe4jnuyzf55jt7y

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
This data ecosystem, Brain Observatory Storage Service & Database (BossDB), contains several neuro-imaging datasets across multiple modalities and scales, ranging from nanoscale (electron microscopy), to microscale (cleared lightsheet microscopy and array tomography), and mesoscale (structural and functional magnetic resonance imaging). Additionally, many of the datasets include dense segmentation and meshes.
```

### Is this project associated with other projects/ecosystem stakeholders?

Yes

### Describe the data being stored onto Filecoin

```text
This data ecosystem, Brain Observatory Storage Service & Database (BossDB), contains several neuro-imaging datasets across multiple modalities and scales, ranging from nanoscale (electron microscopy), to microscale (cleared lightsheet microscopy and array tomography), and mesoscale (structural and functional magnetic resonance imaging). Additionally, many of the datasets include dense segmentation and meshes.
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### How do you plan to prepare the dataset

lotus

### Please share a sample of the data

```text
aws s3 ls --no-sign-request s3://bossdb-open-data/

2022-02-26 11:02:10 1.5 KiB witvliet2020/Dataset_8_Segmentation/synapses/info
2022-02-26 11:02:11 1.5 KiB witvliet2020/Dataset_8_Segmentation/synapses/provenance
2022-02-18 05:20:18 446 Bytes witvliet2020/Dataset_8_Segmentation/template/info
2022-06-21 10:00:04 3.8 KiB witvliet2020/Dataset_8_Segmentation_Properties/info

Total Objects: 664318037
Total Size: 849.7 TiB
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

1.5 to 2 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, South America

### How will you be distributing your data to storage providers

Cloud storage (i.e. S3)

### How do you plan to choose storage providers

Slack, Big data exchange

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
Can you list sps you will cooperate with?

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 5PiB

**Expected weekly DataCap usage rate**
> 600TiB

**Client address**
>f1fji3yg3t5xyhuzhq34yl7kihbe4jnuyzf55jt7y

**Comment by caoxinhe0108** [comment]
@TimGuo7  THANK YOU

**Comment by caoxinhe0108** [comment]
Thank you for your support @TimGuo7

**Comment by psh0691** [comment]
I'll sign the first round and make sure it meets the Fileplus regulations.

**Comment by psh0691** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedcphgffxtg2lqvbiddpla4yfanhhwkyvrb577e7sxqffjcblt5s6 
#### Address 
> f1fji3yg3t5xyhuzhq34yl7kihbe4jnuyzf55jt7y
#### Datacap Allocated
> 256.00TiB
#### Signer Address
> f1qdko4jg25vo35qmyvcrw4ak4fmuu3f5rif2kc7i
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedcphgffxtg2lqvbiddpla4yfanhhwkyvrb577e7sxqffjcblt5s6

**Comment by cryptowhizzard** [comment]
Hi @caoxinhe0108 

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Looking at your application i have some questions:
Why did you choose to only store your application in Asia?

What hardware do you have over there to prepare this dataset? What is your internet connection speed? Do you already have the data downloaded on the premises? Can you show us some visible proof of the size of your data and the storage / packing hardware you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230337462961356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!

**Comment by caoxinhe0108** [comment]
Thank you for your attention. We are also looking for SPs from outside Asia and will add them later. Thank you

**Comment by caoxinhe0108** [comment]
checker:manualTrigger

**Comment by mikezli** [comment]
![e86bcd726a9e10afe6e4659c6f9fd75](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/118169683/4d8c51dc-7fe9-414d-b760-10bd6efe899e)

lotus client retrieve --provider f02052217 QmaV1G63CVnmuT6WhxVDbnsJ1z3EUbwmMhjf3nDyyYWgmt QmaV1G63CVnmuT6WhxVDbnsJ1z3EUbwmMhjf3nDyyYWgmt.temp

**Comment by mikezli** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec4udp4d7ufpd47vyacctl7k4pkaurmaqez5afz665ujoc4l5z5bi 
#### Address 
> f1fji3yg3t5xyhuzhq34yl7kihbe4jnuyzf55jt7y
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f1dnb3uz7sylxk6emti3ififcvu3nlufnnsjui6ea
#### Id
> 97436521-8b47-40f6-a079-6aae69668685
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec4udp4d7ufpd47vyacctl7k4pkaurmaqez5afz665ujoc4l5z5bi

**Comment by igoovo** [comment]
checker:manualTrigger

**Comment by caoxinhe0108** [comment]
checker:manualTrigger

**Comment by spaceT9** [comment]
checker:manualTrigger

**Comment by spaceT9** [comment]
The CID report looks great, hope you can communicate with your SPs to increase the http retreival sucess rate in the future. Support this round

**Comment by spaceT9** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebev3262xguqzvw77bswnx3r3lkny7bcbitvi5ceswjt73tjh5kdw 
#### Address 
> f1fji3yg3t5xyhuzhq34yl7kihbe4jnuyzf55jt7y
#### Datacap Allocated
> 1.00PiB
#### Signer Address
> f1dktm3abgn7wkpepxab4q3eaw24qktizk4esfzyy
#### Id
> f05c5b3f-c213-4f86-bbfb-90585a0569d5
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebev3262xguqzvw77bswnx3r3lkny7bcbitvi5ceswjt73tjh5kdw

**Comment by luobin544** [comment]
checker:manualTrigger

**Comment by luobin544** [comment]
The data backup continues to grow, and each node can be retrieved, and the initial report is healthy without any issues.Willing to support this round

**Comment by luobin544** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceasc4nkahwyco24v27l6mkxcebzv6xgqajcd7ceq7axckx4adzz6y 
#### Address 
> f1fji3yg3t5xyhuzhq34yl7kihbe4jnuyzf55jt7y
#### Datacap Allocated
> 1.00PiB
#### Signer Address
> f1tbd632f6w62glfaf7wjpimacbnjiz26poyoes2q
#### Id
> f05c5b3f-c213-4f86-bbfb-90585a0569d5
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceasc4nkahwyco24v27l6mkxcebzv6xgqajcd7ceq7axckx4adzz6y

**Comment by caoxinhe0108** [comment]
checker:manualTrigger

**Comment by caoxinhe0108** [comment]
checker:manualTrigger

**Comment by SuperChaiChai** [comment]
checker:manualTrigger

**Comment by SuperChaiChai** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedyvz2fgybre6kab7eprmim3u6nxtcyi6jcrdk2ttofmezsrdtobi 
#### Address 
> f1fji3yg3t5xyhuzhq34yl7kihbe4jnuyzf55jt7y
#### Datacap Allocated
> 2.00PiB
#### Signer Address
> f12mckci3omexgzoeosjvstcfxfe4vqw7owdia3da
#### Id
> 80e2647b-59a5-449c-a2a5-afc4b8eb2fd0
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedyvz2fgybre6kab7eprmim3u6nxtcyi6jcrdk2ttofmezsrdtobi

**Comment by Tom-OriginStorage** [comment]
The packaging report shows that it is okay, the node distribution SP said that this round will be adjusted, and is willing to support this round, and continue to pay attention to it later

**Comment by Tom-OriginStorage** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecwqfwkk4t2s5fy74kbhkgaz3eybo57i4q44lcrinmfd25qoks5ki 
#### Address 
> f1fji3yg3t5xyhuzhq34yl7kihbe4jnuyzf55jt7y
#### Datacap Allocated
> 2.00PiB
#### Signer Address
> f1q6bpjlqia6iemqbrdaxr2uehrhpvoju3qh4lpga
#### Id
> 80e2647b-59a5-449c-a2a5-afc4b8eb2fd0
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecwqfwkk4t2s5fy74kbhkgaz3eybo57i4q44lcrinmfd25qoks5ki

**Comment by caoxinhe0108** [comment]
checker:manualTrigger

**Comment by ipollo00** [comment]
checker:manualTrigger

**Comment by ipollo00** [comment]
Will the replication rate back to normal? What is your plan?

**Comment by ipollo00** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacearabxvi4bgoctvws27fjjddr66xx6odalx7i35t5pf2j543jsn24 
#### Address 
> f1fji3yg3t5xyhuzhq34yl7kihbe4jnuyzf55jt7y
#### Datacap Allocated
> 2.00PiB
#### Signer Address
> f1n5wlrrhoxpkgwij25xrtt7w7g2k3fhbthmdn6ri
#### Id
> 80e2647b-59a5-449c-a2a5-afc4b8eb2fd0
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacearabxvi4bgoctvws27fjjddr66xx6odalx7i35t5pf2j543jsn24

**Comment by ipollo00** [comment]
the num of backups is enough. kindly suggest increasing the volume of replication. 
Will support this round, and keep following up on the update.

**Comment by a1991car** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceak54dgbsz7magzb2fh6bibvoyq3iihy3uk5ktzcc4mmvxk3rjvdw 
#### Address 
> f1fji3yg3t5xyhuzhq34yl7kihbe4jnuyzf55jt7y
#### Datacap Allocated
> 2.00PiB
#### Signer Address
> f1qnumecdypgrbaebtkdfjnwt5ndacadcuas3deiq
#### Id
> 80e2647b-59a5-449c-a2a5-afc4b8eb2fd0
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceak54dgbsz7magzb2fh6bibvoyq3iihy3uk5ktzcc4mmvxk3rjvdw

**Comment by caoxinhe0108** [comment]
OK

**Comment by caoxinhe0108** [comment]
checker:manualTrigger

**Comment by caoxinhe0108** [comment]
checker:manualTrigger
