### ISSUE TITLE
[DataCap Application] <BossDB Open Neuroimagery Datasets><2/2>

### ISSUE THREAD

**Issue by caoxinhe0108** [filecoin-project/filecoin-plus-large-datasets#1836]
### Data Owner Name

Johns Hopkins University Applied Physics Laboratory

### Data Owner Country/Region

United States

### Data Owner Industry

Life Science / Healthcare

### Website

https://registry.opendata.aws/bossdb 

### Social Media

```text
https://registry.opendata.aws/bossdb
```

### Total amount of DataCap being requested

10PiB

### Weekly allocation of DataCap requested

1PiB

### On-chain address for first allocation

f1ynv3f5ne5k7xxr7z5q7coro7rqpls3ilhuz3ndy

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
This data ecosystem, Brain Observatory Storage Service & Database (BossDB), contains several neuro-imaging datasets across multiple modalities and scales, ranging from nanoscale (electron microscopy), to microscale (cleared lightsheet microscopy and array tomography), and mesoscale (structural and functional magnetic resonance imaging). Additionally, many of the datasets include dense segmentation and meshes.
```

### Is this project associated with other projects/ecosystem stakeholders?

Yes

### Describe the data being stored onto Filecoin

```text
This data ecosystem, Brain Observatory Storage Service & Database (BossDB), contains several neuro-imaging datasets across multiple modalities and scales, ranging from nanoscale (electron microscopy), to microscale (cleared lightsheet microscopy and array tomography), and mesoscale (structural and functional magnetic resonance imaging). Additionally, many of the datasets include dense segmentation and meshes.
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### How do you plan to prepare the dataset

lotus

### Please share a sample of the data

```text
aws s3 ls --no-sign-request s3://bossdb-open-data/

2022-02-26 11:02:10 1.5 KiB witvliet2020/Dataset_8_Segmentation/synapses/info
2022-02-26 11:02:11 1.5 KiB witvliet2020/Dataset_8_Segmentation/synapses/provenance
2022-02-18 05:20:18 446 Bytes witvliet2020/Dataset_8_Segmentation/template/info
2022-06-21 10:00:04 3.8 KiB witvliet2020/Dataset_8_Segmentation_Properties/info

Total Objects: 664318037
Total Size: 849.7 TiB
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

1.5 to 2 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, South America

### How will you be distributing your data to storage providers

Cloud storage (i.e. S3)

### How do you plan to choose storage providers

Slack, Big data exchange

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by caoxinhe0108** [comment]
This is the SP that I am currently cooperating with, please check it out, thank you

f02050599	Bang Sai, Phra Nakhon Si Ayutthaya, TH
f02063202	Mueang Nonthaburi, Nonthaburi, TH
f02064089	Singapore, Singapore, SG
f02058557	Kuala Lumpur, Kuala Lumpur, MY
f02045964	Sham Shui Po, Sham Shui Po, HK
f02055638	Kuala Lumpur, Kuala Lumpur, MY
f02056391	Hong Kong, Central and Western, HK
f02048990	Hong Kong, Central and Western, HK
f02041085	Tokyo, Tokyo, JP
f02044834	Singapore, Singapore, SG
f02046736	Jakarta, Jakarta, ID
f02030031	Singapore, Singapore, SG
f02029895	Seoul, Seoul, KR
f01170282	Hong Kong, Central and Western, HK
f02059055	Seoul, Seoul, KR
f02042992	Singapore, Singapore, SG

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 5PiB

**Expected weekly DataCap usage rate**
> 600TiB

**Client address**
>f147wnixotnvgcjacmwqlhj7qrkb2g2zhcvt3ykwa

**Comment by TimGuo7** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebgglqxl6gj7cwnakj7s5fagurheclndntgct263xcfzgckao2igq 
#### Address 
> f147wnixotnvgcjacmwqlhj7qrkb2g2zhcvt3ykwa
#### Datacap Allocated
> 256.00TiB
#### Signer Address
> f1yslbnnqzrjlyuxsmyxfbqcc7xthcavgpripjevi
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebgglqxl6gj7cwnakj7s5fagurheclndntgct263xcfzgckao2igq

**Comment by caoxinhe0108** [comment]
checker:manualTrigger

**Comment by caoxinhe0108** [comment]
checker:manualTrigger

**Comment by caoxinhe0108** [comment]
checker:manualTrigger

**Comment by Chuangshi1** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacea5nnhngq4rnmygnnaenig64faaagmo5orcwmi6pwkibnztud5zms 
#### Address 
> f147wnixotnvgcjacmwqlhj7qrkb2g2zhcvt3ykwa
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f1mdk7s2vntzm6hu35yuo6vjubtrpfnb2awhgvrri
#### Id
> 4c28b630-39f3-4c0f-a91f-8b365c4b9d63
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacea5nnhngq4rnmygnnaenig64faaagmo5orcwmi6pwkibnztud5zms

**Comment by SuperChaiChai** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceacqorsb2qo2nmn6e2oajzrbge6bukaxkpbzu3vfbajmqp26vdn4i 
#### Address 
> f147wnixotnvgcjacmwqlhj7qrkb2g2zhcvt3ykwa
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f12mckci3omexgzoeosjvstcfxfe4vqw7owdia3da
#### Id
> 4c28b630-39f3-4c0f-a91f-8b365c4b9d63
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceacqorsb2qo2nmn6e2oajzrbge6bukaxkpbzu3vfbajmqp26vdn4i

**Comment by caoxinhe0108** [comment]
checker:manualTrigger

**Comment by 1ane-1** [comment]
checker:manualTrigger

**Comment by ipollo00** [comment]
checker:manualTrigger

**Comment by ipollo00** [comment]
DD:
The data backup keeps growing, every node can be retrieved, and the initial reports are healthy without any issues.
Willing to support.

**Comment by ipollo00** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebsnj5myt5pivr7x6srpcregt22dikkqvqs4jhcfiugtetbetqxkq 
#### Address 
> f147wnixotnvgcjacmwqlhj7qrkb2g2zhcvt3ykwa
#### Datacap Allocated
> 1.00PiB
#### Signer Address
> f1n5wlrrhoxpkgwij25xrtt7w7g2k3fhbthmdn6ri
#### Id
> 5c5ae5c8-882c-415f-bc1f-7235cd3e1b99
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebsnj5myt5pivr7x6srpcregt22dikkqvqs4jhcfiugtetbetqxkq

**Comment by igoovo** [comment]
It looks normal.
I can give my support.

**Comment by igoovo** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceastiocw3xpeoy6ntsyneb6ksix2l4kb5i77ohkg6gajz437k75kw 
#### Address 
> f147wnixotnvgcjacmwqlhj7qrkb2g2zhcvt3ykwa
#### Datacap Allocated
> 1.00PiB
#### Signer Address
> f1shnsfayxqll77svffaxnjenms7bbbysbqcatrpy
#### Id
> 5c5ae5c8-882c-415f-bc1f-7235cd3e1b99
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceastiocw3xpeoy6ntsyneb6ksix2l4kb5i77ohkg6gajz437k75kw

**Comment by caoxinhe0108** [comment]
checker:manualTrigger

**Comment by cryptowhizzard** [comment]
Just a short message.

http://datasetcreators.com/downloadedcarfiles/1836-f02100549-f02058146-40174839-baga6ea4seaqdzy6gomv6gfal6ptwui2cbqtt5lxbowrp2awet6mdrl6hj25jyda/

Retrieving files works.
Applicant is storing according to what he indicated in the LDN subject.

Good work!

**Comment by caoxinhe0108** [comment]
It's in progress

**Comment by caoxinhe0108** [comment]
checker:manualTrigger

**Comment by mikezli** [comment]
checker:manualTrigger

**Comment by mikezli** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced2d3sqy75ocohpcu3fo62smgvnisp2bqb6cb3cqtpembzjgemvci 
#### Address 
> f147wnixotnvgcjacmwqlhj7qrkb2g2zhcvt3ykwa
#### Datacap Allocated
> 2.00PiB
#### Signer Address
> f1dnb3uz7sylxk6emti3ififcvu3nlufnnsjui6ea
#### Id
> 27d096b9-d966-45b0-ad72-3bb0148c407f
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced2d3sqy75ocohpcu3fo62smgvnisp2bqb6cb3cqtpembzjgemvci

**Comment by sxxfuture-official** [comment]
Good report and retrieval rate, will support

**Comment by sxxfuture-official** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebsndmosk5haassj6ap4dcc5vc34sc6u2yi6pkw4yop7ilnhnhex6 
#### Address 
> f147wnixotnvgcjacmwqlhj7qrkb2g2zhcvt3ykwa
#### Datacap Allocated
> 2.00PiB
#### Signer Address
> f1foiomqlmoshpuxm6aie4xysffqezkjnokgwcecq
#### Id
> 27d096b9-d966-45b0-ad72-3bb0148c407f
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebsndmosk5haassj6ap4dcc5vc34sc6u2yi6pkw4yop7ilnhnhex6

**Comment by caoxinhe0108** [comment]
checker:manualTrigger

**Comment by caoxinhe0108** [comment]
checker:manualTrigger

**Comment by nj-steve** [comment]
checker:manualTrigger

**Comment by nj-steve** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebmeorbw2g2g64m5nj22zqsggo2bnfu6zcfzbvd2i4tdkyghvvwbk 
#### Address 
> f147wnixotnvgcjacmwqlhj7qrkb2g2zhcvt3ykwa
#### Datacap Allocated
> 1.25PiB
#### Signer Address
> f1xx6555qijma7igpnjspyvdunc4vfxkawnpqy5ii
#### Id
> 9db0be11-8725-4ed0-aa67-a68f38dcbc6e
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebmeorbw2g2g64m5nj22zqsggo2bnfu6zcfzbvd2i4tdkyghvvwbk

**Comment by nj-steve** [comment]
This client contact me. The report look good.

**Comment by luobin544** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebsbipfqfn7cmxvecqmhhytlc5rhrniyyfmxzygbbgzecp65m6eo6 
#### Address 
> f147wnixotnvgcjacmwqlhj7qrkb2g2zhcvt3ykwa
#### Datacap Allocated
> 1.25PiB
#### Signer Address
> f1tbd632f6w62glfaf7wjpimacbnjiz26poyoes2q
#### Id
> 9db0be11-8725-4ed0-aa67-a68f38dcbc6e
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebsbipfqfn7cmxvecqmhhytlc5rhrniyyfmxzygbbgzecp65m6eo6
