### ISSUE TITLE
[DataCap Application] <Bowenkaicheng> - <Booksinfo>

### ISSUE THREAD

**Issue by davidwang3554** [filecoin-project/filecoin-plus-large-datasets#1837]
### Data Owner Name

Booksinfo

### Data Owner Country/Region

China

### Data Owner Industry

Information, Media & Telecommunications

### Website

 https://booksinfo.cn

### Social Media

```text
N/A.
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

500TiB

### On-chain address for first allocation

f1hvqotftmyiwwqvs227qo4gh6zxmho6q3wtzumcq

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Beijing Bowen Kaicheng Digital Technology Co., Ltd. is a company dedicated to digital content production services (excluding publishing and distribution); digital cultural and creative content application services; conference and exhibition services; cultural venue management services; other cultural and artistic brokerage agents; organizing cultural and artistic exchanges Activities; Information Systems Integration Services Company. And with the digital construction of public culture and the digital construction of cultural industries, Huaxia Ancient Books Library is a free and open online ancient books library created by Beijing Bowen Kaicheng Digital Technology Co., Ltd.
Huaxia Ancient Book Library is a free and open online ancient book library created by Beijing Bowen Kaicheng Digital Technology Co., Ltd. Committed to open sharing, introduction, and recommendation of valuable ancient rare books, calligraphy and paintings, and encourages the digital archiving of cultural and artistic works, and the sharing content is limited to books in the field of public copyright. We try our best to present the appearance and content of books. Through this plan, everyone can enjoy books, calligraphy and paintings that are hard to be seen freely and for free. I hope everyone can feel the progress of human civilization. After years of research and collection, the company is committed to open sharing, introduction, and recommendation of valuable ancient books and rare books. Provide everyone with free and free appreciation of those hard-to-find books, from which they can feel the progress of human civilization.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
At present, we have collected about 700TiB of data, and we are still collecting and sorting. Ancient books are mainly in scanned PDF, picture, text and other formats, and are limited to books in the field of public copyright. It is publicly available for download and circulation by all.
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### How do you plan to prepare the dataset

I don't know yet

### Please share a sample of the data

```text
https://www.aliyundrive.com/s/7vHtMQt6rgD
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Monthly

### For how long do you plan to keep this dataset stored on Filecoin

Permanently

### In which geographies do you plan on making storage deals

Greater China

### How will you be distributing your data to storage providers

I don't know yet

### How do you plan to choose storage providers

I don't know yet

### How do you plan to make deals to your storage providers

I don't know yet

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
Can you explain about the composition of 700 TB data?

**Comment by davidwang3554** [comment]
> Can you explain about the composition of 700 TB data?

Hey, These data are mainly high-definition scanned files such as ancient books and paintings of celebrities in various dynasties in China, ancient calligraphy works, ancient poetry collections, historical materials, local chronicles, etc., mainly in PDF, TIFF, JPG and other formats. Some of them are stored on the Alibaba Cloud network disk, and most of them are stored on the local disk.

**Comment by Sunnyiscoming** [comment]
Could you send an email to filplus-app-review@fil.org with your official domain in order to confirm your identity? Email name should includes the issue id #1837.

**Comment by davidwang3554** [comment]
> Could you send an email to [filplus-app-review@fil.org](mailto:filplus-app-review@fil.org) with your official domain in order to confirm your identity? Email name should includes the issue id #1837.

Hey, we have sent an email, please check it. Thanks!

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 5PiB

**Expected weekly DataCap usage rate**
> 500TiB

**Client address**
>f1hvqotftmyiwwqvs227qo4gh6zxmho6q3wtzumcq
