### ISSUE TITLE
[DataCap Application] DAG House - Web3.Storage

### ISSUE THREAD

**Issue by dchoi27** [filecoin-project/filecoin-plus-large-datasets#1838]
### Data Owner Name

DAG House and the users of our tools

### Data Owner Country/Region

United States

### Data Owner Industry

Web3 / Crypto

### Website

https://web3.storage/

### Social Media

```text
https://twitter.com/web3storage
https://www.linkedin.com/company/dag-house
```

### Total amount of DataCap being requested

15PiB

### Weekly allocation of DataCap requested

250TiB

### On-chain address for first allocation

f3ugiocmlvcaixff6gisjyi3nupy4l6bwlfbrqfe647y3urntcba2quri3v53hie4ad65fuydpiczgz2olgd5a

### Data Type of Application

Public, Open Commercial/Enterprise

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
DAG House was founded in 2021 as a team inside Protocol Labs to develop tools to make it easy for developers and end users to host content addressed data and store the data on Filecoin. Since then our two flagship products, NFT.Storage (Internet Archive of NFTs) and Web3.Storage (developer storage platform) are used by many prominent projects and companies in Web3 and outside of it.
```

### Is this project associated with other projects/ecosystem stakeholders?

Yes

### If answered yes, what are the other projects/ecosystem stakeholders

```text
This project is associated with Protocol Labs. Projects have plans for independence.
```

### Describe the data being stored onto Filecoin

```text
User uploads that meet or adhere to web3.storage's terms of service (https://web3.storage/terms).
```

### Where was the data currently stored in this dataset sourced from

Other

### If you answered "Other" in the previous question, enter the details here

```text
User uploads and hosted IPFS instances
```

### How do you plan to prepare the dataset

others/custom tool

### If you answered "other/custom tool" in the previous question, enter the details here

```text
Users upload CAR files directly, which are then aggregated into sector sized CAR files. Our client libraries do the CAR conversion for users.
```

### Please share a sample of the data

```text
This platform serves all different kinds of media, including images, files, and videos. Some examples:

https://ipfs.io/ipfs/bafybeid5jpdqzlb4tqsd6peoa7qstoxat3ovsg62wutyp4gnzqbqsggfsq
https://ipfs.io/ipfs/bafybeihity6bx24npzvvkzopjbat25ekefjwmnshe7rvldy72dxngzf644
https://ipfs.io/ipfs/bafybeicvcevx3ktiqjsfwnjguu4lnzejlhgb35brayuod5xdtn7demfdhe
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Daily

### For how long do you plan to keep this dataset stored on Filecoin

More than 3 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, Africa, North America, South America, Europe, Australia (continent)

### How will you be distributing your data to storage providers

Cloud storage (i.e. S3), HTTP or FTP server, IPFS

### How do you plan to choose storage providers

Others

### If you answered "Others" in the previous question, what is the tool or platform you plan to use

```text
We plan to use Spade for SP selection and deal execution. Spade is being developed by the Data Programs team at Protocol Labs (https://github.com/data-preservation-programs/spade) and supports storage client to SP matching based on requirements like geography, size, retrievability, etc.
```

### How do you plan to make deals to your storage providers

Others/custom tool

### If you answered "Others/custom tool" in the previous question, enter the details here

```text
We plan to use Spade for deal execution to onboard data to Filecoin. Spade is being developed by the Data Programs team at Protocol Labs (https://github.com/data-preservation-programs/spade).

Spade was initially servicing Slingshot deals and was referred to as the Evergreen Dealer.
```

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by xinaxu** [comment]
Willing to support while watching the w3up demo

**Comment by xinaxu** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedhbivjwujkk2vkqcvbeekpxzegqtft65prbzmg6ma3bned75hlo2 
#### Address 
> f3ugiocmlvcaixff6gisjyi3nupy4l6bwlfbrqfe647y3urntcba2quri3v53hie4ad65fuydpiczgz2olgd5a
#### Datacap Allocated
> 125.00TiB
#### Signer Address
> f1k3ysofkrrmqcot6fkx4wnezpczlltpirmrpsgui
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedhbivjwujkk2vkqcvbeekpxzegqtft65prbzmg6ma3bned75hlo2

**Comment by kernelogic** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacea4o2x4knsssy6nnc4t3ybcx2hxldunrwh2sohdqkm2hl7odvs4ee 
#### Address 
> f3ugiocmlvcaixff6gisjyi3nupy4l6bwlfbrqfe647y3urntcba2quri3v53hie4ad65fuydpiczgz2olgd5a
#### Datacap Allocated
> 125.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### Id
> a6b6dc96-6fcf-495b-b3c1-44f1064f6df7
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacea4o2x4knsssy6nnc4t3ybcx2hxldunrwh2sohdqkm2hl7odvs4ee

**Comment by dchoi27** [comment]
- ready for the next allocation, making good progress with deal making with spade
- CID checker report calls out shared CIDs with ourselves, which makes sense. we've previously tried to store some of these files using different tools, including Textile Bidbot. This tool has been sunset since Dec, and we are working on re-storing those and other files via Spade instead moving forward.

**Comment by jamerduhgamer** [comment]
Willing to support developments with Spade and interested in NFT storage and storage development for Web3 as well.

**Comment by jamerduhgamer** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebvxx4pnivsqwovnsi2x2ddfuthgz776o6hohrviqo2e36gckee3o 
#### Address 
> f3ugiocmlvcaixff6gisjyi3nupy4l6bwlfbrqfe647y3urntcba2quri3v53hie4ad65fuydpiczgz2olgd5a
#### Datacap Allocated
> 250.00TiB
#### Signer Address
> f1kqdiokoeubyse4qpihf7yrpl7czx4qgupx3eyzi
#### Id
> 1a9f5982-8c99-4905-b134-2d7f81b1859e
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebvxx4pnivsqwovnsi2x2ddfuthgz776o6hohrviqo2e36gckee3o

**Comment by s0nik42** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceawl5e25o562hemunbcphmbhzv7mkfisoko5opzob5jwelawdv4hi 
#### Address 
> f3ugiocmlvcaixff6gisjyi3nupy4l6bwlfbrqfe647y3urntcba2quri3v53hie4ad65fuydpiczgz2olgd5a
#### Datacap Allocated
> 250.00TiB
#### Signer Address
> f1wxhnytjmklj2czezaqcfl7eb4nkgmaxysnegwii
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceawl5e25o562hemunbcphmbhzv7mkfisoko5opzob5jwelawdv4hi

**Comment by zcfil** [comment]
Due to slow remote communication, could you cc me the email so that I can quickly handle this issue.
service@szfil.com

**Comment by dkkapur** [comment]
@zcfil - sorry I missed this, was there an intent to just see that the email was received? If so - 
<img width="659" alt="image" src="https://user-images.githubusercontent.com/2343218/231969635-944cd64d-6a33-42f2-8a7e-6af375baadb9.png">

**Comment by kernelogic** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedp5mf2mp4ygndrlaluiagu7jn34bmda5eievgiexkhsp3m2bjvui 
#### Address 
> f3ugiocmlvcaixff6gisjyi3nupy4l6bwlfbrqfe647y3urntcba2quri3v53hie4ad65fuydpiczgz2olgd5a
#### Datacap Allocated
> 250.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedp5mf2mp4ygndrlaluiagu7jn34bmda5eievgiexkhsp3m2bjvui

**Comment by xinaxu** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecziukejsnu2z7wur5pgt3zbh4s534qinswobw62db3ex4u4a4uuw 
#### Address 
> f3ugiocmlvcaixff6gisjyi3nupy4l6bwlfbrqfe647y3urntcba2quri3v53hie4ad65fuydpiczgz2olgd5a
#### Datacap Allocated
> 250.00TiB
#### Signer Address
> f1k3ysofkrrmqcot6fkx4wnezpczlltpirmrpsgui
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecziukejsnu2z7wur5pgt3zbh4s534qinswobw62db3ex4u4a4uuw

**Comment by zcfil** [comment]
> @zcfil - sorry I missed this, was there an intent to just see that the email was received? If so - <img alt="image" width="659" src="https://user-images.githubusercontent.com/2343218/231969635-944cd64d-6a33-42f2-8a7e-6af375baadb9.png">
@dkkapur  Yes, I will continue to follow up

**Comment by jamerduhgamer** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacealrtz26gtfoddrba4e5ucaxh3r33du26wb377uyom3c2qnvgk4l6 
#### Address 
> f3ugiocmlvcaixff6gisjyi3nupy4l6bwlfbrqfe647y3urntcba2quri3v53hie4ad65fuydpiczgz2olgd5a
#### Datacap Allocated
> 1000.00TiB
#### Signer Address
> f1kqdiokoeubyse4qpihf7yrpl7czx4qgupx3eyzi
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacealrtz26gtfoddrba4e5ucaxh3r33du26wb377uyom3c2qnvgk4l6

**Comment by jamerduhgamer** [comment]
Willing to continue support for Spade. Next datacap tranche proposed.

**Comment by Patapon0702** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebusxjz7sojxmsm2lr46r7o73hz6hvvqcsr6vsl23m7oyne6utbxs 
#### Address 
> f3ugiocmlvcaixff6gisjyi3nupy4l6bwlfbrqfe647y3urntcba2quri3v53hie4ad65fuydpiczgz2olgd5a
#### Datacap Allocated
> 1000.00TiB
#### Signer Address
> f1ho2liobpznr7llma6xcl7jtififsfvhdnudn4yy
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebusxjz7sojxmsm2lr46r7o73hz6hvvqcsr6vsl23m7oyne6utbxs

**Comment by Patapon0702** [comment]
Willing to support.

**Comment by dkkapur** [comment]
@Patapon0702 @jamerduhgamer can you resign this? the v3.1 multisig ran out of DataCap so the allocation #4 is being rerequested.

**Comment by jamerduhgamer** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecidmiutpjegutajni6yzqk2w5gjlyree66ez5zpweyxfjapokgzu 
#### Address 
> f3ugiocmlvcaixff6gisjyi3nupy4l6bwlfbrqfe647y3urntcba2quri3v53hie4ad65fuydpiczgz2olgd5a
#### Datacap Allocated
> 1000.00TiB
#### Signer Address
> f1kqdiokoeubyse4qpihf7yrpl7czx4qgupx3eyzi
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecidmiutpjegutajni6yzqk2w5gjlyree66ez5zpweyxfjapokgzu

**Comment by jamerduhgamer** [comment]
Resigning due to Deep's request.

**Comment by Patapon0702** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecew3fy4nnnb6egny6ipfirqwgweq7eaiblhwj4iu6bj6hgi3zg36 
#### Address 
> f3ugiocmlvcaixff6gisjyi3nupy4l6bwlfbrqfe647y3urntcba2quri3v53hie4ad65fuydpiczgz2olgd5a
#### Datacap Allocated
> 1000.00TiB
#### Signer Address
> f1ho2liobpznr7llma6xcl7jtififsfvhdnudn4yy
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecew3fy4nnnb6egny6ipfirqwgweq7eaiblhwj4iu6bj6hgi3zg36

**Comment by Patapon0702** [comment]
Resigned.

**Comment by dchoi27** [comment]
Onboarding is making good progress - would be good to get more support!
<img width="1774" alt="image" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/11778450/81f8a6f1-cff0-4530-a4a5-dc7e4fd85360">

**Comment by kernelogic** [comment]
checker:manualTrigger

**Comment by herrehesse** [comment]
checker:manualTrigger

**Comment by liyunzhi-666** [comment]
checker:manualTrigger

**Comment by liyunzhi-666** [comment]
@dchoi27  has explained to me in slack about the CID sharing and I will support this round.

**Comment by liyunzhi-666** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedwwp7sfac6hxhhtbtdhbs7fjl4pbjeg53dcn2g6zch7cyzvhu3za 
#### Address 
> f3ugiocmlvcaixff6gisjyi3nupy4l6bwlfbrqfe647y3urntcba2quri3v53hie4ad65fuydpiczgz2olgd5a
#### Datacap Allocated
> 1.95PiB
#### Signer Address
> f1pszcrsciyixyuxxukkvtazcokexbn54amf7gvoq
#### Id
> c20b85f8-c506-4773-a537-2f21af30c87a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedwwp7sfac6hxhhtbtdhbs7fjl4pbjeg53dcn2g6zch7cyzvhu3za

**Comment by herrehesse** [comment]
checker:manualTrigger

**Comment by herrehesse** [comment]
checker:manualTrigger

**Comment by kernelogic** [comment]
Does this belong to "merged dataset" ?

**Comment by dchoi27** [comment]
no. this is user uploaded data via web3.storage and nft.storage

**Comment by cryptowhizzard** [comment]
checker:manualTrigger

**Comment by Patapon0702** [comment]
checker:manualTrigger

**Comment by cryptowhizzard** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebkfmnnja6wjefj3teksud3ei6dm5w4yzzh7kurgy55ynq2fp6psw 
#### Address 
> f3ugiocmlvcaixff6gisjyi3nupy4l6bwlfbrqfe647y3urntcba2quri3v53hie4ad65fuydpiczgz2olgd5a
#### Datacap Allocated
> 1000.00TiB
#### Signer Address
> f1krmypm4uoxxf3g7okrwtrahlmpcph3y7rbqqgfa
#### Id
> 8fc42f7e-0bbe-4eec-ba69-faafcfe136a6
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebkfmnnja6wjefj3teksud3ei6dm5w4yzzh7kurgy55ynq2fp6psw

**Comment by jamerduhgamer** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb3fouufwdswm3bgqoapcadfcri4fmbp5v2d6abqxs2c6yypox7bs 
#### Address 
> f3ugiocmlvcaixff6gisjyi3nupy4l6bwlfbrqfe647y3urntcba2quri3v53hie4ad65fuydpiczgz2olgd5a
#### Datacap Allocated
> 1000.00TiB
#### Signer Address
> f1kqdiokoeubyse4qpihf7yrpl7czx4qgupx3eyzi
#### Id
> 8fc42f7e-0bbe-4eec-ba69-faafcfe136a6
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb3fouufwdswm3bgqoapcadfcri4fmbp5v2d6abqxs2c6yypox7bs

**Comment by dchoi27** [comment]
@simonkim0515 we're down to our last allocation on this application but would like to continue onboarding more data. now that the new max is 15PiB per application what would be the best way to change this application's from 5 to 15PiB?

**Comment by simonkim0515** [comment]
@dchoi27 you can  change the "Total amount of DataCap being requested" section to the amount you'd like, but please explain in the application why you are increasing the amount to make sure community members and notaries are all on the same page.

**Comment by dchoi27** [comment]
Thanks - edited above and left this note

> 2023-07-25 EDIT: Changed from 5PiB to 15PiB as the data users are storing with web3.storage is growing to need this volume of data (especially given we are looking to store multiple copies to enable a performant retrieval experience from SPs to users). In addition, when we originally filed this application, 5PiB was the max amount we could request on a single app.

**Comment by cryptowhizzard** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacea2xogxbghgp7mi3yfemnqytdueja55mxou4rjkky5ravxw436v5k 
#### Address 
> f3ugiocmlvcaixff6gisjyi3nupy4l6bwlfbrqfe647y3urntcba2quri3v53hie4ad65fuydpiczgz2olgd5a
#### Datacap Allocated
> 498.16TiB
#### Signer Address
> f1krmypm4uoxxf3g7okrwtrahlmpcph3y7rbqqgfa
#### Id
> f536be0b-0162-4875-8522-a20f0017cbd5
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacea2xogxbghgp7mi3yfemnqytdueja55mxou4rjkky5ravxw436v5k

**Comment by liyunzhi-666** [comment]
checker:manualTrigger

**Comment by liyunzhi-666** [comment]
@dchoi27 shared the program with me in slack earlier and it looks good.I can support this round.

**Comment by liyunzhi-666** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaz2g3comgwi4yyebqp5uyfeliz72kspsmuawkqfrho4fjchunk4g 
#### Address 
> f3ugiocmlvcaixff6gisjyi3nupy4l6bwlfbrqfe647y3urntcba2quri3v53hie4ad65fuydpiczgz2olgd5a
#### Datacap Allocated
> 498.16TiB
#### Signer Address
> f1pszcrsciyixyuxxukkvtazcokexbn54amf7gvoq
#### Id
> f536be0b-0162-4875-8522-a20f0017cbd5
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaz2g3comgwi4yyebqp5uyfeliz72kspsmuawkqfrho4fjchunk4g

**Comment by herrehesse** [comment]
checker:manualTrigger

**Comment by dchoi27** [comment]
application is still active!

**Comment by kernelogic** [comment]
Lol another victim of https://github.com/keyko-io/filecoin-verifier-frontend/issues/851

**Comment by cryptowhizzard** [comment]
> Lol another victim of [keyko-io/filecoin-verifier-frontend#851](https://github.com/keyko-io/filecoin-verifier-frontend/issues/851)

./drama --stop && continue;

Just ping the team to reopen it.

**Comment by clriesco** [comment]
Removed stale label and reopened issue :)

**Comment by jbesraa** [comment]
hey @dchoi27 - its not possible to change the application total amount after it was already created. please open a new application for additional datacap.

**Comment by dchoi27** [comment]
ok because of ^ - closing this one in favor of #2192 2192
