### ISSUE TITLE
[DataCap Application] JINYEXIN

### ISSUE THREAD

**Issue by jinyexon** [filecoin-project/filecoin-plus-large-datasets#1842]
### Data Owner Name
JINYEXIN

### Data Owner Country/Region
China

### Data Owner Industry
Construction, Property & Real Estate

### Website
[https://www.jinyexon.com/](https://www.jinyexon.com/)

### Social Media
gh_604558c80ab8  (Wechat)

### Total amount of DataCap being requested
5 PiB

### Weekly allocation of DataCap requested
500 TiB

### On-chain address for first allocation
f1r56jyfdgh74z3fj5biwkkxprasjqlm4f3hs4ssa

### Data Type of Application
Private Commercial/Enterprise

### Custom multisig
No

### Share a brief history of your project and organization
Shenzhen Jinye New Material Technology Co., Ltd. is located in Shenzhen, the frontier city of my country's reform and opening up; the company was established in 2002, and quickly became a large-scale professional manufacturer of PVC, POF, PET shrink film labels and composite bags , due to business needs, the company is identified as a general taxpayer enterprise, and has independent import and export rights, and has obtained a printing license, and has branches in Hong Kong and Shanghai to serve customers as conveniently as possible

### Is this project associated with other projects/ecosystem stakeholders?
No

### Describe the data being stored onto Filecoin
Our data is mainly workshop monitoring, printing materials, large-format content, advertisements, etc.

### Where was the data currently stored in this dataset sourced from
My own storage infra

### How do you plan to prepare the dataset
lotus

### Please share a sample of the data
https://drive.google.com/drive/folders/1DblCbZT2fOuH6JNocZgpK4_-H29cj9mn?usp=share_link

### Confirm that this is a public dataset that can be retrieved by anyone on the Network
Yes

### What is the expected retrieval frequency for this data
Yearly

### For how long do you plan to keep this dataset stored on Filecoin
More than 3 years

### In which geographies do you plan on making storage deals
Greater China

### How will you be distributing your data to storage providers
Shipping hard drives

### How do you plan to choose SP
Partners

### If you already have a list of storage providers to work with, fill out their names and provider IDs below
01824405 | ChengDu | CN |
f02061213 HEILONGJIANG CN
f02041661 ChengDu CN
f02028326 US
f02006691 HongKong

### How do you plan to make deals to your storage providers
Lotus client

### Can you confirm that you will follow the Fil+ guideline
Yes

**Comment by Sunnyiscoming** [comment]
The website you provided is not about your organization. Can you check it?

**Comment by jinyexon** [comment]
> The website you provided is not about your organization. Can you check it?

It is correct, it seems that there will be problems when opening it with chrome, please try to open it with other browsers!!

**Comment by jinyexon** [comment]
![image](https://user-images.githubusercontent.com/128370231/227716908-ebbcede1-dfc8-495d-948d-319a646f53b9.png)

**Comment by jinyexon** [comment]
![image](https://user-images.githubusercontent.com/128370231/227717072-bf0abfec-ce06-4a92-af27-18d5480333c4.png)
And please use the Chinese Intranet to open

**Comment by Sunnyiscoming** [comment]
I used the Chinese Intranet to open. And I tried firefox, IE, Edge. But I still can not open this website.

**Comment by lyjmry** [comment]
Can you try to clear the cache and open it again?

**Comment by jinyexon** [comment]
> I used the Chinese Intranet to open. And I tried firefox, IE, Edge. But I still can not open this website.

Can you try to clear the cache and open it again?

**Comment by jinyexon** [comment]
I opened it with 
![Uploading image.png…]()

**Comment by Sunnyiscoming** [comment]
![image](https://user-images.githubusercontent.com/105098820/228570751-e7580a4b-14a1-4826-907b-d96ac5b4459c.png)
I tried but I failed. Maybe you can ask notaries check that.

**Comment by xiaoyuaiheshui** [comment]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/43629914/228801788-fea21bdc-566e-4653-bd34-67c4bcb3492a.png">
I checked that it is accessible

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 5PiB

**Expected weekly DataCap usage rate**
> 500TiB

**Client address**
>f1r56jyfdgh74z3fj5biwkkxprasjqlm4f3hs4ssa

**Comment by kyokaki** [comment]
Hi, I have same question that can't open that website from your organization. And I have tried differ browser that shows the same results. Hope you can fix it then more notaries won't have same problems with it.

**Comment by jinyexon** [comment]
> Hi, I have same question that can't open that website from your organization. And I have tried differ browser that shows the same results. Hope you can fix it then more notaries won't have same problems with it.

http://www.jinyexon.com/

**Comment by 1ane-1** [comment]
![image](https://user-images.githubusercontent.com/91301211/236373968-41627c15-11ac-4f10-9418-2c2af821b8c3.png)
It is avaliable.

**Comment by 1ane-1** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceandk4ktawcjrsz6gerv6rpzgtxwwlsep4jm7ic23prqz5eqzljvy 
#### Address 
> f1r56jyfdgh74z3fj5biwkkxprasjqlm4f3hs4ssa
#### Datacap Allocated
> 250.00TiB
#### Signer Address
> f1mdk7s2vntzm6hu35yuo6vjubtrpfnb2awhgvrri
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceandk4ktawcjrsz6gerv6rpzgtxwwlsep4jm7ic23prqz5eqzljvy

**Comment by igoovo** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebjakkjvzffbhwmdrsciyktrsfnq4sdqcmnmy6kwlqy32ivjmocwg 
#### Address 
> f1r56jyfdgh74z3fj5biwkkxprasjqlm4f3hs4ssa
#### Datacap Allocated
> 250.00TiB
#### Signer Address
> f1shnsfayxqll77svffaxnjenms7bbbysbqcatrpy
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebjakkjvzffbhwmdrsciyktrsfnq4sdqcmnmy6kwlqy32ivjmocwg

**Comment by igoovo** [comment]
First round support.

**Comment by ipollo00** [comment]
checker:manualTrigger

**Comment by ipollo00** [comment]
lotus client retrieve --provider f09693 bafybeiapoxgihzfarzbti6qo7vw7ebkvsdjhlhni7fzl6jjzvyjlv4afwm 9693.car
![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/116627408/21294c48-d205-4f3c-98a4-4061ae626e14)

**Comment by ipollo00** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb6yvme7e6cwb3zar4attpsijpahwkpryobqxyk6d453wvlmhg5ku 
#### Address 
> f1r56jyfdgh74z3fj5biwkkxprasjqlm4f3hs4ssa
#### Datacap Allocated
> 500.00TiB
#### Signer Address
> f1n5wlrrhoxpkgwij25xrtt7w7g2k3fhbthmdn6ri
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb6yvme7e6cwb3zar4attpsijpahwkpryobqxyk6d453wvlmhg5ku

**Comment by a1991car** [comment]
lotus client retrieve --provider f02130918 bafybeidmc73paymaqzp6iqkihfujbydbmqxty23yhywuy7y6t5hz7a3b2a bafybeidmc73paymaqzp6iqkihfujbydbmqxty23yhywuy7y6t5hz7a3b2a.car
![WechatIMG1187](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/32447611/2711e143-f166-4335-b10a-5d768b048775)

**Comment by a1991car** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedrreb6rv77jhvxvtfxi2c5z6c5bbptjansk4u46zapj436oxd3re 
#### Address 
> f1r56jyfdgh74z3fj5biwkkxprasjqlm4f3hs4ssa
#### Datacap Allocated
> 500.00TiB
#### Signer Address
> f1qnumecdypgrbaebtkdfjnwt5ndacadcuas3deiq
#### Id
> 3a6dbc62-970e-46b5-9f8b-5b283aec1a18
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedrreb6rv77jhvxvtfxi2c5z6c5bbptjansk4u46zapj436oxd3re

**Comment by Chuangshi1** [comment]
checker:manualTrigger

**Comment by Chuangshi1** [comment]
<img width="886" alt="63905e2b2188b06c1f0cb621a27c5cf" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/112937825/85a110e8-42ee-45e5-8c4c-b8f190f33cfa">

**Comment by Chuangshi1** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecwsvliyrzg4nfz4d7swuxggyrm2bncqlrkrh3kmwtd7h5jargadm 
#### Address 
> f1r56jyfdgh74z3fj5biwkkxprasjqlm4f3hs4ssa
#### Datacap Allocated
> 1000.00TiB
#### Signer Address
> f1mdk7s2vntzm6hu35yuo6vjubtrpfnb2awhgvrri
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecwsvliyrzg4nfz4d7swuxggyrm2bncqlrkrh3kmwtd7h5jargadm

**Comment by SuperChaiChai** [comment]
<img width="928" alt="image" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/42091141/1de22c15-0008-4688-9e27-3d27b93ff921">

**Comment by SuperChaiChai** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecflioblmv7k3bhpsjsn2ognr7hwcjbamihhvflk2p3smxmt4vzdi 
#### Address 
> f1r56jyfdgh74z3fj5biwkkxprasjqlm4f3hs4ssa
#### Datacap Allocated
> 1000.00TiB
#### Signer Address
> f12mckci3omexgzoeosjvstcfxfe4vqw7owdia3da
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecflioblmv7k3bhpsjsn2ognr7hwcjbamihhvflk2p3smxmt4vzdi

**Comment by jinyexon** [comment]
keep watching

**Comment by mikezli** [comment]
![2e211e9a8069315a6fe0869719b831e](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/118169683/1d446b9f-ebdf-4bb9-a09c-4d6c985f5c23)

**Comment by mikezli** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceblawd3ftpfgqdvgqn4poesofznao5yeknsyzghpynpaa7p6auvpy 
#### Address 
> f1r56jyfdgh74z3fj5biwkkxprasjqlm4f3hs4ssa
#### Datacap Allocated
> 1.95PiB
#### Signer Address
> f1dnb3uz7sylxk6emti3ififcvu3nlufnnsjui6ea
#### Id
> 5f949453-25ad-41a8-a660-54034f48a911
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceblawd3ftpfgqdvgqn4poesofznao5yeknsyzghpynpaa7p6auvpy

**Comment by NDLABS-OFFICE** [comment]
checker:manualTrigger

**Comment by NDLABS-OFFICE** [comment]
check bot is very healthy, according to ND audit mark willing to support

**Comment by NDLABS-OFFICE** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedghgk5wtdllo4vhh5tuixkbrjoalrspwc5fvdznanzmmcuz7ltf2 
#### Address 
> f1r56jyfdgh74z3fj5biwkkxprasjqlm4f3hs4ssa
#### Datacap Allocated
> 1.95PiB
#### Signer Address
> f1yayfsv6whu3rheviucvventj3y6t542xfpb47ei
#### Id
> 5f949453-25ad-41a8-a660-54034f48a911
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedghgk5wtdllo4vhh5tuixkbrjoalrspwc5fvdznanzmmcuz7ltf2

**Comment by jinyexon** [comment]
I'm watching this

**Comment by jinyexon** [comment]
I'm watching this

**Comment by lyjmry** [comment]
checker:manualTrigger

**Comment by nj-steve** [comment]
checker:manualTrigger

**Comment by nj-steve** [comment]
the cid report looks fine. the retrieval report also looks fine.
willing to support this round.

**Comment by nj-steve** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceccceuga5zisodtyvylgwqqcalaidhrdenfu6t7bqpgq7ldakzkgw 
#### Address 
> f1r56jyfdgh74z3fj5biwkkxprasjqlm4f3hs4ssa
#### Datacap Allocated
> 1.34PiB
#### Signer Address
> f1xx6555qijma7igpnjspyvdunc4vfxkawnpqy5ii
#### Id
> 7fece818-87c0-40b7-bdae-410de89992e8
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceccceuga5zisodtyvylgwqqcalaidhrdenfu6t7bqpgq7ldakzkgw

**Comment by jinyexon** [comment]
We have added some new data, and we want to allocate about 3.5P quota, how should I do it. @Sunnyiscoming
