### ISSUE TITLE
[DataCap Application] Hexun Huagu Information Technology Co., Ltd.

### ISSUE THREAD

**Issue by mnxspl** [filecoin-project/filecoin-plus-large-datasets#1843]
### Data Owner Name

Hexun Huagu Information 

### Data Owner Country/Region

China

### Data Owner Industry

IT & Technology Services

### Website

https://www.jiguang.cn/

### Social Media

```text
https://www.jiguang.cn/
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

500TiB

### On-chain address for first allocation

f16z5cwessyj44gogblzz3n7qilxcccwfkfwk5mmi

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Founded in 2011, Aurora is a leading customer interaction and marketing technology service provider in China. At the beginning of its establishment, Jiguang focused on providing stable and efficient message push services for enterprises. With its first-mover advantage, it has grown into a mobile message push service provider with a far leading market share. With the continuous strengthening of enterprises' demand for customer contact and marketing growth, Jiguang has proactively launched solutions such as message cloud and marketing cloud to help enterprises achieve multi-channel customer contact and interaction needs, as well as artificial intelligence and big data. The application of marketing technology to help the digital transformation of enterprises.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
The data stored on the filecoin network includes the data generated by the company since our establishment 12 years ago. During the 12 years of growth, we have a large amount of corporate culture data, training data, company precious meeting data, project data, business data, etc. . We help customers plan plans, precious customer data, planning data, we carry out marketing activities, precious market data, marketing data, etc. ，
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### How do you plan to prepare the dataset

lotus, singularity

### Please share a sample of the data

```text
Link：https://pan.baidu.com/s/1f3NL_VpsmOs2rKFpk1cAEQ 
Extraction code：c4p8
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

1 to 1.5 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, Europe

### How will you be distributing your data to storage providers

HTTP or FTP server, Shipping hard drives, Lotus built-in data transfer

### How do you plan to choose storage providers

Slack, Filmine

### How do you plan to make deals to your storage providers

Boost client, Lotus client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
Could you send an email to filplus-app-review@fil.org with your official domain in order to confirm your identity? Email name should includes the issue id #1843.
Can you provide more data samples to prove that you have 5 PB data already?
Please share more detailed information about sps you will cooperate with.

**Comment by Sunnyiscoming** [comment]
![image](https://user-images.githubusercontent.com/105098820/229324680-8911e019-64ac-4f91-95e9-34a43ee886c3.png)
I received email ended by jiguangs.cn not jiguang.cn you provided. Can you explain about that?

**Comment by Sunnyiscoming** [comment]
Any update here?

**Comment by Sunnyiscoming** [comment]
It will be closed in 3 days if there is no update here.
