### ISSUE TITLE
[DataCap Application] NOAA Geostationary Operational Environmental Satellites (GOES) 17, 18<1/2>

### ISSUE THREAD

**Issue by VincentShii** [filecoin-project/filecoin-plus-large-datasets#1849]
### Data Owner Name

The National Oceanic and Atmospheric Administration

### Data Owner Country/Region

United States

### Data Owner Industry

Life Science / Healthcare

### Website

https://github.com/awslabs/open-data-docs/tree/main/docs/noaa/noaa-goes16

### Social Media

```text
https://www.noaa.gov/
https://twitter.com/NOAA
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

1PiB

### On-chain address for first allocation

f1bgxaqwgnrkbwe4wheancxkxf532jlgm4a65gh4y

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
organization: Yuga was founded in 2019 with core members mainly from Microsoft, AWS and other major leading organizations. Till now we have about 20 employees in Shanghai office. We've been dedicated to building and optimizing industry-leading order encapsulation components for three years, enabling rapid processing and encapsulation of real data, and continuously empowering storage providers and data content providers.

Project: NOAA is an agency that enriches life through science. Our agency holds key leadership roles in shaping international ocean, fisheries, climate, space and weather policies.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
GOES satellites provide continuous weather imagery and monitoring of meteorological and space environment data across North America.
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### How do you plan to prepare the dataset

lotus

### Please share a sample of the data

```text
https://registry.opendata.aws/noaa-goes/
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

1.5 to 2 years

### In which geographies do you plan on making storage deals

Asia other than Greater China, North America, South America, Europe

### How will you be distributing your data to storage providers

Shipping hard drives, Lotus built-in data transfer

### How do you plan to choose storage providers

Slack, Filmine, Big data exchange, Partners

### How do you plan to make deals to your storage providers

Lotus client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by TakiChain** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebjwlfdf2fwzjxkh5pz7ynefrlwrn5lsnl4ldygnxyqod54cgzd7g 
#### Address 
> f1bgxaqwgnrkbwe4wheancxkxf532jlgm4a65gh4y
#### Datacap Allocated
> 256.00TiB
#### Signer Address
> f15impf3j2zcaex4lhyxndxswuuhv24vzstuqtxsi
#### Id
> 8cb5c66d-ced1-41a7-aeb2-202d25128ade
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebjwlfdf2fwzjxkh5pz7ynefrlwrn5lsnl4ldygnxyqod54cgzd7g

**Comment by Aifabot-Cloud** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceayx4cjbi5haa2vppg63gmwrxd5yun4brqpbsf4fnpgkgj2jgjzic 
#### Address 
> f1bgxaqwgnrkbwe4wheancxkxf532jlgm4a65gh4y
#### Datacap Allocated
> 256.00TiB
#### Signer Address
> f174fg3bqbln3zjnkxtyf6s54txqkr7yqkj6cig7y
#### Id
> 8cb5c66d-ced1-41a7-aeb2-202d25128ade
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceayx4cjbi5haa2vppg63gmwrxd5yun4brqpbsf4fnpgkgj2jgjzic

**Comment by Casey-PG** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaixqomlpicgvn2hjjsukpo745mvmp272n5s4b63wu66pzlumt47c 
#### Address 
> f1bgxaqwgnrkbwe4wheancxkxf532jlgm4a65gh4y
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f1d4yb3wags3mtddzesxoo63jv7dmlec3bq4yteni
#### Id
> e34cf631-56b2-48ff-92cb-740be251c367
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaixqomlpicgvn2hjjsukpo745mvmp272n5s4b63wu66pzlumt47c

**Comment by cryptowhizzard** [comment]
Hi,

I have checked on your application. Can you tell me why you don't follow on the rules of distribution? This application is only in China and needs 3 other continents to be stored on at least.

![Scherm­afbeelding 2023-04-12 om 15 08 02](https://user-images.githubusercontent.com/36404435/231467332-6e1e40c8-2e0d-4c27-9de5-f8a5f8bce6ea.png)

**Comment by Meibuy** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacect65n56swti6seuvg2w53tcg3bfcx7v6o7sv72qcjl62ijp6mhzu 
#### Address 
> f1bgxaqwgnrkbwe4wheancxkxf532jlgm4a65gh4y
#### Datacap Allocated
> 1.00PiB
#### Signer Address
> f1bwugfihrmn3iyunzyxst5nttql3dge4khwmurtq
#### Id
> 5c039bfc-e60f-4a7b-ac9a-6a1ae5174732
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacect65n56swti6seuvg2w53tcg3bfcx7v6o7sv72qcjl62ijp6mhzu

**Comment by Meibuy** [comment]
Good summary report and ongoing communication from the applicant. We would like to see more and more useful datasets get onboarded.

**Comment by Aifabot-Cloud** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacea6jwf42qepvwbgewjuymlj3ntazgfapih5uhaizsxqga2rzitayc 
#### Address 
> f1bgxaqwgnrkbwe4wheancxkxf532jlgm4a65gh4y
#### Datacap Allocated
> 2.00PiB
#### Signer Address
> f174fg3bqbln3zjnkxtyf6s54txqkr7yqkj6cig7y
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacea6jwf42qepvwbgewjuymlj3ntazgfapih5uhaizsxqga2rzitayc

**Comment by cryptowhizzard** [comment]
Hi

None of the data stored is retrievable here. Why did you sign this application @Aifabot-Cloud . It is against the FIL+ rules and guidelines.

Secondly the distribution of this application is not OK and not according to the FIL+ rules and guidelines.

@Ehume-Yuga why did you not follow the rules and guidelines of FIL+?

<img width="1106" alt="Scherm­afbeelding 2023-05-06 om 19 27 19" src="https://user-images.githubusercontent.com/36404435/236638543-58808755-a894-4c5a-a591-f1ea834ac38f.png">

**Comment by TakiChain** [comment]
checker:manualTrigger

**Comment by VincentShii** [comment]
@TakiChain Thank you!

**Comment by VincentShii** [comment]
Keep it open!

**Comment by VincentShii** [comment]
Keep it open!

**Comment by VincentShii** [comment]
keep open

**Comment by VincentShii** [comment]
keep open

**Comment by clriesco** [comment]
Removed stale label, reopened issue :)

**Comment by cryptowhizzard** [comment]
Hello,

I have downloaded the data but this data is not the data the applicant said he was storing.

![Scherm­afbeelding 2023-09-06 om 14 55 36](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/36404435/c9c78ce6-08a2-4196-8d9a-d808d9e2880b)
![Scherm­afbeelding 2023-09-06 om 14 57 08](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/36404435/98b7c468-ba6b-415d-b44c-a3b0e53dcbdf)

My retrieved sample can be downloaded here:

http://www.datasetcreators.com/downloadedcarfiles/httpretrievals/1849-f02100522-f01122339-36037183-baga6ea4seaqpqruxm7rr3qsvwfdbgorzxh4ienrcalanndysohsamzrc3ffboda

ls -l 1849-f02100522-f01122339-36037183-baga6ea4seaqpqruxm7rr3qsvwfdbgorzxh4ienrcalanndysohsamzrc3ffboda
-rw-r--r-- 1 root root 1405729464 Aug  7 08:59 1849-f02100522-f01122339-36037183-baga6ea4seaqpqruxm7rr3qsvwfdbgorzxh4ienrcalanndysohsamzrc3ffboda

Sample done at august 7th . Deal ID 36037183

**Comment by VincentShii** [comment]
Can you check once more? SPs' replies are different with you. There's some error in your program.

**Comment by VincentShii** [comment]
Yes

**Comment by VincentShii** [comment]
Yes

**Comment by VincentShii** [comment]
Yes

**Comment by Sunnyiscoming** [comment]
Hello, @VincentShii per the https://github.com/filecoin-project/notary-governance/issues/922 for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

This information will be reviewed by Fil+ Governance team to confirm validity and then the application will be allowed to move forward for additional notary review.

**Comment by VincentShii** [comment]
checker:manualTrigger

**Comment by VincentShii** [comment]
@Sunnyiscoming I followed your order and submitted the form.

**Comment by Casey-PG** [comment]
Retrieval looks good. Please keep the allocation more decentralized in the future.

**Comment by Casey-PG** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced33l5ruol6ut3w3o5ao6umadpumlllu7m2p6prndnsu35bpttuuo 
#### Address 
> f1bgxaqwgnrkbwe4wheancxkxf532jlgm4a65gh4y
#### Datacap Allocated
> 1.25PiB
#### Signer Address
> f1d4yb3wags3mtddzesxoo63jv7dmlec3bq4yteni
#### Id
> 902bfe3b-43e7-40e3-bd6c-d6a6c71ad9b2
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced33l5ruol6ut3w3o5ao6umadpumlllu7m2p6prndnsu35bpttuuo

**Comment by VincentShii** [comment]
In progress, need open
