### ISSUE TITLE
[DataCap Application] NOAA Geostationary Operational Environmental Satellites (GOES) 17, 18<2/2>

### ISSUE THREAD

**Issue by VincentShii** [filecoin-project/filecoin-plus-large-datasets#1850]
### Data Owner Name

The National Oceanic and Atmospheric Administration

### Data Owner Country/Region

United States

### Data Owner Industry

Life Science / Healthcare

### Website

https://github.com/awslabs/open-data-docs/tree/main/docs/noaa/noaa-goes16

### Social Media

```text
https://www.noaa.gov/
https://twitter.com/NOAA
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

1PiB

### On-chain address for first allocation

f15fdvvwwjbpbt7vkfjqibtmmg2c6wwkzuzpdkhfa

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
organization: Yuga was founded in 2019 with core members mainly from Microsoft, AWS and other major leading organizations. Till now we have about 20 employees in Shanghai office. We've been dedicated to building and optimizing industry-leading order encapsulation components for three years, enabling rapid processing and encapsulation of real data, and continuously empowering storage providers and data content providers.

Project: NOAA is an agency that enriches life through science. Our agency holds key leadership roles in shaping international ocean, fisheries, climate, space and weather policies.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
GOES satellites provide continuous weather imagery and monitoring of meteorological and space environment data across North America.
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### How do you plan to prepare the dataset

lotus

### Please share a sample of the data

```text
https://registry.opendata.aws/noaa-goes/
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

1.5 to 2 years

### In which geographies do you plan on making storage deals

Asia other than Greater China, North America, South America, Europe

### How will you be distributing your data to storage providers

Shipping hard drives, Lotus built-in data transfer

### How do you plan to choose storage providers

Slack, Filmine, Big data exchange, Partners

### How do you plan to make deals to your storage providers

Lotus client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 5PiB

**Expected weekly DataCap usage rate**
> 1PiB

**Client address**
>f15fdvvwwjbpbt7vkfjqibtmmg2c6wwkzuzpdkhfa

**Comment by TakiChain** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebvvxum5ybtamt3oyeqjekrcobuvu3igoxkfz2w2mqael3ebf57f2 
#### Address 
> f15fdvvwwjbpbt7vkfjqibtmmg2c6wwkzuzpdkhfa
#### Datacap Allocated
> 256.00TiB
#### Signer Address
> f15impf3j2zcaex4lhyxndxswuuhv24vzstuqtxsi
#### Id
> 15c4df7c-3097-4073-92fd-0cdcb4964c43
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebvvxum5ybtamt3oyeqjekrcobuvu3igoxkfz2w2mqael3ebf57f2

**Comment by Aifabot-Cloud** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceax3povjq5gopgfgo4cqgeq2hlemcwzkbhuartqgpdtvmlegai5iy 
#### Address 
> f15fdvvwwjbpbt7vkfjqibtmmg2c6wwkzuzpdkhfa
#### Datacap Allocated
> 256.00TiB
#### Signer Address
> f174fg3bqbln3zjnkxtyf6s54txqkr7yqkj6cig7y
#### Id
> 15c4df7c-3097-4073-92fd-0cdcb4964c43
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceax3povjq5gopgfgo4cqgeq2hlemcwzkbhuartqgpdtvmlegai5iy

**Comment by Meibuy** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedba5wpv2ciibikmqa4jedfwh7zfsck2hmmgeegtmfi6xpvmjamxa 
#### Address 
> f15fdvvwwjbpbt7vkfjqibtmmg2c6wwkzuzpdkhfa
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f1bwugfihrmn3iyunzyxst5nttql3dge4khwmurtq
#### Id
> c035800f-ddfd-4241-8d84-c8eaec67bd0b
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedba5wpv2ciibikmqa4jedfwh7zfsck2hmmgeegtmfi6xpvmjamxa

**Comment by Meibuy** [comment]
Good summary report and ongoing communication from the applicant. We would like to see more and more useful datasets get onboarded.

**Comment by Meibuy** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacea7pom6ndcmfmpwca4ewpkb3zbl4uuo5zwdgfbkfua3thpu5ty3as 
#### Address 
> f15fdvvwwjbpbt7vkfjqibtmmg2c6wwkzuzpdkhfa
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f1bwugfihrmn3iyunzyxst5nttql3dge4khwmurtq
#### Id
> 25212a0e-50d4-4340-ab6f-cdb13582a208
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacea7pom6ndcmfmpwca4ewpkb3zbl4uuo5zwdgfbkfua3thpu5ty3as

**Comment by Protocan** [comment]
Thank you for integrating more trustworthy data into the network and please continue to follow fileplus' guidelines.

**Comment by Protocan** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced5dzl4rc65frhd4qb2zqkfy43gisvvtztg5doyy6wfwjk3omkar4 
#### Address 
> f15fdvvwwjbpbt7vkfjqibtmmg2c6wwkzuzpdkhfa
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f1vxbqrf7rfum3n6m5u6eb4re6xj7amvsaqnzu64y
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced5dzl4rc65frhd4qb2zqkfy43gisvvtztg5doyy6wfwjk3omkar4

**Comment by Aifabot-Cloud** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedz4cjxnu7zkolsgccmswdcz6syxww6dzefvvtcezujczljphuy7g 
#### Address 
> f15fdvvwwjbpbt7vkfjqibtmmg2c6wwkzuzpdkhfa
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f174fg3bqbln3zjnkxtyf6s54txqkr7yqkj6cig7y
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedz4cjxnu7zkolsgccmswdcz6syxww6dzefvvtcezujczljphuy7g

**Comment by Aifabot-Cloud** [comment]
Based on the chat history and fellow notaries' reviews, I would like to get this application moving forward. Please follow the feedback and update us if there's any change or if you need any help.

**Comment by Casey-PG** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaw7r4fs24oc3pjtawyl3v2bhz3rslks6f7oyfkbi7zp4kbesk4me 
#### Address 
> f15fdvvwwjbpbt7vkfjqibtmmg2c6wwkzuzpdkhfa
#### Datacap Allocated
> 3.25PiB
#### Signer Address
> f1d4yb3wags3mtddzesxoo63jv7dmlec3bq4yteni
#### Id
> 3ff6a298-3b0e-4a01-af3c-d59c12485154
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaw7r4fs24oc3pjtawyl3v2bhz3rslks6f7oyfkbi7zp4kbesk4me

**Comment by BobbyChoii** [comment]
Open datasets bring great value to the network. Happy to see more of them join Filecoin. Please keep the allocation in line with Filplus guidlines.

**Comment by BobbyChoii** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced2wdrz6aol5z2bqyickwxetl7y33hxxyhqcehrkph4pf5jxyeyha 
#### Address 
> f15fdvvwwjbpbt7vkfjqibtmmg2c6wwkzuzpdkhfa
#### Datacap Allocated
> 3.25PiB
#### Signer Address
> f1irqs2gmctiv3jcdfwuch7oxvf4ixh3k4b2wc24i
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced2wdrz6aol5z2bqyickwxetl7y33hxxyhqcehrkph4pf5jxyeyha

**Comment by cryptowhizzard** [comment]
Hello,

ALL SP's are not supporting retrieval of data. This is against FIL+ rules and guidelines.
Secondly the distribution is not OK. Everything is in Asai and not geo spread.  This is against FIL+ rules and guidelines.

Please have your SP's support retrieval.

<img width="1114" alt="Scherm­afbeelding 2023-05-05 om 20 21 36" src="https://user-images.githubusercontent.com/36404435/236537796-04e502fd-8bd1-4b1a-abbf-7d77d9d0d047.png">

**Comment by Sunnyiscoming** [comment]
> Hello,
> 
> ALL SP's are not supporting retrieval of data. This is against FIL+ rules and guidelines.
> Secondly the distribution is not OK. Everything is in Asai and not geo spread. This is against FIL+ rules and guidelines.
> 
> Please have your SP's support retrieval.

Can you explain about it?

**Comment by VincentShii** [comment]
![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/122421372/cd35e1a4-b705-4578-90d2-88e70343d615)
@Sunnyiscoming It supports retrieval.

**Comment by cryptowhizzard** [comment]
This client is actively stalling http retrievals and blocked http ranged requests with a reverse proxy to prevent it's data being investigated.

It works as follows:

One set's a bandwidth limit with NGINX on the HTTP retrieval. After a random certain amount the limit is set to zero. This makes the transfer timeout. Because range retrieval is disabled in NGINX one cannot pick up where he left and needs to start all over again. 

Log can be found at http://datasetcreators.com/downloadedcarfiles/logs/1850.log

**Comment by Filplus-govteam** [comment]
Hello @VincentShii  per the new guidelines https://github.com/filecoin-project/notary-governance/issues/922 for Open Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

This information will be reviewed by Fil+ Governance team to confirm validity toward the Fil+ guideline of a distributed storage plan and SPs posted in the comments here. Let us know if you have any questions.
