### ISSUE TITLE
[DataCap Application] CESM LENS

### ISSUE THREAD

**Issue by wei-Alice** [filecoin-project/filecoin-plus-large-datasets#1853]
### Data Owner Name

NCAR

### Data Owner Country/Region

United States

### Data Owner Industry

Environment

### Website

https://ncar.ucar.edu/

### Social Media

```text
Facebook  https://www.facebook.com/NCAR.UCAR/
Youtube   https://www.youtube.com/ncarucar
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

1PiB

### On-chain address for first allocation

f1lbvnyrc2jtvgwrpnkfjpdut6nezg57iq5nycpti

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
NCAR is a center of research excellence in Earth system science sponsored by the National Science Foundation.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
The Community Earth System Model (CESM) Large Ensemble Numerical Simulation (LENS) dataset includes a 40-member ensemble of climate simulations for the period 1920-2100 using historical data (1920-2005) or assuming the RCP8.5 greenhouse gas concentration scenario (2006-2100), as well as longer control runs based on pre-industrial conditions. The data comprise both surface (2D) and volumetric (3D) variables in the atmosphere, ocean, land, and ice domains.
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### How do you plan to prepare the dataset

lotus, singularity

### Please share a sample of the data

```text
https://registry.opendata.aws/ncar-cesm-lens/
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Sporadic

### For how long do you plan to keep this dataset stored on Filecoin

2 to 3 years

### In which geographies do you plan on making storage deals

Asia other than Greater China, North America, Europe

### How will you be distributing your data to storage providers

HTTP or FTP server, Shipping hard drives

### How do you plan to choose storage providers

Slack, Big data exchange

### How do you plan to make deals to your storage providers

Lotus client, Singularity

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
Can you introduce your organizaion? Please share more detailed information about sps you will cooperate with.

**Comment by wei-Alice** [comment]
Hi @Sunnyiscoming , I'm an individual community member. I want to store some public data and take part in Filecoin for storage. Also I want to test the filecoin network performance. Thank you for your attention.

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 5PiB

**Expected weekly DataCap usage rate**
> 1PiB

**Client address**
>f1lbvnyrc2jtvgwrpnkfjpdut6nezg57iq5nycpti

**Comment by Casey-PG** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebgr4ahpnyvh3vruodmox3dfmqrjet6khlvf2wyare7hgh3x7x6i2 
#### Address 
> f1lbvnyrc2jtvgwrpnkfjpdut6nezg57iq5nycpti
#### Datacap Allocated
> 256.00TiB
#### Signer Address
> f1d4yb3wags3mtddzesxoo63jv7dmlec3bq4yteni
#### Id
> b680f1c5-419d-42ff-80ec-a3d5f9e117a7
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebgr4ahpnyvh3vruodmox3dfmqrjet6khlvf2wyare7hgh3x7x6i2

**Comment by Aifabot-Cloud** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedq4ph726nrg6x7w5l3os3zol5cktkn5r6xegtstppl6ljruibt5q 
#### Address 
> f1lbvnyrc2jtvgwrpnkfjpdut6nezg57iq5nycpti
#### Datacap Allocated
> 256.00TiB
#### Signer Address
> f174fg3bqbln3zjnkxtyf6s54txqkr7yqkj6cig7y
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedq4ph726nrg6x7w5l3os3zol5cktkn5r6xegtstppl6ljruibt5q

**Comment by TakiChain** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebz4dzzakmsodznu4agmxvm3yy67bypgkzcv3rtncate6tk56raik 
#### Address 
> f1lbvnyrc2jtvgwrpnkfjpdut6nezg57iq5nycpti
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f15impf3j2zcaex4lhyxndxswuuhv24vzstuqtxsi
#### Id
> 3c0cbba2-edae-4f68-9c9b-81f966ed0889
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebz4dzzakmsodznu4agmxvm3yy67bypgkzcv3rtncate6tk56raik

**Comment by Casey-PG** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecb37glhf5hdryfgklciagkqjjfmmjm3sdvu4fcptgdvrm3a77yac 
#### Address 
> f1lbvnyrc2jtvgwrpnkfjpdut6nezg57iq5nycpti
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f1d4yb3wags3mtddzesxoo63jv7dmlec3bq4yteni
#### Id
> 3c0cbba2-edae-4f68-9c9b-81f966ed0889
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecb37glhf5hdryfgklciagkqjjfmmjm3sdvu4fcptgdvrm3a77yac

**Comment by Meibuy** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebetreclrct6gfud6ykoct4clv6jjrma5btem2lresckppzn7rnnq 
#### Address 
> f1lbvnyrc2jtvgwrpnkfjpdut6nezg57iq5nycpti
#### Datacap Allocated
> 1.00PiB
#### Signer Address
> f1bwugfihrmn3iyunzyxst5nttql3dge4khwmurtq
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebetreclrct6gfud6ykoct4clv6jjrma5btem2lresckppzn7rnnq

**Comment by Meibuy** [comment]
Good summary report and ongoing communication from the applicant. We would like to see more and more useful datasets get onboarded.

**Comment by AthSmith** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacechdk66wudvu4q3apv47o3alxgg3v44gu6iknmdmkcgdzaxvvybto 
#### Address 
> f1lbvnyrc2jtvgwrpnkfjpdut6nezg57iq5nycpti
#### Datacap Allocated
> 2.00PiB
#### Signer Address
> f1vxbqrf7rfum3n6m5u6eb4re6xj7amvsaqnzu64y
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacechdk66wudvu4q3apv47o3alxgg3v44gu6iknmdmkcgdzaxvvybto

**Comment by AthSmith** [comment]
Peformed due diligence before and the report looks good. Willing to help onboard this application.

**Comment by Aifabot-Cloud** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebbfkirj3iolsng5in6iglzlmhulhexo5uwnuos45jfvjgy6vice4 
#### Address 
> f1lbvnyrc2jtvgwrpnkfjpdut6nezg57iq5nycpti
#### Datacap Allocated
> 2.00PiB
#### Signer Address
> f174fg3bqbln3zjnkxtyf6s54txqkr7yqkj6cig7y
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebbfkirj3iolsng5in6iglzlmhulhexo5uwnuos45jfvjgy6vice4

**Comment by cryptowhizzard** [comment]
Hi,

It seems that none of your SP's allow retrieval of data. This is against FIl+ guidelines.
Secondly there is no distribution outside your geo region ( Asia ) -> also against  FIl+ guidelines.

Any reason why you did not follow up on the rules of FIL+?

<img width="1117" alt="Scherm­afbeelding 2023-05-05 om 20 14 55" src="https://user-images.githubusercontent.com/36404435/236536416-8990b0e1-de42-4fd2-907a-feed5a9ec842.png">

**Comment by wei-Alice** [comment]
No, do not close this application.

**Comment by wei-Alice** [comment]
Yes, keep open

**Comment by wei-Alice** [comment]
Yes

**Comment by wei-Alice** [comment]
Yes please

**Comment by cryptowhizzard** [comment]
checker:manualTrigger

**Comment by wei-Alice** [comment]
Yes please

**Comment by herrehesse** [comment]
@Filplus-govteam @Kevin-FF-USA @raghavrmadya

Application is abusive, same set of signed notaries and growing exponentially. Looks like the abusers are just sealing their old datacap for the foreseeable future. Can we please remove/hold the DC from these applications asap?

**Comment by wei-Alice** [comment]
@herrehesse We are just waiting for SP's update about sealing. Why did you make such a rude conclusion?

**Comment by cryptowhizzard** [comment]
This client is actively stalling http retrievals and blocked http ranged requests with a reverse proxy to prevent it's data being investigated.

It works as follows:

One set's a bandwidth limit with NGINX on the HTTP retrieval. After a random certain amount the limit is set to zero. This makes the transfer timeout. Because range retrieval is disabled in NGINX one cannot pick up where he left and needs to start all over again. 

Log can be found at http://datasetcreators.com/downloadedcarfiles/logs/1853.log

**Comment by wei-Alice** [comment]
Open please.

**Comment by cryptowhizzard** [comment]
Dear wei-Alice,

As notary I am doing due diligence on your LDN. I could not get retrieval to work. Can you please upload the car file of CID baga6ea4seaqpvvdm7unpgiz2qtik45kwwa3cfhmpc4uxlunqnudlp4l3cmagchi ?

You can use our upload system at http://send.datasetcreators.com. Please select 7 days for the system to keep the file and post the link you received here so I (and other notaries) can download your content.

**Comment by wei-Alice** [comment]
> Hello @wei-Alice per the new guidelines [filecoin-project/notary-governance#922](https://github.com/filecoin-project/notary-governance/issues/922) for Open Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.
> 
> This information will be reviewed by Fil+ Governance team to confirm validity toward the Fil+ guideline of a distributed storage plan and SPs posted in the comments here. Let us know if you have any questions.

Finished the form.

**Comment by cryptowhizzard** [comment]
> Dear wei-Alice,
> 
> As notary I am doing due diligence on your LDN. I could not get retrieval to work. Can you please upload the car file of CID baga6ea4seaqpvvdm7unpgiz2qtik45kwwa3cfhmpc4uxlunqnudlp4l3cmagchi ?
> 
> You can use our upload system at http://send.datasetcreators.com. Please select 7 days for the system to keep the file and post the link you received here so I (and other notaries) can download your content.

Reminder.

**Comment by wei-Alice** [comment]
Can you try to download it by yourself? We support retrieval.
> > Dear wei-Alice,
> > As notary I am doing due diligence on your LDN. I could not get retrieval to work. Can you please upload the car file of CID baga6ea4seaqpvvdm7unpgiz2qtik45kwwa3cfhmpc4uxlunqnudlp4l3cmagchi ?
> > You can use our upload system at http://send.datasetcreators.com. Please select 7 days for the system to keep the file and post the link you received here so I (and other notaries) can download your content.
> 
> Reminder.

**Comment by cryptowhizzard** [comment]
> Can you try to download it by yourself? We support retrieval.
> 
> > > Dear wei-Alice,
> > > As notary I am doing due diligence on your LDN. I could not get retrieval to work. Can you please upload the car file of CID baga6ea4seaqpvvdm7unpgiz2qtik45kwwa3cfhmpc4uxlunqnudlp4l3cmagchi ?
> > > You can use our upload system at http://send.datasetcreators.com. Please select 7 days for the system to keep the file and post the link you received here so I (and other notaries) can download your content.
> > 
> > 
> > Reminder.

If I could I would not have asked you
