### ISSUE TITLE
[DataCap Application] Holon Global Investments Ltd

### ISSUE THREAD

**Issue by catherinekades** [filecoin-project/filecoin-plus-large-datasets#1856]
### Data Owner Name
Holon Global Investments Ltd

### Data Owner Country/Region
Australia

### Data Owner Industry
Web3 / Crypto

### Website
[https://holon.investments/](https://holon.investments/)

### Social Media
https://www.linkedin.com/company/holon-global-investments/ (@globalholon)

### Total amount of DataCap being requested
1.686523 PiB

### Weekly allocation of DataCap requested
500 TiB

### On-chain address for first allocation
f3sdqvozebdxpclbn2ug4fzhohbzfwakaj2sov2khkx42l2qmy6xvg7wqsxtygdoawxjkb5hzvctij6bkoy26a

### Data Type of Application
Public, Open Dataset (Research/Non-Profit)

### Custom multisig
No

### Share a brief history of your project and organization
We are storing the General Index by https://archive.org/.  The General Index is an invaluable utility for researchers who wish to search for articles about plants, chemicals, genes, proteins, materials, geographical locations, and other entities of interest. The General Index allows scholars and students all over the world to perform specialized and customized searches within the scope of their disciplines and research over the full corpus.

Holon is a leading Asia Pacific distributed data storage provider that is powered by the Filecoin ecosystem. 

### Is this project associated with other projects/ecosystem stakeholders?
No

### Describe the data being stored onto Filecoin
The General Index consists of 3 tables derived from 107,233,728 journal articles. A table of n-grams, ranging from unigrams to 5-grams, is extracted using SpaCy. Each  of the 355,279,820,087 rows of the n-gram table consists of an n-gram coupled with a journal article id. A second table is constructed using Yake and consists of 19,740,906,314 rows, each with a keywords and an article id. A third table associates an article id with metadata. 

### Where was the data currently stored in this dataset sourced from
Other

### If you answered "Other" in the previous question, enter the details here
https://archive.org/search?query=%22general+index%22+AND+collection%3Amulticasting&sort=title

### How do you plan to prepare the dataset
lotus

### Please share a sample of the data
https://archive.org/download/GeneralIndex.keywords.1/doc_keywords_1.sql.zip

### Confirm that this is a public dataset that can be retrieved by anyone on the Network
Yes

### What is the expected retrieval frequency for this data
Monthly

### For how long do you plan to keep this dataset stored on Filecoin
2 to 3 years

### In which geographies do you plan on making storage deals
Australia (continent)

### How will you be distributing your data to storage providers
HTTP or FTP server

### How do you plan to choose SP
Slack

### If you already have a list of storage providers to work with, fill out their names and provider IDs below
DCENT
Distributed Storage Systems - Australia
Vigilant - Australia

### How do you plan to make deals to your storage providers
Others/custom tool

### If you answered "Others/custom tool" in the previous question, enter the details here
Manual HTTP download, manual deal IDs, manual deal ID creation.

### Can you confirm that you will follow the Fil+ guideline
Yes

**Comment by Sunnyiscoming** [comment]
Could you send an email to filplus-app-review@fil.org with your official domain in order to confirm your identity? Email name should includes the issue id #1856.

**Comment by catherinekades** [comment]
@Sunnyiscoming we completed this requirement yesterday.  Please confirm received.

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 1.686523PiB

**Expected weekly DataCap usage rate**
> 500TiB

**Client address**
>f3sdqvozebdxpclbn2ug4fzhohbzfwakaj2sov2khkx42l2qmy6xvg7wqsxtygdoawxjkb5hzvctij6bkoy26a

**Comment by catherinekades** [comment]
@Sunnyiscoming do you need any further information to process our request?
With Thanks
Catherine

**Comment by zcfil** [comment]
checker:manualTrigger

**Comment by zcfil** [comment]
Found only a small amount of data. Can you provide more data samples?

**Comment by catherinekades** [comment]
@zcfil You will see all the data on this URL https://archive.org/search?query=%22general+index%22+AND+collection%3Amulticasting&sort=title

**Comment by zcfil** [comment]
Okay, I looked at the new data sample.

How will you allocate this data, which cities do you plan to store data in, and which data storage vendors do you currently have with you.

I look forward to hearing from you.

**Comment by catherinekades** [comment]
Hi @zcfil,
Our Company Holon will be storing one instance in Australia, one instance in New Zealand,  other companies:
- DCENT - Holland, Europe
- DSS - Australia
- Vigilant - Australia
Let me know if you need anything more.
Thanks
Catherine

**Comment by zcfil** [comment]
Okay, your response is somewhat incomplete. Improve communication efficiency and answer all our questions positively. What data storage vendors do you currently have in cooperation with

**Comment by catherinekades** [comment]
@marshyonline and @zcfil Please let me know if you need anything further to progress my application.

Regards
Catherine

**Comment by zcfil** [comment]
> > Okay, your response is somewhat incomplete. Improve communication efficiency and answer all our questions positively. What data storage vendors do you currently have in cooperation with
> 
> I find it unusual that you are asking what Storage Vendors they (or SP's) are working with - can you provide context to this question as to why its relevant what storage vendors are being used?

I don't think there's a problem with asking questions. If you don't even have basic SP cooperation, what is the purpose of applying for LDN

**Comment by marshyonline** [comment]
Thanks @zcfil - I think this question was lost in translation, I am not debating questions just looking into the meaning of the question. When someone says "Storage Vendor" to me - this means the vendor that manufactured the storage hardware(EG: Seagate, Western Digital) - not the storing SP's

**Comment by catherinekades** [comment]
@galen-mcandrew @dkkapur How can I get some progress on my application?
Thanks
Catherine

**Comment by liyunzhi-666** [comment]
Hey @catherinekades , I checked out the data sample. In the application, you only declare the name of the SP, you can state exactly on which nodes this data will be stored in the future (provide the SP ID)

**Comment by zcfil** [comment]
> Thanks @zcfil - I think this question was lost in translation, I am not debating questions just looking into the meaning of the question. When someone says "Storage Vendor" to me - this means the vendor that manufactured the storage hardware(EG: Seagate, Western Digital) - not the storing SP's

Oky，Translation issues, some misunderstandings

**Comment by zcfil** [comment]
> @zcfil Apologies for late reply, had to source information from SPs and was also on leave.
> 
> DCENT - Holland, Europe, f02095232 DSS - Australia, f01919423 Vigilant - Australia f02055660
> 
> Please let me know if you need anything further.
> 
> Thanks Catherine

F02095232 is not a miner node
![image](https://user-images.githubusercontent.com/45065975/234583429-4d36cf01-8908-4f7b-88a5-fed288079495.png)

**Comment by catherinekades** [comment]
@zcfil Apologies DCENT are f02095132

**Comment by zcfil** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced637fuesvyiuvsmayxrvhhdna3yyfa77ubluimge5iau2durl2iq 
#### Address 
> f3sdqvozebdxpclbn2ug4fzhohbzfwakaj2sov2khkx42l2qmy6xvg7wqsxtygdoawxjkb5hzvctij6bkoy26a
#### Datacap Allocated
> 86.34TiB
#### Signer Address
> f1cjzbiy5xd4ehera4wmbz63pd5ku4oo7g52cldga
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced637fuesvyiuvsmayxrvhhdna3yyfa77ubluimge5iau2durl2iq

**Comment by liyunzhi-666** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceapouijcdy5vkihlgcx5fdoyje6ilhwc2zi2emh2vcsrq6strfe6a 
#### Address 
> f3sdqvozebdxpclbn2ug4fzhohbzfwakaj2sov2khkx42l2qmy6xvg7wqsxtygdoawxjkb5hzvctij6bkoy26a
#### Datacap Allocated
> 86.34TiB
#### Signer Address
> f1pszcrsciyixyuxxukkvtazcokexbn54amf7gvoq
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceapouijcdy5vkihlgcx5fdoyje6ilhwc2zi2emh2vcsrq6strfe6a

**Comment by cryptowhizzard** [comment]
Hi,

It seems that none of your SP's allow retrieval of data. This is against FIl+ guidelines.
Secondly there is no distribution outside your geo region ( Asia ) -> also against  FIl+ guidelines.

Any reason why you did not follow up on the rules of FIL+?

<img width="1117" alt="Scherm­afbeelding 2023-05-05 om 20 14 55" src="https://user-images.githubusercontent.com/36404435/236536416-8990b0e1-de42-4fd2-907a-feed5a9ec842.png">

**Comment by catherinekades** [comment]
Re-open

**Comment by catherinekades** [comment]
This project has been delayed a couple of months, as we want to trial the new S3 api to car and distribute the project.
Regards
Catherine
