### ISSUE TITLE
[DataCap Application] Chengdu Jingshan QianQian Agricultural Co. LTD - QianQian Block Farm

### ISSUE THREAD

**Issue by licornduan** [filecoin-project/filecoin-plus-large-datasets#1859]
### Data Owner Name

Chengdu Jingshan QianQian Agricultural Co. LTD

### Data Owner Country/Region

China

### Data Owner Industry

Resources, Agriculture & Fisheries

### Website

https://farm.fankeyun.net.cn

### Social Media

```text
QianQian block farm wechat mini program
```

### Total amount of DataCap being requested

1PiB

### Weekly allocation of DataCap requested

20TiB

### On-chain address for first allocation

f2rnx2eyi25f5zwv5c4cqft372bkqwdyz5nfolfay

### Data Type of Application

Public, Open Commercial/Enterprise

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Chengdu Jingshan Qianqian Agriculture Co., Ltd. was established on October 14, 2022. The registered place is located at the 1st floor, No. 164 Guanghuabai Third Road, Qingyang District, Chengdu. The legal representative is Lu Zhaohua. Business scope includes general items: agricultural and sideline products sales; Crop cultivation services; Fresh vegetable retail; Vegetable planting; Flower planting; Gift flower sales; Flower and green plant lease and generation management; Leisure and sightseeing activities; Conference and exhibition services; Retail of edible agricultural products; Agricultural scientific research and experimental development.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
bafyreid5wj3wyzsofpautevvbl5aiolpseajormieigvb27yx35g7i3twu
bafyreiagxckx5j3qblskpoyhoj3em76c4dvdqdgp2cz7fwaiydv4egwoxa
bafykbzacebxhqrjjyo2ygynpmk23xyoicevwqlbyptlwwt4djb62ghxqnubgq
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### How do you plan to prepare the dataset

lotus

### Please share a sample of the data

```text
链接: https://pan.baidu.com/s/1j0NnouoSnDR7Fq0lbqsebg 提取码: fdk6 复制这段内容后打开百度网盘手机App，操作更方便哦
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Daily

### For how long do you plan to keep this dataset stored on Filecoin

More than 3 years

### In which geographies do you plan on making storage deals

Asia other than Greater China

### How will you be distributing your data to storage providers

Shipping hard drives

### How do you plan to choose storage providers

Partners

### How do you plan to make deals to your storage providers

Boost client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
![image](https://user-images.githubusercontent.com/105098820/228549949-d1b9cd63-d141-4eb8-b462-ffdd5a3dfca4.png)
What's the relationship between you and the organization?
https://aiqicha.baidu.com/company_detail_86410169031177
The establish time of the organization is Oct, 2022. How they have 5 PB data?
Please describe the data being stored onto Filecoin.
Can you explain how the data samples you provide relates to the organization.

**Comment by licornduan** [comment]
> ![image](https://user-images.githubusercontent.com/105098820/228549949-d1b9cd63-d141-4eb8-b462-ffdd5a3dfca4.png)
> What's the relationship between you and the organization?
> https://aiqicha.baidu.com/company_detail_86410169031177
> The establish time of the organization is Oct, 2022. How they have 5 PB data?
> Please describe the data being stored onto Filecoin.
> Can you explain how the data samples you provide relates to the organization.

This is my last work unit, and I have been using this git account personally. Is there any problem with this? Do I need to use the company's email address to register and submit the application?

**Comment by licornduan** [comment]
@Sunnyiscoming

**Comment by licornduan** [comment]
> ![image](https://user-images.githubusercontent.com/105098820/228549949-d1b9cd63-d141-4eb8-b462-ffdd5a3dfca4.png)
> What's the relationship between you and the organization?
> https://aiqicha.baidu.com/company_detail_86410169031177
> The establish time of the organization is Oct, 2022. How they have 5 PB data?
> Please describe the data being stored onto Filecoin.
> Can you explain how the data samples you provide relates to the organization.

We are providing IT technical support to this agricultural company, which owns 200 mu of land to do modern agriculture project, and has relevant business partners who need to put traditional cloud storage data on IPFS. The company's partners have data generated by agricultural ecological support projects in Sichuan and many provinces after years of deep cultivation of smart agriculture. It includes a large number of data storage requirements such as agricultural soil detection data, ecological aquaculture and ecological planting video detection data, including marketing video data needed for farm product marketing in the later stage.

@Sunnyiscoming

**Comment by Sunnyiscoming** [comment]
What are the business partners? The data you will store belongs to these business partners?

**Comment by licornduan** [comment]
Business partners are companies that provide technical support for eco-farms. Their previous storage model was traditional storage, local + cloud storage. After business cooperation with Qianqian Farm, resources were exchanged. Qianqian Farm has introduced the partner's mature ecological farm technical services, and part of the partner's business data has been introduced to IPFS storage through Qianqian Farm.

@Sunnyiscoming

**Comment by Sunnyiscoming** [comment]
Could you send an email with partners' name and cooperation materials to filplus-app-review@fil.org with your official domain in order to confirm your identity? Email name should includes the issue id #1859.

**Comment by licornduan** [comment]
Our current IT is on Tencent Cloud, the application of web3 and the local smart farm technology connection is still under development and construction, we need to create a legal person of Qian Qian Agriculture Company as the domain name holder to send you an email? Or is it OK to use the email address of the company that currently serves as our technical support?

Or you can assign the DC quota that can be obtained during the current development and construction of Qian Qian Farm. We will communicate with our partners and ask them to apply for DC quota in the way of data owners.


@Sunnyiscoming

**Comment by Sunnyiscoming** [comment]
If you agree with what I said above, I will close this application.

**Comment by licornduan** [comment]
For large data owners, I can suggest them to apply by themselves, while for small data owners, I still need to provide some space support for business requirements, right? I lowered the application to 1PB, so that we have room to work with small partners.

@Sunnyiscoming

**Comment by Sunnyiscoming** [comment]
Could you send an email with partners' name and cooperation materials to [filplus-app-review@fil.org](mailto:filplus-app-review@fil.org) with your official domain([fankeyun.net.cn](https://farm.fankeyun.net.cn/)) in order to confirm your identity? Email name should includes the issue id https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1859.

**Comment by Sunnyiscoming** [comment]
Any update here?

**Comment by Sunnyiscoming** [comment]
It will be closed if there is no reply in 3 days.
