### ISSUE TITLE
[DataCap Application] JMA Himawari-8/9

### ISSUE THREAD

**Issue by Flora-Moody** [filecoin-project/filecoin-plus-large-datasets#1860]
### Data Owner Name

NOAA

### Data Owner Country/Region

Japan

### Data Owner Industry

Environment

### Website

https://www.noaa.gov/

### Social Media

```text
https://www.facebook.com/NOAA
https://www.youtube.com/usnoaagov
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

1PiB

### On-chain address for first allocation

f1u3gc4fsh47pvrszv3otngb2t5hm3ycmtx7jxxny

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
NOAA is an agency that enriches life through science. Our reach goes from the surface of the sun to the depths of the ocean floor as we work to keep the public informed of the changing environment around them.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
Himawari-8, stationed at 140E, owned and operated by the Japan Meteorological Agency (JMA), is a geostationary meteorological satellite, with Himawari-9 as on-orbit back-up, that provides constant and uniform coverage of east Asia, and the west and central Pacific regions from around 35,800 km above the equator with an orbit corresponding to the period of the earth’s rotation.
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### How do you plan to prepare the dataset

IPFS, lotus, singularity

### Please share a sample of the data

```text
https://registry.opendata.aws/noaa-himawari/
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

1.5 to 2 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, Europe

### How will you be distributing your data to storage providers

Cloud storage (i.e. S3), HTTP or FTP server, Shipping hard drives

### How do you plan to choose storage providers

Slack, Filmine, Big data exchange

### How do you plan to make deals to your storage providers

Boost client, Lotus client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 5PiB

**Expected weekly DataCap usage rate**
> 1PiB

**Client address**
>f1u3gc4fsh47pvrszv3otngb2t5hm3ycmtx7jxxny

**Comment by Casey-PG** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceagod25pffke7uaja7kjzu7mjdwsfwlja5hpi56dkdwr7hkasjujw 
#### Address 
> f1u3gc4fsh47pvrszv3otngb2t5hm3ycmtx7jxxny
#### Datacap Allocated
> 256.00TiB
#### Signer Address
> f1d4yb3wags3mtddzesxoo63jv7dmlec3bq4yteni
#### Id
> 02382fad-8c02-4613-a308-cc71f01feeed
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceagod25pffke7uaja7kjzu7mjdwsfwlja5hpi56dkdwr7hkasjujw

**Comment by BobbyChoii** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedsxvmfppszgawgtsx63zknyz2ze5kjzal5hdyhocz3ymebsoznpq 
#### Address 
> f1u3gc4fsh47pvrszv3otngb2t5hm3ycmtx7jxxny
#### Datacap Allocated
> 256.00TiB
#### Signer Address
> f1irqs2gmctiv3jcdfwuch7oxvf4ixh3k4b2wc24i
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedsxvmfppszgawgtsx63zknyz2ze5kjzal5hdyhocz3ymebsoznpq

**Comment by cryptowhizzard** [comment]
Hello,

I checked on this application but you are not following on the rules of distribution as everything is stored in China.
Can you tell us why this is and how you are going to fix this? 

![Scherm­afbeelding 2023-04-12 om 15 28 20](https://user-images.githubusercontent.com/36404435/231472547-2643c6b7-7c67-4269-ba6e-dc0704786847.png)

@Casey-PG 
Can you let us (the community) know what due diligence has been done here for this client?
What is the data onboarding plan for this client? Where is he/she going to store the data and who is she? What is their internet capacity?
On what bases have you approved this application and why?

**Comment by TakiChain** [comment]
Checked the information applicant shared and so far everything is in line with Filplus program rules. Willing to give my signature in the next round.
Keep up the good work!

**Comment by TakiChain** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecuxjwvlcfn43o27lfk42evquga3gwztpphmhnvwybjxgpgvvfiyg 
#### Address 
> f1u3gc4fsh47pvrszv3otngb2t5hm3ycmtx7jxxny
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f15impf3j2zcaex4lhyxndxswuuhv24vzstuqtxsi
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecuxjwvlcfn43o27lfk42evquga3gwztpphmhnvwybjxgpgvvfiyg

**Comment by Aifabot-Cloud** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedtn5sg4fihcrunxghudx4sjogrmh2wnla66m74svojgu4rxzbcuy 
#### Address 
> f1u3gc4fsh47pvrszv3otngb2t5hm3ycmtx7jxxny
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f174fg3bqbln3zjnkxtyf6s54txqkr7yqkj6cig7y
#### Id
> db11a179-6403-461a-954c-a8dd6b13b157
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedtn5sg4fihcrunxghudx4sjogrmh2wnla66m74svojgu4rxzbcuy

**Comment by Meibuy** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacea2enc6ulyuyhohiwdol7k7grjqofyhub7t3g7suaao5dt6b2eifm 
#### Address 
> f1u3gc4fsh47pvrszv3otngb2t5hm3ycmtx7jxxny
#### Datacap Allocated
> 1.00PiB
#### Signer Address
> f1bwugfihrmn3iyunzyxst5nttql3dge4khwmurtq
#### Id
> 8ed8b509-d2da-4571-bbd8-59c987a2abf8
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacea2enc6ulyuyhohiwdol7k7grjqofyhub7t3g7suaao5dt6b2eifm

**Comment by Protocan** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebt26slvxiplz7paqfhzzomd6bwpmvvfd74qs5234bchojfvdwzgg 
#### Address 
> f1u3gc4fsh47pvrszv3otngb2t5hm3ycmtx7jxxny
#### Datacap Allocated
> 1.00PiB
#### Signer Address
> f1vxbqrf7rfum3n6m5u6eb4re6xj7amvsaqnzu64y
#### Id
> 8ed8b509-d2da-4571-bbd8-59c987a2abf8
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebt26slvxiplz7paqfhzzomd6bwpmvvfd74qs5234bchojfvdwzgg

**Comment by AthSmith** [comment]
willing to support this round and keep an eye on the upcoming report.

**Comment by cryptowhizzard** [comment]
Hi @Flora-Moody 

It seems none of your SP's are supporting retrieval. This is against FIL+ guidelines.
Secondly it seems you don't distribute outside your region ( Asia ) . This is also against FIL+ guidelines.

Please contact your SP's to allow retrieval as soon as possible.

![Uploading Scherm­afbeelding 2023-05-05 om 20.08.42.png…]()

**Comment by Casey-PG** [comment]
checker:manualTrigger

**Comment by Casey-PG** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb4bzongngggi4axwrp4ey7oimkekmhcxhucqrdkqea5xhfxlq7wi 
#### Address 
> f1u3gc4fsh47pvrszv3otngb2t5hm3ycmtx7jxxny
#### Datacap Allocated
> 2.00PiB
#### Signer Address
> f1d4yb3wags3mtddzesxoo63jv7dmlec3bq4yteni
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb4bzongngggi4axwrp4ey7oimkekmhcxhucqrdkqea5xhfxlq7wi

**Comment by Casey-PG** [comment]
First of all, thanks @cryptowhizzard for pointing out the unretrievable data problem. Before addressing your concerns, I would like to state that as a media company we do our best to judge from the description of the application, the information shared by the client combined with the Filplus large dataset project concept. However, unfortunately, our technical field has certain limitations. 

We signed the first and fourth rounds of this issue. The signature is provided for the following reasons: (1) This data is publicly available and we recognize its value to meet the project requirements. (2) This client contacted me on slack about their distribution plan. It was also informed that due to the different speeds of sp efficiency, the multi-regional allocation suggested by the project may not be achieved in the early stage. We also find this in many other applications, so we consider it acceptable.

At the Hongkong Web 3 Conference, we deeply felt the importance of clients, data preparers and service providers in ecology. What data means to Filecoin is clear to all participants. The way the notary public judges the project is different, which is a benefit of community diversity and perspectives. We'll pay more attention to retrieval and enhance technical understanding. 

Thank you.

**Comment by cryptowhizzard** [comment]
Hi @Casey-PG 

Thanks for your explanation. I understand that not everyone is on the same speed and same track and this is nothing personal. But when a notary indicates that the data is not retrievable / an application is not according to Fil+ rules the others should be wary to sign unless there is clear understanding that things will get on track in the near future.

If we do work here to check everything and do due diligence we expect the others to consider it and wait until discovered issues are resolved. Otherwise we can just go ahead and sign everything without any due diligence.

**Comment by Flora-Moody** [comment]
As far as I understand, filplus does not have a requirement for data to be scattered across multiple continents. China is a very large country, please refer to my sp distribution table, different cities under different provinces and different regions can meet decentralized storage.

**Comment by Flora-Moody** [comment]
ok. Got it.

**Comment by Joss-Hua** [comment]
checker:manualTrigger

**Comment by Flora-Moody** [comment]
yes

**Comment by Flora-Moody** [comment]
Yes. Please open it

**Comment by cryptowhizzard** [comment]
checker:manualTrigger

**Comment by cryptowhizzard** [comment]
> Yes. Please open it

To what ends?

None of your data is retrievable, that is against FIL+ guidelines.

This application should be closed and datacap should be revoked.

**Comment by spaceT9** [comment]
checker:manualTrigger

**Comment by Filplus-govteam** [comment]
Hello @Flora-Moody  per the https://github.com/filecoin-project/notary-governance/issues/922 for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

This information will be reviewed by Fil+ Governance team to confirm validity and then the application will be approved for notary review. Let us know if you have any questions.

**Comment by Flora-Moody** [comment]
checker:manualTrigger

**Comment by spaceT9** [comment]
checker:manualTrigger

**Comment by spaceT9** [comment]
A little advice: you need to contact your sps to increase retrieval rate before next tranche

**Comment by Flora-Moody** [comment]
checker:manualTrigger

**Comment by Flora-Moody** [comment]
@Filplus-govteam Done for the form.

**Comment by Wengeding** [comment]
checker:manualTrigger

**Comment by Wengeding** [comment]
![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/117442528/71351f5b-9124-47a3-a8c0-b3599220d2e8)
Looks good to me about your retrieval dashboard.

**Comment by Wengeding** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedqayxt4nxxtmtfyrpjgd6lfibxcepxlm6x7rty45mv7zgac4jm4a 
#### Address 
> f1u3gc4fsh47pvrszv3otngb2t5hm3ycmtx7jxxny
#### Datacap Allocated
> 2.00PiB
#### Signer Address
> f1txfsjmix4vlzido4dkildrnbw26owtlbslexmpa
#### Id
> b2fc6540-0613-474e-b83e-55a03bf8e353
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedqayxt4nxxtmtfyrpjgd6lfibxcepxlm6x7rty45mv7zgac4jm4a

**Comment by AthSmith** [comment]
Great to see that retrieval success rate is on the rise, keep up!

**Comment by AthSmith** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebxlqamsr2bdhxgtyx4tslbo7tucr6anuvqi3tejg2adyq2reyhyk 
#### Address 
> f1u3gc4fsh47pvrszv3otngb2t5hm3ycmtx7jxxny
#### Datacap Allocated
> 2.00PiB
#### Signer Address
> f1vxbqrf7rfum3n6m5u6eb4re6xj7amvsaqnzu64y
#### Id
> b2fc6540-0613-474e-b83e-55a03bf8e353
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebxlqamsr2bdhxgtyx4tslbo7tucr6anuvqi3tejg2adyq2reyhyk

**Comment by Filplus-govteam** [comment]
checker:manualTrigger

**Comment by Filplus-govteam** [comment]
SPs provided

f0397855 | Andy |  HK | 
f0518877 | LisaWu | CN | 
f01203032 | Mandy |  CN | 
f01202610 | Calvin | HK | 
f0128166 | Robert | KR | 

Actual SPs used: https://github.com/data-preservation-programs/filplus-checker-assets/blob/main/filecoin-project/filecoin-plus-large-datasets/issues/1860/1692210362327.md

Does not match here @Flora-Moody can you explain?

**Comment by Filplus-govteam** [comment]
other flags:
limited retrievals
no distribution (less than 4 SPs storing)
no geo distribution

**Comment by AthSmith** [comment]
Hey@Filplus-govteam ,thanks for your kind input.

1、The retrieval success rate is clearly shown in the report and I don't see anything inappropriate. Also all bandwidths are limited and retrieval relies heavily on bandwidth resource and entire link. 

2、There are 27(not less than 4)  SPs distributed by this applicaiton as the report, i think it's ok;

3、Up to now there is no evidence that these 27 SPs are located in the same IDC. if there is, I agree with the removal. 

Also, I reserve my opinion on whether SP can be flexible in its distribution. Thanks a lot!

**Comment by cryptowhizzard** [comment]
<img width="575" alt="Scherm­afbeelding 2023-08-17 om 21 48 17" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/36404435/2a8c6f4f-b37f-4bdf-b83e-8c931b05352a">

Before you start here @AthSmith 

I did a Hexdump on the data i could retrieve from you with deal ID 49193893 : 
hexdump -C 1860-f02100529-f02245242-49193893-baga6ea4seaqpiup55s2xofck5xibnkr7hpvbzyiinucmgbs3lyoynlydursfsmy |more

Seems that you are not storing real data.

I invite you to upload baga6ea4seaqpiup55s2xofck5xibnkr7hpvbzyiinucmgbs3lyoynlydursfsmy [here](send.datasetcreators.com) on this link so we can review and inspect the whole carfile.

Thanks!

**Comment by AthSmith** [comment]
I didn't see any logic in your conclusions and suggest you stop gaslighting if you don't have more evidence.

Also, if you don't believe the official report, suggest you share your methodology with Xinan. I do think your comment has no credibility as you're in a profitable DC business.

**Comment by cryptowhizzard** [comment]
The data stored is not the data the applicant told us he was going to store, proof is above. It’s pure fraud and your name tag is on it for eternity making your reputation worthless.
