### ISSUE TITLE
[DataCap Application] Mengxin technology 

### ISSUE THREAD

**Issue by luoxia-guwu** [filecoin-project/filecoin-plus-large-datasets#1861]
### Data Owner Name

Mengxin technology 

### Data Owner Country/Region

China

### Data Owner Industry

Arts & Recreation

### Website

https://space.bilibili.com/25852539/video?tid=0&page=4&keyword=&order=pubdate

### Social Media

```text
https://space.bilibili.com/25852539/video?tid=0&page=4&keyword=&order=pubdate
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

300TiB

### On-chain address for first allocation

f1nxs2obplhgmicjtnvhlqpw2qrsyyicsh6zjwkiy

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Mengxin Technology is located in Hangzhou, China, and its main business is digital + live broadcasting, cultural tourism, art creation, etc.

The digitization of our live streams is similar to virtual reality. We can measure the human body with a set of wearable devices and then digitally model the physical characteristics of the human body. Finally, the data we model is restored to the image display of specific characters, including movements, expressions, artistic creation, etc.

Cultural tourism digitalization refers to the publicity project we cooperate with the Culture and Tourism Bureau, we can digitally model the environment of the designated attraction including terrain, architecture, characteristic facilities, etc., and then generate promotional videos or 3D landscape videos, and then allow tourists to experience the tourist attractions in the cloud.

Digital art such as art exhibitions such as cloud art exhibitions, as well as digital museums, and so on. We can digitally model and restore historical buildings or objects that cannot be displayed on the spot or have disappeared through pictures or other descriptive messages. Finally, it is presented through video or 3D video display.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
https://space.bilibili.com/25852539/video?tid=0&page=4&keyword=&order=pubdate
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### How do you plan to prepare the dataset

lotus

### Please share a sample of the data

```text
https://space.bilibili.com/25852539/video?tid=0&page=4&keyword=&order=pubdate
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

1.5 to 2 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China

### How will you be distributing your data to storage providers

Shipping hard drives

### How do you plan to choose storage providers

Slack, Big data exchange, Partners

### How do you plan to make deals to your storage providers

Lotus client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
Social media you provided seems like a personal channel. What's the relationship between the organization and this social media?
Can you provide Chinese name of your organization? 
Can you provide more information about your project?

**Comment by luoxia-guwu** [comment]
Our company name is Hangzhou Mengxin Culture Technology Co., Ltd. We were established in August 2021, previously operating as an individual industrial and commercial enterprise (Hangzhou Fuyang Meng New Culture and Art Studio), and established as a limited liability company in March 2022.

This Bilibili account is an account maintained by our company for external display and promotional purposes.

This is our promotional [PPt](https://drive.google.com/file/d/1Ts07H7ve2OtM0BJE_IkkA3ZM1c0fAKJf/view?usp=share_link), which has more descriptions of our products and works.

![截图 2023-04-03 11-32-30](https://user-images.githubusercontent.com/127824452/229405539-878e3349-ae57-42d4-a151-a5eaa6170e0d.png)
![截图 2023-04-03 11-32-20](https://user-images.githubusercontent.com/127824452/229405544-e17531ba-0148-414e-9af8-180c92ba4e36.png)

**Comment by fireflyHZ** [comment]
I checked the customer's information and public data, found no problems, the first application I will support this time.

**Comment by fireflyHZ** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceagf35glsydpzb76ugsinxplq7qnalrgkgds3jkl2cphj5czx5kpo 
#### Address 
> f1nxs2obplhgmicjtnvhlqpw2qrsyyicsh6zjwkiy
#### Datacap Allocated
> 150.00TiB
#### Signer Address
> f1fg6jkxsr3twfnyhdlatmq36xca6sshptscds7xa
#### Id
> dd2ab497-7067-4bea-bcfc-acc1cdfeb04f
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceagf35glsydpzb76ugsinxplq7qnalrgkgds3jkl2cphj5czx5kpo

**Comment by Bitrise0111** [comment]
The client's information is correct and true. We'd like to support them in the first round.

**Comment by Bitrise0111** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb66sr7ufbfntspiqxgxq6icly6s2wxwzkppvd53ofqvel4l5v2o6 
#### Address 
> f1nxs2obplhgmicjtnvhlqpw2qrsyyicsh6zjwkiy
#### Datacap Allocated
> 150.00TiB
#### Signer Address
> f1nknj7ayq4o43czrtdoauggtwl43fbqatmqis3yy
#### Id
> dd2ab497-7067-4bea-bcfc-acc1cdfeb04f
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb66sr7ufbfntspiqxgxq6icly6s2wxwzkppvd53ofqvel4l5v2o6
