### ISSUE TITLE
[DataCap Application] NOAA Global Ensemble Forecast System (GEFS) Re-forecast

### ISSUE THREAD

**Issue by Cindy3y** [filecoin-project/filecoin-plus-large-datasets#1862]
### Data Owner Name

NOAA

### Data Owner Country/Region

United States

### Data Owner Industry

Environment

### Website

https://noaa-gefs-retrospective.s3.amazonaws.com/Description_of_reforecast_data.pdf

### Social Media

```text
https://twitter.com/NOAA
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

800TiB

### On-chain address for first allocation

f1tlrfqgjq2k6hhdf54zqkdukttvxejqjeapeymoy

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
I'm community participant. I want to store the public data.The data is from NOAA(aws). NOAA is an agency that enriches life through science. Our reach goes from the surface of the sun to the depths of the ocean floor as we work to keep the public informed of the changing environment around them.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
NOAA has generated a multi-decadal reanalysis and reforecast data set to accompany the next-generation version of its ensemble prediction system, the Global Ensemble Forecast System, version 12 (GEFSv12).
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### How do you plan to prepare the dataset

IPFS, lotus

### Please share a sample of the data

```text
https://registry.opendata.aws/noaa-gefs-reforecast/
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Sporadic

### For how long do you plan to keep this dataset stored on Filecoin

1 to 1.5 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America

### How will you be distributing your data to storage providers

HTTP or FTP server, Shipping hard drives

### How do you plan to choose storage providers

Slack, Big data exchange

### How do you plan to make deals to your storage providers

Lotus client, Singularity

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 5PiB

**Expected weekly DataCap usage rate**
> 800TiB

**Client address**
>f1tlrfqgjq2k6hhdf54zqkdukttvxejqjeapeymoy

**Comment by BobbyChoii** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedujhcliegy3d72blxkgvyopyw5xc76jc3ldklzvq5guyb4kmlsjm 
#### Address 
> f1tlrfqgjq2k6hhdf54zqkdukttvxejqjeapeymoy
#### Datacap Allocated
> 256.00TiB
#### Signer Address
> f1irqs2gmctiv3jcdfwuch7oxvf4ixh3k4b2wc24i
#### Id
> 854e6e8f-3c70-4c25-9fb1-d096f6a89fc9
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedujhcliegy3d72blxkgvyopyw5xc76jc3ldklzvq5guyb4kmlsjm

**Comment by OlivierMolenkamp** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebdlms2hwbcq7e35twxuizclaujklgdxrovjdzsl55czom66hngom 
#### Address 
> f1tlrfqgjq2k6hhdf54zqkdukttvxejqjeapeymoy
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f1fl5gjqv3xknuhka273jrsrkzqcumrp6idrnvgyi
#### Id
> 719df90d-0e88-4caa-a7f8-cb3c5dcccc36
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebdlms2hwbcq7e35twxuizclaujklgdxrovjdzsl55czom66hngom

**Comment by cryptowhizzard** [comment]
Hi @OlivierMolenkamp

Can you let us (the community) know what due diligence has been done here for this client?
What is the data onboarding plan for this client? Where is he/she going to store the data and who is she? What is their internet capacity?
On what bases have you approved this application and why?

Why is this client only storing on the machines from your own operations (Renesis mining) ?

![Scherm­afbeelding 2023-04-12 om 15 16 52](https://user-images.githubusercontent.com/36404435/231469708-f893a3a7-7627-4d7b-9948-446289d5b3ee.png)

**Comment by herrehesse** [comment]
@Casey-PG @BobbyChoii @OlivierMolenkamp REPORTED.

Please add them to "potential fraudulent" notaries. This application has already been done, this applicant is a completely new account, due diligence is completely lacking.

Removing the ability of these notaries to sign applications like this is our #1 priority. 

@raghavrmadya @galen-mcandrew @dkkapur @Sunnyiscoming - for your visibility.

**Comment by BobbyChoii** [comment]
- The dataset is public and the client reached out to me on slack, shared the allocation plan.
- This is the first round allocation, there's nothing much to check so i offered my help.

AFAIK, there is no requirement that client must have previous application history. I'm very disappointed by your false accusation.

**Comment by herrehesse** [comment]
Show the community all details of your: "client reached out to me on slack, shared the allocation plan".

**Comment by Cindy3y** [comment]
@herrehesse 
Thanks for sharing your concerns. Before explaining my application, I would like to share some backgroud of mine as data preparer in this ecosystem. My name is Cindy Lau and I'm a developer in a game company. I heard about Filecoin last year through HK web3 alumni builders network and I was learning the decentralization storage mechanism for around four to five months. I'm capable of converting car files but I do not have enough capital to pledge, so I chose to be a DP. 

To get my application moving forward, I reached out to around 20 notaries and only a few of them replied. I'm very grateful these notaries  supported my first try with Filecoin and I'm deeply sorry about the inconvince it caused for everyone. 

This dataset is from AWS public database, the dataset size is 392TiB and I planed to coordinate with 12 SPs. I contacted service providers through HK filecoin groups and slack fil-deal-market channel. So far, I have confirmed sps from China mainland, Hongkong, and Korea. Meanwhile, i'm actively contacting sps from Japan and North America.

Due to the internet unstability, time consuming communication etc., I wasn't able to coordinate  all sps to seal with the same speed, hence the decentrlization goal wasn't reached in the first round. It will have changes soon once more sps onboarded in the next few rounds. 

If my answer could address your concerns, please help me move it forward. 

Thank you.

**Comment by Casey-PG** [comment]
> @Casey-PG @BobbyChoii @OlivierMolenkamp REPORTED.
> 
> Please add them to "potential fraudulent" notaries. This application has already been done, this applicant is a completely new account, due diligence is completely lacking.
> 
> Removing the ability of these notaries to sign applications like this is our #1 priority.
> 
> @raghavrmadya @galen-mcandrew @dkkapur @Sunnyiscoming - for your visibility.

The data authenticity and allocation plan meet our DD requirements. @Cindy3y also explained to us the difference in SP efficiency makes it impossible to store cross multi-regions in the first few rounds, which we found to be a common situation in many applications. We believe this application fits the LDN criteria for now and we will be following future allocations. 

@raghavrmadya Is it mandatory to leave a comment every time I sign?

**Comment by Casey-PG** [comment]
Sorry for the late reply, our team just got back from FIL-HK.

**Comment by Casey-PG** [comment]
Good summary report and ongoing communication from the applicant. There're lots of inputs from many notaries and reasonable responses from the applicant. I'm willing to give my sign and help to onboard this application.

**Comment by Casey-PG** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebzailbalzxgpqlbpfmj3ci4dtehmo53msyywwj7yof7yzcck2c22 
#### Address 
> f1tlrfqgjq2k6hhdf54zqkdukttvxejqjeapeymoy
#### Datacap Allocated
> 1.00PiB
#### Signer Address
> f1d4yb3wags3mtddzesxoo63jv7dmlec3bq4yteni
#### Id
> 1ee58eba-d94d-470d-92e9-b89dea9766a8
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebzailbalzxgpqlbpfmj3ci4dtehmo53msyywwj7yof7yzcck2c22

**Comment by Aifabot-Cloud** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec3s4dhqo377oz4kptwrjw3oylwm5os53arugukuyb77vdlmuz3uw 
#### Address 
> f1tlrfqgjq2k6hhdf54zqkdukttvxejqjeapeymoy
#### Datacap Allocated
> 2.00PiB
#### Signer Address
> f174fg3bqbln3zjnkxtyf6s54txqkr7yqkj6cig7y
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec3s4dhqo377oz4kptwrjw3oylwm5os53arugukuyb77vdlmuz3uw

**Comment by cryptowhizzard** [comment]
Hi,

None of the data is retrievable here @Aifabot-Cloud . This is against FIL+ rules and guidelines. Distribution is also not OK.
Why did you sign on this?

@Cindy3y why don't you work with SP's who support retrieval and follow the rules? How do you plan to fix this?

<img width="1110" alt="Scherm­afbeelding 2023-05-06 om 19 24 07" src="https://user-images.githubusercontent.com/36404435/236638430-c5c3f6b1-2de2-481b-9aa4-130bd0d17c21.png">

**Comment by Meibuy** [comment]
checker:manualTrigger

**Comment by Meibuy** [comment]
@Cindy3y You need to improve this indicator of "Deal Data Replication" according to the rules of the community.

**Comment by cryptowhizzard** [comment]
@Meibuy 

and make the data retrievable according to the rules of fil+

**Comment by BobbyChoii** [comment]
Retrieval works fine according to my test. I believe this indicator will get better dynamically including Deal Data Replication.

**Comment by BobbyChoii** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedblyr6wrm6dwulrp3qosmtihl67xojoybelhmgz7jrjdquckidcq 
#### Address 
> f1tlrfqgjq2k6hhdf54zqkdukttvxejqjeapeymoy
#### Datacap Allocated
> 2.00PiB
#### Signer Address
> f1irqs2gmctiv3jcdfwuch7oxvf4ixh3k4b2wc24i
#### Id
> 56e9701c-8a0b-405f-9eb3-ccd9c748cb33
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedblyr6wrm6dwulrp3qosmtihl67xojoybelhmgz7jrjdquckidcq

**Comment by Cindy3y** [comment]
Yes, I want to keep this application open.

**Comment by Cindy3y** [comment]
Hi Please reopen my issue. Thank you

**Comment by herrehesse** [comment]
checker:manualTrigger

**Comment by cryptowhizzard** [comment]
Hi @Cindy3y 

It seems that most of your Sp's don't have retrieval enabled. Secondly they are involved in applications who did not follow the FIL+ rules regarding CID sharing.

Any reason for this?

![Scherm­afbeelding 2023-07-31 om 13 52 39](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/36404435/fb55cf47-0ba9-4127-95c7-65aa47dd33c2)

**Comment by herrehesse** [comment]
@Filplus-govteam @Kevin-FF-USA @raghavrmadya 

Application is abusive, same set of signed notaries, closed and growing exponentially. Looks like the abusers are just sealing their old datacap for the foreseeable future. Can we please remove/hold the DC from closed applications asap?

**Comment by Filplus-govteam** [comment]
Hello @Cindy3y per the new guidelines https://github.com/filecoin-project/notary-governance/issues/922 for Open Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

This information will be reviewed by Fil+ Governance team to confirm validity toward the Fil+ guideline of a distributed storage plan and SPs posted in the comments here. Let us know if you have any questions.
