### ISSUE TITLE
[DataCap Application] <Baoding AISI dance Service Center> - <Baoding AISI dance Service Center>

### ISSUE THREAD

**Issue by fm806** [filecoin-project/filecoin-plus-large-datasets#1863]
### Data Owner Name

Baoding AISI dance Service Center

### Data Owner Country/Region

China

### Data Owner Industry

Education & Training

### Website

http://www.aisidance.com/

### Social Media

```text
http://www.aisidance.com/
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

500TiB

### On-chain address for first allocation

f1i7smtddbhgr5cyh3447bd3wijmalzy253mkucti

### Data Type of Application

Public, Open Commercial/Enterprise

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Founded in 2016, Baoding Aisi Dance is a comprehensive dance culture company that integrates street dance, jazz dance, Chinese dance, oriental dance, Latin dance, and ballet as a professional dance training institution. Just to welcome everyone who loves dancing! The essence of curriculum is to stimulate talents, while the essence of education is to illuminate people. We always adhere to the service philosophy of "self-confidence is the starting point, happiness is the key factor, and love is the core", and provide better service to repay our customers.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
child
Breaking, popping, party dance, urban, hiphop, Jazz dance, classical dance, ballet, Chinese dance, modern dance

adult
Jazz dance, Urban choreography, Waacking swing dance, classical dance, belly dance, ballet, Latin dance, slimming class
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### How do you plan to prepare the dataset

singularity

### Please share a sample of the data

```text
http://www.aisidance.com/article.asp?lanmu_id=15
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Monthly

### For how long do you plan to keep this dataset stored on Filecoin

More than 3 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, South America

### How will you be distributing your data to storage providers

Cloud storage (i.e. S3), HTTP or FTP server, Shipping hard drives

### How do you plan to choose storage providers

Slack, Big data exchange, Partners

### If you already have a list of storage providers to work with, fill out their names and provider IDs below

```text
f01923786
f01877184
f01836766
f01938674
f01859603
```

### How do you plan to make deals to your storage providers

Boost client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
Can you provide more data source or dancing videos to prove that you have 5 PB data already?

**Comment by fm806** [comment]
![image](https://user-images.githubusercontent.com/129386118/229865576-d911432b-4901-4f9b-a38e-f3560afb17b1.png)

**Comment by Sunnyiscoming** [comment]
I need some data samples to check. You can upload these data to online cloud storage tools, like google.

**Comment by fm806** [comment]
@Sunnyiscoming 
Due to network restrictions, only a small portion was uploaded. LINK：https://pan.baidu.com/s/1wfxi-W6pPhub5ANqbfRo9g Extract code：1863

**Comment by Sunnyiscoming** [comment]
Could you send an email to filplus-app-review@fil.org with your official domain in order to confirm your identity? Email name should includes the issue id #1863.

**Comment by Sunnyiscoming** [comment]
Any update here?

**Comment by fm806** [comment]
Just a moment, right away

**Comment by fm806** [comment]
![image](https://user-images.githubusercontent.com/129386118/230768119-1d2f4d09-72fd-4c30-b84d-c5d1fa237141.png)

**Comment by cryptowhizzard** [comment]
Dear @fm806 ,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Looking at your application i have some questions:
As you are brand new on Github and have no history of past applications. Can you give me an introduction who you are and an introduction about your company?

You stated that you are a Data preparer. What hardware do you have over there to prepare this dataset? What is your internet connection speed? Do you already have the data downloaded on the premises?

It seems to me that applying for 5PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?

Can you show us some visible proof of the size of your data and the storage / packing hardware you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230337462961356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!

**Comment by Sunnyiscoming** [comment]
It will be closed in 3 days if no reply here.
