### ISSUE TITLE
[DataCap Application] Org name Inc.

### ISSUE THREAD

**Issue by tikagan** [filecoin-project/filecoin-plus-large-datasets#1865]
### Data Owner Name
Org name Inc.

### Data Owner Country/Region
Algeria

### Data Owner Industry
Education & Training

### Website
[website.com](website.com)

### Social Media
@tikagan (Twitter)

### Total amount of DataCap being requested
3.25 PiB

### Weekly allocation of DataCap requested
32 TiB

### On-chain address for first allocation
f29384[23

### Data Type of Application
Private Commercial/Enterprise

### Custom multisig
No

### Share a brief history of your project and organization
about org here is some stuff:
ountshsn@snthi
@eosnthip
@_(#NEHTUDSO
@*@)!*&(#{)(#*%{
sn'th,su@sneutimo
SNoenuth@

### Is this project associated with other projects/ecosystem stakeholders?
No

### Describe the data being stored onto Filecoin
Nature of data

### Where was the data currently stored in this dataset sourced from
Azure Cloud

### How do you plan to prepare the dataset
lotus

### Please share a sample of the data
au.,s.rndcta,.

### Confirm that this is a public dataset that can be retrieved by anyone on the Network
Yes

### What is the expected retrieval frequency for this data
Daily

### For how long do you plan to keep this dataset stored on Filecoin
1.5 to 2 years

### In which geographies do you plan on making storage deals
Africa

### How will you be distributing your data to storage providers
Lotus built-in data transfer

### How do you plan to choose SP
Big data exchange

### How do you plan to make deals to your storage providers
Bidbot

### Can you confirm that you will follow the Fil+ guideline
Yes

_Application created via [filplus.storage](https://filplus.storage)_

**Comment by cryptowhizzard** [comment]
Dear,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Looking at your application i have some questions:
As you are brand new on Github and have no history of past applications. Can you give me an introduction who you are and an introduction about your company?

You stated that you are a Data preparer. What hardware do you have over there to prepare this dataset? What is your internet connection speed? Do you already have the data downloaded on the premises?

It seems to me that applying for 3PB+ of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?

Can you show us some visible proof of the size of your data and the storage / packing hardware you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230337462961356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!

**Comment by data-programs** [comment]
<img width="32" alt="KYC" Verified src="https://stable.filplus.storage/images/filplus-kyc-verified-badge.png"/>

This user’s identity has been verified through [filplus.storage](https://filplus.storage)
