### ISSUE TITLE
[DataCap Application] Encyclopedia of DNA Elements (ENCODE) <1/2>

### ISSUE THREAD

**Issue by Ottow8** [filecoin-project/filecoin-plus-large-datasets#1866]
### Data Owner Name

ENCODE Data Coordinating Center

### Data Owner Country/Region

United States

### Data Owner Industry

Life Science / Healthcare

### Website

https://www.encodeproject.org/

### Social Media

```text
https://twitter.com/EncodeDCC
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

1PiB

### On-chain address for first allocation

f1c6tart43ygvjzemmsal4pmxpzl7ik2mnydn5epa

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
I'm a DP. The organization: The ENCODE Consortium not only produces high-quality data, but also analyzes the data in an integrative fashion. The ENCODE Encyclopedia organizes the most salient analysis products into annotations and provides tools to search and visualize them. The goal of ENCODE is to build a comprehensive parts list of functional elements in the human genome, including elements that act at the protein and RNA levels, and regulatory elements that control cells and circumstances in which a gene is active.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
Regulatory elements are typically investigated through DNA hypersensitivity assays, assays of DNA methylation, and immunoprecipitation (IP) of proteins that interact with DNA and RNA, i.e., modified histones, transcription factors, chromatin regulators, and RNA-binding proteins, followed by sequencing.
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### How do you plan to prepare the dataset

IPFS, lotus, singularity

### Please share a sample of the data

```text
https://registry.opendata.aws/encode-project/
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Sporadic

### For how long do you plan to keep this dataset stored on Filecoin

2 to 3 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, South America, Europe

### How will you be distributing your data to storage providers

Cloud storage (i.e. S3), HTTP or FTP server, IPFS, Shipping hard drives

### How do you plan to choose storage providers

Slack, Filmine, Big data exchange, Partners

### How do you plan to make deals to your storage providers

Boost client, Lotus client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
Can you introduce your organizaion? Please share more detailed information about sps you will cooperate with.

**Comment by Ottow8** [comment]
@Sunnyiscoming Thanks for your asking. I'm a DP and I've mentioned it in my application. Our SP list hasn't confirmed yet, but I'm contacting some reliable SP for cooperating.

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 5PiB

**Expected weekly DataCap usage rate**
> 1PiB

**Client address**
>f1c6tart43ygvjzemmsal4pmxpzl7ik2mnydn5epa

**Comment by Casey-PG** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebb3orydwupcinkbm7wjm72mgwxr5lar6htofwxblykxob76p5raw 
#### Address 
> f1c6tart43ygvjzemmsal4pmxpzl7ik2mnydn5epa
#### Datacap Allocated
> 256.00TiB
#### Signer Address
> f1d4yb3wags3mtddzesxoo63jv7dmlec3bq4yteni
#### Id
> 6c0f16f0-564f-4a93-b5b9-093b028e1ef3
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebb3orydwupcinkbm7wjm72mgwxr5lar6htofwxblykxob76p5raw

**Comment by BobbyChoii** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaqc3fkt6uy72gwa4rrtuooifduspw7jaiipf3teudmocitudmzxe 
#### Address 
> f1c6tart43ygvjzemmsal4pmxpzl7ik2mnydn5epa
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f1irqs2gmctiv3jcdfwuch7oxvf4ixh3k4b2wc24i
#### Id
> 6680731c-a3a6-48e4-9b65-a38aaafbb69f
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaqc3fkt6uy72gwa4rrtuooifduspw7jaiipf3teudmocitudmzxe

**Comment by TakiChain** [comment]
Thank you for integrating more trustworthy data into the network and please continue to follow fileplus' guidelines.

**Comment by TakiChain** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebuudkap6o6nwi5z747pxobhz5vxoqbh4nkkmx7cuhf4zxffzijig 
#### Address 
> f1c6tart43ygvjzemmsal4pmxpzl7ik2mnydn5epa
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f15impf3j2zcaex4lhyxndxswuuhv24vzstuqtxsi
#### Id
> 6680731c-a3a6-48e4-9b65-a38aaafbb69f
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebuudkap6o6nwi5z747pxobhz5vxoqbh4nkkmx7cuhf4zxffzijig

**Comment by Meibuy** [comment]
We did due diligence on this application previously. So far the report looks good,  we'll keep tracking the datacap allocation flow.

**Comment by Meibuy** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedxbletiossu2jff2j6asb4auofkvruzj2aoldjwp4ovffbuzu7xa 
#### Address 
> f1c6tart43ygvjzemmsal4pmxpzl7ik2mnydn5epa
#### Datacap Allocated
> 1.00PiB
#### Signer Address
> f1bwugfihrmn3iyunzyxst5nttql3dge4khwmurtq
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedxbletiossu2jff2j6asb4auofkvruzj2aoldjwp4ovffbuzu7xa

**Comment by AthSmith** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaismh4ek4drikej5jbgugboivtqvbk7mci6qtdo2bvqzl5pe6gca 
#### Address 
> f1c6tart43ygvjzemmsal4pmxpzl7ik2mnydn5epa
#### Datacap Allocated
> 1.00PiB
#### Signer Address
> f1vxbqrf7rfum3n6m5u6eb4re6xj7amvsaqnzu64y
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaismh4ek4drikej5jbgugboivtqvbk7mci6qtdo2bvqzl5pe6gca

**Comment by jomozz** [comment]
checker:manualTrigger

**Comment by TakiChain** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceag5qvsvqzkmra56dysqw5dlah7ipv7lotz4vnvnhh52gbpxd4c5a 
#### Address 
> f1c6tart43ygvjzemmsal4pmxpzl7ik2mnydn5epa
#### Datacap Allocated
> 2.00PiB
#### Signer Address
> f15impf3j2zcaex4lhyxndxswuuhv24vzstuqtxsi
#### Id
> db299ba0-2580-4ae9-a290-bc7eb7b23402
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceag5qvsvqzkmra56dysqw5dlah7ipv7lotz4vnvnhh52gbpxd4c5a

**Comment by Aifabot-Cloud** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebkjpu2tjmg5pyvhhkkekrrhhcaudyxql2vfpyqx4zu5augnkuljm 
#### Address 
> f1c6tart43ygvjzemmsal4pmxpzl7ik2mnydn5epa
#### Datacap Allocated
> 2.00PiB
#### Signer Address
> f174fg3bqbln3zjnkxtyf6s54txqkr7yqkj6cig7y
#### Id
> db299ba0-2580-4ae9-a290-bc7eb7b23402
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebkjpu2tjmg5pyvhhkkekrrhhcaudyxql2vfpyqx4zu5augnkuljm

**Comment by Ottow8** [comment]
Please keep it open.

**Comment by kevzak** [comment]
checker:manualTrigger

**Comment by BobbyChoii** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceauiuzff24fe6wbv7p5q5t7rag7zefdh7ndjziwcqbuhlcahyrdxa 
#### Address 
> f1c6tart43ygvjzemmsal4pmxpzl7ik2mnydn5epa
#### Datacap Allocated
> 1.25PiB
#### Signer Address
> f1irqs2gmctiv3jcdfwuch7oxvf4ixh3k4b2wc24i
#### Id
> 3370680f-b7f5-4fe4-93ff-5ec7c7fbbdca
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceauiuzff24fe6wbv7p5q5t7rag7zefdh7ndjziwcqbuhlcahyrdxa

**Comment by Casey-PG** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebttoj64ojlfavuvviuirlixb4r5xs56lzmgpnpdi7exfx4dvaec6 
#### Address 
> f1c6tart43ygvjzemmsal4pmxpzl7ik2mnydn5epa
#### Datacap Allocated
> 1.25PiB
#### Signer Address
> f1d4yb3wags3mtddzesxoo63jv7dmlec3bq4yteni
#### Id
> 3370680f-b7f5-4fe4-93ff-5ec7c7fbbdca
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebttoj64ojlfavuvviuirlixb4r5xs56lzmgpnpdi7exfx4dvaec6
