### ISSUE TITLE
[DataCap Application] Encyclopedia of DNA Elements (ENCODE) <2/2>

### ISSUE THREAD

**Issue by Ottow8** [filecoin-project/filecoin-plus-large-datasets#1867]
### Data Owner Name

ENCODE Data Coordinating Center

### Data Owner Country/Region

United States

### Data Owner Industry

Life Science / Healthcare

### Website

https://www.encodeproject.org/

### Social Media

```text
https://twitter.com/EncodeDCC
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

1PiB

### On-chain address for first allocation

f1ms3a7qqubyrovt34jjwhjrh3qvyhlstlxibh3xy

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
I'm a DP. The organization: The ENCODE Consortium not only produces high-quality data, but also analyzes the data in an integrative fashion. The ENCODE Encyclopedia organizes the most salient analysis products into annotations and provides tools to search and visualize them. The goal of ENCODE is to build a comprehensive parts list of functional elements in the human genome, including elements that act at the protein and RNA levels, and regulatory elements that control cells and circumstances in which a gene is active.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
Regulatory elements are typically investigated through DNA hypersensitivity assays, assays of DNA methylation, and immunoprecipitation (IP) of proteins that interact with DNA and RNA, i.e., modified histones, transcription factors, chromatin regulators, and RNA-binding proteins, followed by sequencing.
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### How do you plan to prepare the dataset

IPFS, lotus, singularity

### Please share a sample of the data

```text
https://registry.opendata.aws/encode-project/
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Sporadic

### For how long do you plan to keep this dataset stored on Filecoin

2 to 3 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, South America, Europe

### How will you be distributing your data to storage providers

Cloud storage (i.e. S3), HTTP or FTP server, IPFS, Shipping hard drives

### How do you plan to choose storage providers

Slack, Filmine, Big data exchange, Partners

### How do you plan to make deals to your storage providers

Boost client, Lotus client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
See questions in https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1866.

**Comment by Casey-PG** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedb2dr4jny7lou2izl56iqopsc5hcthmqkzzekeibpnetlml2ewj4 
#### Address 
> f1ms3a7qqubyrovt34jjwhjrh3qvyhlstlxibh3xy
#### Datacap Allocated
> 256.00TiB
#### Signer Address
> f1d4yb3wags3mtddzesxoo63jv7dmlec3bq4yteni
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedb2dr4jny7lou2izl56iqopsc5hcthmqkzzekeibpnetlml2ewj4

**Comment by Meibuy** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb4mymjjasjnifi7usswhrsovxdto4gn2yx5agfongkonuil5ftrc 
#### Address 
> f1ms3a7qqubyrovt34jjwhjrh3qvyhlstlxibh3xy
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f1bwugfihrmn3iyunzyxst5nttql3dge4khwmurtq
#### Id
> ecf272bc-448c-4ac4-9a7f-ab070e12cb59
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb4mymjjasjnifi7usswhrsovxdto4gn2yx5agfongkonuil5ftrc

**Comment by Protocan** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacede2r566brpbhg5zlf66bt3wgnhin7n3v5kzfm4mi4uialuvt2pnk 
#### Address 
> f1ms3a7qqubyrovt34jjwhjrh3qvyhlstlxibh3xy
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f1vxbqrf7rfum3n6m5u6eb4re6xj7amvsaqnzu64y
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacede2r566brpbhg5zlf66bt3wgnhin7n3v5kzfm4mi4uialuvt2pnk

**Comment by BobbyChoii** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebnvencahqox6ldkixeg6jwb5xjyjlbgb7cjjclulpzwbcqhotlh4 
#### Address 
> f1ms3a7qqubyrovt34jjwhjrh3qvyhlstlxibh3xy
#### Datacap Allocated
> 1.00PiB
#### Signer Address
> f1irqs2gmctiv3jcdfwuch7oxvf4ixh3k4b2wc24i
#### Id
> 3f1fbeb6-b68d-4a9e-bb93-a5ec3c7fab4d
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebnvencahqox6ldkixeg6jwb5xjyjlbgb7cjjclulpzwbcqhotlh4

**Comment by TakiChain** [comment]
Thank you for integrating more trustworthy data into the network and please continue to follow filplus' guidelines.

**Comment by TakiChain** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebjyvs6gpirglugr73cv4fyf4ypgcgg3rsgahnocqwet527oj2zkq 
#### Address 
> f1ms3a7qqubyrovt34jjwhjrh3qvyhlstlxibh3xy
#### Datacap Allocated
> 1.00PiB
#### Signer Address
> f15impf3j2zcaex4lhyxndxswuuhv24vzstuqtxsi
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebjyvs6gpirglugr73cv4fyf4ypgcgg3rsgahnocqwet527oj2zkq

**Comment by Ottow8** [comment]
OK. I got it!

**Comment by Casey-PG** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedhzax6tki2zu4du3adkgvzeyhf7c4ncjqnk6mlc2gdtozc4e7fvy 
#### Address 
> f1ms3a7qqubyrovt34jjwhjrh3qvyhlstlxibh3xy
#### Datacap Allocated
> 2.00PiB
#### Signer Address
> f1d4yb3wags3mtddzesxoo63jv7dmlec3bq4yteni
#### Id
> 03629dcc-9176-48ed-8225-e1bc7053e1fb
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedhzax6tki2zu4du3adkgvzeyhf7c4ncjqnk6mlc2gdtozc4e7fvy

**Comment by Aifabot-Cloud** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb5ffomfzvgxp4b7e5v5t5sok2pxdmye453gbfhcivqgqzf4zhk3k 
#### Address 
> f1ms3a7qqubyrovt34jjwhjrh3qvyhlstlxibh3xy
#### Datacap Allocated
> 2.00PiB
#### Signer Address
> f174fg3bqbln3zjnkxtyf6s54txqkr7yqkj6cig7y
#### Id
> 03629dcc-9176-48ed-8225-e1bc7053e1fb
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb5ffomfzvgxp4b7e5v5t5sok2pxdmye453gbfhcivqgqzf4zhk3k

**Comment by Joss-Hua** [comment]
checker:manualTrigger

**Comment by Ottow8** [comment]
Please keep my application open.

**Comment by BobbyChoii** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceac3merqi6vs2h4u43j7qkecauo3xuyhlcd7yqslqcttqv3xacegm 
#### Address 
> f1ms3a7qqubyrovt34jjwhjrh3qvyhlstlxibh3xy
#### Datacap Allocated
> 1.25PiB
#### Signer Address
> f1irqs2gmctiv3jcdfwuch7oxvf4ixh3k4b2wc24i
#### Id
> 83bb4b6b-36ef-46dc-9994-69bf1b742da7
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceac3merqi6vs2h4u43j7qkecauo3xuyhlcd7yqslqcttqv3xacegm

**Comment by Aifabot-Cloud** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceddztw3mpxoj3fhxlz3lcnv3776kfgv7tcat66lm77eib4ekuyku4 
#### Address 
> f1ms3a7qqubyrovt34jjwhjrh3qvyhlstlxibh3xy
#### Datacap Allocated
> 1.25PiB
#### Signer Address
> f174fg3bqbln3zjnkxtyf6s54txqkr7yqkj6cig7y
#### Id
> 83bb4b6b-36ef-46dc-9994-69bf1b742da7
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceddztw3mpxoj3fhxlz3lcnv3776kfgv7tcat66lm77eib4ekuyku4

**Comment by Ottow8** [comment]
Got it. I'll continue use it.

**Comment by cryptowhizzard** [comment]
checker:manualTrigger

**Comment by cryptowhizzard** [comment]
> Got it. I'll continue use it.

Will you first try to fix your retrieval please according to the FIL+ rules?
