### ISSUE TITLE
[DataCap Application]Meson.Network 

### ISSUE THREAD

**Issue by Jacintos** [filecoin-project/filecoin-plus-large-datasets#187]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Meson.Network 
- Website / Social Media:https://meson.network/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):300TiB
- On-chain address for first allocation:f1tgii4xgcp6um4n2w7eqaw6bwvnvyii2u7cjgzka

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
It is a cost effective and reliable solution to the user experience and access problems brought by an exponential explosion of content delivery and distribution. It is a new web infrastructure that is made up of accelerator nodes that are distributed geographically. These service nodes will store your business content according to smart caching strategies. When a user initiates a request for your business services, the request will be routed to the service node closest to the user so responses can be as quickly as possible, and delays can be minimized, effectively improving user experience and service usability.
```

What is the primary source of funding for this project?
```
Shareholders and our partners.
```

What other projects/ecosystem stakeholders is this project associated with?
```
None.
```

## Use-case details

Describe the data being stored onto Filecoin
```
Users who want to store their data about games, videos, nft, files and so on can store it on our website. We provide storage with them. So we need more storage to satisfy customers' needs. We'd upload these datasets.
```

Where was the data in this dataset sourced from?
```
Our business service customers include all small, medium and large size internet companies.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://user-images.githubusercontent.com/93566395/148044690-bbc6e961-fd80-4ee3-9e45-4bab285dab64.mp4
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Confirm.
```

What is the expected retrieval frequency for this data?
```
Not too frequent. We'd search when necessary.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
If it is convenient to use, we will use it for a long time.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
North America and Asia.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Mainly online transaction. We accept offline transaction.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We will choose according to the storage strength of the miners. We need miners who can cooperate for a long time.
```

How will you be distributing deals across storage providers?
```
More deals will be allocated to providers who have high reputation.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Sure. We will begin immediately.
```

**Comment by ozhtdong** [comment]
Great project.!  Are you intend to release your project on filecoin, if FVM is ready this year ?

**Comment by ozhtdong** [comment]
Happy to support. Hope you have a nice experience with filecoin.

**Comment by Jacintos** [comment]
@ozhtdong Thank you for your support. Hope my issue have new progress!

**Comment by IPFSUnion** [comment]
Happy to support

**Comment by UnionLabs2020** [comment]
It would be better if you could  share more evidence about your cooperation with Meson. @Jacintos

**Comment by Jacintos** [comment]
![rgdf122945](https://user-images.githubusercontent.com/93566395/156562815-eab5367a-7f21-40b0-8d6c-3634913ab46a.png)
@UnionLabs2020 @ozhtdong @galen-mcandrew @dkkapur @Kevin-FF-USA Hey, can you help approve it?

**Comment by dkkapur** [comment]
@Jacintos can you confirm this one is still relevant? Can notaries or the Filecoin Foundation (filplus@fil.org) be added to your email thread to help with verification of your relationship with the client? 

Have SPs already been identified for this client to store data with?

**Comment by Jacintos** [comment]
Yes, we can add notaries or filplus@fil.org to the email with my client.
Can you help us for this verification? @ozhtdong @Fenbushi-Filecoin @swatchliu @UnionLabs2020 @MRJAVAZHAO @neogeweb3 @steven004 @wjywood

**Comment by dkkapur** [comment]
@Jacintos maybe worth sending the email to filplus@fil.org first, we can also share a screenshot here for other notaries?

**Comment by galen-mcandrew** [comment]
We are still waiting for official communication from the enterprise domain address. Any update here?

**Comment by Jacintos** [comment]
@dkkapur @galen-mcandrew I've resent an email to filplus@fil.org. It seemed that you missed last email which cc you.

**Comment by Jacintos** [comment]
Any update?

**Comment by Jacintos** [comment]
@dkkapur @galen-mcandrew

**Comment by galen-mcandrew** [comment]
## Multisig Notary requested
#### Total DataCap requested 
> 5PiB
#### Expected weekly DataCap usage rate 
> 300TiB

**Comment by KodaRobotDog** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebko5iozheh4nxyh35n5b2pee6w4t6ya6elpxosy55sxkgjsiu3di 
#### Address 
> f1tgii4xgcp6um4n2w7eqaw6bwvnvyii2u7cjgzka
#### Datacap Allocated
> 150.00TiB
#### Signer Address
> f1jyalts5uhtmp5sbbssse23toshvsqbbtjgukm5a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebko5iozheh4nxyh35n5b2pee6w4t6ya6elpxosy55sxkgjsiu3di

**Comment by swatchliu** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced7dtatv5cksosyvwoq352ono6t6ohd4ujjcjxvqe46lxecthdrri 
#### Address 
> f1tgii4xgcp6um4n2w7eqaw6bwvnvyii2u7cjgzka
#### Datacap Allocated
> 150.00TiB
#### Signer Address
> f1yh6q3nmsg7i2sys7f7dexcuajgoweudcqj2chfi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced7dtatv5cksosyvwoq352ono6t6ohd4ujjcjxvqe46lxecthdrri

**Comment by swatchliu** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebuqkxfq5a6nib5rmknb7zojp4zawof47pa4aciev2b2ewoh6pqzk 
#### Address 
> f1tgii4xgcp6um4n2w7eqaw6bwvnvyii2u7cjgzka
#### Datacap Allocated
> 150.00TiB
#### Signer Address
> f1yh6q3nmsg7i2sys7f7dexcuajgoweudcqj2chfi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebuqkxfq5a6nib5rmknb7zojp4zawof47pa4aciev2b2ewoh6pqzk

**Comment by XnMatrixSV** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceagsbn2vg3dwj7ubgf7uirqrqeiqcrhoakelmjmqhss4nu4wocuno 
#### Address 
> f1tgii4xgcp6um4n2w7eqaw6bwvnvyii2u7cjgzka
#### Datacap Allocated
> 300.00TiB
#### Signer Address
> f1yuz2twsllparyfqwslfiuxrc5wj4mfiflvnsw6a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceagsbn2vg3dwj7ubgf7uirqrqeiqcrhoakelmjmqhss4nu4wocuno

**Comment by TimWilliams00** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedra7voghsvex7th2a7pnzww5jusjqnhu6cddwy4s24hbj6waggim 
#### Address 
> f1tgii4xgcp6um4n2w7eqaw6bwvnvyii2u7cjgzka
#### Datacap Allocated
> 300.00TiB
#### Signer Address
> f1fkxkfxgopjf3ufnfg5i3m6qlwf73kp4w5zz7nnq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedra7voghsvex7th2a7pnzww5jusjqnhu6cddwy4s24hbj6waggim

**Comment by 1475Notary** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedyvuyonwacmptlg3ebnjbcv2k6qbo4s7sjbyrsqs75vh2ygnbw76 
#### Address 
> f1tgii4xgcp6um4n2w7eqaw6bwvnvyii2u7cjgzka
#### Datacap Allocated
> 600.00TiB
#### Signer Address
> f1ofq4mngy7ggcp755pfquq2gphjjnlydolf6awtq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedyvuyonwacmptlg3ebnjbcv2k6qbo4s7sjbyrsqs75vh2ygnbw76

**Comment by Fenbushi-Filecoin** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceclyc6arkeem254g2isnvzddkgpnjluhufrockbi2zlicjnljebog 
#### Address 
> f1tgii4xgcp6um4n2w7eqaw6bwvnvyii2u7cjgzka
#### Datacap Allocated
> 600.00TiB
#### Signer Address
> f1yqydpmqb5en262jpottko2kd65msajax7fi4rmq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceclyc6arkeem254g2isnvzddkgpnjluhufrockbi2zlicjnljebog

**Comment by MetaWaveInfo** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb6njobl6drqmmtyipilbseeatxkumcvm7wnka24e26qiadf36xvk 
#### Address 
> f1tgii4xgcp6um4n2w7eqaw6bwvnvyii2u7cjgzka
#### Datacap Allocated
> 1.17PiB
#### Signer Address
> f1ktlkcxnmzxcdaoqfsunrg3vocfbmgv4n3mrn74a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb6njobl6drqmmtyipilbseeatxkumcvm7wnka24e26qiadf36xvk

**Comment by galen-mcandrew** [comment]
This was approved, looks like message was not logged by bot.

**Comment by galen-mcandrew** [comment]
Approved by: Eric Liu - (Shanghai ByteBase Information Technology Co.) @swatchliu 

## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
> bafy2bzacea5qqeuthwiupkdjhcn3rq4nghyj4nfz7rut5orsfp6rxrm5jsxl4 
#### Address 
> f1tgii4xgcp6um4n2w7eqaw6bwvnvyii2u7cjgzka
#### Datacap Allocated
> 1.17PiB
#### Signer Address
> f1yh6q3nmsg7i2sys7f7dexcuajgoweudcqj2chfi
#### You can check the status of the message here: 
https://filfox.info/en/message/bafy2bzacea5qqeuthwiupkdjhcn3rq4nghyj4nfz7rut5orsfp6rxrm5jsxl4

**Comment by fabriziogianni7** [comment]
Approved by: Eric Liu - (Shanghai ByteBase Information Technology Co.) @swatchliu

**Comment by psh0691** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecvokb4jnuzaoaatkkgz3ayk7deuj6pu7ieaabeoibgfa6fy7k5mw 
#### Address 
> f1tgii4xgcp6um4n2w7eqaw6bwvnvyii2u7cjgzka
#### Datacap Allocated
> 2.34PiB
#### Signer Address
> f1qdko4jg25vo35qmyvcrw4ak4fmuu3f5rif2kc7i
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecvokb4jnuzaoaatkkgz3ayk7deuj6pu7ieaabeoibgfa6fy7k5mw

**Comment by UnionLabs2020** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacededpftnx2bbolhljmsuqfaqbo4wj2klsqn45e2doosu3msree7jq 
#### Address 
> f1tgii4xgcp6um4n2w7eqaw6bwvnvyii2u7cjgzka
#### Datacap Allocated
> 2.34PiB
#### Signer Address
> f17xdri3wunqgld7dm23e4f3eqsntjakwc47xjo6i
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacededpftnx2bbolhljmsuqfaqbo4wj2klsqn45e2doosu3msree7jq

**Comment by MetaWaveInfo** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceao7p5chgyv656sl4zpoxww65mxxmdaduzmnrn6dociy45dii5owu 
#### Address 
> f1tgii4xgcp6um4n2w7eqaw6bwvnvyii2u7cjgzka
#### Datacap Allocated
> 2.34PiB
#### Signer Address
> f1ktlkcxnmzxcdaoqfsunrg3vocfbmgv4n3mrn74a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceao7p5chgyv656sl4zpoxww65mxxmdaduzmnrn6dociy45dii5owu

**Comment by swatchliu** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecsulidwzyqyyqhtwztvemb5dwwbxlqxcxuotxn5rdwar6frn7qae 
#### Address 
> f1tgii4xgcp6um4n2w7eqaw6bwvnvyii2u7cjgzka
#### Datacap Allocated
> 2.34PiB
#### Signer Address
> f1yh6q3nmsg7i2sys7f7dexcuajgoweudcqj2chfi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecsulidwzyqyyqhtwztvemb5dwwbxlqxcxuotxn5rdwar6frn7qae

**Comment by BigD-Exchange** [comment]
@Jacintos Hi! Great to see you have gotten approval for DataCap. Your project looks very interesting. If you are looking for storage providers with high reputation to store these data, please visit #bigdata-exchange on Filecoin Slack or reply here.

**Comment by Akkeeeeee** [comment]
Hi, @Jacintos  Would you like to share your rootCID with us?

**Comment by bitruss** [comment]
Hello, all. This is a fake Filecoin Plus, If you have any questions about Meson plz contact martin@meson.network. Thanks
@dkkapur @galen-mcandrew

**Comment by dkkapur** [comment]
@Jacintos - what happened here? Can you help identify what the gap is and stop onboarding any additional data while we can align on the outcomes from the dispute flagged above. 

@bitruss - we have an email thread from @Jacintos and a representative from your team that links them (with a @meson.network) email. Can you help us follow up (sent you an email about this per your last comment).
