### ISSUE TITLE
[DataCap Application] Tech Greedy - Earth System Grid Federation

### ISSUE THREAD

**Issue by xinaxu** [filecoin-project/filecoin-plus-large-datasets#1878]
### Data Owner Name

Earth System Grid Federation

### Data Owner Country/Region

United States

### Data Owner Industry

Environment

### Website

https://registry.opendata.aws/cmip6/

### Social Media

```text
See website
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

1PiB

### On-chain address for first allocation

f1wpl3otf7g2jewwafhyj3xhzffuxbywbseefjmai

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Project Detail: This dataset is an AWS open dataset that has yet been stored on Filecoin. We were planning to onboard this dataset with Slingshot V3, however, with the delay of the program, we want to start onboarding asap. Meanwhile, we want to reach out to storage providers outside of slingshot silo to expand the distribution variety further.

Organization Detail: Tech Greedy has been engaged in Filecoin ecosystem building including building data preparation and deal-making tool, participating in multiple rounds of slingshot and having mining operations.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
Netcdf formatted data managed by the Earth System Grid Federation
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### How do you plan to prepare the dataset

singularity

### Please share a sample of the data

```
https://esgf-world.s3.amazonaws.com/index.html
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Monthly

### For how long do you plan to keep this dataset stored on Filecoin

1.5 to 2 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, Europe

### How will you be distributing your data to storage providers

HTTP or FTP server

### How do you plan to choose storage providers

Slack, Big data exchange, Partners

### If you already have a list of storage providers to work with, fill out their names and provider IDs below

```
f01761579 - FeiGe IT LLC, Anhui, China
f0750779 - OuRuan IT LLC, Chengdu, China
f01969339 - Acrontech, Atlanta, Georgia, US
f01969323 - Acrontech, Atlanta, Georgia, US
f01969306 - Acrontech, Atlanta, Georgia, US
f01832393 - Tech Greedy, Seattle, Washington, US
f01985775 - Greater Heat, Dallas, Texas, US
f033462 - Greater Heat, Dallas, Texas, US
f01989866 - Weimin, Xi'an, CN
f01907545 - Weimin, Xi'an, CN
```

### How do you plan to make deals to your storage providers

Singularity

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by xinaxu** [comment]
@Sunnyiscoming I've updated the storage provider list I plan to make deal with in the description

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 5PiB

**Expected weekly DataCap usage rate**
> 1PiB

**Client address**
>f1wpl3otf7g2jewwafhyj3xhzffuxbywbseefjmai

**Comment by xinaxu** [comment]
@Sunnyiscoming I have updated the description of the dataset to reflect the latest status. There is some label change. Is it good to proceed or will you need to approve it again?

**Comment by cryptowhizzard** [comment]
Supportive of this request. Looking forward to the first CID report. Data is verified (open) and SP's have a great reputation.

**Comment by cryptowhizzard** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb3txntvp3qjzrshcqmbvz62cr6auylhptgrqhdx2fmpim7a3hvx6 
#### Address 
> f1wpl3otf7g2jewwafhyj3xhzffuxbywbseefjmai
#### Datacap Allocated
> 256.00TiB
#### Signer Address
> f1krmypm4uoxxf3g7okrwtrahlmpcph3y7rbqqgfa
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb3txntvp3qjzrshcqmbvz62cr6auylhptgrqhdx2fmpim7a3hvx6

**Comment by liyunzhi-666** [comment]
According to the previous performance of @xinaxu , I am willing to support the first round and will monitor to see the follow-up development.

**Comment by liyunzhi-666** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecohqlt37eihb6odgttkeafkwflgd2ekfhu3iw6t5adedg3tilt7y 
#### Address 
> f1wpl3otf7g2jewwafhyj3xhzffuxbywbseefjmai
#### Datacap Allocated
> 256.00TiB
#### Signer Address
> f1pszcrsciyixyuxxukkvtazcokexbn54amf7gvoq
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecohqlt37eihb6odgttkeafkwflgd2ekfhu3iw6t5adedg3tilt7y

**Comment by xinaxu** [comment]
reopen
