### ISSUE TITLE
[DataCap Application] PUBLIC DATA-COVID-19 Genome Sequence Dataset [1/2]

### ISSUE THREAD

**Issue by nora310** [filecoin-project/filecoin-plus-large-datasets#1880]
### Data Owner Name

National Library of Medicine (NLM)

### Data Owner Country/Region

United States

### Data Owner Industry

Life Science / Healthcare

### Website

https://www.ncbi.nlm.nih.gov/sra/docs/sra-aws-download/

### Social Media

```text
twitter-https://twitter.com/NIH_OSP
youtube-https://www.youtube.com/@nihofficeofsciencepolicy3005/videos
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

1PiB

### On-chain address for first allocation

f17ijtonxrc5kdi25fxfrfw7uutyjajkzedglwbky

### Data Type of Application

None

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
A centralized sequence repository for all records containing sequence associated with the novel corona virus (SARS-CoV-2) submitted to the National Center for Biotechnology Information (NCBI) Sequence Read Archive (SRA). Included are both the original sequences submitted by the principal investigator as well as SRA-processed sequences that require the SRA Toolkit for analysis. Additionally, submitter provided metadata included in associated BioSample and BioProject records is available alongside NCBI calculated data, such k-mer based taxonomy analysis results, contiguous assemblies (contigs) and associated statistics such as contig length, blast results for the assembled contigs, contig annotation, blast databases of contigs and their annotated peptides, and VCF files generated for each record relative to the SARS-CoV-2 RefSeq record. Finally, metadata is additionally made available in parquet format to facilitate search and filtering using the AWS Athena Service.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
Genomic sequence reads of SARS-CoV-2 and related coronaviridae, organized by NCBI accession. Files in the sra-src folder are in FASTQ, BAM, or CRAM format (original submission); files in the run folder are in .sra format and require the SRA Toolkit; Metadata for sra-pub-sars-cov2 in an Athena-queryable format.
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### How do you plan to prepare the dataset

IPFS, lotus, singularity

### Please share a sample of the data

```text
https://registry.opendata.aws/ncbi-covid-19/
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

1.5 to 2 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, Europe

### How will you be distributing your data to storage providers

IPFS, Shipping hard drives

### How do you plan to choose storage providers

Slack, Big data exchange

### How do you plan to make deals to your storage providers

Lotus client, Singularity

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 5PiB

**Expected weekly DataCap usage rate**
> 1PiB

**Client address**
>f17ijtonxrc5kdi25fxfrfw7uutyjajkzedglwbky

**Comment by OlivierMolenkamp** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacea2p7cumpphmhj45eha2l3gfspgrp4pemhauk43h4krocex66tvoi 
#### Address 
> f17ijtonxrc5kdi25fxfrfw7uutyjajkzedglwbky
#### Datacap Allocated
> 256.00TiB
#### Signer Address
> f1fl5gjqv3xknuhka273jrsrkzqcumrp6idrnvgyi
#### Id
> cc1ef9b4-09d7-4c82-93d8-7d41c30cfc27
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacea2p7cumpphmhj45eha2l3gfspgrp4pemhauk43h4krocex66tvoi

**Comment by cryptowhizzard** [comment]
checker:manualTrigger

**Comment by nora310** [comment]
Yes!

**Comment by nora310** [comment]
Yes please!

**Comment by nora310** [comment]
Yes please!

**Comment by cryptowhizzard** [comment]
checker:manualTrigger

**Comment by nora310** [comment]
Yes please!

**Comment by clriesco** [comment]
Removed stale label and reopened issue :)

**Comment by cryptowhizzard** [comment]
Dear nora310,

As notary I am doing due diligence on your LDN. I could not get retrieval to work. Can you please upload the car file of CID baga6ea4seaqefjrj43buul4lyctq3256p5r6frtbslu5baxbsz2kmy24baxc6ja ?

You can use our upload system at http://send.datasetcreators.com. Please select 7 days for the system to keep the file and post the link you received here so I (and other notaries) can download your content.

**Comment by nora310** [comment]
> Dear nora310,
> 
> As notary I am doing due diligence on your LDN. I could not get retrieval to work. Can you please upload the car file of CID baga6ea4seaqefjrj43buul4lyctq3256p5r6frtbslu5baxbsz2kmy24baxc6ja ?
> 
> You can use our upload system at http://send.datasetcreators.com. Please select 7 days for the system to keep the file and post the link you received here so I (and other notaries) can download your content.

Can not open this link.

**Comment by nora310** [comment]
yes

**Comment by nora310** [comment]
yes

**Comment by nora310** [comment]
yes

**Comment by nora310** [comment]
Hello @Sunnyiscoming , I've finished.

**Comment by Wengeding** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedea2ulzkraoprqpjutyqw7oxmtu4pwivfxirzyt55n62blo7gbuk 
#### Address 
> f17ijtonxrc5kdi25fxfrfw7uutyjajkzedglwbky
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f1txfsjmix4vlzido4dkildrnbw26owtlbslexmpa
#### Id
> 479ddd2f-bc41-4938-9435-1d697e772e8e
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedea2ulzkraoprqpjutyqw7oxmtu4pwivfxirzyt55n62blo7gbuk

**Comment by MRJAVAZHAO** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacealnrxa5kiqrbjjug27jysxs5lh7jku7z5jru7gqiymmoemlokh2m 
#### Address 
> f17ijtonxrc5kdi25fxfrfw7uutyjajkzedglwbky
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f14gme3f52prtyzk6pblogrdd6b6ivp4swc6qmesi
#### Id
> 479ddd2f-bc41-4938-9435-1d697e772e8e
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacealnrxa5kiqrbjjug27jysxs5lh7jku7z5jru7gqiymmoemlokh2m

**Comment by MRJAVAZHAO** [comment]
SP distribution and data retrieval are ok. Please pay attention to Deal Data Replication.
I am willing to support it.

**Comment by TakiChain** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedi6746nzfo5nbdqzxxjd6a3iqtqfhiie7i5yrlwpdjybttbrjskw 
#### Address 
> f17ijtonxrc5kdi25fxfrfw7uutyjajkzedglwbky
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f15impf3j2zcaex4lhyxndxswuuhv24vzstuqtxsi
#### Id
> c43a475d-da2c-4043-ae32-5d32b6827acd
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedi6746nzfo5nbdqzxxjd6a3iqtqfhiie7i5yrlwpdjybttbrjskw

**Comment by Suyanj** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedjzdqjyc7zznrn3nxhsytpkz5aob2ldghrqe2kxi5ortkn4q6kmm 
#### Address 
> f17ijtonxrc5kdi25fxfrfw7uutyjajkzedglwbky
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f1ihv7gz3vn3xqvikpt4rwryecgisl7745lodx3yi
#### Id
> c43a475d-da2c-4043-ae32-5d32b6827acd
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedjzdqjyc7zznrn3nxhsytpkz5aob2ldghrqe2kxi5ortkn4q6kmm

**Comment by herrehesse** [comment]
checker:manualTrigger

**Comment by herrehesse** [comment]
![Screenshot 2023-11-13 at 13 39 13](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/70132857/a6bbf591-7e16-4260-84bb-f5846177f9f8)

FULL VPN & Fake distribution. Close @kevzak.

**Comment by nora310** [comment]
@herrehesse **Show your evidence.**

**Comment by herrehesse** [comment]
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1881

Evidence same as above. @kevzak please close.

![Screenshot 2023-11-14 at 09 20 57](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/70132857/e0a96658-3810-4571-9735-e42f19cc1620)

**Comment by nora310** [comment]
> #1881
> 
> Evidence same as above. @kevzak please close.
> 
> ![Screenshot 2023-11-14 at 09 20 57](https://private-user-images.githubusercontent.com/70132857/282708134-e0a96658-3810-4571-9735-e42f19cc1620.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEwNTYzNDksIm5iZiI6MTcwMTA1NjA0OSwicGF0aCI6Ii83MDEzMjg1Ny8yODI3MDgxMzQtZTBhOTY2NTgtMzgxMC00NTcxLTk3MzUtZTQyZjE5Y2MxNjIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI3VDAzMzQwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU3MjRmMTYxYTcwM2ZmODczOTMzZjY2M2NmMzM2ZTg4ZjE3MmFkZjk0NTU4NDQ4N2I3NDZjZjVkYmI0NWY2YTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HGF2WhXHGhPsE_0wS-eMCqqYhxdouYJbggiwAkrmMIw)

wrong pic. Can not be open.

**Comment by Filplus-govteam** [comment]
SP List provided
f02207907 | Tim |New York City, New York, US | no | tim
f01844118 | Garry | no email here |  New York City, New York, US | no | garry
f01844232 | Lukas individual | Dallas, Texas, US | no | Lukas
f01844043 |  Abel | Ashburn, US | no | Abel
f01843994 | Hans individual | Dulles Town Center, Virginia, US | no | hans

All emails bounce, closing for lack of validation of distributed location. same as #1881 
</body>
</html>
