### ISSUE TITLE
[DataCap Application] Sichuan Dongpeng Nonghai Technology Co. LTD - Smart big data platform

### ISSUE THREAD

**Issue by scdpnh** [filecoin-project/filecoin-plus-large-datasets#1883]
### Data Owner Name

Sichuan Dongpeng Nonghai Technology Co. LTD

### Data Owner Country/Region

China

### Data Owner Industry

Resources, Agriculture & Fisheries

### Website

http://www.scdpnh.com

### Social Media

```text
http://www.scdpnh.com/production/smartfarmingapp/af9a2377-f29e-4184-b026-4cdb2bc82eb4
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

350TiB

### On-chain address for first allocation

f2n3wzhod7y7zyhxryahlwesqvshgbvr4d4jxedva

f1j62joj4uatolg62ckvx67m4sqjmxt25yfsmgsvq

### Data Type of Application

Public, Open Commercial/Enterprise

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Sichuan Dongpeng Nonghai Technology Co., Ltd. is an innovative technology company deeply engaged in the field of high-tech and information technology. In response to the national strategy of smart agriculture and rural revitalization, the company has industry-level and whole-chain solutions for the direction of rural economic construction, agricultural social services and rural industry revitalization. Dongpeng Nonghai Co., Ltd. is committed to play the role of platform in the industry and provide industrial supporting equipment from the perspective of focusing on high-tech research and development and independent innovation. Is a set design, research and development, production, sales as one of the industrial service technology company.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
bafykbzacearvivx4gbe4jv4sjx4wwhck74ycicfx65s4npigqy7xaofkuge4y
bafykbzacec4tz6qyb7e3gshqyh4ezq7hzsafv26o4xrrlwq46zvmxzjzm4w4g
bafykbzacebpbdb7dsbmppyasibt7atwrima772fua2m6qk3wpqtg6zfi2rzgs
bafykbzacecv3gajexhgklyqwswpaabhwtbgyxo7fuaadllysfx3eyr4mgcmiq
bafykbzacecba7moa5bdtk4zthflelwfbifftqyaje5isytbdpfilmxfhxlngy bafykbzacearzzmcx2zo5ua65s43zj4isitojc3yry2z5th4lbbpkdohiheylq
bafykbzacedgjzbdme2a5zhlyphl3xzdksabvnahtlcszlx6inynwwsggedyho
bafykbzacecse7zlxbmwuvbdapd63vdwhtvhjzprr2xdz2jo6et5gn4bdvghzo
bafykbzacedc7ra2443l4drp2gufbwzfpocv3lprtbgyzarkzvg57unq7555uu
bafykbzacedrrqvq7im6xq5iu3ua75thjqoyajkg2zvrju5u3pfz5uqadzein2
```

### Where was the data currently stored in this dataset sourced from

Other

### If you answered "Other" in the previous question, enter the details here

```text
Ali cloud and My Own Storage Infra
```

### How do you plan to prepare the dataset

lotus

### Please share a sample of the data

```text
链接：https://pan.baidu.com/s/148d4IKyxuTe2bW78O4G7_g?pwd=7mc1 
提取码：7mc1
视频
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Daily

### For how long do you plan to keep this dataset stored on Filecoin

2 to 3 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China

### How will you be distributing your data to storage providers

Cloud storage (i.e. S3), HTTP or FTP server, Shipping hard drives

### How do you plan to choose storage providers

Big data exchange, Partners

### How do you plan to make deals to your storage providers

Boost client, Lotus client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
Please describe the data being stored onto Filecoin.
Please share more detailed information about sps you will cooperate with.

**Comment by scdpnh** [comment]
The data collected by the company for the data acquisition instrument of smart farm include water quality data, meteorological data, soil data, seedling situation monitoring, pest monitoring, etc


What is sps?  Multiple sp?  How many do I need here?  I have a company on my side that does this business, and I'm in contact with them. Can I ask them to give me information?


@Sunnyiscoming

**Comment by Sunnyiscoming** [comment]
Sp is storage provider. The comunity require each application should allocate Datacap received to each sp less than 30%. So you should establish cooperation with more than 3 sps.

**Comment by scdpnh** [comment]
| SP-id | Contact name | Organization name | Region
f081988 | kun peng chen | ZY cloud | China Mobile Tianjin
f0500878 | liming ding | Pilot star | Hong Kong
f023219 | rizhao wang | FK Cloud Storage | Hong Kong
f0509062 | Maupassant | RY Data center star | Frank
f01130100 | wen zhang | High digital technology | Zhangjiakou China Unicom

Do the SP contacts meet community requirements? 

@Sunnyiscoming

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 5PiB

**Expected weekly DataCap usage rate**
> 350TiB

**Client address**
>f2n3wzhod7y7zyhxryahlwesqvshgbvr4d4jxedva

**Comment by Sunnyiscoming** [comment]
@simonkim0515

**Comment by caoyoungyoung** [comment]
Can you show the proof that you already have 5PiB data?

**Comment by cryptowhizzard** [comment]
Dear,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Looking at your application i have some questions:
As you are brand new on Github and have no history of past applications. Can you give me an introduction who you are and an introduction about your company?

You stated that you are a Data preparer. What hardware do you have over there to prepare this dataset? What is your internet connection speed? Do you already have the data downloaded on the premises?

It seems to me that applying for 5PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?

Can you show us some visible proof of the size of your data and the storage / packing hardware you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230337462961356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!

**Comment by simonkim0515** [comment]
## Datacap Request Trigger

#### Total DataCap requested 
> 5PiB

#### Expected weekly DataCap usage rate 
> 350TiB 

#### Client address
> f2n3wzhod7y7zyhxryahlwesqvshgbvr4d4jxedva

**Comment by scdpnh** [comment]
Hello notary, I will arrange the reply email and form as soon as possible!

The responses to your questions are as follows：

Sichuan Dongpeng Nonghai Technology Co., Ltd. is an innovative technology company deeply engaged in the field of high-tech and information technology. In response to the national strategy of smart agriculture and rural revitalization, the company has industry-level and whole-chain solutions for the direction of rural economic construction, agricultural social services and rural industry revitalization. Dongpeng Nonghai Co., Ltd. is committed to play the role of platform in the industry and provide industrial supporting equipment from the perspective of focusing on high-tech research and development and independent innovation. Is a set design, research and development, production, sales as one of the industrial service technology company.

Q：As you are brand new on Github and have no history of past applications. Can you give me an introduction who you are and an introduction about your company?

A：Company established for agricultural WEB3.0 project recently, I am a member of the data is stored and used by my options and evaluation.


Q：You stated that you are a Data preparer. What hardware do you have over there to prepare this dataset? What is your internet connection speed? Do you already have the data downloaded on the premises?

A：Yes, we have our own internal distributed storage server, which needs to integrate data of existing business scenarios. The data center provides 1GB of egress bandwidth, while the office only has partial scenario data.

Q：It seems to me that applying for 5PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?

A：In the process of our research, we found several Filecoin SP service providers to provide us with storage solutions, and Filecoin SP provides us with technical support. We have continued to pay attention to the Filecoin field and only pay attention to the ecological development of the storage field. We are also investigating the recently launched smart contracts. I hope this technology can play a role in our company's application support. I have not applied for datacap with other GitHub accounts.


@cryptowhizzard @simonkim0515

**Comment by scdpnh** [comment]
@Sunnyiscoming @cryptowhizzard @simonkim0515 


Do you contact me by phone?

**Comment by scdpnh** [comment]
@caoyoungyoung 

Can I find you on slack?I need to send you relevant screenshots.

**Comment by zcfil** [comment]
You can use your official domain name to filplus-app-review@fil.org Send email and copy to reymond.bu@gmail.com To confirm your identity? The email name should include question ID # [1883](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1883).

**Comment by scdpnh** [comment]
@zcfil 
@simonkim0515 

I have sent an email to you yesterday, please check whether it meets the requirements.

**Comment by scdpnh** [comment]
@simonkim0515

**Comment by scdpnh** [comment]
The notary needs your help, so that I can push forward the implementation of my project. Please point out what is missing at present.

**Comment by scdpnh** [comment]
@caoyoungyoung 

The relevant certification materials have been sent to these two emails. If you need them, I can send them to you. Besides, I haven't found your channel on slack.

The relevant certification materials have been sent to these two emails. If you need them, I can send them to you. Besides, I haven't found your channel on slack. If you need to contact me by phone, you need to call my reserved number in the United States at around 9 a.m. I am currently working in China.

[filplus-app-review@fil.org][reymond.bu@gmail.com]

**Comment by scdpnh** [comment]
http://43.228.180.106:7575/ipfs/bafykbzacedgjzbdme2a5zhlyphl3xzdksabvnahtlcszlx6inynwwsggedyho
http://43.228.180.106:7575/ipfs/bafykbzacearvivx4gbe4jv4sjx4wwhck74ycicfx65s4npigqy7xaofkuge4y
http://43.228.180.106:7575/ipfs/bafykbzacec4tz6qyb7e3gshqyh4ezq7hzsafv26o4xrrlwq46zvmxzjzm4w4g
http://43.228.180.106:7575/ipfs/bafykbzacebpbdb7dsbmppyasibt7atwrima772fua2m6qk3wpqtg6zfi2rzgs
http://43.228.180.106:7575/ipfs/bafykbzacecv3gajexhgklyqwswpaabhwtbgyxo7fuaadllysfx3eyr4mgcmiq
http://43.228.180.106:7575/ipfs/bafykbzacecba7moa5bdtk4zthflelwfbifftqyaje5isytbdpfilmxfhxlngy
http://43.228.180.106:7575/ipfs/bafykbzacearzzmcx2zo5ua65s43zj4isitojc3yry2z5th4lbbpkdohiheylq
http://43.228.180.106:7575/ipfs/bafykbzacecse7zlxbmwuvbdapd63vdwhtvhjzprr2xdz2jo6et5gn4bdvghzo
http://43.228.180.106:7575/ipfs/bafykbzacedc7ra2443l4drp2gufbwzfpocv3lprtbgyzarkzvg57unq7555uu
http://43.228.180.106:7575/ipfs/bafykbzacedrrqvq7im6xq5iu3ua75thjqoyajkg2zvrju5u3pfz5uqadzein2


@simonkim0515


 It has been nearly a month of communication, but it has not been put in place. We just need one more approval for our request. Would love your support, our data is ready.

**Comment by zcfil** [comment]
@scdpnh Received your email, we apologize for the delay in processing. Due to the fact that our notaries work in various locations, there may be time differences. This round of audit has been passed, and we hope to complete data storage in accordance with the requirements of plus+

**Comment by zcfil** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced7yzgqjt4j4jwm46b3uoyjfg4uz7fcgv57swqpgdxyelb6jicl5o 
#### Address 
> f2n3wzhod7y7zyhxryahlwesqvshgbvr4d4jxedva
#### Datacap Allocated
> 175.00TiB
#### Signer Address
> f1cjzbiy5xd4ehera4wmbz63pd5ku4oo7g52cldga
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced7yzgqjt4j4jwm46b3uoyjfg4uz7fcgv57swqpgdxyelb6jicl5o

**Comment by scdpnh** [comment]
@Sunnyiscoming @simonkim0515 

Dear notary, regarding our application, what other materials are needed and how long will it take to review? Please kindly deal with it.

**Comment by scdpnh** [comment]
@simonkim0515
The address I applied for is multi-signature address. Could you please tell me the operation method of multi-signature address in use?

**Comment by cryptowhizzard** [comment]
> As last question i would like you to fill out [this form](https://form.jotform.com/230337462961356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

As last question i would like you to fill out [this form](https://form.jotform.com/230337462961356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

**Comment by scdpnh** [comment]
@cryptowhizzard 


Dear notary, I have filled in the relevant form as required. Please review it. Thank you very much.

**Comment by scdpnh** [comment]
@DaYouGroup 

链接: https://pan.baidu.com/s/1ChZwsXq06ZvqeE_QlLEnJg 提取码: 53ws 
--来自百度网盘超级会员v1的分享

google Cloud Disk space capacity is not enough

<img width="582" alt="image" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/129580325/0583fb75-8b16-429e-a350-ceaaaddf559c">


This is our local storage pool, which is running out of space

**Comment by scdpnh** [comment]
@DaYouGroup 

https://drive.google.com/drive/folders/10hECCC0DXqLLePCWnqNX0Ncoj8_s3aId?usp=sharing

**Comment by jomozz** [comment]
Hi, @scdpnh are these smart farms owned by your company? Or does it belong to your customers? If it belongs to the customers, do you have the right to store the data publicly?

**Comment by scdpnh** [comment]
@jomozz 

There are customers, not all the data of the collection equipment should be uploaded, and the data that needs to be uploaded needs to be reduced and desensitized.

**Comment by jomozz** [comment]
@scdpnh the data stored on fil-plus can be accessed by anyone. So please make sure that the data is public and does not contain any content that may cause disputes. I will continue to pay attention to this LDN.

**Comment by jomozz** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedajtdninq7jy4ylopmcowgh6ee7pxlrhdjc6fxely6tnzeuyqgty 
#### Address 
> f2n3wzhod7y7zyhxryahlwesqvshgbvr4d4jxedva
#### Datacap Allocated
> 175.00TiB
#### Signer Address
> f1qpdwt2f2fse74nl5wi27uk5jcyqqqyil47yqt7i
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedajtdninq7jy4ylopmcowgh6ee7pxlrhdjc6fxely6tnzeuyqgty

**Comment by scdpnh** [comment]
@Sunnyiscoming @jomozz @zcfil 

My application uses f2 address. There is no specific explanation on how to allocate the approved datacap. If I use boost to allocate, do I need to change the address to f1 or f3?

**Comment by scdpnh** [comment]
@Sunnyiscoming @jomozz @zcfil 

Dear Notary public
boost does not recommend using the f2 address as the allocation address, which will affect the transaction flow.

Thank you for transferring the approval of f2 address to f1 address.

f2n3wzhod7y7zyhxryahlwesqvshgbvr4d4jxedva


f1j62joj4uatolg62ckvx67m4sqjmxt25yfsmgsvq

**Comment by scdpnh** [comment]
@Sunnyiscoming @jomozz @zcfil @simonkim0515 


How can I handle this situation?

**Comment by scdpnh** [comment]
@simonkim0515 @cryptowhizzard @Sunnyiscoming @jomozz @zcfil 


Dear notary, my application card is unavailable at f2 address and the bill of lading process. I hope you can sign in at f1 address so that the project can continue to move forward.

**Comment by Sunnyiscoming** [comment]
Close it.
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/2022
