### ISSUE TITLE
[DataCap Application] NIH NCBI Sequence Read Archive (SRA) src-1

### ISSUE THREAD

**Issue by AgeeWeb3** [filecoin-project/filecoin-plus-large-datasets#1884]
### Data Owner Name

National Library of Medicine (NLM)

### Data Owner Country/Region

United States

### Data Owner Industry

Life Science / Healthcare

### Website

https://www.ncbi.nlm.nih.gov/sra/docs/sra-cloud/

### Social Media

```text
https://www.nlm.nih.gov/
https://twitter.com/NLM_NIH
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

800TiB

### On-chain address for first allocation

f1g7y7hqjqyp4rkflqd3a2z5cr5olmtdvpj6oz5wq

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
The Sequence Read Archive (SRA), produced by the National Center for Biotechnology Information (NCBI) at the National Library of Medicine (NLM) at the National Institutes of Health (NIH), stores raw DNA sequencing data and alignment information from high-throughput sequencing platforms. The SRA provides open access to these biological sequence data to support the research community's efforts to enhance reproducibility and make new discoveries by comparing data sets. Buckets in this registry contain public SRA data in the original (user submitted) format from select high value and newly-released studies as well as all public-access SRA formatted ETL+BQS data. Also included is all SRA metadata that can be leveraged for attribute-based data discovery.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
.bam, .cram, and .fastq files in a public S3 bucket. This is the first of two S3 buckets for source submissions from sequencing methodologies such as PacBio, Oxford Nanopore Technologies, and 10X Genomics.
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### How do you plan to prepare the dataset

lotus, singularity

### Please share a sample of the data

```text
aws s3 ls --no-sign-request s3://sra-pub-src-1/
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Sporadic

### For how long do you plan to keep this dataset stored on Filecoin

1 to 1.5 years

### In which geographies do you plan on making storage deals

Asia other than Greater China, North America, South America, Europe

### How will you be distributing your data to storage providers

HTTP or FTP server, Shipping hard drives, Lotus built-in data transfer

### How do you plan to choose storage providers

Slack, Filmine, Big data exchange

### How do you plan to make deals to your storage providers

Lotus client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
Can you introduce your organizaion? Please share more detailed information about sps you will cooperate with.

**Comment by AgeeWeb3** [comment]
Hi @Sunnyiscoming  I had participated in hackathon, and after learning about it I discovered filecoin and interested in it. Also, I took part in Slingshot and keep an eye on the community for a long time.
I'm looking for SPs who have good reputation and experience about dealing. That's in the progress.

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 5PiB

**Expected weekly DataCap usage rate**
> 800TiB

**Client address**
>f1g7y7hqjqyp4rkflqd3a2z5cr5olmtdvpj6oz5wq

**Comment by Aifabot-Cloud** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebyulq7mp6xk76ts4hnk7lqgae3k653ggm4wpdaxsmfx5cbgfhvj4 
#### Address 
> f1g7y7hqjqyp4rkflqd3a2z5cr5olmtdvpj6oz5wq
#### Datacap Allocated
> 256.00TiB
#### Signer Address
> f174fg3bqbln3zjnkxtyf6s54txqkr7yqkj6cig7y
#### Id
> 548218af-c034-48c7-9300-5d9bb1ccc190
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebyulq7mp6xk76ts4hnk7lqgae3k653ggm4wpdaxsmfx5cbgfhvj4

**Comment by Casey-PG** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceabb62u7c3xeapsw76h6x5zuzg6xmxccw2ie7hgg52c7bpqzc32bu 
#### Address 
> f1g7y7hqjqyp4rkflqd3a2z5cr5olmtdvpj6oz5wq
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f1d4yb3wags3mtddzesxoo63jv7dmlec3bq4yteni
#### Id
> ee773c65-f904-49e2-8a44-a903a6b9eadf
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceabb62u7c3xeapsw76h6x5zuzg6xmxccw2ie7hgg52c7bpqzc32bu

**Comment by BobbyChoii** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceck7irvp6567w7iwixoeqx4unc7bz75b3lcmg6heqv2ml67egc5l4 
#### Address 
> f1g7y7hqjqyp4rkflqd3a2z5cr5olmtdvpj6oz5wq
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f1irqs2gmctiv3jcdfwuch7oxvf4ixh3k4b2wc24i
#### Id
> ee773c65-f904-49e2-8a44-a903a6b9eadf
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceck7irvp6567w7iwixoeqx4unc7bz75b3lcmg6heqv2ml67egc5l4

**Comment by TakiChain** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedkj44rgaw3lhl37bbengelpibncttdhybnl4hn4fobvolrlzqnfu 
#### Address 
> f1g7y7hqjqyp4rkflqd3a2z5cr5olmtdvpj6oz5wq
#### Datacap Allocated
> 1.00PiB
#### Signer Address
> f15impf3j2zcaex4lhyxndxswuuhv24vzstuqtxsi
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedkj44rgaw3lhl37bbengelpibncttdhybnl4hn4fobvolrlzqnfu

**Comment by cryptowhizzard** [comment]
Hi,

None of the data stored here is retrievable. This is against the FIL+ Guidelines.
Secondly there is no diversity, everything is in HongKong, also against Fil+ Guidelines.

Can you please correct this?

<img width="1121" alt="Scherm­afbeelding 2023-05-05 om 19 47 32" src="https://user-images.githubusercontent.com/36404435/236529617-1c4760c6-e59c-40e8-8422-bf3b80e1ce66.png">

**Comment by Casey-PG** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceblkx6syzonqfmeavc5vknxf6bftaj3gw6mbakxaf5lpggvhz4gf6 
#### Address 
> f1g7y7hqjqyp4rkflqd3a2z5cr5olmtdvpj6oz5wq
#### Datacap Allocated
> 2.00PiB
#### Signer Address
> f1d4yb3wags3mtddzesxoo63jv7dmlec3bq4yteni
#### Id
> 97a92c76-8df9-4a3a-8233-5b3178b5c051
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceblkx6syzonqfmeavc5vknxf6bftaj3gw6mbakxaf5lpggvhz4gf6

**Comment by AthSmith** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedjh2p26reb7sqjyeos3pnjwao6rqnqmxxvxxls7rpwm5wlusnqz2 
#### Address 
> f1g7y7hqjqyp4rkflqd3a2z5cr5olmtdvpj6oz5wq
#### Datacap Allocated
> 2.00PiB
#### Signer Address
> f1vxbqrf7rfum3n6m5u6eb4re6xj7amvsaqnzu64y
#### Id
> 97a92c76-8df9-4a3a-8233-5b3178b5c051
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedjh2p26reb7sqjyeos3pnjwao6rqnqmxxvxxls7rpwm5wlusnqz2

**Comment by AgeeWeb3** [comment]
Please remain open。

**Comment by HiFil** [comment]
checker:manualTrigger

**Comment by AgeeWeb3** [comment]
@cryptowhizzard Your words mean nothing.

**Comment by Wengeding** [comment]
checker:manualTrigger

**Comment by Wengeding** [comment]
have done DD with the applicant, report looks normal to me. some indicators could be improved a bit more.

**Comment by Wengeding** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceae2m2sfdy2n6bfbfyiapc66lkcj3ob3cczqufnlvlqpla5pv42ui 
#### Address 
> f1g7y7hqjqyp4rkflqd3a2z5cr5olmtdvpj6oz5wq
#### Datacap Allocated
> 1.25PiB
#### Signer Address
> f1txfsjmix4vlzido4dkildrnbw26owtlbslexmpa
#### Id
> c5e5c7b2-2cd8-4704-b676-6b08495ab545
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceae2m2sfdy2n6bfbfyiapc66lkcj3ob3cczqufnlvlqpla5pv42ui

**Comment by AthSmith** [comment]
In light of the applicant's long history of engagement and response record, this is the kind of consistent DD response attitude that file plus requires. Thank you for integrating more trustworthy data into the network and please continue to follow fileplus' guidelines.

**Comment by AthSmith** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebk5o5j5xcwahkeek5imjfsxxtr5l3ek7xnxt2q7ir2lpkr7qp3om 
#### Address 
> f1g7y7hqjqyp4rkflqd3a2z5cr5olmtdvpj6oz5wq
#### Datacap Allocated
> 1.25PiB
#### Signer Address
> f1vxbqrf7rfum3n6m5u6eb4re6xj7amvsaqnzu64y
#### Id
> c5e5c7b2-2cd8-4704-b676-6b08495ab545
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebk5o5j5xcwahkeek5imjfsxxtr5l3ek7xnxt2q7ir2lpkr7qp3om

**Comment by clriesco** [comment]
Removed stale label and reopened issue :)

**Comment by cryptowhizzard** [comment]
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1898#issuecomment-1701036576

![Scherm­afbeelding 2023-08-31 om 15 33 22](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/36404435/03c82f44-75e6-4d29-b183-c6b37044a239)
