### ISSUE TITLE
[DataCap Application] <Manchilide Training Center> - <Manchilide Training Center>

### ISSUE THREAD

**Issue by kv0054** [filecoin-project/filecoin-plus-large-datasets#1885]
### Data Owner Name

Manchilide Training Center 

### Data Owner Country/Region

China

### Data Owner Industry

Arts & Recreation

### Website

https://magicleaders.com/

### Social Media

```text
https://magicleaders.com/
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

700TiB

### On-chain address for first allocation

f1zyxhwqzqs5svr6v7kqlctkkmmbdli56tezg7hdi

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Qilide Training Center is located in the historic Fuzhou city of Rongcheng, covering an area of approximately 20000 square meters. It mainly focuses on short-term full-time CG training and full-time college education, and actively explores in various fields such as art exhibitions, surrounding trendy games, and CG competitions. We are committed to creating an education brand that meets the diverse needs of the new generation of digital high-tech talents.
Since 2012, Manqilide has adhered to the teaching philosophy of "education first, skill first, and service first", with the aim of being the first CG education brand in the country, and is committed to researching and learning CG design training. Every year, more than 3000 high-quality CG talents are cultivated, and graduate students are distributed across major game, animation, and related enterprises across the country.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
A large number of training videos, including tutorials on painting, detailed explanations, student painting videos, and more
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### How do you plan to prepare the dataset

lotus, singularity

### Please share a sample of the data

```text
https://magicleaders.com/works
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Monthly

### For how long do you plan to keep this dataset stored on Filecoin

More than 3 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, South America

### How will you be distributing your data to storage providers

HTTP or FTP server, Shipping hard drives

### How do you plan to choose storage providers

Slack, Big data exchange

### If you already have a list of storage providers to work with, fill out their names and provider IDs below

```text
f01923787
f02062851
f01877184
f01836766
f01859603
```

### How do you plan to make deals to your storage providers

Boost client, Lotus client, Singularity

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
Could you send an email to filplus-app-review@fil.org with your official domain in order to confirm your identity? Email name should includes the issue id #1885.

**Comment by kv0054** [comment]
@Sunnyiscoming Hi
![image](https://user-images.githubusercontent.com/129385126/230768495-4ef9a9c8-6a0c-4943-8d4d-dd22e8bb8bc2.png)

**Comment by Sunnyiscoming** [comment]
I did not receive the email. I have sent you an email, please reply according to the content of the email.

**Comment by Sunnyiscoming** [comment]
My email was returned because of a problem with your server. Please check it.

**Comment by cryptowhizzard** [comment]
Dear @kv0054 

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Looking at your application i have some questions:
As you are brand new on Github and have no history of past applications. Can you give me an introduction who you are and an introduction about your company?

You stated that you are a Data preparer. What hardware do you have over there to prepare this dataset? What is your internet connection speed? Do you already have the data downloaded on the premises?

It seems to me that applying for 5PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?

Can you show us some visible proof of the size of your data and the storage / packing hardware you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230337462961356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!

**Comment by Sunnyiscoming** [comment]
Any update here?

**Comment by Sunnyiscoming** [comment]
Close for no reply here.
