### ISSUE TITLE
[DataCap Application] <Beijing Boyi Era Medical Technology Co., Ltd> - <Beijing Boyi Era Medical Technology>

### ISSUE THREAD

**Issue by kej3656** [filecoin-project/filecoin-plus-large-datasets#1886]
### Data Owner Name

Beijing Boyi Era Medical Technology Co., Ltd

### Data Owner Country/Region

China

### Data Owner Industry

Life Science / Healthcare

### Website

https://boyitimes.com/gywm

### Social Media

```text
https://boyitimes.com/gywm
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

500TiB

### On-chain address for first allocation

f1p2ikl27a2mwnaasxu4qsiu2h6xxtnh3loevpfra

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Beijing Boyi Era Medical Technology Co., Ltd. was established on May 27, 2014, dedicated to providing comprehensive surgical training solutions for hospitals and surgeons.
After eight years of independent research and development, the era of Bo Yi is guided by training results and adheres to the product development concept of "lifelike, accurate, and convenient". After being validated by over 100 hospitals, over 200 experts, and over 2000 medical students, the "Bo Yi Era Minimally Invasive Surgery Ability Improvement System" has been officially established with "cognition, skills, and practical operation" as the core.
Bo Yi Times is headquartered in Beijing and has branches and subsidiaries in multiple parts of the country. We look forward to working together with partners in related fields to jointly build a national brand, based in China, with an international perspective, serving global surgeons, and contributing to public health!
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
Committed to providing comprehensive surgical training solutions for hospitals and surgeons, including video and text teaching
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### Please share a sample of the data

```text
https://mp.weixin.qq.com/s/mfSljGP51wyWJ_llV53LkA
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Monthly

### For how long do you plan to keep this dataset stored on Filecoin

More than 3 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, South America

### How will you be distributing your data to storage providers

HTTP or FTP server, Shipping hard drives

### How do you plan to choose storage providers

Slack, Big data exchange

### If you already have a list of storage providers to work with, fill out their names and provider IDs below

```text
f01927554
f01938671
f01877184
f01836766
f01859603
```

### How do you plan to make deals to your storage providers

Boost client, Lotus client, Singularity

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
Can you provide more data samples to prove that you have 5 PB data already?

**Comment by kej3656** [comment]
@Sunnyiscoming The data is a bit messy, sorry
![image](https://user-images.githubusercontent.com/129384958/230768733-b4718cb4-1778-4e0c-a3ec-4411394f0b76.png)
![image](https://user-images.githubusercontent.com/129384958/230768753-44204a50-ef85-4e48-b9d2-a8ee921c54e6.png)
![image](https://user-images.githubusercontent.com/129384958/230768766-584f2073-78e7-491a-beb4-cae4df7480ba.png)
![image](https://user-images.githubusercontent.com/129384958/230768843-ec460d6d-132d-4ba3-8332-e9b44b14b917.png)

**Comment by Sunnyiscoming** [comment]
Could you send an email to filplus-app-review@fil.org with your official domain in order to confirm your identity? Email name should includes the issue id #1886.

**Comment by kej3656** [comment]
@Sunnyiscoming Hi
![image](https://user-images.githubusercontent.com/129384958/230920373-b7107e1c-af5d-4c03-92cc-db758702ee03.png)

**Comment by kej3656** [comment]
@Sunnyiscoming Hi
![image](https://user-images.githubusercontent.com/129384958/230920578-0a5d74b2-8d5c-4bec-97b5-799e301a3848.png)

**Comment by cryptowhizzard** [comment]
Dear @kej3656 ,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Looking at your application i have some questions:
As you are brand new on Github and have no history of past applications. Can you give me an introduction who you are and an introduction about your company?

You stated that you are a Data preparer. What hardware do you have over there to prepare this dataset? What is your internet connection speed? Do you already have the data downloaded on the premises?

It seems to me that applying for 5PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?

Can you show us some visible proof of the size of your data and the storage / packing hardware you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230337462961356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!

**Comment by Sunnyiscoming** [comment]
Any update here?

**Comment by Sunnyiscoming** [comment]
Close for no reply here.
