### ISSUE TITLE
[DataCap Application] VIXII METADATA LAB

### ISSUE THREAD

**Issue by vixiigit** [filecoin-project/filecoin-plus-large-datasets#1887]
### Data Owner Name
VIXII METADATA LAB

### Data Owner Country/Region
Canada

### Data Owner Industry
Financial Services

### Website
[http://www.vixii.net/](http://www.vixii.net/)

### Social Media
@vixii612 (Twitter)

### Total amount of DataCap being requested
5 PiB

### Weekly allocation of DataCap requested
100 TiB

### On-chain address for first allocation
f16hjjuanxe6ojsbf27xq5wh3e7esbae3ucnmfwfq

### Data Type of Application
Public, Open Commercial/Enterprise

### Custom multisig
No

### Share a brief history of your project and organization
VIXII METADATA LAB is a global encrypted digital currency computing power comprehensive service platform, dedicated to providing digital currency transaction quantitative data, investment research tools, mining solutions and related information for global trading users. We have a young, capable and pragmatic team that provides users with a variety of digital currency data solutions and mining solutions through professional and reliable algorithms, flexible and effective services. 
In addition, VIXII METADATA LAB also integrates digital currency market news, blockchain product introductions, and supports uploading articles for free discussion, allowing users to further participate in the WEB3.0 ecology. 
At present, VIXII METADATA LAB's customer base includes institutions and individuals. 

### Is this project associated with other projects/ecosystem stakeholders?
No

### Describe the data being stored onto Filecoin
The public market data of digital currency, including the transaction data of digital currency such as fil/btc/eth, the original data is analyzed and effectively integrated through our unique algorithm. 

### Where was the data currently stored in this dataset sourced from
Other

### If you answered "Other" in the previous question, enter the details here
Dropbox

### How do you plan to prepare the dataset
IPFS

### Please share a sample of the data
https://www.dropbox.com/sh/66c93km63tvc96o/AAA3N8qtWz5GyXQyCQ1ruARJa?dl=0

### Confirm that this is a public dataset that can be retrieved by anyone on the Network
Yes

### What is the expected retrieval frequency for this data
Daily

### For how long do you plan to keep this dataset stored on Filecoin
Permanently

### In which geographies do you plan on making storage deals
North America

### How will you be distributing your data to storage providers
IPFS

### How do you plan to choose SP
I don't know yet

### How do you plan to make deals to your storage providers
I don't know yet

### Can you confirm that you will follow the Fil+ guideline
Yes

_Application created via [filplus.storage](https://filplus.storage)_

**Comment by Sunnyiscoming** [comment]
If you don't know how to find sps. You can chat with more community members in slack channel. https://app.slack.com/client/TEHTVS1L6/C01KCAAURAN/thread/C0405HANNBT-1678182125.832369

Could you send an email to filplus-app-review@fil.org with your official domain in order to confirm your identity? Email name should includes the issue id #1887.

**Comment by vixiigit** [comment]
> If you don't know how to find sps. You can chat with more community members in slack channel. https://app.slack.com/client/TEHTVS1L6/C01KCAAURAN/thread/C0405HANNBT-1678182125.832369
> 
> Could you send an email to [filplus-app-review@fil.org](mailto:filplus-app-review@fil.org) with your official domain in order to confirm your identity? Email name should includes the issue id #1887.

Emailed as requested, please check.
Thanks.

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 5PiB

**Expected weekly DataCap usage rate**
> 100TiB

**Client address**
>f16hjjuanxe6ojsbf27xq5wh3e7esbae3ucnmfwfq

**Comment by vixiigit** [comment]
checker:manualTrigger

**Comment by cryptowhizzard** [comment]
Dear @vixiigit ,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Looking at your application i have some questions:
As you are brand new on Github and have no history of past applications. Can you give me an introduction who you are and an introduction about your company?

You stated that you are a Data preparer. What hardware do you have over there to prepare this dataset? What is your internet connection speed? Do you already have the data downloaded on the premises?

It seems to me that applying for 5PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?

Can you show us some visible proof of the size of your data and the storage / packing hardware you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230337462961356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!

**Comment by zcfil** [comment]
@vixiigit Can you provide more data samples to prove the need for 5P LDN.
The provided 1.1GB file always fails to download, it is unclear why.
You are storing transaction type data, which takes up very little space. Can you provide a large amount of storage requirements

**Comment by vixiigit** [comment]
> @vixiigit Can you provide more data samples to prove the need for 5P LDN. The provided 1.1GB file always fails to download, it is unclear why. You are storing transaction type data, which takes up very little space. Can you provide a large amount of storage requirements

The link seems fine for us, can you see the files and sub-folders listed in 'FilDATASample' folder?  Is there a specific file that failed to be downloaded?

**Comment by vixiigit** [comment]
> This application has not seen any responses in the last 14 days, so for now it is being closed. Please feel free to re-open if this is relevant, or start a new application for DataCap anytime. Thank you!

Sorry we are still collecting information and data and then will reply.  Please allow more time to prepare.  Thanks.
