### ISSUE TITLE
[DataCap Application] <reachauto> - <S1 Single Look Complex (SLC) dataset> (1/2)

### ISSUE THREAD

**Issue by BobStaring** [filecoin-project/filecoin-plus-large-datasets#1889]
### Data Owner Name

reachauto

### Data Owner Country/Region

China

### Data Owner Industry

IT & Technology Services

### Website

https://www.reachauto.com/

### Social Media

```text
微信公众号(WeChat Official Account)：东软睿驰
https://www.reachauto.com/2news-center/
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

500TiB

### On-chain address for first allocation

f1hbciewgwkj4rizz3nvygoauyuzeynihmzaapvvy

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Neusoft Reach, founded in October 2015, is an industry-leading product and service provider of basic software, SOA middleware, autonomous driving and cross-domain integration of vehicle and cloud technology. We take software technology as the core, integrates key technologies such as big data, artificial intelligence and basic software, focuses on key fields such as autonomous driving, intelligent networking, basic software and operating system, and provides outstanding and iterable core technologies, integrated software and hardware products and software platform products for automotive enterprises to face future technological innovation and development.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
The S1 SLC dataset contains Synthetic Aperture Radar (SAR) data obtained by the sensor Sentinel-1 operating in the microwave C-Band wavelength. The SAR sensors are installed on a two-satellite (Sentinel-1A and Sentinel-1B) constellation orbiting the Earth, operated by the European Space Agency. The S1 SLC data are a Level-1 product that consists of focused SAR data in zero-Doppler slant-range geometry, suitable for advanced processing with fewer processing steps as compared to Level-0 raw products. The Level-1 SLC product also preserves the radar backscatter amplitude and phase information in all-weather, day or night conditions, which is ideal for studying natural hazards and emergency response, land applications, oil spill monitoring, sea-ice conditions, and associated climate-change effects.
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### How do you plan to prepare the dataset

IPFS, lotus, graphsplit

### Please share a sample of the data

```text
s3://sentinel1-slc-seasia-pds/ (Total Size: 1.1 PiB)
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Monthly

### For how long do you plan to keep this dataset stored on Filecoin

1.5 to 2 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, Europe

### How will you be distributing your data to storage providers

HTTP or FTP server, IPFS, Shipping hard drives

### How do you plan to choose storage providers

Slack, Partners

### If you already have a list of storage providers to work with, fill out their names and provider IDs below

```text
f02092901
f01789666
f0134516
f0118330
f0839509
f02098007
f0867300
f01395673
f01072221
f0143858
f01786736
f01348489
f0522948
f02099939
```

### How do you plan to make deals to your storage providers

Boost client, Lotus client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
Could you send an email to filplus-app-review@fil.org with your official domain in order to confirm your identity? Email name should includes the issue id #1889.

**Comment by Sunnyiscoming** [comment]
Any update here? It will be closed if there is no reply in 3 days.

**Comment by BobStaring** [comment]
@Sunnyiscoming Sorry, because it's the weekend,I will send the email tomorrow.Thanks!

**Comment by BobStaring** [comment]
@Sunnyiscoming Hi, we sent the email just now.Please check it for us.Thanks.

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 5PiB

**Expected weekly DataCap usage rate**
> 500TiB

**Client address**
>f1hbciewgwkj4rizz3nvygoauyuzeynihmzaapvvy

**Comment by Normalnoise** [comment]
@BobStaring can you confirm those SPs support fast retrieval？How much data did you download？

**Comment by BobStaring** [comment]
@Normalnoise Yes, we have confirm with the SPs.And we have downloaded about 150TiB SLC dada.

**Comment by nj-steve** [comment]
@BobStaring Hello, please tell us how many copies do you want to send to SPs ?and which regions are they distributed in？

**Comment by BobStaring** [comment]
@nj-steve We will send 9 copies to SPs,they are in Greater China or Asia other than Greater China or North America.

**Comment by cryptowhizzard** [comment]
Dear,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Looking at your application i have some questions:
As you are brand new on Github and have no history of past applications. Can you give me an introduction who you are and an introduction about your company?

You stated that you are a Data preparer. What hardware do you have over there to prepare this dataset? What is your internet connection speed? Do you already have the data downloaded on the premises?

It seems to me that applying for 5PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?

Can you show us some visible proof of the size of your data and the storage / packing hardware you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230337462961356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!

**Comment by BobStaring** [comment]
Hello,cryptowhizzard. I'm Bob from reachauto.The one our data storage and management officer. We needs to analyze a lot of relevant lidar data for testing.

We have download the data.Our download speed is about 10T per day. The more detail is in the screenshot.

We've been working on this project for a while.We have consulted a few filecoin orgnizations and have learnt the knowledge of filecoin, packing of data, distribution of data. And have tested it.

The screenshot is about our download speed of the data from aws and the size we have download.
![图片](https://user-images.githubusercontent.com/116865016/232016276-5c592c7a-817d-4802-9fd9-5da9cd491395.png)

<img width="393" alt="图片" src="https://user-images.githubusercontent.com/116865016/232016343-2b10462c-1e30-492a-8eef-d472ae9e5e65.png">

Thanks!

**Comment by nj-steve** [comment]
manualTrigger

**Comment by nj-steve** [comment]
checker:manualTrigger

**Comment by Normalnoise** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceasplbkw5m5mc3lg5wyjzsebuxkvaarz5gt44gb237oj2nqw5pzks 
#### Address 
> f1hbciewgwkj4rizz3nvygoauyuzeynihmzaapvvy
#### Datacap Allocated
> 250.00TiB
#### Signer Address
> f1c5non5yf35avgcpsqvxu4yj54yyvxorwyjochqq
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceasplbkw5m5mc3lg5wyjzsebuxkvaarz5gt44gb237oj2nqw5pzks

**Comment by stcouldlisa** [comment]
I get requests from clients and, as a first round, I'm willing to trust them for now. before supporting you, please list your node's plan, backup plan. And show us a sample of your data.

**Comment by BobStaring** [comment]
@stcouldlisa Hi notary,thanks for your trust.We will not betray your trust.
1.We have contact with some SPs, some news are in contacting.And will  send 8-10 copies to them. They are in Greater China or Asia other than Greater China or North America.
2.The snapshot below is some of the information about the data we have downloaded.
![图片](https://user-images.githubusercontent.com/116865016/234789264-0e771eaa-470f-425b-bb41-20920ce278b5.png)

3.The link of storage is sample data of the lidar data(synced_lidar_cam_data).
https://www.aliyundrive.com/s/tkfoTaSnQp3
4. #1890  is the same dataset.Please check it out.Thanks!

**Comment by stcouldlisa** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaqybju6vy5yzzijvmuuo4v46kxkyqrxd5mrqtna6xf2z5iwejilw 
#### Address 
> f1hbciewgwkj4rizz3nvygoauyuzeynihmzaapvvy
#### Datacap Allocated
> 250.00TiB
#### Signer Address
> f1jvvltduw35u6inn5tr4nfualyd42bh3vjtylgci
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaqybju6vy5yzzijvmuuo4v46kxkyqrxd5mrqtna6xf2z5iwejilw

**Comment by BobStaring** [comment]
checker:manualTrigger

**Comment by BobStaring** [comment]
checker:manualTrigger

**Comment by BobStaring** [comment]
Hello @Sunnyiscoming ,we will use this client recently，plese help us to reopen the  issue. Thanks.

**Comment by BobStaring** [comment]
@Sunnyiscoming  @stcouldlisa @Normalnoise @nj-steve Hello,notaries,please help us to reopen this issue,we will use this client recently. Please help us.Thanks.

**Comment by BobStaring** [comment]
checker:manualTrigger

**Comment by BobStaring** [comment]
checker:manualTrigger

**Comment by BobStaring** [comment]
checker:manualTrigger

**Comment by cryptowhizzard** [comment]
![Scherm­afbeelding 2023-07-27 om 10 55 05](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/36404435/f8496afe-8e22-4949-92bc-7aa793353625)

**Comment by BobStaring** [comment]
keep

**Comment by BobStaring** [comment]
continue

**Comment by BobStaring** [comment]
continue

**Comment by cryptowhizzard** [comment]
Dear BobStaring,

As notary I am doing due diligence on your LDN. I could not get retrieval to work. Can you please upload the car file of CID  ?

You can use our upload system at http://send.datasetcreators.com. Please select 7 days for the system to keep the file and post the link you received here so I (and other notaries) can download your content.

**Comment by BobStaring** [comment]
Hello @Sunnyiscoming this client is still in use.Please help us reopen it.

**Comment by BobStaring** [comment]
Hello @fabriziogianni7 @Sunnyiscoming this client is still in use.Please help us reopen it.

**Comment by BobStaring** [comment]
@cryptowhizzard We are preparing to upload the car file. Thanks for your hard working.

**Comment by cryptowhizzard** [comment]
> > Dear BobStaring,
> > As notary I am doing due diligence on your LDN. I could not get retrieval to work. Can you please upload the car file of CID ?
> > You can use our upload system at http://send.datasetcreators.com. Please select 7 days for the system to keep the file and post the link you received here so I (and other notaries) can download your content.
> 
> Reminder

Reminder.

**Comment by BobStaring** [comment]
OK,got it. We are preparing to upload the car file.The speed is a little slow.Please wait for a moment.

**Comment by BobStaring** [comment]
@cryptowhizzard Hello, we have been experiencing errors and we are trying other ways to want you get the car file.
<img width="1779" alt="error" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/116865016/7ebad697-1120-48ab-b2a1-680746bb74d4">

**Comment by BobStaring** [comment]
link: https://pan.baidu.com/s/1hbi0orDbd7XF8Dar_kVxyA  code: 2he3
piececid: baga6ea4seaqe26jqkama4jz3kusiz7uapq7m3w6defi2iuatkay3cjhquln3wei
@cryptowhizzard Hello we have uploaded the car file. Thanks.

**Comment by BobStaring** [comment]
@simonkim0515 @Sunnyiscoming Please also help me to check the file.And help me to reopen it.

**Comment by shliming** [comment]
thanks，keep please

**Comment by BobStaring** [comment]
Thanks

**Comment by BobStaring** [comment]
also continue

**Comment by BobStaring** [comment]
checker:manualTrigger

**Comment by BobStaring** [comment]
The robot has a delay in updating data

**Comment by BobStaring** [comment]
checker:manualTrigger

**Comment by BobStaring** [comment]
The robot has a delay in updating data. @Sunnyiscoming

**Comment by NiwanDao** [comment]
![301699253224_ pic_hd](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/72185104/4835a883-b752-4155-a5c9-7e908360bf35)
Manual Retrieval Test

**Comment by NiwanDao** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced6kmk753cpvdd2y7gu3beoxofyupy2mimtwen56f4cg3rptaoxrg 
#### Address 
> f1hbciewgwkj4rizz3nvygoauyuzeynihmzaapvvy
#### Datacap Allocated
> 500.00TiB
#### Signer Address
> f1a2lia2cwwekeubwo4nppt4v4vebxs2frozarz3q
#### Id
> 39bea25e-43a4-4a9e-897c-718e21100f3f
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced6kmk753cpvdd2y7gu3beoxofyupy2mimtwen56f4cg3rptaoxrg

**Comment by SuperChaiChai** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecniinebjhd2yo26ggbv22hs6wikck4kwb44lrpcc6kvbjp2kccjc 
#### Address 
> f1hbciewgwkj4rizz3nvygoauyuzeynihmzaapvvy
#### Datacap Allocated
> 500.00TiB
#### Signer Address
> f12mckci3omexgzoeosjvstcfxfe4vqw7owdia3da
#### Id
> 39bea25e-43a4-4a9e-897c-718e21100f3f
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecniinebjhd2yo26ggbv22hs6wikck4kwb44lrpcc6kvbjp2kccjc

**Comment by BobStaring** [comment]
checker:manualTrigger

**Comment by BobStaring** [comment]
keep thanks

**Comment by 1ane-1** [comment]
checker:manualTrigger

**Comment by 1ane-1** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacea4fbatzyta67wmais2jqohesjwftoinmpm4mhd5pxro2itip5ivi 
#### Address 
> f1hbciewgwkj4rizz3nvygoauyuzeynihmzaapvvy
#### Datacap Allocated
> 500.00TiB
#### Signer Address
> f1mdk7s2vntzm6hu35yuo6vjubtrpfnb2awhgvrri
#### Id
> 788c238c-afad-4d25-a56c-ff7d9693b115
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacea4fbatzyta67wmais2jqohesjwftoinmpm4mhd5pxro2itip5ivi

**Comment by mikezli** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb6gu4rylbzsqeqou75uzbfgc4sb3tu5kgx5ci6p6pvgrgqslepne 
#### Address 
> f1hbciewgwkj4rizz3nvygoauyuzeynihmzaapvvy
#### Datacap Allocated
> 500.00TiB
#### Signer Address
> f1dnb3uz7sylxk6emti3ififcvu3nlufnnsjui6ea
#### Id
> 788c238c-afad-4d25-a56c-ff7d9693b115
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb6gu4rylbzsqeqou75uzbfgc4sb3tu5kgx5ci6p6pvgrgqslepne

**Comment by BobStaring** [comment]
keep thanks

**Comment by Sunnyiscoming** [comment]
Hello, per the https://github.com/filecoin-project/notary-governance/issues/922 for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

This information will be reviewed by Fil+ Governance team to confirm validity and then the application will be allowed to move forward for additional notary review.

**Comment by Sunnyiscoming** [comment]
Please provide ID, City, Country, Organization of each SP here.

**Comment by BobStaring** [comment]
Thank you. We are collecting information about SPs.

**Comment by nj-steve** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecawdpgbzizehpf2ngs47gepmwdubbuftvoafxiscciwae3daldf4 
#### Address 
> f1hbciewgwkj4rizz3nvygoauyuzeynihmzaapvvy
#### Datacap Allocated
> 500.00TiB
#### Signer Address
> f1xx6555qijma7igpnjspyvdunc4vfxkawnpqy5ii
#### Id
> 788c238c-afad-4d25-a56c-ff7d9693b115
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecawdpgbzizehpf2ngs47gepmwdubbuftvoafxiscciwae3daldf4

**Comment by Sunnyiscoming** [comment]
SP List provided:
[{"providerID": "f02132642","City": "XYZ", "Country": "Singapore", "SPOrg","QC.sg"},
{"providerID": "f02827777","City": "Mumbai", "Country": "India", "SPOrg","chimsen"},
{"providerID": "f02825666","City": "Guangdong", "Country": "China", "SPOrg","MiningIn"},
{"providerID": "f02836485","City": "Chengdu", "Country": "China", "SPOrg","StorageTrust"},
{"providerID": "f02826888","City": "Toronto", "Country": "Canada", "SPOrg","chimsen"},]

**Comment by BobStaring** [comment]
continue please,thanks

**Comment by BobStaring** [comment]
checker:manualTrigger

**Comment by BobStaring** [comment]
New SPs List provided:
[{"providerID": "f02827111","City": "Osaka", "Country": "JP", "SPOrg","WanDao"},
{"providerID": "f02828222","City": "Seoul", "Country": "KR", "SPOrg","WanDao"},
Thanks, we have new SPs and will solve the problem of 'Deal Data Replication'

**Comment by BobStaring** [comment]
checker:manualTrigger

**Comment by BobStaring** [comment]
I think this problem of 'Deal Data Replication' is caused by our report delay.Please wait for a while.

**Comment by BobStaring** [comment]
checker:manualTrigger

**Comment by nj-steve** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb3jqlcv43u6gr7hpdeae63e5scdds77bahkuzox44kti75gq4it6 
#### Address 
> f1hbciewgwkj4rizz3nvygoauyuzeynihmzaapvvy
#### Datacap Allocated
> 1.95PiB
#### Signer Address
> f1xx6555qijma7igpnjspyvdunc4vfxkawnpqy5ii
#### Id
> adc7c6cc-6e79-4c43-a4bb-f95df5792ce7
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb3jqlcv43u6gr7hpdeae63e5scdds77bahkuzox44kti75gq4it6

**Comment by sxxfuture-official** [comment]
pay attention to reduce duplicate data for [f02826888](https://filfox.info/en/address/f02826888) and  [f02827777](https://filfox.info/en/address/f02827777)

**Comment by sxxfuture-official** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecu6r5qsnav2npt77kdteqeprz7xcbdtoeftnzcjimuzmdvjwxaye 
#### Address 
> f1hbciewgwkj4rizz3nvygoauyuzeynihmzaapvvy
#### Datacap Allocated
> 1.95PiB
#### Signer Address
> f1foiomqlmoshpuxm6aie4xysffqezkjnokgwcecq
#### Id
> adc7c6cc-6e79-4c43-a4bb-f95df5792ce7
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecu6r5qsnav2npt77kdteqeprz7xcbdtoeftnzcjimuzmdvjwxaye

**Comment by BobStaring** [comment]
Thanks, we have paid attention to this duplicate data.

**Comment by BobStaring** [comment]
checker:manualTrigger

**Comment by BobStaring** [comment]
checker:manualTrigger

**Comment by zcfil** [comment]
Viewed the history of responses and would like to support

**Comment by zcfil** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecyyx4tof43ttf352qco5c7kz2wpkr7n6s3zz3bwzlqo7bmyvzcou 
#### Address 
> f1hbciewgwkj4rizz3nvygoauyuzeynihmzaapvvy
#### Datacap Allocated
> 1.95PiB
#### Signer Address
> f1cjzbiy5xd4ehera4wmbz63pd5ku4oo7g52cldga
#### Id
> ee17475f-d914-432a-b9dc-0438a81755b4
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecyyx4tof43ttf352qco5c7kz2wpkr7n6s3zz3bwzlqo7bmyvzcou

**Comment by Tom-OriginStorage** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced25i4ikb2zeucqohxjevgbw6da5iiosgehwbguv2cbs5un6rb7ui 
#### Address 
> f1hbciewgwkj4rizz3nvygoauyuzeynihmzaapvvy
#### Datacap Allocated
> 1.95PiB
#### Signer Address
> f1q6bpjlqia6iemqbrdaxr2uehrhpvoju3qh4lpga
#### Id
> ee17475f-d914-432a-b9dc-0438a81755b4
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced25i4ikb2zeucqohxjevgbw6da5iiosgehwbguv2cbs5un6rb7ui
