### ISSUE TITLE
[DataCap Application] Shanghai Yilianyun Digital Technology Co., Ltd.

### ISSUE THREAD

**Issue by Pandora958** [filecoin-project/filecoin-plus-large-datasets#189]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Shanghai Yilianyun Digital Technology Co., Ltd.
- Website / Social Media: https://www.toutiao.com/c/user/token/MS4wLjABAAAARZ98eyWDzmN5FjrPOLhYh6VVFag0OGvJeSsjMrzfCYs/?
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5 PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 300TiB
- On-chain address for first allocation: f1ciea3vwr6fvdehpuijockqmwfaazz75hna7xoky

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Shanghai Yilianyun Digital Technology Co., Ltd. is a technology company focusing on the R&D and application of data storage technology. It is China’s first public welfare platform dedicated to donating scientists. Through public welfare, it provides scientists with scientific research funds and scientific research results transformation services.
```

What is the primary source of funding for this project?
```
private capital
```

What other projects/ecosystem stakeholders is this project associated with?
```
No
```

## Use-case details

Describe the data being stored onto Filecoin
```
Store COVID-19 Datasets to provide free data support for scientists
```

Where was the data in this dataset sourced from?
```
https://registry.opendata.aws/foldingathome-covid19/
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://registry.opendata.aws/foldingathome-covid19/
https://github.com/FoldingAtHome/coronavirus
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes, it is a public dataset with license cc0
https://creativecommons.org/share-your-work/public-domain/cc0/
```

What is the expected retrieval frequency for this data?
```
Several times a week
```

For how long do you plan to keep this dataset stored on Filecoin?
```
more than 2 years
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Not limited to specific countries or regions, but prefer in Asia
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Online transmission
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
Choose storage providers of different types and regions, and choose at least 5 different storage providers
```

How will you be distributing deals across storage providers?
```
equally distributed, try to make the data distributed in different countries or regions
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Already have sufficient funds and resources
```

**Comment by swatchliu** [comment]
Do you have a public website?

**Comment by Pandora958** [comment]
> Do you have a public website?

@swatchliu Only have the Social Media page：https://www.toutiao.com/c/user/token/MS4wLjABAAAARZ98eyWDzmN5FjrPOLhYh6VVFag0OGvJeSsjMrzfCYs/?

**Comment by galen-mcandrew** [comment]
It sounds like this is a project to store folding at home COVID-19 Datasets, currently hosted in the AWS open data. This would be similar to https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/59 and https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/169

Is this for Slingshot? Am I misreading the application? Do you have a public dataset of your own as a client, related to your operation as a "welfare platform for funding scientists"?

**Comment by quinn463** [comment]
I don't know about them.

**Comment by quinn463** [comment]
In fact I don't know about them.

**Comment by Pandora958** [comment]
> It sounds like this is a project to store folding at home COVID-19 Datasets, currently hosted in the AWS open data. This would be similar to #59 and #169
> 
> Is this for Slingshot? Am I misreading the application? Do you have a public dataset of your own as a client, related to your operation as a "welfare platform for funding scientists"?

@galen-mcandrew It is not for Slingshot. I think it's a coincidence that the same data source was used as this is a recent hot event. Do we have to provide our own dataset? These data are still in preparation.

**Comment by Pandora958** [comment]
@galen-mcandrew Hi Galen, have you check it?

**Comment by dkkapur** [comment]
@Pandora958 is this one still relevant? if so - what is the motivation to upload this dataset for you? are you associated with the research project in any way?

**Comment by dkkapur** [comment]
@Pandora958 pinging back on this, can you confirm if this is still valid?

**Comment by galen-mcandrew** [comment]
Closing for now, please reopen issue if your request is still relevant. Thanks!
