### ISSUE TITLE
[DataCap Application]  <reachauto> - <S1 Single Look Complex (SLC) dataset> (2/2)

### ISSUE THREAD

**Issue by BobStaring** [filecoin-project/filecoin-plus-large-datasets#1890]
### Data Owner Name

reachauto

### Data Owner Country/Region

China

### Data Owner Industry

IT & Technology Services

### Website

https://www.reachauto.com/

### Social Media

```text
微信公众号(WeChat Official Account)：东软睿驰
https://www.reachauto.com/2news-center/
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

500TiB

### On-chain address for first allocation

f1gsvxh5lqvayqgaoxkjwie7swc2lgihgdgjdnaca

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Neusoft Reach, founded in October 2015, is an industry-leading product and service provider of basic software, SOA middleware, autonomous driving and cross-domain integration of vehicle and cloud technology. We take software technology as the core, integrates key technologies such as big data, artificial intelligence and basic software, focuses on key fields such as autonomous driving, intelligent networking, basic software and operating system, and provides outstanding and iterable core technologies, integrated software and hardware products and software platform products for automotive enterprises to face future technological innovation and development.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
The S1 SLC dataset contains Synthetic Aperture Radar (SAR) data obtained by the sensor Sentinel-1 operating in the microwave C-Band wavelength. The SAR sensors are installed on a two-satellite (Sentinel-1A and Sentinel-1B) constellation orbiting the Earth, operated by the European Space Agency. The S1 SLC data are a Level-1 product that consists of focused SAR data in zero-Doppler slant-range geometry, suitable for advanced processing with fewer processing steps as compared to Level-0 raw products. The Level-1 SLC product also preserves the radar backscatter amplitude and phase information in all-weather, day or night conditions, which is ideal for studying natural hazards and emergency response, land applications, oil spill monitoring, sea-ice conditions, and associated climate-change effects.
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### How do you plan to prepare the dataset

IPFS, lotus, graphsplit

### Please share a sample of the data

```text
s3://sentinel1-slc-seasia-pds/ (Total Size: 1.1 PiB)
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Monthly

### For how long do you plan to keep this dataset stored on Filecoin

1.5 to 2 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, Europe

### How will you be distributing your data to storage providers

HTTP or FTP server, IPFS, Shipping hard drives

### How do you plan to choose storage providers

Slack, Partners

### If you already have a list of storage providers to work with, fill out their names and provider IDs below

```text
f02092901
f01789666
f0134516
f0118330
f0839509
f02098007
f0867300
f01395673
f01072221
f0143858
f01786736
f01348489
f0522948
f02099939
```

### How do you plan to make deals to your storage providers

Boost client, Lotus client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
See questions in #1889

**Comment by BobStaring** [comment]
@Sunnyiscoming Hi, we sent the email just now.Please check it for us.Thanks.

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 5PiB

**Expected weekly DataCap usage rate**
> 500TiB

**Client address**
>f1gsvxh5lqvayqgaoxkjwie7swc2lgihgdgjdnaca

**Comment by bq1024** [comment]
Looks good from #1889, willing to support the first round.

**Comment by bq1024** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceds3pmvrcfjvdk5tu4yw5aqu5erzxoxp7pwjcvh5m3iedxtrcwrni 
#### Address 
> f1gsvxh5lqvayqgaoxkjwie7swc2lgihgdgjdnaca
#### Datacap Allocated
> 250.00TiB
#### Signer Address
> f1pkjtavqx4r2q2w3he3jknfc5mo2vgfimccmpnaa
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceds3pmvrcfjvdk5tu4yw5aqu5erzxoxp7pwjcvh5m3iedxtrcwrni

**Comment by stcouldlisa** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceactg4qzwauvmd3gcppelb7hxucgfmfc3dodpwkdtitubye4edsn4 
#### Address 
> f1gsvxh5lqvayqgaoxkjwie7swc2lgihgdgjdnaca
#### Datacap Allocated
> 250.00TiB
#### Signer Address
> f1jvvltduw35u6inn5tr4nfualyd42bh3vjtylgci
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceactg4qzwauvmd3gcppelb7hxucgfmfc3dodpwkdtitubye4edsn4

**Comment by cryptowhizzard** [comment]
checker:manualTrigger

**Comment by BobStaring** [comment]
checker:manualTrigger

**Comment by BobStaring** [comment]
checker:manualTrigger

**Comment by BobStaring** [comment]
checker:manualTrigger

**Comment by BobStaring** [comment]
checker:manualTrigger

**Comment by BobStaring** [comment]
checker:manualTrigger

**Comment by BobStaring** [comment]
checker:manualTrigger

**Comment by BobStaring** [comment]
checker:manualTrigger

**Comment by BobStaring** [comment]
checker:manualTrigger

**Comment by i0k24** [comment]
checker:manualTrigger

**Comment by igoovo** [comment]
It looks okay.
As for the retrieval rate, please continue to improve.

**Comment by igoovo** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb2dtw2yzlsbvw5azuavfr5p5ouuvbc7bnbiyhutqwd2bccr7icdq 
#### Address 
> f1gsvxh5lqvayqgaoxkjwie7swc2lgihgdgjdnaca
#### Datacap Allocated
> 500.00TiB
#### Signer Address
> f1shnsfayxqll77svffaxnjenms7bbbysbqcatrpy
#### Id
> 0277adc4-dce3-43a9-9a61-c7d7873eff04
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb2dtw2yzlsbvw5azuavfr5p5ouuvbc7bnbiyhutqwd2bccr7icdq

**Comment by sxxfuture-official** [comment]
2 report looks OK.

**Comment by sxxfuture-official** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceduvtmrrg7mc5aiyvhwxs47bkk5v6adpexvpwayupadox3uauwkya 
#### Address 
> f1gsvxh5lqvayqgaoxkjwie7swc2lgihgdgjdnaca
#### Datacap Allocated
> 500.00TiB
#### Signer Address
> f1foiomqlmoshpuxm6aie4xysffqezkjnokgwcecq
#### Id
> 0277adc4-dce3-43a9-9a61-c7d7873eff04
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceduvtmrrg7mc5aiyvhwxs47bkk5v6adpexvpwayupadox3uauwkya

**Comment by BobStaring** [comment]
checker:manualTrigger

**Comment by BobStaring** [comment]
checker:manualTrigger

**Comment by BobStaring** [comment]
keep

**Comment by BobStaring** [comment]
continue

**Comment by BobStaring** [comment]
continue

**Comment by cryptowhizzard** [comment]
Dear BobStaring,

As notary I am doing due diligence on your LDN. I could not get retrieval to work. Can you please upload the car file of CID baga6ea4seaqklgex4pdflnz2tqym2z7wm63zweiu3nocunci52ff4bpfg7ooaea ?

You can use our upload system at http://send.datasetcreators.com. Please select 7 days for the system to keep the file and post the link you received here so I (and other notaries) can download your content.

**Comment by BobStaring** [comment]
Hello @Sunnyiscoming this client is still in use.Please help us reopen it.

**Comment by BobStaring** [comment]
Hello @fabriziogianni7 @Sunnyiscoming this client is still in use.Please help us reopen it.

**Comment by cryptowhizzard** [comment]
> Dear BobStaring,
> 
> As notary I am doing due diligence on your LDN. I could not get retrieval to work. Can you please upload the car file of CID baga6ea4seaqklgex4pdflnz2tqym2z7wm63zweiu3nocunci52ff4bpfg7ooaea ?
> 
> You can use our upload system at http://send.datasetcreators.com. Please select 7 days for the system to keep the file and post the link you received here so I (and other notaries) can download your content.

Reminder.

**Comment by Sunnyiscoming** [comment]
Hello, @BobStaring per the https://github.com/filecoin-project/notary-governance/issues/922 for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

This information will be reviewed by Fil+ Governance team to confirm validity and then the application will be allowed to move forward for additional notary review.

**Comment by BobStaring** [comment]
Ok, Thanks Sunny，we will contact SP for corresponding information.

**Comment by BobStaring** [comment]
checker:manualTrigger

**Comment by BobStaring** [comment]
The cid sharing, we investigated, should be a cooperative SP, test data only 4TiB, shared our data externally. All partners have been notified, they should be careful not to share data  in the future.
There won't be any more.

**Comment by BobStaring** [comment]
checker:manualTrigger

**Comment by zcfil** [comment]
checker:manualTrigger

**Comment by zcfil** [comment]
![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/45065975/c4939612-592a-4503-a425-9600b3888674)
检索正常

**Comment by 1ane-1** [comment]
> The cid sharing, we investigated, should be a cooperative SP, test data only 4TiB, shared our data externally. All partners have been notified, they should be careful not to share data in the future. There won't be any more.

As for it is the test data and it is less than 10T that makes the mistake, i hope you don't cooperate with the SP in the future. Support for the current stage and check your report next time.

**Comment by 1ane-1** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceat2g2ewtzkvzliiag7d34ntlkzimxsrf5deo7kz5o7mrdo4rdlqm 
#### Address 
> f1gsvxh5lqvayqgaoxkjwie7swc2lgihgdgjdnaca
#### Datacap Allocated
> 500.00TiB
#### Signer Address
> f1mdk7s2vntzm6hu35yuo6vjubtrpfnb2awhgvrri
#### Id
> 0277adc4-dce3-43a9-9a61-c7d7873eff04
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceat2g2ewtzkvzliiag7d34ntlkzimxsrf5deo7kz5o7mrdo4rdlqm

**Comment by zcfil** [comment]
> The cid sharing, we investigated, should be a cooperative SP, test data only 4TiB, shared our data externally. All partners have been notified, they should be careful not to share data in the future. There won't be any more.

We will pay attention to the subsequent data allocation and reporting situation, please follow the relevant rules, and this round will support

**Comment by zcfil** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced4wvg6wpwpalo6ogpqkfjsjj7qzvunr6t5yky4drusjcmms5ptqi 
#### Address 
> f1gsvxh5lqvayqgaoxkjwie7swc2lgihgdgjdnaca
#### Datacap Allocated
> 500.00TiB
#### Signer Address
> f1cjzbiy5xd4ehera4wmbz63pd5ku4oo7g52cldga
#### Id
> 0277adc4-dce3-43a9-9a61-c7d7873eff04
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced4wvg6wpwpalo6ogpqkfjsjj7qzvunr6t5yky4drusjcmms5ptqi

**Comment by BobStaring** [comment]
@Sunnyiscoming Thanks , we have filled out the registration form.

**Comment by BobStaring** [comment]
checker:manualTrigger

**Comment by Sunnyiscoming** [comment]
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1890#issuecomment-1788765682
Yes. Received that.

**Comment by NiwanDao** [comment]
![321699253264_ pic_hd](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/72185104/6c91f903-fd05-41a3-a349-954880a664c0)
Manual Retrieval Test Passed

**Comment by NiwanDao** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedrzhj7hmrijc3dgbbrhnjdetlpro2bcsfnk2zdonlasg74l7kjru 
#### Address 
> f1gsvxh5lqvayqgaoxkjwie7swc2lgihgdgjdnaca
#### Datacap Allocated
> 500.00TiB
#### Signer Address
> f1a2lia2cwwekeubwo4nppt4v4vebxs2frozarz3q
#### Id
> 0277adc4-dce3-43a9-9a61-c7d7873eff04
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedrzhj7hmrijc3dgbbrhnjdetlpro2bcsfnk2zdonlasg74l7kjru

**Comment by SuperChaiChai** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecgktryypzaiwrcadwnykfv4levsyj7druburmbazksqjv3mlq3p6 
#### Address 
> f1gsvxh5lqvayqgaoxkjwie7swc2lgihgdgjdnaca
#### Datacap Allocated
> 500.00TiB
#### Signer Address
> f12mckci3omexgzoeosjvstcfxfe4vqw7owdia3da
#### Id
> 0277adc4-dce3-43a9-9a61-c7d7873eff04
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecgktryypzaiwrcadwnykfv4levsyj7druburmbazksqjv3mlq3p6

**Comment by herrehesse** [comment]
![Screenshot 2023-11-10 at 13 35 32](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/70132857/5d75c8e4-2304-4f97-9880-90aa7ddaf530)

Entity is fully self-dealing and hiding under VPN. Thanks for signing this shit again abusive notaries, thank you.

@kevzak Please close this asap and remove cap.

**Comment by BobStaring** [comment]
checker:manualTrigger

**Comment by herrehesse** [comment]
Entity is fully self-dealing and hiding under VPN. Thanks for signing this shit again abusive notaries, thank you.

@kevzak Please close this asap and remove cap.

**Comment by Sunnyiscoming** [comment]
Hello, @BobStaring per the https://github.com/filecoin-project/notary-governance/issues/922 for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

This information will be reviewed by Fil+ Governance team to confirm validity and then the application will be allowed to move forward for additional notary review.

**Comment by BobStaring** [comment]
<img width="366" alt="图片" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/116865016/dfe3b4b0-bb28-4a07-a1f6-9ebbc76e0c94">

Hello, @Sunnyiscoming we have submited the form , please check it.

**Comment by herrehesse** [comment]
checker:manualTrigger

**Comment by herrehesse** [comment]
@BobStaring why aren't you replying on my question? I found multiple entities sealing huge amounts of datacao with false locations under VPN. Suggest halting this LDN before more information is public.

![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/70132857/b3890e8a-14ec-498c-be52-2c704fd88e95)

**Comment by Filplus-govteam** [comment]
SPs taking deals:

f02836485 | Chengdu, Sichuan, CNChina Mobile Communications Group Co., Ltd. | 85.56 TiB | 10.28% | 85.56 TiB | 0.00%
f02092901 | Shanghai, Shanghai, CNChina Telecom (Group) | 39.06 TiB | 4.69% | 39.06 TiB | 0.00%
f02029115 | Shanghai, Shanghai, CNChina Telecom (Group) | 39.03 TiB | 4.69% | 39.03 TiB | 0.00%
f02229707new | Hong Kong, Central and Western, HKChina Unicom Global | 71.57 TiB | 8.60% | 71.57 TiB | 0.00%
f02236570 | Hong Kong, Central and Western, HKChina Unicom Global | 41.45 TiB | 4.98% | 41.45 TiB | 0.00%
f02237709 | Hong Kong, Central and Western, HKChina Unicom Global | 41.29 TiB | 4.96% | 41.29 TiB | 0.00%
f02825666 | Shenzhen, Guangdong, CNCHINANET-BACKBONE | 41.06 TiB | 4.93% | 41.06 TiB | 0.00%
f02132642 | Singapore, Singapore, SGSingNet | 174.84 TiB | 21.01% | 174.84 TiB | 0.00%
f02236033new | Singapore, Singapore, SGThe Constant Company, LLC | 48.37 TiB | 5.81% | 48.37 TiB | 0.00%
f02182251 | Stockholm, Stockholm, SEThe Constant Company, LLC | 39.09 TiB | 4.70% | 39.03 TiB | 0.16%
f02827777 | Mumbai, Maharashtra, INThe Constant Company, LLC | 35.25 TiB | 4.24% | 35.25 TiB | 0.00%
f02826888 | Toronto, Ontario, CAThe Constant Company, LLC | 34.63 TiB | 4.16% | 34.63 TiB | 0.00%
f02238701new | Los Angeles, California, USUCLOUD INFORMATION TECHNOLOGY (HK) LIMITED | 46.17 TiB | 5.55% | 46.17 TiB | 0.00%
f01981571 | London, England, GBUCLOUD INFORMATION TECHNOLOGY (HK) LIMITED | 39.09 TiB | 4.70% | 39.09 TiB | 0.00%
f02098007 | Singapore, Singapore, SGUCLOUD INFORMATION TECHNOLOGY (HK) LIMITED | 34.47 TiB | 4.14% | 34.34 TiB | 0.36%
f02237106 | London, England, GBUCLOUD INFORMATION TECHNOLOGY (HK) LIMITED | 21.39 TiB | 2.57% | 21.39 TiB | 0.00%

SPs listed upfront:

**f02132642** | laura |SingaporeSingapore | no | none
**f02229707** | elio |HongKong | no | Elio
**f02092901** | Zhengcheng | Chia | no | Cheng
**f02098007** | Jiezhou | SingaporeSingapore | no | none
**f02238701** | joe |  US | no | Joe

Not all SPs match - not all SPs provided have emails or contact to confirm entity and location. Closing until updated
