### ISSUE TITLE
[DataCap Application] NIH NCBI Sequence Read Archive (SRA) src-2

### ISSUE THREAD

**Issue by AgeeWeb3** [filecoin-project/filecoin-plus-large-datasets#1898]
### Data Owner Name

National Library of Medicine (NLM)

### Data Owner Country/Region

United States

### Data Owner Industry

Life Science / Healthcare

### Website

https://www.ncbi.nlm.nih.gov/sra/docs/sra-cloud/

### Social Media

```text
https://www.nlm.nih.gov/
https://twitter.com/NLM_NIH
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

800TiB

### On-chain address for first allocation

f1bphonqcrdq3imr44y53cuowtmq6a3eqa6qp5joy

### Data Type of Application

None

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
I had participated in hackathon, and after learning about it I discovered filecoin and interested in it. Also, I took part in Slingshot and keep an eye on the community for a long time.
Project: The Sequence Read Archive (SRA), produced by the National Center for Biotechnology Information (NCBI) at the National Library of Medicine (NLM) at the National Institutes of Health (NIH), stores raw DNA sequencing data and alignment information from high-throughput sequencing platforms. The SRA provides open access to these biological sequence data to support the research community's efforts to enhance reproducibility and make new discoveries by comparing data sets. Buckets in this registry contain public SRA data in the original (user submitted) format from select high value and newly-released studies as well as all public-access SRA formatted ETL+BQS data. Also included is all SRA metadata that can be leveraged for attribute-based data discovery.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
.bam, .cram, and .fastq files in a public S3 bucket. This is the second of two S3 buckets for source submissions from sequencing methodologies such as PacBio, Oxford Nanopore Technologies, and 10X Genomics.
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### How do you plan to prepare the dataset

lotus, singularity

### Please share a sample of the data

```text
aws s3 ls --no-sign-request s3://sra-pub-src-2/
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Sporadic

### For how long do you plan to keep this dataset stored on Filecoin

1 to 1.5 years

### In which geographies do you plan on making storage deals

Asia other than Greater China, North America, Greater China

### How will you be distributing your data to storage providers

HTTP or FTP server, Shipping hard drives, Lotus built-in data transfer

### How do you plan to choose storage providers

Slack, Filmine, Big data exchange

### How do you plan to make deals to your storage providers

Lotus client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 5PiB

**Expected weekly DataCap usage rate**
> 800TiB

**Client address**
>f1bphonqcrdq3imr44y53cuowtmq6a3eqa6qp5joy

**Comment by cryptowhizzard** [comment]
Dear @AgeeWeb3 ,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Looking at your application i have some questions:
As you are brand new on Github and have no history of past applications. Can you give me an introduction who you are and an introduction about your company?

What hardware do you have over there to prepare this dataset? What is your internet connection speed? Do you already have the data downloaded on the premises?

It seems to me that applying for 5PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?

Can you show us some visible proof of the size of your data and the storage / packing hardware you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230337462961356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!

**Comment by Casey-PG** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedhf3k7ouk3xrf6ul2rflfyqgvx3rmce5bbpidcp6i5wldi5bkf4i 
#### Address 
> f1bphonqcrdq3imr44y53cuowtmq6a3eqa6qp5joy
#### Datacap Allocated
> 256.00TiB
#### Signer Address
> f1d4yb3wags3mtddzesxoo63jv7dmlec3bq4yteni
#### Id
> e4ff31cc-e90f-4074-87ad-5c4b96689329
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedhf3k7ouk3xrf6ul2rflfyqgvx3rmce5bbpidcp6i5wldi5bkf4i

**Comment by Casey-PG** [comment]
Since this is currently the first round of applications, there are no bot check results available for review. We believe this application meets the Fil+ criteria based on the applicant's description and the distribution plan.

**Comment by BobbyChoii** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecrantnxqr5vlcnvrm53rktcejypqxqhibdn3nm545pj5jnhy3bvi 
#### Address 
> f1bphonqcrdq3imr44y53cuowtmq6a3eqa6qp5joy
#### Datacap Allocated
> 256.00TiB
#### Signer Address
> f1irqs2gmctiv3jcdfwuch7oxvf4ixh3k4b2wc24i
#### Id
> e4ff31cc-e90f-4074-87ad-5c4b96689329
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecrantnxqr5vlcnvrm53rktcejypqxqhibdn3nm545pj5jnhy3bvi

**Comment by Meibuy** [comment]
We did due diligence on this application previously. So far the report looks good,  we'll keep tracking the datacap allocation flow.

**Comment by Meibuy** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacean3isuanlgtbafj7tlb2ev6vaeygll6mpudasbiyql3qxs3ciyfq 
#### Address 
> f1bphonqcrdq3imr44y53cuowtmq6a3eqa6qp5joy
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f1bwugfihrmn3iyunzyxst5nttql3dge4khwmurtq
#### Id
> c7cb6043-d819-439d-8c27-3d7c60b914ae
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacean3isuanlgtbafj7tlb2ev6vaeygll6mpudasbiyql3qxs3ciyfq

**Comment by AthSmith** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacealmficek7pdjtg7g2iluct3pnmd6h36mzvooza6zxm4lhwl73a3g 
#### Address 
> f1bphonqcrdq3imr44y53cuowtmq6a3eqa6qp5joy
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f1vxbqrf7rfum3n6m5u6eb4re6xj7amvsaqnzu64y
#### Id
> c7cb6043-d819-439d-8c27-3d7c60b914ae
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacealmficek7pdjtg7g2iluct3pnmd6h36mzvooza6zxm4lhwl73a3g

**Comment by TakiChain** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecypw6526zl2gsmquuqqvot4wlebcfrbmxsg56vn523ebsnslr5ko 
#### Address 
> f1bphonqcrdq3imr44y53cuowtmq6a3eqa6qp5joy
#### Datacap Allocated
> 1.00PiB
#### Signer Address
> f15impf3j2zcaex4lhyxndxswuuhv24vzstuqtxsi
#### Id
> 8b1b9e8c-4e97-4b44-9063-6a9030ef1252
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecypw6526zl2gsmquuqqvot4wlebcfrbmxsg56vn523ebsnslr5ko

**Comment by BobbyChoii** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceavemfvmjiptlig6k2niwjtlre3itt5q2ad66lz5hfqfh4yctrrgm 
#### Address 
> f1bphonqcrdq3imr44y53cuowtmq6a3eqa6qp5joy
#### Datacap Allocated
> 1.00PiB
#### Signer Address
> f1irqs2gmctiv3jcdfwuch7oxvf4ixh3k4b2wc24i
#### Id
> 8b1b9e8c-4e97-4b44-9063-6a9030ef1252
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceavemfvmjiptlig6k2niwjtlre3itt5q2ad66lz5hfqfh4yctrrgm

**Comment by BobbyChoii** [comment]
Public data with clear allocation plan, we are willing to help onboard more valuable dataset.

**Comment by Aifabot-Cloud** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb4blsi3qh7nixyjxp56jx7kdfikx5qi2pveds2no2slvnul4fnn4 
#### Address 
> f1bphonqcrdq3imr44y53cuowtmq6a3eqa6qp5joy
#### Datacap Allocated
> 2.00PiB
#### Signer Address
> f174fg3bqbln3zjnkxtyf6s54txqkr7yqkj6cig7y
#### Id
> 9a015486-2afa-4f4b-a519-47fdbfd2dfa1
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb4blsi3qh7nixyjxp56jx7kdfikx5qi2pveds2no2slvnul4fnn4

**Comment by Aifabot-Cloud** [comment]
Open datasets bring great value to the network. Happy to see more of them join Filecoin. Please keep the allocation in line with Filplus guidlines.

**Comment by Normalnoise** [comment]
checker:manualTrigger

**Comment by AgeeWeb3** [comment]
remain open please

**Comment by AgeeWeb3** [comment]
Yes, i want

**Comment by cryptowhizzard** [comment]
checker:manualTrigger

**Comment by cryptowhizzard** [comment]
Hi @AgeeWeb3 

Any chance this data will become retrieval according to the FIL+ rules and guidelines?

**Comment by Filplus-govteam** [comment]
Hello @AgeeWeb3 per the https://github.com/filecoin-project/notary-governance/issues/922 for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

This information will be reviewed by Fil+ Governance team to confirm validity and then the application will be triggered for notary review. Let us know if you have any questions.

**Comment by cryptowhizzard** [comment]
<img width="1032" alt="Scherm­afbeelding 2023-07-27 om 09 30 26" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/36404435/c7ffdfb7-fd9a-47b8-afee-381ed15566fc">

I tried dozens of retrievals on this client. None of these are working. 

@AgeeWeb3 Why are your SP's not proving retrieval and why don't they store unsealed sectors / provide readily retrieval according to FIL+ rules and guidelines?

**Comment by AgeeWeb3** [comment]
@cryptowhizzard 
![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/122510851/e2f644e7-6d46-4686-9dd0-bfc1c19e6112)
![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/122510851/7125ba3d-0ef8-4efd-b174-8949714f3372)

I've tried to do some retrieval in the dashboard. Actually they support retrieval. They do obey FIL+ rules and guidelines. Please do some check again! Thank you!

**Comment by cryptowhizzard** [comment]
That dashboard is only testing the first few bytes , not a whole file.

**Comment by cryptowhizzard** [comment]
But , we can fix this another way;

1898-f02130652-f02251709-47283103-baga6ea4seaqjjz35gacierq5iqmpyvchw34rsxmk3kre6budz5indjzscswiifi.log

Can you make baga6ea4seaqjjz35gacierq5iqmpyvchw34rsxmk3kre6budz5indjzscswiifi available for download so i can see the contents of the file? We can do our due diligence then.

**Comment by AgeeWeb3** [comment]
Thank you for your hard work. We support http retrieval for download. You can try it!

**Comment by cryptowhizzard** [comment]
> Thank you for your hard work. We support http retrieval for download. You can try it!

You are welcome.

/usr/local/bin/boost provider retrieval-transports f02251709
Error: failed to fetch transports from peer 12D3KooWQkvqFDGYrL5Jpf1JVHxmQ3Vndj72rjSFqPNHa6CdqWfR: exhausted 5 attempts but failed to open stream, err: protocols not supported: [/fil/retrieval/transports/1.0.0]

**Comment by cryptowhizzard** [comment]
Btw , nothing wrong with my setup: -> 

boost provider retrieval-transports f02033496
libp2p
  /ip4/212.6.53.51/tcp/24002
  /ip6/2a10:2080::51/tcp/24002
http
  /dns/f02033496.datasetcreators.com/tcp/80/http
    http://f02033496.datasetcreators.com:80
bitswap
  /ip4/212.6.53.51/tcp/8888/p2p/12D3KooWRPfVRXRzEsSrJVhcu616vniJF8zQbuBN87skKdh93CbM

Query of SP's works. Just yours don't.

**Comment by AgeeWeb3** [comment]
![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/122510851/efcbbeed-a685-4794-bdb2-31382c7955f3)
It can be retrieved! As the pic shows, you can try it again.

**Comment by cryptowhizzard** [comment]
Hi @AgeeWeb3 

The miners you are using are involved in CID sharing and have retrieval disabled. You can see the issue numbers in the auditTrail column and check yourself if you want.

If you need any more information let me know.

![Scherm­afbeelding 2023-07-31 om 13 19 33](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/36404435/27fa978c-11ee-433d-b50c-5be51fe79967)

**Comment by AgeeWeb3** [comment]
@cryptowhizzard We've tried to checked and it do support retrieval. Such as f01122339. Maybe you need to check your program. Welcome check for the result.

**Comment by cryptowhizzard** [comment]
cat 1898-f02130652-f02251709-47283103-baga6ea4seaqjjz35gacierq5iqmpyvchw34rsxmk3kre6budz5indjzscswiifi.log
Recv 0 B, Paid 0 FIL, Open (New), 20m11.855s [1690024162200370573|0]
Recv 0 B, Paid 0 FIL, DealProposed (WaitForAcceptance), 20m11.862s [1690024162200370573|0]
Recv 0 B, Paid 0 FIL, DealAccepted (Accepted), 20m11.974s [1690024162200370573|0]
Recv 0 B, Paid 0 FIL, PaymentChannelSkip (Ongoing), 20m11.985s [1690024162200370573|0]

Dead from here. 

Piece ID : baga6ea4seaqjjz35gacierq5iqmpyvchw34rsxmk3kre6budz5indjzscswiifi
SP : f02251709
Deal ID : 47283103

**Comment by AgeeWeb3** [comment]
@cryptowhizzard Can you do some http retrieval for checking sp?

**Comment by Wengeding** [comment]
checker:manualTrigger

**Comment by Wengeding** [comment]
have done DD with the applicant, report looks normal to me. some indicators could be improved a bit more.

**Comment by Wengeding** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecuwjwdsmwq4dzizagxz43awo3stpe524xpzq6vlrkrazlqbym37m 
#### Address 
> f1bphonqcrdq3imr44y53cuowtmq6a3eqa6qp5joy
#### Datacap Allocated
> 1.25PiB
#### Signer Address
> f1txfsjmix4vlzido4dkildrnbw26owtlbslexmpa
#### Id
> bd991f4f-800b-435e-a2a0-bfd19a15752c
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecuwjwdsmwq4dzizagxz43awo3stpe524xpzq6vlrkrazlqbym37m

**Comment by Casey-PG** [comment]
Based on the chat history and fellow notaries' reviews, I would like to help this application moving forward. Please follow the feedback and update us if there's any change or if you need any help.

**Comment by Casey-PG** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebrngybzx2tbdh6cckhexlop3mbvaqmqisjkotaelspnau5r6n7uo 
#### Address 
> f1bphonqcrdq3imr44y53cuowtmq6a3eqa6qp5joy
#### Datacap Allocated
> 1.25PiB
#### Signer Address
> f1d4yb3wags3mtddzesxoo63jv7dmlec3bq4yteni
#### Id
> bd991f4f-800b-435e-a2a0-bfd19a15752c
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebrngybzx2tbdh6cckhexlop3mbvaqmqisjkotaelspnau5r6n7uo

**Comment by raghavrmadya** [comment]
As the client has not responded to the evidence provided above in relation to this dispute - https://www.notion.so/filecoin/Applicant-storing-garbage-data-ea97ba7dacd2466d80d4b86276579b10?pvs=4

This application is being closed and flagged for DC removal
