### ISSUE TITLE
[DataCap Application] LFCS

### ISSUE THREAD

**Issue by luhui5** [filecoin-project/filecoin-plus-large-datasets#1899]
### Data Owner Name
LFCS

### Data Owner Country/Region
China

### Data Owner Industry
IT & Technology Services

### Website
[lfcs.com](lfcs.com)

### Social Media
@Leehoom1803 (@Leehoom1803)

### Total amount of DataCap being requested
100 TiB

### Weekly allocation of DataCap requested
3 TiB

### On-chain address for first allocation
f3si75js4pynidohaevw5vauz7zo5bhxjrptcpq3e37x23qf4oi2bqnooqachxk4pvm7liepr3jdevgo7boptq

### Data Type of Application
Slingshot

### Custom multisig
No

### Share a brief history of your project and organization
Apply for a dc.I'm running a lotus miner.

### Is this project associated with other projects/ecosystem stakeholders?
No

### Describe the data being stored onto Filecoin
Store the dc sectors on miner.

### Where was the data currently stored in this dataset sourced from
My own storage infra

### How do you plan to prepare the dataset
lotus

### Please share a sample of the data
yes

### Confirm that this is a public dataset that can be retrieved by anyone on the Network
Yes

### What is the expected retrieval frequency for this data
Weekly

### For how long do you plan to keep this dataset stored on Filecoin
1 to 1.5 years

### In which geographies do you plan on making storage deals
Asia other than Greater China

### How will you be distributing your data to storage providers
Lotus built-in data transfer

### How do you plan to choose SP
Slack

### If you already have a list of storage providers to work with, fill out their names and provider IDs below
f040218

### How do you plan to make deals to your storage providers
Lotus client

### Can you confirm that you will follow the Fil+ guideline
Yes

_Application created via [filplus.storage](https://filplus.storage)_

**Comment by Sunnyiscoming** [comment]
The minimum dataset size required for fil+ large dataset is 500 TB. If you want to apply for 100 TB, you can get DataCap by making a request to a Notary - you can find a list of active Notaries on the [Filecoin Plus Registry](https://plus.fil.org/verifiers).

**Comment by Sunnyiscoming** [comment]
It will be closed if there is no reply in 3 days.
