### ISSUE TITLE
[DataCap Application] please delete

### ISSUE THREAD

**Issue by yiheng1116** [filecoin-project/filecoin-plus-large-datasets#19]
# Large Dataset Notary Application

To apply for a DataCap allocation for your dataset, please fill out the following information.

## Core Information
- Organization Name: 
- Website / Social Media:
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):
- On-chain address for first allocation:

_Please respond to the questions below in pargraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

## Project details

Share a brief history of your project and organization.
```
Please answer here.
```

What is the primary source of funding for this project?
```
Please answer here.
```

What other projects/ecosystem stakeholders is this project associated with?
```
Please answer here.
```

## Use-case details

Describe the data being stored onto Filecoin
```
Please answer here.
```

Where was the data in this dataset sourced from?
```
Please answer here.
```

Can you share a sample of what is in the dataset? A link to a file, an image, a table, etc., are good examples of this. 
```
Please answer here.
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Please answer here.
```

What is the expected retrieval frequency for this data?
```
Please answer here.
```

For how long do you plan to keep this dataset stored on Filecoin? Will this be a permanent archival or a one-time storage deal?
```
Please answer here.
```

## DataCap allocation plan

In which geographies do you plan on making storage deals?
```
Please answer here.
```

What is your expected data onboarding rate? How many deals can you make in a day, in a week? How much DataCap do you plan on using per day, per week?
```
Please answer here.
```

How will you be distributing your data to miners? Is there an offline data transfer process?
```
Please answer here.
```

How do you plan on choosing the miners with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
Please answer here.
```

How will you be distributing data and DataCap across miners storing data?
```
Please answer here.
```

**Comment by dkkapur** [comment]
Closed this per request in title
