### ISSUE TITLE
[DataCap Application]Video++Jiliantech

### ISSUE THREAD

**Issue by quinn463** [filecoin-project/filecoin-plus-large-datasets#190]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Jiliantech
- Website / Social Media:www.videojj.com
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):200TiB
- On-chain address for first allocation:f1fi7vzu266bh7yxsygw6scl2hjltdkhfb6nyzn3a

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Jilian Technology Development Group Co., Ltd. was founded in October 2014 in Shanghai, China, focusing on technology and consumption. It owns Jilian AI Cloud, TAKIPLAY Script Killing, TakiToys Trendy Toys, TakiLucky Entertainment Retail, Video++ Linglian Marketing, and Jilian Technology. In addition to online businesses such as technology, the chain is actively deploying offline consumer entities and has 20+ physical brand stores directly operated by TakiLucky and TakiPlay. The main investors of Jilian Technology Group include Alibaba, Yunfeng Fund, Megvii Technology Face++, Ubisoft, SDIC Fund, K11 Hong Kong New World, etc., have received nearly 1 billion yuan in financing and have grown into a company with leading technology. It has been to a comprehensive business technology company with a large number of users and comprehensive revenue capabilities.
```

What is the primary source of funding for this project?
```
Our main investors of Jilian Technology Group include Alibaba, Yunfeng Fund, Megvii Technology Face++, Ubisoft, SDIC Fund, K11 Hong Kong New World, etc.
```

What other projects/ecosystem stakeholders is this project associated with?
```
No other stakeholders.
```

## Use-case details

Describe the data being stored onto Filecoin
```
We peovide a platform and users can upload their data to storage on it. Such as video clips has been exhaustively annotated by human annotators, data which is stored in a very simple file format designed for storing vectors and multidimensional matrices, UCSD Anomaly Detection Dataset and so on.
```

Where was the data in this dataset sourced from?
```
Users(mostly AI developers) will upload their datasets into our AI cloud.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
Yes.
[ava_v2.2.zip](https://github.com/filecoin-project/filecoin-plus-large-datasets/files/7814008/ava_v2.2.zip)
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes, we confirm that this is a public dataset that can be retrieved by anyone on the Network.
```

What is the expected retrieval frequency for this data?
```
It won't be retrieved very often because of the amount of data.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
5 years at least. We will have a try to store a long time.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Asia.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Online data transfer process. If there is a need, we can change it into offline data transfer process.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We pay attention to their work time and how much they cost.  We need comprehensive storage providers who can coorperate for a long time.
```

How will you be distributing deals across storage providers?
```
We will distribute different deals according to their distance. 
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
We're ready for making deals.
```

**Comment by darrellhendershot** [comment]
Looks interesting! 

More and more IT companies realized the value of the Filecoin network. 

Any autonomous driving data do you have? Are you wish to share it with community members all over the world?

**Comment by quinn463** [comment]
No, we don't. We've got datasets such as traffic lights recognition, parking slot dataset, mappillaryvistas datasets and so on. We would share our datasets with community members because the datasets we store are public.

**Comment by swatchliu** [comment]
Interested in your biz~  Could you help to arrange a visit to your office?

**Comment by quinn463** [comment]
Welcome! We are located at Shanghai! Welcome to coming!!

**Comment by swatchliu** [comment]
Happy to support if RKH passed your issue.

**Comment by galen-mcandrew** [comment]
## Multisig Notary requested
#### Total DataCap requested 
> 5PiB
#### Expected weekly DataCap usage rate 
> 200TiB

**Comment by quinn463** [comment]
Was this RKH broken? @galen-mcandrew I can't get into the next step about multisig. How can I do about it?

**Comment by XnMatrixSV** [comment]
How did you hear about the FIL+ program? Do you have a good understanding of the network and/or are involved in the web3.0 community?

**Comment by XnMatrixSV** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceblcrkvxytrfzfkxsf5lxaofltxyenmouaafc4nbpq2y5jfihs3x2 
#### Address 
> f1fi7vzu266bh7yxsygw6scl2hjltdkhfb6nyzn3a
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1yuz2twsllparyfqwslfiuxrc5wj4mfiflvnsw6a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceblcrkvxytrfzfkxsf5lxaofltxyenmouaafc4nbpq2y5jfihs3x2

**Comment by TimWilliams00** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedmmbszqeudy27klneh5cye7f5vvshyrcrc3rhlle6qxrramipc52 
#### Address 
> f1fi7vzu266bh7yxsygw6scl2hjltdkhfb6nyzn3a
#### Datacap Allocated
> 100TiB
#### Signer Address
> f1fkxkfxgopjf3ufnfg5i3m6qlwf73kp4w5zz7nnq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedmmbszqeudy27klneh5cye7f5vvshyrcrc3rhlle6qxrramipc52

**Comment by quinn463** [comment]
- @XnMatrixSV The first time I heard of FIL+ program is from my clients who wanted to get storage and had made a research. Now I'm very familiar with filecoin and I have experience in storing in the filecoin.

**Comment by quinn463** [comment]
@XnMatrixSV The first time I heard of FIL+ program is from my clients who wanted to get storage and had made a research. Now I'm very familiar with filecoin and I have experience in storing in the filecoin.

**Comment by quinn463** [comment]
@XnMatrixSV Hey! The first time I heard of FIL+ program is from my clients who wanted to get storage and had made a research. Now I'm very familiar with filecoin and I have experience in storing in the filecoin.

**Comment by rayshitou** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced4q5cqvxy2tjcegnug3rqhlynvd6loqhin2vbnzryknfsjgwmccy 
#### Address 
> f1fi7vzu266bh7yxsygw6scl2hjltdkhfb6nyzn3a
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f136bz32l2hlyad4npmfg5dngcdw3jk3tpcpoz2ja
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced4q5cqvxy2tjcegnug3rqhlynvd6loqhin2vbnzryknfsjgwmccy

**Comment by Fenbushi-Filecoin** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaubm2njwawolnt7epyflm3lhg4vsuku4xvtkchywsxmngqr2elpc 
#### Address 
> f1fi7vzu266bh7yxsygw6scl2hjltdkhfb6nyzn3a
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1yqydpmqb5en262jpottko2kd65msajax7fi4rmq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaubm2njwawolnt7epyflm3lhg4vsuku4xvtkchywsxmngqr2elpc

**Comment by XnMatrixSV** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaci6f4dd6hywuyja4u4hareqs4uqupxxdmscyh3mkffpx4n4pva4 
#### Address 
> f1fi7vzu266bh7yxsygw6scl2hjltdkhfb6nyzn3a
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1yuz2twsllparyfqwslfiuxrc5wj4mfiflvnsw6a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaci6f4dd6hywuyja4u4hareqs4uqupxxdmscyh3mkffpx4n4pva4

**Comment by DarnellWashington** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacea4if25ousdfhtbdjwlu5tneb2cdg35cuqczeizhnninm6vftguec 
#### Address 
> f1fi7vzu266bh7yxsygw6scl2hjltdkhfb6nyzn3a
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1bjdcjxha3ldcstw5zmvkyu3r2p5x2bsm745kgsi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacea4if25ousdfhtbdjwlu5tneb2cdg35cuqczeizhnninm6vftguec

**Comment by MRJAVAZHAO** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebw46prlqsf5hvbbfyq5zkksopyye4l2gj3vai7v75aipleyjpv2s 
#### Address 
> f1fi7vzu266bh7yxsygw6scl2hjltdkhfb6nyzn3a
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f14gme3f52prtyzk6pblogrdd6b6ivp4swc6qmesi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebw46prlqsf5hvbbfyq5zkksopyye4l2gj3vai7v75aipleyjpv2s

**Comment by swatchliu** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedh6vehvnxtf423rncu5auejcotl5mwd4kgjbzqta3xqwoqtkjogs 
#### Address 
> f1fi7vzu266bh7yxsygw6scl2hjltdkhfb6nyzn3a
#### Datacap Allocated
> 1.56PiB
#### Signer Address
> f1yh6q3nmsg7i2sys7f7dexcuajgoweudcqj2chfi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedh6vehvnxtf423rncu5auejcotl5mwd4kgjbzqta3xqwoqtkjogs

**Comment by Fenbushi-Filecoin** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecgaia4lxecjm6jrel24mki7eloodyklkdz362asrhsj2ltn6fj2s 
#### Address 
> f1fi7vzu266bh7yxsygw6scl2hjltdkhfb6nyzn3a
#### Datacap Allocated
> 1.56PiB
#### Signer Address
> f1yqydpmqb5en262jpottko2kd65msajax7fi4rmq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecgaia4lxecjm6jrel24mki7eloodyklkdz362asrhsj2ltn6fj2s

**Comment by quinn463** [comment]
@galen-mcandrew @fabriziogianni7 Hello, my datacap is used up soon. It seems that bot should open the next round signature. Can you help me check it?

**Comment by rayshitou** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacea2kvhdfowugkdj2nov4y4rfy6frfgy33vae4fbtdcw7w4qtmitxy 
#### Address 
> f1fi7vzu266bh7yxsygw6scl2hjltdkhfb6nyzn3a
#### Datacap Allocated
> 1.56PiB
#### Signer Address
> f136bz32l2hlyad4npmfg5dngcdw3jk3tpcpoz2ja
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacea2kvhdfowugkdj2nov4y4rfy6frfgy33vae4fbtdcw7w4qtmitxy

**Comment by TimWilliams00** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecs6weg6u34ybl6xmerv77mbz7i7tzgmsecldxheoaxn5fk5ucm3w 
#### Address 
> f1fi7vzu266bh7yxsygw6scl2hjltdkhfb6nyzn3a
#### Datacap Allocated
> 1.56PiB
#### Signer Address
> f1fkxkfxgopjf3ufnfg5i3m6qlwf73kp4w5zz7nnq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecs6weg6u34ybl6xmerv77mbz7i7tzgmsecldxheoaxn5fk5ucm3w

**Comment by XnMatrixSV** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedeci4cee7ptykt2bj4kecix456gl65f76faionzvgw742tqcn5je 
#### Address 
> f1fi7vzu266bh7yxsygw6scl2hjltdkhfb6nyzn3a
#### Datacap Allocated
> 425.12TiB
#### Signer Address
> f1yuz2twsllparyfqwslfiuxrc5wj4mfiflvnsw6a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedeci4cee7ptykt2bj4kecix456gl65f76faionzvgw742tqcn5je

**Comment by Fenbushi-Filecoin** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceayhgoybtlhc27wso4vbkgmn6wypqvfdbptt3h7motaxsf22coxce 
#### Address 
> f1fi7vzu266bh7yxsygw6scl2hjltdkhfb6nyzn3a
#### Datacap Allocated
> 425.12TiB
#### Signer Address
> f1yqydpmqb5en262jpottko2kd65msajax7fi4rmq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceayhgoybtlhc27wso4vbkgmn6wypqvfdbptt3h7motaxsf22coxce
