### ISSUE TITLE
[DataCap Application] <Max study abroad consultant company> 

### ISSUE THREAD

**Issue by shimanmanya** [filecoin-project/filecoin-plus-large-datasets#1900]
### Data Owner Name

Max study abroad consultant company

### Data Owner Country/Region

China

### Data Owner Industry

Education & Training

### Website

www.maxchuguo.com

### Social Media

```text
Tik Tok：https://v.douyin.com/St6oxHc/

Himalayas：https://xima.tv/1_4Re3Ua?_sonic=0
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

500TiB

### On-chain address for first allocation

f1gg5dvu33z36erx5yinelesxkudovfrz3zyqm4py

### Data Type of Application

None

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Shenzhen Max Study Abroad Consulting Co., Ltd. is a well-known immigration firm from North America. It has gathered decades of international senior personnel. It is a trusted professional immigration firm in North America, Europe, Oceania, Asia and other countries and regions. mechanism. Since its inception, we have provided thousands of companies from all over the world with one-stop services ranging from children studying abroad to global asset allocation. We have always been adhering to an international service concept, based on our own authority and expertise, and taking the interests of customers as the starting point, to customize a comprehensive configuration of overseas identity, assets and education for each customer, and to serve China wholeheartedly. To serve the elites of the world and help global citizens in the new era to become who they love.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
The content includes the application materials of customers applying for visas of various countries, background introduction, and when helping customers submit applications, they need to help write and submit graphic and video materials to prove that customers have immigration qualifications. Our company is based on the immigration policies of various countries. The graphic materials provided, as well as the videos that our company will release in external marketing promotion.
```

### Where was the data currently stored in this dataset sourced from

Other

### If you answered "Other" in the previous question, enter the details here

```text
Baidu cloud
```

### How do you plan to prepare the dataset

IPFS

### Please share a sample of the data

```text
Link: https://pan.baidu.com/s/1O0SDxmdIp2p5jMFZ8zcBAA

Extraction code: vuyk
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Monthly

### For how long do you plan to keep this dataset stored on Filecoin

More than 3 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, Africa, North America, South America, Europe, Australia (continent)

### How will you be distributing your data to storage providers

Cloud storage (i.e. S3), HTTP or FTP server, IPFS

### How do you plan to choose storage providers

Filmine

### How do you plan to make deals to your storage providers

Boost client, Lotus client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by shimanmanya** [comment]
My account has been officially flagged by github, so I have to reapply for the project.

**Comment by Sunnyiscoming** [comment]
Could you send an email to filplus-app-review@fil.org with your official domain in order to confirm your identity? Email name should includes the issue id #1900.

**Comment by Sunnyiscoming** [comment]
![image](https://user-images.githubusercontent.com/105098820/231463873-ef1f5531-b594-43c6-aa86-17814e88fec6.png)
The email address is not ok. Please use email address ended by @eb3usa.com and contact me.

**Comment by Sunnyiscoming** [comment]
It will be closed if there is no reply in 3 days.

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 5PiB

**Expected weekly DataCap usage rate**
> 500TiB

**Client address**
>f1gg5dvu33z36erx5yinelesxkudovfrz3zyqm4py

**Comment by simonkim0515** [comment]
## Datacap Request Trigger

#### Total DataCap requested 
> 5PiB

#### Expected weekly DataCap usage rate 
> 500TiB 

#### Client address
> f1gg5dvu33z36erx5yinelesxkudovfrz3zyqm4py

**Comment by zcfil** [comment]
Can you provide more data samples to prove the need for 5P LDN.

**Comment by shimanmanya** [comment]
@zcfil Sorry to reply you so late. We have uploaded the material. The link is: 
Link: https://pan.baidu.com/s/1O0SDxmdIp2p5jMFZ8zcBAA

Extraction code: vuyk

Please check.

**Comment by shimanmanya** [comment]
Hello, I want to ask why this is closed, because I have already answered all the previous questions.

**Comment by shimanmanya** [comment]
@cryptowhizzard @zcfil @fabriziogianni7 @simonkim0515 @galen-mcandrew Hello, I would like to ask why is it closed? I have submitted information and answered questions.

**Comment by shimanmanya** [comment]
Hello, can I resubmit this application? Or open this closed application? @cryptowhizzard @zcfil @fabriziogianni7 @simonkim0515 @galen-mcandrew

**Comment by shimanmanya** [comment]
> 此应用程序在过去 14 天内未收到任何回复，因此目前已关闭。如果相关，请随时重新打开，或者随时为 DataCap 启动新的应用程序。谢谢你！

Hello, I want to ask why this is closed, because I have already answered all the previous questions.Can I resubmit this application? Or open this closed application?

**Comment by shimanmanya** [comment]
Can I resubmit this application to make sure your question？

**Comment by shimanmanya** [comment]
Can I resubmit this application to make sure your question#1900？

**Comment by shimanmanya** [comment]
I want to ask how to re-open or start a new application for DataCap anytime. Thank you!

**Comment by shimanmanya** [comment]
Please support me, I am ready! Please enthusiastic people support me! @cryptowhizzard @zcfil @fabriziogianni7 @simonkim0515 @galen-mcandrew

**Comment by shimanmanya** [comment]
Dear Notary Public, thank you for your questions and enthusiastic support.

We plan to collaborate with 5-10 SPs, including f02181415, f02105219, f0427989, f02085528, f02199203, f02145020, f02036170, f02182902, f02182798

We request that the cooperating SP can provide retrieval, and if the SP is unable to provide retrieval, we will not consider collaborating with them.

Thank you for your patience and support. If possible, please support us. Thank you!

**Comment by shimanmanya** [comment]
Dear Notary Public, thank you for your questions and enthusiastic support.

We plan to collaborate with 5-10 SPs, including f02181415, f02105219, f0427989, f02085528, f02199203, f02145020, f02036170, f02182902, f02182798

We request that the cooperating SP can provide retrieval, and if the SP is unable to provide retrieval, we will not consider collaborating with them.

Thank you for your patience and support. If possible, please support us. Thank you!
@nj-steve @cryptowhizzard @zcfil @fabriziogianni7 @simonkim0515

**Comment by nj-steve** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb337bcrew2svk3vqloaxh7swxpombemu2k233iyp7u5gjfkrgd6g 
#### Address 
> f1gg5dvu33z36erx5yinelesxkudovfrz3zyqm4py
#### Datacap Allocated
> 250.00TiB
#### Signer Address
> f1xx6555qijma7igpnjspyvdunc4vfxkawnpqy5ii
#### Id
> 097d3f03-021f-4b3a-b256-50f72d63cd24
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb337bcrew2svk3vqloaxh7swxpombemu2k233iyp7u5gjfkrgd6g

**Comment by OpenGate01** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceax6avkgxagetrpwbu4fxdzyhjb7saza252rk5lkngxamxtapsdoi 
#### Address 
> f1gg5dvu33z36erx5yinelesxkudovfrz3zyqm4py
#### Datacap Allocated
> 250.00TiB
#### Signer Address
> f1im4hmtbfzqnx7ir74kdaiu4ynjhgqh3sdi2snla
#### Id
> 097d3f03-021f-4b3a-b256-50f72d63cd24
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceax6avkgxagetrpwbu4fxdzyhjb7saza252rk5lkngxamxtapsdoi

**Comment by woshidama323** [comment]
checker:manualTrigger

**Comment by woshidama323** [comment]
<img width="588" alt="WechatIMG18" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/11014169/cb505e8f-27c7-4290-b67a-693246e3d5ec">
LGTM Will support this application

**Comment by woshidama323** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced75wezwjabile4lqccstwwr2vffjq2wabmgfi3d44rjfyyhppxim 
#### Address 
> f1gg5dvu33z36erx5yinelesxkudovfrz3zyqm4py
#### Datacap Allocated
> 500.00TiB
#### Signer Address
> f12tk3adljauwnd3hjbigpfxb7b7gdlj63p6afwtq
#### Id
> d94bf399-4f62-4ca1-bbae-e9b3cda59373
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced75wezwjabile4lqccstwwr2vffjq2wabmgfi3d44rjfyyhppxim

**Comment by MaleiWong** [comment]
checker:manualTrigger

**Comment by sxxfuture-official** [comment]
It looks healthy from the CID checker report. 
and test data retrieve ...
<img width="759" alt="a6bdb58d03a4e1a47dab81250c54cc9" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/113963951/c7b91702-f8a8-403a-8426-8c07fa52312b">

**Comment by sxxfuture-official** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceayal66zuc4kyueey6xtk2j4aywsy27a77puxvg6wr7hhstpeacoe 
#### Address 
> f1gg5dvu33z36erx5yinelesxkudovfrz3zyqm4py
#### Datacap Allocated
> 1000.00TiB
#### Signer Address
> f1foiomqlmoshpuxm6aie4xysffqezkjnokgwcecq
#### Id
> 5a528c75-ba1d-49ee-b336-6074fb5dd519
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceayal66zuc4kyueey6xtk2j4aywsy27a77puxvg6wr7hhstpeacoe

**Comment by SuperChaiChai** [comment]
![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/42091141/1a1c1e64-3f6d-41d4-b7b3-edf109b08406)

**Comment by SuperChaiChai** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedkyjmvnu7paakxtmctuoz6vwnkt27ukffkxkbdipfsk37ao7ibi4 
#### Address 
> f1gg5dvu33z36erx5yinelesxkudovfrz3zyqm4py
#### Datacap Allocated
> 1000.00TiB
#### Signer Address
> f12mckci3omexgzoeosjvstcfxfe4vqw7owdia3da
#### Id
> 5a528c75-ba1d-49ee-b336-6074fb5dd519
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedkyjmvnu7paakxtmctuoz6vwnkt27ukffkxkbdipfsk37ao7ibi4

**Comment by GaryGJG** [comment]
checker:manualTrigger

**Comment by 1ane-1** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb7qy5ahylztee5kimeyxz3u5lqadhxftw7whk3jy2i3y6florija 
#### Address 
> f1gg5dvu33z36erx5yinelesxkudovfrz3zyqm4py
#### Datacap Allocated
> 1.95PiB
#### Signer Address
> f1mdk7s2vntzm6hu35yuo6vjubtrpfnb2awhgvrri
#### Id
> 9146cda1-8303-4353-99e6-ccb799cadc1d
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb7qy5ahylztee5kimeyxz3u5lqadhxftw7whk3jy2i3y6florija

**Comment by NDLABS-OFFICE** [comment]
checker:manualTrigger

**Comment by NDLABS-OFFICE** [comment]
From the report looks very good, willing to support

**Comment by NDLABS-OFFICE** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecgncpup24v5bmxwagexixrk7vu4pey6sukzffq26o6omluyonlse 
#### Address 
> f1gg5dvu33z36erx5yinelesxkudovfrz3zyqm4py
#### Datacap Allocated
> 1.95PiB
#### Signer Address
> f1yayfsv6whu3rheviucvventj3y6t542xfpb47ei
#### Id
> 9146cda1-8303-4353-99e6-ccb799cadc1d
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecgncpup24v5bmxwagexixrk7vu4pey6sukzffq26o6omluyonlse

**Comment by cryptowhizzard** [comment]
checker:manualTrigger

**Comment by Tom-OriginStorage** [comment]
![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/103015469/9152c81b-9421-44d4-87c1-63b216d2b3b0)

**Comment by Tom-OriginStorage** [comment]
The packaging report shows that it is relatively normal, after inspection, the retrieval is also normal, willing to support

**Comment by Tom-OriginStorage** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecxrjdxjvaa6nmoafkqsp537v6bx6hfm5mxngb2g3w4zigmegrfri 
#### Address 
> f1gg5dvu33z36erx5yinelesxkudovfrz3zyqm4py
#### Datacap Allocated
> 1.34PiB
#### Signer Address
> f1q6bpjlqia6iemqbrdaxr2uehrhpvoju3qh4lpga
#### Id
> 5d777e85-7d8d-4beb-a5dd-387eaddaa122
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecxrjdxjvaa6nmoafkqsp537v6bx6hfm5mxngb2g3w4zigmegrfri

**Comment by Aaron01230** [comment]
checker:manualTrigger

**Comment by Aaron01230** [comment]
Normal retrieval rate and normal geographical distribution, I support this round.

**Comment by Aaron01230** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced4xwujynxefauc6h27sr5mtcg57llwy3aq4dye7rysqltgyr2w4i 
#### Address 
> f1gg5dvu33z36erx5yinelesxkudovfrz3zyqm4py
#### Datacap Allocated
> 1.34PiB
#### Signer Address
> f1xrnysd4gimg64d4l6qi7ulzwwq22c6vfg6lpw3i
#### Id
> 5d777e85-7d8d-4beb-a5dd-387eaddaa122
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced4xwujynxefauc6h27sr5mtcg57llwy3aq4dye7rysqltgyr2w4i

**Comment by spaceT9** [comment]
checker:manualTrigger
