### ISSUE TITLE
[DataCap Application] Dixun Network Technology - DNEXT

### ISSUE THREAD

**Issue by i0k24** [filecoin-project/filecoin-plus-large-datasets#1902]
### Data Owner Name

Dixun Network Technology

### Data Owner Country/Region

China

### Data Owner Industry

Information, Media & Telecommunications

### Website

https://www.diction-style.com

### Social Media

```text
See website
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

1PiB

### On-chain address for first allocation

f1tla4lugbghugiugmynz2gwt22acdu5gvugjemzy

### Data Type of Application

Public, Open Commercial/Enterprise

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Shenzhen Dixun Network Technology Co., Ltd. (hereinafter referred to as Dixun) was founded in 1995 and Dixun Online in 2005. It is a company specializing in

Designer growth and development, committed to the construction of an innovative internet enterprise in the fashion industry ecosystem.

Making fashion within reach is Diexun's mission. Dixun applies internet technology to connect producers with consumers and eliminate the fashion industry

The issue of information asymmetry is committed to enabling everyone around the world to have zero contact with fashion.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
Business data and historical logs of the company over 10 years of operation.
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### How do you plan to prepare the dataset

lotus

### Please share a sample of the data

```text
https://pan.baidu.com/s/1YjMOj6Yct56mM8mYE0XQQA?pwd=6acb

https://pan.baidu.com/s/1-WxoqFG9eKhMdvQUF-PISQ?pwd=5463

https://pan.baidu.com/s/1o4J73p7E63ZDX9PqoZ8veA?pwd=0jq5

https://pan.baidu.com/s/1s8JYx60AFVuKUZqf7gFApw?pwd=xtkq

https://pan.baidu.com/s/1nr7AZgRQEW_OlQSFZUDPFg?pwd=thsd
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Monthly

### For how long do you plan to keep this dataset stored on Filecoin

2 to 3 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, Europe

### How will you be distributing your data to storage providers

HTTP or FTP server, Lotus built-in data transfer

### How do you plan to choose storage providers

Slack, Partners

### If you already have a list of storage providers to work with, fill out their names and provider IDs below

```text
f01985775 - Greater Heat, Dallas, Texas, US
f0750779 - OuRuan IT LLC, Chengdu, China
f01907545 - Weimin, Xi'an, CN
f01900722 - F3, Viet Nam
f01850726 - Maike
f01989866 - Weimin, Xi'an, CN
f01985775 - Greater Heat, Dallas, Texas, US
```

### How do you plan to make deals to your storage providers

Boost client, Singularity

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by caoyoungyoung** [comment]
http://www.diexun.com/? or http://www.dixun.com/
 which one is your company website? Can you provide some kyb info like business certificate?

**Comment by Sunnyiscoming** [comment]
Could you send an email to filplus-app-review@fil.org with your official domain in order to confirm your identity? Email name should includes the issue id #1902.

**Comment by cryptowhizzard** [comment]
Dear,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Looking at your application i have some questions:
As you are brand new on Github and have no history of past applications. Can you give me an introduction who you are and an introduction about your company?

You stated that you are a Data preparer. What hardware do you have over there to prepare this dataset? What is your internet connection speed? Do you already have the data downloaded on the premises?

It seems to me that applying for 5PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?

Can you show us some visible proof of the size of your data and the storage / packing hardware you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230337462961356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!
