### ISSUE TITLE
[DataCap Application] Shenzhen Zhongzhi Institute Education Technology Co., Ltd.

### ISSUE THREAD

**Issue by zshou634** [filecoin-project/filecoin-plus-large-datasets#1903]
### Data Owner Name

Shenzhen Zhongzhi Institute Education Technology Co., Ltd.

### Data Owner Country/Region

China

### Data Owner Industry

Web3 / Crypto

### Website

http://www.vkshequn.com/

### Social Media

```text
Tik Tok：https://v.douyin.com/Ssw4G8Y/
https://v.douyin.com/SswSK6W/
Himalayas：https://xima.tv/1_hN2bUi?_sonic=0
Twitter：https://twitter.com/vk20212021
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

500TiB

### On-chain address for first allocation

f15ef4o3u4vxuf52zrt6gkzraeaqtqngfpz76vfvi

### Data Type of Application

None

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
The predecessor of China Institute of Intellectual Property was engaged in traditional corporate training, management consulting, personal growth, and spiritual training.
Later, as the whole world entered the digital economy world from the Internet world, and the Internet entered Web3.0, the company also began to transform into a self-media platform in the digital economy world.
The four businesses positioned by the Institute of Intellectual Property mainly include:
1. Industry self-media: Focus on new industry information, interpret the prospects of the industrial blockchain industry and the changes in the digital currency market in various forms, and produce articles, audio and video;
2. Industry training and consulting: With "Blockchain Thinking" as the core, we will carry out evangelist training, blockchain professional technical training and blockchain project entrepreneurship training, and empower enterprises to go on-chain and tokenize transformation;
3. Channels of high-quality investment products in the industry: Currently focusing on the sales of IPFS distributed cloud storage mining machines, BTC and ETH mining machines; based on its own mining pool, it provides technological financial wealth management products.
4. Community operation: through online and offline activities, manage sticky fans, develop community value, and help fans grow.
The digital economy industry is a new type of industry. There are no authoritative experts and undisputed definitions. Everyone is an adventurer in the unknown world.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
The storage content is: for users to better understand and use the pictures, videos, and audio materials stored in the blockchain and encrypted currency, including: pictures, videos of various activities; and audio and video, so that customers can understand the blockchain. There are also pictures about the company's mine environment and the company's working environment.
```

### Where was the data currently stored in this dataset sourced from

Other

### If you answered "Other" in the previous question, enter the details here

```text
Baidu cloud
```

### How do you plan to prepare the dataset

IPFS, lotus

### Please share a sample of the data

```text
Link:https://pan.baidu.com/s/1uieCoHfTqGnoVTDMWYGIPA 
Extraction code:96jp
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Monthly

### For how long do you plan to keep this dataset stored on Filecoin

More than 3 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, South America, Europe, Australia (continent)

### How will you be distributing your data to storage providers

Cloud storage (i.e. S3), HTTP or FTP server, IPFS

### How do you plan to choose storage providers

Filmine

### How do you plan to make deals to your storage providers

Boost client, Lotus client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by zshou634** [comment]
Sorry, my account has been officially flagged by github, so I have to reapply for the project.

**Comment by Sunnyiscoming** [comment]
Could you send an email to filplus-app-review@fil.org with your official domain in order to confirm your identity? Email name should includes the issue id #1903.

**Comment by zshou634** [comment]
![ed9636d4f8a044e048f53d601901c8a](https://user-images.githubusercontent.com/116909370/231711918-01607631-4e3a-4e8e-954d-b2c9e52cb4ed.png)
Hello, we have sent the email. Please review it as soon as possible. Thank you so much。

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 5PiB

**Expected weekly DataCap usage rate**
> 500TiB

**Client address**
>f15ef4o3u4vxuf52zrt6gkzraeaqtqngfpz76vfvi

**Comment by laurarenpanda** [comment]
Hi, @zshou634.

Would you please provide more details about your data/ total capacity/ quantity of files?
And your DC distribution strategy as well, including the number of copies/ SPs/ SPs' location.

**Comment by maxvint** [comment]
Hello, I have a few questions about DC allocation.

Can you prove the amount of data you currently have? Example screenshot of data capacity.
How many copies will you store?
Can you give information about SP's you will store with?

**Comment by zshou634** [comment]
![e8acc8d825f0cb946111583abdb3f60](https://user-images.githubusercontent.com/116909370/233604763-ab6533e6-4834-43c9-966a-69058fb15077.jpg)
![b10da68aa82aa10869b112c0a7e5938](https://user-images.githubusercontent.com/116909370/233604768-694102a0-2dbc-4146-8d6c-21e26340f4e4.png)


Sorry for the late reply. Hope to get your support.
At your request, we provide proof of data.
We want to cooperate with as many sps as possible, at least 6 sps, and the specific number may be between 6-9. This is the list of some of our sps:
f02036170
f02009673
f02125861
f01915309
f02001485
f0427989
f02101629
f01900537
f01914991

**Comment by liyunzhi-666** [comment]
I have checked the application and data samples, based on the content in the issue comments, I will support the first round and monitor the subsequent allocation of clients.

**Comment by liyunzhi-666** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebgngfqsd6juaiyxkyyzpikvq2fblmge6iuyypdlcstuoewvnvzhs 
#### Address 
> f15ef4o3u4vxuf52zrt6gkzraeaqtqngfpz76vfvi
#### Datacap Allocated
> 250.00TiB
#### Signer Address
> f1pszcrsciyixyuxxukkvtazcokexbn54amf7gvoq
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebgngfqsd6juaiyxkyyzpikvq2fblmge6iuyypdlcstuoewvnvzhs

**Comment by cryptowhizzard** [comment]
checker:Manualtrigger

**Comment by igoovo** [comment]
checker:manualTrigger

**Comment by igoovo** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebfhpv4fyi72ab6zrefj6g5whz62djt2d5akkpoafy5vtqwd5u7rm 
#### Address 
> f15ef4o3u4vxuf52zrt6gkzraeaqtqngfpz76vfvi
#### Datacap Allocated
> 500.00TiB
#### Signer Address
> f1shnsfayxqll77svffaxnjenms7bbbysbqcatrpy
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebfhpv4fyi72ab6zrefj6g5whz62djt2d5akkpoafy5vtqwd5u7rm

**Comment by NDLABS-OFFICE** [comment]
checker:manualTrigger

**Comment by NDLABS-OFFICE** [comment]
The check bot appears to be healthy and the retrieval test was successful
![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/104019147/f963ec03-aa15-491f-b88c-b635a2228ef1)

**Comment by NDLABS-OFFICE** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceck3vgtfgfrbaowkhtcnoghz4emb2cprw5xqiiqhjwjnwrq2b7fye 
#### Address 
> f15ef4o3u4vxuf52zrt6gkzraeaqtqngfpz76vfvi
#### Datacap Allocated
> 500.00TiB
#### Signer Address
> f1yayfsv6whu3rheviucvventj3y6t542xfpb47ei
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceck3vgtfgfrbaowkhtcnoghz4emb2cprw5xqiiqhjwjnwrq2b7fye

**Comment by liyunzhi-666** [comment]
According to the CID checker, the first round of allocations are concentrated in mainland China, and 4 SPs are not the SPs you disclosed contacting before. @zshou634 can you explain this?

**Comment by zshou634** [comment]
@liyunzhi-666 Hello, the entry situation of each SP is different, and this is in the first round, so the distribution of SP is not very reasonable, but this is only temporary, next round, you will see the update, thank you for your help and support~

**Comment by mikezli** [comment]
![4ace2f5059a7e323f09e28a9ad067fa](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/118169683/60910f63-ac1b-4d44-8328-30041389267d)

**Comment by mikezli** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceareksmqxazb3t236fjunuayz7gzcpdzrfov4iy6qkvh6giewzrs2 
#### Address 
> f15ef4o3u4vxuf52zrt6gkzraeaqtqngfpz76vfvi
#### Datacap Allocated
> 1000.00TiB
#### Signer Address
> f1dnb3uz7sylxk6emti3ififcvu3nlufnnsjui6ea
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceareksmqxazb3t236fjunuayz7gzcpdzrfov4iy6qkvh6giewzrs2

**Comment by psh0691** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceardbfv6piuqiicpc67ltzrmpk44ccgiku2pirp6newvhgaw3bkn6 
#### Address 
> f15ef4o3u4vxuf52zrt6gkzraeaqtqngfpz76vfvi
#### Datacap Allocated
> 1.95PiB
#### Signer Address
> f1qdko4jg25vo35qmyvcrw4ak4fmuu3f5rif2kc7i
#### Id
> 438e88f6-2b16-4ad0-a9f9-7a9761225b0c
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceardbfv6piuqiicpc67ltzrmpk44ccgiku2pirp6newvhgaw3bkn6

**Comment by luobin544** [comment]
![img_v2_159dbd65-b7f8-4b84-bc90-49dd4905adch](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/4277341/078feba7-a289-4513-aa01-f5ef7b4f0b81)

**Comment by luobin544** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceannkftlntevczcbhki2b5372qos5nunlisuxbejnzgmya37lkovy 
#### Address 
> f15ef4o3u4vxuf52zrt6gkzraeaqtqngfpz76vfvi
#### Datacap Allocated
> 1.95PiB
#### Signer Address
> f1tbd632f6w62glfaf7wjpimacbnjiz26poyoes2q
#### Id
> 438e88f6-2b16-4ad0-a9f9-7a9761225b0c
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceannkftlntevczcbhki2b5372qos5nunlisuxbejnzgmya37lkovy

**Comment by a1991car** [comment]
checker:manualTrigger

**Comment by 1ane-1** [comment]
![6ab6e19445d325b4362fb09c8cda0cd](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/91301211/33f5ce7b-be85-4fb3-8d96-70e55d5036b7)

**Comment by nj-steve** [comment]
checker:manualTrigger

**Comment by 1ane-1** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecrua7celmnyeoqpjfkecnv5sgld3zq2p5jn2fq22vgepmtrl5ohy 
#### Address 
> f15ef4o3u4vxuf52zrt6gkzraeaqtqngfpz76vfvi
#### Datacap Allocated
> 1.34PiB
#### Signer Address
> f1mdk7s2vntzm6hu35yuo6vjubtrpfnb2awhgvrri
#### Id
> 65194ddd-8eed-4097-94fd-18b0a7e5a39f
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecrua7celmnyeoqpjfkecnv5sgld3zq2p5jn2fq22vgepmtrl5ohy

**Comment by 1ane-1** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecbumllpxhveizzsnjopqkjs25ir5gzaoourkips6zswzmrugrxoa 
#### Address 
> f15ef4o3u4vxuf52zrt6gkzraeaqtqngfpz76vfvi
#### Datacap Allocated
> 1.34PiB
#### Signer Address
> f1mdk7s2vntzm6hu35yuo6vjubtrpfnb2awhgvrri
#### Id
> 65194ddd-8eed-4097-94fd-18b0a7e5a39f
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecbumllpxhveizzsnjopqkjs25ir5gzaoourkips6zswzmrugrxoa

**Comment by nj-steve** [comment]
The report looks good, and also support retrieval.
![1903](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/15796059/70562687-26f8-4189-b845-e6808f980584)

**Comment by herrehesse** [comment]
checker:manualTrigger

**Comment by phantom-rabbit** [comment]
checker:manualTrigger
