### ISSUE TITLE
[DataCap Application] International Neuroimaging Data-Sharing Initiative (INDI)

### ISSUE THREAD

**Issue by Parker35sun** [filecoin-project/filecoin-plus-large-datasets#1906]
### Data Owner Name

Child Mind Institute

### Data Owner Country/Region

United States

### Data Owner Industry

Life Science / Healthcare

### Website

https://childmind.org/

### Social Media

```text
https://www.facebook.com/ChildMindInstitute
https://twitter.com/ChildMindInst
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

800TiB

### On-chain address for first allocation

f1zqpqw7kavxxu3zdaomwveibcsvj4ida7iwmskia

### Data Type of Application

None

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Child Mind Institute is dedicated to transforming the lives of children and families struggling with mental health and learning disorders by giving them the help they need. We’ve become the leading independent nonprofit in children’s mental health by providing gold-standard evidence-based care, delivering educational resources to millions of families each year, training educators in underserved communities, and developing tomorrow’s breakthrough treatments.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
Neuroimaging data for the International Neuroimaging Data-Sharing Initiative (INDI)
This bucket contains multiple neuroimaging datasets that are part of the International Neuroimaging Data-Sharing Initiative. Raw human and non-human primate neuroimaging data include 1) Structural MRI; 2) Functional MRI; 3) Diffusion Tensor Imaging; 4) Electroencephalogram (EEG) In addition to the raw data, preprocessed data is also included for some datasets.
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### How do you plan to prepare the dataset

lotus, singularity

### Please share a sample of the data

```text
https://registry.opendata.aws/fcp-indi/
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Sporadic

### For how long do you plan to keep this dataset stored on Filecoin

1.5 to 2 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America

### How will you be distributing your data to storage providers

HTTP or FTP server, Shipping hard drives

### How do you plan to choose storage providers

Slack, Big data exchange

### How do you plan to make deals to your storage providers

Lotus client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
Can you introduce your organizaion? Please share more detailed information about sps you will cooperate with.

**Comment by Parker35sun** [comment]
@Sunnyiscoming Ok. I'm a DP, who are responsible for the downloading, processing, and distribution of CAR files to SP. I am confirming the list of sp and we will soon reach a cooperation. Hope my application will be approved.

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 5PiB

**Expected weekly DataCap usage rate**
> 800TiB

**Client address**
>f1zqpqw7kavxxu3zdaomwveibcsvj4ida7iwmskia

**Comment by Casey-PG** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedxy6jgjitx7ao6a4gnstaadpbn5uxmorhiv2a4cu3w5xgpp2k34s 
#### Address 
> f1zqpqw7kavxxu3zdaomwveibcsvj4ida7iwmskia
#### Datacap Allocated
> 256.00TiB
#### Signer Address
> f1d4yb3wags3mtddzesxoo63jv7dmlec3bq4yteni
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedxy6jgjitx7ao6a4gnstaadpbn5uxmorhiv2a4cu3w5xgpp2k34s

**Comment by Aifabot-Cloud** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedx7iwlqu3m3udy5kexjleu63bpblakl732ftfxacchkxzqtlishg 
#### Address 
> f1zqpqw7kavxxu3zdaomwveibcsvj4ida7iwmskia
#### Datacap Allocated
> 256.00TiB
#### Signer Address
> f174fg3bqbln3zjnkxtyf6s54txqkr7yqkj6cig7y
#### Id
> 83c8c324-c12a-407f-a23e-f43e40f7918c
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedx7iwlqu3m3udy5kexjleu63bpblakl732ftfxacchkxzqtlishg

**Comment by cryptowhizzard** [comment]
Hello,

I have tried retrieval but none of your SP's seem to support it. This is against FIL+ rules & guidelines.
Secondly, everything is stored in one region and not distributed outside Asia. This is against FIL+ rules & guidelines.

Please advise.

<img width="1105" alt="Scherm­afbeelding 2023-05-05 om 19 56 10" src="https://user-images.githubusercontent.com/36404435/236532846-e6b2b51f-b0f0-4e2c-bfe0-6ffc6823b24b.png">

**Comment by TakiChain** [comment]
checker:manualTrigger

**Comment by TakiChain** [comment]
Hope to improve this indicator of Deal Data Replication in the next few rounds. willing to help onboard more valuable dataset.

**Comment by BobbyChoii** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecyfbgtwdhzyxdt5vjgwq7bemje54a7prjxmpkk34uzehitodjfl6 
#### Address 
> f1zqpqw7kavxxu3zdaomwveibcsvj4ida7iwmskia
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f1irqs2gmctiv3jcdfwuch7oxvf4ixh3k4b2wc24i
#### Id
> 35834b1e-6fa3-49b1-975f-9cb17a325668
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecyfbgtwdhzyxdt5vjgwq7bemje54a7prjxmpkk34uzehitodjfl6

**Comment by Aifabot-Cloud** [comment]
The client contacted me by slack and shared more of their information . I'd like to see more public data joining the network!

**Comment by Aifabot-Cloud** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced6yg3dv4pw4inxerqxfw36zmpogamdbi2fvmwj2yfzgd7u7n3n7i 
#### Address 
> f1zqpqw7kavxxu3zdaomwveibcsvj4ida7iwmskia
#### Datacap Allocated
> 1.00PiB
#### Signer Address
> f174fg3bqbln3zjnkxtyf6s54txqkr7yqkj6cig7y
#### Id
> e39fa630-d845-44a7-92c5-be99a3178830
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced6yg3dv4pw4inxerqxfw36zmpogamdbi2fvmwj2yfzgd7u7n3n7i

**Comment by Casey-PG** [comment]
Glad to support this application in this round.

**Comment by Casey-PG** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceabzpl57xvdqem3yk2vjqpwbgfvtwdp5aujqt6y3l6dxn6echzzqm 
#### Address 
> f1zqpqw7kavxxu3zdaomwveibcsvj4ida7iwmskia
#### Datacap Allocated
> 1.00PiB
#### Signer Address
> f1d4yb3wags3mtddzesxoo63jv7dmlec3bq4yteni
#### Id
> e39fa630-d845-44a7-92c5-be99a3178830
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceabzpl57xvdqem3yk2vjqpwbgfvtwdp5aujqt6y3l6dxn6echzzqm

**Comment by TakiChain** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceafpspygubgmbhd2tytgufzpxs7lycecnyqqaz2q4hqm4omug43kc 
#### Address 
> f1zqpqw7kavxxu3zdaomwveibcsvj4ida7iwmskia
#### Datacap Allocated
> 2.00PiB
#### Signer Address
> f15impf3j2zcaex4lhyxndxswuuhv24vzstuqtxsi
#### Id
> f358de05-d8d7-4702-b1e4-e4c008cabe67
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceafpspygubgmbhd2tytgufzpxs7lycecnyqqaz2q4hqm4omug43kc

**Comment by BobbyChoii** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebzoqtymxitinvemm7bggtxr56m7t4lur4yfn2zwzohxc4yhih3mq 
#### Address 
> f1zqpqw7kavxxu3zdaomwveibcsvj4ida7iwmskia
#### Datacap Allocated
> 2.00PiB
#### Signer Address
> f1irqs2gmctiv3jcdfwuch7oxvf4ixh3k4b2wc24i
#### Id
> f358de05-d8d7-4702-b1e4-e4c008cabe67
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebzoqtymxitinvemm7bggtxr56m7t4lur4yfn2zwzohxc4yhih3mq

**Comment by BobbyChoii** [comment]
The client followed the allocation he disclosed before and the datacap usageis in compliance with regulations.

**Comment by cryptowhizzard** [comment]
checker:manualTrigger

**Comment by cryptowhizzard** [comment]
@TakiChain @BobbyChoii @Aifabot-Cloud 
@Parker35sun 

This data is unretrievable.
This data is fully centralised in China.
There has been no due diligence done.

**Comment by Parker35sun** [comment]
@cryptowhizzard Thank you for your reminder.

1 We've asked and confirmed SPs who are cooperating with us to open http retrieval. However, due to the retrieval bot, it cannot be reflected in the report in real time. We learned that Caro (PL) has noticed the problem and tried to resolve it. 
![3](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/129134651/ad0dc59f-276f-4f99-aa91-1aeb78f42102)

2 It's true that most of the SPs we worked with are in Greater China, but that's allowed in the community rules. China is, after all, a geographically vast country.

3 I saw that most of notaries have left due diligence in my application. Very few notaries may have forgotten to leave the message because of the second signing. It was very hard for me to get their support, please don't blame them too much.

Lastly, thank you for your supervision and reminder, we will continue to look for SPs who are willing to follow the rules and cooperate with them.

**Comment by herrehesse** [comment]
1. Retrieval bot works, the miners are unreachable.
2. No it is not.
3. No these notaries are the same ones found on almost all disputes.

**Comment by cryptowhizzard** [comment]
1, I tested HTTP, still no avail.
2, No. your LDN indicated: Greater China, Asia other than Greater China, North America. This is not true.
3, rules are in place to be followed upon.

**Comment by cryptowhizzard** [comment]
Hello @Parker35sun 

It really seems the SP's used are involved in CID sharing and have retrieval disabled. 
The issue LDN's are in the column auditTrail if you want to check yourself.

Let me know if you need any more information.

![Scherm­afbeelding 2023-07-31 om 13 17 49](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/36404435/eea2eba5-3944-49b0-9ef0-8527d51787f2)

**Comment by Parker35sun** [comment]
checker:manualTrigger

**Comment by Parker35sun** [comment]
@Carohere I saw that you are helping to correct the gaslighting behavior of some notaries, could you give me a hand?

**Comment by Carohere** [comment]
@Parker35sun  Thanks for your trust.
Based on the report, it's true that all of their comments were not supported by written rules and corroborating evidence.
But your application is closed by bot and I am not able to help you.

**Comment by Parker35sun** [comment]
thanks @simonkim0515 @Carohere,  I would place the status update in the LDN application itself.

**Comment by raghavrmadya** [comment]
@Parker35sun , please respond to the notary concerns. Your application is under dispute on the tracker

**Comment by Parker35sun** [comment]
checker:manualTrigger

**Comment by Parker35sun** [comment]
> @cryptowhizzard Thank you for your reminder.
> 
> 1 We've asked and confirmed SPs who are cooperating with us to open http retrieval. However, due to the retrieval bot, it cannot be reflected in the report in real time. We learned that Caro (PL) has noticed the problem and tried to resolve it. ![3](https://user-images.githubusercontent.com/129134651/255379486-ad0dc59f-276f-4f99-aa91-1aeb78f42102.png)
> 
> 2 It's true that most of the SPs we worked with are in Greater China, but that's allowed in the community rules. China is, after all, a geographically vast country.
> 
> 3 I saw that most of notaries have left due diligence in my application. Very few notaries may have forgotten to leave the message because of the second signing. It was very hard for me to get their support, please don't blame them too much.
> 
> Lastly, thank you for your supervision and reminder, we will continue to look for SPs who are willing to follow the rules and cooperate with them.

@raghavrmadya I have answered these questions several times in the past. But this notary ([cryptowhizzard](https://github.com/cryptowhizzard)) and his partner ([herrehesse](https://github.com/herrehesse)) still ask the same questions with the same words all the time everywhere.

I used to ask some notaries if it was acceptable for us to copperate with SPs, who have a bad sealing history with other clients. Some notaries thought it is not a problem and they think I should focus on my own application.

Can you give me a standard answer about it? 
[If a SP had cooperation with some clients in the past, but their DataCap and CID Checker Report shown that their work had problems to fix. **a.** Can another client cooperate with the SP? **b.** How can this new client know that the SP has a 'bad' history in advance? **c.** If there's no problem on the application from the new client, is the new client need to responsible to others' history? ]

**Comment by Sunnyiscoming** [comment]
It seems that the retrieval rate of some sp shows 0, can you explain?

**Comment by Parker35sun** [comment]
Hi @Sunnyiscoming 
Yes, it is true that we can‘t guarantee every nodes can reach 100% retrieval success rate. But for all those nodes that cannot provide retrieval, we will stop continuing to work together. 

Thank you for the opportunity of continue signing.

**Comment by cryptowhizzard** [comment]
This client is actively stalling http retrievals and blocked http ranged requests with a reverse proxy to prevent it's data being investigated.

It works as follows:

One set's a bandwidth limit with NGINX on the HTTP retrieval. After a random certain amount the limit is set to zero. This makes the transfer timeout. Because range retrieval is disabled in NGINX one cannot pick up where he left and needs to start all over again. 

Log can be found at http://datasetcreators.com/downloadedcarfiles/logs/1906.log

**Comment by Parker35sun** [comment]
We have talked to most of the SPs and confirmed that they are not using NGINX. I don't find valid evidence to prove your point from the logs you provided. These are normal data download records. It seems to be a slow download, but that's not against the community's rules.

**Comment by cryptowhizzard** [comment]
You don't support range retrievals , it is disabled while Boost supports these natively.

**Comment by Bennyyangpu** [comment]
checker:manualTrigger

**Comment by Bennyyangpu** [comment]
DD is ok,  the report seems normal. didn't see any retrieval problems. willing to support!

**Comment by Bennyyangpu** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceavd7q5swukghmy236il3z6i7k6nwbgvnyu2engxpabum4qkajp6c 
#### Address 
> f1zqpqw7kavxxu3zdaomwveibcsvj4ida7iwmskia
#### Datacap Allocated
> 1.25PiB
#### Signer Address
> f174fg3bqbln3zjnkxtyf6s54txqkr7yqkj6cig7y
#### Id
> ab927efc-4585-4546-9018-9f477c7e352b
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceavd7q5swukghmy236il3z6i7k6nwbgvnyu2engxpabum4qkajp6c

**Comment by Suyanj** [comment]
![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/107249346/7e4380e5-51ca-4e34-82a0-c6926f4961f1)

**Comment by Suyanj** [comment]
Checked on the Retrieval Dashboard it seems OK. Don't know why there's been so much gaslighting behavior lately.

**Comment by Suyanj** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceckmnj2nyihwdzw3r5goqcfyeh6vtiy27ouh43wteltciudirnvik 
#### Address 
> f1zqpqw7kavxxu3zdaomwveibcsvj4ida7iwmskia
#### Datacap Allocated
> 1.25PiB
#### Signer Address
> f1ihv7gz3vn3xqvikpt4rwryecgisl7745lodx3yi
#### Id
> ab927efc-4585-4546-9018-9f477c7e352b
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceckmnj2nyihwdzw3r5goqcfyeh6vtiy27ouh43wteltciudirnvik

**Comment by cryptowhizzard** [comment]
I checked retrieval ( over HTTP ).

The carfiles i retrieval all contain garbage data. This applicant is not storing the data he told us he was going to store.

![Scherm­afbeelding 2023-08-21 om 14 21 12](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/36404435/b95b9c6a-7bb7-4331-bc2b-3e6fbc761b5e)
![Scherm­afbeelding 2023-08-21 om 13 43 10](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/36404435/6dc95ce3-293d-49fe-ba81-aac4806573cc)

**Comment by cryptowhizzard** [comment]
I downloaded ( partially ) deal 47871504 btw.

**Comment by Filplus-govteam** [comment]
Hello @Parker35sun  per the new guidelines https://github.com/filecoin-project/notary-governance/issues/922 for Open Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

This information will be reviewed by Fil+ Governance team to confirm validity toward the Fil+ guideline of a distributed storage plan and SPs posted in the comments here. Let us know if you have any questions.

**Comment by Parker35sun** [comment]
> I downloaded ( partially ) deal 47871504 btw.

You haven't even finished downloading the data, why are you gaslighting me?

**Comment by cryptowhizzard** [comment]
> > I downloaded ( partially ) deal 47871504 btw.
> 
> You haven't even finished downloading the data, why are you gaslighting me?

Why are you scamming the community?

Deal 47871504 is a deal made with your LDN wallet. This is the data you are storing above. Just plain garbage.

![Scherm­afbeelding 2023-08-22 om 15 54 55](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/36404435/df502340-c0d0-4d8e-97f1-2ef18ab2b32c)

![Scherm­afbeelding 2023-08-22 om 15 55 41](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/36404435/39547088-47c2-4369-be0e-071ea07940be)

**Comment by raghavrmadya** [comment]
Thanks for the continued DD on this app. I just closed the [dispute](https://github.com/filecoin-project/notary-governance/issues/943) as it was running stale but the notaries in question are kindly requested to support the retrieval efforts to ensure [LDN guidelines](https://github.com/filecoin-project/filecoin-plus-large-datasets)

**Comment by raghavrmadya** [comment]
https://www.notion.so/filecoin/Applicant-storing-fake-data-6093d9965b7f41ce9ed3fcf1a5fe64b8?pvs=4

**Comment by raghavrmadya** [comment]
No response from client on the dispute - https://www.notion.so/filecoin/Applicant-storing-fake-data-6093d9965b7f41ce9ed3fcf1a5fe64b8?pvs=4

As a result, application is being closed and being flagged for DC removal
