### ISSUE TITLE
[DataCap Application]  Eystorage Large Dataset Notary Application [2/2]

### ISSUE THREAD

**Issue by heroapn** [filecoin-project/filecoin-plus-large-datasets#1907]
### Data Owner Name
WenChu BlockChain

### Data Owner Country/Region
China

### Data Owner Industry
IT & Technology Services

### Website
[https://www.wenchu.io/](https://www.wenchu.io/)

### Social Media
@WenChu_BC (twitter)

### Total amount of DataCap being requested
2 PiB

### Weekly allocation of DataCap requested
200 TiB

### On-chain address for first allocation
f15e42ee4eaeg4p24db5xdebktll3b6lvvekfuzni

### Data Type of Application
Public, Open Dataset (Research/Non-Profit)

### Custom multisig
No

### Identifier
no

### Share a brief history of your project and organization
Eystorage means easy to store data which provides an easy-to-use storage and retrieval service platform for users and developers of distributed storage. The backend stores data based on distributed storage networks such as IPFS, GlusterFS, web3.storage, Filecoin and https://github.com/filecoin-project/devgrants/issues/430, and provides storage for developers through OpenAPI interface. The front end provides a visual interface for users to store and retrieve data.

### Is this project associated with other projects/ecosystem stakeholders?
Yes

### If answered yes, what are the other projects/ecosystem stakeholders
 Filecoin foundation

### Describe the data being stored onto Filecoin
vps template ,iso file and machine log file.

### Where was the data currently stored in this dataset sourced from
Google Cloud

### How do you plan to prepare the dataset
lotus

### Please share a sample of the data
Centos 8.4 vmdk image:https://drive.google.com/file/d/1nXTrThLP4um3EvLqCrIZ-RT1Ve-mbjbA/view?usp=sharing
Centos 8.5 vmdk image:https://drive.google.com/file/d/1b9UQNLBA-5G0155c_Y3BsB9DeECJANxn/view?usp=sharing
Centos 9 vmdk image: https://drive.google.com/file/d/1HxkXW4ccrPzcizbpkBGMiZlJ0k9M05qg/view?usp=sharing
Centos 8.2 vmdk image: https://drive.google.com/file/d/1jXvTEakPRVKYljxnCA_gtp2e87smF6PV/view?usp=sharing

### Confirm that this is a public dataset that can be retrieved by anyone on the Network
Yes

### What is the expected retrieval frequency for this data
Monthly

### For how long do you plan to keep this dataset stored on Filecoin
Less than 1 year

### In which geographies do you plan on making storage deals
Greater China

### How will you be distributing your data to storage providers
HTTP or FTP server

### How do you plan to choose SP
Slack

### If you already have a list of storage providers to work with, fill out their names and provider IDs below
f07786 f03325 f01915135 f020522 f03325

### How do you plan to make deals to your storage providers
Boost client

### Can you confirm that you will follow the Fil+ guideline
Yes

_Application created via [filplus.storage](https://filplus.storage)_

**Comment by Sunnyiscoming** [comment]
Could you send an email to filplus-app-review@fil.org with your official domain in order to confirm your identity? Email name should includes the issue id #1907.

**Comment by heroapn** [comment]
@Sunnyiscoming Hi,I have sent a email,please check.
![图片](https://user-images.githubusercontent.com/33470476/232013322-3da7f4a4-8053-49ed-9f64-3d6fb5d7e005.png)

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 2PiB

**Expected weekly DataCap usage rate**
> 200TiB

**Client address**
>f15e42ee4eaeg4p24db5xdebktll3b6lvvekfuzni

**Comment by heroapn** [comment]
@Joss-Hua 
Dataset size: 462T,data type:system-iso\ vmdk-template\,with 5 copys.
SP:f07786 f07830 f01915135 f020522 f03325, located in HK,Mainland China,JP,US,Singapore.

**Comment by Joss-Hua** [comment]
![image](https://user-images.githubusercontent.com/75723122/232430342-c851d353-2f5c-4a04-a01a-8ab2697e55ca.png)
Abnormal display

**Comment by Joss-Hua** [comment]
ok

**Comment by heroapn** [comment]
@Joss-Hua hi,can you sign now?

**Comment by Joss-Hua** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebso25sozmqjkadsqappzqcdmeasws6po7xmf42wiu6earmhslrrc 
#### Address 
> f15e42ee4eaeg4p24db5xdebktll3b6lvvekfuzni
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1tfg54zzscugttejv336vivknmsnzzmyudp3t7wi
#### Id
> 7d1e40b2-c114-49dd-bef7-8e7cdcc4ab6d
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebso25sozmqjkadsqappzqcdmeasws6po7xmf42wiu6earmhslrrc

**Comment by maxvint** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebnfab34fol5i7bkmmoup2xex4aw4ui5lpoucfxolazkhahqcpvbo 
#### Address 
> f15e42ee4eaeg4p24db5xdebktll3b6lvvekfuzni
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1ui5iy4mmkxjbw7752omiwp2ols2fzv4thrayagi
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebnfab34fol5i7bkmmoup2xex4aw4ui5lpoucfxolazkhahqcpvbo

**Comment by heroapn** [comment]
checker:manualTrigger

**Comment by heroapn** [comment]
checker:manualTrigger

**Comment by heroapn** [comment]
checker:manualTrigger

**Comment by laurarenpanda** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebyy4tezukdqlhmzdb5zxd7eg2uji5xp4z2ebuvhb52saqdmtx7gw 
#### Address 
> f15e42ee4eaeg4p24db5xdebktll3b6lvvekfuzni
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1bp3tzp536edm7dodldceekzbsx7zcy7hdfg6uzq
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebyy4tezukdqlhmzdb5zxd7eg2uji5xp4z2ebuvhb52saqdmtx7gw

**Comment by Fatman13** [comment]
checker:manualTrigger

**Comment by Fatman13** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecdxmqmd4yzywgxbdhlndds5pkkdczfduxhvj4g53i3ggpyubvuf6 
#### Address 
> f15e42ee4eaeg4p24db5xdebktll3b6lvvekfuzni
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1j3u7crhjzwb2cj5mq7vodlt4o66yoyci7lhcauy
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecdxmqmd4yzywgxbdhlndds5pkkdczfduxhvj4g53i3ggpyubvuf6

**Comment by Fatman13** [comment]
reached out by the client on Wechat. Strategy and CID checker both look good. Will support.

**Comment by destor2023** [comment]
checker:manualTrigger

**Comment by destor2023** [comment]
Fantastic data distribution and deal-making, will to support it.

**Comment by heroapn** [comment]
Thanks for your support. Our DC distribution will meet the various requirements of the community and support quick retrieval.

**Comment by heroapn** [comment]
checker:manualTrigger

**Comment by cryptowhizzard** [comment]
Hi,

It seems that none of the SP's you work with support retrieval. This is against the FIL+ guidelines. I tested with two independent systems.

Please advise how you will solve this as it is against FIl+ guidelines.

<img width="1117" alt="Scherm­afbeelding 2023-05-05 om 19 51 10" src="https://user-images.githubusercontent.com/36404435/236532005-e5c0b5b4-1337-4dc5-8934-053e604e8d6e.png">
<img width="821" alt="Scherm­afbeelding 2023-05-05 om 19 51 06" src="https://user-images.githubusercontent.com/36404435/236532008-92dc44e6-56a8-4f2f-8472-6d3d8afaebfe.png">
<img width="827" alt="Scherm­afbeelding 2023-05-05 om 19 50 54" src="https://user-images.githubusercontent.com/36404435/236532010-8d4f04bc-cb73-4950-95a6-8a2aa8f05eb7.png">
<img width="781" alt="Scherm­afbeelding 2023-05-05 om 19 50 39" src="https://user-images.githubusercontent.com/36404435/236532015-db877a1f-6725-4c78-b635-3a9d88364115.png">

**Comment by heroapn** [comment]
Hi @cryptowhizzard 
SP replied that during the previous upgrade, there was no upgrade to the market code, which resulted in the database of Dagstore not matching the actual one. They need to restore it, and we will continue to follow up and provide feedback to you.

**Comment by heroapn** [comment]
@cryptowhizzard 
Hi,the retrieval function has been repaired,please try again.

**Comment by phantom-rabbit** [comment]
checker:manualTrigger

**Comment by phantom-rabbit** [comment]
checker:manualTrigger

**Comment by fabriziogianni7** [comment]
> ## DataCap Allocation requested
> ### Request number 3
> #### Multisig Notary address
> > f02049625
> 
> #### Client address
> > f15e42ee4eaeg4p24db5xdebktll3b6lvvekfuzni
> 
> #### DataCap allocation requested
> > 400TiB
> 
> #### Id
> > 0df8ca58-b56f-425b-9a62-d9e610ff2b95

I updated the request. should be good to go now

**Comment by fabriziogianni7** [comment]
> ## DataCap Allocation requested
> ### Request number 3
> #### Multisig Notary address
> > f02049625
> 
> #### Client address
> > f15e42ee4eaeg4p24db5xdebktll3b6lvvekfuzni
> 
> #### DataCap allocation requested
> > 400TiB
> 
> #### Id
> > 0df8ca58-b56f-425b-9a62-d9e610ff2b95

I updated the comment, should be good to go now

**Comment by zcfil** [comment]
checker:manualTrigger

**Comment by zcfil** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceafyijrv3kosgifdzndvubgkus7pp4kcyk7ht5xfdov5hiyntp75k 
#### Address 
> f15e42ee4eaeg4p24db5xdebktll3b6lvvekfuzni
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1cjzbiy5xd4ehera4wmbz63pd5ku4oo7g52cldga
#### Id
> 0df8ca58-b56f-425b-9a62-d9e610ff2b95
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceafyijrv3kosgifdzndvubgkus7pp4kcyk7ht5xfdov5hiyntp75k

**Comment by cryptowhizzard** [comment]
Hi,

I have tried to retrieve some of your data but the maximum speed i get is 64 Kbit/s, making this impossible.

Can you make CID baga6ea4seaqj4ug4t3ivgr2jfvynwrmxkwrixifov3gko5yrd4seccqww7dkmmq for download somewhere so i can check the contents of this file and validate the data you are storing?

Thanks!

**Comment by phantom-rabbit** [comment]
checker:manualTrigger

**Comment by heroapn** [comment]
I think the issue of retrieval speed is about to be resolved

**Comment by cryptowhizzard** [comment]
checker:manualTrigger

**Comment by cryptowhizzard** [comment]
@heroapn the retrieval report confirms my findings. 
can you make the care file available so we can check the data?

**Comment by heroapn** [comment]
@cryptowhizzard of course

**Comment by heroapn** [comment]
uploading file

**Comment by heroapn** [comment]
checker:manualTrigger
