### ISSUE TITLE
[DataCap Application] Public Datasets --- Lidar+4DN+Nanopore+Sentinel+Sunflower Genome

### ISSUE THREAD

**Issue by enochleon** [filecoin-project/filecoin-plus-large-datasets#1908]
### Data Owner Name

NOAA; 4DN-DCIC; NWGSC; NRC; UBC

### Data Owner Country/Region

United States

### Data Owner Industry

Other

### Website

http://www.noaa.gov/

### Social Media

```text
https://twitter.com/NOAA
https://twitter.com/4dn_dcic
https://www.facebook.com/EnvironmentandNaturalResourcesinCanada/
https://twitter.com/NRCan
https://www.youtube.com/user/NaturalResourcesCa
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

800TiB

### On-chain address for first allocation

f14ckrd6rtf5suqk7vbrr567pvyarma6pwivscoea

### Data Type of Application

None

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
I'm a DP. I prepare public data and provide car files to SP.
NOAA Coastal Lidar Data: NOAA is an agency that enriches life through science. Our reach goes from the surface of the sun to the depths of the ocean floor as we work to keep the public informed of the changing environment around them.
4D Nucleome (4DN): The 4D Nucleome Network aims to understand the principles behind the three-dimensional organization of the nucleus in space and time (the 4th dimension) and the role nuclear organization plays in gene expression and cellular function. The Network will utilize existing omics and imaging technologies as well as develop new ones to generate data and create resources to enable the study of the 4D Nucleome.
Nanopore Reference Human Genome: This dataset includes the sequencing and assembly of a reference standard human genome (GM12878) using the MinION nanopore sequencing instrument with the R9.4 1D chemistry.
Sentinel Near Real-time Canada Mirror: Near Real-time (NRT) Sentinel Mirror connected to the EU Copernicus programme, focused on Canadian coverage. In 2015, Canada joined the Sentinel collaborative ground segment which introduced an NRT Sentinel mirror site for users and programs inside the Government of Canada (GC).
University of British Columbia Sunflower Genome Dataset: This dataset is a catalogue of functionally important variation that can be used to create better-adapted sunflower varieties (e.g. developing breeding lines with improved drought tolerance) and to study the genetic mechanisms driving evolution and adaptation.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
NOAA Coastal Lidar Dataset
Released and archived 4DNucleome data
Nanopore Reference Human Genome
NRT Sentinel data in an S3 bucket broken down by sensor, product type and date.
UBC Sunflower Genome Data 1
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### How do you plan to prepare the dataset

lotus, singularity

### Please share a sample of the data

```text
https://registry.opendata.aws/noaa-coastal-lidar/
https://registry.opendata.aws/4dnucleome/
https://registry.opendata.aws/nanopore/
https://registry.opendata.aws/sentinel-products-ca-mirror/
https://registry.opendata.aws/ubc-sunflower-genome/
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

1 to 1.5 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, South America, Europe, Australia (continent)

### How will you be distributing your data to storage providers

HTTP or FTP server, Shipping hard drives, Lotus built-in data transfer

### How do you plan to choose storage providers

Slack, Filmine, Big data exchange

### How do you plan to make deals to your storage providers

Lotus client, Singularity

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 5PiB

**Expected weekly DataCap usage rate**
> 800TiB

**Client address**
>f14ckrd6rtf5suqk7vbrr567pvyarma6pwivscoea

**Comment by Aifabot-Cloud** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebki2vpag7artvzsqikpbdsaranxo63xr2optbblrqjvwr3kkxdjq 
#### Address 
> f14ckrd6rtf5suqk7vbrr567pvyarma6pwivscoea
#### Datacap Allocated
> 256.00TiB
#### Signer Address
> f174fg3bqbln3zjnkxtyf6s54txqkr7yqkj6cig7y
#### Id
> a9ae7922-42b4-4e3b-b152-674fd9509a7b
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebki2vpag7artvzsqikpbdsaranxo63xr2optbblrqjvwr3kkxdjq

**Comment by Meibuy** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecowezqae3tqixzi4elg6imf4rstwlpfultkdiafor4kq54hupizk 
#### Address 
> f14ckrd6rtf5suqk7vbrr567pvyarma6pwivscoea
#### Datacap Allocated
> 256.00TiB
#### Signer Address
> f1bwugfihrmn3iyunzyxst5nttql3dge4khwmurtq
#### Id
> a9ae7922-42b4-4e3b-b152-674fd9509a7b
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecowezqae3tqixzi4elg6imf4rstwlpfultkdiafor4kq54hupizk

**Comment by BobbyChoii** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb54el6zwcrmsgbpa4tczbrpavcjao6d2rjniqz5fy6ikc5bxoe4a 
#### Address 
> f14ckrd6rtf5suqk7vbrr567pvyarma6pwivscoea
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f1irqs2gmctiv3jcdfwuch7oxvf4ixh3k4b2wc24i
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb54el6zwcrmsgbpa4tczbrpavcjao6d2rjniqz5fy6ikc5bxoe4a

**Comment by TakiChain** [comment]
Thank you for integrating more trustworthy data into the network and please continue to follow fileplus' guidelines.

**Comment by TakiChain** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedmaom6qu3jthtq2vy463i2gdmggga45h7tqqf4kurjqmrstwltaq 
#### Address 
> f14ckrd6rtf5suqk7vbrr567pvyarma6pwivscoea
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f15impf3j2zcaex4lhyxndxswuuhv24vzstuqtxsi
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedmaom6qu3jthtq2vy463i2gdmggga45h7tqqf4kurjqmrstwltaq

**Comment by Suyanj** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecv3dje6lrah3g2ui4maumy47sdbfv2dknkard6b4w2sx3z73iukg 
#### Address 
> f14ckrd6rtf5suqk7vbrr567pvyarma6pwivscoea
#### Datacap Allocated
> 1.00PiB
#### Signer Address
> f1ihv7gz3vn3xqvikpt4rwryecgisl7745lodx3yi
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecv3dje6lrah3g2ui4maumy47sdbfv2dknkard6b4w2sx3z73iukg

**Comment by AthSmith** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedvwujpwpl733zjonoxtz7osg3rnlumvpuye6xgsnjn3dhvhndc72 
#### Address 
> f14ckrd6rtf5suqk7vbrr567pvyarma6pwivscoea
#### Datacap Allocated
> 1.00PiB
#### Signer Address
> f1vxbqrf7rfum3n6m5u6eb4re6xj7amvsaqnzu64y
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedvwujpwpl733zjonoxtz7osg3rnlumvpuye6xgsnjn3dhvhndc72

**Comment by cryptowhizzard** [comment]
Hi,

I have been checking on your application and SP's. None of them allow retrieval. Can you tell me why this is? 
This is against the rules of FIL+

I am interested in CID baga6ea4seaqftvuvldjh4wttbvrhp76266fclh6bm77dvbzgpq7zdkntwljzccy , deal - ID 35149980 and want to see the data you have been storing.

lotus state get-deal 35149980
{
  "Proposal": {
    "PieceCID": {
      "/": "baga6ea4seaqftvuvldjh4wttbvrhp76266fclh6bm77dvbzgpq7zdkntwljzccy"
    },
    "PieceSize": 34359738368,
    "VerifiedDeal": true,
    "Client": "f02130992",
    "Provider": "f02173949",
    "Label": "mAXCg5AIgKdIGewByY1YOxZfmL5bdhgDRkuefVWrjU5FAMm0LuhI",
    "StartEpoch": 2844943,
    "EndEpoch": 4385743,
    "StoragePricePerEpoch": "0",
    "ProviderCollateral": "9464109606315740",
    "ClientCollateral": "0"
  },
  "State": {
    "SectorStartEpoch": 2831194,
    "LastUpdatedEpoch": -1,
    "SlashEpoch": -1,
    "VerifiedClaim": 17464903
  }
}

<img width="1113" alt="Scherm­afbeelding 2023-05-05 om 18 11 51" src="https://user-images.githubusercontent.com/36404435/236511231-17dfb4bd-0168-4e37-bdb8-1571e89afade.png">
<img width="1297" alt="Scherm­afbeelding 2023-05-05 om 18 11 48" src="https://user-images.githubusercontent.com/36404435/236511235-cff4aff9-2b69-4e93-a5c7-ada9e84180d5.png">

**Comment by Casey-PG** [comment]
checker:manualTrigger

**Comment by Aifabot-Cloud** [comment]
The report looks healthy. Please keep your request in accordance with the principles of the program and in line with their allocation strategy.

**Comment by Aifabot-Cloud** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacectvb3sbq4pjyt63jiwc3l3xgiovzmbg625xk4zci6b3ecmpzdd5m 
#### Address 
> f14ckrd6rtf5suqk7vbrr567pvyarma6pwivscoea
#### Datacap Allocated
> 2.00PiB
#### Signer Address
> f174fg3bqbln3zjnkxtyf6s54txqkr7yqkj6cig7y
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacectvb3sbq4pjyt63jiwc3l3xgiovzmbg625xk4zci6b3ecmpzdd5m

**Comment by enochleon** [comment]
@cryptowhizzard Hi notary, it seems that the network of sp is a big influence on the retrieval. I will contact with them.

**Comment by TakiChain** [comment]
Hi, I noticed that the approval of our organization has drawn concern. From the perspective of Chinese enterprises, we would like to speak about the wall of data. Many nodes located in China are not downloaded consistently by other regions. This is a force majeure caused by geographic location and many geopolitical factors. It's impossible to change the root reason about it.

**Comment by TakiChain** [comment]
In our opinion, data retrievals don't require and cannot be done by all notaries, because these are limited and affected by the quality of network links and regional policies in each region, which is the main reason why the community needs to select so many notaries in each region. But for the DPs, the selected storage nodes need to be "subjectively" public to any regions for retrieval. We need to be aware of the subtle differences in the nature of these two things, especially for notaries.

We suggest that notaries who are currently unable to or can only partially successfully complete retrievals temporarily should not be anxious and can refer to the CID reports before you make the decision of signing. Don't forget that you do have the right to choose not to sign. The key indicators that are constantly updated are reflected in the CID reports by P.L., which are the main reference materials we use for our signing.

**Comment by enochleon** [comment]
@github-actions Thanks for the reminder.

**Comment by cryptowhizzard** [comment]
checker:manualTrigger

**Comment by cryptowhizzard** [comment]
@Aifabot-Cloud @enochleon @TakiChain 

Care to explain what is going on?

**Comment by herrehesse** [comment]
checker:manualTrigger

**Comment by cryptowhizzard** [comment]
Hi,

This application is solely working with SP's who have retrieval disabled and/or are involved in CID sharing abuse.

![Scherm­afbeelding 2023-07-31 om 13 25 07](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/36404435/bb67b43a-27c3-4b17-a386-9003cbad2853)

**Comment by Wengeding** [comment]
checker:manualTrigger

**Comment by cryptowhizzard** [comment]
All these SP's are involved in CID sharing and do not support retrieval, against FIL+ rules and guidelines.

<img width="1690" alt="Scherm­afbeelding 2023-07-31 om 18 07 53" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/36404435/8effcab1-f94d-4a1a-b233-3bc2a6e57553">
