### ISSUE TITLE
[DataCap Application] Shenzhen Chaowei Multi -Media Technology Co., Ltd. - life video archive

### ISSUE THREAD

**Issue by ChaoWWWei** [filecoin-project/filecoin-plus-large-datasets#1909]
### Data Owner Name

Shenzhen Chaowei Multi -Media Technology Co., Ltd.

### Data Owner Country/Region

China

### Data Owner Industry

Information, Media & Telecommunications

### Website

http://www.gzssywz.com/

### Social Media

```text
http://www.gzssywz.com/
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

500TiB

### On-chain address for first allocation

f1xcvrxxxp5a5a4f7bt5jfmjzi2qe6n3knom5ivoi

### Data Type of Application

Public, Open Commercial/Enterprise

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Shenzhen Chaowei Multi -Media Technology Co., Ltd. is a business conference exhibition, literary performance, etiquette celebration, party party, lighting audio leasing, stage design implementation, dance equipment leasing, photography camera, public relations planning, wedding planning and other conference services The comprehensive activity planning company that serves one of the etiquette models.
Ultra -maintenance multi -media is a team that specializes in, younger, super strong, and rich in cultural performance connotation. Pay attention to the fashion, taste, exquisite, innovative, and strive to create a new and elegant performance method. Adhering to the celebration performance culture of a new concept, the company, with a reasonable price, meticulous implementation, and high -quality services, unique performance resources have won unanimous praise from well -known enterprises, government agencies, and peers.
The company also specializes in an art group that provides performance services for many well -known enterprises, government agencies, advertising companies, and etiquette companies. Including: Host, singer dance, model etiquette, band, European and American band, DJ, Russian dance, magic acrobatics, human body painting, women's music house, clown, behavior art, human sculpture, fluorescent dance, shadow dance, electric drum drum , Women's Water Drums, Laser, Crystal Drums, Star Image Show, Street Dance, Extreme Bicycles, Famous Blue Balls, Cheerle Team, Shaolin Kung Fu.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
We have a large amount of materials to be stored. These materials are video materials accumulated by our team for a long time, which is a cultural memory.
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### How do you plan to prepare the dataset

lotus

### Please share a sample of the data

```text
https://drive.google.com/drive/folders/1LzxRgF-hxKF_4K9zJKcoD4EHYYOo3jyc?usp=share_link
https://drive.google.com/drive/folders/1GcVbg-SyXKWZVGN6o61q3JS-KVa4D7sS?usp=share_link
https://drive.google.com/drive/folders/1Gs0n2iJPg-iMqGs0EKMJlI9p0PI930EU?usp=share_link
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [x] I confirm

### What is the expected retrieval frequency for this data

Monthly

### For how long do you plan to keep this dataset stored on Filecoin

2 to 3 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America

### How will you be distributing your data to storage providers

Cloud storage (i.e. S3), HTTP or FTP server, Shipping hard drives

### How do you plan to choose storage providers

Slack, Partners

### How do you plan to make deals to your storage providers

Boost client, Lotus client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
Do these data belongs to you?
Could you send an email to filplus-app-review@fil.org with your official domain in order to confirm your identity? Email name should includes the issue id #1909.

**Comment by ChaoWWWei** [comment]
![image](https://user-images.githubusercontent.com/130637698/231974546-d383111c-a9b6-47f9-819c-fa4f5c805471.png)

Are you an official member? How should we proceed to the next step after we send the email? 
1. Yes, the data is our company's asset.
2. The email has been sent to the specified email address.

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 5PiB

**Expected weekly DataCap usage rate**
> 500TiB

**Client address**
>f1xcvrxxxp5a5a4f7bt5jfmjzi2qe6n3knom5ivoi

**Comment by zcfil** [comment]
After reading history, I have some questions：
Can you show more data？
Is your data publicly available？

**Comment by ChaoWWWei** [comment]
<img width="952" alt="000" src="https://user-images.githubusercontent.com/130637698/233037634-d9506a19-1308-47b4-93ce-c6fb5513f3f7.png">

Thank you @zcfil  for your interest, and please check out the screenshot above, which is the result of our years of operation.
As you can see, the data are almost at the top.
And then let me answer your second question, yes, our data is publicly available.

**Comment by zcfil** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedpwp4isff5ya53hdsw5fhnc2cdifvoxdcmfemai3trgsrdlschry 
#### Address 
> f1xcvrxxxp5a5a4f7bt5jfmjzi2qe6n3knom5ivoi
#### Datacap Allocated
> 250.00TiB
#### Signer Address
> f1cjzbiy5xd4ehera4wmbz63pd5ku4oo7g52cldga
#### Id
> 8daa5837-f706-4518-848f-5ff7f6dcd787
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedpwp4isff5ya53hdsw5fhnc2cdifvoxdcmfemai3trgsrdlschry

**Comment by zcfil** [comment]
@ChaoWWWei We have passed the review and look forward to your performance, making it bigger, stronger, and more brilliant

**Comment by ChaoWWWei** [comment]
> Which SPs do you plan to store data on?

Dear Notary, Thank you for your interest, please check this list, contact has been made so far.

| SP             | City | Region |
| ---- | ---- | ---- |
| f02036170 | Hong Kong | Hong Kong |
| f01927252 | Hounslow | United Kingdom |
| f02027952 | London    | United Kingdom |
| f02028326 | Los Angeles | United States |
| f02014107 | Seoul | South Korea |

**Comment by newwebgroup** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacea4hqos3xfnlkd6dqdnvmqi2qexxs3quzpmo7h7bg6n3c632u4vgo 
#### Address 
> f1xcvrxxxp5a5a4f7bt5jfmjzi2qe6n3knom5ivoi
#### Datacap Allocated
> 250.00TiB
#### Signer Address
> f1e77zuityhvvw6u2t6tb5qlnsegy2s67qs4lbbbq
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacea4hqos3xfnlkd6dqdnvmqi2qexxs3quzpmo7h7bg6n3c632u4vgo

**Comment by stcouldlisa** [comment]
![WechatIMG574](https://user-images.githubusercontent.com/112812896/234773240-36b4af60-e313-4324-a34a-a57946b9d0ab.png)

**Comment by stcouldlisa** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec4wm33njardjmknvxskdxk4zhr5hqps7ipt5usd3ibkahru3zy4k 
#### Address 
> f1xcvrxxxp5a5a4f7bt5jfmjzi2qe6n3knom5ivoi
#### Datacap Allocated
> 500.00TiB
#### Signer Address
> f1jvvltduw35u6inn5tr4nfualyd42bh3vjtylgci
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec4wm33njardjmknvxskdxk4zhr5hqps7ipt5usd3ibkahru3zy4k

**Comment by stcouldlisa** [comment]
checker:manualTrigger

**Comment by stcouldlisa** [comment]
Because it can be retrieved, I support you this round, but I found that your sp distribution is not reasonable, I will continue to pay attention, I think, this round, you need to be corrected immediately, thank you

**Comment by METAVERSEDATAMINING** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebcbnjz4xxko3zknfxmh4533wcy2kjfysh762ckskpae667cyfsn4 
#### Address 
> f1xcvrxxxp5a5a4f7bt5jfmjzi2qe6n3knom5ivoi
#### Datacap Allocated
> 500.00TiB
#### Signer Address
> f17idrnfnxl2mbgcgr57a6z2c6lj2qx56gvm3336i
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebcbnjz4xxko3zknfxmh4533wcy2kjfysh762ckskpae667cyfsn4

**Comment by ChaoWWWei** [comment]
> retrieval works,supporting this round.

Thanks for the support.

**Comment by cryptowhizzard** [comment]
Error: Failed to retrieve content with candidate miner f02121645: data transfer failed: deal errored: getting pieces for cid bafybeigtee6s5caphwq7zwoaueb44s3xcldv46cpixtakeumpjz4ndqwaq: getting pieces containing block bafybeigtee6s5caphwq7zwoaueb44s3xcldv46cpixtakeumpjz4ndqwaq: failed to lookup index for mh 1220d3213d2e880f3da1fcd9c0a103ce4b7712c75e784f45e605128c7a73c68e1604, err: datastore: key not found

It doesn't seem to work here. @stcouldlisa how did you test retrieval and from where?

**Comment by sxxfuture-official** [comment]
@ChaoWWWei 
> ⚠️ 1 storage providers sealed more than 30% of total datacap - [f02121645](https://filfox.info/en/address/f02121645): 51.01%
> ⚠️ 49.94% of deals are for data replicated across less than 4 storage providers.

According to the CID-Checker report, the above two problems exist, and the third round is about to start. I would like to know what plan you have to deal with the above two problems?

**Comment by ChaoWWWei** [comment]
This is mainly because the packaging speed of SP is inconsistent, and some will be faster.
Don't worry about this, the subsequent share will be strictly in accordance with the proportion promised in the application. We have temporarily stopped distribution to the highest nodes.


> @ChaoWWWei
> 
> > ⚠️ 1 storage providers sealed more than 30% of total datacap - [f02121645](https://filfox.info/en/address/f02121645): 51.01%
> > ⚠️ 49.94% of deals are for data replicated across less than 4 storage providers.
> 
> According to the CID-Checker report, the above two problems exist, and the third round is about to start. I would like to know what plan you have to deal with the above two problems?

**Comment by sxxfuture-official** [comment]
OK，hope it goes according to plan.
test retrieve well :
![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/113963951/f6055c3e-9034-44aa-80a3-b0e0dbc383f0)

**Comment by Bitrise0111** [comment]
checker:manualTrigger

**Comment by Bitrise0111** [comment]
Checked the checker report and saw the response above, hoping to see a healthier check report records in the next round. Tested retrieval data and it is working, below are the results of the retrieval test:
![4fb2c3f811eea23ca257331217320e9](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/116627599/817fde22-3dc7-4dc8-b311-8273e84fa1ba)

**Comment by Bitrise0111** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedhoct5cnu4xx6zahqfzte6kkeky72xotwo3th43zt4gjdlalregq 
#### Address 
> f1xcvrxxxp5a5a4f7bt5jfmjzi2qe6n3knom5ivoi
#### Datacap Allocated
> 1000.00TiB
#### Signer Address
> f1nknj7ayq4o43czrtdoauggtwl43fbqatmqis3yy
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedhoct5cnu4xx6zahqfzte6kkeky72xotwo3th43zt4gjdlalregq

**Comment by ChaoWWWei** [comment]
Sorry, recently due to personal health reasons, there is no way to follow up the project in time, and it was closed before leading to the target. How can I open it and continue to use it. Thanks!

**Comment by ChaoWWWei** [comment]
@galen-mcandrew @raghavrmadya Hello, due to the reasons of our technical colleagues, we did not follow up in time, and now it has returned to normal, please help to open this project, thank you

**Comment by ChaoWWWei** [comment]
Can you help me, how can I open it? We continue to use now, thank you。 @raghavrmadya @galen-mcandrew @Sunnyiscoming

**Comment by cryptowhizzard** [comment]
Recv 2.69 GiB, Paid 0 FIL, BlocksReceived (Ongoing), 1h51m27.249s [1692900211438769801|2888435488]
Recv 2.69 GiB, Paid 0 FIL, BlocksReceived (Ongoing), 1h51m27.319s [1692900211438769801|2888475716]
Recv 2.69 GiB, Paid 0 FIL, BlocksReceived (Ongoing), 1h51m27.347s [1692900211438769801|2888475770]
Recv 2.69 GiB, Paid 0 FIL, BlocksReceived (Ongoing), 1h51m28.165s [1692900211438769801|2888475854]
Recv 2.69 GiB, Paid 0 FIL, BlocksReceivRecv 2.691 GiB, Paid 0 FIL, BlocksReceived (Ongoing), 1h51m2Recv 2.691 GiB, Paid 0 FIL, BlocksReceived (Ongoing), 1h51m29.984s [1692900211438769801|2889538091]
Recv 2.691 GiB, Paid 0 FIL, ProviderCancelled (Cancelling), 2h24m46.911s [1692900211438769801|2889538091]
Recv 2.691 GiB, Paid 0 FIL, CancelRecv 2.693 GiB, Paid 0 FIL, ProviderCancelled (Cancelling), 2h24m47.642s [1692900211438769800|2891635243]
Recv 2.693 GiB, Paid 0 FIL, CancelComplete (Cancelled), 2h24m47.653s [1692900211438769800|2891635243]
ERROR: Retrieval Proposal Cancelled: Provider cancelled retrieval

**Comment by cryptowhizzard** [comment]
Dear ChaoWWWei,

As notary I am doing due diligence on your LDN. I could not get retrieval to work. Can you please upload the car file of CID baga6ea4seaqebujtstqnrrx4ys3vuklx7gddq2qj7bhoyo4co24mj5xwvkthqdy ?

You can use our upload system at http://send.datasetcreators.com. Please select 7 days for the system to keep the file and post the link you received here so I (and other notaries) can download your content.
