### ISSUE TITLE
[DataCap Application] NFT Printer Dataset[2/2]

### ISSUE THREAD

**Issue by CourteousBin** [filecoin-project/filecoin-plus-large-datasets#1910]
### Data Owner Name
NFTprinter Global AB

### Data Owner Country/Region
Sweden

### Data Owner Industry
Education & Training

### Website
[https://www.nft-printer.net](https://www.nft-printer.net)

### Social Media
none (none)

### Total amount of DataCap being requested
2.5 PiB

### Weekly allocation of DataCap requested
200 TiB

### On-chain address for first allocation
f1c2unlsfmqzgff3q25xep73nrfxygtujzeubbqqq

### Data Type of Application
Public, Open Commercial/Enterprise

### Custom multisig
No

### Share a brief history of your project and organization
NFT Printer is a unique platform that provides authentication for digital NFT assets as well as its physical counterpart. Contrary to traditional NFT services, we cover up several areas of the ecosystem and welcome all actors on the market to be a part of our community.

Our service is based on the idea of reproducing your digital NFT asset as a pshysical object, and turn it into a trackable item with its data stored in the blockchain. It is a secure, easy and unique way of NFT services that you wont find anywhere else.

### Is this project associated with other projects/ecosystem stakeholders?
No

### Describe the data being stored onto Filecoin
nft picture/video

### Where was the data currently stored in this dataset sourced from
My own storage infra

### How do you plan to prepare the dataset
lotus

### Please share a sample of the data
https://www.nft-printer.net/#/go-print/400
https://www.nft-printer.net/#/go-print/429
https://www.nft-printer.net/#/go-print/477

### Confirm that this is a public dataset that can be retrieved by anyone on the Network
Yes

### What is the expected retrieval frequency for this data
Yearly

### For how long do you plan to keep this dataset stored on Filecoin
More than 3 years

### In which geographies do you plan on making storage deals
Europe

### How will you be distributing your data to storage providers
Shipping hard drives

### How do you plan to choose SP
Slack

### How do you plan to make deals to your storage providers
Lotus client

### Can you confirm that you will follow the Fil+ guideline
Yes

_Application created via [filplus.storage](https://filplus.storage)_

**Comment by Sunnyiscoming** [comment]
Can you provide more data samples to prove that you have 2.5 PB data already?
Please share more detailed information about sps you will cooperate with.

**Comment by Sunnyiscoming** [comment]
It will be closed if there is no reply in 3 days.

**Comment by CourteousBin** [comment]
@Sunnyiscoming https://drive.google.com/file/d/1Sj1AuT55SHGwk8QPCDM1EopLkgzfiQf_/view?usp=sharing

**Comment by CourteousBin** [comment]
@Sunnyiscoming 
Any more questions?

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 2.5PiB

**Expected weekly DataCap usage rate**
> 200TiB

**Client address**
>f1c2unlsfmqzgff3q25xep73nrfxygtujzeubbqqq

**Comment by zcfil** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceakxcmljwzns26ef2sahgetwkfcxpmctn4woftmbjsufjhgfeapte 
#### Address 
> f1c2unlsfmqzgff3q25xep73nrfxygtujzeubbqqq
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1cjzbiy5xd4ehera4wmbz63pd5ku4oo7g52cldga
#### Id
> 4e2d8392-cf24-467f-b9f2-cbea89c4005c
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceakxcmljwzns26ef2sahgetwkfcxpmctn4woftmbjsufjhgfeapte

**Comment by CourteousBin** [comment]
@zcfil 
Thank you very much for approving my proposal! 

I truly appreciate your time and effort in reviewing and evaluating it. 

Your support means a lot to me and I will do my best to make this project a success.

**Comment by zcfil** [comment]
@CourteousBin 
You're welcome, it's the responsibility of a notary public

**Comment by laurarenpanda** [comment]
This application Looks great!
Have you already done the KYC/KYB process?
If not, please email [filplus-app-review@fil.org](mailto:filplus-app-review@fil.org) with your official domain to confirm your identity.
Please includes this issue id https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1910.
And @Sunnyiscoming, please give a hand to verify and confirm the KYB.

**Comment by CourteousBin** [comment]
Hi, @laurarenpanda 
KYC email has been sent, please check again.

**Comment by CourteousBin** [comment]
Hi, @Sunnyiscoming
KYC email has been sent, please check again.

**Comment by CourteousBin** [comment]
Hi, @Sunnyiscoming
KYC email has been sent, please check again.

**Comment by MRJAVAZHAO** [comment]
Sorry for late reply.
I have received that.
![image](https://user-images.githubusercontent.com/47096545/234733449-50cd247f-858a-47ba-8da7-bd6197491415.png)
The registration of NFTprinter Global AB was attached in the email.

**Comment by Sunnyiscoming** [comment]
![image](https://user-images.githubusercontent.com/105098820/235030260-c56d85a8-437b-47be-b91c-268dec568470.png)
![image](https://user-images.githubusercontent.com/105098820/235030141-64df1ea6-24d6-4839-8cd4-175d629d6b99.png)

**Comment by Sunnyiscoming** [comment]
@laurarenpanda The email has been received. It Looks good.

**Comment by CourteousBin** [comment]
@Sunnyiscoming 

I truly appreciate your time and effort in reviewing and evaluating it.

**Comment by maxvint** [comment]
Looks good, willing to support the first round.

**Comment by maxvint** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecpdqxzruudaqqsxsbujsxcsz3v4e6dnsmoofmwpac2v53yebjnc4 
#### Address 
> f1c2unlsfmqzgff3q25xep73nrfxygtujzeubbqqq
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1ui5iy4mmkxjbw7752omiwp2ols2fzv4thrayagi
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecpdqxzruudaqqsxsbujsxcsz3v4e6dnsmoofmwpac2v53yebjnc4

**Comment by CourteousBin** [comment]
Thank @maxvint ,

Your support means a lot to me and I will do my best to make this project a success.

**Comment by laurarenpanda** [comment]
checker:manualTrigger

**Comment by laurarenpanda** [comment]
Since the KYB has been confirmed and the Checker report looks excellent for the 1st
 round, I'm willing to support it.

<img width="732" alt="截屏2023-05-09 13 59 05" src="https://user-images.githubusercontent.com/74699939/237008090-a774faf9-beeb-4087-87a6-e233a659abc0.png">

**Comment by laurarenpanda** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceccwujobxudet26ejqbwcqsvmz6vhyz4s56jfl6qg7crur6wumb76 
#### Address 
> f1c2unlsfmqzgff3q25xep73nrfxygtujzeubbqqq
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1bp3tzp536edm7dodldceekzbsx7zcy7hdfg6uzq
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceccwujobxudet26ejqbwcqsvmz6vhyz4s56jfl6qg7crur6wumb76

**Comment by destor2023** [comment]
![image1](https://user-images.githubusercontent.com/46444977/237044075-21aa6dfa-d94f-4413-8cfa-c761acb11926.png)

CID checker ok, retrieval can be done. Willing to support!

**Comment by destor2023** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebetlkq4ysalhhl66hid6nshqprobes2wsmwlqt52i5p7yxjxjgcs 
#### Address 
> f1c2unlsfmqzgff3q25xep73nrfxygtujzeubbqqq
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1yh6q3nmsg7i2sys7f7dexcuajgoweudcqj2chfi
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebetlkq4ysalhhl66hid6nshqprobes2wsmwlqt52i5p7yxjxjgcs

**Comment by laurarenpanda** [comment]
Have chatted with this client this morning.
It seems they didn't receive DC since the LDN v3.1 didn't have enough DC balance.
So I'll try to sign this application again.

**Comment by laurarenpanda** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced3lybge3kpfaggbucvkntr7ecx55cawyy27cp46z3zkmfchff6nq 
#### Address 
> f1c2unlsfmqzgff3q25xep73nrfxygtujzeubbqqq
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1bp3tzp536edm7dodldceekzbsx7zcy7hdfg6uzq
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced3lybge3kpfaggbucvkntr7ecx55cawyy27cp46z3zkmfchff6nq

**Comment by Fatman13** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb3vf7bmq5cpivffqnncfprjvgb4ndsxpwphmxnbzou74um7ge5ea 
#### Address 
> f1c2unlsfmqzgff3q25xep73nrfxygtujzeubbqqq
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1j3u7crhjzwb2cj5mq7vodlt4o66yoyci7lhcauy
#### Id
> df19e5d8-1c19-4e7f-a178-9056490a12ed
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb3vf7bmq5cpivffqnncfprjvgb4ndsxpwphmxnbzou74um7ge5ea

**Comment by Fatman13** [comment]
Reached out by client on Slack. Everything looks good.

**Comment by CourteousBin** [comment]
@laurarenpanda , @Fatman13,

Thanks to the community notary for checking, 

we will do my best to make this project a success.

**Comment by zcfil** [comment]
checker:manualTrigger

**Comment by Joss-Hua** [comment]
![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/75723122/a4446e81-9d5b-4f4d-87a4-c88a48e2b27b)

**Comment by jomozz** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaj5pbgluoxh6p5bb73kcdbm4b3imnmz2hzchc7ghgt76swexg26q 
#### Address 
> f1c2unlsfmqzgff3q25xep73nrfxygtujzeubbqqq
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1qpdwt2f2fse74nl5wi27uk5jcyqqqyil47yqt7i
#### Id
> f603ef5d-bc22-4107-87df-420d2aa1fb73
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaj5pbgluoxh6p5bb73kcdbm4b3imnmz2hzchc7ghgt76swexg26q

**Comment by jomozz** [comment]
your report looks healthy,  and I will continue to pay attention to it.

**Comment by CourteousBin** [comment]
@Joss-Hua @jomozz ,

Thanks to the community notary for checking,

we will do my best to make this project a success.

**Comment by CourteousBin** [comment]
checker:manualTrigger

**Comment by Patapon0702** [comment]
checker:manualTrigger

**Comment by YuanHeHK** [comment]
![mmexport1686643677302](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/69455705/cec9859c-3b4e-4bc4-9841-939eca3c0cfe)
There is no problem with the robot health report, I try to retrieve a cid is also normal, it seems that this application is healthy at the moment, I will support it this time

**Comment by YuanHeHK** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebibfdspg35urukhlpq5q5aie72jitagxynf7j3vgxh4o2quviygk 
#### Address 
> f1c2unlsfmqzgff3q25xep73nrfxygtujzeubbqqq
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1fg6jkxsr3twfnyhdlatmq36xca6sshptscds7xa
#### Id
> 710f6c5a-ceb9-41c1-b42d-6f5c1ce5a97e
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebibfdspg35urukhlpq5q5aie72jitagxynf7j3vgxh4o2quviygk

**Comment by CourteousBin** [comment]
@YuanHeHK ,

Thanks to the community notary for checking,

we will do my best to make this project a success.

**Comment by Bitrise0111** [comment]
This is the retrieval, and check report shows healthy

![56687988242ceb903634c983e0b51ed](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/116627599/cd3d9d02-3782-4311-8e8b-d6cb3ec8a26c)

**Comment by Bitrise0111** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedfdjczqgil7j67p7itw3waysqmwpuw6nndlv7vuo2zgvls7uijls 
#### Address 
> f1c2unlsfmqzgff3q25xep73nrfxygtujzeubbqqq
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1nknj7ayq4o43czrtdoauggtwl43fbqatmqis3yy
#### Id
> 710f6c5a-ceb9-41c1-b42d-6f5c1ce5a97e
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedfdjczqgil7j67p7itw3waysqmwpuw6nndlv7vuo2zgvls7uijls

**Comment by CourteousBin** [comment]
@Bitrise0111 ,

Thanks to the community notary for checking,

we will do my best to make this project a success.

**Comment by CourteousBin** [comment]
checker:manualTrigger

**Comment by bq1024** [comment]
The report indicates that the overall retrieval success rate is very low, can you improve it?

**Comment by CourteousBin** [comment]
@bq1024 

We have communicated with SP and they are improving the retrieval success rate, 

with some tests showing improvements in retrieval speed and success rates of 70-80%.


![data](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/31603455/5610697b-ec68-47fe-b531-36137fd3938b)

**Comment by spaceT9** [comment]
checker:manualTrigger

**Comment by kernelogic** [comment]
CID report looks good. Retrieval report needs some improvement but I see client is willing to improve.

**Comment by kernelogic** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceao4zuajcgzo3524iqzo54pozrhscjn6uw7bnhrwvbjftjsjdlthu 
#### Address 
> f1c2unlsfmqzgff3q25xep73nrfxygtujzeubbqqq
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### Id
> 3ab09e39-82a6-443b-9546-385108215325
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceao4zuajcgzo3524iqzo54pozrhscjn6uw7bnhrwvbjftjsjdlthu

**Comment by CourteousBin** [comment]
@kernelogic 

Thanks to the community notary for checking,

we will do my best to make this project a success.

**Comment by laurarenpanda** [comment]
checker:manualTrigger

**Comment by laurarenpanda** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecyfzey7hzpurkrbqjcpzekjs234ngefeg2gumw7wxfguxqykpkwe 
#### Address 
> f1c2unlsfmqzgff3q25xep73nrfxygtujzeubbqqq
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1bp3tzp536edm7dodldceekzbsx7zcy7hdfg6uzq
#### Id
> 3ab09e39-82a6-443b-9546-385108215325
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecyfzey7hzpurkrbqjcpzekjs234ngefeg2gumw7wxfguxqykpkwe

**Comment by CourteousBin** [comment]
checker:manualTrigger

**Comment by spaceT9** [comment]
checker:manualTrigger

**Comment by spaceT9** [comment]
CID reports of last rounds are healthy, the retrieval rate is low but increasing obviously. Hope you can improve the retrieval rate next tranche. Love to see LDN from Sweden, support diversity!

**Comment by spaceT9** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedbwibvv66rjle5xz7xdl4mo5vxqejo2jqlocbahkq4gpq7hq3ez4 
#### Address 
> f1c2unlsfmqzgff3q25xep73nrfxygtujzeubbqqq
#### Datacap Allocated
> 260.00TiB
#### Signer Address
> f1dktm3abgn7wkpepxab4q3eaw24qktizk4esfzyy
#### Id
> 70658270-3ead-4c11-af16-aeba854c5a22
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedbwibvv66rjle5xz7xdl4mo5vxqejo2jqlocbahkq4gpq7hq3ez4

**Comment by spaceT9** [comment]
> @spaceT9
> 
> Can you please check [filecoin-project/notary-governance#916](https://github.com/filecoin-project/notary-governance/issues/916)

Thank you!

There are too many applications in dispute recently, there were no labels “in dispute” or “under governance review” against this LDN or relevant comment, that’s why I missed the information you mentioned above. I signed the application based on the good past performance.

To avoid other notaries accidently sign the disputed applications like me, it would be thoughtful if you leave a comment under the LDN once you report any abusive behavior.
