### ISSUE TITLE
Lidar+4DN+Nanopore+Sentinel+Sunflower Genome

### ISSUE THREAD

**Issue by anbaichao1224** [filecoin-project/filecoin-plus-large-datasets#1911]
### Data Owner Name

filecoin_lin

### Data Owner Country/Region

Afghanistan

### Data Owner Industry

Arts & Recreation

### Website

https://www.ncbi.nlm.nih.gov/sra/docs/sra-aws-download/

### Social Media

```text
Lidar+4DN+Nanopore+Sentinel+Sunflower Genome
```

### Total amount of DataCap being requested

200TiB

### Weekly allocation of DataCap requested

700TiB

### On-chain address for first allocation

Long release cycle of pledge currency

### Data Type of Application

None

### Custom multisig

- [X] Use Custom Multisig

### Share a brief history of your project and organization

```text
Lidar+4DN+Nanopore+Sentinel+Sunflower Genome
```

### Is this project associated with other projects/ecosystem stakeholders?

Yes

### If answered yes, what are the other projects/ecosystem stakeholders

```text
Lidar+4DN+Nanopore+Sentinel+Sunflower Genome
```

### Describe the data being stored onto Filecoin

```text
Lidar+4DN+Nanopore+Sentinel+Sunflower Genome
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### If you answered "Other" in the previous question, enter the details here

```text
Lidar+4DN+Nanopore+Sentinel+Sunflower Genome
```

### Please share a sample of the data

```text
Lidar+4DN+Nanopore+Sentinel+Sunflower Genome
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Weekly

### For how long do you plan to keep this dataset stored on Filecoin

1 to 1.5 years

### In which geographies do you plan on making storage deals

Greater China

### How will you be distributing your data to storage providers

Cloud storage (i.e. S3)

### How do you plan to choose storage providers

Filmine

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
Your application lacks of some key information.
Can you provide more information about your organization?
Can you provide the address?
