### ISSUE TITLE
[DataCap Application] ipfspan

### ISSUE THREAD

**Issue by fc221** [filecoin-project/filecoin-plus-large-datasets#1916]
### Data Owner Name
ipfspan

### Data Owner Country/Region
China

### Data Owner Industry
Other

### Website
[https://ipfspan.com](https://ipfspan.com)

### Social Media
@ChenFan98306187 (twitter)

### Total amount of DataCap being requested
5 PiB

### Weekly allocation of DataCap requested
1 PiB

### On-chain address for first allocation
f156zibnmp5vffl6vcbcntmnadhive5yf7ww5b62i

### Data Type of Application
Public, Open Dataset (Research/Non-Profit)

### Custom multisig
No

### Share a brief history of your project and organization
ipfspan drive

### Is this project associated with other projects/ecosystem stakeholders?
No

### Describe the data being stored onto Filecoin
user dirve data

### Where was the data currently stored in this dataset sourced from
My own storage infra

### How do you plan to prepare the dataset
IPFS

### Please share a sample of the data
QmekfRymYbdMUGJcU9WeX9iV282aUKAmeptgcC1cTrb3bc
QmZbQ5KA1ouqWX2e7BSSB9NAkXcUP9kTHyxAe5JmVfGDSb

### Confirm that this is a public dataset that can be retrieved by anyone on the Network
Yes

### What is the expected retrieval frequency for this data
Daily

### For how long do you plan to keep this dataset stored on Filecoin
Permanently

### In which geographies do you plan on making storage deals
Greater China

### How will you be distributing your data to storage providers
IPFS

### How do you plan to choose SP
I don't know yet

### How do you plan to make deals to your storage providers
I don't know yet

### Can you confirm that you will follow the Fil+ guideline
Yes

_Application created via [filplus.storage](https://filplus.storage)_

**Comment by Sunnyiscoming** [comment]
Are user dirve data public? How do you prove it?

**Comment by Sunnyiscoming** [comment]
Can you provide more data samples directly, not the cid of the onchain data?

**Comment by fc221** [comment]
> 用户驱动数据是否公开？你如何证明它？

https://www.ipfspan.com/faq
You can see the program description on this page.
username: test
password: test

**Comment by Sunnyiscoming** [comment]
Any update here?

**Comment by Sunnyiscoming** [comment]
Close for no reply.
