### ISSUE TITLE
[DataCap Application] <Organization> - <Project Name>

### ISSUE THREAD

**Issue by zhong-ta** [filecoin-project/filecoin-plus-large-datasets#1921]
### Data Owner Name

PhotographicFeeling

### Data Owner Country/Region

China

### Data Owner Industry

Information, Media & Telecommunications

### Website

https://photographicfeeling.com/

### Social Media

```text
https://photographicfeeling.com/
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

700TiB

### On-chain address for first allocation

f1q5wggpnt72umthnldc4kvms2odsig32aknafl2i

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
The word photography is derived from the Greek words φω phos (light) and γραφι graphis (painting, drawing) or γραφη graphê, which together mean "to draw with light". It refers to the process of using a special equipment for image recording, generally using mechanical cameras or digital cameras for photography. Sometimes photography is also referred to as photography, which is the process of exposing a photosensitive medium through the light reflected by an object. Someone has said an incisive phrase: the photographer's ability is to transform the fleeting mundane things of everyday life into immortal visual images.
Photography is a photographic application science with the formation and development of traditional photography technology, which is based on photographic optics, photographic chemistry and electronic technology, and has formed a unique shooting system in long-term practice.
Generally referred to as photography, that is, the use of a camera, image on the negative, print the negative into a single photo, one by one for permanent preservation. However, the image of the photo is motionless and silent, only for people to see its characters, artistic conception, and then experience its meaning. The earliest surviving photograph in the world dates back to 1827 by the Frenchman Joseph Nieps.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
The truth is the best photo, the best propaganda
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### How do you plan to prepare the dataset

singularity

### Please share a sample of the data

```text
https://pan.baidu.com/s/14XQhcfVBj3zx3LJZBnpaFA Extract the code: 33q4
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Monthly

### For how long do you plan to keep this dataset stored on Filecoin

More than 3 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China

### How will you be distributing your data to storage providers

HTTP or FTP server, Shipping hard drives

### How do you plan to choose storage providers

Slack, Partners

### How do you plan to make deals to your storage providers

Boost client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by herrehesse** [comment]
checker:manualTrigger

**Comment by herrehesse** [comment]
@kevzak Close this application please.
