### ISSUE TITLE
[DataCap Application] <PhotographicFeeling> - <Photographic>

### ISSUE THREAD

**Issue by zhong-ta** [filecoin-project/filecoin-plus-large-datasets#1922]
### Data Owner Name

PhotographicFeeling

### Data Owner Country/Region

China

### Data Owner Industry

Information, Media & Telecommunications

### Website

https://photographicfeeling.com/

### Social Media

```text
https://photographicfeeling.com/
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

700TiB

### On-chain address for first allocation

f1q5wggpnt72umthnldc4kvms2odsig32aknafl2i

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
The word photography is derived from the Greek words φω phos (light) and γραφι graphis (painting, drawing) or γραφη graphê, which together mean "to draw with light". It refers to the process of using a special equipment for image recording, generally using mechanical cameras or digital cameras for photography. Sometimes photography is also referred to as photography, which is the process of exposing a photosensitive medium through the light reflected by an object. Someone has said an incisive phrase: the photographer's ability is to transform the fleeting mundane things of everyday life into immortal visual images.
Photography is a photographic application science with the formation and development of traditional photography technology, which is based on photographic optics, photographic chemistry and electronic technology, and has formed a unique shooting system in long-term practice.
Generally referred to as photography, that is, the use of a camera, image on the negative, print the negative into a single photo, one by one for permanent preservation. However, the image of the photo is motionless and silent, only for people to see its characters, artistic conception, and then experience its meaning. The earliest surviving photograph in the world dates back to 1827 by the Frenchman Joseph Nieps.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
The truth is the best photo, the best propaganda
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### How do you plan to prepare the dataset

singularity

### Please share a sample of the data

```text
https://pan.baidu.com/s/14XQhcfVBj3zx3LJZBnpaFA Extract the code: 33q4
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Monthly

### For how long do you plan to keep this dataset stored on Filecoin

More than 3 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, South America, Europe

### How will you be distributing your data to storage providers

HTTP or FTP server, Shipping hard drives

### How do you plan to choose storage providers

Slack, Big data exchange

### How do you plan to make deals to your storage providers

Boost client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by zhong-ta** [comment]
We are a group of young people with youthful vitality and the purpose of happy work. We don't have complex departmental hierarchies, our team is in the photography industry, collecting and photographing interesting things.

I'm looking for a partner sp

**Comment by Sunnyiscoming** [comment]
Is the data you want to store produced by yourselves?

**Comment by zhong-ta** [comment]
yes

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 5PiB

**Expected weekly DataCap usage rate**
> 700TiB

**Client address**
>f1q5wggpnt72umthnldc4kvms2odsig32aknafl2i

**Comment by Sunnyiscoming** [comment]
Hope to get more information about your group.

**Comment by zcfil** [comment]
dear,

Thank you for applying for datacap. As a Filecoin FIL+Notary Public, I am currently screening your application and conducting due diligence.

Looking at your application, I have some questions:

Because you are a novice on Github and do not have a history of past applications. Can you introduce who you are and your company?

You declare that you are a data preparer. What hardware do you have on your end to prepare this dataset? What is your internet connection speed? Have you downloaded the data locally?

In my opinion, there are many datacaps that apply for 5PB. People need to have a comprehensive understanding of Filecoin, data packaging, data distribution, and all the requirements that come with it. Are you a novice in the Filecoin field, or have you previously applied for datacap on different Github account names?

Can you show us some visible evidence of the size of your data and the storage/packaging hardware you have?

As a final question, I would like you to fill out [this form](https://form.jotform.com/230953098450156) in order to provide us with the necessary information to make a wise decision on your LDN request when we are willing to support it.

thank you!

**Comment by zhong-ta** [comment]
> dear,
> 
> Thank you for applying for datacap. As a Filecoin FIL+Notary Public, I am currently screening your application and conducting due diligence.
> 
> Looking at your application, I have some questions:
> 
> Because you are a novice on Github and do not have a history of past applications. Can you introduce who you are and your company?
> 
> You declare that you are a data preparer. What hardware do you have on your end to prepare this dataset? What is your internet connection speed? Have you downloaded the data locally?
> 
> In my opinion, there are many datacaps that apply for 5PB. People need to have a comprehensive understanding of Filecoin, data packaging, data distribution, and all the requirements that come with it. Are you a novice in the Filecoin field, or have you previously applied for datacap on different Github account names?
> 
> Can you show us some visible evidence of the size of your data and the storage/packaging hardware you have?
> 
> As a final question, I would like you to fill out [this form](https://form.jotform.com/230953098450156) in order to provide us with the necessary information to make a wise decision on your LDN request when we are willing to support it.
> 
> thank you!

I am the main leader of our team, and our team is committed to shooting, editing, and collecting good photographic works and images
We have our own high-performance server that fully meets the requirements for generating car files, and we have 3GB of enterprise dedicated bandwidth. The data hard drive used is 6T-16T, so our data is stored on our own server without the need to download additional data
Have a detailed understanding of filplus and a complete understanding of data generation and distribution.
![Uploading IMG_1784.png…]()

**Comment by zhong-ta** [comment]
I am the main leader of our team, and our team is committed to shooting, editing, and collecting good photographic works and images
We have our own high-performance server that fully meets the requirements for generating car files, and we have 3GB of enterprise dedicated bandwidth. The data hard drive used is 6T-16T, so our data is stored on our own server without the need to download additional data
Have a detailed understanding of filplus and a complete understanding of data generation and distribution.
![企业微信截图_16823887794030(1)](https://user-images.githubusercontent.com/131101683/234162950-b71050b9-3fc5-4bc1-a4e0-9d9671ea0df7.png)

**Comment by igoovo** [comment]
First round support, I hope the packaging process follows the rules, and I will also keep an eye on it.

**Comment by igoovo** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacea24c5ocaiu5i7vtd7bs7e4znqvfntczzfsyf2fimwxar7zocf46s 
#### Address 
> f1q5wggpnt72umthnldc4kvms2odsig32aknafl2i
#### Datacap Allocated
> 256.00TiB
#### Signer Address
> f1shnsfayxqll77svffaxnjenms7bbbysbqcatrpy
#### Id
> 5619137e-96b6-498a-85d1-c28aef61b7ac
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacea24c5ocaiu5i7vtd7bs7e4znqvfntczzfsyf2fimwxar7zocf46s

**Comment by zcfil** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceauhcnzacx7efvjfigxeg5kopovijhhdzhla3mkuh3afzdtpd77nq 
#### Address 
> f1q5wggpnt72umthnldc4kvms2odsig32aknafl2i
#### Datacap Allocated
> 256.00TiB
#### Signer Address
> f1cjzbiy5xd4ehera4wmbz63pd5ku4oo7g52cldga
#### Id
> 5619137e-96b6-498a-85d1-c28aef61b7ac
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceauhcnzacx7efvjfigxeg5kopovijhhdzhla3mkuh3afzdtpd77nq

**Comment by zcfil** [comment]
Received your form, passed this review, and will continue to follow in the future

**Comment by zhong-ta** [comment]
@Sunnyiscoming I don't know if I need to reply to the message in a timely manner. Can you help me reopen this？

**Comment by zhong-ta** [comment]
@galen-mcandrew @raghavrmadya @Kevin-FF-USA

**Comment by zhong-ta** [comment]
Or can only reapply？

**Comment by zhong-ta** [comment]
Or can only reapply？

**Comment by herrehesse** [comment]
checker:manualTrigger
