### ISSUE TITLE
[DataCap Application] <Organization> - <Project Name>

### ISSUE THREAD

**Issue by zhogntao** [filecoin-project/filecoin-plus-large-datasets#1924]
### Data Owner Name

Beijing Bazuo Architectural Design Firm

### Data Owner Country/Region

China

### Data Owner Industry

Construction, Property & Real Estate

### Website

https://bazuoarchitecture.com/

### Social Media

```text
https://bazuoarchitecture.com/
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

700TiB

### On-chain address for first allocation

f143rrb33ygtwcc5v3drbdlivceknjfn5mii37wvi

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Jingbazuo Architectural Design Firm Co., Ltd. was established on May 29, 2013. Legal representative Wang Miao, the company's business scope includes: engineering survey and engineering design; Construction project management; Urban landscaping construction; Technical promotion services: computer graphic design; Computer animation design, etc.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
Refers to assets constructed manually, belonging to the category of fixed assets, including two categories: houses and structures. A house refers to an engineering building designed for people to live, work, study, produce, operate, entertain, store items, and engage in other social activities. The difference from buildings is structures, which refer to engineering buildings other than houses, such as walls, roads, dams, wells, tunnels, water towers, bridges, and chimneys.
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### How do you plan to prepare the dataset

singularity

### Please share a sample of the data

```text
https://cloud.189.cn/t/feeAnaq6Bvy2 （访问码：wi6m）
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Monthly

### For how long do you plan to keep this dataset stored on Filecoin

More than 3 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, Africa, North America, South America, Europe, Australia (continent), Antarctica

### How will you be distributing your data to storage providers

HTTP or FTP server, Shipping hard drives

### How do you plan to choose storage providers

Slack, Big data exchange

### How do you plan to make deals to your storage providers

Boost client, Lotus client, Singularity

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by herrehesse** [comment]
checker:manualTrigger

**Comment by herrehesse** [comment]
@kevzak Close this application please.
