### ISSUE TITLE
[DataCap Application] GuaZi Dynamic - Open Sustainability Data [4/6]

### ISSUE THREAD

**Issue by Fatman13** [filecoin-project/filecoin-plus-large-datasets#1925]
### Data Owner Name

Guazi Dynamic

### Data Owner Country/Region

China

### Data Owner Industry

Environment

### Website

guazi.io

### Social Media

```text
Slack: @Fatman13
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

1PiB

### On-chain address for first allocation

f1wuonkzwthnrt2tlo4dafgxr4uwhctv6osefb7uq

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Guazi has been with filecoin since Testnets and Space Race. We continue to bridging the gap between storage client and filecoin.
We have developed systems on top of Venus and ready to onboard large amount of data onto filecoin network.
```

### Is this project associated with other projects/ecosystem stakeholders?

Yes

### If answered yes, what are the other projects/ecosystem stakeholders

```text
CN SPWG, venushub program, SPs we have closely worked with in the past.

https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1337
```

### Describe the data being stored onto Filecoin

```text
The datasets we will be on-boarding onto Filecoin network are critical open source research datasets on sustainability, which may include but not not limited to the following...

Prediction Of Worldwide Energy Resources (POWER) Project
GOES-18 Data
Next Generation Weather Radar (NEXRAD)
Global Mangrove Watch (GMW) dataset
Digital Earth Africa (DE Africa)
Water Observations from Space (WOfS)
...

More information can be found at https://registry.opendata.aws/tag/sustainability/
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### How do you plan to prepare the dataset

others/custom tool

### If you answered "other/custom tool" in the previous question, enter the details here

```text
venus.filecoin.io
```

### Please share a sample of the data

```text
https://www.globalmangrovewatch.org/
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

1 to 1.5 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, Europe

### How will you be distributing your data to storage providers

Shipping hard drives

### How do you plan to choose storage providers

Slack, Partners, Others

### If you answered "Others" in the previous question, what is the tool or platform you plan to use

```text
Also with CN SPWG and venushub program
```

### How do you plan to make deals to your storage providers

Others/custom tool

### If you answered "Others/custom tool" in the previous question, enter the details here

```text
droplet.venus-fil.io
```

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
See questions in https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1927.

**Comment by Fatman13** [comment]
> See questions in https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1927.

kk, replied at https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1927#issuecomment-1517501536

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 5PiB

**Expected weekly DataCap usage rate**
> 1PiB

**Client address**
>f1wuonkzwthnrt2tlo4dafgxr4uwhctv6osefb7uq

**Comment by Carohere** [comment]
Hi @Fatman13, 
```
The datasets we will be on-boarding onto Filecoin network are critical open source research datasets on sustainability, which may include but not not limited to the following...

Prediction Of Worldwide Energy Resources (POWER) Project
GOES-18 Data
Next Generation Weather Radar (NEXRAD)
Global Mangrove Watch (GMW) dataset
Digital Earth Africa (DE Africa)
Water Observations from Space (WOfS)
```

the datasets are many and not fully enumerated, future retrieval will not be able to pinpoint the dataset. This creates difficulties for notaries to determine if the actual storage matches the request description. I would like to learn why you chose these datasets and if is there any particular reason you didn't file applications one by one.

FYI - there is still controversy regarding requests from non-data owners with merged datasets in the community. Please see https://github.com/filecoin-project/notary-governance/issues/832

**Comment by Fatman13** [comment]
Hello, @Carohere 

> the datasets are many and not fully enumerated, future retrieval will not be able to pinpoint the dataset.

What do you mean by "not fully enumerated"? If notaries are having trouble retrieving, they are free to reach out to me for technical support.

> FYI - there is still controversy regarding requests from non-data owners with merged datasets in the community. 

AFAIK, these are not incorporated into f+ rules.

**Comment by kernelogic** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecmevtphjxrs2gfai2zqiz73jv4gfalxx2elphfo2p4jpdwwd3a5a 
#### Address 
> f1wuonkzwthnrt2tlo4dafgxr4uwhctv6osefb7uq
#### Datacap Allocated
> 256.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecmevtphjxrs2gfai2zqiz73jv4gfalxx2elphfo2p4jpdwwd3a5a

**Comment by kernelogic** [comment]
In support for well known community contributor

**Comment by laurarenpanda** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedfpzpx7fkkrgdkoaclw3hgk2jtq6nowhjkjcbjkq4vnwoygtfxos 
#### Address 
> f1wuonkzwthnrt2tlo4dafgxr4uwhctv6osefb7uq
#### Datacap Allocated
> 256.00TiB
#### Signer Address
> f1bp3tzp536edm7dodldceekzbsx7zcy7hdfg6uzq
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedfpzpx7fkkrgdkoaclw3hgk2jtq6nowhjkjcbjkq4vnwoygtfxos

**Comment by Fatman13** [comment]
Hello, team, CC @Sunnyiscoming,

How do I reopen this?

**Comment by Fatman13** [comment]
Hello, team, CC @Kevin-FF-USA,

How do I reopen this LDN?

**Comment by Fatman13** [comment]
Hello, team, CC @simonkim0515 

Quick update, ready to prep the data again and restart dc allocation.

**Comment by spaceT9** [comment]
checker:manualTrigger

**Comment by liyunzhi-666** [comment]
checker:manualTrigger

**Comment by liyunzhi-666** [comment]
- CID sharing does not seem to be any problem.
- But there is one thing, the success rate of SP retrieval seems a bit low, can you explain why? @Fatman13

**Comment by Fatman13** [comment]
@liyunzhi-666 Thank you for reply!

Most of the SPs we work with use Venus and Venus has just integrated http retrieval capabilities. We have told SPs to adjust and work on higher http retrieval success rate.

**Comment by liyunzhi-666** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec7tfgowj5vwhfnvahadsidsdgevzn6ivu6ecltwhbzkwhwkginrq 
#### Address 
> f1wuonkzwthnrt2tlo4dafgxr4uwhctv6osefb7uq
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f1pszcrsciyixyuxxukkvtazcokexbn54amf7gvoq
#### Id
> a8981af4-eb69-4f2e-b95e-376b211f8993
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec7tfgowj5vwhfnvahadsidsdgevzn6ivu6ecltwhbzkwhwkginrq

**Comment by ipollo00** [comment]
> @liyunzhi-666 Thank you for reply!
> 
> Most of the SPs we work with use Venus and Venus has just integrated http retrieval capabilities. We have told SPs to adjust and work on higher http retrieval success rate.

Great success on http retrieval. Looking forward to their improvement in the near future. willing to support.

**Comment by ipollo00** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceasdrrsm2od6ubfjmlbobit4yzknavhzsl55kaxjkd6u4pifv6iko 
#### Address 
> f1wuonkzwthnrt2tlo4dafgxr4uwhctv6osefb7uq
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f1n5wlrrhoxpkgwij25xrtt7w7g2k3fhbthmdn6ri
#### Id
> a8981af4-eb69-4f2e-b95e-376b211f8993
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceasdrrsm2od6ubfjmlbobit4yzknavhzsl55kaxjkd6u4pifv6iko

**Comment by Fatman13** [comment]
checker:manualTrigger

**Comment by laurarenpanda** [comment]
checker:manualTrigger

**Comment by 1ane-1** [comment]
It looks healthy.

**Comment by 1ane-1** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedhhmsoxl2t7d5ub4on7a3txs6kcwexnhnrsejbd6rzwpnlplgero 
#### Address 
> f1wuonkzwthnrt2tlo4dafgxr4uwhctv6osefb7uq
#### Datacap Allocated
> 1.00PiB
#### Signer Address
> f1mdk7s2vntzm6hu35yuo6vjubtrpfnb2awhgvrri
#### Id
> edaad7a3-9b44-4848-b80c-f53461b251dc
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedhhmsoxl2t7d5ub4on7a3txs6kcwexnhnrsejbd6rzwpnlplgero

**Comment by Fatman13** [comment]
Please don not stale.

**Comment by newwebgroup** [comment]
checker:manualTrigger

**Comment by newwebgroup** [comment]
The CID Checker report results look good.

The data is evenly distributed and the replicas are well distributed.
SP locations are also scattered.
no CID sharing

However, when checking the report in depth, it is found that the retrieval of individual SPs is 0.
Communicated with Fatman13 and said that they would contact the corresponding SP for improvement.

Because it is a large public data set, and there is a good KYC before that. And also promises to make follow-up improvements,
So willing to support.

<img width="1065" alt="image" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/100118145/6129798e-ae92-4c9d-a212-edf6f950c226">

**Comment by newwebgroup** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedvxcnjsy2pi2ucjpxsl65t6snuuqrai36f6t2iho22qvlikkt5jy 
#### Address 
> f1wuonkzwthnrt2tlo4dafgxr4uwhctv6osefb7uq
#### Datacap Allocated
> 1.00PiB
#### Signer Address
> f1e77zuityhvvw6u2t6tb5qlnsegy2s67qs4lbbbq
#### Id
> edaad7a3-9b44-4848-b80c-f53461b251dc
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedvxcnjsy2pi2ucjpxsl65t6snuuqrai36f6t2iho22qvlikkt5jy

**Comment by Sunnyiscoming** [comment]
Hello, @Fatman13 per the https://github.com/filecoin-project/notary-governance/issues/922 for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

This information will be reviewed by Fil+ Governance team to confirm validity and then the application will be allowed to move forward for additional notary review.
