### ISSUE TITLE
[DataCap Application] Guazi Dynamic - Open Sustainability Data [5/6]

### ISSUE THREAD

**Issue by Fatman13** [filecoin-project/filecoin-plus-large-datasets#1926]
### Data Owner Name

Guazi Dynamic

### Data Owner Country/Region

China

### Data Owner Industry

Environment

### Website

guazi.io

### Social Media

```text
Slack: @Fatman13
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

1PiB

### On-chain address for first allocation

f1eflf6h6mgxflahdipoiihxisxwdjffuaox2ozpq

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Guazi has been with filecoin since Testnets and Space Race. We continue to bridging the gap between storage client and filecoin.
We have developed systems on top of Venus and ready to onboard large amount of data onto filecoin network.
```

### Is this project associated with other projects/ecosystem stakeholders?

Yes

### If answered yes, what are the other projects/ecosystem stakeholders

```text
CN SPWG, venushub program, SPs we have closely worked with in the past.

https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1337
```

### Describe the data being stored onto Filecoin

```text
The datasets we will be on-boarding onto Filecoin network are critical open source research datasets on sustainability, which may include but not not limited to the following...

Prediction Of Worldwide Energy Resources (POWER) Project
GOES-18 Data
Next Generation Weather Radar (NEXRAD)
Global Mangrove Watch (GMW) dataset
Digital Earth Africa (DE Africa)
Water Observations from Space (WOfS)
...

More information can be found at https://registry.opendata.aws/tag/sustainability/
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### How do you plan to prepare the dataset

others/custom tool

### If you answered "other/custom tool" in the previous question, enter the details here

```text
venus.filecoin.io
```

### Please share a sample of the data

```text
https://www.globalmangrovewatch.org/
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

1 to 1.5 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, Europe

### How will you be distributing your data to storage providers

Shipping hard drives

### How do you plan to choose storage providers

Slack, Partners, Others

### If you answered "Others" in the previous question, what is the tool or platform you plan to use

```text
Also with CN SPWG and venushub program
```

### How do you plan to make deals to your storage providers

Others/custom tool

### If you answered "Others/custom tool" in the previous question, enter the details here

```text
droplet.venus-fil.io
```

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
See questions in https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1927.

**Comment by Fatman13** [comment]
> See questions in https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1927.

kk, replied at https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1927#issuecomment-1517501536

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 5PiB

**Expected weekly DataCap usage rate**
> 1PiB

**Client address**
>f1eflf6h6mgxflahdipoiihxisxwdjffuaox2ozpq

**Comment by kernelogic** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec3kfauohfvmq4tk6iysw3pe2ci2fw4lxymnpdb7lcbw2bhzuxkmo 
#### Address 
> f1eflf6h6mgxflahdipoiihxisxwdjffuaox2ozpq
#### Datacap Allocated
> 256.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### Id
> f30d5323-6903-4db4-a7c0-a892323f6f78
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec3kfauohfvmq4tk6iysw3pe2ci2fw4lxymnpdb7lcbw2bhzuxkmo

**Comment by kernelogic** [comment]
In support for well known community contributor

**Comment by laurarenpanda** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceacmkcsxsvg6ffcgj7fz2gejoppocyyrn75fix6lgvrms2bxd72q4 
#### Address 
> f1eflf6h6mgxflahdipoiihxisxwdjffuaox2ozpq
#### Datacap Allocated
> 256.00TiB
#### Signer Address
> f1bp3tzp536edm7dodldceekzbsx7zcy7hdfg6uzq
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceacmkcsxsvg6ffcgj7fz2gejoppocyyrn75fix6lgvrms2bxd72q4

**Comment by Fatman13** [comment]
Hello, team, CC @Sunnyiscoming,

How do I reopen this?

**Comment by Fatman13** [comment]
Hello, team, CC @Kevin-FF-USA,

How do I reopen this LDN?

**Comment by Fatman13** [comment]
Hello, team, CC @simonkim0515 

Quick update, ready to prep the data again and restart dc allocation.

**Comment by Fatman13** [comment]
> This application has not seen any responses in the last 10 days. This issue will be marked with Stale label and will be closed in 4 days. Comment if you want to keep this application open.

Please keep the issue open.

**Comment by Fatman13** [comment]
checker:manualTrigger

**Comment by Bitrise0111** [comment]
checker:manualTrigger

**Comment by Bitrise0111** [comment]
check report shows healthy

**Comment by Bitrise0111** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebjbzrodmknkioudexeztzwnwo4bqqiiuyb7ixswl5emxcca375x6 
#### Address 
> f1eflf6h6mgxflahdipoiihxisxwdjffuaox2ozpq
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f1nknj7ayq4o43czrtdoauggtwl43fbqatmqis3yy
#### Id
> ab09b248-75ca-4880-9b25-8fc9f1b5069a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebjbzrodmknkioudexeztzwnwo4bqqiiuyb7ixswl5emxcca375x6

**Comment by Fatman13** [comment]
checker:manualTrigger

**Comment by Normalnoise** [comment]
checker:manualTrigger

**Comment by Fatman13** [comment]
Don't go stale please.

**Comment by Fatman13** [comment]
@github-actions can you reopen the issue?
