### ISSUE TITLE
[DataCap Application] Guazi Dynamic - Open Sustainability Data [6/6]

### ISSUE THREAD

**Issue by Fatman13** [filecoin-project/filecoin-plus-large-datasets#1927]
### Data Owner Name

Guazi Dynamic

### Data Owner Country/Region

China

### Data Owner Industry

Environment

### Website

guazi.io

### Social Media

```text
Slack: @Fatman13
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

1PiB

### On-chain address for first allocation

f14qawqrk5wr2y7zaylfiorvldkehoc7zzpkw3rzq

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Guazi has been with filecoin since Testnets and Space Race. We continue to bridging the gap between storage client and filecoin.
We have developed systems on top of Venus and ready to onboard large amount of data onto filecoin network.
```

### Is this project associated with other projects/ecosystem stakeholders?

Yes

### If answered yes, what are the other projects/ecosystem stakeholders

```text
CN SPWG, venushub program, SPs we have closely worked with in the past.

https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1337
```

### Describe the data being stored onto Filecoin

```text
The datasets we will be on-boarding onto Filecoin network are critical open source research datasets on sustainability, which may include but not not limited to the following...

Prediction Of Worldwide Energy Resources (POWER) Project
GOES-18 Data
Next Generation Weather Radar (NEXRAD)
Global Mangrove Watch (GMW) dataset
Digital Earth Africa (DE Africa)
Water Observations from Space (WOfS)
...

More information can be found at https://registry.opendata.aws/tag/sustainability/
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### How do you plan to prepare the dataset

others/custom tool

### If you answered "other/custom tool" in the previous question, enter the details here

```text
venus.filecoin.io
```

### Please share a sample of the data

```text
https://www.globalmangrovewatch.org/
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

1 to 1.5 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, Europe

### How will you be distributing your data to storage providers

Shipping hard drives

### How do you plan to choose storage providers

Slack, Partners, Others

### If you answered "Others" in the previous question, what is the tool or platform you plan to use

```text
Also with CN SPWG and venushub program
```

### How do you plan to make deals to your storage providers

Others/custom tool

### If you answered "Others/custom tool" in the previous question, enter the details here

```text
droplet.venus-fil.io
```

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
Please share more detailed information about sps you will cooperate with.

**Comment by Fatman13** [comment]
> Please share more detailed information about sps you will cooperate with.

Hello, @Sunnyiscoming, will be working with SPs from China, Europe and North America. Existing and potentially new SP partners.

Aisa:
f01228105
f01228008
f01228000
f0522948

NA:
f01228100
f01984593

Europe:
f01228087
f01228089

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 5PiB

**Expected weekly DataCap usage rate**
> 1PiB

**Client address**
>f14qawqrk5wr2y7zaylfiorvldkehoc7zzpkw3rzq

**Comment by newwebgroup** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedrolacleahphpcxiywuzgsyf3sd5nntpn47h5shoo2vgb7nuyygo 
#### Address 
> f14qawqrk5wr2y7zaylfiorvldkehoc7zzpkw3rzq
#### Datacap Allocated
> 256.00TiB
#### Signer Address
> f1e77zuityhvvw6u2t6tb5qlnsegy2s67qs4lbbbq
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedrolacleahphpcxiywuzgsyf3sd5nntpn47h5shoo2vgb7nuyygo

**Comment by SuperChaiChai** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced7mqx7gnaz7qk52zkk5fcfdkr2ahe5wqbxf77emd3wfsini7pgiw 
#### Address 
> f14qawqrk5wr2y7zaylfiorvldkehoc7zzpkw3rzq
#### Datacap Allocated
> 256.00TiB
#### Signer Address
> f12mckci3omexgzoeosjvstcfxfe4vqw7owdia3da
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced7mqx7gnaz7qk52zkk5fcfdkr2ahe5wqbxf77emd3wfsini7pgiw

**Comment by Fatman13** [comment]
Hello, team, CC @Sunnyiscoming,

How do I reopen this? There is no reopen button on my side. 

![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/1591330/2c4e2e43-25f4-4253-85e6-859b9ecdc046)

**Comment by Fatman13** [comment]
Hello, team, CC @Kevin-FF-USA,

How do I reopen this LDN?

**Comment by Fatman13** [comment]
Hello, team, CC @simonkim0515 

Quick update, ready to prep the data again and restart dc allocation.

**Comment by Fatman13** [comment]
> This application has not seen any responses in the last 10 days. This issue will be marked with Stale label and will be closed in 4 days. Comment if you want to keep this application open.

Please do not close this LDN.

**Comment by Fatman13** [comment]
checker:manualTrigger

**Comment by nj-steve** [comment]
checker:manualTrigger

**Comment by nj-steve** [comment]
all SPs support retrieval. Although the rate is not very very high, the client has contacted the SPs to increase the rate to be better.
willing  to believe this round.

**Comment by nj-steve** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecxch7ot4mzxl74snljdamiij5mjni5slfcdbh7ud3ampjw7c6g52 
#### Address 
> f14qawqrk5wr2y7zaylfiorvldkehoc7zzpkw3rzq
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f1xx6555qijma7igpnjspyvdunc4vfxkawnpqy5ii
#### Id
> 2d99fa5a-4bc9-4aeb-badd-0bd8559c7fba
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecxch7ot4mzxl74snljdamiij5mjni5slfcdbh7ud3ampjw7c6g52

**Comment by Fatman13** [comment]
checker:manualTrigger

**Comment by liyunzhi-666** [comment]
checker:manualTrigger

**Comment by liyunzhi-666** [comment]
@Fatman13  found me in slack and talked to me about their project plans. In the meantime I compared today's report to the one from two weeks ago and found that retrieval success rate is on the rise. I can support this round.

**Comment by liyunzhi-666** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec2wmengur6xrdmrqkrajuudbijbvbcakhu55u4whocfnawjy77bs 
#### Address 
> f14qawqrk5wr2y7zaylfiorvldkehoc7zzpkw3rzq
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f1pszcrsciyixyuxxukkvtazcokexbn54amf7gvoq
#### Id
> 2d99fa5a-4bc9-4aeb-badd-0bd8559c7fba
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec2wmengur6xrdmrqkrajuudbijbvbcakhu55u4whocfnawjy77bs
