### ISSUE TITLE
[DataCap Application] <Beijing Bazuo Architectural Design Firm> - <Architectural Design（1/2）>

### ISSUE THREAD

**Issue by zhogntao** [filecoin-project/filecoin-plus-large-datasets#1929]
### Data Owner Name

Beijing Bazuo Architectural Design Firm

### Data Owner Country/Region

China

### Data Owner Industry

Construction, Property & Real Estate

### Website

https://bazuoarchitecture.com/

### Social Media

```text
https://bazuoarchitecture.com/
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

1PiB

### On-chain address for first allocation

f1wp2hm4ba23habqxdacavk6yz3z4isrg6ouu5umy

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Beijing Bazuo Architectural Design Firm Co., Ltd. was established on May 29, 2013. Legal representative Wang Miao, the company's business scope includes: engineering survey and engineering design; Construction project management; Urban landscaping construction; Technical promotion services: computer graphic design; Computer animation design, etc.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
Refers to assets constructed manually, belonging to the category of fixed assets, including two categories: houses and structures. A house refers to an engineering building designed for people to live, work, study, produce, operate, entertain, store items, and engage in other social activities. The difference from buildings is structures, which refer to engineering buildings other than houses, such as walls, roads, dams, wells, tunnels, water towers, bridges, and chimneys.
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### How do you plan to prepare the dataset

singularity

### Please share a sample of the data

```text
https://cloud.189.cn/t/feeAnaq6Bvy2 （访问码：wi6m）
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Monthly

### For how long do you plan to keep this dataset stored on Filecoin

More than 3 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, Africa, North America, South America, Europe, Australia (continent), Antarctica

### How will you be distributing your data to storage providers

HTTP or FTP server, Shipping hard drives

### How do you plan to choose storage providers

Slack, Big data exchange

### How do you plan to make deals to your storage providers

Boost client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
https://aiqicha.baidu.com/detail/compinfo?pid=29577632308720&rq=es&pd=ee&from=ps
It seems that http://www.bazuo.com.cn/ is the website of this organization. Can you explain about that?
What's the relationship between you and the organization?

**Comment by zhogntao** [comment]
I am the data administrator of the company. The domain name, account, and password of the website that the company previously purchased cannot be found, so I used the second website to apply.

**Comment by Sunnyiscoming** [comment]
Could you send an email to filplus-app-review@fil.org with business license  in order to confirm your identity? Email name should includes the issue id #1929.

**Comment by zhogntao** [comment]
If a business license is required, the required application process may be delayed

**Comment by zhogntao** [comment]
![企业微信截图_16820605443468](https://user-images.githubusercontent.com/130743442/233566930-05abe631-d258-4ee7-ab2a-0078c3c85dfc.png)
@Sunnyiscoming Sent, please check

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 5PiB

**Expected weekly DataCap usage rate**
> 1PiB

**Client address**
>f1wp2hm4ba23habqxdacavk6yz3z4isrg6ouu5umy

**Comment by igoovo** [comment]
Can you disclose some SP node numbers?

**Comment by zhogntao** [comment]
f01938674    
 f02062851  
f01128206
f01877184

**Comment by igoovo** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced4apvav35ouj47obxowvx5otwgotgkcuyrcjntlhp2a4kw7lri3o 
#### Address 
> f1wp2hm4ba23habqxdacavk6yz3z4isrg6ouu5umy
#### Datacap Allocated
> 256.00TiB
#### Signer Address
> f1shnsfayxqll77svffaxnjenms7bbbysbqcatrpy
#### Id
> 897a6b6c-63e0-47ea-bba1-3d0a48c55ffc
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced4apvav35ouj47obxowvx5otwgotgkcuyrcjntlhp2a4kw7lri3o

**Comment by zhogntao** [comment]
@cryptowhizzard Hi ![image](https://user-images.githubusercontent.com/130743442/236627203-a2ad08f5-cacd-4c44-a2ac-62e4318a426e.png)
![image](https://user-images.githubusercontent.com/130743442/236627236-e5497f4f-6a01-4380-9490-cbf1cb232b1a.png)
![image](https://user-images.githubusercontent.com/130743442/236627279-77076a27-d69c-4ef2-a8cd-63a93c217a65.png)
I am a computer room operation and maintenance personnel in our company. Our company is committed to engineering design, urban design and planning, interior design, environmental art, project management, and other aspects of work.
We have our own server for generating car files and have a dedicated bandwidth of 2GB
For more information, please refer to the form.

**Comment by Normalnoise** [comment]
@zhogntao how much data have prepared?

**Comment by zhogntao** [comment]
Prepare 1.2P data

**Comment by Normalnoise** [comment]
> @cryptowhizzard Hi ![image](https://user-images.githubusercontent.com/130743442/236627203-a2ad08f5-cacd-4c44-a2ac-62e4318a426e.png)
> ![image](https://user-images.githubusercontent.com/130743442/236627236-e5497f4f-6a01-4380-9490-cbf1cb232b1a.png)
> ![image](https://user-images.githubusercontent.com/130743442/236627279-77076a27-d69c-4ef2-a8cd-63a93c217a65.png)
> I am a computer room operation and maintenance personnel in our company. Our company is committed to engineering design, urban design and planning, interior design, environmental art, project management, and other aspects of work.
> We have our own server for generating car files and have a dedicated bandwidth of 2GB
> For more information, please refer to the form.

Have seen your dataset proof, will keep eyes on your data allocation. Willing to support the first round

**Comment by Normalnoise** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebcvoz4ifbjd7bcy3keerxxyk5ai6vj3nqjv5qud4thkq5ohl3jka 
#### Address 
> f1wp2hm4ba23habqxdacavk6yz3z4isrg6ouu5umy
#### Datacap Allocated
> 256.00TiB
#### Signer Address
> f1c5non5yf35avgcpsqvxu4yj54yyvxorwyjochqq
#### Id
> 897a6b6c-63e0-47ea-bba1-3d0a48c55ffc
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebcvoz4ifbjd7bcy3keerxxyk5ai6vj3nqjv5qud4thkq5ohl3jka

**Comment by zhogntao** [comment]
checker:manualTrigger

**Comment by 1ane-1** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb4vuex5i345b7map4y6uhx5vy7r7lvqrrevjsg2efmwu6tjxca4a 
#### Address 
> f1wp2hm4ba23habqxdacavk6yz3z4isrg6ouu5umy
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f1mdk7s2vntzm6hu35yuo6vjubtrpfnb2awhgvrri
#### Id
> b71046e4-d2cb-472c-86fa-7df34ab402b9
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb4vuex5i345b7map4y6uhx5vy7r7lvqrrevjsg2efmwu6tjxca4a

**Comment by stcouldlisa** [comment]
checker:manualTrigger

**Comment by mikezli** [comment]
The CID report looks good, but the retrieval success rate doesn't look too high.

But since clients have reached out to me multiple times, I've decided to back this round for now.

In the next round, we hope to see you your retrieval success rate

**Comment by mikezli** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceckdwu44hzr2eqz4632yzkc6log7o2mokvl5cpnsfdcl3om3hnkig 
#### Address 
> f1wp2hm4ba23habqxdacavk6yz3z4isrg6ouu5umy
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f1dnb3uz7sylxk6emti3ififcvu3nlufnnsjui6ea
#### Id
> b71046e4-d2cb-472c-86fa-7df34ab402b9
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceckdwu44hzr2eqz4632yzkc6log7o2mokvl5cpnsfdcl3om3hnkig

**Comment by dahuajishu** [comment]
checker:manualTrigger

**Comment by zhogntao** [comment]
checker:manualTrigger

**Comment by zhogntao** [comment]
Sorry for replying so late. Due to a work error by the technical staff, the data was duplicated and the cause has been identified. We will correct this situation after the next allocation

**Comment by zhogntao** [comment]
checker:manualTrigger

**Comment by woshidama323** [comment]
> Sorry for replying so late. Due to a work error by the technical staff, the data was duplicated and the cause has been identified. We will correct this situation after the next allocation

please make sure you can fix this at the next round 
Will support this.

**Comment by herrehesse** [comment]
checker:manualTrigger

**Comment by herrehesse** [comment]
@DaYouGroup immediately revoke your application. @kevzak @raghavrmadya
