### ISSUE TITLE
[DataCap Application] <Beijing Bazuo Architectural Design Firm> - <Architectural Design（2/2）>

### ISSUE THREAD

**Issue by zhogntao** [filecoin-project/filecoin-plus-large-datasets#1930]
### Data Owner Name

Beijing Bazuo Architectural Design Firm

### Data Owner Country/Region

China

### Data Owner Industry

Construction, Property & Real Estate

### Website

https://bazuoarchitecture.com/

### Social Media

```text
https://bazuoarchitecture.com/
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

1PiB

### On-chain address for first allocation

f143rrb33ygtwcc5v3drbdlivceknjfn5mii37wvi

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Beijing Bazuo Architectural Design Firm Co., Ltd. was established on May 29, 2013. Legal representative Wang Miao, the company's business scope includes: engineering survey and engineering design; Construction project management; Urban landscaping construction; Technical promotion services: computer graphic design; Computer animation design, etc.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
Refers to assets constructed manually, belonging to the category of fixed assets, including two categories: houses and structures. A house refers to an engineering building designed for people to live, work, study, produce, operate, entertain, store items, and engage in other social activities. The difference from buildings is structures, which refer to engineering buildings other than houses, such as walls, roads, dams, wells, tunnels, water towers, bridges, and chimneys.
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### How do you plan to prepare the dataset

singularity

### Please share a sample of the data

```text
https://cloud.189.cn/t/feeAnaq6Bvy2 （访问码：wi6m）
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Monthly

### For how long do you plan to keep this dataset stored on Filecoin

More than 3 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, Africa, North America, South America, Europe, Australia (continent), Antarctica

### How will you be distributing your data to storage providers

HTTP or FTP server, Shipping hard drives

### How do you plan to choose storage providers

Slack, Big data exchange

### How do you plan to make deals to your storage providers

Boost client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
See questions in #1929

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 5PiB

**Expected weekly DataCap usage rate**
> 1PiB

**Client address**
>f143rrb33ygtwcc5v3drbdlivceknjfn5mii37wvi

**Comment by igoovo** [comment]
First round support, I hope the packaging process follows the rules, and I will also keep an eye on it.

**Comment by igoovo** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecdwdqy4xnvzuhsfxkrzbdbn5ddwme6mc3ejrssnsmekdtmqsib2u 
#### Address 
> f143rrb33ygtwcc5v3drbdlivceknjfn5mii37wvi
#### Datacap Allocated
> 256.00TiB
#### Signer Address
> f1shnsfayxqll77svffaxnjenms7bbbysbqcatrpy
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecdwdqy4xnvzuhsfxkrzbdbn5ddwme6mc3ejrssnsmekdtmqsib2u

**Comment by cryptowhizzard** [comment]
Hi @igoovo 

Why are you proposing 2 applications at one time from this same client for one dataset?
#1929 is open and pending review. When the application is finished we can start with #1930?

**Comment by zhogntao** [comment]
@Sunnyiscoming This has been closed. Can you help me reopen it?

**Comment by zhogntao** [comment]
@simonkim0515 This has been closed. Can you help me reopen it?

**Comment by zhogntao** [comment]
@Normalnoise Hi,I have prepared 1.2P data，The relevant screenshot proof can be found in the #1929  response. Thank you

**Comment by Normalnoise** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaq5hhk7nuh2qfmxl5ax7ypx2chus47q26bjxxvrbafgicudgcy7e 
#### Address 
> f143rrb33ygtwcc5v3drbdlivceknjfn5mii37wvi
#### Datacap Allocated
> 256.00TiB
#### Signer Address
> f1c5non5yf35avgcpsqvxu4yj54yyvxorwyjochqq
#### Id
> b54d2a21-97aa-4363-95c7-8decc6b58ccf
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaq5hhk7nuh2qfmxl5ax7ypx2chus47q26bjxxvrbafgicudgcy7e

**Comment by cbtan21** [comment]
@zhogntao i am the co founder of [BDX](https://www.bigdataexchange.io/), which aims to efficiently match data clients with SPs. Saw that you will be using Big Data Exchange to choose SPs. Have you tried publishing a storage request auction on our platform? Let me know if you need any help with sourcing for other SPs to store your replicas. We have SPs that are based in the same country as your data source and can conduct online/offline transfer for deal making. Happy to walk you through our process. Thanks.

**Comment by dahuajishu** [comment]
checker:manualTrigger

**Comment by zhogntao** [comment]
checker:manualTrigger

**Comment by kevzak** [comment]
checker:manualTrigger
