### ISSUE TITLE
[DataCap Application] <Mixobit lab> - <Blockchain analyze data>

### ISSUE THREAD

**Issue by CypherSimon** [filecoin-project/filecoin-plus-large-datasets#1931]
### Data Owner Name

Mixobit lab

### Data Owner Country/Region

Hong Kong

### Data Owner Industry

IT & Technology Services

### Website

https://mixobit.com/

### Social Media

```text
Twitter: @mixobitlabs
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

500TiB

### On-chain address for first allocation

f13dn5pkeeecb45bvrnmzhebpkwzxqhv4shywmt3a

### Data Type of Application

Public, Open Commercial/Enterprise

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Mixobit Libs focuses on deep analysis and insights into blockchain data. We provide users with easy access to market insights into the blockchain through our powerful data indexing system and visualization tools developed internally. We believe that technology empowers insights and brings a stronger intuitive experience and insights into the blockchain field.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
Blockchain & Crypto analyze data, including account analyze data, transaction data,NFT data, visually represent data, etc.
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### How do you plan to prepare the dataset

IPFS

### Please share a sample of the data

```text
https://gateway.pinata.cloud/ipfs/QmP52diUdh8M6rH3QRNcw1CeWMQ2F2iCpcgPf1ixhknhqC?_gl=1*1f5iosn*rs_ga*ZGFmMTZkYWMtYmI3YS00MjU5LThkNmUtMWVkZTJlOTMxZDAw*rs_ga_5RMPXG14TE*MTY4MTg5OTU3My4xLjEuMTY4MTg5OTgwOS4xMC4wLjA.
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Monthly

### For how long do you plan to keep this dataset stored on Filecoin

1 to 1.5 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America

### How will you be distributing your data to storage providers

HTTP or FTP server, IPFS

### How do you plan to choose storage providers

Slack, Filmine, Partners

### How do you plan to make deals to your storage providers

Boost client, Lotus client, Bidbot

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
![image](https://user-images.githubusercontent.com/105098820/233114091-7b379250-051d-4fda-b8d7-b8120fe84f5d.png)
The website is very young.
![image](https://user-images.githubusercontent.com/105098820/233114217-4a93ac57-4c30-474a-960e-823c017d6372.png)
The github handle can not be found.

Can you give more data samples to prove that you have 5 pb data already?
Please share more detailed information about sps you will cooperate with.

**Comment by CypherSimon** [comment]
Hi @Sunnyiscoming ,
Thank you very much for your response!

Yes, we established our company earlier this year. One of our biggest customers requires extensive DEX and CEX data analysis and audit services. Our current self-hosted storage infrastructure cannot sufficiently accommodate their archive data demands. At the same time, our customers desire access to all available data. Therefore, we need a robust yet cost-effective solution.

Our major customers are based in Hong Kong. We have contacted several SPs locally in addition to mainland China, Singapore, and North America. 

By the way, here is our GitHub repository:
https://github.com/orgs/Mixobit-Labs

And here is another sample:
https://gateway.pinata.cloud/ipfs/Qmb4YemYHSfd9djAsmNHC9R43KqrWwY5LakanVMXMfjcwV

**Comment by Sunnyiscoming** [comment]
It is not enough to prove that you have 5 pb data already. This file is very small.
Can you give more data samples?

**Comment by CypherSimon** [comment]
Thank you very much for the reminder, @Sunnyiscoming! Here is another sample:
http://103.75.117.54/sample.dat
 
This sample is 10+ GiB in size. We have recently removed over 1 PiB of such data for cost saving.

**Comment by Sunnyiscoming** [comment]
I can't open this data sample. I can move this application forward. Notaries will do deep investigation for your application.

**Comment by Sunnyiscoming** [comment]
Could you send an email to filplus-app-review@fil.org with your official domain in order to confirm your identity? Email name should includes the issue id #1931.

**Comment by CypherSimon** [comment]
Great! Thank you very much, Sunny!
I have sent an email and look forward to your reply.

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 5PiB

**Expected weekly DataCap usage rate**
> 500TiB

**Client address**
>f13dn5pkeeecb45bvrnmzhebpkwzxqhv4shywmt3a

**Comment by CypherSimon** [comment]
Maybe this sample is too large to download. I will upload another one. Sorry for that.

**Comment by zcfil** [comment]
> > http:
> > [//103.75.117.54/sample.dat](http://103.75.117.54/sample.dat)
> 
> @Sunnyiscoming me too。 @CypherSimon After reading history, I have some questions： Can you show more data？ Is your data publicly available？

@CypherSimon I haven't received your response yet

**Comment by CypherSimon** [comment]
Hello zcfil, 
Please try the following link: 
http://103.75.117.54/test.tar.gz

My apologies for the delayed response. I am traveling this week and have limited connectivity.

**Comment by CypherSimon** [comment]
Seems double click doesn't work. Please copy the link and open it in another tab.

**Comment by CypherSimon** [comment]
Hi @Sunnyiscoming , 
We are still awaiting approval and identifying more storage providers. Everything should be in place within this week. Do you know how to reopen this ticket or need I create a new one?

**Comment by Sunnyiscoming** [comment]
> Please try the following link:
> http://103.75.117.54/test.tar.gz

It do not work. Can you check it?

**Comment by CypherSimon** [comment]
Hi @Sunnyiscoming ,

there was some issues with our cloud services. it should be ok now. 

sorry for that.

**Comment by GaryGJG** [comment]
Hi @CypherSimon what's your sealing plan about SPs, when will you start to sealing?

**Comment by CypherSimon** [comment]
Hi @GaryGJG,

We connected with several service providers during the Hong Kong Web3 Festival last month. We are currently conducting final testing with some of these service providers, and we are also evaluating other platforms such as Filswan and Big Data Exchange. We expect to be able to start making deals this week.

Thanks,

**Comment by Alex11801** [comment]
Do you have the ownership of all those 5PiB data?

**Comment by CypherSimon** [comment]
Hi @Alex11801 ,

Yes, we own these data and there is no copyright issue for anyone to access.

**Comment by GaryGJG** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecmb2nongq6m67vs3jzmeuwmvhvf2rbbxgeqat77yrfxxwgwc5cso 
#### Address 
> f13dn5pkeeecb45bvrnmzhebpkwzxqhv4shywmt3a
#### Datacap Allocated
> 250.00TiB
#### Signer Address
> f1zffqhxwq2rrg7rtot6lmkl6hb2xyrrseawprzsq
#### Id
> f4d159d1-873a-43e5-83b8-15d408978689
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecmb2nongq6m67vs3jzmeuwmvhvf2rbbxgeqat77yrfxxwgwc5cso

**Comment by CypherSimon** [comment]
great! thank you very mach, @GaryGJG

**Comment by Alex11801** [comment]
> Hi @Alex11801 ,
> 
> Yes, we own these data and there is no copyright issue for anyone to access.

OK. Would like to support.

**Comment by Alex11801** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaa36fpwhao7b7mr6ogmcldr7g2yicsstx4ioc4zsgegckexd67aa 
#### Address 
> f13dn5pkeeecb45bvrnmzhebpkwzxqhv4shywmt3a
#### Datacap Allocated
> 250.00TiB
#### Signer Address
> f1hhippi64yiyhpjdtbidfyzma6irc2nuav7mrwmi
#### Id
> f4d159d1-873a-43e5-83b8-15d408978689
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaa36fpwhao7b7mr6ogmcldr7g2yicsstx4ioc4zsgegckexd67aa

**Comment by CypherSimon** [comment]
thank you very much, @Alex11801

**Comment by GaryGJG** [comment]
checker:manualTrigger

**Comment by GaryGJG** [comment]
The reports show your data is focus on 3 SPs in the same Datacenter, and the retrieval rate is a little bit lower,  these are not ideally , do you have any plan to improve this please ?

**Comment by CypherSimon** [comment]
Hi @GaryGJG ,

We made deals with more than 20 SPs so far. From this group, we intend to choose 4 to 5 consistently high-performing partners to serve as stable long-term collaborators. I think it would improve our dealing and retrieval efficiency.

thanks for your attention!

**Comment by GaryGJG** [comment]
Sounds good, hope you could no sooner said than done, support your second batch.

**Comment by GaryGJG** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedml2ry6i4xs7gsdntlgnamzwlgummppohgeuoproup2rzv2zjqpw 
#### Address 
> f13dn5pkeeecb45bvrnmzhebpkwzxqhv4shywmt3a
#### Datacap Allocated
> 500.00TiB
#### Signer Address
> f1zffqhxwq2rrg7rtot6lmkl6hb2xyrrseawprzsq
#### Id
> 8ca6d3b9-ac93-4cbb-9e63-b0ee44023916
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedml2ry6i4xs7gsdntlgnamzwlgummppohgeuoproup2rzv2zjqpw

**Comment by IreneYoung** [comment]
Mixobit Lab reached out to me. I have checked the sample files that's fine with me. I will support this case.

**Comment by IreneYoung** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebssgi3rwnyw2d4bgwr37eby6pk6goamm47zfhecdddgxiiydvpeu 
#### Address 
> f13dn5pkeeecb45bvrnmzhebpkwzxqhv4shywmt3a
#### Datacap Allocated
> 500.00TiB
#### Signer Address
> f1d4gmpqz3execjj2wvrxuuhvbms5mzh7t7yqrviq
#### Id
> 8ca6d3b9-ac93-4cbb-9e63-b0ee44023916
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebssgi3rwnyw2d4bgwr37eby6pk6goamm47zfhecdddgxiiydvpeu

**Comment by CypherSimon** [comment]
Please hold on.

**Comment by CypherSimon** [comment]
Please hold on.

**Comment by cryptowhizzard** [comment]
Downloaded the data and verified it. Everything looks ok.

**Comment by CypherSimon** [comment]
It is fine to close this application. We may need to adjust our strategy recently.
