### ISSUE TITLE
[DataCap Application] Digital Earth Africa Landsat Collection 2 Level 2

### ISSUE THREAD

**Issue by huang-Cora** [filecoin-project/filecoin-plus-large-datasets#1935]
### Data Owner Name

Digital Earth Africa

### Data Owner Country/Region

South Africa

### Data Owner Industry

Environment

### Website

https://www.digitalearthafrica.org/

### Social Media

```text
T https://twitter.com/DEarthAfrica
Y https://www.youtube.com/channel/UCBasD3Dz-TdQTRoyG30kVVw
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

1PiB

### On-chain address for first allocation

f1vpw4de33zpolipdzx6q7zxx44ayrniqkknntbby

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
I'm an individual dp.
Digital Earth Africa exists to improve the lives of people across the African continent by translating Earth observations into insights that will support sustainable development. 
The platform and services enable African governments, industry and decision makers to track changes across the continent in unprecedented detail. This provides valuable insights for better decision making across many areas, including flooding, drought, soil and coastal erosion, agriculture, forest cover, land use and land cover change, water availability and quality, and changes to human settlements.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
Landsat scenes, metadata and S3 Inventory files
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### How do you plan to prepare the dataset

IPFS, lotus

### Please share a sample of the data

```text
s3://deafrica-landsat/
s3://deafrica-landsat-inventory/
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Sporadic

### For how long do you plan to keep this dataset stored on Filecoin

2 to 3 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, Africa, North America, South America, Europe

### How will you be distributing your data to storage providers

HTTP or FTP server, Shipping hard drives

### How do you plan to choose storage providers

Slack, Filmine, Big data exchange

### How do you plan to make deals to your storage providers

Lotus client, Singularity, I don't know yet

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by huang-Cora** [comment]
@Sunnyiscoming I'm getting touch with sp in HongKong, who has experience in sealing, called Mailuyun. And I'll contact more sps next step.

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 5PiB

**Expected weekly DataCap usage rate**
> 1PiB

**Client address**
>f1vpw4de33zpolipdzx6q7zxx44ayrniqkknntbby

**Comment by zcfil** [comment]
dear,

Thank you for applying for datacap. As a Filecoin FIL+Notary Public, I am currently screening your application and conducting due diligence.

Looking at your application, I have some questions:

Because you are a novice on Github and do not have a history of past applications. Can you introduce who you are and your company?

You declare that you are a data preparer. What hardware do you have on your end to prepare this dataset? What is your internet connection speed? Have you downloaded the data locally?

In my opinion, there are many datacaps that apply for 5PB. People need to have a comprehensive understanding of Filecoin, data packaging, data distribution, and all the requirements that come with it. Are you a novice in the Filecoin field, or have you previously applied for datacap on different Github account names?

Can you show us some visible evidence of the size of your data and the storage/packaging hardware you have?

As a final question, I would like you to fill out [this form](https://form.jotform.com/230953098450156) in order to provide us with the necessary information to make a wise decision on your LDN request when we are willing to support it.

thank you!

**Comment by TakiChain** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacea2klv6t4ibzx6vnvcl5dh2nckcpchm45vdeioukyttmx5kyezyjw 
#### Address 
> f1vpw4de33zpolipdzx6q7zxx44ayrniqkknntbby
#### Datacap Allocated
> 256.00TiB
#### Signer Address
> f15impf3j2zcaex4lhyxndxswuuhv24vzstuqtxsi
#### Id
> c4f7a23f-369c-42d3-865f-4618d93c9219
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacea2klv6t4ibzx6vnvcl5dh2nckcpchm45vdeioukyttmx5kyezyjw

**Comment by Meibuy** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedafublthgdkacomowyvvfcthzmcz5lfztfgig75cyoqa7umpl2rw 
#### Address 
> f1vpw4de33zpolipdzx6q7zxx44ayrniqkknntbby
#### Datacap Allocated
> 256.00TiB
#### Signer Address
> f1bwugfihrmn3iyunzyxst5nttql3dge4khwmurtq
#### Id
> c4f7a23f-369c-42d3-865f-4618d93c9219
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedafublthgdkacomowyvvfcthzmcz5lfztfgig75cyoqa7umpl2rw

**Comment by Meibuy** [comment]
The dataset is valuable, the client has shared the allocation plan. We're confident to kick off this application.

**Comment by Casey-PG** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebegyy62eustoir3eoqmdda4qrzupyzvjupnewc2mcj6gzetaq54e 
#### Address 
> f1vpw4de33zpolipdzx6q7zxx44ayrniqkknntbby
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f15impf3j2zcaex4lhyxndxswuuhv24vzstuqtxsi
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebegyy62eustoir3eoqmdda4qrzupyzvjupnewc2mcj6gzetaq54e

**Comment by cryptowhizzard** [comment]
Hello,

I tried retrieving your data but it failed.

 lotus client retrieve --provider f0136399 mAXCg5AIg5yXalIekpJuIK3JGNoFoGqRkdY9aNKzCEAWujEbIzP8 /root/downloadedcarfiles/f02147046-f0136399-34931634-baga6ea4seaqjkhcx6f3b5kwcct7buf5boxr7x2mdyme3esm4rmgvzdahya4qeey.car

<img width="1268" alt="Scherm­afbeelding 2023-05-04 om 22 19 37" src="https://user-images.githubusercontent.com/36404435/236320045-55d4d050-c57c-404e-82f1-b07b50fa7ba5.png">

It stalls after this. 

Any reason why these providers do not support retrieval?

**Comment by zcfil** [comment]
> 亲爱的，
> 
> 感谢您申请 datacap。作为 Filecoin FIL+Notary Public，我目前正在筛选您的申请并进行尽职调查。
> 
> 看了你的申请，我有一些问题：
> 
> 因为你是Github新手，没有过往的应用历史。你能介绍一下你是谁和你的公司吗？
> 
> 您声明您是数据准备者。你有什么硬件来准备这个数据集？您的互联网连接速度是多少？你在本地下载数据了吗？
> 
> 在我看来，申请5PB的datacaps有很多。人们需要对Filecoin、数据打包、数据分发以及随之而来的所有要求有一个全面的了解。您是Filecoin领域的新手，还是之前在不同的Github账号上申请过datacap？
> 
> 您能否向我们展示您的数据大小和您拥有的存储/打包硬件的一些可见证据？
> 
> 作为最后一个问题，我希望您填写[此表格，](https://form.jotform.com/230953098450156)以便为我们提供必要的信息，以便在我们愿意支持时对您的 LDN 请求做出明智的决定。
> 
> 谢谢你！


So far, I haven't received your reply

**Comment by cryptowhizzard** [comment]
@zcfil 

Like i said, the SP’s do not support retrieval. This is against FIL+ rules and guidelines.

**Comment by zcfil** [comment]
@cryptowhizzard 
Yes, I agree with your opinion, but there is still a notary public reviewing it
Different standards of measurement
1. I will confirm the data ownership;
2. Confirm the integrity of data storage

**Comment by cryptowhizzard** [comment]
@zcfil 

It is not an opinion, it is a rule. Fil+ data should be readily retrievable. If it is not an application should not be signed as you can’t do due diligence and verify / check their data.

**Comment by TakiChain** [comment]
checker:manualTrigger

**Comment by Aifabot-Cloud** [comment]
The client contacted me by slack and shared more of their information . I'd like to see more public data joining the network!

**Comment by Aifabot-Cloud** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceacpkuarf63nhozxpawraw7gt6vfykhv6oxqmw23bgfv66rujzguk 
#### Address 
> f1vpw4de33zpolipdzx6q7zxx44ayrniqkknntbby
#### Datacap Allocated
> 1.00PiB
#### Signer Address
> f174fg3bqbln3zjnkxtyf6s54txqkr7yqkj6cig7y
#### Id
> 90ea082c-a39b-40a6-97a3-b231e1ef277f
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceacpkuarf63nhozxpawraw7gt6vfykhv6oxqmw23bgfv66rujzguk

**Comment by AthSmith** [comment]
No duplicate data，healthy report.

**Comment by AthSmith** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecgqzc2kczrnmlfef3ah2tx6gup37b3kffrukrhp6anf6zuepvrgy 
#### Address 
> f1vpw4de33zpolipdzx6q7zxx44ayrniqkknntbby
#### Datacap Allocated
> 1.00PiB
#### Signer Address
> f1vxbqrf7rfum3n6m5u6eb4re6xj7amvsaqnzu64y
#### Id
> 90ea082c-a39b-40a6-97a3-b231e1ef277f
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecgqzc2kczrnmlfef3ah2tx6gup37b3kffrukrhp6anf6zuepvrgy

**Comment by huang-Cora** [comment]
Yes.

**Comment by Casey-PG** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced36flcrp37h2phfytdplcbhvlf5lxfqdzbwrfbqbxztpohgc4krs 
#### Address 
> f1vpw4de33zpolipdzx6q7zxx44ayrniqkknntbby
#### Datacap Allocated
> 2.00PiB
#### Signer Address
> f1d4yb3wags3mtddzesxoo63jv7dmlec3bq4yteni
#### Id
> 6528dfed-fe09-4962-bbb2-b339bd4beda5
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced36flcrp37h2phfytdplcbhvlf5lxfqdzbwrfbqbxztpohgc4krs

**Comment by Casey-PG** [comment]
Checked the information applicant shared and so far everything is in line with Filplus program rules. Willing to give my signature in this round.

**Comment by Joss-Hua** [comment]
checker:manualTrigger

**Comment by Joss-Hua** [comment]
![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/75723122/ce9e287b-15af-463d-ada0-28940fabc460)

**Comment by Joss-Hua** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceapesocif7wgjlh5iarx2ieefevse42jvvgfns3uxyjnrvljncw4w 
#### Address 
> f1vpw4de33zpolipdzx6q7zxx44ayrniqkknntbby
#### Datacap Allocated
> 2.00PiB
#### Signer Address
> f1tfg54zzscugttejv336vivknmsnzzmyudp3t7wi
#### Id
> 6528dfed-fe09-4962-bbb2-b339bd4beda5
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceapesocif7wgjlh5iarx2ieefevse42jvvgfns3uxyjnrvljncw4w

**Comment by Joss-Hua** [comment]
Same round, re sign

**Comment by Joss-Hua** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced2jj2hlxjdpmhodoksclfyif5opd24nogsfbiwdwuyjaslza7e5u 
#### Address 
> f1vpw4de33zpolipdzx6q7zxx44ayrniqkknntbby
#### Datacap Allocated
> 2.00PiB
#### Signer Address
> f1tfg54zzscugttejv336vivknmsnzzmyudp3t7wi
#### Id
> 818e884a-952a-471c-a336-ae3f65cec248
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced2jj2hlxjdpmhodoksclfyif5opd24nogsfbiwdwuyjaslza7e5u

**Comment by huang-Cora** [comment]
Keep open.

**Comment by cryptowhizzard** [comment]
checker:manualTrigger

**Comment by cryptowhizzard** [comment]
> Keep open.

To what end? Nothing of your data is retrievable?

**Comment by cryptowhizzard** [comment]
checker:manualTrigger

**Comment by Filplus-govteam** [comment]
Hello @huang-Cora per the https://github.com/filecoin-project/notary-governance/issues/922 for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

This information will be reviewed by Fil+ Governance team to confirm validity and then the application will be triggered for notary review. Let us know if you have any questions.

**Comment by HiFil** [comment]
checker:manualTrigger

**Comment by cryptowhizzard** [comment]
Hi,

It seems that your SP's are almost tagged for Abuse / CID sharing ( AT1 ) and a few with non retrievability.

Can you clarify why you choose to work with SP's who are flagged for abuse?

![Scherm­afbeelding 2023-07-28 om 14 32 36](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/36404435/b9a4bfae-0c4e-4d94-9065-d9369023471a)

**Comment by huang-Cora** [comment]
Everything works fine between the SPs and us. If you think there is something wrong between the SPs and other applications, you should contact them instead of me.

**Comment by cryptowhizzard** [comment]
> Everything works fine between the SPs and us. If you think there is something wrong between the SPs and other applications, you should contact them instead of me.

Hello,

As data preparer it is your responsibility to make sure this data cap be retrieved on the FIL network. You confirmed that this was OK when you applied for this LDN.

![Scherm­afbeelding 2023-07-31 om 08 06 29](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/36404435/c3b9c965-9462-4e34-985f-520be80ef6fc)

Please fix.

**Comment by MatrixStorage** [comment]
As a storage user, it is indeed the obligation to supervise whether there is abuse or not.  I think there is no problem with this point raised by @cryptowhizzard , but whether we have other solutions now, I think it is another point that we consider.

**Comment by huang-Cora** [comment]
![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/125257681/6b3f8166-b43c-4332-aed6-85015e64ab4e)

Yes, we do support retrieval.

**Comment by MatrixStorage** [comment]
If you want to continue to apply for LDN, I hope you can do:
1.   Replace the SP that does not support search.
2.   Continuous monitoring of SP to prevent its abuse.

**Comment by cryptowhizzard** [comment]
> ![image](https://user-images.githubusercontent.com/125257681/257184927-6b3f8166-b43c-4332-aed6-85015e64ab4e.png)
> 
> Yes, we do support retrieval.

Http statistics are flawed at the moment. This was posted on slack a few days ago in the notary's and FIL+ channels.

**Comment by huang-Cora** [comment]
> If you want to continue to apply for LDN, I hope you can do:
> 
> 1. Replace the SP that does not support search.
> 2. Continuous monitoring of SP to prevent its abuse.

Yes, we can. Thank you for your reminder.

**Comment by Holiday507** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecjhgisjkhga4lqywl6upwocw3ozla4xgoqye2yp7wuo2rwslezgi 
#### Address 
> f1vpw4de33zpolipdzx6q7zxx44ayrniqkknntbby
#### Datacap Allocated
> 1.25PiB
#### Signer Address
> f1sa3dp3a7fwirrsxjdthvzneo7rnjcrrfllsnjpq
#### Id
> a0a6a5a4-2af5-462d-91b8-450fc79b4c15
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecjhgisjkhga4lqywl6upwocw3ozla4xgoqye2yp7wuo2rwslezgi

**Comment by cryptowhizzard** [comment]
Signed without retrieval. Dispute made.

<img width="710" alt="Scherm­afbeelding 2023-07-31 om 18 03 54" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/36404435/b3afc46d-182a-43e1-bcf8-e08f24515e63">

**Comment by BlockMakeronline** [comment]
At present, there is a problem with http retrieval. I tried to retrieve and was able to retrieve successfully. I am willing to support.

**Comment by BlockMakeronline** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecwc3d3734rvm5zj223lralpgzl62kzyziimnothzi6iyilogkl64 
#### Address 
> f1vpw4de33zpolipdzx6q7zxx44ayrniqkknntbby
#### Datacap Allocated
> 1.25PiB
#### Signer Address
> f1o3twrcpwjtpcd4q36lpq4qmy2qfbgtyy5h6tsty
#### Id
> a0a6a5a4-2af5-462d-91b8-450fc79b4c15
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecwc3d3734rvm5zj223lralpgzl62kzyziimnothzi6iyilogkl64

**Comment by huang-Cora** [comment]
@cryptowhizzard 
![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/125257681/02e111fd-8d67-4409-8832-f901a622cfed)

**This application has no dispute.** Http retrieval is successful! Why did you ignore the data in the report? 

>Http statistics are flawed at the moment. This was posted on slack a few days ago in the notary's and FIL+ channels.


Did you mean that all of http retrieval statistics are flawed now?

**DID YOU DO ANY DOWNLOAD BEFORE YOU PUT OUR APPLICATION INTO DISPUTE FORM?**

**Comment by huang-Cora** [comment]
Yes please.

**Comment by clriesco** [comment]
Removed stale label, reopened issue :)
