### ISSUE TITLE
[DataCap Application] <FanjingAR> - <FanjingAR Data>

### ISSUE THREAD

**Issue by fanjingar** [filecoin-project/filecoin-plus-large-datasets#1937]
### Data Owner Name

Shanghai Fanjing AR Technology LTD

### Data Owner Country/Region

China

### Data Owner Industry

IT & Technology Services

### Website

http://www.fanjing-ar.com/

### Social Media

```text
http://www.fanjing-ar.com/
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

1PiB

### On-chain address for first allocation

f1eg5tywt374hgwu2hafkxabjm3nhe236spg2dcbi 

### Data Type of Application

None

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Fanjing Technology LTD focuses on the combination of technology and scenes, combining advanced technologies such as face recognition, graphic and image recognition, and voice gesture interaction with customers' actual applications, exploring vertical scenes vertically, expanding industry applications horizontally, and accumulating With advanced experience and scenario application, modularization is gradually realized, appropriate modules are selected according to customer needs, and corresponding software and hardware comprehensive solutions are quickly customized and developed for customers.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
AR training data
Graphic image recognition training data
Corporate promotion video
design source file
```

### Where was the data currently stored in this dataset sourced from

Other

### If you answered "Other" in the previous question, enter the details here

```text
We purchased Alibaba Cloud Storage, where the data is stored
```

### How do you plan to prepare the dataset

IPFS, lotus, singularity, graphsplit

### Please share a sample of the data

```text
https://drive.google.com/drive/folders/1Mpw9D8aMAgQPnF-PX4ZoHZPKj7DaZaWr?usp=sharing
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

1.5 to 2 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, Africa, North America, South America, Europe, Australia (continent), Antarctica

### How will you be distributing your data to storage providers

Cloud storage (i.e. S3), HTTP or FTP server, IPFS, Shipping hard drives, Lotus built-in data transfer, I don't know yet

### How do you plan to choose storage providers

Slack, Partners

### How do you plan to make deals to your storage providers

Boost client, Lotus client, Bidbot, Singularity

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
Could you send an email to filplus-app-review@fil.org with your official domain in order to confirm your identity? Email name should includes the issue id #1937.

**Comment by fanjingar** [comment]
![image](https://user-images.githubusercontent.com/130625217/233817293-0b0f2494-03dd-4507-95a3-2c89527f8972.png)
We have sent the email, thanks for your support.

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 5PiB

**Expected weekly DataCap usage rate**
> 500TiB

**Client address**
>f1eg5tywt374hgwu2hafkxabjm3nhe236spg2dcbi

**Comment by zcfil** [comment]
Found only a small amount of data. Can you provide more data samples?
![image](https://user-images.githubusercontent.com/45065975/233928175-f3bcba69-aa8d-4118-acde-e35ba65f4457.png)

**Comment by fanjingar** [comment]
> Found only a small amount of data. Can you provide more data samples? ![image](https://user-images.githubusercontent.com/45065975/233928175-f3bcba69-aa8d-4118-acde-e35ba65f4457.png)

We have upload some other samples, pls check, thanks.

**Comment by zcfil** [comment]
Make sure there are no problems with the organization, this round of audit passed, later will continue to pay attention to
<img width="1220" alt="image" src="https://user-images.githubusercontent.com/45065975/236681166-cb9f63bf-9a08-4816-8393-0fdc7276dc4b.png">
<img width="1035" alt="image" src="https://user-images.githubusercontent.com/45065975/236681245-2398a352-d3e0-4a5c-8a82-4de1e30dbc1b.png">

**Comment by zcfil** [comment]
@Sunnyiscoming Console error：`Verification failed: Invalid secp256k1 address length.`

**Comment by fanjingar** [comment]
> Make sure there are no problems with the organization, this round of audit passed, later will continue to pay attention to <img alt="image" width="1220" src="https://user-images.githubusercontent.com/45065975/236681166-cb9f63bf-9a08-4816-8393-0fdc7276dc4b.png"> <img alt="image" width="1035" src="https://user-images.githubusercontent.com/45065975/236681245-2398a352-d3e0-4a5c-8a82-4de1e30dbc1b.png">

Thank you very much.

**Comment by fanjingar** [comment]
> Make sure there are no problems with the organization, this round of audit passed, later will continue to pay attention to <img alt="image" width="1220" src="https://user-images.githubusercontent.com/45065975/236681166-cb9f63bf-9a08-4816-8393-0fdc7276dc4b.png"> <img alt="image" width="1035" src="https://user-images.githubusercontent.com/45065975/236681245-2398a352-d3e0-4a5c-8a82-4de1e30dbc1b.png">

Could you help we to sign for this LDN?

**Comment by zcfil** [comment]
<img width="1356" alt="image" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/45065975/25afa409-14e5-44f7-b781-3fb8fc9f45b1">
@Kevin-FF-USA

**Comment by fanjingar** [comment]
We tried a lot, but there was no notary to sign for us. This application needs to be reopened @Kevin-FF-USA

**Comment by fanjingar** [comment]
@Sunnyiscoming

**Comment by Kevin-FF-USA** [comment]
Hi @fanjingar.,

No need to reapply, recommend you post a short description of this issue and what you need in the Slack channel; Fil-application review [https://filecoinproject.slack.com/archives/C036JKD8NVA](url)

From there, the Notaries can see your application and continue the diligence review.

**Comment by fanjingar** [comment]
> Hi @fanjingar.,
> 
> No need to reapply, recommend you post a short description of this issue and what you need in the Slack channel; Fil-application review [https://filecoinproject.slack.com/archives/C036JKD8NVA](url)
> 
> From there, the Notaries can see your application and continue the diligence review.

Thank you so much !

**Comment by herrehesse** [comment]
The initial request for 5 PiB using a newly created account and without establishing trust within the community is concerning. I highly recommend close the application and reconsider by starting with a smaller amount to build credibility and trust before making larger requests.

Advising notaries not to engage.

**Comment by fanjingar** [comment]
> The initial request for 5 PiB using a newly created account and without establishing trust within the community is concerning. I highly recommend close the application and reconsider by starting with a smaller amount to build credibility and trust before making larger requests.
> 
> Advising notaries not to engage.

Is there any relationship between the creation time of the account and the size of the quota? Your rules are not consensus by the community. If you are unwilling to support them, you can go away and don't incite other notaries.

**Comment by max1015070108** [comment]
Github is not the mainstream technical communication community in some regions, like in China, where more technicians use CSDN, cnblogs, and gitee. Therefore, most people do not have Github accounts. Does this mean that individuals/organizations in these regions cannot apply for LDNs? This is regional discrimination.

**Comment by herrehesse** [comment]
@max1015070108 You are now playing the racism card? That is pretty sad.

**Comment by herrehesse** [comment]
@fanjingar I am committed to staying vigilant and challenging notaries who sign LDNs without conducting thorough due diligence. As mentioned earlier, the prevalence of fraud is currently at an alarming level. Without a solid foundation of community trust and established reputation, I strongly advise against engaging in signing activities on this application.

Labeling this as racism or discrimination will not alter the underlying facts.

**Comment by defiking0108** [comment]
As per the existing FIL+ guidelines, there's no reference to such requirements. Please highlight where it has been stated. It appears that you have imposed this rule beyond the scope of FIL+ and made judgments based on your personal biases. This could potentially border on racial discrimination, which warrants serious reflection.

**Comment by herrehesse** [comment]
"regional discrimination" you say, can you provide evidence against the fact that over 90%+ of the abuse cases originate out of Asia? I would love to see that evidence.

**Comment by defiking0108** [comment]
Wow, "90%+" 
What led you to draw such a conclusion? Do you possess any concrete evidence? Making such claims without ample proof, doesn't this border on regional discrimination?

**Comment by woshidama323** [comment]
> The initial request for 5 PiB using a newly created account and without establishing trust within the community is concerning. I highly recommend close the application and reconsider by starting with a smaller amount to build credibility and trust before making larger requests.
> 
> Advising notaries not to engage.
This has not reached a consensus. You should not interfere with the decisions of other notaries for such a reason.

**Comment by fanjingar** [comment]
I found other SP sign for this  and the same problem occurred. If the problem cannot be solved today, I will consider changing my wallet address and reapplying for a new LDN. @Kevin-FF-USA @Sunnyiscoming

**Comment by zcfil** [comment]
@herrehesse @fanjingar @defiking0108 Filecoin PULS is a very serious platform. Please do not engage in verbal warfare, as it may affect the development of our community

**Comment by zcfil** [comment]
![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/45065975/2ce31638-5ed2-4214-8b3e-c693d4b509b0)
Sorry, I am still unable to review

**Comment by zcfil** [comment]
I have provided feedback to the team, please wait for a response

**Comment by Filplus-govteam** [comment]
Hello @fanjingar  per the [new guidelines](https://github.com/filecoin-project/notary-governance/issues/922) for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data. 

This information will be reviewed by Fil+ Governance team to confirm validity and then the application will be triggered for notary review. Let us know if you have any questions.

**Comment by fanjingar** [comment]
> Hello @fanjingar per the [new guidelines](https://github.com/filecoin-project/notary-governance/issues/922) for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.
> 
> This information will be reviewed by Fil+ Governance team to confirm validity and then the application will be triggered for notary review. Let us know if you have any questions.

ok, i will fill out this form later

**Comment by fanjingar** [comment]
https://github.com/keyko-io/filecoin-verifier-frontend/issues/805
This bug haven't be fixed yet and 20 days past, anyone response for this ?
