### ISSUE TITLE
[DataCap Application] CESM2 ARISE

### ISSUE THREAD

**Issue by Janicelu1** [filecoin-project/filecoin-plus-large-datasets#1938]
### Data Owner Name

NCAR

### Data Owner Country/Region

United States

### Data Owner Industry

Environment

### Website

https://ncar.ucar.edu/

### Social Media

```text
Facebook: https://www.facebook.com/NCAR.UCAR/
Youtube: https://www.youtube.com/ncarucar
https://github.com/NCAR/CESM2-ARISE
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

1PiB

### On-chain address for first allocation

f1ar7iqp6lpljivz7tgufyik2uvsxpb33tfjcttii

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
NCAR is a center of research excellence in Earth system science sponsored by the National Science Foundation. It was designed by a small group of innovative scientists, most of them university faculty members, as a creative response to major challenges that faced the nation in the years between the 1930s and 1950s. I'm joining in slingshot and I want to get datacap for data sealing and cost saving.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
Project data files from ARISE-SAI Experiments with CESM2.
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### How do you plan to prepare the dataset

IPFS, lotus, singularity

### Please share a sample of the data

```text
s3://ncar-cesm2-arise/
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

More than 3 years

### In which geographies do you plan on making storage deals

Asia other than Greater China, North America, Europe

### How will you be distributing your data to storage providers

Cloud storage (i.e. S3), HTTP or FTP server, Shipping hard drives, Lotus built-in data transfer

### How do you plan to choose storage providers

Slack, Filmine, Big data exchange

### If you already have a list of storage providers to work with, fill out their names and provider IDs below

I'm looking for suitable sps.

### How do you plan to make deals to your storage providers

Lotus client, Singularity

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 5PiB

**Expected weekly DataCap usage rate**
> 1PiB

**Client address**
>f1ar7iqp6lpljivz7tgufyik2uvsxpb33tfjcttii

**Comment by zcfil** [comment]
dear,

Thank you for applying for datacap. As a Filecoin FIL+Notary Public, I am currently screening your application and conducting due diligence.

Looking at your application, I have some questions:

Because you are a novice on Github and do not have a history of past applications. Can you introduce who you are and your company?

You declare that you are a data preparer. What hardware do you have on your end to prepare this dataset? What is your internet connection speed? Have you downloaded the data locally?

In my opinion, there are many datacaps that apply for 5PB. People need to have a comprehensive understanding of Filecoin, data packaging, data distribution, and all the requirements that come with it. Are you a novice in the Filecoin field, or have you previously applied for datacap on different Github account names?

Can you show us some visible evidence of the size of your data and the storage/packaging hardware you have?

As a final question, I would like you to fill out [this form](https://form.jotform.com/230953098450156) in order to provide us with the necessary information to make a wise decision on your LDN request when we are willing to support it.

thank you!

**Comment by TakiChain** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedvke36wt7cwhilc7qiu6lr7hx7llweq53atgchgnjkru676f7z2w 
#### Address 
> f1ar7iqp6lpljivz7tgufyik2uvsxpb33tfjcttii
#### Datacap Allocated
> 256.00TiB
#### Signer Address
> f15impf3j2zcaex4lhyxndxswuuhv24vzstuqtxsi
#### Id
> 829783d5-9743-4abf-bfe6-e4c3508ed759
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedvke36wt7cwhilc7qiu6lr7hx7llweq53atgchgnjkru676f7z2w

**Comment by TakiChain** [comment]
This is an open data application and the client has provided an appropriate allocation plan. The resources available for review in the first round are very limited. For now i would like to go ahead and help this application move forward.

**Comment by BobbyChoii** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceclq7lxpasr7laifuyek62az4yoozgzq43xklpysjhv67224bsbj6 
#### Address 
> f1ar7iqp6lpljivz7tgufyik2uvsxpb33tfjcttii
#### Datacap Allocated
> 256.00TiB
#### Signer Address
> f1irqs2gmctiv3jcdfwuch7oxvf4ixh3k4b2wc24i
#### Id
> 829783d5-9743-4abf-bfe6-e4c3508ed759
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceclq7lxpasr7laifuyek62az4yoozgzq43xklpysjhv67224bsbj6

**Comment by cryptowhizzard** [comment]
Good morning,

It seems none of your SP's are supporting retrieval at this moment.

lotus client retrieve --provider f0136399 mAXCg5AIgVDUPkVKRrZ8q1DCriCl84TwAUBG9SeKJN+evDyoAih0 test.car
Recv 0 B, Paid 0 FIL, Open (New), 0s [1682861878842666113|0]
Recv 0 B, Paid 0 FIL, DealProposed (WaitForAcceptance), 5ms [1682861878842666113|0]
Recv 0 B, Paid 0 FIL, DealAccepted (Accepted), 340ms [1682861878842666113|0]
Recv 0 B, Paid 0 FIL, PaymentChannelSkip (Ongoing), 340ms [1682861878842666113|0]
  
cat  f02147020-f02019788-34808691-baga6ea4seaqf62f3bjorwchcmkwrpcngsm5hypk47dzanhw53p3sqgu6poldopa.log
Error: retrieval query for miner f02019788 failed: failed to dial 12D3KooWDpez5oEcqoWLJArH4zxkpUSpYhvdDx2YADzWWTb8wJ8J:
  * [/ip4/49.213.6.50/tcp/10242] dial tcp4 49.213.6.50:10242: connect: connection refused

Any reason for this?

**Comment by Janicelu1** [comment]
Hello @cryptowhizzard ![1230](https://user-images.githubusercontent.com/125250171/236157410-afabb6ea-15d0-4e6d-8d43-57717ae3570c.png)
The test of retrieval is without any problems. It may differ from country to country due to network. Welcome more notaries who can review and sign for my applliction!

**Comment by Janicelu1** [comment]
@cryptowhizzard  There may be some misunderstanding here. What I meant by my earlier words was---the difference in retrieval results may be related to the network in different countries. We do support retrieval in any country. But sp's network is also a factor in the results. We've already communicated with sp to ask them to fix their network.

**Comment by Casey-PG** [comment]
checker:manualTrigger

**Comment by cryptowhizzard** [comment]
Hi @Janicelu1 

That is good to hear. Let us know when the retrieval is fixed in order to continue with this LDN

**Comment by Casey-PG** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb3dnyap6qkpca7s4ulhg34phylkvh676gr53yumf23ggv7czfoeq 
#### Address 
> f1ar7iqp6lpljivz7tgufyik2uvsxpb33tfjcttii
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f1d4yb3wags3mtddzesxoo63jv7dmlec3bq4yteni
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb3dnyap6qkpca7s4ulhg34phylkvh676gr53yumf23ggv7czfoeq

**Comment by Meibuy** [comment]
The client followed the allocation plan as planned, good report is all dimensions. Keep it up!

**Comment by Meibuy** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebqkzwtdpnsibht356ut7nui3ab2yz3mzqrymzs6a7irtg2ulzsze 
#### Address 
> f1ar7iqp6lpljivz7tgufyik2uvsxpb33tfjcttii
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f1bwugfihrmn3iyunzyxst5nttql3dge4khwmurtq
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebqkzwtdpnsibht356ut7nui3ab2yz3mzqrymzs6a7irtg2ulzsze

**Comment by Janicelu1** [comment]
> Good morning,
> 
> It seems none of your SP's are supporting retrieval at this moment.
> 
> lotus client retrieve --provider f0136399 mAXCg5AIgVDUPkVKRrZ8q1DCriCl84TwAUBG9SeKJN+evDyoAih0 test.car Recv 0 B, Paid 0 FIL, Open (New), 0s [1682861878842666113|0] Recv 0 B, Paid 0 FIL, DealProposed (WaitForAcceptance), 5ms [1682861878842666113|0] Recv 0 B, Paid 0 FIL, DealAccepted (Accepted), 340ms [1682861878842666113|0] Recv 0 B, Paid 0 FIL, PaymentChannelSkip (Ongoing), 340ms [1682861878842666113|0]
> 
> cat f02147020-f02019788-34808691-baga6ea4seaqf62f3bjorwchcmkwrpcngsm5hypk47dzanhw53p3sqgu6poldopa.log Error: retrieval query for miner f02019788 failed: failed to dial 12D3KooWDpez5oEcqoWLJArH4zxkpUSpYhvdDx2YADzWWTb8wJ8J:
> 
> * [/ip4/49.213.6.50/tcp/10242] dial tcp4 49.213.6.50:10242: connect: connection refused
> 
> Any reason for this?

![image](https://user-images.githubusercontent.com/125250171/237007545-d7ef3010-d5c1-40aa-a6a2-834a517c09cc.png)
Dear notaries, SP has fixed the network problem. Retrieval works fine now.

**Comment by TakiChain** [comment]
In our opinion, data retrievals don't require and cannot be done by all notaries, because these are limited and affected by the quality of network links and regional policies in each region, which is the main reason why the community needs to select so many notaries in each region. But for the DPs, the selected storage nodes need to be "subjectively" public to any regions for retrieval. We need to be aware of the subtle differences in the nature of these two things, especially for notaries.

We suggest that notaries who are currently unable to or can only partially successfully complete retrievals temporarily should not be anxious and can refer to the CID reports before you make the decision of signing. Don't forget that you do have the right to choose not to sign. The key indicators that are constantly updated are reflected in the CID reports by P.L., which are the main reference materials we use for our signing.

**Comment by Meibuy** [comment]
> In our opinion, data retrievals don't require and cannot be done by all notaries, because these are limited and affected by the quality of network links and regional policies in each region, which is the main reason why the community needs to select so many notaries in each region. But for the DPs, the selected storage nodes need to be "subjectively" public to any regions for retrieval. We need to be aware of the subtle differences in the nature of these two things, especially for notaries.
> 
> We suggest that notaries who are currently unable to or can only partially successfully complete retrievals temporarily should not be anxious and can refer to the CID reports before you make the decision of signing. Don't forget that you do have the right to choose not to sign. The key indicators that are constantly updated are reflected in the CID reports by P.L., which are the main reference materials we use for our signing.

That's the right attitude, notaries need to communicate better with each other to make the community more friendly and supportive. Many misunderstandings are caused by differences in understanding of the rules.

**Comment by zcfil** [comment]
checker:manualTrigger

**Comment by Aifabot-Cloud** [comment]
The client contacted me by slack and shared their storage plan. I'd like to see more public data joining the network!

**Comment by BobbyChoii** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedrppnudwmk73ivfs4amdf2mdvm65xmq7ro6ruptbprfghy3ijwvw 
#### Address 
> f1ar7iqp6lpljivz7tgufyik2uvsxpb33tfjcttii
#### Datacap Allocated
> 1.00PiB
#### Signer Address
> f1irqs2gmctiv3jcdfwuch7oxvf4ixh3k4b2wc24i
#### Id
> 80b3843e-172f-4d84-8050-52d3a04d3c6b
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedrppnudwmk73ivfs4amdf2mdvm65xmq7ro6ruptbprfghy3ijwvw

**Comment by AthSmith** [comment]
No duplicate data，healthy report. Please keep the allocation more decentralized in the future.

**Comment by AthSmith** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaszpupt7772a3pl55ny5actodd2l5kpppimowq6ziw6toevzory2 
#### Address 
> f1ar7iqp6lpljivz7tgufyik2uvsxpb33tfjcttii
#### Datacap Allocated
> 1.00PiB
#### Signer Address
> f1vxbqrf7rfum3n6m5u6eb4re6xj7amvsaqnzu64y
#### Id
> 80b3843e-172f-4d84-8050-52d3a04d3c6b
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaszpupt7772a3pl55ny5actodd2l5kpppimowq6ziw6toevzory2

**Comment by TakiChain** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecp56dmmcjznfmr5txm2aipuwqseya7fwhljxwhf6vntjnma2fscg 
#### Address 
> f1ar7iqp6lpljivz7tgufyik2uvsxpb33tfjcttii
#### Datacap Allocated
> 2.00PiB
#### Signer Address
> f15impf3j2zcaex4lhyxndxswuuhv24vzstuqtxsi
#### Id
> 6fb66271-defd-4d23-86ab-b76d4c9efbf4
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecp56dmmcjznfmr5txm2aipuwqseya7fwhljxwhf6vntjnma2fscg

**Comment by Suyanj** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced2fbxfojepjtvn6gxnd2qquipmy3325mozfjwlgr5ujom3rgfhly 
#### Address 
> f1ar7iqp6lpljivz7tgufyik2uvsxpb33tfjcttii
#### Datacap Allocated
> 2.00PiB
#### Signer Address
> f1ihv7gz3vn3xqvikpt4rwryecgisl7745lodx3yi
#### Id
> 6fb66271-defd-4d23-86ab-b76d4c9efbf4
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced2fbxfojepjtvn6gxnd2qquipmy3325mozfjwlgr5ujom3rgfhly

**Comment by Suyanj** [comment]
The client followed the allocation plan as planned, good report is all dimensions. Keep it up!

**Comment by cryptowhizzard** [comment]
> > Good morning,
> > It seems none of your SP's are supporting retrieval at this moment.
> > lotus client retrieve --provider f0136399 mAXCg5AIgVDUPkVKRrZ8q1DCriCl84TwAUBG9SeKJN+evDyoAih0 test.car Recv 0 B, Paid 0 FIL, Open (New), 0s [1682861878842666113|0] Recv 0 B, Paid 0 FIL, DealProposed (WaitForAcceptance), 5ms [1682861878842666113|0] Recv 0 B, Paid 0 FIL, DealAccepted (Accepted), 340ms [1682861878842666113|0] Recv 0 B, Paid 0 FIL, PaymentChannelSkip (Ongoing), 340ms [1682861878842666113|0]
> > cat f02147020-f02019788-34808691-baga6ea4seaqf62f3bjorwchcmkwrpcngsm5hypk47dzanhw53p3sqgu6poldopa.log Error: retrieval query for miner f02019788 failed: failed to dial 12D3KooWDpez5oEcqoWLJArH4zxkpUSpYhvdDx2YADzWWTb8wJ8J:
> > 
> > * [/ip4/49.213.6.50/tcp/10242] dial tcp4 49.213.6.50:10242: connect: connection refused
> > 
> > Any reason for this?
> 
> ![image](https://user-images.githubusercontent.com/125250171/237007545-d7ef3010-d5c1-40aa-a6a2-834a517c09cc.png) Dear notaries, SP has fixed the network problem. Retrieval works fine now.

I don't understand.  I tested myself and i checked through dag.parts , nothing works?

<img width="778" alt="Scherm­afbeelding 2023-05-27 om 20 37 07" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/36404435/02509765-893a-4ca3-a883-d02a30130ae3">

Can you make baga6ea4seaqajmsp6lw7mjkd6dtpxboq6cklspagxxj7ie5qj476zuajjsjqeby available for download so we can check the data you are storing here?

Btw , nothing of your data is indexed on the network. 

lassie fetch -o baga6ea4seaqajmsp6lw7mjkd6dtpxboq6cklspagxxj7ie5qj476zuajjsjqeby.car baga6ea4seaqajmsp6lw7mjkd6dtpxboq6cklspagxxj7ie5qj476zuajjsjqeby
Fetching baga6ea4seaqajmsp6lw7mjkd6dtpxboq6cklspagxxj7ie5qj476zuajjsjqeby
2023-05-27T20:39:14.431+0200    FATAL   lassie  lassie/main.go:57       no candidates

**Comment by Janicelu1** [comment]
@cryptowhizzard  We've already fix previous problem. You can try it again.

**Comment by cryptowhizzard** [comment]
checker:manualTrigger

**Comment by cryptowhizzard** [comment]
Hi @Janicelu1 

The checkbot states -> All retrieval success ratios are below 1%.

Sorry.

**Comment by raghavrmadya** [comment]
Under T&T Review. Pause all signing immediately

**Comment by Janicelu1** [comment]
Most of the SPs in Graphsync retrieval are timeout, I think this may be the reason why the retrieval rate is showing zero. @raghavrmadya what is the current standard for retrieval timeout? I will contact SPs to find out more about this issue.

**Comment by Janicelu1** [comment]
> > Good morning,
> > It seems none of your SP's are supporting retrieval at this moment.
> > lotus client retrieve --provider f0136399 mAXCg5AIgVDUPkVKRrZ8q1DCriCl84TwAUBG9SeKJN+evDyoAih0 test.car Recv 0 B, Paid 0 FIL, Open (New), 0s [1682861878842666113|0] Recv 0 B, Paid 0 FIL, DealProposed (WaitForAcceptance), 5ms [1682861878842666113|0] Recv 0 B, Paid 0 FIL, DealAccepted (Accepted), 340ms [1682861878842666113|0] Recv 0 B, Paid 0 FIL, PaymentChannelSkip (Ongoing), 340ms [1682861878842666113|0]
> > cat f02147020-f02019788-34808691-baga6ea4seaqf62f3bjorwchcmkwrpcngsm5hypk47dzanhw53p3sqgu6poldopa.log Error: retrieval query for miner f02019788 failed: failed to dial 12D3KooWDpez5oEcqoWLJArH4zxkpUSpYhvdDx2YADzWWTb8wJ8J:
> > 
> > * [/ip4/49.213.6.50/tcp/10242] dial tcp4 49.213.6.50:10242: connect: connection refused
> > 
> > Any reason for this?
> 
> ![image](https://user-images.githubusercontent.com/125250171/237007545-d7ef3010-d5c1-40aa-a6a2-834a517c09cc.png) Dear notaries, SP has fixed the network problem. Retrieval works fine now.


SP tried again and verified it is retrievable. 
Timeout is due to geographic location and network quality. They're actively modifying. https://github.com/data-preservation-programs/RetrievalBot/blob/main/filplus.md#deployment

**Comment by cryptowhizzard** [comment]
checker:manualTrigger

**Comment by kevzak** [comment]
Hi @Janicelu1 - can you please answer questions about your role in this application above? [LINK](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1938#issuecomment-1518947769)

specifically:  are you the data preparer? if so, how did you prepare the data?

And how did you find SPs? Who are the SP businesses involved?

**Comment by kevzak** [comment]
Also we have a new, optional KYC ID check available on [filplus.storage](https://filplus.storage/). If you want to add additional layer of trust you can complete an ID check and verify this GitHub account. See details: [LINK](https://medium.com/filecoin-plus/implementation-of-a-third-party-kyc-id-check-for-fil-applicants-e5e825b1484e)

**Comment by Janicelu1** [comment]
@kevzak Hi Kevin, I'm a data preparer. I mainly turned data into car files via lotus now. I used to contact with sps on slack, because I need to ensure their capacities for sealing. The SPs we cooperate with now are BlockPi, LEMint, etc.

**Comment by lyjmry** [comment]
checker:manualTrigger

**Comment by Janicelu1** [comment]
yes please!

**Comment by cryptowhizzard** [comment]
Hi,

Another thing,

I see this client is working with SP's previously tagged for CID sharing. Can you explain @Janicelu1 

( All SP's with AT1 ). The ones with AT3 have retrieval disabled.

![Scherm­afbeelding 2023-07-28 om 13 54 06](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/36404435/134f52fb-e8c9-4898-81f7-a94cb7add6d0)

**Comment by Janicelu1** [comment]
As a DP, we can't stop them from cooperating with other DPs or Clients. The controversy over this proposal has been resolved, and your new question is beyond the scope of what I need respond to.  @dkkapur @simonkim0515 @raghavrmadya

**Comment by Janicelu1** [comment]
checker:manualTrigger

**Comment by Carohere** [comment]
checker:manualTrigger

**Comment by Carohere** [comment]
https://filecoinproject.slack.com/archives/C01DLAPKDGX/p1690606951304359

**Comment by Carohere** [comment]
Retrieval Statistics could be accepted.

**Comment by Carohere** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedtc52kyltgwc3f65tgfcdyotdabnjb75ufsmz3cqg43knd525smy 
#### Address 
> f1ar7iqp6lpljivz7tgufyik2uvsxpb33tfjcttii
#### Datacap Allocated
> 1.25PiB
#### Signer Address
> f1pynuve3pi2fwvhlkco6dl3ipspkgzmb25syv5ca
#### Id
> 0688fe64-6a23-4354-a10d-f0e665a632de
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedtc52kyltgwc3f65tgfcdyotdabnjb75ufsmz3cqg43knd525smy

**Comment by cryptowhizzard** [comment]
@filplus-govteam

This one got signed where no retrieval is possible. Secondly the SP’s used do not adhere Fil+ guidelines

**Comment by Suyanj** [comment]
The overall situation and the updated report are good, with most nodes retrievable and successfully downloaded. 

As @Carohere  mentioned on slack, why SPs have a history of flaws should not be a question that the current DP has to answer.

<img width="1408" alt="7973b91815b39e39e66226a3acc57f0" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/107249346/2b793698-fa98-4e6e-a16e-8685cf48bb26">

![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/107249346/1af187d1-f691-4303-b164-e1dffc4d335a)

**Comment by Suyanj** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebmterwegqx647232pg6zidfne6ntq2r4fxtylzvtrvm5kge3zbzq 
#### Address 
> f1ar7iqp6lpljivz7tgufyik2uvsxpb33tfjcttii
#### Datacap Allocated
> 1.25PiB
#### Signer Address
> f1ihv7gz3vn3xqvikpt4rwryecgisl7745lodx3yi
#### Id
> 0688fe64-6a23-4354-a10d-f0e665a632de
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebmterwegqx647232pg6zidfne6ntq2r4fxtylzvtrvm5kge3zbzq

**Comment by cryptowhizzard** [comment]
> The overall situation and the updated report are good, with most nodes retrievable and successfully downloaded.
> 
> As @Carohere mentioned on slack, why SPs have a history of flaws should not be a question that the current DP has to answer.
> 
> <img alt="7973b91815b39e39e66226a3acc57f0" width="1408" src="https://user-images.githubusercontent.com/107249346/257124497-2b793698-fa98-4e6e-a16e-8685cf48bb26.png">
> ![image](https://user-images.githubusercontent.com/107249346/257125561-1af187d1-f691-4303-b164-e1dffc4d335a.png)

Notary's are well aware that the HTTP retrieval statistics are unreliable at the moment. This message was posted on slack before weekend.

**Comment by Suyanj** [comment]
@cryptowhizzard There must be some SPs who won't be your DC-buyers, I suggest you choose silence over defamation!

you shoud read it:
https://github.com/filecoin-project/community/blob/master/CODE_OF_CONDUCT.md

![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/107249346/69226959-959d-4de6-b859-01a8e58a5c65)

**Comment by cryptowhizzard** [comment]
> @cryptowhizzard There must be some SPs who won't be your DC-buyers, I suggest you choose silence over defamation!
> 
> you shoud read it: https://github.com/filecoin-project/community/blob/master/CODE_OF_CONDUCT.md
> 
> ![image](https://user-images.githubusercontent.com/107249346/257128006-69226959-959d-4de6-b859-01a8e58a5c65.png)

Save your energy and adhere to the COC please. I have already tagged this application for abuse.

**Comment by cryptowhizzard** [comment]
![Scherm­afbeelding 2023-07-31 om 08 25 07](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/36404435/db0846f7-872e-4cd0-98d2-5721098cc083)

**Comment by Janicelu1** [comment]
checker:manualTrigger

**Comment by clriesco** [comment]
Removed stale label and reopened issue :)
