### ISSUE TITLE
[DataCap Application] <Shanghai Teng Yuan Logistics Co> - <video data>

### ISSUE THREAD

**Issue by yaoyuanww** [filecoin-project/filecoin-plus-large-datasets#1939]
### Data Owner Name

Shanghai Teng Yuan Logistics Co

### Data Owner Country/Region

China

### Data Owner Industry

Transport Services

### Website

https://www.gkeml.com/

### Social Media

```text
no social media account
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

50TiB

### On-chain address for first allocation

f1sjic2s4q7jfz6clu4st3shazyvbihffqjq7qjvi

### Data Type of Application

Private Commercial/Enterprise

### Custom multisig

- [x] Use Custom Multisig

### Identifier

efil

### Share a brief history of your project and organization

```text
Shanghai Tengyuan Logistics Co., Ltd., established in 2015 with a registered capital of RMB 2 million, is located in Pudong New Area, Shanghai. We are a professional logistics company that integrates car transportation and cargo transportation. Our predecessor was "Siyuan Logistics". After 20 years of development and operation, we have formed a complete logistics distribution network. Our company owns more than 30 large, medium, and small professional transport vehicles, forming a professional transport team with abundant assets, advanced transportation equipment, and excellent vehicle conditions. At the same time, we have a large warehouse base with an area of approximately 20,000 square meters, including 11,000 square meters of indoor space and 9,000 square meters of outdoor space. With strong strength, fast transportation, efficient focus, and safe logistics services, Shanghai Tengyuan Logistics Co., Ltd. has been highly praised and recommended by customers.

Relying on the resource advantages of our partner GKE (Singapore) Metal Logistics Company, in addition to our own warehousing, logistics, and customer resources, we also share resources with our partner in designated LME warehouses in Singapore, bonded warehouses in Shanghai Waigaoqiao Free Trade Zone and Tianjin Free Trade Zone, etc.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
We are planning to store massive amounts of historical video surveillance data from multiple warehouses on the Filecoin network. Firstly, this will prepare us for the financial institution to call up goods monitoring videos at any time. Secondly, these video surveillance data will also provide a dataset for AI machine learning.

Filecoin is a decentralized storage network based on blockchain technology, which can provide reliable data storage and access services. Storing historical video data on the Filecoin network can provide high data security and reliability. In addition, by using the Filecoin network, we can fully utilize its distributed storage features and store data in multiple locations, thereby reducing the risk of data loss.
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### How do you plan to prepare the dataset

singularity

### Please share a sample of the data

```text
https://drive.google.com/file/d/1tl8ps66RHPa9xR4TwSVR2vXQqwLqikKo/view?usp=sharing
https://drive.google.com/file/d/1w06cTgkVKWoQFqhcvgpDFCrpWvMJ-svk/view?usp=sharing
https://drive.google.com/file/d/1VghsZ1mHWAQktSKsJVRgZy3wxOySnEDG/view?usp=sharing
https://drive.google.com/file/d/1tl8ps66RHPa9xR4TwSVR2vXQqwLqikKo/view?usp=sharing
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [ ] I confirm

### If you chose not to confirm, what was the reason

```text
This is a E-FIL project. Data store is enterprise-user data.
```

### What is the expected retrieval frequency for this data

Monthly

### For how long do you plan to keep this dataset stored on Filecoin

1.5 to 2 years

### In which geographies do you plan on making storage deals

North America

### How will you be distributing your data to storage providers

Cloud storage (i.e. S3)

### How do you plan to choose storage providers

Slack

### How do you plan to make deals to your storage providers

Boost client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Carohere** [comment]
Hi @yaoyuanww, the data owner is Shanghai Tengyuan Logistics Co., but the website is GKE Metal Logistics LTD. What is the relation between these two firms?

**Comment by kevzak** [comment]
Hello - I can confirm that @yaoyuanww has completed the KYC and KYB check.

Additionally they have completed the full upfront check registration form. For notaries interested in reviewing this application, send a comment to me, I will share the proof of data set size, data sample, and SP distribution plan.

**Comment by kevzak** [comment]
## Datacap Request Trigger
#### Total DataCap requested 
> 5PiB
#### Expected weekly DataCap usage rate 
> 50TiB
#### Client address
> f1sjic2s4q7jfz6clu4st3shazyvbihffqjq7qjvi

**Comment by kevzak** [comment]
## Datacap Request Trigger
#### Total DataCap requested 
> 5PiB
#### Expected weekly DataCap usage rate 
> 50TiB
#### Client address
> f1sjic2s4q7jfz6clu4st3shazyvbihffqjq7qjvi

**Comment by Carohere** [comment]
> Hi @yaoyuanww, the data owner is Shanghai Tengyuan Logistics Co., but the website is GKE Metal Logistics LTD. What is the relation between these two firms?

@kevzak may I know which company passed the KYB check?

**Comment by kevzak** [comment]
> > Hi @yaoyuanww, the data owner is Shanghai Tengyuan Logistics Co., but the website is GKE Metal Logistics LTD. What is the relation between these two firms?
> 
> @kevzak may I know which company passed the KYB check?

@Carohere Shanghai Tengyuan Logistics Co., Ltd. passed KYB. I'll forward to you

**Comment by zcfil** [comment]
Hi @yaoyuanww yao Official enterprise record inquiry (Shanghai Tengyuan Logistics Co., LTD.) domain name is: 
www.shtylog.com is inconsistent with the domain name provided. What is the reason for this?

<img width="1252" alt="image" src="https://user-images.githubusercontent.com/45065975/236678154-d742b89b-a944-4ee3-9003-7e7ac3bbb615.png">

**Comment by Fatman13** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecgrcuwhkvavukt5jewniqwv7vpxhtemntistjvf625hdc6jmnxhq 
#### Address 
> f1sjic2s4q7jfz6clu4st3shazyvbihffqjq7qjvi
#### Datacap Allocated
> 25.00TiB
#### Signer Address
> f1j3u7crhjzwb2cj5mq7vodlt4o66yoyci7lhcauy
#### Id
> 3b7d6065-70e7-487f-a02a-0921dbd9f81c
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecgrcuwhkvavukt5jewniqwv7vpxhtemntistjvf625hdc6jmnxhq

**Comment by Fatman13** [comment]
Client reached out to me on Slack and shared their data set size, data sample, and SP distribution plan. Everything looks okay for now.

**Comment by Carohere** [comment]
There has been no engagement from the client for the past three weeks - not sure why he never responded to any questions while was able to contact notaries for signatures.😅 If [the auto-close modification](https://github.com/filecoin-project/notary-governance/issues/818) applies to EFIL+, this application should be closed immediately. If not, I highly recommend notaries **NOT** sign off on it until the client provides a clear explanation. cc @kevzak

**Comment by yaoyuanww** [comment]
@Carohere @kevzak I was gone for a while, sorry for the later response. Let me try to explain as much as possible. the company( Shanghai Tengyuan Logistics Co.) has completed KYB throught 3rd party tool that kevin helped  implemented. Shanghai Tengyuan Logistics Co., LTD is the data owner, it is a subsidiary of GKE Metal Logistics LTD in china.  Tengyuan is a in traditional industry and does not have its own website. the website you saw at registration www.shtylog.com is just for registration and only for email purpose. the website was never up running. as part of KYB to verify the relaitonship between these two companies, a email was sent from  GKE Metal Logistics LTD to @kevzak .

**Comment by kevzak** [comment]
I can confirm that someone with an @ty.gkeml.cn emailed to confirm work on Shanghai teng project.

**Comment by liyunzhi-666** [comment]
> Hello - I can confirm that @yaoyuanww has completed the KYC and KYB check.
> 
> Additionally they have completed the full upfront check registration form. For notaries interested in reviewing this application, send a comment to me, I will share the proof of data set size, data sample, and SP distribution plan.

KZ,I want to support the first round, please send me the relevant proof and I will DM you at slack.

**Comment by liyunzhi-666** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecoijsa5byk7klh2fmkg63ijvbn5cz426fb3lzjnfds3auqmvoxja 
#### Address 
> f1sjic2s4q7jfz6clu4st3shazyvbihffqjq7qjvi
#### Datacap Allocated
> 25.00TiB
#### Signer Address
> f1pszcrsciyixyuxxukkvtazcokexbn54amf7gvoq
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecoijsa5byk7klh2fmkg63ijvbn5cz426fb3lzjnfds3auqmvoxja

**Comment by kevzak** [comment]
checker:manualTrigger

**Comment by yaoyuanww** [comment]
we will start sealing very soon

**Comment by kevzak** [comment]
Hello @yaoyuanww - there is now one additional step as part of E-Fil+ application process: To validate your applicant GitHub ID, we ask you to complete the KYC check (a third party ID verification process).

Steps: 
- Go to Filplus.storage
- Login with your GitHub information 
- You'll see a link to "get verified". Click and complete the steps to verify your identification (avoid using Firefox browser).
- Once complete, your application will show a "kyc verified" label for all to see.

Also note: 
- The KYC check process is completed by, [Togggle](http://togggle.io/). 
- During the user data collection process, all gathered information is securely encrypted using the individual user's personal key. This ensures that the data remains confidential and inaccessible, even to Togggle
- Applicant personal information will never show on GitHub applications, only the kyc verified label.
- At any time, applicants can request to have verification information removed from the system, let the Governance team know 

Let me know if you have any issues or questions.

**Comment by Aaron01230** [comment]
checker:manualTrigger

**Comment by Aaron01230** [comment]
The customer contacted me to sign, and I checked the report, but the report shows that only 13T of data is sealed in total, and all storage providers are located in the same region. Are you going to cooperate with SPs in other regions? @yaoyuanww

**Comment by Joss-Hua** [comment]
There's still a lot of dc balance left, I need that the client completes more orders and update the report before making a judgment.

**Comment by yaoyuanww** [comment]
will resume storage very soon.

**Comment by laurarenpanda** [comment]
The Client has reached out to me via Slack.
Could you please share more information about your future allocation plan, @yaoyuanww?
Only 2 SPs stored data for this application.

**Comment by laurarenpanda** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebeuvryxusx67ruyozdnfz2ftorvcisdavhbxznv7d3znp4xv4xva 
#### Address 
> f1sjic2s4q7jfz6clu4st3shazyvbihffqjq7qjvi
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1bp3tzp536edm7dodldceekzbsx7zcy7hdfg6uzq
#### Id
> ef88d230-6f3d-4201-8a39-1c97796642bb
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebeuvryxusx67ruyozdnfz2ftorvcisdavhbxznv7d3znp4xv4xva
