### ISSUE TITLE
[DataCap Application] Shenzhen YouTrans Intelligent Logistics Co., Ltd

### ISSUE THREAD

**Issue by shuyapeng** [filecoin-project/filecoin-plus-large-datasets#194]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information

- Organization Name: Shenzhen YouTrans Intelligent Logistics Co., Ltd
- Website / Social Media: www.youtrans.net
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 1 PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 200 TiB
- On-chain address for first allocation: f3w62a7cocq6qlszyxmrl75qnbumfxgougaf7q57pjmdipfccomogsxxas3qaunmefrqzs7aja4tycy6mxsaxa

Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer.

## Project details

Share a brief history of your project and organization.

```
Shenzhen YouTrans Intelligent Logistics Co., Ltd. owns a professional logistics system development team. We plan to save logistics documents, customer data and videos in IPFs and upload them to the cloud storage platform for use.

In addition, the new digital-driven technology, combined with the application of Internet of things, artificial intelligence and blockchain technology, YouTrans greatly simplifies the international logistics process, quickly responds to diversified customer needs, and realizes the whole online process operation, multi-party real-time collaborative work, transparent and visual during whole process and automatic data transmission through the independently developed international logistics system, which help customers to easily manage the supply chain.
```

What is the primary source of funding for this project?

```
Bank loans, credit, utilization of foreign capital,and other funds, etc.
```

What other projects/ecosystem stakeholders is this project associated with?

```
Shenzhen YouTrans Intelligent Logistics Co., Ltd. is establishing a logistics information platform with various countries. We are discusseing cooperation with logistics projects with other countries. At the same time, migrate data to IPFS storage through APP. It can facilitate the storage, browsing and downloading of logistics data in various countries, and ensure the security of data at the same time.
```

## Use-case details

Describe the data being stored onto Filecoin

```
We plan to use the data required in the process of Filecoin network storage service and then return the stored CID to the customer through the APP. The customer can retrieve it from the Chrome browser and firfox Firefox browser on the computer or smartphone. They can also obtain, check and download it to confirm the integrity of the data.
```

Where was the data in this dataset sourced from?

```
Data uploaded mainly by users (personal images, videos and files, text content and business data, etc.) 
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 

```

```

Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).

```
We will open all the data stored. Of course, because the service we operate can achieve its purpose only by fully opening the data, so that customers can obtain their own logistics information and progress anytime and anywhere.
```

What is the expected retrieval frequency for this data?

```
Maybe often? It's really hard to say, that depends on the user.
```

For how long do you plan to keep this dataset stored on Filecoin?

```
It is expected to be 540 days, which may be extended later.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?

```
Asia, EU and North America.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?

```
Distribute data to 5 different miner storage nodes offline.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.

```
After online transaction and confirmation, 32GB files can be saved if there are no network problems. Or high-quality nodes conduct offline transactions and confirmation to save 32GB files.
```

How will you be distributing deals across storage providers?

```
Depending on the bandwidth of the network and the efficiency of storage. We plan to distribute evenly.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?

```
Yes, all transactions will be verified by DataCap.
```

**Comment by shuyapeng** [comment]
@galen-mcandrew

**Comment by galen-mcandrew** [comment]
Missing a section here:

> Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this.

**Comment by IPFSUnion** [comment]
For a logistics company,1PiB is a huge storage space. Additional materials need to provide.

**Comment by IPFSUnion** [comment]
For a logistics company,1PiB is a huge storage space. Additional materials need to provide.

**Comment by dkkapur** [comment]
Closing this one out for inactivity. @shuyapeng please re-open if relevant and share your responses to the above comments. Thank you.
