### ISSUE TITLE
[DataCap Application] Fly Brain Anatomy: FlyLight Gen1 and Split-GAL4 Imagery AND NOAA Coastal Lidar Data AND 

### ISSUE THREAD

**Issue by haocai2868** [filecoin-project/filecoin-plus-large-datasets#1940]
### Data Owner Name

DNAstack terms of use，Creative Commons Attribution 4.0 International，CC BY-4.0

### Data Owner Country/Region

United States

### Data Owner Industry

Life Science / Healthcare

### Website

https://github.com/DNAstack/dnastack-open-data，https://open.quiltdata.com/b/janelia-flylight-imagery，https://pan.ukbb.broadinstitute.org

### Social Media

```text
https://twitter.com/quiltdata
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

1PiB

### On-chain address for first allocation

f1fd23n3eiqgtixgtvhctnq2ko2aagqrizujwxzcy

### Data Type of Application

Slingshot

### Custom multisig

- [ ] Use Custom Multisig

### Identifier

No response

### Share a brief history of your project and organization

```text
I am a community member who loves filecoin. As a DP, I actively participate in slingshot, support the development of filecoin with my own actions, believe in the future of filecoin, and actively promote filecoin in the community.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
The [Sequence Read Archive (SRA)](https://www.ncbi.nlm.nih.gov/sra/) is the primary archive of high-throughput sequencing data, hosted by the National Institutes of Health (NIH). The SRA represents the largest publicly available repository of SARS-CoV-2 sequencing data. This dataset was created by DNAstack using SARS-CoV-2 sequencing data sourced from the SRA. Where possible, raw sequence data were processed by DNAstack through a unified bioinformatics pipeline to produce genome assemblies and variant calls. The use of a standardized workflow to produce this harmonized dataset allows public data generated using different methodologies to be combined and compared for a more powerful global analysis of available SARS-CoV-2 data, allowing researchers rapid access to aggregated downstream results for accelerated insight generation. Methodology: Reads from the SRA were extracted in FASTQ format, then entered into a different pipeline depending on the sequencing technology used to create the reads: the [ARTIC protocol](https://artic.network/ncov-2019/ncov2019-bioinformatics-sop.html) for Oxford Nanopore-derived reads; the [SIGNAL pipeline](https://github.com/jaleezyy/covid-19-signal) for paired-end Illumina reads; and the [CoSA pipeline](https://github.com/PacificBiosciences/CoSA) (using [DeepVariant](https://github.com/google/deepvariant) for variant calling) for PacBio reads. Briefly, reads were primer-trimmed and aligned to the SARS-CoV-2 reference genome, following which contiguous regions were assembled and variant sites were called. [Pangolin](https://github.com/cov-lineages/pangolin) was then used to assign viral lineage based on the assembled genome.

The overall objective of the FlyLight Project is to produce large anatomical data sets, highly characterized collections of GAL4 drivers, and genetic and computational tools that function synergistically to enable studies of the Drosophila nervous system. We believe the reagents and research tools we are developing are critical to the progress of the field and that Janelia can play a key role in developing them. We work closely with many labs and project teams at Janelia, and are actively engaged with both internal and external scientists who bring expert anatomical knowledge of specific regions of the Drosophila nervous system to generate a comprehensive library of Split-GAL4 driver lines covering the majority of the larval and adult CNS.

A multi-ancestry analysis of 7,221 phenotypes using a generalized mixed model association testing framework, spanning 16,119 genome-wide association studies. We provide standard meta-analysis across all populations and with a leave-one-population-out approach for each trait. The data are provided in tsv format (per phenotype) and Hail MatrixTable (all phenotypes and variants). Metadata is provided in phenotype and variant manifests.
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### How do you plan to prepare the dataset

IPFS, lotus, singularity, graphsplit

### Please share a sample of the data

```text
https://open.quiltdata.com/b/janelia-flylight-imagery/tree/
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

1.5 to 2 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, Africa, North America, South America, Europe, Australia (continent), Antarctica

### How will you be distributing your data to storage providers

Cloud storage (i.e. S3), HTTP or FTP server, IPFS, Shipping hard drives

### How do you plan to choose storage providers

Slack, Filmine, Big data exchange, Partners

### How do you plan to make deals to your storage providers

Boost client, Lotus client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by haocai2868** [comment]
@dkkapur

**Comment by haocai2868** [comment]
> Please share more detailed information about sps you will cooperate with.

I am a DP participant of slingshot v3, and I am looking for a cooperative sp. slingshot v3 has not started for a long time, and the car file has been divided and placed on my disk for almost a year.

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 5PiB

**Expected weekly DataCap usage rate**
> 1PiB

**Client address**
>f1fd23n3eiqgtixgtvhctnq2ko2aagqrizujwxzcy

**Comment by cryptowhizzard** [comment]
Hello,

Why don't the SP's in this application allow retrieval?
f02019788 has a retrieval score of 0% for example. 

FIL+ rules are that the data should be readily retrievable. Please fix this.

**Comment by cryptowhizzard** [comment]
Hello,

None of the SP's you are storing with allow retrieval of data. This is against FIL+ rules.
Please fix this as soon as possible.

<img width="769" alt="Scherm­afbeelding 2023-05-05 om 19 22 44" src="https://user-images.githubusercontent.com/36404435/236525046-f9eff0f0-0b2f-4a20-a090-771ef9effaae.png">

<img width="1101" alt="Scherm­afbeelding 2023-05-05 om 19 23 42" src="https://user-images.githubusercontent.com/36404435/236525138-ea8efcd9-351f-4b83-aa44-e41d2a2b4b91.png">

**Comment by haocai2868** [comment]
> 你好，
> 
> 您存储的所有 SP 都不允许检索数据。这违反了 FIL+ 规则。 请尽快解决此问题。
> 
> <img alt="Schermafbeelding 2023-05-05 om 19 22 44" width="769" src="https://user-images.githubusercontent.com/36404435/236525046-f9eff0f0-0b2f-4a20-a090-771ef9effaae.png">
> 
> <img alt="Schermafbeelding 2023-05-05 om 19 23 42" width="1101" src="https://user-images.githubusercontent.com/36404435/236525138-ea8efcd9-351f-4b83-aa44-e41d2a2b4b91.png">

My application has not been approved yet, how to store it, did you reply to the wrong person?

> Hello,
> 
> None of the SP's you are storing with allow retrieval of data. This is against FIL+ rules. Please fix this as soon as possible.
> 
> <img alt="Scherm­afbeelding 2023-05-05 om 19 22 44" width="769" src="https://user-images.githubusercontent.com/36404435/236525046-f9eff0f0-0b2f-4a20-a090-771ef9effaae.png">
> 
> <img alt="Scherm­afbeelding 2023-05-05 om 19 23 42" width="1101" src="https://user-images.githubusercontent.com/36404435/236525138-ea8efcd9-351f-4b83-aa44-e41d2a2b4b91.png">

My application has not been approved yet, how to store it, did you reply to the wrong person?

**Comment by haocai2868** [comment]
My application has not been approved yet, how to store it, did you reply to the wrong person?

**Comment by cryptowhizzard** [comment]
@haocai2868 

Sorry, you are 100% right. I removed my reply, it was meant for someone else.
Apologies.

**Comment by haocai2868** [comment]
Why has it been two weeks, and no notarys have responded to me, giving me approval, what else do I need to do?

**Comment by haocai2868** [comment]
@dkkapur Hi guys remember me, slack slingshot channel contacted，This process is too slow, almost a month, can you sign for me

**Comment by haocai2868** [comment]
The application sent by notarys is basically approved within a day, but no one has responded to us who have no channels. This mechanism is too rubbish. The interests of notarys are colluding with each other. I think this mechanism should be deleted and replaced.

**Comment by haocai2868** [comment]
such as holding a fil vote
