### ISSUE TITLE
[DataCap Application] Digital Earth Africa Sentinel-1 Radiometrically Terrain Corrected

### ISSUE THREAD

**Issue by Lenwoodyao** [filecoin-project/filecoin-plus-large-datasets#1941]
### Data Owner Name

Digital Earth Africa

### Data Owner Country/Region

South Africa

### Data Owner Industry

Environment

### Website

https://www.digitalearthafrica.org/

### Social Media

```text
https://twitter.com/DEarthAfrica
https://www.youtube.com/channel/UCBasD3Dz-TdQTRoyG30kVVw
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

800TiB

### On-chain address for first allocation

f1g444qlc4obteamjhoc2mozwmh36kn3wdhwzremi

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
I used to attend slingshot, so I've downloaded this dataset and want to store it.
The Digital Earth Africa team is a network of experts. The Africa based team is situated at the Program Management Office in Pretoria. There are also staff and partners across the continent to ensure support for Digital Earth Africa services is Africa-wide.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
Sentinel-1 tiles and metadata
DE Africa’s Sentinel-1 backscatter product is developed to be compliant with the CEOS Analysis Ready Data for Land (CARD4L) specifications. The Sentinel-1 mission, composed of a constellation of two C-band Synthetic Aperture Radar (SAR) satellites, are operated by European Space Agency (ESA) as part of the Copernicus Programme. The mission currently collects data every 12 days over Africa at a spatial resolution of approximately 20 m. Radar backscatter measures the amount of microwave radiation reflected back to the sensor from the ground surface.
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### How do you plan to prepare the dataset

lotus, singularity

### Please share a sample of the data

```text
https://registry.opendata.aws/deafrica-sentinel-1/
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

1.5 to 2 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, Europe

### How will you be distributing your data to storage providers

HTTP or FTP server, Shipping hard drives

### How do you plan to choose storage providers

Slack, Big data exchange, Partners

### If you already have a list of storage providers to work with, fill out their names and provider IDs below

```text
Need time to confirm.
```

### How do you plan to make deals to your storage providers

Lotus client, Singularity

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 5PiB

**Expected weekly DataCap usage rate**
> 800TiB

**Client address**
>f1g444qlc4obteamjhoc2mozwmh36kn3wdhwzremi

**Comment by zcfil** [comment]
You can use your official domain name to filplus-app-review@fil.org Send email and copy to reymond.bu@gmail.com To confirm your identity? The email name should include question ID [# 1941.](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1941)

**Comment by Lenwoodyao** [comment]
@zcfil I'm a dp so I don't have offcial domain.

**Comment by Lenwoodyao** [comment]
ok

**Comment by Lenwoodyao** [comment]
ok, keep this open

**Comment by Carohere** [comment]
Have received DM from this applicant and verified data samples, allocation plan. We would like to offer support for the first round.

**Comment by Carohere** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebabkbbu2tb2hoe5e6c3gfmyctnpejlmbfgsmn7bhiigeglhdtd2s 
#### Address 
> f1g444qlc4obteamjhoc2mozwmh36kn3wdhwzremi
#### Datacap Allocated
> 256.00TiB
#### Signer Address
> f1pynuve3pi2fwvhlkco6dl3ipspkgzmb25syv5ca
#### Id
> 93d2308f-8235-402d-82ce-caeb8954145a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebabkbbu2tb2hoe5e6c3gfmyctnpejlmbfgsmn7bhiigeglhdtd2s

**Comment by Carohere** [comment]
The client reached out to me on slack. I have verified the data samples and the distribution plan. Willing to support the first round and will monitor bot reports for consistency with the claim plan.

**Comment by steven004** [comment]
checker:manualTrigger

**Comment by steven004** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebjhoqhljsabfckpehjp2tzvcpfnfkfjxmmlyzeek7qndpy4xpgja 
#### Address 
> f1g444qlc4obteamjhoc2mozwmh36kn3wdhwzremi
#### Datacap Allocated
> 256.00TiB
#### Signer Address
> f1ozt3gaqbnzfic6f2zsj4vppncws36ik5nqofhka
#### Id
> 93d2308f-8235-402d-82ce-caeb8954145a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebjhoqhljsabfckpehjp2tzvcpfnfkfjxmmlyzeek7qndpy4xpgja

**Comment by steven004** [comment]
256TiB is not that big, but enjoy ...

**Comment by Lenwoodyao** [comment]
Yes, keep open.

**Comment by clriesco** [comment]
Removed stale label and reopened issue :)

**Comment by Lenwoodyao** [comment]
Thanks sir @clriesco

**Comment by Lenwoodyao** [comment]
Yes, keep open.

**Comment by spaceT9** [comment]
checker:manualTrigger

**Comment by Lenwoodyao** [comment]
Yes, keep open.

**Comment by Lenwoodyao** [comment]
yes

**Comment by Lenwoodyao** [comment]
yes

**Comment by Lenwoodyao** [comment]
Yes

**Comment by Sunnyiscoming** [comment]
Hello, @Lenwoodyao per the https://github.com/filecoin-project/notary-governance/issues/922 for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

This information will be reviewed by Fil+ Governance team to confirm validity and then the application will be allowed to move forward for additional notary review.

**Comment by Wengeding** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedb3syvc6jywqfktkaxtujqejhshwnj4w2qankwqfh5znnea2wvjg 
#### Address 
> f1g444qlc4obteamjhoc2mozwmh36kn3wdhwzremi
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f1txfsjmix4vlzido4dkildrnbw26owtlbslexmpa
#### Id
> 3db4f79c-c78a-4e7c-a6e9-018ddae2ec1f
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedb3syvc6jywqfktkaxtujqejhshwnj4w2qankwqfh5znnea2wvjg

**Comment by TakiChain** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedixd5mufmd7mc7cydpnr7x4ltc43i7ly6ferwx2mgnmhk2d6dwdg 
#### Address 
> f1g444qlc4obteamjhoc2mozwmh36kn3wdhwzremi
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f15impf3j2zcaex4lhyxndxswuuhv24vzstuqtxsi
#### Id
> 3db4f79c-c78a-4e7c-a6e9-018ddae2ec1f
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedixd5mufmd7mc7cydpnr7x4ltc43i7ly6ferwx2mgnmhk2d6dwdg

**Comment by Lenwoodyao** [comment]
@Sunnyiscoming OK. Done.

**Comment by herrehesse** [comment]
Bad notaries have signed this LDN. Awaiting first CID report.
