### ISSUE TITLE
[DataCap Application] Prelinger Archives LLC

### ISSUE THREAD

**Issue by prelingerarchives** [filecoin-project/filecoin-plus-large-datasets#1942]
### Data Owner Name
Prelinger Archives LLC

### Data Owner Country/Region
United States

### Data Owner Industry
Information, Media & Telecommunications

### Website
[prelingerarchives.online](prelingerarchives.online)

### Social Media
@prelingerarchives (Twitter)

### Total amount of DataCap being requested
4.5 PiB

### Weekly allocation of DataCap requested
25 TiB

### On-chain address for first allocation
f1r47sx2wu7b7ovw5bk7ptfhiskeriogincoipfyy

### Data Type of Application
Public, Open Dataset (Research/Non-Profit)

### Custom multisig
Use Custom Multisig

### Share a brief history of your project and organization
Operates open access film archives.

### Is this project associated with other projects/ecosystem stakeholders?
Yes

### If answered yes, what are the other projects/ecosystem stakeholders
Internet Archive, FFDW

### Describe the data being stored onto Filecoin
Archival video scanned from historical film.

### Where was the data currently stored in this dataset sourced from
My own storage infra

### How do you plan to prepare the dataset
others/custom tool

### If you answered "other/custom tool" in the previous question, enter the details here
Per arrangement with FFDW.

### Please share a sample of the data
Too large

### Confirm that this is a public dataset that can be retrieved by anyone on the Network
Yes

### What is the expected retrieval frequency for this data
Daily

### For how long do you plan to keep this dataset stored on Filecoin
Permanently

### In which geographies do you plan on making storage deals
North America

### How will you be distributing your data to storage providers
I don't know yet

### How do you plan to choose SP
I don't know yet

### How do you plan to make deals to your storage providers
I don't know yet

### Can you confirm that you will follow the Fil+ guideline
Yes

_Application created via [filplus.storage](https://filplus.storage)_

**Comment by Sunnyiscoming** [comment]
![image](https://user-images.githubusercontent.com/105098820/234577139-bc65102e-bf65-42de-abd9-696976db0b15.png)
The website and social media do not exist.
Please share some small data samples to prove you have data storage requirement.
You can join the community slack and find suitable sps. https://filecoinproject.slack.com/ssb/redirect

**Comment by Sunnyiscoming** [comment]
Any update here?

**Comment by Sunnyiscoming** [comment]
Can you introduce your organizaion?

**Comment by Sunnyiscoming** [comment]
Such as name, socail media, etc.

**Comment by prelingerarchives** [comment]
Hi @Sunnyiscoming, We're [Prelinger Archives](https://en.wikipedia.org/wiki/Prelinger_Archives) we are currently collaborating with Internet Archive and [Filecoin Foundation for the Decentralized Web](https://medium.com/@FFDWeb/ffdw-works-with-prelinger-archives-to-make-rare-historic-films-more-accessible-using-the-558e4dbec990) to make thousands of historical films accessible through the DWeb.

**Comment by Sunnyiscoming** [comment]
Could you send an email to filplus-app-review@fil.org with your official domain in order to confirm your identity? Email name should includes the issue id #1942.

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 4.5PiB

**Expected weekly DataCap usage rate**
> 25TiB

**Client address**
>f1r47sx2wu7b7ovw5bk7ptfhiskeriogincoipfyy

**Comment by dannyob** [comment]
Hey folks, delighted to be able to support this application. Have fun on the Filecoin network!

**Comment by dannyob** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced4okarxxf2lbr7scltxa3vz4b2v4kzq4k6w7ljkkg4fg43xo3emc 
#### Address 
> f1r47sx2wu7b7ovw5bk7ptfhiskeriogincoipfyy
#### Datacap Allocated
> 12.50TiB
#### Signer Address
> f1k6wwevxvp466ybil7y2scqlhtnrz5atjkkyvm4a
#### Id
> 2e93dde8-97f2-416b-9c81-27e67526f2f2
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced4okarxxf2lbr7scltxa3vz4b2v4kzq4k6w7ljkkg4fg43xo3emc

**Comment by kernelogic** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebswd336kwlox57iae7pjvir2ty7ti65o5bcqg7haqd7fbkz3wnem 
#### Address 
> f1r47sx2wu7b7ovw5bk7ptfhiskeriogincoipfyy
#### Datacap Allocated
> 12.50TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebswd336kwlox57iae7pjvir2ty7ti65o5bcqg7haqd7fbkz3wnem
