### ISSUE TITLE
[DataCap Application] Triton One Ltd - Solana Transaction and Block History

### ISSUE THREAD

**Issue by linuskendall** [filecoin-project/filecoin-plus-large-datasets#1943]
### Data Owner Name

Triton One Limited

### Data Owner Country/Region

Isle of Man

### Data Owner Industry

Web3 / Crypto

### Website

https://triton.one

### Social Media

```text
https://twitter.com/triton_one
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

150TiB

### On-chain address for first allocation

f1ps34emfyq2tbioxwzr7tm2nqwprkiehsccvn7gy

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Triton One was one of the first infrastructure providers working on Solana. We began by operating the public RPC nodes that were made available freely to the Solana ecosystem in 2021. Since then we have been an active stakeholder in many Solana projects including ensuring the replication and development of historical archives for Solana. This project seeks to make available a fully queryable historical archive of Solana data on Filecoin.
```

### Is this project associated with other projects/ecosystem stakeholders?

Yes

### If answered yes, what are the other projects/ecosystem stakeholders

```text
This effort is done in collaboration with the Solana Foundation,the Firedancer team at Jump Crypto and the Protocol Labs Outercore Network Growth team. We have also initiated partnerships with other stakeholders in the Solana ecosystem, such as other infrastructure providers who have pledged support and interest in maintaining and using this dataset.

In parallel to this project, there is an effort to upload historical ledger files that have been snapshotted from Solana (https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/923). The historical ledger archives that this other effort seeks to upload are a snapshot in time of the database generated by a Solana validator. The project described in this proposal seeks to upload historical archives in a format that allows data to be accessed semantically and directly by producing a content based DAG based on the logical elements of Solana’s blockchain (blocks, transactions and shreds).
```

### Describe the data being stored onto Filecoin

```text
Solana blockchain data - daily data dumps of blocks and transactions produced by the validators of the chain.
```

### Where was the data currently stored in this dataset sourced from

Other

### If you answered "Other" in the previous question, enter the details here

```text
We maintain archive nodes that keep continuous records of all blocks storing copies of these records in S3 compatible storage.
```

### How do you plan to prepare the dataset

others/custom tool

### If you answered "other/custom tool" in the previous question, enter the details here

```text
Solana data is natively represented in IPLD format and can be exported directly as CAR files. There is no additional data preparation required.

IPLD schema: https://github.com/firedancer-io/radiance/blob/main/pkg/ipld/ipldsch/ipldsch_types.go
Car generator: https://github.com/firedancer-io/radiance/blob/main/pkg/ipld/cargen/cargen.go.
```

### Please share a sample of the data

```text
Solana blockchain data: https://console.cloud.google.com/storage/browser/mainnet-beta-ledger-us-ny5
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Monthly

### For how long do you plan to keep this dataset stored on Filecoin

Permanently

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, Europe

### How will you be distributing your data to storage providers

Cloud storage (i.e. S3), HTTP or FTP server

### How do you plan to choose storage providers

Others

### If you answered "Others" in the previous question, what is the tool or platform you plan to use

```text
We will be participating in the Spade pilot with the Network Growth team. This will automate matching us to SPs that meet our requirements in terms of replication, geography, retrievability, etc.
```

### If you already have a list of storage providers to work with, fill out their names and provider IDs below

```text
N/A
```

### How do you plan to make deals to your storage providers

Others/custom tool

### If you answered "Others/custom tool" in the previous question, enter the details here

```text
As mentioned above, we plan on using Spade, which will support both SP selection and Filecoin storage deal execution to onboard data to Filecoin.
```

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
Please share more detailed information about sps you will cooperate with.
Could you send an email to filplus-app-review@fil.org with your official domain in order to confirm your identity? Email name should includes the issue id #1943.

**Comment by linuskendall** [comment]
Edited to fix a few errors in the initial form fill up - a typo in company name and the data cap allocation number / week.

**Comment by anjor** [comment]
@Sunnyiscoming re SPs: we are targeting participating in the spade pilot and will have the spade engine match prepared data to eligible SPs across the network.

Similar to the [Dag House](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1838) application.

**Comment by kernelogic** [comment]
In support for PL initiated use cases

**Comment by simonkim0515** [comment]
## Datacap Request Trigger

#### Total DataCap requested 
> 5PiB

#### Expected weekly DataCap usage rate 
> 150TiB 

#### Client address
> f1ps34emfyq2tbioxwzr7tm2nqwprkiehsccvn7gy

**Comment by kernelogic** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebbvt6tdcawhl3fapssa32q4malyeqhvbamx6sukyqq43pmx6j34q 
#### Address 
> f1ps34emfyq2tbioxwzr7tm2nqwprkiehsccvn7gy
#### Datacap Allocated
> 75.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebbvt6tdcawhl3fapssa32q4malyeqhvbamx6sukyqq43pmx6j34q

**Comment by xinaxu** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedqswvwivm6j7tdj4nkqf6uav2mcsygsxbkpjdsn3znthcqazx5og 
#### Address 
> f1ps34emfyq2tbioxwzr7tm2nqwprkiehsccvn7gy
#### Datacap Allocated
> 75.00TiB
#### Signer Address
> f1k3ysofkrrmqcot6fkx4wnezpczlltpirmrpsgui
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedqswvwivm6j7tdj4nkqf6uav2mcsygsxbkpjdsn3znthcqazx5og

**Comment by Sunnyiscoming** [comment]
Email has been received.

**Comment by anjor** [comment]
Keep open

**Comment by linuskendall** [comment]
Would like to keep this one open, please.

**Comment by anjor** [comment]
checker:manualTrigger

**Comment by anjor** [comment]
Keep open please.

**Comment by anjor** [comment]
Keep open please.

**Comment by anjor** [comment]
Keep alive.

**Comment by anjor** [comment]
Keep open please.

**Comment by cryptowhizzard** [comment]
Dear linuskendall,

As notary I am doing due diligence on your LDN. I could not get retrieval to work. Can you please upload the car file of CID baga6ea4seaqmjsj7qqndqctfp4trt4pyipum5u6il6xbrcyo36fjnuwyxmgsyli ?

You can use our upload system at http://send.datasetcreators.com. Please select 7 days for the system to keep the file and post the link you received here so I (and other notaries) can download your content.

**Comment by anjor** [comment]
@cryptowhizzard , Linus is the client and not an SP, and therefore has little control over ensuring retrievals are working.

Is the above request to upload a car file to do due diligence on the data itself?

**Comment by linuskendall** [comment]
> Dear linuskendall,
> 
> As notary I am doing due diligence on your LDN. I could not get retrieval to work. Can you please upload the car file of CID baga6ea4seaqmjsj7qqndqctfp4trt4pyipum5u6il6xbrcyo36fjnuwyxmgsyli ?
> 
> You can use our upload system at http://send.datasetcreators.com. Please select 7 days for the system to keep the file and post the link you received here so I (and other notaries) can download your content.

Hi, 

As @anjor  mentioned we have been creating these deals for the storage providers and do not really control their retreival side. However, we do have the original CAR file data hosted here:

https://f003.backblazeb2.com/file/filecoin-car/sp-epoch0.car-baga6ea4seaqmjsj7qqndqctfp4trt4pyipum5u6il6xbrcyo36fjnuwyxmgsyli.car

This would have been the data ingested by the storage provider for this deal.

**Comment by cryptowhizzard** [comment]
Perfect. That's what i have been looking for!

I did commP on the data and that matches. 
Upon screening i found the blockchain data of Solana.

Thanks!

**Comment by anjor** [comment]
Also @cryptowhizzard if you are open to taking deals from Triton yourself, please ping Linus/me on slack and I will help get that set up.

We are definitely interested in having reliable retrievals working for this data!

**Comment by cryptowhizzard** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceafggogkgciheqkcrs7wktpqtjv7kk556cugqbuq4hb2waaktq5qs 
#### Address 
> f1ps34emfyq2tbioxwzr7tm2nqwprkiehsccvn7gy
#### Datacap Allocated
> 300.00TiB
#### Signer Address
> f1krmypm4uoxxf3g7okrwtrahlmpcph3y7rbqqgfa
#### Id
> ac2eac3f-a0f2-47d0-b453-a62a132a0d26
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceafggogkgciheqkcrs7wktpqtjv7kk556cugqbuq4hb2waaktq5qs

**Comment by linuskendall** [comment]
Please keep this open

**Comment by spaceT9** [comment]
checker:manualTrigger

**Comment by spaceT9** [comment]
The performance looks good overrall, it would be great to inrease http retrieval rate and inrease the number of copies and SPs

**Comment by dannyob** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebm7z5mfrhktdiusojls7frbooh3o6tofuy7k4u4e4oyxmojxdwuk 
#### Address 
> f1ps34emfyq2tbioxwzr7tm2nqwprkiehsccvn7gy
#### Datacap Allocated
> 300.00TiB
#### Signer Address
> f1k6wwevxvp466ybil7y2scqlhtnrz5atjkkyvm4a
#### Id
> ac2eac3f-a0f2-47d0-b453-a62a132a0d26
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebm7z5mfrhktdiusojls7frbooh3o6tofuy7k4u4e4oyxmojxdwuk

**Comment by anjor** [comment]
Keep open

**Comment by anjor** [comment]
Keep open

**Comment by Sunnyiscoming** [comment]
Hello, @linuskendall per the https://github.com/filecoin-project/notary-governance/issues/922 for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

This information will be reviewed by Fil+ Governance team to confirm validity and then the application will be allowed to move forward for additional notary review.

**Comment by linuskendall** [comment]
> Hello, @linuskendall per the [filecoin-project/notary-governance#922](https://github.com/filecoin-project/notary-governance/issues/922) for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.
> 
> This information will be reviewed by Fil+ Governance team to confirm validity and then the application will be allowed to move forward for additional notary review.

Hi @Sunnyiscoming, will be filling this out shortly.

**Comment by linuskendall** [comment]
Please keep open. We're working on the latest requests.

**Comment by Sunnyiscoming** [comment]
Have you completed the form?

**Comment by linuskendall** [comment]
We have struggled to find storage providers that are willing to take
datacap deals and are still working on that so we can have 4 replicas.

**Comment by linuskendall** [comment]
Please keep open

**Comment by Sunnyiscoming** [comment]
Please provide ID, City, Country, Organization of each SP here.

**Comment by linuskendall** [comment]
Please keep it open.

**Comment by Sunnyiscoming** [comment]
@linuskendall Hi,
Please provide ID, City, Country, Organization of each SP here.
