### ISSUE TITLE
[DataCap Application] The Joint Data & Cloud Services DMCC

### ISSUE THREAD

**Issue by JointData** [filecoin-project/filecoin-plus-large-datasets#1944]
### Data Owner Name

Joint Data

### Data Owner Country/Region

United Arab Emirates

### Data Owner Industry

IT & Technology Services

### Website

https://www.jointdc.com

### Social Media

```text
https://www.jointdc.com
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

200TiB

### On-chain address for first allocation

f1h4bgvbiww4ufud7h7vlwqmcbvmk7jsljxpgncyy

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
One of the infrastructure providers we work on Solana. We start by operating public RPC nodes, which are freely available to the Solana ecosystem in 2020. Since then, we have been active stakeholders in many Solana projects, including ensuring the replication and development of the Solana Historical Archives. This project attempts to provide a fully queryable historical archive of Solana data on Filecoin.
```

### Is this project associated with other projects/ecosystem stakeholders?

Yes

### If answered yes, what are the other projects/ecosystem stakeholders

```text
This effort is done in collaboration with the Solana Foundation,the Firedancer team at Jump Crypto and the Protocol Labs Outercore Network Growth team. We have also initiated partnerships with other stakeholders in the Solana ecosystem, such as other infrastructure providers who have pledged support and interest in maintaining and using this dataset.

In parallel to this project, there is an effort to upload historical ledger files that have been snapshotted from Solana (https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/923). The historical ledger archives that this other effort seeks to upload are a snapshot in time of the database generated by a Solana validator. The project described in this proposal seeks to upload historical archives in a format that allows data to be accessed semantically and directly by producing a content based DAG based on the logical elements of Solana’s blockchain (blocks, transactions and shreds).
```

### Describe the data being stored onto Filecoin

```text
Solana blockchain data - daily data dumps of blocks and transactions produced by the validators of the chain.
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### How do you plan to prepare the dataset

IPFS, lotus

### Please share a sample of the data

```text
https://mirrors.cloudholy.com/
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Monthly

### For how long do you plan to keep this dataset stored on Filecoin

Permanently

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, Africa, Europe

### How will you be distributing your data to storage providers

Cloud storage (i.e. S3), HTTP or FTP server, IPFS

### How do you plan to choose storage providers

Slack, Filmine, Big data exchange, Partners

### If you already have a list of storage providers to work with, fill out their names and provider IDs below

```text
N/A
```

### How do you plan to make deals to your storage providers

Boost client, Lotus client, Bidbot

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 5PiB

**Expected weekly DataCap usage rate**
> 200TiB

**Client address**
>f1h4bgvbiww4ufud7h7vlwqmcbvmk7jsljxpgncyy

**Comment by Sunnyiscoming** [comment]
Could you send an email to filplus-app-review@fil.org with your official domain in order to confirm your identity? Email name should includes the issue id #1944.

**Comment by jeffok** [comment]
Our data comes from the Internet and the data of our data center customers, providing public links and downloads for data center customers.

At present, our data is stored based on the distributed open source storage component Ceph, and the data is stored based on copy or hash. Each piece of data contains at least two data centers, in case a server or other failure in a data center makes the storage cluster inaccessible.

I am the technical director of the company, responsible for all technologies and businesses of the company, including but not limited to cloud computing and distributed storage.

**Comment by zcfil** [comment]
> Could you send an email to [filplus-app-review@fil.org](mailto:filplus-app-review@fil.org) with your official domain in order to confirm your identity? Email name should includes the issue id #1944.

@jeffok Did you reply to Sunnyiscoming's email? It's best to cc me as well reymond.bu@gmail.com

**Comment by zcfil** [comment]
Please send via the organization's jointdc.com email to confirm that you are a member of the organization
![image](https://user-images.githubusercontent.com/45065975/236817018-7dcd60f2-5c45-4a52-9ce9-38323ef0de96.png)

**Comment by JointData** [comment]
@zcfil  Good afternoon ,I have sent emails using my organization mailbox, please check, thank you .
my organization email address is: jeff@jointdc.com

**Comment by zcfil** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebqflddfg3w524noynwgdebjqka46m44yfcwz6hberjwgcdl2t3dw 
#### Address 
> f1h4bgvbiww4ufud7h7vlwqmcbvmk7jsljxpgncyy
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1cjzbiy5xd4ehera4wmbz63pd5ku4oo7g52cldga
#### Id
> 7f44d046-251b-4338-bdb8-9a87d65ba944
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebqflddfg3w524noynwgdebjqka46m44yfcwz6hberjwgcdl2t3dw

**Comment by JointData** [comment]
We will launch the proof next Monday, 29 May

**Comment by GaryGJG** [comment]
Support this first batch.

**Comment by GaryGJG** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedsf2nfmrrw32toav6izdtkdqjbejd7dwqc7pkwwn5vjsaz3jsqig 
#### Address 
> f1h4bgvbiww4ufud7h7vlwqmcbvmk7jsljxpgncyy
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1zffqhxwq2rrg7rtot6lmkl6hb2xyrrseawprzsq
#### Id
> 7f44d046-251b-4338-bdb8-9a87d65ba944
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedsf2nfmrrw32toav6izdtkdqjbejd7dwqc7pkwwn5vjsaz3jsqig
