### ISSUE TITLE
[DataCap Application] Shenzhen Xingrunhua Technology Co., Ltd. - The lens that records everything

### ISSUE THREAD

**Issue by bengKK** [filecoin-project/filecoin-plus-large-datasets#1946]
### Data Owner Name

Shenzhen Xingrunhua Technology Co., Ltd.

### Data Owner Country/Region

China

### Data Owner Industry

Arts & Recreation

### Website

www.kaihuijin.com

### Social Media

```text
www.kaihuijin.com
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

300TiB

### On-chain address for first allocation

f1xxkutyoil67pxzojiopo4m4o23kzorlihmq6s5i

### Data Type of Application

Public, Open Commercial/Enterprise

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Shenzhen Xingrunhua Technology Co., Ltd. is an elite team dedicated to the integrated communication of video marketing, integrating film and television planning, film and television shooting, and post-production into a one-stop service. Adhering to the creative concept of resource integration and innovation, we strive to create a Film and television works with profound cultural connotation and strong influence. Xingrunhua Culture Media constantly integrates new resources, new technologies, and new ideas, strengthens the in-depth operation and development of the film and television cultural industry, and gradually builds a cultural industry platform with film and television advertising as its key brand.
Through long-term, extensive and professional practice, Xingrunhua Technology has gathered a large number of high-end and strong industry resources, and produced a series of film and television advertising works with high reputation and commercial value. So far, it has served hundreds of enterprises, and successively served enterprises and institutions in various industries such as Poly, Ping An, Kugou, Greenland, China Resources C’estbon, PICC, Kone Elevator, Aoji, Kangmei Pharmaceutical, etc., and established a good reputation Industry reputation. Serving every link from concept planning to project completion.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
Mainly for promotional and advertising types of films, it is focused, targeted and orderly planning, shooting, editing, composite output and production of scenic spots, enterprises and brands. The purpose is to highlight the unique style and appearance of the company, highlight the strength of the company, and let people at different levels of society have a positive and good impression of the company, so as to build a good impression and trust in the company, and trust the company's products or services .
We have more than 15 years of experience in brand film and television production, including shooting Suzhou gardens, intelligent unmanned warehouses, and LOFT renovation series, providing and producing content for branding and other needs for these projects. The content stored is mainly from this part, which is the content made 5 years ago.
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### How do you plan to prepare the dataset

IPFS, lotus

### Please share a sample of the data

```text
https://drive.google.com/drive/folders/1dbGQzOvFdnroWbA8CC7mFJMX8UBkpAGL?usp=share_link
https://drive.google.com/drive/folders/1NGRsXJzPTtgEsD5z2vGeIwfI9LjlPrkh?usp=share_link
https://drive.google.com/drive/folders/1Y0axAGbctl0BdRCBVx0FBh2ehEECnprt?usp=share_link
https://drive.google.com/drive/folders/10_Bslb0MrbsA_MAt_AU4DR4gKeX_5aPN?usp=share_link
https://drive.google.com/drive/folders/1M_vSAcC_z6SZ_0Lz5Ebc3QNOo7p7lGIG?usp=share_link
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Sporadic

### For how long do you plan to keep this dataset stored on Filecoin

2 to 3 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, Europe

### How will you be distributing your data to storage providers

HTTP or FTP server, Shipping hard drives

### How do you plan to choose storage providers

Slack, Filmine, Big data exchange

### How do you plan to make deals to your storage providers

Lotus client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
Could you send an email to filplus-app-review@fil.org with your official domain in order to confirm your identity? Email name should includes the issue id #1946.

**Comment by Sunnyiscoming** [comment]
Any update here?

**Comment by bengKK** [comment]
![image](https://user-images.githubusercontent.com/132041466/236404675-b4249078-3bed-44e6-bb8e-de18b2c18f9c.png)

This week is a holiday, so I only saw the updated information now, we have sent an email, please check the email, the email name is: issue id #1946.

**Comment by cryptowhizzard** [comment]
Hi @bengKK 

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Looking at your application i have some questions:
As you are brand new on Github and have no history of past applications. Can you give me an introduction who you are and an introduction about your company? What hardware do you have over there to prepare this dataset? What is your internet connection speed? Do you already have the data downloaded on the premises?

Can you show us some visible proof of the size of your data and the storage / packing hardware you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230337462961356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!

**Comment by zcfil** [comment]
Hi @bengKK I could not find the website record information on the official website of the Ministry of Industry and Information Technology of China. Could you please explain the situation
<img width="1048" alt="image" src="https://user-images.githubusercontent.com/45065975/236673355-27a8ca08-3873-4513-9991-16ae3c2774ea.png">

**Comment by zcfil** [comment]
> www.kaihuijin.com

<img width="946" alt="image" src="https://user-images.githubusercontent.com/45065975/236673587-a351edf8-3fc4-4308-9cff-33f7ddf40e29.png">

**Comment by bengKK** [comment]
![20230510110516](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/132041466/c2227190-934e-4229-9bf5-158c7aa3904d)
Due to the adjustment of the company's shareholders, a qualification change is required. Then submit a new filing application. So the old one failed, and the new one didn't pass. Please understand that government affairs can sometimes consume very long time periods.

**Comment by bengKK** [comment]
![12bb45b5c31eeed7095160f820d570e](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/132041466/87ed65d9-9d75-42f8-ab8d-ee9c07d2c441)

![413ed2a4eac8c4c2369ce589c532e9f](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/132041466/349f8b7d-4723-49b0-b067-e9367e30cfa1)

I am Guo Ben, the vice president of the Runhua team, responsible for internal affairs. Runhua mainly engages in integrated communication of video marketing. To put it simply, we provide customers with a complete case of visual communication, including precious materials such as garden-style designed ancient buildings.
In terms of hardware, we have 4 cabinets with about 6.5P storage space. The bandwidth used is the bandwidth of the IDC computer room, which is currently 1Gbps. The data is all in the computer room we rent.


> Hi @bengKK
> 
> Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.
> 
> Looking at your application i have some questions: As you are brand new on Github and have no history of past applications. Can you give me an introduction who you are and an introduction about your company? What hardware do you have over there to prepare this dataset? What is your internet connection speed? Do you already have the data downloaded on the premises?
> 
> Can you show us some visible proof of the size of your data and the storage / packing hardware you have there?
> 
> As last question i would like you to fill out [this form](https://form.jotform.com/230337462961356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.
> 
> Thanks!

**Comment by bengKK** [comment]
Please help us through the application if you can. It's always been a holiday, if you have any questions, please contact my email: beng@kaihuijin.com

**Comment by sxxfuture-official** [comment]
According to the information disclosed above, it is in line with the rules of openness and transparency.
I will support in the first round and keep an eye on it .

**Comment by sxxfuture-official** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedbl7g5mctrg5rx542pejbfumvyngbjyii3fgqgdhge2ytvyr53i2 
#### Address 
> f1xxkutyoil67pxzojiopo4m4o23kzorlihmq6s5i
#### Datacap Allocated
> 150.00TiB
#### Signer Address
> f1foiomqlmoshpuxm6aie4xysffqezkjnokgwcecq
#### Id
> not found
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedbl7g5mctrg5rx542pejbfumvyngbjyii3fgqgdhge2ytvyr53i2

**Comment by mikezli** [comment]
<img width="1047" alt="d9f2e819b964996dd3407d2d51ec54b" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/118169683/68258fce-4a20-4e67-b267-4513b8369749">
Please send an email to confirm your identity, thank you!

**Comment by bengKK** [comment]
> <img alt="d9f2e819b964996dd3407d2d51ec54b" width="1047" src="https://user-images.githubusercontent.com/118169683/239814011-68258fce-4a20-4e67-b267-4513b8369749.png"> Please send an email to confirm your identity, thank you!

The email has been sent, please check it

**Comment by mikezli** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedisgm6w5nyzcqxsly2mvwf4dmei6gf5paoayewvublsavpukxpfk 
#### Address 
> f1xxkutyoil67pxzojiopo4m4o23kzorlihmq6s5i
#### Datacap Allocated
> 150.00TiB
#### Signer Address
> f1dnb3uz7sylxk6emti3ififcvu3nlufnnsjui6ea
#### Id
> 56b90f37-e7f8-4af4-9272-8bb104cea59d
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedisgm6w5nyzcqxsly2mvwf4dmei6gf5paoayewvublsavpukxpfk

**Comment by bengKK** [comment]
Technical colleagues have been arranged to follow up, please give me some more time to ensure that the project can be opened normally. Thanks

**Comment by bengKK** [comment]
Still in progress, thanks

**Comment by bengKK** [comment]
Still in progress, thanks

**Comment by bengKK** [comment]
checker:manualTrigger

**Comment by bengKK** [comment]
checker:manualTrigger

**Comment by cryptowhizzard** [comment]
Dear bengKK,

As notary I am doing due diligence on your LDN. I could not get retrieval to work. Can you please upload the car file of CID  ?

You can use our upload system at http://send.datasetcreators.com. Please select 7 days for the system to keep the file and post the link you received here so I (and other notaries) can download your content.

**Comment by bengKK** [comment]
please keep it open

**Comment by bengKK** [comment]
please keep it open

**Comment by bengKK** [comment]
please keep it open

**Comment by bengKK** [comment]
please keep it open

**Comment by bengKK** [comment]
checker:manualTrigger

**Comment by bengKK** [comment]
checker:manualTrigger

**Comment by bengKK** [comment]
checker:manualTrigger

**Comment by Sunnyiscoming** [comment]
Hello, @bengKK per the https://github.com/filecoin-project/notary-governance/issues/922 for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

This information will be reviewed by Fil+ Governance team to confirm validity and then the application will be allowed to move forward for additional notary review.

**Comment by bengKK** [comment]
Already submitted, thank you. @Sunnyiscoming 
![20231201150824](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/132041466/c0c09897-1719-43e4-ab3f-022a4f4b6fb0)

**Comment by Sunnyiscoming** [comment]
Please provide ID, City, Country, Organization of each SP here.

**Comment by bengKK** [comment]
@Sunnyiscoming Sorry, I just saw the message. I will deal with it as soon as possible.

**Comment by bengKK** [comment]
Okay, the scream will be dispersed and the SP ratio will be reduced.

**Comment by bengKK** [comment]
@Sunnyiscoming Sorry, due to the New Year holiday, I did not follow up in time. Please help to open it, thank you! The project is still in progress...

**Comment by bengKK** [comment]
@Sunnyiscoming Please help to open it. Next we will continue to package. Thank you very much.
