### ISSUE TITLE
[DataCap Application] NOAA Operational Forecast System (OFS) AWS Public Dataset

### ISSUE THREAD

**Issue by Lillie-li** [filecoin-project/filecoin-plus-large-datasets#1954]
### Data Owner Name

NOAA

### Data Owner Country/Region

United States

### Data Owner Industry

Environment

### Website

https://registry.opendata.aws/noaa-ofs/

### Social Media

```text
1. https://twitter.com/NOAA
2. https://www.youtube.com/usnoaagov
3. https://www.instagram.com/noaa/
4. https://www.noaa.gov/
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

1PiB

### On-chain address for first allocation

f1ns6d3rppdo2vsc2wb63zm3tjfzrcspoaw47bw3a

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
An Operational Forecast System (OFS) consists of the automated integration of observing system data streams, hydrodynamic model predictions, product dissemination and continuous quality-control monitoring. State-of-the-art numerical hydrodynamic models driven by real-time data and meteorological, oceanographic, and/or river flow rate forecasts form the core of these end-to-end systems. The OFS perform nowcast and short-term (0 hr. - 48 hr.) forecast predictions of pertinent parameters (e.g., water levels, currents, salinity, temperature, waves) and disseminate them to users.
I'm a sp who is participating in sealing in filecoin.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
NOMADS Production OFS Data (30 day rolling retention)
CO-OPS Operational OFS Data (Historical Retention)
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### How do you plan to prepare the dataset

IPFS, lotus, singularity

### Please share a sample of the data

```text
https://registry.opendata.aws/noaa-ofs/
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Sporadic

### For how long do you plan to keep this dataset stored on Filecoin

2 to 3 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, South America, Europe

### How will you be distributing your data to storage providers

IPFS, Shipping hard drives, Lotus built-in data transfer

### How do you plan to choose storage providers

Slack, Filmine, Big data exchange, Partners

### How do you plan to make deals to your storage providers

Lotus client, Singularity

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
Please share more detailed information about sps you will cooperate with.

**Comment by Sunnyiscoming** [comment]
Any update here?

**Comment by Lillie-li** [comment]
@Sunnyiscoming Hello Sunny, thank you for your hard work. I have just finished the holiday. 2 Sps have been contacted. We will ensure that there will be 4 Sps in the first round sealing in the future.

**Comment by cryptowhizzard** [comment]
Hi @Lillie-li 

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Looking at your application i have some questions:
As you are brand new on Github and have no history of past applications. Can you give me an introduction who you are and an introduction about your company?

Can you show us some visible proof of the size of your data and the storage / packing hardware you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230337462961356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!

**Comment by zcfil** [comment]
@Lillie-li Please list the SPs you are pre-collaborating with and the regions.
You can use your official domain name to filplus-app-review@fil.org Send email and copy to reymond.bu@gmail.com To confirm your identity? The email name should include question ID [# 1954.](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1954)

**Comment by RawTechVentures** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceadkdiot4lm535gsy727amghe3dntl35hvruuduh7ukawqed2zbqs 
#### Address 
> f1ns6d3rppdo2vsc2wb63zm3tjfzrcspoaw47bw3a
#### Datacap Allocated
> 256.00TiB
#### Signer Address
> f1txfsjmix4vlzido4dkildrnbw26owtlbslexmpa
#### Id
> 5648b48d-e892-45db-bb96-b8dfe7f9defb
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceadkdiot4lm535gsy727amghe3dntl35hvruuduh7ukawqed2zbqs

**Comment by Meibuy** [comment]
The applicant reached me on Slack and willing to support its first allocation.

**Comment by Meibuy** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacect5gqkt4kd24egie6ue6dcqvowaliadwkdnbddkt2w5plajgfugy 
#### Address 
> f1ns6d3rppdo2vsc2wb63zm3tjfzrcspoaw47bw3a
#### Datacap Allocated
> 256.00TiB
#### Signer Address
> f1bwugfihrmn3iyunzyxst5nttql3dge4khwmurtq
#### Id
> 5648b48d-e892-45db-bb96-b8dfe7f9defb
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacect5gqkt4kd24egie6ue6dcqvowaliadwkdnbddkt2w5plajgfugy

**Comment by Lillie-li** [comment]
Please keep my application open! Thank you

**Comment by Lillie-li** [comment]
Yes.

**Comment by cryptowhizzard** [comment]
checker:manualTrigger

**Comment by cryptowhizzard** [comment]
Hi,

I see that you are working with an SP who was previously tagged for CID sharing abuse. Can you explain please?

![Scherm­afbeelding 2023-07-28 om 13 51 19](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/36404435/7ce56fed-6ce3-4525-a2a7-4e6eb01c992f)

**Comment by Lillie-li** [comment]
![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/125252974/04541a40-0a7f-4e1c-91c7-09c0216edae9)
The sp support retrieval.

**Comment by clriesco** [comment]
Removed stale label and reopened issue :)

**Comment by cryptowhizzard** [comment]
Dear Lillie-li,

As notary I am doing due diligence on your LDN. I could not get retrieval to work. Can you please upload the car file of CID baga6ea4seaqosi2t66dyhua7zbftc5prgxlrpnvqdvdy4veunvxvqhqnxmzw6fq ?

You can use our upload system at http://send.datasetcreators.com. Please select 7 days for the system to keep the file and post the link you received here so I (and other notaries) can download your content.

**Comment by Lillie-li** [comment]
Yes, keep open.

Cuz this SP we used to cooperate with is in update, we will change other SPs to work with.

**Comment by spaceT9** [comment]
checker:manualTrigger

**Comment by Casey-PG** [comment]
checker:manualTrigger

**Comment by Casey-PG** [comment]
Updated report is great, willing to support!

**Comment by Casey-PG** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebjcwfh2echbbsfurffp42uprsevctbpq4yttbp6loagu7z2d2gdg 
#### Address 
> f1ns6d3rppdo2vsc2wb63zm3tjfzrcspoaw47bw3a
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f1d4yb3wags3mtddzesxoo63jv7dmlec3bq4yteni
#### Id
> 5b21b659-3352-4f3e-8714-d331175952ee
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebjcwfh2echbbsfurffp42uprsevctbpq4yttbp6loagu7z2d2gdg

**Comment by Bennyyangpu** [comment]
All metrics are good and willing to support.

**Comment by Bennyyangpu** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedxqjyyxs7uwarpjfih6jcpgoxkturzoouuaks4rfcwb2yvqdz55i 
#### Address 
> f1ns6d3rppdo2vsc2wb63zm3tjfzrcspoaw47bw3a
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f174fg3bqbln3zjnkxtyf6s54txqkr7yqkj6cig7y
#### Id
> 5b21b659-3352-4f3e-8714-d331175952ee
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedxqjyyxs7uwarpjfih6jcpgoxkturzoouuaks4rfcwb2yvqdz55i

**Comment by cryptowhizzard** [comment]
> Dear Lillie-li,
> 
> As notary I am doing due diligence on your LDN. I could not get retrieval to work. Can you please upload the car file of CID baga6ea4seaqosi2t66dyhua7zbftc5prgxlrpnvqdvdy4veunvxvqhqnxmzw6fq ?
> 
> You can use our upload system at http://send.datasetcreators.com. Please select 7 days for the system to keep the file and post the link you received here so I (and other notaries) can download your content.

Reminder.

**Comment by Lillie-li** [comment]
Keep open.

**Comment by Lillie-li** [comment]
Yes.

**Comment by herrehesse** [comment]
@kevzak Can we close all applications like this?

**Comment by Lillie-li** [comment]
> f1ns6d3rppdo2vsc2wb63zm3tjfzrcspoaw47bw3a

Already done.

**Comment by Lillie-li** [comment]
> This application has not seen any responses in the last 10 days. This issue will be marked with Stale label and will be closed in 4 days. Comment if you want to keep this application open.
> 
> -- Commented by Stale Bot.

Yes, please open. Thanks.

**Comment by herrehesse** [comment]
@kevzak Can we close all applications like this?

**Comment by herrehesse** [comment]
CLOSE. FULLY SELF-DEALING UNDER VPN.

**Comment by Sunnyiscoming** [comment]
Hello, @Lillie-li per the https://github.com/filecoin-project/notary-governance/issues/922 for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

This information will be reviewed by Fil+ Governance team to confirm validity and then the application will be allowed to move forward for additional notary review.

**Comment by Lillie-li** [comment]
CLOSE YOUR MOUTH AND BE A REAL MAN.
> CLOSE. FULLY SELF-DEALING UNDER VPN.

**Comment by Lillie-li** [comment]
@Sunnyiscoming The form is finished, please check it.

**Comment by herrehesse** [comment]
![Screenshot 2023-11-29 at 15 25 30](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/70132857/eea753bb-7ab9-4ed1-8ff3-c2ece0041d8a)
![Screenshot 2023-11-29 at 15 26 10](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/70132857/c1de91ae-50d6-4f33-a6de-36f4c6a2eff3)
![Screenshot 2023-11-29 at 15 26 23](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/70132857/e5caf61e-1c8b-4a14-b2db-16a168c13892)

All the above miners are under VPN, and caught abusing a massive amount on previous LDN. 
Suggesting IMMEDIATE closuse!

@Filplus-govteam

**Comment by Filplus-govteam** [comment]
SPs taking deals
f01844232 | Dallas, Texas, USHawk Host Inc. | 146.00 TiB | 30.42% | 146.00 TiB | 0.00%
f01927410 | Los Angeles, California, USHawk Host Inc. | 11.91 TiB | 2.48% | 11.91 TiB | 0.00%
f01844118 | New York City, New York, USSingleHop LLC | 60.97 TiB | 12.71% | 60.97 TiB | 0.00%
f01844999 | Dulles Town Center, Virginia, USSpeedyPage Ltd | 66.00 TiB | 13.75% | 66.00 TiB | 0.00%
f01844043 | Dulles Town Center, Virginia, USSpeedyPage Ltd | 61.00 TiB | 12.71% | 61.00 TiB | 0.00%
f01788231 | Dulles Town Center, Virginia, USSpeedyPage Ltd | 61.00 TiB | 12.71% | 61.00 TiB | 0.00%
f01807908 | London, England, GBSpeedyPage Ltd | 61.00 TiB | 12.71% | 61.00 TiB | 0.00%
f02244750 | London, England, GBSpeedyPage Ltd | 12.00 TiB | 2.50% | 12.00 TiB | 0.00%

SPs provided
f01844232 | Lukas | Dallas, Texas, US | x | Lukas
f01844999 | Tony |Ashburn, US | x | tony
f01788231 | Lucy | Ashburn, US | x | Lucy
f01807908 | Terence |  Madrid, Spain | x | Terence
f01844043 | Abel | Ashburn, US | x | Abel

Lukas email doesn't exist. Lucy with no contact. Abel email doesn't exist. 

Closing until clear list of all SP IDs is identified by entity and location
