### ISSUE TITLE
[DataCap Application] SCVSoft Inc.

### ISSUE THREAD

**Issue by benjioh5** [filecoin-project/filecoin-plus-large-datasets#1956]
### Data Owner Name
SCVSoft Inc.

### Data Owner Country/Region
Korea, Republic of

### Data Owner Industry
Web3 / Crypto

### Website
[https://www.scvsoft.net](https://www.scvsoft.net)

### Social Media
[at]scvs0ft (twitter)

### Total amount of DataCap being requested
1 PiB

### Weekly allocation of DataCap requested
1 TiB

### On-chain address for first allocation
f1o52vwkxh747rpga3n2nsl5dmncytzqirejnpjcy

### Data Type of Application
Public, Open Commercial/Enterprise

### Custom multisig
No

### Share a brief history of your project and organization
SCVSoft is Cryptocurrecny R&D and NFT firm

### Is this project associated with other projects/ecosystem stakeholders?
No

### If answered yes, what are the other projects/ecosystem stakeholders
null

### Describe the data being stored onto Filecoin
Website date backup e.g. Egloos data back up

### Where was the data currently stored in this dataset sourced from
My own storage infra

### If you answered "Other" in the previous question, enter the details here
null

### How do you plan to prepare the dataset
IPFS

### If you answered "other/custom tool" in the previous question, enter the details here
null

### Please share a sample of the data
Web crawl data

### Confirm that this is a public dataset that can be retrieved by anyone on the Network
Yes

### If you chose not to confirm, what was the reason
null

### What is the expected retrieval frequency for this data
Daily

### For how long do you plan to keep this dataset stored on Filecoin
More than 3 years

### In which geographies do you plan on making storage deals
Asia other than Greater China

### How will you be distributing your data to storage providers
HTTP or FTP server

### How do you plan to choose SP
I don't know yet

### If you answered "Others" in the previous question, what is the tool or platform you plan to use
null

### How do you plan to make deals to your storage providers
Lotus client

### If you answered "Others/custom tool" in the previous question, enter the details here
null

### Can you confirm that you will follow the Fil+ guideline
Yes

_Application created via [filplus.storage](https://filplus.storage)_

**Comment by Sunnyiscoming** [comment]
Can you share some data samples you have collected? 
Please provide more information to prove that you have 1 PB data to be stored.
Could you send an email to filplus-app-review@fil.org with your official domain in order to confirm your identity? Email name should includes the issue id #1956.
You can find sps in the Filecoin slack channel. https://filecoin.io/slack

**Comment by Sunnyiscoming** [comment]
Any update here?

**Comment by Sunnyiscoming** [comment]
Close for no reply.
