### ISSUE TITLE
[DataCap Application] Meta C&C

### ISSUE THREAD

**Issue by metacnc** [filecoin-project/filecoin-plus-large-datasets#196]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Meta C&C
- Website / Social Media: www.meta8cnc.com 
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 200TiB
- On-chain address for first allocation: f3rooj3ebr2ed4qdyrtdesaepkwlzhlh5c3oqpxdwcaudrxce3npejxriqzvblutf3lt37m5p2756vhi5vgw2q

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Our company have participated in first level and second level test nets too. We built a Main net and Currently owned about 40 nodes. Our company is growing into a storage company based on IPFS. We build a large scale of servers and operate storage centers, and provide professional management services. 
In addition, We are expanding our business to Cloud Service, so we are planning to get a large amount of Data from various companies. In order to prevent Self-Deal we plan to commit to storing 4 other replicas with other organizations(SPs). In this way we can get a copy in each continent, since it makes it even easier to retrieve for users in other countries and makes it more resilient to any infra issues or regulatory issues. 
```

What is the primary source of funding for this project?
```
Our clients’ company (such as Media Press, Korea Broadcast company etc)
```

What other projects/ecosystem stakeholders is this project associated with?
```
Broadcast Company, Meta Cloud Service 
```

## Use-case details

Describe the data being stored onto Filecoin
```
Enterprise Cloud.
We are offering storage for various Enterprises, data from them should be preserved long term on Filecoin and IPFS. Our client enterprises are SBS(korea’s one of the most largest broadcast company), Korea Consumer Association, Korean Academy of Venture Innovation, Korea Herald, Kiwa Korea, Stonehenge Asset, Biz Greet. 

Ref.  
https://www.sbs.co.kr
http://www.koreaherald.com/ 
http://www.kavi.or.kr/
https://cuk.or.kr/main/main.asp 
https://www.kiwa.com/kr/ko/ 
```

Where was the data in this dataset sourced from?
```
Mostly Asia, especially South Korea.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
yes
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes, it is a public data. 

https://user-images.githubusercontent.com/97426778/148723654-fdda38f8-8610-458c-83f6-f70279829c2f.mp4


```

What is the expected retrieval frequency for this data?
```
Our datas are informative, educational and entertaining contents, and enterprise related open data.  Expected search frequency is similar to that of Google drive and AWS cloud. Also, these data can be used for a long time. So, in the long term its retrieval frequency will be more higher. Moreover, We want to preserve these data almost as a permanent archive. 
```

For how long do you plan to keep this dataset stored on Filecoin?
```
Permanently, we'll constantly upload our data and store them for a long time.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
we plan to commit data to storing 4 other replicas with other organizations(SPs). In this way we will ditribute a copy of enterprise’s data in each continent. since it makes it even easier to retrieve for users in other countries and makes it more resilient to any infra issues or regulatory issues. 
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
We are planning to use both online and offline transfer. 
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We will select miners in each continent through miners reputation systems like filrep.io. 
```

How will you be distributing deals across storage providers?
```
We will use both online and offline transfer.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
We get the fund from our client companies. Also they want to start making deals as soon as possible. We already have technology to make deals and use Datacap. Also, as we are planning to make about four copies of data and store it to each continent’s SP, our business will help Filecoin and IPFS industry to own verified Data.  
```

**Comment by galen-mcandrew** [comment]
It looks like you are a storage provider service, and not the client owner of the data. The large dataset application is intended for clients with open public verifiable data, not storage providers self-dealing.

**Comment by metacnc** [comment]
We were a storage provider but now we are planning to operate cloud service business. Our SP is completely our own storage. 
Also we do have client’s(other company’s) open public data. We are planning to  intermediate clients and SPs. Moreover, to prevent self deal, we are planning to offer system that makes replica of our client’s data and provide it to 4 or more continent’s SPs.  We asked about this self dealing thing with deep kappur and will present our plan on 26th wed in fil+ governance call too.

**Comment by TimWilliams00** [comment]
As we understand, if your clients' data need to be stored, you should use your clients‘ profile to apply for LDN, not yourself.

**Comment by metacnc** [comment]
As we have many clients. We were planning to get a lot of Datacap with our company's profile and distribute datacap for each clients. Then Is it okay to apply for many LDN with same account? Or do we need to make each account using clients' profile?

**Comment by TimWilliams00** [comment]
Thanks for your honesty. We highly encourage the value of Data Partners in our community, but miners are normally not suitable for this role because of compliance factors.
