### ISSUE TITLE
[DataCap Application] NDLABS - Global Museums Collection <1/2>

### ISSUE THREAD

**Issue by NDLABS-OFFICE** [filecoin-project/filecoin-plus-large-datasets#1964]
### Data Owner Name

NDLABS

### Data Owner Country/Region

Singapore

### Data Owner Industry

Utilities

### Website

https://www.ndlabs.io/#/

### Social Media

```text
Twitter： @imNDLABS
Slack： @NDLABS-OFFICE
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

1PiB

### On-chain address for first allocation

f1yzbkrnxgmgqcp5ddhx33vxehc23y6t2qozxpl5a

### Data Type of Application

None

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
ND LABS has technical operation centers and nodes in Singapore, Hong Kong, the United States, and Dubai. Since Fil has launch of the mainnet in 2020, ND has begun to provide technical services to partners to help them complete the construction of storage services. At present, the accumulated storage power of ND exceeds 300P globally. The largest node has 100P storage power, and the node owns exceeds more than 1.4 million FIL. 
ND LABS is positioned as a decentralized storage service provider for WEB3. For a long time, ND not only focuses on building nodes for partners, but also explores how to provide better storage services for potential clients of web3. Since October 2021, ND has been deeply involved in the FilPlus project, vigorously promoting the Filplus project to partners who has effective data storage needs. We also providing them with a complete set of solutions and technical services for storing data in the FIL network. The Singapore and US nodes are the main storage nodes, which was provide real data storage for early customers.
```

### Is this project associated with other projects/ecosystem stakeholders?

Yes

### If answered yes, what are the other projects/ecosystem stakeholders

```text
We gonna cooperate with more SPs from other regions
```

### Describe the data being stored onto Filecoin

```text
Museums record important stages of human development, and we have collected the following open datasets for museums: 
Cooper-Hewitt's Collection Database 
Metropolitan Museum of Art Collection 
Minneapolis Institute of Arts metadata 
Natural History Museum (London) Data Portal 
Rijksmuseum Historical Art Collection 
Tate Collection metadata 
The Getty vocabularies
In total 800T, at least 6 copies.
```

### Where was the data currently stored in this dataset sourced from

Other

### How do you plan to prepare the dataset

IPFS, lotus

### Please share a sample of the data

```text
https://www.metmuseum.org
https://collections.artsmia.org
https://www.rijksmuseum.nl/en/research/conduct-research/data
https://github.com/tategallery/collection
http://vocab.getty.edu
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

1 to 1.5 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America

### How will you be distributing your data to storage providers

Cloud storage (i.e. S3), HTTP or FTP server, IPFS, Lotus built-in data transfer

### How do you plan to choose storage providers

Slack, Filmine, Partners

### If you already have a list of storage providers to work with, fill out their names and provider IDs below

```text
We are one of the members from Singapore SPWG and we also join in other SPWG. SPs from the SPWG are trustable and experienced. 
Also, we are engaging in encouraging more small SPs to join the Filecoin network. What’s more, We will provide those small SPs who newly join the network with technology support.
```

### How do you plan to make deals to your storage providers

Lotus client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 5PiB

**Expected weekly DataCap usage rate**
> 1PiB

**Client address**
>f1yzbkrnxgmgqcp5ddhx33vxehc23y6t2qozxpl5a

**Comment by Joyologist** [comment]
ND is a long time member of the community, they have done public data storage in conjunction with sp before and are willing to support this round

**Comment by Joyologist** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedpjbaygsu2ucx5omdmhtujhzsfhbb3kdtav7frhmaohanzu7ihqq 
#### Address 
> f1yzbkrnxgmgqcp5ddhx33vxehc23y6t2qozxpl5a
#### Datacap Allocated
> 256.00TiB
#### Signer Address
> f1txboxiscdm4f3okffyjmbilmwjtbisrbee72j6q
#### Id
> 8948230f-7ae9-48db-b4aa-75e399c013b7
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedpjbaygsu2ucx5omdmhtujhzsfhbb3kdtav7frhmaohanzu7ihqq

**Comment by liyunzhi-666** [comment]
Can you share the proof of data set size, data sample, and SP distribution plan with me? @NDLABS-OFFICE

**Comment by NDLABS-OFFICE** [comment]
@liyunzhi-666  Thanks for the reply, the following is our data sample and the list of sps ready to cooperate. At present, we are already making data download preparations, and the project will start at any time, hoping for your support.

https://www.metmuseum.org
https://collections.artsmia.org
https://www.rijksmuseum.nl/en/research/conduct-research/data
https://github.com/tategallery/collection
http://vocab.getty.edu

--------------------------

f02000936
Hong Kong, Central and Western, HK
7Road International HK Limited

f02006374
Hong Kong, Central and Western, HK
7Road International HK Limited

f02047841new
Hong Kong, Central and Western, HK
7Road International HK Limited

f02033219
Hong Kong, Central and Western, HK
7Road International HK Limited

f01924189
Singapore, Singapore, SG
Alibaba (US) Technology Co., Ltd.

f01831983
Wuwei, Gansu, CN
China Mobile communications corporation

f01972110
Yancheng, Jiangsu, CN
CHINA UNICOM China169 Backbone

f02037700new
Seoul, Seoul, KR
Korea Telecom

f02012175
Seoul, Seoul, KR
Korea Telecom

f01740934
Los Angeles, California, US
Zenlayer Inc

f02031006
Los Angeles, California, US
Zenlayer Inc

f01852363
Singapore, Singapore, SG
Zenlayer Inc

f01853077
Singapore, Singapore, SG
Zenlayer Inc

f01985611
Los Angeles, California, US
Zenlayer Inc

f01834253
Los Angeles, California, US
Zenlayer Inc

f01890456
Los Angeles, California, US
Zenlayer Inc

f01853104
Los Angeles, California, US
Zenlayer Inc

f01854080
Los Angeles, California, US
Zenlayer Inc

f01834291
Los Angeles, California, US
Zenlayer Inc

f01893023
Los Angeles, California, US
Zenlayer Inc

f01878534

**Comment by liyunzhi-666** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecd7lq3almbn43twqybeh52fiybv4bancv3eiitxktyp2uv43y5qg 
#### Address 
> f1yzbkrnxgmgqcp5ddhx33vxehc23y6t2qozxpl5a
#### Datacap Allocated
> 256.00TiB
#### Signer Address
> f1pszcrsciyixyuxxukkvtazcokexbn54amf7gvoq
#### Id
> 8948230f-7ae9-48db-b4aa-75e399c013b7
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecd7lq3almbn43twqybeh52fiybv4bancv3eiitxktyp2uv43y5qg

**Comment by TrueBlood1** [comment]
f01831983, f01740934, f01852363, f01853077, f01890456, f01853104, f01893023, f01878534 are SPs involved in a highly abusive application of Ipolloverse. https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/767 @raghavrmadya

**Comment by TrueBlood1** [comment]
@liyunzhi-666 What's your due diligence on these miners?

**Comment by liyunzhi-666** [comment]
To avoid any DC abuse, I strongly suggest you consider SPs other than f01831983, f01740934, f01852363, f01853077, f01890456, f01853104, f01893023, f01878534 in this round of allocation.@NDLABS-OFFICE

**Comment by TrueBlood1** [comment]
> I believe that these Sps (service providers) are qualified based on their experience and qualifications.

How? https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/767#issuecomment-1367122000

**Comment by NDLABS-OFFICE** [comment]
@TrueBlood1 As we all know, before the tool check bot, many sp in the storage if a large amount of data, in the processing of downloading data - storage to disk - tagging disk data label - mailing disk - data packaging this whole process, if the occurrence of technical or operation and maintenance of data problems is difficult to be detected. After the check bot tool came out, many sp have upgraded their respective processes or technologies, because this problem can be easily detected. So I hope to put the focus on the follow-up performance of these sp, there are problems to deal with problems, so that they become better. Thank you!

**Comment by TrueBlood1** [comment]
What a coincidence that mispacking caused **CID sharing with 35 clients**. The last thing we need is a fairy tale. You know exactly how this happened and you are doing it again. I'll add this to dispute you can join the discussion on slack https://filecoinproject.slack.com/archives/C0405HANNBT/p1684140667195489

**Comment by NDLABS-OFFICE** [comment]
So what you are questioning is that we can't work with node numbers that have shared data before for this project, right?
@TrueBlood1

**Comment by TrueBlood1** [comment]
Let's be specific, they're ND group‘s SPs in CID sharing with other ND organizations https://github.com/filecoin-project/notary-governance/issues/571

**Comment by james0012022** [comment]
> 

hey @raghavrmadya  I just checked Slack and found a thread mentioning my LDN and I provided my reply. What else should I proceed with as a client  to get things move forward?

**Comment by Sunnyiscoming** [comment]
checker:manualTrigger

**Comment by Joss-Hua** [comment]
checker:manualTrigger

**Comment by NDLABS-OFFICE** [comment]
checker:manualTrigger

**Comment by NDLABS-OFFICE** [comment]
checker:manualTrigger

**Comment by NDLABS-OFFICE** [comment]
checker:manualTrigger

**Comment by NDLABS-OFFICE** [comment]
checker:manualTrigger

**Comment by NDLABS-OFFICE** [comment]
checker:manualTrigger

**Comment by NDLABS-OFFICE** [comment]
[Global Museums Collection] was reorganized when RG notified in slack that it would no longer be submitted as a merged dataset. We will split this project to sort the data for upload. This request form will be closed.

**Comment by data-programs** [comment]
<img width="32" alt="KYC" Verified src="https://stable.filplus.storage/images/filplus-kyc-verified-badge.png"/>

This user’s identity has been verified through [filplus.storage](https://filplus.storage)
