### ISSUE TITLE
[DataCap Application] NDLABS - Global Museums Collection <2/2>

### ISSUE THREAD

**Issue by NDLABS-OFFICE** [filecoin-project/filecoin-plus-large-datasets#1965]
### Data Owner Name

NDLABS

### Data Owner Country/Region

Singapore

### Data Owner Industry

Utilities

### Website

https://www.ndlabs.io/#/

### Social Media

```text
Twitter： @imNDLABS
Slack： @NDLABS-OFFICE
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

1PiB

### On-chain address for first allocation

f1bde2mjgh2zkepkm5ivlctkul6jh2x63bvab3x4i

### Data Type of Application

None

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
ND LABS has technical operation centers and nodes in Singapore, Hong Kong, the United States, and Dubai. Since Fil has launch of the mainnet in 2020, ND has begun to provide technical services to partners to help them complete the construction of storage services. At present, the accumulated storage power of ND exceeds 300P globally. The largest node has 100P storage power, and the node owns exceeds more than 1.4 million FIL. 
ND LABS is positioned as a decentralized storage service provider for WEB3. For a long time, ND not only focuses on building nodes for partners, but also explores how to provide better storage services for potential clients of web3. Since October 2021, ND has been deeply involved in the FilPlus project, vigorously promoting the Filplus project to partners who has effective data storage needs. We also providing them with a complete set of solutions and technical services for storing data in the FIL network. The Singapore and US nodes are the main storage nodes, which was provide real data storage for early customers.
```

### Is this project associated with other projects/ecosystem stakeholders?

Yes

### If answered yes, what are the other projects/ecosystem stakeholders

```text
We gonna cooperate with more SPs from other regions
```

### Describe the data being stored onto Filecoin

```text
Museums record important stages of human development, and we have collected the following open datasets for museums: 
Cooper-Hewitt's Collection Database 
Metropolitan Museum of Art Collection 
Minneapolis Institute of Arts metadata 
Natural History Museum (London) Data Portal 
Rijksmuseum Historical Art Collection 
Tate Collection metadata 
The Getty vocabularies
In total 800T, at least 6 copies.
```

### Where was the data currently stored in this dataset sourced from

Other

### How do you plan to prepare the dataset

IPFS, lotus

### Please share a sample of the data

```text
https://www.metmuseum.org
https://collections.artsmia.org
https://www.rijksmuseum.nl/en/research/conduct-research/data
https://github.com/tategallery/collection
http://vocab.getty.edu
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

1 to 1.5 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America

### How will you be distributing your data to storage providers

Cloud storage (i.e. S3), HTTP or FTP server, Lotus built-in data transfer

### How do you plan to choose storage providers

Slack, Filmine, Partners

### If you already have a list of storage providers to work with, fill out their names and provider IDs below

```text
We are one of the members from Singapore SPWG and we also join in other SPWG. SPs from the SPWG are trustable and experienced. 
Also, we are engaging in encouraging more small SPs to join the Filecoin network. What’s more, We will provide those small SPs who newly join the network with technology support.
```

### How do you plan to make deals to your storage providers

Lotus client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
In total 800T, at least 6 copies.
Can you explain why you request for 10 PiB datacap?

**Comment by NDLABS-OFFICE** [comment]
@Sunnyiscoming Thanks for the reply, 6 copies is the minimum as we are still working with some quality sp's to store the data for backup. So it will be more than 5p.

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 5PiB

**Expected weekly DataCap usage rate**
> 1PiB

**Client address**
>f1bde2mjgh2zkepkm5ivlctkul6jh2x63bvab3x4i

**Comment by Joyologist** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedzgyhjinhjz2bzzvuqdqo6r7ehvnqyyf7v5uihuvourvxc5xviw2 
#### Address 
> f1bde2mjgh2zkepkm5ivlctkul6jh2x63bvab3x4i
#### Datacap Allocated
> 256.00TiB
#### Signer Address
> f1txboxiscdm4f3okffyjmbilmwjtbisrbee72j6q
#### Id
> 84ecc397-0a07-42fc-a735-ca398a0e9e5c
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedzgyhjinhjz2bzzvuqdqo6r7ehvnqyyf7v5uihuvourvxc5xviw2

**Comment by liyunzhi-666** [comment]
DD in #1964

**Comment by TrueBlood1** [comment]
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1964#issuecomment-1547336771

**Comment by NDLABS-OFFICE** [comment]
This is an active project and needs to be kept open

**Comment by NDLABS-OFFICE** [comment]
checker:manualTrigger

**Comment by phantom-rabbit** [comment]
checker:manualTrigger

**Comment by NDLABS-OFFICE** [comment]
checker:manualTrigger

**Comment by NDLABS-OFFICE** [comment]
checker:manualTrigger

**Comment by ipollo00** [comment]
checker:manualTrigger

**Comment by NDLABS-OFFICE** [comment]
checker:manualTrigger

**Comment by NDLABS-OFFICE** [comment]
[Global Museums Collection] was reorganized when RG notified in slack that it would no longer be submitted as a merged dataset. We will split this project to sort the data for upload. This request form will be closed.

**Comment by data-programs** [comment]
<img width="32" alt="KYC" Verified src="https://stable.filplus.storage/images/filplus-kyc-verified-badge.png"/>

This user’s identity has been verified through [filplus.storage](https://filplus.storage)
