### ISSUE TITLE
[DataCap Application] <Fogmeta Labs> - <Store Avalanche snapshots>

### ISSUE THREAD

**Issue by hengdingy** [filecoin-project/filecoin-plus-large-datasets#1966]
### Data Owner Name

Fogmeta Labs

### Data Owner Country/Region

China

### Data Owner Industry

Web3 / Crypto

### Website

https://fogmeta.com, https://fogmetalabs.com/chainsnap

### Social Media

```text
Twitter: https://twitter.com/FogMeta
GitHub: https://github.com/FogMeta
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

1PiB

### On-chain address for first allocation

f17yh2ozos2lxh5jqhogo37cwixormzapjq3lxt3a

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
The research of Fogmeta Labs spans multiple levels from system technology, infrastructure, and middleware to services and solutions, and involves future systems, network technology and business, distributed systems and management, information management, and interactive and innovative services. Based on the views on and practices in the industry, Fogmeta also solves the problem of business complexity through operations optimization and other technologies.

Chainsnap is a project developed by Fogmeta Labs for maintaining blockchain snapshots. This project enables the storing and retrieval of snapshots for blockchain projects including Filecoin, Polygon, Ethereum, Binance Smart Chain, Pocket, and Near.Please refer to: https://github.com/FogMeta/chainsnap.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
These are snapshots of Avalanche mainnet that are maintained by the Sensei Node(https://www.senseinode.com/) on a weekly basis. Please refer to the link here: http://186.233.187.26/.

Moreover, we're also running Avalanche nodes ourselves and will export a snapshot bi-weekly.
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### How do you plan to prepare the dataset

IPFS, lotus, graphsplit, others/custom tool

### If you answered "other/custom tool" in the previous question, enter the details here

```text
We'd also like to use the Swan Client tool (https://github.com/filswan/go-swan-client#Graphsplit) to prepare the dataset.
```

### Please share a sample of the data

```text
http://youravaxsnapshot.senseinode.com/avalanche_mainnet_20230430.tar (Size: 805G)
http://youravaxsnapshot.senseinode.com/avalanche_mainnet_20230507.tar (Size: 828G)
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Monthly

### For how long do you plan to keep this dataset stored on Filecoin

2 to 3 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, Africa, North America, South America, Europe, Australia (continent), Antarctica

### How will you be distributing your data to storage providers

HTTP or FTP server, IPFS, Shipping hard drives, Others

### How do you plan to choose storage providers

Slack, Partners, Others

### If you answered "Others" in the previous question, what is the tool or platform you plan to use

```text
FilSwan platform (https://filswan.com/) is another good choice for us to choose storage providers who meet our requirements.
```

### If you already have a list of storage providers to work with, fill out their names and provider IDs below

```text
The storage providers we'd like to work with are presented below. Some of them are from the FilSwan platform.
f03624
f010088
f02301
f08399
f02401
f0187709
f01163272
f01402814
f01072221
f0240185
f0143858
f01390330
f01225882
f0717969
f03223
f01395673
f01786736
f0836160
f032824
f01443744
f01871352
f01907556
f01946551
f02012951
f01970630
```

### How do you plan to make deals to your storage providers

Boost client, Lotus client, Others/custom tool

### If you answered "Others/custom tool" in the previous question, enter the details here

```text
https://github.com/filswan/go-swan-client
```

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 5PiB

**Expected weekly DataCap usage rate**
> 1PiB

**Client address**
>f17yh2ozos2lxh5jqhogo37cwixormzapjq3lxt3a

**Comment by zcfil** [comment]
You can use your official domain name to filplus-app-review@fil.org Send email and copy to reymond.bu@gmail.com To confirm your identity? The email name should include question ID # [1966](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1966).

**Comment by hengdingy** [comment]
<img width="731" alt="image" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/107467232/f13e2a55-d1bd-4a00-86b4-63a3df87b917">

@zcfil @Sunnyiscoming  please check the email

**Comment by zcfil** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedcmilnhewaqnhfvurymsdq6kgtfx2zhrfckspbsujgiyyt3ahe2w 
#### Address 
> f17yh2ozos2lxh5jqhogo37cwixormzapjq3lxt3a
#### Datacap Allocated
> 256.00TiB
#### Signer Address
> f1cjzbiy5xd4ehera4wmbz63pd5ku4oo7g52cldga
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedcmilnhewaqnhfvurymsdq6kgtfx2zhrfckspbsujgiyyt3ahe2w

**Comment by zcfil** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec35ry5cb6yxoug2q5rv4doaquimaq5v4tyfc2qbmjwb6w4bj5jti 
#### Address 
> f17yh2ozos2lxh5jqhogo37cwixormzapjq3lxt3a
#### Datacap Allocated
> 256.00TiB
#### Signer Address
> f1cjzbiy5xd4ehera4wmbz63pd5ku4oo7g52cldga
#### Id
> d641e900-9b01-453a-9569-711e2510a19d
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec35ry5cb6yxoug2q5rv4doaquimaq5v4tyfc2qbmjwb6w4bj5jti

**Comment by zcfil** [comment]
I have received your email, and will continue to pay attention to the data situation later

**Comment by kernelogic** [comment]
Well known client, willing to support.

**Comment by kernelogic** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec4aspkxn67egyfhsiuwaqpo6vco7qwehpfwkf7sri664jtpx53rk 
#### Address 
> f17yh2ozos2lxh5jqhogo37cwixormzapjq3lxt3a
#### Datacap Allocated
> 256.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### Id
> d641e900-9b01-453a-9569-711e2510a19d
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec4aspkxn67egyfhsiuwaqpo6vco7qwehpfwkf7sri664jtpx53rk

**Comment by hengdingy** [comment]
@Sunnyiscoming  @simonkim0515 Can you help us reopen this application? We are sending the snapshot to the filecoin network.

**Comment by hengdingy** [comment]
@Sunnyiscoming @simonkim0515 Can you help us reopen this application? We are sending the snapshot to the Filecoin network. you can see https://fogmetalabs.com/chainsnapshots/Avalanche
