### ISSUE TITLE
[DataCap Application] N LABS

### ISSUE THREAD

**Issue by ftest01** [filecoin-project/filecoin-plus-large-datasets#197]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: N LABS
- Website / Social Media: https://twitter.com/NlabsDAO
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5 PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 50 TiB
- On-chain address for first allocation: f1mqhue7evy7kd36w54j3hvdcf5hwjtjmsdf7egzi

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
With the development of the times, Open Dao becomes a popular topic in blockchain industry. Nlabs is a Metaverse DAO, Owner of Noun #61, 
@punk8185. 


Besides, N LABS is a decentralized NFT community for users to purchase, trade, and interact. 
```

What is the primary source of funding for this project?
```
Early investment from business partners. 
```

What other projects/ecosystem stakeholders is this project associated with?
```
Open DAO.
```

## Use-case details

Describe the data being stored onto Filecoin
```
Community data
Open Dao related data
NFT data
```

Where was the data in this dataset sourced from?
```
Data mainly from the company’s operation and public material that we need. 
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
Yes. In the reply.
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes, a public dataset.
```

What is the expected retrieval frequency for this data?
```
From time to time.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
540 days first.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
NA, Eourpe.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Online transfer is preferred.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We would like to choose part of SPs in Miner X. 
```

How will you be distributing deals across storage providers?
```
Not more than 30% from each SP.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes.
```

**Comment by ftest01** [comment]
![1](https://user-images.githubusercontent.com/96774208/148733488-a2f3e965-c315-4731-b3a8-c52434747bff.png)

**Comment by galen-mcandrew** [comment]
Do you have an official organization website? It looks like you are claiming ownership of NFT data, which you will be backing up on Filecoin; is that right? Do you have more details about these NFT's, like where they are hosted for purchase?

It sounds like you may need to work first with a direct notary to onboard some sample data to the network. https://plus.fil.org/verifiers

**Comment by dkkapur** [comment]
Closing this one out for inactivity. Please re-open if still relevant.
