### ISSUE TITLE
[DataCap Application] ssongsstore 

### ISSUE THREAD

**Issue by ssongsdesign** [filecoin-project/filecoin-plus-large-datasets#1970]
### Data Owner Name
ssongsstore

### What is your role related to the dataset
Dataset Owner

### Data Owner Country/Region
Republic of Korea

### Data Owner Industry
Other

### Website
[http://www.ssongsstore.com/](http://www.ssongsstore.com/)

### Social Media
[at]ssongs_store (instagram)

### Total amount of DataCap being requested
10 PiB

### Weekly allocation of DataCap requested
500 TiB

### On-chain address for first allocation
f1uywzkk7zjqp2ckqowkpnmli45xme7egx3jjx7ni

### Data Type of Application
Private Commercial/Enterprise

### Custom multisig
- [x] Use Custom Multisig

### Identifier
efil

### Share a brief history of your project and organization
Ssongsdesign is a design company headquartered in South Korea, established in 2012. The company provides comprehensive design services, covering the entire process from design planning to development and implementation. The design process includes market research, conceptual design, sketching and rendering, 3D modeling, prototype production, and production support, among several stages. With over 10 years of experience in the field of design outsourcing, the company designs various products for both domestic and international companies. It specializes in product design, industrial design, packaging design, and brand design, offering comprehensive design solutions.

### Is this project associated with other projects/ecosystem stakeholders?
No

### If answered yes, what are the other projects/ecosystem stakeholders
null

### Describe the data being stored onto Filecoin
Since 2012, our commercial collaborations have involved authorized production of design sketches and renderings, 3D modeling, design materials, prototypes, and product videos. We generate nearly 100 terabytes of data on average each year, and currently, our data storage exceeds 1 petabyte.

### Where was the data currently stored in this dataset sourced from
My own storage infra

### If you answered "Other" in the previous question, enter the details here
null

### How do you plan to prepare the dataset
lotus

### If you answered "other/custom tool" in the previous question, enter the details here
null

### Please share a sample of the data
https://drive.google.com/drive/folders/1tP1PoHavoTDmqTwbv1KYPhGHv-GnCJes

### Confirm that this is a public dataset that can be retrieved by anyone on the Network
No

### If you chose not to confirm, what was the reason
This dataset is not publicly available because it stores internal design documents, design sketches, renderings, 3D modeling files, prototypes, and product videos, which typically contain confidential information such as the company's design concepts, creative ideas, and design processes. To protect the company's design intellectual property and commercial interests, encryption is required.

### What is the expected retrieval frequency for this data
Yearly

### For how long do you plan to keep this dataset stored on Filecoin
Permanently

### In which geographies do you plan on making storage deals
None

### How will you be distributing your data to storage providers
Shipping hard drives

### How do you plan to choose SP
Partners

### If you answered "Others" in the previous question, what is the tool or platform you plan to use
null

### If you already have a list of storage providers to work with, fill out their names and provider IDs below
f02182085	BIGNET LTD	HONG KONG
f02182099	BIGNET LTD	Korea
f02183613	ADA Digital Global Inc	USA
f02183690	LEMON TELECOMMUNICATIONS LIMITED	HONG KONG
f02184109	JIU Cosmetic	Korea

### How do you plan to make deals to your storage providers
Singularity

### If you answered "Others/custom tool" in the previous question, enter the details here
null

### Can you confirm that you will follow the Fil+ guideline
Yes

_Application created via [filplus.storage](https://filplus.storage)_

**Comment by kevzak** [comment]
Hello - I can confirm that @ssongsdesign has completed KYC, KYB via Synaps check and also submitted the registration form including dataset size, sample and SP details. Notaries please review and reach out as needed.

**Comment by liyunzhi-666** [comment]
I am interested in this application, please send me the information including dataset size, sample and SP details. @kevzak

**Comment by liyunzhi-666** [comment]
- I reviewed the profile and assignment plan. 
- The client has passed the KYC, KYB review, and I will support the first round.

**Comment by liyunzhi-666** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebpuuqwfhitsgtg2yonlcxynqkjgdju3u5awjjgadndz43u2bzhmm 
#### Address 
> f1uywzkk7zjqp2ckqowkpnmli45xme7egx3jjx7ni
#### Datacap Allocated
> 250.00TiB
#### Signer Address
> f1pszcrsciyixyuxxukkvtazcokexbn54amf7gvoq
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebpuuqwfhitsgtg2yonlcxynqkjgdju3u5awjjgadndz43u2bzhmm

**Comment by ssongsdesign** [comment]
dear notary @liyunzhi-666 
Thank you very much for your contribution

Are there diligent and actively working notaries who are willing to associate themselves with this project?  @kevzak

**Comment by laurarenpanda** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebvyz54ynmyt6udtpuphzqbooi3mp2pxrkvtgamkc7mhf4m7hpgsu 
#### Address 
> f1uywzkk7zjqp2ckqowkpnmli45xme7egx3jjx7ni
#### Datacap Allocated
> 250.00TiB
#### Signer Address
> f1bp3tzp536edm7dodldceekzbsx7zcy7hdfg6uzq
#### Id
> fdd64d1f-2557-42af-8bd4-d48cf9d23c2f
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebvyz54ynmyt6udtpuphzqbooi3mp2pxrkvtgamkc7mhf4m7hpgsu

**Comment by laurarenpanda** [comment]
Willing to support the 1st round.
Since this is an E-FIL+ project, I'll pay attention to the Checker repost later.

**Comment by kevzak** [comment]
checker:manualTrigger

**Comment by ssongsdesign** [comment]
checker:manualTrigger

**Comment by ssongsdesign** [comment]
checker:manualTrigger

**Comment by ssongsdesign** [comment]
checker:manualTrigger

**Comment by ssongsdesign** [comment]
> 

Dear Notary Public:
Due to the inconsistent sealing ability and time of the storage service provider, more data is stored, please believe that this will disappear in the future.

**Comment by Fatman13** [comment]
checker:manualTrigger

**Comment by Fatman13** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacea5uzoqu6mccdbbrm4d2nxywuoscb326rch56x2zlwbgr2hj3asg4 
#### Address 
> f1uywzkk7zjqp2ckqowkpnmli45xme7egx3jjx7ni
#### Datacap Allocated
> 500.00TiB
#### Signer Address
> f1j3u7crhjzwb2cj5mq7vodlt4o66yoyci7lhcauy
#### Id
> 0b0636bb-1fb6-437e-8911-07ef2230c7dd
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacea5uzoqu6mccdbbrm4d2nxywuoscb326rch56x2zlwbgr2hj3asg4

**Comment by Fatman13** [comment]
Reached out by the client on Slack. Walked through how client could improve on current CIDchecker warning. Will support this round of allocation.

**Comment by Tom-OriginStorage** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebvhzy5udsu7prbzb2u7nwtzaaiqvlyse3pfibkhhkzitmmfxpph4 
#### Address 
> f1uywzkk7zjqp2ckqowkpnmli45xme7egx3jjx7ni
#### Datacap Allocated
> 500.00TiB
#### Signer Address
> f1q6bpjlqia6iemqbrdaxr2uehrhpvoju3qh4lpga
#### Id
> 0b0636bb-1fb6-437e-8911-07ef2230c7dd
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebvhzy5udsu7prbzb2u7nwtzaaiqvlyse3pfibkhhkzitmmfxpph4

**Comment by Sunnyiscoming** [comment]
checker:manualTrigger

**Comment by ssongsdesign** [comment]
checker:manualTrigger

**Comment by liyunzhi-666** [comment]
checker:manualTrigger

**Comment by liyunzhi-666** [comment]
The CID checker looks good and I can support this round.

**Comment by liyunzhi-666** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebgw2z5qjjvyfavs3muanuk5ceeq5qw34ktc5quvaqpkdb37e436e 
#### Address 
> f1uywzkk7zjqp2ckqowkpnmli45xme7egx3jjx7ni
#### Datacap Allocated
> 1000.00TiB
#### Signer Address
> f1pszcrsciyixyuxxukkvtazcokexbn54amf7gvoq
#### Id
> af89d3d2-622d-4ae9-af83-538a9871d8c7
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebgw2z5qjjvyfavs3muanuk5ceeq5qw34ktc5quvaqpkdb37e436e

**Comment by Holiday507** [comment]
I can finish the approval today

**Comment by Holiday507** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecntia5nasractfpgmekpjatj4jysf2itvrbmgbjp4qvrb7uitxsg 
#### Address 
> f1uywzkk7zjqp2ckqowkpnmli45xme7egx3jjx7ni
#### Datacap Allocated
> 1000.00TiB
#### Signer Address
> f1sa3dp3a7fwirrsxjdthvzneo7rnjcrrfllsnjpq
#### Id
> af89d3d2-622d-4ae9-af83-538a9871d8c7
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecntia5nasractfpgmekpjatj4jysf2itvrbmgbjp4qvrb7uitxsg

**Comment by kevzak** [comment]
Hello @ssongsdesign - there is now one additional step as part of E-Fil+ application process: To validate your applicant GitHub ID, we ask you to complete the KYC check (a third party ID verification process).

Steps: 
- Go to Filplus.storage
- Login with your GitHub information 
- You'll see a link to "get verified". Click and complete the steps to verify your identification (avoid using Firefox browser).
- Once complete, your application will show a "kyc verified" label for all to see.

Also note: 
- The KYC check process is completed by, [Togggle](http://togggle.io/). 
- During the user data collection process, all gathered information is securely encrypted using the individual user's personal key. This ensures that the data remains confidential and inaccessible, even to Togggle
- Applicant personal information will never show on GitHub applications, only the kyc verified label.
- At any time, applicants can request to have verification information removed from the system, let the Governance team know 

Let me know if you have any issues or questions.

**Comment by ssongsdesign** [comment]
@kevzak Hello ，Already followed the above steps
![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/131325319/1fc2b182-aa44-4588-9168-6b079edd4873)

**Comment by data-programs** [comment]
<img width="32" alt="KYC" Verified src="https://stable.filplus.storage/images/filplus-kyc-verified-badge.png"/>

This user’s identity has been verified through [filplus.storage](https://filplus.storage)

**Comment by psh0691** [comment]
ckecker:manualTrigger

**Comment by ssongsdesign** [comment]
checker:manualTrigger

**Comment by Fatman13** [comment]
checker:manualTrigger

**Comment by Fatman13** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebe3l5pnzbl5ddhsbvnf6imbnic3b24cespkikkpbriztsab5sx5s 
#### Address 
> f1uywzkk7zjqp2ckqowkpnmli45xme7egx3jjx7ni
#### Datacap Allocated
> 1.95PiB
#### Signer Address
> f1j3u7crhjzwb2cj5mq7vodlt4o66yoyci7lhcauy
#### Id
> 993b39dc-7f67-4b6c-ac22-3d68035060dd
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebe3l5pnzbl5ddhsbvnf6imbnic3b24cespkikkpbriztsab5sx5s

**Comment by Fatman13** [comment]
REached out by the client on Slack. CIDcheker looks good and distribution has been improved since last time.

**Comment by laurarenpanda** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedvr6ucsqnlou22umbyxmxbkpe7gmabfs6i7d2s5p6tfqzxeslgk4 
#### Address 
> f1uywzkk7zjqp2ckqowkpnmli45xme7egx3jjx7ni
#### Datacap Allocated
> 1.95PiB
#### Signer Address
> f1bp3tzp536edm7dodldceekzbsx7zcy7hdfg6uzq
#### Id
> 993b39dc-7f67-4b6c-ac22-3d68035060dd
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedvr6ucsqnlou22umbyxmxbkpe7gmabfs6i7d2s5p6tfqzxeslgk4

**Comment by ssongsdesign** [comment]
checker:manualTrigger

**Comment by ssongsdesign** [comment]
checker:manualTrigger

**Comment by ssongsdesign** [comment]
checker:manualTrigger

**Comment by ssongsdesign** [comment]
checker:manualTrigger

**Comment by ssongsdesign** [comment]
checker:manualTrigger

**Comment by ssongsdesign** [comment]
checker:manualTrigger

**Comment by steven004** [comment]
Sorry, failed to sign. Just noticed I am not a signer of f01940930, do not know why.

**Comment by ssongsdesign** [comment]
> Sorry, failed to sign. Just noticed I am not a signer of f01940930, do not know why.

maybe i missed something

**Comment by ssongsdesign** [comment]
checker:manualTrigger

**Comment by ssongsdesign** [comment]
checker:manualTrigger

**Comment by Suyanj** [comment]
checker:manualTrigger

**Comment by Suyanj** [comment]
![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/107249346/3a058857-b332-4d4d-9169-d70a013a7f30)

**Comment by Suyanj** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedm2lul2is5bc7p6wldzvgfo23r3ftnwdhf5soxyvvggmvm5msa5u 
#### Address 
> f1uywzkk7zjqp2ckqowkpnmli45xme7egx3jjx7ni
#### Datacap Allocated
> 1.95PiB
#### Signer Address
> f1ihv7gz3vn3xqvikpt4rwryecgisl7745lodx3yi
#### Id
> 993b39dc-7f67-4b6c-ac22-3d68035060dd
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedm2lul2is5bc7p6wldzvgfo23r3ftnwdhf5soxyvvggmvm5msa5u

**Comment by newwebgroup** [comment]
checker:manualTriggerv

**Comment by newwebgroup** [comment]
checker:manualTrigger

**Comment by newwebgroup** [comment]
Fil-E ’s LDN,
Good CID Checker report,
The SP distribution is scattered and the replicas are in compliance.
There is no CID sharing.

<img width="584" alt="image" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/100118145/726b6232-9009-4592-bddf-aa4a876512bf">

**Comment by newwebgroup** [comment]
When signing the LDN of this Fil-E, I encountered some problems.
Please check and fix @kevzak 
<img width="484" alt="image" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/100118145/2b1b382b-fcbf-48e0-8993-780e86e5df6d">

**Comment by ssongsdesign** [comment]
Thank you for your efforts. Is there any progress here?
@newwebgroup @kevzak

**Comment by huseyincansoylu** [comment]
Can you send me the address that you are using to sign? @newwebgroup

**Comment by huseyincansoylu** [comment]
also if you attempted to sign more than one request at the same time, please try them individually report me back.
@newwebgroup

**Comment by ssongsdesign** [comment]
checker:manualTrigger

**Comment by ssongsdesign** [comment]
checker:manualTrigger

**Comment by ssongsdesign** [comment]
checker:manualTrigger

**Comment by ssongsdesign** [comment]
checker:manualTrigger

**Comment by ssongsdesign** [comment]
checker:manualTrigger

**Comment by liyunzhi-666** [comment]
checker:manualTrigger

**Comment by liyunzhi-666** [comment]
The client reached out to me on slack. I checked previous DD records,CID Checker,retrieval bots. Everything looks good and I can support this round.

**Comment by liyunzhi-666** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedy2q3ie7fyuyqq3taebnn3ajukuntcrvadbnuvucnmtausj4cl3g 
#### Address 
> f1uywzkk7zjqp2ckqowkpnmli45xme7egx3jjx7ni
#### Datacap Allocated
> 1.95PiB
#### Signer Address
> f1pszcrsciyixyuxxukkvtazcokexbn54amf7gvoq
#### Id
> 9fe182a1-f375-4a28-95be-c8510dccfc77
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedy2q3ie7fyuyqq3taebnn3ajukuntcrvadbnuvucnmtausj4cl3g

**Comment by laurarenpanda** [comment]
checker:manualTrigger

**Comment by laurarenpanda** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebrt2wvaxltyfmrfhdzunoiksyuyb7sr3i4rvn5irrclh3uajpexc 
#### Address 
> f1uywzkk7zjqp2ckqowkpnmli45xme7egx3jjx7ni
#### Datacap Allocated
> 1.95PiB
#### Signer Address
> f1bp3tzp536edm7dodldceekzbsx7zcy7hdfg6uzq
#### Id
> 9fe182a1-f375-4a28-95be-c8510dccfc77
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebrt2wvaxltyfmrfhdzunoiksyuyb7sr3i4rvn5irrclh3uajpexc

**Comment by ssongsdesign** [comment]
checker:manualTrigger

**Comment by ssongsdesign** [comment]
checker:manualTrigger

**Comment by ssongsdesign** [comment]
checker:manualTrigger

**Comment by liyunzhi-666** [comment]
checker:manualTrigger

**Comment by liyunzhi-666** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedsmmhf2uosjoegmvbrznajvxmsclvkr244ntw2iovfi4qpzncx6e 
#### Address 
> f1uywzkk7zjqp2ckqowkpnmli45xme7egx3jjx7ni
#### Datacap Allocated
> 1.95PiB
#### Signer Address
> f1pszcrsciyixyuxxukkvtazcokexbn54amf7gvoq
#### Id
> adfa2b47-307a-4861-9df1-f6e14fce6c78
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedsmmhf2uosjoegmvbrznajvxmsclvkr244ntw2iovfi4qpzncx6e

**Comment by derricktan23** [comment]
checker:manualTrigger

**Comment by derricktan23** [comment]
The applicant reached out to me on slack, the cid checker report looks healthy, will support this round.

**Comment by Tom-OriginStorage** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced3aukadp7idgehjmrnxmntwkdn3xogn7lcsf5rbzgyy6bcszfets 
#### Address 
> f1uywzkk7zjqp2ckqowkpnmli45xme7egx3jjx7ni
#### Datacap Allocated
> 1.95PiB
#### Signer Address
> f1q6bpjlqia6iemqbrdaxr2uehrhpvoju3qh4lpga
#### Id
> adfa2b47-307a-4861-9df1-f6e14fce6c78
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced3aukadp7idgehjmrnxmntwkdn3xogn7lcsf5rbzgyy6bcszfets

**Comment by ssongsdesign** [comment]
checker:manualTrigger

**Comment by ssongsdesign** [comment]
checker:manualTrigger

**Comment by ssongsdesign** [comment]
checker:manualTrigger

**Comment by ssongsdesign** [comment]
checker:manualTrigger

**Comment by ssongsdesign** [comment]
checker:manualTrigger

**Comment by PluskitOfficial** [comment]
Looks good. Will sign this round.

**Comment by PluskitOfficial** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacea23ypy2ui3p4v3loaru4evgtd6gdpub7os2dasjiqerzx4hf5eay 
#### Address 
> f1uywzkk7zjqp2ckqowkpnmli45xme7egx3jjx7ni
#### Datacap Allocated
> 502.79TiB
#### Signer Address
> f1tgnlhtcmhwipfm7thsftxhn5k52velyjlazpvka
#### Id
> d193eafc-f64a-46ab-aa93-5915bb6065c9
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacea23ypy2ui3p4v3loaru4evgtd6gdpub7os2dasjiqerzx4hf5eay

**Comment by cryptowhizzard** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebyxcj26sgxw62knjioyfva356qegz46nkzbw4ohpu34aty4kjnpa 
#### Address 
> f1uywzkk7zjqp2ckqowkpnmli45xme7egx3jjx7ni
#### Datacap Allocated
> 502.79TiB
#### Signer Address
> f1krmypm4uoxxf3g7okrwtrahlmpcph3y7rbqqgfa
#### Id
> d193eafc-f64a-46ab-aa93-5915bb6065c9
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebyxcj26sgxw62knjioyfva356qegz46nkzbw4ohpu34aty4kjnpa

**Comment by cryptowhizzard** [comment]
Tested retrieval en data, both looking Ok. Distribution is also ok.

**Comment by MatrixStorage** [comment]
I am willing to support

**Comment by MatrixStorage** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebjfqrdfyj72g54qzzktpf7o4fcvcfwu3q6n4jzde7r43clo5vwtq 
#### Address 
> f1uywzkk7zjqp2ckqowkpnmli45xme7egx3jjx7ni
#### Datacap Allocated
> 502.79TiB
#### Signer Address
> f1tbxqwjxfyv7swsdin4einirlsfquv3vnmlapley
#### Id
> d193eafc-f64a-46ab-aa93-5915bb6065c9
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebjfqrdfyj72g54qzzktpf7o4fcvcfwu3q6n4jzde7r43clo5vwtq

**Comment by ssongsdesign** [comment]
checker:manualTrigger

**Comment by ssongsdesign** [comment]
checker:manualTrigger

**Comment by ssongsdesign** [comment]
checker:manualTrigger

**Comment by Sunnyiscoming** [comment]
SP List provided:
[{"providerID":"f02182085","City":"HK","Country":"CN","SPOrg","BIGNETLTD"},
{"providerID":"f02182099","City":"XYZ","Country":"Korea","SPOrg","BIGNETLTD"},
{"providerID":"f02183613","City":"XYZ","Country":"USA","SPOrg","ADADigitalGlobalInc"},
{"providerID":"f02183690","City":"HK","Country":"CN","SPOrg","LEMONTELECOMMUNICATIONSLIMITED"},
{"providerID":"f02184109","City":"XYZ","Country":"Korea","SPOrg","JIUCosmetic"},]
