### ISSUE TITLE
[DataCap Application] ssongsstore <2/2>

### ISSUE THREAD

**Issue by ssongsdesign** [filecoin-project/filecoin-plus-large-datasets#1971]
### Data Owner Name
ssongsstore

### What is your role related to the dataset
Dataset Owner

### Data Owner Country/Region
Republic of Korea

### Data Owner Industry
Other

### Website
[http://www.ssongsstore.com/](http://www.ssongsstore.com/)

### Social Media
[at]ssongs_store (instagram)

### Total amount of DataCap being requested
5 PiB

### Weekly allocation of DataCap requested
500 TiB

### On-chain address for first allocation
f1uywzkk7zjqp2ckqowkpnmli45xme7egx3jjx7ni

### Data Type of Application
Private Commercial/Enterprise

### Custom multisig
- [x] Use Custom Multisig

### Identifier
efil

### Share a brief history of your project and organization
Ssongsdesign is a design company headquartered in South Korea, established in 2012. The company provides comprehensive design services, covering the entire process from design planning to development and implementation. The design process includes market research, conceptual design, sketching and rendering, 3D modeling, prototype production, and production support, among several stages. With over 10 years of experience in the field of design outsourcing, the company designs various products for both domestic and international companies. It specializes in product design, industrial design, packaging design, and brand design, offering comprehensive design solutions.

### Is this project associated with other projects/ecosystem stakeholders?
No

### If answered yes, what are the other projects/ecosystem stakeholders
null

### Describe the data being stored onto Filecoin
Since 2012, our commercial collaborations have involved authorized production of design sketches and renderings, 3D modeling, design materials, prototypes, and product videos. We generate nearly 100 terabytes of data on average each year, and currently, our data storage exceeds 1 petabyte.

### Where was the data currently stored in this dataset sourced from
My own storage infra

### If you answered "Other" in the previous question, enter the details here
null

### How do you plan to prepare the dataset
lotus

### If you answered "other/custom tool" in the previous question, enter the details here
null

### Please share a sample of the data
https://drive.google.com/drive/folders/1tP1PoHavoTDmqTwbv1KYPhGHv-GnCJes

### Confirm that this is a public dataset that can be retrieved by anyone on the Network
No

### If you chose not to confirm, what was the reason
This dataset is not publicly available because it stores internal design documents, design sketches, renderings, 3D modeling files, prototypes, and product videos, which typically contain confidential information such as the company's design concepts, creative ideas, and design processes. To protect the company's design intellectual property and commercial interests, encryption is required.

### What is the expected retrieval frequency for this data
Yearly

### For how long do you plan to keep this dataset stored on Filecoin
Permanently

### In which geographies do you plan on making storage deals
None

### How will you be distributing your data to storage providers
Shipping hard drives

### How do you plan to choose SP
Partners

### If you answered "Others" in the previous question, what is the tool or platform you plan to use
null

### If you already have a list of storage providers to work with, fill out their names and provider IDs below
f02182085	BIGNET LTD	HONG KONG
f02182099	BIGNET LTD	Korea
f02183613	ADA Digital Global Inc	USA
f02183690	LEMON TELECOMMUNICATIONS LIMITED	HONG KONG
f02184109	JIU Cosmetic	Korea

### How do you plan to make deals to your storage providers
Singularity

### If you answered "Others/custom tool" in the previous question, enter the details here
null

### Can you confirm that you will follow the Fil+ guideline
Yes

_Application created via [filplus.storage](https://filplus.storage)_

**Comment by kevzak** [comment]
@ssongsdesign Please close this application and for the 1/2 application please increase the DataCap requested from 5 to 10PiB.

**Comment by ssongsdesign** [comment]
> 

@kevzak Sure, I will close the application and change #1970  to 10PiB. Please help me verify if the modification was successful.

**Comment by data-programs** [comment]
<img width="32" alt="KYC" Verified src="https://stable.filplus.storage/images/filplus-kyc-verified-badge.png"/>

This user’s identity has been verified through [filplus.storage](https://filplus.storage)
