### ISSUE TITLE
[DataCap Application] - TCGA

### ISSUE THREAD

**Issue by Hugh-Top** [filecoin-project/filecoin-plus-large-datasets#1974]
### Data Owner Name

Genomic Data Commons (GDC)

### What is your role related to the dataset

Storage provider filling out application on behalf of the data owner

### Data Owner Country/Region

United States

### Data Owner Industry

Life Science / Healthcare

### Website

https://registry.opendata.aws/tcga

### Social Media

```text
N/A
```

### Total amount of DataCap being requested

1PiB

### Weekly allocation of DataCap requested

200TiB

### On-chain address for first allocation

f1tzbllzb7nbmswrw4zgn2nnewqd45nj7qp7vajoy

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
N/A
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
The Cancer Genome Atlas (TCGA), a collaboration between the National Cancer Institute (NCI) and National Human Genome Research Institute (NHGRI), aims to generate comprehensive, multi-dimensional maps of the key genomic changes in major types and subtypes of cancer.
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### How do you plan to prepare the dataset

singularity

### Please share a sample of the data

```text
aws s3 ls --no-sign-request s3://tcga-2-open/
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Sporadic

### For how long do you plan to keep this dataset stored on Filecoin

Less than 1 year

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, Europe

### How will you be distributing your data to storage providers

HTTP or FTP server

### How do you plan to choose storage providers

Slack, Partners

### If you already have a list of storage providers to work with, fill out their names and provider IDs below

```text
f02145020
f02301
f03223
f0143858
f0240185
f01969779
f020522
```

### How do you plan to make deals to your storage providers

Singularity

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
Please share a brief history of your project and organization. 
How much data are in this dataset? How many copies will you store?

**Comment by Hugh-Top** [comment]
> Please share a brief history of your project and organization. How much data are in this dataset? How many copies will you store?

@Sunnyiscoming  I didn't have any project. It's my first ldn application.
This project has  almost 100TiB raw data. I will save 10 copies.

**Comment by Sunnyiscoming** [comment]
Can you introduce your organizaion? 
Which are your nodes?

**Comment by Hugh-Top** [comment]
> Can you introduce your organizaion? Which are your nodes?

@Sunnyiscoming  Hello, we are a small team on fliecoin. i have nonly one node f01969779. I will find more sp for cooperation. think you.

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 1PiB

**Expected weekly DataCap usage rate**
> 200TiB

**Client address**
>f1tzbllzb7nbmswrw4zgn2nnewqd45nj7qp7vajoy

**Comment by zcfil** [comment]
Please list the SPs you are pre-collaborating with and the regions.
Is your data publicly available？

**Comment by Hugh-Top** [comment]
> Please list the SPs you are pre-collaborating with and the regions. Is your data publicly available？
@zcfil  hello, this dataset is public from aws.

|sp|region|
|--|--|
|f02145020|CN|
|f02301|US|
|f03223|US|
|f0143858|US|
|f0240185|US|
|f01969779|US|
|f020522|DE|

think you

**Comment by zcfil** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceayhojxycfrzpv3chxk5jicph7byaaypun2tqsh6tkf4v3jxxcni2 
#### Address 
> f1tzbllzb7nbmswrw4zgn2nnewqd45nj7qp7vajoy
#### Datacap Allocated
> 51.19TiB
#### Signer Address
> f1cjzbiy5xd4ehera4wmbz63pd5ku4oo7g52cldga
#### Id
> fb06c256-a6c8-4fba-94c3-bf268045a80f
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceayhojxycfrzpv3chxk5jicph7byaaypun2tqsh6tkf4v3jxxcni2

**Comment by zcfil** [comment]
First round of support and will continue to follow up in the future

**Comment by Aaron01230** [comment]
According to the above comment, we can support the first round and keep follow up

**Comment by Aaron01230** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacede3jim7dhfczxwppy62idm56wley5fuoghq6sv7e5ejefaovnkuc 
#### Address 
> f1tzbllzb7nbmswrw4zgn2nnewqd45nj7qp7vajoy
#### Datacap Allocated
> 51.19TiB
#### Signer Address
> f1xrnysd4gimg64d4l6qi7ulzwwq22c6vfg6lpw3i
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacede3jim7dhfczxwppy62idm56wley5fuoghq6sv7e5ejefaovnkuc

**Comment by Hugh-Top** [comment]
I see

**Comment by Hugh-Top** [comment]
checker:manualTrigger

**Comment by kernelogic** [comment]
Could you explain the geographical concentration in the CID report?
<img width="994" alt="image" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/3711825/7a918793-5e4c-4e55-920d-34d8d95994b1">

**Comment by Hugh-Top** [comment]
> Could you explain the geographical concentration in the CID report? <img alt="image" width="994" src="https://user-images.githubusercontent.com/3711825/242770809-7a918793-5e4c-4e55-920d-34d8d95994b1.png">

@kernelogic  think you. I will propose deal to other sp on Greater China and Europe.

**Comment by kernelogic** [comment]
Given it's early stage, I will support and observe future allocations.

**Comment by kernelogic** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacediph6tiwwyx7ee4taehz5qlstrublfi24cgazvep32js7we3655a 
#### Address 
> f1tzbllzb7nbmswrw4zgn2nnewqd45nj7qp7vajoy
#### Datacap Allocated
> 102.39TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### Id
> 395be08d-eae9-4063-9b2a-fa1c65762e31
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacediph6tiwwyx7ee4taehz5qlstrublfi24cgazvep32js7we3655a

**Comment by METAVERSEDATAMINING** [comment]
The retrieval is functioning properly.

<img width="1120" alt="0602" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/111408360/4658cd62-0afd-41da-9597-e33cd21fd50b">
<img width="769" alt="06021" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/111408360/73de870f-914a-4eeb-8641-69e8776a990d">

**Comment by METAVERSEDATAMINING** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecrhxfpf375j5vebacsusowdieor4enpioxzrygnxsk6zwhzwuxl6 
#### Address 
> f1tzbllzb7nbmswrw4zgn2nnewqd45nj7qp7vajoy
#### Datacap Allocated
> 102.39TiB
#### Signer Address
> f17idrnfnxl2mbgcgr57a6z2c6lj2qx56gvm3336i
#### Id
> 395be08d-eae9-4063-9b2a-fa1c65762e31
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecrhxfpf375j5vebacsusowdieor4enpioxzrygnxsk6zwhzwuxl6

**Comment by Sunnyiscoming** [comment]
checker:manualTrigger

**Comment by Hugh-Top** [comment]
checker:manualTrigger

**Comment by NiwanDao** [comment]
checker:manualTrigger

**Comment by NiwanDao** [comment]
The report result looks good to me.

**Comment by NiwanDao** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebpjzcd5y2o6aprryo6tei3lsnfcbqec3hdqukqxkr5j6vviqa5hw 
#### Address 
> f1tzbllzb7nbmswrw4zgn2nnewqd45nj7qp7vajoy
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1a2lia2cwwekeubwo4nppt4v4vebxs2frozarz3q
#### Id
> f7c629fb-42fa-4a2a-a826-8246e945ba9b
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebpjzcd5y2o6aprryo6tei3lsnfcbqec3hdqukqxkr5j6vviqa5hw

**Comment by stcouldlisa** [comment]
checker:manualTrigger

**Comment by stcouldlisa** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebgqkhdc2ktp7cptc64n3qqbfdhqdhlstlymwbmixdaeevfzbuil4 
#### Address 
> f1tzbllzb7nbmswrw4zgn2nnewqd45nj7qp7vajoy
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1jvvltduw35u6inn5tr4nfualyd42bh3vjtylgci
#### Id
> f7c629fb-42fa-4a2a-a826-8246e945ba9b
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebgqkhdc2ktp7cptc64n3qqbfdhqdhlstlymwbmixdaeevfzbuil4

**Comment by Hugh-Top** [comment]
checker:manualTrigger

**Comment by herrehesse** [comment]
checker:manualTrigger

**Comment by Hugh-Top** [comment]
checker:manualTrigger

**Comment by Hugh-Top** [comment]
checker:manualTrigger

**Comment by Hugh-Top** [comment]
checker:manualTrigger
