### ISSUE TITLE
[DataCap Application] <Zhejiang Dahua Technology Co., Ltd> - <Smart agriculture>

### ISSUE THREAD

**Issue by dahuajishu** [filecoin-project/filecoin-plus-large-datasets#1975]
### Data Owner Name

Zhejiang Dahua Technology Co., Ltd

### What is your role related to the dataset

Dataset Owner

### Data Owner Country/Region

China

### Data Owner Industry

Resources, Agriculture & Fisheries

### Website

https://www.dahuatech.com/

### Social Media

```text
https://www.dahuatech.com/
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

700TiB

### On-chain address for first allocation

f1e6q3ss3vd2cobkktyim6qzyaiu4hklf2n5w5yeq

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Zhejiang Dahua Technology Co., Ltd. is the world's leading video-centric intelligent IoT solution provider and operation service provider. Based on the Dahua Think# strategy, the company focuses on the two core businesses of cities and enterprises, firmly adheres to the two major technology strategies of AloT and IoT digital intelligence platform, and comprehensively promotes the digital intelligence upgrade of cities and enterprises around customer needs, creating more value for the digital intelligence transformation of thousands of industries.

In 2022, the company achieved an operating income of 30.565 billion yuan, maintaining a steady development trend. The company now has more than 23,000 employees, of which R&D technicians account for more than 50%. The company invests about 10% of its sales revenue in research and development every year, and is constantly committed to technological innovation, and has established the Advanced Technology Research Institute, Big Data Research Institute, Academia Sinica, Network Security Research Institute and Smart City Research Institute. Relying on the in-depth insight and layout of intelligent IoT, the company continues to explore emerging businesses, extending innovative businesses such as Huacheng, Huarui, Huasense, Huaruijie, Huashi Intelligent Inspection, Huahua, Operating Company, Huayixin, and Huachuang.

Dahua's marketing and service network covers the world, and has established 51 domestic and foreign branches in Asia, North America, South America, Europe, Africa and Oceania, and more than 200 offices in China to provide customers with fast and high-quality services. The company's products and solutions cover 180 countries and regions around the world, widely used in smart city, transportation, people's livelihood, manufacturing, education, energy, finance, environmental protection and other fields, and participated in the Beijing Winter Olympics, China International Import Expo, G20 Hangzhou Summit, Rio Olympic Games, Xiamen BRICS Summit, Shanghai World Expo, Guangzhou Asian Games, Hong Kong-Zhuhai-Macao Bridge and other major engineering projects.

As a national high-tech enterprise, Dahua Co., Ltd. was successfully listed on the A-share market in May 2008 (stock code: 002236), the company has a national postdoctoral scientific research workstation, is a national recognized enterprise technology center, a national innovative pilot enterprise, and now has 38 national scientific research projects. The company has applied for more than 8,000 patents, including more than 390 international patents. From 2008 to 2022, it was listed in the top 100 national software enterprises for 15 consecutive years1; It has been selected as "A&S" "Global Security Top 50" for 16 consecutive years2; won the honors of National Industrial Design Center3, Zhejiang Provincial People's Government Quality Award4, High-quality Development Leading Enterprise 5 and other honors, ranked second in the global intelligent video surveillance market share in the report released by Omdia20216, and is the recommended brand of China's smart city construction7 and the most growing enterprise in the field of intelligent IoT and security ecology8.

Dahua will adhere to the core values of "customer-centric, striver-oriented", practice the mission of "making society safer and life smarter", base itself on the market with excellent quality and service, create more value for customers, and make unremitting efforts to build a safe, intelligent, convenient and efficient society.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
With the rapid development of technology, technological innovation is helping to promote the high-quality development of agriculture. In this picture, the shooting and recording of modern technology is described, and the essence of agroecology is clearer.
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### How do you plan to prepare the dataset

singularity

### Please share a sample of the data

```text
https://pan.baidu.com/s/1QJrDXCHwOIjJBx07oWrUUw 
Extract the code:1k7h
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Monthly

### For how long do you plan to keep this dataset stored on Filecoin

More than 3 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, Europe, Australia (continent), Antarctica

### How will you be distributing your data to storage providers

HTTP or FTP server, Shipping hard drives

### How do you plan to choose storage providers

Slack, Big Data Exchange

### How do you plan to make deals to your storage providers

Boost client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
Where are these data from?
Could you send an email to [filplus-app-review@fil.org](mailto:filplus-app-review@fil.org) with your official domain in order to confirm your identity? Email name should includes the issue id https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1975.
Please share more detailed information about sps you will cooperate with.

**Comment by dahuajishu** [comment]
@Sunnyiscoming 
![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/133093794/eed79897-a75c-4ba5-836b-f5711071d715)

**Comment by Sunnyiscoming** [comment]
Can you provide more data samples and provide their specific data sources?

**Comment by Sunnyiscoming** [comment]
For example, where is these open data being downloaded?

**Comment by dahuajishu** [comment]
@Sunnyiscoming HI
The sample data is as follows：
https://pan.baidu.com/s/1205tI54v7QPfPVDYJKv6tg?pwd=7jo0 
Extract the code: 7jo0
https://pan.baidu.com/s/16ENpaD7FOLrq01MMC3NqCA?pwd=vy24 
Extract the code:  vy24

The data comes from our company's internal storage server, and various departments have collaborated to generate this data, but it has not yet been published in the public dataset. Filecoin will be the first.

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 5PiB

**Expected weekly DataCap usage rate**
> 700TiB

**Client address**
>f1e6q3ss3vd2cobkktyim6qzyaiu4hklf2n5w5yeq

**Comment by zcfil** [comment]
Please list the SPs you are pre-collaborating with and the regions.

**Comment by dahuajishu** [comment]
f0872282 in HK
f0399760 in GuangZhou
f01660795 in ShenZhen
f01877184 in Singapore
Thank you for your reply！

**Comment by Normalnoise** [comment]
@dahuajishu how much data have you prepared?

**Comment by dahuajishu** [comment]
More than 700TiB of data were prepared

**Comment by dahuajishu** [comment]
@Normalnoise 
![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/133093794/780b8f4a-92dd-45a0-9abc-01a3319618fd)

**Comment by Normalnoise** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacectdlkgvcqmq7rrw4ghqt6kk7stbatkavj2b4xrgg2cinifjuwhte 
#### Address 
> f1e6q3ss3vd2cobkktyim6qzyaiu4hklf2n5w5yeq
#### Datacap Allocated
> 256.00TiB
#### Signer Address
> f1c5non5yf35avgcpsqvxu4yj54yyvxorwyjochqq
#### Id
> not found
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacectdlkgvcqmq7rrw4ghqt6kk7stbatkavj2b4xrgg2cinifjuwhte

**Comment by Sunnyiscoming** [comment]
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1990
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/2004

**Comment by dahuajishu** [comment]
？

**Comment by Aaron01230** [comment]
According to the above records, we think this application meet the requirements of FIL Plus and willing to support this round.

**Comment by dahuajishu** [comment]
Thanks

**Comment by Sunnyiscoming** [comment]
checker:manualTrigger

**Comment by dahuajishu** [comment]
checker:manualTrigger

**Comment by dahuajishu** [comment]
checker:manualTrigger

**Comment by Chuangshi1** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaitjymrqllyhiskquxd7bojupp5ghdg6yj5iv335w5kcv5ntl2qw 
#### Address 
> f1e6q3ss3vd2cobkktyim6qzyaiu4hklf2n5w5yeq
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f1mdk7s2vntzm6hu35yuo6vjubtrpfnb2awhgvrri
#### Id
> 18e41313-69c5-4db3-b8bf-c1f6b2b85bb4
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaitjymrqllyhiskquxd7bojupp5ghdg6yj5iv335w5kcv5ntl2qw

**Comment by mikezli** [comment]
The client promises to improve the retrieval success rate, so I support this round for now.

**Comment by mikezli** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecsayvew233tqwm2mfdgf2cjmvj2736vohbfjoipjsdtha5rsn4um 
#### Address 
> f1e6q3ss3vd2cobkktyim6qzyaiu4hklf2n5w5yeq
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f1dnb3uz7sylxk6emti3ififcvu3nlufnnsjui6ea
#### Id
> 18e41313-69c5-4db3-b8bf-c1f6b2b85bb4
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecsayvew233tqwm2mfdgf2cjmvj2736vohbfjoipjsdtha5rsn4um

**Comment by dahuajishu** [comment]
checker:manualTrigger

**Comment by dahuajishu** [comment]
checker:manualTrigger

**Comment by Aaron01230** [comment]
checker:manualTrigger

**Comment by dahuajishu** [comment]
checker:manualTrigger

**Comment by kevzak** [comment]
checker:manualTrigger
