### ISSUE TITLE
[DataCap Application] <Shenzhen Xinghongweiye Technology Co., LTD> - <Medical>

### ISSUE THREAD

**Issue by c12xf** [filecoin-project/filecoin-plus-large-datasets#1976]
### Data Owner Name

Shenzhen Xinghongweiye Technology Co., LTD

### What is your role related to the dataset

Data Preparer

### Data Owner Country/Region

China

### Data Owner Industry

Life Science / Healthcare

### Website

http://www.xinghongwy.com/

### Social Media

```text
http://www.xinghongwy.com/
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

1PiB

### On-chain address for first allocation

f1crxayca7f6krwqleegop23v4ewgwloktybgzdua

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Shenzhen Xinghongweiye Technology  CO., LTD. was established in 2005 with a registered capital of 10 million, which is a wholly-owned subsidiary of HONG KONG SKY TALENT HOLDINGS LIMITED, and its own brand is "Xinghongweiye".

Mainly engaged in cloud storage, application storage (NAS, IP-SAN), server virtualization, HPC, GPU high-performance computing, intelligent medical and other overall solutions. Products are widely used in security, education, government, radio and television, communications, Internet and other industries, based on the server field cooperation planning, and different industry manufacturers to establish long-term partnerships, to promote the formation and development of Xinghong full series of product application industry chain.

With the development of the network era and the increasing demand for data storage, we have launched ultra-large-capacity massive information storage and management solutions, customized corresponding solutions according to the characteristics and needs of different industries, broken through the single fixed mode of traditional storage solutions, and fully exerted the advantages of combining hardware and software research and development.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
With the continuous development of medical technology, modern medical means have far exceeded the traditional methods of diagnosis and treatment.  New technology allows doctors to diagnose conditions more accurately and choose more precise treatments.  For example, precision medicine can make personalized treatment plans based on a patient's genetic information and improve treatment results.  In addition, the application of new technologies such as telemedicine and big data analysis is also improving the quality and efficiency of medical services.
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### How do you plan to prepare the dataset

singularity

### Please share a sample of the data

```text
https://pan.baidu.com/s/1TlQy737FO_P0bvm6-OGOUQ
https://pan.baidu.com/s/1SN0O5n07U-XWMlgigzYtbA
https://pan.baidu.com/s/10v6-K4M9lpY-vb5TdWqv3A
https://pan.baidu.com/s/1ud7mKJ1yg4kWiH6LcHwktA
      Extract the code ： 1234
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Monthly

### For how long do you plan to keep this dataset stored on Filecoin

More than 3 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, Africa, North America, South America, Europe, Australia (continent), Antarctica

### How will you be distributing your data to storage providers

HTTP or FTP server, Shipping hard drives

### How do you plan to choose storage providers

Slack, Big Data Exchange

### How do you plan to make deals to your storage providers

Boost client, Lotus client, Singularity

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by c12xf** [comment]
Email sent.
The data comes from publicly available medical resources stored on our servers by several cooperative medical institutions in China.
We are currently collaborating with the following five SPs, and other SPs will join in the future：
f02062851
f01836766
f01128206
f01938671
f01859603

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 5PiB

**Expected weekly DataCap usage rate**
> 1PiB

**Client address**
>f1crxayca7f6krwqleegop23v4ewgwloktybgzdua

**Comment by zcfil** [comment]
Found only a small amount of data. Can you provide more data samples?

**Comment by c12xf** [comment]
https://pan.baidu.com/s/1mMWZ06Znbxc_ppcSHhGiiA?pwd=i96g 
captcha：i96g

**Comment by ipollo00** [comment]
Hi @c12xf 
Do you mind telling us more about what kind of dataset would be stored on Filecoin specifically?
Can those data be publicly reviewed by others? where did you generate those data?

**Comment by c12xf** [comment]
@ipollo00 More about some surgical videos，these data are all publicly available,these data come from several medical institutions that cooperate with our company.

**Comment by ipollo00** [comment]
Hi there, It would be better for us to understand the project if you could have more details.

**Comment by c12xf** [comment]
@ipollo00 Hi，These data come from data storage related to this project that other medical institutions have collaborated with our company. These data include surgical videos and other medical videos and images, with the aim of sharing medical resources and allowing industry personnel to learn and progress together. Currently, more than 900T of data has been saved, and this data is growing at a rate of 50-100T per month.

**Comment by ipollo00** [comment]
Sure, will keep following up on sp distribution and whether the data can be retrieved.

**Comment by ipollo00** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceazxck42gamd2tgpht4qagvucdnshobvfdxyywxn7fdfiac5curgs 
#### Address 
> f1crxayca7f6krwqleegop23v4ewgwloktybgzdua
#### Datacap Allocated
> 256.00TiB
#### Signer Address
> f1n5wlrrhoxpkgwij25xrtt7w7g2k3fhbthmdn6ri
#### Id
> daacbe99-6c5b-4736-81c9-636f75e4701d
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceazxck42gamd2tgpht4qagvucdnshobvfdxyywxn7fdfiac5curgs

**Comment by c12xf** [comment]
Thanks

**Comment by Normalnoise** [comment]
@c12xf How much dataset have you prepared? can you give a proof of data size?

**Comment by c12xf** [comment]
@Normalnoise more than 900T of data has been saved
![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/132553355/39fbc0de-55ba-495f-8d90-7e5a5d6a568a)

**Comment by Normalnoise** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaoeaxxs7yo42jikyoaok4f23g27i6n6ax5eg534el37vm53olr6y 
#### Address 
> f1crxayca7f6krwqleegop23v4ewgwloktybgzdua
#### Datacap Allocated
> 256.00TiB
#### Signer Address
> f1c5non5yf35avgcpsqvxu4yj54yyvxorwyjochqq
#### Id
> daacbe99-6c5b-4736-81c9-636f75e4701d
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaoeaxxs7yo42jikyoaok4f23g27i6n6ax5eg534el37vm53olr6y

**Comment by c12xf** [comment]
@Sunnyiscoming Due to the absence of a DC in v3.1, the signature did not arrive. What should I do?
#1989 also

**Comment by simonkim0515** [comment]
## DataCap Allocation requested

#### Multisig Notary address
> f02049625

#### Client address
> f1crxayca7f6krwqleegop23v4ewgwloktybgzdua

#### DataCap allocation requested
> 256TiB

#### Id
> daacbe99-6c5b-4736-81c9-636f75e4701b

**Comment by simonkim0515** [comment]
## DataCap Allocation requested

#### Multisig Notary address
> f02049625

#### Client address
> f1crxayca7f6krwqleegop23v4ewgwloktybgzdua

#### DataCap allocation requested
> 256TiB

#### Id
> daacbe99-6c5b-4736-81c9-636f75e4701b

**Comment by Normalnoise** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb5sudyhsbfv42m6mo6b5mnv3q35gjbyf4jzgfsnqubdlocfcatty 
#### Address 
> f1crxayca7f6krwqleegop23v4ewgwloktybgzdua
#### Datacap Allocated
> 256.00TiB
#### Signer Address
> f1c5non5yf35avgcpsqvxu4yj54yyvxorwyjochqq
#### Id
> daacbe99-6c5b-4736-81c9-636f75e4701b
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb5sudyhsbfv42m6mo6b5mnv3q35gjbyf4jzgfsnqubdlocfcatty

**Comment by zcfil** [comment]
checker:manualTrigger

**Comment by zcfil** [comment]
https://www.tianyancha.com/company/2317912364  KYB is normal!
Looking back at the historical response, it seems very good. I am willing to support the first round and will follow up on the data situation in the future.

**Comment by zcfil** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceafbuuogq4b4ml3icfsj2qvjw6sjfpumjmbgkbbvsb2ztsq7ixvfe 
#### Address 
> f1crxayca7f6krwqleegop23v4ewgwloktybgzdua
#### Datacap Allocated
> 256.00TiB
#### Signer Address
> f1cjzbiy5xd4ehera4wmbz63pd5ku4oo7g52cldga
#### Id
> daacbe99-6c5b-4736-81c9-636f75e4701b
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceafbuuogq4b4ml3icfsj2qvjw6sjfpumjmbgkbbvsb2ztsq7ixvfe

**Comment by psh0691** [comment]
checker:manualTrigger

**Comment by kevzak** [comment]
checker:manualTrigger

**Comment by kevzak** [comment]
checker:manualTrigger

**Comment by kevzak** [comment]
SPs listed in application question from @Sunnyiscoming 
f02062851
f01836766
f01128206
f01938671
f01859603

Geographies listed in application:
Greater China, Asia other than Greater China, Africa, North America, South America, Europe, Australia (continent), Antarctica

The SPs being used here: https://github.com/data-preservation-programs/filplus-checker-assets/blob/main/filecoin-project/filecoin-plus-large-datasets/issues/1976/1688575153242.md
Only two from original list
f01938671
f01859603
CN and HK only

@c12xf can you explain your storage plan and the SP entities involved here a bit more? Thanks

**Comment by c12xf** [comment]
We are actively contacting SPs from other regions and have already contacted SPs from the United States and the United Kingdom. They will be included in the next round of distribution.

**Comment by c12xf** [comment]
checker:manualTrigger
