### ISSUE TITLE
[DataCap Application] End of Term Web Archive Dataset

### ISSUE THREAD

**Issue by leviYao25** [filecoin-project/filecoin-plus-large-datasets#1977]
### Data Owner Name

EOT

### What is your role related to the dataset

Data Preparer

### Data Owner Country/Region

United States

### Data Owner Industry

Government

### Website

https://eotarchive.org/

### Social Media

```text
https://twitter.com/eotarchive
https://github.com/end-of-term
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

1PiB

### On-chain address for first allocation

f1bvwe3ohazst2t64sfhjdfb4mcdxmy2yb6eho3rq

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
I'm a data prepar. For the End of Term 2020, The Library of Congress, University of North Texas Libraries, Internet Archive, Stanford University Libraries, and the U.S. Government Publishing Office (GPO) joined efforts again, this time with new partners Environmental Data & Governance Initiative (EDGI) and the National Archives and Records Administration (NARA), to preserve public United States Government websites at the conclusion of the presidential administration ending January 20, 2021. This web harvest – like its predecessors in 2008, 2012, and 2016 – was intended to document the federal government’s presence on the World Wide Web during the transition of presidential administrations and to enhance the existing collections of the partner institutions. This broad comprehensive crawl of the .gov domain includes as many federal .gov sites as we could find, plus federal content in other domains (such as .mil, .com, and social media content) and FTP’d datasets.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
Web Archive Crawl Data (WARC and ARC formats)
The End of Term Web Archive (EOT) captures and saves U.S. Government websites at the end of presidential administrations. The EOT has thus far preserved websites from administration changes in 2008, 2012, 2016, and 2020.
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### How do you plan to prepare the dataset

lotus, singularity

### Please share a sample of the data

```text
https://registry.opendata.aws/eot-web-archive/
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Sporadic

### For how long do you plan to keep this dataset stored on Filecoin

1.5 to 2 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, Europe

### How will you be distributing your data to storage providers

HTTP or FTP server, Shipping hard drives, Lotus built-in data transfer

### How do you plan to choose storage providers

Slack, Filmine, Big Data Exchange

### If you already have a list of storage providers to work with, fill out their names and provider IDs below

```text
Not yet.
```

### How do you plan to make deals to your storage providers

Lotus client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 5PiB

**Expected weekly DataCap usage rate**
> 1PiB

**Client address**
>f1bvwe3ohazst2t64sfhjdfb4mcdxmy2yb6eho3rq

**Comment by zcfil** [comment]
You can use your official domain name to filplus-app-review@fil.org Send email and copy to reymond.bu@gmail.com To confirm your identity? The email name should include question ID # [1977](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1977)

**Comment by Sunnyiscoming** [comment]
I have not received that.

**Comment by leviYao25** [comment]
@zcfil @Sunnyiscoming Hi, I'm an individual Data Preparer, do you mean that I should use my own email to send this email?

**Comment by RawTechVentures** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebcz72sgtpvb73i5bnprgwewf4bqjblmhe6b6tuj2e34ugqgqyc7e 
#### Address 
> f1bvwe3ohazst2t64sfhjdfb4mcdxmy2yb6eho3rq
#### Datacap Allocated
> 256.00TiB
#### Signer Address
> f1txfsjmix4vlzido4dkildrnbw26owtlbslexmpa
#### Id
> df1a8f1f-138f-4a55-9c27-6c1f9e0d92fe
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebcz72sgtpvb73i5bnprgwewf4bqjblmhe6b6tuj2e34ugqgqyc7e

**Comment by 1475Notary** [comment]
Have received DM from this applicant and verified data samples, allocation plan. We would like to offer support for the first round.

**Comment by 1475Notary** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaprar6tevaq2whdfqbojnojsh5pgjexspmxs2654p3raobl7vjgc 
#### Address 
> f1bvwe3ohazst2t64sfhjdfb4mcdxmy2yb6eho3rq
#### Datacap Allocated
> 256.00TiB
#### Signer Address
> f1ofq4mngy7ggcp755pfquq2gphjjnlydolf6awtq
#### Id
> df1a8f1f-138f-4a55-9c27-6c1f9e0d92fe
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaprar6tevaq2whdfqbojnojsh5pgjexspmxs2654p3raobl7vjgc

**Comment by Sunnyiscoming** [comment]
checker:manualTrigger

**Comment by Sunnyiscoming** [comment]
Any update here?

**Comment by leviYao25** [comment]
@Sunnyiscoming Hi Sunny, we'll get ready soon.

**Comment by leviYao25** [comment]
ACK

**Comment by cryptowhizzard** [comment]
checker:manualTrigger

**Comment by leviYao25** [comment]
checker:manualTrigger

**Comment by leviYao25** [comment]
checker:manualTrigger

**Comment by raghavrmadya** [comment]
Extremely poor report. Flagged for DC removal by T&T WG based on the dispute on the tracker - https://www.notion.so/filecoin/T-T-Dispute-Tracker-d28b93677cb544b48e77b585856601cf
