### ISSUE TITLE
[DataCap Application] <NFTEra> - <NFTEra>

### ISSUE THREAD

**Issue by NFTEraOfficial** [filecoin-project/filecoin-plus-large-datasets#1986]
### Data Owner Name

NFTEra

### What is your role related to the dataset

Dataset Owner

### Data Owner Country/Region

China

### Data Owner Industry

IT & Technology Services

### Website

bytepic.cn

### Social Media

```text
https://www.xiaohongshu.com/user/profile/60e94a380000000001005f4d?xhsshare=CopyLink&appuid=6166fbac000000001f03daae&apptime=1683753451
WeChat public Account ID: gh_47838b022894
```

### Total amount of DataCap being requested

7PiB

### Weekly allocation of DataCap requested

500TiB

### On-chain address for first allocation

f1hjiip3jr6u4a5wgrktfyvgtqrmf3xyxbhpcvbki

### Data Type of Application

Public, Open Commercial/Enterprise

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
We are a company that makes a platform for the nature of digital collections and also provides the function of AI painting. NFT Era relies on Wuhan University's Institute of Artificial Intelligence, the director of the algorithm has been selected for the Huawei Genius Junior Program, the enterprise is listed in the Wuhan Science and Technology Enterprise and Wuhan Key Industry Development Plan, access to the largest compliant public chain in China, the tree map chain, and the cooperation with Conflux, which is valued at over 10 billion dollars, to create a The world on a chain. NFT Era is committed to combining technology and art, hoping to collide new patterns in the field of digital collections and AI art!
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
We will store a certain number of artwork images, as well as images generated by AI painting.
```

### Where was the data currently stored in this dataset sourced from

Other

### If you answered "Other" in the previous question, enter the details here

```text
Ali cloud server
```

### Please share a sample of the data

```text
https://imgloc.com/i/iYhImp
https://imgloc.com/i/iYhNvU
https://imgloc.com/i/iYh3yv
https://imgloc.com/i/iYhRI3
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Daily

### For how long do you plan to keep this dataset stored on Filecoin

Less than 1 year

### In which geographies do you plan on making storage deals

Asia other than Greater China

### How will you be distributing your data to storage providers

HTTP or FTP server

### How do you plan to choose storage providers

I don't know yet

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/105098820/4f53171e-2189-4a3f-8e60-136af6970ab7)
Can you provide more data samples to prove that you have 7 PB data?
Could you send an email to filplus-app-review@fil.org with your official domain in order to confirm your identity? Email name should includes the issue id #1986.

**Comment by Sunnyiscoming** [comment]
Any update here?

**Comment by Sunnyiscoming** [comment]
Any update here?

**Comment by Sunnyiscoming** [comment]
Close for no reply.
