### ISSUE TITLE
[DataCap Application] SETI Institute

### ISSUE THREAD

**Issue by PiKNiK-Company** [filecoin-project/filecoin-plus-large-datasets#1987]
### Data Owner Name
SETI Institute

### What is your role related to the dataset
Storage provider filling out application on behalf of the data owner

### Data Owner Country/Region
United States

### Data Owner Industry
Not-for-Profit

### Website
[http://laserseti.net](http://laserseti.net)

### Social Media
[at]LaserSeti (Twitter)

### Total amount of DataCap being requested
1.5 PiB

### Weekly allocation of DataCap requested
100 TiB

### On-chain address for first allocation
f125bjsx3drj33mdvosj7c2poyfu37fl5npkb5vga

### Data Type of Application
Public, Open Dataset (Research/Non-Profit)

### Custom multisig
No

### Share a brief history of your project and organization
LaserSETI is the first optical SETI survey designed to cover all the sky all-the-time. The SETI Institute is a non-profit research and education organization dedicated to understanding the nature and prevalence of life in the universe.

### Is this project associated with other projects/ecosystem stakeholders?
Yes

### If answered yes, what are the other projects/ecosystem stakeholders
Nothing formally. The SETI field isn't a huge one, and there's some potential collaborations with other SETI projects that may materialize.

### Describe the data being stored onto Filecoin
Raw observational data from LaserSETI instruments. A small fraction is traditional coherent full frame imaging, most is our specialized 1 kHz readout, which smears the image in one axis.

### Where was the data currently stored in this dataset sourced from
My own storage infra

### If you answered "Other" in the previous question, enter the details here
null

### How do you plan to prepare the dataset
singularity

### If you answered "other/custom tool" in the previous question, enter the details here
null

### Please share a sample of the data
https://ws-cam-bucket.s3.us-west-1.amazonaws.com/CanViz/RFO1PC_horz-cam_2022-03-22T05-41-55.673.tdi_3934_5394.png

### Confirm that this is a public dataset that can be retrieved by anyone on the Network
Yes

### If you chose not to confirm, what was the reason
null

### What is the expected retrieval frequency for this data
Sporadic

### For how long do you plan to keep this dataset stored on Filecoin
More than 3 years

### In which geographies do you plan on making storage deals
North America

### How will you be distributing your data to storage providers
Lotus built-in data transfer

### How do you plan to choose SP
Partners

### If you answered "Others" in the previous question, what is the tool or platform you plan to use
null

### How do you plan to make deals to your storage providers
Boost client

### If you answered "Others/custom tool" in the previous question, enter the details here
null

### Can you confirm that you will follow the Fil+ guideline
Yes

_Application created via [filplus.storage](https://filplus.storage)_

**Comment by Sunnyiscoming** [comment]
Could you send an email to filplus-app-review@fil.org with your official domain in order to confirm your identity? Email name should includes the issue id #1987.
Can you introduce your organizaion?
Please share more detailed information about sps you will cooperate with.

**Comment by Sunnyiscoming** [comment]
Close for no reply.
