### ISSUE TITLE
[DataCap Application] NOAA National Blend of Models (NBM)

### ISSUE THREAD

**Issue by Colinan77** [filecoin-project/filecoin-plus-large-datasets#1988]
### Data Owner Name

NOAA

### What is your role related to the dataset

Data Preparer

### Data Owner Country/Region

United States

### Data Owner Industry

Environment

### Website

https://vlab.noaa.gov/web/mdl/nbm

### Social Media

```text
https://twitter.com/NOAA
https://www.facebook.com/NOAA
https://www.instagram.com/noaa/
https://www.youtube.com/usnoaagov
```

### Total amount of DataCap being requested

15PiB

### Weekly allocation of DataCap requested

1PiB

### On-chain address for first allocation

f1dww5end2qeavsqhh5epni4b64p3xui2343sp3ca

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
The National Blend of Models (NBM) is a nationally consistent and skillful suite of calibrated forecast guidance based on a blend of both NWS and non-NWS numerical weather prediction model data and post-processed model guidance. The goal of the NBM is to create a highly accurate, skillful and consistent starting point for the gridded forecast.
I'm a DP who used to participate in slingshot, Hackathon. Now I want to use this data for distributed storage.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
National Blend of Models (NBM) COG Format; National Blend of Models (NBM) Grib2 Format
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### How do you plan to prepare the dataset

IPFS, lotus, singularity, I don't know yet

### Please share a sample of the data

```text
https://registry.opendata.aws/noaa-nbm/
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Sporadic

### For how long do you plan to keep this dataset stored on Filecoin

More than 3 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, South America, Europe

### How will you be distributing your data to storage providers

Cloud storage (i.e. S3), HTTP or FTP server, Shipping hard drives, Lotus built-in data transfer, I don't know yet

### How do you plan to choose storage providers

Slack, Big Data Exchange, Partners, I don't know yet

### If you already have a list of storage providers to work with, fill out their names and provider IDs below

```text
I'm communicating with sps for my deals.
```

### How do you plan to make deals to your storage providers

Boost client, Lotus client, Singularity

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
Can you list SPs you are communicating with?
How much data are in this dataset? How many copies will you store?

**Comment by Colinan77** [comment]
Hello @Sunnyiscoming , I have communicated with f01609310, f01851450. I will go on looking for more sps to ensure distributing. The dataset I use to apply is 1083.7TiB and plan to store 10 copies in total. Considering car padding or other unknown factors, I applied for this amount of datacap. Hope you can approve my application.

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 15PiB

**Expected weekly DataCap usage rate**
> 1PiB

**Client address**
>f1dww5end2qeavsqhh5epni4b64p3xui2343sp3ca

**Comment by Meibuy** [comment]
The applicant reached me on Slack and willing to support its first allocation.

**Comment by Meibuy** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceadompluylqy4726xfp4afkl5yc52eryehtinmosq6mkfomz5lqc6 
#### Address 
> f1dww5end2qeavsqhh5epni4b64p3xui2343sp3ca
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f1bwugfihrmn3iyunzyxst5nttql3dge4khwmurtq
#### Id
> eb9fe6ad-7aff-4fd8-aa91-302bc813ef97
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceadompluylqy4726xfp4afkl5yc52eryehtinmosq6mkfomz5lqc6

**Comment by AthSmith** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecn5umd2egjwxghbtdzedamkr5xv636imgvpks24vhwt2vojd7oku 
#### Address 
> f1dww5end2qeavsqhh5epni4b64p3xui2343sp3ca
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f1vxbqrf7rfum3n6m5u6eb4re6xj7amvsaqnzu64y
#### Id
> eb9fe6ad-7aff-4fd8-aa91-302bc813ef97
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecn5umd2egjwxghbtdzedamkr5xv636imgvpks24vhwt2vojd7oku

**Comment by AthSmith** [comment]
The client contacted me by slack and shared the storage plan. I'd like to see more public data joining the network!

**Comment by Sunnyiscoming** [comment]
checker:manualTrigger

**Comment by Colinan77** [comment]
I want to keep my application open. Thanks!

**Comment by spaceT9** [comment]
checker:manualTrigger

**Comment by spaceT9** [comment]
You need to improve retrieval rate before next tranche

**Comment by Colinan77** [comment]
@spaceT9 Thanks for your reminder! We've already communicated with sp and they have improved on it. 
![asdd](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/130634004/b502d13d-ead0-4a95-8fae-4c44e26f6cf6)
I don't know why the report still shows rate 0.

**Comment by xmcai2016** [comment]
The report needs a few days to show the increase in scores because it takes the average of retrieval data in the past few months since Retrieval Bot was launched. We are working on a self-serving portal to let you monitor real-time retrieval data. Stay tuned for updates on the release of the monitor dashboard.

**Comment by Colinan77** [comment]
@xmcai2016 Thank you for your hardwork!

**Comment by cryptowhizzard** [comment]
checker:manualTrigger

**Comment by cryptowhizzard** [comment]
The report indicates 0 because your speed is less then a 56K6 modem.

Can you explain why the retrieval speed has been set extremely low so no-one can download anything to do due dilligence?

**Comment by Wengeding** [comment]
@xmcai2016 We also find that the self-serving portal isn't real-time, Could you help to fix it?
Of course we know that cross-country links are really complicated and we often experience download interruptions.

**Comment by Destore2023** [comment]
have talked with the applicant just now. Overall this application is genuine and credible. Looking forward to the new report once the retrieved data is updated.

**Comment by Destore2023** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedn4zyixugzu4kc2zbxlrkxrn6hcldjdbpd7dyck3zalehrc5qbbm 
#### Address 
> f1dww5end2qeavsqhh5epni4b64p3xui2343sp3ca
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f1yh6q3nmsg7i2sys7f7dexcuajgoweudcqj2chfi
#### Id
> 9f67f61a-b3fd-4425-bb15-6e4929782593
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedn4zyixugzu4kc2zbxlrkxrn6hcldjdbpd7dyck3zalehrc5qbbm

**Comment by herrehesse** [comment]
Actively under due diligence while signed by @Destore2023 and @Wengeding.

@raghavrmadya @Kevin-FF-USA @dkkapur, I urge you to take immediate action to close and remove this content. This behavior is precisely what we are fighting against here - collusion and a complete disregard for rules. Please address this promptly.

**Comment by Destore2023** [comment]
Well done!

**Comment by cryptowhizzard** [comment]
> Well done!

https://filecoinproject.slack.com/archives/C0405HANNBT/p1690475040542719

Thank you.

**Comment by kevzak** [comment]
checker:manualTrigger

**Comment by raghavrmadya** [comment]
This application has raised T&T flags based on the error in the retrieval bot. Notaries kindly assess retrieval situation prior to singing further tranches

**Comment by Colinan77** [comment]
Didn't find anything unusual, maybe some differences in some distant countries' network. 

<img width="1405" alt="d69263228e483e47c4514a5726e7d77" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/130634004/55b64981-1efe-4ec6-99ae-28b3b03af39f">

**Comment by cryptowhizzard** [comment]
Hi,

I notice that you are working with SP's who are heavily involved in CID sharing ( AT1 ) and with SP's who have retrieval disabled (AT3).

What is the reason for it?

![Scherm­afbeelding 2023-07-28 om 13 44 30](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/36404435/d0682232-a216-4a41-a1ec-2bf79f634cea)

**Comment by Colinan77** [comment]
> Hi,
> 
> I notice that you are working with SP's who are heavily involved in CID sharing ( AT1 ) and with SP's who have retrieval disabled (AT3).
> 
> What is the reason for it?
> 
> ![Scherm­afbeelding 2023-07-28 om 13 44 30](https://user-images.githubusercontent.com/36404435/256812954-d0682232-a216-4a41-a1ec-2bf79f634cea.png)

It can be retrieved. 
I have no connection to Sp's work with the others. It's not my business to explain.
![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/130634004/1939c9ac-3089-43c0-8e53-3ba4ebe73299)

**Comment by Colinan77** [comment]
<img width="1432" alt="7a8255cf441efde5b79297f7dd6bec4" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/130634004/6a18bb3d-d0da-4064-966d-9aca7300a78a">
We've informed SPs of the retrieval rules. believe that most of them have already done the upgrade.

**Comment by Wengeding** [comment]
checker:manualTrigger

**Comment by clriesco** [comment]
Removed stale label and reopened issue :)

**Comment by kevzak** [comment]
checker:manualTrigger

**Comment by kevzak** [comment]
83.30% of deals are for data replicated across less than 4 storage providers. Need to be using at least 4 SP Entities. Closing until client displays a better distribution

**Comment by cryptowhizzard** [comment]
![Scherm­afbeelding 2023-08-31 om 15 06 04](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/36404435/4557800e-403f-480b-b953-5df2658adecf)

Hello!

Seems you have been storing some very artistic, non-compliant data, however it is not what you promised to store.

I made the retrieved data available for download here:
http://www.datasetcreators.com/downloadedcarfiles/httpretrievals/1988-f02204320-f02029743-48924040-baga6ea4seaqaqjvcfbbp4zdzdv3iq6tjrserssudd373fyah6qoaecilysiqsfq

For those who wish to check on the Linux command prompt:

hexdump -C 1988-f02204320-f02029743-48924040-baga6ea4seaqaqjvcfbbp4zdzdv3iq6tjrserssudd373fyah6qoaecilysiqsfq | more 

![Scherm­afbeelding 2023-08-31 om 15 09 41](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/36404435/57ff5bde-91b8-4d91-b0ab-591457a85ab3)

**Comment by raghavrmadya** [comment]
The concerns on deal replication and inconsistent retrieval samples have been ignored by the client and signing notaries. Such behavior is unacceptable. As a representative of T&T WG, this application is being flagged for DC removal.
