### ISSUE TITLE
[DataCap Application] <Shenzhen Xinghongweiye Technology Co., LTD> - <Technological Agriculture>

### ISSUE THREAD

**Issue by c12xf** [filecoin-project/filecoin-plus-large-datasets#1989]
### Data Owner Name

Shenzhen Xinghongweiye Technology Co., LTD

### What is your role related to the dataset

Dataset Owner

### Data Owner Country/Region

China

### Data Owner Industry

Resources, Agriculture & Fisheries

### Website

http://www.xinghongwy.com/

### Social Media

```text
http://www.xinghongwy.com/
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

1PiB

### On-chain address for first allocation

f1u2ku5l7qv3rzvv4j5m7zdk5aehe5pzmdvzpynfy

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Shenzhen Xinghongweiye Technology  CO., LTD. was established in 2005 with a registered capital of 10 million, which is a wholly-owned subsidiary of HONG KONG SKY TALENT HOLDINGS LIMITED, and its own brand is "Xinghongweiye".

Mainly engaged in cloud storage, application storage (NAS, IP-SAN), server virtualization, HPC, GPU high-performance computing, intelligent medical and other overall solutions. Products are widely used in security, education, government, radio and television, communications, Internet and other industries, based on the server field cooperation planning, and different industry manufacturers to establish long-term partnerships, to promote the formation and development of Xinghong full series of product application industry chain.

With the development of the network era and the increasing demand for data storage, we have launched ultra-large-capacity massive information storage and management solutions, customized corresponding solutions according to the characteristics and needs of different industries, broken through the single fixed mode of traditional storage solutions, and fully exerted the advantages of combining hardware and software research and development.
```

### Is this project associated with other projects/ecosystem stakeholders?

Yes

### Describe the data being stored onto Filecoin

```text
The agriculture industry has been constantly developing and changing. In the past few decades, agricultural production methods and technologies have been greatly improved, and the yield and efficiency of agriculture have also significantly increased. At the same time, agriculture has also been affected by environmental and social changes, and more and more people are paying attention to the development of sustainable agriculture. Agricultural production methods are also improving in a more environmentally friendly and sustainable direction. With the continuous progress of technology, new technologies such as artificial intelligence and big data have also been applied to agricultural production, making the agricultural industry more efficient, intelligent, and modern.
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### How do you plan to prepare the dataset

singularity

### Please share a sample of the data

```text
https://pan.baidu.com/s/1hSFjhvhKCm84oI6QKk324Q
https://pan.baidu.com/s/1H_AS49pjhP2LB_iIschQkw
         Extract the code ： 8888
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Monthly

### For how long do you plan to keep this dataset stored on Filecoin

More than 3 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, Africa, North America, South America, Europe, Australia (continent), Antarctica

### How will you be distributing your data to storage providers

HTTP or FTP server, Shipping hard drives

### How do you plan to choose storage providers

Slack, Big Data Exchange

### If you already have a list of storage providers to work with, fill out their names and provider IDs below

```text
f02062851 
f01836766 
f01128206 
f01938671
f01859603
```

### How do you plan to make deals to your storage providers

Boost client, Lotus client, Singularity

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1976

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 5PiB

**Expected weekly DataCap usage rate**
> 1PiB

**Client address**
>f1u2ku5l7qv3rzvv4j5m7zdk5aehe5pzmdvzpynfy

**Comment by zcfil** [comment]
Found only a small amount of data. Can you provide more data samples?

**Comment by c12xf** [comment]
https://pan.baidu.com/s/1tPGfZSxZ6V2yg39UEJGxqg?pwd=dfxk

**Comment by ipollo00** [comment]
@c12xf Agriculture data do important for humans. However, please be specific about where the data is generated from.

**Comment by c12xf** [comment]
@ipollo00 The data comes from some data generated by agricultural projects that other companies have collaborated with our company.

**Comment by ipollo00** [comment]
Hi there, It would be better for us to understand the project if you could have more details.

**Comment by c12xf** [comment]
@ipollo00  Hi，These data come from data storage related to this project that other companies dedicated to smart agriculture have collaborated with our company. These data include monitoring, monitoring, and recording information on various stages of plant and biological aspects; Currently, over 600T of data has been saved, and this data is growing at a rate of 100-200T per month.

**Comment by ipollo00** [comment]
Sure, will keep following up on sp distribution and whether the data can be retrieved.

**Comment by ipollo00** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebolxlessh67t4cyfdm34gnokeez7bfg2xrtsvc66cvzlex57i6cw 
#### Address 
> f1u2ku5l7qv3rzvv4j5m7zdk5aehe5pzmdvzpynfy
#### Datacap Allocated
> 256.00TiB
#### Signer Address
> f1n5wlrrhoxpkgwij25xrtt7w7g2k3fhbthmdn6ri
#### Id
> c5258779-e86b-4795-bb03-8a134a804ec4
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebolxlessh67t4cyfdm34gnokeez7bfg2xrtsvc66cvzlex57i6cw

**Comment by c12xf** [comment]
Thanks

**Comment by Normalnoise** [comment]
@c12xf How many datasets have you prepared? can you give proof of data size?

**Comment by c12xf** [comment]
![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/132553355/26ad677f-e77f-4a0d-a63a-a5b65b37b538)
over 600T of data has been saved.

**Comment by Normalnoise** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecw3rxtpk3bvira3c26g5xzxy7bnuelmof5y5uza2igucpssfnt64 
#### Address 
> f1u2ku5l7qv3rzvv4j5m7zdk5aehe5pzmdvzpynfy
#### Datacap Allocated
> 256.00TiB
#### Signer Address
> f1c5non5yf35avgcpsqvxu4yj54yyvxorwyjochqq
#### Id
> c5258779-e86b-4795-bb03-8a134a804ec4
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecw3rxtpk3bvira3c26g5xzxy7bnuelmof5y5uza2igucpssfnt64

**Comment by simonkim0515** [comment]
## DataCap Allocation requested

#### Multisig Notary address
> f02049625

#### Client address
> f1u2ku5l7qv3rzvv4j5m7zdk5aehe5pzmdvzpynfy

#### DataCap allocation requested
> 256TiB

#### Id
> c5258779-e86b-4795-bb03-8a134a804ec5

**Comment by c12xf** [comment]
@Normalnoise  @ipollo00 Previously, due to the absence of a DC in v3.1, the signature did not arrive. Could you please help me sign again? Thank you，and #1976

**Comment by Normalnoise** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceallv2zc2zblvbcudujwxxwakusx4itoua425y5vhdl4677bmbpk6 
#### Address 
> f1u2ku5l7qv3rzvv4j5m7zdk5aehe5pzmdvzpynfy
#### Datacap Allocated
> 256.00TiB
#### Signer Address
> f1c5non5yf35avgcpsqvxu4yj54yyvxorwyjochqq
#### Id
> c5258779-e86b-4795-bb03-8a134a804ec5
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceallv2zc2zblvbcudujwxxwakusx4itoua425y5vhdl4677bmbpk6

**Comment by zcfil** [comment]
checker:manualTrigger

**Comment by zcfil** [comment]
https://www.tianyancha.com/company/2317912364  KYB is normal!
Looking back at the historical response, it seems very good. I am willing to support the first round and will follow up on the data situation in the future.

**Comment by zcfil** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecujftalvbv6eevnl2zrcfa7v2yvox3col5aoe7khfkkjlitqvap6 
#### Address 
> f1u2ku5l7qv3rzvv4j5m7zdk5aehe5pzmdvzpynfy
#### Datacap Allocated
> 256.00TiB
#### Signer Address
> f1cjzbiy5xd4ehera4wmbz63pd5ku4oo7g52cldga
#### Id
> c5258779-e86b-4795-bb03-8a134a804ec5
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecujftalvbv6eevnl2zrcfa7v2yvox3col5aoe7khfkkjlitqvap6

**Comment by herrehesse** [comment]
checker:manualTrigger

**Comment by 1ane-1** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedktljglmjbe7jjbzypasbwnkpmyvf3hsyutxkwgoortopdrycqhk 
#### Address 
> f1u2ku5l7qv3rzvv4j5m7zdk5aehe5pzmdvzpynfy
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f1mdk7s2vntzm6hu35yuo6vjubtrpfnb2awhgvrri
#### Id
> 7491fa66-ef83-4929-a757-985ade0a613f
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedktljglmjbe7jjbzypasbwnkpmyvf3hsyutxkwgoortopdrycqhk

**Comment by stcouldlisa** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceajryhm23o4wpp5nt4povwg2mmqkekyotd4rkgbrwgzjkn33qtnmo 
#### Address 
> f1u2ku5l7qv3rzvv4j5m7zdk5aehe5pzmdvzpynfy
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f1jvvltduw35u6inn5tr4nfualyd42bh3vjtylgci
#### Id
> 7491fa66-ef83-4929-a757-985ade0a613f
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceajryhm23o4wpp5nt4povwg2mmqkekyotd4rkgbrwgzjkn33qtnmo

**Comment by c12xf** [comment]
checker:manualTrigger

**Comment by Aaron01230** [comment]
checker:manualTrigger

**Comment by Aaron01230** [comment]
The client contacted me and explain the reason of low retrieval success rate . They promised to improve the retrieval success rate. I am willing to support this round and check the retrieval rate later.

**Comment by Aaron01230** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedxl6p7kw5meil3us64gylb3xe5micqpz3mvffzai542qszuytnze 
#### Address 
> f1u2ku5l7qv3rzvv4j5m7zdk5aehe5pzmdvzpynfy
#### Datacap Allocated
> 1.00PiB
#### Signer Address
> f1xrnysd4gimg64d4l6qi7ulzwwq22c6vfg6lpw3i
#### Id
> 67b47892-6398-41a4-949b-83427972ec68
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedxl6p7kw5meil3us64gylb3xe5micqpz3mvffzai542qszuytnze

**Comment by Aaron01230** [comment]
Why is the retrieval rate so low?

**Comment by c12xf** [comment]
checker:manualTrigger

**Comment by c12xf** [comment]
> @ipollo00 The data comes from some data generated by agricultural projects that other companies have collaborated with our company.

As I mentioned before, our data is generated through collaboration with other companies, and Dahua Company is one of them. Just after conducting an investigation with Dahua's technical personnel responsible for agricultural projects, it was found that we have several 8T data disks with the same data as Dahua's, which led to CID sharing. Through our company's business personnel, we learned that the data in these disks was stored on our company's servers a few years ago, Currently, Dahua Company has abandoned this data, so the sharing of cid will not increase in subsequent allocations.

**Comment by cryptowhizzard** [comment]
checker:manualTrigger
