### ISSUE TITLE
[DataCap Application] <Zhejiang Dahua Technology Co., Ltd> - <Architectural design>

### ISSUE THREAD

**Issue by dahuajishu** [filecoin-project/filecoin-plus-large-datasets#1990]
### Data Owner Name

Zhejiang Dahua Technology Co., Ltd

### What is your role related to the dataset

Dataset Owner

### Data Owner Country/Region

China

### Data Owner Industry

Construction, Property & Real Estate

### Website

https://www.dahuatech.com/

### Social Media

```text
https://www.dahuatech.com/
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

900TiB

### On-chain address for first allocation

f1d7satpgjskky5npn6efotbctqo2u754lubu4omq

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Zhejiang Dahua Technology Co., Ltd. is the world's leading video-centric intelligent IoT solution provider and operation service provider. Based on the Dahua Think# strategy, the company focuses on the two core businesses of cities and enterprises, firmly adheres to the two major technology strategies of AloT and IoT digital intelligence platform, and comprehensively promotes the digital intelligence upgrade of cities and enterprises around customer needs, creating more value for the digital intelligence transformation of thousands of industries.

In 2022, the company achieved an operating income of 30.565 billion yuan, maintaining a steady development trend. The company now has more than 23,000 employees, of which R&D technicians account for more than 50%. The company invests about 10% of its sales revenue in research and development every year, and is constantly committed to technological innovation, and has established the Advanced Technology Research Institute, Big Data Research Institute, Academia Sinica, Network Security Research Institute and Smart City Research Institute. Relying on the in-depth insight and layout of intelligent IoT, the company continues to explore emerging businesses, extending innovative businesses such as Huacheng, Huarui, Huasense, Huaruijie, Huashi Intelligent Inspection, Huahua, Operating Company, Huayixin, and Huachuang.

Dahua's marketing and service network covers the world, and has established 51 domestic and foreign branches in Asia, North America, South America, Europe, Africa and Oceania, and more than 200 offices in China to provide customers with fast and high-quality services. The company's products and solutions cover 180 countries and regions around the world, widely used in smart city, transportation, people's livelihood, manufacturing, education, energy, finance, environmental protection and other fields, and participated in the Beijing Winter Olympics, China International Import Expo, G20 Hangzhou Summit, Rio Olympic Games, Xiamen BRICS Summit, Shanghai World Expo, Guangzhou Asian Games, Hong Kong-Zhuhai-Macao Bridge and other major engineering projects.

As a national high-tech enterprise, Dahua Co., Ltd. was successfully listed on the A-share market in May 2008 (stock code: 002236), the company has a national postdoctoral scientific research workstation, is a national recognized enterprise technology center, a national innovative pilot enterprise, and now has 38 national scientific research projects. The company has applied for more than 8,000 patents, including more than 390 international patents. From 2008 to 2022, it was listed in the top 100 national software enterprises for 15 consecutive years1; It has been selected as "A&S" "Global Security Top 50" for 16 consecutive years2; won the honors of National Industrial Design Center3, Zhejiang Provincial People's Government Quality Award4, High-quality Development Leading Enterprise 5 and other honors, ranked second in the global intelligent video surveillance market share in the report released by Omdia20216, and is the recommended brand of China's smart city construction7 and the most growing enterprise in the field of intelligent IoT and security ecology8.

Dahua will adhere to the core values of "customer-centric, striver-oriented", practice the mission of "making society safer and life smarter", base itself on the market with excellent quality and service, create more value for customers, and make unremitting efforts to build a safe, intelligent, convenient and efficient society.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
Architectural design drawings, building beautiful houses to live comfortably safely, design the love nest in mind
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### How do you plan to prepare the dataset

singularity

### Please share a sample of the data

```text
https://pan.baidu.com/s/1OEDx89PH_YRmLW35cU7AEw?pwd=zuio
Extract the code:zuio
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Monthly

### For how long do you plan to keep this dataset stored on Filecoin

More than 3 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, Europe, Australia (continent), Antarctica

### How will you be distributing your data to storage providers

HTTP or FTP server, Shipping hard drives

### How do you plan to choose storage providers

Slack, Big Data Exchange

### How do you plan to make deals to your storage providers

Boost client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
The previous issue: https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1975
Where are these data from?
Please share more detailed information about sps you will cooperate with.

**Comment by dahuajishu** [comment]
@Sunnyiscoming Hi，
The data comes from our company's internal storage server
f0872282 in HK
f0399760 in GuangZhou
f01660795 in ShenZhen
f01877184 in Singapore
Thank you for your reply！

**Comment by Sunnyiscoming** [comment]
Maybe my words are not clear enough. What I mean is which companies or projects the data come from. Can you provide more information and materials to prove that. 5PB data is too much.

**Comment by dahuajishu** [comment]
@Sunnyiscoming These data come from our company and its subsidiaries. You can view the company details according to this [link](https://www.tianyancha.com/company/4607820), which is also considered one of the materials

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 5PiB

**Expected weekly DataCap usage rate**
> 900TiB

**Client address**
>f1d7satpgjskky5npn6efotbctqo2u754lubu4omq

**Comment by dahuajishu** [comment]
Thank you

**Comment by woshidama323** [comment]
LGTM,  Will support to this application

**Comment by woshidama323** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacea7pkrtrtvwj26zk5bwcgg6fko6tqm27jhziocktn5af2rotf4vy2 
#### Address 
> f1d7satpgjskky5npn6efotbctqo2u754lubu4omq
#### Datacap Allocated
> 256.00TiB
#### Signer Address
> f12tk3adljauwnd3hjbigpfxb7b7gdlj63p6afwtq
#### Id
> f55e68d0-c49e-4613-8369-2761b80f5359
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacea7pkrtrtvwj26zk5bwcgg6fko6tqm27jhziocktn5af2rotf4vy2

**Comment by zcfil** [comment]
I have reviewed historical information and am willing to provide support in the first round, and will follow up on the data situation in the later stage.

**Comment by zcfil** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacearrml4mdrjimznb2gkb6t5rswbyuq4hvduafjbihmoie6o7wyhuq 
#### Address 
> f1d7satpgjskky5npn6efotbctqo2u754lubu4omq
#### Datacap Allocated
> 256.00TiB
#### Signer Address
> f1cjzbiy5xd4ehera4wmbz63pd5ku4oo7g52cldga
#### Id
> f55e68d0-c49e-4613-8369-2761b80f5359
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacearrml4mdrjimznb2gkb6t5rswbyuq4hvduafjbihmoie6o7wyhuq

**Comment by Sunnyiscoming** [comment]
checker:manualTrigger

**Comment by spaceT9** [comment]
Given the good CID report status, I will sign the second round.  
You are very  responsive in #2034. If the first part goes well, then I will sign 2034 later.

**Comment by dahuajishu** [comment]
checker:manualTrigger

**Comment by ipollo00** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb7qrfqf6g3ioiuelgsetz7de3ae6omtmynh7bzsji2556ut6k3qk 
#### Address 
> f1d7satpgjskky5npn6efotbctqo2u754lubu4omq
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f1n5wlrrhoxpkgwij25xrtt7w7g2k3fhbthmdn6ri
#### Id
> 328bd58b-4fb4-43b9-93df-dce64bea18bb
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb7qrfqf6g3ioiuelgsetz7de3ae6omtmynh7bzsji2556ut6k3qk

**Comment by 1ane-1** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaeqmw65kjtxjcoa4ff5tdtfofj5s6vfwk7rsyf5rth4cjsyhxuy4 
#### Address 
> f1d7satpgjskky5npn6efotbctqo2u754lubu4omq
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f1mdk7s2vntzm6hu35yuo6vjubtrpfnb2awhgvrri
#### Id
> 328bd58b-4fb4-43b9-93df-dce64bea18bb
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaeqmw65kjtxjcoa4ff5tdtfofj5s6vfwk7rsyf5rth4cjsyhxuy4

**Comment by dahuajishu** [comment]
checker:manualTrigger

**Comment by dahuajishu** [comment]
checker:manualTrigger

**Comment by NDLABS-OFFICE** [comment]
From the report looks very good, willing to support

**Comment by dahuajishu** [comment]
checker:manualTrigger

**Comment by kevzak** [comment]
checker:manualTrigger

**Comment by kevzak** [comment]
SPs listed in application:
f0872282 in HK
f0399760 in GuangZhou
f01660795 in ShenZhen
f01877184 in Singapore

SP areas listed in application:
Greater China, Asia other than Greater China, North America, Europe, Australia (continent), Antarctica

SPs in use:
https://github.com/data-preservation-programs/filplus-checker-assets/blob/main/filecoin-project/filecoin-plus-large-datasets/issues/1990/1688575150083.md

Can you tell us more about the SP entities involved here?

**Comment by dahuajishu** [comment]
The listed SPs have not been able to reach a cooperation agreement with us due to certain issues.
So we have contacted other SPs and there will be SPs from other regions joining in the next round. We have reached a cooperation agreement so far

**Comment by dahuajishu** [comment]
checker:manualTrigger

**Comment by NiwanDao** [comment]
checker:manualTrigger
