### ISSUE TITLE
[DataCap Application] <Zetacube Inc> - <Common Crawl February 2020>

### ISSUE THREAD

**Issue by hooonc** [filecoin-project/filecoin-plus-large-datasets#1991]
### Data Owner Name

Common Craw

### What is your role related to the dataset

Data Preparer

### Data Owner Country/Region

United States

### Data Owner Industry

Other

### Website

https://commoncrawl.org/2020/03/february-2020-crawl-archive-now-available/

### Social Media

```text
none
```

### Total amount of DataCap being requested

1PiB

### Weekly allocation of DataCap requested

100TiB

### On-chain address for first allocation

f1pkpa3h4suh77mi3guur25r5u4twkere5r35fjii

### Data Type of Application

Slingshot

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Zetacube Inc is a 'Ultra-high-capacity decentralized storage hyper server solution company' in the Web 3.0 era, established to research and commercialize the IPFS storage system, an innovative technology for safely storing huge data in the 4th industrial age.
Also, Zetacube Inc is participant in the Slingshot V3, both as DP and SP.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
The crawl archive for February 2020 is now available! It contains 2.6 billion web pages or 240 TiB of uncompressed content, crawled between February 16th and 29th. It includes page captures of 1 billion URLs unknown in any of our prior crawl archives.
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### How do you plan to prepare the dataset

singularity

### Please share a sample of the data

```text
https://commoncrawl.org/2020/03/february-2020-crawl-archive-now-available/
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Monthly

### For how long do you plan to keep this dataset stored on Filecoin

2 to 3 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, Africa, North America, South America, Europe, Australia (continent)

### How will you be distributing your data to storage providers

HTTP or FTP server, IPFS, Shipping hard drives

### How do you plan to choose storage providers

Slack, Big Data Exchange, Partners

### If you already have a list of storage providers to work with, fill out their names and provider IDs below

```text
f0838467 - IPFSKDC-Incheon
f01227505 - IPFSKDC-Incheon
f01942239 - IPFSKDC-Incheon
f01695888 - IPFSKDC-Gwangju
f01823110 - IPFSKDC-Jeonju
```

### How do you plan to make deals to your storage providers

Boost client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by HoonChoi-Zetacube** [comment]
@Sunnyiscoming Hi, my compay website is https://www.zetacube.net/
Our address is f01103160. It is not included in the SP list

**Comment by Sunnyiscoming** [comment]
Could you send an email to filplus-app-review@fil.org with your official domain in order to confirm your identity? Email name should includes the issue id #1991.

**Comment by HoonChoi-Zetacube** [comment]
@Sunnyiscoming I just sent an email to filplus-app-review@fil.org

**Comment by Sunnyiscoming** [comment]
![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/105098820/4914dd10-5def-4f1e-bed5-3870c7278262)
There is just no more than 100 TB data.

**Comment by Sunnyiscoming** [comment]
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/2003

**Comment by HoonChoi-Zetacube** [comment]
> ![image](https://user-images.githubusercontent.com/105098820/239695032-4914dd10-5def-4f1e-bed5-3870c7278262.png) There is just no more than 100 TB data.

This dataset is what we claimed on Slingshot.
Caro said DP should file LDN applications to the claimed dataset to require Data cap.

On Slingshot, you can see that a large number of data sets do not exceed 100 TiB.

**Comment by HoonChoi-Zetacube** [comment]
> #2003

<img width="792" alt="스크린샷 2023-05-21 060421" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/129706575/5d26d0af-b185-4b1b-9179-d7d12a11ce46">
My team claimed three datasets on Slingshot, and #2003 is one of them.

**Comment by Sunnyiscoming** [comment]
> Total amount of DataCap being requested
> 3PiB

This is not reasonable. Please check it again.

**Comment by HoonChoi-Zetacube** [comment]
I changed the total amount of DataCap requested to 1PiB.
Thank you.

**Comment by HoonChoi-Zetacube** [comment]
> > Total amount of DataCap being requested
> > 3PiB
> 
> This is not reasonable. Please check it again.

I changed the total amount of DataCap requested to 1PiB.
Thank you.

**Comment by GaryGJG** [comment]
Support this little beginning.

**Comment by GaryGJG** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebm3blaiy3e3h6u5eoccmbzwugo7dym4blmo7ko4yrhwob6wpzs4u 
#### Address 
> f1pkpa3h4suh77mi3guur25r5u4twkere5r35fjii
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1zffqhxwq2rrg7rtot6lmkl6hb2xyrrseawprzsq
#### Id
> d0eaed85-f595-4d10-ac20-48b857adb5ca
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebm3blaiy3e3h6u5eoccmbzwugo7dym4blmo7ko4yrhwob6wpzs4u

**Comment by laurarenpanda** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecbrznmf4kgsxilliqjcze4tjrrcgvxzls3tvriga4e7f3xhfpob4 
#### Address 
> f1pkpa3h4suh77mi3guur25r5u4twkere5r35fjii
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1bp3tzp536edm7dodldceekzbsx7zcy7hdfg6uzq
#### Id
> d0eaed85-f595-4d10-ac20-48b857adb5ca
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecbrznmf4kgsxilliqjcze4tjrrcgvxzls3tvriga4e7f3xhfpob4

**Comment by Sunnyiscoming** [comment]
checker:manualTrigger

**Comment by HoonChoi-Zetacube** [comment]
checker:manualTrigger

**Comment by HoonChoi-Zetacube** [comment]
checker:manualTrigger

**Comment by psh0691** [comment]
checker:manualTrigger

**Comment by cryptowhizzard** [comment]
@HoonChoi-Zetacube 

Why did you allocate 100% of the datacap to your own miners?

What part of the FIL+ rules did you not understand?

**Comment by psh0691** [comment]
checker:manualTrigger

**Comment by HoonChoi-Zetacube** [comment]
@cryptowhizzard @psh0691 We were new to onboarding, so there were a lot of unknowns. We thought that we needed to finish uploading at one node before we could upload to another, so we were only onboarding one node. We will start onboarding another regions in Korea early next week by selecting two nodes from the node list.
In addition, regarding other regional SPs, we have been introduced to several regional SPs by the Protocol Labs Foundation and are currently negotiating data storage fees with them. We will update the node list as soon as everything is finalized.

**Comment by cryptowhizzard** [comment]
Well, how about that you fix the retrieval first for your machine?

![Scherm­afbeelding 2023-07-06 om 15 16 06](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/36404435/ad8a40c1-9e6f-43e0-8a29-110c8d594758)

**Comment by HoonChoi-Zetacube** [comment]
@cryptowhizzard A failure occurred while changing the software settings. We will make sure that the correction is completed by the end of the day.

**Comment by psh0691** [comment]
checker:manualTrigger

**Comment by HoonChoi-Zetacube** [comment]
The SPs in the other regions we were planning to replicate the data to are experiencing software issues. Our team is diligently working on resolving these issues promptly, and we will initiate the replication process as soon as the software problems are rectified.

**Comment by HoonChoi-Zetacube** [comment]
We are copying and transferring data to other regional SPs. We will start saving as soon as the copy is finished.

**Comment by cryptowhizzard** [comment]
checker:manualTrigger

**Comment by spaceT9** [comment]
checker:manualTrigger

**Comment by HoonChoi-Zetacube** [comment]
We have confirmed overseas SPs and will start onboarding their equipment as soon as the necessary preparations are completed.

**Comment by spaceT9** [comment]
checker:manualTrigger

**Comment by clriesco** [comment]
Removed stale label and reopened issue :)

**Comment by HoonChoi-Zetacube** [comment]
checker:manualTrigger

**Comment by HoonChoi-Zetacube** [comment]
checker:manualTrigger

**Comment by HoonChoi-Zetacube** [comment]
Dear the governance team and notaries,
We made a big mistake when we made verified deals. When creating deals for #1991, we entered addresses for #2060 and some of them were already sealed. We realized our mistake, stopped the deals, and looked for a solution, but could not find one. I would really appreciate it if anyone could let me know the solution.
Again, we sincerely apologize for the trouble our mistake caused.

**Comment by HoonChoi-Zetacube** [comment]
checker:manualTrigger

**Comment by HoonChoi-Zetacube** [comment]
checker:manualTrigger

**Comment by HoonChoi-Zetacube** [comment]
checker:manualTrigger

**Comment by HoonChoi-Zetacube** [comment]
The assigned datacap is almost exhausted, but the DataCap request bot does not seem to have kicked off a request for a second allocation.
My team was not aware of the storage order when we started storing, so we currently have a lot of data stored on one SP. However, we realized our mistake and started distributed storage. We plan to store it in at least 5 SPs in the future.
Notaries, please sign this application.

**Comment by DanHan88** [comment]
@galen-mcandrew @
raghavrmadya

**Comment by DanHan88** [comment]
Dear @galen-mcandrew, @raghavrmadya, @Kevin-FF-USA, and @Sunnyiscoming,

We've encountered delays due to the lack of datacaps for our datasets. Could you please provide an update or guidance on how to proceed?

**Comment by Sunnyiscoming** [comment]
The rules have been violated. I can't move forward.

**Comment by kevzak** [comment]
Please list SPs publicly here @HoonChoi-Zetacube

**Comment by DanHan88** [comment]
> The rules have been violated. I can't move forward.

@Sunnyiscoming  70% rules or multiple sp rules will be followed through once I get additional datacaps.  Cid sharing report is bigger problem. and It is my fault. I accidently used wrong datacap wallet to do some of this deal. by the time i realized the mistake, some of data has already been sealed. we did report the mistake to other fil + application, but did not do it here. I will provide more details on this matter by tomorrow.

**Comment by DanHan88** [comment]
@kevzak , these are SPs that currently sealing. 
![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/130534113/dc388a9c-c725-4d01-ba65-a8741a28714c)

**Comment by DanHan88** [comment]
@Sunnyiscoming this common crawl dataset has 4448 carfiles. When I made first 1000 deal with f01695888, I used wrong datacap wallet assigned for https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/2060 .  I stopped the process in the middle when I found out the mistake. but by the time I realized it many of first 1000 deals were sealed. I asked around in slack, but I was told there is no way to fix the mistake. So I stopped the process. now I am trying to start  the process again with correct wallet and then make deals excluding the ones already sealed. 

I am really sorry that I made this terrible mistake. This is my first attempt to onboard data, and There has been a lot of mistakes and issues. we fixed many issues, and made scripts and systems to ensure we don't make same mistake. Please give us one more chance.

**Comment by HoonChoi-Zetacube** [comment]
@kevzak We are currently storing data on these three SPs.
f09848 Seamount Tech California, USA
f01227505 IPFSKDC Incheon, Korea
f01695888 IPFSKDC Gwangju, Korea

And, we plan to proceed with sealing by adding two SPs below.
f02005421 Greaterheat Dallas, USA
f01823110 IPFSKDC Jeonju, Korea

**Comment by maxvint** [comment]
checker:manualTrigger

**Comment by HoonChoi-Zetacube** [comment]
waiting for dc
