### ISSUE TITLE
[DataCap Application] <SXX Future Data> - LAMOST DR5 Public Dataset <2/2>

### ISSUE THREAD

**Issue by sxxfuture-official** [filecoin-project/filecoin-plus-large-datasets#1993]
### Data Owner Name

SXX Future Data

### What is your role related to the dataset

Data onramp entity that provides data onboarding services to multiple clients

### Data Owner Country/Region

China

### Data Owner Industry

Not-for-Profit

### Website

https://www.sxxfuture.com/

### Social Media

```text
https://twitter.com/sxxfuture
https://medium.com/@sxxfuture.official
https://discord.gg/GFsJaUFS9K
https://weibo.com/u/7801654981
```

### Total amount of DataCap being requested

10PiB

### Weekly allocation of DataCap requested

500TiB

### On-chain address for first allocation

f17nsjrlqrfuwdrdkln44gch5jxs4tcnwhke4iw2a

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Focusing on distributed big data storage, disaster data protection, encryption algorithm research, encrypted data product application and Web3.0 new-generation Internet research and development.
SXX Future Data provides government enterprises and individual users with products and service system with data value as the core to meet the ever-expanding demand for mass data storage, management and application.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
The Large Sky Area Multi-Object Fiber Spectroscopic Telescope (LAMOST) is a Chinese national scientific research facility operated by the National Astronomical Observatories, Chinese Academy of Sciences. It is a special reflecting Schmidt telescope with 4000 fibers in a field of view of 20 deg2
 in the sky. Until July 2016, LAMOST has completed its pilot survey which was launched in October 2011 and ended in June 2012, and the first four years of regular survey which was initiated on September 2012. After this five-year-survey, we totally obtain 7,617,035 spectra, which consist of stars, galaxies, quasars and other unknown objects[1−7]
. Now, the fourth data release (DR4) has published online (http://dr4.lamost.org/), and released data products include：

Spectra. - In general, there are 7,617,035 flux- and wavelength-calibrated, sky-subtracted spectra in DR4, including 6,943,865 stars, 117,254 galaxies, 36,575 quasars, and 519,341 unknown objects, and these spectra cover the wavelength range of 3690-9100 angstrom with a resolution of 1800[2−3]
 at the 5500 angstrom.
Spectroscopic Parameters Catalogs. - In this data release, six spectroscopic parameters catalogs are also published，they are the LAMOST general catalog, the A, F, G and K type star catalog, the A type star catalog, the M dwarf catalog, the observed plate information catalog, and the input catalog respectively. For the first four catalogs, they all include 36 columns of basic spectroscopic information, for example, right ascension, declination, signal to noise ratio, magnitude, classification and redshift. Also, the A type star catalog publish line indices of six spectral lines and four balmer line widths at 20% below the local continua, the A, F, G and K type star catalog provides effective temperature, surface gravity, and metallicity, and the M dwarf catalog releases the equivalent width of Halpha line, ten line indices, one metallicity sensitive parameter and a flag that indicates whether or not exist magnetic activity. For the observed plate information catalog, it mainly contains nine basic plate information for all published plates. At last, the input catalog includes 24 basic fields mentioned above, and three new fields which are not included in the above catalogs.

http://dr5.lamost.org/v3/doc/data-production-description

Guoshoujing Telescope (the Large Sky Area Multi-Object Fiber Spectroscopic Telescope LAMOST) is a National Major Scientific Project built by the Chinese Academy of Sciences. Funding for the project has been provided by the National Development and Reform Commission. LAMOST is operated and managed by the National Astronomical Observatories, Chinese Academy of Sciences.
```

### Where was the data currently stored in this dataset sourced from

Other

### If you answered "Other" in the previous question, enter the details here

```text
http://dr5.lamost.org/
```

### How do you plan to prepare the dataset

lotus, singularity, graphsplit

### Please share a sample of the data

```text
http://dr5.lamost.org/v3/sas/catalog/
http://dr5.lamost.org/v3/sas/fits/20111024/F5902/
http://dr5.lamost.org/v3/sas/fits/20111024/F5907/
http://dr5.lamost.org/v3/sas/fits/20111024/F5909/
http://dr5.lamost.org/v3/sas/png/20111024/F5902/
http://dr5.lamost.org/v3/sas/png/20111024/F5907/
http://dr5.lamost.org/v3/sas/png/20111024/F5909/
http://dr5.lamost.org/v3/sas/sky/20111024/
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

2 to 3 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America

### How will you be distributing your data to storage providers

HTTP or FTP server, Shipping hard drives

### How do you plan to choose storage providers

Slack, Partners

### If you already have a list of storage providers to work with, fill out their names and provider IDs below

```text
f02188881
f01986236
f02169409
f01986262
f02144581
```

### How do you plan to make deals to your storage providers

Boost client, Lotus client, Singularity

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by sxxfuture-official** [comment]
![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/113963951/186bbe3a-5eb0-44ea-aa79-87e744e67a5f)

**Comment by sxxfuture-official** [comment]
The public time node table of its data.
[http://www.lamost.org/lmusers/](http://www.lamost.org/lmusers/)
![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/113963951/9e977156-5415-4cc4-a579-56c89b4c9721)

**Comment by data-programs** [comment]
<img width="32" alt="KYC" Verified src="https://stable.filplus.storage/images/filplus-kyc-verified-badge.png"/>

This user’s identity has been verified through [filplus.storage](https://filplus.storage)

**Comment by sxxfuture-official** [comment]
@cryptowhizzard  it is closed
