### ISSUE TITLE
[DataCap Application] <Shenzhen Fingertip Culture Media Co., Ltd>

### ISSUE THREAD

**Issue by zhijianwenhua** [filecoin-project/filecoin-plus-large-datasets#1994]
### Data Owner Name

Shenzhen Fingertip Culture Media Co., Ltd

### What is your role related to the dataset

Dataset Owner

### Data Owner Country/Region

China

### Data Owner Industry

Information, Media & Telecommunications

### Website

https://www.qcc.com/firm/576f636e066245ce0fc18fc0d971b5f8.html

### Social Media

```text
https://www.qcc.com/firm/576f636e066245ce0fc18fc0d971b5f8.html
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

800TiB

### On-chain address for first allocation

f1jdsmd76jo35irsi7whidzohlntnmaj4yc7kaela

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Computer and network system technology development; Supply chain channel design, logistics scheme design; Technology development, technical consultation, technical service and technology transfer in the field of e-card, e-business card, digital technology, textile technology and printing; Digital electronic products, photographic equipment, photographic equipment, mechanical and electrical products, mechanical equipment, office supplies, printing equipment.Domestic trade; Operate import and export business. Organize cultural and artistic exchange activities; advertising production; Advertising design, agency; software development; Technical services, technology development, technical consultation, technology exchange, technology transfer, technology promotion; Graphic design
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
Mechanical finished products, mechanical design processes, photographic equipment, photography teaching, photographic works, etc. are used for the study and research of people in the same industry or amateurs.
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### How do you plan to prepare the dataset

singularity

### Please share a sample of the data

```text
https://www.aliyundrive.com/s/iAMspUx8CtB
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Monthly

### For how long do you plan to keep this dataset stored on Filecoin

More than 3 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, South America, Europe

### How will you be distributing your data to storage providers

HTTP or FTP server, Shipping hard drives

### How do you plan to choose storage providers

Slack, Big Data Exchange

### How do you plan to make deals to your storage providers

Boost client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by zhijianwenhua** [comment]
Our data comes from the accumulation of years of work in our company.
The official website has not been created yet, and there is currently no social media account available. We communicate through separate WeChat or group chats.

**Comment by Sunnyiscoming** [comment]
Can you provide more detailed data sources to prove that you have 5 PB data already?
Can you send your business license to me, filplus-app-review@fil.org. Email name should includes the issue id #1994.

**Comment by zhijianwenhua** [comment]
The message was sen
![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/133762784/9e36af2c-0690-41c0-9005-d83d53356f17)

**Comment by Sunnyiscoming** [comment]
Can you provide more detailed data sources, not screenshot?

**Comment by zhijianwenhua** [comment]
https://www.aliyundrive.com/s/mKMsgveXC5s

**Comment by Sunnyiscoming** [comment]
Please share more detailed information about sps you will cooperate with.

**Comment by zhijianwenhua** [comment]
f02062851     USA
f01877184     Singapore
f01660795     Shenzhen
f01128206     HK

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 5PiB

**Expected weekly DataCap usage rate**
> 800TiB

**Client address**
>f1jdsmd76jo35irsi7whidzohlntnmaj4yc7kaela

**Comment by woshidama323** [comment]
Suggest you should list SPs in more than 3 regions so that you can follow the FIL+ rules

**Comment by woshidama323** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebtnxwbzwp2d62zvdvewymcc6w7vjxzqryapqefvzzydc3diyhhrc 
#### Address 
> f1jdsmd76jo35irsi7whidzohlntnmaj4yc7kaela
#### Datacap Allocated
> 256.00TiB
#### Signer Address
> f12tk3adljauwnd3hjbigpfxb7b7gdlj63p6afwtq
#### Id
> 6d3a72f2-0cca-433d-b0fd-3a9b45906efe
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebtnxwbzwp2d62zvdvewymcc6w7vjxzqryapqefvzzydc3diyhhrc

**Comment by zcfil** [comment]
I have reviewed historical information and am willing to provide support in the first round, and will follow up on the data situation in the later stage

**Comment by zcfil** [comment]
checker:manualTrigger

**Comment by 1ane-1** [comment]
checker:manualTrigger

**Comment by 1ane-1** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb6jqoxwurm5r5vmvrzq5qf2adh4mt3sjcjoe53wyeh6olxuvv2es 
#### Address 
> f1jdsmd76jo35irsi7whidzohlntnmaj4yc7kaela
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f1mdk7s2vntzm6hu35yuo6vjubtrpfnb2awhgvrri
#### Id
> 6b2066be-5e37-47af-a158-89e03b688409
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb6jqoxwurm5r5vmvrzq5qf2adh4mt3sjcjoe53wyeh6olxuvv2es

**Comment by zcfil** [comment]
checker:manualTrigger

**Comment by zhijianwenhua** [comment]
checker:manualTrigger

**Comment by psh0691** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceat2vcwedr235vdwgueahsxklpj7xeugp7ql2gc3o26tyqkpixhy2 
#### Address 
> f1jdsmd76jo35irsi7whidzohlntnmaj4yc7kaela
#### Datacap Allocated
> 1.00PiB
#### Signer Address
> f1qdko4jg25vo35qmyvcrw4ak4fmuu3f5rif2kc7i
#### Id
> 329f89f0-3bdc-4409-b2f9-2d8fdf529136
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceat2vcwedr235vdwgueahsxklpj7xeugp7ql2gc3o26tyqkpixhy2

**Comment by zhijianwenhua** [comment]
checker:manualTrigger

**Comment by Normalnoise** [comment]
checker:manualTrigger

**Comment by cryptowhizzard** [comment]
Hello,

I have downloaded some of this data. See : http://datasetcreators.com/downloadedcarfiles/1994-f02191439-f01859603-43663248-baga6ea4seaqdjrtinxmw7jfzlbbtkrcejvc2gaw6btcnkr6rey5adzafzclr2jy/

This data is different from the data you said you were going to store. All mp4 files are broken.
Please clarify.
