### ISSUE TITLE
[DataCap Application] <HashFrog> - <National Solar Radiation Database>

### ISSUE THREAD

**Issue by Mario-y** [filecoin-project/filecoin-plus-large-datasets#1995]
### Data Owner Name

HashFrog

### What is your role related to the dataset

Storage provider filling out application on behalf of the data owner

### Data Owner Country/Region

China

### Data Owner Industry

Web3 / Crypto

### Website

https://www.hashfrog.com/

### Social Media

```text
https://www.hashfrog.com/
https://twitter.com/HashFrogTech
https://www.facebook.com/hashfrog
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

500TiB

### On-chain address for first allocation

f166crdxpdb3tkmidif4kjoyfwjtzzfwswcojmyvy

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
HashFrog is a cloud computing power platform. The computing power comes from tens of thousands of real mining machines. The platform cuts and allocates the computing power of the mining machines. After purchasing the computing power, users can monitor the operation of their own computing power from a third-party mining pool. 

As a leading blockchain company, we are very concerned about innovation in the industry, and we also hope to adjust the company's processes to practice the concept of web3. The decentralized storage field led by Filecoin is our long-term optimistic track，we are also joining this track, hoping that we can store more data on the filecoin chain.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
Released to the public as part of the Department of Energy's Open Energy Data Initiative, the National Solar Radiation Database (NSRDB) is a serially complete collection of hourly and half-hourly values of the three most common measurements of solar radiation – global horizontal, direct normal, and diffuse horizontal irradiance — and meteorological data. These data have been collected at a sufficient number of locations and temporal and spatial scales to accurately represent regional solar radiation climates.
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### How do you plan to prepare the dataset

IPFS, lotus, graphsplit

### Please share a sample of the data

```text
s3://nrel-pds-nsrdb/
The data is about 420.8 TiB
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Monthly

### For how long do you plan to keep this dataset stored on Filecoin

1.5 to 2 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, Europe

### How will you be distributing your data to storage providers

HTTP or FTP server, IPFS, Shipping hard drives

### How do you plan to choose storage providers

Slack, Partners

### If you already have a list of storage providers to work with, fill out their names and provider IDs below

```text
f02098007
f0867300
f01981571
f02029115
f0522948
f02182251
f01228008
f01975316
f01348489
f02099939
f01975326
f01053413
f02092901
```

### How do you plan to make deals to your storage providers

Boost client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
How many copies will you store?
Which are your nodes?
Could you send an email to filplus-app-review@fil.org with your official domain in order to confirm your identity? Email name should includes the issue id #1995.

**Comment by Sunnyiscoming** [comment]
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1015

**Comment by Liuyang1015** [comment]
> How many copies will you store? Which are your nodes? Could you send an email to [filplus-app-review@fil.org](mailto:filplus-app-review@fil.org) with your official domain in order to confirm your identity? Email name should includes the issue id #1995.

Hi, @Sunnyiscoming I have sent the email by using the address of admin@hashfrog.xyz. Please help me to check. Our invested node id is f01975316. And we will send at least 8 copies to different SPs these in different areas.

**Comment by Liuyang1015** [comment]
> #1015

The apply of #1015 was closed,because the owner of the github account has left from our company. We will also store  our own data in the near future.

**Comment by Liuyang1015** [comment]
> Why did you email me by using the domain name hashfrog.xyz instead of hashfrog.com. Can you send me the registration/business license to me?

Hi, @Sunnyiscoming . Both kinds of mail address are our email for external communication.We also sent an email with the email address s.hashfrog.com, please check it.

**Comment by Sunnyiscoming** [comment]
Can you send me the registration/business license to me?

**Comment by Liuyang1015** [comment]
> Can you send me the registration/business license to me?

Hello, this is the hashfrog domain name and company information, please check it
![Uploading mmexport1684760534452.jpg…]()

**Comment by Liuyang1015** [comment]
> Can you send me the registration/business license to me?

Hello, this is the hashfrog domain name and company information, please check it
![微信图片_20230522205905](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/39185425/670f6740-3324-4391-8b43-020a44100dab)

**Comment by Sunnyiscoming** [comment]
I can not find anything related with SKY SAIL DEVELOPMENTS LIMITED
https://www.ltddir.com/companies/sky-sail-limited-2/, whether it is related with your organization?

**Comment by Liuyang1015** [comment]
> I can not find anything related with SKY SAIL DEVELOPMENTS LIMITED https://www.ltddir.com/companies/sky-sail-limited-2/, whether it is related with your organization?

Hello, this involves the company's private information, please delete this reply, we will send registration/business license to your email(filplus-app-review@fil.org) by email  admin@hashfrog.xyz.

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 5PiB

**Expected weekly DataCap usage rate**
> 500TiB

**Client address**
>f166crdxpdb3tkmidif4kjoyfwjtzzfwswcojmyvy

**Comment by nj-steve** [comment]
Hello @Liuyang1015  How much data have you prepared? How many copies do you plan to send?

**Comment by Liuyang1015** [comment]
> Hello @Liuyang1015 How much data have you prepared? How many copies do you plan to send?

Hi @nj-steve,70T of data has been downloaded and is going to be sent to 8 SPs.

**Comment by bq1024** [comment]
> > Hello @Liuyang1015 How much data have you prepared? How many copies do you plan to send?
> 
> Hi @nj-steve,70T of data has been downloaded and is going to be sent to 8 SPs.

Can you show me the data you've downloaded? And where are these 8 SPs located?

**Comment by Liuyang1015** [comment]
> > > Hello @Liuyang1015 How much data have you prepared? How many copies do you plan to send?
> > 
> > 
> > Hi @nj-steve,70T of data has been downloaded and is going to be sent to 8 SPs.
> 
> Can you show me the data you've downloaded? And where are these 8 SPs located?

This is the data data we have downloaded. The SPs we send are distributed in Hong Kong, the United States, Singapore and Europe.
![mmexport1685058700126](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/39185425/6db713f9-d281-4820-a5f2-42a5ffa67fb7)

**Comment by bq1024** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecdmlapnamzt4ct4ca267onsx3w76v3bakqn6v7d23zi62xz7szlc 
#### Address 
> f166crdxpdb3tkmidif4kjoyfwjtzzfwswcojmyvy
#### Datacap Allocated
> 250.00TiB
#### Signer Address
> f1pkjtavqx4r2q2w3he3jknfc5mo2vgfimccmpnaa
#### Id
> 7d0ee9d5-7462-4f13-bb25-dca22dc67c84
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecdmlapnamzt4ct4ca267onsx3w76v3bakqn6v7d23zi62xz7szlc

**Comment by Joss-Hua** [comment]
Have contacted the applicant and have a preliminary understanding. I'm willing to support this round and pay attention to the subsequent inspection results.

**Comment by Joss-Hua** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecusghqwrnsidlip2nmrxeo2kt6iilgj3m6svq5laxtc6drub3idk 
#### Address 
> f166crdxpdb3tkmidif4kjoyfwjtzzfwswcojmyvy
#### Datacap Allocated
> 250.00TiB
#### Signer Address
> f1tfg54zzscugttejv336vivknmsnzzmyudp3t7wi
#### Id
> 7d0ee9d5-7462-4f13-bb25-dca22dc67c84
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecusghqwrnsidlip2nmrxeo2kt6iilgj3m6svq5laxtc6drub3idk

**Comment by stcouldlisa** [comment]
checker:manualTrigger

**Comment by mikezli** [comment]
The customer contacted me, as the first round, temporary support, I will continue to pay attention

**Comment by mikezli** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecgc3hwz3usbehpc2to23bm7vz5grzuvqtycnfpphdav5mmfh4hvc 
#### Address 
> f166crdxpdb3tkmidif4kjoyfwjtzzfwswcojmyvy
#### Datacap Allocated
> 250.00TiB
#### Signer Address
> f1dnb3uz7sylxk6emti3ififcvu3nlufnnsjui6ea
#### Id
> 7d0ee9d5-7462-4f13-bb25-dca22dc67c84
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecgc3hwz3usbehpc2to23bm7vz5grzuvqtycnfpphdav5mmfh4hvc

**Comment by Liuyang1015** [comment]
> This application has not seen any responses in the last 10 days. This issue will be marked with Stale label and will be closed in 4 days. Comment if you want to keep this application open.

checker:manualTrigger

**Comment by Sunnyiscoming** [comment]
checker:manualTrigger

**Comment by Liuyang1015** [comment]
checker:manualTrigger

**Comment by cryptowhizzard** [comment]
checker:manualTrigger

**Comment by Liuyang1015** [comment]
checker:manualTrigger

**Comment by Liuyang1015** [comment]
checker:manualTrigger

**Comment by Mario-y** [comment]
Keep

**Comment by Mario-y** [comment]
keep

**Comment by Mario-y** [comment]
checker:manualTrigger

**Comment by Mario-y** [comment]
checker:manualTrigger

**Comment by cryptowhizzard** [comment]
Dear Liuyang1015,

As notary I am doing due diligence on your LDN. I could not get retrieval to work. Can you please upload the car file of CID baga6ea4seaqlz76begw7wztpcluduarj74sbob4unkaszpquljh4kwbypcrw6ga ?

You can use our upload system at http://send.datasetcreators.com. Please select 7 days for the system to keep the file and post the link you received here so I (and other notaries) can download your content.

**Comment by Mario-y** [comment]
> Dear Liuyang1015,
> 
> As notary I am doing due diligence on your LDN. I could not get retrieval to work. Can you please upload the car file of CID baga6ea4seaqlz76begw7wztpcluduarj74sbob4unkaszpquljh4kwbypcrw6ga ?
> 
> You can use our upload system at http://send.datasetcreators.com. Please select 7 days for the system to keep the file and post the link you received here so I (and other notaries) can download your content.

Dear cryptowhizzard,

No problem, I will prepare it and use the upload system you provided for you

**Comment by Mario-y** [comment]
https://send.datasetcreators.com/download/ced66596aa7bcbee/#kls74ctBvkCLuRLQdCiz3Q

**Comment by cryptowhizzard** [comment]
Thank you!

Data downloaded and verified. Looking good!

**Comment by igoovo** [comment]
checker:manualTrigger

**Comment by igoovo** [comment]
The report of the CID inspection looks good,
There is no CID sharing, and the retrieval rate is also good.

The content has been verified by other notaries, so I am willing to support it.
<img width="515" alt="image" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/103082537/01fb26c5-3aac-407d-888f-6d86fdc903e3">
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1995#issuecomment-1731940033

**Comment by igoovo** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedwhg6udnnjqz6sfi35r4zdvgvfq7gof2ovj7jpwe37af7kbwzs5q 
#### Address 
> f166crdxpdb3tkmidif4kjoyfwjtzzfwswcojmyvy
#### Datacap Allocated
> 500.00TiB
#### Signer Address
> f1shnsfayxqll77svffaxnjenms7bbbysbqcatrpy
#### Id
> 03833259-d42b-4690-9b7e-3ce01944ebc3
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedwhg6udnnjqz6sfi35r4zdvgvfq7gof2ovj7jpwe37af7kbwzs5q

**Comment by ipfscn** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaiktxjmwqf6wzb5n3fyrauu4cfsrs7sgmv2775rvvp7z4nkahmwg 
#### Address 
> f166crdxpdb3tkmidif4kjoyfwjtzzfwswcojmyvy
#### Datacap Allocated
> 500.00TiB
#### Signer Address
> f1j4n74chme7whbz3yls4a7ixqewb6dijypqg2a3a
#### Id
> 03833259-d42b-4690-9b7e-3ce01944ebc3
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaiktxjmwqf6wzb5n3fyrauu4cfsrs7sgmv2775rvvp7z4nkahmwg

**Comment by yangliu-ocean** [comment]
checker:manualTrigger

**Comment by Mario-y** [comment]
checker:manualTrigger

**Comment by Mario-y** [comment]
keep going

**Comment by Mario-y** [comment]
keep going

**Comment by herrehesse** [comment]
checker:manualTrigger

**Comment by herrehesse** [comment]
@Kevin-FF-USA this entity is FULLY self dealing, all miners are under VPN and most likely same owner.

Close LDN.

**Comment by Mario-y** [comment]
checker:manualTrigger

**Comment by Mario-y** [comment]
checker:manualTrigger

**Comment by herrehesse** [comment]
![Screenshot 2023-11-06 at 10 47 00](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/70132857/1cb8ac91-db56-4c46-88af-192b085a6a1b)

@Kevin-FF-USA this entity is FULLY self dealing, all miners are under VPN and most likely same owner.

Close LDN.

**Comment by Mario-y** [comment]
checker:manualTrigger

**Comment by Mario-y** [comment]
checker:manualTrigger

**Comment by herrehesse** [comment]
ABUSE. @Kevin-FF-USA @kevzak close this ldn.

**Comment by Mario-y** [comment]
Hi, @Sunnyiscoming , I have filled out and submitted the FIL+ registration form. please check it.

**Comment by herrehesse** [comment]
also please add the contact information of the SP entities you are working with to store copies of the data.

**Comment by Mario-y** [comment]
Thank you for your due diligence. I have already added it.

**Comment by Filplus-govteam** [comment]
checker:manualTrigger

**Comment by Filplus-govteam** [comment]
SPs taking deals:
**f02229707** | Hong Kong, Central and Western, HKChina Unicom Global | 49.62 TiB | 22.65% | 49.62 TiB | 0.00%
f02236570 | Hong Kong, Central and Western, HKChina Unicom Global | 49.60 TiB | 22.65% | 49.60 TiB | 0.00%
**f02237709** | Hong Kong, Central and Western, HKChina Unicom Global | 24.31 TiB | 11.10% | 24.31 TiB | 0.00%
**f02236033** | Singapore, Singapore, SGThe Constant Company, LLC | 24.31 TiB | 11.10% | 24.31 TiB | 0.00%
**f02237106** | London, England, GBUCLOUD INFORMATION TECHNOLOGY (HK) LIMITED | 49.67 TiB | 22.68% | 49.67 TiB | 0.00%
**f02238701** | Los Angeles, California, USUCLOUD INFORMATION TECHNOLOGY (HK) LIMITED | 21.50 TiB | 9.82% | 21.50 TiB | 0.00%

SPs provided on list:

f02229707 | Elio NJ | HongKong | NO | Elio
f02238701 | joe  ipfswindow | US | NO | Joe
f02236033 | frank  IPFS FILE | Singapore | NO | Frank
f02237106 | ZhangZhang  YuanTai Software | London | NO | ZhangZhang
f02237709 | LEO Chen | Mine Fill | HongKong | NO | LEO

**Comment by herrehesse** [comment]
checker:manualTrigger

**Comment by herrehesse** [comment]
<img width="1032" alt="Screenshot 2023-11-29 at 09 10 29" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/70132857/e8ce7b92-2676-4303-aa68-bbab803b4ad9">

@Filplus-govteam This entity is clearly self-dealing to miners under VPN who are all located and owned by the same entity.
Companies listed are fake, names are fake as well.

Close this LDN.

**Comment by herrehesse** [comment]
checker:manualTrigger

**Comment by herrehesse** [comment]
![Screenshot 2023-12-05 at 09 43 18](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/70132857/e08d916b-74c0-4b21-86ec-31b265a33ff8)

Self-dealing over 50% likely 100%.
CLOSE.

**Comment by Sunnyiscoming** [comment]
SP List provided:
[{"providerID":"f02229707","City":"HongKong","Country":"CN","SPOrg","NJ"},
{"providerID":"f02238701","City":"XYZ","Country":"US","SPOrg","ipfswindow"},
{"providerID":"f02236033","City":"XYZ","Country":"Singapore","SPOrg","IPFS"},
{"providerID":"f02237106","City":"London","Country":"UK","SPOrg","YuanTai"},
{"providerID":"f02237709","City":"HongKong","Country":"CN","SPOrg","Chen"},
{"providerID":"f02236570","City":"HongKong","Country":"CN","SPOrg","XYZ"},]

**Comment by Mario-y** [comment]
checker:manualTrigger

**Comment by Mario-y** [comment]
The issue with duplicate data in the f02826888 transaction is likely due to network fluctuations, causing some repeated orders to be sent by mistake, which I promptly stopped. I have also fixed the network, and I think this issue will not occur again.

**Comment by Mario-y** [comment]
Here  are new SPs we sent:
| SP ID          | Organization |  City           |   Country |
| ------         | ------            | ------         | ------     | 
|f02826888 | chimsen | Toronto|  CA|
|f02827777 | chimsen | Mumbai|  IN|
|f02825666 | chimsen | Shenzhen|  CN|

**Comment by Mario-y** [comment]
checker:manualTrigger

**Comment by Mario-y** [comment]
checker:manualTrigger

**Comment by Mario-y** [comment]
In the next round, we will add some new storage providers to sovle this alert issue.

**Comment by SuperChaiChai** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedh3ohxldtwldayko46arb2v3anavw24zsmttido42shk2spjvjik 
#### Address 
> f166crdxpdb3tkmidif4kjoyfwjtzzfwswcojmyvy
#### Datacap Allocated
> 1000.00TiB
#### Signer Address
> f12mckci3omexgzoeosjvstcfxfe4vqw7owdia3da
#### Id
> 6713b776-04e5-464a-89c3-8eacc63e0f9b
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedh3ohxldtwldayko46arb2v3anavw24zsmttido42shk2spjvjik

**Comment by kernelogic** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceagjp4uqb6flibilrjpo2usqme4zbl33jpv6x5cjtnla2vqhc46pk 
#### Address 
> f166crdxpdb3tkmidif4kjoyfwjtzzfwswcojmyvy
#### Datacap Allocated
> 1000.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### Id
> 6713b776-04e5-464a-89c3-8eacc63e0f9b
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceagjp4uqb6flibilrjpo2usqme4zbl33jpv6x5cjtnla2vqhc46pk

**Comment by kernelogic** [comment]
The explanation by OP is satisfactory.

**Comment by Mario-y** [comment]
checker:manualTrigger

**Comment by Mario-y** [comment]
keep going

**Comment by DDUPA** [comment]
checker:manualTrigger

**Comment by Mario-y** [comment]
checker:manualTrigger

**Comment by Mario-y** [comment]
The SPs' infomation is below.  
| SP ID          | Organization |  City           |   Country |
| ------         | ------            | ------         | ------     | 
| f02827111 | WanDao           | Osaka    | JP |
| f02828222 | WanDao       |Seoul         | KR       |


We will resolve this alert issue in the near future。

**Comment by sxxfuture-official** [comment]
Reduce the duplicate data occupancy of f02826888 and f02827777 in the subsequent process.

**Comment by sxxfuture-official** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb5mpnekamzhxz3xhomrktwxe3yugspfgy3vz7azdg33l6s2czqvo 
#### Address 
> f166crdxpdb3tkmidif4kjoyfwjtzzfwswcojmyvy
#### Datacap Allocated
> 1000.00TiB
#### Signer Address
> f1foiomqlmoshpuxm6aie4xysffqezkjnokgwcecq
#### Id
> 13057ca1-5110-4d7c-b3e2-5731bb30de7a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb5mpnekamzhxz3xhomrktwxe3yugspfgy3vz7azdg33l6s2czqvo

**Comment by Bitrise0111** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacea7wsimxqcjnqehpbppclzpmsx5xsbq23n23sshqn326durmhsiho 
#### Address 
> f166crdxpdb3tkmidif4kjoyfwjtzzfwswcojmyvy
#### Datacap Allocated
> 1000.00TiB
#### Signer Address
> f1nknj7ayq4o43czrtdoauggtwl43fbqatmqis3yy
#### Id
> 13057ca1-5110-4d7c-b3e2-5731bb30de7a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacea7wsimxqcjnqehpbppclzpmsx5xsbq23n23sshqn326durmhsiho

**Comment by Mario-y** [comment]
checker:manualTrigger

**Comment by Mario-y** [comment]
checker:manualTrigger

**Comment by nj-steve** [comment]
checker:manualTrigger

**Comment by nj-steve** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedkx7z4e734ycgcg46im5otfa2qdlzbfmhibxrgqmnerz54qrikoa 
#### Address 
> f166crdxpdb3tkmidif4kjoyfwjtzzfwswcojmyvy
#### Datacap Allocated
> 1.95PiB
#### Signer Address
> f1xx6555qijma7igpnjspyvdunc4vfxkawnpqy5ii
#### Id
> 8acad236-8b82-4e7e-bb92-f33c3f5c2f9c
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedkx7z4e734ycgcg46im5otfa2qdlzbfmhibxrgqmnerz54qrikoa

**Comment by Tom-OriginStorage** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceakeok7co6owfayefvrcs3p27dj4wq46dqqbakay5mrpnwhnzsmum 
#### Address 
> f166crdxpdb3tkmidif4kjoyfwjtzzfwswcojmyvy
#### Datacap Allocated
> 1.95PiB
#### Signer Address
> f1q6bpjlqia6iemqbrdaxr2uehrhpvoju3qh4lpga
#### Id
> 8acad236-8b82-4e7e-bb92-f33c3f5c2f9c
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceakeok7co6owfayefvrcs3p27dj4wq46dqqbakay5mrpnwhnzsmum

**Comment by nj-steve** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedsuvtcpahg3mjnkur74cgg6ufo5zpjgq4vsnztewmk26zuuwrvla 
#### Address 
> f166crdxpdb3tkmidif4kjoyfwjtzzfwswcojmyvy
#### Datacap Allocated
> 1.95PiB
#### Signer Address
> f1xx6555qijma7igpnjspyvdunc4vfxkawnpqy5ii
#### Id
> 327f9c4e-3677-4d2c-be80-72b096de6a05
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedsuvtcpahg3mjnkur74cgg6ufo5zpjgq4vsnztewmk26zuuwrvla

**Comment by Mario-y** [comment]
Here are new SPs we sent:

SP ID | Organization | City | Country
-- | -- | -- | --
f02825333 | YuanTai Software | Saitama | JP
f02825444 | YuanTai Software | Singapore | SG
f02825855 | YuanTai Software | Seoul | KR

The issue of copying numbers greater than 4 will be addressed in the next round.

**Comment by 1ane-1** [comment]
checker:manualTrigger

**Comment by 1ane-1** [comment]
Please solve the report problem above in the next round. At least 4 SPs.  Temporary  support !

**Comment by 1ane-1** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedxfpt6gy2fiovhorvzm2qc7keg4tgm4yfluzxfg3w2d2s5utzzaq 
#### Address 
> f166crdxpdb3tkmidif4kjoyfwjtzzfwswcojmyvy
#### Datacap Allocated
> 1.95PiB
#### Signer Address
> f1mdk7s2vntzm6hu35yuo6vjubtrpfnb2awhgvrri
#### Id
> 327f9c4e-3677-4d2c-be80-72b096de6a05
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedxfpt6gy2fiovhorvzm2qc7keg4tgm4yfluzxfg3w2d2s5utzzaq

**Comment by Joss-Hua** [comment]
I have received the client's message and will provide support in the next round once the above issues are resolved.

**Comment by Mario-y** [comment]
Close as complete
