### ISSUE TITLE
[DataCap Application] ComStock Aws dataset

### ISSUE THREAD

**Issue by Inayatullah199** [filecoin-project/filecoin-plus-large-datasets#1997]
### Data Owner Name

National Renewable Energy Laboratory

### What is your role related to the dataset

Data Preparer

### Data Owner Country/Region

United States

### Data Owner Industry

Environment

### Website

https://www.nrel.gov/index.html

### Social Media

```text
FACEBOOK-https://www.facebook.com/nationalrenewableenergylab
LINKEDIN-https://www.linkedin.com/company/national-renewable-energy-laboratory
YOUTUBE-https://www.youtube.com/user/NRELPR
TWITTER-https://twitter.com/nrel/
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

800TiB

### On-chain address for first allocation

f1whhxwushklk2lklqj7yv3lulqphdgnamei4fdfy

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
I'm a DP who has downloaded this dataset. This dataset is from NREL. At the National Renewable Energy Laboratory (NREL), they focus on creative answers to today's energy challenges. From breakthroughs in fundamental science to new clean technologies to integrated energy systems that power our lives, NREL researchers are transforming the way the nation and the world use energy.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
The commercial building sector stock model, or ComStock, is a highly granular, bottom-up model that uses multiple data sources, statistical sampling methods, and advanced building energy simulations to estimate the annual sub-hourly energy consumption of the commercial building stock across the United States.
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### How do you plan to prepare the dataset

lotus, singularity

### Please share a sample of the data

```text
https://registry.opendata.aws/nrel-pds-building-stock/
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

1.5 to 2 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, Europe

### How will you be distributing your data to storage providers

HTTP or FTP server, Shipping hard drives, Lotus built-in data transfer

### How do you plan to choose storage providers

Slack, Big Data Exchange

### If you already have a list of storage providers to work with, fill out their names and provider IDs below

```text
In the process.
```

### How do you plan to make deals to your storage providers

Lotus client, Singularity

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Inayatullah199** [comment]
@Sunnyiscoming Hi Sunny, I will distribute less than 30% of total datacap to every sp. The exact amount of distribution will be based on the number of sp's I have contacted.

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 5PiB

**Expected weekly DataCap usage rate**
> 800TiB

**Client address**
>f1whhxwushklk2lklqj7yv3lulqphdgnamei4fdfy

**Comment by Meibuy** [comment]
The applicant reached me on Slack and willing to support its first allocation.

**Comment by Meibuy** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaqppjyzsb5547m4p6lbqvkugziacko3o3kezwvb4tzya62cn6bae 
#### Address 
> f1whhxwushklk2lklqj7yv3lulqphdgnamei4fdfy
#### Datacap Allocated
> 256.00TiB
#### Signer Address
> f1bwugfihrmn3iyunzyxst5nttql3dge4khwmurtq
#### Id
> 2702c31f-1dd9-488f-9d7d-d1695f90b38c
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaqppjyzsb5547m4p6lbqvkugziacko3o3kezwvb4tzya62cn6bae

**Comment by AthSmith** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebltigwp6sjjspxc2unf2qi6n4qwnvxjgink2eihjausda5jv5rvu 
#### Address 
> f1whhxwushklk2lklqj7yv3lulqphdgnamei4fdfy
#### Datacap Allocated
> 256.00TiB
#### Signer Address
> f1vxbqrf7rfum3n6m5u6eb4re6xj7amvsaqnzu64y
#### Id
> 2702c31f-1dd9-488f-9d7d-d1695f90b38c
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebltigwp6sjjspxc2unf2qi6n4qwnvxjgink2eihjausda5jv5rvu

**Comment by AthSmith** [comment]
The client contacted me by slack and shared the storage plan. I'd like to see more public data joining the network!

**Comment by BobbyChoii** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaixnzy6uynw7kbtt2lycgowbvkkgec6rwtiza7acwtpujmrhunos 
#### Address 
> f1whhxwushklk2lklqj7yv3lulqphdgnamei4fdfy
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f1irqs2gmctiv3jcdfwuch7oxvf4ixh3k4b2wc24i
#### Id
> ae9ec7f4-74de-4951-b481-ee317adff3d8
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaixnzy6uynw7kbtt2lycgowbvkkgec6rwtiza7acwtpujmrhunos

**Comment by Aifabot-Cloud** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec542xpnproafv66i5yn3mos3iiscjv5xcbidzr7bj6vrj75fo7wy 
#### Address 
> f1whhxwushklk2lklqj7yv3lulqphdgnamei4fdfy
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f174fg3bqbln3zjnkxtyf6s54txqkr7yqkj6cig7y
#### Id
> ae9ec7f4-74de-4951-b481-ee317adff3d8
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec542xpnproafv66i5yn3mos3iiscjv5xcbidzr7bj6vrj75fo7wy

**Comment by Aifabot-Cloud** [comment]
Open datasets bring great value to the network. Happy to see more of them join Filecoin. Please keep the allocation in line with Filplus guidlines.

**Comment by AthSmith** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedd3n6w72bbrxxzgnkotwvwfojbtqaf2zl7yne3j7eexwzihm266a 
#### Address 
> f1whhxwushklk2lklqj7yv3lulqphdgnamei4fdfy
#### Datacap Allocated
> 1.00PiB
#### Signer Address
> f1vxbqrf7rfum3n6m5u6eb4re6xj7amvsaqnzu64y
#### Id
> ff95d35b-078d-4dd0-b809-8b1d80b1687a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedd3n6w72bbrxxzgnkotwvwfojbtqaf2zl7yne3j7eexwzihm266a

**Comment by spaceT9** [comment]
checker:manualTrigger

**Comment by Inayatullah199** [comment]
YES

**Comment by Aifabot-Cloud** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceblaxuqaudjyj4n6ucnt7da5cwn64j5rudzsylk2fsh3qz2h2vixm 
#### Address 
> f1whhxwushklk2lklqj7yv3lulqphdgnamei4fdfy
#### Datacap Allocated
> 2.00PiB
#### Signer Address
> f174fg3bqbln3zjnkxtyf6s54txqkr7yqkj6cig7y
#### Id
> a7d6b768-0b0b-41d0-bdf6-a461a13630a5
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceblaxuqaudjyj4n6ucnt7da5cwn64j5rudzsylk2fsh3qz2h2vixm

**Comment by RawTechVentures** [comment]
The report is indeed inaccurate and the dataset can be retrieved.

**Comment by Wengeding** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceafi4doqj4awk725pa3y4embdl3ugty4sgeufacapla2lnl24sace 
#### Address 
> f1whhxwushklk2lklqj7yv3lulqphdgnamei4fdfy
#### Datacap Allocated
> 2.00PiB
#### Signer Address
> f1txfsjmix4vlzido4dkildrnbw26owtlbslexmpa
#### Id
> a7d6b768-0b0b-41d0-bdf6-a461a13630a5
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceafi4doqj4awk725pa3y4embdl3ugty4sgeufacapla2lnl24sace

**Comment by C00kies77** [comment]
checker:manualTrigger

**Comment by cryptowhizzard** [comment]
checker:manualTrigger

**Comment by cryptowhizzard** [comment]
Dispute made:

https://github.com/filecoin-project/notary-governance/issues/944

@Aifabot-Cloud @Wengeding , you have been signing while you knew that the retrievability was 0%.

**Comment by spaceT9** [comment]
checker:manualTrigger

**Comment by cryptowhizzard** [comment]
Hello, 

I see that you are working with a lot of SP's who are tagged for abuse.

All SP's with AT1 are tagged for CID sharing
All SP's with AT3 don't have retrieval enabled ( for obvious reasons ).

Can you clarify please?

![Scherm­afbeelding 2023-07-28 om 13 39 29](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/36404435/923fa2c0-49d2-480a-b749-c781fd6ba572)

**Comment by Inayatullah199** [comment]
So that's the reason you've been leaving so many messages everywhere!

https://filecoinproject.slack.com/archives/C01DLAPKDGX/p1690606951304359

**Comment by Dave-lgtm** [comment]
checker:manualTrigger

**Comment by Meibuy** [comment]
checker:manualTrigger

**Comment by Meibuy** [comment]
It does look like a big improvement from the report, and I'm willing to support this round.

**Comment by Meibuy** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedqouleczfzr4gizkj6op3sjfe76goyujpvqjnz63wqhems7se4wm 
#### Address 
> f1whhxwushklk2lklqj7yv3lulqphdgnamei4fdfy
#### Datacap Allocated
> 1.25PiB
#### Signer Address
> f1bwugfihrmn3iyunzyxst5nttql3dge4khwmurtq
#### Id
> 6cbfa247-e88b-4c54-a136-4a5a0dfe5bea
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedqouleczfzr4gizkj6op3sjfe76goyujpvqjnz63wqhems7se4wm

**Comment by Wengeding** [comment]
checker:manualTrigger

**Comment by Wengeding** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceay3lb63bv4z2df6bkltbbaajeprv6cgncyeeji3ilaoja6gu3f4y 
#### Address 
> f1whhxwushklk2lklqj7yv3lulqphdgnamei4fdfy
#### Datacap Allocated
> 1.25PiB
#### Signer Address
> f1txfsjmix4vlzido4dkildrnbw26owtlbslexmpa
#### Id
> 6cbfa247-e88b-4c54-a136-4a5a0dfe5bea
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceay3lb63bv4z2df6bkltbbaajeprv6cgncyeeji3ilaoja6gu3f4y

**Comment by cryptowhizzard** [comment]
No data sampling has been done because nothing is retrievable.

This client is actively stalling http retrievals and blocked http ranged requests with a reverse proxy to prevent it's data being investigated.

It works as follows:

One set's a bandwidth limit with NGINX on the HTTP retrieval. After a random certain amount the limit is set to zero. This makes the transfer timeout. Because range retrieval is disabled in NGINX one cannot pick up where he left and needs to start all over again. 

Log can be found at http://datasetcreators.com/downloadedcarfiles/logs/1997.log

**Comment by cryptowhizzard** [comment]
<img width="674" alt="Scherm­afbeelding 2023-08-09 om 16 53 28" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/36404435/8e0aff01-ed03-463e-975b-f20d1a46b543">

**Comment by Inayatullah199** [comment]
So that's the reason you've been leaving so many same messages everywhere!

https://filecoinproject.slack.com/archives/C01DLAPKDGX/p1690606951304359

**Comment by Inayatullah199** [comment]
@cryptowhizzard 

You didn't check for your program, and just blame others.

**You just want to remove others from the reach of your benefits.** 

WE DONT SET A BANDWIDTH LIMIT WITH NGINX ON THE HTTP RETRIEVAL!!

**Comment by raghavrmadya** [comment]
DC removal proposed passed. All signing must stop - https://github.com/filecoin-project/notary-governance/issues/944

**Comment by Inayatullah199** [comment]
Hi @raghavrmadya Can you share why you were comfortable passing this obvious gaslighting propose without any your own confirmation? 

![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/130740851/e79abaa4-535b-468d-a1ab-6a7b682c509a)
