### ISSUE TITLE
[DataCap Application] Hailiang Education

### ISSUE THREAD

**Issue by jnxc** [filecoin-project/filecoin-plus-large-datasets#20]
# Large Dataset Notary Application

To apply for a DataCap allocation for your dataset, please fill out the following information.

## Core Information
- Organization Name: Hailiang Mingyou Online
- Website / Social Media: https://www.hlestudy.com/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 1.5PiB
- On-chain address for first allocation: f1vykg3elgzoa3lpzf5xo6rbcghzr5ifat757mucq

_Please respond to the questions below in pargraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

## Project details

Share a brief history of your project and organization.
```
"Mingyou Online" is the online education brand of Hailiang Mingyou. It is also the only official online education platform of Hailiang education, the benchmark of private basic education in China. We provides multi-disciplinary and multi-year online excellent courses to enable students to gain knowledge and grow happily.
```
What is the primary source of funding for this project?
```
Hailiang Mingyou has this kind of demand so they can provide funding.
```
What other projects/ecosystem stakeholders is this project associated with?
```
This project is mainly related to the Hailiang Mingyou, but we do not exclude that we will also try other solutions in the future.
```
## Use-case details

Describe the data being stored onto Filecoin
```
We mainly upload some of the student materials, teaching videos, telemarketing data to the Filecoin network.
```
Where was the data in this dataset sourced from?
```
As I described above, our data comes from the available work of teachers and students. We are in the process of compiling this data. We can provide that link if necessary.
```
Can you share a sample of what is in the dataset? A link to a file, an image, a table, etc., are good examples of this. 
```
Of course.
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes, we are going to temporarily store this data at a publicly available address, and no specific permissions are required to view it.
```
What is the expected retrieval frequency for this data?
```
Once a month, this data may only be used as a backup.
```
For how long do you plan to keep this dataset stored on Filecoin? Will this be a permanent archival or a one-time storage deal?
```
I think this will be a permanent archive.
```
## DataCap allocation plan

In which geographies do you plan on making storage deals?
```
We intend to store this data primarily in first-tier cities in mainland China.
```
What is your expected data onboarding rate? How many deals can you make in a day, in a week? How much DataCap do you plan on using per day, per week?
```
We think the amount of data uploaded to the Fielcoin network is around 100 TiB per week.
```
How will you be distributing your data to miners? Is there an offline data transfer process?
```
We may give some large amounts of historical data to miners offline, and some small amounts of new data, which will be transmitted online.
```
How do you plan on choosing the miners with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
Firstly he must have a certain scale to ensure data security, and secondly his team needs to have some development capabilities to support subsequent file retrieval in the Filecoin network.
```
How will you be distributing data and DataCap across miners storing data?
```
We will talk to different miners and of course compare the prices of services between them, and these factors will also determine the distribution ratio between real data and DataCap.
```

**Comment by swatchliu** [comment]
Bytebase would like to support~

**Comment by MRJAVAZHAO** [comment]
I support this one.

**Comment by hopsum** [comment]
Online education really needs encouragement  recently. Good Luck！

**Comment by dannyob** [comment]
Filecoin Foundation approves.

**Comment by Broz221** [comment]
I support this one.

**Comment by DarnellWashington** [comment]
This project sounds good.

**Comment by galen-mcandrew** [comment]
Looks like we are at 5 notaries, looking for 2 more.

**Comment by rayshitou** [comment]
Count me in.

**Comment by ozhtdong** [comment]
Count me in.

**Comment by galen-mcandrew** [comment]
Final list of 7 notaries:

1. @swatchliu  - f1yh6q3nmsg7i2sys7f7dexcuajgoweudcqj2chfi
2. @MRJAVAZHAO - f14gme3f52prtyzk6pblogrdd6b6ivp4swc6qmesi
3. @dannyob - f1k6wwevxvp466ybil7y2scqlhtnrz5atjkkyvm4a
4. @Broz221 - f13vzzb65gr7pjmb2vsfq666epq6lhdbanc4vfopq
5. @DarnellWashington - f1bjdcjxha3ldcstw5zmvkyu3r2p5x2bsm745kgsi
6.  @rayshitou - f136bz32l2hlyad4npmfg5dngcdw3jk3tpcpoz2ja
7. @ozhtdong - f1lwpw2bcv66pla3lpkcuzquw37pbx7ur4m6zvq2a


These notaries cover GCN, Europe, and NA thereby meeting the 3 region requirement.

**Comment by galen-mcandrew** [comment]
## Multisig Notary requested

#### Notary addresses
> f1yh6q3nmsg7i2sys7f7dexcuajgoweudcqj2chfi
> f14gme3f52prtyzk6pblogrdd6b6ivp4swc6qmesi
> f1k6wwevxvp466ybil7y2scqlhtnrz5atjkkyvm4a
> f13vzzb65gr7pjmb2vsfq666epq6lhdbanc4vfopq
> f1bjdcjxha3ldcstw5zmvkyu3r2p5x2bsm745kgsi
> f136bz32l2hlyad4npmfg5dngcdw3jk3tpcpoz2ja
> f1lwpw2bcv66pla3lpkcuzquw37pbx7ur4m6zvq2a


#### Total DataCap requested
> 1.5PiB

#### Expected weekly DataCap usage rate
> 100TiB

**Comment by jnxc** [comment]
Thanks all！ When could we see the update?

**Comment by galen-mcandrew** [comment]
Hi @jnxc , you can see the [notary governance issue here](https://github.com/filecoin-project/notary-governance/issues/219). This issue tracks the request sent to the root key holders, and will get updated as they sign. When approved and the notary is created, the first allocation request can then be made. Thanks!

**Comment by galen-mcandrew** [comment]
Hi @jnxc thanks for your patience here! At this time, we are seeing the LDN created with 1.5PiB ([f01185440](https://filplus.d.interplanetary.one/notaries?filter=f01185440))

I'm not sure who wants to take the lead notary role here. Can one of you decide, and please kick off the first allocation request?

@swatchliu, @MRJAVAZHAO, @dannyob, @Broz221, @DarnellWashington, @rayshitou, @ozhtdong

Total DataCap requested: 1.5PiB

Expected weekly DataCap usage rate: 100TiB

First allocation should be **50TiB**

**Comment by jnxc** [comment]
ok，looking forward to your response!

**Comment by galen-mcandrew** [comment]
@swatchliu has agreed to take on lead notary role here! Thank you! Can you start the first allocation request?

**Comment by swatchliu** [comment]
## DataCap Allocation requested
#### Multisig Notary address
> f01185440
#### Client address
> f1vykg3elgzoa3lpzf5xo6rbcghzr5ifat757mucq
#### DataCap allocation requested
> 50TiB

**Comment by swatchliu** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaeiuxs73v4uv34naybsokciio5h4vhub67w3wm5oehankhcfjls4 
#### Address 
> f1vykg3elgzoa3lpzf5xo6rbcghzr5ifat757mucq
#### Datacap Allocated
> 54975581388800
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaeiuxs73v4uv34naybsokciio5h4vhub67w3wm5oehankhcfjls4

**Comment by swatchliu** [comment]
> @swatchliu has agreed to take on lead notary role here! Thank you! Can you start the first allocation request?

Hi Galen， We have done it

**Comment by galen-mcandrew** [comment]
Great, thanks @swatchliu !

@MRJAVAZHAO, @dannyob, @Broz221, @DarnellWashington, @rayshitou, @ozhtdong 

Can we get 3 more approvals to push this allocation through? Thanks!

**Comment by rayshitou** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedkfjuxg3lesutwdi4ybht5chq3mrko2j52fdxztx27zoefy6xrqe 
#### Address 
> f1vykg3elgzoa3lpzf5xo6rbcghzr5ifat757mucq
#### Datacap Allocated
> 54975581388800
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedkfjuxg3lesutwdi4ybht5chq3mrko2j52fdxztx27zoefy6xrqe

**Comment by MRJAVAZHAO** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced7dogc5veykxybf44llutxdgcw3gl2pjzgikls2tfrrqntr4c7r4 
#### Address 
> f1vykg3elgzoa3lpzf5xo6rbcghzr5ifat757mucq
#### Datacap Allocated
> 54975581388800
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced7dogc5veykxybf44llutxdgcw3gl2pjzgikls2tfrrqntr4c7r4

**Comment by Broz221** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceat742riz2zj4hrvezvcr4x7zzvyoscvjlk77uvwg3ft6zrs3ut5e 
#### Address 
> f1vykg3elgzoa3lpzf5xo6rbcghzr5ifat757mucq
#### Datacap Allocated
> 54975581388800
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceat742riz2zj4hrvezvcr4x7zzvyoscvjlk77uvwg3ft6zrs3ut5e

**Comment by galen-mcandrew** [comment]
Thanks! @jnxc looks like address f1vykg3elgzoa3lpzf5xo6rbcghzr5ifat757mucq has 50 TiB of DataCap at this time! Happy deal sealing

**Comment by jnxc** [comment]
Thanks all. I‘ll arrange the sealing issue!

**Comment by galen-mcandrew** [comment]
rolling to https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/51

**Comment by filplus-checker** [comment]
## DataCap and CID Checker Report[^1]
 - Organization: `Hailiang Mingyou Online`
 - Client: `f1vykg3elgzoa3lpzf5xo6rbcghzr5ifat757mucq`
### Storage Provider Distribution
The below table shows the distribution of storage providers that have stored data for this client.

If this is the first time a provider takes verified deal, it will be marked as `new`.

For most of the datacap application, below restrictions should apply.
 - Storage provider should not exceed 25% of total datacap.
 - Storage provider should not be storing duplicate data for more than 20%.
 - Storage provider should have published its public IP address.
 - All storage providers should be located in different regions.

⚠️ 35.15% of total deal sealed by [f01806248](https://filfox.info/en/address/f01806248) are duplicate data.

⚠️ [f01773193](https://filfox.info/en/address/f01773193) has unknown IP location.

⚠️ [f01250837](https://filfox.info/en/address/f01250837) has unknown IP location.

⚠️ 29.77% of total deal sealed by [f01344987](https://filfox.info/en/address/f01344987) are duplicate data.

⚠️ 28.49% of total deal sealed by [f01770524](https://filfox.info/en/address/f01770524) are duplicate data.

⚠️ [f01770524](https://filfox.info/en/address/f01770524) has unknown IP location.

⚠️ 80.20% of total deal sealed by [f01843749](https://filfox.info/en/address/f01843749) are duplicate data.

⚠️ [f01118499](https://filfox.info/en/address/f01118499) has unknown IP location.

⚠️ [f01610285](https://filfox.info/en/address/f01610285) has unknown IP location.

⚠️ [f0826566](https://filfox.info/en/address/f0826566) has unknown IP location.

| Provider                                                    |                           Location | Total Deals Sealed | Percentage | Unique Data | Duplicate Deals |
| :---------------------------------------------------------- | ---------------------------------: | -----------------: | ---------: | ----------: | --------------: |
| [f01806248](https://filfox.info/en/address/f01806248)       |           Singapore, Singapore, SG |         373.78 TiB |     24.34% |  242.41 TiB |          35.15% |
| [f01773193](https://filfox.info/en/address/f01773193)       |                            Unknown |         192.97 TiB |     12.57% |  191.78 TiB |           0.62% |
| [f01250837](https://filfox.info/en/address/f01250837)       |                            Unknown |         128.78 TiB |      8.39% |  128.78 TiB |           0.00% |
| [f01344987](https://filfox.info/en/address/f01344987)       | Hong Kong, Central and Western, HK |         122.28 TiB |      7.96% |   85.88 TiB |          29.77% |
| [f01770524](https://filfox.info/en/address/f01770524)       |                            Unknown |         110.91 TiB |      7.22% |   79.31 TiB |          28.49% |
| [f01843749](https://filfox.info/en/address/f01843749)       | Hong Kong, Central and Western, HK |          80.00 TiB |      5.21% |   15.84 TiB |          80.20% |
| [f01759195](https://filfox.info/en/address/f01759195)       |           San Jose, California, US |          65.97 TiB |      4.30% |   65.97 TiB |           0.00% |
| [f01773206](https://filfox.info/en/address/f01773206)       |                   Seoul, Seoul, KR |          54.63 TiB |      3.56% |   54.63 TiB |           0.00% |
| [f01707814](https://filfox.info/en/address/f01707814)       |                 Hilliard, Ohio, US |          52.50 TiB |      3.42% |   52.50 TiB |           0.00% |
| [f01707569](https://filfox.info/en/address/f01707569)       |                 Hilliard, Ohio, US |          49.81 TiB |      3.24% |   49.81 TiB |           0.00% |
| [f01118499](https://filfox.info/en/address/f01118499)       |                            Unknown |          38.56 TiB |      2.51% |   38.50 TiB |           0.16% |
| [f01610285](https://filfox.info/en/address/f01610285)       |                            Unknown |          37.81 TiB |      2.46% |   37.81 TiB |           0.00% |
| [f01707840](https://filfox.info/en/address/f01707840)`new`  |           San Jose, California, US |          35.19 TiB |      2.29% |   34.97 TiB |           0.62% |
| [f01759262](https://filfox.info/en/address/f01759262)       |           San Jose, California, US |          29.75 TiB |      1.94% |   29.75 TiB |           0.00% |
| [f01653777](https://filfox.info/en/address/f01653777)       |                 Hilliard, Ohio, US |          25.00 TiB |      1.63% |   25.00 TiB |           0.00% |
| [f01578658](https://filfox.info/en/address/f01578658)       |           San Jose, California, US |          23.00 TiB |      1.50% |   23.00 TiB |           0.00% |
| [f01707592](https://filfox.info/en/address/f01707592)       |                 Hilliard, Ohio, US |          20.41 TiB |      1.33% |   20.41 TiB |           0.00% |
| [f01841134](https://filfox.info/en/address/f01841134)       |           Singapore, Singapore, SG |          18.34 TiB |      1.19% |   14.78 TiB |          19.42% |
| [f01578721](https://filfox.info/en/address/f01578721)       |           San Jose, California, US |          18.00 TiB |      1.17% |   18.00 TiB |           0.00% |
| [f01654290](https://filfox.info/en/address/f01654290)       |                 Hilliard, Ohio, US |          10.00 TiB |      0.65% |   10.00 TiB |           0.00% |
| [f01674967](https://filfox.info/en/address/f01674967)       |                 Hilliard, Ohio, US |          10.00 TiB |      0.65% |   10.00 TiB |           0.00% |
| [f01674728](https://filfox.info/en/address/f01674728)       |                 Hilliard, Ohio, US |           9.97 TiB |      0.65% |    9.97 TiB |           0.00% |
| [f01675012](https://filfox.info/en/address/f01675012)       |                 Hilliard, Ohio, US |           9.97 TiB |      0.65% |    9.94 TiB |           0.31% |
| [f0826566](https://filfox.info/en/address/f0826566)         |                            Unknown |           6.63 TiB |      0.43% |    6.63 TiB |           0.00% |
| [f01707292](https://filfox.info/en/address/f01707292)       |           San Jose, California, US |           5.00 TiB |      0.33% |    5.00 TiB |           0.00% |
| [f0688935](https://filfox.info/en/address/f0688935)         |               Chengdu, Sichuan, CN |           4.38 TiB |      0.28% |    4.38 TiB |           0.00% |
| [f01654088](https://filfox.info/en/address/f01654088)       |               Boardman, Oregon, US |           2.00 TiB |      0.13% |    2.00 TiB |           0.00% |
| [f054464](https://filfox.info/en/address/f054464)           | Hong Kong, Central and Western, HK |          32.00 GiB |      0.00% |   32.00 GiB |           0.00% |

![Provider Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/20/1671091410078.png)
### Deal Data Replication
The below table shows how each many unique data are replicated across storage providers.
- No more than 25% of unique data are stored with less than 4 providers.

⚠️ 100.00% of deals are for data replicated across less than 4 storage providers.

| Unique Data Size | Total Deals Made | Number of Providers | Deal Percentage |
| ---------------: | ---------------: | ------------------: | --------------: |
|         1.17 PiB |         1.39 PiB |                   1 |          92.52% |
|        32.44 TiB |       112.22 TiB |                   2 |           7.31% |
|       576.00 GiB |         2.59 TiB |                   3 |           0.17% |

![Replication Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/20/1671091410711.png)
### Deal Data Shared with other Clients
The below table shows how many unique data are shared with other clients.
Usually different applications owns different data and should not resolve to the same CID.

⚠️ CID sharing has been observed.

| Other Client                                                                                                                                                                                                              | Application                                                                                                                    | Total Deals Affected | Unique CIDs |        Verifier |
| :------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ | :----------------------------------------------------------------------------------------------------------------------------- | -------------------: | ----------: | --------------: |
| [f1vbe7ze5yknpgu3orinv4zu4rkofsyqfsmpejpui](https://filfox.info/en/address/f1vbe7ze5yknpgu3orinv4zu4rkofsyqfsmpejpui)                                                                                                     | [HELIOS](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/305)                                          |           140.72 TiB |       1,737 | LDN v3 multisig |
| [f3xffjctbyy7zigopfa3za5ha3pvv4z3xfghlw7kw<br/>vyeuabkg4lzsgfwhnghwkvmmvi6yso6k52hq3ca6c<br/>kveq](https://filfox.info/en/address/f3xffjctbyy7zigopfa3za5ha3pvv4z3xfghlw7kwvyeuabkg4lzsgfwhnghwkvmmvi6yso6k52hq3ca6ckveq) | [Chengdu Digital Media Industry Base Co\., Ltd\.](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/387) |           111.19 TiB |       1,543 | LDN v3 multisig |
| [f1wr6rwwqckh6um2hynaym2t4mniev5b675kbf5ni](https://filfox.info/en/address/f1wr6rwwqckh6um2hynaym2t4mniev5b675kbf5ni)                                                                                                     | [Ctrip Global Shopping](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/303)                           |            92.97 TiB |       1,153 | LDN v3 multisig |
| [f3rncwz3qo2bwnsrfjc7kq53xr7yi2lctcydtllxo<br/>zmszndvttou7n565yb6aqssvn4omyf5m7q62qpfmq<br/>cbwq](https://filfox.info/en/address/f3rncwz3qo2bwnsrfjc7kq53xr7yi2lctcydtllxozmszndvttou7n565yb6aqssvn4omyf5m7q62qpfmqcbwq) | [VillageOne Space LLCVillageOne Space LLC](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/39)         |            67.97 TiB |         868 |        LDN # 39 |
| [f1xnypvbq2f5xbz5u4gzrgdmpz6kak4bmnfk7i2vq](https://filfox.info/en/address/f1xnypvbq2f5xbz5u4gzrgdmpz6kak4bmnfk7i2vq)                                                                                                     | [Contentos Foundation Ltd\.](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/67)                       |            49.38 TiB |       1,180 |        LDN # 67 |
| [f3q7ablez3jqkcjukwbzaql7lmbx4ldouu66nexpd<br/>cfvu6kgho3v6gricckt77cgr46tdre2l4zmvha7bs<br/>u7qq](https://filfox.info/en/address/f3q7ablez3jqkcjukwbzaql7lmbx4ldouu66nexpdcfvu6kgho3v6gricckt77cgr46tdre2l4zmvha7bsu7qq) | `MatrixStorage`                                                                                                                |            31.41 TiB |         570 |        LDN # 72 |
| [f1quofpadzcqlonmz7v3mv7dfqvm5hdztucdsjqsy](https://filfox.info/en/address/f1quofpadzcqlonmz7v3mv7dfqvm5hdztucdsjqsy)                                                                                                     | [HENAN 863 SOFTWARE CO\., LTD](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/468)                    |            30.75 TiB |          96 | LDN v3 multisig |
| [f1shup6au4uqrx77ek2bpstqh4yk7plmc34vprroa](https://filfox.info/en/address/f1shup6au4uqrx77ek2bpstqh4yk7plmc34vprroa)                                                                                                     | [GW Technology Co\. , Ltd\.](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/68)                       |            27.56 TiB |         746 |        LDN # 68 |
| [f1csetl7nor3qie2cehx7axf2ai3nedmowj53xwsa](https://filfox.info/en/address/f1csetl7nor3qie2cehx7axf2ai3nedmowj53xwsa)                                                                                                     | [NOAA GOES\-\-\-Piero](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1112)                           |            22.13 TiB |         135 | LDN v3 multisig |
| [f1bb2z36lpq3pnwiiowiraagpzqnpow4bonjacx7a](https://filfox.info/en/address/f1bb2z36lpq3pnwiiowiraagpzqnpow4bonjacx7a)                                                                                                     | [Hola Space](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/362)                                      |            21.81 TiB |          70 | LDN v3 multisig |
| [f1znd7uramgqquelcgefo5xgozopd3nga73hhywpy](https://filfox.info/en/address/f1znd7uramgqquelcgefo5xgozopd3nga73hhywpy)                                                                                                     | [BotSmart ](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/373)                                       |            20.94 TiB |         205 | LDN v3 multisig |
| [f1yswits4hd4zu6n2pl7nk7cspcuieuzl7btjn5ia](https://filfox.info/en/address/f1yswits4hd4zu6n2pl7nk7cspcuieuzl7btjn5ia)                                                                                                     | [TaoPaiPai](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/54)                                        |            18.22 TiB |         356 |        LDN # 54 |
| [f1kvffnugu5j2fjjuispqr2y7bzmmtrvj6hk32xoq](https://filfox.info/en/address/f1kvffnugu5j2fjjuispqr2y7bzmmtrvj6hk32xoq)                                                                                                     | [Unicom\-for new round application](https://github.com/filecoin-project/filecoin-plus-client-onboarding/issues/1808)           |            15.13 TiB |         166 |     Zhehao Chen |
| [f1fq6abg47ifgeee2z7q2rps3tvknoo2ztcoqy7ai](https://filfox.info/en/address/f1fq6abg47ifgeee2z7q2rps3tvknoo2ztcoqy7ai)                                                                                                     | [DaYe Art Tuition Class \(DKArt\) ](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/888)               |            12.59 TiB |          87 | LDN v3 multisig |
| [f1cf2pp6bgu6vvxfuau6bsmiibhrc7v3gvjsyseay](https://filfox.info/en/address/f1cf2pp6bgu6vvxfuau6bsmiibhrc7v3gvjsyseay)                                                                                                     | [Public Data\-FlyBrain](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1013)                          |            11.66 TiB |          71 | LDN v3 multisig |
| [f1ugo3abkmmb4pb2atxz5oqqgwsd27b4p6k52f2va](https://filfox.info/en/address/f1ugo3abkmmb4pb2atxz5oqqgwsd27b4p6k52f2va)                                                                                                     | [Yuepass Technology Company Limited](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/429)              |             9.59 TiB |         125 | LDN v3 multisig |
| [f127l5waa4pw6k3sm4e7wxevc4fe5uz7dyt4mxa3i](https://filfox.info/en/address/f127l5waa4pw6k3sm4e7wxevc4fe5uz7dyt4mxa3i)                                                                                                     | `Pangod`                                                                                                                       |             7.66 TiB |          90 | LDN v3 multisig |
| [f1ibuglt2lzlyf7vnmtzmuykcfgl2pn2fxym5dibi](https://filfox.info/en/address/f1ibuglt2lzlyf7vnmtzmuykcfgl2pn2fxym5dibi)                                                                                                     | [Appstest](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/346)                                        |             7.66 TiB |          87 | LDN v3 multisig |
| [f1a2rdwwor3kq6mv7nveuxhux7rxtj6iyjs7hfswa](https://filfox.info/en/address/f1a2rdwwor3kq6mv7nveuxhux7rxtj6iyjs7hfswa)                                                                                                     | [Worldkan](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/902)                                        |             7.41 TiB |          47 | LDN v3 multisig |
| [f1tmuircaaenwvffdmyuydcqlidfxvgvg2wsj344i](https://filfox.info/en/address/f1tmuircaaenwvffdmyuydcqlidfxvgvg2wsj344i)                                                                                                     | [Myserver](https://github.com/filecoin-project/filecoin-plus-client-onboarding/issues/447)                                     |             5.44 TiB |         139 |    Tim Williams |
| [f1qnhjr2kq742poi6rukv5hji5rdrtuqsib7khz3a](https://filfox.info/en/address/f1qnhjr2kq742poi6rukv5hji5rdrtuqsib7khz3a)                                                                                                     | [GLOBAL UNIT\-A Corp\.](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/110)                           |             5.34 TiB |          85 |       LDN # 110 |
| [f1avfkllpeqlx32bwjcka6y27scftpl5nzh754yly](https://filfox.info/en/address/f1avfkllpeqlx32bwjcka6y27scftpl5nzh754yly)                                                                                                     | ``                                                                                                                             |             2.53 TiB |          34 |     Zhehao Chen |
| [f1k2pbx376s46c72ouwrg2avyvrglj66u76opbsqa](https://filfox.info/en/address/f1k2pbx376s46c72ouwrg2avyvrglj66u76opbsqa)                                                                                                     | [aifabot inc](https://github.com/filecoin-project/filecoin-plus-client-onboarding/issues/566)                                  |           928.00 GiB |          13 |    Dr. Ann Shin |
| [f1rkmhotssjif6ucrosls7oewjz6pr2v2eygfjyui](https://filfox.info/en/address/f1rkmhotssjif6ucrosls7oewjz6pr2v2eygfjyui)                                                                                                     | `Weipaitang`                                                                                                                   |           672.00 GiB |           7 | LDN v3 multisig |
| [f3u3unadf654vezf62cd4jo6r7h6qpkx26g5amcdc<br/>3oe6rmpmk2nfosfd2kjkdhj4ndvr626gsm7fhpmt7<br/>gg2q](https://filfox.info/en/address/f3u3unadf654vezf62cd4jo6r7h6qpkx26g5amcdc3oe6rmpmk2nfosfd2kjkdhj4ndvr626gsm7fhpmt7gg2q) | [Runtu Information Technology](https://github.com/filecoin-project/filecoin-plus-client-onboarding/issues/1150)                |           480.00 GiB |           7 |       Steven Li |
| [f1fi7vzu266bh7yxsygw6scl2hjltdkhfb6nyzn3a](https://filfox.info/en/address/f1fi7vzu266bh7yxsygw6scl2hjltdkhfb6nyzn3a)                                                                                                     | [Jiliantech](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/190)                                      |           448.00 GiB |          14 |       LDN # 190 |
| [f1tgii4xgcp6um4n2w7eqaw6bwvnvyii2u7cjgzka](https://filfox.info/en/address/f1tgii4xgcp6um4n2w7eqaw6bwvnvyii2u7cjgzka)                                                                                                     | [Meson\.Network ](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/187)                                 |           160.00 GiB |           1 | LDN v3 multisig |

[^1]: To manually trigger this report, add a comment with text `checker:manualTrigger`
