### ISSUE TITLE
[DataCap Application] <Zetacube Inc> - <Common Crawl March/April 2020>

### ISSUE THREAD

**Issue by HoonChoi-Zetacube** [filecoin-project/filecoin-plus-large-datasets#2003]
### Data Owner Name

Common Craw

### What is your role related to the dataset

Data Preparer

### Data Owner Country/Region

United States

### Data Owner Industry

Other

### Website

https://commoncrawl.org/2020/04/march-april-2020-crawl-archive-now-available/

### Social Media

```text
none
```

### Total amount of DataCap being requested

1PiB

### Expected size of single dataset (one copy)

100TiB

### Number of replicas to store

10

### Weekly allocation of DataCap requested

300TiB

### On-chain address for first allocation

f1zipn5azwmajph7xtuspiac234jyanbrqovlgusa

### Data Type of Application

Slingshot

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Zetacube Inc is a 'Ultra-high-capacity decentralized storage hyper server solution company' in the Web 3.0 era, established to research and commercialize the IPFS storage system, an innovative technology for safely storing huge data in the 4th industrial age.
Also, Zetacube Inc is participant in the Slingshot V3, both as DP and SP.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
The crawl archive for March/April 2020 is now available! It contains 2.85 billion web pages or 280 TiB of uncompressed content, crawled between March 28th and April 10th. It includes page captures of 1 billion URLs unknown in any of our prior crawl archives.
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### How do you plan to prepare the dataset

singularity

### Please share a sample of the data

```text
https://commoncrawl.org/2020/04/march-april-2020-crawl-archive-now-available/
https://data.commoncrawl.org/crawl-data/CC-MAIN-2020-16/index.html
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Monthly

### For how long do you plan to keep this dataset stored on Filecoin

2 to 3 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, Africa, North America, South America, Europe, Australia (continent)

### How will you be distributing your data to storage providers

HTTP or FTP server, IPFS, Shipping hard drives

### How do you plan to choose storage providers

Slack, Big Data Exchange, Partners

### If you already have a list of storage providers to work with, fill out their names and provider IDs below

```text
f0838467
f01227505
f01942239
f01695888
f01823110
f01103160
```

### How do you plan to make deals to your storage providers

Boost client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/105098820/8cd3aa51-c7f9-4ad0-8725-bc50f772745b)
There is just no more than 100 TB data.

Is this page related with your product?
![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/105098820/88ae6948-0054-48eb-8447-046cfbd287e7)

Can you provide more information about Zetacube Inc. , such as website, social media, related links?

**Comment by HoonChoi-Zetacube** [comment]
This dataset is what we claimed on Slingshot.
Caro said DP should file LDN applications to the claimed dataset to require Data cap.
On Slingshot, you can see that a large number of data sets do not exceed 100 TiB.

My compay website is https://www.zetacube.net/

We claimed three datasets, and #1991 is one of them.
#1991 and #2003 are different datasets, so I filed each application.

<img width="792" alt="스크린샷 2023-05-21 060421" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/129706575/0feaa796-8516-43ca-8a03-b34dfa93666d">

**Comment by Sunnyiscoming** [comment]
> Total amount of DataCap being requested
> 3PiB

This is not reasonable. Please check it again.

**Comment by HoonChoi-Zetacube** [comment]
> > Total amount of DataCap being requested
> > 3PiB
> 
> This is not reasonable. Please check it again.

I changed the total amount of DataCap to 1TiB. 
Thank you.

**Comment by HoonChoi-Zetacube** [comment]
We are still waiting for the notaries to sign off. We have already completed the CAR file generation for this dataset and once the DataCap is allocated, we can proceed directly to the onboarding process.

**Comment by HoonChoi-Zetacube** [comment]
We are still waiting for the notaries to sign off. We have already completed the CAR file generation for this dataset and once the DataCap is allocated, we can proceed directly to the onboarding process.

As you can see in #2025, on the advice of @kevzak, I changed the application title, which resulted in the 'governance review needed' label. I hope a governance team member will remove this label. I believe this label prevents me from being allocated Datacap.

**Comment by cryptowhizzard** [comment]
Hi @HoonChoi-Zetacube 

The reason we can't sign of is because all the SP's your mention are located in Korea itself

> f0838467
> f01227505
> f01942239
> f01695888
> f01823110
> f01103160

You can find the Fil+ rules and guidelines here: https://github.com/filecoin-project/filecoin-plus-large-datasets

> Best practice for storing large datasets includes ideally, storing it in 3 or more regions, with 4 or more storage provider operators or owners, and having at least 5 replicas of the dataset. No more than one replica should be stored with one SP ID, and if the data cannot leave a particular geographic boundary, then it is expected that replication will still happen across different locations (cities, datacenters, etc.). Each storage provider should not exceed 30% of the total datacap that the client was allocated and the storage provider should have published its public IP address. If you cannot follow these practices due to policy or any other issues, you may explain your case in the application and provide to the community what method you can do instead. These are recommendations and not strict rules that every client must follow.

**Comment by cryptowhizzard** [comment]
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1991#issuecomment-1612310838
