### ISSUE TITLE
[DataCap Application] <Shenzhen Fingertip Culture Media Co., Ltd> - <The art of painting>

### ISSUE THREAD

**Issue by zhijianwenhua** [filecoin-project/filecoin-plus-large-datasets#2005]
### Data Owner Name

Shenzhen Fingertip Culture Media Co., Ltd

### What is your role related to the dataset

Dataset Owner

### Data Owner Country/Region

China

### Data Owner Industry

Arts & Recreation

### Website

https://www.qcc.com/firm/576f636e066245ce0fc18fc0d971b5f8.html

### Social Media

```text
https://www.qcc.com/firm/576f636e066245ce0fc18fc0d971b5f8.html
```

### Total amount of DataCap being requested

5PiB

### Expected size of single dataset (one copy)

500t

### Number of replicas to store

10

### Weekly allocation of DataCap requested

800TiB

### On-chain address for first allocation

f1bgesx2oqpvrqd2l5tigpiji6ker3wabmyjdadoy

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Computer and network system technology development; Supply chain channel design, logistics scheme design; Technology development, technical consultation, technical service and technology transfer in the field of e-card, e-business card, digital technology, textile technology and printing; Digital electronic products, photographic equipment, photographic equipment, mechanical and electrical products, mechanical equipment, office supplies, printing equipment.Domestic trade; Operate import and export business. Organize cultural and artistic exchange activities; advertising production; Advertising design, agency; software development; Technical services, technology development, technical consultation, technology exchange, technology transfer, technology promotion; Graphic design
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
Drawing/painting is an art form that involves teaching beginners who are interested in the hobby, sharing painting/drawing skills with peers and amateurs, and exploring painting/drawing techniques together. It aims to inspire and educate beginners who have an interest in painting/drawing.
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### How do you plan to prepare the dataset

singularity

### Please share a sample of the data

```text
https://www.aliyundrive.com/s/VCq2pKM2fEF
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Monthly

### For how long do you plan to keep this dataset stored on Filecoin

More than 3 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, South America, Europe

### How will you be distributing your data to storage providers

HTTP or FTP server, Shipping hard drives

### How do you plan to choose storage providers

Slack, Big Data Exchange

### How do you plan to make deals to your storage providers

Boost client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
Where are these data from?
Can you provide more information and materials to prove that you have 5 PB data already?

> Our data comes from the accumulation of years of work in our company.
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1994#issuecomment-1549760313
There is no related news about your company. It make me can not believe that you have such a large amount of datasets.

**Comment by zhijianwenhua** [comment]
Our data comes from several of our own companies, such as Guangzhou Deli Industrial Development Co., Ltd., and Shenzhen Zhongyue Cloud Creative Technology Co., Ltd., where artists and members from these companies have created a large number of artistic works. Additionally, our companies often organize various cultural and entertainment activities, such as painting and dancing events. Of course, I can provide the business licenses of these companies to prove that they belong to us.
There is a lot of this data that needs to be stored: https://www.aliyundrive.com/s/yevXaPoV8Ki
Of course, I can also provide screenshots of the local disk in the server and the environment of the computer room

**Comment by Sunnyiscoming** [comment]
Guangzhou Deli Industrial Development Co., Ltd., and Shenzhen Zhongyue Cloud Creative Technology Co., Ltd.,
Can you provide Chinese name and website of these two organizations? 
Could you send an email to filplus-app-review@fil.org with these two organizations' official domain in order to confirm your identity? Email name should includes the issue id #2005.

**Comment by zhijianwenhua** [comment]
@Sunnyiscoming 广州市德力产业发展有限公司，深圳中悦云创科技有限公司
We don't have official websites for these two companies, and we can provide business licenses to prove our identity.

**Comment by zhijianwenhua** [comment]
@Sunnyiscoming Hello! This is the data we have prepared.
![sj](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/133762784/b9fce910-f3c5-40ef-9b86-a7730da79459)

**Comment by zhijianwenhua** [comment]
@Sunnyiscoming Sent, please check

**Comment by zhijianwenhua** [comment]
![9N{P6OHHX%R 9(2KVUJYE@Y](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/133762784/f93f9761-96f1-445a-ab8e-c7f6fea978fb)

**Comment by Sunnyiscoming** [comment]
I have received that. 
### Datacap Request Trigger
**Total DataCap requested**
> 5PiB

**Expected weekly DataCap usage rate**
> 800TiB

**Client address**
>f1bgesx2oqpvrqd2l5tigpiji6ker3wabmyjdadoy

**Comment by woshidama323** [comment]
LGTM

**Comment by woshidama323** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedvmp7yjbbpmbqf2kadnkg7ubz2oydsr7ixtqbypwxoss7pelqcfk 
#### Address 
> f1bgesx2oqpvrqd2l5tigpiji6ker3wabmyjdadoy
#### Datacap Allocated
> 256.00TiB
#### Signer Address
> f12tk3adljauwnd3hjbigpfxb7b7gdlj63p6afwtq
#### Id
> 409c695f-79c7-4d12-be9d-d4dc8900c218
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedvmp7yjbbpmbqf2kadnkg7ubz2oydsr7ixtqbypwxoss7pelqcfk

**Comment by zcfil** [comment]
I have reviewed historical information and am willing to provide support in the first round, and will follow up on the data situation in the later stage

**Comment by zcfil** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecey3oaewgxcp32rrd2u6eaf4rtx7e4v34eg6prek4cd6ipv35hg4 
#### Address 
> f1bgesx2oqpvrqd2l5tigpiji6ker3wabmyjdadoy
#### Datacap Allocated
> 256.00TiB
#### Signer Address
> f1cjzbiy5xd4ehera4wmbz63pd5ku4oo7g52cldga
#### Id
> 409c695f-79c7-4d12-be9d-d4dc8900c218
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecey3oaewgxcp32rrd2u6eaf4rtx7e4v34eg6prek4cd6ipv35hg4

**Comment by Sunnyiscoming** [comment]
checker:manualTrigger

**Comment by zcfil** [comment]
checker:manualTrigger

**Comment by zcfil** [comment]
checker:manualTrigger

**Comment by 1ane-1** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceagb57e564rzitwchflbosxgfsn5ykuiuzfkpku7tooepjds2eeeo 
#### Address 
> f1bgesx2oqpvrqd2l5tigpiji6ker3wabmyjdadoy
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f1mdk7s2vntzm6hu35yuo6vjubtrpfnb2awhgvrri
#### Id
> 390cd9fa-1f99-4d43-8ac7-1e36e1949b69
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceagb57e564rzitwchflbosxgfsn5ykuiuzfkpku7tooepjds2eeeo

**Comment by SuperChaiChai** [comment]
<img width="844" alt="image" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/42091141/e95aa930-0cee-4987-956a-ddd273564019">

**Comment by SuperChaiChai** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebdyqhgti6e5e3a5zdg4nchqj3lqhqptzutj473gvasctmmt4jfko 
#### Address 
> f1bgesx2oqpvrqd2l5tigpiji6ker3wabmyjdadoy
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f12mckci3omexgzoeosjvstcfxfe4vqw7owdia3da
#### Id
> 390cd9fa-1f99-4d43-8ac7-1e36e1949b69
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebdyqhgti6e5e3a5zdg4nchqj3lqhqptzutj473gvasctmmt4jfko

**Comment by psh0691** [comment]
checker:manualTrigger

**Comment by psh0691** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedk6b643v6scblbla3bxoddz4gawf7pnwewcpioed67ayhekrhofq 
#### Address 
> f1bgesx2oqpvrqd2l5tigpiji6ker3wabmyjdadoy
#### Datacap Allocated
> 1.00PiB
#### Signer Address
> f1qdko4jg25vo35qmyvcrw4ak4fmuu3f5rif2kc7i
#### Id
> 22cd1072-86a0-4040-80dd-27251609114e
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedk6b643v6scblbla3bxoddz4gawf7pnwewcpioed67ayhekrhofq

**Comment by maxvint** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced5klbdioccxclxohsqr2s7qbjj2buqqrulafpvm2ffcbu7qvtorm 
#### Address 
> f1bgesx2oqpvrqd2l5tigpiji6ker3wabmyjdadoy
#### Datacap Allocated
> 1.00PiB
#### Signer Address
> f1ui5iy4mmkxjbw7752omiwp2ols2fzv4thrayagi
#### Id
> 22cd1072-86a0-4040-80dd-27251609114e
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced5klbdioccxclxohsqr2s7qbjj2buqqrulafpvm2ffcbu7qvtorm

**Comment by maxvint** [comment]
checker:manualTrigger

**Comment by zhijianwenhua** [comment]
checker:manualTrigger

**Comment by MarshLin88** [comment]
checker:manualTrigger

**Comment by ipollo00** [comment]
@zhijianwenhua Hi there, are you engaging in developing HTTP retrieval to increase the retrieval rate?
