### ISSUE TITLE
[DataCap Application] NOAA Water-Column Sonar Data Archive

### ISSUE THREAD

**Issue by sunLanden** [filecoin-project/filecoin-plus-large-datasets#2006]
### Data Owner Name

NOAA

### What is your role related to the dataset

Data Preparer

### Data Owner Country/Region

United States

### Data Owner Industry

Resources, Agriculture & Fisheries

### Website

https://www.ncei.noaa.gov/products/water-column-sonar-data

### Social Media

```text
https://www.facebook.com/NOAANCEI/
https://www.instagram.com/noaadata/
https://twitter.com/NOAANCEI
```

### Total amount of DataCap being requested

5PiB

### Expected size of single dataset (one copy)

199.7TiB

### Number of replicas to store

10

### Weekly allocation of DataCap requested

800TiB

### On-chain address for first allocation

f1y77vzqlmtv7hc6zcxicu2jqzh766lwgzlej6tti

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
I'm an SP and NOAA is the Nation's leading authority for environmental data, and manage one of the largest archives of atmospheric, coastal, geophysical, and oceanic research in the world. NCEI contributes to the NESDIS mission by developing new products and services that span the science disciplines and enable better data discovery.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
NCEI Water-Column Sonar Data Archive--- Water column sonar data focus on the area from near the surface of the ocean to the seafloor. Primary uses of these specific sonar data include 3-D mapping of fish schools and other mid-water marine organisms; assessing biological abundance; species identification; and habitat characterization. Other uses include mapping underwater gas seeps and remotely monitoring undersea oil spills.
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### How do you plan to prepare the dataset

lotus

### Please share a sample of the data

```text
https://registry.opendata.aws/ncei-wcsd-archive/
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

1.5 to 2 years

### In which geographies do you plan on making storage deals

Asia other than Greater China, North America, Europe

### How will you be distributing your data to storage providers

HTTP or FTP server, Shipping hard drives

### How do you plan to choose storage providers

Slack, Filmine, Big Data Exchange

### If you already have a list of storage providers to work with, fill out their names and provider IDs below

```text
in the progress
```

### How do you plan to make deals to your storage providers

Lotus client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by sunLanden** [comment]
@Sunnyiscoming Hello, my previous application is https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1960, please approve this application which is a substitute of #1960

**Comment by Meibuy** [comment]
The applicant reached me on Slack and willing to support its first allocation.

**Comment by Meibuy** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceccu2j7lj5nzpf736ofavrqimg3num6q2z63brzcs32olycxetkva 
#### Address 
> f1y77vzqlmtv7hc6zcxicu2jqzh766lwgzlej6tti
#### Datacap Allocated
> 256.00TiB
#### Signer Address
> f1bwugfihrmn3iyunzyxst5nttql3dge4khwmurtq
#### Id
> ccdab9ac-cb92-45af-9e66-a0543e485538
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceccu2j7lj5nzpf736ofavrqimg3num6q2z63brzcs32olycxetkva

**Comment by Casey-PG** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedi3l4py47g2tsm5regoo7qfzm7xxx63u6wfklzf3kbnctb2mzzo2 
#### Address 
> f1y77vzqlmtv7hc6zcxicu2jqzh766lwgzlej6tti
#### Datacap Allocated
> 256.00TiB
#### Signer Address
> f1d4yb3wags3mtddzesxoo63jv7dmlec3bq4yteni
#### Id
> ccdab9ac-cb92-45af-9e66-a0543e485538
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedi3l4py47g2tsm5regoo7qfzm7xxx63u6wfklzf3kbnctb2mzzo2

**Comment by Casey-PG** [comment]
Public dataset with reasonable distrubtion plan. I am willing to support the first round and will check the following updates.

**Comment by Sunnyiscoming** [comment]
checker:manualTrigger

**Comment by TakiChain** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebonqjxlric4zk4uwfwhonkgo6ubnyjfpb356uwqj4i6rv2ha24xw 
#### Address 
> f1y77vzqlmtv7hc6zcxicu2jqzh766lwgzlej6tti
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f15impf3j2zcaex4lhyxndxswuuhv24vzstuqtxsi
#### Id
> c30034a9-186e-4cac-bd65-5f835df66b4b
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebonqjxlric4zk4uwfwhonkgo6ubnyjfpb356uwqj4i6rv2ha24xw

**Comment by Aifabot-Cloud** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceclkff3w6uonvy5fpklbq5z2reo2ovkdppclxheuyfary3qkj3nhw 
#### Address 
> f1y77vzqlmtv7hc6zcxicu2jqzh766lwgzlej6tti
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f174fg3bqbln3zjnkxtyf6s54txqkr7yqkj6cig7y
#### Id
> c30034a9-186e-4cac-bd65-5f835df66b4b
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceclkff3w6uonvy5fpklbq5z2reo2ovkdppclxheuyfary3qkj3nhw

**Comment by spaceT9** [comment]
checker:manualTrigger

**Comment by cryptowhizzard** [comment]
@sunLanden 

The FIL+ rules state that your data needs to be retrievable. You data is not, thus notary's can't sign on the next applications.
Are you going to fix this or will you close this application?

**Comment by cryptowhizzard** [comment]
checker:manualTrigger

**Comment by cryptowhizzard** [comment]
@sunLanden 

None of the data is retrievable. If you don't intend to make it retrievable then please close this issue.

**Comment by sunLanden** [comment]
checker:manualTrigger

**Comment by sunLanden** [comment]
![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/130341980/84261f92-3ecf-4391-aec0-ce207d069077)

It is supporting retrieval.

**Comment by cryptowhizzard** [comment]
The HTTP retrieval statistics are unreliable at the moment. See Slack.

**Comment by cryptowhizzard** [comment]
Can you tell me what SP's i should use your retrieval? According to my system the used SP's have been flagged.

Http retrievals have been skewed last week and cannot be used as metric. This is a known issue and has been posted on slack. It's WIP.

![Scherm­afbeelding 2023-07-31 om 12 42 57](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/36404435/37e56897-a315-4e5d-898d-d7ef76d28fc0)

**Comment by sunLanden** [comment]
@cryptowhizzard Is there any possible that your system need to update or fix？Your data is not the latest data.

**Comment by cryptowhizzard** [comment]
@sunLanden 

I am alway reachable for feedback. Can you please explain why you think my data is not up to date? We fetch it from protocol labs ( datacapstats.io ).

Thanks.

**Comment by Wengeding** [comment]
checker:manualTrigger

**Comment by Wengeding** [comment]
Report looks health. The inability of some nodes to retrieve is permissible. We want to focus on the general retrieval success rate that can't be below 1%.

**Comment by Wengeding** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecjn4puaba4ylwcdeehiwxihr45sapc5b7lh2yr643jyt4w7y6u6c 
#### Address 
> f1y77vzqlmtv7hc6zcxicu2jqzh766lwgzlej6tti
#### Datacap Allocated
> 1.00PiB
#### Signer Address
> f1txfsjmix4vlzido4dkildrnbw26owtlbslexmpa
#### Id
> be33b547-c429-46f0-9658-02a3af2cc4c2
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecjn4puaba4ylwcdeehiwxihr45sapc5b7lh2yr643jyt4w7y6u6c

**Comment by AthSmith** [comment]
checker:manualTrigger

**Comment by AthSmith** [comment]
Judging from previous communication and the updated CID report, willing to support.

**Comment by AthSmith** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceabwx6sudsynxfupwbuv74o6mlodgz4dmiyqiegumccpxqktlms6i 
#### Address 
> f1y77vzqlmtv7hc6zcxicu2jqzh766lwgzlej6tti
#### Datacap Allocated
> 1.00PiB
#### Signer Address
> f1vxbqrf7rfum3n6m5u6eb4re6xj7amvsaqnzu64y
#### Id
> be33b547-c429-46f0-9658-02a3af2cc4c2
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceabwx6sudsynxfupwbuv74o6mlodgz4dmiyqiegumccpxqktlms6i

**Comment by cryptowhizzard** [comment]
<img width="676" alt="Scherm­afbeelding 2023-08-09 om 17 03 53" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/36404435/bf36de5d-4b78-4071-8c76-33bdf378f664">

**Comment by raghavrmadya** [comment]
Hi everyone, please note that https://github.com/filecoin-project/notary-governance/issues/895 was passed. @cryptowhizzard is not making these rules himself. 

If you don't agree and did not get a chance to provide your input in 895, kindly open an issue to revert it but until then, applications under dispute must not be signed.

**Comment by Wengeding** [comment]
Hi @raghavrmadya 
As far as i know, bandwidth operators from Asia, especially China, often do bandwidth limitations on unusual access from abroad to prevent suspected DDOS attacks that would be gonna clog up the shared bandwidth seriously. This security policy becomes easier to activate if the node chooses to buy a smaller bandwidth. 

However, if a small amount of data is downloaded for a short period of time for testing, these reports will appear normal.

One possible improved solution could be to suggest SP nodes to buy larger bandwidth services or buy double or triple backup bandwidth, but that might be more costly.

Not sure if this info would be helpful in adjudicating similar situations. Thank you!

**Comment by sunLanden** [comment]
@Wengeding Thanks again for your pertinent comments.

After checking with SPs, there's no problem about this application. Ongoing support retrieval. @raghavrmadya Can my application be removed from the dispute form?

**Comment by cryptowhizzard** [comment]
No, it cannot.

From the part of data that i managed to download i did a screening.

http://www.datasetcreators.com/downloadedcarfiles/httpretrievals/2006-f02204621-f02252118-48979839-baga6ea4seaqgexffnbq7komjthtuznl6at64ezmndar4kchc5ppbkxsvai2lkgy 

doing a hexdump -C 2006-f02204621-f02252118-48979839-baga6ea4seaqgexffnbq7komjthtuznl6at64ezmndar4kchc5ppbkxsvai2lkgy 

results in:

![Scherm­afbeelding 2023-08-28 om 12 55 02](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/36404435/5977f914-206f-4886-9db2-387676332234)

You are storing garbage, no more, no less.

**Comment by cryptowhizzard** [comment]
@raghavrmadya 

Please update the dispute that apart from the malfunction on retrieval this applicant is storing garbage and not the data he promised to store in this LDN.

Datacap should be removed and this LDN should be permanently closed.

**Comment by raghavrmadya** [comment]
The dispute on this application has been open for a long time and the client has not responded to community concerns. The T&T WG recommends pausing all signing until client addresses the concerns directly. No clear response addressing the dispute  in the next 7 days will result in closure of application and removal of DC

Dispute - https://www.notion.so/filecoin/Abuse-DC-no-retrieval-52d113d7dd3d403d944df7a99d0f064e?pvs=4

**Comment by raghavrmadya** [comment]
No response from client. Closing application and requesting DC removal
