### ISSUE TITLE
[DataCap Application] GEFS Re-forecast

### ISSUE THREAD

**Issue by Killianxuan** [filecoin-project/filecoin-plus-large-datasets#2011]
### Data Owner Name

NOAA

### What is your role related to the dataset

Data Preparer

### Data Owner Country/Region

United States

### Data Owner Industry

Environment

### Website

http://www.noaa.gov/

### Social Media

```text
https://twitter.com/NOAA
https://www.facebook.com/NOAA
https://www.instagram.com/noaa
```

### Total amount of DataCap being requested

5PiB

### Expected size of single dataset (one copy)

392TiB

### Number of replicas to store

10

### Weekly allocation of DataCap requested

1PiB

### On-chain address for first allocation

f1dsdtj54saufjswcfyp5t3feqe3i6aw5dppxe4va

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
NOAA is an agency that enriches life through science. Our reach goes from the surface of the sun to the depths of the ocean floor as we work to keep the public informed of the changing environment around them. I'm a DP with some experience of distribute data.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
NOAA has generated a multi-decadal reanalysis and reforecast data set to accompany the next-generation version of its ensemble prediction system, the Global Ensemble Forecast System, version 12 (GEFSv12).
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### How do you plan to prepare the dataset

IPFS, lotus, singularity

### Please share a sample of the data

```text
https://registry.opendata.aws/noaa-gefs-reforecast/
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

1.5 to 2 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, Europe

### How will you be distributing your data to storage providers

HTTP or FTP server, IPFS, Shipping hard drives

### How do you plan to choose storage providers

Slack, Big Data Exchange, Partners

### How do you plan to make deals to your storage providers

Lotus client, Singularity

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Killianxuan** [comment]
@Sunnyiscoming We are contacting with sp Doco, Mond in HongKong and I'll continue finding sp in other regions. I'm checking out their technology.

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 5PiB

**Expected weekly DataCap usage rate**
> 1PiB

**Client address**
>f1dsdtj54saufjswcfyp5t3feqe3i6aw5dppxe4va

**Comment by RawTechVentures** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec4bcuvspxifyq4ld7nnng45ydv2w37vy2ec3vkgao4baf6ofsuh2 
#### Address 
> f1dsdtj54saufjswcfyp5t3feqe3i6aw5dppxe4va
#### Datacap Allocated
> 256.00TiB
#### Signer Address
> f1txfsjmix4vlzido4dkildrnbw26owtlbslexmpa
#### Id
> 55759f5d-12bd-4974-a68b-f7c5be6ab587
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec4bcuvspxifyq4ld7nnng45ydv2w37vy2ec3vkgao4baf6ofsuh2

**Comment by AthSmith** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedrpcnh2ngg5nwwkywr3ulrloxwgvniodf4rw2rgzhttpg3tj2rzo 
#### Address 
> f1dsdtj54saufjswcfyp5t3feqe3i6aw5dppxe4va
#### Datacap Allocated
> 256.00TiB
#### Signer Address
> f1vxbqrf7rfum3n6m5u6eb4re6xj7amvsaqnzu64y
#### Id
> 55759f5d-12bd-4974-a68b-f7c5be6ab587
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedrpcnh2ngg5nwwkywr3ulrloxwgvniodf4rw2rgzhttpg3tj2rzo

**Comment by AthSmith** [comment]
The client contacted me by slack and shared the storage plan. I'd like to see more public data joining the network!

**Comment by Sunnyiscoming** [comment]
checker:manualTrigger

**Comment by Killianxuan** [comment]
OK. I'll go on allocating datacap to sps.

**Comment by spaceT9** [comment]
checker:manualTrigger

**Comment by cryptowhizzard** [comment]
Hi,

I want to retrieve this data like you stated in the LDN @Killianxuan 

Your SP's don't have retrieval enabled. Why?

**Comment by Killianxuan** [comment]
@cryptowhizzard SP is in the process of software upgrade and will continue supporting retrieval in the future.

**Comment by spaceT9** [comment]
checker:manualTrigger

**Comment by BobbyChoii** [comment]
LGTM, willing to support! 
Also, try to increase the number of SPs  ASAM.

**Comment by BobbyChoii** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecsl33kf2fwbqkq6szc2rxsjmsrmgwnqkl27ywg7d7vtrcc4ulxye 
#### Address 
> f1dsdtj54saufjswcfyp5t3feqe3i6aw5dppxe4va
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f1irqs2gmctiv3jcdfwuch7oxvf4ixh3k4b2wc24i
#### Id
> 76666268-7556-4002-84e8-8f11e9bc3d92
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecsl33kf2fwbqkq6szc2rxsjmsrmgwnqkl27ywg7d7vtrcc4ulxye

**Comment by herrehesse** [comment]
All selfdealing, @BobbyChoii is going no DD at all.

Please act @raghavrmadya @Kevin-FF-USA @dkkapur

**Comment by Killianxuan** [comment]
@cryptowhizzard  The miner f02207907 can be retrieved successfully. 



![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/131147500/47088ba8-68ac-4dc5-aea3-cddd854e26fe)


@BobbyChoii Thanks for your support!

**Comment by Killianxuan** [comment]
@herrehesse I looked to notaries for help, and Bobby reviewed my application and responded to my request kindly and responsibly. Please do not try to blame others.

**Comment by cryptowhizzard** [comment]
![Scherm­afbeelding 2023-07-26 om 10 13 20](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/36404435/cff61528-fae1-4617-92b8-f0373b9f6e1f)

2 things:
A:) You are indeed right. HTTP retrieval is supported.
B:) The speed is so slow that this won't work. I can't do due diligence on your data. Can you make baga6ea4seaqmbtrigksyggoxcura75xhqscgdp2jfhgbjgpnm67lhu5zeln2goq available somewhere for fast download?

**Comment by Killianxuan** [comment]
Maybe it need check for your network I guess.

**Comment by cryptowhizzard** [comment]
> Maybe it need check for your network I guess.

I checked from different places on the globe, all the same speed.

>> B:) The speed is so slow that this won't work. I can't do due diligence on your data. Can you make baga6ea4seaqmbtrigksyggoxcura75xhqscgdp2jfhgbjgpnm67lhu5zeln2goq available somewhere for fast download?

**Comment by Killianxuan** [comment]
Asking SPs to set up a high-speed download link especially for you, which is obviously unfair to other users and will add unnecessary burden to SPs. In addition, download speed is affected by many factors, we hope you can understand.

**Comment by cryptowhizzard** [comment]
Hello @Killianxuan 

No, i don't understand. Your data must be readily retrievable for *anyone* on the network. These are the rules.
Secondly, i want to do due diligence on your data that you are storing.

**Comment by clriesco** [comment]
Removed stale label and reopened issue :)

**Comment by Killianxuan** [comment]
This picture is not the files we store! Please clarify with yourself.

**Comment by Killianxuan** [comment]
checker:manualTrigger

**Comment by Killianxuan** [comment]
Our application has no relation to what @cryptowhizzard said. And we will find more SPs to store data with the help of more datacap to finish it. Hope notaries help us for signature!

**Comment by Killianxuan** [comment]
![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/131147500/3d8ebe88-aa03-474b-b977-2603e44a39ab)

This is what I've downloaded. We can prove that @cryptowhizzard ‘s result is wrong.

**Comment by cryptowhizzard** [comment]
Dear Killianxuan,

As notary I am doing due diligence on your LDN. I could not get retrieval to work. Can you please upload the car file of CID baga6ea4seaqep4jkrisrurawchd2wvei65vgfarvmaihn4yl47vvkrmlani24dy ?

You can use our upload system at http://send.datasetcreators.com. Please select 7 days for the system to keep the file and post the link you received here so I (and other notaries) can download your content.

**Comment by cryptowhizzard** [comment]
@Killianxuan 

As per above then, prove me wrong and upload the data.

**Comment by Killianxuan** [comment]
> ![image](https://user-images.githubusercontent.com/131147500/265439819-3d8ebe88-aa03-474b-b977-2603e44a39ab.png)
> 
> This is what I've downloaded. We can prove that @cryptowhizzard ‘s result is wrong.

Actually we have proved that cryptowhizzard‘s result is wrong.

**Comment by Casey-PG** [comment]
checker:manualTrigger

**Comment by Casey-PG** [comment]
DD has been done, Deal Data Replication needs to be improved in the next round.
willing to support!

**Comment by Casey-PG** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceckvltvqvp22s5757bwidddvu4fp77xfks4npo2bzknvzg4rdhhcc 
#### Address 
> f1dsdtj54saufjswcfyp5t3feqe3i6aw5dppxe4va
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f1d4yb3wags3mtddzesxoo63jv7dmlec3bq4yteni
#### Id
> 76666268-7556-4002-84e8-8f11e9bc3d92
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceckvltvqvp22s5757bwidddvu4fp77xfks4npo2bzknvzg4rdhhcc

**Comment by Killianxuan** [comment]
Everything's going well.

**Comment by Killianxuan** [comment]
Yes

**Comment by Wengeding** [comment]
LGTM

**Comment by Wengeding** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceboiahvkfqkgtwwjocsowouai6ptsqdpa66slc473kcnzx4rovecu 
#### Address 
> f1dsdtj54saufjswcfyp5t3feqe3i6aw5dppxe4va
#### Datacap Allocated
> 1.00PiB
#### Signer Address
> f1txfsjmix4vlzido4dkildrnbw26owtlbslexmpa
#### Id
> 734481ee-170f-4773-89ef-9c199d6dc484
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceboiahvkfqkgtwwjocsowouai6ptsqdpa66slc473kcnzx4rovecu

**Comment by TakiChain** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecedkdrdy2cdesgo7lokzdh4fterxymtdjsvxp3t5i5rje4wcu65k 
#### Address 
> f1dsdtj54saufjswcfyp5t3feqe3i6aw5dppxe4va
#### Datacap Allocated
> 1.00PiB
#### Signer Address
> f15impf3j2zcaex4lhyxndxswuuhv24vzstuqtxsi
#### Id
> 734481ee-170f-4773-89ef-9c199d6dc484
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecedkdrdy2cdesgo7lokzdh4fterxymtdjsvxp3t5i5rje4wcu65k

**Comment by Killianxuan** [comment]
Yes

**Comment by C00kies77** [comment]
checker:manualTrigger

**Comment by Sunnyiscoming** [comment]
Hello, @Killianxuan per the https://github.com/filecoin-project/notary-governance/issues/922 for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

This information will be reviewed by Fil+ Governance team to confirm validity and then the application will be allowed to move forward for additional notary review.

**Comment by Filplus-govteam** [comment]
closing until clear SP entity and distribution list provided
