### ISSUE TITLE
[DataCap Application] <SpadeJaymodelAC> - <Model Training Video>

### ISSUE THREAD

**Issue by spadejayac** [filecoin-project/filecoin-plus-large-datasets#2013]
### Data Owner Name

SpadeJaymodelAC

### What is your role related to the dataset

Dataset Owner

### Data Owner Country/Region

Korea, Republic of

### Data Owner Industry

Education & Training

### Website

www.spadejaymodelac.com

### Social Media

```text
https://www.youtube.com/channel/UCmy2-oXfy4X0GXGqXDzOrhQ
```

### Total amount of DataCap being requested

2PiB

### Expected size of single dataset (one copy)

250TiB

### Number of replicas to store

8

### Weekly allocation of DataCap requested

250TiB

### On-chain address for first allocation

f1c6d4ff72jk4wrb7y7xg2appbkgqhiaqdw3nglzi

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
SPADEJAY MODEL AGENCY was founded in 2017 by Jay Shin, a global top model.

Since its inception, SPADEJAY MODEL AGENCY has established partnerships with top agencies around the world, including those in New York, London, Paris, Milan, Hong Kong, Singapore, Japan, Germany, China, Thailand, Spain, Denmark, and more. Through these connections, SPADEJAY has secured contracts for its models to debut on some of the world's most prestigious stages, paving the way for their successful careers.

Thanks to its impressive track record of debuting Korean models abroad, SPADEJAY MODEL AGENCY is currently the company with the highest number of Korean models making their debuts overseas. As the agency continues to cast models and help them pursue their dreams in cities all around the world, SPADEJAY is rapidly growing into a global brand.

In 2020, CEO Jay Shin established the SPADEJAY association to expand the agency's model pool and discover new talent across different age groups. The following year, SPADEJAY brought together a group of Creative Art specialists to work with models on art projects both in Korea and abroad, building portfolios that showcase their unique talents.

Based in the heart of Seoul, South Korea, SPADEJAY MODEL AGENCY exists to showcase the beauty of Korea and its models to the world's most renowned brands. With its global partnerships and commitment to discovering new talent, SPADEJAY is poised to continue making waves in the world of modeling for years to come.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
Most of our content consists of videos, particularly those that are part of our general teaching materials for our walking classes, recordings of fashion shows, and introductions to our agency models. You can find samples of these videos in the data link provided.

The fashion and apparel industries have already entered the web 3.0 era by opening metaverse stores and accepting payments in cryptocurrency or NFT. Our ultimate goal is to become the first model agency to enter the web 3.0 space.

To start this process, I am applying for an LDN to decentralize our public data from agencies (two in the United States and six in Europe). This will allow anyone interested in our agency or the industry as a whole to access our data, and our staff can easily share references and collaborate with others.
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### How do you plan to prepare the dataset

lotus, singularity

### Please share a sample of the data

```text
https://drive.google.com/drive/folders/1VtOV-VD1Td7PIoQ1N0c9pUaPrRIiqtiS?usp=sharing
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Sporadic

### For how long do you plan to keep this dataset stored on Filecoin

2 to 3 years

### In which geographies do you plan on making storage deals

Asia other than Greater China, North America, Europe

### How will you be distributing your data to storage providers

HTTP or FTP server, Lotus built-in data transfer

### How do you plan to choose storage providers

Slack, Partners

### If you already have a list of storage providers to work with, fill out their names and provider IDs below

```text
Dallas, USA - f01971600 - Greaterheat 
Canada, North Ameria - f01886796 
Bulgaria, EU - f020378
Paris, EU - f010479
Belgium, EU- f01345523
Need to find two more SP located in EU and one in Asia. 
Will update it later.
```

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by spadejayac** [comment]
@Sunnyiscoming just sent it! Please check.

**Comment by spadejayac** [comment]
@Sunnyiscoming Sent the business license instead :)

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 4PiB

**Expected weekly DataCap usage rate**
> 450TiB

**Client address**
>f1c6d4ff72jk4wrb7y7xg2appbkgqhiaqdw3nglzi

**Comment by spadejayac** [comment]
Hello, @zcfil 

Thank you for reviewing my LDN and leaving a comment.

As mentioned in my application, I run international model agencies with training centers. 
I would like to distribute our public data to each location where our agencies are located. 
My interest in this initiative grew after participating in community events held in Seoul.

We currently have a 10G port speed connectivity. 
However, I'm uncertain about why you asked about hardware or local download experience. 
I intend to send my data overseas, not locally.

I understand that 4Pib may seem like a lot for a novice, but here's my plan: 
I will create one copy of the dataset, which will be around 500TB. 
I aim to store this dataset with at least eight SPs within three months (I will contact them via Slack). 
This will result in a total of 4Pib.

Currently, I have 380TB, but new training videos are being added every week, so the dataset will eventually reach 500TB.
After the first round, we can select additional SPs in diverse regions to further advance our project.
I hope you understand my LDN plan. Please let me know if you have any further questions.

Regarding the "visible evidence" mentioned, could you please clarify what you mean by that? 
Do you require a screenshot or any other form of evidence?

And I have completed and submitted the form. Please review it on your end.

**Comment by zcfil** [comment]
Is the data you want to store produced by yourselves?

**Comment by zcfil** [comment]
Can you provide data screenshots or other means to prove that you have 380T of data?

**Comment by spadejayac** [comment]
![SpadeJaymodelAC_1](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/128452340/a3b38f56-ed3c-4552-9fe3-c43a714d764f)
![SpadeJaymodelAC_2](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/128452340/15039976-98b6-4f71-b8e3-8eeb90523bfd)
@zcfil 
Yes. The data is produced by ourselves. 
Here's part of our storage

**Comment by zcfil** [comment]
https://drive.google.com/file/d/1aFgOhtuxR_DVCDMjVyFoCCWZCsqbQxvU/view?usp=drive_link

**Comment by zcfil** [comment]
https://drive.google.com/file/d/1aFgOhtuxR_DVCDMjVyFoCCWZCsqbQxvU/view?usp=drive_link
https://www.youtube.com/watch?v=BRI0_T2cdT0

You said that the data was all generated by yourself. I found that there are YouTube videos in the samples you provided that are not from your account. Can you explain this.

**Comment by spadejayac** [comment]
@zcfil 
You are correct. That is not our sample data. 
Upon investigation, it appears that our staff made a mistake in uploading that file to the sample data. 
We have various references to study fashion trends, and that file was one of them.
We will remove it from the sample data immediately.

Furthermore, regarding the data we create ourselves, we have two main categories: online classes and audition classes. 
The data in the online classes consists of basic training videos of walking and posing that everyone can refer to. 
The audition classes provide training videos that share tips and techniques suitable for each brand's auditions. 
Additionally, we have model portfolios, practice videos, and more.

However, the video you mentioned does not belong to either the online or audition classes.

**Comment by zcfil** [comment]
Some unauthorized data that you are planning to upload to filecoin that does not belong to you should be deleted from your storage facility.

@Sunnyiscoming What do you think

**Comment by spadejayac** [comment]
Keep this open LDN. waiting for the approval from notaries

**Comment by spadejayac** [comment]
Do not put the Stale label.
I'm waiting for Notaries' approval. the notaries are not caring about my LDN and leave this application. 
why put stale label? fix the bot. add some filters or smt.

**Comment by ipollo00** [comment]
@spadejayac 
The amount of dc requests won't limit by a GitHub account whether is new or old, in my opinion. 
However, I'm curious whether your data is public. cause I know some training classes are charging online, especially since you guys seem well-known around the world.

**Comment by spadejayac** [comment]
@ipollo00 Good point. The classes are one of our main sources of income, so we cannot open all of them. 
However, the dataset we are going to store in the Filecoin system consists of all public data, such as the basic classes of each course and community event live videos.

**Comment by ipollo00** [comment]
@spadejayac Based on your point, I'm afraid that 450T raw data are way more than your needs.  
Suggesting you apply E-Fil+ application. or you list your public data volume, then change the amount of dc requested.

**Comment by spadejayac** [comment]
@ipollo00 considering your suggestion of downsizing, I edit the requested total DC from 5Pib to 2Pib. Regarding to E+fil+, I would discuss with my team further. However the dataset would be stored in Filcoin is a public data as I mentioned. 

@Sunnyiscoming please review it again and pull the trigger. I have downsized the DC amount.

**Comment by ipollo00** [comment]
@spadejayac respect, I will sign when RKH is done triggering.  at me pls.

**Comment by herrehesse** [comment]
It has been decided by the community that uploading YouTube videos in exchange for datacap is not acceptable. If your application does not contribute value to the ecosystem, you will not be granted datacap. Furthermore, the sources you have claimed for storing the data are proven to be false:

- Dallas, USA - f01971600 - Greaterheat
- Canada, North America - f01886796
- Bulgaria, EU - f020378
- Paris, EU - f010479
- Belgium, EU - f01345523

I have personally contacted three out of the five sources you listed, and they have confirmed that they are not storing any of your data and do not even know who you are. This behaviour is considered abusive and inappropriate.

I strongly urge you to cease your activities and discontinue your application.

@ipollo00 @zcfil You are disputed many times, be warned.

@raghavrmadya Please close this application.

**Comment by ipollo00** [comment]
> 
> * Dallas, USA - f01971600 - Greaterheat
> * Canada, North America - f01886796
> * Bulgaria, EU - f020378
> * Paris, EU - f010479
> * Belgium, EU - f01345523
> 
> I have personally contacted three out of the five sources you listed, and they have confirmed that they are not storing any of your data and do not even know who you are. This behaviour is considered abusive and inappropriate.
> 
@spadejayac Please clarify. If so, I strongly agree close this application.
