### ISSUE TITLE
Can I resubmit this application? Or open this closed application?

### ISSUE THREAD

**Issue by shimanmanya** [filecoin-project/filecoin-plus-large-datasets#2015]
This application has not seen any responses in the last 14 days, so for now it is being closed. Please feel free to re-open if this is relevant, or start a new application for DataCap anytime. Thank you!

_Originally posted by @github-actions[bot] in https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1900#issuecomment-1556058861_
            Hello, I want to ask why this is closed, because I have already answered all the previous questions.Can I resubmit this application? Or open this closed application?

**Comment by shimanmanya** [comment]
Can i start a new application for DataCap anytime. Thank you!

**Comment by Sunnyiscoming** [comment]
It has been reopened. It was closed for no update for 14 days. 
This is the slack channel of Filecoin. https://filecoin.io/slack. You can ask notaries do due diligence for this application and approve it.
