### ISSUE TITLE
[DataCap Application] CMIP6

### ISSUE THREAD

**Issue by Boydling0** [filecoin-project/filecoin-plus-large-datasets#2017]
### Data Owner Name

Pangeo Community

### What is your role related to the dataset

Data Preparer

### Data Owner Country/Region

United States

### Data Owner Industry

Life Science / Healthcare

### Website

https://pangeo-data.github.io/pangeo-cmip6-cloud/

### Social Media

```text
https://registry.opendata.aws/?search=managedBy:esgf%20and%20pangeo
https://www.wcrp-climate.org/wgcm-cmip/wgcm-cmip6
```

### Total amount of DataCap being requested

15PiB

### Expected size of single dataset (one copy)

1.7113PiB

### Number of replicas to store

10

### Weekly allocation of DataCap requested

1PiB

### On-chain address for first allocation

f1473tjqo3p5atezygb2koobcszvy5vftalcomcrq

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
CMIP began in 1995 under the auspices of the Working Group on Coupled Modelling (WGCM). The first set of common experiments involved comparing the model response to an idealized forcing – a constant rate of increase which was accomplished using a CO2 increase of 1% per year compounded.

As a DP, I want to distribute these meaningful data to sp and store it in a decentralized form.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
Zarr formatted data and Netcdf formatted data.
The sixth phase of global coupled ocean-atmosphere general circulation model ensemble.
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### How do you plan to prepare the dataset

IPFS, lotus, singularity

### Please share a sample of the data

```text
s3://cmip6-pds/
s3://esgf-world/
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

1.5 to 2 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, South America, Europe, Australia (continent)

### How will you be distributing your data to storage providers

Cloud storage (i.e. S3), HTTP or FTP server, Shipping hard drives, Lotus built-in data transfer

### How do you plan to choose storage providers

Slack, Filmine, Big Data Exchange, Partners

### If you already have a list of storage providers to work with, fill out their names and provider IDs below

```text
No, still in the progress.
```

### How do you plan to make deals to your storage providers

Boost client, Lotus client, Singularity

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
(1.7113PiB x 10 copies) =17.11PiB
why you are applying for 15 and not over 15?

**Comment by Boydling0** [comment]
@Sunnyiscoming Because our plan is storing 10 copies at most. So we apply 15PiB. If it is enough in the future, we’ll consider change our application. Thank you!

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 15PiB

**Expected weekly DataCap usage rate**
> 1PiB

**Client address**
>f1473tjqo3p5atezygb2koobcszvy5vftalcomcrq

**Comment by Boydling0** [comment]
OK. We'll begin it soon.

**Comment by Boydling0** [comment]
Yes. You can confirm the amount of dataset by aws. 
![adgsd](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/131154580/ac9264bd-351e-40d6-b9eb-8512013e5e8c)
![dfsrj](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/131154580/65f08012-66fe-4f9b-ab34-7503938cd6a5)
I'll distribute data under 30% to each sp to reach distributed storage. Now I hope notaries can sign for us. Thank you!

**Comment by ipollo00** [comment]
@Boydling0 
CMIP data was stored by the other two projects. However, num of copies you said is reasonable.  Willing to support. 
I suggest that you have to pay attention on there might be CID sharing while your data is the same with other projects'.Are you still want to choose this kinda data?

**Comment by Boydling0** [comment]
@ipollo00 Thank you for your support! I'll try to avoid CID sharing!

**Comment by Boydling0** [comment]
Yes, please keep application open.

**Comment by Carohere** [comment]
Talked on slack, willing to support the first round and will check the following updates.

**Comment by Suyanj** [comment]
LGTM, willing to support!

**Comment by Suyanj** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecdqfmvokwg7rhyto5ivcztc5abmdu6pmhuzxj7y7cvanuazq3s7u 
#### Address 
> f1473tjqo3p5atezygb2koobcszvy5vftalcomcrq
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f1ihv7gz3vn3xqvikpt4rwryecgisl7745lodx3yi
#### Id
> 17f0abb1-3d44-4920-84b8-a2fe75259fc8
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecdqfmvokwg7rhyto5ivcztc5abmdu6pmhuzxj7y7cvanuazq3s7u

**Comment by cryptowhizzard** [comment]
checker:manualTrigger

**Comment by spaceT9** [comment]
The CID report and retrieval rate of http are ideal, advise the client to find more SPs in different areas to help the diversity.

**Comment by Destore2023** [comment]
LGTM, will to support.

**Comment by Destore2023** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecmoj45hswaigiop4vf43ix45y7en5tt3c6bshc26unfiv4k2d2nu 
#### Address 
> f1473tjqo3p5atezygb2koobcszvy5vftalcomcrq
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f1yh6q3nmsg7i2sys7f7dexcuajgoweudcqj2chfi
#### Id
> 89aa6b94-3a01-40b1-9c3a-170e7de7dde5
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecmoj45hswaigiop4vf43ix45y7en5tt3c6bshc26unfiv4k2d2nu
