### ISSUE TITLE
[DataCap Application] <Fogmeta Labs> - <Store Arbitrum snapshots>

### ISSUE THREAD

**Issue by hengdingy** [filecoin-project/filecoin-plus-large-datasets#2018]
### Data Owner Name

Fogmeta Labs

### What is your role related to the dataset

Data Preparer

### Data Owner Country/Region

China

### Data Owner Industry

Web3 / Crypto

### Website

https://fogmetalabs.com/chainsnap

### Social Media

```text
Twitter: https://twitter.com/FogMeta
GitHub: https://github.com/FogMeta
```

### Total amount of DataCap being requested

5PiB

### Expected size of single dataset (one copy)

500TiB

### Number of replicas to store

10

### Weekly allocation of DataCap requested

1PiB

### On-chain address for first allocation

f136loip2drf3vsfrcebryfo23q2j5aupnkv23bzi 

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
The research of Fogmeta Labs spans multiple levels from system technology, infrastructure, and middleware to services and solutions, and involves future systems, network technology and business, distributed systems and management, information management, and interactive and innovative services. Based on the views on and practices in the industry, Fogmeta also solves the problem of business complexity through operations optimization and other technologies.

Chainsnap is a project developed by Fogmeta Labs for maintaining blockchain snapshots. This project enables the storing and retrieval of snapshots for blockchain projects including Filecoin, Polygon, Ethereum, Binance Smart Chain, Pocket, and Near.Please refer to: https://github.com/FogMeta/chainsnap.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
These are snapshots of Arbitrum that are maintained by the Arbitrum Team . Please refer to the link here: https://developer.arbitrum.io/node-running/how-tos/running-an-archive-node.

Moreover, we're also running Arbitrum nodes ourselves and will export a snapshot bi-weekly.
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### How do you plan to prepare the dataset

IPFS, lotus, graphsplit, others/custom tool

### If you answered "other/custom tool" in the previous question, enter the details here

```text
We're going to use the `go-mc-sdk` to prepare the datasets. 
https://github.com/FogMeta/go-mc-sdk
```

### Please share a sample of the data

```text
https://snapshot.arbitrum.io/mainnet/db.tar (657.15GB)
https://snapshot.arbitrum.io/mainnet/nitro.tar (199.6GB)
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Monthly

### For how long do you plan to keep this dataset stored on Filecoin

2 to 3 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, Africa, North America, South America, Europe, Australia (continent), Antarctica

### How will you be distributing your data to storage providers

HTTP or FTP server, IPFS, Shipping hard drives, Others

### How do you plan to choose storage providers

Slack, Partners, Others

### If you answered "Others" in the previous question, what is the tool or platform you plan to use

```text
FilSwan platform (https://filswan.com/) is another good choice for us to choose storage providers who meet our requirements.
```

### If you already have a list of storage providers to work with, fill out their names and provider IDs below

```text
The storage providers we'd like to work with are presented below. Some of them are from the FilSwan platform.
f03624
f010088
f02301
f08399
f02401
f0187709
f01163272
f01402814
f01072221
f0240185
f0143858
f01390330
f01225882
f0717969
f03223
f01395673
f01786736
f0836160
f032824
f01443744
f01871352
f01907556
f01946551
f02012951
f01970630
```

### How do you plan to make deals to your storage providers

Boost client, Lotus client, Others/custom tool

### If you answered "Others/custom tool" in the previous question, enter the details here

```text
https://github.com/FogMeta/go-mc-sdk
```

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
Data samples are too large to check it. Can you provide some small data samples to make us check it easily?

**Comment by hengdingy** [comment]
https://snapshot.arbitrum.io/mainnet/db.tar (657.15GB)
https://snapshot.arbitrum.io/mainnet/nitro.tar (199.6GB)


@Sunnyiscoming we are downloading the snapshot from the above link.  And the snapshot is maintained by the arbitrum team. Once the dataset is downloaded, I will paste a screenshot here.

**Comment by Sunnyiscoming** [comment]
Any update here?

**Comment by Sunnyiscoming** [comment]
Any update here?

**Comment by Sunnyiscoming** [comment]
It will be closed if no reply received in 14 days.

**Comment by Sunnyiscoming** [comment]
Close for no reply.

**Comment by hengdingy** [comment]
sorry @Sunnyiscoming , we are preparing the snapshots(including ARB, Avalanch) and website, can you help us reopen it?

**Comment by hengdingy** [comment]
@Sunnyiscoming @Kevin-FF-USA , we are preparing the snapshots, can you help us reopen it?
https://fogmetalabs.com/chainsnapshots/Arbitrum
