### ISSUE TITLE
[DataCap Application] Cloud storage technology

### ISSUE THREAD

**Issue by nike-mp** [filecoin-project/filecoin-plus-large-datasets#2019]
### Data Owner Name

Cloud storage technology

### What is your role related to the dataset

Dataset Owner

### Data Owner Country/Region

China

### Data Owner Industry

Web3 / Crypto

### Website

http://www.cloudbigger.com/#/home

### Social Media

```text
http://www.cloudbigger.com/#/home
```

### Total amount of DataCap being requested

3PiB

### Expected size of single dataset (one copy)

300TIB

### Number of replicas to store

10

### Weekly allocation of DataCap requested

500TiB

### On-chain address for first allocation

f1jdtk3cj76xqwchpnyy7gdwvzx2z2j4oiqle2d3a

### Data Type of Application

Public, Open Commercial/Enterprise

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Founded in 2011, Cloud Storage Technology is a leader in the field of distributed storage in my country, a builder of decentralized cloud storage and big data R&D systems. The technology field is in a leading position. Committed to providing data cloud storage, management, operation and maintenance and technical support for enterprises, individuals and the majority of Internet users, and at the same time developing the application of distributed storage technology, it proposes an advanced technology solution integrating distributed technology and hyper-converged technology. And cloud storage technology develops hybrid cloud storage such as data backup and recovery, hot and cold data layering, and multi-branch sharing; and provides users with reliable , controllable, and visible data protection.

Cloud Storage Technology has a registered capital of 10 million yuan and is headquartered in Hangzhou. It has many years of professional distributed storage Cloud storage technology focuses on the research of content storage and distribution technology, and accelerates the promotion of online and offline application scenarios. In 2018, it successfully developed a multi-layer architecture storage server, and independently developed a hyper-converged distributed storage system to ensure that users have more choices. with the path. Cloud storage technology also independently researches and develops Yunshuo hyper-converged management system, Yunshuo distributed management system and distributed storage 2U servers, 4U servers, etc., to provide users with a one-stop storage service ecosystem.

Cloud storage technology has professional network equipment operation and maintenance personnel and professional server software developers, so that customers can have a good experience. Under the operation of the independent property rights hyper-converged distributed storage system, customers have faster data storage and reception, and adjust the three major network operators in real time according to the network quality, and switch freely.

Cloud storage technology adheres to the strategic thinking of international cooperation and coordinated development, and actively cooperates with domestic and foreign enterprises, scientific research institutes, and universities to deeply cultivate the bandwidth cloud storage industry for ten years. In-depth cooperation with more than ten large IDC data centers across the country, covering Northwest, Central, East and Southwest China. In the future, Cloud Storage Technology will focus on building distributed storage technology and big data center technology development as the axis, and carry out resource integration, technology transformation and ecological construction with a global perspective and pattern, and strive to build the company into an ecological platform enterprise .development experience. It is a high-tech enterprise in Hangzhou and a "Eagle Plan" enterprise in Hangzhou. It has obtained the value-added telecommunications business license of the People's Republic of China. Build into an information data technology innovative enterprise.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
The data is mainly the introduction of Cloud storage technology and the promotional videos of major products, including the solution introduction of document type.
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### How do you plan to prepare the dataset

IPFS, lotus, singularity

### Please share a sample of the data

```text
Link：https://drive.google.com/drive/folders/13pWKJP1c3pjcG7VEj3lOL6cfEE5ErTlS
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Monthly

### For how long do you plan to keep this dataset stored on Filecoin

1.5 to 2 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, Europe

### How will you be distributing your data to storage providers

Cloud storage (i.e. S3), HTTP or FTP server, IPFS, Shipping hard drives, Lotus built-in data transfer

### How do you plan to choose storage providers

Slack, Filmine

### How do you plan to make deals to your storage providers

Boost client, Lotus client, Bidbot

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
Can you provide more data samples and materials to prove that you have 500 TB data already?
Could you send an email to filplus-app-review@fil.org with your official domain in order to confirm your identity? Email name should includes the issue id #2019.

**Comment by nike-mp** [comment]
Sorry, we only saw your message now. We will arrange for more data submission and email sending immediately. Thank you! @Sunnyiscoming

**Comment by nike-mp** [comment]
@Sunnyiscoming 
![7bca8385deeeb83973ebef2aa63388f](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/134700230/16edce81-fd56-4151-9053-9428390c65c5)
![d454feceaf904c5083c28f42d1e9222](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/134700230/fca99b4f-5581-434f-88aa-e1acc83a3fb0)
https://drive.google.com/drive/folders/1T-qtr4XXykMIFkfIM9MGzCK0NJvORSkV?usp=drive_link

Hello, we have added the information and sent an email via corporate email. Have a nice weekend!

**Comment by Sunnyiscoming** [comment]
The data samples you provide are promotional materials for yourself or others in the industry.
1. Whether these data of other organizations is authorized to be stored publicly; 
2. Most of data samples are small files, which are not enough to prove that you have 500TB data storage requirements.

**Comment by nike-mp** [comment]
<img width="471" alt="b55dbc11ef47caeb1f194e10e568836" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/134700230/3ec1fcf3-1105-4a12-9ebe-b9725fc4e153">
@Sunnyiscoming

**Comment by nike-mp** [comment]
Sorry, we just saw the news now, we decided to modify it according to your request, at present 5p has been adjusted to 3P, thank you! @Sunnyiscoming

**Comment by Sunnyiscoming** [comment]
Please share more detailed information about sps you will cooperate with.

**Comment by nike-mp** [comment]
We have contacted many SPs, they are f021255, f0427989, f02201915, f02200472, f02125861, we plan to cooperate with them, if necessary, we will contact more SPs to achieve more decentralized storage. @Sunnyiscoming

**Comment by nike-mp** [comment]
Hi, thank you for going through our application, what we should do next, is to contact the notary https://github.com/filecoin-project/notary-governance/tree/main/notaries
Help us sign? Hope to get help from the community

**Comment by stcouldlisa** [comment]
Looks good, as a first round, I'm willing to support

**Comment by stcouldlisa** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacech4yianxvot6vwdoslrcwsxmobltzlc774dlhtoeuxrwhh6swddq 
#### Address 
> f1jdtk3cj76xqwchpnyy7gdwvzx2z2j4oiqle2d3a
#### Datacap Allocated
> 153.59TiB
#### Signer Address
> f1jvvltduw35u6inn5tr4nfualyd42bh3vjtylgci
#### Id
> 3f092ffd-f5b3-4573-9b59-b06772a1db18
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacech4yianxvot6vwdoslrcwsxmobltzlc774dlhtoeuxrwhh6swddq

**Comment by igoovo** [comment]
Send me (goovolvo#gmail.com) an email from the email under the official domain name of your company.
To confirm your authenticity, thank you.

**Comment by igoovo** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceawdu72orz2bvtb5sl4zptvzvkpugkyc24l6xrbakm5dj6pg7l7ni 
#### Address 
> f1jdtk3cj76xqwchpnyy7gdwvzx2z2j4oiqle2d3a
#### Datacap Allocated
> 153.59TiB
#### Signer Address
> f1shnsfayxqll77svffaxnjenms7bbbysbqcatrpy
#### Id
> 3f092ffd-f5b3-4573-9b59-b06772a1db18
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceawdu72orz2bvtb5sl4zptvzvkpugkyc24l6xrbakm5dj6pg7l7ni

**Comment by nike-mp** [comment]
We are getting ready to launch, please keep it open for us, thanks!

**Comment by herrehesse** [comment]
"_promotional videos of major products_" is not adding value to the filecoin ecosystem and should not be granted datacap.

The initial request for 3 PiB using a newly created account and without establishing trust within the community is concerning. I highly recommend close the application and reconsider by starting with a smaller amount to build credibility and trust before making larger requests.

Advising notaries not to engage.

**Comment by stcouldlisa** [comment]
checker:manualTrigger

**Comment by nike-mp** [comment]
We are a distributed storage provider based on web3. We not only have promotional videos, but also pictures, documents, and other very precious data, such as meeting records, customer pre-sales and after-sales, etc. We are willing to pay for our data Retrieve, because the data is very meaningful to us.

**Comment by sxxfuture-official** [comment]
checker:manualTrigger

**Comment by sxxfuture-official** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceazwjx4uutf5pruemjvt7pq2n3ijcfve4cdz3dwitmjsyiqhehypo 
#### Address 
> f1jdtk3cj76xqwchpnyy7gdwvzx2z2j4oiqle2d3a
#### Datacap Allocated
> 500.00TiB
#### Signer Address
> f1foiomqlmoshpuxm6aie4xysffqezkjnokgwcecq
#### Id
> 2b6aa1c2-5fd4-494b-935a-edf54bab1df7
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceazwjx4uutf5pruemjvt7pq2n3ijcfve4cdz3dwitmjsyiqhehypo

**Comment by nj-steve** [comment]
checker:manualTrigger

**Comment by nj-steve** [comment]
Yunchu Tec contacted me in community. I looked into Yunchu Tec, a storage and data company that is well known in Asia. It's been around for 12 years.He has done KYC certification. 
Willing to believe this client this round. 
keep eyes on it.

**Comment by nj-steve** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecnrlbmhcywqom6k2swfwh3onxyhlr4n7jovhsozcsrdh7jlzyi3i 
#### Address 
> f1jdtk3cj76xqwchpnyy7gdwvzx2z2j4oiqle2d3a
#### Datacap Allocated
> 500.00TiB
#### Signer Address
> f1xx6555qijma7igpnjspyvdunc4vfxkawnpqy5ii
#### Id
> 2b6aa1c2-5fd4-494b-935a-edf54bab1df7
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecnrlbmhcywqom6k2swfwh3onxyhlr4n7jovhsozcsrdh7jlzyi3i

**Comment by ipollo00** [comment]
checker:manualTrigger

**Comment by nike-mp** [comment]
checker:manualTrigger

**Comment by junyaoren** [comment]
checker:manualTrigger

**Comment by junyaoren** [comment]
checker:manualTrigger

**Comment by kernelogic** [comment]
No open dispute. Reports LGTM. Please keep improving the retrieval success rate.

**Comment by kernelogic** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced3ypwqgn6fsny4djryoc3vbh4nhwvncqv62eetpqf7exufxbsynk 
#### Address 
> f1jdtk3cj76xqwchpnyy7gdwvzx2z2j4oiqle2d3a
#### Datacap Allocated
> 500.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### Id
> 7ae861c2-250e-4c9f-baf6-cf1e43898cbc
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced3ypwqgn6fsny4djryoc3vbh4nhwvncqv62eetpqf7exufxbsynk

**Comment by laurarenpanda** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecwvn5fvkl6mkha4v5xcjrgklddx2sr4btm4evzgq2qs6yiq26tfs 
#### Address 
> f1jdtk3cj76xqwchpnyy7gdwvzx2z2j4oiqle2d3a
#### Datacap Allocated
> 500.00TiB
#### Signer Address
> f1bp3tzp536edm7dodldceekzbsx7zcy7hdfg6uzq
#### Id
> 7ae861c2-250e-4c9f-baf6-cf1e43898cbc
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecwvn5fvkl6mkha4v5xcjrgklddx2sr4btm4evzgq2qs6yiq26tfs

**Comment by junyaoren** [comment]
checker:manualTrigger

**Comment by zcfil** [comment]
checker:manualTrigger

**Comment by a1991car** [comment]
checker:manualTrigger

**Comment by a1991car** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebtvccq3yfqszet2fiwukq6t43ia7nb7xctscpyx6gcyzbutkoyd4 
#### Address 
> f1jdtk3cj76xqwchpnyy7gdwvzx2z2j4oiqle2d3a
#### Datacap Allocated
> 500.00TiB
#### Signer Address
> f1qnumecdypgrbaebtkdfjnwt5ndacadcuas3deiq
#### Id
> 7ae861c2-250e-4c9f-baf6-cf1e43898cbc
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebtvccq3yfqszet2fiwukq6t43ia7nb7xctscpyx6gcyzbutkoyd4

**Comment by junyaoren** [comment]
Looks good. Retrieving rate is improving significantly. Will support this round.

**Comment by junyaoren** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec633byvtvdk3i2uekohsntqghiqwyhaxr6yqwztyupptczyqhghw 
#### Address 
> f1jdtk3cj76xqwchpnyy7gdwvzx2z2j4oiqle2d3a
#### Datacap Allocated
> 500.00TiB
#### Signer Address
> f1xzff5xup63o5sygr2swp4zvcajg54lotliimdty
#### Id
> 7ae861c2-250e-4c9f-baf6-cf1e43898cbc
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec633byvtvdk3i2uekohsntqghiqwyhaxr6yqwztyupptczyqhghw

**Comment by Aaron01230** [comment]
checker:manualTrigger

**Comment by Aaron01230** [comment]
The report shows everything is good, i will support this round.

**Comment by Aaron01230** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceavvdkos5jkhv763wjfclbo4qe677mgqx7gbg57kuz2ibfn45d7ja 
#### Address 
> f1jdtk3cj76xqwchpnyy7gdwvzx2z2j4oiqle2d3a
#### Datacap Allocated
> 500.00TiB
#### Signer Address
> f1xrnysd4gimg64d4l6qi7ulzwwq22c6vfg6lpw3i
#### Id
> 70288c7c-e919-4af0-ac8a-920f300d2d9d
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceavvdkos5jkhv763wjfclbo4qe677mgqx7gbg57kuz2ibfn45d7ja

**Comment by ipollo00** [comment]
everything LGTM.

**Comment by ipollo00** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecwk4mtzmxbzbfyux3pwahocbtzdtgothksume2j6e6rns3p25z3k 
#### Address 
> f1jdtk3cj76xqwchpnyy7gdwvzx2z2j4oiqle2d3a
#### Datacap Allocated
> 500.00TiB
#### Signer Address
> f1n5wlrrhoxpkgwij25xrtt7w7g2k3fhbthmdn6ri
#### Id
> 70288c7c-e919-4af0-ac8a-920f300d2d9d
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecwk4mtzmxbzbfyux3pwahocbtzdtgothksume2j6e6rns3p25z3k

**Comment by nike-mp** [comment]
checker:manualTrigger

**Comment by MasaakiNawatani** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebfitkubrccbrelygalc3gqqln63dheja5x7tz2o7eix7i5tmzbzy 
#### Address 
> f1jdtk3cj76xqwchpnyy7gdwvzx2z2j4oiqle2d3a
#### Datacap Allocated
> 918.40TiB
#### Signer Address
> f1ciu27vn3r7htmanzvwrm6ksx6y774gqsz3cot3i
#### Id
> 674de466-7180-4738-9c07-a46961142418
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebfitkubrccbrelygalc3gqqln63dheja5x7tz2o7eix7i5tmzbzy

**Comment by Normalnoise** [comment]
@nike-mp A high retrieval success rate is great!

but the Deal Data Replication should be improved.

**Comment by Normalnoise** [comment]
Hope you can reduce the data replica rate next round. willing support this round
