### ISSUE TITLE
[DataCap Application] Haru English TV

### ISSUE THREAD

**Issue by SeikLeePark** [filecoin-project/filecoin-plus-large-datasets#202]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Baro Education
- Website / Social Media: https://www.youtube.com/watch?v=tpAcXYjE71U
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100TiB
- On-chain address for first allocation: f3vkrnnqrk5rnlcni25lgkfcz4i3q5tkhr6rtxpkshjk62ulcisyv36p2wlf7twhmlfvbjelzgykuu5sszz4ma

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Baro Education provides professional learning materials for our online students through a comprehensive curriculum. We're especially committed to providing comprehensive second-language acquiring solutions for non-English speakers. Besides, Baro Education also integrates language-learning and culture-exchanging platforms where 
highly competent and qualified teams are meeting the needs and expectations our users

```

What is the primary source of funding for this project?
```
The primary source of funding for this project is our own.
```

What other projects/ecosystem stakeholders is this project associated with?
```
Association for the Second Language Acquisition 
```

## Use-case details

Describe the data being stored onto Filecoin
```
We've been making educational videos for English language leaners, which mainly includes short video clips, systematic teaching curriculum (numerous series of video instructions) based on books and individual teaching materials. It'd be better off to be considered as an integrated language learning platform in Korean education industry.
```

Where was the data in this dataset sourced from?
```
From our own publications 
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://www.youtube.com/watch?v=lkznm8i9qqw
https://www.youtube.com/watch?v=tpAcXYjE71U
https://www.youtube.com/watch?v=7VHUchniltc


```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Please! We'd be more than happy to make it public. 
```

What is the expected retrieval frequency for this data?
```
No fixed retrieval frequency.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
Until it's no longer allowed.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Asia
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
We have specific platform to transfer the data. Also, there is an offline data transfer process.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
Storage providers who are willing to make deals with us are welcome.
```

How will you be distributing deals across storage providers?
```
We'll make deals equally.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, we do.
```

**Comment by IPFSUnion** [comment]
Could you clarify your role and share your public website?

**Comment by SeikLeePark** [comment]
> Could you clarify your role and share your public website?

Thank you for getting back to me ;) I own this business and here comes my website 'https://aionedu.com'. Thanks!

**Comment by galen-mcandrew** [comment]
## Multisig Notary requested
#### Total DataCap requested 
> 5PiB
#### Expected weekly DataCap usage rate 
> 100TiB

**Comment by IPFSUnion** [comment]
Your website can't be open.

**Comment by hatv0908** [comment]
@IPFSUnion hi, i can open this site https://aionedu.com/
please again open it, than you!!

**Comment by IPFSUnion** [comment]
The website looks like  a simple static page . How could we get the public dataset you mentioned?

**Comment by SeikLeePark** [comment]
https://aionedu.com/
It opens on my end. 
Please let me know if you still can't open it. Thanks!

**Comment by dud1337** [comment]
The history of this website has changed many times according to archive.org
https://aionedu.com/%EB%B8%94%EB%A1%9C%EA%B7%B8
This website appears to promote learning in AR/Metaverse, but the YouTube channel seems totally different.

Do you have any resources to verify your association with Baro Education?

**Comment by SeikLeePark** [comment]
We're in the process of making all our learning materials mostly video lessons into AR version to be compatible with our AR app. The instructor of the videos of Baro Edu is the same person who also teaches for Aion Edu. They're affiliated. Thank you!

**Comment by dud1337** [comment]
Do you have any resources to verify that?

**Comment by SeikLeePark** [comment]
> Do you have any resources to verify that?

https://aionedu.com/youtube 
You can see the same instructor here.

**Comment by dud1337** [comment]
I can embed a YouTube link to a video of Bill Gates; it does not verify I'm associated with him.

You have linked two YouTube accounts:
1. https://www.youtube.com/channel/UCU2x6yUGEhqxUtF3Y-LfxEw
2. https://www.youtube.com/channel/UCK_RHaKSenHMocMtVMlOdRQ

And this website:
3. https://aionedu.com/
Which has frequently changed on its history, including the recent embed of a video from the second channel.


That said, the second channel has a message about 'metaverse learning' on the about page. So that lends to the credibility somewhat. It also (in various [video descriptions](https://www.youtube.com/watch?v=zzRaViYeh0g)) links to here and here:
* https://www.instagram.com/hyunbcolbert/
* https://blog.naver.com/hyuncolbert

Which appear to be the blogs of the instructor.

@SeikLeePark 
1. Would you be able to arrange an instagram post from the https://www.instagram.com/hyunbcolbert/ account to to prove your association? Given she is the CEO of Aion, according to the YouTube description.
2. Can you provide a link to a public company registry?

Thanks for your patience.

**Comment by UnionLabs2020** [comment]
@dud1337 did a great demo for all of the notaries.
I believe the notaries would have greater enthusiasm to do KYC  if they can choose to "close" the issues when they need.

**Comment by dkkapur** [comment]
@IPFSUnion @dud1337 thanks for the follow-up here. 

@SeikLeePark I am closing this out for now. Please re-open if it is still relevant and provide the above requested info.
