### ISSUE TITLE
This application hI want to ask how to re-open or start a new application for DataCap anytime. Thank you!as not seen any responses in the last 14 days, so for now it is being closed. Please feel free to re-open if this is relevant, or start a new application for DataCap anytime. Thank you!

### ISSUE THREAD

**Issue by shimanmanya** [filecoin-project/filecoin-plus-large-datasets#2020]
This application has not seen any responses in the last 14 days, so for now it is being closed. Please feel free to re-open if this is relevant, or start a new application for DataCap anytime. Thank you!

_Originally posted by @github-actions[bot] in https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1900#issuecomment-1556058861_

**Comment by Sunnyiscoming** [comment]
It has been reopened.
