### ISSUE TITLE
[DataCap Application] MEDIA - XIPH DATASET

### ISSUE THREAD

**Issue by guanxinlian** [filecoin-project/filecoin-plus-large-datasets#2021]
### Data Owner Name

Xiph.Org Media

### What is your role related to the dataset

Storage provider filling out application on behalf of the data owner

### Data Owner Country/Region

United States

### Data Owner Industry

Information, Media & Telecommunications

### Website

https://xiph.org/

### Social Media

```text
N/A
```

### Total amount of DataCap being requested

400TiB

### Expected size of single dataset (one copy)

36T

### Number of replicas to store

10

### Weekly allocation of DataCap requested

50TiB

### On-chain address for first allocation

f1hpyd3mtlelexwcf2nq5l2bb3xkvqx7i25pmhf3a

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
N/A
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
The Xiph.Org Foundation is a non-profit corporation dedicated to protecting the foundations of Internet multimedia from control by private interests. Our purpose is to support and develop free, open protocols and software to serve the public, developer and business markets.
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### How do you plan to prepare the dataset

singularity

### Please share a sample of the data

```text
aws s3 ls --no-sign-request s3://xiph-media/
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Sporadic

### For how long do you plan to keep this dataset stored on Filecoin

Less than 1 year

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, Europe

### How will you be distributing your data to storage providers

HTTP or FTP server

### How do you plan to choose storage providers

Slack, Partners

### If you already have a list of storage providers to work with, fill out their names and provider IDs below

```text
f02032191(my node)
f03223
f0240185
f01703655
```

### How do you plan to make deals to your storage providers

Singularity

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by guanxinlian** [comment]
Looking forward to my first ldn project

**Comment by guanxinlian** [comment]
Hello, we are a small team on fliecoin. i have nonly one node f02032191. I will find more sp for cooperation. think you.
This project has almost 36TiB raw data. I will save 10 copies.
Expect FILECOIN to get better and better

**Comment by guanxinlian** [comment]
> 您可以使用您的官方域名发送电子邮件至[filplus-app-review@fil.org](mailto:filplus-app-review@fil.org)以确认您的身份吗？电子邮件名称应包含问题 ID #2021。

I have already sent an email to you, thank you

> Could you send an email to [filplus-app-review@fil.org](mailto:filplus-app-review@fil.org) with your official domain in order to confirm your identity? Email name should includes the issue id #2021.

I have already sent an email to you, thank you

**Comment by guanxinlian** [comment]
Now I really need a batch of DC to encapsulate the data. Hope developers can help soon

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 400TiB

**Expected weekly DataCap usage rate**
> 50TiB

**Client address**
>f1hpyd3mtlelexwcf2nq5l2bb3xkvqx7i25pmhf3a

**Comment by Normalnoise** [comment]
@guanxinlian How much data have you downloaded? and how do you want to prepare the dataset, such as generating CAR and sending deals?

**Comment by guanxinlian** [comment]
> @guanxinlian How much data have you downloaded? and how do you want to prepare the dataset, such as generating CAR and sending deals?

I have downloaded all the data so far and intend to use singularity to produce and order

**Comment by max1015070108** [comment]
> Looking forward to my first ldn project
Very glad to support this application

**Comment by woshidama323** [comment]
> Looking forward to my first ldn project

Very glad to support your application 
Please follow the rules of FIL+ during deal proposal

**Comment by 1ane-1** [comment]
For the first round, i will support you and hope you keep the fil+rules.

**Comment by 1ane-1** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceabycojvuglp3ucargpjklt7ijaztgfogjepcxwbryjt4hxrh7m24 
#### Address 
> f1hpyd3mtlelexwcf2nq5l2bb3xkvqx7i25pmhf3a
#### Datacap Allocated
> 20.00TiB
#### Signer Address
> f1mdk7s2vntzm6hu35yuo6vjubtrpfnb2awhgvrri
#### Id
> 075c570b-16a6-48ac-b389-45ffc8797759
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceabycojvuglp3ucargpjklt7ijaztgfogjepcxwbryjt4hxrh7m24

**Comment by Normalnoise** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebfeotthtz4ihsowi6hvwqpzhtr7fftcttfvd5kyxtvmkbyp22gjg 
#### Address 
> f1hpyd3mtlelexwcf2nq5l2bb3xkvqx7i25pmhf3a
#### Datacap Allocated
> 20.00TiB
#### Signer Address
> f1c5non5yf35avgcpsqvxu4yj54yyvxorwyjochqq
#### Id
> 075c570b-16a6-48ac-b389-45ffc8797759
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebfeotthtz4ihsowi6hvwqpzhtr7fftcttfvd5kyxtvmkbyp22gjg

**Comment by Sunnyiscoming** [comment]
checker:manualTrigger

**Comment by Sunnyiscoming** [comment]
It is currently stored on only one node, which may be normal at first. 
Note: Best practice for storing large datasets includes ideally, storing it in 3 or more regions, with 4 or more storage provider operators or owners, and having at least 5 replicas of the dataset.

**Comment by guanxinlian** [comment]
> It is currently stored on only one node, which may be normal at first. Note: Best practice for storing large datasets includes ideally, storing it in 3 or more regions, with 4 or more storage provider operators or owners, and having at least 5 replicas of the dataset.

OK

**Comment by Normalnoise** [comment]
checker:manualTrigger

**Comment by newwebgroup** [comment]
checker:manualTrigger

**Comment by newwebgroup** [comment]
Client has made an explanation and is looking forward to seeing improvements
> ⚠️ 1 storage providers sealed more than 70% of total datacap - [f02032191](https://filfox.info/en/address/f02032191): 100.00%
> 
> ⚠️ All storage providers are located in the same region.

Deal Data Replication
⚠️ 100.00% of deals are for data replicated across less than 3 storage providers.

**Comment by guanxinlian** [comment]
> Client has made an explanation and is looking forward to seeing improvements
> 
> > ⚠️ 1 storage providers sealed more than 70% of total datacap - [f02032191](https://filfox.info/en/address/f02032191): 100.00%
> > ⚠️ All storage providers are located in the same region.
> 
> Deal Data Replication ⚠️ 100.00% of deals are for data replicated across less than 3 storage providers.

Now I have sent several copies of data to miner in other areas for encapsulation, but the data delay has not been updated

**Comment by guanxinlian** [comment]
Now I have sent several copies of data to miner in other areas for encapsulation, but the data delay has not been updated

**Comment by newwebgroup** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebi7ug7kdoi6pupzgboah4x7r5rxindfci75icqri5qwffvrzvrmu 
#### Address 
> f1hpyd3mtlelexwcf2nq5l2bb3xkvqx7i25pmhf3a
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1e77zuityhvvw6u2t6tb5qlnsegy2s67qs4lbbbq
#### Id
> 31108c00-7ef3-4e20-87b7-22ed8e6d4d86
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebi7ug7kdoi6pupzgboah4x7r5rxindfci75icqri5qwffvrzvrmu

**Comment by guanxinlian** [comment]
checker:manualTrigger

**Comment by guanxinlian** [comment]
checker:manualTrigger

**Comment by Joss-Hua** [comment]
The report is improving and basically meets the requirements.
Support this round.

**Comment by Joss-Hua** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecgd6b3r5mgabbqehnwvckxievtp6vpvdxvelbyhxpvqazrjeq5vq 
#### Address 
> f1hpyd3mtlelexwcf2nq5l2bb3xkvqx7i25pmhf3a
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1tfg54zzscugttejv336vivknmsnzzmyudp3t7wi
#### Id
> 31108c00-7ef3-4e20-87b7-22ed8e6d4d86
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecgd6b3r5mgabbqehnwvckxievtp6vpvdxvelbyhxpvqazrjeq5vq

**Comment by guanxinlian** [comment]
checker:manualTrigger

**Comment by guanxinlian** [comment]
checker:manualTrigger

**Comment by guanxinlian** [comment]
checker:manualTrigger

**Comment by Bitrise0111** [comment]
the check report is healthy and we'd like to give support.

**Comment by Bitrise0111** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacea67kbur5oep3h5axhpvun6g7w43waqm7q54wufmgb6q6mvprsexo 
#### Address 
> f1hpyd3mtlelexwcf2nq5l2bb3xkvqx7i25pmhf3a
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1nknj7ayq4o43czrtdoauggtwl43fbqatmqis3yy
#### Id
> 7719f696-4e1e-4ce7-b8b2-cd91c7fc55dd
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacea67kbur5oep3h5axhpvun6g7w43waqm7q54wufmgb6q6mvprsexo

**Comment by psh0691** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedxpdx6ll2z56fafqobfybwc2nqr5w66i5wiwgsvussxoq5gdm4mk 
#### Address 
> f1hpyd3mtlelexwcf2nq5l2bb3xkvqx7i25pmhf3a
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1qdko4jg25vo35qmyvcrw4ak4fmuu3f5rif2kc7i
#### Id
> 7719f696-4e1e-4ce7-b8b2-cd91c7fc55dd
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedxpdx6ll2z56fafqobfybwc2nqr5w66i5wiwgsvussxoq5gdm4mk

**Comment by guanxinlian** [comment]
checker:manualTrigger

**Comment by spaceT9** [comment]
checker:manualTrigger

**Comment by laurarenpanda** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedhfjarbtp6xakrqsvfewzbefox6c2lgru2jf4u6qt6jalkp7y7ya 
#### Address 
> f1hpyd3mtlelexwcf2nq5l2bb3xkvqx7i25pmhf3a
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1bp3tzp536edm7dodldceekzbsx7zcy7hdfg6uzq
#### Id
> 125bd6ae-2db1-409a-a475-1d782d147407
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedhfjarbtp6xakrqsvfewzbefox6c2lgru2jf4u6qt6jalkp7y7ya

**Comment by spaceT9** [comment]
From the past history, I can see big progress. The retrieval success rate increased from 1% to 94%, absolutely support the fourth round. Hopefully you can increase the http retrieval rate.

**Comment by spaceT9** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced7gw2ria2ikgexcvif2lrfmwsu47dzpkpxdvjkbn3ex3ycoznpoo 
#### Address 
> f1hpyd3mtlelexwcf2nq5l2bb3xkvqx7i25pmhf3a
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1dktm3abgn7wkpepxab4q3eaw24qktizk4esfzyy
#### Id
> 125bd6ae-2db1-409a-a475-1d782d147407
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced7gw2ria2ikgexcvif2lrfmwsu47dzpkpxdvjkbn3ex3ycoznpoo

**Comment by guanxinlian** [comment]
checker:manualTrigger

**Comment by cryptowhizzard** [comment]
Hello,

54% of the datacap granted to you is stored with Topblocks. 15% is stored in the same IP range, also topblocks.

![Scherm­afbeelding 2023-07-05 om 16 25 51](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/36404435/2f072f72-c10a-4a7f-85c4-dee791c7a1cf)

Please see:

https://github.com/filecoin-project/notary-governance/issues/913

This LDN should be put on hold for further investigation.

**Comment by guanxinlian** [comment]
> Hello,
> 
> 54% of the datacap granted to you is stored with Topblocks. 15% is stored in the same IP range, also topblocks.
> 
> ![Scherm­afbeelding 2023-07-05 om 16 25 51](https://user-images.githubusercontent.com/36404435/251182254-2f072f72-c10a-4a7f-85c4-dee791c7a1cf.png)
> 
> Please see:
> 
> [filecoin-project/notary-governance#913](https://github.com/filecoin-project/notary-governance/issues/913)
> 
> This LDN should be put on hold for further investigation.

Let me make it clear that #2021 is the first DC list I applied for, and I am not an organization that accumulates data for its own miners. For the time being, I am focusing on the encapsulation of a miner(f02032191), and I am also trying to exchange other data with other LDN in different regions. I don't know whether it is my partner's problem or mine. Now my demand is to carry out encapsulation, and we are just a small filecoin team. And I didn't apply for #2067

**Comment by guanxinlian** [comment]
Let me make it clear that #2021 is the first DC list I applied for, and I am not an organization that accumulates data for its own miners. For the time being, I am focusing on the encapsulation of a miner(f02032191), and I am also trying to exchange other data with other LDN in different regions. I don't know whether it is my partner's problem or mine. Now my demand is to carry out encapsulation, and we are just a small filecoin team. And I didn't apply for #2067

**Comment by guanxinlian** [comment]
And now I'm following official orders

**Comment by guanxinlian** [comment]
checker:manualTrigger

**Comment by guanxinlian** [comment]
checker:manualTrigger

**Comment by cryptowhizzard** [comment]
> Let me make it clear that #2021 is the first DC list I applied for, and I am not an organization that accumulates data for its own miners. For the time being, I am focusing on the encapsulation of a miner(f02032191), and I am also trying to exchange other data with other LDN in different regions. I don't know whether it is my partner's problem or mine. Now my demand is to carry out encapsulation, and we are just a small filecoin team. And I didn't apply for #2067

What is your relationship with Topblocks?

**Comment by guanxinlian** [comment]
> > Let me make it clear that #2021 is the first DC list I applied for, and I am not an organization that accumulates data for its own miners. For the time being, I am focusing on the encapsulation of a miner(f02032191), and I am also trying to exchange other data with other LDN in different regions. I don't know whether it is my partner's problem or mine. Now my demand is to carry out encapsulation, and we are just a small filecoin team. And I didn't apply for #2067
> 
> What is your relationship with Topblocks?

We belong to sp partnership and encapsulate data with each other

**Comment by guanxinlian** [comment]
checker:manualTrigger

**Comment by Patapon0702** [comment]
checker:manualTrigger

**Comment by ars-bubu** [comment]
checker:manualTrigger

**Comment by cryptowhizzard** [comment]
![Scherm­afbeelding 2023-07-21 om 14 14 55](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/36404435/d773aebe-3fe0-43f3-8b87-034561853524)

Greetings. Not much has changed since 2 weeks ago. Topblocks is still @50% and sealing to much datacap in this LDN.

In the LDN you gave info:
----
f02032191(my node)
f03223
f0240185
f01703655
----

I am missing f01703655 as it seems. Who are they?

**Comment by guanxinlian** [comment]
checker:manualTrigger

**Comment by guanxinlian** [comment]
> ![Scherm­afbeelding 2023-07-21 om 14 14 55](https://user-images.githubusercontent.com/36404435/255169627-d773aebe-3fe0-43f3-8b87-034561853524.png)
> 
> Greetings. Not much has changed since 2 weeks ago. Topblocks is still @50% and sealing to much datacap in this LDN.
> 
> ## In the LDN you gave info:
> ## f02032191(my node)
> f03223
> f0240185
> f01703655
> I am missing f01703655 as it seems. Who are they?

This is a node of a friend of mine in Henan province, before he was going to encapsulate but did not have the idea of encapsulation

**Comment by Sunyaoyaomk** [comment]
Comments from a DC seller, we are inclined to ignore.

**Comment by cryptowhizzard** [comment]
Hello @guanxinlian 

I managed to do retrieval from you and put the data here:

http://datasetcreators.com/downloadedcarfiles/2021-f02204248-f0143858-42331248-baga6ea4seaqe6pchnot6o44heepqpzsmq3yko5pzr5orzn3mkataeyi2y7fiwjq/xiph-media/media.xiph.org/HereComesTheSunEnc/

Can you tell me what it is i have downloaded? Is it a movie file? I tried opening it but it doesn't play and the file looks broken.

Second point: Can you present a onboarding plan on how you wish to continue with this LDN and where you plan to send the data? At this moment Topblocks still received to much, the maximum is one replica per SP/organization so it needs to be brought down to 25% max.

**Comment by guanxinlian** [comment]
> Hello @guanxinlian
> 
> I managed to do retrieval from you and put the data here:
> 
> http://datasetcreators.com/downloadedcarfiles/2021-f02204248-f0143858-42331248-baga6ea4seaqe6pchnot6o44heepqpzsmq3yko5pzr5orzn3mkataeyi2y7fiwjq/xiph-media/media.xiph.org/HereComesTheSunEnc/
> 
> Can you tell me what it is i have downloaded? Is it a movie file? I tried opening it but it doesn't play and the file looks broken.
> 
> Second point: Can you present a onboarding plan on how you wish to continue with this LDN and where you plan to send the data? At this moment Topblocks still received to much, the maximum is one replica per SP/organization so it needs to be brought down to 25% max.

hello
Can you tell me what it is i have downloaded? Is it a movie file? I tried opening it but it doesn't play and the file looks broken
It was video data, but I'm not sure why it didn't come. I just downloaded it from a public data source. You can see the image below
![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/34392089/b59bc4a4-944e-40bd-9d7e-2d84beca1093)

Second point: Can you present a onboarding plan on how you wish to continue with this LDN and where you plan to send the data? At this moment Topblocks still received to much, the maximum is one replica per SP/organization so it needs to be brought down to 25% max.
As for the topblock ratio, I have stopped issuing orders to him. I have a question about whether the 10 data sets I applied for can be encapsulated with another one to reduce the topblock ratio

**Comment by cryptowhizzard** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebqo356bfp7inwvogdqttzk3f5kplsmnz5sbgjsavb3tg2cq45aua 
#### Address 
> f1hpyd3mtlelexwcf2nq5l2bb3xkvqx7i25pmhf3a
#### Datacap Allocated
> 30.00TiB
#### Signer Address
> f1krmypm4uoxxf3g7okrwtrahlmpcph3y7rbqqgfa
#### Id
> 155cdd4c-3402-46e8-be0d-78311eb4370b
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebqo356bfp7inwvogdqttzk3f5kplsmnz5sbgjsavb3tg2cq45aua

**Comment by guanxinlian** [comment]
> @guanxinlian
> 
> Thanks for answering the questions. Good luck with your LDN! looking forward to see your results.

Thankyou

**Comment by GaryGJG** [comment]
Looks very good client, I support.

**Comment by GaryGJG** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceazeggrrjosrpkp4wvdjabhu2wgmf5owbrap2tvbbd4ychofkjnnu 
#### Address 
> f1hpyd3mtlelexwcf2nq5l2bb3xkvqx7i25pmhf3a
#### Datacap Allocated
> 30.00TiB
#### Signer Address
> f1zffqhxwq2rrg7rtot6lmkl6hb2xyrrseawprzsq
#### Id
> 155cdd4c-3402-46e8-be0d-78311eb4370b
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceazeggrrjosrpkp4wvdjabhu2wgmf5owbrap2tvbbd4ychofkjnnu

**Comment by guanxinlian** [comment]
checker:manualTrigger

**Comment by guanxinlian** [comment]
Please continue. Thank you

**Comment by guanxinlian** [comment]
keep open
