### ISSUE TITLE
[DataCap Application] <PhotographicFeeling> - <Photographic>

### ISSUE THREAD

**Issue by zhong-ta** [filecoin-project/filecoin-plus-large-datasets#2023]
### Data Owner Name

PhotographicFeeling

### What is your role related to the dataset

Dataset Owner

### Data Owner Country/Region

China

### Data Owner Industry

Information, Media & Telecommunications

### Website

https://photographicfeeling.com/

### Social Media

```text
https://photographicfeeling.com/
```

### Total amount of DataCap being requested

7PiB

### Expected size of single dataset (one copy)

700

### Number of replicas to store

10

### Weekly allocation of DataCap requested

1PiB

### On-chain address for first allocation

f1teazw3myutd255ofx3jng2yzoqhqaczmednrioi

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
The word photography is derived from the Greek words φω phos (light) and γραφι graphis (painting, drawing) or γραφη graphê, which together mean "to draw with light". It refers to the process of using a special equipment for image recording, generally using mechanical cameras or digital cameras for photography. Sometimes photography is also referred to as photography, which is the process of exposing a photosensitive medium through the light reflected by an object. Someone has said an incisive phrase: the photographer's ability is to transform the fleeting mundane things of everyday life into immortal visual images.
Photography is a photographic application science with the formation and development of traditional photography technology, which is based on photographic optics, photographic chemistry and electronic technology, and has formed a unique shooting system in long-term practice.
Generally referred to as photography, that is, the use of a camera, image on the negative, print the negative into a single photo, one by one for permanent preservation. However, the image of the photo is motionless and silent, only for people to see its characters, artistic conception, and then experience its meaning. The earliest surviving photograph in the world dates back to 1827 by the Frenchman Joseph Nieps.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
The truth is the best photo, the best propaganda
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### How do you plan to prepare the dataset

singularity

### Please share a sample of the data

```text
https://pan.baidu.com/s/14XQhcfVBj3zx3LJZBnpaFA Extract the code: 33q4
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Monthly

### For how long do you plan to keep this dataset stored on Filecoin

More than 3 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, South America

### How will you be distributing your data to storage providers

HTTP or FTP server, Shipping hard drives

### How do you plan to choose storage providers

Slack, Big Data Exchange

### How do you plan to make deals to your storage providers

Boost client, Singularity

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by zhong-ta** [comment]
@Sunnyiscoming Hi
#1912  I didn't reply in a timely manner and was closed, so I applied for a new one, but the content is the same

**Comment by herrehesse** [comment]
You are completely kidding right?

> Share a brief history of your project and organization
> 
> The word photography is derived from the Greek words φω phos (light) and γραφι graphis (painting, drawing) or γραφη graphê, which together mean "to draw with light". It refers to the process of using a special equipment for image recording, generally using mechanical cameras or digital cameras for photography. Sometimes photography is also referred to as photography, which is the process of exposing a photosensitive medium through the light reflected by an object. Someone has said an incisive phrase: the photographer's ability is to transform the fleeting mundane things of everyday life into immortal visual images.
> Photography is a photographic application science with the formation and development of traditional photography technology, which is based on photographic optics, photographic chemistry and electronic technology, and has formed a unique shooting system in long-term practice.
> Generally referred to as photography, that is, the use of a camera, image on the negative, print the negative into a single photo, one by one for permanent preservation. However, the image of the photo is motionless and silent, only for people to see its characters, artistic conception, and then experience its meaning. The earliest surviving photograph in the world dates back to 1827 by the Frenchman Joseph Nieps.


I'd request an immediate closure of this application @raghavrmadya.

**Comment by Sunnyiscoming** [comment]
Can you give more detailed decription about your team and project?

**Comment by Sunnyiscoming** [comment]
![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/105098820/d47b949f-8649-45e2-b8e5-2c927e6bd1c2)
https://v.youku.com/v_show/id_XMTI0ODM3NTY0OA==.html
https://pan.baidu.com/s/14XQhcfVBj3zx3LJZBnpaFA?fid=85511512576338

http://sp.jzsc.net/guoneishipai/162459
https://pan.baidu.com/s/14XQhcfVBj3zx3LJZBnpaFA?fid=999440262366514

and more.

Can you explain it?

**Comment by Sunnyiscoming** [comment]
Any update here?

**Comment by Sunnyiscoming** [comment]
It will be closed if no reply received in 14 days.

**Comment by Sunnyiscoming** [comment]
Close for no reply.
