### ISSUE TITLE
[DataCap Application] <Organization> - <Project Name>#2024

### ISSUE THREAD

**Issue by fisco1** [filecoin-project/filecoin-plus-large-datasets#2024]
### Data Owner Name

Onnuri Church

### What is your role related to the dataset

Data Preparer

### Data Owner Country/Region

Korea, Republic of

### Data Owner Industry

Not-for-Profit

### Website

https://www.onnuri.org/

### Social Media

```text
https://www.youtube.com/@Onnuriservice/featured
https://www.facebook.com/OnnuriCommunityChurch
https://www.instagram.com/onnuri.acts29/
```

### Total amount of DataCap being requested

1.6PiB

### Expected size of single dataset (one copy)

400 TiB

### Number of replicas to store

4

### Weekly allocation of DataCap requested

50TiB

### On-chain address for first allocation

f17chwp55d4jctsuqkyrgqguiysimkqngrdwobzea

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Lstonz provides sermon videos globally from pastors & plans to store all church sermon data. Onnuri Church, 1 of the largest, is the starting point, followed by the top 10 ranked Churches. Lstonz influences major Korean churches. Long-lasting project breaking church barriers with Filecoin & IPFS.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
Staring with archives and preparing daily retrieval service in 1-2 years. The original files are filmed in 4K or 8K, and new videos are created every week for Wednesday and Sunday sermons. Original, Tv, and Internet versions.
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### How do you plan to prepare the dataset

lotus

### Please share a sample of the data

```text
https://www.onnuri.org/videos/former-senior-pastor-has-sermons/#maintab=1&subtab2=3&subtab1=1
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Monthly

### For how long do you plan to keep this dataset stored on Filecoin

Permanently

### In which geographies do you plan on making storage deals

Asia other than Greater China, North America, Europe, Australia (continent)

### How will you be distributing your data to storage providers

HTTP or FTP server

### How do you plan to choose storage providers

Big Data Exchange

### If you already have a list of storage providers to work with, fill out their names and provider IDs below

```text
Greater Heat, f01985745
VDL, f01624021
FCC, f0521569
Andrew Sjoquist Ent. Pty., f01919423
More SPs are in contact directly or through Darma Capital
```

### How do you plan to make deals to your storage providers

Boost client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by fisco1** [comment]
Thank you for your participation.
Let's see if we have a gap in the application fill-out.
We are planning to store the total expected size of 2PiB (maybe more as proceed) through this project. And each time, 5-10 TiB data will be sealed and stored.
To us in filecoin plus docs,
the terminology for the total size of expected storing data is "DataCapa".
the storage size of each time sealing and uploading is "Dataset".
According to the Estuary doc, it makes storage deals to 6 SPs to complete, which seems to make 6 replicas.
I guess we had some gaps in understanding.
Please generously understand our intention and work through it accordingly.
If needed, we will revise or re do the application.
Thank you.

**Comment by Sunnyiscoming** [comment]
1.You can only apply for datacap to store existing data

2.
> Expected size of single dataset (one copy)
> 5-10 TiB

This means the amount of data which is not duplicated. You need change this value.

Total amount of DataCap being requested
Expected size of single dataset (one copy)
Number of replicas to store

You should modify these values to the actual values, theoretically Expected size of single dataset (one copy) * Number of replicas to store = Total amount of DataCap being requested

3. 
> [DataCap Application] <Organization> - <Project Name> 

You should change your title of application.  [DataCap Application] <Onnuri Church> - <Sermons> 

4.You should find more sps. Best practice for storing large datasets includes ideally, storing it in 3 or more regions, with 4 or more storage provider operators or owners, and having at least 5 replicas of the dataset.

**Comment by fisco1** [comment]
Here is the correct summary of my request.

1-2. 
Total amount of DataCap being requested: 1.6PiB
Expected size of single dataset (one copy): 400TiB
Number of replicas to store: 4

3. Application revised

4. We will find more than 4 foreign SPs for the regional distribution.

Please kindly advise if you find any other issue.
Thank you and God bless you.

**Comment by Sunnyiscoming** [comment]
Could you send an email to filplus-app-review@fil.org with your official domain in order to confirm your identity? Email name should includes the issue id #2024.

**Comment by Sunnyiscoming** [comment]
Any update here?

**Comment by fisco1** [comment]
We will release the new web site from this Sunday, June 11th. It is still the test version for couple of months since it will include not only the archive service but realtime video WEB3.0 up/down-load service with estuary,
Here is the domain: lstonz.com
My official email: ylee@lstonz.com
Please understand for the delay of contact. We are tied up with many promotion activities to churches these days.

**Comment by Sunnyiscoming** [comment]
lstonz.com https://www.onnuri.org/
I can not open these two website.
Maybe you can send me the related supporting documents.

**Comment by fisco1** [comment]
Sunnyiscoming,
Click on blue marked https://www.onnuri.org/ in your chat box above. It works for me.
I don't know why you have problem with https://www.onnuri.org.
The site is viewed by millons of people globally.
Our service domain Lstonz is not working till Sunday as explained one chat box above yours.
However, our web service is not for the use of this application.
It is for our next service that I have introduced for the reference.
This application is for the immidiate archive service for the churches that carry tons of past sermon contents.

**Comment by fisco1** [comment]
Onnuri is one of the top 10 large churches in Korea. We now have deal done or work in process with the mid sized churches as shown below. They are all our affiliate's ERP customer churches. Datacap will need to be expanded as we continue this project in the near future with churches' demand. 

www.bigtree.or.kr
www.fgcdc.org
www.namseoul.org
www.goyangchurch.com
www.bdc.or.kr
www.joongang.or.kr
www.mokpodream.org
www.jesuscountry.net
www.msfirst.com
www.keumsung.org
www.namsanch.org
www.hyangsang.com
www.hjpc.org
www.sieunso.org
www.pcmc.or.kr
www.thanksjesus.co.kr
www.mokwonchurch.com
www.dsjeil.com
www.daeilchurch.net
www.pydp.or.kr
www.cams.or.kr
www.oj-sunghwa.or.kr
www.daegil.net
www.chang-dai.com
www.hgch.net
www.shinan.or.kr

**Comment by fisco1** [comment]
I must confess that I am not entirely acquainted with the precise parameters of your verification requirements. Nonetheless, this invaluable information holds the potential to profoundly benefit the filecoin network in a humanitarian and purposeful manner. In particular, smaller churches lacking substantial financial support are often compelled to discard their cherished sermons and other precious video content owing to budgetary constraints, thereby incurring significant losses within the Christian community.

**Comment by Sunnyiscoming** [comment]
I am confirming whether you are authorized to store these data. If the official website is https://www.onnuri.org/, why did you send me an email from the mailbox at the end of lstonz.com, which cannot be opened? If you cannot use the email address ending onnuri.org to send me a confirmation email, please provide me with your business license or other authorized information.

**Comment by MatrixStorage** [comment]
@Sunnyiscoming Hey, I am a notary public and I am concerned about this project, but I would also like to see more information that can prove the owner of this data, if any, I would be happy to help.

**Comment by Sunnyiscoming** [comment]
Any update here?

**Comment by Sunnyiscoming** [comment]
You can prove that you are authorized to store these data, like this application.https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/2060#issuecomment-1602059121

**Comment by Sunnyiscoming** [comment]
Close for no reply.

**Comment by tigerhsl** [comment]
As we step into 2024, I extend my warmest wishes for a year filled with prosperity and success. My name is H.S. Lee, and I am the president of Lstonz. Since it's one of the most important spiritual projects in Korea, I am personally overseeing and handling its progress.

In our efforts to align with your needs, we have successfully engaged with Onnuri Church. They have graciously agreed to sign on the certificate, a gesture that extends beyond their usual practices. This is not a typical business agreement but a heartfelt gift.

I want to acknowledge that this collaboration has been made possible through the strength of our relationship. Without this, the nature of this partnership could have been perceived to a different purpose.

I am optimistic that our journey ahead will be smooth, particularly as this project's issue number coincidentally aligns with the current year. It's a delightful synchronicity that adds to our shared narrative.

Thank you for your trust in us. Please do not hesitate to reach out if you require any additional support or assistance.

[Data gift certificate to Onnuri Church.pdf](https://github.com/filecoin-project/filecoin-plus-large-datasets/files/13818071/Data.gift.certificate.to.Onnuri.Church.pdf)

**Comment by tigerhsl** [comment]
In addition, we have 47 units of 1TB HDD from the church as the 1st segment.
We plan to make replicas spreading over five eligible SPs. This applies to making a change in our DataCap capacity to 2.5 PB. Please advise me on that approach.
Onnuri church, which is one of the largest in Korea, is very happy about this new innovative storage project.
Looking forward to hearing from the participants.
