### ISSUE TITLE
[DataCap Application] <Zetacube Inc> - <Common Crawl May/June 2020>

### ISSUE THREAD

**Issue by HoonChoi-Zetacube** [filecoin-project/filecoin-plus-large-datasets#2025]
### Data Owner Name

Common Crawl 

### What is your role related to the dataset

Data Preparer

### Data Owner Country/Region

United States

### Data Owner Industry

Other

### Website

https://commoncrawl.org/2020/06/may-june-2020-crawl-archive-now-available/

### Social Media

```text
none
```

### Total amount of DataCap being requested

1PiB

### Expected size of single dataset (one copy)

100TiB

### Number of replicas to store

10

### Weekly allocation of DataCap requested

200TiB

### On-chain address for first allocation

f17if5zitdkyxxwqexfnae536364pw3ygfuocske

### Data Type of Application

Slingshot

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Zetacube Inc is a 'Ultra-high-capacity decentralized storage hyper server solution company' in the Web 3.0 era, established to research and commercialize the IPFS storage system, an innovative technology for safely storing huge data in the 4th industrial age. Also, Zetacube Inc is participant in the Slingshot V3, both as DP and SP. Zetacube website is https://www.zetacube.net/
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
The crawl archive for May/June 2020 is now available! It contains 2.75 billion web pages or 255 TiB of uncompressed content, crawled between May 24th and June 7th. It includes page captures of 1.2 billion URLs unknown in any of our prior crawl archives.
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### How do you plan to prepare the dataset

singularity

### Please share a sample of the data

```text
https://commoncrawl.org/2020/06/may-june-2020-crawl-archive-now-available/
https://data.commoncrawl.org/crawl-data/CC-MAIN-2020-24/index.html
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Monthly

### For how long do you plan to keep this dataset stored on Filecoin

2 to 3 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, Africa, North America, South America, Europe, Australia (continent), Antarctica

### How will you be distributing your data to storage providers

HTTP or FTP server, IPFS, Shipping hard drives

### How do you plan to choose storage providers

Slack, Big Data Exchange, Partners

### If you already have a list of storage providers to work with, fill out their names and provider IDs below

```text
f0838467
f01227505
f01942239
f01695888
f01823110
f01103160
```

### How do you plan to make deals to your storage providers

Boost client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by HoonChoi-Zetacube** [comment]
We claimed three datasets on Slingshot. 
#1991, #2003, and #2025 are all different datasets.
![스크린샷_20230530_095328](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/129706575/4125537e-c3e8-4232-a698-21e394eb169f)

**Comment by Sunnyiscoming** [comment]
> f0838467
> f01227505
> f01942239
> f01695888
> f01823110
> f01103160

Which are your nodes?

**Comment by HoonChoi-Zetacube** [comment]
> > f0838467
> > f01227505
> > f01942239
> > f01695888
> > f01823110
> > f01103160
> 
> Which are your nodes?

Our node is f01103160.

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 1PiB

**Expected weekly DataCap usage rate**
> 200TiB

**Client address**
>f17if5zitdkyxxwqexfnae536364pw3ygfuocske

**Comment by HoonChoi-Zetacube** [comment]
@kevzak Our applications are #1991, #2003, and #2025, and I have already closed #2001 and #2002 due to an incorrect address entry.
Regarding data storage, we will first store each dataset on three of the SPs listed in the list of Storage Providers above. All the SPs listed are located in Korea. Furthermore, we recently had a meeting with officials from Greater Heat in Seoul, and we have decided to utilize their storages in Singapore and Dallas for storing data. Additionally, we plan to make deals to other regional storage providers with Boost.

Based on the attached screenshot above, we have claimed three datasets on the Slingshot. Consequently, each of  the applications I filed corresponds to a distinct dataset. Each dataset is about 100 TiB, so each application requires 1PiB of the DataCap.

**Comment by kevzak** [comment]
Thank you for explaining @HoonChoi-Zetacube . Is there anyway to add more details to the application name based on the dataset? Instead of all as common crawl. Perhaps add the month? It just helps when looking more broadly at open applications. Thanks

**Comment by HoonChoi-Zetacube** [comment]
Thank you for your advice @kevzak. I changed the application names of #1991 and #2003.

**Comment by HoonChoi-Zetacube** [comment]
@kevzak I revised the title of the #2003 application with your advice and the application is currently labeled  'governance review needed'. Could you remove the governance review needed label?

**Comment by cryptowhizzard** [comment]
#1991 

100% selfdealing of the granted datacap

**Comment by cryptowhizzard** [comment]
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1991#issuecomment-1612310838
