### ISSUE TITLE
[DataCap Application] <DataMe> - <World Economic Data>

### ISSUE THREAD

**Issue by QodeNu** [filecoin-project/filecoin-plus-large-datasets#2026]
### Data Owner Name

DataMe

### What is your role related to the dataset

Data Preparer

### Data Owner Country/Region

Hong Kong

### Data Owner Industry

IT & Technology Services

### Website

http://www.econostatistics.co.za/

### Social Media

```text
n/a
```

### Total amount of DataCap being requested

10PiB

### Expected size of single dataset (one copy)

2P

### Number of replicas to store

10

### Weekly allocation of DataCap requested

1PiB

### On-chain address for first allocation

f1cgqp6ivn2expwksf4hmbv6qp2v6gi4r2qh6umzy

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
DATAME was established in Hong Kong in 2021. We focus on the decentralized storage track. In the past, we focused on cc packaging. Currently, we have in total of 50P storage power on Filecoin. Now we are ready to upgrade the software and hardware from cc to dc. I am a pure Filecoin machine and computing power investor, without official website and promotional. Thank you for your undestanding.
Economic data is crucial in the process of human development and affects the development of countries and individuals. We plan to upload economic data that is critical to human development to the Filecoin network. We have collected 30 large-scale economics-related datasets, in a total of 20P storage capacity, with 10 backups.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
Economic data is crucial in the process of human development and affects the development of countries and individuals. We plan to upload economic data that is critical to human development to the Filecoin network. We have collected 30 large-scale economics-related datasets, in a total of 20P storage capacity, with 10 backups.
Dataset including but not all: 
Asian Productivity Organization (APO) 
ASEAN Stats 
American Economic Association (AEA)
Asian KLEMS 
Harvard Atlas of Economic Complexity 
BIS Financial Database
Barro-Lee Education Attainment - Barro-Lee Educational Attainment Data from 1950 to 2010
CEPII Database 
EUKLEMS - EU KLEMS is an industry level, growth and productivity research project. EU KLEMS
Economic Freedom of the World Data
Latin America KLEMS 
Long-Term Productivity Database 
Maddison Project Database
National Transfer Accounts 
OpenCorporates Database of Companies in the World
Our World in Data [Meta]
Penn World Table - PWT version 10.0
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### How do you plan to prepare the dataset

IPFS, lotus, singularity

### Please share a sample of the data

```text
https://www.aeaweb.org/resources/data
https://www.apo-tokyo.org/
https://data.aseanstats.org/
https://dataverse.harvard.edu/dataverse/atlas
http://www.historicalstatistics.org/
http://www.econostatistics.co.za/
https://www.upcdatabase.com/
http://www.jedh.org/
https://www.rug.nl/ggdc/valuechain/wiod/
https://www.fraserinstitute.org/economic-freedom/dataset?geozone=world&page=dataset&min-year=2&max-year=0&filter=0
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

2 to 3 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, South America, Europe

### How will you be distributing your data to storage providers

Cloud storage (i.e. S3), HTTP or FTP server, IPFS, Shipping hard drives, Lotus built-in data transfer

### How do you plan to choose storage providers

Slack, Partners

### If you already have a list of storage providers to work with, fill out their names and provider IDs below

```text
f02199393/f02192496/f02095766/f01971431/f02115125/f02185816 so far
```

### How do you plan to make deals to your storage providers

Boost client, Lotus client, Droplet client, Singularity

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
You are applying for a total amount of 10 PiB, but the single dataset is 2PiB and the number of replicas is 10.
(2 PiB x 10 copies) = 20 PiB
Why do you apply for 10 PiB and not 20 PiB?

Could you send your business license to filplus-app-review@fil.org in order to confirm your identity? Email name should includes the issue id #2026?

**Comment by QodeNu** [comment]
@Sunnyiscoming Cause I wanna go through step by step.  I'm not sure whether the process is smooth or not, even though I have much more data. 

yup, sure, I have sent the business licences through my email.

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 10PiB

**Expected weekly DataCap usage rate**
> 1PiB

**Client address**
>f1cgqp6ivn2expwksf4hmbv6qp2v6gi4r2qh6umzy

**Comment by kernelogic** [comment]
In support for public data

**Comment by laurarenpanda** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecpba32guma6uqajq5sqczrviorcv7l5ye5cnsjs76y34x4dnvkic 
#### Address 
> f1cgqp6ivn2expwksf4hmbv6qp2v6gi4r2qh6umzy
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f1bp3tzp536edm7dodldceekzbsx7zcy7hdfg6uzq
#### Id
> b8fce6c5-8fc8-4ce9-af06-3bd54ef34d85
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecpba32guma6uqajq5sqczrviorcv7l5ye5cnsjs76y34x4dnvkic

**Comment by kernelogic** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebklrbhq46iqguqwcikuovg7gtdkhj5agm6qvhhhp66q6l5xlt34y 
#### Address 
> f1cgqp6ivn2expwksf4hmbv6qp2v6gi4r2qh6umzy
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### Id
> b8fce6c5-8fc8-4ce9-af06-3bd54ef34d85
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebklrbhq46iqguqwcikuovg7gtdkhj5agm6qvhhhp66q6l5xlt34y

**Comment by Sunnyiscoming** [comment]
checker:manualTrigger

**Comment by spaceT9** [comment]
checker:manualTrigger

**Comment by newwebgroup** [comment]
checker:manualTrigger

**Comment by dahuajishu** [comment]
checker:manualTrigger

**Comment by zcfil** [comment]
checker:manualTrigger

**Comment by ipollo00** [comment]
checker:manualTrigger

**Comment by ipollo00** [comment]
checker:manualTrigger

**Comment by NDLABS-OFFICE** [comment]
checker:manualTrigger

**Comment by NDLABS-OFFICE** [comment]
checker:manualTrigger

**Comment by nj-steve** [comment]
checker:manualTrigger

**Comment by nj-steve** [comment]
Hello @QodeNu Have you contacted the SPs? Are they all in favor of retrieval？The report shows that they all do not support retrieval.

**Comment by QodeNu** [comment]
Hello, @nj-steve Thank you for your attention.
After I discovered this problem yesterday, I contacted these sps, and I informed them that they all should support retrieval, which is the newest rule in Fil+. It has been confirmed today that the node is retrievable.
I hope you can support us and keep an eye on the latest updates, thank you.

**Comment by ipollo00** [comment]
checker:manualTrigger

**Comment by Irmagogo** [comment]
checker:manualTrigger

**Comment by NDLABS-OFFICE** [comment]
checker:manualTrigger

**Comment by ipollo00** [comment]
checker:manualTrigger

**Comment by NDLABS-OFFICE** [comment]
checker:manualTrigger

**Comment by sxxfuture-official** [comment]
@QodeNu 
According to the CID check report, so far all the data has only been sealed on one SP, can you explain this situation? In addition, what plans do you have to solve this problem in the future?

**Comment by QodeNu** [comment]
Hi @sxxfuture-official 
The copies of data have been sent to various SPs through online and offline transfers at different speeds.  It will definitely be shown across SPs gradually. Thx.

**Comment by sxxfuture-official** [comment]
Gotta fix things soon, I'll support this round, but I'll keep an eye on it.

**Comment by sxxfuture-official** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceczv3xcjc2rin3by25khkydpys3uzz7jpnzj46usbsg4ygjpopdsg 
#### Address 
> f1cgqp6ivn2expwksf4hmbv6qp2v6gi4r2qh6umzy
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f1foiomqlmoshpuxm6aie4xysffqezkjnokgwcecq
#### Id
> 2d18bdcd-0bf0-4b60-af6b-d9c2500c7baf
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceczv3xcjc2rin3by25khkydpys3uzz7jpnzj46usbsg4ygjpopdsg

**Comment by DirectionTechnology** [comment]
From the recent CID report, it is evident that there has been a significant improvement in Graphsync retrieval. I would like to know what plans you have in improving HTTP/Bitswap retrieval? @QodeNu

**Comment by QodeNu** [comment]
It depends. As for now, we may using Lotus combining with the lates HTTP code updating in Boost Market.  Will keep in touch with latest news in community.

**Comment by DirectionTechnology** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebefhylz73bmecyktmmhgxo6x4ixxkw3awbelw4lfpghkkmmb2r4g 
#### Address 
> f1cgqp6ivn2expwksf4hmbv6qp2v6gi4r2qh6umzy
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f1inkdoatsbfumdvpctxbgcatscewr3rus5pxmsgi
#### Id
> 2d18bdcd-0bf0-4b60-af6b-d9c2500c7baf
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebefhylz73bmecyktmmhgxo6x4ixxkw3awbelw4lfpghkkmmb2r4g

**Comment by woshidama323** [comment]
checker:manualTrigger

**Comment by Normalnoise** [comment]
checker:manualTrigger

**Comment by woshidama323** [comment]
what's your plan for fixing this warning?

**Comment by QodeNu** [comment]
Hello, @woshidama323 as you can see, data backup has begun to be uploaded by various SPs. 
Because this application form is in the early stage, SPs have different speeds to process data. In the end, it will be stored in accordance with the description of the application form. Please support, thank you.

**Comment by psh0691** [comment]
check:manualTrigger

**Comment by psh0691** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaqzhy7iumwohdlbst2snmpcn63jq2aqzhtxppabf5mw5rderujpg 
#### Address 
> f1cgqp6ivn2expwksf4hmbv6qp2v6gi4r2qh6umzy
#### Datacap Allocated
> 1.00PiB
#### Signer Address
> f1qdko4jg25vo35qmyvcrw4ak4fmuu3f5rif2kc7i
#### Id
> 861f77a9-5dbe-4d19-a717-463a26bb3dea
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaqzhy7iumwohdlbst2snmpcn63jq2aqzhtxppabf5mw5rderujpg

**Comment by woshidama323** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec2ogbnqocdxyeqawnhnck2ndoskejxsgzjeytef23xry6xkpkmkm 
#### Address 
> f1cgqp6ivn2expwksf4hmbv6qp2v6gi4r2qh6umzy
#### Datacap Allocated
> 1.00PiB
#### Signer Address
> f12tk3adljauwnd3hjbigpfxb7b7gdlj63p6afwtq
#### Id
> 861f77a9-5dbe-4d19-a717-463a26bb3dea
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec2ogbnqocdxyeqawnhnck2ndoskejxsgzjeytef23xry6xkpkmkm

**Comment by QodeNu** [comment]
checker:manualTrigger

**Comment by 1ane-1** [comment]
Pay attention to the  deal data replication, and hope it will be fine in the next round. Other parts looks good.

**Comment by 1ane-1** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedhegoxbcsdku2rwv5kchnklr7amu7vffoaksc2ey6xjhaoci56y4 
#### Address 
> f1cgqp6ivn2expwksf4hmbv6qp2v6gi4r2qh6umzy
#### Datacap Allocated
> 2.00PiB
#### Signer Address
> f1mdk7s2vntzm6hu35yuo6vjubtrpfnb2awhgvrri
#### Id
> 3badd419-4c8e-4bbc-a032-c0a3a7fd8902
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedhegoxbcsdku2rwv5kchnklr7amu7vffoaksc2ey6xjhaoci56y4

**Comment by a1991car** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecg62ldwdy4ket6pa76ueo7nnwwoqwry4g46nr7khr5rgwmvomhxg 
#### Address 
> f1cgqp6ivn2expwksf4hmbv6qp2v6gi4r2qh6umzy
#### Datacap Allocated
> 2.00PiB
#### Signer Address
> f1qnumecdypgrbaebtkdfjnwt5ndacadcuas3deiq
#### Id
> 3badd419-4c8e-4bbc-a032-c0a3a7fd8902
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecg62ldwdy4ket6pa76ueo7nnwwoqwry4g46nr7khr5rgwmvomhxg

**Comment by a1991car** [comment]
Temporarily supported, next round needs to see improvement

**Comment by cryptowhizzard** [comment]
I am trying to download some of this data but i get errors.

Error: retrieval query for miner f02192496 failed: failed to dial 12D3KooWKAqaifexH1qF1JZFpoSpxGSRCmJzEgWBmUnzHDfEgW36:
  * [/ip4/183.60.189.222/tcp/41009] failed to negotiate security protocol: peer id mismatch: expected 12D3KooWKAqaifexH1qF1JZFpoSpxGSRCmJzEgWBmUnzHDfEgW36, but remote key matches 12D3KooWJ15oWdtAC7oUMEJQ4bhZDqPU15nps9K5JE2bqEm6H6r2

Can you please fix , notary's need to screen your data before next allocation.

**Comment by QodeNu** [comment]
@cryptowhizzard 
Thank you for your reply. We are currently addressing the technical issues related to retrieval. As you can see from the records, our project's retrieval rate has been continuously increasing. As per the community's request, we are gradually shifting towards using HTTP retrieval.

From the check bot's report, you can also observe that our HTTP retrieval rate is on the rise. We hope to receive your support.

**Comment by QodeNu** [comment]
checker:manualTrigger

**Comment by cryptowhizzard** [comment]
I have a Q

You are working with SP's who have a bad history in #371 and #960. They are involved in heavy CID sharing/abuse.
Why is this?

Secondly the Sp's with AT11 are in the same subnet as the SP's above. 

![Scherm­afbeelding 2023-07-28 om 13 27 38](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/36404435/c7d4502b-11c3-4124-a81d-d4e04e67a4df)

**Comment by QodeNu** [comment]
Consistent with 2044

**Comment by QodeNu** [comment]
checker:manualTrigger

**Comment by maxvint** [comment]
checker:manualTrigger

**Comment by QodeNu** [comment]
Regarding the backup of retrieved reports, we have backed them up on different nodes. Since the efficiency of node storage is not completely uniform, but the storage has been scheduled to see a good improvement in reporting in the next round.

**Comment by cryptowhizzard** [comment]
This client is actively stalling http retrievals and blocked http ranged requests with a reverse proxy to prevent it's data being investigated.

It works as follows:

One set's a bandwidth limit with NGINX on the HTTP retrieval. After a random certain amount the limit is set to zero. This makes the transfer timeout. Because range retrieval is disabled in NGINX one cannot pick up where he left and needs to start all over again. 

Log can be found at http://datasetcreators.com/downloadedcarfiles/logs/2026.log

![Scherm­afbeelding 2023-08-15 om 15 50 54](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/36404435/696309c1-b913-4dd0-ae10-88546abdb4c2)

**Comment by QodeNu** [comment]
@cryptowhizzard @raghavrmadya 
The log you provided shows that your retrieval attempt was on August 4th, but the comment was made on August 15th. During this period, you didn't make any further retrieval attempts, yet you criticized the client without evidence and made baseless speculations.

It's quite clear that we haven't restricted the bandwidth for HTTP retrieval using NGINX. If you had carefully reviewed the client, you would know that the port number you retrieved from was incorrect.

To prevent any potential impact from network issues on retrieval results, I conducted HTTP retrievals for the same CID from machines located in Singapore and Hong Kong. The evidence is as follows:

<img width="915" alt="image" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/121181092/213fded7-340f-448a-8635-75100bb5d055">
<img width="1376" alt="image" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/121181092/f1a7268d-05b8-40c7-a052-8f59f35b9138">
<img width="1277" alt="image" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/121181092/04b9e461-648a-40d0-98ab-3f45a292e7e0">
<img width="1473" alt="image" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/121181092/76af4cec-8d02-455c-9471-ecc1190354fe">

**Comment by cryptowhizzard** [comment]
Well, that is great!

Can you make the CID available for download on a simple URL so i can do data inspection? Would love to check the data that you are storing. If it's compliant then we can move on ;-)

**Comment by QodeNu** [comment]
@cryptowhizzard 

#HTTP retrieve command
wget http://IP:port/piece/pieceCID

#e.g
wget http://128.1.207.98:23459/piece/baga6ea4seaqhtldlc32q5dtdrmg3a3wepfufmg3gztklk2sstddhr2so764t4my

baga6ea4seaqd3gwoyzgdyanwhgqfsiohj2rjguockg7jfbvdisydltf6ll3fgga
baga6ea4seaqnh37g6nfowrung3bboprzk2rwqawsgthhqw5svcmjqphkzs4s6da
baga6ea4seaqdwebqq7xfe5ajpomrp7pnuh2xhtmlb2lleyfqrpvrsbfk4ahocdq
baga6ea4seaqk5f2mus6przib6jtgga6oz7ykh4l42aowhvkt5zkngy4vrqsoicy
baga6ea4seaqdp6plztcmasua6pe3zbq7epug2irmnzgha6xzbhunyn4mlotrkgi
baga6ea4seaqkprceyzop7fyqyjestkkblloov2eyxukqqp6fpl67rcjlwsbwcny

**Comment by cryptowhizzard** [comment]
> 

Thanks!

I retrieveved baga6ea4seaqhtldlc32q5dtdrmg3a3wepfufmg3gztklk2sstddhr2so764t4my succesfully.

Unpacking i see the filenames:

DATAME1/POWER/PaxHeaders.0/power_901_hourly_radiation_utc.zarr.tar.split-6 and some other solar radiation files.

This is not the data you said to be storing?

Please explain.

**Comment by QodeNu** [comment]
@cryptowhizzard 
Firstly, there was an error in the storage of data, and I apologize for not conducting a thorough review. Allow me to clarify the situation regarding this data:

The data stored by the SP we collaborate with comes from publicly available datasets. We did not intentionally fabricate this data. However, it is true that the data was prepared by us, so there must have been an issue at some point in the process. I apologize once again for this.

Additionally, according to normal logic, I wouldn't have been able to disclose problematic CIDs since this was indeed an accident. The possible scenario is that our technical personnel mixed up the data from another publicly available dataset that we were preparing to submit for an application.

I apologize once again.

**Comment by QodeNu** [comment]
This application needs to remain open
