### ISSUE TITLE
[DataCap Application] Community Earth System Model v2 ARISE

### ISSUE THREAD

**Issue by kelly787lu** [filecoin-project/filecoin-plus-large-datasets#2027]
### Data Owner Name

NCAR

### What is your role related to the dataset

Data Preparer

### Data Owner Country/Region

United States

### Data Owner Industry

Environment

### Website

https://ncar.ucar.edu/

### Social Media

```text
https://www.youtube.com/ncarucar
```

### Total amount of DataCap being requested

5PiB

### Expected size of single dataset (one copy)

597.2TiB

### Number of replicas to store

9

### Weekly allocation of DataCap requested

1PiB

### On-chain address for first allocation

f1bwxumusb777knxc5pdoiimseuut4yzg6vx7dm4i

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
The organization NCAR is a center of research excellence in Earth system science sponsored by the National Science Foundation. It was designed by a small group of innovative scientists, most of them university faculty members, as a creative response to major challenges that faced the nation in the years between the 1930s and 1950s. I am a data preparer who is responsible for sealing it.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
Data from ARISE-SAI Experiments with CESM2.--- Project data files
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### How do you plan to prepare the dataset

lotus, singularity

### Please share a sample of the data

```text
https://registry.opendata.aws/ncar-cesm2-arise/
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

1.5 to 2 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, Europe

### How will you be distributing your data to storage providers

HTTP or FTP server, Shipping hard drives, Lotus built-in data transfer

### How do you plan to choose storage providers

Slack, Big Data Exchange

### If you already have a list of storage providers to work with, fill out their names and provider IDs below

```text
I am still looking forward to sps.
```

### How do you plan to make deals to your storage providers

Lotus client, Singularity

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 5PiB

**Expected weekly DataCap usage rate**
> 1PiB

**Client address**
>f1bwxumusb777knxc5pdoiimseuut4yzg6vx7dm4i

**Comment by spaceT9** [comment]
What's your distribution plan? Any SPs you worked with? Can you provide any proof of data size?
