### ISSUE TITLE
[DataCap Application] Beijing Zhongke Zhixing IoT Technology Co., Ltd

### ISSUE THREAD

**Issue by binarier** [filecoin-project/filecoin-plus-large-datasets#2028]
### Data Owner Name
Beijing Zhongke Zhixing IoT Technology Co., Ltd

### What is your role related to the dataset
Dataset Owner

### Data Owner Country/Region
China

### Data Owner Industry
Transport Services

### Website
[https://www.zkraising.com/home](https://www.zkraising.com/home)

### Social Media
N/A (N/A)

### Total amount of DataCap being requested
5 PiB

### Expected size of single dataset (one copy)
64 GiB

### Number of replicas to store
2

### Weekly allocation of DataCap requested
420 TiB

### On-chain address for first allocation
f1lf3bgbgm63wagpdfqwxzogojit56womqz25mkya

### Data Type of Application
Private Commercial/Enterprise

### Custom multisig
No

### Share a brief history of your project and organization
This project aims to design and implement a data backup system to archive the location of the company's massive trucks in operation and data collected by other sensors to ensure that the data is safe and reliable.

### Is this project associated with other projects/ecosystem stakeholders?
No

### If answered yes, what are the other projects/ecosystem stakeholders
n/a

### Describe the data being stored onto Filecoin
Encrypted detailed vehicle sensor log data for regulatory spot checks.

### Where was the data currently stored in this dataset sourced from
My own storage infra

### If you answered "Other" in the previous question, enter the details here
n/a

### How do you plan to prepare the dataset
lotus

### If you answered "other/custom tool" in the previous question, enter the details here
n/a

### Please share a sample of the data
No, it's not public.

### Confirm that this is a public dataset that can be retrieved by anyone on the Network
No

### If you chose not to confirm, what was the reason
Data is encrypted

### What is the expected retrieval frequency for this data
Sporadic

### For how long do you plan to keep this dataset stored on Filecoin
2 to 3 years

### In which geographies do you plan on making storage deals
Asia other than Greater China, North America

### How will you be distributing your data to storage providers
Shipping hard drives

### How do you plan to choose SP
Partners

### If you answered "Others" in the previous question, what is the tool or platform you plan to use
n/a

### If you already have a list of storage providers to work with, fill out their names and provider IDs below
n/a

### How do you plan to make deals to your storage providers
Lotus client

### If you answered "Others/custom tool" in the previous question, enter the details here
n/a

### Can you confirm that you will follow the Fil+ guideline
Yes

_Application created via [filplus.storage](https://filplus.storage)_

**Comment by binarier** [comment]
This project aims to design and implement a data backup system to archive the location of the company's massive trucks in operation and data collected by other sensors to ensure that the data is safe and reliable. The data needs to be archived in the Filecoin network. Provide proof of historical data that cannot be tampered with, which can be checked and confirmed by the regulatory authorities from time to time.

1. Each truck runs about 500-1500 kilometers per day, and each kilometer will generate about 10KB of various log data, including vehicle location, speed, fuel consumption, temperature and other information, that is, each truck has a maximum of about 15M data archives per day.
2. At present, there are more than 2 million trucks using the service in the data platform, so the upper limit of the incremental demand for archiving is about 30TB per day.
3. The stock data currently has about two months of volume, about 1PB or so.
4. All archived data will be watermarked, encrypted and packaged, and will be delivered to the cooperative storage provider in the form of SSD hard disk, and stored on the Filecoin network.
5. The stored archived data needs to ensure that the supervisory department with the encrypt key can randomly check a small part of the data at any time to check the integrity, non-tamperability and validity of the data.
6. The data preservation time requirement is 3 years.

**Comment by herrehesse** [comment]
<img width="391" alt="Screenshot 2023-06-07 at 17 46 28" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/70132857/5e589705-43df-4a92-85dd-ec926272bc32">
Can you explain?

**Comment by binarier** [comment]
1. there's months of history data to be stored and running as startup data.
2. all data has been organized and encrypted as packages which is about 50GB, and it will be used as 64GB filecoin data piece.
3. 2 replica is enough when the data provider operating normal, and the access volume in this project is very low.
