### ISSUE TITLE
[DataCap Application] ATC

### ISSUE THREAD

**Issue by changowens** [filecoin-project/filecoin-plus-large-datasets#203]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: ATC
- Website / Social Media: https://www.youtube.com/channel/UCEmk9HDbL5vDF-agepsWR2g/about 
  (The current domain has expired. If the notary public requests it later, we will send you the site address again.)
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 1pib
- Weekly allocation of DataCap requested (usually between 1-100TiB): 20Tib
- On-chain address for first allocation: f3sacym4eofnbyzwptt4zagtknzik5lesfhxcjy3efhh57kvkrv2xfbcyzkd6y3dwusoawgexzsmkp6dekorba

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
 Hi, Our company name is ATC.
 We established in 2020
 
 Introduce to project
1. Video contents will be published in CHINA and Southeast Asian
2. Promotion of MCN contract with published content
3. Implementing its won project using contract creator and platforms
4. Pioneering new markets such as Southeast Asian markets other than CHINA
```
   
What is the primary source of funding for this project?
```
 Bank loan.
```

What other projects/ecosystem stakeholders is this project associated with?
``` 
There are no special stakeholders in the project we are working on.
We just worked with creators in the video production and publishing business.
Through contracts with them, we will store vast amounts of data, including videos, in the file coin network.
```

## Use-case details

Describe the data being stored onto Filecoin
```
We will probably upload entertainment-related videos the most.
In addition, we plan to continue to upload a lot of data to FileCoin through business expansion into various categories.
```

Where was the data in this dataset sourced from?
```
All the original copies of the currently produced video are kept only on a personal hard disk.
``` 

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
 https://drive.google.com/file/d/1VDIAp7JUgoIsR9Ux86Uc1Hu6iT___Zc2/view?usp=sharing
 https://drive.google.com/file/d/1Tw_ro7rlOQGOzW4t6m-Mi0dR_rW3VtR3/view?usp=sharing
``` 

Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Confrim!
``` 

What is the expected retrieval frequency for this data?
```
Not too frequent.  As time passes and our project stabilizes, searches will continue to increase.
``` 

For how long do you plan to keep this dataset stored on Filecoin?
```
If it is convenient to use, we will use it for a long time.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
South Korea, CHINA, Southeast Asian 
``` 

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Mainly online transaction. We accept offline transaction.
``` 

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
 We will choose according to the storage strength of the miners. We need miners who can cooperate for a long time.
```

How will you be distributing deals across storage providers?
```
More deals will be allocated to providers who have high reputation.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Sure. We will begin immediately.
```

**Comment by galen-mcandrew** [comment]
The provided social media link is a youtube channel, looks like Inoboo, a karaoke channel. There is a broken Facebook link, but I'm not finding any other websites. Additionally, the two sample Google Drive links are not opening.

Can you provide some more context about your project, who you are (do you represent this Youtube channel?), and some more details about what exactly you plan to store on the Filecoin network?

**Comment by changowens** [comment]
The karaoke channel is one of our company's projects.
We have opened a new official YouTube channel.
https://www.youtube.com/channel/UCK9H7ikPmrCTigPJFLLaveg

Our company's official site is currently experiencing problems with its domain and server.
We will share the link when the official site opens in the future.

As I said above, 
Our project is to create video content and discover creators and publish them in Southeast Asia, China.

Our company has a file coin network.
We plan to save all the videos we produce.
Please refer to the link.
https://youtu.be/_0RMn55fPJM
https://youtu.be/5_Wza_Nbzws

thx! have a good day!

**Comment by changowens** [comment]
> 제공된 SNS 링크는 유튜브 채널로 노래방 채널인 이노부처럼 보입니다. 깨진 Facebook 링크가 있지만 다른 웹사이트를 찾을 수 없습니다. 또한 두 개의 샘플 Google 드라이브 링크가 열리지 않습니다.
> 
> 귀하의 프로젝트, 귀하가 누구인지(이 YouTube 채널을 대표합니까?), Filecoin 네트워크에 정확히 무엇을 저장할 계획인지에 대한 추가 정보를 제공할 수 있습니까?



> The provided social media link is a youtube channel, looks like Inoboo, a karaoke channel. There is a broken Facebook link, but I'm not finding any other websites. Additionally, the two sample Google Drive links are not opening.
> 
> Can you provide some more context about your project, who you are (do you represent this Youtube channel?), and some more details about what exactly you plan to store on the Filecoin network?

The karaoke channel is one of our company's projects.
We have opened a new official YouTube channel.
https://www.youtube.com/channel/UCK9H7ikPmrCTigPJFLLaveg

Our company's official site is currently experiencing problems with its domain and server.
We will share the link when the official site opens in the future.

As I said above,
Our project is to create video content and discover creators and publish them in Southeast Asia, China.

Our company has a file coin network.
We plan to save all the videos we produce.
Please refer to the link.
https://youtu.be/_0RMn55fPJM
https://youtu.be/5_Wza_Nbzws

thx! have a good day!

**Comment by changowens** [comment]
> The provided social media link is a youtube channel, looks like Inoboo, a karaoke channel. There is a broken Facebook link, but I'm not finding any other websites. Additionally, the two sample Google Drive links are not opening.
> 
> Can you provide some more context about your project, who you are (do you represent this Youtube channel?), and some more details about what exactly you plan to store on the Filecoin network?

The karaoke channel is one of our company's projects.
We have opened a new official YouTube channel.
https://www.youtube.com/channel/UCK9H7ikPmrCTigPJFLLaveg

Our company's official site is currently experiencing problems with its domain and server.
We will share the link when the official site opens in the future.

As I said above,
Our project is to create video content and discover creators and publish them in Southeast Asia, China.

Our company has a file coin network.
We plan to save all the videos we produce.
Please refer to the link.
https://youtu.be/_0RMn55fPJM
https://youtu.be/5_Wza_Nbzws

thx! have a good day!

**Comment by dkkapur** [comment]
@changowens I see 2 unlisted youtube videos, and nothing else on the channel. Can you help us understand where the 1PiB of DataCap need is coming from?

**Comment by dkkapur** [comment]
@changowens ping on the above. is this application still valid/useful?

**Comment by galen-mcandrew** [comment]
Closing for now, please reopen issue if your request is still relevant. Thanks!
