### ISSUE TITLE
[DataCap Application] NASA Physical Sciences Informatics DATASET

### ISSUE THREAD

**Issue by oldamboo** [filecoin-project/filecoin-plus-large-datasets#2030]
### Data Owner Name

NASA Physical Sciences Informatics

### What is your role related to the dataset

Storage provider filling out application on behalf of the data owner

### Data Owner Country/Region

United States

### Data Owner Industry

Information, Media & Telecommunications

### Website

https://www.nasa.gov/

### Social Media

```text
none
```

### Total amount of DataCap being requested

140TB

### Expected size of single dataset (one copy)

14TB

### Number of replicas to store

10

### Weekly allocation of DataCap requested

50TiB

### On-chain address for first allocation

f1nn3reuxn3pbwjynoainndamja2o46nan5ch7hlq

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
We are planning to build an aerospace related system and website to serve astronomy enthusiasts. Therefore, we need NASA to publicly disclose data for display and use FIL for paid reading in the future. Therefore, relevant data needs to be stored in the early stage。
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
The National Aeronautics and Space Administration is America’s civil space program and the global leader in space exploration. Our purpose is to support and develop free, open protocols and software to serve the public, developer and business markets.
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### How do you plan to prepare the dataset

singularity

### Please share a sample of the data

```text
aws s3 ls --no-sign-request s3://nasa-psi/
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Sporadic

### For how long do you plan to keep this dataset stored on Filecoin

1 to 1.5 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America

### How will you be distributing your data to storage providers

HTTP or FTP server

### How do you plan to choose storage providers

Slack, Partners

### If you already have a list of storage providers to work with, fill out their names and provider IDs below

```text
f02129771（owner node）
f01877259
f01172521
f01843178
```

### How do you plan to make deals to your storage providers

Singularity

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by oldamboo** [comment]
> Expected size of single dataset (one copy)
> > 32GB
> 
> 2. Please share a brief history of your project and organization.
> > We are planning to build an aerospace related system and website to serve astronomy enthusiasts. Therefore, we need NASA to publicly disclose data for display and use FIL for paid reading in the future. Therefore, relevant data needs to be stored in the early stage。 

> If you already have a list of storage providers to work with, fill out their names and provider IDs below
> > f02129771（owner node）
> > f01877259（owner node）
> > f01172521
> > f01843178

Thank you very much for your guidance。

**Comment by Sunnyiscoming** [comment]
Expected size of single dataset (one copy)
32GB

It means how many data are in this dataset, nasa-psi.

**Comment by oldamboo** [comment]
> Expected size of single dataset (one copy) 32GB
> 
> It means how many data are in this dataset, nasa-psi.

OK，so sorry，there are 14TB dataset in this dataset。

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 140TiB

**Expected weekly DataCap usage rate**
> 50TiB

**Client address**
>f1nn3reuxn3pbwjynoainndamja2o46nan5ch7hlq

**Comment by kernelogic** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceczl7c4bhdhxarshzpitagv4gkeydqi7ke5t3xwvnmisacebegoy4 
#### Address 
> f1nn3reuxn3pbwjynoainndamja2o46nan5ch7hlq
#### Datacap Allocated
> 6.36TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### Id
> dc524721-36a2-44b6-ae12-cb431413fe30
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceczl7c4bhdhxarshzpitagv4gkeydqi7ke5t3xwvnmisacebegoy4

**Comment by NiwanDao** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceamzqh5wfabxcueqffjlm26drdvhkhw7grv6sr4yobmcfbmkdygfm 
#### Address 
> f1nn3reuxn3pbwjynoainndamja2o46nan5ch7hlq
#### Datacap Allocated
> 6.36TiB
#### Signer Address
> f1a2lia2cwwekeubwo4nppt4v4vebxs2frozarz3q
#### Id
> dc524721-36a2-44b6-ae12-cb431413fe30
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceamzqh5wfabxcueqffjlm26drdvhkhw7grv6sr4yobmcfbmkdygfm

**Comment by Sunnyiscoming** [comment]
checker:manualTrigger

**Comment by oldamboo** [comment]
hi～this issue is still processed，can open this application？

**Comment by oldamboo** [comment]
checker:manualTrigger

**Comment by cryptowhizzard** [comment]
#2032 

This is also your application. Both #2032 and #2030 are funded from the same address. Why do you use 2 account names and why don't you enable retrieval in #2030
