### ISSUE TITLE
[DataCap Application] Prelinger Archives LLC

### ISSUE THREAD

**Issue by brianeggert** [filecoin-project/filecoin-plus-large-datasets#2031]
### Data Owner Name
Prelinger Archives LLC

### What is your role related to the dataset
Dataset Owner

### Data Owner Country/Region
United States

### Data Owner Industry
Information, Media & Telecommunications

### Website
[prelingerarchives.online](https://archive.org/details/prelinger)

### Social Media
@prelingerarchives (Twitter)

### Total amount of DataCap being requested
50 PiB

### Expected size of single dataset (one copy)
12.5 PiB

### Number of replicas to store
4

### Weekly allocation of DataCap requested
50 TiB

### On-chain address for first allocation
f1i2reokfclrqls5mkgtbqk5esvj6it7nykv7c57y

### Data Type of Application
Public, Open Dataset (Research/Non-Profit)

### Custom multisig
- [x] Use Custom Multisig

### Identifier
efil

### Share a brief history of your project and organization
[Prelinger Archives](https://en.wikipedia.org/wiki/Prelinger_Archives) operates open access film archives with a collection of over 40,000 films. We are currently collaborating with [Internet Archive](https://archive.org/details/prelinger) and [Filecoin Foundation for the Decentralized Web](https://medium.com/@FFDWeb/ffdw-works-with-prelinger-archives-to-make-rare-historic-films-more-accessible-using-the-558e4dbec990) to make thousands of historical films accessible through the DWeb.

### Is this project associated with other projects/ecosystem stakeholders?
Yes

### If answered yes, what are the other projects/ecosystem stakeholders
Internet Archive
FFDW

### Describe the data being stored onto Filecoin
Archival video scanned from historical film

### Where was the data currently stored in this dataset sourced from
My own storage infra

### If you answered "Other" in the previous question, enter the details here
n/a

### How do you plan to prepare the dataset
others/custom tool

### If you answered "other/custom tool" in the previous question, enter the details here
n/a

### Please share a sample of the data
Dataset preparation:
https://github.com/anjor/go-fil-dataprep

Data sample:
https://archive.org/details/200333_Panama-Pacific_International_Exposition_Opening_Parade

Data transfer and dealmaking using spade.

### Confirm that this is a public dataset that can be retrieved by anyone on the Network
Yes

### If you chose not to confirm, what was the reason
n/a

### What is the expected retrieval frequency for this data
Daily

### For how long do you plan to keep this dataset stored on Filecoin
Permanently

### In which geographies do you plan on making storage deals
North America, Australia (continent), Europe, Asia other than Greater China, Africa, South America

### How will you be distributing your data to storage providers
Others

### How do you plan to choose SP
Partners

### If you answered "Others" in the previous question, what is the tool or platform you plan to use
n/a

### If you already have a list of storage providers to work with, fill out their names and provider IDs below
Seal Storage
Telnyx
CES Group Inc
PiKNiK
filcollins
Replikate LLC
W3i
VOT Group
Distributed Storage Solutions Limited
DIGITAL INCOME FUND PTY LTD

### How do you plan to make deals to your storage providers
Others/custom tool

### If you answered "Others/custom tool" in the previous question, enter the details here
n/a

### Can you confirm that you will follow the Fil+ guideline
Yes

_Application created via [filplus.storage](https://filplus.storage)_

**Comment by data-programs** [comment]
This application requests a total of 10 PiB, so it’s labeled `very large application`

**Comment by Sankara-Jefferson** [comment]
Through the social Impact team at the filecoin foundation, I have been working closely with the Prelinger Archive team and they have legitimate data - thousands of short films - that they are preparing to upload to the filecoin storage network.

**Comment by kevzak** [comment]
Filecoin Foundation has confirmed this dataset and client. The E-Fil+ requirements complete. 

Also, one thing to note for notaries: This project is using SPADE to make deals and store with verified Storage Providers. See details of the project here: https://ecosystem-wg.notion.site/Spade-efficient-data-onboarding-to-the-Filecoin-network-8e5dc48fd7c54e0e9385e445543a305a

**Comment by kevzak** [comment]
## Datacap Request Trigger
#### Total DataCap requested 
> 50PiB
#### Expected weekly DataCap usage rate 
> 50TiB
#### Client address
> f1i2reokfclrqls5mkgtbqk5esvj6it7nykv7c57y

**Comment by laurarenpanda** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceakowrl5jeeana4lkdycljdnrko6a75ywogxwdaoggjqggrms2qt6 
#### Address 
> f1i2reokfclrqls5mkgtbqk5esvj6it7nykv7c57y
#### Datacap Allocated
> 25.00TiB
#### Signer Address
> f1bp3tzp536edm7dodldceekzbsx7zcy7hdfg6uzq
#### Id
> ffe0897b-255a-4581-8c94-88dc79083a19
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceakowrl5jeeana4lkdycljdnrko6a75ywogxwdaoggjqggrms2qt6

**Comment by liyunzhi-666** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebvzx32sgz2sswyajrcvzukf4a4drixjolox2quapifjrtctksw4w 
#### Address 
> f1i2reokfclrqls5mkgtbqk5esvj6it7nykv7c57y
#### Datacap Allocated
> 25.00TiB
#### Signer Address
> f1pszcrsciyixyuxxukkvtazcokexbn54amf7gvoq
#### Id
> ffe0897b-255a-4581-8c94-88dc79083a19
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebvzx32sgz2sswyajrcvzukf4a4drixjolox2quapifjrtctksw4w

**Comment by Sunnyiscoming** [comment]
checker:manualTrigger

**Comment by kevzak** [comment]
Hello @brianeggert - there is now one additional step as part of E-Fil+ application process: To validate your applicant GitHub ID, we ask you to complete the KYC check (a third party ID verification process).

Steps: 
- Go to Filplus.storage
- Login with your GitHub information 
- You'll see a link to "get verified". Click and complete the steps to verify your identification (avoid using Firefox browser).
- Once complete, your application will show a "kyc verified" label for all to see.

Also note: 
- The KYC check process is completed by, [Togggle](http://togggle.io/). 
- During the user data collection process, all gathered information is securely encrypted using the individual user's personal key. This ensures that the data remains confidential and inaccessible, even to Togggle
- Applicant personal information will never show on GitHub applications, only the kyc verified label.
- At any time, applicants can request to have verification information removed from the system, let the Governance team know 

Let me know if you have any issues or questions.

**Comment by brianeggert** [comment]
@kevzak I completed the process and received confirmation on my phone but an error message in my browser. Can you take a look to see which is true? I no longer have a verification option on filplus.storage, which leads me to believe it worked.

**Comment by data-programs** [comment]
<img width="32" alt="KYC" Verified src="https://stable.filplus.storage/images/filplus-kyc-verified-badge.png"/>

This user’s identity has been verified through [filplus.storage](https://filplus.storage)

**Comment by brianeggert** [comment]
> <img alt="KYC" width="32" src="https://camo.githubusercontent.com/2188907b7d327878edccb8f12ad31b1773b3fabc2e82bf9562487cb3c5cd83bd/68747470733a2f2f737461626c652e66696c706c75732e73746f726167652f696d616765732f66696c706c75732d6b79632d76657269666965642d62616467652e706e67">
> 
> This user’s identity has been verified through [filplus.storage](https://filplus.storage)

@kevzak I was able to complete this this morning on the first try. It seems like there was an update. I tried about five times on Monday with Safari on both devices, and mostly it would show a "Continue on PC" message on mobile but hang on "Continue on mobile" in the desktop browser with a loading spinner. One time it showed a success message on mobile but did not show any updates on the desktop site or `filplus.storage`. If you able to give feedback on KYC, the "Continue on PC" message in the event of an error is misleading and should be replaced with an error message and reopen the camera app because once directed to continue on PC which is stuck on "Continue on mobile", refreshing the desktop site reloads the QR code to repeat all the steps on mobile. Whether or not it works, there are no additional steps to continue on PC.

**Comment by kevzak** [comment]
thank you for this feedback @brianeggert. We rolled this product out to a small group of E-Fil clients first. You are all set.

**Comment by herrehesse** [comment]
checker:manualTrigger

**Comment by brianeggert** [comment]
comment for stale bot

**Comment by brianeggert** [comment]
^We're making lots of progress

**Comment by cryptowhizzard** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced3shrkr4p24avcdclld4do2q4n4c675vfwwwsfjci46egj6ek3jm 
#### Address 
> f1i2reokfclrqls5mkgtbqk5esvj6it7nykv7c57y
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1krmypm4uoxxf3g7okrwtrahlmpcph3y7rbqqgfa
#### Id
> 5f3871df-4526-4c85-b00e-74dbaeecf62b
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced3shrkr4p24avcdclld4do2q4n4c675vfwwwsfjci46egj6ek3jm
