### ISSUE TITLE
[DataCap Application] <Organization> - <Project Name>

### ISSUE THREAD

**Issue by chenkun1223** [filecoin-project/filecoin-plus-large-datasets#2032]
### Data Owner Name

Protein Data Bank 3D Structural Biology Data

### What is your role related to the dataset

Storage provider filling out application on behalf of the data owner

### Data Owner Country/Region

United States

### Data Owner Industry

Information, Media & Telecommunications

### Website

https://www.rcsb.org/pages/snapshots

### Social Media

```text
none
```

### Total amount of DataCap being requested

300TB

### Expected size of single dataset (one copy)

30.75TB

### Number of replicas to store

10

### Weekly allocation of DataCap requested

300TiB

### On-chain address for first allocation

f1lmra3skm3wtbtkw7hbk2tvvkjbeza5tj35rwopa

### Data Type of Application

Slingshot

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
none
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
The "Protein Data Bank (PDB) archive" was established in 1971 as the first open-access digital data archive in biology. It is a collection of three-dimensional (3D) atomic-level structures of biological macromolecules (i.e., proteins, DNA, and RNA) and their complexes with one another and various small-molecule ligands (e.g., US FDA approved drugs, enzyme co-factors). For each PDB entry (unique identifier: 1abc or PDB_0000001abc) multiple data files contain information about the 3D atomic coordinates, sequences of biological macromolecules, information about any small molecules/ligands present in the entry, details about the structure-determination experiment, authors and publication information, experimental data, and the wwPDB validation report. Additional content stored in the archive includes documentation, summary reports, and software (among others). The PDB is a jointly-managed core archive of the Worldwide Protein Data Bank partnership [RCSB Protein Data Bank (RCSB PDB, rcsb.org); Protein Data Bank in Europe (PDBe, pdbe.org); Protein Data Bank Japan (PDBj, pdbj.org); Electron Microscopy Data Bank (EMDB, emdb-empiar.org); and Biological Magnetic Resonance Bank (BMRB, bmrb.io)].
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### How do you plan to prepare the dataset

singularity

### Please share a sample of the data

```text
aws s3 ls --no-sign-request s3://pdbsnapshots/
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Sporadic

### For how long do you plan to keep this dataset stored on Filecoin

1.5 to 2 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America

### How will you be distributing your data to storage providers

HTTP or FTP server

### How do you plan to choose storage providers

Slack, Partners

### If you already have a list of storage providers to work with, fill out their names and provider IDs below

```text
f01172521  （owner）
f01843178
f01877259
f02129771
```

### How do you plan to make deals to your storage providers

Singularity

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by chenkun1223** [comment]
> **感谢您的请求！** ❗我们在所提供的信息中发现了一些问题。
> 
> * 地址应以 f1、f2、f3 或 f4 开头
>   请查看请求并编辑问题的正文，提供所有必需的信息。

以修改
f1nn3reuxn3pbwjynoainndamja2o46nan5ch7hlq

**Comment by Sunnyiscoming** [comment]
> Expected size of single dataset (one copy)
> 32GB

How many data in this dataset? Please modify this value.

> f01172521
> f01843178
> f01877259
> f02129771

Which are your nodes?

**Comment by chenkun1223** [comment]
> > Expected size of single dataset (one copy)
> > 32TB
> 
> How many data in this dataset? Please modify this value.
> 
> > f01172521  （owner）
> > f01843178
> > f01877259
> > f02129771
> 
> Which are your nodes?

**Comment by chenkun1223** [comment]
modified

**Comment by Sunnyiscoming** [comment]
Expected size of single dataset (one copy)*Number of replicas to store≠Total amount of DataCap being requested
30.75TB*10≠3PiB

Can you explain about that?

**Comment by chenkun1223** [comment]
> Expected size of single dataset (one copy)_Number of replicas to store≠Total amount of DataCap being requested 30.75TB_10≠3PiB
> 
> Can you explain about that?

Our calculation error has been corrected

Total amount of DataCap being requested
300TB

**Comment by Sunnyiscoming** [comment]
Can you introduce your organizaion? 
Could you send an email to filplus-app-review@fil.org with your official domain in order to confirm your identity? Email name should includes the issue id #2032.

**Comment by chenkun1223** [comment]
> filplus-app-review@fil.org

Send an email to filplus-app-review@fil.org

**Comment by Sunnyiscoming** [comment]
Please disclose the name of your organization and use your official domain send the message.

**Comment by chenkun1223** [comment]
> 请公开您的组织名称并使用您的官方域发送消息。

Hello, we are a small team focused on Filecoin technology research and development and services. We have not established a company or organization. We have managed some nodes and also collaborated with individuals, teams, and small companies. We urgently need this batch of 30TB data for node encapsulation. At the same time, we hope to have more professional data of this kind in the future. We can provide external services such as data download and preview, I look forward to Filecoin's data ecosystem becoming better and better.

**Comment by Sunnyiscoming** [comment]
What percentage of datacap will your nodes store?

**Comment by chenkun1223** [comment]
> 您的节点将存储多少百分比的数据上限？

My node will store 10% of the upper limit data, and then exchange and cooperate with other FIL storage providers to store all the data

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 300TiB

**Expected weekly DataCap usage rate**
> 300TiB

**Client address**
>f1lmra3skm3wtbtkw7hbk2tvvkjbeza5tj35rwopa

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 300TiB

**Expected weekly DataCap usage rate**
> 300TiB

**Client address**
>f1lmra3skm3wtbtkw7hbk2tvvkjbeza5tj35rwopa

**Comment by chenkun1223** [comment]
We are still preparing

**Comment by AlanGreaterheat** [comment]
Would love to see small to medium sized SPs storing public datasets as the first round of willingness to support, I will continue to focus on data dispersion and fast retrieval support

**Comment by sxxfuture-official** [comment]
@chenkun1223 
Please tell me the name of the organization applying for the current LDN, and the corresponding website
Also, what is your relationship with the agency?

**Comment by AlanGreaterheat** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceceqmqgsrpr6othsjhioszp7krmvymsevpzwifkrxxlrtauiuv57s 
#### Address 
> f1lmra3skm3wtbtkw7hbk2tvvkjbeza5tj35rwopa
#### Datacap Allocated
> 13.64TiB
#### Signer Address
> f1pnmzlxj7cfeo2v6oj5nco46hkg2l46wj7o4xxui
#### Id
> 3844cc95-d826-44eb-bc19-41df43ab97e0
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceceqmqgsrpr6othsjhioszp7krmvymsevpzwifkrxxlrtauiuv57s

**Comment by chenkun1223** [comment]
> 希望看到中小型SP存储公共数据集作为第一轮支持意愿，我将继续专注于数据分散和快速检索支持

Thank you very much. We will continue to work hard and hope that the filecoin ecosystem will become better and better

**Comment by chenkun1223** [comment]
> 请告诉我申请当前LDN的组织的名称以及相应的网站 另外，您与该机构的关系是什么？

Hello, our organization is Handian Supercomputing Data, and this is our official website http://www.inscdt.com/ I am the operations engineer of the company

**Comment by sxxfuture-official** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecdjvszgho42bwvwmlcv744djaaxychs5hxkar72yeu5afaio7kc2 
#### Address 
> f1lmra3skm3wtbtkw7hbk2tvvkjbeza5tj35rwopa
#### Datacap Allocated
> 13.64TiB
#### Signer Address
> f1foiomqlmoshpuxm6aie4xysffqezkjnokgwcecq
#### Id
> 3844cc95-d826-44eb-bc19-41df43ab97e0
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecdjvszgho42bwvwmlcv744djaaxychs5hxkar72yeu5afaio7kc2

**Comment by cryptowhizzard** [comment]
checker:manualTrigger

**Comment by chenkun1223** [comment]
checker:manualTrigger

**Comment by w1259980480** [comment]
checker:manualTrigger

**Comment by cryptowhizzard** [comment]
@chenkun1223 

Why is it that you don't follow the rules of Fil+?

**Comment by junyaoren** [comment]
checker:manualTrigger

**Comment by zcfil** [comment]
checker:manualTrigger
