### ISSUE TITLE
[DataCap Application] <Zhejiang Dahua Technology Co., Ltd> - <Environmental monitoring>

### ISSUE THREAD

**Issue by dahuajishu** [filecoin-project/filecoin-plus-large-datasets#2035]
### Data Owner Name

Zhejiang Dahua Technology Co., Ltd

### What is your role related to the dataset

Dataset Owner

### Data Owner Country/Region

China

### Data Owner Industry

Environment

### Website

https://www.dahuatech.com/

### Social Media

```text
https://www.dahuatech.com/
```

### Total amount of DataCap being requested

7PiB

### Expected size of single dataset (one copy)

700T

### Number of replicas to store

10

### Weekly allocation of DataCap requested

1PiB

### On-chain address for first allocation

f154runlmvubcws5g5ufigrsc3kxbqwb2tqhtpj5a

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Zhejiang Dahua Technology Co., Ltd. is the world's leading video-centric intelligent IoT solution provider and operation service provider. Based on the Dahua Think# strategy, the company focuses on the two core businesses of cities and enterprises, firmly adheres to the two major technology strategies of AloT and IoT digital intelligence platform, and comprehensively promotes the digital intelligence upgrade of cities and enterprises around customer needs, creating more value for the digital intelligence transformation of thousands of industries.

In 2022, the company achieved an operating income of 30.565 billion yuan, maintaining a steady development trend. The company now has more than 23,000 employees, of which R&D technicians account for more than 50%. The company invests about 10% of its sales revenue in research and development every year, and is constantly committed to technological innovation, and has established the Advanced Technology Research Institute, Big Data Research Institute, Academia Sinica, Network Security Research Institute and Smart City Research Institute. Relying on the in-depth insight and layout of intelligent IoT, the company continues to explore emerging businesses, extending innovative businesses such as Huacheng, Huarui, Huasense, Huaruijie, Huashi Intelligent Inspection, Huahua, Operating Company, Huayixin, and Huachuang.

Dahua's marketing and service network covers the world, and has established 51 domestic and foreign branches in Asia, North America, South America, Europe, Africa and Oceania, and more than 200 offices in China to provide customers with fast and high-quality services. The company's products and solutions cover 180 countries and regions around the world, widely used in smart city, transportation, people's livelihood, manufacturing, education, energy, finance, environmental protection and other fields, and participated in the Beijing Winter Olympics, China International Import Expo, G20 Hangzhou Summit, Rio Olympic Games, Xiamen BRICS Summit, Shanghai World Expo, Guangzhou Asian Games, Hong Kong-Zhuhai-Macao Bridge and other major engineering projects.

As a national high-tech enterprise, Dahua Co., Ltd. was successfully listed on the A-share market in May 2008 (stock code: 002236), the company has a national postdoctoral scientific research workstation, is a national recognized enterprise technology center, a national innovative pilot enterprise, and now has 38 national scientific research projects. The company has applied for more than 8,000 patents, including more than 390 international patents. From 2008 to 2022, it was listed in the top 100 national software enterprises for 15 consecutive years1; It has been selected as "A&S" "Global Security Top 50" for 16 consecutive years2; won the honors of National Industrial Design Center3, Zhejiang Provincial People's Government Quality Award4, High-quality Development Leading Enterprise 5 and other honors, ranked second in the global intelligent video surveillance market share in the report released by Omdia20216, and is the recommended brand of China's smart city construction7 and the most growing enterprise in the field of intelligent IoT and security ecology8.

Dahua will adhere to the core values of "customer-centric, striver-oriented", practice the mission of "making society safer and life smarter", base itself on the market with excellent quality and service, create more value for customers, and make unremitting efforts to build a safe, intelligent, convenient and efficient society.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
Environmental monitoring data, including sound, images, videos, files, etc
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### How do you plan to prepare the dataset

singularity

### Please share a sample of the data

```text
https://pan.baidu.com/s/1suuOB1S_4btQNgb28XOdmQ?pwd=q20e 
q20e
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Monthly

### For how long do you plan to keep this dataset stored on Filecoin

More than 3 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, South America

### How will you be distributing your data to storage providers

HTTP or FTP server, Shipping hard drives

### How do you plan to choose storage providers

Slack, Big Data Exchange

### How do you plan to make deals to your storage providers

Boost client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by dahuajishu** [comment]
@Sunnyiscoming ![c7bb4a32-7a4a-4cdf-98be-9cc092d561c8](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/133093794/d4d6c08c-2528-4603-a970-d6a2d5503d7e)

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 7PiB

**Expected weekly DataCap usage rate**
> 1PiB

**Client address**
>f154runlmvubcws5g5ufigrsc3kxbqwb2tqhtpj5a

**Comment by zcfil** [comment]
dear,

Thank you for applying for datacap. As a Filecoin FIL+Notary Public, I am currently screening your application and conducting due diligence.

Looking at your application, I have some questions:

You declare that you are a data owner. What hardware do you have on your end to prepare this dataset? What is your internet connection speed? 

Is your data publicly available？

In my opinion, there are many datacaps that apply for 7PB. People need to have a comprehensive understanding of Filecoin, data packaging, data distribution, and all the requirements that come with it. Are you a novice in the Filecoin field, or have you previously applied for datacap on different Github account names?

As a final question, I would like you to fill out this [form](https://form.jotform.com/230953098450156) in order to provide us with the necessary information to make a wise decision on your LDN request when we are willing to support it.

thank you!

**Comment by dahuajishu** [comment]
@zcfil Thank you for your reply，
My dataset is stored on our own server, 2GB dedicated line，
My data is publicly available，
In the previous application for LDN, I have become proficient in data distribution, data packaging, and more
The form has been filled out. Thank you again for your review.

**Comment by dahuajishu** [comment]
Hi @DaYouGroup I am currently out of the company and unable to log in to the server. Here is a screenshot of our backend monitoring system. ![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/133093794/5b26a02a-66c6-4963-8967-4615100f552f)

**Comment by bq1024** [comment]
Do you already have a list of storage providers to work with?

**Comment by dahuajishu** [comment]
f0872282 in HK
f0399760 in GuangZhou
f01660795 in ShenZhen
f01877184 in Singapore
Thank you for your reply！

**Comment by bq1024** [comment]
You should distribute deals to more geographies. If you have trouble finding SPs, please take a look at https://docs.filswan.com/swan-client/overview

**Comment by bq1024** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebioiz5tiaysor4oe4jrrusjwfzw6gjbsgrarnxa6phde3xscimga 
#### Address 
> f154runlmvubcws5g5ufigrsc3kxbqwb2tqhtpj5a
#### Datacap Allocated
> 358.39TiB
#### Signer Address
> f1pkjtavqx4r2q2w3he3jknfc5mo2vgfimccmpnaa
#### Id
> 9280e7a2-7b1f-47a0-80b7-f8979f32fa18
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebioiz5tiaysor4oe4jrrusjwfzw6gjbsgrarnxa6phde3xscimga

**Comment by dahuajishu** [comment]
checker:manualTrigger

**Comment by dahuajishu** [comment]
checker:manualTrigger

**Comment by dahuajishu** [comment]
checker:manualTrigger

**Comment by dahuajishu** [comment]
checker:manualTrigger

**Comment by cryptowhizzard** [comment]
I have a Q about this LDN.

f01923787, f01923786 and f01859603 have a problematic record in #512 

Why are you working with this SP's?


sp | client | totaldeals | ipadres | port | pname | Online | subnet | MIS | location | vpnresults | % | AT | asource | masteraddres | A-LDN-name | auditTrail
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
f01927554 | f02208908 | 51024211476480 | 103.201.24.40 | 50001 | customer of mike | 1 | 103.201.24 | 6 | HK , Hong Kong , Hong Kong | TRUE with fraudscore 80 | 13 | 11 | <a href="http://datacapstats.io/clients?filter=" target="_blank""></a> | f1khdd2v7il7lxn4zjzzrqwceh466mq5k333ktu7q |   |  
f01923787 | f02208908 | 57827439673344 | 14.215.165.40 | 50001 | mike-f01836766 | 1 | 14.215.165 | 2 | CN , Guangdong , Guangzhou | TRUE with fraudscore 82 | 15 | 1 | <a href="http://datacapstats.io/clients?filter=f01904436" target="_blank"">f01904436</a> | f3sonznjun7e5dvre7nlrhg4zobtyf7xdrvw644qypejmiteblrfqhpo4ya34ywxukzlxefltccbfurjtb5pyq | Shenzhen kuaixue Education Development Co., Ltd | https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/512
f01923786 | f02208908 | 55181739819008 | 103.201.24.41 | 50001 | customer of mike | 1 | 103.201.24 | 6 | HK , Hong Kong , Hong Kong | TRUE with fraudscore 80 | 14 | 1 | <a href="http://datacapstats.io/clients?filter=f01904436" target="_blank"">f01904436</a> | f3qi43eeu2xrmzwqwsefof4u2rrjekm4jc6ldosqhmt6jbytaseu7xo3ak6efofhavejcxz7crzaxj24xpaydq | Shenzhen kuaixue Education Development Co., Ltd | https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/512
f01938674 | f02208908 | 71880572665856 | 183.60.90.194 | 50001 | SWK-f01953985 | 1 | 183.60.90 | 3 | CN , Guangdong , Guangzhou | FALSE with fraudscore 0 | 18 |   | <a href="http://datacapstats.io/clients?filter=" target="_blank""></a> | f1ldcltpmc4gwtxjcj2uvvvagr6222o26sa37szyy |   |  
f01859603 | f02208908 | 75763223101440 | 14.18.234.122 | 50001 | mike-f01859603 | 1 | 14.18.234 | 1 | CN , Guangdong , Guangzhou | FALSE with fraudscore 0 | 19 | 1 | <a href="http://datacapstats.io/clients?filter=f01904436" target="_blank"">f01904436</a> | f3ugnfhqqzm5lkff3jhdzkdrxprsjjc77cxldgxpxfo4rsm2zodjffxm6lf7kiwqdna6yhvrthk2efsugys3ba | Shenzhen kuaixue Education Development Co., Ltd | https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/512
f01938671 | f02208908 | 74698071212032 | 103.201.24.42 | 50001 | customer of mike | 1 | 103.201.24 | 6 | HK , Hong Kong , Hong Kong | TRUE with fraudscore 80 | 19 | 11 | <a href="http://datacapstats.io/clients?filter=" target="_blank""></a> | f3sm4bzapkm3rds7bj6olkwbrkeqv2hxjnwmkj24qyibgkm5ntdbx5igs32pmleu54tlkkkzskpgdmhneuww4a |   |  
f02237006 | f02208908 | 3401614098432 | 91.205.228.128 | 56801 | zoen | 1 | 91.205.228 | 3 | GB , England , Whitley Bay | TRUE with fraudscore 75 | 1 |   | <a href="http://datacapstats.io/clients?filter=" target="_blank""></a> |   |   |  
f02237010 | f02208908 | 2886218022912 | 23.224.22.163 | 56802 | ipfsfy.com | 1 | 23.224.22 | 3 | US , California , Los Angeles | TRUE with fraudscore 94 | 1 |   | <a href="http://datacapstats.io/clients?filter=" target="_blank""></a> |   |   |  


sp	client	totaldeals	ipadres	port	pname	Online	subnet	MIS	location	vpnresults	%	AT	asource	masteraddres	A-LDN-name	auditTrail
f01927554	f02208908	51024211476480	103.201.24.40	50001	customer of mike	1	103.201.24	6	HK , Hong Kong , Hong Kong	TRUE with fraudscore 80	13	11	<a href="http://datacapstats.io/clients?filter=" target="_blank""></a>	f1khdd2v7il7lxn4zjzzrqwceh466mq5k333ktu7q		
f01923787	f02208908	57827439673344	14.215.165.40	50001	mike-f01836766	1	14.215.165	2	CN , Guangdong , Guangzhou	TRUE with fraudscore 82	15	1	<a href="http://datacapstats.io/clients?filter=f01904436" target="_blank"">f01904436</a>	f3sonznjun7e5dvre7nlrhg4zobtyf7xdrvw644qypejmiteblrfqhpo4ya34ywxukzlxefltccbfurjtb5pyq	Shenzhen kuaixue Education Development Co., Ltd	https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/512
f01923786	f02208908	55181739819008	103.201.24.41	50001	customer of mike	1	103.201.24	6	HK , Hong Kong , Hong Kong	TRUE with fraudscore 80	14	1	<a href="http://datacapstats.io/clients?filter=f01904436" target="_blank"">f01904436</a>	f3qi43eeu2xrmzwqwsefof4u2rrjekm4jc6ldosqhmt6jbytaseu7xo3ak6efofhavejcxz7crzaxj24xpaydq	Shenzhen kuaixue Education Development Co., Ltd	https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/512
f01938674	f02208908	71880572665856	183.60.90.194	50001	SWK-f01953985	1	183.60.90	3	CN , Guangdong , Guangzhou	FALSE with fraudscore 0	18		<a href="http://datacapstats.io/clients?filter=" target="_blank""></a>	f1ldcltpmc4gwtxjcj2uvvvagr6222o26sa37szyy		
f01859603	f02208908	75763223101440	14.18.234.122	50001	mike-f01859603	1	14.18.234	1	CN , Guangdong , Guangzhou	FALSE with fraudscore 0	19	1	<a href="http://datacapstats.io/clients?filter=f01904436" target="_blank"">f01904436</a>	f3ugnfhqqzm5lkff3jhdzkdrxprsjjc77cxldgxpxfo4rsm2zodjffxm6lf7kiwqdna6yhvrthk2efsugys3ba	Shenzhen kuaixue Education Development Co., Ltd	https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/512
f01938671	f02208908	74698071212032	103.201.24.42	50001	customer of mike	1	103.201.24	6	HK , Hong Kong , Hong Kong	TRUE with fraudscore 80	19	11	<a href="http://datacapstats.io/clients?filter=" target="_blank""></a>	f3sm4bzapkm3rds7bj6olkwbrkeqv2hxjnwmkj24qyibgkm5ntdbx5igs32pmleu54tlkkkzskpgdmhneuww4a		
f02237006	f02208908	3401614098432	91.205.228.128	56801	zoen	1	91.205.228	3	GB , England , Whitley Bay	TRUE with fraudscore 75	1		<a href="http://datacapstats.io/clients?filter=" target="_blank""></a>			
f02237010	f02208908	2886218022912	23.224.22.163	56802	[ipfsfy.com](http://ipfsfy.com/)	1	23.224.22	3	US , California , Los Angeles	TRUE with fraudscore 94	1		<a href="http://datacapstats.io/clients?filter=" target="_blank""></a>

**Comment by cryptowhizzard** [comment]
![Scherm­afbeelding 2023-07-28 om 13 19 39](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/36404435/26acac87-9482-4637-a6f0-600ab04d7465)

Inserting screenshot for visibility.

**Comment by dahuajishu** [comment]
@cryptowhizzard It was SPs who contacted me, and I was not aware of their previous events.

**Comment by dahuajishu** [comment]
checker:manualTrigger

**Comment by cryptowhizzard** [comment]
<img width="1548" alt="Scherm­afbeelding 2023-08-09 om 16 58 44" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/36404435/d083eca3-7069-41a5-9670-ed2e02e063a3">

This is not going in the right direction. Only 3 SP's are online?

**Comment by dahuajishu** [comment]
> <img alt="Scherm­afbeelding 2023-08-09 om 16 58 44" width="1548" src="https://user-images.githubusercontent.com/36404435/259452826-d083eca3-7069-41a5-9670-ed2e02e063a3.png">
> This is not going in the right direction. Only 3 SP's are online?

I inquired about the reason and they explained that they are currently planning to relocate to another city due to local restrictions

**Comment by clriesco** [comment]
Removed stale label, reopened issue :)
