### ISSUE TITLE
[DataCap Application] ENCODE-Encyclopedia of DNA Elements

### ISSUE THREAD

**Issue by cenhubert** [filecoin-project/filecoin-plus-large-datasets#2036]
### Data Owner Name

ENCODE Data Coordinating Center

### What is your role related to the dataset

Data Preparer

### Data Owner Country/Region

United States

### Data Owner Industry

Life Science / Healthcare

### Website

https://www.encodeproject.org/

### Social Media

```text
https://twitter.com/EncodeDCC
```

### Total amount of DataCap being requested

15PiB

### Expected size of single dataset (one copy)

1.2PiB

### Number of replicas to store

7

### Weekly allocation of DataCap requested

1PiB

### On-chain address for first allocation

f1fbff7wmio7opql7aprlqx5af65gw7tsk56z53kq

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
I'm Hubert - individual dp. The project I'd like to join in filecoin is storing the data I've downloaded before. The data is from the Encode. The ENCODE Consortium not only produces high-quality data, but also analyzes the data in an integrative fashion. The ENCODE Encyclopedia organizes the most salient analysis products into annotations and provides tools to search and visualize them. The goal of ENCODE is to build a comprehensive parts list of functional elements in the human genome, including elements that act at the protein and RNA levels, and regulatory elements that control cells and circumstances in which a gene is active.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
Released and archived ENCODE data. Regulatory elements are typically investigated through DNA hypersensitivity assays, assays of DNA methylation, and immunoprecipitation (IP) of proteins that interact with DNA and RNA, i.e., modified histones, transcription factors, chromatin regulators, and RNA-binding proteins, followed by sequencing.
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### How do you plan to prepare the dataset

IPFS, lotus, singularity

### Please share a sample of the data

```text
https://registry.opendata.aws/encode-project/
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Sporadic

### For how long do you plan to keep this dataset stored on Filecoin

2 to 3 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, Europe

### How will you be distributing your data to storage providers

HTTP or FTP server, IPFS, Shipping hard drives, Lotus built-in data transfer

### How do you plan to choose storage providers

Slack, Big Data Exchange, Partners

### If you already have a list of storage providers to work with, fill out their names and provider IDs below

```text
I'll make sure with the suitable ones as soon.
```

### How do you plan to make deals to your storage providers

Boost client, Lotus client, Singularity

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
Expected size of single dataset (one copy)*Number of replicas to store
1.2PiB*7=8.4PiB
Why do you apply for 15 PiB datacap?

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 15PiB

**Expected weekly DataCap usage rate**
> 1PiB

**Client address**
>f1fbff7wmio7opql7aprlqx5af65gw7tsk56z53kq

**Comment by cenhubert** [comment]
Hello @Sunnyiscoming , thanks for your concern. Due to our technology's setting, we'll put 18 GiB data into a car file. And a car file need 32GiB of datacap. So we need 15PiB datacap in total.

**Comment by cenhubert** [comment]
@spaceT9 I've finished downloading this dataset and the size is 1.2PiB. I've checked it on AWS.
I'm not the owner of this dataset. It is a public dataset, so every one can store it.

**Comment by raghavrmadya** [comment]
Hi, thanks for the comment. The T&T WG is actively working to prevent DC abuse and we are seeing trends where certain clients are abusing DC through open datasets. Why do you think storing this dataset again is valuable? How has it been prepared differently

**Comment by cenhubert** [comment]
@raghavrmadya I think what we do will help spread and store the data. We use own way to prepare data in higher speed so that we can save time on it.
