### ISSUE TITLE
[DataCap Application] Exbee

### ISSUE THREAD

**Issue by oneforalone** [filecoin-project/filecoin-plus-large-datasets#2038]
### Data Owner Name
Exbee

### What is your role related to the dataset
Storage provider filling out application on behalf of the data owner

### Data Owner Country/Region
China

### Data Owner Industry
Web3 / Crypto

### Website
[https://exbee.io](https://exbee.io)

### Social Media
N/A (N/A)

### Total amount of DataCap being requested
2 PiB

### Expected size of single dataset (one copy)
400 TiB

### Number of replicas to store
5

### Weekly allocation of DataCap requested
100 TiB

### On-chain address for first allocation
f13lv6rz3cuhsq436xzrnitrsatgpxo7d7zawvveq

### Data Type of Application
Public, Open Dataset (Research/Non-Profit)

### Custom multisig
No

### Share a brief history of your project and organization
Exbee is a marketplace for cryptocurrencies and virtual goods trading,
developed by Singapore-based BITBEE PTE. LTD. The demo video is: https://youtu.be/HJUMCcOaSKg. It currently supports trading of gift cards and cryptocurrencies.The founding team is from Alibaba's core e-commerce technology team, which has been responsible for the work related to marketing and transactions of Tmall and Taobao, as well as user growth technology of Taote App. We have continuous entrepreneurial experience in the blockchain/web3 field, very deep
industry knowledge in the direction of gift card trading, and have team members who are locally responsible for market cooperation in less developed regions such as Southeast Asia and Africa.

### Is this project associated with other projects/ecosystem stakeholders?
No

### If answered yes, what are the other projects/ecosystem stakeholders
n/a

### Describe the data being stored onto Filecoin
Exbee platform relevant materials such as some network node backups, logs, video tutorial, documents, etc.

### Where was the data currently stored in this dataset sourced from
Google Cloud

### If you answered "Other" in the previous question, enter the details here
n/a

### How do you plan to prepare the dataset
graphsplit

### If you answered "other/custom tool" in the previous question, enter the details here
n/a

### Please share a sample of the data
https://drive.google.com/file/d/1HJa0GQsmepRX1fP-CQANF4Lvxx7t5Qzc/view?usp=sharing
https://drive.google.com/file/d/1QOE3s8A9_iNZJOZglGVC_NVah_j0yzf6/view?usp=sharing
https://drive.google.com/file/d/1rrZ1yF-eQvvNERgu_J19BlEdt9nP2hbs/view?usp=sharing
https://drive.google.com/file/d/1zj5U34tHUZy3b_JGjx0HMn8gmiCX6gKL/view?usp=sharing

### Confirm that this is a public dataset that can be retrieved by anyone on the Network
Yes

### If you chose not to confirm, what was the reason
n/a

### What is the expected retrieval frequency for this data
Yearly

### For how long do you plan to keep this dataset stored on Filecoin
1.5 to 2 years

### In which geographies do you plan on making storage deals
Greater China, Europe, North America

### How will you be distributing your data to storage providers
Others

### How do you plan to choose SP
Partners

### If you answered "Others" in the previous question, what is the tool or platform you plan to use
n/a

### If you already have a list of storage providers to work with, fill out their names and provider IDs below
f01208862, f015233, f0498868, f010617, f0406478

### How do you plan to make deals to your storage providers
Boost client

### If you answered "Others/custom tool" in the previous question, enter the details here
n/a

### Can you confirm that you will follow the Fil+ guideline
Yes

_Application created via [filplus.storage](https://filplus.storage)_

**Comment by oneforalone** [comment]
This is related to issue #1076. But I did not get any response after a week. So i decided to reopen it agian. Please kindly leave a comment if any questions. Thanks.

**Comment by Sunnyiscoming** [comment]
Expected size of single dataset (one copy)Number of replicas to store≠Total amount of DataCap being requested
1TB*5≠2PiB

Can you explain about that?

**Comment by oneforalone** [comment]
> Expected size of single dataset (one copy)Number of replicas to store≠Total amount of DataCap being requested 1TB*5≠2PiB
> 
> Can you explain about that?

Oh, I'm sorry. I mis-understand the meaning of one single dataset (one copy). I thought it was just the average of one file in the dataset. The total size of one dataset is approximately 350 TiB ~ 400 TiB, the replicas number is 5, 400 TiB * 5 = 2 PiB. Therefore, I apply to 2 PiB.

**Comment by Sunnyiscoming** [comment]
Please modify this value.

**Comment by oneforalone** [comment]
Ok, Done.

**Comment by Sunnyiscoming** [comment]
Could you send an email to filplus-app-review@fil.org with your official domain in order to confirm your identity? Email name should includes the issue id #2038.

**Comment by oneforalone** [comment]
We're contacting some natories on slack channel, still waiting for answers.

**Comment by zcfil** [comment]
I have reviewed the data samples and most of them are some log data. Log data is usually classified as non-public data. Could you please explain？
Or do you have any other sample data, such as video tutorials.

**Comment by oneforalone** [comment]
1. Our platform is considering an open, transparent, trustless exchange, so all the information would be public and open sources. Therefore, it's make very sense that logs should be public.
2. Sure, we've already upload an tutorial video to Youtube, please check it out via: https://www.youtube.com/watch?v=HJUMCcOaSKg

**Comment by zcfil** [comment]
Can you provide some supporting materials to prove that you have 400T of data?

**Comment by oneforalone** [comment]
Yeah, see the pics below, we currently storing the data on our own servers:
<img width="447" alt="image" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/41844215/1a92d31e-d40f-491b-b469-6398b81168bd">

**Comment by ipollo00** [comment]
@oneforalone 
From my end, I think notaries should support entity, especially web3 companies to store data through Fil+ project.  That's the valuable and practicality of data, especially HTTP retrieval has been realized. 
Willing to support the first round to see whether your sps are reachable and whether data can be retrieved.

**Comment by ipollo00** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedqmbwv4e6twmmklglsldlx4swnhwelk6jicnklgubrvcgf3gwrds 
#### Address 
> f13lv6rz3cuhsq436xzrnitrsatgpxo7d7zawvveq
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1n5wlrrhoxpkgwij25xrtt7w7g2k3fhbthmdn6ri
#### Id
> efc2843b-b743-44b1-86a0-6753408c6078
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedqmbwv4e6twmmklglsldlx4swnhwelk6jicnklgubrvcgf3gwrds

**Comment by oneforalone** [comment]
> @oneforalone From my end, I think notaries should support entity, especially web3 companies to store data through Fil+ project. That's the valuable and practicality of data, especially HTTP retrieval has been realized. Willing to support the first round to see whether your sps are reachable and whether data can be retrieved.

@ipollo00 Very appreciate for that, especially under the circumstances of the bear market.

**Comment by oneforalone** [comment]
Still waiting some notaries to response in Slack Channel, just need some more time.

**Comment by cryptowhizzard** [comment]
Hey,

I am interested in this project and am willing to sign if you can do KYC with us. Is this possible?
If so, please fill out the form in [this link](https://form.jotform.com/230337462961356)

**Comment by oneforalone** [comment]
> am willing to sign if you can do KYC with us. Is this possible?

@cryptowhizzard May I know why the KYC? I mean, all information is clear in the DC applications. 

If you got any questions about this project, just leave a comment, and i will answer that as best as i can.  But KYC, i don't get it.

**Comment by cryptowhizzard** [comment]
> > am willing to sign if you can do KYC with us. Is this possible?
> 
> @cryptowhizzard May I know why the KYC? I mean, all information is clear in the DC applications.
> 
> If you got any questions about this project, just leave a comment, and i will answer that as best as i can. But KYC, i don't get it.

Sure, i will explain: 

All notary's should do KYC. That's in their rules and guidelines. Some notary's don't perform this as they refuse to align with the rules, i don't want to judge on why but that is up to them.

You can check the latest status [here](https://github.com/filecoin-project/notary-governance/issues/925)

If you want / are interested please [check here](https://form.jotform.com/230337462961356)

**Comment by oneforalone** [comment]
I see, thanks for your explaining.

Already submitted the form. Please check it out. But there's one wrong information cause i can not make the phone number correct, due to the shorten of digits. Maybe you should make the Phone Number field more universal.

**Comment by cryptowhizzard** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceagsn27arc7e22na6dcrka5nh4w54r5ukvtco6bduyqq2fx45p4xc 
#### Address 
> f13lv6rz3cuhsq436xzrnitrsatgpxo7d7zawvveq
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1krmypm4uoxxf3g7okrwtrahlmpcph3y7rbqqgfa
#### Id
> efc2843b-b743-44b1-86a0-6753408c6078
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceagsn27arc7e22na6dcrka5nh4w54r5ukvtco6bduyqq2fx45p4xc

**Comment by oneforalone** [comment]
Appreciate for that, hopes all go well with the first allocation.

**Comment by oneforalone** [comment]
Hi, cause we are transferring the data offline, which means that would take some time for provider to receive the data. And unfortunately, this shipment got delayed for bad whether, and the data arrived to the provider today. However, we got an error while sending the deal, which says: `deal rejected: deal start epoch has already elapsed`, what should i do now? Could someone here to help?

**Comment by oneforalone** [comment]
@ipollo00 @cryptowhizzard Could you give me some support? Or am i doing the wrong thing? Should I send the deal once the dc granted, and the sealing can wait for a while, is that right?

**Comment by cryptowhizzard** [comment]
> @ipollo00 @cryptowhizzard Could you give me some support? Or am i doing the wrong thing? Should I send the deal once the dc granted, and the sealing can wait for a while, is that right?

Hi,

I noticed Fei-Yan answered you already on slack. Is it solved now?

**Comment by oneforalone** [comment]
Yeah, I finally figure it out how to send deals with boost.

**Comment by oneforalone** [comment]
@cryptowhizzard Do you have any idea of quota does not match the actual sealed power. Our storage provider `f02329205`  only seal 36TiB of the data, but now it says that we are out of the quota, the DC is just 80M remains, where is the missing 14 TiB DC? And now we can not make deals proposal due to the shortage of DC quota.

**Comment by cryptowhizzard** [comment]
<img width="1567" alt="Scherm­afbeelding 2023-08-13 om 09 11 11" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/36404435/781116d4-2e09-4a97-a533-99115c911704">

**Comment by cryptowhizzard** [comment]
checker:manualTrigger

**Comment by cryptowhizzard** [comment]
@oneforalone 

Seems that you did not distribute deals to other providers.
Seems retrieval is not worker yet.

?

**Comment by oneforalone** [comment]
We currently just sent the data for 1 providers for the initiating and testing. And planing to distribute to other providers after the testing procedure went well. 
As for retrieval, our provider tell me that they did not enable online retrieval for saving their bandwidth, i'll contact them later. 

So the mis-match with DC and the provider power is related with boost? I'll go to boost channel for help. Thanks in advance.

**Comment by cryptowhizzard** [comment]
> We currently just sent the data for 1 providers for the initiating and testing. And planing to distribute to other providers after the testing procedure went well. As for retrieval, our provider tell me that they did not enable online retrieval for saving their bandwidth, i'll contact them later.
> 
> So the mis-match with DC and the provider power is related with boost? I'll go to boost channel for help. Thanks in advance.

Consider this a warning. Rules of Fil+ state that data needs to be readily retrievable. “Saving bandwidth” is no excuse. Please have it enable asap.

**Comment by oneforalone** [comment]
> 

After communicating with our storage provider, now they make it enabled for HTTP and bitswap enabled both. I've verify with boost in myside. Here is the result:<img width="746" alt="image" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/41844215/92f031c1-dcd1-4fe5-87a4-54c3fcacce61">

**Comment by maxvint** [comment]
checker:manualTrigger

**Comment by oneforalone** [comment]
@cryptowhizzard @maxvint Seems the provider's http retrieval is on now, is there any other thing that i can improve?

**Comment by cryptowhizzard** [comment]
I am running retrieval testing. Let's see.

**Comment by oneforalone** [comment]
How's going now? Any updates?

**Comment by cryptowhizzard** [comment]
ERROR: offer error: retrieval query offer errored: failed to fetch piece to retrieve from: getting pieces for cid baga6ea4seaqeevmgt3ch46p3z3ompagpz65nqaodu3ep2hlbojtfhvcyq5omqai: getting pieces containing block baga6ea4seaqeevmgt3ch46p3z3ompagpz65nqaodu3ep2hlbojtfhvcyq5omqai: failed to lookup index for mh 9220204255869ec47e79fbcedcc780cfcfbad801c3a6c8fd1d61726653d458875cc801, err: datastore: key not found

**Comment by cryptowhizzard** [comment]
Dear oneforalone,

As notary I am doing due diligence on your LDN. I could not get retrieval to work. Can you please upload the car file of CID baga6ea4seaqeevmgt3ch46p3z3ompagpz65nqaodu3ep2hlbojtfhvcyq5omqai ?

You can use our upload system at http://send.datasetcreators.com. Please select 7 days for the system to keep the file and post the link you received here so I (and other notaries) can download your content.

**Comment by oneforalone** [comment]
> As notary I am doing due diligence on your LDN. I could not get retrieval to work. Can you please upload the car file of CID baga6ea4seaqeevmgt3ch46p3z3ompagpz65nqaodu3ep2hlbojtfhvcyq5omqai ?

@cryptowhizzard Thanks for you effort. I've already upload the file to your system at https://send.datasetcreators.com/download/32760bf581ddb819/#Bl50xcAW-1pm14jQAnCThQ, and i set the file validate for 7 days as well as 50 downloads limitation. Hope that helps.

**Comment by cryptowhizzard** [comment]
> > As notary I am doing due diligence on your LDN. I could not get retrieval to work. Can you please upload the car file of CID baga6ea4seaqeevmgt3ch46p3z3ompagpz65nqaodu3ep2hlbojtfhvcyq5omqai ?
> 
> @cryptowhizzard Thanks for you effort. I've already upload the file to your system at https://send.datasetcreators.com/download/32760bf581ddb819/#Bl50xcAW-1pm14jQAnCThQ, and i set the file validate for 7 days as well as 50 downloads limitation. Hope that helps.

Thanks.

Carfile validated. It matches commP. However i could not unpack it.

Perhaps another notary can try?
