### ISSUE TITLE
> Expected size of single dataset (one copy)

### ISSUE THREAD

**Issue by chenkun1223** [filecoin-project/filecoin-plus-large-datasets#2039]
> Expected size of single dataset (one copy)
> 30.75TB

How many data in this dataset? Please modify this value.

> f01172521 （owner）
> f01843178
> f01877259
> f02129771

Which are your nodes?

_Originally posted by @Sunnyiscoming in https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/2032#issuecomment-1573843599_

**Comment by Sunnyiscoming** [comment]
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/2032
Please comment on this issue.
