### ISSUE TITLE
[DataCap Application] Korea Herald

### ISSUE THREAD

**Issue by KoreaHerald** [filecoin-project/filecoin-plus-large-datasets#204]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Korea Herald
- Website / Social Media: www.koreaherald.com
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 3 PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100 TiB
- On-chain address for first allocation: f3vs676it2cxksyo5udykuc2zhfm5pe3r2gvez4y3i2fb3brgxx7vvf5pmrn62zavik3h4rjxx4bh5ct7neb7q

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
The Korea Herald is a leading English-language daily newspaper founded in 1953 and published in Seoul, South Korea. The editorial staff is composed of Korean and international writers and editors, with additional news coverage drawn from international news agencies such as the Associated Press.
The Korea Herald is operated by Herald Corporation. Herald Corporation also publishes The Herald Business, a Korean-language business daily, The Junior Herald, an English weekly for teens, The Campus Herald, a Korean-language weekly for university students. Herald Media is also active in the country's booming English as a foreign language sector, operating a chain of hagwons as well as an English village. The Korea Herald is a member of the Asia News Network.
```

What is the primary source of funding for this project?
```
Our company. 
```

What other projects/ecosystem stakeholders is this project associated with?
```
Meta Cloud Service, it is our peer company. Also Meta C&C said if we grant Datacap, they would help us to store our data in to their SPs and 4 other continents’ SPs for free. 
```

## Use-case details

Describe the data being stored onto Filecoin
```
Since we are a newspaper company, we have a large scale of data from interviews, research materials, and many different kind of data. The reason why we can not delete the data is that there is a lot of demand for us to write articles that look at the present compared to past data and to be able to see past data later. We want our data to be preserved for a long time and securely. 
```

Where was the data in this dataset sourced from?
```
Mostly South Korea, some from Asia, 
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
yes
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes, it is a public dataset. 
![hybe](https://user-images.githubusercontent.com/97571287/149061248-c8c28077-1725-414b-9723-54753f6aa4b6.jpg)
![20220112000353_광주](https://user-images.githubusercontent.com/97571287/149061254-12f5bcfe-af34-4c7d-9757-6d8b87e80abf.jpg)

```

What is the expected retrieval frequency for this data?
```
Our datas are informative contents, and open data. Expected search frequency is not that high, because we need to store our data for a long time, and we will retrieve those data when we nedd to use for writing news. In the long term its retrieval frequency will be higher than future 3~4 years.

```

For how long do you plan to keep this dataset stored on Filecoin?
```
We consider this storage as a permanent archive. we need to preserve our data for a long time to write news comparing past and now. Also, we will constantly upload our data, because our company have too many data to be stored. 
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
we plan to store data in each continents’ SPs. We plan to make replicas and store it in various SPs. In this way it would be easier for our reporters all over the world to retrieve datas in their location. Furthermore, company has many back ups in this way. 
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
We are planning to use both online and offline transfer. 
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We will select miners in each continent through miners by slack. 
```

How will you be distributing deals across storage providers?
```
We will use both online and offline transfer.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
We have enough fund for ourselves. We have been hacked our data(related to politics) once. Therefore our company’s young team managers want to start making deals as soon as possible. Since, this march Korea have president election. So, before that time we need to store our datas with lots of back up in various continents. We already have technology to make deals and use Datacap.(As Meta C&C said they would help with this). 
```

**Comment by IPFSUnion** [comment]
Do you have a contact email from your official domain?

**Comment by IPFSUnion** [comment]
Do you have a contact email from your official domain?
