### ISSUE TITLE
[DataCap Application] Ogcloud

### ISSUE THREAD

**Issue by Frank-jinxin** [filecoin-project/filecoin-plus-large-datasets#2043]
### Data Owner Name
Ogcloud

### What is your role related to the dataset
Dataset Owner

### Data Owner Country/Region
Hong Kong

### Data Owner Industry
Information, Media & Telecommunications

### Website
[www.ogcloud.com](www.ogcloud.com)

### Social Media
www.ogcloud.com (web)

### Total amount of DataCap being requested
5 PiB

### Expected size of single dataset (one copy)
1 TiB

### Number of replicas to store
9

### Weekly allocation of DataCap requested
500 TiB

### On-chain address for first allocation
f3qb7wa7fr3akqookyxwbyfcbqfb3ipouzirpyjnaxflvkmj77mhk6w2rnxtysx2orprfnznwkmfezlqli6ola

### Data Type of Application
Public, Open Commercial/Enterprise

### Custom multisig
No

### Share a brief history of your project and organization
OgCloud is a cloud computing service brand independently developed by Tianyun Technology.

### Is this project associated with other projects/ecosystem stakeholders?
No

### If answered yes, what are the other projects/ecosystem stakeholders
n/a

### Describe the data being stored onto Filecoin
Our customer types are rich, and the types of data that need to be stored are also comprehensive, including but not limited to: videos, documents, photos, voices...

### Where was the data currently stored in this dataset sourced from
My own storage infra

### If you answered "Other" in the previous question, enter the details here
n/a

### How do you plan to prepare the dataset
lotus

### If you answered "other/custom tool" in the previous question, enter the details here
n/a

### Please share a sample of the data
We are the background management, and the front display needs to go through the customer portal.

### Confirm that this is a public dataset that can be retrieved by anyone on the Network
Yes

### If you chose not to confirm, what was the reason
n/a

### What is the expected retrieval frequency for this data
Weekly

### For how long do you plan to keep this dataset stored on Filecoin
Permanently

### In which geographies do you plan on making storage deals
Greater China

### How will you be distributing your data to storage providers
Lotus built-in data transfer

### How do you plan to choose SP
I don't know yet

### If you answered "Others" in the previous question, what is the tool or platform you plan to use
n/a

### If you already have a list of storage providers to work with, fill out their names and provider IDs below
n/a

### How do you plan to make deals to your storage providers
Lotus client

### If you answered "Others/custom tool" in the previous question, enter the details here
n/a

### Can you confirm that you will follow the Fil+ guideline
Yes

_Application created via [filplus.storage](https://filplus.storage)_

```[tasklist]
### Tasks
```

```[tasklist]
### Tasks
```

**Comment by Frank-jinxin** [comment]
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1215

**Comment by Sunnyiscoming** [comment]
> Describe the data being stored onto Filecoin
> Our customer types are rich, and the types of data that need to be stored are also comprehensive, including but not limited to: videos, documents, photos, voices...

Whether you are authorized by customers to store these data as public data?

> Please share a sample of the data
> We are the background management, and the front display needs to go through the customer portal.
How can we prove that the customer's data is publicly available if the data sample cannot be shown and how to prove you have 5 PB data storage request? 

Please share more detailed information about sps you will cooperate with.

Could you send an email to filplus-app-review@fil.org with your official domain in order to confirm your identity? Email name should includes the issue id #2043.

**Comment by Frank-jinxin** [comment]
I have already sent the email, please check it carefully.
Please contact me promptly if you have any questions.

**Comment by Sunnyiscoming** [comment]
Please share more detailed information about sps you will cooperate with.

**Comment by Sunnyiscoming** [comment]
Any update here?

**Comment by Frank-jinxin** [comment]
After this period of time, I have contacted the corresponding SPS.
Here are their node numbers:
F02105377 Hong Kong, China
F02199393 Hong Kong, China
F059813 Chinese Mainland
F01983521 Vietnam
F02230353 USA

now we have extracted some files for display here.The following is a link to display the data:
https://drivegoogle.com/drive/folders/1VcaCbGliloodBxMwhywy8VmX-advgJEK?usp=sharing

**Comment by Frank-jinxin** [comment]
After this period of time, I have contacted the corresponding SPS.
Here are their node numbers:
f02105377 Hong Kong, China
f02199393 Hong Kong, China
f059813 Chinese Mainland
f01983521 Vietnam
f02230353 USA

now we have extracted some files for display here.The following is a link to display the data:
https://drivegoogle.com/drive/folders/1VcaCbGliloodBxMwhywy8VmX-advgJEK?usp=sharing

 we have accumulated it for many years.

**Comment by Sunnyiscoming** [comment]
Please check the link. https://drivegoogle.com/drive/folders/1VcaCbGliloodBxMwhywy8VmX-advgJEK?usp=sharing
I can  not open it.

**Comment by Frank-jinxin** [comment]
https://drive.google.com/drive/folders/1VcqCbGliLoodBxMwhywy8VmX-advgJEK?usp=sharing

**Comment by Frank-jinxin** [comment]
https://drivegoogle.com/drive/folders/1VcaCbGliloodBxMwhywy8VmX-advgJEK?usp=sharing

**Comment by Frank-jinxin** [comment]
Please use this link: https://drive.google.com/drive/folders/1VcqCbGliLoodBxMwhywy8VmX-advgJEK?usp=sharing

**Comment by Sunnyiscoming** [comment]
Whether you are authorized by customers to store these data as public data?

**Comment by Sunnyiscoming** [comment]
Any update here?

**Comment by Frank-jinxin** [comment]
> 您是否获得客户授权将这些数据存储为公共数据？

Yes, I have reached an agreement with my client.
Only authorized data will be uploaded.

**Comment by Frank-jinxin** [comment]
> 这里有更新吗？

I have obtained authorization.

**Comment by Sunnyiscoming** [comment]
- Have you prepared enough token for sector pledge?
- Are you a data preparer? What is your previous experience as a data-preparer? List previous applications and client IDs
- How will the data be prepared? Please include tooling used and technical details
- If you are not preparing the data, who will prepare the data?  (Name and Business)
- Has this dataset been stored on Filecoin before? If so, why are you choosing to store it again?

**Comment by Sunnyiscoming** [comment]
Close for no reply.
