### ISSUE TITLE
[DataCap Application] NIH Genomic Data 

### ISSUE THREAD

**Issue by Marco630** [filecoin-project/filecoin-plus-large-datasets#2047]
### Data Owner Name

National Library of Medicine (NLM)

### What is your role related to the dataset

Data Preparer

### Data Owner Country/Region

United States

### Data Owner Industry

Life Science / Healthcare

### Website

https://www.nlm.nih.gov/

### Social Media

```text
https://twitter.com/NIH_OSP
https://www.youtube.com/@nihofficeofsciencepolicy3005/videos
```

### Total amount of DataCap being requested

15PiB

### Expected size of single dataset (one copy)

1.2PiB

### Number of replicas to store

10

### Weekly allocation of DataCap requested

1PiB

### On-chain address for first allocation

f15bee7lgpoygeka55qz3efkzqxbajkln24pnpz6i

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Project: A centralized sequence repository for all records containing sequence associated with the novel corona virus (SARS-CoV-2) submitted to the National Center for Biotechnology Information (NCBI) Sequence Read Archive (SRA). Included are both the original sequences submitted by the principal investigator as well as SRA-processed sequences that require the SRA Toolkit for analysis. Additionally, submitter provided metadata included in associated BioSample and BioProject records is available alongside NCBI calculated data, such k-mer based taxonomy analysis results, contiguous assemblies (contigs) and associated statistics such as contig length, blast results for the assembled contigs, contig annotation, blast databases of contigs and their annotated peptides, and VCF files generated for each record relative to the SARS-CoV-2 RefSeq record. Finally, metadata is additionally made available in parquet format to facilitate search and filtering using the AWS Athena Service.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
Genomic sequence reads of SARS-CoV-2 and related coronaviridae, organized by NCBI accession. Files in the sra-src folder are in FASTQ, BAM, or CRAM format (original submission); files in the run folder are in .sra format and require the SRA Toolkit; Metadata for sra-pub-sars-cov2 in an Athena-queryable format.
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### How do you plan to prepare the dataset

lotus, singularity, I don't know yet

### Please share a sample of the data

```text
https://registry.opendata.aws/ncbi-covid-19/
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

2 to 3 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America

### How will you be distributing your data to storage providers

HTTP or FTP server, Shipping hard drives, Lotus built-in data transfer, I don't know yet

### How do you plan to choose storage providers

Slack, Big Data Exchange, Partners

### If you already have a list of storage providers to work with, fill out their names and provider IDs below

```text
We'll ensure the list of sps we cooperate as quickly. It takes time to communicate and decide.
```

### How do you plan to make deals to your storage providers

Lotus client, Singularity

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 15PiB

**Expected weekly DataCap usage rate**
> 1PiB

**Client address**
>f15bee7lgpoygeka55qz3efkzqxbajkln24pnpz6i

**Comment by spaceT9** [comment]
Did you find some SPs to work with? Can you  provide the proof of datasize? Can you show some proof of the company identity?

**Comment by Marco630** [comment]
@spaceT9 
I'm looking for the sps now! Here's the size of this dataset. I'm an individual dp so I don't need to show the information of any company I think.
![43](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/125244042/ce7bb594-6e93-4c68-ae0c-ca71082cbf58)
@cbtan21 thank you! If I need it, I will look for BDE!

**Comment by XnMatrixSV** [comment]
Hi Marco, do you have more company information as in, e.g. have you gotten NLM's consent to download and prepare their data? It will be great if you can showcase that. Thanks. 

Plus, if you go through eFil application, KYB should have been part of the protocol, although I cannot see that info in your application yet.

**Comment by Marco630** [comment]
@XnMatrixSV The data I store is a public dataset from AWS. These data is useful for medical research. I download their data from AWS. My application is not a eFil application. Thank you.

**Comment by spaceT9** [comment]
Do you have a detailed distribution plan? If this is your first time to apply for dataCap,it is advisable to start with a small amount to prove your  competency.

**Comment by Marco630** [comment]
We plan to distribute 20% data or below to each sp under the rules. I'll contact experienced SP for work. Thank you for your advice!

**Comment by herrehesse** [comment]
@Marco630 This dataset has already been onboarded, not supportive of granting another 15PiB of datacap.

Requesting notaries not to engage and the applicant to close.

https://github.com/filecoin-project/filecoin-plus-large-datasets/issues?q=is%3Aissue+is%3Aopen+ncbi-covid-19

**Comment by herrehesse** [comment]
The initial request for 15 PiB using a newly created account and without establishing trust within the community is concerning. I highly recommend close the application and reconsider by starting with a smaller amount to build credibility and trust before making larger requests.

Advising notaries not to engage.

**Comment by cryptowhizzard** [comment]
Hi @Marco630 

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Looking at your application i have some questions:
As you are brand new on Github and have no history of past applications. Can you give me an introduction who you are and an introduction about your company?

You stated that you are a Data preparer. What hardware do you have over there to prepare this dataset? What is your internet connection speed? Do you already have the data downloaded on the premises?

It seems to me that applying for 15PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?

Can you show us some visible proof of the size of your data and the storage / packing hardware you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230337462961356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!

**Comment by zcfil** [comment]
> The initial request for 15 PiB using a newly created account and without establishing trust within the community is concerning. I highly recommend close the application and reconsider by starting with a smaller amount to build credibility and trust before making larger requests.
> 
> Advising notaries not to engage.

@herrehesse Many places to copy and paste, do not disturb the notary's work

https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/2048#issuecomment-1637065512

**Comment by junyaoren** [comment]
It would be nice if you could provide more information about what kind of data you are storing. Cause to me, it 's hard to imagine to store 1PiB of genomic sequence of coronavirus, since those virus has tiny genome and to me, it is NOT very easy to fill 1PiB capacity with them. Thanks.

**Comment by cryptowhizzard** [comment]
New issues need to go through PL for verification.

Per the [filecoin-project/notary-governance#922](https://github.com/filecoin-project/notary-governance/issues/922) for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.
This information will be reviewed by Fil+ Governance team to confirm validity and then the application will be approved for notary review. Let us know if you have any questions.

@filplus-govteam

**Comment by Marco630** [comment]
Is there any notary who can help me? I've been waiting too long.

**Comment by cryptowhizzard** [comment]
@Marco630 

New issues need to go through PL for verification.

Per the https://github.com/filecoin-project/notary-governance/issues/922 for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.
This information will be reviewed by Fil+ Governance team to confirm validity and then the application will be approved for notary review. Let us know if you have any questions.

@Filplus-govteam

**Comment by Carohere** [comment]
@Marco630 ,There's no need to hurry. Could we have a call at your convenience? I can help look into it.  You can DM me(@Carohere) your number on slack.

**Comment by Marco630** [comment]
Thank you very much @Carohere , done.

**Comment by junyaoren** [comment]
I think it would be nice if you could provide the list of SP's you will be working with.

**Comment by Carohere** [comment]
This is the first round of this application, based on conversations with the applicant, I'm inclined to believe and support them.

**Comment by Carohere** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb3gimbjylui32ucuk37iyrovrdajiaxd6gbl552as36zgn2hlie4 
#### Address 
> f15bee7lgpoygeka55qz3efkzqxbajkln24pnpz6i
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f1pynuve3pi2fwvhlkco6dl3ipspkgzmb25syv5ca
#### Id
> e4dfd525-989d-4990-b023-6757e486eede
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb3gimbjylui32ucuk37iyrovrdajiaxd6gbl552as36zgn2hlie4

**Comment by cryptowhizzard** [comment]
<img width="671" alt="Scherm­afbeelding 2023-08-09 om 17 07 15" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/36404435/9876bf29-db65-422f-a016-618a472aaee2">

Per the filecoin-project/notary-governance#922 for Open, Public Dataset applicants need to complete the following Fil+ registration form to identify theirself as the applicant and also add contact information of the SP entities you are working with to store copies of the data.
This information will be reviewed by Fil+ Governance team to confirm validity and then the application will be approved for notary review. 

@Carohere notary refuses to adhere to these guidelines.

**Comment by Marco630** [comment]
@cryptowhizzard I‘ve already finished the form before @carohere signed for me and I‘
ve told her. Can you cancel your wrong comment?

**Comment by cryptowhizzard** [comment]
@Marco630 

Like i repeated -> Please check this :  https://github.com/filecoin-project/notary-governance/issues/922

**Comment by Marco630** [comment]
@cryptowhizzard if @Filplus-govteam can confirm that I’ve finished the form before @Carohere signed for me, you should say sorry to me and @Carohere

**Comment by cryptowhizzard** [comment]
@Marco630 

There procedure is simple and outlined. Notary's should *not* sign before DD is done. It is in the issue.

When everything is proper and OK then you are good to go. There is no message from the governance team so you are not good to go atm.

**Comment by Marco630** [comment]
@cryptowhizzard I‘ve finished the form and I told the kind notary. Everything is confirmed so that she signed to me. Every notary has right to make decisions to every application under the rules. I think that **you're just picking a fight**. When you found something puzzled, you should ask them first, **rather than convicting them outright**.

**Comment by Filplus-govteam** [comment]
@Marco630 FYI you can also post your SPs in the application/comments. Does not need to wait for gov team review. Our process is attempting to force applicants to do this.

**Comment by Filplus-govteam** [comment]
Sharing what was submitted as SP entities here:
f01216339  NA  China
f01112335  Wonderbox Taiwan
f01129570  NA China
f0134565 metawall Hong Kong
f0104967  NA UA

**Comment by Filplus-govteam** [comment]
The comments above were reviewed. Techincally this application falls under the conditions of the [proposal 922](https://github.com/filecoin-project/notary-governance/issues/922).

@Marco630 was asked to comply and did not. @Carohere engaged with the applicant, apparently spoke offline about their plan and pledged support. We cannot confirm if Carohere knew or did not know the SPs involved or not. Regardless this information needs to be made public.

**Comment by Carohere** [comment]
Thanks for your inputs.@kevzak 
Should we make it so cheap to submit a dispute?

**Comment by Filplus-govteam** [comment]
We have nothing to dispute here. @Carohere 

@Marco630 can you reconfirm your SPs? 
f01216339 NA China
f01112335 Wonderbox Taiwan
f01129570 NA China
f0134565 metawall Hong Kong
f0104967 NA UA

5 miner IDs storing 10 copies of the dataset?

**Comment by cryptowhizzard** [comment]
> We have nothing to dispute here. @Carohere
> 
> @Marco630 can you reconfirm your SPs? f01216339 NA China f01112335 Wonderbox Taiwan f01129570 NA China f0134565 metawall Hong Kong f0104967 NA UA
> 
> 5 miner IDs storing 10 copies of the dataset?

I disputed in a couple of posts above because the miners applicant was storing on were not known and not. Governance 922 was not followed and caro signed without DD. As soon as you confirm that we are good to go then i will withdraw my dispute.

**Comment by Marco630** [comment]
@filplus-govteam It is the current list of SPs we've identified to work with. I am continuing finding more SPs for cooperation. After this application approved by notaries, I think there will be more SPs willing to cooperate with us to store these data.

**Comment by cryptowhizzard** [comment]
I edited my comment above and revoked the dispute.

@raghavrmadya Fyi.

**Comment by Casey-PG** [comment]
Based on the chat history, willing to support in the first round.

**Comment by Casey-PG** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceasovyelu7dcqojfeztkcjeqlcupxolyef6mjz55zo5yak76nqkcy 
#### Address 
> f15bee7lgpoygeka55qz3efkzqxbajkln24pnpz6i
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f1d4yb3wags3mtddzesxoo63jv7dmlec3bq4yteni
#### Id
> e4dfd525-989d-4990-b023-6757e486eede
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceasovyelu7dcqojfeztkcjeqlcupxolyef6mjz55zo5yak76nqkcy

**Comment by Filplus-govteam** [comment]
checker:manualTrigger

**Comment by cryptowhizzard** [comment]
checker:manualTrigger

**Comment by Marco630** [comment]
Yes, keep open.

**Comment by Marco630** [comment]
Yes, keep open.

**Comment by Marco630** [comment]
Yes

**Comment by Marco630** [comment]
Yes, keep open.

**Comment by Marco630** [comment]
Yes, keep open.

**Comment by Sunnyiscoming** [comment]
Hello, @Marco630 per the https://github.com/filecoin-project/notary-governance/issues/922 for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

This information will be reviewed by Fil+ Governance team to confirm validity and then the application will be allowed to move forward for additional notary review.

**Comment by Filplus-govteam** [comment]
closing until SP entity and distribution list provided
