### ISSUE TITLE
[DataCap Application] Darvin Data Science

### ISSUE THREAD

**Issue by TechSarge** [filecoin-project/filecoin-plus-large-datasets#2049]
### Data Owner Name
Darvin Data Science

### What is your role related to the dataset
Dataset Owner

### Data Owner Country/Region
United States

### Data Owner Industry
Web3 / Crypto

### Website
[https://darvindatascience.com/](https://darvindatascience.com/)

### Social Media
N/A (N/A)

### Total amount of DataCap being requested
5 PiB

### Expected size of single dataset (one copy)
1.25 PiB

### Number of replicas to store
4

### Weekly allocation of DataCap requested
200 TiB

### On-chain address for first allocation
f1vzmf3p2bz5i2cywaz65ennrnln45tks5dtiaedy

### Data Type of Application
Private Commercial/Enterprise

### Custom multisig
- [x] Use Custom Multisig

### Identifier
efil

### Share a brief history of your project and organization
The goal of this project is to store data from other Web 3.0 and crypto networks so that data may be easily retrieved by Darvin Data Science when needed. Darvin Data Science has served a variety of clients building custom applications to enhance workflows, and custom web plugins for crypto mining. 

### Is this project associated with other projects/ecosystem stakeholders?
No

### If answered yes, what are the other projects/ecosystem stakeholders
n/a

### Describe the data being stored onto Filecoin
This data, in particular, are plot files that are dumps from a large database that uses hashes to store the blockchain, and related data, in an accessible manner.

### Where was the data currently stored in this dataset sourced from
My own storage infra

### If you answered "Other" in the previous question, enter the details here
n/a

### How do you plan to prepare the dataset
graphsplit

### If you answered "other/custom tool" in the previous question, enter the details here
n/a

### Please share a sample of the data
This dataset is a company resource.

### Confirm that this is a public dataset that can be retrieved by anyone on the Network
No

### If you chose not to confirm, what was the reason
This resource is only designed to be used internally at this time. 

### What is the expected retrieval frequency for this data
Sporadic

### For how long do you plan to keep this dataset stored on Filecoin
More than 3 years

### In which geographies do you plan on making storage deals
North America, Europe, Greater China

### How will you be distributing your data to storage providers
Shipping hard drives

### How do you plan to choose SP
Slack

### If you answered "Others" in the previous question, what is the tool or platform you plan to use
n/a

### If you already have a list of storage providers to work with, fill out their names and provider IDs below
f0143858	TopBlocks
f02301	TopBlocks
f01969779	Nick
f02201190	James
f03223	TopBlocks
f0240185	TopBlocks
f020522	Wenchu
f02230375 	zkware 
f02230941 	zkware 
f02230939 	zkware 
f02230935 	zkware 
f02032191 	treal 
f01877184 	Aron 
f02337006 	eager 

### How do you plan to make deals to your storage providers
Others/custom tool

### If you answered "Others/custom tool" in the previous question, enter the details here
The custom tool is just a small script that will automate the making of deals in Boost.

### Can you confirm that you will follow the Fil+ guideline
Yes

_Application created via [filplus.storage](https://filplus.storage)_

**Comment by TechSarge** [comment]
I think I have filled out all the forms for the efil+ application. If I have missed anything please let me know. 

This is an e-fil+ application because it is a private dataset and if you have any questions for me or for any of the storage providers please feel free to reach out.

**Comment by kevzak** [comment]
Hello, yes @TechSarge I slacked you directly to complete the registration form and KYB.

**Comment by kevzak** [comment]
## Datacap Request Trigger
#### Total DataCap requested 
> 5PiB
#### Expected weekly DataCap usage rate 
> 200TiB
#### Client address
> f1vzmf3p2bz5i2cywaz65ennrnln45tks5dtiaedy

**Comment by BlockMakeronline** [comment]
Can you provide some sample data after desensitization here?

**Comment by TechSarge** [comment]
I have provided as much information as I am comfortable providing to the public. I would be willing to share more privately with the notaries. Please email me at the address I provided in the E-Fil+ Registration Form.

**Comment by BDE-io** [comment]
very interesting. happy to review this further. may you email me the sample data at info@bigdataexchange.io? thank you!

**Comment by kevzak** [comment]
@TechSarge we have implemented a new process this week as part of E-FIl+.

Can you go to Filplus.storage , login with your GitHub information and then click on Get Verified Link and submit a KYC check? This will add another layer of trust toward a private data client. Thank you.

**Comment by TechSarge** [comment]
@kevzak I have tried to complete the KYC check on filplus.storage but it keeps telling me verification is unsuccessful, is there another way I can complete the KYC check?

@BDE-io I have sent you an email.

Thank You.

**Comment by kevzak** [comment]
ok @techsarge thanks. I sent a slack message to follow up

**Comment by liyunzhi-666** [comment]
I found you on slack, please reply to my DD message at your convenience. @TechSarge

**Comment by liyunzhi-666** [comment]
The slack account you provided is wrong. I didn't find you on slack. @TechSarge

**Comment by TechSarge** [comment]
My apologies I did not realize github thought I was mentioning someone here. My display name on Slack is Andrew S. This link should also take you to my profile, although I have not done the link before [https://filecoinproject.slack.com/team/U058UUM1NQ5](https://filecoinproject.slack.com/team/U058UUM1NQ5). @liyunzhi-666

**Comment by BDE-io** [comment]
@TechSarge i have signed the nda

**Comment by TechSarge** [comment]
Just as an update to anyone reviewing this application, it is on hold waiting for a community dispute against the lead storage provider Top Blocks to be resolved. I will move forward when this dispute is resolved.

**Comment by cryptowhizzard** [comment]
Hi @TechSarge 

I have a Q. Topblocks is your Lead SP, how will this work out?

In your LDN you describe:
"In which geographies do you plan on making storage deals
North America, Europe, Greater China"

This together with:
Total amount of DataCap being requested
5 PiB
Expected size of single dataset (one copy)
2.5 PiB

It means that Topblocks get 2.5PB / 50% of this datacap. Is this correct?

What is the situation with f01969779? Are they included in the 50% from Topblocks?
f0143858 TopBlocks
f02301 TopBlocks
f01969779 Nick
f02201190 James
f03223 TopBlocks
f0240185 TopBlocks

Who are the SP's in Europe for the second 50%?

**Comment by TechSarge** [comment]
@cryptowhizzard  The plan is not for top blocks to get 50% because that would be against the file coin rules. The plan is to have one copy of the dataset in the United States Using spread across the providers you listed above, another copy will be stored with the following storage providers. 

f020522, Wenchu, Frankfurt
f01923786, ZCLabs, Hong Kong
f01938671, ZCLabs, Hong Kong

As to what is the situation with f01969779 I do not know of any situation, is there something I should be aware of?

I hope this clears up the questions.

**Comment by cryptowhizzard** [comment]
> @cryptowhizzard The plan is not for top blocks to get 50% because that would be against the file coin rules. The plan is to have one copy of the dataset in the United States Using spread across the providers you listed above, another copy will be stored with the following storage providers.
> 
> f020522, Wenchu, Frankfurt f01923786, ZCLabs, Hong Kong f01938671, ZCLabs, Hong Kong
> 
> As to what is the situation with f01969779 I do not know of any situation, is there something I should be aware of?
> 
> I hope this clears up the questions.

Hi,

We have a mismatch in communication.
your LDN is 5PB, one replica 2.5. It means you intend to store 2 replica’s.

The miners i mentioned are all from Topblocks, so it means they get 50% of the allocation and that is indeed against the rules. However i don’t see another way with the data you gave.

Perhaps you should revise your distribution plan. Ideally you need 4 organisations on 3 continents. My suggestion would be to raise this LDN from 5 to 10 PB and spread each allocation accordingly 25% per organisation. 2 replica’s is to small anyway

**Comment by TechSarge** [comment]
I was told that f01969779 and f02201190 are not from top blocks and are separate entities.

It says the best practice is to store data in 3 or more regions which I am pretty sure the San Jose, Hong Kong, and Frankfurt, count as three different regions, it also says that the dataset should be stored with 4 or more providers, which I have (Top Blocks, James, Nick, Wenchu, ZCLabs). The only best practice I am not following is the number of replicas which I think 2 replicas is enough.

**Comment by cryptowhizzard** [comment]
> f02201190

Ok, clear. Please note that the miners you mention 
Are visible here : https://github.com/filecoin-project/notary-governance/issues/913

Including explanation. The rest is up to you.

**Comment by zcfil** [comment]
> f02201190

@cryptowhizzard Hi May I ask what the problem is with f02201190? I checked # 913 and couldn't see the problem. Can you tell me

**Comment by cryptowhizzard** [comment]
@zcfil 

Notaries have example roles to the community and should be outstanding in their performance.

Proper and outstanding distribution to me means that a dataset has a minimum of +/- 5 replica's. Out of those 5, 4 replica's go to unique organisations distributed over continents on the globe ( f.e. 1 replica in Asia, one in Europe, one in US and one in Australia. In some situations one replica can be self dealing in case it is an SP starting the LDN request for storing data of it's customers who ask them to store their dataset.

In #913 Topblocks sealed approximately 70% of the data in a number of LDN's. They did not adhere to the rules of proper distribution. Secondly the person acting as data preparer ( Hugh top ) is working for Topblocks itself, thus they dealed to way to much data to themselves. Note that it might be stored on machines where they control the wallets and all ICT things for their SP customers.

I / We are still awaiting an adult discussion with them. It seems there is no understanding on Topblocks side so i can't close the issue in the hope that there is repair and these things won't happen again. I have let one LDN go where the preparer indicated he would stop sending data top Topblocks and bring things in balance and i am watching that one.

I tried suggesting that Topblocks make a repair plan etc. but all i get is contesting the numbers of the CID checkbot and an infinite amount of spam of slack over this. So tbh, i am a bit tired over it. Sorry :(

**Comment by woshidama323** [comment]
Please check the conclusion of 913. 
[913](https://github.com/filecoin-project/notary-governance/issues/913#issuecomment-1670467423)

**Comment by cryptowhizzard** [comment]
> Please check the conclusion of 913. [913](https://github.com/filecoin-project/notary-governance/issues/913#issuecomment-1670467423)
> 
> BTW @cryptowhizzard what you are raised is LDN 913 but not the right issue we discussed

Conclusion is that datacap must be removed.

**Comment by woshidama323** [comment]
> > Please check the conclusion of 913. [913](https://github.com/filecoin-project/notary-governance/issues/913#issuecomment-1670467423)
> > BTW @cryptowhizzard what you are raised is LDN 913 but not the right issue we discussed
> 
> Conclusion is that datacap must be removed.
We will open a new issue to dispute this conclusion 

But anyway, in this issue, As SP, Topblocks should not impact by any other LDN. 
Of course, the same conclusion would be applied to any other LDN which lists Topblocks as SP.

We can chat online with you and also include RG or Deep if you have any further questions.
But please, let's stop here.

**Comment by cryptowhizzard** [comment]
@woshidama323 
I am not interested in further debate because it is useless as i indicated above. Second, this is TechSarge's LDN and about him, not about you or me.

Let me make some clear language here:

@TechSarge , i see no trouble in moving your LDN forward. Please respect the FIL+ rules and guidelines. There are enough SP's out there, make sure you don't send more then 30% to one organization. You thing 2 replica's is enough but that does not work, you need 4 to make sure the distribution guidelines are met if you don't send more then 30% to one organistation.
Please also store on different continents.

Thanks!

**Comment by TechSarge** [comment]
Ok as I see it issue #913 has been resolved as far as I can tell. I plan on moving forward with this application with Topblocks as the lead storage provider. 

From what I have been told during this application the storage guidelines are actually requirements so I will be changing the number of replicas to 4 to help meet this requirement and will start looking for more storage providers on different continents to ensure no storage entity receives more than 30% of the data cap. 

@cryptowhizzard Thank you for clearing that up and hopefully ending the debate of 913 here, this is not the place to debate that.

Thank you, everyone. I hope we can move forward with this application as soon as possible and get it approved as it has been open for a while.

**Comment by cryptowhizzard** [comment]
@kevzak 

Can you help this applicant? I am interested in signing.

**Comment by liyunzhi-666** [comment]
> To help balance out the distribution of Datacap I have decided to add 4 more storage providers. I will personally ensure that no one storage provider will receive more than 25% of the datacap at a time. Here are the new storage providers organization/ SPs / Location / zkware / f02230375,f02230941,f02230939,f02230935 / HK,China treal / f02032191 / ZJ China Aron / f01877184 / Singapore eager / f02337006 / England
> 
> Unfortunately, this application has been open for so long that zclabs is no longer looking to onboard data and will have to be removed as a storage provider.
> 
> The above changes will be reflected in the original post to make it easy to read.
> 
> lastly, I have not heard from any notaries in a long time and am wondering if any notaries are willing to look at this application or if the ones that I have communicated with previously need any more information from me before signing. @BDE-io @liyunzhi-666

As I understand it, there was a previous dispute here. Has the dispute been resolved now? @TechSarge

**Comment by TechSarge** [comment]
@liyunzhi-666 As far as I can tell the issue has been resolved, the GitHub issue has been closed, and there have been many indications that the dispute will not prevent them from taking on data cap as a storage provider.

**Comment by woshidama323** [comment]
>As I understand it, there was a previous dispute here. Has the dispute been resolved now?

@liyunzhi-666 
[913](https://github.com/filecoin-project/notary-governance/issues/913) related to Topblocks Has been resolved

**Comment by NDLABS-Leo** [comment]
@TechSarge 
As an e+fil notary, I need to review this application.
From the records of the application, it seems that the concerns have been addressed, and the disclosed node information complies with the community rules.
However, please send the relevant supporting documentation for the application to my Slack (Leo - ND Labs).

**Comment by kevzak** [comment]
> @kevzak
> 
> Can you help this applicant? I am interested in signing.

should be good @cryptowhizzard

**Comment by cryptowhizzard** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedb32wmm2wgacyn46cuev7uwjcu2wrwdgozpztacngxx6hq7a2pgm 
#### Address 
> f1vzmf3p2bz5i2cywaz65ennrnln45tks5dtiaedy
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1krmypm4uoxxf3g7okrwtrahlmpcph3y7rbqqgfa
#### Id
> fb1086bb-97ef-43ab-bc82-d76bd82ec3a5
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedb32wmm2wgacyn46cuev7uwjcu2wrwdgozpztacngxx6hq7a2pgm

**Comment by NDLABS-Leo** [comment]
The client contacted me at slack and provided verification information and promised to follow the e+fil rules, which I was willing to support~

**Comment by NDLABS-Leo** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebac4d2v3dxarnxqz7ybqiodlwqh5dsuad3kebmgrcnlxa2rarkos 
#### Address 
> f1vzmf3p2bz5i2cywaz65ennrnln45tks5dtiaedy
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1yayfsv6whu3rheviucvventj3y6t542xfpb47ei
#### Id
> fb1086bb-97ef-43ab-bc82-d76bd82ec3a5
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebac4d2v3dxarnxqz7ybqiodlwqh5dsuad3kebmgrcnlxa2rarkos

**Comment by TechSarge** [comment]
Thank You, everyone, for getting the first trove of datacap approved, especially @NDLABS-Leo and @cryptowhizzard for signing the application.

I just changed the application to reflect 4 copies of the data as discussed with the notaries but I forgot to make the change in the application.

**Comment by herrehesse** [comment]
Looking forward to the data storage results and distribution. Will follow closely.

**Comment by TechSarge** [comment]
Please leave the application open. 

The data has been shipped today and deals should start showing up later this week on the network.
