### ISSUE TITLE
[DataCap Application] <Organization> - <Project Name>

### ISSUE THREAD

**Issue by cycpilies** [filecoin-project/filecoin-plus-large-datasets#2053]
### Data Owner Name

Xi'an Lingdong Computer System Co., Ltd.

### What is your role related to the dataset

Data Preparer
### Data Owner Country/Region

China

### Data Owner Industry

IT & Technology Services

### Website

https://lindensys.com/#/HomeE

### Social Media

```text
Xi'an Lingdong Computer System Co., Ltd. is a cutting-edge enterprise established in 2018 and headquartered in the city of Xi'an. Specializing in the research, development, production, and sales of high-end servers and storage devices, the company is dedicated to creating and advancing storage technology and the global storage ecosystem. Among its innovative products is the Linden Cloud Drive, an encrypted network disk that uses IPFS decentralized storage. With this technology, users can easily upload, view, and share their files across multiple devices, anytime and anywhere. Linden Cloud Drive is currently available on both PC and mobile operating systems.
```

### Total amount of DataCap being requested

2PiB

### Expected size of single dataset (one copy)

409.6TiB

### Number of replicas to store

5

### Weekly allocation of DataCap requested

100TiB

### On-chain address for first allocation

f1rb5r7k7lnbbdrvpw4d7ir3hi2cpivcevkgxpxga

### Data Type of Application

Public, Open Commercial/Enterprise

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Linden Cloud offers a decentralized storage solution based on IPFS, which is more secure and stable than traditional centralized storage. Unlike storing data on a single server, data is distributed across multiple nodes to ensure reliability and stability, even if one node fails. Additionally, this solution is both cheaper and more secure than cloud storage, providing long-term data liveness guarantees for all network participants.
To ensure the privacy and security of data, we offer encryption services that use end-to-end encryption. POSS utilizes open-source storage projects and encapsulates data operation tools to simplify the calling process, connect to the CSG gateway, and complete data storage and retrieval.
https://github.com/Linden-Community/flipped
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
Users utilize Linden Cloud to securely store their photos, videos, and files for permanent data storage and convenient access from anywhere, at any time. In addition, Linden Cloud offers private cloud services. Local encryption is employed to secure the data and the private key is holding in their hands, make sure that only authorized parties can access it. Currently, each user is provided with 1TB of free storage space.
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### How do you plan to prepare the dataset

IPFS, lotus

### Please share a sample of the data

```text
https://dweb.lindensys.cn/ipfs/QmU8Hhs6hcXNxWwffgacWezWadKUwKhRM3pqCf9VWfrqL8
https://dweb.lindensys.cn/ipfs/QmdiuxvwZ5vYXJxSFsTTNzAAiZApX3UTZ6cJEwJ6uFBeKq
https://dweb.lindensys.cn/ipfs/QmNTWJEw64x18xWRtKQHWnvkYQpeeQ9L9iLe5EsDTpFaJc
https://dweb.lindensys.cn/ipfs/QmZuKrjAXLkenVneSZzDpd9MANXkoUWkvo2K4aZB3VLyrT
https://dweb.lindensys.cn/ipfs/Qmf3BzVJZChj44GR4N8ubajqj7iSbyEQ1XUi6owdSBMyoM
https://dweb.lindensys.cn/ipfs/QmYHs3XmSaiXudvwoKhy7zb6v3iwMPhVbpe6mR2q6frt9x
https://csg.lindensys.cn/poss/v1/myspace/ipfs/QmUc1HmY38q3hj8N2Vv4ERgYreBkPfynsw6ddc7HB8wWTf
https://csg.lindensys.cn/poss/v1/myspace/ipfs/QmeNNenhUQ7TBWBaMCLoUTSHpCp2sjFrLQoVt68i837YSb
https://csg.lindensys.cn/poss/v1/myspace/ipfs/QmWaPUcvsyPzo9uq6vjdzRUGgHSPUPmkKECYtx5ucA2vZD
https://csg.lindensys.cn/poss/v1/myspace/ipfs/QmZq3rz7tHXN3kzN1eA9CXyc6r3meFoefsM5ypERL6dJ4E
https://csg.lindensys.cn/poss/v1/myspace/ipfs/QmasqPwbkAwwzRNQCuZYwBhoLCYsx2mQCkRbhBya98rs2K
https://csg.lindensys.cn/poss/v1/myspace/ipfs/QmPLxmMEy4PiAyL4tbF73CFPHrDV67TKfSrJXVY3HkeVEw
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

☑︎ I confirm

### What is the expected retrieval frequency for this data

Daily

### For how long do you plan to keep this dataset stored on Filecoin

Permanently

### In which geographies do you plan on making storage deals

Asia other than Greater China, North America

### How will you be distributing your data to storage providers

HTTP or FTP server, IPFS

### How do you plan to choose storage providers

Slack, Big Data Exchange, Partners

### How do you plan to make deals to your storage providers

Boost client, Lotus client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
Expected size of single dataset (one copy)*Number of replicas to store≠Total amount of DataCap being requested
1TiB*1≠2PiB
This single dataset means the amount of non-duplicate data you want to store. Maybe you mistake it, please adjust this value.

You want to store users' data as public data on the Filecoin network. Are you authorized to do that? Please provide the related materials.

Each user have 1 TB data. You have 2 PB data. That means you have 2048 users. Can you provide more materials to prove that?

Please share more detailed information about sps you will cooperate with.

**Comment by cycpilies** [comment]
Thank you for bringing the mistake to our attention. We have now rectified the information. At Linden Cloud, our users have the option to decide whether to keep their data public or encrypted. Public data can only be accessed by others if the user shares it explicitly, while encrypted data requires the user's authorization to grant specific access to designated individuals. Currently, we have over 5000 users. However, we can only provide partial screenshots of the information as we are committed to protecting user privacy. As the number of our users and the demand for storage space continue to increase, we will be actively looking for additional SPS to help replicate data on Slack. Please let us know if you have any further questions.

https://dweb.lindensys.cn/ipfs/QmVEwUzzgLLBbuEN3ishtbpyYyFbDwzMaiWc6RpHC5Z7hw

sps: f0123261
       f01108594

**Comment by cycpilies** [comment]
Hello, our company launched Linden Cloud in 2019, and it has undergone multiple versions and iterations. Please find below screenshots of our app interface.
<img width="232" alt="2" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/132637230/4ef41912-8c6b-4827-83c5-48ce666476d8">
<img width="235" alt="4" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/132637230/d07e4f49-dcf0-438c-876a-bfb9a43a30ad">

**Comment by cycpilies** [comment]
Here are some publicly accessible videos that are stored on Linden Cloud. Please take a look. Thanks!
https://csg.lindensys.cn/poss/v1/myspace/ipfs/QmRd9wTkyHppMpqmc83nancToNZFp1mreTAT7qAAQTCqcs
https://csg.lindensys.cn/poss/v1/myspace/ipfs/QmeUiz4wkusyKbgcMA7xnvuWpjqdu1P2a5eYLnyuu4VG4t
https://csg.lindensys.cn/poss/v1/myspace/ipfs/QmSV15oR6rJtdANLmJvzKtSazFqUJFdxMH9geshJTFLtrM
https://csg.lindensys.cn/poss/v1/myspace/ipfs/QmeEGtTRzWFzdYGKetVUBUWyWikymgWonVo23EfTeaPzVy

**Comment by cycpilies** [comment]
> Please specify the amount of public data you already have. Is 409TB the total amount of public data? Please share more data samples to prove that.

There is a huge market demand for decentralized storage in China as we have already entered the era of data. Many people use their smartphones to record and share their lives. Centralized storage often leads to data loss or deletion due to strict censorship mechanisms and high usage fees. As I mentioned before, we already have over 5000 users, and the future demand for storage space is even greater. We are happy to share Filecoin's decentralized storage system with more people to work together and uphold the prosperity and diversity of Filecoin's ecosystem.

**Comment by cycpilies** [comment]
> Please specify the amount of public data you already have. Is 409TB the total amount of public data? Please share more data samples to prove that.


We launched Linden Cloud in 2019, and it has undergone multiple versions and iterations. Please find below screenshots of our app interface.
<img width="232" alt="2" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/132637230/4ef41912-8c6b-4827-83c5-48ce666476d8">
<img width="235" alt="4" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/132637230/d07e4f49-dcf0-438c-876a-bfb9a43a30ad">
Here are some publicly accessible videos that are stored on Linden Cloud Form ID: Linden 222. Please take a look. Thanks!
https://csg.lindensys.cn/poss/v1/myspace/ipfs/QmRd9wTkyHppMpqmc83nancToNZFp1mreTAT7qAAQTCqcs
https://csg.lindensys.cn/poss/v1/myspace/ipfs/QmeUiz4wkusyKbgcMA7xnvuWpjqdu1P2a5eYLnyuu4VG4t
https://csg.lindensys.cn/poss/v1/myspace/ipfs/QmSV15oR6rJtdANLmJvzKtSazFqUJFdxMH9geshJTFLtrM
https://csg.lindensys.cn/poss/v1/myspace/ipfs/QmeEGtTRzWFzdYGKetVUBUWyWikymgWonVo23EfTeaPzVy

**Comment by Sunnyiscoming** [comment]
Only existing datasets can be applied for datacap. Please specify the amount of public data you already have. Is 409TB the total amount of public data?

For the data sample you provided, which can also be found in some social media, it is not clear whether their copyright will be disputed.
https://www.bilibili.com/video/BV1FV4y1F7Xc/
https://www.bilibili.com/video/BV1GY411y76M/
https://www.bilibili.com/video/BV11d4y1f7fG/

**Comment by cycpilies** [comment]
> 

Hello, thanks for your message. The screenshot provided above showcases our Linden Cloud APP interface, and the accompanying video was uploaded by me to demonstrate its functionality. I uploaded them on June 15th.

As I mentioned earlier, in order to protect user privacy, we cannot directly provide customer data. However, Linden Cloud does have a storage requirement as we are dedicated to creating a decentralized cloud storage platform. The market demand for such services is increasing, and we firmly believe in the immense potential of Perpetual Storage, especially when combined with the advantages of Filecoin's decentralized storage.

Similar to other centralized cloud storage providers, Linden Cloud cannot predict the specific types of data that users store. In the event of any copyright infringement, we promptly inform the user to remove or take down the infringing content.

Requiring a substantial amount of data to be accumulated on web2 before migrating it to Filecoin does not seem reasonable to us. This approach clearly contradicts market trends. Unlike certain service providers, we do not engage in fraudulent practices such as filling up storage space with useless data to obtain quotas.

By the way, if you are interested in our APP, we encourage you to download it and experience its user-friendly features. Currently, our platform is available for PC and Android, while the iOS version is coming soon.

**Comment by cycpilies** [comment]
> Only existing datasets can be applied for datacap. Please specify the amount of public data you already have. Is 409TB the total amount of public data?
> 
> For the data sample you provided, which can also be found in some social media, it is not clear whether their copyright will be disputed. https://www.bilibili.com/video/BV1FV4y1F7Xc/ https://www.bilibili.com/video/BV1GY411y76M/ https://www.bilibili.com/video/BV11d4y1f7fG/

Hello, thanks for your message. The screenshot provided above showcases our Linden Cloud APP interface, and the accompanying video was uploaded by me to demonstrate its functionality. I uploaded them on June 15th.

As I mentioned earlier, in order to protect user privacy, we cannot directly provide customer data. However, Linden Cloud does have a storage requirement as we are dedicated to creating a decentralized cloud storage platform. The market demand for such services is increasing, and we firmly believe in the immense potential of Perpetual Storage, especially when combined with the advantages of Filecoin's decentralized storage.

Similar to other centralized cloud storage providers, Linden Cloud cannot predict the specific types of data that users store. In the event of any copyright infringement, we promptly inform the user to remove or take down the infringing content.

Requiring a substantial amount of data to be accumulated on web2 before migrating it to Filecoin does not seem reasonable to us. This approach clearly contradicts market trends. Unlike certain service providers, we do not engage in fraudulent practices such as filling up storage space with useless data to obtain quotas.

By the way, if you are interested in our APP, we encourage you to download it and experience its user-friendly features. Currently, our platform is available for PC and Android, while the iOS version is coming soon.

**Comment by Sunnyiscoming** [comment]
I know what you mean. But large dataset only can be applied for open dataset.

**Comment by Sunnyiscoming** [comment]
Close for no reply here.

**Comment by cycpilies** [comment]
@simonkim0515 @Kevin-FF-USA 
Thank you everyone for your suggestions. I had the technical team extract some backend data from our Linden Cloud. As you can see, our WEB3 storage has been in operation since 2021, and after two years of development, we have accumulated a large number of users, who have provided highly positive feedback. However, during this period, the development of Linden Cloud was adversely affected by adjustments in national policies and a shift in company strategy, resulting in slower progress. Nevertheless, we have overcome these difficulties and refocused our efforts on Linden Cloud. We hope that FIl+ can provide us with some assistance in achieving wider adoption of distributed storage.
<img width="643" alt="2" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/132637230/1356f39f-9d92-4b60-b9ea-eb2f80512c0c">
<img width="650" alt="3" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/132637230/59189ab6-4cc0-4a20-8e64-ce0f7ec81f66">
<img width="651" alt="4" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/132637230/fd736153-726b-44e8-9139-c226ebf35093">
<img width="645" alt="5" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/132637230/750c9194-fa05-450b-b3fa-9d1f24bd3ecf">

**Comment by cycpilies** [comment]
@simonkim0515 @Kevin-FF-USA
Thank you everyone for your suggestions. I had the technical team extract some backend data from our Linden Cloud. As you can see, our WEB3 storage has been in operation since 2021, and after two years of development, we have accumulated a large number of users, who have provided highly positive feedback. However, during this period, the development of Linden Cloud was adversely affected by adjustments in national policies and a shift in company strategy, resulting in slower progress. Nevertheless, we have overcome these difficulties and refocused our efforts on Linden Cloud. We hope that FIl+ can provide us with some assistance in achieving wider adoption of distributed storage.
<img width="643" alt="2" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/132637230/845bb304-8158-4e51-a984-a4134fa8f0b6">
<img width="650" alt="3" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/132637230/bae11862-280e-4edd-839c-88c0a1a3abba">
<img width="651" alt="4" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/132637230/17a22940-7656-424b-aa73-58d11fac5398">
<img width="645" alt="5" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/132637230/1e71a5a2-8996-4b9f-968e-a46d390d9190">

**Comment by Filplus-govteam** [comment]
Hello @cycpilies Per the https://github.com/filecoin-project/notary-governance/issues/922 for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

This information will be reviewed by Fil+ Governance team to confirm validity and then the application will be triggered for notary review.

**Comment by Sunnyiscoming** [comment]
Any update here?

**Comment by cycpilies** [comment]
@Sunnyiscoming I have already submitted the form, but I have not received any response yet.

**Comment by Sunnyiscoming** [comment]
- Best practice for storing large datasets includes ideally, storing it in 3 or more regions, with 4 or more storage provider operators or owners.You should list Miner ID, Business Entity, Location of sps you will cooperate with.

**Comment by Filplus-govteam** [comment]
We don't see any form submitted. Who are your SPs @cycpilies ?

**Comment by cycpilies** [comment]
@Filplus-govteam @Sunnyiscoming 
f0123261
f01108594
f02128256
f0420161
The above-mentioned SPs come from Canada, Singapore, and mainland China.
We are technical partners and have had previous technical exchanges and business transactions.

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 2PiB

**Expected weekly DataCap usage rate**
> 100TiB

**Client address**
>f1rb5r7k7lnbbdrvpw4d7ir3hi2cpivcevkgxpxga

**Comment by cycpilies** [comment]
Thank you for the support from the Fil+ team. We will strive to do our best with our Linden Cloud and provide a different experience for more people to enjoy decentralized cloud storage. In the future, we will continue to expand the market in the field of permanent data storage and enrich the ecosystem under Filecoin. Once again, we thank the notary team for giving our team hope again.

**Comment by zcfil** [comment]
Hi @cycpilies ,
The data sample you provided seems to be inaccessible. I can't see the data sample. Please help me

**Comment by cycpilies** [comment]
Two days ago, the servers in our Hangzhou data center experienced a hardware failure. We worked overnight to replace the equipment with new devices, and currently, everything has returned to normal.

**Comment by cycpilies** [comment]
A few days ago, the servers in our Hangzhou data center experienced a hardware failure. We worked overnight to replace the equipment with new devices, and currently, everything has returned to normal.
<img width="1275" alt="1" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/132637230/678b4486-496b-478d-b9fb-3a7764f79811">
<img width="1275" alt="2" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/132637230/9eeafdd1-445a-4290-8c77-56c1e9d50489">
<img width="1275" alt="3" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/132637230/bd0dd1d2-a8c1-49d0-8ff4-89d0cc11d17f">
<img width="1275" alt="4" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/132637230/f14a4f9c-eca1-4346-aae6-3c1f9b5dbc82">

**Comment by cycpilies** [comment]
@zcfil 
Our web version does not support video uploads, but the mobile version supports video uploads and data encryption services. This is because there is a larger user base for mobile devices in China, and they are more convenient for daily use.
Currently, our team is developing an iOS version, which will be included in the next version update.
If you have any questions, please let me know. Thank you !

**Comment by zcfil** [comment]
You can upload sample data to the online drive and share it

**Comment by cycpilies** [comment]
@zcfil 
Thank you for your time, please take a look.
https://drive.google.com/file/d/18KpEGVnZ11MbEkH-b6fJaqsp2lbKlF0t/view?usp=sharing
https://drive.google.com/file/d/1MR9qo2sL8BTp_d0VS2vBKAJSQEmG-lTF/view?usp=sharing
https://drive.google.com/file/d/1DngsRJd-P_mK4VNUHf602heyf_FTblus/view?usp=sharing
https://drive.google.com/file/d/10Hpa8pLqdzhVPiDg0580c3f25GbOlXGU/view?usp=sharing

**Comment by zcfil** [comment]
The data is not public and I do not have access rights

**Comment by cycpilies** [comment]
@zcfil 
I'm sorry, it's my fault. I have now set the sample data to be shared.

**Comment by zcfil** [comment]
> @Filplus-govteam @Sunnyiscoming f0123261 f01108594 f02128256 f0420161 上述SP来自加拿大、新加坡和中国大陆。 我们是技术合作伙伴，之前有过技术交流和业务交易。

All the above nodes failed to query ask. Are you sure they all support retrieval?

**Comment by cycpilies** [comment]
@zcfil 
f02128256
f0420161
Support retrieval.

**Comment by cycpilies** [comment]
Hello, in order to save expenses, our company is moving to a new office location and we were unable to reply to your message in a timely manner. Our technical personnel have confirmed that these two nodes can support the query function.
<img width="1390" alt="1" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/132637230/d4eecfdc-cfc2-4baa-a838-32cab65633b0">

**Comment by cycpilies** [comment]
@zcfil Hello, in order to save expenses, our company is moving to a new office location and we were unable to reply to your message in a timely manner. Our technical personnel have confirmed that these two nodes can support the query function.
<img width="1390" alt="1" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/132637230/2eacfc83-41ce-490f-82b2-4cad2e0f1983">

**Comment by cycpilies** [comment]
@zcfil I have moved to a new office location and all services have been restored to normal.
f02128256 and f0420161 support retrieval.
 If you have any questions about our project, please let me know. We are happy to assist you.

**Comment by zcfil** [comment]
Ok, will support the first round

**Comment by zcfil** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecfwrfnnnnefg6r5s5ruf5cxc2cf4lzdreibecnm4hzlf767dw3g2 
#### Address 
> f1rb5r7k7lnbbdrvpw4d7ir3hi2cpivcevkgxpxga
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1cjzbiy5xd4ehera4wmbz63pd5ku4oo7g52cldga
#### Id
> 8031ec32-edfc-410e-95d2-0767a2015a8d
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecfwrfnnnnefg6r5s5ruf5cxc2cf4lzdreibecnm4hzlf767dw3g2

**Comment by BlockMakeronline** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecc5qw2m32p7nfu7alygy4qxmy5uy44jmw4xpozu4dvmkjfqmuejc 
#### Address 
> f1rb5r7k7lnbbdrvpw4d7ir3hi2cpivcevkgxpxga
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1o3twrcpwjtpcd4q36lpq4qmy2qfbgtyy5h6tsty
#### Id
> 8031ec32-edfc-410e-95d2-0767a2015a8d
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecc5qw2m32p7nfu7alygy4qxmy5uy44jmw4xpozu4dvmkjfqmuejc

**Comment by BlockMakeronline** [comment]
Meets community requirements and I am willing to sign the first round.

**Comment by cycpilies** [comment]
Thanks for backing us up, fil+ team!

**Comment by Filplus-govteam** [comment]
checker:manualTrigger
