### ISSUE TITLE
[DataCap Application] Transiting Exoplanet Survey Satellite (TESS)

### ISSUE THREAD

**Issue by jevticgallonsd1466** [filecoin-project/filecoin-plus-large-datasets#2054]
### Data Owner Name

Space Telescope Science Institute.

### What is your role related to the dataset

Storage provider filling out application on behalf of the data owner

### Data Owner Country/Region

United States

### Data Owner Industry

Not-for-Profit

### Website

http://astroquery.readthedocs.io/en/latest/mast/mast.html

### Social Media

```text
N/A
```

### Total amount of DataCap being requested

7PiB

### Expected size of single dataset (one copy)

750TiB

### Number of replicas to store

10

### Weekly allocation of DataCap requested

400TiB

### On-chain address for first allocation

f1hhv5js4gxnw5z4vs7jvgr2cwygtp6gcecog4mui

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
We are topblocks team - https://www.topblocks.io

We are leader sp on https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1248.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
The Transiting Exoplanet Survey Satellite (TESS) is a multi-year survey that will discover exoplanets in orbit around bright stars across the entire sky using high-precision photometry. The survey will also enable a wide variety of stellar astrophysics, solar system science, and extragalactic variability studies. More information about TESS is available at MAST and the TESS Science Support Center.
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### How do you plan to prepare the dataset

singularity

### Please share a sample of the data

```text
aws s3 ls --no-sign-request s3://stpubdata/tess/
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Sporadic

### For how long do you plan to keep this dataset stored on Filecoin

Less than 1 year

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, Europe

### How will you be distributing your data to storage providers

HTTP or FTP server

### How do you plan to choose storage providers

Slack, Partners

### If you already have a list of storage providers to work with, fill out their names and provider IDs below

```text
|minerId|region|org|
|--|--|--|
|f02145020|CN|hongbiao|
|f01969779|US|Nick|
|f020522|DE|phantom|
|f02201190|US|James|
|f02032191|CN|treal|
|f01923786|CN|zcLabs|
|f01938671|CN|zcLabs|

My nodes are f02301,f03223,f0240185,f0143858 in US
```

### How do you plan to make deals to your storage providers

Singularity

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by jevticgallonsd1466** [comment]
@Sunnyiscoming   We have applied for an [ldn](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/2042) before by [michellilamiebqaj](https://github.com/michellilamiebqaj), but cannot access, I don't nkown why. 
I found that there was a problem with that account, so I reapplied with this account

think you

![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/135803746/84d119d0-9483-4323-9ad6-7cb70ad79249)

![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/135803746/dc49ae4d-1f88-49a4-b9e0-a4d94b9a1baf)

**Comment by Sunnyiscoming** [comment]
40% is a very large percentage, each sp should not have more than 30% of Datacap, so I can't move forward with this application。

**Comment by jevticgallonsd1466** [comment]
> 40% is a very large percentage, each sp should not have more than 30% of Datacap, so I can't move forward with this application。

@Sunnyiscoming    Thank you for your correction, this is our mistake. I promise we will not store more than 30 of Datacap to our nodes.

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 7PiB

**Expected weekly DataCap usage rate**
> 400TiB

**Client address**
>f1hhv5js4gxnw5z4vs7jvgr2cwygtp6gcecog4mui

**Comment by Aaron01230** [comment]
The client  contact we and we had made some survey, according to the above records , we think this application meet the requirements of FIL Plus and willing to support this round and keep focusing.

**Comment by Aaron01230** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceapu3pccvujexw7h3xtzsdaze7ouvjitxy7axenswyfd4etrpng5q 
#### Address 
> f1hhv5js4gxnw5z4vs7jvgr2cwygtp6gcecog4mui
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1xrnysd4gimg64d4l6qi7ulzwwq22c6vfg6lpw3i
#### Id
> 79e1c373-7fe4-4a13-a113-c2d6d3a8d38c
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceapu3pccvujexw7h3xtzsdaze7ouvjitxy7axenswyfd4etrpng5q

**Comment by herrehesse** [comment]
![Screenshot 2023-06-21 at 08 38 03](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/70132857/ab1bd7ad-9f9d-45f9-a884-fb50a4dbb3da)

@Aaron01230 @DaYouGroup Can you explain your signature on a 7PiB request if the set contains only 5.49T of data?

Tagging: @raghavrmadya @galen-mcandrew @dkkapur @simonkim0515 

Requesting a pauze on this application, will open a dispute.

**Comment by jevticgallonsd1466** [comment]
> 

@herrehesse  Hello. There must be something wrong with your statistical method. This dataset has 430.1TiB.
![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/135803746/45d86dc4-1201-41cc-a086-fedbcab644bf)

The produced car files are each 19GiB, which can generate 430.1*1024/19=23180 cars, which generates 23180/32=724.375TiB raw data.
![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/135803746/dc81c5d8-c8c9-4e4e-b821-26dde7730fcb)

**Comment by jevticgallonsd1466** [comment]
checker:manualTrigger

**Comment by kernelogic** [comment]
I believe @herrehesse forgot to use --recursive parameter (or was it a result from chatGPT? )

**Comment by jevticgallonsd1466** [comment]
checker:manualTrigger

**Comment by jevticgallonsd1466** [comment]
checker:manualTrigger

**Comment by jevticgallonsd1466** [comment]
checker:manualTrigger

**Comment by kernelogic** [comment]
Report LGTM, plus the DD I performed above regarding source dataset size.

**Comment by kernelogic** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebsyeic7typ2gw3v72z3yq3prt7h6tn2rw3hkriw3voflmrl7jbse 
#### Address 
> f1hhv5js4gxnw5z4vs7jvgr2cwygtp6gcecog4mui
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### Id
> 5143a561-a4e9-4759-b8ab-0daddcd234fe
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebsyeic7typ2gw3v72z3yq3prt7h6tn2rw3hkriw3voflmrl7jbse

**Comment by Bitrise0111** [comment]
the check bot shows healthy

**Comment by Bitrise0111** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceazqipsg7x7bvcxahyt3fxa6j5pfg2lumvxoodp7xsustevsyvbiy 
#### Address 
> f1hhv5js4gxnw5z4vs7jvgr2cwygtp6gcecog4mui
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1nknj7ayq4o43czrtdoauggtwl43fbqatmqis3yy
#### Id
> 5143a561-a4e9-4759-b8ab-0daddcd234fe
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceazqipsg7x7bvcxahyt3fxa6j5pfg2lumvxoodp7xsustevsyvbiy

**Comment by herrehesse** [comment]
checker:manualTrigger

**Comment by jevticgallonsd1466** [comment]
checker:manualTrigger

**Comment by jevticgallonsd1466** [comment]
checker:manualTrigger

**Comment by woshidama323** [comment]
checker:manualTrigger

**Comment by zcfil** [comment]
checker:manualTrigger

**Comment by zcfil** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebfsp47vtuyfgazas3bfwxss4eu773zuvrmkd2uwnsd5yfuykstzq 
#### Address 
> f1hhv5js4gxnw5z4vs7jvgr2cwygtp6gcecog4mui
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1cjzbiy5xd4ehera4wmbz63pd5ku4oo7g52cldga
#### Id
> 5ab7f029-f844-470f-a108-200dfd478285
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebfsp47vtuyfgazas3bfwxss4eu773zuvrmkd2uwnsd5yfuykstzq

**Comment by zcfil** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceauqb4b6kcmjbwwezlgh2zvl43r5annt2jtlu7ztlcllgkzpjrfua 
#### Address 
> f1hhv5js4gxnw5z4vs7jvgr2cwygtp6gcecog4mui
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1cjzbiy5xd4ehera4wmbz63pd5ku4oo7g52cldga
#### Id
> 5ab7f029-f844-470f-a108-200dfd478285
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceauqb4b6kcmjbwwezlgh2zvl43r5annt2jtlu7ztlcllgkzpjrfua

**Comment by ipollo00** [comment]
checker:manualTrigger

**Comment by ipollo00** [comment]
This application has a clear explanation during the T&T call, which is trustworthy for all. 
The checker report is healthy. Willing to support.

**Comment by ipollo00** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebweqlbd35kcwyia3x5ojgmre44r6uxghwlc22k47lnzi5nxusayw 
#### Address 
> f1hhv5js4gxnw5z4vs7jvgr2cwygtp6gcecog4mui
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1n5wlrrhoxpkgwij25xrtt7w7g2k3fhbthmdn6ri
#### Id
> 5ab7f029-f844-470f-a108-200dfd478285
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebweqlbd35kcwyia3x5ojgmre44r6uxghwlc22k47lnzi5nxusayw

**Comment by cryptowhizzard** [comment]
> This application has a clear explanation during the T&T call, which is trustworthy for all. The checker report is healthy. Willing to support.

No it has not been explained during T&T Working group call. Secondly https://github.com/filecoin-project/notary-governance/issues/913 is still open.

Good to know that we don't need to hold of on signing anymore when there are disputes. This behaviour is destructive for the whole ecosystem.

**Comment by raghavrmadya** [comment]
Hi @ipollo00, kindly conduct your own DD. Discussing an application on a call doesn't make it trustworthy. Can you share why you were comfortable singing when the SP distribution is bad?

**Comment by Filplus-govteam** [comment]
checker:manualTrigger

**Comment by jevticgallonsd1466** [comment]
checker:manualTrigger

**Comment by cryptowhizzard** [comment]
Dear jevticgallonsd1466,

As notary I am doing due diligence on your LDN. I could not get retrieval to work. Can you please upload the car file of CID baga6ea4seaqdabzks6yus3wbcdothtyxz22v7aofrar5ahqd2yti5ez6tjynmdq ?

You can use our upload system at http://send.datasetcreators.com. Please select 7 days for the system to keep the file and post the link you received here so I (and other notaries) can download your content.

**Comment by jevticgallonsd1466** [comment]
> Dear jevticgallonsd1466,
> 
> As notary I am doing due diligence on your LDN. I could not get retrieval to work. Can you please upload the car file of CID baga6ea4seaqdabzks6yus3wbcdothtyxz22v7aofrar5ahqd2yti5ez6tjynmdq ?
> 
> You can use our upload system at http://send.datasetcreators.com. Please select 7 days for the system to keep the file and post the link you received here so I (and other notaries) can download your content.

@cryptowhizzard       https://send.datasetcreators.com/download/4ef9119c7cbf7c7c/#N3Q-zMeHpWkZJFhUDBixMQ

**Comment by cryptowhizzard** [comment]
Thanks!

Unpacked & verified.

I will whitelist your application.

**Comment by jevticgallonsd1466** [comment]
checker:manualTrigger

**Comment by cryptowhizzard** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced5i3gua3e6xp6nc4lmyql5uhfn7sqnfdkgobvtgu6w63wgzbddj2 
#### Address 
> f1hhv5js4gxnw5z4vs7jvgr2cwygtp6gcecog4mui
#### Datacap Allocated
> 1.56PiB
#### Signer Address
> f1krmypm4uoxxf3g7okrwtrahlmpcph3y7rbqqgfa
#### Id
> 1f329b2b-0fe0-4f56-bf85-d101737ff947
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced5i3gua3e6xp6nc4lmyql5uhfn7sqnfdkgobvtgu6w63wgzbddj2

**Comment by a1991car** [comment]
checker:manualTrigger

**Comment by a1991car** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecs2xhjkyvhayampifuugkf7i62hiivyabdbnghov6y75445m33gy 
#### Address 
> f1hhv5js4gxnw5z4vs7jvgr2cwygtp6gcecog4mui
#### Datacap Allocated
> 1.56PiB
#### Signer Address
> f1qnumecdypgrbaebtkdfjnwt5ndacadcuas3deiq
#### Id
> 1f329b2b-0fe0-4f56-bf85-d101737ff947
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecs2xhjkyvhayampifuugkf7i62hiivyabdbnghov6y75445m33gy

**Comment by jevticgallonsd1466** [comment]
@Sunnyiscoming  @raghavrmadya  @Kevin-FF-USA 
Hello.  Due to the celebrations of the National Day, I inadvertently missed the robot's reminder and it was closed. Could you please assist me in restarting and reopening it? Thank you very much.

**Comment by jevticgallonsd1466** [comment]
@kevzak  please

**Comment by jevticgallonsd1466** [comment]
checker:manualTrigger

**Comment by jevticgallonsd1466** [comment]
checker:manualTrigger

**Comment by AlanGreaterheat** [comment]
checker:manualTrigger

**Comment by AlanGreaterheat** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceak2jfbehumdpebawgi7rbkehv74lgpv5aohtexjfdw6fokkdvd4q 
#### Address 
> f1hhv5js4gxnw5z4vs7jvgr2cwygtp6gcecog4mui
#### Datacap Allocated
> 1.56PiB
#### Signer Address
> f1pnmzlxj7cfeo2v6oj5nco46hkg2l46wj7o4xxui
#### Id
> 1f329b2b-0fe0-4f56-bf85-d101737ff947
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceak2jfbehumdpebawgi7rbkehv74lgpv5aohtexjfdw6fokkdvd4q

**Comment by mikezli** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebhbubvv2vl5upqqqmlr2hlub4opqulzvcembukxemdsdiyviynb6 
#### Address 
> f1hhv5js4gxnw5z4vs7jvgr2cwygtp6gcecog4mui
#### Datacap Allocated
> 1.56PiB
#### Signer Address
> f1dnb3uz7sylxk6emti3ififcvu3nlufnnsjui6ea
#### Id
> 1f329b2b-0fe0-4f56-bf85-d101737ff947
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebhbubvv2vl5upqqqmlr2hlub4opqulzvcembukxemdsdiyviynb6

**Comment by jevticgallonsd1466** [comment]
@Sunnyiscoming  Hello, The signatures for this round have been approved, but dc has not been increased.
![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/135803746/5de066a9-49d3-4430-9b19-50c7127a3b65)

**Comment by jevticgallonsd1466** [comment]
checker:manualTrigger

**Comment by AlanGreaterheat** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec5fpdignlc3mkw7wgtfa2dil4e7a73kmmlhfkqycomyxxm3fudwa 
#### Address 
> f1hhv5js4gxnw5z4vs7jvgr2cwygtp6gcecog4mui
#### Datacap Allocated
> 1.56PiB
#### Signer Address
> f1pnmzlxj7cfeo2v6oj5nco46hkg2l46wj7o4xxui
#### Id
> e20bcff4-83f2-4801-a09e-8494ede73f87
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec5fpdignlc3mkw7wgtfa2dil4e7a73kmmlhfkqycomyxxm3fudwa

**Comment by AlanGreaterheat** [comment]
Re-signing due to malfunction.

**Comment by Chuangshi1** [comment]
Report shows fine. Support for this round. Keep watching.

**Comment by Chuangshi1** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceccgxw2zg6bbefp7fi3mpqdn43eim32aloh2qnsiwy3qq5ppmwsc4 
#### Address 
> f1hhv5js4gxnw5z4vs7jvgr2cwygtp6gcecog4mui
#### Datacap Allocated
> 1.56PiB
#### Signer Address
> f1mdk7s2vntzm6hu35yuo6vjubtrpfnb2awhgvrri
#### Id
> e20bcff4-83f2-4801-a09e-8494ede73f87
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceccgxw2zg6bbefp7fi3mpqdn43eim32aloh2qnsiwy3qq5ppmwsc4

**Comment by Sunnyiscoming** [comment]
Hello, @jevticgallonsd1466 per the https://github.com/filecoin-project/notary-governance/issues/922 for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

This information will be reviewed by Fil+ Governance team to confirm validity and then the application will be allowed to move forward for additional notary review.

**Comment by jevticgallonsd1466** [comment]
> Hello, @jevticgallonsd1466 per the [filecoin-project/notary-governance#922](https://github.com/filecoin-project/notary-governance/issues/922) for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.
> 
> This information will be reviewed by Fil+ Governance team to confirm validity and then the application will be allowed to move forward for additional notary review.

@Sunnyiscoming  Hello, the form has been submitted. All sps:
|sp|ids|origin|
|--|--|--|
|topblocks|f02301,f03223,f0143858,f0240185|Santa Clara(US)|
|Lianxing storage|f02240216|Tokyo|
|STRAITDEER PTE. LTD.|f02093396,f02259777|Singapore|
|Aron|f01877184|Singapore|
|james|f02201190|us|
|luna|f02252173|Tokyo|
|zkware|f02230375  f02230941 f02230939 f02230935|hongkong(cn)|
|treal|f02032191|zhejiang(cn)|
|赛道云存储|f01939387,f01941622|sichuan(cn)|
|lizhenjie|f02201915|sichuan(cn)|
|Hainan future cloud Technology Co., LTD|f02519323|ningxia(cn)|
|guan|f02808888|guangzhou(cn)|
|zhiwei|f01843178,f01877259|hunan(cn)|
|peter|f02237010|Californial(us)|
|Michael|f02058333,f02234424|Texas(us)|
|nick|f01969779|us|
|eager|f02237006|england|
|jastin|f02816666|huhehaote(cn)|
|guan|f02808889|Hong Kong(cn)|
|mike|f02062851|Californial(us)|
|Feige IT|f02228866|Tokyo|

**Comment by jevticgallonsd1466** [comment]
checker:manualTrigger

**Comment by jevticgallonsd1466** [comment]
checker:manualTrigger

**Comment by jevticgallonsd1466** [comment]
checker:manualTrigger

**Comment by jevticgallonsd1466** [comment]
checker:manualTrigger

**Comment by jevticgallonsd1466** [comment]
checker:manualTrigger

**Comment by jevticgallonsd1466** [comment]
checker:manualTrigger
