### ISSUE TITLE
[DataCap Application] NDLABS - SocialNetwork

### ISSUE THREAD

**Issue by NDLABS-Leo** [filecoin-project/filecoin-plus-large-datasets#2055]
### Data Owner Name

NDLABS

### What is your role related to the dataset

Storage provider filling out application on behalf of the data owner

### Data Owner Country/Region

Singapore

### Data Owner Industry

Not-for-Profit

### Website

https://www.ndlabs.io/#/

### Social Media

```text
Twitter： @imNDLABS
Slack： @NDLABS-OFFICE
```

### Total amount of DataCap being requested

15PiB

### Expected size of single dataset (one copy)

2

### Number of replicas to store

8

### Weekly allocation of DataCap requested

1PiB

### On-chain address for first allocation

f1mx2y5mxynrd5csutdhtfhgep4ct533wbmcbozfy

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
ND LABS has technical operation centers and nodes in Singapore, Hong Kong, the United States, and Dubai. Since Fil has launch of the mainnet in 2020, ND has begun to provide technical services to partners to help them complete the construction of storage services. At present, the accumulated storage power of ND exceeds 300P globally. The largest node has 100P storage power, and the node owns exceeds more than 1.4 million FIL. 
ND LABS is positioned as a decentralized storage service provider for WEB3. For a long time, ND not only focuses on building nodes for partners, but also explores how to provide better storage services for potential clients of web3. Since October 2021, ND has been deeply involved in the FilPlus project, vigorously promoting the Filplus project to partners who has effective data storage needs. We also providing them with a complete set of solutions and technical services for storing data in the FIL network. The Singapore and US nodes are the main storage nodes, which was provide real data storage for early customers.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
Social networks occupy our lives, and the information on social networks covers the daily life and development of all human beings. If we can preserve the publicly available information on social networks, it will be of great help to human development.
We have collected data from: 
Yahoo! Graph and Social Data 、Twitter Scrape Calufa May 2011、Twitter Graph of entire Twitter site、Twitter Data for Sentiment Analysis、Twitter Data for Online Reputation Management、Twitch Top Streamer's Data、Network Twitter Data、GitHub Collaboration Archive 、Facebook Social Networks from LAW (since 2007) 、China Biographical Database 、Youtube Video Social Graph ... and more than other 600 datasets. 
In total 2PiB, at least 8- 10x copies.
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### How do you plan to prepare the dataset

IPFS, lotus, singularity, graphsplit

### Please share a sample of the data

```text
https://law.di.unimi.it/datasets.php
https://webscope.sandbox.yahoo.com/catalog.php?datatype=g
https://projects.iq.harvard.edu/cbdb
https://archive.org/details/oxford-2005-facebook-matrix
http://snap.stanford.edu/data/higgs-twitter.html
http://nlp.uned.es/replab2013/
https://netsg.cs.sfu.ca/youtubedata/
https://data.humdata.org/dataset/social-connectedness-index
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

1 to 1.5 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America

### How will you be distributing your data to storage providers

HTTP or FTP server, IPFS, Shipping hard drives

### How do you plan to choose storage providers

Slack, Big Data Exchange, Partners

### If you already have a list of storage providers to work with, fill out their names and provider IDs below

```text
No response
```

### How do you plan to make deals to your storage providers

Boost client, Lotus client

### If you answered "Others/custom tool" in the previous question, enter the details here

```text
No response
```

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
Please share more detailed information about sps you will cooperate with.

**Comment by NDLABS-OFFICE** [comment]
@Sunnyiscoming  Thank you for your reply, recently we have been contacting quality SPs in different geographies, the most recent ones are the following: f01834253//f01834291//f01853077//f01854080//f01985611//f02047841//f02148382//f02115125//f02000936 and will continuously update.

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 15PiB

**Expected weekly DataCap usage rate**
> 1PiB

**Client address**
>f1mx2y5mxynrd5csutdhtfhgep4ct533wbmcbozfy

**Comment by woshidama323** [comment]
LGTM ,Will support this new application

**Comment by woshidama323** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebe4o6527v2ze6u43ib5vt7yxalke6rn74iv5hvk4u2jwx2vwjspg 
#### Address 
> f1mx2y5mxynrd5csutdhtfhgep4ct533wbmcbozfy
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f12tk3adljauwnd3hjbigpfxb7b7gdlj63p6afwtq
#### Id
> c2cea207-0009-4d15-8015-ea77318f424b
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebe4o6527v2ze6u43ib5vt7yxalke6rn74iv5hvk4u2jwx2vwjspg

**Comment by herrehesse** [comment]
@raghavrmadya @Kevin-FF-USA @kevzak 

I have mentioned this multiple times the last 6 months, merged datasets should NOT be allowed.
@DaYouGroup & @woshidama323 why did you support this application?

It is impossible to check, verify, control or do due diligence on something that looks like this:
> Yahoo! Graph and Social Data 、Twitter Scrape Calufa May 2011、Twitter Graph of entire Twitter site、Twitter Data for Sentiment Analysis、Twitter Data for Online Reputation Management、Twitch Top Streamer's Data、Network Twitter Data、GitHub Collaboration Archive 、Facebook Social Networks from LAW (since 2007) 、China Biographical Database 、Youtube Video Social Graph ... and more than other 600 datasets. 

Love to have a response, and open a dispute after.

Love to hear from @simonkim0515 @raghavrmadya @NDLABS-OFFICE As well.

**Comment by raghavrmadya** [comment]
@herrehesse , thanks for the comment. @DaYouGroup @woshidama323, you are encouraged to conduct more holistic due diligence. We discouraged merged datasets. Client is requested to apply for each dataset differently. If the dataset has been previously stored, provide justification for why you would like to store it again. is it prepared differently? how? 

Notaries are also responsible for this.

Pause further allocation until resolved

**Comment by herrehesse** [comment]
Added discussion thread with Leo from NDLabs: https://filecoinproject.slack.com/archives/C0405HANNBT/p1687329227367969?thread_ts=1687270367.649529&cid=C0405HANNBT

**Comment by NDLABS-OFFICE** [comment]
![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/104019147/a6b038f4-5e08-42d9-88f6-bb385620eec7)

According to the latest notification from the community, data is allowed to be signed

**Comment by NDLABS-OFFICE** [comment]
checker:manualTrigger

**Comment by sxxfuture-official** [comment]
CID checker report looks well , and retrieve bot report is OK, will support

**Comment by sxxfuture-official** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedvqymwx3kmmqijx3jqmua4wlhnkjhqakrqaf6hwkl6j6ekl47vqu 
#### Address 
> f1mx2y5mxynrd5csutdhtfhgep4ct533wbmcbozfy
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f1foiomqlmoshpuxm6aie4xysffqezkjnokgwcecq
#### Id
> 9fb65dc3-ac7e-4ab6-9d17-7905525742e9
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedvqymwx3kmmqijx3jqmua4wlhnkjhqakrqaf6hwkl6j6ekl47vqu

**Comment by maxvint** [comment]
checker:manualTrigger

**Comment by maxvint** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedvc3w7322obskq5th7zt4nbtlzqqbzjfeiw3pbabro343cont2d4 
#### Address 
> f1mx2y5mxynrd5csutdhtfhgep4ct533wbmcbozfy
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f1ui5iy4mmkxjbw7752omiwp2ols2fzv4thrayagi
#### Id
> 9fb65dc3-ac7e-4ab6-9d17-7905525742e9
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedvc3w7322obskq5th7zt4nbtlzqqbzjfeiw3pbabro343cont2d4

**Comment by NDLABS-OFFICE** [comment]
checker:manualTrigger

**Comment by cryptowhizzard** [comment]
This application has been signed despite request of the T&T working group not to sign.

@NDLABS-OFFICE you are notary. Notary's have to have a clean sheet and example role of nice behaviour for this community. I would advise to close this application.

**Comment by NDLABS-OFFICE** [comment]
> ![图像](https://user-images.githubusercontent.com/104019147/249356554-a6b038f4-5e08-42d9-88f6-bb385620eec7.png)
> 
> 根据社区最新通知，允许数据签名

@cryptowhizzard As a notary, you should have also seen the content posted by RG.

**Comment by 1ane-1** [comment]
checker:manualTrigger

**Comment by 1ane-1** [comment]
Above the datacap and CID checker report, it is No CID sharing and good retrieval success rate. But pay attention to the Deal Data Replication. Hope you can deal with it.

**Comment by Fatman13** [comment]
checker:manualTrigger

**Comment by Fatman13** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecliw7bnxyq33thyatu4wk6czduvzhflbfhqb6y4sefr7xeebweza 
#### Address 
> f1mx2y5mxynrd5csutdhtfhgep4ct533wbmcbozfy
#### Datacap Allocated
> 1.00PiB
#### Signer Address
> f1j3u7crhjzwb2cj5mq7vodlt4o66yoyci7lhcauy
#### Id
> f304678a-94f6-4a9c-8211-fa439127ea30
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecliw7bnxyq33thyatu4wk6czduvzhflbfhqb6y4sefr7xeebweza

**Comment by Fatman13** [comment]
Reached out by the client multiple times. Was told that some misunderstanding within T&T WG is resolved and a plan to fix CIDChecker.

**Comment by Normalnoise** [comment]
checker:manualTrigger

**Comment by NiwanDao** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecdn2essais52fumrtu5kcr2wl2lpzewcv2mtpnhxt3ztxzpdekmg 
#### Address 
> f1mx2y5mxynrd5csutdhtfhgep4ct533wbmcbozfy
#### Datacap Allocated
> 1.00PiB
#### Signer Address
> f1a2lia2cwwekeubwo4nppt4v4vebxs2frozarz3q
#### Id
> f304678a-94f6-4a9c-8211-fa439127ea30
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecdn2essais52fumrtu5kcr2wl2lpzewcv2mtpnhxt3ztxzpdekmg

**Comment by kernelogic** [comment]
Reports LGTM. Merged dataset is still allowed for existing applications.

**Comment by kernelogic** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceajlm4kwb6p6ak3krv4zzh7iebyw3xnkxivrtyiyvihekooq62mey 
#### Address 
> f1mx2y5mxynrd5csutdhtfhgep4ct533wbmcbozfy
#### Datacap Allocated
> 1.00PiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### Id
> f304678a-94f6-4a9c-8211-fa439127ea30
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceajlm4kwb6p6ak3krv4zzh7iebyw3xnkxivrtyiyvihekooq62mey

**Comment by NiwanDao** [comment]
Hope to see more replications in the next tranche.

**Comment by NDLABS-Leo** [comment]
@NiwanDao Thanks for your support, because the data is responsible for different transfer speeds, the data backups are planned.

**Comment by psh0691** [comment]
checker:Trigger

**Comment by psh0691** [comment]
checker:manualTrigger

**Comment by mikezli** [comment]
Although the retrieval rate has not reached 50%, it is also improving, and it is temporarily supported

**Comment by mikezli** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecfn4r4326rxhcmzn7jfinlbirfkkd55tmtgg3uakbhxgus63ubry 
#### Address 
> f1mx2y5mxynrd5csutdhtfhgep4ct533wbmcbozfy
#### Datacap Allocated
> 1.00PiB
#### Signer Address
> f1dnb3uz7sylxk6emti3ififcvu3nlufnnsjui6ea
#### Id
> f304678a-94f6-4a9c-8211-fa439127ea30
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecfn4r4326rxhcmzn7jfinlbirfkkd55tmtgg3uakbhxgus63ubry

**Comment by nj-steve** [comment]
checker:manualTrigger

**Comment by NDLABS-Leo** [comment]
checker:manualTrigger

**Comment by AlanGreaterheat** [comment]
Based on RG's information, we are willing to support this application, but we would like to know what is going to be done about "Deal Data Replication"?

**Comment by NDLABS-Leo** [comment]
@AlanGreaterheat Our data backup is done mainly through internet bandwidth and hard disk transfers. Recently, because we need to spread out geographically more, we have contacted a new sp for backup storage, and are in the process of increasing bandwidth, which will have noticeable results in 1~2 weeks. Also, hard disk mailings should be arriving at their destinations one after another in 1~2 weeks. So the data backup reports will see a noticeable boost at that time.

**Comment by AlanGreaterheat** [comment]
> @AlanGreaterheat Our data backup is done mainly through internet bandwidth and hard disk transfers. Recently, because we need to spread out geographically more, we have contacted a new sp for backup storage, and are in the process of increasing bandwidth, which will have noticeable results in 1 ~ 2 weeks. Also, hard disk mailings should be arriving at their destinations one after another in 1 ~ 2 weeks. So the data backup reports will see a noticeable boost at that time.

Looking forward to seeing improvements！

**Comment by igoovo** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacea4v33uq2vew4mxsboryfvgvywxhh52wgtlbhqr3v6uaygnde6pg4 
#### Address 
> f1mx2y5mxynrd5csutdhtfhgep4ct533wbmcbozfy
#### Datacap Allocated
> 2.00PiB
#### Signer Address
> f1shnsfayxqll77svffaxnjenms7bbbysbqcatrpy
#### Id
> 02bfe2e7-5018-433a-a8bb-0cdac4aa8c03
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacea4v33uq2vew4mxsboryfvgvywxhh52wgtlbhqr3v6uaygnde6pg4

**Comment by AlanGreaterheat** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceanuopimenuytowccddkfeh7n46uci7ge67rvesnuhmgqf6w4nzss 
#### Address 
> f1mx2y5mxynrd5csutdhtfhgep4ct533wbmcbozfy
#### Datacap Allocated
> 2.00PiB
#### Signer Address
> f1pnmzlxj7cfeo2v6oj5nco46hkg2l46wj7o4xxui
#### Id
> 02bfe2e7-5018-433a-a8bb-0cdac4aa8c03
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceanuopimenuytowccddkfeh7n46uci7ge67rvesnuhmgqf6w4nzss

**Comment by igoovo** [comment]
The report shows normal, there are many storage nodes, willing to support.
But , The retrieval rate needs to be improved continuously.

**Comment by ipollo00** [comment]
checker:manualTrigger

**Comment by NDLABS-Leo** [comment]
checker:manualTrigger

**Comment by NDLABS-Leo** [comment]
checker:manualTrigger

**Comment by NDLABS-Leo** [comment]
checker:manualTrigger

**Comment by NDLABS-Leo** [comment]
checker:manualTrigger

**Comment by NDLABS-Leo** [comment]
checker:manualTrigger

**Comment by NDLABS-Leo** [comment]
checker:manualTrigger

**Comment by laurarenpanda** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecnrfee5gbziftmv3lk54nvc73625ootsqlyentrdqdmnb5nciao6 
#### Address 
> f1mx2y5mxynrd5csutdhtfhgep4ct533wbmcbozfy
#### Datacap Allocated
> 2.00PiB
#### Signer Address
> f1bp3tzp536edm7dodldceekzbsx7zcy7hdfg6uzq
#### Id
> db64c37a-9819-4be7-b728-b869b0b737e2
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecnrfee5gbziftmv3lk54nvc73625ootsqlyentrdqdmnb5nciao6

**Comment by zcfil** [comment]
checker:manualTrigger

**Comment by zcfil** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacea4gjezchllugjmnegmd6eoex5k24nlcfkojzef24nekqzjghelre 
#### Address 
> f1mx2y5mxynrd5csutdhtfhgep4ct533wbmcbozfy
#### Datacap Allocated
> 2.00PiB
#### Signer Address
> f1cjzbiy5xd4ehera4wmbz63pd5ku4oo7g52cldga
#### Id
> db64c37a-9819-4be7-b728-b869b0b737e2
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacea4gjezchllugjmnegmd6eoex5k24nlcfkojzef24nekqzjghelre

**Comment by kenzz45** [comment]
> This application has been signed despite request of the T&T working group not to sign.
> 
> @NDLABS-OFFICE you are notary. Notary's have to have a clean sheet and example role of nice behaviour for this community. I would advise to close this application.

Comments from DC seller, we are inclined to ignore.

**Comment by Filplus-Watchdog** [comment]
![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/107618834/1590963c-0083-4972-a31b-69cae5095e12)

**Comment by NDLABS-Leo** [comment]
> ![image](https://user-images.githubusercontent.com/107618834/258648056-1590963c-0083-4972-a31b-69cae5095e12.png)

Are you an active notary? If not, your dispute doesn't really fall within this scope.

**Comment by NDLABS-Leo** [comment]
> > ![image](https://user-images.githubusercontent.com/107618834/258648056-1590963c-0083-4972-a31b-69cae5095e12.png)
> 
> Are you an active notary? If not, your dispute doesn't really fall within this scope.

**Comment by Filplus-govteam** [comment]
checker:manualTrigger

**Comment by NDLABS-Leo** [comment]
checker:manualTrigger

**Comment by NDLABS-Leo** [comment]
@Filplus-govteam @Filplus-Watchdog
We have already responded to the queries regarding this application. Can we proceed now?

**Comment by NDLABS-Leo** [comment]
Preparing to reactivate this application, in compliance with the pre-disclosure rules, I'm disclosing the reasons as follows:

link:   https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/2084#issuecomment-1685568090

**Comment by data-programs** [comment]
<img width="32" alt="KYC" Verified src="https://stable.filplus.storage/images/filplus-kyc-verified-badge.png"/>

This user’s identity has been verified through [filplus.storage](https://filplus.storage)

**Comment by 1ane-1** [comment]
checker:manualTrigger

**Comment by 1ane-1** [comment]
The dispute has been more than fourteen days, and the author has responded to the dispute
CID report is ok but Deal Data Replication need to resolve.
Support for this round, if there is anything against the rule, i will cancel my sign.

**Comment by 1ane-1** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebpzkk32vww5dvsappxk5cqxncmqizj2us5t6cyfycojy62b4kdzq 
#### Address 
> f1mx2y5mxynrd5csutdhtfhgep4ct533wbmcbozfy
#### Datacap Allocated
> 2.00PiB
#### Signer Address
> f1mdk7s2vntzm6hu35yuo6vjubtrpfnb2awhgvrri
#### Id
> a61d31bc-7b6b-4733-b4d2-64b16e98255c
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebpzkk32vww5dvsappxk5cqxncmqizj2us5t6cyfycojy62b4kdzq

**Comment by luobin544** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb6daonugntrbr5vwge7r4gmvowmcrwi5m5g2vnd4zoeuycjtujh6 
#### Address 
> f1mx2y5mxynrd5csutdhtfhgep4ct533wbmcbozfy
#### Datacap Allocated
> 2.00PiB
#### Signer Address
> f1tbd632f6w62glfaf7wjpimacbnjiz26poyoes2q
#### Id
> a61d31bc-7b6b-4733-b4d2-64b16e98255c
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb6daonugntrbr5vwge7r4gmvowmcrwi5m5g2vnd4zoeuycjtujh6

**Comment by NDLABS-Leo** [comment]
Keep Open.

**Comment by NDLABS-Leo** [comment]
checker:manualTrigger

**Comment by nj-steve** [comment]
Hello , do you have any plan to solve the problem of "Deal Data Replication"?
⚠️ 76.03% of deals are for data replicated across less than 4 storage providers.

**Comment by NDLABS-Leo** [comment]
@nj-steve 
Hello, from the bot's records, you can see that the backup ratio has been continuously decreasing because the project is undergoing continuous sealing, and different storage providers (SPs) have different speeds. Additionally, we have already contacted the SPs and requested adjustments to the data storage progress. The storage ratio will continue to decrease until it becomes fully compliant.

**Comment by nj-steve** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceajswubec36a4pnzqyohnlqq4p2h6zv6wvry362uhhqfsg2hsjluq 
#### Address 
> f1mx2y5mxynrd5csutdhtfhgep4ct533wbmcbozfy
#### Datacap Allocated
> 2.00PiB
#### Signer Address
> f1xx6555qijma7igpnjspyvdunc4vfxkawnpqy5ii
#### Id
> 55d7a1fd-20e1-4c3b-953b-7c13dbcceafb
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceajswubec36a4pnzqyohnlqq4p2h6zv6wvry362uhhqfsg2hsjluq

**Comment by nj-steve** [comment]
hope to solve it

**Comment by OpenGate01** [comment]
checker:manualTrigger

**Comment by OpenGate01** [comment]
> @nj-steve Hello, from the bot's records, you can see that the backup ratio has been continuously decreasing because the project is undergoing continuous sealing, and different storage providers (SPs) have different speeds. Additionally, we have already contacted the SPs and requested adjustments to the data storage progress. The storage ratio will continue to decrease until it becomes fully compliant.

Hope to see good changes in the future.

**Comment by OpenGate01** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec4xyrxc3mlv2gek35qaybtojsthrtd3typ6ghnuujn5ivv4lge2y 
#### Address 
> f1mx2y5mxynrd5csutdhtfhgep4ct533wbmcbozfy
#### Datacap Allocated
> 2.00PiB
#### Signer Address
> f1im4hmtbfzqnx7ir74kdaiu4ynjhgqh3sdi2snla
#### Id
> 55d7a1fd-20e1-4c3b-953b-7c13dbcceafb
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec4xyrxc3mlv2gek35qaybtojsthrtd3typ6ghnuujn5ivv4lge2y

**Comment by NDLABS-Leo** [comment]
The project is mostly completed, and the application is now closed.
