### ISSUE TITLE
[DataCap Application] DIASICT Inc

### ISSUE THREAD

**Issue by diasict** [filecoin-project/filecoin-plus-large-datasets#2056]
### Data Owner Name
DIASICT Inc

### What is your role related to the dataset
Data Preparer

### Data Owner Country/Region
South Korea

### Data Owner Industry
Web3 / Crypto

### Website
[http://www.diasict.com/](http://www.diasict.com/)

### Social Media
[at]Riverstone (slack)

### Total amount of DataCap being requested
100 TiB

### Expected size of single dataset (one copy)
20 GiB

### Number of replicas to store
3

### Weekly allocation of DataCap requested
50 TiB

### On-chain address for first allocation
f1jk7gbw5mjqwlwkl3oz2yx6ms3rlyza2mgwk4dxa

### Data Type of Application
Private Commercial/Enterprise

### Custom multisig
Use Custom Multisig

### Share a brief history of your project and organization
We are a leader in the filecoin and web3.0 industry in Korea. We have experience in building IPFS IDC for Filecoin and are managing a 10PiB class SP. We are inviting companies that need storage space to apply for datacap. Please approve the data cap. 

### Is this project associated with other projects/ecosystem stakeholders?
No

### If answered yes, what are the other projects/ecosystem stakeholders
n/a

### Describe the data being stored onto Filecoin
Various data is stored. We are planning to collect files necessary for the industry, such as video project libraries, corporate documents, and CCTV footage, and store them in the Filecoin system.

### Where was the data currently stored in this dataset sourced from
Other

### If you answered "Other" in the previous question, enter the details here
n/a

### How do you plan to prepare the dataset
lotus

### If you answered "other/custom tool" in the previous question, enter the details here
n/a

### Please share a sample of the data
Absolutely. I can show you some of them.

### Confirm that this is a public dataset that can be retrieved by anyone on the Network
No

### If you chose not to confirm, what was the reason
Includes corporate documents, materials related to management, and personal information. 

### What is the expected retrieval frequency for this data
Sporadic

### For how long do you plan to keep this dataset stored on Filecoin
More than 3 years

### In which geographies do you plan on making storage deals
Asia other than Greater China

### How will you be distributing your data to storage providers
Lotus built-in data transfer

### How do you plan to choose SP
Partners

### If you answered "Others" in the previous question, what is the tool or platform you plan to use
n/a

### If you already have a list of storage providers to work with, fill out their names and provider IDs below
f01340400
f01310053
f033025

### How do you plan to make deals to your storage providers
Lotus client

### If you answered "Others/custom tool" in the previous question, enter the details here
n/a

### Can you confirm that you will follow the Fil+ guideline
Yes

_Application created via [filplus.storage](https://filplus.storage)_

**Comment by diasict** [comment]
Sorry, I don't understand what you mean. What effort do I need to make to get a datacap? It doesn't have to be a large amount.

**Comment by Sunnyiscoming** [comment]
You plan to collect some data. But Filecoin Plus requires the dataset that only collected datasets can be applied for datacap.
You can see the guidance here.
https://github.com/filecoin-project/filecoin-plus-large-datasets

**Comment by Sunnyiscoming** [comment]
Close for no reply.
