### ISSUE TITLE
[DataCap Application] National Blend of Models

### ISSUE THREAD

**Issue by AN-Toby** [filecoin-project/filecoin-plus-large-datasets#2057]
### Data Owner Name

NOAA

### What is your role related to the dataset

Data Preparer

### Data Owner Country/Region

United States

### Data Owner Industry

Environment

### Website

https://www.noaa.gov/

### Social Media

```text
https://vlab.noaa.gov/web/mdl/nbm
https://twitter.com/NOAA
https://www.facebook.com/NOAA
```

### Total amount of DataCap being requested

11PiB

### Expected size of single dataset (one copy)

1083.7TiB

### Number of replicas to store

10

### Weekly allocation of DataCap requested

1PiB

### On-chain address for first allocation

f16cdcyahaupjbe72gfi7uzu5b57m4t3ppszmav2i

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
In order to preserve the beneficial data, I store this dataset in filecoin to protect this data with distributed storage. The National Blend of Models (NBM) is a nationally consistent and skillful suite of calibrated forecast guidance based on a blend of both NWS and non-NWS numerical weather prediction model data and post-processed model guidance. The goal of the NBM is to create a highly accurate, skillful and consistent starting point for the gridded forecast.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
National Blend of Models (NBM) --- COG Format and Grib2 Format
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### How do you plan to prepare the dataset

lotus, singularity, I don't know yet

### Please share a sample of the data

```text
https://registry.opendata.aws/noaa-nbm/
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Sporadic

### For how long do you plan to keep this dataset stored on Filecoin

2 to 3 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, Africa, North America

### How will you be distributing your data to storage providers

Cloud storage (i.e. S3), HTTP or FTP server, IPFS, Shipping hard drives, Lotus built-in data transfer

### How do you plan to choose storage providers

Slack, Big Data Exchange, Partners

### If you already have a list of storage providers to work with, fill out their names and provider IDs below

```text
f01784916 f01183845 I'll find more sp for cooperation.
```

### How do you plan to make deals to your storage providers

Lotus client, Bidbot, Singularity, I don't know yet

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 11PiB

**Expected weekly DataCap usage rate**
> 1PiB

**Client address**
>f16cdcyahaupjbe72gfi7uzu5b57m4t3ppszmav2i

**Comment by spaceT9** [comment]
Do you apply for dataCap as an individual or organization? Because I did not see your own website

**Comment by PluskitOfficial** [comment]
@AN-Toby Do you have independent intellectual property rights for the data to be stored?

**Comment by raghavrmadya** [comment]
This application is being audited by T&T WG. GitHub account is suspicious and has no previous activity. Do you have a history of storing data on Filecoin? Why do you think this dataset is valuable to the network and how is it prepared differently.

**Comment by AN-Toby** [comment]
@spaceT9 Yes, i'm an individual dp.
@PluskitOfficial This is public dataset from AWS. I'm not the owner of the data.
@raghavrmadya This is my first time to store data in filecoin and it is my first application. I happened to read this dataset that the NBM is considered an important part of the efforts to evolve NWS capabilities to achieve a Weather-Ready Nation. Cause it is helpful to provide forecasters with a suite of information to use for their forecasts, I want to store it for research.

**Comment by herrehesse** [comment]
@AN-Toby, we already have numerous copies of this data set, and we need a comprehensive explanation from you regarding why the community should allocate you additional data capacity to replicate it again. Additionally, for first-time applications, there is a recommended limit of 100T to establish trust within the community and showcase your skills and the quality of your work.

I don't endorse this LDN currently.

**Comment by cryptowhizzard** [comment]
I want to add that f01183845 does not have it's address set on chain and is not suitable to participate in Fil+

lotus net connect f01183845
f01183845 -> {12D3KooWEDUAzWkztePXn2gBSHgaq78N5oksL68iTFwZXsd85Gau: []}
connect 12D3KooWEDUAzWkztePXn2gBSHgaq78N5oksL68iTFwZXsd85Gau: success

**Comment by cryptowhizzard** [comment]
> @cryptowhizzard The address of sp will be published when they begin sealing. Now we need notary's help for their signature.

Sorry but there are some rules in the community.
One rule is that notary's should do due diligence. Part of this is KYC and to have a decent distribution plan.

**Comment by cryptowhizzard** [comment]
Dear @AN-Toby 

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Looking at your application i have some questions:
As you are brand new on Github and have no history of past applications. Can you give me an introduction who you are and an introduction about your company?

You stated that you are a Data preparer. What hardware do you have over there to prepare this dataset? What is your internet connection speed? Do you already have the data downloaded on the premises?

It seems to me that applying for 11PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?

Can you show us some visible proof of the size of your data and the storage / packing hardware you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230337462961356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!

**Comment by HiFil** [comment]
checker:manualTrigger

**Comment by AN-Toby** [comment]
Hello community. After a period  of preparation, we’ve contacted with more Sps for cooperation. f0132765, f01214563, f0110944. They agreed to support retrieval and I’ll focus on it after we been granted. I’ve also contacted with some notaries who’d like give us a chance for storage. Please help us for signatures, and I’ll improve it as soon as we meet any problems.

**Comment by cryptowhizzard** [comment]
Hi @AN-Toby 

Per the https://github.com/filecoin-project/notary-governance/issues/922 for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

This information will be reviewed by Fil+ Governance team to confirm validity and then the application will be triggered for notary review.

**Comment by AN-Toby** [comment]
@cryptowhizzard ok. I have filled the form.
![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/125245765/fca2a42b-9bfb-45ce-b93c-543fd41976d7)

**Comment by Filplus-govteam** [comment]
Confirming the following SP Entities were submitted:
f01784916 Korea
f0132765 Korea
f01214563 Hong Kong
f0110944 China
f01183845 Korea

**Comment by Casey-PG** [comment]
For the first round, I will support you. Hope you keep the Fil+rules.

**Comment by ipfscn** [comment]
Now the community is very chaotic, I think V5 will be delayed until after Christmas, because V4 also started last Christmas. We should not open up the V5 application until the confusion and regulatory rules are resolved.

**Comment by ipfscn** [comment]
As a first round, temporary support, I will confirm SP IDs and locations match your plan
、confirm data is retrievable and data sample matches said datasets

**Comment by ipfscn** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacearm7yixzr7u4rj7cydywwmcuzjbouy7t3yp6nhkjslldxdqljt2a 
#### Address 
> f16cdcyahaupjbe72gfi7uzu5b57m4t3ppszmav2i
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f1j4n74chme7whbz3yls4a7ixqewb6dijypqg2a3a
#### Id
> debbccd5-2400-4a3e-98dd-7175d414b96e
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacearm7yixzr7u4rj7cydywwmcuzjbouy7t3yp6nhkjslldxdqljt2a

**Comment by cryptowhizzard** [comment]
checker:manualTrigger

**Comment by cryptowhizzard** [comment]
root@proposals:~# lotus net connect f01784916
f01784916 -> {12D3KooWS6JkWdJcdqRBosKvtMvkbgGAMYsPjpiKwQ9J7GH1JqqB: [/ip4/59.23.202.101/tcp/11111]}
connect 12D3KooWS6JkWdJcdqRBosKvtMvkbgGAMYsPjpiKwQ9J7GH1JqqB: success
root@proposals:~# lotus net connect f0132765
f0132765 -> {12D3KooWMuTGuJ7ZwN2csEKpBJmJT9xfqqsHMWXQbn7s6jg7fLkT: []}
connect 12D3KooWMuTGuJ7ZwN2csEKpBJmJT9xfqqsHMWXQbn7s6jg7fLkT: failure
ERROR: routing: not found

root@proposals:~# lotus net connect f01214563
f01214563 -> {12D3KooWMbDEWbzaunjrGZs7iTsErAZVrnYENU6mxhcrkaoo1dND: []}
connect 12D3KooWMbDEWbzaunjrGZs7iTsErAZVrnYENU6mxhcrkaoo1dND: failure
ERROR: routing: not found

root@proposals:~# lotus net connect f0110944
f0110944 -> {12D3KooWD7bEyFUiHzBXENMscBuSAahNFftAJpzWfZBLbWNSBvJj: []}
connect 12D3KooWD7bEyFUiHzBXENMscBuSAahNFftAJpzWfZBLbWNSBvJj: failure
ERROR: routing: not found

root@proposals:~# lotus net connect f01183845
f01183845 -> {12D3KooWEDUAzWkztePXn2gBSHgaq78N5oksL68iTFwZXsd85Gau: []}
connect 12D3KooWEDUAzWkztePXn2gBSHgaq78N5oksL68iTFwZXsd85Gau: success
You have new mail in /var/mail/root
root@proposals:~#

**Comment by kevzak** [comment]
checker:manualTrigger

**Comment by AN-Toby** [comment]
> lotus net connect f01784916 f01784916 -> {12D3KooWS6JkWdJcdqRBosKvtMvkbgGAMYsPjpiKwQ9J7GH1JqqB: [/ip4/59.23.202.101/tcp/11111]} connect 12D3KooWS6JkWdJcdqRBosKvtMvkbgGAMYsPjpiKwQ9J7GH1JqqB: success lotus net connect f0132765 f0132765 -> {12D3KooWMuTGuJ7ZwN2csEKpBJmJT9xfqqsHMWXQbn7s6jg7fLkT: []} connect 12D3KooWMuTGuJ7ZwN2csEKpBJmJT9xfqqsHMWXQbn7s6jg7fLkT: failure ERROR: routing: not found lotus net connect f01214563 f01214563 -> {12D3KooWMbDEWbzaunjrGZs7iTsErAZVrnYENU6mxhcrkaoo1dND: []} connect 12D3KooWMbDEWbzaunjrGZs7iTsErAZVrnYENU6mxhcrkaoo1dND: failure ERROR: routing: not found lotus net connect f0110944 f0110944 -> {12D3KooWD7bEyFUiHzBXENMscBuSAahNFftAJpzWfZBLbWNSBvJj: []} connect 12D3KooWD7bEyFUiHzBXENMscBuSAahNFftAJpzWfZBLbWNSBvJj: failure ERROR: routing: not found lotus net connect f01183845 f01183845 -> {12D3KooWEDUAzWkztePXn2gBSHgaq78N5oksL68iTFwZXsd85Gau: []} connect 12D3KooWEDUAzWkztePXn2gBSHgaq78N5oksL68iTFwZXsd85Gau: success
> 
> Why are we not doing due diligence here on the SP's and why don't we adhere to notary governance 922? @Casey-PG @ipfscn

When I contacted with SPs, they promised that they will support retrieval. After I confirmed it, I put these SPs in my application. Then I requested notaries to sign for my application. It is by the rules.

Now I'm still in data preparation. I will check on the SPs before we go official.
Thank you! @Casey-PG @ipfscn

**Comment by AN-Toby** [comment]
update list of SP:
f01882035
f02196792
f02362189
f01941622
The SPs we were already talking about collaborating with wanted to delay the collaboration due to a lack of token, so I contacted other SPs to work together.

**Comment by Filplus-govteam** [comment]
Who are these SPs? Business name and location please @AN-Toby 
f01882035
f02196792
f02362189
f01941622

**Comment by Filplus-govteam** [comment]
checker:manualTrigger

**Comment by cryptowhizzard** [comment]
<img width="691" alt="Scherm­afbeelding 2023-08-26 om 22 10 28" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/36404435/14a85d74-107a-4d5c-916f-d5fb2c9bf061">
<img width="547" alt="Scherm­afbeelding 2023-08-26 om 22 10 41" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/36404435/54199e66-84c1-49cd-a1fc-08271432eb58">

Applicant is storing fake data.

http://www.datasetcreators.com/downloadedcarfiles/httpretrievals/2057-f02362577-f01941622-52247731-baga6ea4seaqfuadcclqhbdmqvxdauielm4ok7v5a2y4ijpksxefsowc25hofwdy

**Comment by kevzak** [comment]
checker:manualTrigger

**Comment by AN-Toby** [comment]
@cryptowhizzard Hello, I told SPs about what you said. SPs think that your download has some problem, so that it looks weird in your picture. Can you review what you did or fix your program?

**Comment by AN-Toby** [comment]
> f16cdcyahaupjbe72gfi7uzu5b57m4t3ppszmav2i

@Filplus-govteam Hello, they are individual SPs. Their location is Chengdu and HongKong. We will find more SPs to help store data in the next step.

**Comment by cryptowhizzard** [comment]
> @cryptowhizzard Hello, I told SPs about what you said. SPs think that your download has some problem, so that it looks weird in your picture. Can you review what you did or fix your program?

Hi An-toby,

No, i don't have a download problem. You can do the same test yourself. Download the file and do hexdump -C filename.

And no, this is no technical error. As data preparer you are responsible to pack the right data and do the distribution to your SP's. I advise you to take a look at the whitepaper of Filecoin so you can learn that there is no way the SP can store different data then the data you provided to him.

Thanks

**Comment by kevzak** [comment]
Original SPs provided:
f01882035
f02196792
f02362189
f01941622

Actual SPs storing data:
f02095764 | Hong Kong, Central and Western, HKANLIAN NETWORK TECHNOLOGY CO., LIMITED | 62.34 TiB | 13.17% | 62.34 TiB 
**f01882035** | Chengdu, Sichuan, CNChina Mobile Communications Group Co., Ltd. | 94.81 TiB | 20.03% | 94.81 TiB | 0.00%
**f01941622** | Chengdu, Sichuan, CNChina Mobile Communications Group Co., Ltd. | 89.19 TiB | 18.84% | 89.19 TiB | 0.00%
f02233608 | Chengdu, Sichuan, CNCHINA UNICOM China169 Backbone | 47.00 TiB | 9.93% | 47.00 TiB | 0.00%
**f02362189** | Hong Kong, Central and Western, HKHK Cable TV Ltd | 90.00 TiB | 19.02% | 90.00 TiB | 0.00%
**f02196792** | Hong Kong, Central and Western, HKHK Cable TV Ltd | 89.94 TiB | 19.00% | 89.94 TiB | 0.00%

@AN-Toby - you are storing with two SP entities. Need a minimum of 5. Closing this until you provide more details on SP partners, entity names and locations.

**Comment by raghavrmadya** [comment]
Flagged for DC removal based on non-compliance with Fil+ guidelines
