### ISSUE TITLE
[DataCap Application]  Provide comprehensive solution for visualization of soccer fields - GoalV

### ISSUE THREAD

**Issue by twosson** [filecoin-project/filecoin-plus-large-datasets#2058]
### Data Owner Name

GoalV

### What is your role related to the dataset

Dataset Owner

### Data Owner Country/Region

China

### Data Owner Industry

Information, Media & Telecommunications

### Website

https://www.goalv.cn

### Social Media

```text
WeChat public account: 够威体育
```

### Total amount of DataCap being requested

15PiB

### Expected size of single dataset (one copy)

2

### Number of replicas to store

8

### Weekly allocation of DataCap requested

1PiB

### On-chain address for first allocation

f1tn3mq5y6ijaw6drzhtd46g7oeepc6how54s4s6i

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Let every game can be rewatched, so that every wonderful goal is recorded completely and from multiple angles. Let everyone share their wonderful moments with others conveniently and quickly!
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
Storing Sports Videos
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### How do you plan to prepare the dataset

IPFS, lotus

### Please share a sample of the data

```text
https://www.goalv.cn/video/GoalV-Panoramic-View_1.mp4
https://www.goalv.cn/video/Broadcast-Feed.mp4
https://www.goalv.cn/video/Players-data-collection.mp4
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Weekly

### For how long do you plan to keep this dataset stored on Filecoin

2 to 3 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, Europe

### How will you be distributing your data to storage providers

HTTP or FTP server, Shipping hard drives

### How do you plan to choose storage providers

Slack, Big Data Exchange, Partners

### How do you plan to make deals to your storage providers

Boost client, Lotus client, Singularity

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
Please provide more data samples to prove that you have 2PB data already.
Could you send an email to filplus-app-review@fil.org with your official domain in order to confirm your identity? Email name should includes the issue id #2058.
Please share more detailed information about sps you will cooperate with.

**Comment by Sunnyiscoming** [comment]
Any update here?

**Comment by twosson** [comment]
data samples: https://drive.google.com/drive/folders/1kivkHo5x4Ms74HfGdmmiVUsO2iG5Ogxq?usp=drive_link

**Comment by twosson** [comment]
Hi @Sunnyiscoming , hope you have a good day!
In previous application (link to #1562), we strictly adhered to the fil+ rules. We still have more data to store, and we will continue to cooperate with SP who have cooperated with us before and abide by the rules. We hope to obtain your approval. thank you！

**Comment by Sunnyiscoming** [comment]
No email received.  
Could you send an email to [filplus-app-review@fil.org](mailto:filplus-app-review@fil.org) with your official domain in order to confirm your identity? Email name should includes the issue id https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/2058.
Many of the data samples you provided are surveillance video. Where is the source of the video. Is it authorized to be stored as public data?

**Comment by twosson** [comment]
Sorry, there was a little problem with the mailbox, and we are fixing it. We will send mail asap.
The video data comes from our offline sports venues and cooperative venues. Through the use of mature AI technology, it outputs professional football TV live broadcast images from multiple angles. These are video data that can be stored publicly

**Comment by twosson** [comment]
![2261688545576_ pic](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/62056343/16166d7f-b6fb-4436-bcaa-6e2ad1f42b2b)

**Comment by twosson** [comment]
![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/62056343/0ae8d265-bf6c-4167-a5d4-5bfeda9831a3)

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 15PiB

**Expected weekly DataCap usage rate**
> 1PiB

**Client address**
>f1tn3mq5y6ijaw6drzhtd46g7oeepc6how54s4s6i

**Comment by 1ane-1** [comment]
I checked the #1562 retrieval success rate, and it looks good for the past performance. So i will support this round, but i will keep looking at your performance.

**Comment by 1ane-1** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebdc3aygrfdaeeleuaunh336532vpvnhwdbtbxbtaujrh7dvfxzua 
#### Address 
> f1tn3mq5y6ijaw6drzhtd46g7oeepc6how54s4s6i
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f1mdk7s2vntzm6hu35yuo6vjubtrpfnb2awhgvrri
#### Id
> 4a6af442-c936-4c69-b57a-74c75915cdea
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebdc3aygrfdaeeleuaunh336532vpvnhwdbtbxbtaujrh7dvfxzua

**Comment by Tom-OriginStorage** [comment]
1652 packaging report is relatively healthy and willing to support

**Comment by Tom-OriginStorage** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebw3zovirnkrfty5ajwmc34svysvphnbxaireu7lojb3cztrkexry 
#### Address 
> f1tn3mq5y6ijaw6drzhtd46g7oeepc6how54s4s6i
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f1q6bpjlqia6iemqbrdaxr2uehrhpvoju3qh4lpga
#### Id
> 4a6af442-c936-4c69-b57a-74c75915cdea
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebw3zovirnkrfty5ajwmc34svysvphnbxaireu7lojb3cztrkexry

**Comment by amiable169** [comment]
checker:manualTrigger

**Comment by amiable169** [comment]
checker:manualTrigger

**Comment by twosson** [comment]
@fabriziogianni7 @Sunnyiscoming Hi, it seems like something went wrong... Please help me to keep the process going

**Comment by herrehesse** [comment]
@cryptowhizzard,

Could you please conduct thorough retrieval testing on this application? Storing "soccer videos" does not appear to be an appropriate use of community datacap. 

It is essential to ensure that data storage requests align with the intended purpose and then comment on the value added to our ecosystem.

**Comment by twosson** [comment]
@herrehesse Does that mean I can't use filecoin to store my data?

**Comment by woshidama323** [comment]
So, @herrehesse   Are you from the FIL+ government team? 
As this application has been verified by @galen-mcandrew  and @Sunnyiscoming, they've agreed with all the details of this application
Why are we still discussing if "soccer videos" is good or not?

**Comment by cryptowhizzard** [comment]
I downloaded some of the data , it is up for review here:

http://www.datasetcreators.com/downloadedcarfiles/bafybeigf5vkolwt7xtsp3gxnk7rgptwspq6tf3bz3qqxkkniaiptbnicfa/

To me this looks like very heavy inflated mp4 files to be as large as possible.
Secondly i was supposed to look at soccer , not snooker.

This is soccer :
<img width="639" alt="Scherm­afbeelding 2023-07-17 om 11 28 00" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/36404435/d8290207-354f-4d48-9ab1-0fe9bacb3cb7">

I do agree with Hidde here that this data does not belong in the quality phase of Fil+ because of the inflation. It only makes retrieval slow if someone wants to watch these games and is probably done on purpose to get the maximum datacap.

**Comment by cryptowhizzard** [comment]
> So, @herrehesse Are you from the FIL+ government team? As this application has been verified by @galen-mcandrew and @Sunnyiscoming, they've agreed with all the details of this application Why are we still discussing if "soccer videos" is good or not?

Please consider your tone of voice. @herrehesse mention's that the data is not valuable to the network because the quality is not good. There are good reasons for that. If we want to make Filecoin succeed then storing / onboarding data of high quality is mandatory.

**Comment by twosson** [comment]
@herrehesse @cryptowhizzard I just have one question, is it that I can't store data in filecoin? I can't participate in filecoin, right?

**Comment by twosson** [comment]
> > @herrehesse @cryptowhizzard I just have one question, is it that I can't store data in filecoin? I can't participate in filecoin, right?
> 
> I already answered you on slack but i will do it again here.
> 
> In short, your data is inflated to the maximum. One minute of mp4 stored as 8 GB. This is not in the spirit of this network and in the spirit of storing / onboarding quality data. The only purpose of this is getting datacap because downloading / watching will be near impossible for future clients. Secondly, you have been storing snooker video's , not soccer.
> 
> Look, if you were not inflating your data I ( and others ) would have been happy to sign off on your application. If you do this kind of things you can expect getting in trouble somewhere down the line.

Sorry? I didn't speak on slack.

**Comment by twosson** [comment]
Regarding the issue of data size, video data contains the validation data we need, which affects the size, clarity, and format of the video data. I don't know, or rather, I don't think that the validation data cannot be stored. (If it really can't, I will improve it.) 

In addition, we always strictly adhere to the rules of FIL+, including the number of copies, data distribution, and support for retrieval. The value of the data itself should not be a topic of community discussion. This is a false proposition.

**Comment by twosson** [comment]
@fabriziogianni7 @Sunnyiscoming Hi, it seems like something went wrong... Please help me to keep the process going.

**Comment by twosson** [comment]
@fabriziogianni7 @Sunnyiscoming Hi, it seems like something went wrong... Please help me to keep the process going.

**Comment by Sunnyiscoming** [comment]
What is the problem?

**Comment by cryptowhizzard** [comment]
@Sunnyiscoming 

This -> https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/2058#issuecomment-1641760236

**Comment by twosson** [comment]
> What is the problem?

Did triggering the next round of signing happen?

**Comment by cryptowhizzard** [comment]
Extra info:

http://datasetcreators.com/downloadedcarfiles/2058-f02239804-f02227726-45670196-baga6ea4seaqmvafkbvt66ainy4ovnn4ub6z4i2h4fqdky2iqg6fevrgzxjocimi/

http://datasetcreators.com/downloadedcarfiles/2058-f02239804-f02227726-45670196-baga6ea4seaqmvafkbvt66ainy4ovnn4ub6z4i2h4fqdky2iqg6fevrgzxjocimi/697137213535278211226971372135352782112.mp4

This ain't the data the applicant stated he would store.

**Comment by raghavrmadya** [comment]
Flagged for DC Removal based on dispute in the tracker
