### ISSUE TITLE
[DataCap Application] <Shenzhen Xinghongweiye Technology Co., LTD> -<Anime>

### ISSUE THREAD

**Issue by c12xf** [filecoin-project/filecoin-plus-large-datasets#2059]
### Data Owner Name

Shenzhen Xinghongweiye Technology Co., LTD

### What is your role related to the dataset

Dataset Owner

### Data Owner Country/Region

China

### Data Owner Industry

Information, Media & Telecommunications

### Website

http://www.xinghongwy.com/

### Social Media

```text
http://www.xinghongwy.com/
```

### Total amount of DataCap being requested

15PiB

### Expected size of single dataset (one copy)

2P

### Number of replicas to store

8

### Weekly allocation of DataCap requested

1PiB

### On-chain address for first allocation

f1bgqhc5hfbs43cqptr55ajg7kas3enehlms6r6ka

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Shenzhen Xinghongweiye Technology  CO., LTD. was established in 2005 with a registered capital of 10 million, which is a wholly-owned subsidiary of HONG KONG SKY TALENT HOLDINGS LIMITED, and its own brand is "Xinghongweiye".

Mainly engaged in cloud storage, application storage (NAS, IP-SAN), server virtualization, HPC, GPU high-performance computing, intelligent medical and other overall solutions. Products are widely used in security, education, government, radio and television, communications, Internet and other industries, based on the server field cooperation planning, and different industry manufacturers to establish long-term partnerships, to promote the formation and development of Xinghong full series of product application industry chain.

With the development of the network era and the increasing demand for data storage, we have launched ultra-large-capacity massive information storage and management solutions, customized corresponding solutions according to the characteristics and needs of different industries, broken through the single fixed mode of traditional storage solutions, and fully exerted the advantages of combining hardware and software research and development.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
Tutorial on anime design, images, videos, and some rendered data.
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### How do you plan to prepare the dataset

singularity

### Please share a sample of the data

```text
https://pan.baidu.com/s/1anxOUaF2FsN4lDlZEZM1TA?pwd=1234 
pwd：1234
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Monthly

### For how long do you plan to keep this dataset stored on Filecoin

More than 3 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, South America

### How will you be distributing your data to storage providers

HTTP or FTP server, Shipping hard drives

### How do you plan to choose storage providers

Slack

### How do you plan to make deals to your storage providers

Boost client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by c12xf** [comment]
Email sent.
Most of these data come from the rendering data and finished products of our company's animation design department and animation rendering cluster.
We are currently collaborating with the following five SPs, and other SPs will join in the future：
f02062851
f01836766
f01938671
f01859603
f02215422

**Comment by c12xf** [comment]
Email sent.
Most of these data come from the rendering data and finished products of our company's animation design department and animation rendering cluster.
We are currently collaborating with the following five SPs, and other SPs will join in the future：
f02062851
f01836766
f01938671
f01859603
f02215422

**Comment by Sunnyiscoming** [comment]
Received that.
Your company's main business is storage, please provide more information to prove that you have 2PB tutorial on anime design, images, videos, and some rendered data.

**Comment by Holiday507** [comment]
@Sunnyiscoming If you have any information about this company, I hope you can share it with me, so that I can provide signing services for it in the future.

**Comment by fsector-1** [comment]
> Received that. Your company's main business is storage, please provide more information to prove that you have 2PB tutorial on anime design, images, videos, and some rendered data.

Our company has arranged for other outsourced studios to complete this project together, including using our designed architecture for rendering and other related tasks. [This link](http://www.xinghongwy.com/detail.aspx?cid=232&siteid=27546) is our industry solution for anime production.

From the monitoring data in the background, it can be seen that there is currently 3Pb of data in the server of the rendering group, but not all data is valuable. We checked a while ago and found that only about 2Pb of data is valuable, so we plan to upload it to the filecoin.
![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/86875295/c13d7eeb-2ae6-4138-a143-e43c4247a747)

**Comment by c12xf** [comment]
> Received that. Your company's main business is storage, please provide more information to prove that you have 2PB tutorial on anime design, images, videos, and some rendered data.

Our company has arranged for other outsourced studios to complete this project together, including using our designed architecture to verify its feasibility. [This link](http://www.xinghongwy.com/detail.aspx?cid=232&siteid=27546) is a brief introduction to an industry solution for animation design by our company.

From the monitoring data in the background, it can be seen that there is currently 3Pb of data in the server of the rendering group, but not all data is valuable. We checked a while ago and found that only about 2Pb of data is valuable, so we plan to upload it to the filecoin.
![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/132553355/98b32fcd-b6c1-43a8-a213-413e4e4bf8c5)

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 15PiB

**Expected weekly DataCap usage rate**
> 1PiB

**Client address**
>f1bgqhc5hfbs43cqptr55ajg7kas3enehlms6r6ka

**Comment by Holiday507** [comment]
I am willing to give support once, and then I will pay attention to the storage situation.

**Comment by Holiday507** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecznawv2txepgknkt5h3kafwhc2b3dog2tenq5iu5k7nrwm2hv5ne 
#### Address 
> f1bgqhc5hfbs43cqptr55ajg7kas3enehlms6r6ka
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f1sa3dp3a7fwirrsxjdthvzneo7rnjcrrfllsnjpq
#### Id
> 0cb96391-a113-4a2a-9256-e655644c1ff4
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecznawv2txepgknkt5h3kafwhc2b3dog2tenq5iu5k7nrwm2hv5ne

**Comment by raghavrmadya** [comment]
It is unclear to me how you have 15 PiBs of data. This application is being audited by T&T WG. Do you have a history of storing data on Filecoin? As pointed out, can you show proof of your animation business because your website does not have anything related to it

**Comment by raghavrmadya** [comment]
Notaries are requested to not approve until client provides sufficient evidence

**Comment by c12xf** [comment]
> It is unclear to me how you have 15 PiBs of data. This application is being audited by T&T WG. Do you have a history of storing data on Filecoin? As pointed out, can you show proof of your animation business because your website does not have anything related to it

https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/2059#issuecomment-1600522760
Please review historical replies.
Additionally, I have a history of storing data in filecoin, such as #1976 and #1989, and I am currently storing them

**Comment by c12xf** [comment]
@raghavrmadya Do you have any other questions？
