### ISSUE TITLE
[DataCap Application] <Beijing Hatd Academy of Traditional Chinese Medicine> - <Web3 Healthy classroom>

### ISSUE THREAD

**Issue by licornduan** [filecoin-project/filecoin-plus-large-datasets#2061]
### Data Owner Name

Beijing Hatd Academy of Traditional Chinese Medicine

### What is your role related to the dataset

Storage provider filling out application on behalf of the data owner

### Data Owner Country/Region

China

### Data Owner Industry

Life Science / Healthcare

### Website

http://www.beijingfude.com/

### Social Media

```text
Beijing Hatde Academy of Traditional Chinese Medicine was officially established in 2016 and is located in Beijing. The institute is committed to training more professionals with professional health care skills to serve the society, so that they can apply what they have learned. It has built a one-stop technical training service system to provide them with more business and employment opportunities. Mr. Zhang Qiao, the director of the research Institute, has developed a series of pure manipulation of health conditioning technology over the years, and trained a large number of professional health conditioning technology talents, which spread throughout the country in large, medium and small cities and regions, helping hundreds of thousands of people to relieve physical and mental pain every year.
```

### Total amount of DataCap being requested

500TiB

### Expected size of single dataset (one copy)

200

### Number of replicas to store

1

### Weekly allocation of DataCap requested

50TiB

### On-chain address for first allocation

f15gbqratmjmfoo5czanhwoe43f66gkuoshowt3xq

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Beijing Hatde Academy of Traditional Chinese Medicine was officially established in 2016 and is located in Beijing. The institute is committed to training more professionals with professional health care skills to serve the society, so that they can apply what they have learned. It has built a one-stop technical training service system to provide them with more business and employment opportunities. Mr. Zhang Qiao, the director of the research Institute, has developed a series of pure manipulation of health conditioning technology over the years, and trained a large number of professional health conditioning technology talents, which spread throughout the country in large, medium and small cities and regions, helping hundreds of thousands of people to relieve physical and mental pain every year.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
bafykbzacediffodt6kwrxzwaj5oy5nou46hj6k5a65m7wzg4jpvvqnt52zjcm
bafykbzaceagzzloxpytf7eas7dj4muj5sp4io3b2juvw25g3p2cdejdnak644
bafykbzaceaf647ol4muhvq4sgrqkvji46nrmef5rmqdqvqxmibgxicg6pyewi
bafykbzacecrydujskay4lenkuiyvlgukyjq4jpo4mgwnwz6ckuevi7t6s2rwe
bafykbzaceazgw6xbiq7lagjrmy5nwchjbvb5firrh2eclbfm6gvfva5qit6o4
bafykbzaceaxr42tlgiai77kogu7ucooibfm4a4vf6tjvgfycssjdazyaguzgc


All mp4 format
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### How do you plan to prepare the dataset

lotus

### Please share a sample of the data

```text
https://drive.google.com/drive/folders/1hZLHW7gGHRNVbcoNr4TxJjaQ4Zu1T1UB?usp=sharing
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Weekly

### For how long do you plan to keep this dataset stored on Filecoin

More than 3 years

### In which geographies do you plan on making storage deals

Greater China

### How will you be distributing your data to storage providers

Shipping hard drives

### How do you plan to choose storage providers

Partners

### How do you plan to make deals to your storage providers

Boost client, Lotus client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by licornduan** [comment]
#1794 

In the previous application, due to the reasons of both parties, the quota was used improperly, and the data was dispersed to 5 nodes, which did not meet the norms and occupied public resources, resulting in the notary being unable to renew the subsequent quota. Please understand.

**Comment by Sunnyiscoming** [comment]
I think you should communicate with the notaries about solutions, rather than open a new application.

**Comment by licornduan** [comment]
The amount is small. No one wants to help me with this project.

**Comment by Sunnyiscoming** [comment]
Please explain why there are duplicates between your dataset and other datasets, and cooperation with same sps, all of which indicate a high likelihood of fraud.
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/114
https://github.com/data-preservation-programs/filplus-checker-assets/blob/main/filecoin-project/filecoin-plus-large-datasets/issues/1794/1685324009827.md
<html>
<body>


Provider | Location | Total Deals Sealed | Percentage | Unique Data | Duplicate Deals
-- | -- | -- | -- | -- | --
f01690631new | UnknownUnknown | 26.63 TiB | 24.60% | 26.63 TiB | 0.00%
f01660052new | UnknownUnknown | 20.75 TiB | 19.17% | 20.75 TiB | 0.00%
f01136592new | UnknownUnknown | 16.38 TiB | 15.13% | 15.63 TiB | 4.58%
f01654478 | UnknownUnknown | 13.78 TiB | 12.73% | 13.78 TiB | 0.00%
f01654220 | UnknownUnknown | 11.53 TiB | 10.66% | 11.53 TiB | 0.00%

https://github.com/data-preservation-programs/filplus-checker-assets/blob/main/filecoin-project/filecoin-plus-large-datasets/issues/1794/1686304529345.md
f0509062 do not support data retrieval.

**Comment by licornduan** [comment]
@Sunnyiscoming 

Q：Please explain why there are duplicates between your dataset and other datasets, and cooperation with same sps, all of which indicate a high likelihood of fraud.

A：The client has many students, including overseas ones, and videos and pictures are also shared by students. It is impossible to confirm that the CID of that picture has duplication with other nodes, and the duplicate data shared by CID is only 2MB. The other data is the test case data used by my test node, for the purpose of sharing data to pass the review.

Do we provide tools to detect CID? Repeated eliminations are found to avoid the occurrence of non-compliance due to very small data.

Q：f0509062 do not support data retrieval.
A：The declared public address of the node is accessible

**Comment by Sunnyiscoming** [comment]
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1794#issuecomment-1609687340
Please close this issue and continue #1794 .
I will introduce your application in the slack channel. You can communicate with notaries in the slack channel.

**Comment by licornduan** [comment]
@Sunnyiscoming 

Thank you for your support
