### ISSUE TITLE
[DataCap Application] Limradar [company data]

### ISSUE THREAD

**Issue by Pauline546** [filecoin-project/filecoin-plus-large-datasets#2063]
### Data Owner Name

Shanghai Limradar Electronic Technology Co., Ltd

### What is your role related to the dataset

Dataset Owner

### Data Owner Country/Region

China

### Data Owner Industry

Information, Media & Telecommunications

### Website

https://www.limradar.com/

### Social Media

```text
Wechat: Limingruida
```

### Total amount of DataCap being requested

15PiB

### Expected size of single dataset (one copy)

1.43PiB

### Number of replicas to store

10

### Weekly allocation of DataCap requested

1PiB

### On-chain address for first allocation

f1kaeoskx4m4tgv3pjytdigmscklhv44behc3ky6i

### Data Type of Application

Private Commercial/Enterprise

### Custom multisig
- [x] Use Custom Multisig

### Identifier
efil

### Share a brief history of your project and organization

```text
Shanghai Limradar was established in 2020. Our company focuses on radar detection, multi-sensor fusion, artificial intelligence traffic control and other technology research in the field of transportation, and provides relevant millimeter wave radar products around intelligent transportation, intelligent security, advanced assisted driving, rail safety and other applications.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
The data we store are radar test records used in various fields. Our company's product---Radar can be applied in several scenarios, including Smart Traffic, Smart Security, Advanced Driving Assistance, Track and traffic safety, etc. We have a large accumulation of data. The data we own is both public and private.
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### How do you plan to prepare the dataset

lotus

### Please share a sample of the data

```text
Our data for this application is private, so we can not show the sample.
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [ ] I confirm

### If you chose not to confirm, what was the reason

```text
Our data for this application is private, so we can not show the sample.
```

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

2 to 3 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America

### How will you be distributing your data to storage providers

HTTP or FTP server, Shipping hard drives

### How do you plan to choose storage providers

Slack

### If you already have a list of storage providers to work with, fill out their names and provider IDs below

```text
We've already provided it in the E-Fil+ registration.
```

### How do you plan to make deals to your storage providers

Boost client, Lotus client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by 1ane-1** [comment]
Can you show me your miner and the enough data that you stored?

**Comment by Pauline546** [comment]
Hello @1ane-1 , I can DM you these information.

**Comment by kevzak** [comment]
Hello @Pauline546 - we have a new process as part of E-FIl+. 

Can you go to Filplus.storage , login with your GitHub information and then click on Get Verified Link and submit a KYC check?

**Comment by raghavrmadya** [comment]
It is unclear to me how you have 15 PiBs of data. This application is being audited by T&T WG. Do you have a history of storing data on Filecoin?

**Comment by data-programs** [comment]
<img width="32" alt="KYC" Verified src="https://stable.filplus.storage/images/filplus-kyc-verified-badge.png"/>

This user’s identity has has been verified through [filplus.storage](https://filplus.storage)

**Comment by Pauline546** [comment]
Hi @kevzak , we have already completed the KYC check.

Hi @raghavrmadya , the amount of our company's data is 1.43PiB. We want to store 10 copies of our data via distributed storage, so we applied 15PiB datacap for it. We haven't store any data on Filecoin yet.

Thank you and if you need more information, please contact with me!

**Comment by kevzak** [comment]
Hi @Pauline546 thank you for completing KYC and explaining your Data storage plan. 

We are still awaiting completion of KYB business check. Let me know when it is complete. Thank you.

**Comment by data-programs** [comment]
<img width="32" alt="KYC" Verified src="https://stable.filplus.storage/images/filplus-kyc-verified-badge.png"/>

This user’s identity has been verified through [filplus.storage](https://filplus.storage)

**Comment by Pauline546** [comment]
I want to keep it open.

**Comment by Pauline546** [comment]
I want to keep it open.

**Comment by kevzak** [comment]
KYB check complete? @Pauline546

**Comment by Sunnyiscoming** [comment]
Any update here?

**Comment by Sunnyiscoming** [comment]
Close for no reply.
