### ISSUE TITLE
[DataCap Application] TEST

### ISSUE THREAD

**Issue by kevzak** [filecoin-project/filecoin-plus-large-datasets#2065]
### Data Owner Name
TEST

### What is your role related to the dataset
Other

### Data Owner Country/Region
United States

### Data Owner Industry
Other

### Website
[https://protocol.ai/](https://protocol.ai/)

### Social Media
TEST KZ (na)

### Total amount of DataCap being requested
10 PiB

### Expected size of single dataset (one copy)
1 TiB

### Number of replicas to store
5

### Weekly allocation of DataCap requested
100 TiB

### On-chain address for first allocation
f1i2reokfclrqls5mkgtbqk5esvj6it7nykv8d68z

### Data Type of Application
Private Commercial/Enterprise

### Custom multisig
No

### Share a brief history of your project and organization
test

### Is this project associated with other projects/ecosystem stakeholders?
No

### If answered yes, what are the other projects/ecosystem stakeholders
n/a

### Describe the data being stored onto Filecoin
test kyc

### Where was the data currently stored in this dataset sourced from
Google Cloud

### If you answered "Other" in the previous question, enter the details here
n/a

### How do you plan to prepare the dataset
IPFS

### If you answered "other/custom tool" in the previous question, enter the details here
n/a

### Please share a sample of the data
test

### Confirm that this is a public dataset that can be retrieved by anyone on the Network
No

### If you chose not to confirm, what was the reason
test

### What is the expected retrieval frequency for this data
Weekly

### For how long do you plan to keep this dataset stored on Filecoin
1 to 1.5 years

### In which geographies do you plan on making storage deals
North America, South America

### How will you be distributing your data to storage providers
I don't know yet

### How do you plan to choose SP
Other

### If you answered "Others" in the previous question, what is the tool or platform you plan to use
n/a

### If you already have a list of storage providers to work with, fill out their names and provider IDs below
n/a

### How do you plan to make deals to your storage providers
None

### If you answered "Others/custom tool" in the previous question, enter the details here
n/a

### Can you confirm that you will follow the Fil+ guideline
Yes

_Application created via [filplus.storage](https://filplus.storage)_

**Comment by data-programs** [comment]
This application requests a total of 6 PiB, so it’s labeled `very large application`

**Comment by data-programs** [comment]
<img width="32" alt="KYC" Verified src="https://stable.filplus.storage/images/filplus-kyc-verified-badge.png"/>

This user’s identity has been verified through [filplus.storage](https://filplus.storage)
