### ISSUE TITLE
[DataCap Application] Wanshen Information Technology

### ISSUE THREAD

**Issue by lyjmry** [filecoin-project/filecoin-plus-large-datasets#2068]
### Data Owner Name
Wanshen Information Technology

### What is your role related to the dataset
Dataset Owner

### Data Owner Country/Region
China

### Data Owner Industry
IT & Technology Services

### Website
[ http://www.onestech.cn]( http://www.onestech.cn)

### Social Media
NA (NA)

### Total amount of DataCap being requested
15 PiB

### Expected size of single dataset (one copy)
2 PiB

### Number of replicas to store
8

### Weekly allocation of DataCap requested
1 PiB

### On-chain address for first allocation
f153myodwhfb22vvmniegfakmsqeyzpel7efcyyxq

### Data Type of Application
Public, Open Commercial/Enterprise

### Custom multisig
No

### Share a brief history of your project and organization
Involving cloud computing, UC converged communication, information security and other fields, the business field covers IT product services, system integration services, disaster recovery backup solutions and other IT service businesses.

### Is this project associated with other projects/ecosystem stakeholders?
No

### If answered yes, what are the other projects/ecosystem stakeholders
n/a

### Describe the data being stored onto Filecoin
Public surveillance video, etc.

### Where was the data currently stored in this dataset sourced from
My own storage infra

### If you answered "Other" in the previous question, enter the details here
n/a

### How do you plan to prepare the dataset
lotus

### If you answered "other/custom tool" in the previous question, enter the details here
n/a

### Please share a sample of the data
https://drive.google.com/drive/folders/1UrslnmvANoCeM9hIjetZtzZojbgt7qpI

### Confirm that this is a public dataset that can be retrieved by anyone on the Network
Yes

### If you chose not to confirm, what was the reason
n/a

### What is the expected retrieval frequency for this data
Sporadic

### For how long do you plan to keep this dataset stored on Filecoin
Permanently

### In which geographies do you plan on making storage deals
Asia other than Greater China, Greater China

### How will you be distributing your data to storage providers
Shipping hard drives

### How do you plan to choose SP
Partners

### If you answered "Others" in the previous question, what is the tool or platform you plan to use
n/a

### If you already have a list of storage providers to work with, fill out their names and provider IDs below
f02028138
f02027847
f02024863
f02072241
f02061213
f01941622

### How do you plan to make deals to your storage providers
Boost client

### If you answered "Others/custom tool" in the previous question, enter the details here
n/a

### Can you confirm that you will follow the Fil+ guideline
Yes

_Application created via [filplus.storage](https://filplus.storage)_

**Comment by data-programs** [comment]
This application requests a total of 15 PiB, so it’s labeled `very large application`

**Comment by Sunnyiscoming** [comment]
What is your role at the company that is behind this project?
How are you connected to the data set? The website isn't yours. Do you work for the listed organization?
How are you finding SPs. List a detailed plan.

**Comment by lyjmry** [comment]
I am also one of the SPs, near the company. The person in charge of the company approached me, they need a lot of data backup needs. We went directly to their company to communicate with them on relevant matters until their data backup requirements were successfully completed. I have a good resource community in the Miner community in Greater China, and it is not too difficult for me to contact these SPs. The allocation plan will be determined according to the relevant rules of Filplus and the packaging capacity of each SP. It is not ruled out that more SPs will be brought in until the project is successfully completed.

**Comment by lyjmry** [comment]
I am also one of the SPs, near the company. The person in charge of the company approached me, they need a lot of data backup needs. As far as I know, they have a very large amount of surveillance video data, but many surveillance videos are relatively old, but they are not willing to clean them up in case they cannot be obtained under special circumstances. They want to do cold backups on filecoin, to be retrieved when needed. We went directly to their company to communicate with them on relevant matters until their data backup requirements were successfully completed. I have a good resource community in the Miner community in Greater China, and it is not too difficult for me to contact these SPs. The allocation plan will be determined according to the relevant rules of Filplus and the packaging capabilities of each SP. It is not ruled out that more SPs will be brought in until the project is successfully completed.

**Comment by cryptowhizzard** [comment]
Hi,

This application is storing private data of a company ( Surveillance data ). This application should therefore go to Fil-E as it is not a public / scientific dataset and should probably encrypted for privacy reasons.

P.s.

f02061213 and f01941622 are involved storing data from data preparers who have not followed on the FIL+ rules and guidelines. I recommend you remove them from your list.

**Comment by lyjmry** [comment]
@cryptowhizzard Hello friend! Please check the data sample, it is not very privacy-related, and the data subject agrees to disclose it. For the above two SPs, I will verify all the cooperative SPs again before sending the order. Thank you for your attention and suggestions.

**Comment by cryptowhizzard** [comment]
> @cryptowhizzard Hello friend! Please check the data sample, it is not very privacy-related, and the data subject agrees to disclose it. For the above two SPs, I will verify all the cooperative SPs again before sending the order. Thank you for your attention and suggestions.

Hi,

I still believe it should go to Fil-E. It is not a public / scientific dataset.

**Comment by lyjmry** [comment]
NO NO NO! We insist that it is not Fil+E, and we don't need encryption, anyone who wants to retrieve it can retrieve it.

**Comment by lyjmry** [comment]
> > @cryptowhizzard Hello friend! Please check the data sample, it is not very privacy-related, and the data subject agrees to disclose it. For the above two SPs, I will verify all the cooperative SPs again before sending the order. Thank you for your attention and suggestions.
> 
> Hi,
> 
> I still believe it should go to Fil-E. It is not a public / scientific dataset.

It is up to the data owner whether to use fil+E

**Comment by Sunnyiscoming** [comment]
Total amount of DataCap being requested≠Expected size of single dataset (one copy)*Number of replicas to store
15 PiB≠1 GiB*8

How many videos do you have at present? Can you provide more information to prove that?

**Comment by lyjmry** [comment]
> Total amount of DataCap being requested≠Expected size of single dataset (one copy) * Number of replicas to store 15 PiB≠1 GiB * 8
> 
> How many videos do you have at present? Can you provide more information to prove that?

![b2ed037af35ff305c6f0509481727b2](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/45060067/6c630ca1-19de-4cf5-b369-2509ca59f4ed)

**Comment by Sunnyiscoming** [comment]
Please provide more related information.

**Comment by lyjmry** [comment]
![e25f18f68f082809b3e7ae1d95815a4](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/45060067/cc9a2b23-0842-490d-b467-ca2ffce271dd)

Each of the folders replied above contains a lot of video files

If you want me to provide other information, please specify Thank you

> Please provide more related information.

**Comment by Sunnyiscoming** [comment]
Total amount of DataCap being requested＝Expected size of single dataset (one copy) * Number of replicas to store Please adjust the amount of expected size of single dataset (one copy) .

**Comment by lyjmry** [comment]
> The total amount of requested DataCap = the expected size of a single data set (one copy) * the number of copies to be stored Please adjust the expected size of a single data set (one copy).

Sorry, I made a mistake when I filled in the information. The data volume should be about 2PiB. I filled it in as 1GiB.

**Comment by lyjmry** [comment]
I have changed the information again

**Comment by lyjmry** [comment]
@Sunnyiscoming  Hi What other information do I need to provide?

**Comment by Sunnyiscoming** [comment]
Best practice for storing large datasets includes ideally, storing it in 3 or more regions, with 4 or more storage provider operators or owners.
You should list Miner ID, Business Entity, Location of sps you will cooperate with.

**Comment by lyjmry** [comment]
f02199243 Penang, Malaysia (individual)

f02191296 Hong Kong, China
f02028138 Thailand (Doudo beans)

f02237295 Shenzhen, Guangdong, China (individual)

f02027952 Nebra Cloud Technology Co., LTDEngland/London

f01811024 Rock Cloud Technology Co., LTD China/HongKong

f02028326 Chengxin Technology Co., Ltd. America/Atlanta

**Comment by cryptowhizzard** [comment]
> Hi @Sunnyiscoming
> 
> f02199243 Penang, Malaysia (individual)
> 
> f02191296 Hong Kong, China f02028138 Thailand (Doudo beans)
> 
> f02237295 Shenzhen, Guangdong, China (individual)
> 
> f02027952 Nebra Cloud Technology Co., LTDEngland/London
> 
> f01811024 Rock Cloud Technology Co., LTD China/HongKong
> 
> f02028326 Chengxin Technology Co., Ltd. America/Atlanta

Are these identities really present at the given location or is it just VPN backhauled to China?

**Comment by lyjmry** [comment]
> > Hi @Sunnyiscoming
> > f02199243 Penang, Malaysia (individual)
> > f02191296 Hong Kong, China f02028138 Thailand (Doudo beans)
> > f02237295 Shenzhen, Guangdong, China (individual)
> > f02027952 Nebra Cloud Technology Co., LTDEngland/London
> > f01811024 Rock Cloud Technology Co., LTD China/HongKong
> > f02028326 Chengxin Technology Co., Ltd. America/Atlanta
> 
> Are these identities really present at the given location or is it just VPN backhauled to China?
This is very simple for you, maybe you can verify it for me

**Comment by lyjmry** [comment]
Just kidding, I also confirmed the location of their computer room.

**Comment by cryptowhizzard** [comment]
> Just kidding, I also confirmed the location of their computer room.

There are LDN participants in trouble b/c some SP’s claim to be where they are not. My job is to guide you and help your LDN to make it a succes. 

If you need guidance or help, let us know.

**Comment by lyjmry** [comment]
> > Just kidding, I also confirmed the location of their computer room.
> 
> There are LDN participants in trouble b/c some SP’s claim to be where they are not. My job is to guide you and help your LDN to make it a succes.
> 
> If you need guidance or help, let us know.

no problem! ! We will abide by the Fil+ rules.

**Comment by lyjmry** [comment]
> * Have you prepared enough token for sector pledge?
> * Are you a data preparer? What is your previous experience as a data-preparer? List previous applications and client IDs
> * How will the data be prepared? Please include tooling used and technical details
> * If you are not preparing the data, who will prepare the data?  (Name and Business)
> * Has this dataset been stored on Filecoin before? If so, why are you choosing to store it again?

Hi     1. In order to avoid suspicion, I will not participate in this SP package. But the contacted customer has already prepared the mortgage currency.
2. I have invited colleagues to provide technical guidance (Plus).
3. Data processed with singularity.

4. It has not been stored on filecoin before.

**Comment by cryptowhizzard** [comment]
> Just kidding, I also confirmed the location of their computer room.

You know, if you want to be the hero of the day, i am perfectly fine with that. 

A few small tips:

1: Put a firewall on your Boost admin panel. Accidents will happen like this and you will loose your funds. See screenshots of miners f02199243 and f02237295.
2: Store the unsealed data and have some respect for the rules.

Cheers!

<img width="1634" alt="Scherm­afbeelding 2023-07-17 om 21 56 39" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/36404435/b04927fb-a7c2-4df8-9be3-6d61835c67ab">


<img width="1635" alt="Scherm­afbeelding 2023-07-17 om 21 56 53" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/36404435/d958e887-8010-4f26-b7c8-110ea1d8f781">

**Comment by lyjmry** [comment]
What other information do I need to submit?
@Sunnyiscoming

**Comment by Sunnyiscoming** [comment]
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/2068#issuecomment-1638787477

**Comment by lyjmry** [comment]
> [#2068 (comment)](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/2068#issuecomment-1638787477)
If you notice, the ip and the address are the same place.

**Comment by Filplus-govteam** [comment]
Hello @lyjmry per the new guidelines https://github.com/filecoin-project/notary-governance/issues/922 for Open Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

This information will be reviewed by Fil+ Governance team to confirm validity toward the Fil+ guideline of a distributed storage plan and then the application will be approved for additional notary review. Let us know if you have any questions.

**Comment by lyjmry** [comment]
@Filplus-govteam I have submitted KYC, please review as soon as possible, we are already processing the data.thank you

**Comment by herrehesse** [comment]
I highly doubt that a client requesting 15PiB of "Public surveillance video, etc." is acting sensibly or for the benefit of the filecoin community. I can and will not support the continuation of this application.

**Comment by herrehesse** [comment]
![Screenshot 2023-07-24 at 13 37 21](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/70132857/216bb3df-04c9-4625-927e-d5d9ff1d9648)

This is not "human's most important information" in my honest opinion.

**Comment by lyjmry** [comment]
> ![Screenshot 2023-07-24 at 13 37 21](https://user-images.githubusercontent.com/70132857/255578171-216bb3df-04c9-4625-927e-d5d9ff1d9648.png)
> 
> This is not "human's most important information" in my honest opinion.

More than 80 people around the world, including but not limited to you. It's not important to you, but it's important to the user. That's enough. You've always been about yourself.

**Comment by cryptowhizzard** [comment]
This client is trying to blackmale me to approve his LDN.

See https://github.com/filecoin-project/notary-governance/issues/935#issuecomment-1647900007

@lyjmry just buzz off. I won't sign , PERIOD!
![Scherm­afbeelding 2023-07-24 om 15 20 24](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/36404435/33c893ab-9519-4712-acab-6cc1d31ef697)

**Comment by lyjmry** [comment]
> This client is trying to blackmale me to approve his LDN.
> 
> See [filecoin-project/notary-governance#935 (comment)](https://github.com/filecoin-project/notary-governance/issues/935#issuecomment-1647900007)
> 
> @lyjmry just buzz off. I won't sign , PERIOD! ![Scherm­afbeelding 2023-07-24 om 15 20 24](https://user-images.githubusercontent.com/36404435/255602577-33c893ab-9519-4712-acab-6cc1d31ef697.png)

That's great! You resisted the temptation.

**Comment by Sunnyiscoming** [comment]
Any update here?

**Comment by Sunnyiscoming** [comment]
Close for no reply.

**Comment by data-programs** [comment]
<img width="32" alt="KYC" Verified src="https://stable.filplus.storage/images/filplus-kyc-verified-badge.png"/>

This user’s identity has been verified through [filplus.storage](https://filplus.storage)
