### ISSUE TITLE
[DataCap Application]ZKLink

### ISSUE THREAD

**Issue by zzhh88** [filecoin-project/filecoin-plus-large-datasets#208]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: ZKLink
- Website / Social Media:Website: https://zk.link/
Twitter：https://twitter.com/zkLinkorg
Discord：https://discord.com/invite/9GCwxN7xaJ
Telegram：https://t.me/zkLinkorg
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):5 PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):100TiB
- On-chain address for first allocation:f1dmx5ge5bjcbhlmoumfhdm7l5ytb4t4f75btje6q

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
zkLink is an ultra secure, chain-to-chain interoperability protocol powered by zero-knowledge technology. As a ”connector” among diverse ecosystems, zkLink cooperates with various public chains and Layer2 protocols to provide a more convenient and secure chain-to-chain trading environment, contributing to a more accessible and efficient DeFi ecosystem for everyone. Furthermore, we are engaging in NFT marketplace. And we have built a platform for cross-chain transactions and already have nearly 100 thousands fans in social media and community. Our blog publishes news about blockchain and followers are allowed to post their content in free. We serve not only individuals, but also toB. 
```

What is the primary source of funding for this project?
```
Shareholder’s investment
```

What other projects/ecosystem stakeholders is this project associated with?
```
We are cooperate with various public chains and Layer2 protocols
```

## Use-case details

Describe the data being stored onto Filecoin
```
Blockchain news, videos and docs. Transaction data, social media information
```

Where was the data in this dataset sourced from?
```
Data from cross-chain transactions, NFT minting and marketplace. Huge amount of images, videos and docs from blog.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://docs.google.com/document/d/1Z_FhSuk6aezCuBzrmbCUxrLTYtS3oayL/edit?usp=sharing&ouid=115954675064466333198&rtpof=true&sd=true
https://docs.google.com/document/d/10GSAtQWWGa9-1kgdoEbWFvcFVMbjZjwv/edit?usp=sharing&ouid=115954675064466333198&rtpof=true&sd=true
https://drive.google.com/file/d/1v6n2O-pAJo7RlRGeCcWQlQjdeDW5k0iK/view?usp=sharing
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes, of course. 
```

What is the expected retrieval frequency for this data?
```
No exactly frequency.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
It is useful for us. So is better to store permanently.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Any acceptable regions.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Online transfer is better.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
Base on provider’s capacity, reputation and performance. 
```

How will you be distributing deals across storage providers?
```
It mainly depends on storage provider’s willing.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
We have enough funding to support this project. 
Also, Filecoin is the platform that we are looking for. maybe we can have further cooperation in the future. 
```

**Comment by galen-mcandrew** [comment]
## Multisig Notary requested
#### Total DataCap requested 
> 5PiB
#### Expected weekly DataCap usage rate 
> 100TiB

**Comment by dud1337** [comment]
No response in email or discord as of yet. I will respond if there is one.

**Comment by zzhh88** [comment]
@dud1337 hi, sorry for reply late. we have confirm it through email. plz check it. thanks a lot!

**Comment by dud1337** [comment]
Please confirm on discord as asked repeatedly.

**Comment by zzhh88** [comment]
> 

@dud1337 
hi, me again! 
could u @zkLink in discord again? i can't find you in discord now.

**Comment by dkkapur** [comment]
@zzhh88 what is your discord user name and # number? I'd like to follow up on this.

**Comment by dkkapur** [comment]
Closing this one out for inactivity. Please re-open if still relevant and answer the above questions. Thanks!

**Comment by zzhh88** [comment]
@dkkapur Hi, Deep.
How to re-open it? 
zkLink#6914  is my account. plz DM me. Thank u!

**Comment by dkkapur** [comment]
<img width="224" alt="Screen Shot 2022-06-03 at 9 11 38 AM" src="https://user-images.githubusercontent.com/2343218/171932920-b0338111-54a0-401c-874f-248677d7b342.png">

This has been pending for >3 weeks. Closing this out for now. Please respond when you are able to confirm that you are the owner / have access to the owner of this dataset.

**Comment by zzhh88** [comment]
@dkkapur Hello, I'm very sorry for not being able to reply in time due to work reasons. We have added you as a discord friend and responded. How do I open an application?

**Comment by zzhh88** [comment]
@dkkapur @dud1337 We would like to know what else should we offer?

**Comment by zzhh88** [comment]
@dkkapur @galen-mcandrew How do we open the application？

**Comment by dkkapur** [comment]
Hey @zzhh88 thanks for your patience, sorry I missed the notifications on these. Can confirm that I received messages back from zkLink#6914 and this is the account that is actively posting on the zk.Link server. 

For any notaries - I would be happy to share screen and provide evidence of this basic KYC. Some screenshots: 
![image](https://user-images.githubusercontent.com/2343218/177278285-218291f4-ce67-4cbd-87f5-4db45e0b1437.png)

![image](https://user-images.githubusercontent.com/2343218/177278331-637a0359-f81a-4ea2-9896-72f3e7bd0955.png)

**Comment by dkkapur** [comment]
@zzhh88 can you confirm that this project is still looking to get verified?

**Comment by zzhh88** [comment]
Hello, @dkkapur  Thank you very much! we confirm.

**Comment by Fenbushi-Filecoin** [comment]
Zklink is a legit blockchain project. We can support the application.

**Comment by zzhh88** [comment]
Hello, @Fenbushi-Filecoin thank you very much for your support of ZKLink!
We've waited so long, how do we move forward?
