### ISSUE TITLE
[DataCap Application] Hello Decentralized

### ISSUE THREAD

**Issue by alexanderbkl** [filecoin-project/filecoin-plus-large-datasets#2081]
### Data Owner Name
Hello Decentralized

### What is your role related to the dataset
Other

### Data Owner Country/Region
Spain

### Data Owner Industry
Web3 / Crypto

### Website
[https://joinhello.app](https://joinhello.app)

### Social Media
https://es.linkedin.com/company/hellostorage (Linkedin)

### Total amount of DataCap being requested
10 PiB

### Expected size of single dataset (one copy)
100 GiB

### Number of replicas to store
4

### Weekly allocation of DataCap requested
200 TiB

### On-chain address for first allocation
f15r52r73xyl6bgvds55oibbeacm3qv2ve2ofr23a

### Data Type of Application
Private Commercial/Enterprise

### Custom multisig
No

### Share a brief history of your project and organization
Hello Drive is a small startup that has a prototype and got pre-seed investments, it is an open-source, encrypted, user-controlled decentralized storage software designed for both web3 and traditional users. Data is securely stored across the decentralized infrastructure. Hello Drive is built on the principles of efficiency, sustainability, and decentralization, and that is why our infrastructure leverages unused storage space from current devices and constantly fine-tunes its efficiency, resulting in unmatched scalability. Sustainability is a key aspect, as our network doesn't require the creation of new servers, making us a carbon-neutral project.

### Is this project associated with other projects/ecosystem stakeholders?
Yes

### If answered yes, what are the other projects/ecosystem stakeholders
IPFS, Sia, Metamask

### Describe the data being stored onto Filecoin
Clients will store their data on hot and cold storage. Hot storage will be linked to IPFS and/or Sia and cold storage is backed up in Filecoin SPs.
When a user uploads its data, it is encrypted with AES-CBC end to end and has the option to share its data publicly or with specific terms (to a specific person, with a time range...).

### Where was the data currently stored in this dataset sourced from
My own storage infra

### If you answered "Other" in the previous question, enter the details here
n/a

### How do you plan to prepare the dataset
lotus

### If you answered "other/custom tool" in the previous question, enter the details here
n/a

### Please share a sample of the data
User's personal data (images, videos, documents...).

### Confirm that this is a public dataset that can be retrieved by anyone on the Network
No

### If you chose not to confirm, what was the reason
n/a

### What is the expected retrieval frequency for this data
Daily

### For how long do you plan to keep this dataset stored on Filecoin
2 to 3 years

### In which geographies do you plan on making storage deals
Europe

### How will you be distributing your data to storage providers
I don't know yet

### How do you plan to choose SP
Slack

### If you answered "Others" in the previous question, what is the tool or platform you plan to use
n/a

### If you already have a list of storage providers to work with, fill out their names and provider IDs below
n/a

### How do you plan to make deals to your storage providers
Others/custom tool

### If you answered "Others/custom tool" in the previous question, enter the details here
n/a

### Can you confirm that you will follow the Fil+ guideline
Yes

_Application created via [filplus.storage](https://filplus.storage)_

**Comment by data-programs** [comment]
This application requests a total of 10 PiB, so it’s labeled `very large application`

**Comment by Sunnyiscoming** [comment]
> When a user uploads its data, it is encrypted with AES-CBC end to end and has the option to share its data publicly or with specific terms (to a specific person, with a time range...).

1. Whether the user data you will store is totally public? If it is encrypted, please apply for FIL+. If it is fully public, please provide enough data samples.

2. Total amount of DataCap being requested≠Expected size of single dataset (one copy)*Number of replicas to store
10 PiB≠100 GiB*4

3. Could you send an email to filplus-app-review@fil.org with your official domain in order to confirm your identity? Email name should includes the issue id #2081.

**Comment by alexanderbkl** [comment]
Thank you for your query Sunny!

To clarify, although our users' data is encrypted with AES-CBC end-to-end, they have the option to share their data publicly or with specific conditions (to a specific person, within a certain time range, etc.). This shared data can be accessed via a special link that our system generates. Therefore, while the data is encrypted, it can become publicly accessible if the user chooses to share it.

Considering this, our data falls in a category that is both private and public to a certain extent, depending on the individual user's choice. I believe applying for FIL+ is suitable for our case as it is partially encrypted. Due to the private nature of our user data, providing data samples might be a challenge but we can arrange some anonymized samples or synthetic data if required.

Regarding the DataCap, we are requesting a total of 10 PiB. We anticipate the average size of a single dataset (one copy) to be about 100 GiB, and we intend to store four replicas of each dataset. This replication strategy aligns with our goal of ensuring data redundancy and availability, and also explains our larger DataCap request. The replicas will likely be stored with different storage providers for the sake of decentralization and security.

As for the question about sending an email to confirm identity, we will be proceeding with that step promptly.

I hope this clarifies your questions regarding our data and our DataCap request. Please let us know if there are any other details we can provide.

**Comment by alexanderbkl** [comment]
Hi!

I've just sent the email from our domain to proof our identity.

Thanks in advance!

**Comment by Sunnyiscoming** [comment]
@kevzak

**Comment by kevzak** [comment]
Hi @alexanderbkl - can you explain the dataset a bit more. What type of data will be stored by your clients?

Also, can you prove the dataset size? As I'm reading, 250GiB x 4 does not = 10PiB. Can you re-explain the math behind the DataCap request?

**Comment by kevzak** [comment]
Because this is a private dataset, the guidelines call for use of E-Fil+ pathway which includes additional upfront checks of the Applicant, Business and Data. See details here: https://efilplus.super.site/

**Comment by kevzak** [comment]
Please let me know if you have any questions about application process @alexanderbkl
