### ISSUE TITLE
[DataCap Application] Global Ensemble Forecast System Re-forecast

### ISSUE THREAD

**Issue by ConnorDao5** [filecoin-project/filecoin-plus-large-datasets#2083]
### Data Owner Name

NOAA

### What is your role related to the dataset

Data Preparer

### Data Owner Country/Region

United States

### Data Owner Industry

Environment

### Website

https://registry.opendata.aws/noaa-gefs-reforecast/

### Social Media

```text
https://www.noaa.gov/
https://www.facebook.com/NOAA
```

### Total amount of DataCap being requested

7PiB

### Expected size of single dataset (one copy)

392TiB

### Number of replicas to store

10

### Weekly allocation of DataCap requested

800TiB

### On-chain address for first allocation

f1rhe5w5lacm6ppdu6mmppjv4xje5cfqniokai4zy

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
NOAA has generated a multi-decadal reanalysis and reforecast data set to accompany the next-generation version of its ensemble prediction system, the Global Ensemble Forecast System, version 12 (GEFSv12). As a data preparer, I've downloaded the beneficial dataset for storage. Now I think it is suited to stored in filecoin for safety storage.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
GEFS Re-forecast in Grib2 Format. Accompanying the real-time forecasts are “reforecasts” of the weather, that is, retrospective forecasts spanning the period 2000-2019.
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### How do you plan to prepare the dataset

lotus, singularity, I don't know yet

### Please share a sample of the data

```text
s3://noaa-gefs-retrospective/
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Sporadic

### For how long do you plan to keep this dataset stored on Filecoin

2 to 3 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America

### How will you be distributing your data to storage providers

HTTP or FTP server, Shipping hard drives, Lotus built-in data transfer

### How do you plan to choose storage providers

Slack, Big Data Exchange, Partners

### If you already have a list of storage providers to work with, fill out their names and provider IDs below

```text
I've found f0143928 f01204565 f0392734 for cooperation. There'll be more SP to join in.
```

### How do you plan to make deals to your storage providers

Lotus client, Singularity

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
What is your role at the company that is behind this project?
How are you connected to the data set? The website isn't yours. Do you work for the listed organization?
How are you finding SPs. List a detailed plan.

**Comment by herrehesse** [comment]
@ConnorDao5, considering that your account is newly created and you are requesting 7PiB of storage, specifically in Asia or through VPNs from the USA (_as witnessed on hundred's of SP's already_), this LDN is highly concerning. Also, this dataset has already been stored multiple times. 

It would be advisable to remove your application as no notary will sign this.

**Comment by ConnorDao5** [comment]
@Sunnyiscoming 
I do not work in the company which owned the data. I am just a data preparer here.
I do want to help our society store worthwhile data. While looking through AWS datasets, I came across this dataset and I thought it was worth to store. Then I chose and downloaded it.
No, I do not work for the organization.
I found SPs on slack/BDE platform who can make deals. Before cooperation, I will ask SPs if they are willing to store data I provide and if they have capacity to store it. Now I have already discussed with several SPs to confirm the idea of cooperation.

**Comment by herrehesse** [comment]
@ConnorDao5 None of the information provided is correct. The dataset is already stored on Filecoin, and new accounts do not receive 7PiB. If you have a smaller 100T dataset that hasn't been stored multiple times yet, I would be more than happy to assist you in onboarding it.

**Comment by Sunnyiscoming** [comment]
Best practice for storing large datasets includes ideally, storing it in 3 or more regions, with 4 or more storage provider operators or owners.
You should list Miner ID, Business Entity, Location of sps in one more region.

**Comment by ConnorDao5** [comment]
Hello @Sunnyiscoming 
I think SP should have enough token, but I'm a DP. I have no application before in filecoin. But I have prepared for offline transfer and online transfer (hard disks and bandwidth). 
We'll pack the data at the first step. Then we use lotus to generate car files. Later I transfer it to SP.
The dataset has been stored before in filecoin. I saw that these applicants haven't finished their storage and their applications have some problem to improve. So I downloaded this dataset and choose it as my application.

**Comment by ConnorDao5** [comment]
>None of the information provided is correct.
@herrehesse How can you say that? You are impolite.

**Comment by herrehesse** [comment]
> "You are impolite."

You are asking for a HUGE amount of community granted datacap with ZERO reputation, that is highly impolite and not how we operate here.

 If you have a smaller 100T dataset that hasn't been stored multiple times yet, I would be more than happy to assist you in onboarding it.

**Comment by Filplus-govteam** [comment]
Hello @ConnorDao5 per the new guidelines https://github.com/filecoin-project/notary-governance/issues/922 for Open Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

This information will be reviewed by Fil+ Governance team to confirm validity toward the Fil+ guideline of a distributed storage plan and then the application will be triggered for notary review. Let us know if you have any questions.

**Comment by Sunnyiscoming** [comment]
Any update here?

**Comment by Sunnyiscoming** [comment]
Close for no reply.
