### ISSUE TITLE
[DataCap Application] USC Shoah Foundation

### ISSUE THREAD

**Issue by mholland-usc** [filecoin-project/filecoin-plus-large-datasets#2085]
### Data Owner Name
USC Shoah Foundation

### What is your role related to the dataset
Dataset Owner

### Data Owner Country/Region
United States

### Data Owner Industry
Not-for-Profit

### Website
[https://sfi.usc.edu/](https://sfi.usc.edu/)

### Social Media
https://www.instagram.com/uscshoahfoundation/ (Instagram)

### Total amount of DataCap being requested
7 PiB

### Expected size of single dataset (one copy)
2 PiB

### Number of replicas to store
1

### Weekly allocation of DataCap requested
400 TiB

### On-chain address for first allocation
f17g7h52bsi53rb263xwne573dusskit4mieqkgry

### Data Type of Application
Private Non-Profit / Social impact

### Custom multisig
- [x] Use Custom Multisig

### Identifier
efil
### Share a brief history of your project and organization
USC Shoah Foundation  The Institute for Visual History and Education develops empathy, understanding and respect through testimony, using its Visual History Archive of more than 55,000 video testimonies, award-winning IWitness education program, and the Center for Advanced Genocide Research. USC Shoah Foundation's interactive programming, research and materials are accessed in museums and universities, cited by government leaders and NGOs, and taught in classrooms around the world. Now in its third decade, USC Shoah Foundation reaches millions of people on six continents from its home at the Dornsife College of Letters, Arts and Sciences at the University of Southern California.

### Is this project associated with other projects/ecosystem stakeholders?
Yes

### If answered yes, what are the other projects/ecosystem stakeholders
Starling Labs

### Describe the data being stored onto Filecoin
Video testimonies

### Where was the data currently stored in this dataset sourced from
My own storage infra

### If you answered "Other" in the previous question, enter the details here
n/a

### How do you plan to prepare the dataset
singularity

### If you answered "other/custom tool" in the previous question, enter the details here
n/a

### Please share a sample of the data
Previously shared in original data cap application.
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/53

### Confirm that this is a public dataset that can be retrieved by anyone on the Network
No

### If you chose not to confirm, what was the reason
A lot of the data is already publicly available for view via the Visual History Archive (https://vhaonline.usc.edu/). Some of the data has been requested to be private for a period of time based on requests from the interviewees of the content. 

### What is the expected retrieval frequency for this data
Never

### For how long do you plan to keep this dataset stored on Filecoin
Permanently

### In which geographies do you plan on making storage deals
North America

### How will you be distributing your data to storage providers
HTTP or FTP server

### How do you plan to choose SP
Partners

### If you answered "Others" in the previous question, what is the tool or platform you plan to use
n/a

### If you already have a list of storage providers to work with, fill out their names and provider IDs below
PiKNiK

### How do you plan to make deals to your storage providers
Boost client

### If you answered "Others/custom tool" in the previous question, enter the details here
n/a

### Can you confirm that you will follow the Fil+ guideline
Yes

_Application created via [filplus.storage](https://filplus.storage)_

**Comment by data-programs** [comment]
This application is requesting DataCap for a **private** dataset, so it's labeled `efil+`

**Comment by kevzak** [comment]
Hi @jamerduhgamer I'm reading you requested 5PiB and need 7PiB total, so 2 additional PiB to get two, 3.5PiB copies completed.

As this is a previously approved, FF supported project, with proof from https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/53 it can proceed. 

Yes, @mholland-usc should complete KYC to comply with E-Fil+ applicant new standards.

**Comment by mholland-usc** [comment]
Hello, I completed the KYC process on Friday, 7/7.

**Comment by jamerduhgamer** [comment]
I have also completed the KYC process. @kevzak, let me know what are the next steps to getting this application approved for notary signatures!

**Comment by Filplus-govteam** [comment]
> Hello, I completed the KYC process on Friday, 7/7.

you might need to submit again @mholland-usc it's not showing as complete. I'm asking our team to look at record as well, I'll get back ASAP

**Comment by kevzak** [comment]
> Hello, I completed the KYC process on Friday, 7/7.

Hi @mholland-usc you might need to try again. I'm asking to look at log of completed, I'll get back ASAP

**Comment by mholland-usc** [comment]
@kevzak Did you receive it? I tried a second time.

**Comment by kevzak** [comment]
I can confirm this client has completed KYC and KYB per E-Fil+ Guidelines. Open for notary review.

**Comment by kevzak** [comment]
## Datacap Request Trigger
#### Total DataCap requested 
> 2PiB
#### Expected weekly DataCap usage rate 
> 400TiB
#### Client address
> f3w5fx6wta4ewl2iyf7xcogmzffz2fmrngpzdpduj3xmk3dwjxc6dyq36gdf3rflkkrblh5nci5xymc5hal3qq

**Comment by TakiChain** [comment]
Willing to give my signature in the first round.

**Comment by TakiChain** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceathsd7h4kfargnk5ltygbkf65mozthq4otitzc5pkjrjnq2pqkdc 
#### Address 
> f3w5fx6wta4ewl2iyf7xcogmzffz2fmrngpzdpduj3xmk3dwjxc6dyq36gdf3rflkkrblh5nci5xymc5hal3qq
#### Datacap Allocated
> 102.39TiB
#### Signer Address
> f15impf3j2zcaex4lhyxndxswuuhv24vzstuqtxsi
#### Id
> f02fca3b-78bc-4697-91b7-a359693ba944
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceathsd7h4kfargnk5ltygbkf65mozthq4otitzc5pkjrjnq2pqkdc

**Comment by MRJAVAZHAO** [comment]
Willing to support the initial approval.

**Comment by MRJAVAZHAO** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced4novss25yryo5nyxzyfde66w6wqps2gitgwjuuqxmgaxcd5fwek 
#### Address 
> f3w5fx6wta4ewl2iyf7xcogmzffz2fmrngpzdpduj3xmk3dwjxc6dyq36gdf3rflkkrblh5nci5xymc5hal3qq
#### Datacap Allocated
> 102.39TiB
#### Signer Address
> f14gme3f52prtyzk6pblogrdd6b6ivp4swc6qmesi
#### Id
> f02fca3b-78bc-4697-91b7-a359693ba944
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced4novss25yryo5nyxzyfde66w6wqps2gitgwjuuqxmgaxcd5fwek

**Comment by herrehesse** [comment]
@mholland-usc I have done due diligence on your LDN & account and willing to support future requests. Good luck with your application!

**Comment by kevzak** [comment]
I think we have an issue here @simonkim0515?

**Comment by cryptowhizzard** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedotca6kpgucdu5wzo4ixtdrvcindz3tsdbsinsallzoursfhptfy 
#### Address 
> f17g7h52bsi53rb263xwne573dusskit4mieqkgry
#### Datacap Allocated
> 1.56PiB
#### Signer Address
> f1krmypm4uoxxf3g7okrwtrahlmpcph3y7rbqqgfa
#### Id
> 2d3e4829-868e-48ef-b228-99f9b58e8e71
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedotca6kpgucdu5wzo4ixtdrvcindz3tsdbsinsallzoursfhptfy

**Comment by zcfil** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec6znmuvrzenajogwslmxshvq45dn4y3idbzjv3jpmqywuvstalt2 
#### Address 
> f17g7h52bsi53rb263xwne573dusskit4mieqkgry
#### Datacap Allocated
> 1.56PiB
#### Signer Address
> f1cjzbiy5xd4ehera4wmbz63pd5ku4oo7g52cldga
#### Id
> 2d3e4829-868e-48ef-b228-99f9b58e8e71
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec6znmuvrzenajogwslmxshvq45dn4y3idbzjv3jpmqywuvstalt2

**Comment by jamerduhgamer** [comment]
Hi @simonkim0515, @kevzak, can we have this LDN reopened?

**Comment by cryptowhizzard** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedfy5bwtosz4namfi27nwest5uu2xtbiaqwfetoztexctl5pfuuwi 
#### Address 
> f17g7h52bsi53rb263xwne573dusskit4mieqkgry
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1krmypm4uoxxf3g7okrwtrahlmpcph3y7rbqqgfa
#### Id
> 4929486e-56c6-4f79-8c80-e40252ce3044
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedfy5bwtosz4namfi27nwest5uu2xtbiaqwfetoztexctl5pfuuwi

**Comment by Fenbushi-Filecoin** [comment]
checker:manualTrigger

**Comment by Fenbushi-Filecoin** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb5ohawoar2vmnynp5lvnjm6swrylakunwfbfifh3pxwqksomauo6 
#### Address 
> f17g7h52bsi53rb263xwne573dusskit4mieqkgry
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1yqydpmqb5en262jpottko2kd65msajax7fi4rmq
#### Id
> 4929486e-56c6-4f79-8c80-e40252ce3044
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb5ohawoar2vmnynp5lvnjm6swrylakunwfbfifh3pxwqksomauo6

**Comment by jamerduhgamer** [comment]
Comment to keep LDN open. Sealing has been on-going.

**Comment by jamerduhgamer** [comment]
Comment to keep LDN open. Sealing has been on-going.

**Comment by jamerduhgamer** [comment]
Comment to keep LDN open.

**Comment by jamerduhgamer** [comment]
Comment to keep LDN open.

**Comment by Sunnyiscoming** [comment]
Closed for total datacap reached.
