### ISSUE TITLE
[DataCap Application] Dewei Art

### ISSUE THREAD

**Issue by james0012022** [filecoin-project/filecoin-plus-large-datasets#2086]
### Data Owner Name
Dewei Art

### What is your role related to the dataset
Data Owner

### Data Owner Country/Region
China

### Data Owner Industry
Education & Training

### Website
[http://www.deweiart.com/](http://www.deweiart.com/)

### Social Media
https://space.bilibili.com/587927837/ https://www.xiaohongshu.com/user/profile/5ce00a6f0000000005020264?xhsshare=CopyLink&appuid=5db980920000000001009152&apptime=1676266482 douyin:dwart021 (Bilibili)

### Total amount of DataCap being requested
1 Pib

### Expected size of single dataset (one copy)
1 TiB

### Number of replicas to store
8

### Weekly allocation of DataCap requested
50 TiB

### On-chain address for first allocation
f1eoynacq7iojj4tnhfcptfrvotn4oiyl24catdei

### Data Type of Application
Public, Open Commercial/Enterprise

### Custom multisig
Use Custom Multisig

### Share a brief history of your project and organization
Dewei Art is an art company focusing on art education and creation. The aim is to motivate art enthusiast to learn and enjoy art world through our artists' professional and flexible education and influence, and also connect with all the excellent artists to create more modern artistic works.

### Is this project associated with other projects/ecosystem stakeholders?
No

### If answered yes, what are the other projects/ecosystem stakeholders
n/a

### Describe the data being stored onto Filecoin
art education lessons

### Where was the data currently stored in this dataset sourced from
My own storage infra

### If you answered "Other" in the previous question, enter the details here
n/a

### How do you plan to prepare the dataset
IPFS

### If you answered "other/custom tool" in the previous question, enter the details here
n/a

### Please share a sample of the data
https://www.xiaohongshu.com/user/profile/5ce00a6f0000000005020264?xhsshare=CopyLink&appuid=5db980920000000001009152&apptime=1676266482
https://space.bilibili.com/587927837/
Douyin:dwart021

### Confirm that this is a public dataset that can be retrieved by anyone on the Network
Yes

### If you chose not to confirm, what was the reason
n/a

### What is the expected retrieval frequency for this data
Monthly

### For how long do you plan to keep this dataset stored on Filecoin
More than 3 years

### In which geographies do you plan on making storage deals
Greater China, Asia other than Greater China, Europe, North America

### How will you be distributing your data to storage providers
Shipping hard drives

### How do you plan to choose SP
Slack

### If you answered "Others" in the previous question, what is the tool or platform you plan to use
n/a

### If you already have a list of storage providers to work with, fill out their names and provider IDs below
f02031006 - US
f02033219 - HK
f01392893 - China
f010479 - China

### How do you plan to make deals to your storage providers
Lotus client

### If you answered "Others/custom tool" in the previous question, enter the details here
n/a

### Can you confirm that you will follow the Fil+ guideline
Yes

_Application created via [filplus.storage](https://filplus.storage)_

**Comment by james0012022** [comment]
Hi Community and Notaries
I reapplied my LDN of entity Dewei which has been applied before (you can refer to below link)
[https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1606]

In previous application you can see I have done official email KYC, proper questions reply, data sample, Sp informaiton.

Appreicate the notaries's due diligence inside and that LDN met a tech issue which cannot be solved - created some obstacles for notaries' signature.

That is why I applied a new one.

@raghavrmadya  Keep you noted.  please keep the old one so that notaries can refer to the communication inside.

Thanks.

**Comment by herrehesse** [comment]
@james0012022, Your deliberate dishonesty towards the community is evident, and I strongly recommend the immediate termination of your application.

The minerIDs f01392893 and f010479 are associated with one of our trusted partners in Europe. Misappropriating their minerIDs to falsely appear legitimate is a serious offense that we do not tolerate lightly.

@simonkim0515 @raghavrmadya Can you close this manually?

**Comment by james0012022** [comment]
@herrehesse

hello, I do not know what you mean?
you mean MinerIDs are not right?

**Comment by james0012022** [comment]
@herrehesse

My information might be a bit outdated because I have been out for biz travel over one month, and I kept focusing on LDN tech issue itself. 
Thanks for your pointing out and I have talked with the team and tried to reach out to more qualified SPs and get back with new SP IDs for review. 

Thanks anyway.

**Comment by herrehesse** [comment]
"My information might be a bit outdated"?

Show me your communication with those SP's please.

**Comment by james0012022** [comment]
hey @herrehesse

I am not the direct talker in my team. I don't know the details.That is why I said outdated. 
I have asked the team to source more SPs for further cooperation. Result- oriented. 

Anyway, Thanks for your information.

**Comment by herrehesse** [comment]
@james0012022 Looking forward to your list!

**Comment by Sunnyiscoming** [comment]
- Have you prepared enough token for sector pledge?
- Are you a data preparer? What is your previous experience as a data-preparer? List previous applications and client IDs
- How will the data be prepared? Please include tooling used and technical details
- If you are not preparing the data, who will prepare the data?  (Name and Business)
- Has this dataset been stored on Filecoin before? If so, why are you choosing to store it again?
- Best practice for storing large datasets includes ideally, storing it in 3 or more regions, with 4 or more storage provider operators or owners.You should list Miner ID, Business Entity, Location of sps you will cooperate with.

**Comment by Filplus-govteam** [comment]
Hello @james0012022  per the new guidelines https://github.com/filecoin-project/notary-governance/issues/922 for Open Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

This information will be reviewed by Fil+ Governance team to confirm validity and then the application will be triggered for notary review. Let us know if you have any questions.

**Comment by james0012022** [comment]
I‘ll respond all the questions as above asap
