### ISSUE TITLE
[DataCap Application] <Game Data> < Shen Zhen JuBao Time>

### ISSUE THREAD

**Issue by MaleiWong** [filecoin-project/filecoin-plus-large-datasets#2092]
### Data Owner Name

Shen Zhen JuBao Time

### What is your role related to the dataset

Dataset Owner

### Data Owner Country/Region

Afghanistan

### Data Owner Industry

Life Science / Healthcare

### Website

https://jubaotime.com/#/

### Social Media

```text
https://jubaotime.com/#/
```

### Total amount of DataCap being requested

5PiB

### Expected size of single dataset (one copy)

500TiB

### Number of replicas to store

10

### Weekly allocation of DataCap requested

600TiB

### On-chain address for first allocation

f12mdi6gfrynaaixg7eht6iq4rqjchltoewv4phza

### Data Type of Application

Public, Open Commercial/Enterprise

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Jubao Time Network Technology Co., Ltd. was established in June 2016. Its headquarter is located in Shenzhen Bay Science and Technology Ecological Park. It is an Internet company dedicated to serving the game ecology.
In the 7 years since its establishment, the company has focused on serving more players and assisting games to create a safer and healthier gaming environment and player community.

The main business includes blind box, OOGAME, etc., creating game products based on "World of Warcraft" and "Three Kingdoms".
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
Design and copywriting of game props
Game Blind Box Design
Posters and videos for product promotion
Some user data that can be disclosed
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### How do you plan to prepare the dataset

IPFS, lotus, singularity

### Please share a sample of the data

```text
https://drive.google.com/drive/folders/1qR0qtvghf8l_yBLENkyBEbCdJdNeOfrl?usp=sharing
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

1 to 1.5 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, Europe

### How will you be distributing your data to storage providers

Cloud storage (i.e. S3), HTTP or FTP server, Shipping hard drives, Lotus built-in data transfer

### How do you plan to choose storage providers

Slack, Filmine

### How do you plan to make deals to your storage providers

Boost client, Lotus client, Singularity

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by MaleiWong** [comment]
It looks like you are mistaken. I'm a programmer in our company, and this GitHub has been around for almost 2 years, and it's not the latest account created.

**Comment by Sunnyiscoming** [comment]
Please explain why #541, the previous issue of yours, disappeared.

Best practice for storing large datasets includes ideally, storing it in 3 or more regions, with 4 or more storage provider operators or owners.
You should list Miner ID, Business Entity, Location of sps you will cooperate with.

**Comment by Filplus-govteam** [comment]
Hello @MaleiWong per the new guidelines https://github.com/filecoin-project/notary-governance/issues/922 for Open Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

This information will be reviewed by Fil+ Governance team to confirm validity and then the application will be triggered for notary review. Let us know if you have any questions.
