### ISSUE TITLE
[DataCap Application] <CAO> - <Sentinel-1 SLC dataset>

### ISSUE THREAD

**Issue by caoxinhe0108** [filecoin-project/filecoin-plus-large-datasets#2093]
### Data Owner Name

LiveEO

### What is your role related to the dataset

Dataset Owner

### Data Owner Country/Region

Afghanistan

### Data Owner Industry

Life Science / Healthcare

### Website

https://www.live-eo.com/

### Social Media

```text
Twitter---https://twitter.com/liveeo_space
Linkedin---https://www.linkedin.com/company/liveeo/
```

### Total amount of DataCap being requested

10PiB

### Expected size of single dataset (one copy)

64G

### Number of replicas to store

1

### Weekly allocation of DataCap requested

1PiB

### On-chain address for first allocation

f1ynv3f5ne5k7xxr7z5q7coro7rqpls3ilhuz3ndy

### Data Type of Application

Slingshot

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
LiveEO was born from the idea that satellite data, a vast and almost untapped resource, has enormous potential to transform our lives, and the world around us, for the better. Sven and Daniel, two NewSpace enthusiasts with a keen interest in A.I., founded LiveEO in 2018 with a simple vision: to apply this incredible trove of data about our planet to improve the way we do business, and live our lives.
```

### Is this project associated with other projects/ecosystem stakeholders?

Yes

### Describe the data being stored onto Filecoin

```text
LiveEO was born from the idea that satellite data, a vast and almost untapped resource, has enormous potential to transform our lives, and the world around us, for the better. Sven and Daniel, two NewSpace enthusiasts with a keen interest in A.I., founded LiveEO in 2018 with a simple vision: to apply this incredible trove of data about our planet to improve the way we do business, and live our lives.
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### Please share a sample of the data

```text
aws s3 ls --no-sign-request s3://sentinel1-slc/	Total Objects: 5961934	
1.1 PiB
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [ ] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

2 to 3 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, Africa, North America

### How will you be distributing your data to storage providers

Cloud storage (i.e. S3), IPFS

### How do you plan to choose storage providers

Slack, Big Data Exchange

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by herrehesse** [comment]
The dataset in question has already been stored multiple times on the chain, and adding another 10 copies does not bring any additional value to the Filecoin ecosystem. 

Requesting notaries not to sign, and applicant to close this request.

https://github.com/filecoin-project/filecoin-plus-large-datasets/issues?page=2&q=is%3Aissue+sentinel

**Comment by Sunnyiscoming** [comment]
Please see questions in #2096

**Comment by luobin544** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebwyt5zfdemidmpr4vy6cqve2jmcadyqyblj6tnz4el6raz7gp5c2 
#### Address 
> f1ynv3f5ne5k7xxr7z5q7coro7rqpls3ilhuz3ndy
#### Datacap Allocated
> 2.00PiB
#### Signer Address
> f1tbd632f6w62glfaf7wjpimacbnjiz26poyoes2q
#### Id
> 03e1dfa2-150f-46d2-a88d-382decd3e250
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebwyt5zfdemidmpr4vy6cqve2jmcadyqyblj6tnz4el6raz7gp5c2

**Comment by SuperChaiChai** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebibabtt4y5gnrdhk5uwmzg7jr4wgbo7cpjwt7zljbg5c76vn52bu 
#### Address 
> f1ynv3f5ne5k7xxr7z5q7coro7rqpls3ilhuz3ndy
#### Datacap Allocated
> 2.00PiB
#### Signer Address
> f12mckci3omexgzoeosjvstcfxfe4vqw7owdia3da
#### Id
> 03e1dfa2-150f-46d2-a88d-382decd3e250
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebibabtt4y5gnrdhk5uwmzg7jr4wgbo7cpjwt7zljbg5c76vn52bu

**Comment by caoxinhe0108** [comment]
It's in progress

**Comment by caoxinhe0108** [comment]
checker:manualTrigger

**Comment by caoxinhe0108** [comment]
The report is very good and I am willing to support it

**Comment by Tom-OriginStorage** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebruy45l46z2wwtm4wa43u5zcqxbev7aim62ov42szfxuls6ptxnq 
#### Address 
> f1ynv3f5ne5k7xxr7z5q7coro7rqpls3ilhuz3ndy
#### Datacap Allocated
> 2.00PiB
#### Signer Address
> f1q6bpjlqia6iemqbrdaxr2uehrhpvoju3qh4lpga
#### Id
> 03e1dfa2-150f-46d2-a88d-382decd3e250
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebruy45l46z2wwtm4wa43u5zcqxbev7aim62ov42szfxuls6ptxnq

**Comment by zcfil** [comment]
checker:manualTrigger

**Comment by zcfil** [comment]
Looking good, willing to support this round

**Comment by zcfil** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedzpsfkyzf7e63f5akgbiyeprgfuwjre6z5aqydgy3jkjh5vs2kvi 
#### Address 
> f1ynv3f5ne5k7xxr7z5q7coro7rqpls3ilhuz3ndy
#### Datacap Allocated
> 2.00PiB
#### Signer Address
> f1cjzbiy5xd4ehera4wmbz63pd5ku4oo7g52cldga
#### Id
> 03e1dfa2-150f-46d2-a88d-382decd3e250
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedzpsfkyzf7e63f5akgbiyeprgfuwjre6z5aqydgy3jkjh5vs2kvi
