### ISSUE TITLE
[DataCap Application] <ZKLink> - <cross-chain platform>

### ISSUE THREAD

**Issue by ZKLink2022** [filecoin-project/filecoin-plus-large-datasets#2098]
### Data Owner Name

ZKLINK

### What is your role related to the dataset

Dataset Owner

### Data Owner Country/Region

China

### Data Owner Industry

IT & Technology Services

### Website

https://zk.link/

### Social Media

```text
Twitter：https://twitter.com/zkLinkorg Discord:https://discord.com/invite/9GCwxN7xaJ 
Telegram：https://t.me/zkLinkorg
```

### Total amount of DataCap being requested

5PiB

### Expected size of single dataset (one copy)

500T

### Number of replicas to store

10

### Weekly allocation of DataCap requested

600TiB

### On-chain address for first allocation

f1ocmtc3rkver5ljygyvofpg6pntgbq7qfinmum2i

### Data Type of Application

Public, Open Commercial/Enterprise

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
zkLink is an ultra secure, chain-to-chain interoperability protocol powered by zero-knowledge technology. As a ”connector” among diverse ecosystems, zkLink cooperates with various public chains and Layer2 protocols to provide a more convenient and secure chain-to-chain trading environment, contributing to a more accessible and efficient DeFi ecosystem for everyone. Furthermore, we are engaging in NFT marketplace. And we have built a platform for cross-chain transactions and already have nearly 100 thousands fans in social media and community. Our blog publishes news about blockchain and followers are allowed to post their content in free. We serve not only individuals, but also toB.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### If answered yes, what are the other projects/ecosystem stakeholders

```text
We are cooperate with various public chains and Layer2 protocols
```

### Describe the data being stored onto Filecoin

```text
Videos, image, info related with our business.
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### How do you plan to prepare the dataset

IPFS

### Please share a sample of the data

```text
https://drive.google.com/file/d/1FxhPW2ye1_-gx5wkYZ9Zj0aOGC2PqZ_V/view?usp=share_link
https://drive.google.com/file/d/1oit2oySVOfYOODhN33VfLODUPbnajQr_/view?usp=share_link
https://drive.google.com/file/d/1MDtNnYnqZtfvoqmcBejLzA_WygS3vgsm/view?usp=share_link
https://drive.google.com/file/d/1-0EpcRcyt34ZGFVx47u_akILIT9cQd52/view?usp=share_link
https://drive.google.com/file/d/1QYEP9zvB79KQoaR_76QfVIjtzxG_2s_-/view?usp=share_link
https://drive.google.com/file/d/1uqwju1tqYvLmdUHTENHX4ia7oYjK1prN/view?usp=share_link
https://drive.google.com/file/d/12g0hvHTTew8i1IYxIpII3hK41GulEgMk/view?usp=share_link
https://drive.google.com/file/d/1CDD75auJp5ogOMflUuOgKaCwNXRCufTK/view?usp=share_link
https://drive.google.com/file/d/1N5ZgIgJJ4GYFp3OQ-wHP78J6Pge-5z7V/view?usp=share_link
https://drive.google.com/file/d/1qsfeOSa12XiTucGxmAg_YvCqeu6rddxw/view?usp=share_link
https://drive.google.com/file/d/1SE5SZDLn0KtDA6aZqbXn1mwSCDsFjrHW/view?usp=share_link
https://drive.google.com/file/d/1p_xSA4Do9P-WnH-SYlOuY742YCI8k5I2/view?usp=share_link
https://drive.google.com/file/d/1SHk22Ecy1N08jjXCxHRX672OTDKEd3Rz/view?usp=share_link
https://drive.google.com/file/d/1XfZqn_fnhsWZwGJUr2swhM9zmbyalqkW/view?usp=share_link
https://drive.google.com/file/d/1sw6sYTL0fcofz8hVHY53sv-mfmZBpmEA/view?usp=share_link
https://drive.google.com/file/d/1b4yyng3nY6pLmveHwabj5ihrWEJlAD-p/view?usp=share_link
https://drive.google.com/file/d/1lkYYVF7kTBKyF-pppoNkDIzNDZWk2jj1/view?usp=share_link
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### If you chose not to confirm, what was the reason

```text
f01740934^^f01834291^^f01854772^^f02148382^^f02201020^^f02194766^^f02226892
```

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

2 to 3 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America

### How will you be distributing your data to storage providers

Cloud storage (i.e. S3), HTTP or FTP server, IPFS, Lotus built-in data transfer

### How do you plan to choose storage providers

Partners

### How do you plan to make deals to your storage providers

Boost client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by herrehesse** [comment]
The initial request for 5 PiB using a newly created account and without establishing trust within the community is concerning. I highly recommend close the application and reconsider by starting with a smaller amount to build credibility and trust before making larger requests.

Advising notaries not to engage.

**Comment by ZKLink2022** [comment]
> * Have you prepared enough token for sector pledge?
 - Yep, I believe they are ready.

> * Are you a data preparer? What is your previous experience as a data-preparer? List previous applications and client IDs
> * How will the data be prepared? Please include tooling used and technical details
> * If you are not preparing the data, who will prepare the data?  (Name and Business)
- We have a proprietary enterprise storage server where all of our enterprise data is currently stored.
We will give the server port corresponding to the sp to be cooperated, and let them download the data we need to store from the port. The ip of these sps will be whitelisted by us to ensure our data security.
> * Has this dataset been stored on Filecoin before? If so, why are you choosing to store it again?
- We have submitted an application form before, and that application form #1307 has been approved, but it seems that due to some bugs, our f1 address has not received the dc. However, no one responded to our application form. It's been too long, so I have to close it, and resubmitting it is a quicker solution. We have prepared the relevant data and processes and can start again at any time.

> * Best practice for storing large datasets includes ideally, storing it in 3 or more regions, with 4 or more storage provider operators or owners.You should list Miner ID, Business Entity, Location of sps you will cooperate with.
- Yes, The region of SPs covers China, the USA, and other countries in Asia... 
For the first allocation will have : f02224274 HK , f02201020 Guangdong , f01853077 Singapore , f02072288 Japan, f01740934 US, f02060013 KR

**Comment by herrehesse** [comment]
@ZKLink2022,

There are ongoing disputes regarding the miners you have provided, and many of them have been involved in numerous questionable applications that are highly likely to be abusive. Additionally, you have not addressed the inquiries made by Sunny regarding personal and business names, or even mine..

Due to these concerns, the community lacks complete trust in your entity. As a recommendation, I suggest following the steps that any entity in a similar position should take in order to earn the trust of the community:

1. Seek out storage providers in different regions who are willing to store your data and ensure retrievability. Making sure these SP's are not on a blacklist/abuselist.
2. Start with a smaller data request, such as 100T, and ask for the community's signature. I'm willing to assist you with this.
3. Store your data, showcase its retrievability, value, and distribution! (not fake VPN)
4. If everything goes well and you can establish trust, you can request additional datacap. I'll be the first one to offer my assistance.

**Comment by ZKLink2022** [comment]
I have explained these issues and passed the review a long time ago. Now I have to answer the same question again. Is the efficiency of the community too low?

@Sunnyiscoming Appreciate it if you could support us.

**Comment by raghavrmadya** [comment]
Can you prove your relationship with zk.link?

**Comment by ZKLink2022** [comment]
<img width="912" alt="image" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/116628409/5a5cb780-9a6b-40dd-8acf-f961ab983c7e">
Hey @raghavrmadya, We sent an email on Dec 2022.

**Comment by herrehesse** [comment]
@ZKLink2022 7 months ago 1 email?

**Comment by Sunnyiscoming** [comment]
Any update here?

**Comment by Sunnyiscoming** [comment]
Close for no reply.
