### ISSUE TITLE
[DataCap Application] please delete

### ISSUE THREAD

**Issue by abcde1101** [filecoin-project/filecoin-plus-large-datasets#21]
# Large Dataset Notary Application

To apply for a DataCap allocation for your dataset, please fill out the following information.

## Core Information
- Organization Name: Alibaba Damo academy 
- Website / Social Media:https://damo.alibaba.com/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 1.5PiB
- On-chain address for first allocation: f1vykg3elgzoa3lpzf5xo6rbcghzr5ifat757mucq

_Please respond to the questions below in pargraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

## Project details

Share a brief history of your project and organization.
```
Alibaba Damo academy is a research institute dedicated to exploring the unknown of science and technology and driven by human vision. It is a scientific research institution established by Alibaba in many places around the world, based on the research of basic science, disruptive technology and applied technology.
```

What is the primary source of funding for this project?
```
the most important funding comes from our DAMO laboratories ,You can see our  laboratories at the following link:
https://damo.alibaba.com/labs/
```

What other projects/ecosystem stakeholders is this project associated with?
```
This project is mainly related to the Filecoin network, but we do not exclude that we will also try other blockchain storage solutions in the future.
```

## Use-case details

Describe the data being stored onto Filecoin
```
We mainly upload some of the corpus data to the Filecoin network, with the permission of the customers, and we briefly describe the features of the Filecoin network to them.

```

Where was the data in this dataset sourced from?
```
As I described above, our data comes from the available orders of a number of our customers. We are in the process of compiling this data. We can provide that link if necessary.
```

Can you share a sample of what is in the dataset? A link to a file, an image, a table, etc., are good examples of this. 
```
Yes, sure.
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes, we are going to temporarily store this data at a publicly available address, and no specific permissions are required to view it.
```

What is the expected retrieval frequency for this data?
```
We don't think this data will be used very frequently, this data may only be  a backup.
```

For how long do you plan to keep this dataset stored on Filecoin? Will this be a permanent archival or a one-time storage deal?
```
This will be a permanent archive.
```

## DataCap allocation plan

In which geographies do you plan on making storage deals?
```
We intend to store this data primarily in Zhejiang Province.
```

What is your expected data onboarding rate? How many deals can you make in a day, in a week? How much DataCap do you plan on using per day, per week?
```
We think the amount of data uploaded to the Fielcoin network is around 100 TiB per week.
```

How will you be distributing your data to miners? Is there an offline data transfer process?
```
We may give some large amounts of historical data to miners offline, and some small amounts of new data, which will be transmitted online.
```

How do you plan on choosing the miners with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
Firstly he must have a certain scale to ensure data security, and secondly his team needs to have some development capabilities to support subsequent file retrieval in the Filecoin network.
```

How will you be distributing data and DataCap across miners storing data?
```
Regarding this piece, we will talk to different miners and of course compare the prices of services between them, and these factors will also determine the distribution ratio between real data and DataCap.
```

**Comment by dkkapur** [comment]
@abcde1101 - you want this application to be deleted, correct?
