### ISSUE TITLE
[DataCap Application] SafeMatrix

### ISSUE THREAD

**Issue by SafematrixFil** [filecoin-project/filecoin-plus-large-datasets#210]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: SafeMatrix
- Website / Social Media: Website https://safematrix.io/  Twitter https://twitter.com/Safematrix_io Telegram https://t.me/safematrix_io  Discord https://discord.gg/Qz57eRYG  Github https://github.com/safematrix  Medium https://medium.com/@Safematrix
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5 PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 50 TiB
- On-chain address for first allocation: f13bmmgqefi7wlhlxyjxieu6eyxx7vy7ofpsdf3ji

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Safematrix is the world's first innovative combination of MPC, TEE and ZKP technologies to solve the problem of secure and trustless crypto asset custody. The team has brought a number of R&D breakthroughs in private computing technology and has deep knowledge and experience of deploying complex cryptography systems to Web3.0.

```

What is the primary source of funding for this project?
```
Investment from shareholders.
```

What other projects/ecosystem stakeholders is this project associated with?
```
2019 Start to research on zero-knowledge proof, combining homomorphic encryption and zero-knowledge proof techniques to implement addition, subtraction, multiplication and division of ciphertext data. 
2020 In-depth research on secure multi-party computation and the first use of threshold signature scheme instead of multi-signature scheme in cross-chain. Application of TEE technology in cross-chain, communication, and privacy-preserving computing. 
2021 Q2 ABWallet mobile and SGX-based trusted key management service release. 
2021 Q3 Patent application for virtual cloud wallet. ABWallet upgrades to Safematrix, implementing non-interactive signature to optimize performance.
2021 Q4 Multi-tenant backend management platform release, also supports strategy, automatic signatures. 
2022 Safematrix SDK release, seamless access to Dapp. Continuous integration of mainstream coins. DAO open platform release. Support for ETH2.0 Trustless Staking.
```

## Use-case details

Describe the data being stored onto Filecoin
```
Would like to store Technical data.
```

Where was the data in this dataset sourced from?
```
From our own R&D.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://github.com/safematrix/itoa-sgx
https://github.com/safematrix/serde-json-sgx
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
All data can be public.
```

What is the expected retrieval frequency for this data?
```
From time to time.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
We would like to try 540 days first.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
NA is preferred, but we would also like to try other regions.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
We will make a online platform.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We will find the storage providers who are active and reliable.
```

How will you be distributing deals across storage providers?
```
According to their sealing rate.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes. No, thanks.
```

**Comment by galen-mcandrew** [comment]
The provided sample data appear to be forks of the popular [MesaLock Linux distro](https://github.com/mesalock-linux). And the website is missing some sections. Can you provide some more details about the specific public verifiable dataset that you own, which you are planning to store on the Filecoin network?

**Comment by dkkapur** [comment]
Closing this one out for inactivity. Please re-open if relevant and answer the above questions. Thanks!
