### ISSUE TITLE
[DataCap Application] Environmental governance

### ISSUE THREAD

**Issue by hash889900** [filecoin-project/filecoin-plus-large-datasets#2100]
### Data Owner Name

Liaoning Zhongguan Environmental engineering Co., Ltd

### What is your role related to the dataset

Dataset Owner

### Data Owner Country/Region

China

### Data Owner Industry

Environment

### Website

no

### Social Media

```text
no
```

### Total amount of DataCap being requested

8PiB

### Expected size of single dataset (one copy)

1P

### Number of replicas to store

8

### Weekly allocation of DataCap requested

1PiB

### On-chain address for first allocation

f1xvsgtyg7ymo6giksv6qb6gxrr6xsfhjjjyylfey

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Liaoning Zhongguan Environmental engineering Co., Ltd. was established on December 6, 2007. The company's business scope includes: water environment governance, atmospheric environment governance, and ecological environment governance; Solid waste treatment; Comprehensive utilization of renewable resources; Design and construction general contracting of industrial wastewater and domestic wastewater treatment engineering; Water conservancy exploration and design, construction and maintenance of municipal public works; General contracting of environmental protection engineering construction; Operation, commissioning, and management services for environmental pollution control facilities; Production and sales of environmental protection equipment and engineering materials; Engineering consulting and evaluation; Design, construction, and sales of protective materials for radiation protection engineering; Manufacturing and installation of atmospheric pressure electric hot water boilers, waste heat recovery and energy-saving complete equipment, etc
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
Environmental governance promotional videos, environmental videos, satellite remote sensing images, etc
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### How do you plan to prepare the dataset

singularity

### Please share a sample of the data

```text
https://cloud.189.cn/t/IFreEfymmI3y （access code：7rjb）
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Monthly

### For how long do you plan to keep this dataset stored on Filecoin

More than 3 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, Europe

### How will you be distributing your data to storage providers

HTTP or FTP server, Shipping hard drives

### How do you plan to choose storage providers

Slack

### How do you plan to make deals to your storage providers

Boost client, Lotus client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by herrehesse** [comment]
The initial request for 8 PiB using a newly created account and without establishing trust within the community is concerning. I highly recommend close the application and reconsider by starting with a smaller amount to build credibility and trust before making larger requests.

Advising notaries not to engage.

**Comment by Sunnyiscoming** [comment]
- Have you prepared enough token for sector pledge?
- Are you a data preparer? What is your previous experience as a data-preparer? List previous applications and client IDs
- How will the data be prepared? Please include tooling used and technical details
- If you are not preparing the data, who will prepare the data?  (Name and Business)
- Has this dataset been stored on Filecoin before? If so, why are you choosing to store it again?
- Best practice for storing large datasets includes ideally, storing it in 3 or more regions, with 4 or more storage provider operators or owners.You should list Miner ID, Business Entity, Location of sps you will cooperate with.

**Comment by hash889900** [comment]
Token should be SPs preparation, not me preparation, right?

I am a data preparation personnel who study in various communication groups and related technical communication groups for the Filecoin project. I will use singularities to generate car files，https://github.com/tech-greedy/singularity，There is relevant technology sharing here。

This data has not been stored in filecoin

We are looking for SP, and I would like to ask if there are three or more regions, which regions to cities, countries, or continents

**Comment by herrehesse** [comment]
@hash889900,

_Are you going to store ""Governance promotional videos" from China?_

I have serious concerns regarding your data request. Not supportive of your merged dataset requests, it is now allowed by the community. Tt would be more beneficial for the ecosystem if you stored your data with storage providers without datacap and simply pay for the storage. Currently, there is no reason for the community to trust you, and it's important to gain their trust by demonstrating your capabilities. Requesting 8PiB of datacap without establishing credibility is not a viable approach.

Here are some steps you can take:

1. Seek out storage providers in different regions who are willing to store your data and ensure retrievability. Making sure these SP's are not on a blacklist/abuselist.
2. Start with a smaller data request, such as 100T, and ask for the community's signature. I'm willing to assist you with this.
3. Store your data, showcase its retrievability, value, and distribution.
4. If everything goes well and you can establish trust, you can request additional datacap. I'll be the first one to offer my assistance.

By following these steps, you can build trust within the community and demonstrate the worthiness of your data.

**Comment by hash889900** [comment]
> @hash889900,
> 
> _Are you going to store ""Governance promotional videos" from China?_
> 
> I have serious concerns regarding your data request. Not supportive of your merged dataset requests, it is now allowed by the community. Tt would be more beneficial for the ecosystem if you stored your data with storage providers without datacap and simply pay for the storage. Currently, there is no reason for the community to trust you, and it's important to gain their trust by demonstrating your capabilities. Requesting 8PiB of datacap without establishing credibility is not a viable approach.
> 
> Here are some steps you can take:
> 
> 1. Seek out storage providers in different regions who are willing to store your data and ensure retrievability. Making sure these SP's are not on a blacklist/abuselist.
> 2. Start with a smaller data request, such as 100T, and ask for the community's signature. I'm willing to assist you with this.
> 3. Store your data, showcase its retrievability, value, and distribution.
> 4. If everything goes well and you can establish trust, you can request additional datacap. I'll be the first one to offer my assistance.
> 
> By following these steps, you can build trust within the community and demonstrate the worthiness of your data.

Why are all the statements discussed in the community opposing you? Are you an official and can I follow your advice?

**Comment by hash889900** [comment]
@Sunnyiscoming 
f02337006
f02337010
f02252173
f01877184
Currently, we have contacted the above SPs and are actively contacting more

**Comment by herrehesse** [comment]
@hash889900 

> f02337006 eager England
> f02337010 peter California
> 

You take this complete community for a fool?

@raghavrmadya Please close this application.

**Comment by hash889900** [comment]
SPs related information has been modified
Is it okay to use screenshots of the server for data proof.
![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/138882650/ac335f14-5ff4-498e-b36d-115964dae044)

Email sent.

**Comment by hash889900** [comment]
> 

I don't understand what you mean

**Comment by hash889900** [comment]
> @hash889900
> 
> > f02337006 eager England
> > f02337010 peter California
> 
> You take this complete community for a fool?
> 
> @raghavrmadya Please close this application.

I don't understand what you mean

**Comment by Filplus-govteam** [comment]
Hello @hash889900 per the new guidelines https://github.com/filecoin-project/notary-governance/issues/922 for Open Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

This information will be reviewed by Fil+ Governance team to confirm validity and then the application will be triggered for notary review. Let us know if you have any questions.

**Comment by hash889900** [comment]
@Filplus-govteam Can you invite me to join Slack? My email is to8548664monai173@163.com

**Comment by hash889900** [comment]
> Hello @hash889900 per the new guidelines [filecoin-project/notary-governance#922](https://github.com/filecoin-project/notary-governance/issues/922) for Open Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.
> 
> This information will be reviewed by Fil+ Governance team to confirm validity and then the application will be triggered for notary review. Let us know if you have any questions.

submitted

**Comment by herrehesse** [comment]
@hash889900 

You are lying to us. Do you see this community as a fool?
Server disks proof nothing, i can fake a billion TiB of storage like this with screenshots. 

Again:

f02337006 eager England --> is involved with abuse from LDN #1918 and is a VPN (false location).
f02337010 peter California --> miner is blocked from Explorers. 404 &  is involved with abuse from LDN #1918 and is a VPN (false location).


Seriously? Eager and Peter? Two exactly the same minerID's? Coincidence? I think not. Here is proof:

![Screenshot 2023-07-21 at 08 41 37](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/70132857/4f23f88b-c22c-43bb-95c6-8a9518aee4b6)
![Screenshot 2023-07-21 at 08 45 13](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/70132857/ef5e73b4-4b86-4f6e-8f39-ef618ee9e8c8)

**Comment by Sunnyiscoming** [comment]
Please use #2100 as the title of your email.

**Comment by hash889900** [comment]
@Filplus-govteam @Sunnyiscoming Sent to the specified email again.

**Comment by Stanton15** [comment]
Ignore these two liars, they're just trying to sell DC to Chinese SPs.

**Comment by hash889900** [comment]
> Ignore these two liars, they're just trying to sell DC to Chinese SPs.

who?

**Comment by Sunnyiscoming** [comment]
Received that.

**Comment by hash889900** [comment]
@Sunnyiscoming Can you approve it? We are currently contacting SPs in more regions. If you need more information, please leave a message. Thank you.

**Comment by hash889900** [comment]
> Hello @hash889900 as per the message above, there are questions surrounding your SPs listed. We ask that you either:
> 
> * provide contact information of your SPs (email) so we can confirm their entity and location you can send to: [filplus-app-review@fil.org](mailto:filplus-app-review@fil.org)
> * or find new SPs who you can work with to store distributed copies

I already sent the email a few days ago, which includes SP's contact information (email). 

I'm currently reaching out to more SPs to join in, it takes time

> Received that.

@Sunnyiscoming He said he received.

**Comment by Sunnyiscoming** [comment]
![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/105098820/65233d0e-929d-4f5a-bd7b-10473eeb5e0f)

**Comment by hash889900** [comment]
Email re-sent with 2 new
![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/138882650/e5f2bf2e-2307-4373-b312-15b8e12f12b2)

**Comment by mjroddy** [comment]
Just reviewed this. Look at these emails. C'mon. Just shut it down and move on.

**Comment by hash889900** [comment]
> Just reviewed this. Look at these emails. C'mon. Just shut it down and move on.

I'm sorry, I didn't get your point.

**Comment by Filplus-govteam** [comment]
@hash889900 last chance to provide SP Entities with clearly distributed locations. 

Your lists above have proven to not be who they say they are. Who are your SPs? Do you need help finding SPs?

**Comment by hash889900** [comment]
> @hash889900 last chance to provide SP Entities with clearly distributed locations.
> 
> Your lists above have proven to not be who they say they are. Who are your SPs? Do you need help finding SPs?

@Filplus-govteam  Thanks for the review，I'm still looking for more SPs in the area, which of the above were not approved, and for what reason, as the information was provided to me by them, I need to double check, thanks!

**Comment by Filplus-govteam** [comment]
OK @hash889900 let's see. Thanks. FYI @Sunnyiscoming 
![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/138785508/9b28f1e8-beb9-4fd7-b9a1-5b5f0e1c0c64)

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 8PiB

**Expected weekly DataCap usage rate**
> 1PiB

**Client address**
>f1xvsgtyg7ymo6giksv6qb6gxrr6xsfhjjjyylfey

**Comment by MRJAVAZHAO** [comment]
The data sample you provided seems to come from the Internet. Are you authorized to do so?

**Comment by hash889900** [comment]
> The data sample you provided seems to come from the Internet. Are you authorized to do so?

Our data comes from our own company as well as data shared by other companies, which may be partially uploaded on the Internet, but the ownership of the data we upload belongs to our company.

**Comment by woshidama323** [comment]
Distributed locations looks good to me ,
Will support the first stage of this LDN

**Comment by woshidama323** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebiz3ufzx5o52raafpriz7se5h5ibydavlnnh2zbze6ghtigbjzd6 
#### Address 
> f1xvsgtyg7ymo6giksv6qb6gxrr6xsfhjjjyylfey
#### Datacap Allocated
> 409.59TiB
#### Signer Address
> f12tk3adljauwnd3hjbigpfxb7b7gdlj63p6afwtq
#### Id
> e12ffae4-0c96-4f85-a06c-58ece81ddf87
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebiz3ufzx5o52raafpriz7se5h5ibydavlnnh2zbze6ghtigbjzd6

**Comment by Normalnoise** [comment]
checker:manualTrigger

**Comment by Normalnoise** [comment]
The data and distribution plan is great for me， willing to support first round

**Comment by maxvint** [comment]
We are willing to support the first round, and continue to pay attention to the distribution and retrieval.

**Comment by maxvint** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebycdj2gbzrwzsn75qnpkiqws4n2ewbsg5vsmgo6s3zy75qh7thmw 
#### Address 
> f1xvsgtyg7ymo6giksv6qb6gxrr6xsfhjjjyylfey
#### Datacap Allocated
> 409.59TiB
#### Signer Address
> f1ui5iy4mmkxjbw7752omiwp2ols2fzv4thrayagi
#### Id
> e12ffae4-0c96-4f85-a06c-58ece81ddf87
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebycdj2gbzrwzsn75qnpkiqws4n2ewbsg5vsmgo6s3zy75qh7thmw

**Comment by hash889900** [comment]
thank you

**Comment by hash889900** [comment]
@simonkim0515 @Filplus-govteam @Sunnyiscoming There seems to have been a problem and no quota was issued.

**Comment by cryptowhizzard** [comment]
-

**Comment by cryptowhizzard** [comment]
-

**Comment by cryptowhizzard** [comment]
Dear hash889900,

As notary I am doing due diligence on your LDN. I could not get retrieval to work. Can you please upload the car file of CID baga6ea4seaqecxzm34roonfu4syjgt3y7w5ofhtdbtuxc2zjufk5mplmd35igca ?

You can use our upload system at http://send.datasetcreators.com. Please select 7 days for the system to keep the file and post the link you received here so I (and other notaries) can download your content.

**Comment by hash889900** [comment]
> 

@cryptowhizzard Hi,I've uploaded it a couple times and it fails to upload, not sure what the problem is. Can you retrieve it directly from the sp?
![企业微信截图_1693185064980](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/138882650/a56d27f5-ecc8-48fd-884f-62ea0ccb84bb)

**Comment by kevzak** [comment]
checker:manualTrigger

**Comment by kevzak** [comment]
SPs provided: https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/2100#issuecomment-1679672961

SPs taking deals:
f02252173 | Tokyo, Tokyo, JPAwesomecloud Limited | 86.06 TiB | 22.77% | 86.06 TiB | 0.00%
f02237010 | Los Angeles, California, USCNSERVERS LLC | 97.09 TiB | 25.68% | 97.09 TiB | 0.00%
f02237006 | London, England, GBGTHost | 96.66 TiB | 25.57% | 96.66 TiB | 0.00%
f02062851 | Los Angeles, California, USNetLab Global | 98.22 TiB | 25.98% | 98.22 TiB | 0.00%

@hash889900 you need 4 different SP entities. You are showing 4 miner IDs under VPN, likely all the same entity.

**Comment by hash889900** [comment]
> SPs provided: [#2100 (comment)](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/2100#issuecomment-1679672961)
> 
> SPs taking deals: f02252173 | Tokyo, Tokyo, JPAwesomecloud Limited | 86.06 TiB | 22.77% | 86.06 TiB | 0.00% f02237010 | Los Angeles, California, USCNSERVERS LLC | 97.09 TiB | 25.68% | 97.09 TiB | 0.00% f02237006 | London, England, GBGTHost | 96.66 TiB | 25.57% | 96.66 TiB | 0.00% f02062851 | Los Angeles, California, USNetLab Global | 98.22 TiB | 25.98% | 98.22 TiB | 0.00%
> 
> @hash889900 you need 4 different SP entities. 

I am looking for more SPs to work with!

> You are showing 4 miner IDs under VPN, likely all the same entity.

It gave me the impression that they were not the same entity because I prepared 100T of data in advance for them to download, and it was only after the download was complete that they started sealing the.
But I will ask them again about the actual situation and follow up, thank you for your review!

**Comment by hash889900** [comment]
> Can you retry please? We had a firewall issue with cloudflare.

Still having the same problem trying again, I logged some info that it will report an error 2-3 hours into the upload

**Comment by hash889900** [comment]
@DaYouGroup I submitted a bug with a bot and it seems to be fixed now, can you re-sign it? Thank you!

**Comment by Normalnoise** [comment]
checker:manualTrigger

**Comment by Normalnoise** [comment]
`

lotus state get-deal 51748044
{
  "Proposal": {
    "PieceCID": {
      "/": "baga6ea4seaqe2oa523rags2gdlcwzfpurk2b5caw4hg4iqbacmsztk6c7dxqkfq"
    },
    "PieceSize": 34359738368,
    "VerifiedDeal": true,
    "Client": "f02367308",
    "Provider": "f02062851",
    "Label": "bafybeibumncsdj36bghlw3nproea4nl7geopnoj5qtcuonrwfgjnqrhcqu",
    "StartEpoch": 3167174,
    "EndEpoch": 4693574,
    "StoragePricePerEpoch": "0",
    "ProviderCollateral": "9748113587756280",
    "ClientCollateral": "0"
  },
  "State": {
    "SectorStartEpoch": 3142282,
    "LastUpdatedEpoch": -1,
    "SlashEpoch": -1,
    "VerifiedClaim": 34059623
  }
}

lotus client  retrieve --miner f02062851 bafybeibumncsdj36bghlw3nproea4nl7geopnoj5qtcuonrwfgjnqrhcqu 2851
Recv 0 B, Paid 0 FIL, Open (New), 0s [1692093752649546690|0]
Recv 0 B, Paid 0 FIL, DealProposed (WaitForAcceptance), 3ms [1692093752649546690|0]
Recv 0 B, Paid 0 FIL, DealAccepted (Accepted), 338ms [1692093752649546690|0]
Recv 0 B, Paid 0 FIL, PaymentChannelSkip (Ongoing), 338ms [1692093752649546690|0]
Recv 10.57 KiB, Paid 0 FIL, BlocksReceived (Ongoing), 502ms [1692093752649546690|10822]
Recv 11.26 KiB, Paid 0 FIL, BlocksReceived (Ongoing), 503ms [1692093752649546690|11531]
Recv 1.011 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 5.012s [1692093752649546690|1060107]
Recv 2.011 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 6.48s [1692093752649546690|2108683]
Recv 3.011 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 8.328s [1692093752649546690|3157259]
Recv 4.011 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 9.914s [1692093752649546690|4205835]
Recv 5.011 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 11.267s [1692093752649546690|5254411]
Recv 6.011 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 12.723s [1692093752649546690|6302987]
Recv 7.011 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 14.183s [1692093752649546690|7351563]
Recv 8.011 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 15.608s [1692093752649546690|8400139]
Recv 9.011 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 16.798s [1692093752649546690|9448715]
Recv 10.01 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 18.302s [1692093752649546690|10497291]
Recv 11.01 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 19.751s [1692093752649546690|11545867]
Recv 12.01 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 21.338s [1692093752649546690|12594443]
Recv 13.01 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 23.898s [1692093752649546690|13643019]
Recv 13.45 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 25.335s [1692093752649546690|14105297]
Recv 13.48 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 25.336s [1692093752649546690|14134308]
Recv 14.48 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 31.623s [1692093752649546690|15182884]
Recv 15.48 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 36.735s [1692093752649546690|16231460]
Recv 16.48 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 43.587s [1692093752649546690|17280036]
Recv 17.48 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 45.589s [1692093752649546690|18328612]
Recv 18.48 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 46.603s [1692093752649546690|19377188]
Recv 19.48 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 47.543s [1692093752649546690|20425764]
Recv 20.48 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 48.335s [1692093752649546690|21474340]
Recv 21.48 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 48.993s [1692093752649546690|22522916]
Recv 22.48 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 50.057s [1692093752649546690|23571492]
Recv 23.48 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 51.267s [1692093752649546690|24620068]
Recv 24.48 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 52.886s [1692093752649546690|25668644]
`

**Comment by Normalnoise** [comment]
CID check report is ok and high retrieval rate. Willing to support

**Comment by Normalnoise** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceddphats73q6a4y7ydfcwoysygnz4ftddvjuh7hlrcalgldtczbhc 
#### Address 
> f1xvsgtyg7ymo6giksv6qb6gxrr6xsfhjjjyylfey
#### Datacap Allocated
> 1.00PiB
#### Signer Address
> f1c5non5yf35avgcpsqvxu4yj54yyvxorwyjochqq
#### Id
> f6198911-22fe-447e-80b2-b6636177ca6f
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceddphats73q6a4y7ydfcwoysygnz4ftddvjuh7hlrcalgldtczbhc

**Comment by cryptowhizzard** [comment]
Dear hash889900,

As notary I am doing due diligence on your LDN. I could not get retrieval to work. Can you please upload the car file of CID baga6ea4seaqecxzm34roonfu4syjgt3y7w5ofhtdbtuxc2zjufk5mplmd35igca ?

You can use our upload system at http://send.datasetcreators.com. Please select 7 days for the system to keep the file and post the link you received here so I (and other notaries) can download your content.

**Comment by cryptowhizzard** [comment]
Note:

NormalNoise showed retrieval. I got that CID to work for 300 MB but then the download got stuck.

I would like to see a full sector and the data in it before a next tranche get's signed.

**Comment by hash889900** [comment]
> Dear hash889900,
> 
> As notary I am doing due diligence on your LDN. I could not get retrieval to work. Can you please upload the car file of CID baga6ea4seaqecxzm34roonfu4syjgt3y7w5ofhtdbtuxc2zjufk5mplmd35igca ?
> 
> You can use our upload system at http://send.datasetcreators.com. Please select 7 days for the system to keep the file and post the link you received here so I (and other notaries) can download your content.

I have uploaded it more than 5 times and it reports an error after a couple hours.

**Comment by hash889900** [comment]
> Note:
> 
> NormalNoise showed retrieval. I got that CID to work for 300 MB but then the download got stuck.

Which cid

**Comment by herrehesse** [comment]
@DaYouGroup show your due diligence, will dispute if not shown. This application is clearly not in order. 

@kevzak Can you take a look?

**Comment by cryptowhizzard** [comment]
> ## Request Approved
> Your Datacap Allocation Request has been approved by the Notary
> 
> #### Message sent to Filecoin Network
> > bafy2bzaceclgrcwiggwdrfzzhamo6w6nw4onecwdojjqtyro6etnrz3hwqjxa
> 
> #### Address
> > f1xvsgtyg7ymo6giksv6qb6gxrr6xsfhjjjyylfey
> 
> #### Datacap Allocated
> > 1.00PiB
> 
> #### Signer Address
> > f1nwjsd2mc6hu4qrwnmd6ukrfkuu4h5fhs7u3exii
> 
> #### Id
> > f6198911-22fe-447e-80b2-b6636177ca6f
> 
> #### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceclgrcwiggwdrfzzhamo6w6nw4onecwdojjqtyro6etnrz3hwqjxa

This is unacceptable during due diligence. There has not been a single retrieval that has worked until now.

![Scherm­afbeelding 2023-09-05 om 15 21 39](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/36404435/c2b2c46e-7c7f-47ea-b548-940d20cc6362)

According to the retrieval bot there is no graphsync and the http ratio is extremely bad. 


![Scherm­afbeelding 2023-09-05 om 15 23 35](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/36404435/52056b55-b08d-4b1b-a613-c613fddb814e)

**Comment by cryptowhizzard** [comment]
This is unacceptable during due diligence. There has not been a single retrieval that has worked until now.

![Scherm­afbeelding 2023-09-05 om 15 21 39](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/36404435/c2b2c46e-7c7f-47ea-b548-940d20cc6362)

According to the retrieval bot there is no graphsync and the http ratio is extremely bad. 


![Scherm­afbeelding 2023-09-05 om 15 23 35](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/36404435/52056b55-b08d-4b1b-a613-c613fddb814e)

**Comment by hash889900** [comment]
Why can all the other notaries retrieve it and you can't?

**Comment by cryptowhizzard** [comment]
Dear hash889900,

As notary I am doing due diligence on your LDN. I could not get retrieval to work. Can you please upload the car file of CID baga6ea4seaqecxzm34roonfu4syjgt3y7w5ofhtdbtuxc2zjufk5mplmd35igca ?

You can use our upload system at http://send.datasetcreators.com. Please select 7 days for the system to keep the file and post the link you received here so I (and other notaries) can download your content.

**Comment by Rioa87** [comment]
> Dear hash889900,
> 
> As notary I am doing due diligence on your LDN. I could not get retrieval to work. Can you please upload the car file of CID baga6ea4seaqecxzm34roonfu4syjgt3y7w5ofhtdbtuxc2zjufk5mplmd35igca ?
> 
> You can use our upload system at http://send.datasetcreators.com. Please select 7 days for the system to keep the file and post the link you received here so I (and other notaries) can download your content.

Please check out [this review](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/2100#issuecomment-1701427250), is there anything else we can do?

**Comment by hash889900** [comment]
> Dear hash889900,
> 
> As notary I am doing due diligence on your LDN. I could not get retrieval to work. Can you please upload the car file of CID baga6ea4seaqecxzm34roonfu4syjgt3y7w5ofhtdbtuxc2zjufk5mplmd35igca ?
> 
> You can use our upload system at http://send.datasetcreators.com. Please select 7 days for the system to keep the file and post the link you received here so I (and other notaries) can download your content.

Please check out https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/2100#issuecomment-1701427250, is there anything else we can do?

**Comment by hash889900** [comment]
@cryptowhizzard  Can you clarify? What do we do?

**Comment by cryptowhizzard** [comment]
> @cryptowhizzard Can you clarify? What do we do?

I can't help you. I can't do my due diligence unless i am able to see your data. 

Sorry.

**Comment by hash889900** [comment]
> > @cryptowhizzard Can you clarify? What do we do?
> 
> I can't help you. I can't do my due diligence unless i am able to see your data.
> 
> Sorry.

Are there any other tools? I can try.

**Comment by hash889900** [comment]
@cryptowhizzard Can you reply to this? I am looking for a solution.

**Comment by hash889900** [comment]
> > @cryptowhizzard Can you reply to this? I am looking for a solution.
> 
> So do I . I retried tonight but the download got stuck again @ 2.1 GB.

I don't know what's causing this problem at the moment, I'll ask around a bit more

**Comment by hash889900** [comment]
checker:manualTrigger

**Comment by Lind111** [comment]
checker:manualTrigger

**Comment by Lind111** [comment]
Already contacted you on slack, please reply to see the cause of this problem thank you

**Comment by cryptowhizzard** [comment]
Hello,

I finally managed to download a deal from you and made it available here:

http://www.datasetcreators.com/downloadedcarfiles/2100-f02367308-f02062851-51706496-baga6ea4seaqf23rem6of45qvylatl6ve7rxlj4ujnul5lgcermpgokap6b6zmmq

This data does not match the same data you provided. Can you explain?

<img width="1060" alt="Scherm­afbeelding 2023-09-16 om 17 43 55" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/36404435/1c18b5fa-09cc-49fa-a311-02f00faea34a">

**Comment by hash889900** [comment]
> Hello,
> 
> I finally managed to download a deal from you and made it available here:
> 
> http://www.datasetcreators.com/downloadedcarfiles/2100-f02367308-f02062851-51706496-baga6ea4seaqf23rem6of45qvylatl6ve7rxlj4ujnul5lgcermpgokap6b6zmmq
> 
> This data does not match the same data you provided. Can you explain?
> 
> <img alt="Scherm­afbeelding 2023-09-16 om 17 43 55" width="1060" src="https://user-images.githubusercontent.com/36404435/268457114-1c18b5fa-09cc-49fa-a311-02f00faea34a.png">

I can't open this link, can you check it on your end?

**Comment by hash889900** [comment]
checker:manualTrigger

**Comment by hash889900** [comment]
> Hello,
> 
> I finally managed to download a deal from you and made it available here:
> 
> http://www.datasetcreators.com/downloadedcarfiles/2100-f02367308-f02062851-51706496-baga6ea4seaqf23rem6of45qvylatl6ve7rxlj4ujnul5lgcermpgokap6b6zmmq
> 
> This data does not match the same data you provided. Can you explain?
> 
> <img alt="Scherm­afbeelding 2023-09-16 om 17 43 55" width="1060" src="https://user-images.githubusercontent.com/36404435/268457114-1c18b5fa-09cc-49fa-a311-02f00faea34a.png">

I asked our techs and looked at our database, the data is some small amount of encrypted data we have in-house and uploaded it to filecoin in order to familiarize ourselves with and validate the process, you can view the data after September and it is all compliant

**Comment by cryptowhizzard** [comment]
"Data Type of Application:
Public, Open Dataset (Research/Non-Profit)"

I'm sorry , but this is what your application stated. I will leave the dispute as is.

**Comment by Lind111** [comment]
> "Data Type of Application: Public, Open Dataset (Research/Non-Profit)"
> 
> I'm sorry , but this is what your application stated. I will leave the dispute as is.

This was my first application, because the previous public data was not ready, so I used encrypted data to do the whole process of testing, including retrieval, and after the test was OK, I started the public data storage in September

**Comment by hash889900** [comment]
> "Data Type of Application: Public, Open Dataset (Research/Non-Profit)"
> 
> I'm sorry , but this is what your application stated. I will leave the dispute as is.

This was my first application, because the previous public data was not ready, so I used encrypted data to do the whole process of testing, including retrieval, and after the test was OK, I started the public data storage in September

**Comment by cryptowhizzard** [comment]
Again,

The data you stored was not the data you said you would be storing.

I suggest closing this application and open a new one to try again.

**Comment by hash889900** [comment]
> Again,
> 
> The data you stored was not the data you said you would be storing.
> 
> I suggest closing this application and open a new one to try again.

@cryptowhizzard Reapplying is a pain in the ass, if this is objectionable can I request an official to intervene?

**Comment by hash889900** [comment]
@Sunnyiscoming Hi, please check the previous replies and can you give me a suggestion? Thank you!!!

**Comment by hash889900** [comment]
checker:manualTrigger

**Comment by hash889900** [comment]
checker:manualTrigger

**Comment by hash889900** [comment]
checker:manualTrigger

**Comment by hash889900** [comment]
checker:manualTrigger

**Comment by Lind111** [comment]
checker:manualTrigger

**Comment by hash889900** [comment]
A new application will be submitted
