### ISSUE TITLE
[DataCap Application] <Zhejiang Nano Cloud Chain Technology Co., Ltd.> - <Enterprise public data>

### ISSUE THREAD

**Issue by zhengxiangjinnano** [filecoin-project/filecoin-plus-large-datasets#2103]
### Data Owner Name

Zhejiang Nano Cloud Chain Technology Co., Ltd.

### What is your role related to the dataset

Dataset Owner

### Data Owner Country/Region

China

### Data Owner Industry

Information, Media & Telecommunications

### Website

http://www.hzhengtong.com/

### Social Media

```text
WeChat public account：NanoCloudChain
```

### Total amount of DataCap being requested

5PiB

### Expected size of single dataset (one copy)

500T

### Number of replicas to store

10

### Weekly allocation of DataCap requested

500TiB

### On-chain address for first allocation

f1srowruir6fcwwjs44c7wdlmoddb3dy7fym6vg4i

### Data Type of Application

Public, Open Commercial/Enterprise

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Zhejiang Nano Cloud Chain is a professional & high-tech service company committed to offer solutions such as cloud computing virtualization, cloud computing (private and public cloud), large data agile BI, IT operations management, product development process management, static source code security detection products, data management and desensitization bleaching, data backup, disaster, security, audio recording, load balancing, storage and private network backup, letter a whole stack products, block chain research and development for information center.
First of all, we have been offering virtual data center solutions, virtual desktop solutions and cloud computing services since establishment. We have worked hard in these fileds for over 11 years and win clients' trust with our profession and reliability, becoming the lead er in this industry.
Besides, We provide our customers with visual big data agile management, big data solutions, help customers dig deeply into the value of data, and promote the new development of Internet information. We through IT operation and maintenance management software and product development process management implement ation services, to provide customers with network and system monitoring platform and ITIL, RESEARCH and development process consulting and landing technical services.
In additional, We provide customers with full stack products that affect national economic development and independent security and control, such as underlying CPU, operating system, database, middleware and so on. In particular, the kirin software solution of the underlying operating system has been Extensively promoted in major banks, and gradually promoted to all small and medium-sized banks in the province in order to form a replicable business system model.
Last but not the least, Our blockchain R&D team has independently developed a blockchain hybrid platform to support heterogeneous multi-chain deployment for customers, and with this as the core, it deeply cuts into the four fields of finance, government affairs, industrial supply the chain and people's livelihood, and uses blockchain technology to break data islands, reshape path dependence and broaden business boundaries.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
Data stored on Filecoin is mainly customer data, such as BI reports, service data backup, mail data, audio and video data.
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### How do you plan to prepare the dataset

IPFS, lotus

### Please share a sample of the data

```text
https://drive.google.com/file/d/1O0cBcSqzDSKoVO1SAWrN7u_C4ZTfZaRZ/view?usp=sharing

https://drive.google.com/file/d/1ZJ0poSz_LXkYbu0oXRhy-uQ8i4R-o1_a/view?usp=sharing

https://drive.google.com/file/d/1jFWv2CwAY7w_X3zcNug1zdgmSA1hwzH-/view?usp=sharing

https://drive.google.com/file/d/1a06Ndsn1HksVFgRY674pYrjyxdaKRcyd/view?usp=sharing

https://drive.google.com/file/d/1Zr3d-yrwcrzmdpmzMh6R5EKzKwbZKkb7/view?usp=sharing

https://drive.google.com/file/d/1lrDU8CRIZ7jVAJqFNN3Jz8i_vja6HBvo/view?usp=sharing

https://drive.google.com/file/d/1_q4qN_FYsZ8M2bZyORqR4xDTcJrt1tCV/view?usp=sharing

https://drive.google.com/file/d/1JRLTBscpZyClhITEPlSVYVGcjTwcYcBR/view?usp=sharing

https://drive.google.com/file/d/1AghHDWKvFkgrDpoxQRliH5uTpFkhltOm/view?usp=sharing

https://drive.google.com/file/d/13KV_7JTs812jnAG349aPM5oEzIjNvikK/view?usp=sharing

https://drive.google.com/file/d/1hnn5QBcrJKvZwWpgEHiaLKHMHh8t7jDh/view?usp=sharing

https://drive.google.com/file/d/1JQoBAjWF9TGtDVinQphqlJBv71Bxi-ZU/view?usp=sharing

https://drive.google.com/file/d/1Of2lgeEinxyIA-tBW6veci-COshbDAhU/view?usp=sharing

https://drive.google.com/file/d/1ZxqHLNUtL-mgO74KymNsM06yiwktINVY/view?usp=sharing

https://drive.google.com/file/d/1UjDSy8E1cM_z9tfkUBoj3om4S3qNQuPX/view?usp=sharing

https://drive.google.com/file/d/1-BRCaGx0hrA67bYhMoirbQutZrqaYezr/view?usp=sharing

https://drive.google.com/file/d/1uJWBF4VDs7n3EYokUV8rMtcRcmr4OpJ7/view?usp=sharing

https://drive.google.com/file/d/11yVsVFWNCJNcKIqs83a4FO_Ai3fkQ4pn/view?usp=sharing
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

1.5 to 2 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America

### How will you be distributing your data to storage providers

Cloud storage (i.e. S3), HTTP or FTP server, Shipping hard drives

### How do you plan to choose storage providers

Slack, Big Data Exchange, Partners

### How do you plan to make deals to your storage providers

Boost client, Lotus client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by herrehesse** [comment]
The initial request for 5 PiB using a newly created account and without establishing trust within the community is concerning. I highly recommend close the application and reconsider by starting with a smaller amount to build credibility and trust before making larger requests.

Advising notaries not to engage.

**Comment by Sunnyiscoming** [comment]
Best practice for storing large datasets includes ideally, storing it in 3 or more regions, with 4 or more storage provider operators or owners.
You should list Miner ID, Business Entity, Location of sps you will cooperate with.

Could you send an email to filplus-app-review@fil.org with your official domain in order to confirm your identity? Email name should includes the issue id #2103.

Can you provide more evidence to prove that you have 500 TB data already?

**Comment by Filplus-govteam** [comment]
Hello @zhengxiangjinnano per the guideline https://github.com/filecoin-project/notary-governance/issues/922 for Open Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and data owner and also please add the contact information of the SP entities you are working with to store copies of the data.

This information will be reviewed by Fil+ Governance team to confirm validity and then the application will be triggered for notary review. Let us know if you have any questions.

**Comment by Sunnyiscoming** [comment]
Any update here?

**Comment by zhengxiangjinnano** [comment]
@Sunnyiscoming 
Hello, we have sent the email, please check. Plus, the data we've got ready。

![f13cdb8275b7a88e08ff76d94bf9dd1](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/139352142/a7c27894-7ccd-4f1b-b160-3a06d09f1803)

**Comment by zhengxiangjinnano** [comment]
@Filplus-govteam Hello, we have submitted the form information

**Comment by Filplus-govteam** [comment]
I don't see the form. 

You can show the 3-5 SP entities that are storing the data in a distributed way? id, entity, location

**Comment by zhengxiangjinnano** [comment]
Hello, @Filplus-govteam 
I confirm that I have already submitted the form. Now, I will list the first batch of cooperating SPs below: 

[f01854772
Los Angeles, California, US
Fiset

f02201020
Shenzhen, Guangdong, CN
polka dot

f02226892
Shenzhen, Guangdong, CN
Blackhole

f02216385
Hong Kong, Central and Western, HK
H&B]

**Comment by Filplus-govteam** [comment]
Just using a quick search we can see that f01854772 was involved in 12+ applications storing duplicate deal data in the past, here are examples:
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/767
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/882
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1469

How has this SP confirmed for you they will store data properly and make retrieveable?

**Comment by cryptowhizzard** [comment]
For the record, I have f01854772 flagged in #962

**Comment by zhengxiangjinnano** [comment]
@cryptowhizzard @Filplus-govteam 
Thank you for keeping me updated on this situation. The SPs have informed me that they have completed the technical adjustments and made optimizations in their data processing workflows. However, I can place the collaboration with them in the second batch, as we are also in communication with two other SPs.
f0861588 SDcloud China
f01988794 Greaterheat

**Comment by Filplus-govteam** [comment]
@zhengxiangjinnano please have SP f01854772 Los Angeles, California, US Fiset email [filplus-app-review@fil.org](mailto:filplus-app-review@fil.org) with proof of location in California

**Comment by zhengxiangjinnano** [comment]
@Filplus-govteam 
Hi, what should I include in email to confirm the location.
Actually, f01854772 will not be include in our plan any more. I have reply in the last week.

----
Here is how it can be proven that a node address is in：

root@Daemon01:~$ lotus net  connect f01854772
f01854772 -> {12D3KooWAxfB5GPndAayRnFAb3XJA2xDrFUGKuMj34U6bsQRd7rn: [/ip4/128.1.112.6/tcp/23450]}
ERROR: failed to parse multiaddr "f01854772": must begin with /

![1691746733547](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/139352142/73863d49-c567-4ead-a196-abe29a7904cd)

**Comment by Filplus-govteam** [comment]
@zhengxiangjinnano last chance - please provide a clear list of SP Entities and distributed locations

**Comment by zhengxiangjinnano** [comment]
@Filplus-govteam 

In conjunction with recent communications, and feedback from the community, we now have the following updated information on the confirmed co-operative sp:|

f02201020    Shenzhen, Guangdong, CN     polka dot
f02226892    Shenzhen, Guangdong, CN     Blackhole
f0861588      China                                        SDcloud
f01988794    Dallas, USA                              Greaterheat
f02239387    hongkong                                 WestWind Ltd.

**Comment by Filplus-govteam** [comment]
ok, thank you @zhengxiangjinnano FYI @Sunnyiscoming

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 5PiB

**Expected weekly DataCap usage rate**
> 500TiB

**Client address**
>f1srowruir6fcwwjs44c7wdlmoddb3dy7fym6vg4i

**Comment by zhengxiangjinnano** [comment]
Due to the long waiting time for the application form, some disclosed nodes are forced to suspend due to a lack of pledge. We'll have to wait for reasons beyond our control until they're ready. The sp that will cooperate with this allocation is as follows: f02274508-H&W-HK; f02320270-R1-US;f02321504-ipollo-US; f02329119-Cryptomage-CN

**Comment by OpenGate01** [comment]
The sample data looks ok, I will support this round if you have done the prep work, after that we will focus on the consistency of the disclosure nodes and the encapsulated nodes including the distribution of the nodes and the success rate of the retrieval, I hope you work according to the rules.

**Comment by zhengxiangjinnano** [comment]
@OpenGate01
Thank you for your response. I confirm that we understand the community rules and have conducted a rigorous selection process for choosing SP partners. We hope to have your support. Thank you.

**Comment by Aaron01230** [comment]
Hello, I've noticed that some notaries have already reviewed this application. Given my review criteria, I need to verify your stored data. Could you please disclose the CID for me to compare against your stored data in the future?

**Comment by zhengxiangjinnano** [comment]
@Aaron01230 
Yes, we will disclose the CID of our stored data for community members to review. We hope to have the support of the notaries.

**Comment by Aaron01230** [comment]
OK，I will support this round and keep paying attention to this LDN

**Comment by Aaron01230** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec6sqoe3atmxlkkcv4iwyj2qpmuh4jgswaoemm5xkujawlxb2dk5c 
#### Address 
> f1srowruir6fcwwjs44c7wdlmoddb3dy7fym6vg4i
#### Datacap Allocated
> 250.00TiB
#### Signer Address
> f1xrnysd4gimg64d4l6qi7ulzwwq22c6vfg6lpw3i
#### Id
> 4c3a1614-2f7f-43e5-ba60-74e855537315
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec6sqoe3atmxlkkcv4iwyj2qpmuh4jgswaoemm5xkujawlxb2dk5c

**Comment by OpenGate01** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebcvipbiga2vtynybue6bbyqbs5utxjidafempetvue2yu4je4wio 
#### Address 
> f1srowruir6fcwwjs44c7wdlmoddb3dy7fym6vg4i
#### Datacap Allocated
> 250.00TiB
#### Signer Address
> f1im4hmtbfzqnx7ir74kdaiu4ynjhgqh3sdi2snla
#### Id
> 4c3a1614-2f7f-43e5-ba60-74e855537315
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebcvipbiga2vtynybue6bbyqbs5utxjidafempetvue2yu4je4wio

**Comment by mikezli** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaa3gkictwct3i432lvbhhmbbd6tgvi2pk5k4lolqrh3u32ub7a7m 
#### Address 
> f1srowruir6fcwwjs44c7wdlmoddb3dy7fym6vg4i
#### Datacap Allocated
> 250.00TiB
#### Signer Address
> f1dnb3uz7sylxk6emti3ififcvu3nlufnnsjui6ea
#### Id
> 4c3a1614-2f7f-43e5-ba60-74e855537315
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaa3gkictwct3i432lvbhhmbbd6tgvi2pk5k4lolqrh3u32ub7a7m

**Comment by maxvint** [comment]
checker:manualTrigger

**Comment by 1ane-1** [comment]
checker:manualTrigger

**Comment by 1ane-1** [comment]
Retrieval rate is ok, But Deal Data Replication problem- How will you deal it?

**Comment by zhengxiangjinnano** [comment]
@maxvint @1ane-1 
Hello, are you a notary?
As the check bot shows, our data preparation and distribution are compliant, but the sp progress cannot be completely unified, and the bot will display normal as time updates.
Hope to get everyone's support.

**Comment by 1ane-1** [comment]
> @maxvint @1ane-1 Hello, are you a notary public? As the check bot shows, our data preparation and distribution are compliant, but the sp progress cannot be fully unified, and the bot will display normal as time updates (two bot triggers can prove it, because their ratio continues to decline ) Hope to get everyone's support.

Support for this round

**Comment by 1ane-1** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebahhndqazjcvz2rlfxapu3p6boobvfqwni4shjqkoayevkwlej5y 
#### Address 
> f1srowruir6fcwwjs44c7wdlmoddb3dy7fym6vg4i
#### Datacap Allocated
> 500.00TiB
#### Signer Address
> f1mdk7s2vntzm6hu35yuo6vjubtrpfnb2awhgvrri
#### Id
> a90c0c9b-be99-4306-b94a-f35aeef752ee
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebahhndqazjcvz2rlfxapu3p6boobvfqwni4shjqkoayevkwlej5y

**Comment by maxvint** [comment]
> @maxvint @1ane-1 Hello, are you a notary public? As the check bot shows, our data preparation and distribution are compliant, but the sp progress cannot be fully unified, and the bot will display normal as time updates (two bot triggers can prove it, because their ratio continues to decline ) Hope to get everyone's support.

Cool, willing to support this round.

**Comment by maxvint** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecwta35gq3nqfwlozyjckvadfz2cc4b53rzqyn3a6n2wsy7qsue2a 
#### Address 
> f1srowruir6fcwwjs44c7wdlmoddb3dy7fym6vg4i
#### Datacap Allocated
> 500.00TiB
#### Signer Address
> f1ui5iy4mmkxjbw7752omiwp2ols2fzv4thrayagi
#### Id
> a90c0c9b-be99-4306-b94a-f35aeef752ee
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecwta35gq3nqfwlozyjckvadfz2cc4b53rzqyn3a6n2wsy7qsue2a

**Comment by cryptowhizzard** [comment]
Dear zhengxiangjinnano,

As notary I am doing due diligence on your LDN. I could not get retrieval to work. Can you please upload the car file of CID baga6ea4seaqhicwhxwy5zajbf2tnu7y6x7ofjgxprl5gqoikqb35on27kf6miia ?

You can use our upload system at http://send.datasetcreators.com. Please select 7 days for the system to keep the file and post the link you received here so I (and other notaries) can download your content.

**Comment by kevzak** [comment]
checker:manualTrigger

**Comment by zhengxiangjinnano** [comment]
@kevzak 
We confirm that we have contacted more than 4 SPs.

SPs taking deals:
f02328179 | Chengdu, Sichuan, CNCHINA UNICOM China169 Backbone | BigMax   3.30%
f02274508 | Hong Kong, Central and Western, HKChina Unicom Global | H&W   22.48%
f02359258 | Shenzhen, Guangdong, CNCHINANET-BACKBONE | 66File  9.95%
f02329119 | Hangzhou, Zhejiang, CNCT-HangZhou-IDC | Cryptomage   8.20%
f02320312 | Los Angeles, California, USZenlayer Inc | R1       11.26%
f02327534 | Los Angeles, California, USZenlayer Inc | ipollo   11%
f02322031 | Los Angeles, California, USZenlayer Inc | ipollo    11%
f02321504 | Los Angeles, California, USZenlayer Inc | ipollo      11%
f02320270 | Los Angeles, California, USZenlayer Inc | R1           11%
f01834291 | Los Angeles, California, USZenlayer Inc | 51 miner   0.03%

**Comment by zhengxiangjinnano** [comment]
@cryptowhizzard 
Dear Notary,

I encountered an issue when trying to upload a file. It said the file is too large. Additionally, I have conducted retrieval tests on the file, and I can confirm that it is functional. For example: 

http://65.255.36.78:22002/piece/baga6ea4seaqp3eecjeznreymjtnikmmyw4ib6zkespmiprdzuyp453kja6ofqli
http://65.255.36.78:22002/piece/baga6ea4seaqkq5tp5ffofbmjsyrf4m23nfqtd5z7iyweofvdabcctgcbwpovwgy
http://65.255.36.78:22002/piece/baga6ea4seaqo3xidgu2fusi5gex2df63rsa2eifb5wbfeijqkttqttgvwo24qly

**Comment by zhengxiangjinnano** [comment]
@cryptowhizzard 
I'm sorry, I attempted to retrieve the data but failed. You can try retrieving other CIDs for data verification.

**Comment by cryptowhizzard** [comment]
> @cryptowhizzard I'm sorry, I attempted to retrieve the data but failed. You can try retrieving other CIDs for data verification.

No.

I specifically asked you for a random one to a check.

**Comment by zhengxiangjinnano** [comment]
@cryptowhizzard 
In cases where the retrieval rate is not 100%, there is a possibility of failure when randomly selecting a CID. So, if the CID you randomly checked cannot be retrieved, please randomly select another CID. As far as I know, the community has not currently required a 100% retrieval rate, considering factors such as network conditions can affect retrieval.

**Comment by cryptowhizzard** [comment]
> @cryptowhizzard
> In cases where the retrieval rate is not 100%, there is a possibility of failure when randomly selecting a CID. So, if the CID you randomly checked cannot be retrieved, please randomly select another CID. As far as I know, the community has not currently required a 100% retrieval rate, considering factors such as network conditions can affect retrieval.

I can select 10 other random ones if you want to?

**Comment by cryptowhizzard** [comment]
Dear zhengxiangjinnano,

As notary I am doing due diligence on your LDN. I could not get retrieval to work. Can you please upload the car file of CID baga6ea4seaqmov3h7tf6itpdvfw3rbj2eago7nxwahxiweuo4qewk3d5hgfvuny ?

You can use our upload system at http://send.datasetcreators.com. Please select 7 days for the system to keep the file and post the link you received here so I (and other notaries) can download your content.

**Comment by cryptowhizzard** [comment]
Dear zhengxiangjinnano,

As notary I am doing due diligence on your LDN. I could not get retrieval to work. Can you please upload the car file of CID baga6ea4seaqoqrk4iwmha5aasue67beqbrvjn4p73dc7mfdmkh2pmhgvejmnacy ?

You can use our upload system at http://send.datasetcreators.com. Please select 7 days for the system to keep the file and post the link you received here so I (and other notaries) can download your content.

**Comment by cryptowhizzard** [comment]
Dear zhengxiangjinnano,

As notary I am doing due diligence on your LDN. I could not get retrieval to work. Can you please upload the car file of CID baga6ea4seaqhicwhxwy5zajbf2tnu7y6x7ofjgxprl5gqoikqb35on27kf6miia ?

You can use our upload system at http://send.datasetcreators.com. Please select 7 days for the system to keep the file and post the link you received here so I (and other notaries) can download your content.

**Comment by zhengxiangjinnano** [comment]
checker:manualTrigger

**Comment by zhengxiangjinnano** [comment]
@cryptowhizzard 
The bot shows that we have a 58.6% retrieval rate, meaning that all of this data can be retrieved and you as the notary need to review it, so please download the data yourself.
Also, again. With a retrieval rate that is not 100%, it is possible to fail when randomly selecting a CID. So, if the CID you randomly ticked cannot be retrieved, please randomly select another CID. as far as I know, the community is not requesting a 100% retrieval rate at this time.

**Comment by sxxfuture-official** [comment]
checker:manualTrigger

**Comment by sxxfuture-official** [comment]
@zhengxiangjinnano  The retrieval rate looks good, but according to the analysis results of the CID check report, if you want to maintain the health of the project in the next, you must increase the number of data replicas.

**Comment by sxxfuture-official** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec5yfa3oju4oh2uarb72e7bbfrm43nxwbvdn2vlvjimo2mh6jwioo 
#### Address 
> f1srowruir6fcwwjs44c7wdlmoddb3dy7fym6vg4i
#### Datacap Allocated
> 500.00TiB
#### Signer Address
> f1foiomqlmoshpuxm6aie4xysffqezkjnokgwcecq
#### Id
> a90c0c9b-be99-4306-b94a-f35aeef752ee
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec5yfa3oju4oh2uarb72e7bbfrm43nxwbvdn2vlvjimo2mh6jwioo

**Comment by zhengxiangjinnano** [comment]
@sxxfuture-official 
Thanks for the reminder, we'll be contacting more sp's for storage as the amount of data stored becomes larger

**Comment by zhengxiangjinnano** [comment]
checker:manualTrigger

**Comment by woshidama323** [comment]
LGTM， a very healthy one 
Will support

**Comment by woshidama323** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec2tla3i33qyih3gxmfu5ejo5li2nnj4fifpuax6eh7mc7gwrrj32 
#### Address 
> f1srowruir6fcwwjs44c7wdlmoddb3dy7fym6vg4i
#### Datacap Allocated
> 1.95PiB
#### Signer Address
> f12tk3adljauwnd3hjbigpfxb7b7gdlj63p6afwtq
#### Id
> 7f522951-2259-4f3d-994f-7e5936c7f501
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec2tla3i33qyih3gxmfu5ejo5li2nnj4fifpuax6eh7mc7gwrrj32

**Comment by AlanGreaterheat** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceahz6g5mg7cowns6xpjlk3cmjm7o7yf6u3gq3gwwy5bbzhrjgqmpq 
#### Address 
> f1srowruir6fcwwjs44c7wdlmoddb3dy7fym6vg4i
#### Datacap Allocated
> 1.95PiB
#### Signer Address
> f1pnmzlxj7cfeo2v6oj5nco46hkg2l46wj7o4xxui
#### Id
> 7f522951-2259-4f3d-994f-7e5936c7f501
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceahz6g5mg7cowns6xpjlk3cmjm7o7yf6u3gq3gwwy5bbzhrjgqmpq

**Comment by zhengxiangjinnano** [comment]
Request number 4 did not take effect and requires the notary to sign again.

**Comment by woshidama323** [comment]
Will sign again because of known issue

**Comment by woshidama323** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced6dg7ua6qb2n6s6hb5cjj4mdmucak5qslu6neictsns2fporqgxg 
#### Address 
> f1srowruir6fcwwjs44c7wdlmoddb3dy7fym6vg4i
#### Datacap Allocated
> 1.95PiB
#### Signer Address
> f12tk3adljauwnd3hjbigpfxb7b7gdlj63p6afwtq
#### Id
> 22f2221f-3bab-4569-9dc5-2c89f907fc84
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced6dg7ua6qb2n6s6hb5cjj4mdmucak5qslu6neictsns2fporqgxg

**Comment by AlanGreaterheat** [comment]
Last signature not valid, re-sign

**Comment by AlanGreaterheat** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedhs5fhu4uoq4ttqberxzvht4kfr2pxjpo2xat4uifobxb44mdunm 
#### Address 
> f1srowruir6fcwwjs44c7wdlmoddb3dy7fym6vg4i
#### Datacap Allocated
> 1.95PiB
#### Signer Address
> f1pnmzlxj7cfeo2v6oj5nco46hkg2l46wj7o4xxui
#### Id
> 22f2221f-3bab-4569-9dc5-2c89f907fc84
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedhs5fhu4uoq4ttqberxzvht4kfr2pxjpo2xat4uifobxb44mdunm

**Comment by jomozz** [comment]
checker:manualTrigger

**Comment by jomozz** [comment]
@zhengxiangjinnano the report shows that 45.71% of deals are for data replicated across less than 4 storage providers. If you want to keep the project healthy, make adjustments to the distribution of data.

**Comment by zhengxiangjinnano** [comment]
@jomozz, thank you for the reminder, but from the data displayed by the bot, it doesn't appear to be the most up-to-date. Our backups have been allocated in full compliance with the community rules. You'll see this once the bot's data is updated.

**Comment by jomozz** [comment]
> @jomozz, thank you for the reminder, but from the data displayed by the bot, it doesn't appear to be the most up-to-date. Our backups have been allocated in full compliance with the community rules. You'll see this once the bot's data is updated.

I will support for this round, please keep your word.

**Comment by jomozz** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebcrdygcjzwwslyjevee5zue7n6ugt5hf3serqlny7einsrpwzbpc 
#### Address 
> f1srowruir6fcwwjs44c7wdlmoddb3dy7fym6vg4i
#### Datacap Allocated
> 1.95PiB
#### Signer Address
> f1qpdwt2f2fse74nl5wi27uk5jcyqqqyil47yqt7i
#### Id
> 22f2221f-3bab-4569-9dc5-2c89f907fc84
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebcrdygcjzwwslyjevee5zue7n6ugt5hf3serqlny7einsrpwzbpc

**Comment by luobin544** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaxwu5krz5f3ov4jpv2vfmc25i26ujaqndmhwfmgzmlei7nhyjhdm 
#### Address 
> f1srowruir6fcwwjs44c7wdlmoddb3dy7fym6vg4i
#### Datacap Allocated
> 1.95PiB
#### Signer Address
> f1tbd632f6w62glfaf7wjpimacbnjiz26poyoes2q
#### Id
> 22f2221f-3bab-4569-9dc5-2c89f907fc84
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaxwu5krz5f3ov4jpv2vfmc25i26ujaqndmhwfmgzmlei7nhyjhdm

**Comment by zhengxiangjinnano** [comment]
Project application completed, ready to close application form
