### ISSUE TITLE
[DataCap Application] <FanjingAR> - <FanjingAR Data>

### ISSUE THREAD

**Issue by fanjingar** [filecoin-project/filecoin-plus-large-datasets#2105]
### Data Owner Name

Shanghai Fanjing AR Technology LTD

### What is your role related to the dataset

Dataset Owner

### Data Owner Country/Region

China

### Data Owner Industry

IT & Technology Services

### Website

http://www.fanjing-ar.com/

### Social Media

```text
http://www.fanjing-ar.com/
```

### Total amount of DataCap being requested

5PiB

### Expected size of single dataset (one copy)

0.625PiB

### Number of replicas to store

8

### Weekly allocation of DataCap requested

500TiB

### On-chain address for first allocation

f1yloa4qkoxw2unnaxql63bttks5cmf67uggsvsiq

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Fanjing Technology LTD focuses on the combination of technology and scenes, combining advanced technologies such as face recognition, graphic and image recognition, and voice gesture interaction with customers' actual applications, exploring vertical scenes vertically, expanding industry applications horizontally, and accumulating With advanced experience and scenario application, modularization is gradually realized, appropriate modules are selected according to customer needs, and corresponding software and hardware comprehensive solutions are quickly customized and developed for customers.

Because the application: [https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1937] wallet had some problem and it hadn't been fixed for days, I changed a new wallet and reapplied
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
AR training data
Graphic image recognition training data
Corporate promotion video
design source file
```

### Where was the data currently stored in this dataset sourced from

Other

### If you answered "Other" in the previous question, enter the details here

```text
We purchased Alibaba Cloud Storage, where the data is stored
```

### How do you plan to prepare the dataset

IPFS, lotus, singularity, graphsplit

### Please share a sample of the data

```text
https://drive.google.com/drive/folders/1Mpw9D8aMAgQPnF-PX4ZoHZPKj7DaZaWr?usp=sharing
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

1.5 to 2 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, Africa, North America, South America, Europe, Australia (continent), Antarctica

### How will you be distributing your data to storage providers

Cloud storage (i.e. S3), HTTP or FTP server, IPFS, Shipping hard drives, Lotus built-in data transfer, I don't know yet

### How do you plan to choose storage providers

Slack, Partners

### How do you plan to make deals to your storage providers

Boost client, Lotus client, Bidbot, Singularity

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by fanjingar** [comment]
Hi , guys : 
    Because the  wallet of application   (https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1937) had some problem and it hadn't been fixed for days, I changed a new wallet and reapplied ,  thanks @Kevin-FF-USA @Sunnyiscoming

**Comment by xiangloong** [comment]
How to verify the client, I clicked to verify the client for a long time.

**Comment by herrehesse** [comment]
The initial request for 5 PiB using a newly created account and without establishing trust within the community is concerning. I highly recommend close the application and reconsider by starting with a smaller amount to build credibility and trust before making larger requests.

Advising notaries not to engage.

https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1937

**Comment by Filplus-govteam** [comment]
Hello @fanjingar per the [new guidelines](https://github.com/filecoin-project/notary-governance/issues/922) for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data. 

This information will be reviewed by Fil+ Governance team to confirm validity and then the application will be triggered for notary review. Let us know if you have any questions.

**Comment by fanjingar** [comment]
we will fill this form later

**Comment by Sunnyiscoming** [comment]
Any update here?

**Comment by fanjingar** [comment]
I have submit the form, thanks @Sunnyiscoming

**Comment by fanjingar** [comment]
if you pass this ldn, then you can close 1937, and the bug （https://github.com/keyko-io/filecoin-verifier-frontend/issues/805） don't need to be fixed @Sunnyiscoming

**Comment by Filplus-govteam** [comment]
Confirming the following SP Entities were submitted:
f01920887 sunpool Australia
f02257610 sunpool Australia
f02274504 sunpool Australia
f02294456 sunpool Australia
f02246008 guotaicloud China
f02294456 TreesTech Singapore
f02274504 NA  China
f02182798 NA  China

We are contacting SPs to confirm location.

**Comment by Aaron01230** [comment]
We only submitted 5 SPs , and they are : 
f02246008 China,  
f01920887 Australia,  
f02294456 Singapore,  
f02274504 China,  
f02182798  China

**Comment by fanjingar** [comment]
We only submitted 5 SPs , and they are :
f02246008 China,
f01920887 Australia,
f02294456 Singapore,
f02274504 China,
f02182798 China

**Comment by fanjingar** [comment]
I contacted these SPs, and they replied that they did not receive the email, please check again, whether it was sent to the following emails:
ssnk6227@gmail.com
szguosetianzi@gmail.com
melodymusicog@gmail.com
noahlee90418@gmail.com
changnanhao@gmail.com

**Comment by fanjingar** [comment]
> Confirming you submitted business email proof earlier: [#1937 (comment)](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1937#issuecomment-1518928038)

yes ,i confirm that i have submitted business email proof earlier : https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1937#issuecomment-1518928038
@Filplus-govteam

**Comment by Filplus-govteam** [comment]
OK thank you @fanjingar . FYI @Sunnyiscoming

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 5PiB

**Expected weekly DataCap usage rate**
> 500TiB

**Client address**
>f1yloa4qkoxw2unnaxql63bttks5cmf67uggsvsiq

**Comment by Aaron01230** [comment]
The client contacted me and based on the comments above and the information provided, I would like to support this round

**Comment by Aaron01230** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedvtpz7tq2re2vhihi6swt72hilthcjkzdp25l2z23qvcut5nc6go 
#### Address 
> f1yloa4qkoxw2unnaxql63bttks5cmf67uggsvsiq
#### Datacap Allocated
> 250.00TiB
#### Signer Address
> f1xrnysd4gimg64d4l6qi7ulzwwq22c6vfg6lpw3i
#### Id
> 7931cfca-ca4d-4d88-9131-faff08f78eae
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedvtpz7tq2re2vhihi6swt72hilthcjkzdp25l2z23qvcut5nc6go

**Comment by ipollo00** [comment]
Fine, will follow up on whether the allocation of sps is real.

**Comment by ipollo00** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceay3nciewrfe3mi2sg5beyyeczzopfnjknssnzmkgnkbmj36dcam6 
#### Address 
> f1yloa4qkoxw2unnaxql63bttks5cmf67uggsvsiq
#### Datacap Allocated
> 250.00TiB
#### Signer Address
> f1n5wlrrhoxpkgwij25xrtt7w7g2k3fhbthmdn6ri
#### Id
> 7931cfca-ca4d-4d88-9131-faff08f78eae
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceay3nciewrfe3mi2sg5beyyeczzopfnjknssnzmkgnkbmj36dcam6

**Comment by cryptowhizzard** [comment]
It seems you are working with 2 SP's.

f02274504 is not eligible for FIL+ . According to the retrieval bot they do not support retrieval in all applications they have been involved in. Please stop sending deals to them.

<img width="1139" alt="Scherm­afbeelding 2023-08-24 om 19 59 49" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/36404435/8cd242e5-cd57-4f89-b19f-126f9517ea40">

**Comment by kevzak** [comment]
checker:manualTrigger

**Comment by cryptowhizzard** [comment]
ERROR: offer error: retrieval query offer errored: failed to fetch piece to retrieve from: getting pieces for cid bafykbzacebn3vcbqgjnvdrxicl4do326ncldagnatjwcxunntfezznnlm4vvi: getting pieces containing block bafykbzacebn3vcbqgjnvdrxicl4do326ncldagnatjwcxunntfezznnlm4vvi: failed to lookup index for mh a0e402205bba8830325b51c6e812f8376f5e68963019a09a6c2bd1ad99499cb5ab672b54, err: datastore: key not found

ERROR: offer error: retrieval query offer errored: failed to fetch piece to retrieve from: getting pieces for cid bafykbzacebn3vcbqgjnvdrxicl4do326ncldagnatjwcxunntfezznnlm4vvi: getting pieces containing block bafykbzacebn3vcbqgjnvdrxicl4do326ncldagnatjwcxunntfezznnlm4vvi: failed to lookup index for mh a0e402205bba8830325b51c6e812f8376f5e68963019a09a6c2bd1ad99499cb5ab672b54, err: datastore: key not found

**Comment by cryptowhizzard** [comment]
Dear fanjingar,

As notary I am doing due diligence on your LDN. I could not get retrieval to work. Can you please upload the car file of CID baga6ea4seaqnz33jgt7gihexmxnvj7rssy3s6zg6w5q7drf4hdfgoxn5r2sbqoa ?

You can use our upload system at http://send.datasetcreators.com. Please select 7 days for the system to keep the file and post the link you received here so I (and other notaries) can download your content.

**Comment by Aaron01230** [comment]
checker:manualTrigger

**Comment by fanjingar** [comment]
I have contact the sp , and they fix the problem , here are the retrieve results:
![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/130625217/71388a26-3e43-4016-b3e9-a8ecefb9c645)
<img width="965" alt="image" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/130625217/8f0377f5-c8f9-432c-9999-f6c9b1f469b9">

**Comment by stcouldlisa** [comment]
It looks like retrieval has been fixed 

> I have contact the sp , and they fix the problem , here are the retrieve results: ![image](https://user-images.githubusercontent.com/130625217/267613847-71388a26-3e43-4016-b3e9-a8ecefb9c645.png) <img alt="image" width="965" src="https://user-images.githubusercontent.com/130625217/267613905-8f0377f5-c8f9-432c-9999-f6c9b1f469b9.png">

**Comment by stcouldlisa** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebdgerissajd6spbu3m6p6h6pwi5p2jhsu2jc7v2xv2r7f6mdhdn4 
#### Address 
> f1yloa4qkoxw2unnaxql63bttks5cmf67uggsvsiq
#### Datacap Allocated
> 500.00TiB
#### Signer Address
> f1jvvltduw35u6inn5tr4nfualyd42bh3vjtylgci
#### Id
> 0ef46080-9f3d-4d65-a6a5-8ac778b9d024
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebdgerissajd6spbu3m6p6h6pwi5p2jhsu2jc7v2xv2r7f6mdhdn4

**Comment by fanjingar** [comment]
> SPs provided: f02246008 China, f01920887 Australia, f02294456 Singapore, f02274504 China, f02182798 China
> 
> SPs taking deals: f02363300 | Tokyo, Tokyo, JPAmazon.com, Inc. | 94.34 TiB | 38.15% | 94.34 TiB | 0.00% f02274504 | Shenzhen, Guangdong, CNCTGNet | 91.06 TiB | 36.82% | 91.06 TiB | 0.00% f02122388 | Shenzhen, Guangdong, CNCTGNet | 61.91 TiB | 25.03% | 61.91 TiB | 0.00%
> 
> @fanjingar one SP matches what you provided. Please confirm SPs entities you are working with.

I am sorry that the situation has changed. The previously listed SPs failed to cooperate with us due to some reasons. We have found two more SPs. Their node numbers are: f02807399, f02363306. 
I will continue to look for new SPs and prompt them here in time.

**Comment by stcouldlisa** [comment]
@fanjingar Hi, you also need to solve the problem of data backup

**Comment by cryptowhizzard** [comment]
@stcouldlisa 

Can you clarify why you signed against rules and guidlines set in https://github.com/filecoin-project/notary-governance/issues/922

Secondly I was doing due diligence and inspection of data?

**Comment by cryptowhizzard** [comment]
<img width="1230" alt="Scherm­afbeelding 2023-09-13 om 22 24 17" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/36404435/0f0c6686-4bd6-45dc-826a-da90f3b0b496">

Only one of 3 SP's provides is open for retrieval here........

**Comment by cryptowhizzard** [comment]
@fanjingar @stcouldlisa 

This application does not meet guidelines in any way. The 2 CN SP's are on the same IP adres and are not open for retrieval in any way. The node in Japan is the only one connectable and that one is not on the list as SP's who are used in this LDN.

**Comment by cryptowhizzard** [comment]
<img width="673" alt="Scherm­afbeelding 2023-09-13 om 22 33 33" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/36404435/3bd719ca-c9ee-4499-88fa-c0c0d82a37ed">

@Filplus-govteam please provide your input.

**Comment by fanjingar** [comment]
> <img alt="Scherm­afbeelding 2023-09-13 om 22 24 17" width="1230" src="https://user-images.githubusercontent.com/36404435/267780546-0f0c6686-4bd6-45dc-826a-da90f3b0b496.png">
> Only one of 3 SP's provides is open for retrieval here........

Is that mean the retrieval rate should be 100%?

**Comment by cryptowhizzard** [comment]
> > <img alt="Scherm­afbeelding 2023-09-13 om 22 24 17" width="1230" src="https://user-images.githubusercontent.com/36404435/267780546-0f0c6686-4bd6-45dc-826a-da90f3b0b496.png">
> > Only one of 3 SP's provides is open for retrieval here........
> 
> Is that mean the retrieval rate should be 100%?

No. It means your application does not meet rules and guidelines

**Comment by fanjingar** [comment]
> > > <img alt="Scherm­afbeelding 2023-09-13 om 22 24 17" width="1230" src="https://user-images.githubusercontent.com/36404435/267780546-0f0c6686-4bd6-45dc-826a-da90f3b0b496.png">
> > > Only one of 3 SP's provides is open for retrieval here........
> > 
> > 
> > Is that mean the retrieval rate should be 100%?
> 
> No. It means your application does not meet rules and guidelines

well，i get it .
<img width="1006" alt="image" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/130625217/a4876cba-0277-4db2-ad1e-d37cd80b1582">
the report shows 2 nodes can be retrieved, and i will stop to corperate with the one which can't be retrieved.

**Comment by woshidama323** [comment]
@fanjingar Please update the latest info ASAP 
I can support this first

**Comment by woshidama323** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceadnrczkwqxrfpffehfteult4edevmvrksxccmuabnptz6gexxct6 
#### Address 
> f1yloa4qkoxw2unnaxql63bttks5cmf67uggsvsiq
#### Datacap Allocated
> 500.00TiB
#### Signer Address
> f12tk3adljauwnd3hjbigpfxb7b7gdlj63p6afwtq
#### Id
> 0ef46080-9f3d-4d65-a6a5-8ac778b9d024
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceadnrczkwqxrfpffehfteult4edevmvrksxccmuabnptz6gexxct6

**Comment by kevzak** [comment]
Closing for violation of 922 and until @fanjingar clarifies clear list of SP IDs, entities, and locations upfront.
