### ISSUE TITLE
[DataCap Application]EagleGame

### ISSUE THREAD

**Issue by ubuckvnockai** [filecoin-project/filecoin-plus-large-datasets#211]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Boong
- Website / Social Media:https://eaglegame.club/index ; https://twitter.com/EagleGameDAO ; https://www.element.market/collections/Eaglegame_Mintpass
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):200TiB
- On-chain address for first allocation:f1gs2dha7gjpiqw34o32aaqr6anyzkcrq2tjpmjvi

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
BOONG is the most professional NFT and GAMEFI technical service team in Asia, dedicated to making NFT a way of communication and using NFT to open the door to the future crypto world. BOONG is always open-minded and has already reached strategic cooperation with many famous NFT platforms such as opensea, element, bakeryswap, etc. The world of crypto art should have no borders, as long as the art is beautiful, it is the world. BOONG is the NFT project operation one-stop service team about NFT design, NFT synthesis, NFT contract deployment, NFT-DAPP building, NFT distribution, NFT trading. We can also work with well-known or non-famous traffic IPs, and we can escort technical support services.
```

What is the primary source of funding for this project?
```
From our shareholders.
```

What other projects/ecosystem stakeholders is this project associated with?
```
No.
```

## Use-case details

Describe the data being stored onto Filecoin
```
Pictures and cartoons which are showed on some platforms.
```

Where was the data in this dataset sourced from?
```
We provide NFT project operation one-stop service, so it will produce amount of data to store.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
![Boongeagleseries](https://user-images.githubusercontent.com/92769092/149752615-5903c9c3-1307-406f-9955-169ff8477a5e.png)

```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes! Confirm!
```

What is the expected retrieval frequency for this data?
```
These data will not be retrieved frequently. Maybe twice a year.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
2 years. Maybe more time.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
China and Korea.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
We want to transfer the data by offline data transfer process. If we have enough network speed, we may choose online process.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We would choose who are interested in our item and who have enough ability to help us store.
```

How will you be distributing deals across storage providers?
```
By distributing no more than 25% to every provider.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes. We can make deals at once.
```

**Comment by IPFSUnion** [comment]
Interesting DAPP. When can you start storing? How many miner nodes do you plan to cooperate？.

**Comment by ubuckvnockai** [comment]
Actually our client is ready for archive a month ago and just waiting for Datacap. Last month, we contacted more than a dozen miners who are interesting of it. As you know the process of datacap approval is quite slow plus the FIL Market changes, there may be 6-8 miners cooperate with us in the first round.

**Comment by IPFSUnion** [comment]
Thanks for your efforts for the clients who are not familiar with filecoin.  Happy to support!

**Comment by dkkapur** [comment]
@ubuckvnockai are you an agent / representative of the client? Any way you can validate that you are working with the right folks who own the data? Also why is 5 PiB of DataCap required for image files? 

If you have already identified the SPs you would like to work with, please make that part of your application as well.

**Comment by dkkapur** [comment]
@ubuckvnockai ping on the above. Thank you!

**Comment by galen-mcandrew** [comment]
Closing for now, please reopen issue if your request is still relevant. Thanks!
