### ISSUE TITLE
[DataCap Application] Public Datasets --- NOAA

### ISSUE THREAD

**Issue by FroghubMan** [filecoin-project/filecoin-plus-large-datasets#2112]
### Data Owner Name

NOAA; 4DN-DCIC; NWGSC; NRC; UBC

### What is your role related to the dataset

Data Preparer

### Data Owner Country/Region

United States

### Data Owner Industry

Other

### Website

http://www.noaa.gov/

### Social Media

```text
https://twitter.com/NOAA
https://twitter.com/4dn_dcic
https://www.facebook.com/EnvironmentandNaturalResourcesinCanada/
https://twitter.com/NRCan
https://www.youtube.com/user/NaturalResourcesCa
```

### Total amount of DataCap being requested

8PiB

### Expected size of single dataset (one copy)

1

### Number of replicas to store

8

### Weekly allocation of DataCap requested

1PiB

### On-chain address for first allocation

f1svst5e6a7b2ux2scyc336mkmdgec3eqthbjtjpa

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
FrogHub has always defined itself as a tool developer and infrastructure builder in the Filecoin ecosystem. In 2019, we started to focus on technical solutions and development based on the IPFS protocol and Filecoin network. We have been working hard to become a qualified builder in the filecoin ecosystem.

Our team is a very pure development team, more than 90% of which are developers, more than half of whom have more than 5 years of development experience in communication, Internet, blockchain and other industries. We hope that we can gain users' recognition by exporting useful tools and platforms.

In order to contribute to the filecoin community, we have developed the open source sector repair tool Filecoin-Sealer-Recover and the nft free authoring platform NFT-Creator.
In addition, we plan to provide a sector browser for the community in 2023 and build the liquidity pledge platform STFIL on FVM.

See the links below for details.
- making: https://github.com/orgs/froghub-io
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
NOAA Coastal Lidar Dataset
Released and archived 4DNucleome data
Nanopore Reference Human Genome
NRT Sentinel data in an S3 bucket broken down by sensor, product type and date.
UBC Sunflower Genome Data 1
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### Please share a sample of the data

```text
https://registry.opendata.aws/noaa-coastal-lidar/
https://registry.opendata.aws/4dnucleome/
https://registry.opendata.aws/nanopore/
https://registry.opendata.aws/sentinel-products-ca-mirror/
https://registry.opendata.aws/ubc-sunflower-genome/
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

2 to 3 years

### In which geographies do you plan on making storage deals

Greater China, North America, Europe

### How will you be distributing your data to storage providers

Cloud storage (i.e. S3), Shipping hard drives

### How do you plan to choose storage providers

Slack, Big Data Exchange, Partners

### How do you plan to make deals to your storage providers

Boost client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
Have you prepared enough token for sector pledge?
Why are you choosing to store it again?
Best practice for storing large datasets includes ideally, storing it in 3 or more regions, with 4 or more storage provider operators or owners.You should list Miner ID, Business Entity, Location of sps you will cooperate with.
Could you send an email to [filplus-app-review@fil.org] with your official domain in order to confirm your identity? Email name should includes the issue id #2112 .

**Comment by FroghubMan** [comment]
1.I am a data preparer, and the SP I am looking for has enough FIL as storage collateral.
2.We want to store valuable data. The data for this application is something we have not stored before.
3.The following are the SPs we have cooperated with.

| MinerID | City | Continent |
| --------- | ---------- | --------- |
| f01811024 | HongKong | CN |
| f0827006 | Tokyo | Japan |
| f02227726 | HongKong | CN |
| f02195153 | Tokyo | Japan |
| f02098006 | Krabi | Thailand |
| f02223012 | Hebei | CN |
| f02235154 | HongKong | CN |
| f02085722 | Jiangmen | CN |

4.I have sent the confirmation email.

**Comment by FroghubMan** [comment]
Hi @Filplus-govteam @Sunnyiscoming ,I have submitted the information in #2119, please review it for me. Thank you very much.

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 8PiB

**Expected weekly DataCap usage rate**
> 1PiB

**Client address**
>f1svst5e6a7b2ux2scyc336mkmdgec3eqthbjtjpa

**Comment by FroghubMan** [comment]
We are preparing the data.

**Comment by FroghubMan** [comment]
Hi @Sunnyiscoming ,We have been preparing data, only to find that it was closed. We have now completed the prep function, can you reopen this application for me?

**Comment by 1ane-1** [comment]
Could you send an email to [[filplus-app-review@fil.org](mailto:filplus-app-review@fil.org)] with your official domain in order to confirm your identity? Email name should includes the issue id https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/2112 .
Could you show your email screenshot above that for us to confirm your identity? Thanks. @FroghubMan

**Comment by FroghubMan** [comment]
![Screenshot_20230831_100248_Gmail](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/88960777/6d8215ca-ba05-43c4-a16c-c04b87f5a37b)

**Comment by Chuangshi1** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceck7huapkgbfo243yjhpp5lqmlcjvtaji5hp73iutmunomh22a45m 
#### Address 
> f1svst5e6a7b2ux2scyc336mkmdgec3eqthbjtjpa
#### Datacap Allocated
> 409.59TiB
#### Signer Address
> f1mdk7s2vntzm6hu35yuo6vjubtrpfnb2awhgvrri
#### Id
> 365d202a-3ba0-4fe2-9e46-81a7ea38149b
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceck7huapkgbfo243yjhpp5lqmlcjvtaji5hp73iutmunomh22a45m

**Comment by ipollo00** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceclulf24bcol3vqp2fp5nbhqeoeowpyeh2yqrpskvygmwsnjtsyhi 
#### Address 
> f1svst5e6a7b2ux2scyc336mkmdgec3eqthbjtjpa
#### Datacap Allocated
> 409.59TiB
#### Signer Address
> f1n5wlrrhoxpkgwij25xrtt7w7g2k3fhbthmdn6ri
#### Id
> 365d202a-3ba0-4fe2-9e46-81a7ea38149b
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceclulf24bcol3vqp2fp5nbhqeoeowpyeh2yqrpskvygmwsnjtsyhi

**Comment by FroghubMan** [comment]
thank you!

**Comment by FroghubMan** [comment]
We're preparing dataset.

**Comment by FroghubMan** [comment]
We're preparing dataset.

**Comment by 1ane-1** [comment]
checker:manualTrigger

**Comment by sxxfuture-official** [comment]
Others look good, please increase the number of data replicas in the subsequent process.

**Comment by sxxfuture-official** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecmsifh3imabr4tosqghhx72ohewonhxobhjp3innel4w2wq6u2sw 
#### Address 
> f1svst5e6a7b2ux2scyc336mkmdgec3eqthbjtjpa
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f1foiomqlmoshpuxm6aie4xysffqezkjnokgwcecq
#### Id
> b00920f9-bc9e-4d65-95e0-d9cabca77333
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecmsifh3imabr4tosqghhx72ohewonhxobhjp3innel4w2wq6u2sw

**Comment by Bitrise0111** [comment]
Check report shows healthy and we'd like to support. We recommand there should be more data backup.

**Comment by Bitrise0111** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb3joewbxwg5ox5sf6i2ieoezg2f7mc4h5rao4h2fi4tox77hwyea 
#### Address 
> f1svst5e6a7b2ux2scyc336mkmdgec3eqthbjtjpa
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f1nknj7ayq4o43czrtdoauggtwl43fbqatmqis3yy
#### Id
> b00920f9-bc9e-4d65-95e0-d9cabca77333
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb3joewbxwg5ox5sf6i2ieoezg2f7mc4h5rao4h2fi4tox77hwyea

**Comment by FroghubMan** [comment]
We're preparing data

**Comment by FroghubMan** [comment]
checker:manualTrigger

**Comment by 1ane-1** [comment]
checker:manualTrigger

**Comment by 1ane-1** [comment]
Report is ok, willing to support this round.

**Comment by 1ane-1** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedafhxisvvzpw7dbywz7oa3piux7344cvv6whxe2usho3bbzqygr6 
#### Address 
> f1svst5e6a7b2ux2scyc336mkmdgec3eqthbjtjpa
#### Datacap Allocated
> 1.00PiB
#### Signer Address
> f1mdk7s2vntzm6hu35yuo6vjubtrpfnb2awhgvrri
#### Id
> fba96cbc-8cc2-44fe-a096-00c9600f4c7a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedafhxisvvzpw7dbywz7oa3piux7344cvv6whxe2usho3bbzqygr6

**Comment by FroghubMan** [comment]
checker:manualTrigger

**Comment by SuperChaiChai** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebycrjeqtrvvcvlycricdtfx5jbil7iplfkjl2vz5ykiqcxyewbp4 
#### Address 
> f1svst5e6a7b2ux2scyc336mkmdgec3eqthbjtjpa
#### Datacap Allocated
> 1.00PiB
#### Signer Address
> f12mckci3omexgzoeosjvstcfxfe4vqw7owdia3da
#### Id
> 194ec683-98c0-4466-aa69-31350eca98ea
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebycrjeqtrvvcvlycricdtfx5jbil7iplfkjl2vz5ykiqcxyewbp4

**Comment by kevzak** [comment]
SPs taking deals

f0870354 | Beijing, Beijing, CNChina Unicom Beijing Province Network | 96.07 TiB | 10.57% | 96.07 TiB | 0.00%
f01989372 | Beijing, Beijing, CNChina Unicom Beijing Province Network | 96.04 TiB | 10.57% | 96.04 TiB | 0.00%
f02816837 | Shenzhen, Guangdong, CNChina Unicom Shenzen network | 29.91 TiB | 3.29% | 29.91 TiB | 0.00%
f01907578 | Xiamen, Fujian, CNCHINANET-BACKBONE | 48.22 TiB | 5.31% | 48.22 TiB | 0.00%
f0123931 | Xiamen, Fujian, CNFuzhou | 80.00 TiB | 8.80% | 80.00 TiB | 0.00%
f02636860 | Hong Kong, Central and Western, HKHKBN Enterprise Solutions HK Limited | 175.86 TiB | 19.35% | 175.86 TiB | 0.00%
f02810687 | Hong Kong, Central and Western, HKHKBN Enterprise Solutions HK Limited | 170.94 TiB | 18.81% | 170.94 TiB | 0.00%
f01854510new | Hong Kong, Central and Western, HKKaopu Cloud HK Limited | 93.03 TiB | 10.24% | 93.03 TiB | 0.00%
f02806894 | Paripark, Seoul, KRThe Constant Company, LLC | 50.78 TiB | 5.59% | 50.78 TiB | 0.00%
f02372022 | Ōi, Saitama, JPThe Constant Company, LLC | 49.45 TiB | 5.44% | 49.45 TiB | 0.00%
f02803754 | Osaka, Ōsaka, JPThe Constant Company, LLC | 18.39 TiB | 2.02% | 18.39 TiB | 0.00%

Original list provided:


f01811024 | HongKong | CN
f0827006 | Tokyo | Japan
f02227726 | HongKong | CN
f02195153 | Tokyo | Japan
f02098006 | Krabi | Thailand
f02223012 | Hebei | CN
f02235154 | HongKong | CN
f02085722 | Jiangmen | CN

@FroghubMan Not seeing any of the original SP IDs matching here, please explain.

**Comment by FroghubMan** [comment]
@kevzak  Thank you for your attention.
The actual allocated miner node is different from the miner node during KYC because if the data preparation time is long, some SPs will first store other available datacaps for the sake of equipment usage efficiency. When the storage power of the miner node reaches a certain value, SPs will consider creating a new miner node. Therefore, over time, changes in the miner node that stores datacap are inevitable.

However, we ensure that everything strictly abides by the rules of FIL+, and we can complete KYC for new nodes if necessary.

**Comment by kevzak** [comment]
Please provide as much information as you can about actual Miner IDs being used and their entities being different and distributed.

**Comment by FroghubMan** [comment]
> Please provide as much information as you can about actual Miner IDs being used and their entities being different and distributed.

Sure. 

| MinerID | Entity | City | Continent |
| --------- | ---------- | ---------- | --------- |
| f0870354 | Personal  | beijing | CN |
| f01989372   | Personal| beijing | CN |
| f02816837   | B.B  Tech| guangdong | CN |
| f01907578  | ssdminer| Putian | CN |
| f0123931   | ssdminer| Fuzhou | CN |
| f02806894   | Chimsen | Seoul | Korea |
| f02372022   | Chimsen | Tokyo | Japan |
| f02810687  | DR66 Tech| HongKong | CN |
| f02636860   | DR66 Tech| HongKong | CN |
| f01854510  | 3cloud tech| HongKong | CN |
| f02803754  | Personal | Osaka | Japan |

**Comment by NiwanDao** [comment]
SP Distribution plan is reasonable. I will support for this round.

**Comment by NiwanDao** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedrfy6q7nokoxevvy3ddgjwc6edeca6oqb4dqliqjf6jplwmifmzo 
#### Address 
> f1svst5e6a7b2ux2scyc336mkmdgec3eqthbjtjpa
#### Datacap Allocated
> 1.00PiB
#### Signer Address
> f1a2lia2cwwekeubwo4nppt4v4vebxs2frozarz3q
#### Id
> 194ec683-98c0-4466-aa69-31350eca98ea
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedrfy6q7nokoxevvy3ddgjwc6edeca6oqb4dqliqjf6jplwmifmzo

**Comment by FroghubMan** [comment]
checker:manualTrigger

**Comment by 1ane-1** [comment]
checker:manualTrigger

**Comment by 1ane-1** [comment]
Looks fine from the report and willing to support.

**Comment by 1ane-1** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebdxvcucx7za5onph6frusbimjrw2fqq4exutkdv5zyuv53wj2yrk 
#### Address 
> f1svst5e6a7b2ux2scyc336mkmdgec3eqthbjtjpa
#### Datacap Allocated
> 2.00PiB
#### Signer Address
> f1mdk7s2vntzm6hu35yuo6vjubtrpfnb2awhgvrri
#### Id
> f5c9f959-d4ce-4686-8134-af13e48fb786
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebdxvcucx7za5onph6frusbimjrw2fqq4exutkdv5zyuv53wj2yrk

**Comment by ipollo00** [comment]
Pretty Good.

**Comment by ipollo00** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedwhx3rawyoeirqghnl2vbhhlox4woxm72jsbr2gpsntgcovozwi6 
#### Address 
> f1svst5e6a7b2ux2scyc336mkmdgec3eqthbjtjpa
#### Datacap Allocated
> 2.00PiB
#### Signer Address
> f1n5wlrrhoxpkgwij25xrtt7w7g2k3fhbthmdn6ri
#### Id
> f5c9f959-d4ce-4686-8134-af13e48fb786
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedwhx3rawyoeirqghnl2vbhhlox4woxm72jsbr2gpsntgcovozwi6

**Comment by FroghubMan** [comment]
We are preparing the data.

**Comment by mikezli** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedyfmr3wnylllnacsnkkcab3yzzopv4z3n4nhcvvf2ompgyyj7nam 
#### Address 
> f1svst5e6a7b2ux2scyc336mkmdgec3eqthbjtjpa
#### Datacap Allocated
> 2.00PiB
#### Signer Address
> f1dnb3uz7sylxk6emti3ififcvu3nlufnnsjui6ea
#### Id
> f5c9f959-d4ce-4686-8134-af13e48fb786
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedyfmr3wnylllnacsnkkcab3yzzopv4z3n4nhcvvf2ompgyyj7nam

**Comment by AlanGreaterheat** [comment]
checker:manualTrigger

**Comment by AlanGreaterheat** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaxqugqtq7qeok4ovjo6mdtef3vf3oucuwuot3nyeqmayyyjdqz56 
#### Address 
> f1svst5e6a7b2ux2scyc336mkmdgec3eqthbjtjpa
#### Datacap Allocated
> 2.00PiB
#### Signer Address
> f1pnmzlxj7cfeo2v6oj5nco46hkg2l46wj7o4xxui
#### Id
> f5c9f959-d4ce-4686-8134-af13e48fb786
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaxqugqtq7qeok4ovjo6mdtef3vf3oucuwuot3nyeqmayyyjdqz56

**Comment by Filplus-govteam** [comment]
@FroghubMan SPs do no match what you submitted. Closing until clarified

**Comment by FroghubMan** [comment]
Hi @Filplus-govteam ,Thank you for your attention. Maybe you missed it I clarified in my reply above.
The actual allocated miner node is different from the miner node during KYC because if the data preparation time is long, some SPs will first store other available datacaps for the sake of equipment usage efficiency. When the storage power of the miner node reaches a certain value, SPs will consider creating a new miner node. Therefore, over time, changes in the miner node that stores datacap are inevitable.

However, we ensure that everything strictly abides by the rules of FIL+, and we can complete KYC for new nodes:

| --------- | ---------- | ---------- | --------- |
| f0870354 | Personal | Beijing, Beijing|  CN| 
| f01989372 | Personal | Beijing, Beijing|  CN| 
| f02816837 | B.B Tech |  Shenzhen, Guangdong|  CN| 
| f02364899 | S&D Tech |  Chengdu, Sichuan|  CN| 
| f02825666 | chimsen  |  Shenzhen, Guangdong|  CN| 
| f02831252 | HCXY Tech |  Jiangmen, Guangdong|  CN| 
| f01708981 | HCXY Tech | Jiangmen, Guangdong|  CN| 
| f01907578 | Personal | Xiamen, Fujian|  CN| 
| f02088858 | chimsen  |  London, England|  GB| 
| f02817995 | 68Tech  | Hong Kong, Central and Western|  HK| 
| f02817992 | 68Tech |  Hong Kong, Central and Western|  HK| 
| f02817993 | 68Tech |  Hong Kong, Central and Western|  HK| 
| f02817991 | 68Tech |  Hong Kong, Central and Western|  HK| 
| f01949260 | ssdminer|  Xiamen, Fujian|  CN| 
| f0123931 | ssdminer | Xiamen, Fujian|  CN| 
| f02810687 | DR66 Tech |   Hong Kong, Central and Western|  HK| 
| f02636860 | DR66 Tech |  Hong Kong, Central and Western| HK| 
| f02051391 | HCXY Tech | Hong Kong, Central and Western|  HK| 
| f02826478 | DD Tech   | Hong Kong, Central and Western|  HK| 
| f02828514 | DD Tech   | Hong Kong, Central and Western|  HK| 
| f01854510 | 3cloud tech|   Hong Kong, Central and Western|  HK| 
| f02806528 | HCXY Tech | Ashburn, Virginia| US| 
| f02806522 | HCXY Tech | HC Ashburn, Virginia|  US| 
| f02838396 | ssdminer | Aberdeen, Southern| HK| 
| f02211244 | ssdminer | Hong Kong, Central and Western|  HK| 
| f02825172 | Personal  |  Bangkok, Bangkok| TH| 
| f02824610 | Personal  |  Bangkok, Bangkok|  TH| 
| f02824414 | DD Tech   | Hong Kong, Central and Western|  HK| 
| f02824865 | DD Tech   | Hong Kong, Central and Western|  HK| 
| f01885088 | S&D Tech  | Hong Kong, Central and Western|  HK| 
| f02372022 | chimsen   | Ōi, Saitama| JP| 
| f02826888 | chimsen   | Toronto, Ontario|  CA| 
| f02827777 | chimsen   | Mumbai, Maharashtra|  IN| 
| f02806894 | chimsen   | Paripark, Seoul| KR| 
| f02803754 | Personal  |  Osaka, Ōsaka|  JP|

**Comment by FroghubMan** [comment]
Hi @Filplus-govteam ,Thank you for your attention. Maybe you missed it I clarified in my reply above.
The actual allocated miner node is different from the miner node during KYC because if the data preparation time is long, some SPs will first store other available datacaps for the sake of equipment usage efficiency. When the storage power of the miner node reaches a certain value, SPs will consider creating a new miner node. Therefore, over time, changes in the miner node that stores datacap are inevitable.

However, we ensure that everything strictly abides by the rules of FIL+, and we can complete KYC for new nodes:

| MinerID | Entity | City | Continent |
| --------- | ---------- | ---------- | --------- |
| f0870354 | Personal | Beijing, Beijing |  CN| 
| f01989372 | Personal | Beijing, Beijing |  CN| 
| f02816837 | B.B Tech |  Shenzhen, Guangdong |  CN| 
| f02364899 | S&D Tech |  Chengdu, Sichuan |  CN| 
| f02825666 | chimsen  |  Shenzhen, Guangdong |  CN| 
| f02831252 | HCXY Tech |  Jiangmen, Guangdong |  CN| 
| f01708981 | HCXY Tech | Jiangmen, Guangdong |  CN| 
| f01907578 | Personal | Xiamen, Fujian |  CN | 
| f02088858 | chimsen  |  London, England|  GB| 
| f02817995 | 68Tech  | Hong Kong, Central and Wester |  HK| 
| f02817992 | 68Tech |  Hong Kong, Central and Western |  HK| 
| f02817993 | 68Tech |  Hong Kong, Central and Western | HK| 
| f02817991 | 68Tech |  Hong Kong, Central and Western |  HK| 
| f01949260 | ssdminer|  Xiamen, Fujian |  CN | 
| f0123931 | ssdminer | Xiamen, Fujian |  CN | 
| f02810687 | DR66 Tech |   Hong Kong, Central and Western |  HK | 
| f02636860 | DR66 Tech |  Hong Kong, Central and Western | HK | 
| f02051391 | HCXY Tech | Hong Kong, Central and Western |  HK | 
| f02826478 | DD Tech   | Hong Kong, Central and Western |  HK | 
| f02828514 | DD Tech   | Hong Kong, Central and Western |  HK | 
| f01854510 | 3cloud tech|   Hong Kong, Central and Western |  HK | 
| f02806528 | HCXY Tech | Ashburn, Virginia | US | 
| f02806522 | HCXY Tech | HC Ashburn, Virginia |  US | 
| f02838396 | ssdminer | Aberdeen, Southern| HK| 
| f02211244 | ssdminer | Hong Kong, Central and Western|  HK | 
| f02825172 | Personal  |  Bangkok, Bangkok | TH | 
| f02824610 | Personal  |  Bangkok, Bangkok |  TH | 
| f02824414 | DD Tech   | Hong Kong, Central and Western |  HK | 
| f02824865 | DD Tech   | Hong Kong, Central and Western |  HK | 
| f01885088 | S&D Tech  | Hong Kong, Central and Western |  HK | 
| f02372022 | chimsen   | Ōi, Saitama| JP | 
| f02826888 | chimsen   | Toronto, Ontario|  CA | 
| f02827777 | chimsen   | Mumbai, Maharashtra |  IN | 
| f02806894 | chimsen   | Paripark, Seoul | KR | 
| f02803754 | Personal  |  Osaka, Ōsaka |  JP |

**Comment by FroghubMan** [comment]
@kevzak @Sunnyiscoming

**Comment by Filplus-govteam** [comment]
@FroghubMan how you are sending copies of the data from China to all of these international locations?

**Comment by FroghubMan** [comment]
Hi @Filplus-govteam ,I submitted the KYC form for #2112 #2116 #2117 #2119 again. please check

**Comment by FroghubMan** [comment]
Hi @Filplus-govteam , Any update ? Long waits will increase the potential cost of SPs.

**Comment by Chuangshi1** [comment]
checker:manualTrigger

**Comment by Chuangshi1** [comment]
Looks great. Willing to support.

**Comment by Chuangshi1** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebmqvftrfs2tpiyml3mcbnjr4bpf5tali6hucm4zw6yp7lkbdqdke 
#### Address 
> f1svst5e6a7b2ux2scyc336mkmdgec3eqthbjtjpa
#### Datacap Allocated
> 2.00PiB
#### Signer Address
> f1mdk7s2vntzm6hu35yuo6vjubtrpfnb2awhgvrri
#### Id
> 27efcfc0-7a06-4188-9c47-4d4e31a546f3
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebmqvftrfs2tpiyml3mcbnjr4bpf5tali6hucm4zw6yp7lkbdqdke

**Comment by Bitengine-reeta** [comment]
LGTM. support this round.

**Comment by Bitengine-reeta** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceacn3obxgz7scftsk5m4ics6ftze36bcbrkazmbytlp2pnjkbai7s 
#### Address 
> f1svst5e6a7b2ux2scyc336mkmdgec3eqthbjtjpa
#### Datacap Allocated
> 2.00PiB
#### Signer Address
> f1jyvhxp4kmwreo22ke4itspraznpudw3uqaink5i
#### Id
> 27efcfc0-7a06-4188-9c47-4d4e31a546f3
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceacn3obxgz7scftsk5m4ics6ftze36bcbrkazmbytlp2pnjkbai7s

**Comment by 1ane-1** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacea5f3223gorprms4sw3fo6ujo5lf4vb2n7ttvc5e5pn5fhmhq7uqg 
#### Address 
> f1svst5e6a7b2ux2scyc336mkmdgec3eqthbjtjpa
#### Datacap Allocated
> 1.10PiB
#### Signer Address
> f1mdk7s2vntzm6hu35yuo6vjubtrpfnb2awhgvrri
#### Id
> 8533f94c-ff00-4bf5-b811-edb956ec3e14
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacea5f3223gorprms4sw3fo6ujo5lf4vb2n7ttvc5e5pn5fhmhq7uqg

**Comment by laurarenpanda** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedzunmsyfasghekpuhzk47i4ig5e4tga2x6wxarqev4666yxmbdv6 
#### Address 
> f1svst5e6a7b2ux2scyc336mkmdgec3eqthbjtjpa
#### Datacap Allocated
> 1.10PiB
#### Signer Address
> f1bp3tzp536edm7dodldceekzbsx7zcy7hdfg6uzq
#### Id
> 8533f94c-ff00-4bf5-b811-edb956ec3e14
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedzunmsyfasghekpuhzk47i4ig5e4tga2x6wxarqev4666yxmbdv6

**Comment by Sunnyiscoming** [comment]
SP List provided:
[{"providerID":"f01811024,City":HongKong","Country":"CN","SPOrg","XYZ"},
{"providerID":"f0827006,City":Tokyo","Country":"Japan","SPOrg","XYZ"},
{"providerID":"f02227726,City":HongKong","Country":"CN","SPOrg","XYZ"},
{"providerID":"f02195153,City":Tokyo","Country":"Japan","SPOrg","XYZ"},
{"providerID":"f02098006,City":Krabi","Country":"Thailand","SPOrg","XYZ"},
{"providerID":"f02223012,City":Hebei","Country":"CN","SPOrg","XYZ"},
{"providerID":"f02235154,City":HongKong","Country":"CN","SPOrg","XYZ"},
{"providerID":"f02085722,City":Jiangmen","Country":"CN","SPOrg","XYZ"},]
