### ISSUE TITLE
[DataCap Application] Encyclopedia of DNA Elements

### ISSUE THREAD

**Issue by FroghubMan** [filecoin-project/filecoin-plus-large-datasets#2113]
### Data Owner Name

ENCODE Data Coordinating Center

### What is your role related to the dataset

Data Preparer

### Data Owner Country/Region

United States

### Data Owner Industry

Life Science / Healthcare

### Website

https://www.encodeproject.org/

### Social Media

```text
https://twitter.com/EncodeDCC
```

### Total amount of DataCap being requested

9PiB

### Expected size of single dataset (one copy)

1.1P

### Number of replicas to store

8

### Weekly allocation of DataCap requested

1PiB

### On-chain address for first allocation

f1nee2el7nyx6a6djmv3brnatohtqrnlnnh7vitmi

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
FrogHub has always defined itself as a tool developer and infrastructure builder in the Filecoin ecosystem. In 2019, we started to focus on technical solutions and development based on the IPFS protocol and Filecoin network. We have been working hard to become a qualified builder in the filecoin ecosystem.

Our team is a very pure development team, more than 90% of which are developers, more than half of whom have more than 5 years of development experience in communication, Internet, blockchain and other industries. We hope that we can gain users' recognition by exporting useful tools and platforms.

In order to contribute to the filecoin community, we have developed the open source sector repair tool Filecoin-Sealer-Recover and the nft free authoring platform NFT-Creator.
In addition, we plan to provide a sector browser for the community in 2023 and build the liquidity pledge platform STFIL on FVM.

See the links below for details.
- github: https://github.com/orgs/froghub-io
- twitter: https://twitter.com/froghub_io
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
Released and archived ENCODE data. Regulatory elements are typically investigated through DNA hypersensitivity assays, assays of DNA methylation, and immunoprecipitation (IP) of proteins that interact with DNA and RNA, i.e., modified histones, transcription factors, chromatin regulators, and RNA-binding proteins, followed by sequencing.
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### Please share a sample of the data

```text
https://registry.opendata.aws/encode-project/
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

2 to 3 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, Europe

### How will you be distributing your data to storage providers

Cloud storage (i.e. S3), Shipping hard drives

### How do you plan to choose storage providers

Slack, Big Data Exchange, Partners

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
Have you prepared enough token for sector pledge?
Why are you choosing to store it again?
Best practice for storing large datasets includes ideally, storing it in 3 or more regions, with 4 or more storage provider operators or owners.You should list Miner ID, Business Entity, Location of sps you will cooperate with.
Could you send an email to [filplus-app-review@fil.org](mailto:filplus-app-review@fil.org) with your official domain in order to confirm your identity? Email name should includes the issue id #2113 .

**Comment by FroghubMan** [comment]
1.I am a data preparer, and the SP I am looking for has enough FIL as storage collateral.
2.We want to store valuable data. The data for this application is something we have not stored before.
3.The following are the SPs we have cooperated with.

| MinerID | City | Continent |
| --------- | ---------- | --------- |
| f01811024 | HongKong | CN |
| f0827006 | Tokyo | Japan |
| f02227726 | HongKong | CN |
| f02195153 | Tokyo | Japan |
| f02098006 | Krabi | Thailand |
| f02223012 | Hebei | CN |
| f02235154 | HongKong | CN |
| f02085722 | Jiangmen | CN |

4.I have sent the confirmation email.

**Comment by FroghubMan** [comment]
Hi @Filplus-govteam @Sunnyiscoming ,I have submitted the information in #2119, please review it for me. Thank you very much.

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 9PiB

**Expected weekly DataCap usage rate**
> 1PiB

**Client address**
>f1nee2el7nyx6a6djmv3brnatohtqrnlnnh7vitmi

**Comment by MatrixStorage** [comment]
I am willing to support

**Comment by FroghubMan** [comment]
> I am willing to support

thank you! we are preparing data

**Comment by 1ane-1** [comment]
It is the first round, i will support and after that check you report.

**Comment by 1ane-1** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebkhmqv4jadzw6rdozp3v4q5g4a7tr4ijjkvklrfmcertiiiyc5ri 
#### Address 
> f1nee2el7nyx6a6djmv3brnatohtqrnlnnh7vitmi
#### Datacap Allocated
> 460.79TiB
#### Signer Address
> f1mdk7s2vntzm6hu35yuo6vjubtrpfnb2awhgvrri
#### Id
> a7e0d95c-c21e-48c5-8394-ba9a2e52bff7
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebkhmqv4jadzw6rdozp3v4q5g4a7tr4ijjkvklrfmcertiiiyc5ri

**Comment by NiwanDao** [comment]
Good luck with your onboarding.

**Comment by NiwanDao** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedpwekta4hsce6hl7fecbbxnkhkmtjwit6wpk3kamfk7ftmx5ugb2 
#### Address 
> f1nee2el7nyx6a6djmv3brnatohtqrnlnnh7vitmi
#### Datacap Allocated
> 460.79TiB
#### Signer Address
> f1a2lia2cwwekeubwo4nppt4v4vebxs2frozarz3q
#### Id
> a7e0d95c-c21e-48c5-8394-ba9a2e52bff7
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedpwekta4hsce6hl7fecbbxnkhkmtjwit6wpk3kamfk7ftmx5ugb2

**Comment by FroghubMan** [comment]
checker:manualTrigger

**Comment by Bitrise0111** [comment]
The check report shows healthy and we'd like to give a support.

**Comment by Bitrise0111** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec5w2bgrfcs654apuqkgyqbb24boonrb2ab47uqqyv4jopyvzkrua 
#### Address 
> f1nee2el7nyx6a6djmv3brnatohtqrnlnnh7vitmi
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f1nknj7ayq4o43czrtdoauggtwl43fbqatmqis3yy
#### Id
> 21d91f35-d190-4c3d-8e88-2193678b53a8
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec5w2bgrfcs654apuqkgyqbb24boonrb2ab47uqqyv4jopyvzkrua

**Comment by woshidama323** [comment]
LGTM about report result。will support

**Comment by woshidama323** [comment]
checker:manualTrigger

**Comment by woshidama323** [comment]
The result of the report looks healthy and the retrieval success rate looks well，
We will support

**Comment by woshidama323** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced5lxinpkz57xjgsoz6fu6emwnbvumyljafmqx5wee6juf2tg7gti 
#### Address 
> f1nee2el7nyx6a6djmv3brnatohtqrnlnnh7vitmi
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f12tk3adljauwnd3hjbigpfxb7b7gdlj63p6afwtq
#### Id
> 21d91f35-d190-4c3d-8e88-2193678b53a8
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced5lxinpkz57xjgsoz6fu6emwnbvumyljafmqx5wee6juf2tg7gti

**Comment by FroghubMan** [comment]
thank you!

**Comment by sxxfuture-official** [comment]
checker:manualTrigger

**Comment by sxxfuture-official** [comment]
Project goes well

**Comment by sxxfuture-official** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaozgn3zdr5sfp5xrg2ffoy3jspdp3t7jbyqrcmbxhqpc4nqiqpyc 
#### Address 
> f1nee2el7nyx6a6djmv3brnatohtqrnlnnh7vitmi
#### Datacap Allocated
> 1.00PiB
#### Signer Address
> f1foiomqlmoshpuxm6aie4xysffqezkjnokgwcecq
#### Id
> caa7ae6b-6933-4cc7-8d66-ef8ef9753094
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaozgn3zdr5sfp5xrg2ffoy3jspdp3t7jbyqrcmbxhqpc4nqiqpyc

**Comment by Chuangshi1** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebfuxgzltheqokz7xdxafnwly4e64dr7bucmvnbn7fpj5fbj6vwke 
#### Address 
> f1nee2el7nyx6a6djmv3brnatohtqrnlnnh7vitmi
#### Datacap Allocated
> 1.00PiB
#### Signer Address
> f1mdk7s2vntzm6hu35yuo6vjubtrpfnb2awhgvrri
#### Id
> caa7ae6b-6933-4cc7-8d66-ef8ef9753094
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebfuxgzltheqokz7xdxafnwly4e64dr7bucmvnbn7fpj5fbj6vwke

**Comment by FroghubMan** [comment]
We're preparing dataset.

**Comment by kernelogic** [comment]
checker:manualTrigger

**Comment by kernelogic** [comment]
Report LGTM and it's open dataset.

**Comment by kernelogic** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecrkyytwb37p26fcgga7myowd42lqflo3tiuhjq6fozuronsldpim 
#### Address 
> f1nee2el7nyx6a6djmv3brnatohtqrnlnnh7vitmi
#### Datacap Allocated
> 2.00PiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### Id
> 8f16c470-99a8-4f0e-97f7-88deba1ccca6
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecrkyytwb37p26fcgga7myowd42lqflo3tiuhjq6fozuronsldpim

**Comment by Joss-Hua** [comment]
pretty great

**Comment by Joss-Hua** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceah6lencdmogwljdjqhteoybl2qlhjuwvn5ukrnocqvtte7lhx7ru 
#### Address 
> f1nee2el7nyx6a6djmv3brnatohtqrnlnnh7vitmi
#### Datacap Allocated
> 2.00PiB
#### Signer Address
> f1tfg54zzscugttejv336vivknmsnzzmyudp3t7wi
#### Id
> 8f16c470-99a8-4f0e-97f7-88deba1ccca6
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceah6lencdmogwljdjqhteoybl2qlhjuwvn5ukrnocqvtte7lhx7ru

**Comment by FroghubMan** [comment]
We're preparing dataset.

**Comment by 1ane-1** [comment]
checker:manualTrigger

**Comment by 1ane-1** [comment]
report great. support.

**Comment by 1ane-1** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec33fjaqa3briuxpjy7lpgd4pw7fdanxe42ri5tblccftlcaas7qs 
#### Address 
> f1nee2el7nyx6a6djmv3brnatohtqrnlnnh7vitmi
#### Datacap Allocated
> 2.00PiB
#### Signer Address
> f1mdk7s2vntzm6hu35yuo6vjubtrpfnb2awhgvrri
#### Id
> 8f16c470-99a8-4f0e-97f7-88deba1ccca6
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec33fjaqa3briuxpjy7lpgd4pw7fdanxe42ri5tblccftlcaas7qs

**Comment by nj-steve** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebw2axfeqvzefdihmsmgf26ctt4jommdzhgn43sgpcvydrdrkpwam 
#### Address 
> f1nee2el7nyx6a6djmv3brnatohtqrnlnnh7vitmi
#### Datacap Allocated
> 2.00PiB
#### Signer Address
> f1xx6555qijma7igpnjspyvdunc4vfxkawnpqy5ii
#### Id
> 8f16c470-99a8-4f0e-97f7-88deba1ccca6
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebw2axfeqvzefdihmsmgf26ctt4jommdzhgn43sgpcvydrdrkpwam

**Comment by 1ane-1** [comment]
checker:manualTrigger

**Comment by Chuangshi1** [comment]
Support for this round.

**Comment by Chuangshi1** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceal2rfllzlnbiwoa36eytkikkeaoxqie7snem6puqnan5yawrgyaw 
#### Address 
> f1nee2el7nyx6a6djmv3brnatohtqrnlnnh7vitmi
#### Datacap Allocated
> 2.00PiB
#### Signer Address
> f1mdk7s2vntzm6hu35yuo6vjubtrpfnb2awhgvrri
#### Id
> 03abaee7-0f56-445e-b2eb-bb8c3f1863a1
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceal2rfllzlnbiwoa36eytkikkeaoxqie7snem6puqnan5yawrgyaw

**Comment by AlanGreaterheat** [comment]
checker:manualTrigger

**Comment by AlanGreaterheat** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecfrqqq5rw3d2is575fdko62cjfachfekjwi6qlbz5gc77ks3ln7q 
#### Address 
> f1nee2el7nyx6a6djmv3brnatohtqrnlnnh7vitmi
#### Datacap Allocated
> 2.00PiB
#### Signer Address
> f1pnmzlxj7cfeo2v6oj5nco46hkg2l46wj7o4xxui
#### Id
> 03abaee7-0f56-445e-b2eb-bb8c3f1863a1
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecfrqqq5rw3d2is575fdko62cjfachfekjwi6qlbz5gc77ks3ln7q

**Comment by FroghubMan** [comment]
checker:manualTrigger

**Comment by laurarenpanda** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecjq3fik74v6du2eq5ffo2mkeobaujsks4bri6z2cwjppx2xg2nqw 
#### Address 
> f1nee2el7nyx6a6djmv3brnatohtqrnlnnh7vitmi
#### Datacap Allocated
> 2.00PiB
#### Signer Address
> f1bp3tzp536edm7dodldceekzbsx7zcy7hdfg6uzq
#### Id
> 99a31c89-83b7-4cfa-88c8-2c674e311a9f
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecjq3fik74v6du2eq5ffo2mkeobaujsks4bri6z2cwjppx2xg2nqw

**Comment by a1991car** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebiy45ise2sxb2jccqdmglojontbdtg4neokqe655bzy7o2ivhai2 
#### Address 
> f1nee2el7nyx6a6djmv3brnatohtqrnlnnh7vitmi
#### Datacap Allocated
> 2.00PiB
#### Signer Address
> f1qnumecdypgrbaebtkdfjnwt5ndacadcuas3deiq
#### Id
> 99a31c89-83b7-4cfa-88c8-2c674e311a9f
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebiy45ise2sxb2jccqdmglojontbdtg4neokqe655bzy7o2ivhai2

**Comment by FroghubMan** [comment]
We're preparing data

**Comment by ipollo00** [comment]
checker:manualTrigger

**Comment by ipollo00** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceckm6gckdsosut7vrge7e7k2qkqwjcen4bztwkunbxqdkentqdczq 
#### Address 
> f1nee2el7nyx6a6djmv3brnatohtqrnlnnh7vitmi
#### Datacap Allocated
> 1.05PiB
#### Signer Address
> f1n5wlrrhoxpkgwij25xrtt7w7g2k3fhbthmdn6ri
#### Id
> e0957037-434a-4e67-af91-f4ecb7e92452
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceckm6gckdsosut7vrge7e7k2qkqwjcen4bztwkunbxqdkentqdczq

**Comment by nj-steve** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebfdwfquyjglig4kte3mpeqewsvltzo36ymfazoyobeilcow2gcje 
#### Address 
> f1nee2el7nyx6a6djmv3brnatohtqrnlnnh7vitmi
#### Datacap Allocated
> 1.05PiB
#### Signer Address
> f1xx6555qijma7igpnjspyvdunc4vfxkawnpqy5ii
#### Id
> e0957037-434a-4e67-af91-f4ecb7e92452
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebfdwfquyjglig4kte3mpeqewsvltzo36ymfazoyobeilcow2gcje
