### ISSUE TITLE
[DataCap Application] Community Earth System Model v2 ARISE

### ISSUE THREAD

**Issue by FroghubMan** [filecoin-project/filecoin-plus-large-datasets#2114]
### Data Owner Name

NCAR

### What is your role related to the dataset

Data Preparer

### Data Owner Country/Region

United States

### Data Owner Industry

Environment

### Website

https://ncar.ucar.edu/

### Social Media

```text
https://www.youtube.com/ncarucar
```

### Total amount of DataCap being requested

5PiB

### Expected size of single dataset (one copy)

625T

### Number of replicas to store

8

### Weekly allocation of DataCap requested

800TiB

### On-chain address for first allocation

f1eaawhy4y3k3ippyzube5lgzywfh6h2qjztdnv4q

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
FrogHub has always defined itself as a tool developer and infrastructure builder in the Filecoin ecosystem. In 2019, we started to focus on technical solutions and development based on the IPFS protocol and Filecoin network. We have been working hard to become a qualified builder in the filecoin ecosystem.

Our team is a very pure development team, more than 90% of which are developers, more than half of whom have more than 5 years of development experience in communication, Internet, blockchain and other industries. We hope that we can gain users' recognition by exporting useful tools and platforms.

In order to contribute to the filecoin community, we have developed the open source sector repair tool Filecoin-Sealer-Recover and the nft free authoring platform NFT-Creator.
In addition, we plan to provide a sector browser for the community in 2023 and build the liquidity pledge platform STFIL on FVM.

See the links below for details.
- github: https://github.com/orgs/froghub-io
- twitter: https://twitter.com/froghub_io
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
Data from ARISE-SAI Experiments with CESM2.--- Project data files
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### Has this dataset been stored on the Filecoin network before? If so, please explain and make the case why you would like to store this dataset again to the network. Provide details on preparation and/or SP distribution.

```text
I saw that although some people have applied for the storage of this data, they have not implemented it. And the related application is closed, so I want to store it.
```

### Please share a sample of the data

```text
https://registry.opendata.aws/ncar-cesm2-arise/
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

2 to 3 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, Europe

### How will you be distributing your data to storage providers

Cloud storage (i.e. S3), Shipping hard drives

### How do you plan to choose storage providers

Slack, Big Data Exchange, Partners

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1623
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1624
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1625

- This dataset has been stored before. Why are you choosing to store it again?
- Have you prepared enough token for sector pledge?
- Best practice for storing large datasets includes ideally, storing it in 3 or more regions, with 4 or more storage provider operators or owners.You should list Miner ID, Business Entity, Location of sps you will cooperate with.
- Could you send an email to [filplus-app-review@fil.org](mailto:filplus-app-review@fil.org) with your official domain in order to confirm your identity? Email name should includes the issue id https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/2114.

**Comment by FroghubMan** [comment]
1.Hello, this is data that I think is valuable to me, so I want to store it. I think the number of backups can be increased within reason.
2.I am a data preparer, and the SP I am looking for has enough FIL as storage collateral.
3.The following are the SPs we have cooperated with.

| MinerID | City | Continent |
| --------- | ---------- | --------- |
| f01811024 | HongKong | CN |
| f0827006 | Tokyo | Japan |
| f02227726 | HongKong | CN |
| f02195153 | Tokyo | Japan |
| f02098006 | Krabi | Thailand |
| f02223012 | Hebei | CN |
| f02235154 | HongKong | CN |
| f02085722 | Jiangmen | CN |

4.I have sent the confirmation email.

**Comment by herrehesse** [comment]
@FroghubMan "Hello, this is data that I think is valuable to me, so I want to store it." Is this adding any value to the ecosystem as a whole? Datacap is quite costly for every single miner on the network and storing excessive copies of datasets does not add any additional value to the ecosystem.

I'd love to talk with you about this more.
