### ISSUE TITLE
[DataCap Application] NOAA Joint Polar Satellite System (JPSS)

### ISSUE THREAD

**Issue by FroghubMan** [filecoin-project/filecoin-plus-large-datasets#2115]
### Data Owner Name

NOAA

### What is your role related to the dataset

Data Preparer

### Data Owner Country/Region

United States

### Data Owner Industry

IT & Technology Services

### Website

http://www.noaa.gov/

### Social Media

```text
https://twitter.com/NOAA
https://github.com/NOAA-Big-Data-Program/bdp-data-docs/tree/main/JPSS
```

### Total amount of DataCap being requested

9PiB

### Expected size of single dataset (one copy)

1

### Number of replicas to store

9

### Weekly allocation of DataCap requested

1PiB

### On-chain address for first allocation

f14grzai465qqtrqprrgkpoygomgvztkgd3axmaya

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
FrogHub files is a platform that will provide users with free storage, allowing users to enjoy free storage at the same time. Facilitating the Filecoin network to store more and more valuable public data sets.

About the FrogHub data set

FrogHub files is a user-oriented cloud storage platform. Any user with data storage needs can use the platform tools free of charge.

The Filecoin Network provides reliable, secure, and affordable decentralized storage, and FrogHub files wants to make it easy for users to store their data in the filecoin network.

Attracting traditional cloud and object-based storage users to the Filecoin network and benefiting from it is a challenge. FrogHub, as developers in the Felicoin ecosystem, needs to face this challenge together. We've been building useful tools to make it easier for users to store data on the Filecoin network.

Froghub files integrates a set of tools, including storage bucket, custom gateway, data encryption service KMS, static web deployment (under development), open API, to provide storage services compatible with cloud storage and object storage, providing better user experience and attracting more users.
FrogHub has always defined itself as a tool developer and infrastructure builder in the Filecoin ecosystem. In 2019, we started to focus on technical solutions and development based on the IPFS protocol and Filecoin network. We have been working hard to become a qualified builder in the filecoin ecosystem.

Our team is a very pure development team, more than 90% of which are developers, more than half of whom have more than 5 years of development experience in communication, Internet, blockchain and other industries. We hope that we can gain users' recognition by exporting useful tools and platforms.

In order to contribute to the filecoin community, we have developed the open source sector repair tool Filecoin-Sealer-Recover and the nft free authoring platform NFT-Creator.
In addition, we plan to provide a sector browser for the community in 2023 and build the liquidity pledge platform STFIL on FVM.

See the links below for details.
- github: https://github.com/orgs/froghub-io
- twitter: https://twitter.com/froghub_io
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
”Satellites in the JPSS constellation gather global measurements of atmospheric, terrestrial and oceanic conditions, including sea and land surface temperatures, vegetation, clouds, rainfall, snow and ice cover, fire locations and smoke plumes, atmospheric temperature, water vapor and ozone. JPSS delivers key observations for the Nation's essential products and services, including forecasting severe weather like hurricanes, tornadoes and blizzards days in advance, and assessing environmental hazards such as droughts, forest fires, poor air quality and harmful coastal waters. Further, JPSS will provide continuity of critical, global observations of Earth’s atmosphere, oceans and land through 2038.“

Source: https://registry.opendata.aws/noaa-jpss/
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### Has this dataset been stored on the Filecoin network before? If so, please explain and make the case why you would like to store this dataset again to the network. Provide details on preparation and/or SP distribution.

```text
I saw that although some people have applied for the storage of this data, they have not implemented it. And the related application is closed, so I want to store it.
```

### Please share a sample of the data

```text
s3://noaa-jpss/(1020.7TiB)
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [ ] I confirm

### What is the expected retrieval frequency for this data

Daily

### For how long do you plan to keep this dataset stored on Filecoin

Less than 1 year

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, Europe

### How will you be distributing your data to storage providers

Cloud storage (i.e. S3), Shipping hard drives

### How do you plan to choose storage providers

Slack, Big Data Exchange, Partners

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
- Have you prepared enough token for sector pledge?
- Why are you choosing to store it again?
- Best practice for storing large datasets includes ideally, storing it in 3 or more regions, with 4 or more storage provider operators or owners.You should list Miner ID, Business Entity, Location of sps you will cooperate with.
- Could you send an email to [filplus-app-review@fil.org](mailto:filplus-app-review@fil.org) with your official domain in order to confirm your identity? Email name should includes the issue id https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/2115.

**Comment by FroghubMan** [comment]
1.I am a data preparer, and the SP I am looking for has enough FIL as storage collateral.
2.We want to store valuable data. The data for this application is something we have not stored before.
3.The following are the SPs we have cooperated with.

| MinerID | City | Continent |
| --------- | ---------- | --------- |
| f01811024 | HongKong | CN |
| f0827006 | Tokyo | Japan |
| f02227726 | HongKong | CN |
| f02195153 | Tokyo | Japan |
| f02098006 | Krabi | Thailand |
| f02223012 | Hebei | CN |
| f02235154 | HongKong | CN |
| f02085722 | Jiangmen | CN |

4.I have sent the confirmation email.

**Comment by FroghubMan** [comment]
Hi @Sunnyiscoming ,After querying this data set has not been stored yet. I will continue the application process.

**Comment by Filplus-govteam** [comment]
Left a [comment](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/2119#issuecomment-1656107816) on 2119

**Comment by FroghubMan** [comment]
Hi @Filplus-govteam @Sunnyiscoming ,I have submitted the information in #2119, please review it for me. Thank you very much.

**Comment by junyaoren** [comment]
> * Best practice for storing large datasets includes ideally, storing it in 3 or more regions, with 4 or more storage provider operators or owners.You should list Miner ID, Business Entity, Location of sps you will cooperate with.

Are some of the SPs listed belong to the same company/organization? As I can see, some of the SPs share funding source.

**Comment by FroghubMan** [comment]
Hi @junyaoren , Do you mean they have the same owner? or something else?

**Comment by junyaoren** [comment]
Yeah, I noticed some of them shared same owner and some of the worker addresses received funds from common addresses. I guess it is allowed for this to happen, but might be better if you could clarify this situation. Thanks!

**Comment by FroghubMan** [comment]
> Yeah, I noticed some of them shared same owner and some of the worker addresses received funds from common addresses. I guess it is allowed for this to happen, but might be better if you could clarify this situation. Thanks!

Can you provide the minerID?

**Comment by FroghubMan** [comment]
Some sps are involved in DeFi which may be the reason for what you are seeing.

**Comment by junyaoren** [comment]
I see. Thanks for the clarification.

**Comment by junyaoren** [comment]
> > Yeah, I noticed some of them shared same owner and some of the worker addresses received funds from common addresses. I guess it is allowed for this to happen, but might be better if you could clarify this situation. Thanks!
> 
> Can you provide the minerID?

f01811024-f02098006-f02235154-f02085722

**Comment by FroghubMan** [comment]
> > > Yeah, I noticed some of them shared same owner and some of the worker addresses received funds from common addresses. I guess it is allowed for this to happen, but might be better if you could clarify this situation. Thanks!
> > 
> > 
> > Can you provide the minerID?
> 
> f01811024-f02098006-f02235154-f02085722

Yes, f02098006 and f02235154 do belong to the same company.

**Comment by 1ane-1** [comment]
According to above comments, i will support but i will after 1st round and check the SP sealing sistuation.

**Comment by 1ane-1** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceby2bobgyb52coiiwdjfoypbpfw4kpw6aaorsedsd6xzsy7t3uylc 
#### Address 
> f14grzai465qqtrqprrgkpoygomgvztkgd3axmaya
#### Datacap Allocated
> 460.79TiB
#### Signer Address
> f1mdk7s2vntzm6hu35yuo6vjubtrpfnb2awhgvrri
#### Id
> b37b9e32-07d3-4bb9-9a43-ad207418aad3
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceby2bobgyb52coiiwdjfoypbpfw4kpw6aaorsedsd6xzsy7t3uylc

**Comment by NiwanDao** [comment]
Good luck with your onboarding.

**Comment by woshidama323** [comment]
checker:manualTrigger

**Comment by woshidama323** [comment]
The result of the report looks healthy
Keep going for data onboarding, will support

**Comment by woshidama323** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceds2woaq4lk7aclzucelrw7rpccyqjpocqnhd7dy6sfq5tiy4lnke 
#### Address 
> f14grzai465qqtrqprrgkpoygomgvztkgd3axmaya
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f12tk3adljauwnd3hjbigpfxb7b7gdlj63p6afwtq
#### Id
> c9d6e730-2c57-4958-b548-7ffae76a7ad5
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceds2woaq4lk7aclzucelrw7rpccyqjpocqnhd7dy6sfq5tiy4lnke

**Comment by sxxfuture-official** [comment]
checker:manualTrigger

**Comment by sxxfuture-official** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb6atq2ufcsrzfnjlio7q3u36ghjnnpvlym2xdsthfi4la4fi3kfo 
#### Address 
> f14grzai465qqtrqprrgkpoygomgvztkgd3axmaya
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f1foiomqlmoshpuxm6aie4xysffqezkjnokgwcecq
#### Id
> c9d6e730-2c57-4958-b548-7ffae76a7ad5
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb6atq2ufcsrzfnjlio7q3u36ghjnnpvlym2xdsthfi4la4fi3kfo

**Comment by FroghubMan** [comment]
thank you!

**Comment by kevzak** [comment]
checker:manualTrigger

**Comment by Chuangshi1** [comment]
checker:manualTrigger

**Comment by Chuangshi1** [comment]
support for this round.

**Comment by Chuangshi1** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebmvj4we422qfjkykoye2enqb3i5r7bepw6ubjs6jsjpk7c5qqlyc 
#### Address 
> f14grzai465qqtrqprrgkpoygomgvztkgd3axmaya
#### Datacap Allocated
> 1.00PiB
#### Signer Address
> f1mdk7s2vntzm6hu35yuo6vjubtrpfnb2awhgvrri
#### Id
> 2fca6a9a-c9ab-4f37-9f91-97f5b3eaa272
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebmvj4we422qfjkykoye2enqb3i5r7bepw6ubjs6jsjpk7c5qqlyc

**Comment by AlanGreaterheat** [comment]
checker:manualTrigger

**Comment by AlanGreaterheat** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceam7mgbovtbva72glbox4cammszhuv34vr2fkqnogzu5nuwiacqgw 
#### Address 
> f14grzai465qqtrqprrgkpoygomgvztkgd3axmaya
#### Datacap Allocated
> 1.00PiB
#### Signer Address
> f1pnmzlxj7cfeo2v6oj5nco46hkg2l46wj7o4xxui
#### Id
> 2fca6a9a-c9ab-4f37-9f91-97f5b3eaa272
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceam7mgbovtbva72glbox4cammszhuv34vr2fkqnogzu5nuwiacqgw

**Comment by FroghubMan** [comment]
We're preparing dataset.

**Comment by kernelogic** [comment]
checker:manualTrigger

**Comment by kernelogic** [comment]
Report LGTM and it's open dataset.

**Comment by kernelogic** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedpemujroqzcblkjzzijrq6z6uvjrm643phn447hh62wkxblo3vhm 
#### Address 
> f14grzai465qqtrqprrgkpoygomgvztkgd3axmaya
#### Datacap Allocated
> 1.00PiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### Id
> fc8d86ee-e6d8-4855-8d01-b3596823fff5
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedpemujroqzcblkjzzijrq6z6uvjrm643phn447hh62wkxblo3vhm

**Comment by Joss-Hua** [comment]
looks good, keep work

**Comment by Joss-Hua** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedb3aja62obzmuip66hdsbclu7jsuzyucv3aahljtgljlubar7k62 
#### Address 
> f14grzai465qqtrqprrgkpoygomgvztkgd3axmaya
#### Datacap Allocated
> 1.00PiB
#### Signer Address
> f1tfg54zzscugttejv336vivknmsnzzmyudp3t7wi
#### Id
> fc8d86ee-e6d8-4855-8d01-b3596823fff5
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedb3aja62obzmuip66hdsbclu7jsuzyucv3aahljtgljlubar7k62

**Comment by xiaoyuaiheshui** [comment]
checker:manualTrigger

**Comment by Chuangshi1** [comment]
checker:manualTrigger

**Comment by Chuangshi1** [comment]
Looks good, signed.

**Comment by Chuangshi1** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecuzebe3wd4stpt4sb6z6uialmsxzicvbdf2fazxhb5cet4244qb2 
#### Address 
> f14grzai465qqtrqprrgkpoygomgvztkgd3axmaya
#### Datacap Allocated
> 1.00PiB
#### Signer Address
> f1mdk7s2vntzm6hu35yuo6vjubtrpfnb2awhgvrri
#### Id
> fc8d86ee-e6d8-4855-8d01-b3596823fff5
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecuzebe3wd4stpt4sb6z6uialmsxzicvbdf2fazxhb5cet4244qb2

**Comment by AlanGreaterheat** [comment]
checker:manualTrigger

**Comment by AlanGreaterheat** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecojaibe46osesama2hpvct4lwwqph3hc6uqxsrrsiqqdfey4desg 
#### Address 
> f14grzai465qqtrqprrgkpoygomgvztkgd3axmaya
#### Datacap Allocated
> 1.00PiB
#### Signer Address
> f1pnmzlxj7cfeo2v6oj5nco46hkg2l46wj7o4xxui
#### Id
> fc8d86ee-e6d8-4855-8d01-b3596823fff5
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecojaibe46osesama2hpvct4lwwqph3hc6uqxsrrsiqqdfey4desg

**Comment by 1ane-1** [comment]
checker:manualTrigger

**Comment by 1ane-1** [comment]
report looks great.

**Comment by 1ane-1** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec2rm2vyost7uboyp4aqnujurv6a5x2hldvfrelr5qetkyhtphvgs 
#### Address 
> f14grzai465qqtrqprrgkpoygomgvztkgd3axmaya
#### Datacap Allocated
> 2.00PiB
#### Signer Address
> f1mdk7s2vntzm6hu35yuo6vjubtrpfnb2awhgvrri
#### Id
> b5bbe627-84cb-4f00-ae1a-161da23c9b26
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec2rm2vyost7uboyp4aqnujurv6a5x2hldvfrelr5qetkyhtphvgs

**Comment by Bitrise0111** [comment]
The report shows healthy and we'd like to give support.

**Comment by Bitrise0111** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebowj2iosz6ksxwzq5kz4qk5uzoy7gyvkewiooiwolsetlafvydb4 
#### Address 
> f14grzai465qqtrqprrgkpoygomgvztkgd3axmaya
#### Datacap Allocated
> 2.00PiB
#### Signer Address
> f1nknj7ayq4o43czrtdoauggtwl43fbqatmqis3yy
#### Id
> b5bbe627-84cb-4f00-ae1a-161da23c9b26
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebowj2iosz6ksxwzq5kz4qk5uzoy7gyvkewiooiwolsetlafvydb4

**Comment by FroghubMan** [comment]
checker:manualTrigger

**Comment by FroghubMan** [comment]
checker:manualTrigger

**Comment by sxxfuture-official** [comment]
checker:manualTrigger

**Comment by sxxfuture-official** [comment]
reports looks healthy,  will support.

**Comment by sxxfuture-official** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacealpjbfpq6guugpgbsba3hksyt2ivoued6w5a5wyuuxo4ubjqc6y2 
#### Address 
> f14grzai465qqtrqprrgkpoygomgvztkgd3axmaya
#### Datacap Allocated
> 2.00PiB
#### Signer Address
> f1foiomqlmoshpuxm6aie4xysffqezkjnokgwcecq
#### Id
> 0d4a9b01-363e-46bd-8709-38498ec8477d
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacealpjbfpq6guugpgbsba3hksyt2ivoued6w5a5wyuuxo4ubjqc6y2

**Comment by Tom-OriginStorage** [comment]
checker:manualTrigger

**Comment by Tom-OriginStorage** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacea73hsh4iygim3225qgag5cumnuvlxf7h6rezeds57skrrx35mqt6 
#### Address 
> f14grzai465qqtrqprrgkpoygomgvztkgd3axmaya
#### Datacap Allocated
> 2.00PiB
#### Signer Address
> f1q6bpjlqia6iemqbrdaxr2uehrhpvoju3qh4lpga
#### Id
> 0d4a9b01-363e-46bd-8709-38498ec8477d
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacea73hsh4iygim3225qgag5cumnuvlxf7h6rezeds57skrrx35mqt6

**Comment by ipollo00** [comment]
checker:manualTrigger

**Comment by ipollo00** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb26zieqabjyb5x4eryx2ejc45uweqtx7olmbveggp6vaye7sj3u6 
#### Address 
> f14grzai465qqtrqprrgkpoygomgvztkgd3axmaya
#### Datacap Allocated
> 1.05PiB
#### Signer Address
> f1n5wlrrhoxpkgwij25xrtt7w7g2k3fhbthmdn6ri
#### Id
> 6953f938-828d-497a-95da-1dc9748a9911
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb26zieqabjyb5x4eryx2ejc45uweqtx7olmbveggp6vaye7sj3u6

**Comment by nj-steve** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedr5pg5usazg4gv6tnv4jrpcrp5lg64z7hr3gv5vr4z5e5aihowjw 
#### Address 
> f14grzai465qqtrqprrgkpoygomgvztkgd3axmaya
#### Datacap Allocated
> 1.05PiB
#### Signer Address
> f1xx6555qijma7igpnjspyvdunc4vfxkawnpqy5ii
#### Id
> 6953f938-828d-497a-95da-1dc9748a9911
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedr5pg5usazg4gv6tnv4jrpcrp5lg64z7hr3gv5vr4z5e5aihowjw
