### ISSUE TITLE
[DataCap Application] NOAA-HRRR

### ISSUE THREAD

**Issue by FroghubMan** [filecoin-project/filecoin-plus-large-datasets#2116]
### Data Owner Name

National Oceanic and Atmospheric Administration

### What is your role related to the dataset

Data Preparer

### Data Owner Country/Region

United States

### Data Owner Industry

Environment

### Website

https://registry.opendata.aws/noaa-hrrr-pds

### Social Media

```text
Website: https://www.noaa.gov/
Twitter: https://twitter.com/NOAA
```

### Total amount of DataCap being requested

15PiB

### Expected size of single dataset (one copy)

2.1

### Number of replicas to store

7

### Weekly allocation of DataCap requested

1PiB

### On-chain address for first allocation

f1h2neemc5yldsckegrvyo5dq26ybo2i66ukgqsei

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
FrogHub files is a platform that will provide users with free storage, allowing users to enjoy free storage at the same time. Facilitating the Filecoin network to store more and more valuable public data sets.

About the FrogHub data set

FrogHub files is a user-oriented cloud storage platform. Any user with data storage needs can use the platform tools free of charge.

The Filecoin Network provides reliable, secure, and affordable decentralized storage, and FrogHub files wants to make it easy for users to store their data in the filecoin network.

Attracting traditional cloud and object-based storage users to the Filecoin network and benefiting from it is a challenge. FrogHub, as developers in the Felicoin ecosystem, needs to face this challenge together. We've been building useful tools to make it easier for users to store data on the Filecoin network.

Froghub files integrates a set of tools, including storage bucket, custom gateway, data encryption service KMS, static web deployment (under development), open API, to provide storage services compatible with cloud storage and object storage, providing better user experience and attracting more users.
FrogHub has always defined itself as a tool developer and infrastructure builder in the Filecoin ecosystem. In 2019, we started to focus on technical solutions and development based on the IPFS protocol and Filecoin network. We have been working hard to become a qualified builder in the filecoin ecosystem.

Our team is a very pure development team, more than 90% of which are developers, more than half of whom have more than 5 years of development experience in communication, Internet, blockchain and other industries. We hope that we can gain users' recognition by exporting useful tools and platforms.

In order to contribute to the filecoin community, we have developed the open source sector repair tool Filecoin-Sealer-Recover and the nft free authoring platform NFT-Creator.
In addition, we plan to provide a sector browser for the community in 2023 and build the liquidity pledge platform STFIL on FVM.

See the links below for details.
- github: https://github.com/orgs/froghub-io
- twitter: https://twitter.com/froghub_io
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
357-resule 
2020-08-25 17:22:47  398.4 MiB hrrr_v2.20160823/conus/hrrr.t09z.wrfprsf13.grib2
2020-08-25 17:22:52  396.0 MiB hrrr_v2.20160823/conus/hrrr.t09z.wrfprsf14.grib2
2020-08-25 17:22:52  394.6 MiB hrrr_v2.20160823/conus/hrrr.t09z.wrfprsf15.grib2
2020-08-25 17:22:52  390.2 MiB hrrr_v2.20160823/conus/hrrr.t09z.wrfprsf16.grib2
2020-08-25 17:23:08  387.1 MiB hrrr_v2.20160823/conus/hrrr.t09z.wrfprsf17.grib2
2020-08-25 17:23:05  384.8 MiB hrrr_v2.20160823/conus/hrrr.t09z.wrfprsf18.grib2
2021-09-28 03:48:22   31.6 KiB index.html

Total Objects: 43282174
   Total Size: 2.1 PiB
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### Please share a sample of the data

```text
357-resule 
2020-08-25 17:22:47  398.4 MiB hrrr_v2.20160823/conus/hrrr.t09z.wrfprsf13.grib2
2020-08-25 17:22:52  396.0 MiB hrrr_v2.20160823/conus/hrrr.t09z.wrfprsf14.grib2
2020-08-25 17:22:52  394.6 MiB hrrr_v2.20160823/conus/hrrr.t09z.wrfprsf15.grib2
2020-08-25 17:22:52  390.2 MiB hrrr_v2.20160823/conus/hrrr.t09z.wrfprsf16.grib2
2020-08-25 17:23:08  387.1 MiB hrrr_v2.20160823/conus/hrrr.t09z.wrfprsf17.grib2
2020-08-25 17:23:05  384.8 MiB hrrr_v2.20160823/conus/hrrr.t09z.wrfprsf18.grib2
2021-09-28 03:48:22   31.6 KiB index.html

Total Objects: 43282174
   Total Size: 2.1 PiB
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

2 to 3 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, Europe

### How will you be distributing your data to storage providers

Cloud storage (i.e. S3), Shipping hard drives

### How do you plan to choose storage providers

Slack, Big Data Exchange, Partners

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
- Have you prepared enough token for sector pledge?
- Why are you choosing to store it again?
- Best practice for storing large datasets includes ideally, storing it in 3 or more regions, with 4 or more storage provider operators or owners.You should list Miner ID, Business Entity, Location of sps you will cooperate with.
- Could you send an email to filplus-app-review@fil.org with your official domain in order to confirm your identity? Email name should includes the issue id #2116.

**Comment by Filplus-govteam** [comment]
Left a [comment](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/2119#issuecomment-1656107816) on 2119

**Comment by FroghubMan** [comment]
Hi @Filplus-govteam @Sunnyiscoming ,I have submitted the information in #2119, please review it for me. Thank you very much.

**Comment by FroghubMan** [comment]
Hi @Sunnyiscoming @Filplus-govteam , I have completed the Fil+ registration form once again.

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 15PiB

**Expected weekly DataCap usage rate**
> 1PiB

**Client address**
>f1h2neemc5yldsckegrvyo5dq26ybo2i66ukgqsei

**Comment by MatrixStorage** [comment]
I am willing to support

**Comment by MatrixStorage** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecqdoqdvubibbn4ngp4bulytcddrzkgiydh2iv5q7m5yckgdcm3la 
#### Address 
> f1h2neemc5yldsckegrvyo5dq26ybo2i66ukgqsei
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f1tbxqwjxfyv7swsdin4einirlsfquv3vnmlapley
#### Id
> 750561f3-d6c5-4957-bea9-11c3eb33c768
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecqdoqdvubibbn4ngp4bulytcddrzkgiydh2iv5q7m5yckgdcm3la

**Comment by FroghubMan** [comment]
Thank you

**Comment by FroghubMan** [comment]
In progress

**Comment by stcouldlisa** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebzvkt3rwqnwheoymemd4vfwazndtfag5bptlbd4bxm7pvbyso2uc 
#### Address 
> f1h2neemc5yldsckegrvyo5dq26ybo2i66ukgqsei
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f1jvvltduw35u6inn5tr4nfualyd42bh3vjtylgci
#### Id
> 750561f3-d6c5-4957-bea9-11c3eb33c768
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebzvkt3rwqnwheoymemd4vfwazndtfag5bptlbd4bxm7pvbyso2uc

**Comment by FroghubMan** [comment]
thank you!

**Comment by FroghubMan** [comment]
We're preparing dataset.

**Comment by FroghubMan** [comment]
We're preparing dataset.

**Comment by xiaoyuaiheshui** [comment]
checker:manualTrigger

**Comment by xiaoyuaiheshui** [comment]
checker:manualTrigger

**Comment by xiaoyuaiheshui** [comment]
checker:manualTrigger

**Comment by xiaoyuaiheshui** [comment]
checker:manualTrigger

**Comment by 1ane-1** [comment]
checker:manualTrigger

**Comment by Chuangshi1** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecnykjk3apekqbeycddlp6ogxbi4maefu4aep6skenhfs6fzzhshy 
#### Address 
> f1h2neemc5yldsckegrvyo5dq26ybo2i66ukgqsei
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f1mdk7s2vntzm6hu35yuo6vjubtrpfnb2awhgvrri
#### Id
> c4846836-9d89-4281-8b8c-e5afc3ec915c
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecnykjk3apekqbeycddlp6ogxbi4maefu4aep6skenhfs6fzzhshy

**Comment by AlanGreaterheat** [comment]
checker:manualTrigger

**Comment by AlanGreaterheat** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced4vdvxwbjrbj4puepcehyn5mbjvp75qgwm6efgsnpwmbduvezhzg 
#### Address 
> f1h2neemc5yldsckegrvyo5dq26ybo2i66ukgqsei
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f1pnmzlxj7cfeo2v6oj5nco46hkg2l46wj7o4xxui
#### Id
> c4846836-9d89-4281-8b8c-e5afc3ec915c
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced4vdvxwbjrbj4puepcehyn5mbjvp75qgwm6efgsnpwmbduvezhzg

**Comment by FroghubMan** [comment]
checker:manualTrigger

**Comment by FroghubMan** [comment]
checker:manualTrigger

**Comment by luobin544** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebyvlz6iwfd65nmm2owyylho5yftblndsgxhblvhrvf6nqxtticiu 
#### Address 
> f1h2neemc5yldsckegrvyo5dq26ybo2i66ukgqsei
#### Datacap Allocated
> 1.00PiB
#### Signer Address
> f1tbd632f6w62glfaf7wjpimacbnjiz26poyoes2q
#### Id
> 5457863c-7964-408e-8b66-bcc14d28d6e9
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebyvlz6iwfd65nmm2owyylho5yftblndsgxhblvhrvf6nqxtticiu

**Comment by newwebgroup** [comment]
checker:manualTrigger

**Comment by newwebgroup** [comment]
The inspection report looks fine, there is no CID sharing.

Regarding the 200T data, the distribution of data copies does not comply with the rules. Can you provide a list of improvement plans for follow-up?
<img width="1145" alt="image" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/100118145/1f7d8d0d-ed6c-4db8-ba58-dfd2259bb35d">

**Comment by 1ane-1** [comment]
> The inspection report looks fine, there is no CID sharing.
> 
> Regarding the 200T data, the distribution of data copies does not comply with the rules. Can you provide a list of improvement plans for follow-up? <img alt="image" width="1145" src="https://user-images.githubusercontent.com/100118145/275736710-1f7d8d0d-ed6c-4db8-ba58-dfd2259bb35d.png">
we will adjust more sps in the future. And pay attention to the diatribution.

**Comment by FroghubMan** [comment]
<img width="1412" alt="image" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/88960777/593d5737-d4ac-469b-be0a-c095fec0c033">
We are proceeding according to the plan, but the disk numbers allocated to f02364899, f02636860, and f02810687 are at the back, and their packaging speed is relatively fast. In the next round, other nodes will catch up!

**Comment by nj-steve** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceachsdhkg5gdufj2vbf7gzhofbtpheqk7kwlmg3aioexmnckk63t6 
#### Address 
> f1h2neemc5yldsckegrvyo5dq26ybo2i66ukgqsei
#### Datacap Allocated
> 1.00PiB
#### Signer Address
> f1xx6555qijma7igpnjspyvdunc4vfxkawnpqy5ii
#### Id
> 5457863c-7964-408e-8b66-bcc14d28d6e9
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceachsdhkg5gdufj2vbf7gzhofbtpheqk7kwlmg3aioexmnckk63t6

**Comment by nj-steve** [comment]
The client has explained the 200T data copies.

**Comment by FroghubMan** [comment]
checker:manualTrigger

**Comment by AlanGreaterheat** [comment]
checker:manualTrigger

**Comment by AlanGreaterheat** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceazuffgrisotxowm3y44zyer6uxfyevw3zzcgohi2yjb7n46lht4q 
#### Address 
> f1h2neemc5yldsckegrvyo5dq26ybo2i66ukgqsei
#### Datacap Allocated
> 2.00PiB
#### Signer Address
> f1pnmzlxj7cfeo2v6oj5nco46hkg2l46wj7o4xxui
#### Id
> 5cf03a86-ce3f-4069-b405-e4ee68e6a2e5
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceazuffgrisotxowm3y44zyer6uxfyevw3zzcgohi2yjb7n46lht4q

**Comment by NiwanDao** [comment]
LGME

**Comment by NiwanDao** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecmoziwsyn46saaf2fkbpanvowowz3lm45j5yt3xp3i7klng4ij2m 
#### Address 
> f1h2neemc5yldsckegrvyo5dq26ybo2i66ukgqsei
#### Datacap Allocated
> 2.00PiB
#### Signer Address
> f1a2lia2cwwekeubwo4nppt4v4vebxs2frozarz3q
#### Id
> 5cf03a86-ce3f-4069-b405-e4ee68e6a2e5
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecmoziwsyn46saaf2fkbpanvowowz3lm45j5yt3xp3i7klng4ij2m

**Comment by FroghubMan** [comment]
checker:manualTrigger

**Comment by 1ane-1** [comment]
Report looks fine. Support for this round.

**Comment by 1ane-1** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedcoitsq6db75gwyc6fndehtdqllbaepqkdysb4mho622742dy3km 
#### Address 
> f1h2neemc5yldsckegrvyo5dq26ybo2i66ukgqsei
#### Datacap Allocated
> 2.00PiB
#### Signer Address
> f1mdk7s2vntzm6hu35yuo6vjubtrpfnb2awhgvrri
#### Id
> 0ffe4579-50bf-456a-971d-008e0246a6c8
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedcoitsq6db75gwyc6fndehtdqllbaepqkdysb4mho622742dy3km

**Comment by sxxfuture-official** [comment]
LGTM. will support

**Comment by sxxfuture-official** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec73dsdom4heigjeup5b7gdvoaap7wqik64jqsrl5g3aepfdihwdg 
#### Address 
> f1h2neemc5yldsckegrvyo5dq26ybo2i66ukgqsei
#### Datacap Allocated
> 2.00PiB
#### Signer Address
> f1foiomqlmoshpuxm6aie4xysffqezkjnokgwcecq
#### Id
> 0ffe4579-50bf-456a-971d-008e0246a6c8
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec73dsdom4heigjeup5b7gdvoaap7wqik64jqsrl5g3aepfdihwdg

**Comment by FroghubMan** [comment]
![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/88960777/cd35e4ee-56cf-4301-8356-4addfca30118)
@Sunnyiscoming My limit has almost been used up, but the new cycle hasn't been triggered yet.

**Comment by laurarenpanda** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedtjpbuoa4cdkcwibal33zok7fusrmjwkeovc2bzaslnmnixaars4 
#### Address 
> f1h2neemc5yldsckegrvyo5dq26ybo2i66ukgqsei
#### Datacap Allocated
> 2.00PiB
#### Signer Address
> f1bp3tzp536edm7dodldceekzbsx7zcy7hdfg6uzq
#### Id
> 0ffe4579-50bf-456a-971d-008e0246a6c8
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedtjpbuoa4cdkcwibal33zok7fusrmjwkeovc2bzaslnmnixaars4

**Comment by ipollo00** [comment]
checker:manualTrigger

**Comment by ipollo00** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceafmwlrd7i3yvacid574y23wcsjvpxblhknbpze2cea5r7ullha7w 
#### Address 
> f1h2neemc5yldsckegrvyo5dq26ybo2i66ukgqsei
#### Datacap Allocated
> 2.00PiB
#### Signer Address
> f1n5wlrrhoxpkgwij25xrtt7w7g2k3fhbthmdn6ri
#### Id
> 0ffe4579-50bf-456a-971d-008e0246a6c8
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceafmwlrd7i3yvacid574y23wcsjvpxblhknbpze2cea5r7ullha7w

**Comment by Filplus-govteam** [comment]
@FroghubMan SPs do no match what was submitted https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/2116#issuecomment-1651876692

closing until clarified

**Comment by FroghubMan** [comment]
Hi @Filplus-govteam ,Thank you for your attention. 
The actual allocated miner node is different from the miner node during KYC because if the data preparation time is long, some SPs will first store other available datacaps for the sake of equipment usage efficiency. When the storage power of the miner node reaches a certain value, SPs will consider creating a new miner node. Therefore, over time, changes in the miner node that stores datacap are inevitable.

However, we ensure that everything strictly abides by the rules of FIL+, and we can complete KYC for new nodes:

| MinerID | Entity | City | Continent |
| --------- | ---------- | ---------- | --------- |
| f02816837	|B.B Tech|		Shenzhen, Guangdong, |CN|
| f02364899	|S&D 	|	Chengdu, Sichuan, |CN|
| f02811050	|chimsen		|	Shenzhen, Guangdong, |CN|
| f02825666	|chimsen	|		Shenzhen, Guangdong, |CN|
| f02806931	|HCXY Tech |Jiangmen, Guangdong, |CN|
| f02831252	|HCXY Tech |	Jiangmen, Guangdong, |CN|
| f01708981	|HCXY Tech	|Jiangmen, Guangdong, |CN|
| f02088858	|chimsen			London, England,| GB|
| f02817992	|68Tech		|Hong Kong, Central and Western, |HK|
| f02817995	|68Tech	|	Hong Kong, Central and Western, |HK|
| f02817991	|68Tech	|	Hong Kong, Central and Western, |HK|
| f02817993	|68Tech	|	Hong Kong, Central and Western,| HK|
| f02636860	|68Tech		|Hong Kong, Central and Western, | HK|
| f02810687	|68Tech	|	Hong Kong, Central and Western, | HK|
| f02828514	|DD Tech	|		Hong Kong, Central and Western, | HK|
| f02826478	|DD Tech	|		Hong Kong, Central and Western, | HK|
| f02806522	|HCXY Tech	|Ashburn, Virginia, |US|
| f02806528	|HCXY Tech	|Ashburn, Virginia, |US|
| f01854510	|3cloud tech	|	Hong Kong, Central and Western, | HK|
| f02838396	|ssdminer	|Aberdeen, Southern, | HK|
| f02824610	|personal	|		Bangkok, Bangkok, |TH|
| f02825172	|personal	|		Bangkok, Bangkok, |TH|
| f02143523	|ssdminer  | Hong Kong, Central and Western, | HK|
| f02016677	|ssdminer	|Hong Kong, Central and Western, | HK|
| f01912211	|ssdminer	|Hong Kong, Central and Western, | HK|
| f02211244	|ssdminer	|	Hong Kong, Central and Western, | HK|
| f02824865	|DD Tech	|		Hong Kong, Central and Western, | HK|
| f02824414	|DD Tech	|		Hong Kong, Central and Western, | HK|
| f01885088	|S&D	|	Hong Kong, Central and Western, | HK|
| f0693793	|S&D	|	Hong Kong, Central and Western, | HK|
| f02826888	|chimsen	|		Toronto, Ontario, |CA|
| f02827777	|chimsen	|		Mumbai, Maharashtra, |IN|
| f02806894	|chimsen	|		Paripark, Seoul, |KR|
| f02803754	|Personal	|		Osaka, Ōsaka, |JP|
| f02519021	|chimsen	|		Singapore, Singapore, |SG|
| f02372022	|chimsen	|		Ōi, Saitama,| JP|

**Comment by 1ane-1** [comment]
checker:manualTrigger

**Comment by 1ane-1** [comment]
The report looks good and SPs KYC has been done. Support.

**Comment by 1ane-1** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaatvck3evfdofxsva4fhtgtcme6otuuh66q4kfbn3d4w3if76glu 
#### Address 
> f1h2neemc5yldsckegrvyo5dq26ybo2i66ukgqsei
#### Datacap Allocated
> 2.00PiB
#### Signer Address
> f1mdk7s2vntzm6hu35yuo6vjubtrpfnb2awhgvrri
#### Id
> ae3ce316-7eef-4274-a9ab-64410b28705c
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaatvck3evfdofxsva4fhtgtcme6otuuh66q4kfbn3d4w3if76glu

**Comment by Bitengine-reeta** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceam4y5wq47pqit7gpmb7ssnuvucvjasnhfuos6zj32awta6iroxui 
#### Address 
> f1h2neemc5yldsckegrvyo5dq26ybo2i66ukgqsei
#### Datacap Allocated
> 2.00PiB
#### Signer Address
> f1jyvhxp4kmwreo22ke4itspraznpudw3uqaink5i
#### Id
> ae3ce316-7eef-4274-a9ab-64410b28705c
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceam4y5wq47pqit7gpmb7ssnuvucvjasnhfuos6zj32awta6iroxui

**Comment by Sunnyiscoming** [comment]
SP List provided:
[{"providerID":"f02816837,City":Shenzhen,Guangdong,","Country":"CN","SPOrg","B.BTech"},
{"providerID":"f02364899,City":Chengdu,Sichuan,","Country":"CN","SPOrg","S&D"},
{"providerID":"f02811050,City":Shenzhen,Guangdong,","Country":"CN","SPOrg","chimsen"},
{"providerID":"f02825666,City":Shenzhen,Guangdong,","Country":"CN","SPOrg","chimsen"},
{"providerID":"f02806931,City":Jiangmen,Guangdong,","Country":"CN","SPOrg","HCXYTech"},
{"providerID":"f02831252,City":Jiangmen,Guangdong,","Country":"CN","SPOrg","HCXYTech"},
{"providerID":"f01708981,City":Jiangmen,Guangdong,","Country":"CN","SPOrg","HCXYTech"},
{"providerID":"f02088858,City":London,England,","Country":"GB","SPOrg","chimsen"},
{"providerID":"f02817992,City":HongKong,CentralandWestern,","Country":"HK","SPOrg","68Tech"},
{"providerID":"f02817995,City":HongKong,CentralandWestern,","Country":"HK","SPOrg","68Tech"},
{"providerID":"f02817991,City":HongKong,CentralandWestern,","Country":"HK","SPOrg","68Tech"},
{"providerID":"f02817993,City":HongKong,CentralandWestern,","Country":"HK","SPOrg","68Tech"},
{"providerID":"f02636860,City":HongKong,CentralandWestern,","Country":"HK","SPOrg","68Tech"},
{"providerID":"f02810687,City":HongKong,CentralandWestern,","Country":"HK","SPOrg","68Tech"},
{"providerID":"f02828514,City":HongKong,CentralandWestern,","Country":"HK","SPOrg","DDTech"},
{"providerID":"f02826478,City":HongKong,CentralandWestern,","Country":"HK","SPOrg","DDTech"},
{"providerID":"f02806522,City":Ashburn,Virginia,","Country":"US","SPOrg","HCXYTech"},
{"providerID":"f02806528,City":Ashburn,Virginia,","Country":"US","SPOrg","HCXYTech"},
{"providerID":"f01854510,City":HongKong,CentralandWestern,","Country":"HK","SPOrg","3cloudtech"},
{"providerID":"f02838396,City":Aberdeen,Southern,","Country":"HK","SPOrg","ssdminer"},
{"providerID":"f02824610,City":Bangkok,Bangkok,","Country":"TH","SPOrg","personal"},
{"providerID":"f02825172,City":Bangkok,Bangkok,","Country":"TH","SPOrg","personal"},
{"providerID":"f02143523,City":HongKong,CentralandWestern,","Country":"HK","SPOrg","ssdminer"},
{"providerID":"f02016677,City":HongKong,CentralandWestern,","Country":"HK","SPOrg","ssdminer"},
{"providerID":"f01912211,City":HongKong,CentralandWestern,","Country":"HK","SPOrg","ssdminer"},
{"providerID":"f02211244,City":HongKong,CentralandWestern,","Country":"HK","SPOrg","ssdminer"},
{"providerID":"f02824865,City":HongKong,CentralandWestern,","Country":"HK","SPOrg","DDTech"},
{"providerID":"f02824414,City":HongKong,CentralandWestern,","Country":"HK","SPOrg","DDTech"},
{"providerID":"f01885088,City":HongKong,CentralandWestern,","Country":"HK","SPOrg","S&D"},
{"providerID":"f0693793,City":HongKong,CentralandWestern,","Country":"HK","SPOrg","S&D"},
{"providerID":"f02826888,City":Toronto,Ontario,","Country":"CA","SPOrg","chimsen"},
{"providerID":"f02827777,City":Mumbai,Maharashtra,","Country":"IN","SPOrg","chimsen"},
{"providerID":"f02806894,City":Paripark,Seoul,","Country":"KR","SPOrg","chimsen"},
{"providerID":"f02803754,City":Osaka,ﾅ茎aka,","Country":"JP","SPOrg","Personal"},
{"providerID":"f02519021,City":Singapore,Singapore,","Country":"SG","SPOrg","chimsen"},
{"providerID":"f02372022,City":Ōi,Saitama,","Country":"JP","SPOrg","chimsen"},]

**Comment by FroghubMan** [comment]
checker:manualTrigger

**Comment by Chuangshi1** [comment]
checker:manualTrigger

**Comment by Chuangshi1** [comment]
Everything goes well. Support.

**Comment by Chuangshi1** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceblgrvid4ys2e6x3q3szewumsfjdwoi6efjbl7z73hjy4hjry42pq 
#### Address 
> f1h2neemc5yldsckegrvyo5dq26ybo2i66ukgqsei
#### Datacap Allocated
> 2.00PiB
#### Signer Address
> f1mdk7s2vntzm6hu35yuo6vjubtrpfnb2awhgvrri
#### Id
> 97d9352d-5351-4eb3-a072-b45a65eee272
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceblgrvid4ys2e6x3q3szewumsfjdwoi6efjbl7z73hjy4hjry42pq

**Comment by sxxfuture-official** [comment]
Looks good to me, support  this round

**Comment by sxxfuture-official** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecfyzg63wrdrs3su5ltdi6pciysjsuul5bqqvfujg3zmicngnhx4a 
#### Address 
> f1h2neemc5yldsckegrvyo5dq26ybo2i66ukgqsei
#### Datacap Allocated
> 2.00PiB
#### Signer Address
> f1foiomqlmoshpuxm6aie4xysffqezkjnokgwcecq
#### Id
> 97d9352d-5351-4eb3-a072-b45a65eee272
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecfyzg63wrdrs3su5ltdi6pciysjsuul5bqqvfujg3zmicngnhx4a

**Comment by ipollo00** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec2ari7sgk3uzoyp4364gi3m2pascd3wayhi62q5dl4wt37hdfkzi 
#### Address 
> f1h2neemc5yldsckegrvyo5dq26ybo2i66ukgqsei
#### Datacap Allocated
> 2.00PiB
#### Signer Address
> f1n5wlrrhoxpkgwij25xrtt7w7g2k3fhbthmdn6ri
#### Id
> ee93279c-2ada-49b0-9d05-9bb83f020ebb
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec2ari7sgk3uzoyp4364gi3m2pascd3wayhi62q5dl4wt37hdfkzi

**Comment by SuperChaiChai** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacect3ehndenpibv76i7mfpyodvjkokq6liajlpubibv5oiq4k6iytu 
#### Address 
> f1h2neemc5yldsckegrvyo5dq26ybo2i66ukgqsei
#### Datacap Allocated
> 2.00PiB
#### Signer Address
> f12mckci3omexgzoeosjvstcfxfe4vqw7owdia3da
#### Id
> ee93279c-2ada-49b0-9d05-9bb83f020ebb
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacect3ehndenpibv76i7mfpyodvjkokq6liajlpubibv5oiq4k6iytu

**Comment by FroghubMan** [comment]
Keep going

**Comment by 1ane-1** [comment]
checker:manualTrigger

**Comment by 1ane-1** [comment]
It looks great.

**Comment by 1ane-1** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedlcyleqwcr5llrdfkjnipk2elkalrsk5bxcjcymisuxwtg725dbo 
#### Address 
> f1h2neemc5yldsckegrvyo5dq26ybo2i66ukgqsei
#### Datacap Allocated
> 1.00PiB
#### Signer Address
> f1mdk7s2vntzm6hu35yuo6vjubtrpfnb2awhgvrri
#### Id
> a78d253a-486d-42a2-b49c-47decb31c77c
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedlcyleqwcr5llrdfkjnipk2elkalrsk5bxcjcymisuxwtg725dbo

**Comment by AlanGreaterheat** [comment]
checker:manualTrigger

**Comment by AlanGreaterheat** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedjype47h2w4yuwnszkv5gipyy5u4o3y7pgoln35wf44wergngzl4 
#### Address 
> f1h2neemc5yldsckegrvyo5dq26ybo2i66ukgqsei
#### Datacap Allocated
> 1.00PiB
#### Signer Address
> f1pnmzlxj7cfeo2v6oj5nco46hkg2l46wj7o4xxui
#### Id
> a78d253a-486d-42a2-b49c-47decb31c77c
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedjype47h2w4yuwnszkv5gipyy5u4o3y7pgoln35wf44wergngzl4

**Comment by laurarenpanda** [comment]
checker:manualTrigger

**Comment by laurarenpanda** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced4g6cxvkdq6w5xhggjbxnyom3htb6k73wdtxhbs3nbak3hty3eyy 
#### Address 
> f1h2neemc5yldsckegrvyo5dq26ybo2i66ukgqsei
#### Datacap Allocated
> 1.00PiB
#### Signer Address
> f1bp3tzp536edm7dodldceekzbsx7zcy7hdfg6uzq
#### Id
> 63b6075b-15f7-41bd-9c7c-8b4d07eef0e2
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced4g6cxvkdq6w5xhggjbxnyom3htb6k73wdtxhbs3nbak3hty3eyy

**Comment by nj-steve** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaoc5tr5sut5hk3x64ztggstr2otl3oecnwljipr5vtjahjb6w63c 
#### Address 
> f1h2neemc5yldsckegrvyo5dq26ybo2i66ukgqsei
#### Datacap Allocated
> 1.00PiB
#### Signer Address
> f1xx6555qijma7igpnjspyvdunc4vfxkawnpqy5ii
#### Id
> 63b6075b-15f7-41bd-9c7c-8b4d07eef0e2
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaoc5tr5sut5hk3x64ztggstr2otl3oecnwljipr5vtjahjb6w63c
