### ISSUE TITLE
[DataCap Application] NREL National Solar Radiation Database

### ISSUE THREAD

**Issue by FroghubMan** [filecoin-project/filecoin-plus-large-datasets#2117]
### Data Owner Name

NREL

### What is your role related to the dataset

Data Preparer

### Data Owner Country/Region

United States

### Data Owner Industry

Environment

### Website

https://nsrdb.nrel.gov/

### Social Media

```text
https://registry.opendata.aws/nrel-pds-nsrdb/
https://nsrdb.nrel.gov/
```

### Total amount of DataCap being requested

8PiB

### Expected size of single dataset (one copy)

800

### Number of replicas to store

10

### Weekly allocation of DataCap requested

1PiB

### On-chain address for first allocation

f16eoaknzqxdw3rgqcv7kx5xs65my2rub6yoliswa

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
FrogHub files is a platform that will provide users with free storage, allowing users to enjoy free storage at the same time. Facilitating the Filecoin network to store more and more valuable public data sets.

About the FrogHub data set

FrogHub files is a user-oriented cloud storage platform. Any user with data storage needs can use the platform tools free of charge.

The Filecoin Network provides reliable, secure, and affordable decentralized storage, and FrogHub files wants to make it easy for users to store their data in the filecoin network.

Attracting traditional cloud and object-based storage users to the Filecoin network and benefiting from it is a challenge. FrogHub, as developers in the Felicoin ecosystem, needs to face this challenge together. We've been building useful tools to make it easier for users to store data on the Filecoin network.

Froghub files integrates a set of tools, including storage bucket, custom gateway, data encryption service KMS, static web deployment (under development), open API, to provide storage services compatible with cloud storage and object storage, providing better user experience and attracting more users.
FrogHub has always defined itself as a tool developer and infrastructure builder in the Filecoin ecosystem. In 2019, we started to focus on technical solutions and development based on the IPFS protocol and Filecoin network. We have been working hard to become a qualified builder in the filecoin ecosystem.

Our team is a very pure development team, more than 90% of which are developers, more than half of whom have more than 5 years of development experience in communication, Internet, blockchain and other industries. We hope that we can gain users' recognition by exporting useful tools and platforms.

In order to contribute to the filecoin community, we have developed the open source sector repair tool Filecoin-Sealer-Recover and the nft free authoring platform NFT-Creator.
In addition, we plan to provide a sector browser for the community in 2023 and build the liquidity pledge platform STFIL on FVM.

See the links below for details.
- github: https://github.com/orgs/froghub-io
- twitter: https://twitter.com/froghub_io
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
"Released to the public as part of the Department of Energy's Open Energy Data Initiative, the National Solar Radiation Database (NSRDB) is a serially complete collection of hourly and half-hourly values of the three most common measurements of solar radiation – global horizontal, direct normal, and diffuse horizontal irradiance — and meteorological data. These data have been collected at a sufficient number of locations and temporal and spatial scales to accurately represent regional solar radiation climates."

Source: https://registry.opendata.aws/nrel-pds-nsrdb/
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### Has this dataset been stored on the Filecoin network before? If so, please explain and make the case why you would like to store this dataset again to the network. Provide details on preparation and/or SP distribution.

```text
I saw that although some people have applied for the storage of this data, they have not implemented it. And the related application is closed, so I want to store it.
```

### Please share a sample of the data

```text
s3://nrel-pds-nsrdb/ (420.8 TiB)
s3://nrel-pds-nsrdb/v3/(47.5 TiB)
s3://nrel-pds-nsrdb/v3/tmy/(4.0 TiB)
s3://nrel-pds-nsrdb/v3/tdy/(4.0 TiB)
s3://nrel-pds-nsrdb/v3/tgy/(4.0 TiB)
s3://nrel-pds-nsrdb/v3/puerto_rico/(114.6 GiB)
s3://nrel-pds-nsrdb/conus/(48.2 TiB)
s3://nrel-pds-nsrdb/full_disc/(81.8 TiB)
s3://nrel-pds-nsrdb/meteosat/(16.1 TiB)
s3://nrel-pds-nsrdb/himawari/(189.1 TiB)
s3://nrel-pds-nsrdb/india/(515.3 GiB)
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

2 to 3 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, Europe

### How will you be distributing your data to storage providers

Cloud storage (i.e. S3), Shipping hard drives

### How do you plan to choose storage providers

Slack, Big Data Exchange, Partners

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
> Has this dataset been stored on the Filecoin network before? If so, please explain and make the case why you would like to store this dataset again to the network. Provide details on preparation and/or SP distribution.
> I saw that although some people have applied for the storage of this data, they have not implemented it. And the related application is closed, so I want to store it.

https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1995
What's the relationship between two applications?
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1104
This dataset has been stored before.

- Have you prepared enough token for sector pledge?
- Are you a data preparer? What is your previous experience as a data-preparer?
- If you are not preparing the data, who will prepare the data?  (Name and Business)
- Best practice for storing large datasets includes ideally, storing it in 3 or more regions, with 4 or more storage provider operators or owners.You should list Miner ID, Business Entity, Location of sps you will cooperate with.
- 
Could you send an email to filplus-app-review@fil.org with your official domain in order to confirm your identity? Email name should includes the issue id #2117.

**Comment by FroghubMan** [comment]
1. We have nothing to do with #1995. (I just found out that the names are somewhat similar.)
2. #1104 stored data. I just discovered this too, so can I continue to store it?
3. We are data preparer, and have experience and confidence to complete. Colleagues comply with FIL+ rules.
4. I have sent a confirmation email.

**Comment by FroghubMan** [comment]
@Sunnyiscoming  I found some valuable public datasets from closed applications that had been passed but not actually implemented. The SP I'm working with has strong storage needs, so I want to get started quickly on storing this data.

**Comment by kevzak** [comment]
Hi @FroghubMan - the one thing missing here is information about SP entities you are working with. Can you map that out publicly here?

**Comment by FroghubMan** [comment]
Hi @kevzak ，Honestly, it's hard to get some SPs to expose their entities for some reason (I could totally fake it, but it's obviously not necessary.). Hope you understand. But I can fully guarantee the authenticity and effectiveness of these nodes, and they will store data fully satisfy the FIL+ rules.

**Comment by FroghubMan** [comment]
| MinerID | City | Continent |
| --------- | ---------- | --------- |
| f01811024 | HongKong | CN |
| f0827006 | Tokyo | Japan |
| f02227726 | HongKong | CN |
| f02195153 | Tokyo | Japan |
| f02098006 | Krabi | Thailand |
| f02223012 | Hebei | CN |
| f02235154 | HongKong | CN |
| f02085722 | Jiangmen | CN |

**Comment by Filplus-govteam** [comment]
Left a [comment](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/2119#issuecomment-1656107816) on 2119

**Comment by FroghubMan** [comment]
Hi @Filplus-govteam @Sunnyiscoming ,I have submitted the information in #2119, please review it for me. Thank you very much.

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 8PiB

**Expected weekly DataCap usage rate**
> 1PiB

**Client address**
>f16eoaknzqxdw3rgqcv7kx5xs65my2rub6yoliswa

**Comment by FroghubMan** [comment]
We are preparing the data.

**Comment by FroghubMan** [comment]
Hi @Sunnyiscoming ,We have been preparing data, only to find that it was closed. We have now completed the prep function, can you reopen this application for me?

**Comment by FroghubMan** [comment]
![Screenshot_20230831_100606_Gmail](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/88960777/0194b0d1-36f1-45d9-8b3f-567c4e363f1a)

**Comment by Chuangshi1** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebvlehaycc44xzoeur6nmwh775fb5yhybp6vw42laryo4dphs5xmy 
#### Address 
> f16eoaknzqxdw3rgqcv7kx5xs65my2rub6yoliswa
#### Datacap Allocated
> 409.59TiB
#### Signer Address
> f1mdk7s2vntzm6hu35yuo6vjubtrpfnb2awhgvrri
#### Id
> d0b265f9-d692-48b7-b3ff-4ba776f6dbf5
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebvlehaycc44xzoeur6nmwh775fb5yhybp6vw42laryo4dphs5xmy

**Comment by AlanGreaterheat** [comment]
Client reached out to me via slack as the first round of a public dataset and is willing to support it, looking forward to seeing the first round of sealing reports.

**Comment by AlanGreaterheat** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedm4nlkeuzv6ch3ysi7wurt7oq6r2xotdsjxthwsvk7ehty27ywlm 
#### Address 
> f16eoaknzqxdw3rgqcv7kx5xs65my2rub6yoliswa
#### Datacap Allocated
> 409.59TiB
#### Signer Address
> f1pnmzlxj7cfeo2v6oj5nco46hkg2l46wj7o4xxui
#### Id
> d0b265f9-d692-48b7-b3ff-4ba776f6dbf5
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedm4nlkeuzv6ch3ysi7wurt7oq6r2xotdsjxthwsvk7ehty27ywlm

**Comment by FroghubMan** [comment]
thank you!

**Comment by FroghubMan** [comment]
We're preparing dataset.

**Comment by spaceT9** [comment]
checker:manualTrigger

**Comment by FroghubMan** [comment]
We're preparing dataset.

**Comment by FroghubMan** [comment]
We're preparing data

**Comment by FroghubMan** [comment]
checker:manualTrigger

**Comment by FroghubMan** [comment]
checker:manualTrigger

**Comment by FroghubMan** [comment]
checker:manualTrigger

**Comment by FroghubMan** [comment]
checker:manualTrigger

**Comment by FroghubMan** [comment]
checker:manualTrigger

**Comment by FroghubMan** [comment]
checker:manualTrigger

**Comment by FroghubMan** [comment]
checker:manualTrigger

**Comment by FroghubMan** [comment]
checker:manualTrigger

**Comment by FroghubMan** [comment]
checker:manualTrigger

**Comment by FroghubMan** [comment]
![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/88960777/a57b281e-9aca-443b-abcf-a59c414032c6)
![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/88960777/0f5eb928-0000-4a95-a8ca-158c2851bcba)

**Comment by FroghubMan** [comment]
checker:manualTrigger

**Comment by mikezli** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceafgmzoqlhp3nkp2qxfd2vp4dsoybxkmbj5zhf2nu7dlp67v2sbyg 
#### Address 
> f16eoaknzqxdw3rgqcv7kx5xs65my2rub6yoliswa
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f1dnb3uz7sylxk6emti3ififcvu3nlufnnsjui6ea
#### Id
> 6530207c-de9b-4b67-8cbf-02682adbbf30
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceafgmzoqlhp3nkp2qxfd2vp4dsoybxkmbj5zhf2nu7dlp67v2sbyg

**Comment by Tom-OriginStorage** [comment]
checker:manualTrigger

**Comment by Tom-OriginStorage** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacea2phsgda6qtp7i5yykykxmybrzww5k7d7fr7pzyjjo7cxkthnw44 
#### Address 
> f16eoaknzqxdw3rgqcv7kx5xs65my2rub6yoliswa
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f1q6bpjlqia6iemqbrdaxr2uehrhpvoju3qh4lpga
#### Id
> 6530207c-de9b-4b67-8cbf-02682adbbf30
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacea2phsgda6qtp7i5yykykxmybrzww5k7d7fr7pzyjjo7cxkthnw44

**Comment by 1ane-1** [comment]
checker:manualTrigger

**Comment by 1ane-1** [comment]
Storage Provider Distribution is ok and report look great. Hope you can add more sps in the future. It will be better.

**Comment by 1ane-1** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecmba5yvpr2usfsxgtleewaz5m6xvo3plj2l3emgidviseh7t2hug 
#### Address 
> f16eoaknzqxdw3rgqcv7kx5xs65my2rub6yoliswa
#### Datacap Allocated
> 1.00PiB
#### Signer Address
> f1mdk7s2vntzm6hu35yuo6vjubtrpfnb2awhgvrri
#### Id
> b53df7da-4392-4f39-8d08-545da491e47a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecmba5yvpr2usfsxgtleewaz5m6xvo3plj2l3emgidviseh7t2hug

**Comment by sxxfuture-official** [comment]
LGTM. will support

**Comment by sxxfuture-official** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebeitarhe2dgh23pv5robkqlshv6n7irlk2kkvtnfuoyp3rxsj6f2 
#### Address 
> f16eoaknzqxdw3rgqcv7kx5xs65my2rub6yoliswa
#### Datacap Allocated
> 1.00PiB
#### Signer Address
> f1foiomqlmoshpuxm6aie4xysffqezkjnokgwcecq
#### Id
> b53df7da-4392-4f39-8d08-545da491e47a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebeitarhe2dgh23pv5robkqlshv6n7irlk2kkvtnfuoyp3rxsj6f2

**Comment by FroghubMan** [comment]
checker:manualTrigger

**Comment by laurarenpanda** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced2dfy2bztpvoq47qz4l4aackpowqfmvts3ibciyhdqda4xlmku2s 
#### Address 
> f16eoaknzqxdw3rgqcv7kx5xs65my2rub6yoliswa
#### Datacap Allocated
> 1.00PiB
#### Signer Address
> f1bp3tzp536edm7dodldceekzbsx7zcy7hdfg6uzq
#### Id
> b53df7da-4392-4f39-8d08-545da491e47a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced2dfy2bztpvoq47qz4l4aackpowqfmvts3ibciyhdqda4xlmku2s

**Comment by Filplus-govteam** [comment]
@FroghubMan SPs do not match the list submitted upfront. Closing until clarified
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/2117#issuecomment-1654947344

**Comment by FroghubMan** [comment]
Hi @Filplus-govteam ,Thank you for your attention. 
The actual allocated miner node is different from the miner node during KYC because if the data preparation time is long, some SPs will first store other available datacaps for the sake of equipment usage efficiency. When the storage power of the miner node reaches a certain value, SPs will consider creating a new miner node. Therefore, over time, changes in the miner node that stores datacap are inevitable.

However, we ensure that everything strictly abides by the rules of FIL+, and we can complete KYC for new nodes:

| MinerID | Entity | City | Continent |
| --------- | ---------- | ---------- | --------- |
| f02816837 | D.D Tech |  Shenzhen, Guangdong, |CN|
| f02364899 | S&D  | Chengdu, Sichuan, |CN|
| f02811050 | chimsen |   Shenzhen, Guangdong, |CN|
| f02806931 | HCXY Tech | Jiangmen, Guangdong, |CN|
| f02831252 | HCXY Tech | Jiangmen, Guangdong, |CN|
| f02817991 | 68Tech|   Hong Kong, Central and Western, |  HK| 
| f02817992 | 68Tech |  Hong Kong, Central and Western, |  HK| 
| f02810687 | D.D Tech |  Hong Kong, Central and Western, |  HK| 
| f02636860 | D.D Tech |  Hong Kong, Central and Western, |  HK| 
| f02806522 | HCXY Tech | Ashburn, Virginia, |US|
| f02806528 | HCXY Tech | Ashburn, Virginia, |US|
| f02211244 | ssdminer|  Hong Kong, Central and Western, |  HK| 
| f0693793 | S&D |  Hong Kong, Central and Western, |  HK| 
| f01885088 | S&D |  Hong Kong, Central and Western,|  HK| 
| f02806894 | chimsen|    Paripark, Seoul, | KR| 
| f02372022|  chimsen|    Ōi, Saitama, | JP| 
| f02826888 | chimsen |   Toronto, Ontario,|  CA| 
| f02827777 | chimsen |   Mumbai, Maharashtra, | IN|

**Comment by FroghubMan** [comment]
Hi @Filplus-govteam ,,I submitted the KYC form for #2117  #2119. please check

**Comment by 1ane-1** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced5ggk6w2fev2vyuskvyhavckaoyseq4ldvycj6pz6ehkm6qmp4u6 
#### Address 
> f16eoaknzqxdw3rgqcv7kx5xs65my2rub6yoliswa
#### Datacap Allocated
> 1.00PiB
#### Signer Address
> f1mdk7s2vntzm6hu35yuo6vjubtrpfnb2awhgvrri
#### Id
> b53df7da-4392-4f39-8d08-545da491e47a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced5ggk6w2fev2vyuskvyhavckaoyseq4ldvycj6pz6ehkm6qmp4u6

**Comment by NDLABS-Leo** [comment]
checker:manualTrigger

**Comment by Bitrise0111** [comment]
We‘ve checked the report and we're willing to support for this round since their report shows healthy.

**Comment by Bitrise0111** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebr2jrw65uscabew5y5lmnwv26pwqzhmfqqga2inrmjijczbnorfq 
#### Address 
> f16eoaknzqxdw3rgqcv7kx5xs65my2rub6yoliswa
#### Datacap Allocated
> 2.00PiB
#### Signer Address
> f1nknj7ayq4o43czrtdoauggtwl43fbqatmqis3yy
#### Id
> bbb9c1f7-0c0a-4862-9c5f-663d61a5c553
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebr2jrw65uscabew5y5lmnwv26pwqzhmfqqga2inrmjijczbnorfq

**Comment by Sunnyiscoming** [comment]
SP List provided:
[{"providerID": "f01811024", "City": "HongKong", "Country": "CN", "SPOrg","chimsen"},
{"providerID": "f0827006", "City": "Tokyo", "Country": "JAPAN","SPOrg","FrogStorage"},
{"providerID": "f02227726", "City": "HongKong", "Country": "CN","SPOrg","Three Clouds"},
{"providerID": "f02195153", "City": "Tokyo", "Country": "JAPAN","SPOrg","XYZ"},
{"providerID": "f02098006", "City": "Krabi", "Country": "Thailand","SPOrg","XYZ"},
{"providerID": "f02223012", "City": "Hebei", "Country": "CN","SPOrg","Person"},
{"providerID": "f02235154", "City": "HK", "Country": "CN","SPOrg","XYZ"},
{"providerID": "f02085722", "City": "Jiangmen", "Country": "CN","SPOrg","Chimsen"},]

**Comment by nj-steve** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedi6vuji3jnqqyj7xkvhjx4azojnwpiest7p7onalbpfgdblwodu4 
#### Address 
> f16eoaknzqxdw3rgqcv7kx5xs65my2rub6yoliswa
#### Datacap Allocated
> 2.00PiB
#### Signer Address
> f1xx6555qijma7igpnjspyvdunc4vfxkawnpqy5ii
#### Id
> bbb9c1f7-0c0a-4862-9c5f-663d61a5c553
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedi6vuji3jnqqyj7xkvhjx4azojnwpiest7p7onalbpfgdblwodu4

**Comment by nj-steve** [comment]
The reports look good, willing to support.

**Comment by FroghubMan** [comment]
Stay active

**Comment by FroghubMan** [comment]
checker:manualTrigger

**Comment by Chuangshi1** [comment]
The  report shows good. Support

**Comment by Chuangshi1** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecpt252s32zddbgmrljkmwf7akro7emyrewd7uccrh6gpviksxajk 
#### Address 
> f16eoaknzqxdw3rgqcv7kx5xs65my2rub6yoliswa
#### Datacap Allocated
> 2.00PiB
#### Signer Address
> f1mdk7s2vntzm6hu35yuo6vjubtrpfnb2awhgvrri
#### Id
> d816efcf-23a3-4add-86b4-4d9e35806eca
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecpt252s32zddbgmrljkmwf7akro7emyrewd7uccrh6gpviksxajk

**Comment by kernelogic** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedlioat2druh7ezc4vc2a5lkbbi65qvz2wty422fkfefveychbzos 
#### Address 
> f16eoaknzqxdw3rgqcv7kx5xs65my2rub6yoliswa
#### Datacap Allocated
> 2.00PiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### Id
> d816efcf-23a3-4add-86b4-4d9e35806eca
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedlioat2druh7ezc4vc2a5lkbbi65qvz2wty422fkfefveychbzos

**Comment by kernelogic** [comment]
Report looks healthy.

**Comment by ipollo00** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebfsyuq5ow3t7zfw6ihr5y4aafzppg2f34urimc6rj53g424r3qhu 
#### Address 
> f16eoaknzqxdw3rgqcv7kx5xs65my2rub6yoliswa
#### Datacap Allocated
> 2.00PiB
#### Signer Address
> f1n5wlrrhoxpkgwij25xrtt7w7g2k3fhbthmdn6ri
#### Id
> 897b1d8f-1267-4f9f-b65b-17853e272ec6
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebfsyuq5ow3t7zfw6ihr5y4aafzppg2f34urimc6rj53g424r3qhu

**Comment by NiwanDao** [comment]
LGTM

**Comment by NiwanDao** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceasno4puaswslpo3ldgpo7vdrxjeergplq6jrpn4oyfb26yzokmt2 
#### Address 
> f16eoaknzqxdw3rgqcv7kx5xs65my2rub6yoliswa
#### Datacap Allocated
> 2.00PiB
#### Signer Address
> f1a2lia2cwwekeubwo4nppt4v4vebxs2frozarz3q
#### Id
> 897b1d8f-1267-4f9f-b65b-17853e272ec6
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceasno4puaswslpo3ldgpo7vdrxjeergplq6jrpn4oyfb26yzokmt2

**Comment by xiaoyuaiheshui** [comment]
stay active

**Comment by FroghubMan** [comment]
Keep going
