### ISSUE TITLE
[DataCap应用程序] <新颜人工智能> - <模型数据>

### ISSUE THREAD

**Issue by fylsan3** [filecoin-project/filecoin-plus-large-datasets#2118]
### Data Owner Name

上海新颜人工智能科技有限公司

### What is your role related to the dataset

Dataset Owner

### Data Owner Country/Region

China

### Data Owner Industry

IT & Technology Services

### Website

https://xinyan.com    https://www.xinyan-ai.com

### Social Media

```text
QR code of WeChat official account at the bottom of official website
```

### Total amount of DataCap being requested

10PiB

### Expected size of single dataset (one copy)

1P

### Number of replicas to store

10

### Weekly allocation of DataCap requested

1PiB

### On-chain address for first allocation

f16bxqdvcliy3x2o4q7w2q5dm4zj4tls6pfsjpmma

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
https://www.xinyan-ai.com/about.html
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
Graphic image recognition model training data
ORC model training data
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### Please share a sample of the data

```text
https://www.robots.ox.ac.uk/~vgg/data/scenetext/
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [ ] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

1.5 to 2 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China

### How will you be distributing your data to storage providers

Cloud storage (i.e. S3), HTTP or FTP server, IPFS, Lotus built-in data transfer

### How do you plan to choose storage providers

Slack, Big Data Exchange, Partners

### How do you plan to make deals to your storage providers

Boost client, Lotus client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
- Have you prepared enough token for sector pledge?
- Are you a data preparer? What is your previous experience as a data-preparer? List previous applications and client IDs
- How will the data be prepared? Please include tooling used and technical details
- If you are not preparing the data, who will prepare the data?  (Name and Business)
- Has this dataset been stored on Filecoin before? If so, why are you choosing to store it again?
- Best practice for storing large datasets includes ideally, storing it in 3 or more regions, with 4 or more storage provider operators or owners.You should list Miner ID, Business Entity, Location of sps you will cooperate with.
- Could you send an email to filplus-app-review@fil.org with your official domain in order to confirm your identity? Email name should includes the issue id #2118 .

**Comment by fylsan3** [comment]
1. We have enough tokens to consume
2. We used to do personal credit reporting business, but later due to policy restrictions, this business disappeared. The source and processing of data that you know are important for credit reporting, and we need to establish a strict data model. I found a news article from a long time ago that you can take a look at“ https://www.yicaiglobal.com/news/two-firms-are-investigated-as-china-online-loan-regulations-extend-to-big-data ”. About us
3. We will prepare the data ourselves

I have sent an email and thank you for your support.

**Comment by Filplus-govteam** [comment]
Hello @fylsan3 Per the https://github.com/filecoin-project/notary-governance/issues/922 for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

This information will be reviewed by Fil+ Governance team to confirm validity and then the application will be triggered for notary review. Let us know if you have any questions.

**Comment by Sunnyiscoming** [comment]
Received email.
I have questions about whether the data can be fully disclosed after reading the report.
Best practice for storing large datasets includes ideally, storing it in 3 or more regions, with 4 or more storage provider operators or owners.You should list Miner ID, Business Entity, Location of sps you will cooperate with.

**Comment by Sunnyiscoming** [comment]
Any update here?

**Comment by fylsan3** [comment]
@Sunnyiscoming  We filled out the form [Fil+ registration form], we are ready，thanks

**Comment by Filplus-govteam** [comment]
Confirming the following SP Entities were submitted:
f02234424  algorithdata USA
f02246008 Calculus  Hong Kong
f0222811 HanTangcloud Hangzhou
f02274504 Dotdata  Shenzhen
f02220982 interstellar cloud Guangzhou

we are contacting to confirm locations

**Comment by fylsan3** [comment]
Hello, @Filplus-govteam  We verified that the address is real and not using a VPN, what else do I need to do next? @Sunnyiscoming Can you pass us?

**Comment by Sunnyiscoming** [comment]
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/2118#issuecomment-1667670456
Contacting to confirm locations.

**Comment by fylsan3** [comment]
@Filplus-govteam   @Sunnyiscoming can you tell me contact email or slack to confirm, we have not  received any message, but we have applied for a long time

**Comment by Filplus-govteam** [comment]
@fylsan3 no word from f02234424

**Comment by Filplus-govteam** [comment]
> Hello, @Filplus-govteam We verified that the address is real and not using a VPN, what else do I need to do next? @Sunnyiscoming Can you pass us?

@fylsan3 how did you verify that is not using VPN?

**Comment by fylsan3** [comment]
Hello, https://www.filutils.com/zh/miner/f02234424 is normal, this is f02234424ip

1. The external active access ip is 38.32.189.82,
2. The externally declared identity ip is 38.32.189.83:52233

We are working hard to find the sp. If you think there is something wrong with this f02234424,  we don't cooperate with this SP.

 We can cooperate with "f02058333". The location is also in the United States, Or, we can cooperate with f02199203, it is in China,please confirm! 

If you think they are not suitable, please let me know as soon as possible, we will look for other SP cooperation. Thank you for your hard work.

In the end, I confirmed with the SP we contacted very seriously, none of them used VPN, Although this is a verbal promise from sp, but I choose to believe them, If we find that sp is dishonest, we will immediately cancel our cooperation with them!

f02234424 algorithdata USA
f02246008 Calculus Hong Kong
f0222811 HanTangcloud Hangzhou
f02274504 Dotdata Shenzhen
f02220982 interstellar cloud Guangzhou

f02058333  algorithdata USA
f02199203  individual investor

Finally, please pass us as soon as possible. Regarding the cooperative SP, we can completely listen to your arrangements. If you think any sp is not suitable, we will stop cooperating with them immediately. If you have a recommended SP, please let me know , we will work with them right away. Thanks again!

**Comment by Filplus-govteam** [comment]
@fylsan3 you can work with any SPs you choose. We'll monitor the list above. Thank you. FYI @Sunnyiscoming

**Comment by fylsan3** [comment]
Okay, I hope to get your continued attention, so, can you approve our request? @Sunnyiscoming @Filplus-govteam

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 10PiB

**Expected weekly DataCap usage rate**
> 1PiB

**Client address**
>f16bxqdvcliy3x2o4q7w2q5dm4zj4tls6pfsjpmma

**Comment by Casey-PG** [comment]
Based on the information provided above, I'm willing to support the first round. Hope you keep the Fil+rules.

**Comment by Casey-PG** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceanmemmfdrm3luhauijkwcu6yss5uedqztzmn2anfeo4kbpzc6mpy 
#### Address 
> f16bxqdvcliy3x2o4q7w2q5dm4zj4tls6pfsjpmma
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f1d4yb3wags3mtddzesxoo63jv7dmlec3bq4yteni
#### Id
> 9ed7f648-c2fa-4abd-8263-026b784904d3
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceanmemmfdrm3luhauijkwcu6yss5uedqztzmn2anfeo4kbpzc6mpy

**Comment by ipollo00** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacea4ismyefuxncdpy27ejqqobaejh73hjy25oshd3h7aqrfkiumftg 
#### Address 
> f16bxqdvcliy3x2o4q7w2q5dm4zj4tls6pfsjpmma
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f1n5wlrrhoxpkgwij25xrtt7w7g2k3fhbthmdn6ri
#### Id
> 9ed7f648-c2fa-4abd-8263-026b784904d3
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacea4ismyefuxncdpy27ejqqobaejh73hjy25oshd3h7aqrfkiumftg

**Comment by cryptowhizzard** [comment]
checker:manualTrigger

**Comment by cryptowhizzard** [comment]
@fylsan3 

What about distribution?

You used all your datacap and send it to one SP?

**Comment by cryptowhizzard** [comment]
Secondly:

I tried to retrieve something from SP f02246008 to do due diligence but it seems they are not open for fast retrieval.
To verify your data, can you please be so kind to upload to http://send.datasetcreators.com :

baga6ea4seaqklofxon7hemedalc4injfkzgc6votrqkw6n35bfrnk5utg4gq4da 

I want to unpack it and check your data.

**Comment by fylsan3** [comment]
![WechatIMG583](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/16700365/c8341424-7702-40ed-bdfa-83f6ad4e277a)
We have prepared 200T of data and it will take time to transfer it to the SP (we use the network and offline hard disk mailing). Therefore, for the time being, we will only issue an order for f02246008, which has already completed the data transfer. We also noticed that there are problems with the retrieval of this node, and SP has reported that the retrieval index construction was not successful, which is currently under repair. Therefore, we have temporarily stopped issuing further orders. We will also initiate an order after other SPs receive the data in the future, and we will ensure that the distribution of the data complies with community rules. We will upload the corresponding data that needs to be checked as soon as possible. Thank you for your attention.

**Comment by fylsan3** [comment]
Hello, we only sent 20% to this SP, we will not send to this SP again, maybe you should be patient and wait for the bot report.

**Comment by herrehesse** [comment]
Flagging for abuse & selfdealing @simonkim0515 @kevzak

**Comment by cryptowhizzard** [comment]
Dear fylsan3,

As notary I am doing due diligence on your LDN. I could not get retrieval to work. Can you please upload the car file of CID baga6ea4seaqklofxon7hemedalc4injfkzgc6votrqkw6n35bfrnk5utg4gq4da ?

You can use our upload system at http://send.datasetcreators.com. Please select 7 days for the system to keep the file and post the link you received here so I (and other notaries) can download your content.

**Comment by fylsan3** [comment]
hi, baga6ea4seaqklofxon7hemedalc4injfkzgc6votrqkw6n35bfrnk5utg4gq4da corresponds to a car with 35G, http://send.datasetcreators.com can only support files up to 32.7G, so it may not be able to upload. So we let baga6ea4seaqklofxon7hemedalc4injfkzgc6votrqkw6n35bfrnk5utg4gq4da be preferentially encapsulated by other sps, and f02246008 can now be retrieved successfully. We tested the retrieval of f02246008 and it is now very fast:
"lotus client retrieve --provider f02246008 bafykbzaceb4gylfri63q6s4kjhonivijt4rd7iem3e4mh5mmt5eloow7dfmbw baga6ea4seaqklofxon7hemedalc4injfkzgc6votrqkw6n35bfrnk5utg4gq4da .car"
So you can retrieve and download from f02246008 immediately, or wait for about 24 hours to retrieve from f0222811, f02220982, f02199203 and other nodes.
We hope to get your support and kind treatment, thank you!
![WechatIMG595](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/16700365/66ac02b2-624f-4c53-a665-30c5017b8535)

**Comment by cryptowhizzard** [comment]
At this moment i don't have other means to check your data. I hope to do DD in the near future then for you.

**Comment by laurarenpanda** [comment]
checker:manualTrigger

**Comment by laurarenpanda** [comment]
The CID report looks good to me.
Hope more SPs from Asia-GCN can join and store data for this program.
Willing to support this round.

**Comment by laurarenpanda** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaywtv7bcc4l7gayqsgtcegwjeiwb2gfl6odbcffynmyaff3cegms 
#### Address 
> f16bxqdvcliy3x2o4q7w2q5dm4zj4tls6pfsjpmma
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f1bp3tzp536edm7dodldceekzbsx7zcy7hdfg6uzq
#### Id
> 4d77ff2c-b1e2-4aff-aeda-609645a14e3e
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaywtv7bcc4l7gayqsgtcegwjeiwb2gfl6odbcffynmyaff3cegms

**Comment by kevzak** [comment]
checker:manualTrigger

**Comment by kevzak** [comment]
SP list provided:
f02234424 algorithdata USA
f02058333 algorithdata USA
f02246008 Calculus Hong Kong
f0222811 HanTangcloud Hangzhou
f02274504 Dotdata Shenzhen
f02220982 interstellar cloud Guangzhou
f02199203 individual investor

SPs taking deals:
f02220982 | Guangzhou, Guangdong, CNChina Mobile communications corporation | 42.75 TiB | 8.71% | 42.75 TiB | 0.00%
**f02199203** | Hohhot, Inner Mongolia, CNCHINA UNICOM China169 Backbone | 113.63 TiB | 23.16% | 113.63 TiB | 0.00%
f02221110 | Shenzhen, Guangdong, CNCHINANET-BACKBONE | 51.00 TiB | 10.39% | 51.00 TiB | 0.00%
f02200472 | Chengdu, Sichuan, CNCHINANET-BACKBONE | 704.00 GiB | 0.14% | 704.00 GiB | 0.00%
**f0222811** | Hangzhou, Zhejiang, CNCT-HangZhou-IDC | 9.06 TiB | 1.85% | 9.06 TiB | 0.00%
f02274504 | Shenzhen, Guangdong, CNCTGNet | 116.75 TiB | 23.79% | 116.69 TiB | 0.05%
**f02246008** | Hong Kong, Central and Western, HKHKBN Enterprise Solutions HK Limited | 153.00 TiB | 31.18% | 151.75 TiB | 0.82%
f01920887 | Melbourne, Victoria, AUVocus Connect International Backbone | 3.78 TiB | 0.77% | 3.78 TiB | 0.00%


@fylsan3 I'm seeing three SP IDs matching the list you provided. Please explain the discrepancy

**Comment by fylsan3** [comment]
Dear, thank you for your attention and support, as you can see, we initially filled out 5 SPs, and we matched 3 of them, the 2 SPs that were not matched were US SPs because the distance was relatively long, when our hard drive Mailed to the United States, SP told me that due to market reasons, it will not be packaged temporarily, so we are actively contacting other nodes. Sorry for causing trouble to you.
Since we filled in 10 copies when filling out the application form, we are working hard to increase the number of cooperative SPs to 10. According to your request, we have listed the SPs we are working with again. If you have any questions, Welcome you contact me anytime, thank you for your attention and support, I wish you a happy life!
f02246008：Hong Kong
f02199203：Inner Mongolia
f01920887：Australia
f02122388：Guangdong
f02221110：Guangzhou
f02221111：Guangzhou
f0222811：Hangzhou
f02519843：Tianjin
f02370792：Guangdong

**Comment by Tom-OriginStorage** [comment]
checker:manualTrigger

**Comment by Tom-OriginStorage** [comment]
The report shows good, willing to support this round

**Comment by Tom-OriginStorage** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceayv73n4gucz4f4k7muxdqubrdbeh3zj55r3dgknku36fog3eyq7o 
#### Address 
> f16bxqdvcliy3x2o4q7w2q5dm4zj4tls6pfsjpmma
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f1q6bpjlqia6iemqbrdaxr2uehrhpvoju3qh4lpga
#### Id
> 3c2c4b5f-cb29-4e9a-93c3-881c34e04b43
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceayv73n4gucz4f4k7muxdqubrdbeh3zj55r3dgknku36fog3eyq7o

**Comment by psh0691** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebms5zxxockdyfriy7zcbdlzm3ajlcbhepekw76tnece4ugfmxcny 
#### Address 
> f16bxqdvcliy3x2o4q7w2q5dm4zj4tls6pfsjpmma
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f1qdko4jg25vo35qmyvcrw4ak4fmuu3f5rif2kc7i
#### Id
> 3c2c4b5f-cb29-4e9a-93c3-881c34e04b43
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebms5zxxockdyfriy7zcbdlzm3ajlcbhepekw76tnece4ugfmxcny

**Comment by cryptowhizzard** [comment]
I am trying to retrieve data from you but all i got is :

ERROR: offer error: retrieval query offer errored: failed to fetch piece to retrieve from: getting pieces for cid bafykbzacebw23jjum2eah3cqj46h6hxi66frmmquv5lmk4m7dris3aho6zfjo: getting pieces containing block bafykbzacebw23jjum2eah3cqj46h6hxi66frmmquv5lmk4m7dris3aho6zfjo: failed to lookup index for mh a0e402206dada534668803ec504f3c7f1ee8f78b163214af56c5719f1c512d80eef64a97, err: datastore: key not found

ERROR: offer error: retrieval query offer errored: failed to fetch piece to retrieve from: getting pieces for cid bafykbzacebw23jjum2eah3cqj46h6hxi66frmmquv5lmk4m7dris3aho6zfjo: getting pieces containing block bafykbzacebw23jjum2eah3cqj46h6hxi66frmmquv5lmk4m7dris3aho6zfjo: failed to lookup index for mh a0e402206dada534668803ec504f3c7f1ee8f78b163214af56c5719f1c512d80eef64a97, err: datastore: key not found

**Comment by cryptowhizzard** [comment]
Dear fylsan3,

As notary I am doing due diligence on your LDN. I could not get retrieval to work. Can you please upload the car file of CID baga6ea4seaqmeat2vj65jftvq53tm4jtivxr6hyqhslycjnwzm6mbj62leqhykq ?

You can use our upload system at http://send.datasetcreators.com. Please select 7 days for the system to keep the file and post the link you received here so I (and other notaries) can download your content.

**Comment by fylsan3** [comment]
http://send.datasetcreators.com Only supports file uploads less than 32.7G here, so what you asked for
baga6ea4seaqmeat2vj65jftvq53tm4jtivxr6hyqhslycjnwzm6mbj62leqhykq cannot be uploaded because it exceeds the limit. It is recommended that you use "lassie" to retrieve this data. We have sent this data to multiple SPs for encapsulation and backup. Use "lassie" to automatically download from nodes that support retrieval. Use the command as follows:
lassie fetch -o baga6ea4seaqmeat2vj65jftvq53tm4jtivxr6hyqhslycjnwzm6mbj62leqhykq.car -p bafykbzaceb4r4ssxdzdjkpvqqcsh5tw6ix7d2y56jvd5mqt7pqdph6srtfvbe
![Alt ​​text](image-1.png)

"ERROR: offer error: retrieval query offer errored: failed to fetch piece to retrieve from: getting pieces for cid bafykbzacebw23jjum2eah3cqj46h6hxi66frmmquv5lmk4m7dris3aho6zfjo: getting pieces containing block bafykb zacebw23jjum2eah3cqj46h6hxi66frmmquv5lmk4m7dris3aho6zfjo: failed to lookup index for mh a0e402206dada534668803ec504f3c7f1ee8f78b163214af56c5719f1c512d80eef64a 97, err: datastore: key not found”
The car file you retrieved in error can be uploaded to http://send.datasetcreators.com. We have arranged for personnel to upload it. Because the upload speed is relatively slow, you need to wait for a while. After the upload is completed, we will The link is sent out.

**Comment by a1991car** [comment]
checker:manualTrigger

**Comment by fylsan3** [comment]
After hard work, we have uploaded the data, thank you!
https://send.datasetcreators.com/download/eeec1382afc88f95/#ogjkRduiYSNy1b8zAZmiUQ

**Comment by Bitengine-reeta** [comment]
checker:manualTrigger

**Comment by Bitengine-reeta** [comment]
It went well and complied with the rules

**Comment by Bitengine-reeta** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecyrog5ytsmu4stadfcswsyjkd3nrvw6pzudewomyabr7pnc5zl7s 
#### Address 
> f16bxqdvcliy3x2o4q7w2q5dm4zj4tls6pfsjpmma
#### Datacap Allocated
> 2.00PiB
#### Signer Address
> f1jyvhxp4kmwreo22ke4itspraznpudw3uqaink5i
#### Id
> d9d1e074-3117-4c94-9f32-2548957da69b
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecyrog5ytsmu4stadfcswsyjkd3nrvw6pzudewomyabr7pnc5zl7s

**Comment by AlanGreaterheat** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecavvhxfhxrckbdadvomoa4cbneylu5o5wiwphafvuys2mtlww4dc 
#### Address 
> f16bxqdvcliy3x2o4q7w2q5dm4zj4tls6pfsjpmma
#### Datacap Allocated
> 2.00PiB
#### Signer Address
> f1pnmzlxj7cfeo2v6oj5nco46hkg2l46wj7o4xxui
#### Id
> d9d1e074-3117-4c94-9f32-2548957da69b
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecavvhxfhxrckbdadvomoa4cbneylu5o5wiwphafvuys2mtlww4dc

**Comment by Joss-Hua** [comment]
checker:manualTrigger

**Comment by Joss-Hua** [comment]
looks great

**Comment by 1ane-1** [comment]
checker:manualTrigger

**Comment by 1ane-1** [comment]
Report looks good. Support fpr this stage.

**Comment by 1ane-1** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedmbk3jstbgmesmrrphpmiq4elpv7ncbuvqxlqdrecuarbad2kpuo 
#### Address 
> f16bxqdvcliy3x2o4q7w2q5dm4zj4tls6pfsjpmma
#### Datacap Allocated
> 2.00PiB
#### Signer Address
> f1mdk7s2vntzm6hu35yuo6vjubtrpfnb2awhgvrri
#### Id
> d1521172-247b-4db6-b450-0f7081254c8b
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedmbk3jstbgmesmrrphpmiq4elpv7ncbuvqxlqdrecuarbad2kpuo

**Comment by Aaron01230** [comment]
checker:manualTrigger

**Comment by Aaron01230** [comment]
The report shows that retrieval success rate is high and SP distribution is  healthy and data replication is healthy, i will support this round.

**Comment by Aaron01230** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecp6u2lljlcwgocqlrv3rhtyi6aj7wo3mdjbybk6ezpnq5qtbgfxc 
#### Address 
> f16bxqdvcliy3x2o4q7w2q5dm4zj4tls6pfsjpmma
#### Datacap Allocated
> 2.00PiB
#### Signer Address
> f1xrnysd4gimg64d4l6qi7ulzwwq22c6vfg6lpw3i
#### Id
> d1521172-247b-4db6-b450-0f7081254c8b
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecp6u2lljlcwgocqlrv3rhtyi6aj7wo3mdjbybk6ezpnq5qtbgfxc

**Comment by cryptowhizzard** [comment]
> After hard work, we have uploaded the data, thank you! https://send.datasetcreators.com/download/eeec1382afc88f95/#ogjkRduiYSNy1b8zAZmiUQ ![WechatIMG654](https://user-images.githubusercontent.com/16700365/265596262-5cd66b65-d936-4bba-a4e5-95e9d5aa0270.jpg)

Verified & Ok.

**Comment by a1991car** [comment]
checker:manualTrigger

**Comment by a1991car** [comment]
The data has been verified , looks good. Please pay attention to data backup.  

> > After hard work, we have uploaded the data, thank you! https://send.datasetcreators.com/download/eeec1382afc88f95/#ogjkRduiYSNy1b8zAZmiUQ ![WechatIMG654](https://user-images.githubusercontent.com/16700365/265596262-5cd66b65-d936-4bba-a4e5-95e9d5aa0270.jpg)
> 
> Verified & Ok.

**Comment by a1991car** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacea7a7tl4fmztc7ujb24ufpdgaik7fnygkrcz7zf6eeuzohxroljsk 
#### Address 
> f16bxqdvcliy3x2o4q7w2q5dm4zj4tls6pfsjpmma
#### Datacap Allocated
> 2.00PiB
#### Signer Address
> f1qnumecdypgrbaebtkdfjnwt5ndacadcuas3deiq
#### Id
> 8d186cfc-29dc-4d36-953c-b8809c9b6ecf
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacea7a7tl4fmztc7ujb24ufpdgaik7fnygkrcz7zf6eeuzohxroljsk

**Comment by kernelogic** [comment]
Going through the history above and looking at the report, I will support it. But please improve the replication factor to be higher.

**Comment by kernelogic** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebhgpyob2ep2miyasbczfn7mpzn23gunwxtrhorq67yzgrssmdv6s 
#### Address 
> f16bxqdvcliy3x2o4q7w2q5dm4zj4tls6pfsjpmma
#### Datacap Allocated
> 2.00PiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### Id
> 8d186cfc-29dc-4d36-953c-b8809c9b6ecf
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebhgpyob2ep2miyasbczfn7mpzn23gunwxtrhorq67yzgrssmdv6s

**Comment by stcouldlisa** [comment]
checker:manualTrigger

**Comment by junyaoren** [comment]
The data looks good to me. I can see the number of replicas is also healthy now. Willing to support this round. Though I do expect to see a better retrieval rate in the future.

**Comment by junyaoren** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebmkneomxavm3dwkvgjsbh6ioyx6flfmwbskuf35hbe6mvpylic3a 
#### Address 
> f16bxqdvcliy3x2o4q7w2q5dm4zj4tls6pfsjpmma
#### Datacap Allocated
> 2.00PiB
#### Signer Address
> f1xzff5xup63o5sygr2swp4zvcajg54lotliimdty
#### Id
> 8d186cfc-29dc-4d36-953c-b8809c9b6ecf
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebmkneomxavm3dwkvgjsbh6ioyx6flfmwbskuf35hbe6mvpylic3a

**Comment by Normalnoise** [comment]
checker:manualTrigger

**Comment by Normalnoise** [comment]
the Checker Report is good for me, willing to support it

**Comment by Normalnoise** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedfmpxxjeszcn5vtgbmut6cz7uvixz3tha23bskfjem63j7nuu77g 
#### Address 
> f16bxqdvcliy3x2o4q7w2q5dm4zj4tls6pfsjpmma
#### Datacap Allocated
> 2.00PiB
#### Signer Address
> f1c5non5yf35avgcpsqvxu4yj54yyvxorwyjochqq
#### Id
> 8d186cfc-29dc-4d36-953c-b8809c9b6ecf
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedfmpxxjeszcn5vtgbmut6cz7uvixz3tha23bskfjem63j7nuu77g

**Comment by fylsan3** [comment]
please keep open

**Comment by stcouldlisa** [comment]
checker:manualTrigger

**Comment by kevzak** [comment]
SPs taking deals

f02363300 | Tokyo, Tokyo, JPAmazon.com, Inc. | 620.66 TiB | 6.91% | 620.66 TiB | 0.00%
f02363308 | Tokyo, Tokyo, JPAmazon.com, Inc. | 183.25 TiB | 2.04% | 183.25 TiB | 0.00%
f02519843 | Beijing, Beijing, CNChina Mobile Communicaitons Corporation | 679.94 TiB | 7.57% | 636.53 TiB | 6.38%
f02105219 | Guangzhou, Guangdong, CNChina Mobile communications corporation | 288.84 TiB | 3.22% | 271.28 TiB | 6.08%
f02220982 | Guangzhou, Guangdong, CNChina Mobile communications corporation | 229.88 TiB | 2.56% | 229.56 TiB | 0.14%
f02760664 | Beijing, Beijing, CNChina Mobile Communications Group Co., Ltd. | 200.00 TiB | 2.23% | 200.00 TiB | 0.00%
f02199203 | Hohhot, Inner Mongolia, CNCHINA UNICOM China169 Backbone | 458.38 TiB | 5.10% | 458.38 TiB | 0.00%
f02221110 | Shenzhen, Guangdong, CNCHINANET-BACKBONE | 1.07 PiB | 12.25% | 1.07 PiB | 0.00%
f02221111 | Shenzhen, Guangdong, CNCHINANET-BACKBONE | 906.75 TiB | 10.10% | 906.75 TiB | 0.00%
f02221113 | Shenzhen, Guangdong, CNCHINANET-BACKBONE | 521.50 TiB | 5.81% | 521.50 TiB | 0.00%
f02221112 | Shenzhen, Guangdong, CNCHINANET-BACKBONE | 426.56 TiB | 4.75% | 426.56 TiB | 0.00%
f02370792 | Shenzhen, Guangdong, CNCHINANET-BACKBONE | 208.09 TiB | 2.32% | 208.09 TiB | 0.00%
f02200472 | Chengdu, Sichuan, CNCHINANET-BACKBONE | 29.75 TiB | 0.33% | 29.75 TiB | 0.00%
f0222811 | Hangzhou, Zhejiang, CNCT-HangZhou-IDC | 10.44 TiB | 0.12% | 10.44 TiB | 0.00%
f02122388 | Shenzhen, Guangdong, CNCTGNet | 454.75 TiB | 5.06% | 454.75 TiB | 0.00%
f02363305new | Shenzhen, Guangdong, CNCTGNet | 311.72 TiB | 3.47% | 311.72 TiB | 0.00%
f02807399 | Shenzhen, Guangdong, CNCTGNet | 161.44 TiB | 1.80% | 161.44 TiB | 0.00%
f02274504 | Shenzhen, Guangdong, CNCTGNet | 116.75 TiB | 1.30% | 116.69 TiB | 0.05%
f02812504 | Hong Kong, Central and Western, HKHK Broadband Network Ltd. | 133.78 TiB | 1.49% | 133.78 TiB | 0.00%
f01435542 | Hong Kong, Central and Western, HKHK Broadband Network Ltd. | 109.94 TiB | 1.22% | 109.94 TiB | 0.00%
f02246008 | Hong Kong, Central and Western, HKHKBN Enterprise Solutions HK Limited | 1.39 PiB | 15.80% | 1.36 PiB | 2.10%
f02363306 | Singapore, Singapore, SGSingapore Telecommunications Ltd | 312.00 TiB | 3.47% | 312.00 TiB | 0.00%
f01920887 | Melbourne, Victoria, AUVocus Connect International Backbone | 38.59 TiB | 0.43% | 38.59 TiB | 0.00%
f02816081 | Singapore, Singapore, SGZenlayer Inc | 43.69 TiB | 0.49% | 43.69 TiB | 0.00%
f02816095 | Singapore, Singapore, SGZenlayer Inc | 14.81 TiB | 0.16% | 14.81 TiB | 0.00%

SPs listed on registration:
f02234424 algorithdata USA
f02246008 Calculus Hong Kong
f0222811 HanTangcloud Hangzhou
f02274504 Dotdata Shenzhen
f02220982 interstellar cloud Guangzhou

f02058333 algorithdata USA
f02199203 individual investor


too many SP IDs that were never presented upfront. Closing until a complete list of entities is supplied

**Comment by stcouldlisa** [comment]
**f1xrw6xh7zs4tqso4in7vh6pnpq2tenj2t7hk3voy**

**Comment by stcouldlisa** [comment]
checker:manualTrigger
