### ISSUE TITLE
[DataCap Application] Open Atmospheric Research Datasets By NCAR

### ISSUE THREAD

**Issue by FroghubMan** [filecoin-project/filecoin-plus-large-datasets#2119]
### Data Owner Name

NCAR

### What is your role related to the dataset

Data Preparer

### Data Owner Country/Region

United States

### Data Owner Industry

Environment

### Website

https://www.ucar.edu/terms-of-use/data

### Social Media

```text
https://www.ucar.edu/terms-of-use/data
```

### Total amount of DataCap being requested

9PiB

### Expected size of single dataset (one copy)

1P

### Number of replicas to store

9

### Weekly allocation of DataCap requested

1PiB

### On-chain address for first allocation

f17zbocai3pf7hks6eomldvnmkdvgn25zojia3agq

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
FrogHub files is a platform that will provide users with free storage, allowing users to enjoy free storage at the same time. Facilitating the Filecoin network to store more and more valuable public data sets.

About the FrogHub data set

FrogHub files is a user-oriented cloud storage platform. Any user with data storage needs can use the platform tools free of charge.

The Filecoin Network provides reliable, secure, and affordable decentralized storage, and FrogHub files wants to make it easy for users to store their data in the filecoin network.

Attracting traditional cloud and object-based storage users to the Filecoin network and benefiting from it is a challenge. FrogHub, as developers in the Felicoin ecosystem, needs to face this challenge together. We've been building useful tools to make it easier for users to store data on the Filecoin network.

Froghub files integrates a set of tools, including storage bucket, custom gateway, data encryption service KMS, static web deployment (under development), open API, to provide storage services compatible with cloud storage and object storage, providing better user experience and attracting more users.
FrogHub has always defined itself as a tool developer and infrastructure builder in the Filecoin ecosystem. In 2019, we started to focus on technical solutions and development based on the IPFS protocol and Filecoin network. We have been working hard to become a qualified builder in the filecoin ecosystem.

Our team is a very pure development team, more than 90% of which are developers, more than half of whom have more than 5 years of development experience in communication, Internet, blockchain and other industries. We hope that we can gain users' recognition by exporting useful tools and platforms.

In order to contribute to the filecoin community, we have developed the open source sector repair tool Filecoin-Sealer-Recover and the nft free authoring platform NFT-Creator.
In addition, we plan to provide a sector browser for the community in 2023 and build the liquidity pledge platform STFIL on FVM.

See the links below for details.
- github: https://github.com/orgs/froghub-io
- twitter: https://twitter.com/froghub_io
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
This application including 5 AWS open datasets for atmospheric research by NCAR(National Center for Atmospheric Research):

1. Community Earth System Model Large Ensemble (CESM LENS)
https://registry.opendata.aws/ncar-cesm-lens/
The Community Earth System Model (CESM) Large Ensemble Numerical Simulation (LENS) dataset includes a 40-member ensemble of climate simulations for the period 1920-2100 using historical data (1920-2005) or assuming the RCP8.5 greenhouse gas concentration scenario (2006-2100), as well as longer control runs based on pre-industrial conditions.

2. Community Earth System Model v2 Large Ensemble (CESM2 LENS)
https://registry.opendata.aws/ncar-cesm2-lens/
The US National Center for Atmospheric Research partnered with the IBS Center for Climate Physics in South Korea to generate the CESM2 Large Ensemble which consists of 100 ensemble members at 1 degree spatial resolution covering the period 1850-2100 under CMIP6 historical and SSP370 future radiative forcing scenarios.

3. Community Earth System Model v2 ARISE (CESM2 ARISE)
https://registry.opendata.aws/ncar-cesm2-arise/
Data from ARISE-SAI Experiments with CESM2

4. NA-CORDEX - North American component of the Coordinated Regional Downscaling Experiment
https://registry.opendata.aws/ncar-na-cordex/
The NA-CORDEX dataset contains regional climate change scenario data and guidance for North America, for use in impacts, decision-making, and climate science. The NA-CORDEX data archive contains output from regional climate models (RCMs) run over a domain covering most of North America using boundary conditions from global climate model (GCM) simulations in the CMIP5 archive.

5. CAM6 Data Assimilation Research Testbed (DART) Reanalysis: Cloud-Optimized Dataset
https://registry.opendata.aws/ncar-dart-cam6/
This is a cloud-hosted subset of the CAM6+DART (Community Atmosphere Model version 6 Data Assimilation Research Testbed) Reanalysis dataset. These data products are designed to facilitate a broad variety of research using the NCAR CESM 2.1 (National Center for Atmospheric Research's Community Earth System Model version 2.1), including model evaluation, ensemble hindcasting, data assimilation experiments, and sensitivity studies. They come from an 80 member ensemble reanalysis of the global troposphere and stratosphere using DART and CAM6. The data products represent states of the atmosphere consistent with observations from 2011 through 2019 at 1 degree horizontal resolution and weekly frequency.
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### Has this dataset been stored on the Filecoin network before? If so, please explain and make the case why you would like to store this dataset again to the network. Provide details on preparation and/or SP distribution.

```text
I found those valuable public datasets from closed applications that had been passed but not actually implemented. The SP I'm working with has strong storage needs, so I want to get started quickly on storing this data.
```

### Please share a sample of the data

```text
s3://ncar-cesm-lens/    82.7 TiB
s3://ncar-cesm2-lens/   309.3 TiB
s3://ncar-cesm2-arise/  597.2 TiB
s3://ncar-na-cordex/    13.2 TiB
s3://ncar-dart-cam6/    2.5 TiB
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

2 to 3 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, Europe

### How will you be distributing your data to storage providers

Cloud storage (i.e. S3), Shipping hard drives

### How do you plan to choose storage providers

Slack, Big Data Exchange, Partners

### If you already have a list of storage providers to work with, fill out their names and provider IDs below

```text
| MinerID   | City       | Continent | 
| --------- | ---------- | --------- | 
| f01811024 | HongKong   | CN        | 
| f0827006  | Tokyo  	 | Japan     | 
| f02227726 | HongKong   | CN        | 
| f02195153 | Tokyo   	 | Japan     | 
| f02098006 | Krabi      | Thailand  | 
| f02223012 | Hebei    	 | CN        | 
| f02235154 | HongKong   | CN        | 
| f02085722 | Jiangmen   | CN        |
```

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by FroghubMan** [comment]
Hello @Sunnyiscoming , We would like to quickly start the data processing and storage process. Can you approve it for me?

**Comment by FroghubMan** [comment]
Hi @kevzak ,I can fully identify these entities, but I cannot disclose them publicly. Some miners belong to the same SP.

**Comment by Filplus-govteam** [comment]
Hi @FroghubMan seeing 4 applications come in with same list of SPs. 

Per the https://github.com/filecoin-project/notary-governance/issues/922 for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

This information will be reviewed by Fil+ Governance team to confirm validity and then the application will be triggered for notary review. I know you said you could just fake it, but please provide real information about the entities that are essentially unknown to anyone in the community. Let us know if you have any questions.

**Comment by FroghubMan** [comment]
Hi @Sunnyiscoming, I have completed the Fil+ registration form.
Can you review it for me and start the data storage process asap? Thank you so much.

**Comment by Filplus-govteam** [comment]
@FroghubMan thank you for sharing SP Entity information:

f01811024 chimsen HongKong
f0827006 FrogStorage Tokyo
f02227726 Three Clouds Hong Kong
f02223012 Person Hebei
f02085722 Chimsen Jiangmen

**Comment by FroghubMan** [comment]
@Filplus-govteam , My pleasure.  I have a basis for cooperation with these SPs, and I promise the authenticity of the information I provide.
 :) I have a small suggestion, it is reasonable to publicly list node IDs and addresses, but some SPs are really reluctant to disclose their identities. It would be nice if the "node owner" could be excluded from the announcement.

**Comment by FroghubMan** [comment]
Hi @Sunnyiscoming , can you support my application?

**Comment by Filplus-govteam** [comment]
Just to re-confirm the process here @FroghubMan - after any allocations we will ask notaries to:
- Confirm SP IDs and locations match your plan
- Confirm data is retrievable and data sample matches said datasets

**Comment by dkkapur** [comment]
> If you are a data preparer. What is your location (City and Country)
No response

> If you are a data preparer, how will the data be prepared? Please include tooling used and technical details?
No response

why were these questions not answered?

**Comment by FroghubMan** [comment]
> Just to re-confirm the process here @FroghubMan - after any allocations we will ask notaries to:
> 
> * Confirm SP IDs and locations match your plan
> * Confirm data is retrievable and data sample matches said datasets

sure

**Comment by FroghubMan** [comment]
> > If you are a data preparer. What is your location (City and Country)
> > No response
> 
> > If you are a data preparer, how will the data be prepared? Please include tooling used and technical details?
> > No response
> 
> why were these questions not answered?

Sorry for that. We are in China. We download the dataset on aws through large bandwidth, and use singularity to generate car files, part of which is transmitted online, and part of which is distributed to sp by posting hard drives offline

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 9PiB

**Expected weekly DataCap usage rate**
> 1TiB

**Client address**
>f17zbocai3pf7hks6eomldvnmkdvgn25zojia3agq

**Comment by Garyweiou** [comment]
checker:manualTrigger

**Comment by BDE-io** [comment]
1. i infer from this thread the applicant has completed the Fil+ registration form
2. the applicant has provided information about the distribution of this dataset, and at this point, it looks like the replicas will be well distributed
3. the applicant has provided information on its data preparation process, which sounds realistic and reasonable

therefore, happy to sign this first tranche. advise notaries to monitor distribution of data upon successful storage

**Comment by FroghubMan** [comment]
We are preparing the data.

**Comment by FroghubMan** [comment]
Hi @kevzak @Sunnyiscoming . We  already have the data ready for this application, can you reopen it for me?

**Comment by FroghubMan** [comment]
Hello @kevzak @Sunnyiscoming ,could you help me to reopen this application ,so that we can continue the work, thank you!

**Comment by FroghubMan** [comment]
@galen-mcandrew @raghavrmadya @Kevin-FF-USA

**Comment by FroghubMan** [comment]
Hello . Any update?

**Comment by 1ane-1** [comment]
checker:manualTrigger

**Comment by 1ane-1** [comment]
Support according to above information, and this is the first round we will check your retrieval and sps information later.
Good luck.

**Comment by 1ane-1** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecw44x4hqzzam5rjbhy43uit6og3d23wj5i54fxzwsjxinhg5eu4i 
#### Address 
> f17zbocai3pf7hks6eomldvnmkdvgn25zojia3agq
#### Datacap Allocated
> 460.79TiB
#### Signer Address
> f1mdk7s2vntzm6hu35yuo6vjubtrpfnb2awhgvrri
#### Id
> 503320d8-726a-4e3a-88c7-159f13f09641
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecw44x4hqzzam5rjbhy43uit6og3d23wj5i54fxzwsjxinhg5eu4i

**Comment by kevzak** [comment]
checker:manualTrigger

**Comment by FroghubMan** [comment]
checker:manualTrigger

**Comment by FroghubMan** [comment]
checker:manualTrigger

**Comment by FroghubMan** [comment]
checker:manualTrigger

**Comment by FroghubMan** [comment]
checker:manualTrigger

**Comment by FroghubMan** [comment]
checker:manualTrigger

**Comment by FroghubMan** [comment]
@Sunnyiscoming  Can you help me take a look at this issue? I've been unable to trigger reports and the robot.

**Comment by FroghubMan** [comment]
checker:manualTrigger

**Comment by FroghubMan** [comment]
checker:manualTrigger

**Comment by FroghubMan** [comment]
checker:manualTrigger

**Comment by sxxfuture-official** [comment]
Reports checked, LGTM.

**Comment by sxxfuture-official** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacearp7cbh4b6xgovgih7sik76mil52pg2cwgnkmmhvzrama5nor2cw 
#### Address 
> f17zbocai3pf7hks6eomldvnmkdvgn25zojia3agq
#### Datacap Allocated
> 460.79TiB
#### Signer Address
> f1foiomqlmoshpuxm6aie4xysffqezkjnokgwcecq
#### Id
> 503320d8-726a-4e3a-88c7-159f13f09641
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacearp7cbh4b6xgovgih7sik76mil52pg2cwgnkmmhvzrama5nor2cw

**Comment by 1ane-1** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebuuuzcud7ozazpca4ddf4s6465qlxtqmvrubjm5r3yezu75wr4ie 
#### Address 
> f17zbocai3pf7hks6eomldvnmkdvgn25zojia3agq
#### Datacap Allocated
> 460.79TiB
#### Signer Address
> f1mdk7s2vntzm6hu35yuo6vjubtrpfnb2awhgvrri
#### Id
> 503320d8-726a-4e3a-88c7-159f13f09641
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebuuuzcud7ozazpca4ddf4s6465qlxtqmvrubjm5r3yezu75wr4ie

**Comment by Filplus-govteam** [comment]
@FroghubMan the SPs taking deals do not match initial list submitted. Closing until clarified

**Comment by FroghubMan** [comment]
Hi @Filplus-govteam ,I submitted the KYC form for #2117  #2119. please check.

**Comment by AlanGreaterheat** [comment]
checker:manualTrigger

**Comment by AlanGreaterheat** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedruskhrpp6c5vjrlw7bxnugxmtrzjd7vjnsz3kd7ert72fea62rg 
#### Address 
> f17zbocai3pf7hks6eomldvnmkdvgn25zojia3agq
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f1pnmzlxj7cfeo2v6oj5nco46hkg2l46wj7o4xxui
#### Id
> bcc333eb-6128-4bc7-8ecc-fede52c4e5a9
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedruskhrpp6c5vjrlw7bxnugxmtrzjd7vjnsz3kd7ert72fea62rg

**Comment by a1991car** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedytgjoqdi3fril6zew3mf2icqkrk2vmsvpf6oenpapmv3q7p7vau 
#### Address 
> f17zbocai3pf7hks6eomldvnmkdvgn25zojia3agq
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f1qnumecdypgrbaebtkdfjnwt5ndacadcuas3deiq
#### Id
> bcc333eb-6128-4bc7-8ecc-fede52c4e5a9
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedytgjoqdi3fril6zew3mf2icqkrk2vmsvpf6oenpapmv3q7p7vau

**Comment by Chuangshi1** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaxbky67mwyy6zgfkixlb52ooaralqxf76ptdylgy3z72fobvtgug 
#### Address 
> f17zbocai3pf7hks6eomldvnmkdvgn25zojia3agq
#### Datacap Allocated
> 1.00PiB
#### Signer Address
> f1mdk7s2vntzm6hu35yuo6vjubtrpfnb2awhgvrri
#### Id
> 04b8b276-49ea-43d7-b3fc-5ccba889daa4
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaxbky67mwyy6zgfkixlb52ooaralqxf76ptdylgy3z72fobvtgug

**Comment by laurarenpanda** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebwnocxqlt4qi2eqktjvh2bvy6pdgz6oycc67qwlihvv5n7jiv4h4 
#### Address 
> f17zbocai3pf7hks6eomldvnmkdvgn25zojia3agq
#### Datacap Allocated
> 1.00PiB
#### Signer Address
> f1bp3tzp536edm7dodldceekzbsx7zcy7hdfg6uzq
#### Id
> 04b8b276-49ea-43d7-b3fc-5ccba889daa4
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebwnocxqlt4qi2eqktjvh2bvy6pdgz6oycc67qwlihvv5n7jiv4h4

**Comment by Sunnyiscoming** [comment]
SP List provided:
[{"providerID": "f01811024",  "City": "HongKong", "Country": "CN", "SPOrg","chimsen"},
{"providerID": "f0827006",  "City": "Tokyo", "Country": "JAPAN","SPOrg","FrogStorage"},
{"providerID": "f02227726",  "City": "HongKong", "Country": "CN","SPOrg","Three Clouds"},
{"providerID": "f02223012",  "City": "Hebei", "Country": "CN","SPOrg","Person"},
{"providerID": "f02085722",  "City": "Jiangmen", "Country": "CN","SPOrg","Chimsen"},]

**Comment by FroghubMan** [comment]
checker:manualTrigger

**Comment by Chuangshi1** [comment]
checker:manualTrigger

**Comment by Chuangshi1** [comment]
Please explain the reason for CID sharing.

**Comment by FroghubMan** [comment]
Dear all. Due to our work error, we got the wrong data source. (Use "Open Atmospheric Research Datasets" - #2119 as "Digital Earth Africa Datasets" - #2289.) This leads to CID sharing issues in #2119 and #2289. We have currently paused the distribution of #2289, deleted the incorrect data and re-prepared the correct data.
Sorry for this!

**Comment by FroghubMan** [comment]
Btw, the datacap of this application is all normal.

**Comment by Chuangshi1** [comment]
I will keep the eyes on the sharing problem. If the CID sharing dataset more than 226.58 TiB, i will apply for delete the Datacap. Hope you can do it well. Support for this round.

**Comment by Chuangshi1** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceajgz3kurpbafmj5fo6mjrbovxwicj77gnmo6ykuqkvnvhqognkt6 
#### Address 
> f17zbocai3pf7hks6eomldvnmkdvgn25zojia3agq
#### Datacap Allocated
> 2.00PiB
#### Signer Address
> f1mdk7s2vntzm6hu35yuo6vjubtrpfnb2awhgvrri
#### Id
> 215c7f4a-e258-4fc2-9612-efcdd65665ff
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceajgz3kurpbafmj5fo6mjrbovxwicj77gnmo6ykuqkvnvhqognkt6

**Comment by AlanGreaterheat** [comment]
> Dear all. Due to our work error, we got the wrong data source. (Use "Open Atmospheric Research Datasets" - #2119 as "Digital Earth Africa Datasets" - #2289.) This leads to CID sharing issues in #2119 and #2289. We have currently paused the distribution of #2289, deleted the incorrect data and re-prepared the correct data. Sorry for this!

Please follow strictly

**Comment by AlanGreaterheat** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedsjzrs2tgw5zqdmvn4plpy3ceegrd3mwhgcdqc2cbdkb6nehxlv6 
#### Address 
> f17zbocai3pf7hks6eomldvnmkdvgn25zojia3agq
#### Datacap Allocated
> 2.00PiB
#### Signer Address
> f1pnmzlxj7cfeo2v6oj5nco46hkg2l46wj7o4xxui
#### Id
> 215c7f4a-e258-4fc2-9612-efcdd65665ff
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedsjzrs2tgw5zqdmvn4plpy3ceegrd3mwhgcdqc2cbdkb6nehxlv6

**Comment by SuperChaiChai** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaau5k2v4lmpbojysrwdfuw3yag74vltqeaz6hu5pg2o3qyva77q6 
#### Address 
> f17zbocai3pf7hks6eomldvnmkdvgn25zojia3agq
#### Datacap Allocated
> 2.00PiB
#### Signer Address
> f12mckci3omexgzoeosjvstcfxfe4vqw7owdia3da
#### Id
> 6e1eb676-63a4-43e9-b27c-0053a153497d
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaau5k2v4lmpbojysrwdfuw3yag74vltqeaz6hu5pg2o3qyva77q6

**Comment by NiwanDao** [comment]
LGTM

**Comment by NiwanDao** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb4ef4lpgqflnze4oliikpi36kmpp2xs3yjvpzvkeekswrwsyxoo6 
#### Address 
> f17zbocai3pf7hks6eomldvnmkdvgn25zojia3agq
#### Datacap Allocated
> 2.00PiB
#### Signer Address
> f1a2lia2cwwekeubwo4nppt4v4vebxs2frozarz3q
#### Id
> 6e1eb676-63a4-43e9-b27c-0053a153497d
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb4ef4lpgqflnze4oliikpi36kmpp2xs3yjvpzvkeekswrwsyxoo6

**Comment by FroghubMan** [comment]
Keep going

**Comment by 1ane-1** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebsjxcnrb6y66pkyo73l3jaelonk3vadizjp3vyo2lepy4rdupoec 
#### Address 
> f17zbocai3pf7hks6eomldvnmkdvgn25zojia3agq
#### Datacap Allocated
> 2.00PiB
#### Signer Address
> f1mdk7s2vntzm6hu35yuo6vjubtrpfnb2awhgvrri
#### Id
> 6e1eb676-63a4-43e9-b27c-0053a153497d
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebsjxcnrb6y66pkyo73l3jaelonk3vadizjp3vyo2lepy4rdupoec

**Comment by sxxfuture-official** [comment]
checker:manualTrigger

**Comment by sxxfuture-official** [comment]
@FroghubMan 
Is that "Open Atmospheric Research Datasets By NCAR" and "DigitalEarth Africa" belong to the same datasets? There  is CID sharing between them.

**Comment by FroghubMan** [comment]
> @FroghubMan Is that "Open Atmospheric Research Datasets By NCAR" and "DigitalEarth Africa" belong to the same datasets? There is CID sharing between them.

Hi @sxxfuture-official ,thank you for you support.Due to our mistakes, we used the wrong data source. (Use "Open Atmospheric Research Datasets" - #2119 as "Digital Earth Africa Datasets" - #2289.) Therefore #2289 is currently using the wrong data and has a CID sharing problem with #2119. Sorry for this! 
We have now deleted all incorrectly processed data and processed the correct data.Everything is fine with the dataset here.

**Comment by sxxfuture-official** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecyfxz4lzqngb3rfnnvybeu4feoszmshv4j6tdfew2ccoauai6fnq 
#### Address 
> f17zbocai3pf7hks6eomldvnmkdvgn25zojia3agq
#### Datacap Allocated
> 2.00PiB
#### Signer Address
> f1foiomqlmoshpuxm6aie4xysffqezkjnokgwcecq
#### Id
> 6e1eb676-63a4-43e9-b27c-0053a153497d
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecyfxz4lzqngb3rfnnvybeu4feoszmshv4j6tdfew2ccoauai6fnq

**Comment by Bitrise0111** [comment]
Their report is quite well, and we'd like to support them for this round.

**Comment by Bitrise0111** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedebjma4m6s6hvqivtkqn4l7xo6ryjq7efshq5nln3of77uqya35o 
#### Address 
> f17zbocai3pf7hks6eomldvnmkdvgn25zojia3agq
#### Datacap Allocated
> 2.00PiB
#### Signer Address
> f1nknj7ayq4o43czrtdoauggtwl43fbqatmqis3yy
#### Id
> b0291b9d-f98d-4292-a567-9c647be8e2fa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedebjma4m6s6hvqivtkqn4l7xo6ryjq7efshq5nln3of77uqya35o

**Comment by AlanGreaterheat** [comment]
checker:manualTrigger

**Comment by AlanGreaterheat** [comment]
For detailed explanation and information, please refer to #2289

**Comment by AlanGreaterheat** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceatdhumvylw5zoy2yinsm2y52e4xyjr7h3e2mphh64dzjbj5simxk 
#### Address 
> f17zbocai3pf7hks6eomldvnmkdvgn25zojia3agq
#### Datacap Allocated
> 2.00PiB
#### Signer Address
> f1pnmzlxj7cfeo2v6oj5nco46hkg2l46wj7o4xxui
#### Id
> b0291b9d-f98d-4292-a567-9c647be8e2fa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceatdhumvylw5zoy2yinsm2y52e4xyjr7h3e2mphh64dzjbj5simxk
