### ISSUE TITLE
[DataCap Application] Distributed Archives for Neurophysiology Data Integration (DANDI)

### ISSUE THREAD

**Issue by FroghubMan** [filecoin-project/filecoin-plus-large-datasets#2120]
### Data Owner Name

DANDI

### What is your role related to the dataset

Data Preparer

### Data Owner Country/Region

United States

### Data Owner Industry

Life Science / Healthcare

### Website

https://www.dandiarchive.org/

### Social Media

```text
https://www.dandiarchive.org/
```

### Total amount of DataCap being requested

8PiB

### Expected size of single dataset (one copy)

900T

### Number of replicas to store

9

### Weekly allocation of DataCap requested

800TiB

### On-chain address for first allocation

f1ttjta4n5hwrqsqpao7ztpyss5vurpluwtpuuijy

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
FrogHub files is a platform that will provide users with free storage, allowing users to enjoy free storage at the same time. Facilitating the Filecoin network to store more and more valuable public data sets.

About the FrogHub data set

FrogHub files is a user-oriented cloud storage platform. Any user with data storage needs can use the platform tools free of charge.

The Filecoin Network provides reliable, secure, and affordable decentralized storage, and FrogHub files wants to make it easy for users to store their data in the filecoin network.

Attracting traditional cloud and object-based storage users to the Filecoin network and benefiting from it is a challenge. FrogHub, as developers in the Felicoin ecosystem, needs to face this challenge together. We've been building useful tools to make it easier for users to store data on the Filecoin network.

Froghub files integrates a set of tools, including storage bucket, custom gateway, data encryption service KMS, static web deployment (under development), open API, to provide storage services compatible with cloud storage and object storage, providing better user experience and attracting more users.
FrogHub has always defined itself as a tool developer and infrastructure builder in the Filecoin ecosystem. In 2019, we started to focus on technical solutions and development based on the IPFS protocol and Filecoin network. We have been working hard to become a qualified builder in the filecoin ecosystem.

Our team is a very pure development team, more than 90% of which are developers, more than half of whom have more than 5 years of development experience in communication, Internet, blockchain and other industries. We hope that we can gain users' recognition by exporting useful tools and platforms.

In order to contribute to the filecoin community, we have developed the open source sector repair tool Filecoin-Sealer-Recover and the nft free authoring platform NFT-Creator.
In addition, we plan to provide a sector browser for the community in 2023 and build the liquidity pledge platform STFIL on FVM.

See the links below for details.
- github: https://github.com/orgs/froghub-io
- twitter: https://twitter.com/froghub_io
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
DANDI is a public archive of neurophysiology datasets, including raw and processed data, and associated software containers. Datasets are shared according to a Creative Commons CC0 or CC-BY licenses. The data archive provides a broad range of cellular neurophysiology data. This includes electrode and optical recordings, and associated imaging data using a set of community standards: NWB:N - NWB:Neurophysiology, BIDS - Brain Imaging Data Structure, and NIDM - Neuro Imaging Data Model.
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### Please share a sample of the data

```text
https://registry.opendata.aws/dandiarchive/
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

2 to 3 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, Europe

### How will you be distributing your data to storage providers

Cloud storage (i.e. S3), Shipping hard drives

### How do you plan to choose storage providers

Slack, Big Data Exchange, Partners

### If you already have a list of storage providers to work with, fill out their names and provider IDs below

```text
| MinerID   | City       | Continent | 
| --------- | ---------- | --------- | 
| f01811024 | HongKong   | CN        | 
| f0827006  | Tokyo  	 | Japan     | 
| f02227726 | HongKong   | CN        | 
| f02195153 | Tokyo   	 | Japan     | 
| f02098006 | Krabi      | Thailand  | 
| f02223012 | Hebei    	 | CN        | 
| f02235154 | HongKong   | CN        | 
| f02085722 | Jiangmen   | CN        |
```

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by herrehesse** [comment]
@FroghubMan Hello there! I have some questions, is it possible to connect on slack? Let me know how i can reach you.

**Comment by FroghubMan** [comment]
@herrehesse Sure, can you tell me your slack handle?

**Comment by herrehesse** [comment]
@FroghubMan Hidde Hoogland.

**Comment by FroghubMan** [comment]
@herrehesse I have already send message to you

**Comment by Stanton15** [comment]
Ignore these two liars, they're just trying to sell DC to Chinese SPs.

**Comment by herrehesse** [comment]
![Screenshot 2023-07-27 at 13 57 36](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/70132857/c9325a12-9513-486b-86a8-cc16db83af73)


I apologize, but I must respectfully decline engaging with a throwaway account that has no established reputation.

**Comment by herrehesse** [comment]
@twosson thank you.

**Comment by FroghubMan** [comment]
Sorry, I found out that someone else has already stored this data. i will close it
