### ISSUE TITLE
[DataCap Application] <Hainan Digital Future> - <NFT data>

### ISSUE THREAD

**Issue by tmzxi** [filecoin-project/filecoin-plus-large-datasets#2121]
### Data Owner Name

Hainan Digital Future

### What is your role related to the dataset

Dataset Owner

### Data Owner Country/Region

China

### Data Owner Industry

Web3 / Crypto

### Website

http://www.supercloudchain.com/art/

### Social Media

```text
N/A
```

### Total amount of DataCap being requested

5PiB

### Expected size of single dataset (one copy)

500TiB

### Number of replicas to store

10

### Weekly allocation of DataCap requested

500TiB

### On-chain address for first allocation

f1uhqyg57r2qdmbvmbtpus2pexko2uedgt5o2b4vq

### Data Type of Application

Public, Open Commercial/Enterprise

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Founded in 2021, Digital Future Platform is committed to empowering the digital culture and art industry with technology, while promoting the transformation of traditional artists, boosting new artists to create value, and making digital art collection a trend. The artworks and goods displayed on the Digital collection platform are specific works uniquely identified and digitized by NFT blockchain technology, including but not limited to quadratic, video, music, pictures, digital paintings, 2D drawings, 3D models and other types of art works
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
The data mainly consists of a large number of pictures and videos accumulated by our nft platform over the years, including but not limited to art works by numerous artists, quadratic elements, natural landscapes, AI-created paintings, animals, and videos
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### Please share a sample of the data

```text
link：https://pan.baidu.com/s/1KuNuYrYXZFp1w7TdwaQncg 
code：1230
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Monthly

### For how long do you plan to keep this dataset stored on Filecoin

1.5 to 2 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, Europe

### How will you be distributing your data to storage providers

HTTP or FTP server, Shipping hard drives

### How do you plan to choose storage providers

Slack, Filmine

### If you already have a list of storage providers to work with, fill out their names and provider IDs below

```text
f01929568   Stockholm, Sweden  
f02236292   Oregon, United States
f01105825   Ningxia  China
f01966377   Ningxia  China
```

### How do you plan to make deals to your storage providers

Boost client, Lotus client, Singularity

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
- Is the data will be stored yours? Or whether it is authorized to be stored on Filecoin network?
- Have you prepared enough token for sector pledge?
- Are you a data preparer? What is your previous experience as a data-preparer? List previous applications and client IDs
- How will the data be prepared? Please include tooling used and technical details
- If you are not preparing the data, who will prepare the data?  (Name and Business)
- Has this dataset been stored on Filecoin before? If so, why are you choosing to store it again?
- Best practice for storing large datasets includes ideally, storing it in 3 or more regions, with 4 or more storage provider operators or owners.You should list Miner ID, Business Entity, Location of sps you will cooperate with.
- Could you send an email to filplus-app-review@fil.org with your official domain in order to confirm your identity? Email name should includes the issue id #2121.

**Comment by tmzxi** [comment]
@Sunnyiscoming 

Is the data will be stored yours? Or whether it is authorized to be stored on Filecoin network?

---The data is owned by our company and has been licensed to be stored in filecoin


Have you prepared enough token for sector pledge?

---We are not sp, and the sp we contacted assured us that there were enough tokens for the pledge

Are you a data preparer? What is your previous experience as a data-preparer? List previous applications and client IDs

---Yes, we are data preparers, and we will be using singularity to prepare and package car files, which my colleagues and I have tested


How will the data be prepared? Please include tooling used and technical details
---The tool I am using is singularity，We have tested and mastered the data preparation techniques based on the singularity tool open source introduction


Has this dataset been stored on Filecoin before? If so, why are you choosing to store it again?

---This data is stored on filecion for the first time

Best practice for storing large datasets includes ideally, storing it in 3 or more regions, with 4 or more storage provider operators or owners.You should list Miner ID, Business Entity, Location of sps you will cooperate with.

f01929568   Stockholm, Sweden      
f02236292   Oregon, United States   
f01105825   Ningxia  China          
f01966377   Ningxia  China          


Could you send an email to filplus-app-review@fil.org with your official domain in order to confirm your identity? Email name should includes the issue id [DataCap Application] <Hainan Digital Future> - <NFT data> #2121.
---I have sent the email, please check it, thank you

**Comment by Filplus-govteam** [comment]
Hello @tmzxi Per the https://github.com/filecoin-project/notary-governance/issues/922 for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

This information will be reviewed by Fil+ Governance team to confirm validity and then the application will be triggered for notary review. I know you said you could just fake it, but please provide real information about the entities that are essentially unknown to anyone in the community. Let us know if you have any questions.

**Comment by tmzxi** [comment]
@Filplus-govteam   I Submitted, please check, thank you

**Comment by Filplus-govteam** [comment]
We can confirm @tmzxi shared the following SP entities:
ID Entity Location
f01929568 Power Meta Corp. Stockholm, Sweden
f02236292 Unknown(email not provided) Oregon, United States
f01105825 JClound Ningxia China
f01966377 person Ningxia China

**Comment by tmzxi** [comment]
@Filplus-govteam 
These sp entities, we have also checked their physical location, we require them to be real, can not hide (such as using vpn), we will follow the fil+ rules, if necessary, we will contact more sp

@Sunnyiscoming  Can you help us approve it?  If you need any more information, please let me know. Thank you

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 5PiB

**Expected weekly DataCap usage rate**
> 500TiB

**Client address**
>f1uhqyg57r2qdmbvmbtpus2pexko2uedgt5o2b4vq

**Comment by a1991car** [comment]
You also need to post an email to filplus-app-review@fil.org to confirm your identity, did you send the email, I didn’t see the screenshot of the email

**Comment by a1991car** [comment]
You also need to make sure you can support retrieval

**Comment by tmzxi** [comment]
@a1991car  I have sent the email, 
                    We follow fil+ rules to ensure that every node supports retrieval

![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/97873688/67ee1f2a-82a0-40d0-80d0-5cb6ba8621ab)

**Comment by a1991car** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebqpsyfh7tw2xp4ntu3qanko2ztd5xqfxveokzjpk5du7mrdmaze2 
#### Address 
> f1uhqyg57r2qdmbvmbtpus2pexko2uedgt5o2b4vq
#### Datacap Allocated
> 250.00TiB
#### Signer Address
> f1qnumecdypgrbaebtkdfjnwt5ndacadcuas3deiq
#### Id
> b23dedf1-3fe7-4252-92f3-95579320c9f3
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebqpsyfh7tw2xp4ntu3qanko2ztd5xqfxveokzjpk5du7mrdmaze2

**Comment by zcfil** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaz475pjynvnlmogbommkh7xffnx6x5prttdqxnialb76d6ob2gse 
#### Address 
> f1uhqyg57r2qdmbvmbtpus2pexko2uedgt5o2b4vq
#### Datacap Allocated
> 250.00TiB
#### Signer Address
> f1cjzbiy5xd4ehera4wmbz63pd5ku4oo7g52cldga
#### Id
> b23dedf1-3fe7-4252-92f3-95579320c9f3
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaz475pjynvnlmogbommkh7xffnx6x5prttdqxnialb76d6ob2gse

**Comment by Filplus-govteam** [comment]
Just to re-confirm the process here @tmzxi - after storage is complete we will ask notaries to:

- Confirm SP IDs and locations match your plan
- Confirm data is retrievable and data sample matches said datasets

**Comment by Filplus-govteam** [comment]
checker:manualTrigger

**Comment by tmzxi** [comment]
Please continue. Thank you

**Comment by tmzxi** [comment]
Please keep it open，Thank you

**Comment by tmzxi** [comment]
Please keep it open，Thank you

**Comment by tmzxi** [comment]
Please keep it open，Thanks

**Comment by tmzxi** [comment]
checker:manualTrigger

**Comment by kevzak** [comment]
SPs listed on registration form

f01929568 Power Meta Corp. Stockholm, Sweden
f02236292 Unknown(email not provided) Oregon, United States
f01105825 JClound Ningxia China
f01966377 person Ningxia China

SPs taking deals:

f02519323 | Yinchuan, Ningxia Hui Autonomous Region, CNCHINANET NINGXIA province ZHONGWEI IDC network | 49.41 TiB | 29.95% | 49.41 TiB | 0.00%
f03223 | Clifton, New Jersey, USDigitalOcean, LLC | 42.89 TiB | 26.00% | 42.89 TiB | 0.00%
f0143858 | Clifton, New Jersey, USDigitalOcean, LLC | 32.48 TiB | 19.69% | 32.45 TiB | 0.10%
f01969779 | Clifton, New Jersey, USDigitalOcean, LLC | 24.66 TiB | 14.95% | 24.66 TiB | 0.00%
f02301 | Clifton, New Jersey, USDigitalOcean, LLC | 15.50 TiB | 9.40% | 15.47 TiB | 0.20%

Not one matching SP ID. Closing

**Comment by tmzxi** [comment]
@kevzak  
I am very sorry that the 3 sp I looked for before chose not to be packaged in recent months due to their own reasons, so I found the other 3 sp again, but I did not update the sp information in time, so you think we do not meet the rules. Please believe us, we will comply with every rule of fil+ in the future, please help to reopen this issue. Thank you very much,

**Comment by tmzxi** [comment]
@kevzak 

Here are the new sp we found, respectively in China, Singapore, and the United States，7 different nodes，Please reopen it. Thank you very much，best wishes

SP Miner IDs：f02093396, f02259777
Contact name：Lingchao Xu
Email：lingchao.xu@bitdeer.com
Organization Name：STRAITDEER PTE. LTD.
Region：Singapore
Using VPN?：No
Slack handle：xlcbd(ID:U0453ME4D7X)


SP Miner IDs：f02301,f03223,f0143858
Contact name：HarryM
Organization Name：topblocks
Region：Santa Clara(US)
Using VPN?：No
Slack handle：HarryM

SP Miner IDs：f01969779
Contact name：nick	
Organization Name：nick
Region：Santa Clara(US)
Using VPN?：No
Slack handle：nickcoming

SP Miner IDs：f02519323
Contact name：Aine
Organization Name：Hainan future cloud Technology Co., LTD
Region：ningxia china
Using VPN?：No
slack: l Aine (Amethystx)

**Comment by tmzxi** [comment]
@kevzak  Please check the sp information I provided，Please help to reopen the issue, thank you very much

**Comment by tmzxi** [comment]
@kevzak  Hi kevzak，I'm sorry for not updating sp information in time， Please check the information I provided，We will strictly abide by fil+ rules in the future，Help re-open the issue，Thank you very much


sp                                                                      ids                                             origin
Hainan future cloud Technology Co., LTD       f02519323                                 ningxia(CN)
topblocks                                                       f02301,f03223,f0143858             New Jersey(US)
nick                                                                 f01969779                                  New Jersey(US)
STRAITDEER PTE. LTD.                                     f02093396, f02259777               Singapore

**Comment by tmzxi** [comment]
@kevzak    @Sunnyiscoming  can you help me reopen this issue？ If you need any more information, please let me know. Thank you

**Comment by tmzxi** [comment]
checker:manualTrigger

**Comment by tmzxi** [comment]
@kevzak  I have updated all the current sp information， can you help me reopen this issue? thank you
