### ISSUE TITLE
[DataCap Application] <Beijing Saide Weikang Medical Research Institute> - <medical treatment>

### ISSUE THREAD

**Issue by xdwk999** [filecoin-project/filecoin-plus-large-datasets#2126]
### Data Owner Name

Beijing Saide Weikang Medical Research Institute

### What is your role related to the dataset

Data Preparer

### Data Owner Country/Region

China

### Data Owner Industry

Life Science / Healthcare

### Website

no

### Social Media

```text
010-58895660
```

### Total amount of DataCap being requested

5PiB

### Expected size of single dataset (one copy)

500T

### Number of replicas to store

10

### Weekly allocation of DataCap requested

500TiB

### On-chain address for first allocation

f1ggvuguykcmcv67fastulivcvj4iyzgwd7vznapa

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Beijing Saide Weikang Medical Research Institute mainly engages in research on cardiovascular, neuropsychiatric, and immune drugs and health products. Having a large number of advanced instruments and equipment provides strong support for the research and development of new drugs. Able to independently complete the entire process of new drug synthesis design, quality research, formulation process research, preclinical pharmacodynamics and toxicology evaluation, and organization of clinical trials. It has professional teams in Medicinal chemistry, Analytical chemistry, pharmaceutical preparations, pharmacology, toxicology, molecular biology, electronic biology, biochemistry and biomedical information.
Beijing Saideweikang Medical Research Institute and the Academy of Military Medical Sciences jointly set up a drug research center for cardio cerebral Vascular disease treatment. Relying on the strong scientific research strength of the Academy of Military Medical Sciences and its own scientific management mechanism, it focuses on the research and production of new drugs of cardio cerebral vascular class I, and has made remarkable achievements in the research of cardiovascular innovative drugs such as hypertension, heart failure, stroke, Atherosclerosis. Received one second prize of the National Natural Science Award, multiple first and second prizes of Beijing Municipal and Provincial Science and Technology Progress Awards, and applied for multiple independent intellectual property rights for inventions.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
Teaching videos, demonstration videos, research videos, practical teaching videos, etc. in the medical field
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### If you are a data preparer. What is your location (City and Country)

```text
CHINA
```

### If you are a data preparer, how will the data be prepared? Please include tooling used and technical details?

```text
Using singularities to package data, our team is familiar with generating many files ending in. car based on this link：https://github.com/tech-greedy/singularity
```

### If you are not preparing the data, who will prepare the data?  (Provide name and business)

```text
I am preparing the data
```

### Has this dataset been stored on the Filecoin network before? If so, please explain and make the case why you would like to store this dataset again to the network. Provide details on preparation and/or SP distribution.

```text
Not stored on filecoin
name-ID-email-area
Mike-f02062851-ye334452000@gmail.com-USA
Eager-f02337006-h32590056@gmail.com-England
Aron-f01877184-aron99301@gmail.com-Singapore
Huang-f01836766-8954056@qq.com-China
```

### Please share a sample of the data

```text
https://www.aliyundrive.com/s/js8Yp2U7SAr
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Monthly

### For how long do you plan to keep this dataset stored on Filecoin

More than 3 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, South America, Europe

### How will you be distributing your data to storage providers

HTTP or FTP server, Shipping hard drives

### How do you plan to choose storage providers

Slack

### If you already have a list of storage providers to work with, fill out their names and provider IDs below

```text
name-ID-email-area
Mike-f02062851-ye334452000@gmail.com-USA
Eager-f02337006-h32590056@gmail.com-England
Aron-f01877184-aron99301@gmail.com-Singapore
Huang-f01836766-8954056@qq.com-China
```

### How do you plan to make deals to your storage providers

Boost client, Singularity

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
Could you send an email with your business license to filplus-app-review@fil.org with your official domain in order to confirm your identity? Email name should includes the issue id #2126.

**Comment by Filplus-govteam** [comment]
Hi @xdwk999 

Per the https://github.com/filecoin-project/notary-governance/issues/922 for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

This information will be reviewed by Fil+ Governance team to confirm validity and then the application will be triggered for notary review. Let us know if you have any questions.

**Comment by xdwk999** [comment]
> Hi @xdwk999
> 
> Per the [filecoin-project/notary-governance#922](https://github.com/filecoin-project/notary-governance/issues/922) for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.
> 
> This information will be reviewed by Fil+ Governance team to confirm validity and then the application will be triggered for notary review. Let us know if you have any questions.

Form submitted，THKS！

**Comment by xdwk999** [comment]
> Could you send an email with your business license to [filplus-app-review@fil.org](mailto:filplus-app-review@fil.org) with your official domain in order to confirm your identity? Email name should includes the issue id #2126.

![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/139419684/8ca41077-c4f7-484c-8b9e-80bf3317b71f)
Please check

**Comment by Sunnyiscoming** [comment]
Received business license.

**Comment by xdwk999** [comment]
@Sunnyiscoming @Filplus-govteam It's been a week now, any more questions please?

**Comment by Filplus-govteam** [comment]
Hello @songyongren your form does not include SP business emails or proof of SP entities. Please confirm

**Comment by xdwk999** [comment]
I'll contact SP right away and they'll reconfirm the email situation, thanks!

**Comment by xdwk999** [comment]
> Hello @xdwk999 your form does not include SP business emails or proof of SP entities. Please confirm

They said they have all confirmed the relevant entities and replied to the email, could you please reconfirm or be more specific as to what's wrong, thanks!

**Comment by Filplus-govteam** [comment]
> Beijing Saide Weikang Medical Research Institute

@Sunnyiscoming where is business name in email included anywhere?

**Comment by xdwk999** [comment]
> OK @xdwk999 f02062851 sent utility bill from a 'partner' in Stockton California. No one named Mike on email or bill. Let's see f02337006 sent a utility bill for supply company in London England. No one name Eager on email or bill. Let's see.

They explained to me that they are all 2-4 people working together to co-build SPs and the contact provided is just one of them, so please confirm!

**Comment by Filplus-govteam** [comment]
ok thank you @xdwk999 . FYI @Sunnyiscoming

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 5PiB

**Expected weekly DataCap usage rate**
> 500TiB

**Client address**
>f1ggvuguykcmcv67fastulivcvj4iyzgwd7vznapa

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 5PiB

**Expected weekly DataCap usage rate**
> 500TiB

**Client address**
>f1ggvuguykcmcv67fastulivcvj4iyzgwd7vznapa

**Comment by herrehesse** [comment]
Mike-f02062851 USA
Eager-f02337006 England
Aron-f01877184 Singapore
Huang-f01836766 China

The minerID list on this applicant is filled with previous abuse or VPN use, not being honest about their real location. Suggesting notaries not to engage.

**Comment by xdwk999** [comment]
> > Hello @xdwk999 your form does not include SP business emails or proof of SP entities. Please confirm
> 
> They said they have all confirmed the relevant entities and replied to the email, could you please reconfirm or be more specific as to what's wrong, thanks!

@herrehesse Check out this review, SPs they say it's verified，thank you

**Comment by xdwk999** [comment]
Is there a notary review here?

**Comment by BlockMakeronline** [comment]
Maybe you can ask more sps join in data storage.

**Comment by xdwk999** [comment]
> Maybe you can ask more sps join in data storage.

I've been looking for more SPs again and currently have a few in talks to work together

**Comment by xdwk999** [comment]
keep open

**Comment by xdwk999** [comment]
> Are there any new SPs joining?

yes，These two will be added later
f02808888
f01128206

**Comment by xdwk999** [comment]
@BlockMakeronline  hi，Can you sign it?

**Comment by zcfil** [comment]
Saw it multiple times at slack, content looks good, willing to support the first round, will follow up on the data

**Comment by zcfil** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceazberpg5nfsjsbl5dqqcaqiryiy6zr2mgipndafyad2tdagavmzg 
#### Address 
> f1ggvuguykcmcv67fastulivcvj4iyzgwd7vznapa
#### Datacap Allocated
> 250.00TiB
#### Signer Address
> f1cjzbiy5xd4ehera4wmbz63pd5ku4oo7g52cldga
#### Id
> b6c2b264-12be-4a99-a3d8-da39b6ffc98d
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceazberpg5nfsjsbl5dqqcaqiryiy6zr2mgipndafyad2tdagavmzg

**Comment by xdwk999** [comment]
checker:manualTrigger

**Comment by xdwk999** [comment]
checker:manualTrigger

**Comment by xdwk999** [comment]
checker:manualTrigger

**Comment by nj-steve** [comment]
checker:manualTrigger

**Comment by nj-steve** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceafduuqrufflby4vdxjlege2rqeiq4npgfmgzmczjsmegbob22twk 
#### Address 
> f1ggvuguykcmcv67fastulivcvj4iyzgwd7vznapa
#### Datacap Allocated
> 500.00TiB
#### Signer Address
> f1xx6555qijma7igpnjspyvdunc4vfxkawnpqy5ii
#### Id
> 772d6433-104f-4727-9dbd-535c1cc73f10
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceafduuqrufflby4vdxjlege2rqeiq4npgfmgzmczjsmegbob22twk

**Comment by nj-steve** [comment]
The reports look so nice.Willing to support.

**Comment by AlanGreaterheat** [comment]
checker:manualTrigger

**Comment by AlanGreaterheat** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecmbagmb5joaqrzqd6jxnfrkk2z5yhbjyfbzvnvpdo4h5zmzajc4y 
#### Address 
> f1ggvuguykcmcv67fastulivcvj4iyzgwd7vznapa
#### Datacap Allocated
> 500.00TiB
#### Signer Address
> f1pnmzlxj7cfeo2v6oj5nco46hkg2l46wj7o4xxui
#### Id
> 772d6433-104f-4727-9dbd-535c1cc73f10
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecmbagmb5joaqrzqd6jxnfrkk2z5yhbjyfbzvnvpdo4h5zmzajc4y

**Comment by xdwk999** [comment]
checker:manualTrigger

**Comment by xdwk999** [comment]
checker:manualTrigger

**Comment by xdwk999** [comment]
checker:manualTrigger

**Comment by xdwk999** [comment]
checker:manualTrigger

**Comment by sxxfuture-official** [comment]
reports looks good, will support

**Comment by sxxfuture-official** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebut2omwovbsuci5mmbpxv6jxyhlguogp3lq663rn3e5l5yavbvje 
#### Address 
> f1ggvuguykcmcv67fastulivcvj4iyzgwd7vznapa
#### Datacap Allocated
> 1000.00TiB
#### Signer Address
> f1foiomqlmoshpuxm6aie4xysffqezkjnokgwcecq
#### Id
> df18bc86-7020-4d6e-9b5d-f201afdd30e3
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebut2omwovbsuci5mmbpxv6jxyhlguogp3lq663rn3e5l5yavbvje

**Comment by kernelogic** [comment]
High retrieval rate, willing to support.

**Comment by kernelogic** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceapkk7k7h5b6gvrtg5ynpmgxxxw7w7dckvdifo3eocvh4h3jzfjm6 
#### Address 
> f1ggvuguykcmcv67fastulivcvj4iyzgwd7vznapa
#### Datacap Allocated
> 1000.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### Id
> df18bc86-7020-4d6e-9b5d-f201afdd30e3
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceapkk7k7h5b6gvrtg5ynpmgxxxw7w7dckvdifo3eocvh4h3jzfjm6

**Comment by xdwk999** [comment]
checker:manualTrigger

**Comment by xdwk999** [comment]
checker:manualTrigger

**Comment by xdwk999** [comment]
checker:manualTrigger

**Comment by NiwanDao** [comment]
LGTM

**Comment by NiwanDao** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebgm2cuuygfsytnfykkuofdwb7rjgnbjo2ykyqncybn7v632lnnhw 
#### Address 
> f1ggvuguykcmcv67fastulivcvj4iyzgwd7vznapa
#### Datacap Allocated
> 1.95PiB
#### Signer Address
> f1a2lia2cwwekeubwo4nppt4v4vebxs2frozarz3q
#### Id
> f26f00a1-60f0-4e6e-be8c-5ce28fcc1afd
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebgm2cuuygfsytnfykkuofdwb7rjgnbjo2ykyqncybn7v632lnnhw

**Comment by kevzak** [comment]
SPs taking deals

f01877184 | Singapore, Singapore, SGAlibaba (US) Technology Co., Ltd. | 17.75 TiB | 2.42% | 17.75 TiB | 0.00%
f02252173 | Tokyo, Tokyo, JPAwesomecloud Limited | 129.19 TiB | 17.60% | 129.19 TiB | 0.00%
f02808888 | Shenzhen, Guangdong, CNCHINANET-BACKBONE | 108.69 TiB | 14.81% | 108.69 TiB | 0.00%
f01970716 | Shenzhen, Guangdong, CNCHINANET-BACKBONE | 40.88 TiB | 5.57% | 40.88 TiB | 0.00%
f01836766 | Shenzhen, Guangdong, CNCHINANET-BACKBONE | 20.44 TiB | 2.78% | 20.44 TiB | 0.00%
f02237010 | Los Angeles, California, USCNSERVERS LLC | 103.50 TiB | 14.10% | 103.47 TiB | 0.03%
f02237006 | London, England, GBFifth Dog Network Limited | 108.78 TiB | 14.82% | 108.75 TiB | 0.03%
f02816666 | Hohhot, Inner Mongolia, CNHangzhou Alibaba Advertising Co.,Ltd. | 128.53 TiB | 17.51% | 119.47 TiB | 7.05%
f02808889new | Aberdeen, Southern, HKHK Kwaifong Group Limited | 47.22 TiB | 6.43% | 47.22 TiB | 0.00%
f02062851 | Los Angeles, California, USNetLab Global | 29.13 TiB | 3.97% | 29.13 TiB | 0.00%


Miner IDs listed on registration:
Mike-f02062851 USA
Eager-f02337006 England
Aron-f01877184 Singapore
Huang-f01836766 China

SP IDs do not match. Please announce all other entities involved. Closing until updated.

**Comment by xdwk999** [comment]
@kevzak Update SPs information
| miner ID   | name    | region       |
| --------- | ------- | ------------ |
| f02252173 | luna    | Tokyo        |
| f02808888 | guan    | GuangZhou    |
| f02808889 | lan     | Hong Kong    |
| f02237010 | peter   | Californial  |
| f02816666 | jastin  | Huhehaote    |
| f01970716 | Zhang   | GuangZhou    |

**Comment by xdwk999** [comment]
@kevzak Can you reopen it, please?

**Comment by xdwk999** [comment]
checker:manualTrigger

**Comment by xdwk999** [comment]
checker:manualTrigger

**Comment by xdwk999** [comment]
checker:manualTrigger

**Comment by xdwk999** [comment]
checker:manualTrigger

**Comment by xdwk999** [comment]
checker:manualTrigger

**Comment by xdwk999** [comment]
checker:manualTrigger

**Comment by xdwk999** [comment]
checker:manualTrigger

**Comment by woshidama323** [comment]
LGTM, a very healthy report, Will support this 
Also, keep tracing

**Comment by woshidama323** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb5zrm34fqhdp2lsqpk5cl3diivycjmoovk2jaml2ky7nlssxcdog 
#### Address 
> f1ggvuguykcmcv67fastulivcvj4iyzgwd7vznapa
#### Datacap Allocated
> 1.34PiB
#### Signer Address
> f12tk3adljauwnd3hjbigpfxb7b7gdlj63p6afwtq
#### Id
> 273d68a6-e78e-46ff-8bf4-4679b3cb8215
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb5zrm34fqhdp2lsqpk5cl3diivycjmoovk2jaml2ky7nlssxcdog

**Comment by zcfil** [comment]
checker:manualTrigger

**Comment by zcfil** [comment]
The client contacted me again and yesterday a random copy of the data was retrieved to check and it matched the application, so we are willing to support the round
![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/45065975/2aea5384-4541-4bc5-9b37-9b7bc13f0b32)
![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/45065975/89455d6c-c1de-4aad-a72b-dfeb2fbb32c9)

![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/45065975/87d9b04c-91b7-4785-b2eb-f031c8d83727)

**Comment by zcfil** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb2vysg6b6ua4za2rzuxfkixeao3mw7ih2zaf2dlo6gtesx3a46by 
#### Address 
> f1ggvuguykcmcv67fastulivcvj4iyzgwd7vznapa
#### Datacap Allocated
> 1.34PiB
#### Signer Address
> f1cjzbiy5xd4ehera4wmbz63pd5ku4oo7g52cldga
#### Id
> 273d68a6-e78e-46ff-8bf4-4679b3cb8215
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb2vysg6b6ua4za2rzuxfkixeao3mw7ih2zaf2dlo6gtesx3a46by

**Comment by xdwk999** [comment]
checker:manualTrigger

**Comment by xdwk999** [comment]
checker:manualTrigger

**Comment by xdwk999** [comment]
checker:manualTrigger

**Comment by xdwk999** [comment]
checker:manualTrigger

**Comment by xdwk999** [comment]
checker:manualTrigger

**Comment by xdwk999** [comment]
checker:manualTrigger

**Comment by xdwk999** [comment]
checker:manualTrigger

**Comment by Normalnoise** [comment]
checker:manualTrigger

**Comment by Normalnoise** [comment]
lotus state get-deal 60719902
{
  "Proposal": {
    "PieceCID": {
      "/": "baga6ea4seaqosbjddrquohched5uebmgokev6px4fm5icbcbfjov4u3lflle2ai"
    },
    "PieceSize": 34359738368,
    "VerifiedDeal": true,
    "Client": "f02814601",
    "Provider": "f02816666",
    "Label": "bafybeiev6dqttjakcgoa2my3lnhzb5ixbnr2q2mul2zh4v6jqbg7ucsnyu",
    "StartEpoch": 3363111,
    "EndEpoch": 4889511,
    "StoragePricePerEpoch": "0",
    "ProviderCollateral": "8910676056022483",
    "ClientCollateral": "0"
  },
  "State": {
    "SectorStartEpoch": 3343943,
    "LastUpdatedEpoch": -1,
    "SlashEpoch": -1,
    "VerifiedClaim": 43017399
  }
}

lotus client  retrieve --miner f02816666 bafybeiev6dqttjakcgoa2my3lnhzb5ixbnr2q2mul2zh4v6jqbg7ucsnyu 2126
Recv 0 B, Paid 0 FIL, Open (New), 0s [1695727115720611817|0]
Recv 0 B, Paid 0 FIL, DealProposed (WaitForAcceptance), 3ms [1695727115720611817|0]
Recv 0 B, Paid 0 FIL, DealAccepted (Accepted), 110ms [1695727115720611817|0]
Recv 0 B, Paid 0 FIL, PaymentChannelSkip (Ongoing), 110ms [1695727115720611817|0]
Recv 17.86 KiB, Paid 0 FIL, BlocksReceived (Ongoing), 301ms [1695727115720611817|18291]
Recv 24.71 KiB, Paid 0 FIL, BlocksReceived (Ongoing), 302ms [1695727115720611817|25301]
Recv 1.024 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 908ms [1695727115720611817|1073877]
Recv 2.024 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 2.439s [1695727115720611817|2122453]
Recv 3.024 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 3.952s [1695727115720611817|3171029]
Recv 4.024 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 5.46s [1695727115720611817|4219605]
Recv 5.024 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 6.98s [1695727115720611817|5268181]
Recv 6.024 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 8.455s [1695727115720611817|6316757]
Recv 7.024 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 9.986s [1695727115720611817|7365333]
Recv 8.024 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 11.554s [1695727115720611817|8413909]
Recv 9.024 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 12.977s [1695727115720611817|9462485]
Recv 10.02 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 14.506s [1695727115720611817|10511061]
Recv 11.02 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 15.983s [1695727115720611817|11559637]
Recv 12.02 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 17.51s [1695727115720611817|12608213]
Recv 13.02 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 19.629s [1695727115720611817|13656789]
Recv 14.02 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 21.722s [1695727115720611817|14705365]
Recv 15.02 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 22.927s [1695727115720611817|15753941]
Recv 16.02 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 23.873s [1695727115720611817|16802517]
Recv 17.02 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 25.456s [1695727115720611817|17851093]
Recv 18.02 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 26.827s [1695727115720611817|18899669]
Recv 19.02 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 28.408s [1695727115720611817|19948245]
Recv 20.02 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 29.836s [1695727115720611817|20996821]
Recv 21.02 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 31.317s [1695727115720611817|22045397]
Recv 22.02 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 32.946s [1695727115720611817|23093973]
Recv 23.02 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 34.374s [1695727115720611817|24142549]
Recv 24.02 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 36.01s [1695727115720611817|25191125]
Recv 25.02 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 37.312s [1695727115720611817|26239701]
Recv 26.02 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 38.954s [1695727115720611817|27288277]
Recv 27.02 MiB, Paid 0 FIL, BlocksReceived (Ongoing), 40.468s [1695727115720611817|28336853]

**Comment by Normalnoise** [comment]
the report is healthy, willing to support it next round

**Comment by Normalnoise** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecuervqfazo4j3nc6trm52fcksjjoqr6rpuietvr53jurvprofvpc 
#### Address 
> f1ggvuguykcmcv67fastulivcvj4iyzgwd7vznapa
#### Datacap Allocated
> 1.34PiB
#### Signer Address
> f1c5non5yf35avgcpsqvxu4yj54yyvxorwyjochqq
#### Id
> 62312748-fbd4-44e3-a636-47c881317f33
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecuervqfazo4j3nc6trm52fcksjjoqr6rpuietvr53jurvprofvpc

**Comment by xdwk999** [comment]
Update SP Information：
Miner ID	Name	Region
f01877184	Aron	Singapore
f02252173	luna	     Tokyo
f02828888	Zhang	GuangZhou
f02808888	guan	GuangZhou
f02808889	guan	Hong Kong
f02816666	jastin	Huhehaote
f01836766	Huang	GuangZhou
f02237006	eager	England
f02237010	peter	Californial
f01970716	Zhang	GuangZhou
f02062851	Mike	Californial

**Comment by xdwk999** [comment]
checker:manualTrigger

**Comment by stcouldlisa** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebbs74wcq5xsiep7wmh34kylhnxxqeerurylvez62bs47xwor7bfi 
#### Address 
> f1ggvuguykcmcv67fastulivcvj4iyzgwd7vznapa
#### Datacap Allocated
> 1.34PiB
#### Signer Address
> f1jvvltduw35u6inn5tr4nfualyd42bh3vjtylgci
#### Id
> 62312748-fbd4-44e3-a636-47c881317f33
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebbs74wcq5xsiep7wmh34kylhnxxqeerurylvez62bs47xwor7bfi

**Comment by xdwk999** [comment]
checker:manualTrigger

**Comment by xdwk999** [comment]
fulfillment
