### ISSUE TITLE
[DataCap Application] <spark thinking>

### ISSUE THREAD

**Issue by dongpo313** [filecoin-project/filecoin-plus-large-datasets#2127]
### Data Owner Name

spark thinking

### What is your role related to the dataset

Data Preparer

### Data Owner Country/Region

China

### Data Owner Industry

Education & Training

### Website

https://www.huohua.cn/

### Social Media

```text
https://www.huohua.cn/
```

### Total amount of DataCap being requested

5PiB

### Expected size of single dataset (one copy)

500t

### Number of replicas to store

10

### Weekly allocation of DataCap requested

800TiB

### On-chain address for first allocation

f1ssjltetryapae755lkrwijvnr3b66kso5pqchhy

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
The Spark Thinking project was established in December 2017. It mainly adopts the method of small class live broadcast class and real-person interactive AI class. Through the inspiration and guidance of the teacher and the three-dimensional combination of animation, games, and interesting teaching aids, it integrates knowledge, ability, and thinking. Interconnected and progressive, cultivate core basic abilities such as logical reasoning and independent problem-solving in interactive practice, and lay a good foundation for future lifelong learning
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
1. Live class video.
2. Real-person interactive AI class video.
3. Videos of animation, games, and interesting teaching aids.
```

### Where was the data currently stored in this dataset sourced from

Other

### If you answered "Other" in the previous question, enter the details here

```text
Online Educational Videos.
```

### If you are a data preparer. What is your location (City and Country)

```text
china,beijing
```

### If you are a data preparer, how will the data be prepared? Please include tooling used and technical details?

```text
tar,boost
```

### Has this dataset been stored on the Filecoin network before? If so, please explain and make the case why you would like to store this dataset again to the network. Provide details on preparation and/or SP distribution.

```text
Try new things, embrace blockchain, save filing costs.
I need a lot of sp from China, and some sp from Hong Kong, Singapore, I am going to store 10 copies.
```

### Please share a sample of the data

```text
https://drive.google.com/file/d/1diSVPWmCNLjBxaoxhBX4PrAztxbbTgF4/view?usp=share_link
https://drive.google.com/file/d/1sF3r2zbNyqK9DmHuKMDCELY9xq-J_2u4/view?usp=share_link
https://drive.google.com/file/d/1XIMu4p6WYte5D6OUpCq0F_qotsf0jI9f/view?usp=share_link
https://drive.google.com/file/d/1Jmer6bVXHKbu8HIFyU_IusKpC9QyyFDS/view?usp=share_link
https://drive.google.com/file/d/1wJxQXfmfq5YG97UkgOrUbUmGXI6tGB6_/view?usp=share_link
https://drive.google.com/file/d/1SmR_gfaLcJO7UliIilUXIxb0hr-SGndg/view?usp=share_link
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

1.5 to 2 years

### In which geographies do you plan on making storage deals

Greater China

### How will you be distributing your data to storage providers

HTTP or FTP server

### How do you plan to choose storage providers

Slack, Big Data Exchange, Partners

### If you already have a list of storage providers to work with, fill out their names and provider IDs below

```text
f01302188
f02058146
f01697248
f02086562
f02058146
```

### How do you plan to make deals to your storage providers

Boost client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
- Have you prepared enough token for sector pledge?
- Can you list Miner ID, Business Entity, Location of sps you will cooperate with.

**Comment by Filplus-govteam** [comment]
Hi @dongpo313 
Per the https://github.com/filecoin-project/notary-governance/issues/922 for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

This information will be reviewed by Fil+ Governance team to confirm validity and then the application will be triggered for notary review. Let us know if you have any questions.

**Comment by hyunmoon** [comment]
I'm the operator of one of the miners listed here but I was never in contact with this applicant.

**Comment by MatrixStorage** [comment]
Is there anything to update here？

**Comment by dongpo313** [comment]
> * Have you prepared enough token for sector pledge?
> * Can you list Miner ID, Business Entity, Location of sps you will cooperate with.
> 
> > f01302188
> > f02058146
> > f01697248
> > f02086562
> > f02058146

f01302188 Zhengzhou, Henan, CN
f02058146 Shenzhen, Guangdong, CN
f01697248 Seongnam-si, Gyeonggi-do, KR
f02086562 Wuhan, Hubei, CN

**Comment by hyunmoon** [comment]
> > * Have you prepared enough token for sector pledge?
> > * Can you list Miner ID, Business Entity, Location of sps you will cooperate with.
> > 
> > > f01302188
> > > f02058146
> > > f01697248
> > > f02086562
> > > f02058146
> 
> f01302188 Zhengzhou, Henan, CN f02058146 Shenzhen, Guangdong, CN f01697248 Seongnam-si, Gyeonggi-do, KR f02086562 Wuhan, Hubei, CN

Operator of f01697248 here.
Not located in Seongnam-si, Gyeonggi-do, KR.
Was never in contact with the applicant.

**Comment by dongpo313** [comment]
> > > * Have you prepared enough token for sector pledge?
> > > * Can you list Miner ID, Business Entity, Location of sps you will cooperate with.
> > > 
> > > > f01302188
> > > > f02058146
> > > > f01697248
> > > > f02086562
> > > > f02058146
> > 
> > 
> > f01302188 Zhengzhou, Henan, CN f02058146 Shenzhen, Guangdong, CN f01697248 Seongnam-si, Gyeonggi-do, KR f02086562 Wuhan, Hubei, CN
> 
> Operator of f01697248 here. Not located in Seongnam-si, Gyeonggi-do, KR. Was never in contact with the applicant.

I have seen the information about you on BDE. You have a good reputation and retrieval rate. Are you interested in storing the data for our project?

**Comment by hyunmoon** [comment]
> > > > * Have you prepared enough token for sector pledge?
> > > > * Can you list Miner ID, Business Entity, Location of sps you will cooperate with.
> > > > 
> > > > > f01302188
> > > > > f02058146
> > > > > f01697248
> > > > > f02086562
> > > > > f02058146
> > > 
> > > 
> > > f01302188 Zhengzhou, Henan, CN f02058146 Shenzhen, Guangdong, CN f01697248 Seongnam-si, Gyeonggi-do, KR f02086562 Wuhan, Hubei, CN
> > 
> > 
> > Operator of f01697248 here. Not located in Seongnam-si, Gyeonggi-do, KR. Was never in contact with the applicant.
> 
> I have seen the information about you on BDE. You have a good reputation and retrieval rate. Are you interested in storing the data for our project?

Yes, please.
My filecoin slack handle is also hyunmoon.

**Comment by hyunmoon** [comment]
> > > > * Have you prepared enough token for sector pledge?
> > > > * Can you list Miner ID, Business Entity, Location of sps you will cooperate with.
> > > > 
> > > > > f01302188
> > > > > f02058146
> > > > > f01697248
> > > > > f02086562
> > > > > f02058146
> > > 
> > > 
> > > f01302188 Zhengzhou, Henan, CN f02058146 Shenzhen, Guangdong, CN f01697248 Seongnam-si, Gyeonggi-do, KR f02086562 Wuhan, Hubei, CN
> > 
> > 
> > Operator of f01697248 here. Not located in Seongnam-si, Gyeonggi-do, KR. Was never in contact with the applicant.
> 
> I have seen the information about you on BDE. You have a good reputation and retrieval rate. Are you interested in storing the data for our project?

Thank you for your offer but I haven't had any success with DPs located in mainland China.
So, I think I will have to pass.

**Comment by dongpo313** [comment]
> > > > > * Have you prepared enough token for sector pledge?
> > > > > * Can you list Miner ID, Business Entity, Location of sps you will cooperate with.
> > > > > 
> > > > > > f01302188
> > > > > > f02058146
> > > > > > f01697248
> > > > > > f02086562
> > > > > > f02058146
> > > > 
> > > > 
> > > > f01302188 Zhengzhou, Henan, CN f02058146 Shenzhen, Guangdong, CN f01697248 Seongnam-si, Gyeonggi-do, KR f02086562 Wuhan, Hubei, CN
> > > 
> > > 
> > > Operator of f01697248 here. Not located in Seongnam-si, Gyeonggi-do, KR. Was never in contact with the applicant.
> > 
> > 
> > I have seen the information about you on BDE. You have a good reputation and retrieval rate. Are you interested in storing the data for our project?
> 
> Thank you for your offer but I haven't had any success with DPs located in mainland China. So, I think I will have to pass.

I will distribute my data in Hong Kong. Is it convenient for you?

**Comment by hyunmoon** [comment]
> > > > > > * Have you prepared enough token for sector pledge?
> > > > > > * Can you list Miner ID, Business Entity, Location of sps you will cooperate with.
> > > > > > 
> > > > > > > f01302188
> > > > > > > f02058146
> > > > > > > f01697248
> > > > > > > f02086562
> > > > > > > f02058146
> > > > > 
> > > > > 
> > > > > f01302188 Zhengzhou, Henan, CN f02058146 Shenzhen, Guangdong, CN f01697248 Seongnam-si, Gyeonggi-do, KR f02086562 Wuhan, Hubei, CN
> > > > 
> > > > 
> > > > Operator of f01697248 here. Not located in Seongnam-si, Gyeonggi-do, KR. Was never in contact with the applicant.
> > > 
> > > 
> > > I have seen the information about you on BDE. You have a good reputation and retrieval rate. Are you interested in storing the data for our project?
> > 
> > 
> > Thank you for your offer but I haven't had any success with DPs located in mainland China. So, I think I will have to pass.
> 
> I will distribute my data in Hong Kong. Is it convenient for you?

Absoutely. No problem in that case.

**Comment by MatrixStorage** [comment]
I haven't received any mail yet

**Comment by Sunnyiscoming** [comment]
Any update here?

**Comment by Sunnyiscoming** [comment]
Close for no reply.
