### ISSUE TITLE
[DataCap Application] <LaughStorage> - < Sloan Digital Sky Survey>

### ISSUE THREAD

**Issue by 26dos** [filecoin-project/filecoin-plus-large-datasets#2128]
### Data Owner Name

LaughStorage

### What is your role related to the dataset

Data Preparer

### Data Owner Country/Region

China

### Data Owner Industry

Not-for-Profit

### Website

https://www.sdss.org/

### Social Media

```text
NA
```

### Total amount of DataCap being requested

12PiB

### Expected size of single dataset (one copy)

1.2p

### Number of replicas to store

10

### Weekly allocation of DataCap requested

1PiB

### On-chain address for first allocation

f1gk53djusmlrwr2extftafi4m23agaacxxueh7aa

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
I joined the filecoin network in 2021, and made the cc package of fil at the very beginning.  In 2022, we did a part of cc to dc conversion, and now we have a planned continuous development of data storage. In 2023, I established a technical service company  <Laughstorage> to make in-depth investment in the distributed storage track.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
The Sloan Digital Sky Survey (SDSS) is one of the most ambitious and influential surveys in the history of astronomy. 
The SDSS project has established in 2000, five periods, 18 times data released. The 19th DR will be in 2024. 
As for now, there are about 750TB volume of data can be accessed.  5.5 million directories, 400 million files. 
DR1-DR7: SDSS-I, 2000-2005; SDSS-II, 2005-2008), it obtained deep, multi-color images covering more than a quarter of the sky and created 3-dimensional maps containing more than 930,000 galaxies and more than 120,000 quasars.
DR8: contains all images from the SDSS telescope - the largest color image of the sky ever made. It also includes measurements for nearly 500 million stars and galaxies, and spectra of nearly two million. 
DR9 contains the first release of BOSS spectroscopy to the public as well as several significant updates to the cumulative SDSS archive
DR10 contains the first release of APOGEE infrared Galactic spectroscopy as well as cumulative updates to the BOSS optical extragalactic spectroscopy archive
The SDSS began regular survey operations in 2000, after a decade of design and construction.  It has progressed through several phases, SDSS-I (2000-2005), SDSS-II (2005-2008), SDSS-III (2008-2014), and SDSS-IV (2014-2020).  Each of these phases has involved multiple surveys with interlocking science goals.  The three surveys that comprise SDSS-IV are eBOSS (including SPIDERS and TDSS), APOGEE-2, and MaNGA (including MaStar),
The SDSS-V Pioneering Panoptic Spectroscopy program started observing in October 2020, and consists of three surveys, known in SDSS-V terminology as mapper programs.

Milky Way Mapper is a multi-object spectroscopic survey to obtain near-infrared and/or optical spectra of more than 4 million stars throughout the Milky Way and Local Group
Local Volume Mapper is an optical, integral-field spectroscopic survey that will target the Milky Way, Small and Large Magellanic Clouds, and other Local Volume galaxies
Black Hole Mapper is a multi-object spectroscopic survey that emphasizes optical spectra (often also with multiple epochs of spectroscopy) for more than 300,000 quasars
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### If you are a data preparer. What is your location (City and Country)

```text
Mainland CN/HK/NA/Singapore/KR/Vietnam.. I can download data in those area cause i have machine.
```

### If you are a data preparer, how will the data be prepared? Please include tooling used and technical details?

```text
After processing the data I download, I will transfer through online.
```

### Has this dataset been stored on the Filecoin network before? If so, please explain and make the case why you would like to store this dataset again to the network. Provide details on preparation and/or SP distribution.

```text
AFAK NO
```

### Please share a sample of the data

```text
http://classic.sdss.org/dr7/
http://sdss3.org/
https://www.sdss4.org/dr17/data_access/volume/
https://dr17.sdss.org/sas/dr17/apogee/spectro/aspcap/
https://dr17.sdss.org/sas/dr17/apogee/spectro/speclib/
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

1-3 year

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, South America, Europe

### How will you be distributing your data to storage providers

Cloud storage (i.e. S3), HTTP or FTP server, IPFS, Lotus built-in data transfer, Others

### How do you plan to choose storage providers

Slack, Partners

### If you already have a list of storage providers to work with, fill out their names and provider IDs below

```text
f0861589 CN,SD C	
f02223876 HK, FTM Ltd.
f02212669 CN,Cryptomage
f02115125 KR, FiveByte
and more are connecting.
Actually is base on their collateral.
```

### How do you plan to make deals to your storage providers

Boost client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Filplus-govteam** [comment]
Hi @26dos 

Per the https://github.com/filecoin-project/notary-governance/issues/922 for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

This information will be reviewed by Fil+ Governance team to confirm validity and then the application will be triggered for notary review. Let us know if you have any questions.

**Comment by 26dos** [comment]
Hi @Filplus-govteam 

The registration form has submitted. Please take a look. thank you.

**Comment by Filplus-govteam** [comment]
Hello the following SP entities were submitted:
f0861589  SDCLOUD China
f02223876 FTM Ltd,. Hong Kong
f02115125 FiveByte Korea
f02212669 Cryptomage China

no contact information provided to confirm locations.

**Comment by Filplus-govteam** [comment]
Yes, this is the problem with the current process @26dos 

Good deal making starts with applicants working with trusted SP Entities that can prove who they are and where they are. Anyone can list a set of miner IDs. How do we know who you are, who they are, where they are?

**Comment by 26dos** [comment]
@Filplus-govteam 

We have communicated with the SPs, and considering privacy concerns, they are not willing to have their contact information disclosed publicly. However, you can contact SDCLOUD via email at: sdcloud@zcpow.cn

**Comment by herrehesse** [comment]
@26dos Hello friend, thanks for your LDN application.

How far are you with the download of the SDSS dataset? In previous slingshot competitions we also stored most of it and the download on a 80Gbps bandwidth line to Europe was not enough to download this set in under 4 years. Their source is slow.

Can you proof to me that you have the files on your DP location?

**Comment by 26dos** [comment]
@herrehesse 

The data download speed is pretty good on our end, here's the download link, and the file on the disk.

https://data.sdss.org/sas/dr18/data/apogee/spectro/apo/

![1ee861f1644f7c445fe1ee6b8ed3f0c](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/120706474/8e8a5229-86e9-42c8-8bfc-178809b6100c)
![6f6c78a10b082ad309c191b110f9e0e](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/120706474/91a620f1-5752-4a7e-a1cc-7105f814f9b9)

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 12PiB

**Expected weekly DataCap usage rate**
> 1PiB

**Client address**
>f1gk53djusmlrwr2extftafi4m23agaacxxueh7aa

**Comment by OpenGate01** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecxxhhx6hvqil65x2bxfpgsn473gp7yyo4oeqzwtpg7q5qzi6d352 
#### Address 
> f1gk53djusmlrwr2extftafi4m23agaacxxueh7aa
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f1im4hmtbfzqnx7ir74kdaiu4ynjhgqh3sdi2snla
#### Id
> 187c1abe-44a6-40a9-9a2b-e90bd2f9fc11
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecxxhhx6hvqil65x2bxfpgsn473gp7yyo4oeqzwtpg7q5qzi6d352

**Comment by AlanGreaterheat** [comment]
First round, willing to support

**Comment by AlanGreaterheat** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedvf64yw6colzisobsd3kvom6z66lnu355muvutasirnd4zqludpo 
#### Address 
> f1gk53djusmlrwr2extftafi4m23agaacxxueh7aa
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f1pnmzlxj7cfeo2v6oj5nco46hkg2l46wj7o4xxui
#### Id
> 187c1abe-44a6-40a9-9a2b-e90bd2f9fc11
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedvf64yw6colzisobsd3kvom6z66lnu355muvutasirnd4zqludpo

**Comment by 26dos** [comment]
checker:manualTrigger

**Comment by 26dos** [comment]
checker:manualTrigger

**Comment by cryptowhizzard** [comment]
checker:manualTrigger

**Comment by cryptowhizzard** [comment]
There is only one SP supporting retrieval ( http only ).

When i try to download something it errors. It's retrieval bot gaming.

Please fix ASAP 

<img width="1220" alt="Scherm­afbeelding 2023-08-23 om 21 54 43" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/36404435/52728da3-3823-4d7f-86d8-d77a8d622d8d">

**Comment by herrehesse** [comment]
@raghavrmadya @simonkim0515 Flagging for abuse.

**Comment by cryptowhizzard** [comment]
<img width="703" alt="Scherm­afbeelding 2023-08-26 om 21 48 53" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/36404435/84ec8c4c-b5b6-4c7b-bf49-71863d60b9b3">
<img width="1605" alt="Scherm­afbeelding 2023-08-26 om 21 50 40" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/36404435/79d87012-b418-4716-9d96-e4d5a0816dd6">

So, let's make up the math here.

grp & hrp are the graphsync retrieval rate and http retrieval rate according to the Fil+ retrieval bot.

f01834291 has recevied 0% of the total deals , so we don't need to count this one for retrieval.

f02226869 provides retrieval only over http. One small check on the data revealed you store garbage.

<img width="551" alt="Scherm­afbeelding 2023-08-26 om 21 55 16" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/36404435/de35ac9b-91f0-4748-a339-a6825fce97f5">

**Comment by cryptowhizzard** [comment]
Stop the trash talk will you?

As data preparer you are responsible to pack the right data and do the distribution to your SP's. I advise you to take a look at the whitepaper of Filecoin so you can learn that there is no way the SP can store different data then the data you provided to him.

Secondly , I provided you screenshot's above. As data preparer you should know what is wrong.

Thanks

**Comment by kevzak** [comment]
checker:manualTrigger

**Comment by raghavrmadya** [comment]
@kevzak , I see you have closed this application as completed. Confirming if DC must be removed based on dispute [here](https://www.notion.so/filecoin/No-retrieval-de75f10bfeed40e18d06d8a146061605?pvs=4)
