### ISSUE TITLE
[DataCap Application] <Xinjiang Nongyuan Jiaye Agricultural Investment Co., Ltd> - <agricultural data>

### ISSUE THREAD

**Issue by Brady168** [filecoin-project/filecoin-plus-large-datasets#2129]
### Data Owner Name

Xinjiang Nongyuan Jiaye Agricultural Investment Co., Ltd

### What is your role related to the dataset

Dataset Owner

### Data Owner Country/Region

China

### Data Owner Industry

Resources, Agriculture & Fisheries

### Website

N/A

### Social Media

```text
Email:2281895919@qq.com
```

### Total amount of DataCap being requested

4PiB

### Expected size of single dataset (one copy)

500T

### Number of replicas to store

7

### Weekly allocation of DataCap requested

400TiB

### On-chain address for first allocation

f1txfwjexmp4gp3dqdglgc3i7qacnyseocs4cecky

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Xinjiang Nongyuan Jiaye Agricultural Investment Co., Ltd. was established on July 26, 2016, and its registered address is 604, Floor 6, Jiangnan Senior Apartment, Saiwai, No. 1096, Karamay West Street, Saybag District, Ürümqi, Xinjiang. Its legal representative is Li Zhifeng. The business scope includes agricultural technology extension services, crop planting, agricultural services, Agricultural science research and experimental development, agricultural tourism, import and export of goods and technology, online trade agents, software and information technology services, Information technology consulting consulting services, vocational skills training, poultry breeding; Sales: agricultural products, livestock products, fresh aquatic products, daily necessities, vegetables and fruits; Wholesale and retail: pre packaged food and bulk food.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
Video files include displays of farmland, various plants and animals, research data and images, etc
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### If you are a data preparer. What is your location (City and Country)

```text
Xinjiang, China
```

### If you are a data preparer, how will the data be prepared? Please include tooling used and technical details?

```text
Our technical department has tested and mastered the packaging data and issued the order command, using the branch packaging data under singularity, and using the boost tool to issue the order.
```

### If you are not preparing the data, who will prepare the data?  (Provide name and business)

```text
Our own technical department prepares the data
```

### Has this dataset been stored on the Filecoin network before? If so, please explain and make the case why you would like to store this dataset again to the network. Provide details on preparation and/or SP distribution.

```text
N/A
```

### Please share a sample of the data

```text
https://drive.google.com/drive/folders/1nDKibmicmL4-c7YCEWwACMwA_SxrtCTE?usp=drive_link
https://drive.google.com/drive/folders/1eiaYIB4X-yG3zRZtaKElF-iLoC1VtU7j?usp=drive_link
https://drive.google.com/drive/folders/1mqyXgA1P0dfb8r9rhli3T-lL2676SJXz?usp=drive_link
https://drive.google.com/drive/folders/1V90RWTvFyZRA8hLshPse8mgXPNocQtm7?usp=drive_link
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Monthly

### For how long do you plan to keep this dataset stored on Filecoin

More than 3 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, South America, Europe

### How will you be distributing your data to storage providers

HTTP or FTP server, Shipping hard drives, Venus built-in data transfer

### How do you plan to choose storage providers

Slack, Partners

### If you already have a list of storage providers to work with, fill out their names and provider IDs below

```text
f02301
f03223
f0240185
f0143858
f02215422
f02062851
```

### How do you plan to make deals to your storage providers

Boost client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
- Have you prepared enough token for sector pledge?
- Are you a data preparer? What is your previous experience as a data-preparer? List previous applications and client IDs.
- Please list Miner ID, Business Entity, Location of sps you will cooperate with. (f02301, f03223, f0240185, f0143858, f02215422, f02062851)
- Could you send an email with business license to filplus-app-review@fil.org with your official domain in order to confirm your identity? Email name should includes the issue id #2129.

**Comment by Sunnyiscoming** [comment]
Hi @Brady168 

Per the https://github.com/filecoin-project/notary-governance/issues/922 for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

This information will be reviewed by Fil+ Governance team to confirm validity and then the application will be triggered for notary review. Let us know if you have any questions.

**Comment by Brady168** [comment]
> * Have you prepared enough token for sector pledge?

SPs they said they have enough tokens ready to pledge.
> * Are you a data preparer? What is your previous experience as a data-preparer? List previous applications and client IDs.

Our technical department has tested and mastered the packaging data and issued the order command, using the branch packaging data under singularity, and using the boost tool to issue the order.
> * Please list Miner ID, Business Entity, Location of sps you will cooperate with. (f02301, f03223, f0240185, f0143858, f02215422, f02062851)

f02301,f03223,f0240185,f0143858  belong to topblocks， Location：Santa Clara(US)
f02215422   belong to Li           Location：Hong Kong
 f02062851  belong to mike      Location：California(US)

> * Could you send an email with business license to [filplus-app-review@fil.org](mailto:filplus-app-review@fil.org) with your official domain in order to confirm your identity? Email name should includes the issue id [[DataCap Application] <Xinjiang Nongyuan Jiaye Agricultural Investment Co., Ltd> - <agricultural data> #2129](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/2129).

Applying and will be sent tomorrow morning

**Comment by Brady168** [comment]
@Sunnyiscoming 
![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/139442891/35323963-2efe-413e-98cf-99af7d2e6bff)
The business license has been sent, please keep it properly and do not disclose it,thanks.

**Comment by Filplus-govteam** [comment]
Hello, confirming the following SP Entities were submitted: 
f02301,f03223,f0240185,f0143858 Top Blocks USA
f02215422 Hong Kong
f02062851 California

**Comment by MatrixStorage** [comment]
The use of agricultural data will help agricultural results, I will pay attention to this project, if everything is compliant, I will support it.

**Comment by Brady168** [comment]
> Hello, confirming the following SP Entities were submitted: f02301,f03223,f0240185,f0143858 Top Blocks USA f02215422 Hong Kong f02062851 California
> 
> We are in contact with f02062851 to confirm location

f02062851 He told me he'd replied.

**Comment by Brady168** [comment]
> The use of agricultural data will help agricultural results, I will pay attention to this project, if everything is compliant, I will support it.

Thank you.

**Comment by Filplus-govteam** [comment]
Hello @Brady168 your form does not include SP business emails or proof of SP entities. Please confirm

**Comment by xdwk999** [comment]
> Hello @Brady168 your form does not include SP business emails or proof of SP entities. Please confirm

They say it's all personal, no commercial emails, and some of them haven't received emails from the relevant confirming entities, can you elaborate?

**Comment by Brady168** [comment]
@Filplus-govteam They all belong to individuals, so none of them have business emails and some of them have never received an email confirming the entity, can you specify?

**Comment by Filplus-govteam** [comment]
OK @Brady168 so we have:
4 IDs for f02301,f03223,f0240185,f0143858 Top Blocks California USA
f02215422 Hong Kong
f02062851 Stockton California USA Mike who we cannot truly confirm [ LINK](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/2126#issuecomment-1675188906)

**Comment by Brady168** [comment]
@Filplus-govteam If some of the SPs do not pass the review, I will temporarily terminate the cooperation with him until he passes the review, which is currently just f02062851 right?

**Comment by Brady168** [comment]
@herrehesse Hi，

We are currently using a cloud server + physical storage to store our company's data, but this cost is too high, I learned in the WeChat public number currently fil + can be stored for free, it would like to try, so the system to learn, and in accordance with the actual situation of the application.

**Comment by Filplus-govteam** [comment]
FYI @Sunnyiscoming

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 4PiB

**Expected weekly DataCap usage rate**
> 400TiB

**Client address**
>f1txfwjexmp4gp3dqdglgc3i7qacnyseocs4cecky

**Comment by MatrixStorage** [comment]
I am willing to support

**Comment by MatrixStorage** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced2dcprdzmhzdgjr42u6bb6cii4waxdb3ufdqhc7yjwjnhqmylbps 
#### Address 
> f1txfwjexmp4gp3dqdglgc3i7qacnyseocs4cecky
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1tbxqwjxfyv7swsdin4einirlsfquv3vnmlapley
#### Id
> fa93efc3-c3c0-42a8-b8a2-cdd2600a822a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced2dcprdzmhzdgjr42u6bb6cii4waxdb3ufdqhc7yjwjnhqmylbps

**Comment by cryptowhizzard** [comment]
@Brady168 

"4 IDs for f02301,f03223,f0240185,f0143858 Top Blocks California USA
f02215422 Hong Kong
f02062851 Stockton California USA Mike who we cannot truly confirm https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/2126#issuecomment-1675188906"

This is what you supplied. In the LDN you mention 7 replica's.

Let me make clear that you can send only 1 replica of this set to TopBlocks ... you have to share the set with f02301,f03223,f0240185,f0143858 and they are not allowed to receive the same CID's. How are you going to accomplish that?

Secondly , there are only 2 SP's left for replica 2 and 3. Where are the other 4 replica's going?

**Comment by Filplus-govteam** [comment]
Please clarify before 2nd notary signature @Brady168

**Comment by cryptowhizzard** [comment]
@Brady168 

No , you can not send 4 replica's of this set to 1 organization. This is called self-dealing.

**Comment by Brady168** [comment]
> @Brady168
> 
> No , you can not send 4 replica's of this set to 1 organization. This is called self-dealing.

Is there a link to the relevant rules?
It's not my sp. How can it be called self-dealing?

**Comment by cryptowhizzard** [comment]
See your screenshot above. One storage provider can hold / is holding more then one miner machines. 

Top Blocks is the storage provider in this case. They should not exceed 30% of the datacap. Given you have 3 entity's in your disclosure and 7 replica's to store this won't work. Reason i am calling out to you to make you aware.

**Comment by Brady168** [comment]
> See your screenshot above. One storage provider can hold / is holding more then one miner machines.
> 
> Top Blocks is the storage provider in this case. They should not exceed 30% of the datacap. Given you have 3 entity's in your disclosure and 7 replica's to store this won't work. Reason i am calling out to you to make you aware.

我理解的是一个SP ID  并不是一个组织

**Comment by Brady168** [comment]
@cryptowhizzard Can I guarantee that they'll be okay if they don't exceed 30% of the total?

**Comment by cryptowhizzard** [comment]
@Brady168  Thank you!

As Filplus-govteam stated: 4 IDs for f02301,f03223,f0240185,f0143858 Top Blocks California USA
These all belong to topblocks , thus they are one service provider and should not exceed 30%.

You stated in your LDN that you were going to store 7 replica's of this set.
100% / 7 = 14.xx % per service provider.

You have given 3 SP's in this case. I suggest you look for 4 extra to send the remaining replica's.
Please make sure you send each CID once to Topblocks. My question is, how are you going to do that? Please elaborate to build thrust and show that you know what you are doing ;-)

**Comment by Brady168** [comment]
> @Brady168 Thank you!
> 
> As Filplus-govteam stated: 4 IDs for f02301,f03223,f0240185,f0143858 Top Blocks California USA These all belong to topblocks , thus they are one service provider and should not exceed 30%.
> 
> You stated in your LDN that you were going to store 7 replica's of this set. 100% / 7 = 14.xx % per service provider.
> 
> You have given 3 SP's in this case. I suggest you look for 4 extra to send the remaining replica's. Please make sure you send each CID once to Topblocks. My question is, how are you going to do that? Please elaborate to build thrust and show that you know what you are doing ;-)

I'll look into it with my tech department on how to do it and reply later, but it will definitely go on according to the rules, so please monitor it, thank you!

**Comment by Brady168** [comment]
> You have given 3 SP's in this case. I suggest you look for 4 extra to send the remaining replica's. Please make sure you send each CID once to Topblocks. My question is, how are you going to do that? Please elaborate to build thrust and show that you know what you are doing ;-)

@cryptowhizzard  Hi,Ensuring that the same replica only sends one deal once in those 4 SP ID solves the problem，right?

**Comment by cryptowhizzard** [comment]
> > You have given 3 SP's in this case. I suggest you look for 4 extra to send the remaining replica's. Please make sure you send each CID once to Topblocks. My question is, how are you going to do that? Please elaborate to build thrust and show that you know what you are doing ;-)
> 
> @cryptowhizzard Hi,Ensuring that the same replica only sends one deal once in those 4 SP ID solves the problem，right?

Given that you have for example 4 deals in a dataset.

Deal A should go to provider 1  from Topblocks , not B / C / D , Replica 1
Deal B shoudl go to provider 2  from Topblocks, not A / C / D, Replica 1
Deal C should go to provider 3  from Topblocks, not A / B / D, Replica 1
Deal D should go to provider 4  from Topblocks, not A / B / C, Replica 1

Deal A / B / C / D should go to f02215422  ( Replica 2 )
Deal A / B / C / D  should go to f02062851 ( Replica 3 )

Deal A / B / C / D  should go to another SP ( i suggested ) ( Replica 4 ).

And so on.

**Comment by kevzak** [comment]
checker:manualTrigger

**Comment by kevzak** [comment]
@Brady168 need to provide 4 different SP entities and locations. Please provide an updated list

**Comment by Brady168** [comment]
> @Brady168 need to provide 4 different SP entities and locations. Please provide an updated list

I'm contacting more SPs and will post them later, thanks!

**Comment by Brady168** [comment]
> This application has not seen any responses in the last 10 days. This issue will be marked with Stale label and will be closed in 4 days. Comment if you want to keep this application open.
> 
> -- Commented by Stale Bot.

Please continue to be open, thank you

**Comment by Brady168** [comment]
Please continue to be open, thank you

**Comment by Brady168** [comment]
Please continue to be open, thank you

**Comment by Brady168** [comment]
> This application has not seen any responses in the last 10 days. This issue will be marked with Stale label and will be closed in 4 days. Comment if you want to keep this application open.
> 
> -- Commented by Stale Bot.

keep it open

**Comment by kevzak** [comment]
Closing until SPs provided
