### ISSUE TITLE
[DataCap Application]About The App

### ISSUE THREAD

**Issue by nnrecive** [filecoin-project/filecoin-plus-large-datasets#213]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name:  About The APP
- Website / Social Media: www.ata.company
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 1PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 20TiB
- On-chain address for first allocation: f3w37mbq6zs5ntivs35unaxzg67m27zkpawjsiohbtdcpb36cyerlggfhrcxfwsopoktkeseb7ucb5tlcmtitq

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
ATA(About The App) company has a Battleground game team, and plans to save game videos in the ipfs method and upload them to the video platform for use.
In addition, we are developing a game application and will convert game data into a safe blockchain method.
```

What is the primary source of funding for this project?
```
There are mainly bonds, credit, bank loans, etc
```

What other projects/ecosystem stakeholders is this project associated with?
```
Institutional investors, private investors and entertainment companies as well as the Filecoin network.
```

## Use-case details

Describe the data being stored onto Filecoin
```
Battleground game video and application storage data.
```

Where was the data in this dataset sourced from?
```
This is Battleground game video/application game data.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://youtu.be/XVvXuNTR6TU
It's a game video and I'm running a YouTube channel. I can't attach an address because my YouTube channel has been deleted due to an account setting error.
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes
```

What is the expected retrieval frequency for this data?
```
It depends on the situation, but it will allow people interested in Battleground to be exposed to the video platform when searching, and will be used as ipfs when loading game data when developing App games.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
When using Battleground and game applications, we will continue to save them, and we will also save other game app development data in the future.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Initially, it wants to be stored in Korea, but ultimately all over the world.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
It may depend on how quickly the service spreads, but initially we expect 10 TiB per week.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We are based on an online deal. As confirmed, 30GB files can be saved if there is no network problem
```

How will you be distributing deals across storage providers?
```
We are testing storage deals to various miners
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
We are testing with miners who will be aggressive with various clients and looking for more miners.
```

**Comment by galen-mcandrew** [comment]
Is this a resubmission of issue https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/161 ?

**Comment by galen-mcandrew** [comment]
Can you please clarify and provide sample data for this project

**Comment by nnrecive** [comment]
https://www.youtube.com/channel/UCnzHZg2Ee3c_Uf8LmT2LyRA
말씀드린 프로젝트의 샘플 영상입니다 youtube채널 문제로 링크제공이 늦어서 죄송합니다.
배틀그라운드 선수 게임영상, 대회영상을 지속적으로 업로드할 예정입니다
https://namu.wiki/w/ATA%20Esports?from=ATA%20LAVEGA ata의 선수단입니다

**Comment by dkkapur** [comment]
@nnrecive can you confirm this is the correct version of #161? If so, we can just move the LDN associated with that application to this one and proceed. Thank you.

**Comment by galen-mcandrew** [comment]
Any updates on this application?

**Comment by galen-mcandrew** [comment]
Closing this for now from no reply. When ready, please reopen or submit a new request here: https://plus.fil.org/ldn-application
