### ISSUE TITLE
[DataCap Application] <Beijing Black Horse Art Photography Company> 

### ISSUE THREAD

**Issue by songyongren** [filecoin-project/filecoin-plus-large-datasets#2137]
### Data Owner Name

Beijing Black Horse Art Photography Company

### What is your role related to the dataset

Data Preparer

### Data Owner Country/Region

China

### Data Owner Industry

Information, Media & Telecommunications

### Website

N/A

### Social Media

```text
telephones：13901362828
```

### Total amount of DataCap being requested

6PiB

### Expected size of single dataset (one copy)

980T

### Number of replicas to store

6

### Weekly allocation of DataCap requested

500TiB

### On-chain address for first allocation

f1jbua3b44ryfitdscioldx2l3u7ajp2r62vfnmqq

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Beijing Black Horse Art Photography Co., Ltd. was established on May 1st, 1993, with its registered address located at No. 19 West Third Ring Middle Road, Haidian District, Beijing. Its legal representative is Liu Zhicheng. The business scope includes art photography, photography training, and consulting; Home decoration; Sales of textiles, general merchandise, hardware, electrical appliances, chemicals, decorative materials, arts and crafts, computers, electronic components, mechanical equipment, electrical equipment, instruments, meters, and automotive accessories; Rental of cameras and cameras.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
Photography works, including cultural environments around the world, natural landscapes, shooting teaching videos, and shooting techniques videos
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### If you are a data preparer. What is your location (City and Country)

```text
Beijing, China
```

### If you are a data preparer, how will the data be prepared? Please include tooling used and technical details?

```text
no
```

### If you are not preparing the data, who will prepare the data?  (Provide name and business)

```text
Bugong，A technician specializing in filecoin
```

### Has this dataset been stored on the Filecoin network before? If so, please explain and make the case why you would like to store this dataset again to the network. Provide details on preparation and/or SP distribution.

```text
no
```

### Please share a sample of the data

```text
https://drive.google.com/drive/folders/1egQGuzJwvdOeZbUR6Kr0dOkX5ltLqTAz?usp=sharing
https://drive.google.com/drive/folders/1oAplKcq--PiZOCGn6rrJ_8NFlhkB4Bmx?usp=sharing
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Monthly

### For how long do you plan to keep this dataset stored on Filecoin

Permanently

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, Europe

### How will you be distributing your data to storage providers

HTTP or FTP server, Shipping hard drives

### How do you plan to choose storage providers

Partners

### If you already have a list of storage providers to work with, fill out their names and provider IDs below

```text
f01726489
f01756683
f01836766
f01660795
f02337006
f01128206
```

### How do you plan to make deals to your storage providers

Boost client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by MatrixStorage** [comment]
Hello, thank you for applying for LDN.  I have the following questions to confirm:
1.  Your data sources
2.  Do you have control over the business
3.  Whether you can disclose the source of your SPs selection

**Comment by songyongren** [comment]
> Hello, thank you for applying for LDN. I have the following questions to confirm:
> 
> 1. Your data sources

Works from daily photography and collected through the internet

> 2. Do you have control over the business

I have complete control over the data.
> 3. Whether you can disclose the source of your SPs selection

It's all through introductions between partners.

**Comment by Sunnyiscoming** [comment]
- Best practice for storing large datasets includes ideally, storing it in 3 or more regions, with 4 or more storage provider operators or owners.You should list Miner ID, Business Entity, Location of sps you will cooperate with.
- Could you send an email with business license to filplus-app-review@fil.org with your official domain in order to confirm your identity? Email name should includes the issue id #2137.

**Comment by songyongren** [comment]
> * Best practice for storing large datasets includes ideally, storing it in 3 or more regions, with 4 or more storage provider operators or owners.You should list Miner ID, Business Entity, Location of sps you will cooperate with.

Miner ID    |Business Entity|Location
f01726489 | Chenzx           |chengdu
f01756683 | laobai             |shenzhen
f01836766 | huang            |guangzhou
f01660795 | liuzong          |guangzhou
f02337006 | eager             |england
f01128206 |zhangx            |hunan
> * Could you send an email with business license to [filplus-app-review@fil.org](mailto:filplus-app-review@fil.org) with your official domain in order to confirm your identity? Email name should includes the issue id [[DataCap Application] <Beijing Black Horse Art Photography Company>  #2137](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/2137).

Sent

**Comment by Sunnyiscoming** [comment]
Hi @songyongren 
Per the https://github.com/filecoin-project/notary-governance/issues/922 for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

This information will be reviewed by Fil+ Governance team to confirm validity and then the application will be triggered for notary review. Let us know if you have any questions.

**Comment by songyongren** [comment]
> Hi @songyongren Per the [filecoin-project/notary-governance#922](https://github.com/filecoin-project/notary-governance/issues/922) for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.
> 
> This information will be reviewed by Fil+ Governance team to confirm validity and then the application will be triggered for notary review. Let us know if you have any questions.

The form has been submitted.

**Comment by Filplus-govteam** [comment]
The following SP entities were submitted:
SP ID   Entity   Location
f01128206  NA  hunan
f01726489  NA  chengdu
f01756683  NA  shenzhen
f01836766  NA  GuangZhou
f02337006  NA  england

f02337006 is being contacted to confirm location

**Comment by songyongren** [comment]
Just sent an email to f02337006 right？ the person in charge of f02337006 has confirmed it.

**Comment by Filplus-govteam** [comment]
Hello @songyongren your form does not include SP business emails or proof of SP entities. Please confirm

**Comment by songyongren** [comment]
> Just sent an email to f02337006 right？ the person in charge of f02337006 has confirmed it.

Is that the reason? Only one person received the authentication email

**Comment by Filplus-govteam** [comment]
Hello @songyongren we sent an email to the one SP not in China. And we received a utility bill for a supply company in London England. Thanks for confirming, let's see. 

The others there is no SP entity, no more information. Not enough to push this through yet I'm afraid. Good deal making starts with applicants working with trusted SP Entities that can prove who they are and where they are. Anyone can list a set of miner IDs. How do we know who you are, who they are, where they are?

**Comment by songyongren** [comment]
> Hello @songyongren we sent an email to the one SP not in China. And we received a utility bill for a supply company in London England. Thanks for confirming, let's see.
> 
> The others there is no SP entity, no more information. Not enough to push this through yet I'm afraid. Good deal making starts with applicants working with trusted SP Entities that can prove who they are and where they are. Anyone can list a set of miner IDs. How do we know who you are, who they are, where they are?

Entity means company or something, but SPs they all told me they are all individually owned, so does this entity have to be under a company?

**Comment by Filplus-govteam** [comment]
@songyongren - each being a separate businesses, yes.

**Comment by herrehesse** [comment]
Hello @songyongren welcome!

I've noticed this is your first LDN with no previous reputation, the ask for 6PiB is quite large. Can you explain to me why you asked for such a large amount?

Thank you!

**Comment by songyongren** [comment]
> Hello @songyongren welcome!
> 
> I've noticed this is your first LDN with no previous reputation, the ask for 6PiB is quite large. Can you explain to me why you asked for such a large amount?
> 
> Thank you!

Thank you for your reply. It was a coincidence that when our team went to the server room for maintenance, we were introduced to filplus, and we went to learn more about it and asked the technician about it, and then we followed his request for this application after we found it feasible.
All applications are currently based on actual storage and will continue when subsequent testing is okay.

**Comment by songyongren** [comment]
> @songyongren - each being a separate businesses, yes.

They explained to me that their miners are owned by individuals or teams and are not owned by a business or company，So there is no entity name as you say, just a contact name

**Comment by Filplus-govteam** [comment]
OK @songyongren FYI @Sunnyiscoming

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 6PiB

**Expected weekly DataCap usage rate**
> 500TiB

**Client address**
>f1jbua3b44ryfitdscioldx2l3u7ajp2r62vfnmqq

**Comment by MatrixStorage** [comment]
I am willing to support

**Comment by herrehesse** [comment]
@songyongren, could you please address my question?

@Filplus-govteam @Sunnyiscoming, I strongly recommend closing this LDN as the client seems to be evading your questions honestly.

All of these IDs have been used and linked to previous closed and disputed applications.

f01128206 NA hunan - Involved in abuse on 1929, 1411, with a known business name.
f01726489 NA chengdu - No abuse found.
f01756683 NA shenzhen - Fully self-dealing abuse on 1166, with a known business name.
f01836766 NA GuangZhou - Involved in abuse on 1918, 1411, 1989, with a known business name.
f02337006 NA england - Involved in abuse on 1918, with a known business name.

I'm quite surprised that this has passed the "checks" and triggered approval.

**Comment by songyongren** [comment]
> @songyongren, could you please address my question?
> 
> @Filplus-govteam @Sunnyiscoming, I strongly recommend closing this LDN as the client seems to be evading your questions honestly.
> 
> All of these IDs have been used and linked to previous closed and disputed applications.
> 
> f01128206 NA hunan - Involved in abuse on 1929, 1411, with a known business name. f01726489 NA chengdu - No abuse found. f01756683 NA shenzhen - Fully self-dealing abuse on 1166, with a known business name. f01836766 NA GuangZhou - Involved in abuse on 1918, 1411, 1989, with a known business name. f02337006 NA england - Involved in abuse on 1918, with a known business name.
> 
> I'm quite surprised that this has passed the "checks" and triggered approval.

Sorry for the misunderstanding I asked these SP's and they all said they are only responsible for storing the data and they don't know anything else, including the LDN thing
Since this has only just begun, and I don't really know what they're up to.If I find that they have violated the relevant LDN rules, I will terminate the cooperation immediately
Thank you for raising the question.

**Comment by herrehesse** [comment]
I won't accept shifting the blame onto the SPs, you are responsible for them. The primary intention seems to be acquiring datacap to store X and expand SP operations, not genuinely enhancing the value of the Filecoin ecosystem through the storage of meaningful, searchable, or important information.

As highlighted earlier, the miners you've listed have been involved in unethical activities and self-dealing multiple times. Their involvement is non-negotiable.

If you genuinely aim to store data on Filecoin, especially as a new account with no established reputation, then start with a modest 10TiB and a transparent list of minerID's from diverse global regions. I'm willing to endorse under the right circumstances, but not in its current form.

**Comment by songyongren** [comment]
> I am willing to support

@MatrixStorage Thanks！

**Comment by songyongren** [comment]
> I won't accept shifting the blame onto the SPs, you are responsible for them. The primary intention seems to be acquiring datacap to store X and expand SP operations, not genuinely enhancing the value of the Filecoin ecosystem through the storage of meaningful, searchable, or important information.
> 
> As highlighted earlier, the miners you've listed have been involved in unethical activities and self-dealing multiple times. Their involvement is non-negotiable.
> 
> If you genuinely aim to store data on Filecoin, especially as a new account with no established reputation, then start with a modest 10TiB and a transparent list of minerID's from diverse global regions. I'm willing to endorse under the right circumstances, but not in its current form.

I'll look into this one, I'm always on the lookout for new SP's as well, thanks for the review!

**Comment by songyongren** [comment]
Preparations are being made.

**Comment by songyongren** [comment]
Preparations are being made.

**Comment by songyongren** [comment]
Preparations are being made.

**Comment by songyongren** [comment]
Preparations are being made.

**Comment by songyongren** [comment]
Preparations are being made.

**Comment by kevzak** [comment]
Closing until clear Sp list provided
