### ISSUE TITLE
[DataCap Application]China Thinkers Bureau

### ISSUE THREAD

**Issue by WinterMelonT** [filecoin-project/filecoin-plus-large-datasets#214]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name:China Thinkers Bureau
- Website / Social Media:website in English： www.chinathinkersbureau.com website in English： www.chinathinkersbureau.com twitter： @China Thinkers Bureau
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):100TiB
- On-chain address for first allocation:f1ediptgl2bplqavzl6qmixe2vssxh5xxpt3qhqvi

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
China Thinkers Bureau was founded by former nation-leading media and state council think-tank veterans. A global expert resource management organization, invested by famous economist Wu Xiaobo, rooted in the Chinese market, and linked to the world's top expert resources. China Thinkers Bureau is the ONLY world-class thinker agency in China representing the world’s greatest minds for various commercial milieu in China. Team graduates from Harvard, Warwick, PKU and all elites schools.
We are providing exclusive access to China’s growing market for ideas, benefiting speakers and China alike. We brand and bring to China world’s eminent thinkers. 
```

What is the primary source of funding for this project?
```
Mainly from business income in multiple business lines of the project.
```

What other projects/ecosystem stakeholders is this project associated with?
```
Our clients including top leading companies in the fields of new infrastructure, economic finance and blockchain and other fields. 
```

## Use-case details

Describe the data being stored onto Filecoin
```
The data stored on Filecoin is basically conference data, such as conference speech videos, photo albums, and third-party communication that our service has completed and other publicly available data
```

Where was the data in this dataset sourced from?
```
Application data mainly from conferences serving various customers, including high-definition video of expert speeches, etc.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://wx.vzan.com/live/page/11EE9454D4ACAB635C965E7FF1A573A6?topicid=1133306937&shauid=OfObiUdOgH8opP_WLsdVoQ**&v=637780287400026346
https://live.aiyaopai.com/live/53291331
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
We confirm this is public data that can be retrieved by anyone on the web
```

What is the expected retrieval frequency for this data?
```
There is no fixed retrieval frequency for data retrieval, it depends on the needs
```

For how long do you plan to keep this dataset stored on Filecoin?
```
It depends on the needs of the conference project.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
USA, Singapore, HK
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
We prefer transfer online, but if there are special circumstances, we can also accept offline.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We have some miners in negotiation, and our principle is to find miners have good performance in the past, so that they can provide stable storage.
```

How will you be distributing deals across storage providers?
```
We may distribute as evenly as possible.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, we have enough resources.
```

**Comment by IPFSUnion** [comment]
Could you tell me how to download your data in public channel?  please share the link of your datasets.

**Comment by WinterMelonT** [comment]
Our current data is mainly stored within the company, and we have not built a platform for external direct download. If you need relevant data samples, I can provide them to you.

**Comment by IPFSUnion** [comment]
Thank you for your reply. According to your description, your dataset should be private and conditionally accessible, which may not meet the requirements of LDN.

**Comment by WinterMelonT** [comment]
Our data is free for pubilc, but it has not been put on a public platform. So filecoin is needed for us now.

**Comment by swatchliu** [comment]
Seems more materials need to be provided if your platform is ready.@WinterMelonT

**Comment by Sunnyiscoming** [comment]
Hi, @WinterMelonT Hope you can provide more data samples and show the relationship of the subject to the data. If there is a data platform, you can publish the link to us.

**Comment by Sunnyiscoming** [comment]
Hello, @WinterMelonT
Is this application valid?

**Comment by galen-mcandrew** [comment]
Closing this for now from no reply. When ready, please reopen or submit a new request here: https://plus.fil.org/ldn-application
