### ISSUE TITLE
[DataCap Application] <Li Zhu> - <Li Zhu>

### ISSUE THREAD

**Issue by Tom88881025** [filecoin-project/filecoin-plus-large-datasets#2142]
### Data Owner Name

Li Zhu Pharmaceutical Group Co.

### What is your role related to the dataset

Data Preparer

### Data Owner Country/Region

China

### Data Owner Industry

Life Science / Healthcare

### Website

https://www.livzon.com.cn/intro/2.html

### Social Media

```text
https://www.livzon.com.cn/intro/2.html
```

### Total amount of DataCap being requested

5PiB

### Expected size of single dataset (one copy)

580TiB

### Number of replicas to store

5

### Weekly allocation of DataCap requested

1PiB

### On-chain address for first allocation

f1hvpd2ppu3b2pkiohkrnvzzbpsgmiyeeyzxwsd2a

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Founded in January 1985, with a registered capital of 935 million yuan, Lizhu Pharmaceutical Group Co., Ltd. is a comprehensive pharmaceutical group company integrating pharmaceutical research and development, production and sales, with more than 8,000 employees, and a listed company on A+H shares.In FY2022, the company's operating revenue was 12.63 billion yuan, with a net profit of 1.909 billion yuan, and an investment of 1.401 billion yuan in research and development.
 
Lizhu has been making breakthroughs in the fields of APIs, chemical drugs, traditional Chinese medicines, biological drugs, in vitro diagnostic reagents, etc. Its products are distributed in the fields of digestion, cardiovascular and cerebral vascular, reproductive endocrine, and psychiatric/neurological. The company continues to focus on the main business of innovative drugs and high-barrier complex formulations, launching heavyweight products such as leucovorin and eplazole, and realizing volume growth in the fields of digestion and reproduction.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
Medical experiment data, medical education data
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### Please share a sample of the data

```text
https://www.livzon.com.cn/intro/2.html
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Sporadic

### For how long do you plan to keep this dataset stored on Filecoin

2 to 3 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, Europe, Australia (continent)

### How will you be distributing your data to storage providers

HTTP or FTP server, Shipping hard drives

### How do you plan to choose storage providers

Slack, Partners

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Tom88881025** [comment]
> 


1. yes, SPs are ready fil.
2. I am mainly responsible for the data preparation, via boost or lotus, the data is stored for the first time on the filecoin network.
3. SPs information is detailed in the filled form.

**Comment by Sunnyiscoming** [comment]
Please list Miner ID, Business Entity, Location of sps you will cooperate with. It will help notaries know more about your application and approve you.

**Comment by Tom88881025** [comment]
> 请列出您将合作的矿工 ID、商业实体、sps 位置。它将帮助公证人更多地了解您的申请并批准您。

The following SPs have been communicated so far and more will be contacted.

1. f02289399  Bailey  Hong Kong
2. f01986262 SXX Hubei
3. f01964215 SXX Guangzhou
4. f039940 NiwanDao China
5. f0694916 Guazi Dynamics Asia

**Comment by cryptowhizzard** [comment]
lotus net connect f02289399, ERROR: no PeerID for miner, not eligible to participate in FIL+

lotus net connect f0694916, ERROR: no PeerID for miner, not eligible to participate in FIL+

f039940 , not serving retrievals according to the retrieval bot and my own stats. -> not eligible to participate in FIL+

**Comment by kernelogic** [comment]
Where is the data sample? The link you provided is a web page.

**Comment by Tom88881025** [comment]
> 数据样本在哪里？您提供的链接是一个网页。

https://share.weiyun.com/xiMATHuX
Thank you for your interest, please check the link for data examples!

**Comment by Aaron01230** [comment]
I downloaded some sample data, and after decompression, the bat file is displayed, can you explain what kind of data this is?

**Comment by Tom88881025** [comment]
> 我下载了一些样本数据，解压后显示了bat文件，你能解释一下这是什么数据吗？

Thank you for your interest, the data are mainly from the EMBL-Nucleic Acid Database, the EMBL Nucleic Acid Sequence Database is maintained by the European Bioinformatics Center EBI. Nucleic acid sequence data are obtained from genome sequencing centers, individual submissions, and exchanges with DDBJ (Japan) and GenBank (NCBI).

**Comment by Aaron01230** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaugsl4opxgrny5ytqb6lhb7raj55ghdha3iplnm5zivcgei6rxxa 
#### Address 
> f1hvpd2ppu3b2pkiohkrnvzzbpsgmiyeeyzxwsd2a
#### Datacap Allocated
> 256.00TiB
#### Signer Address
> f1xrnysd4gimg64d4l6qi7ulzwwq22c6vfg6lpw3i
#### Id
> 26a939e7-ff58-4cd7-8fba-9de46f181a70
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaugsl4opxgrny5ytqb6lhb7raj55ghdha3iplnm5zivcgei6rxxa

**Comment by kernelogic** [comment]
Given the data sample, willing to support. SP retrievability can be verified after onboarding.

**Comment by kernelogic** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceat4edmyueik2xi6ifdhbabsbceils57il2u5kypgzg64ybxdogaq 
#### Address 
> f1hvpd2ppu3b2pkiohkrnvzzbpsgmiyeeyzxwsd2a
#### Datacap Allocated
> 256.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### Id
> 26a939e7-ff58-4cd7-8fba-9de46f181a70
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceat4edmyueik2xi6ifdhbabsbceils57il2u5kypgzg64ybxdogaq

**Comment by kevzak** [comment]
@Tom88881025 please provide list of SP partner entities and locations here, I see a lot of back and forth above. Let's have a clean list

**Comment by Tom88881025** [comment]
checker:manualTrigger

**Comment by Tom88881025** [comment]
checker:manualTrigger

**Comment by Tom88881025** [comment]
We are working with these SPs and we are reaching out to more SPs in the meantime.

f02195555 SXX Future
f02383642 Derek
f02191111 ChenXing Tec
f01964215 SXX Future
f02368751 Alex Li

**Comment by cryptowhizzard** [comment]
According to the retrieval bot the miners of SXX do not support retrieval. This is against Fil+ rules and guidelines.

The other 3 miners are OK, however the names do not match the names of the owner I have here. Why?

**Comment by Tom88881025** [comment]
<img width="531" alt="image" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/116630682/dc19b1d6-7e0b-4a8d-8fe3-422d936ebbe3">

Asked SXX, f02195555 manual retrieval is successful, but the delay is too high, so retrieval bot can't recognize it. f01964215 is currently being sealing, need to wait for two days to retrieve it.

**Comment by Tom88881025** [comment]
checker:manualTrigger

**Comment by 1ane-1** [comment]
The report looks more healthy than before. Support for the present round.

**Comment by 1ane-1** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacea3u4t5paui2itxwrs4qakijyork7ceoj6nwv2gch75u45dsqytgy 
#### Address 
> f1hvpd2ppu3b2pkiohkrnvzzbpsgmiyeeyzxwsd2a
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f1mdk7s2vntzm6hu35yuo6vjubtrpfnb2awhgvrri
#### Id
> 38b499df-8d48-4c2e-a03f-769ae3ad086a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacea3u4t5paui2itxwrs4qakijyork7ceoj6nwv2gch75u45dsqytgy

**Comment by mikezli** [comment]
checker:manualTrigger

**Comment by mikezli** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceba2mbkfbyx3rhvytnakwokcciwbdeexnl2rasp2pwtvjzf5chcla 
#### Address 
> f1hvpd2ppu3b2pkiohkrnvzzbpsgmiyeeyzxwsd2a
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f1dnb3uz7sylxk6emti3ififcvu3nlufnnsjui6ea
#### Id
> 38b499df-8d48-4c2e-a03f-769ae3ad086a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceba2mbkfbyx3rhvytnakwokcciwbdeexnl2rasp2pwtvjzf5chcla

**Comment by cryptowhizzard** [comment]
Data checked, downloaded and verified.

http://www.datasetcreators.com/downloadedcarfiles/2142-f02521732-f02383642-54559813-baga6ea4seaqo7oqdi3zwnf4prxs2krerocmagj52usnnrz42bjw7nzapzjphcmi

**Comment by Tom88881025** [comment]
checker:manualTrigger

**Comment by woshidama323** [comment]
LGTM and Looks healthy at the moment ,Will support this

**Comment by woshidama323** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceacmhiufhsotx4dzxjjzxrvothpngjr4vqkvps76hue3h5r6nykb4 
#### Address 
> f1hvpd2ppu3b2pkiohkrnvzzbpsgmiyeeyzxwsd2a
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f12tk3adljauwnd3hjbigpfxb7b7gdlj63p6afwtq
#### Id
> 38b499df-8d48-4c2e-a03f-769ae3ad086a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceacmhiufhsotx4dzxjjzxrvothpngjr4vqkvps76hue3h5r6nykb4

**Comment by OpenGate01** [comment]
Willing to support this round.

**Comment by OpenGate01** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedpdnp3pgsfne5kzzk74ri2px42bldo5bpvdjvcsrj6ullkbhsmbk 
#### Address 
> f1hvpd2ppu3b2pkiohkrnvzzbpsgmiyeeyzxwsd2a
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f1im4hmtbfzqnx7ir74kdaiu4ynjhgqh3sdi2snla
#### Id
> 38b499df-8d48-4c2e-a03f-769ae3ad086a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedpdnp3pgsfne5kzzk74ri2px42bldo5bpvdjvcsrj6ullkbhsmbk

**Comment by Bitengine-reeta** [comment]
checker:manualTrigger

**Comment by Bitengine-reeta** [comment]
The node distribution and data backup situation shown in the report are good, but the retrieval needs to be further optimized.
Will support .

**Comment by Bitengine-reeta** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceacu255hdczzdnd5sghrhcglaehiol4ipezdap3yjaxf23k2nvdvk 
#### Address 
> f1hvpd2ppu3b2pkiohkrnvzzbpsgmiyeeyzxwsd2a
#### Datacap Allocated
> 2.00PiB
#### Signer Address
> f1jyvhxp4kmwreo22ke4itspraznpudw3uqaink5i
#### Id
> 7da9db31-aab8-4824-9726-9accffcecf27
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceacu255hdczzdnd5sghrhcglaehiol4ipezdap3yjaxf23k2nvdvk

**Comment by NDLABS-Leo** [comment]
willing to support

**Comment by zcfil** [comment]
checker:manualTrigger

**Comment by NDLABS-Leo** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceawdl37zv6d7sidihrq3iehzkpyxqzzsfvkrifncadlgplxywiiji 
#### Address 
> f1hvpd2ppu3b2pkiohkrnvzzbpsgmiyeeyzxwsd2a
#### Datacap Allocated
> 2.00PiB
#### Signer Address
> f1yayfsv6whu3rheviucvventj3y6t542xfpb47ei
#### Id
> 7da9db31-aab8-4824-9726-9accffcecf27
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceawdl37zv6d7sidihrq3iehzkpyxqzzsfvkrifncadlgplxywiiji

**Comment by Tom88881025** [comment]
checker:manualTrigger

**Comment by luobin544** [comment]
checker:manualTrigger

**Comment by luobin544** [comment]
checker:manualTrigger

**Comment by luobin544** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedn7vvfyynbku2pn4iwl6y6ht4hdek2ehmrnj4zrrmhwd4qdrvhre 
#### Address 
> f1hvpd2ppu3b2pkiohkrnvzzbpsgmiyeeyzxwsd2a
#### Datacap Allocated
> 1.75PiB
#### Signer Address
> f1tbd632f6w62glfaf7wjpimacbnjiz26poyoes2q
#### Id
> 8d6dea71-5c59-4ca5-a7d7-10f26ca3bf2f
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedn7vvfyynbku2pn4iwl6y6ht4hdek2ehmrnj4zrrmhwd4qdrvhre

**Comment by Bitrise0111** [comment]
We've check the report and are willing to give support.

**Comment by Bitrise0111** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced4wv5cssr5b4zocgodtzjmsyknko4slortyw7iru6c6gwe4kch2s 
#### Address 
> f1hvpd2ppu3b2pkiohkrnvzzbpsgmiyeeyzxwsd2a
#### Datacap Allocated
> 1.75PiB
#### Signer Address
> f1nknj7ayq4o43czrtdoauggtwl43fbqatmqis3yy
#### Id
> 8d6dea71-5c59-4ca5-a7d7-10f26ca3bf2f
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced4wv5cssr5b4zocgodtzjmsyknko4slortyw7iru6c6gwe4kch2s

**Comment by herrehesse** [comment]
checker:manualTrigger

**Comment by herrehesse** [comment]
VPN & self-dealing. Abusive notaries signing. I hope you guys are happy with yourselves. REPORTED.
<img width="749" alt="Screenshot 2023-10-23 at 22 03 13" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/70132857/137617c9-af0c-4677-af3f-33096a8434d0">

**Comment by Tom88881025** [comment]
checker:manualTrigger

**Comment by kevzak** [comment]
SPs from reg form
f02289399 Bailey Hong Kong
f01986262 SXX Hubei
f01964215 SXX Guangzhou
f039940 NiwanDao China
f0694916 Guazi Dynamics Asia

SPs taking deals

f02005421 | Seoul, Seoul, KRAmazon.com, Inc. | 187.50 TiB | 8.18% | 187.50 TiB | 0.00%
f02002141 | Seoul, Seoul, KRAmazon.com, Inc. | 187.47 TiB | 8.17% | 187.47 TiB | 0.00%
f02195555 | Shanghai, Shanghai, CNChina Mobile Communications Group Co., Ltd. | 61.78 TiB | 2.69% | 61.78 TiB | 0.00%
f01964215 | Shenzhen, Guangdong, CNCHINANET-BACKBONE | 62.44 TiB | 2.72% | 62.44 TiB | 0.00%
f02229545 | Los Angeles, California, USCNSERVERS LLC | 187.50 TiB | 8.18% | 187.50 TiB | 0.00%
f02191111 | Los Angeles, California, USCogent Communications | 12.81 TiB | 0.56% | 12.81 TiB | 0.00%
f02363305 | Shenzhen, Guangdong, CNCTGNet | 123.81 TiB | 5.40% | 123.78 TiB | 0.03%
f02368751 | Dallas, Texas, USFlexential Colorado Corp. | 60.94 TiB | 2.66% | 60.94 TiB | 0.00%
f02383642 | Dallas, Texas, USFlexential Colorado Corp. | 46.88 TiB | 2.04% | 46.88 TiB | 0.00%
f02812314 | Los Angeles, California, USIPTELECOM Global | 312.47 TiB | 13.62% | 312.47 TiB | 0.00%
f02812307 | Singapore, Singapore, SGIPTELECOM Global | 312.47 TiB | 13.62% | 312.47 TiB | 0.00%
f02809368 | Tokyo, Tokyo, JPIPTELECOM Global | 312.16 TiB | 13.61% | 312.16 TiB | 0.00%
f02809382 | Singapore, Singapore, SGIPTELECOM Global | 125.00 TiB | 5.45% | 125.00 TiB | 0.00%
f02809374 | Tokyo, Tokyo, JPIPTELECOM Global | 124.94 TiB | 5.45% | 124.94 TiB | 0.00%
f02230309 | Putra Heights, Selangor, MYTechAvenue Malaysia | 175.41 TiB | 7.65% | 175.41 TiB | 0.00%

@Tom88881025 1 SP matches from original list. Closing for not disclosing all SP entities upfront
