### ISSUE TITLE
[DataCap Application] <Handian supercomputing> - <AI Steward 1.0>

### ISSUE THREAD

**Issue by oldamboo** [filecoin-project/filecoin-plus-large-datasets#2143]
### Data Owner Name

Handian supercomputing data Intelligent Technology

### What is your role related to the dataset

Dataset Owner

### Data Owner Country/Region

China

### Data Owner Industry

IT & Technology Services

### Website

http://www.inscdt.com/

### Social Media

```text
Our digitalization integrates the commodity data of several Fortune 500 supply chain platforms, inherits the big data models of ChatGPT, Baidu ERNIE Bot and Huawei Pangu, and has incubated several mall terminals. Each mall terminal is embedded in our big data engine to provide customers with business data analysis, user behavior analysis, intelligent customer service, mapping, and AI generation audio and video functions, In the future, we will provide industry customized AI intelligent services to enrich the flow of terminal tools in the mall, allowing users to focus more on marketing itself. Our incubated mall access link:
http://sc000112-rich.faikeeper.com
http://sc000110-rich.shuyiim.cn
```

### Total amount of DataCap being requested

More Than 15PiB

### Expected size of single dataset (one copy)

15PB

### Number of replicas to store

10

### Weekly allocation of DataCap requested

1PiB

### On-chain address for first allocation

f1mho5wc23poqa3ajorei2wdlx4pqrauw6ioexf3y

### Data Type of Application

Private Commercial/Enterprise

### Custom multisig

- [X] Use Custom Multisig

### Share a brief history of your project and organization

```text
Shenzhen Handian Supercomputing Data Co., Ltd. is a comprehensive technology service provider dedicated to distributed storage and computing. It is a computing asset management company based on distributed storage and blockchain technology, big data, edge computing and artificial intelligence as the industry background, and distributed computing services as the product form. The company provides global users with digital technology services such as distributed storage, edge computing, data authentication and certification.
```

### Is this project associated with other projects/ecosystem stakeholders?

Yes

### If answered yes, what are the other projects/ecosystem stakeholders

```text
We will be Subsequent disclosure
```

### Describe the data being stored onto Filecoin

```text
Generative AI text dataset, image dataset, audio and video dataset, product images, order data, logistics information, and other supply chain industry data。
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### If you are a data preparer. What is your location (City and Country)

```text
I am in Shenzhen, China。
```

### If you are a data preparer, how will the data be prepared? Please include tooling used and technical details?

```text
singularity

#Building singularity
https://github.com/tech-greedy/singularity

#View the current list
Singularity pre list

#Generate car
Singularity pre create - t/mnt/md0/awscar 2032 Data source address generation car file address

#Monitoring situation
Singularity monitor

#Issue an order
Singularity repl start - l/mnt/disks/192.168.50.161/raidd1/DATA_ 2032/test 649eb491 * * 17dbd192d * * miner f1lmrsadfasdftkw7hbk2tvkjbezasdfrwopa (quota address)
```

### Has this dataset been stored on the Filecoin network before? If so, please explain and make the case why you would like to store this dataset again to the network. Provide details on preparation and/or SP distribution.

```text
The data is not yet in Filecoin。
```

### Please share a sample of the data

```text
part of open datasets：

First level directory：
http://220.168.154.102:18080/images/

Second level directory：
output_matrix_part1  output_matrix_part2  output_matrix_part3  output_matrix_part4

some output_matrix_part3 files：
http://220.168.154.102:18080/images/output_matrix_part3/upscale_img_000cVA_.png.npy

We have approximately 692564 such data samples
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Sporadic

### For how long do you plan to keep this dataset stored on Filecoin

Permanently

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, South America, Australia (continent)

### How will you be distributing your data to storage providers

HTTP or FTP server, Shipping hard drives

### How do you plan to choose storage providers

Partners

### If you already have a list of storage providers to work with, fill out their names and provider IDs below

```text
f02129771（owner）
f01172521 
f01843178
f01877259
f02192588
```

### How do you plan to make deals to your storage providers

Lotus client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Filplus-govteam** [comment]
@oldamboo hello please complete steps for E-Fil+ private data onboarding as listed here: https://efilplus.super.site/

**Comment by oldamboo** [comment]
> @oldamboo hello please complete steps for E-Fil+ private data onboarding as listed here: https://efilplus.super.site/

OK，I've submitted it and worked hard to verify our information，TKS。

**Comment by herrehesse** [comment]
@oldamboo Hello friend, thank you for your LDN.

Your requested amount of DC is very large, do you have any previous reputation build up inside this ecosystem? Would love to learn your previous work.

Thank you.

**Comment by oldamboo** [comment]
@herrehesse Good morning！The above are our contributions to the community.
We started connecting to the Filecoin network through testing in 2019 and contributed approximately 130PB of storage capacity to the network in 2020. In 2019, the company team conducted multiple bug submissions and CC encapsulation optimizations. We started establishing a new company in 2021 to provide technical services and operations, and currently participate in and maintain a storage scale of nearly 80PB in Greater China. On June 27, 2023, we participated in DSPA's Asian Incubation Center Training Camp and became an ecological partner. Currently, our DC data download technology solution in Greater China ranks among the top and has been favored by DC Data. At the same time, I am the technical ambassador of the FilFi community and have proposed an operational solution for distributed storage global urban stations. Currently, the FilFi community is implementing it in Greater China with significant results.

The above is the general content, please be informed.

**Comment by kevzak** [comment]
@oldamboo please confirm if you have completed KYC check and KYB check. I do not see yet. Instructions can be found here https://efilplus.super.site/

**Comment by oldamboo** [comment]
@herrehesse OK，we have submit the KYC and KYB check，and it‘s create a new issue here：
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/2172
