### ISSUE TITLE
[DataCap Application] Solana Labs - Solana Ledger

### ISSUE THREAD

**Issue by yihau** [filecoin-project/filecoin-plus-large-datasets#2145]
### Data Owner Name

Solana Labs

### What is your role related to the dataset

Dataset Owner

### Data Owner Country/Region

United States

### Data Owner Industry

Web3 / Crypto

### Website

https://solana.com

### Social Media

```text
https://twitter.com/solanalabs
```

### Total amount of DataCap being requested

5PiB

### Expected size of single dataset (one copy)

~ 2TiB. (may become bigger in the future)

### Number of replicas to store

3

### Weekly allocation of DataCap requested

50TiB

### On-chain address for first allocation

f3xgawho4wlo2okfyj63m27qh34l7ovlxyqslsiskm437d2rqudqethzvemqpzoemfvf7sjix3gdughfb5tk3q

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Solana is a blockchain built for mass adoption. It's a high performance network that is utilized for a range of use cases, including finance, NFTs, payments, and gaming. Solana operates as a single global state machine, and is open, interoperable and decentralized.
```

### Is this project associated with other projects/ecosystem stakeholders?

Yes

### Describe the data being stored onto Filecoin

```text
The ledger of the Solana blockchain.
```

### Where was the data currently stored in this dataset sourced from

Google Cloud

### If you are a data preparer, how will the data be prepared? Please include tooling used and technical details?

```text
1) download our ledger data from the GCP cloud storage bucket
2) use https://github.com/anjor/go-fil-dataprep to generate car files
3) upload all car files to another GCP cloud storage bucket
4) using boost client to send deals
```

### Has this dataset been stored on the Filecoin network before? If so, please explain and make the case why you would like to store this dataset again to the network. Provide details on preparation and/or SP distribution.

```text
Yes, we would like to control the flow on our end. In our previous cooperation, we only provided raw data, which may have increased our communication costs.
```

### Please share a sample of the data

```text
https://console.cloud.google.com/storage/browser/chido/epoch-2
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Daily

### For how long do you plan to keep this dataset stored on Filecoin

Permanently

### In which geographies do you plan on making storage deals

global

### How will you be distributing your data to storage providers

Cloud storage (i.e. S3), HTTP or FTP server

### How do you plan to choose storage providers

We will be working with the network growth team at PL to identify storage providers that will serve retrievals.

### How do you plan to make deals to your storage providers

Boost client, Singularity

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
- Have you prepared enough token for sector pledge?
- Best practice for storing large datasets includes ideally, storing it in 3 or more regions, with 4 or more storage provider operators or owners.You should list Miner ID, Business Entity, Location of sps you will cooperate with.
- Could you send an email to filplus-app-review@fil.org with your official domain in order to confirm your identity? Email name should includes the issue id #2145.
- Per the https://github.com/filecoin-project/notary-governance/issues/922 for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

This information will be reviewed by Fil+ Governance team to confirm validity and then the application will be triggered for notary review. Let us know if you have any questions.

**Comment by anjor** [comment]
To clarify: this is a potential future tenant for spade once the tenant onboarding service for spade is ready (it's currently being developed).

In the meantime, @yihau will be working with Yan Bo, a solutions architect at the filecoin foundation, and me, an engineer at protocol labs to set up the onboarding pipeline. This involves figuring out the correct technical solution, identifying SPs, and facilitating the interaction between the client (Solana labs) and the SPs to make sure the data is retrievable to the client's satisfaction.

**Comment by kevzak** [comment]
## Datacap Request Trigger
#### Total DataCap requested 
> 5PiB
#### Expected weekly DataCap usage rate 
> 50TiB
#### Client address
> f3xgawho4wlo2okfyj63m27qh34l7ovlxyqslsiskm437d2rqudqethzvemqpzoemfvf7sjix3gdughfb5tk3q

**Comment by kernelogic** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacede3w5fvhf7mlmv3buxnv3jochncfms2moownstaasmmpdfvqtblo 
#### Address 
> f3xgawho4wlo2okfyj63m27qh34l7ovlxyqslsiskm437d2rqudqethzvemqpzoemfvf7sjix3gdughfb5tk3q
#### Datacap Allocated
> 25.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### Id
> d229c745-9004-4784-a086-a3b40418e3d2
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacede3w5fvhf7mlmv3buxnv3jochncfms2moownstaasmmpdfvqtblo

**Comment by kernelogic** [comment]
Looks legit from KYC perspective.

**Comment by Bennyyangpu** [comment]
> To clarify: this is a potential future tenant for spade once the tenant onboarding service for spade is ready (it's currently being developed).
> 
> In the meantime, @yihau will be working with Yan Bo, a solutions architect at the filecoin foundation, and me, an engineer at protocol labs to set up the onboarding pipeline. This involves figuring out the correct technical solution, identifying SPs, and facilitating the interaction between the client (Solana labs) and the SPs to make sure the data is retrievable to the client's satisfaction.

willing to support!

**Comment by anjor** [comment]
Keep open

**Comment by yihau** [comment]
keep open!

**Comment by spaceT9** [comment]
checker:manualTrigger

**Comment by junyaoren** [comment]
checker:manualTrigger

**Comment by spaceT9** [comment]
checker:manualTrigger

**Comment by junyaoren** [comment]
checker:manualTrigger

**Comment by cryptowhizzard** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebxriac4bfbd5hzdd2li7mhtgy4pf4nejkak4f6ul6nit4fjwpcia 
#### Address 
> f3xgawho4wlo2okfyj63m27qh34l7ovlxyqslsiskm437d2rqudqethzvemqpzoemfvf7sjix3gdughfb5tk3q
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1krmypm4uoxxf3g7okrwtrahlmpcph3y7rbqqgfa
#### Id
> 40a61c16-6a96-417d-8932-0ca1db5127d3
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebxriac4bfbd5hzdd2li7mhtgy4pf4nejkak4f6ul6nit4fjwpcia

**Comment by junyaoren** [comment]
checker:manualTrigger

**Comment by junyaoren** [comment]
I'm wondering why the bot fails to work on this application. @raghavrmadya @Kevin-FF-USA  
@cryptowhizzard Have you done related DD on this, and if so, would you mind share it? Thanks

**Comment by anjor** [comment]
My guess would be it's because no data has been onboarded yet.

Is that right @yihau ?

**Comment by yihau** [comment]
yes, we haven't started to onboard any data. I will consume some of them late this week for testing

**Comment by junyaoren** [comment]
It's strange to me. If no DC is consumed yet, how the second round of allocation is triggered?

**Comment by anjor** [comment]
That is a good question. @simonkim0515 @panges2

**Comment by yihau** [comment]
keep open 🙏

**Comment by yihau** [comment]
@anjor could you reopen this one 🙏

**Comment by anjor** [comment]
@simonkim0515 can you help?

**Comment by yihau** [comment]
🙏

**Comment by Sunnyiscoming** [comment]
Please provide ID, City, Country, Organization of each SP here.

**Comment by yihau** [comment]
🙏

**Comment by Sunnyiscoming** [comment]
@yihau Hi, please provide ID, City, Country, Organization of each SP here.

**Comment by yihau** [comment]
🙏

**Comment by yihau** [comment]
🙏

**Comment by Ng-YanBo** [comment]
@Sunnyiscoming @Kevin-FF-USA @simonkim0515 Hey Folks, Yan from Filecoin Foundation here. Since they have regional requirements, Solana will have to wait for one last SP in America to free up the space for Solana as the last replica. Can I check if the LDN will have an issue when the new FIL + program is in place as well. Estimated time for this is 2-3weeks

**Comment by yihau** [comment]
🙏

**Comment by yihau** [comment]
🙏

**Comment by yihau** [comment]
🙏
