### ISSUE TITLE
[DataCap Application] NCAR CESM2 ARISE

### ISSUE THREAD

**Issue by Jaida0** [filecoin-project/filecoin-plus-large-datasets#2147]
### Data Owner Name

NCAR

### What is your role related to the dataset

Data Preparer

### Data Owner Country/Region

United States

### Data Owner Industry

Environment

### Website

https://ncar.ucar.edu/

### Social Media

```text
https://www.facebook.com/NCAR.UCAR/
https://www.youtube.com/ncarucar
https://www.instagram.com/ncar_ucar/
```

### Total amount of DataCap being requested

6PiB

### Expected size of single dataset (one copy)

597.2TiB

### Number of replicas to store

10

### Weekly allocation of DataCap requested

800TiB

### On-chain address for first allocation

f16grdbr73dccc66dxhtrr2shqoarpupowpteo2yi

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
NCAR was established by the National Science Foundation in 1960 to provide the university community with world-class facilities and services that were beyond the reach of any individual institution. NCAR provides the atmospheric and related Earth system science community with state-of-the-art resources, including supercomputers, research aircraft, sophisticated computer models, and extensive data sets.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
Project data files from ARISE-SAI Experiments with CESM2
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### If you are a data preparer. What is your location (City and Country)

```text
Sichuan, China
```

### If you are a data preparer, how will the data be prepared? Please include tooling used and technical details?

```text
We use lotus to prepare data.
```

### Has this dataset been stored on the Filecoin network before? If so, please explain and make the case why you would like to store this dataset again to the network. Provide details on preparation and/or SP distribution.

```text
I don't know.
I will strictly follow that each sp will be sent exceed 30% of the total datacap.
```

### Please share a sample of the data

```text
s3://ncar-cesm2-arise/
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

1.5 to 2 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America

### How will you be distributing your data to storage providers

HTTP or FTP server, Shipping hard drives, Lotus built-in data transfer

### How do you plan to choose storage providers

Slack, Big Data Exchange, Partners

### If you already have a list of storage providers to work with, fill out their names and provider IDs below

```text
f01211025 HK
f01086553 CN
f01125783 HK
f01347695 KR
f0131464 US
```

### How do you plan to make deals to your storage providers

Boost client, Lotus client, Singularity

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
- Please introduce your organization and project.
- Have you prepared enough token for sector pledge?
- It has been stored before. Why are you choosing to store it again?
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1805
- Best practice for storing large datasets includes ideally, storing it in 3 or more regions, with 4 or more storage provider operators or owners.You should list Miner ID, Business Entity, Location of sps you will cooperate with.

**Comment by Jaida0** [comment]
@Sunnyiscoming 
I'm an individual dp. This application is for the data I have downloaded. 
Before cooperation, I will ensure it with SPs.
I didn't know this in advance. After you mentioned, I saw that he didn't begin storing.
I have listed sps in the application and [Fil+ registration form](https://form.jotform.com/231862753015656)
Email has been sent and the form has been filled.
Please check it. Thank you!

**Comment by Jaida0** [comment]
@herrehesse Hello friend, the amount is just based on the size of dataset. Before applied for datacap, I learned about IPFS, then I began to know about Filecoin. I think Fil+ can help data be stored safely and distributedly, that's why I'm very interested in joining in the development process of Fil+. And I am confident that I can do well with this application and storage.

**Comment by herrehesse** [comment]
We're thrilled to hear about your interest, and we're excited to have you on board. While we're enthusiastic about your confidence, I'd strongly recommend starting with a smaller allocation. This approach will help you build a reputation and gain experience within the Filecoin and datacap community.

Before considering an allocation as substantial as 6 PiB of datacap, it's important for us to establish a sense of trust within the community. Could you perhaps begin with a 10TiB allocation? This would provide an opportunity for you to showcase your skills, share your minerID list, and provide insight into the regions and businesses you're involved with.

Not supportive of a 6PiB grant on an account with no reputation.

**Comment by Filplus-govteam** [comment]
SP entities confirmed via registration form:
f01211025 HK
f01086553 CN
f01125783 HK
f01347695 KR
f0131464 US

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 6PiB

**Expected weekly DataCap usage rate**
> 800TiB

**Client address**
>f16grdbr73dccc66dxhtrr2shqoarpupowpteo2yi

**Comment by cryptowhizzard** [comment]
f01211025 is a CC miner, no IP adres set on chain, not reachable.
f01086553 is a CC miner, no IP adres set on chain, not reachable.
f01125783 is a CC miner, no IP adres set on chain, not reachable.
f01347695 is a CC miner, no IP adres set on chain, not reachable.
f0131464 is a CC miner, no IP adres set on chain, not reachable.

None of these miners are useable for FIL+ and none of these comply with the rules & guidelines.

**Comment by Filplus-govteam** [comment]
If true - please remove these miner IDs @Jaida0 and find other SPs

**Comment by Jaida0** [comment]
@cryptowhizzard
First, I haven't been granted datacap. These SPs didn't start sealing yet, so that they are still CC miners.
Second, **there's no rules that clients can not cooperate with CC miners.**
Third, these SPs didn't start sealing yet, so there's no need to public their ip. I will inform them when they begin sealing.

You can look forward to our report after they begin storing data. 

@filplus-govteam I will find more SPs if I found any SPs are not good ideas to work with. Thank you.

**Comment by cryptowhizzard** [comment]
Hi @Jaida0 

If your miners are not reachable:

- We cannot verify their location.
- We cannot verify they are able to serve retrievals and fit in the FIL+ program.

Please contact your SP's and fix.

**Comment by Jaida0** [comment]
@cryptowhizzard OK. I have contacted with SPs and they will check their settings. To make the process go better, I went ahead and reached out to some other SPs and would add them into our plan.
f02123612 | Bruce | US
f01975299 | Emily | HK
f01939387 | Alice | CN

Welcome notaries to support my application!

**Comment by cryptowhizzard** [comment]
Hi,

f02123612  is running on Misaka Network, Inc in Denver. This is a cloud VPN provider.
Where is this miner located? It is not in the US.
Secondly, it is not providing retrieval.

f01975299 is seen in abuse with application #1558 and not proving retrieval.
f01939387  is seen in abuse with application #1558 and not proving retrieval.

Please clarify?

**Comment by Jaida0** [comment]
They have told me that they locate in US. And they agree to support retrieval when they begin sealing.
![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/125258621/c795aa87-9bdd-4f81-9de0-7521992112a5)

We are willing to follow the rules of the community. If community think we should change SPs even if they support retrieval, we will look for new SP.

**Comment by Jaida0** [comment]
Can notaries help sign my application? We will be serious and follow the rules.

**Comment by mikezli** [comment]
Thank you for contacting me, the first round, temporary support, I will pay attention to the SP situation of follow-up cooperation!

**Comment by mikezli** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacea6zf3rnmiqtmjktwytgzjszqcxd65obq2fsvgd6wlg65odw4do74 
#### Address 
> f16grdbr73dccc66dxhtrr2shqoarpupowpteo2yi
#### Datacap Allocated
> 307.19TiB
#### Signer Address
> f1dnb3uz7sylxk6emti3ififcvu3nlufnnsjui6ea
#### Id
> e6432638-122c-4208-80f5-cf313ef593e7
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacea6zf3rnmiqtmjktwytgzjszqcxd65obq2fsvgd6wlg65odw4do74

**Comment by Jaida0** [comment]
Yes, we continue updating the list.
f02114994 | Sichuan ; f01084913 | HongKong ; f01841134 | Guizhou ; f02368321 | Singapore
Hope notaries can sign for us. Then there'll be more SPs want to cooperate with us!

> @Jaida0 you need 4 SP entities and different locations. Also you will be responsible to ensure your SPs provide retrievals on this dataset.
> 
> Please provide a clear list of miner IDs you are partnering with before notary signature here

**Comment by cryptowhizzard** [comment]
I would like to protest against this change.

All these SP's are tagged in my system. None of them provide graphsync retrievals, secondly I have received garbage data from some over http retrieving files.

@Jaida0 please provide us with a sample CID ( .car ) file of the data you will be storing so we can check your data.

**Comment by Jaida0** [comment]
@cryptowhizzard
Can you share your system to us and explain why you flag these SPs?
What's your standard about SPs? Is there any conflict of interest between you and these SPs?
>None of them provide graphsync retrievals

Is there any rules that say SPs don't support graphsync retrieval are breaking the rules?
The SPs we chose has been checked to support http retrieval. Is http retrieval not a standard of community?

**Comment by cryptowhizzard** [comment]
f02114994 | Sichuan ; f01084913 | HongKong ; f01841134 | Guizhou ; f02368321 | Singapore

f02368321 https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/2057

Your reputational SP's did get their datacap removed.

I suggest you look at others.

**Comment by Jaida0** [comment]
I do not see any problem from that application on these SPs.
@galen-mcandrew @kevzak @raghavrmadya Can you help provide some standard or advice about choosing SPs? I don't know what's wrong with the sp I'm looking for.

@cryptowhizzard Also, can you help answer these questions? I really puzzled. Thank you.

> @cryptowhizzard Can you share your system to us and explain why you flag these SPs? What's your standard about SPs? Is there any conflict of interest between you and these SPs?
> 
> > None of them provide graphsync retrievals
> 
> Is there any rules that say SPs don't support graphsync retrieval are breaking the rules? The SPs we chose has been checked to support http retrieval. Is http retrieval not a standard of community?

**Comment by Jaida0** [comment]
Yes

**Comment by Jaida0** [comment]
Yes should be open.

**Comment by Meibuy** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceczhell5a6y67vcxnxw6enoqngfcpysbmz5asdyhcetvpvgd2zgqi 
#### Address 
> f16grdbr73dccc66dxhtrr2shqoarpupowpteo2yi
#### Datacap Allocated
> 307.19TiB
#### Signer Address
> f1bwugfihrmn3iyunzyxst5nttql3dge4khwmurtq
#### Id
> e6432638-122c-4208-80f5-cf313ef593e7
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceczhell5a6y67vcxnxw6enoqngfcpysbmz5asdyhcetvpvgd2zgqi

**Comment by herrehesse** [comment]
checker:manualTrigger

**Comment by Jaida0** [comment]
Yes! We're in process.

**Comment by Sunnyiscoming** [comment]
Some of the sps in the table do not participated in.
@ Can you explain about that?

**Comment by Filplus-govteam** [comment]
Closing as SPs in upfront list do not match those taking deals, 922 violation

**Comment by Jaida0** [comment]
@Sunnyiscoming @Filplus-govteam Hello, I have updated the list of sps and resumitted the Fil+ registration form.
Although we made plans in advance, the actual cooperation process is likely to face changes. I'll keep it updated. Can you open my application?

**Comment by Filplus-govteam** [comment]
SP 1	f02208475	Jack Liu	jacli883@outlook.com	redstone	Guangzhou, Guangdong,CN	no	Jack
SP 2	f02211576	York	goodyoweq@outlook.com	flyship	Dongguan,Guangdong	no	York
SP 3	f081976	Earl	eerarl522@outlook.com	wantou	Xian, Shanxi	no	Earl
SP 4	f02834511	Don	dpmbutwe@outlook.com	webgroup	HongKong	no	Don
SP 5	f01844043	Abel	comeab67el@outlook.com	abel	Ashburn, US	no	abel


@Jaida0 thanks for the list. Next, please collect SP entity and location proof from your SPs and send to filplus.govteam@gmail.com

**Comment by Jaida0** [comment]
@Filplus-govteam Are you joking?
I have submitted Fil+ registration form twice and provided list of SPs a million times. Now you let me send all of information to another email. _Are you just looking for an excuse to stop applicants?_ 
I don't see you asking for the same thing on other's application. @cryptowhizzard @xinaxu Can they be treated the same way?  Can @jbenet be treated the same way?

**Comment by Filplus-govteam** [comment]
@Jaida0 each process utilize has to iterate to evolve with users. What we've learned in this process, is that sending a list of names and emails does not actually verify anything. We emailed SP addresses and asked for SPs to send me proof of entity and location. We did not receive anything. 

From a quick search, SP IDs are under VPN vender services, so there is no way to validate actual locations.

And now, yes we changed our process to make it easier for you to provide information. You can now control collecting information from SPs and send to the email above.
