### ISSUE TITLE
[DataCap Application] <HZ Weitu technology Co., LTD> - <3Dsolution nonE-FIL>

### ISSUE THREAD

**Issue by xujunhuaweitu** [filecoin-project/filecoin-plus-large-datasets#2151]
### Data Owner Name

Hangzhou Weitu technology Co., LTD

### What is your role related to the dataset

Dataset Owner

### Data Owner Country/Region

China

### Data Owner Industry

IT & Technology Services

### Website

N/A

### Social Media

```text
N/A
```

### Total amount of DataCap being requested

5PiB

### Expected size of single dataset (one copy)

500T

### Number of replicas to store

10

### Weekly allocation of DataCap requested

800TiB

### On-chain address for first allocation

f1elc35nz6bzmtxmchc2uoiajv5mkjuhw2yvorl5i

### Data Type of Application

Public, Open Commercial/Enterprise

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
We leverage our parent company's expertise in computer hardware and software infrastructure design to establish ourselves as a leading provider of professional computer technology services, a manufacturer of blockchain products, and a distributor of electronic commercial display solutions. We are actively engaged in blockchain technology research and employ cutting-edge methods to integrate blockchain computing into devices like smart homes and HVAC equipment. By harnessing the power of idle devices through specialized computing modules, we enhance our computational capabilities while keeping costs minimal. Furthermore, we offer remote monitoring software for these blockchain devices, ensuring a secure and efficient control system. Our philosophy is rooted in professionalism and excellence, evident in our diverse range of intelligent commercial display products and integrated solutions that cater to the TV and surveillance industries.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
The data of the company's 3D glasses-free display and other related products,
designed product posters and other promotional content
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### If you are a data preparer. What is your location (City and Country)

```text
Hangzhou, China
```

### If you are a data preparer, how will the data be prepared? Please include tooling used and technical details?

```text
I'm a preparer also the owner of our data. Our data was stored in our own storage infra. We will transfer online to those SPs when they are ready.
```

### Has this dataset been stored on the Filecoin network before? If so, please explain and make the case why you would like to store this dataset again to the network. Provide details on preparation and/or SP distribution.

```text
N/A
```

### Please share a sample of the data

```text
https://drive.google.com/file/d/17zB2loGKl8ou3JuMjYSbm5SIsG1xT4c9/view?usp=sharing

https://drive.google.com/file/d/1H5jU2bvAxS9cdn7WK7Y9hTP5guiC6V_t/view?usp=sharing

https://drive.google.com/file/d/1yd6WpiFFTMjAyTnMCEv0yDN11a6sMNNH/view?usp=sharing

https://drive.google.com/file/d/1Ni812sXw8yIwsKQERBgP-PnwtdcM2_T2/view?usp=sharing

https://drive.google.com/file/d/15YR7nF-aTaqGI4652UZNfu32NbFg6hKd/view?usp=sharing

https://drive.google.com/file/d/138RGOKpyADudpDFA4uWTtHo5loyqqPhw/view?usp=sharing

https://drive.google.com/file/d/1BZACooUwziBZLIVmAxIY9jSgjagsuPc4/view?usp=sharing

https://drive.google.com/file/d/1BZACooUwziBZLIVmAxIY9jSgjagsuPc4/view?usp=sharing

https://drive.google.com/file/d/1sElRryQiWCOhyhlyYsPwsSzFNqwu3HGz/view?usp=sharing

https://drive.google.com/file/d/1ksSr6VEJ7Wb8JkQbowZLgTYBC7ddte8q/view?usp=sharing

https://drive.google.com/file/d/1YsI3ABIHm7zD6gE08Kb3t-9gkuT-BLCJ/view?usp=sharing

https://drive.google.com/file/d/1nhostX6jSg0JimxACvVL8x6Cv9ijmDEu/view?usp=sharing

https://drive.google.com/file/d/1vpAPxS_A6DTxH1FyPTdY8DRtabONRWF4/view?usp=sharing

https://drive.google.com/file/d/1NvsxUXM5Fp-85Su9WS6h_96i2fuuR_gQ/view?usp=sharing

https://drive.google.com/file/d/1ndMY9G0vefBkyhr-g-WdqgFTlrR3F1m0/view?usp=sharing

https://drive.google.com/file/d/1uHyslyOh38FkaSCfduAaGMGKP7E8U2rr/view?usp=sharing

https://drive.google.com/file/d/1RvBUq0Gb80reLepggu_BzBtHB4BP0Xhe/view?usp=sharing
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Sporadic

### For how long do you plan to keep this dataset stored on Filecoin

2 to 3 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, South America, Europe

### How will you be distributing your data to storage providers

Cloud storage (i.e. S3), HTTP or FTP server, IPFS, Lotus built-in data transfer

### How do you plan to choose storage providers

Slack, Filmine, Partners

### If you already have a list of storage providers to work with, fill out their names and provider IDs below

```text
IN communicating. Base on whether the SPs have collateral or not when I pass the application.
```

### How do you plan to make deals to your storage providers

Boost client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
Is there any social media related with the organization? It seems that data samples you provide is relate with WEITU.
![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/105098820/f2299531-3540-433a-ab94-fab24fbd7348)
Is the data you want to store all generated by your company?
Could you send an email to filplus-app-review@fil.org with your official domain in order to confirm your identity? Email name should includes the issue id #2151.
- Have you prepared enough token for sector pledge?
- Best practice for storing large datasets includes ideally, storing it in 3 or more regions, with 4 or more storage provider operators or owners.You should list Miner ID, Business Entity, Location of sps you will cooperate with.
- Per the https://github.com/filecoin-project/notary-governance/issues/922 for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

This information will be reviewed by Fil+ Governance team to confirm validity and then the application will be triggered for notary review. Let us know if you have any questions.

**Comment by Sunnyiscoming** [comment]
Any update here?

**Comment by xujunhuaweitu** [comment]
Hello @Sunnyiscoming , I apologize for the long wait. Here is our response:
1. Currently, we do not have any relevant social media. The data we have pertains to our company's operations, mainly related to AI, blockchain, electronic screens, software services, and other relevant data. Additionally, an email has been sent to you, please check your inbox.
2. We have prepared a portion of the tokens and will distribute them according to different stages. The tokens for the initial launch have all been prepared.
3. We have submitted the information regarding our cooperation through the form. Please take a look.

**Comment by xujunhuaweitu** [comment]
As our application involves company data, based on suggestions from community members, we believe applying for e+fil might be more suitable. We are open to going through the KYC process. @Kevin-FF-USA

**Comment by kevzak** [comment]
@xujunhuaweitu see process for E-Fil+ please complete KYC and KYB check and let me know when complete. . Instructions can be found here https://efilplus.super.site/

**Comment by Sunnyiscoming** [comment]
f01853077 SA
f01834291 US
f02239387 HK
f02363742 CN
f02327534 US

**Comment by cryptowhizzard** [comment]
f01853077 flagged for abuse. Also not providing retrievals in dozens of applications according to retrieval bot. Not eligible.
f01834291 US -> ok.
f02239387 HK flagged for abuse. Also not providing retrievals in 7 applications according to retrieval bot. Not eligible.
f02363742 CN
f02327534 US

**Comment by data-programs** [comment]
<img width="32" alt="KYC" Verified src="https://stable.filplus.storage/images/filplus-kyc-verified-badge.png"/>

This user’s identity has been verified through [filplus.storage](https://filplus.storage)

**Comment by xujunhuaweitu** [comment]
@kevzak  We have submitted for KYC and KYB review.
![1188646ec097d7bb074663f9801a078](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/139351097/ee76ad13-5d68-4f94-a4bc-eae5efaeb189)

**Comment by Chuangshi1** [comment]
> f01853077 flagged for abuse. Also not providing retrievals in dozens of applications according to retrieval bot. Not eligible. f01834291 US -> ok. f02239387 HK flagged for abuse. Also not providing retrievals in 7 applications according to retrieval bot. Not eligible. f02363742 CN flagged for abuse. Also not providing retrievals according to retrieval bot. Not eligible. f02327534 US -> ok.

@xujunhuaweitu  Could you please offer more excellent sps for sealing? and their name, email. Thanks!

**Comment by xujunhuaweitu** [comment]
@Chuangshi1 
Disclosure Update:
f01853077 - Verified to support retrieval
f01834291 US - Approved by community reviewers
f02327534 US - Approved by community reviewers
f02226869 - CN - LuckyMine - New updated node
f02274508 - HK - H&W - New updated node

**Comment by Chuangshi1** [comment]
@xujunhuaweitu  Can you  send your company file to my slack? I will check that.

**Comment by xujunhuaweitu** [comment]
@Chuangshi1 
Sure. Which slack account do you have, please?

**Comment by Chuangshi1** [comment]
> @Chuangshi1 Sure. Which slack account do you have, please?

 Account name: IPFS

**Comment by xujunhuaweitu** [comment]
@Chuangshi1 
Okay, the information has been sent. Please check.

**Comment by Chuangshi1** [comment]
Check all the information, It is ok for me to support the first round.

**Comment by Chuangshi1** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebhlykjtzvmkjzn6pixbjsfidtdixjh7cnv2qrfogzrum3may5wjg 
#### Address 
> f1elc35nz6bzmtxmchc2uoiajv5mkjuhw2yvorl5i
#### Datacap Allocated
> 256.00TiB
#### Signer Address
> f1mdk7s2vntzm6hu35yuo6vjubtrpfnb2awhgvrri
#### Id
> 2ed70426-964b-409e-b6b7-bdbd271efccf
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebhlykjtzvmkjzn6pixbjsfidtdixjh7cnv2qrfogzrum3may5wjg

**Comment by maxvint** [comment]
@xujunhuaweitu Could you please send your company file to my slack? I will check that. My slack account name is: Max, thanks.

**Comment by xujunhuaweitu** [comment]
@maxvint 
Okay, the file has been sent. Please check.

**Comment by laurarenpanda** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecjh3tye37kcl3ton64uyubybkykoxetim5yldkpg563frfc6g2lk 
#### Address 
> f1elc35nz6bzmtxmchc2uoiajv5mkjuhw2yvorl5i
#### Datacap Allocated
> 256.00TiB
#### Signer Address
> f1bp3tzp536edm7dodldceekzbsx7zcy7hdfg6uzq
#### Id
> 2ed70426-964b-409e-b6b7-bdbd271efccf
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecjh3tye37kcl3ton64uyubybkykoxetim5yldkpg563frfc6g2lk

**Comment by herrehesse** [comment]
Highly questionable LDN, will inspect every deal and distribution.

**Comment by xujunhuaweitu** [comment]
checker:manualTrigger

**Comment by xujunhuaweitu** [comment]
checker:manualTrigger

**Comment by zcfil** [comment]
checker:manualTrigger

**Comment by zcfil** [comment]
@xujunhuaweitu Once again, can this data be retrieved by everyone?

Could you please send your company file to my slack? I will check that. My slack account name is:zcfil，thanks

**Comment by xujunhuaweitu** [comment]
@zcfil 
Yes, the sp we work with they all support retrieval. But we do store private data. Also the file we have sent via slack, please check.

**Comment by sxxfuture-official** [comment]
@xujunhuaweitu 
I need to know the information and authenticity of the applicant，So could you please send your company file to my slack?
Account : Jintao - Sxxfuture

**Comment by xujunhuaweitu** [comment]
@sxxfuture-official 
We have sent the verified files, please review the.

**Comment by sxxfuture-official** [comment]
Checked the company's relevant documents, the content is comprehensive and authentic.
Regarding sealing, it is currently in the second round. We hope to introduce more SPs and distribute data replicas to different SPs.

**Comment by sxxfuture-official** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceclnojlftf5qj4qn5r7jh2meuiqfw4hmot2ixif4vnx6fdqep3p5c 
#### Address 
> f1elc35nz6bzmtxmchc2uoiajv5mkjuhw2yvorl5i
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f1foiomqlmoshpuxm6aie4xysffqezkjnokgwcecq
#### Id
> ecf7969a-0055-4177-8336-bd19dcea6d5c
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceclnojlftf5qj4qn5r7jh2meuiqfw4hmot2ixif4vnx6fdqep3p5c

**Comment by zcfil** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb7lxu3ob5gabwzpymsekkauykd2nc6n3lh3m4h36gak2ruwl2l5e 
#### Address 
> f1elc35nz6bzmtxmchc2uoiajv5mkjuhw2yvorl5i
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f1cjzbiy5xd4ehera4wmbz63pd5ku4oo7g52cldga
#### Id
> ecf7969a-0055-4177-8336-bd19dcea6d5c
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb7lxu3ob5gabwzpymsekkauykd2nc6n3lh3m4h36gak2ruwl2l5e

**Comment by cryptowhizzard** [comment]
I tried to retrieve data here but my attempts fail.

/usr/bin/wget --retry-connrefused --waitretry=1 --read-timeout=20 --timeout=15 -t 0 http://101.206.185.216:23459/piece/baga6ea4seaqjvkkufdmwczonzxo33e3odukbybg6jo6tin7qy5r2ruc6tqnrsoa -O /root/downloadedcarfiles/httpretrievals/2151-f02637820-f02368282-54302373-baga6ea4seaqjvkkufdmwczonzxo33e3odukbybg6jo6tin7qy5r2ruc6tqnrsoa 2>&1 | /bin/tee /var/www/html/filplus/2151-f02637820-f02368282-54302373-baga6ea4seaqjvkkufdmwczonzxo33e3odukbybg6jo6tin7qy5r2ruc6tqnrsoa-http.log >(/usr/bin/logger -t dealscanner-LDN2151-f02637820-f02368282 ) 
--2023-09-12 20:02:43--  http://101.206.185.216:23459/piece/baga6ea4seaqjvkkufdmwczonzxo33e3odukbybg6jo6tin7qy5r2ruc6tqnrsoa
Connecting to 101.206.185.216:23459... connected.
HTTP request sent, awaiting response... 404 Not Found
2023-09-12 20:02:43 ERROR 404: Not Found.

**Comment by cryptowhizzard** [comment]
Dear xujunhuaweitu,

As notary I am doing due diligence on your LDN. I could not get retrieval to work. Can you please upload the car file of CID baga6ea4seaqdos3rvrytx27ky5pbhjhfxfr3rked35ws2pmmvbrjf6nms3grgdq ?

You can use our upload system at http://send.datasetcreators.com. Please select 7 days for the system to keep the file and post the link you received here so I (and other notaries) can download your content.

**Comment by xujunhuaweitu** [comment]
@cryptowhizzard 
The sector you attempted to retrieve is a failed sector. You can perform sample tests on other sectors with this storage provider, such as the CID I attempted to retrieve, which was successful. 
< http://101.206.185.216:23459/piece/baga6ea4seaqi2jaju4ahjvko66vhp26auahjidotmrximbbh6utytfuih2ymoji >

Additionally, from the bot's report, you can see that only this storage provider has a relatively low retrieval rate (possibly due to network issues or disk mounting problems). You can also try testing CID retrieval with other storage providers. 
![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/104019147/0510e22a-f0fa-487a-a657-55297b4fee90)

Regarding your question about upload, it seems that it doesn't support large file transfers.

**Comment by Casey-PG** [comment]
After retrieving, we want to support this round. Please keep retrieval and report healthy.
![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/107392596/669ef610-91aa-49f9-9b5b-c4f866d47e2d)

**Comment by Casey-PG** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacea4wvesf5jry3g6xektikciglfavmdg6yt4chd553rbppk6lfsi4k 
#### Address 
> f1elc35nz6bzmtxmchc2uoiajv5mkjuhw2yvorl5i
#### Datacap Allocated
> 1.00PiB
#### Signer Address
> f1d4yb3wags3mtddzesxoo63jv7dmlec3bq4yteni
#### Id
> dce26a85-a082-4b40-a67d-48884589a7eb
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacea4wvesf5jry3g6xektikciglfavmdg6yt4chd553rbppk6lfsi4k

**Comment by maxvint** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedm32prilbs3e6kq7thwdexwer3ns7fkcaa755ml2exbcm4glnwow 
#### Address 
> f1elc35nz6bzmtxmchc2uoiajv5mkjuhw2yvorl5i
#### Datacap Allocated
> 1.00PiB
#### Signer Address
> f1ui5iy4mmkxjbw7752omiwp2ols2fzv4thrayagi
#### Id
> dce26a85-a082-4b40-a67d-48884589a7eb
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedm32prilbs3e6kq7thwdexwer3ns7fkcaa755ml2exbcm4glnwow

**Comment by cryptowhizzard** [comment]
Hello,

I have managed to download a deals from you but there is something strange with your data:

gocar inspect 2151-f02637820-f02329119-53035030-baga6ea4seaqfz6rf2wjzj73oo235opzkfr2lvprv5mzqsfdxjo3g5qphzaahgoy 
Version: 1
Roots: bafykbzaceaonces5i6g42il5xxnrfgaojlkxupjlxxcyxkns2ck4tm4l7ie2o
Root blocks present in data: Yes
Block count: 32803
Min / average / max block length (bytes): 60 / 1047510 / 1048576
Min / average / max CID length (bytes): 38 / 38 / 64
Block count per codec:
	raw: 32769
	dag-pb: 34
CID count per multihash:
	identity: 1
	blake2b-256: 32802

The data provided is not the data you show in the samples of your LDN and i cannot unpack the car file to UnixFS. Can you explain?

**Comment by cryptowhizzard** [comment]
@Casey-PG @maxvint 

Did you download data from this LDN and did you inspect the data? Please provide me with the due diligence done?

**Comment by xujunhuaweitu** [comment]
@cryptowhizzard  @kevzak 
We have applied for private data files, which are not public files. We have encrypted these files during storage.

**Comment by cryptowhizzard** [comment]
![Scherm­afbeelding 2023-09-18 om 14 48 57](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/36404435/ccfc9a9d-8fe5-4f56-8012-d5d2f44b2ce3)

This is the Non E-Fil.

**Comment by xujunhuaweitu** [comment]
@cryptowhizzard 
Please review the records. 
![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/104019147/448f5c2b-aa4f-4a97-b3f9-4b7ca3980ab2)

**Comment by psh0691** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedtbi6srbddas4bpkov7yt5dunkt3ptcpunwzeixf32drpaaa7ezy 
#### Address 
> f1elc35nz6bzmtxmchc2uoiajv5mkjuhw2yvorl5i
#### Datacap Allocated
> 2.00PiB
#### Signer Address
> f1qdko4jg25vo35qmyvcrw4ak4fmuu3f5rif2kc7i
#### Id
> 9436e151-8e3c-4971-9271-b290057c310f
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedtbi6srbddas4bpkov7yt5dunkt3ptcpunwzeixf32drpaaa7ezy

**Comment by psh0691** [comment]
![스크린샷 2023-09-20 15-17-20](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/69004801/69192192-4ac6-4a54-a89a-bec7989de8e6)
In fact, it was distributed to 10 SPs, but it appears to be skewed to a small number of SPs.

**Comment by NDLABS-Leo** [comment]
@psh0691 Thank you for your support.

@DaYouGroup 
Yes, because the storage speed of each SP varies, e+fil data needs to be encrypted before storage by SPs. The speed of encrypting data varies depending on the encryption method used.

**Comment by NDLABS-Leo** [comment]
checker:manualTrigger

**Comment by xujunhuaweitu** [comment]
@psh0691 
Thank you for your support.

@DaYouGroup 
Yes, because the storage speed of each SP varies, e+fil data needs to be encrypted before storage by SPs. The speed of encrypting data varies depending on the encryption method used.

**Comment by NDLABS-Leo** [comment]
@psh0691
Thank you for your support.

@DaYouGroup
Yes, because the storage speed of each SP varies, e+fil data needs to be encrypted before storage by SPs. The speed of encrypting data varies depending on the encryption method used.

**Comment by NDLABS-Leo** [comment]
I apologize for the copying and pasting error. I was just doing a quick check.

**Comment by xujunhuaweitu** [comment]
keep open

**Comment by NDLABS-Leo** [comment]
checker:manualTrigger

**Comment by AlanGreaterheat** [comment]
checker:manualTrigger

**Comment by AlanGreaterheat** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceavnjkkw2bbbibhqungrbe7n6aublxxt4fiko766ierzpbcrv6lo6 
#### Address 
> f1elc35nz6bzmtxmchc2uoiajv5mkjuhw2yvorl5i
#### Datacap Allocated
> 2.00PiB
#### Signer Address
> f1pnmzlxj7cfeo2v6oj5nco46hkg2l46wj7o4xxui
#### Id
> 9436e151-8e3c-4971-9271-b290057c310f
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceavnjkkw2bbbibhqungrbe7n6aublxxt4fiko766ierzpbcrv6lo6

**Comment by Tom-OriginStorage** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebfdqomrawygom74e6myhdi57devkk6xbpzsu3lragohe4etvn7hk 
#### Address 
> f1elc35nz6bzmtxmchc2uoiajv5mkjuhw2yvorl5i
#### Datacap Allocated
> 2.00PiB
#### Signer Address
> f1q6bpjlqia6iemqbrdaxr2uehrhpvoju3qh4lpga
#### Id
> 9436e151-8e3c-4971-9271-b290057c310f
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebfdqomrawygom74e6myhdi57devkk6xbpzsu3lragohe4etvn7hk

**Comment by kevzak** [comment]
checker:manualTrigger

**Comment by kevzak** [comment]
SPs taking deals
f02211572 | Chengdu, Sichuan, CNChina Mobile Communications Group Co., Ltd. | 92.00 TiB | 2.38% | 92.00 TiB | 0.00%
f02368282 | Chengdu, Sichuan, CNCHINA UNICOM China169 Backbone | 752.34 TiB | 19.47% | 721.72 TiB | 4.07%
f02226869 | Nanchang, Jiangxi, CNCHINA UNICOM China169 Backbone | 399.91 TiB | 10.35% | 398.19 TiB | 0.43%
f02274508 | Hong Kong, Central and Western, HKChina Unicom Global | 955.22 TiB | 24.72% | 955.22 TiB | 0.00%
f02815620 | Hong Kong, Central and Western, HKChina Unicom Global | 52.22 TiB | 1.35% | 52.22 TiB | 0.00%
f02329119 | Hangzhou, Zhejiang, CNCT-HangZhou-IDC | 144.13 TiB | 3.73% | 144.13 TiB | 0.00%
f02133079 | Hong Kong, Central and Western, HKHK Broadband Network Ltd. | 51.72 TiB | 1.34% | 51.72 TiB | 0.00%
f02037700 | Seoul, Seoul, KRKorea Telecom | 259.94 TiB | 6.73% | 259.94 TiB | 0.00%
f01159754 | Singapore, Singapore, SGTencent Building, Kejizhongyi Avenue | 62.81 TiB | 1.63% | 62.81 TiB | 0.00%
f01853077 | Singapore, Singapore, SGZenlayer Inc | 354.34 TiB | 9.17% | 354.34 TiB | 0.00%
f01852363 | Singapore, Singapore, SGZenlayer Inc | 235.59 TiB | 6.10% | 235.59 TiB | 0.00%
f02322031 | Los Angeles, California, USZenlayer Inc | 99.88 TiB | 2.58% | 99.88 TiB | 0.00%
f02320270 | Los Angeles, California, USZenlayer Inc | 99.81 TiB | 2.58% | 99.81 TiB | 0.00%
f02327534 | Los Angeles, California, USZenlayer Inc | 99.66 TiB | 2.58% | 99.66 TiB | 0.00%
f02321504 | Los Angeles, California, USZenlayer Inc | 99.66 TiB | 2.58% | 99.66 TiB | 0.00%
f02320312 | Los Angeles, California, USZenlayer Inc | 99.53 TiB | 2.58% | 99.53 TiB | 0.00%
f01834291 | Los Angeles, California, USZenlayer Inc | 4.97 TiB | 0.13% | 4.97 TiB | 0.00%

SPs listed upfront:
f01853077 - Verified to support retrieval
f01834291 US - Approved by community reviewers
f02327534 US - Approved by community reviewers
f02226869 - CN - LuckyMine - New updated node
f02274508 - HK - H&W - New updated node

Confirm all SP entities @xujunhuaweitu

**Comment by herrehesse** [comment]
High amount of these deals go to the same entity under VPN. Selfdealing is what we are looking at.
