### ISSUE TITLE
[DataCap Application] A-speed

### ISSUE THREAD

**Issue by speed0211** [filecoin-project/filecoin-plus-large-datasets#2153]
### Data Owner Name
A-speed

### What is your role related to the dataset
Dataset Owner

### Data Owner Country/Region
Hong Kong

### Data Owner Industry
IT & Technology Services

### Website
[ https://www.a-speed.net/]( https://www.a-speed.net/)

### Social Media
[at]A-speed (discord)

### Total amount of DataCap being requested
5 PiB

### Expected size of single dataset (one copy)
499 TiB

### Number of replicas to store
10

### Weekly allocation of DataCap requested
200 TiB

### On-chain address for first allocation
f1tvhaycpg7uiy6mqh7g7adc44ahuzgsg7xiabs4i

### Data Type of Application
Private Commercial/Enterprise

### Custom multisig
- [x] Use Custom Multisig

### Identifier
efil

### Share a brief history of your project and organization
Founded in 2012, A-SPEED headquartered in Singapore, regional offices in India, HK and growing network across the region including Asia, Pacific, Europe and USA.
A-Speed Technology is innovative digital transformation solutions, services and Product Company provides solutions to our respective clients and partners. We provide cloud computing services, Cloud strategy and business case development, Cloud architecture, Design & Implementation, Big data analytics solutions, OpenStack Private Cloud Platform, e-Commerce and m-Commerce solutions. We are focused on our clients business outcome and agile best practices, provide comprehensive solutions and services for businesses from small, medium & large.

### Is this project associated with other projects/ecosystem stakeholders?
No

### If answered yes, what are the other projects/ecosystem stakeholders
n/a

### Describe the data being stored onto Filecoin
Our data is generated by our users through AI

### Where was the data currently stored in this dataset sourced from
My own storage infra

### If you answered "Other" in the previous question, enter the details here
n/a

### If you are a data preparer, what is your location (City and Country)
HongKong China

### If you are a data preparer, how will the data be prepared? Please include tooling used and technical details?
Use our own development tool Boost-X, which contains fastcomp, go-car and other toolkits. Can support NFS, HTTP docking.

### If you are not preparing the data, who will prepare the data?  (Provide name and business)
n/a

### Has this dataset been stored on the Filecoin network before? If so, please explain and make the case why you would like to store this dataset again to the network. Provide details on preparation and/or SP distribution.
n/a

### Please share a sample of the data
https://drive.google.com/drive/folders/1Nf_cUMLFx7BWTV4sE6M7JIQH71PcPWK9?usp=sharing

### Confirm that this is a public dataset that can be retrieved by anyone on the Network
No

### If you chose not to confirm, what was the reason
My data will be encrypted and do not want to be retrieved by anyone other than me and the SP I work with

### What is the expected retrieval frequency for this data
Yearly

### For how long do you plan to keep this dataset stored on Filecoin
More than 3 years

### In which geographies do you plan on making storage deals
Greater China, Asia other than Greater China

### How will you be distributing your data to storage providers
HTTP or FTP server

### How do you plan to choose SP
Slack

### If you answered "Others" in the previous question, what is the tool or platform you plan to use
n/a

### If you already have a list of storage providers to work with, fill out their names and provider IDs below
n/a

### How do you plan to make deals to your storage providers
Boost client

### If you answered "Others/custom tool" in the previous question, enter the details here
n/a

### Can you confirm that you will follow the Fil+ guideline
Yes

_Application created via [filplus.storage](https://filplus.storage)_

**Comment by data-programs** [comment]
This application is requesting DataCap for a **private** dataset, so it's labeled `efil+`

**Comment by herrehesse** [comment]
Hello there! I've noticed that you're a new customer seeking a substantial volume of DC (5PiB). Could you provide us with some insight into your decision to not consider building your reputation with a smaller quantity initially? Appreciate it!

**Comment by speed0211** [comment]
> 你好呀！我注意到您是一位新客户，正在寻求大量 DC (5PiB)。您能否向我们提供一些关于您最初不考虑以较小数量来建立声誉的决定的见解？欣赏它！

**Comment by speed0211** [comment]
> 你好呀！我注意到您是一位新客户，正在寻求大量 DC (5PiB)。您能否向我们提供一些关于您最初不考虑以较小数量来建立声誉的决定的见解？欣赏它！

Hi, thanks for your question. First of all, I have participated in Filecoin as an individual investor before, and I have personally purchased FIL in the secondary market. because the price is relatively low recently, our company also has the demand of storing the company's data in this area, so this time it is to participate in the data storage in the name of the company.

Secondly, there are firewall restrictions on using Github in China, so our company has not applied for a Github account, and the code we develop is in our own code base.

Finally, the application for E-FIL+ has a more complete KYC/KYB mechanism, and we are willing to complete the KYC/KYB certification, so we submitted the application.

Since this is the first time I've submitted an application, I realized that I didn't write a lot of the content in it completely, and I'm going to close this application and resubmit it again later today.

**Comment by speed0211** [comment]
@herrehesse

**Comment by speed0211** [comment]
@herrehesse

**Comment by data-programs** [comment]
<img width="32" alt="KYC" Verified src="https://stable.filplus.storage/images/filplus-kyc-verified-badge.png"/>

This user’s identity has been verified through [filplus.storage](https://filplus.storage)
