### ISSUE TITLE
[DataCap Application] <Shenzhen Dadi Donghong architectural decoration Co., LTD> - <Architecture and design>

### ISSUE THREAD

**Issue by Rioa87** [filecoin-project/filecoin-plus-large-datasets#2154]
### Data Owner Name

Shenzhen Dadi Donghong architectural decoration Co., LTD

### What is your role related to the dataset

Data Preparer

### Data Owner Country/Region

China

### Data Owner Industry

Construction, Property & Real Estate

### Website

www.grounddh.com

### Social Media

```text
www.grounddh.com
```

### Total amount of DataCap being requested

5PiB

### Expected size of single dataset (one copy)

500T

### Number of replicas to store

10

### Weekly allocation of DataCap requested

500TiB

### On-chain address for first allocation

f135ek5cnapg4456jhtsq7r67r2zcxnexcfsxssai

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Research, development and technical consultation on waterproof and heat insulation technology and reinforcement technology; Building materials development, wholesale and retail; Domestic trade. (Except for items prohibited by laws, administrative regulations or decisions of The State Council and required to be approved before registration) construction machinery leasing. The licensed business projects are: building waterproof engineering, steel structure engineering, waterproof leak repair engineering, interior decoration engineering, housing engineering design and construction; Landscaping works; Construction labor subcontracting, highway, railway, bridge construction; Cast-in-place pile construction; Earthwork; Concrete precast processing.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### If answered yes, what are the other projects/ecosystem stakeholders

```text
no
```

### Describe the data being stored onto Filecoin

```text
Architectural design scheme data,
Material statistics.
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### If you answered "Other" in the previous question, enter the details here

```text
no
```

### If you are a data preparer. What is your location (City and Country)

```text
Shenzhen, China
```

### If you are a data preparer, how will the data be prepared? Please include tooling used and technical details?

```text
I'm a preparer, and our data is stored in our own storage infrastructure. When they're ready, we'll transfer the money online.
```

### Has this dataset been stored on the Filecoin network before? If so, please explain and make the case why you would like to store this dataset again to the network. Provide details on preparation and/or SP distribution.

```text
no
```

### Please share a sample of the data

```text
https://drive.google.com/drive/folders/1qZjgB6gytunee7DqxjEsYshUjugatLDh?usp=sharing
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Monthly

### For how long do you plan to keep this dataset stored on Filecoin

2 to 3 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America

### How will you be distributing your data to storage providers

HTTP or FTP server, Shipping hard drives

### How do you plan to choose storage providers

Slack, Partners

### If you already have a list of storage providers to work with, fill out their names and provider IDs below

```text
jack f0158156
aron f01877184
peng f01051151
huang f01836766
```

### How do you plan to make deals to your storage providers

Boost client, Lotus client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
- Could you send an email to filplus-app-review@fil.org with your official domain in order to confirm your identity? Email name should includes the issue id #2154.
- Have you prepared enough token for sector pledge?
- Best practice for storing large datasets includes ideally, storing it in 3 or more regions, with 4 or more storage provider operators or owners.You should list Miner ID, Business Entity, Location of sps you will cooperate with.
- Per the https://github.com/filecoin-project/notary-governance/issues/922 for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

This information will be reviewed by Fil+ Governance team to confirm validity and then the application will be triggered for notary review. Let us know if you have any questions.

**Comment by herrehesse** [comment]
Hello there! I've noticed that you're a new customer seeking a substantial volume of DC (5PiB). Could you provide us with some insight into your decision to not consider building your reputation with a smaller quantity initially? Appreciate it!

**Comment by Rioa87** [comment]
@Sunnyiscoming 
>Can you use your official domain name to email filplus-app-review@fil.org to confirm your identity? The email name should contain the issue ID [DataCap application] < Shenzhen Dadi Donghong Building Decoration Co., LTD. > - < Architecture and Design > #2154.

Our domain name does not open the mail function, the relevant proof I put in the following:
https://www.grounddh.com/2154.txt

>Have you prepared enough tokens for industry pledge?

My company is not an SP, but the SP we work with assures us that we have enough tokens and enough funds.

>Best practices for storing large data sets include ideally storing them in 3 or more regions and having 4 or more storage 
provider operators or owners. You should list the location of the miner ID, business entity, sps you will be working with.

Incheon, Korea          jack    f0158156
Singapore    aron    f01877184
Seoul, Korea      peng      f01051151
Guangzhou, China  huang   f01836766

**Comment by Rioa87** [comment]
@herrehesse 
We are very glad to receive your reply. This is our first time to use it, so we apply according to the actual situation of our company. If the future goes well, we will use it for a long time.
I hope my answer is a good start and look forward to hearing from you next time

**Comment by Rioa87** [comment]
@Sunnyiscoming 
![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/141409938/76706b25-b767-4de1-a5dd-aa4c900b9813)
The form has been submitted, please pay attention to checking

**Comment by herrehesse** [comment]
@Rioa87, your response does not directly address my question. Moreover, several of the miners you've listed have been linked to a significant number of abuse cases. This raises concerns and I am not supportive of this LDN.

**Comment by Filplus-govteam** [comment]
Confirm these are the 4 SPs that were submitted:
Incheon, Korea jack f0158156
Singapore aron f01877184
Seoul, Korea peng f01051151
Guangzhou, China huang f01836766

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 5PiB

**Expected weekly DataCap usage rate**
> 500TiB

**Client address**
>f135ek5cnapg4456jhtsq7r67r2zcxnexcfsxssai

**Comment by Rioa87** [comment]
@Sunnyiscoming Hello, how is mine different from others, why does the robot not trigger the signature request

**Comment by herrehesse** [comment]
@Rioa87 Why are you including miners who were previously involved in questionable activities or self-dealing? Moreover, the names don't reflect the businesses they're associated with. Once again, I must stress to the authorities that this isn't a suitable application. An applicant with no established reputation and miners known for misconduct shouldn't be allocated 5PiB of DC.

**Comment by Rioa87** [comment]
@herrehesse Which sp are you talking about? I will ask them the reason. Thank you.

**Comment by Sunnyiscoming** [comment]
Can you ask notaries to try to sign this application?

**Comment by herrehesse** [comment]
@Sunnyiscoming the minerID's listed are involved in multiple abuse cases. Asking notaries not to engage.

**Comment by Sunnyiscoming** [comment]
@Rioa87 Can you explain about that?

**Comment by jauea** [comment]
@herrehesse 
Please tell me which SP it is, I will not cooperate with this customer。

**Comment by Sunnyiscoming** [comment]
Any update here?

**Comment by Sunnyiscoming** [comment]
Close for no reply.

**Comment by Rioa87** [comment]
Sorry for the lack of replies, I've been doing prep work, including preparing data and looking for new miners, so I haven't been paying attention to this place

**Comment by Rioa87** [comment]
> @Sunnyiscoming the minerID's listed are involved in multiple abuse cases. Asking notaries not to engage.

Can you say which miner? I will go and ask about the actual situation and I am always on the lookout for new miners, if he is not qualified I will not work with him, thanks

**Comment by Rioa87** [comment]
@Sunnyiscoming So can you reopen it, I'll keep an eye on things here in the future, thanks!

**Comment by Rioa87** [comment]
@simonkim0515 @raghavrmadya Hi,Can you reopen it here?

**Comment by Rioa87** [comment]
@simonkim0515 @raghavrmadya  Hi,Can you reopen it here?
