### ISSUE TITLE
[DataCa99degreesp Application] <Organization> - <99degreesAR>

### ISSUE THREAD

**Issue by ninetyninedegrees** [filecoin-project/filecoin-plus-large-datasets#2157]
### Data Owner Name

Guangzhou Jiushijiudu Information Technology Co., Ltd

### What is your role related to the dataset

Dataset Owner

### Data Owner Country/Region

China

### Data Owner Industry

IT & Technology Services

### Website

www.99lt.com

### Social Media

```text
www.99lt.com
```

### Total amount of DataCap being requested

5PiB

### Expected size of single dataset (one copy)

500TB

### Number of replicas to store

10

### Weekly allocation of DataCap requested

500TiB

### On-chain address for first allocation

f1t4rb6hbqqmrv6idqx3fnjsclieoiey32urad3bi

### Data Type of Application

Public, Open Commercial/Enterprise

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Ninety Nine Degree Technology，It is a high-tech company specializing in AR (augmented reality) products and information construction projects. Since its establishment, we have been committed to promoting technological development and innovation, providing customers with cutting-edge AR solutions and information construction services. We have rich experience and professional knowledge in the field of AR technology. Our AR products cover multiple fields including education, entertainment, advertising, industry, and healthcare. Through AR technology, virtual information can be integrated with the real world, providing users with a brand new experience in their environment.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
AR training data
Graphic image recognition training data
Corporate promotion video
design source file
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### If you are a data preparer. What is your location (City and Country)

```text
guangzhou,china
```

### If you are a data preparer, how will the data be prepared? Please include tooling used and technical details?

```text
I'm a preparer, and our data is stored in our own storage infrastructure. When they're ready, we'll transfer the money online.
```

### If you are not preparing the data, who will prepare the data?  (Provide name and business)

```text
No response
```

### Has this dataset been stored on the Filecoin network before? If so, please explain and make the case why you would like to store this dataset again to the network. Provide details on preparation and/or SP distribution.

```text
No
```

### Please share a sample of the data

```text
https://drive.google.com/drive/folders/1-y6hWII_4YnTmBAh7U8BhsZUOUntf76n?usp=sharing
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Daily

### For how long do you plan to keep this dataset stored on Filecoin

1.5 to 2 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, Africa, North America, South America, Europe, Australia (continent)

### How will you be distributing your data to storage providers

Cloud storage (i.e. S3), HTTP or FTP server, Lotus built-in data transfer, I don't know yet

### How do you plan to choose storage providers

Slack, Partners

### If you answered "Others" in the previous question, what is the tool or platform you plan to use

```text
No response
```

### If you already have a list of storage providers to work with, fill out their names and provider IDs below

```text
n/a
```

### How do you plan to make deals to your storage providers

Lotus client, Droplet client, I don't know yet

### If you answered "Others/custom tool" in the previous question, enter the details here

```text
No response
```

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by herrehesse** [comment]
Hello there! I've noticed that you're a new customer seeking a substantial volume of DC (5PiB). Could you provide us with some insight into your decision to not consider building your reputation with a smaller quantity initially? Appreciate it!

**Comment by ninetyninedegrees** [comment]
> **Thanks for your request!** ❗ We have found some problems in the information provided.
> 
> * Address should start with either f1, f2, f3 or f4
>   Please, take a look at the request and edit the body of the issue providing all the required information.

I have updated the new address, please check
