### ISSUE TITLE
[DataCap Application] <Shenyang Dongya Medical Research Institute Co.> - <East Asia Medical>

### ISSUE THREAD

**Issue by Hunter3576** [filecoin-project/filecoin-plus-large-datasets#2159]
### Data Owner Name

Shenyang Dongya Medical Research Institute Co.

### What is your role related to the dataset

Data Preparer

### Data Owner Country/Region

China

### Data Owner Industry

Life Science / Healthcare

### Website

https://www.syeamri.com/

### Social Media

```text
https://www.syeamri.com/
```

### Total amount of DataCap being requested

4PiB

### Expected size of single dataset (one copy)

400TiB

### Number of replicas to store

10

### Weekly allocation of DataCap requested

400TiB

### On-chain address for first allocation

f1wpkzdsyum376fqfg4wgfnhmmcubvqj7duqldpma

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
We are a company dedicated to providing quality healthcare services. As a leading healthcare provider, we aim to provide our patients with the best possible treatment options through advanced technology and a dedicated team of healthcare professionals. Improving people's quality of life and helping them regain their health and stay well through innovative healthcare solutions. We are committed to being a leader in healthcare, delivering excellence in healthcare and making a positive social impact. We provide comprehensive healthcare services covering a wide range of areas including prevention, diagnosis, treatment and rehabilitation. We have a team of experienced doctors, nurses and healthcare professionals with a wide range of expertise and clinical experience to provide personalised and integrated medical care to our patients.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
Medical data, surgical data, equipment and other videos and images, medical literature, etc.
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### If you are a data preparer. What is your location (City and Country)

```text
Shenyang China
```

### If you are a data preparer, how will the data be prepared? Please include tooling used and technical details?

```text
We have our own storage facility . We will use the Boost tool
```

### Please share a sample of the data

```text
https://drive.google.com/drive/folders/1rJvCYROC5m35_GyISvHBXIoRQflhvyzd?usp=sharing
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Weekly

### For how long do you plan to keep this dataset stored on Filecoin

1.5 to 2 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China

### How will you be distributing your data to storage providers

HTTP or FTP server, Shipping hard drives

### How do you plan to choose storage providers

Slack, Partners

### If you already have a list of storage providers to work with, fill out their names and provider IDs below

```text
f01996817    Hong Kong
f02007892    Wuhan
f02252173    Tokyo      
f01289416    Taiwan
```

### How do you plan to make deals to your storage providers

Boost client, Singularity

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by herrehesse** [comment]
Hello there! I've noticed that you're a new client seeking a substantial volume of DC (4PiB). Could you provide us with some insight into your decision to not consider building your reputation with a smaller quantity initially? Appreciate it!

**Comment by Hunter3576** [comment]
> Could you send an email to [filplus-app-review@fil.org](mailto:filplus-app-review@fil.org) with your official domain in order to confirm your identity? Email name should includes the issue id #2159.
> 
>     * Have you prepared enough token for sector pledge?
> Yes our partners guarantee enough tokens as an industry commitment
>     * Best practice for storing large datasets includes ideally, storing it in 3 or more regions, with 4 or more storage provider operators or owners.You should list Miner ID, Business Entity, Location of sps you will cooperate with.
f01996817  Hong Kong
f02007892  Wuhan
f02252173  Tokyo       
f01289416  Taiwan
>     * Per the [Modification: Changes required to public open dataset application flow notary-governance#922](https://github.com/filecoin-project/notary-governance/issues/922) for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.
> 
> 
> This information will be reviewed by Fil+ Governance team to confirm validity and then the application will be triggered for notary review. Let us know if you have any questions.

The email form has been submitted

![图片](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/142307066/689a7104-47b7-452d-9bc8-fa1badaca9e9)

**Comment by Hunter3576** [comment]
> Hello there! I've noticed that you're a new client seeking a substantial volume of DC (4PiB). Could you provide us with some insight into your decision to not consider building your reputation with a smaller quantity initially? Appreciate it!

Filecoin's secure cloud storage service allows files to be uploaded to the network without having to worry about the security of the data, it uses advanced encryption and decentralised storage technologies, by participating in the storage network, not only can you reap the financial rewards, but you can also contribute to sustainability by processing data in an efficient way, thus reducing the environmental impact.

**Comment by Filplus-govteam** [comment]
Confirming the following SP entities are to be used: 
f01996817    Hong Kong
f02007892    Wuhan
f02252173    Tokyo      
f01289416    Taiwan

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 4PiB

**Expected weekly DataCap usage rate**
> 400TiB

**Client address**
>f1wpkzdsyum376fqfg4wgfnhmmcubvqj7duqldpma

**Comment by cryptowhizzard** [comment]
f01996817 is not open for retrieval and flagged for abuse. It can be seen in #1350.
f02007892 is flagged for abuse in #400 and is not open for retrieval.
f01289416 is flagged for abuse in #1550 and is not open for retrieval.

**Comment by Hunter3576** [comment]
> f01996817 is not open for retrieval and flagged for abuse. It can be seen in #1350. f02007892 is flagged for abuse in #400 and is not open for retrieval. f01289416 is flagged for abuse in #1550 and is not open for retrieval.

Thank you very much for your feedback! I will check it carefully and improve it, and I will continue to look for a new service provider (SP)!

**Comment by zcfil** [comment]
Please list the SPs and regions that you are preparing to collaborate with.

**Comment by Hunter3576** [comment]
> 
 f02055540  US
 f02252173 Tokyo
 f01313233 wuxi
 Flagged for abuse, abandoned. This is my new partner.

**Comment by Hunter3576** [comment]
> Please list the SPs and regions that you are preparing to collaborate with.

f02055540 US
f02252173 Tokyo
f01313233 wuxi
Flagged for abuse, abandoned. This is my new partner.

**Comment by herrehesse** [comment]
f02252173 - Has been engaged in various forms of abuse for example 2094 (self-dealing)

**Comment by Hunter3576** [comment]
> f02252173 - Has been engaged in various forms of abuse for example 2094 (self-dealing)
Thank you. I'll check.

**Comment by Hunter3576** [comment]
> This application has not seen any responses in the last 10 days. This issue will be marked with Stale label and will be closed in 4 days. Comment if you want to keep this application open.
> 
> -- Commented by Stale Bot.

In preliminary preparation

**Comment by Hunter3576** [comment]
In preliminary preparation

**Comment by Hunter3576** [comment]
In preliminary preparation

**Comment by Hunter3576** [comment]
> This application has not seen any responses in the last 10 days. This issue will be marked with Stale label and will be closed in 4 days. Comment if you want to keep this application open.
> 
> -- Commented by Stale Bot.

In preliminary preparation

**Comment by Hunter3576** [comment]
> This application has not seen any responses in the last 10 days. This issue will be marked with Stale label and will be closed in 4 days. Comment if you want to keep this application open.
> 
> -- Commented by Stale Bot.

keep it open

**Comment by kevzak** [comment]
Closing until clear SP entity list with miner IDs is provided here

**Comment by Hunter3576** [comment]
f02808889   Hong Kong
f01836766   GuangZhou
f01877184   Singapore
f01970716   GuangZhou

@kevzak The data is ready and has been re-contacted with a new sps for sealing, can you re-opened?

**Comment by Filplus-govteam** [comment]
@Hunter3576 you are looking to store 10 copies. We see only 4 miner IDs. Can you explain?

**Comment by Hunter3576** [comment]
> @Hunter3576 you are looking to store 10 copies. We see only 4 miner IDs. Can you explain?

I'm looking for more SPs, for now these four are downloaded and ready  data

**Comment by Hunter3576** [comment]
@Filplus-govteam Hello. Is this okay?

**Comment by Filplus-govteam** [comment]
You can find more or edit your application to apply for less copies

**Comment by Hunter3576** [comment]
> You can find more or edit your application to apply for less copies

I'm looking for more and they are already downloading the data, can you open it first?
Add 3 new
f02816666 Huhehaote
f02093396 Singapore
f02259777 Singapore
f02808889 Hong Kong
f01836766 GuangZhou
f01877184 Singapore
f01970716 GuangZhou
That makes seven.
