### ISSUE TITLE
[DataCa99degreesp Application] <Organization> - <99degreesAR>

### ISSUE THREAD

**Issue by ninetyninedegrees** [filecoin-project/filecoin-plus-large-datasets#2160]
### Data Owner Name

Guangzhou Jiushijiudu Information Technology Co., Ltd

### What is your role related to the dataset

Dataset Owner

### Data Owner Country/Region

China

### Data Owner Industry

IT & Technology Services

### Website

www.99lt.com

### Social Media

```text
www.99lt.com
```

### Total amount of DataCap being requested

5PiB

### Expected size of single dataset (one copy)

500TB

### Number of replicas to store

10

### Weekly allocation of DataCap requested

500TiB

### On-chain address for first allocation

f1t4rb6hbqqmrv6idqx3fnjsclieoiey32urad3bi

### Data Type of Application

Public, Open Commercial/Enterprise

### Custom multisig

- [ ] Use Custom Multisig

### Identifier

No response

### Share a brief history of your project and organization

```text
Ninety Nine Degree Technology，It is a high-tech company specializing in AR (augmented reality) products and information construction projects. Since its establishment, we have been committed to promoting technological development and innovation, providing customers with cutting-edge AR solutions and information construction services. We have rich experience and professional knowledge in the field of AR technology. Our AR products cover multiple fields including education, entertainment, advertising, industry, and healthcare. Through AR technology, virtual information can be integrated with the real world, providing users with a brand new experience in their environment.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### If answered yes, what are the other projects/ecosystem stakeholders

```text
No response
```

### Describe the data being stored onto Filecoin

```text
AR training data
Graphic image recognition training data
Corporate promotion video
design source file
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### If you answered "Other" in the previous question, enter the details here

```text
No response
```

### If you are a data preparer. What is your location (City and Country)

```text
guangzhou,china
```

### If you are a data preparer, how will the data be prepared? Please include tooling used and technical details?

```text
I'm a preparer, and our data is stored in our own storage infrastructure. When they're ready, we'll transfer the money online.
```

### If you are not preparing the data, who will prepare the data?  (Provide name and business)

```text
No response
```

### Has this dataset been stored on the Filecoin network before? If so, please explain and make the case why you would like to store this dataset again to the network. Provide details on preparation and/or SP distribution.

```text
No
```

### Please share a sample of the data

```text
https://drive.google.com/drive/folders/1-y6hWII_4YnTmBAh7U8BhsZUOUntf76n?usp=sharing
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### If you chose not to confirm, what was the reason

```text
No response
```

### What is the expected retrieval frequency for this data

Daily

### For how long do you plan to keep this dataset stored on Filecoin

1.5 to 2 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, Africa, North America, South America, Europe, Australia (continent)

### How will you be distributing your data to storage providers

Cloud storage (i.e. S3), HTTP or FTP server, Lotus built-in data transfer, I don't know yet

### How do you plan to choose storage providers

Slack, Partners

### If you answered "Others" in the previous question, what is the tool or platform you plan to use

```text
No response
```

### If you already have a list of storage providers to work with, fill out their names and provider IDs below

```text
n/a
```

### How do you plan to make deals to your storage providers

Lotus client, Droplet client, I don't know yet

### If you answered "Others/custom tool" in the previous question, enter the details here

```text
No response
```

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
Could you send an email to filplus-app-review@fil.org with your official domain in order to confirm your identity? Email name should includes the issue id #2160.
- Have you prepared enough token for sector pledge?
- Best practice for storing large datasets includes ideally, storing it in 3 or more regions, with 4 or more storage provider operators or owners.You should list Miner ID, Business Entity, Location of sps you will cooperate with.
- Per the https://github.com/filecoin-project/notary-governance/issues/922 for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

This information will be reviewed by Fil+ Governance team to confirm validity and then the application will be triggered for notary review. Let us know if you have any questions.

**Comment by ninetyninedegrees** [comment]
> 您能否使用您的官方域名发送电子邮件至[filplus-app-review@fil.org](mailto:filplus-app-review@fil.org)以确认您的身份？电子邮件名称应包含问题 ID #2160。
> 
> * 您准备好足够的代币用于行业质押了吗？
> * 存储大型数据集的最佳实践包括理想情况下将其存储在 3 个或更多区域，并有 4 个或更多存储提供商运营商或所有者。您应该列出矿工 ID、业务实体、您将合作的 sps 的位置。
> * 根据[修改：公共开放数据集申请流程](https://github.com/filecoin-project/notary-governance/issues/922)[ notary-governance#922](https://github.com/filecoin-project/notary-governance/issues/922)所需的更改对于开放、公共数据集申请人，请填写以下[Fil+ 注册表](https://form.jotform.com/231862753015656)以表明您自己是申请人，并请添加您所在 SP 实体的联系信息使用来存储数据的副本。[](https://github.com/filecoin-project/notary-governance/issues/922)[](https://form.jotform.com/231862753015656)
> 
> 该信息将由 Fil+ 治理团队审核以确认有效性，然后触发申请进行公证审核。假如你有任何问题请告知我们。

![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/141104133/74ddc866-fa5b-464a-b305-b170792d1ac1)
email replied

**Comment by ninetyninedegrees** [comment]
> Could you send an email to [filplus-app-review@fil.org](mailto:filplus-app-review@fil.org) with your official domain in order to confirm your identity? Email name should includes the issue id #2160.
> 
> * Have you prepared enough token for sector pledge?
> * Best practice for storing large datasets includes ideally, storing it in 3 or more regions, with 4 or more storage provider operators or owners.You should list Miner ID, Business Entity, Location of sps you will cooperate with.
> * Per the [Modification: Changes required to public open dataset application flow notary-governance#922](https://github.com/filecoin-project/notary-governance/issues/922) for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.
> 
> This information will be reviewed by Fil+ Governance team to confirm validity and then the application will be triggered for notary review. Let us know if you have any questions.

![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/141104133/efd22cab-a624-44de-aa38-73ede6dbae50)
email replied

**Comment by herrehesse** [comment]
@ninetyninedegrees can you list the Miner ID, Business Entity, Location of sps you will cooperate with? Thank you!

**Comment by Sunnyiscoming** [comment]
Have you submitted the form?

**Comment by ninetyninedegrees** [comment]
> [ninetyninedegrees](/ninetyninedegrees)
Sorry, I just filled out the form and submitted it

**Comment by ninetyninedegrees** [comment]
> Have you submitted the form?



> @ninetyninedegrees can you list the Miner ID, Business Entity, Location of sps you will cooperate with? Thank you!

f02056391，Hong Kong, Central and Western, HK
f02048990，Hong Kong, Central and Western, HK
f02041085，Tokyo, Tokyo, JP
f02059055，Seoul, Seoul, KR
f02042992，Singapore, Singapore, SG

**Comment by ninetyninedegrees** [comment]
@Sunnyiscoming 
> Sorry, I just filled out the form and submitted it

**Comment by ninetyninedegrees** [comment]
> Have you submitted the form?

@Sunnyiscoming
Sorry, I just filled out the form and submitted it，and I've got enough stake ready

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 5PiB

**Expected weekly DataCap usage rate**
> 500TiB

**Client address**
>f1t4rb6hbqqmrv6idqx3fnjsclieoiey32urad3bi

**Comment by herrehesse** [comment]
@ninetyninedegrees Greetings.

From the list you provided, it seems every entry is employing a VPN to conceal their genuine location. Could you provide evidence of their true whereabouts? Additionally, the applications associated with the minerID's were predominantly used in Asia with no distribution to other regions.

Could you shed light on why I should assume that subsequent minerID's such as f0203, f0204, f0205, especially when using VPNs, aren't operated by the same entity aiming to expand with datacap and engage in self-dealing?

I'm eager to understand better. Please enlighten me.

**Comment by cryptowhizzard** [comment]
Please note:

f02059055 has not been serving retrievals *according to the retrieval bot* in a dozen applications. It should be banned from FIL+.

**Comment by ninetyninedegrees** [comment]
> Please note:
> 
> f02059055 has not been serving retrievals _according to the retrieval bot_ in a dozen applications. It should be banned from FIL+.

OK, we will stop the cooperation with f02059055 and choose f02328179 chengdu for cooperation

**Comment by ninetyninedegrees** [comment]
> @ninetyninedegrees Greetings.
> 
> From the list you provided, it seems every entry is employing a VPN to conceal their genuine location. Could you provide evidence of their true whereabouts? Additionally, the applications associated with the minerID's were predominantly used in Asia with no distribution to other regions.
> 
> Could you shed light on why I should assume that subsequent minerID's such as f0203, f0204, f0205, especially when using VPNs, aren't operated by the same entity aiming to expand with datacap and engage in self-dealing?
> 
> I'm eager to understand better. Please enlighten me.
@herrehesse   Hi there,
Sorry, I don't quite understand what you want to express. Can you tell me how to provide something to answer your question? What I understand is that you need me and the owner of the above miner number to find out their real addresses and then synchronize the relevant information to you?

**Comment by ninetyninedegrees** [comment]
@Sunnyiscoming @herrehesse @cryptowhizzard hi there.
   
What information do Sunnyiscoming, herrehesse, and cryptowhizzard need to provide? This has been shelved for a long time, and I hope to get the support of the notary

looking forward to your reply.
