### ISSUE TITLE
[DataCap Application] NHGRI-ENCODE

### ISSUE THREAD

**Issue by Hilarylilei** [filecoin-project/filecoin-plus-large-datasets#2161]
### Data Owner Name

ENCODE Data Coordinating Center

### What is your role related to the dataset

Data Preparer

### Data Owner Country/Region

United States

### Data Owner Industry

Life Science / Healthcare

### Website

https://registry.opendata.aws/?search=managedBy:encode%20data%20coordinating%20center

### Social Media

```text
Web: https://www.encodeproject.org/
Twi: https://twitter.com/EncodeDCC
```

### Total amount of DataCap being requested

13PiB

### Expected size of single dataset (one copy)

1.2PiB

### Number of replicas to store

10

### Weekly allocation of DataCap requested

1PiB

### On-chain address for first allocation

f1dm6mztwueypcemeoxkcrw6pey6tamhp4ljgzt6i

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
i'm a data preparer. By a chance I learned about and successfully downloaded this public dataset. After I was introduced to the Fil+ program, I decided to open my first application to store this dataset distributedly.
The goal of ENCODE is to build a comprehensive parts list of functional elements in the human genome, including elements that act at the protein and RNA levels, and regulatory elements that control cells and circumstances in which a gene is active.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
Released and archived ENCODE data
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### If you are a data preparer. What is your location (City and Country)

```text
I locate in HongKong, China.
```

### If you are a data preparer, how will the data be prepared? Please include tooling used and technical details?

```text
Lotus/Boost
```

### Has this dataset been stored on the Filecoin network before? If so, please explain and make the case why you would like to store this dataset again to the network. Provide details on preparation and/or SP distribution.

```text
Maybe I'm the first one who want to store this dataset. If not, it's just a coincidence. It's great that this dataset is being saved by more people around the world.
```

### Please share a sample of the data

```text
aws s3 ls --no-sign-request s3://encode-public/
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Sporadic

### For how long do you plan to keep this dataset stored on Filecoin

Permanently

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, Europe

### How will you be distributing your data to storage providers

HTTP or FTP server, Shipping hard drives, Lotus built-in data transfer

### How do you plan to choose storage providers

Slack, Big Data Exchange, Partners

### If you already have a list of storage providers to work with, fill out their names and provider IDs below

```text
The list of SPs --- before I sumit this application, I look for some SP for storing. They have interest in joining this plan.
 
f0409765|HK
f0102513|HK
f0133486|CN
f0127259|KR
```

### How do you plan to make deals to your storage providers

Boost client, Lotus client, Singularity

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
- Have you prepared enough token for sector pledge?
- Best practice for storing large datasets includes ideally, storing it in 3 or more regions, with 4 or more storage provider operators or owners.You should list Miner ID, Business Entity, Location of sps you will cooperate with.
- Per the https://github.com/filecoin-project/notary-governance/issues/922 for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

This information will be reviewed by Fil+ Governance team to confirm validity and then the application will be triggered for notary review. Let us know if you have any questions.

**Comment by herrehesse** [comment]
@Hilarylilei Hi, appreciate your LDN request. I'd like to address a couple of points:

- Firstly, your request for 13PiB of datacap is concerning since it's coming from a new account without any established reputation or experience.
- Secondly, the dataset you're proposing to store has already been replicated numerous times. Could you clarify how your contribution would enhance the value of the Filecoin network in this case?

**Comment by Hilarylilei** [comment]
Hello @Sunnyiscoming 
I asked SPs for it and they are sure that they have token to seal.
Yes, I know. I've submitted the form. Thank you for confirmation.

**Comment by Hilarylilei** [comment]
@herrehesse Thank you! I think i can have a try as a new part. Maybe others have stored the dataset but they may didn't finish store it. And this is the first time for me to store the data. I can make it store in other regions where others didn't choose, to spread useful data.

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 13PiB

**Expected weekly DataCap usage rate**
> 1PiB

**Client address**
>f1dm6mztwueypcemeoxkcrw6pey6tamhp4ljgzt6i

**Comment by cryptowhizzard** [comment]
This application should not pass #922.

f0409765|HK -> No ip address set on chain. Not verifyable, not eligible for Fil+
f0102513|HK -> No ip address set on chain. Not verifyable, not eligible for Fil+
f0133486|CN -> No ip address set on chain. Not verifyable, not eligible for Fil+
f0127259|KR  -> No ip address set on chain. Not verifyable, not eligible for Fil+

<img width="715" alt="Scherm­afbeelding 2023-08-23 om 21 39 12" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/36404435/63923d91-af3b-429d-9fdd-ff48b2153466">

**Comment by Hilarylilei** [comment]
@cryptowhizzard I'm contacting more SPs when I made this application. Thanks for the note, I won't work with these SPs if it's not a good match! I will turn to other SPs. Can you help sign for me?

**Comment by cryptowhizzard** [comment]
> preparing

Offcourse i won't sign. This application does not meet the rules of 922. - > https://github.com/filecoin-project/notary-governance/issues/922

@filplus-govteam , please interviene.

**Comment by Sunnyiscoming** [comment]
f0409765|HK
f0102513|HK
f0133486|CN
f0127259|KR
f01939387|CN

**Comment by cryptowhizzard** [comment]
f0409765|HK -> Not eligible to participate in Fil+. No IP adress set on chain.
f0102513|HK -> Not eligible to participate in Fil+. No IP adress set on chain.
f0133486|CN -> Not eligible to participate in Fil+. No IP adress set on chain.
f0127259|KR -> Not eligible to participate in Fil+. No IP adress set on chain.
f01939387|CN -> Ok with a warning in #1559 for not proving retrieval.

**Comment by Hilarylilei** [comment]
Keep open

**Comment by Hilarylilei** [comment]
We have changed our plan of SPs to cooperate. f0117211|Guizhou f02368321|Singapore f02232007|Yaan f0428306|Zhejiang Look forward to notary's help!

> @cryptowhizzard I'm contacting more SPs when I made this application. Thanks for the note, I won't work with these SPs if it's not a good match! I will turn to other SPs. Can you help sign for me?

**Comment by Casey-PG** [comment]
Have communicated with this client. Clients are willing to cooperate with community rules to adapt to the plan. Support this round and take a look on next step.

**Comment by Casey-PG** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaj4ckek6rjqzsihvo6s63tkfw3y54fbntmlq45aydsercxyq3bny 
#### Address 
> f1dm6mztwueypcemeoxkcrw6pey6tamhp4ljgzt6i
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f1d4yb3wags3mtddzesxoo63jv7dmlec3bq4yteni
#### Id
> 775fa27f-a412-4601-a307-29a5336341e7
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaj4ckek6rjqzsihvo6s63tkfw3y54fbntmlq45aydsercxyq3bny

**Comment by cryptowhizzard** [comment]
I object against this change. This is not in alignment with the rules set in 922 ( https://github.com/filecoin-project/notary-governance/issues/922 ) for notary due diligence.

"We have changed our plan of SPs to cooperate. f0117211|Guizhou f02368321|Singapore f02232007|Yaan f0428306|Zhejiang Look forward to notary's help!"

These providers are flagged and have been storing garbage data. 

@Hilarylilei  , can you send us a sample .car file of the data you have prepared with a CID that you intend to store in the first round?  You can upload it here -> https://send.datasetcreators.com/      and give us the download link.

**Comment by Hilarylilei** [comment]
Where and how did these SPs be flagged? Please provide evidence.

> I object against this change. This is not in alignment with the rules set in 922 ( [filecoin-project/notary-governance#922](https://github.com/filecoin-project/notary-governance/issues/922) ) for notary due diligence.
> 
> "We have changed our plan of SPs to cooperate. f0117211|Guizhou f02368321|Singapore f02232007|Yaan f0428306|Zhejiang Look forward to notary's help!"
> 
> These providers are flagged and have been storing garbage data.
> 
> @Hilarylilei , can you send us a sample .car file of the data you have prepared with a CID that you intend to store in the first round? You can upload it here -> https://send.datasetcreators.com/ and give us the download link.

**Comment by Hilarylilei** [comment]
@cryptowhizzard Also, who flagged these SPs? Please provide evidence too.

**Comment by cryptowhizzard** [comment]
@Hilarylilei 

https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/2057  for f02368321.

f0117211 does not support retrieval. Check the Protocol labs retrieval bot here:
![Scherm­afbeelding 2023-09-18 om 14 32 39](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/36404435/c8bc1e04-390d-4e2b-81fe-9f9d0d46e7c9)

https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1608 for f02232007

https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/2057 for f0428306 including datacap removal.

**Comment by Hilarylilei** [comment]
Sure

**Comment by Hilarylilei** [comment]
Yes

**Comment by AthSmith** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec2y5xzs452bz5unykey2alwnoffowymjg5iiqxrm2tpro7hwrvh6 
#### Address 
> f1dm6mztwueypcemeoxkcrw6pey6tamhp4ljgzt6i
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f1vxbqrf7rfum3n6m5u6eb4re6xj7amvsaqnzu64y
#### Id
> 775fa27f-a412-4601-a307-29a5336341e7
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec2y5xzs452bz5unykey2alwnoffowymjg5iiqxrm2tpro7hwrvh6

**Comment by herrehesse** [comment]
@raghavrmadya @galen-mcandrew @dkkapur @simonkim0515 @Kevin-FF-USA 

Can we remove @Casey-PG & @AthSmith after their millionth abusive signature or shall we wait a bit longer?

**Comment by Hilarylilei** [comment]
@herrehesse What's the meaning of abusive signature? You should be responsible for your words. Here is not your backyard.

@raghavrmadya @galen-mcandrew @dkkapur @simonkim0515 @Kevin-FF-USA

> @raghavrmadya @galen-mcandrew @dkkapur @simonkim0515 @Kevin-FF-USA
> 
> Can we remove @Casey-PG & @AthSmith after their millionth abusive signature or shall we wait a bit longer?

**Comment by kevzak** [comment]
Who are the legit SPs @Hilarylilei ? Please list here SP entity, location, miner ID. Closing until updated.

**Comment by kevzak** [comment]
post them here please on the application for notaries to see @Hilarylilei

**Comment by Hilarylilei** [comment]
@Kevin-FF-USA 
f0117211|Guizhou|Emma
f02368321|Singapore|CarlSun
f02232007|Yaan|PeterW
f0428306|Zhejiang|Cindy
f01879772|HongKong|Ronald
Actually SPs do not want to public thier specific information. So I choose to DM you first.

**Comment by kevzak** [comment]
checker:manualTrigger

**Comment by kevzak** [comment]
[f01879772](https://filfox.info/en/address/f01879772) - taking all deals so far @Hilarylilei - please start distributing on next allocation. Ensure this list below matches your SPs

f0117211|Guizhou|Emma
f02368321|Singapore|CarlSun
f02232007|Yaan|PeterW
f0428306|Zhejiang|Cindy
f01879772|HongKong|Ronald

**Comment by Hilarylilei** [comment]
Yes, please open and we'll begin the next allocation.

**Comment by EVS2024** [comment]
checker:manualTrigger

**Comment by PluskitOfficial** [comment]
checker:manualTrigger

**Comment by PluskitOfficial** [comment]
Seems all well.  Willing to sign this round.

**Comment by PluskitOfficial** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebmi6cfjj6kwsq3p76kbks3nowbnqijykjwv6njla5frubl5jolqc 
#### Address 
> f1dm6mztwueypcemeoxkcrw6pey6tamhp4ljgzt6i
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f1tgnlhtcmhwipfm7thsftxhn5k52velyjlazpvka
#### Id
> 6a006acd-0314-4ba0-88bb-547724aa5521
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebmi6cfjj6kwsq3p76kbks3nowbnqijykjwv6njla5frubl5jolqc

**Comment by Destore2023** [comment]
Looks good, keep it up!

**Comment by Destore2023** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacednzlsvl7wr7ejnrdkba36obsugph44k4knwepzbspmbs5tubxepq 
#### Address 
> f1dm6mztwueypcemeoxkcrw6pey6tamhp4ljgzt6i
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f1yh6q3nmsg7i2sys7f7dexcuajgoweudcqj2chfi
#### Id
> 6a006acd-0314-4ba0-88bb-547724aa5521
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacednzlsvl7wr7ejnrdkba36obsugph44k4knwepzbspmbs5tubxepq

**Comment by Hilarylilei** [comment]
SP list update
f02816097|steve  f02234029|Wendy  f01879772|Ronald  f01084913|Bill  f02196792|Tyler

**Comment by Filplus-govteam** [comment]
SPs taking deals
f02234029 | Hong Kong, Central and Western, HKBIH-Global Internet Harbor | 127.50 TiB | 25.52% | 127.50 TiB | 0.00%
f01879772 | Hong Kong, Central and Western, HKBIH-Global Internet Harbor | 95.81 TiB | 19.18% | 95.81 TiB | 0.00%
f01084913 | Hong Kong, Central and Western, HKChina Unicom Global | 87.91 TiB | 17.59% | 87.91 TiB | 0.00%
f02816097 | Shenzhen, Guangdong, CNCHINANET-BACKBONE | 129.88 TiB | 25.99% | 129.88 TiB | 0.00%
f02196792 | Hong Kong, Central and Western, HKHK Cable TV Ltd | 58.56 TiB | 11.72% | 58.56 TiB | 0.00%

Please provide proof these are not the same entity @Hilarylilei and provide entity name. Closing until updated
