### ISSUE TITLE
[DataCap Application]jqcultural

### ISSUE THREAD

**Issue by Brynad** [filecoin-project/filecoin-plus-large-datasets#2162]
### Data Owner Name

Brynad

### What is your role related to the dataset

Data Preparer

### Data Owner Country/Region

China

### Data Owner Industry

Arts & Recreation

### Website

jqcultural.com

### Social Media

```text
jqcultural.com
```

### Total amount of DataCap being requested

3PiB

### Expected size of single dataset (one copy)

300T

### Number of replicas to store

10

### Weekly allocation of DataCap requested

300TiB

### On-chain address for first allocation

f1mcdzzrtv63iup2mrf3xiub3ybgwp3s7nrdbiesq

### Data Type of Application

Public, Open Commercial/Enterprise

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Shenzhen Giant Culture Development Co., Ltd. is the first cultural communication company in Longgang that integrates performing arts planning and enterprise operation planning, so as to achieve corporate publicity and momentum. The company undertakes the planning and execution of various public relations activities; wedding etiquette planning; advertising design, production, agency, and release; planning and organizing various theme activities, exhibitions, and press conferences; planning and organizing corporate image and marketing activities; planning and organizing large, medium and small performing arts activities; Model artist training, packaging, training; national celebrity agency, provision of Chinese and foreign art models and other services.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
Some shots from nature, mountains and seas and rivers etc.
```

### Where was the data currently stored in this dataset sourced from

Google Cloud

### If you are a data preparer. What is your location (City and Country)

```text
Shenzhen, China
```

### If you are a data preparer, how will the data be prepared? Please include tooling used and technical details?

```text
We have our own storage facility
```

### Please share a sample of the data

```text
https://drive.google.com/file/d/1tOU9FUxG_spM5YpA8HBrd69C4bTzR6IM/view?usp=sharing
https://drive.google.com/file/d/1LE9748nLzSZXsSpgKprBj_7zQvXsT1iH/view?usp=sharing
https://drive.google.com/file/d/1PL1i3wNHN9F8-Z7aiiLau2KHMlkrbFt0/view?usp=sharing
https://drive.google.com/file/d/1iJ4O1uiogEUqdk4lDSPmWbUiO9S3HCsu/view?usp=sharing
https://drive.google.com/file/d/1dljMqxIZ-8HuHKyZ7C1pvyjc_B57ciRH/view?usp=sharing
https://drive.google.com/file/d/1oYrCGhBnX577coYys5zJROe0Nac0EdcJ/view?usp=sharing
https://drive.google.com/file/d/1LidAYFGrV4NNBsU3cRgW6f-P9aiZ30IT/view?usp=sharing
https://drive.google.com/file/d/1wJ2GboQs6kEO8OHMwRiBiwMMwDmGGuYl/view?usp=sharing
https://drive.google.com/file/d/16a9vYsdkwtG0BiqRH95I_iCs36zLhNLk/view?usp=sharing
https://drive.google.com/file/d/1Jnb6En0dodVXGUiAcg_Cq96tAWJLYz1h/view?usp=sharing
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Monthly

### For how long do you plan to keep this dataset stored on Filecoin

1.5 to 2 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, South America

### How will you be distributing your data to storage providers

HTTP or FTP server, Shipping hard drives

### How do you plan to choose storage providers

Slack, Partners

### If you already have a list of storage providers to work with, fill out their names and provider IDs below

```text
f02092901  ShangHai
f01776669  Chengdu
f0746542   Korea
f02204960  GuangZhou
f02337010  Californial
```

### How do you plan to make deals to your storage providers

Boost client, Lotus client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by herrehesse** [comment]
Hello there! I've noticed that you're a new client seeking a substantial volume of DC (3PiB). Could you provide us with some insight into your decision to not consider building your reputation with a smaller quantity initially? Appreciate it!

**Comment by Sunnyiscoming** [comment]
Where are these data from? Are you authorized to store these data as public data on the Filecoin network?
Could you send an email to filplus-app-review@fil.org with your official domain in order to confirm your identity? Email name should includes the issue id #2162.
- Per the https://github.com/filecoin-project/notary-governance/issues/922 for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

This information will be reviewed by Fil+ Governance team to confirm validity and then the application will be triggered for notary review. Let us know if you have any questions.

**Comment by Brynad** [comment]
> 嗨，你好！我注意到您是一位寻求大量 DC （3PiB） 的新客户。您能否向我们提供一些见解，说明您最初不考虑以较小的数量建立声誉的决定？欣赏它！
The reason why we don't choose a smaller number is because 3P is relatively small data for us. I read a lot of applications, and most of the data applications are much more than 3P. I read the rules and said that it is recommended to start from Apply within 5P

**Comment by Brynad** [comment]
1. The data we show can be uploaded to public data and stored on the Filecoin network, so you don’t have to worry about it
2. The email has been sent, pay attention to check it
3. The registration form has been filled

**Comment by Brynad** [comment]
> 这些数据从何而来？您是否有权将这些数据作为公共数据存储在Filecoin网络上？你能用你的官方域名[向 filplus-app-review@fil.org](mailto:filplus-app-review@fil.org) 发送电子邮件以确认你的身份吗？电子邮件名称应包含问题 ID #2162。
> 
> * 根据[修改：公共开放数据集应用程序流公证治理所需的更改#922](https://github.com/filecoin-project/notary-governance/issues/922)对于开放、公共数据集申请人，请填写以下 [Fil+ 注册表](https://form.jotform.com/231862753015656)以表明您自己是申请人，并请添加与您合作的 SP 实体的联系信息以存储数据副本。
> 
> 此信息将由 Fil+ 治理团队审核以确认有效性，然后触发申请进行公证审查。如果您有任何问题，请告诉我们。

1. The data we show can be uploaded to public data and stored on the Filecoin network, so you don’t have to worry about it
2. The email has been sent, pay attention to check it
3. The registration form has been filled

**Comment by Filplus-govteam** [comment]
Confirming we have received the following SP entities:
f02092901  ShangHai
f01776669  Chengdu
f0746542   Korea
f02204960  GuangZhou
f02337010  California

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 3PiB

**Expected weekly DataCap usage rate**
> 300TiB

**Client address**
>f1mcdzzrtv63iup2mrf3xiub3ybgwp3s7nrdbiesq

**Comment by cryptowhizzard** [comment]
f01776669 is not open for retrieval ( Connection refused )
f02204960 is not open for retrieval ( Connection refused )
f02337010 is not a miner address but a wallet address

**Comment by Brynad** [comment]
> f01776669 is not open for retrieval ( Connection refused ) f02204960 is not open for retrieval ( Connection refused ) f02337010 is not a miner address but a wallet address

Thank you for your feedback first
I haven't been granted a data cap yet.
These SPs have not yet begun to seal, so their IPs do not need to be exposed.
I'll let them know when they start sealing.
After they start storing data, you can expect our reports. Thank you for your feedback first
I haven't been granted a data cap yet.
These SPs have not yet begun to seal, so their IPs do not need to be exposed.
I'll let them know when they start sealing.
After they start storing data, you can expect our reports.

**Comment by Brynad** [comment]
> f01776669 is not open for retrieval ( Connection refused ) f02204960 is not open for retrieval ( Connection refused ) f02337010 is not a miner address but a wallet address

Thank you for your feedback
First of all, I haven't been granted a data cap yet.
Because these SPs have not yet begun to seal, they do not need to expose their IP.
I notify them when they start sealing, and you can expect our reports after they start storing data.

**Comment by cryptowhizzard** [comment]
> > f01776669 is not open for retrieval ( Connection refused ) f02204960 is not open for retrieval ( Connection refused ) f02337010 is not a miner address but a wallet address
> 
> Thank you for your feedback First of all, I haven't been granted a data cap yet. Because these SPs have not yet begun to seal, they do not need to expose their IP. I notify them when they start sealing, and you can expect our reports after they start storing data.

Hello,

They really do need to expose their IP and be reachable.

A- to verify their location
B- to verify that they are able to serve retrievals.

**Comment by Brynad** [comment]
> > > f01776669 is not open for retrieval ( Connection refused ) f02204960 is not open for retrieval ( Connection refused ) f02337010 is not a miner address but a wallet address
> > 
> > 
> > Thank you for your feedback First of all, I haven't been granted a data cap yet. Because these SPs have not yet begun to seal, they do not need to expose their IP. I notify them when they start sealing, and you can expect our reports after they start storing data.
> 
> Hello,
> 
> They really do need to expose their IP and be reachable.
> 
> A- to verify their location B- to verify that they are able to serve retrievals.

Hello, I contacted the miner, and they replied to me that the SP is still in preparation, and the IP address will be published after the preparation is completed, of course, it will support retrieval.

**Comment by cryptowhizzard** [comment]
Well,

As long as they are preparing there is no reason to grant you datacap since they are not ready to store.
Let us know when they are ready please so we can check.

**Comment by zcfil** [comment]
If ready, please list the SPs and regions that you have previously collaborated with.

**Comment by Brynad** [comment]
> f02092901  ShangHai
> f01776669  Chengdu
> f0746542   Korea
> f02204960  GuangZhou
> f02337010  Californial

**Comment by Brynad** [comment]
> If ready, please list the SPs and regions that you have previously collaborated with.

f02092901  ShangHai
f01776669  Chengdu
f0746542   Korea
f02204960  GuangZhou
f02337010  Californial

**Comment by herrehesse** [comment]
f02092901 - Found self-dealing on 1995
f01776669 - CC miner
f0746542 - CC miner
f02204960 - This ID is linked to multiple self-dealing attempts
f02337010 - This ID has been linked to a multitude of abusive applications

Can you explain why you want to store on miners with such a poor reputation?

**Comment by Brynad** [comment]
> f02092901 - Found self-dealing on 1995 f01776669 - CC miner f0746542 - CC miner f02204960 - This ID is linked to multiple self-dealing attempts f02337010 - This ID has been linked to a multitude of abusive applications
> 
> Can you explain why you want to store on miners with such a poor reputation?

I'll be checking on them, still making preparations and I'm still looking for other miners as well

**Comment by Brynad** [comment]
> The app hasn't received any response in the last 10 days. This issue will be marked as "Obsolete" and will be closed within 4 days. If you want to leave this app open, leave a comment.
> 
> --The stale bot commented.

Keep it open

**Comment by Brynad** [comment]
Keep it open

**Comment by Brynad** [comment]
keep it open

**Comment by Brynad** [comment]
> This application has not seen any responses in the last 10 days. This issue will be marked with Stale label and will be closed in 4 days. Comment if you want to keep this application open.
> 
> -- Commented by Stale Bot.

keep it open

**Comment by Brynad** [comment]
> This application has not seen any responses in the last 10 days. This issue will be marked with Stale label and will be closed in 4 days. Comment if you want to keep this application open.
> 
> -- Commented by Stale Bot.

keep it open

**Comment by Brynad** [comment]
keep it open

**Comment by Filplus-govteam** [comment]
Closing until clear SP ID list, entity and location is provided
