### ISSUE TITLE
[DataCap Application] Naval Research Laboratory: Ocean Dynamics and Prediction Branch

### ISSUE THREAD

**Issue by hyunmoon** [filecoin-project/filecoin-plus-large-datasets#2164]
### Data Owner Name
Naval Research Laboratory: Ocean Dynamics and Prediction Branch

### What is your role related to the dataset
Data Preparer

### Data Owner Country/Region
United States

### Data Owner Industry
Government

### Website
[https://www.hycom.org/dataserver/gofs-3pt1/reanalysis](https://www.hycom.org/dataserver/gofs-3pt1/reanalysis)

### Social Media
[at]USNRL (Twitter)

### Total amount of DataCap being requested
1.36 PiB

### Expected size of single dataset (one copy)
278.1 TiB

### Number of replicas to store
5

### Weekly allocation of DataCap requested
150 TiB

### On-chain address for first allocation
f1bw37oiqarwddlib4bt7elzwaskql63ffd7zmvki

### Data Type of Application
Public, Open Dataset (Research/Non-Profit)

### Custom multisig
- [ ] Use Custom Multisig

### Identifier
n/a

### Share a brief history of your project and organization
https://www.simpleipfs.com

### Is this project associated with other projects/ecosystem stakeholders?
No

### If answered yes, what are the other projects/ecosystem stakeholders
n/a

### Describe the data being stored onto Filecoin
https://registry.opendata.aws/hycom-gofs-3pt1-reanalysis
s3://hycom-gofs-3pt1-reanalysis

Global Ocean Forecasting System (GOFS) 3.1 output on the GLBv0.08 grid. The resolution is 0.08° resolution between 40°S and 40°N, 0.04° poleward of these latitudes. The temportal frequenct is 3 hourly. This data was created by the Naval Research Laboratory: Ocean Dynamics and Prediction Branch.

### Where was the data currently stored in this dataset sourced from
AWS Cloud

### If you answered "Other" in the previous question, enter the details here
n/a

### If you are a data preparer, what is your location (City and Country)
Seoul, South Korea

### If you are a data preparer, how will the data be prepared? Please include tooling used and technical details?
Singularity v2

### If you are not preparing the data, who will prepare the data?  (Provide name and business)
n/a

### Has this dataset been stored on the Filecoin network before? If so, please explain and make the case why you would like to store this dataset again to the network. Provide details on preparation and/or SP distribution.
n/a

### Please share a sample of the data
```
aws s3 ls --summarize --human-readable --recursive --no-sign-request s3://hycom-gofs-3pt1-reanalysis
...
2020-08-18 20:45:19    4.5 GiB 2015/hycom_GLBv0.08_539_2015123012_t009.nc
2020-08-18 20:45:20    4.5 GiB 2015/hycom_GLBv0.08_539_2015123012_t012.nc
2020-08-18 20:46:10    4.5 GiB 2015/hycom_GLBv0.08_539_2015123012_t015.nc
2020-08-18 20:49:46    4.5 GiB 2015/hycom_GLBv0.08_539_2015123012_t018.nc
2020-08-18 20:56:02    4.5 GiB 2015/hycom_GLBv0.08_539_2015123012_t021.nc

Total Objects: 63342
Total Size: 278.1 TiB
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network
Yes

### If you chose not to confirm, what was the reason
n/a

### What is the expected retrieval frequency for this data
Yearly

### For how long do you plan to keep this dataset stored on Filecoin
1 to 1.5 years

### In which geographies do you plan on making storage deals
Asia other than Greater China, North America, Europe

### How will you be distributing your data to storage providers
HTTP or FTP server

### How do you plan to choose SP
Slack

### If you answered "Others" in the previous question, what is the tool or platform you plan to use
n/a

### If you already have a list of storage providers to work with, fill out their names and provider IDs below
Asia other than Greater China: f01697248 (Siheung-si, South Korea)
North America: f01985775 (Dallas, USA)
Middle East: f01907556 (Dubai, UAE)
Greater China: f01939377 (Chengdu, China)
North America: f02002141 (Dallas, USA)

### How do you plan to make deals to your storage providers
Boost client

### If you answered "Others/custom tool" in the previous question, enter the details here
n/a

### Can you confirm that you will follow the Fil+ guideline
Yes

_Application created via [filplus.storage](https://filplus.storage)_

**Comment by Sunnyiscoming** [comment]
- Have you prepared enough token for sector pledge?
- Best practice for storing large datasets includes ideally, storing it in 3 or more regions, with 4 or more storage provider operators or owners.You should list Miner ID, Business Entity, Location of sps you will cooperate with.
- Per the https://github.com/filecoin-project/notary-governance/issues/922 for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

This information will be reviewed by Fil+ Governance team to confirm validity and then the application will be triggered for notary review. Let us know if you have any questions.

**Comment by hyunmoon** [comment]
> * Have you prepared enough token for sector pledge?

Yes, I have

> * Best practice for storing large datasets includes ideally, storing it in 3 or more regions, with 4 or more storage provider operators or owners.You should list Miner ID, Business Entity, Location of sps you will cooperate with.

Understood. I'm still looking for the rest of the required SPs.

> * Per the [Modification: Changes required to public open dataset application flow notary-governance#922](https://github.com/filecoin-project/notary-governance/issues/922) for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.
> 

The form has been submitted.

**Comment by Filplus-govteam** [comment]
Hello - please let us know when you have at least 4 SP entities per the guidelines of distributed storage.

Currently received:
f01697248 SIMPLE IPFS Inc. Asia excluding greater China
f01985775 GREATER HEAT North America

**Comment by zcfil** [comment]
Can you explain the source of your data? What is your relationship with the organization?

**Comment by hyunmoon** [comment]
EDIT:
Added the 3rd SP (f01907556)
I will re-submit the registration form once I find the 4th.

> Can you explain the source of your data? What is your relationship with the organization?

The source of data is Amazon AWS Public Data Sets.

SIMPLE IPFS: My own company.
GREATER HEAT: No relationship. I reached out by slack DM to ask if they can store the dataset.
PRIDE GROUP: No relationship. They reached out to me after reading my post on fil-deal-market slack channel.

**Comment by zcfil** [comment]
Based on some of the issues raised by the notary public mentioned above, I will support this round of review and continue to follow up in the future. Please store enough copies according to regulations

**Comment by Sunnyiscoming** [comment]
Any update here?

**Comment by hyunmoon** [comment]
> Any update here?

Yes, I added the 4th SP today and I'm looking for the 5th.

**Comment by hyunmoon** [comment]
Re-submitted the Fil+ registration form with all 5 SPs.

**Comment by zcfil** [comment]
Okay, we will support this time. Please follow the rules and we will continue to follow up

**Comment by zcfil** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedq5av2lsfuclj2r4xzza6ct3jkfb7c2s4um7t22vkzdc6t4r5jhu 
#### Address 
> f1bw37oiqarwddlib4bt7elzwaskql63ffd7zmvki
#### Datacap Allocated
> 69.63TiB
#### Signer Address
> f1cjzbiy5xd4ehera4wmbz63pd5ku4oo7g52cldga
#### Id
> ce7e83f9-90b5-4e67-9e9b-86676853d1de
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedq5av2lsfuclj2r4xzza6ct3jkfb7c2s4um7t22vkzdc6t4r5jhu

**Comment by jomozz** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaxcb74sis3dni5lg32vyqp5etir3lul2v46ii5vvc74h4hhvjj6i 
#### Address 
> f1bw37oiqarwddlib4bt7elzwaskql63ffd7zmvki
#### Datacap Allocated
> 69.63TiB
#### Signer Address
> f1qpdwt2f2fse74nl5wi27uk5jcyqqqyil47yqt7i
#### Id
> ce7e83f9-90b5-4e67-9e9b-86676853d1de
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaxcb74sis3dni5lg32vyqp5etir3lul2v46ii5vvc74h4hhvjj6i

**Comment by hyunmoon** [comment]
Almost finished packing. Will distribute the CAR files to SPs.

**Comment by hyunmoon** [comment]
It's in use. Still distributing the CAR files.

**Comment by hyunmoon** [comment]
Still distributing the CAR files. It's taking longer than I thought.

**Comment by hyunmoon** [comment]
still distributing car files

**Comment by hyunmoon** [comment]
Still distributing the CAR files.

**Comment by hyunmoon** [comment]
Still distributing the CAR files.

**Comment by hyunmoon** [comment]
Still distributing the CAR files.

**Comment by herrehesse** [comment]
checker:manualTrigger

**Comment by herrehesse** [comment]
@hyunmoon "Still distributing the CAR files." ?
All files stored on 1 SP in 1 region?

**Comment by hyunmoon** [comment]
![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/2242149/7fb67319-4e3c-4d04-8434-5d3a55d62164)
I'm not sure where the 'more than 90%' came from.
I was given 69.63TiB, and I've only used 18.63TiB of it.
As for the distribution, I'm totally in the dark.
I shared my links with the SPs, and it looked like they started downloading, but they haven’t gotten back to me yet.

**Comment by kevzak** [comment]
Are these your confirm SPs @hyunmoon ?


f01697248 | Henry | Asia other than Greater China | 
f01985775 | GREATER HEAT | North America | 
f01907556 |  PRIDE GROUP | Middle East |
f01939377 |  LUFANG | Greater China |
f02002141 | | GREATER HEAT | North America |

**Comment by hyunmoon** [comment]
Yes, Greater Heat, Lufang, and Pride Group were pre-arranged SPs.
But none of them seem eager to start sealing the dataset.
I will ping them again and hear what they say.
