### ISSUE TITLE
[DataCap Application] simban

### ISSUE THREAD

**Issue by io10xx** [filecoin-project/filecoin-plus-large-datasets#2165]
### Data Owner Name

simban

### What is your role related to the dataset

Storage provider filling out application on behalf of the data owner

### Data Owner Country/Region

Singapore

### Data Owner Industry

Web3 / Crypto

### Website

https://simban.io/

### Social Media

```text
https://www.facebook.com/simban.io
https://twitter.com/SimbanMetaverse
```

### Total amount of DataCap being requested

5PiB

### Expected size of single dataset (one copy)

500TiB

### Number of replicas to store

5

### Weekly allocation of DataCap requested

1PiB

### On-chain address for first allocation

f1rtngbskg6lfpijtao6yrgteg334tv3i34swbj4i

### Data Type of Application

Public, Open Commercial/Enterprise

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Simban is a new travel-style metaverse with never-before-seen integrated digital twins of real-world and fictional planets. We are the first galaxy to offer °∞travel and earn°± opportunities. Players in our hyper-realistic metaverse encounter visually stunning earth locations as well as an open virtual galaxy filled with quests and mini-games.The company is located in New York.

One of our distinguishing features is that we work with digital twins of real-world locations and virtual mythical worlds, allowing us to incorporate IRL experiences that have never been attempted before.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
3D models, audio and video, documents, etc.
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### If you are a data preparer. What is your location (Country/Region)

Viet Nam

### If you are a data preparer, how will the data be prepared? Please include tooling used and technical details?

```text
Using Qiniu software system to manage storage system and cache, and using lotus client for transaction storage.
```

### Please share a sample of the data

```text
https://drive.google.com/drive/folders/1iliRDp3nz-lB0lviR2coap2qC2MImkRA
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Monthly

### For how long do you plan to keep this dataset stored on Filecoin

2 to 3 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, Europe

### How will you be distributing your data to storage providers

Lotus built-in data transfer

### How do you plan to choose storage providers

Partners

### If you already have a list of storage providers to work with, fill out their names and provider IDs below

```text
f01850726  | Wuma Cloud       | Hanoi, Vietnam                      | qinqiyuse@hotmail.com
f02274570  | Anxin Network    | Hong Kong                           | lupiruwi9@outlook.com
f01928022  | F3               | Los Angeles, California, US         | F3jialiang@outlook.com
f0675459   | Nov tech         | Shenzhen, Guangdong, China.         | movehx@hotmail.com
f01926792  | Mk storage       | Hanoi, Vietnam                      | peter1195@proton.me
```

### How do you plan to make deals to your storage providers

Lotus client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by io10xx** [comment]
1  The data comes from the business scenario. I can use the email with the official domain suffix to email you to prove it.
2  Yes, the SPs have prepared enough FIL tokens.
3  I confirm that I will abide by the rules of FIL+.

**Comment by Sunnyiscoming** [comment]
You should list Miner ID, Business Entity, Location of sps on the issue.
Please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656).

**Comment by io10xx** [comment]
> 

The form has been filled out. 
Thank you!

**Comment by herrehesse** [comment]
Hello @io10xx welcome to FIL+!

Allocating 5 PiB to a new account without an established reputation might not be in the best interest of our community.
I'd suggest running a demo with 10-100T before requesting 5000T from the community. Regrettably, the notary system has its flaws, with some taking advantage to inappropriately endorse everything.

You should list Miner ID, Business Entity, Location of sps on the issue as well.

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 5PiB

**Expected weekly DataCap usage rate**
> 1PiB

**Client address**
>f1rtngbskg6lfpijtao6yrgteg334tv3i34swbj4i

**Comment by Sunnyiscoming** [comment]
f01850726 Wuma Cloud Hanoi,Vietnam
f02274570 Anxin Network,Hong Kong 
f01928022 F3, US
f0675459 Nov tech, CN
f01926792 Mk storage, Vietnam

**Comment by herrehesse** [comment]
f02274570 - Selfdealing completely application 1418
f01928022 - CID abuse & Selfdealing many applications
f01926792 - CID abuse & Selfdealing many applications

Also are the business names you stated are wrong, we got many names under these so called "miners" but its all the same entity mostly.

@Sunnyiscoming You need access to our tool so you can check yourself?

**Comment by io10xx** [comment]
This is the part of SP that we contacted.
Thank you for telling me they might have a problem.
Now I will actively look for more SP.

**Comment by io10xx** [comment]
I will submit a new SP in one or two days.

**Comment by io10xx** [comment]
Negotiated these SP:
F090999
F091987
F091313
F094311
F093856 
F091936
F091099
F093961
F0187556

**Comment by ipfscn** [comment]
Could you send an email to [filplus-app-review@fil.org](mailto:filplus-app-review@fil.org) with your official domain in order to confirm your identity? Email name should includes the issue id https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/2165

**Comment by io10xx** [comment]
> Could you send an email to [filplus-app-review@fil.org](mailto:filplus-app-review@fil.org) with your official domain in order to confirm your identity? Email name should includes the issue id #2165
![WechatIMG694](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/117383350/1b4f8875-e172-476c-8c83-35f05ab588b7)

**Comment by io10xx** [comment]
The email has been sent.
Thank you！

**Comment by SuperChaiChai** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceain5c5ti242ulhgrgjfw2eqhdohg7qtbj333xy4nq4ynfomdv63u 
#### Address 
> f1rtngbskg6lfpijtao6yrgteg334tv3i34swbj4i
#### Datacap Allocated
> 256.00TiB
#### Signer Address
> f12mckci3omexgzoeosjvstcfxfe4vqw7owdia3da
#### Id
> 22c3f9ab-fe23-4c2c-843b-19e00cf921bc
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceain5c5ti242ulhgrgjfw2eqhdohg7qtbj333xy4nq4ynfomdv63u

**Comment by ipfscn** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedbvl5izzjz36ziyisdzl24uyvfo4kjhqvqwho4xiv35popmle75y 
#### Address 
> f1rtngbskg6lfpijtao6yrgteg334tv3i34swbj4i
#### Datacap Allocated
> 256.00TiB
#### Signer Address
> f1j4n74chme7whbz3yls4a7ixqewb6dijypqg2a3a
#### Id
> 22c3f9ab-fe23-4c2c-843b-19e00cf921bc
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedbvl5izzjz36ziyisdzl24uyvfo4kjhqvqwho4xiv35popmle75y

**Comment by sxxfuture-official** [comment]
checker:manualTrigger

**Comment by sxxfuture-official** [comment]
All retrieval success ratios are below 1%， @io10xx you should supervise the corresponding SP to resolve this problem as soon as possible

**Comment by io10xx** [comment]
Ok, I've been urging SP to do a good job of technical maintenance.

**Comment by io10xx** [comment]
checker:manualTrigger

**Comment by io10xx** [comment]
checker:manualTrigger

**Comment by io10xx** [comment]
checker:manualTrigger

**Comment by io10xx** [comment]
checker:manualTrigger

**Comment by io10xx** [comment]
checker:manualTrigger

**Comment by sxxfuture-official** [comment]
The retrieval rate has improved significantly and we hope to continue to improve.

**Comment by sxxfuture-official** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaqtdgkjxojjmn24xtzegkxlxk3cdytweaa6qghxwxdrbkz2cb6i4 
#### Address 
> f1rtngbskg6lfpijtao6yrgteg334tv3i34swbj4i
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f1foiomqlmoshpuxm6aie4xysffqezkjnokgwcecq
#### Id
> 9ef520a8-40fb-458b-aaf6-7f31a7822186
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaqtdgkjxojjmn24xtzegkxlxk3cdytweaa6qghxwxdrbkz2cb6i4

**Comment by AlanGreaterheat** [comment]
checker:manualTrigger

**Comment by AlanGreaterheat** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedq4bzht6ir3mi35d6v6z7ldhnumwg4btwtkye6hw7hbkb5yqkxkc 
#### Address 
> f1rtngbskg6lfpijtao6yrgteg334tv3i34swbj4i
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f1pnmzlxj7cfeo2v6oj5nco46hkg2l46wj7o4xxui
#### Id
> 9ef520a8-40fb-458b-aaf6-7f31a7822186
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedq4bzht6ir3mi35d6v6z7ldhnumwg4btwtkye6hw7hbkb5yqkxkc

**Comment by io10xx** [comment]
checker:manualTrigger

**Comment by io10xx** [comment]
checker:manualTrigger

**Comment by woshidama323** [comment]
checker:manualTrigger

**Comment by woshidama323** [comment]
LGTM , Will support

**Comment by woshidama323** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecyn24ae35l3rautxdrugm3xievttip75o25lv6yxau56xbq62xue 
#### Address 
> f1rtngbskg6lfpijtao6yrgteg334tv3i34swbj4i
#### Datacap Allocated
> 1.00PiB
#### Signer Address
> f12tk3adljauwnd3hjbigpfxb7b7gdlj63p6afwtq
#### Id
> d5fdea18-c064-4411-bb0a-1afb594823fe
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecyn24ae35l3rautxdrugm3xievttip75o25lv6yxau56xbq62xue

**Comment by herrehesse** [comment]
checker:manualTrigger

**Comment by herrehesse** [comment]
@DaYouGroup why do you sign? ALL distribution is in the same region, against the rules.

**Comment by io10xx** [comment]
> @DaYouGroup why do you sign? ALL distribution is in the same region, against the rules.

Thank you for your supervision!
This problem will be solved step by step in the subsequent packaging process!

**Comment by herrehesse** [comment]
Yeah sure buddy

**Comment by kevzak** [comment]
SPs listed upfront:
f01850726 Wuma Cloud Hanoi,Vietnam
f02274570 Anxin Network,Hong Kong
f01928022 F3, US
f0675459 Nov tech, CN
f01926792 Mk storage, Vietnam

SPs taking deals
f093393 | Shenzhen, Guangdong, CNChina Mobile Communications Group Co., Ltd. | 250.28 TiB | 20.52% | 250.28 TiB | 0.00%
f093961 | Shenzhen, Guangdong, CNChina Mobile Communications Group Co., Ltd. | 243.88 TiB | 19.99% | 243.88 TiB | 0.00%
f090888 | Qingdao, Shandong, CNCHINANET-BACKBONE | 266.56 TiB | 21.85% | 266.56 TiB | 0.00%
f092229 | Qingdao, Shandong, CNCHINANET-BACKBONE | 254.78 TiB | 20.89% | 254.78 TiB | 0.00%
f0675459 | Shenzhen, Guangdong, CNCHINANET-BACKBONE | 58.06 TiB | 4.76% | 57.97 TiB | 0.16%
f0478837 | Zhangzhou, Fujian, CNCHINANET-BACKBONE | 6.69 TiB | 0.55% | 6.69 TiB | 0.00%
f0495421 | Zhangzhou, Fujian, CNCHINANET-BACKBONE | 4.34 TiB | 0.36% | 4.31 TiB | 0.72%
f02636860 | Hong Kong, Central and Western, HKHKBN Enterprise Solutions HK Limited | 111.61 TiB | 9.15% | 111.61 TiB | 0.00%
f02810687new | Hong Kong, Central and Western, HKHKBN Enterprise Solutions HK Limited | 23.69 TiB | 1.94% | 23.69 TiB | 0.00%


Not one SP matches, closing
