### ISSUE TITLE
[DataCap Application] A-Speed Technology

### ISSUE THREAD

**Issue by speed0211** [filecoin-project/filecoin-plus-large-datasets#2166]
### Data Owner Name
A-Speed Technology

### What is your role related to the dataset
Dataset Owner

### Data Owner Country/Region
Hong Kong

### Data Owner Industry
IT & Technology Services

### Website
[https://www.a-speed.net/](https://www.a-speed.net/)

### Social Media
N/A (we do not have social media accounts.)

### Total amount of DataCap being requested
5 PiB

### Expected size of single dataset (one copy)
500 TiB

### Number of replicas to store
10

### Weekly allocation of DataCap requested
200 TiB

### On-chain address for first allocation
f1tvhaycpg7uiy6mqh7g7adc44ahuzgsg7xiabs4i

### Data Type of Application
Private Commercial/Enterprise

### Custom multisig
- [x] Use Custom Multisig

### Identifier
efil

### Share a brief history of your project and organization
Founded in 2012, A-SPEED headquartered in Singapore, regional offices in India, HK and growing network across the region including Asia, Pacific, Europe and USA.
A-Speed Technology is innovative digital transformation solutions, services and Product Company provides solutions to our respective clients and partners. We provide cloud computing services, Cloud strategy and business case development, Cloud architecture, Design & Implementation, Big data analytics solutions, OpenStack Private Cloud Platform, e-Commerce and m-Commerce solutions. We are focused on our clients business outcome and agile best practices, provide comprehensive solutions and services for businesses from small, medium & large.

### Is this project associated with other projects/ecosystem stakeholders?
No

### If answered yes, what are the other projects/ecosystem stakeholders
n/a

### Describe the data being stored onto Filecoin
The Aspeed platform has a rich library of problem solutions and tools, and clients use our cloud computing platform to create their own problem solution libraries using AI analytics and big data.

### Where was the data currently stored in this dataset sourced from
My own storage infra

### If you answered "Other" in the previous question, enter the details here
n/a

### If you are a data preparer, what is your location (City and Country)
Hong Kong China

### If you are a data preparer, how will the data be prepared? Please include tooling used and technical details?
Use our own development tool Boost-X, which contains fastcomp, go-car and other toolkits. Can support NFS, HTTP docking.

### If you are not preparing the data, who will prepare the data?  (Provide name and business)
n/a

### Has this dataset been stored on the Filecoin network before? If so, please explain and make the case why you would like to store this dataset again to the network. Provide details on preparation and/or SP distribution.
n/a

### Please share a sample of the data
https://drive.google.com/drive/folders/1Nf_cUMLFx7BWTV4sE6M7JIQH71PcPWK9?usp=sharing

### Confirm that this is a public dataset that can be retrieved by anyone on the Network
No

### If you chose not to confirm, what was the reason
My data will be encrypted and do not want to be retrieved by anyone other than me and the SP I work with

### What is the expected retrieval frequency for this data
Yearly

### For how long do you plan to keep this dataset stored on Filecoin
More than 3 years

### In which geographies do you plan on making storage deals
Greater China, Asia other than Greater China

### How will you be distributing your data to storage providers
HTTP or FTP server

### How do you plan to choose SP
Partners

### If you answered "Others" in the previous question, what is the tool or platform you plan to use
n/a

### If you already have a list of storage providers to work with, fill out their names and provider IDs below
Apollo Group Holdings Limited            f01983521
Gongqi technology Co.,LTD                   f0169097
Waka Technology Co.,LTD                      f01924189
San Star Technology Limited                 f02237106
Shanghai Conglan Intelligent Technology Co., LTD    f02105377

### How do you plan to make deals to your storage providers
Boost client

### If you answered "Others/custom tool" in the previous question, enter the details here
n/a

### Can you confirm that you will follow the Fil+ guideline
Yes

_Application created via [filplus.storage](https://filplus.storage)_

**Comment by data-programs** [comment]
This application is requesting DataCap for a **private** dataset, so it's labeled `efil+`

**Comment by speed0211** [comment]
I have previously explained who I am and why I am resubmitting an application once more, so please check it out
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/2153#issuecomment-1683419734

**Comment by herrehesse** [comment]
Hello and thank you for your response. It's great to know that you're an investor in this project. However, that doesn't automatically reflect your expertise in data preparation and distribution. Allocating 5 PiB to a new account without an established reputation might not be in the best interest of our community.

I'd suggest running a demo with 10-100T before requesting 5000T from the community. Regrettably, the notary system has its flaws, with some taking advantage to inappropriately endorse everything.

https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/2153#issuecomment-1685779519

**Comment by kevzak** [comment]
@speed0211 Hello - you need to complete KYC and KYB for E-Fil+ requirements. Please see more information here: https://efilplus.super.site/

**Comment by Sunnyiscoming** [comment]
Close for no reply.

**Comment by data-programs** [comment]
<img width="32" alt="KYC" Verified src="https://stable.filplus.storage/images/filplus-kyc-verified-badge.png"/>

This user’s identity has been verified through [filplus.storage](https://filplus.storage)

**Comment by speed0211** [comment]
@kevzak @Sunnyiscoming Hello, I have been doing KYC certification after the application was completed, but it kept failing, so it was delayed for some time. Now that my KYC certification has passed, I hope I can re-apply to open it.

**Comment by kevzak** [comment]
@speed0211 need KYB completion with Synaps. Please confirm when complete
