### ISSUE TITLE
[DataCap Application] <Dazhu County Wannongda agricultural development limited liability company> - <agriculture>

### ISSUE THREAD

**Issue by jauea** [filecoin-project/filecoin-plus-large-datasets#2168]
### Data Owner Name

Dazhu County Wannongda agricultural development limited liability company

### What is your role related to the dataset

Dataset Owner

### Data Owner Country/Region

China

### Data Owner Industry

Life Science / Healthcare

### Website

www.wannongda.net

### Social Media

```text
www.wannongda.net
```

### Total amount of DataCap being requested

5PiB

### Expected size of single dataset (one copy)

500

### Number of replicas to store

10

### Weekly allocation of DataCap requested

500TiB

### On-chain address for first allocation

f15ssaxpw3swf6j2rseq6a7oejn2abiwcimdaaunq

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
General projects: spice crop cultivation; Fruit cultivation; Tea planting; Vegetable cultivation; Nut cultivation; Bean planting; Tobacco cultivation; Sugar crop cultivation; Tree planting and management; Fertilizer sales; Agricultural machinery sales; Agricultural film sales; Conference and exhibition services; Marketing of pesticides for health use; Livestock and fishery feed sales; Sales of agricultural and sideline products; Sales of forestry products; Primary processing of edible agricultural products; Wholesale of edible agricultural products; Retail of edible agricultural products; Fresh vegetable wholesale; Purchase of primary agricultural products; Sales of specialized machinery for agriculture, forestry, animal husbandry, auxiliary and fishery; Internet sales (except sales of goods that require a license); Installation and maintenance of specialized machinery for agriculture, forestry, animal husbandry and secondary fishery; Crop pest control services; Business agency service; Technical service, technology development, technology consultation, technology exchange, technology transfer, technology.
```

### Is this project associated with other projects/ecosystem stakeholders?

Yes

### Describe the data being stored onto Filecoin

```text
Various farming techniques.
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### If you are a data preparer. What is your location (Country/Region)

China

### If you are a data preparer, how will the data be prepared? Please include tooling used and technical details?

```text
I'm a data preparer and I use Lotus/Boost
```

### Please share a sample of the data

```text
https://cloud.189.cn/web/share?code=ueaaEfiUJjQv（pwd：pw5z）
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Weekly

### For how long do you plan to keep this dataset stored on Filecoin

More than 3 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China

### How will you be distributing your data to storage providers

HTTP or FTP server, Shipping hard drives

### How do you plan to choose storage providers

Slack

### If you already have a list of storage providers to work with, fill out their names and provider IDs below

```text
|f02237006 | eager
|f02237010 | peter 
|f01310564 |  Eve  
|f01099820 | Freda
```

### How do you plan to make deals to your storage providers

Lotus client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by herrehesse** [comment]
Hello @jauea, since this is your inaugural LDN request, I'd recommend beginning with a range of 10-100TiB to build your reputation within the community. 5 PiB is quite substantial, and given the current state of the program, I'm unsupportive to such requests.

**Comment by jauea** [comment]
@Sunnyiscoming 
|f02337006 | eager| England     |
|f02337010 | peter  |Californial |
|f01310564 |  Eve   |  Norway   |
|f01099820 | Freda | Sichuan, China|

*
Form submitted

**Comment by jauea** [comment]
@cryptowhizzard 
This miner is going to seal the DC

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 5PiB

**Expected weekly DataCap usage rate**
> 500TiB

**Client address**
>f15ssaxpw3swf6j2rseq6a7oejn2abiwcimdaaunq

**Comment by cryptowhizzard** [comment]
> @cryptowhizzard This SP is ready to encapsulate the DC

lotus net connect f01099820
f01099820 -> {12D3KooWALersjiiYix2Tmw95dSyWrjgnofFZvAiErC79hLoF5XB: []}
connect 12D3KooWALersjiiYix2Tmw95dSyWrjgnofFZvAiErC79hLoF5XB: failure

Again ... This SP is NOT eligible to be used in this LDN untill the IP is set on chain.

@Sunnyiscoming Why are you triggering on miners that are not eligible according to notary governance 922?

@filplus-govteam please track this application.

**Comment by jauea** [comment]
Sorry for taking so long to reply, I will look for more eligible miners before signing. Thank you!

**Comment by jauea** [comment]
> This application has not seen any responses in the last 10 days. This issue will be marked with Stale label and will be closed in 4 days. Comment if you want to keep this application open.
> 
> -- Commented by Stale Bot.

Sorry it took so long to reply, please keep opening.

**Comment by jauea** [comment]
Sorry it took so long to reply, please keep opening.

**Comment by jauea** [comment]
keep it open

**Comment by jauea** [comment]
> This application has not seen any responses in the last 10 days. This issue will be marked with Stale label and will be closed in 4 days. Comment if you want to keep this application open.
> 
> -- Commented by Stale Bot.

keep it open

**Comment by kevzak** [comment]
Please provide updated list of SP ids and entities
