### ISSUE TITLE
[DataCap Application] <RongYin> - <AI Tools-NLP> - NEW

### ISSUE THREAD

**Issue by datalove2** [filecoin-project/filecoin-plus-large-datasets#2169]
### Data Owner Name

RongYin

### What is your role related to the dataset

Data Preparer

### Data Owner Country/Region

China

### Data Owner Industry

IT & Technology Services

### Website

https://www.qcc.com/firm/3380acbb3101bd58394d1ba4be51e877.html

### Social Media

```text
https://www.qcc.com/firm/3380acbb3101bd58394d1ba4be51e877.html
```

### Total amount of DataCap being requested

7PiB

### Expected size of single dataset (one copy)

1.5PiB

### Number of replicas to store

10

### Weekly allocation of DataCap requested

1PiB

### On-chain address for first allocation

f15waefbgzgzjq2wlb3cqcttgfsmkldfrctiwf2jq

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
RongYin was established in 2019 in HK. We were provided with a storage capacity in total of 150PiB. Now, we are planning to engage in onboard humanity data which is useful for the network. <RongYin Open Data Project> has successed onboard 10PiB storage capacity to the network, which is about 1.5P raw data. For the next steps, we have prepared 3P raw data with 10x backups.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
We are going to onboard open data of <natural language processing> from AWS, which is a branch of artificial intelligence (AI) that enables computers to comprehend, generate, and manipulate human language. Natural language processing has the ability to interrogate the data with natural language text or voice.
Natural language processing datasets covers 68 matching datasets. In total about 1.7PiB. 
Including Common Crawl, Sudachi Language Resources, Japanese Tokenizer Dictionaries, MIMIC-III (‘Medical Information Mart for Intensive Care’), Common Screens, Discrete Reasoning Over the content of Paragraphs (DROP), End of Term Web Archive Dataset, MultiCoNER Datasets, etc.
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### If you are a data preparer. What is your location (Country/Region)

Hong Kong

### If you are a data preparer, how will the data be prepared? Please include tooling used and technical details?

```text
IPFS, lotus, singularity, graphsplit
```

### Has this dataset been stored on the Filecoin network before? If so, please explain and make the case why you would like to store this dataset again to the network. Provide details on preparation and/or SP distribution.

```text
no
```

### Please share a sample of the data

```text
https://registry.opendata.aws/eot-web-archive/
https://registry.opendata.aws/allenai-quoref/
https://registry.opendata.aws/comonscreens/
https://registry.opendata.aws/allenai-drop/
https://registry.opendata.aws/paracrawl/
https://registry.opendata.aws/allenai-quoref/
https://registry.opendata.aws/mmid/
...
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

1.5 to 2 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, Europe

### How will you be distributing your data to storage providers

Cloud storage (i.e. S3), HTTP or FTP server, IPFS, Shipping hard drives

### How do you plan to choose storage providers

Slack, Big Data Exchange, Partners

### If you already have a list of storage providers to work with, fill out their names and provider IDs below

```text
I will fill in the information disclosure form in detail
```

### How do you plan to make deals to your storage providers

Boost client, Lotus client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by herrehesse** [comment]
Based on the discussion at [this link](https://github.com/filecoin-project/notary-governance/issues/832) and the decisions from T&T calls a few months ago, we do not permit merged datacap requests.

@datalove2, you're welcome to request these datasets individually. However, given that these datasets have been stored on the Filecoin network several times already, it might be challenging to garner support.

We encourage you to contribute meaningfully to the Filecoin network instead of solely seeking to acquire datacap.

**Comment by Sunnyiscoming** [comment]
- Best practice for storing large datasets includes ideally, storing it in 3 or more regions, with 4 or more storage provider operators or owners.You should list Miner ID, Business Entity, Location of sps you will cooperate with.
- Per the https://github.com/filecoin-project/notary-governance/issues/922 for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

**Comment by cryptowhizzard** [comment]
I am not satisfied with the explanation given in the last LDN by this client here:

https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/2050#issuecomment-1689352475

Although this LDN is closed the applicant blames his SP for wrongdoing. This is a fairytale.

We all know that the Data preparer sends out the deal. This unique deal ID can only match with the original content of the data preparer. This is the whole meaning of Filecoin , immutability.

I propose to close this application and new ones until a proper explanation is given. Fraud brings harm to the community and this behaviour must be stopped.

**Comment by Sunnyiscoming** [comment]
Any update here?

**Comment by Sunnyiscoming** [comment]
Any update here?

**Comment by Sunnyiscoming** [comment]
Please list information of sps here.

**Comment by datalove2** [comment]
@Sunnyiscoming 
![Uploading B5586255-9F1B-410C-B9C0-77DA4A554D69.jpeg…]()

**Comment by datalove2** [comment]
@Sunnyiscoming 
![7E51352E-6F6D-43D6-A3D1-4A81064CC77D](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/124253156/e9ad41ff-77de-47c7-96ac-1f37ecd2982d)

**Comment by cryptowhizzard** [comment]
> I am not satisfied with the explanation given in the last LDN by this client here:
> 
> [#2050 (comment)](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/2050#issuecomment-1689352475)
> 
> Although this LDN is closed the applicant blames his SP for wrongdoing. This is a fairytale.
> 
> We all know that the Data preparer sends out the deal. This unique deal ID can only match with the original content of the data preparer. This is the whole meaning of Filecoin , immutability.
> 
> I propose to close this application and new ones until a proper explanation is given. Fraud brings harm to the community and this behaviour must be stopped.

Reminder.

**Comment by Sunnyiscoming** [comment]
Any update here?

**Comment by Sunnyiscoming** [comment]
It will be closed in 3 days if there is no reply here.

**Comment by datalove2** [comment]
@Sunnyiscoming 
I apologize for the delayed response.

The community discourages applications for "merged data sets" because combining a large number of unrelated data into a single large file can result in messy, difficult-to-use uploads that offer limited value. However, what we are applying for is a category of data labeled "natural language processing," which falls under the same category and serves the same purpose.

**Comment by Sunnyiscoming** [comment]
I cannot support your application. There is clear rule in the community.
Maybe you can apply for other open dataset.
