### ISSUE TITLE
[DataCap Application] Super Handian 

### ISSUE THREAD

**Issue by oldamboo** [filecoin-project/filecoin-plus-large-datasets#2172]
### Data Owner Name
Super Handian 

### What is your role related to the dataset
Dataset Owner

### Data Owner Country/Region
China

### Data Owner Industry
IT & Technology Services

### Website
[http://www.inscdt.com/](http://www.inscdt.com/)

### Social Media
http://www.inscdt.com/ (Organization Website)

### Total amount of DataCap being requested
150 PiB

### Expected size of single dataset (one copy)
15 PiB

### Number of replicas to store
10

### Weekly allocation of DataCap requested
1 PiB

### On-chain address for first allocation
f1mho5wc23poqa3ajorei2wdlx4pqrauw6ioexf3y

### Data Type of Application
Private Commercial/Enterprise

### Custom multisig
- [x] Use Custom Multisig

### Identifier
efil

### Share a brief history of your project and organization
Shenzhen Handian Supercomputing Data Co., Ltd. is a comprehensive technology service provider dedicated to distributed storage and computing. It is a computing asset management company based on distributed storage and blockchain technology, big data, edge computing and artificial intelligence as the industry background, and distributed computing services as the product form. The company provides global users with digital technology services such as distributed storage, edge computing, data authentication and certification.

### Is this project associated with other projects/ecosystem stakeholders?
Yes

### If answered yes, what are the other projects/ecosystem stakeholders
We will be Subsequent disclosure

### Describe the data being stored onto Filecoin
We will be Subsequent disclosure

### Where was the data currently stored in this dataset sourced from
My own storage infra

### If you answered "Other" in the previous question, enter the details here
n/a

### If you are a data preparer, what is your location (City and Country)
Shenzhen, China

### If you are a data preparer, how will the data be prepared? Please include tooling used and technical details?
singularity

#Building singularity
https://github.com/tech-greedy/singularity

#View the current list
Singularity pre list

#Generate car
Singularity pre create - t/mnt/md0/awscar 2032 Data source address generation car file address

#Monitoring situation
Singularity monitor

#Issue an order
Singularity repl start - l/mnt/disks/192.168.50.161/raidd1/DATA_ 2032/test 649eb491 * * 17dbd192d * * miner f1lmrsadfasdftkw7hbk2tvkjbezasdfrwopa (quota address)

### If you are not preparing the data, who will prepare the data?  (Provide name and business)
n/a

### Has this dataset been stored on the Filecoin network before? If so, please explain and make the case why you would like to store this dataset again to the network. Provide details on preparation and/or SP distribution.
n/a

### Please share a sample of the data
part of open datasets

First level directory
http://220.168.154.102:18080/images/

Second level directory
output_matrix_part1  output_matrix_part2  output_matrix_part3  output_matrix_part4

some output_matrix_part3 files
http://220.168.154.102:18080/images/output_matrix_part3/upscale_img_000cVA_.png.npy

We have approximately 692564 such data samples

### Confirm that this is a public dataset that can be retrieved by anyone on the Network
Yes

### If you chose not to confirm, what was the reason
n/a

### What is the expected retrieval frequency for this data
Sporadic

### For how long do you plan to keep this dataset stored on Filecoin
Permanently

### In which geographies do you plan on making storage deals
Asia other than Greater China, North America

### How will you be distributing your data to storage providers
HTTP or FTP server

### How do you plan to choose SP
Partners

### If you answered "Others" in the previous question, what is the tool or platform you plan to use
n/a

### If you already have a list of storage providers to work with, fill out their names and provider IDs below
f02129771
f01172521 
f01843178
f01877259
f02192588

### How do you plan to make deals to your storage providers
Lotus client

### If you answered "Others/custom tool" in the previous question, enter the details here
n/a

### Can you confirm that you will follow the Fil+ guideline
Yes

_Application created via [filplus.storage](https://filplus.storage)_

**Comment by data-programs** [comment]
This application requests a total of 150 PiB, so it’s labeled `efil+`

**Comment by Filplus-govteam** [comment]
@oldamboo please complete requirements for E-Fil+, details here: https://efilplus.super.site/

**Comment by oldamboo** [comment]
@Filplus-govteam hi，I have already submit the E-Fil+ Registration Form、 KYB and KYC info yestoday，and it‘s in progress now。

**Comment by kevzak** [comment]
Hi @oldamboo you need to complete KYB on Synaps. That is not completed. 

Also, you need to complete KYC via filplus.storage. That is not completed. Let me know if you have more questions.

**Comment by oldamboo** [comment]
> Hi @oldamboo you need to complete KYB on Synaps. That is not completed.
> 
> Also, you need to complete KYC via filplus.storage. That is not completed. Let me know if you have more questions.

KYB is so difficult to complete。
