### ISSUE TITLE
[DataCap Application] Coupled Model Intercomparison Project

### ISSUE THREAD

**Issue by Lucasxie77** [filecoin-project/filecoin-plus-large-datasets#2173]
### Data Owner Name

ESGF and Pangeo

### What is your role related to the dataset

Data Preparer

### Data Owner Country/Region

United States

### Data Owner Industry

Life Science / Healthcare

### Website

https://wcrp-cmip.org/cmip-phase-6-cmip6/

### Social Media

```text
https://pangeo-data.github.io/pangeo-cmip6-cloud/
```

### Total amount of DataCap being requested

15PiB

### Expected size of single dataset (one copy)

1753TiB

### Number of replicas to store

9

### Weekly allocation of DataCap requested

1PiB

### On-chain address for first allocation

f16pp7pzswzd5qnrzagukwggslrv56bwcwwahu7ly

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
The WCRP Working Group on Coupled Modelling (WGCM) oversees the Coupled Model Intercomparison Project, which is now in its 6th phase. Background information about CMIP and its phases can be found on WGCM website as well as on the PCMDI-hosted pages. An introductory overview of CMIP6 is also provided by the WGCM.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
Zarr formatted data from the sixth phase of global coupled ocean-atmosphere general circulation model ensemble.
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### If you are a data preparer. What is your location (Country/Region)

Hong Kong

### If you are a data preparer, how will the data be prepared? Please include tooling used and technical details?

```text
Mainly lotus, also use ipfs, singularity.
```

### Has this dataset been stored on the Filecoin network before? If so, please explain and make the case why you would like to store this dataset again to the network. Provide details on preparation and/or SP distribution.

```text
Don't know. I will finish storing this dataset.
```

### Please share a sample of the data

```text
aws s3 ls --no-sign-request s3://cmip6-pds/
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

1.5 to 2 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, Europe

### How will you be distributing your data to storage providers

HTTP or FTP server, IPFS, Shipping hard drives, Lotus built-in data transfer

### How do you plan to choose storage providers

Slack, Big Data Exchange, Partners

### If you already have a list of storage providers to work with, fill out their names and provider IDs below

```text
f02169597 Guangdong
f01841131 HongKong
f01344987 HongKong
f01106276 Hebei
```

### How do you plan to make deals to your storage providers

Boost client, Lotus client, Singularity

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
Any update here?

**Comment by Lucasxie77** [comment]
@Sunnyiscoming OK! I have finished the form.

**Comment by herrehesse** [comment]
@Lucasxie77 welcome to FIL+!

Allocating 15 PiB to a new account without an established reputation might not be in the best interest of our community.
I'd suggest running a demo with 10-100T before requesting 15000T from the community. Regrettably, the notary system has its flaws, with some taking advantage to inappropriately endorse everything.

You should list Miner ID, Business Entity, Location of sps on the issue as well.
Thank you!

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 15PiB

**Expected weekly DataCap usage rate**
> 1PiB

**Client address**
>f16pp7pzswzd5qnrzagukwggslrv56bwcwwahu7ly

**Comment by Lucasxie77** [comment]
@herrehesse These miners are not in the same regions. They are distributed in different regions. And this is just a preliminary list of SPs, we will continue to find more SPs in different regions after we are granted datacap.

**Comment by herrehesse** [comment]
@Lucasxie77 That is not how this works. First you get a proper list, distributed globally (NO VPN) and proper reputation SP's. Then you get approved. Then notaries will do their due diligence. Then you get datacap.

**Comment by Lucasxie77** [comment]
> @Lucasxie77 That is not how this works. First you get a proper list, distributed globally (NO VPN) and proper reputation SP's. Then you get approved. Then notaries will do their due diligence. Then you get datacap.

Yes, I got it and we are obeying rules. Thank you.

**Comment by Bitrise0111** [comment]
Do you have new nodes to disclose from the time of application to now ?  your entry into LDN should align with the nodes you disclosed.

**Comment by Lucasxie77** [comment]
@Bitrise0111 Yes, we have communicated with some SPs new. Such as f0103710, f01955028.

**Comment by Bitrise0111** [comment]
Got it. For this round, we're willing to give you support as you need to seal your nodes as you disclosed before. We'll do the check work randomly.

**Comment by Bitrise0111** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedmymfmwrty5axnv3t3smpppu6dnpgojccbwvu6l3j2i7ellxipsm 
#### Address 
> f16pp7pzswzd5qnrzagukwggslrv56bwcwwahu7ly
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f1nknj7ayq4o43czrtdoauggtwl43fbqatmqis3yy
#### Id
> c3300ade-5549-4065-9f16-d7325eed596f
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedmymfmwrty5axnv3t3smpppu6dnpgojccbwvu6l3j2i7ellxipsm

**Comment by herrehesse** [comment]
@Bitrise0111 here you go again. @kevzak can we start and remove this notary?

**Comment by Lucasxie77** [comment]
@herrehesse Why did you say that about this kind notary? My application has no problem and what the notary did has no problem!

**Comment by kevzak** [comment]
please disclose all SPs upfront @Lucasxie77 - closing until updated

**Comment by Lucasxie77** [comment]
Hello @kevzak , actually I have disclosed SPs several times--- in my application, in Fil+ form, and in the comment.
f02169597 Guangdong
f01841131 HongKong
f01344987 HongKong
f01106276 Hebei
f0103710 Guiyang
f01955028 Jinhua
f02363999 Singapore

Now I disclose these again. Can you open my application?

**Comment by AthSmith** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecywebjua3vs4nwl2vj5yfestayhsxwjaer5pi4s5cwtbckftbk4o 
#### Address 
> f16pp7pzswzd5qnrzagukwggslrv56bwcwwahu7ly
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f1vxbqrf7rfum3n6m5u6eb4re6xj7amvsaqnzu64y
#### Id
> c3300ade-5549-4065-9f16-d7325eed596f
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecywebjua3vs4nwl2vj5yfestayhsxwjaer5pi4s5cwtbckftbk4o

**Comment by herrehesse** [comment]
No business names and contact information but an insta sign by a known abusive notary @AthSmith.
Anyone looking?

**Comment by Lucasxie77** [comment]
@herrehesse What're you talking about? Just making noise?

**Comment by herrehesse** [comment]
checker:manualTrigger

**Comment by herrehesse** [comment]
Close this application immediately.

**Comment by kevzak** [comment]
SPs provided upfront

SP 1 | f01820802 | Paul | - | - | Dongguan,Guangdong,CN | - | Paul
f0132178 | Aaron | - | - | Hangzhou, Zhejiang, CN | - | Aaron
f01270684 | WilliamSun | - | - | Guangzhou, Guangdong,CN | - | William
f01084913 | Bill | - | - | HongKong | - | bill
f01445167 | Ray | - | - | Hong Kong | - | Ray

SPs used for deals
f01879772 | Hong Kong, Central and Western, HKBIH-Global Internet Harbor | 18.63 TiB | 41.91% | 18.63 TiB | 0.00%
f01098931 | Hangzhou, Zhejiang, CNCHINANET-BACKBONE | 25.81 TiB | 58.09% | 25.81 TiB | 0.00%

no matches. closing for abuse

**Comment by Lucasxie77** [comment]
@kevzak Hey Kevin. That's not abuse.
After my application was triggered by sunny, it took 2 months, on and off, for 2 notaries to sign my application. During this time, some sps were unwilling to deal with us because we waited too long for our application. So we found other sps to participate in us.
In the following process, we can expand our sp list and show on the application. Please open my application. Thank you Kevin.

**Comment by kevzak** [comment]
Abuse is not the proper term here, apologies. Non-compliance is the correct term. 

You can share all SP that you will partner with - entities locations and miner IDs upfront to continue.
