### ISSUE TITLE
[DataCap Application] <Pubang seedlings> - <Pubang seedlings>

### ISSUE THREAD

**Issue by Timothea01** [filecoin-project/filecoin-plus-large-datasets#2174]
### Data Owner Name

Guangdong Pubangang Seedling Plantation Co.

### What is your role related to the dataset

Dataset Owner

### Data Owner Country/Region

Afghanistan

### Data Owner Industry

Life Science / Healthcare

### Website

https://pubangmm.com/

### Social Media

```text
https://pubangmm.com/
```

### Total amount of DataCap being requested

5PiB

### Expected size of single dataset (one copy)

500TiB

### Number of replicas to store

10

### Weekly allocation of DataCap requested

100TiB

### On-chain address for first allocation

f1eguy4uruawgfecmsj5kid57c7v6kcdprzwejggi

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Pubang is a diversified group of companies integrating rare plant cultivation and research, organic agriculture promotion and demonstration, bio-organic fertiliser production, eco-agriculture sightseeing and tourism, tourism and real estate, professional planning of cultural activities, and landscaping projects. The group is committed to become a pioneer of organic environmental protection revolution, the promotion of organic, environmental protection, healthy living as a corporate responsibility and sustainable development path, the future will be "to become a nationally renowned organic life demonstration enterprise, the leader of the organic industry, and even the participation and development of the industry standard" and unremitting efforts in the development of speciality tourism, In the future, we will make unremitting efforts to "become a national famous organic life demonstration enterprise, organic industry leader, and even participate in the formulation of industry standards", and create greater glory in the fields of special tourism development, organic agricultural planting, rare species planting research!
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
Seedling planting and grafting, agricultural planting development, knowledge, etc.
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### If you are a data preparer. What is your location (Country/Region)

None

### If you are a data preparer, how will the data be prepared? Please include tooling used and technical details?

```text
We use Lotus Boost to prepare the data
```

### Please share a sample of the data

```text
https://www.aliyundrive.com/s/ymBTw53jsvj
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Weekly

### For how long do you plan to keep this dataset stored on Filecoin

1.5 to 2 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China

### How will you be distributing your data to storage providers

HTTP or FTP server, Shipping hard drives

### How do you plan to choose storage providers

Slack, Partners

### If you already have a list of storage providers to work with, fill out their names and provider IDs below

```text
f01836766  GuangZhou
f02048990  hong kong
f02062851  Californial
f016563    Sichuan
```

### How do you plan to make deals to your storage providers

Boost client, Singularity

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Timothea01** [comment]
> ![image](https://user-images.githubusercontent.com/105098820/263306253-433b4ba9-c5b6-41a2-a90c-c02f0d5c7a76.png) Something abnormal on the website.

Under repair
> 
> Total amount of DataCap being requested≠Expected size of single dataset (one copy)_Number of replicas to store 100TiB≠500TiB_10 Please check the value
Thank you for pointing out that my carelessness caused a misunderstanding and has been corrected
> 
> Can you provide more data samples to prove you have such a large amount of data?
https://www.aliyundrive.com/s/74D9krwqLJw
> 
> Could you send an email to [filplus-app-review@fil.org](mailto:filplus-app-review@fil.org) with your official domain in order to confirm your identity? Email name should includes the issue id #2174.
![图片](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/142859578/f4e4c3d1-cd68-46a9-9e07-c297db7d569e)
has been sent

> 
> Per the [filecoin-project/notary-governance#922](https://github.com/filecoin-project/notary-governance/issues/922) for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.
Already submitted

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 5 PiB

**Expected weekly DataCap usage rate**
> 100 TiB

**Client address**
>f1eguy4uruawgfecmsj5kid57c7v6kcdprzwejggi

**Comment by herrehesse** [comment]
@Sunnyiscoming Have you checked the minerID's against the abuse tooling?

**Comment by Timothea01** [comment]
> This application has not seen any responses in the last 10 days. This issue will be marked with Stale label and will be closed in 4 days. Comment if you want to keep this application open.
> 
> -- Commented by Stale Bot.

Please wait a moment.

**Comment by Timothea01** [comment]
Please wait a moment.

**Comment by Timothea01** [comment]
> Please wait a moment.

Please wait a moment.

**Comment by Timothea01** [comment]
> This application has not seen any responses in the last 10 days. This issue will be marked with Stale label and will be closed in 4 days. Comment if you want to keep this application open.
> 
> -- Commented by Stale Bot.
Please wait a moment.

**Comment by Timothea01** [comment]
> This application has not seen any responses in the last 10 days. This issue will be marked with Stale label and will be closed in 4 days. Comment if you want to keep this application open.
> 
> -- Commented by Stale Bot.

Please wait a moment.

**Comment by kevzak** [comment]
Please provide a list of miner IDs and entities for this application. Closing until updated
