### ISSUE TITLE
[DataCap Application] <6BLOCK LLC > - <Blockchain technology>

### ISSUE THREAD

**Issue by KeYuW** [filecoin-project/filecoin-plus-large-datasets#2177]
### Data Owner Name

6BLOCK LLC 

### What is your role related to the dataset

Dataset Owner

### Data Owner Country/Region

American Samoa

### Data Owner Industry

Web3 / Crypto

### Website

https://6block.com/

### Social Media

```text
https://6block.com/
```

### Total amount of DataCap being requested

2PiB

### Expected size of single dataset (one copy)

500TiB

### Number of replicas to store

4

### Weekly allocation of DataCap requested

150TiB

### On-chain address for first allocation

f1b5otvwd4in6kbcmrob7i4peylt3uthrqnrvw7xa

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Pomegranate Mining pool focuses on unicorn projects in the field of digital currency, providing mining pools, customized mining software, mining machines, wallets and other solutions.

Since entering the Filecoin mining field, I have discovered and reported to the authorities several vulnerabilities in the Filecoin test network, such as unlimited issue vulnerabilities and block vulnerabilities, and was invited to become a member of the FileCoin Security Research Fellowship (FSRF). At present, two developers of the pomegranate pool are members of the FSRF.

The pomegranate mining pool focuses on the optimization of Filecoin mining software, and shares the excess income brought by software optimization with miners. The packaging speed of mining software has been increased by more than 2 times on the official basis, which is at the leading level in the industry. In terms of hardware, all the pomegranate pool miners are equipped with AMD CPU, and the hosted IDC room is a T3+ level big data center, with three power supplies and two network supplies, which is safe and stable.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
The data set comes from a video we produced to share new technologies in the blockchain field
```

### Where was the data currently stored in this dataset sourced from

Other

### If you answered "Other" in the previous question, enter the details here

```text
network platform
```

### If you are a data preparer. What is your location (Country/Region)

None

### If you are a data preparer, how will the data be prepared? Please include tooling used and technical details?

```text
lotus
```

### Has this dataset been stored on the Filecoin network before? If so, please explain and make the case why you would like to store this dataset again to the network. Provide details on preparation and/or SP distribution.

```text
no
```

### Please share a sample of the data

```text
https://www.youtube.com/@biquanlibai
https://space.bilibili.com/1895248295/video
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Weekly

### For how long do you plan to keep this dataset stored on Filecoin

1.5 to 2 years

### In which geographies do you plan on making storage deals

Greater China

### How will you be distributing your data to storage providers

Lotus built-in data transfer

### How do you plan to choose storage providers

Partners

### If you already have a list of storage providers to work with, fill out their names and provider IDs below

```text
f02031063 xingjiang
f01879914 us
f02362189 changji
f02129337 kelamayi
```

### How do you plan to make deals to your storage providers

Lotus client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by herrehesse** [comment]
@KeYuW Hello friend, I have a question for you about your LDN:

- Why do you think that storing youtube video's will benefit to the goal of "storing humanities most important information"?

**Comment by KeYuW** [comment]
fil is a new storage mode. Storing well-known FIL-related videos published by our company in fil is a new experience. I believe fil storage can provide a better storage experience than youtube

**Comment by herrehesse** [comment]
Filecoin currently does simply not provide a better storage experience than youtube. It's essential to ensure that datacap requests align with genuine storage needs rather than just expanding miner capacity. If storing YouTube video's is accepted we can infinitely ask for DC to store it. That is not how this works.

At this time, I cannot support this request.

**Comment by KeYuW** [comment]
At present, there are many FIL-related videos in our company, and YouTUbe is just one of the places we promote. I think it can be better stored by storing our company's videos on the fil from U disk or web disk

**Comment by Sunnyiscoming** [comment]
- Have you prepared enough token for sector pledge?
- Please provide more data samples to prove that you have 500 TB data already.
- Per the https://github.com/filecoin-project/notary-governance/issues/922 for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

**Comment by herrehesse** [comment]
@KeYuW please add the contact information of the SP entities you are working with to store copies of the data.

**Comment by KeYuW** [comment]
> @KeYuW please add the contact information of the SP entities you are working with to store copies of the data.

f01879914    | Toeic           ｜changji
f02031063   | sitestar         |  Silicon Valley
f02362189   | recreation     | kelamayi
f02129337   |  momentum  | tianchi

**Comment by herrehesse** [comment]
f01879914 | Toeic ｜changji
f02031063 | sitestar | Silicon Valley
f02362189 | recreation | kelamayi
f02129337 | momentum | tianchi

Those businesses do not exsist and they are on VPN mostly. Why lie?

**Comment by KeYuW** [comment]
Sorry, these sp provider information is incorrect, I will immediately verify and correct the new sp partner information
