### ISSUE TITLE
[DataCap Application] <agriculture> - <Fengwo Extraordinary Agricultural >

### ISSUE THREAD

**Issue by Bohden** [filecoin-project/filecoin-plus-large-datasets#2179]
### Data Owner Name

Fengwo Extraordinary

### What is your role related to the dataset

Storage provider filling out application on behalf of the data owner

### Data Owner Country/Region

China

### Data Owner Industry

Resources, Agriculture & Fisheries

### Website

https://www.qcc.com/firm/97d395cae168248fb4911d659b6750b5.html

### Social Media

```text
https://www.qcc.com/firm/97d395cae168248fb4911d659b6750b5.html
```

### Total amount of DataCap being requested

3PiB

### Expected size of single dataset (one copy)

300T

### Number of replicas to store

10

### Weekly allocation of DataCap requested

300TiB

### On-chain address for first allocation

f1kur4jy3kj7eavaou7lwekthbcln5wsxx32shr4a

### Data Type of Application

Public, Open Commercial/Enterprise

### Custom multisig

- [X] Use Custom Multisig

### Share a brief history of your project and organization

```text
Heilongjiang Fengwo Extraordinary Agricultural Science and Technology Development Co., Ltd., mainly engaged in agricultural intelligence, digital products, is a collection of scientific research, production, sales, service as one of the technology enterprises.
```

### Is this project associated with other projects/ecosystem stakeholders?

Yes

### Describe the data being stored onto Filecoin

```text
With the rapid development of technology, technological innovation is helping to promote high-quality agricultural development. In this promotional video, we will introduce the positive role of technology in promoting agricultural development.
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### If you are a data preparer. What is your location (Country/Region)

China

### If you are a data preparer, how will the data be prepared? Please include tooling used and technical details?

```text
IPFS, lotus, singularity, graphsplit
```

### Has this dataset been stored on the Filecoin network before? If so, please explain and make the case why you would like to store this dataset again to the network. Provide details on preparation and/or SP distribution.

```text
no
```

### Please share a sample of the data

```text
https://drive.google.com/drive/folders/1cTLYO-9vumVrpT0aY0QQAGl5E6N_boT9?usp=sharing
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Monthly

### For how long do you plan to keep this dataset stored on Filecoin

1.5 to 2 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America

### How will you be distributing your data to storage providers

HTTP or FTP server, IPFS, Shipping hard drives

### How do you plan to choose storage providers

Slack, Big Data Exchange, Partners

### If you already have a list of storage providers to work with, fill out their names and provider IDs below

```text
f02252173 Tokyo
f0746542  Chengdu
f01776669 Korea
f0702010  Guangzhou
```

### How do you plan to make deals to your storage providers

Boost client, Lotus client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by herrehesse** [comment]
![Screenshot 2023-08-29 at 11 10 32](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/70132857/5b0e6fb9-5a46-405a-b4ed-df9a2bf48888)

Data is protected by a login barrier. I don't advocate for storing arbitrary videos on FIL+ since, in my view, it doesn't align with the mission of preserving humanity's most valuable information.

**Comment by Bohden** [comment]
> ![Screenshot 2023-08-29 at 11 10 32](https://user-images.githubusercontent.com/70132857/263964189-5b0e6fb9-5a46-405a-b4ed-df9a2bf48888.png)
> 
> Data is protected by a login barrier. I don't advocate for storing arbitrary videos on FIL+ since, in my view, it doesn't align with the mission of preserving humanity's most valuable information.

I'm sorry I overlooked this and I re-uploaded it to Google Drive

**Comment by herrehesse** [comment]
@Bohden Please add the contact information of the SP entities you are working with to store copies of the data.

**Comment by Bohden** [comment]
I'm contacting them now. Please hold.

**Comment by Sunnyiscoming** [comment]
Any update here?

**Comment by Bohden** [comment]
> * Have you prepared enough token for sector pledge?
> * Could you send an email to [filplus-app-review@fil.org](mailto:filplus-app-review@fil.org) with your official domain in order to confirm your identity? Email name should includes the issue id [[DataCap Application] <agriculture> - <Fengwo Extraordinary Agricultural > #2179](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/2179).
> * Per the [Modification: Changes required to public open dataset application flow notary-governance#922](https://github.com/filecoin-project/notary-governance/issues/922) for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.
1. Yes, we have enough tokens 2. Our company does not have a website, so we can only send you an email with a private email, what do you think? 3. The registration form has been submitted

**Comment by Bohden** [comment]
![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/143244468/9f1e3623-6919-4cc6-be62-78894b4ee0cf)

**Comment by Sunnyiscoming** [comment]
You can send the business license to [filplus-app-review@fil.org] with your own email. Email name should includes the issue id #2179.

**Comment by Bohden** [comment]
> You can send the business license to [[filplus-app-review@fil.org](mailto:filplus-app-review@fil.org)] with your own email. Email name should includes the issue id #2179.

The business license will be sent to this mailbox the day after tomorrow

**Comment by Bohden** [comment]
> * Have you prepared enough token for sector pledge?
> * Could you send an email to [filplus-app-review@fil.org](mailto:filplus-app-review@fil.org) with your official domain in order to confirm your identity? Email name should includes the issue id [[DataCap Application] <agriculture> - <Fengwo Extraordinary Agricultural > #2179](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/2179).
> * Per the [Modification: Changes required to public open dataset application flow notary-governance#922](https://github.com/filecoin-project/notary-governance/issues/922) for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

The business license has been sent to this mailbox with the subject line #2179

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 3PiB

**Expected weekly DataCap usage rate**
> 300TiB

**Client address**
>f1kur4jy3kj7eavaou7lwekthbcln5wsxx32shr4a

**Comment by herrehesse** [comment]
@Sunnyiscoming why trigger, I have not seen information from this applicant yet?

**Comment by Bohden** [comment]
> This application has not seen any responses in the last 10 days. This issue will be marked with Stale label and will be closed in 4 days. Comment if you want to keep this application open.
> 
> -- Commented by Stale Bot.

Deal with it right away, thanks for the reminder.

**Comment by Sunnyiscoming** [comment]
It is still being processed.

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 3PiB

**Expected weekly DataCap usage rate**
> 300TiB

**Client address**
>f1kur4jy3kj7eavaou7lwekthbcln5wsxx32shr4a

**Comment by kevzak** [comment]
closed until SP IDs and entities are provided
