### ISSUE TITLE
[DataCap Application] ChainOn Technology (HK) Limited

### ISSUE THREAD

**Issue by ChainOnHK** [filecoin-project/filecoin-plus-large-datasets#2180]
### Data Owner Name
ChainOn Technology (HK) Limited

### What is your role related to the dataset
Storage provider filling out application on behalf of the data owner

### Data Owner Country/Region
Hong Kong

### Data Owner Industry
IT & Technology Services

### Website
[http://www.chainonc.com/tcn](http://www.chainonc.com/tcn)

### Social Media
https://www.facebook.com/ChainonHk (Facebook)

### Total amount of DataCap being requested
100 TiB

### Expected size of single dataset (one copy)
32 GiB

### Number of replicas to store
1

### Weekly allocation of DataCap requested
100 TiB

### On-chain address for first allocation
 f3u3wfajso3qcoxy2ym6k5zm4lkd44255xxib3ryevhme7l55eobuyzxvqmz4c2bvaomrwl4cmhkxd526kgbpq

### Data Type of Application
Public, Open Dataset (Research/Non-Profit)

### Custom multisig
- [x] Use Custom Multisig

### Identifier
efil

### Share a brief history of your project and organization
ChainOn Technology (HK) Limited, headquartered in HK, is a service organization dedicated to technology development with 10 years of experience in Internet project research and development and application implementation in the field of architecture storage. 

### Is this project associated with other projects/ecosystem stakeholders?
Yes

### If answered yes, what are the other projects/ecosystem stakeholders
Decentralised Instant messager via filecoin virtual machines, all data will be storage on filecoin storage network ; also support decentralised wallet

### Describe the data being stored onto Filecoin
instant messager data.

### Where was the data currently stored in this dataset sourced from
My own storage infra

### If you answered "Other" in the previous question, enter the details here
n/a

### If you are a data preparer, what is your location (City and Country)
Hong Kong

### If you are a data preparer, how will the data be prepared? Please include tooling used and technical details?
n/a

### If you are not preparing the data, who will prepare the data?  (Provide name and business)
n/a

### Has this dataset been stored on the Filecoin network before? If so, please explain and make the case why you would like to store this dataset again to the network. Provide details on preparation and/or SP distribution.
n/a

### Please share a sample of the data
/var/folders/ks/d443t2ns4jb3_r5t65826f6w0000gn/T/com.apple.useractivityd/shared-pasteboard/items/DD644427-53A9-4A74-8461-E9E57D830204/com.hpplay.happycast_5.9.02.apk

### Confirm that this is a public dataset that can be retrieved by anyone on the Network
No

### If you chose not to confirm, what was the reason
It's private instant chat application, so all the conversation cannot be shared to public

### What is the expected retrieval frequency for this data
Monthly

### For how long do you plan to keep this dataset stored on Filecoin
Permanently

### In which geographies do you plan on making storage deals
Asia other than Greater China

### How will you be distributing your data to storage providers
IPFS

### How do you plan to choose SP
Filmine

### If you answered "Others" in the previous question, what is the tool or platform you plan to use
n/a

### If you already have a list of storage providers to work with, fill out their names and provider IDs below
Filefast / f02370792

### How do you plan to make deals to your storage providers
I don't know yet

### If you answered "Others/custom tool" in the previous question, enter the details here
n/a

### Can you confirm that you will follow the Fil+ guideline
Yes

_Application created via [filplus.storage](https://filplus.storage)_

**Comment by data-programs** [comment]
This application is requesting DataCap for a **private** dataset, so it's labeled `efil+`

**Comment by Sunnyiscoming** [comment]
Any update here?

**Comment by data-programs** [comment]
<img width="32" alt="KYC" Verified src="https://stable.filplus.storage/images/filplus-kyc-verified-badge.png"/>

This user’s identity has been verified through [filplus.storage](https://filplus.storage)

**Comment by Sunnyiscoming** [comment]
Any update here?

**Comment by ChainOnHK** [comment]
Hello there,

I’m sorry, we are already trying to fill every blank earlier these few days. We just did the kyc today and got approved. And got stuck in a few blanks. We will try to finish up by the end of this week.

It’s our first time for the application, we were a bit confused.

Thanks very much!

Best regards,
Stefanie
________________________________
寄件者: Sunnyiscoming ***@***.***>
寄件日期: Wednesday, September 13, 2023 9:19:01 PM
收件者: filecoin-project/filecoin-plus-large-datasets ***@***.***>
副本: ChainOnHK ***@***.***>; Mention ***@***.***>
主旨: Re: [filecoin-project/filecoin-plus-large-datasets] [DataCap Application] ChainOn Technology (HK) Limited (Issue #2180)


Any update here?
