### ISSUE TITLE
[DataCap Application] <NOAA> - <NBM>

### ISSUE THREAD

**Issue by CarmineZc** [filecoin-project/filecoin-plus-large-datasets#2181]
### Data Owner Name

NOAA

### What is your role related to the dataset

Data Preparer

### Data Owner Country/Region

United States

### Data Owner Industry

Environment

### Website

https://vlab.noaa.gov/web/mdl/nbm

### Social Media

```text
Twitter---https://twitter.com/NOAA
Youtube---https://www.youtube.com/usnoaagov
```

### Total amount of DataCap being requested

15PiB

### Expected size of single dataset (one copy)

1084TiB

### Number of replicas to store

10

### Weekly allocation of DataCap requested

1PiB

### On-chain address for first allocation

f1xkuqhfkmxsvlb546oppidbhh7yed7rwg4syteii

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
The National Blend of Models (NBM) is a nationally consistent and skillful suite of calibrated forecast guidance based on a blend of both NWS and non-NWS numerical weather prediction model data and post-processed model guidance. The goal of the NBM is to create a highly accurate, skillful and consistent starting point for the gridded forecast. The NBM is considered an important part of the efforts to evolve NWS capabilities to achieve a Weather-Ready Nation.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
National Blend of Models (NBM) COG Format
National Blend of Models (NBM) Grib2 Format
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### If you are a data preparer. What is your location (Country/Region)

Hong Kong

### If you are a data preparer, how will the data be prepared? Please include tooling used and technical details?

```text
Lotus/Singularity
```

### Has this dataset been stored on the Filecoin network before? If so, please explain and make the case why you would like to store this dataset again to the network. Provide details on preparation and/or SP distribution.

```text
No. And I will find more SPs to store this data in different regions.
```

### Please share a sample of the data

```text
s3://noaa-nbm-pds/
s3://noaa-nbm-grib2-pds/
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

More than 3 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, Europe

### How will you be distributing your data to storage providers

HTTP or FTP server, IPFS, Shipping hard drives, Lotus built-in data transfer

### How do you plan to choose storage providers

Slack, Filmine, Big Data Exchange, Partners

### If you already have a list of storage providers to work with, fill out their names and provider IDs below

```text
f0671982 Central, HK
f01820802 Dongguan, Guangdong
f02169597 SZ, CN
f02247136 Langfang,Hebei
```

### How do you plan to make deals to your storage providers

Boost client, Lotus client, Singularity

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
- Have you prepared enough token for sector pledge?
- Per the https://github.com/filecoin-project/notary-governance/issues/922 for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

**Comment by herrehesse** [comment]
Not supportive, throwaway account asking for 15P with no reputation.

**Comment by CarmineZc** [comment]
@Sunnyiscoming Yes. Sps will prepare it.
![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/141728588/48475c1a-9567-41de-9e4f-4d0a45e48a33)
Filled the form.

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 15PiB

**Expected weekly DataCap usage rate**
> 1PiB

**Client address**
>f1xkuqhfkmxsvlb546oppidbhh7yed7rwg4syteii

**Comment by a1991car** [comment]
The first round, support, will continue to pay attention

**Comment by a1991car** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecz6p56ht6nczhfdqfzrar2rjbotb2tkhzr47thzbrgng6dubxt5y 
#### Address 
> f1xkuqhfkmxsvlb546oppidbhh7yed7rwg4syteii
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f1qnumecdypgrbaebtkdfjnwt5ndacadcuas3deiq
#### Id
> 078154f6-628f-4fa5-b1e6-ade5920e74c7
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecz6p56ht6nczhfdqfzrar2rjbotb2tkhzr47thzbrgng6dubxt5y

**Comment by Casey-PG** [comment]
Glad to support your first round.

**Comment by Casey-PG** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaq7gbwxu2xnn3f4zpij37o6s4bleweowq7gy2lna3gm6rn44cs4c 
#### Address 
> f1xkuqhfkmxsvlb546oppidbhh7yed7rwg4syteii
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f1d4yb3wags3mtddzesxoo63jv7dmlec3bq4yteni
#### Id
> 078154f6-628f-4fa5-b1e6-ade5920e74c7
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaq7gbwxu2xnn3f4zpij37o6s4bleweowq7gy2lna3gm6rn44cs4c

**Comment by CarmineZc** [comment]
Keep open.

**Comment by herrehesse** [comment]
checker:manualTrigger

**Comment by herrehesse** [comment]
checker:manualTrigger

**Comment by herrehesse** [comment]
checker:manualTrigger

**Comment by CarmineZc** [comment]
Sure. Everything is fine.

**Comment by BobbyChoii** [comment]
LGTM, willing to support.

**Comment by herrehesse** [comment]
@BobbyChoii what "looks good" exactly?

**Comment by BobbyChoii** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedczpzmtytmajdijz75f47s6bbtjiw27hkijxrfvbzlwnox6g2e2q 
#### Address 
> f1xkuqhfkmxsvlb546oppidbhh7yed7rwg4syteii
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f1irqs2gmctiv3jcdfwuch7oxvf4ixh3k4b2wc24i
#### Id
> cfa266bd-fc75-4a0b-a4ae-8bf695a8911b
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedczpzmtytmajdijz75f47s6bbtjiw27hkijxrfvbzlwnox6g2e2q

**Comment by Suyanj** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacea2arrajrmuff6x2f25rtnppnw4pysvkhkzg5ae6fi2xvzrh5o6jg 
#### Address 
> f1xkuqhfkmxsvlb546oppidbhh7yed7rwg4syteii
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f1ihv7gz3vn3xqvikpt4rwryecgisl7745lodx3yi
#### Id
> cfa266bd-fc75-4a0b-a4ae-8bf695a8911b
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacea2arrajrmuff6x2f25rtnppnw4pysvkhkzg5ae6fi2xvzrh5o6jg

**Comment by Filplus-govteam** [comment]
SPs taking deals
f02234029 | Central, Central and Western, HKBIH-Global Internet Harbor | 50.00 TiB | 10.55% | 50.00 TiB | 0.00%
f02208475 | Shenzhen, Guangdong, CNCHINANET-BACKBONE | 168.00 TiB | 35.45% | 168.00 TiB | 0.00%
f02834511new | Hong Kong, Central and Western, HKHK Cable TV Ltd | 33.72 TiB | 7.12% | 33.72 TiB | 0.00%
f02035545 | Nanjing, Jiangsu, CNJiangsu Wuxi International IDC network | 134.16 TiB | 28.31% | 134.16 TiB | 0.00%
f02368314 | Deyang, Sichuan, CNSichuan Chuanxn IDC | 88.00 TiB | 18.57% | 88.00 TiB | 0.00%

SPs on unfront list
SP 1	f0671982	Sam	no	no	Central, HK	no	Sam
SP 2	f01820802	Paul	no	no	Dongguan, Guangdong	no	Paul
SP 3	f02169597	Edwin	no	SZ, CN	no	no
SP 4	f02247136	Vincent	no	no	Langfang,Hebei	no	Vincent
SP 5	-	-	-	-	-	-	-

SPs do not match and SPs provided have no clear entity or distribution information, closing until updated
