### ISSUE TITLE
[DataCap Application] <Kena> - <teas>

### ISSUE THREAD

**Issue by youDreamer** [filecoin-project/filecoin-plus-large-datasets#2182]
### Data Owner Name

Xiamen Kena Tea Co., Ltd

### What is your role related to the dataset

Data Preparer

### Data Owner Country/Region

China

### Data Owner Industry

Resources, Agriculture & Fisheries

### Website

QQ: 453398548

### Social Media

```text
http://kn.zzys.group/kn.png
QQ:453398548
```

### Total amount of DataCap being requested

5PiB

### Expected size of single dataset (one copy)

 500TiB

### Number of replicas to store

10

### Weekly allocation of DataCap requested

500TiB

### On-chain address for first allocation

f1hggb5aiksj73aae6kca77fqhgqrl7d2lphtq6ry

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Chinese people drinking tea is not only a habit, but also an accumulation of historical and cultural heritage. This culture has lasted for thousands of years.
The Tea Road was once a new international trade route that emerged on the Eurasian continent after the decline of the world-renowned Silk Road. It has promoted the widespread dissemination of traditional Chinese culture, with tea culture as the main body, in Russia and even Europe; Communication and exchange between Chinese civilization and world civilization. Its influence continues to this day.
Undoubtedly, the Tea Road opened the closed doors of ancient empires, leaving behind a precious historical memory for future generations.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
Tea culture is a type of culture that uses tea as a carrier and aims to reflect the traditional ideology, morality, and humanistic spirit of Eastern countries, including data related to tea etiquette, customs, tea laws, tea regulations, tea techniques, and tea art
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### If you are a data preparer. What is your location (Country/Region)

None

### If you are a data preparer, how will the data be prepared? Please include tooling used and technical details?

```text
BOOST LOTUS
```

### Please share a sample of the data

```text
https://drive.google.com/drive/folders/1aC9p75oxaaJMQCF8LJcQdrqHZKnjjYbF?usp=sharing
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Weekly

### For how long do you plan to keep this dataset stored on Filecoin

2 to 3 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, Europe

### How will you be distributing your data to storage providers

HTTP or FTP server, Lotus built-in data transfer

### How do you plan to choose storage providers

Slack, Partners

### If you already have a list of storage providers to work with, fill out their names and provider IDs below

```text
f023013	  	      hong kong
f0158156  	      Korea
f02337006	      England
f02306912             Iran
```

### How do you plan to make deals to your storage providers

Boost client, Lotus client, Singularity

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
- http://kn.zzys.group/kn.png is not available. Please check it.
- Please introduce your organization. What's the relationship between you and the oragnization?
- Have you prepared enough token for sector pledge?
- Per the https://github.com/filecoin-project/notary-governance/issues/922 for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

**Comment by youDreamer** [comment]
> * http://kn.zzys.group/kn.png

![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/143373399/67ed32c7-ba95-4995-af98-2666d1b50482)
> * http://kn.zzys.group/kn.png is not available. Please check it.
Can be accessed normally, may need to wait for a while. This is the company promotional page, and the website WeChat mini program is still under construction

> * Please introduce your organization. What's the relationship between you and the oragnization?
Xiamen Kena Tea Co., Ltd.  Company management personnel
> * Have you prepared enough token for sector pledge?
Yes, our partners have prepared enough tokens to set sail at any time
> * Per the [Modification: Changes required to public open dataset application flow notary-governance#922](https://github.com/filecoin-project/notary-governance/issues/922) for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

**Comment by youDreamer** [comment]
The form has been completed

**Comment by herrehesse** [comment]
@youDreamer please add the contact information of the SP entities you are working with to store copies of the data.

**Comment by youDreamer** [comment]
> @youDreamer please add the contact information of the SP entities you are working with to store copies of the data.

Thank you for your question, the contact information for the SP entity has been submitted in the form.
![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/143373399/9d24d1f8-b4c8-4876-b13d-6f89a53728ed)

**Comment by youDreamer** [comment]
> Could you send an email with business license to [filplus-app-review@fil.org](mailto:filplus-app-review@fil.org) with your official domain in order to confirm your identity? Email name should includes the issue id #2182. 
![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/143373399/3e502db9-d430-49b6-aa51-56ac7f0ccb8d)
Mail has been sent
Where are these data from? Can you provide more data samples or relative materials to prove that you have 500 TB data already?
Part of the data comes from the company, promoting tea culture through filming and editing, and part comes from online tea friends, inheriting tea culture

**Comment by youDreamer** [comment]
> Could you send an email with business license to [filplus-app-review@fil.org](mailto:filplus-app-review@fil.org) with your official domain in order to confirm your identity? Email name should includes the issue id #2182. Where are these data from? Can you provide more data samples or relative materials to prove that you have 500 TB data already?

![4ee780b11075041443c084c5618d142](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/143373399/5211c5f4-d1c4-4dc3-b75a-91d080456639)
![368f845a1772b884752974467e88e52](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/143373399/15f87dcd-44de-4cd4-b6ab-feb9d70e5cd7)
This is our strength.

**Comment by herrehesse** [comment]
Why are you triggering this @Sunnyiscoming ?

@youDreamer please add the contact information of the SP entities you are working with to store copies of the data.

**Comment by herrehesse** [comment]
@Sunnyiscoming There are no miners in Iran and England. Stop accepting their VPN lies. It is not true.

**Comment by youDreamer** [comment]
> There are no miners in Iran and England. Stop accepting their VPN lies. It is not true.

SP contacted me and informed them that they are from there

**Comment by herrehesse** [comment]
@youDreamer You are deceiving the Filecoin community and it is extremely harmful. @Sunnyiscoming you are facilitating this behaviour.

**Comment by youDreamer** [comment]
> @youDreamer You are deceiving the Filecoin community and it is extremely harmful. @Sunnyiscoming you are facilitating this behaviour.

I will strictly comply with the relevant treaties and will actively seek to resolve the situation.

**Comment by youDreamer** [comment]
wait

**Comment by youDreamer** [comment]
> wait

wait

**Comment by youDreamer** [comment]
> wait

wait

**Comment by youDreamer** [comment]
> This application has not seen any responses in the last 10 days. This issue will be marked with Stale label and will be closed in 4 days. Comment if you want to keep this application open.
> 
> -- Commented by Stale Bot.

wait

**Comment by kevzak** [comment]
SPs provided upfront:

f02337006 | eager | England | / | /
f023013 | jastin | hong kong | / | /
f0158156 | jack | Korea | / | /
f02306912 | TIting | Iran

**Comment by kevzak** [comment]
@youDreamer please provide proof of location for SPs. Closing until provided
