### ISSUE TITLE
[DataCap Application] ESGF and Pangeo - CMIP6

### ISSUE THREAD

**Issue by Nevada74** [filecoin-project/filecoin-plus-large-datasets#2191]
### Data Owner Name

Pangeo Community

### What is your role related to the dataset

Dataset Preparer

### Data Owner Country/Region

United States

### Data Owner Industry

Life Science / Healthcare

### Website

https://pcmdi.llnl.gov/CMIP6/

### Social Media

```text
https://pangeo-data.github.io/pangeo-cmip6-cloud/
https://wcrp-cmip.org/cmip-phase-6-cmip6/
```

### Total amount of DataCap being requested

15PiB

### Expected size of single dataset (one copy)

1760TiB

### Number of replicas to store

8

### Weekly allocation of DataCap requested

1PiB

### On-chain address for first allocation

f1fi5h6gp3xp5kbierzi7ycn55kontg7mc4nmrn2a

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
The sixth phase of global coupled ocean-atmosphere general circulation model ensemble. The WCRP Working Group on Coupled Modelling (WGCM) oversees the Coupled Model Intercomparison Project, which is now in its 6th phase.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
Zarr formatted data and Netcdf formatted data managed by the Earth System Grid Federation
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### If you are a data preparer. What is your location (Country/Region)

Hong Kong

### If you are a data preparer, how will the data be prepared? Please include tooling used and technical details?

```
use lotus
```

### Has this dataset been stored on the Filecoin network before? If so, please explain and make the case why you would like to store this dataset again to the network. Provide details on preparation and/or SP distribution.

```
This is a updating dataset. So I choose to help store it in filecoin.
```

### Please share a sample of the data

```
s3://cmip6-pds/
s3://esgf-world/
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

More than 3 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, Europe

### How will you be distributing your data to storage providers

HTTP or FTP server, Shipping hard drives, Lotus built-in data transfer

### How do you plan to choose storage providers

Slack, Big Data Exchange, Partners

### If you already have a list of storage providers to work with, fill out their names and provider IDs below
```
This is a preliminary plan of SPs. We plan find more SPs to work together.
f01808139|HongKong
f01931631|Dongguan
f02233608|Chengdu
f01084913|HongKong
```
### How do you plan to make deals to your storage providers

Boost client, Lotus client, Singularity

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
- Please adjust value of Total amount of DataCap being requested(Expected size of single dataset (one copy)*Number of replicas to store) to 5PiB
- Have you prepared enough token for sector pledge?
- Are you a data preparer? What is your previous experience as a data-preparer? List previous applications and client IDs
- How will the data be prepared? Please include tooling used and technical details
- If you are not preparing the data, who will prepare the data?  (Name and Business)
- Has this dataset been stored on Filecoin before? If so, why are you choosing to store it again?
- Best practice for storing large datasets includes ideally, storing it in 3 or more regions, with 4 or more storage provider operators or owners.You should list Miner ID, Business Entity, Location of sps you will cooperate with.
- Per the https://github.com/filecoin-project/notary-governance/issues/922 for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

**Comment by herrehesse** [comment]
Newly created throwaway account asking for 15PiB, not supportive.

**Comment by Nevada74** [comment]
@jbesraa Why did you change my application into another one?

@Sunnyiscoming 
I saw that someone edited my application. Now I have reedited my application into previous comments.
Sps can prepare it.
Yes. I'm a data preparer and this is the first time I go to apply datacap.
We will use lotus to prepare data into car files.
I don't know. But this is a updating dataset, more and more new data will be stored in filecoin.
OK. I'll put the information into the form. Please check it.

**Comment by Nevada74** [comment]
@herrehesse What is throwaway account? Who are you?

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 15PiB

**Expected weekly DataCap usage rate**
> 1PiB

**Client address**
>f1fi5h6gp3xp5kbierzi7ycn55kontg7mc4nmrn2a

**Comment by herrehesse** [comment]
@Sunnyiscoming 

It's imperative that the approval of these applications isn't taken lightly.
Miners seem to be failing in supplying adequate retrievals (refer to: [issue link](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/2014)).
Additionally, there is a noticeable concentration of miners in a single region.
The utilization of disposable accounts continues, seemingly to bypass previous vetting processes and maintain anonymity.
The creation of a new account requesting 15 million gigabytes is absolutely alarming, especially considering the lack of established reputation. How is this even being considered for approval?

@galen-mcandrew @kevzak @raghavrmadya Please check!

**Comment by Nevada74** [comment]
All Sps I provided above can be retrieved. I have examined in https://retrievalbot-dashboard.vercel.app/. We still finding more SPs for this process. Don't worry about that, we'll insist on checking the sp's qualifications in the next progress.

**Comment by Bitrise0111** [comment]
Since you must align with the nodes you previously disclosed, you'd better disclose some other nodes from the time of application to now.

**Comment by Nevada74** [comment]
@Bitrise0111 OK. In our list of SPs, there's also f01882035, f01563172 and f01152462.

**Comment by Bitrise0111** [comment]
We'd like to give support for the first round. You need to seal the node as you disclosed one, and we'll check it randomly.

**Comment by Bitrise0111** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec7rlhp26xqmy5i7jrrxs4y4vlkjphpfvb6iysalrouky5rgmrws4 
#### Address 
> f1fi5h6gp3xp5kbierzi7ycn55kontg7mc4nmrn2a
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f1nknj7ayq4o43czrtdoauggtwl43fbqatmqis3yy
#### Id
> a72c2f38-9499-4711-aafb-3d364557ead7
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec7rlhp26xqmy5i7jrrxs4y4vlkjphpfvb6iysalrouky5rgmrws4

**Comment by herrehesse** [comment]
@Bitrise0111 - please revoke your allocation - @kevzak please check this kind of behaviour is unacceptable. Gaming the system.

**Comment by Nevada74** [comment]
Without any evidence, you can not discredit others. There's no problem about my application. Don't be so rude.

> @Bitrise0111 - please revoke your allocation - @kevzak please check this kind of behaviour is unacceptable. Gaming the system.

**Comment by Nevada74** [comment]
Yes, wait for next step.

**Comment by Nevada74** [comment]
Yes!

**Comment by kevzak** [comment]
No SP entities or contacts provided
