### ISSUE TITLE
[DataCap Application] DAG House - Web3.Storage

### ISSUE THREAD

**Issue by dchoi27** [filecoin-project/filecoin-plus-large-datasets#2192]
### Data Owner Name

DAG House and the users of our tools

### What is your role related to the dataset

Data onramp entity that provides data onboarding services to multiple clients

### Data Owner Country/Region

United States

### Data Owner Industry

Web3 / Crypto

### Website

https://web3.storage/

### Social Media

```text
https://twitter.com/web3storage
https://www.linkedin.com/company/dag-house
```

### Total amount of DataCap being requested

15PiB

### Expected size of single dataset (one copy)

500TiB and growing

### Number of replicas to store

10

### Weekly allocation of DataCap requested

250TiB

### On-chain address for first allocation

f3se4aw3p3tlvggkhsymdg7qmbjnxu4uudjvar6c3scfwsge6voesbxff4lkoiqyjcl4yot7hxqmukhusxgurq

### Data Type of Application

Public, Open Commercial/Enterprise

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
DAG House was founded in 2021 as a team inside Protocol Labs to develop tools to make it easy for developers and end users to host content addressed data and store the data on Filecoin. Since then our two flagship products, NFT.Storage (Internet Archive of NFTs) and Web3.Storage (developer storage platform) are used by many prominent projects and companies in Web3 and outside of it.
```

### Is this project associated with other projects/ecosystem stakeholders?

Yes

### If answered yes, what are the other projects/ecosystem stakeholders

```text
This project is associated with Protocol Labs. Projects have plans for independence.
```

### Describe the data being stored onto Filecoin

```text
User uploads that meet or adhere to web3.storage's terms of service (https://web3.storage/terms).
```

### Where was the data currently stored in this dataset sourced from

Other

### If you answered "Other" in the previous question, enter the details here

```text
User uploads (generally for their web3 apps)
```

### If you are a data preparer. What is your location (Country/Region)

None

### Has this dataset been stored on the Filecoin network before? If so, please explain and make the case why you would like to store this dataset again to the network. Provide details on preparation and/or SP distribution.

```text
The goal is to be able to use the Filecoin copies as the only available copies on the network (rather than also storing the data on centralized infra), which requires things like retrieval to have high performance and global availability. As a result, some parts of the dataset have already been stored but not to the replication limit with other Datacap apps (https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1838, https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/2110).
```

### Please share a sample of the data

```text
This platform serves all different kinds of media, including images, files, and videos. Some examples:

https://ipfs.io/ipfs/bafybeid5jpdqzlb4tqsd6peoa7qstoxat3ovsg62wutyp4gnzqbqsggfsq
https://ipfs.io/ipfs/bafybeihity6bx24npzvvkzopjbat25ekefjwmnshe7rvldy72dxngzf644
https://ipfs.io/ipfs/bafybeicvcevx3ktiqjsfwnjguu4lnzejlhgb35brayuod5xdtn7demfdhe
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Daily

### For how long do you plan to keep this dataset stored on Filecoin

Permanently

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, Africa, North America, South America, Europe, Australia (continent)

### How will you be distributing your data to storage providers

HTTP or FTP server

### How do you plan to choose storage providers

Others

### If you answered "Others" in the previous question, what is the tool or platform you plan to use

```text
We plan to use Spade for SP selection and deal execution. Spade is being developed by the Data Programs team at Protocol Labs (https://github.com/data-preservation-programs/spade) and supports storage client to SP matching based on requirements like geography, size, retrievability, etc.
```

### How do you plan to make deals to your storage providers

Others/custom tool

### If you answered "Others/custom tool" in the previous question, enter the details here

```text
We plan to use Spade for deal execution to onboard data to Filecoin. Spade is being developed by the Data Programs team at Protocol Labs (https://github.com/data-preservation-programs/spade).

Spade was initially servicing Slingshot deals and was referred to as the Evergreen Dealer.
```

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by simonkim0515** [comment]
## Datacap Request Trigger

#### Total DataCap requested 
> 15PiB

#### Expected weekly DataCap usage rate 
> 250TiB 

#### Client address
> f3se4aw3p3tlvggkhsymdg7qmbjnxu4uudjvar6c3scfwsge6voesbxff4lkoiqyjcl4yot7hxqmukhusxgurq

**Comment by simonkim0515** [comment]
## Datacap Request Trigger

#### Total DataCap requested 
> 15PiB

#### Expected weekly DataCap usage rate 
> 250TiB 

#### Client address
> f3se4aw3p3tlvggkhsymdg7qmbjnxu4uudjvar6c3scfwsge6voesbxff4lkoiqyjcl4yot7hxqmukhusxgurq

**Comment by cryptowhizzard** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceawtxdf2sqbes7dp3s56jqt7qyabxxz5tkpzlncsghtqz3hvlfdq2 
#### Address 
> f3se4aw3p3tlvggkhsymdg7qmbjnxu4uudjvar6c3scfwsge6voesbxff4lkoiqyjcl4yot7hxqmukhusxgurq
#### Datacap Allocated
> 125.00TiB
#### Signer Address
> f1krmypm4uoxxf3g7okrwtrahlmpcph3y7rbqqgfa
#### Id
> 1a683d47-7859-4670-9afc-b28fb0611030
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceawtxdf2sqbes7dp3s56jqt7qyabxxz5tkpzlncsghtqz3hvlfdq2

**Comment by liyunzhi-666** [comment]
I have been following and supporting the program before. I can continue to support it this time as well. Looking forward to excellent performance afterwards.

**Comment by liyunzhi-666** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec7gqldor3rgjulokq63qrmvytxiu45sblysrmijrodkybmyu2usu 
#### Address 
> f3se4aw3p3tlvggkhsymdg7qmbjnxu4uudjvar6c3scfwsge6voesbxff4lkoiqyjcl4yot7hxqmukhusxgurq
#### Datacap Allocated
> 125.00TiB
#### Signer Address
> f1pszcrsciyixyuxxukkvtazcokexbn54amf7gvoq
#### Id
> 1a683d47-7859-4670-9afc-b28fb0611030
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec7gqldor3rgjulokq63qrmvytxiu45sblysrmijrodkybmyu2usu

**Comment by Patapon0702** [comment]
checker:manualTrigger

**Comment by Patapon0702** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecptph7iozs3gjlsgwde4vfsqikihobcf6sbnayvatdykicmwwgj4 
#### Address 
> f3se4aw3p3tlvggkhsymdg7qmbjnxu4uudjvar6c3scfwsge6voesbxff4lkoiqyjcl4yot7hxqmukhusxgurq
#### Datacap Allocated
> 250.00TiB
#### Signer Address
> f1ho2liobpznr7llma6xcl7jtififsfvhdnudn4yy
#### Id
> 735ec2b8-7292-48e0-8bef-5f41eb534dff
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecptph7iozs3gjlsgwde4vfsqikihobcf6sbnayvatdykicmwwgj4

**Comment by cryptowhizzard** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecbnk3mre6r7obslof4tmextmcgjfimkxhh5bpmymt5ig7pvqbooa 
#### Address 
> f3se4aw3p3tlvggkhsymdg7qmbjnxu4uudjvar6c3scfwsge6voesbxff4lkoiqyjcl4yot7hxqmukhusxgurq
#### Datacap Allocated
> 250.00TiB
#### Signer Address
> f1krmypm4uoxxf3g7okrwtrahlmpcph3y7rbqqgfa
#### Id
> 735ec2b8-7292-48e0-8bef-5f41eb534dff
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecbnk3mre6r7obslof4tmextmcgjfimkxhh5bpmymt5ig7pvqbooa

**Comment by cryptowhizzard** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecy5dojl23opqqhgey76fs5nxa45znrarwtzpnad55iyng5m3muxs 
#### Address 
> f3se4aw3p3tlvggkhsymdg7qmbjnxu4uudjvar6c3scfwsge6voesbxff4lkoiqyjcl4yot7hxqmukhusxgurq
#### Datacap Allocated
> 500.00TiB
#### Signer Address
> f1krmypm4uoxxf3g7okrwtrahlmpcph3y7rbqqgfa
#### Id
> 2bf30b49-1406-48e8-889d-2bae95955d8d
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecy5dojl23opqqhgey76fs5nxa45znrarwtzpnad55iyng5m3muxs

**Comment by jamerduhgamer** [comment]
checker:manualTrigger

**Comment by jamerduhgamer** [comment]
# of SPs sealing the dataset has increased. f010202 has more than 50% datacap but it is only ~46 TiBs.

Willing to support this next tranche of datacap.

**Comment by jamerduhgamer** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecmucctg7dnihxwcu7w2t73y6gmriixijhqz2zh64b6dopj3wnpko 
#### Address 
> f3se4aw3p3tlvggkhsymdg7qmbjnxu4uudjvar6c3scfwsge6voesbxff4lkoiqyjcl4yot7hxqmukhusxgurq
#### Datacap Allocated
> 500.00TiB
#### Signer Address
> f1kqdiokoeubyse4qpihf7yrpl7czx4qgupx3eyzi
#### Id
> 2bf30b49-1406-48e8-889d-2bae95955d8d
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecmucctg7dnihxwcu7w2t73y6gmriixijhqz2zh64b6dopj3wnpko

**Comment by dannyob** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedg7jwfsjetslzyboturqjrkerzikspcsgal6efhr5djjfozteqcw 
#### Address 
> f3se4aw3p3tlvggkhsymdg7qmbjnxu4uudjvar6c3scfwsge6voesbxff4lkoiqyjcl4yot7hxqmukhusxgurq
#### Datacap Allocated
> 500.00TiB
#### Signer Address
> f1k6wwevxvp466ybil7y2scqlhtnrz5atjkkyvm4a
#### Id
> 2bf30b49-1406-48e8-889d-2bae95955d8d
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedg7jwfsjetslzyboturqjrkerzikspcsgal6efhr5djjfozteqcw

**Comment by dchoi27** [comment]
keep open

**Comment by dchoi27** [comment]
keep open

**Comment by dchoi27** [comment]
leave open

**Comment by dchoi27** [comment]
keep open

**Comment by dchoi27** [comment]
keep open

**Comment by Sunnyiscoming** [comment]
Hello, @dchoi27 per the https://github.com/filecoin-project/notary-governance/issues/922 for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

This information will be reviewed by Fil+ Governance team to confirm validity and then the application will be allowed to move forward for additional notary review.

**Comment by cryptowhizzard** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec7psbzkcrlviwmt7y7e2rjxeifqvtjis6kxlorhf5spalrci4gt6 
#### Address 
> f3se4aw3p3tlvggkhsymdg7qmbjnxu4uudjvar6c3scfwsge6voesbxff4lkoiqyjcl4yot7hxqmukhusxgurq
#### Datacap Allocated
> 1000.00TiB
#### Signer Address
> f1krmypm4uoxxf3g7okrwtrahlmpcph3y7rbqqgfa
#### Id
> e36061ee-9538-43dd-af79-463e149a8bb9
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec7psbzkcrlviwmt7y7e2rjxeifqvtjis6kxlorhf5spalrci4gt6

**Comment by liyunzhi-666** [comment]
> Client f02759235 does not follow the datacap usage rules. More info [here](https://github.com/filecoin-project/notary-governance/issues/986). This application has been failing the requirements for 43 days. Please take appropiate action to fix the following DataCap usage problems.
> 
> Criteria	Treshold	Reason
> Shared data percent	< 20%	20.57% of the clients data is shared with other clients. This should be less than 20%

Hi @dchoi27 Can you explain this?

**Comment by dchoi27** [comment]
Nothing has changed from before - we use Spade to make deals publicly, and any SP is available to onboard our data that way. Ideally the distribution is flatter, but if not, it's more a reflection of the willingness of SPs to onboard data rather than anything we're doing.

**Comment by liyunzhi-666** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebz6n5jmluohloyfvic4ko4hmmli7bclxcjlblrpu72chm23f6624 
#### Address 
> f3se4aw3p3tlvggkhsymdg7qmbjnxu4uudjvar6c3scfwsge6voesbxff4lkoiqyjcl4yot7hxqmukhusxgurq
#### Datacap Allocated
> 1000.00TiB
#### Signer Address
> f1pszcrsciyixyuxxukkvtazcokexbn54amf7gvoq
#### Id
> e36061ee-9538-43dd-af79-463e149a8bb9
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebz6n5jmluohloyfvic4ko4hmmli7bclxcjlblrpu72chm23f6624

**Comment by dchoi27** [comment]
Do not close

**Comment by dchoi27** [comment]
keep open

**Comment by dchoi27** [comment]
keep open

**Comment by dchoi27** [comment]
keep open, cc @heyjay (for future datacap management)

**Comment by heyjay44** [comment]
Hey, just commenting as I'll be taking this over.

**Comment by heyjay44** [comment]
keep open

**Comment by kevzak** [comment]
@heyjay44 this pathway is no longer active. You can apply for more DataCap here if you are interested: https://github.com/fidlabs/Open-Data-Pathway/issues/new/choose
