### ISSUE TITLE
[DataCap Application] <Organization> - <Project Name>

### ISSUE THREAD

**Issue by ymhaihao** [filecoin-project/filecoin-plus-large-datasets#2193]
### Data Owner Name

Common Crawl

### What is your role related to the dataset

Data Preparer

### Data Owner Country/Region

United States

### Data Owner Industry

Life Science / Healthcare

### Website

https://commoncrawl.org/

### Social Media

```text
https://commoncrawl.org/
```

### Total amount of DataCap being requested

15PiB

### Expected size of single dataset (one copy)

1.5PiB

### Number of replicas to store

10

### Weekly allocation of DataCap requested

1PiB

### On-chain address for first allocation

f1m5fcvbtgn3rzg5qzzazcm7l6xgbzy7ullwbstgy

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
The corpus contains raw web page data, metadata extracts, and text extracts.

Common Crawl data is stored on Amazon Web Services’ Public Data Sets and on multiple academic cloud platforms across the world.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
The corpus contains raw web page data, metadata extracts, and text extracts.

Common Crawl data is stored on Amazon Web Services’ Public Data Sets and on multiple academic cloud platforms across the world.
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### If you are a data preparer. What is your location (Country/Region)

China

### Please share a sample of the data

```text
https://commoncrawl.org/
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Monthly

### For how long do you plan to keep this dataset stored on Filecoin

1 to 1.5 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, Australia (continent)

### How will you be distributing your data to storage providers

Cloud storage (i.e. S3), IPFS, Shipping hard drives, Lotus built-in data transfer

### How do you plan to choose storage providers

Slack, Filmine

### How do you plan to make deals to your storage providers

Boost client, Lotus client, Singularity

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
Have you prepared enough token for sector pledge?
Are you a data preparer? What is your previous experience as a data-preparer? List previous applications and client IDs
How will the data be prepared? Please include tooling used and technical details
If you are not preparing the data, who will prepare the data? (Name and Business)
Has this dataset been stored on Filecoin before? If so, why are you choosing to store it again?
Best practice for storing large datasets includes ideally, storing it in 3 or more regions, with 4 or more storage provider operators or owners.You should list Miner ID, Business Entity, Location of sps you will cooperate with.
Per the https://github.com/filecoin-project/notary-governance/issues/922 for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

**Comment by herrehesse** [comment]
Not supportive of newly created account requesting 15PiB. Too much too soon, no reputation.
