### ISSUE TITLE
[DataCap Application] <HUOHUA>

### ISSUE THREAD

**Issue by mingyang313** [filecoin-project/filecoin-plus-large-datasets#2195]
### Data Owner Name

HUOHUA

### What is your role related to the dataset

Data Preparer

### Data Owner Country/Region

Hong Kong

### Data Owner Industry

Education & Training

### Website

https://www.huohua.cn/

### Social Media

```text
https://www.huohua.cn/
```

### Total amount of DataCap being requested

5PiB

### Expected size of single dataset (one copy)

500t

### Number of replicas to store

8

### Weekly allocation of DataCap requested

800TiB

### On-chain address for first allocation

f1tzehoozaa33ns42eac42kwboczlnfov4w7xoj7i

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
The Spark Thinking project was established in December 2017. It mainly adopts the method of small class live broadcast class and real-person interactive AI class. Through the inspiration and guidance of the teacher and the three-dimensional combination of animation, games, and interesting teaching aids, it integrates knowledge, ability, and thinking. Interconnected and progressive, cultivate core basic abilities such as logical reasoning and independent problem-solving in interactive practice, and lay a good foundation for future lifelong learning.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
1. Live class video.
2. Real-person interactive AI class video.
3. Videos of animation, games, and interesting teaching aids.
```

### Where was the data currently stored in this dataset sourced from

Other

### If you answered "Other" in the previous question, enter the details here

```text
Online Educational Videos on aliyun.
```

### If you are a data preparer. What is your location (Country/Region)

China

### If you are a data preparer, how will the data be prepared? Please include tooling used and technical details?

```text
lotus,boost,singularity
```

### Has this dataset been stored on the Filecoin network before? If so, please explain and make the case why you would like to store this dataset again to the network. Provide details on preparation and/or SP distribution.

```text
Try new things, embrace blockchain, save filing costs.
I need a lot of sp from China, and some sp from Hong Kong, Singapore, I am going to store 10 copies.
```

### Please share a sample of the data

```text
https://drive.google.com/file/d/1diSVPWmCNLjBxaoxhBX4PrAztxbbTgF4/view?usp=share_link
https://drive.google.com/file/d/1sF3r2zbNyqK9DmHuKMDCELY9xq-J_2u4/view?usp=share_link
https://drive.google.com/file/d/1XIMu4p6WYte5D6OUpCq0F_qotsf0jI9f/view?usp=share_link
https://drive.google.com/file/d/1Jmer6bVXHKbu8HIFyU_IusKpC9QyyFDS/view?usp=share_link
https://drive.google.com/file/d/1wJxQXfmfq5YG97UkgOrUbUmGXI6tGB6_/view?usp=share_link
https://drive.google.com/file/d/1SmR_gfaLcJO7UliIilUXIxb0hr-SGndg/view?usp=share_link
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

1.5 to 2 years

### In which geographies do you plan on making storage deals

Greater China

### How will you be distributing your data to storage providers

HTTP or FTP server

### How do you plan to choose storage providers

Slack, Big Data Exchange, Partners

### If you already have a list of storage providers to work with, fill out their names and provider IDs below

```text
f02086436 Singapore, SG Leaseweb Asia Pacific pte. ltd.
f02053449 Hong Kong, Central and Western, HK IPTELECOM Global.
f02060013 Paripark, Seoul, KR The Constant Company, LLC.
f02051558 Shenzhen, Guangdong, CN China Telecom (Group).
```

### How do you plan to make deals to your storage providers

Boost client, Lotus client, Singularity

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
- Could you send an email to filplus-app-review@fil.org with your official domain in order to confirm your identity? Email name should includes the issue id #2195.
- Have you prepared enough token for sector pledge?
- What is your previous experience as a data-preparer? List previous applications and client IDs
- Has this dataset been stored on Filecoin before? If so, why are you choosing to store it again?
- Per the https://github.com/filecoin-project/notary-governance/issues/922 for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

**Comment by mingyang313** [comment]
1.yes,i had sent email,please check.
2.yes,i have enough token.
3.Yes, I already have some experience, and I am familiar with the FIL+ rules.
4.firstly stored on Filecoin.
5.kyc had been finished,please check.
@Sunnyiscoming 
![77841694058180_ pic](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/37865375/b9e8e2a5-143c-432d-95fd-b5483e40d637)
![26091693927939_ pic](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/37865375/4b0a3e86-993e-48fe-bafa-00a9230d4e0b)

**Comment by Sunnyiscoming** [comment]
Have you submitted the form(https://form.jotform.com/231862753015656)? Can you check again?

**Comment by mingyang313** [comment]
> Have you submitted the form(https://form.jotform.com/231862753015656)? Can you check again?

Yes, I can confirm that I have submitted it. @Sunnyiscoming

**Comment by herrehesse** [comment]
@mingyang313 

Please add the contact information of the SP entities you are working with including region.

**Comment by mingyang313** [comment]
> @mingyang313
> 
> Please add the contact information of the SP entities you are working with including region.

In addition to the 5 SPs already listed in the submitted form, I have also reached out to the following four SPs. Please review:
f02050599, Thailand，Charlie
f02041085，Japan，TopValue
f02048990，Hong Kong，HS88
f02096851，Indonesia，EdgeIPC

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 5PiB

**Expected weekly DataCap usage rate**
> 500TiB

**Client address**
>f1tzehoozaa33ns42eac42kwboczlnfov4w7xoj7i

**Comment by a1991car** [comment]
The first round, support, will continue to pay attention

**Comment by a1991car** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacechogjt4cuxxeidypyuiwzsnjvrychkwitsm6lw3nkjp3niyq233u 
#### Address 
> f1tzehoozaa33ns42eac42kwboczlnfov4w7xoj7i
#### Datacap Allocated
> 256.00TiB
#### Signer Address
> f1qnumecdypgrbaebtkdfjnwt5ndacadcuas3deiq
#### Id
> 7f2ded11-8c58-4d8a-8dd1-e6174dba72cb
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacechogjt4cuxxeidypyuiwzsnjvrychkwitsm6lw3nkjp3niyq233u

**Comment by luobin544** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacea3kpzx7ipen6kgoifglckzgygkdtrf3hhmkfqpair7ij3ac7tsma 
#### Address 
> f1tzehoozaa33ns42eac42kwboczlnfov4w7xoj7i
#### Datacap Allocated
> 256.00TiB
#### Signer Address
> f1tbd632f6w62glfaf7wjpimacbnjiz26poyoes2q
#### Id
> 7f2ded11-8c58-4d8a-8dd1-e6174dba72cb
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacea3kpzx7ipen6kgoifglckzgygkdtrf3hhmkfqpair7ij3ac7tsma

**Comment by herrehesse** [comment]
Cant find any of the minerID's without VPN, and the businesses do not exist.
@kevzak can we close and remove the notaries who signed with 0 due diligence?

**Comment by mingyang313** [comment]
Can you provide more information? If it is true, I will contact the service provider again for confirmation.

**Comment by dongpo313** [comment]
it works.

**Comment by mingyang313** [comment]
it works.

**Comment by caoxinhe0108** [comment]
checker:manualTrigger

**Comment by mingyang313** [comment]
it's in use.

**Comment by mingyang313** [comment]
it works.

**Comment by Bitengine-reeta** [comment]
checker:manualTrigger

**Comment by mingyang313** [comment]
<img width="954" alt="image" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/37865375/795a09a6-b7a6-4cb6-981a-f6824e1b07d2">
this is bug,it's not final result,it's not real.

**Comment by Bitengine-reeta** [comment]
@mingyang313 
Can you provide evidence of on-chain storage deals for the current client make with multiple minerIDs?

**Comment by mingyang313** [comment]
<img width="839" alt="image" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/37865375/14ad9a03-c529-423d-8907-758a08188d22">
<img width="1353" alt="image" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/37865375/8bea0ee4-998a-4ca1-aa66-1ecf0164161f">
here is,please fix,thx.

**Comment by mingyang313** [comment]
@Bitengine-reeta

**Comment by Bitengine-reeta** [comment]
@mingyang313 
Yes, it seems that it has not been included in the report yet. Just wait for the information to be synchronized.
In addition, the four Miners in the picture are different from the previously disclosed Miner IDs. Please disclose the locations and organization names of these four Miners.

**Comment by mingyang313** [comment]
Due to the decrease in gas, we have recently chosen to first package the 32GB nodes，there are details，please check.

f02818594   Katharine   Katharine937@gmail.com         Samajuga                Kuala Lumpur, Malaysia
f02812304   saili             saili@gmail.com                         SY-Tech                    Singapore
f02823383   Lee             Lee93718@tom.com                 Meixin Technology   Hong Kong 
f02823878   Joan           Joooan@stufflebeam.com.au   stufflebeam              Australia

**Comment by mingyang313** [comment]
@Bitengine-reeta

**Comment by Bitengine-reeta** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebywg46rw7fnegwubpbk5qtg4onvpow35kh6oyri5a6jsiw5jmzp4 
#### Address 
> f1tzehoozaa33ns42eac42kwboczlnfov4w7xoj7i
#### Datacap Allocated
> 256.00TiB
#### Signer Address
> f1jyvhxp4kmwreo22ke4itspraznpudw3uqaink5i
#### Id
> 7f2ded11-8c58-4d8a-8dd1-e6174dba72cb
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebywg46rw7fnegwubpbk5qtg4onvpow35kh6oyri5a6jsiw5jmzp4

**Comment by 1ane-1** [comment]
checker:manualTrigger

**Comment by 1ane-1** [comment]
The report shows everything goes well as they said before. Support.

**Comment by 1ane-1** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceducbmktkpexk5677m7xurtfjsv7grdsb67dyeisu7dzioyggbqz4 
#### Address 
> f1tzehoozaa33ns42eac42kwboczlnfov4w7xoj7i
#### Datacap Allocated
> 256.00TiB
#### Signer Address
> f1mdk7s2vntzm6hu35yuo6vjubtrpfnb2awhgvrri
#### Id
> 7f2ded11-8c58-4d8a-8dd1-e6174dba72cb
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceducbmktkpexk5677m7xurtfjsv7grdsb67dyeisu7dzioyggbqz4

**Comment by SuperChaiChai** [comment]
checker:manualTrigger

**Comment by kernelogic** [comment]
Report LGTM

**Comment by Tom-OriginStorage** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb5zqnnwnkveocwyein6cr3yfwzzw5p2vuktgmcasf6dfk4gehznw 
#### Address 
> f1tzehoozaa33ns42eac42kwboczlnfov4w7xoj7i
#### Datacap Allocated
> 256.00TiB
#### Signer Address
> f1q6bpjlqia6iemqbrdaxr2uehrhpvoju3qh4lpga
#### Id
> 7f2ded11-8c58-4d8a-8dd1-e6174dba72cb
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb5zqnnwnkveocwyein6cr3yfwzzw5p2vuktgmcasf6dfk4gehznw

**Comment by herrehesse** [comment]
Guys? We keep accepting fraud? How great for this project you all are.

**Comment by mingyang313** [comment]
Thank you for your attention. So far, we have been doing well in complying with the FIL+ rules, haven't we? We will continue to onboard new and more reliable service providers with higher retrieval success rates.

**Comment by ipollo00** [comment]
checker:manualTrigger

**Comment by ipollo00** [comment]
Pretty good, willing to support!

**Comment by ipollo00** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecgefs46c6e7xrlcvm2zrvo6o4hdzlbhsgex27tykwtww7i7wzyr6 
#### Address 
> f1tzehoozaa33ns42eac42kwboczlnfov4w7xoj7i
#### Datacap Allocated
> 2.00PiB
#### Signer Address
> f1n5wlrrhoxpkgwij25xrtt7w7g2k3fhbthmdn6ri
#### Id
> 4505de45-6a0a-4184-be5a-307e27206d6b
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecgefs46c6e7xrlcvm2zrvo6o4hdzlbhsgex27tykwtww7i7wzyr6

**Comment by METAVERSEDATAMINING** [comment]
checker:manualTrigger

**Comment by METAVERSEDATAMINING** [comment]
f02823878 Singapore, Singapore, SG
Is there any reasonable explanation for the inconsistency between this IP address and the disclosed information?

> Due to the decrease in gas, we have recently chosen to first package the 32GB nodes，there are details，please check.
> 
> f02818594 Katharine [Katharine937@gmail.com](mailto:Katharine937@gmail.com) Samajuga Kuala Lumpur, Malaysia f02812304 saili [saili@gmail.com](mailto:saili@gmail.com) SY-Tech Singapore f02823383 Lee [Lee93718@tom.com](mailto:Lee93718@tom.com) Meixin Technology Hong Kong f02823878 Joan [Joooan@stufflebeam.com.au](mailto:Joooan@stufflebeam.com.au) stufflebeam Australia

**Comment by mingyang313** [comment]
> @mingyang313 f02823878 Singapore, Singapore, SG Is there any reasonable explanation for the inconsistency between this IP address and the disclosed information?
> 
> > Due to the decrease in gas, we have recently chosen to first package the 32GB nodes，there are details，please check.
> > f02818594 Katharine [Katharine937@gmail.com](mailto:Katharine937@gmail.com) Samajuga Kuala Lumpur, Malaysia f02812304 saili [saili@gmail.com](mailto:saili@gmail.com) SY-Tech Singapore f02823383 Lee [Lee93718@tom.com](mailto:Lee93718@tom.com) Meixin Technology Hong Kong f02823878 Joan [Joooan@stufflebeam.com.au](mailto:Joooan@stufflebeam.com.au) stufflebeam Australia

It seems
![Uploading 2
![29221699946420_ pic](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/37865375/6d02f6e5-7d60-4394-afb6-6a248a9632f3)
9191699946372_.pic.jpg…]()
 that the robot has different results, please recheck.

**Comment by mingyang313** [comment]
> @mingyang313 f02823878 Singapore, Singapore, SG Is there any reasonable explanation for the inconsistency between this IP address and the disclosed information?
> 
> > Due to the decrease in gas, we have recently chosen to first package the 32GB nodes，there are details，please check.
> > f02818594 Katharine [Katharine937@gmail.com](mailto:Katharine937@gmail.com) Samajuga Kuala Lumpur, Malaysia f02812304 saili [saili@gmail.com](mailto:saili@gmail.com) SY-Tech Singapore f02823383 Lee [Lee93718@tom.com](mailto:Lee93718@tom.com) Meixin Technology Hong Kong f02823878 Joan [Joooan@stufflebeam.com.au](mailto:Joooan@stufflebeam.com.au) stufflebeam Australia

It seems that the robot has different results, please check.
![29191699946372_ pic](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/37865375/223a946c-f702-4f9c-b3fc-4220165d8858)
![29221699946420_ pic](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/37865375/ea8672a5-a96f-44f3-9f21-a8f5fc74db15)

**Comment by METAVERSEDATAMINING** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebb3qm5fdmyook4tysi4xa73qx53lir6ngtnyerf3mzok2fgt2noc 
#### Address 
> f1tzehoozaa33ns42eac42kwboczlnfov4w7xoj7i
#### Datacap Allocated
> 2.00PiB
#### Signer Address
> f17idrnfnxl2mbgcgr57a6z2c6lj2qx56gvm3336i
#### Id
> 4505de45-6a0a-4184-be5a-307e27206d6b
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebb3qm5fdmyook4tysi4xa73qx53lir6ngtnyerf3mzok2fgt2noc

**Comment by SuperChaiChai** [comment]
checker:manualTrigger

**Comment by zcfil** [comment]
checker:manualTrigger

**Comment by zcfil** [comment]
> Due to the decrease in gas, we have recently chosen to first package the 32GB nodes，there are details，please check.
> 
> f02818594 Katharine [Katharine937@gmail.com](mailto:Katharine937@gmail.com) Samajuga Kuala Lumpur, Malaysia f02812304 saili [saili@gmail.com](mailto:saili@gmail.com) SY-Tech Singapore f02823383 Lee [Lee93718@tom.com](mailto:Lee93718@tom.com) Meixin Technology Hong Kong f02823878 Joan [Joooan@stufflebeam.com.au](mailto:Joooan@stufflebeam.com.au) stufflebeam Australia

The report looks good, browsed the historical info consistent with the stated SP, retrieved properly, so willing to support this round
![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/45065975/4d60cdf5-632f-4dba-85af-e87168f978bd)

**Comment by zcfil** [comment]
![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/45065975/42cabb6f-3319-4eea-9330-8853a8ddc836)
I only chose one, but it reported an error
@Filplus-govteam @Sunnyiscoming @simonkim0515

**Comment by zcfil** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecfmkbkl2nk22toy23mmshb5f6uyx3yjhewbqu6vw6rv5bzqvmrzu 
#### Address 
> f1tzehoozaa33ns42eac42kwboczlnfov4w7xoj7i
#### Datacap Allocated
> 2.00PiB
#### Signer Address
> f1cjzbiy5xd4ehera4wmbz63pd5ku4oo7g52cldga
#### Id
> 5b76054b-695e-4fc2-bb9a-5b3d0c9ea00f
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecfmkbkl2nk22toy23mmshb5f6uyx3yjhewbqu6vw6rv5bzqvmrzu

**Comment by SuperChaiChai** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebmnyynkitbkhgrofnyqaxt6ewuhtxjdsouz3o4zmadzmv4he65oy 
#### Address 
> f1tzehoozaa33ns42eac42kwboczlnfov4w7xoj7i
#### Datacap Allocated
> 2.00PiB
#### Signer Address
> f12mckci3omexgzoeosjvstcfxfe4vqw7owdia3da
#### Id
> 5b76054b-695e-4fc2-bb9a-5b3d0c9ea00f
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebmnyynkitbkhgrofnyqaxt6ewuhtxjdsouz3o4zmadzmv4he65oy

**Comment by nj-steve** [comment]
checker:manualTrigger

**Comment by nj-steve** [comment]
The cid and retrieval report fit the fil+ rules, no dispute here. But I also hope you send deals to more SPs.

**Comment by Filplus-govteam** [comment]
SPs taking deals:
f02823878new | Singapore, Singapore, SGDatacamp Limited | 312.09 TiB | 24.92% | 312.06 TiB | 0.01%
f02823383new | Sham Shui Po, Sham Shui Po, HKGigabit Hosting Sdn Bhd | 301.56 TiB | 24.07% | 301.56 TiB | 0.00%
f02818594new | Kuala Lumpur, Kuala Lumpur, MYGigabit Hosting Sdn Bhd | 296.72 TiB | 23.69% | 296.72 TiB | 0.00%
f02812304new | Singapore, Singapore, SGOVH SAS | 342.25 TiB | 27.32% | 342.25 TiB | 0.00%

SPs listed upfront:

f02086436 | SG Leaseweb Asia Pacific pte. ltd. | Singapore | no | none
f02053449 Central and Western, HK IPTELECOM Global. | Hong Kong | no | none
f02060013 Seoul, KR The Constant Company, LLC. | Paripark | no | none
f02060013  Guangdong, CN China Telecom (Group). | Shenzhen | no | none
f02042992 Singapore, SG OVH SAS | Singapore | no | none

SPs do not match, closing per 922 guidelines and until a clear list of SP entities and distribution is provided
