### ISSUE TITLE
[DataCap Application] NIH NCBI SRA

### ISSUE THREAD

**Issue by AdaIfan** [filecoin-project/filecoin-plus-large-datasets#2196]
### Data Owner Name

National Library of Medicine

### What is your role related to the dataset

Data Preparer

### Data Owner Country/Region

United States

### Data Owner Industry

Life Science / Healthcare

### Website

https://www.ncbi.nlm.nih.gov/sra/docs/sra-cloud/

### Social Media

```text
https://www.nlm.nih.gov/
```

### Total amount of DataCap being requested

15PiB

### Expected size of single dataset (one copy)

1.55PiB

### Number of replicas to store

9

### Weekly allocation of DataCap requested

1PiB

### On-chain address for first allocation

f13knv34s7u63jbpey6mt5bq2jrod6hp4egwp422i

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
The Sequence Read Archive (SRA), produced by the National Center for Biotechnology Information (NCBI) at the National Library of Medicine (NLM) at the National Institutes of Health (NIH), stores raw DNA sequencing data and alignment information from high-throughput sequencing platforms. The SRA provides open access to these biological sequence data to support the research community's efforts to enhance reproducibility and make new discoveries by comparing data sets.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
Buckets in this registry contain public SRA data in the original (user submitted) format from select high value and newly-released studies as well as all public-access SRA formatted ETL+BQS data. Also included is all SRA metadata that can be leveraged for attribute-based data discovery.
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### If you are a data preparer. What is your location (Country/Region)

Hong Kong

### If you are a data preparer, how will the data be prepared? Please include tooling used and technical details?

```text
We plan to use Lotus.
```

### Has this dataset been stored on the Filecoin network before? If so, please explain and make the case why you would like to store this dataset again to the network. Provide details on preparation and/or SP distribution.

```text
No. It is a dataset that is updated daily. So it should be stored into filecoin to store safely.
```

### Please share a sample of the data

```text
s3://sra-pub-src-1/
s3://sra-pub-src-2/
s3://sra-pub-run-odp/
s3://sra-pub-metadata-us-east-1/sra/metadata/
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Sporadic

### For how long do you plan to keep this dataset stored on Filecoin

Permanently

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, Europe

### How will you be distributing your data to storage providers

HTTP or FTP server, Shipping hard drives, Lotus built-in data transfer

### How do you plan to choose storage providers

Slack, Big Data Exchange

### If you already have a list of storage providers to work with, fill out their names and provider IDs below

```text
f0103710 Guiyang
f0509981 Guizhou
f02181152 Sichuan
f02239446 HongKong
f01563172 Dongguan
```

### How do you plan to make deals to your storage providers

Lotus client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by herrehesse** [comment]
Hi friend, thank you for this LDN. Can you show me proof of download?

**Comment by Sunnyiscoming** [comment]
Any update here?

**Comment by AdaIfan** [comment]
@Sunnyiscoming 
Yes, SP will prepared it.
OK. I have already finished this form.

**Comment by AdaIfan** [comment]
@herrehesse Yes

<img width="647" alt="_6110910b-9820-439a-8c2b-ae901558a470" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/141729164/66535d79-dc7d-4001-bc2b-049921304d0e">

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 15PiB

**Expected weekly DataCap usage rate**
> 1PiB

**Client address**
>f13knv34s7u63jbpey6mt5bq2jrod6hp4egwp422i

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 15PiB

**Expected weekly DataCap usage rate**
> 1PiB

**Client address**
>f13knv34s7u63jbpey6mt5bq2jrod6hp4egwp422i

**Comment by AdaIfan** [comment]
@Sunnyiscoming Thank you for your help. Waiting for the fix.

**Comment by Sunnyiscoming** [comment]
It is still being processed.

**Comment by herrehesse** [comment]
@Sunnyiscoming why are you still allowing scammers to proceed?

**Comment by AdaIfan** [comment]
@herrehesse Wait, how can you say it? Are you a bot?

**Comment by herrehesse** [comment]
@AdaIfan I was not talking to you.

**Comment by Sunnyiscoming** [comment]
@herrehesse Please submit evidence to prove the problem.

**Comment by AdaIfan** [comment]
@Sunnyiscoming I have resubmitted the form and explained the condition.

**Comment by AdaIfan** [comment]
@kevzak Hey Kevin, can you please check the form I've submitted on Oct 20? I have provided thesee in the form.

**Comment by AdaIfan** [comment]
@kevzak And can you open my application? It shouldn't be closed without any advance notice. Thank you sir.

**Comment by AdaIfan** [comment]
@Sunnyiscoming Hello, may I ask when my application's problem will be fixed?

**Comment by Sunnyiscoming** [comment]
SP List provided:
[{"providerID": "f02239446",  "City": "HongKong", "Country": "CN", "SPOrg","cryptomoon"},
{"providerID": "f01882035",  "City": "Sichuan", "Country": "CN","SPOrg","Ganzi"},
{"providerID": "f01084913",  "City": "HongKong", "Country": "CN", "SPOrg","XYZ"},
{"providerID": "f02029743",  "City": "XYZ", "Country": "Singapore", "SPOrg","XYZ"},
{"providerID": "f01841134",  "City": "Guiyang", "Country": "CN", "SPOrg","XYZ"},]

**Comment by herrehesse** [comment]
checker:manualTrigger

**Comment by herrehesse** [comment]
Supported by two abusive notaries, fully self-dealing in same region. Awaiting CID report and suggest closure.

**Comment by cryptowhizzard** [comment]
checker:manualTrigger
