### ISSUE TITLE
[DataCap Application] <Organization> - <Events data & Videos>

### ISSUE THREAD

**Issue by Metainsightofficial** [filecoin-project/filecoin-plus-large-datasets#2200]
### Data Owner Name

Metainsight (HONG KONG B&H TECHNOLOGY CO., LIMITED)

### What is your role related to the dataset

Dataset Owner

### Data Owner Country/Region

Hong Kong

### Data Owner Industry

Information, Media & Telecommunications

### Website

https://twitter.com/Metainsight2022

### Social Media

```text
Twitter:@Metainsight2022
```

### Total amount of DataCap being requested

5PiB

### Expected size of single dataset (one copy)

500

### Number of replicas to store

10

### Weekly allocation of DataCap requested

500TiB

### On-chain address for first allocation

f1oscd3gc7bxsucnjzejt77cb47zaaptp3hhgigxa

### Data Type of Application

Public, Open Commercial/Enterprise

### Custom multisig

- [ ] Use Custom Multisig

### Identifier

No response

### Share a brief history of your project and organization

```text
Metainsight, the main body of the company is located in Hong Kong, China (HONG KONG MEET TECHNOLOGY CO., LIMITED).
The team was established in November 2019 and was invested and incubated by Bitrise Capital. Currently relying on media consulting, marketing planning, conference activities, public relations, creative design and other products and services, by combining the information flow of the blockchain industry with customized services, creating Blockchain industry-leading information service platform.
At present, the team has held several thousand-person summits in the blockchain industry and nearly a hundred online activities, with more than 200 cooperative enterprises and institutions, covering more than 2 million users.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### If answered yes, what are the other projects/ecosystem stakeholders

```text
No response
```

### Describe the data being stored onto Filecoin

```text
Events videos、recordings、files of programs from daily events,host Spaces on twitters.
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### If you answered "Other" in the previous question, enter the details here

```text
No response
```

### If you are a data preparer. What is your location (Country/Region)

Hong Kong

### If you are a data preparer, how will the data be prepared? Please include tooling used and technical details?

```text
HTTP or FTP server, IPFS, Shipping hard drives, Lotus built-in data transfer
```

### If you are not preparing the data, who will prepare the data?  (Provide name and business)

```text
No response
```

### Has this dataset been stored on the Filecoin network before? If so, please explain and make the case why you would like to store this dataset again to the network. Provide details on preparation and/or SP distribution.

```text
No
```

### Please share a sample of the data

```text
https://twitter.com/i/spaces/1lPKqBjEvWNGb
https://twitter.com/i/spaces/1YqGoAbWXngxv
https://twitter.com/i/spaces/1MnxnpOVEbMGO
https://twitter.com/i/spaces/1MYxNgQLBWvKw
https://twitter.com/i/spaces/1DXGyvLPZebJM
https://twitter.com/i/spaces/1yoJMZqjeVXxQ
https://twitter.com/i/spaces/1ypJddlRVkaJW
https://twitter.com/i/spaces/1PlJQpYgZgNGE
https://twitter.com/i/spaces/1MYxNgPDXZZKw
https://medium.com/@metakey2022
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### If you chose not to confirm, what was the reason

```text
No response
```

### What is the expected retrieval frequency for this data

Sporadic

### For how long do you plan to keep this dataset stored on Filecoin

1.5 to 2 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China

### How will you be distributing your data to storage providers

Cloud storage (i.e. S3), HTTP or FTP server, IPFS, Shipping hard drives, Lotus built-in data transfer, Venus built-in data transfer

### How do you plan to choose storage providers

Slack, Filmine, Big Data Exchange, Partners

### If you answered "Others" in the previous question, what is the tool or platform you plan to use

```text
No response
```

### If you already have a list of storage providers to work with, fill out their names and provider IDs below

```text
No response
```

### How do you plan to make deals to your storage providers

Boost client

### If you answered "Others/custom tool" in the previous question, enter the details here

```text
No response
```

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by data-programs** [comment]
<img width="32" alt="KYC" Verified src="https://stable.filplus.storage/images/filplus-kyc-verified-badge.png"/>

This user’s identity has been verified through [filplus.storage](https://filplus.storage)

**Comment by Metainsightofficial** [comment]
@Sunnyiscoming @kevzak 
Looking forward to getting touched, KYC verification has been completed.

**Comment by herrehesse** [comment]
@Metainsightofficial Can you share your collaborating minerID's, regions and business names?

**Comment by Sunnyiscoming** [comment]
- Have you prepared enough token for sector pledge?
- Best practice for storing large datasets includes ideally, storing it in 3 or more regions, with 4 or more storage provider operators or owners.You should list Miner ID, Business Entity, Location of sps you will cooperate with.
- Per the https://github.com/filecoin-project/notary-governance/issues/922 for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

**Comment by Metainsightofficial** [comment]
@Sunnyiscoming 

1. The email has been sent, please check your inbox.
2. Yes, sample data has been submitted in the application form.
3. Yes.
4. I will disclose the information of the cooperating service providers in the form, please check it.

**Comment by Sunnyiscoming** [comment]
Please send email with business license bacause receiving email from personal gmail.
Please list sps here.

**Comment by Metainsightofficial** [comment]
Hi Sunny
The PDF attached is the business license.

Sunnyiscoming ***@***.***> 于2023年9月16日周六 22:55写道：

**Comment by Metainsightofficial** [comment]
Here are the SPs (Miner id, location, entity)we corporated. And the email including our business license has been sent.
f01853077    Singapore  Alpha100
f02329119   jiaxing   Cryptomage
f02133079   HongKong    FineTune
f02274508   HongKong    H&W
f02320312   USA    R1

**Comment by Sunnyiscoming** [comment]
No pdf attached in the two email.

**Comment by Metainsightofficial** [comment]
The email proving our identity has been sent, so has our business license in it. Please check it out.
@Sunnyiscoming

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 5PiB

**Expected weekly DataCap usage rate**
> 500TiB

**Client address**
>f1oscd3gc7bxsucnjzejt77cb47zaaptp3hhgigxa

**Comment by 1ane-1** [comment]
My Slack name is Genesis.Could you please send the company documents on slack? I will help check the organzation.

**Comment by Metainsightofficial** [comment]
Thanks for your work. We have sent you according file through slack, please check. @1ane-1

**Comment by 1ane-1** [comment]
The file has been checked, and willing to support it.

**Comment by 1ane-1** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebzhpde3zpbkdtdj3epridpeaji5grpp2sp3k3bodplytgdicvmya 
#### Address 
> f1oscd3gc7bxsucnjzejt77cb47zaaptp3hhgigxa
#### Datacap Allocated
> 250.00TiB
#### Signer Address
> f1mdk7s2vntzm6hu35yuo6vjubtrpfnb2awhgvrri
#### Id
> 38f12415-c82b-4889-86ae-6408c4ad4ce9
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebzhpde3zpbkdtdj3epridpeaji5grpp2sp3k3bodplytgdicvmya

**Comment by sxxfuture-official** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceazxmad76owcozsrr6rgsape6ggke73bwn25xljo73wotlpsp4rce 
#### Address 
> f1oscd3gc7bxsucnjzejt77cb47zaaptp3hhgigxa
#### Datacap Allocated
> 250.00TiB
#### Signer Address
> f1foiomqlmoshpuxm6aie4xysffqezkjnokgwcecq
#### Id
> 38f12415-c82b-4889-86ae-6408c4ad4ce9
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceazxmad76owcozsrr6rgsape6ggke73bwn25xljo73wotlpsp4rce

**Comment by NDLABS-Leo** [comment]
checker:manualTrigger

**Comment by NDLABS-Leo** [comment]
checker:manualTrigger

**Comment by NDLABS-Leo** [comment]
checker:manualTrigger

**Comment by NDLABS-Leo** [comment]
checker:manualTrigger

**Comment by NDLABS-Leo** [comment]
checker:manualTrigger

**Comment by maxvint** [comment]
Cool, data distribution looks very good, and check all the boxes, retrieval also works very well, willing to support.

**Comment by maxvint** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceauoswaqq7gr77z5jf2fujdzvlxgqjq7betvdqjpv6wrbscwmqrwa 
#### Address 
> f1oscd3gc7bxsucnjzejt77cb47zaaptp3hhgigxa
#### Datacap Allocated
> 500.00TiB
#### Signer Address
> f1ui5iy4mmkxjbw7752omiwp2ols2fzv4thrayagi
#### Id
> 50144bdc-a4f3-496c-901e-d0d9fbc37e13
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceauoswaqq7gr77z5jf2fujdzvlxgqjq7betvdqjpv6wrbscwmqrwa

**Comment by Metainsightofficial** [comment]
@kevzak  @Sunnyiscoming 
Hi Fil+ team, sorry to find that the Data Type we had applied is wrong(Public, Open Commercial/Enterprise), please change it to e+fil, thanks.

**Comment by AlanGreaterheat** [comment]
checker:manualTrigger

**Comment by AlanGreaterheat** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecb6dpyfswx3ycvyxtsupexuodekmviumg4zjygtefmo3jc7f2xjo 
#### Address 
> f1oscd3gc7bxsucnjzejt77cb47zaaptp3hhgigxa
#### Datacap Allocated
> 500.00TiB
#### Signer Address
> f1pnmzlxj7cfeo2v6oj5nco46hkg2l46wj7o4xxui
#### Id
> 50144bdc-a4f3-496c-901e-d0d9fbc37e13
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecb6dpyfswx3ycvyxtsupexuodekmviumg4zjygtefmo3jc7f2xjo

**Comment by ipfscn** [comment]
checker:manualTrigger

**Comment by ipfscn** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceatbqlz22onsenqvvgkjkr3butc7wlmjfr74k5moexpxnm4vvjgck 
#### Address 
> f1oscd3gc7bxsucnjzejt77cb47zaaptp3hhgigxa
#### Datacap Allocated
> 1000.00TiB
#### Signer Address
> f1j4n74chme7whbz3yls4a7ixqewb6dijypqg2a3a
#### Id
> c6d5cbb8-6925-4c1f-be61-6f87302f88a4
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceatbqlz22onsenqvvgkjkr3butc7wlmjfr74k5moexpxnm4vvjgck

**Comment by laurarenpanda** [comment]
checker:manualTrigger

**Comment by laurarenpanda** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedfmmaqxdy3k7mjc3hl6xdyumm5xvkw3drdu4josggjbqfe77gm7k 
#### Address 
> f1oscd3gc7bxsucnjzejt77cb47zaaptp3hhgigxa
#### Datacap Allocated
> 1000.00TiB
#### Signer Address
> f1bp3tzp536edm7dodldceekzbsx7zcy7hdfg6uzq
#### Id
> c6d5cbb8-6925-4c1f-be61-6f87302f88a4
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedfmmaqxdy3k7mjc3hl6xdyumm5xvkw3drdu4josggjbqfe77gm7k

**Comment by luobin544** [comment]
checker:manualTrigger

**Comment by luobin544** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecjsa5rq3vsqfxdkhkohtfpacnorme5djyw72imv4qxtltg4spk56 
#### Address 
> f1oscd3gc7bxsucnjzejt77cb47zaaptp3hhgigxa
#### Datacap Allocated
> 1.95PiB
#### Signer Address
> f1tbd632f6w62glfaf7wjpimacbnjiz26poyoes2q
#### Id
> 4523007e-7611-4cbc-9352-75adf1570413
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecjsa5rq3vsqfxdkhkohtfpacnorme5djyw72imv4qxtltg4spk56

**Comment by kernelogic** [comment]
I see the replication ratio is improving. Also no other problem with this LDN.

Last week: 73.86% of deals are for data replicated across less than 4 storage providers.
This week: 52.26% of deals are for data replicated across less than 4 storage providers.

**Comment by BlockMakeronline** [comment]
The distribution of SP and retrieval ratio looks good. We'd like to support.

**Comment by BlockMakeronline** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaevj3mk3rnex4p4urahyahoer5t55yi5zwe7ya63mvax5b2rb2u6 
#### Address 
> f1oscd3gc7bxsucnjzejt77cb47zaaptp3hhgigxa
#### Datacap Allocated
> 1.95PiB
#### Signer Address
> f1o3twrcpwjtpcd4q36lpq4qmy2qfbgtyy5h6tsty
#### Id
> 4523007e-7611-4cbc-9352-75adf1570413
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaevj3mk3rnex4p4urahyahoer5t55yi5zwe7ya63mvax5b2rb2u6

**Comment by kernelogic** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceafy26e5a7p6i3mk5x2fyu54od33dblzltauvd6fq2td4qbtpwcyq 
#### Address 
> f1oscd3gc7bxsucnjzejt77cb47zaaptp3hhgigxa
#### Datacap Allocated
> 1.95PiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### Id
> 4523007e-7611-4cbc-9352-75adf1570413
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceafy26e5a7p6i3mk5x2fyu54od33dblzltauvd6fq2td4qbtpwcyq

**Comment by kevzak** [comment]
checker:manualTrigger

**Comment by kevzak** [comment]
SPs provided. No contact info
 f01853077 | Peter | - | Alpha100 | Singapore | - | -
f02329119 | Jennie | - | Cryptomage | Jiaxing | - | -
f02133079 | Stephine | - | FineTune | HongKong | - | -
f02274508 | Rick | - | H&W | HongKong | - | -
f02320312 | Greg | - | R1 | USA | -

SPs used:

f02211572 | Chengdu, Sichuan, CNChina Mobile Communications Group Co., Ltd. | 156.81 TiB | 13.98% | 156.81 TiB | 0.00%
f02368282 | Chengdu, Sichuan, CNCHINA UNICOM China169 Backbone | 303.72 TiB | 27.07% | 251.63 TiB | 17.15%
f02815620new | Hong Kong, Central and Western, HKChina Unicom Global | 227.94 TiB | 20.32% | 213.22 TiB | 6.46%
f02274508 | Hong Kong, Central and Western, HKChina Unicom Global | 222.16 TiB | 19.80% | 197.13 TiB | 11.27%
f01853077 | Singapore, Singapore, SGZenlayer Inc | 101.16 TiB | 9.02% | 101.16 TiB | 0.00%
f01852363 | Singapore, Singapore, SGZenlayer Inc | 79.50 TiB | 7.09% | 78.16 TiB | 1.69%
f02031006 | Los Angeles, California, USZenlayer Inc | 30.66 TiB | 2.73% | 30.63 TiB | 0.10%

does not match. closing until updated. Please provide contact info for all SPs. fill out registration form again if needed

**Comment by Metainsightofficial** [comment]
Hi, node f01853077 is matched, and we have resubmitted the contact info, please check it out.

**Comment by kevzak** [comment]
I see two that match @Metainsightofficial 
**f01853077**  | Alpha100 | Singapore |
f02329119  | Cryptomage | Jiaxing |
f02133079 | FineTune | HongKong | 
**f02274508** | HongKong | 
f02320312 | R1 | USA |

**Comment by Metainsightofficial** [comment]
The program is in process, and we have submited the added form, how can we open and review our application?

**Comment by Metainsightofficial** [comment]
Hi Fil+ team. How is it going with checking?

**Comment by Filplus-govteam** [comment]
checker:manualTrigger
