### ISSUE TITLE
[DataCap Application] <Yunnan Yimiao Environmental Protection Technology Co., Ltd> - <Yunnan Yimiao>

### ISSUE THREAD

**Issue by liruior** [filecoin-project/filecoin-plus-large-datasets#2201]
### Data Owner Name

Yunnan Yimiao Environmental Protection Technology Co., Ltd

### What is your role related to the dataset

Data Preparer

### Data Owner Country/Region

China

### Data Owner Industry

Environment

### Website

www.yimiaohb.net

### Social Media

```text
www.yimiaohb.net
```

### Total amount of DataCap being requested

3PiB

### Expected size of single dataset (one copy)

300T

### Number of replicas to store

10

### Weekly allocation of DataCap requested

300TiB

### On-chain address for first allocation

f14iffvmi4cpnjqzwu524zfomoc6ousw2zquk7vya

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Yunnan Yimiao Environmental Protection Technology Co., Ltd. is a comprehensive environmental protection service enterprise in China, with outstanding scientific research investment in water treatment. We have established communication and cooperation relationships with multiple domestic universities. Our business covers multiple environmental protection fields, including wastewater treatment, noise treatment, soil treatment and remediation, reclaimed water reuse, environmental protection equipment, energy-saving equipment, and comprehensive energy utilization.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
Including wastewater treatment, noise treatment, soil treatment and remediation, reclaimed water reuse, environmental protection equipment, energy-saving equipment, etc
```

### Where was the data currently stored in this dataset sourced from

Other

### If you are a data preparer. What is your location (Country/Region)

China

### If you are a data preparer, how will the data be prepared? Please include tooling used and technical details?

```text
Use your own storage facilities
```

### Please share a sample of the data

```text
https://www.aliyundrive.com/s/r5S2akEHqnT
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Monthly

### For how long do you plan to keep this dataset stored on Filecoin

2 to 3 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America

### How will you be distributing your data to storage providers

HTTP or FTP server, Shipping hard drives

### How do you plan to choose storage providers

Slack, Big Data Exchange, Partners

### If you already have a list of storage providers to work with, fill out their names and provider IDs below

```text
f02252173 luna  ymmart.com@gmail.com
f01872965 Seoul, South Korea Kim wsyy74a30w9cp@126.com
f01907578 Fujian, China Li j2perybkukx2@126.com
f01173645 Jiangxi, China king oqggt2fs25iv5@126.com
```

### How do you plan to make deals to your storage providers

Boost client, Lotus client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by liruior** [comment]
![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/143980674/d2022ee1-3180-40c3-b484-e64032d93bd0)
Unknown reason, the 2171 previously applied for was lost

**Comment by herrehesse** [comment]
@liruior can you state all your collaborating minerIDs, their region and their business contact information? Email addresses like "oqggt2fs25iv5@126.com" do not spark high confidence, as they are throwaway email accounts.

**Comment by Sunnyiscoming** [comment]
Any update here?

**Comment by jlsjs** [comment]
> Any update here?

Same as previously applied for

**Comment by liruior** [comment]
> Any update here?

not have

**Comment by liruior** [comment]
> @liruior can you state all your collaborating minerIDs, their region and their business contact information? Email addresses like "[oqggt2fs25iv5@126.com](mailto:oqggt2fs25iv5@126.com)" do not spark high confidence, as they are throwaway email accounts.

f02252173 luna  ymmart.com@gmail.com
f01872965 Seoul, South Korea Kim wsyy74a30w9cp@126.com
f01907578 Fujian, China Li j2perybkukx2@126.com
f01173645 Jiangxi, China king oqggt2fs25iv5@126.com

**Comment by kevzak** [comment]
email sent to SPs listed above - let's confirm who they are and where they are.

**Comment by liruior** [comment]
> 发送到上面列出的 SP 的电子邮件 - 让我们确认他们是谁以及他们在哪里。

Good email has been sent, please check

**Comment by liruior** [comment]
> email sent to SPs listed above - let's confirm who they are and where they are.

Contacted them for confirmation

**Comment by liruior** [comment]
@kevzak Have you received the email on your end? It's been two weeks now. Do you have any questions?

**Comment by kevzak** [comment]
no @liruior

**Comment by liruior** [comment]
> This application has not seen any responses in the last 10 days. This issue will be marked with Stale label and will be closed in 4 days. Comment if you want to keep this application open.
> 
> -- Commented by Stale Bot.

keep it open

**Comment by liruior** [comment]
> no @liruior

Is there anything else that needs my assistance

**Comment by kevzak** [comment]
no SPs confirmed. Please provide updated list with entity and contact. Closing for now.
