### ISSUE TITLE
[DataCap Application] Banyan Storage Inc

### ISSUE THREAD

**Issue by laudiacay** [filecoin-project/filecoin-plus-large-datasets#2202]
### Data Owner Name
Banyan Storage Inc

### What is your role related to the dataset
Data onramp entity that provides data onboarding services to multiple clients

### Data Owner Country/Region
United States

### Data Owner Industry
Other

### Website
[https://banyan.computer](https://banyan.computer)

### Social Media
BanyanComputer (twitter)

### Total amount of DataCap being requested
15 PiB

### Expected size of single dataset (one copy)
10 TiB

### Number of replicas to store
3

### Weekly allocation of DataCap requested
500 TiB

### On-chain address for first allocation
f1oc6qvenzp7wsriu7edyebb325gnaovktmujl7jq

### Data Type of Application
Private Commercial/Enterprise

### Custom multisig
- [x] Use Custom Multisig

### Identifier
efil

### Share a brief history of your project and organization
data preparer with a BD pipeline/SOC2/encrypted storage and transfer product.

### Is this project associated with other projects/ecosystem stakeholders?
Yes

### If answered yes, what are the other projects/ecosystem stakeholders
Claudia Richoux, some SPs who are our partners

### Describe the data being stored onto Filecoin
whatever our customers pay us to upload, prepared and encrypted.

### Where was the data currently stored in this dataset sourced from
Other

### If you answered "Other" in the previous question, enter the details here
However our customers are currently storing it.

### If you are a data preparer, what is your location (City and Country)
n/a

### If you are a data preparer, how will the data be prepared? Please include tooling used and technical details?
n/a

### If you are not preparing the data, who will prepare the data?  (Provide name and business)
We give our customers software to prepare it themselves.

### Has this dataset been stored on the Filecoin network before? If so, please explain and make the case why you would like to store this dataset again to the network. Provide details on preparation and/or SP distribution.
n/a

### Please share a sample of the data
No

### Confirm that this is a public dataset that can be retrieved by anyone on the Network
No

### If you chose not to confirm, what was the reason
Private customer data.

### What is the expected retrieval frequency for this data
Sporadic

### For how long do you plan to keep this dataset stored on Filecoin
2 to 3 years

### In which geographies do you plan on making storage deals
North America, Australia (continent), Europe, Greater China, Asia other than Greater China

### How will you be distributing your data to storage providers
Others

### How do you plan to choose SP
Partners

### If you answered "Others" in the previous question, what is the tool or platform you plan to use
n/a

### If you already have a list of storage providers to work with, fill out their names and provider IDs below
Ghostbyte and Vault32 are 2 of our initial partners. We make our SPs sign an SLA with us.

### How do you plan to make deals to your storage providers
Others/custom tool

### If you answered "Others/custom tool" in the previous question, enter the details here
We have a custom algorithm to determine proper combinations of SPs to get a given quality of service and fit compliance requirements.

### Can you confirm that you will follow the Fil+ guideline
Yes

_Application created via [filplus.storage](https://filplus.storage)_

**Comment by data-programs** [comment]
This application requests a total of 15 PiB, so it’s labeled `very large application`

**Comment by data-programs** [comment]
This application is requesting DataCap for a **private** dataset, so it's labeled `efil+`

**Comment by herrehesse** [comment]
I would assume this application is also required to pass #922 ?

**Comment by kevzak** [comment]
This use case is technically eligible on the Enterprise Fil+ pathway.
 
- The Applicant needs to complete a KYC check. 
- The company needs to complete a KYB check. 
- A clear list of SP partners (Miner IDs, Entities, locations) needs to be shared. 

Then its up to the notaries to support the client data claiming to be onboarded. (There is currently no mention of any of the data)

**Comment by Sunnyiscoming** [comment]
Any update here?
