### ISSUE TITLE
[DataCap Application] <MetaEra GLOBLE LIMITED> - <E-FIL>

### ISSUE THREAD

**Issue by CockroachBoss** [filecoin-project/filecoin-plus-large-datasets#2203]
### Data Owner Name

MetaEra

### What is your role related to the dataset

Dataset Owner

### Data Owner Country/Region

Hong Kong

### Data Owner Industry

Web3 / Crypto

### Website

https://metaera.media/

### Social Media

```text
Meta Era Website：https://metaera.media/

Meta Era Twitter EN：https://twitter.com/MetaEra_Media

Meta Era Twitter CN：https://twitter.com/MetaEraCN

Meta Era Telegram Group：https://t.me/METAERAofficial

Meta Era Telegram Channel ：https://t.me/metaeranews

Meta Era LinkedIn：https://www.linkedin.com/company/metaeramedia/

Meta Era Wechat Public：Meta Era Global

Meta Era Wechat：MetaEraGlobal

Meta Era YouTube：https://www.youtube.com/@MetaEraCN

Mera Era TikTok: https://www.tiktok.com/@meteeramedia
```

### Total amount of DataCap being requested

5PiB

### Expected size of single dataset (one copy)

500T

### Number of replicas to store

10

### Weekly allocation of DataCap requested

800TiB

### On-chain address for first allocation

f1jiyk6afgtiytqvqxtkd6lqf5na2matwmecj24hq

### Data Type of Application

Private Commercial/Enterprise

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Meta Era is a distinguished media outlet based in Hong Kong that advocates for the expansion of Web 3.0 technology across Asia and worldwide. We pride ourselves on delivering precise, professional information to our audience, and have fostered strong alliances with numerous investment institutions, cutting-edge Web 3.0 enterprises, and influential industry media and communities.

Beyond our regular content, Meta Era also spearheads large-scale online summits and impactful offline conferences, cementing our status as a significant influencer in the industry. With our dedicated focus on the digital frontier, we are paving the way for the new era of the internet - a Meta Era.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
Corporate data, mainly high-definition video files as well as high-precision promotional images and so on.
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### If you are a data preparer. What is your location (Country/Region)

Hong Kong

### If you are a data preparer, how will the data be prepared? Please include tooling used and technical details?

```text
I am an enterprise data storage data owner and preparer and we currently store our data in our own storage devices. The main focus is on cloud storage and server room equipment storage. We will subsequently transfer the data via online transfer and hard drive mailing.
```

### Has this dataset been stored on the Filecoin network before? If so, please explain and make the case why you would like to store this dataset again to the network. Provide details on preparation and/or SP distribution.

```text
We'll disclose the details in the github comments!
```

### Please share a sample of the data

```text
https://drive.google.com/file/d/1SErtZofR34bVN-ZAG-K9slHtTkz32GH1/view?usp=drive_link
https://drive.google.com/file/d/10P4qnGpxYmNw0NaygRYyu-NTHzdtARWg/view?usp=sharing
https://drive.google.com/file/d/1fSGT7kzOhiYxJNCS85kFPovAtR5K0wEr/view?usp=sharing
https://drive.google.com/file/d/1pJxuzwi9QpZBdSHkPQlb5cly7G4edDs6/view?usp=drive_link
https://drive.google.com/file/d/1ES4vdU6AovjHJYnNiXc28me_GIj3PkK0/view?usp=drive_link
https://drive.google.com/file/d/186fDpIfVpL92b9yMw0uClHW6o5mUZqAo/view?usp=drive_link
https://drive.google.com/file/d/1YWNtH1HpCyHqoqzuSNMhnpfzdVrwBerS/view?usp=drive_link
https://drive.google.com/file/d/1GyLn7t9Y13oP6XCdAMnkvGO_4UeN34BO/view?usp=drive_link
https://drive.google.com/file/d/1U9UFoFQDGscN37ruh33yEoE3ShfEWvih/view?usp=drive_link
https://drive.google.com/file/d/17eebMkG47i888mF_FV3gVjDmf6imYw_P/view?usp=drive_link
https://drive.google.com/file/d/1nMwF1ZgD9VQ0GGNBkcpAbgU7wBVhu60I/view?usp=drive_link
https://drive.google.com/file/d/1BjSUPSGgalrHeZCJnQwb5btLzpdqYD4O/view?usp=drive_link
https://e0zu9q0wme4.feishu.cn/file/GxnubC0esoUvVmxuV48cnxFznmZ?from=from_copylink
https://sbyxu2l9z8.feishu.cn/file/GWs4b1jO8o5EXxxNAN1cLamHn0f
https://e0zu9q0wme4.feishu.cn/file/MO7JbmEqRoLh1dxSLVdcZADNn4b
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

1.5 to 2 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America

### How will you be distributing your data to storage providers

Cloud storage (i.e. S3), HTTP or FTP server, Shipping hard drives

### How do you plan to choose storage providers

Slack, Big Data Exchange, Partners

### How do you plan to make deals to your storage providers

Boost client, Lotus client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by CockroachBoss** [comment]
We're KYC certified with github, I'll be KYB certified next!
![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/134630973/36b188d2-5652-4a90-ba3b-cae68579d469)

**Comment by data-programs** [comment]
<img width="32" alt="KYC" Verified src="https://stable.filplus.storage/images/filplus-kyc-verified-badge.png"/>

This user’s identity has been verified through [filplus.storage](https://filplus.storage)

**Comment by Sunnyiscoming** [comment]
Whether this is a public enterprise dataset?
E-FIL+ is always applied for private enterprise datasets.

**Comment by CockroachBoss** [comment]
Hello, MetaEra is a private enterprise.
@Sunnyiscoming

**Comment by Sunnyiscoming** [comment]
I want to make it clear whether the data is public or private?

**Comment by CockroachBoss** [comment]
@Sunnyiscoming 
I confirm once again that the data is private data. As a mainstream web3 media company in Hong Kong, our data structure includes not only high-resolution images, videos, and audio. While some of this data may be published on our MetaEra platform, a significant portion of the data belongs exclusively to our organization as private data.

**Comment by CockroachBoss** [comment]
@kevzak @Sunnyiscoming 
What else do I need to do to move forward, please?

**Comment by kevzak** [comment]
@CockroachBoss please see requirements listed here: https://efilplus.super.site/

you still need to complete KYB check.

**Comment by CockroachBoss** [comment]
Keep  open.

**Comment by CockroachBoss** [comment]
Have completed the KYB process and paid the verification fee

@kevzak @Sunnyiscoming

![d7286925b9c49d650f184b673c80388](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/134630973/15d77394-a28f-4143-855f-eecda5df2af1)

**Comment by CockroachBoss** [comment]
Have completed the KYB process and paid the verification fee

@kevzak @Sunnyiscoming

**Comment by kevzak** [comment]
Looks like still a few pending verifications. Once it shows KYB complete, let me know @CockroachBoss
