### ISSUE TITLE
[DataCap Application] NOAA National Blend of Models

### ISSUE THREAD

**Issue by KalebYang** [filecoin-project/filecoin-plus-large-datasets#2205]
### Data Owner Name

NOAA

### What is your role related to the dataset

Data Preparer

### Data Owner Country/Region

United States

### Data Owner Industry

Environment

### Website

https://www.noaa.gov/

### Social Media

```text
https://twitter.com/NOAA
https://www.facebook.com/NOAA
```

### Total amount of DataCap being requested

15PiB

### Expected size of single dataset (one copy)

1.1PiB

### Number of replicas to store

10

### Weekly allocation of DataCap requested

1PiB

### On-chain address for first allocation

f1hf2lh3kb45my2wypi7qsj3s6jqwbujsxghe6qga

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
The National Blend of Models (NBM) is a nationally consistent and skillful suite of calibrated forecast guidance based on a blend of both NWS and non-NWS numerical weather prediction model data and post-processed model guidance. The goal of the NBM is to create a highly accurate, skillful and consistent starting point for the gridded forecast
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
National Blend of Models (NBM) COG Format and National Blend of Models (NBM) Grib2 Format
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### If you are a data preparer. What is your location (Country/Region)

Singapore

### If you are a data preparer, how will the data be prepared? Please include tooling used and technical details?

```text
We plan use lotus or Boost to prepared data.
```

### Has this dataset been stored on the Filecoin network before? If so, please explain and make the case why you would like to store this dataset again to the network. Provide details on preparation and/or SP distribution.

```text
It seems there's no other applications.
```

### Please share a sample of the data

```text
aws s3 ls --no-sign-request s3://noaa-nbm-pds/
aws s3 ls --no-sign-request s3://noaa-nbm-grib2-pds/
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

More than 3 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, Europe

### How will you be distributing your data to storage providers

HTTP or FTP server, IPFS, Shipping hard drives, Lotus built-in data transfer

### How do you plan to choose storage providers

Slack, Filmine, Big Data Exchange, Partners

### If you already have a list of storage providers to work with, fill out their names and provider IDs below

```text
f0509981 Guiyang
f02251709 Chengdu, CN
f02029743 Singapore
f02169597 Guangdong
```

### How do you plan to make deals to your storage providers

Lotus client, Singularity

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
- Have you prepared enough token for sector pledge?
complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

**Comment by KalebYang** [comment]
@Sunnyiscoming 
Yes, I have checked with SPs. 
I have filled the form. Please check it, thank you!

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 15PiB

**Expected weekly DataCap usage rate**
> 1PiB

**Client address**
>f1hf2lh3kb45my2wypi7qsj3s6jqwbujsxghe6qga

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 15PiB

**Expected weekly DataCap usage rate**
> 1PiB

**Client address**
>f1hf2lh3kb45my2wypi7qsj3s6jqwbujsxghe6qga

**Comment by KalebYang** [comment]
Yes, hope notary can sign for my application.

**Comment by MRJAVAZHAO** [comment]
How many sps will participant in storage?

**Comment by KalebYang** [comment]
@MRJAVAZHAO Hello, now we have found more than 5 sps for storage. Since we haven't receive any datacap, we can not contact more sps to work together. After be allocated, we will continue to find more sps to store the data.

**Comment by kevzak** [comment]
No SP entity or contacts provided. Please update, fill registration form again if needed. Closing until updated.

**Comment by KalebYang** [comment]
@kevzak Hello KZ, I was submitted the Fil+ registration form on Sep 22! I've given all the information I know. Now I send the form again. Check it out, please.

**Comment by KalebYang** [comment]
@kevzak And can you help open the application?

**Comment by KalebYang** [comment]
Yes!

**Comment by Filplus-govteam** [comment]
SPs provided
f0509981 |He is a personal SP | Guiyang | x | Laura
f02251709 | He is a personal SP | Chengdu, CN | x | Alan
f02029743 | He is a personal SP | Singapore | x | Andrew
f02169597 | He is a personal SP | Guangdong | x | don't have slack
f0420161 | THe is a personal SP | Toronto, Ontario, CA | x | Tomas

@KalebYang need more proof of SP Entity and distribution than this. closing until updated
