### ISSUE TITLE
[DataCap Application] <xt> - <xt>

### ISSUE THREAD

**Issue by winter0707winter** [filecoin-project/filecoin-plus-large-datasets#2207]
### Data Owner Name

xuetian

### What is your role related to the dataset

Data Preparer

### Data Owner Country/Region

China

### Data Owner Industry

Education & Training

### Website

https://www.xuetian.cn/

### Social Media

```text
https://www.xuetian.cn/
```

### Total amount of DataCap being requested

15PiB

### Expected size of single dataset (one copy)

950

### Number of replicas to store

10

### Weekly allocation of DataCap requested

1PiB

### Data Type of Application

Public, Open Commercial/Enterprise

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Since its founding in 2010, Xuedian Education has become a multi-disciplinary, comprehensive and professional education platform enterprise integrating training and teaching, educational product development, and vocational skills training by virtue of its professional, leading and trustworthy teaching and training services. At present, it has opened more than 90 branches in Hangzhou, Beijing, Shanghai, Guangzhou, Shenzhen, Xi'an, Nanjing, Hefei, Zhengzhou, Shenyang, Jinan and other key cities across the country, serving hundreds of thousands of students every year, with a cumulative total of more than one million students, and tens of thousands of enterprises in various industries.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
Mainly educational videos, training videos, etc.
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### If you are a data preparer. What is your location (Country/Region)

China

### Please share a sample of the data

```text
https://www.xuetian.cn/open-class
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Sporadic

### For how long do you plan to keep this dataset stored on Filecoin

1.5 to 2 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America

### How will you be distributing your data to storage providers

HTTP or FTP server, Shipping hard drives

### How do you plan to choose storage providers

Slack, Partners

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
- Could you send an email to filplus-app-review@fil.org with your official domain in order to confirm your identity? Email name should includes the issue id #2207.
- Have you prepared enough token for sector pledge?
- Are you a data preparer? What is your previous experience as a data-preparer? List previous applications and client IDs
- How will the data be prepared? Please include tooling used and technical details
- If you are not preparing the data, who will prepare the data?  (Name and Business)
- Has this dataset been stored on Filecoin before? If so, why are you choosing to store it again?
- Best practice for storing large datasets includes ideally, storing it in 3 or more regions, with 4 or more storage provider operators or owners.You should list Miner ID, Business Entity, Location of sps you will cooperate with.
- Per the https://github.com/filecoin-project/notary-governance/issues/922 for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

**Comment by winter0707winter** [comment]
1. The verification email has been sent.
2. yes, most of the SPs have prepared a large amount of fil.
3. I am a first time data preparer, matched with practitioners in the filecoin industry and know some ways of data preparation. boost or lotus are good tools.
4. First time storage.
5. f02122388 china
   f03223 North America ca
   f01986262 Hubei
   f0861589 USA
Meanwhile, more SPs are being contacted
6. tables are completed.

**Comment by winter0707winter** [comment]
Hi @Sunnyiscoming  can I get an updated reply? Thanks！

**Comment by Aaron01230** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedhdxphhozb67erg65drfiwmyvqmvtpczko3issiyjdjrzpf6ijbc 
#### Address 
> f14d3vubmq6xqimope655lrkr2425v6v2qg6byjba
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f1xrnysd4gimg64d4l6qi7ulzwwq22c6vfg6lpw3i
#### Id
> 82159a0c-f969-4c2b-9f0b-ae0637140a1e
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedhdxphhozb67erg65drfiwmyvqmvtpczko3issiyjdjrzpf6ijbc

**Comment by woshidama323** [comment]
Will support this application for the first stage 
Wish you could follow the rules of FILPlus during your work

**Comment by woshidama323** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced2qr6ktaslata6g6ksl5o5yl6gyfvyiz7p2354lh5lvhgaa6h5lm 
#### Address 
> f14d3vubmq6xqimope655lrkr2425v6v2qg6byjba
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f12tk3adljauwnd3hjbigpfxb7b7gdlj63p6afwtq
#### Id
> 82159a0c-f969-4c2b-9f0b-ae0637140a1e
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced2qr6ktaslata6g6ksl5o5yl6gyfvyiz7p2354lh5lvhgaa6h5lm

**Comment by winter0707winter** [comment]
In progress.

**Comment by herrehesse** [comment]
Keep singing abusive requests @woshidama323 & @Aaron01230 ! I hope you believe in the future of this project.

**Comment by herrehesse** [comment]
checker:manualTrigger

**Comment by laurarenpanda** [comment]
checker:manualTrigger

**Comment by Bitengine-reeta** [comment]
The report looks good. I will support the current second round. I hope SP will maintain a good retrieval rate in the later period.

**Comment by Bitengine-reeta** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb6znju2v2g34qfu5qscv2kconk2pwfrxmsxepgimdcenvxcronma 
#### Address 
> f14d3vubmq6xqimope655lrkr2425v6v2qg6byjba
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f1jyvhxp4kmwreo22ke4itspraznpudw3uqaink5i
#### Id
> 7aee05c8-35d7-4711-ae11-97495508b04c
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb6znju2v2g34qfu5qscv2kconk2pwfrxmsxepgimdcenvxcronma

**Comment by METAVERSEDATAMINING** [comment]
@winter0707winter I would like to know about the data preparation status and storage plan, such as the amount of data currently available and whether proof can be provided. Also, how many backups are being prepared for storage and how will they be distributed to the SPs in different regions?

**Comment by winter0707winter** [comment]
> @winter0707winter I would like to know about the data preparation status and storage plan, such as the amount of data currently available and whether proof can be provided. Also, how many backups are being prepared for storage and how will they be distributed to the SPs in different regions?

As an online education and training institution, we have recorded courses covering popular industries such as architecture, finance, and design. For data examples, please refer to 
https://space.bilibili.com/690802979/video
We continue to contact different SPs for data onchain, and more SPs will join in the future in order to store our data in a decentralized manner.
The number of data backups we plan to store is between 7-10.

**Comment by METAVERSEDATAMINING** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebaupthocuvsu65mouxinqzockxl54yutllus62fxryh5p3p3e64e 
#### Address 
> f14d3vubmq6xqimope655lrkr2425v6v2qg6byjba
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f17idrnfnxl2mbgcgr57a6z2c6lj2qx56gvm3336i
#### Id
> 7aee05c8-35d7-4711-ae11-97495508b04c
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebaupthocuvsu65mouxinqzockxl54yutllus62fxryh5p3p3e64e

**Comment by herrehesse** [comment]
![Screenshot 2023-10-19 at 09 40 01](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/70132857/fddd85fa-8469-4d2a-8a62-e1d4f3b300cc)

ABUSE ABUSE!
CLEAR THIS ENTITY IS SELF-DEALING & FAKE VPN DISTRIBUTION

Abusive notaries for the 100th time: @METAVERSEDATAMINING @Bitengine-reeta @Aaron01230 @woshidama323 

Why are we stil allowing this behaviour on chain?
@Kevin-FF-USA @dkkapur @galen-mcandrew @simonkim0515 @galargh 

Remove this application and all notaries immediately.

**Comment by winter0707winter** [comment]
The results obtained after communicating with SP:
IPTelecom Global is an ISP company operating globally. It is normal for an ASN to have routes in different regions, so the resulting "name" is the same. You can view their annouced network routes under AS63916 [here](https://bgp.he.net/AS63916).

**Comment by winter0707winter** [comment]
The results obtained after communicating with SP:
IPTelecom Global is an ISP company operating globally. It is normal for an ASN to have routes in different regions, so the resulting "name" is the same. You can view their annouced network routes under AS63916 [here](https://bgp.he.net/AS63916).

**Comment by kevzak** [comment]
checker:manualTrigger

**Comment by kevzak** [comment]
SPs taking deals:
f02363305 | Shenzhen, Guangdong, CNCTGNet | 24.03 TiB | 5.02% | 24.03 TiB | 0.00%
f02818480 | Dallas, Texas, USFlexential Colorado Corp. | 88.91 TiB | 18.55% | 88.91 TiB | 0.00%
f02817832new | Dallas, Texas, USFlexential Colorado Corp. | 84.97 TiB | 17.73% | 84.97 TiB | 0.00%
f02809368 | Tokyo, Tokyo, JPIPTELECOM Global | 93.75 TiB | 19.57% | 93.75 TiB | 0.00%
f02812307 | Singapore, Singapore, SGIPTELECOM Global | 93.75 TiB | 19.57% | 93.75 TiB | 0.00%
f02812314 | Los Angeles, California, USIPTELECOM Global | 93.75 TiB | 19.57% | 93.75 TiB | 0.00%

SPs provided upfront:

f02122388 || nanhao | China | no | /
f03223 | | TopBlocks | NA CA | no | HarryM
f01986262 | | SXX | Hubei | no | /
f0861589 |  | SDcloud | USA | no | 

No SPs match - closing

**Comment by winter0707winter** [comment]
Hi @kevzak, thanks for the guidance.

As for the application, we did communicate with SPs f02122388, f03223, f01986262, f0861589 at the beginning, but due to various reasons, these SPs were not able to encapsulate in a timely manner. SPs encapsulation cooperation is actually about timing, right place, right person and right place, and you can't have one without the other.

So we found the following SPs for cooperation, we believe that KYC and the actual package has a certain discrepancy can be understood, more attention should be paid to data decentralization. The following is the SP node information, we will subsequently disclose new SP information. Thank you.

f02363305 HZDC
f02818480 SJX
f02817832 SJX
f02809368 Tom Liu
f02812307 Alice Xu
f02812314 Jerry Zhang

**Comment by winter0707winter** [comment]
> > @winter0707winter我想了解一下数据准备情况和存储计划，例如目前可用的数据量以及是否可以提供证明。另外，准备存储多少备份以及如何将它们分发到不同区域的 SP？
> 
> 作为在线教育培训机构，我们录制的课程涵盖建筑、金融、设计等热门行业。数据示例请参考 https://space.bilibili.com/690802979/video 我们不断联系不同的SP进行数据上链，未来还会有更多的SP加入，以便去中心化的方式存储我们的数据。 我们计划存储的数据备份数量在7-10个之间。

@kevzak We have also explained it briefly here, and we will continue to find different SPs for data storage.

**Comment by winter0707winter** [comment]
@kevzak Can I get an updated response?

**Comment by winter0707winter** [comment]
@kevzak Please help to reopen, SPs tokens are ready. Thank you！

**Comment by winter0707winter** [comment]
> SPs taking deals: f02363305 | Shenzhen, Guangdong, CNCTGNet | 24.03 TiB | 5.02% | 24.03 TiB | 0.00% f02818480 | Dallas, Texas, USFlexential Colorado Corp. | 88.91 TiB | 18.55% | 88.91 TiB | 0.00% f02817832new | Dallas, Texas, USFlexential Colorado Corp. | 84.97 TiB | 17.73% | 84.97 TiB | 0.00% f02809368 | Tokyo, Tokyo, JPIPTELECOM Global | 93.75 TiB | 19.57% | 93.75 TiB | 0.00% f02812307 | Singapore, Singapore, SGIPTELECOM Global | 93.75 TiB | 19.57% | 93.75 TiB | 0.00% f02812314 | Los Angeles, California, USIPTELECOM Global | 93.75 TiB | 19.57% | 93.75 TiB | 0.00%
> 
> SPs provided upfront:
> 
> f02122388 || nanhao | China | no | / f03223 | | TopBlocks | NA CA | no | HarryM f01986262 | | SXX | Hubei | no | / f0861589 | | SDcloud | USA | no |
> 
> No SPs match - closing

Hi @kevzak, thanks for the guidance.

As for the application, we did communicate with SPs f02122388, f03223, f01986262, f0861589 at the beginning, but due to various reasons, these SPs were not able to encapsulate in a timely manner. SPs encapsulation cooperation is actually about timing, right place, right person and right place, and you can't have one without the other.

So we found the following SPs for cooperation, we believe that KYC and the actual package has a certain discrepancy can be understood, more attention should be paid to data decentralization. The following is the SP node information, we will subsequently disclose new SP information. Thank you.

f02363305 HZDC
f02818480 SJX
f02817832 SJX
f02809368 Tom Liu
f02812307 Alice Xu
f02812314 Jerry Zhang

Can we continue？

**Comment by Filplus-govteam** [comment]
Email sent to confirm SP entity and location

**Comment by winter0707winter** [comment]
> Email sent to confirm SP entity and location

Responded, is it possible to continue?

The application was filed on September 17th so far, and if it doesn't proceed in time, it could be another batch of new SPs in 1 week.

After all, the SPs program can be adjusted at any time. I ask for your understanding, thank you!

**Comment by winter0707winter** [comment]
Happy new year！@kevzak @Filplus-govteam @galen-mcandrew any updation ？

**Comment by winter0707winter** [comment]
Hi,any updation? @kevzak @Filplus-govteam

**Comment by Sunnyiscoming** [comment]
checker:manualTrigger

**Comment by Sunnyiscoming** [comment]
Please confirm the list of sps here if there is any more sp.

**Comment by winter0707winter** [comment]
According to the requirements, the latest disclosure of SPs' collaboration is as follows. To ensure the smooth progress of LDN, #2207 will be closed, and new updates and discussions will take place in #2306. Thank you.

f02829749 xingcircle Shenzhen, Guangdong, CN
f02829748 Mole Shenzhen, Guangdong, CN
f02818480 GH Dallas, Texas, US
f02363305 XYZ Shenzhen, Guangdong, CN
f02824134 GH Dallas, Texas, US
f02934879 HK_Fil Hong Kong, Central and Western, HK
f02809368 Tom Liu Tokyo, Tokyo, JP
f02812307 Alice Xu Singapore, Singapore, SG
f02812314 Jerry Los Angeles, California, US
f02934869 HK_Fil Hong Kong, Central and Western, HK
f02817832 GH Dallas, Texas, US
