### ISSUE TITLE
[DataCap Application] Resolution Rapid Refresh (HRRR) Model

### ISSUE THREAD

**Issue by himomo007** [filecoin-project/filecoin-plus-large-datasets#2211]
### Data Owner Name
Resolution Rapid Refresh (HRRR) Model

### What is your role related to the dataset
Data Preparer

### Data Owner Country/Region
United States

### Data Owner Industry
Environment

### Website
[https://github.com/awslabs/open-data-docs/tree/main/docs/noaa/noaa-hrrr](https://github.com/awslabs/open-data-docs/tree/main/docs/noaa/noaa-hrrr)

### Social Media
Website: https://www.noaa.gov/    (Website)

### Total amount of DataCap being requested
35 PiB

### Expected size of single dataset (one copy)
3.5 PiB

### Number of replicas to store
10

### Weekly allocation of DataCap requested
1 PiB

### On-chain address for first allocation
f1hm6tbz2q5mxl7zvmxgvpehg277ffjhgmi6hcfhq

### Data Type of Application
Public, Open Dataset (Research/Non-Profit)

### Custom multisig
- [x] Use Custom Multisig

### Identifier
efil

### Share a brief history of your project and organization
The HRRR is a NOAA real-time 3-km resolution, hourly updated, cloud-resolving, convection-allowing atmospheric model, initialized by 3km grids with 3km radar assimilation. Radar data is assimilated in the HRRR every 15 min over a 1-h period adding further detail to that provided by the hourly data assimilation from the 13km radar-enhanced.
HRRR implementations at NCEP
HRRRv1 - 30 Sept 2014
HRRRv2 - 23 Aug 2016
HRRRv3 - 12 July 2018
HRRRv4 - 2 Dec 2020

### Is this project associated with other projects/ecosystem stakeholders?
No

### If answered yes, what are the other projects/ecosystem stakeholders
n/a

### Describe the data being stored onto Filecoin
1. The High-Resolution Rapid Refresh (HRRR) is sourced by Global System Laboratory from National Oceanic && Atmospheric Administration. It is a NOAA real-time 3-km resolution, hourly updated, cloud-resolving, convection-allowing atmospheric model, initialized by 3km grids with 3km radar assimilation. Radar data is assimilated in the HRRR every 15 min over a 1-h period adding further detail to that provided by the hourly data assimilation from the 13km radar-enhanced Rapid Refresh. 
2. HRRR dataset stored on AWS is the archive since 2014 with a total size of 2PiB and 38526457 Object.

### Where was the data currently stored in this dataset sourced from
AWS Cloud

### If you answered "Other" in the previous question, enter the details here
n/a

### If you are a data preparer, what is your location (City and Country)
USA

### If you are a data preparer, how will the data be prepared? Please include tooling used and technical details?
via boost or lotus

### If you are not preparing the data, who will prepare the data?  (Provide name and business)
n/a

### Has this dataset been stored on the Filecoin network before? If so, please explain and make the case why you would like to store this dataset again to the network. Provide details on preparation and/or SP distribution.
It was stored before, but there are some applications that have been closed. As a public dataset of significance to the development of human history, it deserves to be stored over and over again.

### Please share a sample of the data
https://rapidrefresh.noaa.gov/hrrr/

### Confirm that this is a public dataset that can be retrieved by anyone on the Network
Yes

### If you chose not to confirm, what was the reason
n/a

### What is the expected retrieval frequency for this data
Yearly

### For how long do you plan to keep this dataset stored on Filecoin
1.5 to 2 years

### In which geographies do you plan on making storage deals
Greater China, Asia other than Greater China, North America, Europe

### How will you be distributing your data to storage providers
HTTP or FTP server

### How do you plan to choose SP
Slack

### If you answered "Others" in the previous question, what is the tool or platform you plan to use
n/a

### If you already have a list of storage providers to work with, fill out their names and provider IDs below
n/a

### How do you plan to make deals to your storage providers
Boost client

### If you answered "Others/custom tool" in the previous question, enter the details here
n/a

### Can you confirm that you will follow the Fil+ guideline
Yes

_Application created via [filplus.storage](https://filplus.storage)_

**Comment by data-programs** [comment]
This application requests a total of 35 PiB, so it’s labeled `efil+`

**Comment by kevzak** [comment]
Hello @himomo007 please see E-Fil application requirements here: https://efilplus.super.site/ 

let me know if you have any questions

**Comment by himomo007** [comment]
<img width="893" alt="image" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/144330825/8c05b254-1568-4a34-89dd-6b68ed381baa">

As a public dataset, the steps have been followed. Thanks

**Comment by himomo007** [comment]
<img width="1374" alt="image" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/144330825/b2f35e60-90a7-4c5d-b5cc-bd429dbaeb04">
Identity verified,thanks！

**Comment by data-programs** [comment]
<img width="32" alt="KYC" Verified src="https://stable.filplus.storage/images/filplus-kyc-verified-badge.png"/>

This user’s identity has been verified through [filplus.storage](https://filplus.storage)

**Comment by herrehesse** [comment]
Throwaway account asking for 35 PiB on a already stored dataset. Do not engage further.

**Comment by himomo007** [comment]
hi, @Sunnyiscoming @kevzak @Kevin-FF-USA  I have waited for some time and completed KYC as required, can I get further reply now?Thanks！

**Comment by himomo007** [comment]
Hi @Sunnyiscoming  @kevzak I have been applying for 2-3 weeks now and have completed KYC as required, please help to move on to the next step, thanks!

**Comment by herrehesse** [comment]
Stop scamming.

**Comment by kevzak** [comment]
> <img alt="image" width="893" src="https://user-images.githubusercontent.com/144330825/269237991-8c05b254-1568-4a34-89dd-6b68ed381baa.png">
> As a public dataset, the steps have been followed. Thanks

@himomo007 the steps have not been followed completely. You still need to complete a KYB check https://efilplus.synaps.me/

**Comment by himomo007** [comment]
> > <img alt="image" width="893" src="https://user-images.githubusercontent.com/144330825/269237991-8c05b254-1568-4a34-89dd-6b68ed381baa.png">
> > As a public dataset, the steps have been followed. Thanks
> 
> @himomo007 the steps have not been followed completely. You still need to complete a KYB check https://efilplus.synaps.me/

Hi @kevzak ，The High-Resolution Rapid Refresh (HRRR) is sourced by Global System Laboratory from National Oceanic && Atmospheric Administration. It is a NOAA real-time 3-km resolution, hourly updated, cloud-resolving, convection-allowing atmospheric model, initialized by 3km grids with 3km radar assimilation. Radar data is assimilated in the HRRR every 15 min over a 1-h period adding further detail to that provided by the hourly data assimilation from the 13km radar-enhanced Rapid Refresh.HRRR dataset stored on AWS is the archive since 2014 with a total size of 2PiB and 38526457 Object.

As an open public dataset, we believe we have completed all the steps.
Any help in viewing it would be appreciated！

**Comment by himomo007** [comment]
@kevzak @Sunnyiscoming Hi, can we continue? This is a public dataset and SPs want to store this valuable public dataset.

**Comment by herrehesse** [comment]
No @himomo007 we can not continue. This is fraud and we do not want this any longer in the community.

**Comment by himomo007** [comment]
@herrehesse Who are you? Are you the official governance team?

@kevzak @Sunnyiscoming Hopefully more attention will be paid to the Late Storage Report, SPs are ready to go.

**Comment by himomo007** [comment]
Hi @kevzak @Sunnyiscoming it's been over a month since we applied, can we continue now?

**Comment by himomo007** [comment]
Hi @Sunnyiscoming Can we continue? This seems a little too long.Thanks.

**Comment by himomo007** [comment]
Hi @Sunnyiscoming  can I get an update?

**Comment by himomo007** [comment]
Hi @Sunnyiscoming ,what should we do? Seems like a bit of an inefficient approval process.

**Comment by himomo007** [comment]
Hi @kevzak ,what should we do? Seems like a bit of an inefficient approval process.

**Comment by kevzak** [comment]
I don't see any registration form for 2211 @himomo007

**Comment by himomo007** [comment]
> @himomo007 you'll need to provide proof of location and entity for these SPs
> 
> f02274508 HK f02320312 USA f02211572 CN f02368282 CN f02320270 USA

Since it has been so long, a month and a half has passed, the SPs previously contacted for storage cooperation have changed.

Now we contacted the following SPs and will plan to encapsulate the first batch of DCs in the next 1-2 weeks, as announced below:

f02815456 Xiangyun carolinatang315@gmail.com, USA
f02815451 HZZC nibuil0730@163.com, Canada
f02815448 bluesky danacheng2021@gmail.com, USA
f02809368 Tom Liu daniel@bowyuan.com, Japan
f02814767 XHS 1504068285@qq.com, Korea

So as not to jeopardize the progress, can we please move on? @kevzak

**Comment by himomo007** [comment]
Can we please move on ？   @Sunnyiscoming

**Comment by himomo007** [comment]
It's been two months since the application and SPs are ready, please let us continue, thanks a million! @kevzak

**Comment by himomo007** [comment]
Hi，
@kevzak @simonkim0515 @raghavrmadya @dkkapur @Sunnyiscoming ,what is wrong with you? We have completed all the steps as required and the SPs are waiting.Please!

**Comment by Filplus-govteam** [comment]
Please provide clear entity and location for these SPs @himomo007, Name and country doesn't really validate anything. Closing until updated.

**Comment by himomo007** [comment]
Updation again：

f02815456 Xiangyun [carolinatang315@gmail.com](mailto:carolinatang315@gmail.com), USA
f02815451 HZZC [nibuil0730@163.com](mailto:nibuil0730@163.com), Canada
f02815448 bluesky [danacheng2021@gmail.com](mailto:danacheng2021@gmail.com), USA
f02809368 Tom Liu [daniel@bowyuan.com](mailto:daniel@bowyuan.com), Japan
f02814767 XHS [1504068285@qq.com](mailto:1504068285@qq.com), Korea

**Comment by himomo007** [comment]
@kevzak @Filplus-govteam what should we do next？Can you reopen it？

**Comment by Filplus-govteam** [comment]
@himomo007 please email SP entity and location information to filplus.govteam@gmail.com to confirm distribution
