### ISSUE TITLE
[DataCap Application] Guangdong Zhiyun Urban Construction Technology Co., Ltd.

### ISSUE THREAD

**Issue by tanjian917** [filecoin-project/filecoin-plus-large-datasets#2212]
### Data Owner Name

Guangdong Zhiyun Urban Construction Technology Co., Ltd.

### What is your role related to the dataset

Dataset Owner

### Data Owner Country/Region

China

### Data Owner Industry

Life Science / Healthcare

### Website

https://www.jiancaiyi.com/

### Social Media

```text
https://www.jiancaiyi.com/
```

### Total amount of DataCap being requested

10PiB

### Expected size of single dataset (one copy)

1024TiB

### Number of replicas to store

10

### Weekly allocation of DataCap requested

1PiB

### On-chain address for first allocation

f1kgn5wbp25s4vkjx2saop44573mwfwthig4tb7ba

### Data Type of Application

Public, Open Commercial/Enterprise

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Guangdong Zhiyun Urban Construction Technology Co., Ltd. is the largest architectural design company in South China that integrates raw material production, sales, construction, design, decoration, and after-sales. It is a digital solution provider for the entire construction industry. We have gathered thousands of construction materials construction companies. There are hundreds of architectural designers providing services to customers. From raw materials to construction to after-sales, we have everything.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
Guangdong Zhiyun Urban Construction Technology Co., Ltd. is the largest architectural design company in South China that integrates raw material production.As an architectural design company that integrates raw material production, sales, construction, design, decoration, and after-sales, we have a wide variety of data.
Including construction equipment, architectural design manuscripts, CAD drawings, construction pictures and videos, customer negotiations, etc.
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### If you are a data preparer. What is your location (Country/Region)

China

### Please share a sample of the data

```text
As an architectural design company that integrates raw material production, sales, construction, design, decoration, and after-sales, we have a wide variety of data.
Link: https://pan.baidu.com/s/1IGhv0Cb-k9LKmQtkXTsOtQ?pwd=6vjh Extraction code: 6vjh
Link: https://pan.baidu.com/s/1shij_nj3vXTIzXzzLoBblQ?pwd=3f41 Extraction code: 3f41
Link: https://pan.baidu.com/s/1PUGbZh1JUPTlb3NLBHig4Q?pwd=vjdy Extraction code: vjdy
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Monthly

### For how long do you plan to keep this dataset stored on Filecoin

1.5 to 2 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, Europe

### How will you be distributing your data to storage providers

Cloud storage (i.e. S3), HTTP or FTP server, Shipping hard drives, Lotus built-in data transfer

### How do you plan to choose storage providers

Slack, Filmine

### How do you plan to make deals to your storage providers

Boost client, Lotus client, Bidbot, Singularity

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by tanjian917** [comment]
#2184

**Comment by tanjian917** [comment]
It has been 12 days since there was a problem with 2184. We have closed 2184 and promised not to open it again. Please pass 2212 as soon as possible. Thank you very much for your support and understanding.

**Comment by tanjian917** [comment]
@Sunnyiscoming @simonkim0515 @raghavrmadya @jbenet @Kevin-FF-USA

**Comment by Sunnyiscoming** [comment]
The issue of 2184 is being processed, please wait for a while.

**Comment by tanjian917** [comment]
@Sunnyiscoming  You close #2184 and passing 2212  is the best option.

**Comment by herrehesse** [comment]
@tanjian917 selfdealing. @Sunnyiscoming please take a look at the previous CID report. Can we close this now?

**Comment by tanjian917** [comment]
This is a very obvious thing. The bot is buging. I think that as a professional technician, you should be strict in what you say. @herrehesse

**Comment by Sunnyiscoming** [comment]
Whether SPs support data retrieval? Please provide proof of that.

**Comment by tanjian917** [comment]
boost retrieve -p=f02760664 --o=output.car bafykbzaceaddyhryyz4uipbmde56ne7254aqouvneuyrnz7eo4vduxlb2fjvu
<img width="678" alt="WechatIMG1150" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/42170625/aa462869-345a-4755-834c-5e46092e573e">
boost retrieve -p=f02200472 --o=output.car bafykbzacea5jdnt7pvhzretdpq7w3naazqxthjwm4vyyr3vim3mc6uiv6ji6g
<img width="676" alt="WechatIMG1152" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/42170625/30dd1ca7-d4e2-47dd-b1fb-8a88f3070c7b">
boost retrieve -p=f01920887 --o=output.car bafykbzacedbhjymw62tctgodghkwb5eribujq66vegrp4esehozjtlnyi7oe6
<img width="679" alt="WechatIMG1154" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/42170625/1ae4105b-3549-4cd9-84df-fc3f17019a6f">
boost retrieve -p=f02221112 --o=output.car bafykbzaceb7ubuc2csxi45e3puchwyop7kmr4vyjcengxyaahfph7qgppw4i2
<img width="680" alt="WechatIMG12813" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/42170625/1a64d8d6-7814-4cb0-a070-9a0f57c8b295">

**Comment by herrehesse** [comment]
This is a very obvious thing. The bot is buging? Excuse me? You are self-dealing. Bot is working fine. Dont cheat the system.
