### ISSUE TITLE
[DataCap Application] LAMOST DR7

### ISSUE THREAD

**Issue by stroage** [filecoin-project/filecoin-plus-large-datasets#2213]
### Data Owner Name

LAMOST DR7

### What is your role related to the dataset

Data Preparer

### Data Owner Country/Region

United States

### Data Owner Industry

Life Science / Healthcare

### Website

http://www.lamost.org/dr7/v2.0/

### Social Media

```text
http://www.lamost.org/dr7/v2.0/
```

### Total amount of DataCap being requested

10PiB

### Expected size of single dataset (one copy)

1024T

### Number of replicas to store

10

### Weekly allocation of DataCap requested

1PiB

### On-chain address for first allocation

f1xrw6xh7zs4tqso4in7vh6pnpq2tenj2t7hk3voy

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Observed Plates：4,922 Total Spectra：10,431,197

Guoshoujing Telescope (the Large Sky Area Multi-Object Fiber Spectroscopic Telescope LAMOST) is a National Major Scientific Project built by the Chinese Academy of Sciences. Funding for the project has been provided by the National Development and Reform Commission. LAMOST is operated and managed by the National Astronomical Observatories, Chinese Academy of Sciences.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
http://www.lamost.org/dr7/v2.0/
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### If you are a data preparer. What is your location (Country/Region)

Singapore

### Please share a sample of the data

```text
http://www.lamost.org/dr7/v2.0/search#gaiaconstraints
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Monthly

### For how long do you plan to keep this dataset stored on Filecoin

1 to 1.5 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, Europe

### How will you be distributing your data to storage providers

Cloud storage (i.e. S3), HTTP or FTP server, IPFS, Shipping hard drives, Lotus built-in data transfer

### How do you plan to choose storage providers

Slack, Filmine, Big Data Exchange

### How do you plan to make deals to your storage providers

Boost client, Lotus client, Bidbot, Singularity

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
Any update here?

**Comment by stroage** [comment]
Our have prepared enough token for sector pledge. We have seen that data such as NOAA has been applied for multiple times but you have all passed it, while LAMOST DR7 is only the second application, and the data backup is within a reasonable range. I think this is reasonable.
We plan to cooperate with these SP: 
f02229545
f01422327
f02252024
f02252023
f01110088
f02002141

**Comment by stroage** [comment]
I submitted it [Fil+ registration form](https://form.jotform.com/231862753015656) t, can you pass us? thanks a lot~

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 10PiB

**Expected weekly DataCap usage rate**
> 1PiB

**Client address**
>f1xrw6xh7zs4tqso4in7vh6pnpq2tenj2t7hk3voy

**Comment by ipfscn** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceawgjdwvug2ajjafld43pe2jdqjinbvbvbwb3ii5sfr5zka4szy6m 
#### Address 
> f1xrw6xh7zs4tqso4in7vh6pnpq2tenj2t7hk3voy
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f1j4n74chme7whbz3yls4a7ixqewb6dijypqg2a3a
#### Id
> 7b8fe2b6-a5d8-4f4e-add1-8d0ed092fc53
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceawgjdwvug2ajjafld43pe2jdqjinbvbvbwb3ii5sfr5zka4szy6m

**Comment by junyaoren** [comment]
Everything looks fair to me. I would support this first round of allocation.

**Comment by junyaoren** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedmi5mx3cb7egk75n4mzey2vjqvwctdduma5xgyl6tbtpbgx6i23w 
#### Address 
> f1xrw6xh7zs4tqso4in7vh6pnpq2tenj2t7hk3voy
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f1xzff5xup63o5sygr2swp4zvcajg54lotliimdty
#### Id
> 7b8fe2b6-a5d8-4f4e-add1-8d0ed092fc53
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedmi5mx3cb7egk75n4mzey2vjqvwctdduma5xgyl6tbtpbgx6i23w

**Comment by stroage** [comment]
hey

**Comment by herrehesse** [comment]
checker:manualTrigger

**Comment by herrehesse** [comment]
@Kevin-FF-USA @raghavrmadya @simonkim0515 

Hello guys! Evidence above, all deals to same minerID. No names are given, no region or business contact information.
Please close this application and remove datacap.

**Comment by stroage** [comment]
The total quota in the first round is 512T. Currently, only one of the SPs we cooperate with has started, so we sent 150T DC to this SP, 150/512=29%, not exceeding 30%, which complies with the rules.When other SPs cooperate, we will send the remaining DC to the SP. We will strictly abide by the rules and the proportion of each SP will not exceed 30%.

Please wait a moment, thank you.
<img width="696" alt="WX20231015-131111@2x" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/144337021/947905eb-43d6-415c-8335-d235dec2ad45">

**Comment by herrehesse** [comment]
As stated, No names are given, no region or business contact information.
Please close this application and remove datacap.

**Comment by stroage** [comment]
We have given it and verified[Fil+ registration form](https://form.jotform.com/231862753015656).

**Comment by herrehesse** [comment]
@stroage you need to post it PUBLICLY. Can you do that here?

**Comment by kevzak** [comment]
SPs provided upfront
f02252024 |  | applecould | United States | no | Aamie
f02252023 |  | applecould | Hong Kong | no | Aamie
f01110088 |  | Coffeecomputing | Hong Kong | no | hantao
f01422327 |  | Japan | Huineng | no | alan
f02002141 |  | South Korea | Darun | no | chang

**Comment by kevzak** [comment]
checker:manualTrigger

**Comment by kevzak** [comment]
SPs provided doesn't match SP taking deal

SPs provided have no contact or entity information. Closing until updated

**Comment by stroage** [comment]
checker:manualTrigger

**Comment by stroage** [comment]
Hi, sorry to keep you waiting for a long time, our SP is ready, thank you for your patience, now, we look forward to you reopening it for us, thank you again. @kevzak 
-      SP	          Client	                Area

1. f02831201 	 Juwu Mine	         Guangzhou, Guangdong
2. f02831202	 Juwu Mine	         Guangzhou, Guangdong
3. f02824157	 zhongchuangyun 	 Ningxia 
4. f01110088	 Coffeecomputing 	 HK 
5. f02824140	 cylinder          	 Ningxia
6. f02816081	 KRAL	              Singapore
7. f02816095	 KRAL	              Singapore
8. f02829200	 applecould       	jiangxi

**Comment by stroage** [comment]
Hey, is there any update here? @kevzak

**Comment by stroage** [comment]
What do we need to do so you can reopen it for us? @kevzak

**Comment by stroage** [comment]
Why there aren't any updates?

**Comment by stroage** [comment]
It looks like there won’t be any updates, so I’ll re-open the 2270 application.

**Comment by kevzak** [comment]
checker:manualTrigger

**Comment by kevzak** [comment]
SPs taking deals previously:

f02824157 | Shenzhen, Guangdong, CNCHINA UNICOM China169 Backbone | 49.34 TiB | 9.73% | 49.34 TiB | 0.00%
f02824140 | Shenzhen, Guangdong, CNCHINA UNICOM China169 Backbone | 49.22 TiB | 9.71% | 49.22 TiB | 0.00%
f02831202 | Shenzhen, Guangdong, CNCHINANET-BACKBONE | 51.69 TiB | 10.20% | 51.69 TiB | 0.00%
f02829200 | Nanchang, Jiangxi, CNCHINANET-BACKBONE | 51.69 TiB | 10.20% | 51.69 TiB | 0.00%
f02831201 | Shenzhen, Guangdong, CNCHINANET-BACKBONE | 51.69 TiB | 10.20% | 51.69 TiB | 0.00%
f01110088 | Hong Kong, Central and Western, HKGigabitbank Global | 150.00 TiB | 29.59% | 150.00 TiB | 0.00%
f02816081 | Singapore, Singapore, SGZenlayer Inc | 51.69 TiB | 10.20% | 51.69 TiB | 0.00%
f02816095 | Singapore, Singapore, SGZenlayer Inc | 51.63 TiB | 10.18% | 51.63 TiB | 0.00%

**Comment by kevzak** [comment]
Thank you for clarifying, please provide updates of SP entities and IDs you are working with/not working with

**Comment by Normalnoise** [comment]
Report shows healthy, willing to support

**Comment by Normalnoise** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaectocuh37mpgplt7m3wqlcagtdxkumejp6aafwwrk7ouslqhxpo 
#### Address 
> f1xrw6xh7zs4tqso4in7vh6pnpq2tenj2t7hk3voy
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f1c5non5yf35avgcpsqvxu4yj54yyvxorwyjochqq
#### Id
> 70de5298-fe6d-4a80-9df8-15ebce19410d
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaectocuh37mpgplt7m3wqlcagtdxkumejp6aafwwrk7ouslqhxpo

**Comment by Tom-OriginStorage** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebrphls63slxyb3dywr6oovvvedhnno4aq3dlzdxc2yosucmwqlie 
#### Address 
> f1xrw6xh7zs4tqso4in7vh6pnpq2tenj2t7hk3voy
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f1q6bpjlqia6iemqbrdaxr2uehrhpvoju3qh4lpga
#### Id
> 70de5298-fe6d-4a80-9df8-15ebce19410d
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebrphls63slxyb3dywr6oovvvedhnno4aq3dlzdxc2yosucmwqlie

**Comment by Sunnyiscoming** [comment]
Please provide ID, City, Country, Organization of each SP here.

**Comment by AlanGreaterheat** [comment]
checker:manualTrigger

**Comment by herrehesse** [comment]
checker:manualTrigger

**Comment by herrehesse** [comment]
![Screenshot 2023-12-05 at 09 37 52](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/70132857/b674208d-81f0-454d-a390-d37d9f6f5b55)

No global distribution what so ever, no contact information of SP's, most likely self-dealing (see concurrent IDs).

**Comment by stroage** [comment]
> @kevzak Dear, In order to give you a better view, we have relisted the cooperative SPs again. We sincerely hope that you will open them for us. For this, we have closed 2273, I just hope you can reopen 2213. It has been 33 days. We have waited for too long. We are very sad. Thank you for your help.
> 
> Provider	Location	SP Entity or Personal
> f01110088	HK	Coffeecomputing
> f02831201	GuangDong	Juwu Mine
> f02831202	GuangDong	Juwu Mine
> f02816081	Singapore	KRAL
> f02816095	Singapore	KRAL
> f02824157	Beijing	zhongchuangyun
> f02824140	Beijing	zhongchuangyun
> f02829200	jiangxi	applecould

We have explained it. hope you will take a few minutes to read more about the information. Thank you for your patience.

**Comment by 1ane-1** [comment]
checker:manualTrigger

**Comment by 1ane-1** [comment]
Pay attention  to the data replication problem.

**Comment by 1ane-1** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacechcxupdphjpwii67rwvcyoalqstklfqwr3w6l66y5fbchr3slupu 
#### Address 
> f1xrw6xh7zs4tqso4in7vh6pnpq2tenj2t7hk3voy
#### Datacap Allocated
> 2.00PiB
#### Signer Address
> f1mdk7s2vntzm6hu35yuo6vjubtrpfnb2awhgvrri
#### Id
> 639dde8a-ad11-471a-90df-cde9ef34d716
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacechcxupdphjpwii67rwvcyoalqstklfqwr3w6l66y5fbchr3slupu

**Comment by xinaxu** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedmmvyboaov4exljwcn2ppwr4g3fkezdletwr3ttcjgbial2hrbik 
#### Address 
> f1xrw6xh7zs4tqso4in7vh6pnpq2tenj2t7hk3voy
#### Datacap Allocated
> 2.00PiB
#### Signer Address
> f1k3ysofkrrmqcot6fkx4wnezpczlltpirmrpsgui
#### Id
> 639dde8a-ad11-471a-90df-cde9ef34d716
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedmmvyboaov4exljwcn2ppwr4g3fkezdletwr3ttcjgbial2hrbik

**Comment by ipollo00** [comment]
checker:manualTrigger

**Comment by ipollo00** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedyuadwcavrv6iecdutekwcnuoxgmicudp32cfqu2keditsysylha 
#### Address 
> f1xrw6xh7zs4tqso4in7vh6pnpq2tenj2t7hk3voy
#### Datacap Allocated
> 2.00PiB
#### Signer Address
> f1n5wlrrhoxpkgwij25xrtt7w7g2k3fhbthmdn6ri
#### Id
> 6365d7bf-14f0-4b31-8905-dfa73c96fad0
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedyuadwcavrv6iecdutekwcnuoxgmicudp32cfqu2keditsysylha

**Comment by stroage** [comment]
checker:manualTrigger

**Comment by woshidama323** [comment]
Very healthy report info about this LDN
Will support

**Comment by woshidama323** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebw2jzatib42p6ajkv7xo5p5syswq2347wfc4oxvuqod6kwma3ps6 
#### Address 
> f1xrw6xh7zs4tqso4in7vh6pnpq2tenj2t7hk3voy
#### Datacap Allocated
> 2.00PiB
#### Signer Address
> f12tk3adljauwnd3hjbigpfxb7b7gdlj63p6afwtq
#### Id
> 6365d7bf-14f0-4b31-8905-dfa73c96fad0
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebw2jzatib42p6ajkv7xo5p5syswq2347wfc4oxvuqod6kwma3ps6

**Comment by stroage** [comment]
checker:manualTrigger

**Comment by Sunnyiscoming** [comment]
SP List provided:
[{"providerID": "f01110088","City": "HK", "Country": "CN", "SPOrg","Coffeecomputing"},
{"providerID": "f02831201","City": "GuangDong", "Country": "CN", "SPOrg","Juwu Mine"},
{"providerID": "f02831202","City": "GuangDong", "Country": "CN", "SPOrg","Juwu Mine"},
{"providerID": "f02816081","City": "XYZ", "Country": "Singapore", "SPOrg","KRAL"},
{"providerID": "f02816095","City": "XYZ", "Country": "Singapore", "SPOrg","KRAL"},
{"providerID": "f02824157","City": "Beijing", "Country": "CN", "SPOrg","zhongchuangyun"},
{"providerID": "f02824140","City": "Beijing", "Country": "CN", "SPOrg","zhongchuangyun"},
{"providerID": "f02829200","City": "jiangxi", "Country": "CN", "SPOrg","applecould"},]

**Comment by stroage** [comment]
checker:manualTrigger

**Comment by stroage** [comment]
| Provider  |                            Location | SP Entity or Personal |
| :-------- | ----------------------------------: | --------------------: |
| f01110088|       HK |       CoffeecomputingI|
| f02831201 |   GuangDong|      Juwu Mine |
| f02831202 |    GuangDong|     Juwu Mine |
| f02816081|      Singapore |       KRAL|
| f02816095 |  Singapore |           KRAL|
| f02824157 |    Beijing|           zhongchuangyun |
| f02824140|   Beijing |            zhongchuangyun|
| f02829200 |  jiangxi |           applecould |
| f02831202 |    GuangDong |             Juwu Mine |
| f02850067 |    HK|           datastone |
| f02850016|   HK |          datastone|
| f02850015 |  HK |         datastone |

**Comment by psh0691** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceailgbhow6fjfswz5nwwr7n5fgkvrbmtdrotbus2xnnqgyebcltk4 
#### Address 
> f1xrw6xh7zs4tqso4in7vh6pnpq2tenj2t7hk3voy
#### Datacap Allocated
> 2.00PiB
#### Signer Address
> f1qdko4jg25vo35qmyvcrw4ak4fmuu3f5rif2kc7i
#### Id
> 4ffd7ad8-2414-4cd9-865e-f3dc3cc8fb6c
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceailgbhow6fjfswz5nwwr7n5fgkvrbmtdrotbus2xnnqgyebcltk4

**Comment by nj-steve** [comment]
checker:manualTrigger

**Comment by luobin544** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedyzbkgkpiqco5e4y3kqu7qt3y432tu4w2ljaebbf7j3tugtcisne 
#### Address 
> f1xrw6xh7zs4tqso4in7vh6pnpq2tenj2t7hk3voy
#### Datacap Allocated
> 2.00PiB
#### Signer Address
> f1tbd632f6w62glfaf7wjpimacbnjiz26poyoes2q
#### Id
> 4ffd7ad8-2414-4cd9-865e-f3dc3cc8fb6c
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedyzbkgkpiqco5e4y3kqu7qt3y432tu4w2ljaebbf7j3tugtcisne

**Comment by laurarenpanda** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecv2tsjbt72nru5ewd62mch6h7mp56dgnd53c3bpyuhuorkxxzupg 
#### Address 
> f1xrw6xh7zs4tqso4in7vh6pnpq2tenj2t7hk3voy
#### Datacap Allocated
> 2.00PiB
#### Signer Address
> f1bp3tzp536edm7dodldceekzbsx7zcy7hdfg6uzq
#### Id
> 991c3bcc-9612-4dd5-9554-8a4e1c2ee602
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecv2tsjbt72nru5ewd62mch6h7mp56dgnd53c3bpyuhuorkxxzupg

**Comment by Aaron01230** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebgag7ngewkw7itevkl4qelqf2c52jhknw4mqdxvztjg43ocnsapo 
#### Address 
> f1xrw6xh7zs4tqso4in7vh6pnpq2tenj2t7hk3voy
#### Datacap Allocated
> 2.00PiB
#### Signer Address
> f1xrnysd4gimg64d4l6qi7ulzwwq22c6vfg6lpw3i
#### Id
> 991c3bcc-9612-4dd5-9554-8a4e1c2ee602
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebgag7ngewkw7itevkl4qelqf2c52jhknw4mqdxvztjg43ocnsapo

**Comment by shuchenglhk** [comment]
checker:manualTrigger

**Comment by sxxfuture-official** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacechm7fzihdjb7rbockaryrvhozwxjuox3yu6xrqpjntgdasyrzqgm 
#### Address 
> f1xrw6xh7zs4tqso4in7vh6pnpq2tenj2t7hk3voy
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f1foiomqlmoshpuxm6aie4xysffqezkjnokgwcecq
#### Id
> b0ab3bef-5e8f-4402-992b-00aadfc7f817
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacechm7fzihdjb7rbockaryrvhozwxjuox3yu6xrqpjntgdasyrzqgm

**Comment by sxxfuture-official** [comment]
reduce duplicate data for f02850015 and f02850016

**Comment by nj-steve** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaifaxkpan7bujthyev7fw7pghdnln7tz73rdudqsu3tmhxnwdxie 
#### Address 
> f1xrw6xh7zs4tqso4in7vh6pnpq2tenj2t7hk3voy
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f1xx6555qijma7igpnjspyvdunc4vfxkawnpqy5ii
#### Id
> b0ab3bef-5e8f-4402-992b-00aadfc7f817
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaifaxkpan7bujthyev7fw7pghdnln7tz73rdudqsu3tmhxnwdxie

**Comment by ipollo00** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebzb56pkrefizafo5xeplqbzgnwe4tmjv6zvtt33tuo3mhjjdzvgq 
#### Address 
> f1xrw6xh7zs4tqso4in7vh6pnpq2tenj2t7hk3voy
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f1n5wlrrhoxpkgwij25xrtt7w7g2k3fhbthmdn6ri
#### Id
> 4ed54fab-2e52-46f3-a2d9-4c6a60de446b
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebzb56pkrefizafo5xeplqbzgnwe4tmjv6zvtt33tuo3mhjjdzvgq

**Comment by SuperChaiChai** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedvyjebmmeactxj4sphj3djgwyogp6qfxuvanpkrr6waxvigdozb2 
#### Address 
> f1xrw6xh7zs4tqso4in7vh6pnpq2tenj2t7hk3voy
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f12mckci3omexgzoeosjvstcfxfe4vqw7owdia3da
#### Id
> 4ed54fab-2e52-46f3-a2d9-4c6a60de446b
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedvyjebmmeactxj4sphj3djgwyogp6qfxuvanpkrr6waxvigdozb2

**Comment by fdate11** [comment]
checker:manualTrigger
