### ISSUE TITLE
[DataCap Application] < OriginStorage> - <NOAA Rapid Refresh Forecast System>

### ISSUE THREAD

**Issue by Tom-OriginStorage** [filecoin-project/filecoin-plus-large-datasets#2215]
### Data Owner Name
Telnyx

### What is your role related to the dataset
Data onramp entity that provides data onboarding services to multiple clients

### Data Owner Country/Region
United States

### Data Owner Industry
Other

### Website
[https://telnyx.com/](https://telnyx.com/)

### Social Media
[at]telnyx (Twitter)

### Total amount of DataCap being requested
15 PiB

### Expected size of single dataset (one copy)
10 TiB

### Number of replicas to store
3

### Weekly allocation of DataCap requested
500 TiB

### On-chain address for first allocation
f1jqk7xok5kautet2knhwlg74jvcfbrqlj47kbp2i

### Data Type of Application
Private Commercial/Enterprise

### Custom multisig
- [x] Use Custom Multisig

### Identifier
efil

### Share a brief history of your project and organization
data preparer with a BD pipeline/SOC2/encrypted storage and transfer product.

### Is this project associated with other projects/ecosystem stakeholders?
Yes

### If answered yes, what are the other projects/ecosystem stakeholders
@dcasem, some SPs who are our partner

### Describe the data being stored onto Filecoin
whatever our customers pay us to upload, prepared and encrypted.

### Where was the data currently stored in this dataset sourced from
Other

### If you answered "Other" in the previous question, enter the details here
However our customers are currently storing it.

### If you are a data preparer, what is your location (City and Country)
n/a

### If you are a data preparer, how will the data be prepared? Please include tooling used and technical details?
n/a

### If you are not preparing the data, who will prepare the data?  (Provide name and business)
We give our customers software to prepare it themselves.

### Has this dataset been stored on the Filecoin network before? If so, please explain and make the case why you would like to store this dataset again to the network. Provide details on preparation and/or SP distribution.
n/a

### Please share a sample of the data
No

### Confirm that this is a public dataset that can be retrieved by anyone on the Network
No

### If you chose not to confirm, what was the reason
Private customer data.

### What is the expected retrieval frequency for this data
Sporadic

### For how long do you plan to keep this dataset stored on Filecoin
2 to 3 years

### In which geographies do you plan on making storage deals
North America, Australia (continent), Europe, Greater China, Asia other than Greater China

### How will you be distributing your data to storage providers
Others

### How do you plan to choose SP
Partners

### If you answered "Others" in the previous question, what is the tool or platform you plan to use
n/a

### If you already have a list of storage providers to work with, fill out their names and provider IDs below
n/a

### How do you plan to make deals to your storage providers
Others/custom tool

### If you answered "Others/custom tool" in the previous question, enter the details here
We have a custom algorithm to determine proper combinations of SPs to get a given quality of service and fit compliance requirements.

### Can you confirm that you will follow the Fil+ guideline
Yes

_Application created via [filplus.storage](https://filplus.storage)_

**Comment by herrehesse** [comment]
Tom your work for Telnyx now?

**Comment by Tom-OriginStorage** [comment]
I'm busy with other things recently, I will reply as soon as possible

**Comment by herrehesse** [comment]
@Tom-OriginStorage scammer.

**Comment by Tom-OriginStorage** [comment]
![img_v2_088fedf1-18e8-4d8e-a999-27fe5f6090dh](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/103015469/67551105-da46-45fe-bc46-1758b4a2f442)

@kevzak

**Comment by Tom-OriginStorage** [comment]
No matter what you fill in, it will not pass the verification

**Comment by Tom-OriginStorage** [comment]
No matter what you fill in, it will not pass the verification

**Comment by kevzak** [comment]
ok I removed that question. Try again @Tom-OriginStorage

**Comment by Tom-OriginStorage** [comment]
> Hello - because this is larger than 15PiB DataCap request @Tom-OriginStorage please follow E-Fil plus guidelines here: https://efilplus.super.site/

Completed, forgot to reply, sorry

**Comment by Tom-OriginStorage** [comment]
![img_v3_0250_20b714fe-4553-4f6b-b285-fb7c3965419h](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/103015469/093ea978-246e-4f38-ac22-9d321715941e)

**Comment by Tom-OriginStorage** [comment]
@kevzak  Do you have any other questions？

**Comment by kevzak** [comment]
Lee and Kenneth emails bounced. no response from others yet

**Comment by Tom-OriginStorage** [comment]
@kevzak 
Thank you for your reply. I will confirm the information immediately

**Comment by Tom-OriginStorage** [comment]
f02838518	akcd4040 [Jordan@bitwind.com](mailto:Jordan@bitwind.com) bitwind Russia 
f02832475	Lee [karl@hs88.kr](mailto:karl@hs88.kr) HS88 Thailand
f02859053	miaozi [Cordarell@chainup.com](mailto:Cordarell@chainup.com) chainup USA
f02830321	OriginStorage [Jenuel@originstorage.com](mailto:Jenuel@originstorage.com) OriginStorage Vietnam
f02837226	Jerry [fuqiancheng@kinghash.com](mailto:fuqiancheng@kinghash.com) kinghash Britain

**Comment by Tom-OriginStorage** [comment]
@Sunnyiscoming  Due to a long period of time, we have obtained the information of SP again. Below is the updated SP information, please refer to it

**Comment by Tom-OriginStorage** [comment]
@Sunnyiscoming Due to a long period of time, we have obtained the information of SP again. Below is the updated SP information, please refer to it

**Comment by Filplus-govteam** [comment]
Hi @Tom-OriginStorage emailing SPs was not working. We updated the process to allow you to collect information and send to us for review. Please provide proof of location of SPs (business license or proof of address) and email to filplus.govteam@gmail.com.

**Comment by Tom-OriginStorage** [comment]
@Filplus-govteam 
Please take a good look at this application. It has been going through such a long period of time, and Originsrotage is currently a very powerful mining company that has provided all the information it can provide. Why is LDN's approval so slow? You can count the packaging quality and usage rate of LDN under the originstorage account. I have applied for nearly 100P DC in total, and the packaging quality and usage rate are very high,

**Comment by Filplus-govteam** [comment]
Hello - 

This is an E-Fil+ application. Because the data is private/encrypted, information about the client and SPs involved needs to be provided upfront. That includes:
- KYC
- KYB
- providing proof of distributed SP entity and location information. 

All three of these key checks are still outstanding. Let me know if you have any questions and please refer to EFil guidelines: https://efilplus.super.site/

**Comment by Tom-OriginStorage** [comment]
keep  open

**Comment by Tom-OriginStorage** [comment]
> https://efilplus.super.site/

@Filplus-govteam  I completed it on November 8th, 2023

**Comment by Tom-OriginStorage** [comment]
Please approve it

**Comment by kevzak** [comment]
Hi @Tom-OriginStorage - let me see if I can help here. You completed what exactly?  Can you point me to the information?

KYB is through https://efilplus.synaps.me/signup - that has not been completed. 
KYC is through filplus.storage. Go to login, KYC. That also has not been completed. A 'KYC verified' label will appear on your application.
