### ISSUE TITLE
[DataCap Application] <Wenming> - <Video>

### ISSUE THREAD

**Issue by WenmingTechnology** [filecoin-project/filecoin-plus-large-datasets#2218]
### Data Owner Name

Shenzhen Wenming Technology Co., Ltd

### What is your role related to the dataset

Dataset Owner

### Data Owner Country/Region

China

### Data Owner Industry

Information, Media & Telecommunications

### Website

www.imxpw.com

### Social Media

```text
www.imxpw.com
```

### Total amount of DataCap being requested

5PiB

### Expected size of single dataset (one copy)

500T

### Number of replicas to store

10

### Weekly allocation of DataCap requested

500TiB

### On-chain address for first allocation

f1zmm6fcz4mmyedccsrp3qfshwh5qcuwdp3ocwqla

### Data Type of Application

Public, Open Commercial/Enterprise

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Wenming Technology is a young team that gathers outstanding talents from various majors. Focusing on the visual field for more than 10 years, he has excellent creativity, imagination, and rich experience, and has created many influential works in the industry. We adhere to the concept of meeting customer requirements and exceeding customer expectations. Our works have won repeated praise and awards, which makes us more determined to explore and pursue on the visual road, never stop moving forward, and are determined to become the most customer-satisfied original 3D vision in the industry. supplier.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
Company videos, video materials, video highlights, finished videos, some video files abandoned by customers, etc.
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### If you are a data preparer. What is your location (Country/Region)

China

### If you are a data preparer, how will the data be prepared? Please include tooling used and technical details?

```text
Yes, I am a data preparer and this is my first time applying
```

### Has this dataset been stored on the Filecoin network before? If so, please explain and make the case why you would like to store this dataset again to the network. Provide details on preparation and/or SP distribution.

```text
Does not yet store on Filecoin network
```

### Please share a sample of the data

```text
https://www.aliyundrive.com/s/6iXMhx2GsiU
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Monthly

### For how long do you plan to keep this dataset stored on Filecoin

More than 3 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China

### How will you be distributing your data to storage providers

HTTP or FTP server, Shipping hard drives

### How do you plan to choose storage providers

Slack

### How do you plan to make deals to your storage providers

Boost client, Lotus client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by herrehesse** [comment]
Throwaway account asking for 5 PiB. Again. Do not engage please.

**Comment by WenmingTechnology** [comment]
Hello, who are you? Why can't I participate? Isn’t this a community that everyone can join? @herrehesse

**Comment by Sunnyiscoming** [comment]
- Have you prepared enough token for sector pledge?
- How will the data be prepared? Please include tooling used and technical details
- If you are not preparing the data, who will prepare the data?  (Name and Business)
- Best practice for storing large datasets includes ideally, storing it in 3 or more regions, with 4 or more storage provider operators or owners.You should list Miner ID, Business Entity, Location of sps you will cooperate with.
- Per the https://github.com/filecoin-project/notary-governance/issues/922 for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

**Comment by WenmingTechnology** [comment]
@Sunnyiscoming  Thank you, I will reply to your question as soon as possible.

**Comment by WenmingTechnology** [comment]
Yes, we have prepared tokens.
The data is accumulated through our work, mainly stored using hard drives and some online tools.
Our own prepared data.
SP information has been submitted through the Fill+registration form.
![20230927174437](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/145652053/5a19009b-2cf3-4452-99b9-0bf74e3c5a0d)

@Sunnyiscoming Please confirm, thank you

**Comment by herrehesse** [comment]
also please add the contact information of the SP entities you are working with to store copies of the data.

**Comment by WenmingTechnology** [comment]
@herrehesse Fill+registration form has been submitted

**Comment by Sunnyiscoming** [comment]
You only submit 3 sps in the form. Can you list sps here?
Best practice for storing large datasets includes ideally, storing it in 3 or more regions, with 4 or more storage provider operators or owners.You should list Miner ID, Business Entity, Location of sps you will cooperate with.

**Comment by rainsummer1088** [comment]
@Sunnyiscoming 
f02274508   HK
f02127382   Australia
f02040772   United Kingdom

**Comment by WenmingTechnology** [comment]
f02274508   HK
f02127382   Australia
f02040772   UK
@Sunnyiscoming @herrehesse

**Comment by herrehesse** [comment]
Business names and contact information, we also need 4+ SP not 3.

**Comment by WenmingTechnology** [comment]
@herrehesse Okay, thank you, I'll confirm it as soon as possible

**Comment by WenmingTechnology** [comment]
f02274508   HK   H&W     zcli@vip.qq.com
f02127382   AU   IndeCom   kingkabs@yahoo.com
f02040772   UK   HB   ken00happy@outlook.com
f02320270   US   R1   Jimmy0352@hotmail.com
@herrehesse @Sunnyiscoming  Please confirm, thanks！

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 5PiB

**Expected weekly DataCap usage rate**
> 500TiB

**Client address**
>f1zmm6fcz4mmyedccsrp3qfshwh5qcuwdp3ocwqla

**Comment by WenmingTechnology** [comment]
@Sunnyiscoming Thank you very much, I will deal with the kyc problem as soon as possible

**Comment by WenmingTechnology** [comment]
Hold on

**Comment by kevzak** [comment]
closing until 4 SP entities and KYC provided

**Comment by WenmingTechnology** [comment]
f02274508 HK H&W [zcli@vip.qq.com](mailto:zcli@vip.qq.com)
f02127382 AU IndeCom [kingkabs@yahoo.com](mailto:kingkabs@yahoo.com)
f02040772 UK HB [ken00happy@outlook.com](mailto:ken00happy@outlook.com)
f02320270 US R1 [Jimmy0352@hotmail.com](mailto:Jimmy0352@hotmail.com)

![20231110175333](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/145652053/71db1749-5cec-4c85-a429-35d278d789bb)
@kevzak Hello, can you help me see how it works?

**Comment by WenmingTechnology** [comment]
@kevzak 
Can you open it for me?

**Comment by Filplus-govteam** [comment]
@WenmingTechnology please provide proof of SP entity and location distribution. You can collect and send any information to filplus.govteam@gmail.com

**Comment by WenmingTechnology** [comment]
Is there no one to help with the operation? Is there still no staff left? I haven't received a reply yet, please reply to me. Thank you!@kevzak @Kevin-FF-USA @raghavrmadya @Sunnyiscoming

**Comment by psufootball73** [comment]
@WenmingTechnology the LDN pathway has been phased out, there is no new DataCap available. 

You will need to select a different allocator and apply
