### ISSUE TITLE
[DataCap Application] Coupled Model Intercomparison Project 6

### ISSUE THREAD

**Issue by LUGalina** [filecoin-project/filecoin-plus-large-datasets#2219]
### Data Owner Name

Pangeo Community

### What is your role related to the dataset

Data Preparer

### Data Owner Country/Region

United States

### Data Owner Industry

Life Science / Healthcare

### Website

https://wcrp-cmip.org/cmip-phase-6-cmip6/

### Social Media

```text
https://pangeo-data.github.io/pangeo-cmip6-cloud/
```

### Total amount of DataCap being requested

15PiB

### Expected size of single dataset (one copy)

1730TiB

### Number of replicas to store

8

### Weekly allocation of DataCap requested

10TiB

### On-chain address for first allocation

f1l66uxwsnh6wp2k5uzkriccr23wkxffwfkxjxj4i

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
CMIP began in 1995 under the auspices of the Working Group on Coupled Modelling (WGCM). The first set of common experiments involved comparing the model response to an idealized forcing – a constant rate of increase which was accomplished using a CO2 increase of 1% per year compounded.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
Zarr formatted data and Netcdf formatted data---The sixth phase of global coupled ocean-atmosphere general circulation model ensemble.
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### If you are a data preparer. What is your location (Country/Region)

Hong Kong

### If you are a data preparer, how will the data be prepared? Please include tooling used and technical details?

```text
i have downloaded data, then i will use lotus to make data into car files.
```

### Has this dataset been stored on the Filecoin network before? If so, please explain and make the case why you would like to store this dataset again to the network. Provide details on preparation and/or SP distribution.

```text
Seeems no one finished storing it.
```

### Please share a sample of the data

```text
s3://cmip6-pds/
s3://esgf-world/
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

More than 3 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, Europe

### How will you be distributing your data to storage providers

HTTP or FTP server, Shipping hard drives, Lotus built-in data transfer

### How do you plan to choose storage providers

Slack, Filmine, Big Data Exchange, Partners

### If you already have a list of storage providers to work with, fill out their names and provider IDs below

```text
f01392600 Guiyang  f01808139 HongKong  f0420161 Toronto f02368321 Singapore f02097936 Hangzhou
```

### How do you plan to make deals to your storage providers

Boost client, Lotus client, Singularity

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
- Have you prepared enough token for sector pledge?
- Per the https://github.com/filecoin-project/notary-governance/issues/922 for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

**Comment by LUGalina** [comment]
Hi @Sunnyiscoming , thank you for your attention. Sps have talked to me about it. They will be ready for it.
I've finished Fil+ registration form.

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
>15 PiB

**Expected weekly DataCap usage rate**
> 10TiB

**Client address**
>f1l66uxwsnh6wp2k5uzkriccr23wkxffwfkxjxj4i

**Comment by herrehesse** [comment]
@Sunnyiscoming why are you still allowing huge amounts of fraud on chain? This is unnacceptable.

**Comment by Sunnyiscoming** [comment]
If you think it is not reasonable. Just put relative materials there. @herrehesse

**Comment by LUGalina** [comment]
@kevzak f01392600 Guiyang  f01808139 HongKong  f0420161 Toronto f02368321 Singapore f02097936 Hangzhou

**Comment by LUGalina** [comment]
Due to an written error about Weekly allocation of DataCap requested, we choose to close this application and open a new one. Thanks.
