### ISSUE TITLE
[DataCap Application] PT Nusa Mentari Teknologi

### ISSUE THREAD

**Issue by igc-ai** [filecoin-project/filecoin-plus-large-datasets#2220]
### Data Owner Name
PT Nusa Mentari Teknologi

### What is your role related to the dataset
Dataset Owner

### Data Owner Country/Region
Indonesia

### Data Owner Industry
IT & Technology Services

### Website
[https://www.igc.ai](https://www.igc.ai)

### Social Media
[at]igc_ai (Twitter)

### Total amount of DataCap being requested
5 PiB

### Expected size of single dataset (one copy)
1.5 PiB

### Number of replicas to store
5

### Weekly allocation of DataCap requested
200 TiB

### On-chain address for first allocation
f1kqflbseqshscsrh2kcflmhqlfzru7jxo3ot6x6i

### Data Type of Application
Public, Open Dataset (Research/Non-Profit)

### Custom multisig
- [ ] Use Custom Multisig

### Identifier
n/a

### Share a brief history of your project and organization
IGC.ai is a picture entertainment APP developed by our company. Based on our strong technical capabilities, IGC.ai provides users around the world with a large number of beautiful pictures generated by AI. Everyone can browse freely and share them with their friends at will. They can be downloaded for free. and use without worrying about copyright issues. PT NUSA MENTARI TEKNOLOGI is an innovative technology company that continuously invests and cultivates innovative technical teams. This year, our AI team launched the IGC.ai business based on AIGC technology and relying on our strong computing power.

### Is this project associated with other projects/ecosystem stakeholders?
No

### If answered yes, what are the other projects/ecosystem stakeholders
n/a

### Describe the data being stored onto Filecoin
IPFS technology and Filecoin project are based on decentralized blockchain technology and provide good solutions for content sharing around the world. This philosophy is consistent with the free spirit of our IGC.ai. These contents are generated through the creative clustering technology of our AI team and the exquisite and artistic prompt word optimization technology. Based on our large computing power base, a large amount of high-definition picture content is generated. We own all the copyrights of these data. IGC.ai is a way of sharing, and IPFS is also a good way. We hope to share it with everyone for free through Filecoin.

### Where was the data currently stored in this dataset sourced from
My own storage infra

### If you answered "Other" in the previous question, enter the details here
n/a

### If you are a data preparer, what is your location (City and Country)
n/a

### If you are a data preparer, how will the data be prepared? Please include tooling used and technical details?
n/a

### If you are not preparing the data, who will prepare the data?  (Provide name and business)
Ourselves

### Has this dataset been stored on the Filecoin network before? If so, please explain and make the case why you would like to store this dataset again to the network. Provide details on preparation and/or SP distribution.
n/a

### Please share a sample of the data
Visit website https://www.nusament.com and install IGC.AI App.

### Confirm that this is a public dataset that can be retrieved by anyone on the Network
Yes

### If you chose not to confirm, what was the reason
n/a

### What is the expected retrieval frequency for this data
Yearly

### For how long do you plan to keep this dataset stored on Filecoin
More than 3 years

### In which geographies do you plan on making storage deals
North America, Asia other than Greater China, Europe

### How will you be distributing your data to storage providers
Shipping hard drives

### How do you plan to choose SP
Partners

### If you answered "Others" in the previous question, what is the tool or platform you plan to use
n/a

### If you already have a list of storage providers to work with, fill out their names and provider IDs below
f02804585, James
f02805912, Emily
f02805138, Michael
f02806796, Sarah
f02808432, Kevin

### How do you plan to make deals to your storage providers
Lotus client

### If you answered "Others/custom tool" in the previous question, enter the details here
n/a

### Can you confirm that you will follow the Fil+ guideline
Yes

_Application created via [filplus.storage](https://filplus.storage)_

**Comment by Sunnyiscoming** [comment]
- Could you send an email with certificate to filplus-app-review@fil.org with your official domain in order to confirm your identity? Email name should includes the issue id #2220.
- Have you prepared enough token for sector pledge?
- How will the data be prepared? Please include tooling used and technical details.
- Total amount of DataCap being requested≠Expected size of single dataset (one copy)*Number of replicas to store
5 PiB≠500 TiB*5 Please explain about it. Can you provide more evidence to show you have 500 TB data already?
- Best practice for storing large datasets includes ideally, storing it in 3 or more regions, with 4 or more storage provider operators or owners.You should list Miner ID, Business Entity, Location of sps you will cooperate with.
- Per the https://github.com/filecoin-project/notary-governance/issues/922 for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

**Comment by herrehesse** [comment]
You are gotta be kidding me right?

f02804585, James
f02805912, Emily
f02805138, Michael
f02806796, Sarah
f02808432, Kevin

Please remove your LDN.

**Comment by Sunnyiscoming** [comment]
Any update here?

**Comment by igc-ai** [comment]
> You are gotta be kidding me right?
> 
> f02804585, James f02805912, Emily f02805138, Michael f02806796, Sarah f02808432, Kevin
> 
> Please remove your LDN.

Hello friend, 
Who are you?

**Comment by igc-ai** [comment]
Hello @Sunnyiscoming,

Q: Have you prepared enough token for sector pledge?
A: Yes. The SPs have committed that enough tokens are available.

Q: How will the data be prepared? Please include tooling used and technical details.
A: Step 1: Generate a car file
lotus client generate-car /input_path /output_path.car

Step 2: Calculate the CID of the car file, get a <DataCID>
lotus client commP /output_path.car 

Step 3: Make a deal, get a <DealCID>
lotus client deal --manual-piece-cid=<DataCID> --manual-piece-size=<DataSize> <DataCID> <Miner> <Price> <Duration>

Step 4: Store data(DealCID, output_path.car) to hard drives and express hard drives to SPs

Q: Total amount of DataCap being requested≠Expected size of single dataset (one copy)Number of replicas to store
5 PiB≠500 TiB5 Please explain about it. Can you provide more evidence to show you have 500 TB data already?
A: Sorry, I may have misunderstood what a single dataset means. In fact, we have 3 storage clusters to store 3 datasets, each dataset is about 500TiB. The amount of data continues to grow every day.

The Fil+ Registration Form submitted.

**Comment by Sunnyiscoming** [comment]
If you will store 3 copies for 500 TB data. You should change the value of Total amount of DataCap being requested into 1.5 PB. LDN is set for existed dataset, not for data being generated.
Are all the sp's you work with individuals?

**Comment by igc-ai** [comment]
The data has been changed to 1.5PiB.

Yes, They are all individuals.

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 5PiB

**Expected weekly DataCap usage rate**
> 200TiB

**Client address**
>f1kqflbseqshscsrh2kcflmhqlfzru7jxo3ot6x6i

**Comment by igc-ai** [comment]
Can any notaries sign for us?

**Comment by zcfil** [comment]
How to prove you have a copy of 1.5P

**Comment by igc-ai** [comment]
Thank you for your response. Here is a screenshot of the data storage information provided by our operations engineers, which shows the sizes of our three storage datasets.

**Comment by igc-ai** [comment]
> How to prove you have a copy of 1.5P

Thank you for your response. Here is a screenshot of the data storage information provided by our operations engineers, which shows the sizes of our three storage datasets.
<img width="381" alt="1" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/135959795/9220b7ed-2b17-4751-a042-36d73d2d985d">
<img width="345" alt="2" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/135959795/9569eddc-41e6-420d-bc52-6d76e7269a17">
<img width="341" alt="3" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/135959795/8b1f52b7-6fe2-4baa-a4a7-dd1472677a2e">

**Comment by zcfil** [comment]
> > How to prove you have a copy of 1.5P
> 
> Thank you for your response. Here is a screenshot of the data storage information provided by our operations engineers, which shows the sizes of our three storage datasets. <img alt="1" width="381" src="https://user-images.githubusercontent.com/135959795/273617344-9220b7ed-2b17-4751-a042-36d73d2d985d.png"> <img alt="2" width="345" src="https://user-images.githubusercontent.com/135959795/273617885-9569eddc-41e6-420d-bc52-6d76e7269a17.png"> <img alt="3" width="341" src="https://user-images.githubusercontent.com/135959795/273618237-8b1f52b7-6fe2-4baa-a4a7-dd1472677a2e.png">

The screenshot is not rigorous enough, can we see what data is stored in it?Can you show it with more screenshots?

**Comment by zcfil** [comment]
Looks good, willing to offer support in the first round

**Comment by zcfil** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebbjhqksbrba4avtq3aox4lu6jdxjvo3dvfm2z4xqervhubmojbzm 
#### Address 
> f1kqflbseqshscsrh2kcflmhqlfzru7jxo3ot6x6i
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1cjzbiy5xd4ehera4wmbz63pd5ku4oo7g52cldga
#### Id
> 48a0535c-f894-4037-9320-949efb70dbd2
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebbjhqksbrba4avtq3aox4lu6jdxjvo3dvfm2z4xqervhubmojbzm

**Comment by PicasMix** [comment]
@zcfil Thank you very much.

**Comment by igc-ai** [comment]
@zcfil Thank you very much.

@kernelogic @sxxfuture-official @dannyob @junyaoren @BlockMakeronline @Joss-Hua 
Hi all, could you sign it for me？

**Comment by ipfscn** [comment]
Thank you for contacting me, I will keep an eye on you

**Comment by Joss-Hua** [comment]
Could you finish the KYC in https://filplus.storage?

**Comment by igc-ai** [comment]
> Could you finish the KYC in https://filplus.storage?

I'm sorry, the relevant personnel have delayed the KYC due to vacation, and we are currently processing KYC.

**Comment by kevzak** [comment]
SP 1	f02804585	       Seattle, US	No	
SP 2	f02805912		London, UK	No	
SP 3	f02805138		Frankfurt, Germany	No	
SP 4	f02806796		Tokyo, Japan	No	
SP 5	f02808432               Hanoi, Vietnam	

no SP entity provided. Please update via registration form

**Comment by igc-ai** [comment]
> SP 1 f02804585 Seattle, US No SP 2 f02805912 London, UK No SP 3 f02805138 Frankfurt, Germany No SP 4 f02806796 Tokyo, Japan No SP 5 f02808432 Hanoi, Vietnam
> 
> no SP entity provided. Please update via registration form

Hi @kevzak ,

All SP information has been submitted in the previous form (as shown in the figure below). Do we need to resubmit it again?
![20231030174550250](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/135959795/45305930-a3b2-4cbf-a23e-2b4dd7744b28)

**Comment by kevzak** [comment]
SPs were sent emails to confirm business and location

**Comment by igc-ai** [comment]
> SPs were sent emails to confirm business and location

@kevzak I have informed SPs to check the email.

**Comment by igc-ai** [comment]
> Could you finish the KYC in https://filplus.storage?

Hi @Joss-Hua ,

Both of our colleagues are Indonesian and have passed the KYC certification through the toggle multiple times, but the results are all unsuccessful. I don't know why, is there a bug in the toggle? Is there any other way to complete KYC?

**Comment by igc-ai** [comment]
> SPs were sent emails to confirm business and location

Hi @kevzak ,

All SPs have already provided feedback and have replied to your email. Can you help us pass the review? Please let me known if you have any questions.

**Comment by kevzak** [comment]
confirmed i have received emails. cc @Sunnyiscoming

**Comment by igc-ai** [comment]
> confirmed i have received emails. cc @Sunnyiscoming

Thank you @kevzak .

**Comment by igc-ai** [comment]
> Could you finish the KYC in https://filplus.storage?

We will continue to complete KYC, but the toggle doesn't work for us and we are looking for a feasible way. Could you let us pass the first round? SPs are ready. @Joss-Hua

**Comment by kevzak** [comment]
KYC has been confirmed via ID review. @igc-ai . FYI @Joss-Hua

**Comment by kevzak** [comment]
Also, SP email verification confirmed.

**Comment by Joss-Hua** [comment]
> KYC has been confirmed via ID review. @igc-ai . FYI @Joss-Hua

got it

**Comment by Joss-Hua** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaksfymwjk5ogy67sfp64zbvwtmom3d6wzd5skdbw4hev3xru53jm 
#### Address 
> f1kqflbseqshscsrh2kcflmhqlfzru7jxo3ot6x6i
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1tfg54zzscugttejv336vivknmsnzzmyudp3t7wi
#### Id
> 48a0535c-f894-4037-9320-949efb70dbd2
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaksfymwjk5ogy67sfp64zbvwtmom3d6wzd5skdbw4hev3xru53jm

**Comment by igc-ai** [comment]
Thank you all.

**Comment by herrehesse** [comment]
Are we allowing this SERIOUSLY?

SP 1 f02804585 Seattle, US 
SP 2 f02805912 London, UK 
SP 3 f02805138 Frankfurt, Germany 
SP 4 f02806796 Tokyo, Japan 
SP 5 f02808432 Hanoi, Vietnam

@kevzak Please tell me this cheating abusive entity is not granted datacap to FULLY self deal right?
@Joss-Hua Can you remove your signature please?

**Comment by igc-ai** [comment]
Who are you Bro? @herrehesse

**Comment by herrehesse** [comment]
@Joss-Hua why are you not responding on all of my messages, including PM.

**Comment by igc-ai** [comment]
@herrehesse

I noticed that you have doubts about all LDNs and I don't know what your personal purpose is. Out of politeness, this is the last time I will reply to your comment.

We have submitted detailed and truthful information, and have passed KYC. We will strictly abide by the rules of FIL+. You have no right to demand that the notary close this LDN, pay attention to your words and actions.

**Comment by herrehesse** [comment]
@igc-ai I do not need any communication with you to expose that you are actively abusing this ecosystem.

**Comment by Filplus-govteam** [comment]
SPs taking deals
f02804585new | Tukwila, Washington, USCogent Communications | 16.81 TiB | 20.72% | 16.81 TiB | 0.00%
f02805912new | London, England, GBCogent Communications | 16.31 TiB | 20.11% | 16.31 TiB | 0.00%
f02805138new | Frankfurt am Main, Hesse, DECogent Communications | 14.75 TiB | 18.18% | 14.75 TiB | 0.00%
f02806796new | Tokyo, Tokyo, JPNTT America, Inc. | 17.06 TiB | 21.03% | 17.06 TiB | 0.00%
f02808432new | Hanoi, Hanoi, VNViettel Group | 16.19 TiB | 19.95% | 16.19 TiB | 0.00%

**Comment by herrehesse** [comment]
<img width="1043" alt="Screenshot 2023-11-20 at 20 23 10" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/70132857/772f7828-3cf3-4418-9d49-7168c10bdab4">

Calling out fake distribution under VPN - All the same miner - Prove to me that the miners are where they are because I am 99.99% certain they are not.

@igc-ai We've tried several retrievals and this is so slow, cant explain in any other way than the setup is 100% VPN to hide the fact that the entity is the same. The ID's are corresponding and the names are fake. Also no businesses named or contact info. Clear signs of abusive behaviour.

**Comment by herrehesse** [comment]
<img width="1039" alt="Screenshot 2023-11-20 at 20 25 40" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/70132857/491c5b22-529b-49b3-991a-45b9b1c31084">

I will try to find source wallets for the addresses, most likely they are funded by the same entity.
@Filplus-govteam Can you ask this client to show proof of location & business, and if not provided close? Lets run 922 again and limit abuse on this platform.

**Comment by igc-ai** [comment]
Hi Notaries,
Can you support us and sign?

@IreneYoung 
@DirectionTechnology
@AthSmith 
@flyworker 
@Fenbushi-Filecoin
@TinySwitcher

**Comment by igc-ai** [comment]
Is there a notary here?

**Comment by Sunnyiscoming** [comment]
SP List provided:
[{"providerID": "f02804585",  "City": "Seattle", "Country": "US", "SPOrg","XYZ"},
{"providerID": "f02805912",  "City": "London", "Country": "UK","SPOrg","XYZ"},
{"providerID": "f02805138",  "City": "Frankfurt", "Country": "Germany","SPOrg","XYZ"},
{"providerID": "f02806796",  "City": "Tokyo", "Country": "Japan","SPOrg","XYZ"},
{"providerID": "f02808432",  "City": "Hanoi", "Country": "Vietnam","SPOrg","XYZ"},]

**Comment by igc-ai** [comment]
@zcfil @Joss-Hua 
Could you support us and sign again?

**Comment by igc-ai** [comment]
＠[stcouldlisa](https://github.com/stcouldlisa)　＠[1ane-1](https://github.com/1ane-1)

Could you support us and sign?

**Comment by igc-ai** [comment]
Any notaries here? Really need your support, thank you.

**Comment by igc-ai** [comment]
@Filplus-govteam @Sunnyiscoming @kevzak 
Could you reopen it for us?

**Comment by igc-ai** [comment]
@Filplus-govteam @Sunnyiscoming @kevzak
Are you there?

**Comment by Filplus-govteam** [comment]
checker:manualTrigger

**Comment by igc-ai** [comment]
checker:manualTrigger

**Comment by igc-ai** [comment]
checker:manualTrigger

**Comment by PicasMix** [comment]
checker:manualTrigger

**Comment by PicasMix** [comment]
checker:manualTrigger

**Comment by PicasMix** [comment]
@Filplus-govteam @Sunnyiscoming @kevzak
Could you reopen it for us?

**Comment by igc-ai** [comment]
checker:manualTrigger

**Comment by igc-ai** [comment]
@Filplus-govteam @Sunnyiscoming @kevzak
Could you reopen it for us?

**Comment by igc-ai** [comment]
@Filplus-govteam @Sunnyiscoming @kevzak
Are you there?

**Comment by kevzak** [comment]
reminder - you need to keep it open every 14 days @igc-ai and you won't have to rely on anyone else.

**Comment by igc-ai** [comment]
> reminder - you need to keep it open every 14 days @igc-ai and you won't have to rely on anyone else.

OK. Thanks.

**Comment by igc-ai** [comment]
checker:manualTrigger

**Comment by igc-ai** [comment]
checker:manualTrigger

**Comment by igc-ai** [comment]
checker:manualTrigger

**Comment by igc-ai** [comment]
checker:manualTrigger

**Comment by igc-ai** [comment]
checker:manualTrigger

**Comment by igc-ai** [comment]
checker:manualTrigger

**Comment by igc-ai** [comment]
checker:manualTrigger

**Comment by igc-ai** [comment]
checker:manualTrigger
