### ISSUE TITLE
[DataCap Application] <Youle> - <Youle>

### ISSUE THREAD

**Issue by Chanel8888** [filecoin-project/filecoin-plus-large-datasets#2221]
### Data Owner Name

Youle Pte Ltd

### What is your role related to the dataset

Dataset Owner

### Data Owner Country/Region

Singapore

### Data Owner Industry

Education & Training

### Website

https://www.youle.com.sg/

### Social Media

```text
Facebook - Youle Mandarin
```

### Total amount of DataCap being requested

10PiB

### Expected size of single dataset (one copy)

580TiB

### Number of replicas to store

10

### Weekly allocation of DataCap requested

1PiB

### On-chain address for first allocation

f17dubvo2eydgukbygvv3tf4zrftaboxy7y7vawsa

### Data Type of Application

Public, Open Commercial/Enterprise

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
YOULE IS FOUNDED BY A TEAM OF EDUCATORS AND PARENTS.

We share the hopes and aspirations of giving our young ones the best chance for future success by nurturing in them a love for learning, a growth mindset and confidence to navigate this ever-changing and increasingly bicultural world.

We believe this is best done when children are primed for learning in their early years. With our diverse range of expertise in language milestones development, whole-brain training and early childhood education, our mission is to help stimulate our students’ interests in Mandarin from early childhood and endow them with the best foundation to bring their Mandarin learning to greater heights.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
Education and training videos, child development videos, etc.
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### If you are a data preparer. What is your location (Country/Region)

None

### Please share a sample of the data

```text
https://drive.google.com/drive/folders/10rflL3IfnMxCKwRGvPFtsftIlLkiUjfK?usp=share_link
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Sporadic

### For how long do you plan to keep this dataset stored on Filecoin

1.5 to 2 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, Europe

### How will you be distributing your data to storage providers

HTTP or FTP server, Shipping hard drives

### How do you plan to choose storage providers

Slack, Partners

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by herrehesse** [comment]
New account 10PiB - Can we close?

**Comment by Sunnyiscoming** [comment]
- Have you prepared enough token for sector pledge?
- How will the data be prepared? Please include tooling used and technical details
- If you are not preparing the data, who will prepare the data?  (Name and Business)
- Best practice for storing large datasets includes ideally, storing it in 3 or more regions, with 4 or more storage provider operators or owners.You should list Miner ID, Business Entity, Location of sps you will cooperate with.
- Per the https://github.com/filecoin-project/notary-governance/issues/922 for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

**Comment by Chanel8888** [comment]
1. Yes, SPs have prepared 80% of the filcoins.
2. data is mainly prepared with boost or lotus tools.
3. communicating with the following SPs:
f02368751 USA
f02812314 USA
f02814775 Malaysia
f02122388 China
4. It has been filled out according to the requirements, please check it.

**Comment by 1ane-1** [comment]
Could you send an email to filplus-app-review@fil.org with your official domain in order to confirm your identity? And share the screenshot here? Thanks a lot !

**Comment by Chuangshi1** [comment]
Support for the first round, hope you can have a good report in the next round.

**Comment by Chuangshi1** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec462aciuvdnsarba7rvxwhyc7yngvg5ytqb456jvpjyy76fpjx5i 
#### Address 
> f17dubvo2eydgukbygvv3tf4zrftaboxy7y7vawsa
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f1mdk7s2vntzm6hu35yuo6vjubtrpfnb2awhgvrri
#### Id
> d3d27245-c78f-43f8-a9d2-c6a921ad9353
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec462aciuvdnsarba7rvxwhyc7yngvg5ytqb456jvpjyy76fpjx5i

**Comment by NDLABS-Leo** [comment]
Support for the first round, hope you can have a good report in the next round.

**Comment by NDLABS-Leo** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedknssbta3qesuczrlwagibfjaeh2zukujsn6ox34hkebvvzhfvge 
#### Address 
> f17dubvo2eydgukbygvv3tf4zrftaboxy7y7vawsa
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f1yayfsv6whu3rheviucvventj3y6t542xfpb47ei
#### Id
> d3d27245-c78f-43f8-a9d2-c6a921ad9353
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedknssbta3qesuczrlwagibfjaeh2zukujsn6ox34hkebvvzhfvge

**Comment by herrehesse** [comment]
Zero reputation, asking for 10PiB, gets approved, no SP contact details or business names.

Can we report @NDLABS-Leo & @Sunnyiscoming & @Chuangshi1 right away?

**Comment by Chanel8888** [comment]
Update SP information, we will contact SP according to SP filcoin preparation status：f02814770 Australia、f02368751 USA、f02812307 Singapore、f02122388 China、f02814775 Amsterdam、f02812314 USA、f02815456 New York, USA

**Comment by herrehesse** [comment]
@Chanel8888 same response, its all fake and under VPN. Please share business names and contact information.

**Comment by herrehesse** [comment]
checker:manualTrigger

**Comment by herrehesse** [comment]
@Sunnyiscoming why doesnt this trigger?

**Comment by laurarenpanda** [comment]
checker:manualTrigger

**Comment by Chanel8888** [comment]
checker:manualTrigger

**Comment by Bitrise0111** [comment]
This Client contacted me through slack. We've checked this report and it looked fine. Therefore we'd like to give a support and we'll continue to check this.

**Comment by Bitrise0111** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedidio2gcebg7mclzixbp2e5kimbxtlh62y7lmwe6i6foywmbnfv6 
#### Address 
> f17dubvo2eydgukbygvv3tf4zrftaboxy7y7vawsa
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f1nknj7ayq4o43czrtdoauggtwl43fbqatmqis3yy
#### Id
> a3e3d3ff-577b-4d5d-81d6-0c864006eb52
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedidio2gcebg7mclzixbp2e5kimbxtlh62y7lmwe6i6foywmbnfv6

**Comment by sxxfuture-official** [comment]
looks good.

**Comment by sxxfuture-official** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedkrj6vkgfjhsma7ljalopddrggxtymkbviqdrkqzqf3tmcfsug2y 
#### Address 
> f17dubvo2eydgukbygvv3tf4zrftaboxy7y7vawsa
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f1foiomqlmoshpuxm6aie4xysffqezkjnokgwcecq
#### Id
> a3e3d3ff-577b-4d5d-81d6-0c864006eb52
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedkrj6vkgfjhsma7ljalopddrggxtymkbviqdrkqzqf3tmcfsug2y

**Comment by herrehesse** [comment]
More abuse! REPORTED.
@Sunnyiscoming @simonkim0515 @Kevin-FF-USA @galen-mcandrew @dkkapur Anyone even slightly awake?

Reported the same notaries for fraud.

**Comment by kevzak** [comment]
SPs taking deals

f02812307 | Singapore, Singapore, SGIPTELECOM Global | 127.94 TiB | 25.00% | 127.94 TiB | 0.00%
f02815456new | Piscataway, New Jersey, USThe Constant Company, LLC | 128.00 TiB | 25.01% | 128.00 TiB | 0.00%
f02814775new | Haarlem, North Holland, NLThe Constant Company, LLC | 127.97 TiB | 25.00% | 127.97 TiB | 0.00%
f02814770new | Melbourne, Victoria, AUThe Constant Company, LLC | 127.88 TiB | 24.99% | 127.88 TiB | 0.00%

SPs provided:

SP 1 | f02368751 | Alex Li | / | Alex | USA | no | /
f02814775 | Derek Cui | / | Derek | Malaysia | no | /
f02122388 |  nanhao | China | no | /
f02812314 | Jerry Zhang | / | Jerry Zhang | USA | no | /

SPs do not match, closing

**Comment by herrehesse** [comment]
"we will play by the rules" stop lying.

**Comment by Chanel8888** [comment]
> @kevzak Yes, we did communicate with f02368751, f02814775 , f02122388 and f02812314 at the beginning of the application, but did not work together because of timing issues.
> 
> We update the actual package SPs information: f02812307 Alice Xu f02814775 Derek Cui f02814770 leo f02815456 Xiangyun
> 
> We are also in continuous communication with the following SPs: f02809368 Tom Liu f02812314 Jerry Zhang f02814767 XHS
> 
> Please stay tuned for healthy data reporting, we will play by the rules, thank you!

For the sake of consistency, continue to update information on collaborating SPs:
f02815448 bluesky danacheng2021@gmail.com USA
f02815438 MaiJie nibuil0730@163.com India India

@kevzak can reopen it please？

**Comment by Chanel8888** [comment]
Hi @kevzak  SPs have been waiting for a long time, please help restart the project!Thank you very much！

**Comment by Chanel8888** [comment]
Hi again, @kevzak SPs have been waiting for a long time, please help restart the project!Thank you very much！

**Comment by Chanel8888** [comment]
<img width="870" alt="image" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/143789474/65847141-ee51-499c-b633-e62d92a64621">

@Filplus-govteam We have reconnected with SPs and hope to continue working together to strengthen and expand Fil-Plus. Thank you.

**Comment by Chanel8888** [comment]
@Filplus-govteam @kevzak @Sunnyiscoming Hello, have you received our message and look forward to us continuing to.

**Comment by Chanel8888** [comment]
checker:manualTrigger
