### ISSUE TITLE
[DataCap Application] <Frost> - <Frost>

### ISSUE THREAD

**Issue by kelsey0907** [filecoin-project/filecoin-plus-large-datasets#2222]
### Data Owner Name

Frost & Sullivan (Singapore) Pte Ltd

### What is your role related to the dataset

Data Preparer

### Data Owner Country/Region

Singapore

### Data Owner Industry

Professional Services (Legal, Consulting, Advising)

### Website

https://www.frost.com/

### Social Media

```text
https://www.frost.com/
```

### Total amount of DataCap being requested

8PiB

### Expected size of single dataset (one copy)

600TiB

### Number of replicas to store

10

### Weekly allocation of DataCap requested

1PiB

### On-chain address for first allocation

f1hhsxt2ftbb7f6rvwpih5mzlvfrqvxcgjuhnemki

### Data Type of Application

Public, Open Commercial/Enterprise

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Our History
We are very proud of the history of Frost & Sullivan as it has been a combined effort of many people and clients over many years.  Lore Frost & Dan Sullivan saw the invisible in 1961 over lunch, starting our 60-year journey. In the half-century since its founding, Frost & Sullivan has become a widely recognized leader in the information and growth advisory industry – a Growth Pipeline company.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
Frost & Sullivan is a growth and consulting firm that provide consultancy to help company growth like provide market research data, in-depth process improvements, market product evaluation etc.
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### If you are a data preparer. What is your location (Country/Region)

Singapore

### If you are a data preparer, how will the data be prepared? Please include tooling used and technical details?

```text
mainly via boost or lotus
```

### Has this dataset been stored on the Filecoin network before? If so, please explain and make the case why you would like to store this dataset again to the network. Provide details on preparation and/or SP distribution.

```text
First time storage
```

### Please share a sample of the data

```text
https://drive.google.com/drive/folders/1S4EnuPwNdqURt5XWph0Hcfpz83ISt1Oe?usp=sharing
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Sporadic

### For how long do you plan to keep this dataset stored on Filecoin

1.5 to 2 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, Europe, Australia (continent)

### How will you be distributing your data to storage providers

HTTP or FTP server, Shipping hard drives

### How do you plan to choose storage providers

Slack, Partners

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
- Could you send an email to filplus-app-review@fil.org with your official domain in order to confirm your identity? Email name should includes the issue id #2222.
- I have no access to check data samples https://drive.google.com/drive/folders/1S4EnuPwNdqURt5XWph0Hcfpz83ISt1Oe. Please check it.
- Have you prepared enough token for sector pledge?
- Best practice for storing large datasets includes ideally, storing it in 3 or more regions, with 4 or more storage provider operators or owners.You should list Miner ID, Business Entity, Location of sps you will cooperate with.
- Per the https://github.com/filecoin-project/notary-governance/issues/922 for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

**Comment by kelsey0907** [comment]
1. The e-mail was sent.

2. Please check the link: https://drive.google.com/drive/folders/1S4EnuPwNdqURt5XWph0Hcfpz83ISt1Oe?usp=sharing

3. yes, SPs have prepared enough fil.

4. f02383642 USA
f02809368 Japan
f02812307 Singapore
f02363308 China
f02301 North America CA

5.The form is complete

**Comment by Sunnyiscoming** [comment]
Could you send an email to [filplus-app-review@fil.org](mailto:filplus-app-review@fil.org) with your official domain？
I received an email from a personal email address.

**Comment by kelsey0907** [comment]
<img width="1134" alt="image" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/144329649/5e385c8d-d984-47bc-92c8-095682c83066">
Yes, It's me! Mainly responsible for data preparation, this is my company domain email. Thank you for your time.

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
>8 PiB

**Expected weekly DataCap usage rate**
>1 PiB

**Client address**
>f1hhsxt2ftbb7f6rvwpih5mzlvfrqvxcgjuhnemki

**Comment by Chuangshi1** [comment]
Checked the information and willing to support for the first round. Good luck

**Comment by Chuangshi1** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecka64egjf3mat2qofhjagi6xavfnqd64jscdewu5e5v2ol445os4 
#### Address 
> f1hhsxt2ftbb7f6rvwpih5mzlvfrqvxcgjuhnemki
#### Datacap Allocated
> 409.59TiB
#### Signer Address
> f1mdk7s2vntzm6hu35yuo6vjubtrpfnb2awhgvrri
#### Id
> f8723af3-f54f-44bf-bb2c-5b4195efe841
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecka64egjf3mat2qofhjagi6xavfnqd64jscdewu5e5v2ol445os4

**Comment by Aaron01230** [comment]
Based on the above information, I would like to support this round

**Comment by Aaron01230** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebqnijnj7wpxp4lrbdmf5lb3ylpqtadeb2ksvcoue2jtm73imzkse 
#### Address 
> f1hhsxt2ftbb7f6rvwpih5mzlvfrqvxcgjuhnemki
#### Datacap Allocated
> 409.59TiB
#### Signer Address
> f1xrnysd4gimg64d4l6qi7ulzwwq22c6vfg6lpw3i
#### Id
> f8723af3-f54f-44bf-bb2c-5b4195efe841
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebqnijnj7wpxp4lrbdmf5lb3ylpqtadeb2ksvcoue2jtm73imzkse

**Comment by herrehesse** [comment]
@kelsey0907 where is the SP contact information and business names?

@Aaron01230 & @Chuangshi1 @Sunnyiscoming you are once more involved in abuse.

**Comment by kelsey0907** [comment]
Information is updated and we are in communication with the following SPs:
f02809368 Japan
f02383642 USA
f02363308 China
f02301 North America CA
f02815438 India
f02809368 Japan
f02814767 South Korea
f02812307 Singapore

**Comment by herrehesse** [comment]
@kelsey0907 All faked with VPN, i can not check. Can you show me business names & contact information please?

**Comment by herrehesse** [comment]
checker:manualTrigger

**Comment by herrehesse** [comment]
@Sunnyiscoming why doesnt this trigger?

**Comment by herrehesse** [comment]
checker:manualTrigger

**Comment by kelsey0907** [comment]
checker:manualTrigger

**Comment by psh0691** [comment]
checker:manualTrigger

**Comment by kelsey0907** [comment]
checker:manualTrigger

**Comment by woshidama323** [comment]
LGTM will support

**Comment by MRJAVAZHAO** [comment]
![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/47096545/63f18652-5bd5-4ead-825c-07fbb8f4e28a)
How many sps were involved ?

**Comment by kelsey0907** [comment]
> ![image](https://user-images.githubusercontent.com/47096545/276194086-63f18652-5bd5-4ead-825c-07fbb8f4e28a.png) How many sps were involved ?

Hi, it's 4 SPs.

**Comment by woshidama323** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecxoqezd2miuqwxoc3dqvqzrbjgay3le43wvqfop6lt2kvaquwtwa 
#### Address 
> f1hhsxt2ftbb7f6rvwpih5mzlvfrqvxcgjuhnemki
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f12tk3adljauwnd3hjbigpfxb7b7gdlj63p6afwtq
#### Id
> b84bea24-c16a-4772-9a3f-e81b42aa34a6
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecxoqezd2miuqwxoc3dqvqzrbjgay3le43wvqfop6lt2kvaquwtwa

**Comment by sxxfuture-official** [comment]
with a healty report, will support

**Comment by sxxfuture-official** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecgcxniamjqsmj4gjphr7ud264enaayoo3d5lvumo7c5aiynr7bq6 
#### Address 
> f1hhsxt2ftbb7f6rvwpih5mzlvfrqvxcgjuhnemki
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f1foiomqlmoshpuxm6aie4xysffqezkjnokgwcecq
#### Id
> b84bea24-c16a-4772-9a3f-e81b42aa34a6
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecgcxniamjqsmj4gjphr7ud264enaayoo3d5lvumo7c5aiynr7bq6

**Comment by herrehesse** [comment]
![Screenshot 2023-10-18 at 14 54 14](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/70132857/7dfce7f2-9991-485f-831b-868423490557)

ABUSE ABUSE!

THIS APPLICATION USES VPN TO HIDE AND IS ONE SINGLE ENTITY.

Report notaries: @sxxfuture-official @woshidama323 @Chuangshi1 

@galen-mcandrew @dkkapur @Kevin-FF-USA @simonkim0515 are we watching? Hello?

**Comment by kelsey0907** [comment]
checker:manualTrigger

**Comment by kevzak** [comment]
SPs taking deals

f02809368 | Tokyo, Tokyo, JPIPTELECOM Global | 100.08 TiB | 24.66% | 100.08 TiB | 0.00%
f02814767new | Paripark, Seoul, KRThe Constant Company, LLC | 102.00 TiB | 25.13% | 102.00 TiB | 0.00%
f02815448new | Los Angeles, California, USThe Constant Company, LLC | 101.98 TiB | 25.13% | 101.98 TiB | 0.00%
f02815438new | Mumbai, Maharashtra, INThe Constant Company, LLC | 101.84 TiB | 25.09% | 101.84 TiB | 0.00%

SPs provided:

SP 1 | f02383642 | Alex Li | / | Alex | USA | no | /
f02809368 | Tom Liu | / | Tom | Japan | no | /
f02812307 | Alice Xu | / | Alice | Singapore | no | /
f02363308 | Fly | noahlee90418@gmail.com | Fly | China | no | /
f02301 | Harry | / | Topblocks | North America CA | no

one matching SP, no contact info provided. closing until updated

**Comment by kelsey0907** [comment]
Updated info below and 【will keep looking for more SPs to follow】, the report is reassuringly healthy! @kevzak 

f02809368	Tom Liu	daniel@bowyuan.com
f02814767	XHS	  1504068285@qq.com
f02815448	bluesky	danacheng2021@gmail.com
f02815438	MaiJie	nibuil0730@163.com

**Comment by kelsey0907** [comment]
Hi @kevzak Can we continue? Can you help me reopen it, thanks！

**Comment by kelsey0907** [comment]
@kevzak  The information has been updated, do we need to do anything else?

**Comment by kelsey0907** [comment]
Hi @kevzak Can we continue? Can you help me reopen it, thanks！
