### ISSUE TITLE
[DataCap Application] Public dataset - Encyclopedia of DNA Elements

### ISSUE THREAD

**Issue by Gella1baa** [filecoin-project/filecoin-plus-large-datasets#2223]
### Data Owner Name

ENCODE Data Coordinating Center

### What is your role related to the dataset

Data Preparer

### Data Owner Country/Region

United States

### Data Owner Industry

Life Science / Healthcare

### Website

https://www.encodeproject.org

### Social Media

```text
https://twitter.com/EncodeDCC
```

### Total amount of DataCap being requested

14PiB

### Expected size of single dataset (one copy)

1228.8TiB

### Number of replicas to store

10

### Weekly allocation of DataCap requested

1PiB

### On-chain address for first allocation

f1cjyjcj5puo6vug6x2zmfoou4h7tvwmmxlxgc7ry

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
The Encyclopedia of DNA Elements (ENCODE) Consortium is an international collaboration of research groups funded by the National Human Genome Research Institute (NHGRI). The goal of ENCODE is to build a comprehensive parts list of functional elements in the human genome, including elements that act at the protein and RNA levels, and regulatory elements that control cells and circumstances in which a gene is active.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
Daily Released and archived ENCODE data.
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### If you are a data preparer. What is your location (Country/Region)

Singapore

### If you are a data preparer, how will the data be prepared? Please include tooling used and technical details?

```text
I choose lotus to transform data into car files.
```

### Has this dataset been stored on the Filecoin network before? If so, please explain and make the case why you would like to store this dataset again to the network. Provide details on preparation and/or SP distribution.

```text
This dataset is updating daily. I will follow on this dataset and continue to help store this dataset.
```

### Please share a sample of the data

```text
https://registry.opendata.aws/encode-project/
s3://encode-public/
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Sporadic

### For how long do you plan to keep this dataset stored on Filecoin

Permanently

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, South America, Europe

### How will you be distributing your data to storage providers

HTTP or FTP server, Shipping hard drives, Lotus built-in data transfer

### How do you plan to choose storage providers

Slack, Big Data Exchange, Partners

### If you already have a list of storage providers to work with, fill out their names and provider IDs below

```text
f01808139 HongKong/ f01820802 Dongguan/ f0420161 Toronto/ f02368321 Singapore/ f0671982 HongKong
```

### How do you plan to make deals to your storage providers

Boost client, Lotus client, Singularity

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
- Have you prepared enough token for sector pledge?
- Per the https://github.com/filecoin-project/notary-governance/issues/922 for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

**Comment by Sunnyiscoming** [comment]
Any update here?

**Comment by Gella1baa** [comment]
Hello @Sunnyiscoming ,Yes! SPs will prepared enough token to cooperate with us. We'll try to make sure everything's ready.
I have completed the form, please check it. Thank you very much!!

**Comment by herrehesse** [comment]
First issue ever, 14PiB, new account, no reputation. We can not allow this any longer.

**Comment by Gella1baa** [comment]
I'm suspicious about it. Is there any rules that there's such limitation for applicant? @dkkapur @galen-mcandrew @raghavrmadya @Kevin-FF-USA @kevzak 

> First issue ever, 14PiB, new account, no reputation. We can not allow this any longer.

**Comment by Gella1baa** [comment]
@Sunnyiscoming The reason why some information haven't provided to the form is SPs do not provide to me or they don't have. I will resubmit the form to explain it.

**Comment by herrehesse** [comment]
SPs do not provide to me or they don't have = no datacap then.

**Comment by Gella1baa** [comment]
> SPs do not provide to me or they don't have = no datacap then.

Unreasonable

**Comment by Gella1baa** [comment]
Yes

**Comment by Filplus-govteam** [comment]
Hello, @Gella1baa  per the https://github.com/filecoin-project/notary-governance/issues/922 for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

This information will be reviewed by Fil+ Governance team to confirm validity and then the application will be allowed to move forward for additional notary review.

closing until clear list of SP entities and distribution provided
