### ISSUE TITLE
[DataCap Application] <Fengnong Holdings> - <TTXN>

### ISSUE THREAD

**Issue by io10xx** [filecoin-project/filecoin-plus-large-datasets#2224]
### Data Owner Name

TTXN

### What is your role related to the dataset

Storage provider filling out application on behalf of the data owner

### Data Owner Country/Region

China

### Data Owner Industry

Education & Training

### Website

https://www.ttxn.com/en.html

### Social Media

```text
https://www.ttxn.com/
https://weibo.com/u/6389621268
https://www.facebook.com/profile.php?id=100081869653796
http://www.fnholding.cn/
https://www.dfs168.com/
http://www.foisonshop.com/
```

### Total amount of DataCap being requested

4PiB

### Expected size of single dataset (one copy)

300TiB

### Number of replicas to store

5

### Weekly allocation of DataCap requested

800TiB

### On-chain address for first allocation

f1xcvzbnir6akxths6x27oew6sdenhw3dcw33qkba

### Data Type of Application

Public, Open Commercial/Enterprise

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
"Tiantian Xuenong", a subsidiary of Fengnong Holdings, is an online training platform for agricultural vocational education, which aims to cultivate a new type of professional farmers and help revitalize the countryside. At present, Xuenong cooperates with more than 2000 agricultural experts to produce more than 50, 000 courses. Including crop cultivation, animal husbandry and aquaculture, agricultural management and other contents, in the form of course teaching, expert consultation, online and offline training, public welfare activities, etc., to serve professional farmers and agricultural personnel to help them improve their skills and increase production and income. In terms of college cooperation, we are deeply engaged in the construction of new agricultural disciplines and give full play to the positive role of vocational education in the revitalization of rural areas.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
Video documents such as agricultural production and life, and videos of agriculture-related courses
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### If you are a data preparer. What is your location (Country/Region)

Viet Nam

### If you are a data preparer, how will the data be prepared? Please include tooling used and technical details?

```text
Using Qiniu software system to manage storage system and cache, and using lotus client for transaction storage.
```

### Please share a sample of the data

```text
https://pan.baidu.com/s/1a8L_PHxWS0Pk-GetVwyVeA?pwd=2qek
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Monthly

### For how long do you plan to keep this dataset stored on Filecoin

1.5 to 2 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, Europe

### How will you be distributing your data to storage providers

HTTP or FTP server, Lotus built-in data transfer

### How do you plan to choose storage providers

Slack, Partners

### How do you plan to make deals to your storage providers

Boost client, Lotus client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
- Have you prepared enough token for sector pledge?
- How will the data be prepared? Please include tooling used and technical details
- Best practice for storing large datasets includes ideally, storing it in 3 or more regions, with 4 or more storage provider operators or owners.You should list Miner ID, Business Entity, Location of sps you will cooperate with.
- Per the https://github.com/filecoin-project/notary-governance/issues/922 for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

**Comment by io10xx** [comment]
1   Yes, the SPs have prepared enough FIL tokens.
2  The data is in the owner's storage center. I will build a transmission channel between the data owner and the SP through Http/Ftp, then package the data and send it through Boost client to the Miner node of SP.
3  I confirm that I will abide by the rules of FIL+.

**Comment by io10xx** [comment]
I contacted the following SP：
F090999
F091987
F091313
F094311
F093856
F091936
F091099
F093961
F0187556
F093393
F090888
F092229

Because SP in some Asian regions have recently received extortion / reports (running SP nodes in gray areas in some countries), SP is reluctant to do KYC. Please understand more!
Thank you !

**Comment by Sunnyiscoming** [comment]
Have you completed the form(https://form.jotform.com/231862753015656)?

**Comment by io10xx** [comment]
> Have you completed the form(https://form.jotform.com/231862753015656)?

Yes, I just finished filling out the form. 
Thank you!

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
>4 PiB

**Expected weekly DataCap usage rate**
>800 TiB

**Client address**
>f1xcvzbnir6akxths6x27oew6sdenhw3dcw33qkba

**Comment by woshidama323** [comment]
checker:manualTrigger

**Comment by woshidama323** [comment]
Everything looks good to me 
Will support this first stage of LDN

**Comment by woshidama323** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedivmufz7eru5rsnd3jyikqgxa5xmgsvayqrcd7qflbem4s4rfnm4 
#### Address 
> f1xcvzbnir6akxths6x27oew6sdenhw3dcw33qkba
#### Datacap Allocated
> 204.79TiB
#### Signer Address
> f12tk3adljauwnd3hjbigpfxb7b7gdlj63p6afwtq
#### Id
> 62cfdbfc-52bb-4628-ad45-0d93078c54ab
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedivmufz7eru5rsnd3jyikqgxa5xmgsvayqrcd7qflbem4s4rfnm4

**Comment by herrehesse** [comment]
Report @woshidama323 & @Sunnyiscoming for allowing this behaviour. NO SP information listed publicly. No due diligence done.

@galen-mcandrew @raghavrmadya @Kevin-FF-USA

**Comment by io10xx** [comment]
> Report @woshidama323 & @Sunnyiscoming for allowing this behaviour. NO SP information listed publicly. No due diligence done.
> 
> @galen-mcandrew @raghavrmadya @Kevin-FF-USA

Because SP in some Asian regions have recently received extortion / reports (running SP nodes in gray areas in some countries), SP is reluctant to do KYC. Please understand more!
Thank you !

**Comment by a1991car** [comment]
Can you email filplus-app-review@fil.org using your official domain name to confirm your identity?
Email name should contain Issue ID #2224.

**Comment by io10xx** [comment]
> Can you email [filplus-app-review@fil.org](mailto:filplus-app-review@fil.org) using your official domain name to confirm your identity? Email name should contain Issue ID #2224.

![2224](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/117383350/8f2b6b95-f54c-4230-a90f-fb65074bc19b)

The mail has been sent, please confirm, thank you!

**Comment by herrehesse** [comment]
@io10xx - names, contact information and region of all your SPs please.

**Comment by io10xx** [comment]
> @io10xx - names, contact information and region of all your SPs please.

Reason:
1, an essential reason for the existence of blockchain-anti-authority review!
2, because the public KYC has caused some SP to be censored by some authoritative countries in Asia (KYC is regarded as evidence of reporting)!

So:
I think it's OK to just fill in the form (https://form.jotform.com/231862753015656) , and there's no need to disclose KYC on github.
thanks!  @herrehesse

**Comment by herrehesse** [comment]
Nice government policies i see. You are not sharing the info i asked?

**Comment by io10xx** [comment]
> Nice government policies i see. You are not sharing the info i asked?

Do you really don't understand or pretend you don't understand? In China, the bosses of some large SP companies engaged in filecoin are still in prison and have not been sentenced for a year or two.

This is the news that almost all people engaged in SP business know in East Asia.

Now that we are engaged in the public KYC of SP, who dares to disclose the real KYC? Why force these SP to provide false information?

**Comment by io10xx** [comment]
Recently, many SP who have done KYC on github reported that they were blackmailed and threatened to report illegal operation and maintenance FIL public chain.

**Comment by io10xx** [comment]
In the current situation, if SP is forced to do KYC, they may provide inaccurate or unverifiable KYC, which makes no sense.

**Comment by io10xx** [comment]
> Can you email [filplus-app-review@fil.org](mailto:filplus-app-review@fil.org) using your official domain name to confirm your identity? Email name should contain Issue ID #2224.

@a1991car  The email has been sent through the official domain name. Thank you!

**Comment by a1991car** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebe3dov4zekjl52gx6vl6pv66erpo5akxvyswwktuvrcwf6iyp6x2 
#### Address 
> f1xcvzbnir6akxths6x27oew6sdenhw3dcw33qkba
#### Datacap Allocated
> 204.79TiB
#### Signer Address
> f1qnumecdypgrbaebtkdfjnwt5ndacadcuas3deiq
#### Id
> 62cfdbfc-52bb-4628-ad45-0d93078c54ab
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebe3dov4zekjl52gx6vl6pv66erpo5akxvyswwktuvrcwf6iyp6x2

**Comment by io10xx** [comment]
> @raghavrmadya @Kevin-FF-USA @dkkapur @galen-mcandrew
> 
> Can ANYONE read what is happening here? O my god how are we ever going to sell storage if this keep happening. Lets close the LDN's as soon as we can. Unacceptable behaviour and free signatures from abusive notaries.

Well, you don't have to do that.
I'll just ask SP for this information.

**Comment by herrehesse** [comment]
No, this is clear abuse. Do you close the application yourself or you want me to ask the governance team?

**Comment by io10xx** [comment]
> No, this is clear abuse. Do you close the application yourself or you want me to ask the governance team?

The real filecoin network builder should not be like you blaming others everywhere.

**Comment by herrehesse** [comment]
Allright I ask governance. @raghavrmadya @Kevin-FF-USA @dkkapur

**Comment by kevzak** [comment]
SPs provided

f01850726 | Mk storage | Hanoi, Vietnam | 
f01850726 | J | F3 | Los Angeles, California, US | 
F091313 | Anxin Network | Hong Kong | 
F090888 |  Sever Info | Shenzhen,China | 
f0478837 || VshareCloud | Zhangzhou,China |

**Comment by kevzak** [comment]
checker:manualTrigger

**Comment by herrehesse** [comment]
f01850726 | Mk storage | Hanoi, Vietnam |
f01850726 | J | F3 | Los Angeles, California, US 

@Kevin-FF-USA what?

**Comment by xgoovo** [comment]
filecoin is store

**Comment by Sunnyiscoming** [comment]
Some of the sps in the table do not participated in
Some sps outside the form participated in
@io10xx  Can you explain about that?

**Comment by io10xx** [comment]
> Some of the sps in the table do not participated in Some sps outside the form participated in @io10xx Can you explain about that?

It's a long story, and the plan can't keep up with the change.
Previously promised to package, do not assist later, can only find a new SP to package.
So, it's like this.
Thank you!

**Comment by io10xx** [comment]
checker:manualTrigger

**Comment by io10xx** [comment]
> > Some of the sps in the table do not participated in Some sps outside the form participated in @io10xx Can you explain about that?
> 
> It's a long story, and the plan can't keep up with the change. Previously promised to package, do not assist later, can only find a new SP to package. So, it's like this. Thank you!


This is already the case, can I still continue to assist SP packaging?
@Sunnyiscoming

**Comment by io10xx** [comment]
? ?

**Comment by Filplus-govteam** [comment]
SP taking deals
f092229 | Qingdao, Shandong, CNCHINANET-BACKBONE | 50.97 TiB | 39.05% | 50.97 TiB | 0.00%
f090888 | Qingdao, Shandong, CNCHINANET-BACKBONE | 41.09 TiB | 31.48% | 41.09 TiB | 0.00%
f090833 | Shenzhen, Guangdong, CNCHINANET-BACKBONE | 35.25 TiB | 27.01% | 35.25 TiB | 0.00%
f0495421 | Zhangzhou, Fujian, CNCHINANET-BACKBONE | 3.22 TiB | 2.47% | 3.13 TiB | 2.91%

SP listed upfront 

SP 1 | f01850726 |  Mk storage | Hanoi, Vietnam | No | Peter
f01850726 |  F3 | Los Angeles, California, US | Yes | JiaL
F091313 | Anxin Network | Hong Kong | No | lupwi
F090888 |  Sever Info | Shenzhen,China | No | SeverT
f0478837 |VshareCloud | Zhangzhou,China | No | EgoLee

@io10xx I saw your note above about changes to SPs. However, for now we do not have proof of SP entity and location distribution. Please prove its not the same entity. Closing for now

**Comment by io10xx** [comment]
Okay
