### ISSUE TITLE
[DataCap Application] Environmental governance

### ISSUE THREAD

**Issue by hash889900** [filecoin-project/filecoin-plus-large-datasets#2228]
### Data Owner Name

Liaoning Zhongguan Environmental engineering Co., Ltd

### What is your role related to the dataset

Dataset Owner

### Data Owner Country/Region

China

### Data Owner Industry

Environment

### Website

no

### Social Media

```text
no
```

### Total amount of DataCap being requested

15PiB

### Expected size of single dataset (one copy)

1.5P

### Number of replicas to store

10

### Weekly allocation of DataCap requested

1PiB

### On-chain address for first allocation

f1tnkhku73afy6emaggffwewacjyqjnyn5feubeay

### Data Type of Application

Slingshot

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Liaoning Zhongguan Environmental engineering Co., Ltd. was established on December 6, 2007. The company's business scope includes: water environment governance, atmospheric environment governance, and ecological environment governance; Solid waste treatment; Comprehensive utilization of renewable resources; Design and construction general contracting of industrial wastewater and domestic wastewater treatment engineering; Water conservancy exploration and design, construction and maintenance of municipal public works; General contracting of environmental protection engineering construction; Operation, commissioning, and management services for environmental pollution control facilities; Production and sales of environmental protection equipment and engineering materials; Engineering consulting and evaluation; Design, construction, and sales of protective materials for radiation protection engineering; Manufacturing and installation of atmospheric pressure electric hot water boilers, waste heat recovery and energy-saving complete equipment, etc
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
Environmental governance promotional videos, environmental videos, satellite remote sensing images, etc
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### If you are a data preparer. What is your location (Country/Region)

China

### If you are a data preparer, how will the data be prepared? Please include tooling used and technical details?

```text
I've got experience preparing data at #2100.
```

### Has this dataset been stored on the Filecoin network before? If so, please explain and make the case why you would like to store this dataset again to the network. Provide details on preparation and/or SP distribution.

```text
Will store #2100 public datasets that have not been stored before
```

### Please share a sample of the data

```text
https://cloud.189.cn/t/IFreEfymmI3y （access code：7rjb）
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Monthly

### For how long do you plan to keep this dataset stored on Filecoin

More than 3 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, South America, Europe

### How will you be distributing your data to storage providers

HTTP or FTP server, Shipping hard drives

### How do you plan to choose storage providers

Slack, Partners

### If you already have a list of storage providers to work with, fill out their names and provider IDs below

```text
f02337006
f02337010
f01877184 
f02252173
f01836766
f01128206
f02062851
f02808888
```

### How do you plan to make deals to your storage providers

Boost client, Singularity

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by hash889900** [comment]
Taking advice from notary at #2100  to reapply

**Comment by Sunnyiscoming** [comment]
- The link of data samples you provided is not available. Please check it.
- Each application is applied for a single dataset. You can't store the data of the previous dataset in this application.
- Could you send an email with business license to filplus-app-review@fil.org with your official domain in order to confirm your identity? Email name should includes the issue id #2228.
- Have you prepared enough token for sector pledge?
- Per the https://github.com/filecoin-project/notary-governance/issues/922 for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

**Comment by hash889900** [comment]
> * The link of data samples you provided is not available. Please check it.

![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/138882650/95d205ad-d636-451f-95ac-a178d9fa0eb7)
everything normal

> * Each application is applied for a single dataset. You can't store the data of the previous dataset in this application.


I got it

> * Could you send an email with business license to [filplus-app-review@fil.org](mailto:filplus-app-review@fil.org) with your official domain in order to confirm your identity? Email name should includes the issue id [[DataCap Application] Environmental governance #2228](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/2228).

Don't own a domain name yet, business license confirmation has been sent, please check

> * Have you prepared enough token for sector pledge?

yes

> * Per the [Modification: Changes required to public open dataset application flow notary-governance#922](https://github.com/filecoin-project/notary-governance/issues/922) for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

Forms submitted

**Comment by hash889900** [comment]
> @hash889900
> 
> Business names, regions and contact information before proceeding:
> 
> f02337006 f02337010 f01877184 f02252173 f01836766 f01128206 f02062851 f02808888

| Miner ID   | Name   | Email                    | Region      |
|------------|--------|--------------------------|-------------|
| f02237006  | eager  | h32590056@gmail.com      | England     |
| f02237010  | peter  | 66677peter@gmail.com     | California  |
| f01877184  | Aron   | aron99301@gmail.com      | Singapore   |
| f02252173  | luna   | ymmart.com@gmail.com     | Tokyo       |
| f01836766  | Huang  | 8954056@qq.com           | GuangZhou   |
| f01128206  | zhangx | 970740860@qq.com         | hunan       |
| f02062851  | Mike   | ye334452000@gmail.com    | California  |
| f02808888  | guan   | runfeng13@gmail.com      | GuangZhou   |

**Comment by hash889900** [comment]
@Sunnyiscoming  Hi, any other questions, please?

**Comment by herrehesse** [comment]
@hash889900 why are you lying so much?

**Comment by hash889900** [comment]
> @hash889900 why are you lying so much?

I don't know what you mean.

**Comment by Sunnyiscoming** [comment]
@herrehesse Is there any evidence of challenge presented here? The client has completed the submission of relevant materials.

**Comment by hash889900** [comment]
> @hash889900 Have you completed KYC? 

Are you referring to SP, or this github account of mine?

**Comment by hash889900** [comment]
> @hash889900 Have you completed KYC?

 This account is a company public account and KYC is not available for the time being,

**Comment by herrehesse** [comment]
This is ALL fake:

Miner ID | Name | Email | Region
-- | -- | -- | --
f02237006 | eager | h32590056@gmail.com | England
f02237010 | peter | 66677peter@gmail.com | California
f01877184 | Aron | aron99301@gmail.com | Singapore
f02252173 | luna | ymmart.com@gmail.com | Tokyo
f01836766 | Huang | 8954056@qq.com | GuangZhou
f01128206 | zhangx | 970740860@qq.com | hunan
f02062851 | Mike | ye334452000@gmail.com | California
f02808888 | guan | runfeng13@gmail.com | GuangZhou

Miner ID	Name	Email	Region
f02237006	eager	[h32590056@gmail.com](mailto:h32590056@gmail.com)	England
f02237010	peter	[66677peter@gmail.com](mailto:66677peter@gmail.com)	California
f01877184	Aron	[aron99301@gmail.com](mailto:aron99301@gmail.com)	Singapore
f02252173	luna	[ymmart.com@gmail.com](mailto:ymmart.com@gmail.com)	Tokyo
f01836766	Huang	[8954056@qq.com](mailto:8954056@qq.com)	GuangZhou
f01128206	zhangx	[970740860@qq.com](mailto:970740860@qq.com)	hunan
f02062851	Mike	[ye334452000@gmail.com](mailto:ye334452000@gmail.com)	California
f02808888	guan	[runfeng13@gmail.com](mailto:runfeng13@gmail.com)	GuangZhou


Sunny you can not open up applications like this with clear lies.

**Comment by herrehesse** [comment]
66677peter@gmail.com you f*cking kidding me?

**Comment by herrehesse** [comment]
@hash889900 no KYC and lying about miners. Please spend you time somewhere else.

**Comment by hash889900** [comment]
> [66677peter@gmail.com](mailto:66677peter@gmail.com) you f*cking kidding me?

Please watch what you say and do.What's wrong with this e-mail address?

**Comment by hash889900** [comment]
@Sunnyiscoming  Is KYC mandatory, if yes please reply asap and I will apply for it

**Comment by hash889900** [comment]
@Sunnyiscoming It's been two weeks. Any more questions, please?

**Comment by zcfil** [comment]
Checked out the account history I'm willing to support the first round

**Comment by zcfil** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedq6mkcfjf4dypg64ehtap72bgytccon33bbvd4frz4opkbxpmpem 
#### Address 
> f1tnkhku73afy6emaggffwewacjyqjnyn5feubeay
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f1cjzbiy5xd4ehera4wmbz63pd5ku4oo7g52cldga
#### Id
> 55a98ba1-ff6e-4316-bf2e-3d81b4d88dcb
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedq6mkcfjf4dypg64ehtap72bgytccon33bbvd4frz4opkbxpmpem

**Comment by SuperChaiChai** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacea35cdesaq2qzcogbuila5taklwnnwm2n7qis3zlebv2lwz7znw6u 
#### Address 
> f1tnkhku73afy6emaggffwewacjyqjnyn5feubeay
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f12mckci3omexgzoeosjvstcfxfe4vqw7owdia3da
#### Id
> 55a98ba1-ff6e-4316-bf2e-3d81b4d88dcb
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacea35cdesaq2qzcogbuila5taklwnnwm2n7qis3zlebv2lwz7znw6u

**Comment by herrehesse** [comment]
This is ALL fake:

Miner ID | Name | Email | Region
-- | -- | -- | --
f02237006 | eager | h32590056@gmail.com | England
f02237010 | peter | 66677peter@gmail.com | California
f01877184 | Aron | aron99301@gmail.com | Singapore
f02252173 | luna | ymmart.com@gmail.com | Tokyo
f01836766 | Huang | 8954056@qq.com | GuangZhou
f01128206 | zhangx | 970740860@qq.com | hunan
f02062851 | Mike | ye334452000@gmail.com | California
f02808888 | guan | runfeng13@gmail.com | GuangZhou


SIGNED BY ABUSIVE NOTARIES @SuperChaiChai @zcfil

**Comment by Sunnyiscoming** [comment]
Some of the sps in the table do not participated in
@hash889900  Can you explain about that?

**Comment by hash889900** [comment]
> Some of the sps in the table do not participated in @hash889900 Can you explain about that?

Some SPs don't have storage plans at the moment

**Comment by hash889900** [comment]
checker:manualTrigger

**Comment by Normalnoise** [comment]
checker:manualTrigger

**Comment by hash889900** [comment]
checker:manualTrigger

**Comment by woshidama323** [comment]
LGTM, Will support this, it looks healthy, Keep going

**Comment by woshidama323** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceceocfimlxzwkimq77mlcgriwb4eror7ln67x6btgacogasyhzk2c 
#### Address 
> f1tnkhku73afy6emaggffwewacjyqjnyn5feubeay
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f12tk3adljauwnd3hjbigpfxb7b7gdlj63p6afwtq
#### Id
> 8bd9968b-1b24-41ed-af3b-bde471124ab2
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceceocfimlxzwkimq77mlcgriwb4eror7ln67x6btgacogasyhzk2c

**Comment by hash889900** [comment]
checker:manualTrigger

**Comment by hash889900** [comment]
checker:manualTrigger

**Comment by hash889900** [comment]
checker:manualTrigger

**Comment by Filplus-govteam** [comment]
f02828888new | Shenzhen, Guangdong, CNCHINANET-BACKBONE | 245.94 TiB | 32.06% | 245.94 TiB | 0.00%
f02808888 | Shenzhen, Guangdong, CNCHINANET-BACKBONE | 210.03 TiB | 27.38% | 210.03 TiB | 0.00%
f01836766 | Shenzhen, Guangdong, CNCHINANET-BACKBONE | 21.59 TiB | 2.82% | 21.59 TiB | 0.00%
f01128206 | Hong Kong, Central and Western, HKHK Kwaifong Group Limited | 113.88 TiB | 14.85% | 113.88 TiB | 0.00%
f02062851 | Los Angeles, California, USNetLab Global | 175.56 TiB | 22.89% | 175.56 TiB | 0.00%

SPs provided upfront:
f02337006 |eager | England | no | no
f02237010 | peter | Californial | no | no
f02808888 | guan | GuangZhou | no | no
f01877184 | Aron | Singapore | no | no
f01836766 | Huang | GuangZhou | no | no

SPs not matching @hash889900 . Seeing one entity storing 60%. Closing until proof of SP entity and distribution is provided

**Comment by xdwk999** [comment]
@Filplus-govteam Here's the latest list.
Miner ID | Name | Email | Region
-- | -- | -- | --
f02237006 | eager | h32590056@gmail.com | England
f02237010 | peter | 66677peter@gmail.com | California
f01877184 | Aron | aron99301@gmail.com | Singapore
f02252173 | luna | ymmart.com@gmail.com | Tokyo
f01836766 | Huang | 8954056@qq.com | GuangZhou
f01128206 | zhangx | 970740860@qq.com | hunan
f02062851 | Mike | ye334452000@gmail.com | California
f02808888 | guan | runfeng13@gmail.com | GuangZhou
f02828888|Zhang|kkwdtxm@gmail.com|GuangZhou

**Comment by hash889900** [comment]
@Filplus-govteam Here's the latest list.

Miner ID | Name | Email | Region
-- | -- | -- | --
f02237006 | eager | h32590056@gmail.com | England
f02237010 | peter | 66677peter@gmail.com | California
f01877184 | Aron | aron99301@gmail.com | Singapore
f02252173 | luna | ymmart.com@gmail.com | Tokyo
f01836766 | Huang | 8954056@qq.com | GuangZhou
f01128206 | zhangx | 970740860@qq.com | hunan
f02062851 | Mike | ye334452000@gmail.com | California
f02808888 | guan | runfeng13@gmail.com | GuangZhou
f02828888 | Zhang|kkwdtxm@gmail.com|GuangZhou

**Comment by hash889900** [comment]
checker:manualTrigger

**Comment by hash889900** [comment]
@Filplus-govteam It's been two weeks, the information has been submitted, can you reopen it?

**Comment by hash889900** [comment]
checker:manualTrigger

**Comment by hash889900** [comment]
添加新的存储提供商

**Comment by Filplus-govteam** [comment]
@hash889900 than you for the list. You can contact these SPs and send proof of entity and location for each SP to filplus.govteam@gmail.com

**Comment by hash889900** [comment]
> @hash889900 than you for the list. You can contact these SPs and send proof of entity and location for each SP to [filplus.govteam@gmail.com](mailto:filplus.govteam@gmail.com)

![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/138882650/987819cb-8b03-4662-aa57-987c44c453ae)
Sent

f01128206 | zhangx | 970740860@qq.com | hunan
Not provided yet, only cooperating with it after providing it
@Filplus-govteam

**Comment by Filplus-govteam** [comment]
@hash889900 reviewing this we can consider Mike is legit, provided proof of address in USA and is not using VPN.

Eager in England and Peter in California both show IP provided by VPN service providers and for both, the proof of location documents do not show anything related to them or their entity. Also both are part of many other closed applications.

**Comment by hash889900** [comment]
> @hash889900 reviewing this we can consider Mike is legit, provided proof of address in USA and is not using VPN.
> 
> Eager in England and Peter in California both show IP provided by VPN service providers and for both, the proof of location documents do not show anything related to them or their entity. Also both are part of many other closed applications.

@Filplus-govteam 
Miner ID | Name | Email | Region
-- | -- | -- | --
f02237006 | eager | h32590056@gmail.com | England
f02237010 | peter | 66677peter@gmail.com | California

Are these two SPs right, I'll contact them and Suspend cooperation with them

**Comment by Filplus-govteam** [comment]
With the new documentation provided, we cannot validate their locations accurately. I'd ask them to use a third party to confirm.

**Comment by hash889900** [comment]
@Filplus-govteam I'm in the process of contacting them and until they pass the review, I'll suspend working with them until they do, so can you open this LDN now?

**Comment by hash889900** [comment]
> I'd ask them to use a third party to confirm.

@Filplus-govteam How does the process work? Do you need my help with this, or do you contact them directly via e-mail?

**Comment by Filplus-govteam** [comment]
who are you working with then?

**Comment by hash889900** [comment]
> who are you working with then?

@Filplus-govteam  Work with these for now if you can
Miner ID | Name | Email | Region
-- | -- | -- | --
f01877184 | Aron | aron99301@gmail.com | Singapore
f02252173 | luna | ymmart.com@gmail.com | Tokyo
f01836766 | Huang | 8954056@qq.com | GuangZhou
f02062851 | Mike | ye334452000@gmail.com | California
f02808888 | guan | runfeng13@gmail.com | GuangZhou
f02828888 | Zhang|kkwdtxm@gmail.com|GuangZhou

**Comment by AlanGreaterheat** [comment]
> > who are you working with then?
> 
> @Filplus-govteam Work with these for now if you can
> 
> Miner ID	Name	Email	Region
> f01877184	Aron	[aron99301@gmail.com](mailto:aron99301@gmail.com)	Singapore
> f02252173	luna	[ymmart.com@gmail.com](mailto:ymmart.com@gmail.com)	Tokyo
> f01836766	Huang	[8954056@qq.com](mailto:8954056@qq.com)	GuangZhou
> f02062851	Mike	[ye334452000@gmail.com](mailto:ye334452000@gmail.com)	California
> f02808888	guan	[runfeng13@gmail.com](mailto:runfeng13@gmail.com)	GuangZhou
> f02828888	Zhang	[kkwdtxm@gmail.com](mailto:kkwdtxm@gmail.com)	GuangZhou

Historical records were viewed and scrutinized by the governance team, please work with the SPs as per the latest disclosure.

**Comment by AlanGreaterheat** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedin3gqafnyjd4bpfb2mgmr3k5c235t2k4w3gy2wrc5mxbaocl5dy 
#### Address 
> f1tnkhku73afy6emaggffwewacjyqjnyn5feubeay
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f1pnmzlxj7cfeo2v6oj5nco46hkg2l46wj7o4xxui
#### Id
> a99d5de2-978f-444c-9913-ebbf6a8b6bcf
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedin3gqafnyjd4bpfb2mgmr3k5c235t2k4w3gy2wrc5mxbaocl5dy

**Comment by SuperChaiChai** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebcocb6xbp5lkk43skebmvj6em7nd552dptzacgniikh7bah4k3dw 
#### Address 
> f1tnkhku73afy6emaggffwewacjyqjnyn5feubeay
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f12mckci3omexgzoeosjvstcfxfe4vqw7owdia3da
#### Id
> a99d5de2-978f-444c-9913-ebbf6a8b6bcf
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebcocb6xbp5lkk43skebmvj6em7nd552dptzacgniikh7bah4k3dw

**Comment by hash889900** [comment]
checker:manualTrigger

**Comment by hash889900** [comment]
checker:manualTrigger

**Comment by hash889900** [comment]
checker:manualTrigger

**Comment by hash889900** [comment]
checker:manualTrigger

**Comment by hash889900** [comment]
checker:manualTrigger

**Comment by hash889900** [comment]
Updating the list again
Miner ID | Name | Email | Region
-- | -- | -- | --
f01877184 | Aron | aron99301@gmail.com | Singapore
f02252173 | luna | ymmart.com@gmail.com | Tokyo
f01836766 | Huang | 8954056@qq.com | GuangZhou
f02062851 | Mike | ye334452000@gmail.com | California
f02808888 | guan | runfeng13@gmail.com | GuangZhou
f02828888 | Zhang|kkwdtxm@gmail.com|GuangZhou
f02817777

**Comment by hash889900** [comment]
checker:manualTrigger

**Comment by hash889900** [comment]
checker:manualTrigger

**Comment by hash889900** [comment]
checker:manualTrigger

**Comment by hash889900** [comment]
checker:manualTrigger

**Comment by hash889900** [comment]
checker:manualTrigger

**Comment by hash889900** [comment]
checker:manualTrigger

**Comment by hash889900** [comment]
checker:manualTrigger

**Comment by nj-steve** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedygkiadgvhniv7wlyjq76uws3hglvlq7hhscxfujrulh4tsfsgbm 
#### Address 
> f1tnkhku73afy6emaggffwewacjyqjnyn5feubeay
#### Datacap Allocated
> 1.00PiB
#### Signer Address
> f1xx6555qijma7igpnjspyvdunc4vfxkawnpqy5ii
#### Id
> d0cda024-1572-4b9d-82c1-78341cda0966
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedygkiadgvhniv7wlyjq76uws3hglvlq7hhscxfujrulh4tsfsgbm

**Comment by hash889900** [comment]
checker:manualTrigger

**Comment by SuperChaiChai** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebbvm7xmsb2cwdxoy3qyt4xdu4ps6dprxwrdznd5oaw7pqloxit3m 
#### Address 
> f1tnkhku73afy6emaggffwewacjyqjnyn5feubeay
#### Datacap Allocated
> 1.00PiB
#### Signer Address
> f12mckci3omexgzoeosjvstcfxfe4vqw7owdia3da
#### Id
> d0cda024-1572-4b9d-82c1-78341cda0966
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebbvm7xmsb2cwdxoy3qyt4xdu4ps6dprxwrdznd5oaw7pqloxit3m

**Comment by hash889900** [comment]
checker:manualTrigger

**Comment by hash889900** [comment]
checker:manualTrigger

**Comment by Normalnoise** [comment]
checker:manualTrigger

**Comment by hash889900** [comment]
Updating the list again
Miner ID | Name | Email | Region
-- | -- | -- | --
f01877184 | Aron | aron99301@gmail.com | Singapore
f02252173 | luna | ymmart.com@gmail.com | Tokyo
f01836766 | Huang | 8954056@qq.com | GuangZhou
f02062851 | Mike | ye334452000@gmail.com | California
f02808888 | guan | runfeng13@gmail.com | GuangZhou
f02828888 | Zhang | kkwdtxm@gmail.com | GuangZhou
f02817777 | zhangx |   | Hong Kong
f02816666|jastin| |Huhehaote

**Comment by EVS2024** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacea77ndid76jzycpcttng2nnnjlkejrjmdoxi4lx7i7cda5fw262lu 
#### Address 
> f1tnkhku73afy6emaggffwewacjyqjnyn5feubeay
#### Datacap Allocated
> 2.00PiB
#### Signer Address
> f1yh6q3nmsg7i2sys7f7dexcuajgoweudcqj2chfi
#### Id
> 4801d5cd-a54e-458e-92de-78e614be3f28
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacea77ndid76jzycpcttng2nnnjlkejrjmdoxi4lx7i7cda5fw262lu

**Comment by stcloudlisa** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecje4lv5ans2kht6vnxtcpmy7rqs2ckljc4u7e5qgwpshbejcpw6k 
#### Address 
> f1tnkhku73afy6emaggffwewacjyqjnyn5feubeay
#### Datacap Allocated
> 2.00PiB
#### Signer Address
> f1jvvltduw35u6inn5tr4nfualyd42bh3vjtylgci
#### Id
> 4801d5cd-a54e-458e-92de-78e614be3f28
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecje4lv5ans2kht6vnxtcpmy7rqs2ckljc4u7e5qgwpshbejcpw6k

**Comment by Normalnoise** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedqmpuexdp4yrl7a4i4q3votgjfodkymg5nffr5ge2wjq3p73ttcg 
#### Address 
> f1tnkhku73afy6emaggffwewacjyqjnyn5feubeay
#### Datacap Allocated
> 2.00PiB
#### Signer Address
> f1c5non5yf35avgcpsqvxu4yj54yyvxorwyjochqq
#### Id
> 5a0771eb-fecf-47f3-a476-e47535f85277
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedqmpuexdp4yrl7a4i4q3votgjfodkymg5nffr5ge2wjq3p73ttcg

**Comment by ipollo00** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec6ph3ecdxuugf6hazwpc5l63khrbpfnak577vzbwbn2ujdyst7ry 
#### Address 
> f1tnkhku73afy6emaggffwewacjyqjnyn5feubeay
#### Datacap Allocated
> 2.00PiB
#### Signer Address
> f1n5wlrrhoxpkgwij25xrtt7w7g2k3fhbthmdn6ri
#### Id
> 5a0771eb-fecf-47f3-a476-e47535f85277
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec6ph3ecdxuugf6hazwpc5l63khrbpfnak577vzbwbn2ujdyst7ry

**Comment by hash889900** [comment]
checker:manualTrigger

**Comment by hash889900** [comment]
checker:manualTrigger

**Comment by woshidama323** [comment]
checker:manualTrigger

**Comment by woshidama323** [comment]
LGTM 
Will support, Keep tracing

**Comment by woshidama323** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebjxsx76uhn2fxumlcaahtnp5jvp5xe4tex2mmbym634iazszl5wu 
#### Address 
> f1tnkhku73afy6emaggffwewacjyqjnyn5feubeay
#### Datacap Allocated
> 2.00PiB
#### Signer Address
> f12tk3adljauwnd3hjbigpfxb7b7gdlj63p6afwtq
#### Id
> 63b11665-1ea6-40c9-8f6e-6f1a067bf22c
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebjxsx76uhn2fxumlcaahtnp5jvp5xe4tex2mmbym634iazszl5wu

**Comment by hash889900** [comment]
checker:manualTrigger

**Comment by hash889900** [comment]
checker:manualTrigger

**Comment by MikeH1999** [comment]
checker:manualTrigger

**Comment by hash889900** [comment]
checker:manualTrigger
