### ISSUE TITLE
[DataCap Application] Coupled Model Intercomparison Project 6

### ISSUE THREAD

**Issue by LUGalina** [filecoin-project/filecoin-plus-large-datasets#2230]
### Data Owner Name

Pangeo Community

### What is your role related to the dataset

Data Preparer

### Data Owner Country/Region

United States

### Data Owner Industry

Life Science / Healthcare

### Website

https://wcrp-cmip.org/cmip-phase-6-cmip6/

### Social Media

```text
https://pangeo-data.github.io/pangeo-cmip6-cloud/
```

### Total amount of DataCap being requested

15PiB

### Expected size of single dataset (one copy)

1730TiB

### Number of replicas to store

8

### Weekly allocation of DataCap requested

1PiB

### On-chain address for first allocation

f1l66uxwsnh6wp2k5uzkriccr23wkxffwfkxjxj4i

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
CMIP began in 1995 under the auspices of the Working Group on Coupled Modelling (WGCM). The first set of common experiments involved comparing the model response to an idealized forcing – a constant rate of increase which was accomplished using a CO2 increase of 1% per year compounded.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
Zarr formatted data and Netcdf formatted data---The sixth phase of global coupled ocean-atmosphere general circulation model ensemble.
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### If you are a data preparer. What is your location (Country/Region)

Hong Kong

### If you are a data preparer, how will the data be prepared? Please include tooling used and technical details?

```text
i have downloaded data, then i will use lotus to make data into car files.
```

### Has this dataset been stored on the Filecoin network before? If so, please explain and make the case why you would like to store this dataset again to the network. Provide details on preparation and/or SP distribution.

```text
Seeems no one finished storing it.
```

### Please share a sample of the data

```text
s3://cmip6-pds/
s3://esgf-world/
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

More than 3 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, Europe

### How will you be distributing your data to storage providers

HTTP or FTP server, Shipping hard drives, Lotus built-in data transfer

### How do you plan to choose storage providers

Slack, Filmine, Big Data Exchange, Partners

### If you already have a list of storage providers to work with, fill out their names and provider IDs below

```text
f01392600 Guiyang  f01808139 HongKong  f0420161 Toronto f02368321 Singapore f02097936 Hangzhou
```

### How do you plan to make deals to your storage providers

Boost client, Lotus client, Singularity

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by LUGalina** [comment]
@Sunnyiscoming Hello Sunny, I have submitted the form with the 
 number of this new application. https://form.jotform.com/231862753015656 . Please check it, thank you very much.

**Comment by herrehesse** [comment]
@LUGalina Can you show me your evidence for "Seeems no one finished storing it." ?

**Comment by LUGalina** [comment]
@herrehesse I don't know how to show it.

**Comment by herrehesse** [comment]
Exactly. Point proven. Can we close this application please?

**Comment by LUGalina** [comment]
@herrehesse In fact there's no one finished the store from what I've seen. I didn't do any wrong here. Who exactly are you??

@galen-mcandrew @dkkapur @raghavrmadya @Kevin-FF-USA @Sunnyiscoming Can you please help to explain all?

**Comment by Sunnyiscoming** [comment]
Have you completed KYC?
Contact email information has not been all completed in the form. Please resubmit the form with complete information.
The Miner IDs and entity name and locaiton should be posted here.

**Comment by herrehesse** [comment]
@LUGalina stop trying to scam here, you cant prove your statement so just stop it. No reason to continue.

**Comment by LUGalina** [comment]
@herrehesse 
First, you're not a notary or offcial in Fil+. Whoever you are, you have no right to insult people here. 
Second, I'm not against any rules of community, so I don't need to provide any additional proof to you. I have provided enough for official's @Sunnyiscoming request.
What i saw is you shouting in new applications and stop every one. Any smart person would not behave like you.

**Comment by LUGalina** [comment]
@Sunnyiscoming Yes. Have resubmitted the form.

**Comment by LUGalina** [comment]
@Sunnyiscoming Hello, can you please tell me about when can my application be approved?

**Comment by Filplus-govteam** [comment]
Hi @LUGalina please list SP entity and location to showcase distribution.

**Comment by Filplus-govteam** [comment]
SP 1	f01392600	Jameswang	do not provide to me	individual sp	Guiyang, Guizhou, CN	
SP 2	f01808139	Pedro	do not provide to me	individual sp	HongKong	
SP 3	f0420161	        Tomas	do not provide to me	individual sp	Toronto, Ontario, CA	
SP 4	f02368321	CarlSun		                                 individual sp	Singapore	
SP 5	f02097936	David	do not provide to me	individual sp	Hangzhou, Zhejiang	

There is no contact information, no SP entity information listed on either form. Please provide clear information about the SPs you are partnering with. Can you prove James in CN, Pedro in HK, Tomas in Toronto?

**Comment by LUGalina** [comment]
Hello sir. I have previously provided f02368321 's email in the form. These sps told me that they are individual sps, so that there's no entity information. You can return to look at it. 

James![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/143600776/a89fef40-786e-44d8-a3f0-e52a9a205245)
Pedro![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/143600776/a7c15ee5-1c3e-4a2e-9980-4e58d3e82b56)
Tomas![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/143600776/db98b898-fe9f-4b6f-ad94-a4e2217a35cf)
@Filplus-govteam

**Comment by Sunnyiscoming** [comment]
SP List provided:
[{"providerID": "f01392600","City": "Guizhou", "Country": "CN", "SPOrg","XYZ"},
{"providerID": "f01808139","City": "HongKong", "Country": "CN", "SPOrg","XYZ"},
{"providerID": "f0420161","City": "Ontario", "Country": "CA", "SPOrg","XYZ"},
{"providerID": "f02368321","City": "XYZ", "Country": "Singapore", "SPOrg","XYZ"},
{"providerID": "f02097936","City": "Zhejiang", "Country": "CN", "SPOrg","XYZ"},]
