### ISSUE TITLE
[DataCap Application] SHANGHAIDICHANCulture Media Co., Ltd.

### ISSUE THREAD

**Issue by BSPN-TV** [filecoin-project/filecoin-plus-large-datasets#2231]
### Data Owner Name
SHANGHAIDICHANCulture Media Co., Ltd.

### What is your role related to the dataset
Data Preparer

### Data Owner Country/Region
China

### Data Owner Industry
Information, Media & Telecommunications

### Website
[https://linktr.ee/BSPN_TV](https://linktr.ee/BSPN_TV)

### Social Media
[at]BSPN_CN    [at]BSPN_TV (Twitter)

### Total amount of DataCap being requested
8 PiB

### Expected size of single dataset (one copy)
800 TiB

### Number of replicas to store
10

### Weekly allocation of DataCap requested
1 PiB

### On-chain address for first allocation
f153myodwhfb22vvmniegfakmsqeyzpel7efcyyxq

### Data Type of Application
Private Commercial/Enterprise

### Custom multisig
- [x] Use Custom Multisig

### Identifier
efil

### Share a brief history of your project and organization
BSPN is a game e-sports event operating organization under Shanghai Dichan Culture Media Co., Ltd. The company has been established for 6 years, and its clubs include AS Xiange, the former KPL player in the Honor of Kings competition. The company has a large number of game training videos, event recordings, media promotions and other video culture

### Is this project associated with other projects/ecosystem stakeholders?
No

### If answered yes, what are the other projects/ecosystem stakeholders
n/a

### Describe the data being stored onto Filecoin
Game event videos, player training video. Commercial media promotional videos, etc.

### Where was the data currently stored in this dataset sourced from
My own storage infra

### If you answered "Other" in the previous question, enter the details here
n/a

### If you are a data preparer, what is your location (City and Country)
CHIA 

### If you are a data preparer, how will the data be prepared? Please include tooling used and technical details?
I plan to quickly store existing data to filecoin. Divide the data into 10 copies, and also back up the data to filecoin after the company quickly generates the data in the future

### If you are not preparing the data, who will prepare the data?  (Provide name and business)
n/a

### Has this dataset been stored on the Filecoin network before? If so, please explain and make the case why you would like to store this dataset again to the network. Provide details on preparation and/or SP distribution.
n/a

### Please share a sample of the data
https://drive.google.com/drive/folders/1zprrhqgAtMQ_F39e9PAUChaIATgugYK3?usp=sharing

### Confirm that this is a public dataset that can be retrieved by anyone on the Network
No

### If you chose not to confirm, what was the reason
Most of the data is non-public internal data, such as the results of internal training matches, business media, etc.

### What is the expected retrieval frequency for this data
Yearly

### For how long do you plan to keep this dataset stored on Filecoin
More than 3 years

### In which geographies do you plan on making storage deals
Greater China

### How will you be distributing your data to storage providers
Shipping hard drives

### How do you plan to choose SP
Other

### If you answered "Others" in the previous question, what is the tool or platform you plan to use
boost

### If you already have a list of storage providers to work with, fill out their names and provider IDs below
f02223012
For others, the SP will help me contact other SPs until 10 copies are completed.

### How do you plan to make deals to your storage providers
Boost client

### If you answered "Others/custom tool" in the previous question, enter the details here
n/a

### Can you confirm that you will follow the Fil+ guideline
Yes

_Application created via [filplus.storage](https://filplus.storage)_

**Comment by data-programs** [comment]
This application is requesting DataCap for a **private** dataset, so it's labeled `efil+`

**Comment by kevzak** [comment]
hello @BSPN-TV because this is an E-Fil pathway application please complete the steps as listed here: https://efilplus.super.site/

**Comment by BSPN-TV** [comment]
@kevzak  OK I'll get right on it.
