### ISSUE TITLE
[DataCap Application] <LaughStorage> - < Sloan Digital Sky Survey> - New

### ISSUE THREAD

**Issue by 26dos** [filecoin-project/filecoin-plus-large-datasets#2232]
### Data Owner Name

LaughStorage

### What is your role related to the dataset

Data Preparer

### Data Owner Country/Region

China

### Data Owner Industry

Not-for-Profit

### Website

https://www.sdss.org/

### Social Media

```text
NA
```

### Total amount of DataCap being requested

12PiB

### Expected size of single dataset (one copy)

1.4p

### Number of replicas to store

8

### Weekly allocation of DataCap requested

1PiB

### On-chain address for first allocation

f1f27fmxepqkflvsh7nvmmsh7sgt6oqv25edfz22a

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
I joined the filecoin network in 2021, and made the cc package of fil at the very beginning.  In 2022, we did a part of cc to dc conversion, and now we have a planned continuous development of data storage. In 2023, I established a technical service company  <Laughstorage> to make in-depth investment in the distributed storage track.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
The Sloan Digital Sky Survey (SDSS) is one of the most ambitious and influential surveys in the history of astronomy. 
The SDSS project has established in 2000, five periods, 18 times data released. The 19th DR will be in 2024. 
As for now, there are about 750TB volume of data can be accessed.  5.5 million directories, 400 million files. 
DR1-DR7: SDSS-I, 2000-2005; SDSS-II, 2005-2008), it obtained deep, multi-color images covering more than a quarter of the sky and created 3-dimensional maps containing more than 930,000 galaxies and more than 120,000 quasars.
DR8: contains all images from the SDSS telescope - the largest color image of the sky ever made. It also includes measurements for nearly 500 million stars and galaxies, and spectra of nearly two million. 
DR9 contains the first release of BOSS spectroscopy to the public as well as several significant updates to the cumulative SDSS archive
DR10 contains the first release of APOGEE infrared Galactic spectroscopy as well as cumulative updates to the BOSS optical extragalactic spectroscopy archive
The SDSS began regular survey operations in 2000, after a decade of design and construction.  It has progressed through several phases, SDSS-I (2000-2005), SDSS-II (2005-2008), SDSS-III (2008-2014), and SDSS-IV (2014-2020).  Each of these phases has involved multiple surveys with interlocking science goals.  The three surveys that comprise SDSS-IV are eBOSS (including SPIDERS and TDSS), APOGEE-2, and MaNGA (including MaStar),
The SDSS-V Pioneering Panoptic Spectroscopy program started observing in October 2020, and consists of three surveys, known in SDSS-V terminology as mapper programs.

Milky Way Mapper is a multi-object spectroscopic survey to obtain near-infrared and/or optical spectra of more than 4 million stars throughout the Milky Way and Local Group
Local Volume Mapper is an optical, integral-field spectroscopic survey that will target the Milky Way, Small and Large Magellanic Clouds, and other Local Volume galaxies
Black Hole Mapper is a multi-object spectroscopic survey that emphasizes optical spectra (often also with multiple epochs of spectroscopy) for more than 300,000 quasars
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### If you are a data preparer. What is your location (Country/Region)

China

### If you are a data preparer, how will the data be prepared? Please include tooling used and technical details?

```text
After processing the data I download, I will transfer through online.
```

### Has this dataset been stored on the Filecoin network before? If so, please explain and make the case why you would like to store this dataset again to the network. Provide details on preparation and/or SP distribution.

```text
AFAK NO
```

### Please share a sample of the data

```text
http://classic.sdss.org/dr7/
http://sdss3.org/
https://www.sdss4.org/dr17/data_access/volume/
https://dr17.sdss.org/sas/dr17/apogee/spectro/aspcap/
https://dr17.sdss.org/sas/dr17/apogee/spectro/speclib/
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

1.5 to 2 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, Africa, North America, South America

### How will you be distributing your data to storage providers

HTTP or FTP server, IPFS, Shipping hard drives, Lotus built-in data transfer

### How do you plan to choose storage providers

Slack, Big Data Exchange, Partners

### If you already have a list of storage providers to work with, fill out their names and provider IDs below

```text
f0861589 CN,SD C	
f02223876 HK, FTM Ltd.
f02212669 CN,Cryptomage
f02115125 KR, FiveByte
and more are connecting.
Actually is base on their collateral.
```

### How do you plan to make deals to your storage providers

Boost client, Lotus client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by 26dos** [comment]
Regarding the previous question:
1, regarding the node disclosure issue, we have re-contacted and assured that the node disclosure will be 100% matching
2、About the retrieval problem, we ensure that all nodes support retrievable

**Comment by Sunnyiscoming** [comment]
- Could you send an email to filplus-app-review@fil.org with your official domain in order to confirm your identity? Email name should includes the issue id #2232.
- Per the https://github.com/filecoin-project/notary-governance/issues/922 for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

**Comment by herrehesse** [comment]
@26dos How do you plan on downloading the data? I know people inside SDSS and 1.2PiB will take you over 5 years to download with their bucket speed and they do not accept physical transfers. Can you explain?

**Comment by 26dos** [comment]
@Sunnyiscoming 
All have been submitted. Please check.

**Comment by 26dos** [comment]
@herrehesse
From the data we have prepared so far, the download speed is normal.
![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/120706474/65aff8c7-d234-4168-8dab-928ecb3ad60b)
![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/120706474/32920d52-c3f8-4068-9d59-b7527b57c01c)

**Comment by herrehesse** [comment]
This proofs exactly nothing. Can you proof to me you have SDSS data?

**Comment by 26dos** [comment]
@herrehesse 
The download speed depends on the downloader's network bandwidth, if you think the project is limiting the speed, please provide evidence.

**Comment by herrehesse** [comment]
@26dos - do not get me started my friend. Tolerance for abuse is zero. This application is dead in the water.

**Comment by Sunnyiscoming** [comment]
Have you completed KYC?
Email has not been received. Please check it.
Contact name and email information of sps has not been all completed in the form. Please resubmit the form with complete information.
The Miner IDs and entity name and locaiton should be posted here.

**Comment by 26dos** [comment]
@Sunnyiscoming Hi, I've sent the email again and included our business licence!
Okay, I'll resubmit the form.

**Comment by herrehesse** [comment]
The Miner IDs and entity name and locaiton should be posted here.

**Comment by 26dos** [comment]
@Sunnyiscoming The form has been resubmitted. Thanks.

f02815620  hk    BigFive	
f01159754   Hunan  VITACapital   
f02327534  USA   ipollo	
f02320312  USA  R1	
 f02211572  Chendu  MicroAnt

**Comment by herrehesse** [comment]
I will be contacting the businesses and checking if all is correct.

**Comment by 26dos** [comment]
Is there an update here?

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 12PiB

**Expected weekly DataCap usage rate**
> 1PiB

**Client address**
>f1f27fmxepqkflvsh7nvmmsh7sgt6oqv25edfz22a

**Comment by 26dos** [comment]
@Sunnyiscoming 

Is there an update here?

**Comment by Filplus-govteam** [comment]
> 02815620 hk BigFive
> f01159754 Hunan VITACapital
> f02327534 USA ipollo
> f02320312 USA R1
> f02211572 Chendu MicroAnt

@26dos please resubmit with SP entity contact info included. Need to confirm separate entities here.

**Comment by Filplus-govteam** [comment]
closing until updated

**Comment by 26dos** [comment]
@Sunnyiscoming @Filplus-govteam 

Hi, I've updated the information to the list below, plus if there are adjustments to the sp, I will disclose them earlier in the course of subsequent projects:

f02815620 | hk | BigFive | czh9994@gmail.com | Chen
f01159754 | Hunan | VITACapital | 15071084991@163.com | Chris
f02327534 | USA | ipollo | vito@ipollo.com | vito
f02320312 | USA | R1 | 122764916@qq.com | BoQian
f02211572 | Chendu | MicroAnt | guokai0916@gmail.com | GuoKai

**Comment by 26dos** [comment]
@Sunnyiscoming @galen-mcandrew @Filplus-govteam 
Excuse me, are you still working? Is there someone here to follow up?

**Comment by Filplus-govteam** [comment]
Please submit SP proof of location to filplus.govteam@gmail.com. This can include business licence or proof of SP address in country listed. @26dos
