### ISSUE TITLE
[DataCap Application] <AIGC CHAIN> - <AIGC CHAIN - Data Storage>

### ISSUE THREAD

**Issue by NDLABS-Leo** [filecoin-project/filecoin-plus-large-datasets#2233]
### Data Owner Name

AIGC CHAIN

### What is your role related to the dataset

Storage provider filling out application on behalf of the data owner

### Data Owner Country/Region

United States

### Data Owner Industry

Web3 / Crypto

### Website

https://www.aigcchain.io/home

### Social Media

```text
https://twitter.com/AIGCChain
https://discord.com/invite/aigcchain
```

### Total amount of DataCap being requested

10PiB

### Expected size of single dataset (one copy)

1280T

### Number of replicas to store

8

### Weekly allocation of DataCap requested

1PiB

### On-chain address for first allocation

f1hcstcukrzprglb3xnbkrqu735qp3hc3gybbacwi

### Data Type of Application

Public, Open Commercial/Enterprise

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
AIGC Chain is a decentralized platform that is designed to promote responsible generative AI through the use of blockchain technology.
The platform is built on its own foundational image model and LLM, and aims to address the challenges faced by the industry by ensuring that ownership of data and customized models belongs only to the users (individuals, private sector, and governments) in a secure and trustworthy manner.
With its focus on decentralization and fair participation, AIGC Chain is poised to revolutionize the AI industry.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
With over 400 billion parameters, our base model allows users to generate an expansive range of
content, or train their own models to cover any topic or style.
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### If you are a data preparer. What is your location (Country/Region)

Singapore

### If you are a data preparer, how will the data be prepared? Please include tooling used and technical details?

```text
I was assisting in preparing the data as a sp for one of the homes. Currently we are transferring the data by means of hard drive emails and network transfers. Storage is done through boost.
```

### If you are not preparing the data, who will prepare the data?  (Provide name and business)

```text
We are lesder sp and will be looking to co-operate with more sp's for storage!
```

### Has this dataset been stored on the Filecoin network before? If so, please explain and make the case why you would like to store this dataset again to the network. Provide details on preparation and/or SP distribution.

```text
We are lesder sp and will be looking to co-operate with more sp's for storage!
```

### Please share a sample of the data

```text
https://aigc.ndlabs.io/ipfs/QmdZqR3hWswW9Mm5DRTuAjsj5hKEPv9SVtzXQTU4vLFWRa
https://aigc.ndlabs.io/ipfs/QmacuxRkHgwAZWJmDQkqEucFPGB51uESJDEm7D7n8MdfN7
https://ipfs.ndlabs.io/ipfs/QmagGHSWCUMVvqYHf2LD5fMoFSrL8cdd6cjhULg21cdCxZ
https://ipfs.ndlabs.io/ipfs/QmSL1kHidnJPigAuTCr89zTn5ibbm249W3Ub1FQ75oykgU
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

2 to 3 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, Africa, North America

### How will you be distributing your data to storage providers

Cloud storage (i.e. S3), HTTP or FTP server, IPFS, Shipping hard drives

### How do you plan to choose storage providers

Slack, Big Data Exchange, Partners

### If you already have a list of storage providers to work with, fill out their names and provider IDs below

```text
f01159754 - HK - VITACapital
f02321504 - USA- Ipollo
f02322031 - USA - Ipollo
f02226869 - Jiangxi - LuckyMine
f01853077 - Singapore - Alpha100
```

### How do you plan to make deals to your storage providers

Boost client, Lotus client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by NDLABS-Leo** [comment]
We have assisted our customers in storing their data, and as you can see from the sample data address, it is already stored on IPFS.

**Comment by data-programs** [comment]
<img width="32" alt="KYC" Verified src="https://stable.filplus.storage/images/filplus-kyc-verified-badge.png"/>

This user’s identity has been verified through [filplus.storage](https://filplus.storage)

**Comment by Sunnyiscoming** [comment]
- Could you send an email to filplus-app-review@fil.org with the official domain in order to confirm your identity? Email name should includes the issue id #2233.
- Have you prepared enough token for sector pledge?
- Has this dataset been stored on Filecoin before? If so, why are you choosing to store it again?
- Best practice for storing large datasets includes ideally, storing it in 3 or more regions, with 4 or more storage provider operators or owners.You should list Miner ID, Business Entity, Location of sps you will cooperate with.
- Per the https://github.com/filecoin-project/notary-governance/issues/922 for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

**Comment by NDLABS-Leo** [comment]
@Sunnyiscoming 
1、Email has been sent please check.
2、It has been prepared
3、Already part of the data has been stored on ipfs through the assistance of ND, and all the data of the customer is now ready to be stored.
4、Already submitted in the form
5、Submitted

**Comment by NDLABS-Leo** [comment]
![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/104019147/9aa2513d-3960-49a0-89fc-23b42023d8e7)
@Sunnyiscoming 
Hi, I'm using our corporate email to send emails, and I've tried several times to get a message that there is a problem with the domain name of the email address, and it fails to send. So I took a screenshot and put it on github as a proof that it was indeed submitted by us.

**Comment by Sunnyiscoming** [comment]
I think that you are representing for the data owner, you should ask them to send the email with their domain if you are authorized to store the data.
Please let me know if there is any misunderstanding.

**Comment by NDLABS-Leo** [comment]
@Sunnyiscoming 
OK, I will contact the person in charge of AIGC to send the email, please check it out.
Also they have sent me their business licence, which I can send to you if you need it.

**Comment by NDLABS-Leo** [comment]
@Sunnyiscoming 
The customer has been contacted to send the verification through the AIGC suffix email address, please check it.

<img width="651" alt="image" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/104019147/599f0564-041b-451d-b95a-89fb229969f1">

**Comment by Sunnyiscoming** [comment]
Contact email information has not been all completed in the form. Please resubmit the form with complete information.

**Comment by NDLABS-Leo** [comment]
@Sunnyiscoming Whether the standard of review has been adjusted because many sps are reluctant to disclose contact information due to policy and other factors.

**Comment by herrehesse** [comment]
@NDLABS-Leo Most SP's have been cheating and lying and are now hesitant to disclose. Can we assist you with anything @NDLABS-Leo ? We know a large group of miners who happily disclose.

**Comment by NDLABS-Leo** [comment]
@Sunnyiscoming 
Hi, have reconnected and submitted the form, please check. Thank you.

**Comment by NDLABS-Leo** [comment]
Here are the sp's ready for the first batch of storage, with the added emphasis that we'll be contacting new sp's as we store projects, and of course we'll be making github disclosures in advance：

f02031006  USA  Rolling Capital	
f02368282  chengdu  BigMax	
f02226869  jiangxi    LuckyMine	
f02274508   hk        H&W
f02363742   shenzhen  66File

**Comment by herrehesse** [comment]
@NDLABS-Leo I will be contacting the business above, thank you for disclosing. I hope its correct.

**Comment by herrehesse** [comment]
@NDLABS-Leo None of the above have contact information or a website, seems completely fake to me. Also the miners are in the same range, most likely same owner.

**Comment by NDLABS-Leo** [comment]
@herrehesse 
I hope you understand the following facts: For many small and medium-sized service providers (SPs), it's quite normal for them not to have their own websites. Additionally, they are all located in different regions.

@Sunnyiscoming 
Is there any update?

**Comment by herrehesse** [comment]
@NDLABS-Leo I simply do not believe that miner starting with f022*** and f023*** and are all a followup number are in different regions.

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 10PiB

**Expected weekly DataCap usage rate**
> 1PiB

**Client address**
>f1hcstcukrzprglb3xnbkrqu735qp3hc3gybbacwi

**Comment by NDLABS-Leo** [comment]
@Sunnyiscoming What I need to do？

**Comment by NDLABS-Leo** [comment]
@Sunnyiscoming @Kevin-FF-USA @galen-mcandrew

**Comment by NDLABS-Leo** [comment]
@Sunnyiscoming @Kevin-FF-USA @galen-mcandrew

Keep this application open.

**Comment by NDLABS-Leo** [comment]
Keep this application open.

**Comment by sxxfuture-official** [comment]
Review the complete application process above and I will support the first allocation.

**Comment by sxxfuture-official** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecun35oon64hp7imcagvrrgx4oiawhx3d4t37cisnkak5nkz7woso 
#### Address 
> f1hcstcukrzprglb3xnbkrqu735qp3hc3gybbacwi
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f1foiomqlmoshpuxm6aie4xysffqezkjnokgwcecq
#### Id
> d863f7df-bfe4-4c64-9e25-3da70f735f94
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecun35oon64hp7imcagvrrgx4oiawhx3d4t37cisnkak5nkz7woso

**Comment by woshidama323** [comment]
LGTM for any detail disclosed here
Will support this first stage

**Comment by woshidama323** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecuwhnwjdodqyp2nv752752y6f6xvamyfemuemj3bsezcgz4ni2xa 
#### Address 
> f1hcstcukrzprglb3xnbkrqu735qp3hc3gybbacwi
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f12tk3adljauwnd3hjbigpfxb7b7gdlj63p6afwtq
#### Id
> d863f7df-bfe4-4c64-9e25-3da70f735f94
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecuwhnwjdodqyp2nv752752y6f6xvamyfemuemj3bsezcgz4ni2xa

**Comment by NDLABS-Leo** [comment]
Want to keep this application open.

**Comment by NDLABS-Leo** [comment]
keep this application open

**Comment by NDLABS-Leo** [comment]
keep this application open

**Comment by NDLABS-Leo** [comment]
@Sunnyiscoming Hi, please assist us in restarting this request form and we will activate the credit immediately.

**Comment by Sunnyiscoming** [comment]
checker:manualTrigger
