### ISSUE TITLE
[DataCap Application] <NOAA> - <National Blend of Models (NBM)>

### ISSUE THREAD

**Issue by Farrah20gg** [filecoin-project/filecoin-plus-large-datasets#2234]
### Data Owner Name

US National Oceanic and Atmospheric Administration (NOAA) 

### What is your role related to the dataset

Data Preparer

### Data Owner Country/Region

United States

### Data Owner Industry

Environment

### Website

https://www.noaa.gov/

### Social Media

```text
https://www.youtube.com/usnoaagov
https://www.instagram.com/noaa/
https://www.facebook.com/NOAA
https://twitter.com/NOAA
```

### Total amount of DataCap being requested

15PiB

### Expected size of single dataset (one copy)

1083.7TiB

### Number of replicas to store

10

### Weekly allocation of DataCap requested

1PiB

### On-chain address for first allocation

f1jug5en4wnchyloh3au2j4hnvzkjr7wxbf6x73ui

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
The National Blend of Models (NBM) is a nationally consistent and skillful suite of calibrated forecast guidance based on a blend of both NWS and non-NWS numerical weather prediction model data and post-processed model guidance. The goal of the NBM is to create a highly accurate, skillful and consistent starting point for the gridded forecast.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
National Blend of Models (NBM) COG Format
New data notifications for NBM-COG Format, only Lambda and SQS protocols allowed
National Blend of Models (NBM) Grib2 Format
New data notifications for NBM-Grib2 Format, only Lambda and SQS protocols allowed
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### If you are a data preparer. What is your location (Country/Region)

Germany

### If you are a data preparer, how will the data be prepared? Please include tooling used and technical details?

```text
Lotus or Boost
```

### Has this dataset been stored on the Filecoin network before? If so, please explain and make the case why you would like to store this dataset again to the network. Provide details on preparation and/or SP distribution.

```text
As recently joined Filecoin, I'm not entirely sure if this file has been stored by someone else before me. I am a university researcher working on a project involving this data, and it is constantly being updated. I believe that even if it has been stored previously, it doesn't hinder me from storing the latest version on Filecoin.
```

### Please share a sample of the data

```text
https://registry.opendata.aws/noaa-nbm/
aws s3 ls --no-sign-request s3://noaa-nbm-pds/
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

Permanently

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, Africa, North America, South America, Europe, Australia (continent)

### How will you be distributing your data to storage providers

HTTP or FTP server, Shipping hard drives, Lotus built-in data transfer

### How do you plan to choose storage providers

Slack, Big Data Exchange, Partners

### If you already have a list of storage providers to work with, fill out their names and provider IDs below

```text
f02251709	Alan
f01445167	Ray
f02029743	Andrew
f0420161	Tomas
```

### How do you plan to make deals to your storage providers

Boost client, Lotus client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by herrehesse** [comment]
Yeah lets skip this circus please.

f02251709	Alan
f01445167	Ray
f02029743	Andrew
f0420161	        Tomas

Sure buddy. Stop trying to game the FIL+ system.

**Comment by Farrah20gg** [comment]
> Yeah lets skip this circus please.
> 
> f02251709 Alan f01445167 Ray f02029743 Andrew f0420161 Tomas
> 
> Sure buddy. Stop trying to game the FIL+ system.

Hello, I provided the relevant information as requested in the application requirements, including the SP's number and name, so I believe there shouldn't be any issues. 
Additionally, may I know your role in the community? Your comments come across as quite confrontational and uncomfortable.
If you are an official staff member and require more information from me, I'm happy to cooperate.

**Comment by herrehesse** [comment]
As i said, stop scamming the filecoin plus community. You can drop the act.

**Comment by Farrah20gg** [comment]
> As i said, stop scamming the filecoin plus community. You can drop the act.

If my application has any issue I believe the official team will reach out to me, and I'm happy to respond. However, I will not give any words to your comments. It seems from your perspective that any inquiry is considered as scamming. This attitude will not be conducive to the community's development.

**Comment by herrehesse** [comment]
@Farrah20gg Goodluck with that.

**Comment by Farrah20gg** [comment]
Hi @Sunnyiscoming,  I haven't received a response to my application for a long time. Please review it.

**Comment by Sunnyiscoming** [comment]
- Have you prepared enough token for sector pledge?
- You should list Miner ID, Business Entity, Location of sps you will cooperate with.
- Per the https://github.com/filecoin-project/notary-governance/issues/922 for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

**Comment by Farrah20gg** [comment]
> * Have you prepared enough token for sector pledge?

We have already prepared the initial batch of tokens required for the first round of staking. Our partner sps  who collaborate with us will also provide tokens for sector pledge.

> * You should list Miner ID, Business Entity, Location of sps you will cooperate with.

Please check with registration form I have submitted.  @Sunnyiscoming 
<img width="793" alt="Screenshot 2023-11-07 at 11 28 18" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/144674687/199100e0-41fd-4a05-9444-14fa9b1e2ea6">

**Comment by Farrah20gg** [comment]
Hi @Sunnyiscoming , it has been awhile, any update? Thanks

**Comment by herrehesse** [comment]
Yeah lets skip this circus please.

f02251709 Alan
f01445167 Ray
f02029743 Andrew
f0420161 Tomas

Oh wait, we even missed Kevin.

Sure buddy. Stop trying to game the FIL+ system. None of the above businesses are real, neither their locations.

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 15PiB

**Expected weekly DataCap usage rate**
> 1PiB

**Client address**
>f1jug5en4wnchyloh3au2j4hnvzkjr7wxbf6x73ui

**Comment by Farrah20gg** [comment]
> @Farrah20gg if you are looking to store 10 copies, where are the other SPs?


The listed SPs are the initial batch we plan to collaborate with for distribution. As the encapsulation process progresses, we will reach out to more SPs.

**Comment by Farrah20gg** [comment]
@Sunnyiscoming It seems like the application cannot be signed properly. Please check to see if there is a system bug.

**Comment by Sunnyiscoming** [comment]
SP List provided:
[{"providerID": "f02251709",  "City": "Sichuan", "Country": "CN", "SPOrg","DataMax"},
{"providerID": "f01445167",  "City": "HK", "Country": "CN","SPOrg","Fetaverse"},
{"providerID": "f02029743",  "City": "XYZ", "Country": "Singapore","SPOrg","Filefly"},
{"providerID": "f0420161",  "City": "Toronto", "Country": "Canada","SPOrg","Definvest"},
{"providerID": "f02365890",  "City": "HK", "Country": "CN","SPOrg","LRR"},]

**Comment by Casey-PG** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced7b4qnpg6il6tmgsdqladq3scxrjjuki2z7hkc5zcer2oko4djxq 
#### Address 
> f1jug5en4wnchyloh3au2j4hnvzkjr7wxbf6x73ui
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f1d4yb3wags3mtddzesxoo63jv7dmlec3bq4yteni
#### Id
> 9de8aa09-8757-4ed6-bdd4-9a4ab69c2512
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced7b4qnpg6il6tmgsdqladq3scxrjjuki2z7hkc5zcer2oko4djxq

**Comment by BobbyChoii** [comment]
LGTM

**Comment by BobbyChoii** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecunllsdwcltbpp2fzetchwoqxehnzqfk3pqtb4uanukhy6bgtoxm 
#### Address 
> f1jug5en4wnchyloh3au2j4hnvzkjr7wxbf6x73ui
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f1irqs2gmctiv3jcdfwuch7oxvf4ixh3k4b2wc24i
#### Id
> 9de8aa09-8757-4ed6-bdd4-9a4ab69c2512
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecunllsdwcltbpp2fzetchwoqxehnzqfk3pqtb4uanukhy6bgtoxm

**Comment by herrehesse** [comment]
checker:manualTrigger

**Comment by herrehesse** [comment]
Signed by to known abusive notaries. Awaiting CID report.

**Comment by Farrah20gg** [comment]
Please keep it open
