### ISSUE TITLE
[DataCap Application] <Taikr> - <Taikr>

### ISSUE THREAD

**Issue by aws1117** [filecoin-project/filecoin-plus-large-datasets#2235]
### Data Owner Name

taikr

### What is your role related to the dataset

Dataset Owner

### Data Owner Country/Region

China

### Data Owner Industry

Education & Training

### Website

www.taikr.com

### Social Media

```text
www.taikr.com
```

### Total amount of DataCap being requested

15PiB

### Expected size of single dataset (one copy)

880TiB

### Number of replicas to store

10

### Weekly allocation of DataCap requested

1PiB

### On-chain address for first allocation

f1otr5dhjukpibhflqibf7q4b67bosgglz22pvpfa

### Data Type of Application

Public, Open Commercial/Enterprise

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Founded in October 2013, TAC Online (www.taikr.com) is the online education brand of Shanghai Huangtuo Network Technology Co., Ltd. and is the earliest community-based teaching platform to develop IT online education. At present, the website provides high-quality online courses and teaching services based on online courses, open classes, online practical training classes, Taito training camps, online question banks and other products.

At present, the teaching of TEDO is centered on mobile application development and game development courses, which are mainly for those who aspire to devote themselves to the development of Internet technology, or those who are seeking for self-improvement or employment. Through high-quality video courses, live teaching, network team project combat, network class management, online teaching community and other teaching methods, to provide users with convenient (not subject to time and space constraints, more free learning time arrangements, network teaching across the country), professional online teaching courses and services.

Partners: AliCloud, UCloud, Seven Bulls Cloud, Open Source Power, Haozhi.com
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
IT online education videos, VR thematic videos, etc.
```

### Where was the data currently stored in this dataset sourced from

Other

### If you answered "Other" in the previous question, enter the details here

```text
Own storage devices as well as AliCloud,Qiniu Cloud, etc.
```

### If you are a data preparer. What is your location (Country/Region)

None

### Please share a sample of the data

```text
https://pan.baidu.com/s/1oktqFL9PEkV-CrHSFNL2sg 

v3e9
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

1.5 to 2 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, Europe

### How will you be distributing your data to storage providers

HTTP or FTP server

### How do you plan to choose storage providers

Slack, Partners

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by aws1117** [comment]
Add another link to sample data:
https://pan.baidu.com/s/1gyyWwXwHM6MUxFkKoTekOA?pwd=q803
Extract code: q803

**Comment by aws1117** [comment]
![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/142981093/042697e2-c437-4a81-944f-012e1fefa370)
1.Confirmation email has been sent, please check the screenshot.
2.Data will be prepared as per request, via boost or lotus, application data is stored on filecoin network for the first time.
3. we are communicating with the following SPs while contacting more SPs as reserves
f0861588, SDcloud China, USA
f02815456,Xiangyun，USA
f02815438,Maijie，India
f02212982, WHR, shenzhen
f02815451，HZZC, Canada
f039940, Cabrina, China
f02814775,Derek,Amsterdam
f02105377, Bailey, Hongkong
f02812314，Jerry Zhang，USA
4. fil+ registry has been submitted.

@Sunnyiscoming

**Comment by aws1117** [comment]
#2198 will be closed （https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/2198）

**Comment by herrehesse** [comment]
Most of these are lies.

f0861588, SDcloud China, USA
f02815456,Xiangyun，USA
f02815438,Maijie，India
f02212982, WHR, shenzhen
f02815451，HZZC, Canada
f039940, Cabrina, China
f02814775,Derek,Amsterdam
f02105377, Bailey, Hongkong
f02812314，Jerry Zhang，USA

**Comment by Sunnyiscoming** [comment]
The problem with the bot has been dealt with. Please continue commenting on https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/2198.
