### ISSUE TITLE
[DataCap Application] <Zetacube Inc> - <Common Crawl March/April 2020>

### ISSUE THREAD

**Issue by hooonc** [filecoin-project/filecoin-plus-large-datasets#2236]
### Data Owner Name

Common Crawl March/April 2020

### What is your role related to the dataset

Data Preparer

### Data Owner Country/Region

United States

### Data Owner Industry

Other

### Website

https://commoncrawl.org/blog/march-april-2020-crawl-archive-now-available

### Social Media

```text
none
```

### Total amount of DataCap being requested

1PiB

### Expected size of single dataset (one copy)

100TiB

### Number of replicas to store

10

### Weekly allocation of DataCap requested

200TiB

### On-chain address for first allocation

f1zipn5azwmajph7xtuspiac234jyanbrqovlgusa

### Data Type of Application

Slingshot

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Zetacube Inc is a 'Ultra-high-capacity decentralized storage hyper server solution company' in the Web 3.0 era, established to research and commercialize the IPFS storage system, an innovative technology for safely storing huge data in the 4th industrial age. Also, Zetacube Inc is participant in the Slingshot V3, both as DP and SP.
We clamed this dataset on the Slingshot.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
The crawl archive for March/April 2020 is now available! It contains 2.85 billion web pages or 280 TiB of uncompressed content, crawled between March 28th and April 10th. It includes page captures of 1 billion URLs unknown in any of our prior crawl archives.
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### If you are a data preparer. What is your location (Country/Region)

Korea, Republic of

### If you are a data preparer, how will the data be prepared? Please include tooling used and technical details?

```text
My team downloaded this dataset from the AWS cloud and have already finished converting it to CAR files using Singularity. We will make a deal using Boost.
```

### Has this dataset been stored on the Filecoin network before? If so, please explain and make the case why you would like to store this dataset again to the network. Provide details on preparation and/or SP distribution.

```text
no
```

### Please share a sample of the data

```text
https://commoncrawl.org/2020/04/march-april-2020-crawl-archive-now-available/
https://data.commoncrawl.org/crawl-data/CC-MAIN-2020-16/index.html
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

2 to 3 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America

### How will you be distributing your data to storage providers

HTTP or FTP server, IPFS, Shipping hard drives

### How do you plan to choose storage providers

Slack, Big Data Exchange

### If you already have a list of storage providers to work with, fill out their names and provider IDs below

```text
f02005421 Greaterheat Dallas, USA
f01227505 IPFSKDC Incheon, Korea
f01823110 IPFSKDC Jeonju, Korea
f09848 Seamount Tech California, USA
f02368818 Onse Media Gwangju, Korea
```

### How do you plan to make deals to your storage providers

Boost client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1991#issuecomment-1760721662

**Comment by HoonChoi-Zetacube** [comment]
> [#1991 (comment)](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1991#issuecomment-1760721662)

It was my team's first onboarding. We did not know what order to use the Datacap in, we just thought we should finish sealing them in one SP and then save them in another. However, we realized that our idea was wrong, so we stopped onboarding to f01227505 and started storing to other SPs. This data volume is about 100 TiB, and we were only allocated 50 TiB Datacap, so we were unable to recover from our mistake. If we were given more Datacap, we would correct our mistake by storing the data evenly across the five SPs first.

[#2060 (comment)](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/2060#issuecomment-1767832522)
This is my team's second onboarding. We made a mistake, but we are storing data in five SPs. As a result, Storage provider distribution and Data replication are looks healthy.

**Comment by herrehesse** [comment]
@HoonChoi-Zetacube 

The rules have been violated. We can't move forward.

**Comment by HoonChoi-Zetacube** [comment]
> @HoonChoi-Zetacube
> 
> The rules have been violated. We can't move forward.

Do you have the right to say this?
Are you a member of the governance team or a notary? (I know a notary from Dcent as Wijnand Schouten(cryptowhizzard)).
From your comments, it's clear that you have a negative view of SPs and that's why you are so aggressive with all the applications.
Of course I know you work hard for the Filecoin ecosystem. But the governance team and many notaries also work hard in their positions.
I hope you realize that not all SPs are scams and there are many hardworking SPs out there.

**Comment by HoonChoi-Zetacube** [comment]
@galen-mcandrew @raghavrmadya @Kevin-FF-USA @Sunnyiscoming @Carohere
#1991 and #2236 are datasets claimed on the Slingshot, and each data takes over a month to prepare for sealing.
My team violated the Fil Plus rules when onboarding #1991, and I explained why above. However, I can understand even if we no longer receive the datacap for #1991 because we violated the rule.
#2236 is a different dataset, so I filled out this application, but it stopped progressing because of #1991.  
Does this mean that once I make a mistake, I have to leave filecoin? Is this what Fil Plus is aiming for? 
I'm sure this is not positive for the Filecoin ecosystem.
