### ISSUE TITLE
[DataCap Application] Jungbonet 

### ISSUE THREAD

**Issue by bluequintain** [filecoin-project/filecoin-plus-large-datasets#2237]
### Data Owner Name
Jungbonet 

### What is your role related to the dataset
Dataset Owner

### Data Owner Country/Region
South Korea

### Data Owner Industry
IT & Technology Services

### Website
[https://www.jugbo.net/](https://www.jugbo.net/)

### Social Media
[at]kks447468 (twitter)

### Total amount of DataCap being requested
100 TiB

### Expected size of single dataset (one copy)
1 GiB

### Number of replicas to store
1

### Weekly allocation of DataCap requested
3 TiB

### On-chain address for first allocation
f14yjeyzlh27kwb6rwjgel3ge4vo4hmi57tt2t5sq

### Data Type of Application
Private Commercial/Enterprise

### Custom multisig
- [ ] Use Custom Multisig

### Identifier
n/a

### Share a brief history of your project and organization
We started our first Linux hosting in Korea 20 years ago and have been running a stable service ever since. Our customers include very large commercial shopping mall sites ( https://cyso.co.kr https://ygoon.com ) as well as individuals, providing on-premise and cloud infrastructure and technical support.

In this new project, we want to provide our customers with services that are outside of our existing services. 

1. we will test if a commercial backup service is possible using the FILECOIN network.

2. We will test whether it is possible to serve large video lectures or personal media, and if so, we will commercialize it.

Translated with www.DeepL.com/Translator (free version)

### Is this project associated with other projects/ecosystem stakeholders?
No

### If answered yes, what are the other projects/ecosystem stakeholders
n/a

### Describe the data being stored onto Filecoin
Data files, such as your site's sources and images, and customer days, such as video lesson files.

### Where was the data currently stored in this dataset sourced from
My own storage infra

### If you answered "Other" in the previous question, enter the details here
n/a

### If you are a data preparer, what is your location (City and Country)
n/a

### If you are a data preparer, how will the data be prepared? Please include tooling used and technical details?
n/a

### If you are not preparing the data, who will prepare the data?  (Provide name and business)
Your customers have already uploaded their data and have given you their consent to store it on the Filecoin network.

### Has this dataset been stored on the Filecoin network before? If so, please explain and make the case why you would like to store this dataset again to the network. Provide details on preparation and/or SP distribution.
n/a

### Please share a sample of the data
https://cyso.co.kr/
https://ygoon.com/

### Confirm that this is a public dataset that can be retrieved by anyone on the Network
Yes

### If you chose not to confirm, what was the reason
n/a

### What is the expected retrieval frequency for this data
Daily

### For how long do you plan to keep this dataset stored on Filecoin
1.5 to 2 years

### In which geographies do you plan on making storage deals
Asia other than Greater China

### How will you be distributing your data to storage providers
HTTP or FTP server

### How do you plan to choose SP
I don't know yet

### If you answered "Others" in the previous question, what is the tool or platform you plan to use
n/a

### If you already have a list of storage providers to work with, fill out their names and provider IDs below
n/a

### How do you plan to make deals to your storage providers
Lotus client

### If you answered "Others/custom tool" in the previous question, enter the details here
n/a

### Can you confirm that you will follow the Fil+ guideline
Yes

_Application created via [filplus.storage](https://filplus.storage)_

**Comment by kevzak** [comment]
Hi @bluequintain this is an application for the E-Fil+ pathway, please follow the steps here: https://efilplus.super.site/

**Comment by bluequintain** [comment]
@kevzak thank you ~
