### ISSUE TITLE
[DataCap Application]  <jcphysics>

### ISSUE THREAD

**Issue by simida1911** [filecoin-project/filecoin-plus-large-datasets#2239]
### Data Owner Name

jcphysics

### What is your role related to the dataset

Dataset Owner

### Data Owner Country/Region

Singapore

### Data Owner Industry

Education & Training

### Website

http://jcphysics.com/

### Social Media

```text
http://jcphysics.com/
```

### Total amount of DataCap being requested

12PiB

### Expected size of single dataset (one copy)

700TiB

### Number of replicas to store

10

### Weekly allocation of DataCap requested

1PiB

### On-chain address for first allocation

f1ir5vu4qid6jnaesana47h7vw6nkjcmr546me7oy

### Data Type of Application

Public, Open Commercial/Enterprise

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Jcphysics focuses on educational consulting and A level tuition and was founded by Raymond Cai.Since 2009, Mr Cai has helped numerous batches of grateful JC physics students improve their H2 physics grades within a short time. This is achieved by helping students gain an in-depth understanding of the A level physics syllabus as well as recognition of the common misconceptions and difficulties faced in the examinations.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
Educational counseling and A-level tutorials, video courseware, etc.
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### If you are a data preparer. What is your location (Country/Region)

None

### Please share a sample of the data

```text
https://drive.google.com/open?id=1g_Ft4bM4AX0mTbENUNQNglEwfRS3l5kK&usp=drive_fs
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Sporadic

### For how long do you plan to keep this dataset stored on Filecoin

2 to 3 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, Europe, Australia (continent)

### How will you be distributing your data to storage providers

HTTP or FTP server

### How do you plan to choose storage providers

Slack, Filmine, Partners

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by herrehesse** [comment]
Site not working, no SP list, throwaway account, asking for 12PiB. Can we halt right here?

**Comment by Sunnyiscoming** [comment]
- It seems that most data samples are not related with the main business. Are you authorized to store them as public data on the filecoin network, such as BBC videos, TALENT shows, etc.
- The created date of website is October 17, 2023 13:55:01 UTC, can you explain about that?
- Have you prepared enough token for sector pledge?
- Are you a data preparer? What is your previous experience as a data-preparer? List previous applications and client IDs
- How will the data be prepared? Please include tooling used and technical details
- If you are not preparing the data, who will prepare the data?  (Name and Business)
- Has this dataset been stored on Filecoin before? If so, why are you choosing to store it again?
- Best practice for storing large datasets includes ideally, storing it in 3 or more regions, with 4 or more storage provider operators or owners.You should list Miner ID, Business Entity, Location of sps you will cooperate with.
- Per the https://github.com/filecoin-project/notary-governance/issues/922 for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

**Comment by simida1911** [comment]
> * It seems that most data samples are not related with the main business. Are you authorized to store them as public data on the filecoin network, such as BBC videos, TALENT shows, etc.
> * The created date of website is October 17, 2023 13:55:01 UTC, can you explain about that?
> * Have you prepared enough token for sector pledge?
> * Are you a data preparer? What is your previous experience as a data-preparer? List previous applications and client IDs
> * How will the data be prepared? Please include tooling used and technical details
> * If you are not preparing the data, who will prepare the data?  (Name and Business)
> * Has this dataset been stored on Filecoin before? If so, why are you choosing to store it again?
> * Best practice for storing large datasets includes ideally, storing it in 3 or more regions, with 4 or more storage provider operators or owners.You should list Miner ID, Business Entity, Location of sps you will cooperate with.
> * Per the [Modification: Changes required to public open dataset application flow notary-governance#922](https://github.com/filecoin-project/notary-governance/issues/922) for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.


1. The primary data is video courseware related to teaching and training, so it could be movies, it could be video clips, but the content is used as a tool for teaching and training.
2. the website creation date is March 13, 2019, I don't know if it's because of your network problem, it shows up normally on my side ---- Meanwhile, I sent an email to explain in detail. Please check it.
3. yes, 80% pledged coins have been prepared.
4. yes, partner SPs will guide us in data preparation, mainly using official tools boost or lotus.
5. this dataset is stored on filecoin for the first time.
6. details have been submitted in the form.
7. the form has been submitted.

**Comment by simida1911** [comment]
<img width="985" alt="image" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/144753873/eab5b552-cc95-4ae8-b910-07899f11447c">

**Comment by simida1911** [comment]
<img width="782" alt="image" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/144753873/93f28aa3-e9f5-4a5b-808f-b171a08e6a09">

**Comment by simida1911** [comment]
@Sunnyiscoming Can we get some updates?Thanks！

**Comment by kevzak** [comment]
SPs provided - need more info here @simida1911 no contact info provided.

f02814770 |  leo | Australia |
f02814767 | XHS | South Korea | 
f02815448 |  bluesky | USA |
f02815451 | HZZC | Canada | 

How are you storing 10 copies with 4 SPs?

**Comment by simida1911** [comment]
contact info update：
f02814770	leo	ddzyan@163.com   Australia
f02814767	XHS	1504068285@qq.com   South Korea
f02815448	bluesky	danacheng2021@gmail.com  USA
f02815451	HZZC	nibuil0730@163.com  Canada

@kevzak Yes, as the amount of the first round is not very large, these four SPs will be considered for the time being, and more SPs will be added as the progress advances, and I will disclose them in a timely manner before each round of encapsulation, thank you.

**Comment by simida1911** [comment]
> contact info update： f02814770 leo [ddzyan@163.com](mailto:ddzyan@163.com) Australia f02814767 XHS [1504068285@qq.com](mailto:1504068285@qq.com) South Korea f02815448 bluesky [danacheng2021@gmail.com](mailto:danacheng2021@gmail.com) USA f02815451 HZZC [nibuil0730@163.com](mailto:nibuil0730@163.com) Canada
> 
> @kevzak Yes, as the amount of the first round is not very large, these four SPs will be considered for the time being, and more SPs will be added as the progress advances, and I will disclose them in a timely manner before each round of encapsulation, thank you.

contact info update：
f02814770 leo [ddzyan@163.com](mailto:ddzyan@163.com) Australia
f02814767 XHS [1504068285@qq.com](mailto:1504068285@qq.com) South Korea
f02815448 bluesky [danacheng2021@gmail.com](mailto:danacheng2021@gmail.com) USA
f02815451 HZZC [nibuil0730@163.com](mailto:nibuil0730@163.com) Canada

@kevzak Yes, as the amount of the first round is not very large, these four SPs will be considered for the time being, and more SPs will be added as the progress advances, and I will disclose them in a timely manner before each round of encapsulation, thank you.

**Comment by simida1911** [comment]
It seems like it's been a while. Can we move on to the next step?

@Sunnyiscoming Thanks！

**Comment by simida1911** [comment]
What should we do？Can we move on？ @Sunnyiscoming

**Comment by Filplus-govteam** [comment]
Need more info here @simida1911 , 10 copies with no real proof of any SP entities yet.

**Comment by simida1911** [comment]
@kevzak Updated again, stay tuned for SPs sealing, we'll be compliant! Please go on！Thanks！

1. f02814770     leo     ddzyan@163.com    Australia
2. f02814767     XHS      1504068285@qq.com    South Korea
3. f02815448     bluesky      danacheng2021@gmail.com    USA
4. f02815451      HZZC       nibuil0730@163.com   Canada
5. f02809368	Tom Liu	daniel@bowyuan.com    Japan
6. f02812314	Jerry Zhang	wsbopen@outlook.com  USA
7. f02812307	Alice Xu	275624832@qq.com  Singapore
8. f02814775	Derek Cui	zdderek@qq.com   Haarlem, North Holland, NL
9. f02815438	MaiJie	nibuil0730@163.com  India
10. f02815456	Xiangyun	carolinatang315@gmail.com USA

**Comment by Filplus-govteam** [comment]
email confirmations sent to each SP listed to confirm entity and location

**Comment by kevzak** [comment]
Two emails from USA bounced. 

Closing until this SP list get's cleared up.

**Comment by Filplus-govteam** [comment]
Two SP emails from USA bounced, do not exist.

Closing until this SP list get's cleared up.
