### ISSUE TITLE
[DataCap Application] ML studio

### ISSUE THREAD

**Issue by boa0226** [filecoin-project/filecoin-plus-large-datasets#224]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: ML studio
- Website / Social Media: https://www.youtube.com/channel/UCGf9Ac25q1VKKPkQqiGndbQ
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5 PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100 TiB
- On-chain address for first allocation: f3wazxsuhoo4bzkm3c3yftcxnhmq7m5y3fvr47liuujl3yjyjf5ljb4axwon5xgdvtl2cgcmhqnwkp2mhmckkq

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
We are a studio company that provides the best shooting environment. We collaborate with numerous fashion designers, and we share materials on YouTube and various social media platforms.
```

What is the primary source of funding for this project?
```
Our clients’ company (such as Fashion Korea, Korea Broadcast company etc)
```

What other projects/ecosystem stakeholders is this project associated with?
```
Korea Studio Association, Photographers Association, etc.
```

## Use-case details

Describe the data being stored onto Filecoin
```
The data we want to store mainly are fashion shoots and studio shots for various purposes.
```

Where was the data in this dataset sourced from?
```
Mostly Asia, South Korea.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```

https://user-images.githubusercontent.com/97571852/151533204-fdf22542-4d7c-46af-a45f-9cf5a61ab366.mp4

https://user-images.githubusercontent.com/97571852/151534440-02c6669a-ac2f-4d12-9049-c9fc79c27f38.mp4

```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes, it is a public data. 
```

What is the expected retrieval frequency for this data?
```
From time to time.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
Permanently, we'll constantly upload our data and store them for a long time.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Asia, mostly in South Korea. 
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
We are planning to use both online and offline transfer. 
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We will select miners through miners reputation systems like filrep.io. 
```

How will you be distributing deals across storage providers?
```
We will use both online and offline transfer.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Also these companies want to start making deals as soon as possible. So, we can make a deal right after we get DataCap.
```

**Comment by Sunnyiscoming** [comment]
@boa0226 
1.There are only 10 videos on the youtube channel, which is published since 1 year ago. Please provide more proof that you have 5PB data already.
2.Please prove your affiliation with the channel.

**Comment by Sunnyiscoming** [comment]
Hello@boa0226
Is this application valid?

**Comment by galen-mcandrew** [comment]
Closing this for now from no reply. When ready, please reopen or submit a new request here: https://plus.fil.org/ldn-application
