### ISSUE TITLE
[DataCap Application] <Dot well > 

### ISSUE THREAD

**Issue by Cloudyia** [filecoin-project/filecoin-plus-large-datasets#2240]
### Data Owner Name

Dot well

### What is your role related to the dataset

Dataset Owner

### Data Owner Country/Region

China

### Data Owner Industry

Information, Media & Telecommunications

### Website

http://www.dotwell.com/

### Social Media

```text
https://mp.weixin.qq.com/s/uiYTh4Y8GlVIrXHAI0PW8w
```

### Total amount of DataCap being requested

5PiB

### Expected size of single dataset (one copy)

1P

### Number of replicas to store

5

### Weekly allocation of DataCap requested

800TiB

### On-chain address for first allocation

f1ohytnins7faggh565z5vgstur2mnqvq3dmwwy7i

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [X] Use Custom Multisig

### Share a brief history of your project and organization

```text
Shenzhen DotWell Culture Communication Co., Ltd. (DotWell) is a diversified and integrated creative agency.
Services provided by Dotwell:
Live-action shooting/CG animation/KV/brand strategy/new media integrated marketing/MCN/game art & R&D/self-media business cooperation/column packaging/pan-entertainment content creation/H5/scene marketing exhibition display, etc.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
Live shooting video/game video/brand video/product video/corporate video/entertainment video/plane/CG animation/KV/game art & R&D
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### If you are a data preparer. What is your location (Country/Region)

China

### If you are a data preparer, how will the data be prepared? Please include tooling used and technical details?

```text
Both online and offline transfer process are OK.
```

### Has this dataset been stored on the Filecoin network before? If so, please explain and make the case why you would like to store this dataset again to the network. Provide details on preparation and/or SP distribution.

```text
NO.
[f01016847] US
[f01912253] US
[f0866680] Henan Province of China
[f0861588] Henan Province of China
[f0101021] Zhejiang Province of China
[f0147214] Chengdu Province of China
[f02145020] Guandong Province of China
```

### Please share a sample of the data

```text
(http://www.dotwell.com/work/#section2) you can watch the videos from us in the link.
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

1 to 1.5 years

### In which geographies do you plan on making storage deals

Greater China, North America

### How will you be distributing your data to storage providers

HTTP or FTP server, IPFS

### How do you plan to choose storage providers

Slack, Partners

### If you already have a list of storage providers to work with, fill out their names and provider IDs below

```text
[f01016847] US
[f01912253] US
[f0866680] Genesis 
[f0861588] SDCloud sdcloud@zcpow.cn
[f0101021] Zhejiang Province of China
[f0147214] Chengdu Province of China
[f02145020] Guandong Province of China  harry@lianliwork.com
```

### How do you plan to make deals to your storage providers

Boost client, Lotus client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
- Could you send an email to filplus-app-review@fil.org with your official domain in order to confirm your identity? Email name should includes the issue id #2240.
- Per the https://github.com/filecoin-project/notary-governance/issues/922 for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.
- The Miner IDs and entity name and locaiton should be posted here.

**Comment by Cloudyia** [comment]
> * Could you send an email to [filplus-app-review@fil.org](mailto:filplus-app-review@fil.org) with your official domain in order to confirm your identity? Email name should includes the issue id [[DataCap Application] <Dot well >  #2240](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/2240).
> * Per the [Modification: Changes required to public open dataset application flow notary-governance#922](https://github.com/filecoin-project/notary-governance/issues/922) for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.
> * The Miner IDs and entity name and locaiton should be posted here.

- The email has been sent, pls check it, thank you.
- Fil+ registration form has been done
- [f01016847] US
[f01912253] US
[f0866680] Genesis 
[f0861588] SDCloud sdcloud@zcpow.cn
[f0101021] Zhejiang Province of China
[f0147214] Chengdu Province of China
[f02145020] Guandong Province of China  harry@lianliwork.com
The current SPs information is here.
Thanks so much.

**Comment by Cloudyia** [comment]
going on

**Comment by Sunnyiscoming** [comment]
Contact email information has not been all completed in the form. Please resubmit the form with complete information.

**Comment by Cloudyia** [comment]
> Contact email information has not been all completed in the form. Please resubmit the form with complete information.

<img width="521" alt="image" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/116794494/e896b2d6-63e1-4641-bf14-df68c483f9e6">
The form has been updated and please check it. Thank you so much, have a nice day.

**Comment by Sunnyiscoming** [comment]
![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/105098820/ee4dd49b-b901-4a9a-a69b-ce61651a76df)
Please provide all contact email info in the form.

**Comment by Cloudyia** [comment]
> ![image](https://user-images.githubusercontent.com/105098820/280534184-ee4dd49b-b901-4a9a-a69b-ce61651a76df.png) Contact name and email information has not been all completed in the form. Please resubmit the form with complete information.

![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/116794494/ac1f42d6-f508-478d-9b6a-f924da80631f)
 Updated again.

**Comment by Cloudyia** [comment]
@Sunnyiscoming  Please check the form again.

**Comment by Cloudyia** [comment]
@Sunnyiscoming @Kevin-FF-USA  Hope to update here. Thanks.

**Comment by Cloudyia** [comment]
@Sunnyiscoming  Anyone here?

**Comment by Filplus-govteam** [comment]
email sent to SPs on list

**Comment by Filplus-govteam** [comment]
emails returned bounced, SPs not able to be confirmed

**Comment by Chuangshi1** [comment]
> > ![image](https://user-images.githubusercontent.com/105098820/280534184-ee4dd49b-b901-4a9a-a69b-ce61651a76df.png) Contact name and email information has not been all completed in the form. Please resubmit the form with complete information.
> 
> ![image](https://private-user-images.githubusercontent.com/116794494/280575025-ac1f42d6-f508-478d-9b6a-f924da80631f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEzMzE2NTEsIm5iZiI6MTcwMTMzMTM1MSwicGF0aCI6Ii8xMTY3OTQ0OTQvMjgwNTc1MDI1LWFjMWY0MmQ2LWY1MDgtNDc4ZC05YjZhLWY5MjRkYTgwNjMxZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMTMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTEzMFQwODAyMzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NzFmZTEwNTNjYjZhZDk0YjE3Mjk4MzNlYWFjMTYzOGI2NjQ4Y2Q3YmYwNzFiZWRiM2FhZWNkOTM0MDYxNmEwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.3e3zHl8_hXztbm7m5g-Wa0roTQTkKgMph1pJql-RJpI) Updated again.

@Filplus-govteam These are the SPs offered information. I think it can be confirmed. Hope you can send the check email  to the following email address. We will contact them to confirmed. Thanks.

**Comment by Cloudyia** [comment]
> @Filplus-govteam ![image](https://private-user-images.githubusercontent.com/116794494/286862189-06729805-be11-428e-b8b5-d36453de1169.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM2NjU1NzgsIm5iZiI6MTcwMzY2NTI3OCwicGF0aCI6Ii8xMTY3OTQ0OTQvMjg2ODYyMTg5LTA2NzI5ODA1LWJlMTEtNDI4ZS1iOGI1LWQzNjQ1M2RlMTE2OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyN1QwODIxMThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZTA2ZmRiM2RjOTkyNzNlZGMwMjNiNTVmMzRkOTJjNWM1ZGQwNTA1ZjBmYmZlYjM5MjI4YmFhZWU3OWE5M2M5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.0jiacY5HsexfTfbyS047Uwf2d-12j71IVPvn7m5nY68) Sorry for the late reply. This is the confirmed email from the SP. Hope you can check the email. Thanks a lot.

Please approve the LDN and reopen it.

**Comment by Cloudyia** [comment]
@Sunnyiscoming Can you help us?

**Comment by Cloudyia** [comment]
@Filplus-govteam @Sunnyiscoming @Kevin-FF-USA The application need to get the answer that it is approved or not. It waited for more than 2 months. Appreciate!

**Comment by Cloudyia** [comment]
@Filplus-govteam @Sunnyiscoming @Kevin-FF-USA  Hope get your approve.

**Comment by Filplus-govteam** [comment]
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/2240

**Comment by Filplus-govteam** [comment]
@Cloudyia the application is open, you can proceed

**Comment by Cloudyia** [comment]
> @Cloudyia the application is open, you can proceed

@Filplus-govteam  I don't know who can help proceed. No one check the application.

**Comment by kevzak** [comment]
you can post for notary help in # fil-plus-application-review channel in Filecoin slack

**Comment by Cloudyia** [comment]
> you can post for notary help in # fil-plus-application-review channel in Filecoin slack

Thanks Kevzak! It need Fil + official staff to approve the application.   It hasn't reached the stage where it needs a notary's signature.

**Comment by Cloudyia** [comment]
@Sunnyiscoming

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 5PiB

**Expected weekly DataCap usage rate**
> 800TiB

**Client address**
>f1ohytnins7faggh565z5vgstur2mnqvq3dmwwy7i

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 5PiB

**Expected weekly DataCap usage rate**
> 800TiB

**Client address**
>f1ohytnins7faggh565z5vgstur2mnqvq3dmwwy7i

**Comment by Sunnyiscoming** [comment]
SP List provided:
[{"providerID": "f02216385","City": "HK", "Country": "CN", "SPOrg","H&B"},
{"providerID": "f0147214","City": "Sichuan", "Country": "CN", "SPOrg","lianli"},
{"providerID": "f02145020","City": "Sichuan", "Country": "CN", "SPOrg","lianli"},
{"providerID": "f0168588","City": "XYZ", "Country": "US", "SPOrg","SDC"},
{"providerID": "f0109903","City": "XYZ", "Country": "CN", "SPOrg","Fin"},]

**Comment by Chuangshi1** [comment]
Please contact @Sunnyiscoming  It has not been triggered. So i can't sign. Sorry!

**Comment by Sunnyiscoming** [comment]
“Expected size of single dataset (one copy)” the client put in “1P”, but it should be “1PiB”.
You can correct it.

**Comment by Cloudyia** [comment]
> “Expected size of single dataset (one copy)” the client put in “1P”, but it should be “1PiB”. You can correct it.

Thanks so much. It has been corrected. @Sunnyiscoming

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 5PiB

**Expected weekly DataCap usage rate**
> 800TiB

**Client address**
>f1ohytnins7faggh565z5vgstur2mnqvq3dmwwy7i

**Comment by Sunnyiscoming** [comment]
![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/105098820/80f2496c-5f2d-476b-b7a1-16eedf693612)
You need to uncheck  Use Custom Multisig.

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 5PiB

**Expected weekly DataCap usage rate**
> 800TiB

**Client address**
>f1ohytnins7faggh565z5vgstur2mnqvq3dmwwy7i
