### ISSUE TITLE
[DataCap Application] TopBlocks - Allen Institute for Neural Dynamics

### ISSUE THREAD

**Issue by jevticgallonsd1466** [filecoin-project/filecoin-plus-large-datasets#2241]
### Data Owner Name

Allen Institute for Neural Dynamics (AIND)

### What is your role related to the dataset

Storage provider filling out application on behalf of the data owner

### Data Owner Country/Region

United States

### Data Owner Industry

Life Science / Healthcare

### Website

https://registry.opendata.aws/allen-nd-open-data/

### Social Media

```text
https://registry.opendata.aws/allen-nd-open-data/
```

### Total amount of DataCap being requested

10PiB

### Expected size of single dataset (one copy)

750TiB

### Number of replicas to store

10

### Weekly allocation of DataCap requested

200TiB

### On-chain address for first allocation

f1kkhk432dpbskfbk2liusdeg6ztflxgotksmjumy

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
We are topblocks team - https://www.topblocks.io
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
The Allen Institute for Neural Dynamics (AIND) is committed to FAIR, Open, and Reproducible science. We therefore share all of the raw and derived data we collect publicly with rich metadata, including preliminary data collected during methods development, as near to the time of collection as possible.
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### If you are a data preparer. What is your location (Country/Region)

United States

### If you are a data preparer, how will the data be prepared? Please include tooling used and technical details?

```text
Use singularity to generate car.
```

### Has this dataset been stored on the Filecoin network before? If so, please explain and make the case why you would like to store this dataset again to the network. Provide details on preparation and/or SP distribution.

```text
No
```

### Please share a sample of the data

```text
https://registry.opendata.aws/allen-nd-open-data/

aws s3 ls --no-sign-request s3://aind-open-data/


aws s3 ls --no-sign-request --recursive --human-readable --summarize s3://aind-open-data/ | grep "Total Size:"
Total Size: 2.3 PiB
```
```


### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### If you chose not to confirm, what was the reason

_No response_

### What is the expected retrieval frequency for this data

Sporadic

### For how long do you plan to keep this dataset stored on Filecoin

Less than 1 year

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, Europe

### How will you be distributing your data to storage providers

HTTP or FTP server

### How do you plan to choose storage providers

Slack, Big Data Exchange, Partners

### If you answered "Others" in the previous question, what is the tool or platform you plan to use

_No response_

### If you already have a list of storage providers to work with, fill out their names and provider IDs below

```text
|topblocks|f02301,f03223,f0143858,f0240185|Santa Clara(US)|
|treal|f02032191|ZheJiang(CN)|
|STRAITDEER PTE. LTD.|f02093396, f02259777|Singapore|
|Hainan future cloud Technology Co., LTD|f02519323|NingXia(CN)|
|guanxinlian|f02808800|ZheJiang(CN)|
```

### How do you plan to make deals to your storage providers

Boost client, Lotus client, Singularity

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
- Have you prepared enough token for sector pledge?
- Per the https://github.com/filecoin-project/notary-governance/issues/922 for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

**Comment by jevticgallonsd1466** [comment]
> * Have you prepared enough token for sector pledge?
> * Per the [Modification: Changes required to public open dataset application flow notary-governance#922](https://github.com/filecoin-project/notary-governance/issues/922) for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.


>> yes
>> From has been submitted

**Comment by herrehesse** [comment]
please add the contact information of the SP entities you are working with to store copies of the data.

**Comment by jevticgallonsd1466** [comment]
> please add the contact information of the SP entities you are working with to store copies of the data.

Sorry. The contact information for SP has already been submitted in the form. I believe it should not be displayed here.

**Comment by herrehesse** [comment]
It should. Otherwise we will not accept your LDN.

**Comment by Aaron01230** [comment]
According to the information above , i will support this round.

**Comment by jevticgallonsd1466** [comment]
![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/135803746/2d1912f2-12d5-4416-9e76-54095dba8cf0)
![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/135803746/e17c906a-865f-40ca-9b8a-5626e58ac6c3)

@Sunnyiscoming  @jbesraa   
Hello, Notaries is unable to sign this ldn, this ldn cannot be located.
Could you please assist in resolving this issue?

**Comment by jevticgallonsd1466** [comment]
@kevzak  Could you please me, please!!!!

**Comment by Aaron01230** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceasvpvf2laajypig27etkap6fl5nlhiqqv3lmcmzkfy7iockmjzzg 
#### Address 
> f1kkhk432dpbskfbk2liusdeg6ztflxgotksmjumy
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1xrnysd4gimg64d4l6qi7ulzwwq22c6vfg6lpw3i
#### Id
> fa8e0c30-6a47-41fc-be4d-c97c61f138f9
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceasvpvf2laajypig27etkap6fl5nlhiqqv3lmcmzkfy7iockmjzzg

**Comment by zcfil** [comment]
Looking good, start your data storage

**Comment by zcfil** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacechoqte2lnkebol6vaqmxeorlawe2bwz5aiq3qimkbc4falioz6w4 
#### Address 
> f1kkhk432dpbskfbk2liusdeg6ztflxgotksmjumy
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1cjzbiy5xd4ehera4wmbz63pd5ku4oo7g52cldga
#### Id
> fa8e0c30-6a47-41fc-be4d-c97c61f138f9
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacechoqte2lnkebol6vaqmxeorlawe2bwz5aiq3qimkbc4falioz6w4

**Comment by herrehesse** [comment]
checker:manualTrigger

**Comment by jevticgallonsd1466** [comment]
checker:manualTrigger

**Comment by Sunnyiscoming** [comment]
f02093396, f02259777| STRAITDEER PTE. LTD. | Singapore |
f02301,f03223,f0143858,f0240185 | topblocks | Santa Clara(US) |
f02808800 |NA | ZheJiang(CN) |
f02519323 |Hainan future cloud Technology Co., LTD | NingXia(CN) |
f02032191 | NA | ZheJiang(CN) |

SP List provided:
[{"providerID": "f02093396",  "City": "XYZ", "Country": "Singapore", "SPOrg","STRAITDEER PTE. LTD."},
{"providerID": "f02259777",  "City": "XYZ", "Country": "Singapore", "SPOrg","STRAITDEER PTE. LTD."},
{"providerID": "f02301",  "City": "Santa Clara", "Country": "US", "SPOrg","topblocks"},
{"providerID": "f03223",  "City": "Santa Clara", "Country": "US", "SPOrg","topblocks"},
{"providerID": "f0143858",  "City": "Santa Clara", "Country": "US", "SPOrg","topblocks"},
{"providerID": "f0240185",  "City": "Santa Clara", "Country": "US", "SPOrg","topblocks"},
{"providerID": "f02808800",  "City": "ZheJiang", "Country": "CN", "SPOrg","XYZ"},
{"providerID": "f02519323",  "City": "NingXia", "Country": "CN", "SPOrg","Hainan future cloud Technology Co., LTD"},
{"providerID": "f02032191",  "City": "ZheJiang", "Country": "CN","SPOrg","XYZ"},]

**Comment by herrehesse** [comment]
checker:manualTrigger

**Comment by herrehesse** [comment]
![Screenshot 2023-12-05 at 09 44 09](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/70132857/72584c87-a6f7-4d8e-b707-e6e0ac06198c)

All IP's are under VPN. Most likely self-dealing much past 20% as allowed. Suggest explaining, proving location, or closing this LDN.

**Comment by Filplus-govteam** [comment]
checker:manualTrigger

**Comment by Filplus-govteam** [comment]
SPs taking deals not matching SPs provided
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/2241#issuecomment-1785682540

Please provide updated SP Entity and location proof and send to filplus.govteam@gmail.com. Closing until we have some clarity on all SPs
