### ISSUE TITLE
[DataCap Application] <Jiecheng>-< Customer disaster recovery data> - [e-fil]

### ISSUE THREAD

**Issue by gaopingjiecheng** [filecoin-project/filecoin-plus-large-datasets#2242]
### Data Owner Name

Jiecheng

### What is your role related to the dataset

Dataset Owner

### Data Owner Country/Region

China

### Data Owner Industry

IT & Technology Services

### Website

N/A

### Social Media

```text
N/A
```

### Total amount of DataCap being requested

5PiB

### Expected size of single dataset (one copy)

650T

### Number of replicas to store

8

### Weekly allocation of DataCap requested

800TiB

### On-chain address for first allocation

f1pbqgoobpqw5fvuvabhocsy2rjftpvdq72qyozey

### Data Type of Application

Private Commercial/Enterprise

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Hangzhou Jiecheng Computer Co., Ltd. was founded in 2000 in Hangzhou City, West Lake District, has been established for 23 years, is the oldest system integration service provider, is committed to providing users with servers, storage, network security disaster recovery and backup, and other related applications of technical support and deployment services. 
With the rapid development of computer technology, each enterprise is using a large number of computers to deal with their core data, these data are the top priority of the production and operation of enterprises, the core of life. But with hard disc failure, human error, application logic errors, natural disasters and other reasons to bring system downtime or data loss, so it is essential to do backup protection of these important data.
After the backup, you can achieve real-time synchronisation of dual databases, which can ensure real-time consistency of dual real data, if the production database fails, the backup database server at any time to enable the main data server, no longer need the media recovery process.
 The company has a first-class management and technical team, trust, skills, experience, quality and other core elements of the company's most important values, relying on the mutual support of partners, to provide users with a full range of high-performance, highly reliable, professional level of first-class IT services, and to become a trusted long-term partner of the customer.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
The data to be stored is about Jiecheng's internal corporate data, as well as data to help customers with disaster recovery backup storage.
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### If you are a data preparer. What is your location (Country/Region)

China

### If you are a data preparer, how will the data be prepared? Please include tooling used and technical details?

```text
We store our data in our own storage devices. We will transfer to these SPs online when they are ready. alternatively we can mail the hard drives if the sought sp supports hard drive transfer.
```

### Has this dataset been stored on the Filecoin network before? If so, please explain and make the case why you would like to store this dataset again to the network. Provide details on preparation and/or SP distribution.

```text
No. This is because we changed the underlying storage solution to distributed storage, which is used to save some of the storage costs.
```

### Please share a sample of the data

```text
https://drive.google.com/file/d/1pI7hVL2MjfLAjq7t5rE5VTjNMt9G0qrF/view?usp=sharing

https://drive.google.com/file/d/1oKEeIQt8VczNgtr7eHOvA_uYBKyMh-bY/view?usp=sharing

https://drive.google.com/file/d/1BHmO4ZLGjobHI4r7Jh2XsiS8RIXZo7Ze/view?usp=sharing

https://drive.google.com/file/d/10jnQBSU4t8WOQOU21Qkr-1eMyInKOizk/view?usp=sharing

https://drive.google.com/file/d/1Nl87iv6lY0GC0OrQhDBOxOrl_-Q5tYNp/view?usp=sharing

https://drive.google.com/file/d/1LgtAvik_vCXJwLCn8K14iZlte8Ujo5lQ/view?usp=sharing

https://drive.google.com/file/d/1Bi9BNY7uqufhKipEC0i2_lp9UybwMmsg/view?usp=sharing

https://drive.google.com/file/d/1SVI-Rryf5bXVTzimW6Xq9aVIJNTLMflD/view?usp=sharing

https://drive.google.com/file/d/1C1PJGNa6YtG1sIGvf_pYDZgMaOxebJ4f/view?usp=sharing

https://drive.google.com/file/d/1SLj29O1JjMmHzDjwxoFLrdn3x-oT360z/view?usp=sharing

https://drive.google.com/file/d/1WV1s4H8QFx-PmGlDQ-qC63V3VlWODRy8/view?usp=sharing

https://drive.google.com/file/d/1NXShZzoH5dGo4y7vLT4I4LWGJbh-4H2c/view?usp=sharing

https://drive.google.com/file/d/1Z4ZVGJR_RvCjs2kixGbHwl30pIFAQakH/view?usp=sharing

https://drive.google.com/file/d/1I3aU_lBtO0rJgC6_cg078vUuR-f3KrDy/view?usp=sharing
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

1.5 to 2 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America

### How will you be distributing your data to storage providers

HTTP or FTP server, IPFS, Shipping hard drives

### How do you plan to choose storage providers

Slack, Big Data Exchange, Partners

### How do you plan to make deals to your storage providers

Boost client, Lotus client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by herrehesse** [comment]
New acount 5 PIB - can we close?

**Comment by gaopingjiecheng** [comment]
Keep it open, please tell me how to proceed?
