### ISSUE TITLE
[DataCap Application] <GOLF SPOT> 

### ISSUE THREAD

**Issue by yazalulu** [filecoin-project/filecoin-plus-large-datasets#2245]
### Data Owner Name

GOLF SPOT

### What is your role related to the dataset

Dataset Owner

### Data Owner Country/Region

Singapore

### Data Owner Industry

Arts & Recreation

### Website

https://instagram.com/golf_spot.sg?igshid=OGQ5ZDc2ODk2ZA==

### Social Media

```text
https://instagram.com/golf_spot.sg?igshid=OGQ5ZDc2ODk2ZA==

www.tiktok.com/@golfspotsg?_t=8XoHqTtM7Lm&_r=1
```

### Total amount of DataCap being requested

10PiB

### Expected size of single dataset (one copy)

600TiB

### Number of replicas to store

10

### Weekly allocation of DataCap requested

1PiB

### On-chain address for first allocation

f1u6xzzex3krtfkwvbjqus6ejpx3c5yhuqqji5hri

### Data Type of Application

Public, Open Commercial/Enterprise

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Golf Spot Cafe & Bistro business registration number UEN202201912W, our mission is to explore and share the beauty of the golf course, with instagram and tiktok (see social media for more details), we have accumulated a lot of loyal followers, and throughout the process we have recorded and preserved a lot of beautiful moments and a constant flow of data generated.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
Data on dining, food and video shooting on the golf course
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### If you are a data preparer. What is your location (Country/Region)

None

### Please share a sample of the data

```text
https://www.dropbox.com/scl/fo/786zgeprfn7mr51zx0y5r/h?dl=0
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Sporadic

### For how long do you plan to keep this dataset stored on Filecoin

2 to 3 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, Europe, Australia (continent)

### How will you be distributing your data to storage providers

HTTP or FTP server

### How do you plan to choose storage providers

Slack, Partners

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by herrehesse** [comment]
New account, 10PiB, lets close this immediately.

**Comment by Sunnyiscoming** [comment]
No permission to view data samples.
![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/105098820/abae93e4-f1cc-4b73-b350-ee109c0dfac5)
Social media accounts are unavailable, please check it.

**Comment by herrehesse** [comment]
Nothing to check here, please close.

**Comment by yazalulu** [comment]
![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/146307018/c8a76c18-1644-46f0-bfe7-38a0153d24d3)

Tiktok can be opened normally as shown in the picture, please check your network.

**Comment by yazalulu** [comment]
![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/146307018/aff4bc1b-6c52-46eb-b68f-b0a4e92195ad)
The sample data is also fine, but you need to access it with a google account or follow the instructions, thanks.

**Comment by herrehesse** [comment]
Please close. Nothing about your application shouts "fine".

**Comment by Sunnyiscoming** [comment]
I have requested permissions to check data samples. But I can not check it now.

**Comment by herrehesse** [comment]
Close this LDN please.

**Comment by yazalulu** [comment]
> I have requested permissions to check data samples. But I can not check it now.

Sorry, just got noticed. Let me see.

**Comment by yazalulu** [comment]
> 我已请求检查数据样本的权限。但我现在无法检查。

https://drive.google.com/drive/folders/1h1QRio9IjrJui6vDYa_l3PwBl5J2zgf8

**Comment by yazalulu** [comment]
@Sunnyiscoming Can we move on to the next step, please?

**Comment by yazalulu** [comment]
> @Sunnyiscoming Can we move on to the next step, please?

@Sunnyiscoming Can we move on to the next step, please?

**Comment by Filplus-govteam** [comment]
@yazalulu who is preparing the data? This username has no record of using Filecoin. You didn't answer all questions in the application. Closing until updated.
