### ISSUE TITLE
[DataCap Application] FILTAKES - UK Biobank Pan-Ancestry Summary Statistics

### ISSUE THREAD

**Issue by filtakes** [filecoin-project/filecoin-plus-large-datasets#2247]
### Data Owner Name

Analytic and Translational Genetics Unit, Massachusetts General Hospital and the Broad Institute

### What is your role related to the dataset

Data Preparer

### Data Owner Country/Region

United Kingdom

### Data Owner Industry

Life Science / Healthcare

### Website

https://pan.ukbb.broadinstitute.org/

### Social Media

```text
http://www.filtakes.com
```

### Total amount of DataCap being requested

2PiB

### Expected size of single dataset (one copy)

143.5 TiB

### Number of replicas to store

10

### Weekly allocation of DataCap requested

500TiB

### On-chain address for first allocation

f1l7b3sko5hqtpsb3pwjqqymh3ssoslucafzhd2jy

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Founded in 2021, filtakes is a technology company focusing on distributed storage technology, data computing and intelligent AI. We provide data storage and technical support services to various companies and have complete industry solutions.
 
We provide customers with technical services such as data collection and download, data storage, and big data model training to help customers gain deep insights from data and promote business decision-making and innovation.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
https://registry.opendata.aws/broad-pan-ukb/
UK Biobank Pan-Ancestry Summary Statistics
A multi-ancestry analysis of 7,221 phenotypes using a generalized mixed model association testing framework, spanning 16,119 genome-wide association studies. We provide standard meta-analysis across all populations and with a leave-one-population-out approach for each trait. The data are provided in tsv format (per phenotype) and Hail MatrixTable (all phenotypes and variants). Metadata is provided in phenotype and variant manifests.
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### If you are a data preparer. What is your location (Country/Region)

China

### If you are a data preparer, how will the data be prepared? Please include tooling used and technical details?

```text
Singularity or go-graphsplit
```

### Has this dataset been stored on the Filecoin network before? If so, please explain and make the case why you would like to store this dataset again to the network. Provide details on preparation and/or SP distribution.

```text
According to my investigation, no organization or individual currently stores this data on the filecoin network.
```

### Please share a sample of the data

```text
https://registry.opendata.aws/broad-pan-ukb/
aws s3 ls --no-sign-request --recursive --human-readable --summarize s3://pan-ukb-us-east-1/
Total Size: 143.5 TiB
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

1.5 to 2 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, Europe

### How will you be distributing your data to storage providers

HTTP or FTP server, Shipping hard drives, Lotus built-in data transfer

### How do you plan to choose storage providers

Slack, Partners

### If you already have a list of storage providers to work with, fill out their names and provider IDs below

```text
f01153105    Fujian mine world Technology Co., Ltd  Japan
f01946104   SiChuan ZhuaYin Technology Co., Ltd  China
f01985775   GREATER HEAT  US
f02311133    NKD Tech  HK
f01660795   Shenzhen Brilliance Technology Co., LTD  China

We will update here as we reach out to more SPs
```

### How do you plan to make deals to your storage providers

Boost client, Singularity

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by filtakes** [comment]
@Sunnyiscoming  As required by the notary, I will apply separately!

**Comment by Sunnyiscoming** [comment]
- Could you send an email to filplus-app-review@fil.org with your official domain in order to confirm your identity? Email name should includes the issue id #2247.
- Have you prepared enough token for sector pledge?
- Per the https://github.com/filecoin-project/notary-governance/issues/922 for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

**Comment by filtakes** [comment]
> * Could you send an email to [filplus-app-review@fil.org](mailto:filplus-app-review@fil.org) with your official domain in order to confirm your identity? Email name should includes the issue id [[DataCap Application] FILTAKES - UK Biobank Pan-Ancestry Summary Statistics #2247](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/2247).
> * Have you prepared enough token for sector pledge?
> * Per the [Modification: Changes required to public open dataset application flow notary-governance#922](https://github.com/filecoin-project/notary-governance/issues/922) for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

@Sunnyiscoming 
1、Our official email contact@filtakes.com has tried sending emails to filplus-app-review@fil.org many times, but it keeps prompting: **Name service error for name=fil.org type=MX: Host not found**. We tested sending to other mailboxes to confirm that there is no problem with our mailbox.
2、Yes, we have enough tokens
3、The form has been completed

**Comment by filtakes** [comment]
Dear @Sunnyiscoming, any update here?

**Comment by Sunnyiscoming** [comment]
I have tried to send email and successed. You can use other email address and send with the business license.

**Comment by filtakes** [comment]
> I have tried to send email and successed. You can use other email address and send with the business license.
@Sunnyiscoming  We tried using a personal business email and the message was sent successfully, please confirm it!
![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/105106429/707b1e2a-6682-4379-b0b4-c02e186b4d6e)

**Comment by filtakes** [comment]
@Sunnyiscoming Have you received our email? and can our application proceed to the next step?

**Comment by filtakes** [comment]
Dear @Sunnyiscoming , we are waiting for your reply, it is very much appreciated.

**Comment by filtakes** [comment]
@galen-mcandrew @raghavrmadya @Kevin-FF-USA @Sunnyiscoming  any update here?

**Comment by Filplus-govteam** [comment]
Please provide SP entities and contacts. You are planning 10 copies, there are 4 names listed. Closing until updated.
