### ISSUE TITLE
[DataCap Application] FILTAKES - NASA Space Biology Open Science Data Repository (OSDR)

### ISSUE THREAD

**Issue by filtakes** [filecoin-project/filecoin-plus-large-datasets#2248]
### Data Owner Name

NASA

### What is your role related to the dataset

Data Preparer

### Data Owner Country/Region

United States

### Data Owner Industry

Life Science / Healthcare

### Website

https://osdr.nasa.gov

### Social Media

```text
http://www.filtakes.com
https://twitter.com/NASA
```

### Total amount of DataCap being requested

2PiB

### Expected size of single dataset (one copy)

133TiB

### Number of replicas to store

10

### Weekly allocation of DataCap requested

500TiB

### On-chain address for first allocation

f1l7b3sko5hqtpsb3pwjqqymh3ssoslucafzhd2jy

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Founded in 2021, filtakes is a technology company focusing on distributed storage technology, data computing and intelligent AI. We provide data storage and technical support services to various companies and have complete industry solutions.
 
We provide customers with technical services such as data collection and download, data storage, and big data model training to help customers gain deep insights from data and promote business decision-making and innovation.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
https://registry.opendata.aws/nasa-osdr/
NASA Space Biology Open Science Data Repository (OSDR)
NASA’s Space Biology Open Science Data Repository (OSDR) introduces a one-stop site where users can explore and contribute a variety of NASA open science biological data. This site consolidates data from the Ames Life Sciences Data Archive (ALSDA) and GeneLab and includes information about the broader NASA Open Science and Open Data initiatives, all at one centralized location. Our mission is to maximize the utilization of the valuable biological research resources and enable new discoveries.
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### If you are a data preparer. What is your location (Country/Region)

China

### If you are a data preparer, how will the data be prepared? Please include tooling used and technical details?

```text
Singularity or go-graphsplit
```

### Has this dataset been stored on the Filecoin network before? If so, please explain and make the case why you would like to store this dataset again to the network. Provide details on preparation and/or SP distribution.

```text
According to my investigation, no organization or individual currently stores this data on the filecoin network.
```

### Please share a sample of the data

```text
https://registry.opendata.aws/nasa-osdr/
aws s3 ls --no-sign-request --recursive --human-readable --summarize s3://nasa-osdr/
Total Size: 133 TiB
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

1.5 to 2 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, Europe

### How will you be distributing your data to storage providers

HTTP or FTP server, Shipping hard drives, Lotus built-in data transfer

### How do you plan to choose storage providers

Slack, Partners

### If you already have a list of storage providers to work with, fill out their names and provider IDs below

```text
f01153105    Fujian mine world Technology Co., Ltd  Japan
f01946104   SiChuan ZhuaYin Technology Co., Ltd  China
f01985775   GREATER HEAT  US
f02311133    NKD Tech  HK
f01660795   Shenzhen Brilliance Technology Co., LTD  China

We will update here as we reach out to more SPs
```

### How do you plan to make deals to your storage providers

Boost client, Singularity

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by filtakes** [comment]
@Sunnyiscoming As required by the notary, I applied for the dataset separately. https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/2246#issuecomment-1773697023

**Comment by Sunnyiscoming** [comment]
- Have you prepared enough token for sector pledge?
- Per the https://github.com/filecoin-project/notary-governance/issues/922 for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

**Comment by filtakes** [comment]
> * Have you prepared enough token for sector pledge?
> * Per the [Modification: Changes required to public open dataset application flow notary-governance#922](https://github.com/filecoin-project/notary-governance/issues/922) for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

@Sunnyiscoming 
1、Yes, we have enough tokens
2、The form has been completed

**Comment by filtakes** [comment]
> The Miner IDs and entity name and locaiton of no less than 4 sps should be posted here.

@Sunnyiscoming  
f01153105    Fujian mine world Technology Co., Ltd  Japan
f01946104   SiChuan ZhuaYin Technology Co., Ltd  China
f01985775   GREATER HEAT  US
f02311133    NKD Tech  HK
f01660795   Shenzhen Brilliance Technology Co., LTD  China

**Comment by filtakes** [comment]
Hi @Sunnyiscoming  Can our application move to the next stage?

**Comment by filtakes** [comment]
@Sunnyiscoming @galen-mcandrew @raghavrmadya @Kevin-FF-USA any update here?

**Comment by Filplus-govteam** [comment]
Please provide SP entities and contacts. You are planning 10 copies, there are 4 names listed. Closing until updated.
