### ISSUE TITLE
[DataCap Application] Create coach

### ISSUE THREAD

**Issue by Leviiee** [filecoin-project/filecoin-plus-large-datasets#225]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Create coach
- Website / Social Media: http://www.cccoach.cn/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100TiB
- On-chain address for first allocation: f1ac3mjrhahxbyvxsasp4e7kwa6vyds3ahm27us6a

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Founded in 2013, CCCoach is a community organization which specializing in coaching training and spreading coaching culture in organization. Headquartered in Shanghai, and Shenzhen is our sub-center, and with partner institutions in Beijing, Chengdu, Dalian and other cities across mainland China. CCCoach is the exclusive partner of TNM International Coach Union, Offering ICF ACTP-level program, and as U Lab's Strategic partners in China, leading U Theory's application in organizations. In the past 8 years, CCCoach has trained more than 1,000 certified evolutionary coaches, and nearly 50 of them became ICF professional certified coaches (PCC). With the vision to spread Coaching culture in China, we organized thousands of coaching-related learning activities, reaching nearly 70,000 participants.
```

What is the primary source of funding for this project?
```
Our shareholders give funds to us.
```

What other projects/ecosystem stakeholders is this project associated with?
```
No.
```

## Use-case details

Describe the data being stored onto Filecoin
```
It is about two parts. One part is about online course source material. The other part is about recordings of live courses.
```

Where was the data in this dataset sourced from?
```
It was from different teams who give users lessons. They made these videos and match them to proper classification.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
Ok. 
http://www.cccoach.cn/uploads/ueditor/video/20210526/1622022358551266.mp4
http://www.cccoach.cn/uploads/ueditor/video/20161116/1479288556950382.mp4
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes. We confirm that this is a public dataset that can be retrieved by anyone on the Network.
```

What is the expected retrieval frequency for this data?
```
Less than 2 times a year.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
More than 1 year.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
We will mostly make deals in Asia.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
We can use both online and offline processes to make sure the success rate. 
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We are looking forward to finding closer miners. 
```

How will you be distributing deals across storage providers?
```
We will choose cheaper miners preferentially.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, we can make deals as quickly.
```

**Comment by IPFSUnion** [comment]
Coaching training is a very interesting and professional field.  Would love to support.

**Comment by swatchliu** [comment]
I used to be the member of CCCoach Club.  Happy to support if RKH passed.

**Comment by Leviiee** [comment]
Oh, thank you! @IPFSUnion @swatchliu

**Comment by Leviiee** [comment]
@swatchliu @UnionLabs2020 Hi notaries! When can I get my datacap? I don't know what should I do right now. Can you give me some advice?

**Comment by Leviiee** [comment]
@swatchliu @UnionLabs2020 Hi notaries! When can I get my datacap? I don't know what should I do right now. Can you give me some advice? Thank you!

**Comment by swatchliu** [comment]
> @swatchliu @UnionLabs2020 Hi notaries! When can I get my datacap? I don't know what should I do right now. Can you give me some advice? Thank you!

Dear Leviiee, I would like to double-verify your connection with the CCCoach.   Will you please provide your contact and I would like to visit them in Shanghai China.

**Comment by Leviiee** [comment]
OK! I will dm you! I think they're looking forward to your visit!

**Comment by Leviiee** [comment]
@swatchliu OK! I will dm you! I think they're looking forward to your visit!

**Comment by galen-mcandrew** [comment]
## Multisig Notary requested
#### Total DataCap requested 
> 5PiB
#### Expected weekly DataCap usage rate 
> 100TiB

**Comment by Fenbushi-Filecoin** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedc7peyp2jat7fgtm357bcxyapg2zn7oo5i5s6pjabemakrzoowjm 
#### Address 
> f1ac3mjrhahxbyvxsasp4e7kwa6vyds3ahm27us6a
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1yqydpmqb5en262jpottko2kd65msajax7fi4rmq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedc7peyp2jat7fgtm357bcxyapg2zn7oo5i5s6pjabemakrzoowjm

**Comment by TimWilliams00** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedpcqvbfww7nbl43ex5bdhh6vhubnq3vwttumd2tse54kzydjivni 
#### Address 
> f1ac3mjrhahxbyvxsasp4e7kwa6vyds3ahm27us6a
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1fkxkfxgopjf3ufnfg5i3m6qlwf73kp4w5zz7nnq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedpcqvbfww7nbl43ex5bdhh6vhubnq3vwttumd2tse54kzydjivni

**Comment by swatchliu** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced7337e6722oqo7kicyp2dwgtxrcg3dwfrlf4ynjscmilnj3gzps4 
#### Address 
> f1ac3mjrhahxbyvxsasp4e7kwa6vyds3ahm27us6a
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1yh6q3nmsg7i2sys7f7dexcuajgoweudcqj2chfi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced7337e6722oqo7kicyp2dwgtxrcg3dwfrlf4ynjscmilnj3gzps4

**Comment by rayshitou** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedg7ca5q2mtsu6txdtmcnoty7hufhyl6q5ujr5bms54mvempazxxk 
#### Address 
> f1ac3mjrhahxbyvxsasp4e7kwa6vyds3ahm27us6a
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f136bz32l2hlyad4npmfg5dngcdw3jk3tpcpoz2ja
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedg7ca5q2mtsu6txdtmcnoty7hufhyl6q5ujr5bms54mvempazxxk

**Comment by swatchliu** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedvd5hpa5qj6r7x3vyh4uqhwpcje3rjaxaburypp5hszv5ooevclc 
#### Address 
> f1ac3mjrhahxbyvxsasp4e7kwa6vyds3ahm27us6a
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1yh6q3nmsg7i2sys7f7dexcuajgoweudcqj2chfi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedvd5hpa5qj6r7x3vyh4uqhwpcje3rjaxaburypp5hszv5ooevclc

**Comment by TimWilliams00** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacealrqx5qqu4k5m5brayy2ttcouuyljdki7gcut2rdelhr2oq5a6bm 
#### Address 
> f1ac3mjrhahxbyvxsasp4e7kwa6vyds3ahm27us6a
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1fkxkfxgopjf3ufnfg5i3m6qlwf73kp4w5zz7nnq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacealrqx5qqu4k5m5brayy2ttcouuyljdki7gcut2rdelhr2oq5a6bm

**Comment by rayshitou** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceajeybrqqev7ysa32grs6idx7cyrgp5bdrbc3pkugn2uuhrfycqzi 
#### Address 
> f1ac3mjrhahxbyvxsasp4e7kwa6vyds3ahm27us6a
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f136bz32l2hlyad4npmfg5dngcdw3jk3tpcpoz2ja
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceajeybrqqev7ysa32grs6idx7cyrgp5bdrbc3pkugn2uuhrfycqzi

**Comment by Leviiee** [comment]
@Fenbushi-Filecoin @TimWilliams00 @swatchliu Hi, can you help me finish this round of signature?

**Comment by TimWilliams00** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceduh3ckooxyzxa35sh7lx743d2o4c6f4wpcd4polclbakwurkbbta 
#### Address 
> f1ac3mjrhahxbyvxsasp4e7kwa6vyds3ahm27us6a
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1fkxkfxgopjf3ufnfg5i3m6qlwf73kp4w5zz7nnq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceduh3ckooxyzxa35sh7lx743d2o4c6f4wpcd4polclbakwurkbbta

**Comment by KodaRobotDog** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedlvkflg2s6lzlelozpuu72ut67x23seaj7qpplhimq6hx64dbems 
#### Address 
> f1ac3mjrhahxbyvxsasp4e7kwa6vyds3ahm27us6a
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1jyalts5uhtmp5sbbssse23toshvsqbbtjgukm5a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedlvkflg2s6lzlelozpuu72ut67x23seaj7qpplhimq6hx64dbems

**Comment by swatchliu** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedxsrlqnutiyrublgvioehcw3grawraikzgmsaobclg2a3cug3ceq 
#### Address 
> f1ac3mjrhahxbyvxsasp4e7kwa6vyds3ahm27us6a
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1yh6q3nmsg7i2sys7f7dexcuajgoweudcqj2chfi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedxsrlqnutiyrublgvioehcw3grawraikzgmsaobclg2a3cug3ceq

**Comment by TimWilliams00** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedvvpll434ieekbnaor6a4lafbtkv5sxvciyyw3qxwy3732trjv7u 
#### Address 
> f1ac3mjrhahxbyvxsasp4e7kwa6vyds3ahm27us6a
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1fkxkfxgopjf3ufnfg5i3m6qlwf73kp4w5zz7nnq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedvvpll434ieekbnaor6a4lafbtkv5sxvciyyw3qxwy3732trjv7u

**Comment by fabriziogianni7** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
> bafy2bzacedmsiasbkdznnvamipgrlcgjcqd2fgihz2mu2zdrjsc6s2nlcbpdi 
#### Address 
> f1ac3mjrhahxbyvxsasp4e7kwa6vyds3ahm27us6a
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1ktlkcxnmzxcdaoqfsunrg3vocfbmgv4n3mrn74a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedmsiasbkdznnvamipgrlcgjcqd2fgihz2mu2zdrjsc6s2nlcbpdi

**Comment by fabriziogianni7** [comment]
approved by @MetaWaveInfo

**Comment by swatchliu** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedi7qamv2cdrjcx57wwmvkgqtqhqelq2pou4ab5loh2dmfungs4i2 
#### Address 
> f1ac3mjrhahxbyvxsasp4e7kwa6vyds3ahm27us6a
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1yh6q3nmsg7i2sys7f7dexcuajgoweudcqj2chfi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedi7qamv2cdrjcx57wwmvkgqtqhqelq2pou4ab5loh2dmfungs4i2

**Comment by Leviiee** [comment]
Thanks for Pluskit @PluskitOfficial  ---approve
bafy2bzaceafm252lm7mwtysv6wlgk67bvegxbxidiztouxj4xsn7jy6wwc3y4

Is there any other notary who can please sign for me?

**Comment by UnionLabs2020** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebozrgudm5ps2u337j63its6id47ckazlji5vgbhhb7wizecztw3m 
#### Address 
> f1ac3mjrhahxbyvxsasp4e7kwa6vyds3ahm27us6a
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f17xdri3wunqgld7dm23e4f3eqsntjakwc47xjo6i
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebozrgudm5ps2u337j63its6id47ckazlji5vgbhhb7wizecztw3m

**Comment by BigD-Exchange** [comment]
@Leviiee Hi! Great to see you have gotten approval for DataCap. If you are looking for storage providers to store these data or have any questions, please visit #bigdata-exchange on Filecoin Slack or reply here. 

We have strong demand from a diverse group of SPs, who are actively looking to onboard more data.

**Comment by filplus-checker** [comment]
## DataCap and CID Checker Report[^1]
 - Organization: `Create coach`
 - Client: `f1ac3mjrhahxbyvxsasp4e7kwa6vyds3ahm27us6a`
### Storage Provider Distribution
The below table shows the distribution of storage providers that have stored data for this client.

If this is the first time a provider takes verified deal, it will be marked as `new`.

For most of the datacap application, below restrictions should apply.
 - Storage provider should not exceed 25% of total datacap.
 - Storage provider should not be storing duplicate data for more than 20%.
 - Storage provider should have published its public IP address.
 - All storage providers should be located in different regions.

⚠️ 59.34% of total deal sealed by [f01895891](https://filfox.info/en/address/f01895891) are duplicate data.

⚠️ [f01844999](https://filfox.info/en/address/f01844999) has unknown IP location.

| Provider                                              |                 Location | Total Deals Sealed | Percentage | Unique Data | Duplicate Deals |
| :---------------------------------------------------- | -----------------------: | -----------------: | ---------: | ----------: | --------------: |
| [f01895783](https://filfox.info/en/address/f01895783) |     Boardman, Oregon, US |         359.19 TiB |     13.10% |  311.28 TiB |          13.34% |
| [f01832653](https://filfox.info/en/address/f01832653) |         Seoul, Seoul, KR |         266.50 TiB |      9.72% |  266.50 TiB |           0.00% |
| [f01844613](https://filfox.info/en/address/f01844613) |       Hilliard, Ohio, US |         222.03 TiB |      8.10% |  222.03 TiB |           0.00% |
| [f01843994](https://filfox.info/en/address/f01843994) |       Hilliard, Ohio, US |         220.91 TiB |      8.06% |  220.91 TiB |           0.00% |
| [f01844043](https://filfox.info/en/address/f01844043) |       Hilliard, Ohio, US |         220.13 TiB |      8.03% |  220.13 TiB |           0.00% |
| [f01844118](https://filfox.info/en/address/f01844118) |       Hilliard, Ohio, US |         218.53 TiB |      7.97% |  218.53 TiB |           0.00% |
| [f01844329](https://filfox.info/en/address/f01844329) |       Hilliard, Ohio, US |         210.34 TiB |      7.67% |  210.34 TiB |           0.00% |
| [f01844232](https://filfox.info/en/address/f01844232) |       Hilliard, Ohio, US |         198.63 TiB |      7.24% |  198.63 TiB |           0.00% |
| [f01843673](https://filfox.info/en/address/f01843673) |       Hilliard, Ohio, US |         119.84 TiB |      4.37% |  119.84 TiB |           0.00% |
| [f01843974](https://filfox.info/en/address/f01843974) |       Hilliard, Ohio, US |          99.66 TiB |      3.63% |   99.66 TiB |           0.00% |
| [f01843889](https://filfox.info/en/address/f01843889) |       Hilliard, Ohio, US |          99.00 TiB |      3.61% |   99.00 TiB |           0.00% |
| [f01843602](https://filfox.info/en/address/f01843602) | San Jose, California, US |          98.00 TiB |      3.57% |   98.00 TiB |           0.00% |
| [f01832632](https://filfox.info/en/address/f01832632) | San Jose, California, US |          87.81 TiB |      3.20% |   87.81 TiB |           0.00% |
| [f01895891](https://filfox.info/en/address/f01895891) | Singapore, Singapore, SG |          74.25 TiB |      2.71% |   30.19 TiB |          59.34% |
| [f01788210](https://filfox.info/en/address/f01788210) |     Boardman, Oregon, US |          64.34 TiB |      2.35% |   64.34 TiB |           0.00% |
| [f01788231](https://filfox.info/en/address/f01788231) | San Jose, California, US |          41.00 TiB |      1.50% |   41.00 TiB |           0.00% |
| [f01843549](https://filfox.info/en/address/f01843549) | San Jose, California, US |          26.56 TiB |      0.97% |   26.56 TiB |           0.00% |
| [f01843540](https://filfox.info/en/address/f01843540) | San Jose, California, US |          18.00 TiB |      0.66% |   18.00 TiB |           0.00% |
| [f01807908](https://filfox.info/en/address/f01807908) | San Jose, California, US |          17.00 TiB |      0.62% |   17.00 TiB |           0.00% |
| [f01828096](https://filfox.info/en/address/f01828096) | San Jose, California, US |          17.00 TiB |      0.62% |   17.00 TiB |           0.00% |
| [f01844999](https://filfox.info/en/address/f01844999) |                  Unknown |          15.00 TiB |      0.55% |   15.00 TiB |           0.00% |
| [f01788199](https://filfox.info/en/address/f01788199) |     Boardman, Oregon, US |          13.44 TiB |      0.49% |   13.44 TiB |           0.00% |
| [f01788202](https://filfox.info/en/address/f01788202) |     Boardman, Oregon, US |          12.09 TiB |      0.44% |   12.09 TiB |           0.00% |
| [f01778041](https://filfox.info/en/address/f01778041) |       Hilliard, Ohio, US |          11.72 TiB |      0.43% |   11.72 TiB |           0.00% |
| [f01780720](https://filfox.info/en/address/f01780720) |     Boardman, Oregon, US |          10.97 TiB |      0.40% |   10.97 TiB |           0.00% |

![Provider Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/225/1671094220303.png)
### Deal Data Replication
The below table shows how each many unique data are replicated across storage providers.
- No more than 25% of unique data are stored with less than 4 providers.

⚠️ 100.00% of deals are for data replicated across less than 4 storage providers.

| Unique Data Size | Total Deals Made | Number of Providers | Deal Percentage |
| ---------------: | ---------------: | ------------------: | --------------: |
|         2.59 PiB |         2.68 PiB |                   1 |         100.00% |

![Replication Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/225/1671094221023.png)
### Deal Data Shared with other Clients
The below table shows how many unique data are shared with other clients.
Usually different applications owns different data and should not resolve to the same CID.

⚠️ CID sharing has been observed.

| Other Client                                                                                                          | Application                                                                                        | Total Deals Affected | Unique CIDs |        Verifier |
| :-------------------------------------------------------------------------------------------------------------------- | :------------------------------------------------------------------------------------------------- | -------------------: | ----------: | --------------: |
| [f1tivtdkq34mnfzso63wrr2xh6r2zo7aebao4jfla](https://filfox.info/en/address/f1tivtdkq34mnfzso63wrr2xh6r2zo7aebao4jfla) | `China travel service(HongKong) limited`                                                           |           100.97 TiB |       1,014 | LDN v3 multisig |
| [f1dx7ljly4vmk5x2bn5ng4jpbqnuvozrz2phw42qy](https://filfox.info/en/address/f1dx7ljly4vmk5x2bn5ng4jpbqnuvozrz2phw42qy) | [CoinPhD](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/364)             |            88.06 TiB |       1,021 | LDN v3 multisig |
| [f1u522dt3zabkgbxxzecl77wgv473yvpecxh6t6zq](https://filfox.info/en/address/f1u522dt3zabkgbxxzecl77wgv473yvpecxh6t6zq) | [Huifan livestream](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/407)   |            52.47 TiB |         858 | LDN v3 multisig |
| [f1ojo3wo24zkeovndlxfpqmlgzlbysg5fiukmup4a](https://filfox.info/en/address/f1ojo3wo24zkeovndlxfpqmlgzlbysg5fiukmup4a) | `Titansoft`                                                                                        |            12.94 TiB |          95 | LDN v3 multisig |
| [f14abwn2goturifmt27s2bssoe3fup2b3npkgfzui](https://filfox.info/en/address/f14abwn2goturifmt27s2bssoe3fup2b3npkgfzui) | [KONGFU VR](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/372)           |            32.00 GiB |           1 | LDN v3 multisig |
| [f1ivsvpljx4ovp2tth73pllkxmumrudemks623iia](https://filfox.info/en/address/f1ivsvpljx4ovp2tth73pllkxmumrudemks623iia) | `TIS Inc. group`                                                                                   |            32.00 GiB |           1 | LDN v3 multisig |
| [f1iach3ih3q5x5k4lxy6wlysmqm65vwegpxwm4oii](https://filfox.info/en/address/f1iach3ih3q5x5k4lxy6wlysmqm65vwegpxwm4oii) | [Friday Shopping](https://github.com/filecoin-project/filecoin-plus-client-onboarding/issues/2019) |            32.00 GiB |           1 |        Eric Liu |
| [f1727w2vwjctfo7hflr5trgqkl3c7texh7pl4grzq](https://filfox.info/en/address/f1727w2vwjctfo7hflr5trgqkl3c7texh7pl4grzq) | [GMverse](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/365)             |            32.00 GiB |           1 | LDN v3 multisig |
| [f1clwd2dooy2cflfilhzeq2ycl544b3heqsiwhjrq](https://filfox.info/en/address/f1clwd2dooy2cflfilhzeq2ycl544b3heqsiwhjrq) | [FiboAI](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/349)              |            32.00 GiB |           1 | LDN v3 multisig |
| [f1fi7vzu266bh7yxsygw6scl2hjltdkhfb6nyzn3a](https://filfox.info/en/address/f1fi7vzu266bh7yxsygw6scl2hjltdkhfb6nyzn3a) | [Jiliantech](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/190)          |            32.00 GiB |           1 |       LDN # 190 |

[^1]: To manually trigger this report, add a comment with text `checker:manualTrigger`
