### ISSUE TITLE
[DataCap Application] <YIQU> 

### ISSUE THREAD

**Issue by dongpo313** [filecoin-project/filecoin-plus-large-datasets#2254]
### Data Owner Name 

YIQU

### What is your role related to the dataset

Data Preparer

### Data Owner Country/Region

China

### Data Owner Industry

IT & Technology Services

### Website
http://www.yiqu8888.com/

### Social Media

```text
http://www.yiqu8888.com/
```

### Total amount of DataCap being requested

5PiB

### Expected size of single dataset (one copy)

500t

### Number of replicas to store

10

### Weekly allocation of DataCap requested

500TiB

### On-chain address for first allocation

f15lcowaebhzj4h6hsrbul5gsbc6bzr3dxoesysci

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Beijing yiqu Technology Co.LTD. is an Internet technology company specializing in cultural creativity and brand design, program software development, and new media operations. It was established on February 25, 2021. The company has inherited experience in the Internet field, integrated today's advanced Internet models and creative concepts, and has achieved certain results in the fields of product research and development, new media and creative design. Our vision is to help customers break through bottlenecks, give customers wings, and become A company with strong influence in the field.

Beijing Yiqu Technology Co., Ltd. consists of a new media operation center, a design center, an R&D center, and a product center. It has strong design, R&D, and new media operation capabilities and can provide customers with professional brand-wide case design, system and software development , product planning, new media training and agency operations and other services. With the development of the company, it has cooperated with multiple projects and brands. Our purpose: Professionalism is the foundation, service is the guarantee, and quality is the credibility. The company has cooperated with projects covering medical, financial, poverty alleviation, charity, education and training and other industries. With its reliable service quality and good reputation, Yiqu has won the recognition of customers and won the honorary title of Langfang "Luxin Enterprise".
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
1."New Media Video and Image Data"
2. software data and temp data 
3. Exhibition video
```

### Where was the data currently stored in this dataset sourced from

Other

### If you answered "Other" in the previous question, enter the details here

```text
aliyun cloud
huawei cloud
```

### If you are a data preparer. What is your location (Country/Region)

Hong Kong

### If you are a data preparer, how will the data be prepared? Please include tooling used and technical details?

```text
boost，singularity
"First, I will acquire the data, then package it into files that comply with the Filecoin Plus (FIL+) data size using Singularity, and then distribute it to the storage providers (SPs)."
```

### Has this dataset been stored on the Filecoin network before? If so, please explain and make the case why you would like to store this dataset again to the network. Provide details on preparation and/or SP distribution.

```text
no
```

### Please share a sample of the data

```text
https://drive.google.com/file/d/1FEeMcgeUzK2PR6JpSdLbM_7DN3Tzlgqo/view?usp=sharing
https://drive.google.com/file/d/1Q0CQBsma1cq6X1NUVvx14ZEYZi5lYP2h/view?usp=sharing
https://drive.google.com/file/d/1A957EjlKrmd5Fu4uKF9DhwAktcg23a2U/view?usp=sharing
https://drive.google.com/file/d/1rkxysp2pBywk2S6maur8xTrVfQ9U-eBf/view?usp=sharing
https://drive.google.com/file/d/1ClSV8M1KsJlObQ8ah0Eyn_tsNr59_ckX/view?usp=sharing
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

1.5 to 2 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China

### How will you be distributing your data to storage providers

HTTP or FTP server

### How do you plan to choose storage providers

Slack, Big Data Exchange, Partners

### If you already have a list of storage providers to work with, fill out their names and provider IDs below

```text
yes，i already got some sps.
f02041085，Japan，TopValue 
f02813403 rimington Britain 
f02828509 hs88 Korea 
f02048990，Hong Kong，HS88
```

### How do you plan to make deals to your storage providers

Boost client, Lotus client, Singularity

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
- Can you provide more data samples to prove that you already have 500 TB data?
- Could you send an email to filplus-app-review@fil.org with your official domain in order to confirm your identity? Email name should includes the issue id #2254.
- Have you prepared enough token for sector pledge?
- Per the https://github.com/filecoin-project/notary-governance/issues/922 for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

**Comment by herrehesse** [comment]
Client is lying about location of SP's and the data stored is most likely faked like all other. Please close this LDN.

**Comment by dongpo313** [comment]
> * Can you provide more data samples to prove that you already have 500 TB data?
> * Could you send an email to [filplus-app-review@fil.org](mailto:filplus-app-review@fil.org) with your official domain in order to confirm your identity? Email name should includes the issue id [[DataCap Application] <YIQU>  #2254](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/2254).
> * Have you prepared enough token for sector pledge?
> * Per the [Modification: Changes required to public open dataset application flow notary-governance#922](https://github.com/filecoin-project/notary-governance/issues/922) for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

![27711698825158_ pic](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/115816842/657604a9-a909-4992-a909-2da244a0f326)
![27721698825590_ pic](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/115816842/fa98c2eb-3e0d-4d62-bc0c-503edea06d5c)
![85881698806821_ pic](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/115816842/5ba9e291-9cb6-4ea9-b125-f37d87af85ab)
![26091693927939_ pic](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/115816842/0b21445b-5029-4e48-84e1-0e5e8f03d291)

1).  yes,as you can seen,data includes software data backup ,media video,product image,mysql data backupand log backup.
2).  sure, i had sent.
3).  Yes, it's available.
4).  kyc had completed.
please check it,thanks.

**Comment by Sunnyiscoming** [comment]
Received the form.
Can you explain about the question submitted by the notary above?

**Comment by mingyang313** [comment]
> Received the form. Can you explain about the question submitted by the notary above?

Thank you for your response. As you can see, I am a data preparer. I contacted SPs and they provided their location and entity information. I confirmed their location by querying the IP and found nothing unusual. I even contacted them again to confirm the information. If the notary has means and evidence to confirm that the entity information and location information provided by the SPs is incorrect, I will terminate cooperation with these SPs and look for more reliable ones. Alternatively, the notary can recommend some SPs to me.

**Comment by dongpo313** [comment]
> Received the form. Can you explain about the question submitted by the notary above?

Thank you for your response. As you can see, I am a data preparer. I contacted SPs and they provided their location and entity information. I confirmed their location by querying the IP and found nothing unusual. I even contacted them again to confirm the information. If the notary has means and evidence to confirm that the entity information and location information provided by the SPs is incorrect, I will terminate cooperation with these SPs and look for more reliable ones. Alternatively, the notary can recommend some SPs to me.

**Comment by herrehesse** [comment]
@dongpo313 Do not even get me started. These miners are the same list which every abusive LDN lists. They are fake or simply self-dealing all datacap. You are not a data preparer, you ARE the miner. Simply trying to get more datacap.

Stop lying.

@kevzak please close.

**Comment by dongpo313** [comment]
It's completely groundless speculation, which is very frustrating for FIL+. It's ridiculous to question just because the same service provider was found for data preparer.

**Comment by herrehesse** [comment]
Client is lying about location of SP's and the data stored is most likely faked like all other. Please close this LDN.

**Comment by dongpo313** [comment]
> attempting to email SP contacts provided. having trouble reaching rimington.com , site doesn't exist, please provide proof of location for reach SP - closing until updated

f02041085，Japan，TopValue, tangshantai@gmail.com
f02813403 rimington，Britain, y760946378@gmail.com
f02828509 hs88，Korea, longxingli730@gmail.com
f02048990，Hong Kong，HS88,460987450@qq.com

I have already contacted these service providers, and they provided their email information, Please fix it and reopen issue.

@Filplus-govteam @Sunnyiscoming  @kevzak

**Comment by Filplus-govteam** [comment]
Email sent to confirm

**Comment by dongpo313** [comment]
> Email sent to confirm

i had connected sps to reply the email,please check.

**Comment by dongpo313** [comment]
if there are not any problem，please apply datacap，thanks.
@Filplus-govteam @Sunnyiscoming @clriesco

**Comment by dongpo313** [comment]
any update?
@Filplus-govteam @Sunnyiscoming @clriesco

**Comment by clriesco** [comment]
This is not a tech related issue, please do not tag the tech team.

**Comment by dongpo313** [comment]
![img_v3_0270_dc9b03d8-06e1-4177-832f-b198936813fh](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/115816842/d6372aa7-1cad-4cc9-8753-f449153264cb)
![93241704968617_ pic](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/115816842/79f4392f-d83b-4375-a03e-3b5a04101a19)
![img_v3_0270_ba0fc8ef-8136-4c30-b942-04002441036h](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/115816842/88993743-fdf5-4ec4-b10d-66d11df8e42a)

**Comment by dongpo313** [comment]
@Filplus-govteam i had connected sp to reply your email，please check it.

**Comment by dongpo313** [comment]
@Sunnyiscoming hi,please check,if no problem,please approve datacap,thx.

**Comment by dongpo313** [comment]
@Sunnyiscoming 
any update?thx

**Comment by dongpo313** [comment]
@Sunnyiscoming @Filplus-govteam 
can you fix it?thx

**Comment by Filplus-govteam** [comment]
we reopened it @dongpo313 it is ok to use.

**Comment by dongpo313** [comment]
> we reopened it @dongpo313 it is ok to use.

yes,but no grant for datacap.

**Comment by dongpo313** [comment]
@Sunnyiscoming  
any update?

**Comment by dongpo313** [comment]
@Sunnyiscoming

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 5PiB

**Expected weekly DataCap usage rate**
> 500TiB

**Client address**
>f15lcowaebhzj4h6hsrbul5gsbc6bzr3dxoesysci

**Comment by Chuangshi1** [comment]
f02041085，Japan，TopValue, [tangshantai@gmail.com](mailto:tangshantai@gmail.com)
f02813403 rimington，Britain, [y760946378@gmail.com](mailto:y760946378@gmail.com)
f02828509 hs88，Korea, [longxingli730@gmail.com](mailto:longxingli730@gmail.com)
f02048990，Hong Kong，HS88,[460987450@qq.com](mailto:460987450@qq.com)
support! Hope you can add more SPs in the following stage.

**Comment by Chuangshi1** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacednwb6y7xhc3jyvkg6rmamavzrexjuasaf72us3cvhrn6lecglrsy 
#### Address 
> f15lcowaebhzj4h6hsrbul5gsbc6bzr3dxoesysci
#### Datacap Allocated
> 250.00TiB
#### Signer Address
> f1mdk7s2vntzm6hu35yuo6vjubtrpfnb2awhgvrri
#### Id
> c934d9a8-8737-4228-9ae0-bccac1275368
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacednwb6y7xhc3jyvkg6rmamavzrexjuasaf72us3cvhrn6lecglrsy

**Comment by ipollo00** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacea5t63kwt5obr35z4xw6im6bcw2izp47thrksfoveojdegzeueyse 
#### Address 
> f15lcowaebhzj4h6hsrbul5gsbc6bzr3dxoesysci
#### Datacap Allocated
> 250.00TiB
#### Signer Address
> f1n5wlrrhoxpkgwij25xrtt7w7g2k3fhbthmdn6ri
#### Id
> c934d9a8-8737-4228-9ae0-bccac1275368
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacea5t63kwt5obr35z4xw6im6bcw2izp47thrksfoveojdegzeueyse

**Comment by dongpo313** [comment]
it's ok'

**Comment by luobin544** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebmciozugiet4dctpqdqrmff56l7wpn6qurauadxralp5nfzkzccg 
#### Address 
> f15lcowaebhzj4h6hsrbul5gsbc6bzr3dxoesysci
#### Datacap Allocated
> 500.00TiB
#### Signer Address
> f1tbd632f6w62glfaf7wjpimacbnjiz26poyoes2q
#### Id
> ba0beb8b-2362-435d-9239-e9460fdbe394
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebmciozugiet4dctpqdqrmff56l7wpn6qurauadxralp5nfzkzccg

**Comment by stcloudlisa** [comment]
checker:manualTrigger

**Comment by stcloudlisa** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedjvi2bod4dsbroyugimmbyn2adjfguirimdi3qof4sapxa3mlfvu 
#### Address 
> f15lcowaebhzj4h6hsrbul5gsbc6bzr3dxoesysci
#### Datacap Allocated
> 500.00TiB
#### Signer Address
> f1jvvltduw35u6inn5tr4nfualyd42bh3vjtylgci
#### Id
> ba0beb8b-2362-435d-9239-e9460fdbe394
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedjvi2bod4dsbroyugimmbyn2adjfguirimdi3qof4sapxa3mlfvu

**Comment by SuperChaiChai** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecjfjojxxu5n5sivvwkskw5pnib4gyyo6bo46x3yur4mo3jzs7bqs 
#### Address 
> f15lcowaebhzj4h6hsrbul5gsbc6bzr3dxoesysci
#### Datacap Allocated
> 500.00TiB
#### Signer Address
> f12mckci3omexgzoeosjvstcfxfe4vqw7owdia3da
#### Id
> db89b8e1-701c-4751-873b-b65765da0d3b
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecjfjojxxu5n5sivvwkskw5pnib4gyyo6bo46x3yur4mo3jzs7bqs

**Comment by zcfil** [comment]
checker:manualTrigger

**Comment by zcfil** [comment]
> f02041085，Japan，TopValue, [tangshantai@gmail.com](mailto:tangshantai@gmail.com) f02813403 rimington，Britain, [y760946378@gmail.com](mailto:y760946378@gmail.com) f02828509 hs88，Korea, [longxingli730@gmail.com](mailto:longxingli730@gmail.com) f02048990，Hong Kong，HS88,[460987450@qq.com](mailto:460987450@qq.com)
> 
> I have already contacted these service providers, and they provided their email information, Please fix it and reopen issue.

![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/45065975/0c56e22b-ebe2-4494-a55f-7b4ef61539a5)
It doesn't match the previously provided storage provider, can you explain this and provide information about them

**Comment by dongpo313** [comment]
> you

f02843151   cheng lingsucheng@yeah.net FBC-Capital Turkey 
f02886019   qbit qbit@mercurityfintech.com MFH Canada
f02838518   akcd4040 Jordan@bitwind.com bitwind Russia 

The nodes for which the application has been submitted are preparing data. I have introduced some new nodes, please check.

**Comment by zcfil** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedsgfnok4rnsjq44pcky4kerziaahmwewhiusv6wt7n2xqpjukfco 
#### Address 
> f15lcowaebhzj4h6hsrbul5gsbc6bzr3dxoesysci
#### Datacap Allocated
> 500.00TiB
#### Signer Address
> f1cjzbiy5xd4ehera4wmbz63pd5ku4oo7g52cldga
#### Id
> db89b8e1-701c-4751-873b-b65765da0d3b
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedsgfnok4rnsjq44pcky4kerziaahmwewhiusv6wt7n2xqpjukfco

**Comment by dongpo313** [comment]
works

**Comment by Chuangshi1** [comment]
checker:manualTrigger

**Comment by 1ane-1** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceboniprkvjskvsxyw3gtlxu3ate2g6sv3gvz2qfhrt3vgwa5h3hk6 
#### Address 
> f15lcowaebhzj4h6hsrbul5gsbc6bzr3dxoesysci
#### Datacap Allocated
> 500.00TiB
#### Signer Address
> f1mdk7s2vntzm6hu35yuo6vjubtrpfnb2awhgvrri
#### Id
> 7da8f1d1-6d68-4588-8c31-f0a5ee2fa499
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceboniprkvjskvsxyw3gtlxu3ate2g6sv3gvz2qfhrt3vgwa5h3hk6

**Comment by Tom-OriginStorage** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebwjuq52goj43bxsz4cwyonoli3pw7tkjpuv73aqycsft2a3rzbbo 
#### Address 
> f15lcowaebhzj4h6hsrbul5gsbc6bzr3dxoesysci
#### Datacap Allocated
> 500.00TiB
#### Signer Address
> f1q6bpjlqia6iemqbrdaxr2uehrhpvoju3qh4lpga
#### Id
> 7da8f1d1-6d68-4588-8c31-f0a5ee2fa499
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebwjuq52goj43bxsz4cwyonoli3pw7tkjpuv73aqycsft2a3rzbbo

**Comment by dongpo313** [comment]
works.

**Comment by dongpo313** [comment]
works
