### ISSUE TITLE
[DataCap Application] <NOAA Rapid Refresh Forecast System (RRFS) [Prototype]> 

### ISSUE THREAD

**Issue by mingyang313** [filecoin-project/filecoin-plus-large-datasets#2255]
### Data Owner Name 

NOAA

### What is your role related to the dataset

Data Preparer

### Data Owner Country/Region

United States

### Data Owner Industry

Other

### Website

https://vlab.noaa.gov/web/ufs-r2o,https://registry.opendata.aws/noaa-rrfs

### Social Media

```text
Website: https://www.noaa.gov/
Twitter: https://twitter.com/NOAA
```

### Total amount of DataCap being requested

15PiB

### Expected size of single dataset (one copy)

2p

### Number of replicas to store

7

### Weekly allocation of DataCap requested

1PiB

### On-chain address for first allocation

f1qbjrguazenevpjtok55fj5fwq3q2f2nzlsdijoq

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
The Rapid Refresh Forecast System (RRFS) is the National Oceanic and Atmospheric Administration’s (NOAA) next generation convection-allowing, rapidly-updated ensemble prediction system, currently scheduled for operational implementation in 2024. The operational configuration will feature a 3 km grid covering North America and include deterministic forecasts every hour out to 18 hours, with deterministic and ensemble forecasts to 60 hours four times per day at 00, 06, 12, and 18 UTC.The RRFS will provide guidance to support forecast interests including, but not limited to, aviation, severe convective weather, renewable energy, heavy precipitation, and winter weather on timescales where rapidly-updated guidance is particularly useful.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
experiments dataset.
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### If you are a data preparer. What is your location (Country/Region)

Hong Kong

### If you are a data preparer, how will the data be prepared? Please include tooling used and technical details?

```text
boost,singarate
```

### Please share a sample of the data

```text
sudo aws s3 ls --no-sign-request s3://noaa-rrfs-pds/ --recursive --human-readable --summarize | grep Total 
Total Objects: 12634735
Total Size: 2 PiB
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

1.5 to 2 years

### In which geographies do you plan on making storage deals

Greater China, North America

### How will you be distributing your data to storage providers

HTTP or FTP server

### How do you plan to choose storage providers

Slack, Big Data Exchange

### If you already have a list of storage providers to work with, fill out their names and provider IDs below

```text
f02041085，TopValue Japan 
f02812304 SY-Tech Singapore
f02828509 hs88 Korea 
f02814393 pythia California,USA
```

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
- Has this dataset been stored on the Filecoin network before? If so, please explain and make the case why you would like to store this dataset again to the network. Provide details on preparation and/or SP distribution.
- Related issue: https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/2195, which is being questioned by a notary.
- Have you prepared enough token for sector pledge?
- Per the https://github.com/filecoin-project/notary-governance/issues/922 for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

**Comment by herrehesse** [comment]
Account requesting the maximum 15P on an already stored dataset. Please close this LDN.

**Comment by mingyang313** [comment]
> * Has this dataset been stored on the Filecoin network before? If so, please explain and make the case why you would like to store this dataset again to the network. Provide details on preparation and/or SP distribution.
> * Related issue: [[DataCap Application] <HUOHUA> #2195](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/2195), which is being questioned by a notary.
> * Have you prepared enough token for sector pledge?
> * Per the [Modification: Changes required to public open dataset application flow notary-governance#922](https://github.com/filecoin-project/notary-governance/issues/922) for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

1）No, I didn't see it.As you can seen, each copy is 2 PiB and sealed into 8 SPs.
2）Yes, I saw it and answered.
3）yes，I can start once approved.
4）kyc had been complted.
<img width="1412" alt="image" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/37865375/1f6b2eea-cba6-4964-81be-45a8a898a855">

**Comment by mingyang313** [comment]
@Sunnyiscoming

**Comment by herrehesse** [comment]
f02812304 SY-Tech Singapore
f02828509 hs88 Korea 
f02814393 pythia California,USA

These above are all in the same DC this entity is lying.

**Comment by mingyang313** [comment]
If you can provide more evidence to help me avoid dishonest SPs, I would be very grateful. Thank you for your attention.

**Comment by herrehesse** [comment]
You need to provide evidence my friend, you are requesting datacap here not me. Show me.

**Comment by Filplus-govteam** [comment]
requesting 7 copies, only seeing 4 SPs listed. Please update

**Comment by mingyang313** [comment]
@Sunnyiscoming

**Comment by mingyang313** [comment]
@Filplus-govteam @Sunnyiscoming 
i had selected three sps to sealed,please check.

**Comment by Filplus-govteam** [comment]
SP IDs provided
f02041085 | kaji | TopValue | Japan | 
f02812304 | linzhen |  | SY-Tech | Singapore | 
f02828509 | kinxishan |  | hs88 | Korea 
f02814393 | james lei | | pythia | California,USA | 
f02058146 | wang yixin | okfex | GuangZhou, China | 
f02824257,Singapore,Kenneth/TL-Limited
f02131855,Hong Kong,chris/private
f0870558, Hong Kong,Crack/private

**Comment by mingyang313** [comment]
@Sunnyiscoming @
please check for datacap,thx.I am ready for sealing.

**Comment by mingyang313** [comment]
@Sunnyiscoming 
If you have any other questions, please contact me. If there are no further questions, I hope for a quick approval. Thank you.

**Comment by mingyang313** [comment]
@Sunnyiscoming @Filplus-govteam 
there are no tag with "ready to sing",please fix it,thx.

**Comment by clriesco** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 15PiB

**Expected weekly DataCap usage rate**

> 1PiB

**Client address**

> f1qbjrguazenevpjtok55fj5fwq3q2f2nzlsdijoq

**Comment by clriesco** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 15PiB

**Expected weekly DataCap usage rate**

> 1PiB

**Client address**

> f1qbjrguazenevpjtok55fj5fwq3q2f2nzlsdijoq

**Comment by xinaxu** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedqebhe5s6plgwv2j6vd573afovufiefdx4555znnwiqry723upwg 
#### Address 
> f1qbjrguazenevpjtok55fj5fwq3q2f2nzlsdijoq
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f1k3ysofkrrmqcot6fkx4wnezpczlltpirmrpsgui
#### Id
> 957583ec-b9a2-46cc-b821-a57dfb4b1742
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedqebhe5s6plgwv2j6vd573afovufiefdx4555znnwiqry723upwg

**Comment by METAVERSEDATAMINING** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceab7pc4zxu3hpveilziklsieh4xs5xsv2hkn7jlkzx4fuxwk74gc2 
#### Address 
> f1qbjrguazenevpjtok55fj5fwq3q2f2nzlsdijoq
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f17idrnfnxl2mbgcgr57a6z2c6lj2qx56gvm3336i
#### Id
> 957583ec-b9a2-46cc-b821-a57dfb4b1742
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceab7pc4zxu3hpveilziklsieh4xs5xsv2hkn7jlkzx4fuxwk74gc2

**Comment by nj-steve** [comment]
checker:manualTrigger

**Comment by nj-steve** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebn674zhohpolirjk2r6peb5lqsekv4gc3wyydg6nf2yluos5noyk 
#### Address 
> f1qbjrguazenevpjtok55fj5fwq3q2f2nzlsdijoq
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f1xx6555qijma7igpnjspyvdunc4vfxkawnpqy5ii
#### Id
> a5c87100-1305-4813-b9be-a0993544a039
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebn674zhohpolirjk2r6peb5lqsekv4gc3wyydg6nf2yluos5noyk

**Comment by stcloudlisa** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec6xcs3b74jthhthoekfwtugenwbqcvusaeuflh7vq2hzqhw45bls 
#### Address 
> f1qbjrguazenevpjtok55fj5fwq3q2f2nzlsdijoq
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f1jvvltduw35u6inn5tr4nfualyd42bh3vjtylgci
#### Id
> a5c87100-1305-4813-b9be-a0993544a039
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec6xcs3b74jthhthoekfwtugenwbqcvusaeuflh7vq2hzqhw45bls

**Comment by sxxfuture-official** [comment]
checker:manualTrigger

**Comment by sxxfuture-official** [comment]
@mingyang313 
⚠️ 70.16% of deals are for data replicated across less than 4 storage providers.
After two rounds of sealing, you need to pay attention to this aspect in the future.

**Comment by sxxfuture-official** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedrqc5vqdjxbqaq34zjb4oswx4zmdgkqvnl4u6tu3aqgejbqj4np4 
#### Address 
> f1qbjrguazenevpjtok55fj5fwq3q2f2nzlsdijoq
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f1foiomqlmoshpuxm6aie4xysffqezkjnokgwcecq
#### Id
> e5cdb8fa-fb76-47c6-b57b-8dc99199ace9
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedrqc5vqdjxbqaq34zjb4oswx4zmdgkqvnl4u6tu3aqgejbqj4np4

**Comment by 1ane-1** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacea3ajufikzes4gyqjhxtohcqk3sxs7kfm7gsi5rd3a5vx3ow5nlw2 
#### Address 
> f1qbjrguazenevpjtok55fj5fwq3q2f2nzlsdijoq
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f1mdk7s2vntzm6hu35yuo6vjubtrpfnb2awhgvrri
#### Id
> e5cdb8fa-fb76-47c6-b57b-8dc99199ace9
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacea3ajufikzes4gyqjhxtohcqk3sxs7kfm7gsi5rd3a5vx3ow5nlw2

**Comment by mingyang313** [comment]
works

**Comment by a1991car** [comment]
checker:manualTrigger

**Comment by a1991car** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceci3xzhxayal3pwjvspw3ob4imbvuorau5qr6hwfap36la5sfcjmc 
#### Address 
> f1qbjrguazenevpjtok55fj5fwq3q2f2nzlsdijoq
#### Datacap Allocated
> 2.00PiB
#### Signer Address
> f1qnumecdypgrbaebtkdfjnwt5ndacadcuas3deiq
#### Id
> 171e37fa-c7b8-4f68-8040-098e33863c40
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceci3xzhxayal3pwjvspw3ob4imbvuorau5qr6hwfap36la5sfcjmc

**Comment by SuperChaiChai** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebvbbz5ozzsqhcjyw64otbbq4n4lhoqbrsv6ry6bpz7ulmsmws6y4 
#### Address 
> f1qbjrguazenevpjtok55fj5fwq3q2f2nzlsdijoq
#### Datacap Allocated
> 2.00PiB
#### Signer Address
> f12mckci3omexgzoeosjvstcfxfe4vqw7owdia3da
#### Id
> 171e37fa-c7b8-4f68-8040-098e33863c40
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebvbbz5ozzsqhcjyw64otbbq4n4lhoqbrsv6ry6bpz7ulmsmws6y4

**Comment by mingyang313** [comment]
it's ok

**Comment by Chuangshi1** [comment]
checker:manualTrigger

**Comment by Tom-OriginStorage** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceav3fgmij66jrxsf25dy7n5cedjaf3cx5sy3m7vh7o6knapyk5ro4 
#### Address 
> f1qbjrguazenevpjtok55fj5fwq3q2f2nzlsdijoq
#### Datacap Allocated
> 2.00PiB
#### Signer Address
> f1q6bpjlqia6iemqbrdaxr2uehrhpvoju3qh4lpga
#### Id
> 3e582af3-ed39-43f6-9894-0113f01b3c92
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceav3fgmij66jrxsf25dy7n5cedjaf3cx5sy3m7vh7o6knapyk5ro4

**Comment by mingyang313** [comment]
it's in use

**Comment by mingyang313** [comment]
it's ok

**Comment by mingyang313** [comment]
checker:manualTrigger
