### ISSUE TITLE
[DataCap Application] NewToken - NOAA 3-D Surge and Tide Operational Forecast System for the Atlantic Basin (STOFS-3D-Atlantic)

### ISSUE THREAD

**Issue by jomozz** [filecoin-project/filecoin-plus-large-datasets#2257]
### Data Owner Name 

NOAA

### What is your role related to the dataset

Data Preparer

### Data Owner Country/Region

United States

### Data Owner Industry

Environment

### Website

https://noaa-nos-stofs3d-pds.s3.amazonaws.com/README.html

### Social Media

```text
https://twitter.com/NOAA
https://www.ntkblock.com
```

### Total amount of DataCap being requested

3PiB

### Expected size of single dataset (one copy)

183.1 TiB

### Number of replicas to store

10

### Weekly allocation of DataCap requested

600TiB

### On-chain address for first allocation

f1huke6ntamxqsz2dwpvfkvx7ng3hzyk4whzhgrkq

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
NewToken was established in 2019. It is a cutting-edge Internet technology development company. The company adheres to the concept of innovation first, focuses on the research and development of new technologies in the blockchain industry, and provides technology development related to the blockchain industry. The company was established Since then, we have closely followed industry hot spots and provided customers with technology development services including DAPP, IPFS storage technology, NFT, DEFI and other technologies. The core members of the company's technical team come from well-known Internet companies. They all have more than 8 years of senior industry development experience and have rich technology research and development experience in public chain application development, distributed storage, NFT and other fields. Team members have always maintained strong learning capabilities, quickly kept up with changes in the blockchain industry, and provided customers with guaranteed services.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
https://registry.opendata.aws/noaa-nos-stofs3d/
NOAA's Surge and Tide Operational Forecast System: Three-Dimensional Component for the Atlantic Basin (STOFS-3D-Atlantic). STOFS-3D-Atlantic runs daily (at 12 UTC) to provide users with 24-hour nowcasts (analyses of near present conditions) and up to 48-hour forecast guidance of water level conditions, and 2- and 3-dimensional fields of water temperature, salinity, and currents. The water level outputs represent the combined tidal and subtidal water surface elevations and are referenced to NAVD88 in general or geoid referenced where there is no NAVD88 coverage, e.g., Puerto Rico.

STOFS-3D-Atlantic has been developed to serve the marine navigation, weather forecasting, and disaster mitigation user communities. It is developed in a collaborative effort between the NOAA/National Ocean Service (NOS)/Office of Coast Survey, the NOAA/National Weather Service (NWS)/National Centers for Environmental Prediction (NCEP) Central Operations (NCO), and the Virginia Institute of Marine Science.

STOFS-3D-Atlantic employs the Semi-implicit Cross-scale Hydroscience Integrated System Model (SCHISM) as the hydrodynamic model core. Its unstructured grid consists of 2,654,153 nodes and 5,137,229 triangular or quadrilateral elements. Grid resolution is 1.5-2 km near the shoreline, 200-550 m for the floodplain, and up to 10 m for both levees and some small rivers. Along the U.S. coastline, the land boundary of the domain aligns with the 10-m contour above NAVD88, encompassing the coastal transitional zone most vulnerable to coastal and inland flooding.

STOFS-3D-Atlantic makes uses of outputs from the National Water Model (NWM) to include inland hydrology and extreme precipitation effects on coastal flooding; forecast guidance from the NCEP Global Forecast System (GFS) and High-Resolution Rapid Refresh (HRRR) model as the surface meteorological forcing; the tidal water level and currents from the FES2014 tidal database; and the subtidal water level, and subtidal three-dimensional water temperature, salinity, and currents from the NCEP Global Real-Time Ocean Forecast System (G-RTOFS) as the open ocean boundary forcing.
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### If you are a data preparer. What is your location (Country/Region)

China

### If you are a data preparer, how will the data be prepared? Please include tooling used and technical details?

```text
In order to speed up downloading, we have specially prepared large broadband.
We will use the go-graphsplit tool for packaging
```

### Has this dataset been stored on the Filecoin network before? If so, please explain and make the case why you would like to store this dataset again to the network. Provide details on preparation and/or SP distribution.

```text
I have carefully gone through all the LDN applications, and I have not yet found that anyone else has applied for this data.
```

### Please share a sample of the data

```text
aws s3 ls --no-sign-request --recursive --human-readable --summarize s3://noaa-nos-stofs3d-pds/ | grep "Total"
Total Objects: 831523
Total Size: 183.1 TiB

The stored data is growing every day, taking into account the filling of the data, the final stored data will exceed 200TiB
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

2 to 3 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, Europe, Australia (continent)

### How will you be distributing your data to storage providers

HTTP or FTP server, Shipping hard drives

### How do you plan to choose storage providers

Slack, Partners

### If you already have a list of storage providers to work with, fill out their names and provider IDs below

```text
f01395673 | Fujian Dongshu Xishu Technology Co., Ltd. | Fujian,China

f0674600  | FileVault Technologies, LLC | Los Angeles,US 

f01193812 | Endex Technologies,Inc. | Oregon,US 

f01211558 | Hubei Digital CloudDepot Network Technology Co., Ltd. | Hubei,China
```

### How do you plan to make deals to your storage providers

Lotus client, Singularity

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by herrehesse** [comment]
This set is already stored. Why do you want to redo it? Also there are no physical miners in Los Angeles, where is the VPN from?

**Comment by Sunnyiscoming** [comment]
- Total amount of DataCap being requested ≠ Expected size of single dataset (one copy) * Number of replicas to store
3PiB ≠ 183.1 TiB * 10
Can you explain about that?
- Per the https://github.com/filecoin-project/notary-governance/issues/922 for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

**Comment by jomozz** [comment]
> * Total amount of DataCap being requested ≠ Expected size of single dataset (one copy) * Number of replicas to store
>   3PiB ≠ 183.1 TiB * 10
>   Can you explain about that?
> * Per the [Modification: Changes required to public open dataset application flow notary-governance#922](https://github.com/filecoin-project/notary-governance/issues/922) for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

@Sunnyiscoming 
*  1/ The dataset is growing every day, and today it is almost 190T. During our LDN application and use period, it will definitely exceed 200T.
   2/ when we actually process the car file, there will be data filling.
*  I have filled out the form and submitted it

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 3PiB

**Expected weekly DataCap usage rate**
> 600TiB

**Client address**
>f1huke6ntamxqsz2dwpvfkvx7ng3hzyk4whzhgrkq

**Comment by jomozz** [comment]
@Sunnyiscoming Is there any progress so far?

**Comment by herrehesse** [comment]
@jomozz dont try and look over my questions, answer them:

This set is already stored. Why do you want to redo it? Also there are no physical miners in Los Angeles, where is the VPN from?

**Comment by Filplus-govteam** [comment]
Not finding SP entities businesses exist in locations mentioned. Also asking for 10 copies with only 4 SPs listed. Closing until updated.
