### ISSUE TITLE
[DataCap Application]Shenzhen Star Luopan Technology Co., Ltd.

### ISSUE THREAD

**Issue by ymhaihao** [filecoin-project/filecoin-plus-large-datasets#2258]
### Data Owner Name 

Shenzhen Star Luopan Technology Co., Ltd.

### What is your role related to the dataset

Dataset Owner

### Data Owner Country/Region

China

### Data Owner Industry

IT & Technology Services

### Website

https://www.xingluopan.com/

### Social Media

```text
https://www.xingluopan.com/
```

### Total amount of DataCap being requested

12PiB

### Expected size of single dataset (one copy)

1.2PiB

### Number of replicas to store

10

### Weekly allocation of DataCap requested

1PiB

### On-chain address for first allocation

f1dxeykanixlamxzogamclx7dotd3x5eehzt6nuxi

### Data Type of Application

Public, Open Commercial/Enterprise

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Star Luopan Technology is a provider of intelligent IoT solutions. Through the independently developed application management SaaS platform + AIoT cloud + intelligent hardware equipment, the multi-dimensional combination of product models is in line with industry applications and meets the needs of enterprise operation and development throughout the entire process. Helping companies reach new levels of productivity and efficiency, thereby giving their businesses a competitive advantage.
The Star Luopan fixed assets SaaS platform independently developed by the company is a professional fixed asset management cloud platform developed based on low-code systems. It provides comprehensive asset management solutions such as fixed asset management, equipment management, inventory consumables management, and virtual asset management to meet the needs of enterprises. Asset management needs in various scenarios. As well as an intelligent warehousing management platform, it can comprehensively manage the entire process of item warehousing, allocation, inventory, etc., helping enterprises to rationally dispatch inventory. In addition, the R&D team with strong experience also has mature solutions in smart archives, smart libraries, smart washing, smart manufacturing and other industrial application fields.
In addition to meeting the universal needs of enterprises for mobile work anytime, anywhere, real-time data synchronization, and standard and efficient management, the Xingluopan Intelligent IoT Cloud Application Platform can provide customers with flexible personalized configuration capabilities and development that meets the needs of enterprises. capabilities, accelerate enterprises to complete intelligent digitalization, and help enterprises lead the forefront of intelligence.
Star Luopan will continue to focus on IoT technology and enterprise services, actively promote technology integration and innovation, further expand IoT application scenarios, deeply explore the value of physical world data, and achieve more and better intelligent services.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
Posters, videos, plans, company design drafts, item information, etc.
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### If you are a data preparer. What is your location (Country/Region)

China

### Please share a sample of the data

```text
2022 Smart Community Technology House Fourth Generation Housing R&D Material Plan Text SU Model Video Report
Link: https://pan.baidu.com/s/1HkuI7apGJ3NJZfojoA0AzA?pwd=qhl7
Extraction code: qhl7

Link: https://pan.baidu.com/s/1d6Yvszugq2fdGNEsW8ijmQ Extraction code: lm6i
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Monthly

### For how long do you plan to keep this dataset stored on Filecoin

1.5 to 2 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America

### How will you be distributing your data to storage providers

Cloud storage (i.e. S3), Shipping hard drives

### How do you plan to choose storage providers

Slack, Filmine

### How do you plan to make deals to your storage providers

Boost client, Lotus client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by herrehesse** [comment]
No miner list, questionable data and 12P request. I recommend closing.

**Comment by Sunnyiscoming** [comment]
- Can you provide more information to prove that you alreday have 1.2 PB data?
- Could you send an email to filplus-app-review@fil.org with your official domain in order to confirm your identity? Email name should includes the issue id #2258.
- Best practice for storing large datasets includes ideally, storing it in 3 or more regions, with 4 or more storage provider operators or owners.You should list Miner ID, Business Entity, Location of sps you will cooperate with.
- Per the https://github.com/filecoin-project/notary-governance/issues/922 for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

**Comment by ymhaihao** [comment]
Hello, we are a cloud disk company that stores a lot of data. We have our own data storage facilities and the data storage exceeds 3PiB. We submitted the form, sent the email, and look forward to your early approval.
<img width="997" alt="WX20231101-221603@2x" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/5005401/ee2cf109-cf12-40a7-92e9-ce71fe20e095">
<img width="739" alt="WX20231101-221228@2x" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/5005401/778ae58f-c75c-4a64-82a2-543bb084983f">

**Comment by Sunnyiscoming** [comment]
![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/105098820/26c724c8-70d9-4486-af1d-d896156da4bc) ![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/105098820/ce632ae5-c3d5-469a-8bdd-c61c0ee65afd)

Yes. Received that.

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
>12 PiB

**Expected weekly DataCap usage rate**
> 1 PiB

**Client address**
>f1dxeykanixlamxzogamclx7dotd3x5eehzt6nuxi

**Comment by ymhaihao** [comment]
Why isn't the bot delegating the signature request, is there anything I can do? @jbesraa @simonkim0515 @fabriziogianni7

**Comment by ymhaihao** [comment]
@jbesraa

**Comment by ymhaihao** [comment]
Are there any updates here?

**Comment by ymhaihao** [comment]
hi， @Sunnyiscoming @Kevin-FF-USA @simonkim0515 Can you trigger it manually?

**Comment by herrehesse** [comment]
No miner list, questionable data and 12P request. I recommend closing @kevzak.

**Comment by ymhaihao** [comment]
We filled out the form, since the form can only fill in 5 SPs, we only filled in 5, we will add another 5 SPs to reach 10 SPs

**Comment by ymhaihao** [comment]
Can you tell me when the robot will be updated. We will provide a list of 10 SPs within 24 hours.

**Comment by herrehesse** [comment]
@ymhaihao You are talking about the fake names niic, han and ted? We both know those are the same entity.

**Comment by ymhaihao** [comment]
| Provider  |                            Location | SP Entity or Personal |
| :-------- | ----------------------------------: | --------------------: |
| f02816095 |   Singapore |              KRAL |
| f02816081|   Singapore |              KRAL |
| f02829200 |  JiangXi|              applecould |
| f02833198 |    HK |              CoffeeCould |
| f02824533 |    HK |              CoffeeCould |
| f02837094 |    HK |              CoffeeCould |
| f02841613 |    HK |              CoffeeCould |
| f02824157 |   Shenzhen |             ZhongChuangYun |
| f02824140 |   Shenzhen |             ZhongChuangYun |
|f02829749 |    GuangDong|              Calculus |

**Comment by ymhaihao** [comment]
We submitted 10 SPs for cooperation, thank you. Can someone tell me when the robot will be working properly?

**Comment by ymhaihao** [comment]
This is sad news. It has been 20 days and the bug has not been triggered yet. We can only choose to close it and reapply. @Sunnyiscoming @kevzak @Filplus-govteam

**Comment by clriesco** [comment]
Please @Sunnyiscoming , trigger this issue if you consider it

**Comment by ymhaihao** [comment]
@clriesco Thank you for manually decentralizing the quota for me, but I found that I forgot the private key, so please help me close 2258 (because I can't open it after you close it). Everything will be subject to the new application for 2288. Thank you. @Sunnyiscoming
