### ISSUE TITLE
[DataCap Application]Brantgoose

### ISSUE THREAD

**Issue by GarvinMedeles** [filecoin-project/filecoin-plus-large-datasets#226]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Brantgoose
- Website / Social Media: https://www.brantgoose.cn/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):400TiB
- On-chain address for first allocation:f1xwmnlen7j7qlkktm3oqggzcbrxp6cvqnkd2wipa

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Our goal is to be a conglomerate that continuously creates new value and provides emotion and happiness. ‎We can provide our clients with world-class technologies in visualization, analysis and processing, including image and video recognition, language and semantic understanding, machine learning, predictive detection and optimal planning. Also, we provide big data development services, such as data analysis based on industry data, and multiple services of ToB and ToC, including SDK and APP.‎
```

What is the primary source of funding for this project?
```
It’s mainly from our company‘s account.
```

What other projects/ecosystem stakeholders is this project associated with?
```
We have not associated with anyone.
```

## Use-case details

Describe the data being stored onto Filecoin
```
Some of our services are about AI and big data development, so we have large data about AL and program of AI.
```

Where was the data in this dataset sourced from?
```
From our collection about daily work.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
[Test.zip](https://github.com/filecoin-project/filecoin-plus-large-datasets/files/7963068/Test.zip)
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
We confirm that these datasets are allowed to be used.
```

What is the expected retrieval frequency for this data?
```
It is cold data, so the frequency may be once a year.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
2 years.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Japan, Korea. Other countries may be chosed.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Mainly choose offline data transfer process.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
Stable and credible miners. Credit is most improtant.
```

How will you be distributing deals across storage providers?
```
According to their cost of time, we will allocate proper ratio of deals.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, we have.
```

**Comment by swatchliu** [comment]
How did you hear about the FIL+ program?

**Comment by GarvinMedeles** [comment]
@swatchliu Hello!
From my business partner. And I think filecoin is a potential distributed storage network.

**Comment by dkkapur** [comment]
@GarvinMedeles looks like you've had a few past applications that have been getting shut down by GitHub. As was the case in https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/252, the community / notaries usually need to see some proof of your identity and that you actually represent the organization claimed above. 

One easy way to do this is to send an email from your official work email to filplus@fil.org that we can screenshot and share here. Alternatively, you may also email notaries directly that can vouch for you and support your application.

**Comment by galen-mcandrew** [comment]
Any update on this request?
