### ISSUE TITLE
[DataCap Application] National Radio Astronomy Observatory

### ISSUE THREAD

**Issue by shuchenglhk** [filecoin-project/filecoin-plus-large-datasets#2260]
### Data Owner Name

National Radio Astronomy Observatory

### What is your role related to the dataset

Data Preparer

### Data Owner Country/Region

United States

### Data Owner Industry

IT & Technology Services

### Website

https://data.nrao.edu/portal/#/

### Social Media

```text
https://data.nrao.edu/portal/#/
```

### Total amount of DataCap being requested

15PiB

### Expected size of single dataset (one copy)

1.5PiB

### Number of replicas to store

10

### Weekly allocation of DataCap requested

1PiB

### On-chain address for first allocation

f1o3jab3scsehb5klytlhko46skubkq3o7sixw5ui

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Founded in 1956, NRAO provides the most advanced radio telescope facilities and information to the international scientific community. Currently, https://data.nrao.edu/portal/#/ has stored 4.3PB of data.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
Founded in 1956, NRAO provides the most advanced radio telescope facilities and information to the international scientific community. Currently, https://data.nrao.edu/portal/#/ has stored 4.3PB of data.
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### If you are a data preparer. What is your location (Country/Region)

Singapore

### Please share a sample of the data

```text
https://data.nrao.edu/portal/#/
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

1.5 to 2 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, South America, Europe

### How will you be distributing your data to storage providers

Cloud storage (i.e. S3), HTTP or FTP server, Shipping hard drives, Lotus built-in data transfer

### How do you plan to choose storage providers

Slack, Filmine, Partners

### How do you plan to make deals to your storage providers

Boost client, Lotus client, Singularity

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by herrehesse** [comment]
New account, maximum request of 15P, no history, no miner list. Close this LDN immediately.

**Comment by herrehesse** [comment]
Why do these people keep trying? Last 6-8 weeks zero new-fraud came through, only old LDN fraud abuse has been on-going.

**Comment by Sunnyiscoming** [comment]
- Have you prepared enough token for sector pledge?
- Are you a data preparer? What is your previous experience as a data-preparer? List previous applications and client IDs
- How will the data be prepared? Please include tooling used and technical details
- If you are not preparing the data, who will prepare the data?  (Name and Business)
- Has this dataset been stored on Filecoin before? If so, why are you choosing to store it again?
- Best practice for storing large datasets includes ideally, storing it in 3 or more regions, with 4 or more storage provider operators or owners.You should list Miner ID, Business Entity, Location of sps you will cooperate with.
- Per the https://github.com/filecoin-project/notary-governance/issues/922 for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

**Comment by shuchenglhk** [comment]
1

**Comment by shuchenglhk** [comment]
We are the data preparation, we are ready enough pledge, when you pass us, we can start. As a data preparation, I have a wealth of experience, we are familiar with IPFS and filecoin, familiar with boost and lotus, familiar with Venus and data upload, download to hard disk, we have many years of experience in the storage industry. We offer 5 SP from three companies. We have filled out the form. Thanks  for your reading.

**Comment by shuchenglhk** [comment]
![WechatIMG18984](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/5136401/64a4f386-c78b-418f-9e5a-44f03d8a3da1)

**Comment by Sunnyiscoming** [comment]
![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/105098820/3ff59ac6-af36-42e8-ace6-1fda684ee8d8) ![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/105098820/5903d029-3d68-45f3-a6ae-0421dbc89111)

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
>15 PiB

**Expected weekly DataCap usage rate**
>1 PiB

**Client address**
>f1o3jab3scsehb5klytlhko46skubkq3o7sixw5ui

**Comment by shuchenglhk** [comment]
We are the data preparation, we are ready enough pledge, when you pass us, we can start. As a data preparation, I have a wealth of experience, we are familiar with IPFS and filecoin, familiar with boost and lotus, familiar with Venus and data upload, download to hard disk, we have many years of experience in the storage industry. We offer 5 SP from three companies. We have filled out the form. Thank you for your reading.

**Comment by herrehesse** [comment]
@Sunnyiscoming What are you doing? The above list is simply fake and you are pushing this with a trigger? 

@kevzak please assist.

**Comment by shuchenglhk** [comment]
Why can't we sign? Is the robot not working?who can solve this problem？ @jbenet @Kevin-FF-USA @galen-mcandrew @raghavrmadya @kevzak @dkkapur @Sunnyiscoming

**Comment by Filplus-govteam** [comment]
@shuchenglhk please provide proof of Data Preparation experience on Filecoin. 

Also, only providing 3 SP entities for 10 copies requested. Closing until updated .
