### ISSUE TITLE
[DataCap Application] -International Neuroimaging Data-Sharing Initiative (INDI)

### ISSUE THREAD

**Issue by Swift-scouts** [filecoin-project/filecoin-plus-large-datasets#2261]
### Data Owner Name 

Child Mind Institute

### What is your role related to the dataset

Data Preparer

### Data Owner Country/Region

Hong Kong

### Data Owner Industry

Life Science / Healthcare

### Website

http://fcon_1000.projects.nitrc.org/

### Social Media

```text
http://fcon_1000.projects.nitrc.org/
```

### Total amount of DataCap being requested

5PiB

### Expected size of single dataset (one copy)

500Tib

### Number of replicas to store

10

### Weekly allocation of DataCap requested

600TiB

### On-chain address for first allocation

f1qa2ittjkjduusczljp3izrtac7d3tttlmmsgdsi

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
We are a data processor with hundreds of storage machines and a 5G bandwidth computer room in Hong Kong that can process large amounts of data.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
This bucket contains multiple neuroimaging datasets that are part of the International Neuroimaging Data-Sharing Initiative. Raw human and non-human primate neuroimaging data include 1) Structural MRI; 2) Functional MRI; 3) Diffusion Tensor Imaging; 4) Electroencephalogram (EEG) In addition to the raw data, preprocessed data is also included for some datasets. A complete list of the available datasets can be seen in the documentation lonk provided below.
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### If you are a data preparer. What is your location (Country/Region)

None

### Please share a sample of the data

```text
aws s3 ls --no-sign-request s3://fcp-indi/
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Sporadic

### For how long do you plan to keep this dataset stored on Filecoin

1.5 to 2 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America

### How will you be distributing your data to storage providers

Cloud storage (i.e. S3), HTTP or FTP server

### How do you plan to choose storage providers

Slack, Big Data Exchange, Partners

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by herrehesse** [comment]
@Swift-scouts can you show me the bucket size of this AWS dataset?

**Comment by Sunnyiscoming** [comment]
- Have you prepared enough token for sector pledge?
- Are you a data preparer? What is your previous experience as a data-preparer? List previous applications and client IDs
- How will the data be prepared? Please include tooling used and technical details
- If you are not preparing the data, who will prepare the data?  (Name and Business)
- Has this dataset been stored on Filecoin before? If so, why are you choosing to store it again?
- Best practice for storing large datasets includes ideally, storing it in 3 or more regions, with 4 or more storage provider operators or owners.You should list Miner ID, Business Entity, Location of sps you will cooperate with.
- Per the https://github.com/filecoin-project/notary-governance/issues/922 for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

**Comment by Swift-scouts** [comment]
We have enough tokens.

Here I download the data from aws and convert it into car files. The downloaded files are packaged in 64GB or 32GB tar packages, and then boostx is used to generate car. I have noticed that INDI's data has been submitted, but there are some violations in his data encapsulation, so the encapsulation is not complete, so I plan to store this data again.

Our preferred storage providers are as follows, which may be increased, f02828509 Korea HS88, f02048990 Hong Kong HS88, f02812304 Singapore SY-Tech, f02812781 TVfinance Vietnam, f02814393 USA pythia California
<img width="829" alt="图片" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/33534080/0cc8dc8f-94c4-4d6e-a1b8-1e6156619559">

**Comment by herrehesse** [comment]
f02828509 Korea HS88
f02048990 Hong Kong HS88
f02812304 Singapore SY-Tech
f02812781 TVfinance Vietnam
f02814393 USA pythia California

Why are you lying about multiple locations of these entities? They are under VPN and not in the locations you submitted.

Requesting closure of this LDN.

**Comment by Swift-scouts** [comment]
They're right there. They're not using a vpn

**Comment by herrehesse** [comment]
<img width="974" alt="Screenshot 2023-11-02 at 15 41 53" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/70132857/66794bdb-ee96-472f-96a3-62035b7d8215">

_(above previous application of the same minerID's)_


No, they fact that you consistency lie is very sad. The miners are using Zenlayer (VPN provider) to hide their region. They are most likely all in the same datacenter.

Close this LDN

**Comment by Swift-scouts** [comment]
Your statement does not prove your point,I connect with the storage company and they're not in oneplace.

**Comment by herrehesse** [comment]
Never argue with a fool, onlookers may not be able to tell the difference.

**Comment by Sunnyiscoming** [comment]
Contact name and email information has not been all completed in the form. Please resubmit the form with complete information.

**Comment by Swift-scouts** [comment]
Ok, we will update SPs.

**Comment by Swift-scouts** [comment]
Have been updated
<img width="803" alt="图片" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/33534080/1dd20e15-dcf1-4317-9eb2-70b5e4131b8c">

**Comment by herrehesse** [comment]
![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/70132857/bf65f9d0-ea14-4f86-adf0-fa2faf3a27d5)


No, the fact that you consistency lie is very sad. The miners are using Zenlayer (VPN provider) to hide their region. They are most likely all in the same datacenter.

Close this LDN

**Comment by Swift-scouts** [comment]
What is the rating scale in the last column of your picture? How did you come to the conclusion of using vpn? It does not prove that the storage provider is using a vpn. As far as I know, the storage companies have rooms and machines locally and do not use VPNS.

**Comment by herrehesse** [comment]
Your response holds zero ground since you are unable to provide any evidence to counter mine. Close this LDN.

**Comment by herrehesse** [comment]
@kevzak Please close this LDN.

**Comment by Swift-scouts** [comment]
@herrehesse  Your evidence is not strong enough to be convincing

**Comment by herrehesse** [comment]
You provide ZERO evidence but claim my evidence is not strong. How unintelligent are you?

https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/2261#issuecomment-1796649216

**Comment by herrehesse** [comment]
@kevzak Close this LDN and the @Swift-scouts others. This group is trying to abuse FIL+.

**Comment by Filplus-govteam** [comment]
email sent to confirm SPs

**Comment by Swift-scouts** [comment]
Can you open this issue and I can update it these days? @Sunnyiscoming
