### ISSUE TITLE
[DataCap Application] <tuyouhuwai> 

### ISSUE THREAD

**Issue by tuyouuhuwai** [filecoin-project/filecoin-plus-large-datasets#2264]
### Data Owner Name 

tuyouhuwai

### What is your role related to the dataset

Dataset Owner

### Data Owner Country/Region

China

### Data Owner Industry

Arts & Recreation

### Website

WeChat Public:TOOYOU

### Social Media

```text
WeChat Public:TOOYOU
```

### Total amount of DataCap being requested

8PiB

### Expected size of single dataset (one copy)

930TiB

### Number of replicas to store

5

### Weekly allocation of DataCap requested

1PiB

### On-chain address for first allocation

f1bx6gbnj2lyze6gijuch7ivwpu3csujixwoun4ea

### Data Type of Application

Public, Open Commercial/Enterprise

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
tuyouhuwai is a professional outdoor travel club, giving outdoor enthusiasts a platform for outdoor companionship. We were founded in Hangzhou in early 2012 and are famous for our tours around Hangzhou, domestic long-distance and foreign niche depth tours.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
Outdoor landscape shooting, outdoor activity shooting, short video shooting
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### If you are a data preparer. What is your location (Country/Region)

None

### Please share a sample of the data

```text
WeChat Public:TOOYOU
Most of the works have been uploaded to WeChat Public/Video (tuyouhuwai).
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Sporadic

### For how long do you plan to keep this dataset stored on Filecoin

2 to 3 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, Australia (continent)

### How will you be distributing your data to storage providers

HTTP or FTP server

### How do you plan to choose storage providers

Slack, Partners

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by tuyouuhuwai** [comment]
There were some account surprises, #2210, reapplication. @Sunnyiscoming

**Comment by tuyouuhuwai** [comment]
Please check the verification email for Wednesday, September 20, titled: INFORMATION VERIFICATION #2210, please.

I just sent another updated verification message to filplus-app-review@fil.org using the company domain email with the subject line: information verification #2264

Please check, thank you. @Sunnyiscoming

**Comment by herrehesse** [comment]
New account, no history, no reputation, asking for 8 PiB for video footage and has no SP's listed.

Can we close this LDN right away @kevzak ?

**Comment by herrehesse** [comment]
FRAUD:

https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/2210#issuecomment-1766384517

**Comment by herrehesse** [comment]
This entity is self-dealing:

![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/70132857/df52a390-e1af-4913-9140-6564142b43c5)

**Comment by Sunnyiscoming** [comment]
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/2264#issuecomment-1792487990
Please explain about that. @tuyouuhuwai

**Comment by tuyouuhuwai** [comment]
> [#2264 (comment)](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/2264#issuecomment-1792487990) Please explain about that. @tuyouuhuwai

Disclosure of SPs information:
f02812307	Alice Xu	275624832@qq.com
f02812314	Jerry Zhang	wsbopen@outlook.com
f02809368	Tom Liu	daniel@bowyuan.com

The latter does not preclude new SPs from joining and is in communication with the following SPs:
f02809374 Wu Chunwei wenying20107@outlook.com Japan
f02129771  Handian slk10@qq.com China
f02815451 HZZC nibuil0730@163.com Canada

**Comment by herrehesse** [comment]
<img width="1039" alt="Screenshot 2023-11-04 at 14 54 20" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/70132857/09369956-840e-45c6-8f59-4dc3d157290b">

You removed all previous messages to hide your lies. Please stop and go abuse another program.

**Comment by tuyouuhuwai** [comment]
Please, let's move on.Thanks！ @Sunnyiscoming

**Comment by herrehesse** [comment]
Please, lets not move on with abusers. Close this LDN and call it a day. Go scam Siacoin or something.

**Comment by tuyouuhuwai** [comment]
let's move on.Thanks！ @Sunnyiscoming

**Comment by Filplus-govteam** [comment]
SPs emailed. several do not exist or did not reply yet

**Comment by tuyouuhuwai** [comment]
@Filplus-govteam What do you need me to do?

**Comment by Filplus-govteam** [comment]
@tuyouuhuwai first thing: Answer all the questions on the application. Everything about data preparation is blank

**Comment by Filplus-govteam** [comment]
SPs have not replied to our email. Jerry's email is not correct here. He provided a different email but has not proven to be in USA.

Have your SPs email filplus.govteam@gmail.com - with proof of entity and location.
