### ISSUE TITLE
[DataCap Application] <CAO> - <Sentinel-1 SLC>

### ISSUE THREAD

**Issue by caoxinhe0108** [filecoin-project/filecoin-plus-large-datasets#2267]
### Data Owner Name

LiveEO

### What is your role related to the dataset

Dataset Owner

### Data Owner Country/Region

Afghanistan

### Data Owner Industry

Life Science / Healthcare

### Website

https://www.live-eo.com/

### Social Media

```text
Twitter---https://twitter.com/liveeo_space
Linkedin---https://www.linkedin.com/company/liveeo/
```

### Total amount of DataCap being requested

10PiB

### Expected size of single dataset (one copy)

64G

### Number of replicas to store

6

### Weekly allocation of DataCap requested

1PiB

### On-chain address for first allocation

f1ynv3f5ne5k7xxr7z5q7coro7rqpls3ilhuz3ndy

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
LiveEO was born from the idea that satellite data, a vast and almost untapped resource, has enormous potential to transform our lives, and the world around us, for the better. Sven and Daniel, two NewSpace enthusiasts with a keen interest in A.I., founded LiveEO in 2018 with a simple vision: to apply this incredible trove of data about our planet to improve the way we do business, and live our lives.
```

### Is this project associated with other projects/ecosystem stakeholders?

Yes

### Describe the data being stored onto Filecoin

```text
LiveEO was born from the idea that satellite data, a vast and almost untapped resource, has enormous potential to transform our lives, and the world around us, for the better. Sven and Daniel, two NewSpace enthusiasts with a keen interest in A.I., founded LiveEO in 2018 with a simple vision: to apply this incredible trove of data about our planet to improve the way we do business, and live our lives.
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### If you are a data preparer. What is your location (Country/Region)

None

### Please share a sample of the data

```text
aws s3 ls --no-sign-request s3://sentinel1-slc/	Total Objects: 5961934	
1.1 PiB
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [ ] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

1.5 to 2 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America

### How will you be distributing your data to storage providers

Cloud storage (i.e. S3)

### How do you plan to choose storage providers

Slack, Big Data Exchange

### If you already have a list of storage providers to work with, fill out their names and provider IDs below

```text
SP-Miner-IDs Contact-name SP-Business-Email SP-Organization-Name Region
f02813403 YuanBao yuanbao@rimington.com rimington Britain
f02811783 yuanbao yuanbao@rimington.com rimington Britain
f02814393 pythia connect@pythia.com pythia California,USA
f02812781 TVfinance Alma@TVfinance.com TVfinance Vietnam
f02828509 jkkts12 John@hs88.com hs88 Korea
f02812304 saili saili@gmail.com SY-Tech Singapore
```

### How do you plan to make deals to your storage providers

Boost client, Lotus client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by caoxinhe0108** [comment]
Re apply due to #2197  being closed

**Comment by caoxinhe0108** [comment]
<img width="968" alt="image" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/12047170/fc6983a2-6443-486a-bbf1-2f6573c7d601">

**Comment by caoxinhe0108** [comment]
I have submitted the form according to the requirements of #2197

**Comment by herrehesse** [comment]
@caoxinhe0108 Multiple of your SP's are hiding their true location with VPN and falsely stating their region. This is against the rules, most of these miners are likely to be the same entity self-dealing.

Close this LDN or improve your real distribution and SP list.

**Comment by caoxinhe0108** [comment]
> @caoxinhe0108 Multiple of your SP's are hiding their true location with VPN and falsely stating their region. This is against the rules, most of these miners are likely to be the same entity self-dealing.
> 
> Close this LDN or improve your real distribution and SP list.

Please speak truthfully and provide evidence. The community is not up to you alone

**Comment by caoxinhe0108** [comment]
checker:manualTrigger

**Comment by luobin544** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec3ajcfx6ckges6yp4z7hhuntirj6oik3yb3kdy322akleuma5vom 
#### Address 
> f1ynv3f5ne5k7xxr7z5q7coro7rqpls3ilhuz3ndy
#### Datacap Allocated
> 1.00PiB
#### Signer Address
> f1tbd632f6w62glfaf7wjpimacbnjiz26poyoes2q
#### Id
> b5497604-4620-491a-a801-40c8214a77a5
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec3ajcfx6ckges6yp4z7hhuntirj6oik3yb3kdy322akleuma5vom

**Comment by herrehesse** [comment]
<img width="914" alt="Screenshot 2023-11-06 at 22 45 07" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/70132857/73449c55-b17d-40cb-9487-572bfd679bf2">

CLEAR ABUSE AGAIN! This entity is fully self-dealing with fake distribution under VPN. REPORT notaries @SuperChaiChai @luobin544 You should be ashamed of yourselves. 

@simonkim0515 @raghavrmadya @kevzak Can we perform removal of DC before this abuser uses all of their 1PiB?

**Comment by Tom-OriginStorage** [comment]
@herrehesse 
Please take back your words. Don't bully me just because I'm weak. I'm not easy to provoke, is there no one buying your DC? You're stirring up trouble here

**Comment by caoxinhe0108** [comment]
@herrehesse 
Please speak truthfully. Why have you been disturbing everyone lately? Is it because no one has bought your DC?

**Comment by Tom-OriginStorage** [comment]
checker:manualTrigger

**Comment by Tom-OriginStorage** [comment]
Report shows good

**Comment by Tom-OriginStorage** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecflnbmcw5435z2ia2677576r7qz3bt4xpad5yylm366hae35cdae 
#### Address 
> f1ynv3f5ne5k7xxr7z5q7coro7rqpls3ilhuz3ndy
#### Datacap Allocated
> 1.00PiB
#### Signer Address
> f1q6bpjlqia6iemqbrdaxr2uehrhpvoju3qh4lpga
#### Id
> e921263d-93d8-49c8-b0b1-fd3aad4875ec
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecflnbmcw5435z2ia2677576r7qz3bt4xpad5yylm366hae35cdae

**Comment by ipollo00** [comment]
I think there is no evidence showing those sps are using VPN.  Reports pretty good. willing to support from my end.

**Comment by ipollo00** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedlkia7hnf3ft54sx6ftciuyiv2u2z434goxol6mrewvhu7l4rvnm 
#### Address 
> f1ynv3f5ne5k7xxr7z5q7coro7rqpls3ilhuz3ndy
#### Datacap Allocated
> 1.00PiB
#### Signer Address
> f1n5wlrrhoxpkgwij25xrtt7w7g2k3fhbthmdn6ri
#### Id
> e921263d-93d8-49c8-b0b1-fd3aad4875ec
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedlkia7hnf3ft54sx6ftciuyiv2u2z434goxol6mrewvhu7l4rvnm

**Comment by herrehesse** [comment]
@caoxinhe0108 We have identified the perpetrators of fraud and are reporting them to their local authorities. Fraud is a grave offense, and we trust it will be dealt with appropriately by the authorities.

**Comment by herrehesse** [comment]
Same goes for all notaries who signed.

**Comment by caoxinhe0108** [comment]
@herrehesse 
I found that you leave comments under most LDNs, which are basically some very casual questions. If there are indeed problems, you can directly list your evidence below, otherwise please do not leave comments casually to affect the progress of others' projects.

@simonkim0515 @raghavrmadya @kevzak 
We have always followed the rules, and most people are moving the project in the right direction. Only some people have been messing around and affecting the progress of the project. We hope you can pay attention to it

**Comment by herrehesse** [comment]
@caoxinhe0108 - I am very sorry to hear that people are taking advantage of your proper work, but facts do not lie. These entities are completely self-dealing while hiding under VPN.

**Comment by Sunnyiscoming** [comment]
- Some of the sps in the table do not participated in
- Some sps outside the form participated in

@caoxinhe0108 Can you explain about that?

**Comment by caoxinhe0108** [comment]
checker:manualTrigger

**Comment by caoxinhe0108** [comment]
SP-Miner-IDs Contact-name SP-Business-Email SP-Organization-Name Region
f02813403 YuanBao yuanbao@rimington.com rimington Britain
f02811783 yuanbao yuanbao@rimington.com rimington Britain
f02814393 pythia connect@pythia.com pythia California,USA
f02812781 TVfinance Alma@TVfinance.com TVfinance Vietnam
f02828509 jkkts12 John@hs88.com hs88 Korea
f02812304 saili saili@gmail.com SY-Tech Singapore

**Comment by herrehesse** [comment]
![Screenshot 2023-11-13 at 13 11 01](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/70132857/c28007fb-42dd-4b15-ad02-1ab37a643377)

I am very sorry @caoxinhe0108 but you are abusing the FIL+ program by using VPN to falsely hide and self-deal datacap. This is against the rules and your application should be closed immediately.

_(DATA IS FROM PREVIOUS LDN 2197)_

@kevzak Can you close?

f02813403 YuanBao [yuanbao@rimington.com](mailto:yuanbao@rimington.com) rimington Britain (FALSE)
f02811783 yuanbao [yuanbao@rimington.com](mailto:yuanbao@rimington.com) rimington Britain (FALSE)
f02814393 pythia [connect@pythia.com](mailto:connect@pythia.com) pythia California,USA (FALSE)
f02812781 TVfinance [Alma@TVfinance.com](mailto:Alma@TVfinance.com) TVfinance Vietnam (FALSE)
f02828509 jkkts12 [John@hs88.com](mailto:John@hs88.com) hs88 Korea (FALSE)
f02812304 saili [saili@gmail.com](mailto:saili@gmail.com) SY-Tech Singapore (FALSE)

**Comment by herrehesse** [comment]
All fake domains as well. What a circus.

**Comment by kevzak** [comment]
Closing until we can validate SP entity and location

**Comment by caoxinhe0108** [comment]
First of all, I am very angry because this is not the first time this happened.

Just based on a picture of Decent, my LDN can be shut down so arbitrarily. Putting aside whether I am compliant or not, does Filecoin+ now have the final say of one person or a team outside the project?
 @kevzak I hope you can give me time to find out where I violated the rules. My project is in progress. Please give me a time point when I can confirm it. 
I will formally initiate such questions at the next notary meeting, hoping to explain your recent series of behaviors.

**Comment by caoxinhe0108** [comment]
> ![Screenshot 2023-11-13 at 13 11 01](https://user-images.githubusercontent.com/70132857/282456715-c28007fb-42dd-4b15-ad02-1ab37a643377.png)
> 
> I am very sorry @caoxinhe0108 but you are abusing the FIL+ program by using VPN to falsely hide and self-deal datacap. This is against the rules and your application should be closed immediately.
> 
> _(DATA IS FROM PREVIOUS LDN 2197)_
> 
> @kevzak Can you close?
> 
> f02813403 YuanBao [yuanbao@rimington.com](mailto:yuanbao@rimington.com) rimington Britain (FALSE) f02811783 yuanbao [yuanbao@rimington.com](mailto:yuanbao@rimington.com) rimington Britain (FALSE) f02814393 pythia [connect@pythia.com](mailto:connect@pythia.com) pythia California,USA (FALSE) f02812781 TVfinance [Alma@TVfinance.com](mailto:Alma@TVfinance.com) TVfinance Vietnam (FALSE) f02828509 jkkts12 [John@hs88.com](mailto:John@hs88.com) hs88 Korea f02812304 saili [saili@gmail.com](mailto:saili@gmail.com) SY-Tech Singapore (FALSE)

@herrehesse 
What is the basis for your rating, where is the underlying data? You can publish it for everyone to see if it is a third-party authoritative organization. If not, please retract your words. Don't slander us here. This is very unethical.

**Comment by Filplus-govteam** [comment]
@caoxinhe0108 - SPs provided do not add up. Please provide proof of SP businesses. Rimington does not exist online or in England that we could find. same for other SPs under VPN. Provide proof of differing SP entities
