### ISSUE TITLE
[DataCap Application] <Cayman Atomic Fund Co., Ltd.> - <Atoshi>

### ISSUE THREAD

**Issue by 87103978** [filecoin-project/filecoin-plus-large-datasets#2269]
### Data Owner Name

Atoshi

### What is your role related to the dataset

Dataset Owner

### Data Owner Country/Region

Cayman Islands

### Data Owner Industry

IT & Technology Services

### Website

https://atoshi.org/

### Social Media

```text
https://twitter.com/atoshiofficial
```

### Total amount of DataCap being requested

10PiB

### Expected size of single dataset (one copy)

32G

### Number of replicas to store

5

### Weekly allocation of DataCap requested

700TiB

### On-chain address for first allocation

f1bwcd4g2ygy4wgryeeils42jjpdf2dpbbvi37gfq

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Identifier

No response

### Share a brief history of your project and organization

```text
1. Atomic Fund Co., Ltd. (Atoshi Foundation) was established in May 2018, using block chain to achieve value transfer, using block chain to achieve landing application of electronic mall. Atomic chain Mall, the main atoshi brand goods, the main B2C e-commerce, brand e-commerce. And do diversion services for the world's mainstream e-commerce.

2. At present, the main project is ATOSHI. With blockchain to enable social e-commerce, APP starts more than 9.6 million times a day, Mall makes more than 40000 daily payments, and its daily active users peak more than one million; Mall has the following characteristics: cooperate with Taobao Tmall, JD.com, pinduoduo, and Amazon,Shopee,eBay in the future, our users will enjoy certain discounts when they go to the above malls through our APP, and can also get atomic coins. We will also get a rebate from the above platform. At present, we have more than 10 million registered users. On average, after each customer spends on the above platform, if we get a rebate of 1 yuan, that is more than 10 million daily income. Can also start a business at home: by sharing APP, turn idle time into productivity; as long as you work hard, your monthly income may exceed 10,000 yuan! Buyers buy products free of charge, currency appreciation potential is unlimited, from simple consumers to potential moneymakers, encourage consumption to boost GDP. We have a variety of games for our users' leisure and entertainment, including idioms, chess and other educational and learning games. Users can get atomic coins by playing games. At present, we have more than 10 million registered users. If 1% of people can contribute 10 yuan a day, the income will reach more than 1 million a day, and this income will be even higher in the future.
```

### Is this project associated with other projects/ecosystem stakeholders?

Yes

### Describe the data being stored onto Filecoin

```text
At present, the main project is ATOSHI. With blockchain to enable social e-commerce, APP starts more than 9.6 million times a day, Mall makes more than 40000 daily payments, and its daily active users peak more than one million; Mall has the following characteristics: cooperate with Taobao Tmall, JD.com, pinduoduo, and Amazon,Shopee,eBay in the future, our users will enjoy certain discounts when they go to the above malls through our APP, and can also get atomic coins. We will also get a rebate from the above platform. At present, we have more than 10 million registered users. On average, after each customer spends on the above platform, if we get a rebate of 1 yuan, that is more than 10 million daily income. Can also start a business at home: by sharing APP, turn idle time into productivity; as long as you work hard, your monthly income may exceed 10,000 yuan! Buyers buy products free of charge, currency appreciation potential is unlimited, from simple consumers to potential moneymakers, encourage consumption to boost GDP. We have a variety of games for our users' leisure and entertainment, including idioms, chess and other educational and learning games. Users can get atomic coins by playing games. At present, we have more than 10 million registered users. If 1% of people can contribute 10 yuan a day, the income will reach more than 1 million a day, and this income will be even higher in the future.
```

### Where was the data currently stored in this dataset sourced from

Google Cloud

### If you are a data preparer. What is your location (Country/Region)

None

### Please share a sample of the data

```text
https://drive.google.com/file/d/15bn7BfG8vv4DEqTIp3dXD_ys8TCQDw4c/view?usp=share_link
https://drive.google.com/file/d/1xhZgSucBzaoqfs5g5RX1LhgAGmpvf_-A/view?usp=share_link
https://drive.google.com/file/d/16Af6k6FOQEmCAiW_Ax2qXT7E6WMn97hW/view?usp=share_link
https://drive.google.com/file/d/1VoNeP7gLbVSp30s2weZWG81Uo-0FGXGP/view?usp=share_link
https://drive.google.com/file/d/1dW9brB_tmpdInItsYhE5qJW-Fvs2afsM/view?usp=share_link
https://drive.google.com/file/d/1K2G20pQ7KURClB6FcmX8B8dxsQKnPP80/view?usp=share_link
https://drive.google.com/file/d/1veP8Utsqd4znacihVFa-9267_YMPO54x/view?usp=share_link
https://drive.google.com/file/d/1ubJF0CIcqkjeoin_RB9cTksWyWR7o17l/view?usp=share_link
https://drive.google.com/file/d/1Zl-KZyuMxs7kpvOrhDnjpoMYaOnExrxu/view?usp=share_link
https://drive.google.com/file/d/152uRUqPhA7v8S0xmaTjNGxXSlSGzbZn8/view?usp=share_link
https://drive.google.com/file/d/1ioj7d9PRrWaqA28zTC3DqMTUDlNd341u/view?usp=share_link
https://drive.google.com/file/d/1EtYdJDv_rGVFpFIMjSX2fiRUJb8J2kca/view?usp=share_link
https://drive.google.com/file/d/1T9BlJkZJLO5exQNrSsmF1qfl-kFpeFDq/view?usp=share_link
https://drive.google.com/file/d/1beIWb-Kg_NSvJ6C8a27aFSjK_pGeFZhf/view?usp=share_link
https://drive.google.com/file/d/1FGYV45D8jccmKHGybjE_T72uLbkaGkQ1/view?usp=share_link
https://drive.google.com/file/d/1B9BsoczbJ8dg02GKh3Ygza31U8JY3D-f/view?usp=share_link
https://drive.google.com/file/d/1D0c_9pWC0Gr7EnNfTdIeqe8PicnxfZlO/view?usp=share_link
https://drive.google.com/file/d/15EMaC8gwttoFrZ9YxAgjzIrvt0ZZCNkt/view?usp=share_link
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

1.5 to 2 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China

### How will you be distributing your data to storage providers

Cloud storage (i.e. S3)

### How do you plan to choose storage providers

Slack, Big Data Exchange

### If you already have a list of storage providers to work with, fill out their names and provider IDs below

```text
SP-Miner-IDs Contact-name SP-Business-Email SP-Organization-Name Region
f01992563 xl.li myhostfly2016@gmail.com	China Unicom Beijing Province Network  Beijing
f01996719 stevin.liu caokun8008@gmail.com AOFEI DATA INTERNATIONAL COMPANY LIMITED	Singapore
f01996817 jack.zhang jackzhang22@gmail.com Central and Western, HK PCCW Global, Inc.	Hong Kong
f02812304 saili saili@gmail.com SY-Tech Singapore
f01992032 lucy.ma 2380549582@qq.com	IDC, China Telecommunications Corporation Beijing
```

### How do you plan to make deals to your storage providers

Boost client, Lotus client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by 87103978** [comment]
Re apply due to https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1357 being closed

**Comment by 87103978** [comment]
<img width="800" alt="image" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/72076505/6d1ef0bc-f6a8-4b4e-be20-53c9efcc3c11">

**Comment by herrehesse** [comment]
You are joking right? Why do you lie so much?

- f01996719 stevin.liu caokun8008@gmail.com AOFEI DATA INTERNATIONAL COMPANY LIMITED	Singapore
- f01996817 jack.zhang jackzhang22@gmail.com Central and Western, HK PCCW Global, Inc.	Hong Kong

**Comment by 87103978** [comment]
@herrehesse Who are you? Why would you say that? We just need to be ready to find the right SPs to store our data.

**Comment by herrehesse** [comment]
@87103978 Kevin, you know as well as I do that the only reason why you requested this LDN is to get datacap and grow miners and their income of block rewards. It's not your fault that this system is designed to allow this type of behaviour. But do not try and explain yourself away.

f01996719 & f01996817 are the same entity using VPN to show a different location. It is as simple as that. You want to grow your QaP with datacap.

**Comment by Sunnyiscoming** [comment]
@87103978 Please explain about that.

**Comment by 87103978** [comment]
I found that you were questioning everyone without reason, regardless of the purpose, which is very discouraging for everyone who wants to store data on the Filecoin network. As you can see, I am a data owner, and through some channels, I have found the listed service providers (SPs) who have provided company entity information and location details. This is the fact. If you have a better verification method, please let me know. Alternatively, if you have SPs that are 100% trustworthy, please also inform me. I simply want to store my data on the Filecoin network. Thank you for your attention.

**Comment by herrehesse** [comment]
Stating "this is a fact" without providing evidence does not strengthen your argument. Given that 99% of LDNs tend to be abusive, and you're offering questionable regions and disreputable storage providers, there's no justification for granting you datacap.

If your goal is to store data on Filecoin, you can proceed without needing datacap (and abuse the program). Simply compensate storage providers for their services to store your data.

**Comment by 87103978** [comment]
Support fil-plus, support filecoin data cap to fight counterfeiting, and oppose obtaining ldn quota by cheating.

**Comment by Filplus-govteam** [comment]
We don't see an SP registration form ever submitted, please submit when you get a chance [Fil+ registration form](https://form.jotform.com/231862753015656)

**Comment by 87103978** [comment]
Anything update？
