### ISSUE TITLE
[DataCap Application] TechGreedy Slingshot Restore Program Assignments 2 and 3

### ISSUE THREAD

**Issue by xinaxu** [filecoin-project/filecoin-plus-large-datasets#227]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: TechGreedy - Xinan Xu - Slingshot Restore
- Website / Social Media: https://www.techgreedy.net/librivox
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 1PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 500 TiB
- On-chain address for first allocation: f1epzplqtkjbp7tik2y2sgqouu3gedai3kygrqk3y

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
My organization has been actively engaged in Filecoin community, including
1. Acting as clients - we have been participating Slingshot competition since 2.1
2. Acting as small Miner - we were part of MinerX program
3. Part of Filecoin enterprise work group
4. Part of Slingshot Restore program cohort
```

**I want to highlight that our team is the first that completes the Slingshot recovery assignment and we would like to continue the recovery for our 2nd and 3rd assignments.**

What is the primary source of funding for this project?
```
Company funding.
```

What other projects/ecosystem stakeholders is this project associated with?
```
Slingshot restore program
https://filecoinproject.slack.com/archives/C01AK1J7TF1/p1639607995023000
```

## Use-case details

Describe the data being stored onto Filecoin
```
Those will be the dataset assigned by Protocol Lab as part of the repair and recovery effort for lost deals due to storage outages.
Our 2nd and 3rd assignment is to store year 2020 and 2021 of Encyclopedia of DNA Elements
```

Where was the data in this dataset sourced from?
```
Those are public dataset that was used in previous Slingshot rounds and can be downloaded from 
https://registry.opendata.aws/encode-project/
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
The data is binary and contains sequence of human genomes.
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
This can be retrieved from AWS open dataset.
```

What is the expected retrieval frequency for this data?
```
A few times per year depending on the roadmap of Slingshot competition and following applications.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
500 to 540 days.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
From our 1st slingshot restore program assignment, we have created great relationship with different storage providers around the world, including USA, Belgium, Netherland, Canada and Australia


```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
The deal will be made offline only. There will be 5 assigned storage providers according to Slingshot restore program.
For domestic storage providers, we will be shipping hard drives. For international storage providers, we will be distributing data to EU datacenter and let them download from there.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
The list of allowed storage providers are provided by Protocol Lab
https://docs.google.com/spreadsheets/d/1Skga2Yn0BD7CDgT1WQmKtPJ3nxhQ4QWd45e78Y42Wjc/edit#gid=0
We have chosen below providers as we have successfully completed the first assignment with their help
Rob, James, Eliovp, Xinan, Harry, Fei Yan, Gregory, Jack
```

How will you be distributing deals across storage providers?
```
Most storage providers will have same amount of deals to accept and seal.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes. I am familiar with the deal making process. It will start once the Slingshot restore program starts.
```

**Comment by galen-mcandrew** [comment]
## Multisig Notary requested
#### Total DataCap requested 
> 1PiB
#### Expected weekly DataCap usage rate 
> 500TiB

**Comment by marinakosti** [comment]
Confirmed XinAn received 2 additional assignments for slingshot restore program totalling 100TiB x 2 assignments x 5 copies = 1,00TiB

**Comment by galen-mcandrew** [comment]
@fabriziogianni7 the first allocation should be kicking off automatically here. Worked in other issues (181 & 182), but didn't pick up here.

**Comment by Fenbushi-Filecoin** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceatfvxibf4zuqt2b5piolyhoecoajz5lvpwhw7nw6f4qeabvvvl6k 
#### Address 
> f1epzplqtkjbp7tik2y2sgqouu3gedai3kygrqk3y
#### Datacap Allocated
> 51.20TiB
#### Signer Address
> f1yqydpmqb5en262jpottko2kd65msajax7fi4rmq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceatfvxibf4zuqt2b5piolyhoecoajz5lvpwhw7nw6f4qeabvvvl6k

**Comment by Reiers** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedp4owjcnfh2gguidsfvpsdn24fbgrgtwxav6w7tdm7fbow6ordx2 
#### Address 
> f1epzplqtkjbp7tik2y2sgqouu3gedai3kygrqk3y
#### Datacap Allocated
> 51.20TiB
#### Signer Address
> f1oz43ckvmtxmmsfzqm6bpnemqlavz4ifyl524chq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedp4owjcnfh2gguidsfvpsdn24fbgrgtwxav6w7tdm7fbow6ordx2

**Comment by Reiers** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced37g6rtfebpznxksc2pixvtlztse4xqyi5bqot3mcluptqmgfclm 
#### Address 
> f1epzplqtkjbp7tik2y2sgqouu3gedai3kygrqk3y
#### Datacap Allocated
> 102.40TiB
#### Signer Address
> f1oz43ckvmtxmmsfzqm6bpnemqlavz4ifyl524chq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced37g6rtfebpznxksc2pixvtlztse4xqyi5bqot3mcluptqmgfclm

**Comment by flyworker** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaxbqb62s5eqttwnxrrlprff7koogflrzhiq5e22o5zeav3a4ufu2 
#### Address 
> f1epzplqtkjbp7tik2y2sgqouu3gedai3kygrqk3y
#### Datacap Allocated
> 102.40TiB
#### Signer Address
> f1hlubjsdkv4wmsdadihloxgwrz3j3ernf6i3cbpy
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaxbqb62s5eqttwnxrrlprff7koogflrzhiq5e22o5zeav3a4ufu2

**Comment by flyworker** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedalc4inb5g6xw6yfqyu56fvz2ihqs5ctim5z3y4p5jdywy5tgrku 
#### Address 
> f1epzplqtkjbp7tik2y2sgqouu3gedai3kygrqk3y
#### Datacap Allocated
> 204.80TiB
#### Signer Address
> f1hlubjsdkv4wmsdadihloxgwrz3j3ernf6i3cbpy
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedalc4inb5g6xw6yfqyu56fvz2ihqs5ctim5z3y4p5jdywy5tgrku

**Comment by Fenbushi-Filecoin** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedcht2lbjj6was6tczlx4j4hzjvxlc5kinkjbv4qg7t7h2ccly5ow 
#### Address 
> f1epzplqtkjbp7tik2y2sgqouu3gedai3kygrqk3y
#### Datacap Allocated
> 204.80TiB
#### Signer Address
> f1yqydpmqb5en262jpottko2kd65msajax7fi4rmq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedcht2lbjj6was6tczlx4j4hzjvxlc5kinkjbv4qg7t7h2ccly5ow

**Comment by dannyob** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceboryxwtvf7kduw2rvrdo4ccviqvkh7a5fwquc4vi2bobdtdxefbc 
#### Address 
> f1epzplqtkjbp7tik2y2sgqouu3gedai3kygrqk3y
#### Datacap Allocated
> 409.60TiB
#### Signer Address
> f1k6wwevxvp466ybil7y2scqlhtnrz5atjkkyvm4a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceboryxwtvf7kduw2rvrdo4ccviqvkh7a5fwquc4vi2bobdtdxefbc

**Comment by MegTei** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecorbsppotbyk5la33vvhljc2vcsvp7kx6oeqzwwjeuq3ffuj4com 
#### Address 
> f1epzplqtkjbp7tik2y2sgqouu3gedai3kygrqk3y
#### Datacap Allocated
> 409.60TiB
#### Signer Address
> f1ystxl2ootvpirpa7ebgwl7vlhwkbx2r4zjxwe5i
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecorbsppotbyk5la33vvhljc2vcsvp7kx6oeqzwwjeuq3ffuj4com

**Comment by Fenbushi-Filecoin** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaztzar2ovveetgtvdbital7uukpalspwj4naaqxcqvlzjzjdcfuy 
#### Address 
> f1epzplqtkjbp7tik2y2sgqouu3gedai3kygrqk3y
#### Datacap Allocated
> 256.00TiB
#### Signer Address
> f1yqydpmqb5en262jpottko2kd65msajax7fi4rmq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaztzar2ovveetgtvdbital7uukpalspwj4naaqxcqvlzjzjdcfuy

**Comment by MegTei** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedprf5gknx36l6dawll3xpej5aivtm72rgjlj6eqb4tn74ctl42wu 
#### Address 
> f1epzplqtkjbp7tik2y2sgqouu3gedai3kygrqk3y
#### Datacap Allocated
> 256.00TiB
#### Signer Address
> f1ystxl2ootvpirpa7ebgwl7vlhwkbx2r4zjxwe5i
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedprf5gknx36l6dawll3xpej5aivtm72rgjlj6eqb4tn74ctl42wu

**Comment by flyworker** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedzify4tzknqi3o3xxsn7datynwgxkoinugqyzvx6ihfsmbvg55nu 
#### Address 
> f1epzplqtkjbp7tik2y2sgqouu3gedai3kygrqk3y
#### Datacap Allocated
> 256.00TiB
#### Signer Address
> f1hlubjsdkv4wmsdadihloxgwrz3j3ernf6i3cbpy
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedzify4tzknqi3o3xxsn7datynwgxkoinugqyzvx6ihfsmbvg55nu

**Comment by filplus-checker** [comment]
## DataCap and CID Checker Report[^1]
 - Organization: `TechGreedy - Xinan Xu - Slingshot Restore`
 - Client: `f1epzplqtkjbp7tik2y2sgqouu3gedai3kygrqk3y`
### Storage Provider Distribution
The below table shows the distribution of storage providers that have stored data for this client.

If this is the first time a provider takes verified deal, it will be marked as `new`.

For most of the datacap application, below restrictions should apply.
 - Storage provider should not exceed 25% of total datacap.
 - Storage provider should not be storing duplicate data for more than 20%.
 - Storage provider should have published its public IP address.
 - All storage providers should be located in different regions.

⚠️ 34.97% of total deal sealed by [f01702940](https://filfox.info/en/address/f01702940) are duplicate data.

| Provider                                                    |                     Location | Total Deals Sealed | Percentage | Unique Data | Duplicate Deals |
| :---------------------------------------------------------- | ---------------------------: | -----------------: | ---------: | ----------: | --------------: |
| [f01652333](https://filfox.info/en/address/f01652333)       |    Sunnyvale, California, US |         215.16 TiB |     21.05% |  210.34 TiB |           2.24% |
| [f01732188](https://filfox.info/en/address/f01732188)`new`  |        Chicago, Illinois, US |         211.25 TiB |     20.67% |  211.19 TiB |           0.03% |
| [f01907460](https://filfox.info/en/address/f01907460)`new`  |      Seattle, Washington, US |         162.81 TiB |     15.93% |  162.81 TiB |           0.00% |
| [f01752548](https://filfox.info/en/address/f01752548)       |      Seattle, Washington, US |         153.86 TiB |     15.05% |  153.02 TiB |           0.55% |
| [f01775922](https://filfox.info/en/address/f01775922)`new`  |        Ashburn, Virginia, US |          92.53 TiB |      9.05% |   92.44 TiB |           0.10% |
| [f01832393](https://filfox.info/en/address/f01832393)       |      Seattle, Washington, US |          91.88 TiB |      8.99% |   91.88 TiB |           0.00% |
| [f0838923](https://filfox.info/en/address/f0838923)         |      Seattle, Washington, US |          24.25 TiB |      2.37% |   24.25 TiB |           0.00% |
| [f01851231](https://filfox.info/en/address/f01851231)`new`  |      Seattle, Washington, US |          18.13 TiB |      1.77% |   18.13 TiB |           0.00% |
| [f01157271](https://filfox.info/en/address/f01157271)       |  Sydney, New South Wales, AU |          15.22 TiB |      1.49% |   15.22 TiB |           0.00% |
| [f01702940](https://filfox.info/en/address/f01702940)       |            Dallas, Texas, US |          14.03 TiB |      1.37% |    9.13 TiB |          34.97% |
| [f01345523](https://filfox.info/en/address/f01345523)       |      Antwerpen, Flanders, BE |          10.69 TiB |      1.05% |   10.66 TiB |           0.29% |
| [f01611097](https://filfox.info/en/address/f01611097)       | San Clemente, California, US |           7.34 TiB |      0.72% |    7.34 TiB |           0.00% |
| [f01385207](https://filfox.info/en/address/f01385207)       |        Lincoln, Nebraska, US |           5.00 TiB |      0.49% |    5.00 TiB |           0.00% |

![Provider Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/227/1671094246873.png)
### Deal Data Replication
The below table shows how each many unique data are replicated across storage providers.
- No more than 25% of unique data are stored with less than 4 providers.

⚠️ 55.32% of deals are for data replicated across less than 4 storage providers.

| Unique Data Size | Total Deals Made | Number of Providers | Deal Percentage |
| ---------------: | ---------------: | ------------------: | --------------: |
|       273.14 TiB |       273.14 TiB |                   1 |          26.72% |
|        59.03 TiB |       118.16 TiB |                   2 |          11.56% |
|        56.22 TiB |       174.19 TiB |                   3 |          17.04% |
|        40.53 TiB |       162.25 TiB |                   4 |          15.87% |
|        48.66 TiB |       245.47 TiB |                   5 |          24.02% |
|         7.69 TiB |        48.94 TiB |                   6 |           4.79% |

![Replication Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/227/1671094247544.png)
### Deal Data Shared with other Clients
The below table shows how many unique data are shared with other clients.
Usually different applications owns different data and should not resolve to the same CID.

⚠️ CID sharing has been observed.

| Other Client                                                                                                          | Application                                                                                                                | Total Deals Affected | Unique CIDs |  Verifier |
| :-------------------------------------------------------------------------------------------------------------------- | :------------------------------------------------------------------------------------------------------------------------- | -------------------: | ----------: | --------: |
| [f12uknfljr246uisb4ww7y5z4girbefdqpi4fi64y](https://filfox.info/en/address/f12uknfljr246uisb4ww7y5z4girbefdqpi4fi64y) | [TechGreedy \- Xinan Xu \- Slingshot Restore](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/138) |             1.05 PiB |       6,802 | LDN # 138 |

[^1]: To manually trigger this report, add a comment with text `checker:manualTrigger`

**Comment by sklay** [comment]
👌 @
