### ISSUE TITLE
 [DataCap Application] <hashfin-02>

### ISSUE THREAD

**Issue by qituo** [filecoin-project/filecoin-plus-large-datasets#2270]
### Data Owner Name

hashfin

### What is your role related to the dataset

Dataset Owner

### Data Owner Country/Region

Japan

### Data Owner Industry

Web3 / Crypto

### Website

https://www.hashfin.com

### Social Media

```text
https://www.bloks.io/account/hashfineosio

1: EOS whole node data

2: Log data of EOS project,

3: Log data of 7 currencies of staging;

4: Our statistics on staging;

5: We distribute the platform project data of staging revenue ourselves;
```

### Total amount of DataCap being requested

5PiB

### Expected size of single dataset (one copy)

32G

### Number of replicas to store

5

### Weekly allocation of DataCap requested

400TiB

### On-chain address for first allocation

f1lgbffxfxen7ok2cgkhscgqhcynzxkapj7opofsa

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
This project is a project that we have been working on staging since 2019. At present, our EOS has voted 160 million votes, ranking sixth in the whole network. Other projects are also under way. We want to store our data on filecoin. I hope to get approval. Thank you
```

### Is this project associated with other projects/ecosystem stakeholders?

Yes

### Describe the data being stored onto Filecoin

```text
1: EOS whole node data

2: Log data of EOS project,

3: Log data of 7 currencies of staging;

4: Our statistics on staging;

5: We distribute the platform project data of staging revenue ourselves;
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### If you are a data preparer. What is your location (Country/Region)

None

### Please share a sample of the data

```text
1: EOS whole node data

2: Log data of EOS project,

3: Log data of 7 currencies of staging;

4: Our statistics on staging;

5: We distribute the platform project data of staging revenue ourselves;
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [ ] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

1.5 to 2 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America

### How will you be distributing your data to storage providers

HTTP or FTP server

### How do you plan to choose storage providers

Slack, Big Data Exchange

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by herrehesse** [comment]
How is this application validated instantly and opened an allocation?

**Comment by qituo** [comment]
checker:manualTrigger

**Comment by herrehesse** [comment]
![Screenshot 2023-11-13 at 13 04 50](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/70132857/240613de-f751-4d54-bc15-c1eda9e1d99d)


Multiple SP's in this LDN are known large scale abusers with zero retieval and VPN abuse (fake locations)

![Screenshot 2023-11-13 at 13 05 28](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/70132857/9bbca042-4df1-4892-b556-485aa6eb195e)

@kevzak Please close this LDN since this is fraud.

**Comment by Filplus-govteam** [comment]
This application wasn't triggered, closing and opening a bug issue to determine what happened
