### ISSUE TITLE
[DataCap Application] <Organization> - <XHY-SX>

### ISSUE THREAD

**Issue by xxccli** [filecoin-project/filecoin-plus-large-datasets#2271]
### Data Owner Name

XHY-SX

### What is your role related to the dataset

Dataset Owner

### Data Owner Country/Region

China

### Data Owner Industry

Arts & Recreation

### Website

https://www.jinyegroup.cn/

### Social Media

```text
WeChat：yqwy2019
```

### Total amount of DataCap being requested

5PiB

### Expected size of single dataset (one copy)

200TiB

### Number of replicas to store

10

### Weekly allocation of DataCap requested

200TiB

### On-chain address for first allocation

f12ma25hth5owtobz2rcwjyrje3eqouypnqwgdm2i

### Data Type of Application

Public, Open Commercial/Enterprise

### Custom multisig

- [ ] Use Custom Multisig

### Identifier

No response

### Share a brief history of your project and organization

```text
Share a brief history of your project and organization
Shaanxi Jinye Science and Education Group Co., Ltd. is a diversified group company whose main businesses are higher education, tobacco products and medical care industries. 
The group headquarters is located in Building B, City Gate, Business Core Area, Xi'an High-tech Industrial Development Zone, China ,
the group is a company listed on the main board of the Shenzhen Stock Exchange,
with the stock abbreviation of "Shaanxi Jinye" (stock code: 000812),   and currently has more than 2,000 employees.
```

### Is this project associated with other projects/ecosystem stakeholders?

Yes

### If answered yes, what are the other projects/ecosystem stakeholders

```text
No response
```

### Describe the data being stored onto Filecoin

```text
Our data consists primarily of images and documents displayed within the printing plant.
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### If you are a data preparer. What is your location (Country/Region)

China

### If you are a data preparer, how will the data be prepared? Please include tooling used and technical details?

```text
louts
```

### Please share a sample of the data

```text
I have put the data sample in this link. 
https://drive.google.com/file/d/1lDLyv9ANQ6fjKV5j7PNw6kc2WjAvS-d3/view?usp=drive_link
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Daily

### For how long do you plan to keep this dataset stored on Filecoin

More than 3 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China

### How will you be distributing your data to storage providers

Shipping hard drives

### How do you plan to choose storage providers

Slack, Big Data Exchange, Partners

### How do you plan to make deals to your storage providers

Lotus client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by herrehesse** [comment]
New account, 5PiB, no packing knowledge, no SP list and no reputation.

**Comment by xxccli** [comment]
We have encapsulated nodes for filecoin 
Miner  ID                             City |  Continent |
 f01881191 (32 GiB sectors)  xi‘’an   CN 
 f02006333 (32 GiB sectors)  xi‘’an   CN 
 f01935333 (32 GiB sectors)  xi‘’an   CN

**Comment by herrehesse** [comment]
Yes as i thought, mostly self-dealing to make additional revenue with the datacap multiplier.

**Comment by xxccli** [comment]
Through data storage of its own data and data from the same industry, it drives the development of industry storage. This will further promote the application of filecoin in the printing and publishing industry.

**Comment by herrehesse** [comment]
Actually, miners in your area are not permitted to retain customer data because of local government regulations. Their primary function is to mine Filecoin, and applying a multiplier serves to enhance their revenue, independent of the program's regulations.

**Comment by data-programs** [comment]
<img width="32" alt="KYC" Verified src="https://stable.filplus.storage/images/filplus-kyc-verified-badge.png"/>

This user’s identity has been verified through [filplus.storage](https://filplus.storage)

**Comment by xxccli** [comment]
The stored data are files with corresponding copyrights that are designed to be disclosed and can be stored in compliance with relevant legal regulations.

**Comment by Sunnyiscoming** [comment]
- Has this dataset been stored on Filecoin before? If so, why are you choosing to store it again?
- Best practice for storing large datasets includes ideally, storing it in 3 or more regions, with 4 or more storage provider operators or owners.You should list Miner ID, Business Entity, Location of sps you will cooperate with.
- Per the https://github.com/filecoin-project/notary-governance/issues/922 for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

**Comment by xxccli** [comment]
The data itself is not stored in filecoin, but on the private storage network within the enterprise.
The following is the cooperative sp

Already registered, please check
![QQ截图20231108071433](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/54037574/d146064d-cb03-4b74-a388-1a73f0bb7589)

**Comment by herrehesse** [comment]
The following is the cooperative sp ?

**Comment by xxccli** [comment]
The following is the cooperation sp
![QQ截图20231111063249](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/54037574/f4a7ecfc-d145-4c15-88e1-84b887c8e2f1)

**Comment by herrehesse** [comment]
@xxccli self-dealing is not allowed.

@kevzak please close this LDN.

**Comment by xxccli** [comment]
> > 以下是合作SP ![QQ截图20231111063249](https://user-images.githubusercontent.com/54037574/282192245-f4a7ecfc-d145-4c15-88e1-84b887c8e2f1.png)
> 
> SPs should come from different regions.
add sp
f0500878 | liming ding | Pilot star | Hong Kong

**Comment by herrehesse** [comment]
Can we close this LDN please?

**Comment by xxccli** [comment]
> Can we close this LDN please?
We are actively seeking cooperation with other regional SPs and doing our best to be more compliant with fil+ requirements

**Comment by Filplus-govteam** [comment]
We don't see an SP registration form ever submitted, please submit when you get a chance

**Comment by Filplus-govteam** [comment]
Link is here https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/2271#issuecomment-1798840228
