### ISSUE TITLE
[DataCap Application] LAMOST DR7

### ISSUE THREAD

**Issue by stroage** [filecoin-project/filecoin-plus-large-datasets#2273]
### Data Owner Name

LAMOST DR7

### What is your role related to the dataset

Data Preparer

### Data Owner Country/Region

United States

### Data Owner Industry

Life Science / Healthcare

### Website

http://www.lamost.org/dr7/v2.0/

### Social Media

```text
http://www.lamost.org/dr7/v2.0/
```

### Total amount of DataCap being requested

15PiB

### Expected size of single dataset (one copy)

1.67PiB

### Number of replicas to store

9

### Weekly allocation of DataCap requested

1PiB

### On-chain address for first allocation

f1shskrtkbfzgycly3ehmgp5v3xwtpgvtrr4gbzmi

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Observed Plates：4,922 Total Spectra：10,431,197

Guoshoujing Telescope (the Large Sky Area Multi-Object Fiber Spectroscopic Telescope LAMOST) is a National Major Scientific Project built by the Chinese Academy of Sciences. Funding for the project has been provided by the National Development and Reform Commission. LAMOST is operated and managed by the National Astronomical Observatories, Chinese Academy of Sciences.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
Observed Plates：4,922 Total Spectra：10,431,197

Guoshoujing Telescope (the Large Sky Area Multi-Object Fiber Spectroscopic Telescope LAMOST) is a National Major Scientific Project built by the Chinese Academy of Sciences. Funding for the project has been provided by the National Development and Reform Commission. LAMOST is operated and managed by the National Astronomical Observatories, Chinese Academy of Sciences.
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### If you are a data preparer. What is your location (Country/Region)

Singapore

### Please share a sample of the data

```text
http://www.lamost.org/dr7/v2.0/search#gaiaconstraints
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Sporadic

### For how long do you plan to keep this dataset stored on Filecoin

1.5 to 2 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, Europe

### How will you be distributing your data to storage providers

Cloud storage (i.e. S3), HTTP or FTP server, IPFS, Shipping hard drives, Lotus built-in data transfer

### How do you plan to choose storage providers

Slack, Filmine, Partners

### How do you plan to make deals to your storage providers

Boost client, Lotus client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by herrehesse** [comment]
Entities last LDN was closed due to not adhering to the rules of FIL+ @kevzak

**Comment by kevzak** [comment]
@stroage please list all SP entities involved in this dataset

**Comment by stroage** [comment]
This is the follow-up of 2213:  the 2213 cooperation  SP has not fully started，so it has been closed, now we have re-contacted SP, we are all ready, thank you.

**Comment by stroage** [comment]
#2213

**Comment by stroage** [comment]
We decided to close 2273 and reply to 2213. hope you can reopen 2213. @kevzak

**Comment by stroage** [comment]
Since #2213 didn't respond, we reopened 2273

**Comment by stroage** [comment]
| Provider  |                            Location | SP Entity or Personal |
| :-------- | ----------------------------------: | --------------------: |
| f02850067 |    HK |              datastone |
| f02850071 |    HK |             datastone |
| f02837094 |    HK |              datastone |
| f02837094 |    HK |              datastone |
| f02816095 |   Singapore |              KRAL |
| f02816081|   Singapore |              KRAL |
| f02829200 |  JiangXi|              applecould |
| f02824157 |   Shenzhen |             ZhongChuangYun |
| f02824140 |   Shenzhen |             ZhongChuangYun |

**Comment by stroage** [comment]
We have disclosed all the SPs we cooperate with and hope to get your help as soon as possible. Thank you.

**Comment by herrehesse** [comment]
If i take a quick look, they are all in CN.

**Comment by Filplus-govteam** [comment]
@stroage For Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data so they can be validated

**Comment by stroage** [comment]
@Filplus-govteam hey, we have experience in #2213, we have already filled it in 2213, just because 2213 was closed, so we can only reapply, now we have decided to close 2273, reply to the question of 2213, list all cooperative sp , hope to see you open it for us, thank you.
