### ISSUE TITLE
[DataCap Application] <MetaEra GLOBLE LIMITED>

### ISSUE THREAD

**Issue by CockroachBoss** [filecoin-project/filecoin-plus-large-datasets#2274]
### Data Owner Name

MetaEra

### What is your role related to the dataset

Dataset Owner

### Data Owner Country/Region

Hong Kong

### Data Owner Industry

Web3 / Crypto

### Website

https://metaera.hk/

### Social Media

```text
Meta Era Website：https://metaera.hk/

Meta Era Twitter EN：https://twitter.com/MetaEra_Media

Meta Era Twitter CN：https://twitter.com/MetaEraCN

Meta Era Telegram Group：https://t.me/METAERAofficial

Meta Era Telegram Channel ：https://t.me/metaeranews

Meta Era LinkedIn：https://www.linkedin.com/company/metaeramedia/

Meta Era Wechat Public：Meta Era Global

Meta Era Wechat：MetaEraGlobal

Meta Era YouTube：https://www.youtube.com/@MetaEraCN

Mera Era TikTok: https://www.tiktok.com/@meteeramedia
```

### Total amount of DataCap being requested

5PiB

### Expected size of single dataset (one copy)

700T

### Number of replicas to store

8

### Weekly allocation of DataCap requested

800TiB

### On-chain address for first allocation

f1k6evrqoxb2kmxjxqeh6awlztqnj6kyio46hgnqa

### Data Type of Application

Public, Open Commercial/Enterprise

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Meta Era is a distinguished media outlet based in Hong Kong that advocates for the expansion of Web 3.0 technology across Asia and worldwide. We pride ourselves on delivering precise, professional information to our audience, and have fostered strong alliances with numerous investment institutions, cutting-edge Web 3.0 enterprises, and influential industry media and communities.

Beyond our regular content, Meta Era also spearheads large-scale online summits and impactful offline conferences, cementing our status as a significant influencer in the industry. With our dedicated focus on the digital frontier, we are paving the way for the new era of the internet - a Meta Era.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### If answered yes, what are the other projects/ecosystem stakeholders

```text
No response
```

### Describe the data being stored onto Filecoin

```text
Corporate data, mainly high-definition video files as well as high-precision promotional images and so on.
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### If you answered "Other" in the previous question, enter the details here

```text
No response
```

### If you are a data preparer. What is your location (Country/Region)

Hong Kong

### If you are a data preparer, how will the data be prepared? Please include tooling used and technical details?

```text
I am an enterprise data storage data owner and preparer and we currently store our data in our own storage devices. The main focus is on cloud storage and server room equipment storage. We will subsequently transfer the data via online transfer and hard drive mailing.
```

### If you are not preparing the data, who will prepare the data?  (Provide name and business)

```text
No response
```

### Has this dataset been stored on the Filecoin network before? If so, please explain and make the case why you would like to store this dataset again to the network. Provide details on preparation and/or SP distribution.

```text
We'll disclose the details in the github comments!
```

### Please share a sample of the data

```text
https://drive.google.com/file/d/1SErtZofR34bVN-ZAG-K9slHtTkz32GH1/view?usp=drive_link
https://drive.google.com/file/d/10P4qnGpxYmNw0NaygRYyu-NTHzdtARWg/view?usp=sharing
https://drive.google.com/file/d/1fSGT7kzOhiYxJNCS85kFPovAtR5K0wEr/view?usp=sharing
https://drive.google.com/file/d/1pJxuzwi9QpZBdSHkPQlb5cly7G4edDs6/view?usp=drive_link
https://drive.google.com/file/d/1ES4vdU6AovjHJYnNiXc28me_GIj3PkK0/view?usp=drive_link
https://drive.google.com/file/d/186fDpIfVpL92b9yMw0uClHW6o5mUZqAo/view?usp=drive_link
https://drive.google.com/file/d/1YWNtH1HpCyHqoqzuSNMhnpfzdVrwBerS/view?usp=drive_link
https://drive.google.com/file/d/1GyLn7t9Y13oP6XCdAMnkvGO_4UeN34BO/view?usp=drive_link
https://drive.google.com/file/d/1U9UFoFQDGscN37ruh33yEoE3ShfEWvih/view?usp=drive_link
https://drive.google.com/file/d/17eebMkG47i888mF_FV3gVjDmf6imYw_P/view?usp=drive_link
https://drive.google.com/file/d/1nMwF1ZgD9VQ0GGNBkcpAbgU7wBVhu60I/view?usp=drive_link
https://drive.google.com/file/d/1BjSUPSGgalrHeZCJnQwb5btLzpdqYD4O/view?usp=drive_link
https://e0zu9q0wme4.feishu.cn/file/GxnubC0esoUvVmxuV48cnxFznmZ?from=from_copylink
https://sbyxu2l9z8.feishu.cn/file/GWs4b1jO8o5EXxxNAN1cLamHn0f
https://e0zu9q0wme4.feishu.cn/file/MO7JbmEqRoLh1dxSLVdcZADNn4b
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### If you chose not to confirm, what was the reason

```text
No response
```

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

1.5 to 2 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America

### How will you be distributing your data to storage providers

Cloud storage (i.e. S3), HTTP or FTP server, IPFS, Shipping hard drives

### How do you plan to choose storage providers

Slack, Big Data Exchange, Partners

### If you answered "Others" in the previous question, what is the tool or platform you plan to use

```text
No response
```

### If you already have a list of storage providers to work with, fill out their names and provider IDs below

```text
No response
```

### How do you plan to make deals to your storage providers

Boost client, Lotus client

### If you answered "Others/custom tool" in the previous question, enter the details here

```text
No response
```

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by data-programs** [comment]
<img width="32" alt="KYC" Verified src="https://stable.filplus.storage/images/filplus-kyc-verified-badge.png"/>

This user’s identity has been verified through [filplus.storage](https://filplus.storage)

**Comment by Sunnyiscoming** [comment]
- Have you prepared enough token for sector pledge?
- Best practice for storing large datasets includes ideally, storing it in 3 or more regions, with 4 or more storage provider operators or owners.You should list Miner ID, Business Entity, Location of sps you will cooperate with.
- Per the https://github.com/filecoin-project/notary-governance/issues/922 for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

**Comment by CockroachBoss** [comment]
@Sunnyiscoming 
1、yes.
2、Well, we will disclose the details in the from table below.
3、Submitted

**Comment by herrehesse** [comment]
please add the contact information of the SP entities you are working with to store copies of the data.

**Comment by CockroachBoss** [comment]
This application form needs to remain open

**Comment by Sunnyiscoming** [comment]
Please provide ID, City, Country, Organization of each SP here.

**Comment by CockroachBoss** [comment]
@Sunnyiscoming @Filplus-govteam

Is there any update here?

**Comment by Filplus-govteam** [comment]
OK @CockroachBoss thank you for the SP information

**Comment by Sunnyiscoming** [comment]
SP List provided:
[{"providerID":"f01852363","City":"XYZ","Country":"Singapore","SPOrg","HectorLi"},
{"providerID":"f01853077","City":"XYZ","Country":"Singapore","SPOrg","Alpha100"},
{"providerID":"f02837293","City":"XYZ","Country":"South Korea","SPOrg","FiveByte"},
{"providerID":"f02363742","City":"shenzhen","Country":"CN","SPOrg","66File"},
{"providerID":"f02274508","City":"hongkong","Country":"CN","SPOrg","H&W"},]

**Comment by CockroachBoss** [comment]
Keep it open.

**Comment by CockroachBoss** [comment]
Keep it open.

**Comment by PluskitOfficial** [comment]
checker:manualTrigger
