### ISSUE TITLE
[DataCap Application] <Leek Lab>

### ISSUE THREAD

**Issue by Dictators** [filecoin-project/filecoin-plus-large-datasets#2275]
### Data Owner Name

 Leek Lab

### What is your role related to the dataset

Dataset Owner

### Data Owner Country/Region

China

### Data Owner Industry

Information, Media & Telecommunications

### Website

https://space.bilibili.com/329519036

### Social Media

```text
https://space.bilibili.com/329519036
```

### Total amount of DataCap being requested

10PiB

### Expected size of single dataset (one copy)

32G

### Number of replicas to store

8

### Weekly allocation of DataCap requested

1PiB

### On-chain address for first allocation

f1g555fn7cumpu3pw3vljex2t4nhattwigoqbe5ey

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
The leek laboratory is an experimental platform for evaluating various scientific and technological products and daily necessities to avoid being cheated and to recycle various electronic products. It is committed to building a world famous platform to avoid consumers being cheated
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
Some videos, pictures, pictures, documents and other materials we recorded.
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### If you are a data preparer. What is your location (Country/Region)

None

### Please share a sample of the data

```text
https://www.bilibili.com/video/BV14S4y1E7g6/?spm_id_from=333.999.0.0&vd_source=0eabdc807a75e221f5ef3f41500aee38
https://www.bilibili.com/video/BV1HY4y1s7UB/?spm_id_from=333.999.0.0&vd_source=0eabdc807a75e221f5ef3f41500aee38
https://www.bilibili.com/video/BV1KY4y1v7Qj/?spm_id_from=333.999.0.0&vd_source=0eabdc807a75e221f5ef3f41500aee38
https://www.bilibili.com/video/BV1Gq4y1f7ZV/?spm_id_from=333.999.0.0&vd_source=0eabdc807a75e221f5ef3f41500aee38
https://www.bilibili.com/video/BV1Db4y1D7Wf/?spm_id_from=333.999.0.0&vd_source=0eabdc807a75e221f5ef3f41500aee38
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Daily

### For how long do you plan to keep this dataset stored on Filecoin

More than 3 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, Australia (continent)

### How will you be distributing your data to storage providers

Cloud storage (i.e. S3), Lotus built-in data transfer

### How do you plan to choose storage providers

Slack, Filmine, Partners

### How do you plan to make deals to your storage providers

Boost client, Lotus client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Dictators** [comment]
Re apply due to https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1007 being closed

**Comment by Dictators** [comment]
https://submit.jotform.com/231862753015656

**Comment by Dictators** [comment]
![aaa](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/24631857/57356e33-179e-44d6-8ab5-99687fa5379f)

**Comment by Sunnyiscoming** [comment]
- Are these 290 videos the only ones to be stored? What is the total amount of data in these 290 videos?
- Are you a data preparer? What is your previous experience as a data-preparer? List previous applications and client IDs
- How will the data be prepared? Please include tooling used and technical details
- If you are not preparing the data, who will prepare the data?  (Name and Business)
- Has this dataset been stored on Filecoin before? If so, why are you choosing to store it again?
- Best practice for storing large datasets includes ideally, storing it in 3 or more regions, with 4 or more storage provider operators or owners.You should list Miner ID, Business Entity, Location of sps you will cooperate with.

**Comment by herrehesse** [comment]
f01992032 Beijing
f01992563 Beijing
f01996719 Singapore
f01996817 Herndon


Yeah sure buddy. My wallet 1234 1235 and 1236 are on completely different locations and totally not from the same owner. I am very serious.

@kevzak Please close this LDN.

**Comment by Dictators** [comment]
@herrehesse  Are you the storage provider, or the storage provider that you are sure there are no problems, can you introduce me? If possible, we are also happy to store the data in more storage providers, please

**Comment by herrehesse** [comment]
@Dictators Since your above lists shows that you store at one single entity, I have a hard time to believe your actions and intentions are legitimate. I will not support this.

**Comment by Dictators** [comment]
@herrehesse Please read what I'm saying, okay? Do you understand? It's weird

**Comment by herrehesse** [comment]
Here are a few proper SP's with high reputation.


Provider | Location
-- | --
f02806702 | Sydney, New South Wales, AUAndrew Sjoquist Enterprises Pty Ltd
f02806693 | Sydney, New South Wales, AUAndrew Sjoquist Enterprises Pty Ltd
f02806700 | Sydney, New South Wales, AUAndrew Sjoquist Enterprises Pty Ltd
f01611097 | Irvine, California, USAT&T Services, Inc.
f097777 | Otyniia, Ivano-Frankivsk, UABranch Enterprise "Netgroup-Service"
f010479 | Paris, Île-de-France, FRCELESTE SAS
f01345523 | Antwerpen, Flanders, BECogent Communications
f01864397 | Zaventem, Flanders, BECogent Communications
f01907556 | Sharjah, Sharjah, AEEMIRATES TELECOMMUNICATIONS GROUP COMPANY (ETISALAT GROUP) PJSC
f020378 | Asenovgrad, Plovdiv, BGESCOM Ltd. - Haskovo
f01392893 | Utrecht, Utrecht, NLFusix Networks B.V.
f02055660 | Sydney, New South Wales, AUHurricane Electric LLC
f0773157 | Sydney, New South Wales, AUHurricane Electric LLC
f01227505 | Incheon, Incheon, KRKorea Telecom
f0717969 | Los Angeles, California, USKrypt Technologies
f01163272 | Perm, Perm Krai, RUPJSC Rostelecom
f0706693 | Brest, Brest, BYRepublican Unitary Telecommunication Enterprise Beltelecom
f02832654 | Chicago, Illinois, USServer Central Network
f01943041 | Marlow, England, GBSwish Fibre Ltd
f01786387 | Heerhugowaard, North Holland, NLWijnand Schouten
f01771403 | Heerhugowaard, North Holland, NLWijnand Schouten
f02366527 | Heerhugowaard, North Holland, NLWijnand Schouten
f01720359 | Heerhugowaard, North Holland, NLWijnand Schouten

**Comment by Dictators** [comment]
Ok, any update?

**Comment by Dictators** [comment]
@Filplus-govteam Can you send me a link? Let me add. Thank you

**Comment by Filplus-govteam** [comment]
Please also complete all the questions on the application

**Comment by Sunnyiscoming** [comment]
Please provide ID, City, Country, Organization of each SP here.

**Comment by Dictators** [comment]
Ok, let's fill it out here

**Comment by Dictators** [comment]
ok

**Comment by Dictators** [comment]
Open it, please. We still need an sp. Looking for it
