### ISSUE TITLE
[DataCap Application] <Organization> - <Events data & Videos> 

### ISSUE THREAD

**Issue by Metainsightofficial** [filecoin-project/filecoin-plus-large-datasets#2277]
### Data Owner Name

Metainsight (HONG KONG B&H TECHNOLOGY CO., LIMITED)

### What is your role related to the dataset

Dataset Owner

### Data Owner Country/Region

Hong Kong

### Data Owner Industry

Information, Media & Telecommunications

### Website

https://twitter.com/Metainsight2022

### Social Media

```text
Twitter:@Metainsight2022
```

### Total amount of DataCap being requested

5PiB

### Expected size of single dataset (one copy)

500T

### Number of replicas to store

10

### Weekly allocation of DataCap requested

500TiB

### On-chain address for first allocation

f17lmyguhyvvsjo5yl4purihgqndbvhw4dlagupeq

### Data Type of Application

Public, Open Commercial/Enterprise

### Custom multisig

- [ ] Use Custom Multisig

### Identifier

No response

### Share a brief history of your project and organization

```text
Metainsight, the main body of the company is located in Hong Kong, China (HONG KONG MEET TECHNOLOGY CO., LIMITED).
The team was established in November 2019 and was invested and incubated by Bitrise Capital. Currently relying on media consulting, marketing planning, conference activities, public relations, creative design and other products and services, by combining the information flow of the blockchain industry with customized services, creating Blockchain industry-leading information service platform.
At present, the team has held several thousand-person summits in the blockchain industry and nearly a hundred online activities, with more than 200 cooperative enterprises and institutions, covering more than 2 million users.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### If answered yes, what are the other projects/ecosystem stakeholders

```text
No response
```

### Describe the data being stored onto Filecoin

```text
Events videos、recordings、files of programs from daily events,host Spaces on twitters.
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### If you answered "Other" in the previous question, enter the details here

```text
No response
```

### If you are a data preparer. What is your location (Country/Region)

Hong Kong

### If you are a data preparer, how will the data be prepared? Please include tooling used and technical details?

```text
HTTP or FTP server, IPFS, Shipping hard drives, Lotus built-in data transfer
```

### If you are not preparing the data, who will prepare the data?  (Provide name and business)

```text
No response
```

### Has this dataset been stored on the Filecoin network before? If so, please explain and make the case why you would like to store this dataset again to the network. Provide details on preparation and/or SP distribution.

```text
No
```

### Please share a sample of the data

```text
https://twitter.com/i/spaces/1lPKqBjEvWNGb
https://twitter.com/i/spaces/1YqGoAbWXngxv
https://twitter.com/i/spaces/1MnxnpOVEbMGO
https://twitter.com/i/spaces/1MYxNgQLBWvKw
https://twitter.com/i/spaces/1DXGyvLPZebJM
https://twitter.com/i/spaces/1yoJMZqjeVXxQ
https://twitter.com/i/spaces/1ypJddlRVkaJW
https://twitter.com/i/spaces/1PlJQpYgZgNGE
https://twitter.com/i/spaces/1MYxNgPDXZZKw
https://medium.com/@metakey2022
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### If you chose not to confirm, what was the reason

```text
No response
```

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

1.5 to 2 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China

### How will you be distributing your data to storage providers

Cloud storage (i.e. S3), HTTP or FTP server, IPFS, Shipping hard drives, Lotus built-in data transfer, Venus built-in data transfer

### How do you plan to choose storage providers

Slack, Filmine, Big Data Exchange, Partners

### If you answered "Others" in the previous question, what is the tool or platform you plan to use

```text
No response
```

### If you already have a list of storage providers to work with, fill out their names and provider IDs below

```text
No response
```

### How do you plan to make deals to your storage providers

Boost client

### If you answered "Others/custom tool" in the previous question, enter the details here

```text
No response
```

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by data-programs** [comment]
<img width="32" alt="KYC" Verified src="https://stable.filplus.storage/images/filplus-kyc-verified-badge.png"/>

This user’s identity has been verified through [filplus.storage](https://filplus.storage)

**Comment by Sunnyiscoming** [comment]
- Please provide more data samples to prove that you have 500 TB data already.
- Has this dataset been stored on Filecoin before? If so, why are you choosing to store it again?
- Best practice for storing large datasets includes ideally, storing it in 3 or more regions, with 4 or more storage provider operators or owners.You should list Miner ID, Business Entity, Location of sps you will cooperate with.
- Per the https://github.com/filecoin-project/notary-governance/issues/922 for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

**Comment by herrehesse** [comment]
Why twice?

**Comment by Metainsightofficial** [comment]
> Why twice?

The [old one](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/2200) is closed halfway, so we reopened an issue.

**Comment by Metainsightofficial** [comment]
1.Some of our data has been gathered on a [cloud storage](https://drive.google.com/drive/folders/1Cn_KNZMznffXMxRQn3d_xifDuZnOjZt1?usp=sharing), which includes some recording videos held by us before, plus the twitter space recordings we uploaded on this form below.
2.Our data has not been stored on Filecoin before. We are planning to do some backup for our data, so we need DataCap to store more data on Filecoin.
3.The Fil+ registration form is complete, please check it out.

**Comment by herrehesse** [comment]
@Metainsightofficial closed for good reason right?

SPs provided. No contact info
f01853077 | Peter | - | Alpha100 | Singapore | - | -
f02329119 | Jennie | - | Cryptomage | Jiaxing | - | -
f02133079 | Stephine | - | FineTune | HongKong | - | -
f02274508 | Rick | - | H&W | HongKong | - | -
f02320312 | Greg | - | R1 | USA | -

SPs used:

f02211572 | Chengdu, Sichuan, CNChina Mobile Communications Group Co., Ltd. | 156.81 TiB | 13.98% | 156.81 TiB | 0.00%
f02368282 | Chengdu, Sichuan, CNCHINA UNICOM China169 Backbone | 303.72 TiB | 27.07% | 251.63 TiB | 17.15%
f02815620new | Hong Kong, Central and Western, HKChina Unicom Global | 227.94 TiB | 20.32% | 213.22 TiB | 6.46%
f02274508 | Hong Kong, Central and Western, HKChina Unicom Global | 222.16 TiB | 19.80% | 197.13 TiB | 11.27%
f01853077 | Singapore, Singapore, SGZenlayer Inc | 101.16 TiB | 9.02% | 101.16 TiB | 0.00%
f01852363 | Singapore, Singapore, SGZenlayer Inc | 79.50 TiB | 7.09% | 78.16 TiB | 1.69%
f02031006 | Los Angeles, California, USZenlayer Inc | 30.66 TiB | 2.73% | 30.63 TiB | 0.10%

does not match. closing until updated. Please provide contact info for all SPs. fill out registration form again if needed

**Comment by Metainsightofficial** [comment]
![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/139758630/46e5147d-4836-4508-ac26-8cfe2765b0d3)
As pic shows that previously kevzak said two are matched.

**Comment by Filplus-govteam** [comment]
email sent to confirm SPs

**Comment by Metainsightofficial** [comment]
@Filplus-govteam 
We have contacted the SPs we corporated and asked them to reply when receive the email, is everything going well?

**Comment by Filplus-govteam** [comment]
no emails received. If you want to be proactive, have them email filplus.govteam@gmail.com and send proof of entity and location of each listed.

**Comment by Sunnyiscoming** [comment]
SP List provided:
[{"providerID":"f01938357","City":"Sichuan","Country":"CN","SPOrg","CN China Mobile Communications Group Co."},
{"providerID":"f01919423","City":"Sichuan","Country":"CN","SPOrg","CN CHINA UNICOM China 169 Backbone"},
{"providerID":"f02033496","City":"CentralandWestern","Country":"CN","SPOrg","HK China Unicom Global"},
{"providerID":"f01771403","City":"CentralandWestern","Country":"CN","SPOrg","HK China Unicom Global"},
{"providerID":"f01926635","City":"Singapore","Country":"Singapore","SPOrg","SG Zenlayer Inc"},
{"providerID":"f01989888","City":"Singapore","Country":"Singapore","SPOrg","SG Zenlayer Inc"},
{"providerID":"f01933917","City":"California","Country":"US","SPOrg","US Zenlayer Inc"},]

**Comment by Metainsightofficial** [comment]
Please keep this issue open.

**Comment by Metainsightofficial** [comment]
@Sunnyiscoming  @Filplus-govteam  Hi Fil+team, in order to make further connection, we will keep on using this issue, please reopen this for us ,thanks!
