### ISSUE TITLE
[DataCap Application]  - <NOAA High-Resolution Rapid Refresh (HRRR) Model>

### ISSUE THREAD

**Issue by Swift-scouts** [filecoin-project/filecoin-plus-large-datasets#2278]
### Data Owner Name

NOAA

### What is your role related to the dataset

Data Preparer

### Data Owner Country/Region

Afghanistan

### Data Owner Industry

Life Science / Healthcare

### Website

https://github.com/awslabs/open-data-docs/tree/main/docs/noaa/noaa-hrrr

### Social Media

```text
https://github.com/awslabs/open-data-docs/tree/main/docs/noaa/noaa-hrrr
```

### Total amount of DataCap being requested

15PiB

### Expected size of single dataset (one copy)

1.5P

### Number of replicas to store

10

### Weekly allocation of DataCap requested

10TiB

### On-chain address for first allocation

f1itdw3qxfmtruyevfjl5epufwvlbvos6cqno6vgy

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
We are a data processor with hundreds of storage machines and a 5G bandwidth computer room in Hong Kong that can process large amounts of data.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
The HRRR is a NOAA real-time 3-km resolution, hourly updated, cloud-resolving, convection-allowing atmospheric model, initialized by 3km grids with 3km radar assimilation. Radar data is assimilated in the HRRR every 15 min over a 1-h period adding further detail to that provided by the hourly data assimilation from the 13km radar-enhanced Rapid Refresh.
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### If you are a data preparer. What is your location (Country/Region)

None

### Please share a sample of the data

```text
aws s3 ls --no-sign-request s3://noaa-hrrr-bdp-pds/
Total Objects: 81732586
   Total Size: 2.4 PiB
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

1.5 to 2 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, South America, Europe

### How will you be distributing your data to storage providers

Cloud storage (i.e. S3), HTTP or FTP server

### How do you plan to choose storage providers

Slack, Big Data Exchange

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1205#issuecomment-1382838178
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/2261#issuecomment-1796649216
@Swift-scouts Please explain about that.

**Comment by Swift-scouts** [comment]
#1205 
Since the storage provider contacted at the time could not provide retrieval services, we suspended cooperation with them, and we could not reach an agreement with the customer, so 1205 was stalled.
#2261  
Reply in original issue

**Comment by Swift-scouts** [comment]
@herrehesse   That's the right sentence for you  “stop with your scam please. We know you are a bad actor in this ecosystem. You can not prove anything with mere words and I have showed time and time again that you are abusing this ecosystem.”

**Comment by Swift-scouts** [comment]
keep this open

**Comment by Sunnyiscoming** [comment]
The questions have not been completed in the above. Please complete them.

**Comment by Swift-scouts** [comment]
> The questions have not been completed in the above. Please complete them.

23/5000

Can you open this issue and I can  update it these days?
