### ISSUE TITLE
[DataCap Application] <Crato Labs> - <Prediction Club>

### ISSUE THREAD

**Issue by SuperRita** [filecoin-project/filecoin-plus-large-datasets#2279]
### Data Owner Name

Prediction Club

### What is your role related to the dataset

Data Preparer

### Data Owner Country/Region

China

### Data Owner Industry

Web3 / Crypto

### Website

https://www.predictionclub.xyz/

### Social Media

```text
https://twitter.com/PCLUB_Community
```

### Total amount of DataCap being requested

1 Pib

### Expected size of single dataset (one copy)

20G

### Number of replicas to store

8

### Weekly allocation of DataCap requested

150TiB

### On-chain address for first allocation

f1qnrqwwfszpcwis3awc3uxfnqdvhixklc7zxrqsy

### Data Type of Application

Public, Open Commercial/Enterprise

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
PredictionClub Community is a prediction marketplace built on a 
decentralized blockchain technology, where users can trade contracts that 
yields profits based on the outcomes of unknown future events.                        
The market prices generated from these contracts can be understood as a kind 
of collective prediction among market participants.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
videos, pictures, documents and NFTs we recorded.
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### If you are a data preparer. What is your location (Country/Region)

China

### If you are a data preparer, how will the data be prepared? Please include tooling used and technical details?

```text
singularity
```

### Has this dataset been stored on the Filecoin network before? If so, please explain and make the case why you would like to store this dataset again to the network. Provide details on preparation and/or SP distribution.

```text
no
```

### Please share a sample of the data

```text
https://www.predictionclub.xyz/
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Daily

### For how long do you plan to keep this dataset stored on Filecoin

More than 3 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, Europe

### How will you be distributing your data to storage providers

IPFS

### How do you plan to choose storage providers

Slack, Big Data Exchange, Partners, I don't know yet

### How do you plan to make deals to your storage providers

Singularity

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by herrehesse** [comment]
@SuperRita welcome to FIL+. Can you help me with the following:

Who will be the miners that you will be storing your data on?
Will you be paying the miners a fee for their storage services?
What continents do you plan on storing on?
Who will prepare the data for you?

Thank you.

**Comment by SuperRita** [comment]
> @SuperRita welcome to FIL+. Can you help me with the following:
> 
> Who will be the miners that you will be storing your data on? Will you be paying the miners a fee for their storage services? What continents do you plan on storing on? Who will prepare the data for you?
> 
> Thank you.

Hey @herrehesse 

Thanks for your reply!

Please refer to my reply as below:

1. We are reaching out to some SPs and will share it here once we decide it for first step! Hope it will be soon.
2. not sure what fee you mean? I think not
3. plan to store on Asia other than China, North America, Europe, China. (sorry I missed one in the application)
4. we are the preparer as I stated in the application.

Let me know if you have any further query!

Thanks

**Comment by herrehesse** [comment]
Great, looking forward to your information about SP's.
Paying for storage is something every client should do, not giving SP's a reward is bad for the ecosystem. Just something to note, free deals are not healthy.

**Comment by SuperRita** [comment]
@herrehesse 
Thanks for your suggestion. 
I'll get things done asap.

**Comment by Sunnyiscoming** [comment]
- Best practice for storing large datasets includes ideally, storing it in 3 or more regions, with 4 or more storage provider operators or owners.You should list Miner ID, Business Entity, Location of sps you will cooperate with.
- Per the https://github.com/filecoin-project/notary-governance/issues/922 for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

**Comment by SuperRita** [comment]
> * Best practice for storing large datasets includes ideally, storing it in 3 or more regions, with 4 or more storage provider operators or owners.You should list Miner ID, Business Entity, Location of sps you will cooperate with.
> * Per the [Modification: Changes required to public open dataset application flow notary-governance#922](https://github.com/filecoin-project/notary-governance/issues/922) for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

hey there
it is submitted.
Thanks!
![1700059381587](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/133638497/8110959c-6157-4295-aef6-d1e2f3228f7c)

**Comment by SuperRita** [comment]
hello @Sunnyiscoming  any update?

**Comment by herrehesse** [comment]
Please add the contact information of the SP entities you are working with to store copies of the data.

**Comment by SuperRita** [comment]
> Please add the contact information of the SP entities you are working with to store copies of the data.

sure I filled it in the form.

**Comment by herrehesse** [comment]
Can you show the community in here?

**Comment by SuperRita** [comment]
> Can you show the community in here?

ohh！ I got it. Thanks for suggestion.

**Comment by SuperRita** [comment]
Dear community

I have a list of first 4 SPs as below, and I will try my best to look for more nice SPs to work with. 
Thank you for your support and questions.

![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/133638497/9d9d3b3f-036d-4ec2-851f-625904154d9c)

**Comment by herrehesse** [comment]
I have checked which LDNs your miners have sealed before and I am shocked.

Your miner lists consist of miner who have been caught on abusive LDN's many many times before. Their reputation is clearly awful and I do not support them getting datacap.

![Screenshot 2023-11-20 at 09 43 54](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/70132857/0abb6b27-8e61-45c7-bb76-fb7212d9a79b)
![Screenshot 2023-11-20 at 09 43 28](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/70132857/f6aab91b-9c83-4f9f-b914-f84a6edbc1fe)

**Comment by SuperRita** [comment]
> I have checked which LDNs your miners have sealed before and I am shocked.
> 
> Your miner lists consist of miner who have been caught on abusive LDN's many many times before. Their reputation is clearly awful and I do not support them getting datacap.
> 
> ![Screenshot 2023-11-20 at 09 43 54](https://user-images.githubusercontent.com/70132857/284204760-0abb6b27-8e61-45c7-bb76-fb7212d9a79b.png) ![Screenshot 2023-11-20 at 09 43 28](https://user-images.githubusercontent.com/70132857/284204765-f6aab91b-9c83-4f9f-b914-f84a6edbc1fe.png)

Hey @herrehesse 

Thanks for your information!

Can I know how to check this useful information? any tool in the community?

But as I know, those SPs are still contributing to Filecoin ecosystem, I cannot work them? or better not?

For us, we need SPs to store the data as I stated, though their reputation WAS not so good, is it banned?

This is just first round of my SPs, and I am actively looking for more to cooperate.

**Comment by herrehesse** [comment]
@SuperRita, great questions!

Firstly, I can help you find suitable Storage Providers (SPs) in the EU, USA, and AUS regions. For Asian regions, it would be best if you explore options yourself.

As someone new to this, it's understandable that you might not be fully aware of past issues with SPs' abusive behavior. In the future, you can quickly check their history by copying and pasting the minerID into the search bar at [GitHub Issues](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues). Reviewing their previous Large Datacap (LDN) applications can reveal any disputes or closure requests.

It's important to note that an SP's ongoing contribution to the ecosystem isn't necessarily indicative of their reputation. Many of the top 20 SPs globally have been implicated in datacap abuse and are still operational.

While nothing can be outright banned, choosing to store with low-reputation SPs could impact your standing in the community and affect potential datacap allocations.

If you provide details about the number of copies, preferred regions, and volume, I can compile a public list of reputable actors in this ecosystem and assist you further.

**Comment by SuperRita** [comment]
@herrehesse 
Hey Sir. Thanks for sharing and suggestion!
Sorry that I am not familar with the stories here.

From my understanding, there were some disputes on some SPs but they are not banned, right?

Totally understand your point, but deal is deal, can I move on with the 1st round and tried to reach out to more SPs with good reputation for further cooperation ( I'll learn your way to search and evaluate).

We are data preparer, our goal is to store the real and public data in filecoin network with effective SPs, but I will have your suggestion and look for more nice SPs in more ways.

Thanks

**Comment by SuperRita** [comment]
hey any update?
@Sunnyiscoming is it fine from your side for my 1st round application?

Thanks!

**Comment by herrehesse** [comment]
@SuperRita Ehm, no it is not fine from our side to give your 1st round application. Clearly stated above. Good luck finding other SP's with good reputation.

**Comment by SuperRita** [comment]
@herrehesse I am looking for more SPs as well. Could you please list some for me to check? Thanks!

**Comment by herrehesse** [comment]
Here are a few proper SP's with high reputation.

Provider | Location | Total Deals Sealed | Percentage | Unique Data | Duplicate Deals
-- | -- | -- | -- | -- | --
f02806702 | Sydney, New South Wales, AUAndrew Sjoquist Enterprises Pty Ltd | 2.81 TiB | 2.05% | 2.81 TiB | 0.00%
f02806693 | Sydney, New South Wales, AUAndrew Sjoquist Enterprises Pty Ltd | 2.72 TiB | 1.98% | 2.72 TiB | 0.00%
f02806700 | Sydney, New South Wales, AUAndrew Sjoquist Enterprises Pty Ltd | 2.28 TiB | 1.66% | 2.28 TiB | 0.00%
f01611097 | Irvine, California, USAT&T Services, Inc. | 4.03 TiB | 2.93% | 4.03 TiB | 0.00%
f097777 | Otyniia, Ivano-Frankivsk, UABranch Enterprise "Netgroup-Service" | 7.72 TiB | 5.62% | 7.72 TiB | 0.00%
f010479 | Paris, Île-de-France, FRCELESTE SAS | 4.16 TiB | 3.03% | 4.16 TiB | 0.00%
f01345523 | Antwerpen, Flanders, BECogent Communications | 11.69 TiB | 8.51% | 11.69 TiB | 0.00%
f01864397 | Zaventem, Flanders, BECogent Communications | 4.28 TiB | 3.12% | 4.28 TiB | 0.00%
f01907556 | Sharjah, Sharjah, AEEMIRATES TELECOMMUNICATIONS GROUP COMPANY (ETISALAT GROUP) PJSC | 7.53 TiB | 5.48% | 7.53 TiB | 0.00%
f020378 | Asenovgrad, Plovdiv, BGESCOM Ltd. - Haskovo | 7.69 TiB | 5.60% | 7.69 TiB | 0.00%
f01392893 | Utrecht, Utrecht, NLFusix Networks B.V. | 20.25 TiB | 14.74% | 20.25 TiB | 0.00%
f02055660 | Sydney, New South Wales, AUHurricane Electric LLC | 9.00 TiB | 6.55% | 9.00 TiB | 0.00%
f0773157 | Sydney, New South Wales, AUHurricane Electric LLC | 736.00 GiB | 0.52% | 736.00 GiB | 0.00%
f01227505 | Incheon, Incheon, KRKorea Telecom | 32.00 GiB | 0.02% | 32.00 GiB | 0.00%
f0717969 | Los Angeles, California, USKrypt Technologies | 7.84 TiB | 5.71% | 7.84 TiB | 0.00%
f01163272 | Perm, Perm Krai, RUPJSC Rostelecom | 3.03 TiB | 2.21% | 3.03 TiB | 0.00%
f0706693 | Brest, Brest, BYRepublican Unitary Telecommunication Enterprise Beltelecom | 5.94 TiB | 4.32% | 5.94 TiB | 0.00%
f02832654 | Chicago, Illinois, USServer Central Network | 992.00 GiB | 0.71% | 992.00 GiB | 0.00%
f01943041 | Marlow, England, GBSwish Fibre Ltd | 1.19 TiB | 0.86% | 1.19 TiB | 0.00%
f01786387 | Heerhugowaard, North Holland, NLWijnand Schouten | 9.91 TiB | 7.21% | 9.91 TiB | 0.00%
f01771403 | Heerhugowaard, North Holland, NLWijnand Schouten | 9.41 TiB | 6.85% | 9.41 TiB | 0.00%
f02366527 | Heerhugowaard, North Holland, NLWijnand Schouten | 7.81 TiB | 5.69% | 7.81 TiB | 0.00%
f01720359 | Heerhugowaard, North Holland, NLWijnand Schouten | 6.38 TiB | 4.64% | 6.38 TiB | 0.00%

Provider	Location	Total Deals Sealed	Percentage	Unique Data	Duplicate Deals
[f02806702](https://filfox.info/en/address/f02806702)	Sydney, New South Wales, AU
Andrew Sjoquist Enterprises Pty Ltd	2.81 TiB	2.05%	2.81 TiB	0.00%
[f02806693](https://filfox.info/en/address/f02806693)	Sydney, New South Wales, AU
Andrew Sjoquist Enterprises Pty Ltd	2.72 TiB	1.98%	2.72 TiB	0.00%
[f02806700](https://filfox.info/en/address/f02806700)	Sydney, New South Wales, AU
Andrew Sjoquist Enterprises Pty Ltd	2.28 TiB	1.66%	2.28 TiB	0.00%
[f01611097](https://filfox.info/en/address/f01611097)	Irvine, California, US
AT&T Services, Inc.	4.03 TiB	2.93%	4.03 TiB	0.00%
[f097777](https://filfox.info/en/address/f097777)	Otyniia, Ivano-Frankivsk, UA
Branch Enterprise "Netgroup-Service"	7.72 TiB	5.62%	7.72 TiB	0.00%
[f010479](https://filfox.info/en/address/f010479)	Paris, Île-de-France, FR
CELESTE SAS	4.16 TiB	3.03%	4.16 TiB	0.00%
[f01345523](https://filfox.info/en/address/f01345523)	Antwerpen, Flanders, BE
Cogent Communications	11.69 TiB	8.51%	11.69 TiB	0.00%
[f01864397](https://filfox.info/en/address/f01864397)	Zaventem, Flanders, BE
Cogent Communications	4.28 TiB	3.12%	4.28 TiB	0.00%
[f01907556](https://filfox.info/en/address/f01907556)	Sharjah, Sharjah, AE
EMIRATES TELECOMMUNICATIONS GROUP COMPANY (ETISALAT GROUP) PJSC	7.53 TiB	5.48%	7.53 TiB	0.00%
[f020378](https://filfox.info/en/address/f020378)	Asenovgrad, Plovdiv, BG
ESCOM Ltd. - Haskovo	7.69 TiB	5.60%	7.69 TiB	0.00%
[f01392893](https://filfox.info/en/address/f01392893)	Utrecht, Utrecht, NL
Fusix Networks B.V.	20.25 TiB	14.74%	20.25 TiB	0.00%
[f02055660](https://filfox.info/en/address/f02055660)	Sydney, New South Wales, AU
Hurricane Electric LLC	9.00 TiB	6.55%	9.00 TiB	0.00%
[f0773157](https://filfox.info/en/address/f0773157)	Sydney, New South Wales, AU
Hurricane Electric LLC	736.00 GiB	0.52%	736.00 GiB	0.00%
[f01227505](https://filfox.info/en/address/f01227505)	Incheon, Incheon, KR
Korea Telecom	32.00 GiB	0.02%	32.00 GiB	0.00%
[f0717969](https://filfox.info/en/address/f0717969)	Los Angeles, California, US
Krypt Technologies	7.84 TiB	5.71%	7.84 TiB	0.00%
[f01163272](https://filfox.info/en/address/f01163272)	Perm, Perm Krai, RU
PJSC Rostelecom	3.03 TiB	2.21%	3.03 TiB	0.00%
[f0706693](https://filfox.info/en/address/f0706693)	Brest, Brest, BY
Republican Unitary Telecommunication Enterprise Beltelecom	5.94 TiB	4.32%	5.94 TiB	0.00%
[f02832654](https://filfox.info/en/address/f02832654)	Chicago, Illinois, US
Server Central Network	992.00 GiB	0.71%	992.00 GiB	0.00%
[f01943041](https://filfox.info/en/address/f01943041)	Marlow, England, GB
Swish Fibre Ltd	1.19 TiB	0.86%	1.19 TiB	0.00%
[f01786387](https://filfox.info/en/address/f01786387)	Heerhugowaard, North Holland, NL
Wijnand Schouten	9.91 TiB	7.21%	9.91 TiB	0.00%
[f01771403](https://filfox.info/en/address/f01771403)	Heerhugowaard, North Holland, NL
Wijnand Schouten	9.41 TiB	6.85%	9.41 TiB	0.00%
[f02366527](https://filfox.info/en/address/f02366527)	Heerhugowaard, North Holland, NL
Wijnand Schouten	7.81 TiB	5.69%	7.81 TiB	0.00%
[f01720359](https://filfox.info/en/address/f01720359)	Heerhugowaard, North Holland, NL
Wijnand Schouten	6.38 TiB	4.64%	6.38 TiB	0.00%

**Comment by SuperRita** [comment]
> Here are a few proper SP's with high reputation.
> 
> Provider	Location
> f02806702	Sydney, New South Wales, AUAndrew Sjoquist Enterprises Pty Ltd
> f02806693	Sydney, New South Wales, AUAndrew Sjoquist Enterprises Pty Ltd
> f02806700	Sydney, New South Wales, AUAndrew Sjoquist Enterprises Pty Ltd
> f01611097	Irvine, California, USAT&T Services, Inc.
> f097777	Otyniia, Ivano-Frankivsk, UABranch Enterprise "Netgroup-Service"
> f010479	Paris, Île-de-France, FRCELESTE SAS
> f01345523	Antwerpen, Flanders, BECogent Communications
> f01864397	Zaventem, Flanders, BECogent Communications
> f01907556	Sharjah, Sharjah, AEEMIRATES TELECOMMUNICATIONS GROUP COMPANY (ETISALAT GROUP) PJSC
> f020378	Asenovgrad, Plovdiv, BGESCOM Ltd. - Haskovo
> f01392893	Utrecht, Utrecht, NLFusix Networks B.V.
> f02055660	Sydney, New South Wales, AUHurricane Electric LLC
> f0773157	Sydney, New South Wales, AUHurricane Electric LLC
> f01227505	Incheon, Incheon, KRKorea Telecom
> f0717969	Los Angeles, California, USKrypt Technologies
> f01163272	Perm, Perm Krai, RUPJSC Rostelecom
> f0706693	Brest, Brest, BYRepublican Unitary Telecommunication Enterprise Beltelecom
> f02832654	Chicago, Illinois, USServer Central Network
> f01943041	Marlow, England, GBSwish Fibre Ltd
> f01786387	Heerhugowaard, North Holland, NLWijnand Schouten
> f01771403	Heerhugowaard, North Holland, NLWijnand Schouten
> f02366527	Heerhugowaard, North Holland, NLWijnand Schouten
> f01720359	Heerhugowaard, North Holland, NLWijnand Schouten

Thanks!
But there is no contact, how to reach out to them?

**Comment by herrehesse** [comment]
You can come to Slack and try to contact most, are you willing to pay for the storage? Most high quality SP's require a fee.
PM me on slack.

**Comment by Joss-Hua** [comment]
![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/75723122/fd97dde2-969a-4195-8cc4-d6db86dda2e4)
There is some kind of error here @SuperRita

**Comment by SuperRita** [comment]
> ![image](https://user-images.githubusercontent.com/75723122/284780076-fd97dde2-969a-4195-8cc4-d6db86dda2e4.png) There is some kind of error here @SuperRita

Thanks for the reminder!

**Comment by Sunnyiscoming** [comment]
SP List provided:
[{"providerID": "f02327534",  "City": "XYZ", "Country": "US", "SPOrg","ipollo"},
{"providerID": "f02006374",  "City": "HK", "Country": "CN","SPOrg","KK"},
{"providerID": "f01831983",  "City": XYZ", "Country": "CN","SPOrg","Coplus"},
{"providerID": "f01971431",  "City": XYZ", "Country": "CN","SPOrg","Coplus"},]

**Comment by SuperRita** [comment]
> SP List provided: [{"providerID": "f02327534", "City": "XYZ", "Country": "US", "SPOrg","ipollo"}, {"providerID": "f02006374", "City": "HK", "Country": "CN","SPOrg","KK"}, {"providerID": "f01831983", "City": XYZ", "Country": "CN","SPOrg","Coplus"}, {"providerID": "f01971431", "City": XYZ", "Country": "CN","SPOrg","Coplus"},]

Thanks

**Comment by SuperRita** [comment]
please keep it open. thanks

**Comment by SuperRita** [comment]
please keep it open

**Comment by SuperRita** [comment]
keep it open
