### ISSUE TITLE
[DataCap Application] DailyGym

### ISSUE THREAD

**Issue by MetaGirls** [filecoin-project/filecoin-plus-large-datasets#228]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Daily Gym
- Website / Social Media: http://dailygym.net
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5 PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100TiB
- On-chain address for first allocation: f3tevu2xmxtjctqumk4s7sba7vvi3a32sxdfubtg3rqpbjwah3q3aq444aj3sh2sywqeq6avugftltebww7tna

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
We train people to lose weight and get in shape by providing on/offline hardcore training/ diet programs. 
```

What is the primary source of funding for this project?
```
Ourselves along with our clients
```

What other projects/ecosystem stakeholders is this project associated with?
```
Strategic Multilateral Partnerships through Fitness Alliance
```

## Use-case details

Describe the data being stored onto Filecoin
```
Video Tutorials, lessons, systematic curriculum on self-discipline and ultimate cross-fit
```

Where was the data in this dataset sourced from?
```
Asia
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
http://dailygym.net
https://blog.naver.com/dailygym
https://www.instagram.com/dailygym_official/
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
We do confirm that this is a public dataset that can be retrieved by anyone on the Network.
```

What is the expected retrieval frequency for this data?
```
Not very often. Prbly less than 3 times a year.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
Hopefully permanently until we're granted.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Anywhere in Asia
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Both on/offline
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We'll partner with legit miners.
```

How will you be distributing deals across storage providers?
```
Both on/offline
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
We're familiar with the deal making process already. It will start once we're all set to go!

```

**Comment by swatchliu** [comment]
“Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this.”  Please answer again.

**Comment by MetaGirls** [comment]
https://www.youtube.com/watch?v=V9pVR8GWMXk
Thanks!

**Comment by MetaGirls** [comment]
Was our data reviewed? Please let me know. Thank you!

**Comment by IPFSUnion** [comment]
Where are your data stored before？5p is not a small capacity.

**Comment by MetaGirls** [comment]
> Where are your data stored before？5p is not a small capacity.

Our data has been stored in many other cloud storage services, so we'd decided to ask for the maximum amount allowed since we have a number of branches of our own. If 5 PiB is too much, then, we'd appreciate smaller amount of capacity. Thank you!

**Comment by MetaGirls** [comment]
> Where are your data stored before？5p is not a small capacity.

Could we still be allocated with smaller amount of DataCap?

**Comment by dkkapur** [comment]
@MetaGirls are you able to send an email from your @dailygym email account to filplus@fil.org or to some of the notaries to validate that you are indeed a representative of this organization? I see no other GitHub activity for your account, so it is hard to know if you are from this organization or not. 

Additionally - what is an acceptable amount of DataCap you would like to eventually get to in total? I see you are OK with less than 5 PiB, but what is the ideal total amount?

**Comment by galen-mcandrew** [comment]
Any update on the questions above?

**Comment by galen-mcandrew** [comment]
Closing this for now from no reply. When ready, please reopen or submit a new request here: https://plus.fil.org/ldn-application
