### ISSUE TITLE
[DataCap Application] <CAO> - <Sentinel-1 SLC-03>

### ISSUE THREAD

**Issue by caoxinhe0108** [filecoin-project/filecoin-plus-large-datasets#2280]
### Data Owner Name

LiveEO

### What is your role related to the dataset

Dataset Owner

### Data Owner Country/Region

Afghanistan

### Data Owner Industry

Life Science / Healthcare

### Website

https://www.live-eo.com/

### Social Media

```text
Twitter---https://twitter.com/liveeo_space
Linkedin---https://www.linkedin.com/company/liveeo/
```

### Total amount of DataCap being requested

10PiB

### Expected size of single dataset (one copy)

32G

### Number of replicas to store

6

### Weekly allocation of DataCap requested

1PiB

### On-chain address for first allocation

f1m6zc5oe5hvfttvjesxpboenbxvqstk4onhq4zqy

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
LiveEO was born from the idea that satellite data, a vast and almost untapped resource, has enormous potential to transform our lives, and the world around us, for the better. Sven and Daniel, two NewSpace enthusiasts with a keen interest in A.I., founded LiveEO in 2018 with a simple vision: to apply this incredible trove of data about our planet to improve the way we do business, and live our lives.
```

### Is this project associated with other projects/ecosystem stakeholders?

Yes

### Describe the data being stored onto Filecoin

```text
LiveEO was born from the idea that satellite data, a vast and almost untapped resource, has enormous potential to transform our lives, and the world around us, for the better. Sven and Daniel, two NewSpace enthusiasts with a keen interest in A.I., founded LiveEO in 2018 with a simple vision: to apply this incredible trove of data about our planet to improve the way we do business, and live our lives.
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### If you are a data preparer. What is your location (Country/Region)

None

### Please share a sample of the data

```text
aws s3 ls --no-sign-request s3://sentinel1-slc/	Total Objects: 5961934	
1.1 PiB
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [ ] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

1.5 to 2 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, South America

### How will you be distributing your data to storage providers

Cloud storage (i.e. S3), HTTP or FTP server

### How do you plan to choose storage providers

Slack, Big Data Exchange

### If you already have a list of storage providers to work with, fill out their names and provider IDs below

```text
SP-Miner-IDs Contact-name SP-Business-Email SP-Organization-Name Region
f02813403 YuanBao yuanbao@rimington.com rimington Britain
f02811783 yuanbao yuanbao@rimington.com rimington Britain
f02814393 pythia connect@pythia.com pythia California,USA
f02812781 TVfinance Alma@TVfinance.com TVfinance Vietnam
f02828509 jkkts12 John@hs88.com hs88 Korea
```

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by herrehesse** [comment]
Entity is trying to re-open closed LDN by moderators: https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/2267#issuecomment-1808112722

All of these miners are under VPN most likely the same entity doing self-dealing. Client has provided zero counter evidence about the wherabouts of their chosen SP's. 

![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/70132857/9573b8b8-f498-4d40-9ca1-f4c82f1bf83c)

**Comment by Filplus-govteam** [comment]
This application is under SP entity and location review. Closing until clear information is provided. SP contacts submitted are not matching. 

Same issue as #2197
