### ISSUE TITLE
DataCap Application by CPSA

### ISSUE THREAD

**Issue by godsufficient** [filecoin-project/filecoin-plus-large-datasets#229]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: CPSA
- Website / Social Media: http://www.cpsa.co.kr/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5 PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100 TiB
- On-chain address for first allocation: f3q4bi7yx56pgm4u3shrhhsoaq2xdv7sw32fek2wb7jzyygl4rsk4wxp6gb2uirlbs26ph3g7fagx6go73jptq

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
CPSA has been equipping high school students to transition to college-level academic proficiency. The demand of our renowned on/offline lectures are spreading viral due to its excellence and proven results.
```

What is the primary source of funding for this project?
```
CPSA and individuals involved in this project
```

What other projects/ecosystem stakeholders is this project associated with?
```
Peer companies
```

## Use-case details

Describe the data being stored onto Filecoin
```
SAT Prep learning materials including video and Mp4 files for each level.
```

Where was the data in this dataset sourced from?
```
Asia
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
http://www.cpsa.co.kr
https://cafe.naver.com/cpsa8079
https://cafe.daum.net/cpsa
https://www.youtube.com/watch?v=N7Ga8SvFiRo
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
No specific permissions or access rights are required to view the data.
```

What is the expected retrieval frequency for this data?
```
Every once in a while.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
Maximum period of time
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Asia
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
We do have an offline data transfer process but online process is always preferred.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We'll search for miners who are capable of supporting stable storage.
```

How will you be distributing deals across storage providers?
```
Based on both parties' integrity and excellence.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
We're financially backed-up by all our stakeholders.
```

**Comment by godsufficient** [comment]
Please let me know how this is being processed, that'd be great! Thanks!

**Comment by godsufficient** [comment]
Hi, any update yet?

**Comment by dkkapur** [comment]
@godsufficient - can you help us understand why you need 5 PiB for the data you are storing? Is this because of the mp4 files? How many replicas are you aiming to onboard? 

Separately, your GitHub account seems to be new / has no other history related to your organization. Can you email filplus@fil.org with your work email so we can share this with notaries as a form of proof that you represent this organization?

**Comment by galen-mcandrew** [comment]
Any update on the above request?

**Comment by galen-mcandrew** [comment]
Closing this for now from no reply. When ready, please reopen or submit a new request here: https://plus.fil.org/ldn-application
