### ISSUE TITLE
[DataCap Application] JMA Himawari-8/9 Open Data

### ISSUE THREAD

**Issue by FroghubMan** [filecoin-project/filecoin-plus-large-datasets#2292]
### Data Owner Name

NOAA

### What is your role related to the dataset

Data Preparer

### Data Owner Country/Region

Japan

### Data Owner Industry

Environment

### Website

https://www.noaa.gov/

### Social Media

```text
https://www.facebook.com/NOAA
https://www.youtube.com/usnoaagov
```

### Total amount of DataCap being requested

15PiB

### Expected size of single dataset (one copy)

1.5P

### Number of replicas to store

10

### Weekly allocation of DataCap requested

1PiB

### On-chain address for first allocation

f1itqagmoxyc35kozkvle6mtsaqchxgpjojkn6szi

### Data Type of Application

Slingshot

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
FrogHub has always defined itself as a tool developer and infrastructure builder in the Filecoin ecosystem. In 2019, we started to focus on technical solutions and development based on the IPFS protocol and Filecoin network. We have been working hard to become a qualified builder in the filecoin ecosystem.

Our team is a very pure development team, more than 90% of which are developers, more than half of whom have more than 5 years of development experience in communication, Internet, blockchain and other industries. We hope that we can gain users' recognition by exporting useful tools and platforms.

In order to contribute to the filecoin community, we have developed the open source sector repair tool Filecoin-Sealer-Recover and the nft free authoring platform NFT-Creator.
In addition, we plan to provide a sector browser for the community in 2023 and build the liquidity pledge platform STFIL on FVM.

See the links below for details.
- github: https://github.com/orgs/froghub-io
- twitter: https://twitter.com/froghub_io
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
Himawari-8, stationed at 140E, owned and operated by the Japan Meteorological Agency (JMA), is a geostationary meteorological satellite, with Himawari-9 as on-orbit back-up, that provides constant and uniform coverage of east Asia, and the west and central Pacific regions from around 35,800 km above the equator with an orbit corresponding to the period of the earth’s rotation.
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### If you are a data preparer. What is your location (Country/Region)

Hong Kong

### If you are a data preparer, how will the data be prepared? Please include tooling used and technical details?

```text
After we download data from the Internet, the data is cut into disks through Singularity, and then the hard disk is mailed to the SP.
```

### Please share a sample of the data

```text
https://registry.opendata.aws/noaa-himawari/
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [ ] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

1.5 to 2 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, Africa, North America, Europe

### How will you be distributing your data to storage providers

Cloud storage (i.e. S3), HTTP or FTP server, Shipping hard drives

### How do you plan to choose storage providers

Slack, Big Data Exchange, Partners

### If you already have a list of storage providers to work with, fill out their names and provider IDs below

```text
| MinerID | Entity | City | Continent |
| --------- | ---------- | ---------- | --------- |
| f0870354 | Personal  | beijing | CN |
| f01989372   | Personal| beijing | CN |
| f02816837   | B.B  Tech| guangdong | CN |
| f01907578  | ssdminer| Putian | CN |
| f0123931   | ssdminer| Fuzhou | CN |
| f02806894   | Chimsen | Seoul | Korea |
| f02372022   | Chimsen | Tokyo | Japan |
| f02810687  | DR66 Tech| HongKong | CN |
| f02636860   | DR66 Tech| HongKong | CN |
| f01854510  | 3cloud tech| HongKong | CN |
| f02803754  | Personal | Osaka | Japan |
```

### How do you plan to make deals to your storage providers

Boost client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by FroghubMan** [comment]
Since #2243 encountered a bug, I re-initiated this application. Once this application is approved I will close #2243

**Comment by Sunnyiscoming** [comment]
@FroghubMan Hi, Can you ask notaries for help and try to sign your application https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/2243?
As @clriesco said, it is ready to sign. If there is any problem, please let us know.

**Comment by FroghubMan** [comment]
![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/88960777/b3ccfc0f-b782-489b-8a4f-1e673307a3d9)

Still unable to sign, can you help me with that?
@clriesco @Sunnyiscoming
