### ISSUE TITLE
[DataCap Application] EMPIAR

### ISSUE THREAD

**Issue by liou38469** [filecoin-project/filecoin-plus-large-datasets#2293]
### Data Owner Name

EMPIAR

### What is your role related to the dataset

Data Preparer

### Data Owner Country/Region

United Kingdom

### Data Owner Industry

Life Science / Healthcare

### Website

https://www.ebi.ac.uk/empiar/

### Social Media

```text
https://www.ebi.ac.uk/empiar/
```

### Total amount of DataCap being requested

14PiB

### Expected size of single dataset (one copy)

2P

### Number of replicas to store

7

### Weekly allocation of DataCap requested

1PiB

### On-chain address for first allocation

f1dcjn2qk4jsnjfdaavsdle5ydkufuxws767zarfi

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
EMPIAR, the Electron Microscopy Public Image Archive, is a public resource for raw images underpinning 3D cryo-EM maps and tomograms (themselves archived in EMDB). EMPIAR also accommodates 3D datasets obtained with volume EM techniques and soft and hard X-ray tomography. More ...
As of 2023-08-15, EMPIAR contains 1391 entries, taking up 3.15 PB of storage.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
Founded in 1956, NRAO provides the most advanced radio telescope facilities and information to the international scientific community.
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### If you are a data preparer. What is your location (Country/Region)

Singapore

### If you are not preparing the data, who will prepare the data?  (Provide name and business)

```text
_ This dataset is prepared using Singularity V2_
```

### Has this dataset been stored on the Filecoin network before? If so, please explain and make the case why you would like to store this dataset again to the network. Provide details on preparation and/or SP distribution.

```text
_ This should be the first time we store a dataset on the Filecoin network_
```

### Please share a sample of the data

```text
https://www.ebi.ac.uk/empiar/
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

2 to 3 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, Europe

### How will you be distributing your data to storage providers

Cloud storage (i.e. S3), HTTP or FTP server, Shipping hard drives, Lotus built-in data transfer

### How do you plan to choose storage providers

Slack, Filmine

### How do you plan to make deals to your storage providers

Boost client, Lotus client, Bidbot, Singularity

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by liou38469** [comment]
We have been applying for 2284 for a long time. We basically submitted all the information, but there was an error in the bot and no assignees were assigned. Therefore, I close 2284 and apply again. As an experienced data preparer and Filecoin enthusiast, I hope the FIL+ team can help us move forward, thank you.

**Comment by Sunnyiscoming** [comment]
Hi, @liou38469 I am confirming whether the last application is in investigation. Please wait for a moment.

**Comment by liou38469** [comment]
We have experience in 2152, thank you

**Comment by herrehesse** [comment]
First time, with experience? Hmmm..
Where is your SP list so we can run a background check. 
<img width="1126" alt="Screenshot 2023-12-14 at 09 04 10" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/70132857/e8b1481d-6672-459f-abf2-5f7c39b40101">

Your previous application has a lot of VPN & potentially self-dealing. Would love to get all details first.

**Comment by mikezli** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb3xkrrtzqmmvgda6elexdluhyeiitbik643tvq2yjojuoitdvgiy 
#### Address 
> f1dcjn2qk4jsnjfdaavsdle5ydkufuxws767zarfi
#### Datacap Allocated
> 2.00PiB
#### Signer Address
> f1dnb3uz7sylxk6emti3ififcvu3nlufnnsjui6ea
#### Id
> 8214fefa-1573-47e5-8143-bb65ebbe2bc1
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb3xkrrtzqmmvgda6elexdluhyeiitbik643tvq2yjojuoitdvgiy

**Comment by SuperChaiChai** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceddt6uijlplof4e53c4ww464tnaapbuqdrpuomzixtr6dp4axds3m 
#### Address 
> f1dcjn2qk4jsnjfdaavsdle5ydkufuxws767zarfi
#### Datacap Allocated
> 2.00PiB
#### Signer Address
> f12mckci3omexgzoeosjvstcfxfe4vqw7owdia3da
#### Id
> 8214fefa-1573-47e5-8143-bb65ebbe2bc1
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceddt6uijlplof4e53c4ww464tnaapbuqdrpuomzixtr6dp4axds3m

**Comment by Tom-OriginStorage** [comment]
checker:manualTrigger

**Comment by Tom-OriginStorage** [comment]
The robot seems to have a problem. According to the last report, it is basically normal and willing to support it

**Comment by Tom-OriginStorage** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacealzf2glzxd3wgfqyjfaxne2vu4xhi45emvj5caab2bmoavyddor6 
#### Address 
> f1dcjn2qk4jsnjfdaavsdle5ydkufuxws767zarfi
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f1q6bpjlqia6iemqbrdaxr2uehrhpvoju3qh4lpga
#### Id
> 0c38cec5-467f-450a-9037-19c11fa609d1
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacealzf2glzxd3wgfqyjfaxne2vu4xhi45emvj5caab2bmoavyddor6

**Comment by a1991car** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacea2hm3wqffr2yisnwjfme7ayjloansaua3h5c5vurpi7w6lotq3ia 
#### Address 
> f1dcjn2qk4jsnjfdaavsdle5ydkufuxws767zarfi
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f1qnumecdypgrbaebtkdfjnwt5ndacadcuas3deiq
#### Id
> 0c38cec5-467f-450a-9037-19c11fa609d1
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacea2hm3wqffr2yisnwjfme7ayjloansaua3h5c5vurpi7w6lotq3ia
