### ISSUE TITLE
[DataCap Application] Alchemist Data Center

### ISSUE THREAD

**Issue by kee4834** [filecoin-project/filecoin-plus-large-datasets#2296]
### Data Owner Name
Alchemist Data Center

### What is your role related to the dataset
Dataset Owner

### Data Owner Country/Region
Malaysia

### Data Owner Industry
IT & Technology Services

### Website
[https://alchemistfix.com](https://alchemistfix.com)

### Social Media
[at]KeeYS19 (Twitter)

### Total amount of DataCap being requested
343.75 TiB

### Expected size of single dataset (one copy)
343 TiB

### Number of replicas to store
1

### Weekly allocation of DataCap requested
100 TiB

### On-chain address for first allocation
f3vuj5pxwfdmqoybfsrrkhhr3mh7ajasuike7gyimc74cbiv6c6stj7ua4ldiagskca6ukql647ki3seltd2rq

### Data Type of Application
Slingshot

### Custom multisig
- [ ] Use Custom Multisig

### Identifier
n/a

### Share a brief history of your project and organization
We're miner company which is supply,hosting & repairing at malaysia

### Is this project associated with other projects/ecosystem stakeholders?
No

### If answered yes, what are the other projects/ecosystem stakeholders
n/a

### Describe the data being stored onto Filecoin
outsider data

### Where was the data currently stored in this dataset sourced from
My own storage infra

### If you answered "Other" in the previous question, enter the details here
n/a

### If you are a data preparer, what is your location (City and Country)
n/a

### If you are a data preparer, how will the data be prepared? Please include tooling used and technical details?
n/a

### If you are not preparing the data, who will prepare the data?  (Provide name and business)
We will prepare our own

### Has this dataset been stored on the Filecoin network before? If so, please explain and make the case why you would like to store this dataset again to the network. Provide details on preparation and/or SP distribution.
n/a

### Please share a sample of the data
Currently nope

### Confirm that this is a public dataset that can be retrieved by anyone on the Network
Yes

### If you chose not to confirm, what was the reason
n/a

### What is the expected retrieval frequency for this data
Weekly

### For how long do you plan to keep this dataset stored on Filecoin
Less than 1 year

### In which geographies do you plan on making storage deals
Asia other than Greater China

### How will you be distributing your data to storage providers
IPFS

### How do you plan to choose SP
I don't know yet

### If you answered "Others" in the previous question, what is the tool or platform you plan to use
n/a

### If you already have a list of storage providers to work with, fill out their names and provider IDs below
n/a

### How do you plan to make deals to your storage providers
Lotus client

### If you answered "Others/custom tool" in the previous question, enter the details here
n/a

### Can you confirm that you will follow the Fil+ guideline
Yes

_Application created via [filplus.storage](https://filplus.storage)_

**Comment by herrehesse** [comment]
@kee4834 Hi there, interested on what you are planning to store! Can we assist you?

**Comment by Sunnyiscoming** [comment]
If you are a data preparer, what is your location (City and Country)
n/a

If you are a data preparer, how will the data be prepared? Please include tooling used and technical details?
n/a

If you are not preparing the data, who will prepare the data? (Provide name and business)
We will prepare our own

Has this dataset been stored on the Filecoin network before? If so, please explain and make the case why you would like to store this dataset again to the network. Provide details on preparation and/or SP distribution.
n/a

Please share a sample of the data
Currently nope

How do you plan to choose SP
I don't know yet

If you answered "Others" in the previous question, what is the tool or platform you plan to use
n/a

If you already have a list of storage providers to work with, fill out their names and provider IDs below
n/a


Please answer the above questions in details.
