### ISSUE TITLE
[DataCap Application] Socioeconomic Analysis and Visualization Platform

### ISSUE THREAD

**Issue by jackyqj** [filecoin-project/filecoin-plus-large-datasets#2298]
### Data Owner Name
Socioeconomic Analysis and Visualization Platform

### What is your role related to the dataset
Dataset Owner

### Data Owner Country/Region
Hong Kong

### Data Owner Industry
Not-for-Profit

### Website
[https://github.com/savp-cloud/site](https://github.com/savp-cloud/site)

### Social Media
[at]savp_cloud (Twitter)

### Total amount of DataCap being requested
2 PiB

### Expected size of single dataset (one copy)
1 PiB

### Number of replicas to store
1

### Weekly allocation of DataCap requested
1 TiB

### On-chain address for first allocation
f3vpwtgnifj4zr7sxrdgogw76gqrjyuzcqncaoedh4fepv4npr27euvappgatohttm2zzsuv3fovxleucig74q

### Data Type of Application
Public, Open Dataset (Research/Non-Profit)

### Custom multisig
- [ ] Use Custom Multisig

### Identifier
n/a

### Share a brief history of your project and organization
We're dedicated to transforming data into actionable insights for a smarter, more sustainable future. Our flagship product is the Socioeconomic Analysis and Visualization Platform, a powerful tool that empowers governments, businesses, and researchers with comprehensive socioeconomic analysis capabilities.

### Is this project associated with other projects/ecosystem stakeholders?
No

### If answered yes, what are the other projects/ecosystem stakeholders
n/a

### Describe the data being stored onto Filecoin
Public data including economic, population, education, and environmental information.

### Where was the data currently stored in this dataset sourced from
My own storage infra

### If you answered "Other" in the previous question, enter the details here
n/a

### If you are a data preparer, what is your location (City and Country)
n/a

### If you are a data preparer, how will the data be prepared? Please include tooling used and technical details?
n/a

### If you are not preparing the data, who will prepare the data?  (Provide name and business)
My own data collector.

### Has this dataset been stored on the Filecoin network before? If so, please explain and make the case why you would like to store this dataset again to the network. Provide details on preparation and/or SP distribution.
n/a

### Please share a sample of the data
https://en.wikipedia.org/wiki/Hong_Kong

### Confirm that this is a public dataset that can be retrieved by anyone on the Network
Yes

### If you chose not to confirm, what was the reason
n/a

### What is the expected retrieval frequency for this data
Sporadic

### For how long do you plan to keep this dataset stored on Filecoin
Permanently

### In which geographies do you plan on making storage deals
Asia other than Greater China, Greater China, Africa, North America, South America, Europe, Australia (continent), Antarctica

### How will you be distributing your data to storage providers
Shipping hard drives

### How do you plan to choose SP
Slack

### If you answered "Others" in the previous question, what is the tool or platform you plan to use
n/a

### If you already have a list of storage providers to work with, fill out their names and provider IDs below
n/a

### How do you plan to make deals to your storage providers
Boost client

### If you answered "Others/custom tool" in the previous question, enter the details here
n/a

### Can you confirm that you will follow the Fil+ guideline
Yes

_Application created via [filplus.storage](https://filplus.storage)_

**Comment by Sunnyiscoming** [comment]
If you are not preparing the data, who will prepare the data? (Provide name and business)
My own data collector.

Has this dataset been stored on the Filecoin network before? If so, please explain and make the case why you would like to store this dataset again to the network. Provide details on preparation and/or SP distribution.
n/a

If you already have a list of storage providers to work with, fill out their names and provider IDs below
n/a

Please supplement the above information.

**Comment by jackyqj** [comment]
> If you are not preparing the data, who will prepare the data? (Provide name and business) My own data collector.

Yes, we prepare the data ourselves and the data will be formatted in our own format. 
> 
> Has this dataset been stored on the Filecoin network before? If so, please explain and make the case why you would like to store this dataset again to the network. Provide details on preparation and/or SP distribution. n/a

No the data is not stored on the Filecoin network before. 
> 
> If you already have a list of storage providers to work with, fill out their names and provider IDs below n/a
> 

No we don’t have storage providers yet, am looking on the slack and other discussion channels for potential partners. 
> Please supplement the above information.

Sorry for late reply due to the Christmas holiday, hope you’re doing well. Please see details above between the lines.

**Comment by Sunnyiscoming** [comment]
SPs information should be provided before being triggered. Please add SPs information and more you want to mention in the application.

**Comment by herrehesse** [comment]
Total amount of DataCap being requested
2 PiB

Expected size of single dataset (one copy)
1 PiB

Number of replicas to store
1

What is this exactly?

**Comment by jackyqj** [comment]
> SPs information should be provided before being triggered. Please add SPs information and more you want to mention in the application.

I got one partner confirmed now: f01074953
Still looking for new SPs from slack

**Comment by jackyqj** [comment]
> Total amount of DataCap being requested 2 PiB
> 
> Expected size of single dataset (one copy) 500 T
> 
> Number of replicas to store 4
> 
> What is this exactly?

So the single set of data size would be around 500T and  4 copies.

**Comment by Sunnyiscoming** [comment]
@jackyqj 
- Best practice for storing large datasets includes ideally, storing it in 3 or more regions, with 4 or more storage provider operators or owners.You should list Miner ID, Business Entity, Location of sps you will cooperate with.
- Per the https://github.com/filecoin-project/notary-governance/issues/922 for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.
