### ISSUE TITLE
[DataCap Application]Digital Earth

### ISSUE THREAD

**Issue by ssnks1** [filecoin-project/filecoin-plus-large-datasets#2307]
### Data Owner Name

Digital Earth

### What is your role related to the dataset

Data Preparer

### Data Owner Country/Region

South Africa

### Data Owner Industry

Environment

### Website

https://www.digitalearthafrica.org/

### Social Media

```text
https://www.digitalearthafrica.org/
```

### Total amount of DataCap being requested

5PiB

### Expected size of single dataset (one copy)

512t

### Number of replicas to store

10

### Weekly allocation of DataCap requested

1PiB

### On-chain address for first allocation

f1eguy4uruawgfecmsj5kid57c7v6kcdprzwejggi

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Landsat scenes and metadata. DE Africa provides data from Landsat 5, 7 and 8 satellites, including historical observations dating back to late 1980s and regularly updated new acquisitions.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
Landsat scenes and metadata. DE Africa provides data from Landsat 5, 7 and 8 satellites, including historical observations dating back to late 1980s and regularly updated new acquisitions.
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### If you are a data preparer. What is your location (Country/Region)

Viet Nam

### Please share a sample of the data

```text
Landsat scenes and metadata. DE Africa provides data from Landsat 5, 7 and 8 satellites, including historical observations dating back to late 1980s and regularly updated new acquisitions.
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Daily

### For how long do you plan to keep this dataset stored on Filecoin

Less than 1 year

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, South America, Europe

### How will you be distributing your data to storage providers

Cloud storage (i.e. S3), HTTP or FTP server, IPFS, Shipping hard drives, Lotus built-in data transfer

### How do you plan to choose storage providers

Slack, Filmine, Big Data Exchange, Partners

### If you already have a list of storage providers to work with, fill out their names and provider IDs below

_

f02079257 - Vietnam
f01234567 - Vietnam
f02252023 - Japan
f02252024 - Japan
f02105010 - Malaysia_

### How do you plan to make deals to your storage providers

Boost client, Lotus client, Bidbot

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by ssnks1** [comment]
The client has started and hoping to receive support. Here are our cooperative clients:

f02079257 - Vietnam
f01234567 - Vietnam
f02252023 - Japan
f02252024 - Japan
f02105010 - Malaysia

**Comment by a1991car** [comment]
Thank you for contacting me, as the first rounder I choose to help you

**Comment by a1991car** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebhihyiweivyelk252jspgnx6lbkoeq6kw4i5fzxsavw43jqlddf6 
#### Address 
> f155pwwoytusrwhijxtnybex2szracdvl7rfsyd6a
#### Datacap Allocated
> 2.00PiB
#### Signer Address
> f1qnumecdypgrbaebtkdfjnwt5ndacadcuas3deiq
#### Id
> aa941a55-6e1b-4f45-812b-525f9e7afdc0
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebhihyiweivyelk252jspgnx6lbkoeq6kw4i5fzxsavw43jqlddf6

**Comment by Aaron01230** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb36xlhcdg7l6iq3cwpcipq5tdb2gtcqlmtxfy2eur52qp5mh777s 
#### Address 
> f155pwwoytusrwhijxtnybex2szracdvl7rfsyd6a
#### Datacap Allocated
> 2.00PiB
#### Signer Address
> f1xrnysd4gimg64d4l6qi7ulzwwq22c6vfg6lpw3i
#### Id
> aa941a55-6e1b-4f45-812b-525f9e7afdc0
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb36xlhcdg7l6iq3cwpcipq5tdb2gtcqlmtxfy2eur52qp5mh777s

**Comment by mikezli** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedpsuzprdtvgbq52cwemkx4zlirp7f2ncgcpqpsunavfad6fjr65m 
#### Address 
> f155pwwoytusrwhijxtnybex2szracdvl7rfsyd6a
#### Datacap Allocated
> 2.00PiB
#### Signer Address
> f1dnb3uz7sylxk6emti3ififcvu3nlufnnsjui6ea
#### Id
> a942f047-d566-498c-8c02-4b7368c2e4d9
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedpsuzprdtvgbq52cwemkx4zlirp7f2ncgcpqpsunavfad6fjr65m

**Comment by 1ane-1** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecky53543yfkwaun42qlc7kdwkmrtjruuytypjqwdgyf6fw2jlr7q 
#### Address 
> f155pwwoytusrwhijxtnybex2szracdvl7rfsyd6a
#### Datacap Allocated
> 2.00PiB
#### Signer Address
> f1mdk7s2vntzm6hu35yuo6vjubtrpfnb2awhgvrri
#### Id
> a942f047-d566-498c-8c02-4b7368c2e4d9
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecky53543yfkwaun42qlc7kdwkmrtjruuytypjqwdgyf6fw2jlr7q

**Comment by nj-steve** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedybjdd5esthuucmzeb5c5xh7ulssv4lqhee75m4nyow5j3rxytd4 
#### Address 
> f1wbwggh7id4lm3loajxf5lcnk7o2vacvpk64wvna
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f1xx6555qijma7igpnjspyvdunc4vfxkawnpqy5ii
#### Id
> e9e6c665-9110-497c-8ca9-1ce0dea828de
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedybjdd5esthuucmzeb5c5xh7ulssv4lqhee75m4nyow5j3rxytd4

**Comment by SuperChaiChai** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb5qwrtedxwtyxaopmntsli36rk7hvvjbgn4baj56gifn7wqaywhq 
#### Address 
> f1wbwggh7id4lm3loajxf5lcnk7o2vacvpk64wvna
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f12mckci3omexgzoeosjvstcfxfe4vqw7owdia3da
#### Id
> e9e6c665-9110-497c-8ca9-1ce0dea828de
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb5qwrtedxwtyxaopmntsli36rk7hvvjbgn4baj56gifn7wqaywhq

**Comment by hyunmoon** [comment]
checker:manualTrigger
