### ISSUE TITLE
[DataCap Application] <Resolution Rapid Refresh (HRRR) Model> 

### ISSUE THREAD

**Issue by himomo007** [filecoin-project/filecoin-plus-large-datasets#2309]
### Data Owner Name

Resolution Rapid Refresh (HRRR) Model

### What is your role related to the dataset

Data Preparer

### Data Owner Country/Region

United States

### Data Owner Industry

Environment

### Website

https://github.com/awslabs/open-data-docs/tree/main/docs/noaa/noaa-hrrr

### Social Media

```text
Website: https://www.noaa.gov/ (Website)
```

### Total amount of DataCap being requested

15PiB

### Expected size of single dataset (one copy)

3PiB

### Number of replicas to store

5

### Weekly allocation of DataCap requested

1PiB

### On-chain address for first allocation

f1gavvrcgtksbr3p5g7clqx2xyji7usvdagd75may

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
The HRRR is a NOAA real-time 3-km resolution, hourly updated, cloud-resolving, convection-allowing atmospheric model, initialized by 3km grids with 3km radar assimilation. Radar data is assimilated in the HRRR every 15 min over a 1-h period adding further detail to that provided by the hourly data assimilation from the 13km radar-enhanced.
HRRR implementations at NCEP
HRRRv1 - 30 Sept 2014
HRRRv2 - 23 Aug 2016
HRRRv3 - 12 July 2018
HRRRv4 - 2 Dec 2020
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
The High-Resolution Rapid Refresh (HRRR) is sourced by Global System Laboratory from National Oceanic && Atmospheric Administration. It is a NOAA real-time 3-km resolution, hourly updated, cloud-resolving, convection-allowing atmospheric model, initialized by 3km grids with 3km radar assimilation. Radar data is assimilated in the HRRR every 15 min over a 1-h period adding further detail to that provided by the hourly data assimilation from the 13km radar-enhanced Rapid Refresh.
HRRR dataset stored on AWS is the archive since 2014 with a total size of 2PiB and 38526457 Object.
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### If you are a data preparer. What is your location (Country/Region)

United States

### If you are a data preparer, how will the data be prepared? Please include tooling used and technical details?

```text
Mainly official tools such as boost or lotus
```

### Has this dataset been stored on the Filecoin network before? If so, please explain and make the case why you would like to store this dataset again to the network. Provide details on preparation and/or SP distribution.

```text
It was stored before, but there are some applications that have been closed. As a public dataset of significance to the development of human history, it deserves to be stored over and over again.
```

### Please share a sample of the data

```text
https://rapidrefresh.noaa.gov/hrrr/
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

1.5 to 2 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, Europe, Australia (continent)

### How will you be distributing your data to storage providers

HTTP or FTP server, Shipping hard drives

### How do you plan to choose storage providers

Slack, Partners

### If you already have a list of storage providers to work with, fill out their names and provider IDs below

```text
f02363308
f02820572  
f02829747 
f02807399
f02916995 
f02078669
f02363306   
f02917080
f02934915 
f02934916
f02934869   
f02934879
```

### How do you plan to make deals to your storage providers

Boost client, Lotus client, Singularity

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by data-programs** [comment]
<img width="32" alt="KYC" Verified src="https://stable.filplus.storage/images/filplus-kyc-verified-badge.png"/>

This user’s identity has been verified through [filplus.storage](https://filplus.storage)

**Comment by himomo007** [comment]
Hi @Sunnyiscoming ，HRRR is a public dataset, and the HRRR dataset stored on AWS has been archived since 2014, with a total size of 2 PiB and 38,526,457 objects.

Previously, I applied for a 35 PiB DC, which may be a bit excessive. For the new application, I plan to start with 15 PiB. Considering the actual dataset size of 2 PiB, applying for a 15 PiB DC quota is relatively conservative.

Recently, we have observed similar applications for NOAA and NIH, and we hope to continue receiving favorable treatment from the community. Wishing you a smooth New Year.

**Comment by Sunnyiscoming** [comment]
Hello. Please provide ID, City, Country, Organization of each SP here.

Per the https://github.com/filecoin-project/notary-governance/issues/922 for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

This information will be reviewed by Fil+ Governance team to confirm validity and then the application will be allowed to move forward for additional notary review.

**Comment by himomo007** [comment]
The form submitted,thanks.
