### ISSUE TITLE
[DataCap Application] lamost

### ISSUE THREAD

**Issue by liou38469** [filecoin-project/filecoin-plus-large-datasets#2315]
### Data Owner Name

LAMOST DR7

### What is your role related to the dataset

Data Preparer

### Data Owner Country/Region

Armenia

### Data Owner Industry

Life Science / Healthcare

### Website

http://www.lamost.org/dr7/v2.0/

### Social Media

```text
http://www.lamost.org/dr7/v2.0/
```

### Total amount of DataCap being requested

5PiB

### Expected size of single dataset (one copy)

1P

### Number of replicas to store

5

### Weekly allocation of DataCap requested

1PiB

### On-chain address for first allocation

f1f765xblwrppl6mkn2b6kfzw6qwcngyk5hlhkpby

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Observed Plates：4,922 Total Spectra：10,431,197

Guoshoujing Telescope (the Large Sky Area Multi-Object Fiber Spectroscopic Telescope LAMOST) is a National Major Scientific Project built by the Chinese Academy of Sciences. Funding for the project has been provided by the National Development and Reform Commission. LAMOST is operated and managed by the National Astronomical Observatories, Chinese Academy of Sciences.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
Observed Plates：4,922 Total Spectra：10,431,197

Guoshoujing Telescope (the Large Sky Area Multi-Object Fiber Spectroscopic Telescope LAMOST) is a National Major Scientific Project built by the Chinese Academy of Sciences. Funding for the project has been provided by the National Development and Reform Commission. LAMOST is operated and managed by the National Astronomical Observatories, Chinese Academy of Sciences.
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### If you are a data preparer. What is your location (Country/Region)

None

### Please share a sample of the data

```text
http://www.lamost.org/dr7/v2.0/
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

1.5 to 2 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, Europe

### How will you be distributing your data to storage providers

Cloud storage (i.e. S3), HTTP or FTP server, IPFS, Shipping hard drives, Lotus built-in data transfer

### How do you plan to choose storage providers

Slack, Partners

### How do you plan to make deals to your storage providers

Boost client, Lotus client, Bidbot, Singularity

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by liou38469** [comment]
Thanks for the support, we have brought 400P growth to Filecoin. Now the customer has restarted and we have applied for DC for the customer.

**Comment by liou38469** [comment]
f02079257 Vietnam
f01234567 Vietnam
f02252023 Japan
f02252024 Japan
f02105010 Malaysia

**Comment by sxxfuture-official** [comment]
support the first round

**Comment by sxxfuture-official** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceatdu2erxdijtok7pyksabh4opocdkfko7a6yx2ls7zwpyozaxc54 
#### Address 
> f1f765xblwrppl6mkn2b6kfzw6qwcngyk5hlhkpby
#### Datacap Allocated
> 2.00PiB
#### Signer Address
> f1foiomqlmoshpuxm6aie4xysffqezkjnokgwcecq
#### Id
> 88139bad-01d9-4843-aef9-a2f8ca7e4e6a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceatdu2erxdijtok7pyksabh4opocdkfko7a6yx2ls7zwpyozaxc54

**Comment by Sunnyiscoming** [comment]
Hello, per the https://github.com/filecoin-project/notary-governance/issues/922 for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

This information will be reviewed by Fil+ Governance team to confirm validity and then the application will be allowed to move forward for additional notary review.

**Comment by Sunnyiscoming** [comment]
> f02079257 Vietnam
> f01234567 Vietnam
> f02252023 Japan
> f02252024 Japan
> f02105010 Malaysia
Please provide City, Organization name of each SP here.

**Comment by PluskitOfficial** [comment]
Also need to know the relevant info.  about each SP.

**Comment by liou38469** [comment]
f02079257 Vietnam Digitalstar
f01234567 Vietnam Digitalstar
f02252023 Japan   Ōka Denshi 
f02252024 Japan   Ōka Denshi  
f02105010 Malaysia  Xing Chen

**Comment by Sunnyiscoming** [comment]
SP List provided:
[{"providerID": "f02079257","City": "", "Country": "Vietnam", "SPOrg","Digitalstar"},
{"providerID": "f01234567","City": "", "Country": "Vietnam", "SPOrg","Digitalstar"},
{"providerID": "f02252023","City": "Ōka", "Country": "Japan", "SPOrg","Denshi"},
{"providerID": "f02252024","City": "Ōka", "Country": "Japan", "SPOrg","Denshi"},
{"providerID": "f02105010","City": "Xing", "Country": "Malaysia", "SPOrg","Chen"},]

**Comment by Sunnyiscoming** [comment]
The form has not been received.

**Comment by liou38469** [comment]
We are still on New Year's holiday and will submit it within five days, thank you

**Comment by liou38469** [comment]
<img width="807" alt="WX20240218-205252@2x" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/142089399/79a7726c-8fb3-432a-86e5-af0dac8f0f04">
we submit it

**Comment by liou38469** [comment]
Would love to see someone sign for us

**Comment by psh0691** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebytzby4u4x427ayg22mhhfofjqvnreb7q26w7wh25rr3xh7mg2rg 
#### Address 
> f1f765xblwrppl6mkn2b6kfzw6qwcngyk5hlhkpby
#### Datacap Allocated
> 2.00PiB
#### Signer Address
> f1qdko4jg25vo35qmyvcrw4ak4fmuu3f5rif2kc7i
#### Id
> 88139bad-01d9-4843-aef9-a2f8ca7e4e6a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebytzby4u4x427ayg22mhhfofjqvnreb7q26w7wh25rr3xh7mg2rg

**Comment by psh0691** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedan4dofvowjnf4tvcg5mpnd4vfps6dslmnareedygbe5dxtoxw2s 
#### Address 
> f1f765xblwrppl6mkn2b6kfzw6qwcngyk5hlhkpby
#### Datacap Allocated
> 2.00PiB
#### Signer Address
> f1qdko4jg25vo35qmyvcrw4ak4fmuu3f5rif2kc7i
#### Id
> 94e207c7-9d66-41da-8517-b7ce6143e947
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedan4dofvowjnf4tvcg5mpnd4vfps6dslmnareedygbe5dxtoxw2s

**Comment by psh0691** [comment]
I signed it, but it was not assigned, so I re-signed it.

**Comment by stcloudlisa** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacea5y4twjat65axhnbsqtowajpvhjt25pgkma5cohmunbvuryow72g 
#### Address 
> f1f765xblwrppl6mkn2b6kfzw6qwcngyk5hlhkpby
#### Datacap Allocated
> 2.00PiB
#### Signer Address
> f1jvvltduw35u6inn5tr4nfualyd42bh3vjtylgci
#### Id
> 94e207c7-9d66-41da-8517-b7ce6143e947
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacea5y4twjat65axhnbsqtowajpvhjt25pgkma5cohmunbvuryow72g

**Comment by AlanGreaterheat** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacearpvay6y5a467iwbse7btbfb3j6i5wc6pld37pkkjpqulkv4tumo 
#### Address 
> f1f765xblwrppl6mkn2b6kfzw6qwcngyk5hlhkpby
#### Datacap Allocated
> 2.00PiB
#### Signer Address
> f1pnmzlxj7cfeo2v6oj5nco46hkg2l46wj7o4xxui
#### Id
> bcde1760-6073-4b8b-b53a-c080a3840c6a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacearpvay6y5a467iwbse7btbfb3j6i5wc6pld37pkkjpqulkv4tumo

**Comment by 1ane-1** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceca4ofxsrowpedny37ahktj5wbt7yferrfrgnarg63iw6dd4pgrla 
#### Address 
> f1f765xblwrppl6mkn2b6kfzw6qwcngyk5hlhkpby
#### Datacap Allocated
> 2.00PiB
#### Signer Address
> f1mdk7s2vntzm6hu35yuo6vjubtrpfnb2awhgvrri
#### Id
> 5aca8088-aef7-4e21-8390-67de988ecf19
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceca4ofxsrowpedny37ahktj5wbt7yferrfrgnarg63iw6dd4pgrla

**Comment by Aaron01230** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced2rziwynmkyq2xgnrs65xhkgzbjgxz6qkdpftcovrnvc3t5qxpnk 
#### Address 
> f1f765xblwrppl6mkn2b6kfzw6qwcngyk5hlhkpby
#### Datacap Allocated
> 2.00PiB
#### Signer Address
> f1xrnysd4gimg64d4l6qi7ulzwwq22c6vfg6lpw3i
#### Id
> 5aca8088-aef7-4e21-8390-67de988ecf19
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced2rziwynmkyq2xgnrs65xhkgzbjgxz6qkdpftcovrnvc3t5qxpnk

**Comment by nicelove666** [comment]
checker:manualTrigger
