### ISSUE TITLE
[DataCap Application] <CS Render> - <The Smithsonian Digitization of Collections>

### ISSUE THREAD

**Issue by shliming** [filecoin-project/filecoin-plus-large-datasets#2316]
### Data Owner Name

Smithsonian Institution

### What is your role related to the dataset

Data Preparer

### Data Owner Country/Region

United States

### Data Owner Industry

Arts & Recreation

### Website

https://www.si.edu/

### Social Media

```text
https://www.si.edu/about
```

### Total amount of DataCap being requested

5PiB

### Expected size of single dataset (one copy)

1 PiB

### Number of replicas to store

5

### Weekly allocation of DataCap requested

600TiB

### On-chain address for first allocation

f1zozfxoynkg7eygtgnilf6zb2m56nplz3odumgua

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
CS Render is a rendering service cloud platform that is developed independently. We are well known in China in 3D production, digital media, architectural design, film special effects, animation games, advertising and other industries.We are interested in filecoin, and we've been paying attention for years.In 2020, we invested in a sealing node.Now we want to store some opendata of 2D or 3D to filecoin net to promote ecological development .
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
The Smithsonian’s mission is the "increase and diffusion of knowledge" and has been collecting since 1846. The Smithsonian, through its efforts to digitize its multidisciplinary collections, has created millions of digital assets and related metadata describing the collection objects. On February 25th, 2020, the Smithsonian released over 2.8 million CC0 interdisciplinary 2-D and 3-D images, related metadata, and additionally, research data from researches across the Smithsonian. The 2.8 million "open access" collections are a subset of the Smithsonian’s 155 million objects, 2.1 million library volumes and 156,000 cubic feet of archival collections held in 19 museums, 9 research centers, libraries, archives and the National Zoo. Digitization of collections is ongoing.
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### If you are a data preparer. What is your location (Country/Region)

China

### If you are a data preparer, how will the data be prepared? Please include tooling used and technical details?

```text
lotus, graphsplit, others/custom tool
The other tool is the Swan Client tool (https://github.com/filswan/go-swan-client#Graphsplit) to prepare the dataset.
```

### Please share a sample of the data

```text
s3://smithsonian-open-access/
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Monthly

### For how long do you plan to keep this dataset stored on Filecoin

1.5 to 2 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, Europe

### How will you be distributing your data to storage providers

HTTP or FTP server, IPFS, Shipping hard drives, Lotus built-in data transfer

### How do you plan to choose storage providers

Slack, Partners, Others

### If you answered "Others" in the previous question, what is the tool or platform you plan to use

```text
such as wechat group
```

### If you already have a list of storage providers to work with, fill out their names and provider IDs below

```text
f02132642 Singapore
f02811050 Chia
f02237709 HongKog
f02826888 Canada
f02029115 Chia
```

### How do you plan to make deals to your storage providers

Boost client, Lotus client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
Hello, per the https://github.com/filecoin-project/notary-governance/issues/922 for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

This information will be reviewed by Fil+ Governance team to confirm validity and then the application will be allowed to move forward for additional notary review.

Please provide ID, City, Country, Organization of each SP here.

**Comment by shliming** [comment]
The initialized SPs' infomation is here.  
| SP ID          | Organization |  City           |   Country |
| ------         | ------            | ------         | ------     | 
| f02132642 | QC.sg           | Singapore   | Singapore |
| f02237709 | Mine Fill       |HongKong         | China      |
| f02836485 | StorageTrust|Chengdu     | Chia  |
| f02826888 | chimsen       |Toronto      | Canada |
| f02029115 | JiaYin       |Shanghai      | China |
| f02806894 | chimsen       |Seoul      | Korea |
| f02229707 | NJ       |HongKong      | China |

<img width="762" alt="图片" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/116863228/a65acbc7-6023-4fa4-87f4-13c016be4d1b">

**Comment by shliming** [comment]
@Sunnyiscoming  We have submitted. Thanks .

**Comment by Sunnyiscoming** [comment]
SP List provided:
[{"providerID": "f02132642","City": "Singapore", "Country": "Singapore", "SPOrg","QC.sg"},
{"providerID": "f02237709","City": "HongKong", "Country": "China", "SPOrg","Mine Fill"},
{"providerID": "f02836485","City": "Chengdu", "Country": "Chia", "SPOrg","StorageTrust"},
{"providerID": "f02826888","City": "Toronto", "Country": "Canada", "SPOrg","chimsen"},
{"providerID": "f02029115","City": "Shanghai", "Country": "China", "SPOrg","JiaYin"},
{"providerID": "f02806894","City": "Seoul", "Country": "Korea", "SPOrg","chimsen"},
{"providerID": "f02229707","City": "HongKong", "Country": "China", "SPOrg","NJ"},]

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
>5 PiB

**Expected weekly DataCap usage rate**
>600 TiB

**Client address**
>f1zozfxoynkg7eygtgnilf6zb2m56nplz3odumgua

**Comment by shliming** [comment]
Hello @Sunnyiscoming  The bot has not trigger to the label of ready to sign. Please help us. Thanks.

**Comment by shliming** [comment]
Hello @Sunnyiscoming The bot has not trigger to the label of ready to sign. Please help us. Thanks.

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
>5 PiB

**Expected weekly DataCap usage rate**
>600 TiB

**Client address**
>f1zozfxoynkg7eygtgnilf6zb2m56nplz3odumgua

**Comment by woshidama323** [comment]
LGTM Will support this first round
Keep tracing

**Comment by woshidama323** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedenprwrbuejxv7dqe35vfmqazheqrduizlzy6y4ph4niw5j36pn6 
#### Address 
> f1zozfxoynkg7eygtgnilf6zb2m56nplz3odumgua
#### Datacap Allocated
> 256.00TiB
#### Signer Address
> f12tk3adljauwnd3hjbigpfxb7b7gdlj63p6afwtq
#### Id
> a7d7ee5c-e84e-449d-893f-ebe233b4e383
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedenprwrbuejxv7dqe35vfmqazheqrduizlzy6y4ph4niw5j36pn6

**Comment by Joss-Hua** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced3s26nzwpnwad675gihwxx5yywlu3zbjwous2i3bes45qyvjke7u 
#### Address 
> f1zozfxoynkg7eygtgnilf6zb2m56nplz3odumgua
#### Datacap Allocated
> 256.00TiB
#### Signer Address
> f1tfg54zzscugttejv336vivknmsnzzmyudp3t7wi
#### Id
> a7d7ee5c-e84e-449d-893f-ebe233b4e383
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced3s26nzwpnwad675gihwxx5yywlu3zbjwous2i3bes45qyvjke7u

**Comment by Joss-Hua** [comment]
👀

**Comment by shliming** [comment]
keep
