### ISSUE TITLE
[DataCap Application] Smartcity Dataset for Slingshot 2.7 and forward

### ISSUE THREAD

**Issue by xingjitansuo** [filecoin-project/filecoin-plus-large-datasets#232]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: CabrinaHuang-Xingjitansuo
- Website / Social Media: http://api.sr2.glm2m.com/index.php?r=smartcity-dataset%2Findex
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 3PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 300TiB 
- On-chain address for first allocation: f1zil5gn6fgelxw5lb7sbv22eayfltg7eohcrqpni

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization. 
```
SmartCity Dataset is generated by a research lab in University of Electronic Science and Technology of China. Xingjitansuo personally contacted the research lab on onboarding its open dataset to Filecoin. Xingjitansuo has previously participated in Slingshot and and is familiar with generating cars, contacting SP, and sending deals. SmartCity is currently a Slingshot Curate Dataset under the help of Xingjitansuo.

```

What is the primary source of funding for this project?
```
Slingshot Reward 
```

What other projects/ecosystem stakeholders is this project associated with?
```
Slingshot phase 2.7 and forward.

```

## Use-case details

Describe the data being stored onto Filecoin
```
SmartCity Dataset is a Slingshot Curated Dataset. 
SmartCity Dataset is part of Smartcity Sensor-based network and data analysis system which is a kind of Urban Nervous System and Urban Brain. It adopts the world's most advanced distributed linear sensor system using the widely-laid communication optical fiber as the sensing element continuously detect and collect the temperature, pressure, vibration, sound and other information around the optical fiber. The artificial intelligence system is used to identify and classify signal types, which can be widely used in urban and tunnel construction monitoring, underground pipeline network, pipeline monitoring, track monitoring, cross-border monitoring, displacement monitoring, earthquake monitoring and other scenes. As the cities nervous system, the combination of artificial intelligence technology handles massive amounts of city data every day and provides leading technical services for smart cities.

```

Where was the data in this dataset sourced from?
```
Those datasets are generated by a research lab in University of Electronic Science and Technology of China.

```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
http://api.sr2.glm2m.com/index.php?r=smartcity-dataset%2Fdataset
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes
```

What is the expected retrieval frequency for this data?
```
Not often.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
>= 1 year
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
All Region
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
1. Prepare car file and upload to server for SP to download
2. Propose deal to SP once they have file locally.

```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
I met a bunch of SPs in different sealing capability in Singshot-Restore, and will co-op with them.

```

How will you be distributing deals across storage providers?
```
Distribute equally to all SP.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
I got experience from being a client in Slingshot-Restore.
```

**Comment by xingjitansuo** [comment]
@galen-mcandrew  Can you please take a look

**Comment by galen-mcandrew** [comment]
## Multisig Notary requested
#### Total DataCap requested 
> 3PiB
#### Expected weekly DataCap usage rate 
> 300TiB

**Comment by MegTei** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaz45pq4wgoviuznpm3e3mwmb3yezgj6b4w5a74qn4a5pknas5ewu 
#### Address 
> f1zil5gn6fgelxw5lb7sbv22eayfltg7eohcrqpni
#### Datacap Allocated
> 150.00TiB
#### Signer Address
> f1ystxl2ootvpirpa7ebgwl7vlhwkbx2r4zjxwe5i
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaz45pq4wgoviuznpm3e3mwmb3yezgj6b4w5a74qn4a5pknas5ewu

**Comment by neogeweb3** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecvih2bhzf2k5a25qexelkweiltxazkibohwz5mlazgcowynugaqu 
#### Address 
> f1zil5gn6fgelxw5lb7sbv22eayfltg7eohcrqpni
#### Datacap Allocated
> 150.00TiB
#### Signer Address
> f13k5zr6ovc2gjmg3lvd43ladbydhovpylcvbflpa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecvih2bhzf2k5a25qexelkweiltxazkibohwz5mlazgcowynugaqu

**Comment by xingjitansuo** [comment]
@galen-mcandrew 
Not sure why the bot is not triggered again this time .... I only have 5.3 TiB Datacap left in address. (https://verify.glif.io/), and is far below the 25% threshold.  Could you please take a look ?

**Comment by flyworker** [comment]
I did not see this application in https://plus.fil.org/

**Comment by dkkapur** [comment]
## DataCap Allocation requested

#### Multisig Notary address
> f01736650

#### Client address
> f1zil5gn6fgelxw5lb7sbv22eayfltg7eohcrqpni

#### DataCap allocation requested
> 300TiB

**Comment by cryptowhizzard** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacearwwxpgnokypxzfl54kohfwgaham3n2v2why26iaxwpkgmbuugpw 
#### Address 
> f1zil5gn6fgelxw5lb7sbv22eayfltg7eohcrqpni
#### Datacap Allocated
> 300.00TiB
#### Signer Address
> f1krmypm4uoxxf3g7okrwtrahlmpcph3y7rbqqgfa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacearwwxpgnokypxzfl54kohfwgaham3n2v2why26iaxwpkgmbuugpw

**Comment by xingjitansuo** [comment]
@Reiers @IreneYoung @flyworker @MasaakiNawatani @tinkmk @s0nik42 @aaitor @rayshitou  @dannyob @TimWilliams00 @ozhtdong @Fenbushi-Filecoin @steven004 @neogeweb3 @waynewyang @swatchliu @MRJAVAZHAO @KodaRobotDog @andrewxhill @XnMatrixSV

Hi, could someone please help here ?

**Comment by TimWilliams00** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaujixosvztnqiewibqftvsrhhh7m2xeosb7eqkmrud7bfretegfc 
#### Address 
> f1zil5gn6fgelxw5lb7sbv22eayfltg7eohcrqpni
#### Datacap Allocated
> 300.00TiB
#### Signer Address
> f1fkxkfxgopjf3ufnfg5i3m6qlwf73kp4w5zz7nnq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaujixosvztnqiewibqftvsrhhh7m2xeosb7eqkmrud7bfretegfc

**Comment by TimWilliams00** [comment]
> @Reiers @IreneYoung @flyworker @MasaakiNawatani @tinkmk @s0nik42 @aaitor @rayshitou @dannyob @TimWilliams00 @ozhtdong @Fenbushi-Filecoin @steven004 @neogeweb3 @waynewyang @swatchliu @MRJAVAZHAO @KodaRobotDog @andrewxhill @XnMatrixSV
> 
> Hi, could someone please help here ?

Done

**Comment by xingjitansuo** [comment]
@Reiers @IreneYoung @flyworker @MasaakiNawatani @tinkmk @s0nik42 @aaitor @rayshitou @dannyob @TimWilliams00 @ozhtdong @Fenbushi-Filecoin @steven004 @neogeweb3 @waynewyang @swatchliu @MRJAVAZHAO @KodaRobotDog @andrewxhill @XnMatrixSV @cryptowhizzard 

Can someone please help me to sign again?

**Comment by Reiers** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedccgvww62zhh5znuevfgpiotzepozksqos5qdkrujcn4ajzllyjo 
#### Address 
> f1zil5gn6fgelxw5lb7sbv22eayfltg7eohcrqpni
#### Datacap Allocated
> 600.00TiB
#### Signer Address
> f1oz43ckvmtxmmsfzqm6bpnemqlavz4ifyl524chq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedccgvww62zhh5znuevfgpiotzepozksqos5qdkrujcn4ajzllyjo

**Comment by dannyob** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecdin7g22oipfpjglvxkb4oqqja5hykep2smherwcpnlraevbv2wa 
#### Address 
> f1zil5gn6fgelxw5lb7sbv22eayfltg7eohcrqpni
#### Datacap Allocated
> 600.00TiB
#### Signer Address
> f1k6wwevxvp466ybil7y2scqlhtnrz5atjkkyvm4a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecdin7g22oipfpjglvxkb4oqqja5hykep2smherwcpnlraevbv2wa

**Comment by MegTei** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec7wu4z7m24kbwbzalmhnm57k4ggskkuyyk3yfo4bprreydmvxihy 
#### Address 
> f1zil5gn6fgelxw5lb7sbv22eayfltg7eohcrqpni
#### Datacap Allocated
> 1.17PiB
#### Signer Address
> f1ystxl2ootvpirpa7ebgwl7vlhwkbx2r4zjxwe5i
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec7wu4z7m24kbwbzalmhnm57k4ggskkuyyk3yfo4bprreydmvxihy

**Comment by xingjitansuo** [comment]
@Reiers @IreneYoung @s0nik42 @rayshitou @dannyob @TimWilliams00 @ozhtdong @Fenbushi-Filecoin  @neogeweb3 @swatchliu @andrewxhill @XnMatrixSV @cryptowhizzard
Could one of you help me to sign this? Really appreciated!

**Comment by cryptowhizzard** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacear4h7wyqrowsew7qxrldm5ihwfhmjqdprg4g6e4lcfvetecy3rum 
#### Address 
> f1zil5gn6fgelxw5lb7sbv22eayfltg7eohcrqpni
#### Datacap Allocated
> 1.17PiB
#### Signer Address
> f1krmypm4uoxxf3g7okrwtrahlmpcph3y7rbqqgfa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacear4h7wyqrowsew7qxrldm5ihwfhmjqdprg4g6e4lcfvetecy3rum

**Comment by IreneYoung** [comment]
Hi @xingjitansuo, I can support it if you still need DataCap.

**Comment by kernelogic** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceayevl6hf2lkpu3ooafa363rpnvfu7izu5rw6xrmpmfrh3fsz2lxu 
#### Address 
> f1zil5gn6fgelxw5lb7sbv22eayfltg7eohcrqpni
#### Datacap Allocated
> 823.92TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceayevl6hf2lkpu3ooafa363rpnvfu7izu5rw6xrmpmfrh3fsz2lxu

**Comment by xinaxu** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedziaeg3rsu3453n5reqt3jb4ynvhb4qhc7ejtffhwwdy2gwsqtsw 
#### Address 
> f1zil5gn6fgelxw5lb7sbv22eayfltg7eohcrqpni
#### Datacap Allocated
> 823.92TiB
#### Signer Address
> f1k3ysofkrrmqcot6fkx4wnezpczlltpirmrpsgui
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedziaeg3rsu3453n5reqt3jb4ynvhb4qhc7ejtffhwwdy2gwsqtsw

**Comment by kevzak** [comment]
Hello @xingjitansuo  - I'm Kevin from the Client Success Team. I saw you were recently granted more DataCap but there's been a delay in onboarding data. I wanted to reach out to offer any support as needed. Let me know if you have any questions or issues currently holding you back.

Also, feel free to post a message in #fil-plus or slingshot slack channel.

**Comment by xingjitansuo** [comment]
@kevzak Thanks for reaching out. The main reason for delay in onboarding is the speed of dataset transfer. The internet bandwidth is the blocker.

**Comment by xingjitansuo** [comment]
Closing this one. Appreciate everyone involved in this LDN.

**Comment by filplus-checker** [comment]
## DataCap and CID Checker Report[^1]
 - Organization: `CabrinaHuang-Xingjitansuo`
 - Client: `f1zil5gn6fgelxw5lb7sbv22eayfltg7eohcrqpni`
### Storage Provider Distribution
The below table shows the distribution of storage providers that have stored data for this client.

If this is the first time a provider takes verified deal, it will be marked as `new`.

For most of the datacap application, below restrictions should apply.
 - Storage provider should not exceed 25% of total datacap.
 - Storage provider should not be storing duplicate data for more than 20%.
 - Storage provider should have published its public IP address.
 - All storage providers should be located in different regions.

⚠️ 52.76% of total deal sealed by [f01826997](https://filfox.info/en/address/f01826997) are duplicate data.

⚠️ 50.00% of total deal sealed by [f01924827](https://filfox.info/en/address/f01924827) are duplicate data.

⚠️ 50.00% of total deal sealed by [f01882035](https://filfox.info/en/address/f01882035) are duplicate data.

⚠️ 49.95% of total deal sealed by [f01863339](https://filfox.info/en/address/f01863339) are duplicate data.

⚠️ 49.44% of total deal sealed by [f01840219](https://filfox.info/en/address/f01840219) are duplicate data.

⚠️ 49.32% of total deal sealed by [f01850141](https://filfox.info/en/address/f01850141) are duplicate data.

⚠️ 48.77% of total deal sealed by [f054464](https://filfox.info/en/address/f054464) are duplicate data.

⚠️ 48.59% of total deal sealed by [f01823264](https://filfox.info/en/address/f01823264) are duplicate data.

⚠️ 47.97% of total deal sealed by [f01887962](https://filfox.info/en/address/f01887962) are duplicate data.

⚠️ 26.87% of total deal sealed by [f098743](https://filfox.info/en/address/f098743) are duplicate data.

⚠️ 32.09% of total deal sealed by [f039940](https://filfox.info/en/address/f039940) are duplicate data.

⚠️ 24.60% of total deal sealed by [f0142637](https://filfox.info/en/address/f0142637) are duplicate data.

⚠️ 49.32% of total deal sealed by [f01395673](https://filfox.info/en/address/f01395673) are duplicate data.

| Provider                                                    |                            Location | Total Deals Sealed | Percentage | Unique Data | Duplicate Deals |
| :---------------------------------------------------------- | ----------------------------------: | -----------------: | ---------: | ----------: | --------------: |
| [f01826997](https://filfox.info/en/address/f01826997)`new`  |             Dongguan, Guangdong, CN |         205.89 TiB |      6.70% |   97.26 TiB |          52.76% |
| [f01924827](https://filfox.info/en/address/f01924827)`new`  |  Hong Kong, Central and Western, HK |         204.50 TiB |      6.66% |  102.25 TiB |          50.00% |
| [f01882035](https://filfox.info/en/address/f01882035)       |                Chengdu, Sichuan, CN |         204.44 TiB |      6.66% |  102.22 TiB |          50.00% |
| [f01863339](https://filfox.info/en/address/f01863339)`new`  |              Shanghai, Shanghai, CN |         204.31 TiB |      6.65% |  102.25 TiB |          49.95% |
| [f01840219](https://filfox.info/en/address/f01840219)       |                Chengdu, Sichuan, CN |         202.31 TiB |      6.59% |  102.28 TiB |          49.44% |
| [f01850141](https://filfox.info/en/address/f01850141)       |  Hong Kong, Central and Western, HK |         201.75 TiB |      6.57% |  102.25 TiB |          49.32% |
| [f054464](https://filfox.info/en/address/f054464)           |  Hong Kong, Central and Western, HK |         199.68 TiB |      6.50% |  102.29 TiB |          48.77% |
| [f01823264](https://filfox.info/en/address/f01823264)       |                Chengdu, Sichuan, CN |         198.97 TiB |      6.48% |  102.28 TiB |          48.59% |
| [f01887962](https://filfox.info/en/address/f01887962)       |  Hong Kong, Central and Western, HK |         196.53 TiB |      6.40% |  102.25 TiB |          47.97% |
| [f098743](https://filfox.info/en/address/f098743)           |             Shenzhen, Guangdong, CN |         139.87 TiB |      4.55% |  102.29 TiB |          26.87% |
| [f039940](https://filfox.info/en/address/f039940)           |                Chengdu, Sichuan, CN |         108.28 TiB |      3.53% |   73.53 TiB |          32.09% |
| [f01344987](https://filfox.info/en/address/f01344987)       |  Hong Kong, Central and Western, HK |         102.17 TiB |      3.33% |  102.17 TiB |           0.00% |
| [f01284467](https://filfox.info/en/address/f01284467)`new`  |  Hong Kong, Central and Western, HK |          99.84 TiB |      3.25% |   99.84 TiB |           0.00% |
| [f01806248](https://filfox.info/en/address/f01806248)`new`  |            Singapore, Singapore, SG |          84.82 TiB |      2.76% |   79.82 TiB |           5.89% |
| [f01392600](https://filfox.info/en/address/f01392600)       |  Hong Kong, Central and Western, HK |          84.76 TiB |      2.76% |   84.76 TiB |           0.00% |
| [f0117211](https://filfox.info/en/address/f0117211)`new`    |            Singapore, Singapore, SG |          69.52 TiB |      2.26% |   69.52 TiB |           0.00% |
| [f01270767](https://filfox.info/en/address/f01270767)`new`  |            Guangzhou, Guangdong, CN |          65.38 TiB |      2.13% |   65.38 TiB |           0.00% |
| [f0136399](https://filfox.info/en/address/f0136399)`new`    |  Hong Kong, Central and Western, HK |          44.23 TiB |      1.44% |   44.23 TiB |           0.00% |
| [f0142637](https://filfox.info/en/address/f0142637)         |                Chengdu, Sichuan, CN |          40.78 TiB |      1.33% |   30.75 TiB |          24.60% |
| [f03223](https://filfox.info/en/address/f03223)             |            San Jose, California, US |          39.23 TiB |      1.28% |   35.58 TiB |           9.32% |
| [f0240185](https://filfox.info/en/address/f0240185)         |             Clifton, New Jersey, US |          38.59 TiB |      1.26% |   34.88 TiB |           9.64% |
| [f0143858](https://filfox.info/en/address/f0143858)         |             Clifton, New Jersey, US |          35.67 TiB |      1.16% |   32.11 TiB |           9.99% |
| [f01395673](https://filfox.info/en/address/f01395673)       |                  Fuzhou, Fujian, CN |          34.56 TiB |      1.13% |   17.52 TiB |          49.32% |
| [f02301](https://filfox.info/en/address/f02301)             |            San Jose, California, US |          31.11 TiB |      1.01% |   29.52 TiB |           5.12% |
| [f01111112](https://filfox.info/en/address/f01111112)`new`  |  Hong Kong, Central and Western, HK |          26.31 TiB |      0.86% |   21.36 TiB |          18.82% |
| [f01732188](https://filfox.info/en/address/f01732188)       |               Chicago, Illinois, US |          24.42 TiB |      0.80% |   24.42 TiB |           0.00% |
| [f01702940](https://filfox.info/en/address/f01702940)       |                   Dallas, Texas, US |          23.78 TiB |      0.77% |   23.78 TiB |           0.00% |
| [f01794835](https://filfox.info/en/address/f01794835)       |                Chengdu, Sichuan, CN |          22.58 TiB |      0.74% |   22.58 TiB |           0.00% |
| [f01222595](https://filfox.info/en/address/f01222595)       |                  Moscow, Moscow, RU |          19.45 TiB |      0.63% |   18.05 TiB |           7.23% |
| [f0187709](https://filfox.info/en/address/f0187709)         |                  Moscow, Moscow, RU |          19.45 TiB |      0.63% |   18.05 TiB |           7.23% |
| [f01652333](https://filfox.info/en/address/f01652333)       |           Sunnyvale, California, US |          17.77 TiB |      0.58% |   17.77 TiB |           0.00% |
| [f0133509](https://filfox.info/en/address/f0133509)`new`    |  Hong Kong, Central and Western, HK |          15.63 TiB |      0.51% |   15.63 TiB |           0.00% |
| [f01611097](https://filfox.info/en/address/f01611097)       |        San Clemente, California, US |          12.73 TiB |      0.41% |   12.70 TiB |           0.25% |
| [f01732189](https://filfox.info/en/address/f01732189)`new`  |           San Diego, California, US |          12.03 TiB |      0.39% |   12.03 TiB |           0.00% |
| [f01672960](https://filfox.info/en/address/f01672960)       |                Chengdu, Sichuan, CN |           8.91 TiB |      0.29% |    8.91 TiB |           0.00% |
| [f01163272](https://filfox.info/en/address/f01163272)       |                 Perm, Perm Krai, RU |           8.81 TiB |      0.29% |    8.81 TiB |           0.00% |
| [f034258](https://filfox.info/en/address/f034258)           |                Chengdu, Sichuan, CN |           6.53 TiB |      0.21% |    6.53 TiB |           0.00% |
| [f01157288](https://filfox.info/en/address/f01157288)       |         Sydney, New South Wales, AU |           3.78 TiB |      0.12% |    3.78 TiB |           0.00% |
| [f0773157](https://filfox.info/en/address/f0773157)         |             Fremont, California, US |           3.75 TiB |      0.12% |    3.75 TiB |           0.00% |
| [f01208189](https://filfox.info/en/address/f01208189)       |         Sydney, New South Wales, AU |           2.91 TiB |      0.09% |    2.91 TiB |           0.00% |
| [f01509930](https://filfox.info/en/address/f01509930)       |            Guangzhou, Guangdong, CN |           1.88 TiB |      0.06% |    1.88 TiB |           0.00% |
| [f079817](https://filfox.info/en/address/f079817)           |         Tomilino, Moscow Oblast, RU |           1.66 TiB |      0.05% |    1.66 TiB |           0.00% |
| [f08240](https://filfox.info/en/address/f08240)             | Novosibirsk, Novosibirsk Oblast, RU |           1.50 TiB |      0.05% |    1.50 TiB |           0.00% |
| [f0688935](https://filfox.info/en/address/f0688935)         |                Chengdu, Sichuan, CN |         128.00 GiB |      0.00% |  128.00 GiB |           0.00% |

![Provider Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/232/1671094292159.png)
### Deal Data Replication
The below table shows how each many unique data are replicated across storage providers.
- No more than 25% of unique data are stored with less than 4 providers.

✔️ Data replication looks healthy.

| Unique Data Size | Total Deals Made | Number of Providers | Deal Percentage |
| ---------------: | ---------------: | ------------------: | --------------: |
|         4.00 GiB |        24.00 GiB |                   6 |           0.00% |
|        16.00 GiB |       144.00 GiB |                   7 |           0.00% |
|         8.00 GiB |        88.00 GiB |                   9 |           0.00% |
|        32.00 GiB |       608.00 GiB |                  11 |           0.02% |
|         1.19 TiB |        24.38 TiB |                  13 |           0.79% |
|         5.25 TiB |       114.72 TiB |                  14 |           3.74% |
|         6.53 TiB |       155.06 TiB |                  15 |           5.05% |
|        16.41 TiB |       413.09 TiB |                  16 |          13.45% |
|        19.77 TiB |       527.69 TiB |                  17 |          17.18% |
|        10.38 TiB |       293.72 TiB |                  18 |           9.56% |
|         1.78 TiB |        52.78 TiB |                  19 |           1.72% |
|       992.00 GiB |        30.00 TiB |                  20 |           0.98% |
|         3.50 TiB |       112.59 TiB |                  21 |           3.67% |
|         2.38 TiB |        78.25 TiB |                  22 |           2.55% |
|         2.22 TiB |        74.00 TiB |                  23 |           2.41% |
|         3.81 TiB |       131.66 TiB |                  24 |           4.29% |
|         8.16 TiB |       292.19 TiB |                  25 |           9.51% |
|         5.88 TiB |       218.78 TiB |                  26 |           7.12% |
|         6.25 TiB |       238.81 TiB |                  27 |           7.78% |
|         4.31 TiB |       168.91 TiB |                  28 |           5.50% |
|         2.31 TiB |        93.88 TiB |                  29 |           3.06% |
|       864.00 GiB |        35.25 TiB |                  30 |           1.15% |
|       352.00 GiB |        14.59 TiB |                  31 |           0.48% |

![Replication Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/232/1671094292824.png)
### Deal Data Shared with other Clients
The below table shows how many unique data are shared with other clients.
Usually different applications owns different data and should not resolve to the same CID.

⚠️ CID sharing has been observed.

| Other Client                                                                                                          | Application                                                                                                                     | Total Deals Affected | Unique CIDs |    Verifier |
| :-------------------------------------------------------------------------------------------------------------------- | :------------------------------------------------------------------------------------------------------------------------------ | -------------------: | ----------: | ----------: |
| [f1c2nxtixkivuzmmezwawg4nwzoknvd7hto37cy4q](https://filfox.info/en/address/f1c2nxtixkivuzmmezwawg4nwzoknvd7hto37cy4q) | [CabrinaHuang\-Slingshot Restore Program](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/249)          |            24.89 TiB |         797 |   LDN # 249 |
| [f1lnecek42mynnu5ph7ucoikald2gucl6jty2ivty](https://filfox.info/en/address/f1lnecek42mynnu5ph7ucoikald2gucl6jty2ivty) | [](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/171)                                                 |            21.13 TiB |         676 |   LDN # 171 |
| [f1pkrmygbvweykpjcut36lf7ewgqdfhjklbhvepda](https://filfox.info/en/address/f1pkrmygbvweykpjcut36lf7ewgqdfhjklbhvepda) | [Protocol Labs \( project: Slingshot Evergreen \)](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/293) |             7.22 TiB |         205 |   LDN # 293 |
| [f12m4wzu4ynkpilkh5bv4zaadigmr6hml4zg46dhq](https://filfox.info/en/address/f12m4wzu4ynkpilkh5bv4zaadigmr6hml4zg46dhq) | [Chengdu Sinso Technology Co\., Ltd\.](https://github.com/filecoin-project/filecoin-plus-client-onboarding/issues/485)          |            32.00 GiB |           1 | Zhehao Chen |

[^1]: To manually trigger this report, add a comment with text `checker:manualTrigger`
