### ISSUE TITLE
[DataCap Application] FILDATA Co., Ltd.

### ISSUE THREAD

**Issue by fildata** [filecoin-project/filecoin-plus-large-datasets#2322]
### Data Owner Name
FILDATA Co., Ltd.

### What is your role related to the dataset
Dataset Owner

### Data Owner Country/Region
South Korea

### Data Owner Industry
IT & Technology Services

### Website
[https://theskyzone.net/](https://theskyzone.net/)

### Social Media
https://theskyzone.net/ (web)

### Total amount of DataCap being requested
5 PiB

### Expected size of single dataset (one copy)
20 GiB

### Number of replicas to store
7

### Weekly allocation of DataCap requested
300 TiB

### On-chain address for first allocation
f3vvab3qun5ye6w7ut2vow7o3r4uap3qmt3xz3eib2cp7j3chfb2v3auu4p3w5h62pjqj7dkta3xs5vaky4goa

### Data Type of Application
Private Non-Profit / Social impact

### Custom multisig
- [ ] Use Custom Multisig

### Identifier
n/a

### Share a brief history of your project and organization
Organization : FILDATA Co., Ltd.
 FILDATA is a corporation that develops IT services in Korea and provides services to customers.
 FILDATA established and operates the company in 2020 and directly operates and manages its own storage data center. And based on this, we provide services to our customers.

Project : theskyzone.net
 We are providing our customers with a cloud storage service.
 Our customers are using the service for work, personal work, and backup purposes.
 Cloud storage service provides services through various channels based on web browsers, folder synchronization of Windows and Mac PCs, and iOS and Android apps.

 theskyzone.net service demo
  You can use the service demo through the information below.
  URL : https://theskyzone.net
  Demo ID : demo
  Demo Password : demo17291729*

### Is this project associated with other projects/ecosystem stakeholders?
No

### If answered yes, what are the other projects/ecosystem stakeholders
n/a

### Describe the data being stored onto Filecoin
Project : theskyzone.net
 We are providing our customers with a cloud storage service.
 Our customers are using the service for work, personal work, and backup purposes.
 Cloud storage service provides services through various channels based on web browsers, folder synchronization of Windows and Mac PCs, and iOS and Android apps.

### Where was the data currently stored in this dataset sourced from
My own storage infra

### If you answered "Other" in the previous question, enter the details here
n/a

### If you are a data preparer, what is your location (City and Country)
n/a

### If you are a data preparer, how will the data be prepared? Please include tooling used and technical details?
n/a

### If you are not preparing the data, who will prepare the data?  (Provide name and business)
 FILDATA Co., Ltd.

### Has this dataset been stored on the Filecoin network before? If so, please explain and make the case why you would like to store this dataset again to the network. Provide details on preparation and/or SP distribution.
n/a

### Please share a sample of the data
theskyzone.net service demo
  You can use the service demo through the information below.
  URL : https://theskyzone.net
  Demo ID : demo
  Demo Password : demo17291729*

### Confirm that this is a public dataset that can be retrieved by anyone on the Network
Yes

### If you chose not to confirm, what was the reason
n/a

### What is the expected retrieval frequency for this data
Sporadic

### For how long do you plan to keep this dataset stored on Filecoin
2 to 3 years

### In which geographies do you plan on making storage deals
Asia other than Greater China

### How will you be distributing your data to storage providers
Shipping hard drives

### How do you plan to choose SP
Partners

### If you answered "Others" in the previous question, what is the tool or platform you plan to use
n/a

### If you already have a list of storage providers to work with, fill out their names and provider IDs below
provide ID, City, Country, Organization
f01115949, Seoul, Korea, GMI
f01900525, Seoul, Korea, GMI
f01770778, GyuyngGi, Korea, newclave
f01924824, GyuyngGi, Korea, newclave
f01924891, Seoul, Korea, TotalShift
f01927163, Seoul, Korea, TheAfter Co., Ltd.
f01784916, DaeGu, Korea, diasict Co., Ltd
f01340400, Asan, Korea, diasict Co., Ltd
f01310053, Asan, Korea, diasict Co., Ltd
f01987994, Seoul, Korea, VOGO Digital Labs

### How do you plan to make deals to your storage providers
Others/custom tool

### If you answered "Others/custom tool" in the previous question, enter the details here
filswan client

### Can you confirm that you will follow the Fil+ guideline
Yes

_Application created via [filplus.storage](https://filplus.storage)_

**Comment by fildata** [comment]
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/311

No one has reviewed the above application for so long, I had no way to contact them, so I re-applied to get in touch.
Someone please check the above application, and you can close this application.

thanks.

**Comment by fildata** [comment]
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/311

Hello. 
No one has reviewed the above application for so long, and I have no way to contact the notary, 
so I am applying this again.

I would appreciate it if someone could review the above application. 
If so, you can close this application.

thanks.

**Comment by kevzak** [comment]
@fildata I can work with you on this application. The Fil+ program is transitioning this month into new allocator pathways. 

Since this is a private dataset, I'd advise you to apply via my allocator, [the Enterprise Data Pathway](https://github.com/fidlabs/Enterprise-Data-Pathway)

**Comment by kevzak** [comment]
How big is the dataset? 20GiB?

**Comment by kevzak** [comment]
Which of these SPs are your organization's SP nodes?
provide ID, City, Country, Organization
f01115949, Seoul, Korea, GMI
f01900525, Seoul, Korea, GMI
f01770778, GyuyngGi, Korea, newclave
f01924824, GyuyngGi, Korea, newclave
f01924891, Seoul, Korea, TotalShift
f01927163, Seoul, Korea, TheAfter Co., Ltd.
f01784916, DaeGu, Korea, diasict Co., Ltd
f01340400, Asan, Korea, diasict Co., Ltd
f01310053, Asan, Korea, diasict Co., Ltd
f01987994, Seoul, Korea, VOGO Digital Labs

**Comment by fildata** [comment]
> 데이터 세트의 크기는 얼마나 됩니까? 20Gb?



> How big is the dataset? 20GiB?

17~20Gib

**Comment by fildata** [comment]
> How big is the dataset? 20GiB?

Thanks @kevzak 
Data size is between 17 and 20 GiB per file.

**Comment by fildata** [comment]
> Which of these SPs are your organization's SP nodes? provide ID, City, Country, Organization f01115949, Seoul, Korea, GMI f01900525, Seoul, Korea, GMI f01770778, GyuyngGi, Korea, newclave f01924824, GyuyngGi, Korea, newclave f01924891, Seoul, Korea, TotalShift f01927163, Seoul, Korea, TheAfter Co., Ltd. f01784916, DaeGu, Korea, diasict Co., Ltd f01340400, Asan, Korea, diasict Co., Ltd f01310053, Asan, Korea, diasict Co., Ltd f01987994, Seoul, Korea, VOGO Digital Labs

@kevzak 
We are not a SP, we are a data provider.
Those SPs are the Korean SP Association (cooperative). They want to store our data, so we give our data to them.

**Comment by fildata** [comment]
> @fildata I can work with you on this application. The Fil+ program is transitioning this month into new allocator pathways.
> 
> Since this is a private dataset, I'd advise you to apply via my allocator, [the Enterprise Data Pathway](https://github.com/fidlabs/Enterprise-Data-Pathway)
> 
> I'll have more details in 1-2 weeks

@kevzak

Hi... @kevzak  We opened new issue. Check Plz..
https://github.com/fidlabs/Enterprise-Data-Pathway/issues/22

**Comment by fildata** [comment]
Hi @kevzak
We opened new application for 'Enterprise-Data-Pathway'
https://github.com/fidlabs/Enterprise-Data-Pathway/issues/22

**Comment by data-programs** [comment]
<img width="32" alt="KYC" Verified src="https://stable.filplus.storage/images/filplus-kyc-verified-badge.png"/>

This user’s identity has been verified through [filplus.storage](https://filplus.storage)
