### ISSUE TITLE
[DataCap Application] <DATADAO> - <NOAA-HRRR>

### ISSUE THREAD

**Issue by yse88483** [filecoin-project/filecoin-plus-large-datasets#2327]
### Data Owner Name

NOAA-HRRR

### What is your role related to the dataset

Data Preparer

### Data Owner Country/Region

United States

### Data Owner Industry

Environment

### Website

https://registry.opendata.aws/

### Social Media

```text
https://registry.opendata.aws/
```

### Total amount of DataCap being requested

12PiB

### Expected size of single dataset (one copy)

2PiB

### Number of replicas to store

6

### Weekly allocation of DataCap requested

1PiB

### On-chain address for first allocation

f1snhspx7pphhlr5i4ent6d7k66nz2sfkosmutbwy

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
The Registry of Open Data on AWS is now available on AWS Data Exchange
All datasets on the Registry of Open Data are now discoverable on AWS Data Exchange alongside 3,000+ existing data products from category-leading data providers across industries. Explore the catalog to find open, free, and commercial data sets. Learn more about AWS Data Exchange
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### If answered yes, what are the other projects/ecosystem stakeholders

```text
There are no other stakeholders
```

### Describe the data being stored onto Filecoin

```text
The Registry of Open Data on AWS is now available on AWS Data Exchange
All datasets on the Registry of Open Data are now discoverable on AWS Data Exchange alongside 3,000+ existing data products from category-leading data providers across industries. Explore the catalog to find open, free, and commercial data sets. Learn more about AWS Data Exchange
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### If you are a data preparer. What is your location (Country/Region)

United States

### Please share a sample of the data

```text
357-resule 
2020-08-25 17:22:47  398.4 MiB hrrr_v2.20160823/conus/hrrr.t09z.wrfprsf13.grib2
2020-08-25 17:22:52  396.0 MiB hrrr_v2.20160823/conus/hrrr.t09z.wrfprsf14.grib2
2020-08-25 17:22:52  394.6 MiB hrrr_v2.20160823/conus/hrrr.t09z.wrfprsf15.grib2
2020-08-25 17:22:52  390.2 MiB hrrr_v2.20160823/conus/hrrr.t09z.wrfprsf16.grib2
2020-08-25 17:23:08  387.1 MiB hrrr_v2.20160823/conus/hrrr.t09z.wrfprsf17.grib2
2020-08-25 17:23:05  384.8 MiB hrrr_v2.20160823/conus/hrrr.t09z.wrfprsf18.grib2
2021-09-28 03:48:22   31.6 KiB index.html

Total Objects: 43282174
   Total Size: 2.1 PiB
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

1.5 to 2 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, Europe

### How will you be distributing your data to storage providers

HTTP or FTP server, IPFS, Shipping hard drives, Lotus built-in data transfer

### How do you plan to choose storage providers

Slack, Filmine

### How do you plan to make deals to your storage providers

Boost client, Lotus client, Bidbot

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by yse88483** [comment]
f01992032
f01992563
f01996719
f01996817
f02812304
f02320270

**Comment by yse88483** [comment]
f02850067 | [ninadaidata@gmail.com](mailto:ninadaidata@gmail.com) | datastone | Hong Kong
f01992563|ksjhsux888@gmail.com| SAcloud | china
f01996719|ksjhsux888@gmail.com | SAcloud | china
f01996817|ksjhsux888@gmail.com | SAcloud |china
f02812304 | [ndlabsipollo@gmail.com](mailto:ndlabsipollo@gmail.com) | SY-Tech | Singapore |
f02320270 | [ukvsusv@gmail.com](mailto:ukvsusv@gmail.com) | R1 | US

**Comment by yse88483** [comment]
<img width="791" alt="WX20240229-175336@2x" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/161669187/fec52ffc-1012-43a3-ab5c-86378b46fd48">

**Comment by yse88483** [comment]
We submitted the form and hope to see more progress, thank you.

**Comment by Sunnyiscoming** [comment]
SP List provided:
[{"providerID":"f02850067","City":"HongKong","Country":"china","SPOrg","datastone"},
{"providerID":"f01992563","City":"XYZ","Country":"china","SPOrg","SAcloud"},
{"providerID":"f01996719","City":"XYZ","Country":"china","SPOrg","SAcloud"},
{"providerID":"f01996817","City":"XYZ","Country":"china","SPOrg","SAcloud"},
{"providerID":"f02812304","City":"XYZ","Country":"Singapore","SPOrg","SY-Tech"},
{"providerID":"f02320270","City":"XYZ","Country":"US","SPOrg","R1"},]

**Comment by yse88483** [comment]
Hi, dear, we have modified the form:

Total amount of DataCap being requested
12PiB

Expected size of single dataset (one copy)
2PiB

Number of replicas to store
6

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
>12 PiB

**Expected weekly DataCap usage rate**
>1 PiB

**Client address**
>f1snhspx7pphhlr5i4ent6d7k66nz2sfkosmutbwy

**Comment by yse88483** [comment]
Considering that v3.1 has no quota, it is temporarily closed.
