### ISSUE TITLE
[DataCap Application] web3eye.io

### ISSUE THREAD

**Issue by kikakkz** [filecoin-project/filecoin-plus-large-datasets#2328]
### Data Owner Name

web3eye.io

### What is your role related to the dataset

Dataset Owner

### Data Owner Country/Region

Singapore

### Data Owner Industry

Web3 / Crypto

### Website

https://testnet.web3eye.io

### Social Media

```text
@web3_eye
```

### Total amount of DataCap being requested

1PiB

### Expected size of single dataset (one copy)

1PiB

### Number of replicas to store

3

### Weekly allocation of DataCap requested

50TiB

### On-chain address for first allocation

f1pvixpahnuxfjp73ojo43oax5asoopobyqu4hmea

### Data Type of Application

Public, Open Commercial/Enterprise

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Currently in the world of NFT, many methods for obtaining information about blockchain are complex and difficult for users to use, making it difficult for the public to obtain information.
Furthermore, various blockchain project data is in a fragmented state currently, making it even more difficult to obtain or organize information. Web3Eye is a search engine that aggregates historical NFT transaction records, and provides multi-chain aggregation search for NFT assets.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
Due to so many NFTs are stored in IPFS, or central server, sometimes when we view the exist NFT, we get error for the missed data. we think of it's valuable to make snapshot for those data. So in web3eye.io's engine, we parse the NFT history, generate snapshot for them, then store to Filecoin. When user search the data, and we know its original data is missed, then we'll recover from Filecoin for user, and let user know its original source is lost.
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### If you are a data preparer. What is your location (Country/Region)

Singapore

### If you are a data preparer, how will the data be prepared? Please include tooling used and technical details?

```text
After generate the snapshot by our cross-chain meta engine, the data will be cut into disks through Singularity, and then the hard disk is mailed to the SPs.
We also provide online method to fetch the data from our data source. If one of the copy is stored successfully, the original snapshot will be removed from the source.
We also implement a car generating tool to generate car file, then send to preset miners online.
```

### Has this dataset been stored on the Filecoin network before? If so, please explain and make the case why you would like to store this dataset again to the network. Provide details on preparation and/or SP distribution.

```text
No.
```

### Please share a sample of the data

```text
# Tarball with a bunch of NFT data
-rw-rw-r-- 1 coast coast 2148532224  3月  6 13:04 fdd65bf6-db76-11ee-8b8f-e7daf58958d9.tar.gz
-rw-rw-r-- 1 coast coast 2148532224  3月  6 13:04 fdd6b2f4-db76-11ee-932f-b7e26d86e3b0.tar.gz
-rw-rw-r-- 1 coast coast 2148532224  3月  6 13:04 fdd70a56-db76-11ee-b873-476f4f5f23c0.tar.gz
-rw-rw-r-- 1 coast coast 2148532224  3月  6 13:04 fdd76366-db76-11ee-8b14-93209f72bdaa.tar.gz
-rw-rw-r-- 1 coast coast 2148532224  3月  6 13:04 fdd7c8ce-db76-11ee-9968-b73681ea7bfb.tar.gz
-rw-rw-r-- 1 coast coast 2148532224  3月  6 13:04 fdd8401a-db76-11ee-94a6-bb3bcf1b70ec.tar.gz
-rw-rw-r-- 1 coast coast 2148532224  3月  6 13:04 fdd8c2f6-db76-11ee-a1aa-7f7632305de8.tar.gz
-rw-rw-r-- 1 coast coast 2148532224  3月  6 13:04 fdd93b6e-db76-11ee-97f6-dbd9d8c0e1f5.tar.gz
-rw-rw-r-- 1 coast coast 2148532224  3月  6 13:04 fdd99cd0-db76-11ee-95ff-ebf3bb4da26a.tar.gz
-rw-rw-r-- 1 coast coast 2148532224  3月  6 13:04 fdda004e-db76-11ee-8034-8b110be82bb3.tar.gz

# Car file generated with above tarball
-rw-rw-r-- 1 coast coast 113246208  3月  6 13:04 fdd65bf6-db76-11ee-8b8f-e7daf58958d9.car
-rw-rw-r-- 1 coast coast 113246208  3月  6 13:04 fdd6b2f4-db76-11ee-932f-b7e26d86e3b0.car
-rw-rw-r-- 1 coast coast 113246208  3月  6 13:04 fdd70a56-db76-11ee-b873-476f4f5f23c0.car
-rw-rw-r-- 1 coast coast 113246208  3月  6 13:04 fdd76366-db76-11ee-8b14-93209f72bdaa.car
-rw-rw-r-- 1 coast coast 113246208  3月  6 13:04 fdd7c8ce-db76-11ee-9968-b73681ea7bfb.car
-rw-rw-r-- 1 coast coast 113246208  3月  6 13:04 fdd8401a-db76-11ee-94a6-bb3bcf1b70ec.car
-rw-rw-r-- 1 coast coast 113246208  3月  6 13:04 fdd8c2f6-db76-11ee-a1aa-7f7632305de8.car
-rw-rw-r-- 1 coast coast 113246208  3月  6 13:04 fdd93b6e-db76-11ee-97f6-dbd9d8c0e1f5.car
-rw-rw-r-- 1 coast coast 113246208  3月  6 13:04 fdd99cd0-db76-11ee-95ff-ebf3bb4da26a.car
-rw-rw-r-- 1 coast coast 113246208  3月  6 13:04 fdda004e-db76-11ee-8034-8b110be82bb3.car

# Original NFT data
-rw-rw-r-- 1 coast coast     72586  2月 24  2023 1000.webp
-rw-rw-r-- 1 coast coast    359239  9月 12 12:02 1109.png
-rw-rw-r-- 1 coast coast    375057  6月 18  2023 1_front.png
-rw-rw-r-- 1 coast coast   1417554  8月  7  2023 22_3.png
-rw-rw-r-- 1 coast coast     78969  8月 11  2023 4b560f2f-934c-43dc-9021-6f4d62fec19e
-rw-rw-r-- 1 coast coast     18252  6月 18  2023 613.png
-rw-rw-r-- 1 coast coast     22102  6月 18  2023 617.png
-rw-rw-r-- 1 coast coast   5081267  6月 18  2023 788.png
-rw-rw-r-- 1 coast coast    110899  2月 20  2023 8ce3abd5936a2ad5ffc03a27114eeb26.avif
-rw-rw-r-- 1 coast coast    803970  8月 21  2023 917590f0c295682acc5aa07f65d219db54b964d8.png
-rw-rw-r-- 1 coast coast   1413857  6月 18  2023 99.png
-rw-rw-r-- 1 coast coast    226886  8月 17  2023 body-7a-eyes-32b-clothes-80f-hairs-21e-earrings-21a.webp
-rw-rw-r-- 1 coast coast 209715200  3月  6 11:41 data.bin
-rw-rw-r-- 1 coast coast   1413857  6月 18  2023 eee.png
-rw-rw-r-- 1 coast coast     94281  6月 18  2023 he.jpeg
-rw-rw-r-- 1 coast coast  13306505  8月 17  2023 LiNHX_TiexGO0DRC4rUl3Fa9oH74Ny9vY_MYmbPWRoY.jpeg
-rw-rw-r-- 1 coast coast      7164  6月 18  2023 nn.jpeg
-rw-rw-r-- 1 coast coast    762051  9月 21 08:57 QmaMG7ygHJiXizKBwdddyKnPBBdRiYX5yac9uuQaBqB7mj.png
-rw-rw-r-- 1 coast coast   2706728  9月 15 16:37 QmXsX73NjzMKz62ukADqGGxAYcGdamrwUutWiFUp6JqR8Q.png
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Daily

### For how long do you plan to keep this dataset stored on Filecoin

More than 3 years

### In which geographies do you plan on making storage deals

Asia other than Greater China

### How will you be distributing your data to storage providers

Shipping hard drives

### How do you plan to choose storage providers

Partners

### If you already have a list of storage providers to work with, fill out their names and provider IDs below

```text
| MinerID | Entity | City | Continent |
| --------- | ---------- | ---------- | --------- |
| f01970622 | Padeng  | HongKong | Asia |
| TBD(Our New Miner)   | web3eye.io | HongKong | Asia |
| f01146045   | Tianzhi | Singapore | Asia |
| f0832131  | Beishou | YangZhou,CN | Asia |
```

### How do you plan to make deals to your storage providers

Boost client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
SP List provided:
[{"providerID":"f01970622","City":"HongKong","Country":"CN","SPOrg","Padeng"},
{"providerID":"XYZ","City":"HongKong","Country":"CN","SPOrg","web3eye.io"},
{"providerID":"f01146045","City":"XYZ","Country":"Singapore","SPOrg","Tianzhi"},
{"providerID":"f0832131","City":"YangZhou","Country":"CN","SPOrg","Beishou"},]

**Comment by Sunnyiscoming** [comment]
Hello, per the https://github.com/filecoin-project/notary-governance/issues/922 for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

This information will be reviewed by Fil+ Governance team to confirm validity and then the application will be allowed to move forward for additional notary review.

**Comment by kikakkz** [comment]
> Hello, per the [filecoin-project/notary-governance#922](https://github.com/filecoin-project/notary-governance/issues/922) for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.
> 
> This information will be reviewed by Fil+ Governance team to confirm validity and then the application will be allowed to move forward for additional notary review.

I got this error. Could you please give me a right link ?
![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/13128505/686b0d77-63e8-4351-9358-356401eb6e95)

**Comment by kevzak** [comment]
@kikakkz this pathway is no longer active. You can follow up with your application in the Open Public Dataset pathway here: https://github.com/fidlabs/Open-Data-Pathway/issues/6

**Comment by data-programs** [comment]
<img width="32" alt="KYC" Verified src="https://stable.filplus.storage/images/filplus-kyc-verified-badge.png"/>

This user’s identity has been verified through [filplus.storage](https://filplus.storage)
