### ISSUE TITLE
[DataCap Application] Online Fashion/ Clothes Shopping Platform 

### ISSUE THREAD

**Issue by maytheforthbewithyou** [filecoin-project/filecoin-plus-large-datasets#233]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: ClicknFunny
- Website / Social Media: www.clicknfunny.com
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100TiB
- On-chain address for first allocation: f3qa7gg4v7xq3on2v7pi7l2fqf32zz7cnxdpjp3hvpzv2653ngj2cawzqohyqsujp4zfqvifhriwzqbi2w3p6q 

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
We're one of the biggest fashion/ clothes shopping platforms in Asia scaling up for the next level hoping to become a unicorn company in the future.
```

What is the primary source of funding for this project?
```
Funding from within/out.
```

What other projects/ecosystem stakeholders is this project associated with?
```
Our current and prospective clients.
```

## Use-case details

Describe the data being stored onto Filecoin
```
Fashion and model images and video descriptions of each item we sell.
```

Where was the data in this dataset sourced from?
```
Asia
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://www.youtube.com/watch?v=Mx4IoBd-8pU
https://www.clicknfunny.com/board/board.html?code=smblue111_image2&type=v&num1=999723&num2=00000&lock=
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes, I do confirm the above.
```

What is the expected retrieval frequency for this data?
```
Won't be very often.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
At least 5 years
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Asia would be good.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
We'd prefer online process.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We've been connected to strategic partners through recommended communities.
```

How will you be distributing deals across storage providers?
```
Equally
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
We're fully funded.
```

**Comment by maytheforthbewithyou** [comment]
Hi, I was wondering what's next for this request.

**Comment by galen-mcandrew** [comment]
Hi @maytheforthbewithyou Can you email [filplus@fil.org](mailto:filplus@fil.org) with your official work email so we can share this with notaries as a form of proof that you represent this organization?

**Comment by galen-mcandrew** [comment]
Closing this for now from no reply. When ready, please reopen or submit a new request here: https://plus.fil.org/ldn-application
