### ISSUE TITLE
[DataCap Application] <K12 International Education Platform> - <datastorage>

### ISSUE THREAD

**Issue by 1613557499** [filecoin-project/filecoin-plus-large-datasets#2332]
### Data Owner Name

K12 International Education Platform

### What is your role related to the dataset

Dataset Owner

### Data Owner Country/Region

China

### Data Owner Industry

Education & Training

### Website

http://www.topschools.cn/index?_l=en

### Social Media

```text
http://www.topschools.cn/index?_l=en
```

### Total amount of DataCap being requested

10PiB

### Expected size of single dataset (one copy)

1PiB

### Number of replicas to store

10

### Weekly allocation of DataCap requested

1PiB

### On-chain address for first allocation

f16xgqbyk4fonenyxqfgik3qf2odr73ws7rqnisca

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
TopSchools was founded on August 28, 2016.  As the resource aggregation platform of K12 international Education, TopSchools is committed to supporting the sustainable development of the international school market through community communication, data research, teacher training and talent recruitment.  Topschools is a close partner of international schools and international education institutions.  Provides industry with information on international education policies, operations, investments, schools, and people.  Organized various online and offline activities, cooperated with various examination bureaus, global top universities, research institutions, embassies and consulates, and provided services and support for more than 600 schools across the country;  We are linked to thousands of quality school service providers around the world to provide a variety of solutions for schools.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
Our data is very large, mainly stored all kinds of courses of teaching videos, materials, documents.
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### If you are a data preparer. What is your location (Country/Region)

China

### If you are a data preparer, how will the data be prepared? Please include tooling used and technical details?

```text
We plan to cooperate and negotiate with professionals to ensure the safety and reliability of data, and achieve short-term or long-term effective storage to ensure the integrity of data
```

### Has this dataset been stored on the Filecoin network before? If so, please explain and make the case why you would like to store this dataset again to the network. Provide details on preparation and/or SP distribution.

```text
We have previously applied for 1p data, that data is only a small part of our total data, the company's development is stable, our data is always growing, storage costs are also increasing, the need for filecoin network support, for the development of the traditional Internet industry to promote.
```

### Please share a sample of the data

```text
https://pan.baidu.com/s/1vOQ-h6lCCLvCXAY_PtsP1A?pwd=6jt9 
https://pan.baidu.com/s/1CbRHk1E-tiXULoJIgLawMw?pwd=iapx 
https://pan.baidu.com/s/1_qSCseiHfUPyXFumfgvsLQ?pwd=fgis
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Monthly

### For how long do you plan to keep this dataset stored on Filecoin

Permanently

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, Europe, Australia (continent)

### How will you be distributing your data to storage providers

Cloud storage (i.e. S3), HTTP or FTP server, IPFS, Lotus built-in data transfer

### How do you plan to choose storage providers

Slack, Filmine, Big Data Exchange, Partners

### If you already have a list of storage providers to work with, fill out their names and provider IDs below

```text
f02850067 | ninadaidata@gmail.com | datastone | Hong Kong
f02812304 | ndlabsipollo@gmail.com | SY-Tech | Singapore |
f02363305 |miasun829@gmail.com| Guangdong
f02320270 | ukvsusv@gmail.com | R1 | US
```

### How do you plan to make deals to your storage providers

Boost client, Lotus client, Droplet client, Bidbot, Singularity

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by psh0691** [comment]
@1613557499 
This LDN is no longer in progress.
You now have to apply to each DC allocator (formerly notary).

This is my DC allocator site. Please apply here and I'll help you.
https://github.com/Blockchain-World-News/FIL-DC-Allocator/issues

**Comment by data-programs** [comment]
<img width="32" alt="KYC" Verified src="https://stable.filplus.storage/images/filplus-kyc-verified-badge.png"/>

This user’s identity has been verified through [filplus.storage](https://filplus.storage)
