### ISSUE TITLE
[DataCap Application]  - Jiangsu Jubei Technology Co., Ltd

### ISSUE THREAD

**Issue by tianzyt** [filecoin-project/filecoin-plus-large-datasets#2336]
### Data Owner Name

Analytic and Translational Genetics Unit, Massachusetts General Hospital and the Broad Institute

### What is your role related to the dataset

Data Preparer

### Data Owner Country/Region

China

### Data Owner Industry

Life Science / Healthcare

### Website

https://pan.ukbb.broadinstitute.org/

### Social Media

```text
http://www.filtakes.com
```

### Total amount of DataCap being requested

5PiB

### Expected size of single dataset (one copy)

150tb

### Number of replicas to store

10

### Weekly allocation of DataCap requested

150TiB

### On-chain address for first allocation

f3qqybcknthb767wlifd4xt3wwashbiao6bfbq42sx2ay3watwox3cqpihi6pdaq2r32r4qljf6igu5msf3ifa

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [X] Use Custom Multisig

### Share a brief history of your project and organization

```text
Founded in 2021, filtakes is a technology company focusing on distributed storage technology, data computing and intelligent AI. We provide data storage and technical support services to various companies and have complete industry solutions.
 
We provide customers with technical services such as data collection and download, data storage, and big data model training to help customers gain deep insights from data and promote business decision-making and innovation.
```

### Is this project associated with other projects/ecosystem stakeholders?

Yes

### Describe the data being stored onto Filecoin

```text
UK Biobank Pan-Ancestry Summary Statistics
National Cancer Institute Imaging Data Commons (IDC) Collections
NASA Space Biology Open Science Data Repository (OSDR)
New Zealand Imagery
Indiana Statewide Digital Aerial Imagery Catalog
Downscaled Climate Data for Alaska
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### If you are a data preparer. What is your location (Country/Region)

China

### Please share a sample of the data

```text
https://registry.opendata.aws/broad-pan-ukb/
aws s3 ls --no-sign-request --recursive --human-readable --summarize s3://pan-ukb-us-east-1/
Total Size: 143.5 TiB

https://registry.opendata.aws/nci-imaging-data-commons/
aws s3 ls --no-sign-request --recursive --human-readable --summarize s3://idc-open-data/
Total Size: 61.3 TiB

https://registry.opendata.aws/nasa-osdr/
aws s3 ls --no-sign-request --recursive --human-readable --summarize s3://nasa-osdr/
Total Size: 133.3 TiB

https://registry.opendata.aws/nz-imagery/
aws s3 ls --no-sign-request --recursive --human-readable --summarize s3://nz-imagery/
Total Size: 18 TiB

https://registry.opendata.aws/in-imagery/
aws s3 ls --no-sign-request --recursive --human-readable --summarize s3://gisimageryingov/
Total Size: 72.9 TiB

https://registry.opendata.aws/wrf-alaska-snap/
aws s3 ls --no-sign-request --recursive --human-readable --summarize s3://wrf-ak-ar5/
Total Size: 79.9 TiB
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

1.5 to 2 years

### In which geographies do you plan on making storage deals

Greater China

### How will you be distributing your data to storage providers

HTTP or FTP server

### How do you plan to choose storage providers

Slack

### If you already have a list of storage providers to work with, fill out their names and provider IDs below

f01930832

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by data-programs** [comment]
<img width="32" alt="KYC" Verified src="https://stable.filplus.storage/images/filplus-kyc-verified-badge.png"/>

This user’s identity has been verified through [filplus.storage](https://filplus.storage)
