### ISSUE TITLE
[DataCap Application] Woodworking Shop (DIY, License Programs)

### ISSUE THREAD

**Issue by whynotcloud** [filecoin-project/filecoin-plus-large-datasets#234]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Woodmakers
- Website / Social Media: http://woodmakers.kr/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100TiB
- On-chain address for first allocation: f3urigga4xhoya7ijhoe7b6hi2lby2hkenl2ssczuirg5kyv2a7vululjvu3snilb4xvk4zxwag3bactl6cs6a

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
We've been running a woodworking shop and training programs for individuals who seek carpentry licenses or carpentry as leisure activities.
```

What is the primary source of funding for this project?
```
Mainly from us and our peers.
```

What other projects/ecosystem stakeholders is this project associated with?
```
Peer organizations
```

## Use-case details

Describe the data being stored onto Filecoin
```
Long/short video clips of Carpentry 101 tutorials and DIY Projects.
```

Where was the data in this dataset sourced from?
```
Asia
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
http://woodmakers.kr
https://www.youtube.com/watch?v=4YoASyLgKQM
https://www.youtube.com/watch?v=AGQPhyB-UPs

```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes it can be retrieved with no specific permissions.
```

What is the expected retrieval frequency for this data?
```
Once a year.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
Permanantly
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Asia
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Both are possible.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
Based on peer recommendations
```

How will you be distributing deals across storage providers?
```
Equally
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
We do have enough funds.
```

**Comment by whynotcloud** [comment]
> **Thanks for your request!** Everything looks **good**. 👌
> 
> A Governance Team member will review the information provided and contact you back pretty soon.

I'd appreciate if you'd let me know about this at your earliest convenience. Thanks ;)

**Comment by Sunnyiscoming** [comment]
@whynotcloud 
1. Please clarify the relationship between the two data samples provided and the application subject, and whether the data storage permission is obtained.  
2. Please provide more information to prove that the applicant has 5PB of data.

**Comment by Sunnyiscoming** [comment]
Hello @whynotcloud
Is this application available?

**Comment by galen-mcandrew** [comment]
Closing this for now from no reply. When ready, please reopen or submit a new request here: https://plus.fil.org/ldn-application
