### ISSUE TITLE
[DataCap Application] Chengdu Shuguang Yitong Information Technology Service Co., Ltd

### ISSUE THREAD

**Issue by Cclarm** [filecoin-project/filecoin-plus-large-datasets#2341]
### Data Owner Name
Chengdu Shuguang Yitong Information Technology Service Co., Ltd

### What is your role related to the dataset
Dataset Owner

### Data Owner Country/Region
China

### Data Owner Industry
Education & Training

### Website
[http://gpuclub.cn/#/home](http://gpuclub.cn/#/home)

### Social Media
[at]xyc510923 (Twitter)

### Total amount of DataCap being requested
4 PiB

### Expected size of single dataset (one copy)
100 TiB

### Number of replicas to store
1

### Weekly allocation of DataCap requested
500 TiB

### On-chain address for first allocation
f1naxsgeu7gipmkbopsbof6y7cs6m7oqk4noraoka

### Data Type of Application
Private Commercial/Enterprise

### Custom multisig
- [x] Use Custom Multisig

### Identifier
efil

### Share a brief history of your project and organization

2019226599655052,002.0791510100MA63DEM189AIGC20232.252

1. 82000PB
2. GPUGPU2GPUGPU2600GPUGPUAIGC
3. AIGCGPUAIGC
4. ITITT3+IDCT3+2ITIDCIDC

20ITAIGC

### Is this project associated with other projects/ecosystem stakeholders?
Yes

### If answered yes, what are the other projects/ecosystem stakeholders
Students and teachers and AI training companies

### Describe the data being stored onto Filecoin
 Public datasets
AI container images

### Where was the data currently stored in this dataset sourced from
My own storage infra

### If you answered "Other" in the previous question, enter the details here
n/a

### If you are a data preparer, what is your location (City and Country)
n/a

### If you are a data preparer, how will the data be prepared? Please include tooling used and technical details?
n/a

### If you are not preparing the data, who will prepare the data?  (Provide name and business)
Students and teachers and AI training companies

### Has this dataset been stored on the Filecoin network before? If so, please explain and make the case why you would like to store this dataset again to the network. Provide details on preparation and/or SP distribution.
n/a

### Please share a sample of the data
http://183.222.164.253:40071/api/public/dl/eMBiyZ53/sugon/ubuntu-22.04.3-live-server-amd64.iso

### Confirm that this is a public dataset that can be retrieved by anyone on the Network
No

### If you chose not to confirm, what was the reason
Private data

### What is the expected retrieval frequency for this data
Daily

### For how long do you plan to keep this dataset stored on Filecoin
More than 3 years

### In which geographies do you plan on making storage deals
Greater China

### How will you be distributing your data to storage providers
IPFS

### How do you plan to choose SP
Big Data Exchange

### If you answered "Others" in the previous question, what is the tool or platform you plan to use
n/a

### If you already have a list of storage providers to work with, fill out their names and provider IDs below
n/a

### How do you plan to make deals to your storage providers
Droplet client

### If you answered "Others/custom tool" in the previous question, enter the details here
n/a

### Can you confirm that you will follow the Fil+ guideline
Yes

_Application created via [filplus.storage](https://filplus.storage)_

**Comment by data-programs** [comment]
This application is requesting DataCap for a **private** dataset, so it's labeled `efil+`

**Comment by kevzak** [comment]
Hello @Cclarm E-Fil+ pathway was closed back in early 2024. There are now allocator pathways available, of which, there is an Enterprise pathway. You can apply here if you like: https://github.com/fidlabs/Enterprise-Data-Pathway/issues/new/choose

Please read guidelines first to ensure you meet requirements: https://github.com/fidlabs/Enterprise-Data-Pathway/blob/main/README.md
