### ISSUE TITLE
[DataCap Application] Theatre Down-In

### ISSUE THREAD

**Issue by Down-E** [filecoin-project/filecoin-plus-large-datasets#237]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Theatre Down-In
- Website / Social Media: https://theatredownin.modoo.at/?link=3kieywma 
https://www.youtube.com/channel/UCknsiIXQ2mWhCgrwhBEcwAQ 
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 3PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 60PiB
- On-chain address for first allocation: f3vdyypbsje2nasdjwraipppgm5wsmi6oz6dd3cyfecwcg2uc45cqlyk7bl5oezwla6as3x5q775yko65yueaa

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
The creative group Down In, which started as an amateur club in the summer of 2018 and continued workshop performances, and began full-fledged creative performance activities in the summer of 2019. Down's first creative play produced in 2019 was the musical "Gretel and Hansel," inspired by the painting brothers' fairy tale "Hansel and Gretel." Thanks to the interest and love of many audiences, our first creative play "Gretel and Hansel" was able to end successfully. Since then, Daun, our creative group, has been officially registered as a theater company as of 2020.
Creative group Down In. Through performing arts, we tell about various people's stories.
To find the true self by experiencing it, our theater company created. People from different fields and backgrounds.
"Just with the love for the stage." Gather together. Our Down In, who has been formed, is free to do creative activities.
```

What is the primary source of funding for this project?
```
 musical "Gretel and Hansel", "Traveling to the moon"
```

What other projects/ecosystem stakeholders is this project associated with?
```
Production Team, sometimes fund from gevernment's business, Theater
```

## Use-case details

Describe the data being stored onto Filecoin
```
Our Dance videos, Music videos, Youtube Channel Videos, Music files, and Musical Videos, etc. (Related to Musical, and performance)
```

Where was the data in this dataset sourced from?
```
Korea, republic of
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
Yes, you can see them in here www.youtube.com/channel/UCknsiIXQ2mWhCgrwhBEcwAQ 
![Travel to the moon](https://user-images.githubusercontent.com/98946446/152315565-0d86b2e3-ec44-42a7-93d4-edc83e193a28.JPG) 
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes, We are both creaters and actors. We do have all rights about all of our videos (music, actors portraits rights, script rights, etc)  
```

What is the expected retrieval frequency for this data?
```
Our musicals were highly popular in Seoul "Dream Theater". So I think many people would search for these datas. 
```

For how long do you plan to keep this dataset stored on Filecoin?
```
As long as I can. This is because we want to make permanant archive for us, "Theatre Down In"
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
If it is possible Korea, (or other asia), North America, Europe.  I want these 3 regions.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Offline data transfer would be possible. I am contacting technician who have Storage Provider through slack channel. 
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
Through Slack, fil-plus, fil-deal-market. Or any recommendation would be fine. 
I will contact with technician by offline and will have conversation about making offline deals and retrieve methods. 
```

How will you be distributing deals across storage providers?
```
For safety, I want to pick 5 or more storage providers to make a deal. 
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
I have one technician communicating with, if conversation goes smoothly I think I can make a deals ASAP. 
I think Filecoin would have public open entertaining data, which has no problem of copyrights.(Because we have all rights reserved with our data)  
```

**Comment by Sunnyiscoming** [comment]
Based on the information you have provided, it seems that the current production is not sufficient to support data size of  3PB DataCap. Please provide more information to prove that the applicant has 3PB of data.

**Comment by Sunnyiscoming** [comment]
Hello @Down-E 
Is this application available?

**Comment by galen-mcandrew** [comment]
Closing this for now from no reply. When ready, please reopen or submit a new request here: https://plus.fil.org/ldn-application
