### ISSUE TITLE
[DataCap Application] Roadwise

### ISSUE THREAD

**Issue by suneng** [filecoin-project/filecoin-plus-large-datasets#239]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Roadwise
- Website / Social Media: http://www.roadwise.co.kr/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 2PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100TiB
- On-chain address for first allocation: f3saku3z2mjghd2xsxhss3svwvc2ajehzvxz6onjosvapoduaztsgsqup6sdehrryuwk4xcujqhnt3hs7glnca

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Roadwise has developed a customized E-learning platform based on AI artificial intelligence and big data-based technologies to support real-time non-face-to-face classes. We are an edutech company with educational voice recognition system and automatic correction system technology.
```

What is the primary source of funding for this project?
```
The primary source of funding is our own.
```

What other projects/ecosystem stakeholders is this project associated with?
```
Except for our partner company, there isn't.
```

## Use-case details

Describe the data being stored onto Filecoin
```
We are going to save educational content.
```

Where was the data in this dataset sourced from?
```
We made the contents and our partner company shares their data too.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
![image](https://user-images.githubusercontent.com/99155216/152718149-0224ec21-b382-4874-b845-df6926776753.png)
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
We are going to upload the data everyone can see.
```

What is the expected retrieval frequency for this data?
```
I think people interested in English education will find a lot of our data. We want many English educators to see our materials.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
As long as possible, because we want to record the previous data so we can refer to it when creating new content.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
At first we are going to make storage deals in korea, and we will find the another global one after.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
We may use 2~3 SPs and we are planning to make offline data transfer process.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We plan to find a stable storage minor and use it continuously. As I said above, I am looking for a good SP in Korea at first.
```

How will you be distributing deals across storage providers?
```
We will use offline data transfer process.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
We are looking for a stable SP through the FileCoin community and are preparing to proceed with the contract as soon as the SP is determined. As we receive the Datacap, we try to start making deals as soon as possible.
```

**Comment by galen-mcandrew** [comment]
@suneng Can you email [filplus@fil.org](mailto:filplus@fil.org) with your official work email so we can share this with notaries as a form of proof that you represent this organization?
