### ISSUE TITLE
[DataCap Application] ATB FiL TV

### ISSUE THREAD

**Issue by abouttblock** [filecoin-project/filecoin-plus-large-datasets#240]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name:  ATB
- Website / Social Media: https://www.youtube.com/channel/UCFqqo_5n8y21z1cBunIPp9Q
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 1PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 20TiB
- On-chain address for first allocation: f3wurij2nsoyz4e56ztjmod5kzpz3xhhp2gx73ctx7pzkgznfwpkzu6kovgqlp7cwvnedzqkdw5lgch5katzoq

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
We were born in 2020.
We are a YouTube channel that deals with major news about FileCoin.
```

What is the primary source of funding for this project?
```
Start a business with loans and personal savings funds.
```

What other projects/ecosystem stakeholders is this project associated with?
```
We help attract new minors to the filecoin network by sharing information.
```

## Use-case details

Describe the data being stored onto Filecoin
```
We plan to store useful new videos and documents related to file coins in the future, as well as existing videos currently uploaded on YouTube.
```

Where was the data in this dataset sourced from?
```
Ownership of all stored data is all in our channel.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://youtu.be/_rlM-8s7_1M
https://youtu.be/wErczWkpEY8
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
YES!
```

What is the expected retrieval frequency for this data?
```
It is expected that people will use it more often than expected to acquire information on file coins and other coins.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
It plans to use it in the long run.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Only in South Korea
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Mainly online transaction!
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We plan to choose according to the minor's ability. I think we need a minor that can be with us for a long time.
```

How will you be distributing deals across storage providers?
```
It will benefit more where you are more capable.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes! I'll make sure to start right away.
```

**Comment by abouttblock** [comment]
> Please share your official certificate to prove your identity of your organization.

What are some types of documents for proof of organization? May I share your Korean corporate registration card or business card of the person in Korea?

**Comment by IPFSUnion** [comment]
Thank you for your diligence. Please provide your business registration certificate and any presentation documents related to your business.

**Comment by abouttblock** [comment]
> Thank you for your diligence. Please provide your business registration certificate and any presentation documents related to your business.

When the documents are ready, we will send them to the email registered on github.

**Comment by abouttblock** [comment]
> 



> Thank you for your diligence. Please provide your business registration certificate and any presentation documents related to your business.

I sent it to you by email. Please check. (tech@ipfsunion.cn)

**Comment by IPFSUnion** [comment]
Received and thanks. Does your main business include mining?

**Comment by abouttblock** [comment]
> Received and thanks. Does your main business include mining?

No, it doesn't include it. Our main business is to deliver information about FileCoin and ipfs and to maintain, repair, and operate apps and web.

**Comment by abouttblock** [comment]
Is there anything else I need to do?

**Comment by UnionLabs2020** [comment]
Your website, your mailbox with your official domain and your office address

**Comment by Sunnyiscoming** [comment]
@abouttblock 
As you said, you plan to store useful new videos and documents related to file coins in the future, as well as existing videos currently uploaded on YouTube.
There are only 52 videos on your youtube video, which can not support your request of 1 PiB DataCap.

**Comment by Sunnyiscoming** [comment]
Hello @abouttblock 
Is this application available?

**Comment by galen-mcandrew** [comment]
Closing this for now from no reply. When ready, please reopen or submit a new request here: https://plus.fil.org/ldn-application
