### ISSUE TITLE
[DataCap Application] Architecture Masterpiece

### ISSUE THREAD

**Issue by Kimyoonh** [filecoin-project/filecoin-plus-large-datasets#241]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Architecture Masterpiece
- Website / Social Media: http://www.mj-arc.com
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 1PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100TiB
- On-chain address for first allocation: f3ry4vqvpddvsf35si6mgbwmjsiott7becrg7kcbct462ugy6uao2plm355tgtkjan25iqcg3h7h5xszhfi54q

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
My company, The Masterpiece is not just about building, but I have faith that it is about developing the quality of life of our users.
To do this, the initial approach of the project is not only the budget and duration of the architecturalist. Research and analysis of important parts such as lifestyle and identity it starts by drawing ideas.
To realize the harmony of emotional value and production technology required by modern society, We bring emotional value to life through the latest digital design and production technology, In other words, we strive to provide a design that is implemented, not a picture. 
```

What is the primary source of funding for this project?
```
my clients, and my company itself 
```

What other projects/ecosystem stakeholders is this project associated with?
```
interior, furniture related company.
```

## Use-case details

Describe the data being stored onto Filecoin
```
Over 15 years, I've been designed and built numerous offices, residence facilities, factories, commercial buildings. All of those data is artistic and useful. So I want to store it permanently, and make it easy to retrieve. so that my customers can easily see my work, and share my ideas and design with many people. 
```

Where was the data in this dataset sourced from?
```
Korea, specially Sejong city
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
Yes.
![corporation_model](https://user-images.githubusercontent.com/99229514/152905683-187d44d3-38f4-41ed-824e-e27d2707f41b.jpg)
![comtree_modeling](https://user-images.githubusercontent.com/99229514/152905686-bdcdf035-1bc1-444c-a4df-5cc694b436a5.jpg)
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Ok, I confirmed. 
```

What is the expected retrieval frequency for this data?
```
I guess it would be fairly frequent, because my future clients will want to see these data and my peer company. 
Also, if anyone can see my design and built building I think it can be helpful for other people to design their home or workplace.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
If possible, permanently.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Korea, or near asia or europe(if possible to contact with them)
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
If I use Korean storage providers, I know some companies. Maybe possible to do offline data transfer process. 
I will distribute my data into 5~6 storage providers. To be safe in error or any problem. 
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
I am considering to choose one of Korea storage provider company, to retrieve data easily. 
And if possible I want to contact with European storage provider through Github or Slack. 
```

How will you be distributing deals across storage providers?
```
offline for Korea storage provider, online for foreign storage provider. 
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
I have about 1PiB of data that filmed numerous designed buildings (in 3D, and 4K) and modellinged CAD documents and virtual simulation files. So data is enough, and as soon as I recieve Datacap, I can directly go to one of Korea Storage Provider Company. 
```

**Comment by Sunnyiscoming** [comment]
@Kimyoonh 
Hi. The data samples is not enough to prove that there is already 1 PiB data. Can you provide more data samples?

**Comment by Sunnyiscoming** [comment]
Hello @Kimyoonh 
Is this application available?

**Comment by galen-mcandrew** [comment]
Closing this for now from no reply. When ready, please reopen or submit a new request here: https://plus.fil.org/ldn-application
