### ISSUE TITLE
Dynamic Acting School applying for LargeDataCap

### ISSUE THREAD

**Issue by extendedrealityinme** [filecoin-project/filecoin-plus-large-datasets#243]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Dynamic Acting School
- Website / Social Media: https://www.dynactors.com/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100 TiB
- On-chain address for first allocation: f3ryeyljt4ov3ym4kql2lrykgwsl3fentpxkzpyevikdtx7jypkmt4iwanfiau44hkrpgqwicicynl5g2uhe6q

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
We're teachers who prepare students for college entrance exam and audition for acting career.
We also keep records of every moment of our students' hard working and effort.
```

What is the primary source of funding for this project?
```
The project investment mainly comes from our angel investors.
```

What other projects/ecosystem stakeholders is this project associated with?
```
Peers
```

## Use-case details

Describe the data being stored onto Filecoin
```
Mainly acting record data, profile images and sample clips of acting
```

Where was the data in this dataset sourced from?
```
Uploaded from our staff and our students.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
Please refer the attached.
https://www.youtube.com/watch?v=oQSAcgn9uqM
https://www.youtube.com/watch?v=zCulftzcLcM
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Confirmed.
```

What is the expected retrieval frequency for this data?
```
The retrieval probability for now is not very high.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
We'd appreciate permanent storage as our institute's long-term record asset.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Asia
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
We'll transfer the data both on/offline.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
What we'd most consider are the following:
1. Capability in dealing with verified data.
2. Location (Asia)
```

How will you be distributing deals across storage providers?
```
We'll pursue fair distribution.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes.
```

**Comment by Sunnyiscoming** [comment]
@extendedrealityinme 
Please provide the relationship between the organization and the provided YouTube channel  
In addition to the YouTube channel videos, are there other data sources? Can you provide more data samples?

**Comment by Sunnyiscoming** [comment]
@extendedrealityinme Hi
Is this application available?

**Comment by galen-mcandrew** [comment]
Closing this for now from no reply. When ready, please reopen or submit a new request here: https://plus.fil.org/ldn-application
