### ISSUE TITLE
[DataCap Application] Junior Soccer School 

### ISSUE THREAD

**Issue by ipomaster** [filecoin-project/filecoin-plus-large-datasets#244]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Fever Soccer Academy
- Website / Social Media: https://fever-sports.com/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100TiB
- On-chain address for first allocation: f3rqw4miajyvdry6rrnnetgup5fnft2h4szixdz6rfscsbbol3e6n2sq4a5d5dz3y4atfazbbybmmhmiag66hq

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Founded in 2007, we've been providing sports lessons especially soccer to young generations. 
```

What is the primary source of funding for this project?
```
We're funded through donations and teaching services that we provide daily.
```

What other projects/ecosystem stakeholders is this project associated with?
```
Associated with our members and fellow sports organizations.
```

## Use-case details

Describe the data being stored onto Filecoin
```
Soccer lesson 101 tutorials, archives of each member
```

Where was the data in this dataset sourced from?
```
Social media accounts, our own data archives
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://www.youtube.com/watch?v=72-hzOIYbKQ
https://www.youtube.com/watch?v=WRsMawrWVHU
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes, it's for public usage.
```

What is the expected retrieval frequency for this data?
```
Upon requests.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
We're interested in long-term archival storage.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Asia would be preferred but we're also open to wider geographic distributions.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Online
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We're looking for miners with high reputation scores.
```

How will you be distributing deals across storage providers?
```
Evenly by chunking the data into pieces at first.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Funded by many sources
```

**Comment by ipomaster** [comment]
I'd like to hear updates on this if there's any. Thank you!

**Comment by Sunnyiscoming** [comment]
@ipomaster 
1.Can you provide more information or related reports link of your organization?
2.Please provide the relationship between the organization and the provided YouTube channel  
3.In addition to the YouTube channel videos, are there other data sources? Can you provide more data samples? Because you request 5 PB DataCap, and there are only 80 videos in the provided YouTube channel.

**Comment by Sunnyiscoming** [comment]
@ipomaster  Hi
Is this application available?

**Comment by galen-mcandrew** [comment]
Closing this for now from no reply. When ready, please reopen or submit a new request here: https://plus.fil.org/ldn-application
