### ISSUE TITLE
[DataCap Application] Video Game History Foundation

### ISSUE THREAD

**Issue by Caraae** [filecoin-project/filecoin-plus-large-datasets#247]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Video Game History Foundation
- Website / Social Media:https://gamehistory.org/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):400TiB
- On-chain address for first allocation:f1do6aznd2a3x6rxdmmy2fgxlsmc6t2nvge3hjqly

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
The Video Game History Foundation is a 501(c)3 non-profit organization dedicated to preserving, celebrating, and teaching the history of video games. Our archives provide rare material for study, and our advocacy and educational outreach bring everyone together to do their part in celebrating and discovering video game history.
```

What is the primary source of funding for this project?
```
Our funding is from our own account. We sell goods about our foundation.
```

What other projects/ecosystem stakeholders is this project associated with?
```
No other stakeholders.
```

## Use-case details

Describe the data being stored onto Filecoin
```
Source code about development tools and arts documents; Commodity information data; Materials about game informer.
```

Where was the data in this dataset sourced from?
```
From our collection.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
![Baseball_0102-1-1024x821](https://user-images.githubusercontent.com/98458763/153392407-a1474a4f-d248-45db-acaf-71fc7bf40acb.png)
![FK9bS_sVEAAgXla](https://user-images.githubusercontent.com/98458763/153394006-30c58146-930f-44a3-99ea-2b7e72e3d72f.jpg)
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
This is a public dataset.
```

What is the expected retrieval frequency for this data?
```
These data will be retrieved infrequenly and it will be twice per year.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
2 years.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Korea.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Actually, we usually use offline data transfer process, but we will change the process if they need online process.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
1.providers who have proper distance and price.
2.stable providers.
```

How will you be distributing deals across storage providers?
```
On the basis of their distance to allocate the percentage.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
We have.
```

**Comment by swatchliu** [comment]
How did you hear about the FIL+ program?

**Comment by dud1337** [comment]
I've reached out to info@gamehistory.org to confirm association.

**Comment by dud1337** [comment]
@Caraae the response was that this request was not associated with gamehistory.org
Do you wish to dispute that?

**Comment by swatchliu** [comment]
Could you please clarify your role?

**Comment by Caraae** [comment]
Dear @dud1337 and @swatchliu, I am one of business parnter of gamehisory.org. I have sent them a lot of vedio magazines which I collected in the past 20 years. I do have a PiB video games to store, and I will keep collecting it until my death. That's my Final Fantasy. I hope have your approval.

**Comment by Caraae** [comment]
Hi, @dud1337 I was entrusted with the issue's application. I have communicated with my clientele and he gave me a reply. My clientele will give up on this application if you insist on identity himself after he had internal chat with Kelsey.

**Comment by dud1337** [comment]
Hi @Caraae, we've reached out to info@gamehistory.org again to confirm if identifying themself would be an issue or not.

If the only evidence for your association, is a random GitHub account's (with no other activity other than this request) testimony, it is not sufficient.

**Comment by dud1337** [comment]
Closing this application due to repeated refutation by official source.
