### ISSUE TITLE
[DataCap Application]  CabrinaHuang - Slingshot Restore Program - 2nd

### ISSUE THREAD

**Issue by xingjitansuo** [filecoin-project/filecoin-plus-large-datasets#249]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: CabrinaHuang-Slingshot Restore Program
- Website / Social Media:: https://gnomad.broadinstitute.org/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 500TiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):  200TiB
- On-chain address for first allocation: f1c2nxtixkivuzmmezwawg4nwzoknvd7hto37cy4q
_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
The requested DataCap is for Slingshot Restore Program hosted by the Slingshot teams as shown in 
Restore Program Description: https://docs.google.com/document/d/1sGLkw321Fl09jvAr80kFY2FcQWa1H-dYpowXFRWo-OM/edit?usp=sharing.
I participated as the client under the name Cabrina Huang 
```

What is the primary source of funding for this project?
```
Slingshot Reward 

```

What other projects/ecosystem stakeholders is this project associated with?
```
Slingshot team
```

## Use-case details

Describe the data being stored onto Filecoin
```
The Genome Aggregation Database (gnomAD), is a coalition of investigators seeking to aggregate and harmonize exome and genome sequencing data from a variety of large-scale sequencing projects, and to make summary data available for the wider scientific community.  
This was previously onboarded in Slingshot by others.
 
```

Where was the data in this dataset sourced from?
```
Pubic Datasets at https://gnomad.broadinstitute.org/downloads

```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
Pubic Datasets at https://gnomad.broadinstitute.org/downloads

```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
yes
```

What is the expected retrieval frequency for this data?
```
Depends
```

For how long do you plan to keep this dataset stored on Filecoin?
```
>=500days
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
All around the world  

```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
offline deal
Distribute equally
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
Choose from eligible SP from Slingshot-Restore
```

How will you be distributing deals across storage providers?
```
distribute same data to SP from 2 continents, 3 countries and 5 cities. 

```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
yes
```

**Comment by xingjitansuo** [comment]
@galen-mcandrew  Thanks, and should I just wait for the creation of Multisig now?

**Comment by MegTei** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecq3zwza6apio5ip3tpnd2mi54se55cld662dr4gdoyrkht3fyavo 
#### Address 
> f1c2nxtixkivuzmmezwawg4nwzoknvd7hto37cy4q
#### Datacap Allocated
> 25.00TiB
#### Signer Address
> f1ystxl2ootvpirpa7ebgwl7vlhwkbx2r4zjxwe5i
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecq3zwza6apio5ip3tpnd2mi54se55cld662dr4gdoyrkht3fyavo

**Comment by neogeweb3** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedzl5nyodzvoof2kyu4qireowzndb6kehgpo5faifkynqwh5ajqfy 
#### Address 
> f1c2nxtixkivuzmmezwawg4nwzoknvd7hto37cy4q
#### Datacap Allocated
> 25.00TiB
#### Signer Address
> f13k5zr6ovc2gjmg3lvd43ladbydhovpylcvbflpa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedzl5nyodzvoof2kyu4qireowzndb6kehgpo5faifkynqwh5ajqfy

**Comment by Reiers** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedm3l47c6pquzs3z52yhjmnop7djjmxsl4xw72dnmeleqjrldlmqu 
#### Address 
> f1c2nxtixkivuzmmezwawg4nwzoknvd7hto37cy4q
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1oz43ckvmtxmmsfzqm6bpnemqlavz4ifyl524chq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedm3l47c6pquzs3z52yhjmnop7djjmxsl4xw72dnmeleqjrldlmqu

**Comment by flyworker** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceanahrrtgkta7dhkjpumnrt4wdahj7zoouiyfjneyn43t6ithobue 
#### Address 
> f1c2nxtixkivuzmmezwawg4nwzoknvd7hto37cy4q
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1hlubjsdkv4wmsdadihloxgwrz3j3ernf6i3cbpy
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceanahrrtgkta7dhkjpumnrt4wdahj7zoouiyfjneyn43t6ithobue

**Comment by MegTei** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec3bsqkps4jo2nzn4hbltovtcxolt4vggqymr6zotttatnw2c34ze 
#### Address 
> f1c2nxtixkivuzmmezwawg4nwzoknvd7hto37cy4q
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1ystxl2ootvpirpa7ebgwl7vlhwkbx2r4zjxwe5i
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec3bsqkps4jo2nzn4hbltovtcxolt4vggqymr6zotttatnw2c34ze

**Comment by flyworker** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb3uibyzozswkabf6bzynms3urr2udp6otqb73aia2vpl2p4uxsoe 
#### Address 
> f1c2nxtixkivuzmmezwawg4nwzoknvd7hto37cy4q
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1hlubjsdkv4wmsdadihloxgwrz3j3ernf6i3cbpy
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb3uibyzozswkabf6bzynms3urr2udp6otqb73aia2vpl2p4uxsoe

**Comment by Neal-fil** [comment]
Hi @xingjitansuo, I noticed this is slingshot project but I failed to retrieve f01392600 and f01660837. Please check.

**Comment by xingjitansuo** [comment]
Hi @Neal-fil  
Thanks for your notice. I am sorry that you failed in retrieval. If you are looking for any specific file, you can probably retrieve it from other nodes, and that is one of the pros of storing multiple copies for the same piece.  

Since I do not control the storage provider, I cannot guarantee the retrieval is online 24/7.  But I do remember checking they supported fast retrieval when I sent the deals, and I found evidence from one of the slack channels that the node you mentioned was up for retrieval, and please check the below image.

![211667315758_ pic](https://user-images.githubusercontent.com/72185104/199268393-5d7d8d39-4800-4102-b885-ee85dcfa4673.jpg)

In addition, Slingshot Restore SPs were all verified && KYC  by the Fil-Plus team before, so if you have any further questions regarding the SP, maybe they could help as well.

**Comment by filplus-checker** [comment]
## DataCap and CID Checker Report[^1]
 - Organization: `CabrinaHuang-Slingshot Restore Program`
 - Client: `f1c2nxtixkivuzmmezwawg4nwzoknvd7hto37cy4q`
### Storage Provider Distribution
The below table shows the distribution of storage providers that have stored data for this client.

If this is the first time a provider takes verified deal, it will be marked as `new`.

For most of the datacap application, below restrictions should apply.
 - Storage provider should not exceed 25% of total datacap.
 - Storage provider should not be storing duplicate data for more than 20%.
 - Storage provider should have published its public IP address.
 - All storage providers should be located in different regions.

⚠️ [f01660837](https://filfox.info/en/address/f01660837) has unknown IP location.

| Provider                                                    |                           Location | Total Deals Sealed | Percentage | Unique Data | Duplicate Deals |
| :---------------------------------------------------------- | ---------------------------------: | -----------------: | ---------: | ----------: | --------------: |
| [f01392600](https://filfox.info/en/address/f01392600)`new`  | Hong Kong, Central and Western, HK |          24.89 TiB |     24.33% |   24.89 TiB |           0.00% |
| [f01702940](https://filfox.info/en/address/f01702940)       |                  Dallas, Texas, US |          21.22 TiB |     20.75% |   21.22 TiB |           0.00% |
| [f01611097](https://filfox.info/en/address/f01611097)       |       San Clemente, California, US |           9.25 TiB |      9.05% |    9.25 TiB |           0.00% |
| [f01558688](https://filfox.info/en/address/f01558688)       |               Toronto, Ontario, CA |           7.22 TiB |      7.06% |    7.22 TiB |           0.00% |
| [f01392893](https://filfox.info/en/address/f01392893)       |       Amsterdam, North Holland, NL |           6.56 TiB |      6.42% |    6.56 TiB |           0.00% |
| [f01345523](https://filfox.info/en/address/f01345523)       |            Antwerpen, Flanders, BE |           5.54 TiB |      5.41% |    5.54 TiB |           0.00% |
| [f01652333](https://filfox.info/en/address/f01652333)       |          Sunnyvale, California, US |           5.26 TiB |      5.14% |    5.26 TiB |           0.00% |
| [f010617](https://filfox.info/en/address/f010617)           |       Surrey, British Columbia, CA |           4.97 TiB |      4.86% |    4.94 TiB |           0.63% |
| [f097777](https://filfox.info/en/address/f097777)           |                Kivertsi, Volyn, UA |           3.44 TiB |      3.36% |    3.44 TiB |           0.00% |
| [f01660837](https://filfox.info/en/address/f01660837)       |                            Unknown |           3.20 TiB |      3.12% |    3.20 TiB |           0.00% |
| [f01163272](https://filfox.info/en/address/f01163272)       |                Perm, Perm Krai, RU |           2.44 TiB |      2.38% |    2.44 TiB |           0.00% |
| [f01208189](https://filfox.info/en/address/f01208189)`new`  |        Sydney, New South Wales, AU |           2.34 TiB |      2.29% |    2.34 TiB |           0.00% |
| [f08403](https://filfox.info/en/address/f08403)             |  Bourton on the Water, England, GB |           2.16 TiB |      2.11% |    2.16 TiB |           0.00% |
| [f01157288](https://filfox.info/en/address/f01157288)       |        Sydney, New South Wales, AU |           1.66 TiB |      1.62% |    1.66 TiB |           0.00% |
| [f01385207](https://filfox.info/en/address/f01385207)       |              Lincoln, Nebraska, US |           1.25 TiB |      1.22% |    1.25 TiB |           0.00% |
| [f066596](https://filfox.info/en/address/f066596)           |          San Diego, California, US |         928.00 GiB |      0.89% |  928.00 GiB |           0.00% |

![Provider Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/249/1671094314373.png)
### Deal Data Replication
The below table shows how each many unique data are replicated across storage providers.
- No more than 25% of unique data are stored with less than 4 providers.

⚠️ 99.88% of deals are for data replicated across less than 4 storage providers.

| Unique Data Size | Total Deals Made | Number of Providers | Deal Percentage |
| ---------------: | ---------------: | ------------------: | --------------: |
|        63.52 TiB |        63.55 TiB |                   1 |          62.12% |
|        15.79 TiB |        31.58 TiB |                   2 |          30.87% |
|         2.35 TiB |         7.04 TiB |                   3 |           6.88% |
|        32.00 GiB |       128.00 GiB |                   4 |           0.12% |

![Replication Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/249/1671094314926.png)
### Deal Data Shared with other Clients
The below table shows how many unique data are shared with other clients.
Usually different applications owns different data and should not resolve to the same CID.

⚠️ CID sharing has been observed.

| Other Client                                                                                                          | Application                                                                                                                     | Total Deals Affected | Unique CIDs |  Verifier |
| :-------------------------------------------------------------------------------------------------------------------- | :------------------------------------------------------------------------------------------------------------------------------ | -------------------: | ----------: | --------: |
| [f1zil5gn6fgelxw5lb7sbv22eayfltg7eohcrqpni](https://filfox.info/en/address/f1zil5gn6fgelxw5lb7sbv22eayfltg7eohcrqpni) | [CabrinaHuang\-Xingjitansuo](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/232)                       |           942.91 TiB |         797 | LDN # 232 |
| [f1lnecek42mynnu5ph7ucoikald2gucl6jty2ivty](https://filfox.info/en/address/f1lnecek42mynnu5ph7ucoikald2gucl6jty2ivty) | [](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/171)                                                 |           234.17 TiB |       2,390 | LDN # 171 |
| [f1pkrmygbvweykpjcut36lf7ewgqdfhjklbhvepda](https://filfox.info/en/address/f1pkrmygbvweykpjcut36lf7ewgqdfhjklbhvepda) | [Protocol Labs \( project: Slingshot Evergreen \)](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/293) |             4.38 TiB |         137 | LDN # 293 |

[^1]: To manually trigger this report, add a comment with text `checker:manualTrigger`
