### ISSUE TITLE
[DataCap Application] NOKNOK

### ISSUE THREAD

**Issue by giggy22** [filecoin-project/filecoin-plus-large-datasets#25]
# Large Dataset Notary Application

To apply for a DataCap allocation for your dataset, please fill out the following information.

## Core Information
- Organization Name: NOKNOK
- Website / Social Media: [www.noknok.co.kr](http://www.noknok.co.kr/)
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 1PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 50TiB
- On-chain address for first allocation: f3uabycbcjbizjnhvkfh3vyodjotznh5qn6c5o4enmgxy4fc7xycbnqnhkq3qwmevhmvrrzbrvnybpoksp7swq

_Please respond to the questions below in paragraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

## Project details

Share a brief history of your project and organization.
```
NOKNOK is Korea’s TOP Casual Simulation Game Company.
The history of games made by NOKNOK is as follows:

History of NOKNOK
2018. 09 – “Happy Delivery for Kakao” launched on KaKao games, Popularity Rank #1
2018. 05 – "Inn of Heroes" launched on Google Play.
2015.08 – “Happy Delivery for Kakao” launched on Google Play.
2015.06 – “Take Care of My Family “ launched. Google Play, Top Revenue Rank #54
2015.12 – "Chef Over Flower" launched. Google Play, Top Revenue Rank #34
2014.11 – "Happy Happy Bread Mobile” signs with Thai Publisher( True Digital Plus )
2014.09 – "Happy Happy Bread" launched. Google Play Japan, Revenue Rank # 40 ( Casual games Chart )
2014.04 – "Take Care of my Pet” launched. Google Play, Popularity Rank #1
2014.01 – "Happy Happy Bread for Kakao” launched. Google Play, Revenue Rank 28
2013.11 – "I Love Style for Kakao” launched. Google Play, Revenue Rank #26
2012.09 – "Fashion City Mobile” launched. Google Play, Top Revenue Rank #19
2012.07 – "Fashion City Mobile” launched. Apple App. Store, Top Revenue Rank #4
2012.03 – "Fashion City” Ranked #5 on Japan’s Mixi SNG ( PC )
2011.10 – "Fashion City” Ranked #1 on Taiwan’s SNS platform Yahoo Minik ( PC )
2011.03 – "Fashion City" Ranked #1 on Naver App. Store ( PC )
2009.12 – Noknok founded * Korea market ranking

In addition to the representative games of NOKNOK mentioned above, we have created various games.
```

What is the primary source of funding for this project?
```
As you can see above, the games we make have been consistently popular. We continue to earn revenue while servicing our games.
```

What other projects/ecosystem stakeholders is this project associated with?
```
Currently NOKNOK directs it, but there may be collaborations with other projects and organizations as well. 
```

## Use-case details

Describe the data being stored onto Filecoin
```
Various data necessary for game development will be saved. The Data are program sources, APKs, APIs, etc. required for game development, and graphic resources are also included. However, some sensitive data will be encrypted and stored.
```

Where was the data in this dataset sourced from?
```
It is created by ourselves as we develop the game.
```

Can you share a sample of what is in the dataset? A link to a file, an image, a table, etc., are good examples of this. 
```
This is the sample data. https://www.dropbox.com/sh/iwvpbtybqp2bd85/AABnCmf6MRM5tDwpt_3Mg73za?dl=0
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes, of course. Dataset can be retrieved. 
```

What is the expected retrieval frequency for this data?
```
It is expected that the retrieval frequency will not be high for the time being because necessary data related to game development are mainly stored. If a big fan of the game we made is in the Filecoin ecosystem, the frequency may increase. As we positively consider the development and launch of game services through the IPFS ecosystem in the future, the retrieval frequency may increase in the future.
```

For how long do you plan to keep this dataset stored on Filecoin? Will this be a permanent archival or a one-time storage deal?
```
If the Filecoin system in which we will participate is positive with this try, we wanna keep it permanently while conducting business.
```

## DataCap allocation plan

In which geographies do you plan on making storage deals?
```
Since our game is used a lot in Korea, it seems like we will make a storage deal mainly in Korea. However, we are also considering a deal with miners from other continents because we also need distributed storage for global expansion plans and data safety.
```

What is your expected data onboarding rate? How many deals can you make in a day, in a week? How much DataCap do you plan on using per day, per week?
```
We expect us to be able to onboard 50Tb a week & 10Tb a day.  There is already close to 1pb of data to be saved.
```

How will you be distributing your data to miners? Is there an offline data transfer process?
```
We received a reply that two miners and offline data transmission in Korea are possible, and we are considering this. Of course, we are thinking about other continental miners because online is also possible.
```

How do you plan on choosing the miners with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
Consideration for the miners we will be trading with is that first of all, they must be large enough, and so far there must be no problems with long-term management.
```

How will you be distributing data and DataCap across miners storing data?
```
Considering the miners' excellent management ability and low cost, we will select miners from other continents, including Korean miners, if conditions are good. And Based on the considerations, we will distribute the data through offline deals or online deals.
```

**Comment by dannyob** [comment]
FIlecoin Foundation supports this.

**Comment by rayshitou** [comment]
mathwallet supports this one.

**Comment by dkkapur** [comment]
@giggy22 - thanks for submitting your application for a large DataCap allocation to the Fil+ Notaries! As the Notaries and the Fil+ community carries out the due diligence process on your application - we'd love to invite you to participate in the Fil+ Community Governance Call. We're inviting clients applying for large amounts of DataCap to come present and field questions during the second half of each community call to help enable the process. The next set of calls are actually today - Tues Aug 31 at 3pm and 11pm UTC, information to participate can be found here: https://github.com/filecoin-project/notary-governance/issues/221. Looking forward to seeing you there or perhaps at the next one on Sept 14!

**Comment by MegTei** [comment]
Looks interesting, count me in

**Comment by galen-mcandrew** [comment]
## Multisig Notary requested
#### Total DataCap requested 
> 1PiB
#### Expected weekly DataCap usage rate 
> 50TiB

**Comment by MegTei** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedx6jynl3bhleo6lspvu4gqkrxq3j5y4gkj734gu764og5oo2ar6k 
#### Address 
> f3uabycbcjbizjnhvkfh3vyodjotznh5qn6c5o4enmgxy4fc7xycbnqnhkq3qwmevhmvrrzbrvnybpoksp7swq
#### Datacap Allocated
> 25TiB
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedx6jynl3bhleo6lspvu4gqkrxq3j5y4gkj734gu764og5oo2ar6k

**Comment by fabriziogianni7** [comment]
updating the comment of meg with the signer address to make it readable from the bot. cc @MegTei @dkkapur @galen-mcandrew

**Comment by Sunnyiscoming** [comment]
Hi @giggy22 
Are there any problems with using datacap?

**Comment by anbaichao1224** [comment]
updating the comment of meg with the signer address to make it readable from the bot

**Comment by Sunnyiscoming** [comment]
checker:manualTrigger
