### ISSUE TITLE
[DataCap Application]Star Image Culture Media

### ISSUE THREAD

**Issue by yukiljn** [filecoin-project/filecoin-plus-large-datasets#250]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Star Image Culture Media
- Website / Social Media: https://v.douyin.com/Lp6gMSy/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5 PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100 Tib
- On-chain address for first allocation: f1y7277tcuqdooge6opfzn3aumsaexvrpmtv2xkvy

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Our organization name is: Beijing Star Image Culture Media Co., Ltd. The company's business involves film and television variety show production, artist brokerage, Internet celebrity business, live broadcast sales and other fields.
```

What is the primary source of funding for this project?
```
1. Early investors invest capital.
2. The business income of the live broadcast business line.
3. Media promotion business income
```

What other projects/ecosystem stakeholders is this project associated with?
```
None.
```

## Use-case details

Describe the data being stored onto Filecoin
```
The data stored on Filecoin is currently basically open data in formats such as video, picture, and audio.
```

Where was the data in this dataset sourced from?
```
Mainly from company video media accounts.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://v.douyin.com/LpLe54E/
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes, it is.
```

What is the expected retrieval frequency for this data?
```
The expected retrieval frequency is unpredictable, but is expected to be very high.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
In about five years, I will keep updating.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Singapore and USA.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
It is mainly based on online data transmission, and there is almost no offline data transmission.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
I will choose to cooperate with miners with high ratings and strong capabilities on www.filrep.io.
```

How will you be distributing deals across storage providers?
```
The main choices are miners who support online data transmission.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, we have the funding to start making deals as soon as our receive DataCap.
```

**Comment by swatchliu** [comment]
How did you hear about the FIL+ program?

**Comment by pbumpers701** [comment]
Because we want to store data in a distributed network, we found that FIL is very suitable for our needs. And found the fillplus program in github during research. @swatchliu

**Comment by yukiljn** [comment]
Because we want to store data in a distributed network, we found that FIL is very suitable for our needs. And found the fillplus program in github during research. @swatchliu

**Comment by yukiljn** [comment]
@swatchliu Anything else should I offer?

**Comment by Sunnyiscoming** [comment]
@yukiljn 
1.The provided 映像星选 douyin(https://www.douyin.com/user/MS4wLjABAAAApewln5f9Fk4JbWFqm19iDccTZpgO3k4_ydBMQ-_66WjYJTQ-KPOAJ8MEedsY31EA) introduction is the source of the manufacturer to create sheets, quilt covers, MATS, blankets, children's bed products, high-quality cloth low-cost activities, dumped! It doesn't seem to fit with your description of the company.
2.Please provide the relationship between the organization and the other douyin link(https://www.douyin.com/user/MS4wLjABAAAAg40gtUVGiS1ayPljFWevgPpbJ_F7DNxp-Fc5zYkRHkE)
3.Please provide more data samples to prove that you already have 5PB data.

**Comment by yukiljn** [comment]
Hi there, @Sunnyiscoming 
Reply to your Q：
1. The description of our company said that we are a media company. This account （https://www.douyin.com/user/MS4wLjABAAAApewln5f9Fk4JbWFqm19iDccTZpgO3k4_ydBMQ-_66WjYJTQ-KPOAJ8MEedsY31EA)  shown here, just because we want to tell everybody we are a real company. Selling products is part of our business.
2. (https://www.douyin.com/user/MS4wLjABAAAAg40gtUVGiS1ayPljFWevgPpbJ_F7DNxp-Fc5zYkRHkE)The control of this account is in the hands of our company. The intent of the examples of "sample of data" is to give examples. That account is an example we gave. Of course, there are many more accounts and influencers under our company. In my opinion, listing them all defeats the purpose of "sample data".
3. video in the sample account has shown what kind of data we have.
Thanks.

**Comment by Sunnyiscoming** [comment]
@yukiljn 
2. I have asked this doyin account. ([https://www.douyin.com/user/MS4wLjABAAAAg40gtUVGiS1ayPljFWevgPpbJ_F7DNxp-Fc5zYkRHkE)](https://www.douyin.com/user/MS4wLjABAAAAg40gtUVGiS1ayPljFWevgPpbJ_F7DNxp-Fc5zYkRHkE)The)
3. Because the applied datacap is 5PB. Hope to provide more data samples, not all of them.

**Comment by dkkapur** [comment]
@yukiljn I'm going to close this issue for now since we have not heard in the last 2 weeks. Please ping back and let us know if this is still relevant.
