### ISSUE TITLE
[DataCap Application]Arlo Technologies, Inc

### ISSUE THREAD

**Issue by Leviiee** [filecoin-project/filecoin-plus-large-datasets#251]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name:Arlo Technologies, Inc
- Website / Social Media:https://www.arlo.com/en-us/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):3PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):400TiB
- On-chain address for first allocation:f1t6mtpp7tgxn7syu7jrhfcot4wosvitc72hvvsri

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Company's vision is to bring peace of mind by connecting and protecting what people care about the most. We build trusted, lifelong customer relationships by creating innovative, smart security solutions that deliver an exceptional user experience.
```

What is the primary source of funding for this project?
```
From company's own account.
```

What other projects/ecosystem stakeholders is this project associated with?
```
Nope.
```

## Use-case details

Describe the data being stored onto Filecoin
```
Videos about our products, which are allowed to be showed in public.
```

Where was the data in this dataset sourced from?
```
It was from demonstrations of our products or users' data which was allowed us to use as examples.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
Ok.
https://user-images.githubusercontent.com/98516536/153569973-a61fc88c-e784-4f2b-8dc7-bd9b10363710.mp4
https://user-images.githubusercontent.com/98516536/153569985-5dc6b2c0-ac11-4aa5-8acc-c9732f5f4f48.mp4
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
I confirm this data is public and can be used by our company.
```

What is the expected retrieval frequency for this data?
```
Maybe once half a year.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
It would be 5 years.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
North America and Asia.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
By online transfer process and offline process.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
For performance, we choose stable providers.
```

How will you be distributing deals across storage providers?
```
We give priority to providers who have a huge amount of experience.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes.
```

**Comment by swatchliu** [comment]
How did you hear about the FIL+ program?

**Comment by MRJAVAZHAO** [comment]
According to you request, your datasets are from your enduser. Can the data be public? Any authorization from your client?

**Comment by Leviiee** [comment]
@MRJAVAZHAO Yes! Our data is public and all of users' data is allowed to be used by our users. Before using data, we would ask for users' permissions.
![arlo1 com](https://user-images.githubusercontent.com/98516536/155095367-eab6989f-3d0c-4b62-80e5-1b8ee53313a8.jpeg)
![arlo2 com](https://user-images.githubusercontent.com/98516536/155095377-15cec474-e142-4fcf-b292-6fa4ee864ae3.jpeg)

**Comment by MRJAVAZHAO** [comment]
alright, thank you for your application！  please feel free to contact me if you need any assist。
@deep @galen @kevin diligence complete, please send it to RKH.

**Comment by Leviiee** [comment]
@MRJAVAZHAO Thanks a lot!

**Comment by galen-mcandrew** [comment]
Can you please provide an official email address for correspondence, something with the companies domain and name/title of the representative from Arlo that is working to onboard data to Filecoin?

The above screenshot is from this page: https://www.arlo.com/en-us/privacy-policy.html
