### ISSUE TITLE
[DataCap Application] Daneng Audio-Visual Culture Media

### ISSUE THREAD

**Issue by pbumpers701** [filecoin-project/filecoin-plus-large-datasets#253]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Beijing Daneng Audio-Visual Culture Media Co., Ltd.
- Website / Social Media: https://v.douyin.com/LpRWPsg/       https://www.youtube.com/channel/UCtA-porJYtKXchl6ntZ2XaA
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5 PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100 TiB
- On-chain address for first allocation:  f1xu6cxwplzrtrhrctvhcyax73xemgzagq7m4qoqq

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Our organization name is: Beijing Daneng Audio-Visual Culture Media Co., Ltd. is a cultural media company integrating creative planning, media promotion, marketing, and business operations. The company is committed to making Internet cultural products.
```

What is the primary source of funding for this project?
```
1. Early investors invest capital.
2. Media promotion business income
```

What other projects/ecosystem stakeholders is this project associated with?
```
None.
```

## Use-case details

Describe the data being stored onto Filecoin
```
The data stored on Filecoin basically is open data in formats such as video, picture, and audio.
```

Where was the data in this dataset sourced from?
```
Mainly from the company's video account
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://v.douyin.com/Lp8r114/ 
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes, it is public data.
```

What is the expected retrieval frequency for this data?
```
Because it is a video media account, it is expected that the retrieval frequency will be very high
```

For how long do you plan to keep this dataset stored on Filecoin?
```
I think it's a roughly 10 years archive and I'll constantly update our data stored on Filecoin.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
China and USA
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
We know technicians, mainly online transmission. If there is a need for large-scale data transmission, we will choose offline transmission.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
I will select miners which have high score according to www.filrep.io
```

How will you be distributing deals across storage providers?
```
I will mainly use online transmission to distribute my data, if there is a large batch of data, I will choose offline transmission.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, we have.
```

**Comment by XnMatrixSV** [comment]
We read your homepage content, very interesting, glad to have such a project to join. Your main content is video, which is highly searchable. Is filecoin mainly used for backup?

**Comment by pbumpers701** [comment]
We want to use ipfs as the primary storage method. Because we shoot far more footage than we publish, we think ipfs is the best place for us to store it. @XnMatrixSV

**Comment by pbumpers701** [comment]
We don't have an official website, Tiktok and Youtube are our channels to showcase our business. @UnionLabs2020

**Comment by UnionLabs2020** [comment]
The official website is one of the necessary materials for LDN application.

**Comment by pbumpers701** [comment]
I don’t have an official website doesn’t mean I don’t have business. Our company is of a media nature, and social media accounts are our value. The official website cannot absolutely represent anything.

**Comment by kernelogic** [comment]
This looks fun. Website is so 2010 :D

**Comment by marik336514** [comment]
大能  我是你的粉丝

**Comment by Joss-Hua** [comment]
When Da neng was a small blogger, I liked his videos. Welcome to Filecoin ecology. @pbumpers701

**Comment by pbumpers701** [comment]
@IPFSUnion @XnMatrixSV We would like to know what else should we offer?

**Comment by Sunnyiscoming** [comment]
1. Data sample can not be opened (https://v.douyin.com/Lp8r114/). Please check it.
2.Is your company's name 北京大能视听文化传媒有限公司? https://aiqicha.baidu.com/detail/compinfo?pid=xlTM-TogKuTwH9tfUp0y1FZSono50D6pWAmd&rq=ef&pd=ee&from=ps

**Comment by Sunnyiscoming** [comment]
Any update here?

**Comment by galen-mcandrew** [comment]
Closing this for now from no reply. When ready, please reopen or submit a new request here: https://plus.fil.org/ldn-application
