### ISSUE TITLE
[DataCap Application] Party Planning Agency

### ISSUE THREAD

**Issue by HashFisher** [filecoin-project/filecoin-plus-large-datasets#256]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Dehostyle
- Website / Social Media: https://www.dehostyle.com/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 2PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 50TiB
- On-chain address for first allocation: f3scjilalayifmhngnsvcwzj4rmy6vnsrylggwrjpiuk26bw75ikr7nw3zhfrfjgn4saawanvzucsfiqugtieq

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
We're professional 'party planners', 'stylists' and 'food directors' who offer everything from event planning to catering, styling and directing. We're also proud of our space directing and styling with sensuous and strong designing competence.


```

What is the primary source of funding for this project?
```
Funded by funding projects
```

What other projects/ecosystem stakeholders is this project associated with?
```
None
```

## Use-case details

Describe the data being stored onto Filecoin
```
All datasets of our past and current projects, Party Planning and Food Styling tutorials
```

Where was the data in this dataset sourced from?
```
By us
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://www.youtube.com/watch?v=r-RKdvI_z4Q
https://www.youtube.com/watch?v=V32l95zv5M0
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes, this is a public dataset.
```

What is the expected retrieval frequency for this data?
```
every quarter
```

For how long do you plan to keep this dataset stored on Filecoin?
```
5 years
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Preferably Asia
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
We'd prefer online
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We'll consult peer recommendations.
```

How will you be distributing deals across storage providers?
```
Evenly
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, we're all set to go!
```

**Comment by UnionLabs2020** [comment]
Website is broken.

**Comment by HashFisher** [comment]
> Website is broken.

I'm sorry but it works fine with our computers. Would you retry and let us know? We'd appreciate it!

**Comment by Sunnyiscoming** [comment]
![image](https://user-images.githubusercontent.com/105098820/169959310-337726fe-f793-4242-ab06-1cbde6b33722.png)
1. Website is still broken.
2. Can you provide more data sample and more detailed data sources to prove that you have 2 PB data?

**Comment by Sunnyiscoming** [comment]
Any update here?

**Comment by dkkapur** [comment]
@HashFisher  I'm going to close this issue for now since we have not heard in the last 2 weeks. Please ping back and let us know if this is still relevant.
