### ISSUE TITLE
[DataCap Application] Kondor Group (Blockchain-based ICT Company)

### ISSUE THREAD

**Issue by choicesmatter** [filecoin-project/filecoin-plus-large-datasets#257]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Kondor Group
- Website / Social Media: https://kondor.co.kr/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100TiB
- On-chain address for first allocation: f3sguquukr4rsqwz3f6jashvgi67fwfr3totdxrzi7d7dyv45ppzb4o7fr26htllx4kz5q5xxakzlpesvknjra

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
The KONDOR group is developing a core technology business that will lead the upcoming digital transformation.
Maximizing synergy through convergence of blockchain, metaverse, and entertainment. We connect technology and everyday life where imagination becomes reality.

```

What is the primary source of funding for this project?
```
We're self-sufficient.
```

What other projects/ecosystem stakeholders is this project associated with?
```
NA
```

## Use-case details

Describe the data being stored onto Filecoin
```
Entertainment
Social Contents, Live Commerce, Metaverse activities
Datasets generated through our business

```

Where was the data in this dataset sourced from?
```
Sourced from our own
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://butterland.co.kr
https://www.ckbbrothers.com
https://www.youtube.com/watch?v=cibrd_w3JL4
Please consult our website 'https://kondor.co.kr'.
You'll see the above mentioned companies are all subsidiaries of Kondor Group. 
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
This is a public dataset.
```

What is the expected retrieval frequency for this data?
```
Several times a year.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
approximately 2 years
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Asia
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Both work!
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
Through thorough selection
```

How will you be distributing deals across storage providers?
```
Each storage provider gets 10% of the DataCap maximum.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Self-sufficient already
```

**Comment by UnionLabs2020** [comment]
I have sent the confirmation letter to your official mailbox. But the server told me that it doesn't exist.

**Comment by choicesmatter** [comment]
> I have sent the confirmation letter to your official mailbox. But the server told me that it doesn't exist.

Thank you for letting me know. We've actually found some problems with our server. We apologize. We'll get back you once we have it fixed.

**Comment by Sunnyiscoming** [comment]
@choicesmatter Have it fixed？

**Comment by dkkapur** [comment]
@choicesmatter I'm going to close this issue for now since we have not heard in the last 2 weeks. Please ping back and let us know if this is still relevant.
