### ISSUE TITLE
[DataCap Application] Each Journal

### ISSUE THREAD

**Issue by jjeeny** [filecoin-project/filecoin-plus-large-datasets#258]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Each Journal
- Website / Social Media: http://www.eachj.co.kr/, https://eachj.tistory.com/, https://twitter.com/eachj77, https://blog.naver.com/each-j, https://www.facebook.com/eachjournal/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 3PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100TiB
- On-chain address for first allocation: f3wl2qa3io3w3c6eptrkd7x3rct7jq4n3bzkbpqvjnbrkzkawal5gglgznfdjiiialvzxmpfneuc63u2poejlq

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Our company was created by combining the first letters of Environment, Art, Construction, and Human.
It is intended to be a cultural space where individual individuals can gather and coexist with each other.
We want to be a medium that can be harmonized, not alone, but at the same time has its own.
```

What is the primary source of funding for this project?
```
Just with the funds of our company.
```

What other projects/ecosystem stakeholders is this project associated with?
```
We have no others in this project.
```

## Use-case details

Describe the data being stored onto Filecoin
```
Our company has numerous writers writing articles and even collecting readers' contributions. Therefore, we would like to save a draft of the article, a completed version, and a preliminary article. Most of the data are documented, and I also want to save videos and photo materials.
```

Where was the data in this dataset sourced from?
```
Asia.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
Here's one of our article. http://www.eachj.co.kr/news/articleView.html?idxno=5288
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Ok. We already understand that.
```

What is the expected retrieval frequency for this data?
```
Our article covers various fields, so we expect many people to search.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
Our company wants to save data as long as possible because the article data continues to accumulate.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
We are planning to make deals in the South Korea because we are rooted in the country.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
I think our company would use both online and offline transfer process.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
Since it's our first deal, we don't have much information about SP yet. So I'm currently looking for a good SP through the Slack channel related to FileCoin. When signing a contract with SP, we will proceed in the direction in which our data can be retrieved.
```

How will you be distributing deals across storage providers?
```
I think our company would use both online and offline transfer process.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
We are currently working on getting ready before receiving the Datacap. For getting the Datacap, me and my colleagues were designated as business managers. In addition, there are so many IT companies near our company that we are receiving help by inquiring about the process after receiving the Datacap. If there is a problem that cannot be solved in the process, I would like to ask the community about it.
```

**Comment by Sunnyiscoming** [comment]
I do not see video files through your website, mostly articles. Can you be more specific about the source of the data.

**Comment by Sunnyiscoming** [comment]
@jjeeny Any update here?

**Comment by dkkapur** [comment]
@jjeeny I'm going to close this issue for now since we have not heard in the last 2 weeks. Please ping back and let us know if this is still relevant.
