### ISSUE TITLE
[DataCap Application] Youtube Channel_Coin Class 

### ISSUE THREAD

**Issue by classofcoin** [filecoin-project/filecoin-plus-large-datasets#259]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Coin Class
- Website / Social Media: https://www.youtube.com/channel/UCO-ZvwtuptqO398lR2dIYvg
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 4PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100TiB
- On-chain address for first allocation: f3qnzdigxsny7ougpatlt4x3725bnu3djiukfwlepews7tjdvfssyejvsrdt6r755ev5wrio3nwhft7zgl4daq

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
I run a YouTube channel that introduces FileCoin and Protocol Labs.
I do not broadcast by any particular company or represents any interest group. I fairly provide information on the current situation of FileCoin, and broadcasts to organize and notice information known by Protocol Labs or FileCoin Foundation.
Also, I am helping people who have been scammed or damaged by vicious filecoin mining company. 
I really think FileCoin will be the third coin after Bitcoin and Ethereum in the future. Therefore,  I'm promoting FileCoin to go to that moment, and I myself wanted to save videos of my channel in FileCoin storage, so I applied for this data cap.
```

What is the primary source of funding for this project?
```
me
```

What other projects/ecosystem stakeholders is this project associated with?
```
me and filecoin's ecosystem (because I inform my subscribers filecoin and protocol labs)
```

## Use-case details

Describe the data being stored onto Filecoin
```
My youtube channel is about filecoin, and its mechanism and IPFS protocol. It is informative and I am not standing specific company's side. so I think my youtube channel's information is very useful and good enough to open public. 
```

Where was the data in this dataset sourced from?
```
me, informations are from protocol labs and filecoin foundation, filecoin docs. 
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://www.youtube.com/watch?v=mS_ZxQFb1O4
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes
```

What is the expected retrieval frequency for this data?
```
Recently, my Youtube channel is scoring over thousands view for each videos. So I think it would be similar to my youtube view number. 
```

For how long do you plan to keep this dataset stored on Filecoin?
```
Forever
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Asia, North America
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
both, prefer offline. I do have offline data transfer process
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
I will make a meeting time with various companies and ask them if they have enough technology and retrieve skills. Then I will select some companies. 
```

How will you be distributing deals across storage providers?
```
I will contact with several companies and choose 5 or more SP to preserve my data. 
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
YES, I can make a deal as soon as I recieve datacap, my data are ready and I am contacting with some of companies too. 
```

**Comment by galen-mcandrew** [comment]
@classofcoin Seems like an interesting use case, but it does not look like 4PiB worth of content. Can you help provide some more details about the scale of video data that you are intending to upload?
