### ISSUE TITLE
[DataCap Application] Dukesoft / Slingshot Restore (Part 2)

### ISSUE THREAD

**Issue by RobQuistNL** [filecoin-project/filecoin-plus-large-datasets#262]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Dukesoft - Slingshot Restore
- Website / Social Media:Dukesoft.nl
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 2 PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 500TiB
- On-chain address for first allocation: f3w436qzcbnzpngwwkslethcbsnt7rjdslf25mk7ufoo27gmf4uxt3pa3yn5zilzaqwqduew7pqmu5v2nypuiq

## Project details

Share a brief history of your project and organization.
```
Repairing the lost slingshot data.
```

What is the primary source of funding for this project?
```
My own time.
```

What other projects/ecosystem stakeholders is this project associated with?
```
Filecoin / Slingshot.
```

## Use-case details

Describe the data being stored onto Filecoin
```
Folding at Home / Covid19 dataset
```

Where was the data in this dataset sourced from?
```
Public dataset assigned to me by Protocol Labs
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
[Slingshot restore overviw](https://slingshot.filecoin.io/restore/fah-public-data-covid19-absolute-free-energy)
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes
```

What is the expected retrieval frequency for this data?
```
Once in a while
```

For how long do you plan to keep this dataset stored on Filecoin?
```
At least 1 year
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
North America, South America, Europe, Maybe Africa
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Offline deals. Wrote custom tooling for that.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
Already have a few from the restore program.
```

How will you be distributing deals across storage providers?
```
Spreading the deals over 5 different miners as per the slingshot recovery project's rules.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes
```

**Comment by RobQuistNL** [comment]
@galen-mcandrew @cryptowhizzard @neogeweb3 @Fenbushi-Filecoin @TimWilliams00 @MegTei 

Sorry to bother you but this requests' been open for a while and I can't continue the Slingshot Restore project without it

**Comment by galen-mcandrew** [comment]
## Multisig Notary requested
#### Total DataCap requested 
> 2PiB
#### Expected weekly DataCap usage rate 
> 500TiB

**Comment by flyworker** [comment]
strange, I did not see this request on my notary panel

**Comment by galen-mcandrew** [comment]
@flyworker it's still going to RKH, there was some delay with the bot. Should show up for notaries by end of week. Thanks!

**Comment by RobQuistNL** [comment]
Still nothing?

**Comment by galen-mcandrew** [comment]
@RobQuistNL bot has kicked off the allocation request above, so notaries should see it in the app now
![Screen Shot 2022-03-17 at 6 49 52 PM](https://user-images.githubusercontent.com/85587348/158922083-1c1883dd-08d7-453e-9366-4ad936ee77b1.png)

**Comment by galen-mcandrew** [comment]
@fabriziogianni7 looks like the rounding calculation is still not quite accurate here, could we adjust this to round to 102.4 TiB for example?

**Comment by RobQuistNL** [comment]
Thanks Galen. Hope I have the DC soon : )

**Comment by TimWilliams00** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaggqnluee5qgtvmuj7zgkj5qsyqc5fxjli5z27evdk5hqnouiinm 
#### Address 
> f3w436qzcbnzpngwwkslethcbsnt7rjdslf25mk7ufoo27gmf4uxt3pa3yn5zilzaqwqduew7pqmu5v2nypuiq
#### Datacap Allocated
> 102.40TiB
#### Signer Address
> f1fkxkfxgopjf3ufnfg5i3m6qlwf73kp4w5zz7nnq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaggqnluee5qgtvmuj7zgkj5qsyqc5fxjli5z27evdk5hqnouiinm

**Comment by RobQuistNL** [comment]
Is there any action required from my end?

**Comment by RobQuistNL** [comment]
Awesome!! <3 thanks a ton!

**Comment by RobQuistNL** [comment]
Please note that this 100TiB will probaly be used up somewhere around tomorrow

**Comment by RobQuistNL** [comment]
its gone again :(

**Comment by cryptowhizzard** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebijziaif2bjjgw2cbc4trrqyyvy4ygsbnkl23nd6fjj47s4bzc4g 
#### Address 
> f3w436qzcbnzpngwwkslethcbsnt7rjdslf25mk7ufoo27gmf4uxt3pa3yn5zilzaqwqduew7pqmu5v2nypuiq
#### Datacap Allocated
> 204.79TiB
#### Signer Address
> f1krmypm4uoxxf3g7okrwtrahlmpcph3y7rbqqgfa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebijziaif2bjjgw2cbc4trrqyyvy4ygsbnkl23nd6fjj47s4bzc4g

**Comment by s0nik42** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceasg2ydlyqwu5b5xjehugedmse7lfucsgqkktktcmoravn2hlzgwi 
#### Address 
> f3w436qzcbnzpngwwkslethcbsnt7rjdslf25mk7ufoo27gmf4uxt3pa3yn5zilzaqwqduew7pqmu5v2nypuiq
#### Datacap Allocated
> 204.79TiB
#### Signer Address
> f1wxhnytjmklj2czezaqcfl7eb4nkgmaxysnegwii
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceasg2ydlyqwu5b5xjehugedmse7lfucsgqkktktcmoravn2hlzgwi

**Comment by MegTei** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacea4u5c2sd3crv6xw3zhrwgjglraclmljgansnryibalbqpk5nbj6e 
#### Address 
> f3w436qzcbnzpngwwkslethcbsnt7rjdslf25mk7ufoo27gmf4uxt3pa3yn5zilzaqwqduew7pqmu5v2nypuiq
#### Datacap Allocated
> 409.59TiB
#### Signer Address
> f1ystxl2ootvpirpa7ebgwl7vlhwkbx2r4zjxwe5i
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacea4u5c2sd3crv6xw3zhrwgjglraclmljgansnryibalbqpk5nbj6e

**Comment by TimWilliams00** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaqeqa6bnjvr33cti4hvsbbobeuxfq4ercrjkbvaflsxd2nau7bkk 
#### Address 
> f3w436qzcbnzpngwwkslethcbsnt7rjdslf25mk7ufoo27gmf4uxt3pa3yn5zilzaqwqduew7pqmu5v2nypuiq
#### Datacap Allocated
> 409.59TiB
#### Signer Address
> f1fkxkfxgopjf3ufnfg5i3m6qlwf73kp4w5zz7nnq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaqeqa6bnjvr33cti4hvsbbobeuxfq4ercrjkbvaflsxd2nau7bkk

**Comment by dkkapur** [comment]
This went through, client still has DataCap. Fixing labels. 
![image](https://user-images.githubusercontent.com/2343218/164626011-1edef104-78a1-488c-924b-87b6d4d8cb58.png)

**Comment by Yvette516** [comment]
As far as I know, there are no miners in South America and Africa .Could you provide the ID of miners in these areas？

**Comment by RobQuistNL** [comment]
I think the selected miners right now are spread throughout NA and EU only

**Comment by filplus-checker** [comment]
## DataCap and CID Checker Report[^1]
 - Organization: `Dukesoft - Slingshot Restore`
 - Client: `f3w436qzcbnzpngwwkslethcbsnt7rjdslf25mk7ufoo27gmf4uxt3pa3yn5zilzaqwqduew7pqmu5v2nypuiq`
### Storage Provider Distribution
The below table shows the distribution of storage providers that have stored data for this client.

If this is the first time a provider takes verified deal, it will be marked as `new`.

For most of the datacap application, below restrictions should apply.
 - Storage provider should not exceed 25% of total datacap.
 - Storage provider should not be storing duplicate data for more than 20%.
 - Storage provider should have published its public IP address.
 - All storage providers should be located in different regions.

⚠️ [f01660837](https://filfox.info/en/address/f01660837) has unknown IP location.

| Provider                                                    |                         Location | Total Deals Sealed | Percentage | Unique Data | Duplicate Deals |
| :---------------------------------------------------------- | -------------------------------: | -----------------: | ---------: | ----------: | --------------: |
| [f01345523](https://filfox.info/en/address/f01345523)       |          Antwerpen, Flanders, BE |         370.84 TiB |     23.57% |  370.46 TiB |           0.10% |
| [f01392893](https://filfox.info/en/address/f01392893)       |     Amsterdam, North Holland, NL |         369.45 TiB |     23.48% |  369.29 TiB |           0.04% |
| [f01702940](https://filfox.info/en/address/f01702940)       |                Dallas, Texas, US |         194.38 TiB |     12.35% |  194.31 TiB |           0.03% |
| [f01752548](https://filfox.info/en/address/f01752548)`new`  |          Seattle, Washington, US |         188.35 TiB |     11.97% |  188.35 TiB |           0.00% |
| [f01652333](https://filfox.info/en/address/f01652333)       |        Sunnyvale, California, US |         175.60 TiB |     11.16% |  175.60 TiB |           0.00% |
| [f01558688](https://filfox.info/en/address/f01558688)       |             Toronto, Ontario, CA |         119.17 TiB |      7.57% |  119.17 TiB |           0.00% |
| [f0838923](https://filfox.info/en/address/f0838923)         |          Seattle, Washington, US |          78.21 TiB |      4.97% |   78.21 TiB |           0.00% |
| [f01611097](https://filfox.info/en/address/f01611097)       |     San Clemente, California, US |          36.16 TiB |      2.30% |   36.16 TiB |           0.00% |
| [f01775922](https://filfox.info/en/address/f01775922)       |            Ashburn, Virginia, US |          20.03 TiB |      1.27% |   20.03 TiB |           0.00% |
| [f01208862](https://filfox.info/en/address/f01208862)       | Heerhugowaard, North Holland, NL |          11.73 TiB |      0.75% |   11.73 TiB |           0.00% |
| [f01786387](https://filfox.info/en/address/f01786387)       | Heerhugowaard, North Holland, NL |           7.73 TiB |      0.49% |    7.73 TiB |           0.00% |
| [f01847751](https://filfox.info/en/address/f01847751)`new`  |             Denver, Colorado, US |           1.56 TiB |      0.10% |    1.56 TiB |           0.00% |
| [f01240](https://filfox.info/en/address/f01240)             | Heerhugowaard, North Holland, NL |          32.00 GiB |      0.00% |   32.00 GiB |           0.00% |
| [f01660837](https://filfox.info/en/address/f01660837)       |                          Unknown |          16.00 GiB |      0.00% |   16.00 GiB |           0.00% |

![Provider Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/262/1671094391568.png)
### Deal Data Replication
The below table shows how each many unique data are replicated across storage providers.
- No more than 25% of unique data are stored with less than 4 providers.

✔️ Data replication looks healthy.

| Unique Data Size | Total Deals Made | Number of Providers | Deal Percentage |
| ---------------: | ---------------: | ------------------: | --------------: |
|        32.00 GiB |        32.00 GiB |                   1 |           0.00% |
|         1.63 TiB |         3.25 TiB |                   2 |           0.21% |
|        77.58 TiB |       233.20 TiB |                   3 |          14.82% |
|       144.10 TiB |       576.40 TiB |                   4 |          36.64% |
|       141.01 TiB |       705.16 TiB |                   5 |          44.82% |
|         9.20 TiB |        55.22 TiB |                   6 |           3.51% |

![Replication Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/262/1671094392200.png)
### Deal Data Shared with other Clients
The below table shows how many unique data are shared with other clients.
Usually different applications owns different data and should not resolve to the same CID.

✔️ No CID sharing has been observed.

[^1]: To manually trigger this report, add a comment with text `checker:manualTrigger`
