### ISSUE TITLE
[DataCap Application] Harain Company

### ISSUE THREAD

**Issue by harain12** [filecoin-project/filecoin-plus-large-datasets#263]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Daitjihye/Harain Company
- Website / Social Media: https://shoppinglive.naver.com/channels/66905
https://smartstore.naver.com/daitjihye
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 3PIB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100TIB
- On-chain address for first allocation: f1mvio35fttr4cumqnssbdg6ytotht7gzi67lyqpy

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Harline Company is a company that conducts online sales and live commerce through a channel called 'Daitjihye'. 13 comedians and broadcasters united to run the company, representing the broadcaster Ha Ji-hye. In the company name 'Harain', 'Hara' means 'Do' in Korean, and 'in' means 'person'. And at the same time, it contains the English meaning of 'in', which means 'to go into a person and act'. In the Covid era, as the untact and ontact consumption trends spread, we want Harline Company to take center stage in the 'mobile live commerce market' and 'one-person media and viral advertisements' that are rapidly growing recently. We want to create the best content with the tremendous experience and know-how accumulated on various platforms, including over-the-air broadcasting. We want to shoot a lot of videos, but we have limited production due to the cost of storage space. We want to contribute to the ecosystem by producing high-quality videos and storing large-capacity video media in Filecoin.

```

What is the primary source of funding for this project?
```
Main source of funds is the profit from contracts with platform companies and advertisers

```

What other projects/ecosystem stakeholders is this project associated with?
```
platform companies and advertisers

```

## Use-case details

Describe the data being stored onto Filecoin
```
We plan to save videos for live commerce (about 1 hour per a shot).
```

Where was the data in this dataset sourced from?
```
Those are videos we shot for live commerce broadcasting.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://shoppinglive.naver.com/replays/233714?fm=shoppinglive&sn=home
[하라인컴퍼니_총괄(최종) (1).pdf](https://github.com/filecoin-project/filecoin-plus-large-datasets/files/8106632/_.1.pdf)

```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
No specific permissions

```

What is the expected retrieval frequency for this data?
```
There is no fixed retrieval frequency. It depends on business.

```

For how long do you plan to keep this dataset stored on Filecoin?
```
Better to store permanently
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Planning in Korea and USA.

```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
We have offline deal process.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We are choosing by our definition, and we may do some updates in the future
```

How will you be distributing deals across storage providers?
```
We will distribute equally, and manually select the storage providers who has high quality
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
yes
```

**Comment by harain12** [comment]
> We have found some problems in the information provided.
> We could not find any **Web site or social media info** in the information provided

Hello,
Could anyone tell me why I've got this comment?  
I wrote info below this.
https://shoppinglive.naver.com/channels/66905
https://smartstore.naver.com/daitjihye

**Comment by harain12** [comment]
> > We have found some problems in the information provided.
> > We could not find any **Web site or social media info** in the information provided
> 
> Hello, Could anyone tell me why I've got this comment? I wrote info below this. https://shoppinglive.naver.com/channels/66905 https://smartstore.naver.com/daitjihye

I found what was wrong:) fixed it.

**Comment by Sunnyiscoming** [comment]
@harain12 
1.Can you provide more data sample and more detailed data sources to prove that you have 3 PB data?
2. Have you established cooperation with miners? Please list their nodes.

**Comment by Sunnyiscoming** [comment]
Any update here?

**Comment by harain12** [comment]
1.Can you provide more data sample and more detailed data sources to prove that you have 3 PB data? 
You can check more detailed data in https://shoppinglive.naver.com/channels/66905 or https://smartstore.naver.com/daitjihye

2. Have you established cooperation with miners? Please list their nodes.
Once we get the datacap, we will make a deal with the miners.

**Comment by Sunnyiscoming** [comment]
@harain12 Do you have the website? Or provide proof of your company's existence.

**Comment by harain12** [comment]
Do you have the website? Or provide proof of your company's existence.
Our website is https://shoppinglive.naver.com/channels/66905 or https://smartstore.naver.com/daitjihye.
What proof exactly should we provide? It would be helpful if you could tell us exactly.

**Comment by Yvette516** [comment]
How would you make deals with SP offline?

**Comment by Sunnyiscoming** [comment]
Documents relating to the existence of the organization or websites proving the existence of the organization.
These two links seem that it is not the official website of your project/organization but belong to third platform.

**Comment by Sunnyiscoming** [comment]
Any update here?

**Comment by galen-mcandrew** [comment]
Due to no reply from client, we are closing this issue for now. When ready, please reopen or submit a new request here: https://plus.fil.org/ldn-application
