### ISSUE TITLE
[DataCap Application] The Herald Business

### ISSUE THREAD

**Issue by Ki-Jun-Lee** [filecoin-project/filecoin-plus-large-datasets#264]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: The Herald Business
- Website / Social Media: http://biz.heraldcorp.com/, https://twitter.com/TheHeraldBiz, https://www.instagram.com/heraldbusiness/, https://www.youtube.com/channel/UC5RMl_yYFDMAuww6rhW-oLA
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 3 PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100TiB
- On-chain address for first allocation: f1aderndy66ew46w7ym5rjvrxo7yislkn6t5ljxri

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Established in 1953 as a unique, informative journalism company that has kept pace with readers, Herald is growing into a media company that produces high quality digital content.
    Herald thrives in changing environments, and is dynamic and flexible. Aiming for reader-friendly content, Herald seeks innovation and growth in line with changes in the media market.
    As Korea’s leading specialist papers, The Herald Business continues to push their limits in various fields. We strive for digitalization of content while expanding our portfolio and making new efforts to stay ahead of the times.
    The Herald Business is a leading business daily in the mobile era. Seeking creative content based on original perspectives and specialty in economy, The Herald Business is pioneering to realize “mobile only” media with its distinguished video content.
```

What is the primary source of funding for this project?
```
Primary source of fundings are news subscription and advertising.
```

What other projects/ecosystem stakeholders is this project associated with?
```
None.
```

## Use-case details

Describe the data being stored onto Filecoin
```
The data being stored onto Filecoin are articles, photos and videos.
```

Where was the data in this dataset sourced from?
```
The dataset sourced from the reporter and journalist assinged by our company.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
You can find the sample of the data on our website and social media. (http://biz.heraldcorp.com/)
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes, this is a public dataset that can be retrieved by anyone.
```

What is the expected retrieval frequency for this data?
```
At the beginning of the article writing, the expected retrieval frequency is high, but due to the characteristic of the article, the retrieval frequency will decrease over time.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
We would like to keep this dataset stored on Filecoin permanently as possible.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Asia but mainly in South Korea.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
We will distributing the data both online and offline.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We have search for the storage provider in Korea. And we will distributing the data at least 3 different providers according to the storage provider's recommdations in South Korea.
```

How will you be distributing deals across storage providers?
```
Both online abd offline data transfer are acceptable.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, we have the resources.
```

**Comment by Sunnyiscoming** [comment]
@Ki-Jun-Lee What is your relationship with https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/268?

**Comment by Sunnyiscoming** [comment]
Any update here?

**Comment by Ki-Jun-Lee** [comment]
I apologize for late reply.
The Herald Business and The Korea Herald are companies under The Herald Cooperation. The Herald Business focuses on the economy and The Korea Herald focuses on English newspapers and can be viewed as a different affiliate.

**Comment by dkkapur** [comment]
@Ki-Jun-Lee - great, can you send us an email to filplus@fil.org from your official Herald Business email account so we can do a light KYC check on your representation of the company?

**Comment by Yvette516** [comment]
Can you show the relevant copyright certificate?

**Comment by galen-mcandrew** [comment]
Can you email [filplus@fil.org](mailto:filplus@fil.org) with your official work email so we can share this with notaries as a form of proof that you represent this organization?

**Comment by galen-mcandrew** [comment]
Due to no reply from client, we are closing this issue for now. When ready, please reopen or submit a new request here: https://plus.fil.org/ldn-application
