### ISSUE TITLE
[DataCap Application] K-MGA

### ISSUE THREAD

**Issue by bcgana** [filecoin-project/filecoin-plus-large-datasets#265]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: K-MGA
- Website / Social Media: http://www.k-mga.or.kr/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 2PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100TiB
- On-chain address for first allocation: f3xanyfjjsglefoh3kbkrjwcz4fqc2r3trnzd522wejx7s37cuy72wlavkngzhpa2ymuqxxiiiestywdpjqhwq

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Our association was established in 2013 and includes 670 companies in the mobile game industry. The nation's Ministry of Science and ICT is the competent authority of our association.
```

What is the primary source of funding for this project?
```
Members of our association introduced this project and proceeded with this project in one direction of the development of the game industry. So they will provide us with the funds for the project.
```

What other projects/ecosystem stakeholders is this project associated with?
```
Members of our association.
```

## Use-case details

Describe the data being stored onto Filecoin
```
Members' marketing videos and picture files are mainly data to store.
```

Where was the data in this dataset sourced from?
```
Companies belonging to our association will continue to create promotional data.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
(http://www.k-mga.or.kr/)
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Since data for promotion is mainly data to be stored, it is okay to use it as public data.
```

What is the expected retrieval frequency for this data?
```
Those interested in games will look up our data a lot.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
If I can save a lot of data, I will continue to save it without erasing it.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
I think it's mainly Asia.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
We are currently building an offline transfer with SP.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
Among the SPs recommended by our member companies, we are considering choosing the SP that suits our purpose the most.
```

How will you be distributing deals across storage providers?
```
We will use an offline transfer with SP.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
We are currently collecting marketing data from our members. We plan to start saving data as soon as we can.
```

**Comment by Sunnyiscoming** [comment]
@bcgana Please provide specific data samples. No information about the data is found in http://www.k-mga.or.kr/.

**Comment by Sunnyiscoming** [comment]
Do you have social media account?

**Comment by dkkapur** [comment]
@bcgana I'm going to close this issue for now since we have not heard in the last 2 weeks. Please ping back and let us know if this is still relevant.
