### ISSUE TITLE
[DataCap Application]K-Blockchain Contents Association

### ISSUE THREAD

**Issue by blockchainasso** [filecoin-project/filecoin-plus-large-datasets#266]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Korea Blockchain Contents Association
- Website / Social Media: https://kbcca.tistory.com/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100TiB
- On-chain address for first allocation:  f3xexw7qz6b5nz5fytnvvtlhtqqad6vm7xwqsod4cl5nsdod74wcelq42pl5zmjjdow5u6zsks55py3ckx2oqq

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
The Korea Blockchain Contents Association is a non-profit corporation composed of blockchain content business officials such as blockchain games, education, platforms, and solutions, and was established to promote the development of small and medium-sized content companies and contribute to industrial development.
The Korea Blockchain Contents Association will focus on the blockchain content market based on decentralization, cost reduction, reliability and security through major industrial development using Dapp (Decentralized Application) to become a frontier of the 4th industrial era with blockchain.
```

What is the primary source of funding for this project?
```
K-Blockchain Contents Association
```

What other projects/ecosystem stakeholders is this project associated with?
```
Our association has numerous memebers, each members are blockchain related company.
```

## Use-case details

Describe the data being stored onto Filecoin
```
Related to blockchain info, seminars and conference data, etc
```

Where was the data in this dataset sourced from?
```
our own, Korea
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
![img](https://user-images.githubusercontent.com/100180437/155059553-37f2ccc9-d649-4497-b79b-65a1b39599fe.png)
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
yes
```

What is the expected retrieval frequency for this data?
```
It would be fairly frequent, because our information and conferences was popular in korea.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
As long As I can store. 
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Asia, North America
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
We are contacting various company in korea, for offline data transfer process. 
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
choose company first, and will distribute our data in to several or more SP. Contacted company should be prepared to retrieve our data. 
```

How will you be distributing deals across storage providers?
```
offline deal for Korea SPs, Online deal for North America 
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
our association own funding, able to make a deals soon as I get datacap. 
```

**Comment by Sunnyiscoming** [comment]
Any update here?

**Comment by dkkapur** [comment]
@blockchainasso I'm going to close this issue for now since we have not heard in the last 2 weeks. Please ping back and let us know if this is still relevant.
