### ISSUE TITLE
[DataCap Application] The Korea Herald

### ISSUE THREAD

**Issue by KoreaHeraldNews** [filecoin-project/filecoin-plus-large-datasets#268]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: The Korea Herald
- Website / Social Media: : http://www.koreaherald.com/
https://youtube.com/c/thekoreaherald
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 3PIB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100TIB
- On-chain address for first allocation: f1l4x32zpffd6setxms2vm2yutx6opvqie4iyg3fa

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Established in 1953 as a unique, informative journalism company that has kept pace with readers, Herald is growing into a media company that produces high quality digital content. Herald thrives in changing environments, and is dynamic and flexible. Aiming for reader-friendly content, Herald seeks innovation and growth in line with changes in the media market. Herald is interested in IPFS and filecoin. It would be great if there was an opportunity to cover and report on PL's web 3.0 IPFS.

```

What is the primary source of funding for this project?
```
Money earned by the company, advertising revenue from clients
```

What other projects/ecosystem stakeholders is this project associated with?
```
The Herald Business, Herald Design, Herald Eco, Herald Artday, Herald Edu, Busan Global Village
```

## Use-case details

Describe the data being stored onto Filecoin
```
All Herald Korea articles and video news

```

Where was the data in this dataset sourced from?
```
Articles directly covered by reporters of the Korea Herald
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
[[Please answer here.](http://www.koreaherald.com/view.php?ud=20220224000723&np=1&mp=1
)]
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
We confirm that the data we stored are all open source. 
```

What is the expected retrieval frequency for this data?
```
There is no fixed retrieval frequency. It depends on business.

```

For how long do you plan to keep this dataset stored on Filecoin?
```
Most of data is required to stored permanently. 
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Currently planning in Korea and some English-speaking countries.

```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
We currently distribute it manually.

```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We plan to develop a related automation way as soon as possible. For now, we do it by hand selection. 

```

How will you be distributing deals across storage providers?
```
At present, we are mainly based on the personal wishes of the storage providers, and we will designate relevant standards for practice in the future
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, we have
```

**Comment by Sunnyiscoming** [comment]
@KoreaHeraldNews  What is your relationship with https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/264?

**Comment by Sunnyiscoming** [comment]
Any update here? @KoreaHeraldNews

**Comment by KoreaHeraldNews** [comment]
What is your relationship with #264?
The Korea Herald and The Herald Business are different affiliates. You can think of it as a different company.

**Comment by dkkapur** [comment]
Thanks! 

@KoreaHeraldNews Can you send us an email to filplus@fil.org from your official Korea Herald email account so we can do a light KYC check on your representation of the company?

**Comment by galen-mcandrew** [comment]
Due to no reply from client, we are closing this issue for now. When ready, please reopen or submit a new request here: https://plus.fil.org/ldn-application
