### ISSUE TITLE
[DataCap Application] Precious data of the earth and mankind

### ISSUE THREAD

**Issue by kdreampool** [filecoin-project/filecoin-plus-large-datasets#270]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: (주) 부린
- Website / Social Media: http://xn--sy2bt3e.kr/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 1 PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100 TiB
- On-chain address for first allocation: f15w2irla72a6s46jouhqsvh2tus3pzhmt44y7fei

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Started in 2010.
Underground facility surveying as a survey to confirm the location of facilities and structures buried under the surface of the ground, such as underground irrigation channels and underground facilities;
Survey conducted by the State or a public organization for the main purpose of avoiding duplication and increasing accuracy (Survey Method 2-3);
In addition to triangulation and general surveying
We are conducting a project called surveying valuable data of the earth and mankind as a public surveying project such as map production and aerial photography for surveying.
In 2014, we obtained permission for the ultra-light vehicle (drone) business and use power flying devices, hang gliders, paragliders, instruments, and unmanned flying devices that meet the standards set by the law, such as own weight and number of magnets.
We are also working on a project to record high-definition (4K or higher) images by surveying the current situation.
We are delighted to see the opportunity to safely store large amounts of valuable data on Earth and humanity in large quantities.
```

What is the primary source of funding for this project?
```
Shareholder support.
```

What other projects/ecosystem stakeholders is this project associated with?
```
Does not exist.
```
## Use-case details

Describe the data being stored onto Filecoin
```
High-definition (4K or higher) video and others recorded as a project called surveying the earth and humanity's precious surface.
```

Where was the data in this dataset sourced from?
```
This is our Burin. (주)부린
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://youtu.be/2XjIiQSzKhs
This is a sample the employee uploaded to YouTube for promotional purposes. One finished file is up to 10 GiB or more.
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes. But there is a license.
```

What is the expected retrieval frequency for this data?
```
Sometimes
```

For how long do you plan to keep this dataset stored on Filecoin?
```
It can also be a perpetual storage transaction.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
I will think of Korea first. and Asia
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Yes. Adopt online transmission and offline transmission.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We hope you choose a good credit miner. A storage provider with fewer sector defects and stable node operation (transfer speed, transaction success rate, etc.).
```

How will you be distributing deals across storage providers?
```
At least one copy of the data for each storage provider, or at least 20% of the total.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Support is still sufficient.
Once data limits are granted, it will start in 1-2 weeks.
```

**Comment by Sunnyiscoming** [comment]
@kdreampool 
> Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data). 
> 
> Yes. But there is a license. 

what "license" refers to?

> How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
> 
> We hope you choose a good credit miner. A storage provider with fewer sector defects and stable node operation (transfer speed, transaction success rate, etc.).

what "you" refers to? 

I can't open the website (http://xn--sy2bt3e.kr/). Please check it.

**Comment by kdreampool** [comment]
> @kdreampool
> 
> > 이것이 네트워크의 모든 사람이 검색할 수 있는 공개 데이터 세트인지 확인합니다(즉, 데이터를 보기 위해 특정 권한이나 액세스 권한이 필요하지 않음).
> > 예. 그러나 라이센스가 있습니다.
> 
> "라이센스"는 무엇을 의미합니까?
> 
> > 거래할 스토리지 제공업체를 어떻게 선택할 계획입니까? 여기에는 미래에 귀하와 다른 사람들이 데이터를 검색할 수 있도록 하는 계획이 포함되어야 합니다.
> > 좋은 신용 채굴기를 선택하시기 바랍니다. 섹터 결함이 적고 안정적인 노드 운영(전송 속도, 트랜잭션 성공률 등)을 제공하는 스토리지 제공자입니다.
> 
> "당신"은 무엇을 의미합니까?
> 
> [홈페이지( http://xn--sy2bt3e.kr/](http://xn--sy2bt3e.kr/) ) 가 열리지 않습니다 . 확인하십시오.

**Comment by dkkapur** [comment]
@kdreampool 

> All of our data is publicly available, but this means that it must not be downloaded or copied without our permission.
How do you plan to control for this on Filecoin? Retrievals are available for public data to any client on the network. Anyone can see the CIDs you store and can request retrievals from SPs you work with. 

In a similar vein, how do clients get permission or license from you?

If this is similar/equivalent to private data, then you will need to likely go down a similar path as https://github.com/filecoin-project/notary-governance/issues/489, working with a specific subset of notaries that can work with you and understand your data and do additional KYC as needed to establish a relationship. 

> In the Filecoin Reputation System, we will select an Asian or Korean SP with a high Reputation Score.

Do you have SPs already selected? 

> On my PC, this link opens well.

This link does not work for me as well. Additionally, this is an http and not an https link. Can you validate your company and identity via a different social media account or similar?

**Comment by Sunnyiscoming** [comment]
Any update here?

**Comment by kdreampool** [comment]
@dkkapur

> Any update here?
Questions are not answered as they have already been answered or are unrelated to the Data Cap application.
Any update here?

**Comment by Sunnyiscoming** [comment]
1. Fil+ Large datasets require data should be open, which means your data is stored without encryption and storage providers needs to provide data retrieval.  

> If this is similar/equivalent to private data,   then you will need to likely go down a similar path as https://github.com/filecoin-project/notary-governance/issues/489,  working with a specific subset of notaries that can work with you and understand your data and do additional KYC as   needed to establish a relationship.  

2.Your website is not working, which prevents us from understanding your business and enterprise to establish information with you and allocate datacap to you.  Or you can provide more information about your business and enterprise, such as proof of your organization's existence, business description, business partners, etc. 

3. We want to confirm whether you have found storage providers to cooperate with. If not, you can not do data storage on Filecoin even though you get datacap.

**Comment by dkkapur** [comment]
closing this one for now, given no reply for a while.
