### ISSUE TITLE
[DataCap Application] BOS

### ISSUE THREAD

**Issue by kord130** [filecoin-project/filecoin-plus-large-datasets#271]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: BOS
- Website / Social Media: http://www.bos-korea.com/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 1PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100TiB
- On-chain address for first allocation: f1otiim3t6dp4jf62yidtlvn6swr2q2w3mf5ykj7q

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
The pioneer of oriental medicine cosmetics in 42 years. Luxury brand of cosmetics. Luxury rental company
```

What is the primary source of funding for this project?
```
Product sales and investment attraction
```

What other projects/ecosystem stakeholders is this project associated with?
```
Currently BOS itself, but there could be possible participation with other projects as well.
```

## Use-case details

Describe the data being stored onto Filecoin
```
Customer DB , product manufacturing method , promotional video.
```

Where was the data in this dataset sourced from?
```
the company's server
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
http://www.bos-korea.com/category/%EB%AA%85%EA%B2%BD%EC%A7%80%EC%88%98/29/
http://www.bos-korea.com/category/%ED%99%94%EC%9A%A9/30/
http://www.bos-korea.com/product/list.html?cate_no=52
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
yes
```

What is the expected retrieval frequency for this data?
```
it would be frequent
```

For how long do you plan to keep this dataset stored on Filecoin?
```
permanently if possible
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Asia, (Korea and China; possibly mainly in Korea as of now)
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
online and offline, we have a technician from the partner company that would help us with the data transfer process
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
we have contacted at least 4 entrusted providers that ensured us about the retrieval.
```

How will you be distributing deals across storage providers?
```
by using both online and offline
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
There are storage providers and the partner company who are ready to help us with the data transfer. We plan to use the datacap as soon as we get approved.
```

**Comment by Sunnyiscoming** [comment]
@kord130 
1. Can you provide more data sample about Customer DB , product manufacturing method, instead of the picture from the website. And to prove that you already have 5 PB data alreday.
2. can you share the storage provider nodes here, I suppose you already contact them for data backup.

**Comment by Sunnyiscoming** [comment]
Any update here?

**Comment by dkkapur** [comment]
@kord130 I'm going to close this issue for now since we have not heard in the last 2 weeks. Please ping back and let us know if this is still relevant.
