### ISSUE TITLE
[DataCap Application] The World Recreation Educational Association. WREA

### ISSUE THREAD

**Issue by fdd20201015** [filecoin-project/filecoin-plus-large-datasets#273]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: World Recreation Educational Center Co.,Ltd(WREC), World Recreation Educational Association(WREA)
- Website / Social Media: http://www.creckorea.or.kr/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 3PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 200TiB
- On-chain address for first allocation: f1guitwioi7a2sbed276fcb7l5r27id5hxgsh7m6q

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
The World Recreation Educational Association(WREA) was started in 1989 as the Korea Living Recreation Association.
After passing through the World Recreation Exchange Committee in Korea in 2004, the name was changed to today's World Recreation Educational Association(WREA) in 2006.

WREA strives and cooperates with UNESCO, IOC and WHO. 
WREA is an NGO.

In a rapidly changing era, modern people are experiencing many social and cultural phenomena.
We live in an era where cultural and social exchanges across borders are frequent and free in a world where the global village is connected as one.
With the development of material civilization and the improvement of income, the desire for recreation is increasing.
The exhaustive desire of modern people to resolve the underlying emotions of joy and sorrow and fulfill social, physical, and emotional roles is increasing. 
Therefore, the establishment of a healthy recreational culture is necessary worldwide.

Based on the fundamental spirit of love and service, WREA is conducting various activities around the world to spread a healthy recreational culture and to create a bright social culture.

WREA will disseminate these cultures and programs around the world so that all people in the world can lead a healthy life physically, mentally and socially, and will contribute to the education of the whole person as an integrated education of intelligence, virtue, and body, and character education. In addition, by resolving cultural conflicts by understanding cultures between countries through recreational exchanges such as play, dance, song, and games of each country, we will contribute to the promotion of friendship between countries and further to world peace.
Korean dramas and K-pop are spreading all over the world due to the Korean Wave culture craze, and they are loved by people all over the world and are contributing to the improvement of the national brand value. By distributing leisure and recreation programs fused with the IT industry not only in Korea but also around the world to create jobs and leisure. It is good for the global economy by nurturing the recreational industry.

WREA will continuously research, develop and disseminate programs related to leisure and recreation around the world. 

WREA has entered into a business agreement with content education companies to provide certification courses and leisure activities worldwide on 6 continents. We are conducting recreational educational activities.
```

What is the primary source of funding for this project?
```
This is the support of shareholders of World Recreation Educational Center Co.,Ltd(WREC)
```

What other projects/ecosystem stakeholders is this project associated with?
```
Everything is owned by World Recreation Educational Center Co.,Ltd(WREC)
```

## Use-case details

Describe the data being stored onto Filecoin
```
WREA has 30 chapters office in countries around the world. The activities of members of each country were recorded in a video. We will video record in the future. Those videos are a precious cultural heritage of mankind, and they require large-capacity storage.
```

Where was the data in this dataset sourced from?
```
Members of WREA's 30 chapters office around the world.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://www.youtube.com/channel/UC9s5SsR_3ONdgmhUtfqtjpg
These are short introductory videos.

http://www.creckorea.or.kr/bbs/board.php?bo_table=worldrec
Here are short video clips of WREA members from 30 countries around the world.
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes. But there is a license.
```

What is the expected retrieval frequency for this data?
```
often
```

For how long do you plan to keep this dataset stored on Filecoin?
```
It can also be a perpetual storage transaction.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
I will put Korea first. and Asia
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Yes. Adopt online transmission and offline transmission.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We hope to choose a good credit miner. A storage provider (transfer speed, transaction success rate, etc.) that has fewer sector faults and runs nodes reliably.
```

How will you be distributing deals across storage providers?
```
At least one copy of the data for each storage provider, or at least 20% of the total.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Once the data cap is granted, it will start in 1-2 weeks. We spend a lot of money every month on storage space. I would like to get rid of that cost as soon as possible.
```

**Comment by fdd20201015** [comment]
ok

2022년 2월 25일 (금) 오후 9:32, large-datacap-requests[bot] <
***@***.***>님이 작성:

**Comment by Sunnyiscoming** [comment]
> Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
> 
> Yes. But there is a license.
large dataset requirements data are fully public. Please explain the license you are referring to here.


> How will you be distributing deals across storage providers?
> 
> At least one copy of the data for each storage provider, or at least 20% of the total.
Can you describe the storage providers you work with and specify the datacap allocation per storage provider.

**Comment by fdd20201015** [comment]
> > Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
> > Yes. But there is a license.
> 
> large dataset requirements data are fully public. Please explain the license you are referring to here.
> 
> > How will you be distributing deals across storage providers?
> > At least one copy of the data for each storage provider, or at least 20% of the total.
> 
> Can you describe the storage providers you work with and specify the datacap allocation per storage provider.

Are you a Fil+ Notary?

**Comment by Sunnyiscoming** [comment]
I'm working for FIL+ governance team. Any answer?

**Comment by Sunnyiscoming** [comment]
@fdd20201015

**Comment by dkkapur** [comment]
@fdd20201015 I can confirm @Sunnyiscoming is working with us to help do due diligence at scale on LDN applications. 

Regardless, LDN applications are open for due diligence from anyone in the community. It should not matter if they are a notary or an active member of an open community looking to keep the network safe and help identify trustworthy clients to support with DataCap.

**Comment by fdd20201015** [comment]
> @fdd20201015 I can confirm @Sunnyiscoming is working with us to help do due diligence at scale on LDN applications.
> 
> Regardless, LDN applications are open for due diligence from anyone in the community. It should not matter if they are a notary or an active member of an open community looking to keep the network safe and help identify trustworthy clients to support with DataCap.

Thanks for letting me know.

**Comment by fdd20201015** [comment]
> > Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
> > Yes. But there is a license.
> 
It may be viewed by anyone, but may not be downloaded, posted, transmitted to any other site or medium, or used commercially.
It is the difference between seeing and using.
Further details are set out in the site terms and conditions.

> large dataset requirements data are fully public. Please explain the license you are referring to here.
> 
> > How will you be distributing deals across storage providers?
> > At least one copy of the data for each storage provider, or at least 20% of the total.
> 
> Can you describe the storage providers you work with and specify the datacap allocation per storage provider.

SPs are f01096124, f01213742, f01323699, f01412461, f01462978, f01656499, etc. We cannot specify the exact assignments, and we plan to assign them almost identically.

**Comment by dkkapur** [comment]
> It is the difference between seeing and using.
@fdd20201015 can you clarify how you plan on enforcing this in the future? Someone can retrieve this from a storage provider correct? You will just ensure that they do not use it or pretend to own it based on local legal jurisdiction, similar to how copyright would work for an image that can be copied online? 

>  f01096124, f01213742, f01323699, f01412461, f01462978, f01656499
Great to hear you have a plan. Took a quick glance at the list of SPs, and looks like there's a mix here:

- f01096124 - 2 clients served already https://filplus.d.interplanetary.one/miners/f01096124, including Estuary, a known deal engine
- f01213742 - [no Fil+ deals yet](https://filplus.d.interplanetary.one/miners?filter=f01213742), 1 unverified deal
- f01323699 - [no Fil+ deals yet](https://filplus.d.interplanetary.one/miners?filter=f01323699), 53 unverified deals with https://filfox.info/en/address/f3soaazrjuc4os4mtov5miqkqtozzeemvhugamp3och7yuhk6jjndibfdmudtwblsxzjh4cgua4g3aoatqiuxa, a client that has received DataCap in the past and is a relatively well known entity in the SP ecosystem
- f01412461 - [no Fil+ deals yet](https://filplus.d.interplanetary.one/miners?filter=f01412461), 1 unverified deal
- f01462978 - [no Fil+ deals yet](https://filplus.d.interplanetary.one/miners?filter=f01462978), no deals
- f01656499 - [no Fil+ deals yet](https://filplus.d.interplanetary.one/miners?filter=f01656499), no deals

> We hope to choose a good credit miner. A storage provider (transfer speed, transaction success rate, etc.) that has fewer sector faults and runs nodes reliably.
Can you help any additional info here in terms of how you picked the SPs? I think this will make a difference in terms of your answer to the question above re who will be allowed to retrieve the data and how you will ensure the SP complies with your requirements.

**Comment by Sunnyiscoming** [comment]
It is the difference between seeing and using.
@fdd20201015 can you clarify how you plan on enforcing this in the future? Someone can retrieve this from a storage provider correct? You will just ensure that they do not use it or pretend to own it based on local legal jurisdiction, similar to how copyright would work for an image that can be copied online?

For this point, can you provide more explanation?

**Comment by fdd20201015** [comment]
> It is the difference between seeing and using. @fdd20201015 can you clarify how you plan on enforcing this in the future? 
I can't answer the question because I don't understand the content of the question.

>Someone can retrieve this from a storage provider correct? 
I answered 'yes' from the beginning that I could search.

>You will just ensure that they do not use it or pretend to own it based on local legal jurisdiction, similar to how copyright would work for an image that can be copied online?
It is our choice to prevent the use or possession of data using local jurisdictions. why? Interested in a notary public?

> For this point, can you provide more explanation?
I have a lot of questions, so I answer each one individually.

**Comment by Sunnyiscoming** [comment]
Fil+ Large datasets require data should be open, which means your data is stored without encryption and storage providers needs to provide data retrieval, everyone can get these data.

> If this is similar/equivalent to private data, then you will need to likely go down a similar path as https://github.com/filecoin-project/notary-governance/issues/489, working with a specific subset of notaries that can work with you and understand your data and do additional KYC as needed to establish a relationship.

**Comment by fdd20201015** [comment]
@Sunnyiscoming @dkkapur 

> Fil+ Large datasets require data should be open, which means your data is stored without encryption and storage providers needs to provide data retrieval, everyone can get these data.

WREA agrees.
Data stored in FIL+ is open without encryption and provides data retrieval.

**Comment by Sunnyiscoming** [comment]
Could you send an email to filplus@fil.org with your official domain in order to confirm your identity?
Email name should includes the issue id #273.

**Comment by Sunnyiscoming** [comment]
![image](https://user-images.githubusercontent.com/105098820/179921164-d769541a-a803-4992-9d8a-74e498411fcb.png)

**Comment by Sunnyiscoming** [comment]
Have you sent email?

**Comment by dkkapur** [comment]
Closing this one out for now - didn't receive an email and no response here for a few weeks. @fdd20201015 if this is still relevant, please open up another application. Thank you!
