### ISSUE TITLE
[DataCap Application] Speedium Network

### ISSUE THREAD

**Issue by cryptowhizzard** [filecoin-project/filecoin-plus-large-datasets#275]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Speedium Network
- Website / Social Media: www.speedium.nl
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 20PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 300TiB
- On-chain address for first allocation: f17ia7m5mvizrdug3sqtevqw3tifiqvxqr3kdaeuq

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
This datacap request is meant to store the SDSS dataset ( DR15 , DR16 , DR17, DR18, DR19 ) with a total of +/- 2 PB
```

What is the primary source of funding for this project?
```
We have not received any grants for sending data to the network untill now. We aim to utilize this datacap at zero cost, and send data to all active community providers out there on Slack, especially MinerX / enterprise-sp-wg members who are willing and capable of receiving deals.

We participate in slingshot to aim to have some  return on our efforts to get everything working properly and cover the costs of bandwidth, hardware and communicating with providers to keep everything aligned during this phase. We aim to do this in the SP group.
```

What other projects/ecosystem stakeholders is this project associated with?
```
Slingshot, MinerX, enterprise-sp-wp.
```

## Use-case details

Describe the data being stored onto Filecoin
```
SDSS datasets ( DR15 , DR16, DR17, DR18, DR19 )
```

Where was the data in this dataset sourced from?
```
Globus.org
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
globus.org ( SDSS search )
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes. It has the license of https://creativecommons.org/licenses/by/4.0/.
```

What is the expected retrieval frequency for this data?
```
Anyone interested in retrieving this datacet ( a few times we guess )
```

For how long do you plan to keep this dataset stored on Filecoin?
```
1.5 yr.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
All regions.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Offline
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We will contact the MinerX and enterprise-sp-wg members as well as any other providers interested to receive the deals.
```

How will you be distributing deals across storage providers?
```
Evenly across all providers as long as they can handle. If a miner is a notary itself, this notary will receive no more than 20% of the total granted datacap.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes
```

**Comment by galen-mcandrew** [comment]
@dkkapur Is this a slingshot LDN application?

**Comment by dkkapur** [comment]
@galen-mcandrew - yes. We're coordinating on a follow-on grant as part of Restore for the SDSS datasets.

**Comment by galen-mcandrew** [comment]
Checking back for an update here.

**Comment by dkkapur** [comment]
@cryptowhizzard going to close this one out for now. Current plan is to scope into v3.1, for which we will have a separate central LDN application.

**Comment by data-programs** [comment]
<img width="32" alt="KYC" Verified src="https://stable.filplus.storage/images/filplus-kyc-verified-badge.png"/>

This user’s identity has been verified through [filplus.storage](https://filplus.storage)
