### ISSUE TITLE
[DataCap Application]USGS Landsat For Slingshot

### ISSUE THREAD

**Issue by Leviiee** [filecoin-project/filecoin-plus-large-datasets#276]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: USGS Landsat
- Website / Social Media: https://registry.opendata.aws/usgs-landsat/index.html
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):4PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):400TiB
- On-chain address for first allocation:f1glyp2jay5ya2mc2tew5gpbkoebjjn2tb7niajzy

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
It is for Slingshot program. We prepare to archive these data.
```

What is the primary source of funding for this project?
```
From company's account.
```

What other projects/ecosystem stakeholders is this project associated with?
```
No other projects.
```

## Use-case details

Describe the data being stored onto Filecoin
```
It is the longest continuous space-based record of Earth’s land in existence from joint NASA/USGS program. Data is provided for Landsats 1, 2, 3, 4, 5, 7, and 8.
```

Where was the data in this dataset sourced from?
```
These are landsat data downloaded from the USGS, public dataset.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
[doq_qq.zip](https://github.com/filecoin-project/filecoin-plus-large-datasets/files/8177234/doq_qq.zip)
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes. These are landsat data downloaded from the USGS, public dataset.
```

What is the expected retrieval frequency for this data?
```
A few times per year.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
540 days.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Asia.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
We will ship hard drives to storage providers in our city. Or we will post our request on lack and send to some providers via online process.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We are looking for long term partners. We need them with strong storage capacity.
```

How will you be distributing deals across storage providers?
```
3 copies needed. And every provider will be allocated no more than 30% of the datasets.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes. We have downloaded the dataset, so we will start it once datacap is granted.
```

**Comment by Leviiee** [comment]
Hi anyone? Can we get the datacap? The slingshot is coming to the end soon!

**Comment by galen-mcandrew** [comment]
@dkkapur Can you verify this slingshot request?

**Comment by dkkapur** [comment]
@galen-mcandrew great flag - not a valid dataset for Slingshot since several phases ago, and I see that the client plans to work with 3 providers but not allocate more than 30% per ID, which mathematically does not add up. 

Recommend that we close this one out for now and @Leviiee can re-open with a valid dataset and use case in the future.
