### ISSUE TITLE
[DataCap Application] Tribute

### ISSUE THREAD

**Issue by arthive2022** [filecoin-project/filecoin-plus-large-datasets#277]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Tribute
- Website / Social Media: https://en.our-tribute.com/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100TiB
- On-chain address for first allocation: f3qnooswepwaleqmh52pzhhrfetprq333uz5ccluvxcujdbdins5nzchcckqduhcnjboqla7a6rtohjk4pg5na

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Tribute is a one-stop platform that takes care of campaign planning, e-commerce, marketing, sales, and distribution worldwide. We designed to make life easier for brands, creators, influencers, and celebrities looking to go direct-toconsumer with their products and empower them with a suite of tools to manage their company. 

Campaign products produced with brands, creators, influencers, and celebrities deliver good values and messages to the world in a fandom-friendly way. And through public participation content creation, it is possible to satisfy the needs of various people around the world, from individuals to companies.

The platform was designed to be very flexible and enable users to plan their projects from start to finish with ease. We believe in content creation by the masses, and have developed a platform that aims to serve everyone's needs, from ordinary individuals to multi-million dollar companies globally. 

By collaborating with artists on the planning-production of charity campaigns, we intend to create a forward-looking movement in which fans become the subject beyond just donations.And it exists to realize the ideas of creators, entrepreneurs, and everyone with vision.
```

What is the primary source of funding for this project?
```
Our project is being built on its own capital. It is operated with less than 1% of angel investment and equity investors' funds, and recently received investment confirmation from Mirae Asset Investment & Securities (Mirae Asset Securities - Overseas Stock Investment Specialist) (www.miraeasset.com).
```

What other projects/ecosystem stakeholders is this project associated with?
```
Future Asset Financial, which operates and manages IPFS data.
www.futureassetfinancial.com

"AVECS", an experiential marketing agency that connects brands and users.
http://www.avecs.co.kr/

Autorism high-end photo studio "DADA".

"SHHNCO", an online distribution and marketing platform company.
```

## Use-case details

Describe the data being stored onto Filecoin
```
Database data from all of our core industries, management systems, platforms and commercial advertising of various campaigns currently in operation, numerous contents from individuals to companies, and projects to be carried out by numerous creators and artists will be stored.
```

Where was the data in this dataset sourced from?
```
These are the data inside the platform we already operate. It will be a platform of good value with one-stop all processes from campaigns planned and produced with artists to marketing and sales, as well as content with brands, creators, influencers, and celebrities together.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
It is our official YouTube account. You can watch videos collaborating with famous artists.

 https://www.youtube.com/channel/UCdTFzLwS0xfzqB7NMlOX0bw
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes. The data we produce is perfectly public data. Many users and artists will participate in the planning and production of charity campaigns together, creating a forward-looking movement in which numerous fans become the main body.
```

What is the expected retrieval frequency for this data?
```
We are designing the platform targeting the participation of many users. Therefore, while those users create content within our platform, plan and produce campaign concepts, our data will be constantly searched.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
The data we produce and store is deeply related to our sales. Therefore, we want our stored data to be kept permanently, and if possible, we want to use a storage method(FileCoin) to preserve it permanently.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
We plan to store it around the world, mainly in Korea, beyond Asia. The platform we are preparing for is being planned for global. Therefore, data will be generated around the world, not in a structure in which data is generated in a specific country.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Data generated after datacap allocation will be quickly distributed online to storage providers. Before datacap allocation, we will copy and deliver our own data to miners.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
Through the Filecoin Reputation System (filrep.io), we will choose a miner that enables long-term cooperation, stores data more securely, and has a stable data transmission rate.
```

How will you be distributing deals across storage providers?
```
It will be distributed evenly on/offline.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
We are already conducting cloud funding with small business owners. In addition, transactions can be made immediately through the ongoing blockchain project mentioned above. Storing datacap for allocated data will help store more data if collateral can be reduced. In addition, if we can receive datacap, post our service on FileCoin, and promote our platform in the community, it will help us save it on FileCoin.
```

**Comment by Sunnyiscoming** [comment]
@arthive2022 ![image](https://user-images.githubusercontent.com/105098820/170455302-1e372bd8-9251-40d2-9cfd-666f10c9d17f.png)
1. Some pages on the official website are broken.
2. Please provide more data sources to prove that you already have 5PB of data.  
There are only 15 video on https://www.youtube.com/channel/UCdTFzLwS0xfzqB7NMlOX0bw, the youtube channel provided.

**Comment by Sunnyiscoming** [comment]
Any update here?

**Comment by dkkapur** [comment]
@arthive2022 I'm going to close this issue for now since we have not heard in the last 2 weeks. Please ping back and let us know if this is still relevant.
