### ISSUE TITLE
[DataCap Application]EpikProtocol

### ISSUE THREAD

**Issue by Sigrid-Epik** [filecoin-project/filecoin-plus-large-datasets#281]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: EpikProtocol
- Website / Social Media: http://[www.epik-protocol.io](http://www.epik-protocol.io/) 
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100TiB
- On-chain address for first allocation: f1ffbtksiso5za73pypuxbxznng6rdv64nbihdtba

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer. _

## Project details

Share a brief history of your project and organization.
```
EpiK Protocol envisions building a decentralized KG using blockchain technology with trustable storage, incentives, governance and financial capabilities; this creates a trusted, multi-party collaboration platform where all trusted contributors are rewarded fairly while preserving human knowledge at an affordable rate permanently, expanding the horizons of today's AI, and will usher in the era of cognitive intelligence. Now we have approximate 920TiB data and decentralized storage would perfer to storage provider. (≥5 copies)
You can reach us via below methods:
twitter: https://twitter.com/EpikProtocol
medium:  https://epikprotocol.medium.com
Email: Sigrid@epik-protocol.io
GitHub: @EpiK-Protocol
```

What is the primary source of funding for this project?
```
From our own account.
```

What other projects/ecosystem stakeholders is this project associated with?
```
None.
```

## Use-case details

Describe the data being stored onto Filecoin
```
These data is mainly images about 10,000 hours of virtual road vedio and images which are marked the shape of objects with 100% accuracy using simulation algorithms by domain expert. 
```

Where was the data in this dataset sourced from?
```
This file is verified and uploaded by our active domain experts from community. Experts aims to contribute AI data in the domain of smart transport to EpiK Protocol network. Please refer link for detail https://youtu.be/NkAY9x8OUJU
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
![depth](https://user-images.githubusercontent.com/100819040/157023639-e70d33d7-a945-41f9-a114-703afcef0bc9.png)
![panorama](https://user-images.githubusercontent.com/100819040/157023646-0db83de6-3b3b-46ee-a191-01e191a719b7.png)
![segmentation](https://user-images.githubusercontent.com/100819040/157023651-3f9a8922-5359-4edf-b29b-70e594129907.png)

[smart_transport_cases_scene_highway.zip](https://github.com/filecoin-project/filecoin-plus-large-datasets/files/8197227/smart_transport_cases_scene_highway.zip)

```
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes. We confirm it.
```

What is the expected retrieval frequency for this data?
```
These data was simulated for search and comparison. Maybe twice a year for retrieval.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
1-2 years
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Mainly Asia.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
We prefer choosing offline data transfer process. Or we’ll find providers from the community for making deals. 
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We have to consider 2 points.
1.   Stable or safe transfer.
2.   High speed internet.
```

How will you be distributing deals across storage providers?
```
1. ≥ 5 copies for my dataset
2. Offline deal for the SPs in the same city.(90%)
3. Less online deal for SPs in different cities/regions.(≤10%)
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes. Data transfer plan or my techman need some API code from Filecoin engineer
```

**Comment by galen-mcandrew** [comment]
## Multisig Notary requested
#### Total DataCap requested 
> 5PiB
#### Expected weekly DataCap usage rate 
> 100TiB

**Comment by Sigrid-Epik** [comment]
Thanks! @galen-mcandrew

**Comment by Sigrid-Epik** [comment]
Thanks! @galen-mcandrew Waiting for the datacap.

**Comment by Fenbushi-Filecoin** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebl24vic662qquumvfothhcslhzaysn45kv2hpcr2c4cl3qay4ukc 
#### Address 
> f1ffbtksiso5za73pypuxbxznng6rdv64nbihdtba
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1yqydpmqb5en262jpottko2kd65msajax7fi4rmq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebl24vic662qquumvfothhcslhzaysn45kv2hpcr2c4cl3qay4ukc

**Comment by TimWilliams00** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaqlcn4mgpod6wwpogy43xi7ci7yrt4h7hj5lpoaszbv474xhzz7c 
#### Address 
> f1ffbtksiso5za73pypuxbxznng6rdv64nbihdtba
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1fkxkfxgopjf3ufnfg5i3m6qlwf73kp4w5zz7nnq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaqlcn4mgpod6wwpogy43xi7ci7yrt4h7hj5lpoaszbv474xhzz7c

**Comment by TimWilliams00** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebuy2hynswoddusj2qijd6373thdelw6j5xix723n22yd3fshuzyy 
#### Address 
> f1ffbtksiso5za73pypuxbxznng6rdv64nbihdtba
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1fkxkfxgopjf3ufnfg5i3m6qlwf73kp4w5zz7nnq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebuy2hynswoddusj2qijd6373thdelw6j5xix723n22yd3fshuzyy

**Comment by rayshitou** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecn2yf3vtlebnehysrsy7qu26e6tobbqzxavvdlvcq4ggx6swb5si 
#### Address 
> f1ffbtksiso5za73pypuxbxznng6rdv64nbihdtba
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f136bz32l2hlyad4npmfg5dngcdw3jk3tpcpoz2ja
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecn2yf3vtlebnehysrsy7qu26e6tobbqzxavvdlvcq4ggx6swb5si

**Comment by Sigrid-Epik** [comment]
@Fenbushi-Filecoin @TimWilliams00 @rayshitou Thanks for your approval! But I have not got the Datacap yet. Should I wait for it? Or what can I do next?

**Comment by rayshitou** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceajssw5drvm6vns4i75m5btshjvswgihkmqmkpjdwf56tyshwn6li 
#### Address 
> f1ffbtksiso5za73pypuxbxznng6rdv64nbihdtba
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f136bz32l2hlyad4npmfg5dngcdw3jk3tpcpoz2ja
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceajssw5drvm6vns4i75m5btshjvswgihkmqmkpjdwf56tyshwn6li

**Comment by swatchliu** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceanpefpwx76evdyvimlw6hcfcvcvtbnz3niszy5yjt37bpqpqdozw 
#### Address 
> f1ffbtksiso5za73pypuxbxznng6rdv64nbihdtba
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1yh6q3nmsg7i2sys7f7dexcuajgoweudcqj2chfi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceanpefpwx76evdyvimlw6hcfcvcvtbnz3niszy5yjt37bpqpqdozw

**Comment by galen-mcandrew** [comment]
@fabriziogianni7 wondering if we can investigate this issue. Seeing messages land, but looks like client is not getting any DataCap.

**Comment by fabriziogianni7** [comment]
@galen-mcandrew

The client have used 99.91 TiB as shown here ---> https://filplus.d.interplanetary.one/clients?filter=f1ffbtksiso5za73pypuxbxznng6rdv64nbihdtba
That means he actually received the DataCap

**Comment by Fenbushi-Filecoin** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceararriqgwqihth3xyg6gazqq7zahyv3xat55j5iopa3d3iy6eg3i 
#### Address 
> f1ffbtksiso5za73pypuxbxznng6rdv64nbihdtba
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1yqydpmqb5en262jpottko2kd65msajax7fi4rmq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceararriqgwqihth3xyg6gazqq7zahyv3xat55j5iopa3d3iy6eg3i

**Comment by swatchliu** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb2eyhu7dgiuw72ukl4t4rmp2fzstkgb62vipauniavrnsml45gr2 
#### Address 
> f1ffbtksiso5za73pypuxbxznng6rdv64nbihdtba
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1yh6q3nmsg7i2sys7f7dexcuajgoweudcqj2chfi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb2eyhu7dgiuw72ukl4t4rmp2fzstkgb62vipauniavrnsml45gr2

**Comment by rayshitou** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceapod5v6u6khxqsg2uauayvqevvkjrmp7nincm5r3dbfnmoidsewk 
#### Address 
> f1ffbtksiso5za73pypuxbxznng6rdv64nbihdtba
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f136bz32l2hlyad4npmfg5dngcdw3jk3tpcpoz2ja
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceapod5v6u6khxqsg2uauayvqevvkjrmp7nincm5r3dbfnmoidsewk

**Comment by TimWilliams00** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceasx5rjic3wvwv2xfnmgoe3s4l76xzikpfiyii6enartxsldztcou 
#### Address 
> f1ffbtksiso5za73pypuxbxznng6rdv64nbihdtba
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1fkxkfxgopjf3ufnfg5i3m6qlwf73kp4w5zz7nnq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceasx5rjic3wvwv2xfnmgoe3s4l76xzikpfiyii6enartxsldztcou

**Comment by Sigrid-Epik** [comment]
@rayshitou @TimWilliams00 Hi notaries, actually I've got only 50TiB instead of 200TiB.

**Comment by swatchliu** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebau7we2fhj3p7zzgumudb7wfmwiqxy4vqsb7net7ziwgq3fhp4f4 
#### Address 
> f1ffbtksiso5za73pypuxbxznng6rdv64nbihdtba
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1yh6q3nmsg7i2sys7f7dexcuajgoweudcqj2chfi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebau7we2fhj3p7zzgumudb7wfmwiqxy4vqsb7net7ziwgq3fhp4f4

**Comment by TimWilliams00** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceatox4e4yvfyq5clwlbobcuo5hgmp4ntgf6zaiwtfkr7exexjfyse 
#### Address 
> f1ffbtksiso5za73pypuxbxznng6rdv64nbihdtba
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1fkxkfxgopjf3ufnfg5i3m6qlwf73kp4w5zz7nnq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceatox4e4yvfyq5clwlbobcuo5hgmp4ntgf6zaiwtfkr7exexjfyse

**Comment by MRJAVAZHAO** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec7yobhz5ketplauhjqegdc4tg2t5mq4n7a7zoam3p7by4cmuswbu 
#### Address 
> f1ffbtksiso5za73pypuxbxznng6rdv64nbihdtba
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f14gme3f52prtyzk6pblogrdd6b6ivp4swc6qmesi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec7yobhz5ketplauhjqegdc4tg2t5mq4n7a7zoam3p7by4cmuswbu

**Comment by swatchliu** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacea7isx4bxnpsgtomiagczkilr2rdirm4lbtbgn574pj5ofdhloxb2 
#### Address 
> f1ffbtksiso5za73pypuxbxznng6rdv64nbihdtba
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1yh6q3nmsg7i2sys7f7dexcuajgoweudcqj2chfi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacea7isx4bxnpsgtomiagczkilr2rdirm4lbtbgn574pj5ofdhloxb2

**Comment by TimWilliams00** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebelw7u6xzsjzzmakzol7mplpbppfudj3yutlsnitla5wmnrufcru 
#### Address 
> f1ffbtksiso5za73pypuxbxznng6rdv64nbihdtba
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1fkxkfxgopjf3ufnfg5i3m6qlwf73kp4w5zz7nnq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebelw7u6xzsjzzmakzol7mplpbppfudj3yutlsnitla5wmnrufcru

**Comment by DarnellWashington** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecexlqfqndueblyj3zcbonfh4azm4sf3vieimxkjfv3kkru6clmjc 
#### Address 
> f1ffbtksiso5za73pypuxbxznng6rdv64nbihdtba
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1bjdcjxha3ldcstw5zmvkyu3r2p5x2bsm745kgsi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecexlqfqndueblyj3zcbonfh4azm4sf3vieimxkjfv3kkru6clmjc

**Comment by swatchliu** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecdjlbcgvi73p5f7xknlfbeezlv4e4mhikrzopzdssenopjbsef4m 
#### Address 
> f1ffbtksiso5za73pypuxbxznng6rdv64nbihdtba
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1yh6q3nmsg7i2sys7f7dexcuajgoweudcqj2chfi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecdjlbcgvi73p5f7xknlfbeezlv4e4mhikrzopzdssenopjbsef4m

**Comment by swatchliu** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebeuznhd2xdx3e4vqstdfziaiaoqebcgnbtycpl53wrpwxyqruquk 
#### Address 
> f1ffbtksiso5za73pypuxbxznng6rdv64nbihdtba
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1yh6q3nmsg7i2sys7f7dexcuajgoweudcqj2chfi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebeuznhd2xdx3e4vqstdfziaiaoqebcgnbtycpl53wrpwxyqruquk

**Comment by TimWilliams00** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb735dwi6jrvknn7v6wwjifcmj745sf5uufphewnbd4yahfgp7ea2 
#### Address 
> f1ffbtksiso5za73pypuxbxznng6rdv64nbihdtba
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1fkxkfxgopjf3ufnfg5i3m6qlwf73kp4w5zz7nnq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb735dwi6jrvknn7v6wwjifcmj745sf5uufphewnbd4yahfgp7ea2

**Comment by swatchliu** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb4jzziyprtjm5acvcnsvprneq3f2l62qsny4kqohffykyuprycxk 
#### Address 
> f1ffbtksiso5za73pypuxbxznng6rdv64nbihdtba
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1yh6q3nmsg7i2sys7f7dexcuajgoweudcqj2chfi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb4jzziyprtjm5acvcnsvprneq3f2l62qsny4kqohffykyuprycxk

**Comment by Sigrid-Epik** [comment]
@kevzak Ok! I've done!

**Comment by MRJAVAZHAO** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebg2ir7k6imot5q4corpp6bghpptfibsxpofxd4ttktkm2vkye5dg 
#### Address 
> f1ffbtksiso5za73pypuxbxznng6rdv64nbihdtba
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f14gme3f52prtyzk6pblogrdd6b6ivp4swc6qmesi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebg2ir7k6imot5q4corpp6bghpptfibsxpofxd4ttktkm2vkye5dg

**Comment by 1475Notary** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacea7gxwjebrjnhsl56iwo62bj26in2jhpegt7awigrlecjwjk7ugp4 
#### Address 
> f1ffbtksiso5za73pypuxbxznng6rdv64nbihdtba
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1ofq4mngy7ggcp755pfquq2gphjjnlydolf6awtq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacea7gxwjebrjnhsl56iwo62bj26in2jhpegt7awigrlecjwjk7ugp4

**Comment by BigD-Exchange** [comment]
@Sigrid-Epik Hi! Great to see you have gotten approval for DataCap. If you are looking for more storage providers to store these data or have any questions, please visit #bigdata-exchange on Filecoin Slack or reply here. 

We have strong demand from a diverse group of SPs, who are actively looking to onboard more data.

**Comment by PluskitOfficial** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecnihippgaamvrc6ubl7ozaiupgejwf5mr4f3ybpjaagrvdhmakfs 
#### Address 
> f1ffbtksiso5za73pypuxbxznng6rdv64nbihdtba
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1tgnlhtcmhwipfm7thsftxhn5k52velyjlazpvka
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecnihippgaamvrc6ubl7ozaiupgejwf5mr4f3ybpjaagrvdhmakfs

**Comment by BlockMakeronline** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecceldkhgekshqjb3xomrkuf4d2q4tdrq7r3qmho4dldonxeptbcy 
#### Address 
> f1ffbtksiso5za73pypuxbxznng6rdv64nbihdtba
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1o3twrcpwjtpcd4q36lpq4qmy2qfbgtyy5h6tsty
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecceldkhgekshqjb3xomrkuf4d2q4tdrq7r3qmho4dldonxeptbcy
