### ISSUE TITLE
[DataCap Application]Dingdingpai

### ISSUE THREAD

**Issue by Dingding-pai** [filecoin-project/filecoin-plus-large-datasets#286]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Dingdingpai
- Website / Social Media: website:https://www.ddpai.com       Sina Weibo:https://weibo.com/ddpai         WeChat public account:dingdingpai
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5 PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100TiB
- On-chain address for first allocation: f1tfoiunmztymuipqnstdluboioitk4kw2kvg6pna

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Founded in 2013, Dingdingpai is committed to enriching human travel and lifestyle with innovative technologies. Through machine vision, artificial intelligence and 5G interconnection, it empowers smart travel and shares interesting life.

As a leading company in the Internet of Vehicles, Dingdingpai has more than 5 million end users, and will generate a large amount of video data during travel, which requires a large amount of storage and analysis.
```

What is the primary source of funding for this project?
```
Our current main sources of funding are two-fold:
1. The company's business income.
2. Company financing.
```

What other projects/ecosystem stakeholders is this project associated with?
```
DDDIPAI has teamed up with Huawei, Honor, Alibaba and other industry ecosystems to provide users with deeply integrated multi-scenario application services; and has helped SAIC, Shouqi, Geely, Volvo, T3 Travel, Xiaopeng Motors and many others Enterprises upgrade smart cockpits and smart travel to enrich driving experience and improve operational efficiency; at the same time, they cooperate with industry partners such as AutoNavi Maps, Sogou Maps, and Baidu Maps to create a more intuitive and convenient navigation experience.
```

## Use-case details

Describe the data being stored onto Filecoin
```
The data stored on Filecoin is currently basically open data of business and video.
```

Where was the data in this dataset sourced from?
```
It mainly comes from a large amount of video data generated during travel and the company's product marketing and promotion video data.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://video.weibo.com/show?fid=1034:4726555847622659         
https://video.weibo.com/show?fid=1034:4711740647342084
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
We confirm that this is a publicly retrievable public dataset.
```

What is the expected retrieval frequency for this data?
```
Search once every six months
```

For how long do you plan to keep this dataset stored on Filecoin?
```
We are currently tentatively set for 730 days, and we need to adjust the specific storage period according to storage needs.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
North America and Asia
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
At present, we are transmitting online through the designated platform, and we are ready for the offline transmission process. We can choose the transmission method according to the needs of miners
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We will choose miners with verified data experience and a legitimate company background
```

How will you be distributing deals across storage providers?
```
We will make a table to score miners, and confirm the distribution ratio according to the score.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
We are very willing to communicate with officials and notaries
```

**Comment by Dingding-pai** [comment]
Hi, any update?

**Comment by Sunnyiscoming** [comment]
@Dingding-pai 
1.What is the name of your online storage platform? Is the platform yours or someone else's? If it's someone else's, what is your relationship?
2. Are you interested in cooperating with storage providers? If yes, please list them. If not, please explain how to find them.

**Comment by Dingding-pai** [comment]
@Sunnyiscoming Hello         
1. We did not mention that we have an online storage platform, we only mentioned that the data we transmit is transmitted through our own platform.
2. Some of our data will be allocated to storage providers, who listed on official web. And some will be allocated through online deals.
Also, I see your account is a new one? Are you a new notary?

**Comment by Sunnyiscoming** [comment]
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/273
Deep has clarified my identity. Please check it.

**Comment by Sunnyiscoming** [comment]
You said you would choose online transfer. Therefore, I would like to confirm with you whether the online transmission platform has been identified.

**Comment by Dingding-pai** [comment]
@Dingding-pai Hello,Part of our data  is stored in web2's centralized platform for data storage, and sp has an account to download by themselves.thank you！

**Comment by galen-mcandrew** [comment]
Can you email [filplus@fil.org](mailto:filplus@fil.org) with your official work email so we can share this with notaries as a form of proof that you represent this organization?

**Comment by galen-mcandrew** [comment]
Due to no reply from client, we are closing this issue for now. When ready, please reopen or submit a new request here: https://plus.fil.org/ldn-application
