### ISSUE TITLE
[DataCap Application]Beijing Hualu Baina Film and Television Co., Ltd.

### ISSUE THREAD

**Issue by Beijing-Hualubaina** [filecoin-project/filecoin-plus-large-datasets#287]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Beijing Hualu Baina Film and Television Co., Ltd.
- Website / Social Media:http://www.hualbn.com/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):5 PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):100TiB
- On-chain address for first allocation:f1dpbuhncsehuclqupynycz5yfovc4s3zjoya6z2a

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Our organization name is Beijing Hualu Baina Film and Television Co., Ltd. It is an all-round professional film and television company with film and television investment, management, planning, production and marketing capabilities. Combining the strategies to carry out efficient commercial organization and operation, and concurrently operate related cultural industries, it has large-scale production capabilities.
```

What is the primary source of funding for this project?
```
 Commercialization income, etc.
```

What other projects/ecosystem stakeholders is this project associated with?
```
none
```

## Use-case details

Describe the data being stored onto Filecoin
```
The data stored on Filecoin is publicly available data in the format of video, picture, audio, etc.
```

Where was the data in this dataset sourced from?
```
Mainly from company videos, pictures, audios.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
http://m.v.qq.com/x/cover/m/mzc00200mu0cw18/d0041exs3x7.html?url_from=share&second_share=0&share_from=copy&pgid=page_detail&mod_id=mod_toolbar_new
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes, it is.
```

What is the expected retrieval frequency for this data?
```
The retrieval frequency is relatively low.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
We intend to store in Filcoin for two years.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Asia , NA and Europe
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
We have plans for offline transfers for transferring large files. However, considering the portability, online transmission is still the main method.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We will check whether the miners' recent on-chain transaction activities are abnormal first, and then decide the miners to cooperate with.
```

How will you be distributing deals across storage providers?
```
We mainly distribute data to miners online. If there are miners close to us, we will use offline transmission to transfer large files.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
we have enought funds to support it
```

**Comment by Beijing-Hualubaina** [comment]
What can we do to push the progress?

**Comment by galen-mcandrew** [comment]
Please send an email from the official business HBN email domain to [filplus@fil.org](mailto:filplus@fil.org) to verify your association with this company.

**Comment by dkkapur** [comment]
@Beijing-Hualubaina I believe we are still waiting for the email. Please reach out when convenient. Thanks!

**Comment by galen-mcandrew** [comment]
Due to no reply from client, we are closing this issue for now. When ready, please reopen or submit a new request here: https://plus.fil.org/ldn-application
