### ISSUE TITLE
[DataCap Application]Interhash

### ISSUE THREAD

**Issue by Inter-hash** [filecoin-project/filecoin-plus-large-datasets#288]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Interhash
- Website / Social Media: Website：interhash.top    telegram:https://t.me/InterhashOfficial    Twitter: https://twitter.com/inter_hash     Facebook: https://www.facebook.com/jiadong.shao.33     Weibo: https://weibo.com/u/7358303999?refer_flag=1005050010_      Wechat:Interhash
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):5 PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):100TiB)
- On-chain address for first allocation: f1hp6dqonu5uurzaszl3bcgb5yyl6xvomogsfo6py

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Interhash founded in 2018, it is a service provider that provides one-stop BTC mining and cloud computing solutions around crypto mining, and provides comprehensive mining consulting services. Its business covers: mining funds, BTC/ETH mining machine procurement, Filecoin combined mining, mining farm investment, equipment hosting, minier financial leasing, mortgage loan, hedging, etc.
At present, the development of computing power interconnection has begun to take shape, the number of mining machines under management has reached 40,000+, and the scale of net assets under management has reached 300 million yuan. Service customers cover many countries around the world.
```

What is the primary source of funding for this project?
```
Company business income.
```

What other projects/ecosystem stakeholders is this project associated with?
```
Interhash has in-depth cooperation with Canaan Technology, Bitmain, Whatsminer, GSR, F2Pool, Poolin, 51miner,  Mini Yunzhi, 1TMine, and Bit Blue Whale , we provide users with deeply integrated multi-scenario application services and help.
```

## Use-case details

Describe the data being stored onto Filecoin
```
The data stored on Filecoin is mainly data of mining machines.
```

Where was the data in this dataset sourced from?
```
Mainly from partners, such as miner data and mining pool data.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://play.yunxi.tv/pages/ebef8d18df22493cb187a978f33d2e71?openId=oY3TsvvjLhBjP6aDg5LNwPd-q_oA#/
https://news.huoxing24.com/20191113000542278379.html
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
We confirm that this is a publicly retrievable public dataset.
```

What is the expected retrieval frequency for this data?
```
Search once every six months
```

For how long do you plan to keep this dataset stored on Filecoin?
```
We tentatively store for three years
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Southeast Asia, North America
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
It is mainly based on offline data transmission, and in certain cases, it will be transmitted online.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We have cooperative miners who can guarantee transaction and service quality
```

How will you be distributing deals across storage providers?
```
According to the miners we cooperate with, if it is close to us, we will transmitted offline, and if it is far away, we will transmitted online.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, we have
```

**Comment by Sunnyiscoming** [comment]
@Inter-hash Hi
Website, Twitter, Data sample can not be opened. Please check it.
> Website：interhash.top

![image](https://user-images.githubusercontent.com/105098820/171375172-f26ef0e1-d000-429e-827a-679ba6f22dbc.png)

> Twitter: https://twitter.com/inter_hash

![image](https://user-images.githubusercontent.com/105098820/171375056-3f7c332c-f42b-4ec8-b7b8-97ef72e81b97.png)

> https://play.yunxi.tv/pages/ebef8d18df22493cb187a978f33d2e71?openId=oY3TsvvjLhBjP6aDg5LNwPd-q_oA#/
> https://news.huoxing24.com/20191113000542278379.html

![image](https://user-images.githubusercontent.com/105098820/171376047-4176c436-71b9-4f1a-9062-6426539dc171.png)
![image](https://user-images.githubusercontent.com/105098820/171376135-7818c031-adcb-461c-97d9-8a91ad181d89.png)

**Comment by Sunnyiscoming** [comment]
Any update? @Inter-hash

**Comment by dkkapur** [comment]
Closing this one for the time being. @Inter-hash please let us know if it should be re-opened if it is still relevant since we have not heard from you.
