### ISSUE TITLE
[DataCap Application] Klaywatch

### ISSUE THREAD

**Issue by ejnklf2351z** [filecoin-project/filecoin-plus-large-datasets#29]
# Large Dataset Notary Application

To apply for a DataCap allocation for your dataset, please fill out the following information.

## Core Information
- Organization Name: Klaywatch
- Website / Social Media: [https://klaywatch.com](https://klaywatch.com)
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 1PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 400GiB
- On-chain address for first allocation: f3r4catwzlk6jfau54tsnp6qesf47rhcu5kesn5v7jatzwrsgqc4tagftwpignluubpohyikhqmgmwm6kuebkq

_Please respond to the questions below in pargraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

## Project details

Share a brief history of your project and organization.
```
We are a developer group of 7 blockchain developers.
We are mainly interested in blockchain service, NFT service, Defi, etc. Currently concentrating on technology development, we launched a utility service called Klaywatch for Defi, which is operated based on Klay, Korea's most promising blockchain network.
```

What is the primary source of funding for this project?
```
We are currently operating through our own funding.
```

What other projects/ecosystem stakeholders is this project associated with?
```
Klaywatch is a service runned by our own. We have plans to cooperate with various Defi projects and NFT projects in the future. Currently, we are communicating with promising projects in Korea.
```

## Use-case details

Describe the data being stored onto Filecoin
```
Klaywatch holds all user-based data generated by the defi service, such as deposit, withdrawal, and swap history of users created in klayswap defi. We also have snapshots of users' asset information every day, and we need to store them in secure ipfs.
```

Where was the data in this dataset sourced from?
```
Defi data is generated every day, and Klaywatch collects it every day through the defi blockchain. Klaywatch provides quality defi service to users by classifying and organizing unspecified Defi transaction details by user address.
```

Can you share a sample of what is in the dataset? A link to a file, an image, a table, etc., are good examples of this. 
```
Service : https://klaywatch.com
Data sample : https://drive.google.com/drive/u/3/folders/13mBgikJUzWe09J6FKZSm6E8GYwsv9H3D
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
All of the data we have is open to anyone, and these data are data stored in the blockchain that are well sorted and organized by user address. Because it is already open data, there is no problem providing it publicly.
```

What is the expected retrieval frequency for this data?
```
Klaywatch is an essential utility service for those who use klay-based defi service. We are generating 100,000 PV per day, and we are recording and inquiring transaction details that occur in about 9000 wallets. It is expected that the search frequency will increase as Defi is more activated.
```

For how long do you plan to keep this dataset stored on Filecoin? Will this be a permanent archival or a one-time storage deal?
```
We wanna use Filecoin storage permanently. We hope to use Filecoin as the main storage for the Klaywatch service.
```

## DataCap allocation plan

In which geographies do you plan on making storage deals?
```
First, we plan to make deals mainly in the Asian region (Korea and China). And, of course, we have plans to make deals for other continents.
```

What is your expected data onboarding rate? How many deals can you make in a day, in a week? How much DataCap do you plan on using per day, per week?
```
We generate user data every day. We have a plan to create deals every week and store data. We will make about 50GiB of data daily and about 400 GiB per week and store it using Data Cap.
```

How will you be distributing your data to miners? Is there an offline data transfer process?
```
We are developing to be able to create deals and store data directly on Klaywatch. Also, we will work with miners who can provide us with optimal storage. Create a separate one so that we can send that data offline before automation.
```

How do you plan on choosing the miners with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We will work with miner who has built stable storage and secure IDC center. Also we consider Miners who do the retrieval function well. Since our service will also provide data retrieval service in the future, we will continue to work with miner who has sustainable and stable operational capabilities in terms of operation.
```

How will you be distributing data and DataCap across miners storing data?
```
We will work with 4 or 5 miners and we will work with them to create a service to store and retrieve our data.
```

**Comment by dkkapur** [comment]
@ejnklf2351z - - thanks for submitting your application for a large DataCap allocation to the Fil+ Notaries! As the Notaries and the Fil+ community carries out the due diligence process on your application - we'd love to invite you to participate in the Fil+ Community Governance Call. We're inviting clients applying for large amounts of DataCap to come present and field questions during the second half of each community call to help enable the process. The next set of calls are actually today - Tues Aug 31 at 3pm and 11pm UTC, information to participate can be found here: https://github.com/filecoin-project/notary-governance/issues/221. Looking forward to seeing you there or perhaps at the next one on Sept 14!

**Comment by IreneYoung** [comment]
Hi @ejnklf2351z, I have interest in approving this application too. 

But I wonder why you need 1 PiB DataCap. Is it too much? To my knowledge, the DeFi data is not that huge. So could you please provide more details of how much generated DeFi data is there on your platform? It would be better if you could show us something to prove that you are in need of 1 PiB DataCap to store your data in the near future. Thanks!

**Comment by ejnklf2351z** [comment]
@IreneYoung Thanks for your interest in our project.

 Recording Defi's transaction details is not huge data, as you say. These data are text-level data. But We are not aiming to simply leave transaction details. We have a plan to become utility service of comprehensive ecosystem in Defi sector.
 This service is a comprehensive dashboard system related to DeFi. As various Defi services are launched like now, the amount of data that Defi users want to store increases and becomes more important. And this data needs to be created as a snapshot. For example, NFTs can be issued based on various information, such as real-time balance history generated in the Defi area. Although these NFTs are not used commercially, can be used as if the bank uses transaction details and real-time balance details for a variety of services and Individuals use a variety of information for for their own private contracts. These data should be left as snapshots and stored in IPFS at the same time.
 We plan to record a lot of information that can be of value to users of the Defi ecosystem, such as the balance ranking, real-time chart history, and large balance movement of each different Defi project and create it as a snapshot & NFT. We expect that as Defi services become more diverse and user-friendly, the data we need to store to create meaningful information will also increase. This is why we applied for a substantial DataCap.

We thank you once again for your interest in this project.

**Comment by galen-mcandrew** [comment]
## Multisig Notary requested
#### Total DataCap requested 
> 1PiB
#### Expected weekly DataCap usage rate 
> 400GiB

**Comment by MegTei** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced6iajsnpe4y7kalc5bygh2urhggkct7ofn7e4ifbrutyj5c6iaxw 
#### Address 
> f3r4catwzlk6jfau54tsnp6qesf47rhcu5kesn5v7jatzwrsgqc4tagftwpignluubpohyikhqmgmwm6kuebkq
#### Datacap Allocated
> 200GiB
#### Signer Address
> f1ystxl2ootvpirpa7ebgwl7vlhwkbx2r4zjxwe5i
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced6iajsnpe4y7kalc5bygh2urhggkct7ofn7e4ifbrutyj5c6iaxw

**Comment by IreneYoung** [comment]
@ejnklf2351z Hi, glad to see that you moved forward with the request progress. I support you but I just can't sign it because our notary address doesn't exist in this Multisig Notary address f01322670 above. Anyway, hope some other notaries could review and sign the request for you. Good luck.

**Comment by dannyob** [comment]
I'm happy to support this for the initial allocation: I'd encourage you to look to a wide range of storage providers (especially those outside your region) in distributing the initial datacap. Thanks for participating!

**Comment by galen-mcandrew** [comment]
@fabriziogianni7 This one is not showing up in the app for some reason, and still has pending txID0 for 200GiB

**Comment by Reiers** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecxlqi7sowb4qcpsyfzs6thwfbwirsqiazemnqmr5sd44ubaury2y 
#### Address 
> f3r4catwzlk6jfau54tsnp6qesf47rhcu5kesn5v7jatzwrsgqc4tagftwpignluubpohyikhqmgmwm6kuebkq
#### Datacap Allocated
> 200GiB
#### Signer Address
> f1oz43ckvmtxmmsfzqm6bpnemqlavz4ifyl524chq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecxlqi7sowb4qcpsyfzs6thwfbwirsqiazemnqmr5sd44ubaury2y

**Comment by ClarkYin5566** [comment]
Hi @ejnklf2351z , I am also applying for datacap but still waiting for review. I would like to discuss with you how to proceed and how to promote the development of real data. If possible, please leave your email or contact me: mr.clark.yin@gmail.com

**Comment by Sunnyiscoming** [comment]
Hi @ejnklf2351z 
Are there any problems with using datacap?

**Comment by Sunnyiscoming** [comment]
checker:manualTrigger
