### ISSUE TITLE
[DataCap Application] ShenSuanYun Co.,ltd

### ISSUE THREAD

**Issue by gnasnik** [filecoin-project/filecoin-plus-large-datasets#291]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: ShenSuanYun Co.,ltd
- Website / Social Media: http://dmdb_dev.sspool.cn/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 300TiB
- On-chain address for first allocation: f1rhqvznwmxigssjn22xsyb7wywxnhyfawiwm4xgi

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
ShenSuanYun  Co.,ltd founded in September 2015, is a professional supply block chain service provider. 
The decentralized Materials Database (DMDB) cooperated with Harbin Institute of Technology will carry out cooperation in the field of blockchain, IPFS distributed storage and other fields to empower ShenZhen Nanshan blockchain industry development.
```
What is the primary source of funding for this project?
```
Business income.
```

What other projects/ecosystem stakeholders is this project associated with?
```
we have related with Etherem network.
```

## Use-case details

Describe the data being stored onto Filecoin
```
The data stored on Filecoin is currently basically the application data and the publicly available data stored on the client project side chain.
```

Where was the data in this dataset sourced from?
```
Mainly from on-chain data of multiple blockchains and application data on projects.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://ipfs.io/ipfs/QmRnSGnMNfTkJkG88bCQefQvkRjeS5mFRgbVWQciwzWzoR?filename=5fc70f44c78412255c8bb210c7fafa3e.txt
https://ipfs.io/ipfs/QmQGTcDDu7mQ3Szuw6nyhbPL4BhVA2SE5jEfn3NES1Y81n?filename=1f8533d0bf72170e5bcd410e341dbd05.png
https://ipfs.io/ipfs/Qmf2UL4LePfAY33r3fAuFyN7rqC1HZk7NjsgzTA1bbkSqS?filename=7711cc7d998d40559083e064f14949c2.zip

```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
We confirm that this is a publicly retrievable public dataset.
```

What is the expected retrieval frequency for this data?
```
The frequency of retrieval depends on the user's needs.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
We plan to store it permanently.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Asia.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
We will distribute to storage providers using offline transfer.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We have selected more than 10 miners around us with good reputation, trustworthiness, and experience in verifying data to conduct transactions, we will cooperate for a long time with reputable miners.
```

How will you be distributing deals across storage providers?
```
Depending on the miner's retrieval deal success rate, we allocate quotas dynamically and make sure that each miner won’t be allocated more than 30% Datacap of us. 
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, we have resources and funds to start making deals as soon as we receive Datacap.
```

**Comment by AnthnoySmith** [comment]
At this time the large dataset process is not intended for storage providers to self-deal. Can you provide some more details about your real business model? Obviously your website does not seem to validate 5PiB of public data.

**Comment by Yvette516** [comment]
I see your company was launched in 2020, but you said 2015?

**Comment by EGGRICE02** [comment]
I've tried to mail you by the address on your website, but it seems that the address is not available. What's going on there?

**Comment by dkkapur** [comment]
Closing this one for the time being. @gnasnik please let us know if it should be re-opened if it is still relevant since we have not heard from you.
