### ISSUE TITLE
[DataCap Application]ChainUp Cloud

### ISSUE THREAD

**Issue by llifezou** [filecoin-project/filecoin-plus-large-datasets#292]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name:  ChainUp Cloud
- Website / Social Media: https://www.chainupcloud.com/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 2 PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100TiB
- On-chain address for first allocation: f13dkryrmhnsvmromygwhnm37v2ospivoielu4dya

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
At ChainUP Cloud, we enable enterprises to rapidly deploy and iterate innovative blockchain applications program. Our goal is to reduce the complexity of using blockchain with quick and easy configuration, high monitoring availability and quality service with enterprise-grade security.

ChainUP Cloud is committed to lowering the barriers to connect with blockchain, allowing customers to connect to various blockchain networks so they can quickly build their applications.
We focus on improving the experience of web3 developers, provide optional node usage, and provide free IPFS storage services to facilitate developers to store DAPP application data, and developers can choose to store data in the Filecoin network.

Product use case:
(i) Blockchain API: Instant, Scalable API access with integrated data analytics for developers.
(ii) Node Service: Easily deploy industrial grade nodes for both staking & DApps services.

For Filecoin:
(i) Provide IPFS API, users can pin data for free, and can choose to store data to Filecoin.
(ii) Provide a free lotus daemon public API, allowing anyone to initiate transactions and query data on the Filecoin mainnet through the API.
```

What is the primary source of funding for this project?
```
Corporate Strategy Fund.
```

What other projects/ecosystem stakeholders is this project associated with?
```
All mainstream blockchains / All web3 applications / All valid data users
```

## Use-case details

Describe the data being stored onto Filecoin
```
Blockchain data snapshot / web3.0 application data / user valid data
```

Where was the data in this dataset sourced from?
```
Chainup Cloud platform
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
http://ipfs.originblock.info/ipfs/Qmf93EMrADXAK6CyiSfE8xx45fkMfR3uzKEPCvZC1n2kzb
(v28-stacked-proof-of-replication-merkletree-poseidon_hasher-8-8-0-sha256_hasher-82a357d2f2ca81dc61bb45f4a762807aedee1b0a53fd6c4e77b46a01bfef7820.vk)

http://ipfs.originblock.info/ipfs/QmNPc75iEfcahCwNKdqnWLtxnjspUGGR4iscjiz3wP3RtS
(v28-empty-sector-update-merkletree-poseidon_hasher-8-8-0-3b7f44a9362e3985369454947bc94022e118211e49fd672d52bec1cbfd599d18.params)
```

Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes, we only use DataCap for data that does not require specific permissions or access rights to view the data. For other data, initially, we may subsidize users' expenses (or provide an SP that does not charge for data certified by the ORIGIN block platform) to incentivize users to store data in Filecoin.
```

What is the expected retrieval frequency for this data?
```
There may not be a fixed retrieval frequency, and each type of data retrieval needs may be different.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
540 Day, and there is the possibility of extend.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
All countries
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
We plan to use offline services for data transfer.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We accept storage requests from any SP, however retrieval requirements must be met in order to be assigned a DataCap. We will conduct regular search and spot checks. If we cannot search, we will communicate with SP in time to solve the problem. We will conduct SP scoring according to the random check strategy. SPs with too low scores will not be assigned DataCap.
```

How will you be distributing deals across storage providers?
```
Balance is guaranteed. Will be distributed to multiple SPs to ensure data dispersion.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, we have enough resources, and if we can get community marketing, it will certainly help us store valid data in Filecoin.
```

**Comment by llifezou** [comment]
> @llifezou
> 
> 1. Please describe your organization's business 2PiB data composition.
> 2. Have you establish cooperation with storage providers?  If yes, please list them.  If not, please explain how to find them.

Thanks for your question.
1. chainup cloud is a blockchain infrastructure. It is focused on web3. Provides the function of web3 portal. Data includes but is not limited to Blockchain data snapshot / web3.0 application data / user valid data.
(i) For Blockchain data snapshots, we plan to store mainstream blockchain snapshots in filecoin and provide download and distribution services on our multi-region ipfs nodes.
(ii) For web3.0 application data, its most typical data is the metadata of nft
(iii) For user valid data, we provide ipfs pin service that will allow users to store their data to the filecoin network
2. We have not yet reached a cooperative relationship with storage providers, and we will cooperate with any storage providers capable of ensuring data security. Regarding how to find them, when the LDN application is approved, we accept the invitation of any capable depositor

**Comment by Sunnyiscoming** [comment]
http://ipfs.originblock.info/ipfs/Qmf93EMrADXAK6CyiSfE8xx45fkMfR3uzKEPCvZC1n2kzb
(v28-stacked-proof-of-replication-merkletree-poseidon_hasher-8-8-0-sha256_hasher-82a357d2f2ca81dc61bb45f4a762807aedee1b0a53fd6c4e77b46a01bfef7820.vk)
I opened this data sample. But it seems that because of the format problem and it is garbled.  Can you explain the format ?
The second data sample is too large to check.
Can you provide more data samples?

**Comment by dkkapur** [comment]
@llifezou this sounds like something similar to Estuary (https://estuary.tech/). Is that right? In that case, would love to understand: 
- are data owners coming to you with raw data and your software handles translating it to a CAR file and a CID?
- how are the SPs selected?
- how is the data distributed to SPs?

**Comment by llifezou** [comment]
@dkkapur 


> are data owners coming to you with raw data and your software handles translating it to a CAR file and a CID?

Yes, we provide ipfs pin service, the original data stored directly by the user, the conversion of the car file is completed by the background.

> how are the SPs selected?

We will look for at least 5 reliable SPs; we will choose SPs in the United States/Singapore/Hong Kong and other places, and we will provide IPFS services in these places to facilitate the collection and distribution of data and improve user experience.

> how is the data distributed to SPs?

We are choosing offline deals (not planning to use Lotus's data transfer as it is not very mature at present, and prone to failure). We will be leveraging our IPFS service to distribute the car file data and conduct the offline deals.

thanks

**Comment by Sunnyiscoming** [comment]
@llifezou  Hey. Could you send an email to filplus@fil.org with your official domain in order to confirm your identity?

**Comment by llifezou** [comment]
> @llifezou Hey. Could you send an email to [filplus@fil.org](mailto:filplus@fil.org) with your official domain in order to confirm your identity?

Just sent successfully, waiting for your reply @[Sunnyiscoming](https://github.com/Sunnyiscoming) @galen-mcandrew

**Comment by llifezou** [comment]
@dkkapur @galen-mcandrew @Kevin-FF-USA @Sunnyiscoming Is there any update please, thanks

**Comment by AlisaWeb** [comment]
1. There's no docs, any contents about products or guide books. It's curious that your website is empty.
![1](https://user-images.githubusercontent.com/106143617/177028450-89d75f1c-50f7-4a92-81bf-d1530cb46b6a.jpeg)

![2](https://user-images.githubusercontent.com/106143617/177028452-8d3c0fc2-b7ef-417c-be05-c47652c63613.jpeg)

2. Nothing related with Filecoin, no matter node or staking page, there is no IPFS&Filecoin or FIL.
![3](https://user-images.githubusercontent.com/106143617/177028822-096decab-13d7-44fc-9a53-401151bef9a4.jpeg)

![4](https://user-images.githubusercontent.com/106143617/177028883-f5a79079-63c4-470b-b515-35ab642f3443.jpeg)

**Comment by Sunnyiscoming** [comment]
@llifezou 
1. It seems that two data samples do not work, can you explain about that?
![image](https://user-images.githubusercontent.com/105098820/177066679-9bd1a51b-7278-43b6-9f79-10ec89b0ea5e.png)
![image](https://user-images.githubusercontent.com/105098820/177066701-6ec33ed3-4e33-4b5d-bb59-103e15abad1f.png)
2. Your organization is not a platform open for users but developers. Can you explain where users' data are from?
> We are the AWS of Web3.
> We provide a range of Web3 services such as API services for developers,
> Defi products for users and node services for everyone.
3. Can you explain about the questions [AlisaWeb](https://github.com/AlisaWeb) said above?

**Comment by Sunnyiscoming** [comment]
Hi, @llifezou 
As you said, your product is currently in the pilot stage. And you will be storing Filecoin snapshots, Filecoin proofs, platform analytics, etc.
I feel very confused about the data you will store. Where these data are from? To crawl data from other Filecoin browsers? As I know,  the code of most Filecoin browsers is open. So I don't know the meaning of you storing these data. 
FIL+ large dataset is open for clients who have the real storage requirements and save their cost on storage. I do not think you have such a requirement.

**Comment by llifezou** [comment]
> Hi, @llifezou As you said, your product is currently in the pilot stage. And you will be storing Filecoin snapshots, Filecoin proofs, platform analytics, etc. I feel very confused about the data you will store. Where these data are from? To crawl data from other Filecoin browsers? As I know, the code of most Filecoin browsers is open. So I don't know the meaning of you storing these data. FIL+ large dataset is open for clients who have the real storage requirements and save their cost on storage. I do not think you have such a requirement.

@Sunnyiscoming Our product is in the pilot stage and is already released. Users can use our platform for free currently and we have simply yet to commercialized it. Our storage requirements is not limited to just Filecoin Network alone, we highlight Filecoin to express that we want to contribute more to the Filecoin ecosystem. We will be providing snapshots for several blockchains, not just Filecoin as shown in our data sample.

Snapshots generally describe the behavior of recording the state of the blockchain at a specific block height. In this case, snapshots record the contents of the entire blockchain ledger, which includes all existing addresses and their associated data (transactions, fees, balances, metadata, etc.). Blockchain snapshots allow nodes to perform fast synchronization on all types of blockchains, which can greatly speed up the time for a blockchain node to join the network. Its a common application and its significance needs no doubt.

Analytical data from the platform is definitely valuable.
(I) Data from users using the platform. For example:How many users are running Bitcoin and Ethereum nodes, this data can reflect which blockchain is more popular and help decision makers make decisions;Daily request statistics on the platform, which can reflect which blockchain is more active.
(II) Most importantly, the analysis of various blockchain transactions will be stored in the form of secondary indexing. These data require a lot of storage space and cannot be obtained trivially from the blockchain alone.

We can assure you that these are real storage requirements, and the data we store will definitely be of used to the community for their own projects/hobbies. As a blockchain service provider, these blockchain data/platform data are actual and realistic storage use cases for us. And as a Web3 participant, we want to store our data in Filecoin Network as it can contribute to the Filecoin/ipfs ecosystem and Filecoin's vision of becoming a Decentralized Storage for Humanity's Most Important Information. We believe what we are doing is rather inlined with Fil+'s goals.

**Comment by galen-mcandrew** [comment]
## Datacap Request Trigger
#### Total DataCap requested 
> 2PiB
#### Expected weekly DataCap usage rate 
> 100TiB 
#### Client address
> f13dkryrmhnsvmromygwhnm37v2ospivoielu4dya

**Comment by llifezou** [comment]
why is that? what should we do @galen-mcandrew

**Comment by Sunnyiscoming** [comment]
@llifezou There are some checking on the sample data and the source of data.  
Sorry for the delay. It will be procceed in a short time if nothing unusual.

**Comment by llifezou** [comment]
Hi, how is the progress？ @Sunnyiscoming @galen-mcandrew

**Comment by Sunnyiscoming** [comment]
@llifezou  Can you list storage providers you will cooperate with? 
The community is very concerned about the distribution of datacap and whether storage providers support data retrieval.

**Comment by llifezou** [comment]
> @llifezou Can you list storage providers you will cooperate with? The community is very concerned about the distribution of datacap and whether storage providers support data retrieval.

We will look for SPs in Hong Kong and Singapore. The specific SPs are uncertain, and the support of SPs for retrieval is the premise of our choice.
We perform random checks on stored data to ensure data retrievability.

**Comment by llifezou** [comment]
Hi, I hope to make progress, if you have questions, I am always ready to answer

**Comment by llifezou** [comment]
@dkkapur @galen-mcandrew @Sunnyiscoming Is there any problem? Hope to make progress soon, thanks

**Comment by raghavrmadya** [comment]
Flagging for notaries for the second set of eyes, data sampling, and any other clarification for gaining full confidence before proceeding with allocation.

**Comment by raghavrmadya** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 2 PiB

**Expected weekly DataCap usage rate**

> 100 TiB

**Client address**

> f13dkryrmhnsvmromygwhnm37v2ospivoielu4dya

**Comment by raghavrmadya** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 2 PiB

**Expected weekly DataCap usage rate**

> 100 TiB

**Client address**

> f13dkryrmhnsvmromygwhnm37v2ospivoielu4dya

**Comment by psh0691** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebdv7h7yxghmldxuxmtn4fs5u5tpwyw4gl4jyoqlefvmrpch3ua72 
#### Address 
> f13dkryrmhnsvmromygwhnm37v2ospivoielu4dya
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1qdko4jg25vo35qmyvcrw4ak4fmuu3f5rif2kc7i
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebdv7h7yxghmldxuxmtn4fs5u5tpwyw4gl4jyoqlefvmrpch3ua72

**Comment by 1LISA2** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacea6k7voe6oihksz4n2y747qmcmnttx2q4osryp57uxohnrt74di7m 
#### Address 
> f13dkryrmhnsvmromygwhnm37v2ospivoielu4dya
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1jvvltduw35u6inn5tr4nfualyd42bh3vjtylgci
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacea6k7voe6oihksz4n2y747qmcmnttx2q4osryp57uxohnrt74di7m

**Comment by xingjitansuo** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebrv6pgkkgxapbdazn76sye6nvcjvb7tvoufrffby6uctndzu2iig 
#### Address 
> f13dkryrmhnsvmromygwhnm37v2ospivoielu4dya
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1a2lia2cwwekeubwo4nppt4v4vebxs2frozarz3q
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebrv6pgkkgxapbdazn76sye6nvcjvb7tvoufrffby6uctndzu2iig

**Comment by fireflyHZ** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebxoasyo5bnxy3nkhohbie7buvvecpumf3ed2lrzgdb7mvsa4jnwg 
#### Address 
> f13dkryrmhnsvmromygwhnm37v2ospivoielu4dya
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1fg6jkxsr3twfnyhdlatmq36xca6sshptscds7xa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebxoasyo5bnxy3nkhohbie7buvvecpumf3ed2lrzgdb7mvsa4jnwg

**Comment by BigD-Exchange** [comment]
@llifezou Hi! Great to see you have gotten approval for DataCap. If you are looking for storage providers to store these data or have any questions, please visit #bigdata-exchange on Filecoin Slack or reply here. 

We have strong demand from a diverse group of SPs, who are actively looking to onboard more data.

**Comment by stcouldlisa** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecgexs4bha3g64vu7uuhdacvwelc6n633r3y4lgmxmfimdleit7d6 
#### Address 
> f13dkryrmhnsvmromygwhnm37v2ospivoielu4dya
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1jvvltduw35u6inn5tr4nfualyd42bh3vjtylgci
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecgexs4bha3g64vu7uuhdacvwelc6n633r3y4lgmxmfimdleit7d6

**Comment by liyunzhi-666** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecwazzztkshkmnplfsaefipfpva2tq2gi7y67me6d53subwjp64ki 
#### Address 
> f13dkryrmhnsvmromygwhnm37v2ospivoielu4dya
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1pszcrsciyixyuxxukkvtazcokexbn54amf7gvoq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecwazzztkshkmnplfsaefipfpva2tq2gi7y67me6d53subwjp64ki

**Comment by kernelogic** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebfd4325u6a7dddithyhd3bbconi4fmqixpxs4vt5yyurgqurdz4e 
#### Address 
> f13dkryrmhnsvmromygwhnm37v2ospivoielu4dya
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebfd4325u6a7dddithyhd3bbconi4fmqixpxs4vt5yyurgqurdz4e

**Comment by newwebgroup** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedjjaxnpdzlt2pvqoolfpg46ljkgwswofvf5uteijsbaasc3wib6w 
#### Address 
> f13dkryrmhnsvmromygwhnm37v2ospivoielu4dya
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1e77zuityhvvw6u2t6tb5qlnsegy2s67qs4lbbbq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedjjaxnpdzlt2pvqoolfpg46ljkgwswofvf5uteijsbaasc3wib6w

**Comment by fireflyHZ** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceae6ftfwezzefflcpllu7wxr5uve2tl6fi2xsiztdoefad3b5lx2g 
#### Address 
> f13dkryrmhnsvmromygwhnm37v2ospivoielu4dya
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1fg6jkxsr3twfnyhdlatmq36xca6sshptscds7xa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceae6ftfwezzefflcpllu7wxr5uve2tl6fi2xsiztdoefad3b5lx2g

**Comment by newwebgroup** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebmcbuhi7ljxth6ku7hox6eizseyqgnrf67qnsncnqqqvyx2lxyea 
#### Address 
> f13dkryrmhnsvmromygwhnm37v2ospivoielu4dya
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1e77zuityhvvw6u2t6tb5qlnsegy2s67qs4lbbbq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebmcbuhi7ljxth6ku7hox6eizseyqgnrf67qnsncnqqqvyx2lxyea

**Comment by newwebgroup** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebkh4lfbaxol4sxaz4lgjq5llxc36eddpvlc2dqhu5v3eqrpwr62e 
#### Address 
> f13dkryrmhnsvmromygwhnm37v2ospivoielu4dya
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1e77zuityhvvw6u2t6tb5qlnsegy2s67qs4lbbbq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebkh4lfbaxol4sxaz4lgjq5llxc36eddpvlc2dqhu5v3eqrpwr62e

**Comment by newwebgroup** [comment]
Special reminder:
There was no quota in the last round, so the 800T signed and approved did not arrive in the account. Now we need to sign again.

**Comment by stcouldlisa** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedi2avbfrg5c2my4sa4xc424xmctwyv3r3leoayrsywrp46d5hztq 
#### Address 
> f13dkryrmhnsvmromygwhnm37v2ospivoielu4dya
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1jvvltduw35u6inn5tr4nfualyd42bh3vjtylgci
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedi2avbfrg5c2my4sa4xc424xmctwyv3r3leoayrsywrp46d5hztq

**Comment by graceonline9** [comment]
We have noticed that there are some things that are not transparent enough in https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/292. So, we hope that the community and notary public will pay attention to this application. @dkkapur @raghavrmadya 
1. The answer is deceptive in the applications https://github.com/filecoin-project/filecoin-plus-client-onboarding/issues/2481. He claimed that he did not apply for datacap before after getting too much datacap in the LDN.
2. Newwebgroup approved them three times continuously. The rules of the community do not allow a notary to continuously approve the same application. 
3. Can you provide the root CID of the orders? We hope to retrieve the data randomly.

**Comment by llifezou** [comment]
@graceonline9 
Warn! ChainUP and ChainUP Cloud have not applied for [Client Allocation Request for: ChainUP #2481](https://github.com/filecoin-project/filecoin-plus-client-onboarding/issues/2481). This applicant impersonated ChainUp. Easiest, we can provide email verification from chainup.com and chainupcloud.com!

**Comment by derricktan23** [comment]
@graceonline9 

Hi I am from ChainUp, and to answer the below questions. 

1.	The answer is deceptive in the applications Client Allocation Request for: ChainUP filecoin-plus-client-onboarding#2481. You claimed that you did not apply for datacap before after getting too much datacap in the LDN.
Ans : We are not affiliated with the malicious user: wianeigniengggoe which created the following request [Client Allocation Request for: ChainUP filecoin-plus-client-onboarding#248](https://github.com/filecoin-project/filecoin-plus-client-onboarding/issues/2481)  , also the user wianeigniengggoe was not able to back up the claims by verification methods: sent from his official email domain to confirm which organization he was representing. He has not been active since, after being exposed for an untrue answer, he provided.  
Also, llifezou from ChainUp have[ sent u an email](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/292 )  to [filplus@fil.org](mailto:filplus@fil.org) with the official ChainUp domain (email) in order to confirm his identity. 

2.	Newwebgroup approved them three times continuously. The rules of the community do not allow a notary to continuously approve the same application.
Ans : This is correctly explained by newwebgroup as above. 

3.	Can you provide the root CID of the orders? We hope to retrieve the data randomly.
Ans : Yes, that would not be an issue, my team will need some time to go through the logs. We can reach out to you by email regarding that. Please let me know if you need any clarification.

**Comment by Yvette516** [comment]
> 3. Can you provide the root CID of the orders? We hope to retrieve the data randomly.
>    **Ans :** Yes, that would not be an issue, my team will need some time to go through the logs. We can reach out to you by email regarding that. Please let me know if you need any clarification.

It's been a week, is your team ready? I don't understand why you can't make the rootcid public... @graceonline9, i would like to know if you have received any of them? In the meantime, I suggest suspending approval of the application until it supports retrieval.

**Comment by llifezou** [comment]
Any data you want is public, you can take a look at https://docs.filecoin.io/get-started/store-and-retrieve/retrieve-data/. Also, the fake application was closed after it was discovered. You can check it out: https://github.com/filecoin-project/filecoin-plus-client-onboarding/issues/2481. The storage providers that provide us with storage services have always supported retrieval. We accept any reasonable request and we do not accept groundless accusations.

**Comment by xiaoyuaiheshui** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec7owih3au5fmc4ral7jmmyqgpjp6vp5xmh4dkrqbvxydbzm5x66m 
#### Address 
> f13dkryrmhnsvmromygwhnm37v2ospivoielu4dya
#### Datacap Allocated
> 498.00TiB
#### Signer Address
> f122qmy25wdtt5mxd77kndiq7z5x2n3iwiuz2wdsa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec7owih3au5fmc4ral7jmmyqgpjp6vp5xmh4dkrqbvxydbzm5x66m

**Comment by Yvette516** [comment]
@llifezou groundless accusations? I don't think so. What you are claiming is nothing but A LIE. 
<img width="1405" alt="2022-10-09" src="https://user-images.githubusercontent.com/106008819/194745087-c91bd0c1-0a7d-49fb-ba9c-a2934a1e10e2.png">
Flagging this applicant and recommending stricter KYC/KYB and due diligence for any future applications. @xiaoyuaiheshui @Joss-Hua would you mind sharing some details as to why you feel confident in signing this application? Though the DC has been completely granted, it would be very helpful to the community if you could provide some context. Thanks!

**Comment by Yvette516** [comment]
I have flagged this application several times regarding retrieval issues. Is there any guideline or suggestion from the governance team for non-retrievable applications? @dkkapur @raghavrmadya 
https://filecoinproject.slack.com/archives/C0405HANNBT/p1664277276781369?thread_ts=1663753853.923189&cid=C0405HANNBT

**Comment by Tom-OriginStorage** [comment]
> @llifezou groundless accusations? I don't think so. What you are claiming is nothing but A LIE. <img alt="2022-10-09" width="1405" src="https://user-images.githubusercontent.com/106008819/194745087-c91bd0c1-0a7d-49fb-ba9c-a2934a1e10e2.png"> Flagging this applicant and recommending stricter KYC/KYB and due diligence for any future applications. @xiaoyuaiheshui @Joss-Hua would you mind sharing some details as to why you feel confident in signing this application? Though the DC has been completely granted, it would be very helpful to the community if you could provide some context. Thanks!

Dear @Yvette516, it looks like you were trying to retrieve data from the SPs and ran into some issues. We would let the SPs involved know of this issue. We would greatly appreciate it if you can provide more details on which [deals](https://filplus.d.interplanetary.one/clients/f01771053) that are currently unretrievable, and what commands you used for retrieval, software version etc, so that the SPs can debug the issue from their end. 

We are greatly sorry for the lack of response as it had been holiday week in China (we have colleagues in China, and there's a shortage of manpower within ChainUp 😖, we are hiring!). As for legitimacy of [ChainUp Cloud](https://www.chainupcloud.com/), it is definitely legit 👍, and its a upcoming product of ChainUp. The [ChainUp](https://www.chainup.com/team) company comprises of several well-known individuals around the world and you can also take a look at our socials to see our [doxxed images](https://twitter.com/ChainUpOfficial). Apart from attending the Notary, SPs meetings on a regular basis, Protocol Labs & Filecoin Foundation had also been visiting our office for the past few weeks for various reasons, therefore we can assure you that we definitely exist. 

If you have other queries, you can reach out to me on Slack at **Tom [OriginStorage]** or join the 3pm UTC Notary meeting and we can have a discussion there. 

Note: In case you were wondering, OriginStorage is ChainUp's subsidiary.

**Comment by filplus-checker** [comment]
## DataCap and CID Checker Report[^1]
 - Organization: ` ChainUp Cloud`
 - Client: `f13dkryrmhnsvmromygwhnm37v2ospivoielu4dya`
### Storage Provider Distribution
The below table shows the distribution of storage providers that have stored data for this client.

If this is the first time a provider takes verified deal, it will be marked as `new`.

For most of the datacap application, below restrictions should apply.
 - Storage provider should not exceed 25% of total datacap.
 - Storage provider should not be storing duplicate data for more than 20%.
 - Storage provider should have published its public IP address.
 - All storage providers should be located in different regions.

✔️ Storage provider distribution looks healthy.

| Provider                                              |                           Location | Total Deals Sealed | Percentage | Unique Data | Duplicate Deals |
| :---------------------------------------------------- | ---------------------------------: | -----------------: | ---------: | ----------: | --------------: |
| [f01852325](https://filfox.info/en/address/f01852325) | Hong Kong, Central and Western, HK |         446.16 TiB |     21.78% |  446.03 TiB |           0.03% |
| [f01852023](https://filfox.info/en/address/f01852023) |                   Busan, Busan, KR |         444.69 TiB |     21.71% |  444.56 TiB |           0.03% |
| [f01852677](https://filfox.info/en/address/f01852677) |    Morrisville, North Carolina, US |         413.41 TiB |     20.19% |  413.34 TiB |           0.02% |
| [f01851482](https://filfox.info/en/address/f01851482) |                   Busan, Busan, KR |         374.56 TiB |     18.29% |  374.50 TiB |           0.02% |
| [f01852664](https://filfox.info/en/address/f01852664) |           Singapore, Singapore, SG |         354.72 TiB |     17.32% |  354.66 TiB |           0.02% |
| [f01938721](https://filfox.info/en/address/f01938721) | Hong Kong, Central and Western, HK |           3.53 TiB |      0.17% |    3.53 TiB |           0.00% |
| [f01938714](https://filfox.info/en/address/f01938714) |     Sham Shui Po, Sham Shui Po, HK |           2.91 TiB |      0.14% |    2.91 TiB |           0.00% |
| [f01938718](https://filfox.info/en/address/f01938718) |    Morrisville, North Carolina, US |           2.88 TiB |      0.14% |    2.88 TiB |           0.00% |
| [f01938717](https://filfox.info/en/address/f01938717) |           Singapore, Singapore, SG |           2.59 TiB |      0.13% |    2.59 TiB |           0.00% |
| [f01938665](https://filfox.info/en/address/f01938665) |     Sham Shui Po, Sham Shui Po, HK |           2.56 TiB |      0.13% |    2.56 TiB |           0.00% |

![Provider Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/292/1671094506961.png)
### Deal Data Replication
The below table shows how each many unique data are replicated across storage providers.
- No more than 25% of unique data are stored with less than 4 providers.

✔️ Data replication looks healthy.

| Unique Data Size | Total Deals Made | Number of Providers | Deal Percentage |
| ---------------: | ---------------: | ------------------: | --------------: |
|        14.28 TiB |        14.28 TiB |                   1 |           0.70% |
|        17.84 TiB |        35.69 TiB |                   2 |           1.74% |
|        59.53 TiB |       178.69 TiB |                   3 |           8.72% |
|       107.13 TiB |       428.69 TiB |                   4 |          20.93% |
|       276.59 TiB |         1.35 PiB |                   5 |          67.54% |
|         1.22 TiB |         7.31 TiB |                   6 |           0.36% |
|        32.00 GiB |       224.00 GiB |                   7 |           0.01% |

![Replication Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/292/1671094507645.png)
### Deal Data Shared with other Clients
The below table shows how many unique data are shared with other clients.
Usually different applications owns different data and should not resolve to the same CID.

✔️ No CID sharing has been observed.

[^1]: To manually trigger this report, add a comment with text `checker:manualTrigger`

**Comment by lyjmry** [comment]
checker:manualTrigger
