### ISSUE TITLE
[DataCap Application] Slingshot NASA NEX dataset for team Kernelogic

### ISSUE THREAD

**Issue by kernelogic** [filecoin-project/filecoin-plus-large-datasets#297]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Fei Yan - Kernelogic
- Website / Social Media: https://slingshot.kernelogic.ca/ @feiya200
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 1PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 200 TiB
- On-chain address for first allocation: f1eknn564qwkfjwwzscbef2yc4itr5r6om3bq7yvi
- **I am the original requester for adding this dataset to slingshot** https://github.com/filecoin-project/slingshot/issues/528

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
I have participated every Slingshot phase and is probably the best performing as a "small individual client". 

I have successfully completed a few LDNs on other datasets and I have record to show I have been following the rules of decentralization and have zero self dealing.

https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/60
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/59
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/46
```

What is the primary source of funding for this project?
```
I am hoping to utilize this datacap at no cost, on active community providers on Slack, especially SPX / Slingshot Restore / enterprise-sp-wg members. 

I expect to receive prize from Slingshot as return of my effort as I need to spend a lot time preparing dataset, bandwidth, hardware and communicating with providers.
```

What other projects/ecosystem stakeholders is this project associated with?
```
Slingshot, MinerX, enterprise-sp-wp.
```

## Use-case details

Describe the data being stored onto Filecoin
```
A collection of Earth science datasets maintained by NASA, including climate change projections and satellite images of the Earth's surface.
```

Where was the data in this dataset sourced from?
```
https://registry.opendata.aws/nasanex/
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://nasanex.s3.amazonaws.com/NEX-DCP30/nex-dcp30-s3-files.json
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes
```

What is the expected retrieval frequency for this data?
```
I am expecting some retrievals during prize judging period, as well as anyone interested in downloading this dataset.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
As slingshot rule, minimum 1 year. 
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
All regions.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
I will upload my prepared CAR files to a web server and coordinate with providers to download and propose offline deals.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
I plan to deal with SPX, approved slingshot restore SPs and enterprise-sp-wg members, as well as any real community providers who are interested.
```

How will you be distributing deals across storage providers?
```
Evenly across all providers I propose to, if they can handle. If a miner is a notary itself, this notary will receive no more than 10% of the total granted datacap.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
I have all I need to start making deals.
```

**Comment by galen-mcandrew** [comment]
## Multisig Notary requested
#### Total DataCap requested 
> 1PiB
#### Expected weekly DataCap usage rate 
> 200TiB

**Comment by swatchliu** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebiimhrrnlemuss5zb6livpbmnzot744s4ccv25laxniu3nwkrdfg 
#### Address 
> f1eknn564qwkfjwwzscbef2yc4itr5r6om3bq7yvi
#### Datacap Allocated
> 51.19TiB
#### Signer Address
> f1yh6q3nmsg7i2sys7f7dexcuajgoweudcqj2chfi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebiimhrrnlemuss5zb6livpbmnzot744s4ccv25laxniu3nwkrdfg

**Comment by MegTei** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceba2sl2onk5lsq6yggtczeoi7wporeaqlqv6f5uk6hpjcj5dt37ze 
#### Address 
> f1eknn564qwkfjwwzscbef2yc4itr5r6om3bq7yvi
#### Datacap Allocated
> 51.19TiB
#### Signer Address
> f1ystxl2ootvpirpa7ebgwl7vlhwkbx2r4zjxwe5i
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceba2sl2onk5lsq6yggtczeoi7wporeaqlqv6f5uk6hpjcj5dt37ze

**Comment by Fenbushi-Filecoin** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec5h72j6jxfrzzqms3d75bzetvbzpluxufennfjjd3vaygxrr2gua 
#### Address 
> f1eknn564qwkfjwwzscbef2yc4itr5r6om3bq7yvi
#### Datacap Allocated
> 51.19TiB
#### Signer Address
> f1yqydpmqb5en262jpottko2kd65msajax7fi4rmq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec5h72j6jxfrzzqms3d75bzetvbzpluxufennfjjd3vaygxrr2gua

**Comment by dkkapur** [comment]
Subsequent allocation bot is down, pushing the next transaction through manually.

**Comment by dkkapur** [comment]
![image](https://user-images.githubusercontent.com/2343218/164392884-bdb9a9c9-05e2-4c58-8169-2b36de7cae0c.png)

current state:
![image](https://user-images.githubusercontent.com/2343218/164392996-0b9e61da-26fe-455a-80bb-2c9d0521938e.png)

**Comment by flyworker** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedtmyfnp3cywma3lkprlvqnl3gohagtugxvyk7rr7frnuzkljxbog 
#### Address 
> f1eknn564qwkfjwwzscbef2yc4itr5r6om3bq7yvi
#### Datacap Allocated
> 102.39TiB
#### Signer Address
> f1hlubjsdkv4wmsdadihloxgwrz3j3ernf6i3cbpy
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedtmyfnp3cywma3lkprlvqnl3gohagtugxvyk7rr7frnuzkljxbog

**Comment by neogeweb3** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceab42z7qql3gid65pi6v4q7fmnfqqk3x3dcbrwq6ajixoialgmxbc 
#### Address 
> f1eknn564qwkfjwwzscbef2yc4itr5r6om3bq7yvi
#### Datacap Allocated
> 102.39TiB
#### Signer Address
> f13k5zr6ovc2gjmg3lvd43ladbydhovpylcvbflpa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceab42z7qql3gid65pi6v4q7fmnfqqk3x3dcbrwq6ajixoialgmxbc

**Comment by swatchliu** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceceoqwch6p4vv2qqw222477xffyhbbnldwniznpy6zepbt3mb7c2k 
#### Address 
> f1eknn564qwkfjwwzscbef2yc4itr5r6om3bq7yvi
#### Datacap Allocated
> 102.39TiB
#### Signer Address
> f1yh6q3nmsg7i2sys7f7dexcuajgoweudcqj2chfi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceceoqwch6p4vv2qqw222477xffyhbbnldwniznpy6zepbt3mb7c2k

**Comment by dkkapur** [comment]
@fabriziogianni7 - this client ran out of DataCap. Looks like SA-bot saw that this was happening but comment was not posted. Any idea why?
![image](https://user-images.githubusercontent.com/2343218/166202675-0ecd281e-a33b-4f7b-af0d-7d98ee95aaed.png)

**Comment by Reiers** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecu3bwf35u3oz5gqpagx2erm2xqa5hxna2djfxplwyxf6ieulush2 
#### Address 
> f1eknn564qwkfjwwzscbef2yc4itr5r6om3bq7yvi
#### Datacap Allocated
> 204.79TiB
#### Signer Address
> f1oz43ckvmtxmmsfzqm6bpnemqlavz4ifyl524chq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecu3bwf35u3oz5gqpagx2erm2xqa5hxna2djfxplwyxf6ieulush2

**Comment by swatchliu** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedwszbyav4vzuj6lpyzpmckec2pztu4b3q5rfnmhjns7gax5mjy5u 
#### Address 
> f1eknn564qwkfjwwzscbef2yc4itr5r6om3bq7yvi
#### Datacap Allocated
> 204.79TiB
#### Signer Address
> f1yh6q3nmsg7i2sys7f7dexcuajgoweudcqj2chfi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedwszbyav4vzuj6lpyzpmckec2pztu4b3q5rfnmhjns7gax5mjy5u

**Comment by kernelogic** [comment]
20TB left now and no top-up request from bot. @dkkapur @fabriziogianni7

**Comment by s0nik42** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceblr3hcvv6jvasiprc6bnuk7skk4sp3yr5d36k6cebofjfnphchyq 
#### Address 
> f1eknn564qwkfjwwzscbef2yc4itr5r6om3bq7yvi
#### Datacap Allocated
> 409.59TiB
#### Signer Address
> f1wxhnytjmklj2czezaqcfl7eb4nkgmaxysnegwii
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceblr3hcvv6jvasiprc6bnuk7skk4sp3yr5d36k6cebofjfnphchyq

**Comment by flyworker** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceccyulgle73pwc2l35tk4htdfcmyrdoxoohaffdvfesc5pa24pibc 
#### Address 
> f1eknn564qwkfjwwzscbef2yc4itr5r6om3bq7yvi
#### Datacap Allocated
> 409.59TiB
#### Signer Address
> f1hlubjsdkv4wmsdadihloxgwrz3j3ernf6i3cbpy
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceccyulgle73pwc2l35tk4htdfcmyrdoxoohaffdvfesc5pa24pibc

**Comment by kernelogic** [comment]
All allocated and competition concluded. Closing this issue now. Thank you very much all!

**Comment by filplus-checker** [comment]
## DataCap and CID Checker Report[^1]
 - Organization: `Fei Yan - Kernelogic`
 - Client: `f1eknn564qwkfjwwzscbef2yc4itr5r6om3bq7yvi`
### Storage Provider Distribution
The below table shows the distribution of storage providers that have stored data for this client.

If this is the first time a provider takes verified deal, it will be marked as `new`.

For most of the datacap application, below restrictions should apply.
 - Storage provider should not exceed 25% of total datacap.
 - Storage provider should not be storing duplicate data for more than 20%.
 - Storage provider should have published its public IP address.
 - All storage providers should be located in different regions.

✔️ Storage provider distribution looks healthy.

| Provider                                                    |                               Location | Total Deals Sealed | Percentage | Unique Data | Duplicate Deals |
| :---------------------------------------------------------- | -------------------------------------: | -----------------: | ---------: | ----------: | --------------: |
| [f03223](https://filfox.info/en/address/f03223)             |               San Jose, California, US |          75.16 TiB |      9.44% |   75.16 TiB |           0.00% |
| [f01652333](https://filfox.info/en/address/f01652333)       |              Sunnyvale, California, US |          71.81 TiB |      9.02% |   71.81 TiB |           0.00% |
| [f01823264](https://filfox.info/en/address/f01823264)       |                   Chengdu, Sichuan, CN |          65.84 TiB |      8.27% |   65.84 TiB |           0.00% |
| [f02301](https://filfox.info/en/address/f02301)             |               San Jose, California, US |          64.06 TiB |      8.04% |   64.06 TiB |           0.00% |
| [f0240185](https://filfox.info/en/address/f0240185)         |                Clifton, New Jersey, US |          63.19 TiB |      7.93% |   63.19 TiB |           0.00% |
| [f01208154](https://filfox.info/en/address/f01208154)       |            Sydney, New South Wales, AU |          61.16 TiB |      7.68% |   61.16 TiB |           0.00% |
| [f0143858](https://filfox.info/en/address/f0143858)         |                Clifton, New Jersey, US |          56.66 TiB |      7.11% |   56.66 TiB |           0.00% |
| [f01702940](https://filfox.info/en/address/f01702940)       |                      Dallas, Texas, US |          48.25 TiB |      6.06% |   48.25 TiB |           0.00% |
| [f01392893](https://filfox.info/en/address/f01392893)       |           Amsterdam, North Holland, NL |          37.50 TiB |      4.71% |   37.50 TiB |           0.00% |
| [f01208803](https://filfox.info/en/address/f01208803)       |            Sydney, New South Wales, AU |          37.34 TiB |      4.69% |   37.34 TiB |           0.00% |
| [f01208189](https://filfox.info/en/address/f01208189)       |            Sydney, New South Wales, AU |          30.63 TiB |      3.85% |   30.63 TiB |           0.00% |
| [f01840219](https://filfox.info/en/address/f01840219)`new`  |                   Chengdu, Sichuan, CN |          24.63 TiB |      3.09% |   24.63 TiB |           0.00% |
| [f01882569](https://filfox.info/en/address/f01882569)       |                   Atlanta, Georgia, US |          23.34 TiB |      2.93% |   23.34 TiB |           0.00% |
| [f01900823](https://filfox.info/en/address/f01900823)`new`  |                    Jinan, Shandong, CN |          21.38 TiB |      2.68% |   21.38 TiB |           0.00% |
| [f09848](https://filfox.info/en/address/f09848)             | Rancho Santa Margarita, California, US |          19.53 TiB |      2.45% |   18.19 TiB |           6.88% |
| [f01752548](https://filfox.info/en/address/f01752548)       |                Seattle, Washington, US |          18.59 TiB |      2.33% |   18.56 TiB |           0.17% |
| [f039940](https://filfox.info/en/address/f039940)           |                   Chengdu, Sichuan, CN |          18.22 TiB |      2.29% |   18.22 TiB |           0.00% |
| [f01872811](https://filfox.info/en/address/f01872811)       |                      Dallas, Texas, US |          17.94 TiB |      2.25% |   17.94 TiB |           0.00% |
| [f01889910](https://filfox.info/en/address/f01889910)       |                   Phoenix, Arizona, US |          17.16 TiB |      2.15% |   17.16 TiB |           0.00% |
| [f01208632](https://filfox.info/en/address/f01208632)       |            Sydney, New South Wales, AU |          14.09 TiB |      1.77% |   14.09 TiB |           0.00% |
| [f0397083](https://filfox.info/en/address/f0397083)         |                       Tokyo, Tokyo, JP |           9.88 TiB |      1.24% |    9.88 TiB |           0.00% |

![Provider Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/297/1671094629784.png)
### Deal Data Replication
The below table shows how each many unique data are replicated across storage providers.
- No more than 25% of unique data are stored with less than 4 providers.

✔️ Data replication looks healthy.

| Unique Data Size | Total Deals Made | Number of Providers | Deal Percentage |
| ---------------: | ---------------: | ------------------: | --------------: |
|        64.00 GiB |       192.00 GiB |                   3 |           0.02% |
|         1.22 TiB |         4.97 TiB |                   4 |           0.62% |
|         1.31 TiB |         6.88 TiB |                   5 |           0.86% |
|         4.47 TiB |        27.00 TiB |                   6 |           3.39% |
|         6.09 TiB |        42.75 TiB |                   7 |           5.37% |
|         8.03 TiB |        64.53 TiB |                   8 |           8.10% |
|        17.56 TiB |       158.41 TiB |                   9 |          19.89% |
|        22.03 TiB |       220.38 TiB |                  10 |          27.67% |
|         2.81 TiB |        30.94 TiB |                  11 |           3.88% |
|         2.88 TiB |        34.50 TiB |                  12 |           4.33% |
|         3.25 TiB |        42.25 TiB |                  13 |           5.31% |
|         4.25 TiB |        59.50 TiB |                  14 |           7.47% |
|         6.94 TiB |       104.06 TiB |                  15 |          13.07% |

![Replication Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/297/1671094630456.png)
### Deal Data Shared with other Clients
The below table shows how many unique data are shared with other clients.
Usually different applications owns different data and should not resolve to the same CID.

⚠️ CID sharing has been observed.

| Other Client                                                                                                          | Application                                                                                          | Total Deals Affected | Unique CIDs |        Verifier |
| :-------------------------------------------------------------------------------------------------------------------- | :--------------------------------------------------------------------------------------------------- | -------------------: | ----------: | --------------: |
| [f1euejrtpg5vphqzydzleld2vgxfkhbrueiomz54y](https://filfox.info/en/address/f1euejrtpg5vphqzydzleld2vgxfkhbrueiomz54y) | [Fei Yan \- Kernelogic](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/457) |           352.00 GiB |          11 | LDN v3 multisig |

[^1]: To manually trigger this report, add a comment with text `checker:manualTrigger`
