### ISSUE TITLE
[DataCap Application] [DEPRECATED] 3000 Rice Genome for Slingshot 2.5 and forward

### ISSUE THREAD

**Issue by kernelogic** [filecoin-project/filecoin-plus-large-datasets#3]
# Client DataCap application

To apply for a DataCap allocation for your dataset, please fill out the following information.
    
## Core Information
- Organization Name: [DEPRECATED] Fei Yan - Kernelogic
- Website / Social Media: slack @feiya200
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 500 TiB
- On-chain address for first allocation: f3spci2tzjzhedgvxsoxg4hprrkyszdce5dacaxg4ndkvpshpuma2uf6c4fmk2lvvrobnz5bvr6j5hfeccpupq

## Project details

Share a brief history of your project and organization.
```
I have participated every Slingshot phase and is probably the best performing as a "small individual miner". 

I am known for always storing data with many different community miners in different countries rather than self-dealing.

Given the slingshot prize is getting smaller and smaller for me to make a profit, I am turning to this large datacap application hoping to reduce my cost of participating slingshot, also benefit every small but real miners out there to take verified deals.
```

What is the primary source of funding for this project?
```
I am hoping to use all these 500TiB datacap at zero cost, on all the small active community miners (< 500T) out there on Slack, especially MinerX members. 

I expect to receive prize from Slingshot as return of my effort. I am not sure if this is allowed or not under this framework.
```

What other projects/ecosystem stakeholders is this project associated with?
```
Slingshot phase 2.5 and forward.
```

## Use-case details

Describe the data being stored onto Filecoin
```
https://docs.opendata.aws/3kricegenome/readme.html
The 3000 Rice Genome Project is an international effort to sequence the genomes of 3,024 rice varieties from 89 countries. 
```

Where was the data in this dataset sourced from?
```
https://docs.opendata.aws/3kricegenome/readme.html
The 3000 Rice Genome Project is an international effort to sequence the genomes of 3,024 rice varieties from 89 countries. 
```

Can you share a sample of what is in the dataset? A link to a file, an image, a table, etc., are good examples of this. 
```
https://3kricegenome.s3.amazonaws.com/9311/IRIS_313-15896.realigned.bam
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes it is on the list of slingshot approved dataset and is hosted on AWS.
```

What is the expected retrieval frequency for this data?
```
I am expecting some retrievals during prize judging period, as well as anyone interested in downloading this dataset.
```

For how long do you plan to keep this dataset stored on Filecoin? Will this be a permanent archival or a one-time storage deal?
```
As slingshot rule, 1 year.
```

## DataCap allocation plan

In which geographies do you plan on making storage deals?
```
All regions.
```

What is your expected data onboarding rate? How many deals can you make in a day, in a week? How much DataCap do you plan on using per day, per week?
```
I can send out 100TiB of 32GiB deals a week.
```

How will you be distributing your data to miners? Is there an offline data transfer process?
```
Yes I will upload my prepared CAR files to a web server and coordinate with miners to download and propose offline deals.
I might utilize filswan platform to automate the process.
```

How do you plan on choosing the miners with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
I plan to make deals with MinerX members, as well as a couple small miners (under 500T) I deal with frequently during previous phases.
```

How will you be distributing data and DataCap across miners storing data?
```
Evenly across all miners I propose to, if they can handle. If a miner is a notary itself, this notary will receive more than 5% of the total granted datacap.
```

**Comment by dkkapur** [comment]
@kernelogic - in case you can make it to the Notary Governance Call happening on 2021-05-25 at 1500 UTC, it would be great to discuss your application further with the community! Details for attending the call can be found here: https://github.com/filecoin-project/notary-governance/issues/156

**Comment by KodaRobotDog** [comment]
I  am interested into looking at this one.

**Comment by kernelogic** [comment]
Sorry @kernelogic I missed the governance meeting. Was in a meeting with Sonia about the devgrant. 

And thank you @KodaRobotDog for looking into my application. I believe I can benefit the small miner community by sending large amount of deals of public dataset efficiently and I have been done so with all my previously granted datacaps.

**Comment by XnMatrixSV** [comment]
@kernelogic This project sounds great.

**Comment by kernelogic** [comment]
Because slingshot 2.4 is approaching its end and this is not yet approved. I have amended my request to be applicable to future phases.

**Comment by cryptowhizzard** [comment]
I am in favor of supporting this. 

Storing so much data in Slingshot does not provide security of funds you invest. I.e. miners charge Fil to @kernelogic while in the end they do not provide retrieval ( intentionally by others to get higher rank or not ). This can cost a great deal of money for bandwidth. Covering some of the risks by making this dataset available in Fil-plus might provide a solution to have Slingshot available to a broader audience. ( most now is stored on owned miners by those who originate.  ) 

I would like to see a precondition amended that it is clear to who the deals are send. I.e. i would like to see all miner-ID's before the datacap (or parts of) is granted to prevent excessive self dealing apart from the " regular " screening taking place.

**Comment by flyworker** [comment]
I am OK with this.
The current situation is the slingshot reward is barely cover the cost of send deals, for miners who is not self sealing they do not have incentive to do the sealing work.

**Comment by kernelogic** [comment]
[miners.csv](https://github.com/filecoin-project/filecoin-plus-large-datasets/files/6831874/miners.csv)

Here is a list of all the deals count per miner throughout all the slingshot phases sent by me. I have a great variety of miners selection and most of them are recognizable community members.

Like I emphasized again and again, this datacap will benefit more for the community miners than my personal gain on the prize.

**Comment by swatchliu** [comment]
Great project， Bytebase will support this and salute to Academician Mr. Yuan Longping

**Comment by Fenbushi-Filecoin** [comment]
> [miners.csv](https://github.com/filecoin-project/filecoin-plus-large-datasets/files/6831874/miners.csv)
> 
> Here is a list of all the deals count per miner throughout all the slingshot phases sent by me. I have a great variety of miners selection and most of them are recognizable community members.
> 
> Like I emphasized again and again, this datacap will benefit more for the community miners than my personal gain on the prize.

Fenbushi would like to support this. I checked the list of the miners and the selection looks legit.

**Comment by dkkapur** [comment]
Thanks folks - looks like 7 notaries approve and we have coverage from EU, NA, GCR.

1. @KodaRobotDog - f1jyalts5uhtmp5sbbssse23toshvsqbbtjgukm5a
2. @XnMatrixSV - f1yuz2twsllparyfqwslfiuxrc5wj4mfiflvnsw6a
3. @cryptowhizzard - f1krmypm4uoxxf3g7okrwtrahlmpcph3y7rbqqgfa
4. @flyworker - f1hlubjsdkv4wmsdadihloxgwrz3j3ernf6i3cbpy
5. @swatchliu - f1yh6q3nmsg7i2sys7f7dexcuajgoweudcqj2chfi
6. @Fenbushi-Filecoin - f1yqydpmqb5en262jpottko2kd65msajax7fi4rmq
7. @Reiers - f1oz43ckvmtxmmsfzqm6bpnemqlavz4ifyl524chq

Can the notaries please confirm the addresses I have listed above following which I can kick off the request to the RKH? Thank you!

**Comment by cryptowhizzard** [comment]
@dkkapur -> f1krmypm4uoxxf3g7okrwtrahlmpcph3y7rbqqgfa -> confirmed.

**Comment by flyworker** [comment]
> * 
> 
> * @swatchliu - f1yh6q3nmsg7i2sys7f7dexcuajgoweudcqj2chfi

@flyworker -f1hlubjsdkv4wmsdadihloxgwrz3j3ernf6i3cbpy confirmed

**Comment by Reiers** [comment]
**f1oz43ckvmtxmmsfzqm6bpnemqlavz4ifyl524chq -> Confirmed.**

**Comment by swatchliu** [comment]
f1yh6q3nmsg7i2sys7f7dexcuajgoweudcqj2chfi

confirmed

**Comment by Fenbushi-Filecoin** [comment]
f1yqydpmqb5en262jpottko2kd65msajax7fi4rmq - confirmed

**Comment by dkkapur** [comment]
## Multisig Notary requested
 
#### Notary addresses
> f1jyalts5uhtmp5sbbssse23toshvsqbbtjgukm5a
> f1yuz2twsllparyfqwslfiuxrc5wj4mfiflvnsw6a
> f1krmypm4uoxxf3g7okrwtrahlmpcph3y7rbqqgfa
> f1hlubjsdkv4wmsdadihloxgwrz3j3ernf6i3cbpy
> f1yh6q3nmsg7i2sys7f7dexcuajgoweudcqj2chfi
> f1yqydpmqb5en262jpottko2kd65msajax7fi4rmq
> f1oz43ckvmtxmmsfzqm6bpnemqlavz4ifyl524chq

#### Total DataCap requested
> 500PiB

#### Expected weekly DataCap usage rate
> 100TiB

**Comment by flyworker** [comment]
I could work as lead notary for this project if no one wants to lead.
Thanks

**Comment by kernelogic** [comment]
I here by request lead notary to allocate me 100TiB datacap to this address
f3spci2tzjzhedgvxsoxg4hprrkyszdce5dacaxg4ndkvpshpuma2uf6c4fmk2lvvrobnz5bvr6j5hfeccpupq

**Comment by galen-mcandrew** [comment]
@flyworker I think this has LDN has cleared the root key holders, and the multisig f01155654 is now created with 500 TiB. 

I think you can kick off the first allocation message and get three more notaries to approve the first allocation of 10TiB!

**Comment by XnMatrixSV** [comment]
Hi, @galen-mcandrew 
First allocation: lesser of 5% of total DataCap requested or 50% of weekly allocation rate
https://github.com/filecoin-project/notary-governance/issues/94
First allocation should be 25TiB, right?

**Comment by flyworker** [comment]
@galen-mcandrew I am a new born notary, could you please tell me how much I should to allocate?
as @XnMatrixSV  said, 25TB?

**Comment by kernelogic** [comment]
25T is fine with me

**Comment by galen-mcandrew** [comment]
Thank you @XnMatrixSV ! Community Governance at work here keeping us all aligned

@flyworker you should be able to see the specific steps here, happy to help if there are any questions.

https://github.com/filecoin-project/filecoin-plus-large-datasets#granting-datacap-to-the-client

**Comment by flyworker** [comment]
## DataCap Allocation requested
#### Multisig Notary address
>f01155654
#### Client address
> f3spci2tzjzhedgvxsoxg4hprrkyszdce5dacaxg4ndkvpshpuma2uf6c4fmk2lvvrobnz5bvr6j5hfeccpupq
#### DataCap allocation requested
> 25TiB

**Comment by swatchliu** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacea7umxdjuqmrefoj7qigtpcjfj2ii2mvjzc7ejkc4ywvp77fsvs7w 
#### Address 
> f3spci2tzjzhedgvxsoxg4hprrkyszdce5dacaxg4ndkvpshpuma2uf6c4fmk2lvvrobnz5bvr6j5hfeccpupq
#### Datacap Allocated
> 27487790694400
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacea7umxdjuqmrefoj7qigtpcjfj2ii2mvjzc7ejkc4ywvp77fsvs7w

**Comment by flyworker** [comment]
![image](https://user-images.githubusercontent.com/8363795/130176121-ac2a23fa-1311-4430-a174-901588ae15f7.png)

**Comment by flyworker** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceboivbodr475w2p4clcssmpsrf6l7gm5xwx4z6av3xvz6i6x54ecm 
#### Address 
> f3spci2tzjzhedgvxsoxg4hprrkyszdce5dacaxg4ndkvpshpuma2uf6c4fmk2lvvrobnz5bvr6j5hfeccpupq
#### Datacap Allocated
> 27487790694400
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceboivbodr475w2p4clcssmpsrf6l7gm5xwx4z6av3xvz6i6x54ecm

**Comment by cryptowhizzard** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebllezaweg3jsut6ecmndwyh3xmnwlga2tcxdc5ivehhvtnyfcksi 
#### Address 
> f3spci2tzjzhedgvxsoxg4hprrkyszdce5dacaxg4ndkvpshpuma2uf6c4fmk2lvvrobnz5bvr6j5hfeccpupq
#### Datacap Allocated
> 27487790694400
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebllezaweg3jsut6ecmndwyh3xmnwlga2tcxdc5ivehhvtnyfcksi

**Comment by Reiers** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedlcfuis32bvyzo2ed6kyxjrzjyrcdejzhmjd5xhrpxdjivjzmu54 
#### Address 
> f3spci2tzjzhedgvxsoxg4hprrkyszdce5dacaxg4ndkvpshpuma2uf6c4fmk2lvvrobnz5bvr6j5hfeccpupq
#### Datacap Allocated
> 27487790694400
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedlcfuis32bvyzo2ed6kyxjrzjyrcdejzhmjd5xhrpxdjivjzmu54

**Comment by galen-mcandrew** [comment]
@kernelogic Thank you so much for the patience here, we're hoping to get this process moving more efficiently! At this time, I'm seeing that address f01037760 has 25 TiB of DataCap! https://filplus.d.interplanetary.one/clients?filter=f01037760

**Comment by kernelogic** [comment]
@flyworker I am close to use up 80% of the second allocation and I still have many deals sent out pending sealing. In order to avoid interruptions, I'd like to request the next allocation of 200TiB on the same address please.
`Third allocation onwards: lesser of 20% of total DataCap request or 200% of weekly allocation rate`

Current progress: https://filplus.d.interplanetary.one/clients?filter=f01037760

Address(same): f3spci2tzjzhedgvxsoxg4hprrkyszdce5dacaxg4ndkvpshpuma2uf6c4fmk2lvvrobnz5bvr6j5hfeccpupq

**Comment by flyworker** [comment]
## DataCap Allocation requested
#### Multisig Notary address
>f01155654
#### Client address
> f3spci2tzjzhedgvxsoxg4hprrkyszdce5dacaxg4ndkvpshpuma2uf6c4fmk2lvvrobnz5bvr6j5hfeccpupq
#### DataCap allocation requested
> 100TiB

**Comment by flyworker** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced65wry3cjouhmgj6f5bpskm23gt7zq7uiamburrmg5nqiexxwbqi 
#### Address 
> f3spci2tzjzhedgvxsoxg4hprrkyszdce5dacaxg4ndkvpshpuma2uf6c4fmk2lvvrobnz5bvr6j5hfeccpupq
#### Datacap Allocated
> 109951162777600
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced65wry3cjouhmgj6f5bpskm23gt7zq7uiamburrmg5nqiexxwbqi

**Comment by Reiers** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceag5qr6qmnzazab3sk3q5ofqzihoj4xtfhj3oxgdq4xa6knli2spo 
#### Address 
> f3spci2tzjzhedgvxsoxg4hprrkyszdce5dacaxg4ndkvpshpuma2uf6c4fmk2lvvrobnz5bvr6j5hfeccpupq
#### Datacap Allocated
> 109951162777600
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceag5qr6qmnzazab3sk3q5ofqzihoj4xtfhj3oxgdq4xa6knli2spo

**Comment by kernelogic** [comment]
@KodaRobotDog @XnMatrixSV could you sign this datacap top up?

**Comment by swatchliu** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebnob2wsodjssxavg3fxgknyqjhcstybfodqkelemmevmjmcz4sti 
#### Address 
> f3spci2tzjzhedgvxsoxg4hprrkyszdce5dacaxg4ndkvpshpuma2uf6c4fmk2lvvrobnz5bvr6j5hfeccpupq
#### Datacap Allocated
> 109951162777600
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebnob2wsodjssxavg3fxgknyqjhcstybfodqkelemmevmjmcz4sti

**Comment by kernelogic** [comment]
@flyworker I am close to use up 70% of the second allocation and I still have many deals sent out pending sealing. (Last time I waited till 80% is used but it took too long to approve and I got some down time).

In order to avoid interruptions, I'd like to request the next allocation of 100TiB on the same address please.

Third allocation onwards: lesser of 20% of total DataCap request or 200% of weekly allocation rate

Current progress: https://filplus.d.interplanetary.one/clients?filter=f01037760

Address(same): f3spci2tzjzhedgvxsoxg4hprrkyszdce5dacaxg4ndkvpshpuma2uf6c4fmk2lvvrobnz5bvr6j5hfeccpupq

**Comment by flyworker** [comment]
## DataCap Allocation requested
#### Multisig Notary address
>f01155654
#### Client address
> f3spci2tzjzhedgvxsoxg4hprrkyszdce5dacaxg4ndkvpshpuma2uf6c4fmk2lvvrobnz5bvr6j5hfeccpupq
#### DataCap allocation requested
> 100TiB

**Comment by flyworker** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebkoj2wmlllhinnban52je5plmtb6xktz7w2ni3vn5j4ycxkfm3yq 
#### Address 
> f3spci2tzjzhedgvxsoxg4hprrkyszdce5dacaxg4ndkvpshpuma2uf6c4fmk2lvvrobnz5bvr6j5hfeccpupq
#### Datacap Allocated
> 109951162777600
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebkoj2wmlllhinnban52je5plmtb6xktz7w2ni3vn5j4ycxkfm3yq

**Comment by Reiers** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacea3geaqpc3lgre2vkvobztwhbpn5i25kmfus2hs3ot2pobkahxeqc 
#### Address 
> f3spci2tzjzhedgvxsoxg4hprrkyszdce5dacaxg4ndkvpshpuma2uf6c4fmk2lvvrobnz5bvr6j5hfeccpupq
#### Datacap Allocated
> 109951162777600
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacea3geaqpc3lgre2vkvobztwhbpn5i25kmfus2hs3ot2pobkahxeqc

**Comment by cryptowhizzard** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb35jwd43366aqrm5tdgzhw5iasnlsdruy3tvuvr5ndklesditf6u 
#### Address 
> f3spci2tzjzhedgvxsoxg4hprrkyszdce5dacaxg4ndkvpshpuma2uf6c4fmk2lvvrobnz5bvr6j5hfeccpupq
#### Datacap Allocated
> 109951162777600
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb35jwd43366aqrm5tdgzhw5iasnlsdruy3tvuvr5ndklesditf6u

**Comment by swatchliu** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebry6py7h4ilwhy7a6g3cstgdlobahsrpei7fno4amedhpgqhhk4y 
#### Address 
> f3spci2tzjzhedgvxsoxg4hprrkyszdce5dacaxg4ndkvpshpuma2uf6c4fmk2lvvrobnz5bvr6j5hfeccpupq
#### Datacap Allocated
> 109951162777600
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebry6py7h4ilwhy7a6g3cstgdlobahsrpei7fno4amedhpgqhhk4y

**Comment by galen-mcandrew** [comment]
Rolling to https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/46

**Comment by filplus-checker** [comment]
## DataCap and CID Checker Report[^1]
 - Organization: `Fei Yan - Kernelogic`
 - Client: `f3spci2tzjzhedgvxsoxg4hprrkyszdce5dacaxg4ndkvpshpuma2uf6c4fmk2lvvrobnz5bvr6j5hfeccpupq`
### Storage Provider Distribution
The below table shows the distribution of storage providers that have stored data for this client.

If this is the first time a provider takes verified deal, it will be marked as `new`.

For most of the datacap application, below restrictions should apply.
 - Storage provider should not exceed 25% of total datacap.
 - Storage provider should not be storing duplicate data for more than 20%.
 - Storage provider should have published its public IP address.
 - All storage providers should be located in different regions.

⚠️ [f0145874](https://filfox.info/en/address/f0145874) has unknown IP location.

⚠️ [f020378](https://filfox.info/en/address/f020378) has unknown IP location.

| Provider                                                    |                     Location | Total Deals Sealed | Percentage | Unique Data | Duplicate Deals |
| :---------------------------------------------------------- | ---------------------------: | -----------------: | ---------: | ----------: | --------------: |
| [f0240185](https://filfox.info/en/address/f0240185)         |      Clifton, New Jersey, US |          12.00 TiB |     23.86% |   12.00 TiB |           0.00% |
| [f0143858](https://filfox.info/en/address/f0143858)         |      Clifton, New Jersey, US |          11.22 TiB |     22.31% |   11.22 TiB |           0.00% |
| [f02301](https://filfox.info/en/address/f02301)             |     San Jose, California, US |          11.13 TiB |     22.12% |   11.13 TiB |           0.00% |
| [f0447183](https://filfox.info/en/address/f0447183)         |    Indianapolis, Indiana, US |           6.64 TiB |     13.20% |    6.58 TiB |           0.94% |
| [f0157535](https://filfox.info/en/address/f0157535)         |         Montréal, Quebec, CA |           6.03 TiB |     11.99% |    6.03 TiB |           0.00% |
| [f01163272](https://filfox.info/en/address/f01163272)       |          Perm, Perm Krai, RU |         736.00 GiB |      1.43% |  672.00 GiB |           8.70% |
| [f0145874](https://filfox.info/en/address/f0145874)`new`    |                      Unknown |         576.00 GiB |      1.12% |  576.00 GiB |           0.00% |
| [f047419](https://filfox.info/en/address/f047419)`new`      | North Prairie, Wisconsin, US |         512.00 GiB |      0.99% |  512.00 GiB |           0.00% |
| [f097777](https://filfox.info/en/address/f097777)           |          Kivertsi, Volyn, UA |         416.00 GiB |      0.81% |  416.00 GiB |           0.00% |
| [f020378](https://filfox.info/en/address/f020378)           |                      Unknown |         320.00 GiB |      0.62% |  320.00 GiB |           0.00% |
| [f01255977](https://filfox.info/en/address/f01255977)`new`  |      Shenzhen, Guangdong, CN |         256.00 GiB |      0.50% |  256.00 GiB |           0.00% |
| [f0165400](https://filfox.info/en/address/f0165400)         |         Montréal, Quebec, CA |         224.00 GiB |      0.43% |  224.00 GiB |           0.00% |
| [f022352](https://filfox.info/en/address/f022352)           |               Oslo, Oslo, NO |         192.00 GiB |      0.37% |  192.00 GiB |           0.00% |
| [f01091840](https://filfox.info/en/address/f01091840)`new`  |         Montréal, Quebec, CA |          64.00 GiB |      0.12% |   64.00 GiB |           0.00% |
| [f01136409](https://filfox.info/en/address/f01136409)`new`  |     Zhongshan, Guangdong, CN |          64.00 GiB |      0.12% |   64.00 GiB |           0.00% |

![Provider Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/3/1671089671032.png)
### Deal Data Replication
The below table shows how each many unique data are replicated across storage providers.
- No more than 25% of unique data are stored with less than 4 providers.

⚠️ 94.66% of deals are for data replicated across less than 4 storage providers.

| Unique Data Size | Total Deals Made | Number of Providers | Deal Percentage |
| ---------------: | ---------------: | ------------------: | --------------: |
|       976.00 GiB |       976.00 GiB |                   1 |           1.89% |
|         6.13 TiB |        12.28 TiB |                   2 |          24.42% |
|        11.44 TiB |        34.38 TiB |                   3 |          68.34% |
|       640.00 GiB |         2.53 TiB |                   4 |           5.03% |
|        32.00 GiB |       160.00 GiB |                   5 |           0.31% |

![Replication Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/3/1671089671624.png)
### Deal Data Shared with other Clients
The below table shows how many unique data are shared with other clients.
Usually different applications owns different data and should not resolve to the same CID.

⚠️ CID sharing has been observed.

| Other Client                                                                                                                                                                                                              | Application                                                                                                                     | Total Deals Affected | Unique CIDs |          Verifier |
| :------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ | :------------------------------------------------------------------------------------------------------------------------------ | -------------------: | ----------: | ----------------: |
| [f1pkrmygbvweykpjcut36lf7ewgqdfhjklbhvepda](https://filfox.info/en/address/f1pkrmygbvweykpjcut36lf7ewgqdfhjklbhvepda)                                                                                                     | [Protocol Labs \( project: Slingshot Evergreen \)](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/293) |           407.17 TiB |       2,639 |         LDN # 293 |
| [f14r2jybmccwiu6hze4fu55jyhclktvwacec56hea](https://filfox.info/en/address/f14r2jybmccwiu6hze4fu55jyhclktvwacec56hea)                                                                                                     | [ FilSwan](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/15)                                          |            26.23 TiB |          24 |   LDN v3 multisig |
| [f3ucumnjg35m6fae7bzrxpcvjx3t6t6eezrriqxmr<br/>v3fqnvijnu6et554kmuca6qyfsywp2kmo3af5ruyu<br/>lyva](https://filfox.info/en/address/f3ucumnjg35m6fae7bzrxpcvjx3t6t6eezrriqxmrv3fqnvijnu6et554kmuca6qyfsywp2kmo3af5ruyulyva) | `Glif auto verified`                                                                                                            |            32.00 GiB |           1 | Jonathan Schwartz |
| [f3xcewu5k4ftbxprwqxxwdgqdb7pzvtg26gntnwlu<br/>vfpkkzrviw5mr3rvb5fbu24vkdwercjwb4qdqynuy<br/>smna](https://filfox.info/en/address/f3xcewu5k4ftbxprwqxxwdgqdb7pzvtg26gntnwluvfpkkzrviw5mr3rvb5fbu24vkdwercjwb4qdqynuysmna) | Unknown                                                                                                                         |            32.00 GiB |           1 |           Unknown |

[^1]: To manually trigger this report, add a comment with text `checker:manualTrigger`
