### ISSUE TITLE
[DataCap Application]True Elite Global

### ISSUE THREAD

**Issue by MetaWaveInfo** [filecoin-project/filecoin-plus-large-datasets#300]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: True Elite
- Website / Social Media: https://metawave.info/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):200TiB
- On-chain address for first allocation: f1vmbre2qgafcfizvbmcfdj5k24ouwscp5cavspxi

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
MetaWave is a Web 3.0 data storage and retrieval platform that integrates Data Dashboard, storage, computing, and network core capabilities to provide inter-blockchain (Filecoin Network) communication and web services.
```

What is the primary source of funding for this project?
```
It's from Metawave team.
```

What other projects/ecosystem stakeholders is this project associated with?
```
No.
```

## Use-case details

Describe the data being stored onto Filecoin
```
Filcoin chain data and log data of FIL+Dashboard. We need 5 copies.
```

Where was the data in this dataset sourced from?
```
From Filecoin network.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
[sys-info.2022-02-19.log](https://github.com/filecoin-project/filecoin-plus-large-datasets/files/8252490/sys-info.2022-02-19.log)

```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Sure. These data is public and it can be retrieved by anyone.
```

What is the expected retrieval frequency for this data?
```
This is cold data, so that it's data retrieval should be once a year.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
3 years.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Oceania and Asia.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Both online and offline transfer.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
From filecoin commuinty(slack/telegram/discord) and local storage providers
```

How will you be distributing deals across storage providers?
```
We'll distribute less than 25% of whole deals to each storage provider.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, we can make deals once we get datacap.
```

**Comment by UnionLabs2020** [comment]
A very excellent FIL+ dashboard tool with rich viewing angles.  Very happy to support you!

**Comment by MetaWaveInfo** [comment]
Thanks. When could  we move forward?

**Comment by Sunnyiscoming** [comment]
As you said, you will store Filcoin chain data and log data of FIL+Dashboard. 
But for the understand of these data analysis tools. The amount of data currently does not reach PB level. Can you explain it?

**Comment by MetaWaveInfo** [comment]
Thank you, Sunny. We have contacted several miners who are very interested in our application. However, they also said that they only receive deals with datacap. At present, we may not be able to afford the storage and cloud cost for a long time. I hope PL can support us.

**Comment by Sunnyiscoming** [comment]
@MetaWaveInfo Can you provide more data samples to show that you have 5 PB data already.

**Comment by MetaWaveInfo** [comment]
OK, I  see that the log files every day have exceeded 6.5TiB, which does not include the copies. Only a very small part of the data samples can be presented for your reference. thank you!
[sys-info.2022-06-08.log](https://github.com/filecoin-project/filecoin-plus-large-datasets/files/8867467/sys-info.2022-06-08.log)

**Comment by Sunnyiscoming** [comment]
Data sample cannot be opened, please view it.

**Comment by MetaWaveInfo** [comment]
GitHub is not suitable for storing these large volumes of data. If the size and quantity of data samples are required, it is recommended to specify.

**Comment by Sunnyiscoming** [comment]
It is recommended to provide one or two data samples for different product areas.

**Comment by MetaWaveInfo** [comment]
What we need to store is mainly log files, please check
[sys-info.2022-06-08.log](https://github.com/filecoin-project/filecoin-plus-large-datasets/files/8947796/sys-info.2022-06-08.log)

**Comment by Sunnyiscoming** [comment]
@MetaWaveInfo  Hey. Could you send an email to filplus@fil.org with your official domain in order to confirm your identity?

**Comment by MetaWaveInfo** [comment]
We will prompt this application on our official website in these two days.

**Comment by MetaWaveInfo** [comment]
![image](https://user-images.githubusercontent.com/100760052/176876997-5d81ab0a-9ac9-4651-8682-65e065975843.png)

**Comment by MetaWaveInfo** [comment]
Any update?
![image](https://user-images.githubusercontent.com/100760052/181068243-a54c06c7-17b1-4734-b84a-06872e5bbf5b.png)

**Comment by raghavrmadya** [comment]
Please clarify your relationship with True Elite Global Limited

**Comment by raghavrmadya** [comment]
When did you come into operation? Please justify the request for 5 PiBs. Additionally, please provide more insight into SP allocation

**Comment by MetaWaveInfo** [comment]
> Please clarify your relationship with True Elite Global Limited

Hi Raghav, did you get our biz-certificaiton from your public mailbox? 

I'm Jazz, CEO of True Elite Global Limited. Metawave is our innovative dashborad for FIL+. You can understand it as a product like STARBOARD.  Our allocation plan is find 3-5SP (f01891008/f034710...) to seal our dataset.

**Comment by raghavrmadya** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5 PiB

**Expected weekly DataCap usage rate**

> 200 TiB

**Client address**

> f1vmbre2qgafcfizvbmcfdj5k24ouwscp5cavspxi

**Comment by raghavrmadya** [comment]
Thanks Jazz.

**Comment by UnionLabs2020** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceapgah75vpaalarffgiy4vda22cxsyp7qu34lk7makupb5ww5yei4 
#### Address 
> f1vmbre2qgafcfizvbmcfdj5k24ouwscp5cavspxi
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f17xdri3wunqgld7dm23e4f3eqsntjakwc47xjo6i
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceapgah75vpaalarffgiy4vda22cxsyp7qu34lk7makupb5ww5yei4

**Comment by swatchliu** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec43ob3hnwexit7dnrg7y63h6aub5wyb2yj7qo4b4e6fw344pdwb4 
#### Address 
> f1vmbre2qgafcfizvbmcfdj5k24ouwscp5cavspxi
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1yh6q3nmsg7i2sys7f7dexcuajgoweudcqj2chfi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec43ob3hnwexit7dnrg7y63h6aub5wyb2yj7qo4b4e6fw344pdwb4

**Comment by BigD-Exchange** [comment]
@MetaWaveInfo Hi! Great to see you have gotten approval for DataCap. If you are looking for storage providers to store these data or have any questions, please visit #bigdata-exchange on Filecoin Slack or reply here. 

We have strong demand from a diverse group of SPs, who are actively looking to onboard more data.

**Comment by filplus-checker** [comment]
## DataCap and CID Checker Report[^1]
 - Organization: ``
 - Client: `f1vmbre2qgafcfizvbmcfdj5k24ouwscp5cavspxi`
### Storage Provider Distribution
The below table shows the distribution of storage providers that have stored data for this client.

If this is the first time a provider takes verified deal, it will be marked as `new`.

For most of the datacap application, below restrictions should apply.
 - Storage provider should not exceed 25% of total datacap.
 - Storage provider should not be storing duplicate data for more than 20%.
 - Storage provider should have published its public IP address.
 - All storage providers should be located in different regions.

⚠️ [f01946714](https://filfox.info/en/address/f01946714) has sealed 47.09% of total datacap.

⚠️ 89.68% of total deal sealed by [f01946714](https://filfox.info/en/address/f01946714) are duplicate data.

⚠️ [f01946714](https://filfox.info/en/address/f01946714) has unknown IP location.

⚠️ [f01445167](https://filfox.info/en/address/f01445167) has sealed 26.14% of total datacap.

⚠️ 89.02% of total deal sealed by [f01445167](https://filfox.info/en/address/f01445167) are duplicate data.

⚠️ 77.02% of total deal sealed by [f01927578](https://filfox.info/en/address/f01927578) are duplicate data.

⚠️ [f01927578](https://filfox.info/en/address/f01927578) has unknown IP location.

⚠️ 75.78% of total deal sealed by [f01926749](https://filfox.info/en/address/f01926749) are duplicate data.

⚠️ [f01926749](https://filfox.info/en/address/f01926749) has unknown IP location.

| Provider                                              |                           Location | Total Deals Sealed | Percentage | Unique Data | Duplicate Deals |
| :---------------------------------------------------- | ---------------------------------: | -----------------: | ---------: | ----------: | --------------: |
| [f01946714](https://filfox.info/en/address/f01946714) |                            Unknown |          36.94 TiB |     47.09% |    3.81 TiB |          89.68% |
| [f01445167](https://filfox.info/en/address/f01445167) | Hong Kong, Central and Western, HK |          20.50 TiB |     26.14% |    2.25 TiB |          89.02% |
| [f01927578](https://filfox.info/en/address/f01927578) |                            Unknown |          17.00 TiB |     21.67% |    3.91 TiB |          77.02% |
| [f01926749](https://filfox.info/en/address/f01926749) |                            Unknown |           4.00 TiB |      5.10% |  992.00 GiB |          75.78% |

![Provider Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/300/1671094667402.png)
### Deal Data Replication
The below table shows how each many unique data are replicated across storage providers.
- No more than 25% of unique data are stored with less than 4 providers.

⚠️ 100.00% of deals are for data replicated across less than 4 storage providers.

| Unique Data Size | Total Deals Made | Number of Providers | Deal Percentage |
| ---------------: | ---------------: | ------------------: | --------------: |
|        10.94 TiB |        78.44 TiB |                   1 |         100.00% |

![Replication Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/300/1671094667923.png)
### Deal Data Shared with other Clients
The below table shows how many unique data are shared with other clients.
Usually different applications owns different data and should not resolve to the same CID.

⚠️ CID sharing has been observed.

| Other Client                                                                                                          | Application                                                                                          | Total Deals Affected | Unique CIDs |        Verifier |
| :-------------------------------------------------------------------------------------------------------------------- | :--------------------------------------------------------------------------------------------------- | -------------------: | ----------: | --------------: |
| [f127l5waa4pw6k3sm4e7wxevc4fe5uz7dyt4mxa3i](https://filfox.info/en/address/f127l5waa4pw6k3sm4e7wxevc4fe5uz7dyt4mxa3i) | `Pangod`                                                                                             |            28.06 TiB |         150 | LDN v3 multisig |
| [f1vbe7ze5yknpgu3orinv4zu4rkofsyqfsmpejpui](https://filfox.info/en/address/f1vbe7ze5yknpgu3orinv4zu4rkofsyqfsmpejpui) | [HELIOS](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/305)                |             1.16 TiB |           3 | LDN v3 multisig |
| [f1rkmhotssjif6ucrosls7oewjz6pr2v2eygfjyui](https://filfox.info/en/address/f1rkmhotssjif6ucrosls7oewjz6pr2v2eygfjyui) | `Weipaitang`                                                                                         |           512.00 GiB |           3 | LDN v3 multisig |
| [f1wr6rwwqckh6um2hynaym2t4mniev5b675kbf5ni](https://filfox.info/en/address/f1wr6rwwqckh6um2hynaym2t4mniev5b675kbf5ni) | [Ctrip Global Shopping](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/303) |           128.00 GiB |           3 | LDN v3 multisig |

[^1]: To manually trigger this report, add a comment with text `checker:manualTrigger`

**Comment by cryptowhizzard** [comment]
checker:manualTrigger
