### ISSUE TITLE
[DataCap Application]Ctrip Global Shopping

### ISSUE THREAD

**Issue by TGShopping** [filecoin-project/filecoin-plus-large-datasets#303]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Ctrip Global Shopping
- Website / Social Media: https://g.ctrip.com/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):100TiB
- On-chain address for first allocation: f1wr6rwwqckh6um2hynaym2t4mniev5b675kbf5ni

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Ctrip global Shopping is one of business line for the Trip.com which is the biggest online travel company in the world, It provides tourists the service of shopping strategy ,consulting,discounts, reservations and currency exchange during the trips before, in and after. since it was established in August 2014, with 7300 + partners all over the world to establish cooperation relations, covering 1200 + 45 countries and cities. Types of merchants: outlets, duty free groups, department stores (including airports), brand stores, boutiques, specialty stores, etc.
I'm the financial director of  Ctrip Global Shopping. I hope to reduce our growing storage costs through filecoin. This is our attempt. I hope it can be approved. If you have any questions, please feel free contact me by Email.
```

What is the primary source of funding for this project?
```
We are listed on NASDAQ(code: TCOM) and Hong Kong(code: 09961)
```

What other projects/ecosystem stakeholders is this project associated with?
```
Priceline.com
```

## Use-case details

Describe the data being stored onto Filecoin
```
Suitable for public website data, including but not limited to millions of shopping SKU publicity, real-time exchange rate data archiving of all kinds of foreign currency exchange,and system archive logs.  We normally produce about 30TiB of new data every day, and the current storage amount has exceeded 10PiB. We will take out some data to try filecoin.
```

Where was the data in this dataset sourced from?
```
We produce some by ourselves, and some are produced synchronously with us through the international exchange rate system.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://m.ctrip.com/webapp/fsh5/index?bid=151&ts=1647606965144&s_guid=8B750E78-799F-4BCA-94E1-60050D52561C
https://m.ctrip.com/webapp/gshop/home/index?destid=14&share=1&bid=14&s_guid=43F582CA-29B6-4AFF-A72E-5D81BEB015B4
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Sure. These data is public and it can be retrieved by anyone.
```

What is the expected retrieval frequency for this data?
```
This is just one of our redundant backups, which does not require frequent access.Maybe every  6 months.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
I hope it's long-term.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Greater China or somewhere in Asia.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Both online and offline would be OK.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We would find suitable local storage providers on slack.
```

How will you be distributing deals across storage providers?
```
We plan to distribute deals to 10+ providers at least in the front 4 weeks.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Of course, the funds are enough and we can pay easily.
```

**Comment by XnMatrixSV** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedenapeteoyyrw4q6jyjo2orvlsmqmmpvdxjtfrtoe4yyx3rnc67e 
#### Address 
> f1wr6rwwqckh6um2hynaym2t4mniev5b675kbf5ni
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1yuz2twsllparyfqwslfiuxrc5wj4mfiflvnsw6a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedenapeteoyyrw4q6jyjo2orvlsmqmmpvdxjtfrtoe4yyx3rnc67e

**Comment by rayshitou** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced5xuidw3ecopifuiic7agsctok4dpfriepwbuqbsibhsxn2jtiow 
#### Address 
> f1wr6rwwqckh6um2hynaym2t4mniev5b675kbf5ni
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f136bz32l2hlyad4npmfg5dngcdw3jk3tpcpoz2ja
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced5xuidw3ecopifuiic7agsctok4dpfriepwbuqbsibhsxn2jtiow

**Comment by Fenbushi-Filecoin** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecaz5e2n2ztpneoguid34le5pepzebctmkdx7ostfhmq4vrpeg35c 
#### Address 
> f1wr6rwwqckh6um2hynaym2t4mniev5b675kbf5ni
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1yqydpmqb5en262jpottko2kd65msajax7fi4rmq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecaz5e2n2ztpneoguid34le5pepzebctmkdx7ostfhmq4vrpeg35c

**Comment by XnMatrixSV** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacea7m3o67jjp27tk6aegf7axwef2d6s6e7byg5xc2xe6gxpyhslaj2 
#### Address 
> f1wr6rwwqckh6um2hynaym2t4mniev5b675kbf5ni
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1yuz2twsllparyfqwslfiuxrc5wj4mfiflvnsw6a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacea7m3o67jjp27tk6aegf7axwef2d6s6e7byg5xc2xe6gxpyhslaj2

**Comment by swatchliu** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceds5afuotrux6nh66amcc6h3xpnufyovue6aenm2n7c2fsiqrusaa 
#### Address 
> f1wr6rwwqckh6um2hynaym2t4mniev5b675kbf5ni
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1yh6q3nmsg7i2sys7f7dexcuajgoweudcqj2chfi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceds5afuotrux6nh66amcc6h3xpnufyovue6aenm2n7c2fsiqrusaa

**Comment by KodaRobotDog** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebutkuj6wlu6ig26ixj6qppaeh3poihpk7pp5rskfv3x2a55n3a3y 
#### Address 
> f1wr6rwwqckh6um2hynaym2t4mniev5b675kbf5ni
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1jyalts5uhtmp5sbbssse23toshvsqbbtjgukm5a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebutkuj6wlu6ig26ixj6qppaeh3poihpk7pp5rskfv3x2a55n3a3y

**Comment by rayshitou** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebv36py63scuzgv4dpsd2vh4yb5ucwn3yebrfbmpgtmvsy6zzh25c 
#### Address 
> f1wr6rwwqckh6um2hynaym2t4mniev5b675kbf5ni
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f136bz32l2hlyad4npmfg5dngcdw3jk3tpcpoz2ja
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebv36py63scuzgv4dpsd2vh4yb5ucwn3yebrfbmpgtmvsy6zzh25c

**Comment by UnionLabs2020** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceblufdjvr2ydtzoinln6id62t6f4xglbe35i3nxlvvqqkuse4tlca 
#### Address 
> f1wr6rwwqckh6um2hynaym2t4mniev5b675kbf5ni
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f17xdri3wunqgld7dm23e4f3eqsntjakwc47xjo6i
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceblufdjvr2ydtzoinln6id62t6f4xglbe35i3nxlvvqqkuse4tlca

**Comment by MetaWaveInfo** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced2qoz3gapi4jo4ax4xux3izmpifz4nstzmrduwkgws6orayug7ma 
#### Address 
> f1wr6rwwqckh6um2hynaym2t4mniev5b675kbf5ni
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1ktlkcxnmzxcdaoqfsunrg3vocfbmgv4n3mrn74a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced2qoz3gapi4jo4ax4xux3izmpifz4nstzmrduwkgws6orayug7ma

**Comment by BigD-Exchange** [comment]
@TGShopping Hi! Great to see you have gotten approval for DataCap. If you are looking for storage providers to store these data or have any questions, please visit #bigdata-exchange on Filecoin Slack or reply here. 

We have strong demand from a diverse group of SPs, who are actively looking to onboard more data.

**Comment by swatchliu** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebsayooaxl3qzfqb4hzslzricy724tnipyfhzlpd4zichd4x2ten2 
#### Address 
> f1wr6rwwqckh6um2hynaym2t4mniev5b675kbf5ni
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1yh6q3nmsg7i2sys7f7dexcuajgoweudcqj2chfi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebsayooaxl3qzfqb4hzslzricy724tnipyfhzlpd4zichd4x2ten2

**Comment by kernelogic** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebntaj64ltrgk2b7rkogtngghtbnr4cfjm6dbovnvzv26c6dm5cdg 
#### Address 
> f1wr6rwwqckh6um2hynaym2t4mniev5b675kbf5ni
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebntaj64ltrgk2b7rkogtngghtbnr4cfjm6dbovnvzv26c6dm5cdg

**Comment by MetaWaveInfo** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaqh5hydjqwyl6snh3ivtpyqnvaths4ook5xdxm6lahp3sswarcmu 
#### Address 
> f1wr6rwwqckh6um2hynaym2t4mniev5b675kbf5ni
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1ktlkcxnmzxcdaoqfsunrg3vocfbmgv4n3mrn74a
#### Id
> c2de2c9e-668e-4f3a-ad8e-134582539dd6
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaqh5hydjqwyl6snh3ivtpyqnvaths4ook5xdxm6lahp3sswarcmu

**Comment by filplus-checker** [comment]
## DataCap and CID Checker Report[^1]
 - Organization: `Ctrip Global Shopping`
 - Client: `f1wr6rwwqckh6um2hynaym2t4mniev5b675kbf5ni`
### Storage Provider Distribution
The below table shows the distribution of storage providers that have stored data for this client.

If this is the first time a provider takes verified deal, it will be marked as `new`.

For most of the datacap application, below restrictions should apply.
 - Storage provider should not exceed 25% of total datacap.
 - Storage provider should not be storing duplicate data for more than 20%.
 - Storage provider should have published its public IP address.
 - All storage providers should be located in different regions.

⚠️ [f01946714](https://filfox.info/en/address/f01946714) has sealed 33.91% of total datacap.

⚠️ 88.90% of total deal sealed by [f01946714](https://filfox.info/en/address/f01946714) are duplicate data.

⚠️ [f01946714](https://filfox.info/en/address/f01946714) has unknown IP location.

⚠️ 89.67% of total deal sealed by [f0136399](https://filfox.info/en/address/f0136399) are duplicate data.

⚠️ 65.12% of total deal sealed by [f01841131](https://filfox.info/en/address/f01841131) are duplicate data.

⚠️ 75.28% of total deal sealed by [f01927574](https://filfox.info/en/address/f01927574) are duplicate data.

⚠️ [f01927574](https://filfox.info/en/address/f01927574) has unknown IP location.

⚠️ 44.73% of total deal sealed by [f01841133](https://filfox.info/en/address/f01841133) are duplicate data.

⚠️ 39.33% of total deal sealed by [f01843749](https://filfox.info/en/address/f01843749) are duplicate data.

⚠️ 78.05% of total deal sealed by [f01927578](https://filfox.info/en/address/f01927578) are duplicate data.

⚠️ [f01927578](https://filfox.info/en/address/f01927578) has unknown IP location.

⚠️ 87.69% of total deal sealed by [f01520](https://filfox.info/en/address/f01520) are duplicate data.

⚠️ [f01520](https://filfox.info/en/address/f01520) has unknown IP location.

⚠️ 59.41% of total deal sealed by [f01877862](https://filfox.info/en/address/f01877862) are duplicate data.

⚠️ 73.75% of total deal sealed by [f01688](https://filfox.info/en/address/f01688) are duplicate data.

⚠️ [f01688](https://filfox.info/en/address/f01688) has unknown IP location.

⚠️ 63.32% of total deal sealed by [f01392600](https://filfox.info/en/address/f01392600) are duplicate data.

⚠️ 68.23% of total deal sealed by [f0103710](https://filfox.info/en/address/f0103710) are duplicate data.

⚠️ [f0103710](https://filfox.info/en/address/f0103710) has unknown IP location.

| Provider                                                    |                           Location | Total Deals Sealed | Percentage | Unique Data | Duplicate Deals |
| :---------------------------------------------------------- | ---------------------------------: | -----------------: | ---------: | ----------: | --------------: |
| [f01946714](https://filfox.info/en/address/f01946714)       |                            Unknown |         514.44 TiB |     33.91% |   57.13 TiB |          88.90% |
| [f0136399](https://filfox.info/en/address/f0136399)         | Hong Kong, Central and Western, HK |         250.50 TiB |     16.51% |   25.88 TiB |          89.67% |
| [f01841131](https://filfox.info/en/address/f01841131)       | Hong Kong, Central and Western, HK |         119.97 TiB |      7.91% |   41.84 TiB |          65.12% |
| [f01927574](https://filfox.info/en/address/f01927574)`new`  |                            Unknown |         117.94 TiB |      7.77% |   29.16 TiB |          75.28% |
| [f01841133](https://filfox.info/en/address/f01841133)       |           Singapore, Singapore, SG |         106.53 TiB |      7.02% |   58.88 TiB |          44.73% |
| [f01843749](https://filfox.info/en/address/f01843749)       | Hong Kong, Central and Western, HK |          89.06 TiB |      5.87% |   54.03 TiB |          39.33% |
| [f01927578](https://filfox.info/en/address/f01927578)       |                            Unknown |          84.00 TiB |      5.54% |   18.44 TiB |          78.05% |
| [f01520](https://filfox.info/en/address/f01520)             |                            Unknown |          60.91 TiB |      4.01% |    7.50 TiB |          87.69% |
| [f01877862](https://filfox.info/en/address/f01877862)       |                   Seoul, Seoul, KR |          49.97 TiB |      3.29% |   20.28 TiB |          59.41% |
| [f01688](https://filfox.info/en/address/f01688)`new`        |                            Unknown |          41.19 TiB |      2.72% |   10.81 TiB |          73.75% |
| [f01841134](https://filfox.info/en/address/f01841134)       |           Singapore, Singapore, SG |          37.91 TiB |      2.50% |   31.84 TiB |          15.99% |
| [f01392600](https://filfox.info/en/address/f01392600)       | Hong Kong, Central and Western, HK |          23.00 TiB |      1.52% |    8.44 TiB |          63.32% |
| [f0103710](https://filfox.info/en/address/f0103710)         |                            Unknown |          19.97 TiB |      1.32% |    6.34 TiB |          68.23% |
| [f01823070](https://filfox.info/en/address/f01823070)`new`  |            Shenzhen, Guangdong, CN |           1.66 TiB |      0.11% |    1.66 TiB |           0.00% |

![Provider Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/303/1671094684523.png)
### Deal Data Replication
The below table shows how each many unique data are replicated across storage providers.
- No more than 25% of unique data are stored with less than 4 providers.

⚠️ 100.00% of deals are for data replicated across less than 4 storage providers.

| Unique Data Size | Total Deals Made | Number of Providers | Deal Percentage |
| ---------------: | ---------------: | ------------------: | --------------: |
|       268.31 TiB |         1.18 PiB |                   1 |          79.44% |
|        29.69 TiB |       183.34 TiB |                   2 |          12.09% |
|        14.84 TiB |       128.63 TiB |                   3 |           8.48% |

![Replication Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/303/1671094685301.png)
### Deal Data Shared with other Clients
The below table shows how many unique data are shared with other clients.
Usually different applications owns different data and should not resolve to the same CID.

⚠️ CID sharing has been observed.

| Other Client                                                                                                                                                                                                              | Application                                                                                                                    | Total Deals Affected | Unique CIDs |        Verifier |
| :------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ | :----------------------------------------------------------------------------------------------------------------------------- | -------------------: | ----------: | --------------: |
| [f1rkmhotssjif6ucrosls7oewjz6pr2v2eygfjyui](https://filfox.info/en/address/f1rkmhotssjif6ucrosls7oewjz6pr2v2eygfjyui)                                                                                                     | `Weipaitang`                                                                                                                   |           146.41 TiB |       1,101 | LDN v3 multisig |
| [f127l5waa4pw6k3sm4e7wxevc4fe5uz7dyt4mxa3i](https://filfox.info/en/address/f127l5waa4pw6k3sm4e7wxevc4fe5uz7dyt4mxa3i)                                                                                                     | `Pangod`                                                                                                                       |           110.69 TiB |       1,073 | LDN v3 multisig |
| [f1ibuglt2lzlyf7vnmtzmuykcfgl2pn2fxym5dibi](https://filfox.info/en/address/f1ibuglt2lzlyf7vnmtzmuykcfgl2pn2fxym5dibi)                                                                                                     | [Appstest](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/346)                                        |            74.27 TiB |       1,057 | LDN v3 multisig |
| [f1vykg3elgzoa3lpzf5xo6rbcghzr5ifat757mucq](https://filfox.info/en/address/f1vykg3elgzoa3lpzf5xo6rbcghzr5ifat757mucq)                                                                                                     | [Hailiang Mingyou Online](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/51)                          |            70.66 TiB |       1,153 |        LDN # 51 |
| [f1ugo3abkmmb4pb2atxz5oqqgwsd27b4p6k52f2va](https://filfox.info/en/address/f1ugo3abkmmb4pb2atxz5oqqgwsd27b4p6k52f2va)                                                                                                     | [Yuepass Technology Company Limited](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/429)              |            67.25 TiB |         482 | LDN v3 multisig |
| [f1xwmnlen7j7qlkktm3oqggzcbrxp6cvqnkd2wipa](https://filfox.info/en/address/f1xwmnlen7j7qlkktm3oqggzcbrxp6cvqnkd2wipa)                                                                                                     | ``                                                                                                                             |            66.28 TiB |         669 |       LDN # 121 |
| [f1fq6abg47ifgeee2z7q2rps3tvknoo2ztcoqy7ai](https://filfox.info/en/address/f1fq6abg47ifgeee2z7q2rps3tvknoo2ztcoqy7ai)                                                                                                     | [DaYe Art Tuition Class \(DKArt\) ](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/888)               |            49.75 TiB |         206 | LDN v3 multisig |
| [f1csetl7nor3qie2cehx7axf2ai3nedmowj53xwsa](https://filfox.info/en/address/f1csetl7nor3qie2cehx7axf2ai3nedmowj53xwsa)                                                                                                     | [NOAA GOES\-\-\-Piero](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1112)                           |            44.91 TiB |         261 | LDN v3 multisig |
| [f1quofpadzcqlonmz7v3mv7dfqvm5hdztucdsjqsy](https://filfox.info/en/address/f1quofpadzcqlonmz7v3mv7dfqvm5hdztucdsjqsy)                                                                                                     | [HENAN 863 SOFTWARE CO\., LTD](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/468)                    |            33.50 TiB |         100 | LDN v3 multisig |
| [f1cf2pp6bgu6vvxfuau6bsmiibhrc7v3gvjsyseay](https://filfox.info/en/address/f1cf2pp6bgu6vvxfuau6bsmiibhrc7v3gvjsyseay)                                                                                                     | [Public Data\-FlyBrain](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1013)                          |            32.81 TiB |         230 | LDN v3 multisig |
| [f1bb2z36lpq3pnwiiowiraagpzqnpow4bonjacx7a](https://filfox.info/en/address/f1bb2z36lpq3pnwiiowiraagpzqnpow4bonjacx7a)                                                                                                     | [Hola Space](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/362)                                      |            27.09 TiB |          87 | LDN v3 multisig |
| [f3q7ablez3jqkcjukwbzaql7lmbx4ldouu66nexpd<br/>cfvu6kgho3v6gricckt77cgr46tdre2l4zmvha7bs<br/>u7qq](https://filfox.info/en/address/f3q7ablez3jqkcjukwbzaql7lmbx4ldouu66nexpdcfvu6kgho3v6gricckt77cgr46tdre2l4zmvha7bsu7qq) | `MatrixStorage`                                                                                                                |            21.48 TiB |         479 |        LDN # 72 |
| [f1vbe7ze5yknpgu3orinv4zu4rkofsyqfsmpejpui](https://filfox.info/en/address/f1vbe7ze5yknpgu3orinv4zu4rkofsyqfsmpejpui)                                                                                                     | [HELIOS](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/305)                                          |            16.16 TiB |         290 | LDN v3 multisig |
| [f3skkellc7wegakh2blqeu4kkrlzuqy2siymwli7s<br/>ec6eq77c2v4kzgz5ozgnasjl5r52ckameba5kds7h<br/>djda](https://filfox.info/en/address/f3skkellc7wegakh2blqeu4kkrlzuqy2siymwli7sec6eq77c2v4kzgz5ozgnasjl5r52ckameba5kds7hdjda) | [Meizhai Technology](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/75)                               |            15.97 TiB |         392 | LDN v3 multisig |
| [f3woqxpu6ekmj43nmpcv7j2pgu6lejxtzgxpzl6f2<br/>vrueoqlzjntakyhdkghymyffbzfbsio6dvfmy643x<br/>4y7q](https://filfox.info/en/address/f3woqxpu6ekmj43nmpcv7j2pgu6lejxtzgxpzl6f2vrueoqlzjntakyhdkghymyffbzfbsio6dvfmy643x4y7q) | [RICH ST PETE LLC](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/64)                                 |            12.36 TiB |         339 | LDN v3 multisig |
| [f1a2rdwwor3kq6mv7nveuxhux7rxtj6iyjs7hfswa](https://filfox.info/en/address/f1a2rdwwor3kq6mv7nveuxhux7rxtj6iyjs7hfswa)                                                                                                     | [Worldkan](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/902)                                        |            11.72 TiB |          75 | LDN v3 multisig |
| [f3rncwz3qo2bwnsrfjc7kq53xr7yi2lctcydtllxo<br/>zmszndvttou7n565yb6aqssvn4omyf5m7q62qpfmq<br/>cbwq](https://filfox.info/en/address/f3rncwz3qo2bwnsrfjc7kq53xr7yi2lctcydtllxozmszndvttou7n565yb6aqssvn4omyf5m7q62qpfmqcbwq) | [VillageOne Space LLCVillageOne Space LLC](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/39)         |             5.72 TiB |          94 |        LDN # 39 |
| [f3u3unadf654vezf62cd4jo6r7h6qpkx26g5amcdc<br/>3oe6rmpmk2nfosfd2kjkdhj4ndvr626gsm7fhpmt7<br/>gg2q](https://filfox.info/en/address/f3u3unadf654vezf62cd4jo6r7h6qpkx26g5amcdc3oe6rmpmk2nfosfd2kjkdhj4ndvr626gsm7fhpmt7gg2q) | [Runtu Information Technology](https://github.com/filecoin-project/filecoin-plus-client-onboarding/issues/1150)                |             4.28 TiB |          29 |       Steven Li |
| [f1qnhjr2kq742poi6rukv5hji5rdrtuqsib7khz3a](https://filfox.info/en/address/f1qnhjr2kq742poi6rukv5hji5rdrtuqsib7khz3a)                                                                                                     | [GLOBAL UNIT\-A Corp\.](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/110)                           |             3.25 TiB |          46 |       LDN # 110 |
| [f1yswits4hd4zu6n2pl7nk7cspcuieuzl7btjn5ia](https://filfox.info/en/address/f1yswits4hd4zu6n2pl7nk7cspcuieuzl7btjn5ia)                                                                                                     | [TaoPaiPai](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/54)                                        |             2.69 TiB |          54 |        LDN # 54 |
| [f1znd7uramgqquelcgefo5xgozopd3nga73hhywpy](https://filfox.info/en/address/f1znd7uramgqquelcgefo5xgozopd3nga73hhywpy)                                                                                                     | [BotSmart ](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/373)                                       |             2.63 TiB |          30 | LDN v3 multisig |
| [f3xffjctbyy7zigopfa3za5ha3pvv4z3xfghlw7kw<br/>vyeuabkg4lzsgfwhnghwkvmmvi6yso6k52hq3ca6c<br/>kveq](https://filfox.info/en/address/f3xffjctbyy7zigopfa3za5ha3pvv4z3xfghlw7kwvyeuabkg4lzsgfwhnghwkvmmvi6yso6k52hq3ca6ckveq) | [Chengdu Digital Media Industry Base Co\., Ltd\.](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/387) |             1.81 TiB |          39 | LDN v3 multisig |
| [f162jayw3utjlbp5ae6ssqghm5jrl3js32dbmnfja](https://filfox.info/en/address/f162jayw3utjlbp5ae6ssqghm5jrl3js32dbmnfja)                                                                                                     | ``                                                                                                                             |             1.75 TiB |           9 |       LDN # 121 |
| [f1tmuircaaenwvffdmyuydcqlidfxvgvg2wsj344i](https://filfox.info/en/address/f1tmuircaaenwvffdmyuydcqlidfxvgvg2wsj344i)                                                                                                     | [Myserver](https://github.com/filecoin-project/filecoin-plus-client-onboarding/issues/447)                                     |             1.50 TiB |          47 |    Tim Williams |
| [f1vmbre2qgafcfizvbmcfdj5k24ouwscp5cavspxi](https://filfox.info/en/address/f1vmbre2qgafcfizvbmcfdj5k24ouwscp5cavspxi)                                                                                                     | ``                                                                                                                             |           608.00 GiB |           3 | LDN v3 multisig |
| [f1tgii4xgcp6um4n2w7eqaw6bwvnvyii2u7cjgzka](https://filfox.info/en/address/f1tgii4xgcp6um4n2w7eqaw6bwvnvyii2u7cjgzka)                                                                                                     | [Meson\.Network ](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/187)                                 |           512.00 GiB |           3 | LDN v3 multisig |
| [f1avfkllpeqlx32bwjcka6y27scftpl5nzh754yly](https://filfox.info/en/address/f1avfkllpeqlx32bwjcka6y27scftpl5nzh754yly)                                                                                                     | ``                                                                                                                             |           416.00 GiB |          13 |     Zhehao Chen |
| [f1k2pbx376s46c72ouwrg2avyvrglj66u76opbsqa](https://filfox.info/en/address/f1k2pbx376s46c72ouwrg2avyvrglj66u76opbsqa)                                                                                                     | [aifabot inc](https://github.com/filecoin-project/filecoin-plus-client-onboarding/issues/566)                                  |            32.00 GiB |           1 |    Dr. Ann Shin |
| [f1b7p57icxibagtqcr2opw74bjyjw5mc7eclcu64y](https://filfox.info/en/address/f1b7p57icxibagtqcr2opw74bjyjw5mc7eclcu64y)                                                                                                     | Unknown                                                                                                                        |            16.00 GiB |           1 |         Unknown |

[^1]: To manually trigger this report, add a comment with text `checker:manualTrigger`
