### ISSUE TITLE
[DataCap Application] Slingshot Brazil Data Cube dataset for team Kernelogic

### ISSUE THREAD

**Issue by kernelogic** [filecoin-project/filecoin-plus-large-datasets#304]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Fei Yan - Kernelogic
- Website / Social Media: https://slingshot.kernelogic.ca/ @feiya200
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 2PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 200 TiB
- On-chain address for first allocation: f1j6pwjnuo5a6s4ou7emsx6jymam5nu4es7ogf7tq
- **I am the original requester for adding this dataset to slingshot** https://github.com/filecoin-project/slingshot/issues/526

## Project details

Share a brief history of your project and organization.
```
I have participated every Slingshot phase and is probably the best performing as a "small individual client". 

I have successfully completed a few LDNs on other datasets and I have record to show I have been following the rules of decentralization and have zero self dealing.

https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/60
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/59
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/46
```

What is the primary source of funding for this project?
```
I am hoping to utilize this datacap at no cost, on active community providers on Slack, especially SPX / Slingshot Restore / enterprise-sp-wg members. 

I expect to receive prize from Slingshot as return of my effort as I need to spend a lot time preparing dataset, bandwidth, hardware and communicating with providers.
```

What other projects/ecosystem stakeholders is this project associated with?
```
Slingshot, MinerX, enterprise-sp-wp.
```

## Use-case details

Describe the data being stored onto Filecoin
```
A research, development and technological innovation project of the National Institute for Space Research (INPE), Brazil, producing datasets from big volumes of medium-resolution remote sensing images.
```

Where was the data in this dataset sourced from?
```
https://registry.opendata.aws/brazil-data-cubes
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://bdc-sentinel-2.s3.amazonaws.com/s2-16d/v1/071/090/2017/01/01/S2-16D_V1_071090_20170101_CLEAROB.tif
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes
```

What is the expected retrieval frequency for this data?
```
I am expecting some retrievals during prize judging period, as well as anyone interested in downloading this dataset.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
As slingshot rule, minimum 1 year. 
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
All regions.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
I will upload my prepared CAR files to a web server and coordinate with providers to download and propose offline deals.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
I plan to deal with SPX, approved slingshot restore SPs and enterprise-sp-wg members, as well as any real community providers who are interested.
```

How will you be distributing deals across storage providers?
```
Evenly across all providers I propose to, if they can handle. If a miner is a notary itself, this notary will receive no more than 10% of the total granted datacap.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
I have all I need to start making deals.
```

**Comment by galen-mcandrew** [comment]
## Multisig Notary requested
#### Total DataCap requested 
> 2PiB
#### Expected weekly DataCap usage rate 
> 200TiB

**Comment by swatchliu** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec523dxaqzwimmmr3y6w7uxxuy7psgdhnvfdfyi5kiitfjisaeuys 
#### Address 
> f1j6pwjnuo5a6s4ou7emsx6jymam5nu4es7ogf7tq
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1yh6q3nmsg7i2sys7f7dexcuajgoweudcqj2chfi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec523dxaqzwimmmr3y6w7uxxuy7psgdhnvfdfyi5kiitfjisaeuys

**Comment by MegTei** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedgkgrlrbav5weihrjlrvyuo2aryr6p5la2vlmwju5qdykokzadna 
#### Address 
> f1j6pwjnuo5a6s4ou7emsx6jymam5nu4es7ogf7tq
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1ystxl2ootvpirpa7ebgwl7vlhwkbx2r4zjxwe5i
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedgkgrlrbav5weihrjlrvyuo2aryr6p5la2vlmwju5qdykokzadna

**Comment by dkkapur** [comment]
Looks like the original allocation did go through, but the address is now at zero. Subsequent allocation bot / automated checks are down at the moment, so requested the next batch manually. 
![image](https://user-images.githubusercontent.com/2343218/164392312-b63011ce-cd9d-4208-b253-db9f651f7e49.png)

**Comment by dkkapur** [comment]
## DataCap Allocation requested

#### Multisig Notary address
> f01814935

#### Client address
> f1j6pwjnuo5a6s4ou7emsx6jymam5nu4es7ogf7tq

#### DataCap allocation requested
> 200TiB

**Comment by flyworker** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedt4dqfkg76gsdeuslf4lktxpnix32hiq3ec3tr7nn7p65wrfnsga 
#### Address 
> f1j6pwjnuo5a6s4ou7emsx6jymam5nu4es7ogf7tq
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1hlubjsdkv4wmsdadihloxgwrz3j3ernf6i3cbpy
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedt4dqfkg76gsdeuslf4lktxpnix32hiq3ec3tr7nn7p65wrfnsga

**Comment by Fenbushi-Filecoin** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebofgajy5r7g4bwccaltf4iccymlkzlh5zyqktawliedpak3bprla 
#### Address 
> f1j6pwjnuo5a6s4ou7emsx6jymam5nu4es7ogf7tq
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1yqydpmqb5en262jpottko2kd65msajax7fi4rmq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebofgajy5r7g4bwccaltf4iccymlkzlh5zyqktawliedpak3bprla

**Comment by neogeweb3** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedtxv5wkidcyv3jlr2wej4vcbungiec2s6h3q23uainqp67tfrd5k 
#### Address 
> f1j6pwjnuo5a6s4ou7emsx6jymam5nu4es7ogf7tq
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f13k5zr6ovc2gjmg3lvd43ladbydhovpylcvbflpa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedtxv5wkidcyv3jlr2wej4vcbungiec2s6h3q23uainqp67tfrd5k

**Comment by kernelogic** [comment]
@fabriziogianni7 @dkkapur 
![image](https://user-images.githubusercontent.com/3711825/166391721-974c6e29-dbcc-4df4-bd44-f71e1a06f555.png)

**Comment by dkkapur** [comment]
@fabriziogianni7 SA bot seems to have stalled on this issue again.

**Comment by Reiers** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebtm73mvgt5ik7ktwpjcsfw3ewsashdn3bxyidgov32jf4yplpivu 
#### Address 
> f1j6pwjnuo5a6s4ou7emsx6jymam5nu4es7ogf7tq
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1oz43ckvmtxmmsfzqm6bpnemqlavz4ifyl524chq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebtm73mvgt5ik7ktwpjcsfw3ewsashdn3bxyidgov32jf4yplpivu

**Comment by cryptowhizzard** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebsbuswqplxxvgs56j3fm5qp4vyz6ectllyik3lmmr4pinpk7gu3c 
#### Address 
> f1j6pwjnuo5a6s4ou7emsx6jymam5nu4es7ogf7tq
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1krmypm4uoxxf3g7okrwtrahlmpcph3y7rbqqgfa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebsbuswqplxxvgs56j3fm5qp4vyz6ectllyik3lmmr4pinpk7gu3c

**Comment by MegTei** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaibiat6v5ixx25c4miuleowfl35rloct4gj724zbxvnqsa5ju2b2 
#### Address 
> f1j6pwjnuo5a6s4ou7emsx6jymam5nu4es7ogf7tq
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1ystxl2ootvpirpa7ebgwl7vlhwkbx2r4zjxwe5i
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaibiat6v5ixx25c4miuleowfl35rloct4gj724zbxvnqsa5ju2b2

**Comment by kernelogic** [comment]
@galen-mcandrew @dkkapur Please change the status of this issue. It's stuck. Can't proceed to sign.

Transactions:  1
ID      State    Approvals  To      Value   Method                Params
4       pending  1          f06     0 FIL   AddVerifiedClient(4)  {"Address":"f1j6pwjnuo5a6s4ou7emsx6jymam5nu4es7ogf7tq","Allowance":"879609302220800"}

**Comment by flyworker** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec3rv25auvf7wlpg6cscli62yp3y3b6rzynfegzm7e6kij7kfyte4 
#### Address 
> f1j6pwjnuo5a6s4ou7emsx6jymam5nu4es7ogf7tq
#### Datacap Allocated
> 1.12PiB
#### Signer Address
> f1hlubjsdkv4wmsdadihloxgwrz3j3ernf6i3cbpy
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec3rv25auvf7wlpg6cscli62yp3y3b6rzynfegzm7e6kij7kfyte4

**Comment by psh0691** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaan73o2had6y2562exijjepk47qmmnmtrkzynea4elzcnletbijy 
#### Address 
> f1j6pwjnuo5a6s4ou7emsx6jymam5nu4es7ogf7tq
#### Datacap Allocated
> 348.00TiB
#### Signer Address
> f1qdko4jg25vo35qmyvcrw4ak4fmuu3f5rif2kc7i
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaan73o2had6y2562exijjepk47qmmnmtrkzynea4elzcnletbijy

**Comment by xingjitansuo** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacednxmg3yalkawjbxxo6yyfbvqhagnzuyfr6ad56vjnkw65newgh4w 
#### Address 
> f1j6pwjnuo5a6s4ou7emsx6jymam5nu4es7ogf7tq
#### Datacap Allocated
> 348.00TiB
#### Signer Address
> f1a2lia2cwwekeubwo4nppt4v4vebxs2frozarz3q
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacednxmg3yalkawjbxxo6yyfbvqhagnzuyfr6ad56vjnkw65newgh4w

**Comment by kernelogic** [comment]
All allocated and competition concluded. Closing this issue now. Thank you very much all!

**Comment by filplus-checker** [comment]
## DataCap and CID Checker Report[^1]
 - Organization: `Fei Yan - Kernelogic`
 - Client: `f1j6pwjnuo5a6s4ou7emsx6jymam5nu4es7ogf7tq`
### Storage Provider Distribution
The below table shows the distribution of storage providers that have stored data for this client.

If this is the first time a provider takes verified deal, it will be marked as `new`.

For most of the datacap application, below restrictions should apply.
 - Storage provider should not exceed 25% of total datacap.
 - Storage provider should not be storing duplicate data for more than 20%.
 - Storage provider should have published its public IP address.
 - All storage providers should be located in different regions.

⚠️ 29.47% of total deal sealed by [f01840219](https://filfox.info/en/address/f01840219) are duplicate data.

⚠️ 48.96% of total deal sealed by [f047419](https://filfox.info/en/address/f047419) are duplicate data.

⚠️ [f020378](https://filfox.info/en/address/f020378) has unknown IP location.

| Provider                                                    |                               Location | Total Deals Sealed | Percentage | Unique Data | Duplicate Deals |
| :---------------------------------------------------------- | -------------------------------------: | -----------------: | ---------: | ----------: | --------------: |
| [f01840219](https://filfox.info/en/address/f01840219)       |                   Chengdu, Sichuan, CN |         190.22 TiB |      9.32% |  134.16 TiB |          29.47% |
| [f03223](https://filfox.info/en/address/f03223)             |               San Jose, California, US |         182.50 TiB |      8.94% |  182.50 TiB |           0.00% |
| [f02301](https://filfox.info/en/address/f02301)             |               San Jose, California, US |         175.41 TiB |      8.59% |  175.41 TiB |           0.00% |
| [f0240185](https://filfox.info/en/address/f0240185)         |                Clifton, New Jersey, US |         164.34 TiB |      8.05% |  164.34 TiB |           0.00% |
| [f0143858](https://filfox.info/en/address/f0143858)         |                Clifton, New Jersey, US |         164.22 TiB |      8.04% |  164.22 TiB |           0.00% |
| [f01879914](https://filfox.info/en/address/f01879914)       |               San Jose, California, US |         106.22 TiB |      5.20% |  106.22 TiB |           0.00% |
| [f01850141](https://filfox.info/en/address/f01850141)       |     Hong Kong, Central and Western, HK |         106.06 TiB |      5.20% |  106.06 TiB |           0.00% |
| [f01863339](https://filfox.info/en/address/f01863339)       |                 Shanghai, Shanghai, CN |         106.00 TiB |      5.19% |  106.00 TiB |           0.00% |
| [f01864434](https://filfox.info/en/address/f01864434)`new`  |            Sydney, New South Wales, AU |          91.69 TiB |      4.49% |   89.50 TiB |           2.39% |
| [f01878005](https://filfox.info/en/address/f01878005)       |               Singapore, Singapore, SG |          88.03 TiB |      4.31% |   88.03 TiB |           0.00% |
| [f01880047](https://filfox.info/en/address/f01880047)       |               Singapore, Singapore, SG |          88.03 TiB |      4.31% |   88.03 TiB |           0.00% |
| [f01882184](https://filfox.info/en/address/f01882184)`new`  |               Singapore, Singapore, SG |          88.00 TiB |      4.31% |   88.00 TiB |           0.00% |
| [f01877571](https://filfox.info/en/address/f01877571)       |               Singapore, Singapore, SG |          88.00 TiB |      4.31% |   88.00 TiB |           0.00% |
| [f01882177](https://filfox.info/en/address/f01882177)       |               Singapore, Singapore, SG |          88.00 TiB |      4.31% |   88.00 TiB |           0.00% |
| [f01702940](https://filfox.info/en/address/f01702940)       |                      Dallas, Texas, US |          72.69 TiB |      3.56% |   72.69 TiB |           0.00% |
| [f01652333](https://filfox.info/en/address/f01652333)       |              Sunnyvale, California, US |          64.75 TiB |      3.17% |   64.75 TiB |           0.00% |
| [f09848](https://filfox.info/en/address/f09848)             | Rancho Santa Margarita, California, US |          54.69 TiB |      2.68% |   54.69 TiB |           0.00% |
| [f01823264](https://filfox.info/en/address/f01823264)       |                   Chengdu, Sichuan, CN |          41.06 TiB |      2.01% |   41.06 TiB |           0.00% |
| [f01918046](https://filfox.info/en/address/f01918046)       |         Kuala Lumpur, Kuala Lumpur, MY |          18.75 TiB |      0.92% |   18.75 TiB |           0.00% |
| [f01794835](https://filfox.info/en/address/f01794835)       |                   Chengdu, Sichuan, CN |          18.72 TiB |      0.92% |   18.72 TiB |           0.00% |
| [f039940](https://filfox.info/en/address/f039940)           |                   Chengdu, Sichuan, CN |          17.00 TiB |      0.83% |   17.00 TiB |           0.00% |
| [f047419](https://filfox.info/en/address/f047419)           |           North Prairie, Wisconsin, US |          13.53 TiB |      0.66% |    6.91 TiB |          48.96% |
| [f020378](https://filfox.info/en/address/f020378)           |                                Unknown |           9.25 TiB |      0.45% |    9.25 TiB |           0.00% |
| [f01821041](https://filfox.info/en/address/f01821041)       |        Vancouver, British Columbia, CA |           4.38 TiB |      0.21% |    4.38 TiB |           0.00% |

![Provider Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/304/1671094719984.png)
### Deal Data Replication
The below table shows how each many unique data are replicated across storage providers.
- No more than 25% of unique data are stored with less than 4 providers.

✔️ Data replication looks healthy.

| Unique Data Size | Total Deals Made | Number of Providers | Deal Percentage |
| ---------------: | ---------------: | ------------------: | --------------: |
|       160.00 GiB |       320.00 GiB |                   2 |           0.02% |
|         1.13 TiB |         3.38 TiB |                   3 |           0.17% |
|       512.00 GiB |         2.06 TiB |                   4 |           0.10% |
|         4.78 TiB |        26.63 TiB |                   5 |           1.30% |
|        14.00 TiB |        94.66 TiB |                   6 |           4.64% |
|        13.59 TiB |       100.47 TiB |                   7 |           4.92% |
|        15.78 TiB |       132.09 TiB |                   8 |           6.47% |
|        55.72 TiB |       529.19 TiB |                   9 |          25.92% |
|        28.88 TiB |       295.19 TiB |                  10 |          14.46% |
|        11.91 TiB |       130.97 TiB |                  11 |           6.42% |
|        22.44 TiB |       269.25 TiB |                  12 |          13.19% |
|         7.25 TiB |        94.50 TiB |                  13 |           4.63% |
|         9.13 TiB |       133.63 TiB |                  14 |           6.55% |
|        15.28 TiB |       229.22 TiB |                  15 |          11.23% |

![Replication Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/304/1671094720822.png)
### Deal Data Shared with other Clients
The below table shows how many unique data are shared with other clients.
Usually different applications owns different data and should not resolve to the same CID.

⚠️ CID sharing has been observed.

| Other Client                                                                                                          | Application                                                                                                               | Total Deals Affected | Unique CIDs |  Verifier |
| :-------------------------------------------------------------------------------------------------------------------- | :------------------------------------------------------------------------------------------------------------------------ | -------------------: | ----------: | --------: |
| [f15djc5avdxihguvpmtej24rzbvnnqvzurxe55kja](https://filfox.info/en/address/f15djc5avdxihguvpmtej24rzbvnnqvzurxe55kja) | [Kernelogic \- Fei Yan \- Slingshot Restore](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/136) |           107.81 TiB |       1,350 | LDN # 136 |
| [f1ufbhme24mzlo3mtzx3hkhte3xndpinq7xycezxi](https://filfox.info/en/address/f1ufbhme24mzlo3mtzx3hkhte3xndpinq7xycezxi) | [HarryM \- Slingshot Restore](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/172)                |            97.13 TiB |         782 | LDN # 172 |

[^1]: To manually trigger this report, add a comment with text `checker:manualTrigger`
