### ISSUE TITLE
[DataCap Application]HELIOS

### ISSUE THREAD

**Issue by HELIOSSHANGHAI** [filecoin-project/filecoin-plus-large-datasets#305]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: HELIOS
- Website / Social Media:https://www.huilianyi.com/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100TiB
- On-chain address for first allocation: f1vbe7ze5yknpgu3orinv4zu4rkofsyqfsmpejpui

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
HELIOS is a business travel and expense management software developed by Shanghai Zhenhui Information and Technology Co., Ltd. The company is owned by industry-leading IT consulting firm Hand (stock code: 300170).
Since its debut in 2016, HELIOS is dedicated to providing customers with an advanced management concept to more organizations to run their operations more productively and efficiently. It has processed over 5 million receipts and handled over 10 billion Yuan in reimbursement. With close to one million monthly active users, it is dominating the SaaS market in China. Huilianyi is dedicated to providing more customers with advanced management concept in order to help them run more efficiently.
```

What is the primary source of funding for this project?
```
From company's income.
```

What other projects/ecosystem stakeholders is this project associated with?
```
No.
```

## Use-case details

Describe the data being stored onto Filecoin
```
These are masked data from our system. Approximate 1PiB.

```

Where was the data in this dataset sourced from?
```
Masked enterprise data set from our customers, involving Hotel, transportation, manufacturing and other industries.

  public static String maskSensitiveData(String str, int headCharCount, int tailCharCount) {
        if(str.length()<headCharCount+tailCharCount){
            throw new IllegalArgumentException("明文过短，无法脱敏");
        }
        String repeat = "";

        int len = str.length() - headCharCount - tailCharCount;
        if (len > 0) {
            char[] buf = new char[len];
            AtomicInteger integer = new AtomicInteger(0);
            Arrays.asList(new Integer[len]).stream().forEach(b -> buf[integer.getAndIncrement()] = '*');
            repeat = new String(buf);
        }
        return str.substring(0, headCharCount) + repeat + str.substring(str.length() - tailCharCount);
    }

    public static void main(String[] args) {
        System.out.println(maskSensitiveData("120115201406180712", 6, 4));
        System.out.println(maskSensitiveData("9558820200019833888", 6, 4));
        System.out.println(maskSensitiveData("18810754438", 3, 2));
    }
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
[sqlResult_3175590.csv](https://github.com/filecoin-project/filecoin-plus-large-datasets/files/8804253/sqlResult_3175590.csv)

```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
We confirm that our dataset is public.
```

What is the expected retrieval frequency for this data?    
```
2-3 times a year. 
```

For how long do you plan to keep this dataset stored on Filecoin?
```
540 days or more.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
China Only
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
We've prepared some hard-disks for offline transfer. For storage providers at a distance, we'll distribute data online.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We've contacted some Asia storage providers on slack and telegram, and they need datacap to give us a low price. If PL can find more storage providers for us, we are happy to cooperate with them. We may have more than 10 nodes to make deals.
```

How will you be distributing deals across storage providers?
```
Less than 15% data for every storage providers. 
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes. We are ready to make deals. 
We also have lots of non-public data. If filecoin can accept non-public data, we are happy to continue to make more deals in the future.
```

**Comment by UnionLabs2020** [comment]
Happy to support!

**Comment by galen-mcandrew** [comment]
## Multisig Notary requested
#### Total DataCap requested 
> 5PiB
#### Expected weekly DataCap usage rate 
> 100TiB

**Comment by Fenbushi-Filecoin** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedbuksk6qbbvvxlvb2edgoht6mt5jd5f4okmwoaq4apox22t523q6 
#### Address 
> f1vbe7ze5yknpgu3orinv4zu4rkofsyqfsmpejpui
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1yqydpmqb5en262jpottko2kd65msajax7fi4rmq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedbuksk6qbbvvxlvb2edgoht6mt5jd5f4okmwoaq4apox22t523q6

**Comment by rayshitou** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacediqfjfad253jglpvjvgyqgk6oimgzjwdlbrvld2jhfgpzr24bxps 
#### Address 
> f1vbe7ze5yknpgu3orinv4zu4rkofsyqfsmpejpui
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f136bz32l2hlyad4npmfg5dngcdw3jk3tpcpoz2ja
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacediqfjfad253jglpvjvgyqgk6oimgzjwdlbrvld2jhfgpzr24bxps

**Comment by galen-mcandrew** [comment]
@fabriziogianni7 looks like two notaries kicked off proposal requests here, manually adjusting labels to see if next signature will clear one of the transactions.

**Comment by Reiers** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedmzjikyiyvkkm2lmxwdqdgyhwhvptjqc2jmoh4qo2uf5h573tygq 
#### Address 
> f1vbe7ze5yknpgu3orinv4zu4rkofsyqfsmpejpui
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1oz43ckvmtxmmsfzqm6bpnemqlavz4ifyl524chq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedmzjikyiyvkkm2lmxwdqdgyhwhvptjqc2jmoh4qo2uf5h573tygq

**Comment by galen-mcandrew** [comment]
Checking history, there is still a pending transaction for 50TiB with one signature. Adjusting labels, so that the next signature should match that txID1 and resolve that transaction.

**Comment by swatchliu** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecwcd4sfnjm6gesi5qdf42l6oupzu72bykntq4nwy6sxlberfpyfq 
#### Address 
> f1vbe7ze5yknpgu3orinv4zu4rkofsyqfsmpejpui
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1yh6q3nmsg7i2sys7f7dexcuajgoweudcqj2chfi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecwcd4sfnjm6gesi5qdf42l6oupzu72bykntq4nwy6sxlberfpyfq

**Comment by rayshitou** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaoakbthaha7xiu77rlfjlrpcw7hdyui3u6jf7jlmnvxu2ejh43u4 
#### Address 
> f1vbe7ze5yknpgu3orinv4zu4rkofsyqfsmpejpui
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f136bz32l2hlyad4npmfg5dngcdw3jk3tpcpoz2ja
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaoakbthaha7xiu77rlfjlrpcw7hdyui3u6jf7jlmnvxu2ejh43u4

**Comment by Fenbushi-Filecoin** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedgsxldova2hhabdruzllytvaucoav5otlqh3yszosqljwm7ctbuk 
#### Address 
> f1vbe7ze5yknpgu3orinv4zu4rkofsyqfsmpejpui
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1yqydpmqb5en262jpottko2kd65msajax7fi4rmq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedgsxldova2hhabdruzllytvaucoav5otlqh3yszosqljwm7ctbuk

**Comment by swatchliu** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebgwxsp43vgto2gqfulqb6q7zqnecucbfuql4zeissqwaxinu674k 
#### Address 
> f1vbe7ze5yknpgu3orinv4zu4rkofsyqfsmpejpui
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1yh6q3nmsg7i2sys7f7dexcuajgoweudcqj2chfi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebgwxsp43vgto2gqfulqb6q7zqnecucbfuql4zeissqwaxinu674k

**Comment by swatchliu** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceascczare4ixktzupfn4ohjofmkrhluruxz3s2ukzs2sf4bl4y2cu 
#### Address 
> f1vbe7ze5yknpgu3orinv4zu4rkofsyqfsmpejpui
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1yh6q3nmsg7i2sys7f7dexcuajgoweudcqj2chfi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceascczare4ixktzupfn4ohjofmkrhluruxz3s2ukzs2sf4bl4y2cu

**Comment by DarnellWashington** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebvcjrvwumadgm7axb4n5i5rk6xjcygjty4u3eo3d66qkowt4wcek 
#### Address 
> f1vbe7ze5yknpgu3orinv4zu4rkofsyqfsmpejpui
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1bjdcjxha3ldcstw5zmvkyu3r2p5x2bsm745kgsi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebvcjrvwumadgm7axb4n5i5rk6xjcygjty4u3eo3d66qkowt4wcek

**Comment by rayshitou** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacea4ud7bdkz4q6334lmfhx4oq73fyjlpfzlnwx7bzpw352luhtnjso 
#### Address 
> f1vbe7ze5yknpgu3orinv4zu4rkofsyqfsmpejpui
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f136bz32l2hlyad4npmfg5dngcdw3jk3tpcpoz2ja
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacea4ud7bdkz4q6334lmfhx4oq73fyjlpfzlnwx7bzpw352luhtnjso

**Comment by MetaWaveInfo** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceba75u7eniw7lvoswkop76shqq5jdf26naehdmi4wmqxxiykmwtn4 
#### Address 
> f1vbe7ze5yknpgu3orinv4zu4rkofsyqfsmpejpui
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1ktlkcxnmzxcdaoqfsunrg3vocfbmgv4n3mrn74a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceba75u7eniw7lvoswkop76shqq5jdf26naehdmi4wmqxxiykmwtn4

**Comment by BigD-Exchange** [comment]
@HELIOSSHANGHAI Hi! Great to see you have gotten approval for DataCap and advancing the mission of preserving humanity’s most important information. If you are looking for storage providers to store these data or have any questions, please visit #bigdata-exchange on Filecoin Slack or reply here. 

We have strong demand from a diverse group of SPs, who are actively looking to onboard more data.

**Comment by swatchliu** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedxh6qvarcgsayzpn3oosoatbzjcavmevwpnwxnbor2htji2rpdbk 
#### Address 
> f1vbe7ze5yknpgu3orinv4zu4rkofsyqfsmpejpui
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1yh6q3nmsg7i2sys7f7dexcuajgoweudcqj2chfi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedxh6qvarcgsayzpn3oosoatbzjcavmevwpnwxnbor2htji2rpdbk

**Comment by liyunzhi-666** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacednnipoqtxdugt5qkbjgoiwewwk3dr2crqrledt6mnc23iitpwgei 
#### Address 
> f1vbe7ze5yknpgu3orinv4zu4rkofsyqfsmpejpui
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1pszcrsciyixyuxxukkvtazcokexbn54amf7gvoq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacednnipoqtxdugt5qkbjgoiwewwk3dr2crqrledt6mnc23iitpwgei

**Comment by UnionLabs2020** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedj5rdyv7ijrimm7zwsre6p35h2es27e7cykzs4go2evuf4u46zge 
#### Address 
> f1vbe7ze5yknpgu3orinv4zu4rkofsyqfsmpejpui
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f17xdri3wunqgld7dm23e4f3eqsntjakwc47xjo6i
#### Id
> 441b9aaf-b27a-45d0-a5b9-10d6929aadfa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedj5rdyv7ijrimm7zwsre6p35h2es27e7cykzs4go2evuf4u46zge

**Comment by 1475Notary** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec3h4i7vsg3yn2p26me4j55adr6pnnaxzuvgb4lpi46npnparqt66 
#### Address 
> f1vbe7ze5yknpgu3orinv4zu4rkofsyqfsmpejpui
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1ofq4mngy7ggcp755pfquq2gphjjnlydolf6awtq
#### Id
> 441b9aaf-b27a-45d0-a5b9-10d6929aadfa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec3h4i7vsg3yn2p26me4j55adr6pnnaxzuvgb4lpi46npnparqt66

**Comment by filplus-checker** [comment]
## DataCap and CID Checker Report[^1]
 - Organization: `HELIOS`
 - Client: `f1vbe7ze5yknpgu3orinv4zu4rkofsyqfsmpejpui`
### Storage Provider Distribution
The below table shows the distribution of storage providers that have stored data for this client.

If this is the first time a provider takes verified deal, it will be marked as `new`.

For most of the datacap application, below restrictions should apply.
 - Storage provider should not exceed 25% of total datacap.
 - Storage provider should not be storing duplicate data for more than 20%.
 - Storage provider should have published its public IP address.
 - All storage providers should be located in different regions.

⚠️ 88.11% of total deal sealed by [f01445167](https://filfox.info/en/address/f01445167) are duplicate data.

⚠️ 89.24% of total deal sealed by [f01520](https://filfox.info/en/address/f01520) are duplicate data.

⚠️ [f01520](https://filfox.info/en/address/f01520) has unknown IP location.

⚠️ 89.98% of total deal sealed by [f01933849](https://filfox.info/en/address/f01933849) are duplicate data.

⚠️ [f01933849](https://filfox.info/en/address/f01933849) has unknown IP location.

⚠️ 65.39% of total deal sealed by [f01843749](https://filfox.info/en/address/f01843749) are duplicate data.

⚠️ 54.67% of total deal sealed by [f01841133](https://filfox.info/en/address/f01841133) are duplicate data.

⚠️ 89.54% of total deal sealed by [f0136399](https://filfox.info/en/address/f0136399) are duplicate data.

⚠️ 66.53% of total deal sealed by [f0681068](https://filfox.info/en/address/f0681068) are duplicate data.

⚠️ 87.85% of total deal sealed by [f01878693](https://filfox.info/en/address/f01878693) are duplicate data.

⚠️ [f01878693](https://filfox.info/en/address/f01878693) has unknown IP location.

⚠️ 21.26% of total deal sealed by [f01841131](https://filfox.info/en/address/f01841131) are duplicate data.

⚠️ 89.13% of total deal sealed by [f01946714](https://filfox.info/en/address/f01946714) are duplicate data.

⚠️ [f01946714](https://filfox.info/en/address/f01946714) has unknown IP location.

⚠️ 77.08% of total deal sealed by [f01926749](https://filfox.info/en/address/f01926749) are duplicate data.

⚠️ [f01926749](https://filfox.info/en/address/f01926749) has unknown IP location.

⚠️ 75.59% of total deal sealed by [f01926777](https://filfox.info/en/address/f01926777) are duplicate data.

⚠️ [f01926777](https://filfox.info/en/address/f01926777) has unknown IP location.

⚠️ 69.62% of total deal sealed by [f01392600](https://filfox.info/en/address/f01392600) are duplicate data.

⚠️ [f01773193](https://filfox.info/en/address/f01773193) has unknown IP location.

⚠️ 26.53% of total deal sealed by [f01806248](https://filfox.info/en/address/f01806248) are duplicate data.

⚠️ [f01854758](https://filfox.info/en/address/f01854758) has unknown IP location.

⚠️ [f01854755](https://filfox.info/en/address/f01854755) has unknown IP location.

⚠️ [f01854757](https://filfox.info/en/address/f01854757) has unknown IP location.

⚠️ 88.76% of total deal sealed by [f01817517](https://filfox.info/en/address/f01817517) are duplicate data.

⚠️ [f01817517](https://filfox.info/en/address/f01817517) has unknown IP location.

| Provider                                                    |                           Location | Total Deals Sealed | Percentage | Unique Data | Duplicate Deals |
| :---------------------------------------------------------- | ---------------------------------: | -----------------: | ---------: | ----------: | --------------: |
| [f01445167](https://filfox.info/en/address/f01445167)`new`  | Hong Kong, Central and Western, HK |         777.06 TiB |     24.01% |   92.38 TiB |          88.11% |
| [f01520](https://filfox.info/en/address/f01520)             |                            Unknown |         585.00 TiB |     18.08% |   62.94 TiB |          89.24% |
| [f01933849](https://filfox.info/en/address/f01933849)       |                            Unknown |         299.97 TiB |      9.27% |   30.06 TiB |          89.98% |
| [f01843749](https://filfox.info/en/address/f01843749)`new`  | Hong Kong, Central and Western, HK |         260.50 TiB |      8.05% |   90.16 TiB |          65.39% |
| [f01841133](https://filfox.info/en/address/f01841133)`new`  |           Singapore, Singapore, SG |         256.88 TiB |      7.94% |  116.44 TiB |          54.67% |
| [f0136399](https://filfox.info/en/address/f0136399)         | Hong Kong, Central and Western, HK |         154.81 TiB |      4.78% |   16.19 TiB |          89.54% |
| [f0681068](https://filfox.info/en/address/f0681068)`new`    | Hong Kong, Central and Western, HK |         150.31 TiB |      4.64% |   50.31 TiB |          66.53% |
| [f01878693](https://filfox.info/en/address/f01878693)       |                            Unknown |         119.31 TiB |      3.69% |   14.50 TiB |          87.85% |
| [f01841131](https://filfox.info/en/address/f01841131)`new`  | Hong Kong, Central and Western, HK |          92.03 TiB |      2.84% |   72.47 TiB |          21.26% |
| [f01946714](https://filfox.info/en/address/f01946714)       |                            Unknown |          91.13 TiB |      2.82% |    9.91 TiB |          89.13% |
| [f01926749](https://filfox.info/en/address/f01926749)       |                            Unknown |          90.00 TiB |      2.78% |   20.63 TiB |          77.08% |
| [f01926777](https://filfox.info/en/address/f01926777)       |                            Unknown |          90.00 TiB |      2.78% |   21.97 TiB |          75.59% |
| [f01841134](https://filfox.info/en/address/f01841134)`new`  |           Singapore, Singapore, SG |          71.66 TiB |      2.21% |   59.16 TiB |          17.44% |
| [f01392600](https://filfox.info/en/address/f01392600)       | Hong Kong, Central and Western, HK |          70.88 TiB |      2.19% |   21.53 TiB |          69.62% |
| [f01773206](https://filfox.info/en/address/f01773206)       |                   Seoul, Seoul, KR |          22.75 TiB |      0.70% |   22.75 TiB |           0.00% |
| [f01773193](https://filfox.info/en/address/f01773193)       |                            Unknown |          22.00 TiB |      0.68% |   22.00 TiB |           0.00% |
| [f01806248](https://filfox.info/en/address/f01806248)       |           Singapore, Singapore, SG |          19.91 TiB |      0.62% |   14.63 TiB |          26.53% |
| [f01854758](https://filfox.info/en/address/f01854758)       |                            Unknown |          19.88 TiB |      0.61% |   19.88 TiB |           0.00% |
| [f01854755](https://filfox.info/en/address/f01854755)       |                            Unknown |          19.88 TiB |      0.61% |   19.88 TiB |           0.00% |
| [f01854757](https://filfox.info/en/address/f01854757)       |                            Unknown |          19.69 TiB |      0.61% |   19.69 TiB |           0.00% |
| [f01817517](https://filfox.info/en/address/f01817517)`new`  |                            Unknown |           2.78 TiB |      0.09% |  320.00 GiB |          88.76% |

![Provider Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/305/1671094741984.png)
### Deal Data Replication
The below table shows how each many unique data are replicated across storage providers.
- No more than 25% of unique data are stored with less than 4 providers.

⚠️ 99.73% of deals are for data replicated across less than 4 storage providers.

| Unique Data Size | Total Deals Made | Number of Providers | Deal Percentage |
| ---------------: | ---------------: | ------------------: | --------------: |
|       548.84 TiB |         2.19 PiB |                   1 |          69.41% |
|        93.44 TiB |       829.31 TiB |                   2 |          25.62% |
|        18.34 TiB |       151.94 TiB |                   3 |           4.69% |
|         1.75 TiB |         8.75 TiB |                   4 |           0.27% |

![Replication Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/305/1671094742642.png)
### Deal Data Shared with other Clients
The below table shows how many unique data are shared with other clients.
Usually different applications owns different data and should not resolve to the same CID.

⚠️ CID sharing has been observed.

| Other Client                                                                                                                                                                                                              | Application                                                                                                                    | Total Deals Affected | Unique CIDs |        Verifier |
| :------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ | :----------------------------------------------------------------------------------------------------------------------------- | -------------------: | ----------: | --------------: |
| [f1rkmhotssjif6ucrosls7oewjz6pr2v2eygfjyui](https://filfox.info/en/address/f1rkmhotssjif6ucrosls7oewjz6pr2v2eygfjyui)                                                                                                     | `Weipaitang`                                                                                                                   |           117.00 TiB |         972 | LDN v3 multisig |
| [f1ugo3abkmmb4pb2atxz5oqqgwsd27b4p6k52f2va](https://filfox.info/en/address/f1ugo3abkmmb4pb2atxz5oqqgwsd27b4p6k52f2va)                                                                                                     | [Yuepass Technology Company Limited](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/429)              |            80.59 TiB |         698 | LDN v3 multisig |
| [f1vykg3elgzoa3lpzf5xo6rbcghzr5ifat757mucq](https://filfox.info/en/address/f1vykg3elgzoa3lpzf5xo6rbcghzr5ifat757mucq)                                                                                                     | [Hailiang Mingyou Online](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/51)                          |            66.56 TiB |       1,737 |        LDN # 51 |
| [f1fq6abg47ifgeee2z7q2rps3tvknoo2ztcoqy7ai](https://filfox.info/en/address/f1fq6abg47ifgeee2z7q2rps3tvknoo2ztcoqy7ai)                                                                                                     | [DaYe Art Tuition Class \(DKArt\) ](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/888)               |            43.16 TiB |         241 | LDN v3 multisig |
| [f1cf2pp6bgu6vvxfuau6bsmiibhrc7v3gvjsyseay](https://filfox.info/en/address/f1cf2pp6bgu6vvxfuau6bsmiibhrc7v3gvjsyseay)                                                                                                     | [Public Data\-FlyBrain](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1013)                          |            28.69 TiB |         151 | LDN v3 multisig |
| [f3rncwz3qo2bwnsrfjc7kq53xr7yi2lctcydtllxo<br/>zmszndvttou7n565yb6aqssvn4omyf5m7q62qpfmq<br/>cbwq](https://filfox.info/en/address/f3rncwz3qo2bwnsrfjc7kq53xr7yi2lctcydtllxozmszndvttou7n565yb6aqssvn4omyf5m7q62qpfmqcbwq) | [VillageOne Space LLCVillageOne Space LLC](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/39)         |            18.91 TiB |         413 |        LDN # 39 |
| [f1wr6rwwqckh6um2hynaym2t4mniev5b675kbf5ni](https://filfox.info/en/address/f1wr6rwwqckh6um2hynaym2t4mniev5b675kbf5ni)                                                                                                     | [Ctrip Global Shopping](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/303)                           |            16.00 TiB |         290 | LDN v3 multisig |
| [f1a2rdwwor3kq6mv7nveuxhux7rxtj6iyjs7hfswa](https://filfox.info/en/address/f1a2rdwwor3kq6mv7nveuxhux7rxtj6iyjs7hfswa)                                                                                                     | [Worldkan](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/902)                                        |            14.81 TiB |         193 | LDN v3 multisig |
| [f1csetl7nor3qie2cehx7axf2ai3nedmowj53xwsa](https://filfox.info/en/address/f1csetl7nor3qie2cehx7axf2ai3nedmowj53xwsa)                                                                                                     | [NOAA GOES\-\-\-Piero](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1112)                           |            11.19 TiB |         147 | LDN v3 multisig |
| [f127l5waa4pw6k3sm4e7wxevc4fe5uz7dyt4mxa3i](https://filfox.info/en/address/f127l5waa4pw6k3sm4e7wxevc4fe5uz7dyt4mxa3i)                                                                                                     | `Pangod`                                                                                                                       |             6.75 TiB |          29 | LDN v3 multisig |
| [f3xffjctbyy7zigopfa3za5ha3pvv4z3xfghlw7kw<br/>vyeuabkg4lzsgfwhnghwkvmmvi6yso6k52hq3ca6c<br/>kveq](https://filfox.info/en/address/f3xffjctbyy7zigopfa3za5ha3pvv4z3xfghlw7kwvyeuabkg4lzsgfwhnghwkvmmvi6yso6k52hq3ca6ckveq) | [Chengdu Digital Media Industry Base Co\., Ltd\.](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/387) |             3.06 TiB |          60 | LDN v3 multisig |
| [f162jayw3utjlbp5ae6ssqghm5jrl3js32dbmnfja](https://filfox.info/en/address/f162jayw3utjlbp5ae6ssqghm5jrl3js32dbmnfja)                                                                                                     | ``                                                                                                                             |             2.16 TiB |          15 |       LDN # 121 |
| [f1znd7uramgqquelcgefo5xgozopd3nga73hhywpy](https://filfox.info/en/address/f1znd7uramgqquelcgefo5xgozopd3nga73hhywpy)                                                                                                     | [BotSmart ](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/373)                                       |             2.03 TiB |          11 | LDN v3 multisig |
| [f1tmuircaaenwvffdmyuydcqlidfxvgvg2wsj344i](https://filfox.info/en/address/f1tmuircaaenwvffdmyuydcqlidfxvgvg2wsj344i)                                                                                                     | [Myserver](https://github.com/filecoin-project/filecoin-plus-client-onboarding/issues/447)                                     |             1.78 TiB |          57 |    Tim Williams |
| [f3q7ablez3jqkcjukwbzaql7lmbx4ldouu66nexpd<br/>cfvu6kgho3v6gricckt77cgr46tdre2l4zmvha7bs<br/>u7qq](https://filfox.info/en/address/f3q7ablez3jqkcjukwbzaql7lmbx4ldouu66nexpdcfvu6kgho3v6gricckt77cgr46tdre2l4zmvha7bsu7qq) | `MatrixStorage`                                                                                                                |             1.78 TiB |          57 |        LDN # 72 |
| [f1xwmnlen7j7qlkktm3oqggzcbrxp6cvqnkd2wipa](https://filfox.info/en/address/f1xwmnlen7j7qlkktm3oqggzcbrxp6cvqnkd2wipa)                                                                                                     | ``                                                                                                                             |             1.69 TiB |           6 |       LDN # 121 |
| [f1kvffnugu5j2fjjuispqr2y7bzmmtrvj6hk32xoq](https://filfox.info/en/address/f1kvffnugu5j2fjjuispqr2y7bzmmtrvj6hk32xoq)                                                                                                     | [Unicom\-for new round application](https://github.com/filecoin-project/filecoin-plus-client-onboarding/issues/1808)           |             1.59 TiB |          32 |     Zhehao Chen |
| [f1avfkllpeqlx32bwjcka6y27scftpl5nzh754yly](https://filfox.info/en/address/f1avfkllpeqlx32bwjcka6y27scftpl5nzh754yly)                                                                                                     | ``                                                                                                                             |             1.44 TiB |          26 |     Zhehao Chen |
| [f1qnhjr2kq742poi6rukv5hji5rdrtuqsib7khz3a](https://filfox.info/en/address/f1qnhjr2kq742poi6rukv5hji5rdrtuqsib7khz3a)                                                                                                     | [GLOBAL UNIT\-A Corp\.](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/110)                           |             1.31 TiB |          27 |       LDN # 110 |
| [f1bb2z36lpq3pnwiiowiraagpzqnpow4bonjacx7a](https://filfox.info/en/address/f1bb2z36lpq3pnwiiowiraagpzqnpow4bonjacx7a)                                                                                                     | [Hola Space](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/362)                                      |             1.25 TiB |           4 | LDN v3 multisig |
| [f1yswits4hd4zu6n2pl7nk7cspcuieuzl7btjn5ia](https://filfox.info/en/address/f1yswits4hd4zu6n2pl7nk7cspcuieuzl7btjn5ia)                                                                                                     | [TaoPaiPai](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/54)                                        |             1.00 TiB |          29 |        LDN # 54 |
| [f1quofpadzcqlonmz7v3mv7dfqvm5hdztucdsjqsy](https://filfox.info/en/address/f1quofpadzcqlonmz7v3mv7dfqvm5hdztucdsjqsy)                                                                                                     | [HENAN 863 SOFTWARE CO\., LTD](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/468)                    |           640.00 GiB |           2 | LDN v3 multisig |
| [f1vmbre2qgafcfizvbmcfdj5k24ouwscp5cavspxi](https://filfox.info/en/address/f1vmbre2qgafcfizvbmcfdj5k24ouwscp5cavspxi)                                                                                                     | ``                                                                                                                             |           416.00 GiB |           3 | LDN v3 multisig |
| [f1k2pbx376s46c72ouwrg2avyvrglj66u76opbsqa](https://filfox.info/en/address/f1k2pbx376s46c72ouwrg2avyvrglj66u76opbsqa)                                                                                                     | [aifabot inc](https://github.com/filecoin-project/filecoin-plus-client-onboarding/issues/566)                                  |           192.00 GiB |           6 |    Dr. Ann Shin |

[^1]: To manually trigger this report, add a comment with text `checker:manualTrigger`
