### ISSUE TITLE
[DataCap Application]CTG Business Service

### ISSUE THREAD

**Issue by ctgatfilecoin** [filecoin-project/filecoin-plus-large-datasets#306]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: CTG Business Service
- Website / Social Media:https://www.ctg.cn/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100TiB
- On-chain address for first allocation: f1smfrznoqsp7eptqnselnosng7vxuo3ptnoqv2oa

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
It was established in 2000 and belongs to China Travel Server. With a global travel agency and supplier service network, real-time tracking of business travel is realized. One-click ticket changes and refunds are available anywhere in the world. Quick customs clearance at the airport brings more convenient travel experiences. The service guarantee personnel are safe and reliable, realizing 7*24 hours of uninterrupted service. It is a platform of air tickets, hotels and travel services for lients.
```

What is the primary source of funding for this project?
```
Company's revenues.
```

What other projects/ecosystem stakeholders is this project associated with?
```
No.
```

## Use-case details

Describe the data being stored onto Filecoin
```
Real-time price data archiving of air tickets and hotels; analysis and archiving of user travel data and log of the trading system.
```

Where was the data in this dataset sourced from?
```
From the platform of our service. Our business mainly provides air tickets, hotels and travel service to users.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
[CTG Travel Report dataset.xlsx](https://github.com/filecoin-project/filecoin-plus-large-datasets/files/8313914/CTG.Travel.Report.dataset.xlsx)
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes.
```

What is the expected retrieval frequency for this data?    
```
Once a year. 
```

For how long do you plan to keep this dataset stored on Filecoin?
```
At least 1 year.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Asia.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
We want to use both online and offline transfer. Small-capacity data will transfer onilne.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We hope to find some storage providers in Asia through slack. The purpose of applying for datacap is to hope that more storage providers can finish our deals.
```

How will you be distributing deals across storage providers?
```
We may prepare about 15 nodes for storage because of several copies. Less than 10% for every storage provider.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes. If we have a good experience in filecoin, we hope to introduce more companies in our group or some companies in the same industry to participate together. Is there some rewards for inviting new members to take part in filecoin?
```

**Comment by galen-mcandrew** [comment]
## Multisig Notary requested
#### Total DataCap requested 
> 5PiB
#### Expected weekly DataCap usage rate 
> 100TiB

**Comment by swatchliu** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecfkiegamfu3p72kgbaanmivqymvfnidkz2636qveip74pg6r4apg 
#### Address 
> f1smfrznoqsp7eptqnselnosng7vxuo3ptnoqv2oa
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1yh6q3nmsg7i2sys7f7dexcuajgoweudcqj2chfi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecfkiegamfu3p72kgbaanmivqymvfnidkz2636qveip74pg6r4apg

**Comment by Fenbushi-Filecoin** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebsrlzypbwxs7c3hzeyie2btbeneru467zlady6apq6agn4iy5hbi 
#### Address 
> f1smfrznoqsp7eptqnselnosng7vxuo3ptnoqv2oa
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1yqydpmqb5en262jpottko2kd65msajax7fi4rmq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebsrlzypbwxs7c3hzeyie2btbeneru467zlady6apq6agn4iy5hbi

**Comment by dkkapur** [comment]
This went through! SSA needs to pick this up for the next allocation

**Comment by rayshitou** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebhsu3r7ourqxpzvngv5o6gjodj7kqm7vlbvl24gpkv3hekpwwiu6 
#### Address 
> f1smfrznoqsp7eptqnselnosng7vxuo3ptnoqv2oa
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f136bz32l2hlyad4npmfg5dngcdw3jk3tpcpoz2ja
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebhsu3r7ourqxpzvngv5o6gjodj7kqm7vlbvl24gpkv3hekpwwiu6

**Comment by MRJAVAZHAO** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebc62kmm2lge5wsed56zyg2puy5dulkehmhscnyab2lhsi6woerru 
#### Address 
> f1smfrznoqsp7eptqnselnosng7vxuo3ptnoqv2oa
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f14gme3f52prtyzk6pblogrdd6b6ivp4swc6qmesi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebc62kmm2lge5wsed56zyg2puy5dulkehmhscnyab2lhsi6woerru

**Comment by galen-mcandrew** [comment]
@fabriziogianni7 not seeing the SA bot checking this issue after 4/29. Looks like maybe the bot thinks it posted? Did the bot lose permissions to post in GitHub?

**Comment by swatchliu** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedfb7pk3fs67hkofod4dwtir55cwm4rjhbwzpuy6gn3mg37kqlgtq 
#### Address 
> f1smfrznoqsp7eptqnselnosng7vxuo3ptnoqv2oa
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1yh6q3nmsg7i2sys7f7dexcuajgoweudcqj2chfi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedfb7pk3fs67hkofod4dwtir55cwm4rjhbwzpuy6gn3mg37kqlgtq

**Comment by TimWilliams00** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacealg4wherecph4tha4ngjnxz3dytlff6f2ckt26fvzteqvxn2twxu 
#### Address 
> f1smfrznoqsp7eptqnselnosng7vxuo3ptnoqv2oa
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1fkxkfxgopjf3ufnfg5i3m6qlwf73kp4w5zz7nnq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacealg4wherecph4tha4ngjnxz3dytlff6f2ckt26fvzteqvxn2twxu

**Comment by MRJAVAZHAO** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacea3lhsgarx6okrcbsab7zpx7jbatzywwffzqyjvnxf2wyqyy2p2nw 
#### Address 
> f1smfrznoqsp7eptqnselnosng7vxuo3ptnoqv2oa
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f14gme3f52prtyzk6pblogrdd6b6ivp4swc6qmesi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacea3lhsgarx6okrcbsab7zpx7jbatzywwffzqyjvnxf2wyqyy2p2nw

**Comment by swatchliu** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacea3kmanxevdb64f3o4y3peo5nzav5uyapqsr3j5c7jyc423wwmrg4 
#### Address 
> f1smfrznoqsp7eptqnselnosng7vxuo3ptnoqv2oa
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1yh6q3nmsg7i2sys7f7dexcuajgoweudcqj2chfi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacea3kmanxevdb64f3o4y3peo5nzav5uyapqsr3j5c7jyc423wwmrg4

**Comment by TimWilliams00** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceajerivniuw7mfilpcn2p723tmfnzhcjwfxdksuxt6rmrwgkkp4ag 
#### Address 
> f1smfrznoqsp7eptqnselnosng7vxuo3ptnoqv2oa
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1fkxkfxgopjf3ufnfg5i3m6qlwf73kp4w5zz7nnq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceajerivniuw7mfilpcn2p723tmfnzhcjwfxdksuxt6rmrwgkkp4ag

**Comment by Fenbushi-Filecoin** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec5q7vl7rte2ido5gmqk3fjl67tpxcn32q7hioutjimktzv2nmufu 
#### Address 
> f1smfrznoqsp7eptqnselnosng7vxuo3ptnoqv2oa
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1yqydpmqb5en262jpottko2kd65msajax7fi4rmq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec5q7vl7rte2ido5gmqk3fjl67tpxcn32q7hioutjimktzv2nmufu

**Comment by swatchliu** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceatpgwimugeqabsu3lfpg5nkj4w5mqztzxtbwtwprbione36dx7ng 
#### Address 
> f1smfrznoqsp7eptqnselnosng7vxuo3ptnoqv2oa
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1yh6q3nmsg7i2sys7f7dexcuajgoweudcqj2chfi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceatpgwimugeqabsu3lfpg5nkj4w5mqztzxtbwtwprbione36dx7ng

**Comment by TimWilliams00** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec26ap5etwpmprttchrttfht3vbpplqxrk7evkhmjxg5ebu2mohfo 
#### Address 
> f1smfrznoqsp7eptqnselnosng7vxuo3ptnoqv2oa
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1fkxkfxgopjf3ufnfg5i3m6qlwf73kp4w5zz7nnq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec26ap5etwpmprttchrttfht3vbpplqxrk7evkhmjxg5ebu2mohfo

**Comment by PluskitOfficial** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedoytwhgo3yma626ktn2hhwt6nfdglc5m6v6zhx4n55273gq5ev4s 
#### Address 
> f1smfrznoqsp7eptqnselnosng7vxuo3ptnoqv2oa
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1tgnlhtcmhwipfm7thsftxhn5k52velyjlazpvka
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedoytwhgo3yma626ktn2hhwt6nfdglc5m6v6zhx4n55273gq5ev4s

**Comment by 1475Notary** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebjldjgrmwryil22hg2pva4x3hyurjfu2vdqxoophnp36et5pmvni 
#### Address 
> f1smfrznoqsp7eptqnselnosng7vxuo3ptnoqv2oa
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1ofq4mngy7ggcp755pfquq2gphjjnlydolf6awtq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebjldjgrmwryil22hg2pva4x3hyurjfu2vdqxoophnp36et5pmvni

**Comment by BlockMakeronline** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecscm3ny6su3oe7euzam6ug5lxnf7w25y6zm3uehhbrpaxeppzhga 
#### Address 
> f1smfrznoqsp7eptqnselnosng7vxuo3ptnoqv2oa
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1o3twrcpwjtpcd4q36lpq4qmy2qfbgtyy5h6tsty
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecscm3ny6su3oe7euzam6ug5lxnf7w25y6zm3uehhbrpaxeppzhga

**Comment by MRJAVAZHAO** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecc3qqc5gpduvvt7xvsreptfvyvgytgd4yogo52zrh6yctxunj636 
#### Address 
> f1smfrznoqsp7eptqnselnosng7vxuo3ptnoqv2oa
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f14gme3f52prtyzk6pblogrdd6b6ivp4swc6qmesi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecc3qqc5gpduvvt7xvsreptfvyvgytgd4yogo52zrh6yctxunj636

**Comment by BigD-Exchange** [comment]
@ctgatfilecoin Hi! Great to see you have gotten approval for DataCap. If you are looking for storage providers to store these data or have any questions, please visit #bigdata-exchange on Filecoin Slack or reply here. 

We have strong demand from a diverse group of SPs, who are actively looking to onboard more data.

**Comment by 1475Notary** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebhxfw5ukeccet6k6yky3qr7k2g6lst54nzg752tmtz5aqas6ep3u 
#### Address 
> f1smfrznoqsp7eptqnselnosng7vxuo3ptnoqv2oa
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1ofq4mngy7ggcp755pfquq2gphjjnlydolf6awtq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebhxfw5ukeccet6k6yky3qr7k2g6lst54nzg752tmtz5aqas6ep3u

**Comment by UnionLabs2020** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedwbqr2h6std6djwd5nvzxmjsb7t4yefur2qwo2zqk2lysddzde5m 
#### Address 
> f1smfrznoqsp7eptqnselnosng7vxuo3ptnoqv2oa
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f17xdri3wunqgld7dm23e4f3eqsntjakwc47xjo6i
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedwbqr2h6std6djwd5nvzxmjsb7t4yefur2qwo2zqk2lysddzde5m

**Comment by filplus-checker** [comment]
## DataCap and CID Checker Report[^1]
 - Organization: `CTG Business Service`
 - Client: `f1smfrznoqsp7eptqnselnosng7vxuo3ptnoqv2oa`
### Storage Provider Distribution
The below table shows the distribution of storage providers that have stored data for this client.

If this is the first time a provider takes verified deal, it will be marked as `new`.

For most of the datacap application, below restrictions should apply.
 - Storage provider should not exceed 25% of total datacap.
 - Storage provider should not be storing duplicate data for more than 20%.
 - Storage provider should have published its public IP address.
 - All storage providers should be located in different regions.

⚠️ 83.71% of total deal sealed by [f01845667](https://filfox.info/en/address/f01845667) are duplicate data.

⚠️ 70.63% of total deal sealed by [f01924416](https://filfox.info/en/address/f01924416) are duplicate data.

⚠️ 58.71% of total deal sealed by [f01917241](https://filfox.info/en/address/f01917241) are duplicate data.

⚠️ 57.96% of total deal sealed by [f01917236](https://filfox.info/en/address/f01917236) are duplicate data.

⚠️ 53.30% of total deal sealed by [f01917214](https://filfox.info/en/address/f01917214) are duplicate data.

⚠️ [f01844999](https://filfox.info/en/address/f01844999) has unknown IP location.

⚠️ 87.31% of total deal sealed by [f01868890](https://filfox.info/en/address/f01868890) are duplicate data.

| Provider                                              |                 Location | Total Deals Sealed | Percentage | Unique Data | Duplicate Deals |
| :---------------------------------------------------- | -----------------------: | -----------------: | ---------: | ----------: | --------------: |
| [f01832632](https://filfox.info/en/address/f01832632) | San Jose, California, US |         437.63 TiB |     11.21% |  437.63 TiB |           0.00% |
| [f01845667](https://filfox.info/en/address/f01845667) |       Hilliard, Ohio, US |         382.88 TiB |      9.81% |   62.38 TiB |          83.71% |
| [f01924416](https://filfox.info/en/address/f01924416) | Singapore, Singapore, SG |         201.00 TiB |      5.15% |   59.03 TiB |          70.63% |
| [f01917241](https://filfox.info/en/address/f01917241) |         Seoul, Seoul, KR |         197.09 TiB |      5.05% |   81.38 TiB |          58.71% |
| [f01788206](https://filfox.info/en/address/f01788206) |     Boardman, Oregon, US |         192.50 TiB |      4.93% |  192.50 TiB |           0.00% |
| [f01917236](https://filfox.info/en/address/f01917236) |         Seoul, Seoul, KR |         185.84 TiB |      4.76% |   78.13 TiB |          57.96% |
| [f01759262](https://filfox.info/en/address/f01759262) | San Jose, California, US |         184.47 TiB |      4.72% |  184.47 TiB |           0.00% |
| [f01832653](https://filfox.info/en/address/f01832653) |         Seoul, Seoul, KR |         183.72 TiB |      4.71% |  183.72 TiB |           0.00% |
| [f01917214](https://filfox.info/en/address/f01917214) |         Seoul, Seoul, KR |         172.38 TiB |      4.42% |   80.50 TiB |          53.30% |
| [f01844999](https://filfox.info/en/address/f01844999) |                  Unknown |         153.13 TiB |      3.92% |  153.13 TiB |           0.00% |
| [f01788210](https://filfox.info/en/address/f01788210) |     Boardman, Oregon, US |         140.44 TiB |      3.60% |  140.44 TiB |           0.00% |
| [f01868890](https://filfox.info/en/address/f01868890) |     Boardman, Oregon, US |         129.31 TiB |      3.31% |   16.41 TiB |          87.31% |
| [f01654290](https://filfox.info/en/address/f01654290) |       Hilliard, Ohio, US |         115.91 TiB |      2.97% |  115.91 TiB |           0.00% |
| [f01674728](https://filfox.info/en/address/f01674728) |       Hilliard, Ohio, US |         112.47 TiB |      2.88% |  112.47 TiB |           0.00% |
| [f01674967](https://filfox.info/en/address/f01674967) |       Hilliard, Ohio, US |         110.03 TiB |      2.82% |  110.03 TiB |           0.00% |
| [f01807908](https://filfox.info/en/address/f01807908) | San Jose, California, US |         106.63 TiB |      2.73% |  106.63 TiB |           0.00% |
| [f01675012](https://filfox.info/en/address/f01675012) |       Hilliard, Ohio, US |         104.00 TiB |      2.66% |  104.00 TiB |           0.00% |
| [f01769554](https://filfox.info/en/address/f01769554) | San Jose, California, US |         102.94 TiB |      2.64% |  102.94 TiB |           0.00% |
| [f01843673](https://filfox.info/en/address/f01843673) |       Hilliard, Ohio, US |          86.13 TiB |      2.21% |   86.13 TiB |           0.00% |
| [f01653777](https://filfox.info/en/address/f01653777) |       Hilliard, Ohio, US |          84.31 TiB |      2.16% |   84.31 TiB |           0.00% |
| [f01788231](https://filfox.info/en/address/f01788231) | San Jose, California, US |          81.00 TiB |      2.07% |   81.00 TiB |           0.00% |
| [f01828096](https://filfox.info/en/address/f01828096) | San Jose, California, US |          66.94 TiB |      1.71% |   66.94 TiB |           0.00% |
| [f01819592](https://filfox.info/en/address/f01819592) | San Jose, California, US |          49.97 TiB |      1.28% |   49.97 TiB |           0.00% |
| [f01843994](https://filfox.info/en/address/f01843994) |       Hilliard, Ohio, US |          48.94 TiB |      1.25% |   48.94 TiB |           0.00% |
| [f01844613](https://filfox.info/en/address/f01844613) |       Hilliard, Ohio, US |          43.31 TiB |      1.11% |   43.31 TiB |           0.00% |
| [f01844329](https://filfox.info/en/address/f01844329) |       Hilliard, Ohio, US |          43.09 TiB |      1.10% |   43.09 TiB |           0.00% |
| [f01844232](https://filfox.info/en/address/f01844232) |       Hilliard, Ohio, US |          42.34 TiB |      1.08% |   42.34 TiB |           0.00% |
| [f01844043](https://filfox.info/en/address/f01844043) |       Hilliard, Ohio, US |          39.66 TiB |      1.02% |   39.66 TiB |           0.00% |
| [f01844118](https://filfox.info/en/address/f01844118) |       Hilliard, Ohio, US |          36.25 TiB |      0.93% |   36.25 TiB |           0.00% |
| [f01825473](https://filfox.info/en/address/f01825473) | San Jose, California, US |          35.00 TiB |      0.90% |   35.00 TiB |           0.00% |
| [f01825475](https://filfox.info/en/address/f01825475) | San Jose, California, US |          35.00 TiB |      0.90% |   35.00 TiB |           0.00% |

![Provider Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/306/1671094774570.png)
### Deal Data Replication
The below table shows how each many unique data are replicated across storage providers.
- No more than 25% of unique data are stored with less than 4 providers.

⚠️ 100.00% of deals are for data replicated across less than 4 storage providers.

| Unique Data Size | Total Deals Made | Number of Providers | Deal Percentage |
| ---------------: | ---------------: | ------------------: | --------------: |
|         2.75 PiB |         3.40 PiB |                   1 |          89.05% |
|        53.78 TiB |       248.44 TiB |                   2 |           6.36% |
|        29.75 TiB |       179.03 TiB |                   3 |           4.59% |

![Replication Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/306/1671094775222.png)
### Deal Data Shared with other Clients
The below table shows how many unique data are shared with other clients.
Usually different applications owns different data and should not resolve to the same CID.

⚠️ CID sharing has been observed.

| Other Client                                                                                                          | Application                                                                                                              | Total Deals Affected | Unique CIDs |        Verifier |
| :-------------------------------------------------------------------------------------------------------------------- | :----------------------------------------------------------------------------------------------------------------------- | -------------------: | ----------: | --------------: |
| [f1727w2vwjctfo7hflr5trgqkl3c7texh7pl4grzq](https://filfox.info/en/address/f1727w2vwjctfo7hflr5trgqkl3c7texh7pl4grzq) | [GMverse](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/365)                                   |           443.44 TiB |       3,705 | LDN v3 multisig |
| [f1ffbtksiso5za73pypuxbxznng6rdv64nbihdtba](https://filfox.info/en/address/f1ffbtksiso5za73pypuxbxznng6rdv64nbihdtba) | [EpikProtocol](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/281)                              |           273.34 TiB |       2,771 |       LDN # 281 |
| [f1clwd2dooy2cflfilhzeq2ycl544b3heqsiwhjrq](https://filfox.info/en/address/f1clwd2dooy2cflfilhzeq2ycl544b3heqsiwhjrq) | [FiboAI](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/349)                                    |           162.34 TiB |       1,970 | LDN v3 multisig |
| [f1tivtdkq34mnfzso63wrr2xh6r2zo7aebao4jfla](https://filfox.info/en/address/f1tivtdkq34mnfzso63wrr2xh6r2zo7aebao4jfla) | `China travel service(HongKong) limited`                                                                                 |           117.63 TiB |         937 | LDN v3 multisig |
| [f1qjrlejxv5a73kxurwtxyrni6ji7orm74zeeetiy](https://filfox.info/en/address/f1qjrlejxv5a73kxurwtxyrni6ji7orm74zeeetiy) | [Mooc](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/223)                                      |            66.13 TiB |         515 | LDN v3 multisig |
| [f1ki4cjk27ypzjsuzkvvqzs6xobaweuoxfdcnpqhy](https://filfox.info/en/address/f1ki4cjk27ypzjsuzkvvqzs6xobaweuoxfdcnpqhy) | [TimeQuant](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/385)                                 |            64.25 TiB |       1,280 | LDN v3 multisig |
| [f17qd6x3leh5pa7vh6ewdaed7qhbn2mgofrokuayy](https://filfox.info/en/address/f17qd6x3leh5pa7vh6ewdaed7qhbn2mgofrokuayy) | [Drust](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/427)                                     |            62.56 TiB |       1,166 | LDN v3 multisig |
| [f1ojo3wo24zkeovndlxfpqmlgzlbysg5fiukmup4a](https://filfox.info/en/address/f1ojo3wo24zkeovndlxfpqmlgzlbysg5fiukmup4a) | `Titansoft`                                                                                                              |            60.81 TiB |         623 | LDN v3 multisig |
| [f1avhqgmeazxzvylz34l26o3nlj2ywnzaviwns3dq](https://filfox.info/en/address/f1avhqgmeazxzvylz34l26o3nlj2ywnzaviwns3dq) | [87v5\-CarsonVideo](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/392)                         |            46.88 TiB |         431 | LDN v3 multisig |
| [f1einobkrjcjk6gfc5ov6663vrri75hwdsjfs6pmq](https://filfox.info/en/address/f1einobkrjcjk6gfc5ov6663vrri75hwdsjfs6pmq) | [Cansoti](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/640)                                   |            25.16 TiB |         235 | LDN v3 multisig |
| [f1tgii4xgcp6um4n2w7eqaw6bwvnvyii2u7cjgzka](https://filfox.info/en/address/f1tgii4xgcp6um4n2w7eqaw6bwvnvyii2u7cjgzka) | [Meson\.Network ](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/187)                           |            19.47 TiB |         109 | LDN v3 multisig |
| [f1ajdk7e6ex7fvtjtydzgys47bcg7jub2baucun7y](https://filfox.info/en/address/f1ajdk7e6ex7fvtjtydzgys47bcg7jub2baucun7y) | [Ruikuyun Information Technology Co\., Ltd](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/529) |            13.28 TiB |         168 | LDN v3 multisig |
| [f1nmhjvibl7acp45lpxmo5kduz42evjazsyi4mzza](https://filfox.info/en/address/f1nmhjvibl7acp45lpxmo5kduz42evjazsyi4mzza) | `ubuckvnockai`                                                                                                           |             9.59 TiB |         168 | LDN v3 multisig |
| [f1bpncrva3scb63ege4w56w3udl35nt7ikhq2snwy](https://filfox.info/en/address/f1bpncrva3scb63ege4w56w3udl35nt7ikhq2snwy) | [Jaggy Inc\.](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/175)                               |             5.84 TiB |         123 |       LDN # 175 |

[^1]: To manually trigger this report, add a comment with text `checker:manualTrigger`
