### ISSUE TITLE
[DataCap Application] Slingshot Terra Fusion Data Sampler dataset for Haoqian Mx team

### ISSUE THREAD

**Issue by CodeIsLaw0108** [filecoin-project/filecoin-plus-large-datasets#308]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name:  Haoqian Mx
- Website / Social Media: https://twitter.com/Haoqian_Ma
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 1 PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100TiB
- On-chain address for first allocation: f1eto4dfafkoeukxenoc7vzexrvf6i4yqvhszrq2y

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
An application for participating slingshot 2.8
We are newcomer for slingshot and we want to try our best to finish all the tasks 

```

What is the primary source of funding for this project?
```
No cost ,
All the machines or any other fee for this application will be payed by ourselves 
Wish we will win finishing prize for covering some of them.
```

What other projects/ecosystem stakeholders is this project associated with?
```
Slingshot, MinerX, enterprise-sp-wp.
```

## Use-case details

Describe the data being stored onto Filecoin
```
The Terra Basic Fusion dataset is a fused dataset of the original Level 1 radiances from the five Terra instruments. 
```

Where was the data in this dataset sourced from?
```
https://registry.opendata.aws/terrafusion/
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://terrafusiondatasampler.s3.amazonaws.com/P108/TERRA_BF_L1B_O10204_20011118010522_F000_V001.h5
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
yes 
```

What is the expected retrieval frequency for this data?
```
Once a day
```

For how long do you plan to keep this dataset stored on Filecoin?
```
1 year+
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
All regions.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
I will upload my prepared CAR files to a web server and coordinate with providers to download and propose offline deals.
A prepared web file system where storing car files will be launched online for anyone who want to download for sealing 
Of course offline deal  is prefer.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
Any SPs who could prove that they have ability to make data safe and can finish the sealing tasks.
```

How will you be distributing deals across storage providers?
```
No more than 30% each project for a SP entry
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes have some, Will appreciate if community could help to find more suitable sp for sealing.
```

**Comment by CodeIsLaw0108** [comment]
@galen-mcandrew could you help to sign this issue if all the info is correct?

**Comment by galen-mcandrew** [comment]
@dkkapur can you verify this slingshot request?

**Comment by dkkapur** [comment]
Confirming that this is on the eligible datasets for Slingshot - https://github.com/filecoin-project/slingshot/blob/master/datasets.md. 

However - applicants that have received DataCap in the past for Slingshot V2 have met a very high bar in proving the quality of the work they are doing as well as the robustness of the deal distribution mechanism to ensure they work with several SPs and do not self-deal. On behalf of the Slingshot community, I'd love to hear more about @CodeIsLaw0108's plan to identify SPs and fairly distribute deals across them.

**Comment by woshidama323** [comment]
Hi  Any update ?
@dkkapur 
For "plan to identify SPs and fairly distribute deals across them"
1.  Need to check the sps' IPs  , Get useful infos from slack channels about a specific miner ID which i want to work with for identifying if there are together.
2. Talk to SPs and make sure will agree with slingshot rules, If broken, We will stop sending deals if not followed 
3.  Make sure all the SPs will be assigned with 3:1:1 for a certain project  by monitoring the dealing procedure


I think there are no reliable methods for doing this.
They are no reliable info on-chain for clarifying this unless any miners need to publish their public IP honestly.

**Comment by CodeIsLaw0108** [comment]
Hi  Any update ?
@dkkapur 
For "plan to identify SPs and fairly distribute deals across them"
1.  Need to check the sps' IPs  , Get useful infos from slack channels about a specific miner ID which i want to work with for identifying if there are together.
2. Talk to SPs and make sure will agree with slingshot rules, If broken, We will stop sending deals if not followed 
3.  Make sure all the SPs will be assigned with 3:1:1 for a certain project  by monitoring the dealing procedure


I think there are no reliable methods for doing this.
They are no reliable info on-chain for clarifying this unless any miners need to publish their public IP honestly.

**Comment by galen-mcandrew** [comment]
Has there been any progress in identifying SP's to work with? I know there are multiple other Slingshot participants that may be able to help provide some more details or starting points for you.

**Comment by dkkapur** [comment]
@kernelogic if you have any suggestions here, might be good to get your advice!

**Comment by kernelogic** [comment]
I agree there's no reliable methods for identifying without a pre-registration platform. I guess the second best alternative  would be SPs (or the entities) registered during the slingshot restore program earlier this year.

Given the short remaining time on the current phase 2.8 and the size of this LDN, if OP could give a planned list of SP and their respective owning entity to prove no self-dealing and following decentralization rules, that would be very convincing.

**Comment by dkkapur** [comment]
> Given the short remaining time on the current phase 2.8 and the size of this LDN, if OP could give a planned list of SP and their respective owning entity to prove no self-dealing and following decentralization rules, that would be very convincing.

+1. Looking forward to hearing from @CodeIsLaw0108

**Comment by CodeIsLaw0108** [comment]
Hi, Very happy while we know slingshot2.8 will continue up to 7.6 ,Thanks
Could you help to give us a list of SPs , and we could contact them directly ?
I think there is no necessary  for us to proving such issue if our list is from community ?

**Comment by dkkapur** [comment]
@CodeIsLaw0108 fair enough. The Slingshot site has information available about every deal uploaded and the SPs involved, e.g., for one of @kernelogic's projects, you can see the recent deal metadata here: https://slingshot.filecoin.io/project/62340a7a7d907fffc878620e/deals. 

Additionally, from Slingshot Evergreen, we publish a list of active SP IDs and their relative deal making here: https://api.evergreen.filecoin.io/public/qap.txt. 

What do you think?

**Comment by CodeIsLaw0108** [comment]
Yeah Thanks

1. f03223  f02301 (from https://slingshot.filecoin.io/project/62340a7a7d907fffc878620e/deals. Will ask kernelogic for help to contact the sp)
2. f01850141 (from cabrina) 

As for https://api.evergreen.filecoin.io/public/qap.txt. 
Could you please help to give slack name also ?
It's hard for me to find slack name from miner ID ?

**Comment by Chris00618** [comment]
Hey Cabrina, does this node f01850141 belong to you? @xingjitansuo
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/312
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/232
As you know, self dealing in LDN is not allowed in our community.
In addition,we found another case connected with you ,could you give some clarification about it. 
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/354

**Comment by xingjitansuo** [comment]
@Chris00618 
I totally understand and follow the community rule on prohibition of seal-dealing. I do not own SP f01850141.  I just recommend this node to @CodeIsLaw0108 .

**Comment by CodeIsLaw0108** [comment]
@Chris00618  Thanks for your reply after waiting so long time . 
Have checked with @xingjitansuo , Sorry i fault ,Just one of their SP before slingshot 2.8 ?
But can I still send deals for this miner ? Could you help to comments this and help us to speed up this procedure ?
![image](https://user-images.githubusercontent.com/81554458/175870777-befb9f4d-08ea-4c3f-a257-48448413df19.png)

We all want to participate slingshot 2.8 and of course want to get reward from this project 
But , some guys have finished almost all the task about slingshot 2.8 while we are still struggling applying the project, And project is almost end
Many SPs have to pay for Datacap as they need deals for sealing but only few client have gotten their datacap

Wish community could handle issues as quickly as possible , And you can closed this issue if there is any issue that will not meet the requirement, then  there is no necessary for us to ask for checking this issue again and again.

**Comment by dkkapur** [comment]
## Datacap Request Trigger
#### Total DataCap requested 
> 1 PiB
#### Expected weekly DataCap usage rate 
> 100 TiB 
#### Client address
> f1eto4dfafkoeukxenoc7vzexrvf6i4yqvhszrq2y

**Comment by xingjitansuo** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedfuwpyxffdezk2ddmgsf24mftex67gwsr5ke42sw7vwliblszmjw 
#### Address 
> f1eto4dfafkoeukxenoc7vzexrvf6i4yqvhszrq2y
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1a2lia2cwwekeubwo4nppt4v4vebxs2frozarz3q
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedfuwpyxffdezk2ddmgsf24mftex67gwsr5ke42sw7vwliblszmjw

**Comment by 1ane-1** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedv4j7evy4wbdwo62ld3dbfkazavhsyzzeoxy27p7o3xg22monsik 
#### Address 
> f1eto4dfafkoeukxenoc7vzexrvf6i4yqvhszrq2y
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1mdk7s2vntzm6hu35yuo6vjubtrpfnb2awhgvrri
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedv4j7evy4wbdwo62ld3dbfkazavhsyzzeoxy27p7o3xg22monsik

**Comment by psh0691** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacea3gryhu4zkbeksb3yjfcz7yv4czx5wo27xc5nz6ceuqon5a7dzlu 
#### Address 
> f1eto4dfafkoeukxenoc7vzexrvf6i4yqvhszrq2y
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1qdko4jg25vo35qmyvcrw4ak4fmuu3f5rif2kc7i
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacea3gryhu4zkbeksb3yjfcz7yv4czx5wo27xc5nz6ceuqon5a7dzlu

**Comment by psh0691** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec7iowtwost6ury7evnieetnrkf2k3vmmj4pskbivjhd7qdz3m7j4 
#### Address 
> f1eto4dfafkoeukxenoc7vzexrvf6i4yqvhszrq2y
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1qdko4jg25vo35qmyvcrw4ak4fmuu3f5rif2kc7i
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec7iowtwost6ury7evnieetnrkf2k3vmmj4pskbivjhd7qdz3m7j4

**Comment by Filefly-ph** [comment]
> 

So do you have any idea of who is f01850141? This guy is a major SP in Filecoin and you're cooperating with him/her.

**Comment by jamerduhgamer** [comment]
Is this a bug where psh0691 was able to both propose and approve the datacap request?

**Comment by psh0691** [comment]
@jamerduhgamer @Filefly-ph 
I am not cooperating with this applicant, and I cannot make proposals and approvals at once. 
In this case, when there was a bug where the proposal request was repeated, I signed the approval, and the proposal was repeated.
I remember reporting to Slack's notary channel.
https://filecoinproject.slack.com/archives/C01HRNU4VBK/p1661305706567739

**Comment by jamerduhgamer** [comment]
Ah that makes sense now. You tried to approve the datacap request and the wrong message was sent. Thank you for answering my question @psh0691

**Comment by xingjitansuo** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb4iahqcggxwwzmuoqrkcopozakg23jeada535lggedkm2dq333gu 
#### Address 
> f1eto4dfafkoeukxenoc7vzexrvf6i4yqvhszrq2y
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1a2lia2cwwekeubwo4nppt4v4vebxs2frozarz3q
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb4iahqcggxwwzmuoqrkcopozakg23jeada535lggedkm2dq333gu

**Comment by BigD-Exchange** [comment]
@CodeIsLaw0108 Hi! Great to see you have gotten approval for DataCap. If you are looking for storage providers to store these data or have any questions, please visit #bigdata-exchange on Filecoin Slack or reply here. 

We have strong demand from a diverse group of SPs, who are actively looking to onboard more data.

**Comment by newwebgroup** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecqz62lvdlyururvosbmjmvex6oajkiwqz6u4ud7osq75qhnhj7h6 
#### Address 
> f1eto4dfafkoeukxenoc7vzexrvf6i4yqvhszrq2y
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1e77zuityhvvw6u2t6tb5qlnsegy2s67qs4lbbbq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecqz62lvdlyururvosbmjmvex6oajkiwqz6u4ud7osq75qhnhj7h6

**Comment by kernelogic** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebbcmchsz2ofwurkw7xxy6tknrgsncxcbdwvskd6woa5jfhmgbr4m 
#### Address 
> f1eto4dfafkoeukxenoc7vzexrvf6i4yqvhszrq2y
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebbcmchsz2ofwurkw7xxy6tknrgsncxcbdwvskd6woa5jfhmgbr4m

**Comment by psh0691** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacediwkrbapbdiqqupsvau6rwslwtmvfnb53gmt7jcf2oqfxjcve5za 
#### Address 
> f1eto4dfafkoeukxenoc7vzexrvf6i4yqvhszrq2y
#### Datacap Allocated
> 274.00TiB
#### Signer Address
> f1qdko4jg25vo35qmyvcrw4ak4fmuu3f5rif2kc7i
#### Id
> 5ba40089-e49d-4f9e-821e-44c0bc47cffb
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacediwkrbapbdiqqupsvau6rwslwtmvfnb53gmt7jcf2oqfxjcve5za

**Comment by filplus-checker** [comment]
## DataCap and CID Checker Report[^1]
 - Organization: ` Haoqian Mx`
 - Client: `f1eto4dfafkoeukxenoc7vzexrvf6i4yqvhszrq2y`
### Storage Provider Distribution
The below table shows the distribution of storage providers that have stored data for this client.

If this is the first time a provider takes verified deal, it will be marked as `new`.

For most of the datacap application, below restrictions should apply.
 - Storage provider should not exceed 25% of total datacap.
 - Storage provider should not be storing duplicate data for more than 20%.
 - Storage provider should have published its public IP address.
 - All storage providers should be located in different regions.

⚠️ [f01926698](https://filfox.info/en/address/f01926698) has unknown IP location.

| Provider                                                    |                           Location | Total Deals Sealed | Percentage | Unique Data | Duplicate Deals |
| :---------------------------------------------------------- | ---------------------------------: | -----------------: | ---------: | ----------: | --------------: |
| [f01969779](https://filfox.info/en/address/f01969779)`new`  |            Clifton, New Jersey, US |          83.13 TiB |     18.40% |   83.13 TiB |           0.00% |
| [f0143858](https://filfox.info/en/address/f0143858)         |            Clifton, New Jersey, US |          80.34 TiB |     17.79% |   80.34 TiB |           0.00% |
| [f03223](https://filfox.info/en/address/f03223)             |           San Jose, California, US |          79.06 TiB |     17.50% |   79.06 TiB |           0.00% |
| [f02301](https://filfox.info/en/address/f02301)             |           San Jose, California, US |          77.25 TiB |     17.10% |   77.25 TiB |           0.00% |
| [f0240185](https://filfox.info/en/address/f0240185)         |            Clifton, New Jersey, US |          57.47 TiB |     12.72% |   57.47 TiB |           0.00% |
| [f0142637](https://filfox.info/en/address/f0142637)         |               Chengdu, Sichuan, CN |          41.16 TiB |      9.11% |   41.16 TiB |           0.00% |
| [f01926698](https://filfox.info/en/address/f01926698)       |                            Unknown |          27.19 TiB |      6.02% |   27.19 TiB |           0.00% |
| [f01850141](https://filfox.info/en/address/f01850141)       | Hong Kong, Central and Western, HK |           6.13 TiB |      1.36% |    6.13 TiB |           0.00% |

![Provider Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/308/1671094786020.png)
### Deal Data Replication
The below table shows how each many unique data are replicated across storage providers.
- No more than 25% of unique data are stored with less than 4 providers.

✔️ Data replication looks healthy.

| Unique Data Size | Total Deals Made | Number of Providers | Deal Percentage |
| ---------------: | ---------------: | ------------------: | --------------: |
|        19.06 TiB |        19.06 TiB |                   1 |           4.22% |
|        19.75 TiB |        39.50 TiB |                   2 |           8.74% |
|         3.69 TiB |        11.06 TiB |                   3 |           2.45% |
|        24.44 TiB |        97.75 TiB |                   4 |          21.64% |
|        35.78 TiB |       178.91 TiB |                   5 |          39.61% |
|        16.41 TiB |        98.44 TiB |                   6 |          21.79% |
|         1.00 TiB |         7.00 TiB |                   7 |           1.55% |

![Replication Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/308/1671094786537.png)
### Deal Data Shared with other Clients
The below table shows how many unique data are shared with other clients.
Usually different applications owns different data and should not resolve to the same CID.

⚠️ CID sharing has been observed.

| Other Client                                                                                                          | Application                                                                                                  | Total Deals Affected | Unique CIDs |        Verifier |
| :-------------------------------------------------------------------------------------------------------------------- | :----------------------------------------------------------------------------------------------------------- | -------------------: | ----------: | --------------: |
| [f1o54sve7ede7im4caux3ug7lsyjmbue7ss3zzl6y](https://filfox.info/en/address/f1o54sve7ede7im4caux3ug7lsyjmbue7ss3zzl6y) | [FilSwan](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/278)                       |            85.25 TiB |         384 | LDN v3 multisig |
| [f1bstbq5bi72kyovhh7zoo2f6l6uivsjz4ey5dnqq](https://filfox.info/en/address/f1bstbq5bi72kyovhh7zoo2f6l6uivsjz4ey5dnqq) | [FilSwan](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/917)                       |            33.38 TiB |         258 | LDN v3 multisig |
| [f14r2jybmccwiu6hze4fu55jyhclktvwacec56hea](https://filfox.info/en/address/f14r2jybmccwiu6hze4fu55jyhclktvwacec56hea) | [ FilSwan](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/15)                       |             9.16 TiB |         126 | LDN v3 multisig |
| [f1r3d25hl2y7rqlsu2mgczdethy4qqjmkfdlmibfq](https://filfox.info/en/address/f1r3d25hl2y7rqlsu2mgczdethy4qqjmkfdlmibfq) | [ NEXRAD \- FilSwan](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/80)             |             6.19 TiB |         198 | LDN v3 multisig |
| [f13d6zt424jkp55u7kp67azotkzadtlokwnz2ntxa](https://filfox.info/en/address/f13d6zt424jkp55u7kp67azotkzadtlokwnz2ntxa) | [ FilSwan \- Slingshot Restore](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/157) |             1.97 TiB |          63 | LDN v3 multisig |

[^1]: To manually trigger this report, add a comment with text `checker:manualTrigger`

**Comment by cryptowhizzard** [comment]
Hello @CodeIsLaw0108 

It seems that the total datacap is reached. Can you close the issue please?

Thanks!
