### ISSUE TITLE
[DataCap Application]China Plant Research Base

### ISSUE THREAD

**Issue by vetetable360** [filecoin-project/filecoin-plus-large-datasets#309]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Plant Research South China Base of China Agricultural University
- Website / Social Media:  http://vetetable.com/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100TiB
- On-chain address for first allocation: f15d5pxriekd6rcxx2t5xlebbubc5qlqtcuyewxfy

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Vetetable.com, also known as Plant Elements, was founded in 2019. It was initiated by 5 professors and 12 scholars from Agricultural University, and a plant science website jointly built by several plant enthusiasts from all over the country. Preserve originals and copies of botanical photographs, negatives, slides, digital image source files, and other botanical-related images. Nearly 10,000 original pictures of plants, pictures of wild plants such as ferns, and 100,000 digital photos have been collected, which have produced a significant effect of building a library in scientific research, popular science education, book publishing, and economic and social services. The website aims to promote plant science, popularize plant knowledge, and let more people understand the habits and characteristics of different plants, so as to achieve peaceful coexistence between humans and nature, and make the earth full of green and oxygen.
```

What is the primary source of funding for this project?
```
Government grants and fund sponsorship
```

What other projects/ecosystem stakeholders is this project associated with?
```
No.
```

## Use-case details

Describe the data being stored onto Filecoin
```
Plant Elements has its own research center to study the distribution, growth characteristics, growth environment and endangerment reasons of plants. The research data includes not limited to pictures, videos and analysis data on the reasons for plant endangerment.
```

Where was the data in this dataset sourced from?
```
Derived from plant practice research, it includes pictures and videos in various forms, involving plant characteristics, growth laws and cycles, and growth environment monitoring.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
http://vetetable.com/categories
http://vetetable.com/pictures
http://vetetable.com/videos
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Open Data. There are no restrictions on the use of this data.
```

What is the expected retrieval frequency for this data?
```
People interested in this data can retrieve it at any time
```

For how long do you plan to keep this dataset stored on Filecoin?
```
More than three years.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Asia, North America.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
We will upload the plant data files we prepared to the web server, coordinate the download with the storage service provider, and propose offline transactions. We can also use the filswan platform to automate this process.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We are willing to cooperate with any deposit miner who is interested in receiving transactions.
```

How will you be distributing deals across storage providers?
```
It is provided to miners capable of storing data in an equal distribution manner.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, we have sufficient funds and resources
```

**Comment by flyworker** [comment]
Glad to see product want to use filswan. We would like to check with the data integration process.

**Comment by vetetable360** [comment]
> Glad to see product want to use filswan. We would like to check with the data integration process.

We would appreciate it if you could help us advance this application.We are happy to be checked by you, what data do we need to provide now?

**Comment by UnionLabs2020** [comment]
This applicant (Plant Research South China Base of China Agricultural University) looks like an official organization, could you provide your official certification of authorization by your university?

**Comment by vetetable360** [comment]
@tech-UnionLabs  Sorry, I haven't received your reply. Do you have any questions?

**Comment by vetetable360** [comment]
@galen-mcandrew @dkkapur @flyworker @IPFSUnion 

1. We have prepared slides for the Governance Call on 5.17, but unfortunately the time is too short, and we have not had the opportunity to give a speech. For this reason, we specially recorded a video ([ video link ](https://drive.google.com/file/d/17WewJi_1qcE3iebUHPdMUMd0UHV1u9Ci/view?usp=sharing)), hoping that notaries will have a better understanding of our application. Our vast amounts of data are stored on traditional cloud storage servers. Hope to get more support and help through the application .
2. We have passed the Fil+ client on-boarding and DataCap applications ( https://github.com/filecoin-project/filecoin-plus-client-onboarding/issues/1684) on April 22, and have been successfully allocated to 6 SPs in the form of online and offline orders within two weeks.
Could you process our application to the next stage? If you need more information, we are glad to provide it.

**Comment by Sunnyiscoming** [comment]
@vetetable360
I have submitted an application to you to view: https://docs.google.com/document/d/1LqAtofO2BdDeVqdZc3u264ORSi4d8M2WDNSQ1j5l1G4/edit?usp=sharing

Could you pass this request?

**Comment by Sunnyiscoming** [comment]
Can you explain about the following questions?
1. The domain name of website is not recorded
2. The organization cannot be checked on baidu
3. The contact information published on the website is personal.

**Comment by vetetable360** [comment]
> Can you explain about the following questions?
> 
> 1. The organization cannot be checked on baidu
> 2. The contact information published on the website is personal.

1. This organization is a non-governmental public welfare organization without any funds, and it cannot be promoted to relevant commercial organizations, so there is no introduction of relevant organizations on the website. This point is mentioned in [the PPT introduction](https://docs.google.com/presentation/d/1d4vgr-o4znDOnspgTfFtocxSquv4DDfLM8CYwSTiLL8/edit?usp=sharing). The main purpose is to popularize plant knowledge and collect relevant plant information from the public.
2. The contact person and phone number provided on the website is the person in charge of the website. She needs to deal with all kinds of emails and problems from time to time.

**Comment by swatchliu** [comment]
Hi @vetetable360，Could you confirm that your website was established in 2019？

**Comment by vetetable360** [comment]
Hello @swatchliu , our website is definitely built before 2019. For some reasons, before applying for the filecoin-plus-large-datasets, we changed the domain. It used to be www.upingou.com. Now entering this domain can still be opened, you can check, thank you!

**Comment by vetetable360** [comment]
Hello @EGGRICE02 , I have sorted out your question and answered as follows:
1. What is your relationship with New Token?
We are a non-commercial organization, and the technical complexity is too high to be placed on the filcoin network, so we asked New Token to help us provide technology. At first, the application for small data was submitted in the name of New Token. Later, we will look at the requirements. Saying that the data requester needs to submit, we made a change. The multiple submission applications in your screenshot are a bug of the website. The submissions have not been successful for many times. Many people have reported this bug before.
2. The previous small data has not been encapsulated?
Our previous small data has been almost completely packaged, and only about 600g is left, because the sp was not packaged and returned successfully. I don't know why what you see is that there are 3t left, you can log in to this website https://verify.glif.io/ to check the remaining datacap of our address.
3. Questions about pictures:
Google can search for us and similar pictures, which means that our content is completely open and meets the requirements of filcoin. We are the first company to store the content of plants on filcoin, and we are very happy. For all the pictures of the website, we have the original pictures recorded in the background, see [the original picture sample ](https://pan.baidu.com/s/1pIewCEH84iQ3gpbbaHrEkA?pwd=854t)
4. Regarding the amount of data:
Regarding plant image files, we have a lot of data requirements, which is very certain. The front desk of the website is only a part of the content, which has been proved. Because the online transmission speed was very slow when sending small data to sp before, resulting in a very long cycle, we only need to apply for big data and cooperate with sp in an offline way.

**Comment by vetetable360** [comment]
Hello @EGGRICE02 , I have sorted out your question and answered as follows:
1. What is your relationship with New Token?
We are a non-commercial organization, and the technical complexity is too high to be placed on the filcoin network, so we asked New Token to help us provide technology. At first, the application for small data was submitted in the name of New Token. Later, we will look at the requirements. Saying that the data requester needs to submit, we made a change. The multiple submission applications in your screenshot are a bug of the website. The submissions have not been successful for many times. Many people have reported this bug before.
2. The previous small data has not been encapsulated?
Our previous small data has been almost completely packaged, and only about 600g is left, because the sp was not packaged and returned successfully. I don't know why what you see is that there are 3t left, you can log in to this website https://verify.glif.io/ to check the remaining datacap of our address.
3. Questions about pictures:
Google can search for us and similar pictures, which means that our content is completely open and meets the requirements of filcoin. We are the first company to store the content of plants on filcoin, and we are very happy. For all the pictures of the website, we have the original pictures recorded in the background, see [the original picture sample](https://pan.baidu.com/s/1pIewCEH84iQ3gpbbaHrEkA?pwd=854t) 
4. Regarding the amount of data:
Regarding plant image files, we have a lot of data requirements, which is very certain. The front desk of the website is only a part of the content, which has been proved. Because the online transmission speed was very slow when sending small data to sp before, resulting in a very long cycle, we only need to apply for big data and cooperate with sp in an offline way.

**Comment by EGGRICE02** [comment]
Can you share a more detailed plan with us on how to transfer data offline between continents? You know for security concern, most counties have rigid regulations on intercontinental data transfer.

**Comment by dkkapur** [comment]
@vetetable360 can you email [filplus@fil.org](mailto:filplus@fil.org) with your official work email so we can share this with notaries as a form of proof that you represent this organization?

**Comment by vetetable360** [comment]
The email has been sent. Thank you @dkkapur

**Comment by zhonghdadi** [comment]
any updates？ @galen-mcandrew @dkkapur

**Comment by galen-mcandrew** [comment]
## Datacap Request Trigger
#### Total DataCap requested 
> 5PiB
#### Expected weekly DataCap usage rate 
> 100TiB 
#### Client address
> f15d5pxriekd6rcxx2t5xlebbubc5qlqtcuyewxfy

**Comment by vetetable360** [comment]
hi, dear notaries. Could you sign it for us？ @flyworker @swatchliu @IPFSUnion

**Comment by newwebgroup** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb7xef36vyaakne4u3s42vqa7w42imfvtkylk5434hhnkbhc2hivc 
#### Address 
> f15d5pxriekd6rcxx2t5xlebbubc5qlqtcuyewxfy
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1e77zuityhvvw6u2t6tb5qlnsegy2s67qs4lbbbq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb7xef36vyaakne4u3s42vqa7w42imfvtkylk5434hhnkbhc2hivc

**Comment by newwebgroup** [comment]
After the application was approved, it stagnated for a long time
It doesn't seem to have any obvious problems
I will continue to pay attention to it in the future

**Comment by liyunzhi-666** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaivaifn5xlee6vutniqyalshj7bdgso5eywrp6tpipxsg5xyjfsw 
#### Address 
> f15d5pxriekd6rcxx2t5xlebbubc5qlqtcuyewxfy
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1pszcrsciyixyuxxukkvtazcokexbn54amf7gvoq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaivaifn5xlee6vutniqyalshj7bdgso5eywrp6tpipxsg5xyjfsw

**Comment by BigD-Exchange** [comment]
@vetetable360 Hi! Great to see you have gotten approval for DataCap. If you are looking for more storage providers to store these data or have any questions, please visit #bigdata-exchange on Filecoin Slack or reply here. 

We have strong demand from a diverse group of SPs, who are actively looking to onboard more data.

**Comment by kernelogic** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecdjnayjjcbely72ps6x3ekmkawghel4kpckxgcv4uvxax7h4kyeu 
#### Address 
> f15d5pxriekd6rcxx2t5xlebbubc5qlqtcuyewxfy
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecdjnayjjcbely72ps6x3ekmkawghel4kpckxgcv4uvxax7h4kyeu

**Comment by newwebgroup** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedaif74fuqzsapxxpw4d2hsaem6wg4y57k4zvs4unglwrc3wk3dtu 
#### Address 
> f15d5pxriekd6rcxx2t5xlebbubc5qlqtcuyewxfy
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1e77zuityhvvw6u2t6tb5qlnsegy2s67qs4lbbbq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedaif74fuqzsapxxpw4d2hsaem6wg4y57k4zvs4unglwrc3wk3dtu

**Comment by newwebgroup** [comment]
**Tip**
As the f01858410 quota was exhausted, the last approval and signature did not receive the quota.
So I reviewed and signed again.


<img width="821" alt="image" src="https://user-images.githubusercontent.com/100118145/191889686-12635258-2021-4a34-89ed-d5c4ba862733.png">

**Comment by NDLABS-OFFICE** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaqcjpmhopwv3eknxxq3fnhptvgahzguuawimm7byvv7cqvdvthns 
#### Address 
> f15d5pxriekd6rcxx2t5xlebbubc5qlqtcuyewxfy
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1yayfsv6whu3rheviucvventj3y6t542xfpb47ei
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaqcjpmhopwv3eknxxq3fnhptvgahzguuawimm7byvv7cqvdvthns

**Comment by Tom-OriginStorage** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceamlvmg26omu7cfumenfpa2v4cyhcx2mzc5mbfzi5dq637hb7w4wo 
#### Address 
> f15d5pxriekd6rcxx2t5xlebbubc5qlqtcuyewxfy
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1q6bpjlqia6iemqbrdaxr2uehrhpvoju3qh4lpga
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceamlvmg26omu7cfumenfpa2v4cyhcx2mzc5mbfzi5dq637hb7w4wo

**Comment by newwebgroup** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb6u5lu23bdnb7wranbtolu32ws63i7cyeyzm257xahn433wba4o2 
#### Address 
> f15d5pxriekd6rcxx2t5xlebbubc5qlqtcuyewxfy
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1e77zuityhvvw6u2t6tb5qlnsegy2s67qs4lbbbq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb6u5lu23bdnb7wranbtolu32ws63i7cyeyzm257xahn433wba4o2

**Comment by Joss-Hua** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebytppsbkni6mhtgudrxdq7tt7gkfoyeaq5t7snll7evqp4bdatma 
#### Address 
> f15d5pxriekd6rcxx2t5xlebbubc5qlqtcuyewxfy
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1tfg54zzscugttejv336vivknmsnzzmyudp3t7wi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebytppsbkni6mhtgudrxdq7tt7gkfoyeaq5t7snll7evqp4bdatma

**Comment by Tom-OriginStorage** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceanwl5v4sxtwju2ndtgtifbc7vr6llgnsq2ok3fkrqmzksrug64qo 
#### Address 
> f15d5pxriekd6rcxx2t5xlebbubc5qlqtcuyewxfy
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1q6bpjlqia6iemqbrdaxr2uehrhpvoju3qh4lpga
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceanwl5v4sxtwju2ndtgtifbc7vr6llgnsq2ok3fkrqmzksrug64qo

**Comment by kernelogic** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb5hqgn7344ikqqyaqwyz4iml7rzpdsqm6rvnmk3pcffivguqkwa6 
#### Address 
> f15d5pxriekd6rcxx2t5xlebbubc5qlqtcuyewxfy
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb5hqgn7344ikqqyaqwyz4iml7rzpdsqm6rvnmk3pcffivguqkwa6

**Comment by newwebgroup** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec7valosttg5hebnzsmq3ikanipozf5brjzzhyvp2zu24xsl544c6 
#### Address 
> f15d5pxriekd6rcxx2t5xlebbubc5qlqtcuyewxfy
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1e77zuityhvvw6u2t6tb5qlnsegy2s67qs4lbbbq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec7valosttg5hebnzsmq3ikanipozf5brjzzhyvp2zu24xsl544c6

**Comment by Tom-OriginStorage** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebsxtgxn3gx37dfbfe6blxsvo6eqq6fo7tqvbd5u4bcrlitnhhveu 
#### Address 
> f15d5pxriekd6rcxx2t5xlebbubc5qlqtcuyewxfy
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1q6bpjlqia6iemqbrdaxr2uehrhpvoju3qh4lpga
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebsxtgxn3gx37dfbfe6blxsvo6eqq6fo7tqvbd5u4bcrlitnhhveu

**Comment by liyunzhi-666** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebxfvc2jbiubcr74rubvhdt3zznz665krtetxyqdjwxxi7pufk3cm 
#### Address 
> f15d5pxriekd6rcxx2t5xlebbubc5qlqtcuyewxfy
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1pszcrsciyixyuxxukkvtazcokexbn54amf7gvoq
#### Id
> b68997ca-d4b6-4e84-9a5f-22f3b73399bf
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebxfvc2jbiubcr74rubvhdt3zznz665krtetxyqdjwxxi7pufk3cm

**Comment by Tom-OriginStorage** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecscwgoz2svkageslkymwm7gpkhlk5zlhtmxupk5dxtzhmoj7cdve 
#### Address 
> f15d5pxriekd6rcxx2t5xlebbubc5qlqtcuyewxfy
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1q6bpjlqia6iemqbrdaxr2uehrhpvoju3qh4lpga
#### Id
> 8fdb2f53-3cea-4789-9619-ab4a4156cd44
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecscwgoz2svkageslkymwm7gpkhlk5zlhtmxupk5dxtzhmoj7cdve

**Comment by newwebgroup** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecymsqky2sgmfjfbcfyjooe5amzplitd4mjrrxumpd5gwoa2xhgkw 
#### Address 
> f15d5pxriekd6rcxx2t5xlebbubc5qlqtcuyewxfy
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1e77zuityhvvw6u2t6tb5qlnsegy2s67qs4lbbbq
#### Id
> 8fdb2f53-3cea-4789-9619-ab4a4156cd44
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecymsqky2sgmfjfbcfyjooe5amzplitd4mjrrxumpd5gwoa2xhgkw

**Comment by NDLABS-OFFICE** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebzzni43gxzxqwo3l3bpbpxnhtogicbpjubo6lkp6ekxruseppwoq 
#### Address 
> f15d5pxriekd6rcxx2t5xlebbubc5qlqtcuyewxfy
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1yayfsv6whu3rheviucvventj3y6t542xfpb47ei
#### Id
> 0020bc72-da2b-4d3c-9f6e-4b6194d34727
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebzzni43gxzxqwo3l3bpbpxnhtogicbpjubo6lkp6ekxruseppwoq

**Comment by stcouldlisa** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaymumgfhhew7rndx7ozuua2mmtgnhvbfgmwq3p5y5re673d7vu24 
#### Address 
> f15d5pxriekd6rcxx2t5xlebbubc5qlqtcuyewxfy
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1jvvltduw35u6inn5tr4nfualyd42bh3vjtylgci
#### Id
> 0020bc72-da2b-4d3c-9f6e-4b6194d34727
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaymumgfhhew7rndx7ozuua2mmtgnhvbfgmwq3p5y5re673d7vu24

**Comment by raghavrmadya** [comment]
This application has been flagged for review by the trust and transparency WG. Notaries are requested to pause signing additional tranches while the WG investigates and conducts retrievals. @vetetable360 , could you assist us in retrievals and ask the SPs you are working with the same? Your cooperation will help us unblock things quickly. 

Thanks

**Comment by vetetable360** [comment]
hi, @raghavrmadya :
Thank you for your concern for us! We have been working on this data according to the prescribed principles.
Welcome your supervision and inspection：

309 Up to now, 4PiB quota has been used to load data into Filecoin
This time period is about two months. This is the schedule we have listed according to Approved.
<img width="263" alt="image" src="https://user-images.githubusercontent.com/102020973/202348082-29ce6440-db25-4ffe-9e68-4e8409dde130.png">

From the data we have loaded into Filecoin，We randomly selected 3 Car files from our data for verification:
QmVCJrA9eR6d5tJCGm1xMLw2xzNsEzweeUZpDzbdh9dsLi.car （Piece CID：baga6ea4seaqji4oh4oyixn4deo5itluo4kgvasgvml5lxx2ujmbex2s2y3ehwlq）

Qmbi8H1q5KJobHqP7MkGwcDsfCF3pGoZxANbiBj5iLLYZ3.car  （Piece CID：baga6ea4seaqndnnwja2yimwct7xb6hh67wj256h6flpttw3witmw7yqhrt57ena）

QmeZhuoLCctcGFyaXWPkFaPC7NQT9nJmkYJTiYkKrJCayw.car（Piece CID：baga6ea4seaqjugvzfvczzjdh7uazf7uylnc2pakmcrmtqfibchxbk7atcj4ciea）

1) Let's make sure that the provided data samples are really stored in Filecoin
adopt https://filecoin.tools/ On this website, we checked the piece CID of the three car files
![image](https://user-images.githubusercontent.com/102020973/202348203-c150f841-e7e4-40bb-afab-0aec85f8fba8.png)
![image](https://user-images.githubusercontent.com/102020973/202348236-0363d4af-970d-4fbe-979b-49b1798439db.png)
![image](https://user-images.githubusercontent.com/102020973/202348256-1f947ec1-77db-4472-ade5-f23ff4ef6bfb.png)

2) Let's confirm whether these data are business related data or randomly generated data
And we restored the Car file to a readable state
You can visit and view through this link
http://112.49.47.204:9400/

The red folder is used to restore the data to a readable state
The green folder is in Car status
<img width="640" alt="image" src="https://user-images.githubusercontent.com/102020973/202348315-3ee4bdc4-31d3-4ad6-86d4-70a7659f3f8f.png">

**Comment by raghavrmadya** [comment]
Can you explain this? - 
All five of SPs were created on the same day. 4 of them within 5 minutes of each other. Also, two of them have the same IP address (which could be fine if that is the "Lead SP" that gets two copies) but its almost impossible to have the same miner creation dates if it wasn't the same entity initializing SPs back to back. All 5 SPs are nearly the same size as well which is also suspicious.
SP ID (Size) - Creation Date - IP Address - Country
f01938665 (37 PiB) - 2022-10-14 2:57:00
/ip4/162.219.87.139/tcp/11243 - Hong Kong
f01938714 (36 PiB) - 2022-10-14 4:40:30
/ip4/162.219.87.140/tcp/21241 - Hong Kong
f01938717 (34 PiB) - 2022-10-14 4:43:30
/ip4/203.116.52.34/tcp/33340 - Singapore
f01938718 (35 PiB) - 2022-10-14 4:43:30
/ip4/40.143.168.100/tcp/11820 - USA
f01938721 (34 PiB) - 2022-10-14 4:45:30 -
/ip4/43.228.183.90/tcp/15910 - Hong Kong

**Comment by vetetable360** [comment]
hi, @raghavrmadya : 
According to our many conversations with SPs, the Miner is indeed from a different SP, but it is the same company that provides technical services to the SP, and the nodes are also created by the same technical service company, so some of its behavior is similar. 
The owners of SPs belong to completely different entities, they are located in three different countries, four different regions, the geographical distribution of SPs is in line with Filplus requirements. 
 
As a Client, we spent a lot of time looking for SP in the early stage. However, due to the constraints of investment pace, technical strength and other conditions, our progress was very slow. Therefore, we later found a technical service company, which provided services for multiple SPs. They told us that the nodes were indeed owned by completely different investors. After that, our data distribution speed was guaranteed.

**Comment by vetetable360** [comment]
hi, @raghavrmadya:
Whether the investigation of 309 can be closed?
 If we can get a notary to take the next step?

**Comment by Datadaos** [comment]
I noticed this in slack.
Can we get data samples?
* Notaries should ask for retrieval random deal id in each of the following allocation time frame,
![image](https://user-images.githubusercontent.com/114021295/204160158-3efe7ac0-48c9-4d9c-bae6-ab6feb88d3e7.png)
* Data client should provide a way of how to read the data

if the request is not satisfied.
the datacap allocation should not be signed.

**Comment by kernelogic** [comment]
The allocation amount seems weird. From the table above, it is over the total 5PiB.

**Comment by vetetable360** [comment]
The allocation amount seems weird. From the table above, it is over the total 5PiB.

——Yes, there was a data difference of 50t. 
The first batch of data 50t was directly skipped because there was no limit of official RKH.

**Comment by newwebgroup** [comment]
The client contacted us and hoped that we could support them,
According to the data samples provided above, the requirements are met.
It is common that multiple nodes are provided with technical services by the same technical team.

From KYC and data samples, we are willing to support the LDN to continue.

cc @raghavrmadya

**Comment by filplus-checker** [comment]
## DataCap and CID Checker Report[^1]
 - Organization: `Plant Research South China Base of China Agricultural University`
 - Client: `f15d5pxriekd6rcxx2t5xlebbubc5qlqtcuyewxfy`
### Storage Provider Distribution
The below table shows the distribution of storage providers that have stored data for this client.

If this is the first time a provider takes verified deal, it will be marked as `new`.

For most of the datacap application, below restrictions should apply.
 - Storage provider should not exceed 25% of total datacap.
 - Storage provider should not be storing duplicate data for more than 20%.
 - Storage provider should have published its public IP address.
 - All storage providers should be located in different regions.

⚠️ 23.93% of total deal sealed by [f01193812](https://filfox.info/en/address/f01193812) are duplicate data.

| Provider                                                    |                           Location | Total Deals Sealed | Percentage | Unique Data | Duplicate Deals |
| :---------------------------------------------------------- | ---------------------------------: | -----------------: | ---------: | ----------: | --------------: |
| [f01938721](https://filfox.info/en/address/f01938721)       | Hong Kong, Central and Western, HK |         817.13 TiB |     18.98% |  817.13 TiB |           0.00% |
| [f01938718](https://filfox.info/en/address/f01938718)       |    Morrisville, North Carolina, US |         815.50 TiB |     18.95% |  815.50 TiB |           0.00% |
| [f01938714](https://filfox.info/en/address/f01938714)       |     Sham Shui Po, Sham Shui Po, HK |         801.91 TiB |     18.63% |  801.91 TiB |           0.00% |
| [f01938665](https://filfox.info/en/address/f01938665)       |     Sham Shui Po, Sham Shui Po, HK |         799.84 TiB |     18.58% |  799.84 TiB |           0.00% |
| [f01938717](https://filfox.info/en/address/f01938717)       |           Singapore, Singapore, SG |         728.22 TiB |     16.92% |  728.22 TiB |           0.00% |
| [f01852325](https://filfox.info/en/address/f01852325)       | Hong Kong, Central and Western, HK |          87.72 TiB |      2.04% |   87.72 TiB |           0.00% |
| [f01852023](https://filfox.info/en/address/f01852023)       |                   Busan, Busan, KR |          67.22 TiB |      1.56% |   67.22 TiB |           0.00% |
| [f01852677](https://filfox.info/en/address/f01852677)       |    Morrisville, North Carolina, US |          64.91 TiB |      1.51% |   64.91 TiB |           0.00% |
| [f01852664](https://filfox.info/en/address/f01852664)       |           Singapore, Singapore, SG |          64.38 TiB |      1.50% |   64.38 TiB |           0.00% |
| [f01851482](https://filfox.info/en/address/f01851482)       |                   Busan, Busan, KR |          52.75 TiB |      1.23% |   52.75 TiB |           0.00% |
| [f01193812](https://filfox.info/en/address/f01193812)       |               Boardman, Oregon, US |           2.74 TiB |      0.06% |    2.09 TiB |          23.93% |
| [f01395673](https://filfox.info/en/address/f01395673)       |                 Fuzhou, Fujian, CN |           1.38 TiB |      0.03% |    1.16 TiB |          15.91% |
| [f01702940](https://filfox.info/en/address/f01702940)       |                  Dallas, Texas, US |         424.00 GiB |      0.01% |  424.00 GiB |           0.00% |
| [f01211558](https://filfox.info/en/address/f01211558)`new`  |                   Wuhan, Hubei, CN |         176.00 GiB |      0.00% |  176.00 GiB |           0.00% |
| [f01392893](https://filfox.info/en/address/f01392893)       |       Amsterdam, North Holland, NL |         120.02 GiB |      0.00% |  120.02 GiB |           0.00% |
| [f01606849](https://filfox.info/en/address/f01606849)       |               Montréal, Quebec, CA |          16.00 GiB |      0.00% |   16.00 GiB |           0.00% |
| [f01716466](https://filfox.info/en/address/f01716466)       |           Singapore, Singapore, SG |           8.00 GiB |      0.00% |    8.00 GiB |           0.00% |
| [f01602479](https://filfox.info/en/address/f01602479)       |              Longueuil, Quebec, CA |           8.00 GiB |      0.00% |    8.00 GiB |           0.00% |
| [f01641612](https://filfox.info/en/address/f01641612)       |               Montréal, Quebec, CA |           8.00 GiB |      0.00% |    8.00 GiB |           0.00% |
| [f01163272](https://filfox.info/en/address/f01163272)       |                Perm, Perm Krai, RU |           8.00 GiB |      0.00% |    8.00 GiB |           0.00% |
| [f01606675](https://filfox.info/en/address/f01606675)       |               Montréal, Quebec, CA |          16.00 MiB |      0.00% |   16.00 MiB |           0.00% |

![Provider Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/309/1671094811021.png)
### Deal Data Replication
The below table shows how each many unique data are replicated across storage providers.
- No more than 25% of unique data are stored with less than 4 providers.

✔️ Data replication looks healthy.

| Unique Data Size | Total Deals Made | Number of Providers | Deal Percentage |
| ---------------: | ---------------: | ------------------: | --------------: |
|         3.59 TiB |         4.07 TiB |                   1 |           0.09% |
|        23.74 TiB |        47.70 TiB |                   2 |           1.11% |
|       107.70 TiB |       323.29 TiB |                   3 |           7.51% |
|       293.13 TiB |         1.15 PiB |                   4 |          27.24% |
|       551.38 TiB |         2.69 PiB |                   5 |          64.05% |

![Replication Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/309/1671094811629.png)
### Deal Data Shared with other Clients
The below table shows how many unique data are shared with other clients.
Usually different applications owns different data and should not resolve to the same CID.

✔️ No CID sharing has been observed.

[^1]: To manually trigger this report, add a comment with text `checker:manualTrigger`
