### ISSUE TITLE
[DataCap Application]ZhongHe Survey and Design Co., Ltd.

### ISSUE THREAD

**Issue by zhonghdadi** [filecoin-project/filecoin-plus-large-datasets#310]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: ZhongHe Survey and Design Co., Ltd.
- Website / Social Media: http://www.dadikancha.cn/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100TiB
- On-chain address for first allocation: f12ima4tjej3yqvbnu7hizyobfrrkq574v7ojytay

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Founded in 2007, ZhongHe Survey and Design Co., Ltd. is located in Hepingli, Dongcheng District, Beijing. It is committed to mineral resource exploration, landscaping services, water pollution control, research and development and production of intelligent and cost-effective IoT environmental monitoring products. A high-tech enterprise with Internet + intelligent hardware technology innovation as the core. Since its establishment, the company has always been committed to the large-scale application of environmental Internet of Things, agricultural intelligent hardware research and development and agricultural big data analysis, providing technical and data support services for scientific planting, food safety traceability, and agricultural brand building. The company consistently implements the international quality management system, and has obtained the national industrial production license, technology "little giant" enterprise certification, remote wireless acquisition and control system, tubular soil moisture sensor data acquisition system, automatic water and fertilizer irrigation control integrated machine software, full Automatic intelligent irrigation control system, intelligent agricultural Internet of Things service platform system, integrated dust monitoring system, integrated automatic weather station monitoring system, automatic weather station data monitoring system and other software copyrights.
```

What is the primary source of funding for this project?
```
From our corporate shareholders.
```

What other projects/ecosystem stakeholders is this project associated with?
```
No.
```

## Use-case details

Describe the data being stored onto Filecoin
```
It mainly stores water pollution detection data and large-scale environmental IOT production data, such as tubular soil moisture sensor data, dust monitoring, weather station monitoring data, etc.
```

Where was the data in this dataset sourced from?
```
It is derived from water pollution detection data and data generated by the large-scale application of environmental Internet of Things, data collected by tubular soil moisture sensors, dust monitoring data in the air from dust monitoring equipment, and meteorological data generated by weather station monitoring equipment.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://ddkc-01.oss-cn-beijing.aliyuncs.com/beijing/pm2.5/beijing_pm25_20121009-20121221.zip
https://ddkc-01.oss-cn-beijing.aliyuncs.com/beijing/air/beijing_20210101-20211231.zip
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes, it is a public data. 
We are working on a website where we will publish the CID of the data to be stored. 
The public will be able to view the data through this website.
```

What is the expected retrieval frequency for this data?
```
This type of data is not as attractive to the general public as entertainment content, and We want people or organizations concerned about environmental monitoring to see our data.So the search frequency is not expected to be as high as that of video sites.This is the reason for we choosing the Filecoin network for storage.We want to retain the data over a longer period of time and provide it to those who need it when they need it.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
I think it's a permanent archival, and we'll constantly update our data stored on Filecoin.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Republic of North American, Asia
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
It is possible online and offline if you are a North American or Asia storage provider.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
And storage providers who are willing to make deals with us are welcome.
```

How will you be distributing deals across storage providers?
```
We have specific platform to transfer the data. And there is an offline data transfer process.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Sure, we have. 
```

**Comment by zhonghdadi** [comment]
@galen-mcandrew @dkkapur @Kevin-FF-USA  Hello,I've seen a lot of applications from others and I for the May 3rd meeting go through, how is my application going? Do I need to provide more information?

**Comment by IreneYoung** [comment]
Hi @zhonghdadi, please answer the following questions:
1.How many team members do you have in your R&D or core team? And how long have the team core members been engaged in development? Could you provide several Github accounts or email addresses of them?
2.How many datacap did you get before?
3.How many miners you intend to store data in?

**Comment by zhonghdadi** [comment]
Hi, @IreneYoung , thank you for your reply:

1. We have been researching into IPFS since 2 years ago.Always wanted to get involved in the project.We have 6 core members, two of the core technology of github account: https://github.com/jomozz;https://github.com/EverythingIsNothing
2. This is the first time for us to apply for datacap. Since 2007, we have had about 3P data, and more data will be stored continuously.
3.  We will deliver them to at least 20 storage providers for storage, which can be checked publicly by then.

**Comment by IreneYoung** [comment]
OK @zhonghdadi, I'll support it later.

**Comment by zhonghdadi** [comment]
@IreneYoung Thanks for your support.

**Comment by xingjitansuo** [comment]
Thanks for your application and reach out. I have the following question and hope you can answer. 
After browsing the website, I feel like the company you stand for provides different IoT devices and analysis tooling to clients in multiple areas. Have you confirmed with your client that those data are stored publicly and should support retrieval by anyone ?

**Comment by zhonghdadi** [comment]
@xingjitansuo Thanks for your reply. Customer data we will have to get their approval, but that's only part of it. The data we want to store on Filcoin is mainly our own research data, which is used for the detection and replacement of our own technology and equipment, such as research data related to meteorology, engineering, fish ponds, tea gardens, noise, etc., including files, pictures, videos, etc. The vast amount of data generated each year is fully publicly available and searchable by anyone.

**Comment by Sunnyiscoming** [comment]
@zhonghdadi  The sample data is in a table with a small amount of data. The datacap requested is 5PB. Please describe the structure of these data and provide corresponding data samples.

**Comment by zhonghdadi** [comment]
@Sunnyiscoming  We have a large amount of water quality monitoring data, air monitoring data, soil monitoring data, etc. The data formats include videos, pictures, documents, and more data samples, you can click to view [this link](https://pan.baidu.com/s/1GUolJeA9ZQjrm4X3m-6SIA ) and password:94p2.

**Comment by xingjitansuo** [comment]
@zhonghdadi 
Looks good to me.. I am happy to support.

**Comment by zhonghdadi** [comment]
@xingjitansuo Thanks for your support.

**Comment by vetetable360** [comment]
Hi @dkkapur @Kevin-FF-USA @galen-mcandrew , how is my application going? Do I need to provide more information?

**Comment by Yvette516** [comment]
![da8da137-3176-49d5-8a60-2a3a476222ae](https://user-images.githubusercontent.com/106008819/173767479-adf55f87-1614-407d-b975-d34f2a6cd53d.jpg)
I have found that your company's information is related to the nuclear industry. The National Security Law strictly prohibits the  data  transmission.

**Comment by zhonghdadi** [comment]
Hi @Yvette516 , Our company is a private enterprise. Although the major shareholder shows that it is the nuclear industry, our company is only a private enterprise affiliated with the Geological Bureau and operates private business.

**Comment by woshidama323** [comment]
But Worry about ome sensitive data about location, building, etc sampling from IOT devices would be collected and committed to FILCOIN network?

**Comment by zhonghdadi** [comment]
Thank you for your interest in data security@Yvette516 @woshidama323 
 I would like to add: 
1. We will strictly abide by the national data security law and regulations, and transfer publicable data under this principle. 
2. We will desensitize the locations and names mentioned by @woshidama323 .We will definitely not upload the private information of customers to Filcoin. 
3. The main reason for filcoin to store data is that, on the one hand, we have some valuable historical data to preserve, and on the other hand, we want to experience the decentralized storage in the Web3 era. It is impossible for us to violate national laws and regulations because of this. 
thank you!

**Comment by dkkapur** [comment]
@zhonghdadi can you email [filplus@fil.org](mailto:filplus@fil.org) with your official work email so we can share this with notaries as a form of proof that you represent this organization?

**Comment by zhonghdadi** [comment]
Thank you for your reply @dkkapur . The email has been sent. Please check.

**Comment by zhonghdadi** [comment]
Hello @dkkapur ,have you received our email? Is there anything else we need to do?

**Comment by galen-mcandrew** [comment]
Received the email and business license. Notaries may want to request a copy of the license as well to perform their diligence.
<img width="993" alt="Screen Shot 2022-06-29 at 6 51 26 PM" src="https://user-images.githubusercontent.com/85587348/176575669-69ea4ff7-3410-44b4-bf0e-a951deb0f271.png">

**Comment by galen-mcandrew** [comment]
## Datacap Request Trigger
#### Total DataCap requested 
> 5PiB
#### Expected weekly DataCap usage rate 
> 100TiB 
#### Client address
> f12ima4tjej3yqvbnu7hizyobfrrkq574v7ojytay

**Comment by zhonghdadi** [comment]
Thank you very much for your approval @galen-mcandrew 
Could you sign it for us？ @IreneYoung @xingjitansuo  thank you！

**Comment by xingjitansuo** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedldotpvux5dkjdedgs4nzubdh7tv7xl4d6sn7yzc7cjmiomkrpb2 
#### Address 
> f12ima4tjej3yqvbnu7hizyobfrrkq574v7ojytay
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1a2lia2cwwekeubwo4nppt4v4vebxs2frozarz3q
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedldotpvux5dkjdedgs4nzubdh7tv7xl4d6sn7yzc7cjmiomkrpb2

**Comment by kevzak** [comment]
Hello @zhonghdadi - I'm Kevin from the Client Success Team. I saw you were recently granted DataCap and began onboarding data. I wanted to reach out as you getting started to offer any support as needed. Let me know if you have any questions or issues.

Also, feel free to post a message in #fil-plus slack channel. Thank you!

**Comment by zhonghdadi** [comment]
Hi,  @kevzak sorry for the late reply, thank you for your attention to us!
So far, our progress is very smooth, SP has been found, it is expected that everyone will wrap up this batch of data within 10 days. If there are any questions, we'll leave them on Slack. Thanks again

**Comment by newwebgroup** [comment]
Hi @zhonghdadi 
I have observed that you have already started to encapsulate.
Just a reminder, please try to make the data more dispersed.
<img width="1605" alt="image" src="https://user-images.githubusercontent.com/100118145/183331073-ca7f8121-1d35-4048-8abf-2ffaff015707.png">

**Comment by zhonghdadi** [comment]
Thanks for the reminder @newwebgroup , we will allocate the datacap strictly according to the rules. And some deals are under sealing.
<img width="1352" alt="image" src="https://user-images.githubusercontent.com/102300446/184273647-08e02341-7a6c-4691-8812-c2697b0512a1.png">

**Comment by fireflyHZ** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb3rmdudrvp6liqjiuuqdgufq4axexlikahzbf3rcljxvkulptdfs 
#### Address 
> f12ima4tjej3yqvbnu7hizyobfrrkq574v7ojytay
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1fg6jkxsr3twfnyhdlatmq36xca6sshptscds7xa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb3rmdudrvp6liqjiuuqdgufq4axexlikahzbf3rcljxvkulptdfs

**Comment by psh0691** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceba36xe7njhjtegztvhewevhs5vuzndblio6gglo35dcofuyj6lrs 
#### Address 
> f12ima4tjej3yqvbnu7hizyobfrrkq574v7ojytay
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1qdko4jg25vo35qmyvcrw4ak4fmuu3f5rif2kc7i
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceba36xe7njhjtegztvhewevhs5vuzndblio6gglo35dcofuyj6lrs

**Comment by zhonghdadi** [comment]
@galen-mcandrew Hi galen, today, the second notary helped us approve the second Datacap Allocation Request, but the datacap in my address did not increase, and the robot opened the third DataCap Allocation request. Is there a bug?
<img width="648" alt="image" src="https://user-images.githubusercontent.com/102300446/186928074-662a4842-fcff-4d30-9612-d1f964ab008d.png">

**Comment by BigD-Exchange** [comment]
@zhonghdadi Hi! Great to see you have gotten approval for DataCap. If you are looking for storage providers to store these data or have any questions, please visit #bigdata-exchange on Filecoin Slack or reply here. 

We have strong demand from a diverse group of SPs, who are actively looking to onboard more data.

**Comment by newwebgroup** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedfdfpzaacc7l3a6l6enacucjg6jvt6zazhrtxkg7jdgiaf4fzz5a 
#### Address 
> f12ima4tjej3yqvbnu7hizyobfrrkq574v7ojytay
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1e77zuityhvvw6u2t6tb5qlnsegy2s67qs4lbbbq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedfdfpzaacc7l3a6l6enacucjg6jvt6zazhrtxkg7jdgiaf4fzz5a

**Comment by fireflyHZ** [comment]
This LDN shuold be Request number 2 , But looks like did not receive DC of Request number 2. Now it come to Request number 3.  It's weird！

**Comment by psh0691** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedor22dhiunj2b7nywfjdi7ziwroojagi5gudd7rf6wzyuzpgsjfm 
#### Address 
> f12ima4tjej3yqvbnu7hizyobfrrkq574v7ojytay
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1qdko4jg25vo35qmyvcrw4ak4fmuu3f5rif2kc7i
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedor22dhiunj2b7nywfjdi7ziwroojagi5gudd7rf6wzyuzpgsjfm

**Comment by newwebgroup** [comment]
It seems that there is something wrong with the system
CC @dkkapur @Kevin-FF-USA

**Comment by kernelogic** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedldlf3trc74ij4ifboellpvtn26phnkecu5t4dmi2u2faafudkxq 
#### Address 
> f12ima4tjej3yqvbnu7hizyobfrrkq574v7ojytay
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedldlf3trc74ij4ifboellpvtn26phnkecu5t4dmi2u2faafudkxq

**Comment by xiaoyuaiheshui** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedjxlogvyfz6ohdjrsvrwcb7ofeeumjf4hpwjk2u7txv55ksavgde 
#### Address 
> f12ima4tjej3yqvbnu7hizyobfrrkq574v7ojytay
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f122qmy25wdtt5mxd77kndiq7z5x2n3iwiuz2wdsa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedjxlogvyfz6ohdjrsvrwcb7ofeeumjf4hpwjk2u7txv55ksavgde

**Comment by newwebgroup** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebnotweiwudg7cjnxwisonpo666rixs3fnfgiqizac3prdxefosce 
#### Address 
> f12ima4tjej3yqvbnu7hizyobfrrkq574v7ojytay
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1e77zuityhvvw6u2t6tb5qlnsegy2s67qs4lbbbq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebnotweiwudg7cjnxwisonpo666rixs3fnfgiqizac3prdxefosce

**Comment by Tom-OriginStorage** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced6odwbm2ja4h7e4jigo4ok6x5yyyfcoam6if6lohiijdykhmp5h2 
#### Address 
> f12ima4tjej3yqvbnu7hizyobfrrkq574v7ojytay
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1q6bpjlqia6iemqbrdaxr2uehrhpvoju3qh4lpga
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced6odwbm2ja4h7e4jigo4ok6x5yyyfcoam6if6lohiijdykhmp5h2

**Comment by fireflyHZ** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaunc22e5ebgmob4jwrkny7d6enlaggegh2bve3pxkcpclzbkdapy 
#### Address 
> f12ima4tjej3yqvbnu7hizyobfrrkq574v7ojytay
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1fg6jkxsr3twfnyhdlatmq36xca6sshptscds7xa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaunc22e5ebgmob4jwrkny7d6enlaggegh2bve3pxkcpclzbkdapy

**Comment by Joss-Hua** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedb43trczy7ny7r7zasd4mcocrwl6bgmptetnppujpodfkm75xta6 
#### Address 
> f12ima4tjej3yqvbnu7hizyobfrrkq574v7ojytay
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1tfg54zzscugttejv336vivknmsnzzmyudp3t7wi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedb43trczy7ny7r7zasd4mcocrwl6bgmptetnppujpodfkm75xta6

**Comment by stcouldlisa** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacea6a3zzeg4g4xr5czlaxekbxkffbpr5onebt6aqib6yso7zthoia4 
#### Address 
> f12ima4tjej3yqvbnu7hizyobfrrkq574v7ojytay
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1jvvltduw35u6inn5tr4nfualyd42bh3vjtylgci
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacea6a3zzeg4g4xr5czlaxekbxkffbpr5onebt6aqib6yso7zthoia4

**Comment by Tom-OriginStorage** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedauzq2rqizqymt2zili7midrseuzklgnjdatypevkxdfvehdqhcq 
#### Address 
> f12ima4tjej3yqvbnu7hizyobfrrkq574v7ojytay
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1q6bpjlqia6iemqbrdaxr2uehrhpvoju3qh4lpga
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedauzq2rqizqymt2zili7midrseuzklgnjdatypevkxdfvehdqhcq

**Comment by liyunzhi-666** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedbdxr2ewhf44i4k56p3mj65gebihvuhrp4ywqdn2rfjtz32pw6sw 
#### Address 
> f12ima4tjej3yqvbnu7hizyobfrrkq574v7ojytay
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1pszcrsciyixyuxxukkvtazcokexbn54amf7gvoq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedbdxr2ewhf44i4k56p3mj65gebihvuhrp4ywqdn2rfjtz32pw6sw

**Comment by fireflyHZ** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedz2czvuwr7duojtq3epvpmbay6xkdzjgz6nxxpxi36rhc7hmieu2 
#### Address 
> f12ima4tjej3yqvbnu7hizyobfrrkq574v7ojytay
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1fg6jkxsr3twfnyhdlatmq36xca6sshptscds7xa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedz2czvuwr7duojtq3epvpmbay6xkdzjgz6nxxpxi36rhc7hmieu2

**Comment by newwebgroup** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecfsef2jfxaq5clieytm7fuubwxfhqpa43uy4bvtg67uaazhkdwnc 
#### Address 
> f12ima4tjej3yqvbnu7hizyobfrrkq574v7ojytay
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1e77zuityhvvw6u2t6tb5qlnsegy2s67qs4lbbbq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecfsef2jfxaq5clieytm7fuubwxfhqpa43uy4bvtg67uaazhkdwnc

**Comment by Tom-OriginStorage** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecqsih23uxsqqze3flwzl3dbjbxtkdnk2bpzlxgrqvxpahpizccmk 
#### Address 
> f12ima4tjej3yqvbnu7hizyobfrrkq574v7ojytay
#### Datacap Allocated
> 370.00TiB
#### Signer Address
> f1q6bpjlqia6iemqbrdaxr2uehrhpvoju3qh4lpga
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecqsih23uxsqqze3flwzl3dbjbxtkdnk2bpzlxgrqvxpahpizccmk

**Comment by newwebgroup** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecbxjqtpunzrf3v6fgmq4gmmyyabxqna3r2ndwzkquzumc5c4d7hy 
#### Address 
> f12ima4tjej3yqvbnu7hizyobfrrkq574v7ojytay
#### Datacap Allocated
> 370.00TiB
#### Signer Address
> f1e77zuityhvvw6u2t6tb5qlnsegy2s67qs4lbbbq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecbxjqtpunzrf3v6fgmq4gmmyyabxqna3r2ndwzkquzumc5c4d7hy

**Comment by zhonghdadi** [comment]
Hi @dkkapur  my datacap still has 100T left, why doesn't the bot allocate it to me?

**Comment by filplus-checker** [comment]
## DataCap and CID Checker Report[^1]
 - Organization: `ZhongHe Survey and Design Co., Ltd.`
 - Client: `f12ima4tjej3yqvbnu7hizyobfrrkq574v7ojytay`
### Storage Provider Distribution
The below table shows the distribution of storage providers that have stored data for this client.

If this is the first time a provider takes verified deal, it will be marked as `new`.

For most of the datacap application, below restrictions should apply.
 - Storage provider should not exceed 25% of total datacap.
 - Storage provider should not be storing duplicate data for more than 20%.
 - Storage provider should have published its public IP address.
 - All storage providers should be located in different regions.

✔️ Storage provider distribution looks healthy.

| Provider                                                    |                           Location | Total Deals Sealed | Percentage | Unique Data | Duplicate Deals |
| :---------------------------------------------------------- | ---------------------------------: | -----------------: | ---------: | ----------: | --------------: |
| [f01938665](https://filfox.info/en/address/f01938665)`new`  |     Sham Shui Po, Sham Shui Po, HK |         792.47 TiB |     15.79% |  786.00 TiB |           0.82% |
| [f01938714](https://filfox.info/en/address/f01938714)`new`  |     Sham Shui Po, Sham Shui Po, HK |         739.78 TiB |     14.74% |  737.47 TiB |           0.31% |
| [f01938717](https://filfox.info/en/address/f01938717)`new`  |           Singapore, Singapore, SG |         642.00 TiB |     12.79% |  639.34 TiB |           0.41% |
| [f01938718](https://filfox.info/en/address/f01938718)`new`  |    Morrisville, North Carolina, US |         558.00 TiB |     11.12% |  558.00 TiB |           0.00% |
| [f01938721](https://filfox.info/en/address/f01938721)`new`  | Hong Kong, Central and Western, HK |         498.03 TiB |      9.92% |  498.03 TiB |           0.00% |
| [f01852023](https://filfox.info/en/address/f01852023)       |                   Busan, Busan, KR |         431.25 TiB |      8.59% |  431.25 TiB |           0.00% |
| [f01852325](https://filfox.info/en/address/f01852325)       | Hong Kong, Central and Western, HK |         368.53 TiB |      7.34% |  368.53 TiB |           0.00% |
| [f01851482](https://filfox.info/en/address/f01851482)       |                   Busan, Busan, KR |         343.78 TiB |      6.85% |  343.78 TiB |           0.00% |
| [f01852677](https://filfox.info/en/address/f01852677)       |    Morrisville, North Carolina, US |         326.41 TiB |      6.50% |  326.41 TiB |           0.00% |
| [f01852664](https://filfox.info/en/address/f01852664)       |           Singapore, Singapore, SG |         270.28 TiB |      5.38% |  270.28 TiB |           0.00% |
| [f0240185](https://filfox.info/en/address/f0240185)         |            Clifton, New Jersey, US |           9.81 TiB |      0.20% |    9.81 TiB |           0.00% |
| [f0143858](https://filfox.info/en/address/f0143858)         |            Clifton, New Jersey, US |           9.81 TiB |      0.20% |    9.81 TiB |           0.00% |
| [f03223](https://filfox.info/en/address/f03223)             |           San Jose, California, US |           9.72 TiB |      0.19% |    9.72 TiB |           0.00% |
| [f01193812](https://filfox.info/en/address/f01193812)       |               Boardman, Oregon, US |           9.22 TiB |      0.18% |    9.22 TiB |           0.00% |
| [f0674600](https://filfox.info/en/address/f0674600)         |        Los Angeles, California, US |           5.92 TiB |      0.12% |    5.80 TiB |           2.11% |
| [f02301](https://filfox.info/en/address/f02301)             |           San Jose, California, US |           4.94 TiB |      0.10% |    4.94 TiB |           0.00% |

![Provider Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/310/1671094836159.png)
### Deal Data Replication
The below table shows how each many unique data are replicated across storage providers.
- No more than 25% of unique data are stored with less than 4 providers.

✔️ Data replication looks healthy.

| Unique Data Size | Total Deals Made | Number of Providers | Deal Percentage |
| ---------------: | ---------------: | ------------------: | --------------: |
|        55.95 TiB |        56.08 TiB |                   1 |           1.12% |
|        22.22 TiB |        44.44 TiB |                   2 |           0.89% |
|        18.72 TiB |        57.00 TiB |                   3 |           1.14% |
|       147.69 TiB |       595.44 TiB |                   4 |          11.86% |
|       852.22 TiB |         4.17 PiB |                   5 |          85.00% |

![Replication Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/310/1671094836793.png)
### Deal Data Shared with other Clients
The below table shows how many unique data are shared with other clients.
Usually different applications owns different data and should not resolve to the same CID.

⚠️ CID sharing has been observed.

| Other Client                                                                                                          | Application                                                                                                               | Total Deals Affected | Unique CIDs |         Verifier |
| :-------------------------------------------------------------------------------------------------------------------- | :------------------------------------------------------------------------------------------------------------------------ | -------------------: | ----------: | ---------------: |
| [f1wyxv3ysg3xpgmzlpuhkfqykm6wfhohdg4ordnmq](https://filfox.info/en/address/f1wyxv3ysg3xpgmzlpuhkfqykm6wfhohdg4ordnmq) | [Shenzhen Jubao Time Technology Co\., Ltd\.](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/541) |           196.75 TiB |       2,121 |  LDN v3 multisig |
| [f14z37zddplbkmmkvm3jrdldkxji5a5r6iux4dhfi](https://filfox.info/en/address/f14z37zddplbkmmkvm3jrdldkxji5a5r6iux4dhfi) | `  Common primitive universe`                                                                                             |            39.45 TiB |         186 |  LDN v3 multisig |
| [f1dbpdc56q6wfcmb4p2ppzqruufiqcr2s5xqwybma](https://filfox.info/en/address/f1dbpdc56q6wfcmb4p2ppzqruufiqcr2s5xqwybma) | ``                                                                                                                        |             2.58 TiB |          83 | Philipp Banhardt |
| [f17subptxqumxfdt27r64amsvkehh5bwxtd2aethi](https://filfox.info/en/address/f17subptxqumxfdt27r64amsvkehh5bwxtd2aethi) | [wujia](https://github.com/filecoin-project/filecoin-plus-client-onboarding/issues/2487)                                  |             1.89 TiB |          61 |         embedsky |

[^1]: To manually trigger this report, add a comment with text `checker:manualTrigger`

**Comment by cryptowhizzard** [comment]
#1214 

CID sharing / fraudulent data.
