### ISSUE TITLE
[DataCap Application] FILDATA Co., Ltd.

### ISSUE THREAD

**Issue by fildata** [filecoin-project/filecoin-plus-large-datasets#311]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: FILDATA Co., Ltd.
- Website / Social Media: https://theskyzone.net/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100TiB
- On-chain address for first allocation: f3vvab3qun5ye6w7ut2vow7o3r4uap3qmt3xz3eib2cp7j3chfb2v3auu4p3w5h62pjqj7dkta3xs5vaky4goa

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Organization : FILDATA Co., Ltd.
• FILDATA is a corporation that develops IT services in Korea and provides services to customers.
• FILDATA established and operates the company in 2020 and directly operates and manages its own storage data center. And based on this, we provide services to our customers.

Project : theskyzone.net
• We are providing our customers with a cloud storage service.
• Our customers are using the service for work, personal work, and backup purposes.
• Cloud storage service provides services through various channels based on web browsers, folder synchronization of Windows and Mac PCs, and iOS and Android apps.

• theskyzone.net service demo
  You can use the service demo through the information below.
  URL : https://theskyzone.net
  Demo ID : demo
  Demo Password : demo17291729*
```

What is the primary source of funding for this project?
```
Company shareholders and technology partners.
```

What other projects/ecosystem stakeholders is this project associated with?
```
None.
```

## Use-case details

Describe the data being stored onto Filecoin
```
We have plans to store the material stored by users on theskyzone.net in Filecoin for the short or long term at the request of users.
In addition, we plan to use Filecoin to periodically back-up the entire data of theskyzone.net project.
```

Where was the data in this dataset sourced from?
```
• The source of the dataset is the material stored by the user on theskyzone.net.
• Users mainly use theskyzone.net for video editing, design work, photography work, and publishing work, etc.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://theskyzone.net/index.php/s/x73jT6BP3PnwEgf
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes.
```

What is the expected retrieval frequency for this data?
```
Data retrieval is required in the following cases.
• When a user requests restoration of data stored in Filecoin
• When it is necessary to restore the entire data of theskyzone.net project
Therefore, the frequency of data retrieval may occur irregularly.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
The data stored in Filecoin will be stored according to the following standards.
• When a user requests storage in Filecoin, the user directly decides how long the data will be kept in Filecoin, and accordingly, the data will be kept in Filecoin for as long as the user requested.
• When storing data in Filecoin to periodically back-up the entire data of theskyzone.net project, we plan to keep each backup dataset for 3 years.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Korea, Japan
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
We use online transfer by default. However, in special cases with large data capacity, data can be sent offline through a hard disk or SSD.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
• We plan to choose a storage provider considering reputation, reliability, and price due to the importance of data storage.
• And considering the case of large data storage, it is also planning to select a storage provider that offers offline data transfer processes.
```

How will you be distributing deals across storage providers?
```
• We plan to store data distributed across 3 or more storage providers.
• And we plan to distribute our allocated Datacap to each storage provider so that no more than 25% is allocated.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, we will find and add better storage providers as soon as we receive DataCap, and we have the resources and funds ready to start making deals.
```

**Comment by Sunnyiscoming** [comment]
@fildata The site provided is a business platform website. Is there any website or social media account about the organization?

**Comment by Sunnyiscoming** [comment]
Any update?

**Comment by fildata** [comment]
> @fildata The site provided is a business platform website. Is there any website or social media account about the organization?

Hello.
We check the question late and answer it now.

Our company website is below.
http://fildata.co.kr

If you have any additional questions or requests, please ask us.
We appreciate your feedback.

**Comment by Sunnyiscoming** [comment]
http://fildata.co.kr/ do not work. Please check it.

**Comment by fildata** [comment]
> http://fildata.co.kr/ do not work. Please check it.

@Sunnyiscoming 
We read and checked what you sent.
We have confirmed that there is a problem in accessing our web server.
We have fixed the current web server connection problem.

http://fildata.co.kr/
Please check the website again.

**Comment by Sunnyiscoming** [comment]
@fildata  Hey. Could you send an email of your organization existence certificant to filplus@fil.org with your official domain in order to confirm your identity?

**Comment by galen-mcandrew** [comment]
## Datacap Request Trigger
#### Total DataCap requested 
> 5PiB
#### Expected weekly DataCap usage rate 
> 100TiB 
#### Client address
> f3vvab3qun5ye6w7ut2vow7o3r4uap3qmt3xz3eib2cp7j3chfb2v3auu4p3w5h62pjqj7dkta3xs5vaky4goa

**Comment by fildata** [comment]
@psh0691 
1. You applied for LDN of 5PiB,

* How many users of 'skyzone'?
“→ Skyzone service has recently started and is operating as an open beta-service. 
      There are 35 accounts of the Skyzone service. 
      Skyzone accounts can be divided into corporate user accounts and personal user accounts. 
      A corporate user account can actually be accessed and used by multiple users at the same time.“
* How much data have you collected now?
“→ The data collected for the Skyzone service is 27 TiB“
* Can you disclose the evidence of the above?
“→ We may disclose data, except for personal information in service accounts.“

2. As a 'FILDATA' storage provider,

* Are you operating a filecoin node?
“→ We are running a Filecoin node.“
* If so, can you disclose the nodes?
“→ We are running 3 Filecoin nodes and plan to add more nodes later. 
The nodes we are operating on are as follows. 
https://filfox.info/en/address/f01115949 
https://filfox.info/en/address/f01768757 
https://filfox.info/en/address/f01770778“

3. Are you working with other storage providers? If so, can you disclose your partner?
“→ We are not working with other storage providers.“

**Comment by psh0691** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb6pkoefzteh7p4omlwlxt5atatwbvs4i663sa5rtpcgnxvya6cew 
#### Address 
> f3vvab3qun5ye6w7ut2vow7o3r4uap3qmt3xz3eib2cp7j3chfb2v3auu4p3w5h62pjqj7dkta3xs5vaky4goa
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1qdko4jg25vo35qmyvcrw4ak4fmuu3f5rif2kc7i
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb6pkoefzteh7p4omlwlxt5atatwbvs4i663sa5rtpcgnxvya6cew

**Comment by fildata** [comment]
To @psh0691 @galen-mcandrew @Sunnyiscoming @rayshitou @dannyob @TimWilliams00 @ozhtdong @Fenbushi-Filecoin @swatchliu @MRJAVAZHAO @KodaRobotDog @XnMatrixSV @KodaRobotDog @flyworker @IPFSUnion 

Hi, please help me to approve next round of Datacap. Thanks!

**Comment by cryptowhizzard** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebkluqaar2c6uoiurh2z3ulierbb4bvdbsbvm6ymu5qgxapv5nygo 
#### Address 
> f3vvab3qun5ye6w7ut2vow7o3r4uap3qmt3xz3eib2cp7j3chfb2v3auu4p3w5h62pjqj7dkta3xs5vaky4goa
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1krmypm4uoxxf3g7okrwtrahlmpcph3y7rbqqgfa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebkluqaar2c6uoiurh2z3ulierbb4bvdbsbvm6ymu5qgxapv5nygo

**Comment by BigD-Exchange** [comment]
@fildata Hi! Great to see you have gotten approval for DataCap. If you are looking for storage providers to store these data, please visit #bigdata-exchange on Filecoin Slack or reply here.

**Comment by hyunmoon** [comment]
> @fildata Hi! Great to see you have gotten approval for DataCap. If you are looking for storage providers to store these data, please visit #bigdata-exchange on Filecoin Slack or reply here.

Nope. Not a chance cuz they claiemd that they're gonna give it all to themselves.

@psh0691 
I happened to get this message from someone I know and I couldn't look the other way because their intension seemd very clear which is a SP getting datacap for self dealing (or to an associated SP).
As a Korean speaker, I'm sure you'll understand what their intension has been.
I'd recommend you to watch how they spend their datacap.

-------------------------------
📌 파이온 소식 전합니다 :)

드디어 회사에서 몇달간 수고한 보람의 결실로 "5페타" 대용량 데이터캡 승인이 완료되어, 그 첫번째로 50테라 실링 배정받았습니다 !

회사가 받은 5페타를 데이터캡으로 실링하면 "50페타" 의 용량으로 인정을 받습니다.
이제부터 5패타 만큼은 계속 실링할수 있게 되었습니다 (담보금은 50패타의 비용이 들어가겠지요)

정말 오랜시간이 걸렸고 어려운 결과를 얻어 냈습니다
모두 축하 하는 마음으로 기대 하셔도 좋을듯 합니다!

https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/311#issuecomment-1206467100
----------------------------------
![image](https://user-images.githubusercontent.com/2242149/183345640-a996af52-3df8-43a0-a3fb-ebea7e111de9.jpeg)

**Comment by psh0691** [comment]
The File Plus DataCap is not a self-dealing project.
The same client and SP can be disputed, and notaries who approve the DataCap are also liable.
Based on the above information, we've done some research
Both accounts are self-accounts that have already been disclosed.
There seems to be a need for clarification and action.
![스크린샷, 2022-08-17 09-36-41](https://user-images.githubusercontent.com/69004801/185009144-04ea88b2-0113-4e3f-8077-29bfd0b56193.png)

**Comment by cryptowhizzard** [comment]
Ok, if this is a self dealing project it might be better to have the team close it to prevent it pops up in our dashboards to sign. That way mistakes are prevented.

**Comment by psh0691** [comment]
SP doesn't mean you can't be a client. Any data owner can apply for a data cap. However, there is a possibility of dispute if you applied only for your own trading purposes

**Comment by psh0691** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecqfjgnt2r3kwq6af3gdlkwvs3pguoh6rhfmjdrthrp65g5ju7vcs 
#### Address 
> f3vvab3qun5ye6w7ut2vow7o3r4uap3qmt3xz3eib2cp7j3chfb2v3auu4p3w5h62pjqj7dkta3xs5vaky4goa
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1qdko4jg25vo35qmyvcrw4ak4fmuu3f5rif2kc7i
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecqfjgnt2r3kwq6af3gdlkwvs3pguoh6rhfmjdrthrp65g5ju7vcs

**Comment by Reiers** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceapgyhoipv6sfir65qjps4xuwvl5ffz6zrt5bgwpu7olxmkrculyg 
#### Address 
> f3vvab3qun5ye6w7ut2vow7o3r4uap3qmt3xz3eib2cp7j3chfb2v3auu4p3w5h62pjqj7dkta3xs5vaky4goa
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1oz43ckvmtxmmsfzqm6bpnemqlavz4ifyl524chq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceapgyhoipv6sfir65qjps4xuwvl5ffz6zrt5bgwpu7olxmkrculyg

**Comment by GaryGJG** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebffuae37n34twk6u43gp44rywqdavw2henixjkvie2qu266uqtd2 
#### Address 
> f3vvab3qun5ye6w7ut2vow7o3r4uap3qmt3xz3eib2cp7j3chfb2v3auu4p3w5h62pjqj7dkta3xs5vaky4goa
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1zffqhxwq2rrg7rtot6lmkl6hb2xyrrseawprzsq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebffuae37n34twk6u43gp44rywqdavw2henixjkvie2qu266uqtd2

**Comment by liyunzhi-666** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec4wk7ium32gb5flemt5dzys35kibinsb7t5bgxvvuifjpki77sw4 
#### Address 
> f3vvab3qun5ye6w7ut2vow7o3r4uap3qmt3xz3eib2cp7j3chfb2v3auu4p3w5h62pjqj7dkta3xs5vaky4goa
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1pszcrsciyixyuxxukkvtazcokexbn54amf7gvoq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec4wk7ium32gb5flemt5dzys35kibinsb7t5bgxvvuifjpki77sw4

**Comment by psh0691** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebvdv7v7ppahvohr2rqdpsmiawrrtkhkpfjvp2kqimtdm4y4bozxm 
#### Address 
> f3vvab3qun5ye6w7ut2vow7o3r4uap3qmt3xz3eib2cp7j3chfb2v3auu4p3w5h62pjqj7dkta3xs5vaky4goa
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1qdko4jg25vo35qmyvcrw4ak4fmuu3f5rif2kc7i
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebvdv7v7ppahvohr2rqdpsmiawrrtkhkpfjvp2kqimtdm4y4bozxm

**Comment by filplus-checker** [comment]
## DataCap and CID Checker Report[^1]
 - Organization: `FILDATA Co., Ltd.`
 - Client: `f3vvab3qun5ye6w7ut2vow7o3r4uap3qmt3xz3eib2cp7j3chfb2v3auu4p3w5h62pjqj7dkta3xs5vaky4goa`
### Storage Provider Distribution
The below table shows the distribution of storage providers that have stored data for this client.

If this is the first time a provider takes verified deal, it will be marked as `new`.

For most of the datacap application, below restrictions should apply.
 - Storage provider should not exceed 25% of total datacap.
 - Storage provider should not be storing duplicate data for more than 20%.
 - Storage provider should have published its public IP address.
 - All storage providers should be located in different regions.

⚠️ [f01924891](https://filfox.info/en/address/f01924891) has unknown IP location.

⚠️ [f01927163](https://filfox.info/en/address/f01927163) has unknown IP location.

⚠️ [f01900525](https://filfox.info/en/address/f01900525) has unknown IP location.

⚠️ [f01924824](https://filfox.info/en/address/f01924824) has unknown IP location.

⚠️ [f01770778](https://filfox.info/en/address/f01770778) has unknown IP location.

| Provider                                                    |         Location | Total Deals Sealed | Percentage | Unique Data | Duplicate Deals |
| :---------------------------------------------------------- | ---------------: | -----------------: | ---------: | ----------: | --------------: |
| [f01115949](https://filfox.info/en/address/f01115949)       | Seoul, Seoul, KR |          80.00 TiB |     22.87% |   79.97 TiB |           0.04% |
| [f01924891](https://filfox.info/en/address/f01924891)`new`  |          Unknown |          69.63 TiB |     19.91% |   69.63 TiB |           0.00% |
| [f01927163](https://filfox.info/en/address/f01927163)`new`  |          Unknown |          60.91 TiB |     17.41% |   60.91 TiB |           0.00% |
| [f01900525](https://filfox.info/en/address/f01900525)       |          Unknown |          48.69 TiB |     13.92% |   48.69 TiB |           0.00% |
| [f01924824](https://filfox.info/en/address/f01924824)`new`  |          Unknown |          47.88 TiB |     13.69% |   47.88 TiB |           0.00% |
| [f01770778](https://filfox.info/en/address/f01770778)       |          Unknown |          42.66 TiB |     12.20% |   42.66 TiB |           0.00% |

![Provider Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/311/1671094845426.png)
### Deal Data Replication
The below table shows how each many unique data are replicated across storage providers.
- No more than 25% of unique data are stored with less than 4 providers.

⚠️ 100.00% of deals are for data replicated across less than 4 storage providers.

| Unique Data Size | Total Deals Made | Number of Providers | Deal Percentage |
| ---------------: | ---------------: | ------------------: | --------------: |
|       349.72 TiB |       349.75 TiB |                   1 |         100.00% |

![Replication Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/311/1671094845950.png)
### Deal Data Shared with other Clients
The below table shows how many unique data are shared with other clients.
Usually different applications owns different data and should not resolve to the same CID.

✔️ No CID sharing has been observed.

[^1]: To manually trigger this report, add a comment with text `checker:manualTrigger`

**Comment by cryptowhizzard** [comment]
Hello,

I was looking at this application to approve it but It seems to me that only f01924891 is reachable. The guidelines of Fil+ state that the miners should be reachable.

Can you tell me how this works when you are working cloud storage without a reachable miner? How can anyone retrieve this data?

Can you tell me who are miners ->

f01924891new | Unknown | 69.63 TiB | 19.91% | 69.63 TiB | 0.00%
-- | -- | -- | -- | -- | --
f01927163new | Unknown | 60.91 TiB | 17.41% | 60.91 TiB | 0.00%
f01900525 | Unknown | 48.69 TiB | 13.92% | 48.69 TiB | 0.00%
f01924824new | Unknown | 47.88 TiB | 13.69% | 47.88 TiB | 0.00%
f01770778 | Unknown | 42.66 TiB | 12.20% | 42.66 TiB | 0.00%

**Comment by fildata** [comment]
checker:manualTrigger

**Comment by fildata** [comment]
checker:manualTrigger

**Comment by futuremaster777** [comment]
checker:manualTrigger

**Comment by futuremaster777** [comment]
checker:manualTrigger

**Comment by futuremaster777** [comment]
checker:manualTrigger

**Comment by futuremaster777** [comment]
checker:manualTrigger

**Comment by futuremaster777** [comment]
checker:manualTrigger

**Comment by futuremaster777** [comment]
checker:manualTrigger

**Comment by futuremaster777** [comment]
checker:manualTrigger

**Comment by futuremaster777** [comment]
checker:manualTrigger

**Comment by futuremaster777** [comment]
checker:manualTrigger

**Comment by futuremaster777** [comment]
checker:manualTrigger

**Comment by futuremaster777** [comment]
checker:manualTrigger

**Comment by futuremaster777** [comment]
checker:manualTrigger

**Comment by futuremaster777** [comment]
checker:manualTrigger

**Comment by futuremaster777** [comment]
checker:manualTrigger

**Comment by futuremaster777** [comment]
checker:manualTrigger

**Comment by futuremaster777** [comment]
checker:manualTrigger

**Comment by futuremaster777** [comment]
checker:manualTrigger

**Comment by futuremaster777** [comment]
checker:manualTrigger

**Comment by futuremaster777** [comment]
checker:manualTrigger

**Comment by futuremaster777** [comment]
checker:manualTrigger

**Comment by futuremaster777** [comment]
checker:manualTrigger

**Comment by futuremaster777** [comment]
checker:manualTrigger

**Comment by futuremaster777** [comment]
checker:manualTrigger

**Comment by futuremaster777** [comment]
checker:manualTrigger

**Comment by futuremaster777** [comment]
checker:manualTrigger

**Comment by futuremaster777** [comment]
checker:manualTrigger

**Comment by futuremaster777** [comment]
checker:manualTrigger

**Comment by futuremaster777** [comment]
checker:manualTrigger

**Comment by futuremaster777** [comment]
checker:manualTrigger

**Comment by futuremaster777** [comment]
checker:manualTrigger

**Comment by futuremaster777** [comment]
checker:manualTrigger

**Comment by futuremaster777** [comment]
checker:manualTrigger

**Comment by futuremaster777** [comment]
checker:manualTrigger

**Comment by futuremaster777** [comment]
checker:manualTrigger

**Comment by futuremaster777** [comment]
checker:manualTrigger

**Comment by futuremaster777** [comment]
checker:manualTrigger

**Comment by futuremaster777** [comment]
checker:manualTrigger

**Comment by futuremaster777** [comment]
checker:manualTrigger

**Comment by futuremaster777** [comment]
checker:manualTrigger

**Comment by futuremaster777** [comment]
checker:manualTrigger

**Comment by qhost3650001** [comment]
checker:manualTrigger

**Comment by futuremaster777** [comment]
checker:manualTrigger

**Comment by futuremaster777** [comment]
checker:manualTrigger

**Comment by MarvinHongX** [comment]
checker:manualTrigger

**Comment by Sunnyiscoming** [comment]
Hello, @fildata per the https://github.com/filecoin-project/notary-governance/issues/922 for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

This information will be reviewed by Fil+ Governance team to confirm validity and then the application will be allowed to move forward for additional notary review.

**Comment by MarvinHongX** [comment]
checker:manualTrigger

**Comment by MarvinHongX** [comment]
checker:manualTrigger

**Comment by futuremaster777** [comment]
checker:manualTrigger

**Comment by fildata** [comment]
> This application has not seen any responses in the last 10 days. This issue will be marked with Stale label and will be closed in 4 days. Comment if you want to keep this application open.
> 
> -- Commented by Stale Bot.

We are preparing to respond to the information below.

>Hello, [@fildata](https://github.com/fildata) per the [filecoin-project/notary-governance#922](https://github.com/filecoin->project/notary-governance/issues/922) for Open, Public Dataset applicants, please complete the following [Fil+ registration >form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact >information of the SP entities you are working with to store copies of the data.
>This information will be reviewed by Fil+ Governance team to confirm validity and then the application will be allowed to >move forward for additional notary review.

We want to keep this application open.

**Comment by herrehesse** [comment]
![Screenshot 2023-11-14 at 09 45 17](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/70132857/9f5a168a-3c13-4522-8ecc-e61aae04f75e)

Fully self dealing close this LDN @kevzak

**Comment by futuremaster777** [comment]
checker:manualTrigger

**Comment by Sunnyiscoming** [comment]
> Author

Any update here? Have you submit the form?

**Comment by fildata** [comment]
> [> Author](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/311#issuecomment-1807097484)
> 
> Any update here? Have you submit the form?

We have registered our information on the Fil+ registration form.
Please confirm.

**Comment by Filplus-govteam** [comment]
Can you please provide proof these SPs are different entities in different locations? @fildata

**Comment by futuremaster777** [comment]
checker:manualTrigger

**Comment by futuremaster777** [comment]
checker:manualTrigger

**Comment by futuremaster777** [comment]
checker:manualTrigger

**Comment by futuremaster777** [comment]
checker:manualTrigger

**Comment by Sunnyiscoming** [comment]
Please provide ID, City, Country, Organization of each SP here.

**Comment by fildata** [comment]
> Please provide ID, City, Country, Organization of each SP here.

provide ID, City, Country,  Organization
f01115949, Seoul, Korea, GMI
f01900525, Seoul, Korea, GMI
f01770778, GyuyngGi, Korea, newclave   
f01924824, GyuyngGi, Korea, newclave   
f01924891, Seoul, Korea, TotalShift   
f01927163, Seoul, Korea, TheAfter Co., Ltd.   
f01784916, DaeGu, Korea, diasict Co., Ltd   
f01340400, Asan, Korea, diasict Co., Ltd   
f01310053, Asan, Korea, diasict Co., Ltd   
f01987994, Seoul, Korea, VOGO Digital Labs

**Comment by futuremaster777** [comment]
checker:manualTrigger

**Comment by fildata** [comment]
> Please provide ID, City, Country, Organization of each SP here.

@Sunnyiscoming
@Sunnyiscoming 

> Please provide ID, City, Country, Organization of each SP here.

provide ID, City, Country, Organization
f01115949, Seoul, Korea, GMI
f01900525, Seoul, Korea, GMI
f01770778, GyuyngGi, Korea, newclave
f01924824, GyuyngGi, Korea, newclave
f01924891, Seoul, Korea, TotalShift
f01927163, Seoul, Korea, TheAfter Co., Ltd.
f01784916, DaeGu, Korea, diasict Co., Ltd
f01340400, Asan, Korea, diasict Co., Ltd
f01310053, Asan, Korea, diasict Co., Ltd
f01987994, Seoul, Korea, VOGO Digital Labs

**Comment by fildata** [comment]
> Please provide ID, City, Country, Organization of each SP here.

@Sunnyiscoming

Please provide ID, City, Country, Organization of each SP here.

provide ID, City, Country, Organization
f01115949, Seoul, Korea, GMI
f01900525, Seoul, Korea, GMI
f01770778, GyuyngGi, Korea, newclave
f01924824, GyuyngGi, Korea, newclave
f01924891, Seoul, Korea, TotalShift
f01927163, Seoul, Korea, TheAfter Co., Ltd.
f01784916, DaeGu, Korea, diasict Co., Ltd
f01340400, Asan, Korea, diasict Co., Ltd
f01310053, Asan, Korea, diasict Co., Ltd
f01987994, Seoul, Korea, VOGO Digital Labs

**Comment by fildata** [comment]
> Please provide ID, City, Country, Organization of each SP here.

@Sunnyiscoming

Please provide ID, City, Country, Organization of each SP here.

provide ID, City, Country, Organization
f01115949, Seoul, Korea, GMI
f01900525, Seoul, Korea, GMI
f01770778, GyuyngGi, Korea, newclave
f01924824, GyuyngGi, Korea, newclave
f01924891, Seoul, Korea, TotalShift
f01927163, Seoul, Korea, TheAfter Co., Ltd.
f01784916, DaeGu, Korea, diasict Co., Ltd
f01340400, Asan, Korea, diasict Co., Ltd
f01310053, Asan, Korea, diasict Co., Ltd
f01987994, Seoul, Korea, VOGO Digital Labs

**Comment by fildata** [comment]
> Please provide ID, City, Country, Organization of each SP here.

provide ID, City, Country, Organization
f01115949, Seoul, Korea, GMI
f01900525, Seoul, Korea, GMI
f01770778, GyuyngGi, Korea, newclave
f01924824, GyuyngGi, Korea, newclave
f01924891, Seoul, Korea, TotalShift
f01927163, Seoul, Korea, TheAfter Co., Ltd.
f01784916, DaeGu, Korea, diasict Co., Ltd
f01340400, Asan, Korea, diasict Co., Ltd
f01310053, Asan, Korea, diasict Co., Ltd
f01987994, Seoul, Korea, VOGO Digital Labs

**Comment by fildata** [comment]
@Sunnyiscoming

Please provide ID, City, Country, Organization of each SP here.

provide ID, City, Country, Organization
f01115949, Seoul, Korea, GMI
f01900525, Seoul, Korea, GMI
f01770778, GyuyngGi, Korea, newclave
f01924824, GyuyngGi, Korea, newclave
f01924891, Seoul, Korea, TotalShift
f01927163, Seoul, Korea, TheAfter Co., Ltd.
f01784916, DaeGu, Korea, diasict Co., Ltd
f01340400, Asan, Korea, diasict Co., Ltd
f01310053, Asan, Korea, diasict Co., Ltd
f01987994, Seoul, Korea, VOGO Digital Labs

**Comment by fildata** [comment]
Hi... @kevzak We opened new application. Check Plz..
https://github.com/fidlabs/Enterprise-Data-Pathway/issues/22

**Comment by fildata** [comment]
Hi @kevzak
We opened new application for 'Enterprise-Data-Pathway'
https://github.com/fidlabs/Enterprise-Data-Pathway/issues/22

**Comment by data-programs** [comment]
<img width="32" alt="KYC" Verified src="https://stable.filplus.storage/images/filplus-kyc-verified-badge.png"/>

This user’s identity has been verified through [filplus.storage](https://filplus.storage)
