### ISSUE TITLE
[DataCap Application] Slingshot NEXRAD Dataset - CabrinaHuang

### ISSUE THREAD

**Issue by xingjitansuo** [filecoin-project/filecoin-plus-large-datasets#312]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: CabrinaHuang
- Website / Social Media: n/a
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 3PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 500TiB
- On-chain address for first allocation: f12ecnsbf7b2xkmuz4kwd5fhyvr2ktwg6ixw4kdtq

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
I have constantly joined as a client in Slingshot. I previously made deals with storage providers from different backgrounds all over the world.  
```

What is the primary source of funding for this project?
```
Slingshot Reward, and personal money. 
```

What other projects/ecosystem stakeholders is this project associated with?
```
Slingshot 2.8
```

## Use-case details

Describe the data being stored onto Filecoin
```
The Next Generation Weather Radar (NEXRAD) is a network of 160 high-resolution Doppler radar sites that detects precipitation and atmospheric movement and disseminates data in approximately 5 minute intervals from each site. NEXRAD enables severe storm prediction and is used by researchers and commercial enterprises to study and address the impact of weather across multiple sectors.

.
```

Where was the data in this dataset sourced from?
```
Slingshot Curated Datasets. 
https://registry.opendata.aws/noaa-nexrad/
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://noaa-nexrad-level2.s3.amazonaws.com/index.html
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Confirm -  yes.  
```

What is the expected retrieval frequency for this data?
```
Not often. I might retrieve it once a week to ensure the deal is retrievable. The slingshot team might retrieve it a few times in the review period. 
```

For how long do you plan to keep this dataset stored on Filecoin?
```
At least one year
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
All Regions. 

```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
1. Prepare car file 
2. Upload to the server for SP to download, or ship the disks to SP to download.  
3. Propose offline deal to SP once they have files ready to import. 

```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
I will send a large portion (90%) of the deal to SPs that demonstrate the ability to run node safely,  handle real deals with a consistent sealing rate, and supports retrieval. 
I am also willing to send a small portion of deals to SPs that are new to the network and provide them the opportunities to onboard to Filecoin faster.  
```

How will you be distributing deals across storage providers?
```
No single SPs can make deals more than 25%. 

```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
I am an expert in sending deals. 
```

**Comment by galen-mcandrew** [comment]
## Multisig Notary requested
#### Total DataCap requested 
> 3PiB
#### Expected weekly DataCap usage rate 
> 500TiB

**Comment by MegTei** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec7vshj2op5p2wj7jyjodrxek7n662o4iugey3f6fcnrl32f7a3ea 
#### Address 
> f12ecnsbf7b2xkmuz4kwd5fhyvr2ktwg6ixw4kdtq
#### Datacap Allocated
> 153.59TiB
#### Signer Address
> f1ystxl2ootvpirpa7ebgwl7vlhwkbx2r4zjxwe5i
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec7vshj2op5p2wj7jyjodrxek7n662o4iugey3f6fcnrl32f7a3ea

**Comment by xingjitansuo** [comment]
@Reiers @IreneYoung @s0nik42 @rayshitou @dannyob @TimWilliams00 @ozhtdong @Fenbushi-Filecoin  @neogeweb3 @swatchliu @andrewxhill @XnMatrixSV @cryptowhizzard
Could one of you help me to sign this? Really appreciated!

**Comment by cryptowhizzard** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebggs4uzp2cf2scejw46r4jdte72sscbynpag2kacsx7rywvrwtgk 
#### Address 
> f12ecnsbf7b2xkmuz4kwd5fhyvr2ktwg6ixw4kdtq
#### Datacap Allocated
> 153.59TiB
#### Signer Address
> f1krmypm4uoxxf3g7okrwtrahlmpcph3y7rbqqgfa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebggs4uzp2cf2scejw46r4jdte72sscbynpag2kacsx7rywvrwtgk

**Comment by IreneYoung** [comment]
Hi @xingjitansuo, I can support it if you still need DataCap.

**Comment by cryptowhizzard** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebrvaysjga3ht7dmsyhhpimma2sbxti3ur5jdf22gvjjokacrjuj2 
#### Address 
> f12ecnsbf7b2xkmuz4kwd5fhyvr2ktwg6ixw4kdtq
#### Datacap Allocated
> 307.19TiB
#### Signer Address
> f1krmypm4uoxxf3g7okrwtrahlmpcph3y7rbqqgfa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebrvaysjga3ht7dmsyhhpimma2sbxti3ur5jdf22gvjjokacrjuj2

**Comment by xingjitansuo** [comment]
@cryptowhizzard 
Yes, we are one the same page !!  and that's what I am working on right now. I have already contacted SP in North America and Europe. However, the data transfer speed is slow, and most of the data is still in the download phase.  and that's the reason why the first allocation is mostly to the SP from one continent. I can make sure that the next allocation would be more decentralized.

**Comment by xingjitansuo** [comment]
@IreneYoung 
Could you please help to sign this one ?

**Comment by xingjitansuo** [comment]
@Reiers @IreneYoung @s0nik42 @rayshitou @dannyob @TimWilliams00 @ozhtdong @Fenbushi-Filecoin @neogeweb3 @swatchliu @andrewxhill @XnMatrixSV 
Can one of you please review? Thanks

**Comment by cryptowhizzard** [comment]
@xingjitansuo 

I already proposed ;-) You need someone else to approve.

**Comment by swatchliu** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb5lnftirsb6nwi7agf2jtvb25s46dxzewibc2hojmqpttjxuy3u2 
#### Address 
> f12ecnsbf7b2xkmuz4kwd5fhyvr2ktwg6ixw4kdtq
#### Datacap Allocated
> 307.19TiB
#### Signer Address
> f1yh6q3nmsg7i2sys7f7dexcuajgoweudcqj2chfi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb5lnftirsb6nwi7agf2jtvb25s46dxzewibc2hojmqpttjxuy3u2

**Comment by EGGRICE02** [comment]
Any follow up on dealing with more storage providers? It has been two weeks since last update. You know 4 SP is far from enough for sake of data security.

**Comment by Yvette516** [comment]
@xingjitansuo Could you please provide your rootcid to retrieve?

**Comment by xingjitansuo** [comment]
@Yvette516 Those will be provided at the end of the Slingshot. Let me know if you need now.

**Comment by xingjitansuo** [comment]
@EGGRICE02  I have more than 10 SPs from three continents now.

**Comment by MegTei** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceazw7jvowfzk5s6y2pxjjvwxfq7gwojvjgoqvrjrb3ot2qgabia2c 
#### Address 
> f12ecnsbf7b2xkmuz4kwd5fhyvr2ktwg6ixw4kdtq
#### Datacap Allocated
> 614.39TiB
#### Signer Address
> f1ystxl2ootvpirpa7ebgwl7vlhwkbx2r4zjxwe5i
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceazw7jvowfzk5s6y2pxjjvwxfq7gwojvjgoqvrjrb3ot2qgabia2c

**Comment by kernelogic** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebgyfhhshjeggrdrifgvpv6ovbe2zo324uhxwovpe6kjrwwnztx4i 
#### Address 
> f12ecnsbf7b2xkmuz4kwd5fhyvr2ktwg6ixw4kdtq
#### Datacap Allocated
> 614.39TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebgyfhhshjeggrdrifgvpv6ovbe2zo324uhxwovpe6kjrwwnztx4i

**Comment by newwebgroup** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebwg6snxi3ptdxhfbdd75r3a3xn5yzj6fivaunon4cj4vdip3tpac 
#### Address 
> f12ecnsbf7b2xkmuz4kwd5fhyvr2ktwg6ixw4kdtq
#### Datacap Allocated
> 1.20PiB
#### Signer Address
> f1e77zuityhvvw6u2t6tb5qlnsegy2s67qs4lbbbq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebwg6snxi3ptdxhfbdd75r3a3xn5yzj6fivaunon4cj4vdip3tpac

**Comment by liyunzhi-666** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec44an6vghbgitm3njw6t34oa3t2sx2zpa4elrgu555znhrlxcfdw 
#### Address 
> f12ecnsbf7b2xkmuz4kwd5fhyvr2ktwg6ixw4kdtq
#### Datacap Allocated
> 1.20PiB
#### Signer Address
> f1pszcrsciyixyuxxukkvtazcokexbn54amf7gvoq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec44an6vghbgitm3njw6t34oa3t2sx2zpa4elrgu555znhrlxcfdw

**Comment by StFileCloud** [comment]
@xingjitansuo Hey, I noticed that you have committed no single SPs can make deals more than 25%. But f01863339 as shown in the screenshot has over 28% of the total DC.
![image](https://user-images.githubusercontent.com/106466939/180037856-1af1a5e0-9579-44d3-8798-3b0ec00710fb.png)

**Comment by xingjitansuo** [comment]
> @xingjitansuo Hey, I noticed that you have committed no single SPs can make deals more than 25%. But f01863339 as shown in the screenshot has over 28% of the total DC.
> 
> ![image](https://user-images.githubusercontent.com/106466939/180038197-ca08d19d-1e79-413c-b510-f62af4a902df.png)
> 
> 
> 
> 

That's because all other SPs are currently downloading the datasets. Please be patient and see the final state of distribution.

**Comment by StFileCloud** [comment]
> > @xingjitansuo Hey, I noticed that you have committed no single SPs can make deals more than 25%. But f01863339 as shown in the screenshot has over 28% of the total DC.
> > ![image](https://user-images.githubusercontent.com/106466939/180038197-ca08d19d-1e79-413c-b510-f62af4a902df.png)
> 
> That's because all other SPs are currently downloading the datasets. Please be patient and see the final state of distribution.

I see. So can you kindly provide CIDs to verify sealed data?

**Comment by xingjitansuo** [comment]
Please just read the rule of Slingshot carefully beforehand and then ask the silly question. 
Also, can you specify who you are. ? 

> > > @xingjitansuo Hey, I noticed that you have committed no single SPs can make deals more than 25%. But f01863339 as shown in the screenshot has over 28% of the total DC.
> 
> > > ![image](https://user-images.githubusercontent.com/106466939/180038197-ca08d19d-1e79-413c-b510-f62af4a902df.png)
> 
> > 
> 
> > That's because all other SPs are currently downloading the datasets. Please be patient and see the final state of distribution.
> 
> 
> 
> I see. So can you kindly provide CIDs to verify sealed data?

**Comment by cryptowhizzard** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced5io7dtb25u26jpggmjrgxrbprfhmygdoty3j7hebu7noyjomcsu 
#### Address 
> f12ecnsbf7b2xkmuz4kwd5fhyvr2ktwg6ixw4kdtq
#### Datacap Allocated
> 1.20PiB
#### Signer Address
> f1krmypm4uoxxf3g7okrwtrahlmpcph3y7rbqqgfa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced5io7dtb25u26jpggmjrgxrbprfhmygdoty3j7hebu7noyjomcsu

**Comment by kernelogic** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebdgyod74tfbsbffcwjmprngirfs7kglppque3m6skah36yrbjsxo 
#### Address 
> f12ecnsbf7b2xkmuz4kwd5fhyvr2ktwg6ixw4kdtq
#### Datacap Allocated
> 1.20PiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebdgyod74tfbsbffcwjmprngirfs7kglppque3m6skah36yrbjsxo

**Comment by kernelogic** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebiu5inuit4bwqs2t32ztndvclf3tx5qlpcvndamyhtcpbyjiezu4 
#### Address 
> f12ecnsbf7b2xkmuz4kwd5fhyvr2ktwg6ixw4kdtq
#### Datacap Allocated
> 1.20PiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebiu5inuit4bwqs2t32ztndvclf3tx5qlpcvndamyhtcpbyjiezu4

**Comment by kernelogic** [comment]
The above approval was done properly through plus.file.org website but still the client address received no DC.

**Comment by psh0691** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceadowc5c7gzydhhisunlrzvtpd2e3tznumfpvvvtgsvdnaaknanuk 
#### Address 
> f12ecnsbf7b2xkmuz4kwd5fhyvr2ktwg6ixw4kdtq
#### Datacap Allocated
> 1.20PiB
#### Signer Address
> f1qdko4jg25vo35qmyvcrw4ak4fmuu3f5rif2kc7i
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceadowc5c7gzydhhisunlrzvtpd2e3tznumfpvvvtgsvdnaaknanuk

**Comment by newwebgroup** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecb7sibwhgdtvh6aqiosaw735iggx25cl7b3mgdaln454l6u2bla4 
#### Address 
> f12ecnsbf7b2xkmuz4kwd5fhyvr2ktwg6ixw4kdtq
#### Datacap Allocated
> 1.20PiB
#### Signer Address
> f1e77zuityhvvw6u2t6tb5qlnsegy2s67qs4lbbbq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecb7sibwhgdtvh6aqiosaw735iggx25cl7b3mgdaln454l6u2bla4

**Comment by raghavrmadya** [comment]
@kernelogic @cryptowhizzard @psh0691 @newwebgroup please propose and approve this request again

**Comment by raghavrmadya** [comment]
## DataCap Allocation requested

### Request number 5
#### Multisig Notary address
> f01858410

#### Client address
> f12ecnsbf7b2xkmuz4kwd5fhyvr2ktwg6ixw4kdtq

#### DataCap allocation requested
> 1.20PiB

**Comment by kernelogic** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedhsik3mvsibyau4pos5dakcjaivsk2s6l7sefd4knj4ko7slnn4s 
#### Address 
> f12ecnsbf7b2xkmuz4kwd5fhyvr2ktwg6ixw4kdtq
#### Datacap Allocated
> 1.20PiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedhsik3mvsibyau4pos5dakcjaivsk2s6l7sefd4knj4ko7slnn4s

**Comment by kernelogic** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceacmgwifm23crkt7hfgsnobukva455hugpqn2akpucmx6fmzlz45a 
#### Address 
> f12ecnsbf7b2xkmuz4kwd5fhyvr2ktwg6ixw4kdtq
#### Datacap Allocated
> 1.20PiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceacmgwifm23crkt7hfgsnobukva455hugpqn2akpucmx6fmzlz45a

**Comment by xingjitansuo** [comment]
Thanks everyone helped with this LDN. Closing this one as it is done.

**Comment by filplus-checker** [comment]
## DataCap and CID Checker Report[^1]
 - Organization: `CabrinaHuang`
 - Client: `f12ecnsbf7b2xkmuz4kwd5fhyvr2ktwg6ixw4kdtq`
### Storage Provider Distribution
The below table shows the distribution of storage providers that have stored data for this client.

If this is the first time a provider takes verified deal, it will be marked as `new`.

For most of the datacap application, below restrictions should apply.
 - Storage provider should not exceed 25% of total datacap.
 - Storage provider should not be storing duplicate data for more than 20%.
 - Storage provider should have published its public IP address.
 - All storage providers should be located in different regions.

⚠️ 50.00% of total deal sealed by [f01924827](https://filfox.info/en/address/f01924827) are duplicate data.

⚠️ 50.00% of total deal sealed by [f01882035](https://filfox.info/en/address/f01882035) are duplicate data.

⚠️ 49.81% of total deal sealed by [f01887962](https://filfox.info/en/address/f01887962) are duplicate data.

⚠️ 49.53% of total deal sealed by [f01863339](https://filfox.info/en/address/f01863339) are duplicate data.

⚠️ 49.47% of total deal sealed by [f01850141](https://filfox.info/en/address/f01850141) are duplicate data.

⚠️ 49.06% of total deal sealed by [f098743](https://filfox.info/en/address/f098743) are duplicate data.

⚠️ 38.46% of total deal sealed by [f01841134](https://filfox.info/en/address/f01841134) are duplicate data.

⚠️ 22.85% of total deal sealed by [f01826997](https://filfox.info/en/address/f01826997) are duplicate data.

⚠️ 33.21% of total deal sealed by [f0117211](https://filfox.info/en/address/f0117211) are duplicate data.

⚠️ 27.97% of total deal sealed by [f0136399](https://filfox.info/en/address/f0136399) are duplicate data.

| Provider                                                    |                           Location | Total Deals Sealed | Percentage | Unique Data | Duplicate Deals |
| :---------------------------------------------------------- | ---------------------------------: | -----------------: | ---------: | ----------: | --------------: |
| [f01924827](https://filfox.info/en/address/f01924827)       | Hong Kong, Central and Western, HK |         368.88 TiB |     10.44% |  184.44 TiB |          50.00% |
| [f01882035](https://filfox.info/en/address/f01882035)`new`  |               Chengdu, Sichuan, CN |         368.88 TiB |     10.44% |  184.44 TiB |          50.00% |
| [f01887962](https://filfox.info/en/address/f01887962)       | Hong Kong, Central and Western, HK |         367.50 TiB |     10.40% |  184.44 TiB |          49.81% |
| [f01863339](https://filfox.info/en/address/f01863339)       |             Shanghai, Shanghai, CN |         365.41 TiB |     10.34% |  184.44 TiB |          49.53% |
| [f01850141](https://filfox.info/en/address/f01850141)`new`  | Hong Kong, Central and Western, HK |         365.03 TiB |     10.33% |  184.44 TiB |          49.47% |
| [f098743](https://filfox.info/en/address/f098743)           |            Shenzhen, Guangdong, CN |         362.07 TiB |     10.25% |  184.44 TiB |          49.06% |
| [f01841134](https://filfox.info/en/address/f01841134)       |           Singapore, Singapore, SG |         299.71 TiB |      8.48% |  184.44 TiB |          38.46% |
| [f01826997](https://filfox.info/en/address/f01826997)       |            Dongguan, Guangdong, CN |         212.45 TiB |      6.01% |  163.91 TiB |          22.85% |
| [f01946104](https://filfox.info/en/address/f01946104)`new`  |               Chengdu, Sichuan, CN |         183.78 TiB |      5.20% |  183.78 TiB |           0.00% |
| [f054464](https://filfox.info/en/address/f054464)           | Hong Kong, Central and Western, HK |         149.84 TiB |      4.24% |  131.48 TiB |          12.25% |
| [f01840219](https://filfox.info/en/address/f01840219)       |               Chengdu, Sichuan, CN |          93.34 TiB |      2.64% |   93.31 TiB |           0.03% |
| [f0117211](https://filfox.info/en/address/f0117211)         |           Singapore, Singapore, SG |          74.61 TiB |      2.11% |   49.83 TiB |          33.21% |
| [f0103704](https://filfox.info/en/address/f0103704)`new`    | Hong Kong, Central and Western, HK |          69.95 TiB |      1.98% |   69.95 TiB |           0.00% |
| [f0136399](https://filfox.info/en/address/f0136399)         | Hong Kong, Central and Western, HK |          69.39 TiB |      1.96% |   49.98 TiB |          27.97% |
| [f01823264](https://filfox.info/en/address/f01823264)       |               Chengdu, Sichuan, CN |          47.69 TiB |      1.35% |   47.69 TiB |           0.00% |
| [f0142637](https://filfox.info/en/address/f0142637)         |               Chengdu, Sichuan, CN |          39.00 TiB |      1.10% |   39.00 TiB |           0.00% |
| [f01344987](https://filfox.info/en/address/f01344987)       | Hong Kong, Central and Western, HK |          29.97 TiB |      0.85% |   29.97 TiB |           0.00% |
| [f01702940](https://filfox.info/en/address/f01702940)       |                  Dallas, Texas, US |          18.73 TiB |      0.53% |   18.73 TiB |           0.00% |
| [f01652333](https://filfox.info/en/address/f01652333)       |          Sunnyvale, California, US |          17.86 TiB |      0.51% |   17.86 TiB |           0.00% |
| [f01163272](https://filfox.info/en/address/f01163272)       |                Perm, Perm Krai, RU |           8.25 TiB |      0.23% |    8.25 TiB |           0.00% |
| [f02301](https://filfox.info/en/address/f02301)             |           San Jose, California, US |           5.97 TiB |      0.17% |    5.97 TiB |           0.00% |
| [f01864434](https://filfox.info/en/address/f01864434)       |        Sydney, New South Wales, AU |           4.00 TiB |      0.11% |    4.00 TiB |           0.00% |
| [f01225882](https://filfox.info/en/address/f01225882)       |      Burnaby, British Columbia, CA |           3.97 TiB |      0.11% |    3.97 TiB |           0.00% |
| [f0240185](https://filfox.info/en/address/f0240185)         |            Clifton, New Jersey, US |           2.13 TiB |      0.06% |    2.13 TiB |           0.00% |
| [f03223](https://filfox.info/en/address/f03223)             |           San Jose, California, US |           2.13 TiB |      0.06% |    2.13 TiB |           0.00% |
| [f0143858](https://filfox.info/en/address/f0143858)         |            Clifton, New Jersey, US |           1.94 TiB |      0.05% |    1.94 TiB |           0.00% |

![Provider Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/312/1671094879984.png)
### Deal Data Replication
The below table shows how each many unique data are replicated across storage providers.
- No more than 25% of unique data are stored with less than 4 providers.

✔️ Data replication looks healthy.

| Unique Data Size | Total Deals Made | Number of Providers | Deal Percentage |
| ---------------: | ---------------: | ------------------: | --------------: |
|         4.00 GiB |        12.00 GiB |                   2 |           0.00% |
|        16.00 GiB |        96.00 GiB |                   5 |           0.00% |
|        16.00 GiB |       176.00 GiB |                   7 |           0.00% |
|         7.28 TiB |       100.56 TiB |                   8 |           2.85% |
|        30.31 TiB |       451.66 TiB |                   9 |          12.79% |
|         3.50 TiB |        59.66 TiB |                  10 |           1.69% |
|        20.63 TiB |       369.59 TiB |                  11 |          10.46% |
|        57.09 TiB |         1.07 PiB |                  12 |          31.06% |
|        14.31 TiB |       299.63 TiB |                  13 |           8.48% |
|        25.59 TiB |       567.00 TiB |                  14 |          16.05% |
|        22.13 TiB |       496.19 TiB |                  15 |          14.05% |
|         1.81 TiB |        44.22 TiB |                  16 |           1.25% |
|       768.00 GiB |        18.88 TiB |                  17 |           0.53% |
|       928.00 GiB |        24.19 TiB |                  18 |           0.68% |
|       128.00 GiB |         3.47 TiB |                  19 |           0.10% |

![Replication Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/312/1671094880798.png)
### Deal Data Shared with other Clients
The below table shows how many unique data are shared with other clients.
Usually different applications owns different data and should not resolve to the same CID.

⚠️ CID sharing has been observed.

| Other Client                                                                                                                                                                                                              | Application          | Total Deals Affected | Unique CIDs |          Verifier |
| :------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ | :------------------- | -------------------: | ----------: | ----------------: |
| [f3u4iq6goq3ihauapuxrixgve4nuxou3khxjlv3yo<br/>fx3kolj6rn4vqaiyc7ma3zofjsxyahif2svqvvbud<br/>idxq](https://filfox.info/en/address/f3u4iq6goq3ihauapuxrixgve4nuxou3khxjlv3yofx3kolj6rn4vqaiyc7ma3zofjsxyahif2svqvvbudidxq) | Unknown              |             1.69 TiB |          54 |           Unknown |
| [f3vxf2bjxlo6yjezfk3edmi6hjkvqyjgdwt5r7aga<br/>zctmpkvhyjrwzajuxmvd2d5vfhiqbnl7xidrpbk5g<br/>aveq](https://filfox.info/en/address/f3vxf2bjxlo6yjezfk3edmi6hjkvqyjgdwt5r7agazctmpkvhyjrwzajuxmvd2d5vfhiqbnl7xidrpbk5gaveq) | `Glif auto verified` |            96.00 GiB |           3 | Jonathan Schwartz |
| [f1jmjc5zicv7gmrchnesma64cqjnbfiexzosdo24i](https://filfox.info/en/address/f1jmjc5zicv7gmrchnesma64cqjnbfiexzosdo24i)                                                                                                     | `Glif auto verified` |            64.00 GiB |           2 | Jonathan Schwartz |

[^1]: To manually trigger this report, add a comment with text `checker:manualTrigger`

**Comment by xingjitansuo** [comment]
Close this one as completed.
