### ISSUE TITLE
[DataCap Application] Baikal Seal Storage Technology

### ISSUE THREAD

**Issue by scharfstein** [filecoin-project/filecoin-plus-large-datasets#325]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Seal Storage Technology
- Website / Social Media: https://www.sealstorage.io/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 2 PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 400 TiB
- On-chain address for first allocation: f1usscfxtogr5v4jmi32uzkckeql2mgvun72q37ga

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Our customer is a Dark Matter Group within UC Berkeley and Seal is involved in a project with them to store the outputs of their scientific experiments. They would like to upload data to a distributed platform for other globally based researchers to be able to access this data. We will kicked off the project in early March 2022 with ingestion estimated to begin in mid April 2022 via portable disk unit. The customer’s data will not be encrypted, access controls will be implemented. They are looking for storage for at least the next three years.

Seal is a carbon-neutral, decentralized cloud storage provider. Seal's technical leadership brings decades of experience from traditional enterprise storage companies including Seagate and Oracle, as well as world-class experience on the Filecoin Network. Today, Seal operates data centers across the US and Canada with enterprise-grade infrastructure and data policies.
```

What is the primary source of funding for this project?
```
Seal is funding the project.
```

What other projects/ecosystem stakeholders is this project associated with?
```
None at this time.
```

## Use-case details

Describe the data being stored onto Filecoin
```
The data sets are the original outputs of scientific experiments.
```

Where was the data in this dataset sourced from?
```
The data sets have been created by dark matter-related experiments and instrumentation.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
Yes. A link will be added shortly.
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
The current data set requires permission based access.

A goal of the pilot project is for Seal to work with our customer to provide a permission based model to access data. Staged data for access will be supported on IPFS, Seaweed FS Open Source tools.
```

What is the expected retrieval frequency for this data?
```
Archival is primary. The data will be accessed by external collaborators and Researchers.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
Three years, at least.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
We plan to store five copies of the 400 TiB data set [total of 2 PiB] in five different cities, in three different countries and across two continents.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Seal Storage has dual 100 Gbps internet connections. SPs will download data from Seal. Offline data transfer may be possible.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We are currently discussing capabilities and performing due diligence with several SPs and have chosen three SPs for this project. We chose these based on their current storage capacity, compute capabilities, enterprise-grade DCs and bandwidth.
```

How will you be distributing deals across storage providers?
```
Holon, 400 TiB
ElioVP, 400 TiB
PikNik, 400 TiB
Seal, 800 TiB

Seal will also be keeping a hot copy (400 TB) for the Customer available for access.

The data ingestion will follow this approximate schedule:

55 TB right away
by the end of year 1: 5 TB
by end of year 2: 50 TB
by end of year 3: 290 TB
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, we have the resources/funding to begin making deals once we receive DataCap. 

We currently have the support we need.
```

**Comment by TimWilliams00** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceahnlilxqzokl2km27u2vxc3kovsqyinjg2ijx7oxmcwo7bs3tceu 
#### Address 
> f1usscfxtogr5v4jmi32uzkckeql2mgvun72q37ga
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1fkxkfxgopjf3ufnfg5i3m6qlwf73kp4w5zz7nnq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceahnlilxqzokl2km27u2vxc3kovsqyinjg2ijx7oxmcwo7bs3tceu

**Comment by dkkapur** [comment]
This went through, clearing the warning. 

<img width="553" alt="Screen Shot 2022-06-03 at 12 13 05 PM" src="https://user-images.githubusercontent.com/2343218/171961090-22ad17f9-1e23-4fd2-b7a8-d3d0034ea2bf.png">

**Comment by salstorage** [comment]
@raghavrmadya waiting for auto bot allocation for next tranche

**Comment by dkkapur** [comment]
@salstorage -> as part of routine cleanup we were doing (cc @galen-mcandrew) this notary was actually deprecated and set to 0. see https://filplus.d.interplanetary.one/notaries?showInactive=true&filter=Baikal. this is likely because it got picked up in our filters for "inactive" notaries where we had latent DataCap. can you shed any light on recent progress for this application and we can get you started up again? 

@galen-mcandrew @simonkim0515 @raghavrmadya what are your thoughts on getting this stood up via a new app following the latest guidelines (i.e., issue on notary governance + new app in this repo)? @kevzak is this a fit for E-Fil+ given private data?

**Comment by kevzak** [comment]
I think if Seal already had notaries that supported this application, there's no need to change the path to DataCap. If they need to start over, then it might be worth considering E-Fil

**Comment by johansealstorage** [comment]
checker:manualTrigger

**Comment by salstorage** [comment]
@raghavrmadya @dkkapur @galen-mcandrew this application is in a deprecated state.
LDN Application #1212 is active and replaces application #325

Please close this application as inactive/void
Thanks
Sal - Seal Storage
