### ISSUE TITLE
[DataCap Application] Ecology Limited 2

### ISSUE THREAD

**Issue by EcologyLtd** [filecoin-project/filecoin-plus-large-datasets#328]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Ecology Limited
- Website / Social Media: Slack@Ecology; Email: Ecology.ltd@outlook.com
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 200TiB
- On-chain address for first allocation: f1hv5lywbgq5oikqxjpes4svvg4nrybfdw3xusosi 

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Ecology Limited is a trading firm specializing in cryptocurrencies and digital assets. Founded in 2017, we manage millions USD in digital assets and trade across different financial products. With a dynamic and talented team, we leverage technology, research, and risk management to identify strategic market opportunities.
```

What is the primary source of funding for this project?
```
We are a self-funded company. We trade our own capital at our own risk. 
```

What other projects/ecosystem stakeholders is this project associated with?
```
We have a global network with different blockchain projects.
```

## Use-case details

Describe the data being stored onto Filecoin
```
Being a trading firm, we collect tons of data on a daily base from market news, analytics platforms, exchanges, etc. Our algorithmic trading system and proprietary trade execution model rely on these database for being responsive to changing markets. 
The data being stored include, but is not limited to market news, on-chain data, price & volume tracking, analysis, project database and non-confidential trading strategies.
```

Where was the data in this dataset sourced from?
```
Exchanges, analytics platforms, on-chain data, market news, and our own database.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
Yes. https://www.dropbox.com/s/g2oetn51w51kcxh/ecology.sample.txt?dl=0
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes, the datasets can be retrieved by anyone on the network. We might encrypt the sensitive data if there is any.
```

What is the expected retrieval frequency for this data?
```
We expect that retrieval may be sporadic.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
We intend to store this dataset as long as possible. 
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
We are open to all regions. Preferably Canada, Singapore and China as we have team based there.  
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Given the scale of the dataset, we plan to use an offline data transfer process.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We will choose a few different miners who are reputable and being active in the past 3 months.
```

How will you be distributing deals across storage providers?
```
We expect to work with a few reputable miners, and we will be distributing the data and DataCap based on their capacity and conditions. The miners also have to meet our requirements of minimum 12-month duration of storage.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes.
```

**Comment by AnthnoySmith** [comment]
Please provide your SP node and rootcid, we need to retrieve and download your public dataset before continuing this process.

**Comment by dkkapur** [comment]
@AnthnoySmith are you volunteering to do some retrieval checks on this? Thank you!

**Comment by dkkapur** [comment]
@EcologyLtd great to see part 2 of your data. You mention above that 
>We expect to work with a few reputable miners, and we will be distributing the data and DataCap based on their capacity and conditions. The miners also have to meet our requirements of minimum 12-month duration of storage.

From the deals made in the past, I see 35 SP IDs you worked with: https://filplus.d.interplanetary.one/clients/f01343523/breakdown. 

The main ones are:

- f01602479, https://whatismyipaddress.com/ip/3.26.3.84 looks to have a cloud based IP address in Australia
- f01606675, https://whatismyipaddress.com/ip/106.14.220.59 looks legitimately based in Shanghai 
- f01606849, https://whatismyipaddress.com/ip/35.178.203.79 looks to have a cloud based IP address in England
- f01641612, https://whatismyipaddress.com/ip/3.21.102.27 looks to have a cloud based IP address in USA

For the 3 that have cloud based IP addresses, are you aware of the SP organizations and where they are actually based? How did you find them / how did they establish reputation per your needs to ensure they are offering the quality of storage services you require?

**Comment by AnthnoySmith** [comment]
> @AnthnoySmith are you volunteering to do some retrieval checks on this? Thank you!

Yes, trying to check most of the suspicious nodes by myself.

**Comment by EcologyLtd** [comment]
> @EcologyLtd great to see part 2 of your data. You mention above that
> 
> > We expect to work with a few reputable miners, and we will be distributing the data and DataCap based on their capacity and conditions. The miners also have to meet our requirements of minimum 12-month duration of storage.
> 
> From the deals made in the past, I see 35 SP IDs you worked with: https://filplus.d.interplanetary.one/clients/f01343523/breakdown.
> 
> The main ones are:
> 
> * f01602479, https://whatismyipaddress.com/ip/3.26.3.84 looks to have a cloud based IP address in Australia
> * f01606675, https://whatismyipaddress.com/ip/106.14.220.59 looks legitimately based in Shanghai
> * f01606849, https://whatismyipaddress.com/ip/35.178.203.79 looks to have a cloud based IP address in England
> * f01641612, https://whatismyipaddress.com/ip/3.21.102.27 looks to have a cloud based IP address in USA
> 
> For the 3 that have cloud based IP addresses, are you aware of the SP organizations and where they are actually based? How did you find them / how did they establish reputation per your needs to ensure they are offering the quality of storage services you require?

@dkkapur Thanks for paying close attention to this application. We know them and have their promise for the quality of storage services, we also do retrieve testing to confirm that frequently. Looking forward to the result from AnthnoySmith and continue this process.

**Comment by dkkapur** [comment]
@EcologyLtd f01606849 and f01641612 seem to serve a lot of the same clients. There is substantial overlap https://filplus.d.interplanetary.one/miners/f01641612 and https://filplus.d.interplanetary.one/miners/f01606849. Are they related in any way? How did you find these SPs and get the guarantees you need? 

It's always a little concerning when the nodes are pointed to cloud based IP addresses. Do you know where the sealing workers and the data will physically be located?

**Comment by GaryGJG** [comment]
> 

Yes, they belong to the same institution, who has better reputation in this industry, a client of ours introduced us to them for help us dealing with data archive requirement. Trust them after they explain all the technical details to us, we think it's safe enough.
We know these miners hardware are in a datacenter of Canada,  as you could check from filplus website, we have tried to connect more miners, due to lack of staff, we have to put the most data in the most convenient place. If this doesn't meet  community's rules, welcome to give us valuable suggestions. Thank you @dkkapur

**Comment by EcologyLtd** [comment]
> @EcologyLtd f01606849 and f01641612 seem to serve a lot of the same clients. There is substantial overlap https://filplus.d.interplanetary.one/miners/f01641612 and https://filplus.d.interplanetary.one/miners/f01606849. Are they related in any way? How did you find these SPs and get the guarantees you need?
> 
> It's always a little concerning when the nodes are pointed to cloud based IP addresses. Do you know where the sealing workers and the data will physically be located?

Yes, they belong to the same institution, who has better reputation in this industry, a client of ours introduced us to them for help us dealing with data archive requirement. Trust them after they explain all the technical details to us, we think it's safe enough.
We know these miners hardware are in a datacenter of Canada,  as you could check from filplus website,we have tried to connect more miners,due to lack of staff, we have to put the most data in the most convenient place. If this doesn't meet  community's rules, welcome to give us valuable suggestions. Thank you! @dkkapur

**Comment by dkkapur** [comment]
@EcologyLtd I think it is super important to value decentralization and diversification as you onboard large sums of data onto the network, especially to minimize concentration risk and distribute data to several SPs. At this point, I suggest that you find at least 3 other SP organizations and focus first on restoring the data you have already stored with the main SP org to ensure you have safe replica building and no data loss from the network. 

Every other LDN application is held to this standard (at least 4 SP organizations). I don't think you'll get significant support from notaries without this. 

We can work on building a mechanism that tracks CIDs you want stored and shows where replicas are being built. We've done something similar to this with https://evergreen.filecoin.io/. Let me know what you think

**Comment by EcologyLtd** [comment]
> 

@dkkapur , really appreciate for your advice. we will take more efforts on allocating our data to more SP organizations.

It would be great if you can share more details on the CID tracking mechanism.  we would like take part in building and improving the tracking system. I will ping you on slack later.

**Comment by AnthnoySmith** [comment]
Your dataset could be retrieved, but most of them is invalid redundant data content.  Vote to close this application.

**Comment by raghavrmadya** [comment]
@EcologyLtd This link is broken. Could you please update it? - https://drive.google.com/drive/folders/1AQANDXMLkns6vmvQttdVZpIfACnUo65l

**Comment by raghavrmadya** [comment]
@EcologyLtd Interesting to see the SP-driven grouping approach based on reputation. The balance between reputable miners and meeting decentralization and diversification requirements is always tricky. Could you please share more details on how the SP's are establishing reputation per your needs to ensure they are offering the quality of storage services you require? I think insights into this could be useful to others.

**Comment by Sunnyiscoming** [comment]
Hope you can find appropriate storage providers quickly.

**Comment by dkkapur** [comment]
Any update here @EcologyLtd?

**Comment by EcologyLtd** [comment]
> 

Hi Deep, which subject do you mean? I think we have answered all the questions already.

**Comment by EcologyLtd** [comment]
> Any update here @EcologyLtd?


Hi Deep, which subject do you mean? I think we have answered all the questions already.

**Comment by Sunnyiscoming** [comment]
Have you found at least 3 other SP organizations?

**Comment by Sunnyiscoming** [comment]
Any update here?

**Comment by raghavrmadya** [comment]
Closing due to no response to @Sunnyiscoming. Please open a new application and provide satisfactory evidence of deal distribution as well as proof that all deals are not being stored in the same data centre. You can use the fil-plus slack channel. BigDexchange and Filgram to find reputable SPs.Thank you
