### ISSUE TITLE
[DataCap Application] ONE STORE

### ISSUE THREAD

**Issue by JongBin0606** [filecoin-project/filecoin-plus-large-datasets#331]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: ONE STORE
- Website / Social Media: https://www.youtube.com/channel/UCVrXzq5LZO5dzoXwSFeV2jw
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):
- On-chain address for first allocation: f3uhbzavra5cvzieul3q3ybza6fjsxxcrc5tvq77m5smeaplcfrdmpzq4slzaem23fopvzdcgctqll2cp6di6a

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
One store is the data storage space for one-person media creators. Advances in image sensors enable individuals and small groups to produce high-quality media. But at the same time, they're asking for a lot of storage. This will accelerate over time. The size of the data will increase by tens of times due to the dynamic range, increased pixel count and commercialization of raw format. One store will securely store and transfer customer data quickly.
```

What is the primary source of funding for this project?
```
Customer usage fees, company capital
```

What other projects/ecosystem stakeholders is this project associated with?
```
Data Storage Client
```

## Use-case details

Describe the data being stored onto Filecoin
```
Media files such as photos, videos, and audio files
```

Where was the data in this dataset sourced from?
```
Client's Data
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://www.youtube.com/watch?v=u8GO7HWuIG0&t=49s
https://www.youtube.com/channel/UCVrXzq5LZO5dzoXwSFeV2jw
https://www.youtube.com/channel/UCLR0KAD2n4t7gMj01Hypc2w)
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes, they want to spread the data to a lot of people
```

What is the expected retrieval frequency for this data?
```
Stored media is data that gives interesting information to the general public. The frequency of retrieval of this data is expected to be very high
```

For how long do you plan to keep this dataset stored on Filecoin?
```
5 years. It will be updated in the future
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Asia, mostly China and Korea
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
We prefer online transmission. However, if offline transmission is necessary, we will use our distribution network.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We understand IPFS and FILECOIN systems well. You will be using filrep.io or Filecoin Blockchain Explorer
```

How will you be distributing deals across storage providers?
```
Depending on your data, you will use the most efficient method of online or offline transfers.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Our users want to let a lot of people know their data. Also, I want to make a deal as soon as possible. So we can maintain a cooperative relationship with them.
```

**Comment by JongBin0606** [comment]
oh I miss

**Comment by JongBin0606** [comment]
Weekly allocation of DataCap requested (usually between 1-100TiB)

**Comment by JongBin0606** [comment]
oh sorry, we want 10TiB weekly DataCap usage rate

**Comment by raghavrmadya** [comment]
No reply
