### ISSUE TITLE
[DataCap Application]zhenshu.ai

### ISSUE THREAD

**Issue by Zhenshu-AI** [filecoin-project/filecoin-plus-large-datasets#332]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name:zhenshu.ai
- Website / Social Media:www.zsxcai.com
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 4.5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 150TiB
- On-chain address for first allocation: f1xyx3tvfoy7ue62oqdtcpud5ewcw2i7ctu4kyylq

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Zhenshu.ai is headquartered in Chengdu High-tech Zone. Zhenshu is not only a technology enterprise with AI algorithm application technology as its main research direction, but also an AI talent innovation center of Sichuan Artificial Intelligence Research Institute.The company focuses on the research of artificial intelligence basic algorithms, has accumulated a lot in the industries of industrial inspection and medical treatment. We have formed breakthrough products in many industries.
```

What is the primary source of funding for this project?
```
Company's income.
```

What other projects/ecosystem stakeholders is this project associated with?
```
No.
```

## Use-case details

Describe the data being stored onto Filecoin
```
Database, video, audio, AI material.
```

Where was the data in this dataset sourced from?
```
Training lessons (100% copyright from our company) , dataset of AI training material.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://user-images.githubusercontent.com/103952593/163977716-7665bb9b-9756-4a0f-b9b9-29e177f4e0cc.mp4
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes, we confirm that all data is public.
```

What is the expected retrieval frequency for this data?
```
Maybe once a year or longer.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
3 years.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
China.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Both online(If it has a stable and fast network) and offline.
Offline data transfer will be 1. Convert data format 2. copy data, 3. storage cluster transportation 4. storage cluster coneted with miner server.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We'll pick up storage providers for filecoin cummunity (Slack or Telegram or Discord or Chinese SP register in Estuary) 
A CID list will be posted on this application since the deal have been made.
```

How will you be distributing deals across storage providers?
```
Less than 20% of total DC for each SPs.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
We've ready for starting storing. Just wait for the datacap.
```

**Comment by galen-mcandrew** [comment]
## Multisig Notary requested
#### Total DataCap requested 
> 4.5PiB
#### Expected weekly DataCap usage rate 
> 150TiB

**Comment by swatchliu** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacectsuts5bles3nn5qupapxxegmadmfrezrgmfj66xe2la55ccbuvg 
#### Address 
> f1xyx3tvfoy7ue62oqdtcpud5ewcw2i7ctu4kyylq
#### Datacap Allocated
> 75.00TiB
#### Signer Address
> f1yh6q3nmsg7i2sys7f7dexcuajgoweudcqj2chfi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacectsuts5bles3nn5qupapxxegmadmfrezrgmfj66xe2la55ccbuvg

**Comment by Fenbushi-Filecoin** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedoj5dpqpgbcwqmz6aojnmii7mbfwbyggwe3kijfq3ihmcev2prok 
#### Address 
> f1xyx3tvfoy7ue62oqdtcpud5ewcw2i7ctu4kyylq
#### Datacap Allocated
> 75.00TiB
#### Signer Address
> f1yqydpmqb5en262jpottko2kd65msajax7fi4rmq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedoj5dpqpgbcwqmz6aojnmii7mbfwbyggwe3kijfq3ihmcev2prok

**Comment by MRJAVAZHAO** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec2i4hqoybipn4tzytxqifoiek5ju2kmwi35g3flrdjawo34auojc 
#### Address 
> f1xyx3tvfoy7ue62oqdtcpud5ewcw2i7ctu4kyylq
#### Datacap Allocated
> 150.00TiB
#### Signer Address
> f14gme3f52prtyzk6pblogrdd6b6ivp4swc6qmesi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec2i4hqoybipn4tzytxqifoiek5ju2kmwi35g3flrdjawo34auojc

**Comment by TimWilliams00** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecolfecajgdt2worowymgozhubhrk75m37bjzza34psbdzazrv5tu 
#### Address 
> f1xyx3tvfoy7ue62oqdtcpud5ewcw2i7ctu4kyylq
#### Datacap Allocated
> 150.00TiB
#### Signer Address
> f1fkxkfxgopjf3ufnfg5i3m6qlwf73kp4w5zz7nnq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecolfecajgdt2worowymgozhubhrk75m37bjzza34psbdzazrv5tu

**Comment by MRJAVAZHAO** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebhg3nwpxokni4p2a4cfsk5y7ztbhmbjxdv52fbr7e4yl4pmkhk6e 
#### Address 
> f1xyx3tvfoy7ue62oqdtcpud5ewcw2i7ctu4kyylq
#### Datacap Allocated
> 300.00TiB
#### Signer Address
> f14gme3f52prtyzk6pblogrdd6b6ivp4swc6qmesi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebhg3nwpxokni4p2a4cfsk5y7ztbhmbjxdv52fbr7e4yl4pmkhk6e

**Comment by swatchliu** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebfcndxhbr37stdlse3jgxg777qjqfvyeos2ln5gaxkdbmsr6v47k 
#### Address 
> f1xyx3tvfoy7ue62oqdtcpud5ewcw2i7ctu4kyylq
#### Datacap Allocated
> 300.00TiB
#### Signer Address
> f1yh6q3nmsg7i2sys7f7dexcuajgoweudcqj2chfi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebfcndxhbr37stdlse3jgxg777qjqfvyeos2ln5gaxkdbmsr6v47k

**Comment by MRJAVAZHAO** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecvnlf2cpvqx6vhgdjeqxcf7zfdhedcktgutisn54qhrbc6xdmsta 
#### Address 
> f1xyx3tvfoy7ue62oqdtcpud5ewcw2i7ctu4kyylq
#### Datacap Allocated
> 600.00TiB
#### Signer Address
> f14gme3f52prtyzk6pblogrdd6b6ivp4swc6qmesi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecvnlf2cpvqx6vhgdjeqxcf7zfdhedcktgutisn54qhrbc6xdmsta

**Comment by rayshitou** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacednn7oro7xv74a6c5vpfitydi7p7gvgcedpbl6mqnkcxxsa6ob6bg 
#### Address 
> f1xyx3tvfoy7ue62oqdtcpud5ewcw2i7ctu4kyylq
#### Datacap Allocated
> 600.00TiB
#### Signer Address
> f136bz32l2hlyad4npmfg5dngcdw3jk3tpcpoz2ja
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacednn7oro7xv74a6c5vpfitydi7p7gvgcedpbl6mqnkcxxsa6ob6bg

**Comment by swatchliu** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecalnxofkuclgmzvdsm55d6wo7wpento6n3u4hdsbfbyvidsmygb2 
#### Address 
> f1xyx3tvfoy7ue62oqdtcpud5ewcw2i7ctu4kyylq
#### Datacap Allocated
> 1.17PiB
#### Signer Address
> f1yh6q3nmsg7i2sys7f7dexcuajgoweudcqj2chfi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecalnxofkuclgmzvdsm55d6wo7wpento6n3u4hdsbfbyvidsmygb2

**Comment by DarnellWashington** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebijzlgmbon3uozv6lkmonrsj74wzvg32mpdnrlvquuurp7vtohye 
#### Address 
> f1xyx3tvfoy7ue62oqdtcpud5ewcw2i7ctu4kyylq
#### Datacap Allocated
> 1.17PiB
#### Signer Address
> f1bjdcjxha3ldcstw5zmvkyu3r2p5x2bsm745kgsi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebijzlgmbon3uozv6lkmonrsj74wzvg32mpdnrlvquuurp7vtohye

**Comment by XnMatrixSV** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedchhrz6wjutthnl4cakkxeu3xxhysmrvftyqr7yoelcl4qosznh4 
#### Address 
> f1xyx3tvfoy7ue62oqdtcpud5ewcw2i7ctu4kyylq
#### Datacap Allocated
> 1.06PiB
#### Signer Address
> f1yuz2twsllparyfqwslfiuxrc5wj4mfiflvnsw6a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedchhrz6wjutthnl4cakkxeu3xxhysmrvftyqr7yoelcl4qosznh4

**Comment by TimWilliams00** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced5x6qtgz5q6p3sde5ekmhcldq4tv5hueteycu6nlyxquwgagy5fy 
#### Address 
> f1xyx3tvfoy7ue62oqdtcpud5ewcw2i7ctu4kyylq
#### Datacap Allocated
> 1.06PiB
#### Signer Address
> f1fkxkfxgopjf3ufnfg5i3m6qlwf73kp4w5zz7nnq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced5x6qtgz5q6p3sde5ekmhcldq4tv5hueteycu6nlyxquwgagy5fy

**Comment by filplus-checker** [comment]
## DataCap and CID Checker Report[^1]
 - Organization: `zhenshuai`
 - Client: `f1xyx3tvfoy7ue62oqdtcpud5ewcw2i7ctu4kyylq`
### Storage Provider Distribution
The below table shows the distribution of storage providers that have stored data for this client.

If this is the first time a provider takes verified deal, it will be marked as `new`.

For most of the datacap application, below restrictions should apply.
 - Storage provider should not exceed 25% of total datacap.
 - Storage provider should not be storing duplicate data for more than 20%.
 - Storage provider should have published its public IP address.
 - All storage providers should be located in different regions.

⚠️ 89.89% of total deal sealed by [f01974746](https://filfox.info/en/address/f01974746) are duplicate data.

⚠️ [f01974746](https://filfox.info/en/address/f01974746) has unknown IP location.

⚠️ 89.51% of total deal sealed by [f01887654](https://filfox.info/en/address/f01887654) are duplicate data.

⚠️ 89.32% of total deal sealed by [f01962589](https://filfox.info/en/address/f01962589) are duplicate data.

⚠️ [f01962589](https://filfox.info/en/address/f01962589) has unknown IP location.

⚠️ 89.82% of total deal sealed by [f01937964](https://filfox.info/en/address/f01937964) are duplicate data.

⚠️ [f01844999](https://filfox.info/en/address/f01844999) has unknown IP location.

⚠️ 79.67% of total deal sealed by [f01924416](https://filfox.info/en/address/f01924416) are duplicate data.

| Provider                                              |                 Location | Total Deals Sealed | Percentage | Unique Data | Duplicate Deals |
| :---------------------------------------------------- | -----------------------: | -----------------: | ---------: | ----------: | --------------: |
| [f01843974](https://filfox.info/en/address/f01843974) |       Hilliard, Ohio, US |         515.84 TiB |     11.66% |  515.84 TiB |           0.00% |
| [f01843889](https://filfox.info/en/address/f01843889) |       Hilliard, Ohio, US |         507.59 TiB |     11.47% |  507.59 TiB |           0.00% |
| [f01843549](https://filfox.info/en/address/f01843549) | San Jose, California, US |         494.38 TiB |     11.17% |  494.38 TiB |           0.00% |
| [f01843540](https://filfox.info/en/address/f01843540) | San Jose, California, US |         468.03 TiB |     10.58% |  468.03 TiB |           0.00% |
| [f01843673](https://filfox.info/en/address/f01843673) |       Hilliard, Ohio, US |         467.91 TiB |     10.57% |  467.91 TiB |           0.00% |
| [f01843602](https://filfox.info/en/address/f01843602) | San Jose, California, US |         460.50 TiB |     10.41% |  460.50 TiB |           0.00% |
| [f01974746](https://filfox.info/en/address/f01974746) |                  Unknown |         431.97 TiB |      9.76% |   43.66 TiB |          89.89% |
| [f01887654](https://filfox.info/en/address/f01887654) |    Ashburn, Virginia, US |         200.25 TiB |      4.53% |   21.00 TiB |          89.51% |
| [f01962589](https://filfox.info/en/address/f01962589) |                  Unknown |         150.66 TiB |      3.40% |   16.09 TiB |          89.32% |
| [f01828096](https://filfox.info/en/address/f01828096) | San Jose, California, US |         137.22 TiB |      3.10% |  137.22 TiB |           0.00% |
| [f01937964](https://filfox.info/en/address/f01937964) |         Tokyo, Tokyo, JP |         116.00 TiB |      2.62% |   11.81 TiB |          89.82% |
| [f01788231](https://filfox.info/en/address/f01788231) | San Jose, California, US |         105.69 TiB |      2.39% |  105.69 TiB |           0.00% |
| [f01807908](https://filfox.info/en/address/f01807908) | San Jose, California, US |          73.06 TiB |      1.65% |   73.06 TiB |           0.00% |
| [f01769554](https://filfox.info/en/address/f01769554) | San Jose, California, US |          69.91 TiB |      1.58% |   69.91 TiB |           0.00% |
| [f01788210](https://filfox.info/en/address/f01788210) |     Boardman, Oregon, US |          69.78 TiB |      1.58% |   69.78 TiB |           0.00% |
| [f01844999](https://filfox.info/en/address/f01844999) |                  Unknown |          47.00 TiB |      1.06% |   44.44 TiB |           5.45% |
| [f01788206](https://filfox.info/en/address/f01788206) |     Boardman, Oregon, US |          46.00 TiB |      1.04% |   46.00 TiB |           0.00% |
| [f01759262](https://filfox.info/en/address/f01759262) | San Jose, California, US |          23.38 TiB |      0.53% |   23.38 TiB |           0.00% |
| [f01924416](https://filfox.info/en/address/f01924416) | Singapore, Singapore, SG |          20.59 TiB |      0.47% |    4.19 TiB |          79.67% |
| [f01832632](https://filfox.info/en/address/f01832632) | San Jose, California, US |          19.06 TiB |      0.43% |   19.06 TiB |           0.00% |

![Provider Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/332/1671095041126.png)
### Deal Data Replication
The below table shows how each many unique data are replicated across storage providers.
- No more than 25% of unique data are stored with less than 4 providers.

⚠️ 100.00% of deals are for data replicated across less than 4 storage providers.

| Unique Data Size | Total Deals Made | Number of Providers | Deal Percentage |
| ---------------: | ---------------: | ------------------: | --------------: |
|         3.52 PiB |         4.32 PiB |                   1 |         100.00% |

![Replication Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/332/1671095041956.png)
### Deal Data Shared with other Clients
The below table shows how many unique data are shared with other clients.
Usually different applications owns different data and should not resolve to the same CID.

⚠️ CID sharing has been observed.

| Other Client                                                                                                          | Application                                                                                    | Total Deals Affected | Unique CIDs |                                                                                 Verifier |
| :-------------------------------------------------------------------------------------------------------------------- | :--------------------------------------------------------------------------------------------- | -------------------: | ----------: | ---------------------------------------------------------------------------------------: |
| [f1rnwp6p5kx7pcwexpucoav6mmwz3rkxw5blrboyy](https://filfox.info/en/address/f1rnwp6p5kx7pcwexpucoav6mmwz3rkxw5blrboyy) | [MigoVideo](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/517)       |            21.00 TiB |         132 |                                                                          LDN v3 multisig |
| [f1einobkrjcjk6gfc5ov6663vrri75hwdsjfs6pmq](https://filfox.info/en/address/f1einobkrjcjk6gfc5ov6663vrri75hwdsjfs6pmq) | [Cansoti](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/640)         |             2.50 TiB |           7 |                                                                          LDN v3 multisig |
| [f1ivsvpljx4ovp2tth73pllkxmumrudemks623iia](https://filfox.info/en/address/f1ivsvpljx4ovp2tth73pllkxmumrudemks623iia) | `TIS Inc. group`                                                                               |             2.03 TiB |          12 |                                                                          LDN v3 multisig |
| [f1zb6pgkktdbyy7zxfob6gripqxuc25ukf35cc7fq](https://filfox.info/en/address/f1zb6pgkktdbyy7zxfob6gripqxuc25ukf35cc7fq) | `Maxpic PhotoGraphic Studio`                                                                   |           992.00 GiB |           6 |                                                                          LDN v3 multisig |
| [f1tgii4xgcp6um4n2w7eqaw6bwvnvyii2u7cjgzka](https://filfox.info/en/address/f1tgii4xgcp6um4n2w7eqaw6bwvnvyii2u7cjgzka) | [Meson\.Network ](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/187) |           896.00 GiB |           3 |                                                                          LDN v3 multisig |
| [f1fmdka4yaspkjp3kw65azeygbmgp5dujl6wlghti](https://filfox.info/en/address/f1fmdka4yaspkjp3kw65azeygbmgp5dujl6wlghti) | [Bole digital](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/654)    |           672.00 GiB |           4 |                                                                          LDN v3 multisig |
| [f1mn5mw2dpqz6p3s7vxrlkhkh3okdtc6t7wqro4xa](https://filfox.info/en/address/f1mn5mw2dpqz6p3s7vxrlkhkh3okdtc6t7wqro4xa) | [Unisound](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/577)        |           576.00 GiB |           3 |                                                                          LDN v3 multisig |
| [f1hamzyd3tx4pdchop3l4hfeay5q6s427pxga6flq](https://filfox.info/en/address/f1hamzyd3tx4pdchop3l4hfeay5q6s427pxga6flq) | `Beacon Project`                                                                               |           576.00 GiB |           1 | Project Beacon, 12 LDNs LDN # 444, 446, 447, 448, 474, 475, 476, 477, 479, 480, 481, 482 |

[^1]: To manually trigger this report, add a comment with text `checker:manualTrigger`
