### ISSUE TITLE
[DataCap Application] CyArk

### ISSUE THREAD

**Issue by TCOtim** [filecoin-project/filecoin-plus-large-datasets#333]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: CyArk
- Website / Social Media: https://www.cyark.org
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 1.25PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100TiB
- On-chain address for first allocation: f1qtw2lcacklwev4dtupx4r2ubcixqg6rxjcfbsra

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
CyArk is a nonprofit organization committed to empowering connections with historic places. Founded in 2003, CyArk pioneered the application of 3D recording technologies to the preservation and celebration of cultural heritage and has worked with local partners at over 200 sites in more than 40 countries. CyArk strives to connect new audiences to heritage through place-based web, mobile and immersive experiences that inspire reflection, conversation and imagination..
```

What is the primary source of funding for this project?
```
Funding by donor only based on non-profit status.
```

What other projects/ecosystem stakeholders is this project associated with?
```
Seagate.
```

## Use-case details

Describe the data being stored onto Filecoin
```
We create photo-realistic 3D models of places through the application of state-of-the-art reality capture technologies.
```

Where was the data in this dataset sourced from?
```
3D Images captured by CyArk of world heritage sites to preserve and celebrate cultural history
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
Samples can be found here    https://cyark.org/explore/
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
confirmed
```

What is the expected retrieval frequency for this data?
```
quarterly at most.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
Forever, depending on service and value.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
US,  Western Europe, asia.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Planning to move over wire or alternatively via Seagate Lyve mobile(offline transfer).
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
recommendations from Seagate and Filecoin.
```

How will you be distributing deals across storage providers?
```
at least one copy per region.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Not planning to onboard till early June.  Seagate to facilitate data onboarding from Lyve cloud.
```

**Comment by galen-mcandrew** [comment]
@TCOtim The "weekly allocation" is connected to how much data you anticipate sealing and onboarding with storage providers per week. The bot will request tranches of DataCap at a scale based on your weekly and total requests, per the following rules: https://github.com/filecoin-project/filecoin-plus-large-datasets#datacap-allocation-calculations

For example, you may anticipate sealing and onboarding 50TiB per week, total across your distributed replicas with 4+ storage providers.

**Comment by TCOtim** [comment]
thanks Galen.  What is the duration/period/timeframe that this covers?  when does it expire?

________________________________

**Comment by galen-mcandrew** [comment]
## Multisig Notary requested
#### Total DataCap requested 
> 1.25PiB
#### Expected weekly DataCap usage rate 
> 100TiB

**Comment by TCOtim** [comment]
HI Galen and all.

Here's an F1 wallet that we can use:

f1qtw2lcacklwev4dtupx4r2ubcixqg6rxjcfbsra

**Comment by MegTei** [comment]
Hi, attempted to sign but recieved error msg, didnt seem to like the address

**Comment by TCOtim** [comment]
Josip-
Can you please clarify the address?

________________________________

**Comment by TCOtim** [comment]
Transferred FIL into the wallet without a problem: Address f1qtw2lcacklwev4dtupx4r2ubcixqg6rxjcfbsra - Filfox<https://filfox.info/en/address/f1qtw2lcacklwev4dtupx4r2ubcixqg6rxjcfbsra>

Address f1qtw2lcacklwev4dtupx4r2ubcixqg6rxjcfbsra - Filfox<https://filfox.info/en/address/f1qtw2lcacklwev4dtupx4r2ubcixqg6rxjcfbsra>
Filfox is a Filecoin blockchain explorer and data service platform, providing one-stop data services based on Filecoin, including various mining rankings, blockchain data queries, and visualization charts.
filfox.info

________________________________

**Comment by dkkapur** [comment]
Adjusting the application to reflect the updated address

**Comment by dkkapur** [comment]
@cryptowhizzard @MegTei can you folks try now?

**Comment by cryptowhizzard** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebapyvrtvsz7dfjvgssw3fqcamibaqp2smzzoyrlcjfvag4hlb2fs 
#### Address 
> f1qtw2lcacklwev4dtupx4r2ubcixqg6rxjcfbsra
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1krmypm4uoxxf3g7okrwtrahlmpcph3y7rbqqgfa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebapyvrtvsz7dfjvgssw3fqcamibaqp2smzzoyrlcjfvag4hlb2fs

**Comment by Fenbushi-Filecoin** [comment]
I can support the application.

**Comment by Fenbushi-Filecoin** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceash2d3qwrdlue4iy2vbhb5o4pk7uhbwve6f6yp6sszqbgief5vba 
#### Address 
> f1qtw2lcacklwev4dtupx4r2ubcixqg6rxjcfbsra
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1yqydpmqb5en262jpottko2kd65msajax7fi4rmq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceash2d3qwrdlue4iy2vbhb5o4pk7uhbwve6f6yp6sszqbgief5vba

**Comment by Sunnyiscoming** [comment]
Are there any problems with using datacap?

**Comment by pwrepo** [comment]
@Sunnyiscoming and @dkkapur doing some cleanup on LDNs and FF client interactions. There hasn't been movement on this for 6+ months. Close it out?

**Comment by TCOtim** [comment]
you can close it
________________________________
