### ISSUE TITLE
[DataCap Application] Tech Greedy / NEXRAD

### ISSUE THREAD

**Issue by xinaxu** [filecoin-project/filecoin-plus-large-datasets#335]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Tech Greedy Inc
- Website / Social Media: techgreed dot net
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5 PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100 TiB
- On-chain address for first allocation: f1ws3n5tuxtyg26lraqkjirz7qon7y7ckju7hhmii

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Tech Greedy has engaged in various activities in Filecoin ecosystem
1. Participation with Slingshot competition since 2020
2. Active storage providers with real retrieval
3. Developer for client tooling

This project is to onboard NEXRAD dataset to Filecoin network. It is a public dataset and there are two major purposes for this project
1. We have a contract with Protocol lab for developping end to end solution to onboard PiB scale client dataset to Filecoin network. The goal is to demonstrate the capability of onboarding PiB scale of data to Filecoin network within a month.
2. Continue participating Slingshot competition so the dataset can be recognized by Slingshot clients.
```

What is the primary source of funding for this project?
```
Company funding
```

What other projects/ecosystem stakeholders is this project associated with?
```
1. We are developing large-scale client tooling with PiB-scale data onboarding
    a. https://www.dgm.xyz/grants/zQV7SsH23ZMgRKbDjzjk
    b. Ensure the scalability and reliability of deal generation, deal making and distribution
    c. Integration with provider reputation system, consuming metrics from filrep/estuary and public metrics to other consumers.
    d. User friendly data retrieval
    e. Demonstration the capability of onboarding 1PiB of unique data within 30 days
2. Use BigD.Exchange platform (funded by Starboard Ventures) to
    a. Storage provider discovery
    b. Ask/Bid system


```

## Use-case details

Describe the data being stored onto Filecoin
```
The data is 20 years history of climate data
```

Where was the data in this dataset sourced from?
```
AWS open dataset
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
The data is primarily compressed binary data. Below site demonstrate how to consume and render the data
https://nbviewer.org/gist/dopplershift/356f2e14832e9b676207
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes
```

What is the expected retrieval frequency for this data?
```
Once a year
```

For how long do you plan to keep this dataset stored on Filecoin?
```
1.5 years
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
For the 1st round of the datacap allocation, we will use it for testing purpose to trouble shoot bugs and issues as we develop the deal making software. The providers will be selected from SPX who is willing to try out beta software to accept deals.

For the subsequent round of the datacap allocation, as we stablize the software, we will utilize this opportunity to demonstrate the scalability of our solution. We will prioritize making deals with storage providers who have demonstrate their sealing capabilities.
* APAC – Cabrina H, Holon
* NA – PikNik, CES Group, etc
* EU – Eliovp, Rob, Dcent, etc
* BigD.Exchange (funded by Starboard ventures), 20%
* Open to other experienced storage providers who’re willing to test out the solution (boost required)

```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Online data transfer.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
Already described above. We have built relationship with trustworth providers certified by Protocol Lab.
```

How will you be distributing deals across storage providers?
```
One copy per provider.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
We will start using the first round of datacap for testing immediately. In around June 2022, we will start using next rounds of datacap allocation for scalability testing.
```

**Comment by galen-mcandrew** [comment]
## Multisig Notary requested
#### Total DataCap requested 
> 5PiB
#### Expected weekly DataCap usage rate 
> 100TiB

**Comment by MegTei** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceau3gufukttzwuku7cztz762ogmiar3w4vtgovcszfn65y5wnoiq4 
#### Address 
> f1ws3n5tuxtyg26lraqkjirz7qon7y7ckju7hhmii
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1ystxl2ootvpirpa7ebgwl7vlhwkbx2r4zjxwe5i
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceau3gufukttzwuku7cztz762ogmiar3w4vtgovcszfn65y5wnoiq4

**Comment by s0nik42** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedbjdgwuijahtxlcm6lk7lmryxixmvnutvjj6d3ssgkt2ug7p2ehy 
#### Address 
> f1ws3n5tuxtyg26lraqkjirz7qon7y7ckju7hhmii
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1wxhnytjmklj2czezaqcfl7eb4nkgmaxysnegwii
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedbjdgwuijahtxlcm6lk7lmryxixmvnutvjj6d3ssgkt2ug7p2ehy

**Comment by Fenbushi-Filecoin** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced57byjlor5ivkz27qiiixbzs6lkrjge7ckj4ihvkwv5srqpyrz4y 
#### Address 
> f1ws3n5tuxtyg26lraqkjirz7qon7y7ckju7hhmii
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1yqydpmqb5en262jpottko2kd65msajax7fi4rmq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced57byjlor5ivkz27qiiixbzs6lkrjge7ckj4ihvkwv5srqpyrz4y

**Comment by kernelogic** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb3cvser7nyikti572ua44aqhvms3rmah3xi6u4fbcio523ahrpja 
#### Address 
> f1ws3n5tuxtyg26lraqkjirz7qon7y7ckju7hhmii
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb3cvser7nyikti572ua44aqhvms3rmah3xi6u4fbcio523ahrpja

**Comment by kernelogic** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced54vfrbupavk5xonxjcsg6m6ihac3yyjqrnrydrs5yoatnp5ohui 
#### Address 
> f1ws3n5tuxtyg26lraqkjirz7qon7y7ckju7hhmii
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced54vfrbupavk5xonxjcsg6m6ihac3yyjqrnrydrs5yoatnp5ohui

**Comment by xingjitansuo** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecxcyqgixurosugyhn33jr6slh6w5vimgiqxixgkbwffzxpgw45ce 
#### Address 
> f1ws3n5tuxtyg26lraqkjirz7qon7y7ckju7hhmii
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1a2lia2cwwekeubwo4nppt4v4vebxs2frozarz3q
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecxcyqgixurosugyhn33jr6slh6w5vimgiqxixgkbwffzxpgw45ce

**Comment by Fenbushi-Filecoin** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecvxpmiumx4killwolycdtseuhv36y3txetuvkrds2sa4jkaxjkzw 
#### Address 
> f1ws3n5tuxtyg26lraqkjirz7qon7y7ckju7hhmii
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1yqydpmqb5en262jpottko2kd65msajax7fi4rmq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecvxpmiumx4killwolycdtseuhv36y3txetuvkrds2sa4jkaxjkzw

**Comment by cryptowhizzard** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceahg46ndgonjhqhcryupcus2vv546cbttrhmuz6hoytvzrshyajqy 
#### Address 
> f1ws3n5tuxtyg26lraqkjirz7qon7y7ckju7hhmii
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1krmypm4uoxxf3g7okrwtrahlmpcph3y7rbqqgfa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceahg46ndgonjhqhcryupcus2vv546cbttrhmuz6hoytvzrshyajqy

**Comment by kernelogic** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced6jhqzv7zdf6xnx74kduopyer4eudzc7qyven3ychxxicqrgykuq 
#### Address 
> f1ws3n5tuxtyg26lraqkjirz7qon7y7ckju7hhmii
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced6jhqzv7zdf6xnx74kduopyer4eudzc7qyven3ychxxicqrgykuq

**Comment by jamerduhgamer** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceamrwhxrxj74k56vugkjzdy4pnkbj5z6mbz5h77anweisdpy5ltgc 
#### Address 
> f1ws3n5tuxtyg26lraqkjirz7qon7y7ckju7hhmii
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1ypuqpi4xn5q7zi5at3rmdltosozifhqmrt66vhq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceamrwhxrxj74k56vugkjzdy4pnkbj5z6mbz5h77anweisdpy5ltgc

**Comment by xingjitansuo** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedrmvmb2kdruukqum4rkaatbekbujnwnfl6ns2bf7k4ngeh67hgva 
#### Address 
> f1ws3n5tuxtyg26lraqkjirz7qon7y7ckju7hhmii
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1a2lia2cwwekeubwo4nppt4v4vebxs2frozarz3q
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedrmvmb2kdruukqum4rkaatbekbujnwnfl6ns2bf7k4ngeh67hgva

**Comment by IreneYoung** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceasxzpadtc4mpwdaketccia6guw357fwwyfy4g7gb3upiqvbnjx5s 
#### Address 
> f1ws3n5tuxtyg26lraqkjirz7qon7y7ckju7hhmii
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1d4gmpqz3execjj2wvrxuuhvbms5mzh7t7yqrviq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceasxzpadtc4mpwdaketccia6guw357fwwyfy4g7gb3upiqvbnjx5s

**Comment by kernelogic** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec57zjsykfe3cbj2jbprjlvimeevqpwtz4zrpea7sfxcyxpcdzese 
#### Address 
> f1ws3n5tuxtyg26lraqkjirz7qon7y7ckju7hhmii
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec57zjsykfe3cbj2jbprjlvimeevqpwtz4zrpea7sfxcyxpcdzese

**Comment by xingjitansuo** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaehoj6vycdh6hn2z6n3uyfmqcppodsnx2acqjz4ba2ezfdp6l3ay 
#### Address 
> f1ws3n5tuxtyg26lraqkjirz7qon7y7ckju7hhmii
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1a2lia2cwwekeubwo4nppt4v4vebxs2frozarz3q
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaehoj6vycdh6hn2z6n3uyfmqcppodsnx2acqjz4ba2ezfdp6l3ay

**Comment by kernelogic** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec44e2u7zxyxrdk5gsgqyfkdfh5x2yjx3o4qqexml5kpzw7glurcc 
#### Address 
> f1ws3n5tuxtyg26lraqkjirz7qon7y7ckju7hhmii
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec44e2u7zxyxrdk5gsgqyfkdfh5x2yjx3o4qqexml5kpzw7glurcc

**Comment by cryptowhizzard** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacednxefu7wwixsxustnc3iqxnxjbyxhvhywzxjvc4chydrvq4w7e26 
#### Address 
> f1ws3n5tuxtyg26lraqkjirz7qon7y7ckju7hhmii
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1krmypm4uoxxf3g7okrwtrahlmpcph3y7rbqqgfa
#### Id
> c112bfbb-a7a0-40a6-a0d3-aff1dc83d1a0
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacednxefu7wwixsxustnc3iqxnxjbyxhvhywzxjvc4chydrvq4w7e26

**Comment by Fenbushi-Filecoin** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedfbp4q3pdjgepwy4pggjdvep4dqgcedru6yilhhjtjcztu4xtmp2 
#### Address 
> f1ws3n5tuxtyg26lraqkjirz7qon7y7ckju7hhmii
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1yqydpmqb5en262jpottko2kd65msajax7fi4rmq
#### Id
> c112bfbb-a7a0-40a6-a0d3-aff1dc83d1a0
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedfbp4q3pdjgepwy4pggjdvep4dqgcedru6yilhhjtjcztu4xtmp2

**Comment by Fenbushi-Filecoin** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceat6jkfbrnfh36zvfu2asjis3nsudvesy4mc2rwcsqozvq46nwjmw 
#### Address 
> f1ws3n5tuxtyg26lraqkjirz7qon7y7ckju7hhmii
#### Datacap Allocated
> 370.00TiB
#### Signer Address
> f1yqydpmqb5en262jpottko2kd65msajax7fi4rmq
#### Id
> ab8885c6-397e-4599-bd30-6dab5f1242fa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceat6jkfbrnfh36zvfu2asjis3nsudvesy4mc2rwcsqozvq46nwjmw

**Comment by cryptowhizzard** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedsmrwlrlitho3anyge7quszy2lpfc52tdxu35z3cjycdd2zomn5g 
#### Address 
> f1ws3n5tuxtyg26lraqkjirz7qon7y7ckju7hhmii
#### Datacap Allocated
> 370.00TiB
#### Signer Address
> f1krmypm4uoxxf3g7okrwtrahlmpcph3y7rbqqgfa
#### Id
> ab8885c6-397e-4599-bd30-6dab5f1242fa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedsmrwlrlitho3anyge7quszy2lpfc52tdxu35z3cjycdd2zomn5g

**Comment by fabriziogianni7** [comment]
## DataCap Allocation requested

### Request number 11
#### Multisig Notary address
> f01858410

#### Client address
> f1ws3n5tuxtyg26lraqkjirz7qon7y7ckju7hhmii

#### DataCap allocation requested
> 800TiB

**Comment by simonkim0515** [comment]
## DataCap Allocation requested

### Request number 11
#### Multisig Notary address
> f01858410

#### Client address
> f1ws3n5tuxtyg26lraqkjirz7qon7y7ckju7hhmii

#### DataCap allocation requested
> 800TiB

#### Id
> ab8885c6-397e-4599-bd30-6dab5f1242fa

**Comment by cryptowhizzard** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedm4pzbpsm5ev6rxe6m6ti6hn37ixhscs74ttyx6l7vkoqqkidr6u 
#### Address 
> f1ws3n5tuxtyg26lraqkjirz7qon7y7ckju7hhmii
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1krmypm4uoxxf3g7okrwtrahlmpcph3y7rbqqgfa
#### Id
> ab8885c6-397e-4599-bd30-6dab5f1242fa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedm4pzbpsm5ev6rxe6m6ti6hn37ixhscs74ttyx6l7vkoqqkidr6u

**Comment by kernelogic** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebekpds4m4ksio45g2enw367iotj7wj52sjvok5pv663d74agbnpu 
#### Address 
> f1ws3n5tuxtyg26lraqkjirz7qon7y7ckju7hhmii
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### Id
> ab8885c6-397e-4599-bd30-6dab5f1242fa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebekpds4m4ksio45g2enw367iotj7wj52sjvok5pv663d74agbnpu

**Comment by filplus-checker** [comment]
## DataCap and CID Checker Report[^1]
 - Organization: `Tech Greedy Inc`
 - Client: `f1ws3n5tuxtyg26lraqkjirz7qon7y7ckju7hhmii`
### Storage Provider Distribution
The below table shows the distribution of storage providers that have stored data for this client.

If this is the first time a provider takes verified deal, it will be marked as `new`.

For most of the datacap application, below restrictions should apply.
 - Storage provider should not exceed 25% of total datacap.
 - Storage provider should not be storing duplicate data for more than 20%.
 - Storage provider should have published its public IP address.
 - All storage providers should be located in different regions.

✔️ Storage provider distribution looks healthy.

| Provider                                                    |                               Location | Total Deals Sealed | Percentage | Unique Data | Duplicate Deals |
| :---------------------------------------------------------- | -------------------------------------: | -----------------: | ---------: | ----------: | --------------: |
| [f01907460](https://filfox.info/en/address/f01907460)       |                Seattle, Washington, US |         583.38 TiB |     12.14% |  583.38 TiB |           0.00% |
| [f01920723](https://filfox.info/en/address/f01920723)       |               Maywood Park, Oregon, US |         414.97 TiB |      8.63% |  407.19 TiB |           1.88% |
| [f01761579](https://filfox.info/en/address/f01761579)`new`  |                 Hangzhou, Zhejiang, CN |         380.69 TiB |      7.92% |  378.75 TiB |           0.51% |
| [f01873432](https://filfox.info/en/address/f01873432)       |                  Las Vegas, Nevada, US |         332.09 TiB |      6.91% |  328.47 TiB |           1.09% |
| [f01850141](https://filfox.info/en/address/f01850141)       |     Hong Kong, Central and Western, HK |         314.59 TiB |      6.55% |  313.19 TiB |           0.45% |
| [f01652333](https://filfox.info/en/address/f01652333)       |              Sunnyvale, California, US |         277.97 TiB |      5.78% |  274.31 TiB |           1.32% |
| [f01851060](https://filfox.info/en/address/f01851060)`new`  |                  Las Vegas, Nevada, US |         277.41 TiB |      5.77% |  273.03 TiB |           1.58% |
| [f0838923](https://filfox.info/en/address/f0838923)         |                Seattle, Washington, US |         274.41 TiB |      5.71% |  271.19 TiB |           1.17% |
| [f01119939](https://filfox.info/en/address/f01119939)       |                      Dallas, Texas, US |         263.34 TiB |      5.48% |  260.94 TiB |           0.91% |
| [f01908671](https://filfox.info/en/address/f01908671)       |         Philadelphia, Pennsylvania, US |         262.78 TiB |      5.47% |  259.84 TiB |           1.12% |
| [f0750779](https://filfox.info/en/address/f0750779)`new`    |                   Chengdu, Sichuan, CN |         250.09 TiB |      5.20% |  249.50 TiB |           0.24% |
| [f01864434](https://filfox.info/en/address/f01864434)       |            Sydney, New South Wales, AU |         203.31 TiB |      4.23% |  202.06 TiB |           0.61% |
| [f09848](https://filfox.info/en/address/f09848)             | Rancho Santa Margarita, California, US |         190.94 TiB |      3.97% |  190.25 TiB |           0.36% |
| [f01894158](https://filfox.info/en/address/f01894158)`new`  |     Hong Kong, Central and Western, HK |         181.00 TiB |      3.77% |  180.84 TiB |           0.09% |
| [f039940](https://filfox.info/en/address/f039940)           |                   Chengdu, Sichuan, CN |         142.59 TiB |      2.97% |  142.41 TiB |           0.13% |
| [f01392893](https://filfox.info/en/address/f01392893)       |           Amsterdam, North Holland, NL |         121.06 TiB |      2.52% |  121.06 TiB |           0.00% |
| [f01904630](https://filfox.info/en/address/f01904630)       |                  Las Vegas, Nevada, US |         102.88 TiB |      2.14% |  101.66 TiB |           1.18% |
| [f01345523](https://filfox.info/en/address/f01345523)       |                Antwerpen, Flanders, BE |          80.38 TiB |      1.67% |   80.06 TiB |           0.39% |
| [f01863339](https://filfox.info/en/address/f01863339)       |                 Shanghai, Shanghai, CN |          70.22 TiB |      1.46% |   68.44 TiB |           2.54% |
| [f01419959](https://filfox.info/en/address/f01419959)       |              San Diego, California, US |          36.50 TiB |      0.76% |   35.53 TiB |           2.65% |
| [f01775922](https://filfox.info/en/address/f01775922)       |                  Ashburn, Virginia, US |          24.72 TiB |      0.51% |   24.69 TiB |           0.13% |
| [f01851231](https://filfox.info/en/address/f01851231)       |                Seattle, Washington, US |          21.25 TiB |      0.44% |   21.25 TiB |           0.00% |
| [f01662356](https://filfox.info/en/address/f01662356)       |                  Ashburn, Virginia, US |          64.00 GiB |      0.00% |   64.00 GiB |           0.00% |

![Provider Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/335/1671095070223.png)
### Deal Data Replication
The below table shows how each many unique data are replicated across storage providers.
- No more than 25% of unique data are stored with less than 4 providers.

✔️ Data replication looks healthy.

| Unique Data Size | Total Deals Made | Number of Providers | Deal Percentage |
| ---------------: | ---------------: | ------------------: | --------------: |
|       584.53 TiB |       584.59 TiB |                   1 |          12.16% |
|         9.44 TiB |        19.09 TiB |                   2 |           0.40% |
|        16.78 TiB |        50.75 TiB |                   3 |           1.06% |
|        16.91 TiB |        68.06 TiB |                   4 |           1.42% |
|        27.44 TiB |       138.19 TiB |                   5 |           2.87% |
|        29.69 TiB |       179.50 TiB |                   6 |           3.73% |
|        30.06 TiB |       211.78 TiB |                   7 |           4.41% |
|        27.97 TiB |       225.59 TiB |                   8 |           4.69% |
|        24.81 TiB |       225.16 TiB |                   9 |           4.68% |
|        26.31 TiB |       264.78 TiB |                  10 |           5.51% |
|        29.03 TiB |       321.81 TiB |                  11 |           6.70% |
|        25.94 TiB |       313.84 TiB |                  12 |           6.53% |
|        25.47 TiB |       334.06 TiB |                  13 |           6.95% |
|        29.84 TiB |       421.78 TiB |                  14 |           8.77% |
|        30.50 TiB |       462.28 TiB |                  15 |           9.62% |
|        27.63 TiB |       446.69 TiB |                  16 |           9.29% |
|        19.31 TiB |       332.09 TiB |                  17 |           6.91% |
|         9.09 TiB |       165.94 TiB |                  18 |           3.45% |
|         2.09 TiB |        40.63 TiB |                  19 |           0.85% |

![Replication Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/335/1671095071067.png)
### Deal Data Shared with other Clients
The below table shows how many unique data are shared with other clients.
Usually different applications owns different data and should not resolve to the same CID.

⚠️ CID sharing has been observed.

| Other Client                                                                                                          | Application                                                                                     | Total Deals Affected | Unique CIDs |        Verifier |
| :-------------------------------------------------------------------------------------------------------------------- | :---------------------------------------------------------------------------------------------- | -------------------: | ----------: | --------------: |
| [f1xafi3wsh7q553efnumhgeomathrehwwd2mye7oy](https://filfox.info/en/address/f1xafi3wsh7q553efnumhgeomathrehwwd2mye7oy) | [Speedium network](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/483) |             2.63 PiB |      13,100 | LDN v3 multisig |
| [f1pc5usvsbfgxxbq7c7quhhg6k7l6y5reiwqr3noy](https://filfox.info/en/address/f1pc5usvsbfgxxbq7c7quhhg6k7l6y5reiwqr3noy) | [Speedium network](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/403) |           236.44 TiB |       4,341 | LDN v3 multisig |

[^1]: To manually trigger this report, add a comment with text `checker:manualTrigger`

**Comment by Tom-zhang987** [comment]
checker:manualTrigger
