### ISSUE TITLE
[DataCap Application]xiaojipu

### ISSUE THREAD

**Issue by kimtony** [filecoin-project/filecoin-plus-large-datasets#337]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: xiaojipu
- Website / Social Media: https://www.xiaojipu.vip/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 50TiB
- On-chain address for first allocation: f3ryokto6idz5uwsfkynnv5sb7wyvxmszvhl3myjmomgve3clykzfvgfqgrswrxl7oggnu7njlhdeumx3c5ota

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
xiaojibu is a music score search website, which stores a large number of music scores and provides users with free retrieval of corresponding music scores. It is deeply loved by hundreds of thousands of music score lovers. We currently have hundreds of production servers in use. In the future, we plan to
Store music scores around the world and back up these data to the filecoin network, and use the retrieval function of the filecoin network to make retrieval more convenient for users around the world.
```

What is the primary source of funding for this project?
```
self-sustaining funds.
```

What other projects/ecosystem stakeholders is this project associated with?
```
No, we don't have.
```

## Use-case details

Describe the data being stored onto Filecoin
```
images,Database, video, audio
```

Where was the data in this dataset sourced from?
```
My team collects public free materials from the Internet  and  music lovers
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
[xiaojipu](https://soup-ku.oss-cn-beijing.aliyuncs.com/1024/75595fa6-9d84-4768-bda0-1d98c66476ad-0.gif)
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes, we confirm that all data is public.
```

What is the expected retrieval frequency for this data?
```
Maybe once a month or longer.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
Permanents.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
China.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Both online and offline transfer. It depends on actual network. In general, we choose offline transfer.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We plan to select free storage vendors, while opening it up for other retrieval.
```

How will you be distributing deals across storage providers?
```
3-5 SPs will store our data. Every sp will be distributed deals no more than 25% of all.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, we can make deals once we get datacap.  We have a technical team to track community dynamics enough to support making deals.
```

**Comment by Sunnyiscoming** [comment]
@kimtony Hi

Are you helping clients apply? What's your role in this application.

**Comment by kimtony** [comment]
@Sunnyiscoming 
platform developer

**Comment by dkkapur** [comment]
Can you email [filplus@fil.org](mailto:filplus@fil.org) with your official work email so we can share this with notaries as a form of proof that you represent this organization?

How are you picking the SPs you will be working with?

**Comment by kimtony** [comment]
> Can you email [filplus@fil.org](mailto:filplus@fil.org) with your official work email so we can share this with notaries as a form of proof that you represent this organization?
> 
> How are you picking the SPs you will be working with?


Thanks for the reply, I have sent [filplus@fil.org](mailto:filplus@fil.org)

**Comment by kimtony** [comment]
@dkkapur  
Excuse me, what should I do next?

**Comment by EGGRICE02** [comment]
1. Can you send an email to filplus@fil.org to verify you are representing for the company?
2. As for you data sample, I believe a mere picture cannot prove you need 5PB, not to mention there's no videos or audios on you website as you described. Please reupload data sample to clarify it.

**Comment by kimtony** [comment]
@EGGRICE02  hello
1、What information do I need to provide?
2、Our current first version is the old version, only the map pictures are stored, and a new version will be updated later, and we will store some free teaching videos and audios in it. There are videos of various musical instruments.

like this https://www.youtube.com/watch?v=avtDYCAtWjU

The new version has not been launched yet. It is currently under reconstruction. After the release of fvm, we will do related nft on-chain filecoin, and plan to update and iterate on the entire website.

**Comment by EGGRICE02** [comment]
@kimtony Hey
1.Sorry for the mess. I didn't notice that you've already mailed to filplus@fil.org
2.The Youtube link seems like a demo to demonstrate what kind of data you'd like to backup. That Youtube account has no relationship with you, right? So can you provide more info about the data you have or you're going to backup? To be clear, I mean the data you actually have now, a schedule of how much data will you generate per week just like you've mentioned, teaching videos or audios, or a developer account of fvm for us to track the progress of the new version, or what's your plan in making this project combining with nft on-chain filecoin or whatever.

**Comment by kimtony** [comment]
@EGGRICE02 hello

**Comment by kimtony** [comment]
@EGGRICE02 hello
1、our company did not apply for a business email, I sent it with my personal email.
2、data explame link: https://www.aliyundrive.com/s/sDCC33ka8Qe  Extraction code: d3h8
We record videos of different teachers' guitar, piano, guqin, flute and other instruments every day.
We have old video data, newly generated data, about 30tb per week.

**Comment by kimtony** [comment]
@Sunnyiscoming hello
doyin: wangdadadejita
At present, we are still doing social media accounts of other musical instruments.

**Comment by kimtony** [comment]
@Sunnyiscoming 
We want to back up music data like this to the filecoin network. Maybe some data in it is not directly generated by us, but it can be guaranteed to be publicly accessible.

**Comment by kimtony** [comment]
@EGGRICE02
Yes, these music data are musical instrument teaching videos produced by our teachers, and the music copyright is legal.

**Comment by kimtony** [comment]
@EGGRICE02 
hello, what should i do next

**Comment by Sunnyiscoming** [comment]
The governance will check the email and create multisig address after receiving that and checking the application materials.

**Comment by galen-mcandrew** [comment]
## Datacap Request Trigger
#### Total DataCap requested 
> 5PiB
#### Expected weekly DataCap usage rate 
> 50TiB 
#### Client address
> f3ryokto6idz5uwsfkynnv5sb7wyvxmszvhl3myjmomgve3clykzfvgfqgrswrxl7oggnu7njlhdeumx3c5ota

**Comment by Joss-Hua** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebath2cvcnoj3nmb4g6f73czkj7mw2sm2gbxuf2zqgc6t2vuq5iag 
#### Address 
> f3ryokto6idz5uwsfkynnv5sb7wyvxmszvhl3myjmomgve3clykzfvgfqgrswrxl7oggnu7njlhdeumx3c5ota
#### Datacap Allocated
> 25.00TiB
#### Signer Address
> f1tfg54zzscugttejv336vivknmsnzzmyudp3t7wi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebath2cvcnoj3nmb4g6f73czkj7mw2sm2gbxuf2zqgc6t2vuq5iag

**Comment by kimtony** [comment]
@galen-mcandrew @Sunnyiscoming  hello 
Thank you for the work you've done,as far as I know we need to get an additional signature from one notary.How do I need to contact？

**Comment by liyunzhi-666** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceagqsxsrgc5xnqkcx6ggt7mynsc5ltvh3akhqna5ex6avfgonnn24 
#### Address 
> f3ryokto6idz5uwsfkynnv5sb7wyvxmszvhl3myjmomgve3clykzfvgfqgrswrxl7oggnu7njlhdeumx3c5ota
#### Datacap Allocated
> 25.00TiB
#### Signer Address
> f1pszcrsciyixyuxxukkvtazcokexbn54amf7gvoq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceagqsxsrgc5xnqkcx6ggt7mynsc5ltvh3akhqna5ex6avfgonnn24

**Comment by kernelogic** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecyg5bteokhhpnt3flx2qdqv3gjxszfnpplci5cp22qqi2fecl3da 
#### Address 
> f3ryokto6idz5uwsfkynnv5sb7wyvxmszvhl3myjmomgve3clykzfvgfqgrswrxl7oggnu7njlhdeumx3c5ota
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecyg5bteokhhpnt3flx2qdqv3gjxszfnpplci5cp22qqi2fecl3da

**Comment by psh0691** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedghau275r6sq4nlb7osdmzanx7mxnnco7denctvetk4qrvpvdtmu 
#### Address 
> f3ryokto6idz5uwsfkynnv5sb7wyvxmszvhl3myjmomgve3clykzfvgfqgrswrxl7oggnu7njlhdeumx3c5ota
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1qdko4jg25vo35qmyvcrw4ak4fmuu3f5rif2kc7i
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedghau275r6sq4nlb7osdmzanx7mxnnco7denctvetk4qrvpvdtmu

**Comment by BigD-Exchange** [comment]
@kimtony Hi! Great to see you have gotten approval for DataCap. If you are looking for storage providers to store these data or have any questions, please visit #bigdata-exchange on Filecoin Slack or reply here. 

We have strong demand from a diverse group of SPs, who are actively looking to onboard more data.

**Comment by filplus-checker** [comment]
## DataCap and CID Checker Report[^1]
 - Organization: `xiaojipu`
 - Client: `f3ryokto6idz5uwsfkynnv5sb7wyvxmszvhl3myjmomgve3clykzfvgfqgrswrxl7oggnu7njlhdeumx3c5ota`
### Storage Provider Distribution
The below table shows the distribution of storage providers that have stored data for this client.

If this is the first time a provider takes verified deal, it will be marked as `new`.

For most of the datacap application, below restrictions should apply.
 - Storage provider should not exceed 25% of total datacap.
 - Storage provider should not be storing duplicate data for more than 20%.
 - Storage provider should have published its public IP address.
 - All storage providers should be located in different regions.

⚠️ [f01166098](https://filfox.info/en/address/f01166098) has sealed 74.36% of total datacap.

⚠️ 99.59% of total deal sealed by [f01166098](https://filfox.info/en/address/f01166098) are duplicate data.

⚠️ [f01166098](https://filfox.info/en/address/f01166098) has unknown IP location.

⚠️ [f082635](https://filfox.info/en/address/f082635) has sealed 25.64% of total datacap.

⚠️ 98.33% of total deal sealed by [f082635](https://filfox.info/en/address/f082635) are duplicate data.

| Provider                                                    |             Location | Total Deals Sealed | Percentage | Unique Data | Duplicate Deals |
| :---------------------------------------------------------- | -------------------: | -----------------: | ---------: | ----------: | --------------: |
| [f01166098](https://filfox.info/en/address/f01166098)`new`  |              Unknown |          15.28 TiB |     74.36% |   64.00 GiB |          99.59% |
| [f082635](https://filfox.info/en/address/f082635)           | Chengdu, Sichuan, CN |           5.27 TiB |     25.64% |   90.31 GiB |          98.33% |

![Provider Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/337/1671095076416.png)
### Deal Data Replication
The below table shows how each many unique data are replicated across storage providers.
- No more than 25% of unique data are stored with less than 4 providers.

⚠️ 100.00% of deals are for data replicated across less than 4 storage providers.

| Unique Data Size | Total Deals Made | Number of Providers | Deal Percentage |
| ---------------: | ---------------: | ------------------: | --------------: |
|        26.31 GiB |        52.31 GiB |                   1 |           0.25% |
|        64.00 GiB |        20.50 TiB |                   2 |          99.75% |

![Replication Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/337/1671095077007.png)
### Deal Data Shared with other Clients
The below table shows how many unique data are shared with other clients.
Usually different applications owns different data and should not resolve to the same CID.

✔️ No CID sharing has been observed.

[^1]: To manually trigger this report, add a comment with text `checker:manualTrigger`
