### ISSUE TITLE
Terrafusion data Sampler / (Speedium)

### ISSUE THREAD

**Issue by cryptowhizzard** [filecoin-project/filecoin-plus-large-datasets#339]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Speedium network
- Website / Social Media: www.speedium.nl
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 3 PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 300 TiB
- On-chain address for first allocation: f1z7jogzx4x42wtilzb4lu6iotlad5rptt2acbzpi

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Speedium / Dcent has engaged in Slingshot starting 2.6. We have successfully stored more than 15 differerent datasets with 20+ different miners.

```

What is the primary source of funding for this project?
```
Company account
```

What other projects/ecosystem stakeholders is this project associated with?
```
Slingshot competition hosted by Protocol Labs
```

## Use-case details

Describe the data being stored onto Filecoin
```
The Terra Basic Fusion dataset is a fused dataset of the original Level 1 radiances from the five Terra instruments. They have been fully validate to contain the original Terra instrument Level 1 data. 
```

Where was the data in this dataset sourced from?
```
AWS
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://terrafusion.web.illinois.edu/.
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes
```

What is the expected retrieval frequency for this data?
```
Multiple times p/y
```

For how long do you plan to keep this dataset stored on Filecoin?
```
18 months or longer
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
EU / US / Australia
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
The data will be transferred both offline and online.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We have a few providers who have been working with us during Slingshot Restore program and we'd like to continue working with them for ongoing Slingshot competition.
```

How will you be distributing deals across storage providers?
```
Max 2 copy's per storage provider if stored on different miners / locations.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, we have the resources.
```

**Comment by galen-mcandrew** [comment]
## Multisig Notary requested
#### Total DataCap requested 
> 3PiB
#### Expected weekly DataCap usage rate 
> 300TiB

**Comment by dkkapur** [comment]
@cryptowhizzard see https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/348#issuecomment-1123004278 when you get a chance. Using separate address here would help with Slingshot tracking too. Please update if this is possible! Thank you!

**Comment by cryptowhizzard** [comment]
@dkkapur - > Done.

**Comment by Reiers** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebamluoib4co62sauzopee5bftzym6ju4kzceu5xbnf27mmdd6d5w 
#### Address 
> f1z7jogzx4x42wtilzb4lu6iotlad5rptt2acbzpi
#### Datacap Allocated
> 150.00TiB
#### Signer Address
> f1oz43ckvmtxmmsfzqm6bpnemqlavz4ifyl524chq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebamluoib4co62sauzopee5bftzym6ju4kzceu5xbnf27mmdd6d5w

**Comment by MegTei** [comment]
HI @galen-mcandrew I was able to approve 348 but no others, have attempted this approval but just stuck in a loop

**Comment by MegTei** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecmnbqi4xmzqpj4fo32fgcyrcgatibfdzvyqa6ned3lxh76fr6aak 
#### Address 
> f1z7jogzx4x42wtilzb4lu6iotlad5rptt2acbzpi
#### Datacap Allocated
> 150.00TiB
#### Signer Address
> f1ystxl2ootvpirpa7ebgwl7vlhwkbx2r4zjxwe5i
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecmnbqi4xmzqpj4fo32fgcyrcgatibfdzvyqa6ned3lxh76fr6aak

**Comment by s0nik42** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecx4lol2kf4x7qd52pwtclrcnolsstmoi756albyggqapsq4znmte 
#### Address 
> f1z7jogzx4x42wtilzb4lu6iotlad5rptt2acbzpi
#### Datacap Allocated
> 300.00TiB
#### Signer Address
> f1wxhnytjmklj2czezaqcfl7eb4nkgmaxysnegwii
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecx4lol2kf4x7qd52pwtclrcnolsstmoi756albyggqapsq4znmte

**Comment by MegTei** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb5aynzgv7ubvhgrk2pla7dgfqu2id75gvapxoxq3qzwk4mu3tn3w 
#### Address 
> f1z7jogzx4x42wtilzb4lu6iotlad5rptt2acbzpi
#### Datacap Allocated
> 300.00TiB
#### Signer Address
> f1ystxl2ootvpirpa7ebgwl7vlhwkbx2r4zjxwe5i
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb5aynzgv7ubvhgrk2pla7dgfqu2id75gvapxoxq3qzwk4mu3tn3w

**Comment by flyworker** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecg5hpytjy46qjcf6motrgawijvr5xa7ero7qh6oi3ehz6toqcbra 
#### Address 
> f1z7jogzx4x42wtilzb4lu6iotlad5rptt2acbzpi
#### Datacap Allocated
> 600.00TiB
#### Signer Address
> f1hlubjsdkv4wmsdadihloxgwrz3j3ernf6i3cbpy
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecg5hpytjy46qjcf6motrgawijvr5xa7ero7qh6oi3ehz6toqcbra

**Comment by psh0691** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedkckfmmkjhuuakwcze2jxhy2urlrgqewos5vjvnhpuhq5rxhbu7s 
#### Address 
> f1z7jogzx4x42wtilzb4lu6iotlad5rptt2acbzpi
#### Datacap Allocated
> 1.17PiB
#### Signer Address
> f1qdko4jg25vo35qmyvcrw4ak4fmuu3f5rif2kc7i
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedkckfmmkjhuuakwcze2jxhy2urlrgqewos5vjvnhpuhq5rxhbu7s

**Comment by Reiers** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecy65r7j6mit73r3luiif2hk57jkknnblik7niiq3iabe25ksayi2 
#### Address 
> f1z7jogzx4x42wtilzb4lu6iotlad5rptt2acbzpi
#### Datacap Allocated
> 1.17PiB
#### Signer Address
> f1oz43ckvmtxmmsfzqm6bpnemqlavz4ifyl524chq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecy65r7j6mit73r3luiif2hk57jkknnblik7niiq3iabe25ksayi2

**Comment by kernelogic** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebti424xfplp4d7zdqkqs3muxyrwx5tpzt7u4fnoybjgdcvuhgul6 
#### Address 
> f1z7jogzx4x42wtilzb4lu6iotlad5rptt2acbzpi
#### Datacap Allocated
> 1.83PiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebti424xfplp4d7zdqkqs3muxyrwx5tpzt7u4fnoybjgdcvuhgul6

**Comment by MegTei** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedxpbqgqrtsge54cqzuituss6tzli2n4z5tfak4vrp7xzajsm2vqc 
#### Address 
> f1z7jogzx4x42wtilzb4lu6iotlad5rptt2acbzpi
#### Datacap Allocated
> 1.83PiB
#### Signer Address
> f1ystxl2ootvpirpa7ebgwl7vlhwkbx2r4zjxwe5i
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedxpbqgqrtsge54cqzuituss6tzli2n4z5tfak4vrp7xzajsm2vqc

**Comment by psh0691** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec6cmwo2qcw6xmhnw5ui3qtct2ttlv4gcsunfvcivgrxqs6ys222g 
#### Address 
> f1z7jogzx4x42wtilzb4lu6iotlad5rptt2acbzpi
#### Datacap Allocated
> 1.83PiB
#### Signer Address
> f1qdko4jg25vo35qmyvcrw4ak4fmuu3f5rif2kc7i
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec6cmwo2qcw6xmhnw5ui3qtct2ttlv4gcsunfvcivgrxqs6ys222g

**Comment by Reiers** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebx2ykj5kjb2prj7zrw2fg4yoqcqlkpynauigfoe7ndsi4wnasyo2 
#### Address 
> f1z7jogzx4x42wtilzb4lu6iotlad5rptt2acbzpi
#### Datacap Allocated
> 1.83PiB
#### Signer Address
> f1oz43ckvmtxmmsfzqm6bpnemqlavz4ifyl524chq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebx2ykj5kjb2prj7zrw2fg4yoqcqlkpynauigfoe7ndsi4wnasyo2

**Comment by raghavrmadya** [comment]
## DataCap Allocation requested

### Request number 6
#### Multisig Notary address
> f01858410

#### Client address
> f1z7jogzx4x42wtilzb4lu6iotlad5rptt2acbzpi

#### DataCap allocation requested
> 1.83PiB

**Comment by raghavrmadya** [comment]
## DataCap Allocation requested

### Request number 6
#### Multisig Notary address
> f01858410

#### Client address
> f1z7jogzx4x42wtilzb4lu6iotlad5rptt2acbzpi

#### DataCap allocation requested
> 1.83PiB

**Comment by raghavrmadya** [comment]
@psh0691 @Reiers , please propose and approve again

**Comment by MegTei** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceai5eynwu3vxptkcm6pelvvrjcnq6y7527trbnsxase53frvya3ny 
#### Address 
> f1z7jogzx4x42wtilzb4lu6iotlad5rptt2acbzpi
#### Datacap Allocated
> 1.83PiB
#### Signer Address
> f1ystxl2ootvpirpa7ebgwl7vlhwkbx2r4zjxwe5i
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceai5eynwu3vxptkcm6pelvvrjcnq6y7527trbnsxase53frvya3ny

**Comment by s0nik42** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebne3x552kq7fjfgrrzeqdydexnajat3h6dwkywyvticm735kbhso 
#### Address 
> f1z7jogzx4x42wtilzb4lu6iotlad5rptt2acbzpi
#### Datacap Allocated
> 1.83PiB
#### Signer Address
> f1wxhnytjmklj2czezaqcfl7eb4nkgmaxysnegwii
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebne3x552kq7fjfgrrzeqdydexnajat3h6dwkywyvticm735kbhso

**Comment by filplus-checker** [comment]
## DataCap and CID Checker Report[^1]
 - Organization: `Speedium network`
 - Client: `f1z7jogzx4x42wtilzb4lu6iotlad5rptt2acbzpi`
### Storage Provider Distribution
The below table shows the distribution of storage providers that have stored data for this client.

If this is the first time a provider takes verified deal, it will be marked as `new`.

For most of the datacap application, below restrictions should apply.
 - Storage provider should not exceed 25% of total datacap.
 - Storage provider should not be storing duplicate data for more than 20%.
 - Storage provider should have published its public IP address.
 - All storage providers should be located in different regions.

⚠️ 31.23% of total deal sealed by [f01901765](https://filfox.info/en/address/f01901765) are duplicate data.

| Provider                                                    |                               Location | Total Deals Sealed | Percentage | Unique Data | Duplicate Deals |
| :---------------------------------------------------------- | -------------------------------------: | -----------------: | ---------: | ----------: | --------------: |
| [f01786387](https://filfox.info/en/address/f01786387)       |       Heerhugowaard, North Holland, NL |         281.19 TiB |      7.58% |  266.31 TiB |           5.29% |
| [f01864434](https://filfox.info/en/address/f01864434)       |            Sydney, New South Wales, AU |         257.96 TiB |      6.96% |  244.71 TiB |           5.14% |
| [f022352](https://filfox.info/en/address/f022352)           |                         Oslo, Oslo, NO |         249.11 TiB |      6.72% |  248.73 TiB |           0.15% |
| [f01720359](https://filfox.info/en/address/f01720359)       |       Heerhugowaard, North Holland, NL |         196.93 TiB |      5.31% |  182.20 TiB |           7.48% |
| [f01771403](https://filfox.info/en/address/f01771403)       |       Heerhugowaard, North Holland, NL |         180.69 TiB |      4.87% |  171.24 TiB |           5.23% |
| [f01878201](https://filfox.info/en/address/f01878201)       |                 Hangzhou, Zhejiang, CN |         153.93 TiB |      4.15% |  136.13 TiB |          11.56% |
| [f01880047](https://filfox.info/en/address/f01880047)       |               Singapore, Singapore, SG |         129.41 TiB |      3.49% |  129.41 TiB |           0.00% |
| [f01119939](https://filfox.info/en/address/f01119939)       |                      Dallas, Texas, US |         129.38 TiB |      3.49% |  129.38 TiB |           0.00% |
| [f01896422](https://filfox.info/en/address/f01896422)`new`  |                Fremont, California, US |         129.09 TiB |      3.48% |  128.97 TiB |           0.10% |
| [f01962819](https://filfox.info/en/address/f01962819)`new`  |                     Xi’an, Shaanxi, CN |         127.63 TiB |      3.44% |  127.54 TiB |           0.07% |
| [f01746964](https://filfox.info/en/address/f01746964)       |            Sydney, New South Wales, AU |         127.42 TiB |      3.44% |  127.42 TiB |           0.00% |
| [f01911083](https://filfox.info/en/address/f01911083)       |                   Tuusula, Uusimaa, FI |         125.61 TiB |      3.39% |  125.52 TiB |           0.07% |
| [f01885088](https://filfox.info/en/address/f01885088)       |     Hong Kong, Central and Western, HK |         125.44 TiB |      3.38% |  125.44 TiB |           0.00% |
| [f01926635](https://filfox.info/en/address/f01926635)       |     Hong Kong, Central and Western, HK |         125.00 TiB |      3.37% |  125.00 TiB |           0.00% |
| [f01926686](https://filfox.info/en/address/f01926686)       |                 Hangzhou, Zhejiang, CN |         123.49 TiB |      3.33% |  123.49 TiB |           0.00% |
| [f01858429](https://filfox.info/en/address/f01858429)       |              Boston, Massachusetts, US |         122.99 TiB |      3.32% |  122.99 TiB |           0.00% |
| [f01907545](https://filfox.info/en/address/f01907545)       |                     Xi’an, Shaanxi, CN |         120.71 TiB |      3.26% |  120.71 TiB |           0.00% |
| [f01928520](https://filfox.info/en/address/f01928520)       |               Maywood Park, Oregon, US |         114.45 TiB |      3.09% |  114.45 TiB |           0.00% |
| [f099608](https://filfox.info/en/address/f099608)           |                         Riga, Riga, LV |         109.72 TiB |      2.96% |  109.63 TiB |           0.09% |
| [f097777](https://filfox.info/en/address/f097777)           |                    Kivertsi, Volyn, UA |         103.56 TiB |      2.79% |   98.60 TiB |           4.79% |
| [f01929565](https://filfox.info/en/address/f01929565)`new`  |            Sydney, New South Wales, AU |          86.69 TiB |      2.34% |   86.69 TiB |           0.00% |
| [f01199442](https://filfox.info/en/address/f01199442)       |       Heerhugowaard, North Holland, NL |          61.85 TiB |      1.67% |   61.82 TiB |           0.05% |
| [f01207045](https://filfox.info/en/address/f01207045)       |       Heerhugowaard, North Holland, NL |          59.05 TiB |      1.59% |   59.05 TiB |           0.00% |
| [f01199430](https://filfox.info/en/address/f01199430)       |       Heerhugowaard, North Holland, NL |          50.18 TiB |      1.35% |   50.12 TiB |           0.13% |
| [f01208862](https://filfox.info/en/address/f01208862)       |       Heerhugowaard, North Holland, NL |          49.05 TiB |      1.32% |   49.05 TiB |           0.00% |
| [f09848](https://filfox.info/en/address/f09848)             | Rancho Santa Margarita, California, US |          45.49 TiB |      1.23% |   45.49 TiB |           0.00% |
| [f01824635](https://filfox.info/en/address/f01824635)       |                Antwerpen, Flanders, BE |          43.03 TiB |      1.16% |   43.03 TiB |           0.00% |
| [f01201327](https://filfox.info/en/address/f01201327)       |       Heerhugowaard, North Holland, NL |          37.45 TiB |      1.01% |   37.45 TiB |           0.00% |
| [f010479](https://filfox.info/en/address/f010479)           |               Paris, Île-de-France, FR |          36.88 TiB |      0.99% |   32.58 TiB |          11.67% |
| [f01902461](https://filfox.info/en/address/f01902461)       |                   Zhengzhou, Henan, CN |          35.31 TiB |      0.95% |   35.31 TiB |           0.00% |
| [f01851482](https://filfox.info/en/address/f01851482)       |                       Busan, Busan, KR |          26.16 TiB |      0.71% |   26.16 TiB |           0.00% |
| [f01732189](https://filfox.info/en/address/f01732189)       |              San Diego, California, US |          22.30 TiB |      0.60% |   22.30 TiB |           0.00% |
| [f01852664](https://filfox.info/en/address/f01852664)       |               Singapore, Singapore, SG |          19.25 TiB |      0.52% |   19.25 TiB |           0.00% |
| [f01208803](https://filfox.info/en/address/f01208803)       |            Sydney, New South Wales, AU |          19.05 TiB |      0.51% |   16.13 TiB |          15.33% |
| [f01385207](https://filfox.info/en/address/f01385207)       |                  Lincoln, Nebraska, US |          18.31 TiB |      0.49% |   18.31 TiB |           0.00% |
| [f01208154](https://filfox.info/en/address/f01208154)       |            Sydney, New South Wales, AU |          18.13 TiB |      0.49% |   18.13 TiB |           0.00% |
| [f01208189](https://filfox.info/en/address/f01208189)       |            Sydney, New South Wales, AU |          17.43 TiB |      0.47% |   17.40 TiB |           0.18% |
| [f01901765](https://filfox.info/en/address/f01901765)       |                  Jiaxing, Zhejiang, CN |          12.41 TiB |      0.33% |    8.53 TiB |          31.23% |
| [f01652333](https://filfox.info/en/address/f01652333)       |              Sunnyvale, California, US |           7.40 TiB |      0.20% |    6.10 TiB |          17.63% |
| [f01882184](https://filfox.info/en/address/f01882184)       |               Singapore, Singapore, SG |           4.03 TiB |      0.11% |    4.03 TiB |           0.00% |
| [f010202](https://filfox.info/en/address/f010202)           |     Hong Kong, Central and Western, HK |           3.13 TiB |      0.08% |    3.13 TiB |           0.00% |
| [f01901739](https://filfox.info/en/address/f01901739)       |            Sydney, New South Wales, AU |           1.91 TiB |      0.05% |    1.91 TiB |           0.00% |
| [f0773157](https://filfox.info/en/address/f0773157)         |                Fremont, California, US |         176.00 GiB |      0.00% |  176.00 GiB |           0.00% |
| [f01208632](https://filfox.info/en/address/f01208632)       |            Sydney, New South Wales, AU |          32.00 GiB |      0.00% |   32.00 GiB |           0.00% |

![Provider Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/339/1671095123079.png)
### Deal Data Replication
The below table shows how each many unique data are replicated across storage providers.
- No more than 25% of unique data are stored with less than 4 providers.

⚠️ 27.81% of deals are for data replicated across less than 4 storage providers.

| Unique Data Size | Total Deals Made | Number of Providers | Deal Percentage |
| ---------------: | ---------------: | ------------------: | --------------: |
|       255.70 TiB |       263.55 TiB |                   1 |           7.11% |
|       152.89 TiB |       315.37 TiB |                   2 |           8.50% |
|       148.51 TiB |       452.56 TiB |                   3 |          12.20% |
|        14.73 TiB |        61.14 TiB |                   4 |           1.65% |
|       364.00 GiB |         1.87 TiB |                   5 |           0.05% |
|        32.00 GiB |       384.00 GiB |                  12 |           0.01% |
|       101.00 GiB |         1.41 TiB |                  14 |           0.04% |
|       776.00 GiB |        11.62 TiB |                  15 |           0.31% |
|         2.34 TiB |        38.35 TiB |                  16 |           1.03% |
|         7.67 TiB |       134.24 TiB |                  17 |           3.62% |
|        17.72 TiB |       327.92 TiB |                  18 |           8.84% |
|        30.34 TiB |       591.46 TiB |                  19 |          15.95% |
|        30.21 TiB |       618.11 TiB |                  20 |          16.67% |
|        22.42 TiB |       481.55 TiB |                  21 |          12.99% |
|        12.23 TiB |       275.00 TiB |                  22 |           7.42% |
|         4.64 TiB |       108.51 TiB |                  23 |           2.93% |
|         1.01 TiB |        24.39 TiB |                  24 |           0.66% |
|        32.00 GiB |       800.00 GiB |                  25 |           0.02% |
|         8.00 GiB |       208.00 GiB |                  26 |           0.01% |

![Replication Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/339/1671095123697.png)
### Deal Data Shared with other Clients
The below table shows how many unique data are shared with other clients.
Usually different applications owns different data and should not resolve to the same CID.

⚠️ CID sharing has been observed.

| Other Client                                                                                                          | Application                                                                                                     | Total Deals Affected | Unique CIDs |        Verifier |
| :-------------------------------------------------------------------------------------------------------------------- | :-------------------------------------------------------------------------------------------------------------- | -------------------: | ----------: | --------------: |
| [f15cps7yo2x4fosvp45opfihk3a4wg2qukmwyet7a](https://filfox.info/en/address/f15cps7yo2x4fosvp45opfihk3a4wg2qukmwyet7a) | [Dcent network](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/540)                    |             3.08 PiB |      18,148 | LDN v3 multisig |
| [f1pc5usvsbfgxxbq7c7quhhg6k7l6y5reiwqr3noy](https://filfox.info/en/address/f1pc5usvsbfgxxbq7c7quhhg6k7l6y5reiwqr3noy) | [Speedium network](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/403)                 |             1.43 PiB |       3,203 | LDN v3 multisig |
| [f1c4tsscftr3a6ljujjn7zmfpd6q5vab62ylqxrmi](https://filfox.info/en/address/f1c4tsscftr3a6ljujjn7zmfpd6q5vab62ylqxrmi) | [Speedium network](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/341)                 |           709.94 TiB |       1,913 | LDN v3 multisig |
| [f17ia7m5mvizrdug3sqtevqw3tifiqvxqr3kdaeuq](https://filfox.info/en/address/f17ia7m5mvizrdug3sqtevqw3tifiqvxqr3kdaeuq) | [ Speedium NetworkSpeedium Network](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/77) |           395.64 TiB |       4,354 |        LDN # 77 |
| [f1mgnwoczfj25foxn4555wvwyak6rsynzy7z73azy](https://filfox.info/en/address/f1mgnwoczfj25foxn4555wvwyak6rsynzy7z73azy) | [Speedium network](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/488)                 |            50.53 TiB |         909 | LDN v3 multisig |
| [f1xafi3wsh7q553efnumhgeomathrehwwd2mye7oy](https://filfox.info/en/address/f1xafi3wsh7q553efnumhgeomathrehwwd2mye7oy) | [Speedium network](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/483)                 |           288.00 GiB |           9 | LDN v3 multisig |

[^1]: To manually trigger this report, add a comment with text `checker:manualTrigger`

**Comment by Tom-zhang987** [comment]
checker:manualTrigger

**Comment by Tom-OriginStorage** [comment]
checker:manualTrigger

**Comment by data-programs** [comment]
<img width="32" alt="KYC" Verified src="https://stable.filplus.storage/images/filplus-kyc-verified-badge.png"/>

This user’s identity has been verified through [filplus.storage](https://filplus.storage)

**Comment by Sunnyiscoming** [comment]
Hello, @cryptowhizzard per the https://github.com/filecoin-project/notary-governance/issues/922 for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

This information will be reviewed by Fil+ Governance team to confirm validity and then the application will be allowed to move forward for additional notary review.

**Comment by Tom-OriginStorage** [comment]
checker:manualTrigger
