### ISSUE TITLE
Nexrad Dataset ( Speedium )

### ISSUE THREAD

**Issue by cryptowhizzard** [filecoin-project/filecoin-plus-large-datasets#340]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Speedium network
- Website / Social Media: www.speedium.nl
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 3 PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 300 TiB
- On-chain address for first allocation: f1xafi3wsh7q553efnumhgeomathrehwwd2mye7oy 

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Speedium / Dcent has engaged in Slingshot starting 2.6. We have successfully stored more than 15 differerent datasets with 20+ different miners.

```

What is the primary source of funding for this project?
```
Company account
```

What other projects/ecosystem stakeholders is this project associated with?
```
Slingshot competition hosted by Protocol Labs
```

## Use-case details

Describe the data being stored onto Filecoin
```
The [Next Generation Weather Radar](https://www.ncdc.noaa.gov/data-access/radar-data/nexrad) (NEXRAD) is a network of 160 high-resolution Doppler radar sites that detects precipitation and atmospheric movement and disseminates data in approximately 5 minute intervals from each site.
```

Where was the data in this dataset sourced from?
```
AWS
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://www.ncei.noaa.gov/products/radar-data/nexrad
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes.
```

What is the expected retrieval frequency for this data?
```
Multiple times p/y
```

For how long do you plan to keep this dataset stored on Filecoin?
```
18 months or longer
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
EU / US / Australia
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
The data will be transferred both offline and online.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We have a few providers who have been working with us during Slingshot Restore program and we'd like to continue working with them for ongoing Slingshot competition.
```

How will you be distributing deals across storage providers?
```
Max 2 copy's per storage provider if stored on different miners / locations.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, we have the resources.
```

**Comment by dkkapur** [comment]
@cryptowhizzard see https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/348#issuecomment-1123004278 when you get a chance. Using separate address here would help with Slingshot tracking too. Please update if this is possible! Thank you!

**Comment by galen-mcandrew** [comment]
## Multisig Notary requested
#### Total DataCap requested 
> 3PiB
#### Expected weekly DataCap usage rate 
> 300TiB

**Comment by cryptowhizzard** [comment]
@dkkapur - > Done.

**Comment by MegTei** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecmqt3kucuoypw57oaqrmmljbeviagykshpadba6r7crtr7s4r34q 
#### Address 
> f1xafi3wsh7q553efnumhgeomathrehwwd2mye7oy
#### Datacap Allocated
> 150.00TiB
#### Signer Address
> f1ystxl2ootvpirpa7ebgwl7vlhwkbx2r4zjxwe5i
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecmqt3kucuoypw57oaqrmmljbeviagykshpadba6r7crtr7s4r34q

**Comment by s0nik42** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaqb5f6wemvs4bdeq35y5tireuavixteihgn5duna4uzn52uzggcu 
#### Address 
> f1xafi3wsh7q553efnumhgeomathrehwwd2mye7oy
#### Datacap Allocated
> 150.00TiB
#### Signer Address
> f1wxhnytjmklj2czezaqcfl7eb4nkgmaxysnegwii
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaqb5f6wemvs4bdeq35y5tireuavixteihgn5duna4uzn52uzggcu

**Comment by MegTei** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedqajohlic7xrhz4vjgxqqunzlysnuifzuzxeckcj4bgmy34zzdau 
#### Address 
> f1xafi3wsh7q553efnumhgeomathrehwwd2mye7oy
#### Datacap Allocated
> 300.00TiB
#### Signer Address
> f1ystxl2ootvpirpa7ebgwl7vlhwkbx2r4zjxwe5i
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedqajohlic7xrhz4vjgxqqunzlysnuifzuzxeckcj4bgmy34zzdau

**Comment by Reiers** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebghl6qll4wri652ok45drogklgszta776uon2xzanubuwgmhnm5o 
#### Address 
> f1xafi3wsh7q553efnumhgeomathrehwwd2mye7oy
#### Datacap Allocated
> 300.00TiB
#### Signer Address
> f1oz43ckvmtxmmsfzqm6bpnemqlavz4ifyl524chq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebghl6qll4wri652ok45drogklgszta776uon2xzanubuwgmhnm5o

**Comment by Reiers** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacea4lziurldyirsaosjkcrt64bllwilqsbcojqttzajy3vakyfwrgu 
#### Address 
> f1xafi3wsh7q553efnumhgeomathrehwwd2mye7oy
#### Datacap Allocated
> 600.00TiB
#### Signer Address
> f1oz43ckvmtxmmsfzqm6bpnemqlavz4ifyl524chq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacea4lziurldyirsaosjkcrt64bllwilqsbcojqttzajy3vakyfwrgu

**Comment by kernelogic** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceahh7ejdwkah3jx7m2ysmuu7kfhnem7zrkmxvk7rapjwp7kdzf3iq 
#### Address 
> f1xafi3wsh7q553efnumhgeomathrehwwd2mye7oy
#### Datacap Allocated
> 600.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceahh7ejdwkah3jx7m2ysmuu7kfhnem7zrkmxvk7rapjwp7kdzf3iq

**Comment by Reiers** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedh3d43hp2vaxtehmiywipl6gwtd6bmwqcmjrg2dwfbuixdajhsam 
#### Address 
> f1xafi3wsh7q553efnumhgeomathrehwwd2mye7oy
#### Datacap Allocated
> 1.17PiB
#### Signer Address
> f1oz43ckvmtxmmsfzqm6bpnemqlavz4ifyl524chq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedh3d43hp2vaxtehmiywipl6gwtd6bmwqcmjrg2dwfbuixdajhsam

**Comment by kernelogic** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced3twpeywbjnt7bybbpwjzvhcw6bkrjzcti2qgyeghptrsmplq52s 
#### Address 
> f1xafi3wsh7q553efnumhgeomathrehwwd2mye7oy
#### Datacap Allocated
> 973.92TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced3twpeywbjnt7bybbpwjzvhcw6bkrjzcti2qgyeghptrsmplq52s

**Comment by s0nik42** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebxjmiuiorsds3ftxob6r2kor5dzw5pgf6gah772bvfzbezzupwne 
#### Address 
> f1xafi3wsh7q553efnumhgeomathrehwwd2mye7oy
#### Datacap Allocated
> 973.92TiB
#### Signer Address
> f1wxhnytjmklj2czezaqcfl7eb4nkgmaxysnegwii
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebxjmiuiorsds3ftxob6r2kor5dzw5pgf6gah772bvfzbezzupwne

**Comment by filplus-checker** [comment]
## DataCap and CID Checker Report[^1]
 - Organization: `Speedium network`
 - Client: `f1xafi3wsh7q553efnumhgeomathrehwwd2mye7oy`
### Storage Provider Distribution
The below table shows the distribution of storage providers that have stored data for this client.

If this is the first time a provider takes verified deal, it will be marked as `new`.

For most of the datacap application, below restrictions should apply.
 - Storage provider should not exceed 25% of total datacap.
 - Storage provider should not be storing duplicate data for more than 20%.
 - Storage provider should have published its public IP address.
 - All storage providers should be located in different regions.

⚠️ 25.76% of total deal sealed by [f01157271](https://filfox.info/en/address/f01157271) are duplicate data.

⚠️ 27.24% of total deal sealed by [f01208803](https://filfox.info/en/address/f01208803) are duplicate data.

⚠️ 24.50% of total deal sealed by [f01208154](https://filfox.info/en/address/f01208154) are duplicate data.

⚠️ 21.28% of total deal sealed by [f01156835](https://filfox.info/en/address/f01156835) are duplicate data.

⚠️ 53.06% of total deal sealed by [f01208189](https://filfox.info/en/address/f01208189) are duplicate data.

⚠️ 34.04% of total deal sealed by [f01208042](https://filfox.info/en/address/f01208042) are duplicate data.

⚠️ 23.89% of total deal sealed by [f01156538](https://filfox.info/en/address/f01156538) are duplicate data.

⚠️ [f01908299](https://filfox.info/en/address/f01908299) has unknown IP location.

| Provider                                                    |                         Location | Total Deals Sealed | Percentage | Unique Data | Duplicate Deals |
| :---------------------------------------------------------- | -------------------------------: | -----------------: | ---------: | ----------: | --------------: |
| [f01919423](https://filfox.info/en/address/f01919423)       |      Sydney, New South Wales, AU |         597.30 TiB |     11.13% |  576.67 TiB |           3.45% |
| [f01908671](https://filfox.info/en/address/f01908671)       |   Philadelphia, Pennsylvania, US |         503.09 TiB |      9.37% |  460.88 TiB |           8.39% |
| [f01938357](https://filfox.info/en/address/f01938357)       |      Sydney, New South Wales, AU |         431.94 TiB |      8.05% |  431.91 TiB |           0.01% |
| [f01851482](https://filfox.info/en/address/f01851482)       |                 Busan, Busan, KR |         383.06 TiB |      7.14% |  383.06 TiB |           0.00% |
| [f01852664](https://filfox.info/en/address/f01852664)       |         Singapore, Singapore, SG |         306.91 TiB |      5.72% |  306.91 TiB |           0.00% |
| [f01882184](https://filfox.info/en/address/f01882184)       |         Singapore, Singapore, SG |         296.03 TiB |      5.52% |  296.03 TiB |           0.00% |
| [f01880047](https://filfox.info/en/address/f01880047)       |         Singapore, Singapore, SG |         259.88 TiB |      4.84% |  259.88 TiB |           0.00% |
| [f01877571](https://filfox.info/en/address/f01877571)       |         Singapore, Singapore, SG |         253.53 TiB |      4.72% |  253.38 TiB |           0.06% |
| [f01967501](https://filfox.info/en/address/f01967501)`new`  |   Philadelphia, Pennsylvania, US |         192.44 TiB |      3.59% |  192.44 TiB |           0.00% |
| [f01720359](https://filfox.info/en/address/f01720359)       | Heerhugowaard, North Holland, NL |         184.78 TiB |      3.44% |  179.19 TiB |           3.03% |
| [f01938665](https://filfox.info/en/address/f01938665)       |   Sham Shui Po, Sham Shui Po, HK |         172.31 TiB |      3.21% |  170.25 TiB |           1.20% |
| [f01938717](https://filfox.info/en/address/f01938717)       |         Singapore, Singapore, SG |         164.16 TiB |      3.06% |  163.94 TiB |           0.13% |
| [f01878005](https://filfox.info/en/address/f01878005)       |         Singapore, Singapore, SG |         146.69 TiB |      2.73% |  146.19 TiB |           0.34% |
| [f01882177](https://filfox.info/en/address/f01882177)       |         Singapore, Singapore, SG |         142.47 TiB |      2.65% |  142.41 TiB |           0.04% |
| [f01786387](https://filfox.info/en/address/f01786387)       | Heerhugowaard, North Holland, NL |         114.28 TiB |      2.13% |  110.69 TiB |           3.14% |
| [f01157271](https://filfox.info/en/address/f01157271)       |      Sydney, New South Wales, AU |          99.47 TiB |      1.85% |   73.84 TiB |          25.76% |
| [f01208803](https://filfox.info/en/address/f01208803)       |      Sydney, New South Wales, AU |          98.19 TiB |      1.83% |   71.44 TiB |          27.24% |
| [f01771403](https://filfox.info/en/address/f01771403)       | Heerhugowaard, North Holland, NL |          96.50 TiB |      1.80% |   89.53 TiB |           7.22% |
| [f01208154](https://filfox.info/en/address/f01208154)       |      Sydney, New South Wales, AU |          85.19 TiB |      1.59% |   64.31 TiB |          24.50% |
| [f01059489](https://filfox.info/en/address/f01059489)       |                 Plano, Texas, US |          83.31 TiB |      1.55% |   83.31 TiB |           0.00% |
| [f01981059](https://filfox.info/en/address/f01981059)       |            Richardson, Texas, US |          75.78 TiB |      1.41% |   75.78 TiB |           0.00% |
| [f01208632](https://filfox.info/en/address/f01208632)       |      Sydney, New South Wales, AU |          68.84 TiB |      1.28% |   55.09 TiB |          19.97% |
| [f01156835](https://filfox.info/en/address/f01156835)`new`  |      Sydney, New South Wales, AU |          64.47 TiB |      1.20% |   50.75 TiB |          21.28% |
| [f01208189](https://filfox.info/en/address/f01208189)       |      Sydney, New South Wales, AU |          63.25 TiB |      1.18% |   29.69 TiB |          53.06% |
| [f01207874](https://filfox.info/en/address/f01207874)       |      Sydney, New South Wales, AU |          62.69 TiB |      1.17% |   53.91 TiB |          14.01% |
| [f01208042](https://filfox.info/en/address/f01208042)       |      Sydney, New South Wales, AU |          56.38 TiB |      1.05% |   37.19 TiB |          34.04% |
| [f01157249](https://filfox.info/en/address/f01157249)       |      Sydney, New South Wales, AU |          51.56 TiB |      0.96% |   46.25 TiB |          10.30% |
| [f01207954](https://filfox.info/en/address/f01207954)       |      Sydney, New South Wales, AU |          45.97 TiB |      0.86% |   42.44 TiB |           7.68% |
| [f01156883](https://filfox.info/en/address/f01156883)       |      Sydney, New South Wales, AU |          27.81 TiB |      0.52% |   26.63 TiB |           4.27% |
| [f01199430](https://filfox.info/en/address/f01199430)       | Heerhugowaard, North Holland, NL |          27.09 TiB |      0.50% |   24.44 TiB |           9.80% |
| [f01937642](https://filfox.info/en/address/f01937642)`new`  | Heerhugowaard, North Holland, NL |          26.66 TiB |      0.50% |   26.00 TiB |           2.46% |
| [f01156538](https://filfox.info/en/address/f01156538)`new`  |      Sydney, New South Wales, AU |          23.28 TiB |      0.43% |   17.72 TiB |          23.89% |
| [f01206408](https://filfox.info/en/address/f01206408)       |      Sydney, New South Wales, AU |          22.13 TiB |      0.41% |   20.41 TiB |           7.77% |
| [f01908299](https://filfox.info/en/address/f01908299)       |                          Unknown |          20.44 TiB |      0.38% |   20.38 TiB |           0.31% |
| [f01157018](https://filfox.info/en/address/f01157018)       |      Sydney, New South Wales, AU |          20.09 TiB |      0.37% |   20.09 TiB |           0.00% |
| [f01154023](https://filfox.info/en/address/f01154023)       |      Sydney, New South Wales, AU |          19.84 TiB |      0.37% |   18.63 TiB |           6.14% |
| [f01156975](https://filfox.info/en/address/f01156975)       |      Sydney, New South Wales, AU |          18.66 TiB |      0.35% |   18.63 TiB |           0.17% |
| [f01157027](https://filfox.info/en/address/f01157027)       |      Sydney, New South Wales, AU |          18.34 TiB |      0.34% |   18.13 TiB |           1.19% |
| [f022352](https://filfox.info/en/address/f022352)           |                   Oslo, Oslo, NO |          17.25 TiB |      0.32% |   17.06 TiB |           1.09% |
| [f0855584](https://filfox.info/en/address/f0855584)`new`    |            Lincoln, Nebraska, US |          11.28 TiB |      0.21% |   11.28 TiB |           0.00% |
| [f01156901](https://filfox.info/en/address/f01156901)       |      Sydney, New South Wales, AU |          10.25 TiB |      0.19% |   10.22 TiB |           0.30% |
| [f01864434](https://filfox.info/en/address/f01864434)       |      Sydney, New South Wales, AU |           3.22 TiB |      0.06% |    3.22 TiB |           0.00% |
| [f01878201](https://filfox.info/en/address/f01878201)       |           Hangzhou, Zhejiang, CN |         288.00 GiB |      0.01% |  288.00 GiB |           0.00% |

![Provider Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/340/1671095165638.png)
### Deal Data Replication
The below table shows how each many unique data are replicated across storage providers.
- No more than 25% of unique data are stored with less than 4 providers.

✔️ Data replication looks healthy.

| Unique Data Size | Total Deals Made | Number of Providers | Deal Percentage |
| ---------------: | ---------------: | ------------------: | --------------: |
|        24.23 TiB |        24.64 TiB |                   1 |           0.46% |
|       181.50 TiB |       372.09 TiB |                   2 |           6.93% |
|       246.63 TiB |       787.13 TiB |                   3 |          14.67% |
|       209.66 TiB |       881.63 TiB |                   4 |          16.43% |
|       176.41 TiB |       935.84 TiB |                   5 |          17.44% |
|       121.13 TiB |       761.09 TiB |                   6 |          14.18% |
|       103.31 TiB |       755.91 TiB |                   7 |          14.08% |
|        62.81 TiB |       530.47 TiB |                   8 |           9.88% |
|        24.78 TiB |       236.19 TiB |                   9 |           4.40% |
|         7.03 TiB |        75.06 TiB |                  10 |           1.40% |
|       640.00 GiB |         7.03 TiB |                  11 |           0.13% |

![Replication Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/340/1671095166398.png)
### Deal Data Shared with other Clients
The below table shows how many unique data are shared with other clients.
Usually different applications owns different data and should not resolve to the same CID.

⚠️ CID sharing has been observed.

| Other Client                                                                                                          | Application                                                                                                     | Total Deals Affected | Unique CIDs |        Verifier |
| :-------------------------------------------------------------------------------------------------------------------- | :-------------------------------------------------------------------------------------------------------------- | -------------------: | ----------: | --------------: |
| [f1ws3n5tuxtyg26lraqkjirz7qon7y7ckju7hhmii](https://filfox.info/en/address/f1ws3n5tuxtyg26lraqkjirz7qon7y7ckju7hhmii) | [Tech Greedy Inc](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/335)                  |             4.47 PiB |      13,100 | LDN v3 multisig |
| [f1pc5usvsbfgxxbq7c7quhhg6k7l6y5reiwqr3noy](https://filfox.info/en/address/f1pc5usvsbfgxxbq7c7quhhg6k7l6y5reiwqr3noy) | [Speedium network](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/403)                 |           245.34 TiB |       4,493 | LDN v3 multisig |
| [f1z7jogzx4x42wtilzb4lu6iotlad5rptt2acbzpi](https://filfox.info/en/address/f1z7jogzx4x42wtilzb4lu6iotlad5rptt2acbzpi) | [Speedium network](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/339)                 |             5.91 TiB |           9 | LDN v3 multisig |
| [f17ia7m5mvizrdug3sqtevqw3tifiqvxqr3kdaeuq](https://filfox.info/en/address/f17ia7m5mvizrdug3sqtevqw3tifiqvxqr3kdaeuq) | [ Speedium NetworkSpeedium Network](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/77) |           832.00 GiB |           9 |        LDN # 77 |

[^1]: To manually trigger this report, add a comment with text `checker:manualTrigger`

**Comment by cryptowhizzard** [comment]
Closing issue as total datacap has been reached.

**Comment by data-programs** [comment]
<img width="32" alt="KYC" Verified src="https://stable.filplus.storage/images/filplus-kyc-verified-badge.png"/>

This user’s identity has been verified through [filplus.storage](https://filplus.storage)
