### ISSUE TITLE
Brazil Data Cube - Speedium

### ISSUE THREAD

**Issue by cryptowhizzard** [filecoin-project/filecoin-plus-large-datasets#341]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Speedium network
- Website / Social Media: www.speedium.nl
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 3 PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 300 TiB
- On-chain address for first allocation: f1c4tsscftr3a6ljujjn7zmfpd6q5vab62ylqxrmi

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Speedium / Dcent has engaged in Slingshot starting 2.6. We have successfully stored more than 15 differerent datasets with 20+ different miners.

```

What is the primary source of funding for this project?
```
Company account
```

What other projects/ecosystem stakeholders is this project associated with?
```
Slingshot competition hosted by Protocol Labs
```

## Use-case details

Describe the data being stored onto Filecoin
```
Earth observation (EO) data cubes produced from analysis-ready data (ARD) of CBERS-4, Sentinel-2 A/B and Landsat-8 satellite images for Brazil. The datacubes are regular in time and use a hierarchical tiling system. Further details are described in [Ferreira et al.](https://www.mdpi.com/2072-4292/12/24/4033)
```

Where was the data in this dataset sourced from?
```
AWS
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://registry.opendata.aws/brazil-data-cubes
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes.
```

What is the expected retrieval frequency for this data?
```
Multiple times p/y
```

For how long do you plan to keep this dataset stored on Filecoin?
```
18 months or longer
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
EU / US / Australia
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
The data will be transferred both offline and online.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We have a few providers who have been working with us during Slingshot Restore program and we'd like to continue working with them for ongoing Slingshot competition.
```

How will you be distributing deals across storage providers?
```
Max 2 copy's per storage provider if stored on different miners / locations.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, we have the resources.
```

**Comment by dkkapur** [comment]
@cryptowhizzard see https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/348#issuecomment-1123004278 when you get a chance. Using separate address here would help with Slingshot tracking too. Please update if this is possible! Thank you!

**Comment by galen-mcandrew** [comment]
## Multisig Notary requested
#### Total DataCap requested 
> 3PiB
#### Expected weekly DataCap usage rate 
> 300TiB

**Comment by cryptowhizzard** [comment]
@dkkapur - > Done.

**Comment by MegTei** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedekus2ndvluvatcbdsgmyg7jdmencpaw5izswzl36p2n5peoqw6o 
#### Address 
> f1c4tsscftr3a6ljujjn7zmfpd6q5vab62ylqxrmi
#### Datacap Allocated
> 150.00TiB
#### Signer Address
> f1ystxl2ootvpirpa7ebgwl7vlhwkbx2r4zjxwe5i
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedekus2ndvluvatcbdsgmyg7jdmencpaw5izswzl36p2n5peoqw6o

**Comment by s0nik42** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebtbm7h7aszqbsly3bpal5jraffkiv2k5gouojpsj2msxku3v7gh4 
#### Address 
> f1c4tsscftr3a6ljujjn7zmfpd6q5vab62ylqxrmi
#### Datacap Allocated
> 150.00TiB
#### Signer Address
> f1wxhnytjmklj2czezaqcfl7eb4nkgmaxysnegwii
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebtbm7h7aszqbsly3bpal5jraffkiv2k5gouojpsj2msxku3v7gh4

**Comment by 1475Notary** [comment]
![image](https://user-images.githubusercontent.com/103022086/180722671-e7044310-eaf1-4bcf-84c3-0577a9b7e930.png)

Flagging here.

**Comment by cryptowhizzard** [comment]
@1475Notary 

Thanks for your input. This is because the first allocation is small. Only one of the providers have start sealing this set yet. Over the course of next weeks there will be more diversity.

**Comment by 1475Notary** [comment]
If  the stats can be verifed in the last round, why do we need so many rounds of allocation?

Curious about which notaries will sign such an application @galen-mcandrew @dkkapur

**Comment by s0nik42** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaj7shtppgidphs3vb2pttzi2k3rlv2jktdpe2sjmltci6tl7qmu2 
#### Address 
> f1c4tsscftr3a6ljujjn7zmfpd6q5vab62ylqxrmi
#### Datacap Allocated
> 300.00TiB
#### Signer Address
> f1wxhnytjmklj2czezaqcfl7eb4nkgmaxysnegwii
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaj7shtppgidphs3vb2pttzi2k3rlv2jktdpe2sjmltci6tl7qmu2

**Comment by Reiers** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedpdx4lzygzsvt7blaoesfh2tnzmhnnee47t23lirw4c53lwun2q2 
#### Address 
> f1c4tsscftr3a6ljujjn7zmfpd6q5vab62ylqxrmi
#### Datacap Allocated
> 300.00TiB
#### Signer Address
> f1oz43ckvmtxmmsfzqm6bpnemqlavz4ifyl524chq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedpdx4lzygzsvt7blaoesfh2tnzmhnnee47t23lirw4c53lwun2q2

**Comment by Chris00618** [comment]
Could you disclose the owner of f01720359? Why does it get such a centralized allocation?

**Comment by cryptowhizzard** [comment]
Hello @Chris00618 

As already explained above this is because the first allocation is small and only some of the providers have start sealing this dataset yet. Over the course of next weeks there will be more diversity as not everyone is sealing at the same speed.

**Comment by kernelogic** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedr2ozmbxkv5ot652hxlpgo2n3tnzrdcrgblq4wxqvzuccnziuewu 
#### Address 
> f1c4tsscftr3a6ljujjn7zmfpd6q5vab62ylqxrmi
#### Datacap Allocated
> 600.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedr2ozmbxkv5ot652hxlpgo2n3tnzrdcrgblq4wxqvzuccnziuewu

**Comment by Reiers** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedfftryygeeneduymrsrc4bamkkpiv2b3uaoewxugktwowqwqnxjm 
#### Address 
> f1c4tsscftr3a6ljujjn7zmfpd6q5vab62ylqxrmi
#### Datacap Allocated
> 600.00TiB
#### Signer Address
> f1oz43ckvmtxmmsfzqm6bpnemqlavz4ifyl524chq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedfftryygeeneduymrsrc4bamkkpiv2b3uaoewxugktwowqwqnxjm

**Comment by raghavrmadya** [comment]
## DataCap Allocation requested

### Request number 4
#### Multisig Notary address
> f01858410

#### Client address
> f1c4tsscftr3a6ljujjn7zmfpd6q5vab62ylqxrmi

#### DataCap allocation requested
> 1.17PiB

**Comment by raghavrmadya** [comment]
## DataCap Allocation requested

### Request number 4
#### Multisig Notary address
> f01858410

#### Client address
> f1c4tsscftr3a6ljujjn7zmfpd6q5vab62ylqxrmi

#### DataCap allocation requested
> 1.17PiB

**Comment by kernelogic** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceavoa53tgjnjm7eriff6nzavqravx6lbyv26qdbogkdxjomabsfv6 
#### Address 
> f1c4tsscftr3a6ljujjn7zmfpd6q5vab62ylqxrmi
#### Datacap Allocated
> 1.17PiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceavoa53tgjnjm7eriff6nzavqravx6lbyv26qdbogkdxjomabsfv6

**Comment by xingjitansuo** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecqjfbki3t6ckmelqy2h73hudr5o2wbqx6adp3jhpkyw7vqovir5y 
#### Address 
> f1c4tsscftr3a6ljujjn7zmfpd6q5vab62ylqxrmi
#### Datacap Allocated
> 1.17PiB
#### Signer Address
> f1a2lia2cwwekeubwo4nppt4v4vebxs2frozarz3q
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecqjfbki3t6ckmelqy2h73hudr5o2wbqx6adp3jhpkyw7vqovir5y

**Comment by s0nik42** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedeherdgmseeeq5gigjode4wdmru6k2f32tddkcopa32gdu7dmcmw 
#### Address 
> f1c4tsscftr3a6ljujjn7zmfpd6q5vab62ylqxrmi
#### Datacap Allocated
> 1.17PiB
#### Signer Address
> f1wxhnytjmklj2czezaqcfl7eb4nkgmaxysnegwii
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedeherdgmseeeq5gigjode4wdmru6k2f32tddkcopa32gdu7dmcmw

**Comment by filplus-checker** [comment]
## DataCap and CID Checker Report[^1]
 - Organization: `Speedium network`
 - Client: `f1c4tsscftr3a6ljujjn7zmfpd6q5vab62ylqxrmi`
### Storage Provider Distribution
The below table shows the distribution of storage providers that have stored data for this client.

If this is the first time a provider takes verified deal, it will be marked as `new`.

For most of the datacap application, below restrictions should apply.
 - Storage provider should not exceed 25% of total datacap.
 - Storage provider should not be storing duplicate data for more than 20%.
 - Storage provider should have published its public IP address.
 - All storage providers should be located in different regions.

⚠️ 31.87% of total deal sealed by [f01878201](https://filfox.info/en/address/f01878201) are duplicate data.

⚠️ 27.06% of total deal sealed by [f01156538](https://filfox.info/en/address/f01156538) are duplicate data.

⚠️ 21.05% of total deal sealed by [f01156835](https://filfox.info/en/address/f01156835) are duplicate data.

⚠️ 42.42% of total deal sealed by [f01157018](https://filfox.info/en/address/f01157018) are duplicate data.

| Provider                                                    |                         Location | Total Deals Sealed | Percentage | Unique Data | Duplicate Deals |
| :---------------------------------------------------------- | -------------------------------: | -----------------: | ---------: | ----------: | --------------: |
| [f01878201](https://filfox.info/en/address/f01878201)       |           Hangzhou, Zhejiang, CN |         162.59 TiB |     10.79% |  110.78 TiB |          31.87% |
| [f01877571](https://filfox.info/en/address/f01877571)       |         Singapore, Singapore, SG |         129.20 TiB |      8.58% |  129.20 TiB |           0.00% |
| [f099608](https://filfox.info/en/address/f099608)           |                   Riga, Riga, LV |         128.92 TiB |      8.56% |  125.55 TiB |           2.62% |
| [f01902461](https://filfox.info/en/address/f01902461)       |             Zhengzhou, Henan, CN |         123.34 TiB |      8.19% |  123.34 TiB |           0.00% |
| [f01911083](https://filfox.info/en/address/f01911083)`new`  |             Tuusula, Uusimaa, FI |         122.02 TiB |      8.10% |  122.02 TiB |           0.00% |
| [f01928520](https://filfox.info/en/address/f01928520)`new`  |         Maywood Park, Oregon, US |         117.55 TiB |      7.80% |  117.55 TiB |           0.00% |
| [f01944347](https://filfox.info/en/address/f01944347)       |         Maywood Park, Oregon, US |         115.27 TiB |      7.65% |  115.23 TiB |           0.03% |
| [f01929565](https://filfox.info/en/address/f01929565)       |      Sydney, New South Wales, AU |         112.41 TiB |      7.46% |  112.41 TiB |           0.00% |
| [f01864434](https://filfox.info/en/address/f01864434)       |      Sydney, New South Wales, AU |          93.95 TiB |      6.24% |   93.95 TiB |           0.00% |
| [f01720359](https://filfox.info/en/address/f01720359)       | Heerhugowaard, North Holland, NL |          78.05 TiB |      5.18% |   77.95 TiB |           0.12% |
| [f01059489](https://filfox.info/en/address/f01059489)`new`  |                 Plano, Texas, US |          50.61 TiB |      3.36% |   50.61 TiB |           0.00% |
| [f022352](https://filfox.info/en/address/f022352)           |                   Oslo, Oslo, NO |          44.69 TiB |      2.97% |   44.66 TiB |           0.07% |
| [f01780412](https://filfox.info/en/address/f01780412)`new`  |                 Plano, Texas, US |          43.94 TiB |      2.92% |   42.84 TiB |           2.49% |
| [f01771403](https://filfox.info/en/address/f01771403)       | Heerhugowaard, North Holland, NL |          27.03 TiB |      1.79% |   26.81 TiB |           0.81% |
| [f01824635](https://filfox.info/en/address/f01824635)       |          Antwerpen, Flanders, BE |          25.16 TiB |      1.67% |   25.16 TiB |           0.00% |
| [f01786387](https://filfox.info/en/address/f01786387)       | Heerhugowaard, North Holland, NL |          18.28 TiB |      1.21% |   18.28 TiB |           0.00% |
| [f01208154](https://filfox.info/en/address/f01208154)       |      Sydney, New South Wales, AU |          14.63 TiB |      0.97% |   14.47 TiB |           1.07% |
| [f01208632](https://filfox.info/en/address/f01208632)       |      Sydney, New South Wales, AU |          14.47 TiB |      0.96% |   14.47 TiB |           0.00% |
| [f01208042](https://filfox.info/en/address/f01208042)       |      Sydney, New South Wales, AU |          12.84 TiB |      0.85% |   12.84 TiB |           0.00% |
| [f01207954](https://filfox.info/en/address/f01207954)       |      Sydney, New South Wales, AU |          12.16 TiB |      0.81% |   12.09 TiB |           0.51% |
| [f01208803](https://filfox.info/en/address/f01208803)       |      Sydney, New South Wales, AU |           9.88 TiB |      0.66% |    9.75 TiB |           1.27% |
| [f01208189](https://filfox.info/en/address/f01208189)       |      Sydney, New South Wales, AU |           9.44 TiB |      0.63% |    9.41 TiB |           0.33% |
| [f0399610](https://filfox.info/en/address/f0399610)         |              Kyiv, Kyiv City, UA |           8.03 TiB |      0.53% |    8.03 TiB |           0.00% |
| [f01206408](https://filfox.info/en/address/f01206408)       |      Sydney, New South Wales, AU |           5.84 TiB |      0.39% |    5.84 TiB |           0.00% |
| [f01207874](https://filfox.info/en/address/f01207874)       |      Sydney, New South Wales, AU |           3.94 TiB |      0.26% |    3.94 TiB |           0.00% |
| [f01156883](https://filfox.info/en/address/f01156883)       |      Sydney, New South Wales, AU |           2.97 TiB |      0.20% |    2.44 TiB |          17.89% |
| [f01154023](https://filfox.info/en/address/f01154023)       |      Sydney, New South Wales, AU |           2.69 TiB |      0.18% |    2.31 TiB |          13.95% |
| [f01156538](https://filfox.info/en/address/f01156538)       |      Sydney, New South Wales, AU |           2.66 TiB |      0.18% |    1.94 TiB |          27.06% |
| [f01157271](https://filfox.info/en/address/f01157271)       |      Sydney, New South Wales, AU |           2.63 TiB |      0.17% |    2.56 TiB |           2.38% |
| [f01157027](https://filfox.info/en/address/f01157027)`new`  |      Sydney, New South Wales, AU |           2.59 TiB |      0.17% |    2.47 TiB |           4.82% |
| [f01156835](https://filfox.info/en/address/f01156835)       |      Sydney, New South Wales, AU |           2.38 TiB |      0.16% |    1.88 TiB |          21.05% |
| [f01156901](https://filfox.info/en/address/f01156901)`new`  |      Sydney, New South Wales, AU |           2.16 TiB |      0.14% |    1.84 TiB |          14.49% |
| [f01156975](https://filfox.info/en/address/f01156975)`new`  |      Sydney, New South Wales, AU |           2.16 TiB |      0.14% |    1.78 TiB |          17.39% |
| [f01157018](https://filfox.info/en/address/f01157018)`new`  |      Sydney, New South Wales, AU |           2.06 TiB |      0.14% |    1.19 TiB |          42.42% |

![Provider Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/341/1671095197028.png)
### Deal Data Replication
The below table shows how each many unique data are replicated across storage providers.
- No more than 25% of unique data are stored with less than 4 providers.

✔️ Data replication looks healthy.

| Unique Data Size | Total Deals Made | Number of Providers | Deal Percentage |
| ---------------: | ---------------: | ------------------: | --------------: |
|        64.00 GiB |       320.00 GiB |                   5 |           0.02% |
|       704.00 GiB |         4.97 TiB |                   7 |           0.33% |
|         4.30 TiB |        36.13 TiB |                   8 |           2.40% |
|        13.19 TiB |       124.91 TiB |                   9 |           8.29% |
|        25.28 TiB |       267.06 TiB |                  10 |          17.73% |
|        38.16 TiB |       442.28 TiB |                  11 |          29.36% |
|        27.97 TiB |       348.50 TiB |                  12 |          23.13% |
|        15.81 TiB |       208.41 TiB |                  13 |          13.83% |
|         5.06 TiB |        71.13 TiB |                  14 |           4.72% |
|       192.00 GiB |         2.81 TiB |                  15 |           0.19% |

![Replication Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/341/1671095197729.png)
### Deal Data Shared with other Clients
The below table shows how many unique data are shared with other clients.
Usually different applications owns different data and should not resolve to the same CID.

⚠️ CID sharing has been observed.

| Other Client                                                                                                          | Application                                                                                     | Total Deals Affected | Unique CIDs |        Verifier |
| :-------------------------------------------------------------------------------------------------------------------- | :---------------------------------------------------------------------------------------------- | -------------------: | ----------: | --------------: |
| [f1z7jogzx4x42wtilzb4lu6iotlad5rptt2acbzpi](https://filfox.info/en/address/f1z7jogzx4x42wtilzb4lu6iotlad5rptt2acbzpi) | [Speedium network](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/339) |            85.94 TiB |       1,913 | LDN v3 multisig |

[^1]: To manually trigger this report, add a comment with text `checker:manualTrigger`

**Comment by data-programs** [comment]
<img width="32" alt="KYC" Verified src="https://stable.filplus.storage/images/filplus-kyc-verified-badge.png"/>

This user’s identity has been verified through [filplus.storage](https://filplus.storage)
