### ISSUE TITLE
[DataCap Allocation] - Appstest

### ISSUE THREAD

**Issue by Aitester66** [filecoin-project/filecoin-plus-large-datasets#346]
---
name: Large Dataset Notary application
about: Clients should use this application form to request a DataCap allocation via a LDN for a dataset
title: "[DataCap Application] - Appstest
labels: 'application, Phase: Diligence'
assignees: ''

---
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Appstest
- Website / Social Media: https://www.appstest.cn/ 
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 200TiB
- On-chain address for first allocation: f1ibuglt2lzlyf7vnmtzmuykcfgl2pn2fxym5dibi

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
AppsTest is China's new generation of information technology products AI automation test tool chain core technology provider. With the help of home-made automated testing tools, the company provides a complete set of high-efficiency and high-quality software testing solutions for communication, energy, transportation, finance, logistics, manufacturing, e-government, smart city and other industry information fields, aiming to break the monopoly of developed countries and enhance the core competitiveness of China's underlying information technology.
```

What is the primary source of funding for this project?
```
From company's income.
```

What other projects/ecosystem stakeholders is this project associated with?
```
No.
```

## Use-case details

Describe the data being stored onto Filecoin
```
These are test data from our system. Approximate 5PiB.
```

Where was the data in this dataset sourced from?
```
The data are mainly from our customers involving communications, energy, transportation, finance, logistics, manufacturing, e-government, smart city and other industry information fields.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
Yes of course. 
![apptester](https://user-images.githubusercontent.com/105147082/167575046-c05dbeeb-1606-41ab-86b4-afe1745c9126.png)
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
We confirm that our dataset is public.
```

What is the expected retrieval frequency for this data?
```
1-2 times a year. 
```

For how long do you plan to keep this dataset stored on Filecoin?
```
720 days or more.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
China Only
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
  we are ready for distributing data online. At the same time, we will prepare some hard-disks for offline transfer.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We've contacted some Asia storage providers on slack and telegram before, they need datacap to give us a low price. If PL can find more storage providers, we could cooperate with them.
```

How will you be distributing deals across storage providers?
```
Less than 25% data for every storage providers. 
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, we have.  We have lots of non-public data, too. We are willing to making more deals in the future if Filecoin can accept non-public data!
```

**Comment by dannyob** [comment]
As we mentioned in the Governance call, it'd be great if you could post the presentation, and list the SPs you're thinking of using.

**Comment by Aitester66** [comment]
Please see as below:
[Appstest.pdf](https://github.com/filecoin-project/filecoin-plus-large-datasets/files/8712779/Appstest.pdf)
SPs we have communicated with in the early stage and are interested in include hashcow, bfcloud, linkfly, Westlake, etc.

**Comment by Aitester66** [comment]
Please see as below:
[Appstest.pdf](https://github.com/filecoin-project/filecoin-plus-large-datasets/files/8712779/Appstest.pdf)
SPs we have communicated with in the early stage and are interested in include hashcat, bfcloud, linkfly, Westlake, etc.

**Comment by Aitester66** [comment]
Please speed up the review so that we can see the progress. Thanks

**Comment by Aitester66** [comment]
@Kevin-FF-USA @galen-mcandrew @dkkapur

**Comment by Sunnyiscoming** [comment]
@Aitester66  Can you provide more data sample or derailed data source to indicate you have 5 PB already?

**Comment by Aitester66** [comment]
Of course, please refer to this type of recording file for catching bugs:
https://user-images.githubusercontent.com/105147082/172666510-31eaa67d-1984-4075-ab75-f6c3fc60b827.mp4

**Comment by dkkapur** [comment]
Can you email [filplus@fil.org](mailto:filplus@fil.org) with your official work email so we can share this with notaries as a form of proof that you represent this organization?

**Comment by Aitester66** [comment]
I tried to send mail to that address several times but failed. Is there any other notary can help?

**Comment by MetaWaveInfo** [comment]
@Aitester66  We're a member of this round of notaries,  would like to share and forward.  
You can try metawaveinfo@gmail.com.

**Comment by Aitester66** [comment]
Thanks, it has be done, please have a check.

**Comment by Sunnyiscoming** [comment]
@MetaWaveInfo Have you received that? If so, please share that on this issue.

**Comment by MetaWaveInfo** [comment]
![image](https://user-images.githubusercontent.com/100760052/175329455-15b42f5f-23f5-41f7-8ec1-cdcee748f0c8.png)

**Comment by galen-mcandrew** [comment]
## Datacap Request Trigger
#### Total DataCap requested 
> 5PiB
#### Expected weekly DataCap usage rate 
> 200TiB 
#### Client address
> f1ibuglt2lzlyf7vnmtzmuykcfgl2pn2fxym5dibi

**Comment by MetaWaveInfo** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec7pgnwmnskj6kxrsnu3fp5kbhtvix3bvzkrrp5qltprje7vjx2hu 
#### Address 
> f1ibuglt2lzlyf7vnmtzmuykcfgl2pn2fxym5dibi
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1ktlkcxnmzxcdaoqfsunrg3vocfbmgv4n3mrn74a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec7pgnwmnskj6kxrsnu3fp5kbhtvix3bvzkrrp5qltprje7vjx2hu

**Comment by swatchliu** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecosqackuevioct367begep3sawar3srwinwq5l3i6argcrgbcsii 
#### Address 
> f1ibuglt2lzlyf7vnmtzmuykcfgl2pn2fxym5dibi
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1yh6q3nmsg7i2sys7f7dexcuajgoweudcqj2chfi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecosqackuevioct367begep3sawar3srwinwq5l3i6argcrgbcsii

**Comment by BigD-Exchange** [comment]
@Aitester66 Hi! Great to see you have gotten approval for DataCap. If you are looking for more storage providers to store these data or have any questions, please visit #bigdata-exchange on Filecoin Slack or reply here. 

We have strong demand from a diverse group of SPs, who are actively looking to onboard more data.

**Comment by MetaWaveInfo** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacediijf56dy3wfk34lpo5wwszg2f5z62cudq372yuuix6ee3xsvssu 
#### Address 
> f1ibuglt2lzlyf7vnmtzmuykcfgl2pn2fxym5dibi
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1ktlkcxnmzxcdaoqfsunrg3vocfbmgv4n3mrn74a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacediijf56dy3wfk34lpo5wwszg2f5z62cudq372yuuix6ee3xsvssu

**Comment by UnionLabs2020** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec6kvmbk6r4jmcvk453nymq3527gdieirw7dukk5sue7dsb72cqu6 
#### Address 
> f1ibuglt2lzlyf7vnmtzmuykcfgl2pn2fxym5dibi
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f17xdri3wunqgld7dm23e4f3eqsntjakwc47xjo6i
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec6kvmbk6r4jmcvk453nymq3527gdieirw7dukk5sue7dsb72cqu6

**Comment by swatchliu** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebiukkny345lxi7vwpfsqnpr7k2gwi3onecqklvoomcwal7sytp3y 
#### Address 
> f1ibuglt2lzlyf7vnmtzmuykcfgl2pn2fxym5dibi
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1yh6q3nmsg7i2sys7f7dexcuajgoweudcqj2chfi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebiukkny345lxi7vwpfsqnpr7k2gwi3onecqklvoomcwal7sytp3y

**Comment by Fenbushi-Filecoin** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecabzcljwvlxnb36k7rbz7sh6ckc2wiuahxwzut2dmsd4clyafpww 
#### Address 
> f1ibuglt2lzlyf7vnmtzmuykcfgl2pn2fxym5dibi
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1yqydpmqb5en262jpottko2kd65msajax7fi4rmq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecabzcljwvlxnb36k7rbz7sh6ckc2wiuahxwzut2dmsd4clyafpww

**Comment by UnionLabs2020** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedbxvzlgiek5iqd7utevrbgdxxi6wkdhfwsdjllaxbgnerseilcae 
#### Address 
> f1ibuglt2lzlyf7vnmtzmuykcfgl2pn2fxym5dibi
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f17xdri3wunqgld7dm23e4f3eqsntjakwc47xjo6i
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedbxvzlgiek5iqd7utevrbgdxxi6wkdhfwsdjllaxbgnerseilcae

**Comment by stcouldlisa** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebbb2psf2ims5oellxxw5oaig4c3pjhv2bmebkd54ce6gzimogqms 
#### Address 
> f1ibuglt2lzlyf7vnmtzmuykcfgl2pn2fxym5dibi
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1jvvltduw35u6inn5tr4nfualyd42bh3vjtylgci
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebbb2psf2ims5oellxxw5oaig4c3pjhv2bmebkd54ce6gzimogqms

**Comment by MetaWaveInfo** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedy2fvqgcz7lqamm6jq4cuxmarrmp4briinb25hgvgorzdtmvkbpq 
#### Address 
> f1ibuglt2lzlyf7vnmtzmuykcfgl2pn2fxym5dibi
#### Datacap Allocated
> 1.56PiB
#### Signer Address
> f1ktlkcxnmzxcdaoqfsunrg3vocfbmgv4n3mrn74a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedy2fvqgcz7lqamm6jq4cuxmarrmp4briinb25hgvgorzdtmvkbpq

**Comment by swatchliu** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebkwvjji7e3rjyn4acdpi2pol2uffsflxgizca7ogqfyzhfqzbhqi 
#### Address 
> f1ibuglt2lzlyf7vnmtzmuykcfgl2pn2fxym5dibi
#### Datacap Allocated
> 1.56PiB
#### Signer Address
> f1yh6q3nmsg7i2sys7f7dexcuajgoweudcqj2chfi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebkwvjji7e3rjyn4acdpi2pol2uffsflxgizca7ogqfyzhfqzbhqi

**Comment by UnionLabs2020** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebpuf76ygqaulgljddge5e6jnipjpajh3voy7ao66onii5qxep5gc 
#### Address 
> f1ibuglt2lzlyf7vnmtzmuykcfgl2pn2fxym5dibi
#### Datacap Allocated
> 1.56PiB
#### Signer Address
> f17xdri3wunqgld7dm23e4f3eqsntjakwc47xjo6i
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebpuf76ygqaulgljddge5e6jnipjpajh3voy7ao66onii5qxep5gc

**Comment by MetaWaveInfo** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceajs3afhmkjfkch7vznuvxfofi6vtm3ai2dozdas3cgshgswhf47c 
#### Address 
> f1ibuglt2lzlyf7vnmtzmuykcfgl2pn2fxym5dibi
#### Datacap Allocated
> 1.56PiB
#### Signer Address
> f1ktlkcxnmzxcdaoqfsunrg3vocfbmgv4n3mrn74a
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceajs3afhmkjfkch7vznuvxfofi6vtm3ai2dozdas3cgshgswhf47c

**Comment by filplus-checker** [comment]
## DataCap and CID Checker Report[^1]
 - Organization: `Appstest`
 - Client: `f1ibuglt2lzlyf7vnmtzmuykcfgl2pn2fxym5dibi`
### Storage Provider Distribution
The below table shows the distribution of storage providers that have stored data for this client.

If this is the first time a provider takes verified deal, it will be marked as `new`.

For most of the datacap application, below restrictions should apply.
 - Storage provider should not exceed 25% of total datacap.
 - Storage provider should not be storing duplicate data for more than 20%.
 - Storage provider should have published its public IP address.
 - All storage providers should be located in different regions.

⚠️ 89.92% of total deal sealed by [f01933849](https://filfox.info/en/address/f01933849) are duplicate data.

⚠️ [f01933849](https://filfox.info/en/address/f01933849) has unknown IP location.

⚠️ 79.29% of total deal sealed by [f01926768](https://filfox.info/en/address/f01926768) are duplicate data.

⚠️ [f01926768](https://filfox.info/en/address/f01926768) has unknown IP location.

⚠️ 72.33% of total deal sealed by [f01688](https://filfox.info/en/address/f01688) are duplicate data.

⚠️ [f01688](https://filfox.info/en/address/f01688) has unknown IP location.

⚠️ 72.51% of total deal sealed by [f01927578](https://filfox.info/en/address/f01927578) are duplicate data.

⚠️ [f01927578](https://filfox.info/en/address/f01927578) has unknown IP location.

⚠️ 80.76% of total deal sealed by [f01926777](https://filfox.info/en/address/f01926777) are duplicate data.

⚠️ [f01926777](https://filfox.info/en/address/f01926777) has unknown IP location.

⚠️ 76.93% of total deal sealed by [f01926749](https://filfox.info/en/address/f01926749) are duplicate data.

⚠️ [f01926749](https://filfox.info/en/address/f01926749) has unknown IP location.

⚠️ 70.60% of total deal sealed by [f01927574](https://filfox.info/en/address/f01927574) are duplicate data.

⚠️ [f01927574](https://filfox.info/en/address/f01927574) has unknown IP location.

⚠️ 87.09% of total deal sealed by [f01946714](https://filfox.info/en/address/f01946714) are duplicate data.

⚠️ [f01946714](https://filfox.info/en/address/f01946714) has unknown IP location.

⚠️ 79.93% of total deal sealed by [f01520](https://filfox.info/en/address/f01520) are duplicate data.

⚠️ [f01520](https://filfox.info/en/address/f01520) has unknown IP location.

⚠️ 68.98% of total deal sealed by [f01843749](https://filfox.info/en/address/f01843749) are duplicate data.

⚠️ 20.25% of total deal sealed by [f01877862](https://filfox.info/en/address/f01877862) are duplicate data.

⚠️ 68.63% of total deal sealed by [f01841133](https://filfox.info/en/address/f01841133) are duplicate data.

⚠️ 73.88% of total deal sealed by [f01841131](https://filfox.info/en/address/f01841131) are duplicate data.

⚠️ 82.73% of total deal sealed by [f01392600](https://filfox.info/en/address/f01392600) are duplicate data.

⚠️ 75.78% of total deal sealed by [f0103710](https://filfox.info/en/address/f0103710) are duplicate data.

⚠️ [f0103710](https://filfox.info/en/address/f0103710) has unknown IP location.

⚠️ 85.48% of total deal sealed by [f0136399](https://filfox.info/en/address/f0136399) are duplicate data.

⚠️ 50.00% of total deal sealed by [f054464](https://filfox.info/en/address/f054464) are duplicate data.

| Provider                                              |                           Location | Total Deals Sealed | Percentage | Unique Data | Duplicate Deals |
| :---------------------------------------------------- | ---------------------------------: | -----------------: | ---------: | ----------: | --------------: |
| [f01933849](https://filfox.info/en/address/f01933849) |                            Unknown |         343.59 TiB |     20.23% |   34.63 TiB |          89.92% |
| [f01926768](https://filfox.info/en/address/f01926768) |                            Unknown |         203.28 TiB |     11.97% |   42.09 TiB |          79.29% |
| [f01688](https://filfox.info/en/address/f01688)       |                            Unknown |         172.66 TiB |     10.17% |   47.78 TiB |          72.33% |
| [f01927578](https://filfox.info/en/address/f01927578) |                            Unknown |         169.97 TiB |     10.01% |   46.72 TiB |          72.51% |
| [f01926777](https://filfox.info/en/address/f01926777) |                            Unknown |         153.84 TiB |      9.06% |   29.59 TiB |          80.76% |
| [f01926749](https://filfox.info/en/address/f01926749) |                            Unknown |         153.06 TiB |      9.01% |   35.31 TiB |          76.93% |
| [f01927574](https://filfox.info/en/address/f01927574) |                            Unknown |         150.72 TiB |      8.87% |   44.31 TiB |          70.60% |
| [f01946714](https://filfox.info/en/address/f01946714) |                            Unknown |         100.00 TiB |      5.89% |   12.91 TiB |          87.09% |
| [f01520](https://filfox.info/en/address/f01520)       |                            Unknown |          70.06 TiB |      4.13% |   14.06 TiB |          79.93% |
| [f01843749](https://filfox.info/en/address/f01843749) | Hong Kong, Central and Western, HK |          41.81 TiB |      2.46% |   12.97 TiB |          68.98% |
| [f01877862](https://filfox.info/en/address/f01877862) |                   Seoul, Seoul, KR |          25.00 TiB |      1.47% |   19.94 TiB |          20.25% |
| [f01841133](https://filfox.info/en/address/f01841133) |           Singapore, Singapore, SG |          25.00 TiB |      1.47% |    7.84 TiB |          68.63% |
| [f01841131](https://filfox.info/en/address/f01841131) | Hong Kong, Central and Western, HK |          25.00 TiB |      1.47% |    6.53 TiB |          73.88% |
| [f01392600](https://filfox.info/en/address/f01392600) | Hong Kong, Central and Western, HK |          19.00 TiB |      1.12% |    3.28 TiB |          82.73% |
| [f0103710](https://filfox.info/en/address/f0103710)   |                            Unknown |          18.97 TiB |      1.12% |    4.59 TiB |          75.78% |
| [f0136399](https://filfox.info/en/address/f0136399)   | Hong Kong, Central and Western, HK |          18.94 TiB |      1.12% |    2.75 TiB |          85.48% |
| [f054464](https://filfox.info/en/address/f054464)     | Hong Kong, Central and Western, HK |           7.44 TiB |      0.44% |    3.72 TiB |          50.00% |

![Provider Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/346/1671095240822.png)
### Deal Data Replication
The below table shows how each many unique data are replicated across storage providers.
- No more than 25% of unique data are stored with less than 4 providers.

⚠️ 100.00% of deals are for data replicated across less than 4 storage providers.

| Unique Data Size | Total Deals Made | Number of Providers | Deal Percentage |
| ---------------: | ---------------: | ------------------: | --------------: |
|       246.47 TiB |         1.19 PiB |                   1 |          71.96% |
|        61.28 TiB |       476.22 TiB |                   2 |          28.04% |

![Replication Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/346/1671095241471.png)
### Deal Data Shared with other Clients
The below table shows how many unique data are shared with other clients.
Usually different applications owns different data and should not resolve to the same CID.

⚠️ CID sharing has been observed.

| Other Client                                                                                                                                                                                                              | Application                                                                                                            | Total Deals Affected | Unique CIDs |        Verifier |
| :------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ | :--------------------------------------------------------------------------------------------------------------------- | -------------------: | ----------: | --------------: |
| [f127l5waa4pw6k3sm4e7wxevc4fe5uz7dyt4mxa3i](https://filfox.info/en/address/f127l5waa4pw6k3sm4e7wxevc4fe5uz7dyt4mxa3i)                                                                                                     | `Pangod`                                                                                                               |           501.80 TiB |       3,054 | LDN v3 multisig |
| [f1rkmhotssjif6ucrosls7oewjz6pr2v2eygfjyui](https://filfox.info/en/address/f1rkmhotssjif6ucrosls7oewjz6pr2v2eygfjyui)                                                                                                     | `Weipaitang`                                                                                                           |           391.59 TiB |       2,834 | LDN v3 multisig |
| [f1znd7uramgqquelcgefo5xgozopd3nga73hhywpy](https://filfox.info/en/address/f1znd7uramgqquelcgefo5xgozopd3nga73hhywpy)                                                                                                     | [BotSmart ](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/373)                               |           142.44 TiB |         802 | LDN v3 multisig |
| [f162jayw3utjlbp5ae6ssqghm5jrl3js32dbmnfja](https://filfox.info/en/address/f162jayw3utjlbp5ae6ssqghm5jrl3js32dbmnfja)                                                                                                     | ``                                                                                                                     |           113.59 TiB |         737 |       LDN # 121 |
| [f1wr6rwwqckh6um2hynaym2t4mniev5b675kbf5ni](https://filfox.info/en/address/f1wr6rwwqckh6um2hynaym2t4mniev5b675kbf5ni)                                                                                                     | [Ctrip Global Shopping](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/303)                   |           101.47 TiB |       1,057 | LDN v3 multisig |
| [f1xwmnlen7j7qlkktm3oqggzcbrxp6cvqnkd2wipa](https://filfox.info/en/address/f1xwmnlen7j7qlkktm3oqggzcbrxp6cvqnkd2wipa)                                                                                                     | ``                                                                                                                     |            65.98 TiB |         663 |       LDN # 121 |
| [f1ugo3abkmmb4pb2atxz5oqqgwsd27b4p6k52f2va](https://filfox.info/en/address/f1ugo3abkmmb4pb2atxz5oqqgwsd27b4p6k52f2va)                                                                                                     | [Yuepass Technology Company Limited](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/429)      |            34.16 TiB |         317 | LDN v3 multisig |
| [f1cf2pp6bgu6vvxfuau6bsmiibhrc7v3gvjsyseay](https://filfox.info/en/address/f1cf2pp6bgu6vvxfuau6bsmiibhrc7v3gvjsyseay)                                                                                                     | [Public Data\-FlyBrain](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1013)                  |            29.50 TiB |         175 | LDN v3 multisig |
| [f1csetl7nor3qie2cehx7axf2ai3nedmowj53xwsa](https://filfox.info/en/address/f1csetl7nor3qie2cehx7axf2ai3nedmowj53xwsa)                                                                                                     | [NOAA GOES\-\-\-Piero](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1112)                   |            26.69 TiB |         214 | LDN v3 multisig |
| [f1quofpadzcqlonmz7v3mv7dfqvm5hdztucdsjqsy](https://filfox.info/en/address/f1quofpadzcqlonmz7v3mv7dfqvm5hdztucdsjqsy)                                                                                                     | [HENAN 863 SOFTWARE CO\., LTD](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/468)            |            21.22 TiB |          62 | LDN v3 multisig |
| [f1bb2z36lpq3pnwiiowiraagpzqnpow4bonjacx7a](https://filfox.info/en/address/f1bb2z36lpq3pnwiiowiraagpzqnpow4bonjacx7a)                                                                                                     | [Hola Space](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/362)                              |            20.94 TiB |          67 | LDN v3 multisig |
| [f1a2rdwwor3kq6mv7nveuxhux7rxtj6iyjs7hfswa](https://filfox.info/en/address/f1a2rdwwor3kq6mv7nveuxhux7rxtj6iyjs7hfswa)                                                                                                     | [Worldkan](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/902)                                |            18.97 TiB |         132 | LDN v3 multisig |
| [f1fq6abg47ifgeee2z7q2rps3tvknoo2ztcoqy7ai](https://filfox.info/en/address/f1fq6abg47ifgeee2z7q2rps3tvknoo2ztcoqy7ai)                                                                                                     | [DaYe Art Tuition Class \(DKArt\) ](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/888)       |            16.81 TiB |          98 | LDN v3 multisig |
| [f3skkellc7wegakh2blqeu4kkrlzuqy2siymwli7s<br/>ec6eq77c2v4kzgz5ozgnasjl5r52ckameba5kds7h<br/>djda](https://filfox.info/en/address/f3skkellc7wegakh2blqeu4kkrlzuqy2siymwli7sec6eq77c2v4kzgz5ozgnasjl5r52ckameba5kds7hdjda) | [Meizhai Technology](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/75)                       |            15.72 TiB |         386 | LDN v3 multisig |
| [f3q7ablez3jqkcjukwbzaql7lmbx4ldouu66nexpd<br/>cfvu6kgho3v6gricckt77cgr46tdre2l4zmvha7bs<br/>u7qq](https://filfox.info/en/address/f3q7ablez3jqkcjukwbzaql7lmbx4ldouu66nexpdcfvu6kgho3v6gricckt77cgr46tdre2l4zmvha7bsu7qq) | `MatrixStorage`                                                                                                        |            14.64 TiB |         381 |        LDN # 72 |
| [f1vykg3elgzoa3lpzf5xo6rbcghzr5ifat757mucq](https://filfox.info/en/address/f1vykg3elgzoa3lpzf5xo6rbcghzr5ifat757mucq)                                                                                                     | [Hailiang Mingyou Online](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/51)                  |            13.78 TiB |          87 |        LDN # 51 |
| [f3woqxpu6ekmj43nmpcv7j2pgu6lejxtzgxpzl6f2<br/>vrueoqlzjntakyhdkghymyffbzfbsio6dvfmy643x<br/>4y7q](https://filfox.info/en/address/f3woqxpu6ekmj43nmpcv7j2pgu6lejxtzgxpzl6f2vrueoqlzjntakyhdkghymyffbzfbsio6dvfmy643x4y7q) | [RICH ST PETE LLC](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/64)                         |            12.33 TiB |         338 | LDN v3 multisig |
| [f1tgii4xgcp6um4n2w7eqaw6bwvnvyii2u7cjgzka](https://filfox.info/en/address/f1tgii4xgcp6um4n2w7eqaw6bwvnvyii2u7cjgzka)                                                                                                     | [Meson\.Network ](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/187)                         |           640.00 GiB |           2 | LDN v3 multisig |
| [f3rncwz3qo2bwnsrfjc7kq53xr7yi2lctcydtllxo<br/>zmszndvttou7n565yb6aqssvn4omyf5m7q62qpfmq<br/>cbwq](https://filfox.info/en/address/f3rncwz3qo2bwnsrfjc7kq53xr7yi2lctcydtllxozmszndvttou7n565yb6aqssvn4omyf5m7q62qpfmqcbwq) | [VillageOne Space LLCVillageOne Space LLC](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/39) |           352.00 GiB |          11 |        LDN # 39 |
| [f3q3eysweh273pwygu27yllyafljznqewpxwlrc7j<br/>daugrpvhmrcnxmkn43wkctxalcg3z42zxas2hinsf<br/>tgva](https://filfox.info/en/address/f3q3eysweh273pwygu27yllyafljznqewpxwlrc7jdaugrpvhmrcnxmkn43wkctxalcg3z42zxas2hinsftgva) | [Beijing Yibo Technology Co\., Ltd\.](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/74)      |            96.00 GiB |           1 |        LDN # 74 |
| [f1qnhjr2kq742poi6rukv5hji5rdrtuqsib7khz3a](https://filfox.info/en/address/f1qnhjr2kq742poi6rukv5hji5rdrtuqsib7khz3a)                                                                                                     | [GLOBAL UNIT\-A Corp\.](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/110)                   |            32.00 GiB |           1 |       LDN # 110 |

[^1]: To manually trigger this report, add a comment with text `checker:manualTrigger`
