### ISSUE TITLE
[DataCap Application] NHN KCP CORP.

### ISSUE THREAD

**Issue by choibs95** [filecoin-project/filecoin-plus-large-datasets#35]
# Large Dataset Notary Application

To apply for a DataCap allocation for your dataset, please fill out the following information.

## Core Information
- Organization Name: NHN KCP CORP. 
- Website / Social Media: www.kcp.co.kr 
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100TiB
- On-chain address for first allocation: f3wi7p7plkdzeyq5mjfjjvgztv757tzzibqd5sfr5xgoj7snsp4y34x67khduur43tutwj4cp5diyfihs2h6aa

_Please respond to the questions below in pargraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

## Project details

Share a brief history of your project and organization.
[Big Data_ML Analytics Platform for SMEs_V 1.3.pdf](https://github.com/filecoin-project/filecoin-plus-large-datasets/files/7089539/Big.Data_ML.Analytics.Platform.for.SMEs_V.1.3.pdf)
```
NHN KCP is the biggest payment and e-wallet related Fintech company in Korea. 
- We also have our own subsidary company in Singapore (NHN KCP PTE) and Thailand (Treepay, JV with SKT and National Telecom Public Company Thailand).

We are family member of Korea's biggest IT enterprise "NHN". and Korea's one of the biggest e-Wallet platform "PAYCO". 
- Please refer to first few pages of attached project deck for more details on our company.

As a TF leader of Global business part, i have been studying and planning new Fintech project without issuing new "Token" or "Coin"  but apply "Blockchain Technology" itself so that our Customers and Government can easily adopt into pure blockchain techology itself. 

Especially under current "Covid" situation worldwide, i have been witnessing a lot of "small sizes" to "medium sizes" offline merchants and "potential" merchants suffering without paying "expensive fees" for consulting with expensive consultants. 

There are a lot of state and local government parts who provides "public data" for anyone who need to use but doesn't understand and face difficulties trying to utilize the data. 
That's why i started to design big data based machine learning fintech platform that any small ~ medium size merchants without any costs for them. 

In order to provide "free service" for SMEs, one of the biggest challenges was the "our cost" for massive amount of data that can be used as base source to generate meaningful data from our ML algorithm if i want to store in traditional cloud server like "AWS".

Filecoin Plus's purpose to enable the demand side of the network and maximize the amount of useful storage on a layer of social trust to the network, exactly matches with our needs to help as much as possible for small ~ medium size merchants who can't afford a lot of fund on consulting with expensive charges. 

```

What is the primary source of funding for this project?
```
Our funding source for this project is the revenue that our company generates from our own service. 
```

What other projects/ecosystem stakeholders is this project associated with?
```
I am contacting with a lot of government departments, universities, research institutions to obtain as much as useful "public" data that can be used for the project. 
```

## Use-case details

Describe the data being stored onto Filecoin
```
We will be uploading a lot of good quality video files, image files and csv data in order to improve and display as quality output as possible from our platform.  
```

Where was the data in this dataset sourced from?

```
Data will be received from below institutions; 

1. Official government website such as  https://www.data.go.kr/, https://bigdata.changwon.go.kr/

2. A lot of Universities who is doing Data based projects (like PHD projects) that relates with fintech data, ML, public data and so on. 

3. Research institutions

4. Government departments 
    - with current trend in Korea, Government is supporting well for Fourth Industrial Revolution including big data, machine learning, Blockchain. 

```

Can you share a sample of what is in the dataset? A link to a file, an image, a table, etc., are good examples of this. 
```
 Video Samples 
  
   * Jeju Island Section 2 A 
    - https://www.dropbox.com/s/34dmrgjefper9ny/%5BJEJU%5DSection%202_A.mp4?dl=0

  * Jeju Island Section 2 B 
    -  https://www.dropbox.com/s/8khid39swa4r6ng/%5BJEJU%5DSection%202_B.mp4?dl=0

 Image Samples (Video Analysis Particle)

 * Jeju Section 2 A 
  - https://www.dropbox.com/sh/32huv3pjwzecalm/AABD_MSBbWWiWWbDXO6LY7GQa?dl=0

 * Jeju Section 2 B 
  - https://www.dropbox.com/sh/e9mnm1y0vlulemk/AACiaUhQ8LvQ_KrCyjVKa-g0a?dl=0

 Image Samples 2 (Google Tile Data)
 - https://www.dropbox.com/s/g344qdyh065yw5a/Jeju%20Section%20tile.JPG?dl=0

Data Sample (Merchant Distribution Data with GPS, name, type information) 
 - https://www.dropbox.com/scl/fi/4pak1naqt48ua2psg9k27/ZeroPay-Merchant-information-with-geological-info_Changwon.xlsx?dl=0&rlkey=fn6u88ji7trno4o0t7oglwk8s

```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
It will be public dataset that anyone on the network can view without permission. 
```

What is the expected retrieval frequency for this data?
```
During early stage of the project, retrieval frequency won't be often as there will not be enough data and customer at first stage. 

As we store more data on the network and get more users to utilize our platform, retrieval frequency will gradually increase. 
```

For how long do you plan to keep this dataset stored on Filecoin? Will this be a permanent archival or a one-time storage deal?
```
We intend to keep the data for long-term as we can generate more efficient output as our base data is getting bigger to create more accurate algorithms. 
```

## DataCap allocation plan

In which geographies do you plan on making storage deals?
```
At early stage, we will try to speak 2~3 mining companies in Korea as we might need to visit onsite and need time to finalize how to transfer data like offline, SFTP, PP CLI and so on. 

After we develop how to transfer data with miners, we will try to make agreement with miners in other regions. so that we can spread to at least 5 different locations. 

```

What is your expected data onboarding rate? How many deals can you make in a day, in a week? How much DataCap do you plan on using per day, per week?
```
We expect around 50 ~ 100 tib per week on average for updating our base data for platform. 
- PS. 1 min length sample video was around 1 gib. 
```

How will you be distributing your data to miners? Is there an offline data transfer process?
```
We will start by offline data transfer to local miners to begin with and build couple of more ways to transfer with mines across world, such as SFTP, PP CLI or any other protocol after few workshop with their tech team. 
```

How do you plan on choosing the miners with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We will visit at least 2~3 different miners in Korea first and see their capacity, security protocol and so on. 
Our IT team and miner tech team's capabilities for data retrievable procedure will be import factor as well. 
```

How will you be distributing data and DataCap across miners storing data?
```
We will try to distribute equal amount of data sets evenly to as least 5~6 miners across world. 

```

**Comment by choibs95** [comment]
Hello team,
Any feedbacks on the application? 

Thanks

**Comment by IreneYoung** [comment]
Hi, @choibs95 I'm interested in your project. Please count me in to be one of the Notaries. And you can feel free to contact me if you have any problems when applying the DataCap here. the contact email address is: contact@12ships.com.

I have some questions hopefully to get your reply. 

1. You are requesting the DataCap on behalf of the company, NHN KCP CORP., do you? So what's your position in NHN KCP CORP.?
2. What is the exact relationship between your company and the institutions you mentioned above, like the government departments, research institutions, and universities? Is there any cooperative relationship?

**Comment by choibs95** [comment]
@IreneYoung Thanks for your interest in our project. 

Please refer to below for your questions; 

1. I am representing on behalf of the NHN KCP CORP. I'm senior Manager for NHN KCP's Global Department, NHN KCP PTE (our Singapore Entity) and Treepay (JV of NHN KCP, SKT and National Telecom company of Thailand). 
  - If you have any questions, please  feel free to contact my company email: csyu@kcp.co.kr 

2. Our project CTO and advisor has personal relationship with a lot of universities for professor and PHD students and government departments. We contacted them about our project and they are willing to be involved as part of their university big data research. 

We have contact a lot of governement entities and state government as our CTO has previously worked with a lot of projects.
As you may know, NHN has a lot of data subsdary companies such as NHN DATA, PAYCO (for e-commerce data) and so on. 

We do have a lot of quality datas that we can utilize and from Goverment's Data center (https://www.data.go.kr/) that we can enhance our data for the project. 

Please feel free contact me by my company email if you have and further questions. 

Best Regards,

**Comment by galen-mcandrew** [comment]
## Multisig Notary requested
#### Total DataCap requested 
> 5PiB
#### Expected weekly DataCap usage rate 
> 100TiB

**Comment by choibs95** [comment]
@galen-mcandrew Dear Galen, i'm so glad to see there has been update. Any follow up steps that i need to get involved with?

I will be looking forward to response. 

Best Regards,

**Comment by IreneYoung** [comment]
Hi @galen-mcandrew , I'd like to approve this application from @choibs95, but my notary address (f1d4gmpqz3execjj2wvrxuuhvbms5mzh7t7yqrviq) is not in the multisig signer list. I wonder if you can add the address into the multisig signer list, or if it is convenient for you to create a new one?

**Comment by galen-mcandrew** [comment]
@IreneYoung all ~39 of the current large dataset multisigs have the address f1inc6lx4oosssdf5n7rkt45rtwzlip7ohott7vha as a signor. We will need to update the system so that the new LDN's that get submitted and created by governance team and root key holders have the address f1d4gmpqz3execjj2wvrxuuhvbms5mzh7t7yqrviq . It is technically challenging to add a signor to all 39 of those multisigs, as it will require existing signing members of the multisig to propose and approve the message: governance team and root key holders cannot change the signing addresses on a multisig.

@dkkapur @fabriziogianni7 we will need to update our list of notary addresses so that future LDN's can be signed by 12ships

**Comment by Reiers** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced7456q6dmkjds6adimusctfd3mhs7wpegj76cnic7d3t4wea4suc 
#### Address 
> f3wi7p7plkdzeyq5mjfjjvgztv757tzzibqd5sfr5xgoj7snsp4y34x67khduur43tutwj4cp5diyfihs2h6aa
#### Datacap Allocated
> 50TiB
#### Signer Address
> f1oz43ckvmtxmmsfzqm6bpnemqlavz4ifyl524chq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced7456q6dmkjds6adimusctfd3mhs7wpegj76cnic7d3t4wea4suc

**Comment by MegTei** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceciq2spi7zl5yqfbeexiu2akjgg5cyvotdyta7nug63c4cxe3c5eg 
#### Address 
> f3wi7p7plkdzeyq5mjfjjvgztv757tzzibqd5sfr5xgoj7snsp4y34x67khduur43tutwj4cp5diyfihs2h6aa
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1ystxl2ootvpirpa7ebgwl7vlhwkbx2r4zjxwe5i
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceciq2spi7zl5yqfbeexiu2akjgg5cyvotdyta7nug63c4cxe3c5eg

**Comment by mr-spaghetti-code** [comment]
Hi,

It looks like you received 50TiBs of DataCap to date but have spent less than 20% of it so far.

We would love to understand if there's anything holding you back. We are working hard to make the data onboarding process easier for clients like you and your feedback is very valuable. If you have a moment, please fill in this survey: https://forms.gle/s6AuTXZPZSMokscLA

If you have any feedback or would like to consult with an expert, please let me know. 

Thanks,

João Fiadeiro
Product Manager, Large Data Client Onboarding
Protocol Labs

**Comment by Sunnyiscoming** [comment]
Hi @choibs95 
Are there any problems with using datacap?
