### ISSUE TITLE
[DataCap Application]Huiya

### ISSUE THREAD

**Issue by Huiya-Shanghai** [filecoin-project/filecoin-plus-large-datasets#354]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Shanghai Huiya Information Technology Co., Ltd.
- Website / Social Media:www.shhuiya.com
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):2PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):100TiB
- On-chain address for first allocation: f1nmgcc66hqbaj3ztovlsjurvu4nw4siygoxmnnry

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Shanghai Huiya Information Technology Co., Ltd. is a "double-software" software company recognized by the Shanghai Municipal of Economic and Informatization. The company was established in September 2007. In February 2012, the company obtained the "Huiya" and related LOGO trademark registration certificate. In May 2012, the company won the Shanghai Innovation Fund. At the same time, the company has also obtained a number of software product copyrights and software product registration certificates. We provide application development services, including ios, Android, app, mini-program, windows application. Our company has served a large number of Fortune 500 companies in the fields of medicine, medical equipment, machinery automation, etc.
```

What is the primary source of funding for this project?
```
Our company have shareholders who can give us funds.
```

What other projects/ecosystem stakeholders is this project associated with?
```
None.
```

## Use-case details

Describe the data being stored onto Filecoin
```
Application development files, live videos of online shopping mall and code.
```

Where was the data in this dataset sourced from?
```
From our company's products and service.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
[node_modules.zip](https://github.com/filecoin-project/filecoin-plus-large-datasets/files/8666904/node_modules.zip)
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes, we confirm it.
```

What is the expected retrieval frequency for this data?
```
Maybe once half a year.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
We hope to have long-time storage. 5 years.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Asia.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
We will choose both online and offline transfer.
We would choose the more convenient one according to the network.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
Storage providers who are reliable and stable are our first choice.
```	

How will you be distributing deals across storage providers?
```
It will be distributed to storage providers who are closer first and try the best to distribute deals averagely.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes. We need to start deals at once.
```

**Comment by Huiya-Shanghai** [comment]
@galen-mcandrew @dkkapur Please tell me when can I get my datacap?

**Comment by Huiya-Shanghai** [comment]
@galen-mcandrew @dkkapur We have been following the Filecoin project since a long time ago, and we have full confidence in it. After a long time of observation, we think it has considerable potential as a Web 3.0 data storage application. We hope that notaries will pass our application request.

Best Regards.

**Comment by AnthnoySmith** [comment]
Could you help explain why you broke your promise to use datacap in your previous experience? 
https://github.com/filecoin-project/filecoin-plus-client-onboarding/issues/650
![image](https://user-images.githubusercontent.com/94275737/169471740-cb52460e-cbd3-4316-93e6-cb826b366ebb.png)
![image](https://user-images.githubusercontent.com/94275737/169471829-5d1c600d-d994-418f-8304-606edc837fae.png)

**Comment by Huiya-Shanghai** [comment]
Thank you for your caring and careful research.

First of all I want to say sorry, I did apply for datacap once. But that was the first time we applied for datacap, we only understood the rules in the literal sense, and we are not familiar with the specific operation of using datacap. Therefore, the 2TiB from that application was just an attempt for us. I think it is really difficult to allocate datacap in one wallet address to multiple different storage providers without exceeding the specified allocation capacity for every storage provider. 

Now we have more experience and know how to distribute better. Based on our expectations for the future of Filecoin, we applied for LDN this time.

**Comment by Sunnyiscoming** [comment]
@Huiya-Shanghai 
1. As you said, you have application development files, live videos of online shopping mall and code. Can you provide more data samples, like live videos of online shopping mall and point out which online mall it is.
2.In view of the above question, can you explain which storage providers you have established cooperation intention with at present?

**Comment by Huiya2** [comment]
@Sunnyiscoming 
My previous account goes wrong, so I change into this account to reply.
[data.zip](https://github.com/filecoin-project/filecoin-plus-large-datasets/files/8920070/data.zip)
Part of live videos.

We are looking for storage providers via slack/github.

**Comment by Sunnyiscoming** [comment]
@Huiya-Shanghai In response to the previous question, you may need to identify the storage providers before proceeding to the next step.

**Comment by Huiya2** [comment]
f01870475
f01850141
f047666
f061666
@Sunnyiscoming We communicated with these SPs for application.

**Comment by Chris00618** [comment]
These nodes have some close connection with Cabrina Huang, do you know or serve for their teams?  It seems that we need rootCIDs to make further investigation into this issue.

**Comment by Huiya2** [comment]
First of all I have to say thank you “Chirs00618” for your question and thank you for keeping us in the loop! However, I would like to say that we have submitted all the relevant information required for the LDN application as requested and we have answered all the additional questions.

Every serious answer is always followed by the next question, always, and this is wearing on our patience.This makes us think that this LDN is not open to "others", as it is obviously very harsh on us, and without the LDN quota.

I don't know what else I have to answer, maybe you might want me to prove that I am me and you have to know that blockchain is an open world, but Chirs00618 you clearly are not. By the way your account was registered on 2022.5.18 and  only active on this issue, which is clearly deliberate and I am quite familiar with this combination of English names + numbers and the fact that none of these accounts are very active.

We can also follow these leads very easily and find more results, and like "Chirs00618" you said, we should dig deeper.

**Comment by Sunnyiscoming** [comment]
@Huiya-Shanghai Hey. Could you send an email to [filplus@fil.org](mailto:filplus@fil.org) with your official domain in order to confirm your identity?

**Comment by Huiya2** [comment]
@Sunnyiscoming  I have sent an email to filplus@fil.org

**Comment by galen-mcandrew** [comment]
## Datacap Request Trigger
#### Total DataCap requested 
> 2PiB
#### Expected weekly DataCap usage rate 
> 100TiB 
#### Client address
> f1nmgcc66hqbaj3ztovlsjurvu4nw4siygoxmnnry

**Comment by Joss-Hua** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaxjvdl6maw2n6q6ethv4gjeaclrrlaoe65v4y7nxfpwemsi3wdcs 
#### Address 
> f1nmgcc66hqbaj3ztovlsjurvu4nw4siygoxmnnry
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1tfg54zzscugttejv336vivknmsnzzmyudp3t7wi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaxjvdl6maw2n6q6ethv4gjeaclrrlaoe65v4y7nxfpwemsi3wdcs

**Comment by Joss-Hua** [comment]
Since this is the first signature, I will continue to verify.

**Comment by Huiya2** [comment]
Thank you so much!

**Comment by xinaxu** [comment]
> @Huiya-Shanghai Hey. Could you send an email to [filplus@fil.org](mailto:filplus@fil.org) with your official domain in order to confirm your identity?

@Sunnyiscoming Has the identity of the applicant been verified (SFP/DKIM)

**Comment by Huiya2** [comment]
Thank you so much, I have sent the E-mail.

**Comment by xinaxu** [comment]
The applicant does not have a domain verified email address so instead I've asked him to add a verification file on their website: http://www.shhuiya.com/fil.txt
This provides a proof that the applicant is the owner of www.shhuiya.com

**Comment by xinaxu** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced5rly6vhyqwaeo7pnoltrmu6rflpakvwbsqzpp75tfrqhs2fvmho 
#### Address 
> f1nmgcc66hqbaj3ztovlsjurvu4nw4siygoxmnnry
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1k3ysofkrrmqcot6fkx4wnezpczlltpirmrpsgui
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced5rly6vhyqwaeo7pnoltrmu6rflpakvwbsqzpp75tfrqhs2fvmho

**Comment by newwebgroup** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedupgzwks4aprdbjrmjwwwbaabevwn35inlcp7evvlfahp4irkhwg 
#### Address 
> f1nmgcc66hqbaj3ztovlsjurvu4nw4siygoxmnnry
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1e77zuityhvvw6u2t6tb5qlnsegy2s67qs4lbbbq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedupgzwks4aprdbjrmjwwwbaabevwn35inlcp7evvlfahp4irkhwg

**Comment by ipfscn** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebfxz4xr45nnhkixbkorpzpgguncnhcp3qvpfxiadfj4kv2agbyso 
#### Address 
> f1nmgcc66hqbaj3ztovlsjurvu4nw4siygoxmnnry
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1j4n74chme7whbz3yls4a7ixqewb6dijypqg2a3a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebfxz4xr45nnhkixbkorpzpgguncnhcp3qvpfxiadfj4kv2agbyso

**Comment by kernelogic** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec6x43qoxq6hh4wjpergnoaptbmdy72gefpc7jlxn3r2kcoj2g2k6 
#### Address 
> f1nmgcc66hqbaj3ztovlsjurvu4nw4siygoxmnnry
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec6x43qoxq6hh4wjpergnoaptbmdy72gefpc7jlxn3r2kcoj2g2k6

**Comment by liyunzhi-666** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceat7frrnqg2altkrmtfwuzh6z6zh3dk35me44elguikkack4sldjc 
#### Address 
> f1nmgcc66hqbaj3ztovlsjurvu4nw4siygoxmnnry
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1pszcrsciyixyuxxukkvtazcokexbn54amf7gvoq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceat7frrnqg2altkrmtfwuzh6z6zh3dk35me44elguikkack4sldjc

**Comment by BigD-Exchange** [comment]
@Huiya-Shanghai Hi! Great to see you have gotten approval for DataCap and advancing the mission of preserving humanity’s most important information. If you are looking for storage providers to store these data or have any questions, please visit #bigdata-exchange on Filecoin Slack or reply here.

**Comment by xingjitansuo** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceagihettsfyddgpzwmlfexbncbwawumxbdl2es3lgatvf5ffwf3ls 
#### Address 
> f1nmgcc66hqbaj3ztovlsjurvu4nw4siygoxmnnry
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1a2lia2cwwekeubwo4nppt4v4vebxs2frozarz3q
#### Id
> 01e4f2f3-d0af-461a-a5ef-5d9de447c979
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceagihettsfyddgpzwmlfexbncbwawumxbdl2es3lgatvf5ffwf3ls

**Comment by liyunzhi-666** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacectie74xjjq3uf5noz7t2o7k2famo255w32nupv2cjl6yytc5gjne 
#### Address 
> f1nmgcc66hqbaj3ztovlsjurvu4nw4siygoxmnnry
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1pszcrsciyixyuxxukkvtazcokexbn54amf7gvoq
#### Id
> 01e4f2f3-d0af-461a-a5ef-5d9de447c979
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacectie74xjjq3uf5noz7t2o7k2famo255w32nupv2cjl6yytc5gjne

**Comment by newwebgroup** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecbojsjvsxivi2jqeyazc6gv6xchqufoazvkazdhkqqvw63zxhz54 
#### Address 
> f1nmgcc66hqbaj3ztovlsjurvu4nw4siygoxmnnry
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1e77zuityhvvw6u2t6tb5qlnsegy2s67qs4lbbbq
#### Id
> 45cdad5e-209b-4ed3-826a-e346dd7760e3
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecbojsjvsxivi2jqeyazc6gv6xchqufoazvkazdhkqqvw63zxhz54

**Comment by kernelogic** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecyb5iydbfgu77udspdlwovhfw322htu2dbtfwvqdthjlya36tiam 
#### Address 
> f1nmgcc66hqbaj3ztovlsjurvu4nw4siygoxmnnry
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### Id
> 45cdad5e-209b-4ed3-826a-e346dd7760e3
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecyb5iydbfgu77udspdlwovhfw322htu2dbtfwvqdthjlya36tiam

**Comment by Sunnyiscoming** [comment]
@Huiya-Shanghai 
Does the nodes working for this project support retrieval publicly?
Please provide retrieval samples.
Please provide the above information for community members review before the next allocation.

**Comment by filplus-checker** [comment]
## DataCap and CID Checker Report[^1]
 - Organization: `Shanghai Huiya Information Technology Co., Ltd.`
 - Client: `f1nmgcc66hqbaj3ztovlsjurvu4nw4siygoxmnnry`
### Storage Provider Distribution
The below table shows the distribution of storage providers that have stored data for this client.

If this is the first time a provider takes verified deal, it will be marked as `new`.

For most of the datacap application, below restrictions should apply.
 - Storage provider should not exceed 25% of total datacap.
 - Storage provider should not be storing duplicate data for more than 20%.
 - Storage provider should have published its public IP address.
 - All storage providers should be located in different regions.

⚠️ [f01946104](https://filfox.info/en/address/f01946104) has sealed 53.08% of total datacap.

| Provider                                              |                 Location | Total Deals Sealed | Percentage | Unique Data | Duplicate Deals |
| :---------------------------------------------------- | -----------------------: | -----------------: | ---------: | ----------: | --------------: |
| [f01946104](https://filfox.info/en/address/f01946104) |     Chengdu, Sichuan, CN |         566.97 TiB |     53.08% |  566.97 TiB |           0.00% |
| [f01270767](https://filfox.info/en/address/f01270767) | Guangzhou, Guangdong, CN |         240.19 TiB |     22.49% |  240.13 TiB |           0.03% |
| [f098743](https://filfox.info/en/address/f098743)     |  Shenzhen, Guangdong, CN |         204.00 TiB |     19.10% |  204.00 TiB |           0.00% |
| [f0142637](https://filfox.info/en/address/f0142637)   |     Chengdu, Sichuan, CN |          56.97 TiB |      5.33% |   56.97 TiB |           0.00% |

![Provider Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/354/1671095337024.png)
### Deal Data Replication
The below table shows how each many unique data are replicated across storage providers.
- No more than 25% of unique data are stored with less than 4 providers.

⚠️ 100.00% of deals are for data replicated across less than 4 storage providers.

| Unique Data Size | Total Deals Made | Number of Providers | Deal Percentage |
| ---------------: | ---------------: | ------------------: | --------------: |
|       205.00 TiB |       205.00 TiB |                   1 |          19.19% |
|       222.84 TiB |       445.72 TiB |                   2 |          41.73% |
|       139.13 TiB |       417.41 TiB |                   3 |          39.08% |

![Replication Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/354/1671095338225.png)
### Deal Data Shared with other Clients
The below table shows how many unique data are shared with other clients.
Usually different applications owns different data and should not resolve to the same CID.

✔️ No CID sharing has been observed.

[^1]: To manually trigger this report, add a comment with text `checker:manualTrigger`

**Comment by xingjitansuo** [comment]
checker:manualTrigger

**Comment by xingjitansuo** [comment]
<img width="935" alt="image" src="https://user-images.githubusercontent.com/72185104/228426125-76cd6fb4-0f67-4a36-b357-d9bc16df853a.png">

Retrieval works. I will support this tranche. Hope to see more duplicates in the next round.

**Comment by xingjitansuo** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceamb5xoic5gahptfk5fgbbogyjqc6tcvowckanu3h4hpmdbfw26ty 
#### Address 
> f1nmgcc66hqbaj3ztovlsjurvu4nw4siygoxmnnry
#### Datacap Allocated
> 498.00TiB
#### Signer Address
> f1a2lia2cwwekeubwo4nppt4v4vebxs2frozarz3q
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceamb5xoic5gahptfk5fgbbogyjqc6tcvowckanu3h4hpmdbfw26ty

**Comment by METAVERSEDATAMINING** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebogfgdzyumbqdlvzcsyd5xsgofnosy7wqfi6xgzv5lj5l7vhsn4c 
#### Address 
> f1nmgcc66hqbaj3ztovlsjurvu4nw4siygoxmnnry
#### Datacap Allocated
> 498.00TiB
#### Signer Address
> f17idrnfnxl2mbgcgr57a6z2c6lj2qx56gvm3336i
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebogfgdzyumbqdlvzcsyd5xsgofnosy7wqfi6xgzv5lj5l7vhsn4c
