### ISSUE TITLE
[DataCap Allocation] - MainNet Database

### ISSUE THREAD

**Issue by ElonMNC** [filecoin-project/filecoin-plus-large-datasets#355]
---
name: Large Dataset Notary application
about: Clients should use this application form to request a DataCap allocation via a LDN for a dataset
title: "MainNet Database"
labels: 'application, Phase: Diligence'
assignees: ''

---
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: MainNet Capital
- Website / Social Media: www.mainnetcapital.com
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 10
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100
- On-chain address for first allocation: f1wm77szwwxsrqt52l433msu5bzdssmu6773z2kiy
- Region: Asia (excl. Greater China)

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Founded in 2017, MainNet Capital is Asia’s leading alternative asset management and investment fund house, holding a Capital Market Security license (LFMC) in singapore issue via Monetary Authority of Singapore. MainNet Capital is managing hundreds of millions dollars via VCC funds (Open-ended and close-ended fund structure in Singapore and Cayman)

We started Filecoin mining back in 2020. As of Feb 2022, we have data center setup in Singapore

We have established a compliant closed-end investment fund in Singapore, dedicated to build the eco-system for Filecoin, which including storage providing and data storage from our existing data.

Our dedicated VCC fund was founded in Q2 2021, specialised in mining investment and eco-system build up.
```

What is the primary source of funding for this project?
```
Our established VCC Fund in Singapore.
https://opengovsg.com/corporate/T21VC0075B
Unique Entity Number (UEN)	T21VC0075B
Entity Name	M TURING
```

What other projects/ecosystem stakeholders is this project associated with?
```
this project is run by MainNet Capital, and the affiliate group with MainNet Group Holding companies. The Affiliate companies have strong needs for cloud data storage for our trading data, back-testing data, market research data, app/website data storage and etc.

```

## Use-case details

Describe the data being stored onto Filecoin
```
Our company and the affiliate companies have strong needs for cloud data storage for our trading data, back-testing data, market research data, app/website data storage and etc.
In our affiliate companies, we have neobanks logs, terminal logs, photos, videos and etc.
```

Where was the data in this dataset sourced from?
```
Nasdaq, NYSE, Binance and etc market data, Bloomberg, yahoo, Tom Lee and etc market news and research report. internal app, website, trading terminal data, investor portal data, transaction and trading log from internal trading terminal too. we will ensure the legitimacy of the data and the copyright as well.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://mainnetcapitalcom-my.sharepoint.com/:i:/g/personal/elon_mainnetcapital_com/ETMzeBcUISNLgRBWOZgs5EsBXDQnJJV3kPsUcoXfTMf3hw?e=pSFDec
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
most of the data is public dataset, we are willing to share among the network to build Filecoin Ecosystem.

```

What is the expected retrieval frequency for this data?
```
daily, weekly mostly
```

For how long do you plan to keep this dataset stored on Filecoin?
```
we don't have timeframe for keeping the data in filecoin, ideally is safekeeping for longer period of time. easier for our team and users to have those data to keep for good

```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Asia (excluding Greater China) - Singapore
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
We will distribute the data to storage on our established data center in Singapore. f0158613 is one of our node which started last year. for the offline data transfer process at current moment is not essential for our needs.

```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We plan to use our data center which was built in Singapore for the support of our affiliate companies' and partners' needs.
however, for the onboarding of customers. we are following the internal process as follows:
1. Every DataCap applicant must hand in applications to us. They can apply online (small DataCap) and offline in written form.
2. After the initial review, we will carry out a qualification pre-review. The applicant must be maturely developed business organisations or NPOs with actual data storage demand.
3. The applicant that fails the pre-review will be required to provide extra information or will be refused directly.
4. For applicants that pass the pre-review, we will carry out due diligence investigation to learn the applicant's legality, operation status, and other related stats. 
5. According to the result of the due diligence investigation, we will rate the business organization based on the factors and standards mentioned above. (NPOs excluded).
6. Last, we will refuse or approve the application in written form. If approved, we will allocate the DataCap based on actual conditions. 
```

How will you be distributing deals across storage providers?
```
we are distributing the Deals among the machines in our Singapore data center.
1. All allocation decisions will be conducted on GitHub publicly and all communications and problems can be traced via the memory library.
2. The application materials and allocation records of each applicant will be saved graphicly and will be uploaded on the Filecoin network for permanent saving. 
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, we do have sufficient resources and funding for us to kick start deals as soon as we receive the DataCap. meanwhile we have enough community base and support for us to do the onboarding. 
```

**Comment by ElonMNC** [comment]
thanks for the auto reply. looking forward to receive the feedbacks. cheers

**Comment by ElonMNC** [comment]
@galen-mcandrew Dear Galen, may I kindly follow up on the verifying process of our application. thanks

**Comment by Sunnyiscoming** [comment]
@ElonMNC Hi,
This application seems to be duplicates of https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/351, right?

**Comment by ElonMNC** [comment]
> @ElonMNC Hi,
> This application seems to be duplicates of #351, right?

yes, #351 was not fully completed. #355 is more furnished. may I know shall we continue here? or just continue with #351 is fine

**Comment by Sunnyiscoming** [comment]
@ElonMNC
You can close #351, and we continue #355.

One more question.
Large datasets focus on decentralization for storage providers.
Is there more information to provide about data storage services with other storage providers?

**Comment by ElonMNC** [comment]
> 

@Sunnyiscoming 
yes, we are currently use multi cloud storage provider, like AWS, AliCloud and Google Cloud. 
this the our sample data in the link.https://mainnetcapitalcom-my.sharepoint.com/:f:/g/personal/elon_mainnetcapital_com/EuoXOXp_SpRKlnq-7dVHXUMBHnESiCIGVlg2ekVX3TDg-A?e=YBDauF

**Comment by ElonMNC** [comment]
hi @Sunnyiscoming may I kindly follow up the process and looking forward to get the approval

**Comment by Sunnyiscoming** [comment]
Any Filecoin storage provides can be provided?

**Comment by ElonMNC** [comment]
@Sunnyiscoming yes, we are writing up the details will send over shortly

**Comment by ElonMNC** [comment]
@Sunnyiscoming currently we have the following node  as our storage provider:
f01879880/f01880894/f01880896/f01880897/f01880898

**Comment by dkkapur** [comment]
> we are distributing the Deals among the machines in our Singapore data center.

Just wanted to flag that this is actually not in like with the geo and SP distribution expectations for LDN applications. @ElonMNC you'll need to find at least 3 other SP organizations to work with, in different datacenters, to ensure that deals are being distributed in a way that works for your needs long term.

**Comment by raghavrmadya** [comment]
@ElonMNC , please provide an update if you still wish to pursue this application.

**Comment by ElonMNC** [comment]
@raghavrmadya Hi Rag, yes, we are preparing the updates with the latest information. and will revert shortly. and we still wish to pursue this application

**Comment by Sunnyiscoming** [comment]
Any update here?

**Comment by raghavrmadya** [comment]
Closing due to no reply. Please open a new application.

**Comment by ElonMNC** [comment]
> Closing due to no reply. Please open a new application.

thanks Rag
