### ISSUE TITLE
[DataCap Application]Newwebgroup

### ISSUE THREAD

**Issue by newwebgroup** [filecoin-project/filecoin-plus-large-datasets#356]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: New Web Group
- Website / Social Media: https://www.newwebgroup.com/   twitter: NewWebGroup
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 3PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 200TiB
-  `or more, Note: Because we are involved in the foundation's  Project Gravity enterprise data storage activity, Enterprise customers hope to store data on filecoin faster.https://filecoin.io/blog/posts/filecoin-project-gravity-a-sales-referral-program/）`
- On-chain address for first allocation: f126k3tkdwfaqpflgcclkiwhqxhh73ebqqazwgcoy

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
In 2017, the founding team of New Web Group was involved in IPFS and formed a technical team.
In August 2020, we participated in the FIL Space Race.
In 2019, NWG established a deep long-term partnership with GCR local IDC operators. 
December 2020, New Web Group Technology was established and now has 100+ employees and has gained a very good reputation in China.
In August 2021, New Web Group's international office was established and is building an international computing platform, hoping that more people internationally will come to focus on FileCoin.
In January 2022, we cooperated with the FileCoin retrieval market and submitted a development proposal for a distributed shared CDN to help FileCoin improve the reward mechanism for retrieval service providers and enhance the experience of the Filecoin retrieval market and the ecological construction of FileCoin.
In March 2022, we officially became a member of the orbit community, and as a founding member, we are ready to work with the community to do a good job of educating the world and making more people aware of and enjoy FileCoin.
On top of that, our company has a great group of employees who each promote Filecoin on social media and in total have gained a following of over 50,000 people and influenced 5 million crypto digital currency investors.

```

What is the primary source of funding for this project?
```
Supported by ourselves and the filecoin Foundation
```

What other projects/ecosystem stakeholders is this project associated with?
```
Filecoin foundation
Related to the customer to store the data.  Name of client organization: Wanjing media
```

## Use-case details

Describe the data being stored onto Filecoin
```
The data type is internet personalities video.

China tiktok link
https://www.douyin.com/user/MS4wLjABAAAAhraWM86XeU3vEpfo7_yZaUhX5uwpOliUpU255LC8K_ifWH-1VsczXyke1t8skR4f
https://www.douyin.com/user/MS4wLjABAAAAvgSfPrLtxuvpdfmHHsSsOkcLu2ihsvHLAitVuj9VHvY
```

Where was the data in this dataset sourced from?
```
enterprise data
Founded in February 2020, Wanjing media is a rapidly rising content output company perpendicular to the short video ecology. Wanjing covers six major sectors, including talent incubation, talent brokerage, IP creation, content creativity, live broadcast and short video. Among them, Taiyue brokerage company is specially responsible for talent incubation, talent brokerage and other businesses. In the short time since its establishment, it has grown rapidly, and has laid a solid foundation in the target sector. In a short time, it has grown into a professional team with a scale of more than 100 people, creating many accounts of millions of fans and many millions of popular works.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
Open the link to see the data type
China tiktok link
https://www.douyin.com/user/MS4wLjABAAAAhraWM86XeU3vEpfo7_yZaUhX5uwpOliUpU255LC8K_ifWH-1VsczXyke1t8skR4f
https://www.douyin.com/user/MS4wLjABAAAAvgSfPrLtxuvpdfmHHsSsOkcLu2ihsvHLAitVuj9VHvY
There are many similar data...
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes, all the data are public.
```

What is the expected retrieval frequency for this data?
```
Twice a year
```

For how long do you plan to keep this dataset stored on Filecoin?
```
Two to three years
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Asia
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
All are offline transfers
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We will focus on the running time of the SP, whether the running state is stable, the size of the node, and whether it supports retrieval.
We need high-quality storage providers who can work together for a long time.
```

How will you be distributing deals across storage providers?
```
We will allocate different transactions according to distance, running time, etc.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes，We have the support of filecoin foundation,We're ready for making deals.

**Comment by galen-mcandrew** [comment]
I think there is some confusion here, and want to understand more about this specific large dataset. Some initial concerning sections:

> No, 95% of the data in it needs to be encrypted.
> The data type is internet personalities video.

Does this mean you are requesting DataCap for 1 PiB of private encrypted tiktok videos? Is this application request for some other program that New Web Group is using to identify data partners and clients?

Additionally, I want to understand what the flowchart at the bottom means. It looks like that flowchart is how New Web Group will make notary decisions for their direct client allocation requests that come in through the [registry](https://plus.fil.org/verifiers). Is that accurate?

**Comment by newwebgroup** [comment]
Thank you for your reply, Galen @galen-mcandrew 

Does this mean you are requesting DataCap for 1 PiB of private encrypted tiktok videos? 
Yes, Wanjing media is a MCN media company. They have incubated many Internet Celebrities. At present, the number of fans on the whole Internet is about 60000k+
They want to store these videos of Internet celebrities on fileocin through new web group.
95% of the encrypted part is: the project file of video source material or video clip. This part involves trade secrets and intellectual copyright, which is not suitable for disclosure.
The part that can be disclosed is to output the finished video presented on the exported tiktok.
The exported finished video can be made public, but his production project files and materials in the shooting process need to be encrypted.

Is this application request for some other program that New Web Group is using to identify data partners and clients?
Yes, the ownership of the two cases of Internet Celebrities cited here belongs to Wangjing media. He authorizes us to store these business data on filecoin and provide them with retrieval solutions in the future.

On the last question:
Thank you for reminding. You are right. There are problems in this part, which has been modified.

**Comment by Sunnyiscoming** [comment]
@[newwebgroup](https://github.com/newwebgroup) Wanjing media is 万璟传媒? Could you please clarify the client's Chinese company name?

**Comment by newwebgroup** [comment]
> @newwebgroup[万](https://github.com/newwebgroup)景传媒是万璟传媒？能否请您澄清一下客户的中国公司名称？

Yes，The Chinese name of this customer is' 万鲸传媒 '

**Comment by newwebgroup** [comment]
> I have sent a message to the douyin provided. Please check that.

Hi @Sunnyiscoming 
Can you tell me which account you wrote to?
Just now, I asked our customer to check the private letter of "我叫星然啊"“带你吃瓜” Tiktok account, but I didn't find the message you sent.

Can you send it again? And tell me which account you sent the message to, and the sending time.


带你吃瓜：https://www.douyin.com/user/MS4wLjABAAAAhraWM86XeU3vEpfo7_yZaUhX5uwpOliUpU255LC8K_ifWH-1VsczXyke1t8skR4f
我是星然：https://www.douyin.com/user/MS4wLjABAAAAvgSfPrLtxuvpdfmHHsSsOkcLu2ihsvHLAitVuj9VHvY

**Comment by newwebgroup** [comment]
We found a message suspected of being sent by you in the "带你吃瓜" account private letter, and have replied.

**Comment by Sunnyiscoming** [comment]
Ok, I have seen that.
@newwebgroup  Hey. Could you send an email to filplus@fil.org with your official domain in order to confirm your identity?

**Comment by newwebgroup** [comment]
> Ok, I have seen that. @newwebgroup Hey. Could you send an email to [filplus@fil.org](mailto:filplus@fil.org) with your official domain in order to confirm your identity?

@Sunnyiscoming  Hey，Of course, do you want us to send mail using **New web group** or using **Wanjing media**?

**Comment by newwebgroup** [comment]
<img width="922" alt="image" src="https://user-images.githubusercontent.com/100118145/176599184-2723b8ee-7cbe-45b2-bf68-8ce54f34aa6b.png">
I have sent an email, please check it.
I explained some questions about Wanjing media data in my email
What is it? Where did it come from? How many? And other relevant information @galen-mcandrew @Sunnyiscoming

**Comment by newwebgroup** [comment]
<img width="672" alt="image" src="https://user-images.githubusercontent.com/100118145/177736769-f7243f2a-2f48-4938-a7cc-f318b4006e6e.png">
Hi Galen @galen-mcandrew   Deep @dkkapur   and  @Sunnyiscoming 

**The latest good news** 
through our communication with customers, all data can be made public and can be retrieved by everyone.

**Comment by galen-mcandrew** [comment]
## Datacap Request Trigger
#### Total DataCap requested 
> 3PiB
#### Expected weekly DataCap usage rate 
> 200TiB 
#### Client address
> f126k3tkdwfaqpflgcclkiwhqxhh73ebqqazwgcoy

**Comment by galen-mcandrew** [comment]
Heads up! [This notary](https://github.com/filecoin-project/notary-governance/issues/422) was also ratified in round 3, and should **not** be signing any allocation proposals or approvals for this client app.

Notary Address: f1e77zuityhvvw6u2t6tb5qlnsegy2s67qs4lbbbq

**Comment by kernelogic** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebs2cpsloa5ly6bj6kojk25nmrbygmmixpwzl7wre6f3jjdn6kcvc 
#### Address 
> f126k3tkdwfaqpflgcclkiwhqxhh73ebqqazwgcoy
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebs2cpsloa5ly6bj6kojk25nmrbygmmixpwzl7wre6f3jjdn6kcvc

**Comment by Joss-Hua** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecpzqpdhxzom3nk5umd3p43xheosa4kshdzhvtdq6fbjuwnkft7x4 
#### Address 
> f126k3tkdwfaqpflgcclkiwhqxhh73ebqqazwgcoy
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1tfg54zzscugttejv336vivknmsnzzmyudp3t7wi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecpzqpdhxzom3nk5umd3p43xheosa4kshdzhvtdq6fbjuwnkft7x4

**Comment by kernelogic** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedrbxue6xk7v6lvbryrftkoehs2oka25f5myiavvwnpgznxaro6im 
#### Address 
> f126k3tkdwfaqpflgcclkiwhqxhh73ebqqazwgcoy
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedrbxue6xk7v6lvbryrftkoehs2oka25f5myiavvwnpgznxaro6im

**Comment by liyunzhi-666** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebt3zbyvqgs22pxvx7i4p53ow7z7j3uj7zpqqvsulsrwpzm6fc5ti 
#### Address 
> f126k3tkdwfaqpflgcclkiwhqxhh73ebqqazwgcoy
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1pszcrsciyixyuxxukkvtazcokexbn54amf7gvoq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebt3zbyvqgs22pxvx7i4p53ow7z7j3uj7zpqqvsulsrwpzm6fc5ti

**Comment by 1LISA2** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecgb5mrmmbtx4ff6hetdrrluwr3gx3jzloe7pz2ogni75n26pqpbs 
#### Address 
> f126k3tkdwfaqpflgcclkiwhqxhh73ebqqazwgcoy
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1jvvltduw35u6inn5tr4nfualyd42bh3vjtylgci
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecgb5mrmmbtx4ff6hetdrrluwr3gx3jzloe7pz2ogni75n26pqpbs

**Comment by kernelogic** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaqrs3jl6uasobxpmoykmmrdz3nm4r62uarlozk2laka6aacbjr62 
#### Address 
> f126k3tkdwfaqpflgcclkiwhqxhh73ebqqazwgcoy
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaqrs3jl6uasobxpmoykmmrdz3nm4r62uarlozk2laka6aacbjr62

**Comment by stcouldlisa** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacearqqbyebfkfbmeg5mryu2lneb5jzqsiculhwhigukrbg2yjq26bg 
#### Address 
> f126k3tkdwfaqpflgcclkiwhqxhh73ebqqazwgcoy
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1jvvltduw35u6inn5tr4nfualyd42bh3vjtylgci
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacearqqbyebfkfbmeg5mryu2lneb5jzqsiculhwhigukrbg2yjq26bg

**Comment by newwebgroup** [comment]
@fabriziogianni7 
Hello， Sir，

Here come some problems that will require your help.
From the records above, it should be the system that misled the order of approvals due to multiple proposal, resulting in confusing TX IDs.
Should have been approved for 400t, only 200t was obtained.

**Comment by Tom-OriginStorage** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced4jyxfupuzeujgget2nm3bv42eg3n2sjhbazsu4pvcizqrirb5ic 
#### Address 
> f126k3tkdwfaqpflgcclkiwhqxhh73ebqqazwgcoy
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1q6bpjlqia6iemqbrdaxr2uehrhpvoju3qh4lpga
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced4jyxfupuzeujgget2nm3bv42eg3n2sjhbazsu4pvcizqrirb5ic

**Comment by Reiers** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebd5ffykmmwepozywq7fqqihn7sc5o2tmxibu35g25jrnkhol3754 
#### Address 
> f126k3tkdwfaqpflgcclkiwhqxhh73ebqqazwgcoy
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1oz43ckvmtxmmsfzqm6bpnemqlavz4ifyl524chq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebd5ffykmmwepozywq7fqqihn7sc5o2tmxibu35g25jrnkhol3754

**Comment by kernelogic** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedp65jylr45hohunr7ds2gic7dy4kznt26t6ddfa5ifgy43o7rete 
#### Address 
> f126k3tkdwfaqpflgcclkiwhqxhh73ebqqazwgcoy
#### Datacap Allocated
> 1.56PiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedp65jylr45hohunr7ds2gic7dy4kznt26t6ddfa5ifgy43o7rete

**Comment by liyunzhi-666** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec6cocsegn5l4vpqxsn6etfx3wx2lgtrrvrdw5p5jkzpodz4hoyhw 
#### Address 
> f126k3tkdwfaqpflgcclkiwhqxhh73ebqqazwgcoy
#### Datacap Allocated
> 1.56PiB
#### Signer Address
> f1pszcrsciyixyuxxukkvtazcokexbn54amf7gvoq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec6cocsegn5l4vpqxsn6etfx3wx2lgtrrvrdw5p5jkzpodz4hoyhw

**Comment by liyunzhi-666** [comment]
hey @newwebgroup.I noticed that one of your SP nodes has exceeded 35%, please reduce this ratio in the next allocation.

<img width="1229" alt="image" src="https://user-images.githubusercontent.com/52949274/193235165-2919e62f-ff27-401c-987b-dd3fb20f6be6.png">

**Comment by newwebgroup** [comment]
Thank you for your reminder @liyunzhi-666 

This LDN does not belong to Newwebgroup, which is just a service provider providing technology. Wanjing Media is the Client.
I will remind our client, Wanjing Media, to pay attention to the reasonable distribution of the proportion.

Because of the impact of the new crown epidemic, some data cannot be transmitted to the location of the SP in time, so the packaging speed has decreased.
I have reminded the SP with too high storage capacity ratio to suspend the storage speed.
Wait until the overall proportion is relatively average, and then start to store the data in the Filecoin network.

You can get some data of Wanjing Media through these links. I hope you like it.
China tiktok link
https://www.douyin.com/user/MS4wLjABAAAAhraWM86XeU3vEpfo7_yZaUhX5uwpOliUpU255LC8K_ifWH-1VsczXyke1t8skR4f
https://www.douyin.com/user/MS4wLjABAAAAvgSfPrLtxuvpdfmHHsSsOkcLu2ihsvHLAitVuj9VHvY

**Comment by filplus-checker** [comment]
## DataCap and CID Checker Report[^1]
 - Organization: `New Web Group`
 - Client: `f126k3tkdwfaqpflgcclkiwhqxhh73ebqqazwgcoy`
### Storage Provider Distribution
The below table shows the distribution of storage providers that have stored data for this client.

If this is the first time a provider takes verified deal, it will be marked as `new`.

For most of the datacap application, below restrictions should apply.
 - Storage provider should not exceed 25% of total datacap.
 - Storage provider should not be storing duplicate data for more than 20%.
 - Storage provider should have published its public IP address.
 - All storage providers should be located in different regions.

⚠️ 58.14% of total deal sealed by [f01901815](https://filfox.info/en/address/f01901815) are duplicate data.

⚠️ 56.67% of total deal sealed by [f01699999](https://filfox.info/en/address/f01699999) are duplicate data.

⚠️ 57.30% of total deal sealed by [f01919535](https://filfox.info/en/address/f01919535) are duplicate data.

⚠️ 38.65% of total deal sealed by [f01890287](https://filfox.info/en/address/f01890287) are duplicate data.

⚠️ 24.56% of total deal sealed by [f01901773](https://filfox.info/en/address/f01901773) are duplicate data.

⚠️ 89.50% of total deal sealed by [f01935005](https://filfox.info/en/address/f01935005) are duplicate data.

⚠️ 89.38% of total deal sealed by [f01945176](https://filfox.info/en/address/f01945176) are duplicate data.

⚠️ 20.91% of total deal sealed by [f01876488](https://filfox.info/en/address/f01876488) are duplicate data.

⚠️ 22.18% of total deal sealed by [f01953959](https://filfox.info/en/address/f01953959) are duplicate data.

⚠️ 70.03% of total deal sealed by [f0428306](https://filfox.info/en/address/f0428306) are duplicate data.

| Provider                                                    |                           Location | Total Deals Sealed | Percentage | Unique Data | Duplicate Deals |
| :---------------------------------------------------------- | ---------------------------------: | -----------------: | ---------: | ----------: | --------------: |
| [f01901815](https://filfox.info/en/address/f01901815)`new`  | Hong Kong, Central and Western, HK |         516.28 TiB |     19.15% |  216.09 TiB |          58.14% |
| [f01699999](https://filfox.info/en/address/f01699999)       |           Zhongshan, Guangdong, CN |         501.56 TiB |     18.60% |  217.34 TiB |          56.67% |
| [f01919535](https://filfox.info/en/address/f01919535)       |                   Wuhan, Hubei, CN |         303.47 TiB |     11.25% |  129.59 TiB |          57.30% |
| [f01890287](https://filfox.info/en/address/f01890287)       |             Shanghai, Shanghai, CN |         293.34 TiB |     10.88% |  179.97 TiB |          38.65% |
| [f01901773](https://filfox.info/en/address/f01901773)`new`  | Hong Kong, Central and Western, HK |         214.00 TiB |      7.94% |  161.44 TiB |          24.56% |
| [f01942420](https://filfox.info/en/address/f01942420)`new`  |           Guangzhou, Guangdong, CN |         162.41 TiB |      6.02% |  162.41 TiB |           0.00% |
| [f01942425](https://filfox.info/en/address/f01942425)`new`  |           Guangzhou, Guangdong, CN |         154.53 TiB |      5.73% |  154.53 TiB |           0.00% |
| [f01935005](https://filfox.info/en/address/f01935005)`new`  |             Hangzhou, Zhejiang, CN |         127.06 TiB |      4.71% |   13.34 TiB |          89.50% |
| [f01945176](https://filfox.info/en/address/f01945176)`new`  |             Hangzhou, Zhejiang, CN |         125.00 TiB |      4.64% |   13.28 TiB |          89.38% |
| [f01907545](https://filfox.info/en/address/f01907545)`new`  |                 Xi’an, Shaanxi, CN |          99.84 TiB |      3.70% |   96.28 TiB |           3.57% |
| [f01876488](https://filfox.info/en/address/f01876488)       |  Ho Chi Minh City, Ho Chi Minh, VN |          95.97 TiB |      3.56% |   75.91 TiB |          20.91% |
| [f01953959](https://filfox.info/en/address/f01953959)`new`  |           Singapore, Singapore, SG |          50.44 TiB |      1.87% |   39.25 TiB |          22.18% |
| [f0428306](https://filfox.info/en/address/f0428306)`new`    |             Hangzhou, Zhejiang, CN |          44.31 TiB |      1.64% |   13.28 TiB |          70.03% |
| [f01901351](https://filfox.info/en/address/f01901351)`new`  |               Chengdu, Sichuan, CN |           7.72 TiB |      0.29% |    6.97 TiB |           9.72% |
| [f01852677](https://filfox.info/en/address/f01852677)       |    Morrisville, North Carolina, US |         352.00 GiB |      0.01% |  352.00 GiB |           0.00% |
| [f0469055](https://filfox.info/en/address/f0469055)`new`    |           Zhongshan, Guangdong, CN |         128.00 GiB |      0.00% |  128.00 GiB |           0.00% |
| [f01132569](https://filfox.info/en/address/f01132569)`new`  |           Guangzhou, Guangdong, CN |          64.00 GiB |      0.00% |   64.00 GiB |           0.00% |
| [f01885088](https://filfox.info/en/address/f01885088)       | Hong Kong, Central and Western, HK |          32.00 GiB |      0.00% |   32.00 GiB |           0.00% |
| [f01113378](https://filfox.info/en/address/f01113378)`new`  |             Hangzhou, Zhejiang, CN |          32.00 GiB |      0.00% |   32.00 GiB |           0.00% |
| [f01089422](https://filfox.info/en/address/f01089422)`new`  |           Zhongshan, Guangdong, CN |          32.00 GiB |      0.00% |   32.00 GiB |           0.00% |

![Provider Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/356/1671095360051.png)
### Deal Data Replication
The below table shows how each many unique data are replicated across storage providers.
- No more than 25% of unique data are stored with less than 4 providers.

✔️ Data replication looks healthy.

| Unique Data Size | Total Deals Made | Number of Providers | Deal Percentage |
| ---------------: | ---------------: | ------------------: | --------------: |
|        36.22 TiB |        46.03 TiB |                   1 |           1.71% |
|        21.25 TiB |       108.34 TiB |                   2 |           4.02% |
|        19.59 TiB |        95.03 TiB |                   3 |           3.52% |
|        37.59 TiB |       284.97 TiB |                   4 |          10.57% |
|        41.88 TiB |       339.84 TiB |                   5 |          12.60% |
|        34.06 TiB |       337.06 TiB |                   6 |          12.50% |
|        56.34 TiB |       664.97 TiB |                   7 |          24.66% |
|        35.00 TiB |       499.97 TiB |                   8 |          18.54% |
|         6.66 TiB |       175.50 TiB |                   9 |           6.51% |
|         4.44 TiB |       144.84 TiB |                  10 |           5.37% |

![Replication Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/356/1671095360693.png)
### Deal Data Shared with other Clients
The below table shows how many unique data are shared with other clients.
Usually different applications owns different data and should not resolve to the same CID.

⚠️ CID sharing has been observed.

| Other Client                                                                                                                                                                                                              | Application                                                                                                                      | Total Deals Affected | Unique CIDs |          Verifier |
| :------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ | :------------------------------------------------------------------------------------------------------------------------------- | -------------------: | ----------: | ----------------: |
| [f16ioghg3qy36f6572viouwv4dqow5ejpolo4kodi](https://filfox.info/en/address/f16ioghg3qy36f6572viouwv4dqow5ejpolo4kodi)                                                                                                     | [Shenzhen kuaixue Education Development Co\., Ltd](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/512)  |             1.20 PiB |         943 |   LDN v3 multisig |
| [f1t3buz7oqz4fktpthqe43vauhzlnuztpgm3iyhbi](https://filfox.info/en/address/f1t3buz7oqz4fktpthqe43vauhzlnuztpgm3iyhbi)                                                                                                     | [Shenzhen kuaixue Education Development Co\., Ltd](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1363) |           477.50 TiB |         943 |   LDN v3 multisig |
| [f3v7x4a2aapgx6o2r477tenoin3u5oadaeqyd7kjd<br/>sitykvf4ok7vq2utcyh34lmu5u7oybs25ff6s4dbu<br/>dpma](https://filfox.info/en/address/f3v7x4a2aapgx6o2r477tenoin3u5oadaeqyd7kjdsitykvf4ok7vq2utcyh34lmu5u7oybs25ff6s4dbudpma) | [LeoCheung \- Slingshot Restore](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/151)                    |            52.44 TiB |       1,342 |   LDN v3 multisig |
| [f1tb2hrxk5eaeewcesnid6xmvfkklfdrxsjr5k6iy](https://filfox.info/en/address/f1tb2hrxk5eaeewcesnid6xmvfkklfdrxsjr5k6iy)                                                                                                     | [Yisainuo](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/537)                                          |            50.41 TiB |         910 |   LDN v3 multisig |
| [f1unz5yuxgui573lpuh2wyxpsx5ahvw5farqb7hji](https://filfox.info/en/address/f1unz5yuxgui573lpuh2wyxpsx5ahvw5farqb7hji)                                                                                                     | `AOLIGEI`                                                                                                                        |            13.31 TiB |         426 |   LDN v3 multisig |
| [f3qebbkqspq4w6deouaubtngt4bmaada76uqs3omy<br/>3tki6hoeocpgxyplknev5u3oi5e7xnltobrvgxnpa<br/>3qga](https://filfox.info/en/address/f3qebbkqspq4w6deouaubtngt4bmaada76uqs3omy3tki6hoeocpgxyplknev5u3oi5e7xnltobrvgxnpa3qga) | [codex8080 \- Slingshot Restore](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/152)                    |             3.16 TiB |         101 |   LDN v3 multisig |
| [f3xgpw2lnfkk24h5na6gqyrrapx5gk75haem4zeep<br/>6v7bm4pcuykot3ceqd5lonenrxw4sxvqjymxtaihe<br/>4una](https://filfox.info/en/address/f3xgpw2lnfkk24h5na6gqyrrapx5gk75haem4zeep6v7bm4pcuykot3ceqd5lonenrxw4sxvqjymxtaihe4una) | Unknown                                                                                                                          |            32.00 GiB |           1 |           Unknown |
| [f1x7wsqpj6waymzzfqmu4hh32tyc4pbbqnpwy2ucq](https://filfox.info/en/address/f1x7wsqpj6waymzzfqmu4hh32tyc4pbbqnpwy2ucq)                                                                                                     | `Glif auto verified`                                                                                                             |            32.00 GiB |           1 | Jonathan Schwartz |
| [f3qlswwr34nwyleul5mqyh7kh4job5hcw7cklasay<br/>6ldttdfgvcfpkv2urtf72dfynpehkge7ctpgrelpk<br/>e55a](https://filfox.info/en/address/f3qlswwr34nwyleul5mqyh7kh4job5hcw7cklasay6ldttdfgvcfpkv2urtf72dfynpehkge7ctpgrelpke55a) | Unknown                                                                                                                          |            32.00 GiB |           1 |           Unknown |

[^1]: To manually trigger this report, add a comment with text `checker:manualTrigger`
