### ISSUE TITLE
[DataCap Allocation] - Autonomous driving big data

### ISSUE THREAD

**Issue by hajeungwoo** [filecoin-project/filecoin-plus-large-datasets#358]
---
name: Large Dataset Notary application
about: Clients should use this application form to request a DataCap allocation via a LDN for a dataset
title: "[DataCap Application] - Autonomous driving big data"
labels: 'application, Phase: Diligence'
assignees: ''

---
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Bumi Co., Ltd.
- Website / Social Media: http://www.bumi.co.kr/eng/ 
- Region: Asia (excl. Greater China)
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 2PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100TiB
- On-chain address for first allocation: f1ll4zafrefwklbuwbuptmz67ifemc62xapfaqm3q

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Bumi has been manufacturing automobile parts such as brackets, fittings, spirals, tubes, insert metals etc. over a 40-year history.
Its outstanding technology in design and production of goods and moulds and a perfect package of equipment and facilities enabling mass production bring the company reliability and recognition from the customer companies by means of differentiated quality and scale.
Now the parts of the company are applied to the prevalent automobile models of Hyundai, Kia, GM Daewoo, Renault Samsung, Ssangyong Motors in Korea, and the overseas models of Cooper Standard (USA), Hitach Cable (Japan), Suntech (Japan), Nitzirin (Japan), Rainbow (Taiwan), Hutchinson (France, USA, Poland, Portugal, Mexico), Imperial (India), Sanoh (Mexico) etc.

```

What is the primary source of funding for this project?
```
Company account
```

What other projects/ecosystem stakeholders is this project associated with?
```
Electronic machinery, auto parts, B2B QC DATA (high-definition video, high-definition photos) Customer marketing Online parts public data and all online contents generated in the course of work are safely stored and provided to customers in the following cases.

```

## Use-case details

Describe the data being stored onto Filecoin
```
It is related to car parts, autonomous driving videos, and photos.
```

Where was the data in this dataset sourced from?
```
For publicity of public data or produced by the company
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```

It is for publicity purposes only and is open.
(http://bumi.co.kr/_public/images/product/pd.png
http://bumi.co.kr/_public/images/product/pd11.png
http://bumi.co.kr/_public/images/product/pd15.png
http://bumi.co.kr/_public/images/product/pd12.png
http://bumi.co.kr/_public/images/product/pd21.png)
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
YES. 
```

What is the expected retrieval frequency for this data?
```
Multiple times.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
30 months or longer
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Asia excl. Greater China
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
The data will be transferred both offline and online.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
Storage providers will be carefully selected, and through continuous development, anyone will be able to search.
```

How will you be distributing deals across storage providers?
```
It mainly depends on storage provider’s willing.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, we have the resources.
```

**Comment by hajeungwoo** [comment]
hello.
How long will it take?

**Comment by UnionLabs2020** [comment]
Autonomous driving videos belongs to highly sensitive data, which may cause unnecessary legal risks.

**Comment by hajeungwoo** [comment]
It seems wrong.
It is a roadmap map, related to automobile parts, etc.
No problem at all.
All data is publicly available for anyone to see.

**Comment by Sunnyiscoming** [comment]
Hello, @hajeungwoo, you have applied for Datacap many times.

For example, 
https://github.com/filecoin-project/filecoin-plus-client-onboarding/issues/982
https://github.com/filecoin-project/filecoin-plus-client-onboarding/issues/1160

You said that you would look for 4 SPs, but you stored all the datacap on the one SP node. Could you give a brief explanation.

https://filplus.d.interplanetary.one/clients/f01452734/breakdown
https://filplus.d.interplanetary.one/clients/f01345472/breakdown

**Comment by hajeungwoo** [comment]
For us, this is a small capacity. I prefer offline and signed a contract with a well-managed company. An additional contract with one other company has been completed. There is currently no datacap, so it is impossible to proceed.

**Comment by Sunnyiscoming** [comment]
@hajeungwoo Can you specify storage service providers or nodes?

**Comment by hajeungwoo** [comment]
@Sunnyiscoming This is the f081078 company. Is it a problem?

**Comment by hajeungwoo** [comment]
Too much time wasted. Please help me

**Comment by Sunnyiscoming** [comment]
@hajeungwoo Large datasets require decentralizated storage, so a node does not meet the community requirements. Have you contacted other storage providers?

**Comment by hajeungwoo** [comment]
@Sunnyiscoming yes. 
We have contracted with other companies and will store them distributedly.

**Comment by hajeungwoo** [comment]
It will be distributed and stored with 2-3 companies.
Any other issues?

**Comment by Sunnyiscoming** [comment]
Can you list nodes of storage providers here?

**Comment by hajeungwoo** [comment]
f01776341,f081078,f01319989 3 companies are 30%. It will be sent at 80% random.

**Comment by AnthnoySmith** [comment]
> Hello, @hajeungwoo, you have applied for Datacap many times.
> 
> For example, [filecoin-project/filecoin-plus-client-onboarding#982](https://github.com/filecoin-project/filecoin-plus-client-onboarding/issues/982) [filecoin-project/filecoin-plus-client-onboarding#1160](https://github.com/filecoin-project/filecoin-plus-client-onboarding/issues/1160)
> 
> You said that you would look for 4 SPs, but you stored all the datacap on the one SP node. Could you give a brief explanation.
> 
> https://filplus.d.interplanetary.one/clients/f01452734/breakdown https://filplus.d.interplanetary.one/clients/f01345472/breakdown

Please share your rootcid and SP node, we need to have a check whether the dataset can be downloaded?

**Comment by hajeungwoo** [comment]
Online has upload limit. If you upload more than a certain amount per day, the speed will decrease. So we prefer offline. We've been asking for it for a long time. In order to upload to as many companies as possible, we made a contract with three companies, and we disclosed them here. However, I was asked the same question several times. I am very sorry and very disappointed. We don't want our time to be wasted.

**Comment by Sunnyiscoming** [comment]
https://whatismyipaddress.com/ip/220.119.144.84
https://whatismyipaddress.com/ip/121.156.92.230
![image](https://user-images.githubusercontent.com/105098820/179927855-36cc4598-82f5-4b82-828d-56a2a4142202.png)
https://filrep.io/?search=f081078
![image](https://user-images.githubusercontent.com/105098820/179928162-dbd37aa8-89ce-46bc-a88f-093a28bb1d37.png)

**Comment by Sunnyiscoming** [comment]
Any update here?

**Comment by hajeungwoo** [comment]
@Sunnyiscoming No more time to request a datacap. It's been over 3 months. The company doesn't wait. Let's find another way. sorry.
