### ISSUE TITLE
[DataCap Application]Beijing Briskvision Culture and Broadcast Co., Ltd.

### ISSUE THREAD

**Issue by BriskvisionCulture** [filecoin-project/filecoin-plus-large-datasets#359]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Beijing Briskvision Culture and Broadcast Co., Ltd.
- Website / Social Media: website: https://www.briskvision.cn/      Wechat: 视觉灵动
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):100TiB
- On-chain address for first allocation: f1aimdegciywract2vmx2ubse7hgl3plx3fa4g6ya

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Beijing Briskvision Culture and Broadcast Co., Ltd. aims to provide high-profile commercial solutions for excellence enterprises in China. Briskvision is specialized in business overall image commercial, business activity broadcasting, product promotion, TV advertising, and Microfilm making.
Through years of work in the industry, Briskvision acquired various successful experiences from the previous projects, and willing to share the experiences with the client in order to help decision-making of the client side.Briskvision was always focused on budget management, which offered reasonable and competitive prices. Through conservation of the expenditures of the projects, optimize the procedures, to control the budget.Briskvision utilized the pricing system, in order to achieve a win-win situation with the clients.
In the recent years, Briskvision also built up firm partnerships with plenty of 4A Class public relation agencies, which enhanced our team to be more advanced and internationalize.Briskvision takes a pragmatic, innovative, breakthrough style, and has won the praise of many customers and the companies in the industry.
```

What is the primary source of funding for this project?
```
Operating income 
```

What other projects/ecosystem stakeholders is this project associated with?
```
Those companies and projects who cooperate with us were shown in our website. 
```

## Use-case details

Describe the data being stored onto Filecoin
```
The data stored on Filecoin is currently the publicly available data, including image commercial, business activity broadcasting, product promotion, TV advertising, and Microfilm making.
```

Where was the data in this dataset sourced from?
```
From our company. 
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://pan.baidu.com/share/init?surl=zxAWTs2zvd5JSnj77tl79g
code：sq4e
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes, it is. 
```

What is the expected retrieval frequency for this data?
```
Retrieval frequency will be low.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
At least few years. 
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Asia, USA, EU
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
For now, we have a platform to store our data. Storage provider can download from that platform. Also, some data we needs to transfer through offline method. 
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We know that we should choose SPs as decentralized as possible. There are many providers we are communicating. 
```

How will you be distributing deals across storage providers?
```
Each provider will not receive more than 20% of my datacap. 
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes! We are ready for storage very soon. 
```

**Comment by dkkapur** [comment]
@BriskvisionCulture Can you email [filplus@fil.org](mailto:filplus@fil.org) with your official work email so we can share this with notaries as a form of proof that you represent this organization?

**Comment by galen-mcandrew** [comment]
Due to no reply from client, we are closing this issue for now. When ready, please reopen or submit a new request here: https://plus.fil.org/ldn-application
