### ISSUE TITLE
[DataCap Application] Ecology Limited

### ISSUE THREAD

**Issue by EcologyLtd** [filecoin-project/filecoin-plus-large-datasets#36]
# Large Dataset Notary Application

To apply for a DataCap allocation for your dataset, please fill out the following information.

## Core Information
- Organization Name: Ecology Limited
- Website / Social Media: Slack@Ecology; Email: Ecology.ltd@outlook.com
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 200TiB
- On-chain address for first allocation: f3vygs6wslfvenruzrrbez5yelczv2jjoii4wlvd6yuyb3snm7sajh2ngjflhdntzxewuzmeczy4j6q56fqdsq

_Please respond to the questions below in pargraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

## Project details

Share a brief history of your project and organization.
```
Ecology Limited is a trading firm specializing in cryptocurrencies and digital assets. Founded in 2017, we manage millions USD in digital assets and trade across different financial products. With a dynamic and talented team, we leverage technology, research, and risk management to identify strategic market opportunities.
```

What is the primary source of funding for this project?
```
We are a self-funded company. We trade our own capital at our own risk. 
```

What other projects/ecosystem stakeholders is this project associated with?
```
We have a global network with different blockchain projects.
```

## Use-case details

Describe the data being stored onto Filecoin
```
Being a trading firm, we collect tons of data on a daily base from market news, analytics platforms, exchanges, etc. Our algorithmic trading system and proprietary trade execution model rely on these database for being responsive to changing markets. 
The data being stored include, but is not limited to market news, on-chain data, price & volume tracking, analysis, project database and non-confidential trading strategies.
```

Where was the data in this dataset sourced from?
```
Exchanges, analytics platforms, on-chain data, market news, and our own database.
```

Can you share a sample of what is in the dataset? A link to a file, an image, a table, etc., are good examples of this. 
```
Yes. https://drive.google.com/drive/folders/1AQANDXMLkns6vmvQttdVZpIfACnUo65l
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes, the datasets can be retrieved by anyone on the network. We might encrypt the sensitive data if there is any.
```

What is the expected retrieval frequency for this data?
```
We expect that retrieval may be sporadic.
```

For how long do you plan to keep this dataset stored on Filecoin? Will this be a permanent archival or a one-time storage deal?
```
We intend to store this dataset as long as possible. 
```

## DataCap allocation plan

In which geographies do you plan on making storage deals?
```
We are open to all regions. Preferably Canada, Singapore and China as we have team based there.  
```

What is your expected data onboarding rate? How many deals can you make in a day, in a week? How much DataCap do you plan on using per day, per week?
```
We will be able to store 200-800TiB per week.
```

How will you be distributing your data to miners? Is there an offline data transfer process?
```
Given the scale of the dataset, we plan to use an offline data transfer process.
```

How do you plan on choosing the miners with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We will choose about 30 different miners who are reputable and being active in the past 3 months.
```

How will you be distributing data and DataCap across miners storing data?
```
We expect to work with about 30 miners, and we will be distributing the data and DataCap based on their capacity and conditions. The miners also have to meet our requirements of minimum 12-month duration of storage.
```

**Comment by flyworker** [comment]
interesting to know the detail of the data, the sample dataset. why it is so big and how the data formatted.

**Comment by ozhtdong** [comment]
1475 would like to support this project if you can show data demo.

**Comment by EcologyLtd** [comment]
> interesting to know the detail of the data, the sample dataset. why it is so big and how the data formatted.

Hi Flyworker, 

Here’s a link to our data sample, in csv format. (https://drive.google.com/drive/folders/1AQANDXMLkns6vmvQttdVZpIfACnUo65l) 
Pls feel free to let us know if you need more information :)

**Comment by EcologyLtd** [comment]
> 1475 would like to support this project if you can show data demo.

Hi there, many thanks for your support! 
Here’s a link to our data sample: https://drive.google.com/drive/folders/1AQANDXMLkns6vmvQttdVZpIfACnUo65l

**Comment by DarnellWashington** [comment]
That sounds awesome.

**Comment by ozhtdong** [comment]
> > 1475 would like to support this project if you can show data demo.
> 
> Hi there, many thanks for your support!
> Here’s a link to our data sample: https://drive.google.com/drive/folders/1AQANDXMLkns6vmvQttdVZpIfACnUo65l

After inspection, it was indeed a large data structure,  1475 would like to support real data application.

**Comment by Fenbushi-Filecoin** [comment]
After reviewing your data, we would like to support the application.

**Comment by swatchliu** [comment]
Count me in if your local notary would like to support you.

**Comment by IreneYoung** [comment]
Sounds good. The big data of trading is really useful and valuable for trading strategies. Count me in, please.

**Comment by EcologyLtd** [comment]
> Could you please provide your website for us？I‘m curious about it.

Hi there, at the moment we don’t have a website for promoting our company. But you can always reach out to us via email: Ecology.ltd@outlook.com

**Comment by rayshitou** [comment]
Sounds good, count me in.

**Comment by mendezy** [comment]
So how could we get any valuable public data?  via email every time？

**Comment by EcologyLtd** [comment]
> So how could we get any valuable public data? via email every time？

Thank you for bringing this up. The dataset will be listed properly which allows users to access data easily. In the meantime, we are actively working with some solution providers.

**Comment by flyworker** [comment]
After carefully reviewed the data source and format, Filswan have tools support those data format, we probably  can do some pre-work for it. Those data is useful for keeping history record  trading data for R&D purpose. They should not be dominated and controlled by big companies, we would like to support the project. If this project need a lead notary, we are willing to be the one.

**Comment by SFH535fh** [comment]
![4185c5e858676d135e2f0609f1eb3ea](https://user-images.githubusercontent.com/83384071/134631832-32547900-7fc7-45f6-b131-cdc8a05ca512.png)
I don’t think such a dataset meets the requirements of LDN.

**Comment by galen-mcandrew** [comment]
## Multisig Notary requested
#### Total DataCap requested 
> 5PiB
#### Expected weekly DataCap usage rate 
> 200TiB

**Comment by flyworker** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaorib44irafyeqvr24bns7cliotd6qw75wvfhwld6z6adzvenyfy 
#### Address 
> f3vygs6wslfvenruzrrbez5yelczv2jjoii4wlvd6yuyb3snm7sajh2ngjflhdntzxewuzmeczy4j6q56fqdsq
#### Datacap Allocated
> 100TiB
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaorib44irafyeqvr24bns7cliotd6qw75wvfhwld6z6adzvenyfy

**Comment by EcologyLtd** [comment]
@galen-mcandrew 
Hi Galen, how can we request for more datacap? For example 200TiB per week? 
We've optimized our data onboarding rate and the current datacap isn't really enough. Thanks!

**Comment by galen-mcandrew** [comment]
Hello, your weekly rate is set to 200TiB for now, but the large dataset process currently has new clients 'ramp up' the amount they get with each allocation. Specifically:

First allocation: lesser of 5% of total DataCap requested or 50% of weekly allocation rate
Second allocation: lesser of 10% of total DataCap requested or 100% of weekly allocation rate
Third allocation onwards: lesser of 20% of total DataCap request or 200% of weekly allocation rate

**Comment by EcologyLtd** [comment]
> Hello, your weekly rate is set to 200TiB for now, but the large dataset process currently has new clients 'ramp up' the amount they get with each allocation. Specifically:
> 
> First allocation: lesser of 5% of total DataCap requested or 50% of weekly allocation rate Second allocation: lesser of 10% of total DataCap requested or 100% of weekly allocation rate Third allocation onwards: lesser of 20% of total DataCap request or 200% of weekly allocation rate

Thanks for setting our weekly rate to 200TiB and well noted on the allocation ramp-up. 
Is multisig still requested from notaries for changing to 200TiB? @galen-mcandrew

**Comment by galen-mcandrew** [comment]
Looks like the subsequent allocation bot is not currently working, and checking verify.glif I'm seeing the client address f3vygs6wslfvenruzrrbez5yelczv2jjoii4wlvd6yuyb3snm7sajh2ngjflhdntzxewuzmeczy4j6q56fqdsq has <1TiB of DataCap remaining.

That said, checking the [deal allocation stats](https://filplus.d.interplanetary.one/clients?filter=f3vygs6wslfvenruzrrbez5yelczv2jjoii4wlvd6yuyb3snm7sajh2ngjflhdntzxewuzmeczy4j6q56fqdsq) and seeing deals made with only 2 storage proividers, and 90% of the deals with a single provider. Per your application:

> We expect to work with about 30 miners, and we will be distributing the data and DataCap based on their capacity and conditions. The miners also have to meet our requirements of minimum 12-month duration of storage.

So before we manually start a subsequent allocation, I'd like to hear more about your deal-making behavior.

**Comment by EcologyLtd** [comment]
> Looks like the subsequent allocation bot is not currently working, and checking verify.glif I'm seeing the client address f3vygs6wslfvenruzrrbez5yelczv2jjoii4wlvd6yuyb3snm7sajh2ngjflhdntzxewuzmeczy4j6q56fqdsq has <1TiB of DataCap remaining.
> 
> That said, checking the [deal allocation stats](https://filplus.d.interplanetary.one/clients?filter=f3vygs6wslfvenruzrrbez5yelczv2jjoii4wlvd6yuyb3snm7sajh2ngjflhdntzxewuzmeczy4j6q56fqdsq) and seeing deals made with only 2 storage proividers, and 90% of the deals with a single provider. Per your application:
> 
> > We expect to work with about 30 miners, and we will be distributing the data and DataCap based on their capacity and conditions. The miners also have to meet our requirements of minimum 12-month duration of storage.
> 
> So before we manually start a subsequent allocation, I'd like to hear more about your deal-making behavior.

Hi Galen, we actually tried to send orders to some miners but most of the orders didn’t go through. At the moment we have only managed to find 3 miners who can provide stable datacap storage. (f01238519, f01380788, f01264125)

We're also working on different ways to ensure the efficiency of orders and the stability of services. Currently we are testing with miners from different regions, some of them meet our criteria and they will receive our orders soon. 

Appreciate if you could start a subsequent allocation asap, thanks a lot!

**Comment by EcologyLtd** [comment]
Hi there, how should we follow up on this? Can we attend and clarify on the weekly notary meeting if that's more efficient? Thanks!

**Comment by galen-mcandrew** [comment]
Representatives from Ecology joined our Notary Governance call on 11.23 and provided some more details and context about the hurdles they have been facing with onboarding. The recording of that call will be available soon. 

In the meantime, the governance team will remove the diligence label and start the next allocation. We encourage notaries to review the information shared here and ask further questions!

**Comment by ozhtdong** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedfqm47nn555nwqp2gmi4jsp3zq776vsfnecnjoqlg6arbl3g2foo 
#### Address 
> f3vygs6wslfvenruzrrbez5yelczv2jjoii4wlvd6yuyb3snm7sajh2ngjflhdntzxewuzmeczy4j6q56fqdsq
#### Datacap Allocated
> 200TiB
#### Signer Address
> f1lwpw2bcv66pla3lpkcuzquw37pbx7ur4m6zvq2a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedfqm47nn555nwqp2gmi4jsp3zq776vsfnecnjoqlg6arbl3g2foo

**Comment by swatchliu** [comment]
We are willing to sign for the second round if you can keep the promise that allocated for 30 miners.

**Comment by xinaxu** [comment]
Hi notaries. I came across this client while searching for filplus clients to take deals. After checking all verified deals made by this client, I found out that a significant portion of the datacap are deals made with storage provider `f01264125` and `f01466173`. `f01466173` has an internal public IP address `10.x.x.x` while `f01264125` does not even has a published IP address. Since they have already accepted and sealed lots of verified deals from this client, it is very likely that the are on the same LAN so they can be reachable by the lotus daemon directly via libp2p. Other than potential self dealing, it is also making retrieval impossible as long as those storage providers do not expose a public IP address.

**Comment by EcologyLtd** [comment]
> Hi notaries. I came across this client while searching for filplus clients to take deals. After checking all verified deals made by this client, I found out that a significant portion of the datacap are deals made with storage provider `f01264125` and `f01466173`. `f01466173` has an internal public IP address `10.x.x.x` while `f01264125` does not even has a published IP address. Since they have already accepted and sealed lots of verified deals from this client, it is very likely that the are on the same LAN so they can be reachable by the lotus daemon directly via libp2p. Besides, it is also making retrieval impossible as long as those storage providers do not expose a public IP address.

Hi there, thanks for bringing this up. We’ve explained why most of the orders are sealed by 2 miners during the last Notary Governance Call (on 23 Nov). We will try to send deals to more miners for the following allocation. 
For the public IP issue, we do take and send orders through the Internet. We’ve checked with the miner and their explanation is that they adopted technologies such as dynamic IP and firewall for their own consideration. We will communicate with the miner if this doesn’t meet the requirements.

**Comment by EcologyLtd** [comment]
Hi there, 
May I know how should we start a subsequent allocation? 

A few updates from our side: 
- We’ve communicated with our storage providers and they have published their IP addresses.
- We have successfully sent deals to ~30 storage providers, and some of them have very good sealing capability. In the meantime we will keep trying more ways to improve the sealing efficiency.

**Comment by galen-mcandrew** [comment]
@swatchliu Did you see the above comments? This allocation needs one more notary signature.

**Comment by EcologyLtd** [comment]
> @swatchliu Did you see the above comments? This allocation needs one more notary signature.

Hi Galen, @swatchliu has already signed for the last allocation, which the bot is not showing here.
We’re running out of datacap for the 2nd allocation, and would like to apply for the subsequent allocation. Thanks

**Comment by dkkapur** [comment]
@galen-mcandrew @fabriziogianni7 - looks like the bot failed to pick this one up for the subsequent allocation. I see `f3vygs6wslfvenruzrrbez5yelczv2jjoii4wlvd6yuyb3snm7sajh2ngjflhdntzxewuzmeczy4j6q56fqdsq` has ~250 GiB of DataCap left. Should we manually trigger this one to unblock stats + enable notaries to decide the next allocation?

**Comment by fabriziogianni7** [comment]
@dkkapur @galen-mcandrew the log say:
`[Subsequent Allocation] Issue number 36 skipped --> bot:readyToSign is present`
I'll just remove the readyToSign label and the ssa bot will trigger in 2 hours from now.

**Comment by Fenbushi-Filecoin** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecuwiyhepq7qzhusf4s33mgrdpc2l766icu2dn5t4zdhjprt7t7lg 
#### Address 
> f3vygs6wslfvenruzrrbez5yelczv2jjoii4wlvd6yuyb3snm7sajh2ngjflhdntzxewuzmeczy4j6q56fqdsq
#### Datacap Allocated
> 400TiB
#### Signer Address
> f1yqydpmqb5en262jpottko2kd65msajax7fi4rmq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecuwiyhepq7qzhusf4s33mgrdpc2l766icu2dn5t4zdhjprt7t7lg

**Comment by ozhtdong** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebkkrrvoeddo42mwt4euhmz4yp46srro3efgjturkigmf6mf7qthq 
#### Address 
> f3vygs6wslfvenruzrrbez5yelczv2jjoii4wlvd6yuyb3snm7sajh2ngjflhdntzxewuzmeczy4j6q56fqdsq
#### Datacap Allocated
> 400TiB
#### Signer Address
> f1lwpw2bcv66pla3lpkcuzquw37pbx7ur4m6zvq2a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebkkrrvoeddo42mwt4euhmz4yp46srro3efgjturkigmf6mf7qthq

**Comment by dannyob** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedd4auwwoum6mjnndf7zyqd3le6rc6uumkq63xanvsobyz7ym44p4 
#### Address 
> f3vygs6wslfvenruzrrbez5yelczv2jjoii4wlvd6yuyb3snm7sajh2ngjflhdntzxewuzmeczy4j6q56fqdsq
#### Datacap Allocated
> 400TiB
#### Signer Address
> f1k6wwevxvp466ybil7y2scqlhtnrz5atjkkyvm4a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedd4auwwoum6mjnndf7zyqd3le6rc6uumkq63xanvsobyz7ym44p4

**Comment by EcologyLtd** [comment]
Hi there, could you pls help to approve the next allocation? Thanks!
@ozhtdong @IreneYoung @Fenbushi-Filecoin @rayshitou

**Comment by Reiers** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacectbngkizsge7kb265lsrotpiom33quxr7zqasxwdkuyvc2ej36ge 
#### Address 
> f3vygs6wslfvenruzrrbez5yelczv2jjoii4wlvd6yuyb3snm7sajh2ngjflhdntzxewuzmeczy4j6q56fqdsq
#### Datacap Allocated
> 400TiB
#### Signer Address
> f1oz43ckvmtxmmsfzqm6bpnemqlavz4ifyl524chq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacectbngkizsge7kb265lsrotpiom33quxr7zqasxwdkuyvc2ej36ge

**Comment by EcologyLtd** [comment]
Hi, Much appreciate it if you could help to approve the next allocation. Thanks a lot! 
@Reiers @Kevin-FF-USA @ozhtdong @IreneYoung @Fenbushi-Filecoin @rayshitou

**Comment by rayshitou** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec5bf4es74xvqtxwxroixsr3zj5qigpi3zf3emvusepvlc56amkfw 
#### Address 
> f3vygs6wslfvenruzrrbez5yelczv2jjoii4wlvd6yuyb3snm7sajh2ngjflhdntzxewuzmeczy4j6q56fqdsq
#### Datacap Allocated
> 1.56PiB
#### Signer Address
> f136bz32l2hlyad4npmfg5dngcdw3jk3tpcpoz2ja
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec5bf4es74xvqtxwxroixsr3zj5qigpi3zf3emvusepvlc56amkfw

**Comment by Reiers** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecizxc3hpsvg2y2plb6qgnfzhefitkt4i4naasalznaoguivf2sdi 
#### Address 
> f3vygs6wslfvenruzrrbez5yelczv2jjoii4wlvd6yuyb3snm7sajh2ngjflhdntzxewuzmeczy4j6q56fqdsq
#### Datacap Allocated
> 1.56PiB
#### Signer Address
> f1oz43ckvmtxmmsfzqm6bpnemqlavz4ifyl524chq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecizxc3hpsvg2y2plb6qgnfzhefitkt4i4naasalznaoguivf2sdi

**Comment by EcologyLtd** [comment]
Hi, Much appreciate it if you could help to approve the next allocation. Thank you! @dannyob @rayshitou @flyworker @Reiers @Fenbushi-Filecoin @IreneYoung

**Comment by Reiers** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec6djzfdqibgjgp4cc3bi4gvxppgakwskq6vgrl377yei6pwidgmy 
#### Address 
> f3vygs6wslfvenruzrrbez5yelczv2jjoii4wlvd6yuyb3snm7sajh2ngjflhdntzxewuzmeczy4j6q56fqdsq
#### Datacap Allocated
> 1.56PiB
#### Signer Address
> f1oz43ckvmtxmmsfzqm6bpnemqlavz4ifyl524chq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec6djzfdqibgjgp4cc3bi4gvxppgakwskq6vgrl377yei6pwidgmy

**Comment by rayshitou** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec5kbgoknricxaspykfltofgx4exs46r73mi5gjrjji4iyhaqncgo 
#### Address 
> f3vygs6wslfvenruzrrbez5yelczv2jjoii4wlvd6yuyb3snm7sajh2ngjflhdntzxewuzmeczy4j6q56fqdsq
#### Datacap Allocated
> 1.56PiB
#### Signer Address
> f136bz32l2hlyad4npmfg5dngcdw3jk3tpcpoz2ja
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec5kbgoknricxaspykfltofgx4exs46r73mi5gjrjji4iyhaqncgo

**Comment by EcologyLtd** [comment]
Hi there, Much appreciate it if you could help to approve the next allocation. Thank you! @dannyob @rayshitou @flyworker @Reiers @Fenbushi-Filecoin @IreneYoung

**Comment by flyworker** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedjowtgkjbu22j3sussipbutr3wxcedy5cfryiioucrpe7tlbru4o 
#### Address 
> f3vygs6wslfvenruzrrbez5yelczv2jjoii4wlvd6yuyb3snm7sajh2ngjflhdntzxewuzmeczy4j6q56fqdsq
#### Datacap Allocated
> 822.56TiB
#### Signer Address
> f1hlubjsdkv4wmsdadihloxgwrz3j3ernf6i3cbpy
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedjowtgkjbu22j3sussipbutr3wxcedy5cfryiioucrpe7tlbru4o

**Comment by Fenbushi-Filecoin** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec3iphetzdzcoe4aayfysxu7kuz6x4yuwuvohreiimxg7unqtsbtg 
#### Address 
> f3vygs6wslfvenruzrrbez5yelczv2jjoii4wlvd6yuyb3snm7sajh2ngjflhdntzxewuzmeczy4j6q56fqdsq
#### Datacap Allocated
> 822.56TiB
#### Signer Address
> f1yqydpmqb5en262jpottko2kd65msajax7fi4rmq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec3iphetzdzcoe4aayfysxu7kuz6x4yuwuvohreiimxg7unqtsbtg

**Comment by filplus-checker** [comment]
## DataCap and CID Checker Report[^1]
 - Organization: `Ecology Limited`
 - Client: `f3vygs6wslfvenruzrrbez5yelczv2jjoii4wlvd6yuyb3snm7sajh2ngjflhdntzxewuzmeczy4j6q56fqdsq`
### Storage Provider Distribution
The below table shows the distribution of storage providers that have stored data for this client.

If this is the first time a provider takes verified deal, it will be marked as `new`.

For most of the datacap application, below restrictions should apply.
 - Storage provider should not exceed 25% of total datacap.
 - Storage provider should not be storing duplicate data for more than 20%.
 - Storage provider should have published its public IP address.
 - All storage providers should be located in different regions.

⚠️ 78.15% of total deal sealed by [f01606675](https://filfox.info/en/address/f01606675) are duplicate data.

⚠️ 78.18% of total deal sealed by [f01606849](https://filfox.info/en/address/f01606849) are duplicate data.

⚠️ 76.76% of total deal sealed by [f01602479](https://filfox.info/en/address/f01602479) are duplicate data.

⚠️ 71.44% of total deal sealed by [f01641612](https://filfox.info/en/address/f01641612) are duplicate data.

⚠️ 85.51% of total deal sealed by [f01781851](https://filfox.info/en/address/f01781851) are duplicate data.

⚠️ 78.47% of total deal sealed by [f01716466](https://filfox.info/en/address/f01716466) are duplicate data.

⚠️ 42.96% of total deal sealed by [f01264125](https://filfox.info/en/address/f01264125) are duplicate data.

⚠️ 21.66% of total deal sealed by [f01466173](https://filfox.info/en/address/f01466173) are duplicate data.

⚠️ [f01466173](https://filfox.info/en/address/f01466173) has unknown IP location.

⚠️ [f01238519](https://filfox.info/en/address/f01238519) has unknown IP location.

⚠️ 74.02% of total deal sealed by [f01479781](https://filfox.info/en/address/f01479781) are duplicate data.

⚠️ 95.20% of total deal sealed by [f01380788](https://filfox.info/en/address/f01380788) are duplicate data.

⚠️ 33.03% of total deal sealed by [f01372912](https://filfox.info/en/address/f01372912) are duplicate data.

⚠️ 23.53% of total deal sealed by [f01208862](https://filfox.info/en/address/f01208862) are duplicate data.

⚠️ 23.53% of total deal sealed by [f01207045](https://filfox.info/en/address/f01207045) are duplicate data.

⚠️ 25.00% of total deal sealed by [f01240](https://filfox.info/en/address/f01240) are duplicate data.

⚠️ 44.44% of total deal sealed by [f01199442](https://filfox.info/en/address/f01199442) are duplicate data.

⚠️ 44.44% of total deal sealed by [f01199430](https://filfox.info/en/address/f01199430) are duplicate data.

⚠️ [f0137168](https://filfox.info/en/address/f0137168) has unknown IP location.

| Provider                                                    |                         Location | Total Deals Sealed | Percentage | Unique Data | Duplicate Deals |
| :---------------------------------------------------------- | -------------------------------: | -----------------: | ---------: | ----------: | --------------: |
| [f01606675](https://filfox.info/en/address/f01606675)       |             Montréal, Quebec, CA |           1.09 PiB |     21.89% |  244.82 TiB |          78.15% |
| [f01606849](https://filfox.info/en/address/f01606849)       |             Montréal, Quebec, CA |           1.09 PiB |     21.84% |  243.94 TiB |          78.18% |
| [f01602479](https://filfox.info/en/address/f01602479)`new`  |            Longueuil, Quebec, CA |           1.01 PiB |     20.24% |  240.75 TiB |          76.76% |
| [f01641612](https://filfox.info/en/address/f01641612)`new`  |             Montréal, Quebec, CA |         838.51 TiB |     16.38% |  239.45 TiB |          71.44% |
| [f01781851](https://filfox.info/en/address/f01781851)`new`  |         Singapore, Singapore, SG |         339.63 TiB |      6.63% |   49.23 TiB |          85.51% |
| [f01716466](https://filfox.info/en/address/f01716466)       |         Singapore, Singapore, SG |         228.66 TiB |      4.47% |   49.23 TiB |          78.47% |
| [f01264125](https://filfox.info/en/address/f01264125)`new`  |             Montréal, Quebec, CA |         127.59 TiB |      2.49% |   72.78 TiB |          42.96% |
| [f01466173](https://filfox.info/en/address/f01466173)`new`  |                          Unknown |          99.53 TiB |      1.94% |   77.97 TiB |          21.66% |
| [f01238519](https://filfox.info/en/address/f01238519)`new`  |                          Unknown |          67.38 TiB |      1.32% |   60.78 TiB |           9.79% |
| [f01479781](https://filfox.info/en/address/f01479781)`new`  |         Singapore, Singapore, SG |          57.91 TiB |      1.13% |   15.04 TiB |          74.02% |
| [f01380788](https://filfox.info/en/address/f01380788)`new`  |           Shanghai, Shanghai, CN |          44.91 TiB |      0.88% |    2.16 TiB |          95.20% |
| [f01666984](https://filfox.info/en/address/f01666984)       |               Dorval, Quebec, CA |          38.17 TiB |      0.75% |   34.82 TiB |           8.76% |
| [f01372912](https://filfox.info/en/address/f01372912)`new`  |         Singapore, Singapore, SG |           2.12 TiB |      0.04% |    1.42 TiB |          33.03% |
| [f01208862](https://filfox.info/en/address/f01208862)       | Heerhugowaard, North Holland, NL |           2.13 GiB |      0.00% |    1.63 GiB |          23.53% |
| [f01207045](https://filfox.info/en/address/f01207045)       | Heerhugowaard, North Holland, NL |           2.13 GiB |      0.00% |    1.63 GiB |          23.53% |
| [f01240](https://filfox.info/en/address/f01240)             | Heerhugowaard, North Holland, NL |           2.00 GiB |      0.00% |    1.50 GiB |          25.00% |
| [f01201327](https://filfox.info/en/address/f01201327)       | Heerhugowaard, North Holland, NL |           1.63 GiB |      0.00% |    1.63 GiB |           0.00% |
| [f01199442](https://filfox.info/en/address/f01199442)       | Heerhugowaard, North Holland, NL |           1.13 GiB |      0.00% |  640.00 MiB |          44.44% |
| [f01199430](https://filfox.info/en/address/f01199430)       | Heerhugowaard, North Holland, NL |           1.13 GiB |      0.00% |  640.00 MiB |          44.44% |
| [f01058790](https://filfox.info/en/address/f01058790)`new`  |                 Tokyo, Tokyo, JP |           1.13 GiB |      0.00% |    1.13 GiB |           0.00% |
| [f0871563](https://filfox.info/en/address/f0871563)         |             Beijing, Beijing, CN |         128.00 MiB |      0.00% |  128.00 MiB |           0.00% |
| [f01221675](https://filfox.info/en/address/f01221675)`new`  |    Uijeongbu-si, Gyeonggi-do, KR |         128.00 MiB |      0.00% |  128.00 MiB |           0.00% |
| [f0127896](https://filfox.info/en/address/f0127896)         |         Sofia, Sofia-Capital, BG |         128.00 MiB |      0.00% |  128.00 MiB |           0.00% |
| [f0137168](https://filfox.info/en/address/f0137168)         |                          Unknown |         128.00 MiB |      0.00% |  128.00 MiB |           0.00% |
| [f019551](https://filfox.info/en/address/f019551)           |          Birmingham, England, GB |         128.00 MiB |      0.00% |  128.00 MiB |           0.00% |
| [f020904](https://filfox.info/en/address/f020904)`new`      |                 Seoul, Seoul, KR |         128.00 MiB |      0.00% |  128.00 MiB |           0.00% |
| [f0401254](https://filfox.info/en/address/f0401254)`new`    |                 Seoul, Seoul, KR |         128.00 MiB |      0.00% |  128.00 MiB |           0.00% |
| [f0524489](https://filfox.info/en/address/f0524489)`new`    |    Uijeongbu-si, Gyeonggi-do, KR |         128.00 MiB |      0.00% |  128.00 MiB |           0.00% |
| [f0835643](https://filfox.info/en/address/f0835643)`new`    |     Seongnam-si, Gyeonggi-do, KR |         128.00 MiB |      0.00% |  128.00 MiB |           0.00% |
| [f0101087](https://filfox.info/en/address/f0101087)         |                 Seoul, Seoul, KR |         128.00 MiB |      0.00% |  128.00 MiB |           0.00% |

![Provider Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/36/1671091528617.png)
### Deal Data Replication
The below table shows how each many unique data are replicated across storage providers.
- No more than 25% of unique data are stored with less than 4 providers.

✔️ Data replication looks healthy.

| Unique Data Size | Total Deals Made | Number of Providers | Deal Percentage |
| ---------------: | ---------------: | ------------------: | --------------: |
|        81.58 TiB |       146.01 TiB |                   1 |           2.85% |
|        51.90 TiB |       601.74 TiB |                   2 |          11.75% |
|         8.63 TiB |        53.03 TiB |                   3 |           1.04% |
|       114.84 TiB |         1.74 PiB |                   4 |          34.90% |
|        62.19 TiB |         1.25 PiB |                   5 |          25.02% |
|        56.94 TiB |         1.19 PiB |                   6 |          23.72% |
|         1.31 TiB |        37.03 TiB |                   7 |           0.72% |
|       128.00 MiB |         2.13 GiB |                  17 |           0.00% |

![Replication Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/36/1671091529190.png)
### Deal Data Shared with other Clients
The below table shows how many unique data are shared with other clients.
Usually different applications owns different data and should not resolve to the same CID.

⚠️ CID sharing has been observed.

| Other Client                                                                                                                                                                                                              | Application                                                                                              | Total Deals Affected | Unique CIDs |        Verifier |
| :------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ | :------------------------------------------------------------------------------------------------------- | -------------------: | ----------: | --------------: |
| [f3vyn26odhgiu746qv4n4h3xv7u3bzntwwnnhzrcp<br/>pnhv52htgzkdg2war2pgi4kdoucneqzkl7wenj3mn<br/>jpea](https://filfox.info/en/address/f3vyn26odhgiu746qv4n4h3xv7u3bzntwwnnhzrcppnhv52htgzkdg2war2pgi4kdoucneqzkl7wenj3mnjpea) | [Epeng Times Technology Ltd](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/86) |           323.78 TiB |       1,934 |        LDN # 86 |
| [f1rb4fa2yoozp7ju6xlnau57uxbmhaf3blwz2njdi](https://filfox.info/en/address/f1rb4fa2yoozp7ju6xlnau57uxbmhaf3blwz2njdi)                                                                                                     | [ Define Platform](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/91)           |            32.00 GiB |           1 | LDN v3 multisig |

[^1]: To manually trigger this report, add a comment with text `checker:manualTrigger`

**Comment by Sunnyiscoming** [comment]
Hi, please explain the abnormal information.
