### ISSUE TITLE
[DataCap Application]filtakes

### ISSUE THREAD

**Issue by filtakes** [filecoin-project/filecoin-plus-large-datasets#363]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name:  filtakes
- Website / Social Media: http://www.filtakes.com/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100TiB
- On-chain address for first allocation:  f1l7b3sko5hqtpsb3pwjqqymh3ssoslucafzhd2jy

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Founded in 2021, filtakes is a technology company specialising in IPFS storage technology and web 3.0 applications, we provide  technical support services for various data companies.
 
We also collect public datasets in the fields of medicine and machine learning, and provide free data download support for medical and AI researchers to promote the progress and development of related fields worldwide.
```

What is the primary source of funding for this project?
```
This relies on the support of our shareholders.
```

What other projects/ecosystem stakeholders is this project associated with?
```
There is no other projects/ecosystem stakeholders associated with.
```

## Use-case details

Describe the data being stored onto Filecoin
```
We need to store  public datasets in the fields of medicine and machine learning.
```

Where was the data in this dataset sourced from?
```
Mainly from our collaborating research institutions and the public datasets we collect.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://filtakes.oss-cn-hangzhou.aliyuncs.com/files/healthcare-dataset.zip
https://filtakes.oss-cn-hangzhou.aliyuncs.com/files/monai-v060-deep-learning-in-healthcare-imaging.zip
https://filtakes.oss-cn-hangzhou.aliyuncs.com/files/siim-medical-images.zip
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes. I confirm that this is a public dataset that can be retrieved by anyone on the Network.
```

What is the expected retrieval frequency for this data?
```
About 10 times half a year.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
It will be a permanent archival storage deal.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
In the People's Republic of China.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Yes. We will adopt online transmission and offline transmission.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We hope to choose miners with good credit. This is the character we value.
```

How will you be distributing deals across storage providers?
```
We will follow the rules for large-datasets, and we will ensure fair distribution through limiting the amount of deals send to each miner. These records will be made and published regularly on Github.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
No, but we are developing some funding from some conmpanies who are interested in us.
```

**Comment by Sunnyiscoming** [comment]
Please provide the name of the organization that runs filtakes.

**Comment by Yvette516** [comment]
Can you provide more information about your organization And send  an email to filplus@fil.org from your official email account?

**Comment by Sunnyiscoming** [comment]
> Please provide the name of the organization that runs filtakes.
Any update here?

**Comment by filtakes** [comment]
hi @Sunnyiscoming @Yvette516 :
Sorry for the late reply,Our company is Fujian Endex Technology Co., LTD.We've been around IPFS and Filcoin for a long time and formed a company two years ago to focus on them.  Our company's website: http://www.endex.vip
Now we are ready to advance enterprise real data storage and drive the development of distributed storage industry. Filtakes is a business we do based on filcoin ecology, and we hope to participate in the ecological construction of Filcoin and develop together. 

The email has been sent to:  filplus@fil.org
Thanks.

**Comment by galen-mcandrew** [comment]
## Datacap Request Trigger
#### Total DataCap requested 
> 5PiB
#### Expected weekly DataCap usage rate 
> 100TiB 
#### Client address
> f1l7b3sko5hqtpsb3pwjqqymh3ssoslucafzhd2jy

**Comment by psh0691** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceby5vwzep46ftfw3j5rnzhdrpzvljwshsjiyoscc66pehwqpqjg5c 
#### Address 
> f1l7b3sko5hqtpsb3pwjqqymh3ssoslucafzhd2jy
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1qdko4jg25vo35qmyvcrw4ak4fmuu3f5rif2kc7i
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceby5vwzep46ftfw3j5rnzhdrpzvljwshsjiyoscc66pehwqpqjg5c

**Comment by MetaWaveInfo** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebxt55tlqrvwfiutgfa77hijnhq2nhtjcte3uncxkc6binefjuqn6 
#### Address 
> f1l7b3sko5hqtpsb3pwjqqymh3ssoslucafzhd2jy
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1ktlkcxnmzxcdaoqfsunrg3vocfbmgv4n3mrn74a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebxt55tlqrvwfiutgfa77hijnhq2nhtjcte3uncxkc6binefjuqn6

**Comment by BigD-Exchange** [comment]
@filtakes Hi! Great to see you have gotten approval for DataCap. If you are looking for more storage providers to store these data or have any questions, please visit #bigdata-exchange on Filecoin Slack or reply here. 

We have strong demand from a diverse group of SPs, who are actively looking to onboard more data.
