### ISSUE TITLE
[DataCap Application]CoinPhD

### ISSUE THREAD

**Issue by CoinPhD-official** [filecoin-project/filecoin-plus-large-datasets#364]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: CoinPhD
- Website / Social Media:https://www.coinphd.com/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 200TiB
- On-chain address for first allocation: f1dx7ljly4vmk5x2bn5ng4jpbqnuvozrz2phw42qy

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
The CoinPhD team is from well-known Internet and financial companies at home and abroad. It has deep accumulation of big data and AI technology, and has rich experience in intelligent quantitative strategy, graph calculation, data mining and blockchain data analysis.
CoinPhD is committed to advancing the development of digital assets through distributed big data AI analysis technology, helping individuals to obtain greater digital asset business value.
```

What is the primary source of funding for this project?
```
Our own fund.
```

What other projects/ecosystem stakeholders is this project associated with?
```
No
```

## Use-case details

Describe the data being stored onto Filecoin
```
SNS Media data, blockchain eco data, block data, market trade data. Mongodb, Json, Csv and other formats.
```

Where was the data in this dataset sourced from?
```
Ethereum Chain, Binance Smart Chain, NFT Metadara, Market Snapshot.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
[l_media_data.csv](https://github.com/filecoin-project/filecoin-plus-large-datasets/files/8692265/l_media_data.csv)
[kline_5m.csv](https://github.com/filecoin-project/filecoin-plus-large-datasets/files/8692266/kline_5m.csv)
[categoriy_snapshot.csv](https://github.com/filecoin-project/filecoin-plus-large-datasets/files/8692267/categoriy_snapshot.csv)
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes.
```

What is the expected retrieval frequency for this data?
```
Just 1-2 times a year.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
3 years.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
In Asia.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Mainly thought online storage deals. Yes, we'll prepare hard-disk for offline transfer.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We prefer that any SP who are willing to accept the deal.
```

How will you be distributing deals across storage providers?
```
We'll obey rules of filecoin to distribute these deals.Now, it is mainly based on the personal wishes of the storage providers. What’s more, we will manually select the storage providers who has high quality.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, we are ready to make deals.
```

**Comment by CoinPhD-official** [comment]
Is there anyone push my issue?

**Comment by swatchliu** [comment]
Thanks for your application, could you mail to filplus@fil.org and CC partner@bytebase.cn with your official domain mailbox in order to confirm your identity?

**Comment by CoinPhD-official** [comment]
Hello@swatchliu , we have sent an email. You can check it now. Thank you.

**Comment by swatchliu** [comment]
![image](https://user-images.githubusercontent.com/46444977/175206170-f43c8f1c-4ace-4a9d-9d68-65da9500ff00.png)

**Comment by galen-mcandrew** [comment]
## Datacap Request Trigger
#### Total DataCap requested 
> 5PiB
#### Expected weekly DataCap usage rate 
> 200TiB 
#### Client address
> f1dx7ljly4vmk5x2bn5ng4jpbqnuvozrz2phw42qy

**Comment by cryptowhizzard** [comment]
Hello @CoinPhD-official 

I was reviewing your application but it seems that non of the SP's you used for storing your data are open for retrieval.
One of the Rules for Fil+ / LDN is that the data needs to be retrievable.

Can you please contact your SP and have them make the stored data visible? Before we can continue this needs to be fixed.


<img width="578" alt="Schermafbeelding 2022-07-20 om 00 22 37" src="https://user-images.githubusercontent.com/36404435/179858638-32ed2c94-41cc-4ae3-9663-02424409959c.png">
<img width="540" alt="Schermafbeelding 2022-07-20 om 00 22 33" src="https://user-images.githubusercontent.com/36404435/179858657-69305e51-0531-4e57-b96c-8b53846232e8.png">

**Comment by CoinPhD-official** [comment]
@cryptowhizzard We communicated with SP. They've already made data open for retrieval. Please check it now.

**Comment by MRJAVAZHAO** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacea2qmxcgpujjh5q5eaxx2ru3gw4ouztxuv7ck3efqqybaxgc3whao 
#### Address 
> f1dx7ljly4vmk5x2bn5ng4jpbqnuvozrz2phw42qy
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f14gme3f52prtyzk6pblogrdd6b6ivp4swc6qmesi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacea2qmxcgpujjh5q5eaxx2ru3gw4ouztxuv7ck3efqqybaxgc3whao

**Comment by BlockMakeronline** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceasuwq3k7pytodxy7eyt5iii65gbpwf4kqzgybvk54mhge6trmpeo 
#### Address 
> f1dx7ljly4vmk5x2bn5ng4jpbqnuvozrz2phw42qy
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1o3twrcpwjtpcd4q36lpq4qmy2qfbgtyy5h6tsty
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceasuwq3k7pytodxy7eyt5iii65gbpwf4kqzgybvk54mhge6trmpeo

**Comment by BigD-Exchange** [comment]
@CoinPhD-official Hi! Great to see you have gotten approval for DataCap. Your project looks very interesting. If you are looking for storage providers to store these data, please visit #bigdata-exchange on Filecoin Slack or reply here.

**Comment by swatchliu** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceanhvqehk56ukvfiqtel66xrlwddxafycpde5a3orhhwqmcvdub6w 
#### Address 
> f1dx7ljly4vmk5x2bn5ng4jpbqnuvozrz2phw42qy
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1yh6q3nmsg7i2sys7f7dexcuajgoweudcqj2chfi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceanhvqehk56ukvfiqtel66xrlwddxafycpde5a3orhhwqmcvdub6w

**Comment by MetaWaveInfo** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebcasfplt3dzjawi2xyxytmzunj3imcyiwhohpycgyrfeslz5iho6 
#### Address 
> f1dx7ljly4vmk5x2bn5ng4jpbqnuvozrz2phw42qy
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1ktlkcxnmzxcdaoqfsunrg3vocfbmgv4n3mrn74a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebcasfplt3dzjawi2xyxytmzunj3imcyiwhohpycgyrfeslz5iho6

**Comment by UnionLabs2022** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecwlcv3k4x36rdqokoi4rqzhwgiobnpuu47gkpzvk32qwvyrzmvly 
#### Address 
> f1dx7ljly4vmk5x2bn5ng4jpbqnuvozrz2phw42qy
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f17xdri3wunqgld7dm23e4f3eqsntjakwc47xjo6i
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecwlcv3k4x36rdqokoi4rqzhwgiobnpuu47gkpzvk32qwvyrzmvly

**Comment by swatchliu** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacea2rfcxdofxj343nuitqry6gtizueo3vddgvzkeqtux5nbulmibgo 
#### Address 
> f1dx7ljly4vmk5x2bn5ng4jpbqnuvozrz2phw42qy
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1yh6q3nmsg7i2sys7f7dexcuajgoweudcqj2chfi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacea2rfcxdofxj343nuitqry6gtizueo3vddgvzkeqtux5nbulmibgo

**Comment by MRJAVAZHAO** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecctcaac6dhiaazar4eex3dgvslv2ivinpucewxguix6tk26lf5dw 
#### Address 
> f1dx7ljly4vmk5x2bn5ng4jpbqnuvozrz2phw42qy
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f14gme3f52prtyzk6pblogrdd6b6ivp4swc6qmesi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecctcaac6dhiaazar4eex3dgvslv2ivinpucewxguix6tk26lf5dw

**Comment by MetaWaveInfo** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebp64iy4iwnzvuh4emhsadze5sozzfouphyjxz3ymzv3htjqpqs3c 
#### Address 
> f1dx7ljly4vmk5x2bn5ng4jpbqnuvozrz2phw42qy
#### Datacap Allocated
> 1.56PiB
#### Signer Address
> f1ktlkcxnmzxcdaoqfsunrg3vocfbmgv4n3mrn74a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebp64iy4iwnzvuh4emhsadze5sozzfouphyjxz3ymzv3htjqpqs3c

**Comment by 1475Notary** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaq65wz7fleauzuoetxcc3logppvvtslvyfbzuskclvzilzxlb3ga 
#### Address 
> f1dx7ljly4vmk5x2bn5ng4jpbqnuvozrz2phw42qy
#### Datacap Allocated
> 1.56PiB
#### Signer Address
> f1ofq4mngy7ggcp755pfquq2gphjjnlydolf6awtq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaq65wz7fleauzuoetxcc3logppvvtslvyfbzuskclvzilzxlb3ga

**Comment by filplus-checker** [comment]
## DataCap and CID Checker Report[^1]
 - Organization: `CoinPhD`
 - Client: `f1dx7ljly4vmk5x2bn5ng4jpbqnuvozrz2phw42qy`
### Storage Provider Distribution
The below table shows the distribution of storage providers that have stored data for this client.

If this is the first time a provider takes verified deal, it will be marked as `new`.

For most of the datacap application, below restrictions should apply.
 - Storage provider should not exceed 25% of total datacap.
 - Storage provider should not be storing duplicate data for more than 20%.
 - Storage provider should have published its public IP address.
 - All storage providers should be located in different regions.

⚠️ 20.08% of total deal sealed by [f01914977](https://filfox.info/en/address/f01914977) are duplicate data.

⚠️ 59.66% of total deal sealed by [f01896469](https://filfox.info/en/address/f01896469) are duplicate data.

⚠️ 25.99% of total deal sealed by [f01895913](https://filfox.info/en/address/f01895913) are duplicate data.

⚠️ 70.88% of total deal sealed by [f01924416](https://filfox.info/en/address/f01924416) are duplicate data.

⚠️ 71.92% of total deal sealed by [f01924350](https://filfox.info/en/address/f01924350) are duplicate data.

⚠️ 70.52% of total deal sealed by [f01924325](https://filfox.info/en/address/f01924325) are duplicate data.

⚠️ 46.31% of total deal sealed by [f01889046](https://filfox.info/en/address/f01889046) are duplicate data.

⚠️ 35.43% of total deal sealed by [f01895778](https://filfox.info/en/address/f01895778) are duplicate data.

⚠️ 32.16% of total deal sealed by [f01895891](https://filfox.info/en/address/f01895891) are duplicate data.

⚠️ 45.53% of total deal sealed by [f01917236](https://filfox.info/en/address/f01917236) are duplicate data.

⚠️ 76.27% of total deal sealed by [f01879880](https://filfox.info/en/address/f01879880) are duplicate data.

⚠️ 67.82% of total deal sealed by [f01880896](https://filfox.info/en/address/f01880896) are duplicate data.

⚠️ 65.99% of total deal sealed by [f01880894](https://filfox.info/en/address/f01880894) are duplicate data.

⚠️ 61.72% of total deal sealed by [f01880897](https://filfox.info/en/address/f01880897) are duplicate data.

⚠️ 40.64% of total deal sealed by [f01895928](https://filfox.info/en/address/f01895928) are duplicate data.

⚠️ 85.94% of total deal sealed by [f01895783](https://filfox.info/en/address/f01895783) are duplicate data.

| Provider                                              |                 Location | Total Deals Sealed | Percentage | Unique Data | Duplicate Deals |
| :---------------------------------------------------- | -----------------------: | -----------------: | ---------: | ----------: | --------------: |
| [f01914977](https://filfox.info/en/address/f01914977) |    Ashburn, Virginia, US |         311.50 TiB |     16.41% |  248.94 TiB |          20.08% |
| [f01896469](https://filfox.info/en/address/f01896469) | Singapore, Singapore, SG |         186.91 TiB |      9.85% |   75.41 TiB |          59.66% |
| [f01895913](https://filfox.info/en/address/f01895913) | Singapore, Singapore, SG |         177.97 TiB |      9.38% |  131.72 TiB |          25.99% |
| [f01924416](https://filfox.info/en/address/f01924416) | Singapore, Singapore, SG |         135.00 TiB |      7.11% |   39.31 TiB |          70.88% |
| [f01924350](https://filfox.info/en/address/f01924350) | Singapore, Singapore, SG |         135.00 TiB |      7.11% |   37.91 TiB |          71.92% |
| [f01924325](https://filfox.info/en/address/f01924325) | Singapore, Singapore, SG |         134.09 TiB |      7.06% |   39.53 TiB |          70.52% |
| [f01889046](https://filfox.info/en/address/f01889046) |    Ashburn, Virginia, US |         133.75 TiB |      7.05% |   71.81 TiB |          46.31% |
| [f01895778](https://filfox.info/en/address/f01895778) | Singapore, Singapore, SG |         133.00 TiB |      7.01% |   85.88 TiB |          35.43% |
| [f01895891](https://filfox.info/en/address/f01895891) | Singapore, Singapore, SG |         132.94 TiB |      7.00% |   90.19 TiB |          32.16% |
| [f01917236](https://filfox.info/en/address/f01917236) |         Seoul, Seoul, KR |         132.34 TiB |      6.97% |   72.09 TiB |          45.53% |
| [f01895990](https://filfox.info/en/address/f01895990) | Singapore, Singapore, SG |         111.00 TiB |      5.85% |  111.00 TiB |           0.00% |
| [f01896513](https://filfox.info/en/address/f01896513) | Singapore, Singapore, SG |          45.00 TiB |      2.37% |   45.00 TiB |           0.00% |
| [f01879880](https://filfox.info/en/address/f01879880) | Singapore, Singapore, SG |          27.00 TiB |      1.42% |    6.41 TiB |          76.27% |
| [f01880896](https://filfox.info/en/address/f01880896) | Singapore, Singapore, SG |          27.00 TiB |      1.42% |    8.69 TiB |          67.82% |
| [f01880894](https://filfox.info/en/address/f01880894) | Singapore, Singapore, SG |          26.00 TiB |      1.37% |    8.84 TiB |          65.99% |
| [f01880897](https://filfox.info/en/address/f01880897) | Singapore, Singapore, SG |          20.00 TiB |      1.05% |    7.66 TiB |          61.72% |
| [f01895928](https://filfox.info/en/address/f01895928) | Singapore, Singapore, SG |          19.53 TiB |      1.03% |   11.59 TiB |          40.64% |
| [f01895783](https://filfox.info/en/address/f01895783) |     Boardman, Oregon, US |          10.00 TiB |      0.53% |    1.41 TiB |          85.94% |

![Provider Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/364/1671096193125.png)
### Deal Data Replication
The below table shows how each many unique data are replicated across storage providers.
- No more than 25% of unique data are stored with less than 4 providers.

⚠️ 100.00% of deals are for data replicated across less than 4 storage providers.

| Unique Data Size | Total Deals Made | Number of Providers | Deal Percentage |
| ---------------: | ---------------: | ------------------: | --------------: |
|       714.69 TiB |         1.08 PiB |                   1 |          58.06% |
|       132.16 TiB |       499.75 TiB |                   2 |          26.33% |
|        38.13 TiB |       296.31 TiB |                   3 |          15.61% |

![Replication Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/364/1671096193707.png)
### Deal Data Shared with other Clients
The below table shows how many unique data are shared with other clients.
Usually different applications owns different data and should not resolve to the same CID.

⚠️ CID sharing has been observed.

| Other Client                                                                                                          | Application                                                                                                              | Total Deals Affected | Unique CIDs |        Verifier |
| :-------------------------------------------------------------------------------------------------------------------- | :----------------------------------------------------------------------------------------------------------------------- | -------------------: | ----------: | --------------: |
| [f1u522dt3zabkgbxxzecl77wgv473yvpecxh6t6zq](https://filfox.info/en/address/f1u522dt3zabkgbxxzecl77wgv473yvpecxh6t6zq) | [Huifan livestream](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/407)                         |           724.94 TiB |       6,164 | LDN v3 multisig |
| [f1muygjb5zowppbhr7wnmdreqdoiyyanfm7fe54dy](https://filfox.info/en/address/f1muygjb5zowppbhr7wnmdreqdoiyyanfm7fe54dy) | [MappingFunk Protocol ](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/374)                     |           337.47 TiB |       3,601 | LDN v3 multisig |
| [f1ki4cjk27ypzjsuzkvvqzs6xobaweuoxfdcnpqhy](https://filfox.info/en/address/f1ki4cjk27ypzjsuzkvvqzs6xobaweuoxfdcnpqhy) | [TimeQuant](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/385)                                 |           335.00 TiB |       4,586 | LDN v3 multisig |
| [f1zb6pgkktdbyy7zxfob6gripqxuc25ukf35cc7fq](https://filfox.info/en/address/f1zb6pgkktdbyy7zxfob6gripqxuc25ukf35cc7fq) | `Maxpic PhotoGraphic Studio`                                                                                             |           331.16 TiB |       3,768 | LDN v3 multisig |
| [f1tivtdkq34mnfzso63wrr2xh6r2zo7aebao4jfla](https://filfox.info/en/address/f1tivtdkq34mnfzso63wrr2xh6r2zo7aebao4jfla) | `China travel service(HongKong) limited`                                                                                 |           300.59 TiB |       2,727 | LDN v3 multisig |
| [f1quofpadzcqlonmz7v3mv7dfqvm5hdztucdsjqsy](https://filfox.info/en/address/f1quofpadzcqlonmz7v3mv7dfqvm5hdztucdsjqsy) | [HENAN 863 SOFTWARE CO\., LTD](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/468)              |           280.78 TiB |       3,049 | LDN v3 multisig |
| [f1727w2vwjctfo7hflr5trgqkl3c7texh7pl4grzq](https://filfox.info/en/address/f1727w2vwjctfo7hflr5trgqkl3c7texh7pl4grzq) | [GMverse](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/365)                                   |           261.50 TiB |       3,393 | LDN v3 multisig |
| [f1qjrlejxv5a73kxurwtxyrni6ji7orm74zeeetiy](https://filfox.info/en/address/f1qjrlejxv5a73kxurwtxyrni6ji7orm74zeeetiy) | [Mooc](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/223)                                      |           154.72 TiB |       1,411 | LDN v3 multisig |
| [f14abwn2goturifmt27s2bssoe3fup2b3npkgfzui](https://filfox.info/en/address/f14abwn2goturifmt27s2bssoe3fup2b3npkgfzui) | [KONGFU VR](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/372)                                 |           144.56 TiB |       1,920 | LDN v3 multisig |
| [f1f5edx6ofn3lf6rk3yfpldbi2pzgq2egoyu6ubpi](https://filfox.info/en/address/f1f5edx6ofn3lf6rk3yfpldbi2pzgq2egoyu6ubpi) | [Samdata Trade](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/382)                             |           120.19 TiB |       1,496 | LDN v3 multisig |
| [f1bb2z36lpq3pnwiiowiraagpzqnpow4bonjacx7a](https://filfox.info/en/address/f1bb2z36lpq3pnwiiowiraagpzqnpow4bonjacx7a) | [Hola Space](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/362)                                |            95.50 TiB |       1,682 | LDN v3 multisig |
| [f1vtcetpapwwyka6txwqjwymsa67npdfilbkwh64a](https://filfox.info/en/address/f1vtcetpapwwyka6txwqjwymsa67npdfilbkwh64a) | [Chimay](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/397)                                    |            93.59 TiB |       1,700 | LDN v3 multisig |
| [f17qd6x3leh5pa7vh6ewdaed7qhbn2mgofrokuayy](https://filfox.info/en/address/f17qd6x3leh5pa7vh6ewdaed7qhbn2mgofrokuayy) | [Drust](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/427)                                     |            87.69 TiB |       1,484 | LDN v3 multisig |
| [f1ac3mjrhahxbyvxsasp4e7kwa6vyds3ahm27us6a](https://filfox.info/en/address/f1ac3mjrhahxbyvxsasp4e7kwa6vyds3ahm27us6a) | `Create coach`                                                                                                           |            79.00 TiB |       1,021 | LDN v3 multisig |
| [f1dwhevm3p2slu6itmkssznscmpkpltdiztprnpya](https://filfox.info/en/address/f1dwhevm3p2slu6itmkssznscmpkpltdiztprnpya) | [Hiscene](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/548)                                   |            75.94 TiB |       1,317 | LDN v3 multisig |
| [f1clwd2dooy2cflfilhzeq2ycl544b3heqsiwhjrq](https://filfox.info/en/address/f1clwd2dooy2cflfilhzeq2ycl544b3heqsiwhjrq) | [FiboAI](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/349)                                    |            40.69 TiB |         601 | LDN v3 multisig |
| [f1ojo3wo24zkeovndlxfpqmlgzlbysg5fiukmup4a](https://filfox.info/en/address/f1ojo3wo24zkeovndlxfpqmlgzlbysg5fiukmup4a) | `Titansoft`                                                                                                              |            37.22 TiB |         504 | LDN v3 multisig |
| [f1ffbtksiso5za73pypuxbxznng6rdv64nbihdtba](https://filfox.info/en/address/f1ffbtksiso5za73pypuxbxznng6rdv64nbihdtba) | [EpikProtocol](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/281)                              |            24.81 TiB |         324 |       LDN # 281 |
| [f1hik4fc3wvck2jchtufrnfnzmmskw2nyezlbsr3q](https://filfox.info/en/address/f1hik4fc3wvck2jchtufrnfnzmmskw2nyezlbsr3q) | [NFTSCAN](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/350)                                   |            16.41 TiB |         288 | LDN v3 multisig |
| [f1tgii4xgcp6um4n2w7eqaw6bwvnvyii2u7cjgzka](https://filfox.info/en/address/f1tgii4xgcp6um4n2w7eqaw6bwvnvyii2u7cjgzka) | [Meson\.Network ](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/187)                           |             5.66 TiB |          57 | LDN v3 multisig |
| [f1qdycz5jgdcg4lerfpkujikkwcj7wq7yiqnmubni](https://filfox.info/en/address/f1qdycz5jgdcg4lerfpkujikkwcj7wq7yiqnmubni) | [National library](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/70)                           |             5.03 TiB |          86 |        LDN # 70 |
| [f1einobkrjcjk6gfc5ov6663vrri75hwdsjfs6pmq](https://filfox.info/en/address/f1einobkrjcjk6gfc5ov6663vrri75hwdsjfs6pmq) | [Cansoti](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/640)                                   |           640.00 GiB |           2 | LDN v3 multisig |
| [f1ivsvpljx4ovp2tth73pllkxmumrudemks623iia](https://filfox.info/en/address/f1ivsvpljx4ovp2tth73pllkxmumrudemks623iia) | `TIS Inc. group`                                                                                                         |           224.00 GiB |           4 | LDN v3 multisig |
| [f1ffr7uhq7mszotfdybexcnl4i7xw5tqyp5fhqy3y](https://filfox.info/en/address/f1ffr7uhq7mszotfdybexcnl4i7xw5tqyp5fhqy3y) | [MyTrade Technology Limited](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/386)                |           192.00 GiB |           4 | LDN v3 multisig |
| [f1ajdk7e6ex7fvtjtydzgys47bcg7jub2baucun7y](https://filfox.info/en/address/f1ajdk7e6ex7fvtjtydzgys47bcg7jub2baucun7y) | [Ruikuyun Information Technology Co\., Ltd](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/529) |           160.00 GiB |           3 | LDN v3 multisig |
| [f1fi7vzu266bh7yxsygw6scl2hjltdkhfb6nyzn3a](https://filfox.info/en/address/f1fi7vzu266bh7yxsygw6scl2hjltdkhfb6nyzn3a) | [Jiliantech](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/190)                                |            32.00 GiB |           1 |       LDN # 190 |

[^1]: To manually trigger this report, add a comment with text `checker:manualTrigger`
