### ISSUE TITLE
[DataCap Application]GMverse

### ISSUE THREAD

**Issue by GMverse** [filecoin-project/filecoin-plus-large-datasets#365]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name:GMverse
- Website / Social Media:https://gmverse.io/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 200TiB
- On-chain address for first allocation: f1727w2vwjctfo7hflr5trgqkl3c7texh7pl4grzq

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
GM VERSE has vibrant communities with high retention,high engagement, real activities, reward participation in Metaverse building. We aim to build GM Space and GM City which has easy access, powerful space builder, smooth communications, and multi-purpose space design.
```

What is the primary source of funding for this project?
```
It is from company's income.
```

What other projects/ecosystem stakeholders is this project associated with?
```
No.
```

## Use-case details

Describe the data being stored onto Filecoin
```
3D model of GMverse (unity engine, material, texture etc.)
So far we have more than 600 TiB data. plan to have full 8 copies.
```

Where was the data in this dataset sourced from?
```
Our project GMverse.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
[GMverse dataset.zip](https://github.com/filecoin-project/filecoin-plus-large-datasets/files/8694640/GMverse.dataset.zip)

```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes. 
```

What is the expected retrieval frequency for this data?
```
1-2 times per year, it's our back up data.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
Permanent.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
China + Aisa.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Online and Offline.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We want to contact storage providers via slack and telegram.
```

How will you be distributing deals across storage providers?
```
As even as possible every SPs will seal my deal.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, we have enough funding. Ready for continuing making deals.
```

**Comment by GMverse** [comment]
What can I do next after the issue? @galen-mcandrew

**Comment by GMverse** [comment]
@galen-mcandrew @dkkapur

**Comment by GMverse** [comment]
I'm not sure that if my application will be noticed.

**Comment by dkkapur** [comment]
@GMverse Can you email [filplus@fil.org](mailto:filplus@fil.org) with your official work email so we can share this with notaries as a form of proof that you represent this organization?

**Comment by GMverse** [comment]
> @GMverse Can you email [filplus@fil.org](mailto:filplus@fil.org) with your official work email so we can share this with notaries as a form of proof that you represent this organization?

@dkkapur My email was just sent to you. Hope for your response!

**Comment by GMverse** [comment]
@dkkapur @galen-mcandrew Hello, is there anything I should provide to you?

**Comment by galen-mcandrew** [comment]
## Datacap Request Trigger
#### Total DataCap requested 
> 5PiB
#### Expected weekly DataCap usage rate 
> 200TiB 
#### Client address
> f1727w2vwjctfo7hflr5trgqkl3c7texh7pl4grzq

**Comment by 1475Notary** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedxenlj5o5h3u6rcap2t3cl65rlxx6euk64vuggjnevcrhpgqqd5u 
#### Address 
> f1727w2vwjctfo7hflr5trgqkl3c7texh7pl4grzq
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1ofq4mngy7ggcp755pfquq2gphjjnlydolf6awtq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedxenlj5o5h3u6rcap2t3cl65rlxx6euk64vuggjnevcrhpgqqd5u

**Comment by MegTei** [comment]
HI @GMverse this looks like a very new site/ business, is there a reason you are requesting so much storage space at such an early stage?

**Comment by MRJAVAZHAO** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacea3qijfpe7qucj23z3667otennlmjcroyxan3zpettwyp57paf5dq 
#### Address 
> f1727w2vwjctfo7hflr5trgqkl3c7texh7pl4grzq
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f14gme3f52prtyzk6pblogrdd6b6ivp4swc6qmesi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacea3qijfpe7qucj23z3667otennlmjcroyxan3zpettwyp57paf5dq

**Comment by MatrixStorage** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebla4baaw7jh72j22uqvoqfv5pcvvr4svxa56d2yl4uy34l75fzqm 
#### Address 
> f1727w2vwjctfo7hflr5trgqkl3c7texh7pl4grzq
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1tbxqwjxfyv7swsdin4einirlsfquv3vnmlapley
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebla4baaw7jh72j22uqvoqfv5pcvvr4svxa56d2yl4uy34l75fzqm

**Comment by BigD-Exchange** [comment]
@GMverse Hi! Great to see you have gotten approval for DataCap. If you are looking for reputable storage providers to store these data, please visit #bigdata-exchange on Filecoin Slack or reply here.

**Comment by MRJAVAZHAO** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecfznicpogaiimsbzt5wxxph2cm3rzq6gwxdmppqp7vuks3fzrl6g 
#### Address 
> f1727w2vwjctfo7hflr5trgqkl3c7texh7pl4grzq
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f14gme3f52prtyzk6pblogrdd6b6ivp4swc6qmesi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecfznicpogaiimsbzt5wxxph2cm3rzq6gwxdmppqp7vuks3fzrl6g

**Comment by PluskitOfficial** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedcsknajldbqogtizlbqgmjvxsmahhst7oqunmljk2zfn2pjep3iq 
#### Address 
> f1727w2vwjctfo7hflr5trgqkl3c7texh7pl4grzq
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1tgnlhtcmhwipfm7thsftxhn5k52velyjlazpvka
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedcsknajldbqogtizlbqgmjvxsmahhst7oqunmljk2zfn2pjep3iq

**Comment by 1475Notary** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceasbrrwdczlo6as3hfabj34lsefyjn3r56wdhsabqdak5sc2hjqiu 
#### Address 
> f1727w2vwjctfo7hflr5trgqkl3c7texh7pl4grzq
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1ofq4mngy7ggcp755pfquq2gphjjnlydolf6awtq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceasbrrwdczlo6as3hfabj34lsefyjn3r56wdhsabqdak5sc2hjqiu

**Comment by UnionLabs2022** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceboa35c5k74szusbeawjozap7dfokbsqenfq4r4vhdak4ew5pshxe 
#### Address 
> f1727w2vwjctfo7hflr5trgqkl3c7texh7pl4grzq
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f17xdri3wunqgld7dm23e4f3eqsntjakwc47xjo6i
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceboa35c5k74szusbeawjozap7dfokbsqenfq4r4vhdak4ew5pshxe

**Comment by swatchliu** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb6vwfhc7pjnqugkv7plsuxn5gsoeuo5tyx5ugkjbnk5ryhd2r7ho 
#### Address 
> f1727w2vwjctfo7hflr5trgqkl3c7texh7pl4grzq
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1yh6q3nmsg7i2sys7f7dexcuajgoweudcqj2chfi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb6vwfhc7pjnqugkv7plsuxn5gsoeuo5tyx5ugkjbnk5ryhd2r7ho

**Comment by PluskitOfficial** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceall7ta2vawk42mrlj6iyrkymilm2qeznzskvnvurawduxgkpc4j6 
#### Address 
> f1727w2vwjctfo7hflr5trgqkl3c7texh7pl4grzq
#### Datacap Allocated
> 1.56PiB
#### Signer Address
> f1tgnlhtcmhwipfm7thsftxhn5k52velyjlazpvka
#### Id
> f82cdcb6-94c6-4b23-bbe3-73863b809b75
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceall7ta2vawk42mrlj6iyrkymilm2qeznzskvnvurawduxgkpc4j6

**Comment by MetaWaveInfo** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedxjwohgs5wfyjamn7if3o7s2owjvctmq4oqk7trazn472tazsceq 
#### Address 
> f1727w2vwjctfo7hflr5trgqkl3c7texh7pl4grzq
#### Datacap Allocated
> 1.56PiB
#### Signer Address
> f1ktlkcxnmzxcdaoqfsunrg3vocfbmgv4n3mrn74a
#### Id
> f82cdcb6-94c6-4b23-bbe3-73863b809b75
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedxjwohgs5wfyjamn7if3o7s2owjvctmq4oqk7trazn472tazsceq

**Comment by filplus-checker** [comment]
## DataCap and CID Checker Report[^1]
 - Organization: `GMverse`
 - Client: `f1727w2vwjctfo7hflr5trgqkl3c7texh7pl4grzq`
### Storage Provider Distribution
The below table shows the distribution of storage providers that have stored data for this client.

If this is the first time a provider takes verified deal, it will be marked as `new`.

For most of the datacap application, below restrictions should apply.
 - Storage provider should not exceed 25% of total datacap.
 - Storage provider should not be storing duplicate data for more than 20%.
 - Storage provider should have published its public IP address.
 - All storage providers should be located in different regions.

⚠️ 45.87% of total deal sealed by [f01917208](https://filfox.info/en/address/f01917208) are duplicate data.

⚠️ 26.42% of total deal sealed by [f01895913](https://filfox.info/en/address/f01895913) are duplicate data.

⚠️ 45.75% of total deal sealed by [f01917257](https://filfox.info/en/address/f01917257) are duplicate data.

⚠️ 27.09% of total deal sealed by [f01895891](https://filfox.info/en/address/f01895891) are duplicate data.

⚠️ 70.22% of total deal sealed by [f01924325](https://filfox.info/en/address/f01924325) are duplicate data.

⚠️ 74.01% of total deal sealed by [f01926585](https://filfox.info/en/address/f01926585) are duplicate data.

⚠️ 34.28% of total deal sealed by [f01893290](https://filfox.info/en/address/f01893290) are duplicate data.

⚠️ 71.35% of total deal sealed by [f01924416](https://filfox.info/en/address/f01924416) are duplicate data.

⚠️ 47.14% of total deal sealed by [f01844999](https://filfox.info/en/address/f01844999) are duplicate data.

⚠️ [f01844999](https://filfox.info/en/address/f01844999) has unknown IP location.

⚠️ 42.56% of total deal sealed by [f01917236](https://filfox.info/en/address/f01917236) are duplicate data.

⚠️ 71.17% of total deal sealed by [f01924350](https://filfox.info/en/address/f01924350) are duplicate data.

⚠️ 66.38% of total deal sealed by [f01880894](https://filfox.info/en/address/f01880894) are duplicate data.

⚠️ 53.13% of total deal sealed by [f01880898](https://filfox.info/en/address/f01880898) are duplicate data.

⚠️ 65.63% of total deal sealed by [f01880896](https://filfox.info/en/address/f01880896) are duplicate data.

⚠️ 37.59% of total deal sealed by [f01879880](https://filfox.info/en/address/f01879880) are duplicate data.

⚠️ 47.95% of total deal sealed by [f01900713](https://filfox.info/en/address/f01900713) are duplicate data.

⚠️ 88.39% of total deal sealed by [f01937964](https://filfox.info/en/address/f01937964) are duplicate data.

| Provider                                                    |                 Location | Total Deals Sealed | Percentage | Unique Data | Duplicate Deals |
| :---------------------------------------------------------- | -----------------------: | -----------------: | ---------: | ----------: | --------------: |
| [f01917208](https://filfox.info/en/address/f01917208)       |         Seoul, Seoul, KR |         313.00 TiB |     11.59% |  169.44 TiB |          45.87% |
| [f01895913](https://filfox.info/en/address/f01895913)       | Singapore, Singapore, SG |         303.72 TiB |     11.25% |  223.47 TiB |          26.42% |
| [f01917257](https://filfox.info/en/address/f01917257)       |         Seoul, Seoul, KR |         300.47 TiB |     11.13% |  163.00 TiB |          45.75% |
| [f01895891](https://filfox.info/en/address/f01895891)       | Singapore, Singapore, SG |         230.00 TiB |      8.52% |  167.69 TiB |          27.09% |
| [f01924325](https://filfox.info/en/address/f01924325)       | Singapore, Singapore, SG |         229.00 TiB |      8.48% |   68.19 TiB |          70.22% |
| [f01926585](https://filfox.info/en/address/f01926585)`new`  |    Ashburn, Virginia, US |         216.69 TiB |      8.03% |   56.31 TiB |          74.01% |
| [f01893290](https://filfox.info/en/address/f01893290)       | Singapore, Singapore, SG |         182.94 TiB |      6.78% |  120.22 TiB |          34.28% |
| [f01924416](https://filfox.info/en/address/f01924416)       | Singapore, Singapore, SG |         133.81 TiB |      4.96% |   38.34 TiB |          71.35% |
| [f01895783](https://filfox.info/en/address/f01895783)       |     Boardman, Oregon, US |         132.97 TiB |      4.92% |  132.97 TiB |           0.00% |
| [f01844999](https://filfox.info/en/address/f01844999)       |                  Unknown |         132.91 TiB |      4.92% |   70.25 TiB |          47.14% |
| [f01917236](https://filfox.info/en/address/f01917236)       |         Seoul, Seoul, KR |         123.28 TiB |      4.57% |   70.81 TiB |          42.56% |
| [f01924350](https://filfox.info/en/address/f01924350)       | Singapore, Singapore, SG |         115.00 TiB |      4.26% |   33.16 TiB |          71.17% |
| [f01895928](https://filfox.info/en/address/f01895928)       | Singapore, Singapore, SG |          99.97 TiB |      3.70% |   83.00 TiB |          16.97% |
| [f01896469](https://filfox.info/en/address/f01896469)       | Singapore, Singapore, SG |          50.00 TiB |      1.85% |   50.00 TiB |           0.00% |
| [f01880894](https://filfox.info/en/address/f01880894)       | Singapore, Singapore, SG |          25.00 TiB |      0.93% |    8.41 TiB |          66.38% |
| [f01880898](https://filfox.info/en/address/f01880898)       | Singapore, Singapore, SG |          25.00 TiB |      0.93% |   11.72 TiB |          53.13% |
| [f01880896](https://filfox.info/en/address/f01880896)       | Singapore, Singapore, SG |          25.00 TiB |      0.93% |    8.59 TiB |          65.63% |
| [f01879880](https://filfox.info/en/address/f01879880)       | Singapore, Singapore, SG |          24.94 TiB |      0.92% |   15.56 TiB |          37.59% |
| [f01900713](https://filfox.info/en/address/f01900713)       |         Seoul, Seoul, KR |          22.16 TiB |      0.82% |   11.53 TiB |          47.95% |
| [f01937964](https://filfox.info/en/address/f01937964)       |         Tokyo, Tokyo, JP |          14.00 TiB |      0.52% |    1.63 TiB |          88.39% |
| [f01895715](https://filfox.info/en/address/f01895715)       |         Seoul, Seoul, KR |         128.00 GiB |      0.00% |  128.00 GiB |           0.00% |

![Provider Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/365/1671096219805.png)
### Deal Data Replication
The below table shows how each many unique data are replicated across storage providers.
- No more than 25% of unique data are stored with less than 4 providers.

⚠️ 98.52% of deals are for data replicated across less than 4 storage providers.

| Unique Data Size | Total Deals Made | Number of Providers | Deal Percentage |
| ---------------: | ---------------: | ------------------: | --------------: |
|       842.19 TiB |         1.46 PiB |                   1 |          55.24% |
|       234.75 TiB |       905.59 TiB |                   2 |          33.54% |
|        55.28 TiB |       263.16 TiB |                   3 |           9.75% |
|         6.72 TiB |        39.84 TiB |                   4 |           1.48% |

![Replication Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/365/1671096220415.png)
### Deal Data Shared with other Clients
The below table shows how many unique data are shared with other clients.
Usually different applications owns different data and should not resolve to the same CID.

⚠️ CID sharing has been observed.

| Other Client                                                                                                          | Application                                                                                                                | Total Deals Affected | Unique CIDs |                                                                                 Verifier |
| :-------------------------------------------------------------------------------------------------------------------- | :------------------------------------------------------------------------------------------------------------------------- | -------------------: | ----------: | ---------------------------------------------------------------------------------------: |
| [f1ki4cjk27ypzjsuzkvvqzs6xobaweuoxfdcnpqhy](https://filfox.info/en/address/f1ki4cjk27ypzjsuzkvvqzs6xobaweuoxfdcnpqhy) | [TimeQuant](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/385)                                   |           531.38 TiB |       8,086 |                                                                          LDN v3 multisig |
| [f1smfrznoqsp7eptqnselnosng7vxuo3ptnoqv2oa](https://filfox.info/en/address/f1smfrznoqsp7eptqnselnosng7vxuo3ptnoqv2oa) | [CTG Business Service](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/306)                        |           454.38 TiB |       3,705 |                                                                          LDN v3 multisig |
| [f1tivtdkq34mnfzso63wrr2xh6r2zo7aebao4jfla](https://filfox.info/en/address/f1tivtdkq34mnfzso63wrr2xh6r2zo7aebao4jfla) | `China travel service(HongKong) limited`                                                                                   |           401.38 TiB |       4,356 |                                                                          LDN v3 multisig |
| [f1zb6pgkktdbyy7zxfob6gripqxuc25ukf35cc7fq](https://filfox.info/en/address/f1zb6pgkktdbyy7zxfob6gripqxuc25ukf35cc7fq) | `Maxpic PhotoGraphic Studio`                                                                                               |           397.88 TiB |       3,734 |                                                                          LDN v3 multisig |
| [f1bb2z36lpq3pnwiiowiraagpzqnpow4bonjacx7a](https://filfox.info/en/address/f1bb2z36lpq3pnwiiowiraagpzqnpow4bonjacx7a) | [Hola Space](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/362)                                  |           385.38 TiB |       4,403 |                                                                          LDN v3 multisig |
| [f1qjrlejxv5a73kxurwtxyrni6ji7orm74zeeetiy](https://filfox.info/en/address/f1qjrlejxv5a73kxurwtxyrni6ji7orm74zeeetiy) | [Mooc](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/223)                                        |           357.69 TiB |       4,877 |                                                                          LDN v3 multisig |
| [f17qd6x3leh5pa7vh6ewdaed7qhbn2mgofrokuayy](https://filfox.info/en/address/f17qd6x3leh5pa7vh6ewdaed7qhbn2mgofrokuayy) | [Drust](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/427)                                       |           311.03 TiB |       4,598 |                                                                          LDN v3 multisig |
| [f1f5edx6ofn3lf6rk3yfpldbi2pzgq2egoyu6ubpi](https://filfox.info/en/address/f1f5edx6ofn3lf6rk3yfpldbi2pzgq2egoyu6ubpi) | [Samdata Trade](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/382)                               |           307.41 TiB |       3,671 |                                                                          LDN v3 multisig |
| [f14abwn2goturifmt27s2bssoe3fup2b3npkgfzui](https://filfox.info/en/address/f14abwn2goturifmt27s2bssoe3fup2b3npkgfzui) | [KONGFU VR](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/372)                                   |           285.97 TiB |       3,815 |                                                                          LDN v3 multisig |
| [f1dx7ljly4vmk5x2bn5ng4jpbqnuvozrz2phw42qy](https://filfox.info/en/address/f1dx7ljly4vmk5x2bn5ng4jpbqnuvozrz2phw42qy) | [CoinPhD](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/364)                                     |           250.91 TiB |       3,393 |                                                                          LDN v3 multisig |
| [f1ffr7uhq7mszotfdybexcnl4i7xw5tqyp5fhqy3y](https://filfox.info/en/address/f1ffr7uhq7mszotfdybexcnl4i7xw5tqyp5fhqy3y) | [MyTrade Technology Limited](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/386)                  |           214.69 TiB |       1,486 |                                                                          LDN v3 multisig |
| [f1jdmx2cuswzjlt4pnsv3t7ipmesywzxsg6q56a2a](https://filfox.info/en/address/f1jdmx2cuswzjlt4pnsv3t7ipmesywzxsg6q56a2a) | [Raysun Radar Electronic Technology Co\.,Ltd](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/884) |           163.19 TiB |       1,530 |                                                                          LDN v3 multisig |
| [f1ivsvpljx4ovp2tth73pllkxmumrudemks623iia](https://filfox.info/en/address/f1ivsvpljx4ovp2tth73pllkxmumrudemks623iia) | `TIS Inc. group`                                                                                                           |           143.50 TiB |       1,450 |                                                                          LDN v3 multisig |
| [f1rnwp6p5kx7pcwexpucoav6mmwz3rkxw5blrboyy](https://filfox.info/en/address/f1rnwp6p5kx7pcwexpucoav6mmwz3rkxw5blrboyy) | [MigoVideo](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/517)                                   |           131.94 TiB |       1,480 |                                                                          LDN v3 multisig |
| [f1vtcetpapwwyka6txwqjwymsa67npdfilbkwh64a](https://filfox.info/en/address/f1vtcetpapwwyka6txwqjwymsa67npdfilbkwh64a) | [Chimay](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/397)                                      |           115.06 TiB |       2,074 |                                                                          LDN v3 multisig |
| [f1ffbtksiso5za73pypuxbxznng6rdv64nbihdtba](https://filfox.info/en/address/f1ffbtksiso5za73pypuxbxznng6rdv64nbihdtba) | [EpikProtocol](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/281)                                |           109.78 TiB |       1,557 |                                                                                LDN # 281 |
| [f1quofpadzcqlonmz7v3mv7dfqvm5hdztucdsjqsy](https://filfox.info/en/address/f1quofpadzcqlonmz7v3mv7dfqvm5hdztucdsjqsy) | [HENAN 863 SOFTWARE CO\., LTD](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/468)                |           108.97 TiB |       1,459 |                                                                          LDN v3 multisig |
| [f1clwd2dooy2cflfilhzeq2ycl544b3heqsiwhjrq](https://filfox.info/en/address/f1clwd2dooy2cflfilhzeq2ycl544b3heqsiwhjrq) | [FiboAI](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/349)                                      |           106.03 TiB |       1,858 |                                                                          LDN v3 multisig |
| [f1ojo3wo24zkeovndlxfpqmlgzlbysg5fiukmup4a](https://filfox.info/en/address/f1ojo3wo24zkeovndlxfpqmlgzlbysg5fiukmup4a) | `Titansoft`                                                                                                                |            43.28 TiB |         353 |                                                                          LDN v3 multisig |
| [f1nmhjvibl7acp45lpxmo5kduz42evjazsyi4mzza](https://filfox.info/en/address/f1nmhjvibl7acp45lpxmo5kduz42evjazsyi4mzza) | `ubuckvnockai`                                                                                                             |            42.31 TiB |         593 |                                                                          LDN v3 multisig |
| [f1u522dt3zabkgbxxzecl77wgv473yvpecxh6t6zq](https://filfox.info/en/address/f1u522dt3zabkgbxxzecl77wgv473yvpecxh6t6zq) | [Huifan livestream](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/407)                           |            37.91 TiB |         553 |                                                                          LDN v3 multisig |
| [f1dwhevm3p2slu6itmkssznscmpkpltdiztprnpya](https://filfox.info/en/address/f1dwhevm3p2slu6itmkssznscmpkpltdiztprnpya) | [Hiscene](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/548)                                     |            37.59 TiB |         664 |                                                                          LDN v3 multisig |
| [f1avhqgmeazxzvylz34l26o3nlj2ywnzaviwns3dq](https://filfox.info/en/address/f1avhqgmeazxzvylz34l26o3nlj2ywnzaviwns3dq) | [87v5\-CarsonVideo](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/392)                           |            33.19 TiB |         320 |                                                                          LDN v3 multisig |
| [f1hik4fc3wvck2jchtufrnfnzmmskw2nyezlbsr3q](https://filfox.info/en/address/f1hik4fc3wvck2jchtufrnfnzmmskw2nyezlbsr3q) | [NFTSCAN](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/350)                                     |            33.13 TiB |         589 |                                                                          LDN v3 multisig |
| [f1muygjb5zowppbhr7wnmdreqdoiyyanfm7fe54dy](https://filfox.info/en/address/f1muygjb5zowppbhr7wnmdreqdoiyyanfm7fe54dy) | [MappingFunk Protocol ](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/374)                       |            28.09 TiB |         308 |                                                                          LDN v3 multisig |
| [f1mn5mw2dpqz6p3s7vxrlkhkh3okdtc6t7wqro4xa](https://filfox.info/en/address/f1mn5mw2dpqz6p3s7vxrlkhkh3okdtc6t7wqro4xa) | [Unisound](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/577)                                    |            10.78 TiB |         101 |                                                                          LDN v3 multisig |
| [f1einobkrjcjk6gfc5ov6663vrri75hwdsjfs6pmq](https://filfox.info/en/address/f1einobkrjcjk6gfc5ov6663vrri75hwdsjfs6pmq) | [Cansoti](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/640)                                     |             2.75 TiB |          32 |                                                                          LDN v3 multisig |
| [f1xtnkj5ti77f5gbzhclnpj3xt6e5dwhfzive2yca](https://filfox.info/en/address/f1xtnkj5ti77f5gbzhclnpj3xt6e5dwhfzive2yca) | [Beacon Project](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/482)                              |             1.81 TiB |          11 | Project Beacon, 12 LDNs LDN # 444, 446, 447, 448, 474, 475, 476, 477, 479, 480, 481, 482 |
| [f1tgii4xgcp6um4n2w7eqaw6bwvnvyii2u7cjgzka](https://filfox.info/en/address/f1tgii4xgcp6um4n2w7eqaw6bwvnvyii2u7cjgzka) | [Meson\.Network ](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/187)                             |             1.38 TiB |          27 |                                                                          LDN v3 multisig |
| [f1zav4f4rak2yvbrq357z3whj224wn4dipl7eiesy](https://filfox.info/en/address/f1zav4f4rak2yvbrq357z3whj224wn4dipl7eiesy) | [Shanghai Zhixun](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/628)                             |           384.00 GiB |           2 |                                                                          LDN v3 multisig |
| [f1ac3mjrhahxbyvxsasp4e7kwa6vyds3ahm27us6a](https://filfox.info/en/address/f1ac3mjrhahxbyvxsasp4e7kwa6vyds3ahm27us6a) | `Create coach`                                                                                                             |            96.00 GiB |           1 |                                                                          LDN v3 multisig |

[^1]: To manually trigger this report, add a comment with text `checker:manualTrigger`

**Comment by Filplus-govteam** [comment]
Hello @GMverse  per the https://github.com/filecoin-project/notary-governance/issues/922 for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

This information will be reviewed by Fil+ Governance team to confirm validity and then the application will be triggered for notary review. Let us know if you have any questions.
