### ISSUE TITLE
[DataCap Application] FilSwan Slingshot Restore Program 2- Fly Brain Anatomy

### ISSUE THREAD

**Issue by flyworker** [filecoin-project/filecoin-plus-large-datasets#366]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name:  FilSwan - Slingshot Restore
- Website / Social Media: https://www.filswan.com
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5 PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 200TiB
- On-chain address for first allocation: f1qugwxtg7w4jrzhkemzcu7fcdevkaf6kw4ro3poi 

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
This is a project for the Slingshot Restore Program, the program is for fix 10PB storage within 100 days. We are out of datacap in the [previous allocation](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/157) so we reopen a new one.


FilSwan is a leading web3 and computing provider in the filecoin ecosystem player. We would like to working as a client for this project.

```

What is the primary source of funding for this project?
```
Self funded by each node
```

What other projects/ecosystem stakeholders is this project associated with?
```
No
```

## Use-case details

Describe the data being stored onto Filecoin
```
Previous work of dataset can be found here: https://console.filswan.com/#/dataset

```

Where was the data in this dataset sourced from?
```
This dataset, made available by Janelia's FlyLight project, consists of fluorescence images of Drosophila melanogaster driver lines, aligned to standard templates, and stored in formats suitable for rapid searching in the cloud. https://registry.opendata.aws/janelia-flylight/
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
Please answer here.
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
https://open.quiltdata.com/b/janelia-flylight-imagery/tree/Annotator%20Gen1%20MCFO/R10A09/R10A09-20170217_21_E4-f-20x-brain-GAL4-JRC2018_Unisex_20x_HR-CDM_2.png
```

What is the expected retrieval frequency for this data?
```
Monthly
```

For how long do you plan to keep this dataset stored on Filecoin?
```
540 days
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
3 countries with 5 nodes
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
though Filswan IPFS gateway
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
Please answer here.
```

How will you be distributing deals across storage providers?
```
Please answer here.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, we have the fund, and community has the collateral.
```

**Comment by dkkapur** [comment]
Closing this out to get the other one moving first. Can re-open this if that gets blocked again.
