### ISSUE TITLE
Twinquasar /  Folding at home Covid 19

### ISSUE THREAD

**Issue by s0nik42** [filecoin-project/filecoin-plus-large-datasets#368]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Twin Quasar
- Website / Social Media: twinquasar.io
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 500TiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 290TiB
- On-chain address for first allocation: f1x2wjpopqkrg6qtrhm2ieifcqwc5er7dy3usqkgi

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
At twinquasar we are onboarding data to Slingshot since Slingshot 2.2 . Our goal is to onboard useful data to the network in a reusable way.  ```

What is the primary source of funding for this project?
```
Our own funds```

What other projects/ecosystem stakeholders is this project associated with?
```
PL via the Slinshot challenge
```

## Use-case details

Describe the data being stored onto Filecoin
```
Folding at home  dataset
```

Where was the data in this dataset sourced from?
```
Folding@home is a massively distributed computing project that uses biomolecular simulations to investigate the molecular origins of disease and accelerate the discovery of new therapies.

The dataset is coming from AWS public S3 repo  : https://registry.opendata.aws/foldingathome-covid19/

```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
A link to 

https://molssi-bioexcel-covid-19-structure-therapeutics-hub.s3.amazonaws.com/GumbartGroup/RBD-ACE2.tgz

```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes
```

What is the expected retrieval frequency for this data?
```
Not much
```

For how long do you plan to keep this dataset stored on Filecoin?
```
18 months
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
US
APAC
EUROPE

```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Data will transfered offline
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We're selecting the SPs with high reputation on slack  and who already participate to Slingshot. They have the ability to store deals at a very fast pace and a high success rate.  

```

How will you be distributing deals across storage providers?
```
1 to 2 copies per companies
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes
```

**Comment by galen-mcandrew** [comment]
## Multisig Notary requested
#### Total DataCap requested 
> 500TiB
#### Expected weekly DataCap usage rate 
> 290TiB

**Comment by cryptowhizzard** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedqi45ugbqdjmlri5ygn4tyr5ybi5jstwfnm6r5g7b4tu3squ744k 
#### Address 
> f1x2wjpopqkrg6qtrhm2ieifcqwc5er7dy3usqkgi
#### Datacap Allocated
> 25.00TiB
#### Signer Address
> f1krmypm4uoxxf3g7okrwtrahlmpcph3y7rbqqgfa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedqi45ugbqdjmlri5ygn4tyr5ybi5jstwfnm6r5g7b4tu3squ744k

**Comment by dkkapur** [comment]
Proposal went through AFAIK, @s0nik42 you just need an approval. Thanks!

**Comment by dannyob** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceboyxv55jjuqxsoxipkl3xhhhis2faf3qeht5xn7rzutly2nrcgba 
#### Address 
> f1x2wjpopqkrg6qtrhm2ieifcqwc5er7dy3usqkgi
#### Datacap Allocated
> 25.00TiB
#### Signer Address
> f1k6wwevxvp466ybil7y2scqlhtnrz5atjkkyvm4a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceboyxv55jjuqxsoxipkl3xhhhis2faf3qeht5xn7rzutly2nrcgba

**Comment by filplus-checker** [comment]
## DataCap and CID Checker Report[^1]
 - Organization: `Twin Quasar`
 - Client: `f1x2wjpopqkrg6qtrhm2ieifcqwc5er7dy3usqkgi`
### Storage Provider Distribution
The below table shows the distribution of storage providers that have stored data for this client.

If this is the first time a provider takes verified deal, it will be marked as `new`.

For most of the datacap application, below restrictions should apply.
 - Storage provider should not exceed 25% of total datacap.
 - Storage provider should not be storing duplicate data for more than 20%.
 - Storage provider should have published its public IP address.
 - All storage providers should be located in different regions.

⚠️ [f01385207](https://filfox.info/en/address/f01385207) has sealed 99.22% of total datacap.

⚠️ 50.00% of total deal sealed by [f010479](https://filfox.info/en/address/f010479) are duplicate data.

| Provider                                              |                 Location | Total Deals Sealed | Percentage | Unique Data | Duplicate Deals |
| :---------------------------------------------------- | -----------------------: | -----------------: | ---------: | ----------: | --------------: |
| [f01385207](https://filfox.info/en/address/f01385207) |    Lincoln, Nebraska, US |           8.00 TiB |     99.22% |    8.00 TiB |           0.00% |
| [f010479](https://filfox.info/en/address/f010479)     | Paris, Île-de-France, FR |          64.00 GiB |      0.78% |   32.00 GiB |          50.00% |

![Provider Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/368/1671096226484.png)
### Deal Data Replication
The below table shows how each many unique data are replicated across storage providers.
- No more than 25% of unique data are stored with less than 4 providers.

⚠️ 100.00% of deals are for data replicated across less than 4 storage providers.

| Unique Data Size | Total Deals Made | Number of Providers | Deal Percentage |
| ---------------: | ---------------: | ------------------: | --------------: |
|         7.97 TiB |         7.97 TiB |                   1 |          98.84% |
|        32.00 GiB |        96.00 GiB |                   2 |           1.16% |

![Replication Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/368/1671096227174.png)
### Deal Data Shared with other Clients
The below table shows how many unique data are shared with other clients.
Usually different applications owns different data and should not resolve to the same CID.

✔️ No CID sharing has been observed.

[^1]: To manually trigger this report, add a comment with text `checker:manualTrigger`

**Comment by data-programs** [comment]
<img width="32" alt="KYC" Verified src="https://stable.filplus.storage/images/filplus-kyc-verified-badge.png"/>

This user’s identity has been verified through [filplus.storage](https://filplus.storage)

**Comment by Sunnyiscoming** [comment]
Hello, @s0nik42 per the https://github.com/filecoin-project/notary-governance/issues/922 for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

This information will be reviewed by Fil+ Governance team to confirm validity and then the application will be allowed to move forward for additional notary review.
