### ISSUE TITLE
Twinquasar / Nasa Nex 

### ISSUE THREAD

**Issue by s0nik42** [filecoin-project/filecoin-plus-large-datasets#369]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Twin Quasar
- Website / Social Media: twinquasar.io
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 400TiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 290TiB
- On-chain address for first allocation: f1zo3n62q6j5b3rfc4drj67d5e7hr5pqtygxy6s6i

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
At twinquasar we are onboarding data to Slingshot since Slingshot 2.2 . Our goal is to onboard useful data to the network in a reusable way. ```

What is the primary source of funding for this project?
```
Our own funds```

What other projects/ecosystem stakeholders is this project associated with?
```
PL via the Slinshot challenge
```

## Use-case details

Describe the data being stored onto Filecoin
```
NASA NEX dataset
```

Where was the data in this dataset sourced from?
```
Nasa NEX is a collection of Earth science datasets maintained by NASA, including climate change projections and satellite images of the Earth's surface.

The dataset is coming from AWS public S3 repo  : https://registry.opendata.aws/nasanex/

```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
A link to 

Available at s3://nasanex/NEX-DCP30


```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes
```

What is the expected retrieval frequency for this data?
```
Not much
```

For how long do you plan to keep this dataset stored on Filecoin?
```
18 months
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
US
APAC
EUROPE

```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Data will transfered ofline
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We're selecting the SPs with high reputation on slack  and who already participate to Slingshot. They have the ability to store deals at a very fast pace and a high success rate.  

```

How will you be distributing deals across storage providers?
```
1 to 2 copies per company
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes
```

**Comment by galen-mcandrew** [comment]
## Multisig Notary requested
#### Total DataCap requested 
> 400TiB
#### Expected weekly DataCap usage rate 
> 290TiB

**Comment by neogeweb3** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacea3knbd22u2ebarin52q6pgdb3aqggfjwbsfsu7jemgurjvs5ie34 
#### Address 
> f1zo3n62q6j5b3rfc4drj67d5e7hr5pqtygxy6s6i
#### Datacap Allocated
> 20.00TiB
#### Signer Address
> f13k5zr6ovc2gjmg3lvd43ladbydhovpylcvbflpa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacea3knbd22u2ebarin52q6pgdb3aqggfjwbsfsu7jemgurjvs5ie34

**Comment by cryptowhizzard** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebnwjzwre2j76gglpr3omkebkfmz2kows2rmgbx2xdyrrrhanm2tc 
#### Address 
> f1zo3n62q6j5b3rfc4drj67d5e7hr5pqtygxy6s6i
#### Datacap Allocated
> 20.00TiB
#### Signer Address
> f1krmypm4uoxxf3g7okrwtrahlmpcph3y7rbqqgfa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebnwjzwre2j76gglpr3omkebkfmz2kows2rmgbx2xdyrrrhanm2tc

**Comment by data-programs** [comment]
<img width="32" alt="KYC" Verified src="https://stable.filplus.storage/images/filplus-kyc-verified-badge.png"/>

This user’s identity has been verified through [filplus.storage](https://filplus.storage)
