### ISSUE TITLE
[DataCap Application]Zhonghe Mineral Processing Technology

### ISSUE THREAD

**Issue by ZHPT-FILplus** [filecoin-project/filecoin-plus-large-datasets#371]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Zhonghe Mineral Processing Technology
- Website / Social Media:Website:http://en.hczhkx.com/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):3 PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):100TiB
- On-chain address for first allocation:f1qntyafmuq5h3moldezdkpgiiycbilrsvgfvyzti

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
The company is subordinate to Anshan Hengtong group, which is a comprehensive and service-oriented enterprise mainly engaged in direct and reverse flotation of magnesite. The main business includes engineering consulting, process design, engineering construction, mineral processing experiment, equipment manufacturing, reagent research and development, equipment maintenance, personnel training, etc. It is the only domestic housekeeper service-oriented enterprise aiming at magnesite beneficiation process.
```

What is the primary source of funding for this project?
```
Business revenue 
```

What other projects/ecosystem stakeholders is this project associated with?
```
Traditional commerce
```

## Use-case details

Describe the data being stored onto Filecoin
```
video, jpg, docs including equipment data, operational content, design content, product information, and development research
```

Where was the data in this dataset sourced from?
```
Different data comes from different departments. For example: the announcement content comes from the marketing department, and the product information comes from the product department. In addition, the most important thing is that our company has been working on the research and discovery of magnesite, and we have cooperated with many universities. There are many specialized research topics.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
http://www.hczhkx.com/news/496.html
http://www.hczhkx.com/news/495.html
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes,it is
```

What is the expected retrieval frequency for this data?
```
No exactly number. Maybe twice a year
```

For how long do you plan to keep this dataset stored on Filecoin?
```
For now, it is the first time we try decentralized storage. We may store 2 years for a try.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Asia, North America, Europe
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Now we store our data set online and also have offline copy. We want storage provider to download online. 
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We will select storage provider on official website who nearby us. Also, the basic information we must in consider.
```

How will you be distributing deals across storage providers?
```
Allocate evenly.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, we do. 
However Filecoin is relatively a new scope for us, we want to make an attmept on decentralized storage. Hope this will surprise me. 
```

**Comment by Sunnyiscoming** [comment]
@ZHPT-FILplus Hi,
As you said, you will store video, jpg, docs including equipment data, operational content, design content, product information, and development research in the Filecoin network.
Can you provide more related data samples with the above data description to prove that you have 5 PB data already? Videos would be better.

**Comment by Yvette516** [comment]
@ZHPT-FILplus @Sunnyiscoming I just gave official Key person a call, he said he didn't know any information about filecoin and hadn't applied for DataCap.

**Comment by Zhonghe112211** [comment]
@Sunnyiscoming Hey there!  The github account i used before, i can't login with no reason.  Can I use this account to communicate with you？
The person you have called with is our vice president. Our leader who in charge in this has synchronized with the vice president now. You can have a call or email. 
Thank you!

**Comment by Sunnyiscoming** [comment]
@Yvette516 Can you help to check the result?
The person you have called with is our vice president. Our leader who in charge in this has synchronized with the vice president now. You can have a call or email.
Thank you!

**Comment by Zhonghe112211** [comment]
Hello @Sunnyiscoming 
We are still waiting for confirmation. 
What else should we do?  Can anyone help us to check it out, please?
Thanks a lot!

**Comment by Sunnyiscoming** [comment]
> @ZHPT-FILplus Hi,
> As you said, you will store video, jpg, docs including equipment data, operational content, design content, product information, and development research in the Filecoin network.
> Can you provide more related data samples with the above data description to prove that you have 5 PB data already? Videos would be better.

I asked questions before but I do not receive any information about that.

**Comment by Sunnyiscoming** [comment]
The data samples you provided just two related articles.

**Comment by Zhonghe112211** [comment]
> > @ZHPT-FILplus Hi,
> > As you said, you will store video, jpg, docs including equipment data, operational content, design content, product information, and development research in the Filecoin network.
> > Can you provide more related data samples with the above data description to prove that you have 5 PB data already? Videos would be better.
> 
> I asked questions before but I do not receive any information about that.

@Sunnyiscoming Hello! Sorry I didn't mentioned this question before. 
Total amount of Datacap I requested for 3PiB. 
Here are data samples for video, Please kindly take a look, Thank you! 
https://drive.google.com/file/d/1W5ahtZfo5DKOME8IRQ-wzWDicNms6-K6/view?usp=sharing
https://drive.google.com/file/d/1zjQ8uqi2sCtiU3z9Zspz79Dq1DcWaesh/view?usp=sharing
https://drive.google.com/file/d/1vZVSCpjchLMsPSahkPLXIs5zO5lufted/view?usp=sharing

**Comment by Zhonghe112211** [comment]
@galen-mcandrew @Sunnyiscoming 
Currently, We have already prepared the dataset of 1.5 PiB with 3 to 4 replicates. The transfer method will most use hard drives. Can anyone do me a favor to push the application to the next step? Everything is ready now! Great thanks!

**Comment by raghavrmadya** [comment]
<img width="1280" alt="Screen Shot 2022-08-09 at 11 12 30 PM" src="https://user-images.githubusercontent.com/91579519/183828417-eef23ee9-7fa2-4a4a-99f0-e6fa9cb193ed.png">
?

**Comment by raghavrmadya** [comment]
The 3 PiBs request is still unclear. Please provide additional evidence of your role in the company and more insight into the SP allocation plan.

**Comment by Zhonghe112211** [comment]
Hello @raghavrmadya,
Thank you so much for the reminder! The website is working now. Please check it out.
I understand your concerns. We can use the email on the official website (htfx2018@163.com) to send you an email to confirm my identity. What do you think?
Regarding the distribution plan of DC, we expect to have four replicas. We search for the SPs in the deal market channel in slack and the websites. Recently, We are negotiating with ,f01878534, f01250837, f01893023, f01843994,f01790264 etc., The final SP allocation result is not fixed. However, data will be effectively dispersed on SPs in different regions.
Thank you.

**Comment by Sunnyiscoming** [comment]
Could you send an email to filplus-app-review@fil.org with your official domain in order to confirm your identity?
Email name should includes the issue id #371.

**Comment by Zhonghe112211** [comment]
Hello @raghavrmadya @Sunnyiscoming, 
The email has been sent, Please take a look! 
Thank you!

**Comment by Zhonghe112211** [comment]
Hiyo @Sunnyiscoming @raghavrmadya ,
May I ask how is everything going on? Just wondering if you have a chance to read my email below.

**Comment by Sunnyiscoming** [comment]
You should send with your official domain (hczhkx.com))in order to confirm your identity rather than 163 email address.

**Comment by Zhonghe112211** [comment]
![屏幕快照 2022-08-17 下午2 39 57](https://user-images.githubusercontent.com/108108802/185051638-a12de5f6-dfc6-4786-9333-a0f2ff194413.png)
Hey @Sunnyiscoming , 
htfx2018@163.com is our official email and it is shown on our official web. Doesn't this still prove my identity??
Please take a look at our web, Thank you so much!

**Comment by zhonghe112211-Fil** [comment]
Hello @Sunnyiscoming @raghavrmadya ,

I hope this message finds you well! We are very sorry for the inconvenience caused I don't know why my previous github account can't be used.  I need to communicate using a new account. I'm not familiar with Github actually. Appreciated your understand.

Here's a summary of my previous responses to various questions:
1. Here are data samples for video, Please kindly take a look, Thank you!
https://drive.google.com/file/d/1W5ahtZfo5DKOME8IRQ-wzWDicNms6-K6/view?usp=sharing
https://drive.google.com/file/d/1zjQ8uqi2sCtiU3z9Zspz79Dq1DcWaesh/view?usp=sharing
https://drive.google.com/file/d/1vZVSCpjchLMsPSahkPLXIs5zO5lufted/view?usp=sharing
2. Regarding the distribution plan of DC, we expect to have four replicas. We search for the SPs in the deal market channel in slack and the websites. Recently, We are negotiating with ,f01878534, f01250837, f01893023, f01843994,f01790264 etc., The final SP allocation result is not fixed. However, data will be effectively dispersed on SPs in different regions.
3. Currently, We have already prepared the dataset of 1.5 PiB with 3 to 4 replicates. The transfer method will most use hard drives. 
4. I have sent an email to filplus-app-review@fil.org . What's more,  htfx2018@163.com is our official email and it is shown on our official web.  I think it can prove my identity totally. Also I sent another email to prove my identity.  
![095b35125e365435412c45fa99e1f49](https://user-images.githubusercontent.com/110814735/185630334-21acbff9-8fbe-4982-a3d4-1dd6c96761ef.png)
![6ab8a705261a2e222a0305a1398f51e](https://user-images.githubusercontent.com/110814735/185630438-0b4c89fe-87fc-45e5-a757-03774c293754.png)
Thank you!

**Comment by raghavrmadya** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 3 PiB

**Expected weekly DataCap usage rate**

> 100 TiB

**Client address**

> f1qntyafmuq5h3moldezdkpgiiycbilrsvgfvyzti

**Comment by raghavrmadya** [comment]
Thanks @ZHPT-FILplus. Please be open to community questions if they come in to ensure consistent allocation of DataCap

**Comment by liyunzhi-666** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecpkqbrvxu75p4pz46i5dwkfsk2x6sfzjapsv3iobppv6ch7fvbdi 
#### Address 
> f1qntyafmuq5h3moldezdkpgiiycbilrsvgfvyzti
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1pszcrsciyixyuxxukkvtazcokexbn54amf7gvoq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecpkqbrvxu75p4pz46i5dwkfsk2x6sfzjapsv3iobppv6ch7fvbdi

**Comment by fireflyHZ** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceanrri7zmvbch557zijzzq4sqrpvn3lcn3jut7hzyhxhh4tdfcld2 
#### Address 
> f1qntyafmuq5h3moldezdkpgiiycbilrsvgfvyzti
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1fg6jkxsr3twfnyhdlatmq36xca6sshptscds7xa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceanrri7zmvbch557zijzzq4sqrpvn3lcn3jut7hzyhxhh4tdfcld2

**Comment by 1LISA2** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacea2fw5hdbkpiytxpxpwdjmwu4tkmkxlyet63xphfcqpahps4vqhj6 
#### Address 
> f1qntyafmuq5h3moldezdkpgiiycbilrsvgfvyzti
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1jvvltduw35u6inn5tr4nfualyd42bh3vjtylgci
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacea2fw5hdbkpiytxpxpwdjmwu4tkmkxlyet63xphfcqpahps4vqhj6

**Comment by BigD-Exchange** [comment]
@ZHPT-FILplus Hi! Great to see you have gotten approval for DataCap. If you are looking for storage providers to store these data or have any questions, please visit #bigdata-exchange on Filecoin Slack or reply here. 

We have strong demand from a diverse group of SPs, who are actively looking to onboard more data.

**Comment by newwebgroup** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebgggcw52uld4ebsehrgj7c7hd5zdzglpzsujetoaanl7iaojp26g 
#### Address 
> f1qntyafmuq5h3moldezdkpgiiycbilrsvgfvyzti
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1e77zuityhvvw6u2t6tb5qlnsegy2s67qs4lbbbq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebgggcw52uld4ebsehrgj7c7hd5zdzglpzsujetoaanl7iaojp26g

**Comment by Tom-OriginStorage** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebfmhj6zmt2yvdoillpwgqwemivj2idv5yiouwn5iqgwxdletqmfy 
#### Address 
> f1qntyafmuq5h3moldezdkpgiiycbilrsvgfvyzti
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1q6bpjlqia6iemqbrdaxr2uehrhpvoju3qh4lpga
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebfmhj6zmt2yvdoillpwgqwemivj2idv5yiouwn5iqgwxdletqmfy

**Comment by szalongdzyxgs** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedh2ymyu7dps2l7sdh5sh3f5ohtx6d2a3c225lauf6loskj66r2vq 
#### Address 
> f1qntyafmuq5h3moldezdkpgiiycbilrsvgfvyzti
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1dnb3uz7sylxk6emti3ififcvu3nlufnnsjui6ea
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedh2ymyu7dps2l7sdh5sh3f5ohtx6d2a3c225lauf6loskj66r2vq

**Comment by 1ane-1** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebexwxukhfb745pvg47p7fvutcbhdf3kiiprwdynwc65y6bubgemy 
#### Address 
> f1qntyafmuq5h3moldezdkpgiiycbilrsvgfvyzti
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1mdk7s2vntzm6hu35yuo6vjubtrpfnb2awhgvrri
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebexwxukhfb745pvg47p7fvutcbhdf3kiiprwdynwc65y6bubgemy

**Comment by liyunzhi-666** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacea4v2abc3unrwtbcx3cn6yzp2i6ujw2c6upwtnmbqe5ptb3nufk56 
#### Address 
> f1qntyafmuq5h3moldezdkpgiiycbilrsvgfvyzti
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1pszcrsciyixyuxxukkvtazcokexbn54amf7gvoq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacea4v2abc3unrwtbcx3cn6yzp2i6ujw2c6upwtnmbqe5ptb3nufk56

**Comment by psh0691** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebgtndg6du7frr36bjmvsmlww3wscd5ietwduuxl4vyxezrz5prcq 
#### Address 
> f1qntyafmuq5h3moldezdkpgiiycbilrsvgfvyzti
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1qdko4jg25vo35qmyvcrw4ak4fmuu3f5rif2kc7i
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebgtndg6du7frr36bjmvsmlww3wscd5ietwduuxl4vyxezrz5prcq

**Comment by Defil2022** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacect6pm2kgifu7el6liuocgkv5yb2v56akor6s66utrfomewitcyek 
#### Address 
> f1qntyafmuq5h3moldezdkpgiiycbilrsvgfvyzti
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1dnb3uz7sylxk6emti3ififcvu3nlufnnsjui6ea
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacect6pm2kgifu7el6liuocgkv5yb2v56akor6s66utrfomewitcyek

**Comment by stcouldlisa** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedvppag7g7rtf2zyntl3b4oevlakohosx6tnvxv5hc6cuyargd7z2 
#### Address 
> f1qntyafmuq5h3moldezdkpgiiycbilrsvgfvyzti
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1jvvltduw35u6inn5tr4nfualyd42bh3vjtylgci
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedvppag7g7rtf2zyntl3b4oevlakohosx6tnvxv5hc6cuyargd7z2

**Comment by Tom-OriginStorage** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaswne4teij7jj7tmbqqc3p4beoiayirfipm5l4xrzi3opjtusf22 
#### Address 
> f1qntyafmuq5h3moldezdkpgiiycbilrsvgfvyzti
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1q6bpjlqia6iemqbrdaxr2uehrhpvoju3qh4lpga
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaswne4teij7jj7tmbqqc3p4beoiayirfipm5l4xrzi3opjtusf22

**Comment by NDLABS-OFFICE** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedlu7havyfus7lw6mg2uw5qj2deqkqjkmwathp5gz4kglr2jfx7hi 
#### Address 
> f1qntyafmuq5h3moldezdkpgiiycbilrsvgfvyzti
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1yayfsv6whu3rheviucvventj3y6t542xfpb47ei
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedlu7havyfus7lw6mg2uw5qj2deqkqjkmwathp5gz4kglr2jfx7hi

**Comment by fireflyHZ** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaj4xcbmqnzb7fns22tuhfyqmzv2udvmejkj3uilitied2tbf5sfe 
#### Address 
> f1qntyafmuq5h3moldezdkpgiiycbilrsvgfvyzti
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1fg6jkxsr3twfnyhdlatmq36xca6sshptscds7xa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaj4xcbmqnzb7fns22tuhfyqmzv2udvmejkj3uilitied2tbf5sfe

**Comment by filplus-checker** [comment]
## DataCap and CID Checker Report[^1]
 - Organization: `Zhonghe Mineral Processing Technology`
 - Client: `f1qntyafmuq5h3moldezdkpgiiycbilrsvgfvyzti`
### Storage Provider Distribution
The below table shows the distribution of storage providers that have stored data for this client.

If this is the first time a provider takes verified deal, it will be marked as `new`.

For most of the datacap application, below restrictions should apply.
 - Storage provider should not exceed 25% of total datacap.
 - Storage provider should not be storing duplicate data for more than 20%.
 - Storage provider should have published its public IP address.
 - All storage providers should be located in different regions.

⚠️ 84.68% of total deal sealed by [f01916645](https://filfox.info/en/address/f01916645) are duplicate data.

⚠️ [f01916645](https://filfox.info/en/address/f01916645) has unknown IP location.

⚠️ 84.71% of total deal sealed by [f01854080](https://filfox.info/en/address/f01854080) are duplicate data.

⚠️ 75.13% of total deal sealed by [f01893023](https://filfox.info/en/address/f01893023) are duplicate data.

⚠️ 72.33% of total deal sealed by [f01834253](https://filfox.info/en/address/f01834253) are duplicate data.

⚠️ 70.02% of total deal sealed by [f01834291](https://filfox.info/en/address/f01834291) are duplicate data.

⚠️ 74.05% of total deal sealed by [f01740934](https://filfox.info/en/address/f01740934) are duplicate data.

⚠️ 88.80% of total deal sealed by [f01715155](https://filfox.info/en/address/f01715155) are duplicate data.

| Provider                                              |                    Location | Total Deals Sealed | Percentage | Unique Data | Duplicate Deals |
| :---------------------------------------------------- | --------------------------: | -----------------: | ---------: | ----------: | --------------: |
| [f01916645](https://filfox.info/en/address/f01916645) |                     Unknown |         313.53 TiB |     19.11% |   48.03 TiB |          84.68% |
| [f01854080](https://filfox.info/en/address/f01854080) | Los Angeles, California, US |         247.34 TiB |     15.07% |   37.81 TiB |          84.71% |
| [f01893023](https://filfox.info/en/address/f01893023) | Los Angeles, California, US |         182.97 TiB |     11.15% |   45.50 TiB |          75.13% |
| [f01834253](https://filfox.info/en/address/f01834253) | Los Angeles, California, US |         152.47 TiB |      9.29% |   42.19 TiB |          72.33% |
| [f01834291](https://filfox.info/en/address/f01834291) | Los Angeles, California, US |         139.59 TiB |      8.51% |   41.84 TiB |          70.02% |
| [f01740934](https://filfox.info/en/address/f01740934) | Los Angeles, California, US |         139.56 TiB |      8.50% |   36.22 TiB |          74.05% |
| [f01773206](https://filfox.info/en/address/f01773206) |            Seoul, Seoul, KR |         138.19 TiB |      8.42% |  138.19 TiB |           0.00% |
| [f01880364](https://filfox.info/en/address/f01880364) |            Seoul, Seoul, KR |         125.91 TiB |      7.67% |  125.91 TiB |           0.00% |
| [f01878656](https://filfox.info/en/address/f01878656) |            Seoul, Seoul, KR |         101.72 TiB |      6.20% |  101.72 TiB |           0.00% |
| [f01709150](https://filfox.info/en/address/f01709150) |            Seoul, Seoul, KR |          87.69 TiB |      5.34% |   87.69 TiB |           0.00% |
| [f01715155](https://filfox.info/en/address/f01715155) |    Singapore, Singapore, SG |          12.00 TiB |      0.73% |    1.34 TiB |          88.80% |

![Provider Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/371/1671096248071.png)
### Deal Data Replication
The below table shows how each many unique data are replicated across storage providers.
- No more than 25% of unique data are stored with less than 4 providers.

⚠️ 99.89% of deals are for data replicated across less than 4 storage providers.

| Unique Data Size | Total Deals Made | Number of Providers | Deal Percentage |
| ---------------: | ---------------: | ------------------: | --------------: |
|       517.66 TiB |       888.19 TiB |                   1 |          54.13% |
|        44.19 TiB |       425.16 TiB |                   2 |          25.91% |
|        33.22 TiB |       325.78 TiB |                   3 |          19.85% |
|       192.00 GiB |         1.84 TiB |                   4 |           0.11% |

![Replication Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/371/1671096248723.png)
### Deal Data Shared with other Clients
The below table shows how many unique data are shared with other clients.
Usually different applications owns different data and should not resolve to the same CID.

⚠️ CID sharing has been observed.

| Other Client                                                                                                          | Application                                                                                                        | Total Deals Affected | Unique CIDs |        Verifier |
| :-------------------------------------------------------------------------------------------------------------------- | :----------------------------------------------------------------------------------------------------------------- | -------------------: | ----------: | --------------: |
| [f1mhyxd4unemmhrw4dbhjcovivayrj3tyactezmzq](https://filfox.info/en/address/f1mhyxd4unemmhrw4dbhjcovivayrj3tyactezmzq) | `GOLDEN SECURITY`                                                                                                  |           164.31 TiB |       1,106 | LDN v3 multisig |
| [f1nkh5as6inqcvcoiliumdmvai2luahw5imdqug5a](https://filfox.info/en/address/f1nkh5as6inqcvcoiliumdmvai2luahw5imdqug5a) | ``                                                                                                                 |            37.47 TiB |         225 |            Eden |
| [f1gmiepn73zoa5gz2oiqyugjmrsecwj5qxd42vmyi](https://filfox.info/en/address/f1gmiepn73zoa5gz2oiqyugjmrsecwj5qxd42vmyi) | ``                                                                                                                 |            19.34 TiB |          82 | LDN v3 multisig |
| [f1ng6g57r4u62q67u6lm33ftijfsggyzzjzb2l4cy](https://filfox.info/en/address/f1ng6g57r4u62q67u6lm33ftijfsggyzzjzb2l4cy) | [NFTSTAR](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/960)                             |            18.06 TiB |         103 | LDN v3 multisig |
| [f1ji2xty4dtg2a4pfnslltkw7pbhy76kvihizkfmq](https://filfox.info/en/address/f1ji2xty4dtg2a4pfnslltkw7pbhy76kvihizkfmq) | `Pow Power`                                                                                                        |            12.06 TiB |          66 | LDN v3 multisig |
| [f1guplg5wyjdn6bv4forsb5eu2lohexvdlttkavpq](https://filfox.info/en/address/f1guplg5wyjdn6bv4forsb5eu2lohexvdlttkavpq) | [Ipollo](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/168)                              |            10.09 TiB |          65 |       LDN # 168 |
| [f1y7xmlneep3qtxcumqlmqrja3fhqdxdaxwou6mdq](https://filfox.info/en/address/f1y7xmlneep3qtxcumqlmqrja3fhqdxdaxwou6mdq) | [ND LABS](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/109)                             |             8.72 TiB |          56 |       LDN # 109 |
| [f1o2nxreefzqzc2mvaqneaolpdat5yk3275r6rofa](https://filfox.info/en/address/f1o2nxreefzqzc2mvaqneaolpdat5yk3275r6rofa) | [iPolloverse SG PTE\. LTD](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/767)            |             8.41 TiB |          64 | LDN v3 multisig |
| [f1dfkdmjhuvvol6okun57mix447wdpolwcd323ktq](https://filfox.info/en/address/f1dfkdmjhuvvol6okun57mix447wdpolwcd323ktq) | [BITRISE CAPITAL FOUNDATION PTE\.LTD](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/139) |             4.84 TiB |          45 |       LDN # 139 |
| [f1vajbbihmcqkcjlnicmjto6fflklvhoifips7uzq](https://filfox.info/en/address/f1vajbbihmcqkcjlnicmjto6fflklvhoifips7uzq) | `rctAI`                                                                                                            |             2.84 TiB |          28 | LDN v3 multisig |
| [f17d2n363326qlln4uva7ylxteamtdj3lq6wuaewi](https://filfox.info/en/address/f17d2n363326qlln4uva7ylxteamtdj3lq6wuaewi) | [Metadata Labs Inc](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/200)                   |             2.22 TiB |          23 |       LDN # 200 |
| [f1x73tab6haogefv37tstzws7vcv75javxfflceti](https://filfox.info/en/address/f1x73tab6haogefv37tstzws7vcv75javxfflceti) | ``                                                                                                                 |             1.59 TiB |          25 |            Eden |
| [f1lrfcq5ro2ax45omic5paii6rd6zqghcrygxyhhq](https://filfox.info/en/address/f1lrfcq5ro2ax45omic5paii6rd6zqghcrygxyhhq) | ``                                                                                                                 |             1.56 TiB |          21 |           Barry |
| [f1raeideaex2fwvoemftky6x5jzbqdawrgeuz2mry](https://filfox.info/en/address/f1raeideaex2fwvoemftky6x5jzbqdawrgeuz2mry) | [BBNews](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/218)                              |             1.38 TiB |           8 |       LDN # 218 |
| [f1ewwoms3aiairedun4h2uayqhlmtjsulnqy2xnrq](https://filfox.info/en/address/f1ewwoms3aiairedun4h2uayqhlmtjsulnqy2xnrq) | [AsiaBlockchain Gaming Alliance](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/179)      |           896.00 GiB |          10 |       LDN # 179 |
| [f1qpkmibcsitxtxwg6ayghxwkssoxs4bfyzwzslza](https://filfox.info/en/address/f1qpkmibcsitxtxwg6ayghxwkssoxs4bfyzwzslza) | [GAMEWAY PTE\. LTD\.](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/158)                 |           640.00 GiB |           2 |       LDN # 158 |
| [f16w5d2u57ndts6wcqupwwvrl7ewicrl5xnymfxui](https://filfox.info/en/address/f16w5d2u57ndts6wcqupwwvrl7ewicrl5xnymfxui) | `Maoyoo Network`                                                                                                   |           544.00 GiB |           4 | LDN v3 multisig |
| [f14vri3xpun2ts5oumbh5qnxj46746w6ptetcd7my](https://filfox.info/en/address/f14vri3xpun2ts5oumbh5qnxj46746w6ptetcd7my) | ``                                                                                                                 |           192.00 GiB |           5 |            Eden |
| [f1pnsnrfp5dqfqwospzj6vis6jxhni765i37tne5q](https://filfox.info/en/address/f1pnsnrfp5dqfqwospzj6vis6jxhni765i37tne5q) | [TIMAGE](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/302)                              |           160.00 GiB |           1 | LDN v3 multisig |
| [f14kei3mbjobgsfszu5cndhosuobkbbtoaikc52pq](https://filfox.info/en/address/f14kei3mbjobgsfszu5cndhosuobkbbtoaikc52pq) | [Proya](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/295)                               |           160.00 GiB |           1 | LDN v3 multisig |
| [f1adfy6de75my4pvhsf2yvz7qfu6nlsjmxpbg6rsa](https://filfox.info/en/address/f1adfy6de75my4pvhsf2yvz7qfu6nlsjmxpbg6rsa) | ``                                                                                                                 |            32.00 GiB |           1 |             Nic |

[^1]: To manually trigger this report, add a comment with text `checker:manualTrigger`
