### ISSUE TITLE
[DataCap Application]KONGFU VR

### ISSUE THREAD

**Issue by KONGFU-VR** [filecoin-project/filecoin-plus-large-datasets#372]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: KONGFU VR
- Website / Social Media:  http://kongfuvr.io/ https://store.steampowered.com/app/1906880/KONGFU_VR/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 300TiB
- On-chain address for first allocation: f14abwn2goturifmt27s2bssoe3fup2b3npkgfzui

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
KONGFU VR is the world's first metaverse VR GameFi. It has PVE + PVP mode and a huge view of the universe like Marvel Universe, a variety of mythical characters, famous heroes and other rich characters in the East and the west, and more than 100 kinds of props, weapons and skin. In the future, an open, immersive, sustainable and in-depth 3A level large-scale game will be built. The game has a perfect sustainable economic model. Upgrade Play-To-Earn mode to 2.0 “ Playing Fun, Keep Earning ! ”. This is a cross-era subversive VR GameFi.
```

What is the primary source of funding for this project?
```
Our company.
```

What other projects/ecosystem stakeholders is this project associated with?
```
No.
```

## Use-case details

Describe the data being stored onto Filecoin
```
100% copyright of our game data: pictures, videos, database, texture, 3D model, transactions, shader, audio.
```

Where was the data in this dataset sourced from?
```
From the game, NFT and transaction data from BNBSC.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
![Data Sample Tatsu](https://user-images.githubusercontent.com/105405987/169650559-9d744b4c-6a1d-4d59-80c8-5df6436257cf.jpg)
![Data Sample Tora](https://user-images.githubusercontent.com/105405987/169650561-588d6918-726a-4650-9a28-bef6388c6aa1.jpg)
![Data Sample U](https://user-images.githubusercontent.com/105405987/169650565-75c133b2-3798-44d6-bec8-0eadc00907ae.jpg)
![Data Sample Ushi](https://user-images.githubusercontent.com/105405987/169650568-d183334f-2848-4bfd-af10-94874185ca28.jpg)
![Data Sample Ne](https://user-images.githubusercontent.com/105405987/169650570-480ba3bc-283f-4589-ab25-72200461e199.jpg)
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes, we choose public data to make request for filecoin.
```

What is the expected retrieval frequency for this data?
```
Backup file only, retrieval depends on the request of our business.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
With the roadmap of our game, we plan to keep it at least need 3 years.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Asia and Britain.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Both online and offline transfer.  
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We plan to have 4-6 SP， ≤ 25% of our data will be sending to them.
```

How will you be distributing deals across storage providers?
```
So far we have found 2 storage providers in UK and one in Hongkong. We'll continue looking for other storage providers via slack and github. We may need more storage providers in the future.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Sure! We hope community can help recommend providers for deal. Welcome more storage providers.
```

**Comment by KONGFU-VR** [comment]
@Kevin-FF-USA I've uploaded the video to Google Drive Folder.

**Comment by KONGFU-VR** [comment]
> @Kevin-FF-USA I've uploaded the video to Google Drive Folder.

Hey Kevin, I'm waiting for the datacap!

**Comment by UnionLabs2020** [comment]
According to our common KYC method ,could you give filplus@fil.org a double confirmation from your official mail?

**Comment by Sunnyiscoming** [comment]
@KONGFU-VR It seems to be something wrong with the menu of the website, please check it.

**Comment by KONGFU-VR** [comment]
@UnionLabs2020 The confirming email was sent at 4:44 PM. 
@Sunnyiscoming We are updating our website now and it will done after 5th July. I also explained it in my email. Thank you!

**Comment by KONGFU-VR** [comment]
![coin](https://user-images.githubusercontent.com/105405987/176578037-346e0f28-3ad6-4166-be58-f5e55bbf0280.png)
@UnionLabs2020 Should I show this mail here?

**Comment by UnionLabs2020** [comment]
OK, thanks for your reply.

**Comment by galen-mcandrew** [comment]
## Datacap Request Trigger
#### Total DataCap requested 
> 5PiB
#### Expected weekly DataCap usage rate 
> 300TiB 
#### Client address
> f14abwn2goturifmt27s2bssoe3fup2b3npkgfzui

**Comment by MRJAVAZHAO** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedl23f32gdfhllahfvkyybnqwamop6slh4ioruwgjcjmefgop7wnw 
#### Address 
> f14abwn2goturifmt27s2bssoe3fup2b3npkgfzui
#### Datacap Allocated
> 150.00TiB
#### Signer Address
> f14gme3f52prtyzk6pblogrdd6b6ivp4swc6qmesi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedl23f32gdfhllahfvkyybnqwamop6slh4ioruwgjcjmefgop7wnw

**Comment by PluskitOfficial** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb3mq7cwj3kclqfhyhdbhkf3ryzcf3uv3vuegg3mxb3varb3vq2c6 
#### Address 
> f14abwn2goturifmt27s2bssoe3fup2b3npkgfzui
#### Datacap Allocated
> 150.00TiB
#### Signer Address
> f1tgnlhtcmhwipfm7thsftxhn5k52velyjlazpvka
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb3mq7cwj3kclqfhyhdbhkf3ryzcf3uv3vuegg3mxb3varb3vq2c6

**Comment by kevzak** [comment]
Hello @KONGFU-VR  - I'm Kevin from the Client Success Team. I saw you were recently granted DataCap and began onboarding data. I wanted to reach out as you getting started to offer any support as needed. Let me know if you have any questions or issues.

Also, fell free to post a message in #fil-plus slack channel.

**Comment by MRJAVAZHAO** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacea3jsrqpw4helupc7puwzex2mo7f7xyi5warpeeniqurturf2mu7a 
#### Address 
> f14abwn2goturifmt27s2bssoe3fup2b3npkgfzui
#### Datacap Allocated
> 300.00TiB
#### Signer Address
> f14gme3f52prtyzk6pblogrdd6b6ivp4swc6qmesi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacea3jsrqpw4helupc7puwzex2mo7f7xyi5warpeeniqurturf2mu7a

**Comment by MetaWaveInfo** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebvtgu5yrxchgvtdcah2rrnmjzwfxly3fydzcufcvbs7iv236mh2y 
#### Address 
> f14abwn2goturifmt27s2bssoe3fup2b3npkgfzui
#### Datacap Allocated
> 300.00TiB
#### Signer Address
> f1ktlkcxnmzxcdaoqfsunrg3vocfbmgv4n3mrn74a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebvtgu5yrxchgvtdcah2rrnmjzwfxly3fydzcufcvbs7iv236mh2y

**Comment by MRJAVAZHAO** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedcqeh7df773pcxwrvy4eg6qetmmc4hkupssgygdw37h3kkhbtxb6 
#### Address 
> f14abwn2goturifmt27s2bssoe3fup2b3npkgfzui
#### Datacap Allocated
> 600.00TiB
#### Signer Address
> f14gme3f52prtyzk6pblogrdd6b6ivp4swc6qmesi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedcqeh7df773pcxwrvy4eg6qetmmc4hkupssgygdw37h3kkhbtxb6

**Comment by MatrixStorage** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebqp4qu32ci27yms4kgmkgxkxz5vbie3xkogljwhz4peb4fulpark 
#### Address 
> f14abwn2goturifmt27s2bssoe3fup2b3npkgfzui
#### Datacap Allocated
> 600.00TiB
#### Signer Address
> f1tbxqwjxfyv7swsdin4einirlsfquv3vnmlapley
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebqp4qu32ci27yms4kgmkgxkxz5vbie3xkogljwhz4peb4fulpark

**Comment by BlockMakeronline** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecolwqz5i5uwgevz37r66t5laoyhilunln6ibw5psxbkr3hrzdi6i 
#### Address 
> f14abwn2goturifmt27s2bssoe3fup2b3npkgfzui
#### Datacap Allocated
> 600.00TiB
#### Signer Address
> f1o3twrcpwjtpcd4q36lpq4qmy2qfbgtyy5h6tsty
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecolwqz5i5uwgevz37r66t5laoyhilunln6ibw5psxbkr3hrzdi6i

**Comment by BigD-Exchange** [comment]
@KONGFU-VR, great to see you have gotten approval for DataCap. If you are looking for storage providers to store these data, please visit #bigdata-exchange on Filecoin Slack.

**Comment by PluskitOfficial** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacea7zjaxvv4lxzwb7pleyiqar2y7gqaoqpxycymyqoujczdw2jvaoc 
#### Address 
> f14abwn2goturifmt27s2bssoe3fup2b3npkgfzui
#### Datacap Allocated
> 1.17PiB
#### Signer Address
> f1tgnlhtcmhwipfm7thsftxhn5k52velyjlazpvka
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacea7zjaxvv4lxzwb7pleyiqar2y7gqaoqpxycymyqoujczdw2jvaoc

**Comment by Fenbushi-Filecoin** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedhmau4vweeq6u26laljy65sstisxwqherkeo3nkqnow5dq2kechi 
#### Address 
> f14abwn2goturifmt27s2bssoe3fup2b3npkgfzui
#### Datacap Allocated
> 1.17PiB
#### Signer Address
> f1yqydpmqb5en262jpottko2kd65msajax7fi4rmq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedhmau4vweeq6u26laljy65sstisxwqherkeo3nkqnow5dq2kechi

**Comment by swatchliu** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec6i4mchwrp2heohvusmf6376hfuenrqvfu5xdjofjqek2wnda6xa 
#### Address 
> f14abwn2goturifmt27s2bssoe3fup2b3npkgfzui
#### Datacap Allocated
> 2.34PiB
#### Signer Address
> f1yh6q3nmsg7i2sys7f7dexcuajgoweudcqj2chfi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec6i4mchwrp2heohvusmf6376hfuenrqvfu5xdjofjqek2wnda6xa

**Comment by UnionLabs2022** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceabq5op3ohyiu2s7bymn634imvhsii5yhhojpnbwtjknykxhurpag 
#### Address 
> f14abwn2goturifmt27s2bssoe3fup2b3npkgfzui
#### Datacap Allocated
> 2.34PiB
#### Signer Address
> f17xdri3wunqgld7dm23e4f3eqsntjakwc47xjo6i
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceabq5op3ohyiu2s7bymn634imvhsii5yhhojpnbwtjknykxhurpag

**Comment by filplus-checker** [comment]
## DataCap and CID Checker Report[^1]
 - Organization: `KONGFU VR`
 - Client: `f14abwn2goturifmt27s2bssoe3fup2b3npkgfzui`
### Storage Provider Distribution
The below table shows the distribution of storage providers that have stored data for this client.

If this is the first time a provider takes verified deal, it will be marked as `new`.

For most of the datacap application, below restrictions should apply.
 - Storage provider should not exceed 25% of total datacap.
 - Storage provider should not be storing duplicate data for more than 20%.
 - Storage provider should have published its public IP address.
 - All storage providers should be located in different regions.

⚠️ 33.10% of total deal sealed by [f01895707](https://filfox.info/en/address/f01895707) are duplicate data.

⚠️ 32.38% of total deal sealed by [f01893290](https://filfox.info/en/address/f01893290) are duplicate data.

⚠️ 83.62% of total deal sealed by [f01885260](https://filfox.info/en/address/f01885260) are duplicate data.

⚠️ 45.89% of total deal sealed by [f01914977](https://filfox.info/en/address/f01914977) are duplicate data.

⚠️ 69.65% of total deal sealed by [f01879880](https://filfox.info/en/address/f01879880) are duplicate data.

⚠️ 79.29% of total deal sealed by [f01845679](https://filfox.info/en/address/f01845679) are duplicate data.

⚠️ [f01845679](https://filfox.info/en/address/f01845679) has unknown IP location.

⚠️ 34.67% of total deal sealed by [f01896513](https://filfox.info/en/address/f01896513) are duplicate data.

⚠️ 33.38% of total deal sealed by [f01895913](https://filfox.info/en/address/f01895913) are duplicate data.

⚠️ 74.81% of total deal sealed by [f01880898](https://filfox.info/en/address/f01880898) are duplicate data.

⚠️ 89.74% of total deal sealed by [f01889046](https://filfox.info/en/address/f01889046) are duplicate data.

⚠️ 66.69% of total deal sealed by [f01885280](https://filfox.info/en/address/f01885280) are duplicate data.

⚠️ 65.71% of total deal sealed by [f01880896](https://filfox.info/en/address/f01880896) are duplicate data.

⚠️ 76.01% of total deal sealed by [f01880894](https://filfox.info/en/address/f01880894) are duplicate data.

| Provider                                              |                           Location | Total Deals Sealed | Percentage | Unique Data | Duplicate Deals |
| :---------------------------------------------------- | ---------------------------------: | -----------------: | ---------: | ----------: | --------------: |
| [f01895707](https://filfox.info/en/address/f01895707) |           Singapore, Singapore, SG |         326.16 TiB |     14.55% |  218.19 TiB |          33.10% |
| [f01893290](https://filfox.info/en/address/f01893290) |           Singapore, Singapore, SG |         325.03 TiB |     14.50% |  219.78 TiB |          32.38% |
| [f01885260](https://filfox.info/en/address/f01885260) | Hong Kong, Central and Western, HK |         210.88 TiB |      9.41% |   34.53 TiB |          83.62% |
| [f01914977](https://filfox.info/en/address/f01914977) |              Ashburn, Virginia, US |         196.81 TiB |      8.78% |  106.50 TiB |          45.89% |
| [f01879880](https://filfox.info/en/address/f01879880) |           Singapore, Singapore, SG |         176.48 TiB |      7.88% |   53.57 TiB |          69.65% |
| [f01889480](https://filfox.info/en/address/f01889480) |               Boardman, Oregon, US |         149.88 TiB |      6.69% |  149.88 TiB |           0.00% |
| [f01845679](https://filfox.info/en/address/f01845679) |                            Unknown |         147.13 TiB |      6.57% |   30.47 TiB |          79.29% |
| [f01896513](https://filfox.info/en/address/f01896513) |           Singapore, Singapore, SG |         129.00 TiB |      5.76% |   84.28 TiB |          34.67% |
| [f01895913](https://filfox.info/en/address/f01895913) |           Singapore, Singapore, SG |         129.00 TiB |      5.76% |   85.94 TiB |          33.38% |
| [f01895783](https://filfox.info/en/address/f01895783) |               Boardman, Oregon, US |         128.00 TiB |      5.71% |  128.00 TiB |           0.00% |
| [f01880898](https://filfox.info/en/address/f01880898) |           Singapore, Singapore, SG |         123.69 TiB |      5.52% |   31.16 TiB |          74.81% |
| [f01889046](https://filfox.info/en/address/f01889046) |              Ashburn, Virginia, US |          84.09 TiB |      3.75% |    8.63 TiB |          89.74% |
| [f01885280](https://filfox.info/en/address/f01885280) | Hong Kong, Central and Western, HK |          39.78 TiB |      1.78% |   13.25 TiB |          66.69% |
| [f01880896](https://filfox.info/en/address/f01880896) |           Singapore, Singapore, SG |          38.00 TiB |      1.70% |   13.03 TiB |          65.71% |
| [f01880894](https://filfox.info/en/address/f01880894) |           Singapore, Singapore, SG |          37.00 TiB |      1.65% |    8.88 TiB |          76.01% |

![Provider Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/372/1671096267873.png)
### Deal Data Replication
The below table shows how each many unique data are replicated across storage providers.
- No more than 25% of unique data are stored with less than 4 providers.

⚠️ 93.71% of deals are for data replicated across less than 4 storage providers.

| Unique Data Size | Total Deals Made | Number of Providers | Deal Percentage |
| ---------------: | ---------------: | ------------------: | --------------: |
|       681.91 TiB |         1.34 PiB |                   1 |          61.44% |
|       126.66 TiB |       500.63 TiB |                   2 |          22.34% |
|        49.78 TiB |       222.44 TiB |                   3 |           9.93% |
|        25.38 TiB |       140.94 TiB |                   4 |           6.29% |

![Replication Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/372/1671096268498.png)
### Deal Data Shared with other Clients
The below table shows how many unique data are shared with other clients.
Usually different applications owns different data and should not resolve to the same CID.

⚠️ CID sharing has been observed.

| Other Client                                                                                                                                                                                                              | Application                                                                                                              | Total Deals Affected | Unique CIDs |        Verifier |
| :------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ | :----------------------------------------------------------------------------------------------------------------------- | -------------------: | ----------: | --------------: |
| [f1tivtdkq34mnfzso63wrr2xh6r2zo7aebao4jfla](https://filfox.info/en/address/f1tivtdkq34mnfzso63wrr2xh6r2zo7aebao4jfla)                                                                                                     | `China travel service(HongKong) limited`                                                                                 |           675.56 TiB |       6,151 | LDN v3 multisig |
| [f1ffbtksiso5za73pypuxbxznng6rdv64nbihdtba](https://filfox.info/en/address/f1ffbtksiso5za73pypuxbxznng6rdv64nbihdtba)                                                                                                     | [EpikProtocol](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/281)                              |           638.97 TiB |       4,823 |       LDN # 281 |
| [f1qjrlejxv5a73kxurwtxyrni6ji7orm74zeeetiy](https://filfox.info/en/address/f1qjrlejxv5a73kxurwtxyrni6ji7orm74zeeetiy)                                                                                                     | [Mooc](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/223)                                      |           459.78 TiB |       5,407 | LDN v3 multisig |
| [f1ivsvpljx4ovp2tth73pllkxmumrudemks623iia](https://filfox.info/en/address/f1ivsvpljx4ovp2tth73pllkxmumrudemks623iia)                                                                                                     | `TIS Inc. group`                                                                                                         |           443.08 TiB |       3,451 | LDN v3 multisig |
| [f1u522dt3zabkgbxxzecl77wgv473yvpecxh6t6zq](https://filfox.info/en/address/f1u522dt3zabkgbxxzecl77wgv473yvpecxh6t6zq)                                                                                                     | [Huifan livestream](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/407)                         |           334.47 TiB |       3,661 | LDN v3 multisig |
| [f1727w2vwjctfo7hflr5trgqkl3c7texh7pl4grzq](https://filfox.info/en/address/f1727w2vwjctfo7hflr5trgqkl3c7texh7pl4grzq)                                                                                                     | [GMverse](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/365)                                   |           262.72 TiB |       3,815 | LDN v3 multisig |
| [f1tgii4xgcp6um4n2w7eqaw6bwvnvyii2u7cjgzka](https://filfox.info/en/address/f1tgii4xgcp6um4n2w7eqaw6bwvnvyii2u7cjgzka)                                                                                                     | [Meson\.Network ](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/187)                           |           218.75 TiB |       1,576 | LDN v3 multisig |
| [f1ki4cjk27ypzjsuzkvvqzs6xobaweuoxfdcnpqhy](https://filfox.info/en/address/f1ki4cjk27ypzjsuzkvvqzs6xobaweuoxfdcnpqhy)                                                                                                     | [TimeQuant](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/385)                                 |           210.03 TiB |       2,562 | LDN v3 multisig |
| [f1clwd2dooy2cflfilhzeq2ycl544b3heqsiwhjrq](https://filfox.info/en/address/f1clwd2dooy2cflfilhzeq2ycl544b3heqsiwhjrq)                                                                                                     | [FiboAI](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/349)                                    |           119.78 TiB |       2,338 | LDN v3 multisig |
| [f1dx7ljly4vmk5x2bn5ng4jpbqnuvozrz2phw42qy](https://filfox.info/en/address/f1dx7ljly4vmk5x2bn5ng4jpbqnuvozrz2phw42qy)                                                                                                     | [CoinPhD](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/364)                                   |           115.91 TiB |       1,920 | LDN v3 multisig |
| [f1muygjb5zowppbhr7wnmdreqdoiyyanfm7fe54dy](https://filfox.info/en/address/f1muygjb5zowppbhr7wnmdreqdoiyyanfm7fe54dy)                                                                                                     | [MappingFunk Protocol ](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/374)                     |            89.22 TiB |         862 | LDN v3 multisig |
| [f1f5edx6ofn3lf6rk3yfpldbi2pzgq2egoyu6ubpi](https://filfox.info/en/address/f1f5edx6ofn3lf6rk3yfpldbi2pzgq2egoyu6ubpi)                                                                                                     | [Samdata Trade](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/382)                             |            87.44 TiB |       1,591 | LDN v3 multisig |
| [f1ojo3wo24zkeovndlxfpqmlgzlbysg5fiukmup4a](https://filfox.info/en/address/f1ojo3wo24zkeovndlxfpqmlgzlbysg5fiukmup4a)                                                                                                     | `Titansoft`                                                                                                              |            87.18 TiB |         543 | LDN v3 multisig |
| [f1rnwp6p5kx7pcwexpucoav6mmwz3rkxw5blrboyy](https://filfox.info/en/address/f1rnwp6p5kx7pcwexpucoav6mmwz3rkxw5blrboyy)                                                                                                     | [MigoVideo](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/517)                                 |            69.88 TiB |       1,109 | LDN v3 multisig |
| [f1einobkrjcjk6gfc5ov6663vrri75hwdsjfs6pmq](https://filfox.info/en/address/f1einobkrjcjk6gfc5ov6663vrri75hwdsjfs6pmq)                                                                                                     | [Cansoti](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/640)                                   |            60.31 TiB |       1,081 | LDN v3 multisig |
| [f1hik4fc3wvck2jchtufrnfnzmmskw2nyezlbsr3q](https://filfox.info/en/address/f1hik4fc3wvck2jchtufrnfnzmmskw2nyezlbsr3q)                                                                                                     | [NFTSCAN](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/350)                                   |            51.94 TiB |         752 | LDN v3 multisig |
| [f1fi7vzu266bh7yxsygw6scl2hjltdkhfb6nyzn3a](https://filfox.info/en/address/f1fi7vzu266bh7yxsygw6scl2hjltdkhfb6nyzn3a)                                                                                                     | [Jiliantech](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/190)                                |            44.19 TiB |         920 |       LDN # 190 |
| [f1zb6pgkktdbyy7zxfob6gripqxuc25ukf35cc7fq](https://filfox.info/en/address/f1zb6pgkktdbyy7zxfob6gripqxuc25ukf35cc7fq)                                                                                                     | `Maxpic PhotoGraphic Studio`                                                                                             |            40.16 TiB |         284 | LDN v3 multisig |
| [f1bb2z36lpq3pnwiiowiraagpzqnpow4bonjacx7a](https://filfox.info/en/address/f1bb2z36lpq3pnwiiowiraagpzqnpow4bonjacx7a)                                                                                                     | [Hola Space](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/362)                                |            38.56 TiB |         778 | LDN v3 multisig |
| [f1ajdk7e6ex7fvtjtydzgys47bcg7jub2baucun7y](https://filfox.info/en/address/f1ajdk7e6ex7fvtjtydzgys47bcg7jub2baucun7y)                                                                                                     | [Ruikuyun Information Technology Co\., Ltd](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/529) |            34.91 TiB |         608 | LDN v3 multisig |
| [f1dpgqn57cl5wqijiyv3256nids2ox3fms2mg3oay](https://filfox.info/en/address/f1dpgqn57cl5wqijiyv3256nids2ox3fms2mg3oay)                                                                                                     | [All Blue](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/389)                                  |            31.50 TiB |         256 | LDN v3 multisig |
| [f3q7ablez3jqkcjukwbzaql7lmbx4ldouu66nexpd<br/>cfvu6kgho3v6gricckt77cgr46tdre2l4zmvha7bs<br/>u7qq](https://filfox.info/en/address/f3q7ablez3jqkcjukwbzaql7lmbx4ldouu66nexpdcfvu6kgho3v6gricckt77cgr46tdre2l4zmvha7bsu7qq) | `MatrixStorage`                                                                                                          |            24.97 TiB |         251 |        LDN # 72 |
| [f1ffr7uhq7mszotfdybexcnl4i7xw5tqyp5fhqy3y](https://filfox.info/en/address/f1ffr7uhq7mszotfdybexcnl4i7xw5tqyp5fhqy3y)                                                                                                     | [MyTrade Technology Limited](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/386)                |            19.94 TiB |         293 | LDN v3 multisig |
| [f1dwhevm3p2slu6itmkssznscmpkpltdiztprnpya](https://filfox.info/en/address/f1dwhevm3p2slu6itmkssznscmpkpltdiztprnpya)                                                                                                     | [Hiscene](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/548)                                   |            11.28 TiB |         278 | LDN v3 multisig |
| [f3skkellc7wegakh2blqeu4kkrlzuqy2siymwli7s<br/>ec6eq77c2v4kzgz5ozgnasjl5r52ckameba5kds7h<br/>djda](https://filfox.info/en/address/f3skkellc7wegakh2blqeu4kkrlzuqy2siymwli7sec6eq77c2v4kzgz5ozgnasjl5r52ckameba5kds7hdjda) | [Meizhai Technology](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/75)                         |             6.31 TiB |         119 | LDN v3 multisig |
| [f17qd6x3leh5pa7vh6ewdaed7qhbn2mgofrokuayy](https://filfox.info/en/address/f17qd6x3leh5pa7vh6ewdaed7qhbn2mgofrokuayy)                                                                                                     | [Drust](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/427)                                     |             4.53 TiB |         130 | LDN v3 multisig |
| [f3woqxpu6ekmj43nmpcv7j2pgu6lejxtzgxpzl6f2<br/>vrueoqlzjntakyhdkghymyffbzfbsio6dvfmy643x<br/>4y7q](https://filfox.info/en/address/f3woqxpu6ekmj43nmpcv7j2pgu6lejxtzgxpzl6f2vrueoqlzjntakyhdkghymyffbzfbsio6dvfmy643x4y7q) | [RICH ST PETE LLC](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/64)                           |             1.38 TiB |          34 | LDN v3 multisig |
| [f1yswits4hd4zu6n2pl7nk7cspcuieuzl7btjn5ia](https://filfox.info/en/address/f1yswits4hd4zu6n2pl7nk7cspcuieuzl7btjn5ia)                                                                                                     | [TaoPaiPai](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/54)                                  |           160.00 GiB |           5 |        LDN # 54 |
| [f1ac3mjrhahxbyvxsasp4e7kwa6vyds3ahm27us6a](https://filfox.info/en/address/f1ac3mjrhahxbyvxsasp4e7kwa6vyds3ahm27us6a)                                                                                                     | `Create coach`                                                                                                           |            96.00 GiB |           1 | LDN v3 multisig |
| [f1qdycz5jgdcg4lerfpkujikkwcj7wq7yiqnmubni](https://filfox.info/en/address/f1qdycz5jgdcg4lerfpkujikkwcj7wq7yiqnmubni)                                                                                                     | [National library](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/70)                           |            16.00 GiB |           2 |        LDN # 70 |

[^1]: To manually trigger this report, add a comment with text `checker:manualTrigger`
