### ISSUE TITLE
[DataCap Application]MappingFunk Protocol

### ISSUE THREAD

**Issue by MappingFunkProtocol** [filecoin-project/filecoin-plus-large-datasets#374]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: MappingFunk Protocol 
- Website / Social Media: https://mappingfunk.xyz/#/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 200TiB
- On-chain address for first allocation: f1muygjb5zowppbhr7wnmdreqdoiyyanfm7fe54dy

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
1. MappingFunk is a Decentralised Exchange
2. We build tools helping everyone mint interest-bearing assets on the blockchain.
Hashpower, value-captured tokens, stocks, bonds, and more.
3. We help mining operators cash out without having to sell rigs.
Empowered investors can trade their interest-bearing assets into cryptos.
4. We enable investors to get access to all asset classes with one dApp.
Passively & actively managed, with achievable risk-neutral.
```

What is the primary source of funding for this project?
```
It's from company. 
```

What other projects/ecosystem stakeholders is this project associated with?
```
No one.
```

## Use-case details

Describe the data being stored onto Filecoin
```
Data on chain about BTC and ETH. Data of polygon，BNB，moonbean will need to be stored in the future.
```

Where was the data in this dataset sourced from?
```
BTC and Ethereum, Polygon, BNBSC chain.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
[blocks_20220511.csv](https://github.com/filecoin-project/filecoin-plus-large-data
[height_735987_trasctions.csv](https://github.com/filecoin-project/filecoin-plus-large-datasets/files/8749618/height_735987_trasctions.csv)
sets/files/8749616/blocks_20220511.csv)
[eth_height_14761012_transactions.csv](https://github.com/filecoin-project/filecoin-plus-large-datasets/files/8749619/eth_height_14761012_transactions.csv)
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes. All data is open for public.
```

What is the expected retrieval frequency for this data?
```
Once a year maybe.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
2 years.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
All regions.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Online transfer. Most data is online.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
All SPs on Filecoin can contact me for taking the verfiy deal.
```

How will you be distributing deals across storage providers?
```
On the basis of their willingnes, we distribute the amount of deals.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Ready to begin.
```

**Comment by MappingFunkProtocol** [comment]
@galen-mcandrew It's 10 days since I open this issue.
Please give me some response about my issue!
@dkkapur @Kevin-FF-USA

**Comment by MappingFunkProtocol** [comment]
@galen-mcandrew It's 10 days since I opened this issue.
Please give me some response about my issue!
@dkkapur @Kevin-FF-USA

**Comment by MappingFunkProtocol** [comment]
Waiting

**Comment by Sunnyiscoming** [comment]
@MappingFunkProtocol 

> Describe the data being stored onto Filecoin
> 
> Data on chain about BTC and ETH. Data of polygon，BNB，moonbean will need to be stored in the future.
> Where was the data in this dataset sourced from?
> 
> BTC and Ethereum, Polygon, BNBSC chain.

Do you want to store data by climbing the chain data?

**Comment by MappingFunkProtocol** [comment]
@Sunnyiscoming Yes, we have obtained the data on these chains for our system analysis. That's why we need backup in Filecoin.

**Comment by Yvette516** [comment]
Could you send an email to filplus@fil.org from your official email account?

**Comment by MappingFunkProtocol** [comment]
@Yvette516 OK. I've done it.

**Comment by MappingFunkProtocol** [comment]
![9mapping](https://user-images.githubusercontent.com/105412166/175490406-4c0adf8d-18c1-4712-a16e-74d496b76031.png)
@galen-mcandrew @dkkapur This is my email.

**Comment by galen-mcandrew** [comment]
## Datacap Request Trigger
#### Total DataCap requested 
> 5PiB
#### Expected weekly DataCap usage rate 
> 200TiB 
#### Client address
> f1muygjb5zowppbhr7wnmdreqdoiyyanfm7fe54dy

**Comment by PluskitOfficial** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedfrrbzdv5zuw2xzk4x3bao7uhkzrmdsacpkybp7e4z4vps5ez34o 
#### Address 
> f1muygjb5zowppbhr7wnmdreqdoiyyanfm7fe54dy
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1tgnlhtcmhwipfm7thsftxhn5k52velyjlazpvka
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedfrrbzdv5zuw2xzk4x3bao7uhkzrmdsacpkybp7e4z4vps5ez34o

**Comment by kevzak** [comment]
Hello @MappingFunkProtocol - I'm Kevin from the Client Success Team. I saw you were recently granted DataCap and began onboarding data. I wanted to reach out as you getting started to offer any support as needed. Let me know if you have any questions or issues.

Also, feel free to post a message in #fil-plus slack channel. Thank you!

**Comment by MRJAVAZHAO** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebbuamuuzio7phedc7yabklkpx5grr5faavop6nf44vwwljzzkxkq 
#### Address 
> f1muygjb5zowppbhr7wnmdreqdoiyyanfm7fe54dy
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f14gme3f52prtyzk6pblogrdd6b6ivp4swc6qmesi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebbuamuuzio7phedc7yabklkpx5grr5faavop6nf44vwwljzzkxkq

**Comment by MatrixStorage** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedhqckuelvvt5oza7u5gfqyg3p2lhfqxkb4ddxdkqgrrkil7bifi6 
#### Address 
> f1muygjb5zowppbhr7wnmdreqdoiyyanfm7fe54dy
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1tbxqwjxfyv7swsdin4einirlsfquv3vnmlapley
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedhqckuelvvt5oza7u5gfqyg3p2lhfqxkb4ddxdkqgrrkil7bifi6

**Comment by PluskitOfficial** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebujt4euspv6mn3wck3zkdytxtqpwgfomyxmyecy2mg4ibaxpekcy 
#### Address 
> f1muygjb5zowppbhr7wnmdreqdoiyyanfm7fe54dy
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1tgnlhtcmhwipfm7thsftxhn5k52velyjlazpvka
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebujt4euspv6mn3wck3zkdytxtqpwgfomyxmyecy2mg4ibaxpekcy

**Comment by MRJAVAZHAO** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecr53ckzmjmcz4fiwd6iwkup4qmn6kgeyjsiinjlh6ixp4raxtwcg 
#### Address 
> f1muygjb5zowppbhr7wnmdreqdoiyyanfm7fe54dy
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f14gme3f52prtyzk6pblogrdd6b6ivp4swc6qmesi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecr53ckzmjmcz4fiwd6iwkup4qmn6kgeyjsiinjlh6ixp4raxtwcg

**Comment by BlockMakeronline** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb637hz5r4hjc2bfb3ytdr5xojqi5uwjmnzwplj5h42hsdhhqgirg 
#### Address 
> f1muygjb5zowppbhr7wnmdreqdoiyyanfm7fe54dy
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1o3twrcpwjtpcd4q36lpq4qmy2qfbgtyy5h6tsty
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb637hz5r4hjc2bfb3ytdr5xojqi5uwjmnzwplj5h42hsdhhqgirg

**Comment by BigD-Exchange** [comment]
@MappingFunkProtocol Hi! Great to see you have gotten approval for DataCap. If you are looking for storage providers to store these data, please visit #bigdata-exchange on Filecoin Slack or reply here.

**Comment by MRJAVAZHAO** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecmjiggrcpoeq552yxj3ax5ecynhrm3bwqqgkh5zzxwxhubbvnbkg 
#### Address 
> f1muygjb5zowppbhr7wnmdreqdoiyyanfm7fe54dy
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f14gme3f52prtyzk6pblogrdd6b6ivp4swc6qmesi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecmjiggrcpoeq552yxj3ax5ecynhrm3bwqqgkh5zzxwxhubbvnbkg

**Comment by MatrixStorage** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedpxho5szqd32nb6krgjrhmsypkjyltt4bmbdjcfbrmxmbcvlvt5o 
#### Address 
> f1muygjb5zowppbhr7wnmdreqdoiyyanfm7fe54dy
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1tbxqwjxfyv7swsdin4einirlsfquv3vnmlapley
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedpxho5szqd32nb6krgjrhmsypkjyltt4bmbdjcfbrmxmbcvlvt5o

**Comment by 1475Notary** [comment]
bot error, proposed manually.
bafy2bzacebtyppoqktkwlnz43wyc77vsljemsqgg4t3j2q2n7itmqenkmxiqm

**Comment by psh0691** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecosb4hzqyuwxw53oggakuskraogz2aa7vylfs7jixyxdynbnsw5w 
#### Address 
> f1muygjb5zowppbhr7wnmdreqdoiyyanfm7fe54dy
#### Datacap Allocated
> 1.56PiB
#### Signer Address
> f1qdko4jg25vo35qmyvcrw4ak4fmuu3f5rif2kc7i
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecosb4hzqyuwxw53oggakuskraogz2aa7vylfs7jixyxdynbnsw5w

**Comment by filplus-checker** [comment]
## DataCap and CID Checker Report[^1]
 - Organization: `MappingFunk Protocol `
 - Client: `f1muygjb5zowppbhr7wnmdreqdoiyyanfm7fe54dy`
### Storage Provider Distribution
The below table shows the distribution of storage providers that have stored data for this client.

If this is the first time a provider takes verified deal, it will be marked as `new`.

For most of the datacap application, below restrictions should apply.
 - Storage provider should not exceed 25% of total datacap.
 - Storage provider should not be storing duplicate data for more than 20%.
 - Storage provider should have published its public IP address.
 - All storage providers should be located in different regions.

⚠️ 76.91% of total deal sealed by [f01788231](https://filfox.info/en/address/f01788231) are duplicate data.

⚠️ 77.40% of total deal sealed by [f01807908](https://filfox.info/en/address/f01807908) are duplicate data.

⚠️ 76.70% of total deal sealed by [f01844999](https://filfox.info/en/address/f01844999) are duplicate data.

⚠️ [f01844999](https://filfox.info/en/address/f01844999) has unknown IP location.

⚠️ 71.19% of total deal sealed by [f01832632](https://filfox.info/en/address/f01832632) are duplicate data.

⚠️ 34.58% of total deal sealed by [f01896513](https://filfox.info/en/address/f01896513) are duplicate data.

⚠️ 32.15% of total deal sealed by [f01895928](https://filfox.info/en/address/f01895928) are duplicate data.

⚠️ 25.42% of total deal sealed by [f01895990](https://filfox.info/en/address/f01895990) are duplicate data.

⚠️ 72.57% of total deal sealed by [f01880897](https://filfox.info/en/address/f01880897) are duplicate data.

⚠️ 89.89% of total deal sealed by [f01885260](https://filfox.info/en/address/f01885260) are duplicate data.

⚠️ 66.94% of total deal sealed by [f01880898](https://filfox.info/en/address/f01880898) are duplicate data.

⚠️ 74.96% of total deal sealed by [f01845679](https://filfox.info/en/address/f01845679) are duplicate data.

⚠️ [f01845679](https://filfox.info/en/address/f01845679) has unknown IP location.

⚠️ 70.86% of total deal sealed by [f01880896](https://filfox.info/en/address/f01880896) are duplicate data.

⚠️ 79.55% of total deal sealed by [f01880894](https://filfox.info/en/address/f01880894) are duplicate data.

⚠️ 74.64% of total deal sealed by [f01879880](https://filfox.info/en/address/f01879880) are duplicate data.

⚠️ 68.18% of total deal sealed by [f01885280](https://filfox.info/en/address/f01885280) are duplicate data.

| Provider                                              |                           Location | Total Deals Sealed | Percentage | Unique Data | Duplicate Deals |
| :---------------------------------------------------- | ---------------------------------: | -----------------: | ---------: | ----------: | --------------: |
| [f01788231](https://filfox.info/en/address/f01788231) |           San Jose, California, US |         341.63 TiB |     16.75% |   78.88 TiB |          76.91% |
| [f01807908](https://filfox.info/en/address/f01807908) |           San Jose, California, US |         324.38 TiB |     15.90% |   73.31 TiB |          77.40% |
| [f01844999](https://filfox.info/en/address/f01844999) |                            Unknown |         289.06 TiB |     14.17% |   67.34 TiB |          76.70% |
| [f01832632](https://filfox.info/en/address/f01832632) |           San Jose, California, US |         185.19 TiB |      9.08% |   53.34 TiB |          71.19% |
| [f01896513](https://filfox.info/en/address/f01896513) |           Singapore, Singapore, SG |         135.00 TiB |      6.62% |   88.31 TiB |          34.58% |
| [f01895928](https://filfox.info/en/address/f01895928) |           Singapore, Singapore, SG |         134.81 TiB |      6.61% |   91.47 TiB |          32.15% |
| [f01895990](https://filfox.info/en/address/f01895990) |           Singapore, Singapore, SG |         134.75 TiB |      6.61% |  100.50 TiB |          25.42% |
| [f01880897](https://filfox.info/en/address/f01880897) |           Singapore, Singapore, SG |          95.03 TiB |      4.66% |   26.06 TiB |          72.57% |
| [f01885260](https://filfox.info/en/address/f01885260) | Hong Kong, Central and Western, HK |          91.16 TiB |      4.47% |    9.22 TiB |          89.89% |
| [f01880898](https://filfox.info/en/address/f01880898) |           Singapore, Singapore, SG |          50.00 TiB |      2.45% |   16.53 TiB |          66.94% |
| [f01845679](https://filfox.info/en/address/f01845679) |                            Unknown |          40.06 TiB |      1.96% |   10.03 TiB |          74.96% |
| [f01889480](https://filfox.info/en/address/f01889480) |               Boardman, Oregon, US |          40.00 TiB |      1.96% |   40.00 TiB |           0.00% |
| [f01889046](https://filfox.info/en/address/f01889046) |              Ashburn, Virginia, US |          40.00 TiB |      1.96% |   40.00 TiB |           0.00% |
| [f01880896](https://filfox.info/en/address/f01880896) |           Singapore, Singapore, SG |          39.03 TiB |      1.91% |   11.38 TiB |          70.86% |
| [f01880894](https://filfox.info/en/address/f01880894) |           Singapore, Singapore, SG |          38.97 TiB |      1.91% |    7.97 TiB |          79.55% |
| [f01879880](https://filfox.info/en/address/f01879880) |           Singapore, Singapore, SG |          38.94 TiB |      1.91% |    9.88 TiB |          74.64% |
| [f01885280](https://filfox.info/en/address/f01885280) | Hong Kong, Central and Western, HK |          22.00 TiB |      1.08% |    7.00 TiB |          68.18% |

![Provider Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/374/1671096307752.png)
### Deal Data Replication
The below table shows how each many unique data are replicated across storage providers.
- No more than 25% of unique data are stored with less than 4 providers.

⚠️ 96.87% of deals are for data replicated across less than 4 storage providers.

| Unique Data Size | Total Deals Made | Number of Providers | Deal Percentage |
| ---------------: | ---------------: | ------------------: | --------------: |
|       256.31 TiB |       685.94 TiB |                   1 |          33.62% |
|       117.28 TiB |       773.50 TiB |                   2 |          37.92% |
|        71.53 TiB |       516.63 TiB |                   3 |          25.32% |
|         6.44 TiB |        63.94 TiB |                   4 |           3.13% |

![Replication Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/374/1671096308480.png)
### Deal Data Shared with other Clients
The below table shows how many unique data are shared with other clients.
Usually different applications owns different data and should not resolve to the same CID.

⚠️ CID sharing has been observed.

| Other Client                                                                                                                                                                                                              | Application                                                                                                     | Total Deals Affected | Unique CIDs |        Verifier |
| :------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ | :-------------------------------------------------------------------------------------------------------------- | -------------------: | ----------: | --------------: |
| [f1u522dt3zabkgbxxzecl77wgv473yvpecxh6t6zq](https://filfox.info/en/address/f1u522dt3zabkgbxxzecl77wgv473yvpecxh6t6zq)                                                                                                     | [Huifan livestream](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/407)                |           295.41 TiB |       3,053 | LDN v3 multisig |
| [f1dx7ljly4vmk5x2bn5ng4jpbqnuvozrz2phw42qy](https://filfox.info/en/address/f1dx7ljly4vmk5x2bn5ng4jpbqnuvozrz2phw42qy)                                                                                                     | [CoinPhD](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/364)                          |           270.66 TiB |       3,601 | LDN v3 multisig |
| [f1zb6pgkktdbyy7zxfob6gripqxuc25ukf35cc7fq](https://filfox.info/en/address/f1zb6pgkktdbyy7zxfob6gripqxuc25ukf35cc7fq)                                                                                                     | `Maxpic PhotoGraphic Studio`                                                                                    |           182.56 TiB |       2,427 | LDN v3 multisig |
| [f14abwn2goturifmt27s2bssoe3fup2b3npkgfzui](https://filfox.info/en/address/f14abwn2goturifmt27s2bssoe3fup2b3npkgfzui)                                                                                                     | [KONGFU VR](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/372)                        |           116.44 TiB |         862 | LDN v3 multisig |
| [f1tgii4xgcp6um4n2w7eqaw6bwvnvyii2u7cjgzka](https://filfox.info/en/address/f1tgii4xgcp6um4n2w7eqaw6bwvnvyii2u7cjgzka)                                                                                                     | [Meson\.Network ](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/187)                  |           107.94 TiB |         733 | LDN v3 multisig |
| [f1bb2z36lpq3pnwiiowiraagpzqnpow4bonjacx7a](https://filfox.info/en/address/f1bb2z36lpq3pnwiiowiraagpzqnpow4bonjacx7a)                                                                                                     | [Hola Space](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/362)                       |            98.06 TiB |       1,699 | LDN v3 multisig |
| [f1hik4fc3wvck2jchtufrnfnzmmskw2nyezlbsr3q](https://filfox.info/en/address/f1hik4fc3wvck2jchtufrnfnzmmskw2nyezlbsr3q)                                                                                                     | [NFTSCAN](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/350)                          |            80.53 TiB |         490 | LDN v3 multisig |
| [f1ki4cjk27ypzjsuzkvvqzs6xobaweuoxfdcnpqhy](https://filfox.info/en/address/f1ki4cjk27ypzjsuzkvvqzs6xobaweuoxfdcnpqhy)                                                                                                     | [TimeQuant](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/385)                        |            79.66 TiB |       1,044 | LDN v3 multisig |
| [f1f5edx6ofn3lf6rk3yfpldbi2pzgq2egoyu6ubpi](https://filfox.info/en/address/f1f5edx6ofn3lf6rk3yfpldbi2pzgq2egoyu6ubpi)                                                                                                     | [Samdata Trade](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/382)                    |            57.69 TiB |         857 | LDN v3 multisig |
| [f1dpgqn57cl5wqijiyv3256nids2ox3fms2mg3oay](https://filfox.info/en/address/f1dpgqn57cl5wqijiyv3256nids2ox3fms2mg3oay)                                                                                                     | [All Blue](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/389)                         |            34.78 TiB |         494 | LDN v3 multisig |
| [f1ffr7uhq7mszotfdybexcnl4i7xw5tqyp5fhqy3y](https://filfox.info/en/address/f1ffr7uhq7mszotfdybexcnl4i7xw5tqyp5fhqy3y)                                                                                                     | [MyTrade Technology Limited](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/386)       |            33.03 TiB |         495 | LDN v3 multisig |
| [f1clwd2dooy2cflfilhzeq2ycl544b3heqsiwhjrq](https://filfox.info/en/address/f1clwd2dooy2cflfilhzeq2ycl544b3heqsiwhjrq)                                                                                                     | [FiboAI](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/349)                           |            31.78 TiB |         484 | LDN v3 multisig |
| [f1gs5xe26fkplu64mwcfq5fswycp3qucuvzbg2lia](https://filfox.info/en/address/f1gs5xe26fkplu64mwcfq5fswycp3qucuvzbg2lia)                                                                                                     | [Migu Culture Technology Co\., Ltd](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/63) |            26.88 TiB |         210 |        LDN # 63 |
| [f1727w2vwjctfo7hflr5trgqkl3c7texh7pl4grzq](https://filfox.info/en/address/f1727w2vwjctfo7hflr5trgqkl3c7texh7pl4grzq)                                                                                                     | [GMverse](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/365)                          |            13.38 TiB |         308 | LDN v3 multisig |
| [f3skkellc7wegakh2blqeu4kkrlzuqy2siymwli7s<br/>ec6eq77c2v4kzgz5ozgnasjl5r52ckameba5kds7h<br/>djda](https://filfox.info/en/address/f3skkellc7wegakh2blqeu4kkrlzuqy2siymwli7sec6eq77c2v4kzgz5ozgnasjl5r52ckameba5kds7hdjda) | [Meizhai Technology](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/75)                |            13.22 TiB |         184 | LDN v3 multisig |
| [f3q7ablez3jqkcjukwbzaql7lmbx4ldouu66nexpd<br/>cfvu6kgho3v6gricckt77cgr46tdre2l4zmvha7bs<br/>u7qq](https://filfox.info/en/address/f3q7ablez3jqkcjukwbzaql7lmbx4ldouu66nexpdcfvu6kgho3v6gricckt77cgr46tdre2l4zmvha7bsu7qq) | `MatrixStorage`                                                                                                 |             6.13 TiB |         106 |        LDN # 72 |
| [f1ivsvpljx4ovp2tth73pllkxmumrudemks623iia](https://filfox.info/en/address/f1ivsvpljx4ovp2tth73pllkxmumrudemks623iia)                                                                                                     | `TIS Inc. group`                                                                                                |             1.69 TiB |          27 | LDN v3 multisig |
| [f1ojo3wo24zkeovndlxfpqmlgzlbysg5fiukmup4a](https://filfox.info/en/address/f1ojo3wo24zkeovndlxfpqmlgzlbysg5fiukmup4a)                                                                                                     | `Titansoft`                                                                                                     |           320.00 GiB |           1 | LDN v3 multisig |
| [f3woqxpu6ekmj43nmpcv7j2pgu6lejxtzgxpzl6f2<br/>vrueoqlzjntakyhdkghymyffbzfbsio6dvfmy643x<br/>4y7q](https://filfox.info/en/address/f3woqxpu6ekmj43nmpcv7j2pgu6lejxtzgxpzl6f2vrueoqlzjntakyhdkghymyffbzfbsio6dvfmy643x4y7q) | [RICH ST PETE LLC](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/64)                  |           320.00 GiB |           1 | LDN v3 multisig |
| [f1yswits4hd4zu6n2pl7nk7cspcuieuzl7btjn5ia](https://filfox.info/en/address/f1yswits4hd4zu6n2pl7nk7cspcuieuzl7btjn5ia)                                                                                                     | [TaoPaiPai](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/54)                         |           160.00 GiB |           5 |        LDN # 54 |
| [f1qjrlejxv5a73kxurwtxyrni6ji7orm74zeeetiy](https://filfox.info/en/address/f1qjrlejxv5a73kxurwtxyrni6ji7orm74zeeetiy)                                                                                                     | [Mooc](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/223)                             |            32.00 GiB |           1 | LDN v3 multisig |

[^1]: To manually trigger this report, add a comment with text `checker:manualTrigger`

**Comment by Sunnyiscoming** [comment]
Hello, @MappingFunkProtocol per the https://github.com/filecoin-project/notary-governance/issues/922 for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

This information will be reviewed by Fil+ Governance team to confirm validity and then the application will be allowed to move forward for additional notary review.
