### ISSUE TITLE
[DataCap Application]AOLIGEI

### ISSUE THREAD

**Issue by aoligei-01** [filecoin-project/filecoin-plus-large-datasets#377]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: AOLIGEI
- Website / Social Media:  www.aoligei-fighting.com
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):5 PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):100TiB
- On-chain address for first allocation: f1unz5yuxgui573lpuh2wyxpsx5ahvw5farqb7hji

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
AOLIGEI Media Co., Ltd is a media platform focused on the development of artists. With accurate market positioning, we’ve won a certain market share out of many competitors. Engaged in the filed of the image promotion of internet influencers, short video planning, filming training consulting, etc. We are not only have a large number of media resources, but also create their own flow of IP with the professional operation teams, helping them achieve their own dreams!
```

What is the primary source of funding for this project?
```
Income from influencers and e-commerce products revenue
```

What other projects/ecosystem stakeholders is this project associated with?
```
Our company currently has more than 100 influencers under contract, and our current business has close ties with film and television companies, social media platforms, and e-commerce.
1、Cooperating with film and TV companies to shoot TV series and advertisement promotion works.
2、Cooperating with other media platforms to publish videos, pictures and advertisements of our contracted artists.
3、We also do e-commerce by selling a full range of products through live-stream media.
```

## Use-case details

Describe the data being stored onto Filecoin
```
The data stored on Filecoin are our business videos, commercials, image and client’s video materials. 
```

Where was the data in this dataset sourced from?
```
From our own production
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
Douying：
https://www.douyin.com/user/MS4wLjABAAAAAD-lSehi3CNwG1I8bTSfQUZ-Ak2j9Rxdulx6TZNFsAc
https://www.douyin.com/user/MS4wLjABAAAAkp1fflZfY49fdNe0G35qHPFMiIQllV9hQPzhSMQXbvk
https://www.douyin.com/user/MS4wLjABAAAAqHIH7OBGnA77xHvRJNYaNXRS5MAm-2lDxNIk3dJSHtU
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Confirm that the data we will store is publicly available
```

What is the expected retrieval frequency for this data?
```
Just few times for check.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
The data we store on filecoin is subject to the demand and business needs. It is expected that 20% of the data will be stored for 540 days and 80% of the data will be stored permanently.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Singapore、America
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Both online and offline transfer.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We choose those with real data storage experience and stable operation storage providers from the github repo.
```

How will you be distributing deals across storage providers?
```
Each storage provider will receive 15% of our dataCap, and max 2 copies per SP.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes. We are ready to make deals. 
```

**Comment by EGGRICE02** [comment]
Can you post a video or photo on the Douyin account you've mentioned above in data sample to verify you're making videos for it?

**Comment by Sunnyiscoming** [comment]
I have sent a message to  the above three exposed Douyin accounts by using the personal Douyin id to prove whether there is any business association with 浙 江 奥 利 给 文 化 传 媒 有 限 公 司.
Douyin id： hanhanmami8310
Please check it.

**Comment by aoligei-01** [comment]
@Sunnyiscoming Hello, our artist has sent a confirmation message to Douyin id: hanhanmami8310, please check.
Artist Douyin id: dandanjieshuo; DY533813
Our artists have hidden works because of their personal preferences, so you can't see all the works
![WechatIMG5281](https://user-images.githubusercontent.com/105850093/174956235-1c3e52fc-81ca-42a5-899d-675a18ae1b76.jpeg)
![WechatIMG5282](https://user-images.githubusercontent.com/105850093/174956256-594ab9f3-be4e-4177-82df-f18c7dd
![WechatIMG5283](https://user-images.githubusercontent.com/105850093/174956276-ca3fea0b-01a1-4d05-aded-0855df754a59.jpeg)
1e0a5.jpeg)
![WechatIMG5284](https://user-images.githubusercontent.com/105850093/174956303-f837b0fc-4819-4c7f-bc01-970881f79e36.jpeg)

We confirm that the data we store on Filecoin is publicly available，Thank you！

**Comment by aoligei-01** [comment]
@Sunnyiscoming This influencer is only cooperating with us in the online sales business. The data we want to store on the Filecoin network is just related to our business. NOT ALL OF the Influencer's VIDEO. 
BTW, it seems like you are also Chinese. You might know the meaning of "influencer" and how influencer works. What's the meaning of operation for those influencers' accounts.
Also, It might be offensive to do this as a governance team assistant.

**Comment by Sunnyiscoming** [comment]
@aoligei-01 This is client due diligence, and hope you can understand it. If you are just a influencer, can you provide data storage authorization of this douyin channel?

**Comment by aoligei-01** [comment]
@Sunnyiscoming Sorry, you may have misunderstood me. We are a media company, we have signed some artists and there will be a lot of video material that needs to be stored for backup. Secondly, we have business cooperation with external KOLs and there will be many business opportunities, so the video data used for online sales also need to be stored.Thank you！

**Comment by aoligei-01** [comment]
Hello, @Sunnyiscoming  we have sent an identity confirmation email to filplus@fil.org, please check. thank you!

**Comment by galen-mcandrew** [comment]
## Datacap Request Trigger
#### Total DataCap requested 
> 5PiB
#### Expected weekly DataCap usage rate 
> 100TiB 
#### Client address
> f1unz5yuxgui573lpuh2wyxpsx5ahvw5farqb7hji

**Comment by 1LISA2** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedlvdh6n2hm7wjotmlie4nckpdfsd5jjg5nilr3ev5qdqvvayc2ra 
#### Address 
> f1unz5yuxgui573lpuh2wyxpsx5ahvw5farqb7hji
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1jvvltduw35u6inn5tr4nfualyd42bh3vjtylgci
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedlvdh6n2hm7wjotmlie4nckpdfsd5jjg5nilr3ev5qdqvvayc2ra

**Comment by psh0691** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedb7p7jythcmp4naa6scygmspl5rsey7qlpbjbh7rcjj7g4orv5cq 
#### Address 
> f1unz5yuxgui573lpuh2wyxpsx5ahvw5farqb7hji
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1qdko4jg25vo35qmyvcrw4ak4fmuu3f5rif2kc7i
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedb7p7jythcmp4naa6scygmspl5rsey7qlpbjbh7rcjj7g4orv5cq

**Comment by BigD-Exchange** [comment]
@aoligei-01 Hi! Great to see you have gotten approval for DataCap. If you are looking for storage providers to store these data, please visit #bigdata-exchange on Filecoin Slack or reply here.
