### ISSUE TITLE
[DataCap Application] Slingshot2.8 Open Images Dataset - NewToke

### ISSUE THREAD

**Issue by jomozz** [filecoin-project/filecoin-plus-large-datasets#378]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name:  NewToke
- Website / Social Media:  http://www.ntkblock.com  /   @slack: jomozz
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 500TiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100TiB
- On-chain address for first allocation:  f1huke6ntamxqsz2dwpvfkvx7ng3hzyk4whzhgrkq

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
The requested DataCap is for Slingshot 2.8 hosted by the Slingshot teams.
Our company is a technology company, founded in 2019, focusing on IPFS and web3.0 technology. 
We are very interested in the filecoin ecosystem, this is our first time participating in slingshot. 
This time is to prepare for the deep participation in the next competition, and we will do our best to complete all the tasks.
```

What is the primary source of funding for this project?
```
Mainly funds of our company, and wish we can win some rewards to cover these expenses.
```

What other projects/ecosystem stakeholders is this project associated with?
```
Slingshot team
```

## Use-case details

Describe the data being stored onto Filecoin
```
Open Images is a dataset of ~9 million URLs to images that have been annotated with labels spanning over 6000 categories. 
These annotation files cover the 600 boxable object classes, and span the 1,743,042 training images where we annotated bounding boxes, object segmentations, visual relationships, and localized narratives; as well as the full validation (41,620 images) and test (125,436 images) sets.
```

Where was the data in this dataset sourced from?
```
https://storage.googleapis.com/openimages/web/index.html
https://github.com/cvdfoundation/open-images-dataset
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://storage.googleapis.com/cvdf-datasets/oid/open-images-dataset-train0.tsv
https://storage.googleapis.com/cvdf-datasets/oid/open-images-dataset-train1.tsv
https://farm6.staticflickr.com/8679/16677454546_5ca014effb_o.jpg
https://c8.staticflickr.com/7/6140/5981339808_dfdeaf5ee1_o.jpg
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes
```

What is the expected retrieval frequency for this data?
```
Once a month
```

For how long do you plan to keep this dataset stored on Filecoin?
```
At least one year
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Mainly in China, all around the world if possible
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
1. I will create the car files through the open source software go-graphsplit
2. Upload my prepared CAR files to a web server for SPs to download, or ship the disks to SPs for downloading.
3. Send offline deal to SPs
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
Look for SPs on slack and community, make sure they are different entities.
And who could prove that they have ability to make data safe and can finish the sealing tasks.
```

How will you be distributing deals across storage providers?
```
No single SPs can make deals more than 25%.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes we have, we are ready to send the deals.
```

**Comment by EGGRICE02** [comment]
On your website http://www.ntkblock.com/, the company seems to be NEWTOKEN, however, on the application form it says NewToke. Which one is correct?
If you are NEWTOKEN, are there any commercial relationships between you and China Plant Research Base, issue #309? In #309, the linked website has a WeChat QR Code redirecting to NewToke, which I believe is NewToken.

**Comment by jomozz** [comment]
@EGGRICE02 Yeah, these two are both us. We are a technology company, plant is one of our customers, they need technical support to apply for datacap. If the datacap application is approved, we will help them contact the sps and send the deals.

**Comment by jomozz** [comment]
@galen-mcandrew @dkkapur  hi galen, What else do I need to provide?  Can you help us move forward with the application? thank you very much！

**Comment by jomozz** [comment]
@galen-mcandrew We've already discussed my application on slack: https://filecoinproject.slack.com/archives/C01AK1J7TF1/p1654799395246099

**Comment by Sunnyiscoming** [comment]
@jomozz  Hey. Could you send an email to filplus@fil.org with your official domain in order to confirm your identity?

**Comment by jomozz** [comment]
> @jomozz Hey. Could you send an email to [filplus@fil.org](mailto:filplus@fil.org) with your official domain in order to confirm your identity?

OK,  We have sent it.

**Comment by jomozz** [comment]
> @jomozz Hey. Could you send an email to [filplus@fil.org](mailto:filplus@fil.org) with your official domain in order to confirm your identity?

@Sunnyiscoming @galen-mcandrew OK, We have sent it.

**Comment by jomozz** [comment]
@galen-mcandrew @dkkapur Any update?

**Comment by dkkapur** [comment]
![image](https://user-images.githubusercontent.com/2343218/177511223-0f4d5b16-7327-487b-97ca-80aa7e9d8507.png)

I see this from an official @ntkblock.com email.

**Comment by kernelogic** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb4lshgdpopn62fhuyehxbx44bjjtcsquisd3am6clc3p636fnymm 
#### Address 
> f1huke6ntamxqsz2dwpvfkvx7ng3hzyk4whzhgrkq
#### Datacap Allocated
> 25.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb4lshgdpopn62fhuyehxbx44bjjtcsquisd3am6clc3p636fnymm

**Comment by xingjitansuo** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecfqql2w5hr2ghfz2g7csjx5y45o5afre57k7vqnndv5i3h4ofgug 
#### Address 
> f1huke6ntamxqsz2dwpvfkvx7ng3hzyk4whzhgrkq
#### Datacap Allocated
> 25.00TiB
#### Signer Address
> f1a2lia2cwwekeubwo4nppt4v4vebxs2frozarz3q
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecfqql2w5hr2ghfz2g7csjx5y45o5afre57k7vqnndv5i3h4ofgug

**Comment by galen-mcandrew** [comment]
Adjusted comment from PiB to TiB

**Comment by kevzak** [comment]
Hello @jomozz - I'm Kevin from the Client Success Team. I saw you were recently granted DataCap and began onboarding data. I wanted to reach out as you getting started to offer any support as needed. Let me know if you have any questions or issues.

Also, feel free to post a message in #fil-plus slack channel. Thank you!

**Comment by kernelogic** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceadtyzq4e2yl3n5522u2rr5eai7qyypvimr2vylnyemsk63k2rmds 
#### Address 
> f1huke6ntamxqsz2dwpvfkvx7ng3hzyk4whzhgrkq
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceadtyzq4e2yl3n5522u2rr5eai7qyypvimr2vylnyemsk63k2rmds

**Comment by jamerduhgamer** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb4wjgrfxz7hb2auqzje7pfycpcnb7dmf5yrf6mip5zkpfpom3ejc 
#### Address 
> f1huke6ntamxqsz2dwpvfkvx7ng3hzyk4whzhgrkq
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1ypuqpi4xn5q7zi5at3rmdltosozifhqmrt66vhq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb4wjgrfxz7hb2auqzje7pfycpcnb7dmf5yrf6mip5zkpfpom3ejc

**Comment by BigD-Exchange** [comment]
@jomozz Hi! Great to see you have gotten approval for DataCap. If you are looking for storage providers to store these data, please visit #bigdata-exchange on Filecoin Slack or reply here.

**Comment by jomozz** [comment]
Hi @kevzak - Thanks for your concern, everything is ok now.

**Comment by jomozz** [comment]
@BigD-Exchange Ok maybe i will try it!

**Comment by kernelogic** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebplidqia67ay4ypabvrghr3lyc5lfvfosbagrscv2nqlac7icobw 
#### Address 
> f1huke6ntamxqsz2dwpvfkvx7ng3hzyk4whzhgrkq
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebplidqia67ay4ypabvrghr3lyc5lfvfosbagrscv2nqlac7icobw

**Comment by jamerduhgamer** [comment]
Hi @kernelogic, just a heads up that you approved the last tranche of datacap as well. Is it a requirement for public datasets that the notaries for each other tranche is different? I know this requirement is true for private datasets.

**Comment by kernelogic** [comment]
I have no idea. I think it's better to be different.

**Comment by jamerduhgamer** [comment]
I think each set of two should be different but for this dataset, it should be okay. I will hold off on approving the next tranche then.

**Comment by liyunzhi-666** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebccrzo45ipewoz74zdmhimmqd3elxaucg5ydpbqxsilbbz2fwhx2 
#### Address 
> f1huke6ntamxqsz2dwpvfkvx7ng3hzyk4whzhgrkq
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1pszcrsciyixyuxxukkvtazcokexbn54amf7gvoq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebccrzo45ipewoz74zdmhimmqd3elxaucg5ydpbqxsilbbz2fwhx2

**Comment by kernelogic** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebrxpw3mi4rbogqldgzwemt7ks5uxfxcgqbeosybzwniup4ebmz7s 
#### Address 
> f1huke6ntamxqsz2dwpvfkvx7ng3hzyk4whzhgrkq
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebrxpw3mi4rbogqldgzwemt7ks5uxfxcgqbeosybzwniup4ebmz7s

**Comment by jamerduhgamer** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceat4e22qi7utl7z46qrwavty2ozocd5y6nvbwsm7yahcq7i73jlo6 
#### Address 
> f1huke6ntamxqsz2dwpvfkvx7ng3hzyk4whzhgrkq
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1ypuqpi4xn5q7zi5at3rmdltosozifhqmrt66vhq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceat4e22qi7utl7z46qrwavty2ozocd5y6nvbwsm7yahcq7i73jlo6

**Comment by jamerduhgamer** [comment]
Looks like there was an issue with the 100 TiB allocation but the 200 TiB was successful.

lotus filplus check-client-datacap f1huke6ntamxqsz2dwpvfkvx7ng3hzyk4whzhgrkq
226877352443904

We should check if the "Total DataCap granted for client so far" stat is properly updated next time the bot fires off.

**Comment by filplus-checker** [comment]
## DataCap and CID Checker Report[^1]
 - Organization: ` NewToke`
 - Client: `f1huke6ntamxqsz2dwpvfkvx7ng3hzyk4whzhgrkq`
### Storage Provider Distribution
The below table shows the distribution of storage providers that have stored data for this client.

If this is the first time a provider takes verified deal, it will be marked as `new`.

For most of the datacap application, below restrictions should apply.
 - Storage provider should not exceed 25% of total datacap.
 - Storage provider should not be storing duplicate data for more than 20%.
 - Storage provider should have published its public IP address.
 - All storage providers should be located in different regions.

✔️ Storage provider distribution looks healthy.

| Provider                                                  |                    Location | Total Deals Sealed | Percentage | Unique Data | Duplicate Deals |
| :-------------------------------------------------------- | --------------------------: | -----------------: | ---------: | ----------: | --------------: |
| [f02301](https://filfox.info/en/address/f02301)           |    San Jose, California, US |          11.06 TiB |     16.13% |   11.06 TiB |           0.00% |
| [f0142637](https://filfox.info/en/address/f0142637)       |        Chengdu, Sichuan, CN |          10.00 TiB |     14.59% |   10.00 TiB |           0.00% |
| [f0240185](https://filfox.info/en/address/f0240185)       |     Clifton, New Jersey, US |           9.66 TiB |     14.08% |    9.66 TiB |           0.00% |
| [f0143858](https://filfox.info/en/address/f0143858)       |     Clifton, New Jersey, US |           9.28 TiB |     13.54% |    9.28 TiB |           0.00% |
| [f0674600](https://filfox.info/en/address/f0674600)`new`  | Los Angeles, California, US |           9.22 TiB |     13.45% |    9.19 TiB |           0.34% |
| [f03223](https://filfox.info/en/address/f03223)           |    San Jose, California, US |           9.06 TiB |     13.22% |    9.06 TiB |           0.00% |
| [f01863339](https://filfox.info/en/address/f01863339)     |      Shanghai, Shanghai, CN |           5.28 TiB |      7.70% |    5.28 TiB |           0.00% |
| [f01395673](https://filfox.info/en/address/f01395673)     |          Fuzhou, Fujian, CN |           5.00 TiB |      7.29% |    5.00 TiB |           0.00% |

![Provider Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/378/1671096321197.png)
### Deal Data Replication
The below table shows how each many unique data are replicated across storage providers.
- No more than 25% of unique data are stored with less than 4 providers.

⚠️ 48.63% of deals are for data replicated across less than 4 storage providers.

| Unique Data Size | Total Deals Made | Number of Providers | Deal Percentage |
| ---------------: | ---------------: | ------------------: | --------------: |
|       416.00 GiB |       416.00 GiB |                   1 |           0.59% |
|         5.44 TiB |        10.88 TiB |                   2 |          15.86% |
|         7.34 TiB |        22.06 TiB |                   3 |          32.18% |
|         5.09 TiB |        20.38 TiB |                   4 |          29.72% |
|         2.97 TiB |        14.84 TiB |                   5 |          21.65% |

![Replication Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/378/1671096321998.png)
### Deal Data Shared with other Clients
The below table shows how many unique data are shared with other clients.
Usually different applications owns different data and should not resolve to the same CID.

⚠️ CID sharing has been observed.

| Other Client                                                                                                          | Application                   | Total Deals Affected | Unique CIDs |        Verifier |
| :-------------------------------------------------------------------------------------------------------------------- | :---------------------------- | -------------------: | ----------: | --------------: |
| [f14z37zddplbkmmkvm3jrdldkxji5a5r6iux4dhfi](https://filfox.info/en/address/f14z37zddplbkmmkvm3jrdldkxji5a5r6iux4dhfi) | `  Common primitive universe` |             5.00 TiB |         159 | LDN v3 multisig |

[^1]: To manually trigger this report, add a comment with text `checker:manualTrigger`
