### ISSUE TITLE
[DataCap Application] Hinter

### ISSUE THREAD

**Issue by wdjnbb99zz** [filecoin-project/filecoin-plus-large-datasets#38]
# Large Dataset Notary Application

To apply for a DataCap allocation for your dataset, please fill out the following information.

## Core Information
- Organization Name: Hinter
- Website / Social Media: [https://hinter.team/](https://hinter.team/),  [https://www.frogworld.co.kr](https://www.frogworld.co.kr)
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 10TiB
- On-chain address for first allocation: f3wkyhvuzimh5oal56b5r63fewtfrv3majwg6g5yeu2gydwgjrlhytkgjzombho3eflntbvpyjj54xpowq5z3q

_Please respond to the questions below in pargraph form, replacing the text saying "Please answer here". Include as much detail as you can in your answer!_

## Project details

Share a brief history of your project and organization.
```
Hinter is a company that runs "frog", sneakers resell platform in Korea. Hinter is a startup with about 20 employees who are currently working on development, planning, and design. We launched "frog" in 2018 and have been running it successfully. Currently, "Frog" has over 200,000 members. 
(http://www.apparelnews.co.kr/news/news_view/?idx=187713)
Service : https://www.frogworld.co.kr
Android : https://play.google.com/store/apps/details?id=com.hinter.frogapp_flutter
Ios : [](https://apps.apple.com/kr/app/패션의-완성-프로그-frog/id1494853166)
```

What is the primary source of funding for this project?
```
Hinter, which is currently generating profits on its own, was established as a corporation and received one VC investment.
```

What other projects/ecosystem stakeholders is this project associated with?
```
Hinter is working with a variety of companies that are needed to run "frog" services. Recently, we are discussing additional cooperation with other projects while grafting NFT into operating services. We are preparing a sneaker resell platform that is verified by experts using NFT.
```

## Use-case details

Describe the data being stored onto Filecoin
```
We plan to use Filecoin Network to store data such as sneakers inspection images, sneaker inspection videos, release information videos, and NFT token verification videos required during the service process.
```

Where was the data in this dataset sourced from?
```
Data is generated in the process of operating "frog" service. We create our own images, produce and shoot videos.
```

Can you share a sample of what is in the dataset? A link to a file, an image, a table, etc., are good examples of this. 
```
Service : https://www.frogworld.co.kr
Data sample : https://drive.google.com/drive/folders/1VyDVc3oktbCxt5zkC7hDrK2q3_6pQ6uK

```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
All the data we will store is open data. Naturally, we disclose all data because the service we operate can only achieve its purpose by fully opening the data.
```

What is the expected retrieval frequency for this data?
```
"frog" service is DAU 200,000 service. Sneaker images, videos, and NFT tokens are expected to be accessed and viewed at least 100,000 times a day. As development progresses, we expect the retrieval frequency to increase.
```

For how long do you plan to keep this dataset stored on Filecoin? Will this be a permanent archival or a one-time storage deal?
```
We want to use Filecoin storage permanently. If possible, we would like to use Filecoin storage as the primary storage for the “frog” service.
```

## DataCap allocation plan

In which geographies do you plan on making storage deals?
```
We have plans to create deals mainly in Asia.
```

What is your expected data onboarding rate? How many deals can you make in a day, in a week? How much DataCap do you plan on using per day, per week?
```
We generate user data every day. And we plan to make a deal every week and store the data. We will generate and store about 1 TiB to 2 TiB of data per day and about 10 TiB per week.
```

How will you be distributing your data to miners? Is there an offline data transfer process?
```
Keeping our data safe is very important to us. So we will do distributed storage through 4-5 miners. If possible, we will do offline deals with trusted miners, and we also have online deals in mind. In addition, we plan to proceed with development related to data storage.
```

How do you plan on choosing the miners with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
As we said before, it is very important for us to keep our data safe. So we will make sure that the miners we do business with are specialized in storage operations, have 24-hour supervision, etc. And since data retrieval services are also important to us, we will consider whether we have sufficient competence in this regard. After that, we will make a deal while looking to see if it is possible to continue discussing.
```

How will you be distributing data and DataCap across miners storing data?
```
We will work with 4-5 miners and in consultation with them we will create a service to store and retrieval our data.
```

**Comment by galen-mcandrew** [comment]
## Multisig Notary requested
#### Total DataCap requested 
> 5PiB
#### Expected weekly DataCap usage rate 
> 10TiB

**Comment by MegTei** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebsfyjgnk7pmldqwc3izbfy73ydrqc7byqivd2u6fo4dxvmsbq7ke 
#### Address 
> f3wkyhvuzimh5oal56b5r63fewtfrv3majwg6g5yeu2gydwgjrlhytkgjzombho3eflntbvpyjj54xpowq5z3q
#### Datacap Allocated
> 5TiB
#### Signer Address
> f1ystxl2ootvpirpa7ebgwl7vlhwkbx2r4zjxwe5i
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebsfyjgnk7pmldqwc3izbfy73ydrqc7byqivd2u6fo4dxvmsbq7ke

**Comment by Reiers** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceanmb6xuijt5dskwduy2orsikefxuzf2kv7zlhrbgu4rlqchn2hrm 
#### Address 
> f3wkyhvuzimh5oal56b5r63fewtfrv3majwg6g5yeu2gydwgjrlhytkgjzombho3eflntbvpyjj54xpowq5z3q
#### Datacap Allocated
> 5TiB
#### Signer Address
> f1oz43ckvmtxmmsfzqm6bpnemqlavz4ifyl524chq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceanmb6xuijt5dskwduy2orsikefxuzf2kv7zlhrbgu4rlqchn2hrm

**Comment by ClarkYin5566** [comment]
Hi @wdjnbb99zz , I am also applying for datacap but still waiting for review. I would like to discuss with you how to proceed and how to promote the development of real data. If possible, please leave your email or contact me: mr.clark.yin@gmail.com

**Comment by Sunnyiscoming** [comment]
Are there any problems with using datacap?
