### ISSUE TITLE
[DataCap Application]Samdata Trade

### ISSUE THREAD

**Issue by Samdatatrade1** [filecoin-project/filecoin-plus-large-datasets#382]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Samdata Trade
- Website / Social Media:www.samdata.trade
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5 PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 200TiB
- On-chain address for first allocation: f1f5edx6ofn3lf6rk3yfpldbi2pzgq2egoyu6ubpi

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Matrix mainly takes quantitative investment transaction  as the core , and has the quantitative investment management system with asset portfolio management and other functions, creating a set of full-stack quantitative trading solutions for professional quantitative institutions and quants.
```

What is the primary source of funding for this project?
```
Company's revenues and venture investors.
```

What other projects/ecosystem stakeholders is this project associated with?
```
Nothing else.
```

## Use-case details

Describe the data being stored onto Filecoin
```
1.  Data Type MangoDB
2.  Data stored on Filecoin is mainly from Quotation data, such as market reference data, options data, index data, fund data, futures data, bond data.
```

Where was the data in this dataset sourced from?
```
The data comes from crawler data in the world's major crypto currency CEX .
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
[AMPUSDT_daily.csv](https://github.com/filecoin-project/filecoin-plus-large-datasets/files/8851303/AMPUSDT_daily.csv)
[BORAUSDT_daily.csv](https://github.com/filecoin-project/filecoin-plus-large-datasets/files/8851305/BORAUSDT_daily.csv)

[CELOUSDT_daily.csv](https://github.com/filecoin-project/filecoin-plus-large-datasets/files/8851308/CELOUSDT_daily.csv)

```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes, we confirm that the data is public and can be retrieved by anyone on the network.
```

What is the expected retrieval frequency for this data?
```
Once a year.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
At least 3 years.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
We plan to make deals across Asia.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Both online and offline.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We will negotiate with the miners to enable fast retrieval.
```

How will you be distributing deals across storage providers?
```
At least 5 SP.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, we have enough funding.I want good technical support and SP.
```

**Comment by Samdatatrade1** [comment]
We have submitted the issue,  what do we need to do next? @galen-mcandrew @dkkapur @Kevin-FF-USA

**Comment by Samdatatrade1** [comment]
Is my issue ready for application? @galen-mcandrew @dkkapur @Kevin-FF-USA

**Comment by Yvette516** [comment]
Please send an email to filplus@fil.org from your official email account to confirm your application.

**Comment by Sunnyiscoming** [comment]
Any update?

**Comment by Yvette516** [comment]
Could you send an email to filplus@fil.org from your officail email Account?

**Comment by Samdatatrade1** [comment]
@Yvette516 
![6fed](https://user-images.githubusercontent.com/105560098/177069423-1f87b131-1393-419c-9e00-7ab456d0d3d9.png)
Hi, we have done it last week.

**Comment by Samdatatrade1** [comment]
@Sunnyiscoming
[ades0531.zip](https://github.com/filecoin-project/filecoin-plus-large-datasets/files/9110127/ades0531.zip)
[bdes0603.zip](https://github.com/filecoin-project/filecoin-plus-large-datasets/files/9110657/bdes0603.zip)
Hi Sunny, mainly this kind of data.

**Comment by Sunnyiscoming** [comment]
Could you send an email to filplus@fil.org with your official domain in order to confirm your identity?
Email name should includes the issue id #382.

**Comment by Samdatatrade1** [comment]
> @Yvette516 ![6fed](https://user-images.githubusercontent.com/105560098/177069423-1f87b131-1393-419c-9e00-7ab456d0d3d9.png) Hi, we have done it last week.

@Sunnyiscoming I used to finish it.

**Comment by raghavrmadya** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5 PiB

**Expected weekly DataCap usage rate**

> 200 TiB

**Client address**

> f1f5edx6ofn3lf6rk3yfpldbi2pzgq2egoyu6ubpi

**Comment by raghavrmadya** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5 PiB

**Expected weekly DataCap usage rate**

> 200 TiB

**Client address**

> f1f5edx6ofn3lf6rk3yfpldbi2pzgq2egoyu6ubpi

**Comment by raghavrmadya** [comment]
Note for Notaries: Please determine if the SP distribution looks good as well as the number of copies the client plans to store before making the first allocation. Can confirm that the email was received.

**Comment by BlockMakeronline** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceap4ko5jqywrmaypd62tonc53hwhcvp4mk66pk5pc3na2vhdx47w6 
#### Address 
> f1f5edx6ofn3lf6rk3yfpldbi2pzgq2egoyu6ubpi
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1o3twrcpwjtpcd4q36lpq4qmy2qfbgtyy5h6tsty
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceap4ko5jqywrmaypd62tonc53hwhcvp4mk66pk5pc3na2vhdx47w6

**Comment by MetaWaveInfo** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecdyadohfi4jvwkfx5xnaemgrpxvg6iulmnzxo2viviljcdf7o4se 
#### Address 
> f1f5edx6ofn3lf6rk3yfpldbi2pzgq2egoyu6ubpi
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1ktlkcxnmzxcdaoqfsunrg3vocfbmgv4n3mrn74a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecdyadohfi4jvwkfx5xnaemgrpxvg6iulmnzxo2viviljcdf7o4se

**Comment by BigD-Exchange** [comment]
@Samdatatrade1 Hi! Great to see you have gotten approval for DataCap. If you are looking for reputable storage providers to store these data, please visit #bigdata-exchange on Filecoin Slack or reply here.

**Comment by Joss-Hua** [comment]
![image](https://user-images.githubusercontent.com/75723122/188831352-26f0bb54-7413-446c-9a91-deabe498a9bd.png)
Please note the proportion

**Comment by Samdatatrade1** [comment]
@Joss-Hua OK. It is because that we just got a small amount of datacap and we will follow up with more decentralized distributing. Thank you.

**Comment by PluskitOfficial** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebuhx67glufvby7echvu47kgpg6avfwkssqo2tqpq3c74eahlb7ck 
#### Address 
> f1f5edx6ofn3lf6rk3yfpldbi2pzgq2egoyu6ubpi
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1tgnlhtcmhwipfm7thsftxhn5k52velyjlazpvka
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebuhx67glufvby7echvu47kgpg6avfwkssqo2tqpq3c74eahlb7ck

**Comment by PluskitOfficial** [comment]
Hi, @Samdatatrade1 , we've already signed once.
Pls. be aware of the storage ratio.
We'll continue to pay attention to this project.

**Comment by BlockMakeronline** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedgc3tdoaftvvtarj2t3lluhn7ablrs3dhhczgygpunaq2usrtupm 
#### Address 
> f1f5edx6ofn3lf6rk3yfpldbi2pzgq2egoyu6ubpi
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1o3twrcpwjtpcd4q36lpq4qmy2qfbgtyy5h6tsty
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedgc3tdoaftvvtarj2t3lluhn7ablrs3dhhczgygpunaq2usrtupm

**Comment by swatchliu** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedufdtafe3jf2icnt2i3aoeuzxeyku2jgb3aj6v75auadceoc3fgw 
#### Address 
> f1f5edx6ofn3lf6rk3yfpldbi2pzgq2egoyu6ubpi
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1yh6q3nmsg7i2sys7f7dexcuajgoweudcqj2chfi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedufdtafe3jf2icnt2i3aoeuzxeyku2jgb3aj6v75auadceoc3fgw

**Comment by PluskitOfficial** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebwhwzl2vbgi5ytwbx7kbmfbhhzfvrj3sm7zpzlppnomphewnbkcy 
#### Address 
> f1f5edx6ofn3lf6rk3yfpldbi2pzgq2egoyu6ubpi
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1tgnlhtcmhwipfm7thsftxhn5k52velyjlazpvka
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebwhwzl2vbgi5ytwbx7kbmfbhhzfvrj3sm7zpzlppnomphewnbkcy

**Comment by liyunzhi-666** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecy5irshsrba6rbdif6liz6cehjpl74tmfntzqtckimj3crkzrwaa 
#### Address 
> f1f5edx6ofn3lf6rk3yfpldbi2pzgq2egoyu6ubpi
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1pszcrsciyixyuxxukkvtazcokexbn54amf7gvoq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecy5irshsrba6rbdif6liz6cehjpl74tmfntzqtckimj3crkzrwaa

**Comment by MetaWaveInfo** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedqtotvbwyntdcpdnclmpaahulcqggdssdwehv6lsuumvs5mmtthc 
#### Address 
> f1f5edx6ofn3lf6rk3yfpldbi2pzgq2egoyu6ubpi
#### Datacap Allocated
> 1.56PiB
#### Signer Address
> f1ktlkcxnmzxcdaoqfsunrg3vocfbmgv4n3mrn74a
#### Id
> b8237be1-01af-4dae-a3e4-7771e5fc0596
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedqtotvbwyntdcpdnclmpaahulcqggdssdwehv6lsuumvs5mmtthc

**Comment by 1475Notary** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb75tsewfd7lu5o5sskou6ldq63twwvismnzdpvncgqaeqny6xdow 
#### Address 
> f1f5edx6ofn3lf6rk3yfpldbi2pzgq2egoyu6ubpi
#### Datacap Allocated
> 1.56PiB
#### Signer Address
> f1ofq4mngy7ggcp755pfquq2gphjjnlydolf6awtq
#### Id
> b8237be1-01af-4dae-a3e4-7771e5fc0596
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb75tsewfd7lu5o5sskou6ldq63twwvismnzdpvncgqaeqny6xdow

**Comment by filplus-checker** [comment]
## DataCap and CID Checker Report[^1]
 - Organization: `Samdata Trade`
 - Client: `f1f5edx6ofn3lf6rk3yfpldbi2pzgq2egoyu6ubpi`
### Storage Provider Distribution
The below table shows the distribution of storage providers that have stored data for this client.

If this is the first time a provider takes verified deal, it will be marked as `new`.

For most of the datacap application, below restrictions should apply.
 - Storage provider should not exceed 25% of total datacap.
 - Storage provider should not be storing duplicate data for more than 20%.
 - Storage provider should have published its public IP address.
 - All storage providers should be located in different regions.

⚠️ 83.52% of total deal sealed by [f01889480](https://filfox.info/en/address/f01889480) are duplicate data.

⚠️ 89.83% of total deal sealed by [f01887652](https://filfox.info/en/address/f01887652) are duplicate data.

⚠️ 77.55% of total deal sealed by [f01926914](https://filfox.info/en/address/f01926914) are duplicate data.

⚠️ 79.29% of total deal sealed by [f01926585](https://filfox.info/en/address/f01926585) are duplicate data.

⚠️ 42.80% of total deal sealed by [f01889046](https://filfox.info/en/address/f01889046) are duplicate data.

⚠️ 71.71% of total deal sealed by [f01924350](https://filfox.info/en/address/f01924350) are duplicate data.

⚠️ 46.91% of total deal sealed by [f01914977](https://filfox.info/en/address/f01914977) are duplicate data.

⚠️ 81.14% of total deal sealed by [f01937964](https://filfox.info/en/address/f01937964) are duplicate data.

⚠️ 25.81% of total deal sealed by [f01917214](https://filfox.info/en/address/f01917214) are duplicate data.

⚠️ 25.47% of total deal sealed by [f01917241](https://filfox.info/en/address/f01917241) are duplicate data.

⚠️ 25.83% of total deal sealed by [f01917257](https://filfox.info/en/address/f01917257) are duplicate data.

⚠️ 32.38% of total deal sealed by [f01895990](https://filfox.info/en/address/f01895990) are duplicate data.

⚠️ 33.05% of total deal sealed by [f01895778](https://filfox.info/en/address/f01895778) are duplicate data.

| Provider                                              |                 Location | Total Deals Sealed | Percentage | Unique Data | Duplicate Deals |
| :---------------------------------------------------- | -----------------------: | -----------------: | ---------: | ----------: | --------------: |
| [f01889480](https://filfox.info/en/address/f01889480) |     Boardman, Oregon, US |         278.38 TiB |     14.80% |   45.88 TiB |          83.52% |
| [f01887652](https://filfox.info/en/address/f01887652) |    Ashburn, Virginia, US |         264.38 TiB |     14.05% |   26.88 TiB |          89.83% |
| [f01926914](https://filfox.info/en/address/f01926914) |    Ashburn, Virginia, US |         261.69 TiB |     13.91% |   58.75 TiB |          77.55% |
| [f01926585](https://filfox.info/en/address/f01926585) |    Ashburn, Virginia, US |         257.38 TiB |     13.68% |   53.31 TiB |          79.29% |
| [f01889046](https://filfox.info/en/address/f01889046) |    Ashburn, Virginia, US |         182.25 TiB |      9.69% |  104.25 TiB |          42.80% |
| [f01924350](https://filfox.info/en/address/f01924350) | Singapore, Singapore, SG |         134.00 TiB |      7.12% |   37.91 TiB |          71.71% |
| [f01914977](https://filfox.info/en/address/f01914977) |    Ashburn, Virginia, US |         132.97 TiB |      7.07% |   70.59 TiB |          46.91% |
| [f01937964](https://filfox.info/en/address/f01937964) |         Tokyo, Tokyo, JP |         120.63 TiB |      6.41% |   22.75 TiB |          81.14% |
| [f01917214](https://filfox.info/en/address/f01917214) |         Seoul, Seoul, KR |          50.00 TiB |      2.66% |   37.09 TiB |          25.81% |
| [f01917241](https://filfox.info/en/address/f01917241) |         Seoul, Seoul, KR |          49.94 TiB |      2.65% |   37.22 TiB |          25.47% |
| [f01917257](https://filfox.info/en/address/f01917257) |         Seoul, Seoul, KR |          49.84 TiB |      2.65% |   36.97 TiB |          25.83% |
| [f01895990](https://filfox.info/en/address/f01895990) | Singapore, Singapore, SG |          33.97 TiB |      1.81% |   22.97 TiB |          32.38% |
| [f01895783](https://filfox.info/en/address/f01895783) |     Boardman, Oregon, US |          33.00 TiB |      1.75% |   33.00 TiB |           0.00% |
| [f01895778](https://filfox.info/en/address/f01895778) | Singapore, Singapore, SG |          33.00 TiB |      1.75% |   22.09 TiB |          33.05% |

![Provider Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/382/1671096346894.png)
### Deal Data Replication
The below table shows how each many unique data are replicated across storage providers.
- No more than 25% of unique data are stored with less than 4 providers.

⚠️ 100.00% of deals are for data replicated across less than 4 storage providers.

| Unique Data Size | Total Deals Made | Number of Providers | Deal Percentage |
| ---------------: | ---------------: | ------------------: | --------------: |
|       373.09 TiB |         1.33 PiB |                   1 |          72.18% |
|       110.69 TiB |       503.91 TiB |                   2 |          26.78% |
|         5.06 TiB |        19.44 TiB |                   3 |           1.03% |

![Replication Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/382/1671096347597.png)
### Deal Data Shared with other Clients
The below table shows how many unique data are shared with other clients.
Usually different applications owns different data and should not resolve to the same CID.

⚠️ CID sharing has been observed.

| Other Client                                                                                                          | Application                                                                                                                | Total Deals Affected | Unique CIDs |                                                                                 Verifier |
| :-------------------------------------------------------------------------------------------------------------------- | :------------------------------------------------------------------------------------------------------------------------- | -------------------: | ----------: | ---------------------------------------------------------------------------------------: |
| [f1ivsvpljx4ovp2tth73pllkxmumrudemks623iia](https://filfox.info/en/address/f1ivsvpljx4ovp2tth73pllkxmumrudemks623iia) | `TIS Inc. group`                                                                                                           |           613.59 TiB |       3,656 |                                                                          LDN v3 multisig |
| [f1727w2vwjctfo7hflr5trgqkl3c7texh7pl4grzq](https://filfox.info/en/address/f1727w2vwjctfo7hflr5trgqkl3c7texh7pl4grzq) | [GMverse](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/365)                                     |           421.06 TiB |       3,671 |                                                                          LDN v3 multisig |
| [f1vtcetpapwwyka6txwqjwymsa67npdfilbkwh64a](https://filfox.info/en/address/f1vtcetpapwwyka6txwqjwymsa67npdfilbkwh64a) | [Chimay](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/397)                                      |           251.78 TiB |       2,664 |                                                                          LDN v3 multisig |
| [f1ki4cjk27ypzjsuzkvvqzs6xobaweuoxfdcnpqhy](https://filfox.info/en/address/f1ki4cjk27ypzjsuzkvvqzs6xobaweuoxfdcnpqhy) | [TimeQuant](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/385)                                   |           185.00 TiB |       2,491 |                                                                          LDN v3 multisig |
| [f1dx7ljly4vmk5x2bn5ng4jpbqnuvozrz2phw42qy](https://filfox.info/en/address/f1dx7ljly4vmk5x2bn5ng4jpbqnuvozrz2phw42qy) | [CoinPhD](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/364)                                     |           161.94 TiB |       1,496 |                                                                          LDN v3 multisig |
| [f17qd6x3leh5pa7vh6ewdaed7qhbn2mgofrokuayy](https://filfox.info/en/address/f17qd6x3leh5pa7vh6ewdaed7qhbn2mgofrokuayy) | [Drust](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/427)                                       |           152.09 TiB |       2,337 |                                                                          LDN v3 multisig |
| [f1u522dt3zabkgbxxzecl77wgv473yvpecxh6t6zq](https://filfox.info/en/address/f1u522dt3zabkgbxxzecl77wgv473yvpecxh6t6zq) | [Huifan livestream](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/407)                           |           108.00 TiB |         940 |                                                                          LDN v3 multisig |
| [f1xtnkj5ti77f5gbzhclnpj3xt6e5dwhfzive2yca](https://filfox.info/en/address/f1xtnkj5ti77f5gbzhclnpj3xt6e5dwhfzive2yca) | [Beacon Project](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/482)                              |           106.13 TiB |         300 | Project Beacon, 12 LDNs LDN # 444, 446, 447, 448, 474, 475, 476, 477, 479, 480, 481, 482 |
| [f1rnwp6p5kx7pcwexpucoav6mmwz3rkxw5blrboyy](https://filfox.info/en/address/f1rnwp6p5kx7pcwexpucoav6mmwz3rkxw5blrboyy) | [MigoVideo](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/517)                                   |            92.09 TiB |       1,569 |                                                                          LDN v3 multisig |
| [f14abwn2goturifmt27s2bssoe3fup2b3npkgfzui](https://filfox.info/en/address/f14abwn2goturifmt27s2bssoe3fup2b3npkgfzui) | [KONGFU VR](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/372)                                   |            84.63 TiB |       1,591 |                                                                          LDN v3 multisig |
| [f1tgii4xgcp6um4n2w7eqaw6bwvnvyii2u7cjgzka](https://filfox.info/en/address/f1tgii4xgcp6um4n2w7eqaw6bwvnvyii2u7cjgzka) | [Meson\.Network ](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/187)                             |            81.94 TiB |         243 |                                                                          LDN v3 multisig |
| [f1bb2z36lpq3pnwiiowiraagpzqnpow4bonjacx7a](https://filfox.info/en/address/f1bb2z36lpq3pnwiiowiraagpzqnpow4bonjacx7a) | [Hola Space](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/362)                                  |            64.56 TiB |         754 |                                                                          LDN v3 multisig |
| [f1clwd2dooy2cflfilhzeq2ycl544b3heqsiwhjrq](https://filfox.info/en/address/f1clwd2dooy2cflfilhzeq2ycl544b3heqsiwhjrq) | [FiboAI](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/349)                                      |            58.25 TiB |         661 |                                                                          LDN v3 multisig |
| [f1ffbtksiso5za73pypuxbxznng6rdv64nbihdtba](https://filfox.info/en/address/f1ffbtksiso5za73pypuxbxznng6rdv64nbihdtba) | [EpikProtocol](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/281)                                |            56.00 TiB |         181 |                                                                                LDN # 281 |
| [f1einobkrjcjk6gfc5ov6663vrri75hwdsjfs6pmq](https://filfox.info/en/address/f1einobkrjcjk6gfc5ov6663vrri75hwdsjfs6pmq) | [Cansoti](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/640)                                     |            55.88 TiB |         988 |                                                                          LDN v3 multisig |
| [f1muygjb5zowppbhr7wnmdreqdoiyyanfm7fe54dy](https://filfox.info/en/address/f1muygjb5zowppbhr7wnmdreqdoiyyanfm7fe54dy) | [MappingFunk Protocol ](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/374)                       |            53.38 TiB |         857 |                                                                          LDN v3 multisig |
| [f1ajdk7e6ex7fvtjtydzgys47bcg7jub2baucun7y](https://filfox.info/en/address/f1ajdk7e6ex7fvtjtydzgys47bcg7jub2baucun7y) | [Ruikuyun Information Technology Co\., Ltd](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/529)   |            46.38 TiB |         760 |                                                                          LDN v3 multisig |
| [f1jdmx2cuswzjlt4pnsv3t7ipmesywzxsg6q56a2a](https://filfox.info/en/address/f1jdmx2cuswzjlt4pnsv3t7ipmesywzxsg6q56a2a) | [Raysun Radar Electronic Technology Co\.,Ltd](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/884) |            34.88 TiB |         232 |                                                                          LDN v3 multisig |
| [f1dwhevm3p2slu6itmkssznscmpkpltdiztprnpya](https://filfox.info/en/address/f1dwhevm3p2slu6itmkssznscmpkpltdiztprnpya) | [Hiscene](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/548)                                     |            25.75 TiB |         605 |                                                                          LDN v3 multisig |
| [f1avhqgmeazxzvylz34l26o3nlj2ywnzaviwns3dq](https://filfox.info/en/address/f1avhqgmeazxzvylz34l26o3nlj2ywnzaviwns3dq) | [87v5\-CarsonVideo](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/392)                           |            15.03 TiB |         196 |                                                                          LDN v3 multisig |
| [f1quofpadzcqlonmz7v3mv7dfqvm5hdztucdsjqsy](https://filfox.info/en/address/f1quofpadzcqlonmz7v3mv7dfqvm5hdztucdsjqsy) | [HENAN 863 SOFTWARE CO\., LTD](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/468)                |            14.75 TiB |         124 |                                                                          LDN v3 multisig |
| [f1zb6pgkktdbyy7zxfob6gripqxuc25ukf35cc7fq](https://filfox.info/en/address/f1zb6pgkktdbyy7zxfob6gripqxuc25ukf35cc7fq) | `Maxpic PhotoGraphic Studio`                                                                                               |            14.47 TiB |         275 |                                                                          LDN v3 multisig |
| [f1l2hkjqfh5abpd5x6lxj4tjrphaa44pnumt5ms5i](https://filfox.info/en/address/f1l2hkjqfh5abpd5x6lxj4tjrphaa44pnumt5ms5i) | [Fly Brain Anatomy \- Slingshot](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/153)              |           960.00 GiB |           3 |                                                                                LDN # 153 |
| [f1zav4f4rak2yvbrq357z3whj224wn4dipl7eiesy](https://filfox.info/en/address/f1zav4f4rak2yvbrq357z3whj224wn4dipl7eiesy) | [Shanghai Zhixun](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/628)                             |           832.00 GiB |           2 |                                                                          LDN v3 multisig |
| [f1tivtdkq34mnfzso63wrr2xh6r2zo7aebao4jfla](https://filfox.info/en/address/f1tivtdkq34mnfzso63wrr2xh6r2zo7aebao4jfla) | `China travel service(HongKong) limited`                                                                                   |           736.00 GiB |           2 |                                                                          LDN v3 multisig |
| [f1ojo3wo24zkeovndlxfpqmlgzlbysg5fiukmup4a](https://filfox.info/en/address/f1ojo3wo24zkeovndlxfpqmlgzlbysg5fiukmup4a) | `Titansoft`                                                                                                                |           288.00 GiB |           1 |                                                                          LDN v3 multisig |

[^1]: To manually trigger this report, add a comment with text `checker:manualTrigger`

**Comment by kevzak** [comment]
checker:manualTrigger

**Comment by Sunnyiscoming** [comment]
Hello, @Samdatatrade1 per the https://github.com/filecoin-project/notary-governance/issues/922 for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

This information will be reviewed by Fil+ Governance team to confirm validity and then the application will be allowed to move forward for additional notary review.
