### ISSUE TITLE
[DataCap Application] SAO Network

### ISSUE THREAD

**Issue by SAONetwork01** [filecoin-project/filecoin-plus-large-datasets#383]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Hedra Labs
- Website / Social Media:https://sao.network
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):2PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):100TiB
- On-chain address for first allocation:f1bbv342chq7irgtqqjrcngkb2olyvfcu23p23sey

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
SAO Network, powered by Hedra Labs, is a secure and decentralized storage infrastructure for Web3 based on Cosmos SDK and IPFS protocol. HEDRA LABS, the core development team in SAO Network, was established in Singapore in 2021 as a blockchain technology focused R&D taskforce teamed by industry pioneers, senior architects and developers from both FinTech and blockchain fields who are dedicated to the development and evolution of Web3 and decentralized storage networks.  
```
What is the primary source of funding for this project?
```
Ever since its implementation, SAO Network has been funded with the company's operating funds.
```
What other projects/ecosystem stakeholders is this project associated with?
```
Currently, there is no other project or ecosystem stakeholder associated with SAO Network. 
```
## Use-case details

Describe the data being stored onto Filecoin
```
Users can store any data that is useful or meaningful for them, including files, pictures, videos, music, digital artworks, and data backup, etc.
```
Where was the data in this dataset sourced from?
```
Our users are around the globe, so data in this dataset may be sourced from the US, Canada, China mainland or Taiwan etc.
```
Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://mint.toolsofrock.com/static/img/content/vip-pass.gif  
```      
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes, we confirm this is a public dataset that can be retrieved by anyone on the network with no specific permissions or access rights required.
```
What is the expected retrieval frequency for this data?
```
Data stored onto SAO Network will be sealed over a long period of time and can be retrieved when it's needed. As a result, retrieval frequency is decided by how frequently our users will retrieve their stored data.
```
For how long do you plan to keep this dataset stored on Filecoin?
```
We intend to cooperate and keep this dataset stored on Filecoin for a long term.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Since our customers are scattered around the world, storage deals may happen in any country or region.
```
How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
The data are expectedly distributed online to storage providers. No offline transfer process is needed yet.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We may get some notes and suggestions from the storage provider community and we would try different providers at the start. And experienced storage providers are mostly welcomed to contact us through email at contact@sao.network.
```

How will you be distributing deals across storage providers?
```
We intend to distribute deals to 3 to 5 storage providers at least.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes we have got sufficient funding and resources from the company to make deals. Yet we may occasionally need a few technic supports from the community and Filecoin official team. Thank you.
```

**Comment by swatchliu** [comment]
As a storage project, can you tell us whether you will review the data content uploaded to your platform by users? Is there a notary system in SAO Network?

**Comment by SAONetwork01** [comment]
Yep! There will be. We'll work out different content audit methods which are taken on the ground of feasibility and project phases, like manual review, community governance, oracle and AI technology etc.

**Comment by Sunnyiscoming** [comment]
Any update?

**Comment by SAONetwork01** [comment]
Hello @Sunnyiscoming, thanks for your kind reminder! We have dozens of terabyte data currently in local server. And it's estimated that there are going to be about 1PiB data to be generated in our Apps in the next 6 months. As far as I can see, the DataCap won't be given to us all at once but in a sequential allocation manner, won't it? 

Here is a piece of data in one of our Apps, please check that. I'd appreciate your review and any feedback.
[a(1).txt](https://github.com/filecoin-project/filecoin-plus-large-datasets/files/9044609/a.1.txt)

**Comment by SAONetwork01** [comment]
Yes sure! @Sunnyiscoming 

![631](https://user-images.githubusercontent.com/90945996/178219756-7276a2b8-d6e8-4b4e-aec2-026011ebb034.png)
https://user-images.githubusercontent.com/90945996/178221246-a1021898-c0aa-4e3e-b2f1-d2271f657167.mp4

**Comment by Sunnyiscoming** [comment]
Datacap will be allocated to the existing dataset. So I want to confirm with you how much data you already have at present.

**Comment by SAONetwork01** [comment]
@galen-mcandrew Hi Galen and the team, could you help push forward the process? It's been two months since we firstly submitted this DataCap application issue. We are open to answer any question and provide additional information if requested.

**Comment by raghavrmadya** [comment]
Hi @SAONetwork01 , the .txt file you share above has many .eth addresses some of which have offensive names. Can you share more about the funding sources and what kind of retrieval applications do you see for this data?

**Comment by SAONetwork01** [comment]
Hello. As stated above, we are a self-funded team. And as for the data sample we shared before, SAO is a web3 storage platform, the sample data is a part of the files user uploaded. We checked the full data and confirmed that all data came from Ethereum blockchain and the offensive characters are registered ENS name.

**Comment by raghavrmadya** [comment]
You only have 200 TiBs of data correct? How many copies are you hoping to store? Just to be clear, the power adjustment does not need to be 10x the dataset. Please clarify that you have 2 PiBs of data to store.

**Comment by SAONetwork01** [comment]
@raghavrmadya Yes, currently we have 200 TiB raw data. According to fil+ and slingshot rules, clients are allowed to store up to 10 replicas of the same piece of data. We may need different numbers of replicas for different client's requirements on data safety with an average number at 5.  As a storage platform, our data size will grow constantly.
Here are the rules we will follow: The general recommendation for clients on the network is to build several replicas of their data on the network, ideally with different SPs/SP entities to spread risk. From a DataCap distribution perspective, guidance
is that clients should engage at least 4 SPs and no single SP ID should receive>30% of a client's allocated DataCap.
https://github.com/filecoin-project/filecoin-plus-client-onboarding#finding-storage-providers-to-take-fil-deals
Storing up to 10 replicas of each piece ofdata: You are allowed to store up to 10 replicas of the same piece of data on the network per project.
https://slingshot.filecoin.io/rules

**Comment by raghavrmadya** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 2 PiB

**Expected weekly DataCap usage rate**

> 100 TiB

**Client address**

> f1bbv342chq7irgtqqjrcngkb2olyvfcu23p23sey

**Comment by raghavrmadya** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 2 PiB

**Expected weekly DataCap usage rate**

> 100 TiB

**Client address**

> f1bbv342chq7irgtqqjrcngkb2olyvfcu23p23sey

**Comment by raghavrmadya** [comment]
@SAONetwork01 , have you reached out to notaries ti support your request?

**Comment by SAONetwork01** [comment]
@raghavrmadya Hello! We have posted our request in the "fil-plus-application-review" channel in slack, but it seems that it does not work. Do you suggest that we reach out notaries through DM?

**Comment by SAONetwork01** [comment]
@raghavrmadya Hello! It has been over three months since our first application. What else should we do to get our application approved? Please kindly help us push this forward. Many thanks!

**Comment by simonkim0515** [comment]
@SAONetwork01 Yes, you could reach out to a notary and if you still do not get a response, please look this issue for further support. https://github.com/filecoin-project/notary-governance/issues/537

**Comment by Joss-Hua** [comment]
That is to say, _sao.network_ is a mine pool, so that I want to know the relationship between nodes of the pool and you.

**Comment by SAONetwork01** [comment]
@Joss-Hua Currently, the node of the mine pool is owned by SAO Network. You can refer to f01666984 to check the states.

**Comment by Joss-Hua** [comment]
It seems that SPs have a complex interest relationship with the Client, which is unfavorable to the review of notaries. I want to hear what other notaries think.

**Comment by SAONetwork01** [comment]
@Joss-Hua  Thank you Jose, but I don’t think it’s a problem actually. Firstly, SAO Network provides a decentralized storage platform as well as toolings for any application and user to better utilize IPFS/Filecoin to store and manage their data. Furthermore, while we store the data in our own miner node,  we’re also reaching out for other miners to handle the storage deals. Sure we will follow the requirements and instructions of Filecoin Plus Program.

**Comment by Sunnyiscoming** [comment]
Hey @SAONetwork01, if you still want to apply for datacap, you can ask notaries to do client due diligence.

**Comment by SAONetwork01** [comment]
> Hey @SAONetwork01, if you still want to apply for datacap, you can ask notaries to do client due diligence in slack channel. https://app.slack.com/client/TEHTVS1L6/C036JKD8NVA/thread/C03BG1MNQ4T-1673888660.823499

@Sunnyiscoming Thanks for reaching out! Yes we had tried, so many times, to reach notaries, but unfortunately, seldom got replies. How do you suggest that we should pull the application forward?

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Can you show us visible proof of the size of your data and the storage systems you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230337462961356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!
