### ISSUE TITLE
[DataCap Application]

### ISSUE THREAD

**Issue by xiaoliuxiao6** [filecoin-project/filecoin-plus-large-datasets#384]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Ninth Heaven Guild
- Website / Social Media: https://ninthheaven.io/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100TiB
- On-chain address for first allocation: f3wzua4wihcouehv5datojpgalyapegvdfkhkqamxdtr4tzcsn7kylkoaapmmxisbp3tzekgijb32lrswf5t5q

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Ninth Heaven Guild is a global community focusing on the gmaefi competition track, focusing on the gamefi project with a competitive nature, with a professional blockchain data investment, research team and rich experience in the management of large traditional e-sports clubs.
Ninth Heaven Guild is optimistic about the gamefi competition track, and provides its members with all-round screening and data analysis of various large-scale chain game projects, and guild activities, not only to experience the game fun, satisfaction and superiority brought by well-made gamefi projects, but also get huge profits. Really do play to fun, play to eran! The purpose of our association: Players come first, Play first, and Earn money!
```

What is the primary source of funding for this project?
```
It is funded by ourselves.
```

What other projects/ecosystem stakeholders is this project associated with?
```
Currently, there is no other project or ecosystem stakeholder associated with Ninth Heaven Guild
```

## Use-case details

Describe the data being stored onto Filecoin
```
They are mainly stored competition video, pictures and some documents by our guild.
```

Where was the data in this dataset sourced from?
```
We record game competitions by our guild memebers.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://www.youtube.com/watch?v=CjpRv1lQIOk&t=24s&ab_channel=NinthHeavenGuild
```

Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes, we confirm that the dataset is public and can be retrieved by anyone.
```

What is the expected retrieval frequency for this data?
```
It won't be retrived very often because of amout of data.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
3 years at least, if needed we will keep for a long time.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Asia
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Both online and offline transfer process are OK.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We pay attention to their work time and how much they cost.  We need comprehensive storage providers who can coorperate for a long time.
```

How will you be distributing deals across storage providers?
```
We will distribute different deals according to their distance. 
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
We're ready for making deals.
```

**Comment by Sunnyiscoming** [comment]
> Ninth Heaven Guild is a global community focusing on the gmaefi competition track,  focusing on the gamefi project with a competitive nature, with a professional blockchain data investment,  research team and rich experience in the management of large traditional e-sports clubs.
> Ninth Heaven Guild is optimistic about the gamefi competition track,  and provides its members with all-round screening and data analysis of various large-scale chain game projects,  and guild activities, not only to experience the game fun,  satisfaction and superiority brought by well-made gamefi projects, but also get huge profits. Really do play to fun,  play to eran!  The purpose of our association: Players come first, Play first, and Earn money!

@xiaoliuxiao6 As you said above. Can you give a brief list of gamefi projects, major games events that you've hosted? To prove that you really have accumulated enough data. Or you can be more specific about your data sources.

**Comment by Sunnyiscoming** [comment]
@xiaoliuxiao6 Hey. Could you send an email to filplus@fil.org with your official domain in order to confirm your identity?

**Comment by Sunnyiscoming** [comment]
Have you sent email?

**Comment by raghavrmadya** [comment]
Your online presence indicates that you have not been around for very long. Please provide further clarification of why you need 5 PiBs of data. Also please provide more insight into the SP Allocation plan and anySP IDs you have commitment to store with

**Comment by Sunnyiscoming** [comment]
Any update here?

**Comment by raghavrmadya** [comment]
Closing to to no response. Please open a new app if you still wish to pursue it.
