### ISSUE TITLE
[DataCap Application] MyTrade

### ISSUE THREAD

**Issue by David-MyTrade** [filecoin-project/filecoin-plus-large-datasets#386]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: MyTrade Technology Limited
- Website / Social Media:www.MyTrade.org
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 200PiB
- On-chain address for first allocation: f1ffr7uhq7mszotfdybexcnl4i7xw5tqyp5fhqy3y

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Founded in 2020,MyTrade is a next generation DEX that looks and feels like a centralized exchange with a wide variety of quality tradable assets.
```

What is the primary source of funding for this project?
```
Commercial revenue of our own company.
```

What other projects/ecosystem stakeholders is this project associated with?
```
No, we are the only entity that engaged in this project.
```

## Use-case details

Describe the data being stored onto Filecoin
```
Transaction data, history records of candlestick chart, user data and big data from billions of orders for AI training
```

Where was the data in this dataset sourced from?
```
As a centralized exchange, we have transaction records and relevant system file from over 10 chains in both DEX and CEX transactions; history records of candlestick chart for users and investors to analyze the market; user data and their behavior records for machine learning and data from orders for AI training 
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
Sure. We've uploaded several samples.
[app_sum_action.csv](https://github.com/filecoin-project/filecoin-plus-large-datasets/files/8804617/app_sum_action.csv)
[app_user_action.csv](https://github.com/filecoin-project/filecoin-plus-large-datasets/files/8804618/app_user_action.csv)
[k_line_minute_matic_usdc_mytrade.csv](https://github.com/filecoin-project/filecoin-plus-large-datasets/f
[Release.csv](https://github.com/filecoin-project/filecoin-plus-large-datasets/files/8804622/Release.csv)
iles/8804619/k_line_minute_matic_usdc_mytrade.csv)

```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes, we confirm that the data we owned is public.
```

What is the expected retrieval frequency for this data?
```
2-3 times a year, or less retrieval frequency.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
We are going to keep this dataset on Filecoin for 2 years.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
All regions.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Both online and offline are available for us. SPs should have minimum 1Gbps bandwidth to get the online deal from us.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
SP should have at least 10x filecoin as mortgage
```

How will you be distributing deals across storage providers?
```
We’d like to making deals with 5-8 storage providers. In that case, each provider will storage up to 12.5% of our data. Storage provider from Filecoin community are also welcomed.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Of course we have sufficient funds to start this project. We hope we can make contact with storage provides with technical skills from filecoin community.
```

**Comment by MyTrade-David** [comment]
I've finished my issue for 6 days. @galen-mcandrew @dkkapur @Kevin-FF-USA

**Comment by MyTrade-David** [comment]
Can I get some response?

**Comment by MyTrade-David** [comment]
Please approve my issue. @galen-mcandrew @dkkapur @Kevin-FF-USA

**Comment by Sunnyiscoming** [comment]
@MyTrade-David  Hey. Could you send an email to filplus@fil.org with your official domain in order to confirm your identity?

**Comment by David-MyTrade** [comment]
![MTE1](https://user-images.githubusercontent.com/105814686/176100619-efcd417a-9865-4471-95e3-b3258e89e93f.png)
Hi @Sunnyiscoming , I've finished it.

**Comment by David-MyTrade** [comment]
Hello every one, any update here?

**Comment by galen-mcandrew** [comment]
## Datacap Request Trigger
#### Total DataCap requested 
> 5PiB
#### Expected weekly DataCap usage rate 
> 200TiB 
#### Client address
> f1ffr7uhq7mszotfdybexcnl4i7xw5tqyp5fhqy3y

**Comment by MRJAVAZHAO** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceci4plujikr75fn7pwxkd6f5aiyscyn57wuspf5jyomodrcnalux2 
#### Address 
> f1ffr7uhq7mszotfdybexcnl4i7xw5tqyp5fhqy3y
#### Datacap Allocated
> 256.00TiB
#### Signer Address
> f14gme3f52prtyzk6pblogrdd6b6ivp4swc6qmesi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceci4plujikr75fn7pwxkd6f5aiyscyn57wuspf5jyomodrcnalux2

**Comment by PluskitOfficial** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedoomlqatzn4kxuyvrxu53w3hz6au2id7jvtyeo36ksr5zggwtatu 
#### Address 
> f1ffr7uhq7mszotfdybexcnl4i7xw5tqyp5fhqy3y
#### Datacap Allocated
> 256.00TiB
#### Signer Address
> f1tgnlhtcmhwipfm7thsftxhn5k52velyjlazpvka
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedoomlqatzn4kxuyvrxu53w3hz6au2id7jvtyeo36ksr5zggwtatu

**Comment by kevzak** [comment]
Hello @David-MyTrade - I'm Kevin from the Client Success Team. I saw you were recently granted DataCap and began onboarding data. I wanted to reach out as you getting started to offer any support as needed. Let me know if you have any questions or issues.

Also, feel free to post a message in #fil-plus slack channel. Thank you!

**Comment by David-MyTrade** [comment]
@kevzak Thanks Kevin!

**Comment by MetaWaveInfo** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebbtc6so7alwvrzfnyjmrknymvjwp73kjju7kvtmalpkmrrmhkvko 
#### Address 
> f1ffr7uhq7mszotfdybexcnl4i7xw5tqyp5fhqy3y
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f1ktlkcxnmzxcdaoqfsunrg3vocfbmgv4n3mrn74a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebbtc6so7alwvrzfnyjmrknymvjwp73kjju7kvtmalpkmrrmhkvko

**Comment by PluskitOfficial** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced4mpl2hon75xnvyoueykhlz4paws6j2iwn5d4feaj2cahyk3ngbg 
#### Address 
> f1ffr7uhq7mszotfdybexcnl4i7xw5tqyp5fhqy3y
#### Datacap Allocated
> 1.00PiB
#### Signer Address
> f1tgnlhtcmhwipfm7thsftxhn5k52velyjlazpvka
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced4mpl2hon75xnvyoueykhlz4paws6j2iwn5d4feaj2cahyk3ngbg

**Comment by MatrixStorage** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedtvbe6ya472c6x5hscryv2ghz5td4c5j65sjhvacivmr34jxzn6i 
#### Address 
> f1ffr7uhq7mszotfdybexcnl4i7xw5tqyp5fhqy3y
#### Datacap Allocated
> 1.00PiB
#### Signer Address
> f1tbxqwjxfyv7swsdin4einirlsfquv3vnmlapley
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedtvbe6ya472c6x5hscryv2ghz5td4c5j65sjhvacivmr34jxzn6i

**Comment by BigD-Exchange** [comment]
@David-MyTrade Hi! Great to see you have gotten approval for DataCap. If you are looking for storage providers to store these data, please visit #bigdata-exchange on Filecoin Slack or reply here.

**Comment by 1475Notary** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceacwlshanncdmhskttj5sa5rrvvq4nkqeruaavpu6egbae76stz4i 
#### Address 
> f1ffr7uhq7mszotfdybexcnl4i7xw5tqyp5fhqy3y
#### Datacap Allocated
> 2.00PiB
#### Signer Address
> f1ofq4mngy7ggcp755pfquq2gphjjnlydolf6awtq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceacwlshanncdmhskttj5sa5rrvvq4nkqeruaavpu6egbae76stz4i

**Comment by UnionLabs2020** [comment]
bafy2bzaceayxla6cyhr4hcbmpdzoewemgzketwmhtvjkam3wyxhlyo4jbjs6e

System error occurred, approved manually.

**Comment by 1475Notary** [comment]
Proposed as: bafy2bzacedkwlmkplts5fduqzqn3754r4wehrjm37ppw5u3gmin74ibovu64u

**Comment by BlockMakeronline** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecjd43s6facptpnbphcebb2myc7kpsa3rli7wfbq5j7c5a557m53i 
#### Address 
> f1ffr7uhq7mszotfdybexcnl4i7xw5tqyp5fhqy3y
#### Datacap Allocated
> 1.25PiB
#### Signer Address
> f1o3twrcpwjtpcd4q36lpq4qmy2qfbgtyy5h6tsty
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecjd43s6facptpnbphcebb2myc7kpsa3rli7wfbq5j7c5a557m53i

**Comment by MRJAVAZHAO** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecqcyawgsqnxopgp53qq4aac3wkjuyuzcpnp7xkp4r36m7cbadmxi 
#### Address 
> f1ffr7uhq7mszotfdybexcnl4i7xw5tqyp5fhqy3y
#### Datacap Allocated
> 1.25PiB
#### Signer Address
> f14gme3f52prtyzk6pblogrdd6b6ivp4swc6qmesi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecqcyawgsqnxopgp53qq4aac3wkjuyuzcpnp7xkp4r36m7cbadmxi

**Comment by filplus-checker** [comment]
## DataCap and CID Checker Report[^1]
 - Organization: `MyTrade Technology Limited`
 - Client: `f1ffr7uhq7mszotfdybexcnl4i7xw5tqyp5fhqy3y`
### Storage Provider Distribution
The below table shows the distribution of storage providers that have stored data for this client.

If this is the first time a provider takes verified deal, it will be marked as `new`.

For most of the datacap application, below restrictions should apply.
 - Storage provider should not exceed 25% of total datacap.
 - Storage provider should not be storing duplicate data for more than 20%.
 - Storage provider should have published its public IP address.
 - All storage providers should be located in different regions.

⚠️ 30.16% of total deal sealed by [f01889046](https://filfox.info/en/address/f01889046) are duplicate data.

⚠️ 73.99% of total deal sealed by [f01895778](https://filfox.info/en/address/f01895778) are duplicate data.

⚠️ 83.49% of total deal sealed by [f01880896](https://filfox.info/en/address/f01880896) are duplicate data.

⚠️ 75.89% of total deal sealed by [f01845679](https://filfox.info/en/address/f01845679) are duplicate data.

⚠️ [f01845679](https://filfox.info/en/address/f01845679) has unknown IP location.

⚠️ 84.59% of total deal sealed by [f01879880](https://filfox.info/en/address/f01879880) are duplicate data.

⚠️ 84.96% of total deal sealed by [f01880894](https://filfox.info/en/address/f01880894) are duplicate data.

⚠️ 89.67% of total deal sealed by [f01885260](https://filfox.info/en/address/f01885260) are duplicate data.

⚠️ 57.86% of total deal sealed by [f01885280](https://filfox.info/en/address/f01885280) are duplicate data.

⚠️ 78.92% of total deal sealed by [f01868890](https://filfox.info/en/address/f01868890) are duplicate data.

⚠️ 52.90% of total deal sealed by [f01880898](https://filfox.info/en/address/f01880898) are duplicate data.

| Provider                                                    |                           Location | Total Deals Sealed | Percentage | Unique Data | Duplicate Deals |
| :---------------------------------------------------------- | ---------------------------------: | -----------------: | ---------: | ----------: | --------------: |
| [f01893290](https://filfox.info/en/address/f01893290)       |           Singapore, Singapore, SG |         443.81 TiB |     11.56% |  391.44 TiB |          11.80% |
| [f01896469](https://filfox.info/en/address/f01896469)       |           Singapore, Singapore, SG |         436.78 TiB |     11.38% |  400.38 TiB |           8.34% |
| [f01895891](https://filfox.info/en/address/f01895891)       |           Singapore, Singapore, SG |         434.28 TiB |     11.31% |  396.78 TiB |           8.63% |
| [f01895928](https://filfox.info/en/address/f01895928)       |           Singapore, Singapore, SG |         381.88 TiB |      9.95% |  381.88 TiB |           0.00% |
| [f01889046](https://filfox.info/en/address/f01889046)       |              Ashburn, Virginia, US |         351.81 TiB |      9.17% |  245.72 TiB |          30.16% |
| [f01895778](https://filfox.info/en/address/f01895778)       |           Singapore, Singapore, SG |         350.88 TiB |      9.14% |   91.25 TiB |          73.99% |
| [f01895707](https://filfox.info/en/address/f01895707)       |           Singapore, Singapore, SG |         344.00 TiB |      8.96% |  281.91 TiB |          18.05% |
| [f01889480](https://filfox.info/en/address/f01889480)       |               Boardman, Oregon, US |         226.81 TiB |      5.91% |  226.81 TiB |           0.00% |
| [f01880896](https://filfox.info/en/address/f01880896)       |           Singapore, Singapore, SG |         163.16 TiB |      4.25% |   26.94 TiB |          83.49% |
| [f01845679](https://filfox.info/en/address/f01845679)       |                            Unknown |         145.69 TiB |      3.80% |   35.13 TiB |          75.89% |
| [f01879880](https://filfox.info/en/address/f01879880)       |           Singapore, Singapore, SG |         128.00 TiB |      3.33% |   19.72 TiB |          84.59% |
| [f01880894](https://filfox.info/en/address/f01880894)       |           Singapore, Singapore, SG |         127.78 TiB |      3.33% |   19.22 TiB |          84.96% |
| [f01885260](https://filfox.info/en/address/f01885260)`new`  | Hong Kong, Central and Western, HK |          85.31 TiB |      2.22% |    8.81 TiB |          89.67% |
| [f01885280](https://filfox.info/en/address/f01885280)       | Hong Kong, Central and Western, HK |          61.63 TiB |      1.61% |   25.97 TiB |          57.86% |
| [f01868890](https://filfox.info/en/address/f01868890)       |               Boardman, Oregon, US |          43.00 TiB |      1.12% |    9.06 TiB |          78.92% |
| [f01900713](https://filfox.info/en/address/f01900713)       |                   Seoul, Seoul, KR |          32.00 TiB |      0.83% |   32.00 TiB |           0.00% |
| [f01895715](https://filfox.info/en/address/f01895715)       |                   Seoul, Seoul, KR |          31.22 TiB |      0.81% |   31.22 TiB |           0.00% |
| [f01916487](https://filfox.info/en/address/f01916487)       |                   Seoul, Seoul, KR |          30.56 TiB |      0.80% |   30.56 TiB |           0.00% |
| [f01880898](https://filfox.info/en/address/f01880898)       |           Singapore, Singapore, SG |          19.97 TiB |      0.52% |    9.41 TiB |          52.90% |

![Provider Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/386/1671096511544.png)
### Deal Data Replication
The below table shows how each many unique data are replicated across storage providers.
- No more than 25% of unique data are stored with less than 4 providers.

⚠️ 94.74% of deals are for data replicated across less than 4 storage providers.

| Unique Data Size | Total Deals Made | Number of Providers | Deal Percentage |
| ---------------: | ---------------: | ------------------: | --------------: |
|         2.42 PiB |         3.30 PiB |                   1 |          87.97% |
|         5.41 TiB |        24.47 TiB |                   2 |           0.64% |
|        27.72 TiB |       235.53 TiB |                   3 |           6.14% |
|        17.19 TiB |       147.13 TiB |                   4 |           3.83% |
|         5.47 TiB |        54.63 TiB |                   5 |           1.42% |

![Replication Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/386/1671096512175.png)
### Deal Data Shared with other Clients
The below table shows how many unique data are shared with other clients.
Usually different applications owns different data and should not resolve to the same CID.

⚠️ CID sharing has been observed.

| Other Client                                                                                                                                                                                                              | Application                                                                                          | Total Deals Affected | Unique CIDs |        Verifier |
| :------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ | :--------------------------------------------------------------------------------------------------- | -------------------: | ----------: | --------------: |
| [f1tgii4xgcp6um4n2w7eqaw6bwvnvyii2u7cjgzka](https://filfox.info/en/address/f1tgii4xgcp6um4n2w7eqaw6bwvnvyii2u7cjgzka)                                                                                                     | [Meson\.Network ](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/187)       |           444.16 TiB |       2,472 | LDN v3 multisig |
| [f1727w2vwjctfo7hflr5trgqkl3c7texh7pl4grzq](https://filfox.info/en/address/f1727w2vwjctfo7hflr5trgqkl3c7texh7pl4grzq)                                                                                                     | [GMverse](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/365)               |           122.84 TiB |       1,486 | LDN v3 multisig |
| [f1dpgqn57cl5wqijiyv3256nids2ox3fms2mg3oay](https://filfox.info/en/address/f1dpgqn57cl5wqijiyv3256nids2ox3fms2mg3oay)                                                                                                     | [All Blue](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/389)              |           109.78 TiB |       1,013 | LDN v3 multisig |
| [f1zb6pgkktdbyy7zxfob6gripqxuc25ukf35cc7fq](https://filfox.info/en/address/f1zb6pgkktdbyy7zxfob6gripqxuc25ukf35cc7fq)                                                                                                     | `Maxpic PhotoGraphic Studio`                                                                         |            90.03 TiB |         808 | LDN v3 multisig |
| [f1u522dt3zabkgbxxzecl77wgv473yvpecxh6t6zq](https://filfox.info/en/address/f1u522dt3zabkgbxxzecl77wgv473yvpecxh6t6zq)                                                                                                     | [Huifan livestream](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/407)     |            79.19 TiB |         618 | LDN v3 multisig |
| [f1hik4fc3wvck2jchtufrnfnzmmskw2nyezlbsr3q](https://filfox.info/en/address/f1hik4fc3wvck2jchtufrnfnzmmskw2nyezlbsr3q)                                                                                                     | [NFTSCAN](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/350)               |            57.31 TiB |         404 | LDN v3 multisig |
| [f1muygjb5zowppbhr7wnmdreqdoiyyanfm7fe54dy](https://filfox.info/en/address/f1muygjb5zowppbhr7wnmdreqdoiyyanfm7fe54dy)                                                                                                     | [MappingFunk Protocol ](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/374) |            45.66 TiB |         495 | LDN v3 multisig |
| [f1ki4cjk27ypzjsuzkvvqzs6xobaweuoxfdcnpqhy](https://filfox.info/en/address/f1ki4cjk27ypzjsuzkvvqzs6xobaweuoxfdcnpqhy)                                                                                                     | [TimeQuant](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/385)             |            45.41 TiB |         853 | LDN v3 multisig |
| [f14abwn2goturifmt27s2bssoe3fup2b3npkgfzui](https://filfox.info/en/address/f14abwn2goturifmt27s2bssoe3fup2b3npkgfzui)                                                                                                     | [KONGFU VR](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/372)             |            35.81 TiB |         293 | LDN v3 multisig |
| [f1ivsvpljx4ovp2tth73pllkxmumrudemks623iia](https://filfox.info/en/address/f1ivsvpljx4ovp2tth73pllkxmumrudemks623iia)                                                                                                     | `TIS Inc. group`                                                                                     |            22.38 TiB |         183 | LDN v3 multisig |
| [f1clwd2dooy2cflfilhzeq2ycl544b3heqsiwhjrq](https://filfox.info/en/address/f1clwd2dooy2cflfilhzeq2ycl544b3heqsiwhjrq)                                                                                                     | [FiboAI](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/349)                |            19.06 TiB |         346 | LDN v3 multisig |
| [f3q7ablez3jqkcjukwbzaql7lmbx4ldouu66nexpd<br/>cfvu6kgho3v6gricckt77cgr46tdre2l4zmvha7bs<br/>u7qq](https://filfox.info/en/address/f3q7ablez3jqkcjukwbzaql7lmbx4ldouu66nexpdcfvu6kgho3v6gricckt77cgr46tdre2l4zmvha7bsu7qq) | `MatrixStorage`                                                                                      |             7.94 TiB |         135 |        LDN # 72 |
| [f1ojo3wo24zkeovndlxfpqmlgzlbysg5fiukmup4a](https://filfox.info/en/address/f1ojo3wo24zkeovndlxfpqmlgzlbysg5fiukmup4a)                                                                                                     | `Titansoft`                                                                                          |             5.19 TiB |          23 | LDN v3 multisig |
| [f3skkellc7wegakh2blqeu4kkrlzuqy2siymwli7s<br/>ec6eq77c2v4kzgz5ozgnasjl5r52ckameba5kds7h<br/>djda](https://filfox.info/en/address/f3skkellc7wegakh2blqeu4kkrlzuqy2siymwli7sec6eq77c2v4kzgz5ozgnasjl5r52ckameba5kds7hdjda) | [Meizhai Technology](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/75)     |             4.81 TiB |          99 | LDN v3 multisig |
| [f1tivtdkq34mnfzso63wrr2xh6r2zo7aebao4jfla](https://filfox.info/en/address/f1tivtdkq34mnfzso63wrr2xh6r2zo7aebao4jfla)                                                                                                     | `China travel service(HongKong) limited`                                                             |             3.13 TiB |          21 | LDN v3 multisig |
| [f3woqxpu6ekmj43nmpcv7j2pgu6lejxtzgxpzl6f2<br/>vrueoqlzjntakyhdkghymyffbzfbsio6dvfmy643x<br/>4y7q](https://filfox.info/en/address/f3woqxpu6ekmj43nmpcv7j2pgu6lejxtzgxpzl6f2vrueoqlzjntakyhdkghymyffbzfbsio6dvfmy643x4y7q) | [RICH ST PETE LLC](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/64)       |             1.88 TiB |          24 | LDN v3 multisig |
| [f1qjrlejxv5a73kxurwtxyrni6ji7orm74zeeetiy](https://filfox.info/en/address/f1qjrlejxv5a73kxurwtxyrni6ji7orm74zeeetiy)                                                                                                     | [Mooc](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/223)                  |           512.00 GiB |           9 | LDN v3 multisig |
| [f1yswits4hd4zu6n2pl7nk7cspcuieuzl7btjn5ia](https://filfox.info/en/address/f1yswits4hd4zu6n2pl7nk7cspcuieuzl7btjn5ia)                                                                                                     | [TaoPaiPai](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/54)              |           448.00 GiB |           6 |        LDN # 54 |
| [f1bb2z36lpq3pnwiiowiraagpzqnpow4bonjacx7a](https://filfox.info/en/address/f1bb2z36lpq3pnwiiowiraagpzqnpow4bonjacx7a)                                                                                                     | [Hola Space](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/362)            |           224.00 GiB |           4 | LDN v3 multisig |
| [f1dx7ljly4vmk5x2bn5ng4jpbqnuvozrz2phw42qy](https://filfox.info/en/address/f1dx7ljly4vmk5x2bn5ng4jpbqnuvozrz2phw42qy)                                                                                                     | [CoinPhD](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/364)               |           128.00 GiB |           4 | LDN v3 multisig |

[^1]: To manually trigger this report, add a comment with text `checker:manualTrigger`
