### ISSUE TITLE
[DataCap Application]All Blue 

### ISSUE THREAD

**Issue by Pearl918** [filecoin-project/filecoin-plus-large-datasets#389]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: All Blue
- Website / Social Media: www.allblue.finance
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5 PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 300 TiB
- On-chain address for first allocation: f1dpgqn57cl5wqijiyv3256nids2ox3fms2mg3oay

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
All blue solves the problem with traditional banking .We are building credit, savings, and investment products. Democratizing financial services in ways that are equitable and transparent. To redefine people’s relationship with money through simple, accessible credit, personal finance, digital banking offerings, and much more. 
```

What is the primary source of funding for this project?
```
Company's income.
```

What other projects/ecosystem stakeholders is this project associated with?
```
We were the only company involved in the project.
```

## Use-case details

Describe the data being stored onto Filecoin
```
Dataset include Hong Kong stock data, foreign exchange, American stocks, Shanghai and Shenzhen stocks.
```

Where was the data in this dataset sourced from?
```
The data comes from the historical data during 2000 to 2019, including :
1032TiB of Shanghai and Shenzhen stock analysis data, 
223TiB of foreign exchange analysis data, 
10Tib of Hong Kong stock analysis data, 
15TiB of American stock analysis data,
Total 1280TiB data.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
[^GSPC.csv](https://github.com/filecoin-project/filecoin-plus-large-datasets/files/8830450/GSPC.csv)
[^DJI.csv](https://github.com/filecoin-project/filecoin-plus-large-datasets/files/8830451/DJI.csv)
[AAPL.csv](https://github.com/filecoin-project/filecoin-plus-large-datasets/files/8830452/AAPL.csv)
[^IXIC.csv](https://github.com/filecoin-project/filecoin-plus-large-datasets/files/8830462/IXIC.csv)
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes, we confirm!
```

What is the expected retrieval frequency for this data?
```
Data retrieval has no fixed frequency, depending on the needs of the applications or customers.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
We plan to keep this dataset on Filecoin 2-3 years. 
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
China and Asia-GCN.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Online transfer and offline copy.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We plan to select multiple storage vendors (4-8) and request them open for retrieval.
1) SH and SZ stock analysis data in China.
2) Foreign exchange, Hong Kong stock, American stock analysis data in Asia -GCN.
```

How will you be distributing deals across storage providers?
```
No single SPs can make deals more than 20%. 
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, we have the resources/funding to begin making deals .
```

**Comment by Pearl918** [comment]
Please accelerate the progress of this issue! @galen-mcandrew

**Comment by Pearl918** [comment]
Is no one care about my issue?

**Comment by Pearl918** [comment]
Does no one care about my issue?

**Comment by EGGRICE02** [comment]
@Pearl918 Hey. Could you send an email to filplus@fil.org with your official domain in order to confirm your identity?

**Comment by Sunnyiscoming** [comment]
@Pearl918  Hey. Could you send an email to filplus@fil.org with your official domain in order to confirm your identity?

**Comment by Sunnyiscoming** [comment]
@Pearl918 Hey. Could you send an email to [filplus@fil.org](mailto:filplus@fil.org) with your official domain in order to confirm your identity?

**Comment by Pearl918** [comment]
@Sunnyiscoming Yes! You can check it.
![allblue](https://user-images.githubusercontent.com/105973857/176864354-2d8aabcf-87f5-4c71-8ce9-2362f86482a0.jpg)

**Comment by swatchliu** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedosmzmlhoovgyeeidnx7o6bi43vxrrt4g3h4pyfrcj2uam6ud4f6 
#### Address 
> f1dpgqn57cl5wqijiyv3256nids2ox3fms2mg3oay
#### Datacap Allocated
> 150.00TiB
#### Signer Address
> f1yh6q3nmsg7i2sys7f7dexcuajgoweudcqj2chfi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedosmzmlhoovgyeeidnx7o6bi43vxrrt4g3h4pyfrcj2uam6ud4f6

**Comment by MatrixStorage** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceczyluaayzymklkyrjn3iuprvgowk4duvnyws4ym5lhtcamwpuan2 
#### Address 
> f1dpgqn57cl5wqijiyv3256nids2ox3fms2mg3oay
#### Datacap Allocated
> 150.00TiB
#### Signer Address
> f1tbxqwjxfyv7swsdin4einirlsfquv3vnmlapley
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceczyluaayzymklkyrjn3iuprvgowk4duvnyws4ym5lhtcamwpuan2

**Comment by swatchliu** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecvqwi6qnjwopcprqi244bytfwgzmejdw2oyqvfpqvzb6sbssjesw 
#### Address 
> f1dpgqn57cl5wqijiyv3256nids2ox3fms2mg3oay
#### Datacap Allocated
> 300.00TiB
#### Signer Address
> f1yh6q3nmsg7i2sys7f7dexcuajgoweudcqj2chfi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecvqwi6qnjwopcprqi244bytfwgzmejdw2oyqvfpqvzb6sbssjesw

**Comment by UnionLabs2020** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedalqarxsihqoqirf5ancnbzpvg57mrllkwsyttyiqje34nuaoie6 
#### Address 
> f1dpgqn57cl5wqijiyv3256nids2ox3fms2mg3oay
#### Datacap Allocated
> 300.00TiB
#### Signer Address
> f17xdri3wunqgld7dm23e4f3eqsntjakwc47xjo6i
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedalqarxsihqoqirf5ancnbzpvg57mrllkwsyttyiqje34nuaoie6

**Comment by galen-mcandrew** [comment]
@swatchliu Looks like you signed both the first and second allocation requests. I understand it can get hard to keep track of all the amazing projects!

Reminder to all notaries: please do not sign immediately subsequent allocations, so that other notaries can help review and add their expertise. So in this case, for allocation number 3: @UnionLabs2020 & @swatchliu should not propose/approve this specific request.

Thanks!

**Comment by MatrixStorage** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecice5khgwqjz44kgfeyc2z7sducpddykc4qxfdoxk7kmhl4nr3dk 
#### Address 
> f1dpgqn57cl5wqijiyv3256nids2ox3fms2mg3oay
#### Datacap Allocated
> 600.00TiB
#### Signer Address
> f1tbxqwjxfyv7swsdin4einirlsfquv3vnmlapley
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecice5khgwqjz44kgfeyc2z7sducpddykc4qxfdoxk7kmhl4nr3dk

**Comment by raghavrmadya** [comment]
<img width="998" alt="Screen Shot 2022-08-03 at 8 42 26 PM" src="https://user-images.githubusercontent.com/91579519/182758509-4503a8a8-f539-464f-9a6b-fbfe8ea523cd.png">

Hi, can you please share more about your relationship with MainNet Capital?

**Comment by raghavrmadya** [comment]
Also I see that there is another application open for the same data - https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/355

**Comment by Pearl918** [comment]
Hi @raghavrmadya , we just share a common office space with this MainNet Capital, but we don't know exactly who they are.

**Comment by BigD-Exchange** [comment]
@Pearl918 Hi! Great to see you have gotten approval for DataCap. If you are looking for storage providers to store these data, please visit #bigdata-exchange on Filecoin Slack or reply here.

**Comment by raghavrmadya** [comment]
Needs diligence. Removing the labels to pause the next allocation.

**Comment by Pearl918** [comment]
@raghavrmadya Hello,  can you please tell us why you think we need dilligence? We'd love to cooperate with your request.

**Comment by raghavrmadya** [comment]
Several community members have reached out and pointed out anomalies such the image source on the header (image one) it’s obvious it is a rip-off of UI mocks from another app (looks like it’s called keeper)

<img width="388" alt="Screen Shot 2022-08-22 at 8 32 50 AM" src="https://user-images.githubusercontent.com/91579519/185960383-7d84d352-2629-49e9-917f-983e013ce97f.png">
<img width="702" alt="Screen Shot 2022-08-22 at 8 32 38 AM" src="https://user-images.githubusercontent.com/91579519/185960393-10a3f31b-e255-4b2c-9c53-5085a39bc131.png">
.

**Comment by raghavrmadya** [comment]
@swatchliu @BlockMakeronline , flagging for your review as well.

**Comment by Pearl918** [comment]
@raghavrmadya 
I think there is some misunderstanding here. Our website is currently in the process of being upgraded, so what you see is a transitional template used by the website creator. (Here's the link. https://zh.wix.com/website-template/view/html/2105?originUrl=https%3A%2F%2Fzh.wix.com%2Fwebsite%2Ftemplates%2Fhtml%2Fbusiness%2Ffinance-law&tpClick=view_button&esi=898e1e58-3bca-4c1c-b9dd-e92961bc560a) It is normal for many companies to use the same template. Also, our application is in the process of being upgraded and the beta version is only available for download via Apple's test flight. I can also provide our business license for review. I will send you our company information and business license by email.

**Comment by MetaWaveInfo** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebvhqmai2efhauixdo53svuzqtzbgxd36xh27amhoy65hjb7evxow 
#### Address 
> f1dpgqn57cl5wqijiyv3256nids2ox3fms2mg3oay
#### Datacap Allocated
> 2.34PiB
#### Signer Address
> f1ktlkcxnmzxcdaoqfsunrg3vocfbmgv4n3mrn74a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebvhqmai2efhauixdo53svuzqtzbgxd36xh27amhoy65hjb7evxow

**Comment by 1475Notary** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceagbvflkcxhohuzvtreb5l6t5kc77ucz2kcug2bgylph5hutsfauo 
#### Address 
> f1dpgqn57cl5wqijiyv3256nids2ox3fms2mg3oay
#### Datacap Allocated
> 2.34PiB
#### Signer Address
> f1ofq4mngy7ggcp755pfquq2gphjjnlydolf6awtq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceagbvflkcxhohuzvtreb5l6t5kc77ucz2kcug2bgylph5hutsfauo

**Comment by raghavrmadya** [comment]
@MetaWaveInfo @1475Notary , can you share context as to why you were comfortable signing this application? A few community members including myself raised a flag and would appreciate any additional information you have that I don't which led to singing of this application. 

Thanks

**Comment by Pearl918** [comment]
Thanks @raghavrmadya , I think that my previous reply was clear enough to explain everything and notaries have their own judgements. In web3, we should let different opinions be created, rather than having the power in the hands of one person!

**Comment by raghavrmadya** [comment]
@Pearl918 , thank you for your comment. As a community member, I have every right to question anyone's judgment. This is not power in one hands. @MetaWaveInfo @1475Notary , still waiting for your response.

**Comment by MetaWaveInfo** [comment]
OK, thank RG. We have completed our due diligence on this client and checked their company certificate. It looks normal and real. We can forward it to you if needed.

**Comment by 1475Notary** [comment]
Hi @raghavrmadya , I have seen the shareholders of this company last month, which can confirm that all blue is a real company in Singapore. As for the icons and pictures similar to other applications on the data sample, I think the applicant has given an explanation,  so we are willing to sign it.  Thanks!

**Comment by UnionLabs2020** [comment]
Hi @Pearl918  Could you kindly share your rootcids?  We ‘d like to verify that dataset can be retrieved before we do the next action. Thanks.

**Comment by Pearl918** [comment]
bafybeicucb5y3m4k4ehih3zjnllnbwgjn33fqnsm6tfrpr2aim7p6lxaoi
bafybeiduyj223y6gc6pt4x6jplbcnoy4ufyauoyl6m5z3q5hssfnk5sdtu
bafybeig22kxdg4ww2pg6bqqagbvohsbsquen5q5yhrsekd3zqmnmhiyokq
bafybeiejx5pgoy3usmtiesq655pef7gtb7qliqrsnlsgolpvqngudr4mty
bafybeidi2oggcamz3r6gaa7bnqtrycqmolbpo63klcimedqcfev6y3tupm
bafybeihevoaudso6w56yhxna7rgqyyob3zzf4bk4hiok7fn35s27zt5m3y
bafybeiekkfdli7ejg47fgnk637sxc4kqvzvluaubilmbhdfmtb5p4pzkdq
bafybeifseeexaurnyh7kh2mtgbsjnhqit4xo3wocxg3trp6cco27e333ne
bafybeidmfqam36joxpfswhkwy5za6wouabjo2rrj7jfy43vzmpiklzaj5m
bafybeigzvaiglbwbspnbi3lbhlolsv24yh65jfxtump5sfvm7wir37ypqa
bafybeidvf4uzhnts3pg6d2kwmlwwtnsjf7u4o76dcsy45yjpbt67kcm7g4
bafybeig2shiul4r2uzhquhagwbbfuigujo5o3jbkvyem3khuihqhuwteqm
bafybeigsrtybkfhpyviyjdjpmkl32xexzp7voukimdma2yqi7dvdkbaf4m

@UnionLabs2020 Welcome to retrieve my dataset! If need, I can share more rootcids with you.

**Comment by UnionLabs2020** [comment]
![image](https://user-images.githubusercontent.com/101703888/193006102-7c5ccbfd-f971-448c-80b2-e0dd10c6fbb6.png)

Thanks for your sharing.

**Comment by UnionLabs2020** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacea5r4fqpdddjfqka4x4brzvzwzbx5oebabceggd7zurw5jgxx5zyk 
#### Address 
> f1dpgqn57cl5wqijiyv3256nids2ox3fms2mg3oay
#### Datacap Allocated
> 1.63PiB
#### Signer Address
> f17xdri3wunqgld7dm23e4f3eqsntjakwc47xjo6i
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacea5r4fqpdddjfqka4x4brzvzwzbx5oebabceggd7zurw5jgxx5zyk

**Comment by swatchliu** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaovnlirpmmbc53qor3uuqh7avk2l5cwkqqm6itdkzw6jmqhlicwq 
#### Address 
> f1dpgqn57cl5wqijiyv3256nids2ox3fms2mg3oay
#### Datacap Allocated
> 1.63PiB
#### Signer Address
> f1yh6q3nmsg7i2sys7f7dexcuajgoweudcqj2chfi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaovnlirpmmbc53qor3uuqh7avk2l5cwkqqm6itdkzw6jmqhlicwq

**Comment by filplus-checker** [comment]
## DataCap and CID Checker Report[^1]
 - Organization: `All Blue`
 - Client: `f1dpgqn57cl5wqijiyv3256nids2ox3fms2mg3oay`
### Storage Provider Distribution
The below table shows the distribution of storage providers that have stored data for this client.

If this is the first time a provider takes verified deal, it will be marked as `new`.

For most of the datacap application, below restrictions should apply.
 - Storage provider should not exceed 25% of total datacap.
 - Storage provider should not be storing duplicate data for more than 20%.
 - Storage provider should have published its public IP address.
 - All storage providers should be located in different regions.

⚠️ 66.37% of total deal sealed by [f01880897](https://filfox.info/en/address/f01880897) are duplicate data.

⚠️ 74.02% of total deal sealed by [f01880894](https://filfox.info/en/address/f01880894) are duplicate data.

⚠️ 78.62% of total deal sealed by [f01880896](https://filfox.info/en/address/f01880896) are duplicate data.

⚠️ 84.20% of total deal sealed by [f01885260](https://filfox.info/en/address/f01885260) are duplicate data.

⚠️ 79.33% of total deal sealed by [f01879880](https://filfox.info/en/address/f01879880) are duplicate data.

⚠️ 60.88% of total deal sealed by [f01885280](https://filfox.info/en/address/f01885280) are duplicate data.

⚠️ 76.08% of total deal sealed by [f01845679](https://filfox.info/en/address/f01845679) are duplicate data.

⚠️ [f01845679](https://filfox.info/en/address/f01845679) has unknown IP location.

| Provider                                              |                           Location | Total Deals Sealed | Percentage | Unique Data | Duplicate Deals |
| :---------------------------------------------------- | ---------------------------------: | -----------------: | ---------: | ----------: | --------------: |
| [f01917257](https://filfox.info/en/address/f01917257) |                   Seoul, Seoul, KR |         301.00 TiB |      8.74% |  301.00 TiB |           0.00% |
| [f01917214](https://filfox.info/en/address/f01917214) |                   Seoul, Seoul, KR |         300.00 TiB |      8.72% |  300.00 TiB |           0.00% |
| [f01916487](https://filfox.info/en/address/f01916487) |                   Seoul, Seoul, KR |         299.97 TiB |      8.71% |  299.97 TiB |           0.00% |
| [f01917208](https://filfox.info/en/address/f01917208) |                   Seoul, Seoul, KR |         299.97 TiB |      8.71% |  299.97 TiB |           0.00% |
| [f01900713](https://filfox.info/en/address/f01900713) |                   Seoul, Seoul, KR |         299.91 TiB |      8.71% |  299.91 TiB |           0.00% |
| [f01895715](https://filfox.info/en/address/f01895715) |                   Seoul, Seoul, KR |         299.78 TiB |      8.71% |  299.78 TiB |           0.00% |
| [f01917236](https://filfox.info/en/address/f01917236) |                   Seoul, Seoul, KR |         298.91 TiB |      8.68% |  298.91 TiB |           0.00% |
| [f01917241](https://filfox.info/en/address/f01917241) |                   Seoul, Seoul, KR |         297.72 TiB |      8.65% |  297.72 TiB |           0.00% |
| [f01895891](https://filfox.info/en/address/f01895891) |           Singapore, Singapore, SG |         122.97 TiB |      3.57% |  122.97 TiB |           0.00% |
| [f01895928](https://filfox.info/en/address/f01895928) |           Singapore, Singapore, SG |         122.97 TiB |      3.57% |  122.97 TiB |           0.00% |
| [f01896469](https://filfox.info/en/address/f01896469) |           Singapore, Singapore, SG |         122.97 TiB |      3.57% |  122.97 TiB |           0.00% |
| [f01893290](https://filfox.info/en/address/f01893290) |           Singapore, Singapore, SG |         122.78 TiB |      3.57% |  122.78 TiB |           0.00% |
| [f01880897](https://filfox.info/en/address/f01880897) |           Singapore, Singapore, SG |         109.94 TiB |      3.19% |   36.97 TiB |          66.37% |
| [f01880894](https://filfox.info/en/address/f01880894) |           Singapore, Singapore, SG |         109.56 TiB |      3.18% |   28.47 TiB |          74.02% |
| [f01880896](https://filfox.info/en/address/f01880896) |           Singapore, Singapore, SG |          94.44 TiB |      2.74% |   20.19 TiB |          78.62% |
| [f01885260](https://filfox.info/en/address/f01885260) | Hong Kong, Central and Western, HK |          93.38 TiB |      2.71% |   14.75 TiB |          84.20% |
| [f01879880](https://filfox.info/en/address/f01879880) |           Singapore, Singapore, SG |          59.88 TiB |      1.74% |   12.38 TiB |          79.33% |
| [f01885280](https://filfox.info/en/address/f01885280) | Hong Kong, Central and Western, HK |          49.84 TiB |      1.45% |   19.50 TiB |          60.88% |
| [f01845679](https://filfox.info/en/address/f01845679) |                            Unknown |          36.06 TiB |      1.05% |    8.63 TiB |          76.08% |

![Provider Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/389/1671096576598.png)
### Deal Data Replication
The below table shows how each many unique data are replicated across storage providers.
- No more than 25% of unique data are stored with less than 4 providers.

⚠️ 100.00% of deals are for data replicated across less than 4 storage providers.

| Unique Data Size | Total Deals Made | Number of Providers | Deal Percentage |
| ---------------: | ---------------: | ------------------: | --------------: |
|         2.94 PiB |         3.30 PiB |                   1 |          98.20% |
|         7.88 TiB |        62.09 TiB |                   2 |           1.80% |

![Replication Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/389/1671096577360.png)
### Deal Data Shared with other Clients
The below table shows how many unique data are shared with other clients.
Usually different applications owns different data and should not resolve to the same CID.

⚠️ CID sharing has been observed.

| Other Client                                                                                                                                                                                                              | Application                                                                                                     | Total Deals Affected | Unique CIDs |        Verifier |
| :------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ | :-------------------------------------------------------------------------------------------------------------- | -------------------: | ----------: | --------------: |
| [f1ki4cjk27ypzjsuzkvvqzs6xobaweuoxfdcnpqhy](https://filfox.info/en/address/f1ki4cjk27ypzjsuzkvvqzs6xobaweuoxfdcnpqhy)                                                                                                     | [TimeQuant](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/385)                        |           149.56 TiB |       1,630 | LDN v3 multisig |
| [f1ffr7uhq7mszotfdybexcnl4i7xw5tqyp5fhqy3y](https://filfox.info/en/address/f1ffr7uhq7mszotfdybexcnl4i7xw5tqyp5fhqy3y)                                                                                                     | [MyTrade Technology Limited](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/386)       |           135.84 TiB |       1,013 | LDN v3 multisig |
| [f1tgii4xgcp6um4n2w7eqaw6bwvnvyii2u7cjgzka](https://filfox.info/en/address/f1tgii4xgcp6um4n2w7eqaw6bwvnvyii2u7cjgzka)                                                                                                     | [Meson\.Network ](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/187)                  |           111.72 TiB |         753 | LDN v3 multisig |
| [f1gs5xe26fkplu64mwcfq5fswycp3qucuvzbg2lia](https://filfox.info/en/address/f1gs5xe26fkplu64mwcfq5fswycp3qucuvzbg2lia)                                                                                                     | [Migu Culture Technology Co\., Ltd](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/63) |            77.25 TiB |         579 |        LDN # 63 |
| [f1hik4fc3wvck2jchtufrnfnzmmskw2nyezlbsr3q](https://filfox.info/en/address/f1hik4fc3wvck2jchtufrnfnzmmskw2nyezlbsr3q)                                                                                                     | [NFTSCAN](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/350)                          |            66.28 TiB |         499 | LDN v3 multisig |
| [f3q7ablez3jqkcjukwbzaql7lmbx4ldouu66nexpd<br/>cfvu6kgho3v6gricckt77cgr46tdre2l4zmvha7bs<br/>u7qq](https://filfox.info/en/address/f3q7ablez3jqkcjukwbzaql7lmbx4ldouu66nexpdcfvu6kgho3v6gricckt77cgr46tdre2l4zmvha7bsu7qq) | `MatrixStorage`                                                                                                 |            48.50 TiB |         656 |        LDN # 72 |
| [f3skkellc7wegakh2blqeu4kkrlzuqy2siymwli7s<br/>ec6eq77c2v4kzgz5ozgnasjl5r52ckameba5kds7h<br/>djda](https://filfox.info/en/address/f3skkellc7wegakh2blqeu4kkrlzuqy2siymwli7sec6eq77c2v4kzgz5ozgnasjl5r52ckameba5kds7hdjda) | [Meizhai Technology](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/75)                |            47.38 TiB |         715 | LDN v3 multisig |
| [f1muygjb5zowppbhr7wnmdreqdoiyyanfm7fe54dy](https://filfox.info/en/address/f1muygjb5zowppbhr7wnmdreqdoiyyanfm7fe54dy)                                                                                                     | [MappingFunk Protocol ](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/374)            |            44.50 TiB |         494 | LDN v3 multisig |
| [f1u522dt3zabkgbxxzecl77wgv473yvpecxh6t6zq](https://filfox.info/en/address/f1u522dt3zabkgbxxzecl77wgv473yvpecxh6t6zq)                                                                                                     | [Huifan livestream](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/407)                |            37.69 TiB |         401 | LDN v3 multisig |
| [f14abwn2goturifmt27s2bssoe3fup2b3npkgfzui](https://filfox.info/en/address/f14abwn2goturifmt27s2bssoe3fup2b3npkgfzui)                                                                                                     | [KONGFU VR](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/372)                        |            35.69 TiB |         256 | LDN v3 multisig |
| [f1clwd2dooy2cflfilhzeq2ycl544b3heqsiwhjrq](https://filfox.info/en/address/f1clwd2dooy2cflfilhzeq2ycl544b3heqsiwhjrq)                                                                                                     | [FiboAI](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/349)                           |            16.41 TiB |         137 | LDN v3 multisig |
| [f3woqxpu6ekmj43nmpcv7j2pgu6lejxtzgxpzl6f2<br/>vrueoqlzjntakyhdkghymyffbzfbsio6dvfmy643x<br/>4y7q](https://filfox.info/en/address/f3woqxpu6ekmj43nmpcv7j2pgu6lejxtzgxpzl6f2vrueoqlzjntakyhdkghymyffbzfbsio6dvfmy643x4y7q) | [RICH ST PETE LLC](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/64)                  |             4.72 TiB |         151 | LDN v3 multisig |
| [f1ivsvpljx4ovp2tth73pllkxmumrudemks623iia](https://filfox.info/en/address/f1ivsvpljx4ovp2tth73pllkxmumrudemks623iia)                                                                                                     | `TIS Inc. group`                                                                                                |             1.72 TiB |          21 | LDN v3 multisig |
| [f1qjrlejxv5a73kxurwtxyrni6ji7orm74zeeetiy](https://filfox.info/en/address/f1qjrlejxv5a73kxurwtxyrni6ji7orm74zeeetiy)                                                                                                     | [Mooc](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/223)                             |           640.00 GiB |           7 | LDN v3 multisig |
| [f1zb6pgkktdbyy7zxfob6gripqxuc25ukf35cc7fq](https://filfox.info/en/address/f1zb6pgkktdbyy7zxfob6gripqxuc25ukf35cc7fq)                                                                                                     | `Maxpic PhotoGraphic Studio`                                                                                    |            64.00 GiB |           2 | LDN v3 multisig |

[^1]: To manually trigger this report, add a comment with text `checker:manualTrigger`

**Comment by kevzak** [comment]
checker:manualTrigger

**Comment by Aaronn85** [comment]
checker:manualTrigge
