### ISSUE TITLE
[DataCap Application] VillageOne Space LLC

### ISSUE THREAD

**Issue by twoopportunity** [filecoin-project/filecoin-plus-large-datasets#39]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: VillageOne Space LLC
- Website / Social Media:https://villageoneart.com/about-villageone-art/;https://www.instagram.com/villageoneart/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 1PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 50TiB
- On-chain address for first allocation: f3rncwz3qo2bwnsrfjc7kq53xr7yi2lctcydtllxozmszndvttou7n565yb6aqssvn4omyf5m7q62qpfmqcbwq
 
## Project details
 
Share a brief history of your project and organization.
```
VillageOneArt, located 594 Broadway Suite701 in SoHo, is an immersive art gallery with co-working space designed for creative minds across communication, fine art, fashion and photography. Seeking to promote individuality and imagination along with artistic expression, VillageOne is a site for diversity, beauty and collaboration to coexist in harmony.
```
 
What is the primary source of funding for this project?
```
We obtain funds mainly through the trade of art works, etc.
```
 
What other projects/ecosystem stakeholders is this project associated with?
```
We use Matrix Storage, a distributed storage platform, for data storage.
```
 
## Use-case details
 
Describe the data being stored onto Filecoin
```
These data are original works of artists, evidence files of copyright protection of works, etc.
```
 
Where was the data in this dataset sourced from?
```
At present, we have signed 512 members, and more than 5000 members have participated in or contributed to creative mind design.
```
 
Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
We have published a variety of samples in our instagram, https://www.instagram.com/villageoneart/.
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Confirmed. We have selected the data that can be made public.
```
 
What is the expected retrieval frequency for this data?
```
Maybe a few times a month.
```
 
For how long do you plan to keep this dataset stored on Filecoin?
```
About 1 year.
```
 
 
## DataCap allocation plan
 
In which geographies (countries, regions) do you plan on making storage deals?
```
We're thinking about working with miners around the world.
```
 
How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
We will distribute the data to the storage provider through an online platform. Offline data transfer process is not excluded.
```
 
How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We plan to select some storage providers who have experience in storing verified data and provide services reliably and stably. 
The online platform is very convenient for data retrieval. If users want to retrieve our data, they can search by using CID. Our stored data will be public.  
```
 
How will you be distributing deals across storage providers?
```
We will use an online trading platform to distribute data to storage providers.
```
 
Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
We have prepared some start-up funds to start making deals.
```

**Comment by swatchliu** [comment]
Count me in if your local notary would like to support you!

**Comment by IreneYoung** [comment]
Sounds good! We would support the storage of artwork.

**Comment by XnMatrixSV** [comment]
Cool. That sounds good.

**Comment by TimWilliams00** [comment]
Sounds good, Count me in please!

**Comment by galen-mcandrew** [comment]
## Multisig Notary requested
#### Total DataCap requested 
> 1PiB
#### Expected weekly DataCap usage rate 
> 50TiB

**Comment by DarnellWashington** [comment]
Count me in.

**Comment by MRJAVAZHAO** [comment]
I think this is a good project.

**Comment by KodaRobotDog** [comment]
Koda are willing to be the lead notary.

**Comment by KodaRobotDog** [comment]
DataCap Allocation requested
Multisig Notary address

> f01325133

Client address

> f3rncwz3qo2bwnsrfjc7kq53xr7yi2lctcydtllxozmszndvttou7n565yb6aqssvn4omyf5m7q62qpfmqcbwq

DataCap allocation requested

> 25TiB

**Comment by MRJAVAZHAO** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceadyhdaspklooami63qq7smeo2sz2mllsrowfckjrouoxzpf27rls 
#### Address 
> f3rncwz3qo2bwnsrfjc7kq53xr7yi2lctcydtllxozmszndvttou7n565yb6aqssvn4omyf5m7q62qpfmqcbwq
#### Datacap Allocated
> 25TiB
#### Signer Address
> f14gme3f52prtyzk6pblogrdd6b6ivp4swc6qmesi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceadyhdaspklooami63qq7smeo2sz2mllsrowfckjrouoxzpf27rls

**Comment by Reiers** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebztecvyafl5lziq2vvdjag5c4wc77zmom2aiqrdpjapl4avymvje 
#### Address 
> f3rncwz3qo2bwnsrfjc7kq53xr7yi2lctcydtllxozmszndvttou7n565yb6aqssvn4omyf5m7q62qpfmqcbwq
#### Datacap Allocated
> 50TiB
#### Signer Address
> f1oz43ckvmtxmmsfzqm6bpnemqlavz4ifyl524chq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebztecvyafl5lziq2vvdjag5c4wc77zmom2aiqrdpjapl4avymvje

**Comment by MRJAVAZHAO** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedm6kqpbo6obhvpml7pfcwc5utgeubr7rjmvlq4bka2o3xxfdvfvq 
#### Address 
> f3rncwz3qo2bwnsrfjc7kq53xr7yi2lctcydtllxozmszndvttou7n565yb6aqssvn4omyf5m7q62qpfmqcbwq
#### Datacap Allocated
> 50TiB
#### Signer Address
> f14gme3f52prtyzk6pblogrdd6b6ivp4swc6qmesi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedm6kqpbo6obhvpml7pfcwc5utgeubr7rjmvlq4bka2o3xxfdvfvq

**Comment by MRJAVAZHAO** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceazpcymoqs3s6eoeje3d5wn5byxtzrw3eynnxb73bl4nwrvbmy352 
#### Address 
> f3rncwz3qo2bwnsrfjc7kq53xr7yi2lctcydtllxozmszndvttou7n565yb6aqssvn4omyf5m7q62qpfmqcbwq
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f14gme3f52prtyzk6pblogrdd6b6ivp4swc6qmesi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceazpcymoqs3s6eoeje3d5wn5byxtzrw3eynnxb73bl4nwrvbmy352

**Comment by twoopportunity** [comment]
@galen-mcandrew 
Hello. Can you check our application? We have almost used up the datacap allocated. But the next DataCap Allocation request has  not been created.

**Comment by MRJAVAZHAO** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceamuwsprg44mnefwlh6sjsppk5vplhvc7bepduitefkoah64mhbak 
#### Address 
> f3rncwz3qo2bwnsrfjc7kq53xr7yi2lctcydtllxozmszndvttou7n565yb6aqssvn4omyf5m7q62qpfmqcbwq
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f14gme3f52prtyzk6pblogrdd6b6ivp4swc6qmesi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceamuwsprg44mnefwlh6sjsppk5vplhvc7bepduitefkoah64mhbak

**Comment by Fenbushi-Filecoin** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedmsgbetxu3li355en7x4vz46vfcdxeccj4lzjktuaxpf3sclupe6 
#### Address 
> f3rncwz3qo2bwnsrfjc7kq53xr7yi2lctcydtllxozmszndvttou7n565yb6aqssvn4omyf5m7q62qpfmqcbwq
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1yqydpmqb5en262jpottko2kd65msajax7fi4rmq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedmsgbetxu3li355en7x4vz46vfcdxeccj4lzjktuaxpf3sclupe6

**Comment by XnMatrixSV** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebzz2ng7uukfu6i75thuthppykcfiyq3dlvrfporkcl7yzi3tkkoi 
#### Address 
> f3rncwz3qo2bwnsrfjc7kq53xr7yi2lctcydtllxozmszndvttou7n565yb6aqssvn4omyf5m7q62qpfmqcbwq
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1yuz2twsllparyfqwslfiuxrc5wj4mfiflvnsw6a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebzz2ng7uukfu6i75thuthppykcfiyq3dlvrfporkcl7yzi3tkkoi

**Comment by TimWilliams00** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced3fpu7jjk7zprwe7h2roa3jxcvlaqoaskpfh2ylgdgx64wr66hsi 
#### Address 
> f3rncwz3qo2bwnsrfjc7kq53xr7yi2lctcydtllxozmszndvttou7n565yb6aqssvn4omyf5m7q62qpfmqcbwq
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1fkxkfxgopjf3ufnfg5i3m6qlwf73kp4w5zz7nnq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced3fpu7jjk7zprwe7h2roa3jxcvlaqoaskpfh2ylgdgx64wr66hsi

**Comment by DarnellWashington** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedgdxjrzevruf5cf3rlfdxws7s3m6fnnywk7ofbilledkonurs3sc 
#### Address 
> f3rncwz3qo2bwnsrfjc7kq53xr7yi2lctcydtllxozmszndvttou7n565yb6aqssvn4omyf5m7q62qpfmqcbwq
#### Datacap Allocated
> 249.00TiB
#### Signer Address
> f1bjdcjxha3ldcstw5zmvkyu3r2p5x2bsm745kgsi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedgdxjrzevruf5cf3rlfdxws7s3m6fnnywk7ofbilledkonurs3sc

**Comment by swatchliu** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaa4a2u4sgbbrm5rqofzosvbka7lnbc3boqjffvbzt72bzlsqfg54 
#### Address 
> f3rncwz3qo2bwnsrfjc7kq53xr7yi2lctcydtllxozmszndvttou7n565yb6aqssvn4omyf5m7q62qpfmqcbwq
#### Datacap Allocated
> 249.00TiB
#### Signer Address
> f1yh6q3nmsg7i2sys7f7dexcuajgoweudcqj2chfi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaa4a2u4sgbbrm5rqofzosvbka7lnbc3boqjffvbzt72bzlsqfg54

**Comment by filplus-checker** [comment]
## DataCap and CID Checker Report[^1]
 - Organization: `VillageOne Space LLCVillageOne Space LLC`
 - Client: `f3rncwz3qo2bwnsrfjc7kq53xr7yi2lctcydtllxozmszndvttou7n565yb6aqssvn4omyf5m7q62qpfmqcbwq`
### Storage Provider Distribution
The below table shows the distribution of storage providers that have stored data for this client.

If this is the first time a provider takes verified deal, it will be marked as `new`.

For most of the datacap application, below restrictions should apply.
 - Storage provider should not exceed 25% of total datacap.
 - Storage provider should not be storing duplicate data for more than 20%.
 - Storage provider should have published its public IP address.
 - All storage providers should be located in different regions.

⚠️ [f01840776](https://filfox.info/en/address/f01840776) has sealed 25.95% of total datacap.

⚠️ 51.41% of total deal sealed by [f01840776](https://filfox.info/en/address/f01840776) are duplicate data.

⚠️ 46.31% of total deal sealed by [f01846857](https://filfox.info/en/address/f01846857) are duplicate data.

⚠️ 42.64% of total deal sealed by [f01846877](https://filfox.info/en/address/f01846877) are duplicate data.

⚠️ [f01773193](https://filfox.info/en/address/f01773193) has unknown IP location.

⚠️ [f01308857](https://filfox.info/en/address/f01308857) has unknown IP location.

⚠️ [f01169692](https://filfox.info/en/address/f01169692) has unknown IP location.

⚠️ [f01308862](https://filfox.info/en/address/f01308862) has unknown IP location.

⚠️ 42.03% of total deal sealed by [f0442383](https://filfox.info/en/address/f0442383) are duplicate data.

⚠️ [f0442383](https://filfox.info/en/address/f0442383) has unknown IP location.

⚠️ [f01387466](https://filfox.info/en/address/f01387466) has unknown IP location.

⚠️ [f01387566](https://filfox.info/en/address/f01387566) has unknown IP location.

⚠️ [f0142723](https://filfox.info/en/address/f0142723) has unknown IP location.

⚠️ [f01169691](https://filfox.info/en/address/f01169691) has unknown IP location.

⚠️ [f01387598](https://filfox.info/en/address/f01387598) has unknown IP location.

⚠️ [f01387599](https://filfox.info/en/address/f01387599) has unknown IP location.

⚠️ [f01387460](https://filfox.info/en/address/f01387460) has unknown IP location.

⚠️ [f01308876](https://filfox.info/en/address/f01308876) has unknown IP location.

⚠️ [f0807382](https://filfox.info/en/address/f0807382) has unknown IP location.

⚠️ 21.20% of total deal sealed by [f01132084](https://filfox.info/en/address/f01132084) are duplicate data.

⚠️ [f01132084](https://filfox.info/en/address/f01132084) has unknown IP location.

⚠️ [f0883206](https://filfox.info/en/address/f0883206) has unknown IP location.

⚠️ [f01308916](https://filfox.info/en/address/f01308916) has unknown IP location.

⚠️ [f01387459](https://filfox.info/en/address/f01387459) has unknown IP location.

⚠️ [f0142721](https://filfox.info/en/address/f0142721) has unknown IP location.

⚠️ [f01308863](https://filfox.info/en/address/f01308863) has unknown IP location.

⚠️ [f01387465](https://filfox.info/en/address/f01387465) has unknown IP location.

⚠️ [f01308928](https://filfox.info/en/address/f01308928) has unknown IP location.

⚠️ [f01308877](https://filfox.info/en/address/f01308877) has unknown IP location.

⚠️ [f0883203](https://filfox.info/en/address/f0883203) has unknown IP location.

⚠️ 25.83% of total deal sealed by [f0883202](https://filfox.info/en/address/f0883202) are duplicate data.

⚠️ [f0883202](https://filfox.info/en/address/f0883202) has unknown IP location.

⚠️ 41.12% of total deal sealed by [f0883201](https://filfox.info/en/address/f0883201) are duplicate data.

⚠️ [f0883201](https://filfox.info/en/address/f0883201) has unknown IP location.

⚠️ 46.23% of total deal sealed by [f0883205](https://filfox.info/en/address/f0883205) are duplicate data.

⚠️ [f0883205](https://filfox.info/en/address/f0883205) has unknown IP location.

| Provider                                                    |                           Location | Total Deals Sealed | Percentage | Unique Data | Duplicate Deals |
| :---------------------------------------------------------- | ---------------------------------: | -----------------: | ---------: | ----------: | --------------: |
| [f01840776](https://filfox.info/en/address/f01840776)       | Hong Kong, Central and Western, HK |         267.75 TiB |     25.95% |  130.09 TiB |          51.41% |
| [f01846857](https://filfox.info/en/address/f01846857)       |                   Osaka, Ōsaka, JP |         245.52 TiB |     23.79% |  131.82 TiB |          46.31% |
| [f01846877](https://filfox.info/en/address/f01846877)       |           Singapore, Singapore, SG |         221.94 TiB |     21.51% |  127.30 TiB |          42.64% |
| [f01841133](https://filfox.info/en/address/f01841133)       |           Singapore, Singapore, SG |          52.78 TiB |      5.11% |   43.72 TiB |          17.17% |
| [f01841134](https://filfox.info/en/address/f01841134)       |           Singapore, Singapore, SG |          50.78 TiB |      4.92% |   42.47 TiB |          16.37% |
| [f01841131](https://filfox.info/en/address/f01841131)       | Hong Kong, Central and Western, HK |          49.97 TiB |      4.84% |   41.50 TiB |          16.95% |
| [f01773206](https://filfox.info/en/address/f01773206)       |                   Seoul, Seoul, KR |          42.41 TiB |      4.11% |   42.41 TiB |           0.00% |
| [f01773193](https://filfox.info/en/address/f01773193)       |                            Unknown |          42.03 TiB |      4.07% |   41.91 TiB |           0.30% |
| [f01843749](https://filfox.info/en/address/f01843749)       | Hong Kong, Central and Western, HK |          17.25 TiB |      1.67% |   14.25 TiB |          17.39% |
| [f01308857](https://filfox.info/en/address/f01308857)       |                            Unknown |           4.31 TiB |      0.42% |    4.03 TiB |           6.52% |
| [f01169692](https://filfox.info/en/address/f01169692)       |                            Unknown |           3.52 TiB |      0.34% |    3.42 TiB |           2.67% |
| [f01308862](https://filfox.info/en/address/f01308862)       |                            Unknown |           3.42 TiB |      0.33% |    3.36 TiB |           1.83% |
| [f0442383](https://filfox.info/en/address/f0442383)         |                            Unknown |           2.64 TiB |      0.26% |    1.53 TiB |          42.03% |
| [f01387466](https://filfox.info/en/address/f01387466)       |                            Unknown |           2.44 TiB |      0.24% |    2.40 TiB |           1.84% |
| [f01387566](https://filfox.info/en/address/f01387566)       |                            Unknown |           2.38 TiB |      0.23% |    2.34 TiB |           1.88% |
| [f0142723](https://filfox.info/en/address/f0142723)         |                            Unknown |           2.22 TiB |      0.22% |    2.05 TiB |           7.53% |
| [f01169691](https://filfox.info/en/address/f01169691)       |                            Unknown |           1.69 TiB |      0.16% |    1.57 TiB |           7.50% |
| [f01387598](https://filfox.info/en/address/f01387598)       |                            Unknown |           1.64 TiB |      0.16% |    1.64 TiB |           0.12% |
| [f01387599](https://filfox.info/en/address/f01387599)       |                            Unknown |           1.60 TiB |      0.15% |    1.58 TiB |           1.34% |
| [f01387460](https://filfox.info/en/address/f01387460)       |                            Unknown |           1.40 TiB |      0.14% |    1.28 TiB |           8.59% |
| [f01308876](https://filfox.info/en/address/f01308876)       |                            Unknown |           1.37 TiB |      0.13% |    1.21 TiB |          11.56% |
| [f0807382](https://filfox.info/en/address/f0807382)         |                            Unknown |           1.30 TiB |      0.13% |    1.29 TiB |           0.90% |
| [f01132084](https://filfox.info/en/address/f01132084)       |                            Unknown |           1.23 TiB |      0.12% |  996.00 GiB |          21.20% |
| [f0883206](https://filfox.info/en/address/f0883206)         |                            Unknown |           1.21 TiB |      0.12% |    1.16 TiB |           4.35% |
| [f01308916](https://filfox.info/en/address/f01308916)`new`  |                            Unknown |           1.09 TiB |      0.11% |    1.09 TiB |           0.00% |
| [f01387459](https://filfox.info/en/address/f01387459)       |                            Unknown |           1.05 TiB |      0.10% |  949.77 GiB |          11.77% |
| [f0142721](https://filfox.info/en/address/f0142721)         |                            Unknown |           1.04 TiB |      0.10% |    1.03 TiB |           0.56% |
| [f01308863](https://filfox.info/en/address/f01308863)       |                            Unknown |           1.04 TiB |      0.10% |    1.01 TiB |           2.26% |
| [f01387465](https://filfox.info/en/address/f01387465)       |                            Unknown |        1019.88 GiB |      0.10% |  974.38 GiB |           4.46% |
| [f01308928](https://filfox.info/en/address/f01308928)       |                            Unknown |        1016.28 GiB |      0.10% |  975.28 GiB |           4.03% |
| [f01308877](https://filfox.info/en/address/f01308877)       |                            Unknown |         826.00 GiB |      0.08% |  826.00 GiB |           0.00% |
| [f0883203](https://filfox.info/en/address/f0883203)         |                            Unknown |         652.75 GiB |      0.06% |  546.25 GiB |          16.32% |
| [f0883202](https://filfox.info/en/address/f0883202)         |                            Unknown |         627.25 GiB |      0.06% |  465.25 GiB |          25.83% |
| [f01877862](https://filfox.info/en/address/f01877862)       |                   Seoul, Seoul, KR |         497.75 GiB |      0.05% |  496.25 GiB |           0.30% |
| [f0883201](https://filfox.info/en/address/f0883201)         |                            Unknown |         214.02 GiB |      0.02% |  126.02 GiB |          41.12% |
| [f0883205](https://filfox.info/en/address/f0883205)         |                            Unknown |         212.00 GiB |      0.02% |  114.00 GiB |          46.23% |

![Provider Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/39/1671091563573.png)
### Deal Data Replication
The below table shows how each many unique data are replicated across storage providers.
- No more than 25% of unique data are stored with less than 4 providers.

⚠️ 99.81% of deals are for data replicated across less than 4 storage providers.

| Unique Data Size | Total Deals Made | Number of Providers | Deal Percentage |
| ---------------: | ---------------: | ------------------: | --------------: |
|       624.31 TiB |       979.19 TiB |                   1 |          94.88% |
|         7.61 TiB |        31.45 TiB |                   2 |           3.05% |
|         4.20 TiB |        19.41 TiB |                   3 |           1.88% |
|       371.00 GiB |         1.70 TiB |                   4 |           0.16% |
|        38.00 GiB |       223.00 GiB |                   5 |           0.02% |
|       256.00 MiB |        16.50 GiB |                   6 |           0.00% |

![Replication Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/39/1671091564306.png)
### Deal Data Shared with other Clients
The below table shows how many unique data are shared with other clients.
Usually different applications owns different data and should not resolve to the same CID.

⚠️ CID sharing has been observed.

| Other Client                                                                                                                                                                                                              | Application                                                                                                                    | Total Deals Affected | Unique CIDs |        Verifier |
| :------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ | :----------------------------------------------------------------------------------------------------------------------------- | -------------------: | ----------: | --------------: |
| [f3q7ablez3jqkcjukwbzaql7lmbx4ldouu66nexpd<br/>cfvu6kgho3v6gricckt77cgr46tdre2l4zmvha7bs<br/>u7qq](https://filfox.info/en/address/f3q7ablez3jqkcjukwbzaql7lmbx4ldouu66nexpdcfvu6kgho3v6gricckt77cgr46tdre2l4zmvha7bsu7qq) | `MatrixStorage`                                                                                                                |           859.64 TiB |      12,816 |        LDN # 72 |
| [f3q3eysweh273pwygu27yllyafljznqewpxwlrc7j<br/>daugrpvhmrcnxmkn43wkctxalcg3z42zxas2hinsf<br/>tgva](https://filfox.info/en/address/f3q3eysweh273pwygu27yllyafljznqewpxwlrc7jdaugrpvhmrcnxmkn43wkctxalcg3z42zxas2hinsftgva) | [Beijing Yibo Technology Co\., Ltd\.](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/74)              |           339.52 TiB |       8,425 |        LDN # 74 |
| [f3skkellc7wegakh2blqeu4kkrlzuqy2siymwli7s<br/>ec6eq77c2v4kzgz5ozgnasjl5r52ckameba5kds7h<br/>djda](https://filfox.info/en/address/f3skkellc7wegakh2blqeu4kkrlzuqy2siymwli7sec6eq77c2v4kzgz5ozgnasjl5r52ckameba5kds7hdjda) | [Meizhai Technology](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/75)                               |           301.91 TiB |       7,805 | LDN v3 multisig |
| [f1vykg3elgzoa3lpzf5xo6rbcghzr5ifat757mucq](https://filfox.info/en/address/f1vykg3elgzoa3lpzf5xo6rbcghzr5ifat757mucq)                                                                                                     | [Hailiang Mingyou Online](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/51)                          |            34.41 TiB |         868 |        LDN # 51 |
| [f1vbe7ze5yknpgu3orinv4zu4rkofsyqfsmpejpui](https://filfox.info/en/address/f1vbe7ze5yknpgu3orinv4zu4rkofsyqfsmpejpui)                                                                                                     | [HELIOS](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/305)                                          |            18.13 TiB |         413 | LDN v3 multisig |
| [f1wr6rwwqckh6um2hynaym2t4mniev5b675kbf5ni](https://filfox.info/en/address/f1wr6rwwqckh6um2hynaym2t4mniev5b675kbf5ni)                                                                                                     | [Ctrip Global Shopping](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/303)                           |             7.16 TiB |          94 | LDN v3 multisig |
| [f1xwmnlen7j7qlkktm3oqggzcbrxp6cvqnkd2wipa](https://filfox.info/en/address/f1xwmnlen7j7qlkktm3oqggzcbrxp6cvqnkd2wipa)                                                                                                     | ``                                                                                                                             |             1.67 TiB |          17 |       LDN # 121 |
| [f1tmuircaaenwvffdmyuydcqlidfxvgvg2wsj344i](https://filfox.info/en/address/f1tmuircaaenwvffdmyuydcqlidfxvgvg2wsj344i)                                                                                                     | [Myserver](https://github.com/filecoin-project/filecoin-plus-client-onboarding/issues/447)                                     |           832.00 GiB |          26 |    Tim Williams |
| [f1avfkllpeqlx32bwjcka6y27scftpl5nzh754yly](https://filfox.info/en/address/f1avfkllpeqlx32bwjcka6y27scftpl5nzh754yly)                                                                                                     | ``                                                                                                                             |           800.00 GiB |          25 |     Zhehao Chen |
| [f3xffjctbyy7zigopfa3za5ha3pvv4z3xfghlw7kw<br/>vyeuabkg4lzsgfwhnghwkvmmvi6yso6k52hq3ca6c<br/>kveq](https://filfox.info/en/address/f3xffjctbyy7zigopfa3za5ha3pvv4z3xfghlw7kwvyeuabkg4lzsgfwhnghwkvmmvi6yso6k52hq3ca6ckveq) | [Chengdu Digital Media Industry Base Co\., Ltd\.](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/387) |           672.00 GiB |          14 | LDN v3 multisig |
| [f1ibuglt2lzlyf7vnmtzmuykcfgl2pn2fxym5dibi](https://filfox.info/en/address/f1ibuglt2lzlyf7vnmtzmuykcfgl2pn2fxym5dibi)                                                                                                     | [Appstest](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/346)                                        |           544.00 GiB |          11 | LDN v3 multisig |
| [f1qnhjr2kq742poi6rukv5hji5rdrtuqsib7khz3a](https://filfox.info/en/address/f1qnhjr2kq742poi6rukv5hji5rdrtuqsib7khz3a)                                                                                                     | [GLOBAL UNIT\-A Corp\.](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/110)                           |           544.00 GiB |          17 |       LDN # 110 |
| [f1tgii4xgcp6um4n2w7eqaw6bwvnvyii2u7cjgzka](https://filfox.info/en/address/f1tgii4xgcp6um4n2w7eqaw6bwvnvyii2u7cjgzka)                                                                                                     | [Meson\.Network ](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/187)                                 |           432.50 GiB |           6 | LDN v3 multisig |
| [f1yswits4hd4zu6n2pl7nk7cspcuieuzl7btjn5ia](https://filfox.info/en/address/f1yswits4hd4zu6n2pl7nk7cspcuieuzl7btjn5ia)                                                                                                     | [TaoPaiPai](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/54)                                        |           224.00 GiB |           3 |        LDN # 54 |
| [f127l5waa4pw6k3sm4e7wxevc4fe5uz7dyt4mxa3i](https://filfox.info/en/address/f127l5waa4pw6k3sm4e7wxevc4fe5uz7dyt4mxa3i)                                                                                                     | `Pangod`                                                                                                                       |           224.00 GiB |           7 | LDN v3 multisig |
| [f1ugo3abkmmb4pb2atxz5oqqgwsd27b4p6k52f2va](https://filfox.info/en/address/f1ugo3abkmmb4pb2atxz5oqqgwsd27b4p6k52f2va)                                                                                                     | [Yuepass Technology Company Limited](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/429)              |           144.00 GiB |           5 | LDN v3 multisig |
| [f3woqxpu6ekmj43nmpcv7j2pgu6lejxtzgxpzl6f2<br/>vrueoqlzjntakyhdkghymyffbzfbsio6dvfmy643x<br/>4y7q](https://filfox.info/en/address/f3woqxpu6ekmj43nmpcv7j2pgu6lejxtzgxpzl6f2vrueoqlzjntakyhdkghymyffbzfbsio6dvfmy643x4y7q) | [RICH ST PETE LLC](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/64)                                 |           128.00 GiB |           4 | LDN v3 multisig |
| [f1k2pbx376s46c72ouwrg2avyvrglj66u76opbsqa](https://filfox.info/en/address/f1k2pbx376s46c72ouwrg2avyvrglj66u76opbsqa)                                                                                                     | [aifabot inc](https://github.com/filecoin-project/filecoin-plus-client-onboarding/issues/566)                                  |            96.00 GiB |           3 |    Dr. Ann Shin |

[^1]: To manually trigger this report, add a comment with text `checker:manualTrigger`

**Comment by Sunnyiscoming** [comment]
Hi, please explain the abnormal information.
