### ISSUE TITLE
[DataCap Application] - Protocol Labs Video

### ISSUE THREAD

**Issue by doctorrobinson** [filecoin-project/filecoin-plus-large-datasets#390]
## Core Information

- Organization Name: Protocol Labs - Video Team
- Website / Social Media: protocol.ai
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 500 TiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100 TiB
- On-chain address for first allocation: f1t2haxau774ram6s63zlgfhmn3xkrqyexp7tpoxa

## Project details

Share a brief history of your project and organization

What is the primary source of funding for this project?
Protocol Labs

What other projects/ecosystem stakeholders is this project associated with?

Dogfooding FIL

## Use-case details

Describe the data being stored onto Filecoin

Video content shot at events & for custom video

Where was the data in this dataset sourced from?
All internal to PL

Can you share a sample of the data?
I cannot. It’s video.

Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).

What is the expected retrieval frequency for this data?

Archival

For how long do you plan to keep this dataset stored on Filecoin?

For. Ev. Er.

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
Any countries

How will you be distributing your data to storage providers? Is there an offline data transfer process?
Online over the internet

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
The data will be stored with reputable SPs such as PiKNiK and ESPA participants.

How will you be distributing deals across storage providers?
There will be an offline data transfer process where hosted files will be able to be downloaded by the other SPs.

Do you have the resources/funding to start making deals as soon as you receive DataCap? 
Yes

What support from the community would help you onboard onto Filecoin?
PiKNiK support

**Comment by galen-mcandrew** [comment]
## Datacap Request Trigger
#### Total DataCap requested 
> 500TiB
#### Expected weekly DataCap usage rate 
> 100TiB 
#### Client address
> f1t2haxau774ram6s63zlgfhmn3xkrqyexp7tpoxa

**Comment by dannyob** [comment]
Hey @doctorrobinson please consider providing some of the data with new or random storage providers, so that datacap is not concentrated among the larger players. It sounds like your offline data retrieval plans include this, but it'd be great to know more.

**Comment by dannyob** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedvkg5b45kkswf4gxejgwrbbyebwo2q4nrtkqapy3ozue344fzxbe 
#### Address 
> f1t2haxau774ram6s63zlgfhmn3xkrqyexp7tpoxa
#### Datacap Allocated
> 25.00TiB
#### Signer Address
> f1k6wwevxvp466ybil7y2scqlhtnrz5atjkkyvm4a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedvkg5b45kkswf4gxejgwrbbyebwo2q4nrtkqapy3ozue344fzxbe

**Comment by 1475Notary** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedy672cbrge7yo5aw2f2m2uoughpzyugk4jmelkkclu2ufj3xx3na 
#### Address 
> f1t2haxau774ram6s63zlgfhmn3xkrqyexp7tpoxa
#### Datacap Allocated
> 25.00TiB
#### Signer Address
> f1ofq4mngy7ggcp755pfquq2gphjjnlydolf6awtq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedy672cbrge7yo5aw2f2m2uoughpzyugk4jmelkkclu2ufj3xx3na

**Comment by Sunnyiscoming** [comment]
Are there any problems with using datacap?

**Comment by jamerduhgamer** [comment]
Sealing of the datacap will begin by the end of the week!

**Comment by jamerduhgamer** [comment]
First 25 TiBs have been used. Waiting for the next tranche.
`lotus filplus check-client-datacap f1t2haxau774ram6s63zlgfhmn3xkrqyexp7tpoxa
25769803776`
I thought the bot was supposed to automatically trigger when the datacap amount dropped below a certain percentage?

**Comment by cryptowhizzard** [comment]
Yup. I don't have this on my dashboard to sign. Please contact the governance team.

**Comment by jamerduhgamer** [comment]
Being fully transparent here, we knowingly sealed the first 25 TiB datacap allocation to one of our SPs at f01851060 in order to get access to larger datacap allocations while we are waiting on other SPs that are still getting ready.

**Comment by Joss-Hua** [comment]
Reasonable. Support.

**Comment by Joss-Hua** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecsu7wcrhy22shemidmaocl5emxori5kq54om3imbtpsgmmz2pcbi 
#### Address 
> f1t2haxau774ram6s63zlgfhmn3xkrqyexp7tpoxa
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1tfg54zzscugttejv336vivknmsnzzmyudp3t7wi
#### Id
> ac9f8286-325f-443a-9c0e-51b8bd1a0a16
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecsu7wcrhy22shemidmaocl5emxori5kq54om3imbtpsgmmz2pcbi

**Comment by cryptowhizzard** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebx3zusqhc2mwm3u2zeik6qn5unbph4ibq5s3xsquwy37366gb2ns 
#### Address 
> f1t2haxau774ram6s63zlgfhmn3xkrqyexp7tpoxa
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1krmypm4uoxxf3g7okrwtrahlmpcph3y7rbqqgfa
#### Id
> ac9f8286-325f-443a-9c0e-51b8bd1a0a16
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebx3zusqhc2mwm3u2zeik6qn5unbph4ibq5s3xsquwy37366gb2ns

**Comment by cryptowhizzard** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceawt63o3yskhjlxyfamasxpc6gsg2yq36jpejtd6s7e54e6maxz5e 
#### Address 
> f1t2haxau774ram6s63zlgfhmn3xkrqyexp7tpoxa
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1krmypm4uoxxf3g7okrwtrahlmpcph3y7rbqqgfa
#### Id
> 5caffaa1-2f29-4436-b893-d17d69d7495b
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceawt63o3yskhjlxyfamasxpc6gsg2yq36jpejtd6s7e54e6maxz5e

**Comment by kernelogic** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebt4jt6hgthbtmquhhc4mi67j2grbz2hlmcebgutwxbgteabxptsg 
#### Address 
> f1t2haxau774ram6s63zlgfhmn3xkrqyexp7tpoxa
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### Id
> 5caffaa1-2f29-4436-b893-d17d69d7495b
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebt4jt6hgthbtmquhhc4mi67j2grbz2hlmcebgutwxbgteabxptsg
