### ISSUE TITLE
[DataCap Application] Carson Video

### ISSUE THREAD

**Issue by Jimmy-87v5** [filecoin-project/filecoin-plus-large-datasets#392]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: 87v5-CarsonVideo
- Website / Social Media: http://www.87v5.com/index.html 
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100TiB
- On-chain address for first allocation:f1avhqgmeazxzvylz34l26o3nlj2ywnzaviwns3dq

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Founded in February 2021, CarsonVideo is a company that specializes in user-friendly videos. The company's main UGC business is that users upload videos and the platform publishes and disseminates them.
```

What is the primary source of funding for this project?
```
Business income.
```

What other projects/ecosystem stakeholders is this project associated with?
```
None. We are the only one that engaged in this project.
```

## Use-case details

Describe the data being stored onto Filecoin
```
Amount of videos about kinds of themes.
```

Where was the data in this dataset sourced from?
```
From users and our own collection.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
Sure.
[87.zip](https://github.com/filecoin-project/filecoin-plus-large-datasets/files/9107802/87.zip)
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes, we confirm that all data are public and can be retrieved by anyone on the Network.
```

What is the expected retrieval frequency for this data?
```
We expect to retrieve our data every 6 months.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
Permanently.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
All regions.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
We prefer to transfer our data both online and offline. But bandwidth should be a problem for us. The final decision will depend on the cost.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We plan to select miners though Github community, slack or telegram. Miners who have faster internet connection would be better for us.
```

How will you be distributing deals across storage providers?
```
We’d like to distribute our data to 8-10 miners, so every miner can have a copy of our data.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, we’ll start this project ASAP.
```

**Comment by Jimmy-metahallo** [comment]
6 days

**Comment by Jimmy-metahallo** [comment]
no response

**Comment by EGGRICE02** [comment]
@Jimmy-metahallo Hi, could you please mail to filplus@fil.org with your company domain to confirm you're representing this company?

**Comment by EGGRICE02** [comment]
All links on your website are down. Please have a check

**Comment by Sunnyiscoming** [comment]
@Jimmy-metahallo Hi,

> Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
> 
> Sure. The links are as follows.

Please list the links of data samples.

**Comment by Jimmy-metahallo** [comment]
@Sunnyiscoming Hey, it is the data sample.
https://user-images.githubusercontent.com/106655518/177451675-8f7e5ea0-a104-4773-9ef4-600938dd7457.mp4

**Comment by Sunnyiscoming** [comment]
I have saw related video on your website.
Hope to get more data samples related with your description about the data will be stored on the filecoin  network.

> Describe the data being stored onto Filecoin
> 
> NFT metadata, the resource itself linked to NFT, transaction data on the private chain, metaverse 3D data, user behavior data, project implementation code archive data, etc. We estimate the total data is around 400-600 TiB, and we're going to keep more than 10 copies.

**Comment by Yvette516** [comment]
@Jimmy-metahallo Could you send an email to [filplus@fil.org](mailto:filplus@fil.org) from your officail email Account?

**Comment by Jimmy-metahallo** [comment]
[392.txt](https://github.com/filecoin-project/filecoin-plus-large-datasets/files/9059697/392.txt)
@Sunnyiscoming like this data.

**Comment by Jimmy-metahallo** [comment]
![dejwirg](https://user-images.githubusercontent.com/106655518/177730521-452c54ff-e77b-47b2-8db6-6864aa84ce33.png)
I've sent the email but it seems to be a problem about sending it. @Sunnyiscoming @Yvette516

**Comment by Jimmy-87v5** [comment]
https://user-images.githubusercontent.com/106655518/178967397-0e16d3eb-02f9-48b6-822c-77f22c6341c2.mp4
https://user-images.githubusercontent.com/106655518/178967477-e5e850db-0d41-4117-86f8-07145327a4ea.mp4

> I have saw related video on your website. Hope to get more data samples related with your description about the data will be stored on the filecoin network.

@Sunnyiscoming

**Comment by Jimmy-87v5** [comment]
Already sent an email.
![eisrg](https://user-images.githubusercontent.com/106655518/179384010-6ee3c2e8-8d4a-40df-b637-9c7c8442c9dd.png)

**Comment by raghavrmadya** [comment]
Hi, thanks for the email. Can confirm it was received and sorry for the delay in getting back to you. We would like to know how much data do you have. You came into operation in Feb 2021 as mentioned above and we are not convinced that you have that much or even half of that amount of video data already. 

We would also like to know more about your plan for SP allocation as well as the regions you would focus on. All regions, while great, is not realistic and feasible, especially for offline transfer as you mention.

**Comment by Jimmy-87v5** [comment]
@raghavrmadya Hello Raghav, thanks for your concern! Our total data is around 600 TiB, and we plan making 10 copies. As a platform for videos, we own a library of videos that we have built and need to save them to filecoin for backup. 
We've chosen f01105079 and f014768 for deals. And we are looking for more SPs to cooperate with us in the future. For offline transfer, we focus on Asia. We also support online transfer, so we welcome more SP recieve our deals if they meet our requirements!

**Comment by raghavrmadya** [comment]
How did you choose these two SP IDs? 
### Datacap Request Trigger
**Total DataCap requested**

> 5 PiB

**Expected weekly DataCap usage rate**

> 100 TiB

**Client address**

> f1avhqgmeazxzvylz34l26o3nlj2ywnzaviwns3dq

**Comment by MetaWaveInfo** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecf4pyc23uhjeofp36mc3kk3eotrvbobpbgzwuj36xubkg754j4yi 
#### Address 
> f1avhqgmeazxzvylz34l26o3nlj2ywnzaviwns3dq
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1ktlkcxnmzxcdaoqfsunrg3vocfbmgv4n3mrn74a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecf4pyc23uhjeofp36mc3kk3eotrvbobpbgzwuj36xubkg754j4yi

**Comment by 1475Notary** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecdyay6d23ew5mofruguylueafxnm3x7ohszph7nxktmfhyr6amx4 
#### Address 
> f1avhqgmeazxzvylz34l26o3nlj2ywnzaviwns3dq
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1ofq4mngy7ggcp755pfquq2gphjjnlydolf6awtq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecdyay6d23ew5mofruguylueafxnm3x7ohszph7nxktmfhyr6amx4

**Comment by BigD-Exchange** [comment]
@Jimmy-87v5 Hi! Great to see you have gotten approval for DataCap. If you are looking for storage providers to store these data or have any questions, please visit #bigdata-exchange on Filecoin Slack or reply here. 

We have strong demand from a diverse group of SPs, who are actively looking to onboard more data.

**Comment by UnionLabs2020** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceazxy5h4zlqmesl5wyfzjqg2a3ahrdps2nalfcxqyud4mw3wrqsh6 
#### Address 
> f1avhqgmeazxzvylz34l26o3nlj2ywnzaviwns3dq
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f17xdri3wunqgld7dm23e4f3eqsntjakwc47xjo6i
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceazxy5h4zlqmesl5wyfzjqg2a3ahrdps2nalfcxqyud4mw3wrqsh6

**Comment by liyunzhi-666** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacea53dyjzwuvepunw45c3cbltoizthtb6bhicjpntrpwyguqhitnac 
#### Address 
> f1avhqgmeazxzvylz34l26o3nlj2ywnzaviwns3dq
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1pszcrsciyixyuxxukkvtazcokexbn54amf7gvoq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacea53dyjzwuvepunw45c3cbltoizthtb6bhicjpntrpwyguqhitnac

**Comment by 1475Notary** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebgm6vu3r6eo7od7bwrr736fgvfj75auvuggzmwdt25kuc4afrsng 
#### Address 
> f1avhqgmeazxzvylz34l26o3nlj2ywnzaviwns3dq
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1ofq4mngy7ggcp755pfquq2gphjjnlydolf6awtq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebgm6vu3r6eo7od7bwrr736fgvfj75auvuggzmwdt25kuc4afrsng

**Comment by Alex11801** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb6t2hiaw5nlgqu7wz7rrc3mu2adgfavmhtqw3weyov2cggchn7h6 
#### Address 
> f1avhqgmeazxzvylz34l26o3nlj2ywnzaviwns3dq
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1hhippi64yiyhpjdtbidfyzma6irc2nuav7mrwmi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb6t2hiaw5nlgqu7wz7rrc3mu2adgfavmhtqw3weyov2cggchn7h6

**Comment by psh0691** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecgjmfklvbtaakw6le3i7hilq6es3xwnq2yvrpttdiei74nz2k4t2 
#### Address 
> f1avhqgmeazxzvylz34l26o3nlj2ywnzaviwns3dq
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1qdko4jg25vo35qmyvcrw4ak4fmuu3f5rif2kc7i
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecgjmfklvbtaakw6le3i7hilq6es3xwnq2yvrpttdiei74nz2k4t2

**Comment by MetaWaveInfo** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacea4ohv6uxuyzvhyvt2ynks342kwzaodl5e44aerq5y57vlptw2g36 
#### Address 
> f1avhqgmeazxzvylz34l26o3nlj2ywnzaviwns3dq
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1ktlkcxnmzxcdaoqfsunrg3vocfbmgv4n3mrn74a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacea4ohv6uxuyzvhyvt2ynks342kwzaodl5e44aerq5y57vlptw2g36

**Comment by swatchliu** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced456ros7ssxjtyhdv43fftoun4bzegyr6ic7rjoe6uer23bpmbcu 
#### Address 
> f1avhqgmeazxzvylz34l26o3nlj2ywnzaviwns3dq
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1yh6q3nmsg7i2sys7f7dexcuajgoweudcqj2chfi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced456ros7ssxjtyhdv43fftoun4bzegyr6ic7rjoe6uer23bpmbcu

**Comment by UnionLabs2020** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb2nwvpf4bbfruqwlebj4uuu5aebvgof6qch2mqa57o33o7ftv42c 
#### Address 
> f1avhqgmeazxzvylz34l26o3nlj2ywnzaviwns3dq
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f17xdri3wunqgld7dm23e4f3eqsntjakwc47xjo6i
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb2nwvpf4bbfruqwlebj4uuu5aebvgof6qch2mqa57o33o7ftv42c

**Comment by liyunzhi-666** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebi63ye32mlq3dhfn6favtubaublarxmog5yzdyad3m2dhtwbgdsk 
#### Address 
> f1avhqgmeazxzvylz34l26o3nlj2ywnzaviwns3dq
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1pszcrsciyixyuxxukkvtazcokexbn54amf7gvoq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebi63ye32mlq3dhfn6favtubaublarxmog5yzdyad3m2dhtwbgdsk

**Comment by filplus-checker** [comment]
## DataCap and CID Checker Report[^1]
 - Organization: `87v5-CarsonVideo`
 - Client: `f1avhqgmeazxzvylz34l26o3nlj2ywnzaviwns3dq`
### Storage Provider Distribution
The below table shows the distribution of storage providers that have stored data for this client.

If this is the first time a provider takes verified deal, it will be marked as `new`.

For most of the datacap application, below restrictions should apply.
 - Storage provider should not exceed 25% of total datacap.
 - Storage provider should not be storing duplicate data for more than 20%.
 - Storage provider should have published its public IP address.
 - All storage providers should be located in different regions.

⚠️ [f01828096](https://filfox.info/en/address/f01828096) has sealed 27.13% of total datacap.

⚠️ 81.15% of total deal sealed by [f01828096](https://filfox.info/en/address/f01828096) are duplicate data.

⚠️ [f01832632](https://filfox.info/en/address/f01832632) has sealed 26.94% of total datacap.

⚠️ 80.66% of total deal sealed by [f01832632](https://filfox.info/en/address/f01832632) are duplicate data.

⚠️ [f01937964](https://filfox.info/en/address/f01937964) has sealed 25.49% of total datacap.

⚠️ 73.51% of total deal sealed by [f01937964](https://filfox.info/en/address/f01937964) are duplicate data.

⚠️ 70.03% of total deal sealed by [f01924350](https://filfox.info/en/address/f01924350) are duplicate data.

⚠️ 70.34% of total deal sealed by [f01924325](https://filfox.info/en/address/f01924325) are duplicate data.

⚠️ 50.85% of total deal sealed by [f01917257](https://filfox.info/en/address/f01917257) are duplicate data.

⚠️ 54.06% of total deal sealed by [f01914977](https://filfox.info/en/address/f01914977) are duplicate data.

⚠️ 69.69% of total deal sealed by [f01924416](https://filfox.info/en/address/f01924416) are duplicate data.

⚠️ 41.56% of total deal sealed by [f01889046](https://filfox.info/en/address/f01889046) are duplicate data.

| Provider                                              |                 Location | Total Deals Sealed | Percentage | Unique Data | Duplicate Deals |
| :---------------------------------------------------- | -----------------------: | -----------------: | ---------: | ----------: | --------------: |
| [f01828096](https://filfox.info/en/address/f01828096) | San Jose, California, US |         198.94 TiB |     27.13% |   37.50 TiB |          81.15% |
| [f01832632](https://filfox.info/en/address/f01832632) | San Jose, California, US |         197.50 TiB |     26.94% |   38.19 TiB |          80.66% |
| [f01937964](https://filfox.info/en/address/f01937964) |         Tokyo, Tokyo, JP |         186.88 TiB |     25.49% |   49.50 TiB |          73.51% |
| [f01924350](https://filfox.info/en/address/f01924350) | Singapore, Singapore, SG |          44.00 TiB |      6.00% |   13.19 TiB |          70.03% |
| [f01924325](https://filfox.info/en/address/f01924325) | Singapore, Singapore, SG |          42.88 TiB |      5.85% |   12.72 TiB |          70.34% |
| [f01917257](https://filfox.info/en/address/f01917257) |         Seoul, Seoul, KR |          33.00 TiB |      4.50% |   16.22 TiB |          50.85% |
| [f01914977](https://filfox.info/en/address/f01914977) |    Ashburn, Virginia, US |          10.00 TiB |      1.36% |    4.59 TiB |          54.06% |
| [f01924416](https://filfox.info/en/address/f01924416) | Singapore, Singapore, SG |          10.00 TiB |      1.36% |    3.03 TiB |          69.69% |
| [f01889046](https://filfox.info/en/address/f01889046) |    Ashburn, Virginia, US |          10.00 TiB |      1.36% |    5.84 TiB |          41.56% |

![Provider Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/392/1671096592925.png)
### Deal Data Replication
The below table shows how each many unique data are replicated across storage providers.
- No more than 25% of unique data are stored with less than 4 providers.

⚠️ 100.00% of deals are for data replicated across less than 4 storage providers.

| Unique Data Size | Total Deals Made | Number of Providers | Deal Percentage |
| ---------------: | ---------------: | ------------------: | --------------: |
|       114.34 TiB |       423.09 TiB |                   1 |          57.71% |
|        33.22 TiB |       310.09 TiB |                   2 |          42.29% |

![Replication Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/392/1671096593572.png)
### Deal Data Shared with other Clients
The below table shows how many unique data are shared with other clients.
Usually different applications owns different data and should not resolve to the same CID.

⚠️ CID sharing has been observed.

| Other Client                                                                                                          | Application                                                                                                              | Total Deals Affected | Unique CIDs |                                                                                 Verifier |
| :-------------------------------------------------------------------------------------------------------------------- | :----------------------------------------------------------------------------------------------------------------------- | -------------------: | ----------: | ---------------------------------------------------------------------------------------: |
| [f1xtnkj5ti77f5gbzhclnpj3xt6e5dwhfzive2yca](https://filfox.info/en/address/f1xtnkj5ti77f5gbzhclnpj3xt6e5dwhfzive2yca) | [Beacon Project](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/482)                            |           256.94 TiB |         765 | Project Beacon, 12 LDNs LDN # 444, 446, 447, 448, 474, 475, 476, 477, 479, 480, 481, 482 |
| [f1nmhjvibl7acp45lpxmo5kduz42evjazsyi4mzza](https://filfox.info/en/address/f1nmhjvibl7acp45lpxmo5kduz42evjazsyi4mzza) | `ubuckvnockai`                                                                                                           |            59.22 TiB |         571 |                                                                          LDN v3 multisig |
| [f1dwhevm3p2slu6itmkssznscmpkpltdiztprnpya](https://filfox.info/en/address/f1dwhevm3p2slu6itmkssznscmpkpltdiztprnpya) | [Hiscene](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/548)                                   |            40.63 TiB |         257 |                                                                          LDN v3 multisig |
| [f1smfrznoqsp7eptqnselnosng7vxuo3ptnoqv2oa](https://filfox.info/en/address/f1smfrznoqsp7eptqnselnosng7vxuo3ptnoqv2oa) | [CTG Business Service](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/306)                      |            40.47 TiB |         431 |                                                                          LDN v3 multisig |
| [f1ajdk7e6ex7fvtjtydzgys47bcg7jub2baucun7y](https://filfox.info/en/address/f1ajdk7e6ex7fvtjtydzgys47bcg7jub2baucun7y) | [Ruikuyun Information Technology Co\., Ltd](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/529) |            38.31 TiB |         538 |                                                                          LDN v3 multisig |
| [f1uuzet23wng5lxu3y4iicokksydynamgmptfekdq](https://filfox.info/en/address/f1uuzet23wng5lxu3y4iicokksydynamgmptfekdq) | `Explainer video`                                                                                                        |            37.69 TiB |         250 |                                                                                 LDN # 65 |
| [f1clwd2dooy2cflfilhzeq2ycl544b3heqsiwhjrq](https://filfox.info/en/address/f1clwd2dooy2cflfilhzeq2ycl544b3heqsiwhjrq) | [FiboAI](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/349)                                    |            33.09 TiB |         446 |                                                                          LDN v3 multisig |
| [f1727w2vwjctfo7hflr5trgqkl3c7texh7pl4grzq](https://filfox.info/en/address/f1727w2vwjctfo7hflr5trgqkl3c7texh7pl4grzq) | [GMverse](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/365)                                   |            32.81 TiB |         320 |                                                                          LDN v3 multisig |
| [f17qd6x3leh5pa7vh6ewdaed7qhbn2mgofrokuayy](https://filfox.info/en/address/f17qd6x3leh5pa7vh6ewdaed7qhbn2mgofrokuayy) | [Drust](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/427)                                     |            29.72 TiB |         381 |                                                                          LDN v3 multisig |
| [f1rnwp6p5kx7pcwexpucoav6mmwz3rkxw5blrboyy](https://filfox.info/en/address/f1rnwp6p5kx7pcwexpucoav6mmwz3rkxw5blrboyy) | [MigoVideo](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/517)                                 |            24.78 TiB |         314 |                                                                          LDN v3 multisig |
| [f1ki4cjk27ypzjsuzkvvqzs6xobaweuoxfdcnpqhy](https://filfox.info/en/address/f1ki4cjk27ypzjsuzkvvqzs6xobaweuoxfdcnpqhy) | [TimeQuant](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/385)                                 |            24.69 TiB |         452 |                                                                          LDN v3 multisig |
| [f1vtcetpapwwyka6txwqjwymsa67npdfilbkwh64a](https://filfox.info/en/address/f1vtcetpapwwyka6txwqjwymsa67npdfilbkwh64a) | [Chimay](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/397)                                    |            23.81 TiB |         295 |                                                                          LDN v3 multisig |
| [f1hamzyd3tx4pdchop3l4hfeay5q6s427pxga6flq](https://filfox.info/en/address/f1hamzyd3tx4pdchop3l4hfeay5q6s427pxga6flq) | `Beacon Project`                                                                                                         |            21.06 TiB |         144 | Project Beacon, 12 LDNs LDN # 444, 446, 447, 448, 474, 475, 476, 477, 479, 480, 481, 482 |
| [f1rszqldzirsgganeah32zubr4r4qafwypuwaig2q](https://filfox.info/en/address/f1rszqldzirsgganeah32zubr4r4qafwypuwaig2q) | [Beacon Project](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/477)                            |            16.56 TiB |         139 | Project Beacon, 12 LDNs LDN # 444, 446, 447, 448, 474, 475, 476, 477, 479, 480, 481, 482 |
| [f1f5edx6ofn3lf6rk3yfpldbi2pzgq2egoyu6ubpi](https://filfox.info/en/address/f1f5edx6ofn3lf6rk3yfpldbi2pzgq2egoyu6ubpi) | [Samdata Trade](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/382)                             |            14.44 TiB |         196 |                                                                          LDN v3 multisig |
| [f1einobkrjcjk6gfc5ov6663vrri75hwdsjfs6pmq](https://filfox.info/en/address/f1einobkrjcjk6gfc5ov6663vrri75hwdsjfs6pmq) | [Cansoti](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/640)                                   |            13.78 TiB |         212 |                                                                          LDN v3 multisig |
| [f1mn5mw2dpqz6p3s7vxrlkhkh3okdtc6t7wqro4xa](https://filfox.info/en/address/f1mn5mw2dpqz6p3s7vxrlkhkh3okdtc6t7wqro4xa) | [Unisound](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/577)                                  |             9.75 TiB |          60 |                                                                          LDN v3 multisig |
| [f1zb6pgkktdbyy7zxfob6gripqxuc25ukf35cc7fq](https://filfox.info/en/address/f1zb6pgkktdbyy7zxfob6gripqxuc25ukf35cc7fq) | `Maxpic PhotoGraphic Studio`                                                                                             |             8.31 TiB |         156 |                                                                          LDN v3 multisig |
| [f1quofpadzcqlonmz7v3mv7dfqvm5hdztucdsjqsy](https://filfox.info/en/address/f1quofpadzcqlonmz7v3mv7dfqvm5hdztucdsjqsy) | [HENAN 863 SOFTWARE CO\., LTD](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/468)              |             1.75 TiB |          11 |                                                                          LDN v3 multisig |
| [f1tivtdkq34mnfzso63wrr2xh6r2zo7aebao4jfla](https://filfox.info/en/address/f1tivtdkq34mnfzso63wrr2xh6r2zo7aebao4jfla) | `China travel service(HongKong) limited`                                                                                 |             1.59 TiB |           5 |                                                                          LDN v3 multisig |
| [f1ffbtksiso5za73pypuxbxznng6rdv64nbihdtba](https://filfox.info/en/address/f1ffbtksiso5za73pypuxbxznng6rdv64nbihdtba) | [EpikProtocol](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/281)                              |           384.00 GiB |           6 |                                                                                LDN # 281 |
| [f1ivsvpljx4ovp2tth73pllkxmumrudemks623iia](https://filfox.info/en/address/f1ivsvpljx4ovp2tth73pllkxmumrudemks623iia) | `TIS Inc. group`                                                                                                         |           192.00 GiB |           4 |                                                                          LDN v3 multisig |
| [f1qjrlejxv5a73kxurwtxyrni6ji7orm74zeeetiy](https://filfox.info/en/address/f1qjrlejxv5a73kxurwtxyrni6ji7orm74zeeetiy) | [Mooc](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/223)                                      |           128.00 GiB |           2 |                                                                          LDN v3 multisig |

[^1]: To manually trigger this report, add a comment with text `checker:manualTrigger`

**Comment by Sunnyiscoming** [comment]
Hello, @Jimmy-87v5 per the https://github.com/filecoin-project/notary-governance/issues/922 for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

This information will be reviewed by Fil+ Governance team to confirm validity and then the application will be allowed to move forward for additional notary review.
