### ISSUE TITLE
[DataCap Application]BDNFT

### ISSUE THREAD

**Issue by BDNFT** [filecoin-project/filecoin-plus-large-datasets#394]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: BDNFT
- Website / Social Media: https://bdnft.com/
Twitter link：https://twitter.com/bdnftlab/with_replies
Wechat official account：https://mp.weixin.qq.com/mp/profile_extaction=home&__biz=MzkyMjMzMjQzOA==&scene=124#wechat_redirect

- Total amount of DataCap being requested (between 500 TiB and 5 PiB):3PIB
- Weekly allocation of DataCap requested (usually between 1-100TiB):100TIB
- On-chain address for first allocation:f1gzkt6xc2oscnzcjbsnn6ha25psx5isjyt6ampey

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
BDNFT is a world's leading crowdfunding platform for music copyright NFT. BDNFT's innovative introduction of NFT and token-less blockchain into the music copyright enables it to take the lead in adding value and interests to NFT, realizing the concept of NFT2.0. We strive to facilitate the connection between upstream and downstream of music businesses including creators, copyright owners, investors, fans, recommendation groups and critics. BDNFT makes it possible for copyright owners and NFT holders to share the benefits, which virtually inspires artists and fans as investors and promotes the sound development of the music industry.
```
<img width="1212" alt="iShot2022-06-08_12 00 03" src="https://user-images.githubusercontent.com/106738351/172529432-312c427f-2032-472c-8702-7a9e2c67d458.png">
<img width="1189" alt="iShot2022-06-08_12 00 31" src="https://user-images.githubusercontent.com/106738351/172529597-cfaaa363-0c79-4469-9d56-f4cb2aa82bae.png">
<img width="1208" alt="iShot2022-06-08_12 00 44" src="https://user-images.githubusercontent.com/106738351/172529626-47932df7-05b8-434c-b679-1ac0ef98ff91.png">

What is the primary source of funding for this project?
```
Funded by us and supported by technical services provided by new web group and filecoin foundation.
```

What other projects/ecosystem stakeholders is this project associated with?
```
The project is associated with Polygon public chain.
NFT data cast on polygon and stored on filecoin（Music source data with commercial copyright）;
Filecoin foundation（https://filecoin.io/blog/posts/filecoin-project-gravity-a-sales-referral-program/）
```

## Use-case details

Describe the data being stored onto Filecoin
```

- Music data with commercial copyright

- NFT source data, NFT makes engineering documents

```

Where was the data in this dataset sourced from?
```
1. user's singing music data
- We own the commercial copyright of karaoke bar for many songs,All karaoke bars need our authorization to use these songs.Users upload and save their cover works through karaoke bar’s singing software.There is a lot of data in this part, and it is very memorable for users.So we want to store these data on filecoin, and we will select high-quality works to cast NFT in the future.

2. data from platform casting NFT
We have a lot of licensed music. These works have very high broadcast volume and copyright income in the world.
**Give an example**
Bdnft’s first music copyright NFT work “[Haicao Shake](https://www.bdnftlab.com/)”
2017-2018
TOP1 Chinese popular song with the highest view count
TOP1 popular song with the highest view count on Chinese version of TikTok It was viewed more than one hundred billion times across the world and spawned an upsurge inre-creation and phenomenal imitation.

```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://docs.google.com/spreadsheets/d/1x6VJSD0mE3U7V5pJPNpJkxlxdJt-x34U/edit#gid=1423245778

https://ipfs.io/ipfs/bafkreige537a7goejlc4jc5lybqtyabbnfopnocobzo3f7osirompzaotu
https://ipfs.io/ipfs/bafkreifl7ah7fepm7zt547ecklxz4cjme5jxqalizfldnuvm4cjrczkizm
https://ipfs.io/ipfs/bafkreich3wd5ym7iow6tcqnfkkunjlt3spficwzz6fuhidk7b4fzcmirym
https://ipfs.io/ipfs/bafkreiezwwan6xyje23lecushn76spsglfwpja63uqiecdzw2zixvszlzm
https://ipfs.io/ipfs/bafkreiczq225tqpzroo7mtqkn3oaqv5uzla3bognv2hujvl6dcreunvjum
https://ipfs.io/ipfs/bafkreihawdbxgrwxr25uo6wsdddwgzsoupxmd5itvsgn6p4r6ezgxna7wu
https://ipfs.io/ipfs/bafkreifgchq4fxgaegh7mnr6kif2vzb2pmd5qcdid54k2jlwbdjjhrxwim
https://ipfs.io/ipfs/bafkreiaxc527fgttwdhlttd2q6m2xccijv7sevlcjem4of4lbarkz73y4a
https://ipfs.io/ipfs/bafkreihweikavqleapqapwe7hx54xg273mnqwl4gvzzz3wosrlchj4d4d4
https://ipfs.io/ipfs/bafkreiay5o4z7aq4mteyk6p4jrivyxf3d7lzbzbv4rea2ikr6lcjkgwfwe
https://ipfs.io/ipfs/bafkreiabkwi5hchabvyitojg3assnqsjlgrttwjuvozxvxnbp7zyix77xi
https://ipfs.io/ipfs/bafkreielnzzkyhzniovqdl2klgyuuq54phjjqn5azkvp536dpsm6mfflye
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes, we confirm that the dataset is public and can be retrieved by anyone.
```

What is the expected retrieval frequency for this data?
```
Low retrieval frequency, maybe once or twice a year
```

For how long do you plan to keep this dataset stored on Filecoin?
```
3 years at least, if needed we will keep for a long time.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Asia
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Both online and offline transfer process are OK.But we prefer offline transmission, which is more efficient.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We will focus on the running time of the SP, whether the running state is stable, and whether it supports retrieval.
We need high-quality storage providers who can work together for a long time.
```

How will you be distributing deals across storage providers?
```
We will distribute different deals according to their distance. 
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes，We have the support of filecoin foundation,We're ready for making deals.
```

**Comment by Sunnyiscoming** [comment]
https://bdnft.com/ can not open, please check it.

**Comment by Sunnyiscoming** [comment]
It seems something wrong, there are only a few songs on the page and I can not change page.
![image](https://user-images.githubusercontent.com/105098820/175267214-ad2a54bf-7219-44c5-8c60-a3539e9f2e48.png)

**Comment by BDNFT** [comment]
> It seems something wrong, there are only a few songs on the page and I can not change page. ![image](https://user-images.githubusercontent.com/105098820/175267214-ad2a54bf-7219-44c5-8c60-a3539e9f2e48.png)
@Sunnyiscoming 
Please take a closer look at our data sample presentation
The front end of the web page is only part of the song display, and more of our data is stored locally.

**Comment by Sunnyiscoming** [comment]
Could you send an email to filplus@fil.org with your official domain in order to confirm your identity?
Email name should includes the issue id #394.

**Comment by BDNFT** [comment]
Hi @galen-mcandrew @Sunnyiscoming ，
We have sent filplus@fil.org Sent the verification email, please check the verification.

<img width="1504" alt="image" src="https://user-images.githubusercontent.com/106738351/179994131-0a2b264c-6131-4e6e-8df6-9fa446997c4a.png">

**Comment by BDNFT** [comment]
Hello, team, @galen-mcandrew @Sunnyiscoming @dkkapur 
is there any update on this application? 
We have sent a verification email.

**Comment by BDNFT** [comment]
Hello, team, @galen-mcandrew @Sunnyiscoming @Kevin-FF-USA k
It has been half a month since the verification email occurred
Just following up on this to see if there has been any progress.
Many thanks

**Comment by BDNFT** [comment]
Hi Filplus team， @galen-mcandrew @Kevin-FF-USA k @raghavrmadya 
We re sent KYC verification email to“ **filplus-app-review@fil.org** ”
please check the verification.

<img width="788" alt="image" src="https://user-images.githubusercontent.com/106738351/183837846-e4c4f295-00aa-4a59-bbf2-ff0a56c1bcc8.png">

**Comment by raghavrmadya** [comment]
Thank you. How much data do you have as of today and how many copies do you plan to store? We need more insight into the 3 PiB request as well as SP allocation before we can proceed further.

**Comment by BDNFT** [comment]
Hi @raghavrmadya 
As of today, we have 400tib + Commercial copyright music source data.
The new amount of each month is 20tib ~ 40tib
Plan to store 6-7 backups

**Comment by raghavrmadya** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 3 PiB

**Expected weekly DataCap usage rate**

> 100 TiB

**Client address**

> f1gzkt6xc2oscnzcjbsnn6ha25psx5isjyt6ampey

**Comment by psh0691** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebsjxa7unvltr2rdat5id2f3pqtreqzvpyopevelquldtwkxgzx6c 
#### Address 
> f1gzkt6xc2oscnzcjbsnn6ha25psx5isjyt6ampey
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1qdko4jg25vo35qmyvcrw4ak4fmuu3f5rif2kc7i
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebsjxa7unvltr2rdat5id2f3pqtreqzvpyopevelquldtwkxgzx6c

**Comment by kernelogic** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaxmt6f4s46hpt7hvkoa3657vl47t3lfcmojafohyk335i7k4u2iu 
#### Address 
> f1gzkt6xc2oscnzcjbsnn6ha25psx5isjyt6ampey
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaxmt6f4s46hpt7hvkoa3657vl47t3lfcmojafohyk335i7k4u2iu

**Comment by BigD-Exchange** [comment]
@BDNFT Hi! Great to see you have gotten approval for DataCap. If you are looking for reputable storage providers to store these data or have any questions, please visit #bigdata-exchange on Filecoin Slack or reply here. 

We have strong demand from a diverse group of SPs, who are actively looking to onboard more data onto Filecoin.

**Comment by kernelogic** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebnsrh2n44xvipecnbdnrhhrcmwgg3rptu55txdyrsiaqi6rehy7e 
#### Address 
> f1gzkt6xc2oscnzcjbsnn6ha25psx5isjyt6ampey
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebnsrh2n44xvipecnbdnrhhrcmwgg3rptu55txdyrsiaqi6rehy7e

**Comment by newwebgroup** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedyt7zc6clmnbpbppnuucnrnxninqloiplsvfyb6mqwkqynq4guge 
#### Address 
> f1gzkt6xc2oscnzcjbsnn6ha25psx5isjyt6ampey
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1e77zuityhvvw6u2t6tb5qlnsegy2s67qs4lbbbq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedyt7zc6clmnbpbppnuucnrnxninqloiplsvfyb6mqwkqynq4guge

**Comment by NDLABS-OFFICE** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb2nzns2s4jo5vb6iqsvettqc24ypcbizagw7i4x6hc2kapwsf3ni 
#### Address 
> f1gzkt6xc2oscnzcjbsnn6ha25psx5isjyt6ampey
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1yayfsv6whu3rheviucvventj3y6t542xfpb47ei
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb2nzns2s4jo5vb6iqsvettqc24ypcbizagw7i4x6hc2kapwsf3ni

**Comment by fireflyHZ** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceafjcfrz7sv5dvlezbkpycwmb5i7mqw34x3hmcx2274ka4kmrnkww 
#### Address 
> f1gzkt6xc2oscnzcjbsnn6ha25psx5isjyt6ampey
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1fg6jkxsr3twfnyhdlatmq36xca6sshptscds7xa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceafjcfrz7sv5dvlezbkpycwmb5i7mqw34x3hmcx2274ka4kmrnkww

**Comment by Tom-OriginStorage** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaacjjfryztsvdo433dskwncivcmkztvosir6ii4umcsltkg3q5fo 
#### Address 
> f1gzkt6xc2oscnzcjbsnn6ha25psx5isjyt6ampey
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1q6bpjlqia6iemqbrdaxr2uehrhpvoju3qh4lpga
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaacjjfryztsvdo433dskwncivcmkztvosir6ii4umcsltkg3q5fo

**Comment by fireflyHZ** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebboyf4kscebp3mttzkdlnzozdie2udwkv2jt42tdit37fnpgqbbo 
#### Address 
> f1gzkt6xc2oscnzcjbsnn6ha25psx5isjyt6ampey
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1fg6jkxsr3twfnyhdlatmq36xca6sshptscds7xa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebboyf4kscebp3mttzkdlnzozdie2udwkv2jt42tdit37fnpgqbbo

**Comment by stcouldlisa** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecge2nbcbjunvm27zllymp6dqbgkahrgksrxf535cox63fdo4otzq 
#### Address 
> f1gzkt6xc2oscnzcjbsnn6ha25psx5isjyt6ampey
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1jvvltduw35u6inn5tr4nfualyd42bh3vjtylgci
#### Id
> 6889d7ee-c0e8-44e9-af3a-6e2aeb3326ba
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecge2nbcbjunvm27zllymp6dqbgkahrgksrxf535cox63fdo4otzq

**Comment by Joss-Hua** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedurf4zht6kknx6osthqmutvdxwa5ov6bxmkpct2ep26dfpco2yqs 
#### Address 
> f1gzkt6xc2oscnzcjbsnn6ha25psx5isjyt6ampey
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1tfg54zzscugttejv336vivknmsnzzmyudp3t7wi
#### Id
> 6889d7ee-c0e8-44e9-af3a-6e2aeb3326ba
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedurf4zht6kknx6osthqmutvdxwa5ov6bxmkpct2ep26dfpco2yqs

**Comment by kernelogic** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceanvqk73tv2evm75xaqdfmnfyowrph5gbusdbb7lrdbpdb6xyyuqm 
#### Address 
> f1gzkt6xc2oscnzcjbsnn6ha25psx5isjyt6ampey
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### Id
> a32671ac-325e-46d4-9c76-76329baeccff
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceanvqk73tv2evm75xaqdfmnfyowrph5gbusdbb7lrdbpdb6xyyuqm

**Comment by newwebgroup** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceahnry64hxoiy7mxc2b44k23chtf5agmyaysnrchkdaakpvkxrrms 
#### Address 
> f1gzkt6xc2oscnzcjbsnn6ha25psx5isjyt6ampey
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1e77zuityhvvw6u2t6tb5qlnsegy2s67qs4lbbbq
#### Id
> a32671ac-325e-46d4-9c76-76329baeccff
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceahnry64hxoiy7mxc2b44k23chtf5agmyaysnrchkdaakpvkxrrms

**Comment by newwebgroup** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedee5xvfnlplsg64lwptjdbiivb7tcxixlfzfodyf3otpzoalw722 
#### Address 
> f1gzkt6xc2oscnzcjbsnn6ha25psx5isjyt6ampey
#### Datacap Allocated
> 722.00TiB
#### Signer Address
> f1e77zuityhvvw6u2t6tb5qlnsegy2s67qs4lbbbq
#### Id
> 977692a0-14ad-45a7-953f-1cf27188442a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedee5xvfnlplsg64lwptjdbiivb7tcxixlfzfodyf3otpzoalw722

**Comment by Tom-OriginStorage** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebomnu3koqszvv53nenozhkpveqkatrdv3aeczufgedca5mwgblqi 
#### Address 
> f1gzkt6xc2oscnzcjbsnn6ha25psx5isjyt6ampey
#### Datacap Allocated
> 722.00TiB
#### Signer Address
> f1q6bpjlqia6iemqbrdaxr2uehrhpvoju3qh4lpga
#### Id
> 977692a0-14ad-45a7-953f-1cf27188442a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebomnu3koqszvv53nenozhkpveqkatrdv3aeczufgedca5mwgblqi

**Comment by filplus-checker** [comment]
## DataCap and CID Checker Report[^1]
 - Organization: `BDNFT`
 - Client: `f1gzkt6xc2oscnzcjbsnn6ha25psx5isjyt6ampey`
### Storage Provider Distribution
The below table shows the distribution of storage providers that have stored data for this client.

If this is the first time a provider takes verified deal, it will be marked as `new`.

For most of the datacap application, below restrictions should apply.
 - Storage provider should not exceed 25% of total datacap.
 - Storage provider should not be storing duplicate data for more than 20%.
 - Storage provider should have published its public IP address.
 - All storage providers should be located in different regions.

⚠️ 77.36% of total deal sealed by [f01943316](https://filfox.info/en/address/f01943316) are duplicate data.

⚠️ 78.15% of total deal sealed by [f01920091](https://filfox.info/en/address/f01920091) are duplicate data.

⚠️ 81.67% of total deal sealed by [f01699999](https://filfox.info/en/address/f01699999) are duplicate data.

⚠️ 76.01% of total deal sealed by [f01942420](https://filfox.info/en/address/f01942420) are duplicate data.

⚠️ 76.00% of total deal sealed by [f01942425](https://filfox.info/en/address/f01942425) are duplicate data.

⚠️ 76.00% of total deal sealed by [f01777788](https://filfox.info/en/address/f01777788) are duplicate data.

⚠️ 78.59% of total deal sealed by [f01777787](https://filfox.info/en/address/f01777787) are duplicate data.

⚠️ 64.90% of total deal sealed by [f01777786](https://filfox.info/en/address/f01777786) are duplicate data.

⚠️ 75.35% of total deal sealed by [f01777785](https://filfox.info/en/address/f01777785) are duplicate data.

⚠️ 78.01% of total deal sealed by [f01953959](https://filfox.info/en/address/f01953959) are duplicate data.

⚠️ 77.68% of total deal sealed by [f01876488](https://filfox.info/en/address/f01876488) are duplicate data.

⚠️ 68.51% of total deal sealed by [f01953944](https://filfox.info/en/address/f01953944) are duplicate data.

| Provider                                                    |                           Location | Total Deals Sealed | Percentage | Unique Data | Duplicate Deals |
| :---------------------------------------------------------- | ---------------------------------: | -----------------: | ---------: | ----------: | --------------: |
| [f01943316](https://filfox.info/en/address/f01943316)`new`  |         Piscataway, New Jersey, US |         414.91 TiB |     13.95% |   93.94 TiB |          77.36% |
| [f01920091](https://filfox.info/en/address/f01920091)`new`  |       Frankfurt am Main, Hesse, DE |         398.34 TiB |     13.40% |   87.03 TiB |          78.15% |
| [f01699999](https://filfox.info/en/address/f01699999)       |           Zhongshan, Guangdong, CN |         385.09 TiB |     12.95% |   70.59 TiB |          81.67% |
| [f01942420](https://filfox.info/en/address/f01942420)       |           Guangzhou, Guangdong, CN |         353.69 TiB |     11.90% |   84.84 TiB |          76.01% |
| [f01942425](https://filfox.info/en/address/f01942425)       |           Guangzhou, Guangdong, CN |         353.56 TiB |     11.89% |   84.84 TiB |          76.00% |
| [f01777788](https://filfox.info/en/address/f01777788)`new`  | Hong Kong, Central and Western, HK |         230.56 TiB |      7.75% |   55.34 TiB |          76.00% |
| [f01777787](https://filfox.info/en/address/f01777787)`new`  |                Paripark, Seoul, KR |         216.19 TiB |      7.27% |   46.28 TiB |          78.59% |
| [f01777786](https://filfox.info/en/address/f01777786)`new`  |                    Ōi, Saitama, JP |         195.94 TiB |      6.59% |   68.78 TiB |          64.90% |
| [f01777785](https://filfox.info/en/address/f01777785)`new`  |           Singapore, Singapore, SG |         157.81 TiB |      5.31% |   38.91 TiB |          75.35% |
| [f01953959](https://filfox.info/en/address/f01953959)       |           Singapore, Singapore, SG |          93.94 TiB |      3.16% |   20.66 TiB |          78.01% |
| [f01876488](https://filfox.info/en/address/f01876488)       |  Ho Chi Minh City, Ho Chi Minh, VN |          92.56 TiB |      3.11% |   20.66 TiB |          77.68% |
| [f01953944](https://filfox.info/en/address/f01953944)       |           Singapore, Singapore, SG |          65.59 TiB |      2.21% |   20.66 TiB |          68.51% |
| [f01527777](https://filfox.info/en/address/f01527777)       |               Nanning, Guangxi, CN |          15.06 TiB |      0.51% |   15.06 TiB |           0.00% |

![Provider Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/394/1671096648837.png)
### Deal Data Replication
The below table shows how each many unique data are replicated across storage providers.
- No more than 25% of unique data are stored with less than 4 providers.

✔️ Data replication looks healthy.

| Unique Data Size | Total Deals Made | Number of Providers | Deal Percentage |
| ---------------: | ---------------: | ------------------: | --------------: |
|        96.00 GiB |       992.00 GiB |                   3 |           0.03% |
|         1.69 TiB |        31.78 TiB |                   4 |           1.07% |
|         4.50 TiB |        93.44 TiB |                   5 |           3.14% |
|        15.03 TiB |       410.47 TiB |                   6 |          13.81% |
|        25.88 TiB |       843.63 TiB |                   7 |          28.37% |
|        28.03 TiB |       980.28 TiB |                   8 |          32.97% |
|         5.31 TiB |       167.22 TiB |                   9 |           5.62% |
|        13.47 TiB |       445.47 TiB |                  10 |          14.98% |

![Replication Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/394/1671096649581.png)
### Deal Data Shared with other Clients
The below table shows how many unique data are shared with other clients.
Usually different applications owns different data and should not resolve to the same CID.

✔️ No CID sharing has been observed.

[^1]: To manually trigger this report, add a comment with text `checker:manualTrigger`

**Comment by kernelogic** [comment]
No CID sharing, distribution looks healthy. The duplications can be tolerated for the sake of additional replicas.

**Comment by liyunzhi-666** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedz6q6jivkxlz7huulzzz2udvcwggsageslkqbbee72eykr5xltug 
#### Address 
> f1gzkt6xc2oscnzcjbsnn6ha25psx5isjyt6ampey
#### Datacap Allocated
> 722.00TiB
#### Signer Address
> f1pszcrsciyixyuxxukkvtazcokexbn54amf7gvoq
#### Id
> 977692a0-14ad-45a7-953f-1cf27188442a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedz6q6jivkxlz7huulzzz2udvcwggsageslkqbbee72eykr5xltug
