### ISSUE TITLE
[DataCap Application]Beijing Lexun Technology Co., LTD

### ISSUE THREAD

**Issue by Lexunn** [filecoin-project/filecoin-plus-large-datasets#395]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Beijing Lexun Technology Co., LTD
- Website / Social Media: https://www.lexun.ltd/ 
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 3 PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 150 TiB
- On-chain address for first allocation: f17tvb3ejs3ev6owqmkpzomtewgrd6v2sofv7upma

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Lexun Technology was founded in 2016, based on the domestic IT market, with excellent team and innovation ability to actively expand overseas business. It is committed to the enterprise servers, storage, network equipment, safety equipment and weak current security system integration scheme and implementation, including IDC data center cloud computing, artificial intelligence algorithm, the wisdom city park to super content networking business recycling recycling, IT equipment leasing custom change deserve to wait for many business products, technical service system.
Adhering to the "integrity, focus, innovation, win-win" corporate values, for many well-known enterprises to provide professional, high quality products and efficient service, with the wave, dawn, huawei, the Great Wall cloud, H3C, DELL and other well-known brand manufacturers depth of established long-term relations of cooperation, comprehensive and accurate analysis customer scenarios, to provide comprehensive information service support, Help customers upgrade their services quickly.
The company has high-tech enterprise certification and value-added telecom business license, It has passed ISO9001 quality management system certification, ISO20000 Information Technology Service Management system certification, ISO27001 Information security Management system certification, ISO14001 environmental management system certification, ISO45001- occupational health and safety management system certification, and has obtained a number of practical patents and computer software copyright. It provides effective guarantee for customer information construction.
Following the great development opportunities of national Internet +, cloud big data and new infrastructure strategy, the company increases investment in product research and development to create safe, stable, green, out-of-the-box, high-quality, convenient and systematic integrated products, and provide customers with better service to provide integrated system solutions for Internet digital construction.
China association of renewable resources recycling: https://www.lexun.ltd/index.php?c=show&id=109
High and new technology enterprise certificate: https://www.lexun.ltd/index.php?c=show&id=110

Core Business:
https://drive.google.com/file/d/1dlWSR8IdVrgkFPAgqMNNWKbFZMroPzbm/view?usp=sharing
```

What is the primary source of funding for this project?
```
The company's capital injection is the main source of project funds.
```

What other projects/ecosystem stakeholders is this project associated with?
```
We are an independent project.
```

## Use-case details

Describe the data being stored onto Filecoin
```
Product and business video data, which can be used on public websites and general product introduction, will also be stored including but not limited to computer room operation data, training and analysis data of intelligent robots and aircraft, log analysis of massive website visits and other data. These data will also be desensitized and stored in filecoin network.
```

Where was the data in this dataset sourced from?
```
The data generated in the business.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
Here are samples of the data we intend to store:
1. https://drive.google.com/drive/folders/1dtNpUpjxuoFC4p0QXsl2W7Fblg8DEJvV?usp=sharing
2. https://drive.google.com/drive/folders/1a-PKV6mvFkHH2iI4_wPVXKGfUhyy027G?usp=sharing
3. https://drive.google.com/drive/folders/1uOv8AVHABFgRP-PrIMhH2cOvwvrp_eVf?usp=sharing 
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Confirmed.
```

What is the expected retrieval frequency for this data?
```
We do not visit the data very often, once or twice a year expected.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
We'd like permanent storage.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
We tend to choose Asia for storage.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Both online and offline storage are available.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We will look for storage providers on Slack, but before that we will fully consider how long they have been worked in the Filecoin network to ensure that they will help us store data safely and steadily.
```

How will you be distributing deals across storage providers?
```
Allocation is based on the storage capacity of the storage providers.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes,of courese.We hope to be approved as soon as possible.
```

**Comment by Sunnyiscoming** [comment]
@Lexunn  Hey. Could you send an email to [filplus@fil.org](mailto:filplus@fil.org) with your official domain in order to confirm your identity?

**Comment by Lexunn** [comment]
@Sunnyiscoming Please check the email,thanks.

**Comment by galen-mcandrew** [comment]
## Datacap Request Trigger
#### Total DataCap requested 
> 3PiB
#### Expected weekly DataCap usage rate 
> 150TiB 
#### Client address
> f17tvb3ejs3ev6owqmkpzomtewgrd6v2sofv7upma

**Comment by BlockMakeronline** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedyw56rr5soavgfrp4nu5da6onkdtc73pqsk5m2n4cp7adwfw43b6 
#### Address 
> f17tvb3ejs3ev6owqmkpzomtewgrd6v2sofv7upma
#### Datacap Allocated
> 75.00TiB
#### Signer Address
> f1o3twrcpwjtpcd4q36lpq4qmy2qfbgtyy5h6tsty
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedyw56rr5soavgfrp4nu5da6onkdtc73pqsk5m2n4cp7adwfw43b6

**Comment by MRJAVAZHAO** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceamgwzigj7q4q7sfnha2hxlgmdygwezabmhyseabqv3bnwmvx7j64 
#### Address 
> f17tvb3ejs3ev6owqmkpzomtewgrd6v2sofv7upma
#### Datacap Allocated
> 150.00TiB
#### Signer Address
> f14gme3f52prtyzk6pblogrdd6b6ivp4swc6qmesi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceamgwzigj7q4q7sfnha2hxlgmdygwezabmhyseabqv3bnwmvx7j64

**Comment by swatchliu** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec6ihnz6jhbqew2lmiq4olibap65v77ykfm4pxeucy7eo4izn4two 
#### Address 
> f17tvb3ejs3ev6owqmkpzomtewgrd6v2sofv7upma
#### Datacap Allocated
> 150.00TiB
#### Signer Address
> f1yh6q3nmsg7i2sys7f7dexcuajgoweudcqj2chfi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec6ihnz6jhbqew2lmiq4olibap65v77ykfm4pxeucy7eo4izn4two

**Comment by BigD-Exchange** [comment]
@Lexunn Hi! Great to see you have gotten approval for DataCap. If you are looking for storage providers to store these data or have any questions, please visit #bigdata-exchange on Filecoin Slack or reply here. 

We have strong demand from a diverse group of SPs, who are actively looking to onboard more data.

**Comment by BlockMakeronline** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaz4ikepopygsvqldiuz3e65aea5j4mblcfuug33ukq6kowk2n6we 
#### Address 
> f17tvb3ejs3ev6owqmkpzomtewgrd6v2sofv7upma
#### Datacap Allocated
> 300.00TiB
#### Signer Address
> f1o3twrcpwjtpcd4q36lpq4qmy2qfbgtyy5h6tsty
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaz4ikepopygsvqldiuz3e65aea5j4mblcfuug33ukq6kowk2n6we

**Comment by PluskitOfficial** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb6ala6acoqxrpamoeaktnr3yfb7z5yuq2qtosxchz4koezi2v2lg 
#### Address 
> f17tvb3ejs3ev6owqmkpzomtewgrd6v2sofv7upma
#### Datacap Allocated
> 300.00TiB
#### Signer Address
> f1tgnlhtcmhwipfm7thsftxhn5k52velyjlazpvka
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb6ala6acoqxrpamoeaktnr3yfb7z5yuq2qtosxchz4koezi2v2lg

**Comment by MatrixStorage** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedsxqfojifmsdy6aajmn2zelmatpl64bzr7qcwnf7xcacxahw246e 
#### Address 
> f17tvb3ejs3ev6owqmkpzomtewgrd6v2sofv7upma
#### Datacap Allocated
> 600.00TiB
#### Signer Address
> f1tbxqwjxfyv7swsdin4einirlsfquv3vnmlapley
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedsxqfojifmsdy6aajmn2zelmatpl64bzr7qcwnf7xcacxahw246e

**Comment by MRJAVAZHAO** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced72anueqpj5zpgxmsxwot7wymxzwftixnqoes5azyplleds2hxwi 
#### Address 
> f17tvb3ejs3ev6owqmkpzomtewgrd6v2sofv7upma
#### Datacap Allocated
> 600.00TiB
#### Signer Address
> f14gme3f52prtyzk6pblogrdd6b6ivp4swc6qmesi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced72anueqpj5zpgxmsxwot7wymxzwftixnqoes5azyplleds2hxwi

**Comment by PluskitOfficial** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec4vyhd2t3ucpfem76n4m2njpswnn365n3rhkqktjeydnsgw2agfk 
#### Address 
> f17tvb3ejs3ev6owqmkpzomtewgrd6v2sofv7upma
#### Datacap Allocated
> 1.17PiB
#### Signer Address
> f1tgnlhtcmhwipfm7thsftxhn5k52velyjlazpvka
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec4vyhd2t3ucpfem76n4m2njpswnn365n3rhkqktjeydnsgw2agfk

**Comment by BlockMakeronline** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb2fc3wqg4phu7ghye7el5ik6inr2sowmdwjyka6ta5kbnizplqik 
#### Address 
> f17tvb3ejs3ev6owqmkpzomtewgrd6v2sofv7upma
#### Datacap Allocated
> 1.17PiB
#### Signer Address
> f1o3twrcpwjtpcd4q36lpq4qmy2qfbgtyy5h6tsty
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb2fc3wqg4phu7ghye7el5ik6inr2sowmdwjyka6ta5kbnizplqik

**Comment by filplus-checker** [comment]
## DataCap and CID Checker Report[^1]
 - Organization: `Beijing Lexun Technology Co., LTD`
 - Client: `f17tvb3ejs3ev6owqmkpzomtewgrd6v2sofv7upma`
### Storage Provider Distribution
The below table shows the distribution of storage providers that have stored data for this client.

If this is the first time a provider takes verified deal, it will be marked as `new`.

For most of the datacap application, below restrictions should apply.
 - Storage provider should not exceed 25% of total datacap.
 - Storage provider should not be storing duplicate data for more than 20%.
 - Storage provider should have published its public IP address.
 - All storage providers should be located in different regions.

⚠️ 39.51% of total deal sealed by [f01852664](https://filfox.info/en/address/f01852664) are duplicate data.

⚠️ 41.73% of total deal sealed by [f01938718](https://filfox.info/en/address/f01938718) are duplicate data.

⚠️ 36.61% of total deal sealed by [f01852677](https://filfox.info/en/address/f01852677) are duplicate data.

⚠️ 34.87% of total deal sealed by [f01938717](https://filfox.info/en/address/f01938717) are duplicate data.

⚠️ 39.23% of total deal sealed by [f01938665](https://filfox.info/en/address/f01938665) are duplicate data.

⚠️ 38.28% of total deal sealed by [f01938714](https://filfox.info/en/address/f01938714) are duplicate data.

⚠️ 47.08% of total deal sealed by [f01938721](https://filfox.info/en/address/f01938721) are duplicate data.

⚠️ 32.93% of total deal sealed by [f01852023](https://filfox.info/en/address/f01852023) are duplicate data.

⚠️ 32.26% of total deal sealed by [f01852325](https://filfox.info/en/address/f01852325) are duplicate data.

⚠️ 37.07% of total deal sealed by [f01851482](https://filfox.info/en/address/f01851482) are duplicate data.

| Provider                                              |                           Location | Total Deals Sealed | Percentage | Unique Data | Duplicate Deals |
| :---------------------------------------------------- | ---------------------------------: | -----------------: | ---------: | ----------: | --------------: |
| [f01852664](https://filfox.info/en/address/f01852664) |           Singapore, Singapore, SG |         164.19 TiB |     14.62% |   99.31 TiB |          39.51% |
| [f01938718](https://filfox.info/en/address/f01938718) |    Morrisville, North Carolina, US |         151.34 TiB |     13.48% |   88.19 TiB |          41.73% |
| [f01852677](https://filfox.info/en/address/f01852677) |    Morrisville, North Carolina, US |         137.44 TiB |     12.24% |   87.13 TiB |          36.61% |
| [f01938717](https://filfox.info/en/address/f01938717) |           Singapore, Singapore, SG |         121.00 TiB |     10.78% |   78.81 TiB |          34.87% |
| [f01938665](https://filfox.info/en/address/f01938665) |     Sham Shui Po, Sham Shui Po, HK |         120.84 TiB |     10.76% |   73.44 TiB |          39.23% |
| [f01938714](https://filfox.info/en/address/f01938714) |     Sham Shui Po, Sham Shui Po, HK |         120.81 TiB |     10.76% |   74.56 TiB |          38.28% |
| [f01938721](https://filfox.info/en/address/f01938721) | Hong Kong, Central and Western, HK |         120.41 TiB |     10.73% |   63.72 TiB |          47.08% |
| [f01852023](https://filfox.info/en/address/f01852023) |                   Busan, Busan, KR |          72.13 TiB |      6.42% |   48.38 TiB |          32.93% |
| [f01852325](https://filfox.info/en/address/f01852325) | Hong Kong, Central and Western, HK |          69.66 TiB |      6.20% |   47.19 TiB |          32.26% |
| [f01851482](https://filfox.info/en/address/f01851482) |                   Busan, Busan, KR |          44.84 TiB |      3.99% |   28.22 TiB |          37.07% |

![Provider Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/395/1671096665126.png)
### Deal Data Replication
The below table shows how each many unique data are replicated across storage providers.
- No more than 25% of unique data are stored with less than 4 providers.

⚠️ 83.12% of deals are for data replicated across less than 4 storage providers.

| Unique Data Size | Total Deals Made | Number of Providers | Deal Percentage |
| ---------------: | ---------------: | ------------------: | --------------: |
|       145.06 TiB |       300.09 TiB |                   1 |          26.73% |
|        78.25 TiB |       276.59 TiB |                   2 |          24.64% |
|        77.84 TiB |       356.44 TiB |                   3 |          31.75% |
|        37.56 TiB |       185.94 TiB |                   4 |          16.56% |
|       736.00 GiB |         3.59 TiB |                   5 |           0.32% |

![Replication Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/395/1671096665893.png)
### Deal Data Shared with other Clients
The below table shows how many unique data are shared with other clients.
Usually different applications owns different data and should not resolve to the same CID.

⚠️ CID sharing has been observed.

| Other Client                                                                                                                                                                                                              | Application                                                                                                                    | Total Deals Affected | Unique CIDs |        Verifier |
| :------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ | :----------------------------------------------------------------------------------------------------------------------------- | -------------------: | ----------: | --------------: |
| [f1cuboogcwais57dljrpeltoy6ja2itb7wvwmrl3q](https://filfox.info/en/address/f1cuboogcwais57dljrpeltoy6ja2itb7wvwmrl3q)                                                                                                     | [Penglaiju](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/400)                                       |           201.72 TiB |       2,994 | LDN v3 multisig |
| [f3w4wlayytfmsay6gu5phhij5r4yyx7t4xxrlosgo<br/>tlmqg5eih3co5atsra4h2pe4qd2d6c76bvhj6nwim<br/>7lgq](https://filfox.info/en/address/f3w4wlayytfmsay6gu5phhij5r4yyx7t4xxrlosgotlmqg5eih3co5atsra4h2pe4qd2d6c76bvhj6nwim7lgq) | [GMWBR INC](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/73)                                        |           131.09 TiB |       1,886 | LDN v3 multisig |
| [f1elncewt3sh356aop52uvcappblxmf6asbmhxlya](https://filfox.info/en/address/f1elncewt3sh356aop52uvcappblxmf6asbmhxlya)                                                                                                     | [Beijing Wanjie Data Technology Co\., LTD](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/404)        |            72.72 TiB |       1,446 | LDN v3 multisig |
| [f1piaz4nodpwdemrfqak5jlfg5ois2onzmjv6fkki](https://filfox.info/en/address/f1piaz4nodpwdemrfqak5jlfg5ois2onzmjv6fkki)                                                                                                     | [Chengdu Yundianshang Technology Co\., LTD](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/399)       |            71.97 TiB |         919 | LDN v3 multisig |
| [f14nyld75bnvr2y3ca4ew7vxmwp4tuwytqwggthcy](https://filfox.info/en/address/f14nyld75bnvr2y3ca4ew7vxmwp4tuwytqwggthcy)                                                                                                     | `Kimoc`                                                                                                                        |            37.00 TiB |         829 | LDN v3 multisig |
| [f3uils5cdx3ezyzszjjfnulugknbdsanmqtisd7x7<br/>xkfcljdnshp4jspnrgxpldt5b4aafuz4q4rkebpjy<br/>keha](https://filfox.info/en/address/f3uils5cdx3ezyzszjjfnulugknbdsanmqtisd7x7xkfcljdnshp4jspnrgxpldt5b4aafuz4q4rkebpjykeha) | [Qingyun Education Fund](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/31)                           |            28.44 TiB |         568 | LDN v3 multisig |
| [f14uxcyaoab3qhn42kaquqysga6f6zfry3x4nk3ca](https://filfox.info/en/address/f14uxcyaoab3qhn42kaquqysga6f6zfry3x4nk3ca)                                                                                                     | [ China Tianying INC\.](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/426)                           |            16.69 TiB |         369 | LDN v3 multisig |
| [f1budai5eqmk7zjfd54bmnkj72vuc7jykmkkttgha](https://filfox.info/en/address/f1budai5eqmk7zjfd54bmnkj72vuc7jykmkkttgha)                                                                                                     | ``                                                                                                                             |             5.06 TiB |         105 |        LDN # 64 |
| [f3xffjctbyy7zigopfa3za5ha3pvv4z3xfghlw7kw<br/>vyeuabkg4lzsgfwhnghwkvmmvi6yso6k52hq3ca6c<br/>kveq](https://filfox.info/en/address/f3xffjctbyy7zigopfa3za5ha3pvv4z3xfghlw7kwvyeuabkg4lzsgfwhnghwkvmmvi6yso6k52hq3ca6ckveq) | [Chengdu Digital Media Industry Base Co\., Ltd\.](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/387) |           832.00 GiB |          17 | LDN v3 multisig |
| [f3woqxpu6ekmj43nmpcv7j2pgu6lejxtzgxpzl6f2<br/>vrueoqlzjntakyhdkghymyffbzfbsio6dvfmy643x<br/>4y7q](https://filfox.info/en/address/f3woqxpu6ekmj43nmpcv7j2pgu6lejxtzgxpzl6f2vrueoqlzjntakyhdkghymyffbzfbsio6dvfmy643x4y7q) | [RICH ST PETE LLC](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/64)                                 |           320.00 GiB |           5 | LDN v3 multisig |
| [f3qvn7f5u4z5w5pqx3htckp4jcn5dvgmebq6qkqcz<br/>xdxkicwokf75tt5hbwtrjwldz2sjiyq752ajcn3nd<br/>5tgq](https://filfox.info/en/address/f3qvn7f5u4z5w5pqx3htckp4jcn5dvgmebq6qkqczxdxkicwokf75tt5hbwtrjwldz2sjiyq752ajcn3nd5tgq) | [Beijing Haishi Hengtong Technology Co\., LTD](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/66)     |            96.00 GiB |           2 | LDN v3 multisig |

[^1]: To manually trigger this report, add a comment with text `checker:manualTrigger`

**Comment by cryptowhizzard** [comment]
Hello,

It seems that there is a lot of CID sharing and it looks like you did not store the data as stated in the LDN application.

Can you tell us what happened?
