### ISSUE TITLE
[DataCap Application]Chengdu Yundianshang Technology Co., LTD

### ISSUE THREAD

**Issue by lucasonione** [filecoin-project/filecoin-plus-large-datasets#399]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Chengdu Yundianshang Technology Co., LTD
- Website / Social Media: fs028.com
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 1 PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100 TiB
- On-chain address for first allocation: f1piaz4nodpwdemrfqak5jlfg5ois2onzmjv6fkki

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Chengdu Yundianshang Technology Co., LTD., founded in 2017, is an Internet technology company with independent research and development products and core technologies. 
We comply with the "Internet +" the trend of The Times, the rapid integration of Internet technology, based on the retail store management system research and development, combined with the large data analysis, market control and refinement operations, targeted to propose solutions, and is the only company in Chinese southwest market for Internet cafe technology provider, at the same time, our response to market demand, Internet cafes Focus on creating the core product for Internet cafes: Fshangyigou, and quickly won the recognition and trust of chengdu market, in October 2018, has reached more than 1200 cooperative businesses. 
```

What is the primary source of funding for this project?
```
Enterprise income.
```

What other projects/ecosystem stakeholders is this project associated with?
```
No.
```

## Use-case details

Describe the data being stored onto Filecoin
```
- Internet bar network technology solutions;
- Business data of mall website/client/cashier/voice terminal, including text, picture, audio, video (desensitization information) and cookies and other data;
-User demand research report, and product upgrade and supporting document data involved in the research report;
- Solution data of big data analysis: for example, the favorite products of Internet cafe consumers, the most likely time period of purchase, product warning prompt, etc.
```

Where was the data in this dataset sourced from?
```
Data generated during the operation of our business.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
[Data samples.zip](https://github.com/filecoin-project/filecoin-plus-large-datasets/files/8988436/Data.samples.zip)
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes, it is public.
```

What is the expected retrieval frequency for this data?
```
Current retrieval frequency is expected to be twice a year.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
About five years.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
We accept making storage deals in all regions.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
We will distribute our data to storage providers through offline data transfer.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We will choose the storage providers through Filecoin explorer and other related  website.
```

How will you be distributing deals across storage providers?
```
We will distribute deals to as many storage providers as possible and ensure that no more than 25% of each provider is available.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes. We have contacted with storage providers and data disks are ready.
```

**Comment by Sunnyiscoming** [comment]
Can you provide your data samples here?

**Comment by lucasonione** [comment]
@Sunnyiscoming We have added data samples here, please check it.

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
[Data samples.zip](https://github.com/filecoin-project/filecoin-plus-large-datasets/files/8988436/Data.samples.zip)
```

**Comment by Sunnyiscoming** [comment]
@lucasonione  Hey. Could you send an email to filplus@fil.org with your official domain in order to confirm your identity?

**Comment by galen-mcandrew** [comment]
## Datacap Request Trigger
#### Total DataCap requested 
> 1PiB
#### Expected weekly DataCap usage rate 
> 100TiB 
#### Client address
> f1piaz4nodpwdemrfqak5jlfg5ois2onzmjv6fkki

**Comment by BlockMakeronline** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaygqn6x5rntiuqkiwh5vngxcsmpsrjas4cvisakxivv5snu6ol54 
#### Address 
> f1piaz4nodpwdemrfqak5jlfg5ois2onzmjv6fkki
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1o3twrcpwjtpcd4q36lpq4qmy2qfbgtyy5h6tsty
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaygqn6x5rntiuqkiwh5vngxcsmpsrjas4cvisakxivv5snu6ol54

**Comment by PluskitOfficial** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaegc5yaovbt7zkiiiojvqyzqruriqrtrnjmpkq5mzjt4j4yobdnq 
#### Address 
> f1piaz4nodpwdemrfqak5jlfg5ois2onzmjv6fkki
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1tgnlhtcmhwipfm7thsftxhn5k52velyjlazpvka
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaegc5yaovbt7zkiiiojvqyzqruriqrtrnjmpkq5mzjt4j4yobdnq

**Comment by BigD-Exchange** [comment]
@lucasonione Hi! Great to see you have gotten approval for DataCap. If you are looking for storage providers to store these data or have any questions, please visit #bigdata-exchange on Filecoin Slack or reply here. 

We have strong demand from a diverse group of SPs, who are actively looking to onboard more data.

**Comment by MRJAVAZHAO** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceawjjl433or26cl7y23bnvzj6ygq7klcg7tqfzbhckhnvox7ka2ee 
#### Address 
> f1piaz4nodpwdemrfqak5jlfg5ois2onzmjv6fkki
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f14gme3f52prtyzk6pblogrdd6b6ivp4swc6qmesi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceawjjl433or26cl7y23bnvzj6ygq7klcg7tqfzbhckhnvox7ka2ee

**Comment by MatrixStorage** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced7xffiletggkrz4zigkwuotofxtaqzyahj2vjnivhg5sdajquyiu 
#### Address 
> f1piaz4nodpwdemrfqak5jlfg5ois2onzmjv6fkki
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1tbxqwjxfyv7swsdin4einirlsfquv3vnmlapley
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced7xffiletggkrz4zigkwuotofxtaqzyahj2vjnivhg5sdajquyiu

**Comment by MRJAVAZHAO** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebcmqxox5g44ui3ppw4w572nmuqyurtb25ia353gjrb6jfh3k7guy 
#### Address 
> f1piaz4nodpwdemrfqak5jlfg5ois2onzmjv6fkki
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f14gme3f52prtyzk6pblogrdd6b6ivp4swc6qmesi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebcmqxox5g44ui3ppw4w572nmuqyurtb25ia353gjrb6jfh3k7guy

**Comment by PluskitOfficial** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedfpfj2zwfwvhum7wkk4vzdumucmq45muztyzjmmjnvelanm6ewwu 
#### Address 
> f1piaz4nodpwdemrfqak5jlfg5ois2onzmjv6fkki
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1tgnlhtcmhwipfm7thsftxhn5k52velyjlazpvka
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedfpfj2zwfwvhum7wkk4vzdumucmq45muztyzjmmjnvelanm6ewwu

**Comment by BlockMakeronline** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceblhycaihggsyehfv5la2qqsrknhekqhsmguuy2juwelqnc62tyyo 
#### Address 
> f1piaz4nodpwdemrfqak5jlfg5ois2onzmjv6fkki
#### Datacap Allocated
> 474.00TiB
#### Signer Address
> f1o3twrcpwjtpcd4q36lpq4qmy2qfbgtyy5h6tsty
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceblhycaihggsyehfv5la2qqsrknhekqhsmguuy2juwelqnc62tyyo

**Comment by filplus-checker** [comment]
## DataCap and CID Checker Report[^1]
 - Organization: `Chengdu Yundianshang Technology Co., LTD`
 - Client: `f1piaz4nodpwdemrfqak5jlfg5ois2onzmjv6fkki`
### Storage Provider Distribution
The below table shows the distribution of storage providers that have stored data for this client.

If this is the first time a provider takes verified deal, it will be marked as `new`.

For most of the datacap application, below restrictions should apply.
 - Storage provider should not exceed 25% of total datacap.
 - Storage provider should not be storing duplicate data for more than 20%.
 - Storage provider should have published its public IP address.
 - All storage providers should be located in different regions.

⚠️ 89.80% of total deal sealed by [f01919535](https://filfox.info/en/address/f01919535) are duplicate data.

⚠️ 38.62% of total deal sealed by [f01938718](https://filfox.info/en/address/f01938718) are duplicate data.

⚠️ 40.26% of total deal sealed by [f01938714](https://filfox.info/en/address/f01938714) are duplicate data.

⚠️ 36.12% of total deal sealed by [f01938721](https://filfox.info/en/address/f01938721) are duplicate data.

⚠️ 37.14% of total deal sealed by [f01938717](https://filfox.info/en/address/f01938717) are duplicate data.

⚠️ 33.99% of total deal sealed by [f01938665](https://filfox.info/en/address/f01938665) are duplicate data.

⚠️ 35.59% of total deal sealed by [f01852677](https://filfox.info/en/address/f01852677) are duplicate data.

⚠️ 39.73% of total deal sealed by [f01852664](https://filfox.info/en/address/f01852664) are duplicate data.

⚠️ 34.86% of total deal sealed by [f01852023](https://filfox.info/en/address/f01852023) are duplicate data.

⚠️ 36.50% of total deal sealed by [f01852325](https://filfox.info/en/address/f01852325) are duplicate data.

⚠️ 33.01% of total deal sealed by [f01851482](https://filfox.info/en/address/f01851482) are duplicate data.

| Provider                                              |                           Location | Total Deals Sealed | Percentage | Unique Data | Duplicate Deals |
| :---------------------------------------------------- | ---------------------------------: | -----------------: | ---------: | ----------: | --------------: |
| [f01919535](https://filfox.info/en/address/f01919535) |                   Wuhan, Hubei, CN |         160.00 TiB |     15.63% |   16.31 TiB |          89.80% |
| [f01938718](https://filfox.info/en/address/f01938718) |    Morrisville, North Carolina, US |         110.53 TiB |     10.79% |   67.84 TiB |          38.62% |
| [f01938714](https://filfox.info/en/address/f01938714) |     Sham Shui Po, Sham Shui Po, HK |         106.34 TiB |     10.39% |   63.53 TiB |          40.26% |
| [f01938721](https://filfox.info/en/address/f01938721) | Hong Kong, Central and Western, HK |         105.72 TiB |     10.32% |   67.53 TiB |          36.12% |
| [f01938717](https://filfox.info/en/address/f01938717) |           Singapore, Singapore, SG |         105.59 TiB |     10.31% |   66.38 TiB |          37.14% |
| [f01938665](https://filfox.info/en/address/f01938665) |     Sham Shui Po, Sham Shui Po, HK |         105.38 TiB |     10.29% |   69.56 TiB |          33.99% |
| [f01852677](https://filfox.info/en/address/f01852677) |    Morrisville, North Carolina, US |          86.84 TiB |      8.48% |   55.94 TiB |          35.59% |
| [f01852664](https://filfox.info/en/address/f01852664) |           Singapore, Singapore, SG |          75.75 TiB |      7.40% |   45.66 TiB |          39.73% |
| [f01852023](https://filfox.info/en/address/f01852023) |                   Busan, Busan, KR |          70.47 TiB |      6.88% |   45.91 TiB |          34.86% |
| [f01852325](https://filfox.info/en/address/f01852325) | Hong Kong, Central and Western, HK |          49.66 TiB |      4.85% |   31.53 TiB |          36.50% |
| [f01851482](https://filfox.info/en/address/f01851482) |                   Busan, Busan, KR |          47.72 TiB |      4.66% |   31.97 TiB |          33.01% |

![Provider Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/399/1671096728452.png)
### Deal Data Replication
The below table shows how each many unique data are replicated across storage providers.
- No more than 25% of unique data are stored with less than 4 providers.

⚠️ 86.53% of deals are for data replicated across less than 4 storage providers.

| Unique Data Size | Total Deals Made | Number of Providers | Deal Percentage |
| ---------------: | ---------------: | ------------------: | --------------: |
|       141.94 TiB |       371.84 TiB |                   1 |          36.31% |
|        60.06 TiB |       215.84 TiB |                   2 |          21.08% |
|        62.41 TiB |       298.38 TiB |                   3 |          29.14% |
|        25.88 TiB |       128.56 TiB |                   4 |          12.55% |
|         1.88 TiB |         9.38 TiB |                   5 |           0.92% |

![Replication Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/399/1671096729175.png)
### Deal Data Shared with other Clients
The below table shows how many unique data are shared with other clients.
Usually different applications owns different data and should not resolve to the same CID.

⚠️ CID sharing has been observed.

| Other Client                                                                                                                                                                                                              | Application                                                                                                                    | Total Deals Affected | Unique CIDs |        Verifier |
| :------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ | :----------------------------------------------------------------------------------------------------------------------------- | -------------------: | ----------: | --------------: |
| [f3qvn7f5u4z5w5pqx3htckp4jcn5dvgmebq6qkqcz<br/>xdxkicwokf75tt5hbwtrjwldz2sjiyq752ajcn3nd<br/>5tgq](https://filfox.info/en/address/f3qvn7f5u4z5w5pqx3htckp4jcn5dvgmebq6qkqczxdxkicwokf75tt5hbwtrjwldz2sjiyq752ajcn3nd5tgq) | [Beijing Haishi Hengtong Technology Co\., LTD](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/66)     |           123.63 TiB |       1,464 | LDN v3 multisig |
| [f3xffjctbyy7zigopfa3za5ha3pvv4z3xfghlw7kw<br/>vyeuabkg4lzsgfwhnghwkvmmvi6yso6k52hq3ca6c<br/>kveq](https://filfox.info/en/address/f3xffjctbyy7zigopfa3za5ha3pvv4z3xfghlw7kwvyeuabkg4lzsgfwhnghwkvmmvi6yso6k52hq3ca6ckveq) | [Chengdu Digital Media Industry Base Co\., Ltd\.](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/387) |            55.66 TiB |         675 | LDN v3 multisig |
| [f17tvb3ejs3ev6owqmkpzomtewgrd6v2sofv7upma](https://filfox.info/en/address/f17tvb3ejs3ev6owqmkpzomtewgrd6v2sofv7upma)                                                                                                     | [Beijing Lexun Technology Co\., LTD](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/395)              |            48.22 TiB |         919 | LDN v3 multisig |
| [f3w4wlayytfmsay6gu5phhij5r4yyx7t4xxrlosgo<br/>tlmqg5eih3co5atsra4h2pe4qd2d6c76bvhj6nwim<br/>7lgq](https://filfox.info/en/address/f3w4wlayytfmsay6gu5phhij5r4yyx7t4xxrlosgotlmqg5eih3co5atsra4h2pe4qd2d6c76bvhj6nwim7lgq) | [GMWBR INC](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/73)                                        |            42.94 TiB |         576 | LDN v3 multisig |
| [f1cuboogcwais57dljrpeltoy6ja2itb7wvwmrl3q](https://filfox.info/en/address/f1cuboogcwais57dljrpeltoy6ja2itb7wvwmrl3q)                                                                                                     | [Penglaiju](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/400)                                       |            36.31 TiB |         540 | LDN v3 multisig |
| [f1elncewt3sh356aop52uvcappblxmf6asbmhxlya](https://filfox.info/en/address/f1elncewt3sh356aop52uvcappblxmf6asbmhxlya)                                                                                                     | [Beijing Wanjie Data Technology Co\., LTD](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/404)        |            29.38 TiB |         610 | LDN v3 multisig |
| [f14uxcyaoab3qhn42kaquqysga6f6zfry3x4nk3ca](https://filfox.info/en/address/f14uxcyaoab3qhn42kaquqysga6f6zfry3x4nk3ca)                                                                                                     | [ China Tianying INC\.](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/426)                           |            27.97 TiB |         614 | LDN v3 multisig |
| [f1pediuk4kncwp4qxawlope7hzfmd2ran35w54o7y](https://filfox.info/en/address/f1pediuk4kncwp4qxawlope7hzfmd2ran35w54o7y)                                                                                                     | [Qistone Information technology](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/324)                  |             7.19 TiB |         183 | LDN v3 multisig |
| [f14nyld75bnvr2y3ca4ew7vxmwp4tuwytqwggthcy](https://filfox.info/en/address/f14nyld75bnvr2y3ca4ew7vxmwp4tuwytqwggthcy)                                                                                                     | `Kimoc`                                                                                                                        |             4.25 TiB |          95 | LDN v3 multisig |
| [f1budai5eqmk7zjfd54bmnkj72vuc7jykmkkttgha](https://filfox.info/en/address/f1budai5eqmk7zjfd54bmnkj72vuc7jykmkkttgha)                                                                                                     | ``                                                                                                                             |           992.00 GiB |           8 |        LDN # 64 |
| [f3q7ablez3jqkcjukwbzaql7lmbx4ldouu66nexpd<br/>cfvu6kgho3v6gricckt77cgr46tdre2l4zmvha7bs<br/>u7qq](https://filfox.info/en/address/f3q7ablez3jqkcjukwbzaql7lmbx4ldouu66nexpdcfvu6kgho3v6gricckt77cgr46tdre2l4zmvha7bsu7qq) | `MatrixStorage`                                                                                                                |           384.00 GiB |           5 |        LDN # 72 |
| [f3woqxpu6ekmj43nmpcv7j2pgu6lejxtzgxpzl6f2<br/>vrueoqlzjntakyhdkghymyffbzfbsio6dvfmy643x<br/>4y7q](https://filfox.info/en/address/f3woqxpu6ekmj43nmpcv7j2pgu6lejxtzgxpzl6f2vrueoqlzjntakyhdkghymyffbzfbsio6dvfmy643x4y7q) | [RICH ST PETE LLC](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/64)                                 |           352.00 GiB |           6 | LDN v3 multisig |

[^1]: To manually trigger this report, add a comment with text `checker:manualTrigger`
