### ISSUE TITLE
[DataCap Application] ONBUFF

### ISSUE THREAD

**Issue by junghoonkim2222** [filecoin-project/filecoin-plus-large-datasets#40]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Onbuff
- Website / Social Media: [https://onbuff.com/](https://onbuff.com/) , [https://twitter.com/onbuffchain](https://twitter.com/onbuffchain)
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):2Pib
- Weekly allocation of DataCap requested (usually between 1-100TiB): 5tib
- On-chain address for first allocation: f3xbjtaf2zsvnjmfugvxsk3gal66crwn5l4yplua2fpmdecnqh5pva2y7whm7gusnfpykenj5x47leltwb2c3a

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
The Onbuff project has been working to solve the problem of centralization of the value chain of IP (Intellectual Property) business by utilizing blockchain technology.
We have succeeded in securing a large number of major IPs, and have been developing our own Onbuff IP platform that can easily and transparently participate in business using the secured IPs.

**Major project progress
SNK signs IP exclusive license agreement - 2020.03
Started ONBUFF platform planning and development - 2020.03
ANIVERSE signs IP blockchain business agreement - 2020.05
ONBUFF Token (ONIT) listed on the virtual asset exchange Upbit BTC Market - 2020.08
ONBUFF platform IPBLOCK test launch - 2020.09
VOOZ (Pucca) signs IP block chain business agreement - 2020.09
Iconix (Pororo, Tayo) signs IP license agreement - 2020.10
Started development of ONBUFF platform value evaluation system - 2020.11
ONBUFF platform IPBLOCK Beta launch - 2021.02
ONBUFF signs platform partnership with Chainlink - 2021.02
Signed NFT partnership with TheSandBox - 2021.05
ONBUFF Platform (S-NFT) launch and issuance - 2021.07
Opened NFT metaverse service using Pororo IP in The sandbox - 2021.09


```

What is the primary source of funding for this project?
```
All resources necessary to use the Filecoin network are covered through ONBUFF Foundation funds.

```

What other projects/ecosystem stakeholders is this project associated with?
```
ONBUFF is currently under development or has a working platform. Our platforms are IP and NFT market platforms. We work on projects with global companies and project teams like SNK.

```

## Use-case details

Describe the data being stored onto Filecoin
```
ONBUFF has the exclusive right to use the IPs of several partners in the blockchain field. We feel the need to store the generated data through IPFS while working on IP related project. Also, the ONBUFF NFT Marketplace is about to launch soon. We want to safely and permanently store the data generated on this Marketpalce.

```

Where was the data in this dataset sourced from?
```
IP-related data that ONBUFF has the exclusive right to will be stored. Also we plan to store self-generated data while operating IP and NFT Marketplaces.

```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://drive.google.com/drive/folders/1HLR4zhfU9X1OH6xkuCqwPZOiXmkRb6iX?usp=sharing
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Mostly public data will be stored, as only data that we have exclusive rights will be stored. Due to the nature of IP, some sensitive data are inevitably stored as private data, but most data are publicly available data.

```

What is the expected retrieval frequency for this data?
```
It is not yet possible to infer the search volume, but as ONBUFF ecosystem expands, the interest in the data to be stored will also increase. We predict that retrieval frequency will increase in proportion to this.
  
```

For how long do you plan to keep this dataset stored on Filecoin?
```
We plan to keep the dataset permanently, except in special cases.

```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
We plan to store it mainly in Asia, and gradually expand it to other continents.

```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Since we have sufficient development-related abilities, we will be able to judge the level of the miners well. We are also considering the offline data transfer process, that will be not a big deal.

```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We are discussing with several miners focusing on three points: long-term cost, storage stability, and related development capacity. Based on this, we want to select miners to deal with us.

```

How will you be distributing deals across storage providers?
```
Five or more miners will be selected based on the above three points. Then, we plan to store data according to the assigned grade.

```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Currently, we have about 500 Tib of data related to IP and NFT. And If the marketplace to be launched in the future is activated, we estimate that it will generate 100 Gib of data per day and about 500 Gib of data per week. Filecoin community such as slack and github are all active, so we can always contact community if we need any support. For now, we don't need any special help.

```

**Comment by dkkapur** [comment]
## Multisig Notary requested

#### Total DataCap requested
> 2PiB

#### Expected weekly DataCap usage rate
> 5TiB

**Comment by Reiers** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecyunxatmqf5fubkcawmc6mii2xjbrdyt6tl7xbk7vfgcup4vybzw 
#### Address 
> f3xbjtaf2zsvnjmfugvxsk3gal66crwn5l4yplua2fpmdecnqh5pva2y7whm7gusnfpykenj5x47leltwb2c3a
#### Datacap Allocated
> 2TiB
#### Signer Address
> f1oz43ckvmtxmmsfzqm6bpnemqlavz4ifyl524chq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecyunxatmqf5fubkcawmc6mii2xjbrdyt6tl7xbk7vfgcup4vybzw

**Comment by ClarkYin5566** [comment]
Hi @junghoonkim2222 , I am also applying for datacap but still waiting for review. I would like to discuss with you how to proceed and how to promote the development of real data. If possible, please leave your email or contact me: mr.clark.yin@gmail.com

**Comment by Sunnyiscoming** [comment]
Are there any problems with using datacap?
