### ISSUE TITLE
[DataCap Application]Penglaiju

### ISSUE THREAD

**Issue by PengLaiJu2017** [filecoin-project/filecoin-plus-large-datasets#400]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Penglaiju
- Website / Social Media: http://www.weiminsu.cn/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 2 PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 80 TiB
- On-chain address for first allocation:  f1cuboogcwais57dljrpeltoy6ja2itb7wvwmrl3q

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Penglaiju is a professional short-term rental agency affiliated to Beijing Yiqun Information Technology Co., Ltd. As a senior Internet expert and homestay expert, Penglaiju has divided urban homestays or country homestays into two parts: online hosting and offline hosting, to provide homestay owners with the operation management of the online platform and the promotion and operation of each platform to maximize the customer's house to stand out in the market and increase the occupancy rate.
Penglaiju has been engaged in the Internet industry for more than ten years, and has many experienced Internet experts. In terms of network marketing and brand promotion, Penglaiju can establish resource advantages that ordinary landlords do not have for customers to invest in homestay.
In 2017, Penglaiju started the exploration of urban homestays in Xi'an, the first homestay city to test the water. At present, the operation of these homestays is stable. Under the condition of low initial investment cost, the occupancy rate has been about 85%, and the monthly turnover is about 100,000.
Penglaiju mainly provides homestay management system, which provides customers with personalized independent brand, completely independent website management, easy maintenance without technology, multi-terminal support and other services. 
1.Home Stay Room Supply Management: quickly edit and release rooms through background listing management and manage room status with visual calendar.
2.User Order Management: convenient and fast order management and order notification function; strong membership system.
3.Local Specialty Mall: combine the characteristics of local homestays to promote local specialty products; users can easily purchase local specialty products.
4.Personalized Independent Brand: independent website that can bind independent domain name and design brand LOGO.
5.Multi-Terminal Integration: PC/ HTML5 / Official Account /APP
6.WeChat Marketing: built-in HTML5 version, which can quickly access Official Accounts and small programs.
```

What is the primary source of funding for this project?
```
Mainly from company and business revenue.
```

What other projects/ecosystem stakeholders is this project associated with?
```
None.
```

## Use-case details

Describe the data being stored onto Filecoin
```
We will mainly store photos and videos of some houses and the surrounding environment since 2017.
In addition, we will also try to store part of the online system access and business data after desensitization.
```

Where was the data in this dataset sourced from?
```
These data come from offline collection and online system generation in our business process.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://drive.google.com/file/d/1wKbJ2U9aBp1swAJP96LCTkYrjXpy_9nb/view?usp=sharing 
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes, this is a public dataset.
```

What is the expected retrieval frequency for this data?
```
This is only a part of the data we back up and is expected to be retrieved every 1-2 years.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
We plan to keep this part of the data in the filecoin network permanently.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
We plan to store data in China for business reasons.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Both online and offline.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We will look for storage providers in  slack channels. We also hope that storage providers can also actively provide services for us.
In addition, we hope that the storage providers who provide services for us can guarantee that they will continue to provide us with stable storage services, otherwise it will be very troublesome for our data security.
```

How will you be distributing deals across storage providers?
```
We will follow the filecoin rules for storage allocation and will allocate DataCap to as many storage providers as possible.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
We've got the data and the start-up money, and we don't need any more help yet.
```

**Comment by Sunnyiscoming** [comment]
@PengLaiJu2017 Hey. Could you send an email to [filplus@fil.org](mailto:filplus@fil.org) with your official domain in order to confirm your identity?

**Comment by PengLaiJu2017** [comment]
> @PengLaiJu2017 Hey. Could you send an email to [filplus@fil.org](mailto:filplus@fil.org) with your official domain in order to confirm your identity?

Please check

**Comment by galen-mcandrew** [comment]
## Datacap Request Trigger
#### Total DataCap requested 
> 2PiB
#### Expected weekly DataCap usage rate 
> 80TiB 
#### Client address
> f1cuboogcwais57dljrpeltoy6ja2itb7wvwmrl3q

**Comment by BlockMakeronline** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceayh4k6evko7bea5d4radcx4t7trgt6kktdqtl3zjnqiom4f33byq 
#### Address 
> f1cuboogcwais57dljrpeltoy6ja2itb7wvwmrl3q
#### Datacap Allocated
> 40.00TiB
#### Signer Address
> f1o3twrcpwjtpcd4q36lpq4qmy2qfbgtyy5h6tsty
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceayh4k6evko7bea5d4radcx4t7trgt6kktdqtl3zjnqiom4f33byq

**Comment by MatrixStorage** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecuuxf2xsnkqedekhxcfbd2tg4l6efihkv5pqu4t5cztysqmslrqq 
#### Address 
> f1cuboogcwais57dljrpeltoy6ja2itb7wvwmrl3q
#### Datacap Allocated
> 40.00TiB
#### Signer Address
> f1tbxqwjxfyv7swsdin4einirlsfquv3vnmlapley
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecuuxf2xsnkqedekhxcfbd2tg4l6efihkv5pqu4t5cztysqmslrqq

**Comment by BigD-Exchange** [comment]
@PengLaiJu2017 Hi! Great to see you have gotten approval for DataCap. If you are looking for storage providers to store these data or have any questions, please visit #bigdata-exchange on Filecoin Slack or reply here. 

We have strong demand from a diverse group of SPs, who are actively looking to onboard more data.

**Comment by Joss-Hua** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebmdv4rxy7pd2ofrrctzjadn5r3z5aecqtnsozcdocd7nwbudy47a 
#### Address 
> f1cuboogcwais57dljrpeltoy6ja2itb7wvwmrl3q
#### Datacap Allocated
> 80.00TiB
#### Signer Address
> f1tfg54zzscugttejv336vivknmsnzzmyudp3t7wi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebmdv4rxy7pd2ofrrctzjadn5r3z5aecqtnsozcdocd7nwbudy47a

**Comment by MRJAVAZHAO** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedjlx3t3j5oyvue2r6sljw7pp7tm4r57m3busstgzg6k7csnokhoy 
#### Address 
> f1cuboogcwais57dljrpeltoy6ja2itb7wvwmrl3q
#### Datacap Allocated
> 80.00TiB
#### Signer Address
> f14gme3f52prtyzk6pblogrdd6b6ivp4swc6qmesi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedjlx3t3j5oyvue2r6sljw7pp7tm4r57m3busstgzg6k7csnokhoy

**Comment by BigD-Exchange** [comment]
@PengLaiJu2017 Hi! Great to see you have gotten approval for DataCap. If you are looking for more storage providers to store these data or have any questions, please visit #bigdata-exchange on Filecoin Slack or reply here. 

We have strong demand from a diverse group of SPs, who are actively looking to onboard more data.

**Comment by PluskitOfficial** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacearo6pbroorvjgep36gqdut3xpvt54j3tiyrdvrkwyy2jnjfztham 
#### Address 
> f1cuboogcwais57dljrpeltoy6ja2itb7wvwmrl3q
#### Datacap Allocated
> 160.00TiB
#### Signer Address
> f1tgnlhtcmhwipfm7thsftxhn5k52velyjlazpvka
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacearo6pbroorvjgep36gqdut3xpvt54j3tiyrdvrkwyy2jnjfztham

**Comment by MatrixStorage** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedt64bhjjftb3e6u2uvt4zukf3odtbzcya23fdoz7qr5f2sy6ki7a 
#### Address 
> f1cuboogcwais57dljrpeltoy6ja2itb7wvwmrl3q
#### Datacap Allocated
> 160.00TiB
#### Signer Address
> f1tbxqwjxfyv7swsdin4einirlsfquv3vnmlapley
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedt64bhjjftb3e6u2uvt4zukf3odtbzcya23fdoz7qr5f2sy6ki7a

**Comment by MRJAVAZHAO** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced4kxq3vcgfe4xnbs63nry6gd7tjdldojupvkpd6aun4ofwbph2m2 
#### Address 
> f1cuboogcwais57dljrpeltoy6ja2itb7wvwmrl3q
#### Datacap Allocated
> 320.00TiB
#### Signer Address
> f14gme3f52prtyzk6pblogrdd6b6ivp4swc6qmesi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced4kxq3vcgfe4xnbs63nry6gd7tjdldojupvkpd6aun4ofwbph2m2

**Comment by BlockMakeronline** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb24c62tx2mjzsebpqzmovpiijmxiotxh47t7tooqhe3uznbqhbbg 
#### Address 
> f1cuboogcwais57dljrpeltoy6ja2itb7wvwmrl3q
#### Datacap Allocated
> 320.00TiB
#### Signer Address
> f1o3twrcpwjtpcd4q36lpq4qmy2qfbgtyy5h6tsty
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb24c62tx2mjzsebpqzmovpiijmxiotxh47t7tooqhe3uznbqhbbg

**Comment by PluskitOfficial** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced2equggxmlq4pbm46dtjr656lyitgfjmeou5r4xk6l7rxpjolkbm 
#### Address 
> f1cuboogcwais57dljrpeltoy6ja2itb7wvwmrl3q
#### Datacap Allocated
> 640.00TiB
#### Signer Address
> f1tgnlhtcmhwipfm7thsftxhn5k52velyjlazpvka
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced2equggxmlq4pbm46dtjr656lyitgfjmeou5r4xk6l7rxpjolkbm

**Comment by MatrixStorage** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebkyzeqjfthtcfhxgoxaijwnkpvlenilijefvehowxeweaaphm74a 
#### Address 
> f1cuboogcwais57dljrpeltoy6ja2itb7wvwmrl3q
#### Datacap Allocated
> 640.00TiB
#### Signer Address
> f1tbxqwjxfyv7swsdin4einirlsfquv3vnmlapley
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebkyzeqjfthtcfhxgoxaijwnkpvlenilijefvehowxeweaaphm74a

**Comment by BlockMakeronline** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedk4bpk7npagwgcnldrbsnksyqcdnsoj4nas4s64va6vghohsgobq 
#### Address 
> f1cuboogcwais57dljrpeltoy6ja2itb7wvwmrl3q
#### Datacap Allocated
> 640.00TiB
#### Signer Address
> f1o3twrcpwjtpcd4q36lpq4qmy2qfbgtyy5h6tsty
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedk4bpk7npagwgcnldrbsnksyqcdnsoj4nas4s64va6vghohsgobq

**Comment by liyunzhi-666** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceanxdnjafcltereoafm6heiu5zq3jiiw2xxhadnw5tea2ewvwevxm 
#### Address 
> f1cuboogcwais57dljrpeltoy6ja2itb7wvwmrl3q
#### Datacap Allocated
> 640.00TiB
#### Signer Address
> f1pszcrsciyixyuxxukkvtazcokexbn54amf7gvoq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceanxdnjafcltereoafm6heiu5zq3jiiw2xxhadnw5tea2ewvwevxm

**Comment by filplus-checker** [comment]
## DataCap and CID Checker Report[^1]
 - Organization: `Penglaiju`
 - Client: `f1cuboogcwais57dljrpeltoy6ja2itb7wvwmrl3q`
### Storage Provider Distribution
The below table shows the distribution of storage providers that have stored data for this client.

If this is the first time a provider takes verified deal, it will be marked as `new`.

For most of the datacap application, below restrictions should apply.
 - Storage provider should not exceed 25% of total datacap.
 - Storage provider should not be storing duplicate data for more than 20%.
 - Storage provider should have published its public IP address.
 - All storage providers should be located in different regions.

⚠️ 36.56% of total deal sealed by [f01852023](https://filfox.info/en/address/f01852023) are duplicate data.

⚠️ 35.54% of total deal sealed by [f01852677](https://filfox.info/en/address/f01852677) are duplicate data.

⚠️ 35.83% of total deal sealed by [f01852664](https://filfox.info/en/address/f01852664) are duplicate data.

⚠️ 35.15% of total deal sealed by [f01852325](https://filfox.info/en/address/f01852325) are duplicate data.

⚠️ 33.46% of total deal sealed by [f01851482](https://filfox.info/en/address/f01851482) are duplicate data.

⚠️ 42.58% of total deal sealed by [f01938665](https://filfox.info/en/address/f01938665) are duplicate data.

⚠️ 55.15% of total deal sealed by [f01938714](https://filfox.info/en/address/f01938714) are duplicate data.

⚠️ 37.24% of total deal sealed by [f01938717](https://filfox.info/en/address/f01938717) are duplicate data.

⚠️ 89.22% of total deal sealed by [f01255207](https://filfox.info/en/address/f01255207) are duplicate data.

⚠️ [f01255207](https://filfox.info/en/address/f01255207) has unknown IP location.

| Provider                                                    |                           Location | Total Deals Sealed | Percentage | Unique Data | Duplicate Deals |
| :---------------------------------------------------------- | ---------------------------------: | -----------------: | ---------: | ----------: | --------------: |
| [f01852023](https://filfox.info/en/address/f01852023)       |                   Busan, Busan, KR |         291.84 TiB |     24.49% |  185.16 TiB |          36.56% |
| [f01852677](https://filfox.info/en/address/f01852677)       |    Morrisville, North Carolina, US |         238.19 TiB |     19.99% |  153.53 TiB |          35.54% |
| [f01852664](https://filfox.info/en/address/f01852664)       |           Singapore, Singapore, SG |         224.34 TiB |     18.83% |  143.97 TiB |          35.83% |
| [f01852325](https://filfox.info/en/address/f01852325)       | Hong Kong, Central and Western, HK |         221.91 TiB |     18.62% |  143.91 TiB |          35.15% |
| [f01851482](https://filfox.info/en/address/f01851482)       |                   Busan, Busan, KR |         113.28 TiB |      9.51% |   75.38 TiB |          33.46% |
| [f01938665](https://filfox.info/en/address/f01938665)       |     Sham Shui Po, Sham Shui Po, HK |          42.94 TiB |      3.60% |   24.66 TiB |          42.58% |
| [f01938714](https://filfox.info/en/address/f01938714)       |     Sham Shui Po, Sham Shui Po, HK |          35.19 TiB |      2.95% |   15.78 TiB |          55.15% |
| [f01938717](https://filfox.info/en/address/f01938717)       |           Singapore, Singapore, SG |          20.81 TiB |      1.75% |   13.06 TiB |          37.24% |
| [f01255207](https://filfox.info/en/address/f01255207)`new`  |                            Unknown |           3.19 TiB |      0.27% |  352.00 GiB |          89.22% |

![Provider Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/400/1671096743311.png)
### Deal Data Replication
The below table shows how each many unique data are replicated across storage providers.
- No more than 25% of unique data are stored with less than 4 providers.

⚠️ 94.25% of deals are for data replicated across less than 4 storage providers.

| Unique Data Size | Total Deals Made | Number of Providers | Deal Percentage |
| ---------------: | ---------------: | ------------------: | --------------: |
|       204.84 TiB |       366.06 TiB |                   1 |          30.72% |
|       140.41 TiB |       454.19 TiB |                   2 |          38.11% |
|        71.25 TiB |       302.97 TiB |                   3 |          25.42% |
|        14.09 TiB |        68.47 TiB |                   4 |           5.75% |

![Replication Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/400/1671096744069.png)
### Deal Data Shared with other Clients
The below table shows how many unique data are shared with other clients.
Usually different applications owns different data and should not resolve to the same CID.

⚠️ CID sharing has been observed.

| Other Client                                                                                                                                                                                                              | Application                                                                                                                    | Total Deals Affected | Unique CIDs |        Verifier |
| :------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ | :----------------------------------------------------------------------------------------------------------------------------- | -------------------: | ----------: | --------------: |
| [f3w4wlayytfmsay6gu5phhij5r4yyx7t4xxrlosgo<br/>tlmqg5eih3co5atsra4h2pe4qd2d6c76bvhj6nwim<br/>7lgq](https://filfox.info/en/address/f3w4wlayytfmsay6gu5phhij5r4yyx7t4xxrlosgotlmqg5eih3co5atsra4h2pe4qd2d6c76bvhj6nwim7lgq) | [GMWBR INC](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/73)                                        |           276.88 TiB |       4,396 | LDN v3 multisig |
| [f17tvb3ejs3ev6owqmkpzomtewgrd6v2sofv7upma](https://filfox.info/en/address/f17tvb3ejs3ev6owqmkpzomtewgrd6v2sofv7upma)                                                                                                     | [Beijing Lexun Technology Co\., LTD](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/395)              |           210.34 TiB |       2,994 | LDN v3 multisig |
| [f14nyld75bnvr2y3ca4ew7vxmwp4tuwytqwggthcy](https://filfox.info/en/address/f14nyld75bnvr2y3ca4ew7vxmwp4tuwytqwggthcy)                                                                                                     | `Kimoc`                                                                                                                        |           103.22 TiB |       1,684 | LDN v3 multisig |
| [f3xffjctbyy7zigopfa3za5ha3pvv4z3xfghlw7kw<br/>vyeuabkg4lzsgfwhnghwkvmmvi6yso6k52hq3ca6c<br/>kveq](https://filfox.info/en/address/f3xffjctbyy7zigopfa3za5ha3pvv4z3xfghlw7kwvyeuabkg4lzsgfwhnghwkvmmvi6yso6k52hq3ca6ckveq) | [Chengdu Digital Media Industry Base Co\., Ltd\.](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/387) |           100.06 TiB |       1,394 | LDN v3 multisig |
| [f3qvn7f5u4z5w5pqx3htckp4jcn5dvgmebq6qkqcz<br/>xdxkicwokf75tt5hbwtrjwldz2sjiyq752ajcn3nd<br/>5tgq](https://filfox.info/en/address/f3qvn7f5u4z5w5pqx3htckp4jcn5dvgmebq6qkqczxdxkicwokf75tt5hbwtrjwldz2sjiyq752ajcn3nd5tgq) | [Beijing Haishi Hengtong Technology Co\., LTD](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/66)     |            72.66 TiB |       1,370 | LDN v3 multisig |
| [f1elncewt3sh356aop52uvcappblxmf6asbmhxlya](https://filfox.info/en/address/f1elncewt3sh356aop52uvcappblxmf6asbmhxlya)                                                                                                     | [Beijing Wanjie Data Technology Co\., LTD](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/404)        |            34.09 TiB |         599 | LDN v3 multisig |
| [f1piaz4nodpwdemrfqak5jlfg5ois2onzmjv6fkki](https://filfox.info/en/address/f1piaz4nodpwdemrfqak5jlfg5ois2onzmjv6fkki)                                                                                                     | [Chengdu Yundianshang Technology Co\., LTD](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/399)       |            31.94 TiB |         540 | LDN v3 multisig |
| [f14uxcyaoab3qhn42kaquqysga6f6zfry3x4nk3ca](https://filfox.info/en/address/f14uxcyaoab3qhn42kaquqysga6f6zfry3x4nk3ca)                                                                                                     | [ China Tianying INC\.](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/426)                           |            23.53 TiB |         518 | LDN v3 multisig |
| [f3woqxpu6ekmj43nmpcv7j2pgu6lejxtzgxpzl6f2<br/>vrueoqlzjntakyhdkghymyffbzfbsio6dvfmy643x<br/>4y7q](https://filfox.info/en/address/f3woqxpu6ekmj43nmpcv7j2pgu6lejxtzgxpzl6f2vrueoqlzjntakyhdkghymyffbzfbsio6dvfmy643x4y7q) | [RICH ST PETE LLC](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/64)                                 |            12.81 TiB |         216 | LDN v3 multisig |
| [f3uils5cdx3ezyzszjjfnulugknbdsanmqtisd7x7<br/>xkfcljdnshp4jspnrgxpldt5b4aafuz4q4rkebpjy<br/>keha](https://filfox.info/en/address/f3uils5cdx3ezyzszjjfnulugknbdsanmqtisd7x7xkfcljdnshp4jspnrgxpldt5b4aafuz4q4rkebpjykeha) | [Qingyun Education Fund](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/31)                           |            11.16 TiB |         249 | LDN v3 multisig |
| [f3q7ablez3jqkcjukwbzaql7lmbx4ldouu66nexpd<br/>cfvu6kgho3v6gricckt77cgr46tdre2l4zmvha7bs<br/>u7qq](https://filfox.info/en/address/f3q7ablez3jqkcjukwbzaql7lmbx4ldouu66nexpdcfvu6kgho3v6gricckt77cgr46tdre2l4zmvha7bsu7qq) | `MatrixStorage`                                                                                                                |             5.75 TiB |         128 |        LDN # 72 |
| [f1budai5eqmk7zjfd54bmnkj72vuc7jykmkkttgha](https://filfox.info/en/address/f1budai5eqmk7zjfd54bmnkj72vuc7jykmkkttgha)                                                                                                     | ``                                                                                                                             |             3.09 TiB |          68 |        LDN # 64 |
| [f1pediuk4kncwp4qxawlope7hzfmd2ran35w54o7y](https://filfox.info/en/address/f1pediuk4kncwp4qxawlope7hzfmd2ran35w54o7y)                                                                                                     | [Qistone Information technology](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/324)                  |             1.06 TiB |          26 | LDN v3 multisig |
| [f3skkellc7wegakh2blqeu4kkrlzuqy2siymwli7s<br/>ec6eq77c2v4kzgz5ozgnasjl5r52ckameba5kds7h<br/>djda](https://filfox.info/en/address/f3skkellc7wegakh2blqeu4kkrlzuqy2siymwli7sec6eq77c2v4kzgz5ozgnasjl5r52ckameba5kds7hdjda) | [Meizhai Technology](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/75)                               |           768.00 GiB |          19 | LDN v3 multisig |

[^1]: To manually trigger this report, add a comment with text `checker:manualTrigger`

**Comment by Sunnyiscoming** [comment]
Hello, per the https://github.com/filecoin-project/notary-governance/issues/922 for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

This information will be reviewed by Fil+ Governance team to confirm validity and then the application will be allowed to move forward for additional notary review.
