### ISSUE TITLE
[DataCap Allocation] - advertising production

### ISSUE THREAD

**Issue by kimskorea1** [filecoin-project/filecoin-plus-large-datasets#401]
---
name: Large Dataset Notary application
about: Clients should use this application form to request a DataCap allocation via a LDN for a dataset
title: "advertising production"
labels: 'application, Phase: Diligence'
assignees: ''

---
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: kimskorea
- Website / Social Media: https://www.castingn.com
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 500TiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100TiB
- On-chain address for first allocation: f1qddkgwnntv2uby6u4hy5keubofu6pnlpix66cgq
- Region: Asia (excl. Greater China)

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Established in 2003 as a high-performance server specialized company, we are growing significantly by utilizing IoT systems in addition to advertisement production.
```

What is the primary source of funding for this project?
```
It is our own money.
```

What other projects/ecosystem stakeholders is this project associated with?
```
Advertising production, video, iot
```

## Use-case details

Describe the data being stored onto Filecoin
```
High-definition video, photos
```

Where was the data in this dataset sourced from?
```

my company
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
It is an advertising agency.

https://www.castingn.com/static/images/main_renewal/exp_slide1_img.png
https://www.castingn.com/static/images/main_renewal/exp_slide2_img.png
https://www.castingn.com/static/images/main_renewal/exp_slide3_img.png
https://www.castingn.com/static/images/main_renewal/exp_slide4_img.png
https://www.castingn.com/download/castingN_partner_Join.pdf

```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```

of course.
has been revealed
```

What is the expected retrieval frequency for this data?
```
When the device fails, we will recover from the filecoin backup
```

For how long do you plan to keep this dataset stored on Filecoin?
```

30 months
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Asia excl. Greater China
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```


will be distributed online. If the datacap is granted, offline transmission will also be discussed after consultation.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```


We will select 3 to 5 companies to keep the data, and we will select them after a visit if possible. A search function will be added later.
```

How will you be distributing deals across storage providers?
```

Select 3~5 companies by visiting or selecting old companies
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
The funds are sufficient. Please make sure you get the datacap as quickly as possible.
```

**Comment by kimskorea1** [comment]
What is the problem?

**Comment by Sunnyiscoming** [comment]
@kimskorea1 
https://github.com/filecoin-project/filecoin-plus-client-onboarding/issues/1099
https://github.com/filecoin-project/filecoin-plus-client-onboarding/issues/1170
https://github.com/filecoin-project/filecoin-plus-client-onboarding/issues/1323
https://filplus.d.interplanetary.one/clients/f01452694/breakdown

All the datacap you applied for are stored on one storage node. Large datasets require distributed storage nodes which support data retrieval. Have you found some cooperative storage nodes? Can you list them?

**Comment by Sunnyiscoming** [comment]
Any update here?

**Comment by dkkapur** [comment]
Closing this out for now since there was no response to the above questions. Please open up a new application if still relevant.
