### ISSUE TITLE
Speedium - NASA NEX 

### ISSUE THREAD

**Issue by cryptowhizzard** [filecoin-project/filecoin-plus-large-datasets#403]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Speedium network
- Website / Social Media: www.speedium.nl
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 3 PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 300 TiB
- On-chain address for first allocation: f1pc5usvsbfgxxbq7c7quhhg6k7l6y5reiwqr3noy

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Speedium / Dcent has engaged in Slingshot starting 2.6. We have successfully stored more than 15 differerent datasets with 20+ different miners.

```

What is the primary source of funding for this project?
```
Company account
```

What other projects/ecosystem stakeholders is this project associated with?
```
Slingshot competition hosted by Protocol Labs
```

## Use-case details

Describe the data being stored onto Filecoin
```
A collection of Earth science datasets maintained by NASA, including climate change projections and satellite images of the Earth's surface.
```

Where was the data in this dataset sourced from?
```
AWS
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://registry.opendata.aws/nasanex/
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes.
```

What is the expected retrieval frequency for this data?
```
Multiple times p/y
```

For how long do you plan to keep this dataset stored on Filecoin?
```
18 months or longer
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
EU / US / Australia or others who are interested.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
The data will be transferred both offline and online.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We have a few providers who have been working with us during Slingshot Restore program and we'd like to continue working with them for ongoing Slingshot competition.
```

How will you be distributing deals across storage providers?
```
Max 2 copy's per storage provider if stored on different miners / locations.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, we have the resources.
```

**Comment by dkkapur** [comment]
## Datacap Request Trigger
#### Total DataCap requested 
> 3 PiB
#### Expected weekly DataCap usage rate 
> 300 TiB 
#### Client address
> f1pc5usvsbfgxxbq7c7quhhg6k7l6y5reiwqr3noy

**Comment by liyunzhi-666** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec233fg4ysfh56su54acjvw3sckv3pmfza2uuwzgry4xkmimnmqmi 
#### Address 
> f1pc5usvsbfgxxbq7c7quhhg6k7l6y5reiwqr3noy
#### Datacap Allocated
> 150.00TiB
#### Signer Address
> f1pszcrsciyixyuxxukkvtazcokexbn54amf7gvoq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec233fg4ysfh56su54acjvw3sckv3pmfza2uuwzgry4xkmimnmqmi

**Comment by kernelogic** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced5corqgiukey5khgvi65sz4hvgfsaef2gkzieiaoijreeqkfoe6q 
#### Address 
> f1pc5usvsbfgxxbq7c7quhhg6k7l6y5reiwqr3noy
#### Datacap Allocated
> 300.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced5corqgiukey5khgvi65sz4hvgfsaef2gkzieiaoijreeqkfoe6q

**Comment by MegTei** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceafssiiv2g4av5wylejiinavxmhf6jjgvaiiwfsx6kirisakrzzws 
#### Address 
> f1pc5usvsbfgxxbq7c7quhhg6k7l6y5reiwqr3noy
#### Datacap Allocated
> 300.00TiB
#### Signer Address
> f1ystxl2ootvpirpa7ebgwl7vlhwkbx2r4zjxwe5i
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceafssiiv2g4av5wylejiinavxmhf6jjgvaiiwfsx6kirisakrzzws

**Comment by Reiers** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceagy5zfdcsuvihufj6i6ep5s3h5wjj6oxn65rwzfvmi53lpa56cri 
#### Address 
> f1pc5usvsbfgxxbq7c7quhhg6k7l6y5reiwqr3noy
#### Datacap Allocated
> 300.00TiB
#### Signer Address
> f1oz43ckvmtxmmsfzqm6bpnemqlavz4ifyl524chq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceagy5zfdcsuvihufj6i6ep5s3h5wjj6oxn65rwzfvmi53lpa56cri

**Comment by raghavrmadya** [comment]
## DataCap Allocation requested

### Request number 2
#### Multisig Notary address
> f01858410

#### Client address
> f1pc5usvsbfgxxbq7c7quhhg6k7l6y5reiwqr3noy

#### DataCap allocation requested
> 300TiB

**Comment by raghavrmadya** [comment]
## DataCap Allocation requested

### Request number 3
#### Multisig Notary address
> f01858410

#### Client address
> f1pc5usvsbfgxxbq7c7quhhg6k7l6y5reiwqr3noy

#### DataCap allocation requested
> 600TiB

**Comment by kernelogic** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecbsgvn5cuv2cwtofb6xgvx2ag3szkeycqbxok5soxxdh6bedkhzq 
#### Address 
> f1pc5usvsbfgxxbq7c7quhhg6k7l6y5reiwqr3noy
#### Datacap Allocated
> 600.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecbsgvn5cuv2cwtofb6xgvx2ag3szkeycqbxok5soxxdh6bedkhzq

**Comment by s0nik42** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedu45q6g3i2f7mo3cnh2i7llxtnkk2q7caipscug27epv3zjc6xpc 
#### Address 
> f1pc5usvsbfgxxbq7c7quhhg6k7l6y5reiwqr3noy
#### Datacap Allocated
> 600.00TiB
#### Signer Address
> f1wxhnytjmklj2czezaqcfl7eb4nkgmaxysnegwii
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedu45q6g3i2f7mo3cnh2i7llxtnkk2q7caipscug27epv3zjc6xpc

**Comment by kernelogic** [comment]
The "Total DC" granted seems to be wrong?

**Comment by s0nik42** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedkppxiui3sjc5nxjr73unosxok5uggxtgc6lhf7oy4tnc4hnvhso 
#### Address 
> f1pc5usvsbfgxxbq7c7quhhg6k7l6y5reiwqr3noy
#### Datacap Allocated
> 2.34PiB
#### Signer Address
> f1wxhnytjmklj2czezaqcfl7eb4nkgmaxysnegwii
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedkppxiui3sjc5nxjr73unosxok5uggxtgc6lhf7oy4tnc4hnvhso

**Comment by jamerduhgamer** [comment]
@kernelogic is correct. Last tranche was supposed to allocate 600 TiB but was not tracked?

Total DataCap granted for client so far
450TiB

Also, @s0nik42, I see you approved the last tranche of datacap. Don't we have to alternate notaries per datacap allocation?

**Comment by jamerduhgamer** [comment]
Actually, according to https://www.metawave.info/#/clientDetail?clientAddress=f1pc5usvsbfgxxbq7c7quhhg6k7l6y5reiwqr3noy
there has actually only been 450 TiB granted so far. The last approved tranche of 600 TiB never made it through.

@dkkapur, @raghavrmadya

**Comment by xingjitansuo** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceasrshrykqriv5auxy6qc5wgkgpuxxeow26mioncbccq7udr4qaks 
#### Address 
> f1pc5usvsbfgxxbq7c7quhhg6k7l6y5reiwqr3noy
#### Datacap Allocated
> 600.00TiB
#### Signer Address
> f1a2lia2cwwekeubwo4nppt4v4vebxs2frozarz3q
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceasrshrykqriv5auxy6qc5wgkgpuxxeow26mioncbccq7udr4qaks

**Comment by neogeweb3** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedmgmvfdz7jywp2p52sqq4t6duubl62dl7scy5octxxjvrvvvz4ss 
#### Address 
> f1pc5usvsbfgxxbq7c7quhhg6k7l6y5reiwqr3noy
#### Datacap Allocated
> 2.34PiB
#### Signer Address
> f13k5zr6ovc2gjmg3lvd43ladbydhovpylcvbflpa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedmgmvfdz7jywp2p52sqq4t6duubl62dl7scy5octxxjvrvvvz4ss

**Comment by jamerduhgamer** [comment]
Application is still bugged, total datacap granted still reports 450 TiB after another approved allocation.

**Comment by kernelogic** [comment]
The "faucet" is still empty. Need to wait it get refilled before approving any more LDNs.

**Comment by s0nik42** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedbxded3y5ijtlg3s3ivzzb66w3ghzq4huk2ngm4pklkgitd5ns2q 
#### Address 
> f1pc5usvsbfgxxbq7c7quhhg6k7l6y5reiwqr3noy
#### Datacap Allocated
> 2.34PiB
#### Signer Address
> f1wxhnytjmklj2czezaqcfl7eb4nkgmaxysnegwii
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedbxded3y5ijtlg3s3ivzzb66w3ghzq4huk2ngm4pklkgitd5ns2q

**Comment by Reiers** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec7fyvjbelsn2lywejwef5a7m2cz3qqc64wnxsk54djprrgdfk2yg 
#### Address 
> f1pc5usvsbfgxxbq7c7quhhg6k7l6y5reiwqr3noy
#### Datacap Allocated
> 2.34PiB
#### Signer Address
> f1oz43ckvmtxmmsfzqm6bpnemqlavz4ifyl524chq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec7fyvjbelsn2lywejwef5a7m2cz3qqc64wnxsk54djprrgdfk2yg

**Comment by cryptowhizzard** [comment]
Hello @s0nik42 @Reiers 

NasaNex is a relative small dataset. Are you guys ok with it when we use the excess amount of this datacap on our NexRad dataset in issue #340 ?

We are still waiting on RKH approval for the other parts of this set ( issue #483 ), so this would help us to keep going.

**Comment by s0nik42** [comment]
Fine for me

**Comment by filplus-checker** [comment]
## DataCap and CID Checker Report[^1]
 - Organization: `Speedium network`
 - Client: `f1pc5usvsbfgxxbq7c7quhhg6k7l6y5reiwqr3noy`
### Storage Provider Distribution
The below table shows the distribution of storage providers that have stored data for this client.

If this is the first time a provider takes verified deal, it will be marked as `new`.

For most of the datacap application, below restrictions should apply.
 - Storage provider should not exceed 25% of total datacap.
 - Storage provider should not be storing duplicate data for more than 20%.
 - Storage provider should have published its public IP address.
 - All storage providers should be located in different regions.

✔️ Storage provider distribution looks healthy.

| Provider                                                    |                         Location | Total Deals Sealed | Percentage | Unique Data | Duplicate Deals |
| :---------------------------------------------------------- | -------------------------------: | -----------------: | ---------: | ----------: | --------------: |
| [f01919423](https://filfox.info/en/address/f01919423)       |      Sydney, New South Wales, AU |         216.09 TiB |     12.93% |  216.09 TiB |           0.00% |
| [f01901739](https://filfox.info/en/address/f01901739)       |      Sydney, New South Wales, AU |         108.09 TiB |      6.47% |   95.31 TiB |          11.82% |
| [f01938357](https://filfox.info/en/address/f01938357)       |      Sydney, New South Wales, AU |         106.84 TiB |      6.39% |  106.84 TiB |           0.00% |
| [f01878201](https://filfox.info/en/address/f01878201)       |           Hangzhou, Zhejiang, CN |          98.56 TiB |      5.90% |   98.56 TiB |           0.00% |
| [f01926686](https://filfox.info/en/address/f01926686)       |           Hangzhou, Zhejiang, CN |          98.22 TiB |      5.88% |   98.22 TiB |           0.00% |
| [f01962819](https://filfox.info/en/address/f01962819)       |               Xi’an, Shaanxi, CN |          97.16 TiB |      5.81% |   97.16 TiB |           0.00% |
| [f01882184](https://filfox.info/en/address/f01882184)       |         Singapore, Singapore, SG |          96.09 TiB |      5.75% |   96.09 TiB |           0.00% |
| [f01059489](https://filfox.info/en/address/f01059489)       |                 Plano, Texas, US |          95.88 TiB |      5.74% |   92.06 TiB |           3.98% |
| [f01985775](https://filfox.info/en/address/f01985775)       |                Dallas, Texas, US |          95.06 TiB |      5.69% |   95.06 TiB |           0.00% |
| [f01901765](https://filfox.info/en/address/f01901765)       |            Jiaxing, Zhejiang, CN |          90.91 TiB |      5.44% |   90.91 TiB |           0.00% |
| [f01851482](https://filfox.info/en/address/f01851482)       |                 Busan, Busan, KR |          77.84 TiB |      4.66% |   77.84 TiB |           0.00% |
| [f01896422](https://filfox.info/en/address/f01896422)       |          Fremont, California, US |          69.79 TiB |      4.18% |   69.79 TiB |           0.00% |
| [f01858429](https://filfox.info/en/address/f01858429)       |        Boston, Massachusetts, US |          65.59 TiB |      3.92% |   65.59 TiB |           0.00% |
| [f01902461](https://filfox.info/en/address/f01902461)`new`  |             Zhengzhou, Henan, CN |          64.69 TiB |      3.87% |   64.69 TiB |           0.00% |
| [f01907545](https://filfox.info/en/address/f01907545)       |               Xi’an, Shaanxi, CN |          59.00 TiB |      3.53% |   59.00 TiB |           0.00% |
| [f01720359](https://filfox.info/en/address/f01720359)       | Heerhugowaard, North Holland, NL |          45.22 TiB |      2.71% |   45.16 TiB |           0.14% |
| [f01981059](https://filfox.info/en/address/f01981059)`new`  |            Richardson, Texas, US |          45.09 TiB |      2.70% |   45.09 TiB |           0.00% |
| [f01911083](https://filfox.info/en/address/f01911083)       |             Tuusula, Uusimaa, FI |          39.22 TiB |      2.35% |   39.22 TiB |           0.00% |
| [f01852664](https://filfox.info/en/address/f01852664)       |         Singapore, Singapore, SG |          37.38 TiB |      2.24% |   37.38 TiB |           0.00% |
| [f01771403](https://filfox.info/en/address/f01771403)       | Heerhugowaard, North Holland, NL |          28.06 TiB |      1.68% |   27.16 TiB |           3.23% |
| [f01786387](https://filfox.info/en/address/f01786387)       | Heerhugowaard, North Holland, NL |          24.13 TiB |      1.44% |   24.13 TiB |           0.00% |
| [f01908671](https://filfox.info/en/address/f01908671)       |   Philadelphia, Pennsylvania, US |          12.50 TiB |      0.75% |   12.50 TiB |           0.00% |

![Provider Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/403/1671096767443.png)
### Deal Data Replication
The below table shows how each many unique data are replicated across storage providers.
- No more than 25% of unique data are stored with less than 4 providers.

✔️ Data replication looks healthy.

| Unique Data Size | Total Deals Made | Number of Providers | Deal Percentage |
| ---------------: | ---------------: | ------------------: | --------------: |
|        52.35 TiB |        52.35 TiB |                   1 |           3.13% |
|        75.09 TiB |       150.19 TiB |                   2 |           8.99% |
|        11.16 TiB |        33.47 TiB |                   3 |           2.00% |
|        32.00 GiB |       160.00 GiB |                   5 |           0.01% |
|       256.00 GiB |         1.75 TiB |                   7 |           0.10% |
|       576.00 GiB |         4.53 TiB |                   8 |           0.27% |
|         1.28 TiB |        11.53 TiB |                   9 |           0.69% |
|         1.78 TiB |        18.00 TiB |                  10 |           1.08% |
|         2.84 TiB |        31.59 TiB |                  11 |           1.89% |
|         7.16 TiB |        87.09 TiB |                  12 |           5.21% |
|        14.97 TiB |       198.09 TiB |                  13 |          11.85% |
|        25.75 TiB |       364.63 TiB |                  14 |          21.82% |
|        24.81 TiB |       377.16 TiB |                  15 |          22.57% |
|        15.19 TiB |       245.28 TiB |                  16 |          14.68% |
|         5.47 TiB |        93.88 TiB |                  17 |           5.62% |
|        96.00 GiB |         1.72 TiB |                  18 |           0.10% |

![Replication Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/403/1671096768265.png)
### Deal Data Shared with other Clients
The below table shows how many unique data are shared with other clients.
Usually different applications owns different data and should not resolve to the same CID.

⚠️ CID sharing has been observed.

| Other Client                                                                                                          | Application                                                                                     | Total Deals Affected | Unique CIDs |        Verifier |
| :-------------------------------------------------------------------------------------------------------------------- | :---------------------------------------------------------------------------------------------- | -------------------: | ----------: | --------------: |
| [f1ws3n5tuxtyg26lraqkjirz7qon7y7ckju7hhmii](https://filfox.info/en/address/f1ws3n5tuxtyg26lraqkjirz7qon7y7ckju7hhmii) | [Tech Greedy Inc](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/335)  |             1.20 PiB |       4,341 | LDN v3 multisig |
| [f1xafi3wsh7q553efnumhgeomathrehwwd2mye7oy](https://filfox.info/en/address/f1xafi3wsh7q553efnumhgeomathrehwwd2mye7oy) | [Speedium network](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/483) |           917.25 TiB |       4,493 | LDN v3 multisig |
| [f1z7jogzx4x42wtilzb4lu6iotlad5rptt2acbzpi](https://filfox.info/en/address/f1z7jogzx4x42wtilzb4lu6iotlad5rptt2acbzpi) | [Speedium network](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/339) |           229.47 TiB |       3,203 | LDN v3 multisig |

[^1]: To manually trigger this report, add a comment with text `checker:manualTrigger`

**Comment by Tom-zhang987** [comment]
checker:manualTrigger

**Comment by data-programs** [comment]
<img width="32" alt="KYC" Verified src="https://stable.filplus.storage/images/filplus-kyc-verified-badge.png"/>

This user’s identity has been verified through [filplus.storage](https://filplus.storage)
