### ISSUE TITLE
[DataCap Application] yesfile

### ISSUE THREAD

**Issue by paar13kr** [filecoin-project/filecoin-plus-large-datasets#406]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: M&T
- Website / Social Media: yesfile.com
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5Pib
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100Tib
- On-chain address for first allocation: f16aqr37qeoymlc6m7bc7gfjjgawqorbz7l7avlrq

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Our company combines customer service based on network technology and trust and is the largest content exchange in Korea.
It provides contents such as dramas, music, various videos, and books to customers. So We have a lot of videos, images, files.
We've been leading the Internet Webhard business, and we've been working on technology constantly
It is growing as a representative company in Korea and starting with file sharing service,
We will introduce new Peer-To-Peer-based technologies and products that will be adapted to the future E-Business environment
```

What is the primary source of funding for this project?
```
Company account
```

What other projects/ecosystem stakeholders is this project associated with?
```
None
```

## Use-case details

Describe the data being stored onto Filecoin
```
We will store a lot of pictures, videos, and general files.
We will only store materials that are not copyright-related, and only samples will be stored for materials that are copyright-related.
```

Where was the data in this dataset sourced from?
```
Various broadcasting company data, customer uploaded data, company's own data.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
http://image.yesfile.com/data/2016/06/23/1466613063_jOYb.jpg
https://image.yesfile.com/data/2021/07/29/fddc7be081d1365573d8a1d205ed8819.jpg
https://image.yesfile.com/data/2021/07/29/ws_72200030_300_1_40.jpg
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes. confirm it
```

What is the expected retrieval frequency for this data?
```
We expect to retrieve our data every 5 months.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
540 Days
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Mostly in Asia. Korea will store 90% and other countries 10%.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Use offline services for data transfer or data disks, depending on the requirements of the SP providing the storage
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We will choose a stable miner through due diligence. and We will choose places that are large and well-equipped.
```

How will you be distributing deals across storage providers?
```
We will select and save 2-3 miners for each region in Korea and keep a copy of the data.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, we can start trading immediately once we receive the datacap.
```

**Comment by EGGRICE02** [comment]
How can you make sure that data uploaded by users are not copyright-related since you'd like to backup data from your users?
Do you have a license from user that allow you to upload their data to Filecoin Network?
ARE YOU A MINER?https://github.com/filecoin-project/lotus/discussions/8489 https://github.com/filecoin-project/lotus/discussions/8507

**Comment by GaryGJG** [comment]
How many data do you have now?
what storage are you using to store the data ?
what about your data increase rate ?

**Comment by paar13kr** [comment]
@EGGRICE02  
How can you make sure that data uploaded by users are not copyright-related since you'd like to backup data from your users?
 -> We are filtering copyright data through copyright solutions and will upload non-copyright materials based on filtering.
 
Do you have a license from user that allow you to upload their data to Filecoin Network?
 -> Currently, we are going to choice and test the miner to upload the data, and we want to organize the data in the future and upload it with a license.

ARE YOU A MINER?[filecoin-project/lotus#8489](https://github.com/filecoin-project/lotus/discussions/8489) [filecoin-project/lotus#8507](https://github.com/filecoin-project/lotus/discussions/8507)
 -> Yes, I'm miner. I am interested in IPFS, and I am mining because I got to know the filecoin. As I ran Filecoin Miner, I found that by storing our company's data, I could reduce our company's storage and CDN costs.

**Comment by paar13kr** [comment]
@GaryGJG 
How many data do you have now?
-> We have 3.9Pib data. However, not all data can be stored, and non-copyright data will be selected and stored. It is expected to be more than 1Pib.

what storage are you using to store the data ?
-> We commissioned a storage company to use the data. The company is using on-premise storage.
![image](https://user-images.githubusercontent.com/73625067/173537550-22c5a22a-19d4-44a0-b7a6-4c60e1bb8f54.png)

what about your data increase rate ?
-> Data increases by about 12tib per week.
![image](https://user-images.githubusercontent.com/73625067/173538613-9b3d4e7f-dab2-4ce9-95d4-1a0ea70cf753.png)

**Comment by Sunnyiscoming** [comment]
@paar13kr Can you provide more related data samples with the above data description to prove that you have 5 PB data already? Videos would be better.

**Comment by Sunnyiscoming** [comment]
@paar13kr Can you provide more information about the M&T organization? Such as registered address, time of establishment, proof of existence and so on. I can't find anything very specific on the website.

**Comment by paar13kr** [comment]
@Sunnyiscoming 
yesfile.com is a website for services only. A description of the company can be found on the company's website.
company website : http://mntcompany.co.kr/ 
address: 703 HS TOWER 10F, Seolleung-ro, Gangnam-gu, Seoul
time of establishment: 2010.03

**Comment by UnionLabs2020** [comment]
At this time the large dataset process is not intended for storage providers to self-deal. In addition, could you provide more evidence that you have been authorized by the real owner of dataset?

**Comment by Sunnyiscoming** [comment]
@paar13kr Any update here?

**Comment by paar13kr** [comment]
@UnionLabs2020 
What evidence should we provide, for example?

**Comment by raghavrmadya** [comment]
Hi @paar13kr , Can you share more about your SP distribution and how exactly are you filtering copyright data What is the copyright solution?

**Comment by paar13kr** [comment]
@raghavrmadya 
We are proceeding with filtering through murake, a Korean filtering company. (http://www.wisewall.co.kr/business/business_01.html)
We send the DNA (file hash, file size, etc...) of the video data we have to the filtering company to check if it is a copyrighted video file. 
In order to prevent illegal uploads and downloads, we will first share non-copyright data among the data we have.
My SP was made for IPFS understanding and testing purposes. Now, I'm not sealing, and I'm studying by looking at the contents of the file coin being updated.

**Comment by Sunnyiscoming** [comment]
Can you talk about SPs distribution?

**Comment by paar13kr** [comment]
@Sunnyiscoming 
We will visit the SP to verify the condition and stability of the facilities, and we will select 2 to 3 SPs for each region in Korea.
We will distribute our data by region and organize it like CDN so that users can access it more quickly.

**Comment by raghavrmadya** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5 PiB

**Expected weekly DataCap usage rate**

> 100 TiB

**Client address**

> f16aqr37qeoymlc6m7bc7gfjjgawqorbz7l7avlrq

**Comment by paar13kr** [comment]
@raghavrmadya 
Thanks.  We are planning to visit the SP in two region this week and inspect the facilities.

**Comment by psh0691** [comment]
@paar13kr

**Comment by psh0691** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedwkys2xrdlsyz23agv3j4nw4rxswgeznoej2672j6va7ml5c6msm 
#### Address 
> f16aqr37qeoymlc6m7bc7gfjjgawqorbz7l7avlrq
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1qdko4jg25vo35qmyvcrw4ak4fmuu3f5rif2kc7i
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedwkys2xrdlsyz23agv3j4nw4rxswgeznoej2672j6va7ml5c6msm

**Comment by paar13kr** [comment]
@psh0691 
Thanks.  I will try to save the data without any problems.

**Comment by psh0691** [comment]
@paar13kr 
To assign a full data limit, one more notary must approve it.
Please don't let it be an example of data cap abuse.
Also, please note that self-dealing that occurs when SP and client are the same can be controversial.

**Comment by paar13kr** [comment]
@psh0691 
Yes, I'll keep that in mind.
Is it okay to seal my node with textile or estaury in order to study about data cap in the future?
This is to test the storage deal and retrive deal.

**Comment by psh0691** [comment]
@paar13kr 
https://github.com/filecoin-project/filecoin-plus-client-onboarding

**Comment by MetaWaveInfo** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacealh7235xr3kmdlbbyekb5r3advcwtyhqonuhwui4aqqstlkn7dcw 
#### Address 
> f16aqr37qeoymlc6m7bc7gfjjgawqorbz7l7avlrq
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1ktlkcxnmzxcdaoqfsunrg3vocfbmgv4n3mrn74a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacealh7235xr3kmdlbbyekb5r3advcwtyhqonuhwui4aqqstlkn7dcw

**Comment by BigD-Exchange** [comment]
@paar13kr Hi! Great to see you have gotten approval for DataCap. If you are looking for more storage providers to store these data or have any questions, please visit #bigdata-exchange on Filecoin Slack or reply here. 

We have strong demand from a diverse group of SPs, who are actively looking to onboard more data.

**Comment by UnionLabs2020** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceduxzdewdiahwskhrdxb35r2nhvccadlylw7vrjsgf24j574bbf5w 
#### Address 
> f16aqr37qeoymlc6m7bc7gfjjgawqorbz7l7avlrq
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f17xdri3wunqgld7dm23e4f3eqsntjakwc47xjo6i
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceduxzdewdiahwskhrdxb35r2nhvccadlylw7vrjsgf24j574bbf5w

**Comment by MetaWaveInfo** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebquxbftkacgb3rnw22izj3qz74p2agobdkwnylnzffuihfiel2ck 
#### Address 
> f16aqr37qeoymlc6m7bc7gfjjgawqorbz7l7avlrq
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1ktlkcxnmzxcdaoqfsunrg3vocfbmgv4n3mrn74a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebquxbftkacgb3rnw22izj3qz74p2agobdkwnylnzffuihfiel2ck

**Comment by Sunnyiscoming** [comment]
Are there any problems with using datacap?

**Comment by paar13kr** [comment]
@Sunnyiscoming 
It's taking some time to organize the data.
I think it will be available from April.
