### ISSUE TITLE
[DataCap Application]Huifan

### ISSUE THREAD

**Issue by Huifan-Tina0615** [filecoin-project/filecoin-plus-large-datasets#407]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Huifan livestream
- Website / Social Media:http://www.huifan.top/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 200TiB
- On-chain address for first allocation: f1u522dt3zabkgbxxzecl77wgv473yvpecxh6t6zq

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Huifan provides users with full-case planning, live broadcast execution, operation distribution, data result delivery, live video storage services. We support live audio and video interaction, guest sharing in different places, multi-venue live broadcast, professional on-site guarantee, etc.
```

What is the primary source of funding for this project?
```
Our own account.
```

What other projects/ecosystem stakeholders is this project associated with?
```
None.
```

## Use-case details

Describe the data being stored onto Filecoin
```
Videos and images of live shows.
```

Where was the data in this dataset sourced from?
```
We provide services of livestream. We need to store data and prepare some copies.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
[data1_Trim.zip](https://github.com/filecoin-project/filecoin-plus-large-datasets/files/8899338/data1_Trim.zip)
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes. Our livestreams are provided on our public platform.
```

What is the expected retrieval frequency for this data?
```
All data is mainly stored as copies, so the frequency for it may be once a year.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
540 days.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
In Asia.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
We use hard disks such as Seagate for offline data transfer.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
If storage providers want to take our deals, they need to have enough fund and technical support. We welcome more storage providers can join us.
```

How will you be distributing deals across storage providers?
```
We'll divide persentage of deals on the basis of their ability before allocating deals.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes.
```

**Comment by EGGRICE02** [comment]
Hello, @Huifan-Tina0615. Your data are mainly live stream footages, is there any privacy concern or copyright issue to make it public? Some may not be happy to see themselves showing up on the Internet.
BTW, can you clarify how do you plan to transfer data offline with SP?

**Comment by Huifan-Tina0615** [comment]
Hi @EGGRICE02 , thanks for your question.

In our User Service Agreement, we've declared that we can use all data which they uploaded for showing and storing.
We prepared some seagate hard disks like Lyve Mobile Array for offline transfer. We think it is a safe way for us to choose.

**Comment by EGGRICE02** [comment]
@Huifan-Tina0615 Fantastic! One more question, Could you mail to filplus@fil.orgwith your company domain to confirm your identity?

**Comment by Huifan-Tina0615** [comment]
Yes! Already finished.

**Comment by Sunnyiscoming** [comment]
@Huifan-Tina0615 
Can you provide more information about the M&T organization? Such as registered address, time of establishment, proof of existence and so on. I can't find anything very specific on the website.
Can you provide more data samples?

**Comment by Huifan-Tina0615** [comment]
@Sunnyiscoming 
Yes. We registered at HONG KONG CENTRAL, 5-8 QUEEN VICTORIA STREET in August, 2013. 
[dataset.zip](https://github.com/filecoin-project/filecoin-plus-large-datasets/files/9008163/dataset.zip)
[dataset2.zip](https://github.com/filecoin-project/filecoin-plus-large-datasets/files/9008167/dataset2.zip)
[dataset3.zip](https://github.com/filecoin-project/filecoin-plus-large-datasets/files/9008171/dataset3.zip)

**Comment by Huifan-Tina0615** [comment]
@galen-mcandrew @dkkapur Please tell me what should I do next. Thanks all!

**Comment by galen-mcandrew** [comment]
## Datacap Request Trigger
#### Total DataCap requested 
> 5PiB
#### Expected weekly DataCap usage rate 
> 200TiB 
#### Client address
> f1u522dt3zabkgbxxzecl77wgv473yvpecxh6t6zq

**Comment by BlockMakeronline** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecuczqxeda4gwc6uh6oz3i5rbxlxv6evghh5zkckgcka6vrrrbhhi 
#### Address 
> f1u522dt3zabkgbxxzecl77wgv473yvpecxh6t6zq
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1o3twrcpwjtpcd4q36lpq4qmy2qfbgtyy5h6tsty
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecuczqxeda4gwc6uh6oz3i5rbxlxv6evghh5zkckgcka6vrrrbhhi

**Comment by PluskitOfficial** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb5tpssyakotykeawc27yofo74huxsb5lhj2ddr6xnqs4thjzz74i 
#### Address 
> f1u522dt3zabkgbxxzecl77wgv473yvpecxh6t6zq
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1tgnlhtcmhwipfm7thsftxhn5k52velyjlazpvka
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb5tpssyakotykeawc27yofo74huxsb5lhj2ddr6xnqs4thjzz74i

**Comment by kevzak** [comment]
Hello @Huifan-Tina0615 - I'm Kevin from the Client Success Team. I saw you were granted DataCap and I wanted to reach out as you are preparing to onboard data to offer any support as needed. Let me know if you have any questions.

Also, fell free to post a message in #fil-plus slack channel.

**Comment by MRJAVAZHAO** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceam2mho7vw663so44wlajdlj5mq57gdsq3jz5klpobcjddioetwya 
#### Address 
> f1u522dt3zabkgbxxzecl77wgv473yvpecxh6t6zq
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f14gme3f52prtyzk6pblogrdd6b6ivp4swc6qmesi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceam2mho7vw663so44wlajdlj5mq57gdsq3jz5klpobcjddioetwya

**Comment by MatrixStorage** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedz2fsy7lvc5xh3qwzykejte56tlxolkoyhrjua4mlao6zfqzhzww 
#### Address 
> f1u522dt3zabkgbxxzecl77wgv473yvpecxh6t6zq
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1tbxqwjxfyv7swsdin4einirlsfquv3vnmlapley
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedz2fsy7lvc5xh3qwzykejte56tlxolkoyhrjua4mlao6zfqzhzww

**Comment by UnionLabs2020** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceag25ucwfuimxiiay5i4xenpct7hqj7ouvqqg2ccmgh7kioheokts 
#### Address 
> f1u522dt3zabkgbxxzecl77wgv473yvpecxh6t6zq
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f17xdri3wunqgld7dm23e4f3eqsntjakwc47xjo6i
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceag25ucwfuimxiiay5i4xenpct7hqj7ouvqqg2ccmgh7kioheokts

**Comment by MRJAVAZHAO** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebizxxhl3oqh4ficadqi2glpjz35db6r4ybfwgnigtw7c2sysfui6 
#### Address 
> f1u522dt3zabkgbxxzecl77wgv473yvpecxh6t6zq
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f14gme3f52prtyzk6pblogrdd6b6ivp4swc6qmesi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebizxxhl3oqh4ficadqi2glpjz35db6r4ybfwgnigtw7c2sysfui6

**Comment by BigD-Exchange** [comment]
@Huifan-Tina0615 Hi! Great to see you have gotten approval for DataCap. If you are looking for storage providers to store these data, please visit #bigdata-exchange on Filecoin Slack or reply here.

**Comment by PluskitOfficial** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec2mbapswkhojnksq454jto3duuje742xprgwyjrto7mz3fjdsdvo 
#### Address 
> f1u522dt3zabkgbxxzecl77wgv473yvpecxh6t6zq
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1tgnlhtcmhwipfm7thsftxhn5k52velyjlazpvka
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec2mbapswkhojnksq454jto3duuje742xprgwyjrto7mz3fjdsdvo

**Comment by MetaWaveInfo** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedjrhgnfacsribwbapjljqpweiqpwr5lmsgtfaok5rlma4ue22vg4 
#### Address 
> f1u522dt3zabkgbxxzecl77wgv473yvpecxh6t6zq
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1ktlkcxnmzxcdaoqfsunrg3vocfbmgv4n3mrn74a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedjrhgnfacsribwbapjljqpweiqpwr5lmsgtfaok5rlma4ue22vg4

**Comment by UnionLabs2022** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecad3rkijrhaizmtlvjknjfcyd4epznyg3zg7fo34x35bchmqw5g2 
#### Address 
> f1u522dt3zabkgbxxzecl77wgv473yvpecxh6t6zq
#### Datacap Allocated
> 1.56PiB
#### Signer Address
> f17xdri3wunqgld7dm23e4f3eqsntjakwc47xjo6i
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecad3rkijrhaizmtlvjknjfcyd4epznyg3zg7fo34x35bchmqw5g2

**Comment by swatchliu** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceazwu2zshxu3quwp5togsqbab3ar4yefr5qrskpt6n2chv3yxvfby 
#### Address 
> f1u522dt3zabkgbxxzecl77wgv473yvpecxh6t6zq
#### Datacap Allocated
> 1.56PiB
#### Signer Address
> f1yh6q3nmsg7i2sys7f7dexcuajgoweudcqj2chfi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceazwu2zshxu3quwp5togsqbab3ar4yefr5qrskpt6n2chv3yxvfby

**Comment by filplus-checker** [comment]
## DataCap and CID Checker Report[^1]
 - Organization: `Huifan livestream`
 - Client: `f1u522dt3zabkgbxxzecl77wgv473yvpecxh6t6zq`
### Storage Provider Distribution
The below table shows the distribution of storage providers that have stored data for this client.

If this is the first time a provider takes verified deal, it will be marked as `new`.

For most of the datacap application, below restrictions should apply.
 - Storage provider should not exceed 25% of total datacap.
 - Storage provider should not be storing duplicate data for more than 20%.
 - Storage provider should have published its public IP address.
 - All storage providers should be located in different regions.

⚠️ 42.80% of total deal sealed by [f01895778](https://filfox.info/en/address/f01895778) are duplicate data.

⚠️ 34.29% of total deal sealed by [f01893290](https://filfox.info/en/address/f01893290) are duplicate data.

⚠️ 32.83% of total deal sealed by [f01895707](https://filfox.info/en/address/f01895707) are duplicate data.

⚠️ 70.51% of total deal sealed by [f01880898](https://filfox.info/en/address/f01880898) are duplicate data.

⚠️ 31.85% of total deal sealed by [f01896469](https://filfox.info/en/address/f01896469) are duplicate data.

⚠️ 72.77% of total deal sealed by [f01880897](https://filfox.info/en/address/f01880897) are duplicate data.

⚠️ 76.48% of total deal sealed by [f01880894](https://filfox.info/en/address/f01880894) are duplicate data.

⚠️ 62.32% of total deal sealed by [f01879880](https://filfox.info/en/address/f01879880) are duplicate data.

⚠️ 35.85% of total deal sealed by [f01896513](https://filfox.info/en/address/f01896513) are duplicate data.

⚠️ 33.88% of total deal sealed by [f01895990](https://filfox.info/en/address/f01895990) are duplicate data.

⚠️ 35.95% of total deal sealed by [f01895928](https://filfox.info/en/address/f01895928) are duplicate data.

⚠️ 34.98% of total deal sealed by [f01895913](https://filfox.info/en/address/f01895913) are duplicate data.

⚠️ 72.76% of total deal sealed by [f01880896](https://filfox.info/en/address/f01880896) are duplicate data.

⚠️ 79.97% of total deal sealed by [f01885280](https://filfox.info/en/address/f01885280) are duplicate data.

⚠️ 68.28% of total deal sealed by [f01868890](https://filfox.info/en/address/f01868890) are duplicate data.

| Provider                                                    |                           Location | Total Deals Sealed | Percentage | Unique Data | Duplicate Deals |
| :---------------------------------------------------------- | ---------------------------------: | -----------------: | ---------: | ----------: | --------------: |
| [f01895778](https://filfox.info/en/address/f01895778)       |           Singapore, Singapore, SG |         223.56 TiB |     13.66% |  127.88 TiB |          42.80% |
| [f01893290](https://filfox.info/en/address/f01893290)       |           Singapore, Singapore, SG |         159.94 TiB |      9.78% |  105.09 TiB |          34.29% |
| [f01895707](https://filfox.info/en/address/f01895707)       |           Singapore, Singapore, SG |         149.84 TiB |      9.16% |  100.66 TiB |          32.83% |
| [f01880898](https://filfox.info/en/address/f01880898)`new`  |           Singapore, Singapore, SG |         138.72 TiB |      8.48% |   40.91 TiB |          70.51% |
| [f01896469](https://filfox.info/en/address/f01896469)       |           Singapore, Singapore, SG |         131.97 TiB |      8.07% |   89.94 TiB |          31.85% |
| [f01880897](https://filfox.info/en/address/f01880897)       |           Singapore, Singapore, SG |         106.84 TiB |      6.53% |   29.09 TiB |          72.77% |
| [f01880894](https://filfox.info/en/address/f01880894)       |           Singapore, Singapore, SG |         105.88 TiB |      6.47% |   24.91 TiB |          76.48% |
| [f01879880](https://filfox.info/en/address/f01879880)       |           Singapore, Singapore, SG |          95.63 TiB |      5.84% |   36.03 TiB |          62.32% |
| [f01896513](https://filfox.info/en/address/f01896513)       |           Singapore, Singapore, SG |          85.00 TiB |      5.20% |   54.53 TiB |          35.85% |
| [f01895990](https://filfox.info/en/address/f01895990)       |           Singapore, Singapore, SG |          84.59 TiB |      5.17% |   55.94 TiB |          33.88% |
| [f01895928](https://filfox.info/en/address/f01895928)       |           Singapore, Singapore, SG |          82.41 TiB |      5.04% |   52.78 TiB |          35.95% |
| [f01895913](https://filfox.info/en/address/f01895913)       |           Singapore, Singapore, SG |          82.38 TiB |      5.03% |   53.56 TiB |          34.98% |
| [f01889480](https://filfox.info/en/address/f01889480)       |               Boardman, Oregon, US |          60.31 TiB |      3.69% |   60.31 TiB |           0.00% |
| [f01880896](https://filfox.info/en/address/f01880896)       |           Singapore, Singapore, SG |          56.09 TiB |      3.43% |   15.28 TiB |          72.76% |
| [f01885280](https://filfox.info/en/address/f01885280)       | Hong Kong, Central and Western, HK |          39.94 TiB |      2.44% |    8.00 TiB |          79.97% |
| [f01868890](https://filfox.info/en/address/f01868890)       |               Boardman, Oregon, US |          33.00 TiB |      2.02% |   10.47 TiB |          68.28% |

![Provider Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/407/1671096805314.png)
### Deal Data Replication
The below table shows how each many unique data are replicated across storage providers.
- No more than 25% of unique data are stored with less than 4 providers.

⚠️ 62.29% of deals are for data replicated across less than 4 storage providers.

| Unique Data Size | Total Deals Made | Number of Providers | Deal Percentage |
| ---------------: | ---------------: | ------------------: | --------------: |
|       335.78 TiB |       795.97 TiB |                   1 |          48.65% |
|        43.88 TiB |       169.53 TiB |                   2 |          10.36% |
|        10.69 TiB |        53.69 TiB |                   3 |           3.28% |
|        16.59 TiB |       110.69 TiB |                   4 |           6.77% |
|        23.47 TiB |       188.97 TiB |                   5 |          11.55% |
|        22.78 TiB |       201.13 TiB |                   6 |          12.29% |
|        10.88 TiB |       100.53 TiB |                   7 |           6.14% |
|         1.66 TiB |        15.59 TiB |                   8 |           0.95% |

![Replication Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/407/1671096806093.png)
### Deal Data Shared with other Clients
The below table shows how many unique data are shared with other clients.
Usually different applications owns different data and should not resolve to the same CID.

⚠️ CID sharing has been observed.

| Other Client                                                                                                                                                                                                              | Application                                                                                                     | Total Deals Affected | Unique CIDs |        Verifier |
| :------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ | :-------------------------------------------------------------------------------------------------------------- | -------------------: | ----------: | --------------: |
| [f1dx7ljly4vmk5x2bn5ng4jpbqnuvozrz2phw42qy](https://filfox.info/en/address/f1dx7ljly4vmk5x2bn5ng4jpbqnuvozrz2phw42qy)                                                                                                     | [CoinPhD](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/364)                          |           413.31 TiB |       6,164 | LDN v3 multisig |
| [f14abwn2goturifmt27s2bssoe3fup2b3npkgfzui](https://filfox.info/en/address/f14abwn2goturifmt27s2bssoe3fup2b3npkgfzui)                                                                                                     | [KONGFU VR](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/372)                        |           332.47 TiB |       3,665 | LDN v3 multisig |
| [f1tivtdkq34mnfzso63wrr2xh6r2zo7aebao4jfla](https://filfox.info/en/address/f1tivtdkq34mnfzso63wrr2xh6r2zo7aebao4jfla)                                                                                                     | `China travel service(HongKong) limited`                                                                        |           316.22 TiB |       2,867 | LDN v3 multisig |
| [f1muygjb5zowppbhr7wnmdreqdoiyyanfm7fe54dy](https://filfox.info/en/address/f1muygjb5zowppbhr7wnmdreqdoiyyanfm7fe54dy)                                                                                                     | [MappingFunk Protocol ](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/374)            |           276.50 TiB |       3,053 | LDN v3 multisig |
| [f1tgii4xgcp6um4n2w7eqaw6bwvnvyii2u7cjgzka](https://filfox.info/en/address/f1tgii4xgcp6um4n2w7eqaw6bwvnvyii2u7cjgzka)                                                                                                     | [Meson\.Network ](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/187)                  |           190.75 TiB |       1,068 | LDN v3 multisig |
| [f1hik4fc3wvck2jchtufrnfnzmmskw2nyezlbsr3q](https://filfox.info/en/address/f1hik4fc3wvck2jchtufrnfnzmmskw2nyezlbsr3q)                                                                                                     | [NFTSCAN](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/350)                          |           166.09 TiB |       1,608 | LDN v3 multisig |
| [f1ffbtksiso5za73pypuxbxznng6rdv64nbihdtba](https://filfox.info/en/address/f1ffbtksiso5za73pypuxbxznng6rdv64nbihdtba)                                                                                                     | [EpikProtocol](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/281)                     |           116.56 TiB |       1,066 |       LDN # 281 |
| [f1ojo3wo24zkeovndlxfpqmlgzlbysg5fiukmup4a](https://filfox.info/en/address/f1ojo3wo24zkeovndlxfpqmlgzlbysg5fiukmup4a)                                                                                                     | `Titansoft`                                                                                                     |            74.00 TiB |         680 | LDN v3 multisig |
| [f1qjrlejxv5a73kxurwtxyrni6ji7orm74zeeetiy](https://filfox.info/en/address/f1qjrlejxv5a73kxurwtxyrni6ji7orm74zeeetiy)                                                                                                     | [Mooc](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/223)                             |            71.56 TiB |         966 | LDN v3 multisig |
| [f1ffr7uhq7mszotfdybexcnl4i7xw5tqyp5fhqy3y](https://filfox.info/en/address/f1ffr7uhq7mszotfdybexcnl4i7xw5tqyp5fhqy3y)                                                                                                     | [MyTrade Technology Limited](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/386)       |            66.16 TiB |         618 | LDN v3 multisig |
| [f1ac3mjrhahxbyvxsasp4e7kwa6vyds3ahm27us6a](https://filfox.info/en/address/f1ac3mjrhahxbyvxsasp4e7kwa6vyds3ahm27us6a)                                                                                                     | `Create coach`                                                                                                  |            64.75 TiB |         858 | LDN v3 multisig |
| [f1f5edx6ofn3lf6rk3yfpldbi2pzgq2egoyu6ubpi](https://filfox.info/en/address/f1f5edx6ofn3lf6rk3yfpldbi2pzgq2egoyu6ubpi)                                                                                                     | [Samdata Trade](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/382)                    |            64.22 TiB |         940 | LDN v3 multisig |
| [f1zb6pgkktdbyy7zxfob6gripqxuc25ukf35cc7fq](https://filfox.info/en/address/f1zb6pgkktdbyy7zxfob6gripqxuc25ukf35cc7fq)                                                                                                     | `Maxpic PhotoGraphic Studio`                                                                                    |            63.16 TiB |         969 | LDN v3 multisig |
| [f1clwd2dooy2cflfilhzeq2ycl544b3heqsiwhjrq](https://filfox.info/en/address/f1clwd2dooy2cflfilhzeq2ycl544b3heqsiwhjrq)                                                                                                     | [FiboAI](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/349)                           |            59.19 TiB |         805 | LDN v3 multisig |
| [f1ki4cjk27ypzjsuzkvvqzs6xobaweuoxfdcnpqhy](https://filfox.info/en/address/f1ki4cjk27ypzjsuzkvvqzs6xobaweuoxfdcnpqhy)                                                                                                     | [TimeQuant](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/385)                        |            53.75 TiB |         777 | LDN v3 multisig |
| [f1bb2z36lpq3pnwiiowiraagpzqnpow4bonjacx7a](https://filfox.info/en/address/f1bb2z36lpq3pnwiiowiraagpzqnpow4bonjacx7a)                                                                                                     | [Hola Space](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/362)                       |            48.25 TiB |       1,060 | LDN v3 multisig |
| [f1727w2vwjctfo7hflr5trgqkl3c7texh7pl4grzq](https://filfox.info/en/address/f1727w2vwjctfo7hflr5trgqkl3c7texh7pl4grzq)                                                                                                     | [GMverse](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/365)                          |            31.47 TiB |         553 | LDN v3 multisig |
| [f1dpgqn57cl5wqijiyv3256nids2ox3fms2mg3oay](https://filfox.info/en/address/f1dpgqn57cl5wqijiyv3256nids2ox3fms2mg3oay)                                                                                                     | [All Blue](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/389)                         |            28.28 TiB |         401 | LDN v3 multisig |
| [f1ivsvpljx4ovp2tth73pllkxmumrudemks623iia](https://filfox.info/en/address/f1ivsvpljx4ovp2tth73pllkxmumrudemks623iia)                                                                                                     | `TIS Inc. group`                                                                                                |            25.09 TiB |         255 | LDN v3 multisig |
| [f1gs5xe26fkplu64mwcfq5fswycp3qucuvzbg2lia](https://filfox.info/en/address/f1gs5xe26fkplu64mwcfq5fswycp3qucuvzbg2lia)                                                                                                     | [Migu Culture Technology Co\., Ltd](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/63) |            18.25 TiB |         144 |        LDN # 63 |
| [f3q7ablez3jqkcjukwbzaql7lmbx4ldouu66nexpd<br/>cfvu6kgho3v6gricckt77cgr46tdre2l4zmvha7bs<br/>u7qq](https://filfox.info/en/address/f3q7ablez3jqkcjukwbzaql7lmbx4ldouu66nexpdcfvu6kgho3v6gricckt77cgr46tdre2l4zmvha7bsu7qq) | `MatrixStorage`                                                                                                 |             6.44 TiB |          87 |        LDN # 72 |
| [f3skkellc7wegakh2blqeu4kkrlzuqy2siymwli7s<br/>ec6eq77c2v4kzgz5ozgnasjl5r52ckameba5kds7h<br/>djda](https://filfox.info/en/address/f3skkellc7wegakh2blqeu4kkrlzuqy2siymwli7sec6eq77c2v4kzgz5ozgnasjl5r52ckameba5kds7hdjda) | [Meizhai Technology](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/75)                |             5.88 TiB |         187 | LDN v3 multisig |
| [f3woqxpu6ekmj43nmpcv7j2pgu6lejxtzgxpzl6f2<br/>vrueoqlzjntakyhdkghymyffbzfbsio6dvfmy643x<br/>4y7q](https://filfox.info/en/address/f3woqxpu6ekmj43nmpcv7j2pgu6lejxtzgxpzl6f2vrueoqlzjntakyhdkghymyffbzfbsio6dvfmy643x4y7q) | [RICH ST PETE LLC](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/64)                  |             2.22 TiB |          67 | LDN v3 multisig |
| [f1fi7vzu266bh7yxsygw6scl2hjltdkhfb6nyzn3a](https://filfox.info/en/address/f1fi7vzu266bh7yxsygw6scl2hjltdkhfb6nyzn3a)                                                                                                     | [Jiliantech](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/190)                       |           288.00 GiB |           8 |       LDN # 190 |
| [f1yswits4hd4zu6n2pl7nk7cspcuieuzl7btjn5ia](https://filfox.info/en/address/f1yswits4hd4zu6n2pl7nk7cspcuieuzl7btjn5ia)                                                                                                     | [TaoPaiPai](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/54)                         |            32.00 GiB |           1 |        LDN # 54 |

[^1]: To manually trigger this report, add a comment with text `checker:manualTrigger`

**Comment by Sunnyiscoming** [comment]
Hello, per the https://github.com/filecoin-project/notary-governance/issues/922 for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

This information will be reviewed by Fil+ Governance team to confirm validity and then the application will be allowed to move forward for additional notary review.
