### ISSUE TITLE
[DataCap Application] Geogebra online platform

### ISSUE THREAD

**Issue by Sofia2338** [filecoin-project/filecoin-plus-large-datasets#408]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name:  Geogebra online platform
- Website / Social Media: https://www.geogebra.org/        
                                           twitter/facebook/youtube/ins: GeoGebra
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):150TiB
- On-chain address for first allocation:  f1tetcfz37aaegh3ogwsaw5bqvzarslkx47y55hni

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
GeoGebra is a dynamic mathematics software for all levels of education that brings together geometry, algebra, spreadsheets, graphing, statistics and calculus in one engine. In addition, GeoGebra offers an online platform with over 1 million free classroom resources created by our multilingual community. These resources can be easily shared through our collaboration platform GeoGebra Classroom where student progress can be monitored in real time.
GeoGebra is a community of millions of users located in just about every country. It has become the leading provider of dynamic mathematics software, supporting science, technology, engineering and mathematics (STEM) education and innovations in teaching and learning worldwide. GeoGebra’s math engine powers hundreds of educational websites worldwide in different ways from simple demonstrations to full online assessment systems.
In 2021, GeoGebra became part of the BYJU’S family with hundreds of millions of students on their learning platforms. GeoGebra's apps, classroom resources, GeoGebra Classroom & other features will continue to be available to the public for free. GeoGebra continues to operate as an independent unit within the BYJU’S group under the leadership of GeoGebra’s original founders and developers.
Awards：
-Archimedes 2016: MNU Award in category Mathematics (Hamburg, Germany)
-Microsoft Partner of the Year Award 2015: Finalist, Public Sector: Education (Redmond, WA, USA)
-MERLOT Classics Award 2013: Multimedia Educational Resource for Learning and Online Teaching (Las Vegas, Nevada, USA)
-NTLC Award 2010: National Technology Leadership Award (Washington D.C., USA)
-Tech Award 2009: Laureat in the Education Category (San Jose, California, USA)
-BETT Award 2009: Finalist in London for British Educational Technology Award
-SourceForge.net Community Choice Awards 2008: Finalist, Best Project for Educators
-AECT Distinguished Development Award 2008: Association for Educational Communications and Technology (Orlando, USA)
-Learnie Award 2006: Austrian Educational Software Award (Vienna, Austria)
-eTwinning Award 2006: 1st prize for "Crop Circles Challenge" with GeoGebra (Linz, Austria)
-Les Trophées du Libre 2005: International Free Software Award, category Education (Soisson, France)
-Comenius 2004: German Educational Media Award (Berlin, Germany)
-Learnie Award 2005: Austrian Educational Software Award (Vienna, Austria)
-digita 2004: German Educational Software Award (Cologne, Germany)
-Learnie Award 2003: Austrian Educational Software Award (Vienna, Austria)
-EASA 2002: European Academic Software Award (Ronneby, Sweden)
```

What is the primary source of funding for this project?
```
Our funding comes primarily from our own company, online course partnerships, and course innovation and r&d revenues
```

What other projects/ecosystem stakeholders is this project associated with?
```
None.
```

## Use-case details

Describe the data being stored onto Filecoin
```
GeoGebra is an online platform with over 1 million free classroom resources. These resources can be easily shared through our collaboration platform GeoGebra Classroom where student progress can be monitored in real time. At the same time, GeoGebra’s math engine powers hundreds of educational websites worldwide in different ways from simple demonstrations to full online assessment systems. These are all data sources for us.
```

Where was the data in this dataset sourced from?
```
These data includes course data and real-time data generated in the business. We will desensitize the data before storing it.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://github.com/Geogebro/samples/find/main
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
This is a public dataset.
```

What is the expected retrieval frequency for this data?
```
We store the data for backup, and generally will not access.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
We plan to store these data in the filecoin network permanently.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Global
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Both online and offline.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
In this way, we can try our best to ensure that we can choose the right service provider. We will make an appeal on slack,
We hope to fully understand the service capabilities of the storage providers before selecting them, so we hope that the storage providers can cooperate with us to conduct investigations including but not limited to storage capacity, computing capacity, network access time and other capabilities. This ensures that we can choose the right service provider. 
We will look for storage providers on Slack, and also hope that storage providers can self-recommend.
```

How will you be distributing deals across storage providers?
```
We will distribute the deals fairly according to the service capabilities of the storage service providers.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, we have had the resources/funding and don't need any more support from the community.
```

**Comment by Sunnyiscoming** [comment]
Hey. Could you send an email to [filplus@fil.org](mailto:filplus@fil.org) with your official domain in order to confirm your identity?

**Comment by Sofia2338** [comment]
> Hey. Could you send an email to [filplus@fil.org](mailto:filplus@fil.org) with your official domain in order to confirm your identity?

Please check the email,thanks

**Comment by galen-mcandrew** [comment]
Following up to the requests above, we have not seen any evidence that @Sofia2338 is associated with the official GeoGebra organization.

Please provide further evidence of your official relationship and representation of this organization.

**Comment by Sunnyiscoming** [comment]
Any update here?

**Comment by Sofia2338** [comment]
@galen-mcandrew @Sunnyiscoming As the team of Geogebra in Greater China, we are also actively communicating to prove our connection.It will take some time.

**Comment by Sunnyiscoming** [comment]
Any update here?

**Comment by Sofia2338** [comment]
We're still in discussion. Sorry to keep you waiting.

**Comment by raghavrmadya** [comment]
Given that this issue has been open for quite some time and we have not heard an update from the client, we are going to close this issue. Please submit a new application with more detailed information about SP distribution (saying global is not enough), pre-existing relationships, as well as the SPs you plan to work with. Providing SP IDs will greatly accelerate the process.
