### ISSUE TITLE
[DataCap Application]Beijing Meng Zhi Chuang Digital Technology Co., LTD

### ISSUE THREAD

**Issue by MengZhiChuang** [filecoin-project/filecoin-plus-large-datasets#409]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Beijing Meng Zhi Chuang Digital Technology Co., LTD
- Website / Social Media: https://www.tangdou.com/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5 PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 200 TiB
- On-chain address for first allocation: f1v6qdz64w5u5mmvtzv4krdygqhamusfk7yahyh3a

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Tangdou is a entertainment platform dedicated to serving middle-aged and elderly groups, gathering more than 100 million exercise enthusiasts, square dancing, aerobics, yoga and other teaching videos can be found on the platform.  The company through the square dance dance tools jelly beans APP, public, small program to build content matrix, cut into the square dance user groups, based on the online users to share pictures, video, short video, offline WuDui organization the activities of public performance, communication and other cities, gradually build elderly community platform, and through advertising + form such as electricity, mining silver economy market potential.  

In April 2015, Tangdou APP was officially established.  In September 2015, Tangdou raised $5 million in round A financing;  In October, cooperated with the General Administration of Sport of China in the first National Square Dance Competition.  In July 2016, Tangdou released the TV version with multi-screen interaction;  In October, Tangdou launched a 100-city jumping event to support the Brazil Olympic Games, and received a total of 20 million US dollars in round B financing.  In January 2017, Tangdou obtained B+ round financing of usd 5 million;  In June, the content was upgraded comprehensively, including PGC+UGC, show dance video + small video, advocating to create a common stage with party friends.  In February 2018, tangdou Square Dance debuted on the stage of the Great Hall of the People;  In March, Tangdou helped hunan Taoyuan Ten Thousand Square Dance Guinness challenge success;  In May, we opened APP, mini program, Web terminal, OTT and other multi-scene linkage layout, and cooperated closely with the General Administration of Sport of China in 2018 National Square Dance Contest.  In July, The Tangdou Dance team appeared on CCTV4's "Chinese Love" program to promote Chinese square dance culture;  In August, three small programs of tangdou ranked top10 in the total list of small programs on wechat, and the APP ranked the top in sports and fitness in the past two years. 
```

What is the primary source of funding for this project?
```
Project revenue.
```

What other projects/ecosystem stakeholders is this project associated with?
```
None.
```

## Use-case details

Describe the data being stored onto Filecoin
```
Hot dance music, square dance tutorial, square dance video shooting skills, square dance costume matching skills, etc.  

Related to fitness, weight loss, health, food and other aspects of life, focusing on life tips, common sense, etc. 

```

Where was the data in this dataset sourced from?
```
Project operation data and user data.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://www.tangdou.com/videos
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes, it is a public dataset.
```

What is the expected retrieval frequency for this data?
```
The current frequency of retrieval is not high, and is expected to be a few months. 
```

For how long do you plan to keep this dataset stored on Filecoin?
```
We will store for about 3 years.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
We hope to cooperate with outstanding global storage providers. 
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
This specific reference to the storage provider's requirements for us. We are willing to choose both online and offline data transfer process.
 ```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We will choose reputable storage service providers and accept recommendations. 
```

How will you be distributing deals across storage providers?
```
We want to find 5-10 storage providers and distribute the transactions as evenly as possible. 
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
We have started to communicate with the storage provider and hope everything goes well.  If necessary,  We will point it out on the issue. Thank you. 
```

**Comment by raghavrmadya** [comment]
No response or follow-up. Please open a new application if you are still interested.
