### ISSUE TITLE
[DataCap Application]500px

### ISSUE THREAD

**Issue by aaronsjx07** [filecoin-project/filecoin-plus-large-datasets#411]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: 500px
- Website / Social Media:https://500px.com.cn/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):1PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):50TiB
- On-chain address for first allocation:f1g3wles4fhxtfoh5y6qacgzsyz3zrqimsw7a7qiq

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Vision China 500px Photography Community is a professional community of creative photographers, where we come together to share photos, discover good works, exchange shooting tips and create our own photography personal pages. Photographers from all over the world are our loyal users.
Let you and others get acquainted by pictures, the world is big, I want to see it.
```

What is the primary source of funding for this project?
```
It is from shareholders‘ investment. 
```

What other projects/ecosystem stakeholders is this project associated with?
```
There is no other projects/ecosystem stakeholders associated with.
```

## Use-case details

Describe the data being stored onto Filecoin
```
A large number of photos of landscapes, people, flora and fauna taken by users are uploaded to the website every day.
```

Where was the data in this dataset sourced from?
```
We have a large number of experienced photographers who upload the photos they have taken to the website for users to view.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
Of course.
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes, I confirm that this is a public dataset that can be retrieved by anyone on the web.
```

What is the expected retrieval frequency for this data?
```
About 1-2 times in 6 months.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
I think this will be a permanent archive.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Asia
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Online transfer is preferred.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We hope to find some miners with size and credit. We will also look at how long they work and what their fees are. 
```

How will you be distributing deals across storage providers?
```
We will split up the data and send it to different miners.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
We're ready to make a deal.
```

**Comment by EGGRICE02** [comment]
@aaronsjx07 Can you mail to filplus@fil.org with your company domain to confirm you're applying DataCap for 500px?

**Comment by mamimami666** [comment]
good,I like it.

**Comment by aaronsjx07** [comment]
> @aaronsjx07 Can you mail to [filplus@fil.org](mailto:filplus@fil.org) with your company domain to confirm you're applying DataCap for 500px?
