### ISSUE TITLE
[DataCap Application] Jiangxi Henglian Technology Co., Ltd

### ISSUE THREAD

**Issue by JXHengLian** [filecoin-project/filecoin-plus-large-datasets#412]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Jiangxi Henglian Technology Co., Ltd
- Website / Social Media: http://www.henglianvip.com/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5 PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 200TiB
- On-chain address for first allocation: f1kzvar24effffwrv4355jv6mg53t4g5ets7xu3fq

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Jiangxi Henglian Technology Co., Ltd. is committed to providing customers with comprehensive mobile Internet technology research and development solutions. The services provided to customers include: WeChat public account development, WeChat applet development, mobile phone app development, and enterprise management software development. The core members have more than 15 years of industry development experience and have more than 600 successful cases of independent research and development.
```

What is the primary source of funding for this project?
```
Company revenue
```

What other projects/ecosystem stakeholders is this project associated with?
```
None
```

## Use-case details

Describe the data being stored onto Filecoin
```
The pictures and video materials that need to be displayed in the app we develop, such as beauty tutorials, hair styling tutorials, and dressing tutorials. These data are publicly available and need to be backed up in Filecoin.
```

Where was the data in this dataset sourced from?
```
We upload these data
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
Link: https://pan.baidu.com/s/1bREgd5FSYlskcIylzuyUGg
Extraction code: 86b4
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes
```

What is the expected retrieval frequency for this data?
```
per month
```

For how long do you plan to keep this dataset stored on Filecoin?
```
3 years
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Mainly in China
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
At least five SPs, both online and offline (within mainland China)
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
Because we want the data to be retrievable, we prefer SPs that support retrieval. In order to ensure the security of data, SPs in different cities will be selected.
```

How will you be distributing deals across storage providers?
```
No more than 20% datacap / SP
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Have enough resources/funding
```

**Comment by EGGRICE02** [comment]
@JXHengLian It seems that http://www.henglianvip.com/ was established just two weeks ago, and the whole page was absolute new. Only 4 links on the newsroom page, all commercial cases redirect to irrelevant pages. Therefore can you clarify that and prove more samples or concerning evidence to prove you have 5PB to store?
![image](https://user-images.githubusercontent.com/105268629/173894591-f7799026-d2aa-498c-944c-b653ee399674.png)

**Comment by EGGRICE02** [comment]
BTW, please have a double check on the sample you've uploaded. The content has nothing to do with your business.

**Comment by JXHengLian** [comment]
@EGGRICE02

**Comment by EGGRICE02** [comment]
In that case, please share us with the app you developed. A Google Play link or AppStore link is welcomed. To convince us the app was developed by you, it's better to upload part of source code, or sealed app without digital signature.

**Comment by Sunnyiscoming** [comment]
@JXHengLian Hi
https://aiqicha.baidu.com/company_detail_30083607468280?tab=certRecord
The organization established in 2020. It is true.

I have a question about data samples. I can't find them in the link. I don't know whether there is something wrong.
![image](https://user-images.githubusercontent.com/105098820/176335677-54511dee-bbd1-4107-8338-8d0306f2c741.png)

As [EGGRICE02](https://github.com/EGGRICE02) said, maybe the app you developed will help us better understand your business.

**Comment by Sunnyiscoming** [comment]
Any update here?

**Comment by Sunnyiscoming** [comment]
Any update here?

**Comment by dkkapur** [comment]
Closing this out for now since there was no response to the above questions. Please open up a new application if still relevant.
