### ISSUE TITLE
[DataCap Application] - PiKNiK - gnomAD Slingshot Dataset

### ISSUE THREAD

**Issue by jessie8o8** [filecoin-project/filecoin-plus-large-datasets#414]
# Large Dataset Notary Application
To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: PiKNiK - gnomAD Slingshot Dataset
- Website / Social Media: piknik.com
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):  500TiB
-Weekly allocation of DataCap requested (usually between 1-100TiB):  100TiB
-On-chain address for first allocation: f1o7xtxp3urjtcflqxg4wamb35g6wgqbdsquiigmi

## Project details
Share a brief history of your project and organization
```
PiKNiK is the main client for the USC Shoah Foundation and has experience in allocation deals to other SPs. We work to help others learn how to store valuable data by hosting an accelerator program called ESPA. 
```

What is the primary source of funding for this project?
```
PiKNiK
```

What other projects/ecosystem stakeholders is this project associated with?
```
Slingshot competition hosted by Protocol Labs
```

## Use-case details
Describe the data being stored onto Filecoin
```
V3 short variant data set, which spans 71,702 genomes from unrelated individuals sequenced as part of various disease-specific and population genetic studies.
```

Where was the data in this dataset sourced from?
```
Google Cloud Public Datasets, the Registry of Open Data on AWS, and Azure Open Datasets
```

Can you share a sample of the data? A link to file would work.
```
https://gnomad.broadinstitute.org/downloads
```

Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Confirmed
```

What is the expected retrieval frequency for this data?
```
Slingshot retrieval requirements will be followed
```

For how long do you plan to keep this dataset stored on Filecoin?
```
For the duration of Slingshot
```

## DataCap allocation plan
In which geographies (countries, regions) do you plan on making storage deals?
```
Europe, United States, Australia or any other SPs that are interested.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Offline
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
PiKNIK plans to deal with select SPs that are reputable in the community and are reliable such as SPXs, SPs that have prominent presence in the community, SPs that PiKNiK has successfully worked with before or using sites that rank reliability of SPs.
```

How will you be distributing deals across storage providers?
```
Hosting files online where storage providers can download them.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? 
```
Yes
```

What support from the community would help you onboard onto Filecoin?
```
Slingshot support channels in Filecoin Slack
```

**Comment by Kevin-FF-USA** [comment]
## Datacap Request Trigger
#### Total DataCap requested 
> 500TiB
#### Expected weekly DataCap usage rate 
> 100TiB 
#### Client address
> f1o7xtxp3urjtcflqxg4wamb35g6wgqbdsquiigmi

**Comment by psh0691** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedxsdbtfntvpcn6kfftxp2n4avih4v6t3qgppmkacq274oztev646 
#### Address 
> f1o7xtxp3urjtcflqxg4wamb35g6wgqbdsquiigmi
#### Datacap Allocated
> 25.00TiB
#### Signer Address
> f1qdko4jg25vo35qmyvcrw4ak4fmuu3f5rif2kc7i
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedxsdbtfntvpcn6kfftxp2n4avih4v6t3qgppmkacq274oztev646

**Comment by jessie8o8** [comment]
Thanks for the approval notary team! :)

**Comment by filplus-checker** [comment]
## DataCap and CID Checker Report[^1]
 - Organization: `PiKNiK - gnomAD Slingshot Dataset`
 - Client: `f1o7xtxp3urjtcflqxg4wamb35g6wgqbdsquiigmi`
### Storage Provider Distribution
The below table shows the distribution of storage providers that have stored data for this client.

If this is the first time a provider takes verified deal, it will be marked as `new`.

For most of the datacap application, below restrictions should apply.
 - Storage provider should not exceed 25% of total datacap.
 - Storage provider should not be storing duplicate data for more than 20%.
 - Storage provider should have published its public IP address.
 - All storage providers should be located in different regions.

⚠️ [f01959735](https://filfox.info/en/address/f01959735) has sealed 100.00% of total datacap.

⚠️ All storage providers are located in the same region.

| Provider                                                    |                     Location | Total Deals Sealed | Percentage | Unique Data | Duplicate Deals |
| :---------------------------------------------------------- | ---------------------------: | -----------------: | ---------: | ----------: | --------------: |
| [f01959735](https://filfox.info/en/address/f01959735)`new`  | Los Serranos, California, US |          96.00 GiB |    100.00% |   96.00 GiB |           0.00% |

![Provider Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/414/1671096815035.png)
### Deal Data Replication
The below table shows how each many unique data are replicated across storage providers.
- No more than 25% of unique data are stored with less than 4 providers.

⚠️ 100.00% of deals are for data replicated across less than 4 storage providers.

| Unique Data Size | Total Deals Made | Number of Providers | Deal Percentage |
| ---------------: | ---------------: | ------------------: | --------------: |
|        96.00 GiB |        96.00 GiB |                   1 |         100.00% |

![Replication Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/414/1671096815708.png)
### Deal Data Shared with other Clients
The below table shows how many unique data are shared with other clients.
Usually different applications owns different data and should not resolve to the same CID.

✔️ No CID sharing has been observed.

[^1]: To manually trigger this report, add a comment with text `checker:manualTrigger`

**Comment by cryptowhizzard** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedayy3pr4nyh4ud5nnundydwwd4wvsjf7qx6cxliptcl7h63mkqp6 
#### Address 
> f1o7xtxp3urjtcflqxg4wamb35g6wgqbdsquiigmi
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1krmypm4uoxxf3g7okrwtrahlmpcph3y7rbqqgfa
#### Id
> 4f00cea4-7cbe-4854-b494-5ccb559f9f06
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedayy3pr4nyh4ud5nnundydwwd4wvsjf7qx6cxliptcl7h63mkqp6

**Comment by kernelogic** [comment]
<img width="1330" alt="image" src="https://user-images.githubusercontent.com/3711825/214193892-4f774040-78fc-4b3c-968d-0c95ac822d46.png">
this is most likely bugged

**Comment by kernelogic** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaxj2bzanumtjcnsd7yvln6zrveucwqul5cj7pfjridq7k2sgz5hg 
#### Address 
> f1o7xtxp3urjtcflqxg4wamb35g6wgqbdsquiigmi
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaxj2bzanumtjcnsd7yvln6zrveucwqul5cj7pfjridq7k2sgz5hg

**Comment by data-programs** [comment]
<img width="32" alt="KYC" Verified src="https://stable.filplus.storage/images/filplus-kyc-verified-badge.png"/>

This user’s identity has been verified through [filplus.storage](https://filplus.storage)
