### ISSUE TITLE
[DataCap Allocation] - Gmining Fileplus

### ISSUE THREAD

**Issue by Gmining82** [filecoin-project/filecoin-plus-large-datasets#415]
---
name: Large Dataset Notary application
about: Clients should use this application form to request a DataCap allocation via a LDN for a dataset
title: "Gmining Fileplus"
labels: 'application, Phase: Diligence'
assignees: ''

---
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Gipfs Cloud Corp
- Website / Social Media: www.gmining.co.kr
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 500TiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 2TiB
- On-chain address for first allocation: f3u2gkechfgrxrbwjdomaejfi2rnnum3kpnrwuwaezrzuh4t7znbyw7426tt7qahji3vhrnm7r4ji7h42vvg5a
- Region: Asia (excl. Greater China)

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
We have been started this project for the vision of IPFS system. We have several specialized IT sources.
```

What is the primary source of funding for this project?
```
Owner's business fund for IPFS system
```

What other projects/ecosystem stakeholders is this project associated with?
```
Data storage with religious service programs
```

## Use-case details

Describe the data being stored onto Filecoin
```
Religious service programs and etc
```

Where was the data in this dataset sourced from?
```
Religious broadcasting company and big churchs
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
Yes, we can.
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
The dataset is not a public, but we have the access rights. So anyone can view the data freely.
```

What is the expected retrieval frequency for this data?
```
Unusual, depend on the case cause of religious data
```

For how long do you plan to keep this dataset stored on Filecoin?
```
As long as possible
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
South Korea
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
We will use the project of Filecoin APP and some promotions with religious groups. No, not yet.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We are trying to find the way. The plan will be handled by ourselves.

And the data will be retrieved together.
```

How will you be distributing deals across storage providers?
```
There are no plans yet to distribute.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, we have.
The turnover of capital for our pledge(ex. DeFi)
```

**Comment by Yvette516** [comment]
Could you please provide more data samples to prove that you already have 500TB data?

**Comment by Gmining82** [comment]
The link below is just a sample (video data) to help you understand.

https://www.cts.tv/sermon/detail/C256/P863?DPID=291048

Based on a 60-minute (1 hour) 1080p sermon video, approximately 600 MB of storage space is required.
As such, even the sermon video files of a specific religion (eg Christianity) require much more capacity than 500TB,
Excluding data related to large-scale religious groups in South Korea, it is expected that a larger capacity will be required even if it is assumed that only the sermon video files of small and medium-sized church pastors (only if the parties want it) are stored.
Considering the religious situation in Korea, the demand for data storage is expected to increase steadily.
Of course, we have completed data storage agreements with some religious groups and are continuing to expand.
So, we can say that we are currently able to deliver at least 500 TB of data and much more.
Only 500TB of capacity is the minimum size that is the standard when applying, so I answered.

The business model we're working on is approaching such religious groups to put their valuable data in more robust vaults as an additional safeguard, such as some kind of insurance, independent of the data storage services currently in use.
This is possible because our CEO has a long history and infrastructure dedicated to religious organizations.

**Comment by Sunnyiscoming** [comment]
@Gmining82 Hi,
1. It seems that you are represented for an mining organization(www.gmining.co.kr). I cannot find anything related with Gipfs Cloud Corp. Can you provide more information about it, such as certificate of organization existence .

2.Have you find any SP to cooperate with? Can you list them here? Do they support data retrieval?
> How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
> 
> We are trying to find the way. The plan will be handled by ourselves.
> 
> And the data will be retrieved together.
> How will you be distributing deals across storage providers?
> 
> There are no plans yet to distribute.

3. The data sample you provided above(https://www.cts.tv/sermon/detail/C256/P863?DPID=291048), which belongs to another organization. Have you get data usage authorization?

4.If the dataset is not public, maybe you should do another datacap application model. Please ensure whether your dataset is public.

> Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
> 
> The dataset is not a public, but we have the access rights. So anyone can view the data freely.

**Comment by Gmining82** [comment]
> 1. It seems that you are represented for an mining organization([www.gmining.co.kr](http://www.gmining.co.kr)). I cannot find anything related with Gipfs Cloud Corp. Can you provide more information about it, such as certificate of organization existence .
> Yes, we can. Gmining Inc, & Gipfs Cloud Corp. are same company. It just changed the company name. We can send you the certified copy of the corporate register with the company history, if you want. 

> 2.Have you find any SP to cooperate with? Can you list them here? Do they support data retrieval?
> We have a SP(f0230200). And we are trying to find more. They are developing the process to support data retrieval.

> 3. The data sample you provided above(https://www.cts.tv/sermon/detail/C256/P863?DPID=291048), which belongs to another organization. Have you get data usage authorization?
> Yes, we have full authorization.

> 4.If the dataset is not public, maybe you should do another datacap application model. Please ensure whether your dataset is public.
> Our dataset is public. Even if the dataset is not public, anyone can freely access our dataset.

**Comment by Sunnyiscoming** [comment]
If the dataset is not public for everyone to download.
As Deep mentioned filecoin-project/notary-governance#514, you will need to find notaries that can support your application since it includes private enterprise data.

You will need to follow a process similar to filecoin-project/notary-governance#489. This means:

Find notaries that can support your application. You can do this best in Slack, #fil-plus or #fil-plus-application-review
Once you have them, make an issue in the Notary Governance repo, similar to filecoin-project/notary-governance#489, stating your plan and the notaries that can support your request
FIL+ governance can then set up a custom LDN for this with those notaries and proceed from there
These additional steps are required to ensure that notaries can establish a relationship with you and back you as a trustworthy client, since the usual deal data will be encrypted and not open to access for the community to validate your actions on chain after DataCap has been used.

**Comment by Sunnyiscoming** [comment]
Any update here?

**Comment by dkkapur** [comment]
Closing this out for now since there was no response to the above questions. Please open up a new application if still relevant.
