### ISSUE TITLE
Slingshot  Brazil Data Cube Dataset - CabrinaHuang

### ISSUE THREAD

**Issue by xingjitansuo** [filecoin-project/filecoin-plus-large-datasets#419]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: CabrinaHuang - Slingshot Brazil Data Cube Dataset
- Website / Social Media: n/a
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 3.5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 800TiB
- On-chain address for first allocation:  f16xg7ndclvgnu56mj3jzat4gtlvvhgepnt2lcqaa

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
I have constantly joined as a client in Slingshot. I previously made deals with storage providers from different backgrounds all over the world.  I am aligned with the mission of FIlecoin Slingshot:  distribute real, valuable, and usable data to SP from various continents. 
```

What is the primary source of funding for this project?
```
Slingshot Reward, and personal money. 
```

What other projects/ecosystem stakeholders is this project associated with?
```
Slingshot 2.8
```

## Use-case details

Describe the data being stored onto Filecoin
```
Brazil Data Cube is the production, visualization and analysis of large volumes of remote sensing images modeled as multidimensional data cubes for the entire Brazilian territory.

.
```

Where was the data in this dataset sourced from?
```
AWS
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://registry.opendata.aws/brazil-data-cubes/

```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Confirm -  yes.  
```

What is the expected retrieval frequency for this data?
```
Not often. I might retrieve it once a week to ensure the deal is retrievable. The slingshot team might retrieve it a few times in the review period. 
```

For how long do you plan to keep this dataset stored on Filecoin?
```
At least one year
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Asia, North America, Europe 

```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
1. Prepare car file 
2. Upload to the server for SP to download, or ship the disks to SP to download .  
3. Propose offline deal to SP once they have files ready to import. 

```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
I will send a large portion (90%) of the deal to SPs that demonstrate the ability to run node safely,  handle real deals with a consistent sealing rate, and supports retrieval.   (Most likely the SP I worked before)
I am also willing to send a small portion of deals to SPs that are new to the network and provide them the opportunities to onboard to Filecoin faster.   (Explore SP from BigExchange)
```

How will you be distributing deals across storage providers?
```
No single SPs can make deals more than 25%. 


```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
I am an expert in sending deals. 
```

**Comment by Yvette516** [comment]
I just send an email to your officail email ,please check it.

**Comment by kernelogic** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebo6yhrsiv6g4uchikodhmtwpj7agl4cbge6brq4iej6n7tnevho4 
#### Address 
> f16xg7ndclvgnu56mj3jzat4gtlvvhgepnt2lcqaa
#### Datacap Allocated
> 179.19TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebo6yhrsiv6g4uchikodhmtwpj7agl4cbge6brq4iej6n7tnevho4

**Comment by Joss-Hua** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedv67ctipnhc2yuuftmoucx3zdopdcllmh3hm7xf2tp7g34l2xkxm 
#### Address 
> f16xg7ndclvgnu56mj3jzat4gtlvvhgepnt2lcqaa
#### Datacap Allocated
> 358.39TiB
#### Signer Address
> f1tfg54zzscugttejv336vivknmsnzzmyudp3t7wi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedv67ctipnhc2yuuftmoucx3zdopdcllmh3hm7xf2tp7g34l2xkxm

**Comment by 1ane-1** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb32s5gw7pytrx2btnroeti7mbjrexmcgcwn47x3eiufbtioyrts4 
#### Address 
> f16xg7ndclvgnu56mj3jzat4gtlvvhgepnt2lcqaa
#### Datacap Allocated
> 358.39TiB
#### Signer Address
> f1mdk7s2vntzm6hu35yuo6vjubtrpfnb2awhgvrri
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb32s5gw7pytrx2btnroeti7mbjrexmcgcwn47x3eiufbtioyrts4

**Comment by 1ane-1** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaafou6su2lpxvap5e5xflt63xchpw44rmvc5lxzzokqy4hgylc5c 
#### Address 
> f16xg7ndclvgnu56mj3jzat4gtlvvhgepnt2lcqaa
#### Datacap Allocated
> 358.39TiB
#### Signer Address
> f1mdk7s2vntzm6hu35yuo6vjubtrpfnb2awhgvrri
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaafou6su2lpxvap5e5xflt63xchpw44rmvc5lxzzokqy4hgylc5c

**Comment by 1ane-1** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebjlafl5pjiuiybwxtspbyxx242ngev3cwhix2zxqrasjbnt4uw3c 
#### Address 
> f16xg7ndclvgnu56mj3jzat4gtlvvhgepnt2lcqaa
#### Datacap Allocated
> 358.39TiB
#### Signer Address
> f1mdk7s2vntzm6hu35yuo6vjubtrpfnb2awhgvrri
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebjlafl5pjiuiybwxtspbyxx242ngev3cwhix2zxqrasjbnt4uw3c

**Comment by cryptowhizzard** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced4p4montroqrtotqbmbwe2pjm7ukcq3qt57ip5mfa4qm65zhdilw 
#### Address 
> f16xg7ndclvgnu56mj3jzat4gtlvvhgepnt2lcqaa
#### Datacap Allocated
> 358.39TiB
#### Signer Address
> f1krmypm4uoxxf3g7okrwtrahlmpcph3y7rbqqgfa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced4p4montroqrtotqbmbwe2pjm7ukcq3qt57ip5mfa4qm65zhdilw

**Comment by cryptowhizzard** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacect62hved2ubbgwr54shrstkeno7656i65e2srfmh6xontuc6ewek 
#### Address 
> f16xg7ndclvgnu56mj3jzat4gtlvvhgepnt2lcqaa
#### Datacap Allocated
> 716.79TiB
#### Signer Address
> f1krmypm4uoxxf3g7okrwtrahlmpcph3y7rbqqgfa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacect62hved2ubbgwr54shrstkeno7656i65e2srfmh6xontuc6ewek

**Comment by kernelogic** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb6jktqwfyex3pv6clzo5utkw3j5kkmupggobnbkw3e7weunwftss 
#### Address 
> f16xg7ndclvgnu56mj3jzat4gtlvvhgepnt2lcqaa
#### Datacap Allocated
> 716.79TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb6jktqwfyex3pv6clzo5utkw3j5kkmupggobnbkw3e7weunwftss

**Comment by Kakkouii** [comment]
Hey, some of your data seem to be not retrievable. Please take a look!
![企业微信截图_16599803387363](https://user-images.githubusercontent.com/105268629/183479609-71289972-0929-4bcc-aed6-6592364e3fff.png)

**Comment by kernelogic** [comment]
I think all these kind of errors are caused by a lotus bug
https://github.com/filecoin-project/boost/issues/499#issuecomment-1182780373

**Comment by Kakkouii** [comment]
> I think all these kind of errors are caused by a lotus bug [filecoin-project/boost#499 (comment)](https://github.com/filecoin-project/boost/issues/499#issuecomment-1182780373)

I see. Thanks for your reply. Sealing and retrieving data are of vital importance in filecoin community, this bug has been reported three months ago and it was Lotus 1.15.1 at that time. @LexLuthr committed in https://github.com/filecoin-project/boost/issues/499 that it should be available in upcoming lotus stable release. However, the latest Lotus is 1.16.0 and this bug still exist. Do we have an process on fixing this bug @dkkapur? Influenced SP are almost lost their transparency and in that case all data are not retrievable. I think we should fix it ASAP before raising tons of new proposals in our community for transparency and data security.

**Comment by LexLuthr** [comment]
It would seem there is a lot of confusion around this bug. So let me clarify to the best of my abilities.

1. Bug is in the deals made by market protocol mk1.1 and there is not going to be a fix for that.
2. This bug does not exists in new mk1.2 protocol used by boost deals. So switching to boost will fix this issue for all new boost deals.
3. For the sake of backward compatibility, boost can still make mk1.1 deals i.e. legacy deals (called in boost). These deals will still be affected by the above bug.
4. This bug prevents creation of shard for the piece storing the deal in deals made using mk1.1
5. As a work around, you can use `boostd dagstore register-shard` or `lotus-miner dagstore register-shard` command to manually register the piece CID with the dagstore. New command has already been shipped in lotus. 
6. This workaround will ensure that content is retrievable but you deal status might still show the same error as before.
7. Boost will be releasing a command to identify and fix any issues with retrievability in the near future. It is under development as of now.

If don't want to see this error, then only permanent solution as of now is to use the new market protocol to make deals. This applies to both online and offline deals.

**Comment by kernelogic** [comment]
@LexLuthr are you saying all existing deals made with lotus legacy market module are not retrievable, and there is no fix even after upgrade to boost later on?

**Comment by LexLuthr** [comment]
Not all deals, the deals which are impacted by this bug and show the error when trying to retrieve.
Yes, there is no fix on legacy deals as of now for this bug. But there is a workaround where you can add the pieceCID manually to the dagstore and that should fix retrieval problems.

**Comment by kernelogic** [comment]
So the workaround is I need to ask SP to run "lotus-miner dagstore register-shard" for every pieceCID after the deal is on chain.

**Comment by LexLuthr** [comment]
If deal is not indexed correctly then yes, that's the only solution. Boost should be able to identify such deals and let know the SP(even fix them) in upcoming release. This is still under works.

**Comment by Kakkouii** [comment]
So since this bug is not going to be fixed, should we have all SPs switch to the new protocol to make sure retrieving is available? It seems that it's not hard to avoid this bug so SPs should be responsible for solving it and storing clients' data properly.

**Comment by newwebgroup** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecyyb6h7wewoogebjdyoshao2dpu354fbbyfd3lkw2ks3dh6smkx2 
#### Address 
> f16xg7ndclvgnu56mj3jzat4gtlvvhgepnt2lcqaa
#### Datacap Allocated
> 1.39PiB
#### Signer Address
> f1e77zuityhvvw6u2t6tb5qlnsegy2s67qs4lbbbq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecyyb6h7wewoogebjdyoshao2dpu354fbbyfd3lkw2ks3dh6smkx2

**Comment by xinaxu** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb4s663wdwea57ba4rnpis4zfwkf7l5f6ujcynaww25o643qmrjge 
#### Address 
> f16xg7ndclvgnu56mj3jzat4gtlvvhgepnt2lcqaa
#### Datacap Allocated
> 1.39PiB
#### Signer Address
> f1k3ysofkrrmqcot6fkx4wnezpczlltpirmrpsgui
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb4s663wdwea57ba4rnpis4zfwkf7l5f6ujcynaww25o643qmrjge

**Comment by xingjitansuo** [comment]
I switched to the latest version of the market module since V.1.16. So the deal sent after can be fast-retrieval as shown below. 
![2691660122740_ pic](https://user-images.githubusercontent.com/72185104/183865622-11260938-7196-401b-a148-a813f8e0e01d.jpg)

**Comment by kernelogic** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedlm3r3yjqocogu63efwjixm4zg3xgq4he2wdiz5ub56cadhgb66a 
#### Address 
> f16xg7ndclvgnu56mj3jzat4gtlvvhgepnt2lcqaa
#### Datacap Allocated
> 2.62PiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedlm3r3yjqocogu63efwjixm4zg3xgq4he2wdiz5ub56cadhgb66a

**Comment by Chris00618** [comment]
![1660281108544](https://user-images.githubusercontent.com/105741726/184290142-02d56240-1243-484a-bfe2-f7a161bffb15.png)

Retrieval failed and can't be verified.

**Comment by xingjitansuo** [comment]
> ![1660281108544](https://user-images.githubusercontent.com/105741726/184290142-02d56240-1243-484a-bfe2-f7a161bffb15.png)
> 
> Retrieval failed and can't be verified.

Hilarious hahahaha....

**Comment by xiaoyuaiheshui** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec7r5m3rur4pz7v2evgujztekfeawehtlr3efznv36ifuq7dvwaa6 
#### Address 
> f16xg7ndclvgnu56mj3jzat4gtlvvhgepnt2lcqaa
#### Datacap Allocated
> 2.62PiB
#### Signer Address
> f122qmy25wdtt5mxd77kndiq7z5x2n3iwiuz2wdsa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec7r5m3rur4pz7v2evgujztekfeawehtlr3efznv36ifuq7dvwaa6

**Comment by psh0691** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceblbmvfbynhz5imbdz3bztqpwwdkayz6wy6d476k4rpkf2d54akfw 
#### Address 
> f16xg7ndclvgnu56mj3jzat4gtlvvhgepnt2lcqaa
#### Datacap Allocated
> 1.92PiB
#### Signer Address
> f1qdko4jg25vo35qmyvcrw4ak4fmuu3f5rif2kc7i
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceblbmvfbynhz5imbdz3bztqpwwdkayz6wy6d476k4rpkf2d54akfw

**Comment by llifezou** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecxmomjvq346xocvq4zyace4ewwp3utxwopys4d3q77nhnns6caau 
#### Address 
> f16xg7ndclvgnu56mj3jzat4gtlvvhgepnt2lcqaa
#### Datacap Allocated
> 1.92PiB
#### Signer Address
> f1q6bpjlqia6iemqbrdaxr2uehrhpvoju3qh4lpga
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecxmomjvq346xocvq4zyace4ewwp3utxwopys4d3q77nhnns6caau

**Comment by kernelogic** [comment]
Due to duplicate proposal bug, I manually approved some stuck allocations.

Request Approved
Your Datacap Allocation Request has been approved by the Notary

Message sent to Filecoin Network
bafy2bzacea7xqkcuiqfkno4wn6h7mxb23s36a7xjiqeepgsciaicchflqaz4u

Address
f16xg7ndclvgnu56mj3jzat4gtlvvhgepnt2lcqaa

Datacap Allocated
788118939673559 B

Signer Address
f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa

You can check the status of the message here: https://filfox.info/en/message/bafy2bzacea7xqkcuiqfkno4wn6h7mxb23s36a7xjiqeepgsciaicchflqaz4u

**Comment by kernelogic** [comment]
Due to duplicate proposal bug, I manually approved some stuck allocations.

Request Approved
Your Datacap Allocation Request has been approved by the Notary

Message sent to Filecoin Network
bafy2bzacecgc5v37xeteixzycfy6g4ez7ieps5g56m2jm75kmeugsfm5dgdxc

Address
f16xg7ndclvgnu56mj3jzat4gtlvvhgepnt2lcqaa

Datacap Allocated
1565000870511247 B

Signer Address
f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa

You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecgc5v37xeteixzycfy6g4ez7ieps5g56m2jm75kmeugsfm5dgdxc

**Comment by kernelogic** [comment]
Due to duplicate proposal bug, I manually approved some stuck allocations.

Request Approved
Your Datacap Allocation Request has been approved by the Notary

Message sent to Filecoin Network
bafy2bzacebxnzrlfiyng2zvcfyup2jzufh3g3jq7ipavtgnu4trnaritkwej2

Address
f16xg7ndclvgnu56mj3jzat4gtlvvhgepnt2lcqaa

Datacap Allocated
2161727821137838 B

Signer Address
f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa

You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebxnzrlfiyng2zvcfyup2jzufh3g3jq7ipavtgnu4trnaritkwej2

**Comment by kernelogic** [comment]
This client has agreed to not use DC past the applied amount.

**Comment by cryptowhizzard** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebgblhw2mmnqjbwhp37j33l6btk2lwbq3svi2vtxvxjeytqz5ereg 
#### Address 
> f16xg7ndclvgnu56mj3jzat4gtlvvhgepnt2lcqaa
#### Datacap Allocated
> 1.57PiB
#### Signer Address
> f1krmypm4uoxxf3g7okrwtrahlmpcph3y7rbqqgfa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebgblhw2mmnqjbwhp37j33l6btk2lwbq3svi2vtxvxjeytqz5ereg

**Comment by kernelogic** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacealfojkyg677xvv3zdyul34ah7nyhkxkp77av4z7cgzosfjdvq54s 
#### Address 
> f16xg7ndclvgnu56mj3jzat4gtlvvhgepnt2lcqaa
#### Datacap Allocated
> 1.57PiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacealfojkyg677xvv3zdyul34ah7nyhkxkp77av4z7cgzosfjdvq54s

**Comment by psh0691** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecr3ahfrk3lcgjcgelfzoicrxjdtbsxnsscqd6jdlqsntglllovoo 
#### Address 
> f16xg7ndclvgnu56mj3jzat4gtlvvhgepnt2lcqaa
#### Datacap Allocated
> 1.57PiB
#### Signer Address
> f1qdko4jg25vo35qmyvcrw4ak4fmuu3f5rif2kc7i
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecr3ahfrk3lcgjcgelfzoicrxjdtbsxnsscqd6jdlqsntglllovoo

**Comment by raghavrmadya** [comment]
hi @xingjitansuo , after checking on verify.glif.io, your address has 3.2 PiBs left but based on this issue, you should have 2.4 PiB remaining. Please confirm so I can push the request for the same. Thanks

**Comment by xingjitansuo** [comment]
Confirmed. @raghavrmadya

**Comment by xingjitansuo** [comment]
Thanks everyone helped with this LDN. Closing this one as it is done.

**Comment by dkkapur** [comment]
@xingjitansuo this also means once you get to 2.4 PiB remaining, we should stop there and remove the remaining DataCap. If you have reason to use more, please share why with the rest of the community since that means >5 PiB would have been used by this project.

**Comment by xingjitansuo** [comment]
Yes, they should support public retrieval.
 I made all the deal information, SP partner, and retrieval CLI public at https://dstorage.cabrina.xyz/bdc2.8/.  Community members are welcome to use that as a reference.  

@Sunnyiscoming

**Comment by filplus-checker** [comment]
## DataCap and CID Checker Report[^1]
 - Organization: `CabrinaHuang - Slingshot Brazil Data Cube Dataset`
 - Client: `f16xg7ndclvgnu56mj3jzat4gtlvvhgepnt2lcqaa`
### Storage Provider Distribution
The below table shows the distribution of storage providers that have stored data for this client.

If this is the first time a provider takes verified deal, it will be marked as `new`.

For most of the datacap application, below restrictions should apply.
 - Storage provider should not exceed 25% of total datacap.
 - Storage provider should not be storing duplicate data for more than 20%.
 - Storage provider should have published its public IP address.
 - All storage providers should be located in different regions.

⚠️ 50.38% of total deal sealed by [f01882035](https://filfox.info/en/address/f01882035) are duplicate data.

⚠️ 50.00% of total deal sealed by [f01887962](https://filfox.info/en/address/f01887962) are duplicate data.

⚠️ 50.00% of total deal sealed by [f01946104](https://filfox.info/en/address/f01946104) are duplicate data.

⚠️ 50.00% of total deal sealed by [f01924827](https://filfox.info/en/address/f01924827) are duplicate data.

⚠️ 49.96% of total deal sealed by [f01270767](https://filfox.info/en/address/f01270767) are duplicate data.

⚠️ 46.69% of total deal sealed by [f034258](https://filfox.info/en/address/f034258) are duplicate data.

⚠️ 46.08% of total deal sealed by [f01850141](https://filfox.info/en/address/f01850141) are duplicate data.

⚠️ 42.24% of total deal sealed by [f01926698](https://filfox.info/en/address/f01926698) are duplicate data.

⚠️ [f01926698](https://filfox.info/en/address/f01926698) has unknown IP location.

⚠️ 28.90% of total deal sealed by [f098743](https://filfox.info/en/address/f098743) are duplicate data.

⚠️ 21.56% of total deal sealed by [f01841133](https://filfox.info/en/address/f01841133) are duplicate data.

| Provider                                                    |                           Location | Total Deals Sealed | Percentage | Unique Data | Duplicate Deals |
| :---------------------------------------------------------- | ---------------------------------: | -----------------: | ---------: | ----------: | --------------: |
| [f01882035](https://filfox.info/en/address/f01882035)       |               Chengdu, Sichuan, CN |         474.22 TiB |      8.76% |  235.31 TiB |          50.38% |
| [f01887962](https://filfox.info/en/address/f01887962)`new`  | Hong Kong, Central and Western, HK |         470.63 TiB |      8.69% |  235.31 TiB |          50.00% |
| [f01946104](https://filfox.info/en/address/f01946104)       |               Chengdu, Sichuan, CN |         470.63 TiB |      8.69% |  235.31 TiB |          50.00% |
| [f01924827](https://filfox.info/en/address/f01924827)       | Hong Kong, Central and Western, HK |         470.63 TiB |      8.69% |  235.31 TiB |          50.00% |
| [f01270767](https://filfox.info/en/address/f01270767)       |           Guangzhou, Guangdong, CN |         470.25 TiB |      8.69% |  235.31 TiB |          49.96% |
| [f034258](https://filfox.info/en/address/f034258)           |               Chengdu, Sichuan, CN |         441.38 TiB |      8.15% |  235.31 TiB |          46.69% |
| [f01850141](https://filfox.info/en/address/f01850141)       | Hong Kong, Central and Western, HK |         436.25 TiB |      8.06% |  235.22 TiB |          46.08% |
| [f01926698](https://filfox.info/en/address/f01926698)`new`  |                            Unknown |         404.44 TiB |      7.47% |  233.59 TiB |          42.24% |
| [f098743](https://filfox.info/en/address/f098743)           |            Shenzhen, Guangdong, CN |         330.94 TiB |      6.11% |  235.31 TiB |          28.90% |
| [f01841133](https://filfox.info/en/address/f01841133)       |           Singapore, Singapore, SG |         299.88 TiB |      5.54% |  235.22 TiB |          21.56% |
| [f01937454](https://filfox.info/en/address/f01937454)`new`  |               Chengdu, Sichuan, CN |         244.69 TiB |      4.52% |  235.31 TiB |           3.83% |
| [f01806248](https://filfox.info/en/address/f01806248)       |           Singapore, Singapore, SG |         200.00 TiB |      3.69% |  200.00 TiB |           0.00% |
| [f01863339](https://filfox.info/en/address/f01863339)       |             Shanghai, Shanghai, CN |         125.00 TiB |      2.31% |  125.00 TiB |           0.00% |
| [f0117211](https://filfox.info/en/address/f0117211)         |           Singapore, Singapore, SG |         115.00 TiB |      2.12% |  115.00 TiB |           0.00% |
| [f01841131](https://filfox.info/en/address/f01841131)       | Hong Kong, Central and Western, HK |          99.75 TiB |      1.84% |   99.75 TiB |           0.00% |
| [f01939377](https://filfox.info/en/address/f01939377)       |               Chengdu, Sichuan, CN |          93.06 TiB |      1.72% |   93.06 TiB |           0.00% |
| [f01941622](https://filfox.info/en/address/f01941622)       |               Chengdu, Sichuan, CN |          73.38 TiB |      1.36% |   73.38 TiB |           0.00% |
| [f01392600](https://filfox.info/en/address/f01392600)       | Hong Kong, Central and Western, HK |          69.78 TiB |      1.29% |   69.78 TiB |           0.00% |
| [f0142637](https://filfox.info/en/address/f0142637)         |               Chengdu, Sichuan, CN |          62.25 TiB |      1.15% |   62.25 TiB |           0.00% |
| [f0136399](https://filfox.info/en/address/f0136399)         | Hong Kong, Central and Western, HK |          49.97 TiB |      0.92% |   49.97 TiB |           0.00% |
| [f01939387](https://filfox.info/en/address/f01939387)       |               Chengdu, Sichuan, CN |          11.00 TiB |      0.20% |   11.00 TiB |           0.00% |

![Provider Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/419/1671096840879.png)
### Deal Data Replication
The below table shows how each many unique data are replicated across storage providers.
- No more than 25% of unique data are stored with less than 4 providers.

✔️ Data replication looks healthy.

| Unique Data Size | Total Deals Made | Number of Providers | Deal Percentage |
| ---------------: | ---------------: | ------------------: | --------------: |
|         1.69 TiB |        27.09 TiB |                  10 |           0.50% |
|        32.25 TiB |       550.75 TiB |                  11 |          10.17% |
|        73.19 TiB |         1.38 PiB |                  12 |          26.08% |
|         5.88 TiB |       121.38 TiB |                  13 |           2.24% |
|        12.66 TiB |       278.34 TiB |                  14 |           5.14% |
|        11.38 TiB |       263.41 TiB |                  15 |           4.87% |
|        21.75 TiB |       539.63 TiB |                  16 |           9.97% |
|         3.44 TiB |        90.41 TiB |                  17 |           1.67% |
|        15.75 TiB |       435.34 TiB |                  18 |           8.04% |
|        26.41 TiB |       761.47 TiB |                  19 |          14.07% |
|        29.69 TiB |       894.91 TiB |                  20 |          16.53% |
|         1.25 TiB |        38.75 TiB |                  21 |           0.72% |

![Replication Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/419/1671096841599.png)
### Deal Data Shared with other Clients
The below table shows how many unique data are shared with other clients.
Usually different applications owns different data and should not resolve to the same CID.

✔️ No CID sharing has been observed.

[^1]: To manually trigger this report, add a comment with text `checker:manualTrigger`
