### ISSUE TITLE
[DataCap Application]China Tianying INC.

### ISSUE THREAD

**Issue by HowardAce** [filecoin-project/filecoin-plus-large-datasets#426]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name:  China Tianying INC.
- Website / Social Media:https://www.ctyi.com.cn/index.html
  Official Account: tianyinghuanbao
  Tik Tok: 中国天楹股份有限公司  
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 2PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):100TiB
- On-chain address for first allocation:  f14uxcyaoab3qhn42kaquqysga6f6zfry3x4nk3ca

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
China Tianying Inc.(stockcode:000035)(hereinafter referred to as“CNTY”)is a listed international company engaged in zero-carbon clean energy technologies, smart urban environmental services and resource recycling and recovery.

China Tianying (CNTY) is an international environmental management corporation. Our urban service is featuring a “5A” model—All settings, All types, All smart, All processes, All treatments—covering the entire industrial chain of solid waste management. Our businesses extend from industrial R&D, urban services, waste disposal, equipment manufacturing to developing intelligent management platforms. With global wisdom and professional expertise at our disposal, we are committed to further improving the environment and recycling the resources on our planet.

Our scope of business expands from smart urban environmental services, Waste-to-Energy power generation, renewable energy power generation, regional enerqy centers, hydrogen energy centers, the investment, construction, and operation of circular economy industrial parks, to the reduction, recycling, and harmless treatment of kitchen waste, hazardous waste, construction, and demolition waste, as well as the research, development, and manufacturing of environmental protection equipment and energy storage systems.

Driven by innovation and backed by top-notch equipment manufacturing and R&D capabilities, CNTY strives to lead renewable energy upgrades and business model transformation through information, automation, and industrialization solutions including plasma technology, automated sorting system, environmental service cloud platform, zero-carbon energy network centers, and smart loT centers, making due contribution to the objectives for carbon peaking and carbon neutrality of China.

Leveraging our advanced technologies, global talent pool, and capital resources, CNTY cultivates the renewable energy industry through designing, investing, constructing, and operating activities in the fields of distributed photovoltaic systems, nearshore photovoltaic systems, gravity energy storage and offshore wind power generation. In meeting the demand for regionalenergy centers and needs along the industry chain, we have embarked on an innovative developing path that is unique to our strenaths and in line with the national carbon peaking and carbon neutrality strategies.
```

What is the primary source of funding for this project?
```
From our own business.
```

What other projects/ecosystem stakeholders is this project associated with?
```
None
```

## Use-case details

Describe the data being stored onto Filecoin
```
It mainly contains operation and management data of zero-carbon clean energy technologies, smart urban environmental services and resource recycling and recovery;
business solution data and reports data , etc.
```

Where was the data in this dataset sourced from?
```
The data is our own business data and open solutions& reports data provided by third parties.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://github.com/HowardAce/Samples
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Confirmed
```

What is the expected retrieval frequency for this data?
```
We will conduct retrieval during the annual audit.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
We plan to try to store data for two years.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Considering the audit, we hope to make storage deals in China.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Both online and offline.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We want storage providers to contact us, and we also want them to show us how long they are available, so that we can ensure the security of our data storage for a long time. In addition, we will find storage providers on our own.
```

How will you be distributing deals across storage providers?
```
We will make a fair allocation based on the service capacity on the storage service.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
YES
```

**Comment by Sunnyiscoming** [comment]
@HowardAce  Hey. Could you send an email to [filplus@fil.org](mailto:filplus@fil.org) with your official domain in order to confirm your identity?

**Comment by HowardAce** [comment]
@Sunnyiscoming Please check

**Comment by galen-mcandrew** [comment]
## Datacap Request Trigger
#### Total DataCap requested 
> 2PiB
#### Expected weekly DataCap usage rate 
> 100TiB 
#### Client address
> f14uxcyaoab3qhn42kaquqysga6f6zfry3x4nk3ca

**Comment by BlockMakeronline** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedg2iwqxi3g6cbrkprdj2w2dsyzhbsrxevv675qao2orkpkpo7xzg 
#### Address 
> f14uxcyaoab3qhn42kaquqysga6f6zfry3x4nk3ca
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1o3twrcpwjtpcd4q36lpq4qmy2qfbgtyy5h6tsty
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedg2iwqxi3g6cbrkprdj2w2dsyzhbsrxevv675qao2orkpkpo7xzg

**Comment by MRJAVAZHAO** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecr2vhvrj5uoqajmwo4bbuyozuksjvoh2pctttkvpnhwctt3j6odg 
#### Address 
> f14uxcyaoab3qhn42kaquqysga6f6zfry3x4nk3ca
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f14gme3f52prtyzk6pblogrdd6b6ivp4swc6qmesi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecr2vhvrj5uoqajmwo4bbuyozuksjvoh2pctttkvpnhwctt3j6odg

**Comment by BigD-Exchange** [comment]
@HowardAce Hi! Great to see you have gotten approval for DataCap. If you are looking for storage providers to store these data, please visit #bigdata-exchange on Filecoin Slack or reply here.

**Comment by PluskitOfficial** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceczagtevvga6matfjil7xlloll4re4uda2arvbsz3jxgveyquiede 
#### Address 
> f14uxcyaoab3qhn42kaquqysga6f6zfry3x4nk3ca
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1tgnlhtcmhwipfm7thsftxhn5k52velyjlazpvka
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceczagtevvga6matfjil7xlloll4re4uda2arvbsz3jxgveyquiede

**Comment by MRJAVAZHAO** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedylhxomkvnk6dfk7u5y4b6aiprcqmfoaijvofaaehghiw6e7rqww 
#### Address 
> f14uxcyaoab3qhn42kaquqysga6f6zfry3x4nk3ca
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f14gme3f52prtyzk6pblogrdd6b6ivp4swc6qmesi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedylhxomkvnk6dfk7u5y4b6aiprcqmfoaijvofaaehghiw6e7rqww

**Comment by PluskitOfficial** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebuyf3vj4qt6yqbxgubzvbmwypnjc5diow6dbfbrvytfeadvreq2g 
#### Address 
> f14uxcyaoab3qhn42kaquqysga6f6zfry3x4nk3ca
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1tgnlhtcmhwipfm7thsftxhn5k52velyjlazpvka
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebuyf3vj4qt6yqbxgubzvbmwypnjc5diow6dbfbrvytfeadvreq2g

**Comment by MRJAVAZHAO** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebpb4v7ma3dwf6zx2o7rhr2mubasouuq7mvfk2w4ydonefd5xaz42 
#### Address 
> f14uxcyaoab3qhn42kaquqysga6f6zfry3x4nk3ca
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f14gme3f52prtyzk6pblogrdd6b6ivp4swc6qmesi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebpb4v7ma3dwf6zx2o7rhr2mubasouuq7mvfk2w4ydonefd5xaz42

**Comment by MatrixStorage** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebtzpqmq3ydrlng5havwftcjcq36na4tudls5zdrfm3xhhf5tkalq 
#### Address 
> f14uxcyaoab3qhn42kaquqysga6f6zfry3x4nk3ca
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1tbxqwjxfyv7swsdin4einirlsfquv3vnmlapley
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebtzpqmq3ydrlng5havwftcjcq36na4tudls5zdrfm3xhhf5tkalq

**Comment by filplus-checker** [comment]
## DataCap and CID Checker Report[^1]
 - Organization: ` China Tianying INC.`
 - Client: `f14uxcyaoab3qhn42kaquqysga6f6zfry3x4nk3ca`
### Storage Provider Distribution
The below table shows the distribution of storage providers that have stored data for this client.

If this is the first time a provider takes verified deal, it will be marked as `new`.

For most of the datacap application, below restrictions should apply.
 - Storage provider should not exceed 25% of total datacap.
 - Storage provider should not be storing duplicate data for more than 20%.
 - Storage provider should have published its public IP address.
 - All storage providers should be located in different regions.

⚠️ 88.89% of total deal sealed by [f01919535](https://filfox.info/en/address/f01919535) are duplicate data.

⚠️ 36.42% of total deal sealed by [f01852023](https://filfox.info/en/address/f01852023) are duplicate data.

⚠️ 34.46% of total deal sealed by [f01852677](https://filfox.info/en/address/f01852677) are duplicate data.

⚠️ 32.87% of total deal sealed by [f01852325](https://filfox.info/en/address/f01852325) are duplicate data.

⚠️ 34.55% of total deal sealed by [f01852664](https://filfox.info/en/address/f01852664) are duplicate data.

⚠️ 31.46% of total deal sealed by [f01851482](https://filfox.info/en/address/f01851482) are duplicate data.

⚠️ 34.09% of total deal sealed by [f01938718](https://filfox.info/en/address/f01938718) are duplicate data.

| Provider                                              |                           Location | Total Deals Sealed | Percentage | Unique Data | Duplicate Deals |
| :---------------------------------------------------- | ---------------------------------: | -----------------: | ---------: | ----------: | --------------: |
| [f01919535](https://filfox.info/en/address/f01919535) |                   Wuhan, Hubei, CN |         186.28 TiB |     24.84% |   20.69 TiB |          88.89% |
| [f01852023](https://filfox.info/en/address/f01852023) |                   Busan, Busan, KR |         149.22 TiB |     19.90% |   94.88 TiB |          36.42% |
| [f01852677](https://filfox.info/en/address/f01852677) |    Morrisville, North Carolina, US |         126.59 TiB |     16.88% |   82.97 TiB |          34.46% |
| [f01852325](https://filfox.info/en/address/f01852325) | Hong Kong, Central and Western, HK |          92.78 TiB |     12.37% |   62.28 TiB |          32.87% |
| [f01852664](https://filfox.info/en/address/f01852664) |           Singapore, Singapore, SG |          92.53 TiB |     12.34% |   60.56 TiB |          34.55% |
| [f01851482](https://filfox.info/en/address/f01851482) |                   Busan, Busan, KR |          76.38 TiB |     10.19% |   52.34 TiB |          31.46% |
| [f01938718](https://filfox.info/en/address/f01938718) |    Morrisville, North Carolina, US |          26.03 TiB |      3.47% |   17.16 TiB |          34.09% |

![Provider Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/426/1671096868811.png)
### Deal Data Replication
The below table shows how each many unique data are replicated across storage providers.
- No more than 25% of unique data are stored with less than 4 providers.

⚠️ 90.26% of deals are for data replicated across less than 4 storage providers.

| Unique Data Size | Total Deals Made | Number of Providers | Deal Percentage |
| ---------------: | ---------------: | ------------------: | --------------: |
|       165.69 TiB |       417.47 TiB |                   1 |          55.68% |
|        35.38 TiB |       118.69 TiB |                   2 |          15.83% |
|        31.16 TiB |       140.59 TiB |                   3 |          18.75% |
|        14.03 TiB |        68.22 TiB |                   4 |           9.10% |
|       992.00 GiB |         4.84 TiB |                   5 |           0.65% |

![Replication Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/426/1671096869321.png)
### Deal Data Shared with other Clients
The below table shows how many unique data are shared with other clients.
Usually different applications owns different data and should not resolve to the same CID.

⚠️ CID sharing has been observed.

| Other Client                                                                                                                                                                                                              | Application                                                                                                                    | Total Deals Affected | Unique CIDs |        Verifier |
| :------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ | :----------------------------------------------------------------------------------------------------------------------------- | -------------------: | ----------: | --------------: |
| [f3qvn7f5u4z5w5pqx3htckp4jcn5dvgmebq6qkqcz<br/>xdxkicwokf75tt5hbwtrjwldz2sjiyq752ajcn3nd<br/>5tgq](https://filfox.info/en/address/f3qvn7f5u4z5w5pqx3htckp4jcn5dvgmebq6qkqczxdxkicwokf75tt5hbwtrjwldz2sjiyq752ajcn3nd5tgq) | [Beijing Haishi Hengtong Technology Co\., LTD](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/66)     |           161.28 TiB |       2,022 | LDN v3 multisig |
| [f3w4wlayytfmsay6gu5phhij5r4yyx7t4xxrlosgo<br/>tlmqg5eih3co5atsra4h2pe4qd2d6c76bvhj6nwim<br/>7lgq](https://filfox.info/en/address/f3w4wlayytfmsay6gu5phhij5r4yyx7t4xxrlosgotlmqg5eih3co5atsra4h2pe4qd2d6c76bvhj6nwim7lgq) | [GMWBR INC](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/73)                                        |           117.19 TiB |       2,020 | LDN v3 multisig |
| [f3xffjctbyy7zigopfa3za5ha3pvv4z3xfghlw7kw<br/>vyeuabkg4lzsgfwhnghwkvmmvi6yso6k52hq3ca6c<br/>kveq](https://filfox.info/en/address/f3xffjctbyy7zigopfa3za5ha3pvv4z3xfghlw7kwvyeuabkg4lzsgfwhnghwkvmmvi6yso6k52hq3ca6ckveq) | [Chengdu Digital Media Industry Base Co\., Ltd\.](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/387) |           108.22 TiB |       1,424 | LDN v3 multisig |
| [f1piaz4nodpwdemrfqak5jlfg5ois2onzmjv6fkki](https://filfox.info/en/address/f1piaz4nodpwdemrfqak5jlfg5ois2onzmjv6fkki)                                                                                                     | [Chengdu Yundianshang Technology Co\., LTD](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/399)       |            34.81 TiB |         614 | LDN v3 multisig |
| [f3uils5cdx3ezyzszjjfnulugknbdsanmqtisd7x7<br/>xkfcljdnshp4jspnrgxpldt5b4aafuz4q4rkebpjy<br/>keha](https://filfox.info/en/address/f3uils5cdx3ezyzszjjfnulugknbdsanmqtisd7x7xkfcljdnshp4jspnrgxpldt5b4aafuz4q4rkebpjykeha) | [Qingyun Education Fund](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/31)                           |            32.66 TiB |         672 | LDN v3 multisig |
| [f1elncewt3sh356aop52uvcappblxmf6asbmhxlya](https://filfox.info/en/address/f1elncewt3sh356aop52uvcappblxmf6asbmhxlya)                                                                                                     | [Beijing Wanjie Data Technology Co\., LTD](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/404)        |            29.69 TiB |         641 | LDN v3 multisig |
| [f1cuboogcwais57dljrpeltoy6ja2itb7wvwmrl3q](https://filfox.info/en/address/f1cuboogcwais57dljrpeltoy6ja2itb7wvwmrl3q)                                                                                                     | [Penglaiju](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/400)                                       |            28.09 TiB |         518 | LDN v3 multisig |
| [f17tvb3ejs3ev6owqmkpzomtewgrd6v2sofv7upma](https://filfox.info/en/address/f17tvb3ejs3ev6owqmkpzomtewgrd6v2sofv7upma)                                                                                                     | [Beijing Lexun Technology Co\., LTD](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/395)              |            17.97 TiB |         369 | LDN v3 multisig |
| [f1uuzet23wng5lxu3y4iicokksydynamgmptfekdq](https://filfox.info/en/address/f1uuzet23wng5lxu3y4iicokksydynamgmptfekdq)                                                                                                     | `Explainer video`                                                                                                              |            10.69 TiB |         121 |        LDN # 65 |
| [f3q7ablez3jqkcjukwbzaql7lmbx4ldouu66nexpd<br/>cfvu6kgho3v6gricckt77cgr46tdre2l4zmvha7bs<br/>u7qq](https://filfox.info/en/address/f3q7ablez3jqkcjukwbzaql7lmbx4ldouu66nexpdcfvu6kgho3v6gricckt77cgr46tdre2l4zmvha7bsu7qq) | `MatrixStorage`                                                                                                                |             8.03 TiB |          97 |        LDN # 72 |
| [f1budai5eqmk7zjfd54bmnkj72vuc7jykmkkttgha](https://filfox.info/en/address/f1budai5eqmk7zjfd54bmnkj72vuc7jykmkkttgha)                                                                                                     | ``                                                                                                                             |             7.63 TiB |          37 |        LDN # 64 |
| [f1pediuk4kncwp4qxawlope7hzfmd2ran35w54o7y](https://filfox.info/en/address/f1pediuk4kncwp4qxawlope7hzfmd2ran35w54o7y)                                                                                                     | [Qistone Information technology](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/324)                  |             7.34 TiB |         131 | LDN v3 multisig |
| [f14nyld75bnvr2y3ca4ew7vxmwp4tuwytqwggthcy](https://filfox.info/en/address/f14nyld75bnvr2y3ca4ew7vxmwp4tuwytqwggthcy)                                                                                                     | `Kimoc`                                                                                                                        |             4.13 TiB |          93 | LDN v3 multisig |
| [f3q3eysweh273pwygu27yllyafljznqewpxwlrc7j<br/>daugrpvhmrcnxmkn43wkctxalcg3z42zxas2hinsf<br/>tgva](https://filfox.info/en/address/f3q3eysweh273pwygu27yllyafljznqewpxwlrc7jdaugrpvhmrcnxmkn43wkctxalcg3z42zxas2hinsftgva) | [Beijing Yibo Technology Co\., Ltd\.](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/74)              |             2.41 TiB |          52 |        LDN # 74 |
| [f3woqxpu6ekmj43nmpcv7j2pgu6lejxtzgxpzl6f2<br/>vrueoqlzjntakyhdkghymyffbzfbsio6dvfmy643x<br/>4y7q](https://filfox.info/en/address/f3woqxpu6ekmj43nmpcv7j2pgu6lejxtzgxpzl6f2vrueoqlzjntakyhdkghymyffbzfbsio6dvfmy643x4y7q) | [RICH ST PETE LLC](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/64)                                 |           160.00 GiB |           3 | LDN v3 multisig |

[^1]: To manually trigger this report, add a comment with text `checker:manualTrigger`
