### ISSUE TITLE
[DataCap Application]Slingshot Fly Brain for Drust-Agee

### ISSUE THREAD

**Issue by Agee-Drust** [filecoin-project/filecoin-plus-large-datasets#427]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Drust
- Website / Social Media:N/A
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):1.2PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):300TiB
- On-chain address for first allocation:f17qd6x3leh5pa7vh6ewdaed7qhbn2mgofrokuayy

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
I'm new in Filecoin, but I have ambitious with Filecoin and Filecoin slingshot about ensuring meaningful data is stored and retrieved from the Filecoin Network.
```

What is the primary source of funding for this project?
```
My own source. And I'd like to get slingshot rewards as return.
```

What other projects/ecosystem stakeholders is this project associated with?
```
Slingshot.
```

## Use-case details

Describe the data being stored onto Filecoin
```
Consists of fluorescence images of Drosophila melanogaster driver lines, aligned to standard templates, and stored in formats suitable for rapid searching in the cloud.
```

Where was the data in this dataset sourced from?
```
It is made available by Janelia's FlyLight project.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
aws s3 ls --no-sign-request s3://janelia-flylight-imagery/
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
I confirm. This is open dataset.
```

What is the expected retrieval frequency for this data?
```
Follow Slingshot retrieval rules.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
More than 1 year.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
All regions, especially SPs in Asia. 
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
After CAR files are ready, I will upload it to the server for SP, or I will prepare disks. Then I will propose offline deals after they get files.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
I plan to make deals with SPs that support data retrieval and have stable sealing rate. Also, I welcome every one who are interested with this deal.
```

How will you be distributing deals across storage providers?
```
Try to make every SP under 25% of deals.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Enough.
```

**Comment by dkkapur** [comment]
## Datacap Request Trigger
#### Total DataCap requested 
> 1.2 PiB
#### Expected weekly DataCap usage rate 
> 300 TiB 
#### Client address
> f17qd6x3leh5pa7vh6ewdaed7qhbn2mgofrokuayy

**Comment by BlockMakeronline** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec4gmjqlo4invohwnjp5dxalahnh6dyahop3mzoz24gv36ughe6iu 
#### Address 
> f17qd6x3leh5pa7vh6ewdaed7qhbn2mgofrokuayy
#### Datacap Allocated
> 61.43TiB
#### Signer Address
> f1o3twrcpwjtpcd4q36lpq4qmy2qfbgtyy5h6tsty
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec4gmjqlo4invohwnjp5dxalahnh6dyahop3mzoz24gv36ughe6iu

**Comment by MRJAVAZHAO** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecc4mv57sbfyljfjvvqc3p4wie4katl36hxmjjccfjwdssov36aci 
#### Address 
> f17qd6x3leh5pa7vh6ewdaed7qhbn2mgofrokuayy
#### Datacap Allocated
> 61.43TiB
#### Signer Address
> f14gme3f52prtyzk6pblogrdd6b6ivp4swc6qmesi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecc4mv57sbfyljfjvvqc3p4wie4katl36hxmjjccfjwdssov36aci

**Comment by BigD-Exchange** [comment]
@Agee-Drust Hi! Great to see you have gotten approval for DataCap. If you are looking for storage providers to store these data or have any questions, please visit #bigdata-exchange on Filecoin Slack or reply here. 

We have strong demand from a diverse group of SPs, who are actively looking to onboard more data.

**Comment by UnionLabs2020** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced5kfckzv57ty3dwrkkuntejkio4yb2owdjatzdneply2bgg2fa72 
#### Address 
> f17qd6x3leh5pa7vh6ewdaed7qhbn2mgofrokuayy
#### Datacap Allocated
> 122.87TiB
#### Signer Address
> f17xdri3wunqgld7dm23e4f3eqsntjakwc47xjo6i
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced5kfckzv57ty3dwrkkuntejkio4yb2owdjatzdneply2bgg2fa72

**Comment by PluskitOfficial** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedxc5652c2bbzylvvkxikzla5tmcjtowag456bb5w4azne7a3j2ko 
#### Address 
> f17qd6x3leh5pa7vh6ewdaed7qhbn2mgofrokuayy
#### Datacap Allocated
> 122.87TiB
#### Signer Address
> f1tgnlhtcmhwipfm7thsftxhn5k52velyjlazpvka
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedxc5652c2bbzylvvkxikzla5tmcjtowag456bb5w4azne7a3j2ko

**Comment by BigD-Exchange** [comment]
@Agee-Drust Hi! Great to see you have gotten approval for DataCap. If you are looking for more storage providers to store these data or have any questions, please visit #bigdata-exchange on Filecoin Slack or reply here. 

We have strong demand from a diverse group of SPs, who are actively looking to onboard more data.

**Comment by PluskitOfficial** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebopqjvsmrhatagjyrysumoehlj7y74jnkokln6qf6d5oni3jltac 
#### Address 
> f17qd6x3leh5pa7vh6ewdaed7qhbn2mgofrokuayy
#### Datacap Allocated
> 245.75TiB
#### Signer Address
> f1tgnlhtcmhwipfm7thsftxhn5k52velyjlazpvka
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebopqjvsmrhatagjyrysumoehlj7y74jnkokln6qf6d5oni3jltac

**Comment by MatrixStorage** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceauinyqbe2gaqlzcoz3mrlkiqkwpyo65smdnrqnr2u6qy5snfy3fk 
#### Address 
> f17qd6x3leh5pa7vh6ewdaed7qhbn2mgofrokuayy
#### Datacap Allocated
> 245.75TiB
#### Signer Address
> f1tbxqwjxfyv7swsdin4einirlsfquv3vnmlapley
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceauinyqbe2gaqlzcoz3mrlkiqkwpyo65smdnrqnr2u6qy5snfy3fk

**Comment by PluskitOfficial** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebjj4vyjxkttdgpkediucooi42yqx5jsthxunzhkzmole5yi2mdz4 
#### Address 
> f17qd6x3leh5pa7vh6ewdaed7qhbn2mgofrokuayy
#### Datacap Allocated
> 491.51TiB
#### Signer Address
> f1tgnlhtcmhwipfm7thsftxhn5k52velyjlazpvka
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebjj4vyjxkttdgpkediucooi42yqx5jsthxunzhkzmole5yi2mdz4

**Comment by jamerduhgamer** [comment]
Hi @PluskitOfficial, I see you approved both the previous and current tranche. Reminder that the outline stated here says the notaries should be alternating between tranches - https://github.com/filecoin-project/filecoin-plus-large-datasets/#applying-for-a-large-datacap-allocation

**Comment by MRJAVAZHAO** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb6ljyxgstlo4mbafgxd2v6ghvb5ubrsccveoy2dc4k6ljwkux63y 
#### Address 
> f17qd6x3leh5pa7vh6ewdaed7qhbn2mgofrokuayy
#### Datacap Allocated
> 491.51TiB
#### Signer Address
> f14gme3f52prtyzk6pblogrdd6b6ivp4swc6qmesi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb6ljyxgstlo4mbafgxd2v6ghvb5ubrsccveoy2dc4k6ljwkux63y

**Comment by PluskitOfficial** [comment]
> Hi @PluskitOfficial, I see you approved both the previous and current tranche. Reminder that the outline stated here says the notaries should be alternating between tranches - https://github.com/filecoin-project/filecoin-plus-large-datasets/#applying-for-a-large-datacap-allocation

Hi, @jamerduhgamer, thanks for your reminder. We'll pay attention in the future.

**Comment by MetaWaveInfo** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceafmbyrdpxnno2zgm2yk7exaw42uf6sbzf5gbomvtvwmgvjtylxok 
#### Address 
> f17qd6x3leh5pa7vh6ewdaed7qhbn2mgofrokuayy
#### Datacap Allocated
> 307.24TiB
#### Signer Address
> f1ktlkcxnmzxcdaoqfsunrg3vocfbmgv4n3mrn74a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceafmbyrdpxnno2zgm2yk7exaw42uf6sbzf5gbomvtvwmgvjtylxok

**Comment by UnionLabs2020** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceafmlhfzno5wkxkxgrwedpmortbm7zbqiqtwkdgggwm7mkv6xvtai 
#### Address 
> f17qd6x3leh5pa7vh6ewdaed7qhbn2mgofrokuayy
#### Datacap Allocated
> 307.24TiB
#### Signer Address
> f17xdri3wunqgld7dm23e4f3eqsntjakwc47xjo6i
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceafmlhfzno5wkxkxgrwedpmortbm7zbqiqtwkdgggwm7mkv6xvtai

**Comment by filplus-checker** [comment]
## DataCap and CID Checker Report[^1]
 - Organization: `Drust`
 - Client: `f17qd6x3leh5pa7vh6ewdaed7qhbn2mgofrokuayy`
### Storage Provider Distribution
The below table shows the distribution of storage providers that have stored data for this client.

If this is the first time a provider takes verified deal, it will be marked as `new`.

For most of the datacap application, below restrictions should apply.
 - Storage provider should not exceed 25% of total datacap.
 - Storage provider should not be storing duplicate data for more than 20%.
 - Storage provider should have published its public IP address.
 - All storage providers should be located in different regions.

⚠️ 39.24% of total deal sealed by [f01900713](https://filfox.info/en/address/f01900713) are duplicate data.

⚠️ 30.29% of total deal sealed by [f01895715](https://filfox.info/en/address/f01895715) are duplicate data.

⚠️ 38.53% of total deal sealed by [f01917241](https://filfox.info/en/address/f01917241) are duplicate data.

⚠️ 71.02% of total deal sealed by [f01924325](https://filfox.info/en/address/f01924325) are duplicate data.

⚠️ 88.52% of total deal sealed by [f01895783](https://filfox.info/en/address/f01895783) are duplicate data.

⚠️ 51.58% of total deal sealed by [f01917257](https://filfox.info/en/address/f01917257) are duplicate data.

⚠️ 70.64% of total deal sealed by [f01924350](https://filfox.info/en/address/f01924350) are duplicate data.

⚠️ 71.25% of total deal sealed by [f01924416](https://filfox.info/en/address/f01924416) are duplicate data.

⚠️ 89.40% of total deal sealed by [f01844043](https://filfox.info/en/address/f01844043) are duplicate data.

⚠️ 86.76% of total deal sealed by [f01937964](https://filfox.info/en/address/f01937964) are duplicate data.

| Provider                                                    |                 Location | Total Deals Sealed | Percentage | Unique Data | Duplicate Deals |
| :---------------------------------------------------------- | -----------------------: | -----------------: | ---------: | ----------: | --------------: |
| [f01900713](https://filfox.info/en/address/f01900713)`new`  |         Seoul, Seoul, KR |         237.22 TiB |     19.31% |  144.13 TiB |          39.24% |
| [f01895715](https://filfox.info/en/address/f01895715)`new`  |         Seoul, Seoul, KR |         167.84 TiB |     13.66% |  117.00 TiB |          30.29% |
| [f01914977](https://filfox.info/en/address/f01914977)`new`  |    Ashburn, Virginia, US |         134.97 TiB |     10.98% |  127.81 TiB |           5.30% |
| [f01917241](https://filfox.info/en/address/f01917241)`new`  |         Seoul, Seoul, KR |         132.38 TiB |     10.77% |   81.38 TiB |          38.53% |
| [f01924325](https://filfox.info/en/address/f01924325)       | Singapore, Singapore, SG |         124.00 TiB |     10.09% |   35.94 TiB |          71.02% |
| [f01895783](https://filfox.info/en/address/f01895783)       |     Boardman, Oregon, US |         122.72 TiB |      9.99% |   14.09 TiB |          88.52% |
| [f01917257](https://filfox.info/en/address/f01917257)       |         Seoul, Seoul, KR |         102.63 TiB |      8.35% |   49.69 TiB |          51.58% |
| [f01916487](https://filfox.info/en/address/f01916487)`new`  |         Seoul, Seoul, KR |          46.84 TiB |      3.81% |   46.84 TiB |           0.00% |
| [f01924350](https://filfox.info/en/address/f01924350)       | Singapore, Singapore, SG |          37.47 TiB |      3.05% |   11.00 TiB |          70.64% |
| [f01917214](https://filfox.info/en/address/f01917214)`new`  |         Seoul, Seoul, KR |          34.00 TiB |      2.77% |   34.00 TiB |           0.00% |
| [f01924416](https://filfox.info/en/address/f01924416)       | Singapore, Singapore, SG |          27.94 TiB |      2.27% |    8.03 TiB |          71.25% |
| [f01844043](https://filfox.info/en/address/f01844043)       |       Hilliard, Ohio, US |          25.66 TiB |      2.09% |    2.72 TiB |          89.40% |
| [f01843994](https://filfox.info/en/address/f01843994)       |       Hilliard, Ohio, US |           8.47 TiB |      0.69% |    7.22 TiB |          14.76% |
| [f01844118](https://filfox.info/en/address/f01844118)       |       Hilliard, Ohio, US |           8.28 TiB |      0.67% |    7.22 TiB |          12.83% |
| [f01844329](https://filfox.info/en/address/f01844329)       |       Hilliard, Ohio, US |           7.22 TiB |      0.59% |    6.25 TiB |          13.42% |
| [f01844232](https://filfox.info/en/address/f01844232)       |       Hilliard, Ohio, US |           6.91 TiB |      0.56% |    6.22 TiB |           9.95% |
| [f01937964](https://filfox.info/en/address/f01937964)       |         Tokyo, Tokyo, JP |           4.25 TiB |      0.35% |  576.00 GiB |          86.76% |

![Provider Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/427/1671096890607.png)
### Deal Data Replication
The below table shows how each many unique data are replicated across storage providers.
- No more than 25% of unique data are stored with less than 4 providers.

⚠️ 100.00% of deals are for data replicated across less than 4 storage providers.

| Unique Data Size | Total Deals Made | Number of Providers | Deal Percentage |
| ---------------: | ---------------: | ------------------: | --------------: |
|       573.53 TiB |       990.50 TiB |                   1 |          80.61% |
|        60.56 TiB |       229.06 TiB |                   2 |          18.64% |
|         1.81 TiB |         9.22 TiB |                   3 |           0.75% |

![Replication Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/427/1671096891234.png)
### Deal Data Shared with other Clients
The below table shows how many unique data are shared with other clients.
Usually different applications owns different data and should not resolve to the same CID.

⚠️ CID sharing has been observed.

| Other Client                                                                                                          | Application                                                                                                              | Total Deals Affected | Unique CIDs |        Verifier |
| :-------------------------------------------------------------------------------------------------------------------- | :----------------------------------------------------------------------------------------------------------------------- | -------------------: | ----------: | --------------: |
| [f1727w2vwjctfo7hflr5trgqkl3c7texh7pl4grzq](https://filfox.info/en/address/f1727w2vwjctfo7hflr5trgqkl3c7texh7pl4grzq) | [GMverse](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/365)                                   |           470.44 TiB |       4,598 | LDN v3 multisig |
| [f1ki4cjk27ypzjsuzkvvqzs6xobaweuoxfdcnpqhy](https://filfox.info/en/address/f1ki4cjk27ypzjsuzkvvqzs6xobaweuoxfdcnpqhy) | [TimeQuant](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/385)                                 |           356.00 TiB |       4,960 | LDN v3 multisig |
| [f1clwd2dooy2cflfilhzeq2ycl544b3heqsiwhjrq](https://filfox.info/en/address/f1clwd2dooy2cflfilhzeq2ycl544b3heqsiwhjrq) | [FiboAI](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/349)                                    |           284.81 TiB |       3,112 | LDN v3 multisig |
| [f1ivsvpljx4ovp2tth73pllkxmumrudemks623iia](https://filfox.info/en/address/f1ivsvpljx4ovp2tth73pllkxmumrudemks623iia) | `TIS Inc. group`                                                                                                         |           266.25 TiB |       1,452 | LDN v3 multisig |
| [f1ajdk7e6ex7fvtjtydzgys47bcg7jub2baucun7y](https://filfox.info/en/address/f1ajdk7e6ex7fvtjtydzgys47bcg7jub2baucun7y) | [Ruikuyun Information Technology Co\., Ltd](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/529) |           247.75 TiB |       2,890 | LDN v3 multisig |
| [f1f5edx6ofn3lf6rk3yfpldbi2pzgq2egoyu6ubpi](https://filfox.info/en/address/f1f5edx6ofn3lf6rk3yfpldbi2pzgq2egoyu6ubpi) | [Samdata Trade](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/382)                             |           177.75 TiB |       2,337 | LDN v3 multisig |
| [f1smfrznoqsp7eptqnselnosng7vxuo3ptnoqv2oa](https://filfox.info/en/address/f1smfrznoqsp7eptqnselnosng7vxuo3ptnoqv2oa) | [CTG Business Service](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/306)                      |           135.78 TiB |       1,166 | LDN v3 multisig |
| [f1dx7ljly4vmk5x2bn5ng4jpbqnuvozrz2phw42qy](https://filfox.info/en/address/f1dx7ljly4vmk5x2bn5ng4jpbqnuvozrz2phw42qy) | [CoinPhD](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/364)                                   |           120.38 TiB |       1,484 | LDN v3 multisig |
| [f1quofpadzcqlonmz7v3mv7dfqvm5hdztucdsjqsy](https://filfox.info/en/address/f1quofpadzcqlonmz7v3mv7dfqvm5hdztucdsjqsy) | [HENAN 863 SOFTWARE CO\., LTD](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/468)              |            88.19 TiB |       1,458 | LDN v3 multisig |
| [f1rnwp6p5kx7pcwexpucoav6mmwz3rkxw5blrboyy](https://filfox.info/en/address/f1rnwp6p5kx7pcwexpucoav6mmwz3rkxw5blrboyy) | [MigoVideo](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/517)                                 |            79.66 TiB |         913 | LDN v3 multisig |
| [f1dwhevm3p2slu6itmkssznscmpkpltdiztprnpya](https://filfox.info/en/address/f1dwhevm3p2slu6itmkssznscmpkpltdiztprnpya) | [Hiscene](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/548)                                   |            63.00 TiB |         927 | LDN v3 multisig |
| [f1vtcetpapwwyka6txwqjwymsa67npdfilbkwh64a](https://filfox.info/en/address/f1vtcetpapwwyka6txwqjwymsa67npdfilbkwh64a) | [Chimay](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/397)                                    |            48.28 TiB |         939 | LDN v3 multisig |
| [f1ffbtksiso5za73pypuxbxznng6rdv64nbihdtba](https://filfox.info/en/address/f1ffbtksiso5za73pypuxbxznng6rdv64nbihdtba) | [EpikProtocol](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/281)                              |            43.88 TiB |         686 |       LDN # 281 |
| [f1nmhjvibl7acp45lpxmo5kduz42evjazsyi4mzza](https://filfox.info/en/address/f1nmhjvibl7acp45lpxmo5kduz42evjazsyi4mzza) | `ubuckvnockai`                                                                                                           |            43.84 TiB |         591 | LDN v3 multisig |
| [f1avhqgmeazxzvylz34l26o3nlj2ywnzaviwns3dq](https://filfox.info/en/address/f1avhqgmeazxzvylz34l26o3nlj2ywnzaviwns3dq) | [87v5\-CarsonVideo](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/392)                         |            29.19 TiB |         381 | LDN v3 multisig |
| [f1zb6pgkktdbyy7zxfob6gripqxuc25ukf35cc7fq](https://filfox.info/en/address/f1zb6pgkktdbyy7zxfob6gripqxuc25ukf35cc7fq) | `Maxpic PhotoGraphic Studio`                                                                                             |            19.19 TiB |         317 | LDN v3 multisig |
| [f1einobkrjcjk6gfc5ov6663vrri75hwdsjfs6pmq](https://filfox.info/en/address/f1einobkrjcjk6gfc5ov6663vrri75hwdsjfs6pmq) | [Cansoti](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/640)                                   |            15.66 TiB |         200 | LDN v3 multisig |
| [f1qjrlejxv5a73kxurwtxyrni6ji7orm74zeeetiy](https://filfox.info/en/address/f1qjrlejxv5a73kxurwtxyrni6ji7orm74zeeetiy) | [Mooc](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/223)                                      |             6.81 TiB |         125 | LDN v3 multisig |
| [f14abwn2goturifmt27s2bssoe3fup2b3npkgfzui](https://filfox.info/en/address/f14abwn2goturifmt27s2bssoe3fup2b3npkgfzui) | [KONGFU VR](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/372)                                 |             5.63 TiB |         130 | LDN v3 multisig |
| [f1bb2z36lpq3pnwiiowiraagpzqnpow4bonjacx7a](https://filfox.info/en/address/f1bb2z36lpq3pnwiiowiraagpzqnpow4bonjacx7a) | [Hola Space](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/362)                                |             2.63 TiB |          30 | LDN v3 multisig |
| [f1tivtdkq34mnfzso63wrr2xh6r2zo7aebao4jfla](https://filfox.info/en/address/f1tivtdkq34mnfzso63wrr2xh6r2zo7aebao4jfla) | `China travel service(HongKong) limited`                                                                                 |             1.22 TiB |          16 | LDN v3 multisig |
| [f1zav4f4rak2yvbrq357z3whj224wn4dipl7eiesy](https://filfox.info/en/address/f1zav4f4rak2yvbrq357z3whj224wn4dipl7eiesy) | [Shanghai Zhixun](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/628)                           |           704.00 GiB |           3 | LDN v3 multisig |

[^1]: To manually trigger this report, add a comment with text `checker:manualTrigger`
