### ISSUE TITLE
[DataCap Allocation] - for movie store

### ISSUE THREAD

**Issue by fcdv1** [filecoin-project/filecoin-plus-large-datasets#428]
---
name: Large Dataset Notary application
about: Clients should use this application form to request a DataCap allocation via a LDN for a dataset
title: "for movie store"
labels: 'application, Phase: Diligence'
assignees: ''

---
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: gk104
- Website / Social Media: zfh245185601@gmail.com
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 500TiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 1TiB
- On-chain address for first allocation: f1fr6huajjwmeoyfg6gtmdteyeijk2wwu5z6a7jgq
- Region: Greater China Region

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
save old movie to the ipfs
```

What is the primary source of funding for this project?
```
user donate
```

What other projects/ecosystem stakeholders is this project associated with?
```
pt site usage
```

## Use-case details

Describe the data being stored onto Filecoin
```
some old movie i saved
```

Where was the data in this dataset sourced from?
```
net download
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
no link yet
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
yes
```

What is the expected retrieval frequency for this data?
```
once a week
```

For how long do you plan to keep this dataset stored on Filecoin?
```
I want to keep this dataset forever, or 540 days
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
china
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
hard disk transfer
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
cheap, magisterial storage providers
```

How will you be distributing deals across storage providers?
```
for save reason, need at least three storage providers needed
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
yes,no support need yet
```

**Comment by Sunnyiscoming** [comment]
@fcdv1 
1. Can you provide data use authorization certificate?
2. Please provide specific data samples.
3. You are advised to find appropriate storage service providers at first, which support data retrieval, meet the requirement fragmentation, etc.

**Comment by Sunnyiscoming** [comment]
Any update here?

**Comment by dkkapur** [comment]
Closing this out for now since there was no response to the above questions. Please open up a new application if still relevant.
