### ISSUE TITLE
[DataCap Application] Yuepass Technology

### ISSUE THREAD

**Issue by Japg879** [filecoin-project/filecoin-plus-large-datasets#429]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Yuepass Technology Company Limited
- Website / Social Media:https://www.yuepass.com/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 200TiB
- On-chain address for first allocation: f1ugo3abkmmb4pb2atxz5oqqgwsd27b4p6k52f2va

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Yuepass meets the needs of training exams in different scenarios, and creates a tailor-made training exam system for enterprise informationization. It provides a vast database of shared questions for enterprise users and supports the demand for multi-question and multi-mode exams. Yuepass also features live audio and video teaching to help enterprises with online training, providing a huge amount of original high-quality courses for enterprises to utilize. Moreover, the platform can also help enterprises quickly build exclusive online schools, which saves R&D and time costs for enterprises.
```

What is the primary source of funding for this project?
```
From income of Yuepass.
```

What other projects/ecosystem stakeholders is this project associated with?
```
No.
```

## Use-case details

Describe the data being stored onto Filecoin
```
Live lesson videos and PPT/Word/PDF/PNG of coursewares.
```

Where was the data in this dataset sourced from?
```
Yuepass provide courses to users. Users also can upload courses into the platform.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
[data for yuepass.zip](https://github.com/filecoin-project/filecoin-plus-large-datasets/files/8959986/data.for.yuepass.zip)
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes, I confirm.
```

What is the expected retrieval frequency for this data?
```
It will be retrieved every 1-2 years.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
Long-term storage.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Around Asia.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Yes, we choose offline data transfer process. We have disks for it.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
Slack and Github are good platforms for us connecting with storage providers.We plan choosing 5 storage providers at first.
```

How will you be distributing deals across storage providers?
```
Following community rule, every sp will be distributed below 25% of whole deals. We'll pay attention to it.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes. We don't need support for the moment.
```

**Comment by UnionLabs2020** [comment]
Hey@Japg879, could you send an email to filplus@fil.org with your official domain in order to confirm your identity?

**Comment by Sunnyiscoming** [comment]
@Japg879 
1. According to WHOIS query results, the website is registered by Xin Net Technology Corporation.
Registrar name: Xin Net Technology Corporation(https://www.xinnet.com/)
https://whois.whoisxmlapi.com/lookup-report/JB20jZMLkm

There is no relevant result after querying Yuepass Technologies Company Limited. Can you provide proof of the organization's existence? 

2. Can you provide more data samples to prove that you have 5P data already? And you can provide more cooperation cases and database page.

**Comment by Japg879** [comment]
@UnionLabs2020 ok. This is the email.
![Yuepass1](https://user-images.githubusercontent.com/106439727/177152862-72eea671-e508-4178-a3d7-4648a363dcd7.png)

@Sunnyiscoming Xin Net is providing domain name registration services and we registered our domin name on it.

Dataset you need: [Data.zip](https://github.com/filecoin-project/filecoin-plus-large-datasets/files/9039324/Data.zip)

**Comment by Sunnyiscoming** [comment]
There is no relevant result after querying Yuepass Technologies Company Limited. Can you provide proof of the organization's existence?
Can you explain about that?

**Comment by galen-mcandrew** [comment]
## Datacap Request Trigger
#### Total DataCap requested 
> 5PiB
#### Expected weekly DataCap usage rate 
> 200TiB 
#### Client address
> f1ugo3abkmmb4pb2atxz5oqqgwsd27b4p6k52f2va

**Comment by swatchliu** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedmz3ipvodpeck7nwipngvwi2awnzqnnezqgb56ggnlrl5abdrm3c 
#### Address 
> f1ugo3abkmmb4pb2atxz5oqqgwsd27b4p6k52f2va
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1yh6q3nmsg7i2sys7f7dexcuajgoweudcqj2chfi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedmz3ipvodpeck7nwipngvwi2awnzqnnezqgb56ggnlrl5abdrm3c

**Comment by MetaWaveInfo** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceatbupbfll666uaw32bpvkxvwy225rv6ucedhmhk25u4h5bwtzzgi 
#### Address 
> f1ugo3abkmmb4pb2atxz5oqqgwsd27b4p6k52f2va
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1ktlkcxnmzxcdaoqfsunrg3vocfbmgv4n3mrn74a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceatbupbfll666uaw32bpvkxvwy225rv6ucedhmhk25u4h5bwtzzgi

**Comment by UnionLabs2022** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecvixymkhgiv3zxogr7wnohmsdzveoogve65yxenll66bhtxidndk 
#### Address 
> f1ugo3abkmmb4pb2atxz5oqqgwsd27b4p6k52f2va
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f17xdri3wunqgld7dm23e4f3eqsntjakwc47xjo6i
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecvixymkhgiv3zxogr7wnohmsdzveoogve65yxenll66bhtxidndk

**Comment by wuyang158158** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced4hjz3kzxmqwgw4xzkw5fgteuq6rqlzl276ctcgxfwr33t22xbc6 
#### Address 
> f1ugo3abkmmb4pb2atxz5oqqgwsd27b4p6k52f2va
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1j4n74chme7whbz3yls4a7ixqewb6dijypqg2a3a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced4hjz3kzxmqwgw4xzkw5fgteuq6rqlzl276ctcgxfwr33t22xbc6

**Comment by ipfscn** [comment]
# Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
Message sent to Filecoin Network
>  bafy2bzaced4hjz3kzxmqwgw4xzkw5fgteuq6rqlzl276ctcgxfwr33t22xbc6

Address
> f1ugo3abkmmb4pb2atxz5oqqgwsd27b4p6k52f2va

Datacap Allocated
> 200.00TiB

Signer Address
> f1j4n74chme7whbz3yls4a7ixqewb6dijypqg2a3a

You can check the status of the message here: [https://filfox.info/en/message/bafy2bzaced4hjz3kzxmqwgw4xzkw5fgteuq6rqlzl276ctcgxfwr33t22xbc6]

**Comment by ipfscn** [comment]
# Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
Message sent to Filecoin Network
>  bafy2bzaced4hjz3kzxmqwgw4xzkw5fgteuq6rqlzl276ctcgxfwr33t22xbc6

Address
> f1ugo3abkmmb4pb2atxz5oqqgwsd27b4p6k52f2va

Datacap Allocated
> 200.00TiB

Signer Address
> f1j4n74chme7whbz3yls4a7ixqewb6dijypqg2a3a

You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced4hjz3kzxmqwgw4xzkw5fgteuq6rqlzl276ctcgxfwr33t22xbc6

**Comment by ipfscn** [comment]
# Request Proposed
Your Datacap Allocation Request has been proposed by the Notary

Message sent to Filecoin Network
>  bafy2bzaced4hjz3kzxmqwgw4xzkw5fgteuq6rqlzl276ctcgxfwr33t22xbc6

Address
> f1ugo3abkmmb4pb2atxz5oqqgwsd27b4p6k52f2va

Datacap Allocated
> 200.00TiB

Signer Address
> f1j4n74chme7whbz3yls4a7ixqewb6dijypqg2a3a

You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced4hjz3kzxmqwgw4xzkw5fgteuq6rqlzl276ctcgxfwr33t22xbc6

**Comment by ipfscn** [comment]
**Request Approved**

Your Datacap Allocation Request has been proposed by the Notary

Message sent to Filecoin Network

`bafy2bzaced4hjz3kzxmqwgw4xzkw5fgteuq6rqlzl276ctcgxfwr33t22xbc6`

Address

`f1ugo3abkmmb4pb2atxz5oqqgwsd27b4p6k52f2va`

Datacap Allocated

`200.00TiB`

Signer Address

`f1j4n74chme7whbz3yls4a7ixqewb6dijypqg2a3a`

You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced4hjz3kzxmqwgw4xzkw5fgteuq6rqlzl276ctcgxfwr33t22xbc6

**Comment by ipfscn** [comment]
#Request Approved

Your Datacap Allocation Request has been proposed by the Notary
Message sent to Filecoin Network
>  bafy2bzaced4hjz3kzxmqwgw4xzkw5fgteuq6rqlzl276ctcgxfwr33t22xbc6

Address
> f1ugo3abkmmb4pb2atxz5oqqgwsd27b4p6k52f2va

Datacap Allocated
> 200.00TiB

Signer Address
> f1j4n74chme7whbz3yls4a7ixqewb6dijypqg2a3a

You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced4hjz3kzxmqwgw4xzkw5fgteuq6rqlzl276ctcgxfwr33t22xbc6

**Comment by ipfscn** [comment]
# Request Approved

Your Datacap Allocation Request has been proposed by the Notary

Message sent to Filecoin Network
>  bafy2bzaced4hjz3kzxmqwgw4xzkw5fgteuq6rqlzl276ctcgxfwr33t22xbc6

Address
> f1ugo3abkmmb4pb2atxz5oqqgwsd27b4p6k52f2va

Datacap Allocated
> 200.00TiB

Signer Address
> f1j4n74chme7whbz3yls4a7ixqewb6dijypqg2a3a

You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced4hjz3kzxmqwgw4xzkw5fgteuq6rqlzl276ctcgxfwr33t22xbc6

**Comment by BigD-Exchange** [comment]
@Japg879 Hi! Great to see you have gotten approval for DataCap. If you are looking for storage providers to store these data or have any questions, please visit #bigdata-exchange on Filecoin Slack or reply here. 

We have strong demand from a diverse group of SPs, who are actively looking to onboard more data.

**Comment by stcouldlisa** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecdppfu6txj3piuws4zjp7ybcgjccacdlghmcf4qsiduh5okwu64q 
#### Address 
> f1ugo3abkmmb4pb2atxz5oqqgwsd27b4p6k52f2va
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1jvvltduw35u6inn5tr4nfualyd42bh3vjtylgci
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecdppfu6txj3piuws4zjp7ybcgjccacdlghmcf4qsiduh5okwu64q

**Comment by swatchliu** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecir7e3tav2fmgmsytnxm6haqz6eqc2sstplrrfenbhu4oljcma36 
#### Address 
> f1ugo3abkmmb4pb2atxz5oqqgwsd27b4p6k52f2va
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1yh6q3nmsg7i2sys7f7dexcuajgoweudcqj2chfi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecir7e3tav2fmgmsytnxm6haqz6eqc2sstplrrfenbhu4oljcma36

**Comment by MetaWaveInfo** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecw545eog3am52vknojjqgixttey7bitznmxo4opx5dswe53zhoto 
#### Address 
> f1ugo3abkmmb4pb2atxz5oqqgwsd27b4p6k52f2va
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1ktlkcxnmzxcdaoqfsunrg3vocfbmgv4n3mrn74a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecw545eog3am52vknojjqgixttey7bitznmxo4opx5dswe53zhoto

**Comment by Fenbushi-Filecoin** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedltjcuesxpylo32zp3rlgtua2ibnrhwxsck74osn5z5sadwgsmgs 
#### Address 
> f1ugo3abkmmb4pb2atxz5oqqgwsd27b4p6k52f2va
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1yqydpmqb5en262jpottko2kd65msajax7fi4rmq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedltjcuesxpylo32zp3rlgtua2ibnrhwxsck74osn5z5sadwgsmgs

**Comment by UnionLabs2020** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaw6dlphk6sj4sebyjorn6xyjblvkto3q5xtwqyq4aj6sgsi2buu4 
#### Address 
> f1ugo3abkmmb4pb2atxz5oqqgwsd27b4p6k52f2va
#### Datacap Allocated
> 1.56PiB
#### Signer Address
> f17xdri3wunqgld7dm23e4f3eqsntjakwc47xjo6i
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaw6dlphk6sj4sebyjorn6xyjblvkto3q5xtwqyq4aj6sgsi2buu4

**Comment by liyunzhi-666** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebkvvg44cm76mkugl7hyrthvoqddtvb4kxzz7fmb7yqk2nldva7lq 
#### Address 
> f1ugo3abkmmb4pb2atxz5oqqgwsd27b4p6k52f2va
#### Datacap Allocated
> 1.56PiB
#### Signer Address
> f1pszcrsciyixyuxxukkvtazcokexbn54amf7gvoq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebkvvg44cm76mkugl7hyrthvoqddtvb4kxzz7fmb7yqk2nldva7lq

**Comment by filplus-checker** [comment]
## DataCap and CID Checker Report[^1]
 - Organization: `Yuepass Technology Company Limited`
 - Client: `f1ugo3abkmmb4pb2atxz5oqqgwsd27b4p6k52f2va`
### Storage Provider Distribution
The below table shows the distribution of storage providers that have stored data for this client.

If this is the first time a provider takes verified deal, it will be marked as `new`.

For most of the datacap application, below restrictions should apply.
 - Storage provider should not exceed 25% of total datacap.
 - Storage provider should not be storing duplicate data for more than 20%.
 - Storage provider should have published its public IP address.
 - All storage providers should be located in different regions.

⚠️ 89.83% of total deal sealed by [f01933849](https://filfox.info/en/address/f01933849) are duplicate data.

⚠️ [f01933849](https://filfox.info/en/address/f01933849) has unknown IP location.

⚠️ 78.73% of total deal sealed by [f01926749](https://filfox.info/en/address/f01926749) are duplicate data.

⚠️ [f01926749](https://filfox.info/en/address/f01926749) has unknown IP location.

⚠️ 75.81% of total deal sealed by [f01926777](https://filfox.info/en/address/f01926777) are duplicate data.

⚠️ [f01926777](https://filfox.info/en/address/f01926777) has unknown IP location.

⚠️ 79.00% of total deal sealed by [f01926768](https://filfox.info/en/address/f01926768) are duplicate data.

⚠️ [f01926768](https://filfox.info/en/address/f01926768) has unknown IP location.

⚠️ 89.77% of total deal sealed by [f01878693](https://filfox.info/en/address/f01878693) are duplicate data.

⚠️ [f01878693](https://filfox.info/en/address/f01878693) has unknown IP location.

⚠️ 79.97% of total deal sealed by [f01688](https://filfox.info/en/address/f01688) are duplicate data.

⚠️ [f01688](https://filfox.info/en/address/f01688) has unknown IP location.

⚠️ 64.07% of total deal sealed by [f01843749](https://filfox.info/en/address/f01843749) are duplicate data.

⚠️ 58.81% of total deal sealed by [f054464](https://filfox.info/en/address/f054464) are duplicate data.

⚠️ 69.45% of total deal sealed by [f01841133](https://filfox.info/en/address/f01841133) are duplicate data.

⚠️ 73.41% of total deal sealed by [f01841131](https://filfox.info/en/address/f01841131) are duplicate data.

⚠️ 63.54% of total deal sealed by [f01877862](https://filfox.info/en/address/f01877862) are duplicate data.

⚠️ 74.54% of total deal sealed by [f01927578](https://filfox.info/en/address/f01927578) are duplicate data.

⚠️ [f01927578](https://filfox.info/en/address/f01927578) has unknown IP location.

⚠️ 77.04% of total deal sealed by [f0103710](https://filfox.info/en/address/f0103710) are duplicate data.

⚠️ [f0103710](https://filfox.info/en/address/f0103710) has unknown IP location.

⚠️ 82.93% of total deal sealed by [f0136399](https://filfox.info/en/address/f0136399) are duplicate data.

⚠️ 59.93% of total deal sealed by [f01392600](https://filfox.info/en/address/f01392600) are duplicate data.

⚠️ 87.50% of total deal sealed by [f01520](https://filfox.info/en/address/f01520) are duplicate data.

⚠️ [f01520](https://filfox.info/en/address/f01520) has unknown IP location.

| Provider                                                    |                           Location | Total Deals Sealed | Percentage | Unique Data | Duplicate Deals |
| :---------------------------------------------------------- | ---------------------------------: | -----------------: | ---------: | ----------: | --------------: |
| [f01933849](https://filfox.info/en/address/f01933849)       |                            Unknown |         362.88 TiB |     24.67% |   36.91 TiB |          89.83% |
| [f01926749](https://filfox.info/en/address/f01926749)`new`  |                            Unknown |         229.94 TiB |     15.63% |   48.91 TiB |          78.73% |
| [f01926777](https://filfox.info/en/address/f01926777)`new`  |                            Unknown |         228.41 TiB |     15.53% |   55.25 TiB |          75.81% |
| [f01926768](https://filfox.info/en/address/f01926768)`new`  |                            Unknown |         114.31 TiB |      7.77% |   24.00 TiB |          79.00% |
| [f01878693](https://filfox.info/en/address/f01878693)       |                            Unknown |         111.22 TiB |      7.56% |   11.38 TiB |          89.77% |
| [f01688](https://filfox.info/en/address/f01688)             |                            Unknown |         100.00 TiB |      6.80% |   20.03 TiB |          79.97% |
| [f01843749](https://filfox.info/en/address/f01843749)       | Hong Kong, Central and Western, HK |          65.75 TiB |      4.47% |   23.63 TiB |          64.07% |
| [f054464](https://filfox.info/en/address/f054464)           | Hong Kong, Central and Western, HK |          49.84 TiB |      3.39% |   20.53 TiB |          58.81% |
| [f01841133](https://filfox.info/en/address/f01841133)       |           Singapore, Singapore, SG |          49.09 TiB |      3.34% |   15.00 TiB |          69.45% |
| [f01841131](https://filfox.info/en/address/f01841131)       | Hong Kong, Central and Western, HK |          49.00 TiB |      3.33% |   13.03 TiB |          73.41% |
| [f01877862](https://filfox.info/en/address/f01877862)       |                   Seoul, Seoul, KR |          30.00 TiB |      2.04% |   10.94 TiB |          63.54% |
| [f01927578](https://filfox.info/en/address/f01927578)       |                            Unknown |          25.66 TiB |      1.74% |    6.53 TiB |          74.54% |
| [f0103710](https://filfox.info/en/address/f0103710)         |                            Unknown |          17.97 TiB |      1.22% |    4.13 TiB |          77.04% |
| [f0136399](https://filfox.info/en/address/f0136399)         | Hong Kong, Central and Western, HK |          17.94 TiB |      1.22% |    3.06 TiB |          82.93% |
| [f01392600](https://filfox.info/en/address/f01392600)       | Hong Kong, Central and Western, HK |          17.00 TiB |      1.16% |    6.81 TiB |          59.93% |
| [f01520](https://filfox.info/en/address/f01520)`new`        |                            Unknown |           2.00 TiB |      0.14% |  256.00 GiB |          87.50% |

![Provider Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/429/1671096908849.png)
### Deal Data Replication
The below table shows how each many unique data are replicated across storage providers.
- No more than 25% of unique data are stored with less than 4 providers.

⚠️ 96.27% of deals are for data replicated across less than 4 storage providers.

| Unique Data Size | Total Deals Made | Number of Providers | Deal Percentage |
| ---------------: | ---------------: | ------------------: | --------------: |
|       191.03 TiB |         1.04 PiB |                   1 |          72.50% |
|        24.44 TiB |       223.28 TiB |                   2 |          15.18% |
|        12.78 TiB |       126.44 TiB |                   3 |           8.60% |
|         5.53 TiB |        54.88 TiB |                   4 |           3.73% |

![Replication Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/429/1671096909655.png)
### Deal Data Shared with other Clients
The below table shows how many unique data are shared with other clients.
Usually different applications owns different data and should not resolve to the same CID.

⚠️ CID sharing has been observed.

| Other Client                                                                                                                                                                                                              | Application                                                                                                               | Total Deals Affected | Unique CIDs |        Verifier |
| :------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ | :------------------------------------------------------------------------------------------------------------------------ | -------------------: | ----------: | --------------: |
| [f1znd7uramgqquelcgefo5xgozopd3nga73hhywpy](https://filfox.info/en/address/f1znd7uramgqquelcgefo5xgozopd3nga73hhywpy)                                                                                                     | [BotSmart ](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/373)                                  |           199.41 TiB |       1,031 | LDN v3 multisig |
| [f1rkmhotssjif6ucrosls7oewjz6pr2v2eygfjyui](https://filfox.info/en/address/f1rkmhotssjif6ucrosls7oewjz6pr2v2eygfjyui)                                                                                                     | `Weipaitang`                                                                                                              |           180.03 TiB |       1,370 | LDN v3 multisig |
| [f127l5waa4pw6k3sm4e7wxevc4fe5uz7dyt4mxa3i](https://filfox.info/en/address/f127l5waa4pw6k3sm4e7wxevc4fe5uz7dyt4mxa3i)                                                                                                     | `Pangod`                                                                                                                  |            87.25 TiB |         569 | LDN v3 multisig |
| [f1vbe7ze5yknpgu3orinv4zu4rkofsyqfsmpejpui](https://filfox.info/en/address/f1vbe7ze5yknpgu3orinv4zu4rkofsyqfsmpejpui)                                                                                                     | [HELIOS](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/305)                                     |            83.38 TiB |         698 | LDN v3 multisig |
| [f162jayw3utjlbp5ae6ssqghm5jrl3js32dbmnfja](https://filfox.info/en/address/f162jayw3utjlbp5ae6ssqghm5jrl3js32dbmnfja)                                                                                                     | ``                                                                                                                        |            71.59 TiB |         474 |       LDN # 121 |
| [f1wr6rwwqckh6um2hynaym2t4mniev5b675kbf5ni](https://filfox.info/en/address/f1wr6rwwqckh6um2hynaym2t4mniev5b675kbf5ni)                                                                                                     | [Ctrip Global Shopping](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/303)                      |            67.19 TiB |         482 | LDN v3 multisig |
| [f1xwmnlen7j7qlkktm3oqggzcbrxp6cvqnkd2wipa](https://filfox.info/en/address/f1xwmnlen7j7qlkktm3oqggzcbrxp6cvqnkd2wipa)                                                                                                     | ``                                                                                                                        |            49.58 TiB |         320 |       LDN # 121 |
| [f1cf2pp6bgu6vvxfuau6bsmiibhrc7v3gvjsyseay](https://filfox.info/en/address/f1cf2pp6bgu6vvxfuau6bsmiibhrc7v3gvjsyseay)                                                                                                     | [Public Data\-FlyBrain](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1013)                     |            46.06 TiB |         285 | LDN v3 multisig |
| [f1csetl7nor3qie2cehx7axf2ai3nedmowj53xwsa](https://filfox.info/en/address/f1csetl7nor3qie2cehx7axf2ai3nedmowj53xwsa)                                                                                                     | [NOAA GOES\-\-\-Piero](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1112)                      |            45.38 TiB |         334 | LDN v3 multisig |
| [f1ibuglt2lzlyf7vnmtzmuykcfgl2pn2fxym5dibi](https://filfox.info/en/address/f1ibuglt2lzlyf7vnmtzmuykcfgl2pn2fxym5dibi)                                                                                                     | [Appstest](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/346)                                   |            43.84 TiB |         317 | LDN v3 multisig |
| [f1quofpadzcqlonmz7v3mv7dfqvm5hdztucdsjqsy](https://filfox.info/en/address/f1quofpadzcqlonmz7v3mv7dfqvm5hdztucdsjqsy)                                                                                                     | [HENAN 863 SOFTWARE CO\., LTD](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/468)               |            38.25 TiB |         113 | LDN v3 multisig |
| [f1fq6abg47ifgeee2z7q2rps3tvknoo2ztcoqy7ai](https://filfox.info/en/address/f1fq6abg47ifgeee2z7q2rps3tvknoo2ztcoqy7ai)                                                                                                     | [DaYe Art Tuition Class \(DKArt\) ](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/888)          |            34.81 TiB |         188 | LDN v3 multisig |
| [f1bb2z36lpq3pnwiiowiraagpzqnpow4bonjacx7a](https://filfox.info/en/address/f1bb2z36lpq3pnwiiowiraagpzqnpow4bonjacx7a)                                                                                                     | [Hola Space](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/362)                                 |            27.81 TiB |          89 | LDN v3 multisig |
| [f1tgii4xgcp6um4n2w7eqaw6bwvnvyii2u7cjgzka](https://filfox.info/en/address/f1tgii4xgcp6um4n2w7eqaw6bwvnvyii2u7cjgzka)                                                                                                     | [Meson\.Network ](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/187)                            |            23.00 TiB |         235 | LDN v3 multisig |
| [f1a2rdwwor3kq6mv7nveuxhux7rxtj6iyjs7hfswa](https://filfox.info/en/address/f1a2rdwwor3kq6mv7nveuxhux7rxtj6iyjs7hfswa)                                                                                                     | [Worldkan](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/902)                                   |            19.94 TiB |         136 | LDN v3 multisig |
| [f1vykg3elgzoa3lpzf5xo6rbcghzr5ifat757mucq](https://filfox.info/en/address/f1vykg3elgzoa3lpzf5xo6rbcghzr5ifat757mucq)                                                                                                     | [Hailiang Mingyou Online](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/51)                     |            16.78 TiB |         125 |        LDN # 51 |
| [f1qnhjr2kq742poi6rukv5hji5rdrtuqsib7khz3a](https://filfox.info/en/address/f1qnhjr2kq742poi6rukv5hji5rdrtuqsib7khz3a)                                                                                                     | [GLOBAL UNIT\-A Corp\.](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/110)                      |             2.53 TiB |          84 |       LDN # 110 |
| [f3wtdob5ymm5qy3t6w2ggk3bb4niq25e3zaolvzhr<br/>kzc2fkphrrvrsqau74qvhwncghqoutg6lztjqyrsn<br/>lysa](https://filfox.info/en/address/f3wtdob5ymm5qy3t6w2ggk3bb4niq25e3zaolvzhrkzc2fkphrrvrsqau74qvhwncghqoutg6lztjqyrsnlysa) | [Hunan jinyiyun Storage Technology Co\.](https://github.com/filecoin-project/filecoin-plus-client-onboarding/issues/1327) |             1.56 TiB |          10 |       Steven Li |
| [f3rncwz3qo2bwnsrfjc7kq53xr7yi2lctcydtllxo<br/>zmszndvttou7n565yb6aqssvn4omyf5m7q62qpfmq<br/>cbwq](https://filfox.info/en/address/f3rncwz3qo2bwnsrfjc7kq53xr7yi2lctcydtllxozmszndvttou7n565yb6aqssvn4omyf5m7q62qpfmqcbwq) | [VillageOne Space LLCVillageOne Space LLC](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/39)    |           144.00 GiB |           5 |        LDN # 39 |
| [f3q7ablez3jqkcjukwbzaql7lmbx4ldouu66nexpd<br/>cfvu6kgho3v6gricckt77cgr46tdre2l4zmvha7bs<br/>u7qq](https://filfox.info/en/address/f3q7ablez3jqkcjukwbzaql7lmbx4ldouu66nexpdcfvu6kgho3v6gricckt77cgr46tdre2l4zmvha7bsu7qq) | `MatrixStorage`                                                                                                           |           144.00 GiB |           4 |        LDN # 72 |
| [f3woqxpu6ekmj43nmpcv7j2pgu6lejxtzgxpzl6f2<br/>vrueoqlzjntakyhdkghymyffbzfbsio6dvfmy643x<br/>4y7q](https://filfox.info/en/address/f3woqxpu6ekmj43nmpcv7j2pgu6lejxtzgxpzl6f2vrueoqlzjntakyhdkghymyffbzfbsio6dvfmy643x4y7q) | [RICH ST PETE LLC](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/64)                            |            96.00 GiB |           2 | LDN v3 multisig |
| [f3skkellc7wegakh2blqeu4kkrlzuqy2siymwli7s<br/>ec6eq77c2v4kzgz5ozgnasjl5r52ckameba5kds7h<br/>djda](https://filfox.info/en/address/f3skkellc7wegakh2blqeu4kkrlzuqy2siymwli7sec6eq77c2v4kzgz5ozgnasjl5r52ckameba5kds7hdjda) | [Meizhai Technology](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/75)                          |            64.00 GiB |           2 | LDN v3 multisig |

[^1]: To manually trigger this report, add a comment with text `checker:manualTrigger`
