### ISSUE TITLE
[DataCap Application] - Spexi Geospatial Inc

### ISSUE THREAD

**Issue by peteszym** [filecoin-project/filecoin-plus-large-datasets#431]
# Large Dataset Notary Application
To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Spexi Geospatial Inc
- Website / Social Media: spexigeo.com
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5 PiB
-Weekly allocation of DataCap requested (usually between 1-100TiB): 100 TiB
-On-chain address for first allocation: f122pvhsfze6gglnuwhttijfkwvwar43onahs5jia
- Type: Custom Notary

## Project details
Share a brief history of your project and organization
```
We are building the most engaged drone pilot community and aerial data ecosystem. We currently operate a drone collaboration system that empowers organizations to collect drone-based data for their own projects. We will be expanding our network and covering much larger territories which will create much larger datasets on a continual basis.
```

What is the primary source of funding for this project?
```
Self-financed to date (bootstrapped). Currently seeking external funding through investment partners.
```

What other projects/ecosystem stakeholders is this project associated with?
```
Currently we have over 700 users actively using the Spexi platform from various industry segments. In the next phase of our strategy, a community-driven collection effort will be maintained to bring in data from every corner of the earth (mostly urban areas). Stakeholders will be the drone pilots, and the end users of the data.
```

## Use-case details
Describe the data being stored onto Filecoin
```
Images and 3D point clouds/3D meshes. Imagery collected from the drones will be the prime datasource that will be stored. The imagery will be approximately 3cm GSD (ground sample distance), and in various forms; 1) raw data collected from the drone 2) processed orthorectified and mosaicked tiles, and 3) 360 panoramic images. The 3D point cloud as well as 3D meshes will be in object tiles in manageable sizes.
```

Where was the data in this dataset sourced from?
```
Currently from project stakeholders/users. However, filecoin will be used in the community collection program that Spexi is rolling out. The data will be collected by decentralized drone pilots and processed/stored/served by Spexi through its platform.
```

Can you share a sample of the data? A link to file would work.
```
https://projects.spexigeo.com/285-65b-st/panorama?skipIntro=true (use icons on bottom left to see view output products)
```

Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Data will be publicly retrievable but encrypted 
```

What is the expected retrieval frequency for this data?
```
Our current expectation is that Filecoin will be used as “cold” storage for archival and less frequently data availability needs.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
Our current best guess is a rolling basis for a minimum of 3 years. Parts of the data may be purged and only selected datasets may be kept in perpetuity
```

## DataCap allocation plan
In which geographies (countries, regions) do you plan on making storage deals?
```
Canada, USA, Western Europe, Australia
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Online over the internet
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
Reputable storage providers in Canada, USA, Western Europe and Australia

```

How will you be distributing deals across storage providers?
```
Hosting files online where it is accessible for the storage providers to enter and download.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?

```
Yes. Not additional support needed
```

**Comment by Kevin-PiKNiK** [comment]
Hi @peteszym . Great pleasure meeting your team in Austin. The Filecoin community is excited to work with you!

**Comment by peteszym** [comment]
Thanks @Kevin-PiKNiK ! The feeling is mutual on our side. 🚀

**Comment by Sunnyiscoming** [comment]
> Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
> 
> Data will be publicly retrievable but encrypted 

As you said, maybe this dataset is more

**Comment by Sunnyiscoming** [comment]
Any updat here?

**Comment by cryptowhizzard** [comment]
This looks like a promising project. Count me in.

**Comment by Sunnyiscoming** [comment]
4 more notaries' approval on the issue are needed.
Any notary will support?

**Comment by Fenbushi-Filecoin** [comment]
We can support the project.

**Comment by raghavrmadya** [comment]
Bumping this to get additional notary support to move forward. Please update any progress here @peteszym

**Comment by raghavrmadya** [comment]
Please update by Friday or we would need to close this @peteszym

**Comment by flyworker** [comment]
The  data privacy  is important in this domain, and I can understand how important it is for the enterprise. I want to support the application if the process is appropate.

**Comment by peteszym** [comment]
We are still waiting on responses from a few more notaries, @raghavrmadya

**Comment by raghavrmadya** [comment]
@peteszym , have you posted in Filcoin Slack to get support?

**Comment by IreneYoung** [comment]
Looks great. Count me in, please

**Comment by Tom-OriginStorage** [comment]
Origin Storage is willing to support this project. As the data is private, we had advise them to follow the private enterprise data request pattern to avoid complications. 

However, at the same time, we also respect the lead notary & client decisions to stick with the current application. We will assist the lead notary & client to handle the tough questions & potential disputes from other notaries & community that may accompany this unorthodox application process.

We believe that the data stored is of value to the Filecoin ecosystem, and is different from the usual camera surveillance data we get from most of the LDNs.

**Comment by peteszym** [comment]
Awesome. Thanks everyone! @raghavrmadya, what are the next steps for us?

**Comment by dkkapur** [comment]
## Datacap Request Trigger
#### Total DataCap requested 
> 5 PiB
#### Expected weekly DataCap usage rate 
> 100 TiB 
#### Client address
> f122pvhsfze6gglnuwhttijfkwvwar43onahs5jia

**Comment by IreneYoung** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec5wegjjsciizzu53kydmnjp6p3kmd2xi3gda62ovpqs4dmkbg5e2 
#### Address 
> f122pvhsfze6gglnuwhttijfkwvwar43onahs5jia
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1d4gmpqz3execjj2wvrxuuhvbms5mzh7t7yqrviq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec5wegjjsciizzu53kydmnjp6p3kmd2xi3gda62ovpqs4dmkbg5e2

**Comment by cryptowhizzard** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceadlkbuzpbtnykmivwblif65uuiwghjadvhegsrto5wyhuwhhv2t4 
#### Address 
> f122pvhsfze6gglnuwhttijfkwvwar43onahs5jia
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1krmypm4uoxxf3g7okrwtrahlmpcph3y7rbqqgfa
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceadlkbuzpbtnykmivwblif65uuiwghjadvhegsrto5wyhuwhhv2t4

**Comment by BigD-Exchange** [comment]
@peteszym Hi! Great to see you have gotten approval for DataCap and advancing the mission of preserving humanity’s most important information. If you are looking for storage providers to store these data or have any questions, please visit #bigdata-exchange on Filecoin Slack or reply here.

**Comment by Sunnyiscoming** [comment]
Are there any problems with using datacap?
