### ISSUE TITLE
[DataCap Application] PiKNiK - NEXRAD Slingshot Dataset 1/4

### ISSUE THREAD

**Issue by jessie8o8** [filecoin-project/filecoin-plus-large-datasets#432]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name:  PiKNiK
- Website / Social Media: piknik.com
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5 PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100 TiB
- On-chain address for first allocation: f13csteap4jcgl3a65qtsvmblzvelp4sgivddtpqa

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details
Share a brief history of your project and organization
```
PiKNiK is the main client for the USC Shoah Foundation and has experience in allocation deals to other SPs. We work to help others learn how to store valuable data by hosting an accelerator program called ESPA. 

This application is the first of the four as the total datacap being asked is of 20 PiBs, thus having to split the datacap application into 4 parts
```

What is the primary source of funding for this project?
```
PiKNiK
```

What other projects/ecosystem stakeholders is this project associated with?
```
Slingshot competition hosted by Protocol Labs
```

## Use-case details
Describe the data being stored onto Filecoin
```
Next Generation Weather Radar is a network of 160 high-resolution S-band Doppler weather radars that detect precipitation and wind patterns and movement.
```

Where was the data in this dataset sourced from?
```
Google Cloud Public Datasets, the Registry of Open Data on AWS, and Azure Open Datasets
```

Can you share a sample of the data? A link to file would work.
```
https://registry.opendata.aws/noaa-nexrad/
```

Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Confirmed
```

What is the expected retrieval frequency for this data?
```
Slingshot retrieval requirements will be followed
```

For how long do you plan to keep this dataset stored on Filecoin?
```
For the duration of Slingshot
```

## DataCap allocation plan
In which geographies (countries, regions) do you plan on making storage deals?
```
Europe, United States, Australia or any other SPs that are interested.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Offline
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
PiKNIK plans to deal with select SPs that are reputable in the community and are reliable such as SPXs, SPs that have prominent presence in the community, SPs that PiKNiK has successfully worked with before or using sites that rank reliability of SPs.
```

How will you be distributing deals across storage providers?
```
Hosting files online where storage providers can download them.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes. Additional support would come from Slingshot support channels in Filecoin Slack if needed.
```

**Comment by jessie8o8** [comment]
The rest of the data cap applications for this dataset: 
[DataCap Application] - PiKNiK - NEXRAD Slingshot Dataset 2/4 #433 
[DataCap Application] - PiKNiK - NEXRAD Slingshot Dataset 3/4 #434 
[DataCap Application] - PiKNiK - NEXRAD Slingshot Dataset 4/4 #435

**Comment by dkkapur** [comment]
## Datacap Request Trigger
#### Total DataCap requested 
> 5 PiB
#### Expected weekly DataCap usage rate 
> 400 TiB 
#### Client address
> f13csteap4jcgl3a65qtsvmblzvelp4sgivddtpqa

**Comment by dkkapur** [comment]
Closing this out for now, please see https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/435#issuecomment-1204718136.

**Comment by dkkapur** [comment]
@jessie8o8 figured out the bug wrt the trigger not working in https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/432. Origin Storage team in Slack flagged that this may be because at the top, the amounts requested are in units "PiBs" and "TiBs" rather than "PiB" and "TiB". 

However - Slingshot v2.8 ended. Are you still planning on storing this dataset outside the scope of Slingshot? 

I'm going to close out the associated issues in the meantime, and let's align on your next steps here and discuss the right course of action accordingly. Thank you.

**Comment by jessie8o8** [comment]
Hi @dkkapur. Thanks for figuring out the bug. Noted for next time!

We still completely intend on storing the NEXRAD data under the slingshot vision as it is still useful data. We understand that the reward period has passed and will still commit to storing without the reward.

**Comment by dkkapur** [comment]
@jessie8o8 ACK - can I request that we close out this application in that case and you open up another one that explicitly calls out your desire to store this as an open dataset regardless of Slingshot?

**Comment by jessie8o8** [comment]
@dkkapur Yes! Please see the new application #571

**Comment by cryptowhizzard** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecprd2ccioihqrvyth4dxai23mbivjzoednc3wsyvhky5t6nlg7fi 
#### Address 
> f13csteap4jcgl3a65qtsvmblzvelp4sgivddtpqa
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1krmypm4uoxxf3g7okrwtrahlmpcph3y7rbqqgfa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecprd2ccioihqrvyth4dxai23mbivjzoednc3wsyvhky5t6nlg7fi

**Comment by kernelogic** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaptqtutsczqtxudvly3lwmjrskalzrql4zdv2s4tfxstpydszfjc 
#### Address 
> f13csteap4jcgl3a65qtsvmblzvelp4sgivddtpqa
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaptqtutsczqtxudvly3lwmjrskalzrql4zdv2s4tfxstpydszfjc

**Comment by filplus-checker** [comment]
## DataCap and CID Checker Report[^1]
 - Organization: ` PiKNiK`
 - Client: `f13csteap4jcgl3a65qtsvmblzvelp4sgivddtpqa`
### Storage Provider Distribution
The below table shows the distribution of storage providers that have stored data for this client.

If this is the first time a provider takes verified deal, it will be marked as `new`.

For most of the datacap application, below restrictions should apply.
 - Storage provider should not exceed 25% of total datacap.
 - Storage provider should not be storing duplicate data for more than 20%.
 - Storage provider should have published its public IP address.
 - All storage providers should be located in different regions.

⚠️ [f01910202](https://filfox.info/en/address/f01910202) has sealed 100.00% of total datacap.

⚠️ All storage providers are located in the same region.

| Provider                                              |                       Location | Total Deals Sealed | Percentage | Unique Data | Duplicate Deals |
| :---------------------------------------------------- | -----------------------------: | -----------------: | ---------: | ----------: | --------------: |
| [f01910202](https://filfox.info/en/address/f01910202) | Philadelphia, Pennsylvania, US |           4.50 TiB |    100.00% |    4.50 TiB |           0.00% |

![Provider Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/432/1671096916319.png)
### Deal Data Replication
The below table shows how each many unique data are replicated across storage providers.
- No more than 25% of unique data are stored with less than 4 providers.

⚠️ 100.00% of deals are for data replicated across less than 4 storage providers.

| Unique Data Size | Total Deals Made | Number of Providers | Deal Percentage |
| ---------------: | ---------------: | ------------------: | --------------: |
|         4.50 TiB |         4.50 TiB |                   1 |         100.00% |

![Replication Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/432/1671096916825.png)
### Deal Data Shared with other Clients
The below table shows how many unique data are shared with other clients.
Usually different applications owns different data and should not resolve to the same CID.

⚠️ CID sharing has been observed.

| Other Client                                                                                                          | Application                                                                                      | Total Deals Affected | Unique CIDs |        Verifier |
| :-------------------------------------------------------------------------------------------------------------------- | :----------------------------------------------------------------------------------------------- | -------------------: | ----------: | --------------: |
| [f1r3d25hl2y7rqlsu2mgczdethy4qqjmkfdlmibfq](https://filfox.info/en/address/f1r3d25hl2y7rqlsu2mgczdethy4qqjmkfdlmibfq) | [ NEXRAD \- FilSwan](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/80) |            13.69 TiB |         149 | LDN v3 multisig |
| [f1bstbq5bi72kyovhh7zoo2f6l6uivsjz4ey5dnqq](https://filfox.info/en/address/f1bstbq5bi72kyovhh7zoo2f6l6uivsjz4ey5dnqq) | [FilSwan](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/917)           |             2.00 TiB |          44 | LDN v3 multisig |
| [f1o54sve7ede7im4caux3ug7lsyjmbue7ss3zzl6y](https://filfox.info/en/address/f1o54sve7ede7im4caux3ug7lsyjmbue7ss3zzl6y) | [FilSwan](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/278)           |           128.00 GiB |           4 | LDN v3 multisig |

[^1]: To manually trigger this report, add a comment with text `checker:manualTrigger`

**Comment by cryptowhizzard** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedxleg2pnw27itdbh46q2av7y32pleku2qg5o3ltdvyju72tw5md2 
#### Address 
> f13csteap4jcgl3a65qtsvmblzvelp4sgivddtpqa
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1krmypm4uoxxf3g7okrwtrahlmpcph3y7rbqqgfa
#### Id
> bd4a19a9-1a49-4a2e-9f56-be0290e0bb60
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedxleg2pnw27itdbh46q2av7y32pleku2qg5o3ltdvyju72tw5md2

**Comment by kernelogic** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced6ysbu7zm6tpoopkhk7vqqynbdmtgiodepcmpwehnyvdqxn3earq 
#### Address 
> f13csteap4jcgl3a65qtsvmblzvelp4sgivddtpqa
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### Id
> bd4a19a9-1a49-4a2e-9f56-be0290e0bb60
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced6ysbu7zm6tpoopkhk7vqqynbdmtgiodepcmpwehnyvdqxn3earq

**Comment by cryptowhizzard** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedr3obuqi5bgkmbvbjht6uwfxhxmcyih7b2ty54bjopfekhemxh7a 
#### Address 
> f13csteap4jcgl3a65qtsvmblzvelp4sgivddtpqa
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1krmypm4uoxxf3g7okrwtrahlmpcph3y7rbqqgfa
#### Id
> a5b0af67-590e-4519-9b52-17bc23cefb48
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedr3obuqi5bgkmbvbjht6uwfxhxmcyih7b2ty54bjopfekhemxh7a

**Comment by kernelogic** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaiyc4o6uu4itqwv3hrq7iacgesd7vhbliuinqw3svpitfwz7lxuw 
#### Address 
> f13csteap4jcgl3a65qtsvmblzvelp4sgivddtpqa
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### Id
> a5b0af67-590e-4519-9b52-17bc23cefb48
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaiyc4o6uu4itqwv3hrq7iacgesd7vhbliuinqw3svpitfwz7lxuw

**Comment by BDEio** [comment]
@jessie8o8 Hi! Great to see that you have gotten approval for DataCap!
BDE is a verified deals auction house helping you to get paid storing your data with reliable storage providers. If you need any help, please get in touch.

**Comment by mjroddy** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceawldm3r2l5hhkxcahsrsmr776tmtlxd5gsod5shf6xiraiy5ch3y 
#### Address 
> f13csteap4jcgl3a65qtsvmblzvelp4sgivddtpqa
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1ystxl2ootvpirpa7ebgwl7vlhwkbx2r4zjxwe5i
#### Id
> 9a64386a-c028-41cb-bc08-e0ba5d6ecdd6
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceawldm3r2l5hhkxcahsrsmr776tmtlxd5gsod5shf6xiraiy5ch3y

**Comment by cryptowhizzard** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebmx3hsx4azinaj2gh6qeotn667tpeghw7x4tztvczwqb7d62b5sk 
#### Address 
> f13csteap4jcgl3a65qtsvmblzvelp4sgivddtpqa
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1krmypm4uoxxf3g7okrwtrahlmpcph3y7rbqqgfa
#### Id
> 19b7a933-79b7-457e-844f-282550828e36
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebmx3hsx4azinaj2gh6qeotn667tpeghw7x4tztvczwqb7d62b5sk

**Comment by jamerduhgamer** [comment]
We are currently working on getting replicas stored in the Netherlands and Singapore. CID sharing with Filswan should not be a continued issue as #80 has been closed.

**Comment by xingjitansuo** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecitduq2kv3sudg4iylxlkizmwrq5x6nut4tokkhimq33rwo4firk 
#### Address 
> f13csteap4jcgl3a65qtsvmblzvelp4sgivddtpqa
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1a2lia2cwwekeubwo4nppt4v4vebxs2frozarz3q
#### Id
> 19b7a933-79b7-457e-844f-282550828e36
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecitduq2kv3sudg4iylxlkizmwrq5x6nut4tokkhimq33rwo4firk

**Comment by kernelogic** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec3y7f5yszelsyltjoqeoozcaxwk7ih5v3eqtegtho5aqol2mx46s 
#### Address 
> f13csteap4jcgl3a65qtsvmblzvelp4sgivddtpqa
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### Id
> f0cbccdc-93b4-4838-a4e1-980737ede88d
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec3y7f5yszelsyltjoqeoozcaxwk7ih5v3eqtegtho5aqol2mx46s

**Comment by xinaxu** [comment]
checker:manualTrigger

**Comment by xinaxu** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedmzxgd752nbhhdnxosf4ypdyiayxzfjsqvmvxsfr2medcgvudfoa 
#### Address 
> f13csteap4jcgl3a65qtsvmblzvelp4sgivddtpqa
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1k3ysofkrrmqcot6fkx4wnezpczlltpirmrpsgui
#### Id
> f0cbccdc-93b4-4838-a4e1-980737ede88d
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedmzxgd752nbhhdnxosf4ypdyiayxzfjsqvmvxsfr2medcgvudfoa

**Comment by s0nik42** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb7y5vh7two5qtbe36vm52zzpjwe3ggckna74sd75iofminay6s7u 
#### Address 
> f13csteap4jcgl3a65qtsvmblzvelp4sgivddtpqa
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1wxhnytjmklj2czezaqcfl7eb4nkgmaxysnegwii
#### Id
> f0cbccdc-93b4-4838-a4e1-980737ede88d
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb7y5vh7two5qtbe36vm52zzpjwe3ggckna74sd75iofminay6s7u

**Comment by jamerduhgamer** [comment]
Datacap is currently being sealed.

**Comment by data-programs** [comment]
<img width="32" alt="KYC" Verified src="https://stable.filplus.storage/images/filplus-kyc-verified-badge.png"/>

This user’s identity has been verified through [filplus.storage](https://filplus.storage)

**Comment by Sunnyiscoming** [comment]
Hello, @jessie8o8 per the https://github.com/filecoin-project/notary-governance/issues/922 for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

This information will be reviewed by Fil+ Governance team to confirm validity and then the application will be allowed to move forward for additional notary review.

**Comment by jessie8o8** [comment]
Hi @Sunnyiscoming, the form is complete and submitted.
