### ISSUE TITLE
[DataCap Application] envato pty ltd.

### ISSUE THREAD

**Issue by cdcdx** [filecoin-project/filecoin-plus-large-datasets#436]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: envato pty ltd.
- Website / Social Media: https://www.akustyczna.info
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 500TiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 10TiB
- On-chain address for first allocation: f1upoqjjco3fyt2g3j35hhn2zdfak32jqavwbtyvi

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
The Origin Sound Blockchain solves the problem of copyright confirmation in the transaction process based on mathematical principles, and the record, transmission and storage results of value exchange activities are reliable. Once the blockchain record information is generated, it will be permanently logged and cannot be tampered. Only people with more than 51% of the total network-wide computing power will be able to modify the newly generated block record.
```

What is the primary source of funding for this project?
```
from income of envato.
```

What other projects/ecosystem stakeholders is this project associated with?
```
No.
```

## Use-case details

Describe the data being stored onto Filecoin
```
Live lesson audios and pictures/text of coursewares.
```

Where was the data in this dataset sourced from?
```
envato provide courses to users. Users also can upload courses into the platform.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
[data for demo](https://www.akustyczna.info/fil-datasets/demo.mp3)
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes, I confirm.
```

What is the expected retrieval frequency for this data?
```
It will be retrieved every 1-2 years.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
Long-term storage.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Around Asia.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Yes, we choose offline data transfer process. We have disks for it.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
Slack and Github are good platforms for us connecting with storage providers.We plan choosing 5 storage providers at first.
```

How will you be distributing deals across storage providers?
```
Following community rule, every sp will be distributed below 25% of whole deals. We'll pay attention to it.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes. We don't need support for the moment.
```

**Comment by Sunnyiscoming** [comment]
Hi,@cdcdx The following information is checked just to verify the authenticity of users and data, no offense.
 
1. Windows boot music doesn't seem like a good data example.

> Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this.
> 
> [data for demo](https://www.akustyczna.info/fil-datasets/demo.mp3)

2.I didn't find any relevant informations about what you said about organization.
![image](https://user-images.githubusercontent.com/105098820/177264516-ecaae2cb-6514-42cd-9af5-61f003ba0614.png)
https://www.envato.com/, which is the official website of Envato Pty Ltd.
Envato Pty Ltd is an online marketplace. The Company allows users to buy and sell creative assets, use smart design templates, learn creative skills, and even hire freelancers. Envato serves customers in Australia.(https://www.bloomberg.com/profile/company/1021121D:AU)

> The Origin Sound Blockchain solves the problem of copyright confirmation in the transaction process based on mathematical principles, and the record, transmission and storage results of value exchange activities are reliable. Once the blockchain record information is generated, it will be permanently logged and cannot be tampered. Only people with more than 51% of the total network-wide computing power will be able to modify the newly generated block record.

3.It seems that the website was eastimated for 12 days.
https://whois.whoisxmlapi.com/lookup-report/Gz21j3w75r
Estimated domain age: 12 day(s)

**Comment by Sunnyiscoming** [comment]
Are you an employee of Envato Pty LTD.?

**Comment by Sunnyiscoming** [comment]
Any update here?

**Comment by dkkapur** [comment]
Closing this out for now since there was no response to the above questions. Please open up a new application if still relevant.
