### ISSUE TITLE
[DataCap Application] <Mgame>

### ISSUE THREAD

**Issue by Hailey-Li** [filecoin-project/filecoin-plus-large-datasets#439]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Mgame
- Website / Social Media: https://www.mgame.com/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5 PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 300TiB
- On-chain address for first allocation: f1qjr6wrrjp45bxp2lbvnuqwleiyaylex2rsv2gky

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Mgame Corp. is a Korea-based company engaged in the development and publishing of game software for online games. The Company provides massively multiplayer online role-playing games (MMORPGs), first-person shooter (FPS) games, sports games, RPG games, casual games, Web board games and others. The Company distributes its game products to domestic market through its portal site, www.mgames.com. It also provides online game services to overseas markets through portal sites, www.netgame.com and www.mgame.jp. In addition, it provides advertising services.
```

What is the primary source of funding for this project?
```
Company revenues.
```

What other projects/ecosystem stakeholders is this project associated with?
```
No.
```

## Use-case details

Describe the data being stored onto Filecoin
```
Graphic resources, program codes, videos, database, texture, audios, 3D model, APKs, APIs and other materials required for game development.
```

Where was the data in this dataset sourced from?
```
Mainly from users’ activities on the website..
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://www.youtube.com/hashtag/mgame
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
This is a public dataset that can be publicly retrieved.
```

What is the expected retrieval frequency for this data?
```
There is no fixed retrieval frequency for this data.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
3 years.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Asia, the United States and Brazil.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Both online and offline transfer.  
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We will undertake inspections over prospective storage providers based on the following factors:
- location
- transmission speed
- deal success rate
- previous experience of real data storage
- stability of their nodes
```

How will you be distributing deals across storage providers?
```
We plan to select 4-5 providers according to their network bandwidth and storage efficiency, and each won't surpass 30% of the quota.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes.
```

**Comment by Sunnyiscoming** [comment]
> Describe the data being stored onto Filecoin
> 
> Graphic resources, program codes, videos, database, texture, audios, 3D model, APKs, APIs and other materials required for game development.

The data sample provided are not related with the data will be stored on the Filecoin network, which are mostly videos of users sharing games. Can you provide more data samples about game development?
@Hailey-Li

**Comment by Sunnyiscoming** [comment]
Any update here?

**Comment by dkkapur** [comment]
Closing this out for now since there was no response to the above questions. Please open up a new application if still relevant.
