### ISSUE TITLE
[DataCap Application] Hangzhou Aiyao

### ISSUE THREAD

**Issue by AiYueKeJi** [filecoin-project/filecoin-plus-large-datasets#440]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Hangzhou Aiyao Medical Health Technology Co., Ltd.
- Website / Social Media: http://www.cbang.io/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):100TiB
- On-chain address for first allocation:f1pkhhp5oolmih5xyip4o4fzi4erjorklquhzymsq

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Hangzhou Aiyao Medical Health Technology Co., Ltd ("Aiyao") was established in Hangzhou in 2019 by divesting itself from Tencent Group, with Tencent Group still as its controlling shareholder.

The company was founded based on the informationization of the medical industry, while focusing on the creation of health education short video content, and gradually transformed into a life entertainment health management ecological builder "with the core goal of achieving a comfortable and happy healthy life for users".

At present, the company has accumulated a large number of users, and in the future, the company will continue to expand the richness of content in the field of short video, and gradually transform into a full ecological builder in the field of short video.

```

What is the primary source of funding for this project?
```
Currently, it mainly comes from the company's shareholders, and we do not rule out the introduction of further strategic investment partners in the future.
```

What other projects/ecosystem stakeholders is this project associated with?
```
There is no other projects/ecosystem stakeholders associated with.
```

## Use-case details

Describe the data being stored onto Filecoin
```
Short videos or photos of food, pets, scenery and recreational activities created and uploaded by users, the official website is currently in the pre-construction stage, we will continue to improve
```

Where was the data in this dataset sourced from?
```
Created and uploaded by real users
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
Of course, see the link for details：http://www.ids.link/wp-content/uploads/2022/06/Wait-For-End.mp4
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes
```

What is the expected retrieval frequency for this data?
```
It won't be retrieved very often.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
2 years at least. We will have a try to store a long time.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Asia
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Prefer online, if needed offline can also be considered.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We would like to find some miners who are large-scale and creditable. 
```

How will you be distributing deals across storage providers?
```
We would divide the data up and send it to different miners.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes，we're ready for making deals.
```

**Comment by Kakkouii** [comment]
1. What the relationship between [钛墟寰镜](http://www.cbang.io/) and the link at the bottom of this website, http://www.keytocaring.com/index. The latter one seems to be the client company. So why there are different websites?
2. Both the two websites have very small amount of data, far from 5PB, and no clues indicates those data are as described in this application. Please provide more samples to prove your requirement if possible.
3. [Hangzhou Aiyao](http://www.keytocaring.com/index) was registered in China, while [钛墟寰镜](http://www.cbang.io/) in US, and the registrars are different. Please clarify their relationship.
<img width="702" alt="image" src="https://user-images.githubusercontent.com/105268629/177396264-6e151568-e3ba-42f2-823e-893cd38e3dec.png">
<img width="704" alt="image" src="https://user-images.githubusercontent.com/105268629/177396397-b6ba8d38-1ead-4f39-81b6-b90681192a01.png">

**Comment by Sunnyiscoming** [comment]
@AiYueKeJi Hi,
There are only a few contents published on the website.
http://www.cbang.io/category/short-video/
http://www.cbang.io/category/%e7%be%8e%e9%85%92%e4%b8%8e%e7%be%8e%e9%a3%9f%e4%b8%8d%e5%8f%af%e8%be%9c%e8%b4%9f/
It seems that this large dataset do not have 5 PB. Can you explain about that?
The website's estimated domain age: 58 day(s)

**Comment by Kakkouii** [comment]
1.I do understand your situation here but a pre-alpha website and data uploaded by users in the FUTURE doesn't seem to be an adequate reason to apply 5PB DataCap. 
2.According to your screenshot, activity of your users are relatively low. The total view of the website is merely 220, that's far from 300,000 users or how many active users do you have to upload data to the future website.
3.Since the trademark of Taixu is under registration, can you provide more evidence to prove Taixu is a subsidiary of your company? I believe it's necessary to have a double check in case of avoiding abuse website and data of others.
4.Those files seem to be footages of a dashboard camera. Are they uploaded by users too?
![](https://user-images.githubusercontent.com/107978179/177742847-0e147f5b-2cad-45f3-9a2b-bfb7cf0b2fdb.png)

**Comment by AiYueKeJi** [comment]
> 1.I do understand your situation here but a pre-alpha website and data uploaded by users in the FUTURE doesn't seem to be an adequate reason to apply 5PB DataCap. 2.According to your screenshot, activity of your users are relatively low. The total view of the website is merely 220, that's far from 300,000 users or how many active users do you have to upload data to the future website. 3.Since the trademark of Taixu is under registration, can you provide more evidence to prove Taixu is a subsidiary of your company? I believe it's necessary to have a double check in case of avoiding abuse website and data of others. 4.Those files seem to be footages of a dashboard camera. Are they uploaded by users too? ![](https://user-images.githubusercontent.com/107978179/177742847-0e147f5b-2cad-45f3-9a2b-bfb7cf0b2fdb.png)

Hi，[Kakkouii](https://github.com/Kakkouii)，Thanks for your questions.
AiYao is a health service company. In the past, we focused on sales and development and did not pay much attention to data storage. Now we have more than 300,000 real users, a large number of health education and various data provided by users. We urgently need a platform to store these precious materials.

1.AiYao is a business-focused company, but now we're starting to think about creating and running a user community. We have more than 300,000 real users, a large number of health education and various data provided by users. We have strong storage requirements. Even if the data uploaded in the future is not considered, the existing sufficient data can completely apply for 5 PiB Datacap. Data type samples can refer to the previous screenshots.

2.AiYao's customer statistics are multi-channel, including official website, WeChat public account, background management system, etc. We have sold more than 294,000 smart devices with IMEI code numbers. All devices with public network communication functions in the world require IMEI codes. The IMEI code is equivalent to the ID card of smart devices, which is universal in the world and cannot be faked. That means we have over 294,000 users, not counting the joint family members of each actual user. See the figure below for details.

![图片](https://user-images.githubusercontent.com/107978179/177964868-0ddb7e68-0566-4d82-ba1a-3cc9fefd6f74.png)

We have accumulated a total of more than 84,000 WeChat Official Account users. See the figure below for details.
![图片](https://user-images.githubusercontent.com/107978179/177965199-7137b763-7b82-4906-b3a2-13f3e530d17a.png)

Therefore, we say 300,000 users, which has always been a relatively conservative statistic. Users are mainly diabetic patients and their families.

As mentioned above, AiYao has always been focusing on business development, but has relatively neglected website operation promotion and data display. We have also repeatedly emphasized that the current video platform website is still in the internal testing stage, there is no publicity, and the links are relatively hidden, but this does not mean we don't have enough data at the moment.

Community operation and interaction will be an important direction for our future business development and an inevitable trend of the company's strategic transformation.

3.The company name of Hangzhou AiYao has been written at the bottom of the TAIXU website, and the link of the TAIXU is also hung on the official WeChat account of AiYao, as shown in the figure below.
![图片](https://user-images.githubusercontent.com/107978179/177965288-d1df4c75-dbb5-43a9-8f25-062a85a0f1e4.png)
![图片](https://user-images.githubusercontent.com/107978179/177965317-1f1577f7-6463-4c22-964a-4ea042af3cb9.png)

If you think it is necessary, we can also publish a floating window statement on the homepage of the “TAIXU” website, stating that this website belongs to Hangzhou Aiyao.

4.This is the driving recorder of the company's vehicle. It was originally backed up to prevent possible claims or liability determination for driving accidents. We believe that there is also a certain storage requirement just in case, although such data will not be queried frequently.

Of course, the data types that require the most storage are corporate health education videos and past user interaction videos

Thank you Kakkouii for your patience, what more do you need from us? Please let us know in advance. Thank you~.

**Comment by Kakkouii** [comment]
@AiYueKeJi Thank you very much for the greatly kind response. Very clear and detailed explanation, that's enough for both me and the community to know your project and business better. Have a good day!

**Comment by Sunnyiscoming** [comment]
@Kakkouii Any question here?
@AiYueKeJi  Could you send an email to filplus@fil.org with your official domain(http://www.keytocaring.com/; http://www.keytocaring.com/) in order to confirm your identity? Email name should includes the issue id #440.

**Comment by AiYueKeJi** [comment]
> @Kakkouii Any question here? @AiYueKeJi Could you send an email to [filplus@fil.org](mailto:filplus@fil.org) with your official domain(http://www.keytocaring.com/; http://www.keytocaring.com/) in order to confirm your identity? Email name should includes the issue id #440.

@Sunnyiscoming Hi,Sunnyiscoming,the email has been replied, please check it and look forward to further feedback, thank you very much!

**Comment by AiYueKeJi** [comment]
@Kakkouii Hi,anyother questions?We would be happy to answer.Thanks！

@Sunnyiscoming Hi,Sunnyiscoming,what else do we need to do?Looking forward to official approval.Thanks！

**Comment by Sunnyiscoming** [comment]
We will check the email quickly. Thanks for waiting.

**Comment by StFileCloud** [comment]
@AiYueKeJi Hi! I've checked your website again and it's great to see a lot of updates here. But there is some movie footage on your website. Are you going to store them here? I'm afraid that copyright issues will trouble our community.

**Comment by Sunnyiscoming** [comment]
I see that the website has been updated. Can you explain the source of this data? Whether you have permission to use the data?

**Comment by AiYueKeJi** [comment]
> I see that the website has been updated. Can you explain the source of this data? Whether you have permission to use the data?

As mentioned before,our data sources are mainly our own data and data uploaded by users, all of which have been licensed for legal use. 

I believe you are in doubt about some of the film videos, which are all public copyright films, and according to the Berne Convention, the term of copyright protection for films is 50 years from the date of public release, that is,  Movies released before the 10th August 1972 are already public copyright movies. 

If you have doubts about this part of the data, we can choose not to upload these data.

**Comment by AiYueKeJi** [comment]
@Sunnyiscoming 

Our process has been 1.5 months, we are very timely to respond to any official questions, but also hope that the official can be approved as soon as possible, we are very optimistic about filecoin, very much looking forward to the approval, thank you very much

**Comment by AiYueKeJi** [comment]
Hello, team, is there any update on this application? It has been almost 2 months. @galen-mcandrew @Kevin-FF-USA @dkkapur

**Comment by raghavrmadya** [comment]
Please share more about the number of copies you will store and the SPs you plan to work with. The community is still concerned that you are applying for 5 PiBs upfront for future use. If you are not able to support the claim, you are welcome to adjust the request in this application itself.

**Comment by AiYueKeJi** [comment]
> Please share more about the number of copies you will store and the SPs you plan to work with. The community is still concerned that you are applying for 5 PiBs upfront for future use. If you are not able to support the claim, you are welcome to adjust the request in this application itself.

Real data 1P (case sample as above screenshot), data 5 backup, we have already communicated with Greaterheat, NewWebGroup and other SP initially.

Among them, the communication with Greaterheat is progressing smoothly, and the nodes of f01877571, f01878005 and f01880047 are planned to be encapsulated.

SP we are looking through the official list of SP as well as slack. We are committed to real data compliance and validity, and looking for reliable SPs under the official rules.

@galen-mcandrew @Kevin-FF-USA @dkkapur@raghavrmadya

**Comment by raghavrmadya** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5 PiB

**Expected weekly DataCap usage rate**

> 100 TiB

**Client address**

> f1pkhhp5oolmih5xyip4o4fzi4erjorklquhzymsq

**Comment by raghavrmadya** [comment]
Notaries are encouraged to look at the discussion to make an informed decision before proposing DC. @AiYueKeJi, thank you for being responsive. Please note that while the governance team has unblocked the application, community members and notaries still have full right to do further due diligence. You are welcome to come to the next governance call to gain community confidence.

**Comment by newwebgroup** [comment]
From the above data samples
The types of data samples provided are too messy. According to my observation, there is not much data on medical health. I hope to see more about medical health in the future

I will keep paying attention to what data you save in filecoin


in addition
I used the data analysis website to check the number of followers on your wechat official account, which is similar to the description.
<img width="719" alt="image" src="https://user-images.githubusercontent.com/100118145/187824508-e86296dc-91d6-426e-ae47-838bdc48ae3d.png">

**Comment by newwebgroup** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecik7xglthuwr5bwbmosao4ryenucywixyg6numxkejyurbwkqwt2 
#### Address 
> f1pkhhp5oolmih5xyip4o4fzi4erjorklquhzymsq
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1e77zuityhvvw6u2t6tb5qlnsegy2s67qs4lbbbq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecik7xglthuwr5bwbmosao4ryenucywixyg6numxkejyurbwkqwt2

**Comment by kernelogic** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedmg64acjz3q2igduljw6y4vgrh4vaou6xlxyr3i46tzuwmvleh26 
#### Address 
> f1pkhhp5oolmih5xyip4o4fzi4erjorklquhzymsq
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedmg64acjz3q2igduljw6y4vgrh4vaou6xlxyr3i46tzuwmvleh26

**Comment by 1ane-1** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceay4a2xjmmqebvmwjspllihk3dw2zqv27ultda2przhha7ojqtns6 
#### Address 
> f1pkhhp5oolmih5xyip4o4fzi4erjorklquhzymsq
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1mdk7s2vntzm6hu35yuo6vjubtrpfnb2awhgvrri
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceay4a2xjmmqebvmwjspllihk3dw2zqv27ultda2przhha7ojqtns6

**Comment by kernelogic** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb6abvfphclpjdtziv4fqgi6psqlurhy765ymrz2wa7ywqqsexofc 
#### Address 
> f1pkhhp5oolmih5xyip4o4fzi4erjorklquhzymsq
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb6abvfphclpjdtziv4fqgi6psqlurhy765ymrz2wa7ywqqsexofc

**Comment by AiYueKeJi** [comment]
> 

Thank you so much!

**Comment by BigD-Exchange** [comment]
@AiYueKeJi Hi! Great to see you have gotten approval for DataCap and advancing the mission of preserving humanity’s most important information. If you are looking for storage providers to store these data or have any questions, please visit #bigdata-exchange on Filecoin Slack or reply here. 

We have strong demand from a diverse group of SPs, who are actively looking to onboard more data.

**Comment by psh0691** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecjyar3km7wsiqckur7jabjbh5px6z65gxx4wnmkjce524bk7crya 
#### Address 
> f1pkhhp5oolmih5xyip4o4fzi4erjorklquhzymsq
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1qdko4jg25vo35qmyvcrw4ak4fmuu3f5rif2kc7i
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecjyar3km7wsiqckur7jabjbh5px6z65gxx4wnmkjce524bk7crya

**Comment by kernelogic** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaspn6t4ob5b4blijiilanrt6a257kebmzzw7f6qlimeq2o262y54 
#### Address 
> f1pkhhp5oolmih5xyip4o4fzi4erjorklquhzymsq
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaspn6t4ob5b4blijiilanrt6a257kebmzzw7f6qlimeq2o262y54

**Comment by newwebgroup** [comment]
Client finds me through Slack
According to historical KYB records and the distribution of SPs, it looks good.

<img width="551" alt="image" src="https://user-images.githubusercontent.com/100118145/206977117-452b706f-1869-4418-87c6-1b73d563953d.png">

**Comment by newwebgroup** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedl3c63oulqaxg7ri3jbnmusmfqb2qkczpix2fgy6kfzdxgg7al52 
#### Address 
> f1pkhhp5oolmih5xyip4o4fzi4erjorklquhzymsq
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1e77zuityhvvw6u2t6tb5qlnsegy2s67qs4lbbbq
#### Id
> 98f149a0-ec56-473a-844d-d3492330b1c9
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedl3c63oulqaxg7ri3jbnmusmfqb2qkczpix2fgy6kfzdxgg7al52

**Comment by liyunzhi-666** [comment]
looking good so far

**Comment by liyunzhi-666** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceatr5a5khjicxhahr4uef2wsrql4uhmkdz3ppwfw3vex6j4pxa6oq 
#### Address 
> f1pkhhp5oolmih5xyip4o4fzi4erjorklquhzymsq
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1pszcrsciyixyuxxukkvtazcokexbn54amf7gvoq
#### Id
> 98f149a0-ec56-473a-844d-d3492330b1c9
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceatr5a5khjicxhahr4uef2wsrql4uhmkdz3ppwfw3vex6j4pxa6oq

**Comment by filplus-checker** [comment]
## DataCap and CID Checker Report[^1]
 - Organization: `Hangzhou Aiyao Medical Health Technology Co., Ltd.`
 - Client: `f1pkhhp5oolmih5xyip4o4fzi4erjorklquhzymsq`
### Storage Provider Distribution
The below table shows the distribution of storage providers that have stored data for this client.

If this is the first time a provider takes verified deal, it will be marked as `new`.

For most of the datacap application, below restrictions should apply.
 - Storage provider should not exceed 25% of total datacap.
 - Storage provider should not be storing duplicate data for more than 20%.
 - Storage provider should have published its public IP address.
 - All storage providers should be located in different regions.

⚠️ [f033462](https://filfox.info/en/address/f033462) has sealed 26.89% of total datacap.

| Provider                                              |                 Location | Total Deals Sealed | Percentage | Unique Data | Duplicate Deals |
| :---------------------------------------------------- | -----------------------: | -----------------: | ---------: | ----------: | --------------: |
| [f033462](https://filfox.info/en/address/f033462)     |        Dallas, Texas, US |         105.62 TiB |     26.89% |  105.62 TiB |           0.00% |
| [f01985745](https://filfox.info/en/address/f01985745) |        Dallas, Texas, US |          75.91 TiB |     19.33% |   75.91 TiB |           0.00% |
| [f01985775](https://filfox.info/en/address/f01985775) |        Dallas, Texas, US |          61.22 TiB |     15.59% |   61.22 TiB |           0.00% |
| [f01878005](https://filfox.info/en/address/f01878005) | Singapore, Singapore, SG |          35.27 TiB |      8.98% |   35.27 TiB |           0.00% |
| [f01882184](https://filfox.info/en/address/f01882184) | Singapore, Singapore, SG |          35.26 TiB |      8.98% |   35.26 TiB |           0.00% |
| [f01877571](https://filfox.info/en/address/f01877571) | Singapore, Singapore, SG |          35.23 TiB |      8.97% |   35.23 TiB |           0.00% |
| [f01882177](https://filfox.info/en/address/f01882177) | Singapore, Singapore, SG |          35.20 TiB |      8.96% |   35.20 TiB |           0.00% |
| [f01880047](https://filfox.info/en/address/f01880047) | Singapore, Singapore, SG |           9.00 TiB |      2.29% |    9.00 TiB |           0.00% |

![Provider Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/440/1671096931405.png)
### Deal Data Replication
The below table shows how each many unique data are replicated across storage providers.
- No more than 25% of unique data are stored with less than 4 providers.

⚠️ 100.00% of deals are for data replicated across less than 4 storage providers.

| Unique Data Size | Total Deals Made | Number of Providers | Deal Percentage |
| ---------------: | ---------------: | ------------------: | --------------: |
|       392.70 TiB |       392.70 TiB |                   1 |         100.00% |

![Replication Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/440/1671096932146.png)
### Deal Data Shared with other Clients
The below table shows how many unique data are shared with other clients.
Usually different applications owns different data and should not resolve to the same CID.

✔️ No CID sharing has been observed.

[^1]: To manually trigger this report, add a comment with text `checker:manualTrigger`

**Comment by kernelogic** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced7i3rq2u7ku3syyb5curwwnxde2bmgoxwciflfeglwddjlvx3f3y 
#### Address 
> f1pkhhp5oolmih5xyip4o4fzi4erjorklquhzymsq
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### Id
> a2add692-1232-4c1e-b9a6-6c2a5241b090
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced7i3rq2u7ku3syyb5curwwnxde2bmgoxwciflfeglwddjlvx3f3y

**Comment by psh0691** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebujonu6jo7cajlvptvy4dtdpaabm6iv3qnwwu7nbzqv5v5iwpvgo 
#### Address 
> f1pkhhp5oolmih5xyip4o4fzi4erjorklquhzymsq
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1qdko4jg25vo35qmyvcrw4ak4fmuu3f5rif2kc7i
#### Id
> a2add692-1232-4c1e-b9a6-6c2a5241b090
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebujonu6jo7cajlvptvy4dtdpaabm6iv3qnwwu7nbzqv5v5iwpvgo

**Comment by psh0691** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceadqlw5pin6aqdjqq45b5lzfktgkmlbtmfpllll3uzhymnvop3rsw 
#### Address 
> f1pkhhp5oolmih5xyip4o4fzi4erjorklquhzymsq
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1qdko4jg25vo35qmyvcrw4ak4fmuu3f5rif2kc7i
#### Id
> f841779d-058c-4bb6-8e1b-71016e8962aa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceadqlw5pin6aqdjqq45b5lzfktgkmlbtmfpllll3uzhymnvop3rsw

**Comment by xingjitansuo** [comment]
All the providers you currently work with are storing the first copy, would you like to share any timeline on other duplicates?

**Comment by AiYueKeJi** [comment]
> All the providers you currently work with are storing the first copy, would you like to share any timeline on other duplicates?

Yes, our next plan is to find other SPs and BDEs for decentralized storage, and follow the official rules for storage.

**Comment by xingjitansuo** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceddotuglnprugjo5jnaknap237r2grr6plww7yjb6tplsscrpzln6 
#### Address 
> f1pkhhp5oolmih5xyip4o4fzi4erjorklquhzymsq
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1a2lia2cwwekeubwo4nppt4v4vebxs2frozarz3q
#### Id
> f841779d-058c-4bb6-8e1b-71016e8962aa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceddotuglnprugjo5jnaknap237r2grr6plww7yjb6tplsscrpzln6

**Comment by BDEio** [comment]
@AiYueKeJi Hi! Congratulations on your DataCap approval！
BDE is a verified deals auction house helping you to get paid storing your data with reliable storage providers. If you need any help, please get in touch.

**Comment by woshidama323** [comment]
checker:manualTrigger

**Comment by woshidama323** [comment]
What's your plan for fixing this warning
"82.63% of deals are for data replicated across less than 4 storage providers."

**Comment by AiYueKeJi** [comment]
> What's your plan for fixing this warning "82.63% of deals are for data replicated across less than 4 storage providers."

We will continue to decentralize the data even more, so stay tuned for our later packages, thank you very much!

**Comment by woshidama323** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedougeebycrvbj3llrae2egloip3a5z4z3q5uo2qdqxvhzpolvo3e 
#### Address 
> f1pkhhp5oolmih5xyip4o4fzi4erjorklquhzymsq
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f12tk3adljauwnd3hjbigpfxb7b7gdlj63p6afwtq
#### Id
> 485a1aac-acf5-4f43-b4ed-21e43772e46e
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedougeebycrvbj3llrae2egloip3a5z4z3q5uo2qdqxvhzpolvo3e
