### ISSUE TITLE
[DataCap Application] Project Beacon LDN 3/12 - Jianzhi Power

### ISSUE THREAD

**Issue by Beacon-Edu** [filecoin-project/filecoin-plus-large-datasets#447]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Beacon Project
- Website / Social Media: Due to the privacy concerns of many parties involved in our educational programs, our website will only be available to PL and the relevant notaries.
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 300TiB
- On-chain address for first allocation: f1gilyodlplfjlhscfc6uieabffua5c45rtqvijyi

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
In 1995, we established Education Group Limited under our group. Since then, it has become one of the largest private basic education schools in China, serving over 60,000 teachers and students. Over the past 20 years, more than 30,000 of our students have been enrolled in domestic and foreign universities. With a 95% pass rate on China's university entrance exam which is known as Gao Kao, we are proud of preparing students to become engaged global citizens.
In addition, our group's international schools have students from over 23 countries and regions, including mainland China, the United States, Japan, Great Britain, Germany, Korea, Italy, Russia, Canada, etc. We have sent a large number of outstanding students to world-renowned universities such as Cambridge University, Harvard University, MIT, Imperial College London, Peking University and Tsinghua University.
Our group adheres to the strategic academic principles of "competitiveness, characterization and internationalization" in education to effectively improve the quality of our schools, communities and teachers. We have persistently built our educational strengths since the beginning, ultimately aiming to become one of the top K12 private education groups in China and the world by 2025.
```

What is the primary source of funding for this project?
```
Private capital
```

What other projects/ecosystem stakeholders is this project associated with?
```
No related association

```

## Use-case details

Describe the data being stored onto Filecoin
```
The dataset contains courses from more than 100 schools, documentation managed by teams of teachers, and over 3,600 videos of lessons recordings. Due to the privacy of the students & teachers as well as the teacher's behavior in the classroom, the data itself is not of use to anyone except our education group. Therefore, the data will be encrypted for our own consideration.
```

Where was the data in this dataset sourced from?
```
![Chart1](https://user-images.githubusercontent.com/106231732/175933248-cedd1225-ed0d-40d5-90cb-8807924564bc.png)
![Chart2](https://user-images.githubusercontent.com/106231732/175933258-0318f5f6-e2a3-4c1e-9e1c-871eaca99947.png)
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
No, data samples will only be shared to PL and the relevant Notary for KYC purpose.
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
No, this is an encrypted dataset that can only be sealed by the Chinese SP due to government policy.
```

What is the expected retrieval frequency for this data?
```
Depends on the demand of our business.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
2 years at least.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Greater China
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Yes, we will be using offline data transfer, which will be more efficient than online transfer.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
![image](https://user-images.githubusercontent.com/106231732/182092475-c0062e3c-7327-45b8-be1f-b9f0b7083e9d.png)

How will you be distributing deals across storage providers?
```
Less than 20% of total data will be stored in each SP.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, we already prepared enough funding for making deals.
```

**Comment by dkkapur** [comment]
## Datacap Request Trigger
#### Total DataCap requested 
> 5 PiB
#### Expected weekly DataCap usage rate 
> 300 TiB 
#### Client address
> f1gilyodlplfjlhscfc6uieabffua5c45rtqvijyi

**Comment by kernelogic** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceafebw4hpn3xr43earw5kunrkw473zjcahrgmnotqqspthmgbcmyi 
#### Address 
> f1gilyodlplfjlhscfc6uieabffua5c45rtqvijyi
#### Datacap Allocated
> 150.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceafebw4hpn3xr43earw5kunrkw473zjcahrgmnotqqspthmgbcmyi

**Comment by fireflyHZ** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebxeqquuouwzgoy2s32zwtjmqtidvi32hib67yhqunhpjq2asiii6 
#### Address 
> f1gilyodlplfjlhscfc6uieabffua5c45rtqvijyi
#### Datacap Allocated
> 150.00TiB
#### Signer Address
> f1fg6jkxsr3twfnyhdlatmq36xca6sshptscds7xa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebxeqquuouwzgoy2s32zwtjmqtidvi32hib67yhqunhpjq2asiii6

**Comment by Sunnyiscoming** [comment]
Are there any problems with using datacap?

**Comment by Beacon-Edu** [comment]
Yes.

**Comment by Beacon-Edu** [comment]
Yes.
