### ISSUE TITLE
[DataCap Application] Project Beacon LDN 4/12 - Jiami Jingling

### ISSUE THREAD

**Issue by Beacon-Edu** [filecoin-project/filecoin-plus-large-datasets#448]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Beacon Project
- Website / Social Media: Due to the privacy concerns of many parties involved in our educational programs, our website will only be available to PL and the relevant notaries.
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 300TiB
- On-chain address for first allocation: f1hamzyd3tx4pdchop3l4hfeay5q6s427pxga6flq

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
In 1995, we established Education Group Limited under our group. Since then, it has become one of the largest private basic education schools in China, serving over 60,000 teachers and students. Over the past 20 years, more than 30,000 of our students have been enrolled in domestic and foreign universities. With a 95% pass rate on China's university entrance exam which is known as Gao Kao, we are proud of preparing students to become engaged global citizens.
In addition, our group's international schools have students from over 23 countries and regions, including mainland China, the United States, Japan, Great Britain, Germany, Korea, Italy, Russia, Canada, etc. We have sent a large number of outstanding students to world-renowned universities such as Cambridge University, Harvard University, MIT, Imperial College London, Peking University and Tsinghua University.
Our group adheres to the strategic academic principles of "competitiveness, characterization and internationalization" in education to effectively improve the quality of our schools, communities and teachers. We have persistently built our educational strengths since the beginning, ultimately aiming to become one of the top K12 private education groups in China and the world by 2025.
```

What is the primary source of funding for this project?
```
Private capital
```

What other projects/ecosystem stakeholders is this project associated with?
```
No related association

```

## Use-case details

Describe the data being stored onto Filecoin
```
The dataset contains courses from more than 100 schools, documentation managed by teams of teachers, and over 3,600 videos of lessons recordings. Due to the privacy of the students & teachers as well as the teacher's behavior in the classroom, the data itself is not of use to anyone except our education group. Therefore, the data will be encrypted for our own consideration.
```

Where was the data in this dataset sourced from?
```
![Chart1](https://user-images.githubusercontent.com/106231732/175933248-cedd1225-ed0d-40d5-90cb-8807924564bc.png)
![Chart2](https://user-images.githubusercontent.com/106231732/175933258-0318f5f6-e2a3-4c1e-9e1c-871eaca99947.png)
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
No, data samples will only be shared to PL and the relevant Notary for KYC purpose.
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
No, this is an encrypted dataset that can only be sealed by the Chinese SP due to government policy.
```

What is the expected retrieval frequency for this data?
```
Depends on the demand of our business.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
2 years at least.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Greater China
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Yes, we will be using offline data transfer, which will be more efficient than online transfer.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
![image](https://user-images.githubusercontent.com/106231732/182092627-65f8920e-4ed9-4ae2-9556-8aa5b5ada72c.png)

How will you be distributing deals across storage providers?
```
Less than 20% of total data will be stored in each SP.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, we already prepared enough funding for making deals.
```

**Comment by dkkapur** [comment]
## Datacap Request Trigger
#### Total DataCap requested 
> 5 PiB
#### Expected weekly DataCap usage rate 
> 300 TiB 
#### Client address
> f1hamzyd3tx4pdchop3l4hfeay5q6s427pxga6flq

**Comment by kernelogic** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecka5b5jbjkpribupffipncvss6kvp3bufilb3gq2f6vxzesugwsw 
#### Address 
> f1hamzyd3tx4pdchop3l4hfeay5q6s427pxga6flq
#### Datacap Allocated
> 150.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecka5b5jbjkpribupffipncvss6kvp3bufilb3gq2f6vxzesugwsw

**Comment by fireflyHZ** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebficnqs474u6crpuotpzmkc7l6d6kcatp6w76xc6iwpikfpshrjc 
#### Address 
> f1hamzyd3tx4pdchop3l4hfeay5q6s427pxga6flq
#### Datacap Allocated
> 150.00TiB
#### Signer Address
> f1fg6jkxsr3twfnyhdlatmq36xca6sshptscds7xa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebficnqs474u6crpuotpzmkc7l6d6kcatp6w76xc6iwpikfpshrjc

**Comment by kernelogic** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced2jpnaiyz3aexw4aiiacflqnm4ho5he77y5mkkeafxg3fs237btq 
#### Address 
> f1hamzyd3tx4pdchop3l4hfeay5q6s427pxga6flq
#### Datacap Allocated
> 300.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced2jpnaiyz3aexw4aiiacflqnm4ho5he77y5mkkeafxg3fs237btq

**Comment by liyunzhi-666** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedovrhn63aklan7efsmafneahyaygp7xpxofkkn5yshltnpisijjm 
#### Address 
> f1hamzyd3tx4pdchop3l4hfeay5q6s427pxga6flq
#### Datacap Allocated
> 300.00TiB
#### Signer Address
> f1pszcrsciyixyuxxukkvtazcokexbn54amf7gvoq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedovrhn63aklan7efsmafneahyaygp7xpxofkkn5yshltnpisijjm

**Comment by swatchliu** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaxk2aqzlwmceugemqb6as6zzzfp5x3wtsv5gf4352abertaw5pr4 
#### Address 
> f1hamzyd3tx4pdchop3l4hfeay5q6s427pxga6flq
#### Datacap Allocated
> 600.00TiB
#### Signer Address
> f1yh6q3nmsg7i2sys7f7dexcuajgoweudcqj2chfi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaxk2aqzlwmceugemqb6as6zzzfp5x3wtsv5gf4352abertaw5pr4

**Comment by MetaWaveInfo** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec3gm2ciqxaikl4f5y3pm5lyuxvf4shonx27rsnby7zxsaqdvg7as 
#### Address 
> f1hamzyd3tx4pdchop3l4hfeay5q6s427pxga6flq
#### Datacap Allocated
> 600.00TiB
#### Signer Address
> f1ktlkcxnmzxcdaoqfsunrg3vocfbmgv4n3mrn74a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec3gm2ciqxaikl4f5y3pm5lyuxvf4shonx27rsnby7zxsaqdvg7as

**Comment by kernelogic** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceatubf4yd6ii26jgtnmqvd372ziaftkxbq3vi4y3spmjblzk6qvac 
#### Address 
> f1hamzyd3tx4pdchop3l4hfeay5q6s427pxga6flq
#### Datacap Allocated
> 1.17PiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceatubf4yd6ii26jgtnmqvd372ziaftkxbq3vi4y3spmjblzk6qvac

**Comment by liyunzhi-666** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebdl5xx4xt7yhbl6hkjidkzqjjddvuwj6jnaxvy36vryxhegvuccy 
#### Address 
> f1hamzyd3tx4pdchop3l4hfeay5q6s427pxga6flq
#### Datacap Allocated
> 1.17PiB
#### Signer Address
> f1pszcrsciyixyuxxukkvtazcokexbn54amf7gvoq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebdl5xx4xt7yhbl6hkjidkzqjjddvuwj6jnaxvy36vryxhegvuccy

**Comment by fireflyHZ** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceafyhjna5vcj4s37g36doe2k652aokabmn37qipipdy7v4ke7qpxy 
#### Address 
> f1hamzyd3tx4pdchop3l4hfeay5q6s427pxga6flq
#### Datacap Allocated
> 1.17PiB
#### Signer Address
> f1fg6jkxsr3twfnyhdlatmq36xca6sshptscds7xa
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceafyhjna5vcj4s37g36doe2k652aokabmn37qipipdy7v4ke7qpxy

**Comment by swatchliu** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedutpl2i7i63sd4pmaib7voj6mwu5y4tgjvc2hjipsuny3ojwlzqq 
#### Address 
> f1hamzyd3tx4pdchop3l4hfeay5q6s427pxga6flq
#### Datacap Allocated
> 1.17PiB
#### Signer Address
> f1yh6q3nmsg7i2sys7f7dexcuajgoweudcqj2chfi
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedutpl2i7i63sd4pmaib7voj6mwu5y4tgjvc2hjipsuny3ojwlzqq

**Comment by filplus-checker** [comment]
## DataCap and CID Checker Report[^1]
 - Organization: `Beacon Project`
 - Client: `f1hamzyd3tx4pdchop3l4hfeay5q6s427pxga6flq`
### Storage Provider Distribution
The below table shows the distribution of storage providers that have stored data for this client.

If this is the first time a provider takes verified deal, it will be marked as `new`.

For most of the datacap application, below restrictions should apply.
 - Storage provider should not exceed 25% of total datacap.
 - Storage provider should not be storing duplicate data for more than 20%.
 - Storage provider should have published its public IP address.
 - All storage providers should be located in different regions.

⚠️ [f01887654](https://filfox.info/en/address/f01887654) has sealed 100.00% of total datacap.

⚠️ 77.50% of total deal sealed by [f01887654](https://filfox.info/en/address/f01887654) are duplicate data.

⚠️ All storage providers are located in the same region.

| Provider                                                    |              Location | Total Deals Sealed | Percentage | Unique Data | Duplicate Deals |
| :---------------------------------------------------------- | --------------------: | -----------------: | ---------: | ----------: | --------------: |
| [f01887654](https://filfox.info/en/address/f01887654)`new`  | Ashburn, Virginia, US |         449.94 TiB |    100.00% |  101.25 TiB |          77.50% |

![Provider Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/448/1671096944452.png)
### Deal Data Replication
The below table shows how each many unique data are replicated across storage providers.
- No more than 25% of unique data are stored with less than 4 providers.

⚠️ 100.00% of deals are for data replicated across less than 4 storage providers.

| Unique Data Size | Total Deals Made | Number of Providers | Deal Percentage |
| ---------------: | ---------------: | ------------------: | --------------: |
|       101.25 TiB |       449.94 TiB |                   1 |         100.00% |

![Replication Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/448/1671096944983.png)
### Deal Data Shared with other Clients
The below table shows how many unique data are shared with other clients.
Usually different applications owns different data and should not resolve to the same CID.

⚠️ CID sharing has been observed.

| Other Client                                                                                                          | Application                                                                                                   | Total Deals Affected | Unique CIDs |                                                                                 Verifier |
| :-------------------------------------------------------------------------------------------------------------------- | :------------------------------------------------------------------------------------------------------------ | -------------------: | ----------: | ---------------------------------------------------------------------------------------: |
| [f1rszqldzirsgganeah32zubr4r4qafwypuwaig2q](https://filfox.info/en/address/f1rszqldzirsgganeah32zubr4r4qafwypuwaig2q) | [Beacon Project](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/477)                 |           338.94 TiB |       1,209 | Project Beacon, 12 LDNs LDN # 444, 446, 447, 448, 474, 475, 476, 477, 479, 480, 481, 482 |
| [f1xtnkj5ti77f5gbzhclnpj3xt6e5dwhfzive2yca](https://filfox.info/en/address/f1xtnkj5ti77f5gbzhclnpj3xt6e5dwhfzive2yca) | [Beacon Project](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/482)                 |           149.06 TiB |         541 | Project Beacon, 12 LDNs LDN # 444, 446, 447, 448, 474, 475, 476, 477, 479, 480, 481, 482 |
| [f1avhqgmeazxzvylz34l26o3nlj2ywnzaviwns3dq](https://filfox.info/en/address/f1avhqgmeazxzvylz34l26o3nlj2ywnzaviwns3dq) | [87v5\-CarsonVideo](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/392)              |            24.50 TiB |         144 |                                                                          LDN v3 multisig |
| [f1l2hkjqfh5abpd5x6lxj4tjrphaa44pnumt5ms5i](https://filfox.info/en/address/f1l2hkjqfh5abpd5x6lxj4tjrphaa44pnumt5ms5i) | [Fly Brain Anatomy \- Slingshot](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/153) |            17.50 TiB |          66 |                                                                                LDN # 153 |
| [f1quofpadzcqlonmz7v3mv7dfqvm5hdztucdsjqsy](https://filfox.info/en/address/f1quofpadzcqlonmz7v3mv7dfqvm5hdztucdsjqsy) | [HENAN 863 SOFTWARE CO\., LTD](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/468)   |            15.44 TiB |          96 |                                                                          LDN v3 multisig |
| [f1zav4f4rak2yvbrq357z3whj224wn4dipl7eiesy](https://filfox.info/en/address/f1zav4f4rak2yvbrq357z3whj224wn4dipl7eiesy) | [Shanghai Zhixun](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/628)                |           192.00 GiB |           1 |                                                                          LDN v3 multisig |
| [f1ivsvpljx4ovp2tth73pllkxmumrudemks623iia](https://filfox.info/en/address/f1ivsvpljx4ovp2tth73pllkxmumrudemks623iia) | `TIS Inc. group`                                                                                              |           128.00 GiB |           2 |                                                                          LDN v3 multisig |
| [f1xyx3tvfoy7ue62oqdtcpud5ewcw2i7ctu4kyylq](https://filfox.info/en/address/f1xyx3tvfoy7ue62oqdtcpud5ewcw2i7ctu4kyylq) | [zhenshuai](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/332)                      |            64.00 GiB |           1 |                                                                                LDN # 332 |

[^1]: To manually trigger this report, add a comment with text `checker:manualTrigger`
