### ISSUE TITLE
[DataCap Application] Maxpic PhotoGraphic Studio

### ISSUE THREAD

**Issue by Maxpic-Studio** [filecoin-project/filecoin-plus-large-datasets#456]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Maxpic PhotoGraphic Studio
- Website / Social Media: https://www.maxpic.live/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 200TiB
- On-chain address for first allocation: f1zb6pgkktdbyy7zxfob6gripqxuc25ukf35cc7fq

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Maxpic PhotoGraphic Studio was established in 2016. It provides product photography, portrait photography, graphic design, web and social media board design, exhibition production, store window and set design, video shooting and production services to our clients.
Maxpic PhotoGraphic Studio has provided high quality commercial photography, video and design services to hundreds of companies over the years. The team at Maxpic PhotoGraphic Studio has the experience and flexibility to meet the needs of clients with meticulous attention to detail and perfection.
```

What is the primary source of funding for this project?
```
Our own account.
```

What other projects/ecosystem stakeholders is this project associated with?
```
We have no other stakeholders.
```

## Use-case details

Describe the data being stored onto Filecoin
```
The data is photos, videos and designs.
```

Where was the data in this dataset sourced from?
```
From our team or clients' request.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
![a1023](https://user-images.githubusercontent.com/106519851/176144823-0de14af9-6e3e-47e7-b5db-48fd53545c55.jpg)

https://user-images.githubusercontent.com/106519851/176144839-fa113a34-3de3-422a-aae2-cb4967a2c3b2.mp4


https://user-images.githubusercontent.com/106519851/176144960-c095cca7-c491-4ee2-9830-9c4655c6bff5.mp4

![b1014](https://user-images.githubusercontent.com/106519851/176145006-02539b0d-78b1-460d-923c-94c1217b2f40.jpg)
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Confirm.
```

What is the expected retrieval frequency for this data?
```
These data is stored as copies so that its frequency is every 1.5-2 years.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
We have a large quantity of data to keep constantly so it will take at least 3 years for first step.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Mainly Asia. 
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Offline data transferer is the best and safe way to use.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We plan on choosing those SPs via Github-Filecoin community. Based on their reputation.
```

How will you be distributing deals across storage providers?
```
We'll distribute deals with reference to the miner's capacity, under the request of community.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Our resources/funding are enough for making deals. We'd like community can support and approve our issue.
```

**Comment by UnionLabs2020** [comment]
Could you send an email with your official domain to filplus@fil.org to confirm your identity?

**Comment by Maxpic-Studio** [comment]
@UnionLabs2020 My colleague sent it just now.
![Maxpic email](https://user-images.githubusercontent.com/106519851/177107808-a554a5c4-bf9d-441f-a70f-1045a7580fb4.png)

**Comment by Sunnyiscoming** [comment]
@Maxpic-Studio 
1. Establishment time of Website is too short to prove that your organization was establlished from 2016.
2.Can you provide the proof of organization existence?

**Comment by Maxpic-Studio** [comment]
Our studio is from Nsway Advertisement. You can search it from this website. https://www.hongkongcompanylookup.com/companies/begedaghb/

> 1. 2.Can you provide the proof of organization existence?
Our old domain expired, so we replaced it with a new one and upgraded our website.

**Comment by Maxpic-Studio** [comment]
Our studio is from Nsway Advertisement. You can search it from this website. https://www.hongkongcompanylookup.com/companies/begedaghb/

> 1. Establishment time of Website is too short to prove that your organization was establlished from 2016.

Our old domain expired, so we replaced it with a new one and upgraded our website.

**Comment by galen-mcandrew** [comment]
## Datacap Request Trigger
#### Total DataCap requested 
> 5PiB
#### Expected weekly DataCap usage rate 
> 200TiB 
#### Client address
> f1zb6pgkktdbyy7zxfob6gripqxuc25ukf35cc7fq

**Comment by MRJAVAZHAO** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceawcxlq4q57ocnj3h4pagkl3key2nc3cik3xqwqee4wqi3kgpccrw 
#### Address 
> f1zb6pgkktdbyy7zxfob6gripqxuc25ukf35cc7fq
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f14gme3f52prtyzk6pblogrdd6b6ivp4swc6qmesi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceawcxlq4q57ocnj3h4pagkl3key2nc3cik3xqwqee4wqi3kgpccrw

**Comment by swatchliu** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebww3sygoteejhwacxvtlllngptw5cntx4hqv5ilnhfv57wzewmze 
#### Address 
> f1zb6pgkktdbyy7zxfob6gripqxuc25ukf35cc7fq
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1yh6q3nmsg7i2sys7f7dexcuajgoweudcqj2chfi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebww3sygoteejhwacxvtlllngptw5cntx4hqv5ilnhfv57wzewmze

**Comment by MRJAVAZHAO** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaah6kykeepp53jp6xbd64tkrb2wdruy22bcmmk4npg74isq6onyw 
#### Address 
> f1zb6pgkktdbyy7zxfob6gripqxuc25ukf35cc7fq
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f14gme3f52prtyzk6pblogrdd6b6ivp4swc6qmesi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaah6kykeepp53jp6xbd64tkrb2wdruy22bcmmk4npg74isq6onyw

**Comment by MatrixStorage** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaoj2cduev2bovkr5fpnhzz2ul5repawjcjknn7iuw5qncygi35vy 
#### Address 
> f1zb6pgkktdbyy7zxfob6gripqxuc25ukf35cc7fq
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1tbxqwjxfyv7swsdin4einirlsfquv3vnmlapley
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaoj2cduev2bovkr5fpnhzz2ul5repawjcjknn7iuw5qncygi35vy

**Comment by BigD-Exchange** [comment]
@Maxpic-Studio Hi! Great to see you have gotten approval for DataCap. If you are looking for reputable storage providers to store these data, please visit #bigdata-exchange on Filecoin Slack or reply here.

**Comment by 1475Notary** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedcxi6nhhj62cdyhnfpdcoaw6ha2zfmtt45nxtsdb6s5o62fth7dk 
#### Address 
> f1zb6pgkktdbyy7zxfob6gripqxuc25ukf35cc7fq
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1ofq4mngy7ggcp755pfquq2gphjjnlydolf6awtq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedcxi6nhhj62cdyhnfpdcoaw6ha2zfmtt45nxtsdb6s5o62fth7dk

**Comment by MetaWaveInfo** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb4le5pyrp7jstzaky5awh27inhxiddw7k4whsrs46qydx65eyis4 
#### Address 
> f1zb6pgkktdbyy7zxfob6gripqxuc25ukf35cc7fq
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1ktlkcxnmzxcdaoqfsunrg3vocfbmgv4n3mrn74a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb4le5pyrp7jstzaky5awh27inhxiddw7k4whsrs46qydx65eyis4

**Comment by swatchliu** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedm36m2ygexgtq4pmulinlcuopz3nbwtbsqqdfkrdy7jfzadngkbg 
#### Address 
> f1zb6pgkktdbyy7zxfob6gripqxuc25ukf35cc7fq
#### Datacap Allocated
> 1.56PiB
#### Signer Address
> f1yh6q3nmsg7i2sys7f7dexcuajgoweudcqj2chfi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedm36m2ygexgtq4pmulinlcuopz3nbwtbsqqdfkrdy7jfzadngkbg

**Comment by UnionLabs2020** [comment]
bafy2bzaceamey4u7dialtkdgdnewhdevuyrpyelg4svba5muxbopkfkthng6a

Approved.

**Comment by kernelogic** [comment]
@raghavrmadya this one probably need to manually remove the label StartSignDatacap since the last approval is a manual one.

**Comment by Maxpic-Studio** [comment]
Oh! Why are there so many errors about the bot or label? Can someone help us to fix it?

**Comment by 1475Notary** [comment]
Hi @Maxpic-Studio , I can help you to propose, but you need to find another notary to multisig.
Hope to bring you a better experience.

**Comment by Maxpic-Studio** [comment]
@1475Notary Thanks! 
I'll go for other notaries to help. @MRJAVAZHAO @MetaWaveInfo Notaries, can you give a hand?

**Comment by psh0691** [comment]
@Maxpic-Studio 
Notaries cannot sign in succession.

**Comment by filplus-checker** [comment]
## DataCap and CID Checker Report[^1]
 - Organization: `Maxpic PhotoGraphic Studio`
 - Client: `f1zb6pgkktdbyy7zxfob6gripqxuc25ukf35cc7fq`
### Storage Provider Distribution
The below table shows the distribution of storage providers that have stored data for this client.

If this is the first time a provider takes verified deal, it will be marked as `new`.

For most of the datacap application, below restrictions should apply.
 - Storage provider should not exceed 25% of total datacap.
 - Storage provider should not be storing duplicate data for more than 20%.
 - Storage provider should have published its public IP address.
 - All storage providers should be located in different regions.

⚠️ 89.96% of total deal sealed by [f01974746](https://filfox.info/en/address/f01974746) are duplicate data.

⚠️ [f01974746](https://filfox.info/en/address/f01974746) has unknown IP location.

⚠️ 71.14% of total deal sealed by [f01924350](https://filfox.info/en/address/f01924350) are duplicate data.

⚠️ 81.93% of total deal sealed by [f01844999](https://filfox.info/en/address/f01844999) are duplicate data.

⚠️ [f01844999](https://filfox.info/en/address/f01844999) has unknown IP location.

⚠️ 69.80% of total deal sealed by [f01924325](https://filfox.info/en/address/f01924325) are duplicate data.

⚠️ 24.84% of total deal sealed by [f01895891](https://filfox.info/en/address/f01895891) are duplicate data.

⚠️ 26.06% of total deal sealed by [f01896469](https://filfox.info/en/address/f01896469) are duplicate data.

⚠️ 47.36% of total deal sealed by [f01917257](https://filfox.info/en/address/f01917257) are duplicate data.

⚠️ 73.33% of total deal sealed by [f01924416](https://filfox.info/en/address/f01924416) are duplicate data.

⚠️ 46.87% of total deal sealed by [f01917208](https://filfox.info/en/address/f01917208) are duplicate data.

⚠️ 42.42% of total deal sealed by [f01889046](https://filfox.info/en/address/f01889046) are duplicate data.

⚠️ 47.30% of total deal sealed by [f01917241](https://filfox.info/en/address/f01917241) are duplicate data.

⚠️ 70.98% of total deal sealed by [f01880896](https://filfox.info/en/address/f01880896) are duplicate data.

⚠️ 88.57% of total deal sealed by [f01895783](https://filfox.info/en/address/f01895783) are duplicate data.

⚠️ 73.12% of total deal sealed by [f01880894](https://filfox.info/en/address/f01880894) are duplicate data.

⚠️ 72.06% of total deal sealed by [f01880898](https://filfox.info/en/address/f01880898) are duplicate data.

| Provider                                              |                 Location | Total Deals Sealed | Percentage | Unique Data | Duplicate Deals |
| :---------------------------------------------------- | -----------------------: | -----------------: | ---------: | ----------: | --------------: |
| [f01974746](https://filfox.info/en/address/f01974746) |                  Unknown |         679.59 TiB |     20.50% |   68.25 TiB |          89.96% |
| [f01924350](https://filfox.info/en/address/f01924350) | Singapore, Singapore, SG |         320.88 TiB |      9.68% |   92.59 TiB |          71.14% |
| [f01916487](https://filfox.info/en/address/f01916487) |         Seoul, Seoul, KR |         234.66 TiB |      7.08% |  217.56 TiB |           7.28% |
| [f01914977](https://filfox.info/en/address/f01914977) |    Ashburn, Virginia, US |         211.38 TiB |      6.38% |  202.13 TiB |           4.38% |
| [f01844999](https://filfox.info/en/address/f01844999) |                  Unknown |         209.97 TiB |      6.33% |   37.94 TiB |          81.93% |
| [f01924325](https://filfox.info/en/address/f01924325) | Singapore, Singapore, SG |         199.84 TiB |      6.03% |   60.34 TiB |          69.80% |
| [f01900713](https://filfox.info/en/address/f01900713) |         Seoul, Seoul, KR |         192.56 TiB |      5.81% |  192.56 TiB |           0.00% |
| [f01895715](https://filfox.info/en/address/f01895715) |         Seoul, Seoul, KR |         191.81 TiB |      5.79% |  191.81 TiB |           0.00% |
| [f01895891](https://filfox.info/en/address/f01895891) | Singapore, Singapore, SG |         184.97 TiB |      5.58% |  139.03 TiB |          24.84% |
| [f01896469](https://filfox.info/en/address/f01896469) | Singapore, Singapore, SG |         184.56 TiB |      5.57% |  136.47 TiB |          26.06% |
| [f01895928](https://filfox.info/en/address/f01895928) | Singapore, Singapore, SG |         184.50 TiB |      5.57% |  150.53 TiB |          18.41% |
| [f01917257](https://filfox.info/en/address/f01917257) |         Seoul, Seoul, KR |         140.63 TiB |      4.24% |   74.03 TiB |          47.36% |
| [f01924416](https://filfox.info/en/address/f01924416) | Singapore, Singapore, SG |          75.94 TiB |      2.29% |   20.25 TiB |          73.33% |
| [f01893290](https://filfox.info/en/address/f01893290) | Singapore, Singapore, SG |          50.97 TiB |      1.54% |   50.97 TiB |           0.00% |
| [f01917208](https://filfox.info/en/address/f01917208) |         Seoul, Seoul, KR |          42.94 TiB |      1.30% |   22.81 TiB |          46.87% |
| [f01889046](https://filfox.info/en/address/f01889046) |    Ashburn, Virginia, US |          42.88 TiB |      1.29% |   24.69 TiB |          42.42% |
| [f01917241](https://filfox.info/en/address/f01917241) |         Seoul, Seoul, KR |          41.69 TiB |      1.26% |   21.97 TiB |          47.30% |
| [f01880896](https://filfox.info/en/address/f01880896) | Singapore, Singapore, SG |          32.09 TiB |      0.97% |    9.31 TiB |          70.98% |
| [f01895783](https://filfox.info/en/address/f01895783) |     Boardman, Oregon, US |          32.00 TiB |      0.97% |    3.66 TiB |          88.57% |
| [f01880894](https://filfox.info/en/address/f01880894) | Singapore, Singapore, SG |          30.81 TiB |      0.93% |    8.28 TiB |          73.12% |
| [f01880898](https://filfox.info/en/address/f01880898) | Singapore, Singapore, SG |          30.53 TiB |      0.92% |    8.53 TiB |          72.06% |

![Provider Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/456/1671097019296.png)
### Deal Data Replication
The below table shows how each many unique data are replicated across storage providers.
- No more than 25% of unique data are stored with less than 4 providers.

⚠️ 99.40% of deals are for data replicated across less than 4 storage providers.

| Unique Data Size | Total Deals Made | Number of Providers | Deal Percentage |
| ---------------: | ---------------: | ------------------: | --------------: |
|         1.26 PiB |         2.29 PiB |                   1 |          70.69% |
|       130.19 TiB |       602.88 TiB |                   2 |          18.19% |
|        55.66 TiB |       348.81 TiB |                   3 |          10.52% |
|         3.25 TiB |        19.97 TiB |                   4 |           0.60% |

![Replication Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/456/1671097020022.png)
### Deal Data Shared with other Clients
The below table shows how many unique data are shared with other clients.
Usually different applications owns different data and should not resolve to the same CID.

⚠️ CID sharing has been observed.

| Other Client                                                                                                          | Application                                                                                                                | Total Deals Affected | Unique CIDs |        Verifier |
| :-------------------------------------------------------------------------------------------------------------------- | :------------------------------------------------------------------------------------------------------------------------- | -------------------: | ----------: | --------------: |
| [f1727w2vwjctfo7hflr5trgqkl3c7texh7pl4grzq](https://filfox.info/en/address/f1727w2vwjctfo7hflr5trgqkl3c7texh7pl4grzq) | [GMverse](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/365)                                     |           325.16 TiB |       3,734 | LDN v3 multisig |
| [f1rnwp6p5kx7pcwexpucoav6mmwz3rkxw5blrboyy](https://filfox.info/en/address/f1rnwp6p5kx7pcwexpucoav6mmwz3rkxw5blrboyy) | [MigoVideo](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/517)                                   |           322.97 TiB |       3,374 | LDN v3 multisig |
| [f1ki4cjk27ypzjsuzkvvqzs6xobaweuoxfdcnpqhy](https://filfox.info/en/address/f1ki4cjk27ypzjsuzkvvqzs6xobaweuoxfdcnpqhy) | [TimeQuant](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/385)                                   |           268.41 TiB |       4,096 | LDN v3 multisig |
| [f1muygjb5zowppbhr7wnmdreqdoiyyanfm7fe54dy](https://filfox.info/en/address/f1muygjb5zowppbhr7wnmdreqdoiyyanfm7fe54dy) | [MappingFunk Protocol ](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/374)                       |           265.66 TiB |       2,427 | LDN v3 multisig |
| [f1dx7ljly4vmk5x2bn5ng4jpbqnuvozrz2phw42qy](https://filfox.info/en/address/f1dx7ljly4vmk5x2bn5ng4jpbqnuvozrz2phw42qy) | [CoinPhD](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/364)                                     |           257.78 TiB |       3,768 | LDN v3 multisig |
| [f1vtcetpapwwyka6txwqjwymsa67npdfilbkwh64a](https://filfox.info/en/address/f1vtcetpapwwyka6txwqjwymsa67npdfilbkwh64a) | [Chimay](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/397)                                      |           140.19 TiB |       2,049 | LDN v3 multisig |
| [f1einobkrjcjk6gfc5ov6663vrri75hwdsjfs6pmq](https://filfox.info/en/address/f1einobkrjcjk6gfc5ov6663vrri75hwdsjfs6pmq) | [Cansoti](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/640)                                     |           109.31 TiB |       1,221 | LDN v3 multisig |
| [f1ajdk7e6ex7fvtjtydzgys47bcg7jub2baucun7y](https://filfox.info/en/address/f1ajdk7e6ex7fvtjtydzgys47bcg7jub2baucun7y) | [Ruikuyun Information Technology Co\., Ltd](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/529)   |           101.94 TiB |       1,357 | LDN v3 multisig |
| [f1bb2z36lpq3pnwiiowiraagpzqnpow4bonjacx7a](https://filfox.info/en/address/f1bb2z36lpq3pnwiiowiraagpzqnpow4bonjacx7a) | [Hola Space](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/362)                                  |            93.53 TiB |       1,343 | LDN v3 multisig |
| [f1clwd2dooy2cflfilhzeq2ycl544b3heqsiwhjrq](https://filfox.info/en/address/f1clwd2dooy2cflfilhzeq2ycl544b3heqsiwhjrq) | [FiboAI](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/349)                                      |            88.81 TiB |       1,187 | LDN v3 multisig |
| [f1quofpadzcqlonmz7v3mv7dfqvm5hdztucdsjqsy](https://filfox.info/en/address/f1quofpadzcqlonmz7v3mv7dfqvm5hdztucdsjqsy) | [HENAN 863 SOFTWARE CO\., LTD](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/468)                |            81.81 TiB |       1,294 | LDN v3 multisig |
| [f1u522dt3zabkgbxxzecl77wgv473yvpecxh6t6zq](https://filfox.info/en/address/f1u522dt3zabkgbxxzecl77wgv473yvpecxh6t6zq) | [Huifan livestream](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/407)                           |            62.69 TiB |         969 | LDN v3 multisig |
| [f1ffr7uhq7mszotfdybexcnl4i7xw5tqyp5fhqy3y](https://filfox.info/en/address/f1ffr7uhq7mszotfdybexcnl4i7xw5tqyp5fhqy3y) | [MyTrade Technology Limited](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/386)                  |            57.47 TiB |         808 | LDN v3 multisig |
| [f14abwn2goturifmt27s2bssoe3fup2b3npkgfzui](https://filfox.info/en/address/f14abwn2goturifmt27s2bssoe3fup2b3npkgfzui) | [KONGFU VR](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/372)                                   |            33.09 TiB |         284 | LDN v3 multisig |
| [f17qd6x3leh5pa7vh6ewdaed7qhbn2mgofrokuayy](https://filfox.info/en/address/f17qd6x3leh5pa7vh6ewdaed7qhbn2mgofrokuayy) | [Drust](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/427)                                       |            21.50 TiB |         317 | LDN v3 multisig |
| [f1f5edx6ofn3lf6rk3yfpldbi2pzgq2egoyu6ubpi](https://filfox.info/en/address/f1f5edx6ofn3lf6rk3yfpldbi2pzgq2egoyu6ubpi) | [Samdata Trade](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/382)                               |            19.69 TiB |         275 | LDN v3 multisig |
| [f1avhqgmeazxzvylz34l26o3nlj2ywnzaviwns3dq](https://filfox.info/en/address/f1avhqgmeazxzvylz34l26o3nlj2ywnzaviwns3dq) | [87v5\-CarsonVideo](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/392)                           |             8.31 TiB |         156 | LDN v3 multisig |
| [f1jdmx2cuswzjlt4pnsv3t7ipmesywzxsg6q56a2a](https://filfox.info/en/address/f1jdmx2cuswzjlt4pnsv3t7ipmesywzxsg6q56a2a) | [Raysun Radar Electronic Technology Co\.,Ltd](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/884) |             5.00 TiB |          49 | LDN v3 multisig |
| [f1dwhevm3p2slu6itmkssznscmpkpltdiztprnpya](https://filfox.info/en/address/f1dwhevm3p2slu6itmkssznscmpkpltdiztprnpya) | [Hiscene](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/548)                                     |             1.81 TiB |           6 | LDN v3 multisig |
| [f1tivtdkq34mnfzso63wrr2xh6r2zo7aebao4jfla](https://filfox.info/en/address/f1tivtdkq34mnfzso63wrr2xh6r2zo7aebao4jfla) | `China travel service(HongKong) limited`                                                                                   |           736.00 GiB |           2 | LDN v3 multisig |
| [f1xyx3tvfoy7ue62oqdtcpud5ewcw2i7ctu4kyylq](https://filfox.info/en/address/f1xyx3tvfoy7ue62oqdtcpud5ewcw2i7ctu4kyylq) | [zhenshuai](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/332)                                   |           480.00 GiB |           6 |       LDN # 332 |
| [f1dpgqn57cl5wqijiyv3256nids2ox3fms2mg3oay](https://filfox.info/en/address/f1dpgqn57cl5wqijiyv3256nids2ox3fms2mg3oay) | [All Blue](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/389)                                    |           256.00 GiB |           2 | LDN v3 multisig |

[^1]: To manually trigger this report, add a comment with text `checker:manualTrigger`

**Comment by galen-mcandrew** [comment]
@panges2 sounds like maybe some label issues here? Need to investigate and see where this should be labeled (ready to sign, start sign, or granted?)
