### ISSUE TITLE
[DataCap Application] Missnami

### ISSUE THREAD

**Issue by aries98** [filecoin-project/filecoin-plus-large-datasets#463]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Missnami
- Website / Social Media: https://missnami.com/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 3PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100TiB
- On-chain address for first allocation: f1sfs2m6uvdn3zlzn4zchtmytsda3escmf3xiamty

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Missnami is a company focused on eco-friendly skin care, made with patented technology, derived from nature and free of harmful ingredients. Bacterial ability of 650 species of microbe related to human body (SILVER), Made with 99.99% colloidal silver for the first time in the country (KOREA), Eco-friendly soap that is effective in removing bacteria and odors (SILVER ION). Missnami has always adhered to the belief of "PRESERVATIV-FREE, SURFACTANT-FREE, FLUORESCENT BLEACHING-FREE, ARTIFICAL FRAGRANCE-FREE, OXIDIZER-FREE", and carefully crafted skin care products and cleansing products. There are many fans.

Missnami has its own R&D team, production base, and online sales platform. It is committed to promoting environmentally friendly skin care and striving for a green and beautiful earth.
```

What is the primary source of funding for this project?
```
The company has made a profit, and the main source of funds is the company's own funds.
```

What other projects/ecosystem stakeholders is this project associated with?
```
No stakeholders, we are independent.
```

## Use-case details

Describe the data being stored onto Filecoin
```
The data stored on Filecoin is all about production data, R&D data, sales data.
```

Where was the data in this dataset sourced from?
```
Mainly from the data generated during our research and development, design, transportation and sales.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://drive.google.com/drive/folders/1dKTYInS_6IbahvAxg-CZ3o_M5PQME8Ts
https://drive.google.com/drive/folders/1k0ZlcKvElSuZrO3pjUDm6pijfqdtEnCi
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Confirm.
```

What is the expected retrieval frequency for this data?
```
This is our backup data, expected to be retrieved every 6-9 months.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
about 12 months.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
We do not limit the storage area, we welcome global Miners to store our data to achieve true distributed storage.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Online transmission is simpler and faster, so we mainly focus on online transmission, and if necessary, we will also conduct offline transmission.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We will select miners with good reputation, trustworthiness, and experience in verifying data to conduct transactions.
```

How will you be distributing deals across storage providers?
```
We will find high-quality miners through slack, GitHub and other channels, distribute to miners in an even proportion. Also, each miner won’t be allocated more than 30% of our datacap.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, I do.
```

**Comment by Sunnyiscoming** [comment]
@aries98 
Can you figure out what is the relationship between you and https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/466. 
1. Why this organization use your data sample?
https://drive.google.com/drive/folders/1dKTYInS_6IbahvAxg-CZ3o_M5PQME8Ts
https://drive.google.com/drive/folders/1k0ZlcKvElSuZrO3pjUDm6pijfqdtEnCi
2. The address for them to apply for datacap(f1npjdixiorcwwybbgrrfm4ekkk6udddhvnwpkcoy) received token from the address you applied (f1sfs2m6uvdn3zlzn4zchtmytsda3escmf3xiamty)

**Comment by aries98** [comment]
1. Missnami and LSware are partners. we learn from eath oher, and they've made a mistake to use our data sample. 
2. The transaction is because we were testing if the address was available.

**Comment by aries98** [comment]
> @aries98 Can you figure out what is the relationship between you and #466.
> 
> 1. Why this organization use your data sample?
>    https://drive.google.com/drive/folders/1dKTYInS_6IbahvAxg-CZ3o_M5PQME8Ts
>    https://drive.google.com/drive/folders/1k0ZlcKvElSuZrO3pjUDm6pijfqdtEnCi
> 2. The address for them to apply for datacap(f1npjdixiorcwwybbgrrfm4ekkk6udddhvnwpkcoy) received token from the address you applied (f1sfs2m6uvdn3zlzn4zchtmytsda3escmf3xiamty)

1. Missnami and LSware are partners. we learn from eath oher, and they've made a mistake to use our data sample. 
2. The transaction is because we were testing if the address was available.

**Comment by Sunnyiscoming** [comment]
Have you found any storage provider? Can you list them?

**Comment by raghavrmadya** [comment]
no reply
