### ISSUE TITLE
[DataCap Application] <The New Ads>

### ISSUE THREAD

**Issue by Gonzalo1987** [filecoin-project/filecoin-plus-large-datasets#464]
# Large Dataset Notary Application
To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: The New Ads
- Website / Social Media: https://thenewads.com
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5 PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100 TiB
- On-chain address for first allocation: f1tza7y76ta5zogx5hdifsfdlyjh354xzb2awr33y
- Type: Custom Notary

## Project details
Share a brief history of your project and organization
```
The New Ads is an advertising agency specializing in digital signage, app development, social media, and audiovisual content creation. 
```

What is the primary source of funding for this project?
```
Our revenue flows are the services provided to our clients.
```

What other projects/ecosystem stakeholders is this project associated with?
```
The New Ads is part of the Workanda Group. Workanda is made up of a group of companies from La Rioja, Spain, to offer a comprehensive service through IT services and 360º Communication. Custom programming and software, web development and training, audiovisual and design services.
```

## Use-case details
Describe the data being stored onto Filecoin
```
The dataset provided consists of different forms of data (mainly video) from our client list which extends to more than 1,400. From the Spanish football team Barca F.C, Deutsche Bank, Volkswagen, and Opel, to The Parliament of “La Rioja” which is a public institution in Spain.
```

Where was the data in this dataset sourced from?
```
Own Servers. 
```

Can you share a sample of the data? A link to file would work.
```
http://gofile.me/3XZGR/lZ79X3MRp
http://gofile.me/3XZGR/Qft0AGwzU
http://gofile.me/3XZGR/qLrjekXYk
http://gofile.me/3XZGR/0gbiaYqRW
http://gofile.me/3XZGR/qYXd5MWX5
```

Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes, since the dataset will be encrypted.
```

What is the expected retrieval frequency for this data?
```
There will not be much retrieval frequency of the data. Only if needed to do a revision of a given file. 
```

For how long do you plan to keep this dataset stored on Filecoin?
```
One and a half years with possible renewal.
```

## DataCap allocation plan
In which geographies (countries, regions) do you plan on making storage deals?
```
US and other countries as well
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Files will be hosted online and able to be pulled by storage providers over the internet.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.

Choosing reputable providers in the community via Filecoin slack or ranking sites. Also looking for SPs that are able to comply with GDPR.
```


How will you be distributing deals across storage providers?
```
Hosted online (like the sample links provided) for the SPs to download
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?

```
We have adequate resources and support. 
```

**Comment by Kevin-PiKNiK** [comment]
@Gonzalo1987 : This is very cool and thanks for your interest in the Filecoin network. You say that your company is part of a group of companies from Spain. However, your request mentions storing in the United States among "other countries". I would like to **confirm that this is intentional and without sovereignty restrictions**. Thanks.

**Comment by Gonzalo1987** [comment]
Hello @Kevin-PikNik! We confirm that our intention is to store the data across different places without sovereignty restrictions. In our opinion, one of the main advantages of the Filecoin Network is to diversify risk choosing differents regions and countries. Thanks.

**Comment by Kakkouii** [comment]
@Gonzalo1987 Cool idea and I've taken a look at your application. There's one thing I'd like to figure out. You confirmed that it's a public dataset since it's encrypted. How can encrypted data be public?

**Comment by Fenbushi-Filecoin** [comment]
We can support the application. Just curious, if the data is already encrypted on your side, is it necessary for SPs to comply with GDPR?

**Comment by Gonzalo1987** [comment]
> @Gonzalo1987 Cool idea and I've taken a look at your application. There's one thing I'd like to figure out. You confirmed that it's a public dataset since it's encrypted. How can encrypted data be public?

Hello @Kakkouii! We should've been clearer. What we mean is that the data is publicly retrievable but encrypted. By storing on the Filecoin network, it is inherently public for anyone to retrieve but will be encrypted in order to comply with our company's privacy requirements and GDPR.

> We can support the application. Just curious, if the data is already encrypted on your side, is it necessary for SPs to comply with GDPR?

Hi @Fenbushi-Filecoin! Yes, every organization (SPs in this case) that stores data from European institutions or individuals will need to comply with GDPR. But encryption is called out in Article 32 as an “appropriate technical and organizational measure” of security. For this reason, we will keep the keys for the encrypted data. This means the SPs does not need to be too concerned with GDPR compliance as we will have control of the data. Here is a link for more info! https://gdpr.eu/faq/.

**Comment by Gonzalo1987** [comment]
Hello @galen-mcandrew! What are the next steps now that we have support from one notary (@Fenbushi-Filecoin)?

**Comment by raghavrmadya** [comment]
any updates?

**Comment by Gonzalo1987** [comment]
Yes! Yesterday we posted the following message on the notary governance issue: 

https://github.com/filecoin-project/notary-governance/issues/573#issuecomment-1217757614

We got the notaries backing our application, and a data distribution plan complying with geographic diversification.

**Comment by Gonzalo1987** [comment]
> any updates?

Yes! Yesterday we posted the following message on the notary governance issue:

https://github.com/filecoin-project/notary-governance/issues/573#issuecomment-1217757614

We got the notaries backing our application, and a data distribution plan complying with geographic diversification.

**Comment by raghavrmadya** [comment]
@Gonzalo1987, thanks. We will go ahead and create a custom multisig between the notaries listed in #573.

**Comment by Gonzalo1987** [comment]
> @Gonzalo1987, thanks. We will go ahead and create a custom multisig between the notaries listed in #573.

Hello @raghavrmadya. I see that the issue has the CustomLDN label. What are the next steps to keep moving forward in the process?

**Comment by Gonzalo1987** [comment]
Hello @raghavrmadya @sunnyiscoming @galen-mcandrew! Any updates on the creation of the custom multisig? Is there anything that we can do to accelerate the process?

**Comment by Carohere** [comment]
Hi @Gonzalo1987, I understand the need to encrypt data for client privacy. But as @kernelogic mentioned in your proposal, it's hard to verify their willingness if it's already impossible to get them each authorized for data samples. Is there any way you can prove that the companies in your client list authorized New Ads to store their data here?

**Comment by jamerduhgamer** [comment]
Hi @Carohere, I believe a few of the notaries besides Kernelogic have actually met with the client themselves to perform the KYC process as mentioned in the corresponding proposal https://github.com/filecoin-project/notary-governance/issues/573.

**Comment by Carohere** [comment]
@jamerduhgamer yes james. i'm aware that the project has already gotten support from five notaries. my point here is whether the applicant needs to address queries from other community members after that. cc @Kevin-FF-USA, could you help me on this? thanks.

**Comment by dkkapur** [comment]
## Datacap Request Trigger
#### Total DataCap requested 
> 5 PiB
#### Expected weekly DataCap usage rate 
> 100 TiB 
#### Client address
> f1tza7y76ta5zogx5hdifsfdlyjh354xzb2awr33y

**Comment by xinaxu** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceam3qq3lw5byvorsjfazc5443vsrkoy32oyssbsky4ukrfqbb2kjw 
#### Address 
> f1tza7y76ta5zogx5hdifsfdlyjh354xzb2awr33y
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1k3ysofkrrmqcot6fkx4wnezpczlltpirmrpsgui
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceam3qq3lw5byvorsjfazc5443vsrkoy32oyssbsky4ukrfqbb2kjw

**Comment by xingjitansuo** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacect47i5zh424qshhhzig5tpxxdf2hkswcwlhuxatuomd3flkjto6q 
#### Address 
> f1tza7y76ta5zogx5hdifsfdlyjh354xzb2awr33y
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1a2lia2cwwekeubwo4nppt4v4vebxs2frozarz3q
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacect47i5zh424qshhhzig5tpxxdf2hkswcwlhuxatuomd3flkjto6q

**Comment by Carohere** [comment]
Hi @gonzalo1987, appreciate your time. I absolutely get the point of encryption.
> From the Spanish football team Barca F.C, Deutsche Bank, Volkswagen, and Opel, to The Parliament of “La Rioja” which is a public institution in Spain.

My other concern is the relationship between the 1400 clients and your organization. Is there any way you can provide the partnership between those companies and New ads? Btw about La Rioja, do you mean [La Rioja 25](https://www.larioja.com/)？

**Comment by Gonzalo1987** [comment]
Hi @Carohere! In our application we have provided 5 sample links where you will be able to find files from Volkswagen, Barcelona FC, Opel, Deutsche Bank and the Parlament of La Rioja. I can’t imagine a better proof than that. It’s important to remember that they are not our partners, they are our clients. 

La Rioja is an autonomous community within Spain, like an state in the US. Each autonomous community has its Parlament and Public Institutions, and The New Ads have done several project with them. We don’t know anything about the link you are mentioning.

**Comment by Carohere** [comment]
@Gonzalo1987 fair enough. Oftentimes, many applicants are unable to prove their connection to the data entity which is why I asked the question in the first place. Although I still think it is not enough that encrypted data only needs the support of five notaries. But it looks like that's the current consensus until the criteria for encrypted data review is strengthened. Sorry for the inconvenience and thanks for your time.

**Comment by bmcnabb25** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedpolxpfvpxdbzp4ecxm5jc6f733cpsbspefuzlydp2bwwextoeqs 
#### Address 
> f1tza7y76ta5zogx5hdifsfdlyjh354xzb2awr33y
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1jqk7xok5kautet2knhwlg74jvcfbrqlj47kbp2i
#### Id
> c5ee8d5b-f1fe-48ef-a9cb-646ecb830fe4
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedpolxpfvpxdbzp4ecxm5jc6f733cpsbspefuzlydp2bwwextoeqs

**Comment by Fenbushi-Filecoin** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedan47fdetovzzmpgvc5uy5ktqhtsk7ochir4cwci3sblgbvdlylc 
#### Address 
> f1tza7y76ta5zogx5hdifsfdlyjh354xzb2awr33y
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1yqydpmqb5en262jpottko2kd65msajax7fi4rmq
#### Id
> c5ee8d5b-f1fe-48ef-a9cb-646ecb830fe4
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedan47fdetovzzmpgvc5uy5ktqhtsk7ochir4cwci3sblgbvdlylc

**Comment by BigD-Exchange** [comment]
@Gonzalo1987 Hi! Great to see you have gotten approval for DataCap. If you are looking for storage providers to store these data or have any questions, please visit #bigdata-exchange on Filecoin Slack or reply here. 

We have strong demand from a diverse group of SPs, who are actively looking to onboard more data.

**Comment by xinaxu** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedsadp4qm4mdn423baxfboks7aaygvfprbsmyz2cua3dajwofhxde 
#### Address 
> f1tza7y76ta5zogx5hdifsfdlyjh354xzb2awr33y
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1k3ysofkrrmqcot6fkx4wnezpczlltpirmrpsgui
#### Id
> e7ea47cb-c071-4faf-932b-5e62f06a993a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedsadp4qm4mdn423baxfboks7aaygvfprbsmyz2cua3dajwofhxde

**Comment by xingjitansuo** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecrvqulbucafsbaqm2ra3g6q3yyciswcnjupnm3xvdl3a67yttx76 
#### Address 
> f1tza7y76ta5zogx5hdifsfdlyjh354xzb2awr33y
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1a2lia2cwwekeubwo4nppt4v4vebxs2frozarz3q
#### Id
> e7ea47cb-c071-4faf-932b-5e62f06a993a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecrvqulbucafsbaqm2ra3g6q3yyciswcnjupnm3xvdl3a67yttx76

**Comment by filplus-checker** [comment]
## DataCap and CID Checker Report[^1]
 - Organization: `The New Ads`
 - Client: `f1tza7y76ta5zogx5hdifsfdlyjh354xzb2awr33y`
### Storage Provider Distribution
The below table shows the distribution of storage providers that have stored data for this client.

If this is the first time a provider takes verified deal, it will be marked as `new`.

For most of the datacap application, below restrictions should apply.
 - Storage provider should not exceed 25% of total datacap.
 - Storage provider should not be storing duplicate data for more than 20%.
 - Storage provider should have published its public IP address.
 - All storage providers should be located in different regions.

⚠️ [f01927134](https://filfox.info/en/address/f01927134) has sealed 50.90% of total datacap.

⚠️ [f01900409](https://filfox.info/en/address/f01900409) has sealed 48.37% of total datacap.

| Provider                                                    |                    Location | Total Deals Sealed | Percentage | Unique Data | Duplicate Deals |
| :---------------------------------------------------------- | --------------------------: | -----------------: | ---------: | ----------: | --------------: |
| [f01927134](https://filfox.info/en/address/f01927134)       |       Las Vegas, Nevada, US |          91.42 TiB |     50.90% |   90.48 TiB |           1.03% |
| [f01900409](https://filfox.info/en/address/f01900409)`new`  |   San Diego, California, US |          86.89 TiB |     48.37% |   86.02 TiB |           1.01% |
| [f01884351](https://filfox.info/en/address/f01884351)`new`  |           Dallas, Texas, US |         768.00 GiB |      0.42% |  768.00 GiB |           0.00% |
| [f01857342](https://filfox.info/en/address/f01857342)`new`  |       Detroit, Michigan, US |         544.00 GiB |      0.30% |  544.00 GiB |           0.00% |
| [f01154023](https://filfox.info/en/address/f01154023)       | Sydney, New South Wales, AU |          32.00 GiB |      0.02% |   32.00 GiB |           0.00% |

![Provider Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/464/1671097060162.png)
### Deal Data Replication
The below table shows how each many unique data are replicated across storage providers.
- No more than 25% of unique data are stored with less than 4 providers.

⚠️ 100.00% of deals are for data replicated across less than 4 storage providers.

| Unique Data Size | Total Deals Made | Number of Providers | Deal Percentage |
| ---------------: | ---------------: | ------------------: | --------------: |
|        23.63 TiB |        23.72 TiB |                   1 |          13.20% |
|        75.92 TiB |       153.53 TiB |                   2 |          85.47% |
|       800.00 GiB |         2.38 TiB |                   3 |           1.32% |

![Replication Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/464/1671097060711.png)
### Deal Data Shared with other Clients
The below table shows how many unique data are shared with other clients.
Usually different applications owns different data and should not resolve to the same CID.

✔️ No CID sharing has been observed.

[^1]: To manually trigger this report, add a comment with text `checker:manualTrigger`

**Comment by jamerduhgamer** [comment]
Just a heads up that we are currently working on getting more SPs to seal the replicas of this dataset, you can see this in the filplus-checker-apps comment with the "new" miner IDs.

**Comment by Fenbushi-Filecoin** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedbzrrbdls2jpaolabts5rokcfgk62docuzcshqljzvdqrorgf7hk 
#### Address 
> f1tza7y76ta5zogx5hdifsfdlyjh354xzb2awr33y
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1yqydpmqb5en262jpottko2kd65msajax7fi4rmq
#### Id
> 7f778267-a7f5-4dc9-b335-0389403fe1c9
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedbzrrbdls2jpaolabts5rokcfgk62docuzcshqljzvdqrorgf7hk

**Comment by cryptowhizzard** [comment]
> Just a heads up that we are currently working on getting more SPs to seal the replicas of this dataset, you can see this in the filplus-checker-apps comment with the "new" miner IDs.

Hi James,

Can you please consider storing some of the data on a second continent? Europe / Australia / Asia ......
If so, then i am open for signing on this one.

**Comment by lvschouwen** [comment]
checker:manualTrigger

**Comment by jamerduhgamer** [comment]
Hi @cryptowhizzard, yes we have plans on storing a replica with the Holon team in Australia! I believe they just finish setting up an SP and will start receiving deals in the next datacap tranche!

**Comment by jamerduhgamer** [comment]
Curious why the bot says it should be a 400 TiB tranche this time but Fenbushi's proposal was only for 100 TiBs.

**Comment by cryptowhizzard** [comment]
> Hi @cryptowhizzard, yes we have plans on storing a replica with the Holon team in Australia! I believe they just finish setting up an SP and will start receiving deals in the next datacap tranche!

Sounds good then. Thanks for the info!

**Comment by cryptowhizzard** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceczukmykazdigfebl6bivn73w7ietvgg36siduomfvlbfbg5b2x44 
#### Address 
> f1tza7y76ta5zogx5hdifsfdlyjh354xzb2awr33y
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1krmypm4uoxxf3g7okrwtrahlmpcph3y7rbqqgfa
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceczukmykazdigfebl6bivn73w7ietvgg36siduomfvlbfbg5b2x44

**Comment by cryptowhizzard** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebdp6rpcnualdydhhcyll3ug4gfvxcu55p43wckco3r27sqpy22k4 
#### Address 
> f1tza7y76ta5zogx5hdifsfdlyjh354xzb2awr33y
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1krmypm4uoxxf3g7okrwtrahlmpcph3y7rbqqgfa
#### Id
> aff503cb-ea88-403f-93d2-a0d396a19830
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebdp6rpcnualdydhhcyll3ug4gfvxcu55p43wckco3r27sqpy22k4

**Comment by jamerduhgamer** [comment]
Hi @Gonzalo1987, can we get this LDN re-opened?

**Comment by jamerduhgamer** [comment]
Hi @galen-mcandrew, @raghavrmadya, can we get this LDN re-opened? We took some time to resume sealing and just ran out of datacap again recently.

**Comment by NiwanDao** [comment]
checker:manualTrigger

**Comment by NiwanDao** [comment]
The report looks good, and I will support this tranche.

**Comment by NiwanDao** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceazgbx2wfifmlobvnmtjfg6dlhlhpm4swqkkdfaxukj64cdf5jnq4 
#### Address 
> f1tza7y76ta5zogx5hdifsfdlyjh354xzb2awr33y
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1a2lia2cwwekeubwo4nppt4v4vebxs2frozarz3q
#### Id
> cdfa39a5-ec88-413c-a45b-f08f2ddb7128
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceazgbx2wfifmlobvnmtjfg6dlhlhpm4swqkkdfaxukj64cdf5jnq4

**Comment by PluskitOfficial** [comment]
checker:manualTrigger

**Comment by PluskitOfficial** [comment]
>  Deal Data ReplicationOverall HTTP retrieval success rate: 0.52%
> Overall Bitswap retrieval success rate: 0.79%

Hi, @Gonzalo1987 could you please explain why these two parts have such a low success rate?

**Comment by jamerduhgamer** [comment]
Hi @PluskitOfficial, I took a look at all of the miner IDs to see what the retrieval issues were.

f01998317 - Reached out to the SP, they are looking into it.
f0763337 - Had an issue with its peer ID on-chain, I reached out to the SP and I believe this has been resolved.
f01857342 - Has decent success rate
f01900409 - SP is no longer active

f01165233, f01154023 and f01165179 all belong to one SP that is no longer sealing and have their Boost nodes turned off.

For f01927134, f01884351 and f02022254, I see in the retrieval report that the main error is "protocol not supported", any idea what could be the main cause for these errors so I can relate that to the SPs?

**Comment by jamerduhgamer** [comment]
checker:manualTrigger

**Comment by jamerduhgamer** [comment]
Hello! Still looking for notaries to sign datacap.

**Comment by cryptowhizzard** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacea4rasrqds4qprk34y5v33ewir2n22d7doqzos5ehsojeyzuc57pw 
#### Address 
> f1tza7y76ta5zogx5hdifsfdlyjh354xzb2awr33y
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1krmypm4uoxxf3g7okrwtrahlmpcph3y7rbqqgfa
#### Id
> cdfa39a5-ec88-413c-a45b-f08f2ddb7128
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacea4rasrqds4qprk34y5v33ewir2n22d7doqzos5ehsojeyzuc57pw

**Comment by jamerduhgamer** [comment]
Comment to keep LDN open. Sealing has been on-going.

**Comment by jamerduhgamer** [comment]
Comment to keep LDN open.

**Comment by Sunnyiscoming** [comment]
Hello, @Gonzalo1987 per the https://github.com/filecoin-project/notary-governance/issues/922 for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

This information will be reviewed by Fil+ Governance team to confirm validity and then the application will be allowed to move forward for additional notary review.

**Comment by jamerduhgamer** [comment]
Comment to keep LDN open.

**Comment by jamerduhgamer** [comment]
Hello @dkkapur, can we get this LDN re-opened?

**Comment by jamerduhgamer** [comment]
@simonkim0515 or @Kevin-FF-USA, are you also able to help with getting this LDN re-opened?
