### ISSUE TITLE
[DataCap Application] LSware

### ISSUE THREAD

**Issue by zvooo** [filecoin-project/filecoin-plus-large-datasets#466]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name:  LSware
- Website / Social Media: lsware.com
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 3PIB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100TIB
- On-chain address for first allocation: f1npjdixiorcwwybbgrrfm4ekkk6udddhvnwpkcoy

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Based on the company’s concept of “client exists to provide systems that can be used in a more free environment”, LSware has built a portfolio of four areas in compliance, availability, protect, and security(CAPS). We also strive to meet our customers’ needs and improve the level of customer satisfaction in the specialized areas of the system’s construction and operation services.

In addition, based on the security services information accumulated over the years, Omniguard(Server), which includes SecuMS (Continuous Security Vulnerability Assessment System), UPV (Account Management System), UAC (access control), UCC Session Logging & Command Control), modules to enhance the overall security level of IT infrastructure and maximize availability security solution to protect valuable information resources of customers both inside and outside the world. We have partnered with Symantec, one of the world's leading information security companies, and leading solution vendors at home and abroad to provide proven information protection solutions and technical support services

We develop and supply FOSSGuard, which can be free from license disputes and check information about the licensing of open source software, and we are pursuing industrial drones that have high potential in many industries.

Not only we protect information but also doing our best to create general trends of IT technology by going through various projects for government agencies and development projects. We will do our best every day to become a leader in the field of information security solutions for the purpose of a mission for our customers.
```

What is the primary source of funding for this project?
```
Company account.
```

What other projects/ecosystem stakeholders is this project associated with?
```
None.
```

## Use-case details

Describe the data being stored onto Filecoin
```
LSware's sales data, R&D data.
```

Where was the data in this dataset sourced from?
```
The data comes from the data provided by the company's R&D department, the customer data obtained by the sales department, and the service data of the after-sales department.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://drive.google.com/drive/folders/1dKTYInS_6IbahvAxg-CZ3o_M5PQME8Ts
https://drive.google.com/drive/folders/1k0ZlcKvElSuZrO3pjUDm6pijfqdtEnCi
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Confirm.
```

What is the expected retrieval frequency for this data?
```
Expected to be about 1 year.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
about 24 months.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
We do not limit the storage area, we welcome global Miners to store our data to achieve true distributed storage.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Both online and offline.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We will select miners with good reputation, trustworthiness, and experience in verifying data to conduct transactions.
```

How will you be distributing deals across storage providers?
```
We want to be able to allocate DataCap to as many storage providers as possible, We will choose more stable and secure storage suppliers first, and then allocate according to the allocation rules on this basis.   
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
We do.
```

**Comment by Kakkouii** [comment]
1. I can't find any relationship between the data sample and your company. An Internet security company with some random cosmetics pictures&videos?
2. The data samples per se are completely same as those in #463, which I believe the brand name on those materials belong  to #463.

**Comment by Sunnyiscoming** [comment]
@zvooo 
Can you figure out what is the relationship between you and https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/463.

Why this organization use your data sample?
https://drive.google.com/drive/folders/1dKTYInS_6IbahvAxg-CZ3o_M5PQME8Ts
https://drive.google.com/drive/folders/1k0ZlcKvElSuZrO3pjUDm6pijfqdtEnCi
The address for applying for datacap(f1npjdixiorcwwybbgrrfm4ekkk6udddhvnwpkcoy) sent token from the address #463  applied (f1sfs2m6uvdn3zlzn4zchtmytsda3escmf3xiamty)

**Comment by Sunnyiscoming** [comment]
You should change your data sample. Any update?

**Comment by raghavrmadya** [comment]
any update?

**Comment by raghavrmadya** [comment]
Please open a new issue with updates

**Comment by zvooo** [comment]
Please delete this issue
