### ISSUE TITLE
[DataCap Application] NFT Data Storage 

### ISSUE THREAD

**Issue by bjchend** [filecoin-project/filecoin-plus-large-datasets#469]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name:  NFTBomb
- Website / Social Media: https://nftbomb.org
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):  3PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100TiB
- On-chain address for first allocation: f1rhpecsedmbwdmeqnzxwtc3j5euqx3gqbyf6umuy

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
NFTBmob is the first open ecosystem that integrates the NFT contract protocol layer and application layer. 
In simple terms, NFTBomb is an NFT+DeFi+BSC ecosystem of NFT protocols. 
The core vision of NFTBomb is to nurture and accelerate creative NFT protocols in terms of liquidity and user adoption. 
NFTBomb aims to bring one-stop NFT+DeFi experience on BSC.   https://nftbomb-1.gitbook.io/nftbomb/
```
What is the primary source of funding for this project?
```
Self-owned commercial funding
```

What other projects/ecosystem stakeholders is this project associated with?
```
zkimart NFT : http://zkimart.online/
```

## Use-case details

Describe the data being stored onto Filecoin
```
The data to be stored: mainly for storing NFT data and the records 
and interaction data generated by customers in the process of using NFTBomb.
```

Where was the data in this dataset sourced from?
```
NFT storage data and transaction data from the nftbomb.org web platform
Google Cloud Public Datasets, Ali cloud data storage service
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://nftbomb.org/metadata/top10.zip
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Confirmed -- yes
```

What is the expected retrieval frequency for this data?
```
1. Customers can retrieve their own account's private data at any time
2. Public data retrieval time is expected at the time of monthly audit and quarterly audit
```

For how long do you plan to keep this dataset stored on Filecoin?
```
1. customer private data needs to be stored for more than 3 years, maybe longer
2. public data is stored for at least 2 years
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Asia. North America. and where the user is located.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
   API interface available for data calls
   Support for online data transfer and download
  Support offline download of data files
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
Mainly based on the NFTBomb user experience for selection, and then according to the sp encapsulation capacity, reputation value and network access speed, for comprehensive consideration
```

How will you be distributing deals across storage providers?
```
Develop a list of partners based on the capacity and credit value of the sp
But each SP can not exceed 25%.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
  yes, I have all I need to start making deals.
  Improving the ecosystem of the Filcoin community was the main condition for NFTBomb to choose to join Filecoin.
```

**Comment by Sunnyiscoming** [comment]
@bjchend Whether customer private data is public?

**Comment by dkkapur** [comment]
Closing this out for now since there was no response to the above questions. Please open up a new application if still relevant.
