### ISSUE TITLE
[DataCap Application] <DERIER> - <website>

### ISSUE THREAD

**Issue by jekc2008** [filecoin-project/filecoin-plus-large-datasets#470]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: DERIER GROUP
- Website / Social Media:https://www.derier.com.cn
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):1PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):10TiB
- On-chain address for first allocation:f3uek4o7zxh5bmyqlxuucwivoonmsk3rpixgt47feh6f3qmuafr7ybhdwi4yzlwyjgpp2gwv36nnctsjt32cja

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
In 2000, we established DERIER Group Limited under our group. Since then, it has become one of the largest private basic diamond in China, serving over 60,000 product and style. Over the past 20 years, more than 500,000 of our custermoes have been enrolled in VIP. With a 55% on China's Markers, we are proud of preparing to become love’s imprint.              
```

What is the primary source of funding for this project?
```
Self-owned commercial funding
```

What other projects/ecosystem stakeholders is this project associated with?
```
No related association 
```

## Use-case details

Describe the data being stored onto Filecoin
```
 DERIER APP ERP  web data and the records 
```

Where was the data in this dataset sourced from?
```
storage data and transaction data from the web platform, Ali cloud data storage service
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://www.mediafire.com/folder/01wp5c7f1b6iz/DERIER
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Confirmed – yes
```

What is the expected retrieval frequency for this data?
```
1. Customers can retrieve their own account's private data at any time
2. Public data retrieval time is expected at the time of monthly audit and quarterly audit
```

For how long do you plan to keep this dataset stored on Filecoin?
```
more than 3 years, maybe longer
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Asia.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
API interface available for data calls
Support for online data transfer and download
Support offline download of data files
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
sp encapsulation capacity, reputation value and network access speed
```

How will you be distributing deals across storage providers?
```
Develop a list of partners based on the capacity and credit value of the sp
But each SP can not exceed 50%.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
yes, I have all I need to start making deals.
```

**Comment by Sunnyiscoming** [comment]
> transaction data from the web platform
Companies generally do not disclose transaction data, not only for the sake of companies privacy but also for the sake of customer privacy.  Do you confirm this part of data is totally public?
> each SP can not exceed 50%
The community requires that datacap usage should be distributed to avoid self-dealing, and no more than 50% is not an appropriate storage ratio.

**Comment by Sunnyiscoming** [comment]
Any update here?

**Comment by dkkapur** [comment]
Closing this out for now since there was no response to the above questions. Please open up a new application if still relevant.
