### ISSUE TITLE
[DataCap Application] Krptic

### ISSUE THREAD

**Issue by edwarddong** [filecoin-project/filecoin-plus-large-datasets#471]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name:  krptic corporation
- Website / Social Media: https://www.krptic.com/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 2PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100TiB
- On-chain address for first allocation: f1o7mpjv6l73z7gnbk4n47io6rt3vvkziaibjjkda

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Krptic wallet is a professional decentralized wallet, Krptic supports over 100 digital currencies including all the most popular ones. Krptic incorporates leading edge encryption technology securing both hot and cold wallets. Uses Finnovant's Say-Tec voice and face biometric protection technology to safely secure your assets. Log-in using facial and voice biometric recognition without being connected to a network. This technology uses the unique physical facial and voice characteristics of each individual to generate the only bio-key of the Krptic wallet.
```

What is the primary source of funding for this project?
```
The company's profit.
```

What other projects/ecosystem stakeholders is this project associated with?
```
None.
```

## Use-case details

Describe the data being stored onto Filecoin
```
App's data and user's.
```

Where was the data in this dataset sourced from?
```
Devops and server's data.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://www.krptic.com.
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
From the data generated during our research and development, design, transportation and sales
```

What is the expected retrieval frequency for this data?
```
About once a year.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
2 years.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Asia.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Online and offline.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We will select miners with good reputation, trustworthiness, and experience in verifying data to conduct transactions.
```

How will you be distributing deals across storage providers?
```
We will find high-quality miners through slack, GitHub and other channels, distribute to miners in an even proportion. Also, each miner won’t be allocated more than 30% of our datacap.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, we do.
```

**Comment by Sunnyiscoming** [comment]
> Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
> 
> From the data generated during our research and development, design, transportation and sales

Is it a private dataset? This dataset contains users' data.

**Comment by Sunnyiscoming** [comment]
Any update here?

**Comment by dkkapur** [comment]
Closing this out for now since there was no response to the above questions. Please open up a new application if still relevant.
