### ISSUE TITLE
[DataCap Application] pCloud AG - Cloud Storage

### ISSUE THREAD

**Issue by TopChina** [filecoin-project/filecoin-plus-large-datasets#472]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: pCloud AG
- Website / Social Media: 369.hk
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 4PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):50TiB
- On-chain address for first allocation:f1e3kteofumxt2vhszycenw74xc5ggi2cxlob35yq

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Based in Switzerland, we are a young forward-thinking team doing our best to make a significant impact on the rapidly growing IT market. 

At pCloud, we're providing the world with a comprehensive easy-to-use cloud storage solution for individuals and businesses alike.
```

What is the primary source of funding for this project?
```
corporate sponsorship.and personal money.
```

What other projects/ecosystem stakeholders is this project associated with?
```
No one.
```

## Use-case details

Describe the data being stored onto Filecoin
```
any user dataset.
```

Where was the data in this dataset sourced from?
```
User Upload.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
ed2k://|file|mu_visual_studio_for_mac_mac_10468896.dmg|26944731|FBE947BC68002556294CB0A433EB8444|/.
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Confirmed.  
```

What is the expected retrieval frequency for this data?
```
About 1 time per year.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
3 years.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Asia, North America, Europe .
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Offline.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We're selecting the SPs with high reputation on slack  and who already participate to Slingshot. They have the ability to store deals at a very fast pace and a high success rate.
```

How will you be distributing deals across storage providers?
```
No single SPs can make deals more than 25%. 
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
yes.
```

**Comment by Sunnyiscoming** [comment]
> Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this.
> 
> ed2k://|file|mu_visual_studio_for_mac_mac_10468896.dmg|26944731|FBE947BC68002556294CB0A433EB8444|/.

This link do not work. Can you provide another link?

> Describe the data being stored onto Filecoin
> 
> any user dataset.

Have you get authorization from users?

**Comment by Sunnyiscoming** [comment]
![image](https://user-images.githubusercontent.com/105098820/184053247-12e51d0e-0326-4062-b809-11c5ad6b514d.png)
They are still can not be checked.

**Comment by raghavrmadya** [comment]
Your response above does not satisfy this. Please open a new application with the correct information. 

<img width="848" alt="Screen Shot 2022-08-21 at 4 16 21 PM" src="https://user-images.githubusercontent.com/91579519/185814956-e755822b-69a3-471f-9aa8-00f9d90b3c21.png">

**Comment by raghavrmadya** [comment]
Also make sure to link this application in your new application if you decide to apply again to move quicker.
