### ISSUE TITLE
[DataCap Application] Project Beacon LDN 12/12 - Hash Tiger

### ISSUE THREAD

**Issue by Beacon-Edu** [filecoin-project/filecoin-plus-large-datasets#482]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Beacon Project
- Website / Social Media: Due to the privacy concerns of many parties involved in our educational programs, our website will only be available to PL and the relevant notaries.
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 300TiB
- On-chain address for first allocation: f1xtnkj5ti77f5gbzhclnpj3xt6e5dwhfzive2yca

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
In 1995, we established Education Group Limited under our group. Since then, it has become one of the largest private basic education schools in China, serving over 60,000 teachers and students. Over the past 20 years, more than 30,000 of our students have been enrolled in domestic and foreign universities. With a 95% pass rate on China's university entrance exam which is known as Gao Kao, we are proud of preparing students to become engaged global citizens.
In addition, our group's international schools have students from over 23 countries and regions, including mainland China, the United States, Japan, Great Britain, Germany, Korea, Italy, Russia, Canada, etc. We have sent a large number of outstanding students to world-renowned universities such as Cambridge University, Harvard University, MIT, Imperial College London, Peking University and Tsinghua University.
Our group adheres to the strategic academic principles of "competitiveness, characterization and internationalization" in education to effectively improve the quality of our schools, communities and teachers. We have persistently built our educational strengths since the beginning, ultimately aiming to become one of the top K12 private education groups in China and the world by 2025.
```

What is the primary source of funding for this project?
```
Private capital
```

What other projects/ecosystem stakeholders is this project associated with?
```
No related association
```

## Use-case details

Describe the data being stored onto Filecoin
```
The dataset contains courses from more than 100 schools, documentation managed by teams of teachers, and over 3,600 videos of lessons recordings. Due to the privacy of the students & teachers as well as the teacher's behavior in the classroom, the data itself is not of use to anyone except our education group. Therefore, the data will be encrypted for our own consideration.
```

Where was the data in this dataset sourced from?
```
![Chart1](https://user-images.githubusercontent.com/106231732/175933248-cedd1225-ed0d-40d5-90cb-8807924564bc.png)
![Chart2](https://user-images.githubusercontent.com/106231732/175933258-0318f5f6-e2a3-4c1e-9e1c-871eaca99947.png)

```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
No, data samples will only be shared to PL and the relevant Notary for KYC purpose.
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
No, this is an encrypted dataset that can only be sealed by the Chinese SP due to government policy.
```

What is the expected retrieval frequency for this data?
```
Depends on the demand of our business.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
2 years at least.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Greater China
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Yes, we will be using offline data transfer, which will be more efficient than online transfer.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
![image](https://user-images.githubusercontent.com/106231732/182093956-38bf9bb1-dffd-4514-a195-79a4af1172d6.png)

How will you be distributing deals across storage providers?
```
Less than 20% of total data will be stored in each SP.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, we already prepared enough funding for making deals.
```

**Comment by galen-mcandrew** [comment]
Removing labels to allow tooling updates. Will report back.

**Comment by swatchliu** [comment]
Hi @galen-mcandrew , could you confirm whether we can do the multi-sig?  

We suggest that the first round of 7PiB could be allocated to f1xtnkj5ti77f5gbzhclnpj3xt6e5dwhfzive2yca , and the remaining 53PiB can be allocated to other 11 addresses after the end of the two-week trial period.

More than half of the SPs have indicated that they may change their minds if their nodes can't start these two days. In order not to waste all previous efforts, can we follow this method ?

**Comment by dkkapur** [comment]
## Datacap Request Trigger
#### Total DataCap requested 
> 5 PiB
#### Expected weekly DataCap usage rate 
> 300 TiB 
#### Client address
> f1xtnkj5ti77f5gbzhclnpj3xt6e5dwhfzive2yca

**Comment by kernelogic** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedkn2zbpupnq4jgsjreqfq6gn22tp2sqwcqegqfjj33rwbwmpkauq 
#### Address 
> f1xtnkj5ti77f5gbzhclnpj3xt6e5dwhfzive2yca
#### Datacap Allocated
> 150.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedkn2zbpupnq4jgsjreqfq6gn22tp2sqwcqegqfjj33rwbwmpkauq

**Comment by fireflyHZ** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec7nipy62fgoq4ykl7aps67632sm6ywo3l54efixrij3a45rlcze6 
#### Address 
> f1xtnkj5ti77f5gbzhclnpj3xt6e5dwhfzive2yca
#### Datacap Allocated
> 150.00TiB
#### Signer Address
> f1fg6jkxsr3twfnyhdlatmq36xca6sshptscds7xa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec7nipy62fgoq4ykl7aps67632sm6ywo3l54efixrij3a45rlcze6

**Comment by BigD-Exchange** [comment]
@Beacon-Edu Hi! Great to see you have gotten approval for DataCap and advancing the mission of preserving humanity’s most important information. If you are looking for storage providers to store these data or have any questions, please visit #bigdata-exchange on Filecoin Slack or reply here. 

We have strong demand from a diverse group of SPs, who are actively looking to onboard more data.

**Comment by liyunzhi-666** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecyo23oxlaf6a3rk4o73wvyneomvd4asd75ll4rtzo4cjbwxd7nfc 
#### Address 
> f1xtnkj5ti77f5gbzhclnpj3xt6e5dwhfzive2yca
#### Datacap Allocated
> 600.00TiB
#### Signer Address
> f1pszcrsciyixyuxxukkvtazcokexbn54amf7gvoq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecyo23oxlaf6a3rk4o73wvyneomvd4asd75ll4rtzo4cjbwxd7nfc

**Comment by PluskitOfficial** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebgjkspy6k6e4qk5qqgdypm34cfoofin26tf5mu23yzemtlpiqqaa 
#### Address 
> f1xtnkj5ti77f5gbzhclnpj3xt6e5dwhfzive2yca
#### Datacap Allocated
> 600.00TiB
#### Signer Address
> f1tgnlhtcmhwipfm7thsftxhn5k52velyjlazpvka
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebgjkspy6k6e4qk5qqgdypm34cfoofin26tf5mu23yzemtlpiqqaa

**Comment by kernelogic** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebmz46rofurxwvwacknaihny27vjwaxjem3tycpvyfep6tpmwafeq 
#### Address 
> f1xtnkj5ti77f5gbzhclnpj3xt6e5dwhfzive2yca
#### Datacap Allocated
> 1.17PiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebmz46rofurxwvwacknaihny27vjwaxjem3tycpvyfep6tpmwafeq

**Comment by MetaWaveInfo** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb7is5cyqznjlso65d47duakzufm5f4j74plfrpw5yhkdcjnlh3gy 
#### Address 
> f1xtnkj5ti77f5gbzhclnpj3xt6e5dwhfzive2yca
#### Datacap Allocated
> 1.17PiB
#### Signer Address
> f1ktlkcxnmzxcdaoqfsunrg3vocfbmgv4n3mrn74a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb7is5cyqznjlso65d47duakzufm5f4j74plfrpw5yhkdcjnlh3gy

**Comment by kernelogic** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacechzztuboit466yl3xe6ldtt2v7e4u4q7cwljwtiqe633nojf67xq 
#### Address 
> f1xtnkj5ti77f5gbzhclnpj3xt6e5dwhfzive2yca
#### Datacap Allocated
> 2.34PiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacechzztuboit466yl3xe6ldtt2v7e4u4q7cwljwtiqe633nojf67xq

**Comment by liyunzhi-666** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaw6bvdcpb5672tsh5lyakg4pgz7u6ioza7ed47ivt7vvvm5umkvs 
#### Address 
> f1xtnkj5ti77f5gbzhclnpj3xt6e5dwhfzive2yca
#### Datacap Allocated
> 2.34PiB
#### Signer Address
> f1pszcrsciyixyuxxukkvtazcokexbn54amf7gvoq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaw6bvdcpb5672tsh5lyakg4pgz7u6ioza7ed47ivt7vvvm5umkvs

**Comment by filplus-checker** [comment]
## DataCap and CID Checker Report[^1]
 - Organization: `Beacon Project`
 - Client: `f1xtnkj5ti77f5gbzhclnpj3xt6e5dwhfzive2yca`
### Storage Provider Distribution
The below table shows the distribution of storage providers that have stored data for this client.

If this is the first time a provider takes verified deal, it will be marked as `new`.

For most of the datacap application, below restrictions should apply.
 - Storage provider should not exceed 25% of total datacap.
 - Storage provider should not be storing duplicate data for more than 20%.
 - Storage provider should have published its public IP address.
 - All storage providers should be located in different regions.

⚠️ [f01887327](https://filfox.info/en/address/f01887327) has sealed 100.00% of total datacap.

⚠️ 83.79% of total deal sealed by [f01887327](https://filfox.info/en/address/f01887327) are duplicate data.

⚠️ All storage providers are located in the same region.

| Provider                                                    |         Location | Total Deals Sealed | Percentage | Unique Data | Duplicate Deals |
| :---------------------------------------------------------- | ---------------: | -----------------: | ---------: | ----------: | --------------: |
| [f01887327](https://filfox.info/en/address/f01887327)`new`  | Tokyo, Tokyo, JP |           1.63 PiB |    100.00% |  269.88 TiB |          83.79% |

![Provider Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/482/1671097106258.png)
### Deal Data Replication
The below table shows how each many unique data are replicated across storage providers.
- No more than 25% of unique data are stored with less than 4 providers.

⚠️ 100.00% of deals are for data replicated across less than 4 storage providers.

| Unique Data Size | Total Deals Made | Number of Providers | Deal Percentage |
| ---------------: | ---------------: | ------------------: | --------------: |
|       269.88 TiB |         1.63 PiB |                   1 |         100.00% |

![Replication Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/482/1671097106899.png)
### Deal Data Shared with other Clients
The below table shows how many unique data are shared with other clients.
Usually different applications owns different data and should not resolve to the same CID.

⚠️ CID sharing has been observed.

| Other Client                                                                                                          | Application                                                                                                                | Total Deals Affected | Unique CIDs |                                                                                 Verifier |
| :-------------------------------------------------------------------------------------------------------------------- | :------------------------------------------------------------------------------------------------------------------------- | -------------------: | ----------: | ---------------------------------------------------------------------------------------: |
| [f1dwhevm3p2slu6itmkssznscmpkpltdiztprnpya](https://filfox.info/en/address/f1dwhevm3p2slu6itmkssznscmpkpltdiztprnpya) | [Hiscene](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/548)                                     |           191.81 TiB |         724 |                                                                          LDN v3 multisig |
| [f1avhqgmeazxzvylz34l26o3nlj2ywnzaviwns3dq](https://filfox.info/en/address/f1avhqgmeazxzvylz34l26o3nlj2ywnzaviwns3dq) | [87v5\-CarsonVideo](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/392)                           |           183.69 TiB |         765 |                                                                          LDN v3 multisig |
| [f1hamzyd3tx4pdchop3l4hfeay5q6s427pxga6flq](https://filfox.info/en/address/f1hamzyd3tx4pdchop3l4hfeay5q6s427pxga6flq) | `Beacon Project`                                                                                                           |           102.69 TiB |         541 | Project Beacon, 12 LDNs LDN # 444, 446, 447, 448, 474, 475, 476, 477, 479, 480, 481, 482 |
| [f1uuzet23wng5lxu3y4iicokksydynamgmptfekdq](https://filfox.info/en/address/f1uuzet23wng5lxu3y4iicokksydynamgmptfekdq) | `Explainer video`                                                                                                          |           101.44 TiB |         439 |                                                                                 LDN # 65 |
| [f1rszqldzirsgganeah32zubr4r4qafwypuwaig2q](https://filfox.info/en/address/f1rszqldzirsgganeah32zubr4r4qafwypuwaig2q) | [Beacon Project](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/477)                              |            84.38 TiB |         488 | Project Beacon, 12 LDNs LDN # 444, 446, 447, 448, 474, 475, 476, 477, 479, 480, 481, 482 |
| [f1rnwp6p5kx7pcwexpucoav6mmwz3rkxw5blrboyy](https://filfox.info/en/address/f1rnwp6p5kx7pcwexpucoav6mmwz3rkxw5blrboyy) | [MigoVideo](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/517)                                   |            83.81 TiB |         340 |                                                                          LDN v3 multisig |
| [f1f5edx6ofn3lf6rk3yfpldbi2pzgq2egoyu6ubpi](https://filfox.info/en/address/f1f5edx6ofn3lf6rk3yfpldbi2pzgq2egoyu6ubpi) | [Samdata Trade](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/382)                               |            81.00 TiB |         300 |                                                                          LDN v3 multisig |
| [f1einobkrjcjk6gfc5ov6663vrri75hwdsjfs6pmq](https://filfox.info/en/address/f1einobkrjcjk6gfc5ov6663vrri75hwdsjfs6pmq) | [Cansoti](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/640)                                     |            67.25 TiB |         243 |                                                                          LDN v3 multisig |
| [f1zav4f4rak2yvbrq357z3whj224wn4dipl7eiesy](https://filfox.info/en/address/f1zav4f4rak2yvbrq357z3whj224wn4dipl7eiesy) | [Shanghai Zhixun](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/628)                             |            41.44 TiB |         182 |                                                                          LDN v3 multisig |
| [f1mn5mw2dpqz6p3s7vxrlkhkh3okdtc6t7wqro4xa](https://filfox.info/en/address/f1mn5mw2dpqz6p3s7vxrlkhkh3okdtc6t7wqro4xa) | [Unisound](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/577)                                    |            32.75 TiB |         142 |                                                                          LDN v3 multisig |
| [f1quofpadzcqlonmz7v3mv7dfqvm5hdztucdsjqsy](https://filfox.info/en/address/f1quofpadzcqlonmz7v3mv7dfqvm5hdztucdsjqsy) | [HENAN 863 SOFTWARE CO\., LTD](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/468)                |            20.94 TiB |         130 |                                                                          LDN v3 multisig |
| [f1jdmx2cuswzjlt4pnsv3t7ipmesywzxsg6q56a2a](https://filfox.info/en/address/f1jdmx2cuswzjlt4pnsv3t7ipmesywzxsg6q56a2a) | [Raysun Radar Electronic Technology Co\.,Ltd](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/884) |            17.19 TiB |          87 |                                                                          LDN v3 multisig |
| [f1727w2vwjctfo7hflr5trgqkl3c7texh7pl4grzq](https://filfox.info/en/address/f1727w2vwjctfo7hflr5trgqkl3c7texh7pl4grzq) | [GMverse](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/365)                                     |             4.69 TiB |          11 |                                                                          LDN v3 multisig |

[^1]: To manually trigger this report, add a comment with text `checker:manualTrigger`
