### ISSUE TITLE
[DataCap Application] Speedium - NexRad V2 [ Replica distribution ] Part 1 / 5

### ISSUE THREAD

**Issue by cryptowhizzard** [filecoin-project/filecoin-plus-large-datasets#483]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Speedium network
- Website / Social Media: www.speedium.nl
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5 PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 1 PiB
- On-chain address for first allocation: f1xafi3wsh7q553efnumhgeomathrehwwd2mye7oy

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Short addendum on this project
```
This application is a followup of our first. NexRad is 2 PiB +. We are building the dataset at the moment. This datacap is solely for replica distribution. Link -> https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/340
```

Share a brief history of your project and organization.
```
Speedium / Dcent has engaged in Slingshot starting 2.6. We have successfully stored more than 15 differerent datasets with 20+ different miners.

```

What is the primary source of funding for this project?
```
Company account
```

What other projects/ecosystem stakeholders is this project associated with?
```
Slingshot competition hosted by Protocol Labs
```

## Use-case details

Describe the data being stored onto Filecoin
```
The [Next Generation Weather Radar](https://www.ncdc.noaa.gov/data-access/radar-data/nexrad) (NEXRAD) is a network of 160 high-resolution Doppler radar sites that detects precipitation and atmospheric movement and disseminates data in approximately 5 minute intervals from each site.
```

Where was the data in this dataset sourced from?
```
AWS
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://www.ncei.noaa.gov/products/radar-data/nexrad
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes.
```

What is the expected retrieval frequency for this data?
```
Multiple times p/y
```

For how long do you plan to keep this dataset stored on Filecoin?
```
18 months or longer
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
EU / US / Australia
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
The data will be transferred both offline and online.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We have a few providers who have been working with us during Slingshot Restore program and we'd like to continue working with them for ongoing Slingshot competition.
```

How will you be distributing deals across storage providers?
```
Max 2 copy's per storage provider if stored on different miners / locations.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, we have the resources.
```

**Comment by Sunnyiscoming** [comment]
@cryptowhizzard Hi,
1. https://www.ncei.noaa.gov/products/radar-data/nexrad, Page or Resource Not Found (404 Error)
2. Please ensure that the total amount of DataCap being requested is 30 PiB. As you said, this datacap is solely for replica distribution, NexRad is 2 PiB +. It means you need more than 10 copies.
3. https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/340 The datacap being allocated has not be used(https://filplus.d.interplanetary.one/clients?filter=f1xafi3wsh7q553efnumhgeomathrehwwd2mye7oy). Maybe you should apply when you have used up the datacap you got in this issue.

**Comment by cryptowhizzard** [comment]
Hi @Sunnyiscoming 

Fair points.

1 -> https://registry.opendata.aws/noaa-nexrad/

2 -> I am not sure if it is 2 PB exactly , this dataset is growing over the course of months. It can be that i won't apply for the last tranche.

3 -> This is rather difficult. I can't start sealing #340 solely with one miner by our own as this would violate the program rules. This is the reason i am doing this applications in parallel.

**Comment by Sunnyiscoming** [comment]
I don't quite understand your third point. Why can't datacap of #340 be allocated to other storage providers？

**Comment by cryptowhizzard** [comment]
@Sunnyiscoming this can be done. But if i assign and they don't start in the same pace or rythm it will result in 1 provider taking the whole first allocation.

**Comment by Sunnyiscoming** [comment]
I will talk about this with governance team because I think it is a problem which can be solved.

**Comment by raghavrmadya** [comment]
> Hi @Sunnyiscoming
> 
> Fair points.
> 
> 1 -> https://registry.opendata.aws/noaa-nexrad/
> 
> 2 -> I am not sure if it is 2 PB exactly , this dataset is growing over the course of months. It can be that i won't apply for the last tranche.
> 
> 3 -> This is rather difficult. I can't start sealing #340 solely with one miner by our own as this would violate the program rules. This is the reason i am doing this applications in parallel.

Hi @cryptowhizzard , can you elaborate on the difficulties? I'm unsure why you would only be able to seal with one SP?

**Comment by cryptowhizzard** [comment]
@raghavrmadya because the dataset is the same size as the datacap. Only one can seal the first replica to get it on chain. This is no problem as i will do the replica’s in a separate LDN, i just want to give notification here.

**Comment by Sunnyiscoming** [comment]
If this problem can be solved. Maybe you can close this issue and continue #340

**Comment by raghavrmadya** [comment]
Hi @cryptowhizzard, we have a PR open that was presented at the last gov call to increase the request limit to 25 PiBs. Do you mind waiting until end of this week when we merge that or are there SPs waiting on you?

**Comment by cryptowhizzard** [comment]
Hi @raghavrmadya that is ok. I will also update the wallet address so it is a unique wallet address per datacap request.

**Comment by raghavrmadya** [comment]
@cryptowhizzard, the increase for the limit is still under discussion. If you want to proceed, you can create multiple issues for this app to proceed

**Comment by cryptowhizzard** [comment]
Hello,

I updated the request.

**Comment by raghavrmadya** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 1PiB

**Client address**

>f1xafi3wsh7q553efnumhgeomathrehwwd2mye7oy

**Comment by kernelogic** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedi6fsiv7ycthoio4ls5hybsr5ynsdeamsn2dyn3ql54rhilgs7yq 
#### Address 
> f1xafi3wsh7q553efnumhgeomathrehwwd2mye7oy
#### Datacap Allocated
> 256.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedi6fsiv7ycthoio4ls5hybsr5ynsdeamsn2dyn3ql54rhilgs7yq

**Comment by s0nik42** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceas7ti2iwzqqavdittbejtxdud6ar5f4krqqxubo5nccz7wbyvby6 
#### Address 
> f1xafi3wsh7q553efnumhgeomathrehwwd2mye7oy
#### Datacap Allocated
> 256.00TiB
#### Signer Address
> f1wxhnytjmklj2czezaqcfl7eb4nkgmaxysnegwii
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceas7ti2iwzqqavdittbejtxdud6ar5f4krqqxubo5nccz7wbyvby6

**Comment by Reiers** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceccbwxqbtrn4bfaaviht5bjxvkdkce2dnhy77mtfqwb4ato6uwjpu 
#### Address 
> f1xafi3wsh7q553efnumhgeomathrehwwd2mye7oy
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f1oz43ckvmtxmmsfzqm6bpnemqlavz4ifyl524chq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceccbwxqbtrn4bfaaviht5bjxvkdkce2dnhy77mtfqwb4ato6uwjpu

**Comment by kernelogic** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec3p3irclnfdgvpxq6pzgpplwspsa7s6ueienbstnq2cl5vf2foty 
#### Address 
> f1xafi3wsh7q553efnumhgeomathrehwwd2mye7oy
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec3p3irclnfdgvpxq6pzgpplwspsa7s6ueienbstnq2cl5vf2foty

**Comment by kernelogic** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaasd2apuxiyudvk43vlq6frrzquetz6574adlg2w7uw3itqcyd42 
#### Address 
> f1xafi3wsh7q553efnumhgeomathrehwwd2mye7oy
#### Datacap Allocated
> 1.00PiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### Id
> 8336a73b-1c0b-4fda-86c3-bba095825bd1
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaasd2apuxiyudvk43vlq6frrzquetz6574adlg2w7uw3itqcyd42

**Comment by mjroddy** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecozpjxr5tgxermgyw7mzc27xnkwupdx3naruiqvpnhuzxek7tzym 
#### Address 
> f1xafi3wsh7q553efnumhgeomathrehwwd2mye7oy
#### Datacap Allocated
> 1.00PiB
#### Signer Address
> f1ystxl2ootvpirpa7ebgwl7vlhwkbx2r4zjxwe5i
#### Id
> 8336a73b-1c0b-4fda-86c3-bba095825bd1
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecozpjxr5tgxermgyw7mzc27xnkwupdx3naruiqvpnhuzxek7tzym

**Comment by xinaxu** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebkztcn6mhjbhzxrovop7nj5w4jmu7a2gbvzjhhrubbc7mnsrf6tg 
#### Address 
> f1xafi3wsh7q553efnumhgeomathrehwwd2mye7oy
#### Datacap Allocated
> 2.00PiB
#### Signer Address
> f1k3ysofkrrmqcot6fkx4wnezpczlltpirmrpsgui
#### Id
> aaa8902b-82da-475b-b369-baaec731da70
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebkztcn6mhjbhzxrovop7nj5w4jmu7a2gbvzjhhrubbc7mnsrf6tg

**Comment by kernelogic** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedwwfd25ffvfs4xgsfpg3nyp7khmo4jfd437llkbxsiaskb5vkvwq 
#### Address 
> f1xafi3wsh7q553efnumhgeomathrehwwd2mye7oy
#### Datacap Allocated
> 2.00PiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### Id
> aaa8902b-82da-475b-b369-baaec731da70
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedwwfd25ffvfs4xgsfpg3nyp7khmo4jfd437llkbxsiaskb5vkvwq

**Comment by kernelogic** [comment]
oops, i guess this is double proposed now.

**Comment by flyworker** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecfcryrb6ocnopjx4kacts44gz5ebhkayewoeal46vgzcfuewcm76 
#### Address 
> f1xafi3wsh7q553efnumhgeomathrehwwd2mye7oy
#### Datacap Allocated
> 2.00PiB
#### Signer Address
> f1hlubjsdkv4wmsdadihloxgwrz3j3ernf6i3cbpy
#### Id
> aaa8902b-82da-475b-b369-baaec731da70
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecfcryrb6ocnopjx4kacts44gz5ebhkayewoeal46vgzcfuewcm76

**Comment by filplus-checker** [comment]
## DataCap and CID Checker Report[^1]
 - Organization: `Speedium network`
 - Client: `f1xafi3wsh7q553efnumhgeomathrehwwd2mye7oy`
### Storage Provider Distribution
The below table shows the distribution of storage providers that have stored data for this client.

If this is the first time a provider takes verified deal, it will be marked as `new`.

For most of the datacap application, below restrictions should apply.
 - Storage provider should not exceed 25% of total datacap.
 - Storage provider should not be storing duplicate data for more than 20%.
 - Storage provider should have published its public IP address.
 - All storage providers should be located in different regions.

⚠️ 25.80% of total deal sealed by [f01157271](https://filfox.info/en/address/f01157271) are duplicate data.

⚠️ 27.24% of total deal sealed by [f01208803](https://filfox.info/en/address/f01208803) are duplicate data.

⚠️ 24.50% of total deal sealed by [f01208154](https://filfox.info/en/address/f01208154) are duplicate data.

⚠️ 21.24% of total deal sealed by [f01156835](https://filfox.info/en/address/f01156835) are duplicate data.

⚠️ 52.64% of total deal sealed by [f01208189](https://filfox.info/en/address/f01208189) are duplicate data.

⚠️ 34.04% of total deal sealed by [f01208042](https://filfox.info/en/address/f01208042) are duplicate data.

⚠️ 23.73% of total deal sealed by [f01156538](https://filfox.info/en/address/f01156538) are duplicate data.

⚠️ [f01908299](https://filfox.info/en/address/f01908299) has unknown IP location.

| Provider                                                    |                         Location | Total Deals Sealed | Percentage | Unique Data | Duplicate Deals |
| :---------------------------------------------------------- | -------------------------------: | -----------------: | ---------: | ----------: | --------------: |
| [f01919423](https://filfox.info/en/address/f01919423)       |      Sydney, New South Wales, AU |         597.30 TiB |     11.11% |  576.67 TiB |           3.45% |
| [f01908671](https://filfox.info/en/address/f01908671)       |   Philadelphia, Pennsylvania, US |         503.09 TiB |      9.36% |  460.88 TiB |           8.39% |
| [f01938357](https://filfox.info/en/address/f01938357)       |      Sydney, New South Wales, AU |         431.94 TiB |      8.04% |  431.91 TiB |           0.01% |
| [f01851482](https://filfox.info/en/address/f01851482)       |                 Busan, Busan, KR |         383.06 TiB |      7.13% |  383.06 TiB |           0.00% |
| [f01852664](https://filfox.info/en/address/f01852664)       |         Singapore, Singapore, SG |         306.91 TiB |      5.71% |  306.91 TiB |           0.00% |
| [f01882184](https://filfox.info/en/address/f01882184)       |         Singapore, Singapore, SG |         296.03 TiB |      5.51% |  296.03 TiB |           0.00% |
| [f01880047](https://filfox.info/en/address/f01880047)       |         Singapore, Singapore, SG |         259.88 TiB |      4.84% |  259.88 TiB |           0.00% |
| [f01877571](https://filfox.info/en/address/f01877571)       |         Singapore, Singapore, SG |         253.53 TiB |      4.72% |  253.38 TiB |           0.06% |
| [f01967501](https://filfox.info/en/address/f01967501)`new`  |   Philadelphia, Pennsylvania, US |         196.28 TiB |      3.65% |  196.28 TiB |           0.00% |
| [f01720359](https://filfox.info/en/address/f01720359)       | Heerhugowaard, North Holland, NL |         184.78 TiB |      3.44% |  179.19 TiB |           3.03% |
| [f01938665](https://filfox.info/en/address/f01938665)       |   Sham Shui Po, Sham Shui Po, HK |         172.31 TiB |      3.21% |  170.25 TiB |           1.20% |
| [f01938717](https://filfox.info/en/address/f01938717)       |         Singapore, Singapore, SG |         164.16 TiB |      3.05% |  163.94 TiB |           0.13% |
| [f01878005](https://filfox.info/en/address/f01878005)       |         Singapore, Singapore, SG |         146.69 TiB |      2.73% |  146.19 TiB |           0.34% |
| [f01882177](https://filfox.info/en/address/f01882177)       |         Singapore, Singapore, SG |         142.47 TiB |      2.65% |  142.41 TiB |           0.04% |
| [f01786387](https://filfox.info/en/address/f01786387)       | Heerhugowaard, North Holland, NL |         114.28 TiB |      2.13% |  110.69 TiB |           3.14% |
| [f01157271](https://filfox.info/en/address/f01157271)       |      Sydney, New South Wales, AU |          99.56 TiB |      1.85% |   73.88 TiB |          25.80% |
| [f01208803](https://filfox.info/en/address/f01208803)       |      Sydney, New South Wales, AU |          98.19 TiB |      1.83% |   71.44 TiB |          27.24% |
| [f01771403](https://filfox.info/en/address/f01771403)       | Heerhugowaard, North Holland, NL |          96.50 TiB |      1.80% |   89.53 TiB |           7.22% |
| [f01208154](https://filfox.info/en/address/f01208154)       |      Sydney, New South Wales, AU |          85.19 TiB |      1.58% |   64.31 TiB |          24.50% |
| [f01059489](https://filfox.info/en/address/f01059489)       |                 Plano, Texas, US |          83.31 TiB |      1.55% |   83.31 TiB |           0.00% |
| [f01981059](https://filfox.info/en/address/f01981059)       |            Richardson, Texas, US |          75.78 TiB |      1.41% |   75.78 TiB |           0.00% |
| [f01208632](https://filfox.info/en/address/f01208632)       |      Sydney, New South Wales, AU |          68.91 TiB |      1.28% |   55.13 TiB |          20.00% |
| [f01156835](https://filfox.info/en/address/f01156835)`new`  |      Sydney, New South Wales, AU |          64.75 TiB |      1.20% |   51.00 TiB |          21.24% |
| [f01208189](https://filfox.info/en/address/f01208189)       |      Sydney, New South Wales, AU |          64.00 TiB |      1.19% |   30.31 TiB |          52.64% |
| [f01207874](https://filfox.info/en/address/f01207874)       |      Sydney, New South Wales, AU |          62.69 TiB |      1.17% |   53.91 TiB |          14.01% |
| [f01208042](https://filfox.info/en/address/f01208042)       |      Sydney, New South Wales, AU |          56.38 TiB |      1.05% |   37.19 TiB |          34.04% |
| [f01157249](https://filfox.info/en/address/f01157249)       |      Sydney, New South Wales, AU |          51.91 TiB |      0.97% |   46.56 TiB |          10.30% |
| [f01207954](https://filfox.info/en/address/f01207954)       |      Sydney, New South Wales, AU |          45.97 TiB |      0.86% |   42.44 TiB |           7.68% |
| [f01156883](https://filfox.info/en/address/f01156883)       |      Sydney, New South Wales, AU |          28.13 TiB |      0.52% |   26.84 TiB |           4.56% |
| [f01199430](https://filfox.info/en/address/f01199430)       | Heerhugowaard, North Holland, NL |          27.09 TiB |      0.50% |   24.44 TiB |           9.80% |
| [f01937642](https://filfox.info/en/address/f01937642)`new`  | Heerhugowaard, North Holland, NL |          26.66 TiB |      0.50% |   26.00 TiB |           2.46% |
| [f01156538](https://filfox.info/en/address/f01156538)`new`  |      Sydney, New South Wales, AU |          23.44 TiB |      0.44% |   17.88 TiB |          23.73% |
| [f01206408](https://filfox.info/en/address/f01206408)       |      Sydney, New South Wales, AU |          22.13 TiB |      0.41% |   20.41 TiB |           7.77% |
| [f01157018](https://filfox.info/en/address/f01157018)       |      Sydney, New South Wales, AU |          20.91 TiB |      0.39% |   20.91 TiB |           0.00% |
| [f01908299](https://filfox.info/en/address/f01908299)       |                          Unknown |          20.44 TiB |      0.38% |   20.38 TiB |           0.31% |
| [f01154023](https://filfox.info/en/address/f01154023)       |      Sydney, New South Wales, AU |          19.84 TiB |      0.37% |   18.63 TiB |           6.14% |
| [f01156975](https://filfox.info/en/address/f01156975)       |      Sydney, New South Wales, AU |          19.22 TiB |      0.36% |   19.19 TiB |           0.16% |
| [f01157027](https://filfox.info/en/address/f01157027)       |      Sydney, New South Wales, AU |          18.34 TiB |      0.34% |   18.13 TiB |           1.19% |
| [f022352](https://filfox.info/en/address/f022352)           |                   Oslo, Oslo, NO |          17.25 TiB |      0.32% |   17.06 TiB |           1.09% |
| [f0855584](https://filfox.info/en/address/f0855584)`new`    |            Lincoln, Nebraska, US |          11.28 TiB |      0.21% |   11.28 TiB |           0.00% |
| [f01156901](https://filfox.info/en/address/f01156901)       |      Sydney, New South Wales, AU |          10.72 TiB |      0.20% |   10.69 TiB |           0.29% |
| [f01864434](https://filfox.info/en/address/f01864434)       |      Sydney, New South Wales, AU |           3.22 TiB |      0.06% |    3.22 TiB |           0.00% |
| [f01878201](https://filfox.info/en/address/f01878201)       |           Hangzhou, Zhejiang, CN |         288.00 GiB |      0.01% |  288.00 GiB |           0.00% |

![Provider Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/483/1671097148173.png)
### Deal Data Replication
The below table shows how each many unique data are replicated across storage providers.
- No more than 25% of unique data are stored with less than 4 providers.

✔️ Data replication looks healthy.

| Unique Data Size | Total Deals Made | Number of Providers | Deal Percentage |
| ---------------: | ---------------: | ------------------: | --------------: |
|        24.11 TiB |        24.52 TiB |                   1 |           0.46% |
|       180.94 TiB |       371.00 TiB |                   2 |           6.90% |
|       245.81 TiB |       784.75 TiB |                   3 |          14.60% |
|       209.22 TiB |       879.75 TiB |                   4 |          16.37% |
|       176.78 TiB |       937.72 TiB |                   5 |          17.45% |
|       121.94 TiB |       766.06 TiB |                   6 |          14.25% |
|       103.53 TiB |       757.56 TiB |                   7 |          14.09% |
|        63.19 TiB |       533.59 TiB |                   8 |           9.93% |
|        24.88 TiB |       237.09 TiB |                   9 |           4.41% |
|         7.09 TiB |        75.69 TiB |                  10 |           1.41% |
|       640.00 GiB |         7.03 TiB |                  11 |           0.13% |

![Replication Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/483/1671097149027.png)
### Deal Data Shared with other Clients
The below table shows how many unique data are shared with other clients.
Usually different applications owns different data and should not resolve to the same CID.

⚠️ CID sharing has been observed.

| Other Client                                                                                                          | Application                                                                                                     | Total Deals Affected | Unique CIDs |        Verifier |
| :-------------------------------------------------------------------------------------------------------------------- | :-------------------------------------------------------------------------------------------------------------- | -------------------: | ----------: | --------------: |
| [f1ws3n5tuxtyg26lraqkjirz7qon7y7ckju7hhmii](https://filfox.info/en/address/f1ws3n5tuxtyg26lraqkjirz7qon7y7ckju7hhmii) | [Tech Greedy Inc](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/335)                  |             4.48 PiB |      13,100 | LDN v3 multisig |
| [f1pc5usvsbfgxxbq7c7quhhg6k7l6y5reiwqr3noy](https://filfox.info/en/address/f1pc5usvsbfgxxbq7c7quhhg6k7l6y5reiwqr3noy) | [Speedium network](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/403)                 |           245.34 TiB |       4,493 | LDN v3 multisig |
| [f1z7jogzx4x42wtilzb4lu6iotlad5rptt2acbzpi](https://filfox.info/en/address/f1z7jogzx4x42wtilzb4lu6iotlad5rptt2acbzpi) | [Speedium network](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/339)                 |             5.91 TiB |           9 | LDN v3 multisig |
| [f17ia7m5mvizrdug3sqtevqw3tifiqvxqr3kdaeuq](https://filfox.info/en/address/f17ia7m5mvizrdug3sqtevqw3tifiqvxqr3kdaeuq) | [ Speedium NetworkSpeedium Network](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/77) |           832.00 GiB |           9 |        LDN # 77 |

[^1]: To manually trigger this report, add a comment with text `checker:manualTrigger`

**Comment by Kevin-FF-USA** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 1 PiB

**Expected weekly DataCap usage rate**

> 400 TiB

**Client address**

> f1xafi3wsh7q553efnumhgeomathrehwwd2mye7oy

**Comment by xingjitansuo** [comment]
@cryptowhizzard  The distribution looks healthy, but can you please explain the CID sharing with other entity https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/335 ?

**Comment by cryptowhizzard** [comment]
@xingjitansuo 

Yes i can. #335 and we did build exactly the same dataset from AWS S3. This means the same CID's will be created.

**Comment by xingjitansuo** [comment]
The same CID only happens when the Data preparer uses the same way on the same raw data to prepare the car file.

**Comment by cryptowhizzard** [comment]
@xingjitansuo yes , we did. We build it with Singularity, so did Feiyan.

**Comment by xingjitansuo** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceapnxsq4z54ed4fxvihz4bjuy2dhycfz4sdkqtolw4exp5x3hcyeu 
#### Address 
> f1xafi3wsh7q553efnumhgeomathrehwwd2mye7oy
#### Datacap Allocated
> 256.00TiB
#### Signer Address
> f1a2lia2cwwekeubwo4nppt4v4vebxs2frozarz3q
#### Id
> feee3cd5-ac51-47fa-9810-cf45b5f1223a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceapnxsq4z54ed4fxvihz4bjuy2dhycfz4sdkqtolw4exp5x3hcyeu

**Comment by data-programs** [comment]
<img width="32" alt="KYC" Verified src="https://stable.filplus.storage/images/filplus-kyc-verified-badge.png"/>

This user’s identity has been verified through [filplus.storage](https://filplus.storage)
