### ISSUE TITLE
Speedium - 1000 Genomes Phase 3 

### ISSUE THREAD

**Issue by cryptowhizzard** [filecoin-project/filecoin-plus-large-datasets#485]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Speedium network
- Website / Social Media: www.speedium.nl
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5 PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 300 TiB
- On-chain address for first allocation: f1klrehuwhzfw6boiiywdi7pikztsob4kkieivcwq

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Speedium / Dcent has engaged in Slingshot starting 2.6. We have successfully stored more than 15 differerent datasets with 20+ different miners.

```

What is the primary source of funding for this project?
```
Company account
```

What other projects/ecosystem stakeholders is this project associated with?
```
No related association
```

## Use-case details

Describe the data being stored onto Filecoin
```
This dataset contains alignment files and short nucleotide, copy number, repeat expansion (STR) and structural variant call files from the 1000 Genomes Project Phase 3 dataset (n=3202) using Illumina DRAGEN v3.5.7b and v3.7.6 software.
```

Where was the data in this dataset sourced from?
```
AWS
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://registry.opendata.aws/ilmn-dragen-1kgp/
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes.
```

What is the expected retrieval frequency for this data?
```
Multiple times p/y
```

For how long do you plan to keep this dataset stored on Filecoin?
```
18 months or longer
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
EU / US / Australia / Asia
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
The data will be transferred both offline and online.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We have a few providers who have been working with us during Slingshot Restore program and we'd like to continue working with them for ongoing Slingshot competition.
```

How will you be distributing deals across storage providers?
```
Max 2 copy's per storage provider if stored on different miners / locations.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, we have the resources.
```

**Comment by Sunnyiscoming** [comment]
@cryptowhizzard Hi,
1. Total amount of DataCap being requested (between 500 TiB and 5 PiB): 6 PiB
Please adjust total amount from 6 PiB to no more than 5 PiB.

2.
> How will you be distributing deals across storage providers?
> Max 2 copy's per storage provider if stored on different miners / locations.

How many copies?
How much data is in the whole data set?
How many sps you will cooperate with? What percentage of datacap you might allocate to each storage provider?

**Comment by cryptowhizzard** [comment]
@Sunnyiscoming 

1 -> 10
2 -> 696.9 TiB
3 -> Between 10 and 20. The maximum of allocated datacap shall be no more then 1 PiB ( 1 SP / 2 copies if the locations differ of their miners ). There is no minimum.

**Comment by Sunnyiscoming** [comment]
You have submitted a large number of dataset applications.
I would like to confirm the data set size with you.  But I can't see the size of amazon's public data set. Can you provide any evidence to prove it?

**Comment by cryptowhizzard** [comment]
Hello @Sunnyiscoming

The total size of this dataset is 696.9 TiB

You can retrieve that data with the following command according to AWS official source:

aws s3 ls --summarize --human-readable --recursive s3://bucket-name/

**Comment by raghavrmadya** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5 PiB

**Expected weekly DataCap usage rate**

> 300 TiB

**Client address**

> f1klrehuwhzfw6boiiywdi7pikztsob4kkieivcwq

**Comment by raghavrmadya** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5 PiB

**Expected weekly DataCap usage rate**

> 300 TiB

**Client address**

> f1klrehuwhzfw6boiiywdi7pikztsob4kkieivcwq

**Comment by Alex11801** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecqhhhwyb3auch5qlfbvursgj7xw4tnugemgvucgyvpkn2i6frszg 
#### Address 
> f1klrehuwhzfw6boiiywdi7pikztsob4kkieivcwq
#### Datacap Allocated
> 150.00TiB
#### Signer Address
> f1hhippi64yiyhpjdtbidfyzma6irc2nuav7mrwmi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecqhhhwyb3auch5qlfbvursgj7xw4tnugemgvucgyvpkn2i6frszg

**Comment by raghavrmadya** [comment]
## DataCap Allocation requested

#### Multisig Notary address
> f01858410

#### Client address
> f1klrehuwhzfw6boiiywdi7pikztsob4kkieivcwq

#### DataCap allocation requested
> 150TiB

**Comment by kernelogic** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceddjby7myn4iwh6654ue7uailvd777jhtlrxdducngobpvz2m3spg 
#### Address 
> f1klrehuwhzfw6boiiywdi7pikztsob4kkieivcwq
#### Datacap Allocated
> 150.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceddjby7myn4iwh6654ue7uailvd777jhtlrxdducngobpvz2m3spg

**Comment by psh0691** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedxt5ji5tnqg5plrol6qsby52tay6nv6vr273fzdgqa4tljwmtybo 
#### Address 
> f1klrehuwhzfw6boiiywdi7pikztsob4kkieivcwq
#### Datacap Allocated
> 150.00TiB
#### Signer Address
> f1qdko4jg25vo35qmyvcrw4ak4fmuu3f5rif2kc7i
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedxt5ji5tnqg5plrol6qsby52tay6nv6vr273fzdgqa4tljwmtybo

**Comment by Reiers** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebwc5b45b6zzdqvq4ujxgsvx57cqhzskksixj2rhhkvibvcxsfabq 
#### Address 
> f1klrehuwhzfw6boiiywdi7pikztsob4kkieivcwq
#### Datacap Allocated
> 600.00TiB
#### Signer Address
> f1oz43ckvmtxmmsfzqm6bpnemqlavz4ifyl524chq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebwc5b45b6zzdqvq4ujxgsvx57cqhzskksixj2rhhkvibvcxsfabq

**Comment by kernelogic** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebocwze2jczuw6nt4v24zyxkaefjlos7fhvn2hwoe4qc6njpqo72e 
#### Address 
> f1klrehuwhzfw6boiiywdi7pikztsob4kkieivcwq
#### Datacap Allocated
> 1.17PiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebocwze2jczuw6nt4v24zyxkaefjlos7fhvn2hwoe4qc6njpqo72e

**Comment by kernelogic** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedltw5imhu7yosijn5ilboic5cbm7nm5zebisrg2p6lvlsuxuztog 
#### Address 
> f1klrehuwhzfw6boiiywdi7pikztsob4kkieivcwq
#### Datacap Allocated
> 2.34PiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedltw5imhu7yosijn5ilboic5cbm7nm5zebisrg2p6lvlsuxuztog

**Comment by data-programs** [comment]
<img width="32" alt="KYC" Verified src="https://stable.filplus.storage/images/filplus-kyc-verified-badge.png"/>

This user’s identity has been verified through [filplus.storage](https://filplus.storage)
