### ISSUE TITLE
Speedium - Distributed Archives for Neurophysiology Data Integration

### ISSUE THREAD

**Issue by cryptowhizzard** [filecoin-project/filecoin-plus-large-datasets#486]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Speedium network
- Website / Social Media: www.speedium.nl
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5 PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 300 TiB
- On-chain address for first allocation: f1xlnnzzl2d73amahvsu5uyfwdascodwtw6lopw5y

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Speedium / Dcent has engaged in Slingshot starting 2.6. We have successfully stored more than 15 differerent datasets with 20+ different miners.

```

What is the primary source of funding for this project?
```
Company account
```

What other projects/ecosystem stakeholders is this project associated with?
```
No related association
```

## Use-case details

Describe the data being stored onto Filecoin
```
DANDI is a public archive of neurophysiology datasets, including raw and processed data, and associated software containers. Datasets are shared according to a Creative Commons CC0 or CC-BY licenses. The data archive provides a broad range of cellular neurophysiology data. This includes electrode and optical recordings, and associated imaging data using a set of community standards: NWB:N - NWB:Neurophysiology, BIDS - Brain Imaging Data Structure, and NIDM - Neuro Imaging Data Model.
```

Where was the data in this dataset sourced from?
```
AWS
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://registry.opendata.aws/dandiarchive/
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes.
```

What is the expected retrieval frequency for this data?
```
Multiple times p/y
```

For how long do you plan to keep this dataset stored on Filecoin?
```
18 months or longer
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
EU / US / Australia / Asia
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
The data will be transferred both offline and online.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We have a few providers who have been working with us during Slingshot Restore program and we'd like to continue working with them for ongoing Slingshot competition.
```

How will you be distributing deals across storage providers?
```
Max 2 copy's per storage provider if stored on different miners / locations.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, we have the resources.
```

**Comment by Sunnyiscoming** [comment]
@cryptowhizzard Hi,

Total amount of DataCap being requested (between 500 TiB and 5 PiB): 6 PiB
Please adjust total amount from 6 PiB to no more than 5 PiB.

**Comment by cryptowhizzard** [comment]
@Sunnyiscoming -> done.

**Comment by Sunnyiscoming** [comment]
You have submitted a large number of dataset applications.
I would like to confirm the data set size with you. But I can't see the size of amazon's public data set. Can you provide any evidence to prove it?

**Comment by cryptowhizzard** [comment]
Hello @Sunnyiscoming 

The total size of this dataset is 535.6 TiB.

You can retrieve that data with the following command according to AWS official source:

aws s3 ls --summarize --human-readable --recursive s3://bucket-name/

**Comment by raghavrmadya** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5 PiB

**Expected weekly DataCap usage rate**

> 500 TiB

**Client address**

> f1xlnnzzl2d73amahvsu5uyfwdascodwtw6lopw5y

**Comment by raghavrmadya** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5 PiB

**Expected weekly DataCap usage rate**

> 300 TiB

**Client address**

> f1xlnnzzl2d73amahvsu5uyfwdascodwtw6lopw5y

**Comment by bmcnabb25** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb2mpaqf6moryzzzw2r66idvzghgeaojdffvq6fakzwb2kqorhrtm 
#### Address 
> f1xlnnzzl2d73amahvsu5uyfwdascodwtw6lopw5y
#### Datacap Allocated
> 150.00TiB
#### Signer Address
> f1jqk7xok5kautet2knhwlg74jvcfbrqlj47kbp2i
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb2mpaqf6moryzzzw2r66idvzghgeaojdffvq6fakzwb2kqorhrtm

**Comment by kernelogic** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebcuujjafblwsmieqchzlwqy7cgor4di2qomfxf7pbsw2w7ouezwu 
#### Address 
> f1xlnnzzl2d73amahvsu5uyfwdascodwtw6lopw5y
#### Datacap Allocated
> 150.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebcuujjafblwsmieqchzlwqy7cgor4di2qomfxf7pbsw2w7ouezwu

**Comment by MegTei** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceddtzvgkckisl6fy76qyjqkt5wxqu2622xfjkqf6z7bzhwue77nns 
#### Address 
> f1xlnnzzl2d73amahvsu5uyfwdascodwtw6lopw5y
#### Datacap Allocated
> 150.00TiB
#### Signer Address
> f1ystxl2ootvpirpa7ebgwl7vlhwkbx2r4zjxwe5i
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceddtzvgkckisl6fy76qyjqkt5wxqu2622xfjkqf6z7bzhwue77nns

**Comment by Reiers** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceazdz2r4azmca7pcziyr7ha4u2imi7f32tfzpfcmwuqnvlgohbeog 
#### Address 
> f1xlnnzzl2d73amahvsu5uyfwdascodwtw6lopw5y
#### Datacap Allocated
> 150.00TiB
#### Signer Address
> f1oz43ckvmtxmmsfzqm6bpnemqlavz4ifyl524chq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceazdz2r4azmca7pcziyr7ha4u2imi7f32tfzpfcmwuqnvlgohbeog

**Comment by Reiers** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebyqdysgdlfxfenmpe2llfl4u6eubnmsks6lrjxv2r7gspmwpqh3k 
#### Address 
> f1xlnnzzl2d73amahvsu5uyfwdascodwtw6lopw5y
#### Datacap Allocated
> 150.00TiB
#### Signer Address
> f1oz43ckvmtxmmsfzqm6bpnemqlavz4ifyl524chq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebyqdysgdlfxfenmpe2llfl4u6eubnmsks6lrjxv2r7gspmwpqh3k

**Comment by s0nik42** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceamat5ognecshm45cvq4ndqohp647xyvr2eyg7u2cikgsle2x6hqu 
#### Address 
> f1xlnnzzl2d73amahvsu5uyfwdascodwtw6lopw5y
#### Datacap Allocated
> 150.00TiB
#### Signer Address
> f1wxhnytjmklj2czezaqcfl7eb4nkgmaxysnegwii
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceamat5ognecshm45cvq4ndqohp647xyvr2eyg7u2cikgsle2x6hqu

**Comment by psh0691** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecashdgas4t6saa7nfrugaljxgdxakssmvruxym7cnccdzru6aspq 
#### Address 
> f1xlnnzzl2d73amahvsu5uyfwdascodwtw6lopw5y
#### Datacap Allocated
> 1.17PiB
#### Signer Address
> f1qdko4jg25vo35qmyvcrw4ak4fmuu3f5rif2kc7i
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecashdgas4t6saa7nfrugaljxgdxakssmvruxym7cnccdzru6aspq

**Comment by newwebgroup** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebjebnb47uy453sidfhmq2mbpo6pd5fl3tdy7mfjvhuzketappfn4 
#### Address 
> f1xlnnzzl2d73amahvsu5uyfwdascodwtw6lopw5y
#### Datacap Allocated
> 1.17PiB
#### Signer Address
> f1e77zuityhvvw6u2t6tb5qlnsegy2s67qs4lbbbq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebjebnb47uy453sidfhmq2mbpo6pd5fl3tdy7mfjvhuzketappfn4

**Comment by Reiers** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedhyvj7tqqlirgl2xkeikrfrdr74ogv2ela3awjx2wktuunopsqwi 
#### Address 
> f1xlnnzzl2d73amahvsu5uyfwdascodwtw6lopw5y
#### Datacap Allocated
> 2.34PiB
#### Signer Address
> f1oz43ckvmtxmmsfzqm6bpnemqlavz4ifyl524chq
#### Id
> 694a123b-951c-42f4-8b9b-194876621ce2
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedhyvj7tqqlirgl2xkeikrfrdr74ogv2ela3awjx2wktuunopsqwi

**Comment by kernelogic** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedbrk7ed4i5zej2isbzhzbzc6tgnlx26kymb4xe6g5bhaj6cgslck 
#### Address 
> f1xlnnzzl2d73amahvsu5uyfwdascodwtw6lopw5y
#### Datacap Allocated
> 2.34PiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### Id
> 694a123b-951c-42f4-8b9b-194876621ce2
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedbrk7ed4i5zej2isbzhzbzc6tgnlx26kymb4xe6g5bhaj6cgslck

**Comment by filplus-checker** [comment]
## DataCap and CID Checker Report[^1]
 - Organization: `Speedium network`
 - Client: `f1xlnnzzl2d73amahvsu5uyfwdascodwtw6lopw5y`
### Storage Provider Distribution
The below table shows the distribution of storage providers that have stored data for this client.

If this is the first time a provider takes verified deal, it will be marked as `new`.

For most of the datacap application, below restrictions should apply.
 - Storage provider should not exceed 25% of total datacap.
 - Storage provider should not be storing duplicate data for more than 20%.
 - Storage provider should have published its public IP address.
 - All storage providers should be located in different regions.

⚠️ [f01901765](https://filfox.info/en/address/f01901765) has sealed 27.86% of total datacap.

| Provider                                                    |                           Location | Total Deals Sealed | Percentage | Unique Data | Duplicate Deals |
| :---------------------------------------------------------- | ---------------------------------: | -----------------: | ---------: | ----------: | --------------: |
| [f01901765](https://filfox.info/en/address/f01901765)       |              Jiaxing, Zhejiang, CN |         769.27 TiB |     27.86% |  769.27 TiB |           0.00% |
| [f01985745](https://filfox.info/en/address/f01985745)`new`  |                  Dallas, Texas, US |         395.50 TiB |     14.32% |  395.50 TiB |           0.00% |
| [f033462](https://filfox.info/en/address/f033462)`new`      |                  Dallas, Texas, US |         326.64 TiB |     11.83% |  326.64 TiB |           0.00% |
| [f01927554](https://filfox.info/en/address/f01927554)       |            Shenzhen, Guangdong, CN |         316.36 TiB |     11.46% |  315.77 TiB |           0.19% |
| [f01985775](https://filfox.info/en/address/f01985775)`new`  |                  Dallas, Texas, US |         250.91 TiB |      9.09% |  250.91 TiB |           0.00% |
| [f01518369](https://filfox.info/en/address/f01518369)       |           San Jose, California, US |         170.00 TiB |      6.16% |  170.00 TiB |           0.00% |
| [f01923787](https://filfox.info/en/address/f01923787)       |            Shenzhen, Guangdong, CN |         133.75 TiB |      4.84% |  133.75 TiB |           0.00% |
| [f01938357](https://filfox.info/en/address/f01938357)       |        Sydney, New South Wales, AU |         133.37 TiB |      4.83% |  133.37 TiB |           0.00% |
| [f01240218](https://filfox.info/en/address/f01240218)       |               Chengdu, Sichuan, CN |          78.13 TiB |      2.83% |   78.13 TiB |           0.00% |
| [f01882177](https://filfox.info/en/address/f01882177)       |           Singapore, Singapore, SG |          53.50 TiB |      1.94% |   53.50 TiB |           0.00% |
| [f01878005](https://filfox.info/en/address/f01878005)       |           Singapore, Singapore, SG |          50.73 TiB |      1.84% |   50.73 TiB |           0.00% |
| [f01880047](https://filfox.info/en/address/f01880047)       |           Singapore, Singapore, SG |          49.13 TiB |      1.78% |   49.13 TiB |           0.00% |
| [f01877571](https://filfox.info/en/address/f01877571)       |           Singapore, Singapore, SG |          33.49 TiB |      1.21% |   33.49 TiB |           0.00% |
| [f01923786](https://filfox.info/en/address/f01923786)       | Hong Kong, Central and Western, HK |         128.00 GiB |      0.00% |  128.00 GiB |           0.00% |

![Provider Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/486/1671097185915.png)
### Deal Data Replication
The below table shows how each many unique data are replicated across storage providers.
- No more than 25% of unique data are stored with less than 4 providers.

⚠️ 65.14% of deals are for data replicated across less than 4 storage providers.

| Unique Data Size | Total Deals Made | Number of Providers | Deal Percentage |
| ---------------: | ---------------: | ------------------: | --------------: |
|        93.44 TiB |        93.44 TiB |                   1 |           3.38% |
|       355.86 TiB |       711.72 TiB |                   2 |          25.78% |
|       331.06 TiB |       993.19 TiB |                   3 |          35.97% |
|       126.13 TiB |       504.64 TiB |                   4 |          18.28% |
|        72.89 TiB |       364.67 TiB |                   5 |          13.21% |
|        15.50 TiB |        93.25 TiB |                   6 |           3.38% |

![Replication Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/486/1671097186652.png)
### Deal Data Shared with other Clients
The below table shows how many unique data are shared with other clients.
Usually different applications owns different data and should not resolve to the same CID.

⚠️ CID sharing has been observed.

| Other Client                                                                                                          | Application                                                                                     | Total Deals Affected | Unique CIDs |        Verifier |
| :-------------------------------------------------------------------------------------------------------------------- | :---------------------------------------------------------------------------------------------- | -------------------: | ----------: | --------------: |
| [f1klrehuwhzfw6boiiywdi7pikztsob4kkieivcwq](https://filfox.info/en/address/f1klrehuwhzfw6boiiywdi7pikztsob4kkieivcwq) | [Speedium network](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/485) |           288.00 GiB |           9 | LDN v3 multisig |

[^1]: To manually trigger this report, add a comment with text `checker:manualTrigger`

**Comment by kernelogic** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebl65nekceldwvdhivuczguhn2jsihu6hms2jdf5ay6hbgkcgekzk 
#### Address 
> f1xlnnzzl2d73amahvsu5uyfwdascodwtw6lopw5y
#### Datacap Allocated
> 475.76TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### Id
> e6008956-8840-4229-ac96-fbe446773a08
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebl65nekceldwvdhivuczguhn2jsihu6hms2jdf5ay6hbgkcgekzk

**Comment by filplusapp** [comment]
ERROR: offer error: retrieval query offer errored: failed to fetch piece to retrieve from: getting pieces for cid baga6ea4seaqalllcmbwmyhjtuei6oa7dekhvmj5gfn7dwbqpjy4fulryoywncca: getting pieces containing block baga6ea4seaqalllcmbwmyhjtuei6oa7dekhvmj5gfn7dwbqpjy4fulryoywncca: failed to lookup index for mh 92202005ad62606ccc1d33a111e703e3228f5627a62b7e3b060f4e385a2e38762cd108, err: datastore: key not found

ERROR: offer error: retrieval query offer errored: failed to fetch piece to retrieve from: getting pieces for cid baga6ea4seaqf6f3jeermghocg7gkg7jvdlq5mt7sdkp65ezdyw5oeiz72chdsaq: getting pieces containing block baga6ea4seaqf6f3jeermghocg7gkg7jvdlq5mt7sdkp65ezdyw5oeiz72chdsaq: failed to lookup index for mh 9220205f17692122c31dc237cca37d351ae1d64ff21a9fee9323c5bae2233fd08e3902, err: datastore: key not found

ERROR: offer error: retrieval query offer errored: failed to fetch piece to retrieve from: getting pieces for cid baga6ea4seaqf6f3jeermghocg7gkg7jvdlq5mt7sdkp65ezdyw5oeiz72chdsaq: getting pieces containing block baga6ea4seaqf6f3jeermghocg7gkg7jvdlq5mt7sdkp65ezdyw5oeiz72chdsaq: failed to lookup index for mh 9220205f17692122c31dc237cca37d351ae1d64ff21a9fee9323c5bae2233fd08e3902, err: datastore: key not found

**Comment by lvschouwen** [comment]
checker:manualTrigger

**Comment by cryptowhizzard** [comment]
Hi,

It came to our attention that due a Mysql problem ( full disk ) we send out some duplicate deals to f02033496 ( +/- 160 ).
We will terminate those asap.

**Comment by lvschouwen** [comment]
checker:manualTrigger

**Comment by data-programs** [comment]
<img width="32" alt="KYC" Verified src="https://stable.filplus.storage/images/filplus-kyc-verified-badge.png"/>

This user’s identity has been verified through [filplus.storage](https://filplus.storage)
