### ISSUE TITLE
Speedium - Galaxy Evolution Explorer Satellite dataset

### ISSUE THREAD

**Issue by cryptowhizzard** [filecoin-project/filecoin-plus-large-datasets#487]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Speedium network
- Website / Social Media: www.speedium.nl
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5 PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 500 TiB
- On-chain address for first allocation: f1kyaa43uqypbcsv5isyd4xw7lvgjcumfzqsxag7y

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Speedium / Dcent has engaged in Slingshot starting 2.6. We have successfully stored more than 15 differerent datasets with 20+ different miners.

```

What is the primary source of funding for this project?
```
Company account
```

What other projects/ecosystem stakeholders is this project associated with?
```
No related association
```

## Use-case details

Describe the data being stored onto Filecoin
```
The Galaxy Evolution Explorer Satellite (GALEX) was a NASA mission led by the California Institute of Technology, whose primary goal was to investigates how star formation in galaxies evolved from the early Universe up to the present. GALEX used microchannel plate detectors to obtain direct images in the near-UV (NUV) and far-UV (FUV), and a grism to disperse light for low resolution spectroscopy. More information about GALEX is available at MAST
```

Where was the data in this dataset sourced from?
```
AWS
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://registry.opendata.aws/galex/
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes.
```

What is the expected retrieval frequency for this data?
```
Multiple times p/y
```

For how long do you plan to keep this dataset stored on Filecoin?
```
18 months or longer
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
EU / US / Australia / Asia
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
The data will be transferred both offline and online.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We have a few providers who have been working with us during Slingshot Restore program and we'd like to continue working with them for ongoing Slingshot competition.
```

How will you be distributing deals across storage providers?
```
Max 2 copy's per storage provider if stored on different miners / locations.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, we have the resources.
```

**Comment by Sunnyiscoming** [comment]
@cryptowhizzard Hi,

Total amount of DataCap being requested (between 500 TiB and 5 PiB): 6 PiB
Please adjust total amount from 6 PiB to no more than 5 PiB.

**Comment by cryptowhizzard** [comment]
@Sunnyiscoming -> done

**Comment by Sunnyiscoming** [comment]
You have submitted a large number of dataset applications.
I would like to confirm the data set size with you. But I can't see the size of amazon's public data set. Can you provide any evidence to prove it?

**Comment by cryptowhizzard** [comment]
Hello @Sunnyiscoming

The total size of this dataset is 591.1 TiB

You can retrieve that data with the following command according to AWS official source:

aws s3 ls --summarize --human-readable --recursive s3://bucket-name/

**Comment by raghavrmadya** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5 PiB

**Expected weekly DataCap usage rate**

> 500 TiB

**Client address**

> f1kyaa43uqypbcsv5isyd4xw7lvgjcumfzqsxag7y

**Comment by raghavrmadya** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5 PiB

**Expected weekly DataCap usage rate**

> 500 TiB

**Client address**

> f1kyaa43uqypbcsv5isyd4xw7lvgjcumfzqsxag7y

**Comment by kernelogic** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec6ks7egbsih53lripdz64m4j32psyt7msl2szsfxiiwgjt7sg6us 
#### Address 
> f1kyaa43uqypbcsv5isyd4xw7lvgjcumfzqsxag7y
#### Datacap Allocated
> 250.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec6ks7egbsih53lripdz64m4j32psyt7msl2szsfxiiwgjt7sg6us

**Comment by IreneYoung** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedozpd4r5uzc766rqzp4bpzjoxdvf75wunuoienrludwh7rf7xomu 
#### Address 
> f1kyaa43uqypbcsv5isyd4xw7lvgjcumfzqsxag7y
#### Datacap Allocated
> 250.00TiB
#### Signer Address
> f1d4gmpqz3execjj2wvrxuuhvbms5mzh7t7yqrviq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedozpd4r5uzc766rqzp4bpzjoxdvf75wunuoienrludwh7rf7xomu

**Comment by raghavrmadya** [comment]
## DataCap Allocation requested

#### Multisig Notary address
> f01858410

#### Client address
> f1kyaa43uqypbcsv5isyd4xw7lvgjcumfzqsxag7y

#### DataCap allocation requested
> 250TiB

**Comment by raghavrmadya** [comment]
@kernelogic @IreneYoung Please sign again.

**Comment by s0nik42** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebi5jjdbrdcnb44hmj5qdc2geize2itjf5sw5lc5p4zyjsforurn6 
#### Address 
> f1kyaa43uqypbcsv5isyd4xw7lvgjcumfzqsxag7y
#### Datacap Allocated
> 250.00TiB
#### Signer Address
> f1wxhnytjmklj2czezaqcfl7eb4nkgmaxysnegwii
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebi5jjdbrdcnb44hmj5qdc2geize2itjf5sw5lc5p4zyjsforurn6

**Comment by MegTei** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebsils3boenjqm2upakb7ykrxl6tgmc6rcmdmorexoetg4m5p45pk 
#### Address 
> f1kyaa43uqypbcsv5isyd4xw7lvgjcumfzqsxag7y
#### Datacap Allocated
> 250.00TiB
#### Signer Address
> f1ystxl2ootvpirpa7ebgwl7vlhwkbx2r4zjxwe5i
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebsils3boenjqm2upakb7ykrxl6tgmc6rcmdmorexoetg4m5p45pk

**Comment by Reiers** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebonmr7ste2k3byjmbcr2ps7ud4xwj2jpyki3q4ziq46ffa67ajew 
#### Address 
> f1kyaa43uqypbcsv5isyd4xw7lvgjcumfzqsxag7y
#### Datacap Allocated
> 250.00TiB
#### Signer Address
> f1oz43ckvmtxmmsfzqm6bpnemqlavz4ifyl524chq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebonmr7ste2k3byjmbcr2ps7ud4xwj2jpyki3q4ziq46ffa67ajew

**Comment by psh0691** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecx2x65hsaprgs3xa6drhkdkfkkafbfcj5cgitytcjqrkqm6lixg6 
#### Address 
> f1kyaa43uqypbcsv5isyd4xw7lvgjcumfzqsxag7y
#### Datacap Allocated
> 250.00TiB
#### Signer Address
> f1qdko4jg25vo35qmyvcrw4ak4fmuu3f5rif2kc7i
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecx2x65hsaprgs3xa6drhkdkfkkafbfcj5cgitytcjqrkqm6lixg6

**Comment by kernelogic** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecng2csjfqcomsvdqyagivglbzslczgie3yft4gvdvye6qagaiqxs 
#### Address 
> f1kyaa43uqypbcsv5isyd4xw7lvgjcumfzqsxag7y
#### Datacap Allocated
> 1.95PiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecng2csjfqcomsvdqyagivglbzslczgie3yft4gvdvye6qagaiqxs

**Comment by xinaxu** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceajfizwaxvqqclap3rxuw6vv2jj5sjuk64cffp45cfrimzwcpu6kg 
#### Address 
> f1kyaa43uqypbcsv5isyd4xw7lvgjcumfzqsxag7y
#### Datacap Allocated
> 1.58PiB
#### Signer Address
> f1k3ysofkrrmqcot6fkx4wnezpczlltpirmrpsgui
#### Id
> d2d403e2-5957-4d00-937d-bd82d6ff5a72
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceajfizwaxvqqclap3rxuw6vv2jj5sjuk64cffp45cfrimzwcpu6kg

**Comment by kernelogic** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedkxc3tyfpvn7jz767picaibncmjd2aoziqnbqzefid6e5glxnjtm 
#### Address 
> f1kyaa43uqypbcsv5isyd4xw7lvgjcumfzqsxag7y
#### Datacap Allocated
> 1.58PiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### Id
> d2d403e2-5957-4d00-937d-bd82d6ff5a72
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedkxc3tyfpvn7jz767picaibncmjd2aoziqnbqzefid6e5glxnjtm

**Comment by filplus-checker** [comment]
## DataCap and CID Checker Report[^1]
 - Organization: `Speedium network`
 - Client: `f1kyaa43uqypbcsv5isyd4xw7lvgjcumfzqsxag7y`
### Storage Provider Distribution
The below table shows the distribution of storage providers that have stored data for this client.

If this is the first time a provider takes verified deal, it will be marked as `new`.

For most of the datacap application, below restrictions should apply.
 - Storage provider should not exceed 25% of total datacap.
 - Storage provider should not be storing duplicate data for more than 20%.
 - Storage provider should have published its public IP address.
 - All storage providers should be located in different regions.

⚠️ 30.82% of total deal sealed by [f022352](https://filfox.info/en/address/f022352) are duplicate data.

⚠️ 21.90% of total deal sealed by [f0855584](https://filfox.info/en/address/f0855584) are duplicate data.

⚠️ 21.13% of total deal sealed by [f01908299](https://filfox.info/en/address/f01908299) are duplicate data.

⚠️ [f01908299](https://filfox.info/en/address/f01908299) has unknown IP location.

⚠️ 50.09% of total deal sealed by [f01199430](https://filfox.info/en/address/f01199430) are duplicate data.

⚠️ 41.68% of total deal sealed by [f01720359](https://filfox.info/en/address/f01720359) are duplicate data.

⚠️ 61.24% of total deal sealed by [f01771403](https://filfox.info/en/address/f01771403) are duplicate data.

⚠️ 31.56% of total deal sealed by [f01937642](https://filfox.info/en/address/f01937642) are duplicate data.

⚠️ 68.57% of total deal sealed by [f01385207](https://filfox.info/en/address/f01385207) are duplicate data.

| Provider                                                    |                           Location | Total Deals Sealed | Percentage | Unique Data | Duplicate Deals |
| :---------------------------------------------------------- | ---------------------------------: | -----------------: | ---------: | ----------: | --------------: |
| [f01901765](https://filfox.info/en/address/f01901765)       |              Jiaxing, Zhejiang, CN |         674.61 TiB |     19.44% |  674.61 TiB |           0.00% |
| [f01933917](https://filfox.info/en/address/f01933917)       | Hong Kong, Central and Western, HK |         342.30 TiB |      9.86% |  342.30 TiB |           0.00% |
| [f01392893](https://filfox.info/en/address/f01392893)       |       Amsterdam, North Holland, NL |         302.46 TiB |      8.72% |  297.99 TiB |           1.48% |
| [f022352](https://filfox.info/en/address/f022352)           |                     Oslo, Oslo, NO |         296.58 TiB |      8.55% |  205.18 TiB |          30.82% |
| [f0855584](https://filfox.info/en/address/f0855584)         |              Lincoln, Nebraska, US |         209.18 TiB |      6.03% |  163.37 TiB |          21.90% |
| [f01908299](https://filfox.info/en/address/f01908299)`new`  |                            Unknown |         198.55 TiB |      5.72% |  156.60 TiB |          21.13% |
| [f01345523](https://filfox.info/en/address/f01345523)       |            Antwerpen, Flanders, BE |         191.44 TiB |      5.52% |  190.07 TiB |           0.72% |
| [f01906874](https://filfox.info/en/address/f01906874)`new`  |                   Plano, Texas, US |         190.83 TiB |      5.50% |  190.83 TiB |           0.00% |
| [f01926635](https://filfox.info/en/address/f01926635)       | Hong Kong, Central and Western, HK |         172.28 TiB |      4.96% |  172.28 TiB |           0.00% |
| [f01091851](https://filfox.info/en/address/f01091851)       |              Lincoln, Nebraska, US |         148.91 TiB |      4.29% |  148.91 TiB |           0.00% |
| [f01907545](https://filfox.info/en/address/f01907545)       |                 Xi’an, Shaanxi, CN |         134.00 TiB |      3.86% |  134.00 TiB |           0.00% |
| [f01736668](https://filfox.info/en/address/f01736668)`new`  |              Lincoln, Nebraska, US |         125.58 TiB |      3.62% |  125.58 TiB |           0.00% |
| [f01199430](https://filfox.info/en/address/f01199430)       |   Heerhugowaard, North Holland, NL |         113.92 TiB |      3.28% |   56.86 TiB |          50.09% |
| [f01720359](https://filfox.info/en/address/f01720359)       |   Heerhugowaard, North Holland, NL |          95.06 TiB |      2.74% |   55.44 TiB |          41.68% |
| [f01786387](https://filfox.info/en/address/f01786387)       |   Heerhugowaard, North Holland, NL |          89.79 TiB |      2.59% |   89.79 TiB |           0.00% |
| [f01926686](https://filfox.info/en/address/f01926686)       |             Hangzhou, Zhejiang, CN |          86.74 TiB |      2.50% |   86.74 TiB |           0.00% |
| [f01240218](https://filfox.info/en/address/f01240218)`new`  |               Chengdu, Sichuan, CN |          53.88 TiB |      1.55% |   53.88 TiB |           0.00% |
| [f01885088](https://filfox.info/en/address/f01885088)       | Hong Kong, Central and Western, HK |          22.80 TiB |      0.66% |   22.80 TiB |           0.00% |
| [f01771403](https://filfox.info/en/address/f01771403)       |   Heerhugowaard, North Holland, NL |          10.56 TiB |      0.30% |    4.09 TiB |          61.24% |
| [f01937642](https://filfox.info/en/address/f01937642)       |   Heerhugowaard, North Holland, NL |           9.41 TiB |      0.27% |    6.44 TiB |          31.56% |
| [f01385207](https://filfox.info/en/address/f01385207)       |              Lincoln, Nebraska, US |           1.09 TiB |      0.03% |  352.00 GiB |          68.57% |

![Provider Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/487/1671097215506.png)
### Deal Data Replication
The below table shows how each many unique data are replicated across storage providers.
- No more than 25% of unique data are stored with less than 4 providers.

⚠️ 30.78% of deals are for data replicated across less than 4 storage providers.

| Unique Data Size | Total Deals Made | Number of Providers | Deal Percentage |
| ---------------: | ---------------: | ------------------: | --------------: |
|        69.77 TiB |        70.18 TiB |                   1 |           2.02% |
|       269.55 TiB |       539.99 TiB |                   2 |          15.56% |
|       152.25 TiB |       457.98 TiB |                   3 |          13.20% |
|       128.87 TiB |       517.56 TiB |                   4 |          14.92% |
|        86.33 TiB |       432.80 TiB |                   5 |          12.47% |
|        56.71 TiB |       341.15 TiB |                   6 |           9.83% |
|        54.84 TiB |       392.87 TiB |                   7 |          11.32% |
|        34.92 TiB |       322.38 TiB |                   8 |           9.29% |
|        13.39 TiB |       205.11 TiB |                   9 |           5.91% |
|         3.03 TiB |       142.09 TiB |                  10 |           4.09% |
|       960.00 GiB |        44.44 TiB |                  11 |           1.28% |
|        32.00 GiB |         1.81 TiB |                  12 |           0.05% |
|        32.00 GiB |         1.63 TiB |                  13 |           0.05% |

![Replication Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/487/1671097216207.png)
### Deal Data Shared with other Clients
The below table shows how many unique data are shared with other clients.
Usually different applications owns different data and should not resolve to the same CID.

✔️ No CID sharing has been observed.

[^1]: To manually trigger this report, add a comment with text `checker:manualTrigger`

**Comment by s0nik42** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacea55ppktx2hulcegzm6lqangoiufjweskbbxanmhoji3db27p3d34 
#### Address 
> f1kyaa43uqypbcsv5isyd4xw7lvgjcumfzqsxag7y
#### Datacap Allocated
> 5.27TiB
#### Signer Address
> f1wxhnytjmklj2czezaqcfl7eb4nkgmaxysnegwii
#### Id
> c2fa38f3-8132-4be7-9094-028bf1f9b661
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacea55ppktx2hulcegzm6lqangoiufjweskbbxanmhoji3db27p3d34

**Comment by cryptowhizzard** [comment]
About the duplicates above:

We have had issues with Singularity building this set causing duplicate carfiles. When we discovered this a few weeks ago these were reported ( and fixed ).

**Comment by flyworker** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaxifyvy5kjivthmvmdespyptennb5olv325iovrugnbr3isqfvas 
#### Address 
> f1kyaa43uqypbcsv5isyd4xw7lvgjcumfzqsxag7y
#### Datacap Allocated
> 5.27TiB
#### Signer Address
> f1hlubjsdkv4wmsdadihloxgwrz3j3ernf6i3cbpy
#### Id
> c2fa38f3-8132-4be7-9094-028bf1f9b661
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaxifyvy5kjivthmvmdespyptennb5olv325iovrugnbr3isqfvas

**Comment by cryptowhizzard** [comment]
@raghavrmadya 

seems we are missing 1 PB of the cap due a miss when the faucet was empty.

is it possible to correct that?  As stated above things are tight already due the singularity issue.

**Comment by cryptowhizzard** [comment]
It seems 1 PB is missing here.

![Scherm­afbeelding 2022-12-19 om 16 23 44](https://user-images.githubusercontent.com/36404435/208460053-9750973e-5980-4f6c-b588-3ef17122d90f.png)

**Comment by s0nik42** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecqr25ca67m6ud2ksptzmrukueyngfnbjdrd5hnpwbuoh5qo6m7w6 
#### Address 
> f1kyaa43uqypbcsv5isyd4xw7lvgjcumfzqsxag7y
#### Datacap Allocated
> 10.23GiB
#### Signer Address
> f1wxhnytjmklj2czezaqcfl7eb4nkgmaxysnegwii
#### Id
> a6cba394-e70e-4f30-b0d7-39fde574757c
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecqr25ca67m6ud2ksptzmrukueyngfnbjdrd5hnpwbuoh5qo6m7w6

**Comment by Kevin-FF-USA** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 1 PiB

**Expected weekly DataCap usage rate**

> 500 TiB

**Client address**

> f1kyaa43uqypbcsv5isyd4xw7lvgjcumfzqsxag7y

**Comment by Kevin-FF-USA** [comment]
Simon Kim to Everyone (11:51 AM)
### Datacap Request Trigger
**Total DataCap requested**

> 1 PiB

**Expected weekly DataCap usage rate**

> 500 TiB

**Client address**

> f1kyaa43uqypbcsv5isyd4xw7lvgjcumfzqsxag7y

**Comment by data-programs** [comment]
<img width="32" alt="KYC" Verified src="https://stable.filplus.storage/images/filplus-kyc-verified-badge.png"/>

This user’s identity has been verified through [filplus.storage](https://filplus.storage)
