### ISSUE TITLE
Speedium - NIH NCBI Sequence Read Archive [ 1 / 27 ]

### ISSUE THREAD

**Issue by cryptowhizzard** [filecoin-project/filecoin-plus-large-datasets#488]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Speedium network
- Website / Social Media: www.speedium.nl
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5 PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 500 TiB
- On-chain address for first allocation: f1mgnwoczfj25foxn4555wvwyak6rsynzy7z73azy

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Speedium / Dcent has engaged in Slingshot starting 2.6. We have successfully stored more than 15 differerent datasets with 20+ different miners.

```

What is the primary source of funding for this project?
```
Company account
```

What other projects/ecosystem stakeholders is this project associated with?
```
No related association
```

## Use-case details

Describe the data being stored onto Filecoin
```
NIH NCBI Sequence Read Archive (SRA) on AWS
The Sequence Read Archive (SRA), produced by the [National Center for Biotechnology Information (NCBI)](https://www.ncbi.nlm.nih.gov/) at the [National Library of Medicine (NLM)](http://nlm.nih.gov/) at the [National Institutes of Health (NIH)](http://www.nih.gov/), stores raw DNA sequencing data and alignment information from high-throughput sequencing platforms. 
```

Where was the data in this dataset sourced from?
```
AWS
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://registry.opendata.aws/ncbi-sra/
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes.
```

What is the expected retrieval frequency for this data?
```
Multiple times p/y
```

For how long do you plan to keep this dataset stored on Filecoin?
```
18 months or longer
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
EU / US / Australia / Asia
We intend to store 10 replica's of this data. The dataset has a size of 13.4 PiB.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
The data will be transferred both offline and online.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We have a few providers who have been working with us during Slingshot Restore program and we'd like to continue working with them for ongoing Slingshot competition.
```

How will you be distributing deals across storage providers?
```
Max 2 copy's per storage provider if stored on different miners / locations.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, we have the resources.
```

**Comment by Sunnyiscoming** [comment]
1.Total amount of DataCap being requested (between 500 TiB and 5 PiB): 135 PiB
The total amount must be less than 5 PB, maybe you can reapply after one by one.

2.Weekly allocation of DataCap requested (usually between 1-100TiB): 2 PiB
Can you list storage providers and their nodes for proving that you can store 2 PiB per week?

**Comment by cryptowhizzard** [comment]
@Sunnyiscoming That is ok. I will alter this application title then and structure it with 5 PiB batches. It means 27 batches total, so i will alter the title to [ 1 of 27 ] etc. and reference back to this original application as soon as we progress into the next one and are over 50% done with the previous one.

My plan is to distribute these towards Holon , DLTX , PikNik and i will also distribute these to whoever wants them.

**Comment by Sunnyiscoming** [comment]
You have submitted a large number of dataset applications.
I would like to confirm the data set size with you. But I can't see the size of amazon's public data set. Can you provide any evidence to prove it?

**Comment by cryptowhizzard** [comment]
Hello @Sunnyiscoming

The total size of this dataset is 13.14 PiB

You can retrieve that data with the following command according to AWS official source:

aws s3 ls --summarize --human-readable --recursive s3://bucket-name/

The bucket name and all information is on their public page :

https://registry.opendata.aws/ncbi-sra/

**Comment by kevzak** [comment]
@dkkapur @raghavrmadya FYI

**Comment by raghavrmadya** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5 PiB

**Expected weekly DataCap usage rate**

> 500 TiB

**Client address**

> f1mgnwoczfj25foxn4555wvwyak6rsynzy7z73azy

**Comment by raghavrmadya** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5 PiB

**Expected weekly DataCap usage rate**

> 500 TiB

**Client address**

> f1mgnwoczfj25foxn4555wvwyak6rsynzy7z73azy

**Comment by kernelogic** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceczjbjh62cicnux7i7vqvk3kgs6ka7ntrjzoh3sgkgjucttiwbpp4 
#### Address 
> f1mgnwoczfj25foxn4555wvwyak6rsynzy7z73azy
#### Datacap Allocated
> 250.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceczjbjh62cicnux7i7vqvk3kgs6ka7ntrjzoh3sgkgjucttiwbpp4

**Comment by MegTei** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebdajq4eqg3y5y6rq43dby5u2hpymdckvpcpsucukemciuhcvcrbi 
#### Address 
> f1mgnwoczfj25foxn4555wvwyak6rsynzy7z73azy
#### Datacap Allocated
> 250.00TiB
#### Signer Address
> f1ystxl2ootvpirpa7ebgwl7vlhwkbx2r4zjxwe5i
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebdajq4eqg3y5y6rq43dby5u2hpymdckvpcpsucukemciuhcvcrbi

**Comment by IreneYoung** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebadh5hnq6tackw7owez4crnd55dlsmko434sohb2ii3qi3kth5qq 
#### Address 
> f1mgnwoczfj25foxn4555wvwyak6rsynzy7z73azy
#### Datacap Allocated
> 250.00TiB
#### Signer Address
> f1d4gmpqz3execjj2wvrxuuhvbms5mzh7t7yqrviq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebadh5hnq6tackw7owez4crnd55dlsmko434sohb2ii3qi3kth5qq

**Comment by raghavrmadya** [comment]
## DataCap Allocation requested

#### Multisig Notary address
> f01858410

#### Client address
> f1mgnwoczfj25foxn4555wvwyak6rsynzy7z73azy

#### DataCap allocation requested
> 250TiB

**Comment by raghavrmadya** [comment]
@IreneYoung @MegTei , could you please propose and approve this again?

**Comment by kernelogic** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecrgqdv2gevf2zgvnhtge6tgmhdfrkmkb6hyyq4ukq27wrtbd4ki2 
#### Address 
> f1mgnwoczfj25foxn4555wvwyak6rsynzy7z73azy
#### Datacap Allocated
> 250.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecrgqdv2gevf2zgvnhtge6tgmhdfrkmkb6hyyq4ukq27wrtbd4ki2

**Comment by s0nik42** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacect5ucnv5xchr66ejtkulrnd2drzpyqrixsj27r4jl3c66inefrzi 
#### Address 
> f1mgnwoczfj25foxn4555wvwyak6rsynzy7z73azy
#### Datacap Allocated
> 250.00TiB
#### Signer Address
> f1wxhnytjmklj2czezaqcfl7eb4nkgmaxysnegwii
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacect5ucnv5xchr66ejtkulrnd2drzpyqrixsj27r4jl3c66inefrzi

**Comment by psh0691** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced7pdfi2aguynv4agvn4om6aqaocjatgy56vzerfnveow3r5yw2ow 
#### Address 
> f1mgnwoczfj25foxn4555wvwyak6rsynzy7z73azy
#### Datacap Allocated
> 250.00TiB
#### Signer Address
> f1qdko4jg25vo35qmyvcrw4ak4fmuu3f5rif2kc7i
#### Id
> 1404eb4f-0694-4cce-b5b1-073f3e63da4a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced7pdfi2aguynv4agvn4om6aqaocjatgy56vzerfnveow3r5yw2ow

**Comment by psh0691** [comment]
Why is "Request Approved" first instead of "Request Proposed"?

**Comment by kernelogic** [comment]
Faucet is empty now - signing this will cause error anyways.

**Comment by IreneYoung** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec7y6sgzgiagvkar7fgaryzadhimd5bzbo6xrmbgz4dzpbjmsebzq 
#### Address 
> f1mgnwoczfj25foxn4555wvwyak6rsynzy7z73azy
#### Datacap Allocated
> 1.95PiB
#### Signer Address
> f1d4gmpqz3execjj2wvrxuuhvbms5mzh7t7yqrviq
#### Id
> e0d7d4e4-6aaf-4018-9f94-88e491c9026d
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec7y6sgzgiagvkar7fgaryzadhimd5bzbo6xrmbgz4dzpbjmsebzq

**Comment by liyunzhi-666** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedttitvruluqz6k4wsrbfdya5o66zdn2z7vjkbepi2umsdi6y2g3i 
#### Address 
> f1mgnwoczfj25foxn4555wvwyak6rsynzy7z73azy
#### Datacap Allocated
> 1.95PiB
#### Signer Address
> f1pszcrsciyixyuxxukkvtazcokexbn54amf7gvoq
#### Id
> e0d7d4e4-6aaf-4018-9f94-88e491c9026d
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedttitvruluqz6k4wsrbfdya5o66zdn2z7vjkbepi2umsdi6y2g3i

**Comment by filplus-checker** [comment]
## DataCap and CID Checker Report[^1]
 - Organization: `Speedium network`
 - Client: `f1mgnwoczfj25foxn4555wvwyak6rsynzy7z73azy`
### Storage Provider Distribution
The below table shows the distribution of storage providers that have stored data for this client.

If this is the first time a provider takes verified deal, it will be marked as `new`.

For most of the datacap application, below restrictions should apply.
 - Storage provider should not exceed 25% of total datacap.
 - Storage provider should not be storing duplicate data for more than 20%.
 - Storage provider should have published its public IP address.
 - All storage providers should be located in different regions.

⚠️ [f01199430](https://filfox.info/en/address/f01199430) has sealed 30.56% of total datacap.

| Provider                                              |                         Location | Total Deals Sealed | Percentage | Unique Data | Duplicate Deals |
| :---------------------------------------------------- | -------------------------------: | -----------------: | ---------: | ----------: | --------------: |
| [f01199430](https://filfox.info/en/address/f01199430) | Heerhugowaard, North Holland, NL |         338.50 TiB |     30.56% |  331.75 TiB |           1.99% |
| [f01952350](https://filfox.info/en/address/f01952350) |         Maywood Park, Oregon, US |         238.13 TiB |     21.50% |  236.38 TiB |           0.73% |
| [f01944347](https://filfox.info/en/address/f01944347) |         Maywood Park, Oregon, US |         226.63 TiB |     20.46% |  226.63 TiB |           0.00% |
| [f01786387](https://filfox.info/en/address/f01786387) | Heerhugowaard, North Holland, NL |         197.85 TiB |     17.86% |  193.23 TiB |           2.34% |
| [f01937642](https://filfox.info/en/address/f01937642) | Heerhugowaard, North Holland, NL |          64.63 TiB |      5.83% |   61.50 TiB |           4.84% |
| [f01201327](https://filfox.info/en/address/f01201327) | Heerhugowaard, North Holland, NL |          41.89 TiB |      3.78% |   41.89 TiB |           0.00% |

![Provider Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/488/1671097225081.png)
### Deal Data Replication
The below table shows how each many unique data are replicated across storage providers.
- No more than 25% of unique data are stored with less than 4 providers.

⚠️ 100.00% of deals are for data replicated across less than 4 storage providers.

| Unique Data Size | Total Deals Made | Number of Providers | Deal Percentage |
| ---------------: | ---------------: | ------------------: | --------------: |
|       551.44 TiB |       557.60 TiB |                   1 |          50.34% |
|       225.90 TiB |       458.05 TiB |                   2 |          41.35% |
|        29.38 TiB |        91.97 TiB |                   3 |           8.30% |

![Replication Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/488/1671097225671.png)
### Deal Data Shared with other Clients
The below table shows how many unique data are shared with other clients.
Usually different applications owns different data and should not resolve to the same CID.

⚠️ CID sharing has been observed.

| Other Client                                                                                                          | Application                                                                                     | Total Deals Affected | Unique CIDs |        Verifier |
| :-------------------------------------------------------------------------------------------------------------------- | :---------------------------------------------------------------------------------------------- | -------------------: | ----------: | --------------: |
| [f1z7jogzx4x42wtilzb4lu6iotlad5rptt2acbzpi](https://filfox.info/en/address/f1z7jogzx4x42wtilzb4lu6iotlad5rptt2acbzpi) | [Speedium network](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/339) |            29.95 TiB |         909 | LDN v3 multisig |

[^1]: To manually trigger this report, add a comment with text `checker:manualTrigger`

**Comment by kernelogic** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebnwmdr2zkmz54keuk3qpiwwwma7ok4fgtccq7csjhsr7ry4kls5s 
#### Address 
> f1mgnwoczfj25foxn4555wvwyak6rsynzy7z73azy
#### Datacap Allocated
> 1.58PiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### Id
> bcd85d5b-2b7e-44d8-89fd-1fe74c462697
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebnwmdr2zkmz54keuk3qpiwwwma7ok4fgtccq7csjhsr7ry4kls5s

**Comment by s0nik42** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecfz2vpztcwgv225dhf3vouxbiymg4zg76lt3zd7cmmxj6pwigwxw 
#### Address 
> f1mgnwoczfj25foxn4555wvwyak6rsynzy7z73azy
#### Datacap Allocated
> 1.58PiB
#### Signer Address
> f1wxhnytjmklj2czezaqcfl7eb4nkgmaxysnegwii
#### Id
> bcd85d5b-2b7e-44d8-89fd-1fe74c462697
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecfz2vpztcwgv225dhf3vouxbiymg4zg76lt3zd7cmmxj6pwigwxw

**Comment by BDEio** [comment]
@cryptowhizzard Hi! Great to see that you have gotten approval for DataCap!
BDE is a verified deals auction house helping you to get paid storing your data with reliable storage providers. If you need any help, please get in touch.

**Comment by NDLABS-OFFICE** [comment]
f01972364
f1mgnwoczfj25foxn4555wvwyak6rsynzy7z73azy
baga6ea4seaqpq3e5n27iselfe6mlbyebro2miz2vibe6hjaegupgcc3bpesl2di

<img width="1091" alt="image" src="https://user-images.githubusercontent.com/104019147/215748078-b9bb23ba-b9bb-434f-984a-6bfc9a38046f.png">

**Comment by NDLABS-OFFICE** [comment]
f01972376
f01156835
f1mgnwoczfj25foxn4555wvwyak6rsynzy7z73azy

<img width="1096" alt="image" src="https://user-images.githubusercontent.com/104019147/215750231-a64c82f7-ae12-4627-bd58-300b490d02cd.png">
<img width="1063" alt="image" src="https://user-images.githubusercontent.com/104019147/215750253-9ca26633-d556-4040-a7d5-e0792b8cd0ff.png">

**Comment by lvschouwen** [comment]
@NDLABS-OFFICE Thanks for bringing this to our attention but you are doing the retrievals wrong :-)

MinerID f01972364 random retrieval from this set
`# lotus state get-deal 20273117
{
  "Proposal": {
    "PieceCID": {
      "/": "baga6ea4seaqoq6d6mb2h3rtvc5jnkcwc7cphgs2jxbnvwp3juhkmylvp67u3aey"
    },
    "PieceSize": 34359738368,
    "VerifiedDeal": true,
    "Client": "f01880278",
    "Provider": "f01972364",
    "Label": "bafybeieq6ynhp23ji6nsk6bgnl7tizrg6toxj23zijvnhxnpy3qqhrzw7q",
    "StartEpoch": 2493000,
    "EndEpoch": 3984840,
    "StoragePricePerEpoch": "0",
    "ProviderCollateral": "10639918249664389",
    "ClientCollateral": "0"
  },
  "State": {
    "SectorStartEpoch": 2465534,
    "LastUpdatedEpoch": 2561117,
    "SlashEpoch": -1,
    "VerifiedClaim": 2788665
  }
}
# lotus client retrieve --provider f01972364 bafybeieq6ynhp23ji6nsk6bgnl7tizrg6toxj23zijvnhxnpy3qqhrzw7q tmp
Recv 0 B, Paid 0 FIL, Open (New), 0s [1674922066658078673|0]
Recv 0 B, Paid 0 FIL, DealProposed (WaitForAcceptance), 2ms [1674922066658078673|0]
Recv 0 B, Paid 0 FIL, DealAccepted (Accepted), 8.458s [1674922066658078673|0]
Recv 0 B, Paid 0 FIL, PaymentChannelSkip (Ongoing), 8.459s [1674922066658078673|0]
Recv 120 B, Paid 0 FIL, BlocksReceived (Ongoing), 8.459s [1674922066658078673|120]
Recv 481 B, Paid 0 FIL, BlocksReceived (Ongoing), 8.459s [1674922066658078673|481]
Recv 761 B, Paid 0 FIL, BlocksReceived (Ongoing), 8.988s [1674922066658078673|761]
Recv 50.75 KiB, Paid 0 FIL, BlocksReceived (Ongoing), 9.548s [1674922066658078673|51972]
^CERROR: Retrieval Timed Out`

MinerID f01972376 random retrieval from this set
`# lotus state get-deal 20630140
{
  "Proposal": {
    "PieceCID": {
      "/": "baga6ea4seaqnbtfl3u4pncsqjxfwj44onkryu6b3m6bzqvwnv3sz32ytuhe5kli"
    },
    "PieceSize": 34359738368,
    "VerifiedDeal": true,
    "Client": "f01880278",
    "Provider": "f01972376",
    "Label": "bafybeihmcpimebislocpf54xpcubtw7ph57cezmhuwf53amervryjqmrxi",
    "StartEpoch": 2504186,
    "EndEpoch": 3996026,
    "StoragePricePerEpoch": "0",
    "ProviderCollateral": "10784577865477392",
    "ClientCollateral": "0"
  },
  "State": {
    "SectorStartEpoch": 2475398,
    "LastUpdatedEpoch": 2561020,
    "SlashEpoch": -1,
    "VerifiedClaim": 3144896
  }
}
# lotus client retrieve --provider f01972376 bafybeihmcpimebislocpf54xpcubtw7ph57cezmhuwf53amervryjqmrxi tmp
Recv 0 B, Paid 0 FIL, Open (New), 0s [1674922066658078674|0]
Recv 0 B, Paid 0 FIL, DealProposed (WaitForAcceptance), 1ms [1674922066658078674|0]
Recv 0 B, Paid 0 FIL, DealAccepted (Accepted), 6s [1674922066658078674|0]
Recv 0 B, Paid 0 FIL, PaymentChannelSkip (Ongoing), 6.001s [1674922066658078674|0]
Recv 122 B, Paid 0 FIL, BlocksReceived (Ongoing), 6.002s [1674922066658078674|122]
Recv 251 B, Paid 0 FIL, BlocksReceived (Ongoing), 6.002s [1674922066658078674|251]
Recv 639 B, Paid 0 FIL, BlocksReceived (Ongoing), 6.42s [1674922066658078674|639]
Recv 50.63 KiB, Paid 0 FIL, BlocksReceived (Ongoing), 6.421s [1674922066658078674|51850]
^CERROR: Retrieval Timed Out
`

MinerID f01156835 seems to have some issues and we will work with this SP to get it resolved.

**Comment by lvschouwen** [comment]
Disclosure; the "Retrieval Timed Out" is because I issued a control + c because it is not my intention to download everything. Just a test to see if something is received.

**Comment by herrehesse** [comment]
checker: manualTrigger

**Comment by lvschouwen** [comment]
checker:manualTrigger

**Comment by thebeersmith** [comment]
Just addressing the duplicate data on miners f01208803 and f01208189. 
Over the Xmas period, both these miners had issues while snapping. A small number of files had permission issues (i.e. could not be removed from the file system) and were not cleaned up from the ingest pipeline. While our ingest code normally performs a check to ensure a file has not been previously ingested, this check failed with these files.
This has since been sorted.

**Comment by herrehesse** [comment]
Thank you for the explanation, lets check the CID report in a week so see the percentages improve.

**Comment by hyunmoon** [comment]
checker:manualTrigger
