### ISSUE TITLE
[DataCap Application] <dooob> - <NFT>

### ISSUE THREAD

**Issue by dooobnet** [filecoin-project/filecoin-plus-large-datasets#496]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: dooob
- Website / Social Media: https://nft.dooob.net/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 3PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100TiB
- On-chain address for first allocation: f14hjkaphpkm2zv3lgx2vxf3z74amyz46v3r5gryi

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Dooob is based on blockchain technology, and the entire history and origin of the artwork can be traced on the distributed ledger, and no one can cheat or cheat. Rare digital artwork can be easily created, sold, and collected on this platform.
The platform enables artists to gain new sources of income and provides collectors with a place to store or trade artwork assets, guarantee the scarcity and originality of works, and solve issues such as copyright traceability. Artists can auction their creations or sell them for a fixed price. Once an NFT is sold, it can be resold at any price on various NFT exchanges.
```

What is the primary source of funding for this project?
```
Corporate Strategy Fund.
```

What other projects/ecosystem stakeholders is this project associated with?
```
All users interested in NFT
```

## Use-case details

Describe the data being stored onto Filecoin
```
Transaction records / Log files / NFT works / Data file ...
```

Where was the data in this dataset sourced from?
```
dooob platform
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://drive.google.com/file/d/112EkEa6FWd3Jg-QmMnNfV3mIlnXfBG2w/view?usp=sharing
https://drive.google.com/file/d/1lUAojrSJI3zUKzSSvEK3qX4UZKnUxLOx/view?usp=sharing
https://drive.google.com/file/d/1X4qQP774PVHU4o1sBMHdyvqcFDID-2Zz/view?usp=sharing
https://drive.google.com/file/d/1h7JrpuCj-zpsHJn9e_2AkBqNJcMCjrcx/view?usp=sharing
https://drive.google.com/file/d/1m8atOFw-M-qEvu8dvKZxC8Ll1qTuixv2/view?usp=sharing
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes
```

What is the expected retrieval frequency for this data?
```
4 times a year
```

For how long do you plan to keep this dataset stored on Filecoin?
```
540 Days
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Singapore、Hong Kong
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
We plan to use offline services for data transfer.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We accept storage requests from any SP, however retrieval requirements must be met in order to be assigned a DataCap. We will conduct regular search and spot checks. If we cannot search, we will communicate with SP in time to solve the problem. We will conduct SP scoring according to the random check strategy. SPs with too low scores will not be assigned DataCap.
```

How will you be distributing deals across storage providers?
```
equally distributed
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, we have enough resources
```

**Comment by Sunnyiscoming** [comment]
https://whois.whoisxmlapi.com/lookup-report/mw56am6A2o
Estimated domain age: 74 day(s)

![image](https://user-images.githubusercontent.com/105098820/179682339-50653eff-f4a0-4a3b-bd0f-2d578e9a3238.png)
![image](https://user-images.githubusercontent.com/105098820/179680243-ee9837db-d09d-4e3f-9eb8-968c60df6c99.png)
![image](https://user-images.githubusercontent.com/105098820/179679914-2cc62cad-5fa4-43f1-9ac4-d3546ab70eb8.png)
![image](https://user-images.githubusercontent.com/105098820/179679922-f5d38536-db53-4197-8a04-e6d95d57f60e.png)
![image](https://user-images.githubusercontent.com/105098820/179679954-52561d94-45e6-4cdc-be27-79b92496be28.png)
![image](https://user-images.githubusercontent.com/105098820/179680019-890f92e5-3808-435e-ba00-89249a876bcc.png)

**Comment by Sunnyiscoming** [comment]
Any update here?

**Comment by dooobnet** [comment]
> Any update here?

This is a new domain name, its predecessor is https://nft.xfnh.com

**Comment by Sunnyiscoming** [comment]
@dooobnet 
1.What's the relationship between dooob and JIANGSU BANGNING SCIENCE & TECHNOLOGY CO. LTD and Chainup?
2.But there is no data on the website. Can you explain about that?
![image](https://user-images.githubusercontent.com/105098820/182994283-4789a483-b440-4aa5-a2aa-5b435b79004e.png)

**Comment by dooobnet** [comment]
Sorry, our project has been suspended for policy reasons. The data cannot be saved to the filecoin network for the time being
