### ISSUE TITLE
[DataCap Application] F3

### ISSUE THREAD

**Issue by xxcisco** [filecoin-project/filecoin-plus-large-datasets#497]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: F3
- Website / Social Media: https://f3.xyz/  https://twitter.com/f3_f3xyz
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):5PIB
- Weekly allocation of DataCap requested (usually between 1-100TiB):200TiB
- On-chain address for first allocation:f1jvsdgfwf3mo2knxwl6jlqm5oupufykd2ati6liq

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
F3 is an NFT trading platform with 60 senior technical teams worldwide, 28K Twitter followers and 20K telegram followers. F3 issued the platform's NFT, and 300 copies of the genesis period have been sold out.

F3 enables users to discover and trade NFT products, and can also help creators to create and sell NFTs. F3 will provide a series of professional and free support for high-quality NFT products settled on the F3 platform.

F3 is very concerned about Filecoin. We plan to wait until the launch of FVM, and all NFT products on the F3 platform will be settled with FIL, becoming the world's only and largest NFT trading platform based on FIL settlement.
```

What is the primary source of funding for this project?
```
The founder of F3 owns a lot of BTC\ETH\FIL\usdt, etc., the economic strength is strong, and F3 has been able to achieve a certain degree of profitability
```

What other projects/ecosystem stakeholders is this project associated with?
```
No stakeholders, F3 is independent
```

## Use-case details

Describe the data being stored onto Filecoin
```
The F3 platform update is very fast. The data stored in the Filecoin network includes F3 product iteration and official website update data, new NFT products, F3 brand promotion, etc.
```

Where was the data in this dataset sourced from?
```
From F3 platform update data, NFT transaction data, NFT promotion data, and even Twitter space data
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://drive.google.com/drive/folders/11vfIx6ze4awBQL0tbDTzj-XaBK2ihilP?usp=sharing
https://drive.google.com/drive/folders/1YtqSP1DvaM90A_TUWs0eAJcjpQClcnu-?usp=sharing
https://drive.google.com/drive/folders/1Q9Yb7PYdh9xyo4EK_o3QB1K1PcR0qJBa?usp=sharing 
```

Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Confirm.
```

What is the expected retrieval frequency for this data?
```
This is our backup data, expected to be retrieved every 12 months.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
about 12 -18 months
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
We hope that more miners will store our data, they may come from any corner of the world, I hope these data can be safely stored
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
We do not have a clear limit on this. We think that if it is small data, it will be transmitted online. If it is large data, consider offline hard disk transmission.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We will find storage providers through Slack, GitHub, etc. I hope these storage providers can cooperate with me when I need to retrieve
```

How will you be distributing deals across storage providers?
```
We will strictly abide by the rules of FIL+ to achieve decentralized storage.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, I do
```

**Comment by Sunnyiscoming** [comment]
> Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this.
> 
> https://drive.google.com/drive/folders/11vfIx6ze4awBQL0tbDTzj-XaBK2ihilP?usp=sharing
> https://drive.google.com/drive/folders/1YtqSP1DvaM90A_TUWs0eAJcjpQClcnu-?usp=sharing
> https://drive.google.com/drive/folders/1Q9Yb7PYdh9xyo4EK_o3QB1K1PcR0qJBa?usp=sharing

1. According to Twitter, you started your business earlier this year, and estimated domain age is 82 day(s). Generally, you don't have 5PB data generated from your business. 

2. Can you list storage providers you will cooperate with?
The community is very concerned about the distribution of datacap and whether storage providers support data retrieval.

**Comment by xxcisco** [comment]
Hello, it is a pleasure to see your reply.

F3 was founded in 2021, in December 2021, we registered the official website in f3dao.com, our registration record can be viewed https://ap.www.namecheap.com/domains/list/ here, and later, we upgraded the domain name of F3 from f3dao.com to https://f3.xyz/. Entering the URL f3dao.com browser will jump directly to the https://f3.xyz/. As a result, F3's domain name registration time is now about 220 days.
![image](https://user-images.githubusercontent.com/14759630/179906994-2a23de26-937b-4601-a0b1-462c74763ec5.png)
F3 is committed to becoming the largest NFT market for hashrate, at present, many NFT projects have inflated prices, but there is no actual value to rely on, we plan to use computing power to empower all NFT projects. Therefore, F3 will launch a lot of NFT projects and carry out in-depth cooperation, so we believe that as our business expands, the total amount of data we store will become larger and larger. Of course,  I evaluate our data volume again, we think that although we are developing rapidly, our data volume may not reach 5P in the short term, so we have voluntarily adjusted the data amount to 2P.
We plan to decentralize the storage of data, we hope sp can actively contact us, we think that at least 20 miner to store our data, but because the data has not been approved down, so we have not taken the initiative to find SP, we plan f0697249, f0162385, f01839495 These three miner will be able to carry part of our data, if you have recommended miner, welcome to inform us, thank you again.

**Comment by 1LISA2** [comment]
Hi, thanks again for your reply. In response to your question, we held a technical meeting yesterday. The data volume of F3 from its establishment in 2021 to the present is as follows:
F3 official website, corporate brochures, H5, posters, office decoration and other design materials 73T
F3 team (divided into distributed office and centralized office), the camera data record of centralized office is 1136T
F3 participated in major conferences and held data records of major events, 575T
Product model, product material 176T
NFT65T

**Comment by xxcisco** [comment]
Hi, thanks again for your reply. In response to your question, we held a technical meeting yesterday. The data volume of F3 from its establishment in 2021 to the present is as follows:
F3 official website, corporate brochures, H5, posters, office decoration and other design materials 73T
F3 team (divided into distributed office and centralized office), the camera data record of centralized office is 1136T
F3 participated in major conferences and held data records of major events, 575T
Product model, product material 176T
HD NFT65T

**Comment by Sunnyiscoming** [comment]
Can you list more data samples to show that you have the data as you mentioned above.

> Hi, thanks again for your reply. In response to your question, we held a technical meeting yesterday. The data volume of F3 from its establishment in 2021 to the present is as follows:
> F3 official website, corporate brochures, H5, posters, office decoration and other design materials 73T
> F3 team (divided into distributed office and centralized office), the camera data record of centralized office is 1136T
> F3 participated in major conferences and held data records of major events, 575T
> Product model, product material 176T
> HD NFT65T

**Comment by 1LISA2** [comment]
Hello, we will partially provide the design draft of our official website and the surveillance video of our company. It may take 1-2 days to prepare, please wait a moment.

**Comment by xxcisco** [comment]
Hello, we will partially provide the design draft of our official website and the surveillance video of our company. It may take 1-2 days to prepare, please wait a moment.

**Comment by xxcisco** [comment]
Hello, here is the official website of the latest version of our upcoming release, as well as other types of documents, please check, thank you for your reply      https://drive.google.com/drive/u/0/folders/1T5Q1cwwh_POrXvm3gkd-CSRCCUpaimeF

**Comment by Sunnyiscoming** [comment]
Since these two parts account for a large proportion of data, I look forward to receiving more data samples about these two parts

> F3 team (divided into distributed office and centralized office), the camera data record of centralized office is 1136T
> F3 participated in major conferences and held data records of major events, 575T

**Comment by xxcisco** [comment]
Ok, the data of the company's surveillance video needs to go through multi-level enterprise approval, we have already gone through the approval process. From approval to data download and presentation to you, it will take a certain amount of time, please wait another 1-2 days. ,Thank you

**Comment by xxcisco** [comment]
Honey , please check。https://drive.google.com/drive/u/0/folders/1T5Q1cwwh_POrXvm3gkd-CSRCCUpaimeF

**Comment by Sunnyiscoming** [comment]
Could you send an email to filplus-app-review@fil.org with your official domain in order to confirm your identity?
Email name should includes the issue id #497.

**Comment by xxcisco** [comment]
I have send the email to filplus-app-review@fil.org，please check it !

<img width="561" alt="1" src="https://user-images.githubusercontent.com/14759630/185279195-6e78c2e0-67fc-4053-9959-f26d18b98be5.png">

**Comment by xxcisco** [comment]
@Sunnyiscoming @Kevin-FF-USA @galen-mcandrew  We want to demo our F3 for you, can we join the next session, we hope to have 3-5 minutes to explain F3

**Comment by raghavrmadya** [comment]
<img width="682" alt="Screen Shot 2022-08-19 at 2 03 16 PM" src="https://user-images.githubusercontent.com/91579519/185706948-91d31dde-3da6-4d2f-8a0c-2cdbb98d2656.png">

**Comment by xxcisco** [comment]
Recently, F3 has undergone a brand upgrade, from F3 to F3HASH, and F3's Twitter has also changed from F3 to F3HASH. Therefore, the Twitter URL is https://twitter.com/f3_f3hash, and the others have not changed.
Our Twitter has more than 20,000 followers. Our Chief Strategy Officer, Huang Hao, participated in the "web3.0 China Summit" and was forwarded and liked by Filecoin's official Twitter.
Our brand upgrade will launch new products, and at the same time, it will also generate more data. We hope to store data on the Filecoin network. Please pass our application this morning.
We hope to participate in the notary meeting and demonstrate F3 for everyone. We can also provide any information, including business license, etc. and send it to your mailbox.
![1](https://user-images.githubusercontent.com/14759630/185821635-313fe31e-ba4a-48c4-963c-2341689cf7dd.jpg)

**Comment by raghavrmadya** [comment]
Thanks. Please come to the next governance call to present. We would like to know what is your relationship with the platform as well as more insight into the 5 PiBs request. You can add your request here - https://github.com/filecoin-project/notary-governance/issues/596

**Comment by xxcisco** [comment]
Hello, our business license has been sent to filplus-app-review@fil.org, please review, thank you.

**Comment by xxcisco** [comment]
ok , thank you ，we will be there on time， thank you again

**Comment by kernelogic** [comment]
I'd like to express my support to this application as a NA notary. This looks like a fine utility and we have allocated DC to utility-based projects before, such as Filswan, Estuary, FileDrive etc.

**Comment by raghavrmadya** [comment]
You mentioned 2 days ago that you recently went through a brand upgrade but the twitter was created in Dec 2021, even before the company registration. <img width="376" alt="Screen Shot 2022-08-23 at 11 11 33 AM" src="https://user-images.githubusercontent.com/91579519/186233099-ded2639e-68c4-4290-be68-755ef6882eaf.png">

**Comment by raghavrmadya** [comment]
There are too many red flags here.

**Comment by xxcisco** [comment]
In order to answer your problem more precisely, we have add a cloud document in https://drive.google.com/file/d/1mM9W8LRgTgIFvCaxJ_l9p9VOuH12OHcx/view?usp=sharing.
Thanks for your patient reading.

**Comment by raghavrmadya** [comment]
please add samples of this public client data, nft data, and social data as displayed in the screenshots.

**Comment by raghavrmadya** [comment]
The only sample is surveillance data

**Comment by xxcisco** [comment]
Please review the submitted data.
First, regardless of the later development, Now, we have 1-2P data, and this data can be backed up three times, which can meet our 5P quota.
Second, if you really think we don't have more data, please give us the 2P quota, because 700T of data can be backed up 3 times to meet the 2P quota. 
Third, we have seen that many filecoin ecological projects, such as filswan, nftstorage, filscan, etc., have successfully obtained their quotas. Our F3 is also a filecoin ecological project. We believe that you should treat them equally.
When we encapsulate data, you can pay close attention to the content of our data encapsulation. We promise that what we store on the filecoin network is absolutely the real F3 data.

https://drive.google.com/drive/u/0/folders/14atygDT32Vmudj3rrdDgFY5ElxB6OPli
https://drive.google.com/drive/folders/1jKRErXhsMZSISrPRG7jEeNbbtsJVCePU
https://drive.google.com/drive/folders/1kYxsfLM9pMsl-BmNAzxSZJ2KjvC3ytQi
https://drive.google.com/drive/folders/1Ci6l0myMKEFFcnevXj66DTKhNkJayb7J

**Comment by raghavrmadya** [comment]
If you want a different quota, please update the application.

**Comment by raghavrmadya** [comment]
<img width="660" alt="Screen Shot 2022-09-02 at 2 05 03 PM" src="https://user-images.githubusercontent.com/91579519/188235158-aa6ff736-9c4e-4fc3-845b-6548d60915e0.png">

**Comment by raghavrmadya** [comment]
Can you help me understand why there are zero items in the market

**Comment by xxcisco** [comment]
Hello, our product has been launched, please click the link to view https://f3hash.com/mining

**Comment by raghavrmadya** [comment]
Hi, it's very hard to track your relaunches. Please open a new application with the most up-to-date information and amounts needed. Please mention this application when you open a new one.

**Comment by xxcisco** [comment]
@raghavrmadya We have filled in application 925 again, please approve as soon as possible.
