### ISSUE TITLE
[DataCap Allocation] - dafs

### ISSUE THREAD

**Issue by 542949787** [filecoin-project/filecoin-plus-large-datasets#498]
---
name: Large Dataset Notary application
about: Clients should use this application form to request a DataCap allocation via a LDN for a dataset
title: "dafs"
labels: 'application, Phase: Diligence'
assignees: ''

---
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: asdfdsfa
- Website / Social Media: mv.net
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 2PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 20TiB
- On-chain address for first allocation: f1adf9sadf093fasdf00
- Region: North America

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
dasf asdfsa fdas f
```

What is the primary source of funding for this project?
```
as dfasd fasd fa
```

What other projects/ecosystem stakeholders is this project associated with?
```
asdf safas fsdaf
```

## Use-case details

Describe the data being stored onto Filecoin
```
Please answer here.
```

Where was the data in this dataset sourced from?
```
Please answer here.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
Please answer here.
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Please answer here.
```

What is the expected retrieval frequency for this data?
```
Please answer here.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
Please answer here.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Please answer here.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Please answer here.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
Please answer here.
```

How will you be distributing deals across storage providers?
```
Please answer here.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Please answer here.
```

**Comment by dkkapur** [comment]
Closing this one out. Looks like it might have been opened as a test?

**Comment by 542949787** [comment]
Hi Deep,

Hope this message finds you well. It was nice to see you back in SXSW.  You are correct. It was for a testing. Sorry for the inconvenience. I have used my company email to start another one named Eugene Group 16 days ago but the status is still application. Lots of other applications after us are in verifying stage. Do you know the reason for it? And are there anyways that we can expedite the process?

I have a company that stores lots of data for e-commerce companies (around 8). The Eigen group company is our first application. After this passes, we will be submitting our other applications. Thank you for your help. Hope everything goes well.


Best,

Peter

On Aug 3, 2022, at 20:24, Deep Kapur ***@***.***> wrote:

﻿

Closing this one out. Looks like it might have been opened as a test?

**Comment by Sunnyiscoming** [comment]
There is no result through searching.
![image](https://user-images.githubusercontent.com/105098820/182995743-a63b421c-ee3a-4514-abec-5db4ad112b31.png)
We will check one after one. If it is submitted after 500, please wait for updating. Thanks.

**Comment by 542949787** [comment]
Sorry for the typo. The keyboard auto corrected it Eugene. The application is called “Eigen Group”.

Sorry for any inconvenience.


On Aug 4, 2022, at 20:32, Sunnyiscoming ***@***.***> wrote:

﻿

There is no result through searching.
[image]<https://user-images.githubusercontent.com/105098820/182995743-a63b421c-ee3a-4514-abec-5db4ad112b31.png>
We will check one after one. If it is submitted after 500, please wait for updating. Thanks.
