### ISSUE TITLE
[DataCap Allocation] - Github的名字

### ISSUE THREAD

**Issue by 542949787** [filecoin-project/filecoin-plus-large-datasets#499]
---
name: Large Dataset Notary application
about: Clients should use this application form to request a DataCap allocation via a LDN for a dataset
title: "Github的名字"
labels: 'application, Phase: Diligence'
assignees: ''

---
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: 公司名称
- Website / Social Media: 网页地址
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 2PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100TiB
- On-chain address for first allocation: f1adf9sadf093fasdf00
- Region: North America

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
请分享一个公司和公司项目的简单介绍/历史
```

What is the primary source of funding for this project?
```
这个公司的资金来源主要来自于什么地方
```

What other projects/ecosystem stakeholders is this project associated with?
```
这个公司的股东参与了哪一些项目/生态？
```

## Use-case details

Describe the data being stored onto Filecoin
```
描述一下将要存储在FIL的数据（类型，内容等等）
```

Where was the data in this dataset sourced from?
```
这个数据库里面的数据来源来自于什么地方？
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
你能分享一个数据的例子吗？例如一个文件，一张图片，一张表格等等。
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
确认这是一个公共数据库并且可以被所有人检索。（例如：并不需要特殊批准来查看数据）
```

What is the expected retrieval frequency for this data?
```
这些数据的检索频率在多少？我们多久需要提取一次数据。
```

For how long do you plan to keep this dataset stored on Filecoin?
```
这些数据准备在FIL上面存储多长时间？ （建议按年来计算，例如3-5年）
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Please answer here.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Please answer here.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
Please answer here.
```

How will you be distributing deals across storage providers?
```
Please answer here.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Please answer here.
```

**Comment by dkkapur** [comment]
@542949787 this application seems to be missing a ton of information. Our validation also currently only works in English AFAIK which is why maybe this did not get picked up by the bots. Are you able to fill out the whole application?

**Comment by Sunnyiscoming** [comment]
Maybe it can be closed and create a new application. The contents in Chinese are just translation of questions.

**Comment by 542949787** [comment]
The entire application was carefully filled out with all questions answered in English. Maybe it’s because something was wrong with my end?

This is the URL: https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/503

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Sunnyiscoming** [comment]
Ok. You can close this one.

**Comment by 542949787** [comment]
Ok. I ll close this one and re-fill in a new one. Do you know if there is anything I need to be aware of so that I can prevent any potential mistakes for verification process? Because this application was fully answered and it was in English. Thanks for the help.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
