### ISSUE TITLE
[DataCap Application] < Bitwind > - < Crypto Exchange >

### ISSUE THREAD

**Issue by bitwindinfo** [filecoin-project/filecoin-plus-large-datasets#500]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: bitwind
- Website / Social Media: www.bitwind.com
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 3PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100TiB
- On-chain address for first allocation: f1gyu2r6w735najxova3npcxqjmsql7burrivvxdq

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Bitwind ---- A World's Leading Liquidity Solution Provider
Bitwind is committed to providing premium liquidity services to small amd medium-sized digital currency exchanges,
institutional investors, brokers and other financial institutions, aiming to help exchanges reduce costs and increase efficiency.
```

What is the primary source of funding for this project?
```
Corporate Strategy Fund.
```

What other projects/ecosystem stakeholders is this project associated with?
```
For exchanges and individuals who need liquidity
```

## Use-case details

Describe the data being stored onto Filecoin
```
all Transaction records / Log files / record of service and Data file 
```

Where was the data in this dataset sourced from?
```
bitwind platform
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
Here are samples of the data we intend to store:
https://drive.google.com/file/d/1_IW5AMCHS2OSurnKYmTVKBDqVQ6Yp5a0/view?usp=sharing
https://drive.google.com/file/d/1-VmpacIkL-oiYD3UG4QMfMQzFUrdjShc/view?usp=sharing
https://drive.google.com/file/d/1fxJQ4V8bWT2t4Q3XosAjiyqBWQ9dgM-T/view?usp=sharing
https://drive.google.com/file/d/15c1KLsHbZr796BaNAO2Zn1rMwM28lXf7/view?usp=sharing
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes
```

What is the expected retrieval frequency for this data?
```
1-2 times a year
```

For how long do you plan to keep this dataset stored on Filecoin?
```
540 days or more
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Asia
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
We plan to use offline services .
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We will look for storage providers on Slack, but before that we will fully consider how long they have been worked in the Filecoin network to ensure that they will help us store data safely and steadily.
```

How will you be distributing deals across storage providers?
```
Allocation is based on the storage capacity of the storage providers.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, We hope to be approved as soon as possible.
```

**Comment by Sunnyiscoming** [comment]
There is some doubt about the total amount of data. Can you explain the data composition?

**Comment by Sunnyiscoming** [comment]
Can you explain the relationship between bitwind and chainup?
When Bitwind began its business and can you show the organization which operate it?

**Comment by Margole** [comment]
Thanks to the recovery, we have a large part of private data, so we decided to stop using filecoin+

**Comment by bitwindinfo** [comment]
We have the transaction information of all currencies, but after re examination, we found that there is a large amount of private data, and it is not suitable to use the filecoin plus network for disclosure. We decided to stop this way. Thanks
