### ISSUE TITLE
[DataCap Allocation] - everything on the computer

### ISSUE THREAD

**Issue by domms9911** [filecoin-project/filecoin-plus-large-datasets#501]
---
name: Large Dataset Notary application
about: Clients should use this application form to request a DataCap allocation via a LDN for a dataset
title: "everything on the computer"
labels: 'application, Phase: Diligence'
assignees: ''

---
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: kims-korea
- Website / Social Media: www.kims-korea.co.kr
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 500TiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 50TiB
- On-chain address for first allocation: f1isu6pa3pvbymukbloyger5lcy5gcifugiw5abzq
- Region: Asia (excl. Greater China)

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```

Established in 2001, we provide a wide range of computer services. The detailed items are CCTV (agricultural, mountain, road) and computer repair.
```

What is the primary source of funding for this project?
```

It is a company.
```

What other projects/ecosystem stakeholders is this project associated with?
```
It is video and audio storage in public places, and observation and storage of various vegetables such as strawberries, watermelons, tomatoes, and wild animals. Computer-related educational videos can be viewed by anyone and there is no license.
```

## Use-case details

Describe the data being stored onto Filecoin
```
It is video and audio storage in public places, and observation and storage of various vegetables such as strawberries, watermelons, tomatoes, and wild animals. Computer-related educational videos can be viewed by anyone and there is no license.
```

Where was the data in this dataset sourced from?
```
company.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
http://www.kims-korea.co.kr/img/kims_20220719_01.jpg
http://www.kims-korea.co.kr/img/kims_20220719_02.jpg
http://www.kims-korea.co.kr/img/kims_20220719_03.jpg
http://www.kims-korea.co.kr/img2/contents_04.jpg
http://www.kims-korea.co.kr/img/kims_20220719_04.jpg
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
No license.
everyone.
```

What is the expected retrieval frequency for this data?
```
3 years.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
3 years.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Asia excl. Greater China
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
as many companies as possible.
More than 3 to 5 companies.
Offline transmission is possible.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
It is very difficult to find a reliable storage provider. We will research several companies and select them carefully. Online delivery will be random, and we will select a company that is more than a year old.
```

How will you be distributing deals across storage providers?
```
2 offline companies, 3 to 5 online companies.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```

The funds are sufficient.
```

**Comment by hyunsoo12** [comment]
How long do I have to wait to receive a reply?

**Comment by domms9911** [comment]
How long do I have to wait to receive a reply?

**Comment by Sunnyiscoming** [comment]
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/401
@domms9911 
https://github.com/filecoin-project/filecoin-plus-client-onboarding/issues/1099
https://github.com/filecoin-project/filecoin-plus-client-onboarding/issues/1170
https://github.com/filecoin-project/filecoin-plus-client-onboarding/issues/1323
https://filplus.d.interplanetary.one/clients/f01452694/breakdown

All the datacap you applied for are stored on one storage node. Large datasets require distributed storage nodes which support data retrieval. Have you found some cooperative storage nodes? Can you list them?

**Comment by domms9911** [comment]
@Sunnyiscoming 
It's a different company than us.
This is not what we posted.
