### ISSUE TITLE
[DataCap Application] Raysun

### ISSUE THREAD

**Issue by Raysunradar** [filecoin-project/filecoin-plus-large-datasets#507]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Raysun Radar Electronic Technology Co.,Ltd
- Website / Social Media:http://www.raysunradar.com
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):200TiB
- On-chain address for first allocation:f1jdmx2cuswzjlt4pnsv3t7ipmesywzxsg6q56a2a

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Raysun is committed to developing the world's leading radar technology and roadside sensing solutions for Telematics, providing efficient and reliable holographic sensing data for intelligent transportation systems and driverless solutions. The team has been engaged in radar research dating back to 1945 and has nearly 20 years of experience in radar industrialization. Using advanced technology accumulation, years of radar R&D experience and strong industry support, the company has developed low-cost, highly intelligent and stable millimeter wave radar and radar vision fusion sensors to provide users with more efficient and reliable roadside sensing solutions.
```

What is the primary source of funding for this project?
```
From finance investment.
```

What other projects/ecosystem stakeholders is this project associated with?
```
We only attend Filecoin project---LDN.
```

## Use-case details

Describe the data being stored onto Filecoin
```
Videos----mp4 about road monitoring.
```

Where was the data in this dataset sourced from?
```
Data is from our products which provide service about monitoring.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
There are two videos as samples.
[sample for Raysun.zip](https://github.com/filecoin-project/filecoin-plus-large-datasets/files/9139285/sample.for.Raysun.zip)
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
We confirm these data is authorized as copies to store in Filecoin.
```

What is the expected retrieval frequency for this data?
```
Ideal frequency is every two years. We just need to make it safely.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
2 years --- the first step.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Asia is ok.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Yes. Offline transfer is proper for us to transfer data, by express.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
Github is a good platfom to find SP. They should have enough source to recieve our deals----their capacity, funds.
```

How will you be distributing deals across storage providers?
```
To every sp, we will send less than 25% deals.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes.
```

**Comment by Raysunradar** [comment]
![492f-b10a-0aff424aee07](https://user-images.githubusercontent.com/107109026/180137703-03a5ccff-5558-4ab4-9c31-71550e5d1e1b.jpg)
I sent the email to [filplus@fil.org](mailto:filplus@fil.org) @galen-mcandrew

**Comment by Sunnyiscoming** [comment]
> Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
> 
> We confirm these data is authorized as copies to store in Filecoin.

Whether this dataset is public?

**Comment by Raysunradar** [comment]
@Sunnyiscoming Hi Sunny, I confirm that these data is public and authorized. It is all from our products.

**Comment by Sunnyiscoming** [comment]
Can you provide more detailed information about storage providers distribution, such as you can list SPs you have contacted with at present?

**Comment by Raysunradar** [comment]
@Sunnyiscoming It's a late reply! Now we've prepared some node for our future deals. They are f0129750/f087868/f0131509/f0122940 We will distribute data to SPs in Asia, such as Korea, China.

**Comment by Sunnyiscoming** [comment]
It seems that these nodes is unreachable. Why you choose them?
https://filrep.io/?search=f0129750
https://filrep.io/?search=f087868
https://filrep.io/?search=f0131509
https://filrep.io/?search=f0122940

**Comment by Sunnyiscoming** [comment]
Could you send an email to [filplus-app-review@fil.org](mailto:filplus-app-review@fil.org) with your official domain in order to confirm your identity?
Email name should includes the issue id https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/507.

**Comment by Raysunradar** [comment]
@Sunnyiscoming I contacted these SPs through friends and SPs promised to support data retrieval when they started sealing the data.

**Comment by raghavrmadya** [comment]
<img width="1336" alt="Screen Shot 2022-08-25 at 7 05 35 PM" src="https://user-images.githubusercontent.com/91579519/186801016-d7c94623-8bbb-4aea-ba7b-507024813774.png">

The application is asking for higher weekly allocation without justification. Please open a new application with as much justification as possible including at least 10 data samples of the actual storage. We cannot determine the legitimacy of this client and application.

**Comment by Raysunradar** [comment]
@raghavrmadya I'm confused about what you're referring to. Can you help me with the answer?
When I applied my issue, I didn't see any community rule that said application which is asking for higher weekly allocation would be closed. Also I have already provided the content you need. I don't think it's reasonable to directly close my issue. I can cooperate with your request to make corrections and provide relevant information and I think my issue should be restarted. Looking forward to your response.

**Comment by raghavrmadya** [comment]
@Raysunradar , definitely. Your issue has been open for about 2 months now and we don't have enough details about why exactly do you need 5 PiBs and 200 TiBs weekly. The data samples provided are not sufficient. Instead of going back and forth which consumes too much of both of time, it is best to open a new issue if you still wish to pursue providing as much evidence for your application. Things are evolving and past applications might not always be a good example of what is acceptable and right.
