### ISSUE TITLE
[DataCap Application]Shenzhen Qiyihuo Technology Co., Ltd.

### ISSUE THREAD

**Issue by 49887134** [filecoin-project/filecoin-plus-large-datasets#510]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Shenzhen Qiyihuo Technology Co., Ltd.
- Website / Social Media:https://crypts.cn/   https://rarefy.cn/?bd_pc&cp&szhb&bd_vid=8878743332966028090 
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):3.5 PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):200TiB
- On-chain address for first allocation:f1ppkvhfhixohe7slolot3r4zn6yza7x45kuzs5pi

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Shenzhen Qilihuo Technology Co., Ltd. was established in November 2020, and its team members are composed of top talents in the industry such as blockchain technology geeks, legal compliance experts, and cutting-edge operation gods, and are committed to making everyone and enterprise have their own NFT and meta-universe.

Qilihuo Technology, which has blockchain information service filing, ICP value-added telecommunications services, network culture business licenses, art business service filings, auction operation approval certificates, etc., is the first blockchain technology company in China to deploy the NFT technology protocol on the mainstream alliance chain, and has created the first platform for NFT casting, programming and virtual space applications, and is also the first blockchain technology company in China to file with the Ministry of Network Information technology and pass the NFT protocol.  

Qilihuo Technology has served more than a thousand enterprises, organizations and individual artists, creating a diversified ecosystem of NFT content + application + tools for users, and becoming the lowest technical service platform of the NFT meta-universe with the widest service scope and the most complete functions in China.

Qilihuo Technology has XIWU, Rarefy, Rarefy provide a full range of NFT marketing tools and application scenarios, to help enterprises grow, to help enterprises quickly build an exclusive NFT digital collection platform, the platform currently has a display version, a release version and a meta-universe version of the three major versions, has settled 99 creators, and released millions of NFTs.

"XIWU" is positioned as the world's leading new generation of native digital IP sales platform, has more than 100+ content producers, shelves many rare versions of NFTs, has more than 3W+ NFT users, and has a very high popularity in China.
```

What is the primary source of funding for this project?
```
Our company has its own funds and is already profitable.
```

What other projects/ecosystem stakeholders is this project associated with?
```
No one.
```

## Use-case details

Describe the data being stored onto Filecoin
```
NFT casting and display, sale data, Rarefy SAAS development data, product update data, etc.
```

Where was the data in this dataset sourced from?
```
Generated from the casting and trading of NFTs, from our APP development, from the events we host
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
We can provide you with some data samples. However, many NFTs are cast and put on the shelves every day, and our apps are constantly updated. Therefore, data samples are only a part of our content.
https://drive.google.com/drive/folders/1cB5EfyQz7WcyOnuqXz9LhrMQ3Ne7mBAI
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Confirm
```

What is the expected retrieval frequency for this data?
```
Probably 2-3 times a year
```

For how long do you plan to keep this dataset stored on Filecoin?
```
We want to be able to achieve long-term storage, because the NFT data is stored in the Filecoin network we are more assured, therefore, we want to be 2 years or more
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
All regions, no restrictions
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
A NFT data is not large, so we tend to transmit it online.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We choose a proactive and stable storage provider, and we want to make sure that their storage is long-term, and only then can we keep our data stored securely.
```

How will you be distributing deals across storage providers?
```
We will abide by the rules of Fil+, and we will achieve distribution as decentralized as possible.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, I'm ready. 
```

**Comment by Sunnyiscoming** [comment]
Shenzhen Qilihuo Technology Co., Ltd.
Is your organization name 深圳市奇异火科技有限公司?
Are you the employee of this organization?

**Comment by 49887134** [comment]
Yes, I am an employee of this company, I am from  深圳市奇异火科技有限公司 。Our official website is https://crypts.cn/ ， We are positioned as the world's leading new generation of native digital IP distribution platform, dedicated to providing users with a new, cool and unique digital content novel experience. At the same time, we have over 60+ NFT platforms or companies who use our SaaS whose website is https://rarefy.cn/, which enable us to have lots of users' data.

**Comment by Sunnyiscoming** [comment]
Is this user data publicly available? Do you have the user's authorization to use the data?

**Comment by 49887134** [comment]
Yes, most of our data, such as NFTs, are publicly available data, which can be viewed on our official website or even on trading platforms such as opensea. At the same time, we also provide SAAS services for enterprises, and the SAAS data of enterprises is not convenient to disclose. , Therefore, we mainly store NFT data on the Filecoin network. Our enterprise valuation is nearly 1 billion, and many famous investment institutions have invested in us. We are booming and the data we generate every day is very large .

**Comment by raghavrmadya** [comment]
Please send an email stating you have applied for LDN using an official email plus a business license to filplus-app-review@fil.org. Also shed light on the relationship of the applicant with the company.

Thanks.

**Comment by 49887134** [comment]
Hello, the mail is sent, and the business license is attached, please check.

**Comment by Sunnyiscoming** [comment]
https://micp.chinaz.com/?query=crypts.cn
Received that. Thanks for your sending.

> I am sending an email to prove that I am an employee of Qilihuo
It seems that you mistake your organization name.

**Comment by 49887134** [comment]
Hello, this is a misspelling of the company name caused by my typing too fast, but our domain name mail comes with a business license, which fully shows that  Qiyihuo is applying for FIL+.

**Comment by 49887134** [comment]
I have corrected the wrong spelling, thanks.

**Comment by Sunnyiscoming** [comment]
Before proceeding, what is the amount of data you have today and how many copies do you plan to store? Please also share more insight into SP distribution and SP IDs if possible.

**Comment by 49887134** [comment]
Hello, we were established in 2020. In the past two years, we have achieved rapid growth. We have obtained linear capital with Meta, Sequoia Capital, Hillhouse Capital as LP, and the equity of A-share listed company Aoya Design. invest. Our actual users and secondary transaction volume are one of the largest in China, and more than 60 Chinese NFT platforms are using our SAAS system. In addition, our platform is the most active, with more than 1 million registered user.

As you see, our NFT trading market is huge, our users are very active, we are generating petabytes of data every year, and our data is at least 3P. We applied for 3.5P, and our goal is to take out 1.167P of data to make 3 backups and store them on the Filecoin network.

We contacted the nodes f023971, f0406322, f010617, f0401300, f0447183, f01909497.

Sincerely, we hope that you can give us credit as soon as possible, thank you.

**Comment by raghavrmadya** [comment]
Provide samples for "NFT casting and display, sale data, Rarefy SAAS development data, product update data, etc." Your samples currently contains NFTs and not what you mentioned

**Comment by 49887134** [comment]
Hello, according to your request, we have provided more data, please check it out. Sincerely, I hope you can give us a quota as soon as possible.

https://drive.google.com/drive/folders/10AhZuWTN-UzTQ19fGefvSF7025aRRWTc
https://drive.google.com/drive/folders/1CvzPbX_sBxMoR8ftqpq0t_hX-j-U2Cse
https://drive.google.com/drive/folders/17WJxUWA4LpI3UngN7zUZ46fJutL-_HZt
https://drive.google.com/drive/folders/1mbAg0nbyRmZqrJxRSsgtZ42QK1lA_gsb
https://drive.google.com/drive/folders/1sqATkFNXhipPUwBa9Vdk3JCWxEzyBMH9
https://drive.google.com/drive/folders/1SaAQAF8eVg_QB8bFFfNRc7mOV8nUKlEf

**Comment by Sunnyiscoming** [comment]
![image](https://user-images.githubusercontent.com/105098820/188807844-19202f3f-aecc-4b26-8a3c-5506fed39f78.png)
Please open the access.

**Comment by 49887134** [comment]
The access has been opened, please check.

**Comment by leon-le** [comment]
The access has been opened, please check.

**Comment by raghavrmadya** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 3.5PiB

**Expected weekly DataCap usage rate**

> 200TiB

**Client address**

>f1ppkvhfhixohe7slolot3r4zn6yza7x45kuzs5pi

**Comment by raghavrmadya** [comment]
Please be open to further due diligence from notaries.

**Comment by 49887134** [comment]
OK

**Comment by stcouldlisa** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceayjylvnybkhxwbyi37ug7oc7xrcqimpyyrszuw7lrhqaxobt6ke6 
#### Address 
> f1ppkvhfhixohe7slolot3r4zn6yza7x45kuzs5pi
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1jvvltduw35u6inn5tr4nfualyd42bh3vjtylgci
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceayjylvnybkhxwbyi37ug7oc7xrcqimpyyrszuw7lrhqaxobt6ke6

**Comment by Defil2022** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebceccvermfngscytqwoqbuqlvynyu64od2ks2xqebs66jhvsaas2 
#### Address 
> f1ppkvhfhixohe7slolot3r4zn6yza7x45kuzs5pi
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1dnb3uz7sylxk6emti3ififcvu3nlufnnsjui6ea
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebceccvermfngscytqwoqbuqlvynyu64od2ks2xqebs66jhvsaas2

**Comment by BigD-Exchange** [comment]
@49887134 Hi! Great to see you have gotten approval for DataCap. If you are looking for more storage providers to store these data or have any questions, please visit #bigdata-exchange on Filecoin Slack or reply here. 

We have strong demand from a diverse group of SPs, who are actively looking to onboard more data.

**Comment by Joss-Hua** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced6tith62e63iqyvxt67koxcbazft6duexdpfatu6pzofhsgmd4xo 
#### Address 
> f1ppkvhfhixohe7slolot3r4zn6yza7x45kuzs5pi
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1tfg54zzscugttejv336vivknmsnzzmyudp3t7wi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced6tith62e63iqyvxt67koxcbazft6duexdpfatu6pzofhsgmd4xo

**Comment by newwebgroup** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedznag7tzqyutspucv32vgm2qgt3l2wlvr3soqvd3b54avkjnfuke 
#### Address 
> f1ppkvhfhixohe7slolot3r4zn6yza7x45kuzs5pi
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1e77zuityhvvw6u2t6tb5qlnsegy2s67qs4lbbbq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedznag7tzqyutspucv32vgm2qgt3l2wlvr3soqvd3b54avkjnfuke

**Comment by swatchliu** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecnj2peis6dareklojqbm3ppfczyofpxzsg22tmlk4hnxnlbqevxm 
#### Address 
> f1ppkvhfhixohe7slolot3r4zn6yza7x45kuzs5pi
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1yh6q3nmsg7i2sys7f7dexcuajgoweudcqj2chfi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecnj2peis6dareklojqbm3ppfczyofpxzsg22tmlk4hnxnlbqevxm

**Comment by Stoibers** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedods3p7fkelbq75unpt6336rypd6pv7japlzsczzd6rkqfzboxxo 
#### Address 
> f1ppkvhfhixohe7slolot3r4zn6yza7x45kuzs5pi
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1yayfsv6whu3rheviucvventj3y6t542xfpb47ei
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedods3p7fkelbq75unpt6336rypd6pv7japlzsczzd6rkqfzboxxo

**Comment by 1ane-1** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceafk2fcgkryvsc4ejxof626rxne57twnhldh42mwvysbtue2rez32 
#### Address 
> f1ppkvhfhixohe7slolot3r4zn6yza7x45kuzs5pi
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1mdk7s2vntzm6hu35yuo6vjubtrpfnb2awhgvrri
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceafk2fcgkryvsc4ejxof626rxne57twnhldh42mwvysbtue2rez32

**Comment by kernelogic** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebdrklcr5rsbukdkua7sl6o4aig7qsnvfdeg4qkhhvi56dsxe5bgy 
#### Address 
> f1ppkvhfhixohe7slolot3r4zn6yza7x45kuzs5pi
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebdrklcr5rsbukdkua7sl6o4aig7qsnvfdeg4qkhhvi56dsxe5bgy

**Comment by psh0691** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebp4eby3yb3e4w6tpce65ebuqloj7win2dn2xf4eamv533jnvtk42 
#### Address 
> f1ppkvhfhixohe7slolot3r4zn6yza7x45kuzs5pi
#### Datacap Allocated
> 1.56PiB
#### Signer Address
> f1qdko4jg25vo35qmyvcrw4ak4fmuu3f5rif2kc7i
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebp4eby3yb3e4w6tpce65ebuqloj7win2dn2xf4eamv533jnvtk42

**Comment by newwebgroup** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaajxzpyabdupjvanodu7ocwbdrpwe5bbrd5ebp3yjd5fvyqbfiva 
#### Address 
> f1ppkvhfhixohe7slolot3r4zn6yza7x45kuzs5pi
#### Datacap Allocated
> 1.56PiB
#### Signer Address
> f1e77zuityhvvw6u2t6tb5qlnsegy2s67qs4lbbbq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaajxzpyabdupjvanodu7ocwbdrpwe5bbrd5ebp3yjd5fvyqbfiva

**Comment by newwebgroup** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecmnsakrr2xxpuint7xbg7onsdw3lml7uamd2zmsegasx34qpl6nw 
#### Address 
> f1ppkvhfhixohe7slolot3r4zn6yza7x45kuzs5pi
#### Datacap Allocated
> 486.55TiB
#### Signer Address
> f1e77zuityhvvw6u2t6tb5qlnsegy2s67qs4lbbbq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecmnsakrr2xxpuint7xbg7onsdw3lml7uamd2zmsegasx34qpl6nw

**Comment by newwebgroup** [comment]
**Special reminder**
Because the available balance of Datacap in the previous round was insufficient, the DC quota signed and approved was not received.
So it was re signed

**Comment by stcouldlisa** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedc4hgv4vykz5lmpd5cbacittlkyqvmyl72mxzgzdnwrl5krac6ja 
#### Address 
> f1ppkvhfhixohe7slolot3r4zn6yza7x45kuzs5pi
#### Datacap Allocated
> 486.55TiB
#### Signer Address
> f1jvvltduw35u6inn5tr4nfualyd42bh3vjtylgci
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedc4hgv4vykz5lmpd5cbacittlkyqvmyl72mxzgzdnwrl5krac6ja

**Comment by fabriziogianni7** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebp4eby3yb3e4w6tpce65ebuqloj7win2dn2xf4eamv533jnvtk42 
#### Address 
> f1ppkvhfhixohe7slolot3r4zn6yza7x45kuzs5pi
#### Datacap Allocated
> 1.56PiB
#### Signer Address
> f1qdko4jg25vo35qmyvcrw4ak4fmuu3f5rif2kc7i
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebp4eby3yb3e4w6tpce65ebuqloj7win2dn2xf4eamv533jnvtk42

**Comment by fabriziogianni7** [comment]
Retriggering this proposal since it was not allocated.
@simonkim0515

**Comment by fabriziogianni7** [comment]
## DataCap Allocation requested

### Request number 5
#### Multisig Notary address
> f01858410

#### Client address
> f1ppkvhfhixohe7slolot3r4zn6yza7x45kuzs5pi

#### DataCap allocation requested
> 1.56PiB

**Comment by fabriziogianni7** [comment]
## DataCap Allocation requested

### Request number 5
#### Multisig Notary address
> f01858410

#### Client address
> f1ppkvhfhixohe7slolot3r4zn6yza7x45kuzs5pi

#### DataCap allocation requested
> 1.56PiB

**Comment by kernelogic** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecfdfb6q7iivv72vutz4k4iv4fm3z6gqgh3t4gbnxb4hziikfnsza 
#### Address 
> f1ppkvhfhixohe7slolot3r4zn6yza7x45kuzs5pi
#### Datacap Allocated
> 1.56PiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecfdfb6q7iivv72vutz4k4iv4fm3z6gqgh3t4gbnxb4hziikfnsza

**Comment by liyunzhi-666** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb4eyyrciadxzcgfeqijod3ql6tcztrztmjqdttkirefuhq5pkxqs 
#### Address 
> f1ppkvhfhixohe7slolot3r4zn6yza7x45kuzs5pi
#### Datacap Allocated
> 1.56PiB
#### Signer Address
> f1pszcrsciyixyuxxukkvtazcokexbn54amf7gvoq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb4eyyrciadxzcgfeqijod3ql6tcztrztmjqdttkirefuhq5pkxqs
