### ISSUE TITLE
[DataCap Application] Shenzhen kuaixue Education Development Co., Ltd 

### ISSUE THREAD

**Issue by Acc5com** [filecoin-project/filecoin-plus-large-datasets#512]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Shenzhen kuaixue Education Development Co., Ltd
- Website / Social Media:https://www.acc5.com/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5Pib
- Weekly allocation of DataCap requested (usually between 1-100TiB):200Tib
- On-chain address for first allocation: f16ioghg3qy36f6572viouwv4dqow5ejpolo4kodi

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Accounting school is an online training platform under Shenzhen kuaixue Education Software Technology Co., Ltd. Founded in 2014, it is committed to providing high-quality accounting practice, tax practice, CPA, intermediate accounting, primary accounting and other training for the majority of accounting practitioners. Since its establishment, kuaixue education has a team of excellent teachers with more than 500 people, and has developed practical courses covering 150 + industries and 10000 + class hours. It is a leading online accounting practical training institution in China. Located in Shenzhen Nanshan Science and Technology Park, it is a technology and product driven innovation education training institution with more than 3million online students.
```

What is the primary source of funding for this project?
```
From ourselves.
```

What other projects/ecosystem stakeholders is this project associated with?
```
Only related to ourselves.
```

## Use-case details

Describe the data being stored onto Filecoin
```
Part of the course video of our platform.
```

Where was the data in this dataset sourced from?
```
Courses data
Real account practice: real account practice in more than 150 industries such as industry, commerce and trade, hotel and catering, construction and real estate, software, finance, import and export, administrative units, public institutions, etc;
Introduction to zero Foundation: basic accounting, financial regulations, computerization, career planning, introduction to accounting, introduction to tax law, cashier, entry, voucher binding, office software
I want to learn cashier: introduction to theory and practical operation;
Manual true account: Bookkeeping vouchers, journals, sub ledgers, general ledger, account summary, and financial statements;
Tax practice: introduction to theory, replacing business tax with value-added tax, income tax, national tax and local tax declaration, tax accounting, tax planning, export tax rebate, Golden Tax phase III, invoice management, etc;
Financial management: financial analysis, financial management, bank loans, CFO;
Professional title examination: junior accountant, intermediate accountant, certified public accountant;
Financial software: Kingdee, UFIDA, Suda, Kuai Zhang, general ledger
Excel School: Excel foundation, function formula, pivot table, accounting application, financial modeling, practical operation explanation, VBA, chart, accounting E-form, etc;
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
Yes, we have a large number of open free training courses.
In the future, after filecoin plus enterprises can open applications, we will store more paid courses on filecoin.

https://www.acc5.com/course/course_13335/learn/lesson_74929/
https://www.acc5.com/course/course_13545/learn/lesson_77063/
https://www.acc5.com/course/course_12656/learn/lesson_66671/
https://www.acc5.com/course/course_11017/learn/lesson_43899/
https://www.acc5.com/practice/course/cat_0/list-0-3-1000-0/1.html
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes, there are no restrictions. Anyone who wants to learn accounting knowledge can search it.
```

What is the expected retrieval frequency for this data?
```
At present, it is only used as a backup until our private cloud data is lost.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
We hope it will last forever.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
we hope in China
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
These data are currently stored in our enterprise private cloud. Because the amount of data is very huge, we hope to transmit offline.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
Because we are not miners, we only know filecoin after being introduced by friends. When we learned about fil plus, we were very happy. We carefully read the storage rules of filecoin plus.
first ，We guarantee that the distribution of content will be as decentralized as possible. It will be stored in at least 8 storage service provider nodes.
The more decentralized the data storage is, the more secure it is for our data.
secondly,
We will ask the service provider that stores the data to provide the function of rapid retrieval, and will review the work after the storage is completed.
```

How will you be distributing deals across storage providers?
```
Choose Offline transmission as far as possible.
Our enterprise private cloud should support normal users. If it is used for online transmission, it will occupy too many resources.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, we have enough money. However, we still don't know how to cut the document into a unified format according to the regulations, and we will continue to learn.
```

**Comment by Acc5com** [comment]
Supplementary instructions
Our Chinese name is “ 深圳快学教育发展有限公司 ”
Unified social credit code “91440300311808605Q”

https://www.tianyancha.com/company/2322646414

**Comment by Sunnyiscoming** [comment]
@Acc5com Could you send an email to filplus@fil.org with your official domain in order to confirm your identity?
Email name should includes the issue id #512.

**Comment by raghavrmadya** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5 PiB

**Expected weekly DataCap usage rate**

> 200 TiB

**Client address**

> f16ioghg3qy36f6572viouwv4dqow5ejpolo4kodi

**Comment by raghavrmadya** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5 PiB

**Expected weekly DataCap usage rate**

> 200 TiB

**Client address**
f16ioghg3qy36f6572viouwv4dqow5ejpolo4kodi

**Comment by Acc5com** [comment]
Hello
@raghavrmadya @Sunnyiscoming 
Thank you for allowing us to store the course data on filecoin, which is a very meaningful thing for us.
We have sent a verification email to“ filplus@fil.org  ”“ filplus-app-review@fil.org ”

<img width="560" alt="image" src="https://user-images.githubusercontent.com/109668956/183848901-38fae3a1-010a-45f5-8bb4-807b39877f12.png">

**Comment by 1LISA2** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceafieu73hyvbrdm7yci4veqczfohtnamcxzb57eq2a4ndyw5sq346 
#### Address 
> f16ioghg3qy36f6572viouwv4dqow5ejpolo4kodi
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1jvvltduw35u6inn5tr4nfualyd42bh3vjtylgci
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceafieu73hyvbrdm7yci4veqczfohtnamcxzb57eq2a4ndyw5sq346

**Comment by Acc5com** [comment]
Our existing “course data set” has a capacity of **800TiB**. We plan to make five backups in China.
Because our files are stored in the enterprise private cloud and the external transmission line is only 100MB / s, we only support offline transmission and mailing.
The preferred SP location is within China. If it is an SP outside China, you need to solve the transmission problem yourself
(If the SP is outside China, due to COVID-19 epidemic and customs rules in China, it is only possible to ship the hard disk from China and the hard drive procurement & shipping cost need to be borne by the SP.)

For the first **5 SPS**, we plan to select them with BDE platform, and each SP stores 1 / 10 of each copy.
**Copy 1** of Finance and taxation course data (1 / 10)
**Copy 2** of Finance and taxation course data (1 / 10)
**Copy 3** of Finance and taxation course data (1 / 10)
**Copy 4** of Finance and taxation course data (1 / 10)
**Copy 5** of Finance and taxation course data (1 / 10)

**Comment by liyunzhi-666** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebl4bgstpra4fdsbieadhzbwmr5eves7gzxdry3fneikmhi3exyli 
#### Address 
> f16ioghg3qy36f6572viouwv4dqow5ejpolo4kodi
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1pszcrsciyixyuxxukkvtazcokexbn54amf7gvoq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebl4bgstpra4fdsbieadhzbwmr5eves7gzxdry3fneikmhi3exyli

**Comment by Acc5com** [comment]
**_Progress update:_**
**1 / 5 (1 / 10)**: Hangzhou, China
https://www.bigd.exchange/detail/20220816073797

**2 / 5 (1 / 10)**: Singapore & Australia
https://www.bigd.exchange/detail/20220816742810
https://www.bigd.exchange/detail/20220816309107

**2 / 5 (1 / 10)**: Beijing & Shenzhen, China (not yet determined, in communication)
https://www.bigd.exchange/detail/20220816742810
https://www.bigd.exchange/detail/20220816309107

**Comment by medixccc** [comment]
Hi，@Acc5com ，We are a experienced SP from Hongkong with high-speed of seal,we'd like to coperate with you,and wanna get your contact information, you can contact us here:
Mail:crane9852@gmail.com

**Comment by zoecrane** [comment]
Hi，@Acc5com ，We are a experienced SP from Hongkong with high-speed of seal,we'd like to coperate with you,and wanna get your contact information, you can contact us here:
Mail:crane9852@gmail.com

**Comment by newwebgroup** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebivgv26ww6v4t5eho5kgsjbjz4yce4ejeigsb4kmd246c5pp5quc 
#### Address 
> f16ioghg3qy36f6572viouwv4dqow5ejpolo4kodi
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1e77zuityhvvw6u2t6tb5qlnsegy2s67qs4lbbbq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebivgv26ww6v4t5eho5kgsjbjz4yce4ejeigsb4kmd246c5pp5quc

**Comment by Tom-OriginStorage** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedkq64bqkuou2kthjkf4mh6uvfirnboxazbnyts4zrxltn6omahoo 
#### Address 
> f16ioghg3qy36f6572viouwv4dqow5ejpolo4kodi
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1q6bpjlqia6iemqbrdaxr2uehrhpvoju3qh4lpga
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedkq64bqkuou2kthjkf4mh6uvfirnboxazbnyts4zrxltn6omahoo

**Comment by BigD-Exchange** [comment]
@Acc5com Hi! Great to see you have gotten approval for DataCap. If you are looking for more storage providers to store these data or have any questions, please visit #bigdata-exchange on Filecoin Slack or reply here. 

We have strong demand from a diverse group of SPs, who are actively looking to onboard more data.

**Comment by raghavrmadya** [comment]
@Acc5com, can you clarify the issue? I can see the next request is triggered by the bot and is pending notary signature

**Comment by Acc5com** [comment]
Sir， @raghavrmadya 
Thank you for your attention and reply,
It was wrong before, but now Bot has returned to normal.

**Comment by fireflyHZ** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedz6b52424dp6gsz4giviph2iew6ots6ty24xgmapd3mofhkfvfms 
#### Address 
> f16ioghg3qy36f6572viouwv4dqow5ejpolo4kodi
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1fg6jkxsr3twfnyhdlatmq36xca6sshptscds7xa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedz6b52424dp6gsz4giviph2iew6ots6ty24xgmapd3mofhkfvfms

**Comment by newwebgroup** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebvslddu6dthsagjupx3ejxuw65aljqvx277zerpslvxtegzd6l2e 
#### Address 
> f16ioghg3qy36f6572viouwv4dqow5ejpolo4kodi
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1e77zuityhvvw6u2t6tb5qlnsegy2s67qs4lbbbq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebvslddu6dthsagjupx3ejxuw65aljqvx277zerpslvxtegzd6l2e

**Comment by Stoibers** [comment]
I support this issues because your data is complete, but I noticed that there is a particularly high proportion of nodes, what is the reason for this? It is recommended that the proportion of nodes should not exceed 25%.

**Comment by Stoibers** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedzz5rsyhucpz2fsgz2pvzefveijvyx4ph7rtr2m3tfi7v7zfz5sg 
#### Address 
> f16ioghg3qy36f6572viouwv4dqow5ejpolo4kodi
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1yayfsv6whu3rheviucvventj3y6t542xfpb47ei
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedzz5rsyhucpz2fsgz2pvzefveijvyx4ph7rtr2m3tfi7v7zfz5sg

**Comment by Acc5com** [comment]
Hi notaries，
Thanks for reminding, we will make corrections in the next round.
Because SPs are distributed in different regions, we provide data through offline transactions. Some data are affected by express delivery, and the delivery will be slow.
In addition, the packaging capacity of each SP is different. Some SPs have fast growth in computing power, while others are very slow.
We will make adjustments in the next round to curb those SPs that are faster.
> I support this issues because your data is complete, but I noticed that there is a particularly high proportion of nodes, what is the reason for this? It is recommended that the proportion of nodes should not exceed 25%.

**Comment by ipfscn** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacea4k2qhlx2icmskddle3ckqtoa25lwakww2t6czecfmjynorcn32e 
#### Address 
> f16ioghg3qy36f6572viouwv4dqow5ejpolo4kodi
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1j4n74chme7whbz3yls4a7ixqewb6dijypqg2a3a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacea4k2qhlx2icmskddle3ckqtoa25lwakww2t6czecfmjynorcn32e

**Comment by 1ane-1** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedxfrvvzhnlnegcfrxcw4v4ujge7r4ysrfeelq4klap6nxzfy2fwq 
#### Address 
> f16ioghg3qy36f6572viouwv4dqow5ejpolo4kodi
#### Datacap Allocated
> 1.56PiB
#### Signer Address
> f1mdk7s2vntzm6hu35yuo6vjubtrpfnb2awhgvrri
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedxfrvvzhnlnegcfrxcw4v4ujge7r4ysrfeelq4klap6nxzfy2fwq

**Comment by swatchliu** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceatjdd6ohe2unx46tifgel6subhquvcewldcs3go7qtgy6fvx5ung 
#### Address 
> f16ioghg3qy36f6572viouwv4dqow5ejpolo4kodi
#### Datacap Allocated
> 1.56PiB
#### Signer Address
> f1yh6q3nmsg7i2sys7f7dexcuajgoweudcqj2chfi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceatjdd6ohe2unx46tifgel6subhquvcewldcs3go7qtgy6fvx5ung

**Comment by newwebgroup** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedulaunawe5svzut5o65lhrg7p63er4xggqgn4kqypo7tsvjp56uy 
#### Address 
> f16ioghg3qy36f6572viouwv4dqow5ejpolo4kodi
#### Datacap Allocated
> 1.56PiB
#### Signer Address
> f1e77zuityhvvw6u2t6tb5qlnsegy2s67qs4lbbbq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedulaunawe5svzut5o65lhrg7p63er4xggqgn4kqypo7tsvjp56uy

**Comment by Joss-Hua** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced7jrpjqptug4vg7xievz4fi4lxy2s7o7p3ke4f5r2djqxe3l3vcs 
#### Address 
> f16ioghg3qy36f6572viouwv4dqow5ejpolo4kodi
#### Datacap Allocated
> 1.56PiB
#### Signer Address
> f1tfg54zzscugttejv336vivknmsnzzmyudp3t7wi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced7jrpjqptug4vg7xievz4fi4lxy2s7o7p3ke4f5r2djqxe3l3vcs

**Comment by 1ane-1** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced57sojqhpghn4q56nqv74fqb3mtcjeym7bmatqvcylsmpk2f2c3i 
#### Address 
> f16ioghg3qy36f6572viouwv4dqow5ejpolo4kodi
#### Datacap Allocated
> 425.11TiB
#### Signer Address
> f1mdk7s2vntzm6hu35yuo6vjubtrpfnb2awhgvrri
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced57sojqhpghn4q56nqv74fqb3mtcjeym7bmatqvcylsmpk2f2c3i

**Comment by kernelogic** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceapoc2tuh55ftkign5xpfniio6badek73sosahrf3denfbdjfqm7y 
#### Address 
> f16ioghg3qy36f6572viouwv4dqow5ejpolo4kodi
#### Datacap Allocated
> 425.11TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceapoc2tuh55ftkign5xpfniio6badek73sosahrf3denfbdjfqm7y

**Comment by herrehesse** [comment]
Why dit ANY notary sign this datacap? Clearly fraudulent. PiB's of duplicates.

⚠️ 72.54% of total deal sealed by [f01923786](https://filfox.info/en/address/f01923786) are duplicate data.
⚠️ 78.53% of total deal sealed by [f01923787](https://filfox.info/en/address/f01923787) are duplicate data.
⚠️ 72.55% of total deal sealed by [f01915287](https://filfox.info/en/address/f01915287) are duplicate data.
⚠️ 69.45% of total deal sealed by [f01922865](https://filfox.info/en/address/f01922865) are duplicate data.
⚠️ 58.64% of total deal sealed by [f01901379](https://filfox.info/en/address/f01901379) are duplicate data.
⚠️ 65.81% of total deal sealed by [f01660795](https://filfox.info/en/address/f01660795) are duplicate data.
⚠️ 57.37% of total deal sealed by [f01859603](https://filfox.info/en/address/f01859603) are duplicate data.
⚠️ 63.07% of total deal sealed by [f01870888](https://filfox.info/en/address/f01870888) are duplicate data.
⚠️ 62.29% of total deal sealed by [f01909429](https://filfox.info/en/address/f01909429) are duplicate data.
⚠️ 21.05% of total deal sealed by [f01901351](https://filfox.info/en/address/f01901351) are duplicate data.
⚠️ 28.78% of total deal sealed by [f01128206](https://filfox.info/en/address/f01128206) are duplicate data.
⚠️ 51.33% of total deal sealed by [f01907545](https://filfox.info/en/address/f01907545) are duplicate data.
⚠️ 26.06% of total deal sealed by [f01917009](https://filfox.info/en/address/f01917009) are duplicate data.
