### ISSUE TITLE
[DataCap Application]Qingdao Regency Hotel

### ISSUE THREAD

**Issue by htlw** [filecoin-project/filecoin-plus-large-datasets#515]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Qingdao Regency Hotel
- Website / Social Media:http://www.regencyhotelqd.com/home
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):4PIB
- Weekly allocation of DataCap requested (usually between 1-100TiB):200TIB
- On-chain address for first allocation:f1fzjtvybe74vk5odtxkwafb4v5jryrithg2ihwdq

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Qingdao Regency Hotel located in the center of Qingdao's most prosperous eastern business district, the hotel is surrounded by financial, catering, entertainment and shopping facilities, 70 minutes' drive from Qingdao Jiaozhou International Airport and 20 minutes' drive from the railway station; It is a 5-minute drive from the municipal government, May Fourth Square and the Olympic Sailing Center.

As the first five-star hotel in Shandong Province, since its opening, the hotel has successfully received many dignitaries including former German Prime Minister Kohl, former Singapore Senior Minister Lee Kuan Yew, Singapore Prime Minister Lee Hsien Loong, former United Nations Secretary-General Ban Ki-moon, former South Korean Prime Minister Han Seung-so, former Special Assistant to the Prime Minister of Japan, Speaker and Mayor of Kyoto Prefecture, Mayor of Miyazaki City, former Chairman of the Russian House of Lords, Commander of multinational navies and many Fortune 500 CEOs.

In June 2018, as the key foreign guest reception hotel of the SCO Qingdao Summit, we successfully received the then President of Iran Hassan Rouhani and his delegation, as well as the visiting Presidents of Belarus, Pakistan and Afghanistan. The President of Iran and the visiting presidents and dignitaries of various countries have given high praise to the hotel's perfect hardware facilities, head of state-level distinguished services and special catering and cuisine. 

The hotel has 395 rooms, each of which has been carefully decorated with a special style. The hotel also has meeting rooms, swimming pools, Chinese restaurants, Western restaurants, banquet halls, multi-functional halls, beauty salons, gyms, billiards, indoor golf, bowling, outdoor tennis courts, etc., with rich venues and perfect services for users.
```

What is the primary source of funding for this project?
```
Own funds
```

What other projects/ecosystem stakeholders is this project associated with?
```
No stakeholders 
```

## Use-case details

Describe the data being stored onto Filecoin
```
The data stored on the Filecoin network are mainly pictures and videos, such as the shooting records of hotel rooms and hotel lobbies, the records of meetings in the hotel conference hall, the records of the cooking of the chefs in the hotel kitchen, the records of the activities of the hotel staff, etc.
```

Where was the data in this dataset sourced from?
```
From hotel rooms, hotel public facilities such as swimming pools, banquet halls, conference rooms, restaurants, etc., as well as content stored by hotel camera equipment.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://drive.google.com/drive/folders/1_t624AIFZuUc1F8kZP8GDzryXsuBAq3W?usp=sharing
https://drive.google.com/drive/folders/1BUHscdv2Thp4th9mUJsKTFVfrI2O0Apd?usp=sharing
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Confirm
```

What is the expected retrieval frequency for this data?
```
Retrieval is carried out according to the actual situation, there is no fixed frequency, it may be retrieval once a month or once a year.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
about 12 months
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
All
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Our data is relatively large, we tend to offline transfer
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We plan to store the data in multiple SPs to improve the reliable storage of the data
```

How will you be distributing deals across storage providers?
```
Fair and equitable distribution, try to allow more storage providers to participate in the data storage process
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes
```

**Comment by Sunnyiscoming** [comment]
Could you send an email to filplus-app-review@fil.org with your official domain in order to confirm your identity?
Email name should includes the issue id #515.

**Comment by raghavrmadya** [comment]
What's your relationship with Beijing Zhonglianlixin Technology Co., Ltd. Your IP is in Beijing.

**Comment by raghavrmadya** [comment]
How long have you been in operation? We cannot ascertain your legitimacy through the website as there are many stock images used. How long have you been in operation?

**Comment by htlw** [comment]
Thanks for your replies.

The mailbox of the Business Development Department of Regent Hotel Qingdao has sent an email to filplus-app-review@fil.org, please check.

Our official website http://www.regencyhotelqd.com/home is entrusted to Beijing Zhonglianlixin Technology Co., Ltd. for hosting, so the IP of our website is displayed in Beijing.

Our hotel has been established for 30 years. It is a well-known hotel with a long history. Our data is very rich. We decided to apply for 4P data from you first for storage. Of course, if we can, we hope to be able to store More data is stored on the Filecoin network.

**Comment by htlw** [comment]
![20220811150117](https://user-images.githubusercontent.com/80449172/184080715-f5737dc0-9866-4294-bdda-542207790a7f.jpg)

**Comment by tobbytheelephant** [comment]
Are you storing surveillance video?

**Comment by htlw** [comment]
Since we are adding a lot of data every day, we think that the data we generate every day can meet the 4P capacity we apply for. Therefore, we do not consider storing surveillance for the time being.

**Comment by raghavrmadya** [comment]
Your application says you will store surveillance data but the comment above says otherwise. Please open a new application with more detail on what data will you store exactly and SP distribution with any SPs you are in touch with. You can find SPs on Filecoin slack, BigDexchange, and Filgram. Also please link this application to the new application to move quicker. 

Thanks.

**Comment by htlw** [comment]
#797

**Comment by htlw** [comment]
Hello, we have resubmitted the new application based on your request. The new application is https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/797
