### ISSUE TITLE
[DataCap Application] Migo video

### ISSUE THREAD

**Issue by MigoVideo** [filecoin-project/filecoin-plus-large-datasets#517]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: MigoVideo
- Website / Social Media: http://www.yisfood.com/index.html 
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100TiB
- On-chain address for first allocation:f1rnwp6p5kx7pcwexpucoav6mmwz3rkxw5blrboyy

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
MigoVideo was founded on May 29, 2018, the registered office is located in Haizhu District, Guangzhou City, the scope of business includes the planning of cultural activities for the public interest such as cultural performances and competitions involving the masses; corporate image planning services; conference and exhibition services; marketing planning services; corporate etiquette services; commodity information consulting services; scientific and technological information consulting services; social welfare information consulting services photography services; industrial design services; packaging and decoration design services; multimedia design services; animation and derivative product design services; decoration design services; model design services; art design services; jewelry design services; advertising; wholesale trade in goods (except for licensing and approval of goods); retail trade in goods (except for licensing and approval of goods); import and export of goods (except for the exclusive exclusive control of goods (except for the license approval category); technology import and export; Internet merchandising (except for the license approval category); alcohol wholesale; prepackaged food wholesale; prepackaged food retail.
```

What is the primary source of funding for this project?
```
Own funding.
```

What other projects/ecosystem stakeholders is this project associated with?
```
No.
```

## Use-case details

Describe the data being stored onto Filecoin
```
Lots of videos about cooking and images of menus.
```

Where was the data in this dataset sourced from?
```
Our website has a long-running competition about cooking that attracts a large number of users to submit videos.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
[1112.zip](https://github.com/filecoin-project/filecoin-plus-large-datasets/files/9158619/1112.zip)
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Confirm.
```

What is the expected retrieval frequency for this data?
```
We have already planned to retrieve it twice a year.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
2-3 years.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
China or other nearby countries in Asia.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Considering our network, we use offline transfer.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
Consider their network and technology, we prefer professional SP for deals.
```

How will you be distributing deals across storage providers?
```
It up to SPs' actual seal capacity. And we follow the rules about distributing.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes!
```

**Comment by MigoVideo** [comment]
![981DD04F-D4AB-431A-B715-595ECEBD0A3D](https://user-images.githubusercontent.com/107090974/181300010-a7d61207-2eb2-44f4-8ba2-b6fc55941e33.jpeg)
Hi governance team, please check my email.

**Comment by Sunnyiscoming** [comment]
Can you provide more detailed information about storage providers distribution, such as you can list SPs you have contacted with at present?

**Comment by Sunnyiscoming** [comment]
Could you send an email to filplus-app-review@fil.org with your official domain in order to confirm your identity?
Email name should includes the issue id #517.

**Comment by MigoVideo** [comment]
@Sunnyiscoming We planned to make deals in Hong Kong, Singapore and maybe more places. We just these SPs: f095382, f01823202, f0166327, f0811662
We've sent the email. Thank you.
![302](https://user-images.githubusercontent.com/107090974/185728844-431ad8a0-059e-49e1-a39c-1549a255a90f.jpg)

**Comment by Sunnyiscoming** [comment]
Received that.
It seems that these nodes is unreachable. Why you choose them?
https://filrep.io/?search=f095382
https://filrep.io/?search=f0166327
https://filrep.io/?search=f0811662

**Comment by MigoVideo** [comment]
@Sunnyiscoming Hi Sunny, thank you for the tip. We have communicated with SPs about this. They believe that the CC sector data has no real value and is not necessary to be retrieved publicly. If they start storing validation data, they can support public retrieval based on rules.

**Comment by raghavrmadya** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 100TiB

**Client address**

>f1rnwp6p5kx7pcwexpucoav6mmwz3rkxw5blrboyy

**Comment by swatchliu** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedm7sfcwwxrqo7ya5f54qcfd3kwpldm7rx3vpnu636yyypgc5dmdy 
#### Address 
> f1rnwp6p5kx7pcwexpucoav6mmwz3rkxw5blrboyy
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1yh6q3nmsg7i2sys7f7dexcuajgoweudcqj2chfi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedm7sfcwwxrqo7ya5f54qcfd3kwpldm7rx3vpnu636yyypgc5dmdy

**Comment by MatrixStorage** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedjmvxopylbydr2e4eu3ejr3zfk2uxqedxgfveefcpow4eq7muan2 
#### Address 
> f1rnwp6p5kx7pcwexpucoav6mmwz3rkxw5blrboyy
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1tbxqwjxfyv7swsdin4einirlsfquv3vnmlapley
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedjmvxopylbydr2e4eu3ejr3zfk2uxqedxgfveefcpow4eq7muan2

**Comment by BigD-Exchange** [comment]
@MigoVideo Hi! Great to see you have gotten approval for DataCap. If you are looking for more storage providers to store these data or have any questions, please visit #bigdata-exchange on Filecoin Slack or reply here. 

We have strong demand from a diverse group of SPs, who are actively looking to onboard more data.

**Comment by 1475Notary** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedyjijn4nebcjf7ahtoo5xxjyqkpoqgoalq7z7qxbpgwtcoxbcapo 
#### Address 
> f1rnwp6p5kx7pcwexpucoav6mmwz3rkxw5blrboyy
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1ofq4mngy7ggcp755pfquq2gphjjnlydolf6awtq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedyjijn4nebcjf7ahtoo5xxjyqkpoqgoalq7z7qxbpgwtcoxbcapo

**Comment by MatrixStorage** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacea6zdmkcsrpe6dqasi7c4zvs3i6eeoqisc4625xdiayormq7tqy7k 
#### Address 
> f1rnwp6p5kx7pcwexpucoav6mmwz3rkxw5blrboyy
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1tbxqwjxfyv7swsdin4einirlsfquv3vnmlapley
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacea6zdmkcsrpe6dqasi7c4zvs3i6eeoqisc4625xdiayormq7tqy7k

**Comment by PluskitOfficial** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebzq2aztqmok3hxb7rk5ra3nqzg4jheisv4ibg6zliajj26xflz7w 
#### Address 
> f1rnwp6p5kx7pcwexpucoav6mmwz3rkxw5blrboyy
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1tgnlhtcmhwipfm7thsftxhn5k52velyjlazpvka
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebzq2aztqmok3hxb7rk5ra3nqzg4jheisv4ibg6zliajj26xflz7w

**Comment by MRJAVAZHAO** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecgo2k5mhgf72znpfaieykfn5bc3mq7x2s5iwsncycirj7trhy26a 
#### Address 
> f1rnwp6p5kx7pcwexpucoav6mmwz3rkxw5blrboyy
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f14gme3f52prtyzk6pblogrdd6b6ivp4swc6qmesi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecgo2k5mhgf72znpfaieykfn5bc3mq7x2s5iwsncycirj7trhy26a

**Comment by MatrixStorage** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebxdri4ov72yjsfzecid34sohcd5ygkuoeqx2sfaetrnivl4dyxfc 
#### Address 
> f1rnwp6p5kx7pcwexpucoav6mmwz3rkxw5blrboyy
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1tbxqwjxfyv7swsdin4einirlsfquv3vnmlapley
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebxdri4ov72yjsfzecid34sohcd5ygkuoeqx2sfaetrnivl4dyxfc

**Comment by PluskitOfficial** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaurd6jdpv3n6k2hng5y3q7dfp3hycmcm32latrozlz37u3llbuzo 
#### Address 
> f1rnwp6p5kx7pcwexpucoav6mmwz3rkxw5blrboyy
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1tgnlhtcmhwipfm7thsftxhn5k52velyjlazpvka
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaurd6jdpv3n6k2hng5y3q7dfp3hycmcm32latrozlz37u3llbuzo

**Comment by MRJAVAZHAO** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebuvtsmobvv2acxep2lnvbxugdpmy5jav4b54duuu5bzetbjt5o2k 
#### Address 
> f1rnwp6p5kx7pcwexpucoav6mmwz3rkxw5blrboyy
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f14gme3f52prtyzk6pblogrdd6b6ivp4swc6qmesi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebuvtsmobvv2acxep2lnvbxugdpmy5jav4b54duuu5bzetbjt5o2k

**Comment by psh0691** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebkvvaphpdd6haucgoh7ray4uqwppzrq3hsyuj7prcl3qrbct6k5e 
#### Address 
> f1rnwp6p5kx7pcwexpucoav6mmwz3rkxw5blrboyy
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1qdko4jg25vo35qmyvcrw4ak4fmuu3f5rif2kc7i
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebkvvaphpdd6haucgoh7ray4uqwppzrq3hsyuj7prcl3qrbct6k5e

**Comment by MetaWaveInfo** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedyaqfnr5q3xftmbsi6uq6rrurrxkcmykmwqwcx5ncsoinejolzce 
#### Address 
> f1rnwp6p5kx7pcwexpucoav6mmwz3rkxw5blrboyy
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1ktlkcxnmzxcdaoqfsunrg3vocfbmgv4n3mrn74a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedyaqfnr5q3xftmbsi6uq6rrurrxkcmykmwqwcx5ncsoinejolzce

**Comment by 1475Notary** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecdujnx2peuw3otnfnkg7hcliylcxtuogdoxv26k2h55gm4vhnpdk 
#### Address 
> f1rnwp6p5kx7pcwexpucoav6mmwz3rkxw5blrboyy
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1ofq4mngy7ggcp755pfquq2gphjjnlydolf6awtq
#### Id
> 89b30947-de6e-4459-806d-fc326879fcb5
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecdujnx2peuw3otnfnkg7hcliylcxtuogdoxv26k2h55gm4vhnpdk

**Comment by YuanHeHK** [comment]
After checking the previous rounds of packaging, everything is normal, the highest SP ratio is 16.66, I will give this signature

**Comment by YuanHeHK** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecrzrmhrzkuvjkaq4byrl2uhgfh2yxqqx4yxw2jqw5fd2at4wimvq 
#### Address 
> f1rnwp6p5kx7pcwexpucoav6mmwz3rkxw5blrboyy
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1fg6jkxsr3twfnyhdlatmq36xca6sshptscds7xa
#### Id
> 47a68d97-fc0f-459f-b459-38df6903240b
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecrzrmhrzkuvjkaq4byrl2uhgfh2yxqqx4yxw2jqw5fd2at4wimvq

**Comment by UnionLabs2020** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced5nmctiv53nrqapmp4lj643vazf3y4b5wx5lea47xgicmlcppqsu 
#### Address 
> f1rnwp6p5kx7pcwexpucoav6mmwz3rkxw5blrboyy
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f17xdri3wunqgld7dm23e4f3eqsntjakwc47xjo6i
#### Id
> 47a68d97-fc0f-459f-b459-38df6903240b
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced5nmctiv53nrqapmp4lj643vazf3y4b5wx5lea47xgicmlcppqsu

**Comment by MetaWaveInfo** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedzijszqpdpmiwlfihmtgstmw657yob3zn2agnssytqkeueomszpm 
#### Address 
> f1rnwp6p5kx7pcwexpucoav6mmwz3rkxw5blrboyy
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1ktlkcxnmzxcdaoqfsunrg3vocfbmgv4n3mrn74a
#### Id
> fc51274c-6348-4815-acc3-288bfcb5b7ff
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedzijszqpdpmiwlfihmtgstmw657yob3zn2agnssytqkeueomszpm

**Comment by swatchliu** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb6ov2y5wxt76bon3k6cx7dojrd73hzkvno677blov3cnpp74kafg 
#### Address 
> f1rnwp6p5kx7pcwexpucoav6mmwz3rkxw5blrboyy
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1yh6q3nmsg7i2sys7f7dexcuajgoweudcqj2chfi
#### Id
> fc51274c-6348-4815-acc3-288bfcb5b7ff
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb6ov2y5wxt76bon3k6cx7dojrd73hzkvno677blov3cnpp74kafg

**Comment by filplus-checker** [comment]
## DataCap and CID Checker Report[^1]
 - Organization: `MigoVideo`
 - Client: `f1rnwp6p5kx7pcwexpucoav6mmwz3rkxw5blrboyy`
### Storage Provider Distribution
The below table shows the distribution of storage providers that have stored data for this client.

If this is the first time a provider takes verified deal, it will be marked as `new`.

For most of the datacap application, below restrictions should apply.
 - Storage provider should not exceed 25% of total datacap.
 - Storage provider should not be storing duplicate data for more than 20%.
 - Storage provider should have published its public IP address.
 - All storage providers should be located in different regions.

⚠️ 79.31% of total deal sealed by [f01926914](https://filfox.info/en/address/f01926914) are duplicate data.

⚠️ 78.90% of total deal sealed by [f01926802](https://filfox.info/en/address/f01926802) are duplicate data.

⚠️ 78.33% of total deal sealed by [f01926585](https://filfox.info/en/address/f01926585) are duplicate data.

⚠️ 70.64% of total deal sealed by [f01924416](https://filfox.info/en/address/f01924416) are duplicate data.

⚠️ 84.17% of total deal sealed by [f01937964](https://filfox.info/en/address/f01937964) are duplicate data.

⚠️ 89.91% of total deal sealed by [f01889480](https://filfox.info/en/address/f01889480) are duplicate data.

⚠️ 77.82% of total deal sealed by [f01924325](https://filfox.info/en/address/f01924325) are duplicate data.

⚠️ 30.52% of total deal sealed by [f01900713](https://filfox.info/en/address/f01900713) are duplicate data.

⚠️ 72.11% of total deal sealed by [f01924350](https://filfox.info/en/address/f01924350) are duplicate data.

⚠️ 49.26% of total deal sealed by [f01917214](https://filfox.info/en/address/f01917214) are duplicate data.

| Provider                                                    |                 Location | Total Deals Sealed | Percentage | Unique Data | Duplicate Deals |
| :---------------------------------------------------------- | -----------------------: | -----------------: | ---------: | ----------: | --------------: |
| [f01926914](https://filfox.info/en/address/f01926914)       |    Ashburn, Virginia, US |         514.34 TiB |     17.28% |  106.41 TiB |          79.31% |
| [f01926802](https://filfox.info/en/address/f01926802)       |    Ashburn, Virginia, US |         462.94 TiB |     15.55% |   97.69 TiB |          78.90% |
| [f01926585](https://filfox.info/en/address/f01926585)       |    Ashburn, Virginia, US |         449.41 TiB |     15.10% |   97.41 TiB |          78.33% |
| [f01924416](https://filfox.info/en/address/f01924416)       | Singapore, Singapore, SG |         380.53 TiB |     12.79% |  111.72 TiB |          70.64% |
| [f01937964](https://filfox.info/en/address/f01937964)       |         Tokyo, Tokyo, JP |         223.81 TiB |      7.52% |   35.44 TiB |          84.17% |
| [f01889480](https://filfox.info/en/address/f01889480)       |     Boardman, Oregon, US |         198.81 TiB |      6.68% |   20.06 TiB |          89.91% |
| [f01924325](https://filfox.info/en/address/f01924325)       | Singapore, Singapore, SG |         157.63 TiB |      5.30% |   34.97 TiB |          77.82% |
| [f01900713](https://filfox.info/en/address/f01900713)       |         Seoul, Seoul, KR |         150.00 TiB |      5.04% |  104.22 TiB |          30.52% |
| [f01924350](https://filfox.info/en/address/f01924350)       | Singapore, Singapore, SG |          80.00 TiB |      2.69% |   22.31 TiB |          72.11% |
| [f01917214](https://filfox.info/en/address/f01917214)       |         Seoul, Seoul, KR |          79.88 TiB |      2.68% |   40.53 TiB |          49.26% |
| [f01917257](https://filfox.info/en/address/f01917257)`new`  |         Seoul, Seoul, KR |          72.00 TiB |      2.42% |   72.00 TiB |           0.00% |
| [f01917241](https://filfox.info/en/address/f01917241)       |         Seoul, Seoul, KR |          59.00 TiB |      1.98% |   59.00 TiB |           0.00% |
| [f01895715](https://filfox.info/en/address/f01895715)       |         Seoul, Seoul, KR |          57.97 TiB |      1.95% |   46.44 TiB |          19.89% |
| [f01917236](https://filfox.info/en/address/f01917236)`new`  |         Seoul, Seoul, KR |          45.41 TiB |      1.53% |   43.44 TiB |           4.34% |
| [f01917208](https://filfox.info/en/address/f01917208)`new`  |         Seoul, Seoul, KR |          44.66 TiB |      1.50% |   38.22 TiB |          14.42% |

![Provider Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/517/1671097331659.png)
### Deal Data Replication
The below table shows how each many unique data are replicated across storage providers.
- No more than 25% of unique data are stored with less than 4 providers.

⚠️ 99.96% of deals are for data replicated across less than 4 storage providers.

| Unique Data Size | Total Deals Made | Number of Providers | Deal Percentage |
| ---------------: | ---------------: | ------------------: | --------------: |
|       562.78 TiB |         1.59 PiB |                   1 |          54.72% |
|       118.34 TiB |       925.50 TiB |                   2 |          31.09% |
|        43.13 TiB |       420.97 TiB |                   3 |          14.14% |
|       256.00 GiB |         1.25 TiB |                   4 |           0.04% |

![Replication Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/517/1671097332339.png)
### Deal Data Shared with other Clients
The below table shows how many unique data are shared with other clients.
Usually different applications owns different data and should not resolve to the same CID.

⚠️ CID sharing has been observed.

| Other Client                                                                                                          | Application                                                                                                                | Total Deals Affected | Unique CIDs |                                                                                 Verifier |
| :-------------------------------------------------------------------------------------------------------------------- | :------------------------------------------------------------------------------------------------------------------------- | -------------------: | ----------: | ---------------------------------------------------------------------------------------: |
| [f1zb6pgkktdbyy7zxfob6gripqxuc25ukf35cc7fq](https://filfox.info/en/address/f1zb6pgkktdbyy7zxfob6gripqxuc25ukf35cc7fq) | `Maxpic PhotoGraphic Studio`                                                                                               |           466.84 TiB |       3,374 |                                                                          LDN v3 multisig |
| [f1einobkrjcjk6gfc5ov6663vrri75hwdsjfs6pmq](https://filfox.info/en/address/f1einobkrjcjk6gfc5ov6663vrri75hwdsjfs6pmq) | [Cansoti](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/640)                                     |           308.28 TiB |       3,096 |                                                                          LDN v3 multisig |
| [f1ivsvpljx4ovp2tth73pllkxmumrudemks623iia](https://filfox.info/en/address/f1ivsvpljx4ovp2tth73pllkxmumrudemks623iia) | `TIS Inc. group`                                                                                                           |           190.75 TiB |       1,716 |                                                                          LDN v3 multisig |
| [f1vtcetpapwwyka6txwqjwymsa67npdfilbkwh64a](https://filfox.info/en/address/f1vtcetpapwwyka6txwqjwymsa67npdfilbkwh64a) | [Chimay](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/397)                                      |           173.34 TiB |       1,897 |                                                                          LDN v3 multisig |
| [f1727w2vwjctfo7hflr5trgqkl3c7texh7pl4grzq](https://filfox.info/en/address/f1727w2vwjctfo7hflr5trgqkl3c7texh7pl4grzq) | [GMverse](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/365)                                     |           154.38 TiB |       1,480 |                                                                          LDN v3 multisig |
| [f1xtnkj5ti77f5gbzhclnpj3xt6e5dwhfzive2yca](https://filfox.info/en/address/f1xtnkj5ti77f5gbzhclnpj3xt6e5dwhfzive2yca) | [Beacon Project](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/482)                              |           128.38 TiB |         340 | Project Beacon, 12 LDNs LDN # 444, 446, 447, 448, 474, 475, 476, 477, 479, 480, 481, 482 |
| [f1ajdk7e6ex7fvtjtydzgys47bcg7jub2baucun7y](https://filfox.info/en/address/f1ajdk7e6ex7fvtjtydzgys47bcg7jub2baucun7y) | [Ruikuyun Information Technology Co\., Ltd](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/529)   |           110.81 TiB |       1,685 |                                                                          LDN v3 multisig |
| [f1f5edx6ofn3lf6rk3yfpldbi2pzgq2egoyu6ubpi](https://filfox.info/en/address/f1f5edx6ofn3lf6rk3yfpldbi2pzgq2egoyu6ubpi) | [Samdata Trade](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/382)                               |            90.78 TiB |       1,569 |                                                                          LDN v3 multisig |
| [f1ki4cjk27ypzjsuzkvvqzs6xobaweuoxfdcnpqhy](https://filfox.info/en/address/f1ki4cjk27ypzjsuzkvvqzs6xobaweuoxfdcnpqhy) | [TimeQuant](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/385)                                   |            85.72 TiB |       1,028 |                                                                          LDN v3 multisig |
| [f17qd6x3leh5pa7vh6ewdaed7qhbn2mgofrokuayy](https://filfox.info/en/address/f17qd6x3leh5pa7vh6ewdaed7qhbn2mgofrokuayy) | [Drust](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/427)                                       |            76.25 TiB |         913 |                                                                          LDN v3 multisig |
| [f14abwn2goturifmt27s2bssoe3fup2b3npkgfzui](https://filfox.info/en/address/f14abwn2goturifmt27s2bssoe3fup2b3npkgfzui) | [KONGFU VR](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/372)                                   |            59.75 TiB |       1,109 |                                                                          LDN v3 multisig |
| [f1bb2z36lpq3pnwiiowiraagpzqnpow4bonjacx7a](https://filfox.info/en/address/f1bb2z36lpq3pnwiiowiraagpzqnpow4bonjacx7a) | [Hola Space](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/362)                                  |            46.09 TiB |         516 |                                                                          LDN v3 multisig |
| [f1avhqgmeazxzvylz34l26o3nlj2ywnzaviwns3dq](https://filfox.info/en/address/f1avhqgmeazxzvylz34l26o3nlj2ywnzaviwns3dq) | [87v5\-CarsonVideo](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/392)                           |            22.41 TiB |         314 |                                                                          LDN v3 multisig |
| [f1xyx3tvfoy7ue62oqdtcpud5ewcw2i7ctu4kyylq](https://filfox.info/en/address/f1xyx3tvfoy7ue62oqdtcpud5ewcw2i7ctu4kyylq) | [zhenshuai](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/332)                                   |            19.97 TiB |         132 |                                                                                LDN # 332 |
| [f1quofpadzcqlonmz7v3mv7dfqvm5hdztucdsjqsy](https://filfox.info/en/address/f1quofpadzcqlonmz7v3mv7dfqvm5hdztucdsjqsy) | [HENAN 863 SOFTWARE CO\., LTD](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/468)                |            18.59 TiB |         272 |                                                                          LDN v3 multisig |
| [f1clwd2dooy2cflfilhzeq2ycl544b3heqsiwhjrq](https://filfox.info/en/address/f1clwd2dooy2cflfilhzeq2ycl544b3heqsiwhjrq) | [FiboAI](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/349)                                      |            17.59 TiB |         358 |                                                                          LDN v3 multisig |
| [f1dwhevm3p2slu6itmkssznscmpkpltdiztprnpya](https://filfox.info/en/address/f1dwhevm3p2slu6itmkssznscmpkpltdiztprnpya) | [Hiscene](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/548)                                     |            15.38 TiB |         127 |                                                                          LDN v3 multisig |
| [f1nmhjvibl7acp45lpxmo5kduz42evjazsyi4mzza](https://filfox.info/en/address/f1nmhjvibl7acp45lpxmo5kduz42evjazsyi4mzza) | `ubuckvnockai`                                                                                                             |            14.06 TiB |          83 |                                                                          LDN v3 multisig |
| [f1tivtdkq34mnfzso63wrr2xh6r2zo7aebao4jfla](https://filfox.info/en/address/f1tivtdkq34mnfzso63wrr2xh6r2zo7aebao4jfla) | `China travel service(HongKong) limited`                                                                                   |             2.25 TiB |           7 |                                                                          LDN v3 multisig |
| [f1jdmx2cuswzjlt4pnsv3t7ipmesywzxsg6q56a2a](https://filfox.info/en/address/f1jdmx2cuswzjlt4pnsv3t7ipmesywzxsg6q56a2a) | [Raysun Radar Electronic Technology Co\.,Ltd](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/884) |           896.00 GiB |           9 |                                                                          LDN v3 multisig |
| [f1b5r6ewhodewcjwqumkeycpvfkxcxkzrstlvo5ga](https://filfox.info/en/address/f1b5r6ewhodewcjwqumkeycpvfkxcxkzrstlvo5ga) | [Ruiyi](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/705)                                       |           608.00 GiB |           7 |                                                                          LDN v3 multisig |
| [f1mn5mw2dpqz6p3s7vxrlkhkh3okdtc6t7wqro4xa](https://filfox.info/en/address/f1mn5mw2dpqz6p3s7vxrlkhkh3okdtc6t7wqro4xa) | [Unisound](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/577)                                    |           256.00 GiB |           3 |                                                                          LDN v3 multisig |
| [f1qjrlejxv5a73kxurwtxyrni6ji7orm74zeeetiy](https://filfox.info/en/address/f1qjrlejxv5a73kxurwtxyrni6ji7orm74zeeetiy) | [Mooc](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/223)                                        |           128.00 GiB |           2 |                                                                          LDN v3 multisig |
| [f1ffbtksiso5za73pypuxbxznng6rdv64nbihdtba](https://filfox.info/en/address/f1ffbtksiso5za73pypuxbxznng6rdv64nbihdtba) | [EpikProtocol](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/281)                                |            64.00 GiB |           2 |                                                                                LDN # 281 |

[^1]: To manually trigger this report, add a comment with text `checker:manualTrigger`

**Comment by Sunnyiscoming** [comment]
Hello, per the https://github.com/filecoin-project/notary-governance/issues/922 for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

This information will be reviewed by Fil+ Governance team to confirm validity and then the application will be allowed to move forward for additional notary review.
