### ISSUE TITLE
[DataCap Application] <yueke> - <DEBOX>

### ISSUE THREAD

**Issue by litai686** [filecoin-project/filecoin-plus-large-datasets#521]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Shenzhen yuekeyun
- Website / Social Media: https://www.debox.top/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 200TB
- On-chain address for first allocation:  f14lwf3q5ihmacnp4bd3ai3upd3kficremy26foxi

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
We have developed a set of fast retrieval device debox for Storage providers. 
We will back up the world's public software libraries to the filecoin network and 
all blockchain generates snapshots of data every day  to the filecoin network.
We will also look for meaningful public data to back up to the filecoin network. 
At the same time, we will save the piece file to the debox device for data caching and provide fast retrieval services.

This box device is developed based on IPFS. 
They will be placed in home networks all over the world and 
provide retrieval services externally through the market gateway we developed. 
When users request data through CID,
it will assist SPs to retrieve data quickly, 
which makes SPs not need to do unsealed process
```

What is the primary source of funding for this project?
```
Sell our DEBOX devices
```

What other projects/ecosystem stakeholders is this project associated with?
```
No，We need to find SP, back up our data to filecoin, and provide retrieval services for SP at the same time 
```

## Use-case details

Describe the data being stored onto Filecoin
```
1. The world's public software libraries 
2. Blockchain generates snapshots of data every day 
3. Surveillance video
4. Photos of tourists in the scenic spot
```

Where was the data in this dataset sourced from?
```
http://datasets.datalad.org/
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
http://datasets.datalad.org/?dir=/allen-brain-observatory/visual-coding-neuropixels/raw-data

```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes
```

What is the expected retrieval frequency for this data?
```
at any time
```

For how long do you plan to keep this dataset stored on Filecoin?
```
1 years
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
China 
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Online or offline
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We are not SP , The box we developed is to provide faster retrieval services for SPs. 
There is no connection between us and SPs
```

How will you be distributing deals across storage providers?
```
We will look for SPs and distribute data to them through DEBOX
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, we have joined Deal Accelerator
```

**Comment by Sunnyiscoming** [comment]
Can you share more information about storage providers you have contacted with?

**Comment by litai686** [comment]
1、Some SP met  through friends，Others are selected through the LDN platform
2、Our company has a large datasets，Our business is to collect and retrieve datasets，We will back up a copy of the datasets to the filecoin network, and provide fast retrieval services through our developed debox

**Comment by Sunnyiscoming** [comment]
Can you list SPs you have contacted with at present?

**Comment by litai686** [comment]
@Sunnyiscoming  @Joss-Hua   I have sent the SPs I contacted to the [filplus-app-review@fil.org](mailto:filplus-app-review@fil.org) mail

**Comment by Sunnyiscoming** [comment]
It seems that these nodes is unreachable. Why you choose them?                      
https://filrep.io/?search=f0709366
https://filrep.io/?search=f01349048

**Comment by litai686** [comment]
They told me that when I need to back up data, it will be open, But they told me that they are open ports. It should be a network problem！

**Comment by raghavrmadya** [comment]
Can you provide more evidence that the data is public? What you are describing does not seem fully public

**Comment by litai686** [comment]
Our data are mainly from http://datasets.datalad.org and  public data set on Amazon and   photos of tourists in Chinese scenic spots  https://www.etu1314.com/

**Comment by Sunnyiscoming** [comment]
https://www.etu1314.com/
It seems that it is not public. Can you explain about that?

**Comment by litai686** [comment]
This website https://www.etu1314.com/  is an entrance for tourists' photo retrieval. Each photo has its own code. These codes are open by default, and will be given to tourists when taking photos. Tourists can also share these photos themselves.  I can provide you with some photo codes for retrieval, such as :
B0887-20220809101703-A5-13  
BR0773-20220906145117-A1-62
B0887-20220809101620-A5-11
B0773-20220904121220-CB03-137

In addition, this system is also based on debox. The following is the system architecture diagram
<img width="856" alt="image" src="https://user-images.githubusercontent.com/38679986/188827151-0d2dbefe-3762-4e92-ac64-5a7f1c4bfa61.png">

**Comment by raghavrmadya** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 200TiB

**Client address**

>f14lwf3q5ihmacnp4bd3ai3upd3kficremy26foxi

**Comment by litai686** [comment]
@raghavrmadya  Why does the robot reject your message？

**Comment by litai686** [comment]
@raghavrmadya  Are there any questions? When can the datacap be approved？

**Comment by raghavrmadya** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 200TiB

**Client address**

>f14lwf3q5ihmacnp4bd3ai3upd3kficremy26foxi

**Comment by litai686** [comment]
@Sunnyiscoming Hi，Excuse me, are you a notary？ Can you sign it for me？

**Comment by neogeweb3** [comment]
Your application has changed quite a lot since your last DataCap [request ](https://github.com/filecoin-project/filecoin-plus-client-onboarding/issues/1757)back in May. From what I learned, your application targets storing photos of tourists which are considered private datasets instead of public. I believe tourist photography is just one of your box use cases, but other use cases should fall under the same category of individual and/or enterprise datasets - private. Because of the nature of private datasets, which are practically impossible to verify, I would suggest you find at least 4 notaries to support your application. There is one successful [example ](https://github.com/filecoin-project/notary-governance/issues/489)that I support. You could ask notaries to sign NDA (Non-Disclosure Agreement) to protect the confidentiality of yourself and your clients - aka buyers of your boxes. The best place to find notaries is the Slack channel, and the best place to demonstrate your business and speed up the entire process is the governance call. 

With that being said, it's just hard to imagine how your company(深圳市悦科技云科技有限公司) produced and made sales of 10k 64TB boxes with less than 30k US dollars authorized capital. So is your 5PiB DataCap requested. Unfortunately, there is still a big gap between you and a trustworthy client, IMHO. Therefore, I don't feel confident in proposing or approving this application at the moment.

**Comment by litai686** [comment]
@neogeweb3  Thank you very much for your answer. We are a software and hardware solution company，We are not  only a company.  Our sales company and technology research and development company operate separately，Based on IPFS technology, we have developed many products, which are applied in different industries, We have a large number of partners.     First of all, we made the product and sold it. This is a fact. We actively participate in the FILECOIN ecosystem. We have a large amount of data that conforms to the LDN rules. This is also a fact. You can't deny that our project is meaningless because you think that the registered capital of our software R&D team is small。

**Comment by neogeweb3** [comment]
From where you interpreted it that I believe your project is meaningless? I was trying to help you disclose more information to the public or a small group of notaries through NDA so you become a trustworthy client. Nothing more.

**Comment by litai686** [comment]
@neogeweb3 Thanks, I see , I have found a notary  @Joss-Hua ,  He has a good understanding of my project ,  I am trying to find a second notary,  but I released it on Slack and nobody paid attention to it.

**Comment by Sunnyiscoming** [comment]
Hey @litai686, I am not a notary. If you still want to apply for datacap, you can ask notaries to do client due diligence in slack channel. https://app.slack.com/client/TEHTVS1L6/C036JKD8NVA/thread/C03BG1MNQ4T-1673888660.823499

**Comment by litai686** [comment]
@Sunnyiscoming OK, Thanks!

**Comment by stcouldlisa** [comment]
@litai686  How do you prove that you have 5PiB of data?

How do you prove that you have the ownership of the cloud storage platform, you can store your data on the cloud to FIL+ (FIL+ is a public data set)

**Comment by litai686** [comment]
@stcouldlisa https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/521#issuecomment-1239062664 ,  look this link,Please! I introduced in detail how we combined the traditional scenic spot photography industry with the Filecoin network.

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Can you fill out [this form](https://form.jotform.com/230337462961356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!

**Comment by litai686** [comment]
wait
