### ISSUE TITLE
Global Computer Systems Large Dataset Application

### ISSUE THREAD

**Issue by Kormakornchip** [filecoin-project/filecoin-plus-large-datasets#522]
# Large Dataset Notary Application
To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Global Computer Systems
- Website / Social Media: global-usa.com
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5 PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100 TiB
- On-chain address for first allocation: f1x6mm2pyacdb3xwgzlf33koygp3ktqv5brk6yjna

## Project details
Share a brief history of your project and organization
```
Founded in 1996, we are a managed service provider. We are exploring ways to process archival data for our clients. Services we provide include backup administration, managed backups, disaster recovery, cloud migration and much more.
```

What is the primary source of funding for this project?
```
Internal
```

What other projects/ecosystem stakeholders is this project associated with?
```
None
```

## Use-case details
Describe the data being stored onto Filecoin
```
Backup data sets
```

Where was the data in this dataset sourced from?
```
Backup servers
```

Can you share a sample of the data? A link to file would work.
```
I can make it available for review but would want to maintain confidentiality
```

Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
No, this dataset has to be encrypted
```

What is the expected retrieval frequency for this data?
```
Once every 9 months
```

For how long do you plan to keep this dataset stored on Filecoin?
```
18 months minimum
```

## DataCap allocation plan
In which geographies (countries, regions) do you plan on making storage deals?
```
We would like to retain our data within the United States
- Region United States
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Online and offline
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We are planning to choose reputable storage providers in the community with upstanding no-fault rates and that are in the United States. We are open to inquiring storage providers but must understand that we would only like to store with mature storage providers. 
```

How will you be distributing deals across storage providers?
```
We plan to send deals online over the internet
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?

```
Yes we have adequate resources. Will contact community if we need more support 
```

**Comment by Sunnyiscoming** [comment]
Hi, @Kormakornchip  As you said, this dataset is more suitable for the private enterprise data request pattern. 
 
As Deep mentioned filecoin-project/notary-governance#514, you will need to find notaries that can support your application since it includes private enterprise data. 
 
You will need to follow a process similar to filecoin-project/notary-governance#489.  This means: 
 
Find notaries that can support your application.  You can do this best in Slack, #fil-plus or #fil-plus-application-review 
Once you have them, make an issue in the Notary Governance repo, similar to filecoin-project/notary-governance#489, stating your plan and the notaries that can support your request

**Comment by Kormakornchip** [comment]
re opening for parity with the LDN application

**Comment by laudiacay** [comment]
Supported! :)

**Comment by Alex11801** [comment]
I will support this project if the data is well encrypted ahead of onboarding.

**Comment by GaryGJG** [comment]
For a valuable and reasonable project, even though the data is encrypted we should support.

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 100TiB

**Client address**

>f1x6mm2pyacdb3xwgzlf33koygp3ktqv5brk6yjna

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 100TiB

**Client address**

>f1x6mm2pyacdb3xwgzlf33koygp3ktqv5brk6yjna

**Comment by flyworker** [comment]
This is a good user case for computing. want to support it.

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 100TiB

**Client address**

> f1x6mm2pyacdb3xwgzlf33koygp3ktqv5brk6yjna

**Comment by IreneYoung** [comment]
Seems like a valuable project, I'll support it.

**Comment by IreneYoung** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec22z2ipqzcqrlxqlbzuhzi3mxskayxbcmf532blg2auv7p5da47k 
#### Address 
> f1x6mm2pyacdb3xwgzlf33koygp3ktqv5brk6yjna
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1d4gmpqz3execjj2wvrxuuhvbms5mzh7t7yqrviq
#### Id
> 304b3576-fb02-4d2e-8c3e-33ae768d254c
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec22z2ipqzcqrlxqlbzuhzi3mxskayxbcmf532blg2auv7p5da47k

**Comment by xingjitansuo** [comment]
Nice to see different project onboarding to the network. I would love to support this one and approve the first tranche.

**Comment by xingjitansuo** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebytokzgsbkh7g7urf2ms3lmkbe4rkssh6dsqz3kekub2oeug2hta 
#### Address 
> f1x6mm2pyacdb3xwgzlf33koygp3ktqv5brk6yjna
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1a2lia2cwwekeubwo4nppt4v4vebxs2frozarz3q
#### Id
> 304b3576-fb02-4d2e-8c3e-33ae768d254c
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebytokzgsbkh7g7urf2ms3lmkbe4rkssh6dsqz3kekub2oeug2hta

**Comment by Kormakornchip** [comment]
Hello, 
I have made an amateur mistake. I am very sorry about this. The filecoin address I have provided for this is an address protected by a ledger hardware wallet. As a result the it requires manual approval for sending every sector :( . I have been guided to speak to  Raghav or Simon on the filecoin + governance team to resolve this. 

Would it be possible to change the address to the following address f1bj74ooe7oxupmss7hrygou3avogfqmgoag4nw6i ?

Again, I am sorry for the extra work I am causing. 

Alan

**Comment by brossetti1** [comment]
hey @Kormakornchip just want to double check on this last comment. You should be able to edit the wallet address at the top of the application [here](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/522#issue-1315280957) to update your wallet

**Comment by Sunnyiscoming** [comment]
Hello, @Kormakornchip per the https://github.com/filecoin-project/notary-governance/issues/922 for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

This information will be reviewed by Fil+ Governance team to confirm validity and then the application will be allowed to move forward for additional notary review.
