### ISSUE TITLE
[DataCap Application]Wyndham Grand Qingdao

### ISSUE THREAD

**Issue by carryxiao** [filecoin-project/filecoin-plus-large-datasets#525]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Wyndham Grand Qingdao
- Website / Social Media:https://www.wyndhamhotels.com/wyndham-grand/qingdao-china/wyndham-grand-qingdao/overview
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 3.5PIB
- Weekly allocation of DataCap requested (usually between 1-100TiB):100TIB
- On-chain address for first allocation:f1zzza4pff35r5knggzdmmpeyfqf5xffoz2lynsyi 

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Wyndham Grand Qingdao Silver Beach is strategically located on the charming Silver Beach about 30 minutes' drive south of Qingdao. The hotel has an elegant environment, luxurious and exquisite facilities, stylish decoration and comprehensive and thoughtful service.

The hotel has one of the largest convention and exhibition centers in mainland China, with more than 12,800 square meters of flexible event space.

The hotel is located on the beautiful silver sand beach, with thoughtful service and complete facilities, it is an ideal choice for business, leisure and conference guests.
```

What is the primary source of funding for this project?
```
We are fully funded
```

What other projects/ecosystem stakeholders is this project associated with?
```
No one
```

## Use-case details

Describe the data being stored onto Filecoin
```
We have cameras in many public areas,  we hope the Filecoin network will help us back up some of our data
```

Where was the data in this dataset sourced from?
```
The data comes from the data generated by our hotel, such as data captured by cameras, pictures captured by mobile phones, etc.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://drive.google.com/drive/folders/10-FGuI5I7AmsDBS5pqrWkMbOCN-hCoMq
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes, we confirm
```

What is the expected retrieval frequency for this data?
```
We expect to retrieval twice a year
```

For how long do you plan to keep this dataset stored on Filecoin?
```
If possible, I would like to implement permanent storage
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
We will consider miners in China, Asia, Europe and other regions. We hope that the storage provider is stable and secure, so we give priority to miners with strong technology.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Our data is mainly video and picture. We mainly consider offline transmission, but offline transmission is more troublesome. Therefore, we will decide the transmission method according to the country where the miner we cooperate with is located.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
Our hotel data does not require frequent retrieval, but we will determine with storage providers whether they have relevant retrieval capabilities, and we will consider storage providers that can cooperate with our retrieval.
```

How will you be distributing deals across storage providers?
```
Fair and just distribution. If the data can be approved, we plan to let a colleague be responsible for related matters, including the negotiation and cooperation of storage providers, data distribution, etc. We will definitely abide by the rules of FIL+.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, I do. We are very well-funded and well-prepared.
```

**Comment by Sunnyiscoming** [comment]
Could you send an email to filplus-app-review@fil.org with your official domain(wyndhamhotels.com) in order to confirm your identity?
Email name should includes the issue id #525.

**Comment by raghavrmadya** [comment]
@carryxiao , please provide answers by next Friday to keep this application active.

Thanks. Also please send an email stating you have applied for LDN using an official email plus a business license to filplus-app-review@fil.org

Thanks.

**Comment by asdweds** [comment]
> 1.Can you provide more detailed information about storage providers distribution, such as you can list SPs you have contacted with at present? 2.Could you send an email to [filplus-app-review@fil.org](mailto:filplus-app-review@fil.org) with your official domain(wyndhamhotels.com) in order to confirm your identity? Email name should includes the issue id #525.

![bc0fdb33834c6f4c750ef2f2696ea1a](https://user-images.githubusercontent.com/109947679/186064348-b7b75270-6122-4635-b743-01347aebb3db.jpg)
Hello, we have sent the email to your mailbox last week, please check it.
We're sorry that our colleague carryxiao has left, so we didn't get back to you in time.
The departure of employees does not affect Wyndham Grand Qingdao's application to participate in FIL+.

**Comment by asdweds** [comment]
> 1.Can you provide more detailed information about storage providers distribution, such as you can list SPs you have contacted with at present? 2.Could you send an email to [filplus-app-review@fil.org](mailto:filplus-app-review@fil.org) with your official domain(wyndhamhotels.com) in order to confirm your identity? Email name should includes the issue id #525.

@Sunnyiscoming @raghavrmadya 
![bc0fdb33834c6f4c750ef2f2696ea1a](https://user-images.githubusercontent.com/109947679/186064574-37823efa-ac63-42c5-9e94-026574725fb2.jpg)
Hello, we have sent the email to your mailbox last week, please check it.
We're sorry that our colleague carryxiao has left, so we didn't get back to you in time.
The departure of employees does not affect Wyndham Grand Qingdao's application to participate in FIL+.

**Comment by treecdapou** [comment]
> 1.Can you provide more detailed information about storage providers distribution, such as you can list SPs you have contacted with at present? 2.Could you send an email to [filplus-app-review@fil.org](mailto:filplus-app-review@fil.org) with your official domain(wyndhamhotels.com) in order to confirm your identity? Email name should includes the issue id #525.

@raghavrmadya @Sunnyiscoming 

![396333e868ac1a0c0c1687e192f4ab6](https://user-images.githubusercontent.com/109773105/186554826-f3e56703-a8b6-4ebc-973c-40f548747a02.jpg)

Hello, we have sent the email to your mailbox last week, please check it.
We're sorry that our colleague carryxiao has left, so we didn't get back to you in time.
The departure of employees does not affect Wyndham Grand Qingdao's application to participate in FIL+.

**Comment by jessie8o8** [comment]
Hello! How can we trust that your email domain is actually affiliated with the company?

In the site of the original LDN, the domain is @wyndham.com
![image](https://user-images.githubusercontent.com/90115194/186556779-cc031cf9-0f4a-4e61-9f84-66131830cd24.png)

In the site in the email snippet, the domain is @wyndhamhotelschina.com
![image](https://user-images.githubusercontent.com/90115194/186556703-aa3ec397-f53b-451b-ab28-1e3cd91abedc.png)

The domain the email came from is @wyndhamgrandqdw.com.cn. Could you point where that is mentioned in the official sites?

**Comment by treecdapou** [comment]
Hello, we are Wyndham Grand Qingdao Silver Beach, not the headquarters of Wyndham Group, so our domain name mailbox is the domain name mailbox of Wyndham Grand Qingdao Silver Beach. Please take a look at our application form. The theme of our application is Wyndham Grand Qingdao Silver Beach, not Wyndham Group. Wyndham has a lot of hotels around the world. We are from Qingdao. We only Apply for LDN on behalf of our Wyndham Grand Qingdao Silver Beach Hotel.

**Comment by raghavrmadya** [comment]
The kind of data you mention does not seem public. Please clarify. Also share details about how many copies will you store and SP distribution.

**Comment by treecdapou** [comment]
> The kind of data you mention does not seem public. Please clarify. Also share details about how many copies will you store and SP distribution.

Yes, those can be treated as public data.As per the sample data,  some are promotional pics & videos flimed by our advertising team, some are uploaded to our social media platform by clients. And we are planning to store 2 to 3 copies depending
on the datacap we getting. For now we contacted some of the SPs including f01474838, f01611281, f01509552, f01914699,
and we are still engaging with more SPs, we hope finally 4 or more SPs will be involved in this data storage.

**Comment by Sunnyiscoming** [comment]
Videos produced from cameras in many public areas may not be public. But this type of data is exactly what you want to store.

> We have cameras in many public areas,  we hope the Filecoin network will help us back up some of our data

**Comment by treecdapou** [comment]
> Videos produced from cameras in many public areas may not be public. But this type of data is exactly what you want to store.
> 
> > We have cameras in many public areas,  we hope the Filecoin network will help us back up some of our data

Hi @Sunnyiscoming , sorry for the previous expression that misleading you. We are not trying to store surveillance videos or any similar kind . As i replied to raghavrmadya, we are trying to store promotional pics & videos, and videos from our social media platform which are confirmed 100% public.

**Comment by Sunnyiscoming** [comment]
Can you explain the number of backups you will store, and what constitutes 3.5 pb data? In general, your promotional pictures and videos don't have much data.

**Comment by treecdapou** [comment]
> Can you explain the number of backups you will store, and what constitutes 3.5 pb data? In general, your promotional pictures and videos don't have much data.

hi @Sunnyiscoming 
high resolution raw data takes too much space, especially we have upgraded our video devices with 4k video capability since last year.

during the last 7 years we have around 660T of 1080P raw video materials, 
260T of 4k raw video materials, 140T of final videos with different resolution (for uploading purpose),15T of raw & final pictures, 

90T of client uploaded contents. The data is still increasing and all data are stored in our server room for now.

we are planning to make 2 to 3 copies in the filecoin network.

**Comment by Sunnyiscoming** [comment]
Can you provide more evidence that you currently have so many promotional videos.

> during the last 7 years we have around 660T of 1080P raw video materials,
> 260T of 4k raw video materials, 140T of final videos with different resolution (for uploading purpose),15T of raw & final pictures,
> 90T of client uploaded contents. (Have you authorized to store them onto Filecoin?)

**Comment by Sunnyiscoming** [comment]
Any update here?

**Comment by treecdapou** [comment]
Yes, we have uploaded more sample data for your checking. https://drive.google.com/drive/folders/1yYXRyJ8rBY56EIptwQrPsS-O9DMs8Loc?usp=sharing

**Comment by raghavrmadya** [comment]
Hi, you mention that in the application that data source as - 
"We have cameras in many public areas,  we hope the Filecoin network will help us back up some of our data" but above you say it's promotional videos. Can you clarify?

**Comment by treecdapou** [comment]
Sure, as i explained earlier, our expression not quite accurate, in fact we would like to store media contents,
    more specifically promotional contents. Most of our storage space are occupied to media contents, including survilliance videos
    and promotional contents, however survilliance videos are too private and sensitive that we won't expose. Kindly 
    let us know if anything else need to clarify.

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 3.5PiB

**Expected weekly DataCap usage rate**

> 100TiB

**Client address**

>f1zzza4pff35r5knggzdmmpeyfqf5xffoz2lynsyi

**Comment by Sunnyiscoming** [comment]
Hey @carryxiao , if you still want to apply for datacap, you can ask notaries to do client due diligence in slack channel. https://app.slack.com/client/TEHTVS1L6/C036JKD8NVA/thread/C03BG1MNQ4T-1673888660.823499

**Comment by stcouldlisa** [comment]
Wyndham Grand Hotel is a very well-known hotel with branches all over the world.
Who are you representing? Wyndham Grand Qingdao Hotel or Wyndham Grand Group.
how do you prove your identity
