### ISSUE TITLE
[DataCap Application]  Shenzhen Aprocloud Technology Co., Ltd

### ISSUE THREAD

**Issue by leon-le** [filecoin-project/filecoin-plus-large-datasets#527]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Shenzhen Aprocloud Technology Co., Ltd
- Website / Social Media:http://www.aprocloud.cn/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):200TiB
- On-chain address for first allocation:f1o7erevu55tzgoxsv2lpvay244oee2mif2ujcr6y

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Shenzhen Aprocloud Technology Co., Ltd was established in 2017 and has been established for 5 years. It is a world-leading Professional Computer Unit solution provider. In the field of cloud computing and big data, we provide customers with professional OEM/ODM services, provide system-level product design and development, production and manufacturing integrated solutions, and provide customers with customized cloud computing and big data server products.

Aprocloud company has more than 150 people, has sales department, design department, production department, installation and after-sales department and other departments, and has a production workshop of 1100 square meters in Longgang District, Shenzhen.
```

What is the primary source of funding for this project?
```
Our company is highly profitable and has its own funds.
```

What other projects/ecosystem stakeholders is this project associated with?
```
No one
```

## Use-case details

Describe the data being stored onto Filecoin
```
product design data
Factory production data
Quality inspection data
Aftermarket Shipping Data
```

Where was the data in this dataset sourced from?
```
It comes from the data generated by the company since its establishment five years ago, such as product design data, production data on the factory floor, and storage data stored by the company on Alibaba Cloud.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://drive.google.com/drive/folders/1H8R4B2ymHDP8acjk9-MoFMmor61kIDu4?usp=sharing
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
we confirm
```

What is the expected retrieval frequency for this data?
```
Generally speaking, our data does not need to be retrieved. I think maybe once a year.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
I think the data should be stored for at least 1-2 years.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
We want to be able to store globally
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Both online and offline
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We think that all SPs that want to store real data should be eligible to store FIL+ data, but they must ensure the stability and security of the storage.
```

How will you be distributing deals across storage providers?
```
No more than 25% per storage provider, we hope the more SP storage the better.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, I do
```

**Comment by leon-le** [comment]
sorry

**Comment by Sunnyiscoming** [comment]
1.Can you share more data samples related with product design data, factory production data, quality inspection data, aftermarket shipping Data?
2.Can you provide more detailed information about storage providers distribution, such as you can list SPs you have contacted with at present?

**Comment by raghavrmadya** [comment]
@leon-le , please provide answers by next Friday to keep this application active. 

Thanks. Also please send an email stating you have applied for LDN using an official email plus a business license to filplus-app-review@fil.org

Thanks.

**Comment by leon-le** [comment]
Hello, we have been established for a long time and have generated a lot of data. Now we add the following data:

https://drive.google.com/drive/folders/1HPDUEWANI0Qrin3TzAZiiMlQd_8dnaGD

test tools
Technical Support
Conference training materials
Design draft of product model
Instruction Manual
Test data for factory production machines
Different types of test data 

We will find SPs on Filecoin slack, BigDexchange. At present, we have contacted some SPs in Europe, Vietnam and Greater China. At the same time, we are still actively looking for more high-quality SPs. We promise that we will abide by the rules of FIL+, and the storage of a single SP does not exceed 25%.

In addition, our mail has been sent, and the business license is attached.

**Comment by leon-le** [comment]
![Uploading b3ce96c3b41cbe61dffb1e224b75b8c.jpg…]()

**Comment by leon-le** [comment]
![b3ce96c3b41cbe61dffb1e224b75b8c](https://user-images.githubusercontent.com/37136708/186101741-14812a85-d25a-447d-a87c-d59ca09dbf19.jpg)

**Comment by Sunnyiscoming** [comment]
Before proceeding, what is the amount of data you have today and how many copies do you plan to store? 
Can you list sps nodes here?

**Comment by raghavrmadya** [comment]
Hi, so as a governance team we are not blocking this but it will be good to declare if you are the SP working on behalf of the client. If you are an SP applying for DataCap, that might be problematic. Please clarify.

**Comment by raghavrmadya** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 200TiB

**Client address**

>f1o7erevu55tzgoxsv2lpvay244oee2mif2ujcr6y

**Comment by raghavrmadya** [comment]
Notaries, please take look at the note above

**Comment by stcouldlisa** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecfkcayc2cuqvyi7cak2yc5rwhbqzumxoekfr5cifub5a4pbijqwi 
#### Address 
> f1o7erevu55tzgoxsv2lpvay244oee2mif2ujcr6y
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1jvvltduw35u6inn5tr4nfualyd42bh3vjtylgci
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecfkcayc2cuqvyi7cak2yc5rwhbqzumxoekfr5cifub5a4pbijqwi

**Comment by Defil2022** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced6z3gy5xn4i3ve52izb7r2lleshuuhx3xzuo6nc2f7ztcdjdmarc 
#### Address 
> f1o7erevu55tzgoxsv2lpvay244oee2mif2ujcr6y
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1dnb3uz7sylxk6emti3ififcvu3nlufnnsjui6ea
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced6z3gy5xn4i3ve52izb7r2lleshuuhx3xzuo6nc2f7ztcdjdmarc

**Comment by BigD-Exchange** [comment]
@leon-le Hi! Great to see you have gotten approval for DataCap. If you are looking for more storage providers to store these data or have any questions, please visit #bigdata-exchange on Filecoin Slack or reply here. 

We have strong demand from a diverse group of SPs, who are actively looking to onboard more data.

**Comment by Tom-OriginStorage** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceazx6lbj7t2uxkimhtbgdm4hxb74w55q2q25gyepavxrz7m3jyjxk 
#### Address 
> f1o7erevu55tzgoxsv2lpvay244oee2mif2ujcr6y
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1q6bpjlqia6iemqbrdaxr2uehrhpvoju3qh4lpga
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceazx6lbj7t2uxkimhtbgdm4hxb74w55q2q25gyepavxrz7m3jyjxk

**Comment by kernelogic** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecb4dd5vqlccy7lnxjcarflvyloc34zmsbri4p7icm4csqhrwxgys 
#### Address 
> f1o7erevu55tzgoxsv2lpvay244oee2mif2ujcr6y
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecb4dd5vqlccy7lnxjcarflvyloc34zmsbri4p7icm4csqhrwxgys

**Comment by filplus-checker** [comment]
## DataCap and CID Checker Report[^1]
 - Organization: `Shenzhen Aprocloud Technology Co., Ltd`
 - Client: `f1o7erevu55tzgoxsv2lpvay244oee2mif2ujcr6y`
### Storage Provider Distribution
The below table shows the distribution of storage providers that have stored data for this client.

If this is the first time a provider takes verified deal, it will be marked as `new`.

For most of the datacap application, below restrictions should apply.
 - Storage provider should not exceed 25% of total datacap.
 - Storage provider should not be storing duplicate data for more than 20%.
 - Storage provider should have published its public IP address.
 - All storage providers should be located in different regions.

✔️ Storage provider distribution looks healthy.

| Provider                                              |                          Location | Total Deals Sealed | Percentage | Unique Data | Duplicate Deals |
| :---------------------------------------------------- | --------------------------------: | -----------------: | ---------: | ----------: | --------------: |
| [f01900537](https://filfox.info/en/address/f01900537) | Ho Chi Minh City, Ho Chi Minh, VN |          25.13 TiB |     20.00% |   25.03 TiB |           0.37% |
| [f01900722](https://filfox.info/en/address/f01900722) |       Los Angeles, California, US |          25.13 TiB |     20.00% |   25.03 TiB |           0.37% |
| [f01900787](https://filfox.info/en/address/f01900787) |          Singapore, Singapore, SG |          25.13 TiB |     20.00% |   25.03 TiB |           0.37% |
| [f01914991](https://filfox.info/en/address/f01914991) |  Aubervilliers, Île-de-France, FR |          25.13 TiB |     20.00% |   25.03 TiB |           0.37% |
| [f01915309](https://filfox.info/en/address/f01915309) |              Toronto, Ontario, CA |          25.13 TiB |     20.00% |   25.03 TiB |           0.37% |

![Provider Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/527/1671097360530.png)
### Deal Data Replication
The below table shows how each many unique data are replicated across storage providers.
- No more than 25% of unique data are stored with less than 4 providers.

✔️ Data replication looks healthy.

| Unique Data Size | Total Deals Made | Number of Providers | Deal Percentage |
| ---------------: | ---------------: | ------------------: | --------------: |
|        25.03 TiB |       125.63 TiB |                   5 |         100.00% |

![Replication Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/527/1671097361158.png)
### Deal Data Shared with other Clients
The below table shows how many unique data are shared with other clients.
Usually different applications owns different data and should not resolve to the same CID.

✔️ No CID sharing has been observed.

[^1]: To manually trigger this report, add a comment with text `checker:manualTrigger`

**Comment by herrehesse** [comment]
@leon-le applicant,

The observed distribution, duplication and reuse of CIDs looks excellent. However, it would seem that a VPN was used to appear at the locations in question. Since each location falls under the same cloud company. https://www.constant.com/

Would like full transparency and clarity before proceeding with data cap. 

To add further,, my request and advice is to use for the FIL-E program and not the Filecoin+ program given the relevant nature of the business content namely:

- Product design data
- Factory production data
- Quality inspection data
- Aftermarket Shipping Data

This does not belong under an LDN for the Filecoin+ program.

**Comment by cryptowhizzard** [comment]
Feb 17 15:38:52 proposals dealscanner-f01917209-f01914991: Recv 0 B, Paid 0 FIL, ProviderCancelled (Cancelling), 556ms [1676639687043917252|0]
Feb 17 15:38:52 proposals dealscanner-f01917209-f01914991: Recv 0 B, Paid 0 FIL, DealAccepted (Accepted), 554ms [1676639687043917253|0]
Feb 17 15:38:52 proposals dealscanner-f01917209-f01914991: Recv 0 B, Paid 0 FIL, PaymentChannelSkip (Ongoing), 555ms [1676639687043917253|0]
Feb 17 15:38:52 proposals dealscanner-f01917209-f01914991: Recv 0 B, Paid 0 FIL, ProviderCancelled (Cancelling), 556ms [1676639687043917253|0]
Feb 17 15:38:52 proposals dealscanner-f01917209-f01914991: Recv 0 B, Paid 0 FIL, CancelComplete (Cancelled), 558ms [1676639687043917252|0]
Feb 17 15:38:52 proposals dealscanner-f01917209-f01914991: ERROR: Retrieval Proposal Cancelled: Provider cancelled retrieval
Feb 17 15:38:52 proposals dealscanner-f01917209-f01914991: 
Feb 17 15:38:52 proposals dealscanner-f01917209-f01914991: Recv 0 B, Paid 0 FIL, CancelComplete (Cancelled), 556ms [1676639687043917253|0]
Feb 17 15:38:52 proposals dealscanner-f01917209-f01914991: ERROR: Retrieval Proposal Cancelled: Provider cancelled retrieval
Feb 17 15:38:52 proposals dealscanner-f01917209-f01914991:

**Comment by cryptowhizzard** [comment]
Can you let us know when you will have retrieval working?
