### ISSUE TITLE
[DataCap Application] <Shenzhen WenYiduo Creative Culture Communication Co., Ltd>

### ISSUE THREAD

**Issue by wenyiduomedia** [filecoin-project/filecoin-plus-large-datasets#528]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Shenzhen WenYiduo Creative Culture Communication Co., Ltd
- Website / Social Media:https://m.6pian.cn/12705
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 400TiB
- On-chain address for first allocation:f15m6qoqdsh7fn7l5amegshhvwi4gl5alb2eeuz2y

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
There are also many people who focus on enterprise video customization projects, and enter the industry with innovative vertical field integrated video service mode and open group enterprise cooperation mode. As a practitioner of aesthetics, Wen Yiduo always takes responsibility for the overall image of customers as the premise in video products, adheres to the responsibility for the aesthetics of product style, adheres to the uncompromising to the bad, and adheres to the professional concept of content service design and production.
Based in Shenzhen
The market operation Department of the company is located at 2809a, phase I, Zhuoyue Times Square, No. 4068, Yitian Road, Futian District, Shenzhen. The technical support and post production team is located in Liaobu, Dongguan. Based on Pengcheng, we should respond to the market with the fastest response speed in the face of market demand differentiation and customization.
Global radiation
With years of industry resource accumulation, the business is global, and has a strong supply chain network at home and abroad, including Hong Kong, Macao, Hangzhou, Changsha, Chongqing, Wuhan, as well as Japan, South Korea, Cambodia, Thailand, Malaysia, the United Arab Emirates and other countries and regions
Solve the customization demand of enterprise video publicity planning
Planning and production of large-scale TV programs and activities, enterprise promotional films, documentaries, short video operation and production, tvc advertising, live broadcasting of large-scale events, and global cross regional live broadcasting connections. By using their own team's professional technical strength, they can solve various video customization needs for enterprises.
```

What is the primary source of funding for this project?
```
ourselves.
```

What other projects/ecosystem stakeholders is this project associated with?
```
ourselves.
```

## Use-case details

Describe the data being stored onto Filecoin
```
We shoot and produce various commercial videos.
```

Where was the data in this dataset sourced from?
```
Enterprise promotional film
Special documentary
Short video operation and production
Planning of large-scale TV activities
TV program naming and sponsorship
Large cross regional live broadcast.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://www.6pian.cn/xuanchuan/40066.html
https://www.6pian.cn/xuanchuan/40058.html
https://www.6pian.cn/xuanchuan/40061.html
https://www.6pian.cn/guanggao/44771.html
https://www.6pian.cn/xuanchuan/54897.html

【尊敬的超级会员V6】我通过百度网盘分享的文件：奥拓CV智慧一体....mp4等5个文件
链接：https://pan.baidu.com/s/1fpAIviyFUMEgrCOxPsHtFQ 
提取码：6666 
复制这段内容打开「百度网盘APP即可获取」

【尊敬的超级会员V6】我通过百度网盘分享的文件：达美康.mp4等4个文件
链接：https://pan.baidu.com/s/1GAcbNW9tw3NqjFOdLv-Pkg 
提取码：6666 
复制这段内容打开「百度网盘APP即可获取」
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes, everyone can search it.
```

What is the expected retrieval frequency for this data?
```
Twice a year
```

For how long do you plan to keep this dataset stored on Filecoin?
```
More than five years
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Asia.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Offline transmission
Our bandwidth is very small, with a downlink bandwidth of 500Mb and an uplink bandwidth of 50Mb.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
I hope each data is divided into at least seven parts, or even more scattered.
Our requirements for selecting storage service providers:
1. The distribution area shall be as scattered as possible
2. The company operates normally and has no illegal behaviors, so there will be no legal risks
3. Support fast retrieval
```

How will you be distributing deals across storage providers?
```
Offline transmission
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
yes
```

**Comment by Sunnyiscoming** [comment]
It seems that you have no website built by yourself. Could you send an email to filplus-app-review@fil.org with your business license and the applicant's identification documents in order to confirm your identity?
Email name should includes the issue id #528.

**Comment by wenyiduomedia** [comment]
Hi @Sunnyiscoming 
1.Our source data is 900T, and we plan to find 5 SPS.
****2 / 5** replicas**: because our company is located in Shenzhen, we plan to find two SPS in Guangdong Province to store two replicas. Currently, the nodes being communicated are: f0822441, etc
****2 / 5** replica**: we hope to find two SPS in different provinces for storage.It is planned to be found through BDE platform
****1 / 5** replica**: we plan to store the SP in Hong Kong. At present, there is an intended SP, which is under communication.

2. We will send verification email later

**Comment by Sunnyiscoming** [comment]
https://filrep.io/?search=f0822441
This sp seems to be reacheable. These SPs should provide data retrieval.

**Comment by wenyiduomedia** [comment]
I'm sorry, I think what I said has caused you to misunderstand. @Sunnyiscoming 
We are contacting this sp (822441) and they will use a new miner node to store a copy. This new node will open the retrieval function.
It is not based on 822441 to continue to store replicas

**Comment by wenyiduomedia** [comment]
Hi @Sunnyiscoming 
I just sent a verification email
It contains:
1. Enterprise business license
2. Enterprise ID card information
3. Certificate with official seal of the enterprise
<img width="808" alt="image" src="https://user-images.githubusercontent.com/110023498/185286039-50b2825a-ea2a-4597-8ace-ad4b4b3ef83e.png">

**Comment by wenyiduomedia** [comment]
@Sunnyiscoming  Are there any updates here?

**Comment by wenyiduomedia** [comment]
@Sunnyiscoming  @raghavrmadya We just want to ask
Is there any progress here?

**Comment by raghavrmadya** [comment]
We need more information on SP distribution. Your applications they will all be in China which is not aligned with program rules.

**Comment by wenyiduomedia** [comment]
Hi @raghavrmadya 
Our source data is 900T, and we plan to find 5 SPS.

There are 3 SPS we are contacting.
One is in Shenzhen, China, one is in Hong Kong, China, and the other is in Chengdu, China.
f066104 f01136409 f01611281  f0822441（Still in communication, not the final storage node）
And we are also communicating with some technical service miners, including **Great heart.**
We will also try to use **BDE** or **slack** platform to find some SPS outside China

_**I changed the storage target area from "China" to "Asia"**_

**Comment by wenyiduomedia** [comment]
It is worth mentioning that
I have observed that the storage area of some LDN applications previously applied for is also China or a specific country.
As far as I know, this method was allowed before. Because of national policies, some data can only be stored in specific areas.
But now it's not allowed. What did I miss? Or did I not notice that the latest rules of LDN have changed? @raghavrmadya 

https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/426
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/406
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/402
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/400
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/385
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/363
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/346
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/337

**Comment by wenyiduomedia** [comment]
Dear sir and madam, @raghavrmadya @Sunnyiscoming 

Is there any latest progress here?

**Comment by raghavrmadya** [comment]
Please come to the next gov call to present your case. We have very low confidence in your application. You can also try to find notary support in the slack channel to gain trust. Thanks

**Comment by wenyiduomedia** [comment]
Hi@raghavrmadya 
The core of the blockchain should be to remove the center.
Instead of being more central than the center as it is now. Power is entirely in the hands of one person.
Filplus's audit mechanism now looks like shit
I think this way is very unfriendly,
Your auditing standards are totally different for Chinese companies and foreign companies.

**First:**
1. Our company has been established for nearly 6 years and is operating normally
2. We have submitted more than 10 data samples. If you want more samples, we can provide them
3. During KYC's review, we submitted the business license, ID card of enterprise legal person and enterprise authorization.
We have done so much together. You told me that you have insufficient confidence in us,

Now I want to ask you,
Is it your personal lack of confidence in us, or filecoin? Do you reply on behalf of yourself or filecoin?
Where does your conclusion come from?
What else do you need from us to be confident?
If you represent the filecoin organization, why does filecoin adopt this one vote veto system?
You can refuse me, but you can't tease me,
What puzzles me is that I have done better than most people who have passed. You still don't trust me.
I think there is discrimination here.
The above thoughts are on my own behalf

——————————
Our company will sign up for the next governance meeting. We will clarify where our data comes from and what our business is like?
Thank you for your reply, have nice day

**Comment by wenyiduomedia** [comment]
Hi @raghavrmadya 
The core of the blockchain should be to remove the center.
Instead of being more central than the center as it is now. Power is entirely in the hands of one person.
Filplus's audit mechanism now looks like shit
I think this way is very unfriendly,
Your auditing standards are totally different for Chinese companies and foreign companies.

First:
> 
> 1. Our company has been established for nearly 6 years and is operating normally
> 2. We have submitted more than 10 data samples. If you want more samples, we can provide them
> 3. During KYC's review, we submitted the business license, ID card of enterprise legal person and enterprise authorization.

We have done so much together. You told me that you have insufficient confidence in us,
Now I want to ask you,
Is it your personal lack of confidence in us, or filecoin? Do you reply on behalf of yourself or filecoin?
Where does your conclusion come from?
What else do you need from us to be confident?
If you represent the filecoin organization, why does filecoin adopt this one vote veto system?
You can refuse me, but you can't tease me,
What puzzles me is that I have done better than most people who have passed. You still don't trust me.
I think there is discrimination here.
The above thoughts are on my own behalf

——————————
Our company will sign up for the next governance meeting. We will clarify where our data comes from and what our business is like?
We do suggest you and your team have a translator while you review these LDN from Chinese company.
Thank you for your reply, have nice day

**Comment by raghavrmadya** [comment]
@wenyiduomedia Thank you for expressing your concern. The governance calls are one of the most decentralized aspect of the program. Power is not in the hands of one person. There are more than 1700 community members in the fil-plus channel, more than 50 notaries and 4 different gov team members as mentioned in the gov calls. Filplus audit mechanism relies on the community and given that the instances of fraud are way higher from certain regions, we need to be careful when giving out DataCap.  If you think there is unfairness in the system, please open a discussion topic in the notary governance repo. 

I represent the governance team, not me, not Filecoin. My conclusion comes from seeing more than 100 applications every day, seeing fraud trends, and engaging with clients and SPs working hard to onboard data onto the network. Everything I say can be verified in the open issues. 

We have enough translation support to assess applications. I don't think that is the reason why applications take time but rather because they don't provide sufficient information upfront.

**Comment by wenyiduomedia** [comment]
Hello, sir @raghavrmadya 
Are there any recent developments here?
These materials are for your reference and inspection


https://filecoinproject.slack.com/archives/C036JKD8NVA/p1662387224450579
**_Demo video_**
https://drive.google.com/file/d/1p6RbLdegH8gHsEXxUGkUOgm3-4Y79O0P/view?usp=sharing

**Comment by wenyiduomedia** [comment]
Hello, sir @raghavrmadya  @Sunnyiscoming 
Are there any recent developments here?

**Comment by wenyiduomedia** [comment]
Sir ，We need your help @galen-mcandrew @raghavrmadya @Sunnyiscoming @Kevin-FF-USA ke @dkkapur 

It has been half a month since the presentation of the last governance meeting.
I want to know what our audit results are?

**Comment by raghavrmadya** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 400TiB

**Client address**

>f15m6qoqdsh7fn7l5amegshhvwi4gl5alb2eeuz2y

**Comment by raghavrmadya** [comment]
Pushing this as there haven't been any concerns raised by community members after the presentation at the governance call. Client is requested to share the presentation here and notaries are requested to conduct further due diligence

**Comment by wenyiduomedia** [comment]
Thanks

https://filecoinproject.slack.com/files/U04131Y97U3/F041FSHUWRF/_____________________2022___.pdf
https://drive.google.com/file/d/1p6RbLdegH8gHsEXxUGkUOgm3-4Y79O0P/view

**Comment by Tom-OriginStorage** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedti2zgtefssto5fbgvmejmatkfdnrrt7eke5fsbpylekfbeuiple 
#### Address 
> f15m6qoqdsh7fn7l5amegshhvwi4gl5alb2eeuz2y
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1q6bpjlqia6iemqbrdaxr2uehrhpvoju3qh4lpga
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedti2zgtefssto5fbgvmejmatkfdnrrt7eke5fsbpylekfbeuiple

**Comment by newwebgroup** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecjtwnh2n5tsn3wzi5povhkx5klgksy6b62vfhocdsvkjle2f6nr6 
#### Address 
> f15m6qoqdsh7fn7l5amegshhvwi4gl5alb2eeuz2y
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1e77zuityhvvw6u2t6tb5qlnsegy2s67qs4lbbbq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecjtwnh2n5tsn3wzi5povhkx5klgksy6b62vfhocdsvkjle2f6nr6

**Comment by newwebgroup** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedcg6twd6drcjhii7b252o4nxbk3jgl5v3b6ipadkc77ncqnbwg7e 
#### Address 
> f15m6qoqdsh7fn7l5amegshhvwi4gl5alb2eeuz2y
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1e77zuityhvvw6u2t6tb5qlnsegy2s67qs4lbbbq
#### Id
> 56e0b39e-c3e7-41ca-afc3-cb1285816062
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedcg6twd6drcjhii7b252o4nxbk3jgl5v3b6ipadkc77ncqnbwg7e

**Comment by 1ane-1** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedgrrinq6l75yxj33zzpqritb4qcneraqejng6vzdg3y5upc2ny7k 
#### Address 
> f15m6qoqdsh7fn7l5amegshhvwi4gl5alb2eeuz2y
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1mdk7s2vntzm6hu35yuo6vjubtrpfnb2awhgvrri
#### Id
> 56e0b39e-c3e7-41ca-afc3-cb1285816062
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedgrrinq6l75yxj33zzpqritb4qcneraqejng6vzdg3y5upc2ny7k

**Comment by kernelogic** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceblutmtf6vwmgib436oaqfa4m4hm64zjutiubho576xq3txzy46o4 
#### Address 
> f15m6qoqdsh7fn7l5amegshhvwi4gl5alb2eeuz2y
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### Id
> b34f934c-3fcc-44d8-9d37-632c52cda4f9
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceblutmtf6vwmgib436oaqfa4m4hm64zjutiubho576xq3txzy46o4

**Comment by stcouldlisa** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceamk32z66ypdbhbj6fofp7wenvfwi56ychmgpkzrs4pin5xmzitua 
#### Address 
> f15m6qoqdsh7fn7l5amegshhvwi4gl5alb2eeuz2y
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1jvvltduw35u6inn5tr4nfualyd42bh3vjtylgci
#### Id
> b34f934c-3fcc-44d8-9d37-632c52cda4f9
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceamk32z66ypdbhbj6fofp7wenvfwi56ychmgpkzrs4pin5xmzitua

**Comment by xingjitansuo** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceajx2kvnrqjp3uz26s2xevacslrgd4d22jbpmnybghra767677ll2 
#### Address 
> f15m6qoqdsh7fn7l5amegshhvwi4gl5alb2eeuz2y
#### Datacap Allocated
> 1.56PiB
#### Signer Address
> f1a2lia2cwwekeubwo4nppt4v4vebxs2frozarz3q
#### Id
> cdc9a299-e307-46c6-ba72-3d3e8458cac5
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceajx2kvnrqjp3uz26s2xevacslrgd4d22jbpmnybghra767677ll2

**Comment by newwebgroup** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebiiol33frr4v3pkte4ggelssac4uaae3ogmetujjdt7dhr3ynr5a 
#### Address 
> f15m6qoqdsh7fn7l5amegshhvwi4gl5alb2eeuz2y
#### Datacap Allocated
> 1.56PiB
#### Signer Address
> f1e77zuityhvvw6u2t6tb5qlnsegy2s67qs4lbbbq
#### Id
> cdc9a299-e307-46c6-ba72-3d3e8458cac5
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebiiol33frr4v3pkte4ggelssac4uaae3ogmetujjdt7dhr3ynr5a

**Comment by newwebgroup** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceadadq4dvu62g7f7mpjxulxoirejrj2ug3e72vrbuvj3akgsglz4g 
#### Address 
> f15m6qoqdsh7fn7l5amegshhvwi4gl5alb2eeuz2y
#### Datacap Allocated
> 2.07PiB
#### Signer Address
> f1e77zuityhvvw6u2t6tb5qlnsegy2s67qs4lbbbq
#### Id
> 21dfbaf9-e106-458a-87d7-a017633b04bf
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceadadq4dvu62g7f7mpjxulxoirejrj2ug3e72vrbuvj3akgsglz4g

**Comment by Tom-OriginStorage** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecvvwbk5o53ew5ryg5t3xrw3agnkxocfpranhfx5hehl2wn5jfaci 
#### Address 
> f15m6qoqdsh7fn7l5amegshhvwi4gl5alb2eeuz2y
#### Datacap Allocated
> 2.07PiB
#### Signer Address
> f1q6bpjlqia6iemqbrdaxr2uehrhpvoju3qh4lpga
#### Id
> 21dfbaf9-e106-458a-87d7-a017633b04bf
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecvvwbk5o53ew5ryg5t3xrw3agnkxocfpranhfx5hehl2wn5jfaci

**Comment by raghavrmadya** [comment]
Please provide retrieval samples before further proceeding

**Comment by filplus-checker** [comment]
## DataCap and CID Checker Report[^1]
 - Organization: `Worldkan`
 - Client: `f15m6qoqdsh7fn7l5amegshhvwi4gl5alb2eeuz2y`
### Storage Provider Distribution
The below table shows the distribution of storage providers that have stored data for this client.

If this is the first time a provider takes verified deal, it will be marked as `new`.

For most of the datacap application, below restrictions should apply.
 - Storage provider should not exceed 25% of total datacap.
 - Storage provider should not be storing duplicate data for more than 20%.
 - Storage provider should have published its public IP address.
 - All storage providers should be located in different regions.

⚠️ 68.82% of total deal sealed by [f0417848](https://filfox.info/en/address/f0417848) are duplicate data.

⚠️ 79.26% of total deal sealed by [f01967672](https://filfox.info/en/address/f01967672) are duplicate data.

⚠️ 65.39% of total deal sealed by [f01929568](https://filfox.info/en/address/f01929568) are duplicate data.

⚠️ 53.83% of total deal sealed by [f01970213](https://filfox.info/en/address/f01970213) are duplicate data.

⚠️ 28.45% of total deal sealed by [f01955186](https://filfox.info/en/address/f01955186) are duplicate data.

⚠️ 43.93% of total deal sealed by [f01944347](https://filfox.info/en/address/f01944347) are duplicate data.

⚠️ 65.59% of total deal sealed by [f01937995](https://filfox.info/en/address/f01937995) are duplicate data.

⚠️ 30.18% of total deal sealed by [f01972356](https://filfox.info/en/address/f01972356) are duplicate data.

⚠️ 28.09% of total deal sealed by [f01970674](https://filfox.info/en/address/f01970674) are duplicate data.

⚠️ 36.87% of total deal sealed by [f01412203](https://filfox.info/en/address/f01412203) are duplicate data.

| Provider                                                    |                           Location | Total Deals Sealed | Percentage | Unique Data | Duplicate Deals |
| :---------------------------------------------------------- | ---------------------------------: | -----------------: | ---------: | ----------: | --------------: |
| [f0417848](https://filfox.info/en/address/f0417848)`new`    | Hong Kong, Central and Western, HK |         400.23 TiB |     12.41% |  124.80 TiB |          68.82% |
| [f01967672](https://filfox.info/en/address/f01967672)`new`  | Hong Kong, Central and Western, HK |         382.06 TiB |     11.85% |   79.25 TiB |          79.26% |
| [f01929568](https://filfox.info/en/address/f01929568)       |           Stockholm, Stockholm, SE |         361.16 TiB |     11.20% |  125.00 TiB |          65.39% |
| [f01970213](https://filfox.info/en/address/f01970213)`new`  | Hong Kong, Central and Western, HK |         338.34 TiB |     10.50% |  156.22 TiB |          53.83% |
| [f01928520](https://filfox.info/en/address/f01928520)       |           Maywood Park, Oregon, US |         279.69 TiB |      8.68% |  266.53 TiB |           4.70% |
| [f01955186](https://filfox.info/en/address/f01955186)`new`  | Hong Kong, Central and Western, HK |         268.88 TiB |      8.34% |  192.38 TiB |          28.45% |
| [f01944347](https://filfox.info/en/address/f01944347)       |           Maywood Park, Oregon, US |         231.50 TiB |      7.18% |  129.81 TiB |          43.93% |
| [f01937995](https://filfox.info/en/address/f01937995)       | Hong Kong, Central and Western, HK |         227.22 TiB |      7.05% |   78.19 TiB |          65.59% |
| [f01972356](https://filfox.info/en/address/f01972356)`new`  |           Maywood Park, Oregon, US |         223.44 TiB |      6.93% |  156.00 TiB |          30.18% |
| [f01970674](https://filfox.info/en/address/f01970674)`new`  |        Sydney, New South Wales, AU |         190.81 TiB |      5.92% |  137.22 TiB |          28.09% |
| [f01929565](https://filfox.info/en/address/f01929565)       |        Sydney, New South Wales, AU |         138.50 TiB |      4.30% |  120.84 TiB |          12.75% |
| [f01412203](https://filfox.info/en/address/f01412203)       | Hong Kong, Central and Western, HK |         118.58 TiB |      3.68% |   74.86 TiB |          36.87% |
| [f01952350](https://filfox.info/en/address/f01952350)       |           Maywood Park, Oregon, US |          42.19 TiB |      1.31% |   42.19 TiB |           0.00% |
| [f01947770](https://filfox.info/en/address/f01947770)       | Hong Kong, Central and Western, HK |          18.16 TiB |      0.56% |   18.16 TiB |           0.00% |
| [f01949183](https://filfox.info/en/address/f01949183)       |           Maywood Park, Oregon, US |           3.06 TiB |      0.09% |    3.06 TiB |           0.00% |

![Provider Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/528/1671097381235.png)
### Deal Data Replication
The below table shows how each many unique data are replicated across storage providers.
- No more than 25% of unique data are stored with less than 4 providers.

⚠️ 48.58% of deals are for data replicated across less than 4 storage providers.

| Unique Data Size | Total Deals Made | Number of Providers | Deal Percentage |
| ---------------: | ---------------: | ------------------: | --------------: |
|       566.81 TiB |       900.84 TiB |                   1 |          27.94% |
|        96.73 TiB |       442.13 TiB |                   2 |          13.71% |
|        60.50 TiB |       223.22 TiB |                   3 |           6.92% |
|        25.78 TiB |       145.88 TiB |                   4 |           4.52% |
|        13.69 TiB |       106.09 TiB |                   5 |           3.29% |
|        11.03 TiB |       135.41 TiB |                   6 |           4.20% |
|        36.97 TiB |       537.63 TiB |                   7 |          16.68% |
|        13.09 TiB |       291.09 TiB |                   8 |           9.03% |
|        17.94 TiB |       441.53 TiB |                   9 |          13.70% |

![Replication Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/528/1671097381972.png)
### Deal Data Shared with other Clients
The below table shows how many unique data are shared with other clients.
Usually different applications owns different data and should not resolve to the same CID.

⚠️ CID sharing has been observed.

| Other Client                                                                                                                                                                                                              | Application                                                                                                                      | Total Deals Affected | Unique CIDs |        Verifier |
| :------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ | :------------------------------------------------------------------------------------------------------------------------------- | -------------------: | ----------: | --------------: |
| [f1tb2hrxk5eaeewcesnid6xmvfkklfdrxsjr5k6iy](https://filfox.info/en/address/f1tb2hrxk5eaeewcesnid6xmvfkklfdrxsjr5k6iy)                                                                                                     | [Yisainuo](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/537)                                          |             3.22 PiB |       5,002 | LDN v3 multisig |
| [f3scxjx4k2q4gaa4glpzaayjprnhmebhajsavkzcq<br/>ix3xbvshhlxqouiftzsjo26gakixp3rfb3hdqxmtj<br/>ou5a](https://filfox.info/en/address/f3scxjx4k2q4gaa4glpzaayjprnhmebhajsavkzcqix3xbvshhlxqouiftzsjo26gakixp3rfb3hdqxmtjou5a) | ``                                                                                                                               |             1.00 TiB |          31 |        Joss Hua |
| [f1t3buz7oqz4fktpthqe43vauhzlnuztpgm3iyhbi](https://filfox.info/en/address/f1t3buz7oqz4fktpthqe43vauhzlnuztpgm3iyhbi)                                                                                                     | [Shenzhen kuaixue Education Development Co\., Ltd](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1363) |            64.00 GiB |           1 | LDN v3 multisig |

[^1]: To manually trigger this report, add a comment with text `checker:manualTrigger`
