### ISSUE TITLE
[DataCap Application] Ruikuyun

### ISSUE THREAD

**Issue by ciciRuikuyun** [filecoin-project/filecoin-plus-large-datasets#529]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Ruikuyun Information Technology Co., Ltd
- Website / Social Media: http://www.hnrky.com/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100TiB
- On-chain address for first allocation:f1ajdk7e6ex7fvtjtydzgys47bcg7jub2baucun7y

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Ruikuyun is a technology-based company focusing on software product development, software sales and project outsourcing, mainly providing solution providers for government, schools, enterprises and other industries, which was established in 2019 and fully laid out in 2020, and has already made certain achievements. In the operation, we always adhere to the core concept of "innovation + wisdom" and focus on the close integration of software technology with various application industries. Through the mainstream tools, big data, artificial intelligence and other core technologies, products cover the whole life cycle of the service system, to help promote the transformation of traditional work mode to intelligent mode in various industries.
```

What is the primary source of funding for this project?
```
Our funding is from company's income.
```

What other projects/ecosystem stakeholders is this project associated with?
```
No
```

## Use-case details

Describe the data being stored onto Filecoin
```
Videos in monitors.
```

Where was the data in this dataset sourced from?
```
One of our products is smart shop monitoring system, it produces amounts of videos about clients' requirements.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
[demo.zip](https://github.com/filecoin-project/filecoin-plus-large-datasets/files/9189449/demo.zip)
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes, we confirm.
```

What is the expected retrieval frequency for this data?
```
Twice a year.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
More than 1 year.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
China.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
The safe way for our choice is offline transfer. It can reduce loss than online transfer in our condition.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We chatted with some sps in slack so we want to begin the coorporation with them. We are still finding more sps now. 
```

How will you be distributing deals across storage providers?
```
We try to follow the rule about LDN. Under 25% to per sp.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, we are preparing funding and looking for sps.
```

**Comment by Sunnyiscoming** [comment]
1.Can you provide more detailed information about storage providers distribution, such as you can list SPs you have contacted with at present?
2.Could you send an email to filplus-app-review@fil.org with your official domain(wyndhamhotels.com) in order to confirm your identity?
Email name should includes the issue id #529.

**Comment by ciciRuikuyun** [comment]
@Sunnyiscoming 
We have finished contacting with f0134609. And more Sps will be welcomed to join us! Please cc us. Slack: Ruikuyun
Ok, the email is already sent.
![6](https://user-images.githubusercontent.com/106974804/185080698-04185a5f-ccda-491d-ae38-151080c57870.png)

**Comment by Sunnyiscoming** [comment]
Email received.
It is super important to value decentralization and diversification as you onboard large sums of data onto the network, especially to minimize concentration risk and distribute data to several SPs. At this point, I suggest that you find at least 3 other SP organizations and focus first on restoring the data you have already stored with the main SP org to ensure you have safe replica building and no data loss from the network.

**Comment by ciciRuikuyun** [comment]
@Sunnyiscoming Thank you for your advice!

**Comment by Sunnyiscoming** [comment]
Any update here? Can you list more sps you contact with at present?

**Comment by ciciRuikuyun** [comment]
@Sunnyiscoming Yes, we are contacting f083065, f01136409 and other nodes. I think we can contact more SPs after we apply to get datacap successfully. We are doing our best to find more SPs and also hope you can approve our application and grant us the datacap.

**Comment by raghavrmadya** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 100TiB

**Client address**

>f1ajdk7e6ex7fvtjtydzgys47bcg7jub2baucun7y

**Comment by raghavrmadya** [comment]
Notaries, please ascertain more information on SP distribution and gain confidence on data samples. Thank you @ciciRuikuyun for your continued cooperation

**Comment by UnionLabs2020** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec224i2k4h67undljpknlim4s4iomn7nxegpw7pdpovrwzxkkye2e 
#### Address 
> f1ajdk7e6ex7fvtjtydzgys47bcg7jub2baucun7y
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f17xdri3wunqgld7dm23e4f3eqsntjakwc47xjo6i
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec224i2k4h67undljpknlim4s4iomn7nxegpw7pdpovrwzxkkye2e

**Comment by swatchliu** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedfkx52whsfhfkskgvyuxd6gybttfpwiquzqjih4jrcsmhrfh5elk 
#### Address 
> f1ajdk7e6ex7fvtjtydzgys47bcg7jub2baucun7y
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1yh6q3nmsg7i2sys7f7dexcuajgoweudcqj2chfi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedfkx52whsfhfkskgvyuxd6gybttfpwiquzqjih4jrcsmhrfh5elk

**Comment by BigD-Exchange** [comment]
@ciciRuikuyun Hi! Great to see you have gotten approval for DataCap. If you are looking for more storage providers to store these data or have any questions, please visit #bigdata-exchange on Filecoin Slack or reply here. 

We have strong demand from a diverse group of SPs, who are actively looking to onboard more data.

**Comment by 1475Notary** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedqroowmyjbona7hdoobx2muwt3s5362n2zbtj34yb3rjxhgpap7q 
#### Address 
> f1ajdk7e6ex7fvtjtydzgys47bcg7jub2baucun7y
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1ofq4mngy7ggcp755pfquq2gphjjnlydolf6awtq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedqroowmyjbona7hdoobx2muwt3s5362n2zbtj34yb3rjxhgpap7q

**Comment by PluskitOfficial** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedsjoavxc52irfqvizz4i36leq72d2zm5u5uzxj7ny3wpkii4mtqm 
#### Address 
> f1ajdk7e6ex7fvtjtydzgys47bcg7jub2baucun7y
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1tgnlhtcmhwipfm7thsftxhn5k52velyjlazpvka
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedsjoavxc52irfqvizz4i36leq72d2zm5u5uzxj7ny3wpkii4mtqm

**Comment by MRJAVAZHAO** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebxiir2xxnskeavvltsyne2zwm5cjcnxqp3df753yigyowv5nayqw 
#### Address 
> f1ajdk7e6ex7fvtjtydzgys47bcg7jub2baucun7y
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f14gme3f52prtyzk6pblogrdd6b6ivp4swc6qmesi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebxiir2xxnskeavvltsyne2zwm5cjcnxqp3df753yigyowv5nayqw

**Comment by UnionLabs2020** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedf5fbmiozj4jbjrbuhthrllexlx5yocc2hopbciuxodlemckkmyg 
#### Address 
> f1ajdk7e6ex7fvtjtydzgys47bcg7jub2baucun7y
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f17xdri3wunqgld7dm23e4f3eqsntjakwc47xjo6i
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedf5fbmiozj4jbjrbuhthrllexlx5yocc2hopbciuxodlemckkmyg

**Comment by PluskitOfficial** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacearh6ltwd5kbw423e6vgrigd2cfzcnh5mhwyftemcl3mesi4553ss 
#### Address 
> f1ajdk7e6ex7fvtjtydzgys47bcg7jub2baucun7y
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1tgnlhtcmhwipfm7thsftxhn5k52velyjlazpvka
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacearh6ltwd5kbw423e6vgrigd2cfzcnh5mhwyftemcl3mesi4553ss

**Comment by BlockMakeronline** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecu3vnznx2dwg2bymusyaax2pzf5btfuzrsa7mm742layghgeczxm 
#### Address 
> f1ajdk7e6ex7fvtjtydzgys47bcg7jub2baucun7y
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1o3twrcpwjtpcd4q36lpq4qmy2qfbgtyy5h6tsty
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecu3vnznx2dwg2bymusyaax2pzf5btfuzrsa7mm742layghgeczxm

**Comment by UnionLabs2020** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebct5shhq6n6rjbmzmij7yvnuafhhgwm2a3ow4lw3733m47nv74ms 
#### Address 
> f1ajdk7e6ex7fvtjtydzgys47bcg7jub2baucun7y
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f17xdri3wunqgld7dm23e4f3eqsntjakwc47xjo6i
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebct5shhq6n6rjbmzmij7yvnuafhhgwm2a3ow4lw3733m47nv74ms

**Comment by PluskitOfficial** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecnfku6f5kbdahzgxddjsyas5plrnku5vonoe5nipkbgpekbkehqe 
#### Address 
> f1ajdk7e6ex7fvtjtydzgys47bcg7jub2baucun7y
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1tgnlhtcmhwipfm7thsftxhn5k52velyjlazpvka
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecnfku6f5kbdahzgxddjsyas5plrnku5vonoe5nipkbgpekbkehqe

**Comment by swatchliu** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebmipduc6fsc7mjavkooid3cvoe7wibqay7w4qsp6tl4icklgyjdu 
#### Address 
> f1ajdk7e6ex7fvtjtydzgys47bcg7jub2baucun7y
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1yh6q3nmsg7i2sys7f7dexcuajgoweudcqj2chfi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebmipduc6fsc7mjavkooid3cvoe7wibqay7w4qsp6tl4icklgyjdu

**Comment by PluskitOfficial** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced4xuaqrfq6gftcbuaubuhfofks57yopzukhl4rdt5m3aoj3bwxte 
#### Address 
> f1ajdk7e6ex7fvtjtydzgys47bcg7jub2baucun7y
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1tgnlhtcmhwipfm7thsftxhn5k52velyjlazpvka
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced4xuaqrfq6gftcbuaubuhfofks57yopzukhl4rdt5m3aoj3bwxte

**Comment by UnionLabs2020** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebcn3mgjpdpfw6q3vwcsdnv73wan3tvn35lwy2punwqqrwflgeyms 
#### Address 
> f1ajdk7e6ex7fvtjtydzgys47bcg7jub2baucun7y
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f17xdri3wunqgld7dm23e4f3eqsntjakwc47xjo6i
#### Id
> 0d1b3029-396a-4a01-988c-e070f134a389
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebcn3mgjpdpfw6q3vwcsdnv73wan3tvn35lwy2punwqqrwflgeyms

**Comment by MetaWaveInfo** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceakjwijeb37dpjzkye2jdmdvpyy42jrdxkrjt2fujwa2vjdai6tbe 
#### Address 
> f1ajdk7e6ex7fvtjtydzgys47bcg7jub2baucun7y
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1ktlkcxnmzxcdaoqfsunrg3vocfbmgv4n3mrn74a
#### Id
> 0d1b3029-396a-4a01-988c-e070f134a389
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceakjwijeb37dpjzkye2jdmdvpyy42jrdxkrjt2fujwa2vjdai6tbe

**Comment by filplus-checker** [comment]
## DataCap and CID Checker Report[^1]
 - Organization: `Ruikuyun Information Technology Co., Ltd`
 - Client: `f1ajdk7e6ex7fvtjtydzgys47bcg7jub2baucun7y`
### Storage Provider Distribution
The below table shows the distribution of storage providers that have stored data for this client.

If this is the first time a provider takes verified deal, it will be marked as `new`.

For most of the datacap application, below restrictions should apply.
 - Storage provider should not exceed 25% of total datacap.
 - Storage provider should not be storing duplicate data for more than 20%.
 - Storage provider should have published its public IP address.
 - All storage providers should be located in different regions.

⚠️ 79.73% of total deal sealed by [f01926585](https://filfox.info/en/address/f01926585) are duplicate data.

⚠️ 32.14% of total deal sealed by [f01917214](https://filfox.info/en/address/f01917214) are duplicate data.

⚠️ 42.99% of total deal sealed by [f01917236](https://filfox.info/en/address/f01917236) are duplicate data.

⚠️ 77.06% of total deal sealed by [f01926914](https://filfox.info/en/address/f01926914) are duplicate data.

⚠️ 77.26% of total deal sealed by [f01926802](https://filfox.info/en/address/f01926802) are duplicate data.

⚠️ 70.73% of total deal sealed by [f01924325](https://filfox.info/en/address/f01924325) are duplicate data.

⚠️ 71.41% of total deal sealed by [f01924416](https://filfox.info/en/address/f01924416) are duplicate data.

⚠️ 71.32% of total deal sealed by [f01924350](https://filfox.info/en/address/f01924350) are duplicate data.

⚠️ 40.97% of total deal sealed by [f01895715](https://filfox.info/en/address/f01895715) are duplicate data.

⚠️ 45.36% of total deal sealed by [f01917208](https://filfox.info/en/address/f01917208) are duplicate data.

⚠️ 85.00% of total deal sealed by [f01895783](https://filfox.info/en/address/f01895783) are duplicate data.

| Provider                                              |                 Location | Total Deals Sealed | Percentage | Unique Data | Duplicate Deals |
| :---------------------------------------------------- | -----------------------: | -----------------: | ---------: | ----------: | --------------: |
| [f01926585](https://filfox.info/en/address/f01926585) |    Ashburn, Virginia, US |         286.81 TiB |     12.45% |   58.13 TiB |          79.73% |
| [f01917214](https://filfox.info/en/address/f01917214) |         Seoul, Seoul, KR |         248.88 TiB |     10.81% |  168.88 TiB |          32.14% |
| [f01917236](https://filfox.info/en/address/f01917236) |         Seoul, Seoul, KR |         244.97 TiB |     10.64% |  139.66 TiB |          42.99% |
| [f01926914](https://filfox.info/en/address/f01926914) |    Ashburn, Virginia, US |         243.72 TiB |     10.58% |   55.91 TiB |          77.06% |
| [f01926802](https://filfox.info/en/address/f01926802) |    Ashburn, Virginia, US |         237.16 TiB |     10.30% |   53.94 TiB |          77.26% |
| [f01924325](https://filfox.info/en/address/f01924325) | Singapore, Singapore, SG |         226.78 TiB |      9.85% |   66.38 TiB |          70.73% |
| [f01924416](https://filfox.info/en/address/f01924416) | Singapore, Singapore, SG |         225.28 TiB |      9.78% |   64.41 TiB |          71.41% |
| [f01924350](https://filfox.info/en/address/f01924350) | Singapore, Singapore, SG |         224.38 TiB |      9.74% |   64.34 TiB |          71.32% |
| [f01917241](https://filfox.info/en/address/f01917241) |         Seoul, Seoul, KR |          91.91 TiB |      3.99% |   84.44 TiB |           8.13% |
| [f01917257](https://filfox.info/en/address/f01917257) |         Seoul, Seoul, KR |          91.19 TiB |      3.96% |   81.13 TiB |          11.03% |
| [f01895715](https://filfox.info/en/address/f01895715) |         Seoul, Seoul, KR |          75.97 TiB |      3.30% |   44.84 TiB |          40.97% |
| [f01917208](https://filfox.info/en/address/f01917208) |         Seoul, Seoul, KR |          66.00 TiB |      2.87% |   36.06 TiB |          45.36% |
| [f01916487](https://filfox.info/en/address/f01916487) |         Seoul, Seoul, KR |          10.00 TiB |      0.43% |   10.00 TiB |           0.00% |
| [f01914977](https://filfox.info/en/address/f01914977) |    Ashburn, Virginia, US |          10.00 TiB |      0.43% |   10.00 TiB |           0.00% |
| [f01900713](https://filfox.info/en/address/f01900713) |         Seoul, Seoul, KR |          10.00 TiB |      0.43% |   10.00 TiB |           0.00% |
| [f01895783](https://filfox.info/en/address/f01895783) |     Boardman, Oregon, US |          10.00 TiB |      0.43% |    1.50 TiB |          85.00% |

![Provider Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/529/1671097402160.png)
### Deal Data Replication
The below table shows how each many unique data are replicated across storage providers.
- No more than 25% of unique data are stored with less than 4 providers.

⚠️ 100.00% of deals are for data replicated across less than 4 storage providers.

| Unique Data Size | Total Deals Made | Number of Providers | Deal Percentage |
| ---------------: | ---------------: | ------------------: | --------------: |
|       484.06 TiB |       859.75 TiB |                   1 |          37.33% |
|       130.63 TiB |       773.22 TiB |                   2 |          33.57% |
|        68.09 TiB |       670.06 TiB |                   3 |          29.09% |

![Replication Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/529/1671097403273.png)
### Deal Data Shared with other Clients
The below table shows how many unique data are shared with other clients.
Usually different applications owns different data and should not resolve to the same CID.

⚠️ CID sharing has been observed.

| Other Client                                                                                                          | Application                                                                                                                | Total Deals Affected | Unique CIDs |        Verifier |
| :-------------------------------------------------------------------------------------------------------------------- | :------------------------------------------------------------------------------------------------------------------------- | -------------------: | ----------: | --------------: |
| [f1clwd2dooy2cflfilhzeq2ycl544b3heqsiwhjrq](https://filfox.info/en/address/f1clwd2dooy2cflfilhzeq2ycl544b3heqsiwhjrq) | [FiboAI](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/349)                                      |           312.34 TiB |       3,222 | LDN v3 multisig |
| [f17qd6x3leh5pa7vh6ewdaed7qhbn2mgofrokuayy](https://filfox.info/en/address/f17qd6x3leh5pa7vh6ewdaed7qhbn2mgofrokuayy) | [Drust](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/427)                                       |           250.38 TiB |       2,890 | LDN v3 multisig |
| [f1bb2z36lpq3pnwiiowiraagpzqnpow4bonjacx7a](https://filfox.info/en/address/f1bb2z36lpq3pnwiiowiraagpzqnpow4bonjacx7a) | [Hola Space](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/362)                                  |           231.53 TiB |       1,731 | LDN v3 multisig |
| [f1einobkrjcjk6gfc5ov6663vrri75hwdsjfs6pmq](https://filfox.info/en/address/f1einobkrjcjk6gfc5ov6663vrri75hwdsjfs6pmq) | [Cansoti](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/640)                                     |           218.63 TiB |       2,423 | LDN v3 multisig |
| [f1quofpadzcqlonmz7v3mv7dfqvm5hdztucdsjqsy](https://filfox.info/en/address/f1quofpadzcqlonmz7v3mv7dfqvm5hdztucdsjqsy) | [HENAN 863 SOFTWARE CO\., LTD](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/468)                |           146.66 TiB |       2,139 | LDN v3 multisig |
| [f1vtcetpapwwyka6txwqjwymsa67npdfilbkwh64a](https://filfox.info/en/address/f1vtcetpapwwyka6txwqjwymsa67npdfilbkwh64a) | [Chimay](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/397)                                      |           132.84 TiB |       1,444 | LDN v3 multisig |
| [f1ivsvpljx4ovp2tth73pllkxmumrudemks623iia](https://filfox.info/en/address/f1ivsvpljx4ovp2tth73pllkxmumrudemks623iia) | `TIS Inc. group`                                                                                                           |           109.22 TiB |         900 | LDN v3 multisig |
| [f1rnwp6p5kx7pcwexpucoav6mmwz3rkxw5blrboyy](https://filfox.info/en/address/f1rnwp6p5kx7pcwexpucoav6mmwz3rkxw5blrboyy) | [MigoVideo](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/517)                                   |           107.16 TiB |       1,685 | LDN v3 multisig |
| [f1zb6pgkktdbyy7zxfob6gripqxuc25ukf35cc7fq](https://filfox.info/en/address/f1zb6pgkktdbyy7zxfob6gripqxuc25ukf35cc7fq) | `Maxpic PhotoGraphic Studio`                                                                                               |           103.50 TiB |       1,357 | LDN v3 multisig |
| [f1ki4cjk27ypzjsuzkvvqzs6xobaweuoxfdcnpqhy](https://filfox.info/en/address/f1ki4cjk27ypzjsuzkvvqzs6xobaweuoxfdcnpqhy) | [TimeQuant](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/385)                                   |           102.88 TiB |       1,945 | LDN v3 multisig |
| [f1nmhjvibl7acp45lpxmo5kduz42evjazsyi4mzza](https://filfox.info/en/address/f1nmhjvibl7acp45lpxmo5kduz42evjazsyi4mzza) | `ubuckvnockai`                                                                                                             |            99.59 TiB |       1,108 | LDN v3 multisig |
| [f1f5edx6ofn3lf6rk3yfpldbi2pzgq2egoyu6ubpi](https://filfox.info/en/address/f1f5edx6ofn3lf6rk3yfpldbi2pzgq2egoyu6ubpi) | [Samdata Trade](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/382)                               |            40.25 TiB |         760 | LDN v3 multisig |
| [f1avhqgmeazxzvylz34l26o3nlj2ywnzaviwns3dq](https://filfox.info/en/address/f1avhqgmeazxzvylz34l26o3nlj2ywnzaviwns3dq) | [87v5\-CarsonVideo](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/392)                           |            32.75 TiB |         538 | LDN v3 multisig |
| [f14abwn2goturifmt27s2bssoe3fup2b3npkgfzui](https://filfox.info/en/address/f14abwn2goturifmt27s2bssoe3fup2b3npkgfzui) | [KONGFU VR](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/372)                                   |            27.47 TiB |         608 | LDN v3 multisig |
| [f1dwhevm3p2slu6itmkssznscmpkpltdiztprnpya](https://filfox.info/en/address/f1dwhevm3p2slu6itmkssznscmpkpltdiztprnpya) | [Hiscene](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/548)                                     |            22.94 TiB |         214 | LDN v3 multisig |
| [f1jdmx2cuswzjlt4pnsv3t7ipmesywzxsg6q56a2a](https://filfox.info/en/address/f1jdmx2cuswzjlt4pnsv3t7ipmesywzxsg6q56a2a) | [Raysun Radar Electronic Technology Co\.,Ltd](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/884) |            17.91 TiB |         163 | LDN v3 multisig |
| [f1smfrznoqsp7eptqnselnosng7vxuo3ptnoqv2oa](https://filfox.info/en/address/f1smfrznoqsp7eptqnselnosng7vxuo3ptnoqv2oa) | [CTG Business Service](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/306)                        |            10.88 TiB |         168 | LDN v3 multisig |
| [f1tivtdkq34mnfzso63wrr2xh6r2zo7aebao4jfla](https://filfox.info/en/address/f1tivtdkq34mnfzso63wrr2xh6r2zo7aebao4jfla) | `China travel service(HongKong) limited`                                                                                   |             1.97 TiB |           6 | LDN v3 multisig |
| [f1dx7ljly4vmk5x2bn5ng4jpbqnuvozrz2phw42qy](https://filfox.info/en/address/f1dx7ljly4vmk5x2bn5ng4jpbqnuvozrz2phw42qy) | [CoinPhD](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/364)                                     |           128.00 GiB |           3 | LDN v3 multisig |
| [f1ffbtksiso5za73pypuxbxznng6rdv64nbihdtba](https://filfox.info/en/address/f1ffbtksiso5za73pypuxbxznng6rdv64nbihdtba) | [EpikProtocol](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/281)                                |            32.00 GiB |           1 |       LDN # 281 |
| [f1qjrlejxv5a73kxurwtxyrni6ji7orm74zeeetiy](https://filfox.info/en/address/f1qjrlejxv5a73kxurwtxyrni6ji7orm74zeeetiy) | [Mooc](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/223)                                        |            32.00 GiB |           1 | LDN v3 multisig |

[^1]: To manually trigger this report, add a comment with text `checker:manualTrigger`
