### ISSUE TITLE
[DataCap Application] Nhoman pte. Ltd.

### ISSUE THREAD

**Issue by www-2022** [filecoin-project/filecoin-plus-large-datasets#533]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name:  Nhoman pte. Ltd.
- Website / Social Media:   web: www.ninkia.com   app store: ninkia
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100TiB
- On-chain address for first allocation:  f16avliktafvesomu54iiwoplmbgpzok6q7qxo65a

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.

```
Our company is called Nhoman. The company's products are based on Ninkia, a multilingual community in Southeast Asia and third world countries. At present, it has 1M users distributed in more than 80 countries around the world. The community content includes sports, games, entertainment, tourism and leisure. 19, 10 in Shanghai, 5 in Singapore, 1 each in Thailand, Vietnam, Indonesia and the Philippines

<img width="135" alt="image" src="https://user-images.githubusercontent.com/29194012/180908906-456416a5-5410-4b95-8ab5-fb9df6911e84.png">
```

What is the primary source of funding for this project?
```
1、Early Investors Invest Funds
2、company’s income..
```

What other projects/ecosystem stakeholders is this project associated with?
```
None.
```

## Use-case details

Describe the data being stored onto Filecoin
```
The data stored on Filecoin are all application data, such as app development data, technical data, and publicly available data stored by customers..
```

Where was the data in this dataset sourced from?
```
From our company and customer’s public data.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
ngaccesslog.us-ca.uclouds3.com/access.log.1   
ngaccesslog.us-ca.uclouds3.com/access.log.2  
ngaccesslog.us-ca.uclouds3.com/access.log.3
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes it is.
```

What is the expected retrieval frequency for this data?
```
Probably twice a year.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
At least 540 days.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
North America, ASIA.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
There will be both online and offline data transfer process. We will use hardware copy for the storage provider who are relatively close to us. The rest of those may use online transfer. 
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We have an list of storage providers that are being contacted in North America and Asia. And we believe that the reputation of these storage providers is trustworthy..
```

How will you be distributing deals across storage providers?
```
Try to be even, to ensure that each storage provider is not assigned too much proportion of datacap.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, we are preparing to ensure we can start making deals as soon as possible.
```

**Comment by www-2022** [comment]
Thank for your reply!
1、We will store our data to at least 5 SPs， but we don't have a partnered SP yet.  we will determine the cooperative SP after the application is approved.
2、This is customer‘s access log，it’s public data，we want store to filecoin for backup. can you provide the offical email address，and we will send the proof of right of use to it.

[access.1.log](https://github.com/filecoin-project/filecoin-plus-large-datasets/files/9356446/access.1.log)
[access.2.log](https://github.com/filecoin-project/filecoin-plus-large-datasets/files/9356453/access.2.log)
[access.3.log](https://github.com/filecoin-project/filecoin-plus-large-datasets/files/9356497/access.3.log)

**Comment by Sunnyiscoming** [comment]
There is some doubt about the total amount of data. Can you explain the data composition? Provide at least two data samples for each type of data.

**Comment by www-2022** [comment]
Thanks for your reply!
1、These  data of logs are from our another module of system, please check for it。
[proxy_1660726426_265048.log](https://github.com/filecoin-project/filecoin-plus-large-datasets/files/9389068/proxy_1660726426_265048.log)
[proxy_1660731973_724071.log](https://github.com/filecoin-project/filecoin-plus-large-datasets/files/9389069/proxy_1660731973_724071.log)
[proxy_1660735314_378286.log](https://github.com/filecoin-project/filecoin-plus-large-datasets/files/9389071/proxy_1660735314_378286.log)
[proxy_1660739178_613012.log](https://github.com/filecoin-project/filecoin-plus-large-datasets/files/9389073/proxy_1660739178_613012.log)
[proxy_1660740591_221782.log](https://github.com/filecoin-project/filecoin-plus-large-datasets/files/9389074/proxy_1660740591_221782.log)
[proxy_1660744281_341193.log](https://github.com/filecoin-project/filecoin-plus-large-datasets/files/9389075/proxy_1660744281_341193.log)

**Comment by raghavrmadya** [comment]
We can verify that this company is legitimate but we need to ensure what is your relationship with this company. Please share more. Additionally, please send an email stating you have applied for LDN using an official email plus a business license to filplus-app-review@fil.org

Thanks.

**Comment by www-2022** [comment]
Thanks for your reply!

**Comment by Sunnyiscoming** [comment]
Do not received any email from your organization. Any update here?

**Comment by Sunnyiscoming** [comment]
Any update here? @www-2022

**Comment by raghavrmadya** [comment]
No response

**Comment by www-2022** [comment]
Sorry for the late reply， we have send a email to filplus-app-review@fil.org  some days ago， and send again yesterday.   The sender is leonshan， please check to confirm.
