### ISSUE TITLE
[DataCap Application] <Mlisana> - <Yisainuo>

### ISSUE THREAD

**Issue by ghost** [filecoin-project/filecoin-plus-large-datasets#537]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Yisainuo
- Website / Social Media:https://www.yisainuo.com/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):100TiB
- On-chain address for first allocation:f1tb2hrxk5eaeewcesnid6xmvfkklfdrxsjr5k6iy

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Yisainuo as a professional enterprise was founded in 2003 providing cross-border e-commerce integration services, the company focuses on Chinese enterprise brands going overseas, providing cross-border integrated marketing solution for traditional manufacturing enterprises, cross-border e-commerce sellers, and APP sellers. After years of accumulated service experience and product technology widely recognized by customers, the company relies on the world's leading Internet platform to help Chinese companies improve sales performance in overseas markets, collect global accurate traffic, and establish overseas brand images. At present, the company's solutions are SNS, SEM, foreign trade website construction and video shooting. At present, Yisainuo's photography service is specially aimed at the business department of factory shooting. Many foreign trade companies often ignore the importance of pictures, and the pictures of factories uploaded on the official website are blurry and cluttered. Through our lens, all factories can shine with unique charm. Let foreign customers grab their attention and increase their confidence when they browse your website. Therefore, in the process of the tens of thousands of customers we served, a lot of data is generated.
```
What is the primary source of funding for this project?
```
The source is the income of company.
```

What other projects/ecosystem stakeholders is this project associated with?
```
No
```

## Use-case details

Describe the data being stored onto Filecoin
```
They are mainly videos and pictures created by ourself. And some music and documents.
```

Where was the data in this dataset sourced from?
```
From our company
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
(https://drive.google.com/drive/folders/1E3rCviYkrHGFyJbOJFOpedKXyH6D7Stj?usp=sharing)
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Confirm.
```

What is the expected retrieval frequency for this data?
```
The expected retrieval frequency for most data is once a year.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
We want to keep it for  2 years on Filecoin at first.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Asia
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
We support online and offline data transfer to storage providers.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We are currently looking for more than 4 stable storage providers and will contact more online storage providers later. 
```

How will you be distributing deals across storage providers?
```
We will try our best to contact as many service providers as possible, and ensure that each storage provider gets the datacap allocation according to the rules. 
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes,we have the resources.
```

**Comment by Sunnyiscoming** [comment]
1.Can you provide more detailed information about storage providers distribution, such as you can list SPs you have contacted with at present?
2.Could you send an email to filplus-app-review@fil.org with your official domain(wyndhamhotels.com) in order to confirm your identity?
Email name should includes the issue id #537.

**Comment by Mlisana** [comment]
> 1.Can you provide more detailed information about storage providers distribution, such as you can list SPs you have contacted with at present? 2.Could you send an email to [filplus-app-review@fil.org](mailto:filplus-app-review@fil.org) with your official domain in order to confirm your identity? Email name should includes the issue id #537.
1.f01423116f01674967f01770778f01851683 these are the Sps that we contacted, but these are not the final Sps for the LDN, and we will contacte with more Sps to make the distributed storages.
2.The email had been sent to you,pls check it.

**Comment by Mlisana** [comment]
> 1.Can you provide more detailed information about storage providers distribution, such as you can list SPs you have contacted with at present? 2.Could you send an email to [filplus-app-review@fil.org](mailto:filplus-app-review@fil.org) with your official domain in order to confirm your identity? Email name should includes the issue id #537.

1. we are not decide the all SPs totally, the f01423116 f01851683 are the SPs that we contacted currently.We are going to find more SPs for the project.
2. Pls check the emai the we sent. 
<img width="278" alt="1661321504491" src="https://user-images.githubusercontent.com/110005617/186343869-44766ea7-2f7b-4d5e-bc3a-9e68696b70e5.png">

**Comment by Sunnyiscoming** [comment]
Received that.

**Comment by Mlisana** [comment]
> 

Is there any updates about the LDN?

**Comment by Mlisana** [comment]
> Received that.

Is there any updates about the LDN?

**Comment by Mlisana** [comment]
> Received that.

Sorry to bother you, but how long does it take me to the next step?

**Comment by raghavrmadya** [comment]
As your organizartion is almost 20 years old, can you share some names of  Chinese enterprise brands going overseas? We are unable to determine this through the data samples provided

**Comment by Mlisana** [comment]
> As your organizartion is almost 20 years old, can you share some names of Chinese enterprise brands going overseas? We are unable to determine this through the data samples provided

Henan Hongxing Mining Machinery Co.,Ltd. 
UNIQUE Group
Henan Junshecheng Network Technology Co., Ltd.
Qingdao Langfu Packaging Co., Ltd.
ALL of these companies we served that made advertisements on facebook.They were our customers.
![bc751621d85f427fb5818b79e91e2c1](https://user-images.githubusercontent.com/110005617/188264552-1c7c2a1e-cbff-440e-8933-85b5f625b508.jpg)

**Comment by Mlisana** [comment]
> As your organizartion is almost 20 years old, can you share some names of Chinese enterprise brands going overseas? We are unable to determine this through the data samples provided

@raghavrmadya Sorry to bother you, but how long does it take me to the next step?

**Comment by raghavrmadya** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 100TiB

**Client address**

>f1tb2hrxk5eaeewcesnid6xmvfkklfdrxsjr5k6iy

**Comment by Mlisana** [comment]
> ### Datacap Request Trigger
> **Total DataCap requested**
> 
> > 5PiB
> 
> **Expected weekly DataCap usage rate**
> 
> > 100TiB
> 
> **Client address**
> 
> > f1tb2hrxk5eaeewcesnid6xmvfkklfdrxsjr5k6iy

Sorry to bother you.There is no bot to make DataCap Allocation requested, so i can't go for next step.Hope you can help me!

**Comment by Mlisana** [comment]
> 

@raghavrmadya i don't know why there is no bot to make Datacap Allocation Requested. So hope you can help me. Thank you very much~

**Comment by Mlisana** [comment]
@galen-mcandrew @raghavrmadya  The notary can't find my LDN number and make a signature. I think it is because the bot didn't make the Datacap allocation request. Hope you can help me,Thanks very much.

**Comment by raghavrmadya** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 100TiB

**Client address**

>f1tb2hrxk5eaeewcesnid6xmvfkklfdrxsjr5k6iy

**Comment by 1ane-1** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaiuti7tvqufjpm44vfpsh2b7qe4lqamltjwvrutmq6qgqasospnm 
#### Address 
> f1tb2hrxk5eaeewcesnid6xmvfkklfdrxsjr5k6iy
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1mdk7s2vntzm6hu35yuo6vjubtrpfnb2awhgvrri
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaiuti7tvqufjpm44vfpsh2b7qe4lqamltjwvrutmq6qgqasospnm

**Comment by Tom-OriginStorage** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb6rkux4noqp72a4kczp62dv45f443frpvqt5plvusn2av3ewwxoc 
#### Address 
> f1tb2hrxk5eaeewcesnid6xmvfkklfdrxsjr5k6iy
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1q6bpjlqia6iemqbrdaxr2uehrhpvoju3qh4lpga
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb6rkux4noqp72a4kczp62dv45f443frpvqt5plvusn2av3ewwxoc

**Comment by newwebgroup** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebbexxqvznhk3ztipwcwdzi7rws4manuqmtc5bhkmg4dgibzl23wa 
#### Address 
> f1tb2hrxk5eaeewcesnid6xmvfkklfdrxsjr5k6iy
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1e77zuityhvvw6u2t6tb5qlnsegy2s67qs4lbbbq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebbexxqvznhk3ztipwcwdzi7rws4manuqmtc5bhkmg4dgibzl23wa

**Comment by NDLABS-OFFICE** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedropnyq5fidrfpz6uwjjykpf3qyxbcvyiv5nx3smhq7fon763rxy 
#### Address 
> f1tb2hrxk5eaeewcesnid6xmvfkklfdrxsjr5k6iy
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1yayfsv6whu3rheviucvventj3y6t542xfpb47ei
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedropnyq5fidrfpz6uwjjykpf3qyxbcvyiv5nx3smhq7fon763rxy

**Comment by newwebgroup** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced4lift5tkjpxfsa425a5dvlos7sbgk5sgz3xmqrv63eec3usiqge 
#### Address 
> f1tb2hrxk5eaeewcesnid6xmvfkklfdrxsjr5k6iy
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1e77zuityhvvw6u2t6tb5qlnsegy2s67qs4lbbbq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced4lift5tkjpxfsa425a5dvlos7sbgk5sgz3xmqrv63eec3usiqge

**Comment by kernelogic** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacearz5tapucrtxysa7lanjlknazua3wnliwr2bgsnu4ietoy7obq2e 
#### Address 
> f1tb2hrxk5eaeewcesnid6xmvfkklfdrxsjr5k6iy
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacearz5tapucrtxysa7lanjlknazua3wnliwr2bgsnu4ietoy7obq2e

**Comment by ipfscn** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedlkfh7jc5yaxv7x6444ql3ysycq7m2v6zhr73rg3sszlpcdyzl7s 
#### Address 
> f1tb2hrxk5eaeewcesnid6xmvfkklfdrxsjr5k6iy
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1j4n74chme7whbz3yls4a7ixqewb6dijypqg2a3a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedlkfh7jc5yaxv7x6444ql3ysycq7m2v6zhr73rg3sszlpcdyzl7s

**Comment by Tom-OriginStorage** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceazp6natp3xv4vv326yy5hqclqrtn5keselg3pubstuxduxcfked6 
#### Address 
> f1tb2hrxk5eaeewcesnid6xmvfkklfdrxsjr5k6iy
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1q6bpjlqia6iemqbrdaxr2uehrhpvoju3qh4lpga
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceazp6natp3xv4vv326yy5hqclqrtn5keselg3pubstuxduxcfked6

**Comment by stcouldlisa** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb5ejkkfuihtaamwa7qdwpk24vm4dvnpb72w4sgdgfk4bydrqd7b2 
#### Address 
> f1tb2hrxk5eaeewcesnid6xmvfkklfdrxsjr5k6iy
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1jvvltduw35u6inn5tr4nfualyd42bh3vjtylgci
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb5ejkkfuihtaamwa7qdwpk24vm4dvnpb72w4sgdgfk4bydrqd7b2

**Comment by Joss-Hua** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced4vrr6j4azxkpa2hm3mks776enh6f5ooc5x7u6evcgr4ptc2yahw 
#### Address 
> f1tb2hrxk5eaeewcesnid6xmvfkklfdrxsjr5k6iy
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1tfg54zzscugttejv336vivknmsnzzmyudp3t7wi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced4vrr6j4azxkpa2hm3mks776enh6f5ooc5x7u6evcgr4ptc2yahw

**Comment by Tom-OriginStorage** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedisnw3g7payhsopz2bwaklqypaqhagww6qcmt3v6azuqzdsasgqw 
#### Address 
> f1tb2hrxk5eaeewcesnid6xmvfkklfdrxsjr5k6iy
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1q6bpjlqia6iemqbrdaxr2uehrhpvoju3qh4lpga
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedisnw3g7payhsopz2bwaklqypaqhagww6qcmt3v6azuqzdsasgqw

**Comment by newwebgroup** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacectak226cfov7jd77laswvi2kehzw2rcrefszt44nue7cpegu3h4s 
#### Address 
> f1tb2hrxk5eaeewcesnid6xmvfkklfdrxsjr5k6iy
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1e77zuityhvvw6u2t6tb5qlnsegy2s67qs4lbbbq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacectak226cfov7jd77laswvi2kehzw2rcrefszt44nue7cpegu3h4s

**Comment by newwebgroup** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb4movd34e6hjtlxwmtj4umyrknmab5zdrrrdpfhhqtz5ahjzv5li 
#### Address 
> f1tb2hrxk5eaeewcesnid6xmvfkklfdrxsjr5k6iy
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1e77zuityhvvw6u2t6tb5qlnsegy2s67qs4lbbbq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb4movd34e6hjtlxwmtj4umyrknmab5zdrrrdpfhhqtz5ahjzv5li

**Comment by xiaoyuaiheshui** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacednenizcudzy6w3jhfyazrnn4bfqrfzcvrxd2nflncypxptgc7ueu 
#### Address 
> f1tb2hrxk5eaeewcesnid6xmvfkklfdrxsjr5k6iy
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f122qmy25wdtt5mxd77kndiq7z5x2n3iwiuz2wdsa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacednenizcudzy6w3jhfyazrnn4bfqrfzcvrxd2nflncypxptgc7ueu

**Comment by liyunzhi-666** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebmcxjntejfg2qfcpouocsna6c4ic6ois5f2v4mt7zlcqqfwgyqwq 
#### Address 
> f1tb2hrxk5eaeewcesnid6xmvfkklfdrxsjr5k6iy
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1pszcrsciyixyuxxukkvtazcokexbn54amf7gvoq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebmcxjntejfg2qfcpouocsna6c4ic6ois5f2v4mt7zlcqqfwgyqwq

**Comment by kernelogic** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceabpuyhxsa2lcp36ylazbvmjzjvnpryywt7zb3ypdngqiexivfqwq 
#### Address 
> f1tb2hrxk5eaeewcesnid6xmvfkklfdrxsjr5k6iy
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### Id
> 00572ae3-657e-41fc-8fe3-b3dc9e70aeee
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceabpuyhxsa2lcp36ylazbvmjzjvnpryywt7zb3ypdngqiexivfqwq

**Comment by liyunzhi-666** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedrkzhtssejp6e2nh76wainzrzq27m7dizkofpmcg4ykptaa6ttri 
#### Address 
> f1tb2hrxk5eaeewcesnid6xmvfkklfdrxsjr5k6iy
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1pszcrsciyixyuxxukkvtazcokexbn54amf7gvoq
#### Id
> d114bbb7-ff41-4cbe-b353-c7a96805226e
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedrkzhtssejp6e2nh76wainzrzq27m7dizkofpmcg4ykptaa6ttri

**Comment by Tom-OriginStorage** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceawft4zfxsccrpevokthyj43pztuvceihk73oax5uf4cumd7b5jwa 
#### Address 
> f1tb2hrxk5eaeewcesnid6xmvfkklfdrxsjr5k6iy
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1q6bpjlqia6iemqbrdaxr2uehrhpvoju3qh4lpga
#### Id
> d114bbb7-ff41-4cbe-b353-c7a96805226e
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceawft4zfxsccrpevokthyj43pztuvceihk73oax5uf4cumd7b5jwa

**Comment by 1ane-1** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacece4i4qqo4bozkauaz7oltlnryiy22ljfpygjcr5lzbp4ma5theka 
#### Address 
> f1tb2hrxk5eaeewcesnid6xmvfkklfdrxsjr5k6iy
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1mdk7s2vntzm6hu35yuo6vjubtrpfnb2awhgvrri
#### Id
> caa0cb87-8ad3-4a64-b5e0-66c1b8704064
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacece4i4qqo4bozkauaz7oltlnryiy22ljfpygjcr5lzbp4ma5theka

**Comment by newwebgroup** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec62pee2hif6b26cfvjqurl2njf4n6btnnpekvoz7lu3fym7wtfdo 
#### Address 
> f1tb2hrxk5eaeewcesnid6xmvfkklfdrxsjr5k6iy
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1e77zuityhvvw6u2t6tb5qlnsegy2s67qs4lbbbq
#### Id
> caa0cb87-8ad3-4a64-b5e0-66c1b8704064
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec62pee2hif6b26cfvjqurl2njf4n6btnnpekvoz7lu3fym7wtfdo

**Comment by Tom-OriginStorage** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedumlafru2w2mdsoykqhbqso35i2iwtzjgacogsssn2e5wiuwxv36 
#### Address 
> f1tb2hrxk5eaeewcesnid6xmvfkklfdrxsjr5k6iy
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1q6bpjlqia6iemqbrdaxr2uehrhpvoju3qh4lpga
#### Id
> 4fb209e6-24d7-4cee-8962-f4278a8d46bd
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedumlafru2w2mdsoykqhbqso35i2iwtzjgacogsssn2e5wiuwxv36

**Comment by swatchliu** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebzujfmdpougbwtfqw6zhbzjdrce5wv3gbpt6rchijwfeqo5zpymy 
#### Address 
> f1tb2hrxk5eaeewcesnid6xmvfkklfdrxsjr5k6iy
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1yh6q3nmsg7i2sys7f7dexcuajgoweudcqj2chfi
#### Id
> 4fb209e6-24d7-4cee-8962-f4278a8d46bd
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebzujfmdpougbwtfqw6zhbzjdrce5wv3gbpt6rchijwfeqo5zpymy

**Comment by filplus-checker** [comment]
## DataCap and CID Checker Report[^1]
 - Organization: `Yisainuo`
 - Client: `f1tb2hrxk5eaeewcesnid6xmvfkklfdrxsjr5k6iy`
### Storage Provider Distribution
The below table shows the distribution of storage providers that have stored data for this client.

If this is the first time a provider takes verified deal, it will be marked as `new`.

For most of the datacap application, below restrictions should apply.
 - Storage provider should not exceed 25% of total datacap.
 - Storage provider should not be storing duplicate data for more than 20%.
 - Storage provider should have published its public IP address.
 - All storage providers should be located in different regions.

⚠️ 84.65% of total deal sealed by [f01947770](https://filfox.info/en/address/f01947770) are duplicate data.

⚠️ 80.76% of total deal sealed by [f01937995](https://filfox.info/en/address/f01937995) are duplicate data.

⚠️ 79.69% of total deal sealed by [f01952350](https://filfox.info/en/address/f01952350) are duplicate data.

⚠️ 67.39% of total deal sealed by [f01949183](https://filfox.info/en/address/f01949183) are duplicate data.

⚠️ 72.61% of total deal sealed by [f01928520](https://filfox.info/en/address/f01928520) are duplicate data.

⚠️ 50.31% of total deal sealed by [f01944347](https://filfox.info/en/address/f01944347) are duplicate data.

⚠️ 46.75% of total deal sealed by [f01922865](https://filfox.info/en/address/f01922865) are duplicate data.

⚠️ 23.17% of total deal sealed by [f01938601](https://filfox.info/en/address/f01938601) are duplicate data.

| Provider                                                    |                           Location | Total Deals Sealed | Percentage | Unique Data | Duplicate Deals |
| :---------------------------------------------------------- | ---------------------------------: | -----------------: | ---------: | ----------: | --------------: |
| [f01947770](https://filfox.info/en/address/f01947770)`new`  | Hong Kong, Central and Western, HK |        1018.19 TiB |     19.09% |  156.25 TiB |          84.65% |
| [f01937995](https://filfox.info/en/address/f01937995)`new`  | Hong Kong, Central and Western, HK |         819.63 TiB |     15.37% |  157.72 TiB |          80.76% |
| [f01952350](https://filfox.info/en/address/f01952350)`new`  |           Maywood Park, Oregon, US |         769.47 TiB |     14.43% |  156.25 TiB |          79.69% |
| [f01949183](https://filfox.info/en/address/f01949183)`new`  |           Maywood Park, Oregon, US |         718.72 TiB |     13.48% |  234.34 TiB |          67.39% |
| [f01928520](https://filfox.info/en/address/f01928520)       |           Maywood Park, Oregon, US |         683.84 TiB |     12.82% |  187.28 TiB |          72.61% |
| [f01944347](https://filfox.info/en/address/f01944347)`new`  |           Maywood Park, Oregon, US |         462.13 TiB |      8.67% |  229.63 TiB |          50.31% |
| [f01922865](https://filfox.info/en/address/f01922865)       |  Ho Chi Minh City, Ho Chi Minh, VN |         389.91 TiB |      7.31% |  207.63 TiB |          46.75% |
| [f01938601](https://filfox.info/en/address/f01938601)       |           Maywood Park, Oregon, US |         280.72 TiB |      5.26% |  215.69 TiB |          23.17% |
| [f01870888](https://filfox.info/en/address/f01870888)       |               Chengdu, Sichuan, CN |         132.91 TiB |      2.49% |  111.53 TiB |          16.08% |
| [f01915287](https://filfox.info/en/address/f01915287)       |                   Hanoi, Hanoi, VN |          55.91 TiB |      1.05% |   55.91 TiB |           0.00% |
| [f01920723](https://filfox.info/en/address/f01920723)       |           Maywood Park, Oregon, US |           1.00 TiB |      0.02% |    1.00 TiB |           0.00% |

![Provider Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/537/1671097423054.png)
### Deal Data Replication
The below table shows how each many unique data are replicated across storage providers.
- No more than 25% of unique data are stored with less than 4 providers.

⚠️ 46.08% of deals are for data replicated across less than 4 storage providers.

| Unique Data Size | Total Deals Made | Number of Providers | Deal Percentage |
| ---------------: | ---------------: | ------------------: | --------------: |
|       226.50 TiB |       936.59 TiB |                   1 |          17.56% |
|       185.13 TiB |       472.22 TiB |                   2 |           8.86% |
|       127.31 TiB |         1.02 PiB |                   3 |          19.66% |
|        78.25 TiB |       601.34 TiB |                   4 |          11.28% |
|        64.00 GiB |         2.03 TiB |                   5 |           0.04% |
|        15.84 TiB |       528.06 TiB |                   6 |           9.90% |
|        46.59 TiB |         1.70 PiB |                   7 |          32.70% |

![Replication Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/537/1671097423707.png)
### Deal Data Shared with other Clients
The below table shows how many unique data are shared with other clients.
Usually different applications owns different data and should not resolve to the same CID.

⚠️ CID sharing has been observed.

| Other Client                                                                                                                                                                                                              | Application                                                                                                                      | Total Deals Affected | Unique CIDs |          Verifier |
| :------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ | :------------------------------------------------------------------------------------------------------------------------------- | -------------------: | ----------: | ----------------: |
| [f16ioghg3qy36f6572viouwv4dqow5ejpolo4kodi](https://filfox.info/en/address/f16ioghg3qy36f6572viouwv4dqow5ejpolo4kodi)                                                                                                     | [Shenzhen kuaixue Education Development Co\., Ltd](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/512)  |             3.73 PiB |       5,084 |   LDN v3 multisig |
| [f1t3buz7oqz4fktpthqe43vauhzlnuztpgm3iyhbi](https://filfox.info/en/address/f1t3buz7oqz4fktpthqe43vauhzlnuztpgm3iyhbi)                                                                                                     | [Shenzhen kuaixue Education Development Co\., Ltd](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1363) |             2.99 PiB |       6,770 |   LDN v3 multisig |
| [f15m6qoqdsh7fn7l5amegshhvwi4gl5alb2eeuz2y](https://filfox.info/en/address/f15m6qoqdsh7fn7l5amegshhvwi4gl5alb2eeuz2y)                                                                                                     | [Worldkan](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/902)                                          |             2.22 PiB |       5,002 |   LDN v3 multisig |
| [f1unz5yuxgui573lpuh2wyxpsx5ahvw5farqb7hji](https://filfox.info/en/address/f1unz5yuxgui573lpuh2wyxpsx5ahvw5farqb7hji)                                                                                                     | `AOLIGEI`                                                                                                                        |           258.69 TiB |       5,541 |   LDN v3 multisig |
| [f3qebbkqspq4w6deouaubtngt4bmaada76uqs3omy<br/>3tki6hoeocpgxyplknev5u3oi5e7xnltobrvgxnpa<br/>3qga](https://filfox.info/en/address/f3qebbkqspq4w6deouaubtngt4bmaada76uqs3omy3tki6hoeocpgxyplknev5u3oi5e7xnltobrvgxnpa3qga) | [codex8080 \- Slingshot Restore](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/152)                    |            50.38 TiB |       1,612 |   LDN v3 multisig |
| [f126k3tkdwfaqpflgcclkiwhqxhh73ebqqazwgcoy](https://filfox.info/en/address/f126k3tkdwfaqpflgcclkiwhqxhh73ebqqazwgcoy)                                                                                                     | [New Web Group](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/356)                                     |            28.50 TiB |         910 |   LDN v3 multisig |
| [f3v7x4a2aapgx6o2r477tenoin3u5oadaeqyd7kjd<br/>sitykvf4ok7vq2utcyh34lmu5u7oybs25ff6s4dbu<br/>dpma](https://filfox.info/en/address/f3v7x4a2aapgx6o2r477tenoin3u5oadaeqyd7kjdsitykvf4ok7vq2utcyh34lmu5u7oybs25ff6s4dbudpma) | [LeoCheung \- Slingshot Restore](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/151)                    |            22.97 TiB |         735 |   LDN v3 multisig |
| [f3scxjx4k2q4gaa4glpzaayjprnhmebhajsavkzcq<br/>ix3xbvshhlxqouiftzsjo26gakixp3rfb3hdqxmtj<br/>ou5a](https://filfox.info/en/address/f3scxjx4k2q4gaa4glpzaayjprnhmebhajsavkzcqix3xbvshhlxqouiftzsjo26gakixp3rfb3hdqxmtjou5a) | ``                                                                                                                               |             1.06 TiB |          32 |          Joss Hua |
| [f1x7wsqpj6waymzzfqmu4hh32tyc4pbbqnpwy2ucq](https://filfox.info/en/address/f1x7wsqpj6waymzzfqmu4hh32tyc4pbbqnpwy2ucq)                                                                                                     | `Glif auto verified`                                                                                                             |            32.00 GiB |           1 | Jonathan Schwartz |

[^1]: To manually trigger this report, add a comment with text `checker:manualTrigger`
