### ISSUE TITLE
[DataCap Application] Hiscene

### ISSUE THREAD

**Issue by Gerald49** [filecoin-project/filecoin-plus-large-datasets#548]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Hiscene
- Website / Social Media: www.hiscene.com
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100TiB
- On-chain address for first allocation:f1dwhevm3p2slu6itmkssznscmpkpltdiztprnpya

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
HiScene focuses on researching and developing core technologies and products for augmented reality. The company is committed to be an artificial intelligence company which provides the most natural human-computer interaction and explores the deepest data value.
```

What is the primary source of funding for this project?
```
HiScene is funded by 21 investors. Qingkong Ginkgo and V Fund Management are the most recent investors.
```

What other projects/ecosystem stakeholders is this project associated with?
```
No.
```

## Use-case details

Describe the data being stored onto Filecoin
```
AR training videos.
```

Where was the data in this dataset sourced from?
```
Hiscene provides visual training solutions with core computer vision technology.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
[d1.zip](https://github.com/filecoin-project/filecoin-plus-large-datasets/files/9239943/d1.zip)
[d2.zip](https://github.com/filecoin-project/filecoin-plus-large-datasets/files/9239944/d2.zip)
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes, we confirm it.
```

What is the expected retrieval frequency for this data?
```
About once a year.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
I think we will keep it for 5 years.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Asia.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Yes, I choose offline data transfer primarily.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
I would ensure if they are credible for coorperation and their ability of actual deal recieving.
```

How will you be distributing deals across storage providers?
```
We plan having 5 SPs for deals and we may distribute deals to them for different percentage.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes.
```

**Comment by Gerald49** [comment]
@galen-mcandrew Hi, I'm waiting for 2 weeks. Can you give some respose to my issue?

**Comment by raghavrmadya** [comment]
Hi, sorry for the delay. At this stage, we need to verify your relationship(the applicant) with this company. Please share more. Additionally, please send an email stating you have applied for LDN using an official email plus a business license to filplus-app-review@fil.org

Thanks.

**Comment by raghavrmadya** [comment]
I also want to make sure you are aware of the program requirements as you mention notaries here instead of SPs. If in doubt, please refer to https://github.com/filecoin-project/filecoin-plus-large-datasets for clarification 

<img width="831" alt="Screen Shot 2022-08-21 at 5 01 20 PM" src="https://user-images.githubusercontent.com/91579519/185816870-2985f618-448a-420c-85f9-042b0612feea.png">

**Comment by Gerald49** [comment]
Ah! This is a clerical error, I meant to express that we intend to find 5 storage providers. I'm new in community, so some expressions may not be very precise. Thank you for pointing out this problem. I am in a continuous learning process! @raghavrmadya

**Comment by Gerald49** [comment]
![Hiscene](https://user-images.githubusercontent.com/107183323/186721277-75e90ad9-84eb-4bd3-a4eb-966f742afdbd.jpg)

**Comment by Gerald49** [comment]
![Hiscene](https://user-images.githubusercontent.com/107183323/186723731-d6099adb-b3f7-4b18-bf66-88ad4295ab4f.jpg)

**Comment by Gerald49** [comment]
![Hiscene](https://user-images.githubusercontent.com/107183323/186812650-44435d15-5e01-4215-9a1f-d4a122960f01.jpg)

**Comment by jessie8o8** [comment]
Hello @Gerald49. The data sample you have provided is not original content. 
![image](https://user-images.githubusercontent.com/90115194/186814318-b72fbdd5-d3c6-4058-b18c-4685958b86a7.png)

The original video can be found here: https://www.bilibili.com/video/BV1cw411o7Tj?spm_id_from=333.337.search-card.all.click

Because the data is not generated from the company as they claim, I am not confident that this organization is legitimate.

**Comment by raghavrmadya** [comment]
What's the relationship with #566

**Comment by Gerald49** [comment]
@raghavrmadya No any relationship.

**Comment by raghavrmadya** [comment]
Please respond the question about original data and also provide justification for 5 PiBs. How much data do you currently have and how many copies will you store?

**Comment by raghavrmadya** [comment]
Thanks. Please be ready and open to answer questions from notaries. I'm still not certain that you are not related to https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/566. They previously mentioned Hiscene but then they deleted it from the application. 

I will let notaries decide.

**Comment by raghavrmadya** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 100TiB

**Client address**

>f1dwhevm3p2slu6itmkssznscmpkpltdiztprnpya

**Comment by UnionLabs2020** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebi3kpurnuebuvbehqhbts6mbcxo2ckml533gpnilgjrrt4bfp6ta 
#### Address 
> f1dwhevm3p2slu6itmkssznscmpkpltdiztprnpya
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f17xdri3wunqgld7dm23e4f3eqsntjakwc47xjo6i
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebi3kpurnuebuvbehqhbts6mbcxo2ckml533gpnilgjrrt4bfp6ta

**Comment by MetaWaveInfo** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecat2jhvlet3launyrvs3vjrindkkja7spwca6zpbsspu6jy2pef6 
#### Address 
> f1dwhevm3p2slu6itmkssznscmpkpltdiztprnpya
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1ktlkcxnmzxcdaoqfsunrg3vocfbmgv4n3mrn74a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecat2jhvlet3launyrvs3vjrindkkja7spwca6zpbsspu6jy2pef6

**Comment by BigD-Exchange** [comment]
@Gerald49 Hi! Great to see you have gotten approval for DataCap. If you are looking for more storage providers to store these data or have any questions, please visit #bigdata-exchange on Filecoin Slack or reply here. 

We have strong demand from a diverse group of SPs, who are actively looking to onboard more data.

**Comment by swatchliu** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecfp22guzzate4tuh7vwhkxs25z5iy5lzuyrfd5thlgixcyxi7fwy 
#### Address 
> f1dwhevm3p2slu6itmkssznscmpkpltdiztprnpya
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1yh6q3nmsg7i2sys7f7dexcuajgoweudcqj2chfi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecfp22guzzate4tuh7vwhkxs25z5iy5lzuyrfd5thlgixcyxi7fwy

**Comment by PluskitOfficial** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecof7ko2kubzr4txaxp3npofoa5e7nskkylaonohiy6njy63do6su 
#### Address 
> f1dwhevm3p2slu6itmkssznscmpkpltdiztprnpya
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1tgnlhtcmhwipfm7thsftxhn5k52velyjlazpvka
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecof7ko2kubzr4txaxp3npofoa5e7nskkylaonohiy6njy63do6su

**Comment by MatrixStorage** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaeiwlkvqodnye3y7pnihe6x55m3kgivxyrynw5bmp6kw3jageb4g 
#### Address 
> f1dwhevm3p2slu6itmkssznscmpkpltdiztprnpya
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1tbxqwjxfyv7swsdin4einirlsfquv3vnmlapley
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaeiwlkvqodnye3y7pnihe6x55m3kgivxyrynw5bmp6kw3jageb4g

**Comment by MetaWaveInfo** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebpl35aofq4gsx2o7v6v26myoiulev6z24opimvmtkqpkfxqher3i 
#### Address 
> f1dwhevm3p2slu6itmkssznscmpkpltdiztprnpya
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1ktlkcxnmzxcdaoqfsunrg3vocfbmgv4n3mrn74a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebpl35aofq4gsx2o7v6v26myoiulev6z24opimvmtkqpkfxqher3i

**Comment by PluskitOfficial** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb32uyww7w526rnrt426ng3twmxgcktdmxgufge2vhowxfcw4nn4q 
#### Address 
> f1dwhevm3p2slu6itmkssznscmpkpltdiztprnpya
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1tgnlhtcmhwipfm7thsftxhn5k52velyjlazpvka
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb32uyww7w526rnrt426ng3twmxgcktdmxgufge2vhowxfcw4nn4q

**Comment by UnionLabs2020** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec5umcwechpy3p2go3y23chamydb26tjjzhjoqm2t2vtek7t63eaa 
#### Address 
> f1dwhevm3p2slu6itmkssznscmpkpltdiztprnpya
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f17xdri3wunqgld7dm23e4f3eqsntjakwc47xjo6i
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec5umcwechpy3p2go3y23chamydb26tjjzhjoqm2t2vtek7t63eaa

**Comment by swatchliu** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecbncaxbgvacsltzfmmwv7yj6ipjmthx7ev2uzoevzt74xc5adtp6 
#### Address 
> f1dwhevm3p2slu6itmkssznscmpkpltdiztprnpya
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1yh6q3nmsg7i2sys7f7dexcuajgoweudcqj2chfi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecbncaxbgvacsltzfmmwv7yj6ipjmthx7ev2uzoevzt74xc5adtp6

**Comment by 1475Notary** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebszekmkjrnn6ihc7wv7dtopwqbbxyc4hh4o3cg7wepnbz3faml5g 
#### Address 
> f1dwhevm3p2slu6itmkssznscmpkpltdiztprnpya
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1ofq4mngy7ggcp755pfquq2gphjjnlydolf6awtq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebszekmkjrnn6ihc7wv7dtopwqbbxyc4hh4o3cg7wepnbz3faml5g

**Comment by PluskitOfficial** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceautdca7pxary2lmmhfufwhklzky2qlifdw6jtcvxcxl6razwld6i 
#### Address 
> f1dwhevm3p2slu6itmkssznscmpkpltdiztprnpya
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1tgnlhtcmhwipfm7thsftxhn5k52velyjlazpvka
#### Id
> 33782efb-06a4-40d4-ab92-2fab08359510
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceautdca7pxary2lmmhfufwhklzky2qlifdw6jtcvxcxl6razwld6i

**Comment by filplus-checker** [comment]
## DataCap and CID Checker Report[^1]
 - Organization: `Hiscene`
 - Client: `f1dwhevm3p2slu6itmkssznscmpkpltdiztprnpya`
### Storage Provider Distribution
The below table shows the distribution of storage providers that have stored data for this client.

If this is the first time a provider takes verified deal, it will be marked as `new`.

For most of the datacap application, below restrictions should apply.
 - Storage provider should not exceed 25% of total datacap.
 - Storage provider should not be storing duplicate data for more than 20%.
 - Storage provider should have published its public IP address.
 - All storage providers should be located in different regions.

⚠️ 76.85% of total deal sealed by [f01926585](https://filfox.info/en/address/f01926585) are duplicate data.

⚠️ 81.33% of total deal sealed by [f01832632](https://filfox.info/en/address/f01832632) are duplicate data.

⚠️ 80.92% of total deal sealed by [f01828096](https://filfox.info/en/address/f01828096) are duplicate data.

⚠️ 79.30% of total deal sealed by [f01937964](https://filfox.info/en/address/f01937964) are duplicate data.

⚠️ 76.95% of total deal sealed by [f01926914](https://filfox.info/en/address/f01926914) are duplicate data.

⚠️ 78.48% of total deal sealed by [f01926802](https://filfox.info/en/address/f01926802) are duplicate data.

⚠️ 70.97% of total deal sealed by [f01924416](https://filfox.info/en/address/f01924416) are duplicate data.

⚠️ 72.20% of total deal sealed by [f01924350](https://filfox.info/en/address/f01924350) are duplicate data.

⚠️ 71.55% of total deal sealed by [f01924325](https://filfox.info/en/address/f01924325) are duplicate data.

⚠️ 47.06% of total deal sealed by [f01844999](https://filfox.info/en/address/f01844999) are duplicate data.

⚠️ [f01844999](https://filfox.info/en/address/f01844999) has unknown IP location.

⚠️ 75.70% of total deal sealed by [f01889480](https://filfox.info/en/address/f01889480) are duplicate data.

| Provider                                              |                 Location | Total Deals Sealed | Percentage | Unique Data | Duplicate Deals |
| :---------------------------------------------------- | -----------------------: | -----------------: | ---------: | ----------: | --------------: |
| [f01926585](https://filfox.info/en/address/f01926585) |    Ashburn, Virginia, US |         271.25 TiB |     11.85% |   62.78 TiB |          76.85% |
| [f01832632](https://filfox.info/en/address/f01832632) | San Jose, California, US |         249.38 TiB |     10.89% |   46.56 TiB |          81.33% |
| [f01828096](https://filfox.info/en/address/f01828096) | San Jose, California, US |         247.38 TiB |     10.81% |   47.19 TiB |          80.92% |
| [f01937964](https://filfox.info/en/address/f01937964) |         Tokyo, Tokyo, JP |         247.00 TiB |     10.79% |   51.13 TiB |          79.30% |
| [f01926914](https://filfox.info/en/address/f01926914) |    Ashburn, Virginia, US |         239.97 TiB |     10.48% |   55.31 TiB |          76.95% |
| [f01926802](https://filfox.info/en/address/f01926802) |    Ashburn, Virginia, US |         233.75 TiB |     10.21% |   50.31 TiB |          78.48% |
| [f01924416](https://filfox.info/en/address/f01924416) | Singapore, Singapore, SG |         170.81 TiB |      7.46% |   49.59 TiB |          70.97% |
| [f01924350](https://filfox.info/en/address/f01924350) | Singapore, Singapore, SG |         169.19 TiB |      7.39% |   47.03 TiB |          72.20% |
| [f01924325](https://filfox.info/en/address/f01924325) | Singapore, Singapore, SG |         168.94 TiB |      7.38% |   48.06 TiB |          71.55% |
| [f01844999](https://filfox.info/en/address/f01844999) |                  Unknown |          89.97 TiB |      3.93% |   47.63 TiB |          47.06% |
| [f01889480](https://filfox.info/en/address/f01889480) |     Boardman, Oregon, US |          51.69 TiB |      2.26% |   12.56 TiB |          75.70% |
| [f01917214](https://filfox.info/en/address/f01917214) |         Seoul, Seoul, KR |          38.00 TiB |      1.66% |   38.00 TiB |           0.00% |
| [f01917236](https://filfox.info/en/address/f01917236) |         Seoul, Seoul, KR |          37.97 TiB |      1.66% |   37.97 TiB |           0.00% |
| [f01917208](https://filfox.info/en/address/f01917208) |         Seoul, Seoul, KR |          37.00 TiB |      1.62% |   37.00 TiB |           0.00% |
| [f01916487](https://filfox.info/en/address/f01916487) |         Seoul, Seoul, KR |          36.94 TiB |      1.61% |   30.91 TiB |          16.33% |

![Provider Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/548/1671097508168.png)
### Deal Data Replication
The below table shows how each many unique data are replicated across storage providers.
- No more than 25% of unique data are stored with less than 4 providers.

⚠️ 100.00% of deals are for data replicated across less than 4 storage providers.

| Unique Data Size | Total Deals Made | Number of Providers | Deal Percentage |
| ---------------: | ---------------: | ------------------: | --------------: |
|       325.22 TiB |       940.91 TiB |                   1 |          41.10% |
|        89.19 TiB |       825.03 TiB |                   2 |          36.04% |
|        52.81 TiB |       523.28 TiB |                   3 |          22.86% |

![Replication Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/548/1671097508937.png)
### Deal Data Shared with other Clients
The below table shows how many unique data are shared with other clients.
Usually different applications owns different data and should not resolve to the same CID.

⚠️ CID sharing has been observed.

| Other Client                                                                                                          | Application                                                                                                                | Total Deals Affected | Unique CIDs |                                                                                 Verifier |
| :-------------------------------------------------------------------------------------------------------------------- | :------------------------------------------------------------------------------------------------------------------------- | -------------------: | ----------: | ---------------------------------------------------------------------------------------: |
| [f1xtnkj5ti77f5gbzhclnpj3xt6e5dwhfzive2yca](https://filfox.info/en/address/f1xtnkj5ti77f5gbzhclnpj3xt6e5dwhfzive2yca) | [Beacon Project](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/482)                              |           260.06 TiB |         724 | Project Beacon, 12 LDNs LDN # 444, 446, 447, 448, 474, 475, 476, 477, 479, 480, 481, 482 |
| [f1dx7ljly4vmk5x2bn5ng4jpbqnuvozrz2phw42qy](https://filfox.info/en/address/f1dx7ljly4vmk5x2bn5ng4jpbqnuvozrz2phw42qy) | [CoinPhD](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/364)                                     |           110.66 TiB |       1,317 |                                                                          LDN v3 multisig |
| [f1ki4cjk27ypzjsuzkvvqzs6xobaweuoxfdcnpqhy](https://filfox.info/en/address/f1ki4cjk27ypzjsuzkvvqzs6xobaweuoxfdcnpqhy) | [TimeQuant](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/385)                                   |           107.44 TiB |       1,323 |                                                                          LDN v3 multisig |
| [f1ivsvpljx4ovp2tth73pllkxmumrudemks623iia](https://filfox.info/en/address/f1ivsvpljx4ovp2tth73pllkxmumrudemks623iia) | `TIS Inc. group`                                                                                                           |           105.38 TiB |         606 |                                                                          LDN v3 multisig |
| [f1einobkrjcjk6gfc5ov6663vrri75hwdsjfs6pmq](https://filfox.info/en/address/f1einobkrjcjk6gfc5ov6663vrri75hwdsjfs6pmq) | [Cansoti](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/640)                                     |            92.94 TiB |         594 |                                                                          LDN v3 multisig |
| [f1tgii4xgcp6um4n2w7eqaw6bwvnvyii2u7cjgzka](https://filfox.info/en/address/f1tgii4xgcp6um4n2w7eqaw6bwvnvyii2u7cjgzka) | [Meson\.Network ](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/187)                             |            77.44 TiB |         249 |                                                                          LDN v3 multisig |
| [f1vtcetpapwwyka6txwqjwymsa67npdfilbkwh64a](https://filfox.info/en/address/f1vtcetpapwwyka6txwqjwymsa67npdfilbkwh64a) | [Chimay](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/397)                                      |            61.59 TiB |         655 |                                                                          LDN v3 multisig |
| [f1727w2vwjctfo7hflr5trgqkl3c7texh7pl4grzq](https://filfox.info/en/address/f1727w2vwjctfo7hflr5trgqkl3c7texh7pl4grzq) | [GMverse](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/365)                                     |            57.22 TiB |         664 |                                                                          LDN v3 multisig |
| [f17qd6x3leh5pa7vh6ewdaed7qhbn2mgofrokuayy](https://filfox.info/en/address/f17qd6x3leh5pa7vh6ewdaed7qhbn2mgofrokuayy) | [Drust](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/427)                                       |            56.91 TiB |         927 |                                                                          LDN v3 multisig |
| [f1quofpadzcqlonmz7v3mv7dfqvm5hdztucdsjqsy](https://filfox.info/en/address/f1quofpadzcqlonmz7v3mv7dfqvm5hdztucdsjqsy) | [HENAN 863 SOFTWARE CO\., LTD](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/468)                |            54.31 TiB |         721 |                                                                          LDN v3 multisig |
| [f1f5edx6ofn3lf6rk3yfpldbi2pzgq2egoyu6ubpi](https://filfox.info/en/address/f1f5edx6ofn3lf6rk3yfpldbi2pzgq2egoyu6ubpi) | [Samdata Trade](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/382)                               |            42.03 TiB |         605 |                                                                          LDN v3 multisig |
| [f1avhqgmeazxzvylz34l26o3nlj2ywnzaviwns3dq](https://filfox.info/en/address/f1avhqgmeazxzvylz34l26o3nlj2ywnzaviwns3dq) | [87v5\-CarsonVideo](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/392)                           |            40.25 TiB |         257 |                                                                          LDN v3 multisig |
| [f1jdmx2cuswzjlt4pnsv3t7ipmesywzxsg6q56a2a](https://filfox.info/en/address/f1jdmx2cuswzjlt4pnsv3t7ipmesywzxsg6q56a2a) | [Raysun Radar Electronic Technology Co\.,Ltd](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/884) |            33.88 TiB |         250 |                                                                          LDN v3 multisig |
| [f1ajdk7e6ex7fvtjtydzgys47bcg7jub2baucun7y](https://filfox.info/en/address/f1ajdk7e6ex7fvtjtydzgys47bcg7jub2baucun7y) | [Ruikuyun Information Technology Co\., Ltd](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/529)   |            24.69 TiB |         214 |                                                                          LDN v3 multisig |
| [f14abwn2goturifmt27s2bssoe3fup2b3npkgfzui](https://filfox.info/en/address/f14abwn2goturifmt27s2bssoe3fup2b3npkgfzui) | [KONGFU VR](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/372)                                   |            13.66 TiB |         278 |                                                                          LDN v3 multisig |
| [f1rnwp6p5kx7pcwexpucoav6mmwz3rkxw5blrboyy](https://filfox.info/en/address/f1rnwp6p5kx7pcwexpucoav6mmwz3rkxw5blrboyy) | [MigoVideo](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/517)                                   |            13.28 TiB |         127 |                                                                          LDN v3 multisig |
| [f1zav4f4rak2yvbrq357z3whj224wn4dipl7eiesy](https://filfox.info/en/address/f1zav4f4rak2yvbrq357z3whj224wn4dipl7eiesy) | [Shanghai Zhixun](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/628)                             |            12.72 TiB |          93 |                                                                          LDN v3 multisig |
| [f1mn5mw2dpqz6p3s7vxrlkhkh3okdtc6t7wqro4xa](https://filfox.info/en/address/f1mn5mw2dpqz6p3s7vxrlkhkh3okdtc6t7wqro4xa) | [Unisound](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/577)                                    |             1.53 TiB |          11 |                                                                          LDN v3 multisig |
| [f1zb6pgkktdbyy7zxfob6gripqxuc25ukf35cc7fq](https://filfox.info/en/address/f1zb6pgkktdbyy7zxfob6gripqxuc25ukf35cc7fq) | `Maxpic PhotoGraphic Studio`                                                                                               |             1.19 TiB |           6 |                                                                          LDN v3 multisig |
| [f1ffbtksiso5za73pypuxbxznng6rdv64nbihdtba](https://filfox.info/en/address/f1ffbtksiso5za73pypuxbxznng6rdv64nbihdtba) | [EpikProtocol](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/281)                                |            64.00 GiB |           1 |                                                                                LDN # 281 |

[^1]: To manually trigger this report, add a comment with text `checker:manualTrigger`
