### ISSUE TITLE
[DataCap Application] Heilongjiang Gao Xian Wine Co.

### ISSUE THREAD

**Issue by GaoXianWine** [filecoin-project/filecoin-plus-large-datasets#554]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Heilongjiang Gao Xian Wine Co.
- Website / Social Media:http://www.jsdl9968.com/com/gxjyy/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):160TiB
- On-chain address for first allocation: f1iyebuoahhesordxqzswcxpfub2ap4zafdfckzsa

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
The company was founded in 1909 under the original name of "De Yu Heng Boiling Pot" and was a brewery named after a person in Heilongjiang Province.
In 1982, the company registered the trademark "Gao Xian". The site is located in the government seat of Huizi Town, Wangkui County, Suihua City, Heilongjiang Province, and was expanded in 2008, with all the factory premises being built in an antique style. It covers an area of 20,000 square meters and has a building area of 8,500 square meters. With a registered capital of 5 million yuan, the factory now has fixed assets of 45 million yuan.
```

What is the primary source of funding for this project?
```
From the sale of white wine products
```

What other projects/ecosystem stakeholders is this project associated with?
```
no
```

## Use-case details

Describe the data being stored onto Filecoin
```
Learning materials related to white wine
Promotional video for white wine
```

Where was the data in this dataset sourced from?
```
These figures come from our trainers and the company's communications department
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
yes，https://drive.google.com/drive/folders/1EqUNdVLmKV00IHJjWFtRu3ZaDab6O1zC?usp=sharing
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes, this is a public dataset.
```

What is the expected retrieval frequency for this data?
```
This is only a part of the data we back up and is expected to be retrieved every 1-2 years.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
10 years at least
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
We would like to store it all over the world
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Both online and offline.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
I would choose a large data storage company to ensure that there are no problems in terms of technology and post-use.
```

How will you be distributing deals across storage providers?
```
We will follow the filecoin rules for storage allocation and will allocate DataCap to as many storage providers as possible.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
We have sufficient funds and storage needs and hope that the community will quickly approve my application and work together to promote permanent storage
```

**Comment by raghavrmadya** [comment]
What's your relationship with the client? Are you an executive at Heilongjiang Gao Xian Wine Co.? Please provide further justification for 5 PiBs request and more samples as we cannot feel confident with the current data sample

**Comment by raghavrmadya** [comment]
Please send an email from your official company email to filplus-app-review@fil.org as well as company registration info for review and KYC purposes. 
--

**Comment by GaoXianWine** [comment]
> 



> 您和客户是什么关系？您是黑龙江高酒业公司的贤才吗？请为 5 PiB 请求和更多样本提供更进一步的原因，因为我们对当前的数据样本没有自信心

Hello, we are a liquor group. We have our own brand - Gao Xian Liquor. We produce our own liquor and sell it to our agents and customers. Also, we cooperate with many distilleries and are their regional agents and recruit other regional agents.
I am an executive in the company and I am the head of the planning department of the company, mainly responsible for the design and production of promotional materials for the products.
The data we store is mainly information on original, first draft and finished products of product design, various videos and videos of company activities, and daily surveillance videos of the company. Our company has been established for 9 years and has generated a large amount of data. In the past, a lot of data has been lost due to improper preservation. There is also a lot of data that had to be deleted because of high preservation costs, so we would like to preserve data and information at a lower cost, so we would like to apply for 5PiB of storage space.
Another question I have is that I always thought filcoin is a more open network than web 2.0, but I am wondering why it takes so much process and time to apply for storage quota now?

**Comment by GaoXianWine** [comment]
> ## 请从您的官方公司电子邮件中发送电子邮件至[filplus-app-review@fil.org](mailto:filplus-app-review@fil.org)以及公司注册信息，以供审核和 KYC 使用。
Hello, our confirmation email has been sent via official email, please check it. Thank you for your support and as one of the pre-filcoin participants, we are excited to continue to be a part of the ongoing construction of the project.
By the way, I think applying for a real storage credit should be simple and fast so as to attract more companies to participate.

**Comment by GaoXianWine** [comment]
> ## 请从您的官方公司电子邮件中发送电子邮件至[filplus-app-review@fil.org](mailto:filplus-app-review@fil.org)以及公司注册信息，以供审核和 KYC 使用。
Hello, our confirmation email has been sent for 4 days. Have you received it？
<img width="654" alt="image" src="https://user-images.githubusercontent.com/110466982/184857306-7d20ae0a-1548-4d85-8608-348b541b8a5f.png">

**Comment by GaoXianWine** [comment]
> 你好，你今天有多少数据？5 PiB 是用于教育视频的大量数据，我们不能预先提供 DataCap 以供将来使用。请申请您今天需要的确切金额，当您有更多数据时需要再次申请。如果您有 5 PiB 的数据，请提供证据。
> 
> 这需要时间，因为许多人滥用该系统，而防止此类滥用是我们的工作。
Ok, I see. The exact amount I currently need is 1.5PiB. I have felt your serious and responsible and quick response, so I don't need to worry about not being able to pass quickly in future applications. So I applied for 1.5P today, and I need to apply again later.

**Comment by GaoXianWine** [comment]
> 你提到你在存储公司的日常监控视频，公开数据如何？你能辩解吗？对我来说，这听起来像是私人数据。@raghavrmadya这闻起来很腥

The video of the warehouse can be made public, but the monitoring of the assembly line and the monitoring of the intersection cannot be made public.

**Comment by raghavrmadya** [comment]
Thank you for your response. In that case, this application would qualify for an LDN exception where you would need 5 noatries' support to move forward. 

The other option is not storing the the monitoring of the assembly line and the monitoring of the intersection which would likely change the amount of DC requested. Please open a new application as your response below is no longer valid. Please link this application in the new application so we don't have to do the KYC from start and we can move quickly. 

Appreciate your quick responses and look forward to welcoming you to the Filecoin network as a client. If you have questions about getting notary support, you can drop a message here - https://filecoinproject.slack.com/archives/C036JKD8NVA 

Thank you.  <img width="859" alt="Screen Shot 2022-08-21 at 5 04 32 PM" src="https://user-images.githubusercontent.com/91579519/185817001-b1efbdba-7a42-40b3-ae73-9c0d936b342e.png">

**Comment by GaoXianWine** [comment]
> Thank you for your response. In that case, this application would qualify for an LDN exception where you would need 5 noatries' support to move forward.
> 
> The other option is not storing the the monitoring of the assembly line and the monitoring of the intersection which would likely change the amount of DC requested. Please open a new application as your response below is no longer valid. Please link this application in the new application so we don't have to do the KYC from start and we can move quickly.
> 
> Appreciate your quick responses and look forward to welcoming you to the Filecoin network as a client. If you have questions about getting notary support, you can drop a message here - https://filecoinproject.slack.com/archives/C036JKD8NVA
> 
> Thank you. <img alt="Screen Shot 2022-08-21 at 5 04 32 PM" width="859" src="https://user-images.githubusercontent.com/91579519/185817001-b1efbdba-7a42-40b3-ae73-9c0d936b342e.png">

according to your request, I modified the number of DCs and created a new application, please help me to see if there is anything else wrong, thanks! I hope this will go through.

**Comment by GaoXianWine** [comment]
@raghavrmadya
