### ISSUE TITLE
[DataCap Application] L&M design lab-Shanghai Limu architectural planning and Design Co., Ltd

### ISSUE THREAD

**Issue by LMdesignlab** [filecoin-project/filecoin-plus-large-datasets#565]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: L&M design lab （Shanghai Limu architectural planning and Design Co., Ltd）上海立木建筑规划设计有限公司
- Website / Social Media:https://www.limu.design/
<img width="586" alt="image" src="https://user-images.githubusercontent.com/110532309/182577274-a69fda13-e012-47d4-93cb-2ac1e7436752.png">

- Total amount of DataCap being requested (between 500 TiB and 5 PiB):5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):200TiB
- On-chain address for first allocation:f15cmd7mpswrjpbagpbi233cr3ydauvmi2dbziyla
_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
LiveMore was first suggested by the owner Ms. Zhang Xiaoqing in 2018, which can be literally translated as "more life", but it is obviously not what existed in our values at that time, "more life"? No, we need to "work more", explore the boundary between creativity and technology, and make the designs all over the world.
The epidemic has changed the world. The two years 2020-2021 are not only the instantaneous deceleration of the global ties we used to be familiar with, but also the last Carnival of high growth in the world. The Spring Festival in 2022 is particularly quiet, but all kinds of clues are showing that the era of 996 is coming to an end. Starting from this year, people will increasingly recognize local values and return to the origin of life. Driven by this feeling, we decided to restart this wonderful journey called atelier LiveMore.
Atelier LiveMore is an advanced customized studio dedicated to exploring space art and life aesthetics. Exploring the meaning of life is easy to move towards emptiness, but it is relatively easy to grasp the anchor point of life - children and pets, who bring people the most happiness after tired work, and their real needs are often neglected in space art. Our deep accumulation in the field of children and pets enables design to surpass art and aesthetics and truly serve all users.We design homes for all kinds of people. Some homes are as small as 13 steps, and others are as big as a luxury resort hotel. There are adults, children, cats and dogs in these homes. These lives are simple, or rich, or soup, water, or daily necessities. However, regardless of space geometry, we all want to be closer to nature, closer to truth and closer to happiness. Perhaps this is the value that LiveMore wants to convey.

What is LiveMore? 
Life is elsewhere, 
life is everywhere.
```
<img width="1335" alt="image" src="https://user-images.githubusercontent.com/110532309/182582271-c7652b04-5a82-421c-9d1e-bc7b3526db29.png">

<img width="1356" alt="image" src="https://user-images.githubusercontent.com/110532309/182582415-738b7d0b-4c3a-4f83-a3e5-e31612ece0ed.png">

<img width="1315" alt="image" src="https://user-images.githubusercontent.com/110532309/182582451-e96a44a1-e118-4316-9a6e-8b5b0dcbb0cb.png">

What is the primary source of funding for this project?
```
L&M design lab.
```

What other projects/ecosystem stakeholders is this project associated with?
```
L&M design lab and our business customers.
```

## Use-case details

Describe the data being stored onto Filecoin
```
From our project data.
```

Where was the data in this dataset sourced from?
```
Project data
design scheme
Project design drawing
Design rendering
Rendering video of renderings
Relevant image data after the completion of the project.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://drive.google.com/drive/folders/1fYlL2u6pMAMCEZEm0Lh7ywW48kotBgNw?usp=sharing
https://www.limu.design/yunshe/index

```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes, we hope more people can see our design works.
```

What is the expected retrieval frequency for this data?
```
Once a year.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
Hope to keep it forever.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Asia.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Both online and offline transmission are supported, depending on the requirements of each sp.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
1. If it is an SP in China, we will conduct KYC audit on the SP and judge the legality and compliance of the sp
2. We will pay attention to the operating experience of sp. if they have rich experience, they will become bonus items.
3. SP needs to support retrieval
```

How will you be distributing deals across storage providers?
```
Distribute under filplus rules.
And try to make the SPS more dispersed. Choose different SPS in multiple regions for backup, with 5-8 copies
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
We are ready to store funds.
```

**Comment by raghavrmadya** [comment]
Unable to certain legitmacy using the current website. Please send an email from an official account, not limuarch@163.com

**Comment by raghavrmadya** [comment]
How long have you been in operation? Many projects listed on your website show other firms as lead architects with further investigation. Please provide evidence for at least 3 projects listed on your site that you have delivered and associated data samples.

**Comment by LMdesignlab** [comment]
Hello @raghavrmadya 
Thank you for your reply

On the first question
> The foreign business e-mail that our company has been using is:“ _limuarch@163.com_ ”, you can see this through our website and social media account.
> <img width="481" alt="image" src="https://user-images.githubusercontent.com/110532309/184122106-f54b372e-c59a-44e0-a9f9-8ad73078c40d.png">

I don't quite understand what you mean about this part，Maybe you can get some answers through this link.
_https://www.gooood.cn/company/limu-design-studio?lang=cn_
> How long have you been in operation? Many projects listed on your website show other firms as lead architects with further investigation. Please provide evidence for at least 3 projects listed on your site that you have delivered and associated data samples.


**1.  2021-Convenience store in Beijing**
> <img width="696" alt="image" src="https://user-images.githubusercontent.com/110532309/184123803-66bfa4ae-ad0e-4e43-b335-8849ae831f60.png">
> For some data about this project, you can see the details through this link.There are some planning plans, design drawings, effect rendering drawings and final photos of the project.

**2. 2018-Stage over the Landscape, Neobay Administrative Service Center**
<img width="1441" alt="image" src="https://user-images.githubusercontent.com/110532309/184125372-be4d9316-e955-404b-88b2-f36c9e33d608.png">

https://drive.google.com/drive/folders/19oC9DNsM9PSHfXRN14dJMOFEKgL6XL6l?usp=sharing

**Comment by Sunnyiscoming** [comment]
https://aiqicha.baidu.com/detail/compinfo?pid=xlTM-TogKuTwMR1ObcPsq*vTgWtCeYAdkQmd&rq=ef&pd=ee&from=ps
Is this link related with your organization?

**Comment by LMdesignlab** [comment]
@Sunnyiscoming  
The organization shown in this link is our company

**Comment by raghavrmadya** [comment]
Data samples only have press releases. Please share 5 examples each of - 
Project data
design scheme
Project design drawing
Design rendering
Rendering video of renderings
Relevant image data after the completion of the project.

**Comment by LMdesignlab** [comment]
Hi Sir @raghavrmadya 
Thank you for your reply
We have prepared information related to 5 project cases, please check
> **Tip:** because what we share is the link to the network disk in China, you may not be able to open it.
> However, we are talking about uploading the data to Google cloud disk for inspection

链接: https://pan.baidu.com/s/1D38ysmsvtnv9kAopKN6gUg 提取码: 9vc7 复制这段内容后打开百度网盘手机App，操作更方便哦

It is worth adding that we are also in contact with many SP technology service providers. Because we are engaged in traditional industries, we need more complete technical service solutions to store data in filecoin with their help.
Including great heat, new web group, origin storage, etc
Some SPS we are docking are:
f090387
f01609999 
f01658888
f0149768
f019362
f066104
f0469055
f01128206

**Comment by LMdesignlab** [comment]
https://drive.google.com/drive/folders/1JPvcQhKJxx9xav0U3nFLoN5KYxJXl_Wq?usp=sharing

**Comment by raghavrmadya** [comment]
Your data samples still word files and jpg. 5 PiBs is a LOT of data and I don't have enough confidence that you have that much data. That said, I will let notaries decide.

**Comment by raghavrmadya** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 200TiB

**Client address**

>f15cmd7mpswrjpbagpbi233cr3ydauvmi2dbziyla

**Comment by raghavrmadya** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 200TiB

**Client address**

>f15cmd7mpswrjpbagpbi233cr3ydauvmi2dbziyla

**Comment by newwebgroup** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedvyu6tefzyy26p4ce5arsykbdvz73izy3r36f5lz4vnkgzorxxw2 
#### Address 
> f15cmd7mpswrjpbagpbi233cr3ydauvmi2dbziyla
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1e77zuityhvvw6u2t6tb5qlnsegy2s67qs4lbbbq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedvyu6tefzyy26p4ce5arsykbdvz73izy3r36f5lz4vnkgzorxxw2

**Comment by Tom-OriginStorage** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecrv5ltuyg36c4kzla7khbmgheimm7c6e5c5lvyxucdtv5v3uwxmm 
#### Address 
> f15cmd7mpswrjpbagpbi233cr3ydauvmi2dbziyla
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1q6bpjlqia6iemqbrdaxr2uehrhpvoju3qh4lpga
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecrv5ltuyg36c4kzla7khbmgheimm7c6e5c5lvyxucdtv5v3uwxmm

**Comment by kernelogic** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceadjsyfvkl6c7mdns7f5nerd5rdd27n5wenrosjwc6qembdecyyss 
#### Address 
> f15cmd7mpswrjpbagpbi233cr3ydauvmi2dbziyla
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### Id
> f1519137-196d-4eb3-9f07-3348cf6c07e5
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceadjsyfvkl6c7mdns7f5nerd5rdd27n5wenrosjwc6qembdecyyss

**Comment by kernelogic** [comment]
Early stage of allocation. Checker bot looks OK.

**Comment by YuanHeHK** [comment]
There is no problem with the number of SPs and data checks, but your data is too centralized, which is not in line with the filecoin principle. I will support you this time, but you need to adjust the subsequent packaging to ensure that the data is evenly distributed. In addition, there are 64 data sharing, which is very small and seems to be negligible operational errors.

**Comment by YuanHeHK** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacea4rx5brvlmkikur7r32doelz46s3pvdyasdgb55ptrxheqsqwcmi 
#### Address 
> f15cmd7mpswrjpbagpbi233cr3ydauvmi2dbziyla
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1fg6jkxsr3twfnyhdlatmq36xca6sshptscds7xa
#### Id
> f1519137-196d-4eb3-9f07-3348cf6c07e5
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacea4rx5brvlmkikur7r32doelz46s3pvdyasdgb55ptrxheqsqwcmi

**Comment by Tom-OriginStorage** [comment]
checker:manualTrigger

**Comment by Tom-OriginStorage** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec3pgww6qmf43dxluxuyll6xmkqcnpexgco7wfesumleu2hyircuc 
#### Address 
> f15cmd7mpswrjpbagpbi233cr3ydauvmi2dbziyla
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1q6bpjlqia6iemqbrdaxr2uehrhpvoju3qh4lpga
#### Id
> 0da82a1e-aec7-4ddb-8b07-869ef0981244
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec3pgww6qmf43dxluxuyll6xmkqcnpexgco7wfesumleu2hyircuc

**Comment by LMdesignlab** [comment]
Thank you for your signature support, Notary Public

About CID Sharing
Sorry, this is due to operational errors. We have made corrections, and the sharing situation has not spread further.
About SP dispersion improvement
We plan to add 3 - 5 SPs in the next two rounds to make the data more dispersed.

**Comment by 1ane-1** [comment]
I checked Github's history and CID Checker's conclusions, and it looks ok.
The Client has already explained some problems, and the Client said that it will continue to optimize, so it is willing to support this round.

**Comment by 1ane-1** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced7hr4trk2vr3fket7col2qk76q6umqex7niwqhhoaivkkh7gmn6e 
#### Address 
> f15cmd7mpswrjpbagpbi233cr3ydauvmi2dbziyla
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1mdk7s2vntzm6hu35yuo6vjubtrpfnb2awhgvrri
#### Id
> 0da82a1e-aec7-4ddb-8b07-869ef0981244
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced7hr4trk2vr3fket7col2qk76q6umqex7niwqhhoaivkkh7gmn6e

**Comment by herrehesse** [comment]
Dear Applicant,

Due to the increased amount of erroneous/wrong Filecoin+ data recently, on behalf of the entire community, we feel compelled to go deeper into datacap requests. Hereby to ensure that the overall value of the Filecoin network and Filecoin+ program increases and is not abused.

Please answer the questions below as comprehensively as possible.

**Customer data**

- Could you demonstrate exactly how and to what extent customer contact occurred? 

We expect that for the onboarding of customers with the scale of an LDN there would have been at least multiple email and perhaps several chat conversations preceding it. A single email with an agreement does not qualify here.

- Did the customer specify the amount of data involved in this relevant correspondence?

- Why does the customer in question want to use the Filecoin+ program? 

_Should this only be soley for acquiring datacap this is of course **out of the question**. The customer must have a legitimate reason for wanting to use the Filecoin+ program which is intended as a program to store useful and public datasets on the network._ 

- Why is the customer data considered Filecoin+ eligible?

_(As an intermediate solution Filecoin offers the FIL-E program or the glif.io website for business datasets that do not meet the requirements for a Filecoin+ dataset)_


**Files and Processing**

- Could you please demonstrate to us how you envision processing and transporting the customer data in question to any location for preparation?
- Would you demonstrate to us that the customer, the preparer and the intended storage providers all have adequate bandwidth to process the set with its corresponding size?
- Would you tell us how the data set preparer takes into account the prevention of duplicates in order to prevent data cap abuse?


Hopefully you understand the caution the overall community has for onboarding the wrong data. We understand the increased need for Filecoin+, however, we must not allow the program to be misused. Everything depends on a valuable and useful network, let's do our best to make this happen. Together.

**Comment by BDEio** [comment]
@LMdesignlab Hi! Great to see that you have gotten approval for DataCap!
BDE is a verified deals auction house helping you to get paid storing your data with reliable storage providers. If you need any help, please get in touch.

**Comment by kernelogic** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedakcfl3g4hx3xzw37crzomfzswh5ax355chk5jkjiwwbh5nobkao 
#### Address 
> f15cmd7mpswrjpbagpbi233cr3ydauvmi2dbziyla
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### Id
> 29b4f45e-8e12-4643-8821-0d76b8f2d04f
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedakcfl3g4hx3xzw37crzomfzswh5ax355chk5jkjiwwbh5nobkao

**Comment by LMdesignlab** [comment]
Thank you for your efforts @herrehesse 

1. We are the Client, and the Client is us.
We are the demander for data storage, and currently the company's business data is stored on our servers. We copy the hard drives to SP by mail.

2.LM is a customized architectural design company founded in 2015. It has been in normal operation for 8 years. You can get our information through the above PPT materials.
We currently have 400T+ business data, and we want to make 10 replicas, including:
Project data
design scheme
Project design drawing
Design rendering
Rendering video of renderings
Relevant image data after the completion of the project.



3. We apply for DC for the following reasons
(1) Our data is valuable to both clients and the construction industry. Future clients are willing to pay to get their data back when they need it.
(2) The DC quota allows us to store the data set in Filecoin. When we communicate with SP, they are not willing to provide us with data storage without DC. Because there's a lot of extra cost. These costs are higher than buying our own servers and using a centralized storage service.


4. We reached out to some Filecoin investors, and we also reached out to some technical services teams. We provide the source data, send the hard disk offline, send to the location of SP, and load the data.

5. I'm sorry that we have CID sharing, which is caused by the mistake of technical personnel. You can see that the error is not magnified in subsequent rounds.

In the future, we will pay special attention to it. Before using DC, technical staff will check it out first. And use Lotus to query CID to see whether there is CID sharing.

**Comment by xingjitansuo** [comment]
It seems that the client ask a third party to prepare the file to the format that Filecoin accepts, and that's the reason for the CID sharing. Please be careful next time.

**Comment by LMdesignlab** [comment]
Thank you for your understanding. After the first error, we have corrected the error. No new error occurs again

**Comment by xingjitansuo** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceakzcw4gwthjf7lbugkqk64r35a5ucel5xsougjj5fhowd3vsg7ui 
#### Address 
> f15cmd7mpswrjpbagpbi233cr3ydauvmi2dbziyla
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1a2lia2cwwekeubwo4nppt4v4vebxs2frozarz3q
#### Id
> 29b4f45e-8e12-4643-8821-0d76b8f2d04f
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceakzcw4gwthjf7lbugkqk64r35a5ucel5xsougjj5fhowd3vsg7ui

**Comment by herrehesse** [comment]
@LMdesignlab thank you for your detailed explanation, appreciate it.

The business data you provided is very much welcomed to the Filecoin network, but I believe it does not fit the requirements for the Filecoin+ program. The data is purely for and from your business and does not improve the global network as a whole in my opinion.

_"The DC quota allows us to store the data set in Filecoin. When we communicate with SP, they are not willing to provide us with data storage without DC. Because there's a lot of extra cost. These costs are higher than buying our own servers and using a centralized storage service."_

This one is really important to me, again your transparency is valued, should we grant datacap to applicants who are requesting to store business data at selected storage providers who declined regular paid deals? This way we will never evolve into a monetised storage platform and the datacap will be abused purely for growth only. Not the vision of storing humanities most important information.

**Comment by LMdesignlab** [comment]
I am happy to discuss with you about the abuse of DC. The following views only represent my own personal views

In my opinion, any data is valuable (except for random computer generated numbers), and each piece of data has a different meaning and function for each person.
Whether it's a large public data set or an enterprise data set, if someone is willing to use Fil+ to store it and use it by the rules, I think that's a great thing.

To be honest, Filecoin at this stage is a terrible experience to use, and it will take some time to grow if it is to reach the level of S3.

My personal opinion is:
During the Filecoin ➡️ S3 process,
Any data loaded into Filecoin is helping Filecoin grow.
If there is no DC incentive, SP is hardly motivated to cooperate with Client to store data. This is the fact of the moment.
Besides, right now we only have DC.

I think we might as well not put so much value on DC ️
Can we interpret this as a testing phase? Everything is being done to keep Filecoin strong and growing.
Whether it's through Fil+, fil-e, or fil-A? Fil-B? OR Fil-??
No matter what data, no matter what form.

Until the use experience of Filecoin can reach S3 or close to S3, we can replace the data.
After all, so far, the data storage period is only 540 days.

This is my opinion on DC, which has nothing to do with LM and others.Look forward to your reply😊
 @herrehesse

**Comment by LMdesignlab** [comment]
No slur on Filecoin, just look at it from the perspective of how things are going.
This is normal, after all, everyone needs time to grow up.

In the early days, many successful Internet giants gave away their resources to users for free in order to have more users. Users also helped the application/network to further grow while using them. (e.g. Google, wechat, etc.)

So I think Filecoin's DC is a similar reward,
This reward is given by the community to Client and SP.

We just need to make sure it's not random computer-generated numbers, it's not an adult video, it's not illegal content.
Everyone has the right to enjoy the DC and participate in the community.

What do you think? 🤔

**Comment by herrehesse** [comment]
@LMdesignlab I agree with you mostly, and I respect the way you are responding to my questions. I wished there where more people like you in this github repo.

"Everyone has the right to enjoy the DC and participate in the community" I 100% agree with you. 

It does not automatically mean that "any piece of corporate data may derive the permissions to amass datacap."

**Datacap is a gift, not a right.**

Aside from my opinion that this data may not be suitable for the Filecoin+ program, I am always in favor of experimenting with customers on the Filecoin network. And I also like the above CID report better than the 9/10 applications I have come across. However, two more questions about the report:

Could you enlighten me if you can still approach storage providers in australia or america for full correct distribution?

Also, data dissemination is still among too few different companies. (And as indicated above regions).

Would love to see improvement in this, in addition to the conversation about the eligibility of the data.

**Comment by LMdesignlab** [comment]
checker:manualTrigger

**Comment by LMdesignlab** [comment]
I was surprised by CID Checker's results.
As for the emerging CID sharing situation, we are investigating the cause.
Preliminary judgment is due to the operation error of one of the technical service team, the specific situation is still under investigation.
If the violation is true, we will try to have the offending SP terminate the corresponding DC sector.

**Comment by herrehesse** [comment]
@LMdesignlab Full investigation results are requested by the community as this violation is not acceptable without clear explanation.

**Comment by LMdesignlab** [comment]
I agree with you. We are also checking. @herrehesse

**Comment by Tom-OriginStorage** [comment]
checker:manualTrigger

**Comment by Tom-OriginStorage** [comment]
@LMdesignlab

**Comment by Tom-OriginStorage** [comment]
The customer found me and wanted to continue this project. @LMdesignlab  How is the problem of CID sharing handled now
