### ISSUE TITLE
[DataCap Application] Beijing Premiere Culture Media Co., Ltd.

### ISSUE THREAD

**Issue by sitie123** [filecoin-project/filecoin-plus-large-datasets#567]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Beijing Shouying Culture Media Co., Ltd.
- Website / SocialMedia:[http://www.bjshowinfilm.com
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):5 PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):150TiB
- On-chain address for first allocation:f1uiagqewz3zsq5y5bx6ulpcqd2u3v6bocsv65zfy

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
First Film MediaFounded in 2004, a comprehensive and professional one-stop Internet media company. Headquartered in Beijing, it owns a number of holding subsidiaries in Shanghai, Guangzhou, Wuhan, Chengdu, Nanjing, Hangzhou, Chongqing, Jinan, Zhengzhou, Changsha, Fuzhou, Hefei, Nanning, Hong Kong, etc., building a "creative + shooting + production" The three-in-one business ecological chain integrating online and offline, with a brand value of 8.08 billion.The Film and Television Advertising Division is specialized in the creation, shooting and production of video content such as commercials, promotional films, and 3D animations, and has achieved professional and large-scale operations.The film and television drama division adheres to the core tenet of "content is king", and abandons the "artisan model" that focuses on production, or the "specialized store model" that focuses on individual directors. Optimal allocation of resources for professional talents, management talents, and marketing talents, and specialization in technical fields, in order to achieve the purpose of "more, faster, better and more economical".The Film and Television Technology Division, as a high-tech enterprise in Zhongguancun, has a self-developed Internet advertising platform, and is also the designated operator of a major project of Chuba video lossless compression technology.
After 18 years of sunshine operation, the company has gathered a media elite team of nearly 200 people, with rich experience in brand management, content production and dissemination, and won the "2017 (Industry) Leading Brand", "2020 Top Ten Influences in China's Cultural Industry" Brand” and “Top Ten Influential Enterprises in 2021 (Industry)” and many other honors, establishing a good reputation in the industry and leading the innovation and development of the industry.
Based on more than ten years of international creative thinking and execution experience, the company serves global customers with one-stop video content "creation + shooting + production" solutions, and is determined to become one of the most influential Internet media groups in China.
```

What is the primary source of funding for this project?
```
Account from company
```

What other projects/ecosystem stakeholders is this project associated with?
```
No
```

## Use-case details

Describe the data being stored onto Filecoin
```
Mainly videos and introductory videos of teaching courses for students to learn.
```

Where was the data in this dataset sourced from?
```
Public data generated during brand operations and merchandise sales.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://drive.google.com/drive/folders/1qnBFK9v2uSVfbCrwLG8OSSxX5hGKTO4l
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes
```

What is the expected retrieval frequency for this data?
```
It depends on actual needs.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
permanent
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Asia
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
We can have an offline data transfer process. How the data is distributed will depend on the network.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We will consider the timing and stability of the supplier.
```

How will you be distributing deals across storage providers?
```
We will distribute evenly to each storage provider.
```
Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
We have sufficient funds and resources
```

**Comment by Sunnyiscoming** [comment]
> https://www.qcc.com/ 

1.The website is not correct. Is this link http://www.bjshowinfilm.com/?


> Dì yījiā (gǔpiào dàimǎ:870782) Chénglì yú 2004 nián, shì yī jiā zònghé xìng, zhuānyè huà chuánméi de yǎnglǎo hùliánwǎng méitǐ gōngsī。Huàféi liánsuǒ zǒngbù shè zài bèijīng, shànghǎi, guǎngzhōu, wǔhàn, chéngdū, nánjīng, hángzhōu, chóngqìng, jǐnán, nán zhèngzhōu, zhǎng yì shā, fúshōu, zhèngzhōu, nánníng dìng dì quánmiàn kòngǔ", xiàn shàng +bòzà +chuàngy" "xiàn xià yītǐ huà sān he yī shēngtài, jiàzhi 808."
> Yǐngshì guǎnggào shìyè bù zhuānyè cóngshì guǎnggào, xuānchuán piàn,3D lònghuà dèng shìpín nèiróng de chuàngzuò, pāishè hé zhìzuò。什显乐着眼 huà jīngyíng hé guīmó huà jīngyíng。Diànyǐng diànshìjù de yōuhuà pèizhì jù bù, zhuān wèi diànyǐngshìyè bù dǎzào de zhuānyè móshì, yǐ zhì piàn rénwéi tícái de "yǐng shì yǎnyuán" huò yǐ réncái wéi zhǔjiǎo de "yǎnyuán, yíngxiào rényuán". Zīyuán, yǐ dàdào de mùdì “gèng duō huà, tígāo, gèng hǎo, gèng shěng”。
> Jìshù shìyè bù zhōngguāncūn gāoxīn jìshù qǐyè, yǒngyǒu zhòngdà zìzhǔ yánfā de hùliánwǎng guǎnggào píngtái, yěshì chǔ bà shìpín yāsuō jìshù xiàngmù dì zhǐng.Lìjīng 18 nián de yángguāng yùnyíng, gōngsī níngjù qǐ jìn 200 rén de chuánméi jīngyīng tuánduì, yǒngyǒu fēngfù de pǐnpái guǎnlǐ hé nèiróng zhìzuò, chuánbò jīngyàn, yíngdéle “2017(hángyè) lǐngjūn pǐnpái”,“2020 zhōngguó wénhuà chǎnyè shí dà yǐngxiǎng lì pǐnpái ” yǐjí “2021(hángyè) shí dà yǐngxiǎng lì qǐyè” dèng zhūduō róngyù, shùlì qǐ liánghǎo de yèjiè kǒubēi, yǐnlǐng hángyè chuàngxīn fāzhǎn。
> Jīyú shí duō nián de guójì huà chuàngzuò sīwéi hé zhíxíng jīngyàn, gōngsī yǐ yí zhàn shì shìpín nèiróng “chuàngyì +zhìzuò +chuánbò” jiějué fāng'àn fúwù yú quánqiú kèhù, shǐzhì chéngwéi zhōngguó pǒjù yǐngxiǎng lì de hùliánwǎng chuánmé yī tuán zhī.

2.Please answer in English for more community members.

3.Can you provide more detailed information about storage providers distribution, such as you can list SPs you have contacted with at present?

**Comment by sitie123** [comment]
> > https://www.qcc.com/
> 
> 1.网站不正确。这个链接是http://www.bjshowinfilm.com/吗？
> 
> > Dì yījiā (gǔpiào dàimǎ:870782) Chénglì yú 2004 nián, shì yī jiā zònghé xìng, zhuānyè huà chuánméi de yǎnglǎo hùliánwǎng méitǐ gōngsī。Huàféi liánsuǒ zǒngbù shè zài bèijīng, shànghǎi, guǎngzhōu, wǔhàn, chéngdū, nánjīng, hángzhōu, chóngqìng, jǐnán , nán zhèngzhōu, zhǎng yì shā, fúshōu, zhèngzhōu, nánníng dìng dì quánmíàn kòngǔ", xiàn shàng +bòzà +chuàngy" "xiàn xià yītǐ huà sān he yī shēngtài, jiàzhi 808."
> > Yǐngshì guǎnggào shìyè bù zhuānyè cóngshì guǎnggào, xuānchuán piàn,3D lònghuà dèng shìpín nèiróng de chuàngzuò, pāishè hé zhìzuò。什显乐着眼 huà jīngyíng hé guīmó huà jīngyíng。Diànyǐng diànshìjù de yōuhuà pèizhì jù bù, zhuān wèi diànyǐngshìyè bù dǎzào de zhuānyè móshì , yǐ zhì piàn rénwéi tícái de "yǐng shì yǎnyuán" huò yǐ réncái wéi zhǔjiǎo de "yǎnyuán, yíngxiào rényuán"。Zīyuán, yǐ dàdào de mùdì “gèng duō huà, tígāo, gèng hǎo, gèng shěng”。
> > Jìshù shìyè bù zhōngguāncūn gāoxīn jìshù qǐyè, yǒngyǒu zhòngdà zìzhǔ yánfā de hùliánwǎng guǎnggào píngtái, yěshì chǔ bà shìpín yāsuō jìshù xiàngmù dì zhǐng.Lìjīng 18 nián de yángguāng yùnyíng, gōngsī níngjù qǐ jìn 200 rén de chuánméi jīngyīng tuánduì, yǒngyǒu fēngfù de pǐnpái guǎnlǐ hé nèiróng zhìzuò, chuánbò jīngyàn, yíngdéle “2017(hángyè) lǐngjūn pǐnpái”,“2020 zhōngguó wénhuà chǎnyè shí dà yǐngxiǎng lì pǐnpái ” yǐjí “2021(hángyè) shí dà yǐngxiǎng lì qǐyè” dèng zhūduō róngyù, shùlì qǐ liánghǎo de yèjiè kǒubēi , yǐnlǐng hángyè chuàngxīn fāzhǎn。
> > Jīyú shí duō nián de guójì huà chuàngzuò sīwéi hé zhíxíng jīngyàn, gōngsī yǐ yí zhàn shì shìpín nèiróng “chuàngyì +zhìzuò +chuánbò” jiějué fāng'àn fúwù yú quánqiú kèhù, shǐzhì chéngwéi zhōngguó pǒjù yǐngxiǎng lì de hùliánwǎng chuánmé yī tuán zhī。
> 
> 2.更多社区成员请用英文回答。
> 
> 3.能否提供更详细的存储供应商分布信息，比如可以列出目前接触过的SP？

1. The company's official website has been updated
2. The company has been re-introduced in English.
3. The company we are currently docking with is Beijing Golden Cloud Technology Co., Ltd. (open source mining pool)

**Comment by Sunnyiscoming** [comment]
1.It is super important to value decentralization and diversification as you onboard large sums of data onto the network, especially to minimize concentration risk and distribute data to several SPs. At this point, I suggest that you find at least 3 other SP organizations and focus first on restoring the data you have already stored with the main SP org to ensure you have safe replica building and no data loss from the network.

2.Could you send an email to [filplus-app-review@fil.org](mailto:filplus-app-review@fil.org) with your official domain in order to confirm your identity?
Email name should includes the issue id https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/567.

**Comment by Sunnyiscoming** [comment]
Can you list nodes of this sp? Beijing Golden Cloud Technology Co., Ltd. (open source mining pool).

**Comment by sitie123** [comment]
> 1.当您将大量数据载入网络时，重视去中心化和多样化非常重要，尤其是要最大限度地降低集中风险并将数据分发给多个 SP。在这一点上，我建议您至少找到 3 个其他 SP 组织，并首先专注于恢复您已经使用主 SP 组织存储的数据，以确保您可以安全地构建副本并且不会从网络中丢失数据。
> 
> 2.您可以用您的官方域名发送电子邮件至[filplus-app-review@fil.org](mailto:filplus-app-review@fil.org)以确认您的身份吗？ 电子邮件名称应包含问题 ID #567。

1. Yes, thank you very much for the reminder. We store the data to the storage offline, and the previous backup will not be deleted for the time being, so there should be no data loss.
2. We have sent an email, please check it carefully.

**Comment by sitie123** [comment]
> 你能列出这个sp的节点吗？北京金云科技有限公司（开源矿池）。

Beijing Jinyun Technology Co., Ltd. is a very well-known storage company in China and has made great contributions to filcoin. f01694606 is the node they encapsulate.

**Comment by raghavrmadya** [comment]
As suggested, you cannot store the data with one node. You need to find additional SPs

**Comment by Sunnyiscoming** [comment]
bjshowinfilm.co
The domain name from which the email was sent does not appear to have any connection to the organization.

**Comment by Sunnyiscoming** [comment]
Any update here?

**Comment by raghavrmadya** [comment]
No reply
