### ISSUE TITLE
[DataCap Application] NetSense Technology

### ISSUE THREAD

**Issue by Netzci** [filecoin-project/filecoin-plus-large-datasets#576]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Shanghai Wangshi Science&Technology Co.Ltd.
- Website / Social Media:www.anystreaming.cn
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):5PIB
- Weekly allocation of DataCap requested (usually between 1-100TiB):200TIB
- On-chain address for first allocation:f1o3v5qeroa45qrxl5xsr4dlsmyeso2jty2d6nr3a

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
2012: Company founded; developed the first online encoder, provided national mobile mobile encoder for Huawei's clairvoyant platform
2013-2014: Became a double-soft enterprise; provided mobile TV solution for Sky Consulting and offline cloud transcoding platform for MiguVision
2015: Released video capability platform software; provided end-to-end solution for Jiangsu mobile video capability platform
2016: Became a high-tech enterprise; became a strategic partner of Huawei's three clouds UGC live streaming solution
2017: The only supplier of cloud transcoding platform for CMCC, released cloud guide platform; released cloud transcoding platform
2018: release cloud conference + interactive platform
2019: Video cloud production platform integrating AI
2020: Release of cloud video conferencing
2021: 5G backpack 
```

What is the primary source of funding for this project?
```
Funding from cooperating shareholders and strategic partners with sufficient reserves
```

What other projects/ecosystem stakeholders is this project associated with?
```
no.
```

## Use-case details

Describe the data being stored onto Filecoin
```
Video, text, PPT, etc. data related to the company's operational products
```

Where was the data in this dataset sourced from?
```
(http://www.anystreaming.cn/case.html#cache_list_page_460706=1)
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://drive.google.com/drive/folders/1EtL5wivZ07lnnE5kdeDIltnGKI5UMZAo?usp=sharing
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes
```

What is the expected retrieval frequency for this data?
```
Anyone interested in retrieving this data
```

For how long do you plan to keep this dataset stored on Filecoin?
```
Permanent.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Asia
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Yes. We will use offline data transfer
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We are willing to work with any miner who has the storage conditions and experience.
```

How will you be distributing deals across storage providers?
```
We will choose the vendor that can do it as soon as possible to distribute first.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
We have enough money and resources.
```

**Comment by Sunnyiscoming** [comment]
1.Can you provide more detailed information about storage providers distribution, such as you can list SPs you have contacted with at present?
2.Could you send an email to filplus-app-review@fil.org with your official domain in order to confirm your identity?
Email name should includes the issue id #576.

**Comment by Netzci** [comment]
1. The SP we work with is mainly in Shanghai, because our company is in
Shanghai. For example, f0393236, f01662604
2. I have sent an email through our company's official email address,
please pay attention to check, thank you.

**Comment by Sunnyiscoming** [comment]
Received that.
These two address operates the following nodes. It seems that these nodes is unreachable. Why you choose them?      
f0230449  https://filrep.io/?search=f0230449
f0101021  https://filrep.io/?search=f0101021

**Comment by Netzci** [comment]
Hi, the two nodes were built by SP for their clients and are not on the
public network, so you can't view them. But you can see on filscan that the
nodes are running fine. We chose this SP because they are financially
strong and have faith in filcoin. They will make new nodes and the new
nodes will open the public network.

Sunnyiscoming ***@***.***> 于2022年8月25日周四 10:17写道：

**Comment by Sunnyiscoming** [comment]
It is super important to value decentralization and diversification as you onboard large sums of data onto the network, especially to minimize concentration risk and distribute data to several SPs. At this point, I suggest that you find at least 3 other SP organizations and focus first on restoring the data you have already stored with the main SP org to ensure you have safe replica building and no data loss from the network.

**Comment by Netzci** [comment]
谢谢你的建议。

Sunnyiscoming ***@***.***> 于2022年8月31日周三 11:00写道：

**Comment by Netzci** [comment]
Thank you for your advice. What do I need to do next?

Sunnyiscoming ***@***.***> 于2022年8月31日周三 11:00写道：

**Comment by raghavrmadya** [comment]
Please share examples of video as it relates to your streaming business. 5 PiBs of PDFs and PPTs are hard to believe

**Comment by Netzci** [comment]
Cooperating users with NetSense Technology, which provides live streaming
services using 5G+4K backpacks, the The partner generates a large amount of
video data backup in the process of live streaming
Sichuan TV Station "Sichuan Watch" is one of our cooperative users
https://drive.google.com/drive/folders/1zQSz_lW8AcJVtbwoVoT6hfs3OUBKZmKU?usp=sharing

Raghav Rmadya ***@***.***> 于2022年9月8日周四 04:32写道：

**Comment by Sunnyiscoming** [comment]
@Netzci please provide more data samples.

**Comment by Sunnyiscoming** [comment]
Any update here?

**Comment by Sunnyiscoming** [comment]
Close for no reply. You can resubmit your application if necessary.
