### ISSUE TITLE
[DataCap Application] Unisound

### ISSUE THREAD

**Issue by Eartha116** [filecoin-project/filecoin-plus-large-datasets#577]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Unisound
- Website / Social Media: https://ai.unisound.com/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):100TiB
- On-chain address for first allocation:f1mn5mw2dpqz6p3s7vxrlkhkh3okdtc6t7wqro4xa

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Our mission is to create a more intuitive and connected world through artificial intelligence.
Our vision is to lead the technology evolution in AI and explore every possibility of it.We believe the world would be a better place with artificial intelligence. AI transforms the way we interact and work with each other. Our Company name "Unisound” entails our philosophy of “Intelligently understand your thoughts” .
```

What is the primary source of funding for this project?
```
Company's public account.
```

What other projects/ecosystem stakeholders is this project associated with?
```
No.
```

## Use-case details

Describe the data being stored onto Filecoin
```
Different kinds of audios.
```

Where was the data in this dataset sourced from?
```
From our platform https://ai.unisound.com/tts-short?channel=unisound 
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
[demo.zip](https://github.com/filecoin-project/filecoin-plus-large-datasets/files/9267249/demo.zip)

```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Confirm.
```

What is the expected retrieval frequency for this data?
```
Once a year.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
permanent.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Mainly Asia.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Offline and online.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
Credible storage providers are our first choice.
```

How will you be distributing deals across storage providers?
```
To every sp, we will remain less than 30% of all deals.  
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, we do.
```

**Comment by Eartha116** [comment]
Should I provide anything more to push the process of my application? @galen-mcandrew @dkkapur

**Comment by raghavrmadya** [comment]
please send an email stating you have applied for LDN using an official email plus a business license to filplus-app-review@fil.org

Thanks.

**Comment by Sunnyiscoming** [comment]
1.Can you provide more detailed information about storage providers distribution, such as you can list SPs you have contacted with at present?
2.Can you provide more data samples?There are only two mp3 files provided.

**Comment by Eartha116** [comment]
@raghavrmadya ok! ![e596](https://user-images.githubusercontent.com/107100079/186101148-10798803-adba-4a3d-a0bf-d775dd0cf0bc.jpg)

**Comment by Eartha116** [comment]
@Sunnyiscoming our plan for selecting sp is in progress. We have now contacted several sp: f01841508, f0218092, f0112680, f0127735, f0118641.
[aa.zip](https://github.com/filecoin-project/filecoin-plus-large-datasets/files/9401357/aa.zip)
[ac.zip](https://github.com/filecoin-project/filecoin-plus-large-datasets/files/9401358/ac.zip)

**Comment by Sunnyiscoming** [comment]
Received that.
It seems that these nodes is unreachable. Why you choose them?  
https://filrep.io/?search=f0218092
https://filrep.io/?search=f0112680
https://filrep.io/?search=f0127735
https://filrep.io/?search=f0118641

**Comment by Eartha116** [comment]
Hi Sunny, @Sunnyiscoming I chose them because of their credit. The ones I have contacted are nodes in cc sectors, so currently there's no data for you to retrieve.

**Comment by raghavrmadya** [comment]
The data samples is insufficient. We need more proof that you have 5 PiBs worth of audio files.

**Comment by Sunnyiscoming** [comment]
Otherwise, can you list the name of sps?

**Comment by Eartha116** [comment]
@raghavrmadya OK. We can upload more dataset here. Later I can provide it.
We offer AI intelligent voice service, so we do have a lot of audio files to store. This pic shows that part of our data are using network attached storage. The amount of data we have continues to grow, so we need to find more space to store data and we apply for 5 PiB datacap.
![xcvsdgs](https://user-images.githubusercontent.com/107100079/187827696-273a448c-416e-484f-a99a-1092d7580231.png)

**Comment by raghavrmadya** [comment]
Hi, it is unclear that you have 5 PiB. We can only grant DC for what you have today plus the copies you want to store. Either update the asked amounts or please provide evidence for the requested amount.

**Comment by raghavrmadya** [comment]
Thanks for clarifying

**Comment by raghavrmadya** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 100TiB

**Client address**

>f1mn5mw2dpqz6p3s7vxrlkhkh3okdtc6t7wqro4xa

**Comment by MetaWaveInfo** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacea26f5n3a5acnja3hhd7bj3bdkblwwpr554b5aiaccwzk6ena2src 
#### Address 
> f1mn5mw2dpqz6p3s7vxrlkhkh3okdtc6t7wqro4xa
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1ktlkcxnmzxcdaoqfsunrg3vocfbmgv4n3mrn74a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacea26f5n3a5acnja3hhd7bj3bdkblwwpr554b5aiaccwzk6ena2src

**Comment by BlockMakeronline** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceckwzqofeh5mscslxafab26oool5abca34jrwn5csk7qz7vgpppri 
#### Address 
> f1mn5mw2dpqz6p3s7vxrlkhkh3okdtc6t7wqro4xa
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1o3twrcpwjtpcd4q36lpq4qmy2qfbgtyy5h6tsty
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceckwzqofeh5mscslxafab26oool5abca34jrwn5csk7qz7vgpppri

**Comment by BigD-Exchange** [comment]
@Eartha116 Hi! Great to see you have gotten approval for DataCap and advancing the mission of preserving humanity’s most important information. If you are looking for storage providers to store these data or have any questions, please visit #bigdata-exchange on Filecoin Slack or reply here. 

We have strong demand from a diverse group of SPs, who are actively looking to onboard more data.

**Comment by UnionLabs2020** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceasfaivgmu27rsnhf47b5jws4etnmuyace76k7oozngjsrtd364e6 
#### Address 
> f1mn5mw2dpqz6p3s7vxrlkhkh3okdtc6t7wqro4xa
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f17xdri3wunqgld7dm23e4f3eqsntjakwc47xjo6i
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceasfaivgmu27rsnhf47b5jws4etnmuyace76k7oozngjsrtd364e6

**Comment by liyunzhi-666** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecveawe6euq7uwf7brdk3xvdk643mn7xjomplcqggoqngnkk7luxy 
#### Address 
> f1mn5mw2dpqz6p3s7vxrlkhkh3okdtc6t7wqro4xa
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1pszcrsciyixyuxxukkvtazcokexbn54amf7gvoq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecveawe6euq7uwf7brdk3xvdk643mn7xjomplcqggoqngnkk7luxy

**Comment by MetaWaveInfo** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceadh33hyrd7cnxts5ipm5k5bdwl3xsta4ktf5afmildmqwpmhhtte 
#### Address 
> f1mn5mw2dpqz6p3s7vxrlkhkh3okdtc6t7wqro4xa
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1ktlkcxnmzxcdaoqfsunrg3vocfbmgv4n3mrn74a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceadh33hyrd7cnxts5ipm5k5bdwl3xsta4ktf5afmildmqwpmhhtte

**Comment by swatchliu** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceci3ndcplnroiu5l2yroyrndmrfnmij7shnzn4mwmpin5an7tepiu 
#### Address 
> f1mn5mw2dpqz6p3s7vxrlkhkh3okdtc6t7wqro4xa
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1yh6q3nmsg7i2sys7f7dexcuajgoweudcqj2chfi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceci3ndcplnroiu5l2yroyrndmrfnmij7shnzn4mwmpin5an7tepiu

**Comment by UnionLabs2020** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaysajhbqbwgwqmhkrvswyllobo7tswetksszrrmstaxzxibzstis 
#### Address 
> f1mn5mw2dpqz6p3s7vxrlkhkh3okdtc6t7wqro4xa
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f17xdri3wunqgld7dm23e4f3eqsntjakwc47xjo6i
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaysajhbqbwgwqmhkrvswyllobo7tswetksszrrmstaxzxibzstis

**Comment by liyunzhi-666** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacea2n7zdqgphv7qd34t4iephbup4g32girrmrmbundpza7r4d6f2ya 
#### Address 
> f1mn5mw2dpqz6p3s7vxrlkhkh3okdtc6t7wqro4xa
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1pszcrsciyixyuxxukkvtazcokexbn54amf7gvoq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacea2n7zdqgphv7qd34t4iephbup4g32girrmrmbundpza7r4d6f2ya

**Comment by UnionLabs2020** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedbhgd7arrpyd42bzrwuvlh2lygofo6zt5eihm4auygm4ta43kfoo 
#### Address 
> f1mn5mw2dpqz6p3s7vxrlkhkh3okdtc6t7wqro4xa
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f17xdri3wunqgld7dm23e4f3eqsntjakwc47xjo6i
#### Id
> f340a2d7-c3af-4c76-9a72-523c152a1284
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedbhgd7arrpyd42bzrwuvlh2lygofo6zt5eihm4auygm4ta43kfoo

**Comment by ipfscn** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaprspol4zm4kcav3k75cdftmfuen4qp7qfwjzag345o6dw6fwaac 
#### Address 
> f1mn5mw2dpqz6p3s7vxrlkhkh3okdtc6t7wqro4xa
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1j4n74chme7whbz3yls4a7ixqewb6dijypqg2a3a
#### Id
> f340a2d7-c3af-4c76-9a72-523c152a1284
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaprspol4zm4kcav3k75cdftmfuen4qp7qfwjzag345o6dw6fwaac

**Comment by MetaWaveInfo** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceavobj33gjfrpm4ivdqn6lm6w73ukvxm4louk4oqckeixou2xwnmw 
#### Address 
> f1mn5mw2dpqz6p3s7vxrlkhkh3okdtc6t7wqro4xa
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1ktlkcxnmzxcdaoqfsunrg3vocfbmgv4n3mrn74a
#### Id
> f340a2d7-c3af-4c76-9a72-523c152a1284
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceavobj33gjfrpm4ivdqn6lm6w73ukvxm4louk4oqckeixou2xwnmw

**Comment by filplus-checker** [comment]
## DataCap and CID Checker Report[^1]
 - Organization: `Unisound`
 - Client: `f1mn5mw2dpqz6p3s7vxrlkhkh3okdtc6t7wqro4xa`
### Storage Provider Distribution
The below table shows the distribution of storage providers that have stored data for this client.

If this is the first time a provider takes verified deal, it will be marked as `new`.

For most of the datacap application, below restrictions should apply.
 - Storage provider should not exceed 25% of total datacap.
 - Storage provider should not be storing duplicate data for more than 20%.
 - Storage provider should have published its public IP address.
 - All storage providers should be located in different regions.

⚠️ [f01926914](https://filfox.info/en/address/f01926914) has sealed 40.05% of total datacap.

⚠️ 73.75% of total deal sealed by [f01926914](https://filfox.info/en/address/f01926914) are duplicate data.

⚠️ [f01926585](https://filfox.info/en/address/f01926585) has sealed 39.95% of total datacap.

⚠️ 74.14% of total deal sealed by [f01926585](https://filfox.info/en/address/f01926585) are duplicate data.

⚠️ 78.63% of total deal sealed by [f01832632](https://filfox.info/en/address/f01832632) are duplicate data.

⚠️ 82.57% of total deal sealed by [f01828096](https://filfox.info/en/address/f01828096) are duplicate data.

⚠️ 73.53% of total deal sealed by [f01937964](https://filfox.info/en/address/f01937964) are duplicate data.

⚠️ 70.59% of total deal sealed by [f01924416](https://filfox.info/en/address/f01924416) are duplicate data.

⚠️ 89.33% of total deal sealed by [f01889480](https://filfox.info/en/address/f01889480) are duplicate data.

| Provider                                              |                 Location | Total Deals Sealed | Percentage | Unique Data | Duplicate Deals |
| :---------------------------------------------------- | -----------------------: | -----------------: | ---------: | ----------: | --------------: |
| [f01926914](https://filfox.info/en/address/f01926914) |    Ashburn, Virginia, US |         300.03 TiB |     40.05% |   78.75 TiB |          73.75% |
| [f01926585](https://filfox.info/en/address/f01926585) |    Ashburn, Virginia, US |         299.34 TiB |     39.95% |   77.41 TiB |          74.14% |
| [f01832632](https://filfox.info/en/address/f01832632) | San Jose, California, US |          41.97 TiB |      5.60% |    8.97 TiB |          78.63% |
| [f01828096](https://filfox.info/en/address/f01828096) | San Jose, California, US |          41.06 TiB |      5.48% |    7.16 TiB |          82.57% |
| [f01937964](https://filfox.info/en/address/f01937964) |         Tokyo, Tokyo, JP |          34.00 TiB |      4.54% |    9.00 TiB |          73.53% |
| [f01924416](https://filfox.info/en/address/f01924416) | Singapore, Singapore, SG |          17.00 TiB |      2.27% |    5.00 TiB |          70.59% |
| [f01889480](https://filfox.info/en/address/f01889480) |     Boardman, Oregon, US |          15.81 TiB |      2.11% |    1.69 TiB |          89.33% |

![Provider Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/577/1671097525983.png)
### Deal Data Replication
The below table shows how each many unique data are replicated across storage providers.
- No more than 25% of unique data are stored with less than 4 providers.

⚠️ 100.00% of deals are for data replicated across less than 4 storage providers.

| Unique Data Size | Total Deals Made | Number of Providers | Deal Percentage |
| ---------------: | ---------------: | ------------------: | --------------: |
|        47.72 TiB |       240.78 TiB |                   1 |          32.14% |
|        70.13 TiB |       508.44 TiB |                   2 |          67.86% |

![Replication Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/577/1671097526640.png)
### Deal Data Shared with other Clients
The below table shows how many unique data are shared with other clients.
Usually different applications owns different data and should not resolve to the same CID.

⚠️ CID sharing has been observed.

| Other Client                                                                                                          | Application                                                                                                                | Total Deals Affected | Unique CIDs |                                                                                 Verifier |
| :-------------------------------------------------------------------------------------------------------------------- | :------------------------------------------------------------------------------------------------------------------------- | -------------------: | ----------: | ---------------------------------------------------------------------------------------: |
| [f1bb2z36lpq3pnwiiowiraagpzqnpow4bonjacx7a](https://filfox.info/en/address/f1bb2z36lpq3pnwiiowiraagpzqnpow4bonjacx7a) | [Hola Space](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/362)                                  |           292.38 TiB |       2,511 |                                                                          LDN v3 multisig |
| [f1xtnkj5ti77f5gbzhclnpj3xt6e5dwhfzive2yca](https://filfox.info/en/address/f1xtnkj5ti77f5gbzhclnpj3xt6e5dwhfzive2yca) | [Beacon Project](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/482)                              |            55.75 TiB |         142 | Project Beacon, 12 LDNs LDN # 444, 446, 447, 448, 474, 475, 476, 477, 479, 480, 481, 482 |
| [f1einobkrjcjk6gfc5ov6663vrri75hwdsjfs6pmq](https://filfox.info/en/address/f1einobkrjcjk6gfc5ov6663vrri75hwdsjfs6pmq) | [Cansoti](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/640)                                     |            32.66 TiB |         160 |                                                                          LDN v3 multisig |
| [f1jdmx2cuswzjlt4pnsv3t7ipmesywzxsg6q56a2a](https://filfox.info/en/address/f1jdmx2cuswzjlt4pnsv3t7ipmesywzxsg6q56a2a) | [Raysun Radar Electronic Technology Co\.,Ltd](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/884) |            11.63 TiB |          54 |                                                                          LDN v3 multisig |
| [f1zav4f4rak2yvbrq357z3whj224wn4dipl7eiesy](https://filfox.info/en/address/f1zav4f4rak2yvbrq357z3whj224wn4dipl7eiesy) | [Shanghai Zhixun](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/628)                             |            11.25 TiB |          77 |                                                                          LDN v3 multisig |
| [f1727w2vwjctfo7hflr5trgqkl3c7texh7pl4grzq](https://filfox.info/en/address/f1727w2vwjctfo7hflr5trgqkl3c7texh7pl4grzq) | [GMverse](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/365)                                     |            10.97 TiB |         101 |                                                                          LDN v3 multisig |
| [f1avhqgmeazxzvylz34l26o3nlj2ywnzaviwns3dq](https://filfox.info/en/address/f1avhqgmeazxzvylz34l26o3nlj2ywnzaviwns3dq) | [87v5\-CarsonVideo](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/392)                           |             8.94 TiB |          60 |                                                                          LDN v3 multisig |
| [f1dwhevm3p2slu6itmkssznscmpkpltdiztprnpya](https://filfox.info/en/address/f1dwhevm3p2slu6itmkssznscmpkpltdiztprnpya) | [Hiscene](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/548)                                     |             1.81 TiB |          11 |                                                                          LDN v3 multisig |
| [f1quofpadzcqlonmz7v3mv7dfqvm5hdztucdsjqsy](https://filfox.info/en/address/f1quofpadzcqlonmz7v3mv7dfqvm5hdztucdsjqsy) | [HENAN 863 SOFTWARE CO\., LTD](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/468)                |             1.44 TiB |           9 |                                                                          LDN v3 multisig |
| [f1rnwp6p5kx7pcwexpucoav6mmwz3rkxw5blrboyy](https://filfox.info/en/address/f1rnwp6p5kx7pcwexpucoav6mmwz3rkxw5blrboyy) | [MigoVideo](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/517)                                   |           608.00 GiB |           3 |                                                                          LDN v3 multisig |
| [f1tivtdkq34mnfzso63wrr2xh6r2zo7aebao4jfla](https://filfox.info/en/address/f1tivtdkq34mnfzso63wrr2xh6r2zo7aebao4jfla) | `China travel service(HongKong) limited`                                                                                   |           576.00 GiB |           5 |                                                                          LDN v3 multisig |
| [f1xyx3tvfoy7ue62oqdtcpud5ewcw2i7ctu4kyylq](https://filfox.info/en/address/f1xyx3tvfoy7ue62oqdtcpud5ewcw2i7ctu4kyylq) | [zhenshuai](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/332)                                   |           384.00 GiB |           3 |                                                                                LDN # 332 |

[^1]: To manually trigger this report, add a comment with text `checker:manualTrigger`
