### ISSUE TITLE
[DataCap Application] Foldingathome COVID-19 Datasets

### ISSUE THREAD

**Issue by kernelogic** [filecoin-project/filecoin-plus-large-datasets#59]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Fei Yan - Kernelogic
- Website / Social Media: https://slingshot.kernelogic.ca/ @feiya200
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 1PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 200TiB
- On-chain address for first allocation: f3xbtxeptbmiuevsbjnnsntx6p37a7q6lbw4x7gdkdkiih2ha4qlymoayd2xwk2mpgbwdvgievlje7eivh3e3q

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
I have participated every Slingshot phase and is probably the best performing as a "small individual client". 

I am known for always storing data with many different community providers in different countries rather than self-dealing.

Slingshot prizes in the last phases are not enough to cover market price (8 FIL / TiB prize vs 11 FIL / TiB market price). I am turning to this large datacap application hoping to reduce my cost of participating slingshot, also benefit every small but real providers out there to take verified deals.

I have an existing LDN on another dataset approved and I have record to show I have been following the rules of decentralization and have zero self dealing.

https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/46
https://filplus.d.interplanetary.one/clients/f01037760
https://filplus.d.interplanetary.one/clients/f01037760
```

What is the primary source of funding for this project?
```
I am hoping to utilize this datacap at zero cost, on all the small active community providers (< 2PiB) out there on Slack, especially MinerX / enterprise-sp-wg members. 

I expect to receive prize from Slingshot as return of my effort as I need to spend a lot time preparing dataset, bandwidth, hardware and communicating with providers.
```

What other projects/ecosystem stakeholders is this project associated with?
```
Slingshot, MinerX, enterprise-sp-wp.
```

## Use-case details

Describe the data being stored onto Filecoin
```
Foldingathome COVID-19 Datasets
Folding@home is a massively distributed computing project that uses biomolecular simulations to investigate the molecular origins of disease and accelerate the discovery of new therapies.
```

Where was the data in this dataset sourced from?
```
https://registry.opendata.aws/foldingathome-covid19/
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://fah-public-data-covid19-cryptic-pockets.s3.amazonaws.com/HCoV-NL63/spike/PROJ14201/RUN808/CLONE0/results27/positions.xtc
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes. It has the license of https://creativecommons.org/share-your-work/public-domain/cc0/.
```

What is the expected retrieval frequency for this data?
```
I am expecting some retrievals during prize judging period, as well as anyone interested in downloading this dataset.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
As slingshot rule, 1 year.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
All regions.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
I will upload my prepared CAR files to a web server and coordinate with providers to download and propose offline deals.

I might utilize filswan platform to automate the process.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
I plan to deal with MinerX and enterprise-sp-wg members, as well as a few small providers (under 2PiB) I deal with frequently during previous phases.
```

How will you be distributing deals across storage providers?
```
Evenly across all providers I propose to, if they can handle. If a miner is a notary itself, this notary will receive no more than 10% of the total granted datacap.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
I have all I need to start making deals. However it would be great to see collateral loans (or something else that gives small providers more collateral) to handle the load.
```

**Comment by galen-mcandrew** [comment]
## Multisig Notary requested
#### Total DataCap requested 
> 1PiB
#### Expected weekly DataCap usage rate 
> 200TiB

**Comment by swatchliu** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebbaschaltzc62tiewpiipyyajtnmuajt64y4sezcgcnuznw57b5q 
#### Address 
> f3xbtxeptbmiuevsbjnnsntx6p37a7q6lbw4x7gdkdkiih2ha4qlymoayd2xwk2mpgbwdvgievlje7eivh3e3q
#### Datacap Allocated
> 102TiB
#### Signer Address
> f1yh6q3nmsg7i2sys7f7dexcuajgoweudcqj2chfi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebbaschaltzc62tiewpiipyyajtnmuajt64y4sezcgcnuznw57b5q

**Comment by Reiers** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedyydgecup6lgkqd6wa4odd6f37womsxciktfeavc75skmg2uufpi 
#### Address 
> f3xbtxeptbmiuevsbjnnsntx6p37a7q6lbw4x7gdkdkiih2ha4qlymoayd2xwk2mpgbwdvgievlje7eivh3e3q
#### Datacap Allocated
> 102TiB
#### Signer Address
> f1oz43ckvmtxmmsfzqm6bpnemqlavz4ifyl524chq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedyydgecup6lgkqd6wa4odd6f37womsxciktfeavc75skmg2uufpi

**Comment by kernelogic** [comment]
Hi @dkkapur @galen-mcandrew my address suddenly not a verified client anymore. I think it should still have more than 30TiB datacap before renew.

lotus filplus check-client-datacap f3xbtxeptbmiuevsbjnnsntx6p37a7q6lbw4x7gdkdkiih2ha4qlymoayd2xwk2mpgbwdvgievlje7eivh3e3q
ERROR: client f3xbtxeptbmiuevsbjnnsntx6p37a7q6lbw4x7gdkdkiih2ha4qlymoayd2xwk2mpgbwdvgievlje7eivh3e3q is not a verified client

**Comment by galen-mcandrew** [comment]
When I check https://verify.glif.io/ right now, it says that address has 64 GiB remaining. Very odd. @kernelogic can you double-check?

We are having an issue with the Fil+ registry app, so allocations are not showing up for notaries to sign or approve.

**Comment by flyworker** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedhok6zcirtdgrzisi6nkugbhobisr3komu637obphtvxnvpuyndy 
#### Address 
> f3xbtxeptbmiuevsbjnnsntx6p37a7q6lbw4x7gdkdkiih2ha4qlymoayd2xwk2mpgbwdvgievlje7eivh3e3q
#### Datacap Allocated
> 204TiB
#### Signer Address
> f1hlubjsdkv4wmsdadihloxgwrz3j3ernf6i3cbpy
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedhok6zcirtdgrzisi6nkugbhobisr3komu637obphtvxnvpuyndy

**Comment by kernelogic** [comment]
@galen-mcandrew could you help me to remove the Granted status so it can show up for approval?

**Comment by galen-mcandrew** [comment]
Checking Glif, seeing 66TiB DC remaining. Just looking above, I'm seeing a proposal from flyworker and then an approval from MegTei.

Looks like this accurately removed readyToSign and replaced with Granted once the threshold of 2 was met. At this time, we are waiting for subsequent allocation bot to kick off and start next allocation, which would then adjust labels.

Am I missing something here?

**Comment by Reiers** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedrm6vbu3tn5eviaucwruz4d7adyhixckncqgur4kbgkx4tsjimrm 
#### Address 
> f3xbtxeptbmiuevsbjnnsntx6p37a7q6lbw4x7gdkdkiih2ha4qlymoayd2xwk2mpgbwdvgievlje7eivh3e3q
#### Datacap Allocated
> 204TiB
#### Signer Address
> f1oz43ckvmtxmmsfzqm6bpnemqlavz4ifyl524chq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedrm6vbu3tn5eviaucwruz4d7adyhixckncqgur4kbgkx4tsjimrm

**Comment by swatchliu** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaf44k6c2abtxk42zco2bnbmbo465mmw5wsxqzaboammfstybqwvq 
#### Address 
> f3xbtxeptbmiuevsbjnnsntx6p37a7q6lbw4x7gdkdkiih2ha4qlymoayd2xwk2mpgbwdvgievlje7eivh3e3q
#### Datacap Allocated
> 409TiB
#### Signer Address
> f1yh6q3nmsg7i2sys7f7dexcuajgoweudcqj2chfi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaf44k6c2abtxk42zco2bnbmbo465mmw5wsxqzaboammfstybqwvq

**Comment by flyworker** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec6emocy66g3bha7uojceidzkf4mhxs7lpcraof5qzqiluqeg4yr6 
#### Address 
> f3xbtxeptbmiuevsbjnnsntx6p37a7q6lbw4x7gdkdkiih2ha4qlymoayd2xwk2mpgbwdvgievlje7eivh3e3q
#### Datacap Allocated
> 409TiB
#### Signer Address
> f1hlubjsdkv4wmsdadihloxgwrz3j3ernf6i3cbpy
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec6emocy66g3bha7uojceidzkf4mhxs7lpcraof5qzqiluqeg4yr6

**Comment by kernelogic** [comment]
Consider this as close as this data has been discontinued for further slingshot phases.

**Comment by filplus-checker** [comment]
## DataCap and CID Checker Report[^1]
 - Organization: `Fei Yan - Kernelogic`
 - Client: `f3xbtxeptbmiuevsbjnnsntx6p37a7q6lbw4x7gdkdkiih2ha4qlymoayd2xwk2mpgbwdvgievlje7eivh3e3q`
### Storage Provider Distribution
The below table shows the distribution of storage providers that have stored data for this client.

If this is the first time a provider takes verified deal, it will be marked as `new`.

For most of the datacap application, below restrictions should apply.
 - Storage provider should not exceed 25% of total datacap.
 - Storage provider should not be storing duplicate data for more than 20%.
 - Storage provider should have published its public IP address.
 - All storage providers should be located in different regions.

⚠️ 40.21% of total deal sealed by [f0240185](https://filfox.info/en/address/f0240185) are duplicate data.

⚠️ 43.90% of total deal sealed by [f02301](https://filfox.info/en/address/f02301) are duplicate data.

⚠️ 50.83% of total deal sealed by [f03223](https://filfox.info/en/address/f03223) are duplicate data.

⚠️ 33.02% of total deal sealed by [f0143858](https://filfox.info/en/address/f0143858) are duplicate data.

| Provider                                                    |                               Location | Total Deals Sealed | Percentage | Unique Data | Duplicate Deals |
| :---------------------------------------------------------- | -------------------------------------: | -----------------: | ---------: | ----------: | --------------: |
| [f0240185](https://filfox.info/en/address/f0240185)         |                Clifton, New Jersey, US |         150.57 TiB |     19.90% |   90.03 TiB |          40.21% |
| [f02301](https://filfox.info/en/address/f02301)             |               San Jose, California, US |         143.10 TiB |     18.91% |   80.28 TiB |          43.90% |
| [f03223](https://filfox.info/en/address/f03223)             |               San Jose, California, US |         136.52 TiB |     18.04% |   67.13 TiB |          50.83% |
| [f0143858](https://filfox.info/en/address/f0143858)`new`    |                Clifton, New Jersey, US |         116.30 TiB |     15.37% |   77.89 TiB |          33.02% |
| [f0142637](https://filfox.info/en/address/f0142637)         |                   Chengdu, Sichuan, CN |          40.59 TiB |      5.37% |   40.59 TiB |           0.00% |
| [f039940](https://filfox.info/en/address/f039940)           |                   Chengdu, Sichuan, CN |          39.25 TiB |      5.19% |   39.25 TiB |           0.00% |
| [f034258](https://filfox.info/en/address/f034258)           |                   Chengdu, Sichuan, CN |          31.75 TiB |      4.20% |   31.75 TiB |           0.00% |
| [f0688935](https://filfox.info/en/address/f0688935)         |                   Chengdu, Sichuan, CN |          19.94 TiB |      2.64% |   19.94 TiB |           0.00% |
| [f0773157](https://filfox.info/en/address/f0773157)         |                Fremont, California, US |          15.25 TiB |      2.02% |   15.25 TiB |           0.00% |
| [f01672960](https://filfox.info/en/address/f01672960)       |                   Chengdu, Sichuan, CN |          12.94 TiB |      1.71% |   12.94 TiB |           0.00% |
| [f09848](https://filfox.info/en/address/f09848)             | Rancho Santa Margarita, California, US |          11.38 TiB |      1.50% |   11.38 TiB |           0.00% |
| [f022352](https://filfox.info/en/address/f022352)           |                         Oslo, Oslo, NO |           6.59 TiB |      0.87% |    6.59 TiB |           0.00% |
| [f0838873](https://filfox.info/en/address/f0838873)`new`    |                      Dallas, Texas, US |           5.00 TiB |      0.66% |    5.00 TiB |           0.00% |
| [f0838852](https://filfox.info/en/address/f0838852)`new`    |                 Newark, New Jersey, US |           5.00 TiB |      0.66% |    5.00 TiB |           0.00% |
| [f0838923](https://filfox.info/en/address/f0838923)`new`    |                Seattle, Washington, US |           5.00 TiB |      0.66% |    5.00 TiB |           0.00% |
| [f08399](https://filfox.info/en/address/f08399)             |                Seattle, Washington, US |           5.00 TiB |      0.66% |    5.00 TiB |           0.00% |
| [f0838893](https://filfox.info/en/address/f0838893)`new`    |                Fremont, California, US |           4.94 TiB |      0.65% |    4.94 TiB |           0.00% |
| [f01602479](https://filfox.info/en/address/f01602479)       |                  Longueuil, Quebec, CA |           3.30 TiB |      0.44% |    3.30 TiB |           0.00% |
| [f0164291](https://filfox.info/en/address/f0164291)         |     Hong Kong, Central and Western, HK |           3.22 TiB |      0.43% |    3.22 TiB |           0.00% |
| [f01609999](https://filfox.info/en/address/f01609999)`new`  |     Hong Kong, Central and Western, HK |         768.00 GiB |      0.10% |  768.00 GiB |           0.00% |
| [f01278](https://filfox.info/en/address/f01278)             |             Grand Rapids, Michigan, US |         224.00 GiB |      0.03% |  224.00 GiB |           0.00% |

![Provider Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/59/1671091934579.png)
### Deal Data Replication
The below table shows how each many unique data are replicated across storage providers.
- No more than 25% of unique data are stored with less than 4 providers.

✔️ Data replication looks healthy.

| Unique Data Size | Total Deals Made | Number of Providers | Deal Percentage |
| ---------------: | ---------------: | ------------------: | --------------: |
|         3.11 TiB |         3.11 TiB |                   1 |           0.41% |
|         5.69 TiB |        11.41 TiB |                   2 |           1.51% |
|        13.09 TiB |        40.19 TiB |                   3 |           5.31% |
|        42.89 TiB |       320.15 TiB |                   4 |          42.31% |
|        15.55 TiB |       109.72 TiB |                   5 |          14.50% |
|         2.88 TiB |        17.59 TiB |                   6 |           2.33% |
|        11.59 TiB |        87.44 TiB |                   7 |          11.56% |
|        14.69 TiB |       157.56 TiB |                   8 |          20.83% |
|       736.00 GiB |         9.44 TiB |                   9 |           1.25% |

![Replication Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/59/1671091935580.png)
### Deal Data Shared with other Clients
The below table shows how many unique data are shared with other clients.
Usually different applications owns different data and should not resolve to the same CID.

⚠️ CID sharing has been observed.

| Other Client                                                                                                          | Application                                                                                                                     | Total Deals Affected | Unique CIDs |        Verifier |
| :-------------------------------------------------------------------------------------------------------------------- | :------------------------------------------------------------------------------------------------------------------------------ | -------------------: | ----------: | --------------: |
| [f1euejrtpg5vphqzydzleld2vgxfkhbrueiomz54y](https://filfox.info/en/address/f1euejrtpg5vphqzydzleld2vgxfkhbrueiomz54y) | [Fei Yan \- Kernelogic](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/457)                            |           215.62 TiB |       2,185 | LDN v3 multisig |
| [f1pkrmygbvweykpjcut36lf7ewgqdfhjklbhvepda](https://filfox.info/en/address/f1pkrmygbvweykpjcut36lf7ewgqdfhjklbhvepda) | [Protocol Labs \( project: Slingshot Evergreen \)](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/293) |           143.20 TiB |       2,137 |       LDN # 293 |
| [f15djc5avdxihguvpmtej24rzbvnnqvzurxe55kja](https://filfox.info/en/address/f15djc5avdxihguvpmtej24rzbvnnqvzurxe55kja) | [Kernelogic \- Fei Yan \- Slingshot Restore](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/136)       |           129.55 TiB |       1,386 |       LDN # 136 |

[^1]: To manually trigger this report, add a comment with text `checker:manualTrigger`
