### ISSUE TITLE
[DataCap Application] Fly Brain Anatomy dataset

### ISSUE THREAD

**Issue by kernelogic** [filecoin-project/filecoin-plus-large-datasets#60]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Fei Yan - Kernelogic
- Website / Social Media: https://slingshot.kernelogic.ca/ @feiya200
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 1 PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 200TiB
- On-chain address for first allocation: f3wkoaov5p4ghrjtfk4lcwtloc3mr3vunxk37mkfmh4lwiqj5thj7wddjgvzaqz5eqdzgvbfrhgqhrvxzrmxva

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
I have participated every Slingshot phase and is probably the best performing as a "small individual client". 

I am known for always storing data with many different community providers in different countries rather than self-dealing.

Slingshot prizes in the last phases are not enough to cover market price (8 FIL / TiB prize vs 11 FIL / TiB market price). I am turning to this large datacap application hoping to reduce my cost of participating slingshot, also benefit every small but real providers out there to take verified deals.

I have an existing LDN on another dataset approved and I have record to show I have been following the rules of decentralization and have zero self dealing.

https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/46
https://filplus.d.interplanetary.one/clients/f01037760
https://filplus.d.interplanetary.one/clients/f01037760
```

What is the primary source of funding for this project?
```
I am hoping to utilize this datacap at zero cost, on all the small active community providers (< 2PiB) out there on Slack, especially MinerX / enterprise-sp-wg members. 

I expect to receive prize from Slingshot as return of my effort as I need to spend a lot time preparing dataset, bandwidth, hardware and communicating with providers.
```

What other projects/ecosystem stakeholders is this project associated with?
```
Slingshot, MinerX, enterprise-sp-wp.
```

## Use-case details

Describe the data being stored onto Filecoin
```
Fly Brain Anatomy, made available by Janelia's FlyLight project, consists of fluorescence images of Drosophila melanogaster driver lines, aligned to standard templates, and stored in formats suitable for rapid searching in the cloud.
```

Where was the data in this dataset sourced from?
```
https://registry.opendata.aws/janelia-flylight/
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://janelia-flylight-imagery.s3.amazonaws.com/DNp13%202020/SS45512/SS45512-20180124_32_C2-f-20x-brain-Split_GAL4-JRC2018_FEMALE_20x_HR-aligned_stack.png
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes. It has the license of https://creativecommons.org/licenses/by/4.0/.
```

What is the expected retrieval frequency for this data?
```
I am expecting some retrievals during prize judging period, as well as anyone interested in downloading this dataset.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
As slingshot rule, 1 year.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
All regions.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
I will upload my prepared CAR files to a web server and coordinate with providers to download and propose offline deals.

I might utilize filswan platform to automate the process.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
I plan to deal with MinerX and enterprise-sp-wg members, as well as a few small providers (under 2PiB) I deal with frequently during previous phases.
```

How will you be distributing deals across storage providers?
```
Evenly across all providers I propose to, if they can handle. If a miner is a notary itself, this notary will receive no more than 10% of the total granted datacap.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
I have all I need to start making deals. However it would be great to see collateral loans (or something else that gives small providers more collateral) to handle the load.
```

**Comment by galen-mcandrew** [comment]
## Multisig Notary requested
#### Total DataCap requested 
> 1PiB
#### Expected weekly DataCap usage rate 
> 200TiB

**Comment by kernelogic** [comment]
@galen-mcandrew can we get this sorted out?

**Comment by galen-mcandrew** [comment]
Sorry, meant to come back and comment. This was resolved 6 days ago, I manually edited to bot comment. As you can see in the most recent change, the bot then successfully parsed to comment and added the readyToSign label. At this time, this is showing up in the app for notary approvals.

**Comment by kernelogic** [comment]
Oh great, I will get the notaries to try sign

**Comment by flyworker** [comment]
it seems working now

**Comment by galen-mcandrew** [comment]
Manually removing label state:StartSignDatacap for now, looks like it may not be displaying in the app currently. @fabriziogianni7

**Comment by swatchliu** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecxfciaxrxrkmp75vhemgbvpw6l3neh3f2qpovvfspyy57ze3u7xm 
#### Address 
> f3wkoaov5p4ghrjtfk4lcwtloc3mr3vunxk37mkfmh4lwiqj5thj7wddjgvzaqz5eqdzgvbfrhgqhrvxzrmxva
#### Datacap Allocated
> 50TiB
#### Signer Address
> f1yh6q3nmsg7i2sys7f7dexcuajgoweudcqj2chfi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecxfciaxrxrkmp75vhemgbvpw6l3neh3f2qpovvfspyy57ze3u7xm

**Comment by kernelogic** [comment]
@MegTei @flyworker could you help me to approve this?

**Comment by Reiers** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecg7vzbq5la62c2veyimdsy44ucgo3ly3z5hunqych6jesvxcw5ki 
#### Address 
> f3wkoaov5p4ghrjtfk4lcwtloc3mr3vunxk37mkfmh4lwiqj5thj7wddjgvzaqz5eqdzgvbfrhgqhrvxzrmxva
#### Datacap Allocated
> 102TiB
#### Signer Address
> f1oz43ckvmtxmmsfzqm6bpnemqlavz4ifyl524chq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecg7vzbq5la62c2veyimdsy44ucgo3ly3z5hunqych6jesvxcw5ki

**Comment by flyworker** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebnxxwrty2xg7jizbgpl5szdd7adndjfypo23rewmg3oiydz27s3i 
#### Address 
> f3wkoaov5p4ghrjtfk4lcwtloc3mr3vunxk37mkfmh4lwiqj5thj7wddjgvzaqz5eqdzgvbfrhgqhrvxzrmxva
#### Datacap Allocated
> 102TiB
#### Signer Address
> f1hlubjsdkv4wmsdadihloxgwrz3j3ernf6i3cbpy
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebnxxwrty2xg7jizbgpl5szdd7adndjfypo23rewmg3oiydz27s3i

**Comment by kernelogic** [comment]
@MegTei  @Reiers  could you help me to approve this?

**Comment by MegTei** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebu64zn3uszwlanc3znbjnzhxkz6id32rkkndqpzy4drmeeru2fmo 
#### Address 
> f3wkoaov5p4ghrjtfk4lcwtloc3mr3vunxk37mkfmh4lwiqj5thj7wddjgvzaqz5eqdzgvbfrhgqhrvxzrmxva
#### Datacap Allocated
> 204TiB
#### Signer Address
> f1ystxl2ootvpirpa7ebgwl7vlhwkbx2r4zjxwe5i
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebu64zn3uszwlanc3znbjnzhxkz6id32rkkndqpzy4drmeeru2fmo

**Comment by kernelogic** [comment]
@MegTei thank you!

**Comment by Reiers** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced7ljvqj3rwuy22we25ulrpyrgc64aetwouko6lde34v3okcuyzpy 
#### Address 
> f3wkoaov5p4ghrjtfk4lcwtloc3mr3vunxk37mkfmh4lwiqj5thj7wddjgvzaqz5eqdzgvbfrhgqhrvxzrmxva
#### Datacap Allocated
> 204TiB
#### Signer Address
> f1oz43ckvmtxmmsfzqm6bpnemqlavz4ifyl524chq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced7ljvqj3rwuy22we25ulrpyrgc64aetwouko6lde34v3okcuyzpy

**Comment by galen-mcandrew** [comment]
Yeah, seeing some instances where two notary signatures through the app (both picked up in the GH issue) are leading to 2 transactions since both are proposals.

**Comment by flyworker** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedx24ehourbgr2ykbfcbvha2zvjgff26wixt6gcregmmhttxg2hie 
#### Address 
> f3wkoaov5p4ghrjtfk4lcwtloc3mr3vunxk37mkfmh4lwiqj5thj7wddjgvzaqz5eqdzgvbfrhgqhrvxzrmxva
#### Datacap Allocated
> 204TiB
#### Signer Address
> f1hlubjsdkv4wmsdadihloxgwrz3j3ernf6i3cbpy
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedx24ehourbgr2ykbfcbvha2zvjgff26wixt6gcregmmhttxg2hie

**Comment by kernelogic** [comment]
Hi @galen-mcandrew I think this one needs a manual label adjust again. Showing as "error" now.

**Comment by swatchliu** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecaaa7wa5malzu6glavs6bsbna7jzogm7poqmh6jxcwxghbnvigdo 
#### Address 
> f3wkoaov5p4ghrjtfk4lcwtloc3mr3vunxk37mkfmh4lwiqj5thj7wddjgvzaqz5eqdzgvbfrhgqhrvxzrmxva
#### Datacap Allocated
> 204TiB
#### Signer Address
> f1yh6q3nmsg7i2sys7f7dexcuajgoweudcqj2chfi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecaaa7wa5malzu6glavs6bsbna7jzogm7poqmh6jxcwxghbnvigdo

**Comment by flyworker** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceahhumve7o2ca4427touomqd44mmg63oulrslhqydp7r2xvc6tgkg 
#### Address 
> f3wkoaov5p4ghrjtfk4lcwtloc3mr3vunxk37mkfmh4lwiqj5thj7wddjgvzaqz5eqdzgvbfrhgqhrvxzrmxva
#### Datacap Allocated
> 204TiB
#### Signer Address
> f1hlubjsdkv4wmsdadihloxgwrz3j3ernf6i3cbpy
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceahhumve7o2ca4427touomqd44mmg63oulrslhqydp7r2xvc6tgkg

**Comment by kernelogic** [comment]
@galen-mcandrew Right now this application has a pending approval but the issue status is "Granted", can you change to "readyToSign"?

```
 lotus msig inspect --decode-params f01381729
Transactions:  1
ID      State    Approvals  To      Value   Method                Params
4       pending  1          f06     0 FIL   AddVerifiedClient(4)  {"Address":"f3wkoaov5p4ghrjtfk4lcwtloc3mr3vunxk37mkfmh4lwiqj5thj7wddjgvzaqz5eqdzgvbfrhgqhrvxzrmxva","Allowance":"224300372066304"}
```

**Comment by galen-mcandrew** [comment]
This pending transaction on the multisig is from the previous misalignment of proposals and approvals. So, there's a pending 204TiB txID 4. Client address now has 50TiB remaining, and you can see in the [logs](https://plus.fil.org/logs) where the SA bot checked this morning at 6:50am PT and was just about at threshold for kicking off next request.

The bot should trigger next request the next time it runs, later today. This will post updated stats and the new allocation amount, which I think will be the remaining DataCap at this notary address. I'd prefer to wait and let the bot request this higher amount, rather than manually adjust the labels to clear the pending txID4 for only 200TiB.

**Comment by kernelogic** [comment]
@galen-mcandrew bot says "The allocation of the requested datacap cannot be performed, because it would result in the exceeding of the total granted data cap." Will it cause trouble?

**Comment by galen-mcandrew** [comment]
It shouldn't cause an error, since the multisig notary has 464TiB of DataCap, when checking Lotus. Talking to keyko team, sounds like that error message may be coming from conversion issues (going back and forth from bytes to TiB and having rounding errors).

**Comment by galen-mcandrew** [comment]
We edited the copy here from the bots, to track the "proposal" and the "approval" from the notaries. This is to try and help track and avoid the exact issue you saw above, where a message starts a transaction, then the next notary message starts another transaction (rather than matching to approve).

**Comment by MegTei** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedd2h25ttnokipv2se5pxo6xpvn5bmyo7zqwatbqcmog4n2nwuqck 
#### Address 
> f3wkoaov5p4ghrjtfk4lcwtloc3mr3vunxk37mkfmh4lwiqj5thj7wddjgvzaqz5eqdzgvbfrhgqhrvxzrmxva
#### Datacap Allocated
> 464.00TiB
#### Signer Address
> f1ystxl2ootvpirpa7ebgwl7vlhwkbx2r4zjxwe5i
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedd2h25ttnokipv2se5pxo6xpvn5bmyo7zqwatbqcmog4n2nwuqck

**Comment by kernelogic** [comment]
@galen-mcandrew still kinda messy now

```
lotus msig inspect --decode-params f01381729
Transactions:  2
ID      State    Approvals  To      Value   Method                Params
5       pending  1          f06     0 FIL   AddVerifiedClient(4)  {"Address":"f3wkoaov5p4ghrjtfk4lcwtloc3mr3vunxk37mkfmh4lwiqj5thj7wddjgvzaqz5eqdzgvbfrhgqhrvxzrmxva","Allowance":"510173395288064"}
6       pending  1          f06     0 FIL   AddVerifiedClient(4)  {"Address":"f3wkoaov5p4ghrjtfk4lcwtloc3mr3vunxk37mkfmh4lwiqj5thj7wddjgvzaqz5eqdzgvbfrhgqhrvxzrmxva","Allowance":"285873023221760"}
```

**Comment by MegTei** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec5thqs7vlblcln5noaj4luofqja7gy643xngo4ikhylqahvabx3y 
#### Address 
> f3wkoaov5p4ghrjtfk4lcwtloc3mr3vunxk37mkfmh4lwiqj5thj7wddjgvzaqz5eqdzgvbfrhgqhrvxzrmxva
#### Datacap Allocated
> 260.00TiB
#### Signer Address
> f1ystxl2ootvpirpa7ebgwl7vlhwkbx2r4zjxwe5i
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec5thqs7vlblcln5noaj4luofqja7gy643xngo4ikhylqahvabx3y

**Comment by fabriziogianni7** [comment]
closing this issue, total datacap has been reached

**Comment by kernelogic** [comment]
@fabriziogianni7 actually due to bugs I am missing about 260T datacap for this request.

```
Transactions:  1
ID      State    Approvals  To      Value   Method                Params
6       pending  1          f06     0 FIL   AddVerifiedClient(4)  {"Address":"f3wkoaov5p4ghrjtfk4lcwtloc3mr3vunxk37mkfmh4lwiqj5thj7wddjgvzaqz5eqdzgvbfrhgqhrvxzrmxva","Allowance":"285873023221760"}
```

**Comment by fabriziogianni7** [comment]
ok, reopening issue and requesting the datacap.

**Comment by swatchliu** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecwkpw766am43v2zps3skb2i6njcotsryq272esm7acxas3sqap3u 
#### Address 
> f3wkoaov5p4ghrjtfk4lcwtloc3mr3vunxk37mkfmh4lwiqj5thj7wddjgvzaqz5eqdzgvbfrhgqhrvxzrmxva
#### Datacap Allocated
> 260.00TiB
#### Signer Address
> f1yh6q3nmsg7i2sys7f7dexcuajgoweudcqj2chfi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecwkpw766am43v2zps3skb2i6njcotsryq272esm7acxas3sqap3u

**Comment by MegTei** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebik6psbxqzg76ksq6hh2vnav5bi3mrzzdjewvp67hi4oflhjvdmq 
#### Address 
> f3wkoaov5p4ghrjtfk4lcwtloc3mr3vunxk37mkfmh4lwiqj5thj7wddjgvzaqz5eqdzgvbfrhgqhrvxzrmxva
#### Datacap Allocated
> 260.00TiB
#### Signer Address
> f1ystxl2ootvpirpa7ebgwl7vlhwkbx2r4zjxwe5i
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebik6psbxqzg76ksq6hh2vnav5bi3mrzzdjewvp67hi4oflhjvdmq

**Comment by kernelogic** [comment]
Thank you @MegTei @swatchliu this last allocation finally went through!

**Comment by filplus-checker** [comment]
## DataCap and CID Checker Report[^1]
 - Organization: `Fei Yan - Kernelogic`
 - Client: `f3wkoaov5p4ghrjtfk4lcwtloc3mr3vunxk37mkfmh4lwiqj5thj7wddjgvzaqz5eqdzgvbfrhgqhrvxzrmxva`
### Storage Provider Distribution
The below table shows the distribution of storage providers that have stored data for this client.

If this is the first time a provider takes verified deal, it will be marked as `new`.

For most of the datacap application, below restrictions should apply.
 - Storage provider should not exceed 25% of total datacap.
 - Storage provider should not be storing duplicate data for more than 20%.
 - Storage provider should have published its public IP address.
 - All storage providers should be located in different regions.

⚠️ 24.65% of total deal sealed by [f0240185](https://filfox.info/en/address/f0240185) are duplicate data.

⚠️ 37.34% of total deal sealed by [f03223](https://filfox.info/en/address/f03223) are duplicate data.

⚠️ [f020378](https://filfox.info/en/address/f020378) has unknown IP location.

⚠️ [f01660837](https://filfox.info/en/address/f01660837) has unknown IP location.

| Provider                                                    |                        Location | Total Deals Sealed | Percentage | Unique Data | Duplicate Deals |
| :---------------------------------------------------------- | ------------------------------: | -----------------: | ---------: | ----------: | --------------: |
| [f0240185](https://filfox.info/en/address/f0240185)         |         Clifton, New Jersey, US |         211.67 TiB |     21.07% |  159.48 TiB |          24.65% |
| [f02301](https://filfox.info/en/address/f02301)             |        San Jose, California, US |         186.20 TiB |     18.53% |  165.64 TiB |          11.04% |
| [f03223](https://filfox.info/en/address/f03223)             |        San Jose, California, US |         159.67 TiB |     15.89% |  100.05 TiB |          37.34% |
| [f0143858](https://filfox.info/en/address/f0143858)         |         Clifton, New Jersey, US |         119.22 TiB |     11.86% |  109.50 TiB |           8.15% |
| [f01652333](https://filfox.info/en/address/f01652333)       |       Sunnyvale, California, US |          76.14 TiB |      7.58% |   76.14 TiB |           0.00% |
| [f066596](https://filfox.info/en/address/f066596)           |       San Diego, California, US |          54.41 TiB |      5.41% |   54.41 TiB |           0.00% |
| [f01619524](https://filfox.info/en/address/f01619524)`new`  |    Frankfurt am Main, Hesse, DE |          49.17 TiB |      4.89% |   49.17 TiB |           0.00% |
| [f01702940](https://filfox.info/en/address/f01702940)       |               Dallas, Texas, US |          29.06 TiB |      2.89% |   29.06 TiB |           0.00% |
| [f01732188](https://filfox.info/en/address/f01732188)       |           Chicago, Illinois, US |          25.94 TiB |      2.58% |   25.94 TiB |           0.00% |
| [f01111110](https://filfox.info/en/address/f01111110)`new`  |             Văn Điển, Hanoi, VN |          20.00 TiB |      1.99% |   20.00 TiB |           0.00% |
| [f020378](https://filfox.info/en/address/f020378)           |                         Unknown |          18.31 TiB |      1.82% |   18.31 TiB |           0.00% |
| [f0678914](https://filfox.info/en/address/f0678914)         |       San Diego, California, US |          12.22 TiB |      1.22% |   12.22 TiB |           0.00% |
| [f0773157](https://filfox.info/en/address/f0773157)         |         Fremont, California, US |          10.00 TiB |      1.00% |   10.00 TiB |           0.00% |
| [f022352](https://filfox.info/en/address/f022352)           |                  Oslo, Oslo, NO |          10.00 TiB |      1.00% |   10.00 TiB |           0.00% |
| [f01660837](https://filfox.info/en/address/f01660837)`new`  |                         Unknown |           9.94 TiB |      0.99% |    9.94 TiB |           0.00% |
| [f01752548](https://filfox.info/en/address/f01752548)       |         Seattle, Washington, US |           9.88 TiB |      0.98% |    9.88 TiB |           0.00% |
| [f01821041](https://filfox.info/en/address/f01821041)       | Vancouver, British Columbia, CA |           3.00 TiB |      0.30% |    3.00 TiB |           0.00% |

![Provider Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/60/1671091954222.png)
### Deal Data Replication
The below table shows how each many unique data are replicated across storage providers.
- No more than 25% of unique data are stored with less than 4 providers.

✔️ Data replication looks healthy.

| Unique Data Size | Total Deals Made | Number of Providers | Deal Percentage |
| ---------------: | ---------------: | ------------------: | --------------: |
|         3.88 TiB |         3.88 TiB |                   1 |           0.39% |
|         2.03 TiB |         4.06 TiB |                   2 |           0.40% |
|         8.88 TiB |        28.44 TiB |                   3 |           2.83% |
|        63.75 TiB |       343.34 TiB |                   4 |          34.17% |
|        44.02 TiB |       230.98 TiB |                   5 |          22.99% |
|        29.28 TiB |       190.66 TiB |                   6 |          18.97% |
|        21.84 TiB |       173.09 TiB |                   7 |          17.23% |
|         3.06 TiB |        30.38 TiB |                   8 |           3.02% |

![Replication Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/60/1671091954870.png)
### Deal Data Shared with other Clients
The below table shows how many unique data are shared with other clients.
Usually different applications owns different data and should not resolve to the same CID.

⚠️ CID sharing has been observed.

| Other Client                                                                                                          | Application                                                                                                                     | Total Deals Affected | Unique CIDs |        Verifier |
| :-------------------------------------------------------------------------------------------------------------------- | :------------------------------------------------------------------------------------------------------------------------------ | -------------------: | ----------: | --------------: |
| [f1pkrmygbvweykpjcut36lf7ewgqdfhjklbhvepda](https://filfox.info/en/address/f1pkrmygbvweykpjcut36lf7ewgqdfhjklbhvepda) | [Protocol Labs \( project: Slingshot Evergreen \)](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/293) |           369.58 TiB |       3,834 |       LDN # 293 |
| [f1euejrtpg5vphqzydzleld2vgxfkhbrueiomz54y](https://filfox.info/en/address/f1euejrtpg5vphqzydzleld2vgxfkhbrueiomz54y) | [Fei Yan \- Kernelogic](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/457)                            |           326.95 TiB |       3,405 | LDN v3 multisig |
| [f15djc5avdxihguvpmtej24rzbvnnqvzurxe55kja](https://filfox.info/en/address/f15djc5avdxihguvpmtej24rzbvnnqvzurxe55kja) | [Kernelogic \- Fei Yan \- Slingshot Restore](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/136)       |           202.03 TiB |       2,155 |       LDN # 136 |
| [f1efk7kg5hgmd2r6yr4kyro24pou5hd64ua7x2iii](https://filfox.info/en/address/f1efk7kg5hgmd2r6yr4kyro24pou5hd64ua7x2iii) | [Fei Yan \- Kernelogic](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/298)                            |            18.94 TiB |          96 |       LDN # 298 |

[^1]: To manually trigger this report, add a comment with text `checker:manualTrigger`
