### ISSUE TITLE
[DataCap Application]Aatty Automatic Laundry

### ISSUE THREAD

**Issue by Topeaf** [filecoin-project/filecoin-plus-large-datasets#607]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Topnotch Entertainmen
- Website / Social Media:http://www.topnotchentertainment.in
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):5PIB
- Weekly allocation of DataCap requested (usually between 1-100TiB):200TIB
- On-chain address for first allocation:f1qte7kt3iz624l2r7jxb7cc7v2mgkuxv3qeoqtrq

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Topnotch Entertainment is specialized activist in event management, Promotional activities, Production elements such as sets, lights, sounds etc. We do events of all sizes, whether corporate meet or commercial events. Our target is to hold events of some size which will help you to market your organization, build business relationships, raise money or celebrate.
```

What is the primary source of funding for this project?
```
Our own and partners' funds
```

What other projects/ecosystem stakeholders is this project associated with?
```
No connection to other projects
```

## Use-case details

Describe the data being stored onto Filecoin
```
Data sets (videos, files, music and other data) from Topnotch Entertainment for event planning, design, production, etc. (videos, files, music and other data)
```

Where was the data in this dataset sourced from?
```
Data from our own
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
(https://drive.google.com/drive/folders/1TtJyfZBZq_NdvpGWooiWzgIKqXAVd_j2?usp=sharing)
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes, I confirm
```

What is the expected retrieval frequency for this data?
```
Once a year
```

For how long do you plan to keep this dataset stored on Filecoin?
```
720 days
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
India & Surroundings
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Yes. We will use offline data transfer
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
Choose a storage provider that is well-funded and understands project data.
```

How will you be distributing deals across storage providers?
```
We will choose the vendor that can do it as soon as possible to distribute first.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, we have
```

**Comment by Sunnyiscoming** [comment]
1.Data samples only contain some jpg. , which can not prove that you have 4 PB data already. Hope you can provide more data samples related with more business scope.
2.Can you provide more detailed information about storage providers distribution, such as you can list SPs you have contacted with at present?
3.Could you send an email to filplus-app-review@fil.org with your official domain in order to confirm your identity?
Email name should includes the issue id #607.

**Comment by Topeaf** [comment]
1. Yes, this is the link to our other sample -
https://drive.google.com/file/d/1GAS3L2h6hU45Rr8UbDajk02iToqlUfAW/view?usp=sharing
https://drive.google.com/file/d/1dBUCp8QMBBmBU_TelIq-ZPSBwZBMDUJa/view?usp=sharing
2. The storage providers we work with are mainly located in Hong Kong, and
they are experienced and strong. For example, f01694740. 3. email has been
sent, thanks.

Sunnyiscoming ***@***.***> 于2022年8月24日周三 11:12写道：

**Comment by raghavrmadya** [comment]
What are the SPs in India? You mentioned in the application.

**Comment by Topeaf** [comment]
Our SP in India is f01421241

Raghav Rmadya ***@***.***> 于2022年8月26日周五 09:58写道：

**Comment by Sunnyiscoming** [comment]
topnotchentertaiment.com
The domain name from which the email was sent does not appear to have any connection to the organization.

**Comment by Sunnyiscoming** [comment]
Any update here?

**Comment by raghavrmadya** [comment]
Closing due to no reply
