### ISSUE TITLE
[DataCap Application] Senrica LLC

### ISSUE THREAD

**Issue by sitie127** [filecoin-project/filecoin-plus-large-datasets#614]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Senrica LLC
- Website / Social Media:https://www.moriricca.co.jp/company/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):5 PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):150TiB
- On-chain address for first allocation:f13gse2nzrdjyq3y3xteyv2p46o2pmll2tu3nvaxi

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Our company opened in December 2018 and registered in 2020, we contribute to the happiness and well-being of people in society. We are engaged in online content creation, advertising and product sales (operating products) plastic models, dolls, board games, simulation games, role-playing games, trading card games, etc.
```

What is the primary source of funding for this project?
```
Account from the company.
```

What other projects/ecosystem stakeholders is this project associated with?
```
market place
```

## Use-case details

Describe the data being stored onto Filecoin
```
Primarily promotional images for events held on the website
```

Where was the data in this dataset sourced from?
```
It comes from materials provided by our company and materials uploaded by users themselves.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://drive.google.com/drive/folders/1l9L0uQS5w0Yn9OpD5mrHWMHSkI69fsuj?usp=sharing
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes
```

What is the expected retrieval frequency for this data?
```
It depends on actual needs.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
permanent
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Japan
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
We mainly conduct online transmission through designated platforms, and we can also provide offline data transmission when necessary.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We will consider the timing and stability of the supplier.
```

How will you be distributing deals across storage providers?
```
We will choose the supplier who can do it as quickly as possible to distribute first.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
We have sufficient funds and resources.
```

**Comment by Sunnyiscoming** [comment]
Can you provide more data samples related with the data you will store, primarily promotional images for events held on the website. The data samples you provided seems too few to prove you have 5 pb data already.
![image](https://user-images.githubusercontent.com/105098820/187111201-9acd1498-f05c-45a3-baea-04d38c0c5b0b.png)
The data you will store seems that have little relationship with the main business. Where these data originated from?

Can you provide more detailed information about storage providers distribution, such as you can list SPs you have contacted with at present?

Could you send an email to filplus-app-review@fil.org with your official domain in order to confirm your identity?
Email name should includes the issue id #614.

**Comment by Sunnyiscoming** [comment]
What's the relationship between Senrica LLC with Moririca LLC?

**Comment by raghavrmadya** [comment]
Please respond by Friday this week to prevent closure of application

**Comment by raghavrmadya** [comment]
No response
