### ISSUE TITLE
[DataCap Application] Cloud e-Procurement

### ISSUE THREAD

**Issue by wasdols** [filecoin-project/filecoin-plus-large-datasets#616]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Rexbridge Sdn Bhd
- Website / Social Media:https://www.xbridge.my/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):5PIB
- Weekly allocation of DataCap requested (usually between 1-100TiB):100TIB
- On-chain address for first allocation:f1xfzshc2pc4jjhtgdlcgfkehj5os2ovaddrtkkwa

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
xBridge is an integrated procurement system for supplier management, e-procurement, business process and contract management. It provides procurement departments with software tools for effective sourcing and validation to drive process efficiencies and cost savings throughout the organization. Replaces inefficient and inaccurate paper-based transactions
```

What is the primary source of funding for this project?
```
Our own funds vs. partners' funds
```

What other projects/ecosystem stakeholders is this project associated with?
```
none 
```

## Use-case details

Describe the data being stored onto Filecoin
```
Mainly the procurement data included in xBridge
```

Where was the data in this dataset sourced from?
```
Public data generated in the course of brand operations and product sales.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://drive.google.com/drive/folders/1IEJi0m0kCz2TX1sV2LbEw3Hv64FHDbB4?usp=sharing
(https://www.xbridge.my/solutions/)
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes
```

What is the expected retrieval frequency for this data?
```
It depends on the actual needs```

For how long do you plan to keep this dataset stored on Filecoin?
```
Two years
```


## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Malaysia and surrounding areas
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Off-line transmission
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
Choose a storage provider that is well-funded and understands project data.
```

How will you be distributing deals across storage providers?
```
We will distribute them equally to each storage provider.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
yes.
```

**Comment by Sunnyiscoming** [comment]
- What's the relationship between you and organization?
- 
- Can you provide more data samples related with the data you will store, mainly the procurement data included in xBridge.
- 
- Can you provide more detailed information about storage providers distribution, such as you can list SPs you have contacted with at present?
- 
- Could you send an email to filplus-app-review@fil.org with your official domain in order to confirm your identity?
- Email name should includes the issue id #616.

**Comment by Sunnyiscoming** [comment]
Any update here? @wasdols

**Comment by raghavrmadya** [comment]
No reply
