### ISSUE TITLE
[DataCap Application] Ghost Byte Inc - Skies and Universes

### ISSUE THREAD

**Issue by Trevor-K-Smith** [filecoin-project/filecoin-plus-large-datasets#621]
# Large Dataset Notary Application

 
![image](https://user-images.githubusercontent.com/28652769/205672525-54d502f2-03e3-465c-a802-bf50c41b1ee4.png)

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

### DP Info
- Organization Name: [Ghost Byte Inc](https://ghostbyte.io)
- Website / Social Media: https://ghostbyte.io
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5 PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 512 TiB
- On-chain address for first allocation: f1bg3khvfgh6v4n37oxyoy7rzuh74r7lw77gu7z7a

### Client Info
- Organization Name: [Skies and Universes](http://skiesanduniverses.iaa.es/)
- Website / Social Media: http://skiesanduniverses.iaa.es/

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Ghost Byte is performing DP services on behalf of the client, Skies and Universes. 

Skies and Universes provide the astronomical community with results from cosmological simulations. These results are useful on their own to understand processes related with the non-linear evolution of cosmic structures. Uchuu (meaning "outer space" in Japanese) is the largest and most realistic simulation of the universe to date.
```

What is the primary source of funding for this project?
```
Ghost Byte Inc 
```

What other projects/ecosystem stakeholders is this project associated with?
```
Ghost Byte Inc 
```

## Use-case details

Describe the data being stored onto Filecoin
```
Dataset contains raw data in decompressed format that can be used for research and understanding of the non-linear evolution of cosmic structures.
```

Where was the data in this dataset sourced from?
```
http://skun.iaa.es/SUsimulations/UchuuDR1/
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
Raw data: https://www.dropbox.com/sh/hrzzk320uhrs4gm/AAAHqd9P6yNrUJRggitm2NCza?dl=0
Raw data used to generate Picture: https://www.dropbox.com/s/7awsqc59nr31927/Photo.jpg?dl=0
Raw data used to generate Video: https://www.dropbox.com/s/wsda3bpq1pyegzk/Video.mp4?dl=0
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Confirmed
```

What is the expected retrieval frequency for this data?
```
EST 0-1 Times a year
```

For how long do you plan to keep this dataset stored on Filecoin?
```
Minimum 540 days.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
World Wide
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Offline data transfer and via boostd
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
SP's will be confirmed ahead of replication of cars that they intend to allow the cars to be accessible and retrievable. Car files for this replication will not be enforced to keep unsealed sectors as this is disaster recovery data, and retrievals will be low. 
```

How will you be distributing deals across storage providers?
```
Internal tooling will be used to evenly distribute copies of data across geographical locations. Deals will be sent via boostd if they support, otherwise, offline. CARS will be served up from webserver.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes. No additional support needed. Will reach out if i come across anything. Thanks!
```

**Comment by Sunnyiscoming** [comment]
Have you authorized to store these data as public data on the Filecoin network?
What's the relationship between you and organization?
Can you provide more detailed information about other storage providers participated in this program, such as you can list SPs you have contacted with at present?
Could you send an email to filplus-app-review@fil.org with your official domain in order to confirm your identity? Email name should includes the issue id #621

**Comment by Sunnyiscoming** [comment]
Any update here? @Trevor-K-Smith

**Comment by raghavrmadya** [comment]
No reply

**Comment by Trevor-K-Smith** [comment]
Apologize for the long delay on this.


@raghavrmadya Can we get this issue reopened?


@Sunnyiscoming 

**Can you provide more information about the organization, Ghost Byte Inc?**

Ghost Byte Inc is a for profit organization in MD, USA. Ghost Byte is performing data preparation services for the client, Skies and Universes, for storing their data onto the filecoin network.


**Have you authorized to store these data as public data on the Filecoin network?**

Yes, client was contacted services offered and accepted, and now executing.

**What's the relationship between you and organization?**

I am an employee of Ghost Byte, the data preparer. 

**Can you provide more detailed information about other storage providers participated in this program, such as you can list SPs you have contacted with at present?**

Data is to be stored around the globe with no geo restrictions. Additional SPs needed to store replications will be contacted and/or requested via slack channel. Current SP's to share data with will be PiKNiK, Vault 32, and Scaseye.

**Could you send an email to [filplus-app-review@fil.org](mailto:filplus-app-review@fil.org) with your official domain in order to confirm your identity? Email name should includes the issue id https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/621**

I will send a email from our organization, Ghost Byte, and have the client, Skies and Universes, send one as well. Should receive within next 24 hours.


Let me know if any other questions.

**Comment by psh0691** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacece35u3hcuwc7ygveotxfykl4aejmrok7dharanxg7sprtydrjgdg 
#### Address 
> f1bg3khvfgh6v4n37oxyoy7rzuh74r7lw77gu7z7a
#### Datacap Allocated
> 125.00TiB
#### Signer Address
> f1qdko4jg25vo35qmyvcrw4ak4fmuu3f5rif2kc7i
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacece35u3hcuwc7ygveotxfykl4aejmrok7dharanxg7sprtydrjgdg

**Comment by liyunzhi-666** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebogrm6vhfgu4dvsjgsqczh3zil4rd3h43mwsfcblfsa6psl42tlu 
#### Address 
> f1bg3khvfgh6v4n37oxyoy7rzuh74r7lw77gu7z7a
#### Datacap Allocated
> 125.00TiB
#### Signer Address
> f1pszcrsciyixyuxxukkvtazcokexbn54amf7gvoq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebogrm6vhfgu4dvsjgsqczh3zil4rd3h43mwsfcblfsa6psl42tlu

**Comment by BigD-Exchange** [comment]
@Trevor-K-Smith Hi! Great to see you have gotten approval for DataCap. If you are looking for storage providers to store these data or have any questions, please visit #bigdata-exchange on Filecoin Slack or reply here. 

We have strong demand from a diverse group of SPs, who are actively looking to onboard more data.

**Comment by Alex11801** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceam32ptvfsvknrzs2ttkl7briqb3lpgp6xyyomsfqvtrzwtlja3um 
#### Address 
> f1bg3khvfgh6v4n37oxyoy7rzuh74r7lw77gu7z7a
#### Datacap Allocated
> 1000.00TiB
#### Signer Address
> f1hhippi64yiyhpjdtbidfyzma6irc2nuav7mrwmi
#### Id
> 53865818-9130-4cb0-be34-f6d8d1e4984e
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceam32ptvfsvknrzs2ttkl7briqb3lpgp6xyyomsfqvtrzwtlja3um

**Comment by IreneYoung** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceatsensxqv6n3iaou7447i6dcx4ivbxc3lxycghhq2olacyqyjg3e 
#### Address 
> f1bg3khvfgh6v4n37oxyoy7rzuh74r7lw77gu7z7a
#### Datacap Allocated
> 1000.00TiB
#### Signer Address
> f1d4gmpqz3execjj2wvrxuuhvbms5mzh7t7yqrviq
#### Id
> 53865818-9130-4cb0-be34-f6d8d1e4984e
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceatsensxqv6n3iaou7447i6dcx4ivbxc3lxycghhq2olacyqyjg3e

**Comment by BlockMakeronline** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedz542onwqh2u4t3pleikq66qjhidl5hj4aj55ageb6ed6qckgwbg 
#### Address 
> f1bg3khvfgh6v4n37oxyoy7rzuh74r7lw77gu7z7a
#### Datacap Allocated
> 1.95PiB
#### Signer Address
> f1o3twrcpwjtpcd4q36lpq4qmy2qfbgtyy5h6tsty
#### Id
> 84200a4d-dd71-4b7d-95e1-cf87d7f1f72a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedz542onwqh2u4t3pleikq66qjhidl5hj4aj55ageb6ed6qckgwbg

**Comment by cryptowhizzard** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecfltniqlrvr5oqwizqlbttsvizodcdycehel2aahkhcjk6chijbe 
#### Address 
> f1bg3khvfgh6v4n37oxyoy7rzuh74r7lw77gu7z7a
#### Datacap Allocated
> 1.95PiB
#### Signer Address
> f1krmypm4uoxxf3g7okrwtrahlmpcph3y7rbqqgfa
#### Id
> 84200a4d-dd71-4b7d-95e1-cf87d7f1f72a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecfltniqlrvr5oqwizqlbttsvizodcdycehel2aahkhcjk6chijbe

**Comment by Trevor-K-Smith** [comment]
checker:manualTrigger

**Comment by Trevor-K-Smith** [comment]
checker:manualTrigger

**Comment by Trevor-K-Smith** [comment]
checker:manualTrigger

**Comment by Trevor-K-Smith** [comment]
checker:manualTrigger

**Comment by Trevor-K-Smith** [comment]
checker:manualTrigger

**Comment by Trevor-K-Smith** [comment]
> ## DataCap Allocation requested
> ### Request number 5
> #### Multisig Notary address
> > f01858410
> 
> #### Client address
> > f1bg3khvfgh6v4n37oxyoy7rzuh74r7lw77gu7z7a
> 
> #### DataCap allocation requested
> > 1.70PiB
> 
> #### Id
> > 3040d983-ee08-49a5-9dfc-c7fdd8d026e1

test

**Comment by Trevor-K-Smith** [comment]
Seeking next allocation of datacap on this dataset

**Comment by flyworker** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedfpri43xtypbupsg3tba2xvp7gn3vdh7piizg2lzwkyhbqqxo374 
#### Address 
> f1bg3khvfgh6v4n37oxyoy7rzuh74r7lw77gu7z7a
#### Datacap Allocated
> 10.23GiB
#### Signer Address
> f1hlubjsdkv4wmsdadihloxgwrz3j3ernf6i3cbpy
#### Id
> 7ffaf634-35da-4f63-b21d-70cdfc9a217a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedfpri43xtypbupsg3tba2xvp7gn3vdh7piizg2lzwkyhbqqxo374

**Comment by cryptowhizzard** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb6kvdb4rbkzgpsp4ovkfhbfaonc6vu3ji7w6tcsyfp55v7cw6ols 
#### Address 
> f1bg3khvfgh6v4n37oxyoy7rzuh74r7lw77gu7z7a
#### Datacap Allocated
> 10.23GiB
#### Signer Address
> f1krmypm4uoxxf3g7okrwtrahlmpcph3y7rbqqgfa
#### Id
> 7ffaf634-35da-4f63-b21d-70cdfc9a217a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb6kvdb4rbkzgpsp4ovkfhbfaonc6vu3ji7w6tcsyfp55v7cw6ols

**Comment by Trevor-K-Smith** [comment]
@simonkim0515 @raghavrmadya 

How do i get another allocation of datacap on this dataset? 

It currently has 29GiB of datacap but does not seem to be in another DataCap Allocation requested state

**Comment by Trevor-K-Smith** [comment]
@simonkim0515 @raghavrmadya 

How do i get additional datacap here? 

Address has 29GiB of datacap, but does not seem to autotriggering its next allocation

**Comment by GhostByteInc** [comment]
@simonkim0515 @raghavrmadya @Kevin-FF-USA @galen-mcandrew 

Hello

Kindly pinging again as applications continue to sit with no movement. Can i please be informed on what the issue/holdup/waiting point for this application is?

Thanks,

--Trevor K Smith

**Comment by dkkapur** [comment]
<img width="1005" alt="Screen Shot 2023-03-07 at 12 16 27 AM" src="https://user-images.githubusercontent.com/2343218/223363630-4adfac4e-24e6-431b-945f-1b220a212a63.png">

Here's what I see for the client in terms of DataCap allocations that have actually been allocated. This does track with the commends in the issue, however SA bot seems to be doing the math wrong on this as a result of a few open proposals that didn't get closed out. @simonkim0515 can you follow-up and get this in the backlog for a patch? 

In the meantime, I'm pushing an allocation request manually. 

Total allocated: 
125 TiB + 1000 TiB + 1996 TiB + 0.93 TiB = ~3121 TiB

Per largest allocation of 1996 TiB, going to push the remainder of the DataCap out as a proposal to notaries to review. This is 5120 TiB (5 PiB) - 3121 TiB = 1999 TiB.

**Comment by dkkapur** [comment]
## DataCap Allocation requested

### Request number 8
#### Multisig Notary address
> f01858410

#### Client address
> f1bg3khvfgh6v4n37oxyoy7rzuh74r7lw77gu7z7a

#### DataCap allocation requested
> 1999 TiB

#### Id
> 7ffaf634-35da-4f63-b21d-70cdfc9a217b

**Comment by GaryGJG** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced53yy43gw7zud5zfgjjfucxsa7i4kwu5bqes7jgpgngcxn52jvdi 
#### Address 
> f1bg3khvfgh6v4n37oxyoy7rzuh74r7lw77gu7z7a
#### Datacap Allocated
> 1.95PiB
#### Signer Address
> f1zffqhxwq2rrg7rtot6lmkl6hb2xyrrseawprzsq
#### Id
> 7ffaf634-35da-4f63-b21d-70cdfc9a217b
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced53yy43gw7zud5zfgjjfucxsa7i4kwu5bqes7jgpgngcxn52jvdi

**Comment by cryptowhizzard** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceajmpqvsylawv5gjhb53ja7x7bzn2vhbpvglwksreohyt2nruho7k 
#### Address 
> f1bg3khvfgh6v4n37oxyoy7rzuh74r7lw77gu7z7a
#### Datacap Allocated
> 1.95PiB
#### Signer Address
> f1krmypm4uoxxf3g7okrwtrahlmpcph3y7rbqqgfa
#### Id
> 7ffaf634-35da-4f63-b21d-70cdfc9a217b
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceajmpqvsylawv5gjhb53ja7x7bzn2vhbpvglwksreohyt2nruho7k

**Comment by data-programs** [comment]
<img width="32" alt="KYC" Verified src="https://stable.filplus.storage/images/filplus-kyc-verified-badge.png"/>

This user’s identity has been verified through [filplus.storage](https://filplus.storage)
