### ISSUE TITLE
[DataCap Application] Bangtuike Technology Co., Ltd

### ISSUE THREAD

**Issue by Joshua-zhao** [filecoin-project/filecoin-plus-large-datasets#625]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Bangtuike Technology Co., Ltd
- Website / Social Media: http://www.bangtuike.com.cn/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 3PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100TiB
- On-chain address for first allocation: f1zlkjssrmcgwjxybkc4xwjprte4i5owqjijz3tdy

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Bangtuike Technology Co., Ltd established in 2015, 
located in Beijing China, provides advertisement serving and content delivery services.

The business of Bantuike includes:
1. Enterprise promotion - promote enterprise to targeted clients.
2. Media promotion - promote media content to potential readers to increase pageview conversion rate 
                                    over platforms like Kuaishou, Toutiao etc.
3. Rich content delivery - deliver advertisement including videos, pictures and articles over platforms like Kuaishou, Toutiao etc.

From 2015 to present, Bangtuike has helped hundreds of companies and thousands of media 
to increase their viewable impression with more then 10 million target audience and 
covering 100 cities in China.

```
What is the primary source of funding for this project?
```

Investment from a VC called Follow the Seed (https://followtheseed.vc/)
```
What other projects/ecosystem stakeholders is this project associated with?
```

none
```
## Use-case details

Describe the data being stored onto Filecoin
```
public advertisements including video, picture and articles.

Data set: 
1. Articles (text, images, videos included): 
    * 200 post/ day * 365 days * 20MB/ post => 1.4T/ year * 7 year = 9.8TB
2. Video ads
    *  240 ads/ day * 365 days * 500MB => 41.8TB/ year * 4 year = 167.2TB
3. Third party video
    * 2500 video/ day * 365 days * 30MB => 26.1TB/ year * 4年 = 104.4TB

```
Where was the data in this dataset sourced from?
```

public advertisement data backup in company inernal storage
```
Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```

https://github.com/HaiFangHui/ADs-demo
```        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```

advertisements data is public
```
What is the expected retrieval frequency for this data?
```

Static data. Retrieval once a year for internal needs
```
For how long do you plan to keep this dataset stored on Filecoin?
```

1-2 years
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```

Asian-pacific and America
```
How will you be distributing your data to storage providers? Is there an offline data transfer process?
```

supporting online and offline data transfer depending on the preference of storage providers.
```
How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```

we will select SPs who could meet our requirements in terms of storage cost, storage service and geographical location.
```
How will you be distributing deals across storage providers?
```

3-10 SPs to have the data backup is our preference, and we will follow the filecoin guideline to make our data more reliable and secure.
current plan is listed below:
1 replica of data allocated to the SP located in Singapore,
1 replica of data allocated to the SP located in HK,
1 replica of data allocated to the SP located in US, which is under dicusstion;
The detailed allocation plan with more SPs is being worked on, and details will be shared here once ready.
current distribution plan is:
f01740934    Location: US
f01852363    Location: SGP
f0520660      Location: SGP
```
Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```

we will reach you when needed.
```

**Comment by Alex11801** [comment]
@Joshua-zhao Hi! Can you explain why your company need such a large volume of dataset? Because it seems that you dont provide any storage service on your website or app.

**Comment by raghavrmadya** [comment]
Please add filecoin address

**Comment by Joshua-zhao** [comment]
> Please add filecoin address

updated the client address

**Comment by Joshua-zhao** [comment]
> @Joshua-zhao Hi! Can you explain why your company need such a large volume of dataset? Because it seems that you dont provide any storage service on your website or app.

we will dispatch the datacap to several SPs and some SP are under discussion.
the data are backup for inernal use but they are public. filecoin is a good way for us to make it public

**Comment by Sunnyiscoming** [comment]
What's the relationship between you and organization?
Can you provide more data samples or materials to show that you have 5 pb data already.  The data samples you provided have three same videos and you also provide videos from other platforms, such as Daodao. Can you explain about that.
App can not be downloaded directly, so I am doubt with users volumn.
![mmexport1661825461762](https://user-images.githubusercontent.com/105098820/187333482-23cdd884-c8f3-4f61-bfd0-738ae069228f.jpg)
![Screenshot_20220830_100735_com tencent mm](https://user-images.githubusercontent.com/105098820/187333487-d1a93aaf-0ee8-487d-96d1-03ad5909024e.jpg)

Could you send an email to filplus-app-review@fil.org with your official domain in order to confirm your identity? Email name should includes the issue id #625.

**Comment by raghavrmadya** [comment]
No response leading to closure

**Comment by Joshua-zhao** [comment]
> @Joshua-zhao Hi! Can you explain why your company need such a large volume of dataset? Because it seems that you dont provide any storage service on your website or app.

hi Alex, Bantuike is a AD serving compay, and it provides AD providers channels to post their ADs to target audience over platforms like kuaishou(similar with tiktok), and the public AD data is backuped for internal use. 
this is a breakdown of business data:
Data set: 
1. Articles (text, images, videos included): 
    * 200 post/ day * 365 days * 20MB/ post => 1.4T/ year * 7 year = 9.8TB
2. Video ads
    *  240 ads/ day * 365 days * 500MB => 41.8TB/ year * 4 year = 167.2TB
3. Third party video
    * 2500 video/ day * 365 days * 30MB => 26.1TB/ year * 4年 = 104.4TB

and you can find the sample data link: 
https://github.com/HaiFangHui/ADs-demo

**Comment by Joshua-zhao** [comment]
> What's the relationship between you and organization? Can you provide more data samples or materials to show that you have 5 pb data already. The data samples you provided have three same videos and you also provide videos from other platforms, such as Daodao. Can you explain about that. App can not be downloaded directly, so I am doubt with users volumn and content. ![mmexport1661825461762](https://user-images.githubusercontent.com/105098820/187333482-23cdd884-c8f3-4f61-bfd0-738ae069228f.jpg) ![Screenshot_20220830_100735_com tencent mm](https://user-images.githubusercontent.com/105098820/187333487-d1a93aaf-0ee8-487d-96d1-03ad5909024e.jpg)
> 
> Could you send an email to [filplus-app-review@fil.org](mailto:filplus-app-review@fil.org) with your official domain in order to confirm your identity? Email name should includes the issue id #625.


What's the relationship between you and organization? 
* I am helping my data client to apply the datacap

Can you provide more data samples or materials to show that you have 5 pb data already.
* Bantuike is a AD serving company, and it provides AD providers channels to post their ADs to target audience over platforms like kuaishou(similar with tiktok), and the public AD data is backuped for internal use.
this is a breakdown of business data:
Data set:
Articles (text, images, videos included):
200 post/ day * 365 days * 20MB/ post => 1.4T/ year * 7 year = 9.8TB
Video ads
240 ads/ day * 365 days * 500MB => 41.8TB/ year * 4 year = 167.2TB
Third party video
2500 video/ day * 365 days * 30MB => 26.1TB/ year * 4年 = 104.4TB
and you can find the sample data link:
https://github.com/HaiFangHui/ADs-demo

The data samples you provided have three same videos and you also provide videos from other platforms, such as Daodao. Can you explain about that.
* Bangtuike is a AD serving company and the business is to deliver AD providers' AD materials to target audience over different platforms.

Can you explain about that. App can not be downloaded directly, so I am doubt with users volumn and content. 
* Apple store charges too much, so the app is offline from Apple store. however the business of Bantuike is to B2B, so there is no problem with the client to download it's app

Could you send an email to [filplus-app-review@fil.org](mailto:filplus-app-review@fil.org) with your official domain in order to confirm your identity? Email name should includes the issue id #625.
* Bangtuike will email to filplus with offical domain asap

**Comment by Joshua-zhao** [comment]
@raghavrmadya  @Sunnyiscoming 
The KYC email is listed below and please kindly proceed the approval process. 
Many thanks!

![微信图片_20220906125714](https://user-images.githubusercontent.com/22786714/188550310-23384fbc-0298-47e4-98a7-8de850669e64.jpg)

**Comment by raghavrmadya** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 3PiB

**Expected weekly DataCap usage rate**

> 100TiB

**Client address**

>f1zlkjssrmcgwjxybkc4xwjprte4i5owqjijz3tdy

**Comment by swatchliu** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecitx6zg3d3a64vbriruaiptdrreihigtpurmloajixj6amxr4png 
#### Address 
> f1zlkjssrmcgwjxybkc4xwjprte4i5owqjijz3tdy
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1yh6q3nmsg7i2sys7f7dexcuajgoweudcqj2chfi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecitx6zg3d3a64vbriruaiptdrreihigtpurmloajixj6amxr4png

**Comment by kernelogic** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebwxog2tw3u5co6wytzocrn7nnexhatmk43ombmip553npqov7hoe 
#### Address 
> f1zlkjssrmcgwjxybkc4xwjprte4i5owqjijz3tdy
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebwxog2tw3u5co6wytzocrn7nnexhatmk43ombmip553npqov7hoe

**Comment by BigD-Exchange** [comment]
@Joshua-zhao Hi! Great to see you have gotten approval for DataCap. If you are looking for storage providers to store these data or have any questions, please visit #bigdata-exchange on Filecoin Slack or reply here. 

We have strong demand from a diverse group of SPs, who are actively looking to onboard more data.

**Comment by Tom-OriginStorage** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedd3gcvje3lna56qhslvttuub656xmpxkhati6jhd4use54kcudm4 
#### Address 
> f1zlkjssrmcgwjxybkc4xwjprte4i5owqjijz3tdy
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1q6bpjlqia6iemqbrdaxr2uehrhpvoju3qh4lpga
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedd3gcvje3lna56qhslvttuub656xmpxkhati6jhd4use54kcudm4

**Comment by newwebgroup** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceao2ujo55uh357o2n5ozqotqeg7xtr2gcqbkido7i7ktk6ls7vmy2 
#### Address 
> f1zlkjssrmcgwjxybkc4xwjprte4i5owqjijz3tdy
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1e77zuityhvvw6u2t6tb5qlnsegy2s67qs4lbbbq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceao2ujo55uh357o2n5ozqotqeg7xtr2gcqbkido7i7ktk6ls7vmy2

**Comment by newwebgroup** [comment]
It is found that the client only cooperates with one SPs.
Through the communication between Zoom and Clinet, the client said that the DC quota for the first two rounds was too small, and the DC offline transportation took time. At the beginning of the next round, the proportion of SPs will be adjusted
We will continue to pay attention.

**Comment by newwebgroup** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced4hv6l54wwtasae7xp72uasqt6ytxufgcddwbki4ckiyhwyc2nla 
#### Address 
> f1zlkjssrmcgwjxybkc4xwjprte4i5owqjijz3tdy
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1e77zuityhvvw6u2t6tb5qlnsegy2s67qs4lbbbq
#### Id
> 7a670513-cc2e-408f-9276-b6906a948e85
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced4hv6l54wwtasae7xp72uasqt6ytxufgcddwbki4ckiyhwyc2nla

**Comment by NDLABS-OFFICE** [comment]
It is recommended that the store look for more sp cooperation.

**Comment by kernelogic** [comment]
Will keep an eye on next allocation

**Comment by kernelogic** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceccr7khn2vmtnt5qcza3aksmtr3aothaiss26tc5pg6hinvqwku42 
#### Address 
> f1zlkjssrmcgwjxybkc4xwjprte4i5owqjijz3tdy
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### Id
> 7a670513-cc2e-408f-9276-b6906a948e85
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceccr7khn2vmtnt5qcza3aksmtr3aothaiss26tc5pg6hinvqwku42

**Comment by filplus-checker** [comment]
## DataCap and CID Checker Report[^1]
 - Organization: `Bangtuike Technology Co., Ltd`
 - Client: `f1zlkjssrmcgwjxybkc4xwjprte4i5owqjijz3tdy`
### Storage Provider Distribution
The below table shows the distribution of storage providers that have stored data for this client.

If this is the first time a provider takes verified deal, it will be marked as `new`.

For most of the datacap application, below restrictions should apply.
 - Storage provider should not exceed 25% of total datacap.
 - Storage provider should not be storing duplicate data for more than 20%.
 - Storage provider should have published its public IP address.
 - All storage providers should be located in different regions.

⚠️ [f0520660](https://filfox.info/en/address/f0520660) has sealed 86.23% of total datacap.

⚠️ [f0520660](https://filfox.info/en/address/f0520660) has unknown IP location.

⚠️ [f01776264](https://filfox.info/en/address/f01776264) has unknown IP location.

⚠️ All storage providers are located in the same region.

| Provider                                              | Location | Total Deals Sealed | Percentage | Unique Data | Duplicate Deals |
| :---------------------------------------------------- | -------: | -----------------: | ---------: | ----------: | --------------: |
| [f0520660](https://filfox.info/en/address/f0520660)   |  Unknown |         125.06 TiB |     86.23% |  125.06 TiB |           0.00% |
| [f01776264](https://filfox.info/en/address/f01776264) |  Unknown |          19.97 TiB |     13.77% |   19.97 TiB |           0.00% |

![Provider Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/625/1671097548028.png)
### Deal Data Replication
The below table shows how each many unique data are replicated across storage providers.
- No more than 25% of unique data are stored with less than 4 providers.

⚠️ 100.00% of deals are for data replicated across less than 4 storage providers.

| Unique Data Size | Total Deals Made | Number of Providers | Deal Percentage |
| ---------------: | ---------------: | ------------------: | --------------: |
|       145.03 TiB |       145.03 TiB |                   1 |         100.00% |

![Replication Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/625/1671097548770.png)
### Deal Data Shared with other Clients
The below table shows how many unique data are shared with other clients.
Usually different applications owns different data and should not resolve to the same CID.

✔️ No CID sharing has been observed.

[^1]: To manually trigger this report, add a comment with text `checker:manualTrigger`

**Comment by lvschouwen** [comment]
checker:manualTrigger

**Comment by cryptowhizzard** [comment]
checker:manualTrigger

**Comment by cryptowhizzard** [comment]
Hello,

Nothing of the data stored is retrievable here.

@Joshua-zhao can you give us some information about how you intend to fix this?
The data in Fil+ needs to be retrievable. Second the data needs to be spread amongst 4 SP's / organizations at minimum.

**Comment by Joshua-zhao** [comment]
@cryptowhizzard 
As someone said it's impacted by the slight economic climate, this is a difficult time for SPs, and my SP is also facing the common problems.
Nevertheless, I will firstly try to fix the public IP and retrieval problem as soon as possilbe. 
Secondly, I have been working on dispatching the data to different SPs, and hopefully this will be achieved recently 
Everyone should understand that each SP bears burden to support Filecoin Network, and not every SP is ready all the time to provide their service. This indeed needs some patience just like SPs are waiting for Filecoin infrastructure to be mature enough which has been taking ages.
Thank you so much for reminding me those problems during Chinese New Year holidays, and wish you have a prosperous and harmonious new year!

**Comment by cryptowhizzard** [comment]
Hi @Joshua-zhao 

Sorry for the disturbance during Chinese New Year Holiday. I understand what you are writing however the economic climate should not be a reason for an SP to cancel the agreements and rules in place.

Please update us when you are ready to support retrieval, i will take a look to move forward then.
