### ISSUE TITLE
[DataCap Application] <olevod> - <olevod>

### ISSUE THREAD

**Issue by moonlight233** [filecoin-project/filecoin-plus-large-datasets#626]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name:  olevod
- Website / Social Media: https://www.olevod.com/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 1 PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100 TiB
- On-chain address for first allocation: f3qege2s2qiyrlotcym2h6cz7fhchv5zo2gvcnwmljyimrq6dosefphbpl4vncynkjcdzhdvh4xbw2aumb2aqa

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
olevod theater is an online theater for Chinese, including movies, series, variety shows, animation and other tens of thousands of videos online.

What is the primary source of funding for this project?
Ad cost while video is playing.

What other projects/ecosystem stakeholders is this project associated with?
No.

## Use-case details

Describe the data being stored onto Filecoin
We will store video backup on filecoin

Where was the data in this dataset sourced from?
Copyright owners we work with.

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
https://www.olevod.com/index.php/vod/play/id/37547/sid/1/nid/1.html
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
Yes, all the data will be posted on the website.

What is the expected retrieval frequency for this data?
We plan to check the network 5 times a month.

For how long do you plan to keep this dataset stored on Filecoin?
3 years.

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
China, Singapore, Canada

How will you be distributing your data to storage providers? Is there an offline data transfer process?
Yes. We'll use offlinne data transmission.

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
Major characteristics about choosing the storage providers:
- location
- transmission speed
- deal success rate
- previous experience of real data storage
- stability of their nodes

How will you be distributing deals across storage providers?
All storage deals will be verified if they have enough FIL to pledge and their equipment can handle.

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
Yes, we do.

**Comment by Sunnyiscoming** [comment]
![image](https://user-images.githubusercontent.com/105098820/187335334-3ab6f102-c020-4082-a991-0fb4636bbba8.png)

- This site only provides WEB page services. This site does not store or make any videos, and does not assume any disputes and legal responsibilities arising from the legality and health of the content.
  As website showed above. The website do not authorized by any content owner and do not store them.

**Comment by Sunnyiscoming** [comment]
Any update here? @moonlight233

**Comment by raghavrmadya** [comment]
No reply
