### ISSUE TITLE
[DataCap Application] YunZhiYi - V8 Intelligent Video

### ISSUE THREAD

**Issue by BBQFIL** [filecoin-project/filecoin-plus-large-datasets#630]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: YunZhiYi-V8Intelligent Video
- Website / Social Media:https://www.xlink.cn/products/v8/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):500TiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):100TiB
- On-chain address for first allocation:f1zf7krnsnk5qyivabw4unkp6z5jxlslalp45gpvy

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
YunZhiYi Co., Ltd. is a high-tech enterprise applying cloud computing, big data and artificial intelligence technology to realize data asset operation. Our business covers many industries and is committed to the construction of big data industrial ecological chain. We use advanced technology to realize the whole life cycle management of data from collection, processing to application. Excellent solutions have been successfully applied to the Internet, finance, government, intelligent manufacturing and other fields.
V8 Intelligent Video uses the existing new information infrastructure platform to provide shared resources for the establishment of smart city security management system for mobile communication, traffic monitoring, urban security video monitoring, meteorological and environmental protection monitoring (PM2.5), water quality detection, fire monitoring and early warning, so as to lay a foundation for the sharing of smart city management platform.
YunZhiYi is committed to building the ecosystem of data and application based on Internet 3 (Web3.0), and building EOT data side chain based on EOS, providing data center and data application platform for Internet and big data industry transformation from Internet plus to Internet plus. This will be a scalable, low latency, high interaction, and scalable security chain domain guardrail distributed network platform. Realize the scene display of various objects and data under the jurisdiction of government departments.
```

What is the primary source of funding for this project?
```
It is from the investment of shareholders and the usage fee of users who use this platform.
```

What other projects/ecosystem stakeholders is this project associated with?
```
There are currently no other project/ecosystem stakeholders involved. 
```

## Use-case details

Describe the data being stored onto Filecoin
```
Various video monitoring data of customers
```

Where was the data in this dataset sourced from?
```
 All data is provided by the user.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://drive.google.com/file/d/1bY8gHCfuDO3aKFpp7qaWawELXUVD5_Cu/view?usp=sharing
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes, anyone who store the data and are interested in it can read the data. 
```

What is the expected retrieval frequency for this data?
```
Anytime when clients wants to search.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
This data will be permanently stored in Filecoin.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
in China
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
 We are considering both online and offline data transfers.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
Our criteria of storage provider selection are as follows:
- Location: chian
- Companies with facilities that comply with IDC operating regulations (electricity, network, etc.).
- Companies with real data storage experience.
- Companies operating nodes stable (transmission speed, transaction success rate, etc.).
```

How will you be distributing deals across storage providers?
```
We are planning to distribute evenly to companies that meet the above criteria.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, we have enough capital. It comes from our shareholders' funds and our customers.
```

**Comment by Sunnyiscoming** [comment]
Various video monitoring data of customers do not belongs to open data. I think this dataset can not be approved.

**Comment by Sunnyiscoming** [comment]
Any update here? @BBQFIL

**Comment by BBQFIL** [comment]
@Sunnyiscoming

**Comment by BBQFIL** [comment]
@Sunnyiscoming 
I can understand your concern.
The data samples provided on this page are for reference only.
In the future, we will choose to store public video data in filecoin, such as forest fire prevention monitoring, air quality monitoring, vehicle exhaust quality monitoring, etc.
Most of our orders come from the public sector, and most of our data can be viewed in real time on the public platform.

**Comment by Sunnyiscoming** [comment]
FIL+ Large dataset is set for the existing open data set application. Please specify the type of data, the composition of data, the number of backups, and provide enough data samples to prove that.

**Comment by BBQFIL** [comment]
@Sunnyiscoming 
Yes, of course
The data type mainly includes video files in MP4 and other formats
Data is mainly generated by different dates and time periods, as well as different monitoring platforms.
We plan to select 4 to 8 nodes for backup in the north, south and eastern coastal areas of China. The specific node selection conditions have been described in the main body.
Data sample:
https://www.aliyundrive.com/s/CWbJcG9fqrL    25vd
https://www.aliyundrive.com/s/9WsMwFSrwBg    y7d7
https://www.aliyundrive.com/s/9sn35LQPMgH    1l2l
https://www.aliyundrive.com/s/awfSSw6q3HM    3bz5
https://www.aliyundrive.com/s/YFMAy5WXKY4    89bb
https://www.aliyundrive.com/s/w4Qaf35aTAS    q5q5
https://www.aliyundrive.com/s/Mra39ri4MUj    v8m8

**Comment by Sunnyiscoming** [comment]
Are these surveillance videos public data?

**Comment by BBQFIL** [comment]
@Sunnyiscoming 
Yes, these data are public data.
Our customers will conduct live video broadcast in various channels according to specific business scenarios, and will save historical data for at least one year.
We want to store historical data on filecoin to reduce our storage costs.

Here are some examples.
https://zj.zjol.com.cn/live.html?id=1935447&native=1
https://zj.zjol.com.cn/live.html?id=1935371&native=1

**Comment by Carohere** [comment]
Hi @BBQFIL,
> @Sunnyiscoming Yes, these data are public data. Our customers will conduct live video broadcast in various channels according to specific business scenarios, and will save historical data for at least one year. We want to store historical data on filecoin to reduce our storage costs.

1. by public data do you mean everyone can view it or as an open database? 
> Here are some examples. https://zj.zjol.com.cn/live.html?id=1935447&native=1 https://zj.zjol.com.cn/live.html?id=1935371&native=1

2. the first one is no longer can be viewed and the second one has the logo of Hangzhou Highway Police on it, are they your customer? 
>https://drive.google.com/file/d/1bY8gHCfuDO3aKFpp7qaWawELXUVD5_Cu/view?usp=sharingand 

3. this neighborhood surveillance video has youku's logo which is a video platform. did u upload it there or is it from your customer as well? Plus, could you share the requirements for setting up surveillance cameras in public places in china? 
4. filecoin is centered on decentralized storage. may i know why you plan to store all the replicas in china? 

Thanks!

**Comment by BBQFIL** [comment]
> 你好@BBQFIL,
> 
> > @Sunnyiscoming是的，这些数据是公开数据。我们的客户会根据具体的业务场景在各个渠道进行视频直播，并将历史数据保存至少一年。我们希望将历史数据存储在 filecoin 上以降低我们的存储成本。
> 
> 1. 你所说的公共数据是指每个人都可以查看它还是作为一个开放的数据库？
> 
> > 这里有些例子。[https://zj.zjol.com.cn/live.html?id=1935447&native=1 ](https://zj.zjol.com.cn/live.html?id=1935447&native=1) https://zj.zjol.com.cn/live.html?id=1935371&native=1
> 
> 2. 第一个已经看不到了，第二个上面有杭州公路警察的标志，他们是你的客户吗？
> 
> > https://drive.google.com/file/d/1bY8gHCfuDO3aKFpp7qaWawELXUVD5_Cu/view?usp=sharingand
> 
> 3. 这个小区监控视频有优酷的标识，这是一个视频平台。你是上传到那里的还是从你的客户那里上传的？另外，您能分享一下在中国公共场所设置监控摄像头的要求吗？
> 4. filecoin 以去中心化存储为中心。我可以知道你为什么打算把所有的复制品都存放在中国吗？
> 
> 谢谢！

HI @Carohere 
1. Not all video data are publicly available. We will only store the part that the customer agrees to display publicly in filecoin.
2. The public security department is not our customer, but those video data are publicly available, so anyone can apply for using them at any time (including the public security department).
3. This video was uploaded to youku for the convenience of notaries to view the samples. Therefore, the watermark of youku will be displayed.
4. Because our V8 business is only deployed in China for the time being, we hope to find storage providers around customers to store data, which is also to facilitate customers to quickly obtain data.
We hope to store the public video data in filecoin, which is to reduce our server cost and improve our brand value. We think this is completely in line with the original intention of filecoin plus, and we hope that the notary can pass our application.

**Comment by BBQFIL** [comment]
It should be pointed out that, considering the cost and rationality, it is impossible for us to display all the public videos on a certain page at this stage.
So although the video data is public, you need to submit an application to us before you can get the call link. This is not our intention, but it is completely in cost consideration.
Therefore, we are willing to store data in filecoin. We hope that anyone (especially customers) can quickly obtain these data in the future (the retrieval market is fully available and efficient).

**Comment by Sunnyiscoming** [comment]
https://zj.zjol.com.cn/live.html?id=1935371&native=1
These video is uploaded by users of another platform. Are you authorized to store this data on the filecoin network?
How many copies will you store?
What's the relationship between you and the organization?
Can you provide more detailed information about other storage providers participated in this program, such as you can list SPs you have contacted with at present?

**Comment by BBQFIL** [comment]
@Sunnyiscoming 
This is a data reference.
It is estimated to store 5-8 copies.
I'm responsible for interfacing with filecoin.
We will start to find the right storage provider after the application is approved.

**Comment by BBQFIL** [comment]
any questions？

**Comment by Sunnyiscoming** [comment]
The sample data needs to be from the data you are going to store, and the data needs to be public data, which means your organization's data, or other data authorized for storage on the Filecoin network.

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 500PiB

**Expected weekly DataCap usage rate**

> 100TiB

**Client address**

>f1zf7krnsnk5qyivabw4unkp6z5jxlslalp45gpvy

**Comment by Carohere** [comment]
Hi @simonkim0515, may I know why are you confident in triggering this app?

**Comment by simonkim0515** [comment]
Hi @Carohere, I triggered this app because the application was filled out. Notaries are welcomed to come and do a KYC check on this application. 
Please look at this to understand the governance team role. https://github.com/filecoin-project/notary-governance/discussions/606

**Comment by Carohere** [comment]
Hi @simonkim0515, thanks for the clarification. However I don't think step three was fully done here as the the governance team's queries have not been answered yet.

**Comment by BBQFIL** [comment]
Of course, the data samples are completely from our own data. If necessary, we can provide more.

**Comment by raghavrmadya** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 500TiB

**Expected weekly DataCap usage rate**

> 100TiB

**Client address**

>f1zf7krnsnk5qyivabw4unkp6z5jxlslalp45gpvy

**Comment by raghavrmadya** [comment]
We have 
### Datacap Request Trigger
**Total DataCap requested**

> 500TiB

**Expected weekly DataCap usage rate**

> 100TiB

**Client address**

>f1zf7krnsnk5qyivabw4unkp6z5jxlslalp45gpvy

**Comment by raghavrmadya** [comment]
The governance team is unable to block this application as the client has answered the questions. The quality of response does vary. If the community and notaries don't feel confident, we encourage you to speak out. Thank you @Carohere and @NDLABS-OFFICE for your comments thus far on this application

**Comment by kernelogic** [comment]
I cannot access the data samples as it requires Chinese cellphone number to register. Is it possible upload them to google drive? Do you have a screenshot of your total data size of between 50T~100T?

```
Data sample:
https://www.aliyundrive.com/s/CWbJcG9fqrL 25vd
https://www.aliyundrive.com/s/9WsMwFSrwBg y7d7
https://www.aliyundrive.com/s/9sn35LQPMgH 1l2l
https://www.aliyundrive.com/s/awfSSw6q3HM 3bz5
https://www.aliyundrive.com/s/YFMAy5WXKY4 89bb
https://www.aliyundrive.com/s/w4Qaf35aTAS q5q5
https://www.aliyundrive.com/s/Mra39ri4MUj v8m8
```

**Comment by BBQFIL** [comment]
@kernelogic 
Ok, I have uploaded the data sample to google drive.
And attached a screenshot of a part of the video data volume
https://drive.google.com/file/d/15eV9zGRhaxFAbsYFzbs3ctbVVoAxywyW/view?usp=sharing, https://drive.google.com/file/d/1KgdALMZhifdxcNNzbdGGlPS8ROXQbnQG/view?usp=sharing, https://drive.google.com/file/d/1LHq4Yhvhrxmn3J-8S8XLrBOv5eKMln2A/view?usp=sharing, https://drive.google.com/file/d/1Xeug2uuXc1S7mphKJmTFpFCT6EjxVssC/view?usp=sharing, https://drive.google.com/file/d/1gw4AU_r9bLHk8lPpyfbCtJXlf2jw9nsK/view?usp=sharing, https://drive.google.com/file/d/1vCd1diwXsmH6XbiMKpL6l4FkZ1D9mltF/view?usp=sharing, https://drive.google.com/file/d/1xdhaOQF1gtwNOnWunrKCm2VK7LjPYuCJ/view?usp=sharing

![微信截图_20221129084523](https://user-images.githubusercontent.com/80088593/204414832-ce1c553f-987c-4569-a234-313d69da4975.png)

**Comment by kernelogic** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebydxgjiqctcmbk3phgbryliy4pqqko73zmkhsed7keobx4epagmm 
#### Address 
> f1zf7krnsnk5qyivabw4unkp6z5jxlslalp45gpvy
#### Datacap Allocated
> 25.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### Id
> c0d13e6b-a007-424a-bae4-2748d79fb73c
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebydxgjiqctcmbk3phgbryliy4pqqko73zmkhsed7keobx4epagmm

**Comment by newwebgroup** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedpjv5wgfynh6dcyzhi3pdzaml3otynzgtcqkv4smaul4q7c5caxc 
#### Address 
> f1zf7krnsnk5qyivabw4unkp6z5jxlslalp45gpvy
#### Datacap Allocated
> 25.00TiB
#### Signer Address
> f1e77zuityhvvw6u2t6tb5qlnsegy2s67qs4lbbbq
#### Id
> c0d13e6b-a007-424a-bae4-2748d79fb73c
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedpjv5wgfynh6dcyzhi3pdzaml3otynzgtcqkv4smaul4q7c5caxc

**Comment by BDEio** [comment]
@BBQFIL Hi! Great to see that you have gotten approval for DataCap!
BDE is a verified deals auction house helping you to get paid storing your valuable data with reliable storage providers. If you need any help, please get in touch.

**Comment by Sunnyiscoming** [comment]
Are there any problems with using datacap?

**Comment by BBQFIL** [comment]
Because of the COVID-19 control and the Chinese traditional Spring Festival, our company has a holiday, and we are ready to restart relevant activities in the spring.

**Comment by Sunnyiscoming** [comment]
Ok.
