### ISSUE TITLE
[DataCap Application] FileInAndOut - FileInAndOut

### ISSUE THREAD

**Issue by FileInAndOut** [filecoin-project/filecoin-plus-large-datasets#632]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: fileinandout
- Website / Social Media:  https://fileinandout.social
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100TiB
- On-chain address for first allocation: f1zg5poisp4an4ufzinol3rdfzbaij656s6khoxyy

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
FileInAndOut Social: Your Personal Web3 Cloud Drive with Socials.

Files (e.g. articles, images and videos etc.) are fundamental building blocks for our digital lives.

To save them securely (we called it “file in”) and share them freely (we call it “file out”) are no longer easy tasks mainly because of the growing division between countries (we think it sucks :sad:).

We build FileInAndOut (app name) with Web 3 technologies to fix those problems. Moreover, we did add a social layer in order to enable users to form community around certain contents. Since, it is naturally extended need to share contents with people more broadly and selectively. And, we hear it from our pilot users.

FileInAndOut is still in its infancy stage with fundamental features and full of possibilities. It could become a content publish platform for indie content maker (exciting :-), it would be a forum in Web 3 form and other content-and-social-oriented applications. We wish, with our communities altogether, we would evolve it, foster it and co-own it. In other major social platforms, you had been forgotten when they count “shareholders”. It is not the case here, since every users are essence to the health and success of the platform.

We are a small team (<10 member) distributed over the global, we are engineers (previously worked at Pinterest, Alibaba and etc.), trained economist (graduates from University of Chicago and University of Cambridge), aspirational brand and communities manager (worked at P&G, graduates from New York University). During last few months (from idea to MVP), we built it mainly in part-time fashion with funds from ourselves and closed friends. Moving forward, we are looking to raise funding from Venture Capital or explore the crypto-way to raise necessary fund in order to propel the project by building a content economy and hire more talents.
```

What is the primary source of funding for this project?
```
Founder  funds
```

What other projects/ecosystem stakeholders is this project associated with?
```
N/A
```

## Use-case details

Describe the data being stored onto Filecoin
```
User-generated content/audio/video, etc
```

Where was the data in this dataset sourced from?
```
User-generated content/audio/video, etc
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```

https://ipfs.io/ipfs/bafybeifuqpgsd2s36yadw5p7orvzolxwjqu3ymkysu5nfhtmvdiek66ldu
https://ipfs.io/ipfs/bafybeihxmvq5h63iugx7kxlnb3fdss7cfk7sfqxprb75tgbaszcjvb3xhu
https://ipfs.io/ipfs/bafybeifqe7lu5zcibowyy3qdsvdzzb3k6w2jgtlbahw7xlkiyitvfzqqcy
https://ipfs.io/ipfs/bafybeigptcehshusuehr6mqm2g3wa6ve6nvbueed24gs222foakl7jrroa
https://ipfs.io/ipfs/bafybeif6t3dagwzwsmlncdk66iq4ozxe3suvexo3kwuirlbicegyf2grpi
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
yes
```

What is the expected retrieval frequency for this data?
```
maybe 3-5 times/year
```

For how long do you plan to keep this dataset stored on Filecoin?
```
At least 2 years, the longer the better
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
all
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
i think both ,offline or online . Depending on the storage location, whichever is more efficient.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We plan to select different SPs in many different locations to ensure the reliability of our data, and we regularly check the data to ensure it is available.

```

How will you be distributing deals across storage providers?
```
Balanced storage to multiple SPs

```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
yes
```

**Comment by Sunnyiscoming** [comment]
https://fileinandout.social/ do not work now.
Can you provide more data information to prove that you have 5 PB data already?
Can you provide more detailed information about storage providers distribution, such as you can list SPs you have contacted with at present?

**Comment by Sunnyiscoming** [comment]
Any update here? @FileInAndOut

**Comment by FileInAndOut** [comment]
> https://fileinandout.social/ do not work now. Can you provide more data information to prove that you have 5 PB data already? Can you provide more detailed information about storage providers distribution, such as you can list SPs you have contacted with at present?

I'll provide them later.

**Comment by Sunnyiscoming** [comment]
Any update here?

**Comment by FileInAndOut** [comment]
> https://fileinandout.social/ do not work now. Can you provide more data information to prove that you have 5 PB data already? Can you provide more detailed information about storage providers distribution, such as you can list SPs you have contacted with at present?


Sorry for the late reply.
The website has been restored

At present, our overall data is about 1.5P (3000 users, 500M for each user). It is encrypted and stored on our own servers, but as IPFS becomes more and more popular and our customers grow rapidly, our servers are under more and more pressure, so we hope to gradually switch to the IPFS network and include the backup data. So we are going to apply for 5P first.

You are also welcome to download FileInandOut to use and experience.

Currently, we are communicating with some nodes in Asia. In the future, we hope to have it all over the world, so that it can be a good backup.

more data like this:
https://ipfs.io/ipfs/bafybeiflzagt76jrxonbnaiy7pxhgjoegr3cldcginwqke46ndjvq2kjiq
https://ipfs.io/ipfs/bafybeielb4gxyvsj5ivbeurarwk3fhdpjwdwae2rf4kiixk7tbvxwmxajm
https://ipfs.io/ipfs/bafkreicztgierhsbqa4hh6szb76ppu3qvgy7kblju2yykbp4hvhj3mmhgy
https://ipfs.io/ipfs/bafkreigahregetzeolvloy66nkbv7sm2eesamkf56vsi47w7xitykr4enq
https://ipfs.io/ipfs/bafkreihraeq37jb3bqlzgovggt4bc5gdjshzmuar3mkwoocymieswikwia
https://ipfs.io/ipfs/bafybeifar42mvouquudfp6swt22w2eoiorvv4wj5cz5dwx2jjxhm2iafzm
https://ipfs.io/ipfs/bafybeihvzbgnhzcn42yjbunhgsdvlnfe7qdb6q72gwngjg26sjz6tp2kre
https://ipfs.io/ipfs/bafkreifcq7ulr5ghjrwi4cgxsynrdnywdkjp3xhbtzdsegs7xwnhwcyouu
https://ipfs.io/ipfs/bafkreifxle6znlexgnxu2b44gzb6geltcmspv7xai7k73zs62e5mzynyti
https://ipfs.io/ipfs/bafkreicn2cekgc6erhkbadod4jcgab4afpxmebh5mqr45rbikqidfoom3e
https://ipfs.io/ipfs/bafybeigm4yygroirte5wpgg3brhd6t5u5dxxohs3adreh3trzxmtu7evpq
https://ipfs.io/ipfs/bafkreibzd2qitwr5kpbwqhasocwvz6yybfzek4yyu63prfbmykzpxj3nyi
https://ipfs.io/ipfs/bafybeic4bkb7dtk3gskpesazufwjkqqzni554xkpmb56v6wcxdcb4dofmy
https://ipfs.io/ipfs/bafybeia4o22yrdg7bp2emf25ebn7b5awnvx6lvl7jmuoaftlqlag52tzoe
https://ipfs.io/ipfs/bafybeig6u7wic4t3fyumskfxse2ultyewz3wlkom5td7glza4j3j5gpwze
https://ipfs.io/ipfs/bafybeibakvantopp3xfhsymic6a4ikb522m2nqgl6byg7pdipgip222kvy
https://ipfs.io/ipfs/bafkreic5fzrndpnurjvffxarnopknszoyyw4mc67xfzzacgsuy4knh3amu
https://ipfs.io/ipfs/bafybeicohukonkzzcw5mu6hmj5zliwugjlwfohozgrffyjwmfiluta6xhe
https://ipfs.io/ipfs/bafybeiecixhyesoqc45vjkhvxz3abiko5f2fdyw2mnlbnrzatxbdtyp2ii
https://ipfs.io/ipfs/bafybeihst3a4vmsi2jlcauvoi4g2ypfhd5iimekq5betni2gw37aj6c2p4
https://ipfs.io/ipfs/bafybeic3klxloctf6kzuxn7jfwti235pypr5bbpsqpgqeoknegbwnibgj4
https://ipfs.io/ipfs/bafybeicqeio7fdsyiju2tbnditg4ppqlsbt3fxzvx4liggidexc7ouojwy
https://ipfs.io/ipfs/bafybeihpq7uosqxfrad5wjkll2aelwp7vcwdu25hz4tve4aamxz5pztb5u
https://ipfs.io/ipfs/bafybeibkhi7d54qjj6ojifpo5ohu663uxbst2q6keylywktktka6ijsysq

**Comment by Sunnyiscoming** [comment]
User-generated content/audio/video, etc
If these data are all user-uploaded data, can it all be made public? I doubt it. 
If most of these data are private, I suggest you pay attention to the FIL-E project.
If all of data are public, please provide authoried evidence or other materials.

**Comment by Sunnyiscoming** [comment]
Otherwise, some data samples you provided can not be opened.

**Comment by FileInAndOut** [comment]
> User-generated content/audio/video, etc If these data are all user-uploaded data, can it all be made public? I doubt it. If most of these data are private, I suggest you pay attention to the FIL-E project. If all of data are public, please provide authoried evidence or other materials.

t's all open to the public.
Because it's a social platform similar to Twitter. We will stipulate in the user agreement that the data shall not violate international conventions and relevant laws.

Some data may not open because the network is not stable. That's why we're looking for a stable supplier. So that we can develop more quickly

**Comment by Sunnyiscoming** [comment]
Can you provide more detailed information about storage providers distribution, such as you can list SPs you have contacted with at present?
If all of data are public, please provide authoried evidence or other materials.
Please provide enough available data samples to prove that you have 5 pb data.

**Comment by Sunnyiscoming** [comment]
Close for no reply.
