### ISSUE TITLE
[DataCap Application] Hunan Tianzhou Game Technology Co., Ltd  

### ISSUE THREAD

**Issue by lixiongweidn** [filecoin-project/filecoin-plus-large-datasets#636]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Hunan Tianzhou Game Technology Co., Ltd
- Website / Social Media:
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5 PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):400TiB
- On-chain address for first allocation:  f1jpekpp2cid2ntkcdn62uj7d27gkc7ajdjdsrp2a

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Hunan Tianzhou Game Technology Co., Ltd. was established on April 19, 2017. The legal representative is yuan Xionggui, the registered capital is 100 million yuan, the unified social credit code is 9143010ma4lkc8w8c, and the enterprise address is located at room 332, 3rd floor, headquarters building, Changsha Zhongdian Software Park, No. 39 Jianshan Road, Changsha high tech Development Zone. The industry is Internet and related services, and the business scope includes: research and development of online competitive ball games and various competitive chess and card games; Using information network to manage game products; Trade agency; Self support and agency of import and export of all kinds of goods and technologies, except for the goods and technologies that the state restricts the company to operate or prohibits the import and export; Software development; Research and development of information transmission technology and technology promotion; Game software design and production; Game outsourcing services; Internet information technology consulting; Advertising design; Advertising production services, publishing services, domestic and foreign agency services; Sales of computers, computer software and computer auxiliary equipment
```

What is the primary source of funding for this project?
```
Company revenues.
```

What other projects/ecosystem stakeholders is this project associated with?
```
There are no other items related to it
```

## Use-case details

Describe the data being stored onto Filecoin
```
Exhibition of the company's works
```

Where was the data in this dataset sourced from?
```
We plan to store archived data on this datacap for more than 180 days.
Data include:
1. Database backup of users, including daily complete mysql, redis, etc.
2 Bi user behavior analysis.
(3) server access_ log、error_ Log, etc.
4. Weekly resource data of users, including avatars, chat records, etc.

```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
[Please answer here.](https://www.thinkingdata.cn/aboutus.html)
https://drive.google.com/file/d/1cUAHH5G-_8qqHxYKbKpRdroDJVJkknbG/view?usp=sharing
https://drive.google.com/file/d/1tkmCOFe2WFqscZMpatDMKFqSwFyIsm2V/view?usp=sharing
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes, there are no restrictions. We will encrypt the files involving privacy,
```

What is the expected retrieval frequency for this data?
```
We plan to check the network four times a month.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
We hope it will last forever.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
we hope in China
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Since we used to use cloud disk drives, we started to use filecoin through the introduction of our friends. Our data storage capacity is very large, and it is estimated that it will increase by 30% - 40% every year, so we will use more offline transmission.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
Because we are not miners, we only know filecoin after being introduced by friends. When we learned about fil plus, we were very happy. We carefully read the storage rules of filecoin plus.
first ，We guarantee that the distribution of content will be as decentralized as possible. It will be stored in at least 8 storage service provider nodes.
The more decentralized the data storage is, the more secure it is for our data.
secondly,
We will ask the service provider that stores the data to provide the function of rapid retrieval, and will review the work after the storage is completed.
```

How will you be distributing deals across storage providers?
```
Choose Offline transmission as far as possible.
Our enterprise private cloud should support normal users. If it is used for online transmission, it will occupy too many resources.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, we have enough money. We will continue to learn how to standardize the use of filecoin
```

**Comment by raghavrmadya** [comment]
Please provide all requested info

**Comment by raghavrmadya** [comment]
No response.
