### ISSUE TITLE
[DataCap Application] Cansoti

### ISSUE THREAD

**Issue by Emmet2** [filecoin-project/filecoin-plus-large-datasets#640]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Cansoti
- Website / Social Media: https://www.cansoti.com/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):100TiB
- On-chain address for first allocation:f1einobkrjcjk6gfc5ov6663vrri75hwdsjfs6pmq

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Cansoti Design Studio founded in 2008. The studio has gathered a group of dynamic team with forward-looking ideas and international vision. We are dedicated to enlightening and renewing the concept of contemporary new living and providing more possibilities for design with its excellent professional ability and unremitting exploration, actively facing the future and the new consideration of the market.
```

What is the primary source of funding for this project?
```
Self-owned funds
```

What other projects/ecosystem stakeholders is this project associated with?
```
No
```

## Use-case details

Describe the data being stored onto Filecoin
```
Most design solutions, mainly pictures and videos of the design. We are going to store 5 copies.
```

Where was the data in this dataset sourced from?
```
The data is from the design made by our designers.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
[1-___.zip](https://github.com/filecoin-project/filecoin-plus-large-datasets/files/9308115/1-___.zip)
[3.zip](https://github.com/filecoin-project/filecoin-plus-large-datasets/files/9308066/3.zip)
[4.zip](https://github.com/filecoin-project/filecoin-plus-large-datasets/files/9308067/4.zip)
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes, we confirm it.
```

What is the expected retrieval frequency for this data?
```
3 times a year
```

For how long do you plan to keep this dataset stored on Filecoin?
```
1-2 years.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Asia
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Yes. Offline data transfer is a essential process for us.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
Sp with good reputation is our first request. Because we need stable cooperation.
```

How will you be distributing deals across storage providers?
```
Some SPs with enough experience will be distributed more than others. 
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Sure.
```

**Comment by Sunnyiscoming** [comment]
What's the relationship between you and organization?
Can you provide more detailed information about other storage providers participated in this program, such as you can list SPs you have contacted with at present?
Could you send an email to filplus-app-review@fil.org with your official domain in order to confirm your identity? Email name should includes the issue id #640.

**Comment by Sunnyiscoming** [comment]
Received that.

**Comment by raghavrmadya** [comment]
Can you prove that the images on the website represent your design work? A reverse search shows sources that are unrelated such as https://www.uulucky.com/show-6054089.html

**Comment by Emmet2** [comment]
@raghavrmadya Yes, we have panoramas about these design works. 
[1.zip](https://github.com/filecoin-project/filecoin-plus-large-datasets/files/9487253/1.zip)
I think that this website used our design work without informing us in advance.

**Comment by raghavrmadya** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 100TiB

**Client address**

>f1einobkrjcjk6gfc5ov6663vrri75hwdsjfs6pmq

**Comment by raghavrmadya** [comment]
Thanks @Emmet2 . I'll be honest your website has mostly renderings and as a community member I have my doubts but I will let the notaries decide.

**Comment by swatchliu** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacea7gxrwr2nydc3wqij7vtnn4eeysrpgysrgcb4o2cjqh6xhz45eey 
#### Address 
> f1einobkrjcjk6gfc5ov6663vrri75hwdsjfs6pmq
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1yh6q3nmsg7i2sys7f7dexcuajgoweudcqj2chfi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacea7gxrwr2nydc3wqij7vtnn4eeysrpgysrgcb4o2cjqh6xhz45eey

**Comment by UnionLabs2020** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedtecftiihhgbgmny35hhr7t57tnulmuj5pesidyijd46565kktys 
#### Address 
> f1einobkrjcjk6gfc5ov6663vrri75hwdsjfs6pmq
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f17xdri3wunqgld7dm23e4f3eqsntjakwc47xjo6i
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedtecftiihhgbgmny35hhr7t57tnulmuj5pesidyijd46565kktys

**Comment by BigD-Exchange** [comment]
@Emmet2 Hi! Great to see you have gotten approval for DataCap. If you are looking for more storage providers to store these data or have any questions, please visit #bigdata-exchange on Filecoin Slack or reply here. 

We have strong demand from a diverse group of SPs, who are actively looking to onboard more data.

**Comment by PluskitOfficial** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebbn6drvnegrswyp2xbaulara3g4jjz2piuiana6rvjwppnitflgw 
#### Address 
> f1einobkrjcjk6gfc5ov6663vrri75hwdsjfs6pmq
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1tgnlhtcmhwipfm7thsftxhn5k52velyjlazpvka
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebbn6drvnegrswyp2xbaulara3g4jjz2piuiana6rvjwppnitflgw

**Comment by MRJAVAZHAO** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebkh5yffs77qc6jtljnkwxy7cvy7asxyp2a5ri24h36rwkdkvrljc 
#### Address 
> f1einobkrjcjk6gfc5ov6663vrri75hwdsjfs6pmq
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f14gme3f52prtyzk6pblogrdd6b6ivp4swc6qmesi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebkh5yffs77qc6jtljnkwxy7cvy7asxyp2a5ri24h36rwkdkvrljc

**Comment by BlockMakeronline** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacealf26kt6kb4ja6s5pnzoy4jj23oksfxmrl45svb6doy7zijpicp2 
#### Address 
> f1einobkrjcjk6gfc5ov6663vrri75hwdsjfs6pmq
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1o3twrcpwjtpcd4q36lpq4qmy2qfbgtyy5h6tsty
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacealf26kt6kb4ja6s5pnzoy4jj23oksfxmrl45svb6doy7zijpicp2

**Comment by MatrixStorage** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceao747asgqocqzu2r6uyskq5sb5gtwsvou2vkxpxtrrshy6e2e3fi 
#### Address 
> f1einobkrjcjk6gfc5ov6663vrri75hwdsjfs6pmq
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1tbxqwjxfyv7swsdin4einirlsfquv3vnmlapley
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceao747asgqocqzu2r6uyskq5sb5gtwsvou2vkxpxtrrshy6e2e3fi

**Comment by MRJAVAZHAO** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacednffzoej53wycx4z6aeqmbfri2wdax3kef4e3ftdsy4bylpkkkdi 
#### Address 
> f1einobkrjcjk6gfc5ov6663vrri75hwdsjfs6pmq
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f14gme3f52prtyzk6pblogrdd6b6ivp4swc6qmesi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacednffzoej53wycx4z6aeqmbfri2wdax3kef4e3ftdsy4bylpkkkdi

**Comment by PluskitOfficial** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedihq32hn5ms5ibdgk77oz5jidxjn2d5ohxfv46ejohqcx5nlnj7w 
#### Address 
> f1einobkrjcjk6gfc5ov6663vrri75hwdsjfs6pmq
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1tgnlhtcmhwipfm7thsftxhn5k52velyjlazpvka
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedihq32hn5ms5ibdgk77oz5jidxjn2d5ohxfv46ejohqcx5nlnj7w

**Comment by MatrixStorage** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedmuu4wm4tjejwffxn4metqzyqvzavlihc2c273axx6sp6c6fc27s 
#### Address 
> f1einobkrjcjk6gfc5ov6663vrri75hwdsjfs6pmq
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1tbxqwjxfyv7swsdin4einirlsfquv3vnmlapley
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedmuu4wm4tjejwffxn4metqzyqvzavlihc2c273axx6sp6c6fc27s

**Comment by BlockMakeronline** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedszgquj7y6bxff42fnc7ifl2mk4bwrp7pde5apjvarwxwirlxnkw 
#### Address 
> f1einobkrjcjk6gfc5ov6663vrri75hwdsjfs6pmq
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1o3twrcpwjtpcd4q36lpq4qmy2qfbgtyy5h6tsty
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedszgquj7y6bxff42fnc7ifl2mk4bwrp7pde5apjvarwxwirlxnkw

**Comment by 1475Notary** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced2rvlyd5ouzzoc5dqebbwrc2ampa5qszy2kcpjcwaol2dznkrina 
#### Address 
> f1einobkrjcjk6gfc5ov6663vrri75hwdsjfs6pmq
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1ofq4mngy7ggcp755pfquq2gphjjnlydolf6awtq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced2rvlyd5ouzzoc5dqebbwrc2ampa5qszy2kcpjcwaol2dznkrina

**Comment by liyunzhi-666** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceciuczz4nfxq6lcte2psffiyhpcsc3fpczhevcym5j2lsvkd6hldq 
#### Address 
> f1einobkrjcjk6gfc5ov6663vrri75hwdsjfs6pmq
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1pszcrsciyixyuxxukkvtazcokexbn54amf7gvoq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceciuczz4nfxq6lcte2psffiyhpcsc3fpczhevcym5j2lsvkd6hldq

**Comment by UnionLabs2020** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecgpmxn4si23n6ofgz2e6qbpztpuo5ws4rhs2ahopg54ogoacw27i 
#### Address 
> f1einobkrjcjk6gfc5ov6663vrri75hwdsjfs6pmq
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f17xdri3wunqgld7dm23e4f3eqsntjakwc47xjo6i
#### Id
> 84f3d4d6-cf70-46b3-aadc-f2bc04dade56
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecgpmxn4si23n6ofgz2e6qbpztpuo5ws4rhs2ahopg54ogoacw27i

**Comment by MetaWaveInfo** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebdprayzkg3ph246nphudzndqzdnvs3gijpj32fpsnzmtzt4kn4hq 
#### Address 
> f1einobkrjcjk6gfc5ov6663vrri75hwdsjfs6pmq
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1ktlkcxnmzxcdaoqfsunrg3vocfbmgv4n3mrn74a
#### Id
> 84f3d4d6-cf70-46b3-aadc-f2bc04dade56
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebdprayzkg3ph246nphudzndqzdnvs3gijpj32fpsnzmtzt4kn4hq

**Comment by filplus-checker** [comment]
## DataCap and CID Checker Report[^1]
 - Organization: `Cansoti`
 - Client: `f1einobkrjcjk6gfc5ov6663vrri75hwdsjfs6pmq`
### Storage Provider Distribution
The below table shows the distribution of storage providers that have stored data for this client.

If this is the first time a provider takes verified deal, it will be marked as `new`.

For most of the datacap application, below restrictions should apply.
 - Storage provider should not exceed 25% of total datacap.
 - Storage provider should not be storing duplicate data for more than 20%.
 - Storage provider should have published its public IP address.
 - All storage providers should be located in different regions.

⚠️ 71.97% of total deal sealed by [f01844999](https://filfox.info/en/address/f01844999) are duplicate data.

⚠️ [f01844999](https://filfox.info/en/address/f01844999) has unknown IP location.

⚠️ 73.61% of total deal sealed by [f01924350](https://filfox.info/en/address/f01924350) are duplicate data.

⚠️ 76.82% of total deal sealed by [f01926914](https://filfox.info/en/address/f01926914) are duplicate data.

⚠️ 78.86% of total deal sealed by [f01926802](https://filfox.info/en/address/f01926802) are duplicate data.

⚠️ 79.29% of total deal sealed by [f01926585](https://filfox.info/en/address/f01926585) are duplicate data.

⚠️ 73.43% of total deal sealed by [f01924325](https://filfox.info/en/address/f01924325) are duplicate data.

⚠️ 84.94% of total deal sealed by [f01937964](https://filfox.info/en/address/f01937964) are duplicate data.

⚠️ 89.95% of total deal sealed by [f01889480](https://filfox.info/en/address/f01889480) are duplicate data.

⚠️ 53.21% of total deal sealed by [f01914977](https://filfox.info/en/address/f01914977) are duplicate data.

⚠️ 51.44% of total deal sealed by [f01889046](https://filfox.info/en/address/f01889046) are duplicate data.

⚠️ 75.76% of total deal sealed by [f01924416](https://filfox.info/en/address/f01924416) are duplicate data.

⚠️ 79.84% of total deal sealed by [f01917236](https://filfox.info/en/address/f01917236) are duplicate data.

⚠️ 74.61% of total deal sealed by [f01917241](https://filfox.info/en/address/f01917241) are duplicate data.

⚠️ 23.06% of total deal sealed by [f01900713](https://filfox.info/en/address/f01900713) are duplicate data.

⚠️ 23.88% of total deal sealed by [f01895715](https://filfox.info/en/address/f01895715) are duplicate data.

| Provider                                                    |                 Location | Total Deals Sealed | Percentage | Unique Data | Duplicate Deals |
| :---------------------------------------------------------- | -----------------------: | -----------------: | ---------: | ----------: | --------------: |
| [f01844999](https://filfox.info/en/address/f01844999)       |                  Unknown |         297.91 TiB |     13.16% |   83.50 TiB |          71.97% |
| [f01924350](https://filfox.info/en/address/f01924350)`new`  | Singapore, Singapore, SG |         280.78 TiB |     12.40% |   74.09 TiB |          73.61% |
| [f01926914](https://filfox.info/en/address/f01926914)       |    Ashburn, Virginia, US |         253.41 TiB |     11.19% |   58.75 TiB |          76.82% |
| [f01926802](https://filfox.info/en/address/f01926802)       |    Ashburn, Virginia, US |         245.94 TiB |     10.86% |   52.00 TiB |          78.86% |
| [f01926585](https://filfox.info/en/address/f01926585)       |    Ashburn, Virginia, US |         221.97 TiB |      9.80% |   45.97 TiB |          79.29% |
| [f01924325](https://filfox.info/en/address/f01924325)`new`  | Singapore, Singapore, SG |         205.59 TiB |      9.08% |   54.63 TiB |          73.43% |
| [f01937964](https://filfox.info/en/address/f01937964)       |         Tokyo, Tokyo, JP |         170.56 TiB |      7.53% |   25.69 TiB |          84.94% |
| [f01889480](https://filfox.info/en/address/f01889480)       |     Boardman, Oregon, US |         119.38 TiB |      5.27% |   12.00 TiB |          89.95% |
| [f01914977](https://filfox.info/en/address/f01914977)       |    Ashburn, Virginia, US |          73.00 TiB |      3.22% |   34.16 TiB |          53.21% |
| [f01889046](https://filfox.info/en/address/f01889046)       |    Ashburn, Virginia, US |          72.53 TiB |      3.20% |   35.22 TiB |          51.44% |
| [f01924416](https://filfox.info/en/address/f01924416)`new`  | Singapore, Singapore, SG |          66.78 TiB |      2.95% |   16.19 TiB |          75.76% |
| [f01917236](https://filfox.info/en/address/f01917236)       |         Seoul, Seoul, KR |          64.34 TiB |      2.84% |   12.97 TiB |          79.84% |
| [f01917241](https://filfox.info/en/address/f01917241)       |         Seoul, Seoul, KR |          42.09 TiB |      1.86% |   10.69 TiB |          74.61% |
| [f01917208](https://filfox.info/en/address/f01917208)       |         Seoul, Seoul, KR |          38.00 TiB |      1.68% |   38.00 TiB |           0.00% |
| [f01916487](https://filfox.info/en/address/f01916487)       |         Seoul, Seoul, KR |          37.97 TiB |      1.68% |   31.47 TiB |          17.12% |
| [f01900713](https://filfox.info/en/address/f01900713)       |         Seoul, Seoul, KR |          37.00 TiB |      1.63% |   28.47 TiB |          23.06% |
| [f01895715](https://filfox.info/en/address/f01895715)       |         Seoul, Seoul, KR |          36.91 TiB |      1.63% |   28.09 TiB |          23.88% |

![Provider Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/640/1671097604075.png)
### Deal Data Replication
The below table shows how each many unique data are replicated across storage providers.
- No more than 25% of unique data are stored with less than 4 providers.

⚠️ 100.00% of deals are for data replicated across less than 4 storage providers.

| Unique Data Size | Total Deals Made | Number of Providers | Deal Percentage |
| ---------------: | ---------------: | ------------------: | --------------: |
|       305.28 TiB |         1.10 PiB |                   1 |          49.68% |
|       133.19 TiB |       937.72 TiB |                   2 |          41.42% |
|        23.41 TiB |       201.63 TiB |                   3 |           8.91% |

![Replication Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/640/1671097604783.png)
### Deal Data Shared with other Clients
The below table shows how many unique data are shared with other clients.
Usually different applications owns different data and should not resolve to the same CID.

⚠️ CID sharing has been observed.

| Other Client                                                                                                          | Application                                                                                                                | Total Deals Affected | Unique CIDs |                                                                                 Verifier |
| :-------------------------------------------------------------------------------------------------------------------- | :------------------------------------------------------------------------------------------------------------------------- | -------------------: | ----------: | ---------------------------------------------------------------------------------------: |
| [f1rnwp6p5kx7pcwexpucoav6mmwz3rkxw5blrboyy](https://filfox.info/en/address/f1rnwp6p5kx7pcwexpucoav6mmwz3rkxw5blrboyy) | [MigoVideo](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/517)                                   |           289.41 TiB |       3,096 |                                                                          LDN v3 multisig |
| [f1ajdk7e6ex7fvtjtydzgys47bcg7jub2baucun7y](https://filfox.info/en/address/f1ajdk7e6ex7fvtjtydzgys47bcg7jub2baucun7y) | [Ruikuyun Information Technology Co\., Ltd](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/529)   |           190.19 TiB |       2,423 |                                                                          LDN v3 multisig |
| [f1vtcetpapwwyka6txwqjwymsa67npdfilbkwh64a](https://filfox.info/en/address/f1vtcetpapwwyka6txwqjwymsa67npdfilbkwh64a) | [Chimay](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/397)                                      |           164.66 TiB |       1,877 |                                                                          LDN v3 multisig |
| [f1ivsvpljx4ovp2tth73pllkxmumrudemks623iia](https://filfox.info/en/address/f1ivsvpljx4ovp2tth73pllkxmumrudemks623iia) | `TIS Inc. group`                                                                                                           |           153.38 TiB |       1,331 |                                                                          LDN v3 multisig |
| [f1ffbtksiso5za73pypuxbxznng6rdv64nbihdtba](https://filfox.info/en/address/f1ffbtksiso5za73pypuxbxznng6rdv64nbihdtba) | [EpikProtocol](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/281)                                |           136.81 TiB |       1,198 |                                                                                LDN # 281 |
| [f1bb2z36lpq3pnwiiowiraagpzqnpow4bonjacx7a](https://filfox.info/en/address/f1bb2z36lpq3pnwiiowiraagpzqnpow4bonjacx7a) | [Hola Space](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/362)                                  |           112.31 TiB |       1,106 |                                                                          LDN v3 multisig |
| [f1dwhevm3p2slu6itmkssznscmpkpltdiztprnpya](https://filfox.info/en/address/f1dwhevm3p2slu6itmkssznscmpkpltdiztprnpya) | [Hiscene](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/548)                                     |            91.72 TiB |         594 |                                                                          LDN v3 multisig |
| [f1xtnkj5ti77f5gbzhclnpj3xt6e5dwhfzive2yca](https://filfox.info/en/address/f1xtnkj5ti77f5gbzhclnpj3xt6e5dwhfzive2yca) | [Beacon Project](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/482)                              |            84.63 TiB |         243 | Project Beacon, 12 LDNs LDN # 444, 446, 447, 448, 474, 475, 476, 477, 479, 480, 481, 482 |
| [f1zb6pgkktdbyy7zxfob6gripqxuc25ukf35cc7fq](https://filfox.info/en/address/f1zb6pgkktdbyy7zxfob6gripqxuc25ukf35cc7fq) | `Maxpic PhotoGraphic Studio`                                                                                               |            72.34 TiB |       1,221 |                                                                          LDN v3 multisig |
| [f14abwn2goturifmt27s2bssoe3fup2b3npkgfzui](https://filfox.info/en/address/f14abwn2goturifmt27s2bssoe3fup2b3npkgfzui) | [KONGFU VR](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/372)                                   |            61.22 TiB |       1,081 |                                                                          LDN v3 multisig |
| [f1f5edx6ofn3lf6rk3yfpldbi2pzgq2egoyu6ubpi](https://filfox.info/en/address/f1f5edx6ofn3lf6rk3yfpldbi2pzgq2egoyu6ubpi) | [Samdata Trade](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/382)                               |            51.63 TiB |         988 |                                                                          LDN v3 multisig |
| [f1quofpadzcqlonmz7v3mv7dfqvm5hdztucdsjqsy](https://filfox.info/en/address/f1quofpadzcqlonmz7v3mv7dfqvm5hdztucdsjqsy) | [HENAN 863 SOFTWARE CO\., LTD](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/468)                |            47.19 TiB |         676 |                                                                          LDN v3 multisig |
| [f1ki4cjk27ypzjsuzkvvqzs6xobaweuoxfdcnpqhy](https://filfox.info/en/address/f1ki4cjk27ypzjsuzkvvqzs6xobaweuoxfdcnpqhy) | [TimeQuant](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/385)                                   |            37.91 TiB |         565 |                                                                          LDN v3 multisig |
| [f1clwd2dooy2cflfilhzeq2ycl544b3heqsiwhjrq](https://filfox.info/en/address/f1clwd2dooy2cflfilhzeq2ycl544b3heqsiwhjrq) | [FiboAI](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/349)                                      |            27.75 TiB |         549 |                                                                          LDN v3 multisig |
| [f1smfrznoqsp7eptqnselnosng7vxuo3ptnoqv2oa](https://filfox.info/en/address/f1smfrznoqsp7eptqnselnosng7vxuo3ptnoqv2oa) | [CTG Business Service](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/306)                        |            26.19 TiB |         235 |                                                                          LDN v3 multisig |
| [f1mn5mw2dpqz6p3s7vxrlkhkh3okdtc6t7wqro4xa](https://filfox.info/en/address/f1mn5mw2dpqz6p3s7vxrlkhkh3okdtc6t7wqro4xa) | [Unisound](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/577)                                    |            17.00 TiB |         160 |                                                                          LDN v3 multisig |
| [f1zav4f4rak2yvbrq357z3whj224wn4dipl7eiesy](https://filfox.info/en/address/f1zav4f4rak2yvbrq357z3whj224wn4dipl7eiesy) | [Shanghai Zhixun](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/628)                             |            17.00 TiB |         163 |                                                                          LDN v3 multisig |
| [f17qd6x3leh5pa7vh6ewdaed7qhbn2mgofrokuayy](https://filfox.info/en/address/f17qd6x3leh5pa7vh6ewdaed7qhbn2mgofrokuayy) | [Drust](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/427)                                       |            15.00 TiB |         200 |                                                                          LDN v3 multisig |
| [f1avhqgmeazxzvylz34l26o3nlj2ywnzaviwns3dq](https://filfox.info/en/address/f1avhqgmeazxzvylz34l26o3nlj2ywnzaviwns3dq) | [87v5\-CarsonVideo](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/392)                           |            11.84 TiB |         212 |                                                                          LDN v3 multisig |
| [f1jdmx2cuswzjlt4pnsv3t7ipmesywzxsg6q56a2a](https://filfox.info/en/address/f1jdmx2cuswzjlt4pnsv3t7ipmesywzxsg6q56a2a) | [Raysun Radar Electronic Technology Co\.,Ltd](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/884) |            10.44 TiB |         101 |                                                                          LDN v3 multisig |
| [f1727w2vwjctfo7hflr5trgqkl3c7texh7pl4grzq](https://filfox.info/en/address/f1727w2vwjctfo7hflr5trgqkl3c7texh7pl4grzq) | [GMverse](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/365)                                     |             2.72 TiB |          32 |                                                                          LDN v3 multisig |
| [f1tivtdkq34mnfzso63wrr2xh6r2zo7aebao4jfla](https://filfox.info/en/address/f1tivtdkq34mnfzso63wrr2xh6r2zo7aebao4jfla) | `China travel service(HongKong) limited`                                                                                   |             2.66 TiB |           8 |                                                                          LDN v3 multisig |
| [f1xyx3tvfoy7ue62oqdtcpud5ewcw2i7ctu4kyylq](https://filfox.info/en/address/f1xyx3tvfoy7ue62oqdtcpud5ewcw2i7ctu4kyylq) | [zhenshuai](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/332)                                   |             1.25 TiB |           7 |                                                                                LDN # 332 |
| [f1dx7ljly4vmk5x2bn5ng4jpbqnuvozrz2phw42qy](https://filfox.info/en/address/f1dx7ljly4vmk5x2bn5ng4jpbqnuvozrz2phw42qy) | [CoinPhD](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/364)                                     |           512.00 GiB |           2 |                                                                          LDN v3 multisig |
| [f1qjrlejxv5a73kxurwtxyrni6ji7orm74zeeetiy](https://filfox.info/en/address/f1qjrlejxv5a73kxurwtxyrni6ji7orm74zeeetiy) | [Mooc](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/223)                                        |            32.00 GiB |           1 |                                                                          LDN v3 multisig |

[^1]: To manually trigger this report, add a comment with text `checker:manualTrigger`

**Comment by cryptowhizzard** [comment]
The website is not reachable.
