### ISSUE TITLE
[DataCap Application] <Bytedance -Tik Tok> - <Experts Journey>

### ISSUE THREAD

**Issue by jessica20220403** [filecoin-project/filecoin-plus-large-datasets#648]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name:ByteDance - Tik Tok
- Website / Social Media:https://www.bytedance.com/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):100TiB
- On-chain address for first allocation:f1tvmwuooo7q5yznxs7wkgm4diafpvlud62zukgri

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
As one of the most famous information and technology company in China, Bytedance has various platforms for content sharing, advertising, direct seeding  like global video sharing APP Tik Tok globally. The vision of Bytedance is to build up a global platform for creation and sharing. Therefore we triggered many projects to encourage both originators and customers to flourish the internet culture. Here we are setting up a project called"Experts Journey", which plan to call together all the experts in different industries to share their knowledges/ideas/experiences and then booster the products or services business in those industries with better quality. 
```

What is the primary source of funding for this project?
```
company business income
```

What other projects/ecosystem stakeholders is this project associated with?
```
This projects is associated with many e-commerce brands and supply chain companies.
```

## Use-case details

Describe the data being stored onto Filecoin
```
Public advertisements including video, picture, animation.
```

Where was the data in this dataset sourced from?
```
accumulative data from the project.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://www.douyin.com/(China version of Tik Tok)
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
yes
```

What is the expected retrieval frequency for this data?
```
frequently
```

For how long do you plan to keep this dataset stored on Filecoin?
```
3 years at least
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Asia/America
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
supporting online and offline data distributing depending on the need of storage providers.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We plan to select the SPs with high reputation who already participate in the project.
```

How will you be distributing deals across storage providers?
```
We will identify at least 10-15 SPs as our long term partners, and Ideally we will distribute deals according to their business needs
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
yes
```

**Comment by swatchliu** [comment]
https://sf16-sg.tiktokcdn.com/obj/eden-sg/upsnuhpevbn/bytedance_official/PrivacyPolicy_ByteDance.com.pdf

**Comment by Sunnyiscoming** [comment]
Any update here? @jessica20220403

**Comment by raghavrmadya** [comment]
No reply
