### ISSUE TITLE
[DataCap Application] Shannxi Xuetianxia Education Technology Co., LTD - Xuetianxia

### ISSUE THREAD

**Issue by maxvint** [filecoin-project/filecoin-plus-large-datasets#650]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Xuetianxia
- Website / Social Media: https://www.xuetianxia.cn
  - Social Media:
    - TikTok: https://www.douyin.com/user/MS4wLjABAAAAa2b2GzgOY3dM4Yxoi906c4oHjh3HhmNtzIHIVivmw5o
    - Bilibili: https://space.bilibili.com/394442284
    - Kuaishou: https://www.kuaishou.com/profile/3xgmax4apnnkjpg
    - Wechat: https://mp.weixin.qq.com/mp/profile_ext?action=home&__biz=MzIwOTQ2ODQwMA==&scene=124#wechat_redirect (Please open this link in Wechat APP)
    - Weibo: https://weibo.com/u/5812326091 (Login required)
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100TiB
- On-chain address for first allocation: f1ud77rddmchv4uvwpuoau3rag5rzcdtkqy45uycy

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Shannxi Xuetianxia Education Technology Co., Ltd. was born in Shannxi, China in 2015, we committed to creating a one-stop lifelong learning education service platform. Realize various online teaching methods such as online live broadcast, 1-on-1, recording and broadcasting through internet technology.

At present, Xuetianxia have more than 500,000 online students, and developed courses over 20PiB. And have supported all devices, such as Web APP, iOS, Android and H5 APP.
```

What is the primary source of funding for this project?
```
Own funds and revenue of the company.
```

What other projects/ecosystem stakeholders is this project associated with?
```
None
```

## Use-case details

Describe the data being stored onto Filecoin
```
The data stored on Filecoin is videos and pictures of our online courses. We have produced over 20PiB of online courses since 2016, these courses cover: primary education, middle school education, higher school education, social education, vocational and technical education.
```

Where was the data in this dataset sourced from?
```
Mainly from our online learning platform, and a few data from our strategic parters.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://drive.google.com/drive/folders/1_7DuK7FMrF3huF2rLov_5ukjZJhczuFc?usp=sharing
```

Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes
```

What is the expected retrieval frequency for this data?
```
3 - 5 times every 540 days.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
Store for at least 540 days.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
North America and Asia.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
We will send CAR files to storage providers offline for deal making.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We will check their overall capacity and working hours, we need a storage provider that we can work with for a long time.
```

How will you be distributing deals across storage providers?
```
We will allocate DataCap according to miner's preference, such as online transfer and offline transfer.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes，we have enough funding and resources to start making deals.
```

**Comment by yuwenhui** [comment]
> **Thanks for your request!** ❗ We have found some problems in the information provided. We could not find any **Web site or social media info** in the information provided We could not find any **Region** in the information provided
> 
> ```
> Please, take a look at the request and edit the body of the issue providing all the required information.
> ```

Hi, Mr bot, I have updated the website link and can be successfully accessed.

**Comment by Sunnyiscoming** [comment]
- How many copies you will store?
- Can you provide more detailed information about storage providers distribution, such as you can list SPs you have contacted with at present?
- Could you send an email to filplus-app-review@fil.org with your official domain in order to confirm your identity? Email name should includes the issue id #650.

**Comment by yuwenhui** [comment]
> * How many copies you will store?
> * Can you provide more detailed information about storage providers distribution, such as you can list SPs you have contacted with at present?
> * Could you send an email to [filplus-app-review@fil.org](mailto:filplus-app-review@fil.org) with your official domain in order to confirm your identity? Email name should includes the issue id [[DataCap Application] Shannxi Xuetianxia Education Technology Co., LTD - Xuetianxia #650](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/650).
- We will store 3 - 5 copies currently.
- For storage providers distribution, we have contacted the following SPs:
  - [f0465286](https://filfox.info/zh/address/f0465286)
  - [f0158335](https://filfox.info/zh/address/f0158335)
  - [f0818235](https://filfox.info/zh/address/f0818235)
  - [f01824405](https://filfox.info/zh/address/f01824405)
  - [f087096](https://filfox.info/zh/address/f087096)
  - [f0436661](https://filfox.info/zh/address/f0436661)
  - [f0152866](https://filfox.info/zh/address/f0152866)
- The confirm email has sent to [filplus-app-review@fil.org](mailto:filplus-app-review@fil.org) from coding@xuetianxia.cn.

**Comment by Sunnyiscoming** [comment]
Do not receive any email from coding@xuetianxia.cn. Please check it again.

**Comment by yuwenhui** [comment]
> Do not receive any email from [coding@xuetianxia.cn](mailto:coding@xuetianxia.cn). Please check it again.

I have checked the sending status of the email, and it seems to be sent successfully. Could you please wait for a few hours and check it again?

![E81F086D-5916-46F6-A499-1720D3005E6A](https://user-images.githubusercontent.com/1715211/187717672-05922dff-8309-47bb-9aa5-3bf2ee764424.png)

**Comment by yuwenhui** [comment]
> Do not receive any email from [coding@xuetianxia.cn](mailto:coding@xuetianxia.cn). Please check it again.

@Sunnyiscoming Hi, Sunny, Could please check the confirm email that sent from [coding@xuetianxia.cn](mailto:coding@xuetianxia.cn), if you have not received it, i will send you again.

**Comment by yuwenhui** [comment]
@Sunnyiscoming I have sent the confirm email to [filplus-app-review@fil.org](mailto:filplus-app-review@fil.org) again. Could you please check it?

**Comment by Sunnyiscoming** [comment]
Received that.

**Comment by yuwenhui** [comment]
> Received that.

@Sunnyiscoming @galen-mcandrew So, please let me know what's next i should to? Is there anything else i have to provide?

**Comment by raghavrmadya** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 100TiB

**Client address**

>f1ud77rddmchv4uvwpuoau3rag5rzcdtkqy45uycy

**Comment by xiaoyuaiheshui** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceax3yg6ijxaupdatkybglth7mxnaxfcgty4ytzkg22s7lsui3cabq 
#### Address 
> f1ud77rddmchv4uvwpuoau3rag5rzcdtkqy45uycy
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f122qmy25wdtt5mxd77kndiq7z5x2n3iwiuz2wdsa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceax3yg6ijxaupdatkybglth7mxnaxfcgty4ytzkg22s7lsui3cabq

**Comment by MetaWaveInfo** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedryoopwhkxtx6ugrf4bfrqys57j2e4a6ntb5gbcnaengrp4aj6hy 
#### Address 
> f1ud77rddmchv4uvwpuoau3rag5rzcdtkqy45uycy
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1ktlkcxnmzxcdaoqfsunrg3vocfbmgv4n3mrn74a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedryoopwhkxtx6ugrf4bfrqys57j2e4a6ntb5gbcnaengrp4aj6hy

**Comment by BigD-Exchange** [comment]
@yuwenhui Hi! Great to see you have gotten approval for DataCap. If you are looking for more storage providers to store these data or have any questions, please visit #bigdata-exchange on Filecoin Slack or reply here. 

We have strong demand from a diverse group of SPs, who are actively looking to onboard more data.

**Comment by xiaoyuaiheshui** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedlwmkkzryha7rs6sx6sozzefsu7ibaxqz2nxd4qoh445itlpj2oo 
#### Address 
> f1ud77rddmchv4uvwpuoau3rag5rzcdtkqy45uycy
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f122qmy25wdtt5mxd77kndiq7z5x2n3iwiuz2wdsa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedlwmkkzryha7rs6sx6sozzefsu7ibaxqz2nxd4qoh445itlpj2oo

**Comment by xiaoyuaiheshui** [comment]
I accidentally read the wrong number and signed the LDN incorrectly, violating the rules. I apologize.

**Comment by kernelogic** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecvgfroro6pckcl76ttp2bhyx2jfx45vuwurwpdf4rwtkhvqxq3a4 
#### Address 
> f1ud77rddmchv4uvwpuoau3rag5rzcdtkqy45uycy
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecvgfroro6pckcl76ttp2bhyx2jfx45vuwurwpdf4rwtkhvqxq3a4

**Comment by psh0691** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceapkep6kqwqbw5a3ccakfjcy3u747u23lu3bv73dg4riabrt6vcow 
#### Address 
> f1ud77rddmchv4uvwpuoau3rag5rzcdtkqy45uycy
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1qdko4jg25vo35qmyvcrw4ak4fmuu3f5rif2kc7i
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceapkep6kqwqbw5a3ccakfjcy3u747u23lu3bv73dg4riabrt6vcow

**Comment by Joss-Hua** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaw5qmzugk75hpdmf54v3ronmdpa26wnsb2e4kuxidtu3ixtp2tfs 
#### Address 
> f1ud77rddmchv4uvwpuoau3rag5rzcdtkqy45uycy
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1tfg54zzscugttejv336vivknmsnzzmyudp3t7wi
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaw5qmzugk75hpdmf54v3ronmdpa26wnsb2e4kuxidtu3ixtp2tfs

**Comment by Joss-Hua** [comment]
Why did immediately enter the next round of distribution,there seems to be something unusual.

**Comment by kernelogic** [comment]
faucet is empty

**Comment by EthSwarm-CHINA** [comment]
If there is water in the pool, do you need to re-sign? If you sign, is it 200TiB or 400TiB?

**Comment by lyjmry** [comment]
If there is water in the pool, do you need to re-sign? If sign, is it 200TiB or 400TiB?

**Comment by psh0691** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebbvulzomtspvvdknh36exg2n6nlvkvwhd7pybgeolm7tyox2vnoa 
#### Address 
> f1ud77rddmchv4uvwpuoau3rag5rzcdtkqy45uycy
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1qdko4jg25vo35qmyvcrw4ak4fmuu3f5rif2kc7i
#### Id
> 0788a395-453c-42d3-96ea-428c6d652060
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebbvulzomtspvvdknh36exg2n6nlvkvwhd7pybgeolm7tyox2vnoa

**Comment by kernelogic** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecezsmdc7bp7bvkyqgzzvr6k3wabf4qck56skcp5jgckiucjz75yi 
#### Address 
> f1ud77rddmchv4uvwpuoau3rag5rzcdtkqy45uycy
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### Id
> 0788a395-453c-42d3-96ea-428c6d652060
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecezsmdc7bp7bvkyqgzzvr6k3wabf4qck56skcp5jgckiucjz75yi

**Comment by filplus-checker** [comment]
## DataCap and CID Checker Report[^1]
 - Organization: `Xuetianxia`
 - Client: `f1ud77rddmchv4uvwpuoau3rag5rzcdtkqy45uycy`
### Storage Provider Distribution
The below table shows the distribution of storage providers that have stored data for this client.

If this is the first time a provider takes verified deal, it will be marked as `new`.

For most of the datacap application, below restrictions should apply.
 - Storage provider should not exceed 25% of total datacap.
 - Storage provider should not be storing duplicate data for more than 20%.
 - Storage provider should have published its public IP address.
 - All storage providers should be located in different regions.

⚠️ [f01824405](https://filfox.info/en/address/f01824405) has sealed 34.54% of total datacap.

| Provider                                                    |             Location | Total Deals Sealed | Percentage | Unique Data | Duplicate Deals |
| :---------------------------------------------------------- | -------------------: | -----------------: | ---------: | ----------: | --------------: |
| [f01824405](https://filfox.info/en/address/f01824405)`new`  |  Deyang, Sichuan, CN |          47.56 TiB |     34.54% |   47.47 TiB |           0.20% |
| [f01939387](https://filfox.info/en/address/f01939387)       | Chengdu, Sichuan, CN |          32.59 TiB |     23.67% |   32.53 TiB |           0.19% |
| [f01941622](https://filfox.info/en/address/f01941622)       | Chengdu, Sichuan, CN |          31.66 TiB |     22.99% |   31.59 TiB |           0.20% |
| [f01939377](https://filfox.info/en/address/f01939377)       | Chengdu, Sichuan, CN |          25.88 TiB |     18.79% |   25.88 TiB |           0.00% |

![Provider Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/650/1671097613597.png)
### Deal Data Replication
The below table shows how each many unique data are replicated across storage providers.
- No more than 25% of unique data are stored with less than 4 providers.

⚠️ 100.00% of deals are for data replicated across less than 4 storage providers.

| Unique Data Size | Total Deals Made | Number of Providers | Deal Percentage |
| ---------------: | ---------------: | ------------------: | --------------: |
|        60.22 TiB |        60.31 TiB |                   1 |          43.80% |
|        18.56 TiB |        37.25 TiB |                   2 |          27.05% |
|        13.38 TiB |        40.13 TiB |                   3 |          29.14% |

![Replication Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/650/1671097614414.png)
### Deal Data Shared with other Clients
The below table shows how many unique data are shared with other clients.
Usually different applications owns different data and should not resolve to the same CID.

⚠️ CID sharing has been observed.

| Other Client                                                                                                          | Application                                                                              | Total Deals Affected | Unique CIDs |        Verifier |
| :-------------------------------------------------------------------------------------------------------------------- | :--------------------------------------------------------------------------------------- | -------------------: | ----------: | --------------: |
| [f1gwuigefejd5jkbtg4uznx45toaie5olh2cgm3dq](https://filfox.info/en/address/f1gwuigefejd5jkbtg4uznx45toaie5olh2cgm3dq) | [FeigeData](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/653) |            11.28 TiB |         318 | LDN v3 multisig |

[^1]: To manually trigger this report, add a comment with text `checker:manualTrigger`

**Comment by yuwenhui** [comment]
checker:manualTrigger

**Comment by cryptowhizzard** [comment]
Hello 

CID sharing has been observed between this LDN and #653 

Can you tell us why? The dataset's should be unique.

**Comment by yuwenhui** [comment]
> Hello
> 
> CID sharing has been observed between this LDN and #653
> 
> Can you tell us why? The dataset's should be unique.
Hello @cryptowhizzard ,
This is because Xuetianxia is a customer of Feige Technology. Xuetianxia commissioned Feige Technology to annotate a series of video data to improve their online artificial intelligence learning algorithms. And as partners, they share the copyright of these data.

**Comment by cryptowhizzard** [comment]
Hello,

It seems that one or 2 SP's to store your data with because the machines all share the same IP.

lotus net connect f01941622                                                                                                                                                                                                                                                                                                       
f01941622 -> {12D3KooWSXrsMKNfCsTsGydFj1Ha8KmRqg1q2M3bmFmeDFAoyWuE: [/ip4/183.220.36.2/tcp/36617]}
ERROR: failed to parse multiaddr "f01941622": must begin with /

 lotus net connect f01939387                                                                                                                                                                                                                                                                                                       
f01939387 -> {12D3KooWCsXpYdxt3HB8xUgBb6Pa9Xot9xnd8v7URzcJRVLDy3Rc: [/ip4/183.220.36.2/tcp/36616]}
ERROR: failed to parse multiaddr "f01939387": must begin with /

lotus net connect f01939377                                                                                                                                                                                                                                                                                                       
f01939377 -> {12D3KooWP6ruBqoH971N6goZRdaHnSyRyeTxejH7nzjKktVJqjgf: [/ip4/183.220.36.2/tcp/36615]}
ERROR: failed to parse multiaddr "f01939377": must begin with /

lotus net connect f02006691                                                                                                                                                                                                                                                                                                       
f02006691 -> {12D3KooWPN4arAnJp49HNGWput31hwG1v7GywW2Qc4nBcF45ABYW: [/ip4/162.219.38.93/tcp/34233]}
ERROR: failed to parse multiaddr "f02006691": must begin with /

lotus net connect f01991416                                                                                                                                                                                                                                                                                                       
f01991416 -> {12D3KooWKhhdwS4e2KKcU1w8mmrR8QcAVvYPTNfHyLG62n3M75pc: [/ip4/162.219.38.93/tcp/34232]}
ERROR: failed to parse multiaddr "f01991416": must begin with /

lotus net connect f02012032                                                                                                                                                                                                                                                                                                       
f02012032 -> {12D3KooWLBMSggvqs69icS3srwKpZTtaZAS484aQ2XsDchcAUwV2: [/ip4/162.219.38.93/tcp/34234]}
ERROR: failed to parse multiaddr "f02012032": must begin with /

**Comment by cryptowhizzard** [comment]
Hello @yuwenhui 

I am sorry for the technical language in my post above for my fellow notary's.

For the Filecoin + program itself please note that by storing data on the Filecoin network you get 10x the power ( QAP ) of a normal sector. In return for this to be eligible for this incentive there are important rules to abide:

The data must be stored with multiple service providers. ( Not with one organization running multiple SP's but really independent organizations )
The data must be distributed over multiple regions. (Running a VPN is not allowed to fake presence in the USA for example)
The data must be retrievable by everyone in the community to check if you are really storing what you say you are storing. Running boost is highly recommended.
The data must be in line with the mission of FIL+. That means that the data must be valuable for humanity. It can be scientific or other things that people are highly interested in and is unique.
As data preparer you are allowed to store one copy yourself (if the client requests so for the sake of redundancy of the data). If you store your copy in China it means that the other organizations/SP must be outside China.

Above shows that the rules have not been followed in this LDN. Let me know if you have questions about that.
If not then i would like to create a data onboarding plan together with you to recover and get this LDN on the right track.

It consists of:
The entity that is going to do the data preparation for you, where and when. If you need recommendations i can give them to you.
The new SP's you are going to store data with and their reputation. If you need recommendations i can give them to you.
When we do checks on the data stored and how and by who.
The retrieval frequency (how often does the data needs to be retrieved and from where)

**Comment by cryptowhizzard** [comment]
Notary's ... please check on #653 and the comments of CID sharing i made [here](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/653#issuecomment-1398635272).

**Comment by yuwenhui** [comment]
checker:manualTrigger

**Comment by data-programs** [comment]
<img width="32" alt="KYC" Verified src="https://stable.filplus.storage/images/filplus-kyc-verified-badge.png"/>

This user’s identity has been verified through [filplus.storage](https://filplus.storage)
