### ISSUE TITLE
[DataCap Application] <Suzhou Feige Data Technology Co., Ltd> - <Fileguard>

### ISSUE THREAD

**Issue by maxvint** [filecoin-project/filecoin-plus-large-datasets#653]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: FeigeData
- Website / Social Media: https://fileguard.io
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100TiB
- On-chain address for first allocation: f1gwuigefejd5jkbtg4uznx45toaie5olh2cgm3dq

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Suzhou Feige Data Technology Co., Ltd. was born in Suzhou, China in 2020. Feige has developed a crowdsourcing platform [Fileguard](https://fileguard.io) to provide artificial intelligence enterprises with massive and high-quality training data.

For some artificial enterprises that cannot even obtain enough basic training data, Feige provide a complete training data solution of "software + hardware", Help algorithm companies collect and check data, A complete set of solutions for cleaning, desensitization, labeling, etc.

Feige also provide open data labeling platform SAAS services for small algorithm companies.

At present, we have served more than 30 artificial intelligence enterprise customers, suce as Face++, SenseTime, JD finance and so on, providing customers with more than 20 million image annotation data, and about 200,000 crowdsourcers working on the Fileguard platform.
```

What is the primary source of funding for this project?
```
Own funds and operating income.
```

What other projects/ecosystem stakeholders is this project associated with?
```
No
```

## Use-case details

Describe the data being stored onto Filecoin
```
The data stored on Filecoin is raw pictures and annotation results(JSON format).
```

Where was the data in this dataset sourced from?
```
Mainly from our online annotation platform, and a few data from our strategic parters.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://drive.google.com/drive/folders/1pE5q5PxdNh2eXc_Cpc3ZZjGCDYuodYYC?usp=sharing
```

Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes
```

What is the expected retrieval frequency for this data?
```
About 3 times every 540 days.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
Store for at least 540 days.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
North America and Asia.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
We will distribute offline to storage providers.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We will check their overall capacity and working hours, we need a storage provider that we can work with for a long time.
```

How will you be distributing deals across storage providers?
```
We will allocate DataCap according to miner's preference, such as online transfer and offline transfer.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes，we have enough funding and resources to start making deals.
```

**Comment by Sunnyiscoming** [comment]
https://fileguard.io/ Estimated domain age: 16 day(s)
![image](https://user-images.githubusercontent.com/105098820/187572953-1903f156-1fe5-438a-ba66-0493f82bd194.png)
https://whois.whoisxmlapi.com/lookup-report/1E2NQpwwR6
- The website appears to be new and unrecorded. The enterprise was also registered in December 2021. Can you explain the source of 5P data?
- How many copies you will store?
- Can you provide more detailed information about storage providers distribution, such as you can list SPs you have contacted with at present?

**Comment by yuwenhui** [comment]
> https://fileguard.io/ Estimated domain age: 16 day(s) ![image](https://user-images.githubusercontent.com/105098820/187572953-1903f156-1fe5-438a-ba66-0493f82bd194.png) https://whois.whoisxmlapi.com/lookup-report/1E2NQpwwR6
> 
> * The website appears to be new and unrecorded. The enterprise was also registered in December 2021. Can you explain the source of 5P data?
> * How many copies you will store?
> * Can you provide more detailed information about storage providers distribution, such as you can list SPs you have contacted with at present?

- Yes, the website was new registered, that's because we have changed the domain name from markartisan.com to fileguard.io for business purposes. We were registered markartisan.com at 2016.
  <img width="689" alt="image" src="https://user-images.githubusercontent.com/1715211/187594223-2cb07abe-68a5-4402-9cb6-1fb5ef202225.png">
  And about our enterprise, the business of Fileguard started in Beijing and belonged to [Matu Beijing Technology Co., Ltd.](https://www.tianyancha.com/company/3074607029) (Please review more information at Tianyacha) since 2017. We moved to Suzhou, JiangSu province at 2021 for some business reasons and registered a new company, which name is Suzhou Feige Data Technology Co., Ltd. However, our AI annotation data platform and business were started at 2017. 
  <img width="1262" alt="image" src="https://user-images.githubusercontent.com/1715211/187595688-c00c4059-ed0d-4ef5-b5f2-c4968b61864e.png">
- We will store  5 - 8 copies currently.
- We will make sure the distribution fairly and equitably, and try to allow more storage providers to participate in the data storage process. We have contacted the following SPs:
  - [f0465286](https://filfox.info/zh/address/f0465286)
  - [f0158335](https://filfox.info/zh/address/f0158335)
  - [f0818235](https://filfox.info/zh/address/f0818235)
  - [f01824405](https://filfox.info/zh/address/f01824405)
  - [f087096](https://filfox.info/zh/address/f087096)
  - [f0436661](https://filfox.info/zh/address/f0436661)
  - [f0152866](https://filfox.info/zh/address/f0152866)

**Comment by Sunnyiscoming** [comment]
markartisan.com do not work now, so it is hard to check your business started from 2017.
Can you elaborate on the data composition and source of 5P?
Why you choose these SPs, they are unreachable on the https://filrep.io/.

**Comment by yuwenhui** [comment]
> markartisan.com do not work now, so it is hard to check your business started from 2017. Can you elaborate on the data composition and source of 5P? Why you choose these SPs, they are unreachable on the https://filrep.io/.
- It is really hard to check our business started from 2017 because we don't use markartisan.com anymore. However, we have some data service contracts with some of our customers, using Matu Beijing Technology Co., Ltd. from 2019 to 2020. I wonder if these contracts can prove our business. If so, could you please give me an email, i can send you some photos of these business contracts.
- About the data composition and source of 5P:
    Name | Source | Size
    ------------|----|----
    Object tracking videos for autonomous driving | Customers | 3PiB
    Pictures extracted from object tracking videos | Customers | 1.5PiB
    Scene flow evaluation videos and pictures | Customers | 2.3PiB
    Football scene motion tracking videos and pictures | Customers | 0.8PiB
    3D object detection re-annotation of [Kitti dataset](http://www.cvlibs.net/datasets/kitti/eval_object.php?obj_benchmark=3d) | Public dataset | 1.5PiB
    Printing production line tracking and checking videos | Customers | 0.8PiB
    High-tension transmission line HD pictures | Customers | 500TiB
    Face recognition raw data, annotation data | Customers | 300TiB
    Clothes like t-shirts and trousers raw data, annotation data | Crawled from search angine such as Google, Yandex | 50TiB
    Human posture behavior pictures raw data, annotation data | Crawled from search angine | 30TiB

- We choose these SPs because  we will distribute our data offline to them, we can contacted them at present, and they also agree to transfer and store these data offline. These SPs will be reachable after our data send to them.

**Comment by Sunnyiscoming** [comment]
Please provide more data samples related with the data types you said above.
![image](https://user-images.githubusercontent.com/105098820/188824741-2eae1ffe-9bcb-47fd-890f-c23bc7813328.png)
Could you send an email with business contracts to filplus-app-review@fil.org with your official domain in order to confirm your identity and business? Email name should includes the issue id #653.

**Comment by yuwenhui** [comment]
Here are some more data samples:
- [Object tracking annotation for autonomous driving](https://drive.google.com/drive/folders/1AhVsADS9yTUfplV0OxKPD6wHaxU3OL0n?usp=sharing)
- [Football scene motion tracking videos and pictures](https://drive.google.com/drive/folders/1sg13spNpbzEzGPIXdPLqdNJvuVBob3Ji?usp=sharing)
- [3D object detection re-annotation of Kitti dataset](https://drive.google.com/drive/folders/1sg13spNpbzEzGPIXdPLqdNJvuVBob3Ji?usp=sharing)
- [Face recognition raw data, annotation data](https://drive.google.com/drive/folders/16UIq6wot8B4fpJt28DXPKQxUALmURxL3?usp=sharing)
- [Clothes like t-shirts and trousers raw data, annotation data](https://drive.google.com/drive/folders/12CQ8bWBXlTiYTWEcFAdoXHVJ2OfHzVmQ?usp=sharing)
- [Cable, slipper, socks annotation for research](https://drive.google.com/drive/folders/1smETCXTDXyHksYUQtca1YzU8RqU3xj34?usp=sharing)
- [Traffic cone recognition annotation](https://drive.google.com/drive/folders/1MO3FpbCOArJ6yfaq2hy_J4i3sAr74apG?usp=sharing)
- [Vehicle, bota and human detection annotation](https://drive.google.com/drive/folders/1r-7uwBK6TgcQJH0CG63lFzWcXi5aMDWc?usp=sharing)

And the confirm email has sent to [filplus-app-review@fil.org](mailto:filplus-app-review@fil.org) from max@fileguard.io, please check it.

<img width="806" alt="image" src="https://user-images.githubusercontent.com/1715211/189816450-073b4d3d-c135-44a5-a154-8925c8f13c6b.png">

**Comment by yuwenhui** [comment]
@galen-mcandrew @Sunnyiscoming Could you please check the confirm email? And can i have to supply more data samples?

**Comment by Sunnyiscoming** [comment]
Received that.

**Comment by yuwenhui** [comment]
@raghavrmadya Hello, Raghav, what should i do next?

**Comment by yuwenhui** [comment]
@Sunnyiscoming @raghavrmadya  Hello, what should i do next?

**Comment by raghavrmadya** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 100TiB

**Client address**

>f1gwuigefejd5jkbtg4uznx45toaie5olh2cgm3dq

**Comment by raghavrmadya** [comment]
Moving ahead with the trigger as the client has been responsive. Notaries, please take time to conduct your own due diligence before proposing and approving

**Comment by kernelogic** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec7zrp2lab6q7yzzcvb2ojfxcjehqrlbidogz4dgat7zlglgjfije 
#### Address 
> f1gwuigefejd5jkbtg4uznx45toaie5olh2cgm3dq
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec7zrp2lab6q7yzzcvb2ojfxcjehqrlbidogz4dgat7zlglgjfije

**Comment by liyunzhi-666** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacea2vrhgxzuhi6dgfcdfi4zkmm3skfcbgyl6q2fgd42ztbhi665ksg 
#### Address 
> f1gwuigefejd5jkbtg4uznx45toaie5olh2cgm3dq
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1pszcrsciyixyuxxukkvtazcokexbn54amf7gvoq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacea2vrhgxzuhi6dgfcdfi4zkmm3skfcbgyl6q2fgd42ztbhi665ksg

**Comment by BigD-Exchange** [comment]
@yuwenhui Hi! Great to see you have gotten approval for DataCap and advancing the mission of preserving humanity’s most important information. If you are looking for storage providers to store these data or have any questions, please visit #bigdata-exchange on Filecoin Slack or reply here. 

We have strong demand from a diverse group of SPs, who are actively looking to onboard more data.

**Comment by psh0691** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceauqpgy72ktewhbqa3t6bl26igh7x5xk2kira3wyyu37saknnr6lo 
#### Address 
> f1gwuigefejd5jkbtg4uznx45toaie5olh2cgm3dq
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1qdko4jg25vo35qmyvcrw4ak4fmuu3f5rif2kc7i
#### Id
> 7442f717-c4b0-481c-95ac-79d07afa0d11
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceauqpgy72ktewhbqa3t6bl26igh7x5xk2kira3wyyu37saknnr6lo

**Comment by Fenbushi-Filecoin** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceajv43whoaw3wlxngjmkgatuv23pde26tnrryvhu2auccg3zup2de 
#### Address 
> f1gwuigefejd5jkbtg4uznx45toaie5olh2cgm3dq
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1yqydpmqb5en262jpottko2kd65msajax7fi4rmq
#### Id
> 7442f717-c4b0-481c-95ac-79d07afa0d11
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceajv43whoaw3wlxngjmkgatuv23pde26tnrryvhu2auccg3zup2de

**Comment by filplus-checker** [comment]
## DataCap and CID Checker Report[^1]
 - Organization: `FeigeData`
 - Client: `f1gwuigefejd5jkbtg4uznx45toaie5olh2cgm3dq`
### Storage Provider Distribution
The below table shows the distribution of storage providers that have stored data for this client.

If this is the first time a provider takes verified deal, it will be marked as `new`.

For most of the datacap application, below restrictions should apply.
 - Storage provider should not exceed 25% of total datacap.
 - Storage provider should not be storing duplicate data for more than 20%.
 - Storage provider should have published its public IP address.
 - All storage providers should be located in different regions.

⚠️ [f01824405](https://filfox.info/en/address/f01824405) has sealed 36.91% of total datacap.

⚠️ [f01941622](https://filfox.info/en/address/f01941622) has sealed 32.02% of total datacap.

| Provider                                              |             Location | Total Deals Sealed | Percentage | Unique Data | Duplicate Deals |
| :---------------------------------------------------- | -------------------: | -----------------: | ---------: | ----------: | --------------: |
| [f01824405](https://filfox.info/en/address/f01824405) |  Deyang, Sichuan, CN |          18.16 TiB |     36.91% |   18.16 TiB |           0.00% |
| [f01941622](https://filfox.info/en/address/f01941622) | Chengdu, Sichuan, CN |          15.75 TiB |     32.02% |   15.69 TiB |           0.40% |
| [f01939387](https://filfox.info/en/address/f01939387) | Chengdu, Sichuan, CN |           8.31 TiB |     16.90% |    8.31 TiB |           0.00% |
| [f01939377](https://filfox.info/en/address/f01939377) | Chengdu, Sichuan, CN |           6.97 TiB |     14.17% |    6.97 TiB |           0.00% |

![Provider Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/653/1671097620703.png)
### Deal Data Replication
The below table shows how each many unique data are replicated across storage providers.
- No more than 25% of unique data are stored with less than 4 providers.

⚠️ 100.00% of deals are for data replicated across less than 4 storage providers.

| Unique Data Size | Total Deals Made | Number of Providers | Deal Percentage |
| ---------------: | ---------------: | ------------------: | --------------: |
|        46.50 TiB |        46.56 TiB |                   1 |          94.66% |
|         1.31 TiB |         2.63 TiB |                   2 |           5.34% |

![Replication Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/653/1671097621480.png)
### Deal Data Shared with other Clients
The below table shows how many unique data are shared with other clients.
Usually different applications owns different data and should not resolve to the same CID.

⚠️ CID sharing has been observed.

| Other Client                                                                                                          | Application                                                                               | Total Deals Affected | Unique CIDs |        Verifier |
| :-------------------------------------------------------------------------------------------------------------------- | :---------------------------------------------------------------------------------------- | -------------------: | ----------: | --------------: |
| [f1ud77rddmchv4uvwpuoau3rag5rzcdtkqy45uycy](https://filfox.info/en/address/f1ud77rddmchv4uvwpuoau3rag5rzcdtkqy45uycy) | [Xuetianxia](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/650) |            20.00 TiB |         318 | LDN v3 multisig |

[^1]: To manually trigger this report, add a comment with text `checker:manualTrigger`

**Comment by yuwenhui** [comment]
checker:manualTrigger

**Comment by cryptowhizzard** [comment]
Hello 

There is CID sharing going on between this application and #650.

Can you tell us why?

**Comment by cryptowhizzard** [comment]
Secondly, i checked and it seems the data is not readily retrievable as stated in the [FIL+ rules](https://github.com/filecoin-project/filecoin-plus-large-datasets/)

Why is the data not retrievable?

Can you provide us with the unsealed sectors of this CID's so we can unpack them, do commP on them and verify the data?

<img width="868" alt="Scherm­afbeelding 2023-01-20 om 17 40 12" src="https://user-images.githubusercontent.com/36404435/213754210-d45a1655-a4dd-4e5e-b651-40faaf64ef85.png">



>>
cat /root/Dropbox/clientdealscannerdone/f01904026.csv.log
/usr/local/bin/lotus state get-deal 13496038 
/usr/local/bin/lotus client retrieve --provider f01939387 uAXASIJUIbKNT7CJlA2dqA_8W8qDJJU54-wJ3ZcyDmKYNvr9H
/usr/local/bin/lotus state get-deal 13496039 
/usr/local/bin/lotus client retrieve --provider f01939387 uAXASIN3TG0ev7jWD2lKa9wXVx6sSARZXm_HTm9Mt20Xeswbl
/usr/local/bin/lotus state get-deal 13508033 
/usr/local/bin/lotus client retrieve --provider f01939377 uAXASIP4Q5xrFjzGoI8vmzHbuc2Ki9dzDgz5_aebgipgvqswx
/usr/local/bin/lotus state get-deal 13508034 
/usr/local/bin/lotus client retrieve --provider f01939377 uAXASIF1Kp4j8JEN09XgOdDRtnc3xBJv6ZL7d7LstBhkmgaOU
/usr/local/bin/lotus state get-deal 13576086 
/usr/local/bin/lotus client retrieve --provider f01941622 uAXASIIClU5_PeYXu4MJvFHHPHRJhB5CnvTNVVWYEgaqeHBX_
/usr/local/bin/lotus state get-deal 13576087 
/usr/local/bin/lotus client retrieve --provider f01941622 uAXASIDCilqWAqWhY_D_boM4u-cAzIZCoZuuY-PyH2HH6SuCt
/usr/local/bin/lotus state get-deal 13588690 
/usr/local/bin/lotus client retrieve --provider f01941622 uAXASIEHXhvaB1_6dp7F5i9geHM8aNsIz59njIk-e1cV_vqzN
/usr/local/bin/lotus state get-deal 13588691 
/usr/local/bin/lotus client retrieve --provider f01941622 uAXASIIJqI_n0lNPxsUOIJeL_E5VwodgMIcb8m_jSy2pWzz6v
ERROR: offer error: retrieval query offer errored: failed to fetch piece to retrieve from: getting pieces for cid bafybeieauvjz7t3zqxxobqtpcry46hismedzbj55gnkvkzqeqgvj4hav74: getting pieces containing block bafybeieauvjz7t3zqxxobqtpcry46hismedzbj55gnkvkzqeqgvj4hav74: failed to lookup index for mh 122080a5539fcf7985eee0c26f1471cf1d12610790a7bd335555660481aa9e1c15ff, err: datastore: key not found

ERROR: offer error: retrieval query offer errored: failed to fetch piece to retrieve from: getting pieces for cid bafybeibquklklafjnbmpyp63udhc56oagmqzbkdg5ompr7eh3by7usxavu: getting pieces containing block bafybeibquklklafjnbmpyp63udhc56oagmqzbkdg5ompr7eh3by7usxavu: failed to lookup index for mh 122030a296a580a96858fc3fdba0ce2ef9c0332190a866eb98f8fc87d871fa4ae0ad, err: datastore: key not found

ERROR: offer error: retrieval query offer errored: failed to fetch piece to retrieve from: getting pieces for cid bafybeicb26dpnaox72o2pmlzrpmb4hgpdi3mem7h3hrset462xcx7pvmzu: getting pieces containing block bafybeicb26dpnaox72o2pmlzrpmb4hgpdi3mem7h3hrset462xcx7pvmzu: failed to lookup index for mh 122041d786f681d7fe9da7b1798bd81e1ccf1a36c233e7d9e3224f9ed5c57fbeaccd, err: datastore: key not found

ERROR: offer error: retrieval query offer errored: failed to fetch piece to retrieve from: getting pieces for cid bafybeiecnir7t5eu2py3cq4iexrp6e4vocq5qdbby36jx6gsznvfntz6v4: getting pieces containing block bafybeiecnir7t5eu2py3cq4iexrp6e4vocq5qdbby36jx6gsznvfntz6v4: failed to lookup index for mh 1220826a23f9f494d3f1b1438825e2ff139570a1d80c21c6fc9bf8d2cb6a56cf3eaf, err: datastore: key not found

Recv 0 B, Paid 0 FIL, Open (New), 0s [1673908265200556143|0]
Recv 0 B, Paid 0 FIL, DealProposed (WaitForAcceptance), 14ms [1673908265200556143|0]
Recv 0 B, Paid 0 FIL, Open (New), 0s [1673908265200556144|0]
Recv 0 B, Paid 0 FIL, DealProposed (WaitForAcceptance), 14ms [1673908265200556144|0]
Recv 0 B, Paid 0 FIL, Open (New), 0s [1673908265200556145|0]
Recv 0 B, Paid 0 FIL, DealProposed (WaitForAcceptance), 14ms [1673908265200556145|0]
Recv 0 B, Paid 0 FIL, Open (New), 0s [1673908265200556146|0]
Recv 0 B, Paid 0 FIL, DealProposed (WaitForAcceptance), 15ms [1673908265200556146|0]

**Comment by yuwenhui** [comment]
@cryptowhizzard 

> This is not what is stated in the LDN application. This LDN is about "The data stored on Filecoin is raw pictures and annotation results(JSON format)."

As commented here: https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/653#issuecomment-1233684864

Name | Source | Size
------------|----|----
Object tracking videos for autonomous driving | Customers | 3PiB
Pictures extracted from object tracking videos | Customers | 1.5PiB
Scene flow evaluation videos and pictures | Customers | 2.3PiB
Football scene motion tracking videos and pictures | Customers | 0.8PiB
3D object detection re-annotation of [Kitti dataset](http://www.cvlibs.net/datasets/kitti/eval_object.php?obj_benchmark=3d) | Public dataset | 1.5PiB
Printing production line tracking and checking videos | Customers | 0.8PiB
High-tension transmission line HD pictures | Customers | 500TiB
Face recognition raw data, annotation data | Customers | 300TiB
Clothes like t-shirts and trousers raw data, annotation data | Crawled from search engine such as Google, Yandex | 50TiB
Human posture behavior pictures raw data, annotation data | Crawled from search engine | 30TiB

I have gave more data samples including object tracking videos, scene flow evaluation videos, production line tracking and checking videos and so on. As a crowdsourcing platform, Fileguard will receive more customer's annotation requirements, and will save more data on Filecoin Network, not only pictures and JSON files.

**Comment by yuwenhui** [comment]
@cryptowhizzard Hello, Thanks for your check on our LDN.


> Secondly, i checked and it seems the data is not readily retrievable as stated in the [FIL+ rules](https://github.com/filecoin-project/filecoin-plus-large-datasets/)
> 
> Why is the data not retrievable?
> 
> Can you provide us with the unsealed sectors of this CID's so we can unpack them, do commP on them and verify the data?
> 
> <img alt="Scherm­afbeelding 2023-01-20 om 17 40 12" width="868" src="https://user-images.githubusercontent.com/36404435/213754210-d45a1655-a4dd-4e5e-b651-40faaf64ef85.png">
> 
> > >
> 
> cat /root/Dropbox/clientdealscannerdone/f01904026.csv.log /usr/local/bin/lotus state get-deal 13496038 /usr/local/bin/lotus client retrieve --provider f01939387 uAXASIJUIbKNT7CJlA2dqA_8W8qDJJU54-wJ3ZcyDmKYNvr9H /usr/local/bin/lotus state get-deal 13496039 /usr/local/bin/lotus client retrieve --provider f01939387 uAXASIN3TG0ev7jWD2lKa9wXVx6sSARZXm_HTm9Mt20Xeswbl /usr/local/bin/lotus state get-deal 13508033 /usr/local/bin/lotus client retrieve --provider f01939377 uAXASIP4Q5xrFjzGoI8vmzHbuc2Ki9dzDgz5_aebgipgvqswx /usr/local/bin/lotus state get-deal 13508034 /usr/local/bin/lotus client retrieve --provider f01939377 uAXASIF1Kp4j8JEN09XgOdDRtnc3xBJv6ZL7d7LstBhkmgaOU /usr/local/bin/lotus state get-deal 13576086 /usr/local/bin/lotus client retrieve --provider f01941622 uAXASIIClU5_PeYXu4MJvFHHPHRJhB5CnvTNVVWYEgaqeHBX_ /usr/local/bin/lotus state get-deal 13576087 /usr/local/bin/lotus client retrieve --provider f01941622 uAXASIDCilqWAqWhY_D_boM4u-cAzIZCoZuuY-PyH2HH6SuCt /usr/local/bin/lotus state get-deal 13588690 /usr/local/bin/lotus client retrieve --provider f01941622 uAXASIEHXhvaB1_6dp7F5i9geHM8aNsIz59njIk-e1cV_vqzN /usr/local/bin/lotus state get-deal 13588691 /usr/local/bin/lotus client retrieve --provider f01941622 uAXASIIJqI_n0lNPxsUOIJeL_E5VwodgMIcb8m_jSy2pWzz6v ERROR: offer error: retrieval query offer errored: failed to fetch piece to retrieve from: getting pieces for cid bafybeieauvjz7t3zqxxobqtpcry46hismedzbj55gnkvkzqeqgvj4hav74: getting pieces containing block bafybeieauvjz7t3zqxxobqtpcry46hismedzbj55gnkvkzqeqgvj4hav74: failed to lookup index for mh 122080a5539fcf7985eee0c26f1471cf1d12610790a7bd335555660481aa9e1c15ff, err: datastore: key not found
> 
> ERROR: offer error: retrieval query offer errored: failed to fetch piece to retrieve from: getting pieces for cid bafybeibquklklafjnbmpyp63udhc56oagmqzbkdg5ompr7eh3by7usxavu: getting pieces containing block bafybeibquklklafjnbmpyp63udhc56oagmqzbkdg5ompr7eh3by7usxavu: failed to lookup index for mh 122030a296a580a96858fc3fdba0ce2ef9c0332190a866eb98f8fc87d871fa4ae0ad, err: datastore: key not found
> 
> ERROR: offer error: retrieval query offer errored: failed to fetch piece to retrieve from: getting pieces for cid bafybeicb26dpnaox72o2pmlzrpmb4hgpdi3mem7h3hrset462xcx7pvmzu: getting pieces containing block bafybeicb26dpnaox72o2pmlzrpmb4hgpdi3mem7h3hrset462xcx7pvmzu: failed to lookup index for mh 122041d786f681d7fe9da7b1798bd81e1ccf1a36c233e7d9e3224f9ed5c57fbeaccd, err: datastore: key not found
> 
> ERROR: offer error: retrieval query offer errored: failed to fetch piece to retrieve from: getting pieces for cid bafybeiecnir7t5eu2py3cq4iexrp6e4vocq5qdbby36jx6gsznvfntz6v4: getting pieces containing block bafybeiecnir7t5eu2py3cq4iexrp6e4vocq5qdbby36jx6gsznvfntz6v4: failed to lookup index for mh 1220826a23f9f494d3f1b1438825e2ff139570a1d80c21c6fc9bf8d2cb6a56cf3eaf, err: datastore: key not found
> 
> Recv 0 B, Paid 0 FIL, Open (New), 0s [1673908265200556143|0] Recv 0 B, Paid 0 FIL, DealProposed (WaitForAcceptance), 14ms [1673908265200556143|0] Recv 0 B, Paid 0 FIL, Open (New), 0s [1673908265200556144|0] Recv 0 B, Paid 0 FIL, DealProposed (WaitForAcceptance), 14ms [1673908265200556144|0] Recv 0 B, Paid 0 FIL, Open (New), 0s [1673908265200556145|0] Recv 0 B, Paid 0 FIL, DealProposed (WaitForAcceptance), 14ms [1673908265200556145|0] Recv 0 B, Paid 0 FIL, Open (New), 0s [1673908265200556146|0] Recv 0 B, Paid 0 FIL, DealProposed (WaitForAcceptance), 15ms [1673908265200556146|0]

We have checked these SPs you mentioned, and found that all the deals f01939387 and f01939377 stored can be retrieved very well. However, some deals of f01941622 can not retrieve correctly (about 5%). As this situation, we have stopped sending more deals to them. We will continue to find more SPs who can provide more efficiently and smoothly storage service.

**Comment by data-programs** [comment]
<img width="32" alt="KYC" Verified src="https://stable.filplus.storage/images/filplus-kyc-verified-badge.png"/>

This user’s identity has been verified through [filplus.storage](https://filplus.storage)
