### ISSUE TITLE
[DataCap Application] Bole Digital

### ISSUE THREAD

**Issue by BoleDigital** [filecoin-project/filecoin-plus-large-datasets#654]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Bole digital
- Website / Social Media: https://www.po12.com/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):100TiB
- On-chain address for first allocation:f1fmdka4yaspkjp3kw65azeygbmgp5dujl6wlghti

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
We are a team with a background in industrial. Our team is a mixed team of "light industrial design", "planning", "video" and "marketing". We are enthusiastic and puts 100% passion and creativity into every project to make your brand or product meaningful.
```

What is the primary source of funding for this project?
```
Own income.
```

What other projects/ecosystem stakeholders is this project associated with?
```
No.
```

## Use-case details

Describe the data being stored onto Filecoin
```
Promotion videos.
```

Where was the data in this dataset sourced from?
```
We provide services such as video filming and production.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
[14.zip](https://github.com/filecoin-project/filecoin-plus-large-datasets/files/9338809/14.zip)
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes.
```

What is the expected retrieval frequency for this data?
```
Once a year. We mainly store these data as copies.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
2 years
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Asia.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Offline data transfer is our first choice. 
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We'll use slack and github to find out suitable SP and they should approve retrieval.
```

How will you be distributing deals across storage providers?
```
Every Sp will be given under 25% whole deals.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes.
```

**Comment by Sunnyiscoming** [comment]
Can you provide more information about organization? What's the relationship between you and organization?
Can you provide more detailed information about other storage providers participated in this program, such as you can list SPs you have contacted with at present?
Could you send an email to filplus-app-review@fil.org with your official domain in order to confirm your identity? Email name should includes the issue id #654.

**Comment by BoleDigital** [comment]
We are a team with a background in industrial. Our team is located in Taichung, Taiwan. I am an employee of Bole Digital, and my boss asked me to apply for datacap. We've contacted f0504054, which can cooperate with us in the next process. The ideal region for us to send deals to is China, Japan. Our team will attempt to find more storage providers from Asian countries.
![5email](https://user-images.githubusercontent.com/107545368/188499744-368b8136-495f-4a16-9960-366c56a0a98c.png)

**Comment by Sunnyiscoming** [comment]
Received email.

**Comment by raghavrmadya** [comment]
Hi, we need more data samples. 5 PiBs of promotional videos is quite hard to believe and we would like to know about the scale of your business operations. Please provide at least 10 samples as supporting evidence for your requested amount of DC

**Comment by BoleDigital** [comment]
@raghavrmadya https://drive.google.com/file/d/1kVEXigTpda4Zs-0aVljo20pXea0c9G-I/view?usp=sharing hi, I've uploaded my dataset. Many of our designs are 4k HD videos with a large amount of data, I have only selected a small amount of sample to show.

**Comment by raghavrmadya** [comment]
Still, 5 PiBs of promotional videos is an insane amount of data? How much data do you have and how many copies are you storing?

**Comment by BoleDigital** [comment]
@raghavrmadya Hi Raghav, actually the size of 4k HD videos is usually large, and the dataset I showed is just a little part of whole data. Now we have 531.2TiB data which need to be stored as 10 copies. As it is closely related to our business, we want to keep this data in a good way by filecoin.

**Comment by raghavrmadya** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 100TiB

**Client address**

>f1fmdka4yaspkjp3kw65azeygbmgp5dujl6wlghti

**Comment by 1475Notary** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecr222t32kp426c5ej32x52fqvmsmg2732wnkfst3zurrjv7jema4 
#### Address 
> f1fmdka4yaspkjp3kw65azeygbmgp5dujl6wlghti
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1ofq4mngy7ggcp755pfquq2gphjjnlydolf6awtq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecr222t32kp426c5ej32x52fqvmsmg2732wnkfst3zurrjv7jema4

**Comment by liyunzhi-666** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceagzsctkgpkyzlfzzsywdrf6ixb4cdfv6bi3me6yvvdsoliwejnjy 
#### Address 
> f1fmdka4yaspkjp3kw65azeygbmgp5dujl6wlghti
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1pszcrsciyixyuxxukkvtazcokexbn54amf7gvoq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceagzsctkgpkyzlfzzsywdrf6ixb4cdfv6bi3me6yvvdsoliwejnjy

**Comment by BigD-Exchange** [comment]
@BoleDigital Hi! Great to see you have gotten approval for DataCap and advancing the mission of preserving humanity’s most important information. If you are looking for storage providers to store these data or have any questions, please visit #bigdata-exchange on Filecoin Slack or reply here. 

We have strong demand from a diverse group of SPs, who are actively looking to onboard more data.

**Comment by UnionLabs2020** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecodmniz6vhjtrmysci3s4z3xcarrbtf3jbokycy6jahvoomlw3as 
#### Address 
> f1fmdka4yaspkjp3kw65azeygbmgp5dujl6wlghti
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f17xdri3wunqgld7dm23e4f3eqsntjakwc47xjo6i
#### Id
> 84b88189-a2f2-4021-8833-7db62a9bda35
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecodmniz6vhjtrmysci3s4z3xcarrbtf3jbokycy6jahvoomlw3as

**Comment by MetaWaveInfo** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecak7tkcjmbkz4s4awxgegeeguiw6mkw7dlscfb5ipigvf5c25e5s 
#### Address 
> f1fmdka4yaspkjp3kw65azeygbmgp5dujl6wlghti
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1ktlkcxnmzxcdaoqfsunrg3vocfbmgv4n3mrn74a
#### Id
> 84b88189-a2f2-4021-8833-7db62a9bda35
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecak7tkcjmbkz4s4awxgegeeguiw6mkw7dlscfb5ipigvf5c25e5s

**Comment by filplus-checker** [comment]
## DataCap and CID Checker Report[^1]
 - Organization: `Bole digital`
 - Client: `f1fmdka4yaspkjp3kw65azeygbmgp5dujl6wlghti`
### Storage Provider Distribution
The below table shows the distribution of storage providers that have stored data for this client.

If this is the first time a provider takes verified deal, it will be marked as `new`.

For most of the datacap application, below restrictions should apply.
 - Storage provider should not exceed 25% of total datacap.
 - Storage provider should not be storing duplicate data for more than 20%.
 - Storage provider should have published its public IP address.
 - All storage providers should be located in different regions.

⚠️ [f01974746](https://filfox.info/en/address/f01974746) has sealed 35.90% of total datacap.

⚠️ 89.75% of total deal sealed by [f01974746](https://filfox.info/en/address/f01974746) are duplicate data.

⚠️ [f01974746](https://filfox.info/en/address/f01974746) has unknown IP location.

⚠️ 89.90% of total deal sealed by [f01962589](https://filfox.info/en/address/f01962589) are duplicate data.

⚠️ [f01962589](https://filfox.info/en/address/f01962589) has unknown IP location.

⚠️ 79.78% of total deal sealed by [f01926802](https://filfox.info/en/address/f01926802) are duplicate data.

⚠️ 77.02% of total deal sealed by [f01926914](https://filfox.info/en/address/f01926914) are duplicate data.

⚠️ 78.91% of total deal sealed by [f01926585](https://filfox.info/en/address/f01926585) are duplicate data.

| Provider                                              |              Location | Total Deals Sealed | Percentage | Unique Data | Duplicate Deals |
| :---------------------------------------------------- | --------------------: | -----------------: | ---------: | ----------: | --------------: |
| [f01974746](https://filfox.info/en/address/f01974746) |               Unknown |          44.81 TiB |     35.90% |    4.59 TiB |          89.75% |
| [f01962589](https://filfox.info/en/address/f01962589) |               Unknown |          30.00 TiB |     24.04% |    3.03 TiB |          89.90% |
| [f01926802](https://filfox.info/en/address/f01926802) | Ashburn, Virginia, US |          17.00 TiB |     13.62% |    3.44 TiB |          79.78% |
| [f01926914](https://filfox.info/en/address/f01926914) | Ashburn, Virginia, US |          17.00 TiB |     13.62% |    3.91 TiB |          77.02% |
| [f01926585](https://filfox.info/en/address/f01926585) | Ashburn, Virginia, US |          16.00 TiB |     12.82% |    3.38 TiB |          78.91% |

![Provider Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/654/1671097629879.png)
### Deal Data Replication
The below table shows how each many unique data are replicated across storage providers.
- No more than 25% of unique data are stored with less than 4 providers.

⚠️ 100.00% of deals are for data replicated across less than 4 storage providers.

| Unique Data Size | Total Deals Made | Number of Providers | Deal Percentage |
| ---------------: | ---------------: | ------------------: | --------------: |
|        13.72 TiB |       106.56 TiB |                   1 |          85.38% |
|         2.31 TiB |        18.25 TiB |                   2 |          14.62% |

![Replication Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/654/1671097630533.png)
### Deal Data Shared with other Clients
The below table shows how many unique data are shared with other clients.
Usually different applications owns different data and should not resolve to the same CID.

⚠️ CID sharing has been observed.

| Other Client                                                                                                          | Application                                                                                                   | Total Deals Affected | Unique CIDs |        Verifier |
| :-------------------------------------------------------------------------------------------------------------------- | :------------------------------------------------------------------------------------------------------------ | -------------------: | ----------: | --------------: |
| [f1zav4f4rak2yvbrq357z3whj224wn4dipl7eiesy](https://filfox.info/en/address/f1zav4f4rak2yvbrq357z3whj224wn4dipl7eiesy) | [Shanghai Zhixun](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/628)                |            17.56 TiB |         113 | LDN v3 multisig |
| [f1l2hkjqfh5abpd5x6lxj4tjrphaa44pnumt5ms5i](https://filfox.info/en/address/f1l2hkjqfh5abpd5x6lxj4tjrphaa44pnumt5ms5i) | [Fly Brain Anatomy \- Slingshot](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/153) |            16.50 TiB |         127 |       LDN # 153 |
| [f1xyx3tvfoy7ue62oqdtcpud5ewcw2i7ctu4kyylq](https://filfox.info/en/address/f1xyx3tvfoy7ue62oqdtcpud5ewcw2i7ctu4kyylq) | [zhenshuai](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/332)                      |           608.00 GiB |           4 |       LDN # 332 |
| [f1jsgrkuicjbw5g3u7f4tcs4b6zdctwxq4h6rw5na](https://filfox.info/en/address/f1jsgrkuicjbw5g3u7f4tcs4b6zdctwxq4h6rw5na) | [Neusoft](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/972)                        |           352.00 GiB |           3 | LDN v3 multisig |
| [f1quofpadzcqlonmz7v3mv7dfqvm5hdztucdsjqsy](https://filfox.info/en/address/f1quofpadzcqlonmz7v3mv7dfqvm5hdztucdsjqsy) | [HENAN 863 SOFTWARE CO\., LTD](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/468)   |           224.00 GiB |           1 | LDN v3 multisig |

[^1]: To manually trigger this report, add a comment with text `checker:manualTrigger`
