### ISSUE TITLE
[DataCap Application]Beijing Haishi Hengtong Technology Co., LTD

### ISSUE THREAD

**Issue by poemtoto** [filecoin-project/filecoin-plus-large-datasets#66]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Beijing Haishi Hengtong Technology Co., LTD
- Website / Social Media:http://www.bjseatv.com/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 1.5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 80TiB
- On-chain address for first allocation:f3qvn7f5u4z5w5pqx3htckp4jcn5dvgmebq6qkqczxdxkicwokf75tt5hbwtrjwldz2sjiyq752ajcn3nd5tgq

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Beijing Haishi Hengtong Technology Co., Ltd. was founded in 2008. It is a company specializing in radio and television industry, equipment, research and development and promotion of high-tech enterprise. For a long time, the company spirit of sincere, to create a win-win situation for the purpose, with professional technical strength, stable quality, perfect service enables users have the most stable and cost-effective products. Products all over the country for television, cable stations, network companies, monitoring station, relay stations, transmitters and so on, to provide users with flexible, reliable and practical solution. Has been with Shandong TV, the launch pad, Yibin, Sichuan and dozens of radio and television units to achieve successful cooperation. According to television stations, cable television signals broadcast on the actual needs of security, depending on the series of self-monitoring of products from the safety, quality, content, the face of all three signals, real-time monitoring, improve television stations, cable TV broadcast The degree of automation, the establishment of a complete signal monitoring system. The system can quickly determine the source of various abnormal conditions arise, including the static frames, video loss, audio is lost, RF target abnormal Logo loss and so on, through the alarm to remind the staff on duty as soon as possible to handle problems. At the same time the system will automatically fail the course of the video, technical indicators, as historical data stored for later query. System provides multi-screen high-resolution images for large-screen monitors display output can also be used to monitor the output of plasma TV wall, replacing the original TV wall function.
```

What is the primary source of funding for this project?
```
The company provides specific support for data storage.
```

What other projects/ecosystem stakeholders is this project associated with?
```
IPFS/Filecoin
```

## Use-case details

Describe the data being stored onto Filecoin
```
Material information, edited playback information, and etc.
```

Where was the data in this dataset sourced from?
```
This dataset sourced from business.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
Link：https://pan.baidu.com/s/1Q773UJG1bS6fAFEqbvM_FQ Code：69zu 
Link：https://pan.baidu.com/s/1Knu0B2x4TRdYZmiQwovEBw Code：ntu5 
Link：https://pan.baidu.com/s/1Z6DbPeyA-A5DJnIpmiHV5g Code：5er8 
Link：https://pan.baidu.com/s/19hRy0w-LAFO_lbDffbGKMA Code：8ked 
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes， we confirm that.
```

What is the expected retrieval frequency for this data?
```
At present, the retrieval frequency is relatively low.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
Permanent storage as very important business data.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Mainland China.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
We will distribute the data to storage providers both online and offline.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
The main factors we considered are the following: 
1. Location (Mainland China) 
2. Possess of rich experience in dealing with verified data
3. Possess of legal company background
```

How will you be distributing deals across storage providers?
```
We will follow the rules for large-datasets. We will divide our data into many parts and make records about our data distribution. 
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
We have already contacted some storage providers and don't need more help at the moment.
```

**Comment by MRJAVAZHAO** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebsmwvqinshvm4fkp55uo3g7cccytt5xzg2i7zootemy3lg4xpueu 
#### Address 
> f3qvn7f5u4z5w5pqx3htckp4jcn5dvgmebq6qkqczxdxkicwokf75tt5hbwtrjwldz2sjiyq752ajcn3nd5tgq
#### Datacap Allocated
> 40TiB
#### Signer Address
> f14gme3f52prtyzk6pblogrdd6b6ivp4swc6qmesi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebsmwvqinshvm4fkp55uo3g7cccytt5xzg2i7zootemy3lg4xpueu

**Comment by swatchliu** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebulak3pxn4yipw2dvhbmb5wxybqrcitmuz4f5l7kvkpdnnyi6hh2 
#### Address 
> f3qvn7f5u4z5w5pqx3htckp4jcn5dvgmebq6qkqczxdxkicwokf75tt5hbwtrjwldz2sjiyq752ajcn3nd5tgq
#### Datacap Allocated
> 40TiB
#### Signer Address
> f1yh6q3nmsg7i2sys7f7dexcuajgoweudcqj2chfi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebulak3pxn4yipw2dvhbmb5wxybqrcitmuz4f5l7kvkpdnnyi6hh2

**Comment by galen-mcandrew** [comment]
Not sure why the top provider is reporting out as 0. A quick check here https://filplus.d.interplanetary.one/notaries/f01403224/breakdown and I'm seeing top as ~8%

@fabriziogianni7

**Comment by fabriziogianni7** [comment]
@galen-mcandrew the bot should parse those values correctly now

**Comment by Reiers** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacea2tdveo4k2c4zgmgzbnitevv53mh2id7ovmbwjllgt6e24yzez7k 
#### Address 
> f3qvn7f5u4z5w5pqx3htckp4jcn5dvgmebq6qkqczxdxkicwokf75tt5hbwtrjwldz2sjiyq752ajcn3nd5tgq
#### Datacap Allocated
> 80.00TiB
#### Signer Address
> f1oz43ckvmtxmmsfzqm6bpnemqlavz4ifyl524chq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacea2tdveo4k2c4zgmgzbnitevv53mh2id7ovmbwjllgt6e24yzez7k

**Comment by cryptowhizzard** [comment]
Given the spirit of LDN i won't sign on this one. 

LDN is mean to be distributed globally and not only in China.

**Comment by swatchliu** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecoxwd2yhatrgaocl3pta57qloghl43pzpwgz2g4cfda5f767f7ry 
#### Address 
> f3qvn7f5u4z5w5pqx3htckp4jcn5dvgmebq6qkqczxdxkicwokf75tt5hbwtrjwldz2sjiyq752ajcn3nd5tgq
#### Datacap Allocated
> 160.00TiB
#### Signer Address
> f1yh6q3nmsg7i2sys7f7dexcuajgoweudcqj2chfi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecoxwd2yhatrgaocl3pta57qloghl43pzpwgz2g4cfda5f767f7ry

**Comment by MatrixStorage** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecs426j2mv6trqqr5kk7tefnsfbddeexnp6542l6ka4rq5ebtm7j2 
#### Address 
> f3qvn7f5u4z5w5pqx3htckp4jcn5dvgmebq6qkqczxdxkicwokf75tt5hbwtrjwldz2sjiyq752ajcn3nd5tgq
#### Datacap Allocated
> 160.00TiB
#### Signer Address
> f1tbxqwjxfyv7swsdin4einirlsfquv3vnmlapley
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecs426j2mv6trqqr5kk7tefnsfbddeexnp6542l6ka4rq5ebtm7j2

**Comment by MatrixStorage** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebwk5n5ehp5s2d46zgzp5kmwadoq3tnijrm2dgu6tdhotjpapniu2 
#### Address 
> f3qvn7f5u4z5w5pqx3htckp4jcn5dvgmebq6qkqczxdxkicwokf75tt5hbwtrjwldz2sjiyq752ajcn3nd5tgq
#### Datacap Allocated
> 320.00TiB
#### Signer Address
> f1tbxqwjxfyv7swsdin4einirlsfquv3vnmlapley
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebwk5n5ehp5s2d46zgzp5kmwadoq3tnijrm2dgu6tdhotjpapniu2

**Comment by PluskitOfficial** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebh5vefklsa4txbqiphlenmefo4lppmfuyee4rvdyb37jvu7hjyvc 
#### Address 
> f3qvn7f5u4z5w5pqx3htckp4jcn5dvgmebq6qkqczxdxkicwokf75tt5hbwtrjwldz2sjiyq752ajcn3nd5tgq
#### Datacap Allocated
> 320.00TiB
#### Signer Address
> f1tgnlhtcmhwipfm7thsftxhn5k52velyjlazpvka
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebh5vefklsa4txbqiphlenmefo4lppmfuyee4rvdyb37jvu7hjyvc

**Comment by BigD-Exchange** [comment]
@poemtoto Hi! Great to see you have gotten approval for DataCap. If you are looking for storage providers to store these data or have any questions, please visit #bigdata-exchange on Filecoin Slack or reply here. 

We have strong demand from a diverse group of SPs, who are actively looking to onboard more data.

**Comment by PluskitOfficial** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacear6i2qqbcz3iyahr5guhkd3nvxkod3plbcsd74lcisptrse6zzuy 
#### Address 
> f3qvn7f5u4z5w5pqx3htckp4jcn5dvgmebq6qkqczxdxkicwokf75tt5hbwtrjwldz2sjiyq752ajcn3nd5tgq
#### Datacap Allocated
> 640.00TiB
#### Signer Address
> f1tgnlhtcmhwipfm7thsftxhn5k52velyjlazpvka
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacear6i2qqbcz3iyahr5guhkd3nvxkod3plbcsd74lcisptrse6zzuy

**Comment by MRJAVAZHAO** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced3wedwy5jdi4dnul2sdnjaoeyqhberngp45frpeffqyeq5ioutz4 
#### Address 
> f3qvn7f5u4z5w5pqx3htckp4jcn5dvgmebq6qkqczxdxkicwokf75tt5hbwtrjwldz2sjiyq752ajcn3nd5tgq
#### Datacap Allocated
> 640.00TiB
#### Signer Address
> f14gme3f52prtyzk6pblogrdd6b6ivp4swc6qmesi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced3wedwy5jdi4dnul2sdnjaoeyqhberngp45frpeffqyeq5ioutz4

**Comment by BlockMakeronline** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceddho3vqcauyjmln33sphp6arvroyynwvmqzxxapgd4n7a4lv4fqy 
#### Address 
> f3qvn7f5u4z5w5pqx3htckp4jcn5dvgmebq6qkqczxdxkicwokf75tt5hbwtrjwldz2sjiyq752ajcn3nd5tgq
#### Datacap Allocated
> 416.00TiB
#### Signer Address
> f1o3twrcpwjtpcd4q36lpq4qmy2qfbgtyy5h6tsty
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceddho3vqcauyjmln33sphp6arvroyynwvmqzxxapgd4n7a4lv4fqy

**Comment by MatrixStorage** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecfzkcsj6l53hh3ez74dsamjuft4mscpovy37ghlhbw6ibxognon6 
#### Address 
> f3qvn7f5u4z5w5pqx3htckp4jcn5dvgmebq6qkqczxdxkicwokf75tt5hbwtrjwldz2sjiyq752ajcn3nd5tgq
#### Datacap Allocated
> 416.00TiB
#### Signer Address
> f1tbxqwjxfyv7swsdin4einirlsfquv3vnmlapley
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecfzkcsj6l53hh3ez74dsamjuft4mscpovy37ghlhbw6ibxognon6

**Comment by filplus-checker** [comment]
## DataCap and CID Checker Report[^1]
 - Organization: `Beijing Haishi Hengtong Technology Co., LTD`
 - Client: `f3qvn7f5u4z5w5pqx3htckp4jcn5dvgmebq6qkqczxdxkicwokf75tt5hbwtrjwldz2sjiyq752ajcn3nd5tgq`
### Storage Provider Distribution
The below table shows the distribution of storage providers that have stored data for this client.

If this is the first time a provider takes verified deal, it will be marked as `new`.

For most of the datacap application, below restrictions should apply.
 - Storage provider should not exceed 25% of total datacap.
 - Storage provider should not be storing duplicate data for more than 20%.
 - Storage provider should have published its public IP address.
 - All storage providers should be located in different regions.

⚠️ 35.95% of total deal sealed by [f01852325](https://filfox.info/en/address/f01852325) are duplicate data.

⚠️ 35.42% of total deal sealed by [f01852664](https://filfox.info/en/address/f01852664) are duplicate data.

⚠️ 36.46% of total deal sealed by [f01852677](https://filfox.info/en/address/f01852677) are duplicate data.

⚠️ 37.26% of total deal sealed by [f01851482](https://filfox.info/en/address/f01851482) are duplicate data.

⚠️ 36.32% of total deal sealed by [f01852023](https://filfox.info/en/address/f01852023) are duplicate data.

⚠️ 89.59% of total deal sealed by [f01919535](https://filfox.info/en/address/f01919535) are duplicate data.

⚠️ 39.35% of total deal sealed by [f01938714](https://filfox.info/en/address/f01938714) are duplicate data.

⚠️ 41.79% of total deal sealed by [f01938721](https://filfox.info/en/address/f01938721) are duplicate data.

⚠️ 39.63% of total deal sealed by [f01938665](https://filfox.info/en/address/f01938665) are duplicate data.

⚠️ 36.83% of total deal sealed by [f01938718](https://filfox.info/en/address/f01938718) are duplicate data.

⚠️ 39.73% of total deal sealed by [f01938717](https://filfox.info/en/address/f01938717) are duplicate data.

⚠️ 32.81% of total deal sealed by [f01877862](https://filfox.info/en/address/f01877862) are duplicate data.

⚠️ [f0883205](https://filfox.info/en/address/f0883205) has unknown IP location.

⚠️ [f0883201](https://filfox.info/en/address/f0883201) has unknown IP location.

⚠️ [f01169692](https://filfox.info/en/address/f01169692) has unknown IP location.

⚠️ [f01308862](https://filfox.info/en/address/f01308862) has unknown IP location.

⚠️ [f0142723](https://filfox.info/en/address/f0142723) has unknown IP location.

⚠️ [f01308863](https://filfox.info/en/address/f01308863) has unknown IP location.

⚠️ [f01308876](https://filfox.info/en/address/f01308876) has unknown IP location.

⚠️ 36.64% of total deal sealed by [f0883206](https://filfox.info/en/address/f0883206) are duplicate data.

⚠️ [f0883206](https://filfox.info/en/address/f0883206) has unknown IP location.

⚠️ [f01308857](https://filfox.info/en/address/f01308857) has unknown IP location.

⚠️ [f0142721](https://filfox.info/en/address/f0142721) has unknown IP location.

⚠️ [f01387566](https://filfox.info/en/address/f01387566) has unknown IP location.

⚠️ [f01387466](https://filfox.info/en/address/f01387466) has unknown IP location.

⚠️ 39.74% of total deal sealed by [f0807382](https://filfox.info/en/address/f0807382) are duplicate data.

⚠️ [f0807382](https://filfox.info/en/address/f0807382) has unknown IP location.

⚠️ [f01387598](https://filfox.info/en/address/f01387598) has unknown IP location.

⚠️ [f01387599](https://filfox.info/en/address/f01387599) has unknown IP location.

⚠️ [f01387459](https://filfox.info/en/address/f01387459) has unknown IP location.

⚠️ [f01308928](https://filfox.info/en/address/f01308928) has unknown IP location.

⚠️ [f01387460](https://filfox.info/en/address/f01387460) has unknown IP location.

⚠️ [f01308916](https://filfox.info/en/address/f01308916) has unknown IP location.

⚠️ 20.33% of total deal sealed by [f01387465](https://filfox.info/en/address/f01387465) are duplicate data.

⚠️ [f01387465](https://filfox.info/en/address/f01387465) has unknown IP location.

⚠️ [f0442383](https://filfox.info/en/address/f0442383) has unknown IP location.

⚠️ [f01132084](https://filfox.info/en/address/f01132084) has unknown IP location.

⚠️ [f0883203](https://filfox.info/en/address/f0883203) has unknown IP location.

⚠️ [f0883202](https://filfox.info/en/address/f0883202) has unknown IP location.

⚠️ [f01308877](https://filfox.info/en/address/f01308877) has unknown IP location.

⚠️ [f01169691](https://filfox.info/en/address/f01169691) has unknown IP location.

| Provider                                              |                           Location | Total Deals Sealed | Percentage | Unique Data | Duplicate Deals |
| :---------------------------------------------------- | ---------------------------------: | -----------------: | ---------: | ----------: | --------------: |
| [f01852325](https://filfox.info/en/address/f01852325) | Hong Kong, Central and Western, HK |         250.75 TiB |     15.60% |  160.59 TiB |          35.95% |
| [f01852664](https://filfox.info/en/address/f01852664) |           Singapore, Singapore, SG |         194.13 TiB |     12.08% |  125.38 TiB |          35.42% |
| [f01852677](https://filfox.info/en/address/f01852677) |    Morrisville, North Carolina, US |         191.66 TiB |     11.92% |  121.78 TiB |          36.46% |
| [f01851482](https://filfox.info/en/address/f01851482) |                   Busan, Busan, KR |         179.72 TiB |     11.18% |  112.75 TiB |          37.26% |
| [f01852023](https://filfox.info/en/address/f01852023) |                   Busan, Busan, KR |         165.56 TiB |     10.30% |  105.44 TiB |          36.32% |
| [f01919535](https://filfox.info/en/address/f01919535) |                   Wuhan, Hubei, CN |         149.81 TiB |      9.32% |   15.59 TiB |          89.59% |
| [f01938714](https://filfox.info/en/address/f01938714) |     Sham Shui Po, Sham Shui Po, HK |          86.88 TiB |      5.40% |   52.69 TiB |          39.35% |
| [f01938721](https://filfox.info/en/address/f01938721) | Hong Kong, Central and Western, HK |          82.41 TiB |      5.13% |   47.97 TiB |          41.79% |
| [f01938665](https://filfox.info/en/address/f01938665) |     Sham Shui Po, Sham Shui Po, HK |          82.25 TiB |      5.12% |   49.66 TiB |          39.63% |
| [f01938718](https://filfox.info/en/address/f01938718) |    Morrisville, North Carolina, US |          82.22 TiB |      5.11% |   51.94 TiB |          36.83% |
| [f01938717](https://filfox.info/en/address/f01938717) |           Singapore, Singapore, SG |          82.19 TiB |      5.11% |   49.53 TiB |          39.73% |
| [f01877862](https://filfox.info/en/address/f01877862) |                   Seoul, Seoul, KR |          15.00 TiB |      0.93% |   10.08 TiB |          32.81% |
| [f0883205](https://filfox.info/en/address/f0883205)   |                            Unknown |           4.65 TiB |      0.29% |    4.14 TiB |          10.99% |
| [f0883201](https://filfox.info/en/address/f0883201)   |                            Unknown |           4.39 TiB |      0.27% |    4.14 TiB |           5.65% |
| [f01169692](https://filfox.info/en/address/f01169692) |                            Unknown |           3.07 TiB |      0.19% |    2.82 TiB |           8.14% |
| [f01308862](https://filfox.info/en/address/f01308862) |                            Unknown |           3.00 TiB |      0.19% |    2.91 TiB |           3.12% |
| [f0142723](https://filfox.info/en/address/f0142723)   |                            Unknown |           2.64 TiB |      0.16% |    2.57 TiB |           2.95% |
| [f01308863](https://filfox.info/en/address/f01308863) |                            Unknown |           2.62 TiB |      0.16% |    2.38 TiB |           9.18% |
| [f01308876](https://filfox.info/en/address/f01308876) |                            Unknown |           2.56 TiB |      0.16% |    2.50 TiB |           2.14% |
| [f0883206](https://filfox.info/en/address/f0883206)   |                            Unknown |           2.11 TiB |      0.13% |    1.34 TiB |          36.64% |
| [f01308857](https://filfox.info/en/address/f01308857) |                            Unknown |           2.00 TiB |      0.12% |    1.97 TiB |           1.56% |
| [f0142721](https://filfox.info/en/address/f0142721)   |                            Unknown |           1.97 TiB |      0.12% |    1.80 TiB |           8.34% |
| [f01387566](https://filfox.info/en/address/f01387566) |                            Unknown |           1.77 TiB |      0.11% |    1.77 TiB |           0.00% |
| [f01387466](https://filfox.info/en/address/f01387466) |                            Unknown |           1.66 TiB |      0.10% |    1.66 TiB |           0.00% |
| [f0807382](https://filfox.info/en/address/f0807382)   |                            Unknown |           1.65 TiB |      0.10% | 1019.00 GiB |          39.74% |
| [f01387598](https://filfox.info/en/address/f01387598) |                            Unknown |           1.50 TiB |      0.09% |    1.50 TiB |           0.00% |
| [f01387599](https://filfox.info/en/address/f01387599) |                            Unknown |           1.47 TiB |      0.09% |    1.47 TiB |           0.00% |
| [f01387459](https://filfox.info/en/address/f01387459) |                            Unknown |           1.11 TiB |      0.07% |  945.00 GiB |          16.89% |
| [f01308928](https://filfox.info/en/address/f01308928) |                            Unknown |           1.05 TiB |      0.07% |  913.00 GiB |          14.91% |
| [f01387460](https://filfox.info/en/address/f01387460) |                            Unknown |        1016.03 GiB |      0.06% |  840.01 GiB |          17.32% |
| [f01308916](https://filfox.info/en/address/f01308916) |                            Unknown |         956.00 GiB |      0.06% |  956.00 GiB |           0.00% |
| [f01387465](https://filfox.info/en/address/f01387465) |                            Unknown |         944.25 GiB |      0.06% |  752.25 GiB |          20.33% |
| [f0442383](https://filfox.info/en/address/f0442383)   |                            Unknown |         937.57 GiB |      0.06% |  936.57 GiB |           0.11% |
| [f01132084](https://filfox.info/en/address/f01132084) |                            Unknown |         755.50 GiB |      0.05% |  755.50 GiB |           0.00% |
| [f0883203](https://filfox.info/en/address/f0883203)   |                            Unknown |         529.25 GiB |      0.03% |  465.25 GiB |          12.09% |
| [f0883202](https://filfox.info/en/address/f0883202)   |                            Unknown |         420.03 GiB |      0.03% |  378.03 GiB |          10.00% |
| [f01308877](https://filfox.info/en/address/f01308877) |                            Unknown |         336.02 GiB |      0.02% |  336.02 GiB |           0.00% |
| [f01169691](https://filfox.info/en/address/f01169691) |                            Unknown |          24.72 GiB |      0.00% |   24.72 GiB |           0.00% |

![Provider Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/66/1671092111453.png)
### Deal Data Replication
The below table shows how each many unique data are replicated across storage providers.
- No more than 25% of unique data are stored with less than 4 providers.

⚠️ 89.97% of deals are for data replicated across less than 4 storage providers.

| Unique Data Size | Total Deals Made | Number of Providers | Deal Percentage |
| ---------------: | ---------------: | ------------------: | --------------: |
|       254.74 TiB |       543.11 TiB |                   1 |          33.78% |
|       123.90 TiB |       442.56 TiB |                   2 |          27.53% |
|       103.22 TiB |       460.64 TiB |                   3 |          28.65% |
|        31.23 TiB |       153.88 TiB |                   4 |           9.57% |
|         1.47 TiB |         7.38 TiB |                   5 |           0.46% |

![Replication Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/66/1671092112675.png)
### Deal Data Shared with other Clients
The below table shows how many unique data are shared with other clients.
Usually different applications owns different data and should not resolve to the same CID.

⚠️ CID sharing has been observed.

| Other Client                                                                                                                                                                                                              | Application                                                                                                                    | Total Deals Affected | Unique CIDs |        Verifier |
| :------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ | :----------------------------------------------------------------------------------------------------------------------------- | -------------------: | ----------: | --------------: |
| [f3w4wlayytfmsay6gu5phhij5r4yyx7t4xxrlosgo<br/>tlmqg5eih3co5atsra4h2pe4qd2d6c76bvhj6nwim<br/>7lgq](https://filfox.info/en/address/f3w4wlayytfmsay6gu5phhij5r4yyx7t4xxrlosgotlmqg5eih3co5atsra4h2pe4qd2d6c76bvhj6nwim7lgq) | [GMWBR INC](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/73)                                        |           152.73 TiB |       2,174 | LDN v3 multisig |
| [f3xffjctbyy7zigopfa3za5ha3pvv4z3xfghlw7kw<br/>vyeuabkg4lzsgfwhnghwkvmmvi6yso6k52hq3ca6c<br/>kveq](https://filfox.info/en/address/f3xffjctbyy7zigopfa3za5ha3pvv4z3xfghlw7kwvyeuabkg4lzsgfwhnghwkvmmvi6yso6k52hq3ca6ckveq) | [Chengdu Digital Media Industry Base Co\., Ltd\.](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/387) |           149.69 TiB |       1,929 | LDN v3 multisig |
| [f1pediuk4kncwp4qxawlope7hzfmd2ran35w54o7y](https://filfox.info/en/address/f1pediuk4kncwp4qxawlope7hzfmd2ran35w54o7y)                                                                                                     | [Qistone Information technology](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/324)                  |           106.69 TiB |       1,606 | LDN v3 multisig |
| [f14uxcyaoab3qhn42kaquqysga6f6zfry3x4nk3ca](https://filfox.info/en/address/f14uxcyaoab3qhn42kaquqysga6f6zfry3x4nk3ca)                                                                                                     | [ China Tianying INC\.](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/426)                           |           100.31 TiB |       2,022 | LDN v3 multisig |
| [f1piaz4nodpwdemrfqak5jlfg5ois2onzmjv6fkki](https://filfox.info/en/address/f1piaz4nodpwdemrfqak5jlfg5ois2onzmjv6fkki)                                                                                                     | [Chengdu Yundianshang Technology Co\., LTD](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/399)       |            86.41 TiB |       1,464 | LDN v3 multisig |
| [f1cuboogcwais57dljrpeltoy6ja2itb7wvwmrl3q](https://filfox.info/en/address/f1cuboogcwais57dljrpeltoy6ja2itb7wvwmrl3q)                                                                                                     | [Penglaiju](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/400)                                       |            86.13 TiB |       1,370 | LDN v3 multisig |
| [f1tgii4xgcp6um4n2w7eqaw6bwvnvyii2u7cjgzka](https://filfox.info/en/address/f1tgii4xgcp6um4n2w7eqaw6bwvnvyii2u7cjgzka)                                                                                                     | [Meson\.Network ](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/187)                                 |            58.72 TiB |         300 | LDN v3 multisig |
| [f3uils5cdx3ezyzszjjfnulugknbdsanmqtisd7x7<br/>xkfcljdnshp4jspnrgxpldt5b4aafuz4q4rkebpjy<br/>keha](https://filfox.info/en/address/f3uils5cdx3ezyzszjjfnulugknbdsanmqtisd7x7xkfcljdnshp4jspnrgxpldt5b4aafuz4q4rkebpjykeha) | [Qingyun Education Fund](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/31)                           |            48.81 TiB |         930 | LDN v3 multisig |
| [f3q7ablez3jqkcjukwbzaql7lmbx4ldouu66nexpd<br/>cfvu6kgho3v6gricckt77cgr46tdre2l4zmvha7bs<br/>u7qq](https://filfox.info/en/address/f3q7ablez3jqkcjukwbzaql7lmbx4ldouu66nexpdcfvu6kgho3v6gricckt77cgr46tdre2l4zmvha7bsu7qq) | `MatrixStorage`                                                                                                                |            19.55 TiB |         357 |        LDN # 72 |
| [f3woqxpu6ekmj43nmpcv7j2pgu6lejxtzgxpzl6f2<br/>vrueoqlzjntakyhdkghymyffbzfbsio6dvfmy643x<br/>4y7q](https://filfox.info/en/address/f3woqxpu6ekmj43nmpcv7j2pgu6lejxtzgxpzl6f2vrueoqlzjntakyhdkghymyffbzfbsio6dvfmy643x4y7q) | [RICH ST PETE LLC](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/64)                                 |            14.06 TiB |         228 | LDN v3 multisig |
| [f3q3eysweh273pwygu27yllyafljznqewpxwlrc7j<br/>daugrpvhmrcnxmkn43wkctxalcg3z42zxas2hinsf<br/>tgva](https://filfox.info/en/address/f3q3eysweh273pwygu27yllyafljznqewpxwlrc7jdaugrpvhmrcnxmkn43wkctxalcg3z42zxas2hinsftgva) | [Beijing Yibo Technology Co\., Ltd\.](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/74)              |             6.83 TiB |          90 |        LDN # 74 |
| [f1elncewt3sh356aop52uvcappblxmf6asbmhxlya](https://filfox.info/en/address/f1elncewt3sh356aop52uvcappblxmf6asbmhxlya)                                                                                                     | [Beijing Wanjie Data Technology Co\., LTD](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/404)        |             4.81 TiB |          86 | LDN v3 multisig |
| [f3skkellc7wegakh2blqeu4kkrlzuqy2siymwli7s<br/>ec6eq77c2v4kzgz5ozgnasjl5r52ckameba5kds7h<br/>djda](https://filfox.info/en/address/f3skkellc7wegakh2blqeu4kkrlzuqy2siymwli7sec6eq77c2v4kzgz5ozgnasjl5r52ckameba5kds7hdjda) | [Meizhai Technology](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/75)                               |             3.00 TiB |          47 | LDN v3 multisig |
| [f1h24uonqrkruvcrgp5bhehenvejn3u5d24stmrsa](https://filfox.info/en/address/f1h24uonqrkruvcrgp5bhehenvejn3u5d24stmrsa)                                                                                                     | [Unicom](https://github.com/filecoin-project/filecoin-plus-client-onboarding/issues/1898)                                      |             2.66 TiB |          38 |        Eric Liu |
| [f1budai5eqmk7zjfd54bmnkj72vuc7jykmkkttgha](https://filfox.info/en/address/f1budai5eqmk7zjfd54bmnkj72vuc7jykmkkttgha)                                                                                                     | ``                                                                                                                             |           544.00 GiB |           4 |        LDN # 64 |
| [f14nyld75bnvr2y3ca4ew7vxmwp4tuwytqwggthcy](https://filfox.info/en/address/f14nyld75bnvr2y3ca4ew7vxmwp4tuwytqwggthcy)                                                                                                     | `Kimoc`                                                                                                                        |           224.00 GiB |           5 | LDN v3 multisig |
| [f17tvb3ejs3ev6owqmkpzomtewgrd6v2sofv7upma](https://filfox.info/en/address/f17tvb3ejs3ev6owqmkpzomtewgrd6v2sofv7upma)                                                                                                     | [Beijing Lexun Technology Co\., LTD](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/395)              |            96.00 GiB |           2 | LDN v3 multisig |
| [f1iach3ih3q5x5k4lxy6wlysmqm65vwegpxwm4oii](https://filfox.info/en/address/f1iach3ih3q5x5k4lxy6wlysmqm65vwegpxwm4oii)                                                                                                     | [Friday Shopping](https://github.com/filecoin-project/filecoin-plus-client-onboarding/issues/2019)                             |            64.00 GiB |           2 |        Eric Liu |
| [f3wydt7oy6yg2szd5m53zj4kjwsee6xviboxge2zd<br/>g7hxgglaf4azoau3vlfconj2ocpvmlwk4ityr36hn<br/>dana](https://filfox.info/en/address/f3wydt7oy6yg2szd5m53zj4kjwsee6xviboxge2zdg7hxgglaf4azoau3vlfconj2ocpvmlwk4ityr36hndana) | [北京中经天平科技有限公司](https://github.com/filecoin-project/filecoin-plus-client-onboarding/issues/516)                                 |            32.00 GiB |           1 |          Neo Ge |

[^1]: To manually trigger this report, add a comment with text `checker:manualTrigger`

**Comment by lvschouwen** [comment]
checker:manualTrigger
