### ISSUE TITLE
[DataCap Application] <Jierun software design (Shenzhen) Co., Ltd> - <Zhitiao>

### ISSUE THREAD

**Issue by liangyu09** [filecoin-project/filecoin-plus-large-datasets#662]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name:Jierun software design (Shenzhen) Co., Ltd
- Website / Social Media:Recently, our company will change the domain name and renovate the official website. At present, the new official website has not been launched. We can provide business licenses or even more to prove that we have been established for 6 years.
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):3PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):100TiB
- On-chain address for first allocation:f1p6dqkhlauq2sxqop7wjyglhzlggvpfy7icehd2y

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Jierun technology is a leading software design company in the industry. In the fields of artificial intelligence, big data, blockchain, Im and instant messaging, the company has rich practical development experience. The company strives for excellence and works steadily to provide customers with high-quality software product design and development services, CRM / ERP enterprise product management platform, customized development solutions, etc
```

What is the primary source of funding for this project?
```
Self owned funds of the company
```

What other projects/ecosystem stakeholders is this project associated with?
```
The company is self operated and has no other stakeholders
```

## Use-case details

Describe the data being stored onto Filecoin
```
The data stored on the filecoin network are mainly pictures, audio and video of the chat software system, a large amount of data of the financial system, audio and video of the company's internal meeting minutes, and audio and video materials of internal training of employees.
```

Where was the data in this dataset sourced from?
```
A large amount of data will be generated during the daily operation of the company and the use of the software system
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://drive.google.com/drive/folders/1_1lJB9c_YiV_I7FvQcj2yEDP-jZ3VaUO?usp=sharing
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Confirm
```

What is the expected retrieval frequency for this data?
```
There is no fixed frequency. About 3 searches per quarter
```

For how long do you plan to keep this dataset stored on Filecoin?
```
About 1 year
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Hong Kong and Singapore
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Our data is relatively large. We use offline transmission
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We plan to store data in multiple SPS to improve data stability and security
```

How will you be distributing deals across storage providers?
```
Distribute as fairly and impartially as possible
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes,and I will keep track of the latest trends in the Filecoin community
```

**Comment by liangyu09** [comment]
@galen-mcandrew Hello, when will my project be reviewed

**Comment by Sunnyiscoming** [comment]
Is your organization name 捷润软件设计(深圳)有限公司?Can you provide more information about organization? What's the relationship between you and organization?

The data samples you provided includes video generate from 北京七月在线科技有限公司. Can you explain about that?
Can you elaborate on the data composition and source of 3.5P and provide enough data samples from your business, pictures, audio and video of the chat software system, a large amount of data of the financial system, audio and video of the company's internal meeting minutes, and audio and video materials of internal training of employees.?

Could you tell us more about your company's project and your partner, and you can share more materials.

Can you provide more detailed information about other storage providers participated in this program, such as you can list SPs you have contacted with at present?

**Comment by liangyu09** [comment]
1、Yes, my organization name is 捷润软件设计(深圳)有限公司. I can provide you with the company's business license and my ID card information. I am the corporate legal person of the company.
2、The video is a video material for employees to conduct internal training and learning. Our company paid for their online courses and has the right to use them within the company.
3、In addition to some relatively private data of the financial system, I can provide them. Was it sent to your mailbox?
4、There are many partners of the company. What impresses me deeply is that the public chain project of Ethereum layer 2 network last year has been launched in larger exchanges and achieved great success. I can provide you with relevant information.
5、The global storage providers  we have contacted include those from Singapore, the United States, Taiwan, China, and Vietnam. The better contact SPID is f01360268
f01543586
Others are still in further communication.

**Comment by Sunnyiscoming** [comment]
Large datasets stored in Filecoin require full rights of the data, which is fully public when uploaded to Filecoin. I think that it will damage the rights and interests of Beijing July Online Technology Co., Ltd. to some extent. I hope you can get their authorization and send the relevant information to the community.

**Comment by liangyu09** [comment]
> 



> Large datasets stored in Filecoin require full rights of the data, which is fully public when uploaded to Filecoin. I think that it will damage the rights and interests of Beijing July Online Technology Co., Ltd. to some extent. I hope you can get their authorization and send the relevant information to the community.

I have deleted the videos involving infringement, and the large-scale data uploaded to filecoin in the future will also ensure that there is no infringement data involving other companies

**Comment by liangyu09** [comment]
@Sunnyiscoming Hello, have you read my answer

**Comment by liangyu09** [comment]
@galen-mcandrew Hello, When can I get your response to the information I submitted

**Comment by Sunnyiscoming** [comment]
How much data do you have after deleting these data?
Can you explain the composition of the data?
Please share more data samples here for more people will check it and these data are open.

**Comment by liangyu09** [comment]
> How much data do you have after deleting these data?
> Can you explain the composition of the data?
> Please share more data samples here for more people will check it and these data are open.

We have been established for 6 years, among which we lost a lot of data because the data was not well kept, but now we have 1p of data that can be publicly stored on the filecoin network. These data are mainly generated in the process of our customer service, from our design, construction, after-sales, and of course, also include our company's content meeting records, annual meeting videos, group building pictures, and so on. The following is our new data case, please check。

https://drive.google.com/drive/folders/1_1lJB9c_YiV_I7FvQcj2yEDP-jZ3VaUO?usp=sharing

**Comment by Sunnyiscoming** [comment]
![image](https://user-images.githubusercontent.com/105098820/191644982-f60258bc-b5d0-4702-abf0-9ab3e3d8ee27.png)
The last two data samples are some data related with BINANCE, which is not the type of stored data you pointed out.
The other data samples are just some png., which can not prove you have 1pb data.

**Comment by liangyu09** [comment]
Thank you very much, because my company has been established for more than 6 years, has developed many systems, and has many business lines. As I replied to you before, some data are indeed difficult to disclose because of customer and privacy issues, and some systems need to rely on I also provided you with the data of the third-party company, but of course this does not meet the requirements.

I recently rearranged new data samples to demonstrate that our company has a huge amount of data to store. Here is the link:
Part of the company's internal information that can be made public: https://drive.google.com/drive/folders/1_1lJB9c_YiV_I7FvQcj2yEDP-jZ3VaUO?usp=sharing
Some video NFTs: https://testnets.opensea.io/collection/jierunmeta

If more is needed, I can still provide other data that can be exposed to the web. In addition, our company has updated the official website, the link is as follows: http://www.jierunsoftware.top

**Comment by Sunnyiscoming** [comment]
Some data are indeed difficult to disclose because of customer and privacy issues.
If most of these data are private, I suggest you pay attention to the FIL-E project.

![image](https://user-images.githubusercontent.com/105098820/192953987-495eb826-ab34-4adb-bc20-a03112a21ba4.png)
The NFT is not valid when clicked.
![image](https://user-images.githubusercontent.com/105098820/192954108-48fd9b3a-4868-4c69-b309-be7391801205.png)
Can you explain the data source of these MOV files?

**Comment by liangyu09** [comment]
> https://testnets.opensea.io/collection/jierunmeta



> Some data are indeed difficult to disclose because of customer and privacy issues. If most of these data are private, I suggest you pay attention to the FIL-E project.
> 
> ![image](https://user-images.githubusercontent.com/105098820/192953987-495eb826-ab34-4adb-bc20-a03112a21ba4.png) The NFT is not valid when clicked. ![image](https://user-images.githubusercontent.com/105098820/192954108-48fd9b3a-4868-4c69-b309-be7391801205.png) Can you explain the data source of these MOV files?

1. There is also a large amount of data that we can disclose;
2. The "NFT" of the website is now clickable;
3、These MOVs are modern urban cyberpunk-themed NFTs launched by Jierun Software。

**Comment by Sunnyiscoming** [comment]
1. What are the types and total amounts of the massive data you mentioned that can be disclosed? Please provide enough data samples of each type separately.
2. I can know the business situation of your company through the website. Whether the NFT has been seld in the market, and how to prove that these NFTs created by your company?

**Comment by liangyu09** [comment]
The data that our company can disclose mainly includes the following categories. Part of it is the company's team building, meetings, and promotional videos and pictures. This part has more every quarter. I have already uploaded some data samples of this type to Google Cloud Drive.
	There is another part of NFT. The NFT we made has been uploaded to opensea. On the one hand, it is to show our customers the case of NFT; the current market for NFT is not good, so we have not invested too much resources and energy in market sales, but we will definitely promote sales in the future. Regarding NFTs, we have image NFTs and video NFTs. There are dozens of Gs that have been officially launched, and we will continue to add new content.
	Since I have been applying for so long and you have not officially approved it, I think it may be that my data volume is not large enough, so the total amount of my application has been reduced from 5PiB to 2.5PiB. I sincerely hope that you can pass it. Thank you very much. !

Google Cloud Drive：https://drive.google.com/drive/folders/1_1lJB9c_YiV_I7FvQcj2yEDP-jZ3VaUO?usp=sharing
NFT：
https://opensea.io/zh-CN/account?tab=created
my wallet addres：0xBB33a482500687eFC6D6a19815E03A2E7ff2effd

<img width="1387" alt="image" src="https://user-images.githubusercontent.com/16492019/195052532-d039b37e-fd55-4843-aecd-f3e04ddfecf7.png">

**Comment by Sunnyiscoming** [comment]
> https://opensea.io/JierunSoftware
> There are dozens of Gs that have been officially launched.
> Part of it is the company's team building, meetings, and promotional videos and pictures. 

According to your description, it seems that you will store the above two kinds of data. May I ask how much is the total amount of your original data? Neither seems to have significant data storage requirements, and it is recommended that you request Datacap from notaries directly.

**Comment by Sunnyiscoming** [comment]
Close for no reply. You can open another new application if you want to continue.
