### ISSUE TITLE
[DataCap Application] Elizabeth beauty

### ISSUE THREAD

**Issue by DorisJacksonoa** [filecoin-project/filecoin-plus-large-datasets#669]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Shantou Elizabeth Beauty Co., Ltd
- Website / Social Media:www.sunjiedoctor.com
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):5 PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):100 TiB
- On-chain address for first allocation:f1bfo5fcwfbadcwnn4xuac56dybyguow25qu3df2y

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Founded in the 1980s, Elizabeth beauty management group is the first and only comprehensive large-scale beauty enterprise in Guangdong, China, which integrates plastic surgery, beauty regimen and beauty training. The group has successively reached cooperation with counterparts in the United States, France, Japan, South Korea and other countries, and gathered top talents in various fields at home and abroad. After 26 years of development, it now has 13 secondary subsidiaries, distributed in 5 provinces and 7 cities in China.
Shantou Elizabeth beauty and health care (chain) -- positioned as an international, elegant and comfortable private beauty hall, it has always been the first brand in East Guangdong. There are 6 branches in Shantou City, Chaonan District, Puning City and other central locations, striving to create the first brand of "supreme sincerity" in the beauty industry.
```

What is the primary source of funding for this project?
```
Own funds.
```

What other projects/ecosystem stakeholders is this project associated with?
```
Only related to ourselves.
```

## Use-case details

Describe the data being stored onto Filecoin
```
We are an internet medical beauty agency. The company has accumulated a large number of videos and project introductions of real surgical cases of users, which are important publicity materials of the company.
```

Where was the data in this dataset sourced from?
```
The staff of the company will take photos and collect them.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://drive.google.com/drive/folders/1VG6SHtitqZDiuH-LFeju5-TZyNgON9ox?usp=sharing
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes, we confirm.
```

What is the expected retrieval frequency for this data?
```
Twice a year.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
If possible, we hope it is permanent storage.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
we hope in China.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Yes, we will choose Offline transfer.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
My partner knows filecoin very well and recommended filecoin to me. We will choose a storage supplier with strength and experience.
```

How will you be distributing deals across storage providers?
```
We will understand whether the storage suppliers have relevant experience and sustainability, and reasonably allocate them to different storage suppliers according to the analysis.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, we have enough funds to complete the transaction. We hope to receive your reply as soon as possible.
```

**Comment by jessie8o8** [comment]
Hi @DorisJacksonoa! 2 flags

I understand that your company is "first and only comprehensive large-scale beauty enterprise in Guangdong, China" with 26 years of development. Please explain the lack of content on your site. 

Your sitemap only has 2 links (many buttons on the homepage leading to the same thing)
![image](https://user-images.githubusercontent.com/90115194/186539325-fd8f1d46-321d-4e51-8abf-315d789107c8.png)

Your customer support number and email is non-existent
![image](https://user-images.githubusercontent.com/90115194/186539399-10ffdb88-1ebc-4d52-beb1-5e8ad339692a.png)

Let me know if I'm missing something :)

**Comment by DorisJacksonoa** [comment]
你好，我们是一家整形医院，是通过手术来帮助我们的客户变得更美更自信。我们的客户主要是我们的代理商找来的，所以我们线上广告和内容并不多。但是我们医院和代理商的广告素材非常多，这些素材我们一般都是针对性的发给意向客户。

**Comment by DorisJacksonoa** [comment]
> Hi @DorisJacksonoa! 2 flags
> 
> I understand that your company is "first and only comprehensive large-scale beauty enterprise in Guangdong, China" with 26 years of development. Please explain the lack of content on your site.
> 
> Your sitemap only has 2 links (many buttons on the homepage leading to the same thing) ![image](https://user-images.githubusercontent.com/90115194/186539325-fd8f1d46-321d-4e51-8abf-315d789107c8.png)
> 
> Your customer support number and email is non-existent ![image](https://user-images.githubusercontent.com/90115194/186539399-10ffdb88-1ebc-4d52-beb1-5e8ad339692a.png)
> 
> Let me know if I'm missing something :)

Hello, we are a plastic surgery hospital, which helps our customers become more beautiful and confident through surgery. Our customers are mainly found by our agents, so we do not have many online advertisements and content, but our hospitals and agents have a lot of advertising materials.

**Comment by Sunnyiscoming** [comment]
Customer data in the medical beauty industry should be extremely private. I think it is reasonable to publish a small number of user cases, but the disclosure of as much as 5PB of customer information is not a good signal, which seems to violate user privacy. Otherwise, I did not find enough data samples similar to promotional videos in the data samples you provided or on the website.
Can you provide more detailed information about other storage providers participated in this program, such as you can list SPs you have contacted with at present?

**Comment by Sunnyiscoming** [comment]
Any update here? @DorisJacksonoa

**Comment by raghavrmadya** [comment]
No reply
