### ISSUE TITLE
[DataCap Application] Chengdu White Rabbit Culture Communication Co.

### ISSUE THREAD

**Issue by baituchuanmei** [filecoin-project/filecoin-plus-large-datasets#694]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Chengdu White Rabbit Culture Communication Co.
- Website / Social Media:http://www.baitugroup.com/index.html
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):2 PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):100TiB
- On-chain address for first allocation: f1d5dtppu4xbrwop5pblraps4kpcuej66jg7kre5y

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
The company was established in 2017, with "Reddit Economy + Brand Empowerment" as its core. In 2020, the company successfully completed the promotion of new products such as "Enzyme", "Mistine" and "Mistine". "We are committed to providing professional integrated marketing services for all brands.
```

What is the primary source of funding for this project?
```
Sales share of live lead generation
```

What other projects/ecosystem stakeholders is this project associated with?
```
no
```

## Use-case details

Describe the data being stored onto Filecoin
```
Our live video and recorded mini-video
```

Where was the data in this dataset sourced from?
```
Daily shooting from the company
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://drive.google.com/drive/folders/1YjX4QCMpza5c1lQ1cKeiLyTrjhsPtqB8?usp=sharing
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
yes
```

What is the expected retrieval frequency for this data?
```
Just for backup, not necessarily used
```

For how long do you plan to keep this dataset stored on Filecoin?
```
I certainly hope it is permanent, but it does not matter if it is not permanent
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Greater China
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Offline, not online, because the volume is too large
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
Choose our local miners
```

How will you be distributing deals across storage providers?
```
Try to share equally
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, we are ready to go. Hoping to be more open
```

**Comment by raghavrmadya** [comment]
Insufficient data samples. Please provide enough samples to support your claims in a new applications
