### ISSUE TITLE
[DataCap Application] <EVOCOM> - <Cross-chain Metaverse Social Platform>

### ISSUE THREAD

**Issue by cdcdx** [filecoin-project/filecoin-plus-large-datasets#696]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: EVOCOM
- Website / Social Media: https://www.e-vo.io
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 2PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 50TiB
- On-chain address for first allocation: f1upoqjjco3fyt2g3j35hhn2zdfak32jqavwbtyvi

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
We believe that blockchain and social networking must be indispensable in metaverse ecosystem, and our goal is to provide users with a highly open world, and enable them to participate in various ways through cross platform technology. To give users a highly immersive experience, Evocom avatars will correspond to a specific occupation, so as to gather groups with the same hobbies, skills and resources. Keep in mind this happens cross-chain, which means a larger user base, and all these together will make Evocom one of the coolest and most active communities!
Digital lands in Evocom are permanently owned by relevant community members. Lands are mainly divided into two categories: commercial and residential. As an important means of production, users can arrange various economic activities with lands, and new NFTs may be generated. For instance, houses built can purchased or rent for highly customized business activities, or as own private space to carry out meet-ups.
Based on the closed-loop of production-construction-consumption, development team will help to build economic system in early stage, and also work with community to build a complete set of economic ecosystem and maintain the development. While and after the formation of economic system, avatar NFTs will play key role in the world of Evocom.
```

What is the primary source of funding for this project?
```
ourselves
```

What other projects/ecosystem stakeholders is this project associated with?
```
No
```

## Use-case details

Describe the data being stored onto Filecoin
```
video,pictures,data,logfile
```

Where was the data in this dataset sourced from?
```
Own Servers. 
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://www.e-vo.io/data/EVOCOM_BP.pdf
https://www.youtube.com/watch?v=Z_ARNZAVEWg
https://www.youtube.com/watch?v=JUPyNYYQ5fo
https://www.youtube.com/watch?v=5tg_THnz0zA
https://drive.google.com/file/d/1mYJ6tEaceeqC7eZrgamVdBMM7jdMdDHf/view?usp=sharing
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes.
```

What is the expected retrieval frequency for this data?
```
4-6 times a year.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
Most of data is required to stored permanently. 
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Asia.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
We plan to transfer data offline。
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We're selecting the SPs with high reputation on slack  . They have the ability to store deals at a very fast pace and a high success rate.
```

How will you be distributing deals across storage providers?
```
We plan to find more than 5 SPs and distribute the deals equally.
It is planned to package 70% in Hong Kong, 30% in other regions. Now we have contacted f01885111. Other service providers in contact have no ID for the time being
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
We are contacting SPs and don't need community help at this time.
```

**Comment by raghavrmadya** [comment]
What's your relationship as the applicant with EVOCOM?

**Comment by cdcdx** [comment]
> What's your relationship as the applicant with EVOCOM?

Thanks for the reply, I am the developer of the EVOCOM project.

**Comment by Sunnyiscoming** [comment]
Can you provide more data samples to prove that you have 5 PB data already?How many copies will you store?
Can you provide more detailed information about other storage providers participated in this program, such as you can list SPs you have contacted with at present?
Could you send an email to filplus-app-review@fil.org with your official domain in order to confirm your identity? Email name should includes the issue id #696.

**Comment by Sunnyiscoming** [comment]
![image](https://user-images.githubusercontent.com/105098820/188584763-e20750b9-bfad-4e80-97fa-affb6ef6ab8f.png)

**Comment by cdcdx** [comment]
> Can you provide more data samples to prove that you have 5 PB data already?How many copies will you store? Can you provide more detailed information about other storage providers participated in this program, such as you can list SPs you have contacted with at present? Could you send an email to [filplus-app-review@fil.org](mailto:filplus-app-review@fil.org) with your official domain in order to confirm your identity? Email name should includes the issue id #696.

Email sent from admin@e-vo.io

**Comment by Sunnyiscoming** [comment]
Can you provide more data samples to prove that you have 5 PB data already?How many copies will you store?

**Comment by cdcdx** [comment]
> Can you provide more data samples to prove that you have 5 PB data already?How many copies will you store?

https://www.e-vo.io/data/EVOCOM_BP.pdf
https://www.youtube.com/watch?v=Z_ARNZAVEWg
https://www.youtube.com/watch?v=JUPyNYYQ5fo
https://www.youtube.com/watch?v=5tg_THnz0zA
https://drive.google.com/file/d/1mYJ6tEaceeqC7eZrgamVdBMM7jdMdDHf/view?usp=sharing

These video data are samples, which are placed on youtube for convenience.
These are all files related to this project, I can upload more if needed.
For safety data at least 3 backups.

**Comment by cdcdx** [comment]
> ![image](https://user-images.githubusercontent.com/105098820/188584763-e20750b9-bfad-4e80-97fa-affb6ef6ab8f.png)

Since we are asia users, Twitter has blocked our account, and we are currently applying for unblocking.

**Comment by Sunnyiscoming** [comment]
This project will be launched soon, and all data generated in the future will be stored in the FIL project.
Large dataset is applied for existing dataset not for dataset in the future.
How many data do you have at present? Can you describe the composition of 5 PB data? Please provide several data samples for each component data type.

**Comment by Sunnyiscoming** [comment]
I have not received the verification email from [admin@e-vo.io](mailto:admin@e-vo.io)
Email name should includes the issue id https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/696.
Can you send to [filplus-app-review@fil.org](mailto:filplus-app-review@fil.org) one more time?

**Comment by cdcdx** [comment]
> I have not received the verification email from [admin@e-vo.io](mailto:admin@e-vo.io) Email name should includes the issue id #696. Can you send to [filplus-app-review@fil.org](mailto:filplus-app-review@fil.org) one more time?

# sql
![image](https://user-images.githubusercontent.com/43960231/190296728-362b432d-bdbf-487e-8525-689bf79c344b.png)
This is the database file of the project, which is large and can only provide screenshots, not table information.

# video
https://drive.google.com/file/d/126TByOxlz_ZH52zbiyF2djgWaERvNS88/view?usp=sharing
https://drive.google.com/file/d/1UmsFW74Xje_P76FjgBlDHoYH3on2qWLs/view?usp=sharing

# file
https://drive.google.com/file/d/14VMDG9fAGRZNM88HOxKvR9ZcdFqTgw7F/view?usp=sharing
https://drive.google.com/file/d/15gsp_fYj1di5Ihhgl588IQKRZy9GMZ49/view?usp=sharing
https://drive.google.com/file/d/1HTbjs77MZogiGEIKmWtwU-ldQnVtV5bd/view?usp=sharing

**Comment by cdcdx** [comment]
> This project will be launched soon, and all data generated in the future will be stored in the FIL project. Large dataset is applied for existing dataset not for dataset in the future. How many data do you have at present? Can you describe the composition of 5 PB data? Please provide several data samples for each component data type.

The project is currently in the testing stage, and the data is not that large. The test data is estimated to be 1P, and a large amount of data will come in when it is officially launched.

**Comment by Sunnyiscoming** [comment]
Can you describe the composition of 5 PB data?

**Comment by cdcdx** [comment]
> Can you describe the composition of 5 PB data?

In evocom, we provide a large amount of UGC content, which is created by users to enrich the metaverse content such as:
Users can design costumes for in-game characters, and submit corresponding model files to the server for purchase and use by other users;
Users can carry out secondary development on the basis of the game editor we provide, adding a lot of additional gameplay or content to the Metaverse;
Users can use their own virtual characters to broadcast live in the metaverse world, and the live broadcast process will be stored on the server and provide playback functions;
Users with land NFTs can build their own houses, and the furniture in the houses is also part of the UGC content. Users with home improvement design permissions can design furniture, decorations, and home appliances, and submit corresponding models and animation files to store on the server. for purchase and use by other users;
Users with role customization rights can store their own character body shape and face shape data to the server for other users to purchase and use;
The user interaction content generated in the game will also be stored in different forms for rolling back and solving problems during the operation process, including but not limited to: user movement, chat, construction, work, transactions and other interactive behaviors;

**Comment by raghavrmadya** [comment]
You previously submitted this application which was closed for no response. Can you explain the relationship b/w this application and prev app - https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/436 ?

**Comment by cdcdx** [comment]
> You previously submitted this application which was closed for no response. Can you explain the relationship b/w this application and prev app - #436 ?

The company has been engaged in the blockchain business and has many projects, Envato is a project 2 years ago, and EVO is a current project.

**Comment by cdcdx** [comment]
> You previously submitted this application which was closed for no response. Can you explain the relationship b/w this application and prev app - #436 ?

#436 is because it was too slow to wait for a reply, and I forgot after waiting. It was closed when I found out, so I re-applied for the current project.

**Comment by raghavrmadya** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 2PiB

**Expected weekly DataCap usage rate**

> 50TiB

**Client address**

>f1upoqjjco3fyt2g3j35hhn2zdfak32jqavwbtyvi

**Comment by kernelogic** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb6cek4vxz72r5qkjdrcy5mq2rdizvzgowtjfo6rft25nijb3nzwo 
#### Address 
> f1upoqjjco3fyt2g3j35hhn2zdfak32jqavwbtyvi
#### Datacap Allocated
> 25.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb6cek4vxz72r5qkjdrcy5mq2rdizvzgowtjfo6rft25nijb3nzwo

**Comment by psh0691** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb7cb22w6gg5zajsimqsqmxbnzxsutnfbvknhbav3v37dbztqwgny 
#### Address 
> f1upoqjjco3fyt2g3j35hhn2zdfak32jqavwbtyvi
#### Datacap Allocated
> 25.00TiB
#### Signer Address
> f1qdko4jg25vo35qmyvcrw4ak4fmuu3f5rif2kc7i
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb7cb22w6gg5zajsimqsqmxbnzxsutnfbvknhbav3v37dbztqwgny

**Comment by BigD-Exchange** [comment]
@cdcdx Hi! Great to see you have gotten approval for DataCap. If you are looking for storage providers to store these data or have any questions, please visit #bigdata-exchange on Filecoin Slack or reply here. 

We have strong demand from a diverse group of SPs, who are actively looking to onboard more data.

**Comment by filplus-checker** [comment]
## DataCap and CID Checker Report[^1]
 - Organization: `EVOCOM`
 - Client: `f1upoqjjco3fyt2g3j35hhn2zdfak32jqavwbtyvi`
### Storage Provider Distribution
The below table shows the distribution of storage providers that have stored data for this client.

If this is the first time a provider takes verified deal, it will be marked as `new`.

For most of the datacap application, below restrictions should apply.
 - Storage provider should not exceed 25% of total datacap.
 - Storage provider should not be storing duplicate data for more than 20%.
 - Storage provider should have published its public IP address.
 - All storage providers should be located in different regions.

⚠️ [f01926635](https://filfox.info/en/address/f01926635) has sealed 100.00% of total datacap.

⚠️ All storage providers are located in the same region.

| Provider                                              |                           Location | Total Deals Sealed | Percentage | Unique Data | Duplicate Deals |
| :---------------------------------------------------- | ---------------------------------: | -----------------: | ---------: | ----------: | --------------: |
| [f01926635](https://filfox.info/en/address/f01926635) | Hong Kong, Central and Western, HK |          16.00 GiB |    100.00% |   16.00 GiB |           0.00% |

![Provider Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/696/1671097644346.png)
### Deal Data Replication
The below table shows how each many unique data are replicated across storage providers.
- No more than 25% of unique data are stored with less than 4 providers.

⚠️ 100.00% of deals are for data replicated across less than 4 storage providers.

| Unique Data Size | Total Deals Made | Number of Providers | Deal Percentage |
| ---------------: | ---------------: | ------------------: | --------------: |
|        16.00 GiB |        16.00 GiB |                   1 |         100.00% |

![Replication Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/696/1671097645068.png)
### Deal Data Shared with other Clients
The below table shows how many unique data are shared with other clients.
Usually different applications owns different data and should not resolve to the same CID.

✔️ No CID sharing has been observed.

[^1]: To manually trigger this report, add a comment with text `checker:manualTrigger`

**Comment by cdcdx** [comment]
> ## DataCap and CID Checker Report[1](#user-content-fn-1-34fabd5ab515de90e5508effd539cd40)
> * Organization: `EVOCOM`
> * Client: `f1upoqjjco3fyt2g3j35hhn2zdfak32jqavwbtyvi`
> 
> ### Storage Provider Distribution
> The below table shows the distribution of storage providers that have stored data for this client.
> 
> If this is the first time a provider takes verified deal, it will be marked as `new`.
> 
> For most of the datacap application, below restrictions should apply.
> 
> * Storage provider should not exceed 25% of total datacap.
> * Storage provider should not be storing duplicate data for more than 20%.
> * Storage provider should have published its public IP address.
> * All storage providers should be located in different regions.
> 
> ⚠️ [f01926635](https://filfox.info/en/address/f01926635) has sealed 100.00% of total datacap.
> 
> ⚠️ All storage providers are located in the same region.
> 
> Provider	Location	Total Deals Sealed	Percentage	Unique Data	Duplicate Deals
> [f01926635](https://filfox.info/en/address/f01926635)	Hong Kong, Central and Western, HK	16.00 GiB	100.00%	16.00 GiB	0.00%
> ![Provider Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/696/1671097644346.png)
> 
> ### Deal Data Replication
> The below table shows how each many unique data are replicated across storage providers.
> 
> * No more than 25% of unique data are stored with less than 4 providers.
> 
> ⚠️ 100.00% of deals are for data replicated across less than 4 storage providers.
> 
> Unique Data Size	Total Deals Made	Number of Providers	Deal Percentage
> 16.00 GiB	16.00 GiB	1	100.00%
> ![Replication Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/696/1671097645068.png)
> 
> ### Deal Data Shared with other Clients
> The below table shows how many unique data are shared with other clients. Usually different applications owns different data and should not resolve to the same CID.
> 
> ✔️ No CID sharing has been observed.
> 
> ## Footnotes
> 1. To manually trigger this report, add a comment with text `checker:manualTrigger` [↩](#user-content-fnref-1-34fabd5ab515de90e5508effd539cd40)

Sorry for the delay, the order transaction has already started.

**Comment by raulk-develop** [comment]
checker:manualTrigger

**Comment by cryptowhizzard** [comment]
Hi,

You are storing everything with one organization. Why is it that you don't follow on the rules of FIL+ ?

![Scherm­afbeelding 2023-01-27 om 14 08 07](https://user-images.githubusercontent.com/36404435/215094361-99cce972-e0d1-4b2f-988c-1d10223efd6b.png)

**Comment by cdcdx** [comment]
> Hi,
> 
> You are storing everything with one organization. Why is it that you don't follow on the rules of FIL+ ?
> 
> ![Scherm­afbeelding 2023-01-27 om 14 08 07](https://user-images.githubusercontent.com/36404435/215094361-99cce972-e0d1-4b2f-988c-1d10223efd6b.png)

The amount of data in the early stage is relatively small, and the subsequent data will be stored in different places

**Comment by cryptowhizzard** [comment]
Thanks for that quick reply.

Can you tell me who the sp’s are for the second tranche of data and how many TB you will send to them (approx)

**Comment by cdcdx** [comment]
> Thanks for that quick reply.
> 
> Can you tell me who the sp’s are for the second tranche of data and how many TB you will send to them (approx)
This time we need about 40T quota. We are still actively looking for sp. It is difficult to find reliable sps in different regions. The first time I used DC quotas was inexperienced, so I gave all the quotas to one sp. Later we will Pay attention to this matter, and spread the quota among sps in different regions.

**Comment by lvschouwen** [comment]
@cdcdx 
I think this is not how it should work.
First provide the community a list of SP(s) (MinerIDs) where you plan to seal the next quote on.
Then I suggest the notaries give you half of what you request and that can only be used to seal in a different location to demonstratie you are able to store this according to the rules of FIL+.

We cannot allow the misuse of datacap in the FIL+ community go any further.

**Comment by cdcdx** [comment]
> @cdcdx I think this is not how it should work. First provide the community a list of SP(s) (MinerIDs) where you plan to seal the next quote on. Then I suggest the notaries give you half of what you request and that can only be used to seal in a different location to demonstratie you are able to store this according to the rules of FIL+.
> 
> We cannot allow the misuse of datacap in the FIL+ community go any further.

Well, this time we must strictly follow the rules

**Comment by lvschouwen** [comment]
> > @cdcdx I think this is not how it should work. First provide the community a list of SP(s) (MinerIDs) where you plan to seal the next quote on. Then I suggest the notaries give you half of what you request and that can only be used to seal in a different location to demonstratie you are able to store this according to the rules of FIL+.
> > We cannot allow the misuse of datacap in the FIL+ community go any further.
> 
> Well, this time we must strictly follow the rules

Indeed. Looking forward to the list or the name (and MinerID(s)) of the SP(s) you will be working with to seal the next allocation in a different region 😄!

Until that time I would suggest no that you will not be granted the next trench of datacap.

**Comment by lvschouwen** [comment]
Flagged this LDN in the #fil-plus-trust-wg on Slack for further review.

**Comment by cryptowhizzard** [comment]
Hi @cdcdx 

Have you find new SP's already and are you ready to continiue?

As [f01926635](https://filfox.info/en/address/f01926635) and [f01885088](https://filfox.info/en/address/f01885088) share the same IP address you need 3! new SP's to start a new tranche of datacap.

I would like to get this LDN going again. Especially since i verified your data stored and the data matches the description of what you told us you were storing.

**Comment by cdcdx** [comment]
> Hi @cdcdx
> 
> Have you find new SP's already and are you ready to continiue?
> 
> As [f01926635](https://filfox.info/en/address/f01926635) and [f01885088](https://filfox.info/en/address/f01885088) share the same IP address you need 3! new SP's to start a new tranche of datacap.
> 
> I would like to get this LDN going again. Especially since i verified your data stored and the data matches the description of what you told us you were storing.

Thank you for your reply, I will first find a few storage miner partners to meet the needs of off-site storage.

**Comment by cdcdx** [comment]
> Hi @cdcdx
> 
> Have you find new SP's already and are you ready to continiue?
> 
> As [f01926635](https://filfox.info/en/address/f01926635) and [f01885088](https://filfox.info/en/address/f01885088) share the same IP address you need 3! new SP's to start a new tranche of datacap.
> 
> I would like to get this LDN going again. Especially since i verified your data stored and the data matches the description of what you told us you were storing.

We have contacted the new SP. The node number is f0399346. Any more information?

**Comment by cdcdx** [comment]
@cryptowhizzard @lvschouwen  It's been a long time, please take a look. Thanks
