### ISSUE TITLE
[DataCap Application]Tangshan Construction Engineering Vocational Skill Training School Co., Ltd

### ISSUE THREAD

**Issue by jekrou** [filecoin-project/filecoin-plus-large-datasets#697]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Tangshan Construction Engineering Vocational Skill Training School Co., Ltd
- Website / Social Media:www.tangshanjiangong.com
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):4PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):300TiB
- On-chain address for first allocation:f1qqfhrlhtae5qhb33xxhykp4qdctqe4mqrxf56uq

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
The industry is education, and the business scope includes: Waterproof workers (primary and intermediate), masonry workers (primary and intermediate), rebar workers (primary and intermediate), concrete workers (primary and intermediate), scaffolders (primary and intermediate), safety production management personnel, general machinery operators, mechanical equipment installers, electrical equipment installers, decoration workers, building door and window curtain wall installers, electricians, quality inspectors Professional skills training and related consulting services for construction and municipal design engineering technicians, civil construction engineering technicians, water supply and drainage engineering technicians, special equipment management and application engineering technicians (operated by the license for running a private school); Enterprise management consulting services; Book retailing (it can only be operated after obtaining approval from relevant departments according to law); Wholesale and retail of stationery; Unit logistics management services; Large scale event organization services; Conference and Exhibition Services*
```

What is the primary source of funding for this project?
```
Account from the company
```

What other projects/ecosystem stakeholders is this project associated with?
```
There are no other project / ecosystem stakeholders.
```

## Use-case details

Describe the data being stored onto Filecoin
```
Mainly the promotional pictures and videos of the activities held on the website.
```

Where was the data in this dataset sourced from?
```
It comes from the materials provided by our company and the materials uploaded by users themselves.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://drive.google.com/drive/folders/1sQd_IPhYia0Y73hxbnJprlCpe7_Gwtmw?usp=sharing
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
yes
```

What is the expected retrieval frequency for this data?
```
It depends on the actual needs.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
permanent
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
China
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
online
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We will consider the supplier's time and stability.
```

How will you be distributing deals across storage providers?
```
We will consider the supplier's time and stability.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
We have
```

**Comment by raghavrmadya** [comment]
The application is asking for higher weekly allocation without justification. Please open a new application with as much justification as possible including at least 10 data samples of the actual storage. We cannot determine the legitimacy of this client and application.
