### ISSUE TITLE
[DataCap Application] Shengjia Advertising

### ISSUE THREAD

**Issue by Stanforthww** [filecoin-project/filecoin-plus-large-datasets#698]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Shanghai Shengjia Advertising Co.
- Website / Social Media:www.sgad.com.cn
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):4PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):100TiB
- On-chain address for first allocation:f1ehz2aunofvc2ms4sxzwhtfrwn2tjioaatlnygty

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Founded at the end of 2002, Shengjia is a professional brand management service provider. Shengjia mainly provides brand management services for enterprises in the form of annual cooperation. We are able to support companies in all stages of brand development, from guiding international brands into China, positioning new brands, to "elevating" well-known brands. SEGA provides professional services to clients in three main directions. Firstly, international standard advertising campaigns. These are clients who have their own sophisticated marketing and branding programs. SEGA Advertising Services can provide 4A level creative and visual performance services to them. Secondly, the real-world integrated marketing communications campaigns. This type of client requires advertising suppliers to have not only superior advertising capabilities, but also the ability to interface more deeply with the client's marketing platform, helping the enterprise to complete marketing planning and promotion planning. This type of clients requires advertising suppliers to have not only superior advertising capabilities, but also the ability to interface more deeply with the client's marketing platform to help the company complete marketing planning and promotion planning. SEGA Strategic Services is specially designed for such needs. Thirdly, long-term strategic branding activities. This type of client requires the advertising supplier to be embedded in the marketing and operation platform of the company for a long period of time to assist them in the overall branding activities. SEGA Brand Research Center will work together with these two departments to provide customized and in-depth services to these clients.

```

What is the primary source of funding for this project?
```
The project is financed by cooperative shareholders and strategic partners with sufficient reserves.
```

What other projects/ecosystem stakeholders is this project associated with?
```
No connection to other projects
```

## Use-case details

Describe the data being stored onto Filecoin
```
The data stored on Filecoin are company works, public materials provided by our clients, and materials we need to use for our creative work, and the main forms of data are images, texts and videos.We want to use Filecoin to help us store our data.
```

Where was the data in this dataset sourced from?
```
Public data generated in the course of brand operations and advertising business.
Since its establishment, Shanghai Shengjia Advertising Co., Ltd. has been growing rapidly at a compound growth rate of 40% per year, and so far has more than ten annual service clients, a turnover of more than ten million yuan and a team of dozens of employees. It has become a dynamic force in China's intellectual service industry. With the highest purpose of solving problems for clients, SEGA has not only established a professional advertising team of 4A level, but also a dedicated marketing consulting and branding team.
In addition to our 4A-level professional advertising team, we have also set up a dedicated marketing consulting and brand research organization, integrating two professional fields: consulting and market research. We provide clients with total solutions covering marketing, branding, communication and advertising.

```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://www.sgad.com.cn/video/2022/kongque.mp4
https://www.sgad.com.cn/video/2022/mamaaihua.mp4
https://www.sgad.com.cn/video/2022/2022012c.mp4
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes, everyone can view
```

What is the expected retrieval frequency for this data?
```
 Anyone interested in this data
```

For how long do you plan to keep this dataset stored on Filecoin?
```
We hope it will always be there
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Asia
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
We will upload our data to the web server, communicate with the storage provider, download and propose offline transactions
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We plan to select a number of miners who can provide services reliably and consistently.
```

How will you be distributing deals across storage providers?
```
We will choose the vendor that can do it as soon as possible to distribute first.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, we want to close the deal as soon as possible
```

**Comment by raghavrmadya** [comment]
The application is asking for higher weekly allocation without justification. Please open a new application with as much justification as possible including at least 10 data samples of the actual storage. We cannot determine the legitimacy of this client and application.
