### ISSUE TITLE
[DataCap Application] Litian Film Holdings Limited

### ISSUE THREAD

**Issue by sitie1214** [filecoin-project/filecoin-plus-large-datasets#699]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name:Litian Film Holdings Limited 
- Website / Social Media:www.litian.tv
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):3 PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):150TiB
- On-chain address for first allocation:f1sgqavecybslnyyivwqpdhimiu73mbeyqypr7ama

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Li Tianying ("Li Tianying" and related companies, referred to as "the Group") is a TV drama holding subsidiary company, including the marketing, distribution and distribution of film and television industry dramas (similar to production, production, production, etc.) , production and other industries).The Group was established in 2013, and its current main business is self-produced and buyout of TV drama broadcasting rights. According to the Frost & Sullivan Report, we ranked 15th among all Chinese TV drama distribution groups in terms of revenue earned from the TV drama market in 2019; Among all TV drama distribution companies, we ranked first with a market share of approximately 6.9%; among all TV drama production and distribution companies in China, we ranked sixth with a market share of approximately 0.9% in terms of the number of TV drama hours produced in 2019.From 2017 to 2019, we released a total of 120 TV series with different themes. We have the advantages of abundant TV series distribution channels and maintain business contacts with more than 90 provincial and municipal mainstream TV channels and network platforms. The film and television works we distribute have been successfully broadcasted on CCTV TV series channel, Zhejiang Satellite TV, Anhui Satellite TV, Shenzhen Satellite TV, Tencent Video, iQiyi, Youku and other TV stations and new media network platforms.We have a rich reserve of TV drama copyrights. Starting in 2019, we entered the online drama market, cooperating with a third-party TV drama production company owned by a leading Chinese technology company to co-produce online dramas. We will continue to strengthen the production and distribution capabilities of TV series, focus on producing and distributing more high-quality TV series to leading satellite TV channels, and at the same time, we will invest more resources, actively develop and produce more types of online series to satisfy young audiences different preferences.We are dedicated and professional. We will continue to focus on enhancing our comprehensive competitiveness and consolidate and enhance our position in the Chinese TV drama market.
```

What is the primary source of funding for this project?
```
Account from the company.
```

What other projects/ecosystem stakeholders is this project associated with?
```
This has nothing to do with other projects.
```

## Use-case details

Describe the data being stored onto Filecoin
```
Primarily promotional images for events held on the website.
```

Where was the data in this dataset sourced from?
```
It comes from materials provided by our company and materials uploaded by users themselves.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://drive.google.com/drive/folders/1JDRk4id-aHrMzT-kriRDcbYI7u5J7TH7?usp=sharing
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes
```

What is the expected retrieval frequency for this data?
```
Anyone interested in our brand or products can open it to view.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
permanent
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
China
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
We will use both online and offline transfers.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We will consider the timing and stability of the supplier.
```

How will you be distributing deals across storage providers?
```
We will understand if the storage provider has the relevant experience and sustainability, and based on the analysis we will assign it rationally to different storage providers
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
We have sufficient funds and resources.
```

**Comment by raghavrmadya** [comment]
The application is asking for higher weekly allocation without justification. Please open a new application with as much justification as possible including at least 10 data samples of the actual storage. We cannot determine the legitimacy of this client and application.

**Comment by sitie1214** [comment]
、

> 该应用程序在没有正当理由的情况下要求更高的每周分配。请尽可能多地打开一个新应用程序，包括至少 10 个实际存储的数据样本。我们无法确定此客户端和应用程序的合法性。

A new data sample link has been uploaded please check
https://drive.google.com/drive/folders/1cKMbAcSqpxSdsdESM5L626hdqyk54IX9?usp=sharing
