### ISSUE TITLE
[DataCap Application] OSCCHINA

### ISSUE THREAD

**Issue by Gitee-Alex** [filecoin-project/filecoin-plus-large-datasets#7]
# Large Dataset Notary Application

To apply for a DataCap allocation for your dataset, please fill out the following information.

## Core Information
- Organization Name: OSCCHINA
- Website / Social Media: https://www.oschina.net / https://gitee.com 
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 1PiB
- On-chain address for first allocation: f3qcpd4uybca3mvyovwjcqvvuikia3uqm5nte6lbs5dmtgz3udbohskmo3lmoasqjmtqc2qmsyko7sahfzi46q

## Project details
Share a brief history of your project and organization.
```
OSSCHINA is a one-stop open-source technology company. The flagship product, OSCHINA, is the largest open-source technology community in China. It was founded back in 2008 and now serve more than 3 million users. Gitee, the code hosting and collaborative development platform we built, taking honor of being the second largest source code hosting platform after Github, is currently host more than 6 million developers and more than 15 million hosting projects. It bring together almost all original open source projects in mainland China. Gitee launched the enterprise version in 2016, providing enterprise-level code hosting services, and becoming a leading SaaS service provider in the development field.
```

What is the primary source of funding for this project?
```
Gitee is a project to host both open source project and enterprise private project. We do not charge for open source project, which has been funded by the parent company’s capital injection and corporate service fee. 
```

What other projects/ecosystem stakeholders is this project associated with?
```
The primary stakeholder is the FileStations, who has committed to provide S3 Gateway for Filecoin.
```

## Use-case details
Describe the data being stored onto Filecoin
```
We plan to upload the archived copy of the historical code of the hosted open-source project to Filecoin network. At present, the size of archived code is 200TB. We plan to upload five copies for redundancy. The full list of datasets can be found here: https://gitee.com/explore.
```

Where was the data in this dataset sourced from?
```
Each of these datasets come from historical code of the open-source project hosted on the Gitee . All data are publicly available. 
```

Can you share a sample of what is in the dataset? A link to a file, an image, a table, etc., are good examples of this.
```
Here are links to a few of the projects:
-[Huawei Hongmeng Operating System] (https://gitee.com/openharmony)
-[Baidu Apollo Autonomous Driving Platform] (https://gitee.com/ApolloAuto)
```

Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
These are all public datasets that can be retrieved by anyone on the network through the Gitee website or through the Git protocol.
```

What is the expected retrieval frequency for this data?
```
We expect that retrieval frequency to be sporadic - some users may choose to retrieve this data to backtrack and detect bugs, some may retrieve out of synchronizing local copies-the retrieval frequency really depends on public desire. Since the retrieval request may occur at any time, in the future, we will work with the FileStations to cache some hot data based on user retrieval frequency to reduce the cost of Filecoin decoding.
```

For how long do you plan to keep this dataset stored on Filecoin? Is this a permanent archival or a temporary storage deal?
```
We intend to store the dataset for a minimum 18 months duration, and we are intending to enable renewals in the future.
```

## DataCap allocation plan
In which geographies do you plan on making storage deals?
```
The userbase of Gitee platform is mainly located in China. Considering availability, we will store most of the copies (at least 3 copies) in China, and then at least one copy will be placed in Hong Kong or overseas, ensuring the efficiency and diversity.
```

What is your expected data onboarding rate? How many deals can you make in a day, in a week? How much DataCap do you plan on using per day, per week?
```
The size of archived copy is 200 TB. The DataCap applied is mainly used to upload these data into the Filecoin. The upload speed is decided by the performance of the miners' cluster. We might import data to miners by offline deals
, which is expected to take 20 days to import a whole copy. Adding up the time of data copying and shipping the drive, it will take around 2 months for all five data copies to be uploaded to Filecoin.
```

How will you be distributing your data to miners? Is there an offline data transfer process?
```
Given the scale of the dataset, we plan to use an offline data transfer process. We will use hard disk cabinets to copy the data and transport them to miners for storage.
In the future, the incremental archived data will be transmitted online using S3 gateway. The S3 gateway will be provided by the FileStations team and deployed in the IDC of the miners.
```

How do you plan on choosing the miners with whom you will be making deals?
```
The miners we work with must meet several conditions:
-The IDC should be T3 level or above, and not less than 3 years lease with the IDC is required.
-Public network bandwidth should be 1GB/s or above, with a fixed IP address, and all miners must ensure at least one line of China Telecom, China Unicom, China Mobile and overseas.
-Willingness to provide us with additional machines to build the FileStations S3 gateway.
```

How will you be ensuring fair distribution of storage and DataCap across miners storing data?
```
We plan to work with 5 to 10 miners, and allocate copies according to the miners conditions. The better the IDC level and bandwidth, the more data and DataCaps will be allocated. Each miner can store at most one copy of the complete data.
```

**Comment by steven004** [comment]
This is a really good case of the real data storing in Filecoin Network, and it is easy to validate the data since they are open-source code archives . 

As one of the users of OSCChina, I would support this!

**Comment by rayshitou** [comment]
@Gitee-Alex  As a user, it's great to see you join the Filecoin ecosystem. Support you definitely.

**Comment by MegTei** [comment]
Hi @dkkapur Im assuming this will follow the multisig process, happy to be part of it

**Comment by dannyob** [comment]
This looks to be a great project. Filecoin Foundation (in the Europe notary region) is happy to support as notary.

**Comment by flyworker** [comment]
OSCChina provides lot of useful information for China community developers, we like to see it have backup overseas on Filecoin network.

Yes, we will support.

**Comment by dkkapur** [comment]
In the notary governance call today, we had @dannyob volunteer to take the lead on this application.

**Comment by MRJAVAZHAO** [comment]
I support this project.

**Comment by neogeweb3** [comment]
Count me in

**Comment by dannyob** [comment]
Hi @dkkapur , I think we now have notary quora for an allocation!

**Comment by galen-mcandrew** [comment]
@Gitee-Alex  I'm not seeing your requested weekly DataCap allocation. Looks like your total requested is 1 PiB, correct? Would you like to request a weekly rate of 50 TiB to start?

**Comment by galen-mcandrew** [comment]
Final list of 7 notaries for this application:

1. @dannyob  - f1k6wwevxvp466ybil7y2scqlhtnrz5atjkkyvm4a
2. @steven004 - f1qoxqy3npwcvoqy7gpstm65lejcy7pkd3hqqekna
3. @rayshitou - f136bz32l2hlyad4npmfg5dngcdw3jk3tpcpoz2ja
4. @MegTei - f1ystxl2ootvpirpa7ebgwl7vlhwkbx2r4zjxwe5i
5. @flyworker - f1hlubjsdkv4wmsdadihloxgwrz3j3ernf6i3cbpy
6. @MRJAVAZHAO - f14gme3f52prtyzk6pblogrdd6b6ivp4swc6qmesi
7. @neogeweb3 - f13k5zr6ovc2gjmg3lvd43ladbydhovpylcvbflpa

These notaries cover Europe, GCN, NA, and Oceania thereby meeting the 3 region requirement.

**Comment by dkkapur** [comment]
@galen-mcandrew application above states 20 days for 200TiB, I think pretty safe to move forward with 50TiB for now and we can adjust once we hear back from the client.

**Comment by galen-mcandrew** [comment]
## Multisig Notary requested

#### Notary addresses
>  f1k6wwevxvp466ybil7y2scqlhtnrz5atjkkyvm4a
> f1qoxqy3npwcvoqy7gpstm65lejcy7pkd3hqqekna
> f136bz32l2hlyad4npmfg5dngcdw3jk3tpcpoz2ja
> f1ystxl2ootvpirpa7ebgwl7vlhwkbx2r4zjxwe5i
> f1hlubjsdkv4wmsdadihloxgwrz3j3ernf6i3cbpy
> f14gme3f52prtyzk6pblogrdd6b6ivp4swc6qmesi
> f13k5zr6ovc2gjmg3lvd43ladbydhovpylcvbflpa

#### Total DataCap requested
> 1PiB

#### Expected weekly DataCap usage rate
> 50TiB

**Comment by galen-mcandrew** [comment]
Hi @Gitee-Alex thanks for your patience! At this time we are seeing the large dataset notary successfully created ([f01169319](https://filplus.d.interplanetary.one/notaries?filter=f01169319))

@dannyob you volunteered to take the lead I think? Can you please kick off the first allocation and tag the other notaries to approve?

Total DataCap requested: 1PiB
Expected weekly DataCap usage rate: 50TiB
First allocation: **25TiB**

**Comment by dannyob** [comment]
## DataCap Allocation requested
#### Multisig Notary address
> f01169319
#### Client address
> f3qcpd4uybca3mvyovwjcqvvuikia3uqm5nte6lbs5dmtgz3udbohskmo3lmoasqjmtqc2qmsyko7sahfzi46q
#### DataCap allocation requested
> 25TiB

**Comment by dannyob** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebezw3ybuzbbsumme575q7frow7sgycsuxkfvvgaxxfdatmuq4uto 
#### Address 
> f3qcpd4uybca3mvyovwjcqvvuikia3uqm5nte6lbs5dmtgz3udbohskmo3lmoasqjmtqc2qmsyko7sahfzi46q
#### Datacap Allocated
> 27487790694400
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebezw3ybuzbbsumme575q7frow7sgycsuxkfvvgaxxfdatmuq4uto

**Comment by dannyob** [comment]
@steven004 @rayshitou @MegTei @flyworker @MRJAVAZHAO @neogeweb3 
Hello, fellow notaries! Please log in as the institution multisig f01169319 and approve this large datacap! Thank you! 谢谢 !

**Comment by MegTei** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebhti3tkgedrxgovq6ghihtyu7diqrsgylwiroxngkw2w32tc7mxs 
#### Address 
> f3qcpd4uybca3mvyovwjcqvvuikia3uqm5nte6lbs5dmtgz3udbohskmo3lmoasqjmtqc2qmsyko7sahfzi46q
#### Datacap Allocated
> 27487790694400
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebhti3tkgedrxgovq6ghihtyu7diqrsgylwiroxngkw2w32tc7mxs

**Comment by neogeweb3** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedf2uskstnxn55jgnogefr76dylu65ewd6tezej6o7jxpojundlto 
#### Address 
> f3qcpd4uybca3mvyovwjcqvvuikia3uqm5nte6lbs5dmtgz3udbohskmo3lmoasqjmtqc2qmsyko7sahfzi46q
#### Datacap Allocated
> 27487790694400
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedf2uskstnxn55jgnogefr76dylu65ewd6tezej6o7jxpojundlto

**Comment by flyworker** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedy5mghf5dbd3w2pizfxz7riei5z6d4lqohfebt4iwmzng7p6ia7s 
#### Address 
> f3qcpd4uybca3mvyovwjcqvvuikia3uqm5nte6lbs5dmtgz3udbohskmo3lmoasqjmtqc2qmsyko7sahfzi46q
#### Datacap Allocated
> 27487790694400
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedy5mghf5dbd3w2pizfxz7riei5z6d4lqohfebt4iwmzng7p6ia7s

**Comment by rayshitou** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced6qkomzbjglldabhbpibwoy27k773cyaluyh6nak5b6dvsdlqc6s 
#### Address 
> f3qcpd4uybca3mvyovwjcqvvuikia3uqm5nte6lbs5dmtgz3udbohskmo3lmoasqjmtqc2qmsyko7sahfzi46q
#### Datacap Allocated
> 27487790694400
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced6qkomzbjglldabhbpibwoy27k773cyaluyh6nak5b6dvsdlqc6s

**Comment by galen-mcandrew** [comment]
Amazing, thanks team! At this time, I'm seeing 25TiB of DataCap at client address f3qcpd4uybca3mvyovwjcqvvuikia3uqm5nte6lbs5dmtgz3udbohskmo3lmoasqjmtqc2qmsyko7sahfzi46q using https://verify.glif.io/

@Gitee-Alex thanks again for your patience with this process!

**Comment by galen-mcandrew** [comment]
rolling to https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/47
