### ISSUE TITLE
[DataCap Application] AOE Network

### ISSUE THREAD

**Issue by Gibsonyb** [filecoin-project/filecoin-plus-large-datasets#700]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Shenzhen AOE Network Technology Co., Ltd
- Website / Social Media:www.aoemo.com
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):3 PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):100 TiB
- On-chain address for first allocation:f1ijkwjmh7yhatn64qsqwcekkpqgrqwp5xorty25i

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Aoe network technology, established in Shenzhen in October 2016, is a rapidly developing mobile Internet company. In 2020, it was certified as a national high-tech enterprise. At present, it has branches in Hong Kong and Guangzhou. The company focuses on the realization and empowerment of global leisure content traffic, mainly focusing on the application scenarios on smart phones, and independently develops a variety of APP products including leisure games, input methods, social tools, etc. it is also an excellent game advertising value-added solution provider and leisure game publisher. The audience covers many countries and regions such as Europe and America, South America and Southeast Asia, and the user scale has exceeded 500 million.
```

What is the primary source of funding for this project?
```
Own funds and company profits.
```

What other projects/ecosystem stakeholders is this project associated with?
```
None.
```

## Use-case details

Describe the data being stored onto Filecoin
```
pictures,data,logfile.
```

Where was the data in this dataset sourced from?
```
From within the company.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://drive.google.com/drive/folders/12uJdCcpsJUYF_ePx3ZWNKijq6woJpaCC?usp=sharing
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes, I confirm.
```

What is the expected retrieval frequency for this data?
```
Four times a year.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
More than three years.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
All regions.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
We will use offline data transfer.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We will choose experienced and powerful storage suppliers.
```

How will you be distributing deals across storage providers?
```
We will allocate to high-quality and experienced storage suppliers on an average basis.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Of course, we are a very powerful company.
```

**Comment by Sunnyiscoming** [comment]
Can you provide more data samples to prove that you have 3 PB data already?How many copies will you store?
Can you clarify the name of the game you have developed and the development credentials?
Can you provide more detailed information about other storage providers participated in this program, such as you can list SPs you have contacted with at present?
Could you send an email to filplus-app-review@fil.org with your official domain in order to confirm your identity? Email name should includes the issue id #700.

**Comment by Sunnyiscoming** [comment]
Any update here?
