### ISSUE TITLE
[DataCap Application] <Chuangshengyun> - <CSCloud AI Trainning Platform>

### ISSUE THREAD

**Issue by torans** [filecoin-project/filecoin-plus-large-datasets#702]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Chuangshengyun Technology
- Website / Social Media: https://www.chuangshengyun.info/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 2PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 40TiB
- On-chain address for first allocation: f1xts6y3lb7mmcjelapapjsvso7yv2cvwip7pozay

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Chuangshengyun Technology provides professional AI training data services, and provides the collection, annotation and maintenance of various types of data such as video images, radar, text, and voice throughout the process, paving the way for your AI.
```

What is the primary source of funding for this project?
```
Company `s income. 
```

What other projects/ecosystem stakeholders is this project associated with?
```
No.
```

## Use-case details

Describe the data being stored onto Filecoin
```
Publicly Trainning data(Videos、Images、Files) about Finance、Agricultural、Industrial etc.
```

Where was the data in this dataset sourced from?
```
Company`s NAS servers.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://drive.google.com/drive/folders/1bn62wZ6KV_wtU2LXKG6J6_Ed7l-UMcli?usp=sharing
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Confirm.
```

What is the expected retrieval frequency for this data?
```
There is no fixed retrieval frequency for this data.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
3 years at least.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Asia.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Online transfer or distribute offline to storage providers.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We will select storage provider with Safely, efficiently, reliably and at low cost. Must have experience in verifying data to conduct transactions.
```

How will you be distributing deals across storage providers?
```
Less than 25% of total data will be stored in each SP.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes! We have enough funds to support this project. 
```

**Comment by Sunnyiscoming** [comment]
- What's the relationship between you and organization? Can you provide some related materials?
- Your company was founded in December 2021. Can you explain about data source of trainning data(Videos, Images, Files) about Finance, Agricultural, Industrial etc?  How did you gather this information?
- The data you have provided are all little icons of the cockroaches, too. Can you provide more data samples related with trainning data(Videos, Images, Files) about Finance, Agricultural, Industrial etc.? How many copies will you store?
- Can you provide more detailed information about other storage providers participated in this program, such as you can list SPs you have contacted with at present?

**Comment by torans** [comment]
> * What's the relationship between you and organization? Can you provide some related materials?
> * Your company was founded in December 2021. Can you explain about data source of trainning data(Videos, Images, Files) about Finance, Agricultural, Industrial etc?  How did you gather this information?
> * The data you have provided are all little icons of the cockroaches, too. Can you provide more data samples related with trainning data(Videos, Images, Files) about Finance, Agricultural, Industrial etc.? How many copies will you store?
> * Can you provide more detailed information about other storage providers participated in this program, such as you can list SPs you have contacted with at present?

@Sunnyiscoming 
I am one of the Technical staff in the company. I have been entrusted to submit the company application in my github account. The following attachments are commissioned.
https://drive.google.com/file/d/1FJivNAlOysYIS1IJfsm2rk6eXHPsa69_/view?usp=sharing

Yes, although the company is not a long part, we have many high-quality customers from network cooperation. In terms of data. Have many of these data customers provide publicly available data. Or according to actual needs. We will use the copy data provided from customers time to time and train models that can be more accurate.

Related Data Samples as below.
(Finance) Loan Default Forecast
https://drive.google.com/drive/folders/1x70wNRnmA_80VG7cx01Uaj-7T8etmQiV?usp=sharing 
(Industrial)Hard hat wearing prediction:
https://drive.google.com/drive/folders/1MGN_Xlu3I4ZnDXbCRoofYaFStdxtnmlI?usp=sharing
(Agriculture) Pest identification training
https://drive.google.com/drive/folders/1owpmTFIWwg5vF6V9q3bG7oO-UYIRwA2G?usp=sharing
(Agriculture) Image monitoring of leafy vegetables pests and diseases 
https://drive.google.com/drive/folders/1irnBDmfB28CdmM3SCcbRZ8FVb6IxIbqZ?usp=sharing
(Industrial) Floor tile crack detection sample data 
https://drive.google.com/drive/folders/1txb-wA5XHyMXoWF9dM59Zm8k0taSYw2q?usp=sharing

Some of the SP we are contacting include nodes miner in Hong Kong or Singapore.  Less than 25% of total data will be stored in each SP.If the approved quota is down, we will communicate with them better. I hope you can help us review it first.

In addition, We have revised the usage and resubmitted Total amount of DataCap 2PiB and Weekly allocation of DataCap 40TiB DataCap. We hope it can be approved. Thanks again.

**Comment by Sunnyiscoming** [comment]
Could you send an email to filplus-app-review@fil.org with your official domain in order to confirm your identity? Email name should includes the issue id #702.
Can you list sps nodes here? Whether they support data retrieval?

**Comment by torans** [comment]
> Could you send an email to [filplus-app-review@fil.org](mailto:filplus-app-review@fil.org) with your official domain in order to confirm your identity? Email name should includes the issue id #702. Can you list sps nodes here? Whether they support data retrieval?

@Sunnyiscoming 
It has been sent to filplus-app-review@fil.org by our company email, please confirm.
We will store it on the following SP nodes f095334, f098743, f0509981, f01085801, f0818625. All the SP nodes support data retrieval functions.

**Comment by torans** [comment]
hi @Sunnyiscoming. Is there anything else we need to add and improve?

**Comment by torans** [comment]
> > Could you send an email to [filplus-app-review@fil.org](mailto:filplus-app-review@fil.org) with your official domain in order to confirm your identity? Email name should includes the issue id #702. Can you list sps nodes here? Whether they support data retrieval?
> 
> @Sunnyiscoming It has been sent to [filplus-app-review@fil.org](mailto:filplus-app-review@fil.org) by our official email, please confirm. We will store it on the following SPs nodes f095334, f098743, f0509981, f01085801, f0818625. All the SPs nodes support data retrieval functions.



> Could you send an email to [filplus-app-review@fil.org](mailto:filplus-app-review@fil.org) with your official domain in order to confirm your identity? Email name should includes the issue id #702. Can you list sps nodes here? Whether they support data retrieval?

hi @Sunnyiscoming . Is there anything else we need to add and improve?

**Comment by torans** [comment]
> 



> Could you send an email to [filplus-app-review@fil.org](mailto:filplus-app-review@fil.org) with your official domain in order to confirm your identity? Email name should includes the issue id #702. Can you list sps nodes here? Whether they support data retrieval?

Hey @Sunnyiscoming .  As shown in the figure, we have sent an email to [filplus-app-review@fil.org](mailto:filplus-app-review@fil.org) through the company's official domain email, and look forward to your review, thanks.
![Email snapshot](https://drive.google.com/file/d/1yHomR_i-zwhmKA3tVgxkYgPTRWPkvsfr/view?usp=sharing)

If there are any problems that we need to continue to supplement and improve. We will actively cooperate with SPs. Now we urgently need a safe and reliable platform to backup existing data. No longer consider continuing to use self-built NAS server . If we can pass the application, we still need time to communicate with SPs on how online or offline storage the data. We look forward to your reply, thanks again.

**Comment by Sunnyiscoming** [comment]
Email received.

**Comment by torans** [comment]
> Email received.

Thanks for your reply, what should we do next?

**Comment by raghavrmadya** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 2PiB

**Expected weekly DataCap usage rate**

> 40TiB

**Client address**

>f1xts6y3lb7mmcjelapapjsvso7yv2cvwip7pozay

**Comment by raghavrmadya** [comment]
Triggering because the client has answered questions. Notaries are requested to do further due diligence to ascertain the dataset. Thanks

**Comment by torans** [comment]
> Triggering because the client has answered questions. Notaries are requested to do further due diligence to ascertain the dataset. Thanks

@raghavrmadya  Thanks. what should we do next?

**Comment by fireflyHZ** [comment]
This identification technique is very interesting and I will support and do due diligence

**Comment by fireflyHZ** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaikhw3vmo2osmh454nvzyikgkpzb3gqzo63snvcwwqphbzysp3x4 
#### Address 
> f1xts6y3lb7mmcjelapapjsvso7yv2cvwip7pozay
#### Datacap Allocated
> 20.00TiB
#### Signer Address
> f1fg6jkxsr3twfnyhdlatmq36xca6sshptscds7xa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaikhw3vmo2osmh454nvzyikgkpzb3gqzo63snvcwwqphbzysp3x4

**Comment by psh0691** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacea5qeuwr4nipz5saimmwqxrzudcaly2pa53xs32g4l6pncoxtfeeu 
#### Address 
> f1xts6y3lb7mmcjelapapjsvso7yv2cvwip7pozay
#### Datacap Allocated
> 20.00TiB
#### Signer Address
> f1qdko4jg25vo35qmyvcrw4ak4fmuu3f5rif2kc7i
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacea5qeuwr4nipz5saimmwqxrzudcaly2pa53xs32g4l6pncoxtfeeu

**Comment by BigD-Exchange** [comment]
@torans Hi! Great to see you have gotten approval for DataCap and advancing the mission of preserving humanity’s most important information. If you are looking for storage providers to store these data or have any questions, please visit #bigdata-exchange on Filecoin Slack or reply here. 

We have strong demand from a diverse group of SPs, who are actively looking to onboard more data.

**Comment by GaryGJG** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedaofrd3ryol3uj3w6wfv736qd6vrukhgjcptaovdwinkqoryebke 
#### Address 
> f1xts6y3lb7mmcjelapapjsvso7yv2cvwip7pozay
#### Datacap Allocated
> 40.00TiB
#### Signer Address
> f1zffqhxwq2rrg7rtot6lmkl6hb2xyrrseawprzsq
#### Id
> c72fd5ed-1925-45b1-a49c-440b8d49308e
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedaofrd3ryol3uj3w6wfv736qd6vrukhgjcptaovdwinkqoryebke

**Comment by newwebgroup** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaufbpwt4zg3umvwpevxjl5qxezxztzzw6piz2ptkwxaju4rewm34 
#### Address 
> f1xts6y3lb7mmcjelapapjsvso7yv2cvwip7pozay
#### Datacap Allocated
> 40.00TiB
#### Signer Address
> f1e77zuityhvvw6u2t6tb5qlnsegy2s67qs4lbbbq
#### Id
> c72fd5ed-1925-45b1-a49c-440b8d49308e
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaufbpwt4zg3umvwpevxjl5qxezxztzzw6piz2ptkwxaju4rewm34

**Comment by filplus-checker** [comment]
## DataCap and CID Checker Report[^1]
 - Organization: `Chuangshengyun Technology`
 - Client: `f1xts6y3lb7mmcjelapapjsvso7yv2cvwip7pozay`
### Storage Provider Distribution
The below table shows the distribution of storage providers that have stored data for this client.

If this is the first time a provider takes verified deal, it will be marked as `new`.

For most of the datacap application, below restrictions should apply.
 - Storage provider should not exceed 25% of total datacap.
 - Storage provider should not be storing duplicate data for more than 20%.
 - Storage provider should have published its public IP address.
 - All storage providers should be located in different regions.

⚠️ [f054464](https://filfox.info/en/address/f054464) has sealed 27.39% of total datacap.

| Provider                                                    |                           Location | Total Deals Sealed | Percentage | Unique Data | Duplicate Deals |
| :---------------------------------------------------------- | ---------------------------------: | -----------------: | ---------: | ----------: | --------------: |
| [f054464](https://filfox.info/en/address/f054464)           | Hong Kong, Central and Western, HK |          11.97 TiB |     27.39% |   11.97 TiB |           0.00% |
| [f01445167](https://filfox.info/en/address/f01445167)       | Hong Kong, Central and Western, HK |           8.03 TiB |     18.38% |    8.03 TiB |           0.00% |
| [f01841133](https://filfox.info/en/address/f01841133)       |           Singapore, Singapore, SG |           8.02 TiB |     18.34% |    8.02 TiB |           0.00% |
| [f01841131](https://filfox.info/en/address/f01841131)       | Hong Kong, Central and Western, HK |           4.02 TiB |      9.20% |    3.99 TiB |           0.78% |
| [f01936456](https://filfox.info/en/address/f01936456)`new`  |                Văn Điển, Hanoi, VN |           3.93 TiB |      8.98% |    3.93 TiB |           0.00% |
| [f01971675](https://filfox.info/en/address/f01971675)`new`  |                Văn Điển, Hanoi, VN |           3.93 TiB |      8.98% |    3.93 TiB |           0.00% |
| [f0136399](https://filfox.info/en/address/f0136399)         | Hong Kong, Central and Western, HK |           3.81 TiB |      8.72% |    3.81 TiB |           0.00% |

![Provider Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/702/1671097654743.png)
### Deal Data Replication
The below table shows how each many unique data are replicated across storage providers.
- No more than 25% of unique data are stored with less than 4 providers.

⚠️ 99.36% of deals are for data replicated across less than 4 storage providers.

| Unique Data Size | Total Deals Made | Number of Providers | Deal Percentage |
| ---------------: | ---------------: | ------------------: | --------------: |
|         3.68 TiB |         3.71 TiB |                   1 |           8.49% |
|         2.11 TiB |         4.22 TiB |                   2 |           9.65% |
|        11.83 TiB |        35.50 TiB |                   3 |          81.22% |
|        32.00 GiB |       128.00 GiB |                   4 |           0.29% |
|        32.00 GiB |       160.00 GiB |                   5 |           0.36% |

![Replication Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/702/1671097655370.png)
### Deal Data Shared with other Clients
The below table shows how many unique data are shared with other clients.
Usually different applications owns different data and should not resolve to the same CID.

✔️ No CID sharing has been observed.

[^1]: To manually trigger this report, add a comment with text `checker:manualTrigger`

**Comment by cryptowhizzard** [comment]
Hello @torans 

I have been looking at your LDN to approve it for datacap, however i have some questions.

Are you the one doing the data preparation for your client or are you the client owning this data and doing the data preparation yourself?

I see that the SP's you work with all belong to one organization. Secondly they don't have a clean tracking record and they have been involved in non compliant storage data of FIL+. Can you provide me their contact information? If you want you can do that by email -> kyc@dcent.nl

That brings me to my third question. Can you provide me with a list of SP's for your new datacap allocation? 
Fyi, the SP's should not be controlled by one organization but you need 3 independent organizations in 3 different regions. If you want me to sign for a new tranch of datacap we need understanding that you won't use it for the existing organization / SP's. I know this might be difficult. If you need help finding SP's with good reputation or other help let us know.

**Comment by torans** [comment]
> 我看到与您合作的 SP 都属于一个组织



> Hello @torans
> 
> I have been looking at your LDN to approve it for datacap, however i have some questions.
> 
> Are you the one doing the data preparation for your client or are you the client owning this data and doing the data preparation yourself?
> 
> I see that the SP's you work with all belong to one organization. Secondly they don't have a clean tracking record and they have been involved in non compliant storage data of FIL+. Can you provide me their contact information? If you want you can do that by email -> [kyc@dcent.nl](mailto:kyc@dcent.nl)
> 
> That brings me to my third question. Can you provide me with a list of SP's for your new datacap allocation? Fyi, the SP's should not be controlled by one organization but you need 3 independent organizations in 3 different regions. If you want me to sign for a new tranch of datacap we need understanding that you won't use it for the existing organization / SP's. I know this might be difficult. If you need help finding SP's with good reputation or other help let us know.

Happy New Year, great to hear from you.
Our company provides customers with artificial intelligence algorithm service applications. And use the data for AI model training service. So we have collected a lot of application-related data together with our customers. You mentioned that the SPs we work with belong to the same organizational issue, which is not the case. Store datacap client clients as filecoin. We communicated with our partner SP immediately after receiving this information and found no compliance. If you believe there has been any violation. Please provide relevant proof, and we will further confirm upon receipt. If so, we will rectify according to compliance requirements. In order to promote the development of filecoin. Let us know if you have questions. We are willing to actively cooperate with official arrangements.

**Comment by cryptowhizzard** [comment]
Hi there, happy new year to you to!

I take it you can work with this?
Machines in the same subnet's belong to the same organization. Machines on VPN etc......


![Scherm­afbeelding 2023-02-03 om 12 06 57](https://user-images.githubusercontent.com/36404435/216588792-32353062-79ce-40dd-a779-e6e41a22abbd.png)
![Scherm­afbeelding 2023-02-03 om 12 05 05](https://user-images.githubusercontent.com/36404435/216588795-2b1dafa6-cc41-41d8-8443-d0841901b462.png)
![Scherm­afbeelding 2023-02-03 om 12 04 45](https://user-images.githubusercontent.com/36404435/216588796-e7e113a9-fa40-4c77-a704-b3e7938a5e8f.png)

![Scherm­afbeelding 2023-02-03 om 12 08 07](https://user-images.githubusercontent.com/36404435/216588776-51226dd4-3f5b-4fbc-9c25-3b09e0db5026.png)
![Scherm­afbeelding 2023-02-03 om 12 07 51](https://user-images.githubusercontent.com/36404435/216588781-3eb7f879-0d2a-412a-8345-7d1dcb4d11a2.png)
![Scherm­afbeelding 2023-02-03 om 12 07 30](https://user-images.githubusercontent.com/36404435/216588784-8fbf760a-3e81-470f-805b-d7756f3d94c2.png)
![Scherm­afbeelding 2023-02-03 om 12 07 11](https://user-images.githubusercontent.com/36404435/216588790-3c389d3b-c817-4387-891e-4a17bcd3ed04.png)

**Comment by cryptowhizzard** [comment]
Hello @torans 

You asked me a question and i provided you with the relevant proof. Can you let me know what you plan is to rectify the situation?

**Comment by torans** [comment]
> Hello @torans
> 
> You asked me a question and i provided you with the relevant proof. Can you let me know what you plan is to rectify the situation?

We communicated with SP on this matter, and SP replied that the VPN is mainly for the stability of overseas network bandwidth, which will not affect the use of DC data access at all.
In addition, the official DC data requirement is four different copies, but it seems that there is no requirement for the four different copies to be in different cities IP, and the SP we are looking for exists in three different countries and cities, including Hong Kong, Vietnam and Singapore are not the same organization. It would take us a lot of effort to find all four copies in different cities.

**Comment by torans** [comment]
> @torans At a minimum, we expect all applicants to exert effort towards advancing the Filecoin network. In recognition of such efforts, successful applicants will be rewarded with datacap. Good luck with finding more storage providers!

Dear @herrehesse . First of all, thank you for your reply. Filecoin is a great discovery of mankind. All of us will make more efforts for the human progress of filecoin and witness the development of history.

**Comment by YuanHeHK** [comment]
checker:manualTrigger

**Comment by YuanHeHK** [comment]
@torans I read the robot's report, the number of SPs you have is in line with the requirements, but the distribution areas are concentrated in two places, this is still slightly out of line with the LDN packaging specification, you should look for several SPs in different areas to store your data. Otherwise, it will be difficult to obtain community support in the future.

In addition, I tried to connect some of your SPs, and they still meet the requirements in terms of packaging specifications. For example, the following result.
```
$./bin/lotus client query-ask f01445167
Ask: f01445167
Price per GiB: 0.0000000005 FIL
Verified Price per GiB: 0 FIL
Max Piece size: 64 GiB
Min Piece size: 256 B
$
$
$./bin/lotus client query-ask f01841131
Ask: f01841131
Price per GiB: 0.0000000005 FIL
Verified Price per GiB: 0 FIL
Max Piece size: 32 GiB
Min Piece size: 256 B
$
$
$./bin/lotus client query-ask f0136399
Ask: f0136399
Price per GiB: 0.0000000005 FIL
Verified Price per GiB: 0 FIL
Max Piece size: 64 GiB
Min Piece size: 256 B
$
$
$./bin/lotus client query-ask f01841133
Ask: f01841133
Price per GiB: 0.0000000005 FIL
Verified Price per GiB: 0 FIL
Max Piece size: 32 GiB
Min Piece size: 256 B
$
$
$./bin/lotus client query-ask f01936456
Ask: f01936456
Price per GiB: 0 FIL
Verified Price per GiB: 0 FIL
Max Piece size: 64 GiB
Min Piece size: 1 GiB
$
$
$./bin/lotus client query-ask f01971675
Ask: f01971675
Price per GiB: 0 FIL
Verified Price per GiB: 0 FIL
Max Piece size: 64 GiB
Min Piece size: 1 GiB

$./bin/lotus client retrieval-ask f01445167   baga6ea4seaqn2oydbf3qxkkpa46x3ob4ypoj36uorkcsnywa7ko6qhwwabgzgfi
Ask: f01445167
Unseal price: 0 FIL
Price per byte: 0 FIL
Payment interval: 0 B
Payment interval increase: 0 B

```

**Comment by cryptowhizzard** [comment]
Mar  4 09:35:03 proposals dealscanner-f01904773-f01936456: Error: Failed to retrieve content with candidate miner f01936456: data transfer failed: deal errored: getting pieces for cid bafybeifqa4bpq3y2ud6r3rgwyoxstxsbqdk7hvrdeidcoarhlbmkpk3qca: getting pieces containing block bafybeifqa4bpq3y2ud6r3rgwyoxstxsbqdk7hvrdeidcoarhlbmkpk3qca: failed to lookup index for mh 1220b00702f86f1aa0fd1dc4d6c3af29de4180d5f3d62322062702275858a7ab7010, err: datastore: key not found

**Comment by cryptowhizzard** [comment]
Mar  4 09:35:03 proposals dealscanner-f01904773-f01936456: Error: Failed to retrieve content with candidate miner f01936456: data transfer failed: deal errored: getting pieces for cid bafybeifqa4bpq3y2ud6r3rgwyoxstxsbqdk7hvrdeidcoarhlbmkpk3qca: getting pieces containing block bafybeifqa4bpq3y2ud6r3rgwyoxstxsbqdk7hvrdeidcoarhlbmkpk3qca: failed to lookup index for mh 1220b00702f86f1aa0fd1dc4d6c3af29de4180d5f3d62322062702275858a7ab7010, err: datastore: key not found
Mar  4 21:22:35 proposals dealscanner-f01904773-f01936456: ERROR: offer error: retrieval query offer errored: failed to fetch piece to retrieve from: getting pieces for cid bafybeignteljnwvn426jxnefei2tj2l6r3cstcme46d7pjdigab4yhtpzy: getting pieces containing block bafybeignteljnwvn426jxnefei2tj2l6r3cstcme46d7pjdigab4yhtpzy: failed to lookup index for mh 1220cd991696daade6bc9bb485223534e97e8ec5298984e787f7a4683003cc1e6fce, err: datastore: key not found
Mar  4 21:22:35 proposals dealscanner-f01904773-f01936456: 
Mar  4 21:22:35 proposals dealscanner-f01904773-f01936456: Error: Failed to retrieve content with candidate miner f01936456: data transfer failed: deal errored: getting pieces for cid bafybeifqa4bpq3y2ud6r3rgwyoxstxsbqdk7hvrdeidcoarhlbmkpk3qca: getting pieces containing block bafybeifqa4bpq3y2ud6r3rgwyoxstxsbqdk7hvrdeidcoarhlbmkpk3qca: failed to lookup index for mh 1220b00702f86f1aa0fd1dc4d6c3af29de4180d5f3d62322062702275858a7ab7010, err: datastore: key not found
Mar  4 21:22:35 proposals dealscanner-f01904773-f01936456-19659250: ERROR: offer error: retrieval query offer errored: failed to fetch piece to retrieve from: getting pieces for cid bafybeidk2glqisdrnq7vzmiu4io2hjlg5ioxtogaif4tflzebupw5k22ri: getting pieces containing block bafybeidk2glqisdrnq7vzmiu4io2hjlg5ioxtogaif4tflzebupw5k22ri: failed to lookup index for mh 12206ad1970448716c3f5cb114e21da3a566ea1d79b8c0417932af240d1f6eab5a8a, err: datastore: key not found
Mar  4 21:22:35 proposals dealscanner-f01904773-f01936456-19662920: ERROR: offer error: retrieval query offer errored: failed to fetch piece to retrieve from: getting pieces for cid bafybeifqa4bpq3y2ud6r3rgwyoxstxsbqdk7hvrdeidcoarhlbmkpk3qca: getting pieces containing block bafybeifqa4bpq3y2ud6r3rgwyoxstxsbqdk7hvrdeidcoarhlbmkpk3qca: failed to lookup index for mh 1220b00702f86f1aa0fd1dc4d6c3af29de4180d5f3d62322062702275858a7ab7010, err: datastore: key not found
Mar  4 21:22:35 proposals dealscanner-f01904773-f01936456-19662920: 
Mar  4 21:22:35 proposals dealscanner-f01904773-f01936456-19659250:

**Comment by cryptowhizzard** [comment]
Per above, retrievals are not working. Can you please fix to enable us to do duediligence?
