### ISSUE TITLE
[DataCap Application] Ruiyi

### ISSUE THREAD

**Issue by Karida0615** [filecoin-project/filecoin-plus-large-datasets#705]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Ruiyi
- Website / Social Media: https://www.ryixx.com/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):100TiB
- On-chain address for first allocation:f1b5r6ewhodewcjwqumkeycpvfkxcxkzrstlvo5ga

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Henan Ruiyi creates a business model integrating responsive website technology, cloud architecture and integrated marketing. Along with the growth of China's Internet, we have experienced the rapid development of the Internet for 10 years and accumulated strong independent research and development technology and rich responsive website development cases.
```

What is the primary source of funding for this project?
```
Company's account.
```

What other projects/ecosystem stakeholders is this project associated with?
```
No
```

## Use-case details

Describe the data being stored onto Filecoin
```
The great mass of data are images and videos. We have 620TiB data and want to store 8 copies.
```

Where was the data in this dataset sourced from?
```
We provide custom web development services for our clients so that there's a large amount of website material to be stored, which are mainly uploaded by clients.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
[FUN  - .zip](https://github.com/filecoin-project/filecoin-plus-large-datasets/files/9373643/FUN.-.zip)
https://drive.google.com/file/d/1U9Wy3lJmFUw4nJrtTM_XNl6yWyvyfoRS/view?usp=sharing
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes, we properly confirm.
```

What is the expected retrieval frequency for this data?
```
Maybe once or twice a year.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
2 years
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Mainly China.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
We will take offline data transfer to distribute data. Online transfer need to consider our network speed, we don't currently have a fast network. 
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We consider and need sp's stability. We want to communicate with them via slack.
```

How will you be distributing deals across storage providers?
```
We plan to distribute deals according to their capacity.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes.
```

**Comment by Sunnyiscoming** [comment]
What's the relationship between you and organization? 
Can you provide more detailed information about other storage providers participated in this program, such as you can list SPs you have contacted with at present?
Could you send an email to filplus-app-review@fil.org with your official domain in order to confirm your identity? Email name should includes the issue id #705.

**Comment by Karida0615** [comment]
@Sunnyiscoming Hi Sunny, I am the company's technical support staff, and I represent our company to apply for datacap in Filecoin.
We are in contact with 3 SPs and we expect to work with 5-6 SPs. f01392850, f020523... We will actively look for qualified SPs.
![c7d8c1328b6f146](https://user-images.githubusercontent.com/107449814/189323011-8e3f1adc-a66f-4a22-bde4-f50ff4282ec2.jpg)

**Comment by raghavrmadya** [comment]
I do not see proper justification for 5 PiBs. Additionally, can you share why do you wish to store the 8 copies all in China? Distributing copies is a key aspect of Filecoin and decentralized storage

**Comment by Karida0615** [comment]
@raghavrmadya Hello Raghav! The data we would like to store is mainly uploaded by clients and now it is 620TiB.
What I indicated in the issue is that we will mainly make deals in China because we are currently in contact with Chinese SPs now. But we won't only choose Chinese SPs, we will follow filecoin's concept and contact other SPs from other regions for decentralized storage in the following!

**Comment by raghavrmadya** [comment]
Can you share who are your clients?

**Comment by raghavrmadya** [comment]
Given that you are providing services to clients, you are not the data owner, correct? If so, do you have permission to store your clients data in an open and public manner

**Comment by Karida0615** [comment]
Thanks @raghavrmadya , I think that your understanding is profound. What we have stored this time is some public media data that can be accessed on these platforms. Our clients let us be responsible for their websites. So the choice of storage is up to us and we have that right. We hope that more people can know and enjoy web3 via this way!

**Comment by Karida0615** [comment]
> Thanks for the response. Can you share the names of some of the clients?

Hi Raghav, I've dropped you a DM about the answer!

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 100TiB

**Client address**

>f1b5r6ewhodewcjwqumkeycpvfkxcxkzrstlvo5ga

**Comment by stcouldlisa** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedie4aukbxdwiwho3hdt4uzxnjnxuchywtfpbqhe27fmmfuxsszes 
#### Address 
> f1b5r6ewhodewcjwqumkeycpvfkxcxkzrstlvo5ga
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1jvvltduw35u6inn5tr4nfualyd42bh3vjtylgci
#### Id
> 3b7087f4-3d68-475c-a706-06bdde985fb3
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedie4aukbxdwiwho3hdt4uzxnjnxuchywtfpbqhe27fmmfuxsszes

**Comment by stcouldlisa** [comment]
This is my first signing for this client and I promise that I will keep track of their assignments and if something goes wrong, I will never sign for this client again

**Comment by swatchliu** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecj7zzyxygnfs4ousyweatkc4wicgkpvh4kwwobnmtigl7733ayvq 
#### Address 
> f1b5r6ewhodewcjwqumkeycpvfkxcxkzrstlvo5ga
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1yh6q3nmsg7i2sys7f7dexcuajgoweudcqj2chfi
#### Id
> 3b7087f4-3d68-475c-a706-06bdde985fb3
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecj7zzyxygnfs4ousyweatkc4wicgkpvh4kwwobnmtigl7733ayvq

**Comment by BigD-Exchange** [comment]
@Karida0615 Hi! Great to see you have gotten approval for DataCap and advancing the mission of preserving humanity’s most important information. If you are looking for storage providers to store these data or have any questions, please visit #bigdata-exchange on Filecoin Slack or reply here. 

We have strong demand from a diverse group of SPs, who are actively looking to onboard more data.

**Comment by YuanHeHK** [comment]
It looks like everything is fine with this app at the moment, and I will support this signing

**Comment by YuanHeHK** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebqt6g77v7pngmf4pewphbh775lj3vweys5e4jha22na7ixasdi22 
#### Address 
> f1b5r6ewhodewcjwqumkeycpvfkxcxkzrstlvo5ga
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1fg6jkxsr3twfnyhdlatmq36xca6sshptscds7xa
#### Id
> 3140c23b-8b9c-435c-b40e-4618db2e3a3f
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebqt6g77v7pngmf4pewphbh775lj3vweys5e4jha22na7ixasdi22

**Comment by UnionLabs2020** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedrz7z55zlvf55z3jgwl7j2nq2ztivh6f2467tincpzeacehizoiy 
#### Address 
> f1b5r6ewhodewcjwqumkeycpvfkxcxkzrstlvo5ga
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f17xdri3wunqgld7dm23e4f3eqsntjakwc47xjo6i
#### Id
> 3140c23b-8b9c-435c-b40e-4618db2e3a3f
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedrz7z55zlvf55z3jgwl7j2nq2ztivh6f2467tincpzeacehizoiy

**Comment by filplus-checker** [comment]
## DataCap and CID Checker Report[^1]
 - Organization: `Ruiyi`
 - Client: `f1b5r6ewhodewcjwqumkeycpvfkxcxkzrstlvo5ga`
### Storage Provider Distribution
The below table shows the distribution of storage providers that have stored data for this client.

If this is the first time a provider takes verified deal, it will be marked as `new`.

For most of the datacap application, below restrictions should apply.
 - Storage provider should not exceed 25% of total datacap.
 - Storage provider should not be storing duplicate data for more than 20%.
 - Storage provider should have published its public IP address.
 - All storage providers should be located in different regions.

⚠️ [f01974746](https://filfox.info/en/address/f01974746) has sealed 59.06% of total datacap.

⚠️ 89.56% of total deal sealed by [f01974746](https://filfox.info/en/address/f01974746) are duplicate data.

⚠️ [f01974746](https://filfox.info/en/address/f01974746) has unknown IP location.

⚠️ [f01962589](https://filfox.info/en/address/f01962589) has sealed 40.94% of total datacap.

⚠️ 89.45% of total deal sealed by [f01962589](https://filfox.info/en/address/f01962589) are duplicate data.

⚠️ [f01962589](https://filfox.info/en/address/f01962589) has unknown IP location.

⚠️ All storage providers are located in the same region.

| Provider                                                    | Location | Total Deals Sealed | Percentage | Unique Data | Duplicate Deals |
| :---------------------------------------------------------- | -------: | -----------------: | ---------: | ----------: | --------------: |
| [f01974746](https://filfox.info/en/address/f01974746)`new`  |  Unknown |          50.00 TiB |     59.06% |    5.22 TiB |          89.56% |
| [f01962589](https://filfox.info/en/address/f01962589)       |  Unknown |          34.66 TiB |     40.94% |    3.66 TiB |          89.45% |

![Provider Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/705/1671097659724.png)
### Deal Data Replication
The below table shows how each many unique data are replicated across storage providers.
- No more than 25% of unique data are stored with less than 4 providers.

⚠️ 100.00% of deals are for data replicated across less than 4 storage providers.

| Unique Data Size | Total Deals Made | Number of Providers | Deal Percentage |
| ---------------: | ---------------: | ------------------: | --------------: |
|         8.88 TiB |        84.66 TiB |                   1 |         100.00% |

![Replication Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/705/1671097660347.png)
### Deal Data Shared with other Clients
The below table shows how many unique data are shared with other clients.
Usually different applications owns different data and should not resolve to the same CID.

⚠️ CID sharing has been observed.

| Other Client                                                                                                          | Application                                                                              | Total Deals Affected | Unique CIDs |        Verifier |
| :-------------------------------------------------------------------------------------------------------------------- | :--------------------------------------------------------------------------------------- | -------------------: | ----------: | --------------: |
| [f1rnwp6p5kx7pcwexpucoav6mmwz3rkxw5blrboyy](https://filfox.info/en/address/f1rnwp6p5kx7pcwexpucoav6mmwz3rkxw5blrboyy) | [MigoVideo](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/517) |             1.59 TiB |           7 | LDN v3 multisig |
| [f1jsgrkuicjbw5g3u7f4tcs4b6zdctwxq4h6rw5na](https://filfox.info/en/address/f1jsgrkuicjbw5g3u7f4tcs4b6zdctwxq4h6rw5na) | [Neusoft](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/972)   |           608.00 GiB |           4 | LDN v3 multisig |

[^1]: To manually trigger this report, add a comment with text `checker:manualTrigger`

**Comment by cryptowhizzard** [comment]
Hello!

It seems that this LDN has not been used according to the rules of FIL+ regarding decentralization, reachability of miners, retrieval and CID sharing.

Can you please explain what is going on?

**Comment by Sunnyiscoming** [comment]
Hello, @Karida0615 per the https://github.com/filecoin-project/notary-governance/issues/922 for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

This information will be reviewed by Fil+ Governance team to confirm validity and then the application will be allowed to move forward for additional notary review.
