### ISSUE TITLE
[DataCap Application] Garage Network

### ISSUE THREAD

**Issue by Oliviaio** [filecoin-project/filecoin-plus-large-datasets#710]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Garage Network Technology Co., Ltd
- Website / Social Media:www.chekunet.com
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):5 PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):100 TiB
- On-chain address for first allocation:f1bcjkr5thcffb52y3qgyutmnnmn46fdukcpgxkki

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Garage Network Technology Co., Ltd. is engaged in a series of businesses such as the sales of imported cars, maintenance services and parts supply. The automobile sales brands include Toyota off-road vehicle series, BMW full series, Mercedes Benz GL Series, Porsche Kaiyan and other high-end brands, which come from the Middle East, the United States, Japan and other countries. The sales channel is broad. The company's headquarters is rooted in the economic hinterland of Tianjin Port Free Trade Zone. With a forward-looking development vision and following the principle of "networking with win-win ideas", it has formed 20 sales outlets in Chengdu, Changsha, Urumqi and other cities around the country with Tianjin as the center. There are 7 direct sales stores in Tianjin, Chengdu, Changsha, Chongqing, Shenzhen, Huizhou, Xichang and other cities, with an auto sales exhibition hall of nearly 10000 square meters, A relatively complete network layout has been formed, which provides a strong guarantee for the comprehensive development of the company and the promotion of market share.
The board of directors of the company is the highest authority, with functional departments including general manager, finance department, business department, sales department and logistics department. Under the guidance of "people-oriented" thinking, the company pays attention to the establishment of organizational structure; With the advanced and scientific employment mechanism, we have built an excellent team with rich marketing experience and excellent maintenance technology. Gradually realize the doubling of sales revenue and build the company into a group company with a first-class sales network and marketing system in the industry. In terms of marketing concept, the company pursues to meet the needs of customers in all aspects, always adheres to "user first", comprehensively implements the service tenet of "customer first", and takes winning the maximum trust of customers as the business basis.
```

What is the primary source of funding for this project?
```
From company account.
```

What other projects/ecosystem stakeholders is this project associated with?
```
No.
```

## Use-case details

Describe the data being stored onto Filecoin
```
Mainly video, pictures and other data.
```

Where was the data in this dataset sourced from?
```
It is prepared, collected and summarized by all sales outlets of the company.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://drive.google.com/drive/folders/1cPiTfXIWMN9kZKFI_pFz1TPh8iAcozQz?usp=sharing
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
yes.
```

What is the expected retrieval frequency for this data?
```
It depends on the actual needs.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
permanent.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
All regions.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
yes. We will use offline data transfer.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We will consider the supplier's time and stability.
```

How will you be distributing deals across storage providers?
```
We will use IPFs distributed storage to fairly distribute to miners.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, we hope to conclude the transaction as soon as possible.
```

**Comment by Sunnyiscoming** [comment]
Only 37 videos in your douyin channel. Can you provide more data samples related with video, pictures and other data except videos published on the douyin.
How many copies will you store?
Can you provide more detailed information about other storage providers participated in this program, such as you can list SPs you have contacted with at present?

**Comment by Sunnyiscoming** [comment]
Any update here?

**Comment by raghavrmadya** [comment]
No reply
