### ISSUE TITLE
[DataCap Application] Help Ukrainian miners

### ISSUE THREAD

**Issue by baysenalrone** [filecoin-project/filecoin-plus-large-datasets#713]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: baysenalrone
- Website / Social Media:[www.dcent.nl](http://www.dcent.nl/)
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):5 PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):300TiB
- On-chain address for first allocation: f1jgnl5i7jwqkhr5lt5bxbwmpdiamxroekihhp2ra

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Speedium / Dcent has engaged in Slingshot starting 3.8. We have successfully stored more than 15 different datasets with 10+ different miners.
```

What is the primary source of funding for this project?
```
Company account
```

What other projects/ecosystem stakeholders is this project associated with?
```
None.
```

## Use-case details

Describe the data being stored onto Filecoin
```
We have been contacted by miners from Ukraine to help them make a backup of their data in case anything happens given the situation in their country. The data will consists of sectors of the miners involved. The batch will be 500 TB we intend and we intend to spread it over 4 to 6 SP's.

This issue is a followup to issue #349. 

Set 1 contais 400 TB of sectors and cache data. We have packed it and uploaded it. In the mean time we received another 400 TiB of data for this LDN.
```

Where was the data in this dataset sourced from?
```
The miners uploaded it towards us.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
Yes, but we prefer to keep that private until uploaded for security reasons.
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes.
```

What is the expected retrieval frequency for this data?
```
Just a few times for checking but we hope that it won't be necessary  offcourse.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
18 months or longer
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
EU / China / US / Australia.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
The data will be transferred both offline and online.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We have a few providers who have been working with us during Slingshot Restore program and we'd like to continue working with them for ongoing Slingshot competition.
```

How will you be distributing deals across storage providers?
```
Max 2 copy's per storage provider if stored on different miners / locations.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, we have the resources.
```

**Comment by raghavrmadya** [comment]
@ cryptowhizzard, can you confirm this request is from your organization? A similar request was approved here. If yes, please let me know the reason for using a new/different GitHub account. Thanks.

**Comment by cryptowhizzard** [comment]
@raghavrmadya @galen-mcandrew thanks for checking. No, this is not mine or Dcent / Speedium. So yeah, it is fraud.

**Comment by raghavrmadya** [comment]
@cryptowhizzard, thanks for the quick response.
