### ISSUE TITLE
[DataCap Application] SIZE Media

### ISSUE THREAD

**Issue by donaldqe** [filecoin-project/filecoin-plus-large-datasets#714]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Beijing Seth Times Media Culture Co.
- Website / Social Media:sizemedia.com.cn
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):4PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):100TiB
- On-chain address for first allocation:f164gpwa6q5wenttuj2jygh4agnqzafzcdihrdiay

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Since its establishment, SIZE Media has been dedicated to the operation of sports media and trendy media, mainly engaged in the editing, design, production and distribution of content for paper media (two magazines) and online media (Internet and mobile Internet), as well as the planning, organization and execution of various activities, covering various aspects of sports equipment, trendy life, outdoor sports and lifestyle, which have profoundly influenced people at all levels in China. understanding of sports, sports lifestyle The content covers a wide range of sports equipment, trendy lifestyle, outdoor sports and lifestyle, etc. It has a profound impact on the understanding of sports, sports lifestyle and interpretation of trendy culture of Chinese people at all levels, and has a strong consumer guidance power for the media coverage.

```

What is the primary source of funding for this project?
```
Operating income from companies
```

What other projects/ecosystem stakeholders is this project associated with?
```
No
```

## Use-case details

Describe the data being stored onto Filecoin
```
The data stored on Filecoin is all about sneakers in paper, online, books, audiovisual media, etc.
```

Where was the data in this dataset sourced from?
```
Public data generated in the course of new media business and e-commerce operation
Up to now, size media new media platform has accumulated about one million users and become an influential SNEAKER new media platform in the industry. It provides urban youth with a full range of consumer services for sports shoes and trendy products, combining the media function of an information website and the business function of an e-commerce website. It includes timely and accurate product information, professional and considerate consumer services, real and rich product experience, and safe and convenient online shopping.

```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
http://sizemedia.com.cn/StaticPage/zt_1.html
http://sizemedia.com.cn/StaticPage/xw_1.html
http://sizemedia.com.cn/StaticPage/sz_1.html
https://drive.google.com/file/d/1VZGuyTRuHjIaWabubgsmuuB_KlOPwq8k/view?usp=sharing
https://drive.google.com/file/d/1a5iPtuFdzw1QyFB_Bh9MeQdALgJPreO0/view?usp=sharing
https://drive.google.com/file/d/1v7dBSQX1gJRt0cQwTfg5xVGFRDtF7uj0/view?usp=sharing

```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
yes.
```

What is the expected retrieval frequency for this data?
```
It depends on the actual need.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
Two years
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Asia
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Yes. We will use offline data transfer.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We plan to work with a number of suppliers who can provide services reliably and consistently
```

How will you be distributing deals across storage providers?
```
We will allocate an equal share to high quality storage providers.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, we want to close the deal as soon as possible.
```

**Comment by Sunnyiscoming** [comment]
Some videos shared on the website disappeared. Can you explain the summary of the video, such as the link of the channel of Tencent video, the Tencent video link at the bottom of the website is invalid. How much data of videos do you have? How many copies are you gonna back up?
What's the relationship between you and organization?
Can you provide more detailed information about other storage providers participated in this program, such as you can list SPs you have contacted with at present?

**Comment by Sunnyiscoming** [comment]
Any update here?

**Comment by Sunnyiscoming** [comment]
Close for no reply. You can resubmit your application if necessary.
