### ISSUE TITLE
[DataCap Application] Wuhan Renhe Accounting Consulting Service Co.

### ISSUE THREAD

**Issue by renhekuaiji** [filecoin-project/filecoin-plus-large-datasets#715]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Wuhan Renhe Accounting Consulting Service Co.
- Website / Social Media:https://www.whrhkj.com/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):2 PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):200TiB
- On-chain address for first allocation:f1rn7yklhcnrboyaqrqolahzhifezqlwry2u3ytzi

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
The company's mission is to "focus on practical taxation training and build elite taxation talents", and specializes in providing four core services: practical accounting education and training, corporate taxation management consulting, bookkeeping for small and medium-sized enterprises, and accounting talent recommendation. At present, Renhe has been stationed in Beijing, Shanghai, Guangzhou, Shenzhen, Chongqing, Chengdu, Hefei and other more than 60 cities.
```

What is the primary source of funding for this project?
```
Training Fees
```

What other projects/ecosystem stakeholders is this project associated with?
```
no
```

## Use-case details

Describe the data being stored onto Filecoin
```
Video of our company's instructor giving a lecture
```

Where was the data in this dataset sourced from?
```
Recorded by the company
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://drive.google.com/drive/folders/10KGFHO1TbzA535Xhu4LPOOBfSNd1oh3S?usp=sharing
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
yes
```

What is the expected retrieval frequency for this data?
```
Usually not used
```

For how long do you plan to keep this dataset stored on Filecoin?
```
Three to five years
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Wuhan，China
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
offline
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
Select large miners
```

How will you be distributing deals across storage providers?
```
Handed over to a miner to handle, after all, only 2Pib
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, hurry up and get started!
```

**Comment by Sunnyiscoming** [comment]
How many copies will you store? Can you share more data samples to prove that you have such a dataset to store? I can't check more open videos without paying.
What's the relationship between you and organization?
Can you provide more detailed information about other storage providers participated in this program, such as you can list SPs you have contacted with at present?

**Comment by Sunnyiscoming** [comment]
Any update here?

**Comment by Sunnyiscoming** [comment]
Close for no reply. You can resubmit your application if necessary.
