### ISSUE TITLE
[DataCap Application] Shanxi Focus Media Advertising Co., Ltd.

### ISSUE THREAD

**Issue by sitie1216** [filecoin-project/filecoin-plus-large-datasets#716]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Shanxi Focus Media Advertising Co., Ltd.
- Website / Social Media: http://www.focusmedia.cn
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 3 PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):150TiB
- On-chain address for first allocation:f1v3kibovf4aitjh3wtrka4eekydx4has6ah2kl6a

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Shanxi Focus Media Co., Ltd. (Focus Media), China's leading digital media group, was founded in 2003. Its product line covers many media networks that target specific audiences and can be organically integrated with each other. In July 2005, Focus Media successfully landed on the Nasdaq in the United States, becoming the first Chinese pure advertising media listed overseas, and set an IPO record at that time with a fundraising amount of US$172 million.
```

What is the primary source of funding for this project?
```
Account from the company.
```

What other projects/ecosystem stakeholders is this project associated with?
```
This has nothing to do with other projects.
```

## Use-case details

Describe the data being stored onto Filecoin
```
Primarily promotional images for events held on the website.
```

Where was the data in this dataset sourced from?
```
It comes from materials provided by our company and materials uploaded by users themselves.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://drive.google.com/drive/folders/1bkSUy30PPxJ68QKtbPLcbiW8x8EmE0DR?usp=sharing
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes
```

What is the expected retrieval frequency for this data?
```
Anyone interested in our brand or products can open it to view.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
permanent
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Asia
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
We will use both online and offline transfers.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
Choose a storage provider that has deep pockets and understands project data.
```

How will you be distributing deals across storage providers?
```
We will understand if the storage provider has the relevant experience and sustainability, and based on the analysis we will assign it rationally to different storage providers
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, we have.
```

**Comment by Sunnyiscoming** [comment]
http://www.focusmedia.cn/ is belong to 分众（中国）信息技术有限公司. What's the relationship between 分众（中国）信息技术有限公司 and 山西分众传媒广告有限公司?
How many copies will you store?
What's the relationship between you and organization?
Can you provide more detailed information about other storage providers participated in this program, such as you can list SPs you have contacted with at present?

**Comment by Sunnyiscoming** [comment]
Any update here?

**Comment by Sunnyiscoming** [comment]
Close for no reply. You can resubmit your application if necessary.
