### ISSUE TITLE
[DataCap Application] <Organization>Yongjun Dog Training Center  <Project Name>

### ISSUE THREAD

**Issue by 11019860717** [filecoin-project/filecoin-plus-large-datasets#725]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Yongjun Dog Training Center
- Website / Social Media: http://www.sc-pc.org/index.aspx 
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):  5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):  100TiB
- On-chain address for first allocation: f1rmxeldjfwdxbxaps2borac4frp6or3fums2syji

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Yongjun Dog Training Center was founded in 2008. Over the past 20 years, we developed a systematical method for dog training. Our dog training center covers an area of more than 200 acres with over 40 employees. We have more than 500K followers on Douyin. Other than training the dog in good manner and providing a superior environment for dogs to have fun, we also focus on building up the platform among pet lovers who share their experiences with dogs and promote the dog culture. 

```

What is the primary source of funding for this project?
```
Self-funded
```

What other projects/ecosystem stakeholders is this project associated with?
```
none
```

## Use-case details

Describe the data being stored onto Filecoin
```
Videos that are relevant to dog and training centers. Including surveillant videos on the dog training center, dog training videos, and fun activities that happened to pet owners and pets. 
```

Where was the data in this dataset sourced from?
```
Our company and client/pet owner.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://www.douyin.com/user/MS4wLjABAAAA0uRyqXGId5GVospBVot0e5fMddJatRb_pLVyvapI6O8
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes
```

What is the expected retrieval frequency for this data?
```
Once per week. 
```

For how long do you plan to keep this dataset stored on Filecoin?
```
1-1.5 years 
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Mostly in China region, but can also distribute to other regions. 
``` 

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Offline. 
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
I am looking for storage providers who is in good reputation and are willing to be retrieved. I will send a small amount of deal to each storage provider first and to build up the trust. 
```

How will you be distributing deals across storage providers?
```
I will distribute the data to 10 storage providers, each with an equal amount of Data.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
I know the next step. 
```

**Comment by raghavrmadya** [comment]
can you confirm the surveillance videos are actually public? 5 PiBs is a lot of data. Please shed more light into the DataCap amount request

**Comment by 11019860717** [comment]
Yes I already have 300T raw data.  This contains not only surveillance video, but also dog training video, and every fun moment among dog and dog owners. This is open data that I am willing to share with everyone . I will distribute evenly to 10 storage providers.

**Comment by Sunnyiscoming** [comment]
How many copies will you store?
![image](https://user-images.githubusercontent.com/105098820/189788551-d4520d01-33bf-4a58-b382-03c0ee8a42c8.png)
There are only 155 videos on your douyin channel. Can you share more data samples from other data source?
What's the relationship between you and organization?
Can you provide more detailed information about other storage providers participated in this program, such as you can list SPs you have contacted with at present?

**Comment by 11019860717** [comment]
The video listed in douyin is only a small portion of what we have. I am the business partner of Yongjun. I have contacted with numerous storage provider such as: f0161916, f01870475, f02301, f01072221. I also will find storage providers with good reputation suggested by https://filrep.io/.

**Comment by Sunnyiscoming** [comment]
There are only 155 videos on your douyin channel. Can you share more data samples from other data source?
What's the relationship between you and organization?

**Comment by Sunnyiscoming** [comment]
Any update here?

**Comment by 11019860717** [comment]
https://user-images.githubusercontent.com/111629549/192972465-f915234f-a850-492e-8b6f-92ce754d185d.mov


https://user-images.githubusercontent.com/111629549/192972512-c632f27f-6fed-42f6-8854-caa8fe3ca727.mov


https://user-images.githubusercontent.com/111629549/192972553-fa297cf7-890c-4844-b492-dcd1c24325b9.mov

https://user-images.githubusercontent.com/111629549/192972658-a0ce16e8-e0c6-486a-b1c8-b2da0414605c.mov


https://user-images.githubusercontent.com/111629549/192972770-7e1f7f6f-7692-4ff4-99de-b833ee45583d.MOV

**Comment by 11019860717** [comment]
[归档.zip](https://github.com/filecoin-project/filecoin-plus-large-datasets/files/9672383/default.zip)

**Comment by raghavrmadya** [comment]
Hi, thanks for your response. The community is still unsure of your request. Can you come to the Trust and Transparency WG  call happening next Tuesday at 8:30 am PST and 5:30 pm PST. You can also pre-record a video if that is better.

**Comment by Sunnyiscoming** [comment]
The total amount of data you have is far more than 300T. Why you apply for 5 PB?

**Comment by Sunnyiscoming** [comment]
Any update here?

**Comment by 11019860717** [comment]
It has been 2 months since I applied. What are the questions that remain unclear?  I can answer one by one. Also, can you link me to videos from other applicants so I can use them as a template.

**Comment by Sunnyiscoming** [comment]
> The total amount of data you have is far more than 300T. Why you apply for 5 PB?
No answer to this question.

**Comment by 11019860717** [comment]
Because 5PiB is the maximum number I can apply in one application. If it goes well, I might decide to apply more in the future.

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 100TiB

**Client address**

>f1rmxeldjfwdxbxaps2borac4frp6or3fums2syji

**Comment by xingjitansuo** [comment]
Interesting project. I would love to give it a try for the first time.

**Comment by 1ane-1** [comment]
Could you send an email to filplus-app-review@fil.org with your official domain in order to confirm your identity?

**Comment by Sunnyiscoming** [comment]
Hey @11019860717  , if you still want to apply for datacap, you can ask notaries to do client due diligence in slack channel. https://app.slack.com/client/TEHTVS1L6/C036JKD8NVA/thread/C03BG1MNQ4T-1673888660.823499

**Comment by Chuangshi1** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebfxotm7mheks4lhbgnq6inj2p6fw2adiamwrcvmbfzkct7rj22fk 
#### Address 
> f1rmxeldjfwdxbxaps2borac4frp6or3fums2syji
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1mdk7s2vntzm6hu35yuo6vjubtrpfnb2awhgvrri
#### Id
> 78cc47b9-b85a-432d-b3da-47951328e712
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebfxotm7mheks4lhbgnq6inj2p6fw2adiamwrcvmbfzkct7rj22fk

**Comment by NiwanDao** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaiqt6y44w26e5d5mw4tb6wshbkpkeco7jnat443qqpsn7b6kf7ws 
#### Address 
> f1rmxeldjfwdxbxaps2borac4frp6or3fums2syji
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1a2lia2cwwekeubwo4nppt4v4vebxs2frozarz3q
#### Id
> 78cc47b9-b85a-432d-b3da-47951328e712
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaiqt6y44w26e5d5mw4tb6wshbkpkeco7jnat443qqpsn7b6kf7ws

**Comment by 11019860717** [comment]
Hello fil-gov team @simonkim0515 , Due to technical difficulties encountered in the past, there has been a delay in distributing the data to SP. However, I have now overcome the obstacles and am ready to commence the data distribution process. Please assist me in reopening this issue.
