### ISSUE TITLE
[DataCap Application]ZC Interactive

### ISSUE THREAD

**Issue by zhongcanhudong** [filecoin-project/filecoin-plus-large-datasets#732]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: ZC Interactive
- Website / Social Media:http://www.zhongcanhd.com/index.html
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):3 PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):200TiB
- On-chain address for first allocation:

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
ZC Interactive is a company that integrates integrated communications, brand PR, content marketing, e-commerce direct broadcasting, Internet advertising, platform technology development, digital rights, and Netflix incubation.
It is a company engaged in the flow economy industry, which integrates integrated broadcasting, brand public relations, content marketing, e-commerce direct broadcasting, Internet advertising, platform technology development, digital publishing and Netflix incubation. Zhongcan Interactive and its subsidiaries are currently engaged in a wide range of business activities from e-commerce to social media, from graphics to short video to digital media.
from e-commerce to social networking, from graphics to short video to live broadcasting, from traditional branding to Internet advertising, from digital publishing to net-celebrity incubation.
It is one of the largest enterprises in Jiangxi province with traffic economy as its core business. Currently, the company is operating in Beijing, Shanghai, Guangzhou, Shenzhen, Hangzhou
We have set up subsidiaries in Beijing, Shanghai, Guangzhou, Shenzhen, Hangzhou, Chengdu, Nanchang and other places to lay out business teams, and the group has more than 1,300 full-time employees.
```

What is the primary source of funding for this project?
```
From our live sales
```

What other projects/ecosystem stakeholders is this project associated with?
```
no
```

## Use-case details

Describe the data being stored onto Filecoin
```
Mainly videos shot by our company for Netflix
```

Where was the data in this dataset sourced from?
```
Our own company
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
Please answer here.
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
yes
```

What is the expected retrieval frequency for this data?
```
Usually once a year
```

For how long do you plan to keep this dataset stored on Filecoin?
```
Permanent
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
China
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
offline only
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
miners in Shanghai and Shenzhen
```

How will you be distributing deals across storage providers?
```
50% per family
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, we want the community to get more people involved
```

**Comment by raghavrmadya** [comment]
No data samples. Please submit a new application with all fields complete.
