### ISSUE TITLE
[DataCap Application] Broadcast Media

### ISSUE THREAD

**Issue by Raymondwe** [filecoin-project/filecoin-plus-large-datasets#734]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Shanghai Guang Chuan Culture Media Group Co.
- Website / Social Media:www.gctvmedia.com
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):4PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):150TiB
- On-chain address for first 
allocation:f1awmj3uftquu67bkf5mde4ay7mu5i2kapn2b2njy

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Broadcast Group is a cultural industry group driven by technological innovation and artistic innovation, headquartered in Shanghai, China.
After more than ten years of deep cultivation in the industry, it has now formed a full industry chain group of companies that spans online and offline industry operations and covers three major sectors: film and television, media, and cultural tourism.
```

What is the primary source of funding for this project?
```
Our own and partners
```

What other projects/ecosystem stakeholders is this project associated with?
```
none
```

## Use-case details

Describe the data being stored onto Filecoin
```
Datasets of movies and media videos (promos, documentaries, feature films, etc.) and footage generated by brand operations
```

Where was the data in this dataset sourced from?
```
Data from the company's business and brand operations
Ltd. is dedicated to the integrated service of Chinese cultural tourism IP from investment to planning, from product design to destination operation; to the full media operation service of the unification of corporate brand quality, efficiency and marketing; to the digital art service of film and television special effects, 4D light show, night tour, digital exhibition and meta-universe.
Over the years, the company has obtained many research and development achievements, independent intellectual property rights and first-class night tour copyrights as well as film and television special effects patent technology, and has won many awards at home and abroad. With an international team, the Group empowers Chinese culture with technology and contributes to the revival of Chinese traditional culture with a global vision.

```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://drive.google.com/file/d/1DBaRfxHb9SN_DfyxA-SdppeRlatINMjE/view?usp=sharing
https://drive.google.com/file/d/1dpvSToAvGLMLRGsl1RWTARfq3DZ6LM2h/view?usp=sharing
https://drive.google.com/file/d/132mSKANxpVF69WyrYsXXHV1PLfS6W9N-/view?usp=sharing

```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes.
```

What is the expected retrieval frequency for this data?
```
Once a year
```

For how long do you plan to keep this dataset stored on Filecoin?
```
More than three years
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Asia and surrounding areas
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Yes, by offline transfer
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We plan to select a number of suppliers who can provide services reliably and consistently
```

How will you be distributing deals across storage providers?
```
We will allocate an equal share to high quality storage providers. In addition, each will not be allocated more than 20% of our data volume.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, we want to close the deal as soon as possible
```

**Comment by Sunnyiscoming** [comment]
What's the relationship between you and organization? 
How many copies will you store?
Can you provide more detailed information about other storage providers participated in this program, such as you can list SPs you have contacted with at present?
Could you send an email to filplus-app-review@fil.org with your official domain in order to confirm your identity? Email name should includes the issue id #734.

**Comment by Sunnyiscoming** [comment]
Any update here?

**Comment by Sunnyiscoming** [comment]
Close for no reply. You can resubmit your application if necessary.
