### ISSUE TITLE
[DataCap Application] <Shenzhen Hongyuantai Information Technology Co., Ltd.>

### ISSUE THREAD

**Issue by cuichengshuai** [filecoin-project/filecoin-plus-large-datasets#735]

**Comment by cuichengshuai** [comment]
Thank you for checking, I am full of information about the project.

**Comment by Sunnyiscoming** [comment]
![image](https://user-images.githubusercontent.com/105098820/189796641-729762c4-3a45-4bb2-92e4-e6b7914c0f94.png)
![image](https://user-images.githubusercontent.com/105098820/189796686-c47e0e4b-a099-4d95-a341-a144bec5af5e.png)
Website and data samples link do not work. Please check it.

**Comment by cuichengshuai** [comment]
Sorry! Here is the new link：
Link: https://pan.baidu.com/s/1y5ivczeThf71yxabA1J2BA 
Extraction code: j868

**Comment by Sunnyiscoming** [comment]
How about website?

**Comment by Sunnyiscoming** [comment]
Hope you can provide the composition of your 3PB data and provide sufficient data samples corresponding to the components. How many copies will you store?

**Comment by cuichengshuai** [comment]
Action camera application in the field of aerial photography presents stunning visual effects and records wonderful moments，link：https://pan.baidu.com/s/1hFN5Rr4Gn_GNuwIpVnZcuA 
Extraction code：yq2v

**Comment by cuichengshuai** [comment]
The ultimate picture quality records the driving traffic information for safety，
link：https://pan.baidu.com/s/14OWoGLxNGkcAS78dBYh0xw 
Extraction code：wijq

**Comment by cuichengshuai** [comment]
I have joined the company for three years and am currently in charge of the software development team, committed to providing users with a stable and high experience. Storage providers I know，su as Arweave, Storj ,etc.

**Comment by Sunnyiscoming** [comment]
![image](https://user-images.githubusercontent.com/105098820/191646925-6dfb9fcc-4399-4076-b3bf-5fecaec15a84.png)

**Comment by Sunnyiscoming** [comment]
Hope you can provide the composition of your 3PB data and provide sufficient data samples corresponding to the components. How many copies will you store?

**Comment by cuichengshuai** [comment]
> * WWW.hongyuantai.com

Sorry，The correct URL is http://www.hongyt.com/

**Comment by cuichengshuai** [comment]
The development data for a single product mainly includes the records of the product images in the development process, and the image records of the improved version, including the records of different scenes such as daytime, noon, afternoon, evening, night, cloudy, sunny, rainy, etc., including a large amount of data.
And we develop high-end true 4K images, which will take up a lot of space. Secondly, the image stabilization part is optimized, and the timely archiving and recording will help the project development and improvement. We use Sony's high-end image sensors, such as IMX335, IMX415, IMX386, etc., and different effects need to be recorded.Our data storage only needs to be archived in 6 copies, which are divided into R&D end, APP end and client access end.
This link contains sample stabilized videos, morning, noon, afternoon and evening videos 
链接：https://pan.baidu.com/s/1A_TQ8NgASobl3AT14cs9Kw 
提取码：lega

**Comment by Sunnyiscoming** [comment]
Storage providers I know，su as Arweave, Storj ,etc.
Can you list the nodes of SPs you will cooperate with?

**Comment by cuichengshuai** [comment]
Okay,the node of SPs such as f0143361 ，f0154039,  f095970 and so on.

**Comment by cuichengshuai** [comment]
Okay, the nodes of SPs such as f01412953, f01152097，f01140256，f014768，f07998，f018501.

**Comment by Sunnyiscoming** [comment]
Could you send an email to filplus-app-review@fil.org with your official domain in order to confirm your identity? Email name should includes the issue id #735.

**Comment by cuichengshuai** [comment]
Hello, sir, please check the email.



崔成帅
深圳弘源泰信息技术有限公司
地址：深圳市福田区车公庙泰然六路雪松大厦B座11B
手机：18638768704
***@***.***
QQ ：924102391
 
From: Sunnyiscoming
Date: 2022-10-05 17:02
To: filecoin-project/filecoin-plus-large-datasets
CC: cuichengshuai; Author
Subject: Re: [filecoin-project/filecoin-plus-large-datasets] [DataCap Application] <Organization> - <Project Name> (Issue #735)
Could you send an email to ***@***.*** with your official domain in order to confirm your identity? Email name should includes the issue id #735.

**Comment by cuichengshuai** [comment]
![image](https://user-images.githubusercontent.com/111625845/194702418-7cd842ca-b89c-4dcf-aa2a-df4e917a2bd0.png)
I sent an email, please check.

**Comment by Sunnyiscoming** [comment]
Email received.

**Comment by raghavrmadya** [comment]
Hi, how much data do you have today and who are your customers? You say the data being generated is public but there isn't enough evidence that this is an open dataset. You might have to apply for LDN Exception

**Comment by cuichengshuai** [comment]
Hello, there is about 1P data now. The company is adding data every day. My customer is SP. At present, we are still negotiating. We will put the data that our company can display to the outside on the filecoin network.

**Comment by cuichengshuai** [comment]
Our SP nodes are f01412953, f01152097, f01140256, f014768, f07998, f018501, etc. We have a lot of public data. We are adding data every day. This is our data case. Please check it. In addition, we look forward to your early approval of our request.

**Comment by cuichengshuai** [comment]
Hello, our company is a video imaging company, which is divided into design department, operation department, sales department, production department, after-sales service department, etc.
The company's main business is tachograph, sports camera and PTZ camera. Our company's data consists of the following parts:
1. Product design and R&D data
2. Publicity articles, videos, posters, PPT data
3. Sales data include the environment, video and performance report data of the company's stores, and offline activity data
4. Product display data include product image effect promotion and product effect display data
5. Factory data includes materials, procurement, processing, workers' commuting and canteen data
6. After sales data include user research, use experience and product feedback data
Among them, some manuscripts of product design, product publicity data, sales data, product display data, including part of factory production data and part of after-sales data are public, and can be completely stored on the Filecoin network.
Every company, no matter how long it has been established, its data are divided into public data and private data. Our company has been established for 7 years, with nearly 100 people, and has its own factory. We are generating data every day. Since we have been established for a long time, we believe that our public data must be much larger than those of companies with a shorter time.
Sincerely, please pass our request.

**Comment by Sunnyiscoming** [comment]
Currently, large datasets are for completely open data, so if you want to store corporate data with private data, you can apply for FIL-E. You can use the slack channel for more information, https://app.slack.com/client/TEHTVS1L6/C03MHVAABFV/thread/C03BG1MNQ4T-1663713267.192989

**Comment by cuichengshuai** [comment]
I don't understand why you think we only have private data, not public data?
I think this is impossible for any enterprise.
Finally, it is a prerequisite for us to store private data on the Filecoin network to experience the storage of public data on the Filecoin network.
If you reject our desire to store public data, how can we trust you to store private data?

**Comment by cuichengshuai** [comment]
I don't understand why you think we only have private data, not public data?
I think this is impossible for any enterprise.
Finally, it is a prerequisite for us to store private data on the Filecoin network to experience the storage of public data on the Filecoin network.
If you reject our desire to store public data, how can we trust you to store private data?

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 3.5PiB

**Expected weekly DataCap usage rate**

> 100TiB

**Client address**

>f1cpaleftrriwpunk3jolz4v57ld3uoq2egv543za
