### ISSUE TITLE
[DataCap Application] Beijing Yibo Technology Co., Ltd.

### ISSUE THREAD

**Issue by YiboTechnology** [filecoin-project/filecoin-plus-large-datasets#74]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Beijing Yibo Technology Co., Ltd.
- Website / Social Media: www.bjyibo.org
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 1 PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 60TiB
- On-chain address for first allocation: f3q3eysweh273pwygu27yllyafljznqewpxwlrc7jdaugrpvhmrcnxmkn43wkctxalcg3z42zxas2hinsftgva

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Beijing Yibo Technology Co., Ltd. focus on development and production of AI intelligent live broadcasting equipment. Through intelligent green screen replacement technology, VR live scenes of virtual reality are created, and outdoor live broadcasting and distribution can be carried out quickly through 5G matrix communication. And real-time cloud collection, strip removal, interactive live broadcast, e-commerce push and other supporting services. To create a one-stop network red live base facilities. Quickly complete the business model of interactive e-commerce in the new era and build a virtual reality communication platform with users. So as to build a new generation of network red belt goods new ecology.
```

What is the primary source of funding for this project?
```
The company.
```

What other projects/ecosystem stakeholders is this project associated with?
```
There is no other.
```

## Use-case details

Describe the data being stored onto Filecoin.
```
Pictures, documents, Max files, etc.
```

Where was the data in this dataset sourced from?
```
Internet open data, enterprise docking data and independent analysis data, such as decoration related documents.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
[YIBO.zip](https://github.com/filecoin-project/filecoin-plus-large-datasets/files/7393723/YIBO.zip)
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes, we confirm that.
```

What is the expected retrieval frequency for this data?
```
These data are archived historical data, so retrieval frequency is low.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
Permanent storage.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
We tend to choose China.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Because we have a larger amount of data, we give preference to offline storage.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
Storage providers are required to ensure integrity and security of stored data and data uploading efficiency. Storage nodes with high computing power are preferred.
```

How will you be distributing deals across storage providers?
```
We will divide the data into different parts according to different scenarios and then store them to different storage providers. This is more conducive to the convenience of our later data retrieval.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
We have classified all the data we need to store and placed them on different hard disks. After the application is successful, we can contact the powerful storage provider. No more help is needed for now.
```

**Comment by swatchliu** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecqietsqdlcfkawvbi3k6hdpnks7ftlb4z6mhef4ek23xrgnpgdbo 
#### Address 
> f3q3eysweh273pwygu27yllyafljznqewpxwlrc7jdaugrpvhmrcnxmkn43wkctxalcg3z42zxas2hinsftgva
#### Datacap Allocated
> 30TiB
#### Signer Address
> f1yh6q3nmsg7i2sys7f7dexcuajgoweudcqj2chfi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecqietsqdlcfkawvbi3k6hdpnks7ftlb4z6mhef4ek23xrgnpgdbo

**Comment by MRJAVAZHAO** [comment]
Happy to support.

**Comment by MRJAVAZHAO** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceas5i77dg5g3eppnzvt7ln623446bkidgia66rump42v4nzi3g4m2 
#### Address 
> f3q3eysweh273pwygu27yllyafljznqewpxwlrc7jdaugrpvhmrcnxmkn43wkctxalcg3z42zxas2hinsftgva
#### Datacap Allocated
> 30TiB
#### Signer Address
> f14gme3f52prtyzk6pblogrdd6b6ivp4swc6qmesi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceas5i77dg5g3eppnzvt7ln623446bkidgia66rump42v4nzi3g4m2

**Comment by galen-mcandrew** [comment]
Previous website: http://yb.lvjinhui.cn/

Replacing tags that were changed with parent comment edits.

**Comment by YiboTechnology** [comment]
@IreneYoung We plan to choose less than 30 miners.

**Comment by Reiers** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceae2dd4vsi54c7dyu4g4atevgbqnzfzhb7s6b7objs7s5rhbfeiq4 
#### Address 
> f3q3eysweh273pwygu27yllyafljznqewpxwlrc7jdaugrpvhmrcnxmkn43wkctxalcg3z42zxas2hinsftgva
#### Datacap Allocated
> 60.00TiB
#### Signer Address
> f1oz43ckvmtxmmsfzqm6bpnemqlavz4ifyl524chq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceae2dd4vsi54c7dyu4g4atevgbqnzfzhb7s6b7objs7s5rhbfeiq4

**Comment by cryptowhizzard** [comment]
Given the spirit of LDN i won't sign on this one.

LDN is meant to be distributed globally and not only in China.

"In which geographies (countries, regions) do you plan on making storage deals? Mainland China."

Please let me know if you intend to store globally and to who. Then i will sign.

**Comment by s0nik42** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebf4am5gr6bwcd7q5jilacv6dr7zjli3daedx2cui66w4duusl7oe 
#### Address 
> f3q3eysweh273pwygu27yllyafljznqewpxwlrc7jdaugrpvhmrcnxmkn43wkctxalcg3z42zxas2hinsftgva
#### Datacap Allocated
> 60.00TiB
#### Signer Address
> f1wxhnytjmklj2czezaqcfl7eb4nkgmaxysnegwii
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebf4am5gr6bwcd7q5jilacv6dr7zjli3daedx2cui66w4duusl7oe

**Comment by YiboTechnology** [comment]
@Reiers @s0nik42 @swatchliu Please approve our application.

**Comment by swatchliu** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedtoztir4kphkxlvhlp7t5mpy4xx7binrielg5ljvm4cclns2qpyo 
#### Address 
> f3q3eysweh273pwygu27yllyafljznqewpxwlrc7jdaugrpvhmrcnxmkn43wkctxalcg3z42zxas2hinsftgva
#### Datacap Allocated
> 120.00TiB
#### Signer Address
> f1yh6q3nmsg7i2sys7f7dexcuajgoweudcqj2chfi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedtoztir4kphkxlvhlp7t5mpy4xx7binrielg5ljvm4cclns2qpyo

**Comment by XnMatrixSV** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacea325xiiuauxbn2wa67mq26gejs45ha6522kuoxvszsrhrdwzfnw4 
#### Address 
> f3q3eysweh273pwygu27yllyafljznqewpxwlrc7jdaugrpvhmrcnxmkn43wkctxalcg3z42zxas2hinsftgva
#### Datacap Allocated
> 240.00TiB
#### Signer Address
> f1yuz2twsllparyfqwslfiuxrc5wj4mfiflvnsw6a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacea325xiiuauxbn2wa67mq26gejs45ha6522kuoxvszsrhrdwzfnw4

**Comment by swatchliu** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedkxm6dqxhlvpkp3ukcls7twap4e5edenv6xqtok64p4xljrc3vc6 
#### Address 
> f3q3eysweh273pwygu27yllyafljznqewpxwlrc7jdaugrpvhmrcnxmkn43wkctxalcg3z42zxas2hinsftgva
#### Datacap Allocated
> 240.00TiB
#### Signer Address
> f1yh6q3nmsg7i2sys7f7dexcuajgoweudcqj2chfi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedkxm6dqxhlvpkp3ukcls7twap4e5edenv6xqtok64p4xljrc3vc6

**Comment by MRJAVAZHAO** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceazksm3guldohn6ugbod42pmvrjm7stg6s7wzimtnkvecdvecw2rc 
#### Address 
> f3q3eysweh273pwygu27yllyafljznqewpxwlrc7jdaugrpvhmrcnxmkn43wkctxalcg3z42zxas2hinsftgva
#### Datacap Allocated
> 480.00TiB
#### Signer Address
> f14gme3f52prtyzk6pblogrdd6b6ivp4swc6qmesi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceazksm3guldohn6ugbod42pmvrjm7stg6s7wzimtnkvecdvecw2rc

**Comment by swatchliu** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceduy2gbdvyvhb3ncm4z2jent7otoedqlnhf7uehnt2wqna342ymbm 
#### Address 
> f3q3eysweh273pwygu27yllyafljznqewpxwlrc7jdaugrpvhmrcnxmkn43wkctxalcg3z42zxas2hinsftgva
#### Datacap Allocated
> 480.00TiB
#### Signer Address
> f1yh6q3nmsg7i2sys7f7dexcuajgoweudcqj2chfi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceduy2gbdvyvhb3ncm4z2jent7otoedqlnhf7uehnt2wqna342ymbm

**Comment by MRJAVAZHAO** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaa7vbaiw7tky4j6h5bqj5zf4j6qcfbc4o74gd7gsk76c3j5acfq6 
#### Address 
> f3q3eysweh273pwygu27yllyafljznqewpxwlrc7jdaugrpvhmrcnxmkn43wkctxalcg3z42zxas2hinsftgva
#### Datacap Allocated
> 94.00TiB
#### Signer Address
> f14gme3f52prtyzk6pblogrdd6b6ivp4swc6qmesi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaa7vbaiw7tky4j6h5bqj5zf4j6qcfbc4o74gd7gsk76c3j5acfq6

**Comment by PluskitOfficial** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedan5gvvc76frehvsgrzy4l7h3swzb3ovgny4mmhdtthybso5jo54 
#### Address 
> f3q3eysweh273pwygu27yllyafljznqewpxwlrc7jdaugrpvhmrcnxmkn43wkctxalcg3z42zxas2hinsftgva
#### Datacap Allocated
> 94.00TiB
#### Signer Address
> f1tgnlhtcmhwipfm7thsftxhn5k52velyjlazpvka
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedan5gvvc76frehvsgrzy4l7h3swzb3ovgny4mmhdtthybso5jo54

**Comment by BigD-Exchange** [comment]
@YiboTechnology Hi! Great to see you have gotten approval for DataCap. If you are looking for storage providers to store these data, please visit #bigdata-exchange on Filecoin Slack or reply here.
