### ISSUE TITLE
[DataCap Application] Earth Photography

### ISSUE THREAD

**Issue by Guerreroylo** [filecoin-project/filecoin-plus-large-datasets#745]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Guangzhou Dadi Greenfield Photography Design Co.
- Website / Social Media:www.dadiluye.com
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):3PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):100TiB
- On-chain address for first allocation:f1de4p43ytr3cqqlua7y36hy3iedviu4wsss4kflq

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Ltd. is a well-known domestic commercial photography agency, the first brand in China's photography business, vice president of the Guangdong Provincial Photography Industry Association - Electric Business Photography Professional Committee. Dadi Photography has nine photography bases nationwide, with a total studio area of more than 6,000 square feet, and its Guangzhou headquarters is located in Haizhu Creative Industry Park in Haizhu District, which is a large comprehensive e-commerce photography company

```

What is the primary source of funding for this project?
```
The company's business revenue
```

What other projects/ecosystem stakeholders is this project associated with?
```
Related to the company's partners
```

## Use-case details

Describe the data being stored onto Filecoin
```
Sample shots of products, models, data mainly in the form of videos, pictures.
```

Where was the data in this dataset sourced from?
```
With a core team of more than 100 professional photographers and technicians, Dazhi Photography is equipped with world-class photography equipment and a full set of Apple computer system as hardware facilities. In terms of software, internal management is carried out in accordance with the requirements of industrialization and scale development, from business acceptance to a team of experienced professional photographers, makeup artists to a team of designers, and long-term and stable cooperation with more than 300 models of different styles at home and abroad.

```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
http://www.dadiluye.com/picv_1180.html
http://www.dadiluye.com/picv_516.html
http://www.dadiluye.com/taobao.htm
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes.
```

What is the expected retrieval frequency for this data?
```
As per actual demand
```

For how long do you plan to keep this dataset stored on Filecoin?
```
1-3 years
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
China
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Yes, by offline transfer
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We are willing to work with any supplier who has the storage conditions and experience
```

How will you be distributing deals across storage providers?
```
We will allocate an equal share to high quality storage providers. In addition, each vendor will not be allocated more than 20% of our data volume.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, we have
```

**Comment by raghavrmadya** [comment]
A reverse image search shows pictures on the website are not real. Flagged as fake. Please come to a governance call if you would like to dispute. Thanks.

**Comment by Guerreroylo** [comment]
[image: 1661504954443.jpg]
Hi, our works have the organization's logo on them, this is our previous
website http://www.dadiluye.com/old/ , how do we contact the team to solve
this problem

Raghav Rmadya ***@***.***> 于2022年8月26日周五 02:02写道：
