### ISSUE TITLE
[DataCap Application] Dongguan Amy Aimen Clothing Co., Ltd.

### ISSUE THREAD

**Issue by aimiaimen** [filecoin-project/filecoin-plus-large-datasets#747]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Dongguan Amy Aimen Clothing Co., Ltd.
- Website / Social Media:http://www.aimiaimen.com/index.html
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):2PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):150TiB
- On-chain address for first allocation:f1rty5jcavhfyck5evmji2gotqv4w274g35qw3eai

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Founded in 2002, the company owns the "Aimiaimen" children's clothing brand, mainly engaged in the design, production and sales of children's clothing and accessories as one of the modern brand apparel enterprises.
```

What is the primary source of funding for this project?
```
Proceeds from bulk sales of products.
```

What other projects/ecosystem stakeholders is this project associated with?
```
Please answer here.
```

## Use-case details

Describe the data being stored onto Filecoin
```
Because there are a lot of new clothes every season, a lot of music videos for clothes and photos need to be stored.
```

Where was the data in this dataset sourced from?
```
The company is in demand for photography in the process of brand operation and merchandising.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://drive.google.com/drive/folders/1V5Gf2W_dOogK-FF3A4iHxOItTJ2fyecx?usp=sharing
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes.
```

What is the expected retrieval frequency for this data?
```
Anyone interested in our brand can open it and check it out.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
Permanently stored on Filcoin.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
China.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
We will use both online transfer and offline transfer.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We plan to select a number of miners who can provide services reliably and consistently.
```

How will you be distributing deals across storage providers?
```
We will distribute them equally to each storage provider.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, we want to close the deal as soon as possible.
```

**Comment by Sunnyiscoming** [comment]
What's the relationship between you and organization? 
How many copies will you store?
Can you provide more detailed information about other storage providers participated in this program, such as you can list SPs you have contacted with at present?
Could you send an email to filplus-app-review@fil.org with your official domain in order to confirm your identity? Email name should includes the issue id #747.

**Comment by aimiaimen** [comment]
1. I am one of the shareholders of the company and our application is an act of the whole company.
2. We are just making a backup on fil's network, the exact number of copies is determined according to the cost.
3. We are currently in contact with SP including: f01038389/f0469055/f0120057/f090387 etc.

The company email has been sent, please check it!

**Comment by Sunnyiscoming** [comment]
Not receiving any email name include #747, please check it.
Why you choose these sps, they are unreachable in https://filrep.io/.

**Comment by Sunnyiscoming** [comment]
Any update here?

**Comment by Sunnyiscoming** [comment]
Close for no reply. You can resubmit your application if necessary.
