### ISSUE TITLE
[DataCap Application]Meizhai Technology

### ISSUE THREAD

**Issue by MeizhaiTechnology** [filecoin-project/filecoin-plus-large-datasets#75]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Meizhai Technology
- Website / Social Media: www.decor.ai
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 1.5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100TiB
- On-chain address for first allocation: f3skkellc7wegakh2blqeu4kkrlzuqy2siymwli7sec6eq77c2v4kzgz5ozgnasjl5r52ckameba5kds7hdjda

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Meizhai Technology (Beijing) Co., LTD establlished in 2017. We are committed to creating a set of immersive VR furniture and home decoration experience services, for customers according to the needs, house type, style, hobbies, dynamic adaptation of decoration methods and recommended corresponding home matching. And immersive experience through VR display devices. So that customers can intuitively experience and feel the effect after the decoration through the virtual space, so as to help home furnishing brands and retailers to achieve offline and online double integration of fast experience to retail mode. And for the virtual scene virtual sample, speed scene experience, intelligent recommendation and other new retail service modes. Finally, an online and offline integrated home smart shopping platform will be built for users, and a new home retail ecosystem will be built.
```

What is the primary source of funding for this project?
```
The company undertake this part of the spending.
```

What other projects/ecosystem stakeholders is this project associated with?
```
There is no other
```

## Use-case details

Describe the data being stored onto Filecoin
```
Pictures, documents, Max files, etc.
```

Where was the data in this dataset sourced from?
```
Internet open data, enterprise docking data and independent analysis data, such as decoration related documents.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
Please copy the link and enter the code to view the data samples. The data samples are mainly the decoration pictures.
https://pan.baidu.com/s/1fvpzDcnlsNYdVReRoKR7_w 
Code: qwer
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes, we confirm that it is a public dataset.
```

What is the expected retrieval frequency for this data?
```
These data are archived historical data, so retrieval frequency is low.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
Permanent storage.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
We would like to choose China.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Because we have a larger amount of data, we give preference to offline storage
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
Storage providers are required to ensure integrity and security of stored data and data uploading efficiency. Storage nodes with high computing power are preferred.
```

How will you be distributing deals across storage providers?
```
We will divide the data into different parts according to different scenarios and then store them to different storage providers. This is more conducive to the convenience of our later data retrieval.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
We have classified all the data we need to store and placed them on different hard disks. After the application is successful, we can contact the powerful storage provider. No more help is needed for now.
```

**Comment by Reiers** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedql3plolrymhhwaohpmpa3wp6zknierpcb3asazxzcxjnfikuwfi 
#### Address 
> f3skkellc7wegakh2blqeu4kkrlzuqy2siymwli7sec6eq77c2v4kzgz5ozgnasjl5r52ckameba5kds7hdjda
#### Datacap Allocated
> 50TiB
#### Signer Address
> f1oz43ckvmtxmmsfzqm6bpnemqlavz4ifyl524chq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedql3plolrymhhwaohpmpa3wp6zknierpcb3asazxzcxjnfikuwfi

**Comment by dkkapur** [comment]
https://filfox.info/en/message/bafy2bzacedq3qmhjr7waxkck5femiokw6rg4cbrkruof2piiuhksd3kenwzza looks like this was approved

**Comment by fabriziogianni7** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedq3qmhjr7waxkck5femiokw6rg4cbrkruof2piiuhksd3kenwzza
#### Address 
> f3skkellc7wegakh2blqeu4kkrlzuqy2siymwli7sec6eq77c2v4kzgz5ozgnasjl5r52ckameba5kds7hdjda
#### Datacap Allocated
> 50TiB
#### Signer Address
> f1yuz2twsllparyfqwslfiuxrc5wj4mfiflvnsw6a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedq3qmhjr7waxkck5femiokw6rg4cbrkruof2piiuhksd3kenwzza

**Comment by fabriziogianni7** [comment]
added the comment to make it readable from the bot. cc @dkkapur @galen-mcandrew @XnMatrixSV

**Comment by KodaRobotDog** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaf6fagluebthgfzfil5wd5angpq2uotbzqigjvsr3exydhwplz5c 
#### Address 
> f3skkellc7wegakh2blqeu4kkrlzuqy2siymwli7sec6eq77c2v4kzgz5ozgnasjl5r52ckameba5kds7hdjda
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1jyalts5uhtmp5sbbssse23toshvsqbbtjgukm5a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaf6fagluebthgfzfil5wd5angpq2uotbzqigjvsr3exydhwplz5c

**Comment by IreneYoung** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedbu3ylpfdfigagz7aydpdxbwlhammh3uey6bhayws3mmj2rkbp2u 
#### Address 
> f3skkellc7wegakh2blqeu4kkrlzuqy2siymwli7sec6eq77c2v4kzgz5ozgnasjl5r52ckameba5kds7hdjda
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1d4gmpqz3execjj2wvrxuuhvbms5mzh7t7yqrviq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedbu3ylpfdfigagz7aydpdxbwlhammh3uey6bhayws3mmj2rkbp2u

**Comment by XnMatrixSV** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceajw2wbmwfwy7bk4kg2u7f726mdpg5x2eamrzs5sf5ic2vzsptyvq 
#### Address 
> f3skkellc7wegakh2blqeu4kkrlzuqy2siymwli7sec6eq77c2v4kzgz5ozgnasjl5r52ckameba5kds7hdjda
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1yuz2twsllparyfqwslfiuxrc5wj4mfiflvnsw6a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceajw2wbmwfwy7bk4kg2u7f726mdpg5x2eamrzs5sf5ic2vzsptyvq

**Comment by swatchliu** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaqqmlhqexrcraj7busahmwnreo7nr4fuxjmehswxu6likfwhcphm 
#### Address 
> f3skkellc7wegakh2blqeu4kkrlzuqy2siymwli7sec6eq77c2v4kzgz5ozgnasjl5r52ckameba5kds7hdjda
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1yh6q3nmsg7i2sys7f7dexcuajgoweudcqj2chfi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaqqmlhqexrcraj7busahmwnreo7nr4fuxjmehswxu6likfwhcphm

**Comment by Akkeeeeee** [comment]
Hi, @MeizhaiTechnology  Would you like to share your rootCID with us?

**Comment by MeizhaiTechnology** [comment]
@Akke-1 Please send your peer id to me. I will whitelist you for data retrieval.

**Comment by swatchliu** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb52etmcyc3s3crzfz4k4tl5kvsaufmsqk2hibzr5l4wcvjlewdym 
#### Address 
> f3skkellc7wegakh2blqeu4kkrlzuqy2siymwli7sec6eq77c2v4kzgz5ozgnasjl5r52ckameba5kds7hdjda
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1yh6q3nmsg7i2sys7f7dexcuajgoweudcqj2chfi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb52etmcyc3s3crzfz4k4tl5kvsaufmsqk2hibzr5l4wcvjlewdym

**Comment by BigD-Exchange** [comment]
@MeizhaiTechnology Hi! Great to see you have gotten approval for DataCap. If you are looking for storage providers to store these data or have any questions, please visit #bigdata-exchange on Filecoin Slack or reply here. 

We have strong demand from a diverse group of SPs, who are actively looking to onboard more data.

**Comment by filplus-checker** [comment]
## DataCap and CID Checker Report[^1]
 - Organization: `Meizhai Technology`
 - Client: `f3skkellc7wegakh2blqeu4kkrlzuqy2siymwli7sec6eq77c2v4kzgz5ozgnasjl5r52ckameba5kds7hdjda`
### Storage Provider Distribution
The below table shows the distribution of storage providers that have stored data for this client.

If this is the first time a provider takes verified deal, it will be marked as `new`.

For most of the datacap application, below restrictions should apply.
 - Storage provider should not exceed 25% of total datacap.
 - Storage provider should not be storing duplicate data for more than 20%.
 - Storage provider should have published its public IP address.
 - All storage providers should be located in different regions.

⚠️ 25.66% of total deal sealed by [f01840776](https://filfox.info/en/address/f01840776) are duplicate data.

⚠️ 25.29% of total deal sealed by [f01846857](https://filfox.info/en/address/f01846857) are duplicate data.

⚠️ 23.44% of total deal sealed by [f01846877](https://filfox.info/en/address/f01846877) are duplicate data.

⚠️ 62.50% of total deal sealed by [f01880897](https://filfox.info/en/address/f01880897) are duplicate data.

⚠️ 26.89% of total deal sealed by [f01889046](https://filfox.info/en/address/f01889046) are duplicate data.

⚠️ 65.55% of total deal sealed by [f01879880](https://filfox.info/en/address/f01879880) are duplicate data.

⚠️ 89.86% of total deal sealed by [f01885260](https://filfox.info/en/address/f01885260) are duplicate data.

⚠️ 65.54% of total deal sealed by [f01885280](https://filfox.info/en/address/f01885280) are duplicate data.

⚠️ 67.49% of total deal sealed by [f01880894](https://filfox.info/en/address/f01880894) are duplicate data.

⚠️ 79.54% of total deal sealed by [f01845679](https://filfox.info/en/address/f01845679) are duplicate data.

⚠️ [f01845679](https://filfox.info/en/address/f01845679) has unknown IP location.

⚠️ 23.84% of total deal sealed by [f01877862](https://filfox.info/en/address/f01877862) are duplicate data.

⚠️ [f01308862](https://filfox.info/en/address/f01308862) has unknown IP location.

⚠️ 30.65% of total deal sealed by [f0142723](https://filfox.info/en/address/f0142723) are duplicate data.

⚠️ [f0142723](https://filfox.info/en/address/f0142723) has unknown IP location.

⚠️ [f01169692](https://filfox.info/en/address/f01169692) has unknown IP location.

⚠️ [f0883201](https://filfox.info/en/address/f0883201) has unknown IP location.

⚠️ [f0883205](https://filfox.info/en/address/f0883205) has unknown IP location.

⚠️ 28.26% of total deal sealed by [f01851482](https://filfox.info/en/address/f01851482) are duplicate data.

⚠️ [f0883206](https://filfox.info/en/address/f0883206) has unknown IP location.

⚠️ [f01308876](https://filfox.info/en/address/f01308876) has unknown IP location.

⚠️ 21.25% of total deal sealed by [f01852664](https://filfox.info/en/address/f01852664) are duplicate data.

⚠️ 35.44% of total deal sealed by [f01852023](https://filfox.info/en/address/f01852023) are duplicate data.

⚠️ [f01308863](https://filfox.info/en/address/f01308863) has unknown IP location.

⚠️ 28.57% of total deal sealed by [f01852325](https://filfox.info/en/address/f01852325) are duplicate data.

⚠️ [f01387566](https://filfox.info/en/address/f01387566) has unknown IP location.

⚠️ [f01387466](https://filfox.info/en/address/f01387466) has unknown IP location.

⚠️ [f01387599](https://filfox.info/en/address/f01387599) has unknown IP location.

⚠️ [f01387598](https://filfox.info/en/address/f01387598) has unknown IP location.

⚠️ [f01308857](https://filfox.info/en/address/f01308857) has unknown IP location.

⚠️ 30.77% of total deal sealed by [f01387460](https://filfox.info/en/address/f01387460) are duplicate data.

⚠️ [f01387460](https://filfox.info/en/address/f01387460) has unknown IP location.

⚠️ [f01387459](https://filfox.info/en/address/f01387459) has unknown IP location.

⚠️ [f0442383](https://filfox.info/en/address/f0442383) has unknown IP location.

⚠️ [f0142721](https://filfox.info/en/address/f0142721) has unknown IP location.

⚠️ [f01308916](https://filfox.info/en/address/f01308916) has unknown IP location.

⚠️ [f0883202](https://filfox.info/en/address/f0883202) has unknown IP location.

⚠️ [f01308877](https://filfox.info/en/address/f01308877) has unknown IP location.

⚠️ [f01132084](https://filfox.info/en/address/f01132084) has unknown IP location.

⚠️ [f01169691](https://filfox.info/en/address/f01169691) has unknown IP location.

| Provider                                              |                           Location | Total Deals Sealed | Percentage | Unique Data | Duplicate Deals |
| :---------------------------------------------------- | ---------------------------------: | -----------------: | ---------: | ----------: | --------------: |
| [f01840776](https://filfox.info/en/address/f01840776) | Hong Kong, Central and Western, HK |         108.33 TiB |     14.42% |   80.53 TiB |          25.66% |
| [f01846857](https://filfox.info/en/address/f01846857) |                   Osaka, Ōsaka, JP |         106.40 TiB |     14.17% |   79.49 TiB |          25.29% |
| [f01846877](https://filfox.info/en/address/f01846877) |           Singapore, Singapore, SG |          99.97 TiB |     13.31% |   76.53 TiB |          23.44% |
| [f01880897](https://filfox.info/en/address/f01880897) |           Singapore, Singapore, SG |          53.00 TiB |      7.06% |   19.88 TiB |          62.50% |
| [f01889046](https://filfox.info/en/address/f01889046) |              Ashburn, Virginia, US |          52.53 TiB |      6.99% |   38.41 TiB |          26.89% |
| [f01879880](https://filfox.info/en/address/f01879880) |           Singapore, Singapore, SG |          52.44 TiB |      6.98% |   18.06 TiB |          65.55% |
| [f01885260](https://filfox.info/en/address/f01885260) | Hong Kong, Central and Western, HK |          52.09 TiB |      6.94% |    5.28 TiB |          89.86% |
| [f01885280](https://filfox.info/en/address/f01885280) | Hong Kong, Central and Western, HK |          51.97 TiB |      6.92% |   17.91 TiB |          65.54% |
| [f01880894](https://filfox.info/en/address/f01880894) |           Singapore, Singapore, SG |          51.91 TiB |      6.91% |   16.88 TiB |          67.49% |
| [f01845679](https://filfox.info/en/address/f01845679) |                            Unknown |          46.13 TiB |      6.14% |    9.44 TiB |          79.54% |
| [f01877862](https://filfox.info/en/address/f01877862) |                   Seoul, Seoul, KR |          29.95 TiB |      3.99% |   22.81 TiB |          23.84% |
| [f01308862](https://filfox.info/en/address/f01308862) |                            Unknown |           4.57 TiB |      0.61% |    3.73 TiB |          18.45% |
| [f0142723](https://filfox.info/en/address/f0142723)   |                            Unknown |           4.39 TiB |      0.58% |    3.04 TiB |          30.65% |
| [f01169692](https://filfox.info/en/address/f01169692) |                            Unknown |           4.23 TiB |      0.56% |    3.57 TiB |          15.55% |
| [f0883201](https://filfox.info/en/address/f0883201)   |                            Unknown |           3.93 TiB |      0.52% |    3.93 TiB |           0.00% |
| [f0883205](https://filfox.info/en/address/f0883205)   |                            Unknown |           3.92 TiB |      0.52% |    3.92 TiB |           0.00% |
| [f01851482](https://filfox.info/en/address/f01851482) |                   Busan, Busan, KR |           2.88 TiB |      0.38% |    2.06 TiB |          28.26% |
| [f0883206](https://filfox.info/en/address/f0883206)   |                            Unknown |           2.67 TiB |      0.36% |    2.41 TiB |           9.94% |
| [f01308876](https://filfox.info/en/address/f01308876) |                            Unknown |           2.61 TiB |      0.35% |    2.41 TiB |           7.42% |
| [f01852664](https://filfox.info/en/address/f01852664) |           Singapore, Singapore, SG |           2.50 TiB |      0.33% |    1.97 TiB |          21.25% |
| [f01852023](https://filfox.info/en/address/f01852023) |                   Busan, Busan, KR |           2.47 TiB |      0.33% |    1.59 TiB |          35.44% |
| [f01308863](https://filfox.info/en/address/f01308863) |                            Unknown |           2.39 TiB |      0.32% |    2.39 TiB |           0.01% |
| [f01852325](https://filfox.info/en/address/f01852325) | Hong Kong, Central and Western, HK |           2.19 TiB |      0.29% |    1.56 TiB |          28.57% |
| [f01387566](https://filfox.info/en/address/f01387566) |                            Unknown |           1.81 TiB |      0.24% |    1.79 TiB |           1.29% |
| [f01387466](https://filfox.info/en/address/f01387466) |                            Unknown |           1.78 TiB |      0.24% |    1.75 TiB |           1.54% |
| [f01387599](https://filfox.info/en/address/f01387599) |                            Unknown |           1.71 TiB |      0.23% |    1.70 TiB |           0.69% |
| [f01387598](https://filfox.info/en/address/f01387598) |                            Unknown |           1.65 TiB |      0.22% |    1.65 TiB |           0.35% |
| [f01308857](https://filfox.info/en/address/f01308857) |                            Unknown |         160.00 GiB |      0.02% |  160.00 GiB |           0.00% |
| [f01387460](https://filfox.info/en/address/f01387460) |                            Unknown |         104.00 GiB |      0.01% |   72.00 GiB |          30.77% |
| [f01387459](https://filfox.info/en/address/f01387459) |                            Unknown |          96.25 GiB |      0.01% |   96.25 GiB |           0.00% |
| [f0442383](https://filfox.info/en/address/f0442383)   |                            Unknown |          94.00 GiB |      0.01% |   94.00 GiB |           0.00% |
| [f0142721](https://filfox.info/en/address/f0142721)   |                            Unknown |          40.00 GiB |      0.01% |   40.00 GiB |           0.00% |
| [f01308916](https://filfox.info/en/address/f01308916) |                            Unknown |          36.00 GiB |      0.00% |   36.00 GiB |           0.00% |
| [f0883202](https://filfox.info/en/address/f0883202)   |                            Unknown |          32.25 GiB |      0.00% |   32.25 GiB |           0.00% |
| [f01308877](https://filfox.info/en/address/f01308877) |                            Unknown |          32.00 GiB |      0.00% |   32.00 GiB |           0.00% |
| [f01132084](https://filfox.info/en/address/f01132084) |                            Unknown |           8.13 GiB |      0.00% |    8.13 GiB |           0.00% |
| [f01169691](https://filfox.info/en/address/f01169691) |                            Unknown |           6.75 GiB |      0.00% |    6.75 GiB |           0.00% |

![Provider Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/75/1671092244737.png)
### Deal Data Replication
The below table shows how each many unique data are replicated across storage providers.
- No more than 25% of unique data are stored with less than 4 providers.

⚠️ 99.96% of deals are for data replicated across less than 4 storage providers.

| Unique Data Size | Total Deals Made | Number of Providers | Deal Percentage |
| ---------------: | ---------------: | ------------------: | --------------: |
|       421.56 TiB |       745.94 TiB |                   1 |          99.33% |
|         1.23 TiB |         3.43 TiB |                   2 |           0.46% |
|       320.00 GiB |         1.31 TiB |                   3 |           0.18% |
|        68.00 GiB |       308.00 GiB |                   4 |           0.04% |

![Replication Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/75/1671092245341.png)
### Deal Data Shared with other Clients
The below table shows how many unique data are shared with other clients.
Usually different applications owns different data and should not resolve to the same CID.

⚠️ CID sharing has been observed.

| Other Client                                                                                                                                                                                                              | Application                                                                                                                    | Total Deals Affected | Unique CIDs |        Verifier |
| :------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ | :----------------------------------------------------------------------------------------------------------------------------- | -------------------: | ----------: | --------------: |
| [f3q7ablez3jqkcjukwbzaql7lmbx4ldouu66nexpd<br/>cfvu6kgho3v6gricckt77cgr46tdre2l4zmvha7bs<br/>u7qq](https://filfox.info/en/address/f3q7ablez3jqkcjukwbzaql7lmbx4ldouu66nexpdcfvu6kgho3v6gricckt77cgr46tdre2l4zmvha7bsu7qq) | `MatrixStorage`                                                                                                                |           756.77 TiB |      10,239 |        LDN # 72 |
| [f3rncwz3qo2bwnsrfjc7kq53xr7yi2lctcydtllxo<br/>zmszndvttou7n565yb6aqssvn4omyf5m7q62qpfmq<br/>cbwq](https://filfox.info/en/address/f3rncwz3qo2bwnsrfjc7kq53xr7yi2lctcydtllxozmszndvttou7n565yb6aqssvn4omyf5m7q62qpfmqcbwq) | [VillageOne Space LLCVillageOne Space LLC](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/39)         |           403.23 TiB |       7,805 |        LDN # 39 |
| [f3q3eysweh273pwygu27yllyafljznqewpxwlrc7j<br/>daugrpvhmrcnxmkn43wkctxalcg3z42zxas2hinsf<br/>tgva](https://filfox.info/en/address/f3q3eysweh273pwygu27yllyafljznqewpxwlrc7jdaugrpvhmrcnxmkn43wkctxalcg3z42zxas2hinsftgva) | [Beijing Yibo Technology Co\., Ltd\.](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/74)              |           203.80 TiB |       5,145 |        LDN # 74 |
| [f1tgii4xgcp6um4n2w7eqaw6bwvnvyii2u7cjgzka](https://filfox.info/en/address/f1tgii4xgcp6um4n2w7eqaw6bwvnvyii2u7cjgzka)                                                                                                     | [Meson\.Network ](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/187)                                 |           127.78 TiB |       1,004 | LDN v3 multisig |
| [f1dpgqn57cl5wqijiyv3256nids2ox3fms2mg3oay](https://filfox.info/en/address/f1dpgqn57cl5wqijiyv3256nids2ox3fms2mg3oay)                                                                                                     | [All Blue](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/389)                                        |            74.56 TiB |         715 | LDN v3 multisig |
| [f3woqxpu6ekmj43nmpcv7j2pgu6lejxtzgxpzl6f2<br/>vrueoqlzjntakyhdkghymyffbzfbsio6dvfmy643x<br/>4y7q](https://filfox.info/en/address/f3woqxpu6ekmj43nmpcv7j2pgu6lejxtzgxpzl6f2vrueoqlzjntakyhdkghymyffbzfbsio6dvfmy643x4y7q) | [RICH ST PETE LLC](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/64)                                 |            48.28 TiB |         775 | LDN v3 multisig |
| [f1xwmnlen7j7qlkktm3oqggzcbrxp6cvqnkd2wipa](https://filfox.info/en/address/f1xwmnlen7j7qlkktm3oqggzcbrxp6cvqnkd2wipa)                                                                                                     | ``                                                                                                                             |            35.72 TiB |         392 |       LDN # 121 |
| [f1hik4fc3wvck2jchtufrnfnzmmskw2nyezlbsr3q](https://filfox.info/en/address/f1hik4fc3wvck2jchtufrnfnzmmskw2nyezlbsr3q)                                                                                                     | [NFTSCAN](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/350)                                         |            31.53 TiB |         245 | LDN v3 multisig |
| [f1wr6rwwqckh6um2hynaym2t4mniev5b675kbf5ni](https://filfox.info/en/address/f1wr6rwwqckh6um2hynaym2t4mniev5b675kbf5ni)                                                                                                     | [Ctrip Global Shopping](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/303)                           |            29.66 TiB |         392 | LDN v3 multisig |
| [f1ki4cjk27ypzjsuzkvvqzs6xobaweuoxfdcnpqhy](https://filfox.info/en/address/f1ki4cjk27ypzjsuzkvvqzs6xobaweuoxfdcnpqhy)                                                                                                     | [TimeQuant](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/385)                                       |            29.38 TiB |         357 | LDN v3 multisig |
| [f1u522dt3zabkgbxxzecl77wgv473yvpecxh6t6zq](https://filfox.info/en/address/f1u522dt3zabkgbxxzecl77wgv473yvpecxh6t6zq)                                                                                                     | [Huifan livestream](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/407)                               |            24.44 TiB |         187 | LDN v3 multisig |
| [f1muygjb5zowppbhr7wnmdreqdoiyyanfm7fe54dy](https://filfox.info/en/address/f1muygjb5zowppbhr7wnmdreqdoiyyanfm7fe54dy)                                                                                                     | [MappingFunk Protocol ](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/374)                           |            17.06 TiB |         184 | LDN v3 multisig |
| [f1ibuglt2lzlyf7vnmtzmuykcfgl2pn2fxym5dibi](https://filfox.info/en/address/f1ibuglt2lzlyf7vnmtzmuykcfgl2pn2fxym5dibi)                                                                                                     | [Appstest](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/346)                                        |            14.19 TiB |         386 | LDN v3 multisig |
| [f14abwn2goturifmt27s2bssoe3fup2b3npkgfzui](https://filfox.info/en/address/f14abwn2goturifmt27s2bssoe3fup2b3npkgfzui)                                                                                                     | [KONGFU VR](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/372)                                       |            12.09 TiB |         119 | LDN v3 multisig |
| [f1ffr7uhq7mszotfdybexcnl4i7xw5tqyp5fhqy3y](https://filfox.info/en/address/f1ffr7uhq7mszotfdybexcnl4i7xw5tqyp5fhqy3y)                                                                                                     | [MyTrade Technology Limited](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/386)                      |             9.69 TiB |          99 | LDN v3 multisig |
| [f127l5waa4pw6k3sm4e7wxevc4fe5uz7dyt4mxa3i](https://filfox.info/en/address/f127l5waa4pw6k3sm4e7wxevc4fe5uz7dyt4mxa3i)                                                                                                     | `Pangod`                                                                                                                       |             5.86 TiB |         175 | LDN v3 multisig |
| [f3qvn7f5u4z5w5pqx3htckp4jcn5dvgmebq6qkqcz<br/>xdxkicwokf75tt5hbwtrjwldz2sjiyq752ajcn3nd<br/>5tgq](https://filfox.info/en/address/f3qvn7f5u4z5w5pqx3htckp4jcn5dvgmebq6qkqczxdxkicwokf75tt5hbwtrjwldz2sjiyq752ajcn3nd5tgq) | [Beijing Haishi Hengtong Technology Co\., LTD](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/66)     |             2.47 TiB |          47 | LDN v3 multisig |
| [f1clwd2dooy2cflfilhzeq2ycl544b3heqsiwhjrq](https://filfox.info/en/address/f1clwd2dooy2cflfilhzeq2ycl544b3heqsiwhjrq)                                                                                                     | [FiboAI](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/349)                                          |             2.41 TiB |          40 | LDN v3 multisig |
| [f3w4wlayytfmsay6gu5phhij5r4yyx7t4xxrlosgo<br/>tlmqg5eih3co5atsra4h2pe4qd2d6c76bvhj6nwim<br/>7lgq](https://filfox.info/en/address/f3w4wlayytfmsay6gu5phhij5r4yyx7t4xxrlosgotlmqg5eih3co5atsra4h2pe4qd2d6c76bvhj6nwim7lgq) | [GMWBR INC](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/73)                                        |             1.34 TiB |          27 | LDN v3 multisig |
| [f1cuboogcwais57dljrpeltoy6ja2itb7wvwmrl3q](https://filfox.info/en/address/f1cuboogcwais57dljrpeltoy6ja2itb7wvwmrl3q)                                                                                                     | [Penglaiju](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/400)                                       |             1.13 TiB |          19 | LDN v3 multisig |
| [f3uils5cdx3ezyzszjjfnulugknbdsanmqtisd7x7<br/>xkfcljdnshp4jspnrgxpldt5b4aafuz4q4rkebpjy<br/>keha](https://filfox.info/en/address/f3uils5cdx3ezyzszjjfnulugknbdsanmqtisd7x7xkfcljdnshp4jspnrgxpldt5b4aafuz4q4rkebpjykeha) | [Qingyun Education Fund](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/31)                           |           992.00 GiB |          24 | LDN v3 multisig |
| [f1ojo3wo24zkeovndlxfpqmlgzlbysg5fiukmup4a](https://filfox.info/en/address/f1ojo3wo24zkeovndlxfpqmlgzlbysg5fiukmup4a)                                                                                                     | `Titansoft`                                                                                                                    |           480.00 GiB |           5 | LDN v3 multisig |
| [f3xffjctbyy7zigopfa3za5ha3pvv4z3xfghlw7kw<br/>vyeuabkg4lzsgfwhnghwkvmmvi6yso6k52hq3ca6c<br/>kveq](https://filfox.info/en/address/f3xffjctbyy7zigopfa3za5ha3pvv4z3xfghlw7kwvyeuabkg4lzsgfwhnghwkvmmvi6yso6k52hq3ca6ckveq) | [Chengdu Digital Media Industry Base Co\., Ltd\.](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/387) |           384.00 GiB |           8 | LDN v3 multisig |
| [f1iach3ih3q5x5k4lxy6wlysmqm65vwegpxwm4oii](https://filfox.info/en/address/f1iach3ih3q5x5k4lxy6wlysmqm65vwegpxwm4oii)                                                                                                     | [Friday Shopping](https://github.com/filecoin-project/filecoin-plus-client-onboarding/issues/2019)                             |           128.00 GiB |           3 |        Eric Liu |
| [f1ugo3abkmmb4pb2atxz5oqqgwsd27b4p6k52f2va](https://filfox.info/en/address/f1ugo3abkmmb4pb2atxz5oqqgwsd27b4p6k52f2va)                                                                                                     | [Yuepass Technology Company Limited](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/429)              |            64.00 GiB |           2 | LDN v3 multisig |
| [f1qnhjr2kq742poi6rukv5hji5rdrtuqsib7khz3a](https://filfox.info/en/address/f1qnhjr2kq742poi6rukv5hji5rdrtuqsib7khz3a)                                                                                                     | [GLOBAL UNIT\-A Corp\.](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/110)                           |            32.00 GiB |           1 |       LDN # 110 |
| [f1gs5xe26fkplu64mwcfq5fswycp3qucuvzbg2lia](https://filfox.info/en/address/f1gs5xe26fkplu64mwcfq5fswycp3qucuvzbg2lia)                                                                                                     | [Migu Culture Technology Co\., Ltd](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/63)                |            32.00 GiB |           1 |        LDN # 63 |

[^1]: To manually trigger this report, add a comment with text `checker:manualTrigger`
