### ISSUE TITLE
[DataCap Application] Nine color deer film and television

### ISSUE THREAD

**Issue by Cannondw** [filecoin-project/filecoin-plus-large-datasets#750]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Jiangsu Jiuzhilu Film & TV Co.
- Website / Social Media:www.jiuselu-film.com
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):4PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):160TiB
- On-chain address for first allocation:f1cf7heidxmlf6yyqukdkbnkkodyiaa5fxxhtbgpy

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Ltd. was established in April 2018, we are a film and television production team with more than five years of creative experience. With innovation as the core motivation of the team, we are dedicated to high-end film and television advertising, product advertising, creative advertising, 3D animation, brand microfilm, We are dedicated to high-end film and television commercials, product commercials, creative commercials, 3D animation, brand microfilms, corporate videos, etc. Long-term adherence to the "service + quality" development concept, loved by customers. We strive to become an influential video service provider!

```

What is the primary source of funding for this project?
```
The company's operating income
```

What other projects/ecosystem stakeholders is this project associated with?
```
Related to our partners
```

## Use-case details

Describe the data being stored onto Filecoin
```
Advertising, 3D/MG animation, music videos, corporate videos and other public data, data in the form of video, pictures
```

Where was the data in this dataset sourced from?
```
Data from our own
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://drive.google.com/file/d/13vlyM0F_tbbTH0awv5ac8qwHa1tyHTYZ/view?usp=sharing
https://drive.google.com/file/d/11ZU6Aq0BweQdXM6mHmoGkddfJNn7EECc/view?usp=sharing
https://drive.google.com/file/d/1y70gqeUlzGUcL7F6ty-bJ_8p1LfYaoM6/view?usp=sharing
https://drive.google.com/file/d/13O2-0v73jdV4sax1z6nohSZ1zxUYmUFL/view?usp=sharing
https://drive.google.com/file/d/1ATC59o_IbdSp8v-KSfWZvrdezRdkrGvL/view?usp=sharing
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes, anyone can view
```

What is the expected retrieval frequency for this data?
```
Twice a year
```

For how long do you plan to keep this dataset stored on Filecoin?
```
Minimum 500 days
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Asia
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Yes, we transfer via offline
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We plan to select a number of suppliers who can provide services reliably and consistently
```

How will you be distributing deals across storage providers?
```
We will share equally among the suppliers.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, we are ready to go!
```

**Comment by Sunnyiscoming** [comment]
What's the relationship between you and organization? 
How many copies will you store?
Can you provide more detailed information about other storage providers participated in this program, such as you can list SPs you have contacted with at present?
Could you send an email to filplus-app-review@fil.org with your official domain in order to confirm your identity? Email name should includes the issue id #750.

**Comment by Sunnyiscoming** [comment]
Any update here?

**Comment by Sunnyiscoming** [comment]
Close for no reply. You can resubmit your application if necessary.
