### ISSUE TITLE
[DataCap Application] Anhui Longtuo Film Culture Communication Co., Ltd.

### ISSUE THREAD

**Issue by LongtuoFilm** [filecoin-project/filecoin-plus-large-datasets#753]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Anhui Longtuo Film Culture Communication Co., Ltd.
- Website / Social Media:http://www.longtuoyingshi.cn/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):3PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):200TiB
- On-chain address for first allocation:f1cff3w7s453rgxd6crq667qofc2aegnb3xbqcwci

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
As an influential film and television advertising company in China, Longtop has become a powerful platform for the integration of film and television resources through its thirteen years of operation. Not only does the company have professional directors and skilled planning and post-production teams that are renowned in the industry, but it has also gathered many famous directors from Beijing and Shanghai and introduced industry-leading high-definition pre and post-production equipment resources, creating a number of industry classics.
```

What is the primary source of funding for this project?
```
I'm sorry, that's not easy to say.
```

What other projects/ecosystem stakeholders is this project associated with?
```
This is not related to other projects.
```

## Use-case details

Describe the data being stored onto Filecoin
```
It is mainly public material shot in the past, microfilm and public service type advertisement.
```

Where was the data in this dataset sourced from?
```
We shoot on our own.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://drive.google.com/drive/folders/1rVO0RAEMYTPfccvVkltUry5j7RAqLnX_?usp=sharing
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes.
```

What is the expected retrieval frequency for this data?
```
There are few opportunities during the year.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
Permanent.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
China,Anhui.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Yes, we will use offline data transfer.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We will be looking for some large and reputable miners.
```

How will you be distributing deals across storage providers?
```
We will share equally among the miners.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, we have.
```

**Comment by Sunnyiscoming** [comment]
Please provide more data samples to prove that you have 3Pb data to store. How many copies will you store?

What's the relationship between you and organization? 

Can you provide more detailed information about other storage providers participated in this program, such as you can list SPs you have contacted with at present?

**Comment by Sunnyiscoming** [comment]
Any update here?

**Comment by Sunnyiscoming** [comment]
Close for no reply. You can resubmit your application if necessary.
