### ISSUE TITLE
[DataCap Application] Yingzhao

### ISSUE THREAD

**Issue by Bob8941** [filecoin-project/filecoin-plus-large-datasets#759]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Yingzhao intelligent
- Website / Social Media: http://www.yzzn.group/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):100TiB
- On-chain address for first allocation:f1gnln3t5v7nyrzl6vomuxyx2orwqc3y4yjb7hrhi

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
We offer core products developed specifically for computer front ends, such as JavaScript, CSS. We offer products that are compatible and responsive. Create the perfect professional services and provide one-to-one front-end coaching services for our clients.
```

What is the primary source of funding for this project?
```
Own income.
```

What other projects/ecosystem stakeholders is this project associated with?
```
No.
```

## Use-case details

Describe the data being stored onto Filecoin
```
Front-end skills training videos. We need 6 copies to store.
```

Where was the data in this dataset sourced from?
```
These data come from the front-end courses we offer.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
[css.zip](https://github.com/filecoin-project/filecoin-plus-large-datasets/files/9393701/css.zip)
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Confirm.
```

What is the expected retrieval frequency for this data?
```
Our future retrieval is infrequent. About once every 6 months.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
Minimum 3 years
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Asia Countries.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Offline. We have hard-disks.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We are willing to find more SPs who have experience.
```

How will you be distributing deals across storage providers?
```
We will allocate an equal portion to every storage provider.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes.
```

**Comment by Sunnyiscoming** [comment]
Please provide more data samples to prove that you have 5Pb data to store. How many copies will you store?

What's the relationship between you and organization? 

Can you provide more detailed information about other storage providers participated in this program, such as you can list SPs you have contacted with at present?

**Comment by Sunnyiscoming** [comment]
Could you send an email to filplus-app-review@fil.org with your official domain in order to confirm your identity? Email name should includes the issue id #759.

**Comment by Bob8941** [comment]
![2282](https://user-images.githubusercontent.com/107502005/191936694-ebb69a3a-64be-488a-acf9-2f9c2effa1be.png)
@Sunnyiscoming Hi, the email was already been sent.

**Comment by Sunnyiscoming** [comment]
Email received.

**Comment by raghavrmadya** [comment]
Hey, we can still not ascertain the amount of DataCap requested. Can you please provide more samples and context for the community

**Comment by Geo8942** [comment]
@raghavrmadya Hi Raghav, I'm the PM of Yingzhao. The data we store is front-end skills training videos. 
https://drive.google.com/file/d/1o74Q3v2XawkEhrv-DLTPFXQsuQp6EkKm/view?usp=sharing
Look at the data we provided, it is a part of videos about CSS style. Becasue we provide one-to-one front-end coaching services for our clients, so we do need store these data for our business.

**Comment by Sunnyiscoming** [comment]
https://drive.google.com/file/d/1o74Q3v2XawkEhrv-DLTPFXQsuQp6EkKm/view?usp=sharing
Access is restricted. Please check it.

**Comment by Geo8942** [comment]
> https://drive.google.com/file/d/1o74Q3v2XawkEhrv-DLTPFXQsuQp6EkKm/view?usp=sharing Access is restricted. Please check it.

It is already fixed, you can check it again. Thank you!

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 100TiB

**Client address**

>f1gnln3t5v7nyrzl6vomuxyx2orwqc3y4yjb7hrhi

**Comment by MetaWaveInfo** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebioyva7yebjuocfdqvnkdg6qqtyng76pkcj5pvmzc6v6e6i7j4bu 
#### Address 
> f1gnln3t5v7nyrzl6vomuxyx2orwqc3y4yjb7hrhi
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1ktlkcxnmzxcdaoqfsunrg3vocfbmgv4n3mrn74a
#### Id
> abd375ac-7f36-4092-8d2b-17c2680d9b15
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebioyva7yebjuocfdqvnkdg6qqtyng76pkcj5pvmzc6v6e6i7j4bu

**Comment by UnionLabs2020** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaiiyt3ks4tayfh67h5n3qh2kobsgowwr34dujimrpv6cfwedzmbq 
#### Address 
> f1gnln3t5v7nyrzl6vomuxyx2orwqc3y4yjb7hrhi
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f17xdri3wunqgld7dm23e4f3eqsntjakwc47xjo6i
#### Id
> abd375ac-7f36-4092-8d2b-17c2680d9b15
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaiiyt3ks4tayfh67h5n3qh2kobsgowwr34dujimrpv6cfwedzmbq

**Comment by Sunnyiscoming** [comment]
Are there any problems with using datacap?

**Comment by Geo8942** [comment]
Yes, keep open.

**Comment by herrehesse** [comment]
checker:manualTrigger

**Comment by Geo8942** [comment]
@Sunnyiscoming No, thanks.
