### ISSUE TITLE
[DataCap Application] jinsuanyun Cloud Ltd.

### ISSUE THREAD

**Issue by ghost** [filecoin-project/filecoin-plus-large-datasets#76]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: jinsuanyun Cloud Ltd.,
- Website / Social Media: https://jingsuanyun.top/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100Tib
- On-chain address for first allocation: f3vehf7mwsvfp26xya2eusywb7jqxg6fkkglrtiew5t4ux5q5heicgveojssrvd6pgse66kd7dbvca6omhay6q

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

_*Previously requested address for allocation: f3rsacoz2drjzhtfd2apmvlug5ggsx344p6kfa7wz5y37iyy2pg53gazkjkppj5wvzwjwq7b4prlrzwmkz7eaa_

## Project details

Share a brief history of your project and organization.
```
The company was established on March 2021 with capital stock 30,000 dollars, which is a high-tech company focusing on blockchain technology R&D, distributed storage, cloud computing, chip R&D and supercomputer server production and sales.
Whale Computing Cloud which is cooperating with large enterprises and research institutes promotes IPFS distributed storage and the development of ecological applications in China. It provides safe, inexpensive and eco-friendly storage services in various fields such as blockchain, government affairs, disaster recovery, internet companies, transportation, stock, taxation, tourism, hotels and public facilities.
```

What is the primary source of funding for this project?
```
shareholders‘ investment
```

What other projects/ecosystem stakeholders is this project associated with?
```
There is no other projects/ecosystem stakeholders associated with.
```

## Use-case details

Describe the data being stored onto Filecoin
```
photo, docs 
```

Where was the data in this dataset sourced from?
```
local government of hunan province PRC
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
yes, these data are public to citizen
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
yes, everybody can access those data
```

What is the expected retrieval frequency for this data?
```
if possible , anytime
```

For how long do you plan to keep this dataset stored on Filecoin?
```
permanently
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
PRC
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
online is must, so we  would like to find some  large-scale and creditable miners 
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
 have datacenter of my own
```

How will you be distributing deals across storage providers?
```
We would divide the data up and send it to different miners .
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
yes, cooperate with local(loudi) government of Hunan province PRC
```

**Comment by 16871560** [comment]
hi，can you update the processing status, thx

**Comment by tokencan-tec** [comment]
hi,  could you accelerate this process, I should  have  a brief report to the investor fund

**Comment by tokencan-tec** [comment]
@galen-mcandrew ,Sorry to bother you

**Comment by flyworker** [comment]
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this.

yes, these data are public to citizen
```
You need to provide sample data

**Comment by tokencan-tec** [comment]
http://www.hnloudi.gov.cn/loudi/0605/202110/f3182655e67e41c3b627c6c885b602f3/images/1ce9301edffc43b98ac55ba3e0664d7d.jpg

**Comment by tokencan-tec** [comment]
http://www.hnloudi.gov.cn/loudi/0603/202111/dc4dc0417b454274b7623c6f391fc1b7/files/20c9cfa8a00e41e5ac1933bc7350fa52

**Comment by tokencan-tec** [comment]
@flyworker @galen-mcandrew Is there any update?

**Comment by galen-mcandrew** [comment]
The notaries are responsible for performing diligence and signing the requested allocations. At this time, the notaries will need to weigh in and approve.

Flagging a concerning part of your application though, which may be causing the notaries some confusion: it appears that you are also a storage provider on the Filecoin network, and that you claim to

>  have datacenter of my own

The large dataset process is not intended for storage providers to receive DataCap and exclusively self-deal.

**Comment by tokencan-tec** [comment]
@galen-mcandrew hi, this is a mistake ,my own dat centre is not for IPFS miner , it's  only for the web application and database，and provide k8s service

**Comment by mojoxi** [comment]
Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?

yes, cooperate with local(loudi) government of Hunan province PRC
----------------------

As far as I know the Chinese government does not support and even suppress such subject/actions according to its recent polices.

Any proof you can provide?

**Comment by IPFSUnion** [comment]
Could you get the authorization of your local government?
![image](https://user-images.githubusercontent.com/68763845/150626597-934b6834-a5a4-4442-a113-bedc357629d5.png)

**Comment by Reiers** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebhliz2squaac3t6z6r7unmvkznqdvljqpacijm62ump6cel3g3se 
#### Address 
> f3vehf7mwsvfp26xya2eusywb7jqxg6fkkglrtiew5t4ux5q5heicgveojssrvd6pgse66kd7dbvca6omhay6q
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1oz43ckvmtxmmsfzqm6bpnemqlavz4ifyl524chq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebhliz2squaac3t6z6r7unmvkznqdvljqpacijm62ump6cel3g3se

**Comment by Reiers** [comment]
@UnionLabs2020 Thanks for the heads up!
at first glance this looked okay to me. 

## Other notaries dont sign this one!

**Comment by dannyob** [comment]
I vote to close also, unless we have authorization that reassures Chinese-based notaries.

**Comment by s0nik42** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedl5exdhwrjuibigxsougewlddjww2ukhjlept2uliylptutj2sga 
#### Address 
> f3vehf7mwsvfp26xya2eusywb7jqxg6fkkglrtiew5t4ux5q5heicgveojssrvd6pgse66kd7dbvca6omhay6q
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1wxhnytjmklj2czezaqcfl7eb4nkgmaxysnegwii
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedl5exdhwrjuibigxsougewlddjww2ukhjlept2uliylptutj2sga

**Comment by galen-mcandrew** [comment]
Closing this request for now per notaries comments above.
