### ISSUE TITLE
[DataCap Application] Sanmenxia City Culture Tourism Transportation Development Group Co.

### ISSUE THREAD

**Issue by sanmenxiawentou** [filecoin-project/filecoin-plus-large-datasets#762]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Sanmenxia City Culture Tourism Transportation Development Group Co.
- Website / Social Media:http://www.smxwljt.com/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):2.3 PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):180TiB
- On-chain address for first allocation:f1wzox4whz2xzt5pdghtmihzdmesjr6utrjt7vzra

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
(referred to as the Cultural Tourism Group) was established in early 2019 in accordance with the "Notice on the Formation of Sanmenxia City Cultural Tourism and Transportation Development Group Limited" (Sanzheng [2018] No. 33) and other documents issued by the Sanmenxia Municipal People's Government and the policy requirements on separation of government and enterprises, separation of government and capital, and separation of ownership and operation, in the former Sanmenxia Transportation and Tourism Investment Ltd. was established as a wholly state-owned company on the basis of restructuring and integration. The Group has more than 300 employees, registered capital of 1.02 billion yuan, assets of 3 billion yuan, annual operating income of 400 million yuan and annual profit of 50 million yuan.
```

What is the primary source of funding for this project?
```
Company operating income
```

What other projects/ecosystem stakeholders is this project associated with?
```
NO
```

## Use-case details

Describe the data being stored onto Filecoin
```
Company business development path, promotional video, customer interaction video
```

Where was the data in this dataset sourced from?
```
From our company
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://drive.google.com/drive/folders/1HoW68FMEu5MnVSuBNKq8zWUa42lz3_eh?usp=sharing
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
yes
```

What is the expected retrieval frequency for this data?
```
Once a year
```

For how long do you plan to keep this dataset stored on Filecoin?
```
four years
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Asia
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
offline
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
Stable service providers
```

How will you be distributing deals across storage providers?
```
Average
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Able to provide full funding
```

**Comment by Sunnyiscoming** [comment]
Please provide more data samples to prove that you have 5Pb data to store. How many copies will you store?

What's the relationship between you and organization? 

Can you provide more detailed information about other storage providers participated in this program, such as you can list SPs you have contacted with at present?

**Comment by Sunnyiscoming** [comment]
Any update here?
