### ISSUE TITLE
[DataCap Application] Shanghai yuou culture media Co., Ltd

### ISSUE THREAD

**Issue by jienhg** [filecoin-project/filecoin-plus-large-datasets#764]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Shanghai yuou culture media Co., Ltd
- Website / Social Media:http://www.coinvoice.cn
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):400TiB
- On-chain address for first allocation:f1dm7fxpoozmfypguk6h3sircji34xzejuqtzfpai

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Coinvoice is a blockchain media, committed to providing professional crypto assets, blockchain technology, and industry activity reports. It links blockchain innovators worldwide through the product form of "media + community + activity".
```

What is the primary source of funding for this project?
```
These funds come from the investment of shareholders.
```

What other projects/ecosystem stakeholders is this project associated with?
```
Trading market
```

## Use-case details

Describe the data being stored onto Filecoin
```
Various newsletters, etc
```

Where was the data in this dataset sourced from?
```
Official collection
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://drive.google.com/drive/folders/1Gn2_hddJ5iq5t8T4_z1i73aTaiegW7IM?usp=sharing
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
yes
```

What is the expected retrieval frequency for this data?
```
Anyone interested in retrieving this data
```

For how long do you plan to keep this dataset stored on Filecoin?
```
permanent
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Global
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
We will use both online and offline transmission.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
Select a storage supplier with strong funds and knowledge of project data.
```

How will you be distributing deals across storage providers?
```
We will understand whether the storage suppliers have relevant experience and sustainability, and reasonably allocate them to different storage suppliers according to the analysis
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, we do.
```

**Comment by Sunnyiscoming** [comment]
The data samples on the website and provided are article, and it's hard to justify you having 5 pb data. Can you explain your data composition and provide sufficient data samples separately? How many copies will you store?

What's the relationship between you and organization? 

Can you provide more detailed information about other storage providers participated in this program, such as you can list SPs you have contacted with at present?

**Comment by Sunnyiscoming** [comment]
Any update here?

**Comment by Sunnyiscoming** [comment]
Close for no reply. You can resubmit your application if necessary.
