### ISSUE TITLE
[DataCap Application] Jiuyue Music

### ISSUE THREAD

**Issue by JamarcusHodgey** [filecoin-project/filecoin-plus-large-datasets#769]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Jiuyue Music Technology (Beijing) Co., Ltd
- Website / Social Media:www.9y-china.com
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):5 PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):100 TiB
- On-chain address for first allocation:f1of4smyx6c3eclabtae7an7e2tglvaxxphqmq2ey

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Jiuyue education was founded by "Jiuyue Miracle" in 2015. It is an intelligent technology innovation company focusing on providing music literacy education products for children aged 3 to 12.
With the double row keys as the carrier, the company has joined hands with excellent music education experts and musicians at home and abroad, made full use of advanced technologies such as artificial intelligence, Internet and cloud platform, independently researched and developed courses and system platforms, and created a modern intelligent music course app - "nine month intelligent music class" and "nine month piano room", which are interesting, professional and intelligent.
By upgrading the double row key to the "nine month intelligent double row key" of scientific and technological intelligence, we are committed to solving the pain points existing in traditional music education, such as "difficult for children to accept, monotonous and boring piano practice", "high teaching threshold for teachers, low teaching efficiency", "parents do not know music and can not practice with them". Combining the modern intelligent music course app with the double row keys, and the addition of the game link in the course content, children can easily understand and learn to use various musical instruments, master music theory knowledge such as rhythm, rhythm, beat and music, as well as music creation skills such as melody creation and harmony arrangement, so that children can improve their comprehensive music literacy in happiness.
Jiuyue education is headquartered in Beijing and has been popularized throughout the country. Its development covers 30 provinces, more than 200 cities, more than 600 institutions and more than 10000 families. The service team of the headquarters has nearly 100 people, and the number of teachers in the country has reached more than 1000.
The professional double row key performance Club created by nine month Education - "nine Orchestra" has been invited to participate in CCTV's "very 6 + 1", "Avenue of stars", "echoing", "very star release", "music sharing meeting", "happy piano children's singing", "Dragon Boat Festival Evening", "Mid Autumn Festival Evening", "New Year's day evening" and other well-known programs and evening performances, and has participated in the performance of the Hong Kong Zhuhai Macao Bridge and the opening ceremony of the 2019-2020 CBA League, It has a certain influence in the industry.
```

What is the primary source of funding for this project?
```
Own funds.
```

What other projects/ecosystem stakeholders is this project associated with?
```
None.
```

## Use-case details

Describe the data being stored onto Filecoin
```
A large number of performance videos, music and other data.
```

Where was the data in this dataset sourced from?
```
Photographed, recorded and provided by the company.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://drive.google.com/file/d/1KGHNtutOI62SQ4qIy_meJou8H4VvawPm/view?usp=sharing
https://drive.google.com/file/d/1Ix9UI2zXX9Zaub0GU7rGr2GCLuvNU9C2/view?usp=sharing
https://drive.google.com/file/d/1LBTFP-9LS0ROLMb21ZcY9Th1jd1nlNAg/view?usp=sharing
https://drive.google.com/file/d/1cqXz6q1Et_LKoIehmpr0SqXfGf3ODaA2/view?usp=sharing
https://drive.google.com/file/d/1yRoRF_msiTWsczRjNYFgDYVLkd-ZmAJB/view?usp=sharing
https://drive.google.com/file/d/1OgASXpx3Lymm9ssLEooNGI4hAma1Xlbo/view?usp=sharing
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
yes.
```

What is the expected retrieval frequency for this data?
```
Four times a year.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
More than three years.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
China.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Depending on the network, we can also choose offline data transmission.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We will choose storage suppliers with abundant funds and experience.
```

How will you be distributing deals across storage providers?
```
We will select suppliers that can complete the distribution as soon as possible, but will not exceed 30% of the data volume.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, we have.
```

**Comment by Sunnyiscoming** [comment]
What's the relationship between you and organization? 
How many copies will you store?
Can you provide more detailed information about other storage providers participated in this program, such as you can list SPs you have contacted with at present?
Could you send an email to filplus-app-review@fil.org with your official domain in order to confirm your identity? Email name should includes the issue id #769.

**Comment by Sunnyiscoming** [comment]
Any update here?

**Comment by Sunnyiscoming** [comment]
Close for no reply. You can resubmit your application if necessary.
