### ISSUE TITLE
[DataCap Application] Speedium - Fly Brain Anatomy dataset

### ISSUE THREAD

**Issue by cryptowhizzard** [filecoin-project/filecoin-plus-large-datasets#77]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Speedium Network
- Website / Social Media: www.speedium.nl
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 2PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 200TiB
- On-chain address for first allocation: f17ia7m5mvizrdug3sqtevqw3tifiqvxqr3kdaeuq

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Speedium has participated in SR1 and we are building a bridge between Usenet and Filecoin.
We are ramping up at the moment and have a ready to go system to onboard data to filecoin, however it is not stress-tested on many miners with heavy traffic. We intend to do one or more slingshot rounds to practice the onboarding of large set' s of data at high speed to test our backends and make things work.
```

What is the primary source of funding for this project?
```
We have not received any grants for sending data to the network untill now. We aim to utilize this datacap at zero cost, and send data to all small(er)  active community providers (< 2PiB) out there on Slack, especially MinerX / enterprise-sp-wg members who are willing and capable of receiving deals.

We participate in slingshot to aim to have some  return on our efforts to get everything working properly and cover the costs of bandwidth, hardware and communicating with providers to keep everything aligned during this phase. We aim to do this in the SP group.
```

What other projects/ecosystem stakeholders is this project associated with?
```
Slingshot, MinerX, enterprise-sp-wp.
```

## Use-case details

Describe the data being stored onto Filecoin
```
Please answer here.
```

Where was the data in this dataset sourced from?
```
Fly Brain Anatomy, made available by Janelia's FlyLight project, consists of fluorescence images of Drosophila melanogaster driver lines, aligned to standard templates, and stored in formats suitable for rapid searching in the cloud.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://registry.opendata.aws/janelia-flylight/
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes. It has the license of https://creativecommons.org/licenses/by/4.0/.
```

What is the expected retrieval frequency for this data?
```
Anyone interested in retrieving this datacet ( a few times we guess )
```

For how long do you plan to keep this dataset stored on Filecoin?
```
1.5 yr.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
All regions but mainly EU and US as Speedium has the most bandwidth towards those regions.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Online!
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We will contact the MinerX and enterprise-sp-wg members as well as any other providers interested to receive the deals.
```

How will you be distributing deals across storage providers?
```
Evenly across all providers as long as they can handle. If a miner is a notary itself, this notary will receive no more than 10% of the total granted datacap.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
We have enough funding / recourses to give this a try-out. 
```

**Comment by cryptowhizzard** [comment]
Hello @s0nik42 @Reiers  

Can you please state that you are ok that we use this datacap also for the slingshot recovery program? That program has priority now and we are focussing our efforts on this.

**Comment by Reiers** [comment]
Everything looks good. Speedium have my support!

**Comment by s0nik42** [comment]
Same here

**Comment by cryptowhizzard** [comment]
@dkkapur @galen-mcandrew it seems that the bot did apply for automatic renewal of my datacap. Can you please do RKH request manually.

@s0nik42 it is possible that you give us some manual datacap in the meantime, like 20 TB on above address?

**Comment by galen-mcandrew** [comment]
The previous allocation was for 100 TiB of DataCap, and checking this client address still has 94 TiB. The subsequent allocation bot will not request more DataCap until 75% of the previous allocation has been sealed in deals.

Additionally, this multisig still has a pending transaction from the previous triple signature. So when you have used more DataCap and the SA bot kicks off the next allocation, it should only require one notary signature.

**Comment by flyworker** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacednxl4kwt7aneduncpvairawg5iykmb5vvznjbjoqf55d4seqbslk 
#### Address 
> f17ia7m5mvizrdug3sqtevqw3tifiqvxqr3kdaeuq
#### Datacap Allocated
> 200TiB
#### Signer Address
> f1hlubjsdkv4wmsdadihloxgwrz3j3ernf6i3cbpy
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacednxl4kwt7aneduncpvairawg5iykmb5vvznjbjoqf55d4seqbslk

**Comment by galen-mcandrew** [comment]
Looks like there are now two pending transactions, ID 2 for 100TiB and ID 3 for 200TiB. Adjusting labels, next signature should clear one of these transactions.

**Comment by s0nik42** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebmffl7e6eymaxa5du4vqxebbvmrcqdfoq4wubk72d4mz4thorlge 
#### Address 
> f17ia7m5mvizrdug3sqtevqw3tifiqvxqr3kdaeuq
#### Datacap Allocated
> 200TiB
#### Signer Address
> f1wxhnytjmklj2czezaqcfl7eb4nkgmaxysnegwii
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebmffl7e6eymaxa5du4vqxebbvmrcqdfoq4wubk72d4mz4thorlge

**Comment by Reiers** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecgsa4rzrsmaclpebdlgi7yem5htewibhp3ggzoo7cjjbi6mlxwim 
#### Address 
> f17ia7m5mvizrdug3sqtevqw3tifiqvxqr3kdaeuq
#### Datacap Allocated
> 400TiB
#### Signer Address
> f1oz43ckvmtxmmsfzqm6bpnemqlavz4ifyl524chq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecgsa4rzrsmaclpebdlgi7yem5htewibhp3ggzoo7cjjbi6mlxwim

**Comment by s0nik42** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceccd27phjtfp442juy4yz6vypdeyoyavgcglf7shrgqkkmiydw6qg 
#### Address 
> f17ia7m5mvizrdug3sqtevqw3tifiqvxqr3kdaeuq
#### Datacap Allocated
> 400TiB
#### Signer Address
> f1wxhnytjmklj2czezaqcfl7eb4nkgmaxysnegwii
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceccd27phjtfp442juy4yz6vypdeyoyavgcglf7shrgqkkmiydw6qg

**Comment by MegTei** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedytzjmpliktxusddnbzmxfi6k7gg4sru3dam4bbdudfot4hlwlkk 
#### Address 
> f17ia7m5mvizrdug3sqtevqw3tifiqvxqr3kdaeuq
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1ystxl2ootvpirpa7ebgwl7vlhwkbx2r4zjxwe5i
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedytzjmpliktxusddnbzmxfi6k7gg4sru3dam4bbdudfot4hlwlkk

**Comment by flyworker** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecwhy7i4wr3mdeqdl4efmein27skly37c3ndkizeaqwybprox7ywq 
#### Address 
> f17ia7m5mvizrdug3sqtevqw3tifiqvxqr3kdaeuq
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1hlubjsdkv4wmsdadihloxgwrz3j3ernf6i3cbpy
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecwhy7i4wr3mdeqdl4efmein27skly37c3ndkizeaqwybprox7ywq

**Comment by dannyob** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecbrizbpjznjn7obnxxjjit63mehb5jdtg4iydez6h4b2i4gwf4si 
#### Address 
> f17ia7m5mvizrdug3sqtevqw3tifiqvxqr3kdaeuq
#### Datacap Allocated
> 1.12PiB
#### Signer Address
> f1k6wwevxvp466ybil7y2scqlhtnrz5atjkkyvm4a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecbrizbpjznjn7obnxxjjit63mehb5jdtg4iydez6h4b2i4gwf4si

**Comment by flyworker** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecj5fgnq6j6ns66rqqxnrzxt4yry2ft4dqxzclzb3pbrfy4tkmwa2 
#### Address 
> f17ia7m5mvizrdug3sqtevqw3tifiqvxqr3kdaeuq
#### Datacap Allocated
> 1.12PiB
#### Signer Address
> f1hlubjsdkv4wmsdadihloxgwrz3j3ernf6i3cbpy
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecj5fgnq6j6ns66rqqxnrzxt4yry2ft4dqxzclzb3pbrfy4tkmwa2

**Comment by dannyob** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaje5t3iu3iepnvtavdrqdwmhbmqvihi25bshvjwfyxnneeyr5d2c 
#### Address 
> f17ia7m5mvizrdug3sqtevqw3tifiqvxqr3kdaeuq
#### Datacap Allocated
> 1.56PiB
#### Signer Address
> f1k6wwevxvp466ybil7y2scqlhtnrz5atjkkyvm4a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaje5t3iu3iepnvtavdrqdwmhbmqvihi25bshvjwfyxnneeyr5d2c

**Comment by MegTei** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecjkw6xtorljstcw4apgxl5jwgkpqmhk4sni6g2dvkxvdn4d7a3m4 
#### Address 
> f17ia7m5mvizrdug3sqtevqw3tifiqvxqr3kdaeuq
#### Datacap Allocated
> 1.56PiB
#### Signer Address
> f1ystxl2ootvpirpa7ebgwl7vlhwkbx2r4zjxwe5i
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecjkw6xtorljstcw4apgxl5jwgkpqmhk4sni6g2dvkxvdn4d7a3m4

**Comment by Reiers** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebvde5d6rvsgrnuvmv2qv76yec355gazlr5eky46bpxs4ytawhiem 
#### Address 
> f17ia7m5mvizrdug3sqtevqw3tifiqvxqr3kdaeuq
#### Datacap Allocated
> 1.56PiB
#### Signer Address
> f1oz43ckvmtxmmsfzqm6bpnemqlavz4ifyl524chq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebvde5d6rvsgrnuvmv2qv76yec355gazlr5eky46bpxs4ytawhiem

**Comment by dkkapur** [comment]
FYI - looks like the bot is still bugging out and this allocation will not go through because it will exceed the maximum. The maximum is 348 TiB left to get to 2 PiB as requested by the client. Doing this manually now.

**Comment by dkkapur** [comment]
## DataCap Allocation requested

### Request number 7
#### Multisig Notary address
> f01403237

#### Client address
> f17ia7m5mvizrdug3sqtevqw3tifiqvxqr3kdaeuq

#### DataCap allocation requested
> 348TiB

**Comment by Reiers** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebmbfiv5dl4pwydtcsivg5nilkblpdmmvvlujcsxa7rxfuhza2dgc 
#### Address 
> f17ia7m5mvizrdug3sqtevqw3tifiqvxqr3kdaeuq
#### Datacap Allocated
> 348.00TiB
#### Signer Address
> f1oz43ckvmtxmmsfzqm6bpnemqlavz4ifyl524chq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebmbfiv5dl4pwydtcsivg5nilkblpdmmvvlujcsxa7rxfuhza2dgc

**Comment by MegTei** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedy24gncuh5vv77ik5mugxppntvg4nprb2cezfhw33fyhq2rh362q 
#### Address 
> f17ia7m5mvizrdug3sqtevqw3tifiqvxqr3kdaeuq
#### Datacap Allocated
> 348.00TiB
#### Signer Address
> f1ystxl2ootvpirpa7ebgwl7vlhwkbx2r4zjxwe5i
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedy24gncuh5vv77ik5mugxppntvg4nprb2cezfhw33fyhq2rh362q

**Comment by s0nik42** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec2bhjsszlhi4y22bqsfoynlaoakkrbhrq7lucnfod7pmuiuhxat4 
#### Address 
> f17ia7m5mvizrdug3sqtevqw3tifiqvxqr3kdaeuq
#### Datacap Allocated
> 348.00TiB
#### Signer Address
> f1wxhnytjmklj2czezaqcfl7eb4nkgmaxysnegwii
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec2bhjsszlhi4y22bqsfoynlaoakkrbhrq7lucnfod7pmuiuhxat4

**Comment by s0nik42** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebvq4y47nxrihrlmrswad6koegq6vi4uwx5x4t62vqtyhxroo6qk6 
#### Address 
> f17ia7m5mvizrdug3sqtevqw3tifiqvxqr3kdaeuq
#### Datacap Allocated
> 348.00TiB
#### Signer Address
> f1wxhnytjmklj2czezaqcfl7eb4nkgmaxysnegwii
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebvq4y47nxrihrlmrswad6koegq6vi4uwx5x4t62vqtyhxroo6qk6

**Comment by s0nik42** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceazi5snw5rs3ikfyhdw4fpu6xkygxrpqwihzi7azhubckhtweottm 
#### Address 
> f17ia7m5mvizrdug3sqtevqw3tifiqvxqr3kdaeuq
#### Datacap Allocated
> 348.00TiB
#### Signer Address
> f1wxhnytjmklj2czezaqcfl7eb4nkgmaxysnegwii
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceazi5snw5rs3ikfyhdw4fpu6xkygxrpqwihzi7azhubckhtweottm

**Comment by cryptowhizzard** [comment]
I think that the retrieval is working as far as i can see in your screenshot? 

Ongoing means that it is transferring :)

**Comment by filplus-checker** [comment]
## DataCap and CID Checker Report[^1]
 - Organization: ` Speedium NetworkSpeedium Network`
 - Client: `f17ia7m5mvizrdug3sqtevqw3tifiqvxqr3kdaeuq`
### Storage Provider Distribution
The below table shows the distribution of storage providers that have stored data for this client.

If this is the first time a provider takes verified deal, it will be marked as `new`.

For most of the datacap application, below restrictions should apply.
 - Storage provider should not exceed 25% of total datacap.
 - Storage provider should not be storing duplicate data for more than 20%.
 - Storage provider should have published its public IP address.
 - All storage providers should be located in different regions.

⚠️ 27.89% of total deal sealed by [f022352](https://filfox.info/en/address/f022352) are duplicate data.

⚠️ 21.24% of total deal sealed by [f01720359](https://filfox.info/en/address/f01720359) are duplicate data.

⚠️ 21.23% of total deal sealed by [f02576](https://filfox.info/en/address/f02576) are duplicate data.

⚠️ 20.78% of total deal sealed by [f01222595](https://filfox.info/en/address/f01222595) are duplicate data.

⚠️ 29.11% of total deal sealed by [f0694396](https://filfox.info/en/address/f0694396) are duplicate data.

⚠️ 29.90% of total deal sealed by [f019551](https://filfox.info/en/address/f019551) are duplicate data.

⚠️ 20.41% of total deal sealed by [f01396100](https://filfox.info/en/address/f01396100) are duplicate data.

⚠️ 43.48% of total deal sealed by [f019104](https://filfox.info/en/address/f019104) are duplicate data.

⚠️ 20.59% of total deal sealed by [f01240](https://filfox.info/en/address/f01240) are duplicate data.

⚠️ [f020378](https://filfox.info/en/address/f020378) has unknown IP location.

⚠️ [f01216923](https://filfox.info/en/address/f01216923) has unknown IP location.

| Provider                                                    |                          Location | Total Deals Sealed | Percentage | Unique Data | Duplicate Deals |
| :---------------------------------------------------------- | --------------------------------: | -----------------: | ---------: | ----------: | --------------: |
| [f022352](https://filfox.info/en/address/f022352)           |                    Oslo, Oslo, NO |         434.73 TiB |     21.05% |  313.48 TiB |          27.89% |
| [f01385207](https://filfox.info/en/address/f01385207)`new`  |             Lincoln, Nebraska, US |         215.00 TiB |     10.41% |  210.68 TiB |           2.01% |
| [f01720359](https://filfox.info/en/address/f01720359)`new`  |  Heerhugowaard, North Holland, NL |         212.66 TiB |     10.30% |  167.50 TiB |          21.24% |
| [f01771403](https://filfox.info/en/address/f01771403)`new`  |  Heerhugowaard, North Holland, NL |         158.09 TiB |      7.65% |  133.12 TiB |          15.79% |
| [f01786387](https://filfox.info/en/address/f01786387)`new`  |  Heerhugowaard, North Holland, NL |         149.72 TiB |      7.25% |  137.99 TiB |           7.84% |
| [f01208632](https://filfox.info/en/address/f01208632)       |       Sydney, New South Wales, AU |         104.84 TiB |      5.08% |  104.80 TiB |           0.03% |
| [f01652333](https://filfox.info/en/address/f01652333)       |         Sunnyvale, California, US |         104.30 TiB |      5.05% |   96.64 TiB |           7.34% |
| [f0501283](https://filfox.info/en/address/f0501283)         |             Lincoln, Nebraska, US |          83.10 TiB |      4.02% |   83.07 TiB |           0.04% |
| [f01208189](https://filfox.info/en/address/f01208189)       |       Sydney, New South Wales, AU |          79.85 TiB |      3.87% |   79.85 TiB |           0.00% |
| [f01207045](https://filfox.info/en/address/f01207045)       |  Heerhugowaard, North Holland, NL |          68.33 TiB |      3.31% |   68.08 TiB |           0.37% |
| [f097777](https://filfox.info/en/address/f097777)           |               Kivertsi, Volyn, UA |          65.07 TiB |      3.15% |   63.08 TiB |           3.06% |
| [f01199442](https://filfox.info/en/address/f01199442)       |  Heerhugowaard, North Holland, NL |          61.13 TiB |      2.96% |   60.66 TiB |           0.77% |
| [f010479](https://filfox.info/en/address/f010479)           |          Paris, Île-de-France, FR |          55.51 TiB |      2.69% |   53.61 TiB |           3.42% |
| [f066596](https://filfox.info/en/address/f066596)           |         San Diego, California, US |          50.38 TiB |      2.44% |   49.91 TiB |           0.93% |
| [f01732189](https://filfox.info/en/address/f01732189)       |         San Diego, California, US |          28.36 TiB |      1.37% |   28.36 TiB |           0.00% |
| [f01392893](https://filfox.info/en/address/f01392893)       |      Amsterdam, North Holland, NL |          22.13 TiB |      1.07% |   19.87 TiB |          10.24% |
| [f01208803](https://filfox.info/en/address/f01208803)`new`  |       Sydney, New South Wales, AU |          20.80 TiB |      1.01% |   20.74 TiB |           0.32% |
| [f01201327](https://filfox.info/en/address/f01201327)       |  Heerhugowaard, North Holland, NL |          20.78 TiB |      1.01% |   20.59 TiB |           0.90% |
| [f01208862](https://filfox.info/en/address/f01208862)       |  Heerhugowaard, North Holland, NL |          17.86 TiB |      0.86% |   17.64 TiB |           1.22% |
| [f01199430](https://filfox.info/en/address/f01199430)       |  Heerhugowaard, North Holland, NL |          17.81 TiB |      0.86% |   17.63 TiB |           1.05% |
| [f014768](https://filfox.info/en/address/f014768)           |          Singapore, Singapore, SG |          14.25 TiB |      0.69% |   14.25 TiB |           0.00% |
| [f01345523](https://filfox.info/en/address/f01345523)       |           Antwerpen, Flanders, BE |          13.45 TiB |      0.65% |   11.90 TiB |          11.50% |
| [f01157271](https://filfox.info/en/address/f01157271)`new`  |       Sydney, New South Wales, AU |          11.28 TiB |      0.55% |   10.42 TiB |           7.62% |
| [f02576](https://filfox.info/en/address/f02576)             |    Copenhagen, Capital Region, DK |           8.32 TiB |      0.40% |    6.55 TiB |          21.23% |
| [f08403](https://filfox.info/en/address/f08403)             | Bourton on the Water, England, GB |           7.78 TiB |      0.38% |    7.75 TiB |           0.40% |
| [f010446](https://filfox.info/en/address/f010446)           |            Zaventem, Flanders, BE |           6.56 TiB |      0.32% |    6.47 TiB |           1.43% |
| [f01163272](https://filfox.info/en/address/f01163272)       |               Perm, Perm Krai, RU |           6.01 TiB |      0.29% |    5.88 TiB |           2.08% |
| [f01222595](https://filfox.info/en/address/f01222595)       |                Moscow, Moscow, RU |           4.81 TiB |      0.23% |    3.81 TiB |          20.78% |
| [f0694396](https://filfox.info/en/address/f0694396)         |           Birmingham, England, GB |           3.13 TiB |      0.15% |    2.22 TiB |          29.11% |
| [f019551](https://filfox.info/en/address/f019551)           |           Birmingham, England, GB |           2.86 TiB |      0.14% |    2.01 TiB |          29.90% |
| [f0187709](https://filfox.info/en/address/f0187709)         |                Moscow, Moscow, RU |           1.94 TiB |      0.09% |    1.57 TiB |          19.32% |
| [f0461791](https://filfox.info/en/address/f0461791)`new`    |              Gwangju, Gwangju, KR |           1.94 TiB |      0.09% |    1.56 TiB |          19.35% |
| [f0707721](https://filfox.info/en/address/f0707721)         |  Heerhugowaard, North Holland, NL |           1.69 TiB |      0.08% |    1.53 TiB |           9.26% |
| [f01396100](https://filfox.info/en/address/f01396100)`new`  |              Gwangju, Gwangju, KR |           1.53 TiB |      0.07% |    1.22 TiB |          20.41% |
| [f019104](https://filfox.info/en/address/f019104)           |              Montréal, Quebec, CA |           1.44 TiB |      0.07% |  832.00 GiB |          43.48% |
| [f01133080](https://filfox.info/en/address/f01133080)       |              Gwangju, Gwangju, KR |           1.22 TiB |      0.06% |    1.06 TiB |          12.82% |
| [f01240](https://filfox.info/en/address/f01240)             |  Heerhugowaard, North Holland, NL |           1.06 TiB |      0.05% |  864.00 GiB |          20.59% |
| [f0102313](https://filfox.info/en/address/f0102313)         |      Gyeonggi-do, Gyeonggi-do, KR |         672.00 GiB |      0.03% |  672.00 GiB |           0.00% |
| [f0149444](https://filfox.info/en/address/f0149444)         |      Gyeonggi-do, Gyeonggi-do, KR |         512.00 GiB |      0.02% |  512.00 GiB |           0.00% |
| [f0215497](https://filfox.info/en/address/f0215497)         |      Gyeonggi-do, Gyeonggi-do, KR |         480.00 GiB |      0.02% |  480.00 GiB |           0.00% |
| [f0142606](https://filfox.info/en/address/f0142606)         |      Gyeonggi-do, Gyeonggi-do, KR |         448.00 GiB |      0.02% |  448.00 GiB |           0.00% |
| [f01186444](https://filfox.info/en/address/f01186444)       |      Gyeonggi-do, Gyeonggi-do, KR |         448.00 GiB |      0.02% |  448.00 GiB |           0.00% |
| [f0840770](https://filfox.info/en/address/f0840770)         |        University Park, Texas, US |         416.00 GiB |      0.02% |  384.00 GiB |           7.69% |
| [f0842485](https://filfox.info/en/address/f0842485)         |      Gyeonggi-do, Gyeonggi-do, KR |         384.00 GiB |      0.02% |  384.00 GiB |           0.00% |
| [f020378](https://filfox.info/en/address/f020378)           |                           Unknown |         312.00 GiB |      0.01% |  296.00 GiB |           5.13% |
| [f024184](https://filfox.info/en/address/f024184)           |                  Seoul, Seoul, KR |         288.00 GiB |      0.01% |  288.00 GiB |           0.00% |
| [f01208154](https://filfox.info/en/address/f01208154)`new`  |       Sydney, New South Wales, AU |         240.00 GiB |      0.01% |  240.00 GiB |           0.00% |
| [f058369](https://filfox.info/en/address/f058369)           |         Boston, Massachusetts, US |         224.00 GiB |      0.01% |  224.00 GiB |           0.00% |
| [f0101087](https://filfox.info/en/address/f0101087)`new`    |                  Seoul, Seoul, KR |         224.00 GiB |      0.01% |  224.00 GiB |           0.00% |
| [f01278](https://filfox.info/en/address/f01278)             |        Grand Rapids, Michigan, US |         192.00 GiB |      0.01% |  192.00 GiB |           0.00% |
| [f03488](https://filfox.info/en/address/f03488)             |                  Seoul, Seoul, KR |          96.00 GiB |      0.00% |   96.00 GiB |           0.00% |
| [f033356](https://filfox.info/en/address/f033356)           |                  Seoul, Seoul, KR |          96.00 GiB |      0.00% |   96.00 GiB |           0.00% |
| [f0726405](https://filfox.info/en/address/f0726405)         |      Gyeonggi-do, Gyeonggi-do, KR |          96.00 GiB |      0.00% |   96.00 GiB |           0.00% |
| [f01063173](https://filfox.info/en/address/f01063173)       |      Gyeonggi-do, Gyeonggi-do, KR |          96.00 GiB |      0.00% |   96.00 GiB |           0.00% |
| [f02620](https://filfox.info/en/address/f02620)             |               Warsaw, Mazovia, PL |          64.00 GiB |      0.00% |   64.00 GiB |           0.00% |
| [f0678914](https://filfox.info/en/address/f0678914)         |         San Diego, California, US |          64.00 GiB |      0.00% |   64.00 GiB |           0.00% |
| [f01216923](https://filfox.info/en/address/f01216923)`new`  |                           Unknown |          64.00 GiB |      0.00% |   64.00 GiB |           0.00% |
| [f030379](https://filfox.info/en/address/f030379)           |                  Seoul, Seoul, KR |          64.00 GiB |      0.00% |   64.00 GiB |           0.00% |
| [f0533124](https://filfox.info/en/address/f0533124)         |      Gyeonggi-do, Gyeonggi-do, KR |          64.00 GiB |      0.00% |   64.00 GiB |           0.00% |
| [f01044351](https://filfox.info/en/address/f01044351)       |              Gwangju, Gwangju, KR |          64.00 GiB |      0.00% |   64.00 GiB |           0.00% |
| [f0773157](https://filfox.info/en/address/f0773157)         |           Fremont, California, US |          32.00 GiB |      0.00% |   32.00 GiB |           0.00% |
| [f0104671](https://filfox.info/en/address/f0104671)         |            Kawasaki, Kanagawa, JP |          20.00 GiB |      0.00% |   20.00 GiB |           0.00% |

![Provider Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/77/1671092299060.png)
### Deal Data Replication
The below table shows how each many unique data are replicated across storage providers.
- No more than 25% of unique data are stored with less than 4 providers.

✔️ Data replication looks healthy.

| Unique Data Size | Total Deals Made | Number of Providers | Deal Percentage |
| ---------------: | ---------------: | ------------------: | --------------: |
|        33.46 TiB |        36.91 TiB |                   1 |           1.79% |
|        76.40 TiB |       167.01 TiB |                   2 |           8.09% |
|        95.35 TiB |       307.73 TiB |                   3 |          14.90% |
|       124.24 TiB |       559.62 TiB |                   4 |          27.10% |
|        76.27 TiB |       447.31 TiB |                   5 |          21.66% |
|        41.16 TiB |       281.64 TiB |                   6 |          13.64% |
|        19.81 TiB |       157.80 TiB |                   7 |           7.64% |
|         9.83 TiB |        88.09 TiB |                   8 |           4.27% |
|       960.00 GiB |         9.28 TiB |                   9 |           0.45% |
|       256.00 GiB |         2.63 TiB |                  10 |           0.13% |
|        96.00 GiB |         1.09 TiB |                  11 |           0.05% |
|        96.00 GiB |         1.13 TiB |                  12 |           0.05% |
|        32.00 GiB |       544.00 GiB |                  13 |           0.03% |
|       128.00 GiB |         1.75 TiB |                  14 |           0.08% |
|        64.00 GiB |         1.16 TiB |                  15 |           0.06% |
|        64.00 GiB |         1.03 TiB |                  16 |           0.05% |
|        32.00 GiB |       544.00 GiB |                  17 |           0.03% |

![Replication Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/77/1671092299871.png)
### Deal Data Shared with other Clients
The below table shows how many unique data are shared with other clients.
Usually different applications owns different data and should not resolve to the same CID.

⚠️ CID sharing has been observed.

| Other Client                                                                                                                                                                                                              | Application                                                                                                                     | Total Deals Affected | Unique CIDs |        Verifier |
| :------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ | :------------------------------------------------------------------------------------------------------------------------------ | -------------------: | ----------: | --------------: |
| [f1z7jogzx4x42wtilzb4lu6iotlad5rptt2acbzpi](https://filfox.info/en/address/f1z7jogzx4x42wtilzb4lu6iotlad5rptt2acbzpi)                                                                                                     | [Speedium network](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/339)                                 |             2.36 PiB |       4,354 | LDN v3 multisig |
| [f1r73sc6w57lmgoioycsbywogdxyb674twpzma4hi](https://filfox.info/en/address/f1r73sc6w57lmgoioycsbywogdxyb674twpzma4hi)                                                                                                     | Unknown                                                                                                                         |           332.47 TiB |       4,379 |         Unknown |
| [f1srdxedjfgezixzx6x5asyr7k5l3v632dvwjkxci](https://filfox.info/en/address/f1srdxedjfgezixzx6x5asyr7k5l3v632dvwjkxci)                                                                                                     | Unknown                                                                                                                         |            78.70 TiB |         803 |         Unknown |
| [f1pkrmygbvweykpjcut36lf7ewgqdfhjklbhvepda](https://filfox.info/en/address/f1pkrmygbvweykpjcut36lf7ewgqdfhjklbhvepda)                                                                                                     | [Protocol Labs \( project: Slingshot Evergreen \)](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/293) |            65.21 TiB |         807 |       LDN # 293 |
| [f3tcqolyrf4npnqit625jswb4dzxy55e47i4npdsz<br/>yhaht6i5kpwhgxy4hkr3axzvfh437j3gyxmzdlsec<br/>o6ja](https://filfox.info/en/address/f3tcqolyrf4npnqit625jswb4dzxy55e47i4npdszyhaht6i5kpwhgxy4hkr3axzvfh437j3gyxmzdlseco6ja) | Unknown                                                                                                                         |             2.20 TiB |          24 |         Unknown |
| [f1s2na7nktgkbf6amxg4ag5z73jne3gfivqqwptea](https://filfox.info/en/address/f1s2na7nktgkbf6amxg4ag5z73jne3gfivqqwptea)                                                                                                     | Unknown                                                                                                                         |             1.19 TiB |          27 |         Unknown |
| [f17jxla7d6y4sefo2jma36u666ajmctybnmulkouq](https://filfox.info/en/address/f17jxla7d6y4sefo2jma36u666ajmctybnmulkouq)                                                                                                     | Unknown                                                                                                                         |           768.00 GiB |          16 |         Unknown |
| [f1jazufgrriehamquvuxzzfeapmkn55vrgaxx334i](https://filfox.info/en/address/f1jazufgrriehamquvuxzzfeapmkn55vrgaxx334i)                                                                                                     | Unknown                                                                                                                         |           736.00 GiB |          17 |         Unknown |
| [f1xafi3wsh7q553efnumhgeomathrehwwd2mye7oy](https://filfox.info/en/address/f1xafi3wsh7q553efnumhgeomathrehwwd2mye7oy)                                                                                                     | [Speedium network](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/483)                                 |           288.00 GiB |           9 | LDN v3 multisig |

[^1]: To manually trigger this report, add a comment with text `checker:manualTrigger`

**Comment by Tom-zhang987** [comment]
checker:manualTrigger

**Comment by spaceT9** [comment]
checker:manualTrigger

**Comment by data-programs** [comment]
<img width="32" alt="KYC" Verified src="https://stable.filplus.storage/images/filplus-kyc-verified-badge.png"/>

This user’s identity has been verified through [filplus.storage](https://filplus.storage)
