### ISSUE TITLE
[DataCap Application]Yeda Films

### ISSUE THREAD

**Issue by Weckxsa** [filecoin-project/filecoin-plus-large-datasets#770]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Shaanxi Wentou (Film & TV) Yida Culture & Media Co.
- Website / Social Media:www.yidamedia.cn
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):100TiB
- On-chain address for first allocation:f1x5rwjmllxxeqwytdkpeyuhhixr6z3ijx2armi2a

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
(Yida), founded in 2011, is a comprehensive film and television entertainment company with original content as its foundation. It is dedicated to the investment, production, distribution and marketing of TV dramas, web dramas and movies, and other integrated operations. The company's business scope includes content pre-development, filming and production, promotion and distribution, and acting agency. So far, Yida Film & TV has maintained good cooperation with TV stations, online video platforms and domestic mainstream media in all provinces and cities. The company has successfully invested, produced, distributed and planned more than 20 outstanding works with high reputation, high popularity, high ratings and high social influence, such as "Mr. Love", "Mr. Good", "Little Goodbye", "My True Friend", "Leaves Fall in Longevity", "Wolf of the Desert", "Love in the Time of War" and "The Way of the World is Changing".

```

What is the primary source of funding for this project?
```
Company's revenue
```

What other projects/ecosystem stakeholders is this project associated with?
```
No connection to other projects
```

## Use-case details

Describe the data being stored onto Filecoin
```
Film and television commercials, TV series, film productions and highlights of the shooting process, etc. The data content is mainly videos, pictures
```

Where was the data in this dataset sourced from?
```
Since its establishment, the dramas produced by Yida Film and TV have won multiple recognitions from the industry and the market for their rich subject matter, novel narrative angles and advanced story ideas. Among them, in May 2016, "Mr. Good" was broadcasted and exploded all over the Internet, becoming a well-deserved annual hit and starting the much-awaited "Mr. Series"; in January 2018, the second part of "Mr. Series", "Mr. Love In January 2018, "Mr. Love", the second part of "Mr. Love" series, was launched on the Internet, which once again set off the climax of the network's buzz and became a breakout hit in the beginning of the year with 26 days of broadcast, and "My True Friend" was launched in May 2019, focusing on the plot of "housing" in Chinese society and truly presenting the life of people who buy houses. It has become the most talked about masterpiece in 2019. In addition, works such as "Leaves Fall in Chang'an", "Love at War", "The Way of the World is Changing" and "A Small Goodbye" have all lived up to expectations from the turbulent war years to the reality of today's society, achieving both positive results in terms of word-of-mouth and ratings. With these excellent works, Yida Film & TV has professional attitude and accurate industry insight, it is highly recognized and expected inside and outside the industry.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
http://www.yidamedia.cn/uploads/media/20201209/1-2012091AR2120.mp4
http://www.yidamedia.cn/uploads/media/20220107/1-22010F95T5S8.mp4
http://www.yidamedia.cn/uploads/media/20211018/1-21101QG343H8.mp4

```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes, anyone can retrieve
```

What is the expected retrieval frequency for this data?
```
Twice a year
```

For how long do you plan to keep this dataset stored on Filecoin?
```
At least 500 days
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Asia
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
We can have an offline data transfer process. How the data is distributed will depend on the network
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We will consider the time and stability of the supplier
```

How will you be distributing deals across storage providers?
```
We will understand whether the storage provider has relevant experience and sustainability and rationalize it to different storage providers based on the analysis
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, we have.
```

**Comment by Sunnyiscoming** [comment]
What's the relationship between you and organization? 
How many copies will you store?
Can you provide more detailed information about other storage providers participated in this program, such as you can list SPs you have contacted with at present?
Could you send an email to filplus-app-review@fil.org with your official domain in order to confirm your identity? Email name should includes the issue id #770.

**Comment by Sunnyiscoming** [comment]
Any update here?

**Comment by Sunnyiscoming** [comment]
Close for no reply. You can resubmit your application if necessary.
