### ISSUE TITLE
[DataCap Application] Hebei Bow Tie Culture Media Co., Ltd.

### ISSUE THREAD

**Issue by sitie1219** [filecoin-project/filecoin-plus-large-datasets#773]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Hebei Bow Tie Culture Media Co., Ltd.
- Website / Social Media: www.lingjiecehua.com
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):3 PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):150TiB
- On-chain address for first allocation:f1ybpwddfwrzqf6ipeexupxlxm2g25bsokwv475ly

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Bowtie brand design is a new domestic brand strategy and design agency focusing on brand creation and brand image upgrade design, providing customers with one-stop brand integration design services in brand positioning, brand vision and terminal space.
LEADER bow tie design is a company with the mission of "creating effective brands for customers", gathering talents in related fields, and loyal to creating "natural" culture and "symbolic" brands. It has been exploring and focusing on brand design, visual design, packaging design, publication design, retail promotion and exhibition space design, space orientation logo, forming a comprehensive professional integrated service team.
```

What is the primary source of funding for this project?
```
Account from the company.
```

What other projects/ecosystem stakeholders is this project associated with?
```
No
```

## Use-case details

Describe the data being stored onto Filecoin
```
Primarily promotional images for events held on the website.
```

Where was the data in this dataset sourced from?
```
It comes from materials provided by our company and materials uploaded by users themselves.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://drive.google.com/drive/folders/1YbjZjhM7BrhCz_spWNh08kelqiqLlKY-?usp=sharing
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes
```

What is the expected retrieval frequency for this data?
```
Anyone interested in our brand or products can open it to view.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
permanent
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
China
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
We will use both online and offline transfers.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
Choose a storage provider that has deep pockets and understands project data.
```

How will you be distributing deals across storage providers?
```
We will distribute evenly to each storage provider.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes
```

**Comment by Sunnyiscoming** [comment]
![image](https://user-images.githubusercontent.com/105098820/190089994-b3787124-4830-4967-be44-a7f3d1f11174.png)
The website do not work. Please check it.
The data samples provided are documents, and it's hard to justify you having 5 pb data. Can you explain your data composition and provide sufficient data samples separately? How many copies will you store?
What's the relationship between you and organization? 
Can you provide more detailed information about other storage providers participated in this program, such as you can list SPs you have contacted with at present?

**Comment by Sunnyiscoming** [comment]
Any update here?

**Comment by Sunnyiscoming** [comment]
Close for no reply. You can resubmit your application if necessary.
