### ISSUE TITLE
[DataCap Application] Shanghai Yuanfeng information technology (Group) Co., Ltd

### ISSUE THREAD

**Issue by TerryNatalie** [filecoin-project/filecoin-plus-large-datasets#776]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Yuanfeng information technology
- Website / Social Media: http://www.yuanfeng.cn
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5 PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):150TiB
- On-chain address for first allocation: f1ukhdubpvapkakuthi7bedzrklqhparstxlv5epq

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Yuanfeng started in 2005 and formally established Yuanfeng Group Co., Ltd. in 2009. At present, more than 20 service centers have been set up in the country to focus on the research and development of new and high-tech e-commerce retail, provide customers with professional and complete online retail solutions, and help customers achieve success. As the unremitting pursuit and mission of Yuanfeng people, e business schools were established in 2019 to provide customers with all-round empowerment through technology + training + resources, Help customers achieve large-scale growth and formally enter the new era of technology + training. Yuanfeng group has more than 200 scientific research personnel and is in the leading position in the field of e-commerce technology. The full range of e-commerce software independently developed by the company has its own ecology, mainly including s2b2c new retail system based on artificial intelligence, community e-commerce system, live e-commerce system, small program e-commerce system, APP system, distribution system, cross-border e-commerce system, e-commerce ERP system, cloud cashier system, logistics distribution system, Dozens of software systems with independent intellectual property rights such as offline store face recognition system have won wide praise from many users with their advantages of safety, stability, efficiency and professionalism. In the past 15 years, Yuanfeng has served more than 300000 customers, including bee shopping, CCTV, Panasonic, Sichuan Airlines, China Railway, China Coal Group, industrial bank, UnionPay commerce, Xinhua Bookstore, Xi'an electric power, and signed cooperation agreements with many famous universities such as Shanghai University of Finance and economics and Fudan University. Yuanfeng group has been supported and affirmed by governments at all levels. It has won many honorary titles such as high-tech enterprise, double soft enterprise and high-tech achievement transformation enterprise issued by the state. It has reached deep cooperation with Baidu, Tencent, UnionPay, Alibaba, Netease and JD. In May 2020, Yuanfeng Group signed a strategic cooperation agreement with fengfangou to land on the capital market and realize the listing plan. Since then, Yuanfeng people have more confidence to face future challenges and opportunities, further strengthen the research and development in cloud computing, artificial intelligence and big data, keep pace with the times and grow with customers.
```

What is the primary source of funding for this project?
```
Appropriation from the Finance Department of Yuanfeng group
```

What other projects/ecosystem stakeholders is this project associated with?
```
No.
```

## Use-case details

Describe the data being stored onto Filecoin
```
Photo backup, company data and important encrypted data will be packaged by technology and desensitized before uploading.
```

Where was the data in this dataset sourced from?
```
Provide convenience for customers, and users of the company can directly upload data for storage
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
[Please answer here.](https://www.yuanfeng.cn/news/?p=981)
https://drive.google.com/drive/folders/1o_e4eSenOR2G8EeSxiiBCUveNytmrFYm?usp=sharing
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes, I confirm.
```

What is the expected retrieval frequency for this data?
```
It will be retrieved every 1-2 years.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
Long-term storage.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Around Asia.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Yes, we choose offline data transfer process. We have disks for it.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
Slack and Github are good platforms for us connecting with storage providers.We plan choosing 5 storage providers at first.
```

How will you be distributing deals across storage providers?
```
Following community rule, every sp will be distributed below 25% of whole deals. We'll pay attention to it.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes. We don't need support for the moment.
```

**Comment by Sunnyiscoming** [comment]
The data samples provided are jpg., and it's hard to justify you having 5 pb data. Can you explain your data composition and provide sufficient data samples separately? How many copies will you store?
What's the relationship between you and organization? 
Can you provide more detailed information about other storage providers participated in this program, such as you can list SPs you have contacted with at present?

**Comment by Sunnyiscoming** [comment]
Any update here?

**Comment by Sunnyiscoming** [comment]
Close for no reply. You can resubmit your application if necessary.
