### ISSUE TITLE
[DataCap Application] a1 Snack Institute

### ISSUE THREAD

**Issue by Blanchardaq** [filecoin-project/filecoin-plus-large-datasets#781]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Aiyi (Xiamen) Food Technology Co.
- Website / Social Media:www.a1life.cn
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):3PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):100TiB
- On-chain address for first allocation:f1rgzkzxkb66bmtiazgk64626jltjirxgchgfly6y

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
a1 Snack Institute was established in 2016, from the original intention of "for the family", to do dare to give, willing to give the family to eat safe food.
So far, a1® has more than 400 items in seven categories, including baking, nuts, meat products, marine products, fruits and vegetables, and has successfully created a number of popular products such as egg yolk crisp, cloud cake and watermelon toast. Adopt the omni-channel model of online, offline and new retail. Offline covers more than 500,000 terminal outlets nationwide; the accumulated users of the small program are more than 200w, and there are more than 50 stores nationwide.
The business concept of a1® team has been widely recognized by the industry, and has received multiple rounds of investment from many first-tier institutions such as Today Capital, CICC Capital and China Resources Capital in the past five years, making it one of the new consumer unicorn companies.

```

What is the primary source of funding for this project?
```
Sales of the company's products
```

What other projects/ecosystem stakeholders is this project associated with?
```
no
```

## Use-case details

Describe the data being stored onto Filecoin
```
a1 Snack Institute, a subsidiary of Aiyi (Xiamen) Food Technology Co., Ltd, has opened a flagship store in Tmall, a comprehensive online shopping mall in China. Therefore, a large amount of data is generated during the operation and sales of the online store, including product quotations, detail pages, original pictures and videos of the products, the The frequency of site records when the goods are on the shelves, product reviews, etc. The main form of our data is pictures, text and videos. Our data is open source and will not cause disputes. We hope to provide service and help for our data storage through Filecoin.

```

Where was the data in this dataset sourced from?
```
Public data generated in the course of brand operations and merchandising.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://drive.google.com/file/d/1HNDIi-lgByIVNJv7mJ9nkXSl4haQ-diT/view?usp=sharing
https://drive.google.com/file/d/14H3JoSWLr1Eph2bO7ISzXEGzwZ_7ui3k/view?usp=sharing
https://drive.google.com/file/d/1REfufnO6wIhjXBYA31yJuUN5A127npN3/view?usp=sharing
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
yes
```

What is the expected retrieval frequency for this data?
```
Once a year
```

For how long do you plan to keep this dataset stored on Filecoin?
```
2.5 years
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
China
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
We will upload our data to the web server, communicate with the storage provider, download and propose offline transactions.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We are willing to work with any supplier who has the storage conditions and experience.
```

How will you be distributing deals across storage providers?
```
We will use IPFS distributed storage to equitably distribute to providers.

```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
We have sufficient funds and resources
```

**Comment by Sunnyiscoming** [comment]
Can you explain your data composition and provide sufficient data samples separately? How many copies will you store?
What's the relationship between you and organization? 
Can you provide more detailed information about other storage providers participated in this program, such as you can list SPs you have contacted with at present?

**Comment by Sunnyiscoming** [comment]
Close for no reply. You can resubmit your application if necessary.
