### ISSUE TITLE
[DataCap Application] Shanxi Yi Tong Tianxia Network Technology Co.

### ISSUE THREAD

**Issue by yttianxia** [filecoin-project/filecoin-plus-large-datasets#794]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Shanxi Yi Tong Tianxia Network Technology Co.
- Website / Social Media:www.etwod.com
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):2.6 PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):207TiB
- On-chain address for first allocation:f1pld6nnuiawiwkzuoxc76vjvbfoqasbflyxdupsa

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Founded in April 2008, E-Tong Tianxia Group is a group enterprise with "Digital + Industry" as its core. Adhering to the basic platform of "hand in hand, win together" and the business philosophy of "let users praise, make the enterprise evergreen", we have built a digital platform (Dragon Peak, Piggyback Treasure, Agricultural Network 365, network freight digital platform, cross-border e-commerce group selection service platform We have built a matrix of online + offline integrated development of industrial platform covering digital platform (Longtop, Pikdotbao, Nong.com 365, online freight digital platform, cross-border e-commerce group selection service platform), industrial park (Smart Fishery Green Ecological Industrial Park, Network Cargo Digital Industrial Park, Cross-border E-commerce Industrial Park, Digital Traffic Industrial Park, Industrial Incubation Base), and industrial support (E-Tong Technology, E-Tong Investment, E-Tong Management) to form an open and infinite growth ecosystem, providing professional platform for enterprises and millions of users. R&D and operation services.
```

What is the primary source of funding for this project?
```
Company operating income
```

What other projects/ecosystem stakeholders is this project associated with?
```
NO
```

## Use-case details

Describe the data being stored onto Filecoin
```
Company video material, live video
```

Where was the data in this dataset sourced from?
```
Corporate Marketing Department
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://drive.google.com/drive/folders/17wqbHttktp0cSszwriqtudsvqRxFuzVP?usp=sharing
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
yes
```

What is the expected retrieval frequency for this data?
```
2-3 times a year
```

For how long do you plan to keep this dataset stored on Filecoin?
```
1-3 years
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Shanghai, China
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
offline
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
Strong, stable service providers
```

How will you be distributing deals across storage providers?
```
Average distribution
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, I have enough money.
```

**Comment by Sunnyiscoming** [comment]
Can you explain your data composition and provide sufficient data samples separately? How many copies will you store?
What's the relationship between you and organization? 
Can you provide more detailed information about other storage providers participated in this program, such as you can list SPs you have contacted with at present?

**Comment by Sunnyiscoming** [comment]
Any update here?

**Comment by Sunnyiscoming** [comment]
Close for no reply. You can resubmit your application if necessary.
