### ISSUE TITLE
[DataCap Application] Qingdao Regency Hotel

### ISSUE THREAD

**Issue by htlw** [filecoin-project/filecoin-plus-large-datasets#797]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Qingdao Regency Hotel
- Website / Social Media: http://www.regencyhotelqd.com/home
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):4PIB
- Weekly allocation of DataCap requested (usually between 1-100TiB):100TiB
- On-chain address for first allocation: f1fzjtvybe74vk5odtxkwafb4v5jryrithg2ihwdq

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Qingdao Regency Hotel located in the center of Qingdao's most prosperous eastern business district, the hotel is surrounded by financial, catering, entertainment and shopping facilities, 70 minutes' drive from Qingdao Jiaozhou International Airport and 20 minutes' drive from the railway station; It is a 5-minute drive from the municipal government, May Fourth Square and the Olympic Sailing Center.

As the first five-star hotel in Shandong Province, since its opening, the hotel has successfully received many dignitaries including former German Prime Minister Kohl, former Singapore Senior Minister Lee Kuan Yew, Singapore Prime Minister Lee Hsien Loong, former United Nations Secretary-General Ban Ki-moon, former South Korean Prime Minister Han Seung-so, former Special Assistant to the Prime Minister of Japan, Speaker and Mayor of Kyoto Prefecture, Mayor of Miyazaki City, former Chairman of the Russian House of Lords, Commander of multinational navies and many Fortune 500 CEOs.

In June 2018, as the key foreign guest reception hotel of the SCO Qingdao Summit, we successfully received the then President of Iran Hassan Rouhani and his delegation, as well as the visiting Presidents of Belarus, Pakistan and Afghanistan. The President of Iran and the visiting presidents and dignitaries of various countries have given high praise to the hotel's perfect hardware facilities, head of state-level distinguished services and special catering and cuisine. 

The hotel has 395 rooms, each of which has been carefully decorated with a special style. The hotel also has meeting rooms, swimming pools, Chinese restaurants, Western restaurants, banquet halls, multi-functional halls, beauty salons, gyms, billiards, indoor golf, bowling, outdoor tennis courts, etc., with rich venues and perfect services for users.
```

What is the primary source of funding for this project?
```
Own funds，our hotel has been established for a long time, with high praise rate, high occupancy rate and strong capital.
```

What other projects/ecosystem stakeholders is this project associated with?
```
No stakeholders 
```

## Use-case details

Describe the data being stored onto Filecoin
```
The data stored on the FIlecoin network is the data generated by our hotel. After the determination of our department, we decided to first store the videos or pictures about hotel meetings, restaurants, guest rooms, and public areas stored on our employees' computers to the network for backup to prevent data loss due to the aging of the computers. Then, every day The data that is generated and needs to be backed up is also stored on the filecoin network for backup.
```

Where was the data in this dataset sourced from?
```
From hotel rooms, hotel public facilities such as swimming pools, banquet halls, conference rooms, restaurants, etc. 
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://drive.google.com/drive/folders/1_t624AIFZuUc1F8kZP8GDzryXsuBAq3W?usp=sharing
https://drive.google.com/drive/folders/1BUHscdv2Thp4th9mUJsKTFVfrI2O0Apd?usp=sharing
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Confirm
```

What is the expected retrieval frequency for this data?
```
Retrieval is carried out according to the actual situation, there is no fixed frequency, it may be retrieval once a month or once a year.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
about 36 months
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
We have approached sp s from Vietnam and Singapore on slack and filfox, and we tend to store them in Vietnam or Singapore.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
We tend to offline transfer, but we hope sp can provide hard drive and pay postage.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We plan to store the data in multiple SPs to improve the reliable storage of the data
```

How will you be distributing deals across storage providers?
```
Fair and equitable distribution, try to allow more storage providers to participate in the data storage process
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes
```

**Comment by htlw** [comment]
#515

**Comment by htlw** [comment]
If possible, please review it as soon as possible. Thank you.

**Comment by raghavrmadya** [comment]
- Please provide SP IDs of the Sps you have reached to in Singapore and Vietnam. Also the data samples provided are promotional videos not what you mentioned in the description above. Either provide data samples on hotel meetings, restaurants, guest rooms, and public areas and provide evidence that it is public data

**Comment by htlw** [comment]
Hello, this is some of the SP IDs we are contacting, f01238, f01909496, f0145385, f01672748, and f010254. Since you have not approved the quota for us, we have not yet determined which IDs to cooperate with. But we promise that we will strictly abide by your requirements and use at least 4 nodes to encapsulate, and each node does not exceed 30%.

In addition, this is the video of our public area, I would like to say, what we want to store is all the publicly available and valuable data generated by our hotel, including the content of the public area, the hotel's promotional video, the event held Records, etc. Since the content of the hotel promotional video is relatively small, we only express that the content of the public area is mainly stored, please understand.

https://drive.google.com/drive/folders/190NByGd1HbeRzbmDcV0i0sZfFQqto31M
https://drive.google.com/drive/folders/1_t624AIFZuUc1F8kZP8GDzryXsuBAq3W?usp=sharing
https://drive.google.com/drive/folders/1BUHscdv2Thp4th9mUJsKTFVfrI2O0Apd?usp=sharing

**Comment by raghavrmadya** [comment]
the samples provided are recorded on a mobile device not cctv footage. Please explain why

**Comment by htlw** [comment]
Hello, I remember you once asked me if I need to store CCTV , I replied that our existing data can meet the quota we applied for, therefore, we do not need to store CCTV  so no sample of CCTV is provided .
I want to know, do you prefer us to store CCTV?

**Comment by raghavrmadya** [comment]
We don't have a preference for what you store but if you say you are going to store "hotel public facilities such as swimming pools, banquet halls, conference rooms, restaurants, etc. ", provide samples for that

**Comment by htlw** [comment]
As a five-star hotel, the monitoring video of the hotel is directly connected to the public relations system, so we do not have permission to obtain the monitoring video. We provide any other data to prove that our hotel is applying for FIL+.

**Comment by Sunnyiscoming** [comment]
Large datasets provide Datacap for dataset storage projects larger than 500TB. 
At present, you need to prove that you will store a dataset, not that you are applying for FIL+. If you don't have access to surveillance data, what types of data will you store and how much data will you store? Please provide enough data samples for each type of data you will store.

**Comment by htlw** [comment]
Hi, Sunnyisoming, we apply for 4P to store the data of our hotel. As you can see, our hotel has been established for more than 30 years. In the past 30 years, our data has not been well stored, so that we have lost many valuable data. We hope to improve our storage system and back up our data through Filecoin.
Our hotel has nearly 100 employees, each of whom has a large amount of data stored in their computers. In addition, we are also generating a lot of data every day. Our department needs to make a summary every week. The Food and Beverage Department and the Housekeeping Department have an audit system every day, attendance system, courtesy and etiquette, event planning and holding of holidays, hotel promotional videos, promotional documents, etc, These are the data we will store on the Filecoin network. Below, we provide computer data screenshots of some of our employees:
![001](https://user-images.githubusercontent.com/80449172/191682049-66a01c30-e69f-4155-810e-4289c761c413.png)
![002](https://user-images.githubusercontent.com/80449172/191682054-5d11f393-f641-45cb-a545-80999d86b757.png)
![003](https://user-images.githubusercontent.com/80449172/191682058-d5b470c8-21d7-4cdf-908e-0948d9da4136.png)
![004](https://user-images.githubusercontent.com/80449172/191682064-9af6f1ac-dbcf-40c7-9eac-f6228aa641b4.png)
![005](https://user-images.githubusercontent.com/80449172/191682069-fbd15330-0f5c-46ff-89bb-b631a7fadaa1.png)
![006](https://user-images.githubusercontent.com/80449172/191682075-cb70077b-1915-4c91-9374-318a906f54b6.png)
![007](https://user-images.githubusercontent.com/80449172/191682089-809922d0-cdad-4a80-8be4-34b50514acba.png)
![008](https://user-images.githubusercontent.com/80449172/191682102-84949a49-9ee9-4d34-8e8b-9aebcfbc54a2.png)
![009](https://user-images.githubusercontent.com/80449172/191682110-5cabd223-12dd-422e-8d26-fd1ad2e94978.png)
![010](https://user-images.githubusercontent.com/80449172/191682116-ded4f240-7c9c-4c60-a3ec-6a0e77536081.png)
![011](https://user-images.githubusercontent.com/80449172/191682145-c10ec774-7980-4f45-af06-730a4c78ea14.png)
![012](https://user-images.githubusercontent.com/80449172/191682155-14fbaeeb-c643-400b-ba72-37f2ddc6084f.png)
![013](https://user-images.githubusercontent.com/80449172/191682162-7488804f-4f96-4055-a787-fab964d75c92.png)
![014](https://user-images.githubusercontent.com/80449172/191682167-a1a4086d-800c-426f-bf33-e1e51142a363.png)
![015](https://user-images.githubusercontent.com/80449172/191682175-2ee541c1-4b52-47dc-8516-ee3b9ec9d05b.png)
![016](https://user-images.githubusercontent.com/80449172/191682178-ad05e0b7-3fd0-4bf3-aa19-e001553785ff.png)

**Comment by Sunnyiscoming** [comment]
Your data contains a lot of internal data. Are you sure it's all public?
![image](https://user-images.githubusercontent.com/105098820/192974202-45a721bc-e852-48db-97fe-d10efa219714.png)

In addition, FIL+ large dataset is set for existing datasets. If a large amount of data has been lost, leaving only a small amount of computer data, it may not be appropriate to apply for FIL+ big data set oh.

**Comment by htlw** [comment]
Yes, some are private data. The purpose of the screenshot is to show that we currently have a large amount of data to store, and once the application is approved, we will review the data before it is uploaded to ensure that sensitive data is not uploaded. In addition, we only have a very small amount of data that has been lost due to hard drive/computer failure,
However, the majority of the data is still intact, there is a lot of historical that takes up a lot of space, but needs to be stored for review & audit purpose,
and we are still updating a large amount of data, so we hope we can join FIL+ project to improve our storage conditions.

**Comment by Sunnyiscoming** [comment]
What is the total amount of open data and how many copies do you want to back up? What types of data are these data? Please provide sufficient examples for each type of data.

**Comment by Sunnyiscoming** [comment]
Any update?

**Comment by htlw** [comment]
In the past few weeks, we have consolidated most of the public data from our colleagues' computers, including some 
data files, daily operation documents, hotel related videos and pictures, industry information, training materials,
for now we have more than 700 TiB of data, and still a little more under consolidation, if possible we
 would like to store 5 copies of these data. I have updated more sample data, link listed below for your reference:
 https://drive.google.com/drive/folders/1HpqXrekT0xYpu-006l6HKfKaPr-Lskqx?usp=sharing

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 4PiB

**Expected weekly DataCap usage rate**

> 100TiB

**Client address**

>f1fzjtvybe74vk5odtxkwafb4v5jryrithg2ihwdq

**Comment by Sunnyiscoming** [comment]
Hey @htlw , if you still want to apply for datacap, you can ask notaries to do client due diligence in slack channel. https://app.slack.com/client/TEHTVS1L6/C036JKD8NVA/thread/C03BG1MNQ4T-1673888660.823499

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Looking at your application i have some questions:
As you are brand new on Github and have no history of past applications it seems to me that applying for 4PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?

Can you show us visible proof of the size of your data and the storage systems you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230232885049356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!

**Comment by htlw** [comment]
[sendmail](https://user-images.githubusercontent.com/80449172/184080715-f5737dc0-9866-4294-bdda-542207790a7f.jpg)

**Comment by htlw** [comment]
![image](https://user-images.githubusercontent.com/80449172/219584514-a68fb306-351b-4084-b3d3-a75cc01bfd6f.png)

**Comment by htlw** [comment]
> Hey @htlw , if you still want to apply for datacap, you can ask notaries to do client due diligence in slack channel. https://app.slack.com/client/TEHTVS1L6/C036JKD8NVA/thread/C03BG1MNQ4T-1673888660.823499

Ok， thanks.

**Comment by htlw** [comment]
We have contacted many notaries  here, why don't they reply me.
The email has been sent, what else do I need to do?

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Can you fill out [this form](https://form.jotform.com/230337462961356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!

**Comment by mikezli** [comment]
Thank you for contacting me, as a first round, I decided to help you

**Comment by mikezli** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacea6dfxxpv5k4u3qpn7lvhjej6gg6zzeopl4r4jdif4b7nol5iudr6 
#### Address 
> f1fzjtvybe74vk5odtxkwafb4v5jryrithg2ihwdq
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1dnb3uz7sylxk6emti3ififcvu3nlufnnsjui6ea
#### Id
> 4ba9f9c6-4393-48e6-9f47-1ebbe4e5ede3
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacea6dfxxpv5k4u3qpn7lvhjej6gg6zzeopl4r4jdif4b7nol5iudr6

**Comment by igoovo** [comment]
The first round of support, hope that the process of all compliance.

**Comment by igoovo** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb5cmauz3paf6thkwdjwocliso2b53zno6avjnpq2ikgqktlaoa6w 
#### Address 
> f1fzjtvybe74vk5odtxkwafb4v5jryrithg2ihwdq
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1shnsfayxqll77svffaxnjenms7bbbysbqcatrpy
#### Id
> 4ba9f9c6-4393-48e6-9f47-1ebbe4e5ede3
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb5cmauz3paf6thkwdjwocliso2b53zno6avjnpq2ikgqktlaoa6w

**Comment by lupiruw** [comment]
ok?

**Comment by htlw** [comment]
@Sunnyiscoming Can you help us reopen this application?

**Comment by htlw** [comment]
@Sunnyiscoming @raghavrmadya  Can you help us reopen this application?

**Comment by cryptowhizzard** [comment]
checker:manualTrigger

**Comment by cryptowhizzard** [comment]
![Scherm­afbeelding 2023-08-22 om 12 10 17](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/36404435/e8a3a202-0439-4a0e-8dec-fa971982aa3f)

I have a questions here since your last datacap was sent only to yourself and not to others.

Can you elaborate?

@filplus-govteam can you please track this application before reopening?

**Comment by nickboot** [comment]
Due to the lack of data in the first batch, only two SP were sent.
The latter quota will certainly be distributed to many SP and will certainly abide by the FIL+ rules.
Thank you for your reply!

**Comment by htlw** [comment]
Due to the lack of data in the first batch, only two SP were sent.
The latter quota will certainly be distributed to many SP and will certainly abide by the FIL+ rules.
Thank you for your reply!

**Comment by clriesco** [comment]
Sorry, not authorized, I just rolled back application auto closing due to github actions misconfiguration.
