### ISSUE TITLE
[DataCap Application] NEXRAD - Next Generation Weather Radar

### ISSUE THREAD

**Issue by flyworker** [filecoin-project/filecoin-plus-large-datasets#80]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name:  NEXRAD - FilSwan
- Website / Social Media: https://www.filswan.com Slack: http://filswan.slack.com​ Discord: http://discord.gg/Uw5jCGqc
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 2 PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100 TiB
- On-chain address for first allocation: f1r3d25hl2y7rqlsu2mgczdethy4qqjmkfdlmibfq

## Project details

Share a brief history of your project and organization.
```
Real-time and archival data from the Next Generation Weather Radar (NEXRAD) network.
The Next Generation Weather Radar (NEXRAD) is a network of 160 high-resolution Doppler radar sites that detects precipitation and atmospheric movement and disseminates data in approximately 5 minute intervals from each site. NEXRAD enables severe storm prediction and is used by researchers and commercial enterprises to study and address the impact of weather across multiple sectors.

Filswan provides a decentralized edge infrastructure marketplace and software that moves data storage and analysis as close as necessary on Web 3.0.
```

What is the primary source of funding for this project?
```
FilSwan  Foundation Provide funding for it
```

What other projects/ecosystem stakeholders is this project associated with?
```
enterprise-sp-wp, Deal Market, Asia working group
```

## Use-case details

Describe the data being stored onto Filecoin
```
The Next Generation Weather Radar (NEXRAD) is a network of 160 high-resolution Doppler radar sites that detects precipitation and atmospheric movement and disseminates data in approximately 5 minute intervals from each site. NEXRAD enables severe storm prediction and is used by researchers and commercial enterprises to study and address the impact of weather across multiple sectors.
```

Where was the data in this dataset sourced from?
```
Images  compressed (compressed with gzip).
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
The following animation follows the track of the storm, with the the sky changing color depending on the local time.
https://ipfs.io/ipfs/QmNUbPstcPCDj5r1QB39PesVNoLhgELSE9DBHZNhk3NSbV?filename=1*ioHzusnUyldf0P8C7XULrA.gif
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes
```

What is the expected retrieval frequency for this data?
```
Anyone interested in retrieving this datacet for R&D purpose
```

For how long do you plan to keep this dataset stored on Filecoin?
```
540 days
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Asia, North America
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Through filswan autobid process and [swan provider](https://docs.filswan.com/run-swan-provider/overview). It is an offline data transfer process.

```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
FilSwan have a reputation system, any storage provider has score higher than 80 will have the right to get the deal.
```

How will you be distributing deals across storage providers?
```
Based on the reputation score we followed an gaussian distribution of the deals to different miners and we will have multiple copies across miners.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```No, we have enough resource to perform all the activities.
```

**Comment by galen-mcandrew** [comment]
## Multisig Notary requested
#### Total DataCap requested 
> 2PiB
#### Expected weekly DataCap usage rate 
> 100TiB

**Comment by IreneYoung** [comment]
@flyworker Hi Charles, is NEXRAD one of new features on Filswan platform or anything else? And probably you didn't answer properly to the question 5, "Where was the data in this dataset sourced from?". So please leave your answer here, thanks.

**Comment by flyworker** [comment]
Hi  @IreneYoung , the data source comes from [Next Generation Weather Radar ](https://www.ncei.noaa.gov/products/radar/next-generation-weather-radar ) it can also be found here https://registry.opendata.aws/noaa-nexrad

It is not a new feature of filswan, but we will use filswan platform for distributing data as usual.

**Comment by IreneYoung** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebkvb3ybfxajz3qpsfzpo2idqsutkv3fpgsvtvojcrgjlg54edwjo 
#### Address 
> f1r3d25hl2y7rqlsu2mgczdethy4qqjmkfdlmibfq
#### Datacap Allocated
> 50TiB
#### Signer Address
> f1d4gmpqz3execjj2wvrxuuhvbms5mzh7t7yqrviq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebkvb3ybfxajz3qpsfzpo2idqsutkv3fpgsvtvojcrgjlg54edwjo

**Comment by Reiers** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceay4qjcktdtekzpbyrqfrtrv6wsvpiymlxws4b65hwxat77mzbc6s 
#### Address 
> f1r3d25hl2y7rqlsu2mgczdethy4qqjmkfdlmibfq
#### Datacap Allocated
> 50TiB
#### Signer Address
> f1oz43ckvmtxmmsfzqm6bpnemqlavz4ifyl524chq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceay4qjcktdtekzpbyrqfrtrv6wsvpiymlxws4b65hwxat77mzbc6s

**Comment by mr-spaghetti-code** [comment]
Hi,

It looks like you received 50TiBs of DataCap to date but have spent less than 20% of it so far.

We would love to understand if there's anything holding you back. We are working hard to make the data onboarding process easier for clients like you and your feedback is very valuable. If you have a moment, please fill in this survey: https://forms.gle/s6AuTXZPZSMokscLA

If you have any feedback or would like to consult with an expert, please let me know. 

Thanks,

João Fiadeiro
Product Manager, Large Data Client Onboarding
Protocol Labs

**Comment by flyworker** [comment]
Hi João,
Thanks for your concern, we were working on the data download and sorting the data deals. While we have 3 project on going, they are on our pipeline.
We will let the team start the distribution process with filswan.
thanks

**Comment by kernelogic** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacearo26c6oh7xynsgegpkpdf3e2grn5k2jjbuicstirhytvw4ez6vu 
#### Address 
> f1r3d25hl2y7rqlsu2mgczdethy4qqjmkfdlmibfq
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacearo26c6oh7xynsgegpkpdf3e2grn5k2jjbuicstirhytvw4ez6vu

**Comment by jamerduhgamer** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebiwjqchxvyzggk5uper2uu7runfgzcegjaj7yjfmlhlflxq3wnmo 
#### Address 
> f1r3d25hl2y7rqlsu2mgczdethy4qqjmkfdlmibfq
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1ypuqpi4xn5q7zi5at3rmdltosozifhqmrt66vhq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebiwjqchxvyzggk5uper2uu7runfgzcegjaj7yjfmlhlflxq3wnmo

**Comment by kernelogic** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebhchegjvogsgzcz5qopq6a7kh33e7uzou6arckv73xqn4toujmmg 
#### Address 
> f1r3d25hl2y7rqlsu2mgczdethy4qqjmkfdlmibfq
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebhchegjvogsgzcz5qopq6a7kh33e7uzou6arckv73xqn4toujmmg

**Comment by liyunzhi-666** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced5gi2srnr46xpsugcogai3xscfw4f54fuispkyweuqtmr7vp5i5y 
#### Address 
> f1r3d25hl2y7rqlsu2mgczdethy4qqjmkfdlmibfq
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1pszcrsciyixyuxxukkvtazcokexbn54amf7gvoq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced5gi2srnr46xpsugcogai3xscfw4f54fuispkyweuqtmr7vp5i5y

**Comment by kernelogic** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebrjkucgj7wh24zcsaj6jppc2c7kpeqwatw3s7lg3kmqecy2nknr4 
#### Address 
> f1r3d25hl2y7rqlsu2mgczdethy4qqjmkfdlmibfq
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebrjkucgj7wh24zcsaj6jppc2c7kpeqwatw3s7lg3kmqecy2nknr4

**Comment by xingjitansuo** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedexz3dw7557yjo2zjdltqy2vyc5hpojevckhqvlxq5r4j7axedjq 
#### Address 
> f1r3d25hl2y7rqlsu2mgczdethy4qqjmkfdlmibfq
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1a2lia2cwwekeubwo4nppt4v4vebxs2frozarz3q
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedexz3dw7557yjo2zjdltqy2vyc5hpojevckhqvlxq5r4j7axedjq

**Comment by IreneYoung** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebpd65xtz2oeugnhtsawb4yhv6t53zidlvezc3fp3dvqzz544jh26 
#### Address 
> f1r3d25hl2y7rqlsu2mgczdethy4qqjmkfdlmibfq
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1d4gmpqz3execjj2wvrxuuhvbms5mzh7t7yqrviq
#### Id
> c88919cb-dd81-4982-a47d-cc8c9b83ecfe
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebpd65xtz2oeugnhtsawb4yhv6t53zidlvezc3fp3dvqzz544jh26

**Comment by kernelogic** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecusffgr7nafe3e62cqxpns3uvpuvs5ud2ttdjn6e6d7x47lem72q 
#### Address 
> f1r3d25hl2y7rqlsu2mgczdethy4qqjmkfdlmibfq
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### Id
> c88919cb-dd81-4982-a47d-cc8c9b83ecfe
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecusffgr7nafe3e62cqxpns3uvpuvs5ud2ttdjn6e6d7x47lem72q

**Comment by kernelogic** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaimkmu5kay3jef5kq3fw26ywobm2snsdcb7rth5qy3dzdzk4k3n6 
#### Address 
> f1r3d25hl2y7rqlsu2mgczdethy4qqjmkfdlmibfq
#### Datacap Allocated
> 498.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### Id
> 7678358a-28e1-4434-8ae4-8a8829f7a33a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaimkmu5kay3jef5kq3fw26ywobm2snsdcb7rth5qy3dzdzk4k3n6

**Comment by filplus-checker** [comment]
## DataCap and CID Checker Report[^1]
 - Organization: ` NEXRAD - FilSwan`
 - Client: `f1r3d25hl2y7rqlsu2mgczdethy4qqjmkfdlmibfq`
### Storage Provider Distribution
The below table shows the distribution of storage providers that have stored data for this client.

If this is the first time a provider takes verified deal, it will be marked as `new`.

For most of the datacap application, below restrictions should apply.
 - Storage provider should not exceed 25% of total datacap.
 - Storage provider should not be storing duplicate data for more than 20%.
 - Storage provider should have published its public IP address.
 - All storage providers should be located in different regions.

⚠️ 68.44% of total deal sealed by [f01955034](https://filfox.info/en/address/f01955034) are duplicate data.

⚠️ 52.38% of total deal sealed by [f01938223](https://filfox.info/en/address/f01938223) are duplicate data.

⚠️ 63.16% of total deal sealed by [f01955030](https://filfox.info/en/address/f01955030) are duplicate data.

⚠️ 61.61% of total deal sealed by [f01955028](https://filfox.info/en/address/f01955028) are duplicate data.

⚠️ 46.82% of total deal sealed by [f01947280](https://filfox.info/en/address/f01947280) are duplicate data.

⚠️ 22.90% of total deal sealed by [f01911369](https://filfox.info/en/address/f01911369) are duplicate data.

⚠️ [f01911369](https://filfox.info/en/address/f01911369) has unknown IP location.

⚠️ 37.46% of total deal sealed by [f01146045](https://filfox.info/en/address/f01146045) are duplicate data.

⚠️ 38.12% of total deal sealed by [f01786736](https://filfox.info/en/address/f01786736) are duplicate data.

⚠️ [f01919426](https://filfox.info/en/address/f01919426) has unknown IP location.

⚠️ [f01981571](https://filfox.info/en/address/f01981571) has unknown IP location.

⚠️ 31.21% of total deal sealed by [f0773157](https://filfox.info/en/address/f0773157) are duplicate data.

⚠️ [f0520660](https://filfox.info/en/address/f0520660) has unknown IP location.

| Provider                                                    |                           Location | Total Deals Sealed | Percentage | Unique Data | Duplicate Deals |
| :---------------------------------------------------------- | ---------------------------------: | -----------------: | ---------: | ----------: | --------------: |
| [f01955034](https://filfox.info/en/address/f01955034)`new`  |             Hangzhou, Zhejiang, CN |         233.59 TiB |     16.39% |   73.72 TiB |          68.44% |
| [f01938223](https://filfox.info/en/address/f01938223)`new`  |               Montréal, Quebec, CA |         222.91 TiB |     15.64% |  106.16 TiB |          52.38% |
| [f01955030](https://filfox.info/en/address/f01955030)       |             Hangzhou, Zhejiang, CN |         199.88 TiB |     14.02% |   73.63 TiB |          63.16% |
| [f01955028](https://filfox.info/en/address/f01955028)       |             Hangzhou, Zhejiang, CN |         191.63 TiB |     13.44% |   73.56 TiB |          61.61% |
| [f01947280](https://filfox.info/en/address/f01947280)       |             Hangzhou, Zhejiang, CN |         178.16 TiB |     12.50% |   94.75 TiB |          46.82% |
| [f01911369](https://filfox.info/en/address/f01911369)       |                            Unknown |          80.94 TiB |      5.68% |   62.41 TiB |          22.90% |
| [f01146045](https://filfox.info/en/address/f01146045)       |           Singapore, Singapore, SG |          64.81 TiB |      4.55% |   40.53 TiB |          37.46% |
| [f01786736](https://filfox.info/en/address/f01786736)       |          Saint-Gabriel, Quebec, CA |          50.58 TiB |      3.55% |   31.30 TiB |          38.12% |
| [f01940076](https://filfox.info/en/address/f01940076)       | Hong Kong, Central and Western, HK |          24.47 TiB |      1.72% |   24.47 TiB |           0.00% |
| [f01919426](https://filfox.info/en/address/f01919426)       |                            Unknown |          21.88 TiB |      1.53% |   21.88 TiB |           0.00% |
| [f01981571](https://filfox.info/en/address/f01981571)       |                            Unknown |          21.52 TiB |      1.51% |   21.52 TiB |           0.00% |
| [f01876488](https://filfox.info/en/address/f01876488)       |  Ho Chi Minh City, Ho Chi Minh, VN |          20.91 TiB |      1.47% |   20.91 TiB |           0.00% |
| [f079426](https://filfox.info/en/address/f079426)           |           Singapore, Singapore, SG |          16.84 TiB |      1.18% |   16.84 TiB |           0.00% |
| [f02401](https://filfox.info/en/address/f02401)             |        Raleigh, North Carolina, US |          16.75 TiB |      1.18% |   16.75 TiB |           0.00% |
| [f0447183](https://filfox.info/en/address/f0447183)         |          Indianapolis, Indiana, US |          13.72 TiB |      0.96% |   13.72 TiB |           0.00% |
| [f01072221](https://filfox.info/en/address/f01072221)       |        Los Angeles, California, US |           7.11 TiB |      0.50% |    6.39 TiB |          10.11% |
| [f01402814](https://filfox.info/en/address/f01402814)       |           Singapore, Singapore, SG |           6.38 TiB |      0.45% |    6.34 TiB |           0.49% |
| [f0187709](https://filfox.info/en/address/f0187709)         |                 Moscow, Moscow, RU |           4.75 TiB |      0.33% |    4.59 TiB |           3.29% |
| [f01886797](https://filfox.info/en/address/f01886797)       |    Vancouver, British Columbia, CA |           4.56 TiB |      0.32% |    4.53 TiB |           0.68% |
| [f01163272](https://filfox.info/en/address/f01163272)       |                Perm, Perm Krai, RU |           3.88 TiB |      0.27% |    3.88 TiB |           0.00% |
| [f01222595](https://filfox.info/en/address/f01222595)       |                 Moscow, Moscow, RU |           3.66 TiB |      0.26% |    3.66 TiB |           0.00% |
| [f01858429](https://filfox.info/en/address/f01858429)       |          Boston, Massachusetts, US |           3.53 TiB |      0.25% |    3.53 TiB |           0.00% |
| [f01896422](https://filfox.info/en/address/f01896422)       |            Fremont, California, US |           3.00 TiB |      0.21% |    3.00 TiB |           0.00% |
| [f0773157](https://filfox.info/en/address/f0773157)         |            Fremont, California, US |           2.70 TiB |      0.19% |    1.86 TiB |          31.21% |
| [f010088](https://filfox.info/en/address/f010088)           |            Everett, Washington, US |           2.67 TiB |      0.19% |    2.52 TiB |           5.85% |
| [f01398391](https://filfox.info/en/address/f01398391)       |               Chengdu, Sichuan, CN |           2.36 TiB |      0.17% |    2.20 TiB |           6.62% |
| [f01225882](https://filfox.info/en/address/f01225882)       |      Burnaby, British Columbia, CA |           2.06 TiB |      0.14% |    2.06 TiB |           0.00% |
| [f03624](https://filfox.info/en/address/f03624)             |              Nürnberg, Bavaria, DE |           2.03 TiB |      0.14% |    2.03 TiB |           0.00% |
| [f01390330](https://filfox.info/en/address/f01390330)       |                 Xi’an, Shaanxi, CN |           1.75 TiB |      0.12% |    1.75 TiB |           0.00% |
| [f033356](https://filfox.info/en/address/f033356)           |                   Seoul, Seoul, KR |           1.70 TiB |      0.12% |    1.70 TiB |           0.00% |
| [f08399](https://filfox.info/en/address/f08399)             |            Seattle, Washington, US |           1.66 TiB |      0.12% |    1.66 TiB |           0.00% |
| [f047419](https://filfox.info/en/address/f047419)           |       North Prairie, Wisconsin, US |           1.44 TiB |      0.10% |    1.34 TiB |           6.52% |
| [f0717969](https://filfox.info/en/address/f0717969)         |        Los Angeles, California, US |           1.41 TiB |      0.10% |    1.41 TiB |           0.00% |
| [f0240185](https://filfox.info/en/address/f0240185)         |            Clifton, New Jersey, US |           1.41 TiB |      0.10% |    1.41 TiB |           0.00% |
| [f03488](https://filfox.info/en/address/f03488)             |                   Seoul, Seoul, KR |           1.38 TiB |      0.10% |    1.16 TiB |          15.91% |
| [f0214334](https://filfox.info/en/address/f0214334)`new`    |               Gwangju, Gwangju, KR |           1.28 TiB |      0.09% |    1.28 TiB |           0.00% |
| [f0143858](https://filfox.info/en/address/f0143858)         |            Clifton, New Jersey, US |           1.19 TiB |      0.08% |    1.19 TiB |           0.00% |
| [f03223](https://filfox.info/en/address/f03223)             |           San Jose, California, US |           1.17 TiB |      0.08% |    1.14 TiB |           2.67% |
| [f030379](https://filfox.info/en/address/f030379)           |                   Seoul, Seoul, KR |           1.02 TiB |      0.07% |    1.02 TiB |           0.00% |
| [f01859603](https://filfox.info/en/address/f01859603)       |            Shenzhen, Guangdong, CN |           1.00 TiB |      0.07% |    1.00 TiB |           0.00% |
| [f01683871](https://filfox.info/en/address/f01683871)       |               Gwangju, Gwangju, KR |         448.00 GiB |      0.03% |  448.00 GiB |           0.00% |
| [f0240456](https://filfox.info/en/address/f0240456)         |               Chengdu, Sichuan, CN |         352.00 GiB |      0.02% |  352.00 GiB |           0.00% |
| [f0836160](https://filfox.info/en/address/f0836160)         |                   Seoul, Seoul, KR |         320.00 GiB |      0.02% |  320.00 GiB |           0.00% |
| [f0520660](https://filfox.info/en/address/f0520660)         |                            Unknown |         288.00 GiB |      0.02% |  288.00 GiB |           0.00% |
| [f02301](https://filfox.info/en/address/f02301)             |           San Jose, California, US |         192.00 GiB |      0.01% |  192.00 GiB |           0.00% |
| [f032824](https://filfox.info/en/address/f032824)           |                  Austin, Texas, US |         160.00 GiB |      0.01% |  160.00 GiB |           0.00% |
| [f01871352](https://filfox.info/en/address/f01871352)       |                   Seoul, Seoul, KR |          96.00 GiB |      0.01% |   96.00 GiB |           0.00% |

![Provider Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/80/1671092379015.png)
### Deal Data Replication
The below table shows how each many unique data are replicated across storage providers.
- No more than 25% of unique data are stored with less than 4 providers.

⚠️ 25.33% of deals are for data replicated across less than 4 storage providers.

| Unique Data Size | Total Deals Made | Number of Providers | Deal Percentage |
| ---------------: | ---------------: | ------------------: | --------------: |
|       177.41 TiB |       246.25 TiB |                   1 |          17.28% |
|        22.75 TiB |        76.97 TiB |                   2 |           5.40% |
|         6.44 TiB |        37.81 TiB |                   3 |           2.65% |
|         7.47 TiB |        64.13 TiB |                   4 |           4.50% |
|        38.41 TiB |       454.06 TiB |                   5 |          31.85% |
|        27.19 TiB |       346.03 TiB |                   6 |          24.28% |
|         7.48 TiB |       105.70 TiB |                   7 |           7.42% |
|       288.00 GiB |         2.75 TiB |                   8 |           0.19% |
|       192.00 GiB |         1.75 TiB |                   9 |           0.12% |
|       384.00 GiB |         4.19 TiB |                  10 |           0.29% |
|       512.00 GiB |         6.84 TiB |                  11 |           0.48% |
|       320.00 GiB |         4.75 TiB |                  12 |           0.33% |
|         1.06 TiB |        17.13 TiB |                  13 |           1.20% |
|       928.00 GiB |        15.59 TiB |                  14 |           1.09% |
|         1.22 TiB |        22.94 TiB |                  15 |           1.61% |
|       384.00 GiB |         7.47 TiB |                  16 |           0.52% |
|       384.00 GiB |         7.75 TiB |                  17 |           0.54% |
|       128.00 GiB |         2.63 TiB |                  18 |           0.18% |
|        32.00 GiB |       736.00 GiB |                  19 |           0.05% |

![Replication Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/80/1671092380107.png)
### Deal Data Shared with other Clients
The below table shows how many unique data are shared with other clients.
Usually different applications owns different data and should not resolve to the same CID.

⚠️ CID sharing has been observed.

| Other Client                                                                                                                                                                                                              | Application                                                                                                                                          | Total Deals Affected | Unique CIDs |        Verifier |
| :------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ | :--------------------------------------------------------------------------------------------------------------------------------------------------- | -------------------: | ----------: | --------------: |
| [f1o54sve7ede7im4caux3ug7lsyjmbue7ss3zzl6y](https://filfox.info/en/address/f1o54sve7ede7im4caux3ug7lsyjmbue7ss3zzl6y)                                                                                                     | [FilSwan](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/278)                                                               |             1.10 PiB |       5,403 | LDN v3 multisig |
| [f1bstbq5bi72kyovhh7zoo2f6l6uivsjz4ey5dnqq](https://filfox.info/en/address/f1bstbq5bi72kyovhh7zoo2f6l6uivsjz4ey5dnqq)                                                                                                     | [FilSwan](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/917)                                                               |           587.44 TiB |       5,647 | LDN v3 multisig |
| [f14r2jybmccwiu6hze4fu55jyhclktvwacec56hea](https://filfox.info/en/address/f14r2jybmccwiu6hze4fu55jyhclktvwacec56hea)                                                                                                     | [ FilSwan](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/15)                                                               |           250.56 TiB |       4,703 | LDN v3 multisig |
| [f3wn64jznjqmr3s3qt4tfwynxo6k73wdxkhd6wo2l<br/>4rwpjdyyddirah2ugfaibvlzz2asaj3ehsp7bwc2z<br/>vnia](https://filfox.info/en/address/f3wn64jznjqmr3s3qt4tfwynxo6k73wdxkhd6wo2l4rwpjdyyddirah2ugfaibvlzz2asaj3ehsp7bwc2zvnia) | [Jiaxing Yangtze Delta Region Blockchain Technology Research Institute](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/523) |           132.22 TiB |         698 | LDN v3 multisig |
| [f13d6zt424jkp55u7kp67azotkzadtlokwnz2ntxa](https://filfox.info/en/address/f13d6zt424jkp55u7kp67azotkzadtlokwnz2ntxa)                                                                                                     | [ FilSwan \- Slingshot Restore](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/157)                                         |           114.30 TiB |       2,000 | LDN v3 multisig |
| [f1fkh47gdwclmovclfz2kvorhhdofvgr5y7fjvkmi](https://filfox.info/en/address/f1fkh47gdwclmovclfz2kvorhhdofvgr5y7fjvkmi)                                                                                                     | [BigData Exchange](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/391)                                                      |            98.81 TiB |         698 | LDN v3 multisig |
| [f1eto4dfafkoeukxenoc7vzexrvf6i4yqvhszrq2y](https://filfox.info/en/address/f1eto4dfafkoeukxenoc7vzexrvf6i4yqvhszrq2y)                                                                                                     | [ Haoqian Mx](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/308)                                                           |            31.06 TiB |         198 | LDN v3 multisig |
| [f1pkrmygbvweykpjcut36lf7ewgqdfhjklbhvepda](https://filfox.info/en/address/f1pkrmygbvweykpjcut36lf7ewgqdfhjklbhvepda)                                                                                                     | [Protocol Labs \( project: Slingshot Evergreen \)](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/293)                      |            17.30 TiB |         189 |       LDN # 293 |
| [f13csteap4jcgl3a65qtsvmblzvelp4sgivddtpqa](https://filfox.info/en/address/f13csteap4jcgl3a65qtsvmblzvelp4sgivddtpqa)                                                                                                     | [ PiKNiK](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/432)                                                               |             4.56 TiB |         146 | LDN v3 multisig |
| [f3v7x4a2aapgx6o2r477tenoin3u5oadaeqyd7kjd<br/>sitykvf4ok7vq2utcyh34lmu5u7oybs25ff6s4dbu<br/>dpma](https://filfox.info/en/address/f3v7x4a2aapgx6o2r477tenoin3u5oadaeqyd7kjdsitykvf4ok7vq2utcyh34lmu5u7oybs25ff6s4dbudpma) | [LeoCheung \- Slingshot Restore](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/151)                                        |             4.38 TiB |          28 | LDN v3 multisig |
| [f3td7znsz2q6laexewfqogczo74xyiwgbysuf6i75<br/>k2wrdqwzyvln7wvzmxaz3jvqzskwxqerdwaetdvue<br/>jama](https://filfox.info/en/address/f3td7znsz2q6laexewfqogczo74xyiwgbysuf6i75k2wrdqwzyvln7wvzmxaz3jvqzskwxqerdwaetdvuejama) | Unknown                                                                                                                                              |             1.84 TiB |          39 |         Unknown |
| [f3rwypb3nhyzkslf6eb2qoiaqdwvaedcawxiav4hm<br/>hi4cp4w7ptjua42knqoddbl5uabcrtzgq7jajvjro<br/>z54a](https://filfox.info/en/address/f3rwypb3nhyzkslf6eb2qoiaqdwvaedcawxiav4hmhi4cp4w7ptjua42knqoddbl5uabcrtzgq7jajvjroz54a) | [dropcool \- Slingshot Restore](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/145)                                         |           992.00 GiB |          29 | LDN v3 multisig |
| [f1toz5izxdse43peqyd7zktmyqilvhf6u72z74gfq](https://filfox.info/en/address/f1toz5izxdse43peqyd7zktmyqilvhf6u72z74gfq)                                                                                                     | [Starboard Networks](https://github.com/filecoin-project/filecoin-plus-client-onboarding/issues/1855)                                                |            96.00 GiB |           3 |       Steven Li |
| [f13zfhkvtf6mewd74jhav6iqcggwsojht73tickga](https://filfox.info/en/address/f13zfhkvtf6mewd74jhav6iqcggwsojht73tickga)                                                                                                     | [X\-Order Lab](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/936)                                                          |            96.00 GiB |           3 | LDN v3 multisig |
| [f3wzua4wihcouehv5datojpgalyapegvdfkhkqamx<br/>dtr4tzcsn7kylkoaapmmxisbp3tzekgijb32lrswf<br/>5t5q](https://filfox.info/en/address/f3wzua4wihcouehv5datojpgalyapegvdfkhkqamxdtr4tzcsn7kylkoaapmmxisbp3tzekgijb32lrswf5t5q) | [Ninth Heaven Guild](https://github.com/filecoin-project/filecoin-plus-client-onboarding/issues/1801)                                                |            32.00 GiB |           1 |          Neo Ge |

[^1]: To manually trigger this report, add a comment with text `checker:manualTrigger`

**Comment by cryptowhizzard** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebl37bma5jh74x2oa5h6rz6kohmsudtah5y2ik7nlyd2hppjwuywm 
#### Address 
> f1r3d25hl2y7rqlsu2mgczdethy4qqjmkfdlmibfq
#### Datacap Allocated
> 498.00TiB
#### Signer Address
> f1krmypm4uoxxf3g7okrwtrahlmpcph3y7rbqqgfa
#### Id
> 7678358a-28e1-4434-8ae4-8a8829f7a33a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebl37bma5jh74x2oa5h6rz6kohmsudtah5y2ik7nlyd2hppjwuywm

**Comment by flyworker** [comment]
closed as reach the total amount requested
