### ISSUE TITLE
[DataCap Application] Little Cherry Animation

### ISSUE THREAD

**Issue by Vincesaq** [filecoin-project/filecoin-plus-large-datasets#800]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Henan Little Cherry Animation Group Co.
- Website / Social Media:www.xiaoyingtao.com.cn
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):3PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):100TiB
- On-chain address for first allocation:f12ylbidoafinx25q6y5n7z74q5qh2xlhssjkgsji

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Founded in October 2000, Henan Little Cherry Animation Group has 6 subsidiaries, including Zhengzhou Mangao Entertainment Co. Ltd. and Zhengzhou Cultural Industry Investment Fund Management Company, etc., and has more than 300 contracted cartoonists, animation artists and contracted writers in China. In 2008, Little Cherry Group was named as the national animation industry development base (Henan base) by the General Administration of Press and Publication. In 2012, Little Cherry was included in the national animation brand construction and protection plan by the Ministry of Culture.

```

What is the primary source of funding for this project?
```
Provided by ourselves and our strategic partners
```

What other projects/ecosystem stakeholders is this project associated with?
```
No connection to other projects
```

## Use-case details

Describe the data being stored onto Filecoin
```
Mainly the cartoons and animations we create and the materials we need
```

Where was the data in this dataset sourced from?
```
Data from ourselves
Since its establishment, Little Cherry Group has provided Chinese animation fans and institutional clients with stable and high-quality cartoons, animations, publications, consumer products and other kinds of services. It has produced 15 titles and more than 500 episodes of TV cartoons, including "Little Cherry", "Wake-up Call", "Pan Gu Kai Tian", "Star of the Central Plains" and "Talking Lian according to the Classics", which have been broadcast on CCTV, the website of the Central Commission for Discipline Inspection and more than 100 TV stations nationwide. We have created 36,000 cartoons of "Little Cherry" and published 335 cartoon books and magazines with 21 million copies, which are sold well in China and 12 countries and regions.

```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://drive.google.com/file/d/1gCT5c9WzO0i7rJmooJWvHa0ymd7eiT66/view?usp=sharing
https://drive.google.com/file/d/1xISCNFg6qwuDm9V7AEf6-5zfu2mA8j0Q/view?usp=sharing
https://drive.google.com/file/d/1GF2mJce4grvfBVWC20iFtlrv3uFzC1Xq/view?usp=sharing
https://v.youku.com/v_show/id_XNDIyMTQwMDQ5Mg==.html?spm=a2h0c.8166622.PhoneSokuProgram_1.dselectbutton_1

```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Please answer here.
```

What is the expected retrieval frequency for this data?
```
Yes, anyone can view
```

For how long do you plan to keep this dataset stored on Filecoin?
```
2-3 years```


## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Asia
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Yes, we transfer via offline
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We will consider the time and stability of the supplier
```

How will you be distributing deals across storage providers?
```
We will distribute them equally to each storage provider.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, we have
```

**Comment by Sunnyiscoming** [comment]
What's the relationship between you and organization? 
How many copies will you store?
Can you provide more detailed information about storage providers participated in this program, such as you can list SPs you have contacted with at present?
Could you send an email to filplus-app-review@fil.org with your official domain in order to confirm your identity? Email name should includes the issue id #800.

**Comment by Sunnyiscoming** [comment]
Any update here?

**Comment by Sunnyiscoming** [comment]
Close for no reply. You can resubmit your application if necessary.
