### ISSUE TITLE
[DataCap Application] Westland Tourism Development Co.

### ISSUE THREAD

**Issue by MalcolnLi** [filecoin-project/filecoin-plus-large-datasets#805]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Westland Tourism Development Co.
- Website / Social Media:http://www.xylygf.com/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):2.3 PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):211 TiB
- On-chain address for first allocation:f13ci6gc2p5j2xznw5ayvl3sx5aqni6gm2km2o57i

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
          Ltd., established on January 18, 2001, is the first tourism development joint-stock enterprise in Xinjiang approved by the People's Government of Xinjiang Uygur Autonomous Region. The company currently has a registered capital of 155 million yuan, and its operation area includes Tianshan Tianchi Scenic Area, a World Natural Heritage Site and a national 5A-class scenic spot; Turpan Flaming Mountain, a national 4A-class scenic spot; Tulufan Flaming Mountain, a national 4A-class scenic spot ---Ili Unwinding Princess Lavender Garden Scenic Area; National 3A Scenic Area ---Wu Caiwan Hot Spring Scenic Area. The main business covers: tourism transportation, lake yacht sightseeing, tourism resources development, ropeways, sightseeing buses, hot spring tourism, international travel agency, food, agricultural and sideline products sales, catering, etc. It has the 30-year concession rights of operating projects such as Tianchi Scenic Area Intercity Bus, Ma Ya Mountain Ropeway, Lake Cruise, and Catering Center. The company was officially listed on August 6, 2020 with stock code 300859, which is the first stock of Xinjiang Tourism.
```

What is the primary source of funding for this project?
```
Scenic area admission revenue, company operating income.
```

What other projects/ecosystem stakeholders is this project associated with?
```
NO
```

## Use-case details

Describe the data being stored onto Filecoin
```
Scenic promotional video, company development video.
```

Where was the data in this dataset sourced from?
```
Produced by the company's business department.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://drive.google.com/drive/folders/1LfXUuogm5I3q1kButv4NzycGM9RyoD9c?usp=sharing
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
YES
```

What is the expected retrieval frequency for this data?
```
4-7 times a year
```

For how long do you plan to keep this dataset stored on Filecoin?
```
Permanent
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
China
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Offline
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
Strong and creditworthy service provider.
```

How will you be distributing deals across storage providers?
```
Average distribution
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, I have enough money.
```

**Comment by raghavrmadya** [comment]
It is unclear to me how you have 2.3 PiBs of data. One video on the website is the same as the data sample. I have very low confidence in this being a legitimate application. Provide as much as evidence as possible to prove that you have real data

**Comment by Sunnyiscoming** [comment]
Any update here?

**Comment by Sunnyiscoming** [comment]
Close for no reply. You can resubmit your application if necessary.
