### ISSUE TITLE
[DataCap Application] CTV Seeking Beauty

### ISSUE THREAD

**Issue by rebyron** [filecoin-project/filecoin-plus-large-datasets#808]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Beijing CTV Seeking Beauty Culture Communication Co.
- Website / Social Media:www.cctvxmw.com
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):4PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):100TiB
- On-chain address for first allocation: f1nqa25zgql7xo3anz6ydi57w2nuqkelmle5t67hi

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Ltd. is mainly engaged in branding service, marketing planning, integrated communication, public relations, film and television production and distribution, with innovation, creativity, strategy and real-world marketing as its core competitiveness.
```

What is the primary source of funding for this project?
```
Company business revenue
```

What other projects/ecosystem stakeholders is this project associated with?
```
Associated with our partners
```

## Use-case details

Describe the data being stored onto Filecoin
```
The data stored on Filecoin is all data generated during the brand's operations, and the main forms of our data are images, text and video
```

Where was the data in this dataset sourced from?
```
Public data generated in the course of brand operations and product sales
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://drive.google.com/file/d/1CndKQ3Ot9r5Nfdjr4uCAcgChBnKbgzey/view?usp=sharing
https://drive.google.com/file/d/1fLoqCkjJ4agLscqpBgIGeiTRh-1CktGd/view?usp=sharing
https://drive.google.com/file/d/10lKDsHS0Nu_d4aNi4ktAUrJ2fyolcFvs/view?usp=sharing
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
yes
```

What is the expected retrieval frequency for this data?
```
Once every six months
```

For how long do you plan to keep this dataset stored on Filecoin?
```
More than one year
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
China
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Yes, we transfer via offline
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We plan to select a number of suppliers who can provide services reliably and consistently.
```

How will you be distributing deals across storage providers?
```
We will distribute them equally to each storage provider.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, we want to close the deal as soon as possible
```

**Comment by Sunnyiscoming** [comment]
It seems that most data are from your customers, have you authorized to store them as public data on Filecoin?
What's the relationship between you and organization? 
Can you provide more detailed information about other storage providers participated in this program, such as you can list SPs you have contacted with at present?
Could you send an email to filplus-app-review@fil.org with your official domain in order to confirm your identity? Email name should includes the issue id #808.

**Comment by Sunnyiscoming** [comment]
Any update here?

**Comment by Sunnyiscoming** [comment]
Close for no reply. You can resubmit your application if necessary.
