### ISSUE TITLE
[DataCap Application] Guangzhou Yuntu Animation Design Co.

### ISSUE THREAD

**Issue by yuntudongman** [filecoin-project/filecoin-plus-large-datasets#814]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Guangzhou Yuntu Animation Design Co.
- Website / Social Media:http://www.4wgame.com
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):2Pib
- Weekly allocation of DataCap requested (usually between 1-100TiB):220TiB
- On-chain address for first allocation: f1yk4wntiw3vyqf5t53pxbv5lxiyv6vp2oe4ybb7q

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Founded in 2013 and located in Guangzhou, Yuntu Animation is committed to becoming a highly professional "pan-entertainment digital art service" company with a content team that creates high-quality "original animation cartoons", and has produced such original animation cartoon IPs as "Reversal of the Next Generation", "The Ballad of Illusionary Dream Mountain and Sea", "Love Cloud Book" and "Tea House Floating Dream". We have produced original animated comic IPs such as "Reversal of Subgenres", "The Dream of the Mountain and the Sea", "The Book of Love" and "The Dream of the Floating Life of the Tea House", and have maintained close business cooperation with Tencent, Netease, Ali, Perfect, ChangYou and other companies in the industry.
```

What is the primary source of funding for this project?
```
These funds come from investments made by shareholders.
```

What other projects/ecosystem stakeholders is this project associated with?
```
This is not related to other projects.
```

## Use-case details

Describe the data being stored onto Filecoin
```
Mainly, the company works to preserve.
```

Where was the data in this dataset sourced from?
```
Public data generated in the course of brand operations.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://drive.google.com/drive/folders/1A-mSpKo3ioGPKsudkMAoZAYLy4S-2uis?usp=sharing
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes.
```

What is the expected retrieval frequency for this data?
```
It depends on the actual need.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
Forever.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
China.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
We primarily transfer online via a designated platform, but we can also provide offline data transfer when necessary.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We will consider the time and stability of the supplier.
```

How will you be distributing deals across storage providers?
```
We will understand whether the storage provider has relevant experience and sustainability and rationalize it to different storage providers based on the analysis.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
We don't need any help for now, because we have some plans.
```

**Comment by raghavrmadya** [comment]
The application is asking for higher weekly allocation without justification. Please open a new application with as much justification as possible including at least 10 data samples.
