### ISSUE TITLE
[DataCap Application] Shanghai Hualu Baina Culture Media Co., Ltd.

### ISSUE THREAD

**Issue by HualuBaina** [filecoin-project/filecoin-plus-large-datasets#818]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Shanghai Hualu Baina Culture Media Co., Ltd.
- Website / Social Media:https://www.hualbn.com/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):2PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):150TiB
- On-chain address for first allocation:f1tyu4sf65g5qolsiwtg5733yvxhlpifzwnmfssvy

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Ltd. was founded in 2002 and officially changed its name to Banner Chicheng in 2022, transforming from a simple film and television company to a two-wheeled IP whole industry chain operation platform dedicated to building "content" and "content+", establishing a content matrix of dramas, movies and animation horizontally, extending the industry chain vertically with quality content as the core, precipitating user emotions with multi-format head content, and empowering marketing, consumption, cultural tourism and other back-end.
```

What is the primary source of funding for this project?
```
From the company's account.
```

What other projects/ecosystem stakeholders is this project associated with?
```
There is no relationship with other projects for the time being.
```

## Use-case details

Describe the data being stored onto Filecoin
```
Mainly, our company invests in the production of TV series, movies, promotional videos and other film and television works.
```

Where was the data in this dataset sourced from?
```
Sourced from our company for filming and production.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://drive.google.com/drive/folders/1pGLO-DZibqEplSXOicIEjPPZ3SH8lLvF?usp=sharing
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes.
```

What is the expected retrieval frequency for this data?
```
There are few opportunities throughout the year.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
Always stored on Filcoin.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
China.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Online.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We will be looking for some large and reputable miners.
```

How will you be distributing deals across storage providers?
```
We will choose the vendor that can do it as soon as possible to distribute first.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
We have enough money and resources.
```

**Comment by raghavrmadya** [comment]
The application is asking for higher weekly allocation without justification. Please open a new application with as much justification as possible including at least 10 data samples of the actual storage. We cannot determine the legitimacy of this client and application.
