### ISSUE TITLE
[DataCap Application]Xiamen Wanyan Information Consulting Co., Ltd.

### ISSUE THREAD

**Issue by wanyanjinfu** [filecoin-project/filecoin-plus-large-datasets#819]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Xiamen Wanyan Information Consulting Co., Ltd.
- Website / Social Media:http://www.wanyanzhidai.com/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):1.5 PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):100TiB
- On-chain address for first allocation:f1ixcfaqlvl2lwuwf6mepkpk4wo42w3ubgdwmccni

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Xiamen Wanyan Information Consulting Co., Ltd. was established in 2017 and is headquartered in Xiamen, a beautiful Lu Island. It is designed to provide financing and loan assistance services for large, small and medium-sized enterprises and individuals, to better solve the problem of enterprise development funds, and to quickly support the development of enterprises.
Areas of focus: unsecured loans, mortgage loans and other business areas of Ping An Bank, Dasu Finance and other banks.
Loan assistance business: real estate loan, social security loan, enterprise loan, policy loan, auto loan, reserve fund, tax loan, provident fund loan, etc.
Service tenet: high quota, low interest rate, fast speed, simple process and high success rate of loan assistance.
```

What is the primary source of funding for this project?
```
Investors and business revenues.
```

What other projects/ecosystem stakeholders is this project associated with?
```
None.
```

## Use-case details

Describe the data being stored onto Filecoin
```
Business data generated during the operation of the company, including but not limited to product introduction, product service and service plan data;  
The data we intend to store will be desensitized. 
```

Where was the data in this dataset sourced from?
```
The data provided by users and the analysis data generated during service processes. 
Company promotional materials, promotional pictures and videos, etc.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://drive.google.com/drive/folders/116SzG6UsUOTgeq-CEw2i4VOSgmdcQxBp?usp=sharing
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
 Yes,This is a public dataset.
```

What is the expected retrieval frequency for this data?
```
Twice a year
```

For how long do you plan to keep this dataset stored on Filecoin?
```
At least 2 years.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Asia, Europe, Africa can be
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Both online and offline.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We will  find SPs on Filecoin slack, BigDexchange, and Filgram, and also accept SP to contact us.
Data will be stored in multiple SPs, ensuring distributed storage and data security.  
We periodically retrieve data to ensure that it is safely stored. 
```

How will you be distributing deals across storage providers?
```
We will choose more stable and secure storage suppliers first, and then allocate according to the allocation rules on this basis.  We hope that more storage providers can contact us and provide us with storage services. 
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes,we have.
```

**Comment by raghavrmadya** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 1.5PiB

**Expected weekly DataCap usage rate**

> 100TiB

**Client address**

>f1ixcfaqlvl2lwuwf6mepkpk4wo42w3ubgdwmccni

**Comment by raghavrmadya** [comment]
Recommendation for notaries: Please assess if the applicant is connected with the organization. Video samples seem legitimate but would like to make sure they are not just taken from online sources. @wanyanjinfu , you are welcome to provide additional evidence. Please note that we are trying to protect the business and their IP here. 

Thanks

**Comment by wanyanjinfu** [comment]
> Recommendation for notaries: Please assess if the applicant is connected with the organization. Video samples seem legitimate but would like to make sure they are not just taken from online sources. @wanyanjinfu , you are welcome to provide additional evidence. Please note that we are trying to protect the business and their IP here.
> 
> Thanks

Hi，@raghavrmadya

I have sent you an email using our company's domain email address. Thank you for agreeing to our application.
![3812c976101ffb879c2287b423fde3b](https://user-images.githubusercontent.com/111372030/189345182-2d43cdd3-3dde-4864-82c5-2d610c2d30a9.png)

Thanks

**Comment by Tom-OriginStorage** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceattly6ycynzq2sxtd7wsisn7gvopddu75u3o3mj45yk76bb2bfak 
#### Address 
> f1ixcfaqlvl2lwuwf6mepkpk4wo42w3ubgdwmccni
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1q6bpjlqia6iemqbrdaxr2uehrhpvoju3qh4lpga
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceattly6ycynzq2sxtd7wsisn7gvopddu75u3o3mj45yk76bb2bfak

**Comment by swatchliu** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebonstneokg4kfh57zh3e56maisat66rxm64ptrohv6xm2bedohge 
#### Address 
> f1ixcfaqlvl2lwuwf6mepkpk4wo42w3ubgdwmccni
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1yh6q3nmsg7i2sys7f7dexcuajgoweudcqj2chfi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebonstneokg4kfh57zh3e56maisat66rxm64ptrohv6xm2bedohge

**Comment by BigD-Exchange** [comment]
@wanyanjinfu Hi! Great to see you have gotten approval for DataCap. If you are looking for more storage providers to store these data or have any questions, please visit #bigdata-exchange on Filecoin Slack or reply here. 

We have strong demand from a diverse group of SPs, who are actively looking to onboard more data.

**Comment by newwebgroup** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebx5djrxikxeipau63i6tbzrwpbne3hkduuxkadodgcdzvsny7uge 
#### Address 
> f1ixcfaqlvl2lwuwf6mepkpk4wo42w3ubgdwmccni
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1e77zuityhvvw6u2t6tb5qlnsegy2s67qs4lbbbq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebx5djrxikxeipau63i6tbzrwpbne3hkduuxkadodgcdzvsny7uge

**Comment by ipfscn** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceatrppal3d5xflzutqcmwufpz7vlpputwjzbct7wrjeladr4aclyq 
#### Address 
> f1ixcfaqlvl2lwuwf6mepkpk4wo42w3ubgdwmccni
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1j4n74chme7whbz3yls4a7ixqewb6dijypqg2a3a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceatrppal3d5xflzutqcmwufpz7vlpputwjzbct7wrjeladr4aclyq

**Comment by 1ane-1** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebuizvw7cscybrb3u4ouqihsz7oslbxp6jtdzrarq4y5bp5hytsme 
#### Address 
> f1ixcfaqlvl2lwuwf6mepkpk4wo42w3ubgdwmccni
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1mdk7s2vntzm6hu35yuo6vjubtrpfnb2awhgvrri
#### Id
> 88f2c7e0-ac7c-4b25-b5d7-7a7010abb6e9
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebuizvw7cscybrb3u4ouqihsz7oslbxp6jtdzrarq4y5bp5hytsme

**Comment by newwebgroup** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecy7l2mnoyil7c56lstoibwirc72bmp7czxt2vpnuflh6kalmex7w 
#### Address 
> f1ixcfaqlvl2lwuwf6mepkpk4wo42w3ubgdwmccni
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1e77zuityhvvw6u2t6tb5qlnsegy2s67qs4lbbbq
#### Id
> 88f2c7e0-ac7c-4b25-b5d7-7a7010abb6e9
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecy7l2mnoyil7c56lstoibwirc72bmp7czxt2vpnuflh6kalmex7w

**Comment by NDLABS-OFFICE** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebpzis53ybv4nfuki5v773tbn34fxzl5voaalyun6h2nfj6gtakzq 
#### Address 
> f1ixcfaqlvl2lwuwf6mepkpk4wo42w3ubgdwmccni
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1yayfsv6whu3rheviucvventj3y6t542xfpb47ei
#### Id
> 2e5bbb64-a9e5-4317-9763-d517be3d96f8
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebpzis53ybv4nfuki5v773tbn34fxzl5voaalyun6h2nfj6gtakzq

**Comment by kernelogic** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaqz2acyoxkaoddoysknpmwwwbjcennhllds4f3ev4mdj3l6dxehq 
#### Address 
> f1ixcfaqlvl2lwuwf6mepkpk4wo42w3ubgdwmccni
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### Id
> 2e5bbb64-a9e5-4317-9763-d517be3d96f8
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaqz2acyoxkaoddoysknpmwwwbjcennhllds4f3ev4mdj3l6dxehq

**Comment by xiaoyuaiheshui** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced2knehbdfegncljnynawyihewrozwi2vifdxtlre3rffokllx3kg 
#### Address 
> f1ixcfaqlvl2lwuwf6mepkpk4wo42w3ubgdwmccni
#### Datacap Allocated
> 786.00TiB
#### Signer Address
> f122qmy25wdtt5mxd77kndiq7z5x2n3iwiuz2wdsa
#### Id
> a4dc9442-8a4d-497d-bbb7-be2a33d2f78c
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced2knehbdfegncljnynawyihewrozwi2vifdxtlre3rffokllx3kg

**Comment by swatchliu** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecn7ifbrqg53zrg4wj5kcghapsrxajiw7hgh5ob6ctrtpfqeufoay 
#### Address 
> f1ixcfaqlvl2lwuwf6mepkpk4wo42w3ubgdwmccni
#### Datacap Allocated
> 786.00TiB
#### Signer Address
> f1yh6q3nmsg7i2sys7f7dexcuajgoweudcqj2chfi
#### Id
> a4dc9442-8a4d-497d-bbb7-be2a33d2f78c
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecn7ifbrqg53zrg4wj5kcghapsrxajiw7hgh5ob6ctrtpfqeufoay

**Comment by filplus-checker** [comment]
## DataCap and CID Checker Report[^1]
 - Organization: `Xiamen Wanyan Information Consulting Co., Ltd.`
 - Client: `f1ixcfaqlvl2lwuwf6mepkpk4wo42w3ubgdwmccni`
### Storage Provider Distribution
The below table shows the distribution of storage providers that have stored data for this client.

If this is the first time a provider takes verified deal, it will be marked as `new`.

For most of the datacap application, below restrictions should apply.
 - Storage provider should not exceed 25% of total datacap.
 - Storage provider should not be storing duplicate data for more than 20%.
 - Storage provider should have published its public IP address.
 - All storage providers should be located in different regions.

⚠️ 35.07% of total deal sealed by [f01935005](https://filfox.info/en/address/f01935005) are duplicate data.

⚠️ 37.34% of total deal sealed by [f01945176](https://filfox.info/en/address/f01945176) are duplicate data.

⚠️ [f01861074](https://filfox.info/en/address/f01861074) has unknown IP location.

⚠️ 75.00% of total deal sealed by [f042391](https://filfox.info/en/address/f042391) are duplicate data.

⚠️ 50.00% of total deal sealed by [f0216849](https://filfox.info/en/address/f0216849) are duplicate data.

| Provider                                                    |                           Location | Total Deals Sealed | Percentage | Unique Data | Duplicate Deals |
| :---------------------------------------------------------- | ---------------------------------: | -----------------: | ---------: | ----------: | --------------: |
| [f01935005](https://filfox.info/en/address/f01935005)       |             Hangzhou, Zhejiang, CN |         310.12 TiB |     23.84% |  201.35 TiB |          35.07% |
| [f01945176](https://filfox.info/en/address/f01945176)       |             Hangzhou, Zhejiang, CN |         295.35 TiB |     22.71% |  185.05 TiB |          37.34% |
| [f01861074](https://filfox.info/en/address/f01861074)       |                            Unknown |         151.11 TiB |     11.62% |  151.11 TiB |           0.00% |
| [f01227883](https://filfox.info/en/address/f01227883)`new`  |          Indianapolis, Indiana, US |          82.25 TiB |      6.32% |   80.34 TiB |           2.32% |
| [f01907578](https://filfox.info/en/address/f01907578)       |                 Fuzhou, Fujian, CN |          77.99 TiB |      6.00% |   77.99 TiB |           0.00% |
| [f01098931](https://filfox.info/en/address/f01098931)       |             Hangzhou, Zhejiang, CN |          77.92 TiB |      5.99% |   67.22 TiB |          13.73% |
| [f01566485](https://filfox.info/en/address/f01566485)`new`  |            Shenzhen, Guangdong, CN |          77.69 TiB |      5.97% |   72.72 TiB |           6.40% |
| [f0417848](https://filfox.info/en/address/f0417848)         | Hong Kong, Central and Western, HK |          77.39 TiB |      5.95% |   77.39 TiB |           0.00% |
| [f0428306](https://filfox.info/en/address/f0428306)         |             Hangzhou, Zhejiang, CN |          58.85 TiB |      4.52% |   58.57 TiB |           0.48% |
| [f01752989](https://filfox.info/en/address/f01752989)       |               Zhengzhou, Henan, CN |          15.97 TiB |      1.23% |   15.72 TiB |           1.57% |
| [f01932183](https://filfox.info/en/address/f01932183)       |                   Luohe, Henan, CN |          15.97 TiB |      1.23% |   15.75 TiB |           1.37% |
| [f01939387](https://filfox.info/en/address/f01939387)       |               Chengdu, Sichuan, CN |          13.50 TiB |      1.04% |   13.50 TiB |           0.00% |
| [f01939377](https://filfox.info/en/address/f01939377)       |               Chengdu, Sichuan, CN |          13.50 TiB |      1.04% |   13.50 TiB |           0.00% |
| [f0426933](https://filfox.info/en/address/f0426933)         |               Zhengzhou, Henan, CN |          12.94 TiB |      0.99% |   12.84 TiB |           0.72% |
| [f024016](https://filfox.info/en/address/f024016)           |               Zhengzhou, Henan, CN |          11.75 TiB |      0.90% |   11.59 TiB |           1.33% |
| [f01941622](https://filfox.info/en/address/f01941622)`new`  |               Chengdu, Sichuan, CN |           8.25 TiB |      0.63% |    8.25 TiB |           0.00% |
| [f042391](https://filfox.info/en/address/f042391)           |             Shanghai, Shanghai, CN |         128.00 GiB |      0.01% |   32.00 GiB |          75.00% |
| [f0216849](https://filfox.info/en/address/f0216849)         |                 Xiamen, Fujian, CN |          64.00 GiB |      0.00% |   32.00 GiB |          50.00% |

![Provider Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/819/1671097741457.png)
### Deal Data Replication
The below table shows how each many unique data are replicated across storage providers.
- No more than 25% of unique data are stored with less than 4 providers.

⚠️ 96.98% of deals are for data replicated across less than 4 storage providers.

| Unique Data Size | Total Deals Made | Number of Providers | Deal Percentage |
| ---------------: | ---------------: | ------------------: | --------------: |
|       422.33 TiB |       429.77 TiB |                   1 |          33.04% |
|       202.29 TiB |       569.29 TiB |                   2 |          43.77% |
|        65.82 TiB |       262.33 TiB |                   3 |          20.17% |
|         9.66 TiB |        39.34 TiB |                   4 |           3.02% |

![Replication Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/819/1671097742207.png)
### Deal Data Shared with other Clients
The below table shows how many unique data are shared with other clients.
Usually different applications owns different data and should not resolve to the same CID.

⚠️ CID sharing has been observed.

| Other Client                                                                                                          | Application | Total Deals Affected | Unique CIDs |                          Verifier |
| :-------------------------------------------------------------------------------------------------------------------- | :---------- | -------------------: | ----------: | --------------------------------: |
| [f155pwwoytusrwhijxtnybex2szracdvl7rfsyd6a](https://filfox.info/en/address/f155pwwoytusrwhijxtnybex2szracdvl7rfsyd6a) | `Filwallet` |             6.16 TiB |         102 |                   LDN v3 multisig |
| [f1qzrv37k4ea2dudbv3tvk7sndw23ykymburjo5xi](https://filfox.info/en/address/f1qzrv37k4ea2dudbv3tvk7sndw23ykymburjo5xi) | ``          |            64.00 GiB |           1 | New Web HK Group Holdings Limited |

[^1]: To manually trigger this report, add a comment with text `checker:manualTrigger`
