### ISSUE TITLE
[DataCap Application] TENET Data Systems

### ISSUE THREAD

**Issue by TENET-Data-Systems** [filecoin-project/filecoin-plus-large-datasets#82]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: TENET Data Systems
- Website / Social Media: https://tenetds.co.kr
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100TiB
- On-chain address for first allocation: f3qf6tdzp274qcxy2r6epuy7ennjzqfpzoz265sx2n4p6url4zsg6ohjy5mwhtkmna3wqufiqxmb3v6sj22xja

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
TENET Data Systems was established in June 2021 with a capital of $1,450,000. It is a technology-driven company leading the Korean distributed storage market by focusing on blockchain and IPFS technology R&D, supercomputing server R&D, distributed storage construction, distributed cloud storage platform development, and supercomputer server import & export. Our node is currently being operated by IDC of KT, a Korean state-owned company. We are establishing IPFS-specialized research institutes with large Korean companies. Also, we actively interact with IPFS-related SMEs as well as provide them a technology support. We are discussing to collaborate with government agencies and service platforms in various industries. The aim of distributed storage service of TENET DS is to provide a safe and affordable storage service that anyone can participate in in various fields in Korea.
```

What is the primary source of funding for this project?
```
It is the shareholder's investment.
```

What other projects/ecosystem stakeholders is this project associated with?
```
There is no other projects/ecosystem stakeholders associated with.
```

## Use-case details

Describe the data being stored onto Filecoin
```
We need to store docs, photos, videos, information data, game data, and product information in our distributed storage.
```

Where was the data in this dataset sourced from?
```
Sources are from the various industry platforms we will cooperate with in the future.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://share.weiyun.com/EH1r8PlF
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes, all data stored in the cloud storage of TENET DS is open to the public. Anyone can access.
```

What is the expected retrieval frequency for this data?
```
At any time according to the user's request.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
permanently.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
In the Republic of Korea.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
We have both online and offline data transfer processes.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We have our own massive storage inside KT IDC in Korea. We will store data from various industry platforms in our distributed cloud storage, and all users using the platform will be able to freely store and retrieve their data.
```

How will you be distributing deals across storage providers?
```
Since our IDC cannot store all data from all platforms, we will distribute the deal to trusted storage providers that run nodes stably.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes we have enough resources and funds to start trading as soon as we receive DataCap. Now, We are discussing collaboration with many companies in Korea, and as soon as DataCap is secured, collaboration can proceed quickly. There is nothing the community can do to help our business in Korea right now. But as the size of the Korean market grows, we will need support, and then we will ask for it.
```

**Comment by galen-mcandrew** [comment]
## Multisig Notary requested
#### Total DataCap requested 
> 5PiB
#### Expected weekly DataCap usage rate 
> 100TiB

**Comment by galen-mcandrew** [comment]
@TENET-Data-Systems wanted to flag an issue here: 

> We have our own massive storage inside KT IDC in Korea. We will store data from various industry platforms in our distributed cloud storage, and all users using the platform will be able to freely store and retrieve their data.

The large dataset process is **not designed for storage providers to act as clients and exclusively self-deal.** This process is for clients with large, public, valid data to get approval from a pool of notaries for DataCap, and then to make distributed and decentralized deals across the network.
