### ISSUE TITLE
[DataCap Application] <Guangzhou Yispeed Cloud Computing Co.> - <Eastspeed Cloud>

### ISSUE THREAD

**Issue by sahdqh2763** [filecoin-project/filecoin-plus-large-datasets#820]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Eastspeed Cloud
- Website / Social Media:https://www.yisu.com/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):5 PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):178TiB
- On-chain address for first allocation: f1cwsjy3tlulgmbqufuswarn3opbuvrfu2oay2efi

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Yishu Cloud, full name Guangzhou Yishu Cloud Computing Co. Founded in 2017, is an innovative enterprise dedicated to cloud computing, cloud security technology development, product operation and service security. The core team of Yispeed Cloud has more than sixteen years of experience in the Internet field, and the company currently employs more than one hundred people, mainly for technical research and service security.
As an independent and neutral cloud computing enterprise, its self-developed cloud computing, cloud security, cloud storage, SDN customizable network platform, with outstanding cloud computing technology, solutions more in line with the actual needs of customers and perfect after-sales service guarantee, has been won including greedy game, 4399 games, Seventh Avenue, cloud tour holding group, 9377 games, to play entertainment, tiger live At present, the total number of running cloud servers is more than 50,000, and the monthly growth rate is more than 10%.
```

What is the primary source of funding for this project?
```
The main source of funding for this project is provided by the company's operating income.
```

What other projects/ecosystem stakeholders is this project associated with?
```
NO
```

## Use-case details

Describe the data being stored onto Filecoin
```
Company video data, document data, data generated by the operation process of Yishu cloud platform.
```

Where was the data in this dataset sourced from?
```
The data in this dataset comes from, Yishu Cloud, a cloud computing product that currently acquires data from games, finance, live streaming, video, portals, downloads, webmaster platforms, etc.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://www.yisu.com/produce/
https://www.yisu.com/appmarket/
https://www.yisu.com/zixun/725212.html
https://www.yisu.com/zixun/727399.html
https://www.yisu.com/zixun/728481.html
https://www.yisu.com/zixun/
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes
```

What is the expected retrieval frequency for this data?
```
2-3 times a year
```

For how long do you plan to keep this dataset stored on Filecoin?
```
We plan to store this dataset on Filecoin for 3 years.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Hong Kong, China, United States.Europe, Japan, Korea，Singapore and other regions.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Off-line transmission
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We intend to plan to choose a strong, stable service provider.
```

How will you be distributing deals across storage providers?
```
Average distribution
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, we have enough resources/money to start trading.
```

**Comment by raghavrmadya** [comment]
The application is asking for higher weekly allocation without justification. Please open a new application with as much justification as possible including at least 10 data samples.
