### ISSUE TITLE
[DataCap Application] Aipai Network Storage Plan

### ISSUE THREAD

**Issue by MarcosAncru** [filecoin-project/filecoin-plus-large-datasets#822]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Guangzhou Aipai Network Technology Co., Ltd.
- Website / Social Media:http://www.aipai.com/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):3PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):300TiB
- On-chain address for first allocation:f1s5cz4lt5mrv4uycgsecwekzgfvgs4mjttu72ghi

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Aipai.com is an original video community, with video creation software "master" and so on. It is a product of Guangzhou Aipai Network Technology Co.
```

What is the primary source of funding for this project?
```
The main funding for the project comes from shareholder investment and funding from strategic partners with sufficient reserves.
```

What other projects/ecosystem stakeholders is this project associated with?
```
There are no other project stakeholders.
```

## Use-case details

Describe the data being stored onto Filecoin
```
It is mainly videos of teaching courses and introduction videos for students.
```

Where was the data in this dataset sourced from?
```
The data comes from tutorial videos recorded by the company and material uploaded by users themselves.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://drive.google.com/drive/folders/1S-54cXHKzfo0rmX9Gnap5fSjSPd0AoZz?usp=sharing
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes
```

What is the expected retrieval frequency for this data?
```
Expect 2 search opportunities a year.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
Permanent
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
China
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
We will use a variety of data transfer methods, including online and offline transfers
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We give preference to suppliers with strong capital and knowledge of project data, and also consider the timeliness and stability of the supplier
```

How will you be distributing deals across storage providers?
```
We will use IPFS distributed storage for fair distribution to miners.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, we have enough money and resources. Don't need any help for now.
```

**Comment by raghavrmadya** [comment]
The application is asking for higher weekly allocation without justification. Please open a new application with as much justification as possible including at least 10 data samples.
