### ISSUE TITLE
[DataCap Application] Beijing xingtiantong Telecommunication Technology Co., Ltd

### ISSUE THREAD

**Issue by JarvisTiana** [filecoin-project/filecoin-plus-large-datasets#823]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Beijing Xingtiantong Telecom Technology Co., Ltd.
- Website / Social Media: www.xttkj.com.cn
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):2 PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):200TiB
- On-chain address for first allocation: f1edl3wgh2wq6mdh7ingkojz5co4qm4544byrprjy

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Beijing xingtiantong Telecommunication Technology Co., Ltd. is an enterprise integrating lightning protection engineering design and construction, lightning protection product production and service. The company was founded on February 27, 2003, and its business covers communications, satellite, radar, power, aviation, aerospace, port and other fields. On February 5, 2005, the company obtained the grade B qualification of lightning protection engineering professional design and professional construction issued by Beijing Meteorological Bureau. In 2006, it obtained the network access license for national defense communication network equipment and materials issued by the General Staff Department; In 2007, it obtained the certificate of safety equipment certification of ordnance warehouse issued by the headquarters of the General Logistics Department; In 2010, it obtained GB / T19001-2008 / ISO9001:2008 quality management system certification. The registered capital of the company is 10 million yuan, and the existing workplace is 500 square meters. Currently, there are 60 employees, including 23 professional and technical personnel. It is a high-quality professional team composed of senior engineers, engineers and assistant engineers of lightning protection. The overall goal of the company is to become stronger, better, lead the industry and give better play to the brand advantages. The company will maintain the characteristics of rapid, flexible and efficient decision-making, and make greater contributions to the lightning protection cause in a down-to-earth, honest and reliable manner. The company's existing products are divided into three categories: ttz lightning arrester, TTB surge protector and TTR grounding device. The surge protector ttb-bcd, TTB ant WB, ttb-data-bd110, ttb-data-485, ttz-sj / 8 lightning arrester and ttr-yk / I, ttr-yk / II grounding device lightning protection products developed and produced by the company have been widely used in the army. The surge protective devices developed and produced by the company have passed the test of Beijing lightning protection device test center. The powdered resistance reducing agent ttr-nj developed and produced is a high-efficiency environmental protection product. It can greatly reduce the grounding resistance value of the grounding grid when used in the harsh environment of mountains, sand and gravel, and its reliability has been verified by engineering construction for 10 years.
```

What is the primary source of funding for this project?
```
Company income
```

What other projects/ecosystem stakeholders is this project associated with?
```
No connection with other companies
```

## Use-case details

Describe the data being stored onto Filecoin
```
Technical video
```

Where was the data in this dataset sourced from?
```
Provided by one of the shareholders of the company
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
[Please answer here.](https://drive.google.com/drive/folders/1eZ0xPsNJO3-YXXcMwjCSSN9Nses4EP3F?usp=sharing)
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
This is a public dataset.
```

What is the expected retrieval frequency for this data?
```
Once a year.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
At least five years
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Asia, preferably China
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Both online and offline.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We have employees who regularly retrieve data to ensure its safe storage.
```

How will you be distributing deals across storage providers?
```
We will choose more stable and secure storage suppliers first, and then allocate according to the allocation rules on this basis.  We hope that more storage providers can contact us and provide us with storage services. 
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, we don't need any help for the time being. We have made adequate preparations
```

**Comment by raghavrmadya** [comment]
What do you mean by Technical video? Please elaborate.

**Comment by Sunnyiscoming** [comment]
Any update here?
