### ISSUE TITLE
[DataCap Application] Jiangxi Dajue Mountain Tourism Development Co.

### ISSUE THREAD

**Issue by joycemaome** [filecoin-project/filecoin-plus-large-datasets#825]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Jiangxi Dajue Mountain Tourism Development Co.
- Website / Social Media:http://www.jxdjs.com/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):2.3 PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):205 TiB
- On-chain address for first allocation:f1gb25a4uj3hp5nvljpqrfyolt4r3p7vlp26z55vq

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Dajue Mountain, the domestic scenic spot with the theme of Dajue culture, is located in the eastern part of Jiangxi Province, Zixi County, Fuzhou City, the western foot of the Wuyi Mountain Range, the main peak is 1,647 meters above sea level, the total planning area of the scenic spot is 204 square kilometers, respectively, the East Zone and the West Zone, the East Zone with 300,000 acres of primeval forest as the core of the original forest tourism area; the West Zone with religious culture, canyon rafting as the main comprehensive tourism scenic spot. The forest coverage rate is as high as 97.43%, with an average of 30,000 negative oxygen ions per cubic centimeter in the air, a natural oxygen bar, a gene pool of species and plants, and has been designated by the State Forestry Administration as a base for the reintroduction of wild South China tigers.

```

What is the primary source of funding for this project?
```
Scenic Area Ticket Revenue
```

What other projects/ecosystem stakeholders is this project associated with?
```
NO
```

## Use-case details

Describe the data being stored onto Filecoin
```
Scenic promotion video, attraction promotion poster, company development video.
```

Where was the data in this dataset sourced from?
```
Publicity Department Production
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://drive.google.com/drive/folders/1CWuUUn836fnNxqhNv1iJ2Yc4ATAg8Kqz?usp=sharing
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
YES
```

What is the expected retrieval frequency for this data?
```
2-3 times a year
```

For how long do you plan to keep this dataset stored on Filecoin?
```
Permanent
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
China
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
offline
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
Strong service providers
```

How will you be distributing deals across storage providers?
```
Average distribution
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, I have enough money.
```

**Comment by joycemaome** [comment]
OK if you carefully check our official website, you will find that the content is very rich, including scenery, hotels, food, history, business and other aspects. More importantly, we launched the virtual tourism section. Every visitor will see different landscapes and generate different archives, so a large amount of data is generated.
2.3pib is only the amount of applications at this stage, and more will be applied in the future.

**Comment by Sunnyiscoming** [comment]
What's the relationship between you and organization? 
Can you provide more detailed information about other storage providers participated in this program, such as you can list SPs you have contacted with at present?
Could you send an email to filplus-app-review@fil.org with your official domain in order to confirm your identity? Email name should includes the issue id #825.

**Comment by Sunnyiscoming** [comment]
Any update here?

**Comment by Sunnyiscoming** [comment]
Close for no reply. You can resubmit your application if necessary.
