### ISSUE TITLE
[DataCap Application] Hunan Yingkai Mutual Entertainment Network Information Co.

### ISSUE THREAD

**Issue by lydiaerjiang** [filecoin-project/filecoin-plus-large-datasets#827]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Hunan Yingkai Mutual Entertainment Network Information Co.
- Website / Social Media:https://www.inke.cn/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):2.1 PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):203 TiB
- On-chain address for first allocation:f1l3mtpwh3lejafkaqbeuh4cazitq4fza4o2kbsqq

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
The platform allows users to watch their favorite hosts' live shows and give virtual gifts to their favorite hosts to increase their popularity. For those who like live streaming, they can also apply for an account on the platform and live stream their own shows for others to watch.
```

What is the primary source of funding for this project?
```
Open membership income, live gift income, web3 project income.
```

What other projects/ecosystem stakeholders is this project associated with?
```
NO
```

## Use-case details

Describe the data being stored onto Filecoin
```
Recommend anchor video, company development information, company development video source file.
```

Where was the data in this dataset sourced from?
```
Produced by the Corporate Communications Department
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://drive.google.com/drive/folders/1Pvl0OgYSPzg9Q5byg4yxqRDU8Yt4bhLc?usp=sharing
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
YES
```

What is the expected retrieval frequency for this data?
```
3-5 times a year
```

For how long do you plan to keep this dataset stored on Filecoin?
```
Permanent
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
China
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
offline
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
Stable service provider.
```

How will you be distributing deals across storage providers?
```
Average distribution
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, I have enough money.
```

**Comment by lydiaerjiang** [comment]
Yes, our samples are two videos. If you need us to provide more samples, please give me a clear request.

@tobbytheelephant 
Inke live was listed on the Hong Kong Stock Exchange on July 12, 2018, Although it is not what it used to be, it still has a certain size. We do not understand filcoin's rules, which leads to the current situation. However, I believe that this is not your business level. I hope you can give users respect and thanks.

@galen-mcandrew 
Community management should have high quality and professional ability. I believe this situation is just an example, but I still hope you can supervise. Let filcoin have better consensus and more users.

**Comment by Sunnyiscoming** [comment]
Most of the data you store should be the recommend anchor video. Would the anchor or the anchor's company agree to store it on Filecoin as public data?
In response to the above community member questions. I advice you to provide more than ten data samples of different types you will store, such as recommend anchor video, company development information, company development video source file.
What's the relationship between you and organization? 
Can you provide more detailed information about other storage providers participated in this program, such as you can list SPs you have contacted with at present?
Could you send an email to filplus-app-review@fil.org with your official domain in order to confirm your identity? Email name should includes the issue id #827.

**Comment by Sunnyiscoming** [comment]
Any update here?

**Comment by Sunnyiscoming** [comment]
Close for no reply. You can resubmit your application if necessary.
