### ISSUE TITLE
[DataCap Application] Xiamen Jizhi Interactive Network Technology Co.

### ISSUE THREAD

**Issue by jizhiyouxi** [filecoin-project/filecoin-plus-large-datasets#828]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Xiamen Jizhi Interactive Network Technology Co.
- Website / Social Media:https://www.jzyx.com
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):3PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):230TiB
- On-chain address for first allocation: f16iu4tfuorwxmjx3fcm43nw45nmwot474vda2bpy

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
(hereinafter referred to as "the Company" or "Jizhi Game") was established in August 2010, is a key software enterprise integrating the development and operation of online games, focusing on the development and operation of online games for global users. In July 2014, we set up a R&D branch in Chengdu.Since its establishment, the company has successfully developed many original online games such as "Ancient Crown", "Legend of Magician", "Daoist Please Stay", "Civilization Explosion" and "Oriental Story".
```

What is the primary source of funding for this project?
```
These funds come from investments made by shareholders.
```

What other projects/ecosystem stakeholders is this project associated with?
```
This is not related to other projects.
```

## Use-case details

Describe the data being stored onto Filecoin
```
We have a lot of games, so we need to prepare a lot of pictures, videos, to promote these games.
```

Where was the data in this dataset sourced from?
```
Public data generated in the course of brand operations and merchandising.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://drive.google.com/drive/folders/1QxqjMrNAD1hiRJ6O8D5cwZvfxL_l2H8a?usp=sharing
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes.
```

What is the expected retrieval frequency for this data?
```
There are few opportunities throughout the year.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
More than 1 year.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
China.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Online.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We plan to select a number of miners who can provide services reliably and consistently.
```

How will you be distributing deals across storage providers?
```
We will distribute them equally to each storage provider.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
 We have prepared sufficient funds and resources.
```

**Comment by Sunnyiscoming** [comment]
Can you explain your data composition and provide sufficient data samples separately? How many copies will you store?
What's the relationship between you and organization? 
Can you provide more detailed information about other storage providers participated in this program, such as you can list SPs you have contacted with at present?

**Comment by Sunnyiscoming** [comment]
Any update here?

**Comment by Sunnyiscoming** [comment]
Close for no reply. You can resubmit your application if necessary.
