### ISSUE TITLE
[DataCap Application] Shaanxi Culture Industry Investment Holding Group Co.

### ISSUE THREAD

**Issue by supermanlcb** [filecoin-project/filecoin-plus-large-datasets#829]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Shaanxi Culture Industry Investment Holding Group Co.
- Website / Social Media:http://www.shanwentou.com.cn/mobile/index.aspx
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):2.75 PIB
- Weekly allocation of DataCap requested (usually between 1-100TiB):223 TiB
- On-chain address for first allocation:f143aaxcelnmt4zsmqmenacjby6pltvxg5pzgwahq

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
(Shaanxi Culture Industry Investment Holding (Group) Co., Ltd (Shaanxi Culture Investment Group), established in June 2009, is a large state-owned cultural enterprise in Shaanxi Province and an important market platform for implementing the strategy of "cultural strengthening" in Shaanxi. After thirteen years of development, Shaanxi Wentou Group has total assets of nearly 26 billion yuan, and has built up an industrial layout with film and television production, cultural tourism and cultural finance as its core businesses, supported by art and culture, cultural media and cultural business, etc., becoming one of the state-owned cultural enterprises with the most clustering advantages and development vitality in China.
```

What is the primary source of funding for this project?
```
Company operating income
```

What other projects/ecosystem stakeholders is this project associated with?
```
no
```

## Use-case details

Describe the data being stored onto Filecoin
```
Scenic promotional video, company development video, live video source file

```

Where was the data in this dataset sourced from?
```
Company video material Customer interactive video
```

Can you share a sCorporate Communications and Operations Departmentsample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://drive.google.com/drive/folders/1desm89_Wgob_NODMPO4uVUzMx7oGXfIL?usp=sharing
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes
```

What is the expected retrieval frequency for this data?
```
2-3 times per year
```

For how long do you plan to keep this dataset stored on Filecoin?
```
Permanent
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
China
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
offline
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
Stable and long-established service providers
```

How will you be distributing deals across storage providers?
```
Average distribution
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
yes，I have enough money
```

**Comment by raghavrmadya** [comment]
The application is asking for higher weekly allocation without justification. Please open a new application with as much justification as possible including at least 10 data samples.
