### ISSUE TITLE
[DataCap Application] NCEI

### ISSUE THREAD

**Issue by coveyfassam** [filecoin-project/filecoin-plus-large-datasets#83]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: National Centers for Environmental Information
- Website / Social Media: https://www.ncei.noaa.gov/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100TiB
- On-chain address for first allocation: f16fibkxu77c4ymtzzsws3kwdcj7ztd7qdn5szpoy

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
NOAA's National Centers for Environmental Information (NCEI) hosts and provides public access to one of the most significant archives for environmental data on Earth. We provide over 37 petabytes of comprehensive atmospheric, coastal, oceanic, and geophysical data.
```

What is the primary source of funding for this project?
```
Shareholder Investment.
```

What other projects/ecosystem stakeholders is this project associated with?
```
None.
```

## Use-case details

Describe the data being stored onto Filecoin
```
Earth's open environmental information includes weather, ocean, geography.
```

Where was the data in this dataset sourced from?
```
From National Centers for Environmental Information.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
Of course. 
```
[LCD_sample_pdf.zip](https://github.com/filecoin-project/filecoin-plus-large-datasets/files/7448796/LCD_sample_pdf.zip)
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes, this is the publicly accessible dataset.
```

What is the expected retrieval frequency for this data?
```
Several times a year.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
Permanent storage..
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
At the moment it is mainly Chinese storage providers, and in the future some Asian regions may be added.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
We will do this online,Of course, if we encounter network transmission problems, we will take offline transmission
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
Storage providers need to have some technical strength to support data retrieval.
```

How will you be distributing deals across storage providers?
```
We will send to as many storage providers as possible.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Not currently.
```

**Comment by galen-mcandrew** [comment]
## Multisig Notary requested
#### Total DataCap requested 
> 5PiB
#### Expected weekly DataCap usage rate 
> 100TiB

**Comment by Reiers** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb2f4iws37dtedlhziykhyltntotx5vpojmfoo4bhfrq5bwkgetcy 
#### Address 
> f16fibkxu77c4ymtzzsws3kwdcj7ztd7qdn5szpoy
#### Datacap Allocated
> 50TiB
#### Signer Address
> f1oz43ckvmtxmmsfzqm6bpnemqlavz4ifyl524chq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb2f4iws37dtedlhziykhyltntotx5vpojmfoo4bhfrq5bwkgetcy

**Comment by MegTei** [comment]
HI @galen-mcandrew getting varied error msgs attempting to approve this

**Comment by galen-mcandrew** [comment]
@coveyfassam I am having an issue downloading the sample data that you provided. Are you a representative of NOAA? Can you please provide some more sample data and a contact email from the official NOAA.gov domain?

**Comment by galen-mcandrew** [comment]
@MegTei it appears this message went through: https://filfox.info/en/message/bafy2bzaceb2xryy2krnmuaski7nqr5kvosxy26xcgcuflt42ivepocdjgqnzy

Based on verify.glif, this client has 50 TiB of DataCap, with your approval on 11-23. 

That said, I have some follow-up questions for this client based on the US government agency they are claiming to represent.

**Comment by fabriziogianni7** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb2xryy2krnmuaski7nqr5kvosxy26xcgcuflt42ivepocdjgqnzy
#### Address 
> f16fibkxu77c4ymtzzsws3kwdcj7ztd7qdn5szpoy
#### Datacap Allocated
> 50TiB
#### Signer Address
> f1ystxl2ootvpirpa7ebgwl7vlhwkbx2r4zjxwe5i
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb2xryy2krnmuaski7nqr5kvosxy26xcgcuflt42ivepocdjgqnzy

**Comment by mr-spaghetti-code** [comment]
Hi,

It looks like you received 50TiBs of DataCap to date but have spent less than 20% of it so far.

We would love to understand if there's anything holding you back. We are working hard to make the data onboarding process easier for clients like you and your feedback is very valuable. If you have a moment, please fill in this survey: https://forms.gle/s6AuTXZPZSMokscLA

If you have any feedback or would like to consult with an expert, please let me know. 

Thanks,

João Fiadeiro
Product Manager, Large Data Client Onboarding
Protocol Labs

**Comment by ClarkYin5566** [comment]
Hi @coveyfassam , I am also applying for datacap but still waiting for review. I would like to discuss with you how to proceed and how to promote the development of real data. If possible, please leave your email or contact me: mr.clark.yin@gmail.com

**Comment by dkkapur** [comment]
@coveyfassam - are you storing this dataset as part of Slingshot or just on your own? How will you ensure that it stays retrievable for others in the future?

**Comment by dkkapur** [comment]
Closing this one out for now for lack of response. @coveyfassam please feel free to re-open if still relevant.

**Comment by filplus-checker** [comment]
## DataCap and CID Checker Report[^1]
 - Organization: ``
 - Client: `f16fibkxu77c4ymtzzsws3kwdcj7ztd7qdn5szpoy`
### Storage Provider Distribution
The below table shows the distribution of storage providers that have stored data for this client.

If this is the first time a provider takes verified deal, it will be marked as `new`.

For most of the datacap application, below restrictions should apply.
 - Storage provider should not exceed 25% of total datacap.
 - Storage provider should not be storing duplicate data for more than 20%.
 - Storage provider should have published its public IP address.
 - All storage providers should be located in different regions.

⚠️ [f01823264](https://filfox.info/en/address/f01823264) has sealed 100.00% of total datacap.

⚠️ All storage providers are located in the same region.

| Provider                                              |             Location | Total Deals Sealed | Percentage | Unique Data | Duplicate Deals |
| :---------------------------------------------------- | -------------------: | -----------------: | ---------: | ----------: | --------------: |
| [f01823264](https://filfox.info/en/address/f01823264) | Chengdu, Sichuan, CN |          22.47 TiB |    100.00% |   22.47 TiB |           0.00% |

![Provider Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/83/1671092392048.png)
### Deal Data Replication
The below table shows how each many unique data are replicated across storage providers.
- No more than 25% of unique data are stored with less than 4 providers.

⚠️ 100.00% of deals are for data replicated across less than 4 storage providers.

| Unique Data Size | Total Deals Made | Number of Providers | Deal Percentage |
| ---------------: | ---------------: | ------------------: | --------------: |
|        22.47 TiB |        22.47 TiB |                   1 |         100.00% |

![Replication Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/83/1671092393095.png)
### Deal Data Shared with other Clients
The below table shows how many unique data are shared with other clients.
Usually different applications owns different data and should not resolve to the same CID.

⚠️ CID sharing has been observed.

| Other Client                                                                                                          | Application                                                                                           | Total Deals Affected | Unique CIDs |   Verifier |
| :-------------------------------------------------------------------------------------------------------------------- | :---------------------------------------------------------------------------------------------------- | -------------------: | ----------: | ---------: |
| [f17nj6x2rt7yuk4wyw33gc2jxjjxqibvpve22inna](https://filfox.info/en/address/f17nj6x2rt7yuk4wyw33gc2jxjjxqibvpve22inna) | [charternorth](https://github.com/filecoin-project/filecoin-plus-client-onboarding/issues/1699)       |            10.00 TiB |         320 | Meg Dennis |
| [f1bmkq2l6zhjk6l236m2qoscoucitzfqlimnboixi](https://filfox.info/en/address/f1bmkq2l6zhjk6l236m2qoscoucitzfqlimnboixi) | [hoangkimvietpacific](https://github.com/filecoin-project/filecoin-plus-client-onboarding/issues/847) |             1.47 TiB |          47 | Meg Dennis |

[^1]: To manually trigger this report, add a comment with text `checker:manualTrigger`
