### ISSUE TITLE
[DataCap Application] Henan Jinxiang Culture Development Co.

### ISSUE THREAD

**Issue by meraiot** [filecoin-project/filecoin-plus-large-datasets#830]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Henan Jinxiang Culture Development Co.
- Website / Social Media:http://www.jxdmt.com/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):2.3 PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):201 TiB
- On-chain address for first allocation:f1micntzm23q4q44y2pd37plvn72ikk55wzai73iq

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Founded in 2002, Golden Elephant Culture Development Co., Ltd. has been forging ahead as a cultural technology and creative integration service organization for twenty years, serving more than 1000 local Chinese enterprises. At present, Golden Elephant Culture integrates the resource advantages of Beijing, Henan and Gansu companies to serve the national market.
```

What is the primary source of funding for this project?
```
Cultural and creative income, construction and decoration project income.
```

What other projects/ecosystem stakeholders is this project associated with?
```
NO
```

## Use-case details

Describe the data being stored onto Filecoin
```
Works exhibition hall video, decoration project video, cultural digital technology video.
```

Where was the data in this dataset sourced from?
```
Business Unit Production
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://drive.google.com/drive/folders/1WZSNgqJqXJtIYIasnRxjF5qKpYIiI-DG?usp=sharing
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
YES
```

What is the expected retrieval frequency for this data?
```
2-3 times a year
```

For how long do you plan to keep this dataset stored on Filecoin?
```
Permanent
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
China
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
offline
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
Strong service providers
```

How will you be distributing deals across storage providers?
```
Average distribution
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, I have enough money.
```

**Comment by raghavrmadya** [comment]
The application is asking for higher weekly allocation without justification. Please open a new application with as much justification as possible including at least 10 data samples.
