### ISSUE TITLE
[DataCap Application] Shanghai Senyu Culture Media Co.

### ISSUE THREAD

**Issue by dysking** [filecoin-project/filecoin-plus-large-datasets#831]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Shanghai Senyu Culture Media Co.
- Website / Social Media:http://www.sh-senyu.com/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):2.2PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):208 TiB
- On-chain address for first allocation:f1djsu7qmgtkiryjsw3bmbx65sgbdp6ioposdag2y

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Shanghai Senyu Culture Media Co., Ltd. was established in 2010, adhering to the concept of "spreading positive energy and creating new value", engaging in new media distribution of video programs and new media content provision business. The company has accumulated multi-dimensional audiovisual resources covering animation, TV series, movies, variety shows, documentaries, etc., and comprehensively covers all channels of downstream new media terminals such as Internet video platforms, IPTV operators, OTT TV operators, digital TV operators and video platforms of three major mobile operators.
```

What is the primary source of funding for this project?
```
Film and television drama licensing revenue, animation licensing revenue.
```

What other projects/ecosystem stakeholders is this project associated with?
```
NO
```

## Use-case details

Describe the data being stored onto Filecoin
```
Film and TV showcase video, animation showcase video, company development video.
```

Where was the data in this dataset sourced from?
```
Publicity Department Production
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://drive.google.com/drive/folders/1VPu3P5kpuj3YY9RHmg43FTVM459-MVtK?usp=sharing
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
YES
```

What is the expected retrieval frequency for this data?
```
2-3 times a year
```

For how long do you plan to keep this dataset stored on Filecoin?
```
Permanent
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
China
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
offline
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
Stable service providers
```

How will you be distributing deals across storage providers?
```
Average distribution
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, I have sufficient funds.
```

**Comment by raghavrmadya** [comment]
The application is asking for higher weekly allocation without justification. Please open a new application with as much justification as possible including at least 10 data samples of the actual storage. We cannot determine the legitimacy of this client and application.
