### ISSUE TITLE
[DataCap Application] Gangzhonglv (Xiamen) International Trade Travel Agency Co., Ltd.

### ISSUE THREAD

**Issue by gangzhonglv** [filecoin-project/filecoin-plus-large-datasets#832]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Gangzhonglv (Xiamen) International Trade Travel Agency Co., Ltd.
- Website / Social Media:http://www.ctixm.com/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):5 PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):100TiB
- On-chain address for first allocation:f16zw6z77s3i6txlkmw262uyd6qi6wbqyedjvd3gi

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Gangzhonglv (Xiamen) International Trade Travel Agency Co., Ltd. was established on March 19, 2004. Relying on the trinity global marketing network of Hong Kong China Travel Service Group, the company is down-to-earth, forge ahead and actively innovate. With professionalism, efficiency, high quality and personalization as the service tenet, with group, network and international construction as the development goal, combined with the comprehensive advantages of the local shareholder - International Trade Holdings Co., Ltd., one of the top ten state-owned enterprises directly under Xiamen City , In line with the purpose of "serving the public and creating happiness", we wholeheartedly provide the majority of tourists with more personalized products such as inbound tourism, outbound tourism, domestic tourism, business tourism, exhibition tourism, leisure and vacation tourism, etc., and strive to serve Chinese and global tourists. Provide professional and dedicated travel services.
Sincerely hope to get the support and love of old and new friends, and eagerly look forward to the cooperation of the same industry at home and abroad. Based on the tenet of innovation, quality and service, we will wholeheartedly provide customers with more personalized service products such as inbound tourism, domestic tourism, outbound tourism, business tourism, exhibition tourism, leisure and vacation tourism, etc. We sincerely look forward to your visit and cooperation. .
```

What is the primary source of funding for this project?
```
From the company's own funds
```

What other projects/ecosystem stakeholders is this project associated with?
```
No.
```

## Use-case details

Describe the data being stored onto Filecoin
```
Scenic promotional video, company development video, live video source file.
```

Where was the data in this dataset sourced from?
```
Publicity Department Production.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://drive.google.com/drive/folders/1-V1EzFrZ3-HZ-UFs8a2zbCA0cmRdnd7N?usp=sharing
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes,we confirm.
```

What is the expected retrieval frequency for this data?
```
1-2 times a year.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
Permanent.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Asia, Europe, Africa can be.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
offline
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
I will  find SPs on Filecoin slack, BigDexchange, and Filgram.
Welcome strong service providers to contact us
```

How will you be distributing deals across storage providers?
```
We hope that more storage service providers will cooperate, and each service provider will store no more than 20% of the data.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes,we have.
No help needed,thanks.
```

**Comment by jessie8o8** [comment]
Hello! From a brief browse of your site from the perspective of a customer, there are a number of problems with that site that would not allow me to really do anything on your site

First off, the link to the sample is restricted
![image](https://user-images.githubusercontent.com/90115194/186541481-34a5f194-5de6-40dd-b0d0-c3f5fd110b61.png)

When I tried joining a tour, the tours listed dated back to 2010 with no recent tours available for me to view
![image](https://user-images.githubusercontent.com/90115194/186540600-bcc90bb4-720c-4f21-b574-add7493c765d.png)

The search button does not work. When I hover over it, there is no hand icon, denoting that it is not clickable, thus the options above are not searchable
![image](https://user-images.githubusercontent.com/90115194/186540701-4458a804-8ce0-45ff-8783-281590699ed2.png)

Your site traffic of all time does not surpass 10 ever
![image](https://user-images.githubusercontent.com/90115194/186542998-b37f40cb-ccec-4eda-9058-9db567dfdf45.png)

**Comment by gangzhonglv** [comment]
> 你好！从客户的角度简要浏览您的网站，该网站存在许多问题，使我无法在您的网站上真正做任何事情
> 
> 首先，示例的链接受到限制 ![图片](https://user-images.githubusercontent.com/90115194/186541481-34a5f194-5de6-40dd-b0d0-c3f5fd110b61.png)
> 
> 当我尝试加入旅行时，列出的旅行可以追溯到 2010 年，没有可供我查看的近期旅行 ![图片](https://user-images.githubusercontent.com/90115194/186540600-bcc90bb4-720c-4f21-b574-add7493c765d.png)
> 
> 搜索按钮不起作用。当我将鼠标悬停在它上面时，没有手形图标，表示它不可点击，因此上面的选项不可搜索 ![图片](https://user-images.githubusercontent.com/90115194/186540701-4458a804-8ce0-45ff-8783-281590699ed2.png)
> 
> 您的网站流量从未超过 10。人们在使用这个网站吗？ ![图片](https://user-images.githubusercontent.com/90115194/186542998-b37f40cb-ccec-4eda-9058-9db567dfdf45.png)
> 
> 如果我遗漏任何东西，请告诉我:)

Sorry, I'm not very good at setting up Google cloud disk, this link can be viewed
https://drive.google.com/drive/folders/1-V1EzFrZ3-HZ-UFs8a2zbCA0cmRdnd7N?usp=sharing
Due to the impact of the epidemic in China, our business has been affected a lot. In addition, our main business is promotion through offline partners, so the optimization and update of the website is really not in place. Thank you for your comments, we will Find a technician in time for updates and repairs. You can see a large number of cases in the example. The data storage we applied for this time is our large number of pictures and video materials.

**Comment by raghavrmadya** [comment]
Based on the holistic evidence provided by @jessie8o8, this application and client is being closed, IP is being flagged, and the user is being blocked.
