### ISSUE TITLE
[DataCap Application] Shenzhen Youliang Culture Communication Co., Ltd.

### ISSUE THREAD

**Issue by YouliangCulture** [filecoin-project/filecoin-plus-large-datasets#835]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Shenzhen Youliang Culture Communication Co., Ltd.
- Website / Social Media:http://youliangculture.com/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):3PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):200TiB
- On-chain address for first allocation:f1jtltpzqzq2pmud5lmha5hinhci6e3len57vdhga

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Yuliang Culture, China's first-tier MCN agency, was founded in 2019 and is headquartered in Shenzhen, while having branches in Hangzhou, Chengdu and Shanghai. It is a new network culture and entertainment ecological company with short video as the core, with IP incubation, talent e-commerce, red person live, paper magazine, brand operation, film and variety show and other main business of all-round multi-channel cash.
```

What is the primary source of funding for this project?
```
From the company's account.
```

What other projects/ecosystem stakeholders is this project associated with?
```
This is not related to other projects.
```

## Use-case details

Describe the data being stored onto Filecoin
```
The company's artists broadcast a large number of videos and invest in film and TV variety shows that need to be stored.
```

Where was the data in this dataset sourced from?
```
Netflix live streams produce public videos.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://drive.google.com/drive/folders/18pXzi2xdBTmwZsKQ1wGf52CT8HLYsahi?usp=sharing
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes.
```

What is the expected retrieval frequency for this data?
```
Anyone interested in retrieving this data.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
Permanent storage.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
China.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
We will use both online transfer and offline transfer.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We will select miners with good reputation, trustworthiness and experience in verifying data for transactions.
```

How will you be distributing deals across storage providers?
```
We will choose the vendor that can do it as soon as possible to distribute first.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, we want to close the deal as soon as possible.
```

**Comment by raghavrmadya** [comment]
The application is asking for higher weekly allocation without justification. Please open a new application with as much justification as possible including at least 10 data samples.
