### ISSUE TITLE
[DataCap Application] Qianxuan Culture Media On-chain Data Storage Project

### ISSUE THREAD

**Issue by WendellSeering** [filecoin-project/filecoin-plus-large-datasets#837]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Qianxun (Hangzhou) Culture Media Co., Ltd.
- Website / Social Media:http://www.qxwhmcn.com/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):3PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):300TiB
- On-chain address for first allocation:f1uut4h4rxozp2olgzerunvyczxfylar4xgehggaq

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Qianxun is currently one of the largest Reddit e-commerce companies in China in terms of guided transactions, and is also the top1 agency in the Taobao Live rating in previous years. 2019, the company carries out a group layout and focuses on building a live e-commerce industry ecological cluster covering live services, super supply chain base, and brand IP incubation.
```

What is the primary source of funding for this project?
```
The funding comes from the revenues of the company's various business segments.
```

What other projects/ecosystem stakeholders is this project associated with?
```
We have many collaborating shareholders and strategic partners, but no projects or ecosystems that have a stake in this project
```

## Use-case details

Describe the data being stored onto Filecoin
```
Our company has a wide range of business segments and the main forms of data include, but are not limited to, images, text and video. All of our data is legally copyrighted and will not give rise to disputes.
```

Where was the data in this dataset sourced from?
```
Our data is mainly derived from operational data from various business segments of the company, including live replay videos, public data generated from e-commerce operations and merchandising, customized advertising materials designed by the advertising department, etc.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://drive.google.com/drive/folders/14y6jIU9gdfkrn9MbB04KfLFP-YdmeZ8k?usp=sharing
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes, I am sure
```

What is the expected retrieval frequency for this data?
```
There are few opportunities during the year.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
Forever
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
China
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
We will use both online and offline transfers.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We will choose a storage provider with a good reputation, who is trustworthy and understands project data.
```

How will you be distributing deals across storage providers?
```
We will then rationalise the allocation to different storage providers based on whether they have the relevant experience and sustainability
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
We have sufficient funds and resources and have a plan in place and do not need any help for the time being and we hope to conclude the deal as soon as possible.
```

**Comment by raghavrmadya** [comment]
The application is asking for higher weekly allocation without justification. Please open a new application with as much justification as possible including at least 10 data samples.
