### ISSUE TITLE
[DataCap Application] Save Heart Travel

### ISSUE THREAD

**Issue by Josiahlo** [filecoin-project/filecoin-plus-large-datasets#839]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Xinjiang Provincial Heart International Travel Agency Co.
- Website / Social Media:http://www.xjsxgl.com
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):3PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):100TiB
- On-chain address for first allocation:f1gpo4mjstnkflm3xjyaftyegfzka2kxkz4w6voyi

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Ltd. was established in March 2006, after five years of unremitting efforts, in 2010 to obtain the outbound qualification, is a well-known travel agency with good reputation and reputation in the tourism industry in Xinjiang. Over the years, the provincial heart of the CITS in the capital launched the golden sunset warm life large chartered sunset series, thousands of elderly people down south; I am healthy, I am happy, I I am confident ---- water wood Qing Hua release dream summer camp special line and many other tourism products with characteristics, in Xinjiang's tourism market, the Consumers have a very high reputation and are very popular. Relying on the strong airline ticket advantage, always adhering to the thoughtful service concept; meticulous service sentiment, depending on the customer as a family service beliefs. Based on the business purpose of serving peers and win-win cooperation; insisting on a conscientious attitude, the company's business is growing rapidly; the The scale is also gradually growing. Today, the company from a few single domestic lines, to now radiating the country's connecting lines and Hong Kong, Macao and outbound lines.

```

What is the primary source of funding for this project?
```
Company Revenue
```

What other projects/ecosystem stakeholders is this project associated with?
```
none
```

## Use-case details

Describe the data being stored onto Filecoin
```
We have a lot of tour packages, so we need to prepare a lot of pictures, videos of places that have good scenes. We also offer hotel and transportation tour packages, and we have all this data to store.
```

Where was the data in this dataset sourced from?
```
This information is collected by staff in order to develop plans and cases for clients.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://drive.google.com/file/d/1iY6zbHbq06LdZimoDr0-ua4PfdjIokS_/view?usp=sharing
https://drive.google.com/file/d/189EHwabCiRMIgIlOEtIs_A-cegeT8VMi/view?usp=sharing
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
yes
```

What is the expected retrieval frequency for this data?
```
It depends on the actual need
```

For how long do you plan to keep this dataset stored on Filecoin?
```
Two years
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
China, or anywhere else you can make a deal.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Yes, by offline transfer
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We will be looking for some large and reputable suppliers.
```

How will you be distributing deals across storage providers?
```
We will distribute them equally to each storage provider.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, we have
```

**Comment by jessie8o8** [comment]
Hi @Josiahlo! I understand that you are looking for datacap for the images and videos prepared for each tour package.  Looking through your site, there are a couple things I would like to flag from a perspective of a customer.

### 1. Initial perception
![image](https://user-images.githubusercontent.com/90115194/186602050-3390460f-f0b1-454d-9453-babfb522f814.png)
- Why are many of your tours free? 
- Why do all of them have no departure date/city?
- Most of the packages do not have image preview nor additional images in the "package details". Where does the need of datacap come from if there is a lack of image and videos in all the packages?

### 2. Originality
![image](https://user-images.githubusercontent.com/90115194/186604607-b2635b2c-b82b-494b-8690-f5228b5b6233.png)
I have taken a random description line in one of your packages looked it up for verbatim results and have found multiple sources of it. If this part if not original, I do not have confidence that other content on your site will be original
- Your company site: http://www.xjsxgl.com/line_item.html?lineID=101460&limitMonth=3
- Verbatim google search: [Link](https://www.google.com/search?q=%22%EF%BC%88%E8%BD%A6%E7%A8%8B%E7%BA%A6120%E5%88%86%E9%92%9F%EF%BC%8C%E6%B8%B8%E8%A7%88%E6%97%B6%E9%97%B460%E5%88%86%E9%92%9F%EF%BC%89%EF%BC%8C%E7%BA%B3%E5%B8%95%E6%B5%B7%E6%98%AF%E9%A6%99%E6%A0%BC%E9%87%8C%E6%8B%89%E6%8B%89%E5%B8%82%E6%9C%80%E5%A4%A7%E7%9A%84%E8%8D%89%E5%8E%9F%EF%BC%8C%E7%A7%8B%E5%86%AC%E6%9D%A5%E4%B8%B4%EF%BC%8C%E8%8D%89%E5%8E%9F%E4%B8%80%E7%89%87%E9%87%91%E9%BB%84%EF%BC%8C%E8%BF%9C%E5%B1%B1%E5%A6%82%E9%BB%9B%EF%BC%8C%E7%9A%91%E7%9A%91%E9%9B%AA%E5%B3%B0%E5%80%92%E6%98%A0%E4%BA%8E%E6%B9%96%E6%B3%8A%E4%B9%8B%E4%B8%AD%EF%BC%8C%E8%BF%99%E4%B8%80%E5%AD%A3%E8%8A%82%EF%BC%8C%E9%BB%91%E9%A2%88%E9%B9%A4%E3%80%81%E9%BB%84%E9%B8%AD%E3%80%81%E6%96%91%E5%A4%B4%E9%9B%81%E4%BA%91%E9%9B%86%E4%BA%8E%E6%AD%A4%EF%BC%8C%E5%9C%A8%E8%8D%89%E4%B8%9B%E4%B8%AD%E3%80%81%E6%B0%B4%E9%9D%A2%E4%B8%8A%E5%AC%89%E6%88%8F%E6%BC%AB%E6%B8%B8%EF%BC%8C%E4%BD%BF%E5%B9%BF%E9%98%94%E7%A9%BA%E7%81%B5%E7%9A%84%E8%8D%89%E5%8E%9F%E5%8F%A6%E5%85%B7%E4%B8%80%E7%95%AA%E8%AF%97%E6%80%A7%E7%94%BB%E6%84%8F%E3%80%82%E5%8D%88%E9%A4%90%E5%90%8E%E5%89%8D%E5%BE%80%E3%80%90%E6%99%AE%E8%BE%BE%E6%8E%AA%E5%9B%BD%E5%AE%B6%E6%A3%AE%E6%9E%97%E5%85%AC%E5%9B%AD%E3%80%91%22&biw=1565&bih=912&sxsrf=ALiCzsaaPnXb-gT3MJElfomvEIpikQptAw%3A1661412730316&ei=eiUHY73uErbYkPIP29mVoAM&ved=0ahUKEwi9k_bcvOH5AhU2LEQIHdtsBTQQ4dUDCA4&uact=5&oq=%22%EF%BC%88%E8%BD%A6%E7%A8%8B%E7%BA%A6120%E5%88%86%E9%92%9F%EF%BC%8C%E6%B8%B8%E8%A7%88%E6%97%B6%E9%97%B460%E5%88%86%E9%92%9F%EF%BC%89%EF%BC%8C%E7%BA%B3%E5%B8%95%E6%B5%B7%E6%98%AF%E9%A6%99%E6%A0%BC%E9%87%8C%E6%8B%89%E6%8B%89%E5%B8%82%E6%9C%80%E5%A4%A7%E7%9A%84%E8%8D%89%E5%8E%9F%EF%BC%8C%E7%A7%8B%E5%86%AC%E6%9D%A5%E4%B8%B4%EF%BC%8C%E8%8D%89%E5%8E%9F%E4%B8%80%E7%89%87%E9%87%91%E9%BB%84%EF%BC%8C%E8%BF%9C%E5%B1%B1%E5%A6%82%E9%BB%9B%EF%BC%8C%E7%9A%91%E7%9A%91%E9%9B%AA%E5%B3%B0%E5%80%92%E6%98%A0%E4%BA%8E%E6%B9%96%E6%B3%8A%E4%B9%8B%E4%B8%AD%EF%BC%8C%E8%BF%99%E4%B8%80%E5%AD%A3%E8%8A%82%EF%BC%8C%E9%BB%91%E9%A2%88%E9%B9%A4%E3%80%81%E9%BB%84%E9%B8%AD%E3%80%81%E6%96%91%E5%A4%B4%E9%9B%81%E4%BA%91%E9%9B%86%E4%BA%8E%E6%AD%A4%EF%BC%8C%E5%9C%A8%E8%8D%89%E4%B8%9B%E4%B8%AD%E3%80%81%E6%B0%B4%E9%9D%A2%E4%B8%8A%E5%AC%89%E6%88%8F%E6%BC%AB%E6%B8%B8%EF%BC%8C%E4%BD%BF%E5%B9%BF%E9%98%94%E7%A9%BA%E7%81%B5%E7%9A%84%E8%8D%89%E5%8E%9F%E5%8F%A6%E5%85%B7%E4%B8%80%E7%95%AA%E8%AF%97%E6%80%A7%E7%94%BB%E6%84%8F%E3%80%82%E5%8D%88%E9%A4%90%E5%90%8E%E5%89%8D%E5%BE%80%E3%80%90%E6%99%AE%E8%BE%BE%E6%8E%AA%E5%9B%BD%E5%AE%B6%E6%A3%AE%E6%9E%97%E5%85%AC%E5%9B%AD%E3%80%91%22&gs_lcp=Cgdnd3Mtd2l6EANKBAhBGAFKBAhGGABQzroNWIaKDmC-jA5oAnAAeACAAQCIAQCSAQCYAQCgAQHAAQE&sclient=gws-wiz)
- Another tour site: https://www.citscsc.com/lines/show_438.html

### 3. Function
I tried to act as a genuine customer to understand your ideal client experience and could not purchase any packages. All the packages seemed to be unavailable. 
![image](https://user-images.githubusercontent.com/90115194/186605940-d2dd4aa7-b6b9-4928-ab4b-ced2558bf5da.png)
In addition to that, I tried to register but did into get a verification code to create an account. This is not a glitch on one page but a sitewide lack of function. I have read your[ team introduction](http://www.xjsxgl.com/info_detail.html?infoID=10006) and understand that you have multiple departments dedicated to online wholesale and e-commerce. However, this significant contrast in the your company confidence in online sales + age of your company and the lack of function of the site makes me doubtful of the legitimacy of this organization
![image](https://user-images.githubusercontent.com/90115194/186607222-24d4e1c8-2aab-4d31-b18b-abb7fdee55ae.png)

Overall, I do not feel confident with this organization. Especially when the claim to datacap are public images and videos that I cannot seem to find on their site.

I look forward to hearing your response. Please address all the point I have made (Initial perception, originality, and function)

**Comment by raghavrmadya** [comment]
@jessie8o8 , thanks for chiming in and for the due diligence. @Josiahlo , please respond within the next 48 hours else the application will be closed, and the account and IP will be flagged  Thanks.

**Comment by raghavrmadya** [comment]
no response leading to closure
