### ISSUE TITLE
[DataCap Application] Kernelogic - ZINC Database [2/2]

### ISSUE THREAD

**Issue by kernelogic** [filecoin-project/filecoin-plus-large-datasets#842]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Fei Yan - Kernelogic
- Website / Social Media: https://slingshot.kernelogic.ca/ Slack: Fei Yan
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5 PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 750 TiB
- On-chain address for first allocation: f1wzuvevyfwsyqn2stl4kop4zpamv24bxqabyw5gy

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
I have participated every Slingshot phase and is probably the best performing as a "small individual client". 

Even though Slingshot v2 has ended, there are still strong demand from SPs to onboard useful data. This application is to onboard open dataset from AWS.

I will provide a nice web UI to index all files onboarded and provide ways to retrieve.

I have successfully completed a few LDNs on other datasets and I have record to show I have been following the rules of decentralization and have zero self dealing.

https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/60
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/59
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/46
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/297
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/298
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/304
```

What is the primary source of funding for this project?
```
Self-funded, BigD exchange.
```

What other projects/ecosystem stakeholders is this project associated with?
```
enterprise-sp-wg, BigD exchange.
```

## Use-case details

Describe the data being stored onto Filecoin
```
ZINC Database 3D models for molecular docking screens.
Total size: 924.5 TiB
```

Where was the data in this dataset sourced from?
```
AWS Open dataset
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://registry.opendata.aws/zinc15/
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
AWS Open dataset
```

What is the expected retrieval frequency for this data?
```
Multiple times per year.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
18 months.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
All regions.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
I will upload my prepared CAR files to a web server and coordinate with providers to download and propose offline deals.

Maximum 3 copies per SP entity and maximum of 10 copies for every pieceCID.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
Beside the previous SPs I have worked with, I also utilize bigD exchange to further decentralize the storage

To name a few from the community that I deal with regularly: PIKNIK, Holon, CabrinaHuang, HarryM, BigBear, j1v, XinAn Xu, WillTechMusing.

From BigD exchange: Mog Li, Devin Chen, DSS Nathanial Marsh, Rabinovitch, Vin K, arockpool Tony
```

How will you be distributing deals across storage providers?
```
Evenly across all providers I propose to, if they can handle. If a miner is a notary itself, this notary will receive no more than 20% of the total granted datacap.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
I have all I need to start making deals.
```

**Comment by kernelogic** [comment]
Reason to consider this application:
1. This is AWS public open dataset
2. I have good track record of no self dealing and transparent distribution
3. I am one of the two developers of Singularity, capable of onboarding dataset in this scale
4. I will provide a WEB UI for retrievals

**Comment by raghavrmadya** [comment]
<img width="652" alt="Screen Shot 2022-09-13 at 4 39 22 PM" src="https://user-images.githubusercontent.com/91579519/190028121-c7cf9ca5-b630-4922-8090-e56e15c2340a.png">
 
Can you confirm this isn't being violated?

**Comment by raghavrmadya** [comment]
<img width="623" alt="Screen Shot 2022-09-13 at 4 42 01 PM" src="https://user-images.githubusercontent.com/91579519/190028372-3133d90c-cf79-49ad-b23a-eb3de377cd84.png">

Can you confirm this isn't being violated?

**Comment by kernelogic** [comment]
I will email this guy, thanks for the finding.

**Comment by kernelogic** [comment]
Closing this as I did not get the author's approval to redistribute.
