### ISSUE TITLE
[DataCap Application] <Beijing Qianfeng Internet Technology Co.>

### ISSUE THREAD

**Issue by whdhaiifzjeialmsm** [filecoin-project/filecoin-plus-large-datasets#843]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Beijing Qianfeng Internet Technology Co.
- Website / Social Media:http://www.mobiletrain.org/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):3 PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):168TiB
- On-chain address for first allocation:f16qg236nvthjc5mpsqipaz4oiivacoekc7j7hfzy

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Qianfeng's education and training business is dedicated to cultivating high-quality digital technical skills talents, mainly providing college students with skills training, post-vocational skills training, etc. The courses cover front-end, Java, Python, big data, software testing, Internet of Things, cloud computing, network security, Unity, blockchain, UI/UE design, film and television editing and packaging, commercial illustration, game original painting, full media operation, product manager, etc.; in addition, it also launched soft exams, Adobe certification, PMP certification, Huawei certification, Red Hat RHCE certification, Ministry of Public Security certification and other vocational ability certification courses. In addition, we have also launched soft exams, Adobe certification, PMP certification, Huawei certification, Red Hat RHCE certification, Ministry of Industry and Information Technology certification and other vocational ability certification courses; at the same time, the Qianfeng Teaching and Research Institute was established, with the concept of teaching vocational education, and constantly improve the quality and efficiency of Qianfeng vocational education training.
```

What is the primary source of funding for this project?
```
From company operating income.
```

What other projects/ecosystem stakeholders is this project associated with?
```
This is not related to other projects.
```

## Use-case details

Describe the data being stored onto Filecoin
```
The company provides videos and training videos of teaching courses, materials.
```

Where was the data in this dataset sourced from?
```
Public data generated from online operations and training processes.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
http://video.mobiletrain.org/
http://video.mobiletrain.org/video/12/69
http://video.mobiletrain.org/video/7/258
http://video.mobiletrain.org/video/2/515
http://video.mobiletrain.org/video/8/520
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes.
```

What is the expected retrieval frequency for this data?
```
There are very few opportunities throughout the year.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
Permanent storage.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
China.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
We will use both online transfer and offline transfer.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We will consider the security and stability of our suppliers.
```

How will you be distributing deals across storage providers?
```
We will use IPFS distributed storage for fair distribution to miners.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, we have prepared sufficient funds and resources.
```

**Comment by Sunnyiscoming** [comment]
What's the relationship between you and organization? 
How many copies will you store?
Can you provide more detailed information about other storage providers participated in this program, such as you can list SPs you have contacted with at present?
Could you send an email to filplus-app-review@fil.org with your official domain in order to confirm your identity? Email name should includes the issue id #843.

**Comment by Sunnyiscoming** [comment]
Any update here?

**Comment by Sunnyiscoming** [comment]
Close for no reply. You can resubmit your application if necessary.
