### ISSUE TITLE
[DataCap Application] Jiangxi Xinghui Performing Arts Media Co., Ltd.

### ISSUE THREAD

**Issue by sitie121** [filecoin-project/filecoin-plus-large-datasets#844]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Jiangxi Xinghui Performing Arts Media Co., Ltd.
- Website / Social Media: www.99990000.com
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):3 PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):150TiB
- On-chain address for first allocation:f1rfxmn7ggwpe2a7aygski7yejqkgai6dxgxzdf7q

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Xinghui Media is a professional cultural media enterprise integrating public relations planning, large-scale performances, star brokerage, model etiquette and other services.
As a professional public relations planning and performing arts media agency, "Xinghui Media" takes planning high-end events, creating luxurious feasts, and disseminating fashion culture as its own responsibility, efficiently integrating various special event resources, integrating various cutting-edge star performers, and building for customers. The broad service platform provides services in the fields of fashionable commercial marketing public relations activities, large-scale performances, star brokerage, corporate annual meetings, customer appreciation parties, concerts, advertising endorsements, and model artist training.Since its establishment, the company has been recognized by all sectors of society for its thoughtful, fast, efficient, perfect and high-quality services, and has formed a good cooperative relationship with real estate, cosmetics, automobiles and other industries. It has also won the favor and support of local governments, enterprise groups and media, and has won wide reputation and popularity with extraordinary satisfaction.
Remarks: All positions require: good character, quick thinking, strong affinity, carefulness, dedication and love for work, able to bear hardships and stand hard work, good team spirit!
```

What is the primary source of funding for this project?
```
Account from the company.
```

What other projects/ecosystem stakeholders is this project associated with?
```
No
```

## Use-case details

Describe the data being stored onto Filecoin
```
Primarily promotional images for events held on the website.
```

Where was the data in this dataset sourced from?
```
It comes from materials provided by our company and materials uploaded by users themselves.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://drive.google.com/drive/folders/1s0QiEiuRKaQWDecuz5vG3MqoCawZAtEP?usp=sharing
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes
```

What is the expected retrieval frequency for this data?
```
Anyone interested in our brands or products can open and view
```

For how long do you plan to keep this dataset stored on Filecoin?
```
over 3 years
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
China
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
We will use both online and offline transfers.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We will consider the timing and stability of the supplier.
```

How will you be distributing deals across storage providers?
```
We will understand if the storage provider has the relevant experience and sustainability, and based on the analysis we will assign it rationally to different storage providers
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes
```

**Comment by Sunnyiscoming** [comment]
The data samples provided are word., and it's hard to justify you having 3 pb data. Can you explain your data composition and provide sufficient data samples separately? How many copies will you store?
What's the relationship between you and organization? 
Can you provide more detailed information about other storage providers participated in this program, such as you can list SPs you have contacted with at present?

**Comment by Sunnyiscoming** [comment]
Any update here?

**Comment by Sunnyiscoming** [comment]
Close for no reply. You can resubmit your application if necessary.
