### ISSUE TITLE
[DataCap Application] Guangzhou Xinyujia Entertainment Media Culture Co., Ltd.

### ISSUE THREAD

**Issue by XinyujiaEntertainment** [filecoin-project/filecoin-plus-large-datasets#845]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Guangzhou Xinyujia Entertainment Media Culture Co., Ltd.
- Website / Social Media:www.yj543.com
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):2PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):200TiB
- On-chain address for first allocation: f1sps47zey3qyeocne6ziaqwlo3izn5mpq6niyley

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Founded in Guangzhou in 2013, we provide a full chain of value-added services for entertainment live streaming, e-commerce live streaming, business cooperation, new media marketing, etc.
We provide a full chain of value-added services for brands to create effective solutions, and have branches and subsidiaries in many cities in North China, Guangzhou and other cities.
With the mission of "Let there be no buried talent in the world", we are committed to becoming the best Netflix empowerment service provider in China.
```

What is the primary source of funding for this project?
```
From the company's account.
```

What other projects/ecosystem stakeholders is this project associated with?
```
No.
```

## Use-case details

Describe the data being stored onto Filecoin
```
Our company's anchors generate a lot of live material when they broadcast live, and the contracted artists shoot the show variety.
```

Where was the data in this dataset sourced from?
```
It is mainly the video generated during the live broadcast and the video generated during the shooting.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://drive.google.com/drive/folders/15nOVmrQZHOTaHqO-lQ_jmQjk2pMjonMK?usp=sharing
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes.
```

What is the expected retrieval frequency for this data?
```
There are few opportunities during the year.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
Permanent.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
China.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Online.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We will consider the time and stability of the supplier.
```

How will you be distributing deals across storage providers?
```
We will share equally among the miners.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes,we have.
```

**Comment by Sunnyiscoming** [comment]
> Describe the data being stored onto Filecoin
> 
> Our company's anchors generate a lot of live material when they broadcast live, and the contracted artists shoot the show variety.

Can you provide more data samples related with the data being stored onto Filecoin?Can you explain your data composition and provide sufficient data samples separately? How many copies will you store?
What's the relationship between you and organization? 
Can you provide more detailed information about other storage providers participated in this program, such as you can list SPs you have contacted with at present?

**Comment by Sunnyiscoming** [comment]
Any update here?

**Comment by Sunnyiscoming** [comment]
Close for no reply. You can resubmit your application if necessary.
