### ISSUE TITLE
[DataCap Application] Xinjiang Cultural Tourism Investment Group Co., Ltd

### ISSUE THREAD

**Issue by xinjiangwenhualvyoutouzi** [filecoin-project/filecoin-plus-large-datasets#846]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Xinjiang Cultural Tourism Investment Group Co., Ltd
- Website / Social Media:http://xjlytz.com/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 2.81 PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):203TiB
- On-chain address for first allocation:

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```

Xinjiang Culture and Tourism Investment Group Limited, abbreviated as Xinjiang Culture and Tourism Investment, is a state-owned capital investment company established on December 25, 2019 with the approval of the Party Committee and People's Government of the autonomous region. With the general goal of implementing the national "Culture Run Xinjiang" project and the autonomous region's "Tourism Prosperity" strategy, the company has determined the "256" development strategy, with capital operation and operation management as its main tasks, giving full play to the role of the "five platforms" and making full use of the "five platforms" in the development of tourism industry. The company has determined the "256" development strategy, taking capital operation and operation management as the main tasks, giving full play to the role of "five platforms", and making full use of the "five platforms" in six major sectors to promote the transformation of Xinjiang from a large cultural tourism resource area to a strong cultural tourism economic area and promote the high-quality development of Xinjiang's cultural tourism industry.
```

What is the primary source of funding for this project?
```
Scenic Area Development and Operation.
```

What other projects/ecosystem stakeholders is this project associated with?
```
No
```

## Use-case details

Describe the data being stored onto Filecoin
```
Company Development Video.
```

Where was the data in this dataset sourced from?
```
Produced by the Corporate Communications Department
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://drive.google.com/drive/folders/1dkHNSL_5kDMEmPoJZE6_RK-Rxg8djpaN?usp=sharing
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes.
```

What is the expected retrieval frequency for this data?
```
3-6 times a year.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
Permanent.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Guangzhou.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
offline.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
Strong service providers.
```

How will you be distributing deals across storage providers?
```
Average distribution.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, I have enough money.
```

**Comment by raghavrmadya** [comment]
The application is asking for higher weekly allocation without justification. Please open a new application with as much justification as possible including at least 10 data samples.
