### ISSUE TITLE
[DataCap Application] Nswap 

### ISSUE THREAD

**Issue by Awencrypto21** [filecoin-project/filecoin-plus-large-datasets#848]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Nswap 
- Website / Social Media: nswap.space
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5 PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 200TiB
- On-chain address for first allocation: f1u3rzf5re6nvnyjjixcmbk5tderq55vjhudmapny

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Founded in 2021, Nswap has operation teams in China, America, Singapore, England. Nswap is committed to be a safe, reliable and diversified NFT trading platform for the "meta-universe". Following are two business aspects of Nswap:

1. Cooperation agreement between NFT trading platform and artists. At present, we have set up an operation team in the United States to help various well-known artists to launch the platform and provide pre-sales and marketing strategy services.
2. Related software services of NFT trading platform, including data storage and query. At present, we have developed a static website for users to store effective data as a preliminary promotion and operation. In the future, we will optimize and iterate on the App end as well as the Web end, and develop storage services of user personal information and transaction records.
```

What is the primary source of funding for this project?
```
There are three main sources of funding for us:
1. Investment from early investors
2. Fees incurred when users trade NFT on our platform.
3. Commissions generated when artists and brands publish NFT works on our platform.
```

What other projects/ecosystem stakeholders is this project associated with?
```
Our current lines of business are deeply connected to platform users, artists and brands, as well as advertisers.
```

## Use-case details

Describe the data being stored onto Filecoin
```
The data stored on Filecoin is currently NFT data in BOTH 2D and 3D formats, as well as business publicly available data.
```

Where was the data in this dataset sourced from?
```
The centralized data mainly comes from the application data of the project, the data given to us by the platform users, and the data generated by the platform itself.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://www.mediafire.com/file/20mrktd6lu65lva/NFT_lion.webp/file
https://www.mediafire.com/view/oxnhnw8el3wneik/NFT_girl.jfif/file
https://www.mediafire.com/file/nu2o7v3cv5bpndi/NFT_boy.webp/file
https://www.mediafire.com/view/4wi828ugfy27vfv/NFT_chicken.jfif/file
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes, we would like to share public data to the network.
```

What is the expected retrieval frequency for this data?
```
Relatively low frequency
```

For how long do you plan to keep this dataset stored on Filecoin?
```
Maybe 540 days for try first.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
All over the world.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
We would like to try good transfer platform built by the community. No offline process for now.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We would find the storage providers through slack, so that we can talk about their technology.
```

How will you be distributing deals across storage providers?
```
We would choose more than 3 storage providers.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, we have.
```

**Comment by Awencrypto21** [comment]
it can be seen that our project is doing a lot of things during this period, and has cooperated with many projects.
Please take a quick tour of our website, TG, discord and Twitter again. Thanks a lot!
![image](https://user-images.githubusercontent.com/83798519/186606404-b64c8f8d-a74c-49e8-aede-07db50eb7425.png)
![image](https://user-images.githubusercontent.com/83798519/186606452-92bfe228-3caf-476d-a7ea-c3ff25c7c9a0.png)

**Comment by raghavrmadya** [comment]
The application is asking for higher weekly allocation without justification. Please open a new application with as much justification as possible including at least 10 data samples. Additionally, provided data samples are not accessible. Screenshots of social media are not an acceptable proof of legitimate data. 

<img width="1264" alt="Screen Shot 2022-08-25 at 6 18 58 PM" src="https://user-images.githubusercontent.com/91579519/186796051-ec699950-96d7-45da-a764-8de19ec64607.png">
