### ISSUE TITLE
[DataCap Application] Cardpop Animation

### ISSUE THREAD

**Issue by Ethanplq** [filecoin-project/filecoin-plus-large-datasets#849]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Shenzhen Card Puff Animation Design Co.
- Website / Social Media:www.hugeclaw.com
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):3PIB
- Weekly allocation of DataCap requested (usually between 1-100TiB):100TiB
- On-chain address for first allocation:f1ei3fxim5yf5omaccqnzp57ctx3siweyatomdn5y

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Ltd. was established in 2009, is a diversified creative team specializing in film, television, games, culture and special applications. The company is a diversified creative team specializing in film and television, games, culture and special applications, providing concept design, post-production post-production, game promotion, 2D animation, 3D animation, visual effects advertising, integrated visual design, cultural IP creation and original animation Comic IP development and other creative and services

```

What is the primary source of funding for this project?
```
Company business revenue
```

What other projects/ecosystem stakeholders is this project associated with?
```
Affiliated with our partners
```

## Use-case details

Describe the data being stored onto Filecoin
```
Two-dimensional, three-dimensional digital images, motion cartoons, game advertising, mainly video, picture-based
```

Where was the data in this dataset sourced from?
```
Public data in the process of brand operation and product sales
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://drive.google.com/drive/folders/1kr0-EPRZ31vLmHPMu1wgacVZhVMhQyLL?usp=sharing
http://player.youku.com/embed/XNTE4Njk1Mjk5Ng?autoplay=false&client_id=34d1a54ddda198a6
https://player.youku.com/embed/XNTg3NTI4MzA0NA?autoplay=false&client_id=34d1a54ddda198a6
http://player.youku.com/embed/XNDg4MDE3NDg0OA?autoplay=false&client_id=34d1a54ddda198a6
http://player.youku.com/embed/XNDY5MTM3NjczNg?autoplay=false&client_id=34d1a54ddda198a6
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
yes.
```

What is the expected retrieval frequency for this data?
```
Anyone interested in this data
```

For how long do you plan to keep this dataset stored on Filecoin?
```
Permanent
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
China
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
We can have an offline data transfer process. How the data is distributed will depend on the network.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
Choose a well-funded storage provider that understands project data
```

How will you be distributing deals across storage providers?
```
We will allocate an equal share to high quality storage providers. In addition, each miner will not be allocated more than 25% of our data volume.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, we don't need any help for now
```

**Comment by Sunnyiscoming** [comment]
![image](https://user-images.githubusercontent.com/105098820/192175258-3be658ec-114f-473a-b745-f4b9cbcbc0bb.png)
The website do not work. Please check it.

What's the Chinese name of your organization? Can you share the link of it in tianyancha.

**Comment by Sunnyiscoming** [comment]
Any update here?

**Comment by Sunnyiscoming** [comment]
No reply.
