### ISSUE TITLE
飞图影像

### ISSUE THREAD

**Issue by llb890427** [filecoin-project/filecoin-plus-large-datasets#85]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: 飞图影像
- Website / Social Media:http://www.ftimage.cn/  
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):3PB
- Weekly allocation of DataCap requested (usually between 1-100TiB):100T
- On-chain address for first allocation:f12y74czbkrjizcwwudvrsfdbmgpxarfrpfovpjwq

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
Is a high-tech enterprise focusing on providing medical image big data management application services. Based on the fusion innovation of big data, cloud computing, artificial intelligence, mobile Internet technology and medical imaging science, FTU Has independently researched and developed the "Professional image cloud + ARTIFICIAL intelligence application platform", with medical image cloud service as the core, providing a complete solution of "software + hardware + services". Enable medical institutions at all levels to realize informatization construction and the application of "Internet Plus", and promote the construction of healthy China.

What is the primary source of funding for this project?
Cooperate with large hospitals, store the data generated by the hospital in the background of FeITU, and provide relevant convenient technical services for the hospital

What other projects/ecosystem stakeholders is this project associated with?
This is a complete medical ecological system, from patients, doctors, Internet medical, massive data storage platform, are ecological stakeholders, which are more valuable interests. In terms of projects alone, investors in hospitals and companies are a better answer.

## Use-case details

Describe the data being stored onto Filecoin
Mainly patient's personal information, medical record, medical film, consultation video, etc

Where was the data in this dataset sourced from?
Data generated every day from major hospitals

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
Sorry, due to the special limitations of the project itself, it is impossible to provide data samples that can be retrieved (in essence, it belongs to users' privacy, and we are very optimistic about the official data fragmentation scheme to ensure data security). Use cases can be viewed from the website. http://www.ftimage.cn/applications
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
No, this is a relatively private data set in the industry

What is the expected retrieval frequency for this data?
The data will exist in archived backup form and will only be retrieved by managers during maintenance and validation of the data.

For how long do you plan to keep this dataset stored on Filecoin?
This depends on the security of distributed storage. If the authentication is successful, it will be stored in the network for a long time

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
It is planned for greater China
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Our plan is to do 100T per week
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
Through the offline data transmission, and combined with the data itself to set a specific transmission protocol
```

How will you be distributing deals across storage providers?
```
We need to confirm that it is a large and stable storage provider in the industry within our designated region, and ensure the periodic internal check of data validity through business negotiations
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, we have negotiated with the head storage provider. If you receive DataCap, you can start trading as soon as possible
```

**Comment by galen-mcandrew** [comment]
Hello @llb890427 at this time, the large dataset process is intended for public client data. It sounds like you are hoping to upload private or encrypted data, which we are not able to validate and verify at this time.

**Comment by dkkapur** [comment]
@llb890427 we are experimenting with supporting encrypted and private data. Can you confirm you are still interested in onboarding this and how you can prove you own this data and can safely store it? Are there any licenses or business agreements you can share?

**Comment by dkkapur** [comment]
Hi. Closing this one out. @llb890427 please re-open if still relevant. Thanks!
