### ISSUE TITLE
[DataCap Application]Guangdong Heyi Business Information Technology Co., Ltd

### ISSUE THREAD

**Issue by skhadjwqdj** [filecoin-project/filecoin-plus-large-datasets#850]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name:Guangdong Heyi Business Information Technology Co., Ltd 
- Website / Social Media:[http://www.heyiedu.com/](https://www.qcc.com/web/transfer-link?link=http%3A%2F%2Fwww.heyiedu.com%2F)
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):4PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):200TiB
- On-chain address for first allocation:f16ejyhq3y4pu32x4fhxvgfhn2znkinkobebiy6ri

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Guangdong Heyi Business Information Technology Co., Ltd. is a business institution focusing on wealth investment, aiming to create a business platform for Chinese entrepreneurs and high net worth investors to spread correct investment concepts, improve investor skills and cultivate wealth investment propagation. The integrated business course is divided into three systems, namely, trend investment, value investment and wealth inheritance; It has opened courses in Dongguan, Guangzhou and Shenzhen, and has long-term and stable cooperation with major domestic securities futures, banks, insurance, private equity funds and entrepreneur associations. There are nearly 200 public welfare investment salons every year. After years of precipitation, we have built an all-round education service system from sorting out investment concepts to investment simulation testing, technical standard quantification to investment emotion management, from investment ability training to wealth thinking inheritance
```

What is the primary source of funding for this project?
```
The capital comes from the investment of shareholders.
```

What other projects/ecosystem stakeholders is this project associated with?
```
No,
```

## Use-case details

Describe the data being stored onto Filecoin
```
Teaching video, student sharing and various consulting
```

Where was the data in this dataset sourced from?
```
It comes from the materials provided by our company and the materials uploaded by users themselves.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
(https://drive.google.com/drive/folders/1eO7575MT02C4KdL8mAIxaPBzExahBEi0?usp=sharing)
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes
```

What is the expected retrieval frequency for this data?
```
It depends on the actual needs.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
Always stored
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
China
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
We can have an offline data transmission process. How data is distributed will depend on the network.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
The supplier's time and stability will be considered.
```

How will you be distributing deals across storage providers?
```
Distributed equally to each storage vendor.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
We have
```

**Comment by jessie8o8** [comment]
Hello! The hyperlink you have provided (https://www.qcc.com/web/transfer-link?link=http%3A%2F%2Fwww.heyiedu.com%2F)

Leads me to this page 
![image](https://user-images.githubusercontent.com/90115194/186811985-a58d95c9-3c54-41c0-b8ef-45e8362eb18a.png)

What can I do here to help me review your company if I can't log in?

**Comment by Sunnyiscoming** [comment]
Can you provide more data samples related with eaching video?Can you explain your data composition and provide sufficient data samples separately? How many copies will you store?
What's the relationship between you and organization?
Can you provide more detailed information about other storage providers participated in this program, such as you can list SPs you have contacted with at present?

**Comment by Sunnyiscoming** [comment]
Any update here?

**Comment by Sunnyiscoming** [comment]
No reply.
