### ISSUE TITLE
[DataCap Application] Liancheng Media (Dalian) Co., Ltd.

### ISSUE THREAD

**Issue by sitie122** [filecoin-project/filecoin-plus-large-datasets#851]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Liancheng Media (Dalian) Co., Ltd.
- Website / Social Media:www.lccm.cn
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 3 PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):150TiB
- On-chain address for first allocation:f1ymq327nu7uioit3fo4rxf2tu2cs427sxq2gszaa

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Liancheng Media (Dalian) Co., Ltd. (Liancheng Media) is an Internet company specializing in online marketing for small and medium-sized enterprises. With a new Internet marketing model, it helps small and medium-sized enterprises to achieve breakthroughs from 0 to 1 in the field of Internet marketing and advertising, and create a blue ocean in the red ocean. , to help enterprises double their network marketing performance. The label of Liancheng Media is Dalian's whole network integrated marketing, effect marketing, and core products. It builds a marketing brand official website for enterprises, realizes the homepage ranking of core keywords, and helps enterprises to market through ten thousand sites, whole network coverage, and massive exposure. It is the Southern Netcom G3 cloud promotion Dalian operation center, Yiduan network-wide marketing system to achieve network-wide coverage, soft article marketing, enterprise encyclopedia,Baidu Koubei and other brand building and mobile Internet marketing include WeChat marketing, information flow advertising, DSP advertising, big data marketing, precision marketing, and cooperation with Liancheng Media, allowing you to quickly and easily surpass your peers. -Lianchengjue network marketing system, we are different from others, network marketing needs planning, network marketing needs operation, and network marketing needs results! We can help you! Our implementation attitude is not to land, not to give up! The mission of our team is to help small and medium-sized enterprises achieve breakthroughs from 0 to 1 in the field of Internet marketing and advertising with a new Internet marketing model, create a blue ocean in the red ocean, and help enterprises to double their network marketing performance!
```

What is the primary source of funding for this project?
```
Account from the company.
```

What other projects/ecosystem stakeholders is this project associated with?
```
This has nothing to do with other projects.
```

## Use-case details

Describe the data being stored onto Filecoin
```
Primarily promotional images for events held on the website.
```

Where was the data in this dataset sourced from?
```
It comes from materials provided by our company and materials uploaded by users themselves.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://drive.google.com/drive/folders/1T_Mb0ixFrZLqKu_2cZbqPMLq2dHW8sqp?usp=sharing
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes
```

What is the expected retrieval frequency for this data?
```
Anyone interested in our brand or products can open it to view.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
permanent
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
China
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
We will use both online and offline transfers.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
Choose a storage provider that has deep pockets and understands project data.
```

How will you be distributing deals across storage providers?
```
We will distribute evenly to each storage provider.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, we have.
```

**Comment by jessie8o8** [comment]
Hello @sitie122 ! The dataset sample that you have provided in your application has unoriginal work and was sourced on Behance in 2012
![image](https://user-images.githubusercontent.com/90115194/186811317-1ab116d7-2f58-4794-b375-683a585299ed.png)

I do not have confidence that this is a legitimate organization if they have claimed such work as theirs and do not feel comfortable granting datacap to stolen work

Behance link: https://www.behance.net/gallery/3195195/Louis-Vuitton-Travel-brochure

**Comment by sitie122** [comment]
> Hello @sitie122 ! The dataset sample that you have provided in your application has unoriginal work and was sourced on Behance in 2012 ![image](https://user-images.githubusercontent.com/90115194/186811317-1ab116d7-2f58-4794-b375-683a585299ed.png)
> 
> I do not have confidence that this is a legitimate organization if they have claimed such work as theirs and do not feel comfortable granting datacap to stolen work
> 
> Behance link: https://www.behance.net/gallery/3195195/Louis-Vuitton-Travel-brochure

This one is certainly not original to us, because we are not a film company originally, but a publicity company. We don't make movies, we help promote them. Movie stills are our basic material. I wish people like you would not be so smart and self-righteous.
@raghavrmadya @jbenet @sitie122 
The fil project, which would have required a large number of companies to participate together. Now we are paying human and material resources to support the development of fil, why should we be questioned and judged by such people? I think the governance team and the community need to do some soul-searching.
At the same time, it is more important to think about one question: when a large number of companies are willing to participate, is your first reaction to be skeptical and resistant, or to welcome and believe? Is it necessary to turn away applicants right in the middle of the application process? If the threshold is high, is that good for the development of fil or not?
@raghavrmadya The people who are still involved in the fil project are those who have faith in fil and support it. I think it is very stupid to raise the threshold and strengthen the kyc audit and so on now, it is shutting out the believers, I hope you can think about this issue or react to your superiors.

**Comment by Sunnyiscoming** [comment]
@sitie122 No offense. Welcome to FIL+ family. There are still some questions about your application, and I hope to get your patient reply.

1. Did you make the corporate video, such as the data samples you provided, by yourself?
2. In large datasets, individuals and enterprises apply for datacap with open and vailable data to subsidize storage costs. The public data stored should be the applicant's own data, non-commercial data, and authorized commercial data. If you want to store data of the three types mentioned above, there is no problem.
3. Can you provide more data samples related with the data you will store, primarily promotional images for events held on the website?Can you explain your data composition and provide sufficient data samples separately? How many copies will you store?
4. Can you provide more detailed information about other storage providers participated in this program, such as you can list SPs you have contacted with at present?

**Comment by Sunnyiscoming** [comment]
Any update here?

**Comment by Sunnyiscoming** [comment]
No reply.
