### ISSUE TITLE
[DataCap Application] Boom Adverisng Media Co. Ltd.

### ISSUE THREAD

**Issue by thrbowl** [filecoin-project/filecoin-plus-large-datasets#852]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Boom Adverisng Media Co. Ltd.
- Website / Social Media: http://www.boom-ad.cn/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5 PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100TiB
- On-chain address for first allocation: f1ucw52kv3o7ztmikgmc5cdeq6msr5vdmnmeb3c5a

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Beijing Boom Adverisng Media Co., Ltd. was established in 2019.

Customers covering e-commerce, games, finance and other industries

The company's business scope: design, production, agency, advertising; Graphic design; Logo design; Computer graphic design and production; Packaging design; Enterprise planning; Technology promotion services; Brand planning; Organizing cultural and artistic exchange activities; To undertake exhibitions and exhibitions; Conference services; Computer animation design; Technical consultation, technical promotion.
```

What is the primary source of funding for this project?
```
Income of the company and investment of shareholders.
```

What other projects/ecosystem stakeholders is this project associated with?
```
No other projects/ecosystem stakeholders.
```

## Use-case details

Describe the data being stored onto Filecoin
```
Around 1.5 billion ad requests per month.

Public website data, product content created in about 4 years.Including but not limited to a large number of user information,image, video, audio, artwork, design, photography and other types of data related to advertising.
```

Where was the data in this dataset sourced from?
```
Mainly data are made by ourselves, some of them are synced to us by customers.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
Here are some data samples. For privacy reasons, user data is not provided directly here.

Our data includes
  1 User clicks log
  2 Advertising analysis logs
  3 Advertising big data recommendation of each country
  Because some of the materials involve customer privacy, it is inconvenient to show them in detail here. This is a screenshot of the amount of material displayed at part of the time. We confirm that a lot of storage space is required.

https://user-images.githubusercontent.com/109211726/183399725-a74b50ff-59e0-4ec6-a637-be4a791aee0d.png
http://www.boom-ad.cn/private/datareport2022.png
https://www.boom-ad.cn/dataview/data.zip
But we will not store private data.
For contractual and security reasons, customer-related data will only be stored in our own data center.
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes, We confirm that the data is public and it can be retrieved by anybody. 
```

What is the expected retrieval frequency for this data?
```
Because making new products requires access to previous data, we want the data to be retrieved as often as possible.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
We hope at least 2 years.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Greater China
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Online transfer and offline copy.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We will choose stable and experienced storage providers to store different data in case all data is damaged or lost.

If the application is approved, we will look for SP based on subsequent needs and geographic location.

Currently all of our data is stored in AWS S3 and is archived automatically for 180 days.

Our storage needs to record all the details and keep the data for at least 10 years.
1 Snapshot archive (including videos) after the advertisement is released, which will exceed 100T every month.
2 User access logs, about 15-20T of compressed logs are generated every month.
3 The logs of the advertising analysis system generate 10-20T data every month.
4 Advertising big data recommendation, generating a total of 15-20T archived data every month.

At present, the demand of 1-1.2P needs to be generated every year, and the annual increase is about 35-50%.

If DataCap can provide online video playback and can be automatically archived, we can also put the video storage part on DataCap. The current data stock in this part is about 1.2-1.5P. And it's rising every year.
```

How will you be distributing deals across storage providers?
```
Less than 25% data for every storage providers. 
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Of course, We have made sufficient preparations. 
```

**Comment by jessie8o8** [comment]
Hi @thrbowl ! What is your Business license number/统一社会信用代码? I would like to look your company up on https://www.gsxt.gov.cn/

Also, I understand you do design, production, agency, advertising; Graphic design; Logo design; Computer graphic design and production; Packaging design; Enterprise planning; Technology promotion services; Brand planning; Organizing cultural and artistic exchange activities; Conference services; Computer animation design; Technical consultation, technical promotion. Why does your website only display advertisement services?

**Comment by thrbowl** [comment]
@jessie8o8 
1. 统一社会信用代码：91110105MA01KFQ54T
2. At present, our main business is advertising services, other businesses are relatively less involved, and we hope that the content stored on DataCap is also advertising-related data. The main business scope of the company written before is all the items shown on the business license.

**Comment by jessie8o8** [comment]
You have described your data composition having `user information, image, video, audio, artwork, design, photography`. 

I am perceiving a contrast between what is described in the application and what you say is the true dataset composition. 

Does your company do graphic design and photography? 
- If not, why does your dataset description say so? And what file types is your dataset really composed of?
- If so, can you send a sample data of a graphical design product your company has produced? Along with the source file? (Please don't send a jpg or png but rather a vector file with the layers)

Thanks :)

**Comment by thrbowl** [comment]
@jessie8o8 
Thank you for your replay.

1. We are not an advertising design company. Our main business is the placement of advertising services. The delivered content includes image, videos, audios, etc. Some of this content is provided by customers, and some are produced by ourselves.

2. As an example, this is a video and material we made. 
(because of copyright issues, the link is valid for 24 hours. Please check and download in time. Private use and external dissemination are strictly prohibited, thank you)
Link：https://pan.baidu.com/s/1kUFu9If6MGkfYCYHCWBJkw
Password:aakb

**Comment by jessie8o8** [comment]
Hi @thrbowl . It's not loading for me right now but I would like to ask: Why is there a restriction? I thought this data was public / `no specific permissions or access rights are required to view the data`

Ill try view it later today though!

**Comment by thrbowl** [comment]
@jessie8o8 
Could it be that the link from the last reply cannot be opened?That link is generated locally by the data store. Now the data has been uploaded.
This is a new link, please try again.
http://www.boom-ad.cn/dataview/video0826.zip

**Comment by Sunnyiscoming** [comment]
> The restrictions are now lifted, but no one else is allowed to reprocess and use them commercially.

The dataset for FIL+ should be publicly available for everyone to download and use. If you have data limitations, I suggest you follow the E-FIL+ program. Or delete data that is not fully public and adjust the amount of data requested.

http://www.boom-ad.cn/dataview/video0826.zip is a large files of 5.1GB. It is suggested that you can split the files and upload again, so that community users can view more friendly. 

What's the relationship between you and organization?

Can you provide more detailed information about other storage providers participated in this program, such as you can list SPs you have contacted with at present?

**Comment by thrbowl** [comment]
@Sunnyiscoming 
1. We have removed non-fully public data, and split the files and upload again.
We still need the amount of data we requested earlier.
http://www.boom-ad.cn/dataview/video0927/endpage.zip
http://www.boom-ad.cn/dataview/video0927/font1.zip
http://www.boom-ad.cn/dataview/video0927/font2.zip
http://www.boom-ad.cn/dataview/video0927/font3.zip
http://www.boom-ad.cn/dataview/video0927/resource/endpage.zip
http://www.boom-ad.cn/dataview/video0927/resource/fighting.zip
http://www.boom-ad.cn/dataview/video0927/resource/flat.zip
http://www.boom-ad.cn/dataview/video0927/resource/reference.zip
http://www.boom-ad.cn/dataview/video0927/resource/runningaction.zip
http://www.boom-ad.cn/dataview/video0927/resource/scene.zip
http://www.boom-ad.cn/dataview/video0927/resource/solidcolor.zip

2. I am an employee of this company.

3. We will choose stable and experienced storage providers to store different data in case all data is damaged or lost. If the application is approved, we will look for SP based on subsequent needs and geographic location. Currently all of our data is stored in AWS S3 and is archived automatically for 180 days.

**Comment by Sunnyiscoming** [comment]
http://www.boom-ad.cn/dataview/video0927/endpage.zip
http://www.boom-ad.cn/dataview/video0927/font1.zip
http://www.boom-ad.cn/dataview/video0927/font2.zip
http://www.boom-ad.cn/dataview/video0927/font3.zip
http://www.boom-ad.cn/dataview/video0927/resource/endpage.zip
http://www.boom-ad.cn/dataview/video0927/resource/fighting.zip
http://www.boom-ad.cn/dataview/video0927/resource/flat.zip
http://www.boom-ad.cn/dataview/video0927/resource/reference.zip
http://www.boom-ad.cn/dataview/video0927/resource/runningaction.zip
http://www.boom-ad.cn/dataview/video0927/resource/scene.zip
http://www.boom-ad.cn/dataview/video0927/resource/solidcolor.zip
These link do not work. Please check them.

Could you send an email to filplus-app-review@fil.org with your official domain in order to confirm your identity? Email name should includes the issue id #843.

**Comment by thrbowl** [comment]
@Sunnyiscoming 
1. Copy the link, paste it in a new tab of your browser, and you can download the file directly.
![832E43CC-5987-40BD-9071-06A1F67D8580](https://user-images.githubusercontent.com/1860809/193000797-e23c35de-500a-4325-8c52-15bf7143f8b8.png)
2. I can only send email names that include the issue id #852. Because of issue id #843. I didn't apply for it.
3. The email has been sent, please check, thank you！

**Comment by Sunnyiscoming** [comment]
Sorry for mistaken. #852 is the right issue number. Email received.
I tried to copy the link, paste it in a new tab of your browser, but I can not download the file directly.

**Comment by thrbowl** [comment]
@Sunnyiscoming @jessie8o8 
We have confirmed once again that the link can be opened and downloaded.

https://user-images.githubusercontent.com/1860809/194695636-8fdad1e8-1b35-49d8-b2c4-10933d300034.MOV


https://user-images.githubusercontent.com/1860809/194695670-2a8ea4cb-0566-4b64-934c-d683b2609efa.MOV

And I have sent an email with links to filplus-app-review@fil.org. Please copy the link, make sure that paste it in a new tab of your browser, and you can download the file directly.
Please check the link again, thank you.

**Comment by thrbowl** [comment]
@jessie8o8 @Sunnyiscoming 
Will the above link be able to open and download the file normally?
If you have any other questions,please do not hesitate to contact me.

**Comment by raghavrmadya** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 100TiB

**Client address**

>f1ucw52kv3o7ztmikgmc5cdeq6msr5vdmnmeb3c5a

**Comment by raghavrmadya** [comment]
Notaries, please check the samples before signing

**Comment by Tom-OriginStorage** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec5qyysghpbrr5nxt4okhrvwdjmpbhvtfaz3m5mnh7fuhuajiajkq 
#### Address 
> f1ucw52kv3o7ztmikgmc5cdeq6msr5vdmnmeb3c5a
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1q6bpjlqia6iemqbrdaxr2uehrhpvoju3qh4lpga
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec5qyysghpbrr5nxt4okhrvwdjmpbhvtfaz3m5mnh7fuhuajiajkq

**Comment by kernelogic** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecyusq5vri2u6mbrkbahnpbb7hy3r3ijsls6dunna2xv4thxk7hhm 
#### Address 
> f1ucw52kv3o7ztmikgmc5cdeq6msr5vdmnmeb3c5a
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecyusq5vri2u6mbrkbahnpbb7hy3r3ijsls6dunna2xv4thxk7hhm

**Comment by fabriziogianni7** [comment]
## DataCap Allocation requested

#### Multisig Notary address
> f01858410

#### Client address
> f1ucw52kv3o7ztmikgmc5cdeq6msr5vdmnmeb3c5a

#### DataCap allocation requested
> 100TiB

**Comment by fabriziogianni7** [comment]
## DataCap Allocation requested

#### Multisig Notary address
> f01858410

#### Client address
> f1ucw52kv3o7ztmikgmc5cdeq6msr5vdmnmeb3c5a

#### DataCap allocation requested
> 100TiB

**Comment by newwebgroup** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb4gskkrooxbrqt7slbfqw5xdoizkeevlis3gvrcnnebkggakmhaw 
#### Address 
> f1ucw52kv3o7ztmikgmc5cdeq6msr5vdmnmeb3c5a
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1e77zuityhvvw6u2t6tb5qlnsegy2s67qs4lbbbq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb4gskkrooxbrqt7slbfqw5xdoizkeevlis3gvrcnnebkggakmhaw

**Comment by fireflyHZ** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaaebc2yraib3laxdisb4p6jn3xeojzyhnt4ap62ndpgc463bvoqc 
#### Address 
> f1ucw52kv3o7ztmikgmc5cdeq6msr5vdmnmeb3c5a
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1fg6jkxsr3twfnyhdlatmq36xca6sshptscds7xa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaaebc2yraib3laxdisb4p6jn3xeojzyhnt4ap62ndpgc463bvoqc

**Comment by BigD-Exchange** [comment]
@thrbowl Hi! Great to see you have gotten approval for DataCap. If you are looking for storage providers to store these data or have any questions, please visit #bigdata-exchange on Filecoin Slack or reply here. 

We have strong demand from a diverse group of SPs, who are actively looking to onboard more data.

**Comment by Tom-OriginStorage** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaotslpocnscu3e4r4a3gjplcket4jybt6ithefd2gmv4ldzezigq 
#### Address 
> f1ucw52kv3o7ztmikgmc5cdeq6msr5vdmnmeb3c5a
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1q6bpjlqia6iemqbrdaxr2uehrhpvoju3qh4lpga
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaotslpocnscu3e4r4a3gjplcket4jybt6ithefd2gmv4ldzezigq

**Comment by ipfscn** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceboweptvi2erpkgvg3tvvkdxuveddo5prgrtdnqjpsnc3s4wbk5rq 
#### Address 
> f1ucw52kv3o7ztmikgmc5cdeq6msr5vdmnmeb3c5a
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1j4n74chme7whbz3yls4a7ixqewb6dijypqg2a3a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceboweptvi2erpkgvg3tvvkdxuveddo5prgrtdnqjpsnc3s4wbk5rq

**Comment by kernelogic** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebvfiqodilpljvwtfsr3xaq2uwunyllhm4scpmdfd2mfa2jg7jmq2 
#### Address 
> f1ucw52kv3o7ztmikgmc5cdeq6msr5vdmnmeb3c5a
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebvfiqodilpljvwtfsr3xaq2uwunyllhm4scpmdfd2mfa2jg7jmq2

**Comment by liyunzhi-666** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceau5cuawkbtzdwbjmqca3stvikmpxklkbg5eu26s2uvtz2n6gxtbq 
#### Address 
> f1ucw52kv3o7ztmikgmc5cdeq6msr5vdmnmeb3c5a
#### Datacap Allocated
> 400.00TiB
#### Signer Address
> f1pszcrsciyixyuxxukkvtazcokexbn54amf7gvoq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceau5cuawkbtzdwbjmqca3stvikmpxklkbg5eu26s2uvtz2n6gxtbq

**Comment by Tom-OriginStorage** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaomgnlqob2sh7tmthx5dofxazqp3rku7k662pojwh2htmfdp6lus 
#### Address 
> f1ucw52kv3o7ztmikgmc5cdeq6msr5vdmnmeb3c5a
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1q6bpjlqia6iemqbrdaxr2uehrhpvoju3qh4lpga
#### Id
> 98b507fd-c0aa-4d09-9e6e-a6b28f666aba
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaomgnlqob2sh7tmthx5dofxazqp3rku7k662pojwh2htmfdp6lus

**Comment by liyunzhi-666** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceavzlo74yywyde6fma34hm3ymtsj3pygkwswm3urahwaf45sudtfk 
#### Address 
> f1ucw52kv3o7ztmikgmc5cdeq6msr5vdmnmeb3c5a
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1pszcrsciyixyuxxukkvtazcokexbn54amf7gvoq
#### Id
> 98b507fd-c0aa-4d09-9e6e-a6b28f666aba
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceavzlo74yywyde6fma34hm3ymtsj3pygkwswm3urahwaf45sudtfk

**Comment by Joss-Hua** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebyejccenhru5wnlhua7gbntq2pddxl2lzfxpzduux35qwhb3q3ns 
#### Address 
> f1ucw52kv3o7ztmikgmc5cdeq6msr5vdmnmeb3c5a
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1tfg54zzscugttejv336vivknmsnzzmyudp3t7wi
#### Id
> 3069b753-ba90-46fb-8b38-8c7138f73e8e
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebyejccenhru5wnlhua7gbntq2pddxl2lzfxpzduux35qwhb3q3ns

**Comment by Tom-OriginStorage** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebtsta4vkyoqwopyukzgcez76gogdg35mzt2knzlwkhjt2napyvea 
#### Address 
> f1ucw52kv3o7ztmikgmc5cdeq6msr5vdmnmeb3c5a
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1q6bpjlqia6iemqbrdaxr2uehrhpvoju3qh4lpga
#### Id
> 3069b753-ba90-46fb-8b38-8c7138f73e8e
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebtsta4vkyoqwopyukzgcez76gogdg35mzt2knzlwkhjt2napyvea

**Comment by NDLABS-OFFICE** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec5ys3kdrxgjeaew4bcen3vfmzvblk2sxnbfpsqecla4tbybkf276 
#### Address 
> f1ucw52kv3o7ztmikgmc5cdeq6msr5vdmnmeb3c5a
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1yayfsv6whu3rheviucvventj3y6t542xfpb47ei
#### Id
> 1d90302d-7e58-4acb-8614-baa75954c97c
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec5ys3kdrxgjeaew4bcen3vfmzvblk2sxnbfpsqecla4tbybkf276

**Comment by fireflyHZ** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebof4xjglzr7c4kynjtql6pjtghokmctst2ojbm4dnxuzxpisczpg 
#### Address 
> f1ucw52kv3o7ztmikgmc5cdeq6msr5vdmnmeb3c5a
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1fg6jkxsr3twfnyhdlatmq36xca6sshptscds7xa
#### Id
> 1d90302d-7e58-4acb-8614-baa75954c97c
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebof4xjglzr7c4kynjtql6pjtghokmctst2ojbm4dnxuzxpisczpg

**Comment by stcouldlisa** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecbh7l2k3hetdg7pyqracw7fqzez6t73kpe5hnsqf2fhyoruxt3pa 
#### Address 
> f1ucw52kv3o7ztmikgmc5cdeq6msr5vdmnmeb3c5a
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1jvvltduw35u6inn5tr4nfualyd42bh3vjtylgci
#### Id
> 58c9812e-af0d-4219-bd22-323d0520a219
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecbh7l2k3hetdg7pyqracw7fqzez6t73kpe5hnsqf2fhyoruxt3pa

**Comment by Tom-OriginStorage** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceablhxukyhqda7zezdooxwcox3r6dmdaqmrskq5ddeadte6a55pzs 
#### Address 
> f1ucw52kv3o7ztmikgmc5cdeq6msr5vdmnmeb3c5a
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1q6bpjlqia6iemqbrdaxr2uehrhpvoju3qh4lpga
#### Id
> 58c9812e-af0d-4219-bd22-323d0520a219
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceablhxukyhqda7zezdooxwcox3r6dmdaqmrskq5ddeadte6a55pzs

**Comment by stcouldlisa** [comment]
The quota allocation of each SP is reasonable, and the maximum does not exceed 21%
I randomly checked the data to check, indeed, it is the data related to the company that applied.
So far, this is an honest customer.

**Comment by NDLABS-OFFICE** [comment]
Top Allocation ：16%
I am willing to support and continue to follow.

**Comment by NDLABS-OFFICE** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebdmt5fivpvcxrrjcr63zetj4l3agdt4cljdlxyjuqoramjfd6eee 
#### Address 
> f1ucw52kv3o7ztmikgmc5cdeq6msr5vdmnmeb3c5a
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1yayfsv6whu3rheviucvventj3y6t542xfpb47ei
#### Id
> d0a40676-c153-4751-a3f5-e25682a12e0f
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebdmt5fivpvcxrrjcr63zetj4l3agdt4cljdlxyjuqoramjfd6eee

**Comment by newwebgroup** [comment]
Check items
1. Distribution proportion of SP
Top Allocation ：16%+
2. Location distribution of SPs
Located in four regions, Busan, South Korea, HK, the United States and Singapore

**Comment by newwebgroup** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec7htpaama6ktq5vls2mhyxctf4yhbrse7hm4fjftjlolm44d3txe 
#### Address 
> f1ucw52kv3o7ztmikgmc5cdeq6msr5vdmnmeb3c5a
#### Datacap Allocated
> 800.00TiB
#### Signer Address
> f1e77zuityhvvw6u2t6tb5qlnsegy2s67qs4lbbbq
#### Id
> d0a40676-c153-4751-a3f5-e25682a12e0f
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec7htpaama6ktq5vls2mhyxctf4yhbrse7hm4fjftjlolm44d3txe

**Comment by filplus-checker** [comment]
## DataCap and CID Checker Report[^1]
 - Organization: `Boom Adverisng Media Co. Ltd.`
 - Client: `f1ucw52kv3o7ztmikgmc5cdeq6msr5vdmnmeb3c5a`
### Storage Provider Distribution
The below table shows the distribution of storage providers that have stored data for this client.

If this is the first time a provider takes verified deal, it will be marked as `new`.

For most of the datacap application, below restrictions should apply.
 - Storage provider should not exceed 25% of total datacap.
 - Storage provider should not be storing duplicate data for more than 20%.
 - Storage provider should have published its public IP address.
 - All storage providers should be located in different regions.

✔️ Storage provider distribution looks healthy.

| Provider                                                    |                           Location | Total Deals Sealed | Percentage | Unique Data | Duplicate Deals |
| :---------------------------------------------------------- | ---------------------------------: | -----------------: | ---------: | ----------: | --------------: |
| [f01938721](https://filfox.info/en/address/f01938721)       | Hong Kong, Central and Western, HK |         476.94 TiB |     12.35% |  476.88 TiB |           0.01% |
| [f01938718](https://filfox.info/en/address/f01938718)       |    Morrisville, North Carolina, US |         472.25 TiB |     12.23% |  472.22 TiB |           0.01% |
| [f01938717](https://filfox.info/en/address/f01938717)       |           Singapore, Singapore, SG |         470.78 TiB |     12.19% |  470.78 TiB |           0.00% |
| [f01938665](https://filfox.info/en/address/f01938665)       |     Sham Shui Po, Sham Shui Po, HK |         469.03 TiB |     12.15% |  469.00 TiB |           0.01% |
| [f01938714](https://filfox.info/en/address/f01938714)       |     Sham Shui Po, Sham Shui Po, HK |         466.31 TiB |     12.08% |  466.31 TiB |           0.00% |
| [f01852023](https://filfox.info/en/address/f01852023)       |                   Busan, Busan, KR |         334.50 TiB |      8.66% |  334.50 TiB |           0.00% |
| [f01852325](https://filfox.info/en/address/f01852325)       | Hong Kong, Central and Western, HK |         329.41 TiB |      8.53% |  329.41 TiB |           0.00% |
| [f01852677](https://filfox.info/en/address/f01852677)       |    Morrisville, North Carolina, US |         322.81 TiB |      8.36% |  322.81 TiB |           0.00% |
| [f01852664](https://filfox.info/en/address/f01852664)       |           Singapore, Singapore, SG |         304.59 TiB |      7.89% |  304.59 TiB |           0.00% |
| [f01851482](https://filfox.info/en/address/f01851482)       |                   Busan, Busan, KR |         213.78 TiB |      5.54% |  213.78 TiB |           0.00% |
| [f01969202](https://filfox.info/en/address/f01969202)`new`  |     Sham Shui Po, Sham Shui Po, HK |         192.00 GiB |      0.00% |  192.00 GiB |           0.00% |

![Provider Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/852/1671097826648.png)
### Deal Data Replication
The below table shows how each many unique data are replicated across storage providers.
- No more than 25% of unique data are stored with less than 4 providers.

✔️ Data replication looks healthy.

| Unique Data Size | Total Deals Made | Number of Providers | Deal Percentage |
| ---------------: | ---------------: | ------------------: | --------------: |
|       384.00 GiB |       384.00 GiB |                   1 |           0.01% |
|         4.59 TiB |         9.19 TiB |                   2 |           0.24% |
|        52.72 TiB |       158.16 TiB |                   3 |           4.10% |
|       269.53 TiB |         1.05 PiB |                   4 |          27.93% |
|       522.72 TiB |         2.55 PiB |                   5 |          67.70% |
|        96.00 GiB |       864.00 GiB |                   8 |           0.02% |
|        32.00 GiB |       320.00 GiB |                   9 |           0.01% |

![Replication Distribution](https://raw.githubusercontent.com/data-preservation-programs/filplus-checker-assets/main/filecoin-project/filecoin-plus-large-datasets/issues/852/1671097827257.png)
### Deal Data Shared with other Clients
The below table shows how many unique data are shared with other clients.
Usually different applications owns different data and should not resolve to the same CID.

✔️ No CID sharing has been observed.

[^1]: To manually trigger this report, add a comment with text `checker:manualTrigger`

**Comment by cryptowhizzard** [comment]
Greetings,

I have been doing retrievals on this application but i could not do any except for the demo data. The rest of the deals are inaccessible due the SP's timing out or not open.

[f01948527.log](https://github.com/filecoin-project/filecoin-plus-large-datasets/files/10418085/f01948527.log)

Can you also tell me why f0155049-14 is involved? I don't understand the relationship.


<img width="708" alt="Scherm­afbeelding 2023-01-14 om 16 49 51" src="https://user-images.githubusercontent.com/36404435/212480751-971b90ef-fb6b-4648-a3c7-d95d73a181c7.png">
<img width="709" alt="Scherm­afbeelding 2023-01-14 om 16 49 39" src="https://user-images.githubusercontent.com/36404435/212480755-0ebe1124-6efe-4080-9fbd-97f7af3fbe4c.png">
<img width="359" alt="Scherm­afbeelding 2023-01-14 om 16 48 29" src="https://user-images.githubusercontent.com/36404435/212480757-ab7e39d5-cdcd-43da-a1e8-b98198e19977.png">

**Comment by cryptowhizzard** [comment]
I am also interested in the relationship between what you store above and say to be storing here:

Our data includes
  1 User clicks log
  2 Advertising analysis logs
  3 Advertising big data recommendation of each country
  Because some of the materials involve customer privacy, it is inconvenient to show them in detail here. This is a screenshot of the amount of material displayed at part of the time. We confirm that a lot of storage space is required.

https://user-images.githubusercontent.com/109211726/183399725-a74b50ff-59e0-4ec6-a637-be4a791aee0d.png
http://www.boom-ad.cn/private/datareport2022.png
https://www.boom-ad.cn/dataview/data.zip
But we will not store private data.
For contractual and security reasons, customer-related data will only be stored in our own data center.

**Comment by C00kies77** [comment]
checker:manualTrigger
