### ISSUE TITLE
[DataCap Application]HARDA GROUP

### ISSUE THREAD

**Issue by hardagroup** [filecoin-project/filecoin-plus-large-datasets#853]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: HARDA GROUP
- Website / Social Media:http://www.hardagroup.com/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):2 PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):100TiB
- On-chain address for first allocation:f1ggivof4biip7zfye3haq5shrruh6ch2tzgayena

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Established in 1994, HARDA Group is one of Intel® IMMA LEAGUE members, with its headquarters in an UN Livable City and also Garden City, Xiamen China. The Group is a comprehensive platform with not just one stop service of product design & development, manufacturing, sales and total solutions, but also a vertical integrated Incubator of Innovating, Venture and Accelerating. All of the needed work during EVT, DVT and PVT, including Industrial design, Mechanical design, Prototyping, Hardware/Software design, DFM, Tooling, Injection molding, Extrusion, Compression, Welding, Painting, SMT, Assembly and Testing etc can be managed by the group. Client bases varies from large OEMs/ODMs to chain retailers and branding channels in the industries of mobile phones, cutting-edge electronics, smart home, BLE devices, Bluetooth wireless audio devices, medical & beauty devices, robots and home appliances etc.
HARDA will continue to invest in cutting-edge technology innovation and insist market& customer-oriented and focused on management. With innovation as driver, information as carrier and core competitiveness as root, we strive to be an excellent world class platform of developing leading products &solutions together with venture and accelerating incubation.

```

What is the primary source of funding for this project?
```
The company is self-financed
```

What other projects/ecosystem stakeholders is this project associated with?
```
No.
```

## Use-case details

Describe the data being stored onto Filecoin
```
Product design, production pictures and videos, promotional materials in the process of marketing, pictures and videos of the company and its partners' activities, and other public information that can be made public.
```

Where was the data in this dataset sourced from?
```
All stored data can be stored publicly, and are produced in the company's production, sales, after-sales, and business cooperation.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://drive.google.com/drive/folders/1Gg2b8Sv5gHvUK3-aK1gL5MAhpO0qxgjR?usp=sharing
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes，we Confirm
```

What is the expected retrieval frequency for this data?
```
1-2 times a year.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
permanent.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
China, Asia, Europe, etc. can be.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
offline.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
I will  find SPs on Filecoin slack and Filgram.
And welcome strong service providers to contact us.
```

How will you be distributing deals across storage providers?
```
We hope that more storage service providers will cooperate, and each service provider will store no more than 25% of the data.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
We have sufficient funds to prepare, we do not need help at present, if necessary, we will contact the foundation in time.
```

**Comment by jessie8o8** [comment]
Hello @hardagroup. I see that in your brief history description of the application, your company is an `Intel® IMMA LEAGUE members`. Could you explain what that means? A [google search](https://www.google.com/search?q=Intel%C2%AE+IMMA+LEAGUE&rlz=1C1VDKB_enUS946US946&ei=3DkIY-r4E_TWkPIPifaNkA0&ved=0ahUKEwjq1oinxOP5AhV0K0QIHQl7A9IQ4dUDCA4&uact=5&oq=Intel%C2%AE+IMMA+LEAGUE&gs_lcp=Cgdnd3Mtd2l6EAMyBQghEKABMgUIIRCgAToHCAAQRxCwAzoKCAAQRxCwAxDJAzoICAAQkgMQsAM6BQgAEJECOgUIABCABEoECEEYAEoECEYYAFD7BFilMGCBNWgBcAF4AIABkgGIAZQCkgEDMC4ymAEAoAEBoAECyAEJwAEB&sclient=gws-wiz) of it tells me that it doesnt exist but perhaps I'm missing something.

**Comment by hardagroup** [comment]
> Hello @hardagroup. I see that in your brief history description of the application, your company is an `Intel® IMMA LEAGUE members`. Could you explain what that means? A [google search](https://www.google.com/search?q=Intel%C2%AE+IMMA+LEAGUE&rlz=1C1VDKB_enUS946US946&ei=3DkIY-r4E_TWkPIPifaNkA0&ved=0ahUKEwjq1oinxOP5AhV0K0QIHQl7A9IQ4dUDCA4&uact=5&oq=Intel%C2%AE+IMMA+LEAGUE&gs_lcp=Cgdnd3Mtd2l6EAMyBQghEKABMgUIIRCgAToHCAAQRxCwAzoKCAAQRxCwAxDJAzoICAAQkgMQsAM6BQgAEJECOgUIABCABEoECEEYAEoECEYYAFD7BFilMGCBNWgBcAF4AIABkgGIAZQCkgEDMC4ymAEAoAEBoAECyAEJwAEB&sclient=gws-wiz) of it tells me that it doesnt exist but perhaps I'm missing something.

hi,@jessie8o8
Please use Baidu Chinese search“英特尔众创联盟”
![image](https://user-images.githubusercontent.com/111366804/186843608-7cf8eddc-1be2-4631-8fdf-6bb841e1058d.png)
http://www.mnw.cn/keji/internet/985798.html（News website）
At the Intel Makerspace Accelerator Summit held on September 15 in 2015, Intel announced the formation of the Makerspace Alliance. At present, Intel has established cooperative relations with more than 20 industrial partners in 12 cities in China, among which 8 makerspaces have been jointly listed.HARDA Group is one of them.

**Comment by Sunnyiscoming** [comment]
Can you provide more data samples related with the data you will store?Can you explain your data composition and provide sufficient data samples separately? How many copies will you store?
What's the relationship between you and organization?
Can you provide more detailed information about storage providers participated in this program, such as you can list SPs you have contacted with at present?

**Comment by hardagroup** [comment]
> Can you provide more data samples related with the data you will store?Can you explain your data composition and provide sufficient data samples separately? How many copies will you store? What's the relationship between you and organization? Can you provide more detailed information about storage providers participated in this program, such as you can list SPs you have contacted with at present?

hi,@Sunnyiscoming 
I am the head of HARDA GROUP responsible for the brand, specifically responsible for the FIL+ storage project.
The data stored this time is mainly related information about products, mainly videos.
https://drive.google.com/drive/folders/1SP45Kqv8CW8_G83gpA07nXyP-64-d5mf?usp=sharing
Below are the media accounts of our brands:
https://space.bilibili.com/318081722/video?tid=0&page=3&keyword=&order=pubdate
https://www.youku.com/profile/index/?spm=a2h0c.8166622.PhoneSokuUgc_4.3&uid=UNTkzMjg5MzIzMg==
https://www.douyin.com/user/MS4wLjABAAAAG1Ysh6TK3sF3hPd49QLhoXZTvupo3VzDjgBk8zM0RS0
For data security, at least 6 copies of the stored data need to be saved this time.
For storage providers distribution, we have contacted the following SPs:
f0152799,
f01579009,
f01681808,
f01137150.
We are still actively looking for more high-quality SPs. We promise that we will abide by the rules of FIL+, and the storage of a single SP does not exceed 25%.
Thanks.

**Comment by Sunnyiscoming** [comment]
Whether these storage providers support data retrieval?
Could you send an email to filplus-app-review@fil.org with your official domain in order to confirm your identity? Email name should includes the issue id #853.

**Comment by Sunnyiscoming** [comment]
No email received. Any update here?

**Comment by hardagroup** [comment]
> Whether these storage providers support data retrieval? Could you send an email to [filplus-app-review@fil.org](mailto:filplus-app-review@fil.org) with your official domain in order to confirm your identity? Email name should includes the issue id #853.

Yes，we support retrieval.
Since it is a holiday, we will send an email confirmation as soon as possible.

**Comment by Sunnyiscoming** [comment]
Any update here?

**Comment by Sunnyiscoming** [comment]
Close for no reply. You can open another new application if you want to continue.
