### ISSUE TITLE
[DataCap Application] <Organization> - <Project Name>

### ISSUE THREAD

**Issue by dflangy** [filecoin-project/filecoin-plus-large-datasets#854]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Oriental Friendship Film & Media (Beijing) Co.
- Website / Social Media:http://www.dfliangyou.com/index.html
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):3PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):200TiB
- On-chain address for first allocation:f1unyhkaxuepdlgyyzlr2s5tanav7y7oz5xaarqgy

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Ein Unternehmen, das nicht nur als Film- und Fernsehproduktions- und Museums-Multimediaproduktionsagentur einflussreich in der Branche ist, sondern auch eine offene Kooperationsplattform für die dreidimensionale Verbreitung von exzellenter Kultur, Weisheit und Denken im Zeitalter aller Medien.
```

What is the primary source of funding for this project?
```
Leistungseinkommen des Unternehmens und Beitrag der Aktionäre
```

What other projects/ecosystem stakeholders is this project associated with?
```
Läuft unabhängig und hat keine Beziehung zu anderen Projekten
```

## Use-case details

Describe the data being stored onto Filecoin
```
Wir möchten alle Filme des Unternehmens, Dokumentarfilme, verschiedene Tics und alle Informationen und Materialien, die bei der Produktion der Arbeit verwendet werden, speichern
```

Where was the data in this dataset sourced from?
```
Es geht um die Daten, die bei der Produktion unserer Filme, Dokumentarfilme, Werbespots usw. sowie während des Betriebs des Unternehmens anfallen.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://drive.google.com/drive/folders/13YmJqOj19FRtBP5u55yPxWrh4fbsxOUr?usp=sharing
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Ja, öffentliche Daten, die von allen abgerufen werden können
```

What is the expected retrieval frequency for this data?
```
Selten, etwa einmal alle zwei Jahre
```

For how long do you plan to keep this dataset stored on Filecoin?
```
Wahrscheinlich über 30 Jahre oder mehr
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
China
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Online- und Offline-Überweisungen werden ebenfalls genutzt
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
Erstens, ein großer und angesehener Anbieter
```

How will you be distributing deals across storage providers?
```
Gleichmäßige Verteilung an die Bergleute
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Ja, wir verfügen über ausreichende Mittel und Ressourcen
```

**Comment by raghavrmadya** [comment]
The application is asking for higher weekly allocation without justification. Please open a new application with as much justification as possible including at least 10 data samples.
