### ISSUE TITLE
[DataCap Application] Koolearn Technology Holding Limited

### ISSUE THREAD

**Issue by LouellaYokum** [filecoin-project/filecoin-plus-large-datasets#855]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Koolearn Technology Holding Limited
- Website / Social Media:https://www.koolearn.com/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):2PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):200TiB
- On-chain address for first allocation:f1x67ke7bmjudkdqgfienq3wlzbi2rzpbz63gsely

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Koolearn is the professional online education website of New Oriental Education & Technology Group (NYSE:EDU), a famous private comprehensive education institution in China and listed on the New York Stock Exchange. Since its launch in 2000, New Oriental Online has become a powerful online education service platform and a leading online education brand for foreign language training in China.
```

What is the primary source of funding for this project?
```
I'm sorry, that's not easy to say.
```

What other projects/ecosystem stakeholders is this project associated with?
```
None
```

## Use-case details

Describe the data being stored onto Filecoin
```
As you can see, we are a private educational institution and the data is mainly videos of instructional courses and introductory videos for students to study.
```

Where was the data in this dataset sourced from?
```
The data comes from regional libraries, partner institutions and videos compiled by our instructors
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://drive.google.com/drive/folders/12NAgbLAXPhtso-b6I4T43g-ogkk5yXF3?usp=sharing
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes
```

What is the expected retrieval frequency for this data?
```
About 1 to 2 times a year
```

For how long do you plan to keep this dataset stored on Filecoin?
```
Permanent
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
China
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
We use both online and offline transfers
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We give preference to storage providers who have the time and stability of a supplier and who are well funded and understand project data.
```

How will you be distributing deals across storage providers?
```
We will use IPFS distributed storage for fair distribution to miners.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
We have sufficient funds and resources and do not need any help for the time being.
```

**Comment by raghavrmadya** [comment]
The application is asking for higher weekly allocation without justification. Please open a new application with as much justification as possible including at least 10 data samples.
