### ISSUE TITLE
[DataCap Application] <Triangle Development> - <Myverse>

### ISSUE THREAD

**Issue by mikelee17916** [filecoin-project/filecoin-plus-large-datasets#857]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Triangle BigData Development Co., Ltd.
- Website / Social Media: https://www.3circles.io
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 2.5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 50TiB
- On-chain address for first allocation: f1rros7ulvqjnhrft5gz6bpihzoimjn5xn2lvn7bq

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Myverse is a metaverse industry platform developed by our company that integrates social interaction, entertainment, creation and tourism. We hope to help more companies go digital, so that more companies can build a digital industry ecosystem with deep integration of virtual reality and mutual empowerment.
```

What is the primary source of funding for this project?
```
Self-financing.
```

What other projects/ecosystem stakeholders is this project associated with?
```
No.
```

## Use-case details

Describe the data being stored onto Filecoin
```
3D models of Myverse (unity engine, material, texture etc.)、NFTs、videos、images etc.
```

Where was the data in this dataset sourced from?
```
Our project about Myverse.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://drive.google.com/drive/folders/1e2sKOl2O8ZANRYL0vSlal7lxcv6l4j9p?usp=sharing
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Confirm.
```

What is the expected retrieval frequency for this data?
```
Not fixed.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
5 years at least.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Aisa.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Online or Offline.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We pay attention to their work time and how much they cost. We need comprehensive storage providers who can cooperate for a long time.
```

How will you be distributing deals across storage providers?
```
We will assign different deals based on their distance.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes we have enough funding.
```

**Comment by raghavrmadya** [comment]
Provide as much information as possible on Myverse. Low confidence that 5 PiB request is legitimate. Deadline to provide this information is 1 week.

**Comment by jessie8o8** [comment]
The sample dataset is not original 
![image](https://user-images.githubusercontent.com/90115194/186806323-007e0355-7e80-4227-9bfb-054e5a07d389.png)
Your dataset folder: https://drive.google.com/drive/folders/16pKZTSYaADNv6EYMI7AHdyjW5zgSs0Jv?usp=sharing
Source of some of the images:https://www.behance.net/gallery/63976457/Schneider-Electric

Because that was not truly original and was stolen art, I do not believe this organization is legitimate

**Comment by mikelee17916** [comment]
Dear raghavrmadya 
Sorry for the late reply. Thank you for your interest in our Myverse project.
Since the project is still in the internal testing stage, we asked the company's R&D team to provide some video of scenes under development in the past two days. It is not very mature, but it is very interesting.
https://drive.google.com/drive/folders/1QwXktKPBAqJXFMHjWjY8d10uOfSXrfn4
Just lik Modeling transformation of avator; Scene and map effects; Online meeting for a meeting or exhibition; Scene interaction interactive chat effect. We are expanding the entire project now.

Myverse is currently under development and internal testing. We currently have a large amount of model data (such as architectural models, character models, scene models, and too many auxiliary models and other materials) and scenes files that need to be periodically backed up and stored.
At present, it has been as high as a few. With the iteration of the version, we need to store more and more backup files.

Myverse needs a metaverse world  that never disappears; it must be stored in a decentralized storage such as filecoin; we will spend more time with filecoin storage providers to cooperate with storage to maximize our Myverse project.

**Comment by mikelee17916** [comment]
Dear jessie
Sorry, it was our fault that our art colleagues did not remove the reference when they provided the file. We have corrected and we have provided our sample data.  All copyrights are our creativity now. And We also update some of the our NFT sample. Don't happen again.
https://drive.google.com/drive/folders/1e2sKOl2O8ZANRYL0vSlal7lxcv6l4j9p
https://drive.google.com/drive/folders/1DJRsGqmODheelQuhzThWfJ8dTASjLkgu

**Comment by mikelee17916** [comment]
> Provide as much information as possible on Myverse. Low confidence that 5 PiB request is legitimate. Deadline to provide this information is 1 week.

Dear raghavrmadya
Sorry for the late reply. Thank you for your interest in our Myverse project.
Since the project is still in the internal testing stage. We asked the company's R&D team to provide some video of scenes under development in the past two days. It is not very mature, but it is very interesting.
https://drive.google.com/drive/folders/1QwXktKPBAqJXFMHjWjY8d10uOfSXrfn4
Just like Modeling transformation of avator; Scene and map effects; Online meeting for a meeting or exhibition; Scene interaction interactive chat effect. We are expanding the entire project now.

Myverse is currently under development and internal testing. We currently have a large amount of model data (such as architectural models, character models, scene models, and too many auxiliary models and other materials) and scenes files that need to be periodically backed up and stored.
At present, it has been as high as a few. With the iteration of the version, we need to store more and more backup files.

Myverse needs a metaverse world that never disappears. it must be stored in a decentralized storage such as filecoin. we will spend more time with filecoin storage providers to cooperate with storage to maximize our Myverse project.

**Comment by mikelee17916** [comment]
> The sample dataset is not original ![image](https://user-images.githubusercontent.com/90115194/186806323-007e0355-7e80-4227-9bfb-054e5a07d389.png) Your dataset folder: https://drive.google.com/drive/folders/16pKZTSYaADNv6EYMI7AHdyjW5zgSs0Jv?usp=sharing Source of some of the images:https://www.behance.net/gallery/63976457/Schneider-Electric
> 
> Because that was not truly original and was stolen art, I do not believe this organization is legitimate

@jessie8o8 
Dear jessie
Sorry, it was our fault that our art colleagues did not remove the reference when they provided the file. We have corrected and we have provided our sample data. All copyrights are our creativity now. And We also update some of the our NFT sample. Don't happen again.
https://drive.google.com/drive/folders/1e2sKOl2O8ZANRYL0vSlal7lxcv6l4j9p
https://drive.google.com/drive/folders/1DJRsGqmODheelQuhzThWfJ8dTASjLkgu

**Comment by Sunnyiscoming** [comment]
How many copies will you store?
What's the relationship between you and organization?
Can you provide more detailed information about storage providers participated in this program, such as you can list SPs you have contacted with at present?
Could you send an email to filplus-app-review@fil.org with your official domain in order to confirm your identity? Email name should includes the issue id #857.

**Comment by mikelee17916** [comment]
> How many copies will you store? What's the relationship between you and organization? Can you provide more detailed information about storage providers participated in this program, such as you can list SPs you have contacted with at present? Could you send an email to [filplus-app-review@fil.org](mailto:filplus-app-review@fil.org) with your official domain in order to confirm your identity? Email name should includes the issue id #857.

@Sunnyiscoming 

Dear Sunny.

I Communicate with our R&D team today. We mainly store a large number of 3d model files and pictures. We plan to back up our data to save or store in storage space, such as unity3D, 3DS Max, Maya files, for examples. Like Metaverse FBX Legacy animation based on 3D engine, massive material DDS, local network GLB model, etc. All projects to be researched when creating or constructing Metaverse.

We should be able to use less capacity than this, so I updated the usage and resubmitted the DataCap 2.5PiB total and the DataCap 50TiB DataCap weekly allocation. In the future, Metaverse will never disappear, and there will be massive amounts of data.

I'm just the company's IT staff. Our products are always evolving, and we hope to help our project continue to do better through the massive distributed storage of filecoin.

This is an introduction to filecoin by a friend of mine in Hongkong. If there is an application, we will know more about him, or you can recommend a good storage provider.

I have sent it to your designated filplus-app-review@fil.org email via my personal company email mike.lee@3circles.io. Please check my email and really hope to be recognized. Thanks!
![Confirm email](https://raw.githubusercontent.com/mikelee17916/myverse/main/321664259224_.pic.jpg)

**Comment by Sunnyiscoming** [comment]
Any update here?

**Comment by mikelee17916** [comment]
Hey @raghavrmadya @Sunnyiscoming  We have some primary data including 3D scenes and NFT will be backed up in filecoin. If our project is ok, please reply to us to check whether it can pass. Thanks

**Comment by Sunnyiscoming** [comment]
Large datasets are open to existing open datasets. For your current needs, it is recommended that you directly apply to notaries. https://plus.fil.org/verifiers

**Comment by mikelee17916** [comment]
> Large datasets are open to existing open datasets. For your current needs, it is recommended that you directly apply to notaries. https://plus.fil.org/verifiers

Hey @raghavrmadya @Sunnyiscoming

Our company has applied on August 25, and has been waiting for the official approval to upload the data in the next step.
According to the materials we provided during this period if there is no problem .Or your can officially agree to apply signature for  the original LDN process. After the quota will be allocated by a notary's signature.
Looking forward to your reply, thanks again.

**Comment by mikelee17916** [comment]
@Sunnyiscoming @raghavrmadya 
We submitted this LDN application as early as August, and we see that many other LDN applications applied in August have been approved. Our company now has 3D models of Myverse (unity engine, material, texture etc.), NFTs, videos, images and other data to upload. If there is any other material needed, we will make up for it. Or your  can through our application. Thank you.

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 2.5PiB

**Expected weekly DataCap usage rate**

> 50TiB

**Client address**

>f1rros7ulvqjnhrft5gz6bpihzoimjn5xn2lvn7bq

**Comment by Sunnyiscoming** [comment]
Hey @mikelee17916 , if you still want to apply for datacap, you can ask notaries to do client due diligence in slack channel. https://app.slack.com/client/TEHTVS1L6/C036JKD8NVA/thread/C03BG1MNQ4T-1673888660.823499
